### ISSUE TITLE
Add support for Go input plugins

### ISSUE THREAD

**Issue by jasonkeene** [fluent/fluent-bit#1001]
**Is your feature request related to a problem? Please describe.**

Right now it is not possible to specify an input plugin implemented in Go.

**Describe the solution you'd like**

It should be possible.

**Comment by bluebike** [comment]
I guess that idea of fluent-bit is to be simple c-based program with few dependencies (!?)

**Comment by jasonkeene** [comment]
fluent-bit currently supports dynamic linking for output plugins written in Go. Adding the same kind of support for input plugins and filters would not add any dependencies. In fact the existing code that supports input plugins doesn't really add any dependencies, unless you consider `dlfcn.h` a dependency.

**Comment by czerasz** [comment]
was also mentioned here https://github.com/fluent/fluent-bit-go/issues/16
