### ISSUE TITLE
Add support for Go filter plugins

### ISSUE THREAD

**Issue by jasonkeene** [fluent/fluent-bit#1002]
**Is your feature request related to a problem? Please describe.**

Right now it is not possible to specify a filter plugin implemented in Go.

**Describe the solution you'd like**

It should be possible.

**Comment by jamesgoodhouse** [comment]
I whole heartedly endorse this idea! I've been poking around the code quite a bit, and while I kind of understand what is happening, without additional documentation or some nudges in the right direction, I have no idea how to start tackling the implementation of this. 

Relevant files are as follows:

- https://github.com/fluent/fluent-bit/tree/master/src/proxy/go
- https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_plugin_proxy.h
- https://github.com/fluent/fluent-bit/blob/master/src/flb_plugin_proxy.c
- https://github.com/fluent/fluent-bit/blob/1188110a3cf66b02a26a71c4796f22e25d937709/GOLANG_OUTPUT_PLUGIN.md
