### ISSUE TITLE
MessagePack support for in_tcp plugin

### ISSUE THREAD

**Issue by Behoston** [fluent/fluent-bit#1027]
I'm trying to use libraries that supports Fluentd to forward logs to fluent-bit. 
I must use JSON format (which is not supported by some forwarders). 

I think that TCP input plugin should accept both JSON and MessagePack format to be compatible with Fluentd.

**Comment by cosmo0920** [comment]
We can accept JSON and Msgpack format with in_tcp in Fluentd v1 like as:

### For Msgpack

```aconf
<source>
  @type tcp
  port 24225
  tag tcp.test
  <parse>
    @type msgpack
  </parse>
</source>
<match **>
  @type stdout
</match>
```

### For JSON

```aconf
<source>
  @type tcp
  port 24225
  tag tcp.test
  <parse>
    @type json
  </parse>
</source>
<match **>
  @type stdout
</match>
```

You can check this configuration with `netcat`:

```
% cat Gemfile
source 'https://rubygems.org/'

gem "msgpack"

# For msgpack
% bundle exec ruby -rmsgpack -e 'puts ({"name":"Mike","age":27}).to_msgpack' | netcat 127.0.0.1 24225
# For JSON
% echo {"name":"Mike","age":27}| netcat 127.0.0.1 24225
```

**Comment by edsiper** [comment]
@Behoston Since the last version TCP input plugin supports JSON and payloads with a specific delimiter string.

For Msgpack you can use our [Forward](https://docs.fluentbit.io/manual/input/forward) input plugin that speaks Msgpack (indeed is the Fluentd protocol).
