### ISSUE TITLE
rpm upgrade overwrites exsiting config settings

### ISSUE THREAD

**Issue by JungleGenius** [fluent/fluent-bit#1031]
Updating from package td-agent-bit.x86_64 0:1.0.1-1 to package td-agent-bit.x86_64 0:1.0.2-1 overwrites parsers.conf and td-agent-bit.conf.

Expected behavior is to preserve the existing config files and their settings. 

e.g.  parsers.conf.rpmnew td-agent-bit.conf.rpmnew etc.

**Comment by chsnell** [comment]
This appears to be a Duplicate of #980

**Comment by JungleGenius** [comment]
Agree sorry about that.
