### ISSUE TITLE
FileSystem Buffering.

### ISSUE THREAD

**Issue by gauravcdac** [fluent/fluent-bit#1046]
## Bug Report

Filesystem Buffering not works:
This is my config file.

[SERVICE]
    Flush           5
    Daemon          off
    Log_Level       trace
    **Buffer_Path     /opt/protegrity/defiance_dps/data/
    Buffer_Workers  2**
    Mem_Buf_Limit   10MB

[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Tag         pty_insight_audits
    Port        15780
    Chunk_Size  32
    Buffer_Size 64

[FILTER]
    Name filter_pty_aggregator
    Match pty_insight_audits
    duplicate_check_key operation
    duplicate_check_key dataelement
    duplicate_check_key username
    duplicate_check_key time_utc
    duplicate_field_aggregate count

[OUTPUT]
    Name forward
    Match *
    Retry_Limit False
    Host 10.37.1.80
    Port 15650

Successfully buffered logs in a specified folder but not getting transferred to the destination.
Please suggest

**Comment by gauravcdac** [comment]
I have used the fluentbit 0.14.9 version and I am using file buffering by using Buffer_path option in services plugin. I am able to store logs in a specified directory but the logs are not getting transferred to the destination.
Please suggest me something

**Comment by edsiper** [comment]
that old buffering mechanism is deprecated, please upgrade to v1.0.3 and use the proper setup:

https://docs.fluentbit.io/manual/configuration/buffering

**Comment by gauravcdac** [comment]
I have upgraded fluentbit and  working on filesystem buffering with fluentbit 1.0.3 latest version and my logs files are created successfully in a specified directory but those logs are not getting transferred to destination.
Please find the fluentbit configuration for the same. Please suggest me what i am doing wrong.

[SERVICE]
    Flush           1
    Daemon          off
    Log_Level       trace
    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 10M


[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Tag         pty_insight_audits
    Port        15780
    storage.type  filesystem
    Chunk_Size  32
    Buffer_Size 64
    Routes      forward


[OUTPUT]
    Name forward
    Match *
    Retry_Limit False
    Host 10.37.1.80
    Port 15650

**Comment by edsiper** [comment]
are you facing the same issue after upgrade to v1.0.4 ?

**Comment by edsiper** [comment]
ping
