### ISSUE TITLE
in_tail: Docker_Mode can't recombine split lines if second part is the first line in a file after rotation

### ISSUE THREAD

**Issue by decayofmind** [fluent/fluent-bit#1055]
## Bug Report

**Describe the bug**
Docker_Mode can't recombine a split line if second part of the line is a first row at the beginning of the log file after rotation.

**To Reproduce**

- Deploy to Kubernetes
- Ensure `--log-opt max-size` is set to 1M for example
- Enable Docker_Mode in tail input plugin configuration
- Create a test pod, which will echo HTTP POST data to STDOUT
- Start feeding the pod with JSON data lines greater than 16KB (90KB for example), so Docker engine will need to split them:

```
{"message": <90KB of text>, "level": "INFO"}
```
- Filter messages in Kibana by _"level doesn't exist"_ and notice some unparsed parts exact at the time, where Docker has rotated the pod's log file.

**Expected behavior**
Tail input plugin with Docker_Mode on, recombines long lines even if log file was rotated.

**Your Environment**
* Version used: 1.0.3
* Configuration:
```
    [SERVICE]
        Flush          1
        Grace          10
        Daemon         Off
        Log_Level      info
        Parsers_File   parsers.conf
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_Port      2020
        storage.path   /var/log/flb-storage/
        storage.sync   full
        storage.checksum on
        storage.backlog.mem_limit 5M

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        Skip_Long_Lines   On
        Mem_Buf_Limit     5MB
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   256k
        Rotate_Wait       6
        Refresh_Interval  10
        Docker_Mode       On
        Docker_Mode_Flush 10
        DB                /tail-db/tail-containers-state.db
        DB.Sync           Normal
        storage.type      filesystem

    [FILTER]
        Key_Name            log
        Match               kube.*
        Name                parser
        Parser              json
        Reserve_Data        True

    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log      On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-client
        Port            9200
        Index           fluentbit
        Logstash_Format On
        Logstash_Prefix fluentbit
        Time_Key        @timestamp
        Retry_Limit     False
```
* Environment name and version:  Docker 18.06.1-ce, Kubernetes 1.11.5

**Comment by pmorelli92** [comment]
I am still having this issue, anyone has a way to workaround it?

**Comment by pmorelli92** [comment]
Sorry to tag you directly, but maybe @edsiper can help us?

**Comment by gmflore** [comment]
I'm facing the same issue on fluent-bit 1.7.2

**Comment by gregsterin** [comment]
Did anyone find a workaround to this? Just encountered the same issue, is causing a small percentage of my logs to be randomly unparsable :-(

**Comment by pmorelli92** [comment]
No workaround. We just live with some logs getting unparsable.

**Comment by hhamalai** [comment]
I've tested this also with 1.7.7

**Comment by hhamalai** [comment]
this one still randomly causes issues with huge log events
