### ISSUE TITLE
build folder is missing

### ISSUE THREAD

**Issue by eldad87** [fluent/fluent-bit#1067]
## Bug Report

**Describe the bug**
The `build` folder is missing on master, which contradict the setup instructions listed on the README file.

**Comment by jpgonzalez1985** [comment]
hi boys, i have the same issue on Dockerfile, any news?

**Comment by cosmo0920** [comment]
This will be fixed via https://github.com/fluent/fluent-bit/pull/1173.

**Comment by agup006** [comment]
This should be fixed, closing
