### ISSUE TITLE
Memory leak in kubernetes filter when using  K8S-Logging.Exclude: true

### ISSUE THREAD

**Issue by hectorhuertas** [fluent/fluent-bit#1068]
## Bug Report

**Describe the bug**
It seems that there's a memory leak in kubernetes filter when using `K8S-Logging.Exclude  true`

**To Reproduce**
Run `fluent-bit` with the kubernetes filter using `K8S-Logging.Exclude  true`, for example with the configuration below

**Expected behavior**
Memory usage stays constant with constant load

**Screenshots**
Memory consumption of the last 30 hours of a daemon set with the configuration below using `K8S-Logging.Exclude  true`:
![image](https://user-images.githubusercontent.com/13817763/51978296-1ea92880-248a-11e9-99ce-927bc45d2ea6.png)

Same configuration without `K8S-Logging.Exclude  true`:
![image](https://user-images.githubusercontent.com/13817763/51978233-ed305d00-2489-11e9-8af8-af635d8c7852.png)

Those two screenshots are from a testing environment with a simple configuration while debugging the problem. Here is a 7 day screenshot of one of our production fluent-bit daemonset before and after removing `K8S-Logging.Exclude  true` from our configuration:
![image](https://user-images.githubusercontent.com/13817763/51978525-b4dd4e80-248a-11e9-8eec-5947bee94281.png)

**Your Environment**
* Version used: v1.0.3
* Configuration:
```
    [SERVICE]
        Flush         1
        Log_Level     error
        HTTP_Server   On
        HTTP_Port     8080

    [INPUT]
        Name              tail
        Tag               kube-container.*
        Path              /var/log/containers/*.log
        DB                /var/log/flbi_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                 kubernetes
        Match                kube-container.*
        K8S-Logging.Exclude  true

    [OUTPUT]
        Name         stdout
        Match        kube-container.*
```

Running on Kubernetes v1.12.3 on top of CoreOS stable (1911.4.0)

**Comment by edsiper** [comment]
Fixed by a4947b75f09217385a17932a0b2d94d767fe6727 on GIT master

I will backport the fix for v1.0.4 release (today).
