### ISSUE TITLE
out_http: support https proxy

### ISSUE THREAD

**Issue by whoard** [fluent/fluent-bit#1069]

**Comment by whoard** [comment]
Is your feature request related to a problem?
I saw in documentation that it's currently not supported:
![image](https://user-images.githubusercontent.com/15133597/52000687-fe935c80-24bd-11e9-9a50-9ae90aa99747.png)
 
i also tried it, and getting SSL errors and can't connect to https proxy.

Describe the solution you'd like

Describe alternatives you've considered

Additional context

**Comment by jesk78** [comment]
What is the purpose of sending HTTPS through a proxy? Security by obscurity?

**Comment by moeryomenko** [comment]
> What is the purpose of sending HTTPS through a proxy? Security by obscurity?

What's wrong with sending HTTPS through a proxy? 

> https proxy is needed to send the data/logs outside the private secured environment, having tls as added security is typically a must.

HTTP data is not protected. Explain your position

**Comment by moeryomenko** [comment]
@jesk78 sorry, I was wrong.
>  You also don't want QUIC?

but don't understand.

@whoard, why don't you sending logs to proxy via HTTP, and outside the environment via HTTPS?
