### ISSUE TITLE
is_json_escape() does not handle all JSON escapes

### ISSUE THREAD

**Issue by fhoy** [fluent/fluent-bit#1074]
**Describe the bug**
The function `is_json_escape()` in file `flb_unescape.c` does not handle all escaped JSON characters. According to http://json.org/, the list of escaped characters is `"`, `\`, `/`, `b`, `f`, `n`, `r` and `t`. Currently, `is_json_escape()` does not handle `b`, `f`, `r` and `t`.

**Comment by edsiper** [comment]
thanks for raising this issue. Fixed by 25a6b7ea3c7c125f11845c68e01b221982a5ad9e
