### ISSUE TITLE
filter_kubernetes: Exclude annotation not working

### ISSUE THREAD

**Issue by chiefy** [fluent/fluent-bit#1075]
## Bug Report

**Describe the bug**
When adding the annotation 

```
  annotations:
    fluentbit.io/exclude: "true"
```

On a DaemonSet or Deployment, the Kubernetes filter is not picking up and the logs from the pod are still processed.

**To Reproduce**
Here is a log from a fluent-bit pod, note that the proper annotation is listed but the log is still output....

```
609] kube.fluent-bit-bhmzh_logging_fluent-bit-97e39bd431670e79a57cd97208abc23a573b91fc3d351deda61d417f18a9cf72.log: [1549030585.216855326, {"log"=>"[633] kube.fluent-bit-bhmzh_logging_fluent-bit-97e39bd431670e79a57cd97208abc23a573b91fc3d351deda61d417f18a9cf72.log: [1549030584.121173090, {"log"=u003e"", "stream"=u003e"stdout", "time"=u003e"2019-02-01T14:16:23.010635711Z", "kubernetes"=u003e{"pod_name"=u003e"fluent-bit-bhmzh", "namespace_name"=u003e"logging", "pod_id"=u003e"f227eca8-262b-11e9-8a9c-0af5b7f74a1c", "labels"=u003e{"app"=u003e"fluent-bit-logging", "controller-revision-hash"=u003e"1345808614", "kubernetes.io/cluster-service"=u003e"true", "pod-template-generation"=u003e"1"}, "annotations"=u003e{"fluentbit.io/exclude"=u003e"true", "prometheus.io/path"=u003e"/api/v1/metrics/prometheus", "prometheus.io/port"=u003e"2020", "prometheus.io/scrape"=u003e"true"}, "host"=u003e"ip-10-205-182-192.ec2.internal", "container_name"=u003e"fluent-bit", "docker_id"=u003e"97e39bd431670e79a57cd97208abc23a573b91fc3d351deda61d417f18a9cf72"}, "hostname"=u003e"fluent-bit-bhmzh", "cluster_name"=u003e"najewicc"}]
```

- Steps to reproduce the problem:
  * Run fluent-bit as a DaemonSet or Deployment w/ proper annotation, use this config chain:

```
  [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube-system.db
        Mem_Buf_Limit     30MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```

```
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Merge_Log_Trim      On
        K8S_Logging.Exclude On
```

```
  [OUTPUT]
        Name            stdout
        Match           *
```

**Expected behavior**
Logs from the fluent-bit pods do not appear in stdout

**Your Environment**
* Version used: Fluent-bit 1.0.3
* Environment name and version (e.g. Kubernetes? What version?): K8s 1.11 (EKS)

**Additional context**
Trying to exclude logging pods from logging their own logs which results in a memory leak and eventually kills the pods.

**Comment by edsiper** [comment]
You have a typo, the property is called _k8s-logging.exclude_ (not K8S_Logging.Exclude)

**Comment by chiefy** [comment]
Yeah, actually that's because I tried `K8S-Logging.Exclude` `K8s_Logging_Exclude` etc. none of them worked should it be lowercase?

**Comment by edsiper** [comment]
here is the code: https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_conf.c#L239

**Comment by chiefy** [comment]
Ok, sorry - I can't seem to reproduce this now. Must've been user-error 🤦‍♂️
