### ISSUE TITLE
[OSX] Unable to build 1.0.4. Make failed at Building LuaJIT 2.1.0-beta3 step

### ISSUE THREAD

**Issue by hexwit** [fluent/fluent-bit#1082]
## Bug Report

**Description**
Unable to build 1.0.4 version on OSX.

**To Reproduce**
- Download and extract tarball fluent-bit-1.0.4.tar.gz
- Run cmake ../ in the build directory
- Run make in the build directory

**Actual behavior**
Got error during build process: 
```
Scanning dependencies of target luajit
[  2%] Creating directories for 'luajit'
[  3%] No download step for 'luajit'
[  3%] No patch step for 'luajit'
[  3%] No update step for 'luajit'
[  3%] Performing configure step for 'luajit'
[  4%] Performing build step for 'luajit'
==== Building LuaJIT 2.1.0-beta3 ====
LINK      luajit
Undefined symbols for architecture x86_64:
  "__Unwind_DeleteException", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_GetCFA", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_RaiseException", referenced from:
      _lj_err_throw in libluajit.a(lj_err.o)
  "__Unwind_SetGR", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
  "__Unwind_SetIP", referenced from:
      _lj_err_unwind_dwarf in libluajit.a(lj_err.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [luajit] Error 1
make[3]: *** [default] Error 2
make[2]: *** [luajit-prefix/src/luajit-stamp/luajit-build] Error 2
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
```

**Environment**
* Version used: 1.0.4
* Operating System and version: OSX Mojave

**Comment by brightzheng100** [comment]
Save issue here in `master` or `git checkout 1.0`, in my MacBook Pro.

OS: macOS Mojave v10.14.4
cmake: 3.14.1
make: GNU Make 3.81

**Comment by frankreno** [comment]
Does anyone have a workaround for this?

**Comment by edsiper** [comment]
maybe related to this ?

https://github.com/LuaJIT/LuaJIT/issues/484

**Comment by cosmo0920** [comment]
I'd found that this could be caused by lack of specifying `MACOSX_DEPLOYMENT_TARGET` environment variable explicitly.
This issue could be fixed at https://github.com/fluent/fluent-bit/pull/3622/commits/eac7deb8374325860ad63d3021e4c1b6f6c317af.
