### ISSUE TITLE
Fluent-bit and nginx error.log escaping problem

### ISSUE THREAD

**Issue by alwinmarkcf** [fluent/fluent-bit#1083]
## Bug Report

**Describe the bug**

I'm actually quite confused that I'm having so much problem with this and I couldn't find a solutions to this problem, so maybe this is just a bad usage by myself.

I'm having a nginx deployed on a bare (VM) host. There I installed a fluent-bit agent which should get the nginx error logs (/var/log/nginx/error.log)

As I can't change the error log format, I'm pretty sure everybody should have the same problems as I have. In fact the Problem is, that the Group Extractor does not care about quotes and just leaves them as they are.

**To Reproduce**

To reproduce, just create a logfile somewhere with this content (You may want to change the date and time to the current one):

```
2019/02/04 17:32:32 [error] 30672#0: *881 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:24224, upstream: "10.0.102.10:24224", bytes from/to client:0/0, bytes from/to upstream:0/0
```

Then you have to set INPUT Plugin to:
```
[INPUT]
    Name  tail
    Parser nginx_error
    Path  /var/log/nginx/error.log

```
while creating a new Parser:
```
[PARSER]
    Name     nginx_error
    Format   regex
    Regex    ^(?<time>\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}) \[(?<log_level>\w+)\] (?<pid>\d+).(?<tid>\d+): (?<message>.*)$ 
    Time_Key time
    Time_Format %Y/%m/%d %H:%M:%S
```
I basically used the Regex from: https://docs.fluentd.org/v0.12/articles/common-log-formats

I also kept the stdout OUTPUT plugin for debugging purposes because my forwarding agent seems to ignore the result the fluent-bit agent is sending to him via fluentd protocol:

```
[OUTPUT]
    Name stdout
    Match *
```

What I'm seeing then in the output is:
```
[440] tail.1: [1549300874.000000000, {"log_level"=>"error", "pid"=>"30669", "tid"=>"0", "message"=>"*875 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:24224, upstream: "10.0.102.14:24224", bytes from/to client:0/0, bytes from/to upstream:0/0", "hostname"=>" ACC-MGMT-PROXY-01", "product"=>" nginx"}] 
```
You may notice, that the `message` value is unescaped and so this isn't valid json.

**Expected behavior**

I'd expect that the output is:
```
[440] tail.1: [1549300874.000000000, {"log_level"=>"error", "pid"=>"30669", "tid"=>"0", "message"=>"*875 upstream timed out (110: Connection timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:24224, upstream: \"10.0.102.14:24224\", bytes from/to client:0/0, bytes from/to upstream:0/0", "hostname"=>" ACC-MGMT-PROXY-01", "product"=>" nginx"}] 
```

**Screenshots**

**Your Environment**

* Version used: td-agent-bit.x86_64            1.0.3-1                @centos75-x86_64-fluentbit
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): VM
* Server type and version: Proxmox VM also I installed:
   ```
   yum list installed | grep nginx
   nginx.x86_64                   1:1.12.2-2.el7         @centos75-x86_64-epel     
   nginx-all-modules.noarch       1:1.12.2-2.el7         @centos75-x86_64-epel     
   nginx-filesystem.noarch        1:1.12.2-2.el7         @centos75-x86_64-epel     
   nginx-mod-http-geoip.x86_64    1:1.12.2-2.el7         @centos75-x86_64-epel     
   nginx-mod-http-image-filter.x86_64
   nginx-mod-http-perl.x86_64     1:1.12.2-2.el7         @centos75-x86_64-epel     
   nginx-mod-http-xslt-filter.x86_64
   nginx-mod-mail.x86_64          1:1.12.2-2.el7         @centos75-x86_64-epel     
   nginx-mod-stream.x86_64        1:1.12.2-2.el7         @centos75-x86_64-epel  
   ```
* Operating System and version: CentOS Linux release 7.5.1804 (Core)
* Filters and plugins: see above everything else is vanilla

**Additional context**

I guess this is a general problem, when the field delimiters are not `"` and the message value/content could include `"`.

**Comment by mattpeople** [comment]
Message to future people:

## Working Regex

the monster regex above doesn't parse as a valid fluent-bit regex (for me at least?), but I got this working instead:

```Regex ^(?<timestamp>\d{4}/\d{2}/\d{2}\ \d{2}:\d{2}:\d{2})\ \[(?<severity>emerg|alert|crit|error|warn|notice|info)\]\ (?<process_id>\d+)\#(?<thread_id>\d+):\ \*(?<connection_id>\d+)\ (?<error>.+?)(?:\ while\ (?<context>.+?))?,\ client:\ (?<client_ip>\d+\.\d+\.\d+\.\d+),\ server:\ (?<server>.+?)(?:,\ request:\ "(?<request_method>[A-Z]+?)\ (?<request_path>\/.+?)\ (?<request_protocol>.+?)")?(?:,\ upstream:\ "(?<upstream>.+?)")?(?:,\ host:\ "(?<host>.+?)")?(?:,\ referrer:\ "(?<referrer>.+?)")?$```


## Working Config

so now here's my `parsers-errorlog.conf` (just include via another `parsers_file parsers-errorlog.conf` declaration under `[SERVICE]`):

```
[PARSER]
    Name nginx_errorlog
    Format regex

    # using: https://regex101.com/library/oPEqMk (converted to ruby regex by replacing '?P' with just '?')   
                         
    Regex ^(?<timestamp>\d{4}/\d{2}/\d{2}\ \d{2}:\d{2}:\d{2})\ \[(?<severity>emerg|alert|crit|error|warn|notice|info)\]\ (?<process_id>\d+)\#(?<thread_id>\d+):\ \*(?<connection_id>\d+)\ (?<error>.+?)(?:\ while\ (?<context>.+?))?,\ client:\ (?<client_ip>\d+\.\d+\.\d+\.\d+),\ server:\ (?<server>.+?)(?:,\ request:\ "(?<request_method>[A-Z]+?)\ (?<request_path>\/.+?)\ (?<request_protocol>.+?)")?(?:,\ upstream:\ "(?<upstream>.+?)")?(?:,\ host:\ "(?<host>.+?)")?(?:,\ referrer:\ "(?<referrer>.+?)")?$
```
