### ISSUE TITLE
in_tail: Tag_Regex should match the full path instead of filename

### ISSUE THREAD

**Issue by easeway** [fluent/fluent-bit#1084]
## Bug Report

**Describe the bug**
I'm migrating a system from using fluentd to fluent-bit, however I found `Tag_Regex` matches only the filename. With fluentd, the tag can be specified using information from [full path](https://docs.fluentd.org/v1.0/articles/in_tail#tag). In my system, it's difficult to embed the information into filename, and the kubernetes filter can only parse the metadata from the tag (so Path_Key from tail plugin doesn't work). 

**To Reproduce**

The logs are written to a file with information embedded in a directory:

```
/var/log/foo/podname_namespace_container-cntrid/bar.log
```

Using a fluent-bit config:

```
[INPUT]
    Name tail
    Path /var/log/foo/*/*.log
    Tag_Regex (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
```

It complains:

```
[2019/02/04 11:38:30] [error] [in_tail] invalid pattern for given file bar.log
```

**Expected behavior**

The tag should be generated successfully with information parsed from the full path.

**Your Environment**
* Version used: 1.0.4
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.11
* Operating System and version: Debian 9
* Filters and plugins: tail, kubernetes

**Additional context**

The [code](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.c#L631) explicitly removes the path components using `basename`. Is it possible to do a quick fix not using `basename` that enables more use cases like in my system?

**Comment by easeway** [comment]
An alternative could add one more parameter to kubernetes filter plugin:

```
Parse_From_Key
```

It specifies the key as specified in tail plugin `Path_Key`, instead of Tag, so the metadata is extracted from the full path.

I prefer this approach as it's more flexible.

**Comment by easeway** [comment]
Please let me know which one is preferred, and I can send a PR for that.

**Comment by congliu01** [comment]
I think it's a common pattern to embed some metadata in the file path and then tag the log based on the metadata. And since Fluentbit doesn't support tag_rewrite right now, just having the `Path_Key` doesn't help with routing based on tags. Therefore I believe that the tail plugin should use the full file path as the tag.

**Comment by sporkmonger** [comment]
In a case that I have, some logs end up in `/var/deploy/logs/*/current` where `*` is the service name, so this would be helpful to me too.

**Comment by jcuna** [comment]
Any updates on this?

**Comment by iamacarpet** [comment]
Google Cloud has migrated from fluentd to fluent-bit and we're having the exact same problem.

Has anyone got any advice on how to work around this in the meantime?

@easeway you mention `Parse_From_Key`: is this something that can be used in existing versions?

If so, do you have an example of its usage please?

**Comment by liguangcheng** [comment]
has anyone can extract meta data in the file path? Isn't this a very commonly used feature? It's been four years since this feature has been implemented:(

**Comment by guisan79** [comment]
> has anyone can extract meta data in the file path? Isn't this a very commonly used feature? It's been four years since this feature has been implemented:(

I'm using version 2.0.8 and Tag_Regex works parsing the full path, after that you can per example use a Lua filter like shown here https://docs.fluentbit.io/manual/pipeline/filters/lua#code-examples to extract the tag and append it to the log record.

**Comment by liguangcheng** [comment]
@guisan79 thank for your advice, and sorry respond later, I study the fluent-bit and found that Lua filter [plugin](https://docs.fluentbit.io/manual/pipeline/filters/lua) can help to extract  meta information in the file path
