### ISSUE TITLE
filter_kube failing to match regex tags.

### ISSUE THREAD

**Issue by mgherman** [fluent/fluent-bit#1092]
## Bug Report

**Describe the bug**
The kubernetes filter logs errors indicating that it is unable to match tags when using Tag_Regex on the input.

```[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
[2019/02/07 21:50:09] [ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-svxfr.fluent-bit
```

**To Reproduce**
Updated input configuration from:
```        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```

To:
```       Name              tail
        Tag               kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```

**Expected behavior**
I was expecting to be able to apply filters on a per container-name basis, matching against the Tag, however even with the additional filter removed, the errors persist.

**Your Environment**

* Version used: 1.0.4
* Configuration:
The configuration prior to making the change outlined above.
```
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude True
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-splunk.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  output-splunk.conf: |
    [OUTPUT]
        Name            splunk
        Match           *
        Host            ${FLUENT_SPLUNK_HOST}
        Port            ${FLUENT_SPLUNK_PORT}
        Splunk_Token    ${FLUENT_SPLUNK_TOKEN}
        TLS             Off
        TLS.Verify      Off
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.11.5:
* Operating System and version: Ubuntu 16.04

**Additional context**
Im looking to set the sourcetype for different container logs prior to shipping them to Splunk, using something along the lines of

```
[FILTER]
  Name modify
  Match kube.*k8s-svc
  Add sourcetype k8s_application_x
```

**Comment by mikesphar** [comment]
I got the same error until I added `.*` to the end of the new tag.  I believe the kubernetes filter plugin uses a regex against the tag to extract namespace and pod information so that it can query more information from the API.

**Comment by mikesphar** [comment]
Fwiw I got this working last night. I needed to craft a custom regex parser to give to the kubernetes filter so that it would know how to get the fields it needs from my new custom tag.

```
    [INPUT]
        Name              tail
        # namespace_name, container_name, pod_name, docker_id must be present in the tag
        # as they are required by the kubernetes filter
        # This regex cribbed from https://github.com/fluent/fluent-bit/blob/v1.0.2/plugins/filter_kubernetes/kube_regex.h#L25
        Tag_Regex         (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Tag               k8s_containers.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        DB.Sync           Normal
        Mem_Buf_Limit     256MB
        Skip_Long_Lines   On
        Refresh_Interval  2
```

```
    [FILTER]
        Name           kubernetes
        Match          k8s_containers.**
        Merge_Log      On
        Annotations    On
        tls.verify     Off
        Regex_Parser   k8s-custom-tag
```

```
    [PARSER]
        # Kubernetes filter must be able to parse these fields out of the tag to work
        Name    k8s-custom-tag
        Format  regex
        Regex   ^k8s_containers\.(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})-$
```

I do agree that I wish there was a simpler way to rewrite the tag to accommodate routing without needing complex custom regex parsers.

**Comment by mgherman** [comment]
Thanks @mikesphar with these changes everything is working as I had hoped.

**Comment by mailtoraja18** [comment]
Exact same configuration on 1.0.4 wont work for me. The kubernetes plugin seems to skip. Anything more to it that what i see ?
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              k8s_containers.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
        Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$

    [FILTER]
        Name                kubernetes
        Match               k8s_containers.*
        Regex_Parser        k8s-custom-tag

    [PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   ^k8s_containers\.(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})-$

**Comment by jdeprin** [comment]
In 1.2.2 ... if anyone stumbles on this thread, the following will work.  You still need to specify the `Kube_Tag_Prefix` and there is a slight change to the Parser Regex.
```
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
        Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On

[FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.
        Regex_Parser        k8s-custom-tag
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

[PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   ^(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})-$


```

**Comment by smirgel** [comment]
Anyone have a solution for pods in kube-system namespace that don't match the regex pattern? Some pods (kube-proxy, kube-scheduler etc) have the hostname as suffix instead.

**Comment by smirgel** [comment]
Ok if you actually read the upgrade notes it works:
https://docs.fluentbit.io/manual/installation/upgrade_notes#kubernetes-filter-1

**Comment by linbingdouzhe** [comment]
> In 1.2.2 ... if anyone stumbles on this thread, the following will work. You still need to specify the `Kube_Tag_Prefix` and there is a slight change to the Parser Regex.
> 
> ```
>     [INPUT]
>         Name             tail
>         Path             /var/log/containers/*.log
>         Parser           docker
>         Tag              kube.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
>         Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
>         Refresh_Interval 5
>         Mem_Buf_Limit    5MB
>         Skip_Long_Lines  On
> 
> [FILTER]
>         Name                kubernetes
>         Match               kube.*
>         Kube_Tag_Prefix     kube.
>         Regex_Parser        k8s-custom-tag
>         Kube_URL            https://kubernetes.default.svc:443
>         Merge_Log           On
>         K8S-Logging.Parser  On
>         K8S-Logging.Exclude On
> 
> [PARSER]
>         Name    k8s-custom-tag
>         Format  regex
>         Regex   ^(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})-$
> ```

facing same error on 1.5.0 
that config file doesn't work

**Comment by senvardarsemih** [comment]
Hi, in 1.6.0 I configured the tail plugin down below : 
```
    [INPUT]
        Name              tail
        Tag               <container_name>-<namespace_name>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Parser            docker
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Refresh_Interval  1
        Docker_Mode       On 
```

How can I configure the Kubernetes filter for enriching log data with Kubernetes metadata? Non-working filter and custom parser sample here:
```
    [FILTER]
        Name                kubernetes
        Match               *
        Kube_Tag_Prefix     *
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Regex_Parser        k8s-custom-tag
        Merge_Log           On
        Annotations         On 
```
```
    [PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   ^(?<container_name>[^_]+)\-(?<namespace_name>.+)
```
