### ISSUE TITLE
Maximum number of attempt in caso of failure

### ISSUE THREAD

**Issue by pierluigilenoci** [fluent/fluent-bit#1098]
**Is your feature request related to a problem? Please describe.**
In the event of an error when sending logs to elasticsearch, there are two possible behaviors: the log is discarded or fluentbit continues indefinitely to try to send it again. In case the log is a malformed json ES will never accept it and the pod tries to send it to infinity. (ex: https://github.com/wongnai/kube-slack/issues/51 )

**Describe the solution you'd like**
I would like to be able to configure the maximum number of attempts to send before discarding and possibly be able to configure an alternative destination of the logs that can not be sent. (es: S3, log folder...)

**Describe alternatives you've considered**
Actually we use "fluentbit.io/exclude: true" annotation on pod that generates malformed json to avoid this problem.

**Comment by pierluigilenoci** [comment]
@edsiper could you please take a look?

**Comment by pierluigilenoci** [comment]
@edsiper could you please take a look?

**Comment by pierluigilenoci** [comment]
@edsiper this is still an issue. Can you please reopen it?

**Comment by leonardo-albertovich** [comment]
Hi @pierluigilenoci, isn't this something you would do with retries? In any case, I was under the impression that in those cases elasticsearch returned a different HTTP status code that was honored by fluent-bit. 

Is this still happening in fluent-bit 2.1 and fluent-bit 2.0?
