### ISSUE TITLE
Reduce excessive info logging in out_http

### ISSUE THREAD

**Issue by lbogdan** [fluent/fluent-bit#1141]
**Is your feature request related to a problem? Please describe.**

Currently, the `out_http` plugin does excessive info logging, in my opinion, logging a line like
```
[$dateTime] [ info] [out_http] $host:$port, HTTP status=$status
```
for every successful request. That (uselessly) fills up docker logs when running in a pod inside a kubernetes cluster, and also has the side-effect of a "logging amplification loop" if collecting the `fluent-bit` container logs, and not filtering the above mentioned lines, where every logged line will generate a `fluent-bit` log line that will be logged in turn.

**Describe the solution you'd like**

I'd suggest to change the log level of those successful requests from `info` to `debug`.

If you think that's a reasonable request, I can open a PR.

**Comment by wfernandes** [comment]
We noticed this too. Since we have metrics to determine the number of records consumed, I think it is sufficient to have this be in DEBUG mode if the payload and status information is required for troubleshooting.

**Comment by edsiper** [comment]
log_level can be used on every plugin on versions >= 1.4
