### ISSUE TITLE
in_tail: cleaning up obsolete offsets from DB

### ISSUE THREAD

**Issue by wkuranowski** [fluent/fluent-bit#1143]
I am using fluent-bit to tail Docker logs (--max-file=2). I see that DB file with offsets grows without limits. 
There are multiple entries for rotated files XXXXX.log.1 and only one entry for a current file XXXXX.log.
Is there any good practice for cleaning this DB? Are you going to add cleaning functionality to fluent-bit?

I really appreciate any help you can provide.

**Comment by edsiper** [comment]
Label as an enhancement request.

**Comment by edsiper** [comment]
FYI: this was already addressed . closing.
