### ISSUE TITLE
GELF doesn't support log level 7

### ISSUE THREAD

**Issue by lbogdan** [fluent/fluent-bit#1164]
## Bug Report

**Describe the bug**

Although [7 is a valid syslog severity level](https://en.wikipedia.org/wiki/Syslog#Severity_level), `fluent-bit` errors when reading `systemd` logs generated by the kernel, and converting them to GELF:
```
[2019/03/01 16:40:09] [error] [flb_msgpack_to_gelf] level is '7�log�<e820: update [mem 0x00000000-0x00000fff] usable ==> reserved��', but should be in 0..6
```

**Steps to reproduce the problem**
Use systemd input, ingest kernel logs, get the above error.

**Expected behavior**
Logs ingested, no error.

**Your Environment**
* Version used: latest (1.0.4)
* Configuration: systemd input, http/gelf output

It also looks like there's a bug when logging the invalid log level - `7�log�<e820: update [mem 0x00000000-0x00000fff] usable ==> reserved��` instead of just `7`.

**Comment by yonchin** [comment]
fluent-bit errors when reading systemd logs generated by the kubelet, and converting them to GELF: 
```
[2019/04/30 17:51:12] [error] [flb_msgpack_to_gelf] level is 40, but should be in 0..7
[2019/04/30 17:51:12] [error] [out_gelf] error encoding to GELF
```
