### ISSUE TITLE
[filter_parser] Preserve_Key not working

### ISSUE THREAD

**Issue by jamesgoodhouse** [fluent/fluent-bit#1168]
## Bug Report

**Describe the bug**
The `Preserve_Key` configuration parameter for the Parser Filter does to appear to work at all.

**To Reproduce**
`fluent-bit.conf`:
```
[SERVICE]
    Parsers_File  parser-data.conf

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        somedata
    Preserve_Key  On

[INPUT]
    Name   dummy
    Dummy  {"log":"data=something"}

[OUTPUT]
    Name   stdout
    Match  *
```

`parser-data.conf`:
```
[PARSER]
    Name    somedata
    Format  regex
    Regex   data=(?<data>something)$
```

Log output:
`dummy.0: [1551738784.003213200, {"data"=>"something"}]`

**Expected behavior**
The expected output is exactly what's in the documentation; "Keep original Key_Name field in the parsed result. If false, the field will be removed.".

Expected log output:
`dummy.0: [1551739102.102112300, {"data"=>"something", "log"=>"data=something"}]`

**Screenshots**
N/A

**Your Environment**

* Version used: 1.0.4 (Docker version)
* Operating System and version: MacOS
* Filters and plugins: Parser filter

**Additional context**
N/A

**Comment by jamesgoodhouse** [comment]
One thing to note is that if I use `Reserve_Data` it seems to work fine, but this is not what `Reserve_Data` is meant for. It's meant to keep *other* keys in the parsed output. The `Preserve_Key` config param is meant to keep the `Key_Name` field specifically.

**Comment by singhjagmohan1000** [comment]
@jamesgoodhouse please check the fluent-bit version you are using. 'Preserve_Key' is introduced in version `1.0`. If you are using older version of fluent-bit like `0.14` it won't work.

**Comment by invin12** [comment]
Yes, Preserve_Key still not working in version 1.0.6
Here is a config from documentation
**cat parsers.conf** 
[PARSER]
    Name dummy_test
    Preserve_Key On
    Format regex
    Regex ^(?<INT>[^ ]+) (?<FLOAT>[^ ]+) (?<BOOL>[^ ]+) (?<STRING>.+)$

**[root@test ~]# cat dummy.conf** 
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name dummy
    Tag  dummy.data
    Dummy {"data":"100 0.5 true This is example", "key1":"value1", "key2":"value2"}

[FILTER]
    Name parser
    Match dummy.*
    Key_Name data
    Parser dummy_test

[OUTPUT]
    Name stdout
    Match *
**[root@test ~]# td-agent-bit -c dummy.conf** 
Fluent Bit v1.0.6
Copyright (C) Treasure Data

[2019/04/25 10:49:44] [ info] [storage] initializing...
[2019/04/25 10:49:44] [ info] [storage] in-memory
[2019/04/25 10:49:44] [ info] [storage] normal synchronization mode, checksum disabled
[2019/04/25 10:49:44] [ info] [engine] started (pid=28951)
[0] dummy.data: [1556178585.000244687, {"INT"=>"100", "FLOAT"=>"0.5", "BOOL"=>"true", "STRING"=>"This is example"}]
[1] dummy.data: [1556178586.000393278, {"INT"=>"100", "FLOAT"=>"0.5", "BOOL"=>"true", "STRING"=>"This is example"}]
[2] dummy.data: [1556178587.000119245, {"INT"=>"100", "FLOAT"=>"0.5", "BOOL"=>"true", "STRING"=>"This is example"}]
[3] dummy.data: [1556178588.000129312, {"INT"=>"100", "FLOAT"=>"0.5", "BOOL"=>"true", "STRING"=>"This is example"}]
^C[engine] caught signal (SIGINT)
[2019/04/25 10:49:51] [ info] [input] pausing dummy.0

**Comment by adejongh** [comment]
Confirmed - same behaviour.  The Preserve_Key in the FILTER does nothing at all, whereas the Reserve_Data does send the original data along.

**Comment by nvanheuverzwijn** [comment]
It also does not work for me.
I use version 1.0.6.

**Comment by roemsi** [comment]
It is not working on version 1.1.

Seems Preserve_Data is without any function

**Comment by thiago** [comment]
This only works for me when I put the two flags together with `On` in the FILTER section:

```
[FILTER]
    Name parser
    Preserve_Key On
    Reserve_Data On
    Match dummy.*
    Key_Name data
    Parser dummy_test
```

If the `Reserve_Data` is `Off`, the `Preserve_Key` don't work!


I don't know how they should works but in the docs say to put it in the PARSER section and it only work in the FILTER when putting together.

I tested this with docker image `1.0.4`

**Comment by ohdearaugustin** [comment]
This is still a problem in ```1.3.6``` under Debian Stretch installed from  ``` deb https://packages.fluentbit.io/debian/stretch stretch main ```

```
 [FILTER]
     Name parser
     Alias nginx-access.json
     Match nginx-access.log
     Key_Name message
     Parser nginx-access
     Reserve_Data On
     Preserve_Key On
```

**Comment by sisiliao** [comment]
It's still not working in fluent-bit docker container.
![image](https://user-images.githubusercontent.com/29511668/78255496-56b05f00-74c5-11ea-9143-b8687e0a3c4d.png)

**Comment by nokute78** [comment]
Hi everyone.

`Preserve_key` seems to be ignored when `Reserve_data` is off.
Here is all cases and I have two questions.

1. Should we support case 2  or fix document ?
2. What is the expected behavior of case 2 ? (e.g. The output should be `{"data":"something", "log":"data=something"` Just remove "other" pair.)

## Behavior of v1.4.2

incoming data is
```
{"log":"data=something", "other":"other"}
```

|case|Reserve_data|Preserve_key|Output|Note|
|-----|--------------|--------------|--------|------|
|1|off(=default)|off(=default)|`{"data":"something"}`|(default behavior)|
|2|off| on |`{"data":"something"}` |**The point of this issue.** same as case 1.|
|3|on | off | `{"data":"something", "other":"other"}` |Parsed pair was removed.|
|4|on|on|`{"data":"something", "log":"data=something", "other":"other"}`|All original pairs are preserved.|

### configuration file
```
[SERVICE]
    Parsers_File  parser-data.conf

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        somedata
    reserve_data  on
    Preserve_key  on

[INPUT]
    Name   dummy
    Dummy  {"log":"data=something", "other":"other"}

[OUTPUT]
    Name   stdout
    Match  *
```

parser-data.conf
```
[PARSER]
    Name    somedata
    Format  regex
    Regex   data=(?<data>something)$
```

**Comment by Blobonat** [comment]
Using the `fluent/fluentd:v1.12.0-debian-1.0` Docker Image the problem still exits.

```
<filter **>
  @type parser
  key_name log
  reserve_data true
  preserve_key false
  <parse>
    @type json
  </parse>
</filter>
```

The original key is kept in the logs.
