### ISSUE TITLE
Windows builds fail because of missing "build" folder

### ISSUE THREAD

**Issue by lbogdan** [fluent/fluent-bit#1171]
For some reason, the `build` folder was removed in https://github.com/fluent/fluent-bit/commit/3ea3f24765c3ddc0c066c4feeb2f6e5ec96f52b1#diff-95d5ed7be50898d89384de6991e86642 , which makes the AppVeyor Windows builds fail with

![image](https://user-images.githubusercontent.com/2083930/53808950-3ded1700-3f5c-11e9-83a0-70e359d7b1f7.png)

PR https://github.com/fluent/fluent-bit/pull/1169 tries to address this by creating the folder from the build script, but the `build` folder is also referred to in `README.md`: https://github.com/fluent/fluent-bit/blame/master/README.md#L14 .

**Comment by fujimotos** [comment]
@lbogdan Sorry, this is my bug. I've submitted a patch that reintroduce
`build/.empty` at #1173 and this issue should be gone.

**Comment by fujimotos** [comment]
@lbogdan @edsiper 

Sorry, it's my fault. Evidently I deleted the file inadvertently
while crafting the patch 3ea3f24.

I just have submitted a patch that fixes it at #1173, and appveyor
should run fine with it merged.

**Comment by edsiper** [comment]
Fixed
