### ISSUE TITLE
Possible regression in elasticsearch output

### ISSUE THREAD

**Issue by mwasserschaff** [fluent/fluent-bit#1174]
## Bug Report

**Describe the bug**
It seems that after v1.0.4 a regression was introduced on master. When building fluent-bit from latest master (as of March 3, 2019), integration with elasticsearch is degraded, as fluent-bit emits warnings to stdout

**To Reproduce**
- build fluent-bit from master
- ./fluent-bit -i stdin -o es -p Host=elasticsearch -p Port=9200
- elasticsearch 6.5.3

Even with very low rate of json-formatted logs piped to fluent-bit, I see the follwoing warnings on standard out/err.
```
myapp    | [2019/03/06 09:46:52] [ warn] [out_es] Elasticsearch error
myapp@myhost    | {"took":13,"errors":false,"items":[{"index":{"_index":"fluent-bit","_type":"flb_type","_id":"sfpmUmkBZg4ql2hjBlDg","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1447,"_primary_term":1,"status":201}},{"index":{"_index":"fluent-bit","_type":"flb_type","_id":"svpmUmkBZg4ql2hjBlDg","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1465,"_primary_term":1,"status":201}}]}
myapp    | [2019/03/06 09:47:02] [ warn] [out_es] Elasticsearch error
myapp@myhost   | {"took":3,"errors":false,"items":[{"index":{"_index":"fluent-bit","_type":"flb_type","_id":"ufpmUmkBZg4ql2hjLVDw","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1513,"_primary_term":1,"status":201}},{"index":{"_index":"fluent-bit","_type":"flb_type","_id":"uvpmUmkBZg4ql2hjLVDw","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1481,"_primary_term":1,"status":201}}]}
```
Despite above warnings, some log message end up in elasticsearch.

- Steps to reproduce the problem:

**Expected behavior**
No warnings produced by fluent-bit. When going back to tag v1.0.4, the behaviour is normal.

**Your Environment**
- fluentbit master b1f95a3a4d8a0ad6160cb290933220ce8fc2f268 compiled in container:

```
FROM "docker.io/openjdk:11.0.1-jre-slim" as builder

RUN apt-get update &&  apt-get --assume-yes install gcc git cmake g++
RUN git clone https://github.com/fluent/fluent-bit.git /tmp/fluent-bit
RUN mkdir -p /tmp/fluent-bit/build
RUN cd /tmp/fluent-bit/build && cmake .. && make
# line below causes the warnings to go away.
# RUN cd /tmp/fluent-bit/build && git checkout v1.0.4 && cmake .. && make
 
```

**Comment by donbowman** [comment]
see https://github.com/fluent/fluent-bit/pull/1148 which should resolve

**Comment by edsiper** [comment]
fixed by #1148

**Comment by pathikritmodak** [comment]
Are we looking to release a new version with the above fix?

**Comment by edsiper** [comment]
a new version is coming out today
