### ISSUE TITLE
mem input plugin: useless Mem.free metric reported

### ISSUE THREAD

**Issue by ppizzo** [fluent/fluent-bit#1194]
The `mem` input plugin reports free memory values without considering buffers/cache. A typical Linux system tends to use all the memory available with buffers/cache but that memory should be considered free for applications.

For example, consider the following output of the `free` command on a 8GB Linux machine:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           7.8G        3.3G        333M        170M        4.2G        3.9G
```
as you can see, the used is 3.3G even if there's only 333M in the free metric. This because most of buffers/cache should be considered free as well.

Looking in the source code of the mem plugin, I noticed that the used metric is calculated by subtracting free from total, so in the above example the used would be 7.8GB - 0.3GB = 7.5GB, but the real used memory is actually less (in the example 3.3GB).

In my opinion, to be more useful, the used memory should be extracted directly from the system instead of calculated in that way; or add an additional key with real used value for backward compatibility.

Many thanks for your support.
Pietro

**Comment by nigels-com** [comment]
See also: https://github.com/fluent/fluent-bit/pull/1617

**Comment by nigels-com** [comment]
Came across this too.  Seems like parsing `/proc/meminfo` is the way to incorporate the cache information, but we might need `sysinfo` if that path isn't viable (say, on Mac).

**Comment by nigels-com** [comment]
Will revisit, fell off my radar.

**Comment by iborko** [comment]
Reported Mem.free is useless and makes it impossible to calculate real RAM usage. These issues should have higher priority, because debugging memory issues on the machine is an important problem, as the full RAM will cause services on the machine to get killed.

`sysinfo` struct from the kernel offers these values:
```c
           struct sysinfo {
               long uptime;             /* Seconds since boot */
               unsigned long loads[3];  /* 1, 5, and 15 minute load averages */
               unsigned long totalram;  /* Total usable main memory size */
               unsigned long freeram;   /* Available memory size */
               unsigned long sharedram; /* Amount of shared memory */
               unsigned long bufferram; /* Memory used by buffers */
               unsigned long totalswap; /* Total swap space size */
               unsigned long freeswap;  /* Swap space still available */
               unsigned short procs;    /* Number of current processes */
               char _f[22];             /* Pads structure to 64 bytes */
           };
```

Input plugin contains the following code
https://github.com/fluent/fluent-bit/blob/b02cb1032ea0744eafb6fa83b45897a12e9e8edf/plugins/in_mem/mem.c#L101-L109

but instead, it should be something like:
```c
    m_info->mem_total     = calc_kb(info.totalram, info.mem_unit);

    m_info->mem_free      = calc_kb(info.freeram, info.mem_unit);
    m_info->mem_shared    = calc_kb(info.sharedram, info.mem_unit);
    m_info->mem_buffers   = calc_kb(info.bufferram, info.mem_unit);

    m_info->mem_available      = m_info->mem_free + m_info->mem_shared + m_info->mem_buffers;
    m_info->mem_used           = m_info->mem_total - m_info->mem_available;
```

**Comment by pierrebeaucamp** [comment]
In case this is useful to anyone else, you can replace the `mem` input with an `exec` quite easily, something like the following:

```
   [INPUT]
       name           exec
       command        free | sed -n '2p' | awk '{printf("{\"Mem\":{\"total\":%d, \"used\":%d, \"free\":%d, \"available\":%d}}", $2, $3, $4, $7)}'
       parser         json
```

**Comment by mittermayr** [comment]
This is the YAML variation in case anyone needs it (60 second interval, with CPU and accurate memory):

```
pipeline:
  inputs:
    - name: cpu
      tag: cpu.local
      interval_sec: 60

    - name: exec
      tag: memory
      interval_sec: 60
      command: free | sed -n '2p' | awk '{printf("{\"Mem\":{\"total\":%d, \"used\":%d, \"free\":%d, \"available\":%d}}", $2, $3, $4, $7)}'
      parser: json
```
