### ISSUE TITLE
Support for File Input (in_tail)

### ISSUE THREAD

**Issue by chamilad** [fluent/fluent-bit#121]
I could not find any documentation on how to read a log file like how fluentD does to output to elasticsearch on fluent-bit. In my case, there's already a stdout that I'm processing using fluentD (in Kubernetes). I'm trying to read some additional log files inside a pod using a pod volume.  

Is this feature supported? Is it been targeted for a release in the near future?

**Comment by edsiper** [comment]
in_tail plugin it's in work in process, as well a plugin to gather Kubernetes metadata, it should be ready in a couple of weeks.

**Comment by chamilad** [comment]
Thanks @edsiper ! Looking forward to test it.

**Comment by edsiper** [comment]
in_tail plugin code already merged in Master:

https://github.com/fluent/fluent-bit/tree/master/plugins/in_tail

Documentation here:

https://github.com/fluent/fluent-bit-docs/blob/master/input/tail.md

pending feature on in_tail is to handle rotated files (to be implemented shortly)

**Comment by edsiper** [comment]
FYI: file rotation was added last week.

**Comment by mitchhh22** [comment]
Any idea when kubernetes metadata support will be available?

**Comment by edsiper** [comment]
@mitchhh22 that's coming once #157 is ready (no ETA at the moment but a priority).

Would you please request your interest into that feature on #157 ?

thanks.
