### ISSUE TITLE
I want to add a custom input plugin in C, Can anyone provide the steps to do so?

### ISSUE THREAD

**Issue by rahulprasad31121988** [fluent/fluent-bit#1211]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edsiper** [comment]
@rahulprasad31121988 

sadly we don't have documentation for developers, but you can try taking a look to the in_dummy plugin here:

https://github.com/fluent/fluent-bit/tree/master/plugins/in_dummy

if you have questions feel free to post them here and I will advise as much as I can.
