### ISSUE TITLE
Dynamic header values in http output plugin

### ISSUE THREAD

**Issue by kinghuang** [fluent/fluent-bit#1213]
**Is your feature request related to a problem? Please describe.**

The [http output plugin](https://docs.fluentbit.io/manual/output/http) supports [adding custom headers using the `Header` key](https://docs.fluentbit.io/manual/output/http#example-add-a-header).

I am sending Docker container logs to Sumo Logic, and would like to dynamically set log metadata based on the incoming log records. Sumo Logic's HTTP receivers accept custom source names, hosts, and categories by setting [HTTP headers named `X-Sumo-Name`, `X-Sumo-Host`, `X-Sumo-Category`](https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Data-to-an-HTTP-Source#Supported_HTTP_Headers).

**Describe the solution you'd like**

I would like a way to set dynamically header values in the http output plugin. For example, let's say there is a record key named `category`. There should be a way to use this as the header value. 

```
[1154103724, {"key1"=>12345, "category"=>"abc"}]
```

```
[OUTPUT]
    Name           http
    Match          *
    Host           127.0.0.1
    Port           9000
    Header         X-Key-A Value_A
    Header_record  X-Key-B category
    URI            /something
```

In the above configuration, the header `X-Key-A` would have the value `Value_A`, but `X-Key-B` would have the value `abc` from the record.

**Describe alternatives you've considered**

The [fluentd-output-sumologic output plugin](https://github.com/SumoLogic/fluentd-output-sumologic) for Fluentd can be used for this purpose in Fluentd. It pulls out values from the `_sumo_metadata` key in the record and uses it to populate the aforementioned headers.

**Additional context**

I switched from Fluentd to Fluent Bit for log forwarding to Sumo Logic. But, this particular detail has stymied me. Without the ability to customize the log metadata via headers, I cannot effectively sort and manage logs in Sumo Logic.

**Comment by edsiper** [comment]
@kinghuang is there a way Sumologic can do their work but when they try to find a specific key from the records ?, the problem that I see from the suggested approach is that for optimization we always send a chunk of records (0-N), so if we consider that we need to check a specific value from a key we likely will need to send one HTTP request per record and will be a huge overhead.

What I am asking basically is: can we tell Sumologic through a header which key they need to lookup ?, on that we defer the complexity to their system avoiding performance penalties and network overload.

**Comment by kinghuang** [comment]
@edsiper I've been fiddling with this in the SumoLogic side. I'm able to pull the source name, host, and category from log records using field extraction rules. This generally works, but the rules are applied during indexing. This means developers cannot do live log tailing based on the the extracted fields.

Making one HTTP request per record is definitely higher overhead, but that does seem to be SumoLogic's way to do this, and also what happens in their fluentd plugin. I'm still interested in having similar functionality in fluent-bit!

**Comment by frankreno** [comment]
I work at Sumo Logic.  Our FluentD Plugin is configured so that batching is done by tag.  This ensures we can set the appropriate headers and is a configuration option of fluentD buffers:

https://docs.fluentd.org/configuration/buffer-section#tag

Does fluent-bit support a similar mechanism? I did a quick scan on the docs but did not see anything.

**Comment by edsiper** [comment]
@frankreno Fluent Bit uses similar approach of Tag, Matching and buffers. Chunks records always have the same tag. 

What's the config used to send data to Sumo Logic ?

**Comment by frankreno** [comment]
Currently, we rely on the HTTP output plugin (note this config is for Fluent Bit v0.14.9. )
`
[OUTPUT]
    Name http
    Match *
    Header X-Sumo-Category tko/labs/fluentbit
    Host endpoint3.collection.us2.sumologic.com
    URI /receiver/v1/http/<token>
    Port 443
    tls on
    tls.verify off
    Format json_lines
`

**Comment by edsiper** [comment]
@frankreno so allowing to put the Tag into an HTTP header will be the ideal solution?

**Comment by frankreno** [comment]
Yes if we could reference the tag and use it in the header, this would solve the issue here I believe since logs are batched by tag anyway.

**Comment by alfredkrohmer** [comment]
I think it should be possible with the `headers_key` option in the HTTP output.
