### ISSUE TITLE
Spaces in environment variables cause configuration problems in filters

### ISSUE THREAD

**Issue by dominique-pfister** [fluent/fluent-bit#1225]
## Bug Report

**Describe the bug**
When one `Add`s the value of an environment variable to a _modify_ filter, it stops working when the variable has a value with spaces in it.

**To Reproduce**
Add a modify filter to your `fluent-bit.conf` as follows:
```
[FILTER]
  Name       modify
  Match      *
  Add key    ${value}
```
Then start `fluent-bit` with the following command:
```
$ value=a\ space ./fluent-bit
``` 
The filter rule will not be applied.

**Expected behavior**
The filter rule should be applied.

**Additional context**
We are adding a customisable description field to our log output, which may contain spaces.

**Comment by dominique-pfister** [comment]
Looking at the source code, method `flb_env_var_translate` in `flb_env.c` replaces environment variables with their values, so our input becomes:
```
Add key a space
```
Later on, method `setup` in `plugins/filter_modify/modify.c` splits the alleged value `key a space` by spaces, getting a list of 3 elements [1]. Since rule type `ADD` is only handled for a list containing exactly 2 elements, a regex rule is eventually created, which is not expected.

[1] https://github.com/fluent/fluent-bit/blob/8083d5192c6175406a635032ca0d8ee73df755de/plugins/filter_modify/modify.c#L115

**Comment by edsiper** [comment]
thanks for pointing out the root cause of the problem.

Indeed using the list of items in the property value is not right since list size validation depends on specific command/operation..

thinking about a  simple way to fix it...

**Comment by edsiper** [comment]
Fix requires a refactoring, found that there is no unit-tests for filter_modify, working on that first.

**Comment by dominique-pfister** [comment]
Cool, thanks!

As a side note, I first thought that surrounding the env variable with quotes or double quotes, as in:
```
Add key    "${value}"
```
would help, but `flb_utils_split` is agnostic to quotation, so the resulting list becomes:
```
[ "key", "\"a",  "space\"" ]
```
I was then wondering whether _introducing_ quotation to keep embedded spaces would help, without causing backward compatibility problems, of course.

**Comment by vnedyavila** [comment]
@edsiper - is there any resolution here? Or at least, a temporary workaround?

**Comment by NikNikM** [comment]
@vnedyavila I tried with \s and it worked:
[FILTER]
    Name modify
    Match *
    Condition Key_Value_Matches name Operational\sstatus
    Add metric ifOperStatus
I found the solution here: https://github.com/fluent/fluent-bit/issues/2102
