### ISSUE TITLE
[question] Send original app log "raw" rather than json format

### ISSUE THREAD

**Issue by kiich** [fluent/fluent-bit#1230]
## Question Report
This is probably a really dumb question but I could not find any similar issues raised before so wanted to ask/clarify.

I'm currently using fluent-bit with my java app running on Kubernetes and fluent-bit as sidecar where it shares host volume that holds app's log files.
The fluent-bit side car then sends this to Splunk HCE directly (but I have it working where it sends to another fluentbit container running on all of my nodes as forwarders which then sends to Splunk) - this set up is working ok and it does enrich the logs with Kubernetes metadata via the kubernetes filter and so on.

The output in splunk is of course in json format.

However - I have some of my users who have written hundreds of dashboards that was relying on the splunk log line/event to be in non-json format. These are now broken because the log in splunk is now json format and the message they are after is in the "log" key of the json that fluent-bit sent and for whatever reason, splunk is no longer able to pass this key's value and create further key-value fields in Splunk.

I appreciate you can write Splunk regex etc to maybe over come this but I was wondering if there is some switch/way to let fluent-bit send the log data "as-is" and not in json format.

I understand that this goes against the whole point of fluent-bit - but I wanted to confirm.

**Comment by kiich** [comment]
I've actually ended up doing the work on Splunk side by using `SEDCMD` as part of my props.conf.

I just send the tail of the file and parse using
```
          [PARSER]
            Name         generic
            Format       regex
            Regex        (?<log>^.*$)
            # Command       |  Decoder  | Field | Optional Action   |
            # ==============|===========|=======|===================|
            Decode_Field_As    escaped     log    do_next
            Decode_Field       json        log
```
I then do in `props.conf` of splunk
```
[mysourcetype]
INDEXED_EXTRACTIONS = json
SHOULD_LINEMERGE = true
SEDCMD-removelog = s/{"log":"(.*)"}/\1/
```
Which then lifts the values I want from value of `log` key fluentbit is sending and then Splunk indexes it as raw text. This kind of works BUT what I've found is multi-lined log line in the original file does not work and gets treated like individual lines instead.

I am honestly confused how to proceed as I wanted to use fluent-bit desperately but this fact that Splunk can not extract key value paris from a `json` field fluent bit sends is a blocker. Any tips/hints will be greatly appreciated!

**Comment by phhutter** [comment]
+1 have you found a proper way to display the data stored in the log key or is the props.conf the only way we can go?

mhm curious if theres a simple build in function to remove the metadata from json and only shows a specific key:value

i've just created a table and put there the important valuestime,log. Just to give a better visuability to my users. Json format is nice to enrich logs with data but its not that userfriendly if the developer is familiar with some basic bash commands like tail,cat,more etc.

**Comment by avihaycloudinary** [comment]
using the log_key field does the trick
https://docs.fluentbit.io/manual/pipeline/outputs/cloudwatch
