### ISSUE TITLE
How to set priority in input plugin?

### ISSUE THREAD

**Issue by Veiasai** [fluent/fluent-bit#1235]
**Is your feature request related to a problem? Please describe.**

A common case,  reading log from some files with different priorities.
The problem is that network bandwidth is not enough (some files are very large).
The files with high priority are usually small.
So how to guarantee that files with high priority are always read and sent first ?

**Describe the solution you'd like**

I found there is only one queue in Intermediate process, so it's difficult to block just in input plugin. Is there any great solutions ?
**Describe alternatives you've considered**

**Additional context**

**Comment by edsiper** [comment]
There is no way to set a priority. Note that also a "priority" level can set a wrong expectation, even if we support and process some input firsts than other, we won't know how large the incoming data is and the latency it will add based on buffering and parsing if any. 

If your network bandwidth is not enough, I suggest you enable Mem_Buf_Limit to restrict how much data is being sent per flush round:

https://docs.fluentbit.io/manual/configuration/memory_usage
