### ISSUE TITLE
[Forward input plugin] No support for Json format

### ISSUE THREAD

**Issue by mraczynska** [fluent/fluent-bit#1252]
**Is your feature request related to a problem? Please describe.**
Forward input plugin cannot receive logs in other format than binary msgpack.

**Describe the solution you'd like**
The most of fluent client libraries support logging objects which are serialized using MessagePack or Json.
Forward input plugin should also support both of formats.

**Describe alternatives you've considered**
My workaround: 
I use FluentD with the following configuration

```
<source>
   @type forward     
   bind 0.0.0.0
   port 24224 
</source> 
<match>
  @type forward
  <server>
    name my-server
    host 127.0.0.1
    port 24000
  </server>
  flush_interval 1s
  buffer_chunk_limit 8m     
  buffer_queue_limit 64
</match>
```
and Fluent-bit listens for messages on port 24000.

I want to use only Fluent-bit so Fluent-bit should accept both JSON and MessagePack format to be compatible with Fluentd.

**Comment by marqc** [comment]
+1/2 fluent v1 protocol specification states: 

> * Client MAY send a MessagePackEventStream as **msgpack str** format for compatibility reasons.
> * Server **MUST** accept both formats of bin and **str**.
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1

fluent-bit currently works only with binary msgpack, string representation of msgpack generates parser error.

Json format support seems to be optional in protocol spec:

> Note: In addition to the four carrier modes, in_forward plugin also accepts JSON representation of a single event for convenience. It detect it by the first byte of the request. It is unavailable with authentication/authorization.

and in v0 version of protocol:

> Note: In addition to the three carrier modes, in_forward plugin also accepts JSON representation of a single event for convenience. It detect it by the first byte of the request.

It would be nice to have support for json format to keep better compatibility with fluentd (easier migration to fluent-bit), and it is definitely must have to support "str msgpack" format in in_forward plugin.
