### ISSUE TITLE
CPU Core 100% with regex parsing

### ISSUE THREAD

**Issue by Theoooooo** [fluent/fluent-bit#1253]
## Bug Report

**Describe the bug**
I use td-agent-bit to parse incoming syslog message with specific regex i wrote.
But the recent modification i made to these regex make my agent stuck into a regex and use 100% of the CPU.

**To Reproduce**
- Rubular link if applicable:
I Already checked my Regexs on rubular and i don't have any error on it.
There is the regex101 links (it's more simple to share them for me ^^) :
syslog_sonicwall_vpn_1 : https://regex101.com/r/DroeuY/1
syslog_sonicwall_vpn_2 :https://regex101.com/r/qcYCOq/1
syslog_sonicwall_ips : https://regex101.com/r/qu5czN/1/
syslog_sonicwall_normal : https://regex101.com/r/DaRjaV/1/
syslog_sonicwall_enhanced : https://regex101.com/r/nGdms6/1/

- Steps to reproduce the problem:
I just setup the configuration below. When i start td-agent-bit, it automaticly use 100% of the CPU in a single core.

**Screenshots**

![image](https://user-images.githubusercontent.com/33425208/55615825-b1b75500-5790-11e9-82db-1ec369dc75c5.png)

**Your Environment**

* Version used: td-agent-bit 1.0.6 (repository)
* Configuration:
There is my parsers.conf :
```
[INPUT]
    Name syslog
    Mode udp
    Listen 1.2.3.4
    Port 13000
    Parser syslog_message
    Tag Sonicwall_Something1

[INPUT]
    Name syslog
    Mode udp
    Listen 1.2.3.4
    Port 13001
    Parser syslog_message
    Tag Sonicwall_Something2

[INPUT]
    Name syslog
    Mode udp
    Listen 1.2.3.4
    Port 13002
    Parser syslog_message
    Tag Sonicwall_Something3



[FILTER]
    Name parser
    Match Sonicwall_*
    Key_Name message
    Parser syslog_sonicwall_vpn_1

[FILTER]
    Name parser
    Match Sonicwall_*
    Key_Name message
    Parser syslog_sonicwall_vpn_2

[FILTER]
    Name parser
    Match Sonicwall_*
    Key_Name message
    Parser syslog_sonicwall_ips

[FILTER]
    Name parser
    Match Sonicwall_*
    Key_Name message
    Parser syslog_sonicwall_normal

[FILTER]
    Name parser
    Match Sonicwall_*
    Key_Name message
    Parser syslog_sonicwall_enhanced

[FILTER]
    Name parser
    Match *
    Key_Name message
    Parser debug

[OUTPUT]
    Name es
    Match Sonicwall_Something1
    Host 5.6.7.8
    Port 9200
    Logstash_Format True
    Logstash_Prefix sonicwall_something_1
    Logstash_DateFormat %Y-%m-%d

[OUTPUT]
    Name es
    Match Sonicwall_Something2
    Host 5.6.7.8
    Port 9200
    Logstash_Format True
    Logstash_Prefix sonicwall_something_2
    Logstash_DateFormat %Y-%m-%d

[OUTPUT]
    Name es
    Match Sonicwall_Something3
    Host 5.6.7.8
    Port 9200
    Logstash_Format True
    Logstash_Prefix sonicwall_something_3
    Logstash_DateFormat %Y-%m-%d




```

* Environment name and version (e.g. Kubernetes? What version?):
* Operating System and version: Debian 1.0.6
* Filters and plugins: 
Input : syslog udp
Parsing : parser
Output : es

**Additional context**

With this overload, i missed a lot of messages send to my server because of this cpu usage

If you need specific informations or log, let me know and i will provide them

EDIT :  I manage to found out the bug here. It happened with the syslog_sonicwall_normal regex. I'm trying to fix it on my side

**Comment by edsiper** [comment]
I see that examples provided do not provide a test string, please provide the same examples in Rubular site with regex and test strings.

**Comment by agup006** [comment]
Hey all, this issue is a bit stale and the version used here is a bit old. We have increased performance with our latest release 1.7.0 and would be great if we could try with that version to see if there is a reduction in CPU usage. I am going to close this issue for now, please re-open if we want to resume the discussion. Thank you!
