### ISSUE TITLE
Null output does not drop events

### ISSUE THREAD

**Issue by jstaffans** [fluent/fluent-bit#1266]
## Bug Report

**Describe the bug**

Catch-all `null` output does not seem to drop events.

**To Reproduce**

Using a simple configuration with a `tail` input:

```
[SERVICE]
    Flush 5
    Daemon False
    Log_Level debug

[INPUT]
    Name tail

    Path /tmp/test/*.log

    Path_Key source
    Tag event

[OUTPUT]
    Name null
    Match *

[OUTPUT]
    Name stdout
    Match *
```

Appending a line to e.g. `/tmp/test/foo.log` results in it appearing in stdout.

**Expected behavior**

Everything should be dropped.

**Your Environment**

* Version used: 1.0.6
* Operating System and version: CentOS 7

**Comment by edsiper** [comment]
Yes, you are seeing logs in the standard output interface because you have an output matching rule to stdout that matches everything. null output plugins do nothing. 

If you want to discard records consider using a filter. Also, output tag/matching rules work for all of them, not the first match.

**Comment by jstaffans** [comment]
Thanks for the explanation!
