### ISSUE TITLE
Question: Conditionally enable/disable plugin in conf file

### ISSUE THREAD

**Issue by rashmichandrashekar** [fluent/fluent-bit#1280]
Is it possible to disable/enable the tail plugin based on an environment variable or an other setting?
I want to do this for the tail plugin to customize the log tailing.

**Comment by MengmengZHANG** [comment]
I have also found this feature quite useful, especially when testing feature in a beta version, we could turn off a troublesome plugin by setting value instead of remove the plugin from the conf file. 

It would be great that this disable/enable can be added as a generic control for all plugins.

**Comment by Saya47** [comment]
This would be a very good feature! Write one config for all servers, then enable configs depending on the env variables!

**Comment by mfabricanti** [comment]
Is there a way nowadays to achieve this behavior?

**Comment by mitchellsuzuki** [comment]
poke. this would be a great feature!

**Comment by amitarora-boomi** [comment]
Even this feature can also be there in output plugin, like you are switching to new version of Output server, you want to selectively enable on some machines and remain disable on other machines and enable it gradually without changing code all time.

**Comment by kferrari** [comment]
For anyone needing some inspiration, I had the same issue and [wrote a patch](https://gist.github.com/kferrari/a859318da62b5d9e7969896ab4e28444) for (some) output plugins. 

Caveat: I only tested this with `stdout` and `forward` plugins. This allows to enable/disable output plugins like so

```
[OUTPUT]
    Name        forward
    Alias       fluent_out
    Match      *
    Host        fluent-bit
    Port        24224
    Enabled     on

[OUTPUT]
    Name        stdout
    Alias       stdout_out
    Match       *
    Enabled     off
```

Hope it helps someone 👋
