### ISSUE TITLE
The document is poor

### ISSUE THREAD

**Issue by yangsongx** [fluent/fluent-bit#1281]
** The document is like a plain output on the code, no usable examples. Many many useless options are recorded in the doc, unfortunately, new user finds it's difficult to start the usage. **

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edsiper** [comment]
actually, we point where the real docs are (and there is high traffic on docs site)

![docs](https://user-images.githubusercontent.com/369718/56262527-43ca3200-609c-11e9-8020-3240b96d2f02.png)
