### ISSUE TITLE
What's exactly the simplest plain text log collection like?

### ISSUE THREAD

**Issue by yangsongx** [fluent/fluent-bit#1284]
I'm sorry to write these here, as I'm frustrated to find such topic in the doc, which contained few usable information.

Suppose we running fluent-bit, to collect log from machine-A to machine-B:
1. Assume the log in source end(machine-A) is 'hello world'
2. Then the log in destination end(machine-B) would be like this: '[1555491391.345889983, {"log"=>"hello world"}]

I don't like above **extra decoration** at all! I just want plain log collection, don't add any extra info for me!

What I want:
1. I want do a plain text log collection, don't need above extra decoration

2. I want machine-B would collect the log with just "hello world", not the JSON string data!

I knew there's a way to set Key_Name to log to extract the log data, but I failed find where to correctly set it, I always failed and there's no related instructions in the doc.

The .conf I used is:

`[INPUT]
  Name  tail
  Path  /tmp/a.log

[OUTPUT]
  Name  stdout
  Match *
  Key_name log

I feel very frustrated, as it always print as [1555491391.345895518, {"log"=>"hello world"}], but I only want a plain 'hello world', I don't like such JSON decoration strings at all!

Could anyone give any help about this?

**Comment by nigels-com** [comment]
The internal datastructure for Fluent-bit seems to be a dictionary of key-value pairs.  So perhaps if you're only interested in the "log" values, there could be a mode for only outputting those line-by-line?

Otherwise, filter it downstream with something like jq to extract the log values, one by one?

https://stedolan.github.io/jq/

**Comment by johnpekcan** [comment]
I would still argue this is a nice ask. I also found: 
https://github.com/fluent/fluent-bit/pull/1480 
https://github.com/fluent/fluent-bit/issues/1478 which solved this issue  -- but for out_file instead. 
It would be awesome to get this for stdout!  I've resorted to using fluentd in the meantime to achieve this behavior.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: blahblah
data:
  fluent.conf: |
    <source>
    @type tail
    path path/to/some/*.log
    tag *
    read_from_head true
    follow_inodes true
    <parse>
    @type none
    </parse>
    </source>
    <match **>
    @type stdout
    <format>
    @type single_value
    </format>
    </match>
    <system>
    log_level trace
    </system>
```

**Comment by johnpekcan** [comment]
@fujimotos , any interest in adding this same ability to stdout? Cheers!

**Comment by nigels-com** [comment]
Still sounds reasonable to align stdout with out_file, where possible.
