### ISSUE TITLE
cpu/mem INPUT into kubernetes FILTER

### ISSUE THREAD

**Issue by slimee** [fluent/fluent-bit#1286]
## Bug Report

It sounds like a bug but maybe using together CPU or MEM input is not supported by kubernetes filter? Is a good solution to do so? Thanks you

**Describe the bug**
filter kubernetes does not work with input cpu or mem.

**To Reproduce**
Define 3 INPUT: 1 cpu, 1 mem and 1 tail
Define 1 FILTER: Name kubernetes, match *

**Expected behavior**
Having kubernetes.* fields in ALL outputs.

**Actual behavior**
Only logs from tail input contains kubernetes fields.

**Your Environment**
* Version used: fluentbit 0.13
* Configuration: helm efk 0.13 chart deployment
* Environment name and version (e.g. Kubernetes? What version?): Dockerised deployment of Kubernetes with Rancher 2.1.3 (kubelets are in containers)
* Server type and version: Bare metal
* Operating System and version: Ubuntu 16.04

**Comment by slimee** [comment]
Documentation mention (using tail plugin) in parenthesis so it seems it works only with tail plugin.

[https://fluentbit.io/documentation/0.13/filter/kubernetes.html](url)

**Comment by edsiper** [comment]
@slimee 

- Filter Kubernetes is only designed to enrich logs coming from tail or systemd that have a Kubernetes context associated with namespaces, pod name and so on. So if you enable a different plugin can generate some metrics or info, it cannot be enriched with filter_kubernetes.

- Please upgrade to the latest version on 1.x series

**Comment by slimee** [comment]
I've upgraded to 1.0.4 and I don't see the kubernetes field from cpu and mem.

Is there something wrong with my configuration?

```
[SERVICE]
    Flush 5
    Daemon Off
    Config_Watch On
    Log_Level error
    Parsers_File parsers.conf

[INPUT]
    Name cpu
    Tag  kube.sys.cpu

[INPUT]
    Name   mem
    Tag    kube.sys.mem

[INPUT]
    Name             tail
    Path             /var/log/containers/nginx-ingress*.log
    Parser     docker
    Tag              kube.bf.ingress.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[INPUT]
    Name             tail
    Path             /var/log/containers/gateway*.log
    Parser           docker
    Tag              kube.bf.gateway.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[FILTER]
    Name                kubernetes
    Match               *
    Merge_Log           On
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token

[OUTPUT]
    Name  es
    Match kube.bf.*
    Host  efk-elasticsearch
    Port  9200
    Logstash_Format On
    Retry_Limit False
    Type  flb_type
    Logstash_Prefix bf

[OUTPUT]
    Name  es
    Match kube.sys.cpu
    Host  efk-elasticsearch
    Port  9200
    Logstash_Format On
    Retry_Limit False
    Type  flb_type
    Logstash_Prefix cpu

[OUTPUT]
    Name  es
    Match kube.sys.mem
    Host  efk-elasticsearch
    Port  9200
    Logstash_Format On
    Retry_Limit False
    Type  flb_type
    Logstash_Prefix mem
```

**Comment by edsiper** [comment]
Logs not coming from in_tail or systemd are not suitable for Kubernetes filter.
