### ISSUE TITLE
fluentbit monitor metrics not working as expected 

### ISSUE THREAD

**Issue by CoderOwl** [fluent/fluent-bit#1288]
## Bug Report

**Describe the bug**
Trying to validate the log flow by matching fluent-bit monitor metrics `fluentbit_input_records_total` and `fluentbit_output_proc_records_total` with the log events being read and processed by fluent-bit.
I am manually generating fake logs of 10000 events every 1 minute and able to see the same at the kafka endpoint to which fluent-bit forwards to.
But, the values of `fluentbit_input_records_total` and `fluentbit_output_proc_records_total` are very low (around 600) and also both the records do not match. 

**To Reproduce**
Environment: kubernetes
Fluentbit image tag: 1.0.6

Generating logs with python script in `/var/log/containers`:
```
import sys
import time
import json
f = open('/var/log/containers/prom-test-01.log', 'w')

while True:
        now = time.time()
        for i in range(0,10):
                dict_to_dump = {}
                dict_to_dump["log"] = i
                f.write(json.dumps(dict_to_dump)+"\n")
        later = time.time()
        difference = int(later - now)
        print("sleeping")
        time.sleep( 60 - difference)
```

The configmap of the fluent-bit is set to:
```
Name:         fluentbit-config
Namespace:    logging
Labels:       app=fluentbit
Annotations:  <none>

Data
====
parsers.conf:
----
[PARSER]
    Name        docker
    Format      json
    Time_Keep    true
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Decode_Field_As escaped_utf8 log do_next
    Decode_Field_As json log

[PARSER]
    Name        parse-audit-apiserver
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
fluent-bit.conf:
----
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
[INPUT]
    Name             tail_prom_test
    Path             /var/log/containers/prom-test-*.log
    Tag              prom.*
    Refresh_Interval 60
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    Ignore_Older     2d
    DB               /tail-db/tail-containers-state.db
    DB.Sync          Normal
[FILTER]
    Name      record_modifier
    Match     prom.*
    Record cluster_id eu2-dev-af3
    Record index main
    Record sourcetype kubernetes
[OUTPUT]
    Name  kafka_prom_test
    Match prom.*
    Brokers  <Kafka end point>
    Topics  app_data
    Timestamp_Key time
    Timestamp_Format iso8601
    rdkafka.request.required.acks 0
    rdkafka.log.connection.close false
    rdkafka.message.max.bytes  1000012
    rdkafka.socket.send.buffer.bytes 1256
    rdkafka.batch.num.messages 1000000
    rdkafka.message.send.max.retries 3
    rdkafka.enable.idempotence true
Events:  <none>
```

**Expected behavior**
`fluentbit_input_records_total` and `fluentbit_output_proc_records_total`  increasing by about 10000 every minute.

**Screenshots**
```
{
  "input": {
    "tail.0": {
      "records": 1,
      "bytes": 30
    }
  },
  "filter": {
    "record_modifier.0": {
      "drop_records": 0,
      "add_records": 0
    }
  },
  "output": {
    "kafka.0": {
      "proc_records": 0,
      "proc_bytes": 1300267,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0
    },
    "forward.0": {
      "proc_records": 0,
      "proc_bytes": 1300267,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0
    }
  }
}
```

**Your Environment**

* Version used: 1.0.6
* Configuration: (as above)
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by mjhoffman65** [comment]
I am seeing this too.  The `proc_records` metric is 0 even though I am seeing my log records streaming into my listed outputs.

**Comment by CoderOwl** [comment]
@bobykus31 has also pointed to this at https://github.com/fluent/fluent-bit/issues/233#issuecomment-482514551

**Comment by loburm** [comment]
I have hit the same issue recently. In my case I'm using plugin written in go, but that's what I can see: (timestamps and empty inputs removed for readability):

fluentbit_input_records_total{name="tail.0"} 5
fluentbit_input_bytes_total{name="tail.0"} 849
fluentbit_input_records_total{name="tail.1"} 11
fluentbit_input_bytes_total{name="tail.1"} 1123
fluentbit_input_records_total{name="tail.2"} 4
fluentbit_input_bytes_total{name="tail.2"} 377
fluentbit_input_records_total{name="tail.3"} 99
fluentbit_input_bytes_total{name="tail.3"} 6752
fluentbit_input_records_total{name="tail.5"} 9170
fluentbit_input_bytes_total{name="tail.5"} 2229734
fluentbit_input_records_total{name="tail.9"} 38
fluentbit_input_bytes_total{name="tail.9"} 4446
fluentbit_output_proc_records_total{name="sd_go_new.0"} 29
fluentbit_output_proc_bytes_total{name="sd_go_new.0"} 18057036
fluentbit_output_errors_total{name="sd_go_new.0"} 0
fluentbit_output_retries_total{name="sd_go_new.0"} 0
fluentbit_output_retries_failed_total{name="sd_go_new.0"} 0

Processed bytes is 18MB, but number of records is only 29, which can't be true. I have also checked Stackdriver logs and clearly it has more than 29 ingested records.

**Comment by loburm** [comment]
@edsiper could you take a look?

**Comment by loburm** [comment]
Hm, I just verified fluentbit 1.1 and looks that issue above was already fixed there.
