### ISSUE TITLE
master repository is reverted

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#129]
`golang` repository became `master` and some commits were lost.
https://github.com/fluent/fluent-bit/network

My forked repo may help us...
https://github.com/nokute78/fluent-bit/commit/73d9cc77198bafc82f3859cc51596f1ae1d9f647

**Comment by edsiper** [comment]
damn it, I did a mistake last night, which specific commits are lost ?

**Comment by edsiper** [comment]
I will fix it as follows:

- reset to 0.9 state
- apply manually 2-3 patches from the new 0.10 (master)
- merge golang

**Comment by edsiper** [comment]
thanks again!, It should be OK now.

**Comment by nokute78** [comment]
Thanks, it was fixed.
Please be careful :)
