### ISSUE TITLE
fluent-bit annotation parser not found

### ISSUE THREAD

**Issue by vincent927** [fluent/fluent-bit#1304]
## Bug Report

**Describe the bug**
I have customized an parser named "java" , and when i restart fluent-bit , it was warn in log

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2019/04/26 07:57:08] [ warn] [filter_kube] annotation parser 'java' not found (ns='test' pod_name='pcss-back-config-7c66c88575-64qs8', container_name='pcss-back-config')
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.0.6
* Configuration: 
![image](https://user-images.githubusercontent.com/10399425/56792864-3865cc00-683d-11e9-83d4-179c5a6ac293.png)
![image](https://user-images.githubusercontent.com/10399425/56792881-41ef3400-683d-11e9-99b3-f535e3baceb2.png)

* Environment name and version (e.g. Kubernetes? What version?): kubernetes  v1.13.5
* Server type and version:
* Operating System and version: Centos7
* Filters and plugins:

**Additional context**

**Comment by MaxDiOrio** [comment]
I'm seeing the same thing with a custom annotation parser.

**Comment by edsiper** [comment]
when you start Fluent Bit, do you see any warning or error about the parser defined ?
