### ISSUE TITLE
Any "Replace_Dots On" option for Kafka output？

### ISSUE THREAD

**Issue by judexzhu** [fluent/fluent-bit#1305]
I'm using fluent-bit to send logs to kafka, and ES is the consumer

Facing the error with kubernetes labels 

```
[43]: index [logx-k8s_2019-04-25], type [logx-k8s], id [5X28U2oB2gDMRtJZMcad], message [ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=Could not dynamically add mapping for field [app.kubernetes.io/instance]. Existing mapping for [kubernetes.labels.app] must be of type object but found [text].]]] (org.nesc.ecbd.sink.task.ElasticSearchSinkTask)
```

Found ES has 

`Replace_Dots On` options but cannot find any in Kafka output

Is there any possibility that Kafka can have the same solution as ES

or any other alternative way ?

Thanks a lot 

reference :

https://github.com/fluent/fluent-bit/issues/708

**Comment by edsiper** [comment]
not really, likely we will need to implement this in a new filter to avoid situations...

**Comment by yuha0** [comment]
+1 on this. 

Although Elasticsearch is a very popular log aggregation system, it is not always visible to the log forwarder like fluent-bit. A generic filter implementation is better than adding this specific functionality directly to output plugins.

**Comment by sossickd** [comment]
+1 on this, would be good to have a generic filter that can be applied to the http output

**Comment by DandyDeveloper** [comment]
+1 as I am in need of a similar option on the Kubernetes plugin. A generic filter would be much more appropriate for this.

**Comment by PettitWesley** [comment]
@DandyDeveloper @sossickd @yuha0 @edsiper @judexzhu I started working on a generic filter for this the other day. It doesn't work yet; it'll be some time before I can get back to it.

In the meantime, I'd like to get your opinion on the interface. Here's an example configuration:

```
[FILTER]
     Name         replace_character
     find            .
     replace      _
```

I'm wondering if the name should be "replace_key_characters", and if it should use a regex. I'm not sure if that'd be overkill though and would meaningfully affect performance.

**Comment by DandyDeveloper** [comment]
@PettitWesley I'll have more of a think, but I wonder if `flatten_object` is an appropriate name? As that's the overall objective of this feature, to help flatten to the incoming path to an interpritable JSON object.

`replace_character` is a nice generic name though, but I'm not sure if this is almost too generic?

**Comment by PettitWesley** [comment]
Unfortunately, other Fluent Bit work is higher priority for me right now; I probably won't be able to finish this for a while.

If anyone else wants to take a stab at this, feel free to.

**Comment by Kilz78** [comment]
@PettitWesley 

Hi any news on this 

? I'm exactly in the same situation, and not found any solution. 
It seems that the option replace_dots with ES plugin is a perfect thing for me, but i'm using Kakfa Plugin as mentionned here.

**Comment by true64gurus** [comment]
Same here , I send k8s logs to kafka then logstash pulls logs from kafka as consumer and send it to ES. 
I am getting same warnings in logstash logs.

**Comment by Kilz78** [comment]
@true64gurus : Thanks for your feedback, but unfortunately I can't do it in my organization. Our kafka clusters are mutualized and used by a lot of different service.... Maybe can you share your logstash configuration, I can discuss about that with the service concerned ?

**Comment by true64gurus** [comment]
logstash config for pulling kafka logs 

`input {
  kafka
    {
     codec => json
     bootstrap_servers => "10.10.20.30:9094"
     topics => ["k8s-c1", "k8s-c2", "k8s-c3", "k8s-c4", "k8s-c5", "k8s-c6"]
     decorate_events => true
     group_id => "kafka-cluster1"
     metadata_max_age_ms => 60000
     consumer_threads => 3
    }

}
filter {

    json {
      source => "message"
    }
    mutate { copy => { "[@metadata][kafka]" => "kafka" } }
}
`

**Comment by Kilz78** [comment]
@true64gurus  Thanks for that. 

But it will be very cool if natively we can enable one filter to replace_dots as it's done with ES plugin. 
I do not know how fluent-bit works, but if the work is done on ES plugin, maybe we can take this code to adapt it for kafka plugin ? 

@edsiper  any advice on it ?

**Comment by Kilz78** [comment]
@edsiper up

**Comment by evgkrsk** [comment]
up

**Comment by scila1996** [comment]
+1, same problem when parse log from K8S, it contains a lot of keys with dots (ex `kubernetes.io/name`)

**Comment by squaricdot** [comment]
I am still stuck with this issue after playing with it for a week. I thought I fixed it with combining information from several places and these issues:

https://github.com/fluent/fluent-bit/issues/1134
https://github.com/fluent/fluent-bit/issues/4386

ended up a lua rewrite which is breaking my mind as it's parsing almost all the labels except for some and i dont see the logic.

i send events from fluent-bit to kafka and logstash running next to elastic will pull it from kafka.

i try to let fluent-bit do the parsing with lua with:

```
      function dedot(tag, timestamp, record)
          check = 0
          if not (record["k8s_annotations"] == nil) then
              check = 1
              dedot_keys(record["k8s_annotations"])
          end
          if not (record["k8s_labels"] == nil) then
              check = 1
              dedot_keys(record["k8s_labels"])
          end
          if check == 1 then
              return 1, timestamp, record
          else
              return 0, 0, 0
          end
      end

      function dedot_keys(map)
          if map == nil then
              return
          end
          for k, v in pairs(map) do
              dedotted = string.gsub(k, "%.", "_")
              if k ~= dedotted then
                  map[dedotted] = v
                  map[k] = nil
              end
          end
      end
```

with FILTER:

```
      [FILTER]
          Name lua
          Match kube.*
          script /fluent-bit/scripts/functions.lua
          call dedot
```
