### ISSUE TITLE
Setting Generate_Id inside of ES output plugin creates corrupted JSON output

### ISSUE THREAD

**Issue by JungleGenius** [fluent/fluent-bit#1308]
Something about Generate_Id is introducing Null into the JSON output.  Note the null "." between the _id and @timestamp.
 
`Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens`

`[2019-05-01T00:25:23,859][DEBUG][o.e.a.b.TransportShardBulkAction] [3lELv5Y] [agent-btmp-ip-10-0-0-00.ec2.internal-2019.04][4] failed to execute bulk item (index) index{[agent-btmp-ip-10-0-0-00.ec2.internal-2019.04][btmp][48256416-16be-284b-2ebb-217efea3011d], source[{"index":{"_index":"agent-btmp-ip-10-0-0-00.ec2.internal-2019.04","_type":"btmp","_id":"7e16905d-c679-c1c1-82c9-3df931646a9f"}}.{"@timestamp":"2019-04-18T21:33:49.000Z", "username":"voltiii", "tty":"ssh:notty", "endtime":"Thu Apr 18 21:33:49 2019", "duration":"(00:00)", "ipaddress":"130.61.121.78", "agent_hostname":"ip-10-0-0-00.ec2.internal"}]}`
`org.elasticsearch.index.mapper.MapperParsingException: failed to parse`

**Comment by JungleGenius** [comment]
`
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  Off
    HTTP_Listen  127.0.0.1
    HTTP_Port    2020

[INPUT]
    Name cpu
    Tag cpu.local
    # Interval_Sec 3600
    Interval_Sec 36

[FILTER]
    Name record_modifier
    Match *
    Record agent_hostname ${HOSTNAME}

[OUTPUT]
    Name es
    Generate_ID On
    Retry_Limit 5
    Match cpu.*
    Host 127.0.0.1
    Port 443
    tls On
    tls.verify Off
    Type cpu_metrics
    Logstash_Format On
    Logstash_Prefix agent-cpu-${HOSTNAME}
`

**Comment by JungleGenius** [comment]
`
{"index":{"_index":"agent-cpu-ip-10-0-0-00.ec2.internal-2019.05.14","_type":"cpu_metrics","_id":"1a114cd3-5163-1374-084f-04aba1.........#{"@timestamp":"2019-05-14T16:59:20.000Z", "cpu_p":2.986111, "user_p":2.763889, "system_p":0.222222, "cpu0.p_cpu":2.888889, "cpu0.p_user":2.694444, "cpu0.p_system":0.194444, "cpu1.p_cpu":3.111111, "cpu1.p_user":2.861111, "cpu1.p_system":0.250000, "agent_hostname":"ip-10-0-0-00.ec2.internal"}`

**Comment by edsiper** [comment]
fixed by #1357
