### ISSUE TITLE
Re-tag filter so we can have kubenetes metadata and the possibility to route logs

### ISSUE THREAD

**Issue by Kanshiroron** [fluent/fluent-bit#1311]
Hello,

It's currently not possible to have both Kubernetes metadata (from the Kubernetes filter) and set a custom Tag from tail input at the same time.

If you want to set custom tag from the `tail` input (via the Tag_Regex directve), then you will not be able to retrieve Kubernetes metadata (Fluent bit will throw errors like `[ warn] [filter_kube] invalid pattern for given tag`).
On the other hand, if you don't set a Tag_Regex on the input, you can't filter and route logs easily.

To me, the best solution would be to create a new input plugin that merge the `tail` input plugin with the `kubernetes` filter. The kubernetes filter can't work without the tail input anyway.

Thanks for your support,

**Comment by edsiper** [comment]
Actually the best solution is to implement re-tagging feature which is not yet available.

Note that Filter Kubernetes works with in_tail and in_systemd.

**Comment by Kanshiroron** [comment]
I didn't know that in_systemd was also compatible with the Kubernetes filter.
