### ISSUE TITLE
fluentbit.io is down

### ISSUE THREAD

**Issue by adejongh** [fluent/fluent-bit#1314]
Web site not available, and "Failed to connect to packages.fluentbit.io port 443: Connection refused"

**Comment by edsiper** [comment]
thanks for informing. Looks like there is a DNS issue with the provider, looking at it.

**Comment by freeyoung** [comment]
```
Domain Name: FLUENTBIT.IO
Registry Domain ID: D503300000040396723-LRMS
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: www.namecheap.com
Updated Date: 2019-05-04T15:55:44Z
Creation Date: 2015-05-04T15:47:13Z
Registry Expiry Date: 2019-05-04T15:47:13Z
```

No, the actual issue is that the domain just expired earlier today.

**Comment by edsiper** [comment]
yes, the real problem was "domain expired", fixed now.

**Comment by adejongh** [comment]
Hmm, the fluentbit.io site is still down, and:
```
Err:13 https://packages.fluentbit.io/ubuntu/xenial xenial InRelease
Failed to connect to packages.fluentbit.io port 443: Connection refused
```

**Comment by andyrooster** [comment]
Requests to https://packages.fluentbit.io/ are returning "403 Forbidden" errors and the domain name expires today. Could this be happening again one year after last time?

I also raised this issue: https://github.com/fluent/fluent-bit-packaging/issues/12

**Comment by edsiper** [comment]
@andyrooster the directories are not browsable, that's why you get a forbidden error. 

I see certs are already renewed, maybe the problem happened some hours before?

**Comment by andyrooster** [comment]
@edsiper Ok thats a fair comment but the whole site seems to be down https://fluentbit.io/. Are you sure its not the domain renewal again?

As a side note the initial problem I had was https://packages.fluentbit.io/debian/dists/jessie/main/binary-amd64/Packages returned a 404 when trying to do an apt-get install

**Comment by andyrooster** [comment]
Port 443 doesn't respond and port 80 responds with a Namecheap page:
```
# curl https://fluentbit.io/
curl: (7) couldn't connect to host
# curl http://fluentbit.io/
<!DOCTYPE html>
<html>
<head id="ctl00_ctl00_Head1"><title>
	fluentbit.io - Registered at Namecheap.com
</title>.....
```

**Comment by edsiper** [comment]
we are working on this, found TCP syn flood attack

**Comment by edsiper** [comment]
(services are restored now)

**Comment by andyrooster** [comment]
Thanks @edsiper

**Comment by andyrooster** [comment]
Sorry, me again @edsiper! 

Im still having trouble using the Debian repository. apt-get gets a `404` when trying to download https://packages.fluentbit.io/debian/dists/jessie/main/binary-amd64/Packages

However I can install the repo key fine https://packages.fluentbit.io/fluentbit.key

Is the Debian repository working as expected?

The last time we used the Ansible script that does the `apt-get install` was on 6th Feb 2020 and it worked then. The code has not changed since.

**Comment by rfwankenobi** [comment]
I'm getting errors on this as well on multiple servers:

Err:11 https://packages.fluentbit.io/ubuntu xenial/main amd64 Packages
  404  Not Found
Reading package lists... Done
E: Failed to fetch https://packages.fluentbit.io/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

Please advise.

**Comment by andyrooster** [comment]
They changed the repo URL. Update your sources.list to:

`deb https://packages.fluentbit.io/ubuntu/xenial xenial main`

**Comment by rfwankenobi** [comment]
Many thanks @andyrooster. Sorry for commenting on a closed ticket, noticed after I posted the message. The documentation I was using is now out of date. This solves the problem!
