### ISSUE TITLE
Get Kubernetes metadata of the namespace

### ISSUE THREAD

**Issue by jelmokri** [fluent/fluent-bit#1319]
Hi everyone,

I would like to know if it's possible to get the kubernetes metadata of the Namespaces.

With the Kubernetes filter, I succeed to get the metadata of the pod but I need to get the metadata of the namespace of the pod, especially label of the namespace.

Is it possible ? If not, how can i proceed to get it ?

Thanks for your help .

**Comment by bakito** [comment]
Hi all
Support of namespace annotations would help me too.

**Comment by felixkrohn** [comment]
I would be interested in this as well. In my usecase it would be to read a splunk index from a namespace annotation.

**Comment by envybee** [comment]
Hey all, wondering if anyone came across any workarounds for this? Thanks
