### ISSUE TITLE
CPU load exceeds 100%

### ISSUE THREAD

**Issue by rolandjitsu** [fluent/fluent-bit#1320]
## Bug Report

**Describe the bug**

I'm using the CPU input plugin on a Raspberry Pi 3 and I consistently see CPU load over 100%:
```
cpu: [1557741007.358603, {"cpu_p":2128.250000, "user_p":1575.000000, "system_p":553.250000, "cpu0.p_cpu":1446.000000, "cpu0.p_user":752.000000, "cpu0.p_system":694.000000, "cpu1.p_cpu":1755.000000, "cpu1.p_user":1076.000000, "cpu1.p_system":679.000000, "cpu2.p_cpu":1835.000000, "cpu2.p_user":1251.000000, "cpu2.p_system":584.000000, "cpu3.p_cpu":3477.000000, "cpu3.p_user":3221.000000, "cpu3.p_system":256.000000, "hostname":"raspi"}]
cpu: [1557741053.389968, {"cpu_p":16.000000, "user_p":7.500000, "system_p":8.500000, "cpu0.p_cpu":13.000000, "cpu0.p_user":3.000000, "cpu0.p_system":10.000000, "cpu1.p_cpu":30.000000, "cpu1.p_user":23.000000, "cpu1.p_system":7.000000, "cpu2.p_cpu":12.000000, "cpu2.p_user":3.000000, "cpu2.p_system":9.000000, "cpu3.p_cp":9.000000, "cpu3.p_user":1.000000, "cpu3.p_system":8.000000, "hostname":"raspi"}]
cpu: [1557741096.066868, {"cpu_p":2123.750000, "user_p":1576.250000, "system_p":547.500000, "cpu0.p_cpu":1497.000000, "cpu0.p_user":722.000000, "cpu0.p_system":775.000000, "cpu1.p_cpu":1223.000000, "cpu1.p_user":499.000000, "cpu1.p_system":724.000000, "cpu2.p_cpu":1751.000000, "cpu2.p_user":1134.000000, "cpu2.p_system":617.000000, "cpu3.p_cpu":4024.000000, "cpu3.p_user":3950.000000, "cpu3.p_system":74.000000, "hostname":"raspi"}]
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
```
[2019/05/21 06:11:48] [trace] [in_cpu] CPU 534.50%
[2019/05/21 06:12:11] [trace] [in_cpu] CPU 559.00%
```
- Steps to reproduce the problem:

**Expected behavior**

CPU usage should probably not be above 100%.

**Screenshots**

**Your Environment**

* Version used: v1.0.6
* Configuration:
```
[SERVICE]
    Flush           ${FLB_FLUSH_INT}
    Daemon          Off
    Log_Level       info
    Log_File        ${FLB_LOG_FILE}
    Parsers_File    parsers.conf

[INPUT]
    Name            cpu
    Tag             cpu
    Interval_Sec    ${FLB_PULL_INT}
    Interval_NSec   0

[OUTPUT]
    Name            stdout
    Match           *
```
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
* Filters and plugins:

**Additional context**

I am building Fluent Bit myself with the following flags:
```bash
cmake -DFLB_EXAMPLES=No \
  -DFLB_LUAJIT=No \
  -DFLB_FILTER_KUBERNETES=Off \
  -DFLB_FILTER_LUA=Off \
  -DFLB_IN_DUMMY=Off \
  -DFLB_IN_FORWARD=Off \
  -DFLB_IN_HEAD=Off \
  -DFLB_IN_KMSG=Off \
  -DFLB_IN_MQTT=Off \
  -DFLB_IN_RANDOM=Off \
  -DFLB_IN_SERIAL=Off \
  -DFLB_IN_SYSLOG=Off \
  -DFLB_IN_STDIN=Off \
  -DFLB_OUT_AZURE=Off \
  -DFLB_OUT_BIGQUERY=Off \
  -DFLB_OUT_COUNTER=Off \
  -DFLB_OUT_EXIT=Off \
  -DFLB_OUT_FLOWCOUNTER=Off \
  -DFLB_OUT_GELF=Off \
  -DFLB_OUT_HTTP=Off \
  -DFLB_OUT_INFLUXDB=Off \
  -DFLB_OUT_KAFKA=Off \
  -DFLB_OUT_KAFKA_REST=Off \
  -DFLB_OUT_NATS=Off \
  -DFLB_OUT_NULL=Off \
  -DFLB_OUT_PLOT=Off \
  -DFLB_OUT_SPLUNK=Off \
  -DFLB_OUT_STACKDRIVER=Off \
  ../

# NOTE: Using all cores (4) might crash the Raspi
make -j 3 # $(getconf _NPROCESSORS_ONLN)
```

The binary is not running on the same machine it was built on:
* built on: `Linux 4.14.80-v7+ #1161 SMP Mon Nov 12 18:51:43 GMT 2018 armv7l GNU/Linux`
* running on: `Linux 4.14.80-v7+ #1161 SMP Mon Nov 12 18:51:43 GMT 2018 armv7l GNU/Linux`

But both machines have the same architecture.

If I run the binary on a x86 architecture though, CPU is reported as expected:
```
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

**Comment by rolandjitsu** [comment]
On a side note, I'm also seeing fluentbit constantly taking 100% of the CPU (on one core) if I use the in_cpu/in_mem plugins.

**Comment by edsiper** [comment]
if you set interval_sec to one second, do you still see the issue ?

**Comment by rolandjitsu** [comment]
It's regardless of the interval. I think it's related to the other issue I reported about CPU going at peak 100% on a Raspberry Pi. As this happens on a Pi.

**Comment by edsiper** [comment]
Please provide specific steps to reproduce the problem, what's the config used to parse the log line provided above ?, if you build Fluent Bit in the target host (not cross-compile), do you see the same issue ?

**Comment by rolandjitsu** [comment]
@edsiper I will try to come back with steps to reproduce this. Do you have a Raspberry Pi available to test it on?

**Comment by edsiper** [comment]
@rolandjitsu yes I have.

**Comment by edsiper** [comment]
ping

**Comment by rolandjitsu** [comment]
I cannot see this issue anymore. It happens only when I start FB, but it doesn't peak above 400% (which is ok because there's 4 cores). Then it goes down to using 100% of one core as described in https://github.com/fluent/fluent-bit/issues/1341. So I guess you can close this issue.

**Comment by nigels-com** [comment]
Perhaps it was a previous release of fluent-bit, that exhibited the issue?

**Comment by rolandjitsu** [comment]
It occurred on `v1.0.6`, haven't seen it since upgrading to v2.

**Comment by edsiper** [comment]
could be related to a huge number of chunk files in the filesystem at start ? , in recent versions there is a new mechanism to limit that at start time which lead to less CPU usage.

but... why you see 100% CPU usage ? are you doing intensive data processing ?

**Comment by rolandjitsu** [comment]
@edsiper could you point me to these settings to limit that?

I'm not doing any processing that requires intense usage of CPU. Most other processes are under 1%. Though, we do output at high frequency to the files that FB is tailing (~50Hz).

Note that by disabling TLS as described in https://github.com/fluent/fluent-bit/issues/1341, than FB have very low CPU usage.

**Comment by agup006** [comment]
Hey all, cleaning up some older issues - this one looks resolved with a later version of Fluent Bit. We have also made better TLS improvements with OpenSSL in v1.7.0 that hopefully reduces the CPU usage. Closing for now, please re-open if needed
