### ISSUE TITLE
Provide a way to set a tag in the filtering phase.

### ISSUE THREAD

**Issue by dperetti** [fluent/fluent-bit#1326]
**Is your feature request related to a problem? Please describe.**
I would like to be able to route a record depending on the result of a filter.

**Describe the solution you'd like**
A filter that would allow to set a tag depending on some condition.
Then one could route to a different output using Match.

**Describe alternatives you've considered**
I looks like the brand new stream processor would allow me to that although I don't like the fact that this requires to be defined in the command line (so it cannot work with the current implementation of the helm chart).

**Additional context**
I have an annotation on my ingress controller that triggers a k8 ingress parsing as expected. Now I would like to route those records to a different output (a separate Elasticsearch index in my case).

**Comment by recipedude** [comment]
Have the same use case as @dperetti 

I ended up "re-tagging" using the stream processor.  It did not require to be defined on the command line; was able to be completely configured in a k8s configmap. 

fluent-bit.conf (excerpt)
```
[SERVICE]
    Parsers_File  parsers.conf
    Streams_File  stream-processor.conf
```

and stream-processor.conf is:

```
    [STREAM_TASK]
        Name   rails
        Exec   CREATE STREAM results WITH (tag='rails') AS SELECT * FROM TAG:'kube.*' WHERE kubernetes['labels']['fluentbit']='rails';
```

These files were defined in the configmap with no need to touch command-line of fluent-bit running the daemonset. 

In this case I added a label to the k8s container key off of. 

The issue that I then ran into was that this duplicated the event. That is the original event ends up in ElasticSearch along with the newly tagged even that CREATE STREAM creates.  If there were another flag/option to [STREAM_TASK] to optionally discard the original event that would be very helpful.

**Comment by edsiper** [comment]
the answer from @recipedude is correct.

In addition, if you know beforehand your records will only hit the stream processor, set that input source of data as routable off', documented in release notes here:

https://fluentbit.io/announcements/v1.2.0/

**Comment by edsiper** [comment]
FYI: re-tagging through filtering is an upcoming feature anyways

**Comment by madkote** [comment]
@edsiper also vote for this feature.

**Comment by edsiper** [comment]
This is already implemented.

ref: https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag

thanks
