### ISSUE TITLE
Input Tail Docker_mode On not working

### ISSUE THREAD

**Issue by vfreitas-cit** [fluent/fluent-bit#1327]
## Bug Report

**Describe the bug**
Tail input Docker_mode On not merging the logs

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"2019-05-15 20:05:16.805  INFO [tax,,,] 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]\n","stream":"stdout","time":"2019-05-15T20:05:16.805786249Z"}
{"log":"2019-05-15 20:05:16.901  INFO [tax,,,] 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]\n","stream":"stdout","time":"2019-05-15T20:05:16.902064972Z"}
{"log":"2019-05-15 20:05:17.001  INFO [tax,,,] 1 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=44a59da3,type=ConfigurationPropertiesRebinder]\n","stream":"stdout","time":"2019-05-15T20:05:17.002242433Z"}
{"log":"2019-05-15 20:05:17.107  INFO [tax,,,] 1 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647\n","stream":"stdout","time":"2019-05-15T20:05:17.107425313Z"}
{"log":"2019-05-15 20:05:17.107  INFO [tax,,,] 1 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed\n","stream":"stdout","time":"2019-05-15T20:05:17.198686842Z"}
{"log":"2019-05-15 20:05:17.201  INFO [tax,,,] 1 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)\n","stream":"stdout","time":"2019-05-15T20:05:17.202205629Z"}
{"log":"2019-05-15 20:05:17.507  INFO [tax,,,] 1 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references\n","stream":"stdout","time":"2019-05-15T20:05:17.508093257Z"}
{"log":"2019-05-15 20:05:20.004  INFO [tax,,,] 1 --- [ctor-http-nio-1] r.ipc.netty.tcp.BlockingNettyContext     : Started HttpServer on /0:0:0:0:0:0:0:0:8080\n","stream":"stdout","time":"2019-05-15T20:05:20.004762063Z"}

```
- Steps to reproduce the problem:
Configure docker for json log output driver
start java based container like tomcat with any sample application
configure Fluent-bit to use tail input
send the data to an output of your preference

**Expected behavior**
The Docker_mode sholud merge the logs to a single one

**Screenshots**

**Your Environment**

* Version used: 1.0
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
Kubernetes V1.13.0
* Server type and version:
Kubernetes hosting Java 8 Applications
* Operating System and version:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

* Filters and plugins:
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Docker_Mode       On
        Docker_Mode_Flush 2
        Parser            docker
        DB                /var/log/flb-containers.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Path_Key          src
        key               log

[PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        #2019-05-15T20:05:20.102994802Z
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped_utf8    log

**Additional context**

Without merging the logs, it's very hard to read Java Stack Traces

The context is a Java e-commerce, running inside Kubernetes with Docker and KOPS for AWS.
The docker logs are being sent to file using JSON format and shipped to Splunk.
I believe would be smart to create a field Docker_mode first line using a REGEX to map it.
IMproving the idea could be the option to allow multiple first line parsers with REGEX.

**Comment by etwillbefine** [comment]
I think (as you mentioned stack traces) it is also related to that one: https://github.com/fluent/fluent-bit/issues/1115
