### ISSUE TITLE
flb-it-unit_sizes fails under ubuntu 16.04 on arm

### ISSUE THREAD

**Issue by farnasirim** [fluent/fluent-bit#1328]
## Bug Report

**Describe the bug**

Lines that fail:
tests/internal/unit_sizes.c:44
tests/internal/unit_sizes.c:45
```
    TEST_CHECK(to_bytes("5g") == 5*GB);
    TEST_CHECK(to_bytes("32g") == 32*GB);
```
`ssize_t` is an int and `to_bytes` calculation/output overflows.
**To Reproduce**
- Steps to reproduce the problem:
on Arm7 rev3 32 bit, running ubuntu 16.04:
`make flb-it-unit_sizes && ./bin/flb-it-unit_sizes`

**Comment by edsiper** [comment]
thanks for reporting the problem.

Fixed by https://github.com/fluent/fluent-bit/commit/237b2e7b5c307d03e5378d4fc69b750d93847717
