### ISSUE TITLE
get rid of "log" key

### ISSUE THREAD

**Issue by markuman** [fluent/fluent-bit#1331]
## Bug Report

**Describe the bug**

I use tail to forward my logs with fluent-bit to fluentd which puts the logs to AWS  CloudWatch Logs.

In AWS CloudWatch Logs my logs are stored as a json object, even when my logs has no json format

```
m@pop-os:~$ awslogs get fluentd/testcase --start="1h ago"
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
fluentd/testcase testcase.2c73209fda4f {"log":"irgendwelche tollen 3000 logsache"}
m@pop-os:~$ awslogs get fluentd/testcase --start="1h ago" --query="log"
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
fluentd/testcase testcase.2c73209fda4f irgendwelche tollen 3000 logsache
```

The documentation says

> When a message is unstructured (no parser applied), it's appended as a string under the key name log. This option allows to define an alternative name for that key.

So I can rename the key. But how to get rid of it?

Even with a simple txt parser like that

```
[PARSER]
    Name   simple_txt
    Format regex
    Regex (.+)
```

```
[SERVICE]
    Flush           5
    Daemon          off
    Log_Level       debug

[INPUT]
    Name       tail
    Parser     simple_txt
    Path       /tmp/2nd
    Tag        testcase

[OUTPUT]
    Name stdout
    Match *
```

The "log" keyword stays alive.

**Your Environment**

fluent-bit 1.1

**Comment by edsiper** [comment]
Use the "key" property in Tail section:

https://docs.fluentbit.io/manual/input/tail

**Comment by edsiper** [comment]
note: it's mandatory that all records/logs in Fluent Bit get structured in a map, for hence, one key must exists

**Comment by markuman** [comment]
@edsiper let me show you

`echo -n "{\"key\": \"$(date)\"}" |  fluent-bit -i stdin -t testcase -o stdout`

produces

`[0] testcase: [1558366818.274547608, {"key"=>"Mo 20. Mai 17:40:18 CEST 2019"}]`

but when I used tail instead of stdin, my log object is put into the key `log`.

```
$ echo  "{\"key\": \"$(date)\"}" >> /tmp/example
$ fluent-bit -i tail -p path=/tmp/example -t testcase -o stdout
```

produces

`[0] testcase: [1558367061.534409505, {"log"=>"{"key": "Mo 20. Mai 17:43:38 CEST 2019"}"}]`

**Comment by nitrocode** [comment]
@markuman I ran into the same issue as you. Take a look at https://github.com/aws/aws-for-fluent-bit/issues/45 for more details.

**Comment by debu99** [comment]
have the same issue

**Comment by jcuna** [comment]
If you are using the cloudwatch output plugin, there's a directive `log_key` where you specify the key for what you want amazon to log it's value.

**Comment by bubbleatgit** [comment]
@markuman 

the key "log" can not remove ,because `one key must exists`.
> note: it's mandatory that all records/logs in Fluent Bit get structured in a map, for hence, one key must exists
so, we can use the filter named "nest" in our data, just like this:

## origin data output

```
Sep 22 19:40:07 lg-trust-rsyslog-server01.xxxx.com td-agent-bit[60012]: {"@timestamp":"2021-09-22T11:40:03.516Z","message":{"action":"allow","attack_type":"none","body":"","cookie":"","country":"CN","decode_path":"","dest_ip":"10.2.120.250","dest_port":81,"event_id":"bcb9976bdb3d425ca9e020c350f21984","host":"xxxxxxxxx","location":"","method":"GET","module":"","node":"chaitin-safeline","payload":"","protocol":"http","province":"北京","reason":"whitelist","referer":"","req_header_raw":"GET / HTTP/1.0\r\nHost: xxxxxx\r\nX-Forwarded-For: xxxxxxxx\r\nX-Forwarded-Proto: https\r\nX-Real-IP: xxxxxxxx\r\nConnection: close\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Charset: utf-8\r\nAccept-Encoding: gzip\r\n\r\n","resp_body":"","resp_header_raw":"","resp_reason_phrase":"","resp_status_code":"","risk_level":"none","rule_id":"/1@time-1631893715","selector_id":"","session":"","src_ip":"xxxxx","src_port":51866,"timestamp":1632310803,"timestamp_human":"2021-09-22 19:40:03","urlpath":"/","user_agent":"Go-http-client/1.1"}}

```

## Nest Filter config
```
[FILTER]
    Name nest
    Match *
    Operation lift
    Nested_under message
    Remove_prefix message
```

## result

![image](https://user-images.githubusercontent.com/7858776/134338959-890c2494-1725-4529-b1cf-4ea2e65e8208.png)
