### ISSUE TITLE
Make the arm 32 bit build available for ubuntu

### ISSUE THREAD

**Issue by farnasirim** [fluent/fluent-bit#1334]
**Is your feature request related to a problem? Please describe.**
The provided repo (e.g. `https://packages.fluentbit.io/ubuntu/xenial`) does not contain 32 bit arm builds.

**Describe the solution you'd like**
I'd like to be able to do `apt install td-agent-bit` on such machine.

**Describe alternatives you've considered**
I'm now compiling my own binary.

**Comment by ericvh** [comment]
would be nice to have 64-bit arm as well...
