### ISSUE TITLE
elasticsearch output multiple nodes support

### ISSUE THREAD

**Issue by azhurbilo** [fluent/fluent-bit#1340]
**Is your feature request related to a problem? Please describe.**

Have high-available way of delivering logs to elasticsearch nodes in cluster (failover)

**Describe the solution you'd like**
do smth like

https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#hosts-option

> he events are distributed to these nodes in round robin order. If one node becomes unreachable, the event is automatically sent to another node.

**Comment by amitsaha** [comment]
Also, what would be the current behaviour if the hostname provided to fluent-bit for ES round robins between two addresses, and say one of them dies, will fluent-bit automatically try the other one?

**Comment by jonaz** [comment]
Just started migration from beats to fluent-bit. But could not complete the migration due to this issue. Have to stick on beats for the time beeing :(

**Comment by jonaz** [comment]
We still would like this feature!

**Comment by thatsk** [comment]
is this working or still having issue
