### ISSUE TITLE
Building from GitHub source does not work on CentOS 7

### ISSUE THREAD

**Issue by JungleGenius** [fluent/fluent-bit#1345]
Is there and src.rpm available to build from?  I need to fix a bug and make a pull request but I can't get this to build on CentOS 7...

`
[root@ip-10-0-0-00 build]# cmake ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1")
-- Found Journald: /usr/lib64/libsystemd.so
-- Found Monkey: /root/fluent-bit-1.1.1/lib/monkey/include
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
Enabling FLB_REGEX since FLB_PARSER requires
-- Found GTest: /usr/lib64/libgtest.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed
-- Found Doxygen: /bin/doxygen (found version "1.8.5")
-- Performing Test HAVE_STAT_H
-- Performing Test HAVE_STAT_H - Success
-- Performing Test HAVE_SYS_UIO_H
-- Performing Test HAVE_SYS_UIO_H - Success
-- Performing Test HAVE_UNISTD_H
-- Performing Test HAVE_UNISTD_H - Success
-- Performing Test HAVE_EPOLL
-- Performing Test HAVE_EPOLL - Success
-- Performing Test HAVE_KQUEUE
-- Performing Test HAVE_KQUEUE - Failed
-- Performing Test HAVE_TIMERFD_CREATE
-- Performing Test HAVE_TIMERFD_CREATE - Success
-- Performing Test HAVE_EVENTFD
-- Performing Test HAVE_EVENTFD - Success
-- Performing Test MK_HAVE_MEMRCHR
-- Performing Test MK_HAVE_MEMRCHR - Success
-- Found PythonInterp: /bin/python (found version "2.7.5")
-- Performing Test FLB_HAVE_VALGRIND
-- Performing Test FLB_HAVE_VALGRIND - Failed
-- Performing Test FLB_HAVE_FORK
-- Performing Test FLB_HAVE_FORK - Success
-- Performing Test FLB_HAVE_TIMESPEC_GET
-- Performing Test FLB_HAVE_TIMESPEC_GET - Failed
-- Performing Test FLB_HAVE_GMTOFF
-- Performing Test FLB_HAVE_GMTOFF - Success
-- Performing Test FLB_HAVE_CLOCK_GET_TIME
-- Performing Test FLB_HAVE_CLOCK_GET_TIME - Failed
-- Performing Test FLB_HAVE_UNIX_SOCKET
-- Performing Test FLB_HAVE_UNIX_SOCKET - Success
-- Performing Test FLB_HAVE_C_TLS
-- Performing Test FLB_HAVE_C_TLS - Success
-- Performing Test FLB_HAVE_ACCEPT4
-- Performing Test FLB_HAVE_ACCEPT4 - Success
-- Performing Test FLB_HAVE_INOTIFY
-- Performing Test FLB_HAVE_INOTIFY - Success
-- Looking for accept4
-- Looking for accept4 - not found
-- Found FLEX: /bin/flex (found version "2.5.37")
-- Found BISON: /bin/bison (found version "3.0.4")
CMake Error at /usr/share/cmake/Modules/FindFLEX.cmake:116 (message):
  FLEX_TARGET(<Name> <Input> <Output> [COMPILE_FLAGS <string>]
Call Stack (most recent call first):
  src/stream_processor/parser/CMakeLists.txt:1 (flex_target)

-- Configuring incomplete, errors occurred!
See also "/root/fluent-bit-1.1.1/build/CMakeFiles/CMakeOutput.log".
See also "/root/fluent-bit-1.1.1/build/CMakeFiles/CMakeError.log".`

**Comment by nokute78** [comment]
I have the same issue.

Fluent-bit uses this Cmake syntax.
Older Cmake can't interpret it.

src/stream_processor/parser/CMakeLists.txt : 
```
flex_target(lexer   sql.l "${CMAKE_CURRENT_BINARY_DIR}/sql_lex.c"
            DEFINES_FILE "${CMAKE_CURRENT_BINARY_DIR}/sql_lex.h"
            )
```

`DEFINES_FILE` is implemented at 3.5.X.

https://cmake.org/cmake/help/v3.5/module/FindFLEX.html
https://cmake.org/cmake/help/v3.4/module/FindFLEX.html

**Comment by JungleGenius** [comment]
Thanks for the input.  Does upgrading the cmake version fix this your you?   

BTW, This is why it would be nice if they would release the source rpm as that should have all the build dependencies via the required packages list that typically has version information.

**Comment by JungleGenius** [comment]
`[root@ip-10-0-0-00 ~]# yum install cmake
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
rhui-REGION-client-config-server-7                       | 2.9 kB     00:00
rhui-REGION-rhel-server-releases                         | 3.5 kB     00:00
rhui-REGION-rhel-server-rh-common                        | 3.8 kB     00:00
td-agent-bit                                             | 2.9 kB     00:00
(1/4): epel/x86_64/updateinfo                              | 1.0 MB   00:00
(2/4): rhui-REGION-rhel-server-releases/7Server/x86_64/upd | 3.1 MB   00:00
(3/4): epel/x86_64/primary_db                              | 6.7 MB   00:00
(4/4): rhui-REGION-rhel-server-releases/7Server/x86_64/pri |  56 MB   00:01
Package cmake-2.8.12.2-2.el7.x86_64 already installed and latest version
Nothing to do
`

**Comment by JungleGenius** [comment]
It would be nice to know that their rpm build system looks like because CentOS 7.3 is cmake-2.8.12.2-2

**Comment by JungleGenius** [comment]
It anyone else out there sees this...  The answer is:

`yum install cmake3`

then

`cd build`
`cmake3 ..\`

**Comment by edsiper** [comment]
Already fixed in the documentation, thanks.
