### ISSUE TITLE
epoll_ctl error when systemd input plugin used with stackdriver output plugin

### ISSUE THREAD

**Issue by mwaylonis** [fluent/fluent-bit#1346]
## Bug Report

**Describe the bug**
On version 1.1.0, ubuntu distribution.  When using systemd as an input plugin and stackrdriver as an output plugin, the systemd logs do not get sent to stackdriver, and give the following error.

```
[  Error] epoll_ctl: Operation not permitted, errno=1 at /tmp/fluent-bit-1.1.0/lib/monkey/mk_core/mk_event_epoll.c:136
[error] [io_tls] error changing mask to 4
```

The systemd logs will _occasionally_ be sent to stackdriver successfully, but fail more often than not.

**To Reproduce**
- use systemd input plugin with stackdriver output plugin 
- config file:
```
[SERVICE]
    Flush        10
    Log_Level    trace

[INPUT]
    Name            systemd
    Tag             *
    Systemd_Filter  _SYSTEMD_UNIT=my-systemd-unit.service

[OUTPUT]
    Name  stackdriver
    Match *
```

**Expected behavior**
- Systemd logs get sent to stackdriver

**Your Environment**
* td-agent-bit distribution, Version 1.1.0 Ubuntu 16.04 
* Ubuntu 16.04 Amazon EC2 instance
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```
* Filters and plugins:
  * systemd input plugin
  * stackdriver output plugin

**Additional context**
I have successfully tested:
- random input plugin -> stackdriver
- systemd input plugin -> stdout

**Comment by edsiper** [comment]
Fixed by:

- a1518bf6
- 39650cce
