### ISSUE TITLE
Renaming keys not working

### ISSUE THREAD

**Issue by carlosrmendes** [fluent/fluent-bit#1355]
## Bug Report

**Describe the bug**
Renaming keys with modify filter plugin is not working. The new keys renamed are not showing.

**To Reproduce**
apply these filters (kubernetes environment):
```
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log           On
    K8S-Logging.Parser  On
    K8S-Logging.Exclude Off

[FILTER]
    Name modify
    Match *
    Rename kubernetes.namespace_name company
    Rename kubernetes.pod_name pod
    Remove_wildcard kubernetes
```
**Expected behavior**
logs without kubernetes keys and with the new keys `company` and `pod`

**Your Environment**

* Version used: 1.1.0
* Environment name and version (e.g. Kubernetes? What version?): 1.11.9
* Filters and plugins: kubernetes, modify

**Comment by minhdanh** [comment]
Any updates on this? Looks like I'm seeing this too.

**Comment by windrammer** [comment]
I'm also getting this behaviour. 

Version used: 1.3.7
Environment: Kubernetes 1.18.0
Filters and plugins: kubernetes, modify

**Comment by agup006** [comment]
Hey folks, I see this issue has not been updated in a while. I'm wondering if this is the difference between `rename` and `hard_rename`. Would the latter parameter be more appropriate here? https://docs.fluentbit.io/manual/pipeline/filters/modify

**Comment by q2dg** [comment]
Neither rename nor hard_rename works.

For instance, _fluent-bit -i systemd -p systemd_filter="UNIT=firewalld.service" -F modify -p "rename=message mensaje"-m "*"
-F record_modifier -p allowlist_key=mensaje -m "*" -o stdout_  doesn't show anything, but when I do _-p allowlist_key=message_ instead, then the "message" field (which in theory should have been renamed to "mensaje") is shown.

Thanks

**Comment by q2dg** [comment]
This is issue is important enough to not being staled, I think

**Comment by q2dg** [comment]
Well, I think closing stale issues is not the way. They are issues, anyway!

**Comment by q2dg** [comment]
Well, I think closing stale issues is not the way. They are issues, anyway!

**Comment by agup006** [comment]
Heya @q2dg would you be open to contributing a fix here?

**Comment by q2dg** [comment]
Sorry @agup006 I'm just an user, I've not any developer skills. Thanks anyway.

**Comment by q2dg** [comment]
This is issue is important enough to not being staled, I think

**Comment by q2dg** [comment]
Closing issues is not a good way to deal with them

**Comment by jeffery-jen** [comment]
Why is this issue being ignored when handling nested field clearly is a common place operation?
