### ISSUE TITLE
Regex valid on a td-agent-bit 1.1.1 on Debian 9.5.0 but not on a CentOS7 installation

### ISSUE THREAD

**Issue by Theoooooo** [fluent/fluent-bit#1363]
**Describe the bug**
A regex i wrote is valid on a fresh td-agent-bit installation on a Debian 9.5.0 but the same regex is invalid on a CentOS7 installation with the same version as td-agent-ibt

I test to install the same package on another CentOS and i got the same problem, the regex is not validated by td-agent-bit

**To Reproduce**
Add the treasudedata repos to CentOS, yum install td-agent-bit, paste my regex i wrote (see below), start td-agent-bit and got the error message "Regex Invalid Pattern" on the regex i paste in my parsers.conf

```
td-agent-bit[97617]: [2019/05/29 14:10:43] [error] [parser:test_regex] Invalid regex pattern
``` 
* Version used: td-agent-bit 1.1.1
* Configuration: 
Regex :
```
/(?:Rule:\s+(?<Regle>18107))(?(<Regle>)(?:.+Location:\s+\((?<Agent>[^)]+))\)\s+(?<IP_Agent>[^-]+)(?:.+Security:\s+(?<ID_Message>[^:]+))(?:.+no domain:\s+(?<Domain_Controller>[^:]+)):\s+(?<Message>[^.]+)(?:.+Logon Type:\s+(?<Logon_Type>[[:digit:]]))(?:.+Account Name:\s+(?<Compte>\S+))\s+Account Domain:\s+(?<Domain>\S+)(?:.+Source Network Address:\s+(?(?=- )(?:[^;]+)|(?<IP_Source>\S+)))?\s+Source Port:\s+(?(?=- )|(?<Port_Source>[[:digit:]]+)).+Logon Process:\s+(?<Logon_Process>\S+)\s+Authentication Package:\s+(?<Authentication_Package>\S+)|)/
```
* Operating System and version:
CentOS 7 -- Not Working
Debian 9.5.0 -- Working

**Additional context**
I can't use a regex i wrote on a production parser due to this behavior. 
But i can use it in a new debian installation for testing purpose.

# EDIT : 
After some testing, i found out what is causing td-agent-bit to struggle with this regex.

The LookAhead condition is not working with the 1.1.1 Version on CentOS. Just this regex is not validated : ``` /(?:.+Source Network Address:\s+(?(?=- )(?:[^;]+)|(?<IP_Source>\S+)))?/ ```

**Comment by edsiper** [comment]
The original regex you posted it's not working either in my Ubuntu 19.04

**Comment by Theoooooo** [comment]
@edsiper Thanks for the testing.
If you got a Debian 9.5.0 under your hand, you can test it on this OS. It's working for me on Debian

**Comment by Theoooooo** [comment]
@edsiper However the regex is valid on rubular.com.
There is something wrong about the LookAhead definition but on the official ruby regex documentation i wrote it the right way.
I will take more time about this and git an update if i got anything new

**Comment by Theoooooo** [comment]
According to this site : https://www.rubyguides.com/2015/06/ruby-regex/
The lookahead is wrote correctly :
![image](https://user-images.githubusercontent.com/33425208/58695874-b7977400-8396-11e9-8bf3-aa07b0964426.png)

**Comment by Theoooooo** [comment]
After some digging i found out what was causing the problem.
I missed a ":" at the condition :
``` /(?:.+Source Network Address:\s+(?(?=- )(?:[^;]+)|(?<IP_Source>\S+)))?/ ```
Unstead of 
``` /(?:.+Source Network Address:\s+(?:(?=- )(?:[^;]+)|(?<IP_Source>\S+)))?/ ```
In this case, it was doing a If condition unstead of a non-capturing group
Closing the issue.
