### ISSUE TITLE
logs getting duplicated with foward as input

### ISSUE THREAD

**Issue by sonirahul** [fluent/fluent-bit#1375]
I am noticing a weird behavior with fluent bit with input mode as forward. The problem is whenever I send a log to fluent bit on forward mode it gets cumulated sort of like
log0
log0
log1
log0
log1
log2

i have a way to replicate the issue as well.
1. docker run -p "24224:24224" fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -i forward -o stdout
2. docker run -t -i --log-driver=fluentd --log-opt fluentd-address=my-ip:24224 ubuntu
3. then enter this command multiple times "echo 'hi' >> /dev/null"
4. you will notice that on the fluent bit logs the log for the command at 3 command are getting repeated the way i have mentioned at top. e.g. log0, log 0, log1, log0, log1, log2

I have seen the same issue when I hit the fluent bit using a java program using the fluentd-logger. I think its a bug. Any help on this would be helpful.

**Comment by edsiper** [comment]
thanks for reporting the issue, It has been fixed on 18fea1a5

**Comment by sonirahul** [comment]
any expected date when it would be released?

**Comment by okdas** [comment]
I thought I was mad when tried to troubleshoot that issue. :)
Thanks for the fix. Seems like a serious enough bug for a quick release?

**Comment by sonirahul** [comment]
> I thought I was mad when tried to troubleshoot that issue. :)
> Thanks for the fix. Seems like a serious enough bug for a quick release?

yupp i also spent 2 plus days over it before raising it.

**Comment by sonirahul** [comment]
Anyways any tentative date of release.

**Comment by edsiper** [comment]
Today release v1.1.3 is going out with the fix.

Closing as fixed.
