### ISSUE TITLE
Debian jessie Packages Size-field is incorrect

### ISSUE THREAD

**Issue by rsommer** [fluent/fluent-bit#1376]
## Bug Report

Following the installation instructions at https://docs.fluentbit.io/manual/installation/debian for td-agent-bit on debian jessie leads to
```
E: Failed to fetch https://packages.fluentbit.io/debian/jessie/pool/main/t/td-agent-bit/td-agent-bit_1.1.2_amd64.deb  Size mismatch
```
**To Reproduce**
```
docker run --rm -ti debian:jessie /bin/bash
apt update
apt install wget apt-transport-https
wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add -
echo "deb https://packages.fluentbit.io/debian/jessie jessie main" > /etc/apt/sources.list.d/fluent.list
apt update
apt install td-agent-bit
```

**Expected behavior**
`td-agent-bit` should be installed.

**What happens instead?**
```
Get:1 https://packages.fluentbit.io/debian/jessie/ jessie/main td-agent-bit amd64 1.1.2 [1343 kB]
Fetched 1838 kB in 1s (1033 kB/s)      
E: Failed to fetch https://packages.fluentbit.io/debian/jessie/pool/main/t/td-agent-bit/td-agent-bit_1.1.2_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

The `td-agent-bit` section from `https://packages.fluentbit.io/debian/jessie/dists/jessie/main/binary-amd64/Packages` reads as:

```
Package: td-agent-bit
Priority: optional
Section: net
Installed-Size: 10976
Maintainer: Eduardo Silva <eduardo@treasure-data.com>
Architecture: amd64
Version: 1.1.2
Filename: pool/main/t/td-agent-bit/td-agent-bit_1.1.2_amd64.deb
Size: 1343488
MD5sum: 3f165e6202fa979e50bb0157b91a913f
SHA1: b6af7c1dc1cfec8f6a7c2ecd1de2da09d1515a1a
SHA256: 694d171a76fe3a6051e7fc39cf6aa724035f713cc2cdc7121acee4d923957ac5
SHA512: 51034f8f56cb9bb22ca3cf86b233bf67f01e5069cf87c1c0dd01802343d3c678c2d9853d20e66d91a5fa9df49110f0ac082c66743f95ba810646254911713ef5
Description: High performance Log Forwarder for Linux.
 Fluent Bit is a high performance data collector and log forwarder for Linux.
 It provides a flexible architecture and plugins to collect, parser, filter and
 deliver logs to different backend types.
Homepage: http://fluentbit.io
```

with `Size: 1343488`. Actual filesize when downloading `https://packages.fluentbit.io/debian/jessie/pool/main/t/td-agent-bit/td-agent-bit_1.1.2_amd64.deb` manually is `1838296`.

**Your Environment**
Legacy systems still using Debian jessie, which is specifically supported in td-agent-bit documentation at https://docs.fluentbit.io/manual/installation/debian.

**Comment by edsiper** [comment]
Please try v1.1.3 deb package which has been already pushed to the repo.

**Comment by MarcSchmitzer** [comment]
I'm afraid the issue is not fixed yet. While the v1.1.3 Package hast the correct size in the Packages file, the 1.1.2 version is still present with the wrong size. Apt is pedantic here and refuses to use the repo if any entry in the Packages file is incorrect. You'd have to either remove or fix the v1.1.3 entry in the Packages file to really fix this issue.

**Comment by edsiper** [comment]
@MarcSchmitzer please re-try , it should be ok now

**Comment by MarcSchmitzer** [comment]
@edsiper it is, thanks!
