### ISSUE TITLE
Reload feature in fluentd-bit or Dynamic reload

### ISSUE THREAD

**Issue by Allesgluck** [fluent/fluent-bit#1379]
Hi Team,

I donot see any reload feature or re-loading the dynamic config changes in fluentd w/o taking down the process. Can u please provide any insight or guide me ?

**Comment by edsiper** [comment]
There is no dynamic config reload support, that feature is delayed due to other priorities. 

Closing this question.

**Comment by RiccardoManfrin** [comment]
Is this still the case?

**Comment by FeynmanZhou** [comment]
Hope [Fluentbit-operator](https://github.com/fluent/fluentbit-operator) is helpful for you to address it.

**Comment by nickbroon** [comment]
This is probably a duplicate of #365
