### ISSUE TITLE
Splitting json log into structured fields in Elasticsearch

### ISSUE THREAD

**Issue by BentCoder** [fluent/fluent-bit#1384]
Hi,

Is there a way to tell ES to store json formatted logs (the **log** bit) in structured way? For example, splitting json fields and storing them as shown in **red** below. Filters/Parsers are not clear and `forward` doesn't have a "parser" option. I know what my [regex](https://rubular.com/r/o5nZZU2z0rjPWn) is too. Currently using ES (7.1), Fluent-bit (1.1.3) and Kibana (7.1).

```json
{
  "_index": "hello",
  "_type": "logs",
  "_id": "T631e2sBChSKEuJw-HO4",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-06-21T21:34:02.000Z",
    "tag": "php",
    "container_id": "53154cf4d4e8d7ecf31bdb6bc4a25fdf2f37156edc6b859ba0ddfa9c0ab1715b",
    "container_name": "/hello_php_1",
    "source": "stderr",
    "log": "{\"time_local\":\"2019-06-21T21:34:02+0000\",\"client_ip\":\"-\",\"remote_addr\":\"192.168.192.3\",\"remote_user\":\"\",\"request\":\"GET / HTTP/1.1\",\"status\":\"200\",\"body_bytes_sent\":\"0\",\"request_time\":\"0.001\",\"http_referrer\":\"-\",\"http_user_agent\":\"curl/7.38.0\",\"request_id\":\"91835d61520d289952b7e9b8f658e64f\"}"
  },
  "fields": {
    "@timestamp": [
      "2019-06-21T21:34:02.000Z"
    ]
  },
  "sort": [
    1561152842000
  ]
}
```

Thanks

**conf**
```bash
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    Parsers_File parsers.conf

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[OUTPUT]
    Name  es
    Match hello_*
    Host  elasticsearch
    Port  9200
    Index hello
    Type  logs
    Include_Tag_Key On
    Tag_Key tag
```

![ssss](https://user-images.githubusercontent.com/8837278/59468775-d1bb6280-8e2a-11e9-8025-290f61ea0cb6.png)

**Comment by epcim** [comment]
Kubernetes has Merge_log option
Otherwise you can always use json parser + https://fluentbit.io/documentation/0.13/filter/nest.html (lift)

**Comment by BentCoder** [comment]
Thanks for the response but I must say the documentation is pretty poor. I've been reading it for hours and couldn't work it out. I've just hit a brick wall! Also I am not using Kubernetes.

**Comment by BentCoder** [comment]
Hi @edsiper I know you have been on parsing json stuff but is there a solution for my case above please?

**Comment by BentCoder** [comment]
Seriously, can someone answer please? **I READ THE DOC MANY TIMES!**

**Comment by BentCoder** [comment]
https://github.com/fluent/fluent-bit/issues/1492
