### ISSUE TITLE
Flatten fields, kubernetes filter creates object field

### ISSUE THREAD

**Issue by fpytloun** [fluent/fluent-bit#1386]
**Is your feature request related to a problem? Please describe.**

This issue might be related to https://github.com/fluent/fluent-bit/issues/1278

We are using kubernetes filter to add pod information to log.
Since version 1.2.0, it became to create object field like following:
```
{
   "labels" : {
      "name" : "maurice",
      "app" : "maurice",
      "pod-template-hash" : "736361076"
   },
   "namespace_name" : "ves-system",
   "pod_id" : "216a3d02-8c7f-11e9-bb5f-2203474c3ceb",
   "pod_name" : "maurice-c7b7b54cb-jp7z7",
   "container_name" : "maurice",
   "annotations" : {
      "fluentbit.io/parser-etcd-check" : "initscript",
      "ves.io/app_id" : "633b5a63-1274-4d8a-97b0-71a43efe7502",
      "checksum/config" : "077ea092006d5b01a81fb74bb5c5b7216fc95d52f4b236810fe7831ca50cd4b9",
      "fluentbit.io/parser-maurice" : "serviceframework"
   },
   "host" : "aks-agentpool-42065748-5",
   "docker_id" : "a84c3a4a66d960588eec42002310edc51660147dbe19b834ed135655674b78a6"
}
```

In version 1.1.1, it used to create multiple fields using `.` as a separator, eg. `kubernetes.pod_name`, `kubernetes.labels.app`, etc.

Object field is fine but doesn't allow to analyze fields in Kibana so it cannot be used in the same way as it could be used in version 1.1.1.

As a workaround, it's possible to use `flatten_hash` plugin on fluentd side:
```
    <filter kube.**>
      @type flatten_hash
      separator .
      flatten_array false
    </filter>
```

**Describe the solution you'd like**

There are two solutions, it would be great to have both:

1. Add option to kubernetes filter to create dot-separated fields like in v1.1.1
2. Add flatten hash filter functionality

**Describe alternatives you've considered**

```
    <filter kube.**>
      @type flatten_hash
      separator .
      flatten_array false
    </filter>
```

**Comment by ffscl** [comment]
Does the lift feature do what you need? https://docs.fluentbit.io/manual/filter/nest
