### ISSUE TITLE
Ability to use kubernetes plugin to add metadata to log files not in stdout/stderr

### ISSUE THREAD

**Issue by alvinhom** [fluent/fluent-bit#1394]
We like to use fluentbit in our logging infrastructure.  However, due to the legacy applications, not all containers log to stdout/stderr.  There are a large # of them that just logs to multiple files on the filesystem.

We are currently using fluentd (switching to fluentbit) side-cars for this, but found the side-car pattern to be inefficient.  We have thousands of containers, and it is not efficient to have thousands of side-cars.

We like the daemonset approach but we need to extract the kubernetes metadata.  Right now, the log files are stored either using emptydirs or pvcs.  Either way, these files are mounted into the host filesystem and accessible to a daemonset with host volumes.

So, we would like to do something similar as stdout/stderr but with arbitrary files.  The file directory will have the pod_uid embedded into it, something like:

/var/lib/origin/openshift.local.volumes/pods/01ff87b3-70c5-11e9-80a2-005056885181/volumes/kubernetes.io~empty-dir/my_log

So, if we can use the kubernetes plugin to extract metadata using pod_uid instead of namespace, pod name, we can extract the metadata for this.

I have forked the repo and make a version of this that works for my use case.  I am interested in seeing if there is interest so I can merge this into the main code.

**Comment by apamildner** [comment]
I hit the same probleme here some 5 years later. Feels like a nice solution when you need to migrate away from the sidecar pattern for legacy applications. Or are there better methods now? Otherwise it would be really nice to have this option as a feature in fluentbit.

**Comment by junneyang** [comment]
@apamildner @alvinhom 
same problem,
looking forward to the solution, thanks !
