### ISSUE TITLE
the filter modify or record_modifier for json  add whitespace after comma

### ISSUE THREAD

**Issue by luoweb** [fluent/fluent-bit#1396]
can modify or record_modifier for json do not add whitespace? or how to remove modify or record_modifier for json do not add whitespace, or how to remove it

for example:
the way to  format json is different between fluentd and fluent-bit,  as fluent-bit has whitespace after comma

for fluentd:
{"logTime":"2019-06-19T17:49:09.250","logContent":"+0800 [ca] readCertificateByHash -> DEBU 6939 *CA) readCertificateByHash, hash=[c08b6360cc1219b912354a3588e479ad1d4cea22760707574e8cc4eea7396728]","hostIP":"icbc-4","hostName":"ca0-0q399","logName":"applog.ca0-0q399.laisheng-22188_ca0_log.data.var.hyperledger.log.ca.log","logType":"applog","appName":"f-bctp","destination":"both","@log_name":"applog.ca0-0q399.laisheng-22188_ca0_log.data.var.hyperledger.log.ca.log","time":1560937749}

for fluent bit:
{"@timestamp":1561031638.791345, "logContent":"2019-04-03T16:30:03.520 [shim] DEBU : [e00b9480]Received message RESPONSE from shim\n", "stream":"stderr", "logTime":"2019-04-03T16:30:03.521523178Z", "hostIP":"b98e9c421c38", "hostName":"b98e9c421c38", "logName":"applog.chaincode.log", "logType":"applog", "appName":"f-bctp", "destination":"both", "@log_name":"b98e9c421c38", "time":1561031638, "log_name":"test"}

**Comment by edsiper** [comment]
JSON formatter is adding the empty space, it will be fixed.

**Comment by edsiper** [comment]
Fixed on GIT master. Closing the ticket.
