### ISSUE TITLE
Stream processor SQL statement WHERE key NOT EXISTS fails

### ISSUE THREAD

**Issue by rolandjitsu** [fluent/fluent-bit#1397]
## Bug Report

**Describe the bug**

Running the following stream SQL query makes FB throw:
```
# [STREAM_TASK]
#     Name   metrics
#     Exec   CREATE STREAM metrics WITH (tag='metrics') AS SELECT * FROM TAG:'metrics_src' WHERE event NOT EXISTS;
```

I just want to parse records that do not contain the key `event`.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2019/06/21 10:34:03] [error] [sp] syntax error, unexpected NOT, expecting GROUP_BY or AND or OR or ';' at 'CREATE STREAM metrics WITH (tag='metrics') AS SELECT * FROM TAG:'metrics_src' WHERE event NOT EXISTS;'
[2019/06/21 10:34:03] [error] [sp] invalid query on task 'metrics': 'CREATE STREAM metrics WITH (tag='metrics') AS SELECT * FROM TAG:'metrics_src' WHERE event NOT EXISTS;'
[2019/06/21 10:34:03] [error] [sp] could not initialize stream processor
[2019/06/21 10:34:03] [error] [engine] could not initialize stream processor
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: v1.1.1 (also tried latest master)
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Raspberry Pi
* Server type and version:
* Operating System and version:
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
* Filters and plugins:

**Additional context**

**Comment by rolandjitsu** [comment]
I've also tried:
```
[STREAM_TASK]
    Name   metrics
    Exec   CREATE STREAM metrics WITH (tag='metrics') AS SELECT * FROM TAG:'metrics_src' WHERE event IS NULL;
```

**Comment by edsiper** [comment]
the handling of key existence and null values are handled in v1.2 release (to be out next week).

**Comment by rolandjitsu** [comment]
@edsiper is it in master? Because I tried out the master branch, but it doesn't work with `WHERE key NOT EXISTS`, though it works with `key IS NULL`.
