### ISSUE TITLE
Allow regular expression match in `Systemd_Filter`

### ISSUE THREAD

**Issue by amitsaha** [fluent/fluent-bit#1401]
**Is your feature request related to a problem? Please describe.**

I am often writing something like this in my fluent bit configuration:

```
Systemd_Filter _SYSTEMD_UNIT=x-app.service
Systemd_Filter _SYSTEMD_UNIT=x-worker.service
Systemd_Filter _SYSTEMD_UNIT=x-monitoring.service
..
```

**Describe the solution you'd like**
It would be nice to be able to say:

```
Systemd_Filter _SYSTEMD_UNIT=x-*.service
```

**Describe alternatives you've considered**

NA

**Additional context**

May be `fluent-bit` calls out directly to the journalctl libraries which is why this restriction exists.

**Comment by edsiper** [comment]
Implementing that regex approach will provide a performance penalty. Fluent Bit uses systemd libraries to talk to Journal and get the records, that API provides such interfaces to ask only for specific units or other criteria. Providing a regex for "everything", means that Fluent Bit will need to ask for "ALL" journal data and apply a simple regex for each one. That's not desired, it's better to write more config lines.
