### ISSUE TITLE
how to control fluent-bit output speed

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-bit#1402]
I use fluentd output for kafka or elasticsearch. Because kafka and elasticsearch all have limit speed of data send. So I want to know how to control fluent-bit output speed, and also use for multi users in limited bandwidth environment

**Comment by edsiper** [comment]
you can setup Mem_Buf_Limit, read more about it here:

https://docs.fluentbit.io/manual/configuration/backpressure
