### ISSUE TITLE
JSON handling of \a & \v

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#1415]
The following issue is to track the problem reported on https://github.com/fluent/fluent-bit/issues/1278#issuecomment-508157174 .

> @edsiper Am I correct thinking that with those fixes v1.2 will still output (invalid) \v in a HTTP json output? (meaning, item named Output encoding issues in the bug description is still open ?)
> 
> For example, a docker container running a command like this: echo -e one\\vtwo will yield a docker log file with: {"log":"one\u000btwo\n","stream":"stdout","time":"2019-07-03T15:40:19.840758223Z"} and fluent-bit sends out a payload like this: [{"date":"2019-07-03T15:40:19.840758Z", "log":"one\vtwo\n", "stream":"stdout", "time":"2019-07-03T15:40:19.840758223Z"}]

**Comment by edsiper** [comment]
The following commits have been merged to address the issue:

9b00fad : encoding fix
efdcc2a: add more unit tests

**Comment by jraby** [comment]
Thank you @edsiper !
