### ISSUE TITLE
Syslog Input and Filter Parser for combining different regex on same input - not working?

### ISSUE THREAD

**Issue by ntavares** [fluent/fluent-bit#1417]
## Bug Report

**Describe the bug**
[The docs for the Syslog Input](https://docs.fluentbit.io/manual/v/1.2/input/syslog) imply that there's always a Parser associated with it (which is unlike the examples I've seen for, e.g., routing). After reading [#348](https://github.com/fluent/fluent-bit/issues/348), I tried to implement something like [#363](https://github.com/fluent/fluent-bit/issues/363) by specifying a "catchall" parser with minimal parsing. By tagging the input, I was expecting it to allow it to be catched by the Filter's Match "syslog.*", but this doesn't seem to be working. Since I've added the catchall parser to the Input plugin, all the messages are left with the catchall structure (that is: the Filter Parser seems to not trigger at all).

After spending quite some hours around this, I'm wondering if there is any specific limitation in my reasoning?

**Expected behavior**
The Filter Parser should be parsing the output of the Input.

**Your Environment**
* Version used: 1.2
* Configuration:
```
  [INPUT]
    Name      syslog-udp
    Listen    0.0.0.0
    Port      5140
    Mode      udp
    Tag       syslog.udp
    Parser    syslog-catchall
  [INPUT]
    Name      syslog-tcp
    Listen    0.0.0.0
    Port      5140
    Mode      tcp
    Tag       syslog.tcp
    Parser    syslog-catchall
  [FILTER]
    Parser         filter-sm-ipmi-syslog
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       message
    Match          syslog.*
  [FILTER]
    Parser         filter-sm-switch-syslog
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       message
    Match          syslog.*
  [OUTPUT]
    Name      stdout
    Match     *
```
* Environment name and version (e.g. Kubernetes? What version?): fluent-bit docker image (running on Kubernetes), but exposed as a UDP/TCP syslog server.
* Operating System and version: Official fluent-bit 1.2 docker image.

**Additional context**
I have distinct devices submitting rsyslog-like messages. They're sorts of embedded devices that do not follow the same format between them. For this reason, I need fluent-bit to try several regex (from the Syslog input plugin) until one matches - or, at least, fallback to a default one.

Note that if I test individual devices with the individual regex (basically the same used with Filter Parser, but trimmed down to skip the fields already caught by the catchal), that works, I have them correctly parsed and output. However, while I'm testing one device, I cannot get the other devices' messages.

I've tried debugging this with the "trace" Log_Level, in the hope I could see my message traversing the different components, but it doesn't help (I'm actually having the same output than 'debug').

**Comment by edsiper** [comment]
@ntavares 

hi, 

looking at your configuration I see your Filters are __not__ loading the proper plugin, e.g:

```
[FILTER]
    Parser         filter-sm-ipmi-syslog
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       message
    Match          syslog.*

[FILTER]
    Parser         filter-sm-switch-syslog
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       message
    Match          syslog.*
```

None of the filters above is loading a plugin for processing, I suspect you want to use the [Parser Filter](https://docs.fluentbit.io/manual/filter/parser) , so your config should look like this:

```
[FILTER]
    Name           parser
    Match          syslog.*
    Parser         filter-sm-ipmi-syslog
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       message

[FILTER]
    Name           parser
    Match          syslog.*
    Parser         filter-sm-switch-syslog
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       message
```

changes:

- add "Name parser" <- load the parser plugin
- Move the match rule after the name, this is a good practice for config readability.

**Comment by ntavares** [comment]
Hi @edsiper thanks for the quick reply. Indeed that solved it, I guess at some point I started trimming config and just lost track of it. Sorry for wasting your time! :(

**Comment by edsiper** [comment]
no waste of time :)

**Comment by vikasmishra17** [comment]
Hi,

Fluent-bit is not picking the picking the messages that the server is receiving through tcpdump, Instead of that Fluent-bit is sending the system syslogs to the server itself.

My configuration

[INPUT]
Name syslog
mode tcp
Listen 0.0.0.0
Port 514
tag syslog.tcp
Parser syslog-modified

[FILTER]
Name parser
Match syslog.*
Parser syslog-modified
Preserve_Key On
Reserve_Data On
Key_Name log

[OUTPUT]
name stdout
match *
& We are not getting any thing in the logs too
