### ISSUE TITLE
go proxy: FLBPluginExit not invoked

### ISSUE THREAD

**Issue by sriduth** [fluent/fluent-bit#1421]
**Is your feature request related to a problem? Please describe.**
The `FLBPluginExit` function is not called for external plugins loaded as shared objects when SIGKILL / SIGTERM / SIGINT is sent to the fluent-bit process.

**Describe the solution you'd like**
We can support the `FLBPluginExit` callback as follows:

In `flb_output.c` check if the output plugin is supported by a proxy`:
```c
if(!p->proxy) {
    p->cb_exit(ins->context, config);
} 
else {
    p->cb_exit(ins->p, config);
}
```

Changes can be further made in the `flb_plugin_proxy.c` `flb_proxy_register_output` function to set the `cb_exit` callback.

**Describe alternatives you've considered**

Currently we have a system in place that runs outside of fluentbit to catch potential issues - this is specific to the GZip file output being implemented as an external plugin.

**Additional context**
If it was required to implement a GZip file output plugin - if fluent bit exits before the plugin can 'rotate' the GZip file, it will not be a recognized as a valid file. For example, if the generated GZip files need to be uploaded to S3 for consumption in AWS Athena, a corrupt / invalid GZip file can cause queries to fail.

In this case if the exit handler was called on time, the plugin can close the GZip stream in the correct manner.

fluent-bit commit used to verify issue: 8eb8ac4b38558901a2944fe463f137d070bc2fdf

To verify, the go stdout example plugin was used from the `https://github.com/fluent/fluent-bit-go` repository, adding a `print` in the plugin exit callback.

**Comment by edsiper** [comment]
cc: @fluent/golang-maintainers @wfernandes

**Comment by sriduth** [comment]
I've made a PR with minimal changes to call the exit callback for go plugins. Also added the change to pass the remote context to the callback in case there is state / data in the remote context that is necessary for the plugin to perform a clean exit.

**Comment by edsiper** [comment]
ping @wfernandes @fluent/golang-maintainers

**Comment by PettitWesley** [comment]
I tested this with one of the AWS Go plugins; it works.

```
[2020/02/10 01:34:31] [ warn] [GO] running exit callback
WARN[0018] FLBPluginExit was actually called!
```

Without this change, I can confirm that it doesn't work.
