### ISSUE TITLE
mergeJSONLog causes mapper_parsing_exception 

### ISSUE THREAD

**Issue by mtparet** [fluent/fluent-bit#1422]
## Bug Report

**Describe the bug**
When `mergeJSONLog` is set to `true`, we have conflicts (error returned by elasticsearch) with multiple types for a same field. As it seems there is no way to automatically split 
output index(s) by kubernetes metadata (labels / release / container_name), we don't see a solution for this issue.

**To Reproduce**
- Output to ES
- mergeJSONLog is true
- Send json logs with different types for same field.
- Example log message if applicable:
```
{"took":7,"errors":true,"items":[{"index":{"_index":"fluentbit-2019.07.05","_type":"flb_type","_id":"eRQv0WsBX9njU8gvcqg9","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [job_args] of type [text]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:2531"}}}},
```
**Expected behavior**
Be able to use fluentbit for applications logging same field with different types.

**Your Environment**
* Version used: 1.2.0
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.13.5
* Server type and version:
* Operating System and version:  Ubuntu 16.04
* Filters and plugins:
```
[FILTER]
        Name                kubernetes
        Match               {{ .Values.filter.kubeTag }}.*
        Kube_URL            {{ .Values.filter.kubeURL }}
        Kube_CA_File        {{ .Values.filter.kubeCAFile }}
        Kube_Token_File     {{ .Values.filter.kubeTokenFile }}
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
[OUTPUT]
Name  es
Match *
Host  es.elk
Port  9200
Logstash_Format On
Retry_Limit 5
Type  flb_type
Time_Key @timestamp-flb
Replace_Dots On
Logstash_Prefix fluentbit
```

**Comment by mtparet** [comment]
It seems more a parsing/encoding issue in fact.

**Comment by edsiper** [comment]
Elastic don't support the same field of different types.

**Comment by donbowman** [comment]
I use:
```
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log_Key       values
    Reserve_Data        On
    Merge_Log           On
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Regex_Parser        kube-tag
```

as a work-around, this puts all the merged values uner a new key.
