### ISSUE TITLE
Presence of LD_PRELOAD env var breaks Fluent Bit

### ISSUE THREAD

**Issue by rolandjitsu** [fluent/fluent-bit#1425]
## Bug Report

**Describe the bug**

I noticed that if I start fluent-bit as a service using a unit file and if the unit loads env variables from some file that contains `LD_PRELOAD`, fluent-bit doesn't work anymore. And there seems to be no error or log or anything.

E.g. of env var that is set by uv4l in `/etc/environment`:
```
DEV_MODE=dev
LD_PRELOAD=/usr/lib/uv4l/uv4lext/armv6l/libuv4lext.so
```

And the service unit:
```
[Unit]
Description=Fluent Bit
Requires=network.target
After=network.target

[Service]
Type=simple
Environment="DEV_MODE=dev"
EnvironmentFile=/etc/environment
ExecStart=/bin/bash -c "/home/pi/bin/fluent-bit -c /home/pi/config/fluent-bit/fluent-bit.$DEV_MODE.conf"
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

I experienced this after I installed uv4l lib that I use to run a streaming server for the Raspberry Pi camera.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

Fluent Bit should not be affected by other env variables.

**Screenshots**

**Your Environment**

* Version used: v1.2.0
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version: Raspbian GNU/Linux 9 (stretch)
* Filters and plugins:

**Additional context**

**Comment by nazar554** [comment]
`LD_PRELOAD` worked fine for me (replacing `malloc`), can you post the output of `nm -D /usr/lib/uv4l/uv4lext/armv6l/libuv4lext.so` ?

**Comment by rolandjitsu** [comment]
Unfortunately I moved away from uv4l and I'm using a lighter lib. I can try to install the package again and run the cmd, but only some time next week.

**Comment by edsiper** [comment]
can you reproduce the issue ? and.. is this a Fluent Bit issue ?

**Comment by rolandjitsu** [comment]
You could try installing fluent bit and uv4l on the same os, and run fluent bit as a systemd service that loads the env file as `EnvironmentFile=/etc/environment`.

**Comment by edsiper** [comment]
I am not familiar with uv4l, what's the expectation on this LD_PRELOAD and integration with Fluent Bit?

**Comment by rolandjitsu** [comment]
Fluent bit should work regardless of what `LD_PRELOAD` is set to. But as I mentioned, I moved away from uv4l as it was not suitable for my use case. Therefore, as far as I'm concerned, you can close this issue.

**Comment by edsiper** [comment]
Closing for now
