### ISSUE TITLE
Regexp : fluent-bit ignores group matching

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#1433]
## Bug Report

**Describe the bug**
group match is ignored.

`test` and `(test)` should match string "test".
However `(test)` doesn't match.

**To Reproduce**
- Rubular link if applicable:
https://rubular.com/r/NXXjN4Dp0jXrWb (what we expected)
- Example log message if applicable:
none
- Steps to reproduce the problem:

```
[INPUT]
    Name  dummy
    Tag   test
    dummy {"match":"test"}

[FILTER]
    Name     grep
    Match    *
    Exclude  match (test)

[OUTPUT]
    Name   stdout
    Match  *
```

Event is not excluded.
```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/07/10 18:13:53] [ info] [storage] initializing...
[2019/07/10 18:13:53] [ info] [storage] in-memory
[2019/07/10 18:13:53] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/07/10 18:13:53] [ info] [engine] started (pid=28523)
[0] test: [1562750034.000905148, {"match"=>"test"}]
[1] test: [1562750035.001155696, {"match"=>"test"}]
[2] test: [1562750036.000513506, {"match"=>"test"}]
[3] test: [1562750037.000842280, {"match"=>"test"}]
```

**Expected behavior**
(see Rubular link)

**Screenshots**

**Your Environment**

* Version used: v1.3.0 (git master)
* Configuration: (see above)
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version: 
* Operating System and version: CentOS 6
* Filters and plugins: filter_grep

**Additional context**
I think `flb_regex_do` has a bug.

In this case, `onig_search` returns 0 (= matched).
However, `region->num_regs` = 2.
So finally `flb_regex_do` returns 1 ( != matched.)

flb_regex_do:
```c
    ret = region->num_regs - 1;

    if (ret == 0) {
        result->region = NULL;
        onig_region_free(region, 1);
    }

    return ret;
}
```

**Comment by edsiper** [comment]
thanks for the research.

related and solution available: https://github.com/fluent/fluent-bit/pull/903

to be reviewed shortly

**Comment by edsiper** [comment]
@nokute78 I've cleaned up the conflicts on #903. 

if you have time, would you please validate the fix proposed?

**Comment by nokute78** [comment]
@edsiper Thanks. 
#903 fixes my issue and https://github.com/fluent/fluent-bit/issues/1270#issue-431712014 , but the PR removes `build` directory.

**Comment by edsiper** [comment]
thanks @nokute78 , I will merge #903 manually with a fix for build/ stuff

**Comment by edsiper** [comment]
Fixed by:

- a877165c filter_grep: use new regex_find() API and fix group matching (#1270)
- 6ef8cb81 filter_modify: use new regex_find() API and fix group matching (#1433)
- 670647ee regex: add_flb_regex_match to simplify matching

thanks!

note: I will include these fixes into v1.2.2 release for next week

**Comment by edsiper** [comment]
Fixed

**Comment by nokute78** [comment]
@edsiper Thanks!
