### ISSUE TITLE
mpack: compilation error on CentOS 6/7

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#1441]
## Bug Report

**Describe the bug**
Compilation error on CentOS 7.
C99 style of mpack causes. gcc of Cent OS 7 can't compile by default.

e.g.
```c
bool mpack_str_check_no_null(const char* str, size_t bytes) {
    for (size_t i = 0; i < bytes; ++i)
```

**To Reproduce**
- Rubular link if applicable:
None 
- Example log message if applicable:
None
- Steps to reproduce the problem:
```
$ cmake3 .. && make
```

**Expected behavior**
Buildable.

**Screenshots**
None

**Your Environment**
* Version used: git master
* Configuration: none
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: CentOS 6/7
* Filters and plugins: None

**Additional context**
Workaround is to use -std=gnu99  or c99.

gcc 5 supports gnu11 by default.
https://www.gnu.org/software/gcc/gcc-5/changes.html

Do we need to check compiler and its version?
```diff
diff --git a/lib/mpack-amalgamation-1.0/CMakeLists.txt b/lib/mpack-amalgamation-1.0/CMakeLists.txt
index bbf2ecd..b0fd081 100644
--- a/lib/mpack-amalgamation-1.0/CMakeLists.txt
+++ b/lib/mpack-amalgamation-1.0/CMakeLists.txt
@@ -1,6 +1,6 @@
 set(src
   src/mpack/mpack.c
   )
-
+add_definitions(-std=gnu99)
 add_definitions(-DMPACK_EXTENSIONS=1)
 add_library(mpack-static STATIC ${src})
```

**Comment by edsiper** [comment]
Is it because variable declaration inside the loop?

**Comment by nokute78** [comment]
Yes.

Note: libjemalloc also uses C99 style declaration.
It may be better to compile in the same way.

https://github.com/fluent/fluent-bit/blob/15f6a9e3601fc53b3bfe37cf1608807808a262a7/lib/jemalloc-5.1.0/src/jemalloc.c#L744

**Comment by edsiper** [comment]
@nokute78 what's the specific compiler version ? I would like to pass the info to mpack author

**Comment by nokute78** [comment]
Maybe gcc 4.8.x. Default version of CentOS7.
 I will tell you tommorow. I can't access my PC now.. 

By the way , similar issue and PR are already reported on mpack repo.
PR is not merged and closed.
https://github.com/ludocode/mpack/issues/67
https://github.com/ludocode/mpack/pull/68

**Comment by edsiper** [comment]
I've posted the issue in mpack repo:

https://github.com/ludocode/mpack/issues/69

**Comment by nokute78** [comment]
@edsiper Thank you.

**Comment by edsiper** [comment]
update:

- latest mpack has been merged
- refs: 900c40c3 a1bd32ad

fixed, thanks again.

**Comment by nokute78** [comment]
@edsiper Thank you.
