### ISSUE TITLE
Message are not parsing correctly from syslog-ng

### ISSUE THREAD

**Issue by vaibhavt19** [fluent/fluent-bit#1444]
I'm new at FluentD and trying to parse my application logs through syslog-ng logs to fluentd but I'm getting the error on parsing the message. At first I thought it was due to timestmap, i have tried many combinations but it's not working.
Also getting the duplicate logs on ourput file, i think the issue is the second date field in raw message but don't know how to fix it. 

## FluentD configuration
```
<source>
  @type syslog
  port 1517
  tag firehose
  protocol_type tcp
  append true
  time_format %b %d %H:%M:%S
  #message_format rfc3164
</source>
<match *.**>
  @type file
  path  /firehose/%Y/%m/%d.log
  buffer_type memory
  compress text
  append true
</match>

```

```

**Comment by nokute78** [comment]
Hi. 
Is this an issue of fluentd?

If so, how about reporting on fluentd repo?
Here is fluentbit repo.
https://github.com/fluent/fluentd/issues

Thank you.

**Comment by vaibhavt19** [comment]
Done. Thank you.

**Comment by edsiper** [comment]
Not a Fluent Bit issue, closing
