### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by mhausenblas** [fluent/fluent-bit#1475]
In order for users to assess Fluent Bit, it would be desirable to have a benchmark that covers performance and resource usage. This benchmark could include throughput for various payloads and protocols (HTTP/TCP) as well as resource usage (CPU/MEM, compare with what we did in [Centralized Container Logging with Fluent Bit](https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/)). In addition, the benchmark could be used to compare different Fluent Bit releases.

**Comment by mhausenblas** [comment]
@edsiper WDYT?

**Comment by StevenACoffman** [comment]
For reference:
Recently [AWS ran some benchmarks](https://aws.amazon.com/blogs/opensource/centralized-container-logging-fluent-bit/):
> To get a better feeling for the performance, we performed a benchmarking test to compare the above Fluent Bit plugin with the Fluentd CloudWatch and Kinesis Firehose plugins. All our tests were performed on a c5.9xlarge EC2 instance. Here are the results:

### CloudWatch Plugins: Fluentd vs Fluent Bit

|Log Lines Per second|Data Out|Fluentd CPU|Fluent Bit CPU|Fluentd Memory|Fluent Bit Memory|
|--- |--- |--- |--- |--- |--- |
|100|25 KB/s|0.013 vCPU|0.003 vCPU|146 MB|27 MB|
|1000|250 KB/s|0.103 vCPU|0.03 vCPU|303 MB|44 MB|
|10000|2.5 MB/s|1.03 vCPU|0.19 vCPU|376 MB|65 MB|

> Our tests show that the Fluent Bit plugin is more resource-efficient than Fluentd. On average, Fluentd uses over four times the CPU and six times the memory of the Fluent Bit plugin.

### Kinesis Firehose Plugins: Fluentd vs Fluent Bit

|Log Lines Per second|Data Out|Fluentd CPU|Fluent Bit CPU|Fluentd Memory|Fluent Bit Memory|
|--- |--- |--- |--- |--- |--- |
|100|25 KB/s|0.006 vCPU|0.003 vCPU|84 MB|27 MB|
|1000|250 KB/s|0.073 vCPU|0.033 vCPU|102 MB|37 MB|
|10000|2.5 MB/s|0.86 vCPU|0.13 vCPU|438 MB|55 MB|

> In this benchmark, on average Fluentd uses over three times the CPU and four times the memory than the Fluent Bit plugin consumes. Keep in mind that this data does not represent a guarantee; your footprint may differ. However, the above data points suggest that the Fluent Bit plugin is significantly more efficient than Fluentd.

**Comment by StevenACoffman** [comment]
Other semi-recent benchmark example:
[OutCold Solutions compared fluent-bit fluentd and collectord](https://www.outcoldsolutions.com/blog/2018-11-19-performance-collectord-fluentd-fluentbit/)

I would prefer to have a benchmark that showed:
- **U** = Utilization, as canonically defined
- **S** = Concurrency
- **E** = Error Rate, as a throughput metric
- **R** = Request Throughput, in requests per second
- **E** = Request Error Rate, as either a throughput metric or a fraction of overall throughput
- **D** = Latency, Residence Time, or Response Time; all three are widely used

**Comment by edsiper** [comment]
hey folks, just wanted to let you know that I have published a new Performance Tools project, designed for Fluent Bit as the main purpose and can be used to test other log processors too.

This is not about benchmarking against others, but the foundation for a continuous performance tests of Fluent Bit v/s Fluent Bit on different versions, conditions, and setup:

https://github.com/fluent/fluent-bit-perf

**Comment by edsiper** [comment]
new flb-tcp-writer tool has landed:

https://github.com/fluent/fluent-bit-perf

used to test in_tcp and in_syslog (tcp mode) input plugins.

**Comment by ingshtrom** [comment]
I know this is old, but @PettitWesley do you have any information on how exactly you achieve that throughput? I'm trying to send a measly 2000 records per second at 1MiB/s and hitting a lot of `mem buf overlimit` warnings, even with 8 workers. You were able to achieve this pre-worker support, right?

**Comment by PettitWesley** [comment]
@ingshtrom if you are getting mem buf overlimit errors, increase the value for that setting. Its one of the main config options which can impact throughput. 

The tests that I ran are similar to what is discussed at the end of this blog: https://aws.amazon.com/blogs/containers/under-the-hood-firelens-for-amazon-ecs-tasks/

I've forgotten a lot of the details of how I ran those tests unfortunately. I put some stuff here but I think its not everything I used for those benchmarks: https://github.com/aws-samples/amazon-ecs-firelens-under-the-hood

**Comment by ingshtrom** [comment]
@PettitWesley Ok, I'm trying that now. I hadn't really tried this in the past because I though the memory buffer was just a temporary place to hold processed records. So the way I understood it, say I have an input, some filters, and then some outputs... The records come in, get processed by all filters it matches, and then is put in a memory buffer for each output. Then each output will process that memory buffer as fast as it can. In this example, I don't understand how increasing the size of the buffer helps. Wouldn't scaling the output plugins to consume faster help to reduce the memory buffer from filling up in the first place?
