### ISSUE TITLE
Tag_Regex in input plugin "tail" is not working, I keep getting [in_tail] invalid 'tag_regex' config value error

### ISSUE THREAD

**Issue by jayeshnazre** [fluent/fluent-bit#1477]
## Bug Report

**Describe the bug**

Tag_Regex in input plugin "tail" is not working, I keep getting [in_tail] invalid 'tag_regex' config value error

**To Reproduce**
- Rubular link if applicable: I used https://rubular.com/ to confirm the regular expression is valid.

- Example log message if applicable:
```
{"log":"2019-07-26 10:39:34.771  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'\n","stream":"stdout","time":"2019-07-26T10:39:34.77139027Z"}

```
- Steps to reproduce the problem:
**Step1:** 
Use the following config file

[INPUT]
    Name    tail
    Tag               mydoc.<Log-Level>
    Tag_Regex    `^{"log":"([0-9-:`` .]*)(?<Log-Level>[A-Z]*)`
    Path    mydocker.sample.log
    Parser  docker

[OUTPUT]
    Name stdout
    Match mydoc.INFO*

**Step2:** 
Run the configuration file from step 1 using 
td-agent-bit -c -R command (for parser use the standard parser file that comes with install)
NOTE: I am using td-agent-bit binary

**Expected behavior**

Expect the information log contents to be routed to stdout output.

**Screenshots**

**Your Environment**

* Version used: Fluent Bit v1.2.0 (using td-agent-bit binary from (https://fluentbit.io/documentation/0.13/installation/ubuntu.html) 
* Configuration: See Step 1 
* Environment name and version (e.g. Kubernetes? What version?): Stand alone docker log files - Docker version 18.09.7, build 2d0083d
* Server type and version:
* Operating System and version: Ubuntu 18.04.2 LTS
* Filters and plugins:
See Step 1 
**Additional context**

**Comment by fujimotos** [comment]
`Tag_Regex` is supposed to match against the file name of the file,
not the content.

In your example, Fluent Bit tries to apply the regex against the string
"mydocker.sample.log". This is basically why it keep failing with the
following error message.

```
 [in_tail] invalid pattern for given file mydocker.sample.log
```

**Comment by jayeshnazre** [comment]
@fujimotos 
Thanks for responding. What I am trying to do here is to create two output streams based on one input (example: say with tail plugin). I am trying to create tags with values based on record contents so I can later use "match"  in the output plugins to route contents differently. If the Tag_RegEx is being applied on filename then it will not help me. Do you know if what I asked is possible with Fluent bit which in a nutshell is to route data based on record contents to different output streams. I know with kubernetes filters I can do it with namespaces but what about doing something similar based on file record contents. Any pointers or help is much appreciated.

**Comment by jayeshnazre** [comment]
Any input guys. I am sure my use case is pretty common. 
I am trying to route records to different output plugins based on record contents. For the record contents I want to use regular expressions to determine which output plugin the record can be routed to. This is what I have done so far 
a)	Looked at modify filter and then tried to use the Condition – “Key_value_matches” – however I am unable to use regular expression for key value match as the condition is not evaluating to be true even though the regular expression works on record content when I try it in https://rubular.com/ . below is my record content and the regexpression and the filter details


**Record Content:**

{"log":"2019-07-26 10:58:14.623  INFO 1 --- [       Thread-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.\n","stream":"stdout","time":"2019-07-26T10:58:14.624214432Z"}

**Regular Expression:**

^{"log":"([0-9-: .]*)(\sINFO\s)


**The filter section in config**

[FILTER]
    Name    modify
    Match   *
    Condition Key_value_matches  log ^{"log":"([0-9-: .]*)(\sINFO\s)
    Add errorflag true


b)	I may look at fluent bit streaming and see if I can use the WHERE condition. One  thing I do not know is whether the WHERE condition accepts syntax like “WHERE log LIKE *INFO*”
