### ISSUE TITLE
Fluentbit resets permission on syslog socket file

### ISSUE THREAD

**Issue by konstantin-kornienko** [fluent/fluent-bit#1479]
## Bug Report

**Describe the bug**
Trying to follow https://docs.fluentbit.io/manual/input/syslog to setup local rsyslog -> fluentbit forward via udp and socket file. Problem with this section from the documentation:

```
$ sudo chmod 666 /tmp/fluent-bit.sock
$ sudo service rsyslog restart
```

Fluentbit starts under root, and rsyslog runs under 'syslog' user on Ubuntu 18.
```
syslog    2810     1  0 13:50 ?        00:00:00 /usr/sbin/rsyslogd -n
root      4233     1  0 13:57 ?        00:00:00 /opt/td-agent-bit/bin/td-agent-bit -c //etc/td-agent-bit/td-agent-bit.conf
```
fluentbit creates socket with the following permissions:
```
# ll /tmp/fluent-bit.sock
srwxr-xr-x 1 root root 0 Jul 29 14:13 /tmp/fluent-bit.sock=
```

so rsyslog have no permissions on this file.

**Expected behavior**
I think it's better to control socket file permissions from config file.
Documentation also should be updated, because current workaround with chmod will work until fluentbit service will be restarted.

**Your Environment**
* Version used: td-agent-bit/bionic,now 1.2.2 amd64
* Operating System and version: Ubuntu 18
* Configuration:
```
[INPUT]
  Name     syslog
  Parser   syslog-rfc3164
  Path     /tmp/fluent-bit.sock
  Mode     unix_udp

[OUTPUT]
  Name     stdout
  Match    *
```

**Comment by fujimotos** [comment]
FWIW, I'm right now working on a patch to solve this problem.

The right solution seems to be adding a new parameter `Unix_Perm` that
tweaks a permission on a socket, as @konstantin-kornienko suggested
above.

```
[INPUT]
   Name       syslog
   Parser     syslog-rfc3164
   Path /     tmp/
   Mode       unix_udp
   Unix_Perm  644
```

In this way, it requires no manual `chmod` anymore && should work
seamlessly across reboots.
