### ISSUE TITLE
Regular Expression Parser is skipping empty values

### ISSUE THREAD

**Issue by BentCoder** [fluent/fluent-bit#1486]
Hi,

If a field in JSON log is empty, the field is not preserved in Elasticsearch result. See example below.

**Note**: Using `fluent/fluent-bit:1.2.2-debug`

# EXAMPLES

**ISSUE**

When `client_ip` field is empty in `log`, the field is not preserved.

```json
{
  ...
  "_source": {
    ...
    "time_local": "2019-07-31T21:17:15",
    "log": "{\"time_local\":\"2019-07-31T21:17:15\",\"client_ip\":\"\"}",
    ...
  },
  ...
}
```

**EXPECTED**

When `client_ip` field is empty in `log`, the field should be preserved with empty value.

```json
{
  ...
  "_source": {
    ...
    "time_local": "2019-07-31T21:17:15",
    "client_ip": "",
    "log": "{\"time_local\":\"2019-07-31T21:17:15\",\"client_ip\":\"\"}",
    ...
  },
  ...
}
```

# MY SETUP

**fluent-bit.conf**
```yaml
[SERVICE]
    Flush                     5
    Daemon                    Off
    Log_Level                 debug
    storage.path              /var/log/flb-storage
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M
    Parsers_File              parsers.conf

[INPUT]
    Name         forward
    storage.type filesystem
    Listen       my_fluent_bit_service
    Port         24224

[FILTER]
    Name         parser
    Parser       json_regex
    Match        *
    Key_Name     log
    Reserve_Data On
    Preserve_Key On

[OUTPUT]
    Name            es
    Host            my_elasticsearch_service
    Port            9200
    Match           whatever_*
    Index           whatever
    Type            logs
    Include_Tag_Key On
    Tag_Key         tag
```

**parsers.conf**
```yaml
[PARSER]
    Name   json_regex
    Format regex
    Regex  ^{"time_local":"(?<time_local>.*?)","client_ip":"(?<client_ip>.*?)"}$
```

**Comment by BentCoder** [comment]
If I use this filter, it actually keeps the empty fields as well so there is definitely a problem with regex parser.

```conf
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
    # Command      |  Decoder | Field | Optional Action
    # =============|==================|=================
    Decode_Field_As   escaped_utf8    log    do_next
    Decode_Field_As   json       log
```

**Comment by BentCoder** [comment]
Anyone bother answering?

**Comment by nigels-com** [comment]
It appears to be intended:

```
commit f41daaa696e67685e717765762bcff88743e187d
Author: Yann Soubeyrand <yann.soubeyrand@gmx.fr>
Date:   Wed Nov 21 17:54:25 2018 +0100

    parser: regex: fix wrong memory accesses (#834) (#835)
    
    Signed-off-by: Yann Soubeyrand <ysoubeyrand@leadformance.com>
```

See also:
https://github.com/fluent/fluent-bit/issues/834
https://github.com/fluent/fluent-bit/pull/835

I don't see the harm of removing the following check:

```
    if (vlen == 0) {
        pcb->num_skipped++;
        return;
    }
```

The [documentation](https://docs.fluentbit.io/manual/parser/regular_expression) does imply that empty values (such as referrer and agent) ought to appear in the output, rather than being dropped.

I'd be willing to put a branch together if you'd be willing to test and verify that it solves the problem.

**Comment by nigels-com** [comment]
Can I suggest renaming this issue to: _Regular Expression Parser is skipping empty values_

**Comment by BentCoder** [comment]
The title has been changed and I don't mind testing it but it will be about 1 week later.

**Comment by nigels-com** [comment]
Perhaps the reason fluent-bit is doing this is that we can't tell the difference between an _empty_  value and a _missing_ value that is optional.  Just because a regex mentions something by name, doesn't mean it will always be matched?

**Comment by BentCoder** [comment]
To me it is very simple. If a field is optional, that means leave the field empty. If it is left empty, that doesn't mean that get rid of the field. Nor invalid regex. Fir example, regex and the input below are valid although I left "middlename" empty. The result is, regex match still reports back with the field name. It does't bin it. Also, if the field is dropped it would give wrong impression to person as if there was no such field declared in regex anyway.

The whole consept of droping the field just because there is no value attached to it is OFF to me.

On top of that, logs would look weird if one had value and not the others. It would be impossible to standardise log visualisation too. List goes on.

https://rubular.com/r/yW5uEMGVKRAXY2

**Comment by nigels-com** [comment]
Consider this regex: `(?<name>.*):(=(?<middlename>.*))?`

It matches `N:' for both name and middlename, even though the expected middlename prefix was omitted.

https://rubular.com/r/yW5uEMGVKRAXY2

**Comment by BentCoder** [comment]
@nigels-com But that doesn't address the problem though. The field will still be discarded and won't appear in the logs as described in original post.

**Comment by BentCoder** [comment]
Solution is here: http://www.inanzzz.com/index.php/post/rel5/using-fluent-bit-to-forward-docker-php-fpm-and-nginx-logs-to-elasticsearch

There is a comment in "parsers.conf" file code in there.
