### ISSUE TITLE
[out_forward] implement gzip compression

### ISSUE THREAD

**Issue by hanyijun** [fluent/fluent-bit#1497]
Hi,
   Does the latest version fluent-bit support forward gizp compression?
   If not have,when will fluent-bit support to add it?

**Comment by edsiper** [comment]
Lastest development version on GIT master (not released) comes with gzip support for certain areas, at the moment is implemented in the HTTP output plugin and it will be added too to Forward output.

**Comment by hanyijun** [comment]
Thanks!

**Comment by davemt** [comment]
This issue was closed, but it does not seem like compression was ever added to Forward output (please correct me if I'm wrong). Should it be re-opened?

**Comment by edsiper** [comment]
yes, A misunderstanding, no gzip yet implemented. reopening.

**Comment by hafkaM** [comment]
Hello.
Is gzip support for forwarding (in-out) planned?
Similar to fluentd?
I need to transmit data compressed over a network.
We transfer large volumes of logs from IP television. 
Approx. 750Mbit /s. 
And without compression, throttling occurs on gig interfaces.
I need forwarding between flunetd and fluentbit with compression.
Best regards
Michal.

**Comment by hafkaM** [comment]
I could use Kafka on the output. Where compression can be turned on. But a consumer from Kafka is missing for fluentbit.

**Comment by hafkaM** [comment]
Hi.
Can we expect early implementation of gzip compression into the forwarding processor please?
And if so, do you know approximately a time horizon?
I am preparing a project where I would definitely need compression.
To consider any other alternatives if necessary.

Thank you for answer
Best regards
Michal.

**Comment by hafkaM** [comment]
Hello.
That's great news.
It will help me a lot.
Thank you.
Best regards.
M.

**Comment by edsiper** [comment]
Implemented, it will be part of v1.6.5 release.
