### ISSUE TITLE
About Parser_Firstline I have a question

### ISSUE THREAD

**Issue by MyOldSkyGrandfather** [fluent/fluent-bit#1516]
## Bug Report

**Describe the bug**

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by MyOldSkyGrandfather** [comment]
![image](https://user-images.githubusercontent.com/22900812/63085917-42910f00-bf81-11e9-9c5d-5ef186c2c98f.png)
what mean it is?

**Comment by MyOldSkyGrandfather** [comment]
Parser_Firstline

Name of the parser that matchs the beginning of a multiline message. Note that the regular expression defined in the parser must include a group name (named capture)


what mean it is

**Comment by MyOldSkyGrandfather** [comment]
``[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name             tail
    Path             /var/log/containers/logtest-*.log
    Parser           docker
    Tag              kube.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    Multiline   On
    Parser_Firstline  findfirstline
    
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token

[OUTPUT]
    Name   stdout
    Match  *
[PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped_utf8    log
    [PARSER]
        Name        findfirstline
        Format      regex
        Time_Key    time
        Regex       .*(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}|DEBUG|INFO|ERROR).*
        Time_Format %Y-%m-%d %H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped_utf8    log

But throw a Exception 


[2019/08/15 09:29:24] [error] [in_tail] multiline: invalid parser 'findfirstline'
[2019/08/15 09:29:24] [error] Failed initialize input tail.0

I don't know why.

**Comment by MyOldSkyGrandfather** [comment]
My Log content like this  under path /var/log/containers/


{"log":"[null] [ERROR] [2019-08-15 19:12:53,244] RedirectingEurekaHttpClient \u003e\u003e Request execution error\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245582671Z"}
{"log":"com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: 拒绝连接 (Connection refused)\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245585682Z"}
{"log":"\u0009at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245588908Z"}
{"log":"\u0009at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245594864Z"}
{"log":"\u0009at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245598258Z"}
{"log":"\u0009at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245601271Z"}
{"log":"\u0009at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245604298Z"}
{"log":"\u0009at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245607282Z"}
{"log":"\u0009at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:529) ~[jersey-client-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245610292Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.sendHeartBeat(AbstractJerseyEurekaHttpClient.java:102) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245613341Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245616549Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245619689Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245623337Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245626539Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:118) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245629687Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:79) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245632794Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245635994Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245639252Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245642624Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245645698Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245648805Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245663687Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245670104Z"}
{"log":"\u0009at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245675702Z"}
{"log":"\u0009at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1399) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245678982Z"}
{"log":"\u0009at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.24568202Z"}
{"log":"\u0009at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245711505Z"}
{"log":"\u0009at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245714972Z"}
{"log":"\u0009at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245719704Z"}
{"log":"\u0009at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245724648Z"}
{"log":"Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245729351Z"}
{"log":"\u0009at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245733942Z"}
{"log":"\u0009at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.24573885Z"}
{"log":"\u0009at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245743972Z"}
{"log":"\u0009at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245749008Z"}
{"log":"\u0009at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.24575427Z"}
{"log":"\u0009at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245758127Z"}
{"log":"\u0009at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245761045Z"}
{"log":"\u0009at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245764242Z"}
{"log":"\u0009at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245767295Z"}
{"log":"\u0009at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245770484Z"}
{"log":"\u0009at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.24577353Z"}
{"log":"\u0009at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.24577662Z"}
{"log":"\u0009at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245783295Z"}
{"log":"\u0009at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245786565Z"}
{"log":"\u0009at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar!/:4.5.5]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245790627Z"}
{"log":"\u0009at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245793731Z"}
{"log":"\u0009... 27 common frames omitted\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245796933Z"}
{"log":"[null] [WARN] [2019-08-15 19:12:53,245] RetryableEurekaHttpClient \u003e\u003e Request execution failed with message: java.net.ConnectException: 拒绝连接 (Connection refused)\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245802285Z"}
{"log":"[null] [ERROR] [2019-08-15 19:12:53,245] DiscoveryClient \u003e\u003e DiscoveryClient_WEB-SAMPLE/logtest-574655db87-d5hl6:web-sample:8091 - was unable to send heartbeat!\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245807868Z"}
{"log":"com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245813613Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245818711Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245824104Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$3.execute(EurekaHttpClientDecorator.java:92) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245829064Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245834687Z"}
{"log":"\u0009at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.sendHeartBeat(EurekaHttpClientDecorator.java:89) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245840131Z"}
{"log":"\u0009at com.netflix.discovery.DiscoveryClient.renew(DiscoveryClient.java:846) ~[eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245845404Z"}
{"log":"\u0009at com.netflix.discovery.DiscoveryClient$HeartbeatThread.run(DiscoveryClient.java:1399) [eureka-client-1.9.2.jar!/:1.9.2]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245850213Z"}
{"log":"\u0009at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245870491Z"}
{"log":"\u0009at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245878335Z"}
{"log":"\u0009at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245881815Z"}
{"log":"\u0009at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245884853Z"}
{"log":"\u0009at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]\r\n","stream":"stdout","time":"2019-08-15T11:12:53.245888724Z"}


here is my parser

[PARSER]
Name audit-firstline
Format regex
Time_Key time
Regex .*(?<log>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}|DEBUG|INFO|ERROR).*
Time_Format %Y-%m-%d %H:%M:%S.%L
Time_Keep On


My 【INPUT】
[INPUT]
Name tail
Path /var/log/containers/logtest-*.log
Parser docker
Tag kube.*
Refresh_Interval 5
Mem_Buf_Limit 5MB
Skip_Long_Lines On
Multiline On
Parser_Firstline audit-firstline


but the error on k8s 


[2019/08/15 11:09:48] [ info] [engine] started (pid=1)
[2019/08/15 11:09:48] [error] [in_tail] multiline: invalid parser 'audit-firstline'
[2019/08/15 11:09:48] [error] Failed initialize input tail.0


I don't know why, I do it according to official manual

**Comment by AshutoshNirkhe** [comment]
Exactly same issue here. Please let me know if anybody has any solution this yet ?

**Comment by avdhoot** [comment]
Looks like you forgot to add file name as a  value of `Parsers_File` in `SERVICE` block. @AshutoshNirkhe @MyOldSkyGrandfather 
```
[SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Parsers_File parsers_custom.conf
