### ISSUE TITLE
In dummy input plugin, only current (now()) time is used, not the parser generated one

### ISSUE THREAD

**Issue by alitoufighi** [fluent/fluent-bit#1524]
## Bug Report

**Describe the bug**

When using Dummy input plugin for testing and debugging issues, it doesn't check if any parser is attached to this input (for example, a JSON parser) to extract time and only adds current time (it only uses `flb_pack_time_now()` without paying attention to present parser.)

**To Reproduce**
- Example log message if applicable:
```
{"log":{"data": "This is an example."},"stream":"stderr","time":"2019-07-21T12:45:11.273315023Z"}
```
- Steps to reproduce the problem:
Use these:
```
[INPUT]
        Name    dummy
        Tag     log.test
        Dummy   {"log":{"data": "This is an example."},"time":"2019-07-21T12:45:11.273315023Z"}
        Parser  sample

[PARSER]
        Name        sample
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   Off
```
**Expected behavior**
Use `time` provided in dummy log to create timestamp (I expected to see a fixed timestamp in output.)

**Your Environment**

* Version used: Fluent Bit Docker Image 1.2.2
* Configuration: Default
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.15
* Server type and version: Testing on my local machine
* Operating System and version: Ubuntu 18.04 (Linux 4.15.0-55-generic)
* Filters and plugins: Provided above

**Additional context**
I was really `testing` and `debugging` my timestamps in logs, but I got confused by this behavior. I expected this `Dummy` input to be just a mock for the actual log message we get, and I thought the rest must be the same like other inputs. (I use `tail` input to collect my actual logs).

**Comment by nokute78** [comment]
@alitoufighi Would you try `filter_parser` plugin ?
It helps your use case.
in_dummy generates the JSON like `{"raw":"(your JSON string)"}`,
and filter_parser tries to parse as JSON and it overwrites timestamp using "time" value.

a.conf:
```python
[INPUT]
     Name    dummy
     Tag     log.test
     Dummy   {"raw":"{\"log\":{\"data\": \"This is an example.\"},\"stream\":\"stderr\",\"time\":\"2019-07-21T12:45:11.273315023Z\"}"}
     Parser  sample
[FILTER]
     Name parser
     Match log.*
     Parser sample
     Key_name raw
     Preserve_key stream

[OUTPUT]
     Name stdout
     Match *
```

a.parser:
```python
[PARSER]
     Name        sample
     Format      json
     Time_Key    time
     Time_Format %Y-%m-%dT%H:%M:%S.%L
     Time_Keep   Off
```

output is
```sh
$ ../bin/fluent-bit -c a.conf -R a.parser 
Fluent Bit v1.3.0
Copyright (C) Treasure Data

[2019/08/26 20:46:46] [ info] [storage] initializing...
[2019/08/26 20:46:46] [ info] [storage] in-memory
[2019/08/26 20:46:46] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/08/26 20:46:46] [ info] [engine] started (pid=10603)
[2019/08/26 20:46:46] [ info] [sp] stream processor started
[0] log.test: [1563713111.273315023, {"log"=>{"data"=>"This is an example."}, "stream"=>"stderr"}]
[1] log.test: [1563713111.273315023, {"log"=>{"data"=>"This is an example."}, "stream"=>"stderr"}]
[2] log.test: [1563713111.273315023, {"log"=>{"data"=>"This is an example."}, "stream"=>"stderr"}]
[3] log.test: [1563713111.273315023, {"log"=>{"data"=>"This is an example."}, "stream"=>"stderr"}]
^C[engine] caught signal (SIGINT)
[2019/08/26 20:46:52] [ info] [input] pausing dummy.0
```
