### ISSUE TITLE
out_gelf: Unicode characters doesn't show correctly in Graylog

### ISSUE THREAD

**Issue by alitoufighi** [fluent/fluent-bit#1527]
## Bug Report

**Describe the bug**
I'm using Persian characters in my logs. When I use GELF output plugin, they are corrupted (actually encoded to UTF-16) when they arrive at my Graylog server. The server is also unable to decode it.

For testing, I used a `dummy` input and sent logs using `stdout` and `gelf` output plugins:
```
    [INPUT]
        Name   dummy
        Tag    log.test
        Dummy  {"log": "این یک تست است.", "host": "localhost"}
        # Meaning of above: "This is a test."

    [OUTPUT]
        Name                    gelf
        Match                   log.test
        Host                    localhost
        Port                    12201
        Mode                    tcp
        Gelf_Short_Message_Key  log

    [OUTPUT]
        Name   stdout
        Match  log.test
```

This is what I see in `stdout`:
```
[0] log.test: [1566649794.000169744, {"log"=>"این یک تست است", "host"=>"localhost"}]
```

And if I use `nc` in my Graylog server to see what is the arrived GELF packet, I get this:
```JSON
{"version":"1.1", "short_message":"\u00000627\u000006cc\u00000646 \u000006cc\u000006a9 \u0000062a\u00000633\u0000062a \u00000627\u00000633\u0000062a.", "host": "localhost", "timestamp":1566643450.274220}
```
And when I show it in my Graylog server, it is also unable to decode this message.

There are 2 problems:

1. What happens to my string in GELF plugin which corrupts the data?
2. This is not UTF-8!

**To Reproduce**
See above.

**Expected behavior**
See UTF-8 encoded string that Graylog can understand.
Actually, there are 4 extra zeros after `\u`. For example, this is the valid version of above log:
```JSON
{"version":"1.1", "short_message":"\u0627\u06cc\u0646 \u06cc\u06a9 \u062a\u0633\u062a \u0627\u0633\u062a.", "host": "localhost", "timestamp":1566643450.274220}
``` 
And if I send this manually (using `nc`) to a Graylog input, it successfully understands it.

**Screenshots**
First, I sent above log using GELF output plugin. Which as it seems, it is not correct. The reason is that `\u0000` which comes first, translates to `NULL` character and nothing is shown. Then, the actual part of encoded character comes, that is not interpreted as a Unicode character.

(`\u00000627` --> `\u0000 0627` --> `NULL0627` --> `0627`)

Secondly, I removed first four zeros and sent it using `nc`. As shown, it was decoded and shown properly.

![image](https://user-images.githubusercontent.com/30089812/63637200-2848e680-c68f-11e9-82ed-1b5cbfc61f1a.png)

**Your Environment**

* Version used: I built from master (Aug 24)
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): My local machine
* Server type and version: ASUS Zenbook
* Operating System and version: Elementary OS 5.0 (Ubuntu 18.04) with kernel 4.15.0-55-generic
* Filters and plugins: See above

**Additional context**
I was trying to send my Persian logs into our Graylog server.

**Comment by edsiper** [comment]
Fixed.
