### ISSUE TITLE
Kubernetes Filter - Add "Replace_Dots" function found in Elasticsearch Filter

### ISSUE THREAD

**Issue by DandyDeveloper** [fluent/fluent-bit#1538]
**Is your feature request related to a problem? Please describe.**
We currently have fluentbit tailing and parsing logs, but we subsequently pass these into fluentd for the benefit of buffering logs. 

Due to this, we're using the Kubernetes filter, but not using the Elasticsearch output plugin that comes with `Replace_Dots` feature.

As this is missing, we're experiencing the same problem found in the original ticket raised for the `Replace_Dots` feature: https://github.com/fluent/fluent-bit/issues/708

Example conflict error from ES: 

```
2019-08-29 08:03:47 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'Could not dynamically add mapping for field [kubernetes_labels_app.kubernetes.io/instance]. Existing mapping for [kubernetes_labels_app] must be of type object but found [text].'" location=nil tag="kube.tag.log" time=2019-08-29 08:03:39.488097120 +0000 record={"log"=>" LOG"}
```

**Describe the solution you'd like**
It would be great if the Kubernetes either automatically replaced the dots, or offered the same option as the Elasticsearch filter. 

**Describe alternatives you've considered**
See above

Alternatively, the suggested "generic" filter suggested here would work: https://github.com/fluent/fluent-bit/issues/1305

**Additional context**
Right now, a lot of our logs are rejected due to this, I can make some customized templating changes and a number of other complicated solutions, but having this option would solve the problem much faster.

**Comment by Thoro** [comment]
I also ran into this issue now. A user can simply break his own log collecting by adding various labels to the pod, for example:

app: nextcloud
app.service: database

would break the log collection for this specific pod.

I think the option to replace the dots, or find some other way, that elasticsearch interprets user provided data as separate fields.

**Comment by DandyDeveloper** [comment]
Bad bot.
