### ISSUE TITLE
in_systemd support lowercase option for field names

### ISSUE THREAD

**Issue by gabe-sorensen** [fluent/fluent-bit#1543]
The fluentd-systemd plugin has an option for `fields_lowercase` to make all the fields from systemd lowercase, instead of the default where everything is uppercase. It would be nice if fluent-bit supported this option as well, where the fields would get mapped to the lowercase equivalent (i.e. _PID => _pid, MESSAGE => message).

I've tried several options on the fluentd side, and none of them have worked.

https://github.com/JonathanSerafini/fluent-plugin-mutate_filter
- Only allows mutating the value to lowercase, not the key

https://github.com/shunwen/fluent-plugin-rename-key
- Only allows re/moving the matched group, not any mutations such as \L

https://docs.fluentd.org/filter/record_transformer
- Would require creating a new record with the same contents and key, but lower case key, then have a separate plugin to remove the old key.

This issue could likely be fixed with modifications to the first two plugins, but it would be nice if this was supported as a built-in option to the systemd plugin in fluent-bit.

**Comment by fpytloun** [comment]
Hi, I would also appreciate this feature.

**Comment by surajnarwade** [comment]
Hi, looking forward to this feature implementation  :tada:

**Comment by surajnarwade** [comment]
Hi, I would like to work on this issue

**Comment by fpytloun** [comment]
Hello, any update here?

**Comment by Blobonat** [comment]
+1

**Comment by mattkenn4545** [comment]
+1... my logs look ugly ;)
