### ISSUE TITLE
[Question] Will fluent-bit stop sending logs if timestamps are out of order?

### ISSUE THREAD

**Issue by rolandjitsu** [fluent/fluent-bit#1547]
**Is your feature request related to a problem? Please describe.**

I was wondering if fluent-bit would stop sending logs (via forward output) if one of the timestamps is out of order (it's older than the logs it tracked so far).

To give you an example, here's a few logs that illustrate what I mean:
```
{"datetime":"2019-08-30T06:54:50.006" , "gx":0.138283, "gy":0.319481, "gz":0.535965}
{"datetime": "2019-08-30T06:54:49.999", "srx": 48.6, "sls": 1}
{"datetime":"2019-08-30T06:54:50.056" , "gx":0.161171, "gy":0.116348, "gz":0.34523}
{"datetime":"2019-08-30T06:54:50.107" , "gx":0.211716, "gy":0.2985, "gz":0.472069}
```

The 2nd line is actually timestamped at a time before the 1st line.

It seems to me that fluent-bit doesn't really send any logs after that or something goes wrong.

To give a bit of context on what happened: we use the tail input plugin and we have enabled the db sync (to remember the last line it sent/read), and we power cycled the device where the logs are collected, then we haven't received any logs at all.

To fix it, we did 2 things:
1. we removed the log file which had this line (we did not know about it at that time)
2. we restarted fluent bit

**Describe the solution you'd like**

Ideally, fluent-bit shouldn't care about the order of the logs and just send whatever it reads from the files. I'm not sure if this is already the case today.

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Fluent Bit should ignore the timestamps, in fact this was an issue for Loki that used to not accept out-of-order.
