### ISSUE TITLE
Is tail input supposed to work with glob patterns (**/*.log) ?

### ISSUE THREAD

**Issue by eddycharly** [fluent/fluent-bit#1552]
Is tail input supposed to work with glob patterns (eg /tmp/app-logs/**/*.log) ?

**Comment by d-dmitry** [comment]
This expression works for me: /tmp/app-logs/*/*.log

**Comment by eddycharly** [comment]
`/tmp/app-logs/*/*.log` is not the same thing as `/tmp/app-logs/**/*.log`.

`/tmp/app-logs/*/*.log` only looks at a fixed folder depth level whereas `/tmp/app-logs/**/*.log` looks at various folder depth levels.
