### ISSUE TITLE
How to make fluent-bit lib plugin supporting multi-thread 

### ISSUE THREAD

**Issue by GaoyangWang** [fluent/fluent-bit#1567]
**Is your feature request related to a problem? Please describe.**
I use fluent-bit in the endpoint of an embed security system. I need to use flb_lib_*, the lib plugin to work with my C code. I meet the problem, the performance. Current 1.2v fluent-bit.so can handle 20K events/s, of course each system event is a little big. My goal is to handle 200K/s.

**Describe the solution you'd like**
If fluent-bit can support multi-thread, that will be awesome.

**Describe alternatives you've considered**
I create a daemon to manage multi fluent-bit instance.   

**Additional context**

**Comment by edsiper** [comment]
can you give it a try to the current v1.3 in GIT Master ?, we did some performance improvements recently, just wondering what difference do you see. 

Of course to jump from 200k to 2000k needs a different strategy, multithreading support is planned but no ETA yet.

**Comment by GaoyangWang** [comment]
Sorry, a typo. Updated.

**Comment by edsiper** [comment]
20k/s is a bit slow unless every record is a couple of KBs... I will make sure to implement a performance test for that component first.

Multithreading is planned but no ETA yet

**Comment by GaoyangWang** [comment]
Yes, each security log has 100+ keys. What's more, the use case also include using Lua script as the filter plugin. Thanks for your timely response.

**Comment by edsiper** [comment]
how big in average is a JSON record that you ingest (bytes) ?

**Comment by GaoyangWang** [comment]
Around 10 KB.

**Comment by GaoyangWang** [comment]
Another issue, I am not quite sure whether it is expected. When output in csv file, the Lua code setting some empty keys, for example, "new_record["newkey"] = record["notexist"]", the csv will skip this one.
For instance:
expectation:
(Lua filter: "key1", "key2", "not exist key") => (csv file: "value1" , "value2" , , )
current behaviour (v1.2):
(Lua filter: "key1", "key2", "not exist key") => (csv file: "value1" , "value2")

**Comment by josephflynch** [comment]
Eduardo - what's the current status on multi-threading and how much of a throughput boost do you expect?

**Comment by lmuhlha** [comment]
Hi,
Is there any updated timeline for multithreading support?

Thanks.

**Comment by agup006** [comment]
@lmuhlha @GaoyangWang  we have our first version of multithreading coming out shortly and have been testing for 200K/s. WIll update once the release candidate is available

**Comment by GaoyangWang** [comment]
Is v1.6.10 the version of multithreading? @agup006 thanks.

**Comment by agup006** [comment]
@GaoyangWang 1.7.0 (master) is the version with multi-threading

**Comment by agup006** [comment]
@GaoyangWang, one other note, what backend are you using? Want to see if I can add that to my test suite. Or if you have some cycles would be great to sync over a Zoom

**Comment by viclevy** [comment]
@agup006 why is this issue still open if support for multi-threading was introduced with 1.7.0 release?

**Comment by agup006** [comment]
@viclevy you are right, happy to close this issue and say that multi-threading is available in 1.7.X release

**Comment by hukaixuan** [comment]
is the multi-threading only for output? I use tail input with k8s filter and kafka output, found that if i set docker json parser in tail input and use k8s filter, the max only 70k/s logs; if remove docker json parser and k8s filter, it reach to 600k/s logs in my test machine. If it's possible to make input and filter multi-threading?
