### ISSUE TITLE
Add Filtering support

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#157]
Fluent Bit needs to get filtering plugins support, so data form inputs can be modified. 

First priority is to get a Kubernetes metadata filter.

**Comment by mitchhh22** [comment]
+1 for Kubernetes metadata filter

**Comment by nokute78** [comment]
Note: Some input plugins are still work in progress to support filter. See also #173

**Comment by edsiper** [comment]
Filtering support is already in place, current plugins are:

- stdout
- grep

The branch filter_kubernetes have the progress of that new upcoming filter.
