### ISSUE TITLE
Include copyright notice in every source file for LuaJIT dependency

### ISSUE THREAD

**Issue by qingling128** [fluent/fluent-bit#1572]
Hi Fluent Bit repo maintainers,

We are currently having problems getting Fluent Bit image approved by legal team because one of the dependencies, LuaJIT, organizes license / copyright notice slightly different from common practices.

Instead of directly including copyright notice, most of the files currently have:
```
See Copyright Notice in lua.h
```

We’ve opened an GitHub issue in the [LuaJIT](https://github.com/LuaJIT/LuaJIT/issues/504) project to suggest including full copyright notice in Luajit directly. Unfortunately, the original repo owner is [no longer actively maintaining the repo](https://github.com/LuaJIT/LuaJIT/issues/504#issuecomment-531967127).

As I seek for workarounds, is it possible to modify the copyright notice directly in `Fluent Bit` repo then? I noticed that we included two versions of LuaJIT:
https://github.com/fluent/fluent-bit/tree/master/lib/luajit-2.0.5
https://github.com/fluent/fluent-bit/tree/master/lib/LuaJIT-2.1.0-beta3

I'm happy to send a PR. Basically it would just modify all occurrences like `See Copyright Notice in lua.h` to the actual content of that Copyright Notice (aka the same content as in `lua.h`.)

Let me know if that sounds good to you.

Thanks,
Ling

**Comment by edsiper** [comment]
@qingling128 

Thanks for the notice on this. As a first action, I have removed the unused luajit 2.0.5 content from our repo.

In order to move to the second item, sending a PR to our repo should be fine, please prefix the commit with "lib: luajit: ...."

would you please elaborate the legal process of this and the use case of Fluent Bit at Google ?, as a maintainer I would appreciate get more context of the use of the project.

**Comment by qingling128** [comment]
@edsiper - Thank you so much! I'll send a PR.

As for the legal process and use case. We are trying to adopt Fluent Bit as node-level log pusher (it pushes logs to cluster-level Fluentd instances) in GKE in order to reduce node-level resource usage (e.g. memory). Our license scan tool detects missing licenses from Fluent Bit image and raises "concern" from time to time. We are trying to trace down the root cause to mute that false alarm.

**Comment by edsiper** [comment]
thanks @qingling128 

would you please send the PR shortly so we can make it part of v1.3 release ?

**Comment by qingling128** [comment]
Hi @edsiper ,

I was gonna send a PR but noticed some concern (https://github.com/LuaJIT/LuaJIT/issues/504#issuecomment-532769503) from the original LuaJIT repo.

I did not want to get any maintainers into grey zones for unnecessary issues, so I sync'ed with internal teams. Seems like our new license scanning automation with some minimum effort was able to work around this issue. So it's no longer a requirement to change it in this repo. I'm gonna closing this one.

Thanks all for taking a look though.

**Comment by edsiper** [comment]
thanks for the update @qingling128 .

I hope LuaJIT gets maintained again (for all architectures)...
