### ISSUE TITLE
fluentbit number of input records in bytes decreases by 150% when we are upgrading from version 1.0.4 to 1.2.2

### ISSUE THREAD

**Issue by balraj111** [fluent/fluent-bit#1575]
i am using fluentbit with this configuration
*** environment***
os: centos
platform:kubernetes 1.14.1
fluentbit version 1.0.4
cpu core : "1"

 fluent-bit.conf: |
   [SERVICE]
       Flush         2
       Log_Level     info
       Daemon        off
       Parsers_File  parsers.conf
       HTTP_Server   On
       HTTP_Listen   0.0.0.0
       HTTP_Port     2020
   [INPUT]
       Name        tcp
       Listen      0.0.0.0
       Port        5170
       Chunk_Size  103
       Buffer_Size 5M
   [OUTPUT]
        Name  null
        Match  *
i have created 20 pods of tcp client on kubernetes cluster , where each pod is sending 10MBps of data every second.
here what problem i am facing right now.
1. i am getting around 160 MB data per second in fluent bit input.
2. cpu usage is 100% , even i am trying to increase fluent bit cpu core ( i have assigned 2 cores). there is no improvement . cpu usage is still 100% and incoming bytes   is still 160 MB per second.
3. when i change my image version to 1.2.2-debug from 1.0.4-debug , fluent bit input reduced to 60 MB person.  i have tried all possible combination of chunk_size and buffer_size but i did't see any improvement.
4.  what is the significance of buffer_size and chunk_size , how i can know what value we have to set in these parameters to get better result. when i was using 1.0.4-debug image i was playing with these param , i was getting best result when i was setting chunk_size 103 and buffer_size 2M . my tcp client is sending 1024 bytes of packets . when i am setting chunk size to 128 , fluent bit memory consumption start increasing and after some time fluent bit get crashed.
5.  what are the other parameters that can help me to reachout 200MBps

**Comment by edsiper** [comment]
@balraj111 

would you please evaluate the upcoming (test) version v1.3 ?

https://github.com/fluent/fluent-bit/issues/1580

**Comment by balraj111** [comment]
@edsiper sure, i will evaluate test results soon.

**Comment by edsiper** [comment]
ping

**Comment by edsiper** [comment]
last ping

**Comment by balraj111** [comment]
@edsiper I am attaching a benchmark snippet for your reference.


![FBIT-BENCHMARKING](https://user-images.githubusercontent.com/12413166/66129245-274f9100-e60d-11e9-8f08-942f6e8f1076.jpg)

Notes:-
1.) Same results has been observed with version 1.3 as well
2.) Fluent bit pod start crashing when we scale the number of client pods to 25 with Chunk size > 64 KB
3.)  When the number of client (tcp client to send the data to fluent bit) pods > 25 & chunk size = 64 with  JSON payload =1024 In that case we are getting "fluentbit_number_input_bytes" around 102-110 MBps.

**Comment by edsiper** [comment]
@balraj111 

thanks for the information.

Looking at the code and your configuration I see some things that need to be fixed from our side:

- chunk\_size and buffer\_size configuration: the variables are confusing and prone to bad configuration. By default, the unit size is always in kilobytes, so if you set 2M when converting that value will get 2KB, use a value of 2048 instead to represent 2MB. I will make sure to fix that from a usability perspective.

About performance:

- Note that Fluent Bit (for now) is a single thread process only. So if you assign more CPU cores will not make a difference.

- JSON parsing is expensive by nature

In the meanwhile, I will do some performance tests on my end. Note that I will be using the new perf tools we wrote for this kind of situations: https://github.com/fluent/fluent-bit-perf , the tcp writer don't support concurrency but I will try to implement it. 

Can you also provide your dockerfiles you are using for your tests ?

**Comment by edsiper** [comment]
FYI:

in my tests I've found a 5% performance decrease when parsing JSON content, mostly due to the way UTF-8 decoding is being done.

I am experimenting with some workarounds to speed up that routine.

**Comment by balraj111** [comment]
@edsiper  We upgraded fluent bit to 1.3.10  because of TCP input plugin in this version support the raw format which is less expensive as compared to json, using that we are able to reach our benchmark of more than 1 Giga bits per second. Is there any way we can get pod and container informaton without using json format ?

**Comment by edsiper** [comment]
@balraj111 

- first I would suggest you try v1.4.6, we did several (extra) performance improvements
- if you have your container info as environment variables you might want to add them using record_modifier or a Lua script
- if Fluent Bit is crashing, please test v1.4.6 and let me know if you can reproduce the problem so I can troubleshoot

**Comment by balraj111** [comment]
@edsiper What is the default tag for the tcp plugin??? because in documentation there is no tag field for this plugin.

**Comment by edsiper** [comment]
if you omit a Tag, the default tag is the plugin instance name, on that case it would be tag.0, tag.1...

**Comment by balraj111** [comment]
@edsiper  we tried 1.4.6 with json data as well as raw data with lua script these were our following observations (these were tested with 45 pods in same worker node)
1. when we were sending the json data and input plugin was only tcp in configmap ( we were not reading log from the file ) in that case fluent bit was able to process 380 Mega bit of log per second
but when we include 2 file plugin in configmap then our test application was unable write logs on tcp plugin due to time out. both in write and monitoring.
2. using raw data with lua script i was able to reach 400 Mega bits per second without file plugin. but when we include 2 file plugin then i was observing same issue as 1.

overall , we are unable to reach our bench mark which is 1 giga bits per second.
Is there any way we can send data over udp so that we can run fluent bit as statefullset instead of daemonset to achieve more through put 

this is our config file

apiVersion: v1
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        Kube_Tag_Prefix     kube.data.log.
        Merge_Log_Key    log_processed
  filter-log.conf: |
    [FILTER]
        Name                kubernetes
        Match               tail.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        Kube_Tag_Prefix     kube.data.log.
        Merge_Log_Key    log_processed
  filter-lua.conf: |
    [FILTER]
        Name    lua
        Match   tcp.*
        script  root/test.lua
        call    cb_print
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path        /var/log/flb-storage/
        storage.sync         normal
        storage.checksum       off
        storage.backlog.mem_limit 150M
    @INCLUDE input-kubernetes.conf
    @INCLUDE input-kubefmt-applog.conf
    #@INCLUDE input-kubefmt-mmx.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-lua.conf
    @INCLUDE filter-log.conf
    #@INCLUDE output-fluentd-aggregator.conf
    @INCLUDE input-json-stream.conf
    #@INCLUDE output-elasticsearch.conf
    @INCLUDE output-null.conf
  input-json-stream.conf: |
    [INPUT]
        Name        tcp
        Listen      0.0.0.0
        Port        5170
        Chunk_Size  8
        Tag         tcp.*
        Buffer_Size 1024
        format      none
        storage.type  memory
  input-kubefmt-applog.conf: |
    [INPUT]
        Name              tail
        Tag               tail.*
        Path              /data/logs/*[_][a-zA-Z0-9]*[_][a-zA-Z0-9]*[-]*.log
        Parser            docker
        DB                /var/log/flb_kubefmt.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  5
        storage.type  memory
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        storage.type  memory

this is my lua script
sending log in this format "pod_id//##//container_name//##//namespace_name//##//log"
`function split(str, sep)
   local result = {}
   local regex = ("([^%s]+)"):format(sep)
   for each in str:gmatch(regex) do
      table.insert(result, each)
   end
   return result
end

function cb_print(tag, timestamp, record)
      new_record = record
      content  = record
      lines = split(content["log"], "/##/")
      new_record["kubernetes.pod_id"] = lines[1]
      new_record["kubernetes.container_id"] = lines[2]
      new_record["kubernetes.namespace_name"] = lines[3]
      new_record["log"] = lines[4]
      return 1, timestamp, new_record
end`

**Comment by edsiper** [comment]
is this still an issue with v1.6.4 ? (I could not reproduce any of the problems mentioned), please confirm

**Comment by patrick-stephens** [comment]
Going to close but feel free to re-open if still occurring in more recent builds.

**Comment by balraj111** [comment]
> Going to close but feel free to re-open if still occurring in more recent builds.

@patrick-stephens. Sure.
