### ISSUE TITLE
Community Test: Upcoming v1.3 release

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#1580]
Fluent Bit v1.3 is around the corner and I would like to ask for community input before the final release.

The test docker image is located here:

```
edsiper/fluent-bit-1.3-next:1
```

would you please give it a try and provide some feedback ?

### Overall improvements

- in_tcp
- in_forward
- gelf
- stream processor
- out_datadog 
- stackdriver
- others...

**Comment by vielmetti** [comment]
Is this a multi-architecture manifest?

**Comment by edsiper** [comment]
It should be agnostic...

https://github.com/fluent/fluent-bit/blob/master/fluent-bit_git.bb

^ pull code from GIT master

**Comment by edsiper** [comment]
My bad, I replied the wrong thread! 

This is only x86_64

**Comment by edsiper** [comment]
## update 

Almost 280 Docker hub pulls, no issues reported yet.

**Comment by l2dy** [comment]
Would Fluent Bit 1.3 pass the [JSON Correctness Test](https://github.com/timberio/vector-test-harness/tree/master/cases/wrapped_json_correctness) by Timber?

**Comment by l2dy** [comment]
> Would Fluent Bit 1.3 pass the [JSON Correctness Test](https://github.com/timberio/vector-test-harness/tree/master/cases/wrapped_json_correctness) by Timber?

Never mind, it seems to be a problem with their test case.

**Comment by edsiper** [comment]
@l2dy yep, their tests and overall info when comparing Fluent Bit v/s Vector is not accurate, I opened an issue like 7 weeks ago about this:

https://github.com/timberio/vector/issues/727

Also, I did some performance tests and got totally different results :)

**Comment by edsiper** [comment]
## Update ## 

New test image pushed

```
edsiper/fluent-bit-1.3-next:2
```

### Changes from previous test version

- systemd enabled
- 0e000ca4 lib: chunkio: fixes and improvements (details in the commit)
- ee7abe28 Merge branch 'master' of github.com:fluent/fluent-bit
- 1282823d proxy: windows: remove needless typecast and correct incompatible type (#1594)
- 9801e849 lib: mbedtls: upgrade from v2.16.1 -> v2.16.3
- f2069c76 lib: jemalloc: upgrade from v5.1.0 -> v5.2.1
- 8d077cae filter_grep: add error messages for troubleshooting
- 2045b1b1 in_tail: prevent file duplication on macOS (#1596)
- 92cb486a out_influxdb: add escape for backslash (#1123)
- dd405e00 io: tls: support SNI routing for outputs (#1313)
- 8954655b in_systemd: workaround for systemd tail/skip issue 9934 (#1565)

**Comment by edsiper** [comment]
As of today, no issues has been reported, we got 2661 Docker hub pulls for the images:

| image | pulls | 
|--|--|
| edsiper/fluent-bit-1.3-next:1 | 540 | 
| edsiper/fluent-bit-1.3-next:2 | 2121 |

So release v1.3 will arrive tomorrow unless something comes up last minute.

**Comment by fujimotos** [comment]
@edsiper For what it's worth, I can confirm v1.3 compiles fine on Windows.

I've also run Fluent Bit with `in_tail` + `out_forward` a few hours on Windows
too. It worked without issues, so I think it's ready to be released.

**Comment by loburm** [comment]
@edsiper one question. I see that images for 1.1 and 1.2 are near 53.2MB, at the same time images that you have mentioned here above 230MB, is it expected?

**Comment by edsiper** [comment]
@loburm yes, images mentioned here are just based on ubuntu-slim. 

Note that v1.3 has been released (releases notes will arrive shortly), give it a try:

```
fluent/fluent-bit:1.3.0
```

note: that one is a multi arch image now: x86_64, arm32v7 and arm64v8

**Comment by edsiper** [comment]
Updated information about new Docker images here:

https://docs.fluentbit.io/manual/installation/docker

thanks everyone who helped to test this!!!

**Comment by binarylogic** [comment]
@edsiper sorry for the delay on this, it was just brought to my attention.

> yep, their tests and overall info when comparing Fluent Bit v/s Vector is not accurate, I opened an issue like 7 weeks ago about this

Which tests are you referring to? Our test harness contained 12 tests, you commented on 2 of them, which I responded to here:

https://github.com/timberio/vector/issues/727#issuecomment-561004676

They're also [open source](https://github.com/timberio/vector-test-harness), and I welcome any feedback on ways we can improve them.

> Also, I did some performance tests and got totally different results :)

That statement is suspiciously vague :) . Which performance tests are you referring to? I'm assuming you [ran ours](https://github.com/timberio/vector-test-harness#setup)? Do you mind sharing the results? If fluentbit is misconfigured in any way we'd love to update the test, please feel free to submit a pull request.

I stand by the results though. We previously used fluentbit extensively with our customers on [Timber.io](https://timber.io) and have quite a bit of experience with it. That was the driving motivation behind creating [Vector](https://github.com/timberio/vector) :) .
