### ISSUE TITLE
Handle NaN in JSON when converting from message pack in msgpack2json function

### ISSUE THREAD

**Issue by brava-vinh** [fluent/fluent-bit#1588]
**Is your feature request related to a problem? Please describe.**

Say we have an message pack message with an `NaN`. When output to HTTP JSON, it's converted to JSON end up like this:

```
{"foo":nan}
```
which is obviously not a valid JSON.

The code is in https://github.com/fluent/fluent-bit/blob/master/src/flb_pack.c#L478-L485

```
            char temp[32] = {0};
            i = snprintf(temp, sizeof(temp)-1, "%f", o->via.f64);
            ret = try_to_write(buf, off, left, temp, i);
```
`"%f"` formating cause `nan` issue.

**Describe the solution you'd like**

`nan` should be encode as `null` in json. Given a message pack `{"foo":nan}` it should return this json:

```
{"foo":null}
```

So In this code:

```
    case MSGPACK_OBJECT_FLOAT32:
    case MSGPACK_OBJECT_FLOAT64:
        {
            char temp[32] = {0};
            i = snprintf(temp, sizeof(temp)-1, "%f", o->via.f64);
            ret = try_to_write(buf, off, left, temp, i);
        }
        break;
```

We can probably check if it's an `nan` and if so, we should just write `null` to buffer instead of using `%f` which resulted in `nan`.

**Comment by nigels-com** [comment]
There are probably other non-JSON-representable floating point values to consider.

C++ `std::isfinite` comes to mind
https://en.cppreference.com/w/cpp/numeric/math/isfinite

**Comment by edsiper** [comment]
@hasegaw @fujimotos what do you think about the proper behavior on this case ?

**Comment by fujimotos** [comment]
> We can probably check if it's an nan and if so, we should just write null to buffer instead of using %f which resulted in nan.

I think this is the correct behaviour. As far as I know, this is what `JSON.stringify`
in Javascript does, and should be compatible with other JSON parsers.

```
>>> JSON.stringify({"foo":NaN})
"{\"foo\":null}"
```

Alternatively, we can add an option to switch the behaviour. This is what Ptyhon does;
It provides `allow_nan` option to outputs NaN as is (e.g. `{"foo": NaN}`)

**Comment by nokute78** [comment]
I prefer to treat as an error. ( and an option allows to convert null like python)


Refer to JSON RFC, NaN is not permitted.

https://www.rfc-editor.org/rfc/rfc8259.html#section-6

Data type will be changed.
(number -> null)

https://www.rfc-editor.org/rfc/rfc8259.html#section-3

**Comment by brava-vinh** [comment]
@nokute78 In this particular case, We have a messagepack message with NaN, which is valid message pack.

The problem occurs when we convert it to JSON. Isn't raise an error is to aggresive here? Even javascript will convert NaN to null.

**Comment by edsiper** [comment]
I think NaN-> NULL on JSON conversion makes sense.

**Comment by brava-vinh** [comment]
sound good @edsiper I can whip up a PR for this.

**Comment by nokute78** [comment]
@brava-vinh 
> The problem occurs when we convert it to JSON. Isn't raise an error too aggressive here? Even javascript will convert NaN to null.

I think the default behavior is to obey RFC.

Ruby doesn't support NaN in JSON. 
Fluentd also doesn't support it in case of converting msgpack -> JSON.
https://github.com/fluent/fluentd/blob/master/test/plugin/test_filter_stdout.rb#L68
https://github.com/fluent/fluentd/issues/150

fluent-cat also reports error.
```
$ echo '{"nan":NaN}' |bin/fluent-cat debug.test
lexical error: invalid char in json text.
                                {"nan":NaN} 
                     (right here) ------^
```

ruby example:
```ruby
require "json"
json = {"num"=>Float::NAN}.to_json
```

I tested on Ubuntu18.04.
```
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
$ ruby a.rb 
Traceback (most recent call last):
	1: from a.rb:2:in `<main>'
a.rb:2:in `to_json': 865: NaN not allowed in JSON (JSON::GeneratorError)
```

FYI
There are a lot of example in many programming languages.

What happens when we use NaN/Inf in JSON ? (japanese article)
https://qiita.com/Nabetani/items/1e9af1ee1d25e3b463a0

**Comment by edsiper** [comment]
@nokute78 can you please submit a PR to fix the conversion of NaN in JSON ?

**Comment by nokute78** [comment]
@edsiper Sure.
My opinion is https://github.com/fluent/fluent-bit/issues/1588#issuecomment-543186215

I'll add  an new option to `[SERVICE]` to convert NaN to null. Default is false.
The name is `convert_nan_to_null`. 

How about this?
