### ISSUE TITLE
Error while parsing timestamp in glog format

### ISSUE THREAD

**Issue by jasimmk** [fluent/fluent-bit#1589]
## Bug Report

**Describe the bug**
Getting this error
```
[2019/09/25 07:06:31] [ warn] [parser:glog_format] Invalid time format m%d %H:%M:%S.%L for '0919 19:40:49.924011'.
[2019/09/25 07:06:31] [ warn] [parser:glog_format] Invalid time format m%d %H:%M:%S.%L for '0919 19:41:01.295787'.
[2019/09/25 07:06:31] [ warn] [parser:glog_format] Invalid time format m%d %H:%M:%S.%L for '0919 19:41:01.295832'

``` 
while parsing logs in glog format. While all the fields are properly extracted, its having issue to extract timestamp.

**To Reproduce**

`glogparser.config`
```
[Parser]
    Name        glog_format
    Format      regex
    Regex       ^(?<severity>[IWECF])(?<timestamp>\d{4} \d{2}:\d{2}:\d{2}\.\d{6}) +(?<thread>\d+) (?<src_file>[^:]+):(?<src_line>\d+)\] (?<rest>(?:.|\n)*)
    Time_Key    timestamp
    Time_Format m%d %H:%M:%S.%L
    Time_Keep   Off
    Types thread:integer src_line:integer
```
`test-glog.log`
```
I0919 19:40:49.923933    35 wapchatengine.cpp:4475] Iq operation by handler: "FieldStatsResult" took 127 ms req_id=WapRunner
I0919 19:40:49.924011    22 chatapp.cpp:2671] Field stats sent successfully req_id=Main
I0919 19:41:01.295787    22 servicemetrics.cpp:187] "{internal_server_requests_duration_ms_count,[RefreshAllHSMsResult,ok=104],[GetPrivacyListResult,404=1],[GetServerPropertiesResult,ok=2],[SendMessage,ok=1],[FieldStatsResult,ok=79]}" req_id=Main
I0919 19:41:01.295832    22 servicemetrics.cpp:187] "{internal_server_requests_duration_ms_sum,[RefreshAllHSMsResult,ok=15352],[GetPrivacyListResult,404=196],[GetServerPropertiesResult,ok=289],[SendMessage,ok=189],[FieldStatsResult,ok=10044]}" req_id=Main

```
`glog-config.config`
```
[SERVICE]
    Flush     5
    Daemon    off
    Parsers_File glogparser.config

[INPUT]
    Name tail
    Path test-glog.log
    Tag  *
    Buffer_Chunk_Size 256k
    Buffer_Max_Size 256k

[FILTER]
    Name        parser
    Match       *
    Parser      glog_format
    Key_Name    log

[OUTPUT]
    Name        stdout
    Match       *
```

**Steps**
- Copy above files in one directory
- Run `fluent-bit -c glog-config.config` you can see all fieilds are parsed. But timestamp is not parsed as time, but its just string as in log

**Expected behavior**

Expectation is timestamp field rendered as timestamp in output

**Your Environment**

* Version used: Fluent Bit v0.14.9
* Configuration: Pasted above
* Environment name and version (e.g. Kubernetes? What version?): MacOS Mojave 10.14.5
* Server type and version: n/a
* Operating System and version: 
```
Darwin macos-desktop.com 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
* Filters and plugins:
Pasted above

**Additional context**
glog (Google logging) is a famous log format used by multiple applications. Kubernetes, Mesos usually outputs logs in the format. Same for many golang/modern c++ apps.

`glog`  timestamps doesn't contain year. One way to solve this. Consider timestamp as now. Replace all the fields provided in the log from current timestamp.

**Comment by bluebike** [comment]
I wonder: `Time Format m%d %H:%M:%S.%L `   
Missing  % with m (month) ?  => `%m%d...`
= `Time Format %m%d %H:%M:%S.%L`

**Comment by jasimmk** [comment]
Thanks for the immediate help :rocket:. It was missing % as you specified. Sleepy eyes :( 

Changed it, and working like shiny jewel.

Intstalled fluent-bit via home brew
`brew install fluent-bit` noticed that its serving outdated version. :disappointed:
