### ISSUE TITLE
in_tail: incorrect file name comparation under macOS

### ISSUE THREAD

**Issue by kamyuentse** [fluent/fluent-bit#1591]
## Bug Report

**Describe the bug**

I test `in_tail` under macOS and notice the same file be added to the queue repeatedly, with the time going on, this would cause resources leak.

**To Reproduce**
- Steps to reproduce the problem:

Just run with the following conf:
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    HTTP_Server  Off

[INPUT]
    Name tail
    Path /tmp/nginx_access.log

[OUTPUT]
    Name  stdout
    Match *
```

**Expected behavior**

The same file should not be added to the queue infinitely.

**Screenshots**

<img width="862" alt="屏幕快照 2019-09-26 上午1 18 16" src="https://user-images.githubusercontent.com/15538025/65624954-75f19f80-dffd-11e9-995f-7aea9e0f5a3a.png">
<img width="786" alt="屏幕快照 2019-09-26 上午1 18 37" src="https://user-images.githubusercontent.com/15538025/65624961-7853f980-dffd-11e9-93b9-4ed4ec11ccfe.png">

**Your Environment**

* Version used: `master`
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?):  \
* Server type and version: \
* Operating System and version: macOS 10.14.6 (darwin 18.7.0)
* Filters and plugins: `in_tail`, `out_stdout`

**Additional context**

I think we can fix this problem just add a condition here, but I wonder should we revisit the mechanism to judge same file.

**Comment by edsiper** [comment]
thanks for the detailed report, fixed on #1596 . The fix will be part of v1.3 release
