### ISSUE TITLE
Support Debian Buster build and packages on packages.fluentbit.io

### ISSUE THREAD

**Issue by heartrobotninja** [fluent/fluent-bit#1592]
**Is your feature request related to a problem? Please describe.**

My company is running images based on Debian Buster which is not currently listed under supported builds. jessie is oldoldstable and stretch is oldstable. The current stable release is Buster. Source: https://www.debian.org/releases/

**Describe the solution you'd like**

Add buster to supported builds and have a deb package available on packages.fluentbit.org

**Describe alternatives you've considered**

Cloning and maintaining my own fork internally but that does not scale and is not desired.

**Additional context**

I am trying to use apt in order to deploy fluentbit to a large fleet of VMs. I am going to try to use the stretch version, but it would be much cleaner if there was an actual Buster build.

**Comment by edsiper** [comment]
Thanks. Starting from v1.3 release we will package for Buster too.

**Comment by edsiper** [comment]
here you go!

https://docs.fluentbit.io/manual/installation/debian#debian-10-buster
