### ISSUE TITLE
Docker_Mode combine lines should follow the same stream

### ISSUE THREAD

**Issue by hc-chien** [fluent/fluent-bit#1595]
## Bug Report
Occasionally found this bug. see the example:

there is one "stream":"stderr" record occur in between 3 split records and
cause Docker_Mode combined wrong lines:

> {"log":"very","stream":"stdout","time":"2018-08-06T10:33:50.916508402Z"}
> {"log":" long ","stream":"stdout","time":"2018-08-06T10:33:50.916508403Z"}
> _{"log":"ERR message\n","stream":"stderr","time":"2018-08-06T10:33:50.916508404Z"}_
> {"log":"message\n","stream":"stdout","time":"2018-08-06T10:33:50.916508404Z"}

result become:
> {"log": "very long ERR message\n", "stream":"stderr", "time":"2018-08-06T10:33:50.916508404Z"}
> {"log": "message\n", "stream":"stdout", "time":"2018-08-06T10:33:50.916508404Z"}

correct result should be:
> {"log": "very long message\n", "stream":"stdout", "time":"2018-08-06T10:33:50.916508404Z"}
> {"log":"ERR message\n","stream":"stderr","time":"2018-08-06T10:33:50.916508404Z"}

**Comment by jujugrrr** [comment]
hi @hc-chien , it looks like docker_Mode works for you with json(even fi you have a bit of mismatch)  where https://github.com/fluent/fluent-bit/issues/1115 says it doesn't( which is what we experiencing also).
could you share your fluent-bit versions and conf?

**Comment by pierluigilenoci** [comment]
@hc-chien is this still an issue?

**Comment by pierluigilenoci** [comment]
@hc-chien is this still an issue?

**Comment by pierluigilenoci** [comment]
@hc-chien is this still an issue?
