### ISSUE TITLE
Fluentbit is not working fine to send logs to Graylog

### ISSUE THREAD

**Issue by sanguinoj** [fluent/fluent-bit#1598]
## Bug Report

**Describe the bug**
Fluent bit is not running fine I have installed it as DaemonSet in k8s cluster .. 

Iḿ sending logs to Graylog but I get severals error in my Graylog server.

**To Reproduce**

- Example log message if applicable:
2019-09-26T16:26:29.021Z ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=649d19b7-e07a-11e9-bb16-000d3a44af83, journalOffset=251684814, codec=gelf, payloadSize=377, timestamp=2019-09-26T16:26:29.016Z, remoteAddress=/x.x.X.X:3013} on input <5d7fa641e432345511de9c74>.
2019-09-26T16:26:29.021Z ERROR [DecodingProcessor] Error processing message RawMessage{id=649d19b7-e07a-11e9-bb16-000d3a44af83, journalOffset=251684814, codec=gelf, payloadSize=377, timestamp=2019-09-26T16:26:29.016Z, remoteAddress=/x.x.x.x:3013}
java.lang.IllegalArgumentException: GELF message <649d19b7-e07a-11e9-bb16-000d3a44af83> (received from <x.x.x.x:3013>) has empty mandatory "short_message" field.
	at org.graylog2.inputs.codecs.GelfCodec.validateGELFMessage(GelfCodec.java:252) ~[graylog.jar:?]
	at org.graylog2.inputs.codecs.GelfCodec.decode(GelfCodec.java:134) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:86) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:45) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

- Steps to reproduce the problem:

**Expected behavior**
I wish to eliminate the error

**Screenshots**

**Your Environment**

* Version used:    image: fluent/fluent-bit:1.2.2
* Configuration:

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-graylog.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    # ${HOSTNAME} returns the host name.
    

# But Fluentbit runs in a container. So, it is not meaningful.
    # Instead, copy the host name from the Kubernetes object.
    [FILTER]
        Name nest
        Match *
        Operation lift
        Nested_under kubernetes

    # Remove offending fields, see: https://github.com/fluent/fluent-bit/issues/1291
    [FILTER]
        Name record_modifier
        Match *
        Remove_key annotations
        Remove_key labels

  output-graylog.conf: |
    [OUTPUT]
        Name          gelf
        Match         *
        Host          lokitojess.cloudapp.com
        Port          12205
        Mode          tcp
        Gelf_Short_Message_Key log

  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        #Decode_Field_As  escaped  log  
        #Decode_Field_As   escaped_utf8   log   
        Decode_Field_As  json  log

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

* Environment name and version (e.g. Kubernetes? What version?):

root@loadtests0:/etc/kubernetes/deployments/fluentbit# kubectl api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
batch/v2alpha1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
monitoring.coreos.com/v1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

* Server type and version:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

* Operating System and version:
* Filters and plugins:

**Additional context**

These Graylog error logs cause the journal directory to be filled

Therefore these messages are not processed by elastic-search and the cpu goes up to 100 percent.

**Comment by adriannieto-attechnest** [comment]
This also happens to me, if we enable new multiline mode it we get the missing field error:
```java.lang.IllegalArgumentException: GELF message <649d19b7-e07a-11e9-bb16-000d3a44af83> (received from x.x.x.x:3013) has empty mandatory "short_message" field.
```
