### ISSUE TITLE
Make out_stackdriver work on Windows

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1603]
**Is your feature request related to a problem? Please describe.**

Right now, we cannot use `out_stackdriver` on Windows.

This is due to the source code being incomatible with MSVC. Indeed,
the plugin raises multiple errors during build.

> stackdriver.h(90): error C2059: syntax error: 'constant'
> stackdriver.c(333): error C2143: syntax error: missing ')' before '*'

**Describe the solution you'd like**

Fix the code so that `out_stackderiver` compiles and runs fine on Windows.

**Describe alternatives you've considered**

To use Fluentd.

**Additional context**

This issue issue comes from https://github.com/fluent/fluent-bit/issues/960#issuecomment-533257706

**Comment by barney-s** [comment]
@fujimotos  - I would like to help here. Can you suggest where and how to get started on this. (New to fluentbit)

**Comment by fujimotos** [comment]
@barney-s  Thank you. I have posed a Windows port patch at #2041.

I appreciate if you can test that patch and confirm it works as expected.

**Comment by fujimotos** [comment]
... and the patch just has been merged into main line.

This feature will be usable in the next v1.4.0 release.

**Comment by barney-s** [comment]
Thanks for merging. Will do test it.
