### ISSUE TITLE
Implement a basic SSL/TLS support for in_forward

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1607]
**Is your feature request related to a problem? Please describe.**

This feature is a prerequisite to implement #927.

In order to enable mTLS, we first need to implement a basic
secure connection support on `in_forward`.

**Describe the solution you'd like**

Implement the feature following these steps:

1. Add a common infrastructure `flb_ssl_*` to establish SSL/TLS servers.
2. Implement SSL/TLS support on `in_forward` based on it.

**Describe alternatives you've considered**

Use TLS proxy.

**Additional context**

**Comment by git001** [comment]
Any update for this issue?

**Comment by smil2k** [comment]
I'm also very much interested in the possibility to use tls as input-forward.

**Comment by edsiper** [comment]
This feature is coming this year. Note there are a lot of changes required at the core level to expose TLS and others for forward protocol implementation.

**Comment by git001** [comment]
@edsiper any update on this issue?

**Comment by coderigo** [comment]
bump :) Would love to see this supported

**Comment by tarmacmonsterg** [comment]
> This feature is coming this year. Note there are a lot of changes required at the core level to expose TLS and others for forward protocol implementation.

Maybe you have any updates ?:) Now is 2022 
It's very impotant feature for many infrastructure.

Thanks!

**Comment by braunsonm** [comment]
v2 launched with TLS support for some of the input plugins, but oddly forward remains not supported. It still seems like only fluentd supports TLS on the forward protocol

**Comment by braunsonm** [comment]
With some testing today, it actually looks like this is supported in v2 but is missing in the documentation.

Configuring a forward input with TLS settings as you would a HTTP input works as expected, and you can see the TLS certificate presented with an `openssl s_client` check. 

I think this can be closed (maybe just update the docs)
