### ISSUE TITLE
Wrong Path in Ubuntu 18.04 Service Unit file

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit#1610]
## Bug Report

**Describe the bug**
Wrong path in Ubuntu Service Unit file

sudo vi /etc/systemd/system/multi-user.target.wants/td-agent-bit.service

you will see:
/etc//td-agent-bit/td-agent-bit.conf

The path should be:

/etc/td-agent-bit/td-agent-bit.conf

**Comment by edsiper** [comment]
thanks for reporting the problem.

I've fixed the path in a3a2cede, it will be part of release v1.3.1 (today)
