### ISSUE TITLE
Kube Plugin SSL Verification seems to be broken

### ISSUE THREAD

**Issue by Thoro** [fluent/fluent-bit#1615]
## Bug Report

**Describe the bug**

Fluent bit logs upstream certificate check error:

```
[2019/10/04 22:26:39] [error] [filter_kube] upstream connection error
[2019/10/04 22:26:39] [error] [io_tls] flb_io_tls.c:348 X509 - Certificate verification failed, e.g. CRL, CA or signature check
```

but the upstream certificate is fine:

```
curl https://kubernetes.default.svc:443 --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
Returns no certificate error, and the certificate definitely has the correct Alternative Names:

CN=kube-apiserver
X509v3 Subject Alternative Name:
IP Address:10.253.252.1, IP Address:10.21.13.5, IP Address:10.21.13.15, IP Address:10.21.13.25, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:at-host-02, DNS:at-host-12, DNS:at-host-22

This error occurs in banzaicloud/logging-operator, I therefore cannot set the ssl.verify = off (since there's no option for it, raised here: https://github.com/banzaicloud/logging-operator/issues/172)

**To Reproduce**
Start the provided configuration.

I assume that the issue might be the kubernetes url in the config, but all variations of the url are actually in the Subject Alternative Names. Possibly the SANs are not validated against?

I also found that: https://tls.mbed.org/kb/development/adding_new_subject_alternative_name_support

But it looks like DNS is supported by mbedtls, so still not clear.

**Expected behavior**

Fluentbit should successfully verify the certificate if a correct CA and Cert are provided, based on the error is also not clear what exactly failed (should be improved)

**Screenshots**

**Your Environment**

* Version used: fluent/fluent-bit:1.2.2
* Configuration:
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name             tail
    Path             /var/log/containers/*.log
    Parser           cri
    Tag              kubernetes.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    DB               /tail-db/tail-containers-state.db
    DB.Sync          Normal

[FILTER]
    Name                kubernetes
    Match               kubernetes.*
    Kube_Tag_Prefix     kubernetes.var.log.containers.
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log           On

[OUTPUT]
    Name          forward
    Match         *
    Host          10.21.240.33
    Port          24224
    
    Retry_Limit   False
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.15.3
* Operating System and version: Centos 7.6 / kernel 4.19.72
* Filters and plugins: see config

**Additional context**

**Comment by pepov** [comment]
hey @Thoro, thanks for the report! What kind of Kubernetes cluster do you use in question? Is the API Server running locally in the cluster? Can there possibly be any time difference issues so that the certificate was not yet valid for example?

**Comment by Thoro** [comment]
```
openssl s_client -connect kubernetes.default.svc:443 -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
CONNECTED(00000003)
depth=1 CN = kubernetes
verify return:1
depth=0 CN = kube-apiserver
verify return:1
---
Certificate chain
 0 s:/CN=kube-apiserver
   i:/CN=kubernetes
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgIJALh2vTkpEpqrMA0GCSqGSIb3DQEBBQUAMBUxEzARBgNV
BAMTCmt1YmVybmV0ZXMwHhcNMTkwNzAzMTQyNjMzWhcNMjkwNjMwMTQyNjMzWjAZ
MRcwFQYDVQQDDA5rdWJlLWFwaXNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAMj1NfWQ0WDwp8iNQhTI8dh+E6b+lMeuYFnepnSUXy6ctGeUKroO
BL396VKbh2KCjpum7Cy71qKcFBlviiZ0XCLOI1HqvdKnnPTnZQS9rsVNor+P0mMr
evnPv9ZfhUx3SgzAzsLC4ZnKtg+VnCB0QXfknwqKDouyyh+8oly10MwASCePtPrs
XxG3KbHJSYdzg6M+S69iW76G5CD3uPdP0Zz5T72UF4DigSUTRgHm0ui4NUVTZHXf
KSFjQ9WTp2YAlCCLgVqlkVM7v4yoUuyo89WHGiJ1xPZadYOPwF9RmHpOnPqLBvIt
xh8pT3Xbfg1DIeBU5erkgW2DwRizRrB4u/8CAwEAAaOBwzCBwDAJBgNVHRMEAjAA
MAsGA1UdDwQEAwIF4DCBpQYDVR0RBIGdMIGahwQK/fwBhwQKFQ0FhwQKFQ0PhwQK
FQ0ZggprdWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1bHSCFmt1YmVybmV0ZXMu
ZGVmYXVsdC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2Nh
bIIKYXQtaG9zdC0wMoIKYXQtaG9zdC0xMoIKYXQtaG9zdC0yMjANBgkqhkiG9w0B
AQUFAAOCAQEAY7VMWyqUqsqATj21H4tFwsHq8UDElryLQSuy2eRZTRTv03Waay97
JYdZEzkAw+Hfccb701Fp6pwvJbRhrhXbWpx40xX1onfvgh9xNW/eq2jngu3wcOD1
tP3wpgImzCmToBfBsyBMTPIG61MqC+mtWO2iF8Ndb6nRC4EHZVtsSG/q73qESnrP
w3aQC4ybLr9xL2ObX828RFfNliXikrt7Oj+zPpGwt5i4vEzSfeVLKPrmjiB9i8WV
YfL+9N/aJTW+4LwXUMLgzr3NPbs/ZjLUEs+rV47242y9JyFV4a9bAb171o1/8NQV
lvYnWI2Okr+3iqA912Zgvq7rcvZt3A0tMQ==
-----END CERTIFICATE-----
subject=/CN=kube-apiserver
issuer=/CN=kubernetes
---
Acceptable client certificate CA names
/CN=kubernetes
/{redacted}/OU=kubernetes-aggregation-ca
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA512:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1700 bytes and written 427 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 326C404C67AADE72BD1E76E7DC34CB5A3CB37307B09850197E6889E3184AA5FB
    Session-ID-ctx:
    Master-Key: 451E6C7C731DEC79EB50D94DB27A17005D41E9E8877F8C9BF1EF2E0B205E07F4626073CDD51C4A7573FB0093BCFFF773
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket:
    0000 - 40 60 bf 31 92 13 a7 9d-ce b0 9b 34 16 21 c9 fb   @`.1.......4.!..
    0010 - e0 56 ba f2 6c 44 f5 7d-38 13 ad 50 34 69 ee d2   .V..lD.}8..P4i..
    0020 - 41 11 d6 79 0a 1f 51 99-f9 2b 40 32 65 07 39 7c   A..y..Q..+@2e.9|
    0030 - 8a 8a 38 01 1e b8 b1 f1-61 86 26 73 25 7a 70 08   ..8.....a.&s%zp.
    0040 - a5 07 c5 a3 84 34 61 02-89 fb 1f e3 85 ff 76 02   .....4a.......v.
    0050 - 3d 21 1b 03 06 4c 19 e4-05 f0 d7 38 be 0c f5 30   =!...L.....8...0
    0060 - 48 14 47 a6 06 49 49 15-ca f8 eb 2f 22 d2 27 78   H.G..II..../".'x
    0070 - 73 06 94 b8 50 df c8 14-                          s...P...

    Start Time: 1570435032
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by Thoro** [comment]
Even after enabling debug:
```
tls.debug           4
    tls.verify          On
```

I do not receive any additional out, except what I posted above, it's very hard to test this with the docker container - is there a possiblity to get that image out?

**Comment by Thoro** [comment]
Actually found that there's the centos repo, tried it directly on the host, same issue.

**Comment by edsiper** [comment]
would you please verify if in the certificates path of the Pod or in the system is there any broken symbolic link ?

**Comment by Thoro** [comment]
I copied the files to the host itself, so no symbolic links. I also executed the openssl command in a container and it was fine. (i.e. no broken links)

It could possibly be an issue with the fluentd container, but I believe if it can't access the app throws an error (tried that)

**Comment by Thoro** [comment]
I can also build it and add some custom debug logs, but I would need the correct packages to build this on Centos 7

**Comment by edsiper** [comment]
can you try please the fluent/fluent-bit:1.3.1-debug image and confirm if you still see the issue ?, if so, if you enable ```tls.debug 4```, what do you see in the logs with kubectl log ?

**Comment by Thoro** [comment]
Yep, and that's with tls.debug 4

```
Fluent Bit v1.3.1
Copyright (C) Treasure Data

[2019/10/08 04:10:13] [ info] [storage] initializing...
[2019/10/08 04:10:13] [ info] [storage] in-memory
[2019/10/08 04:10:13] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/10/08 04:10:13] [ info] [engine] started (pid=1)
[2019/10/08 04:10:13] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2019/10/08 04:10:13] [ info] [filter_kube] local POD info OK
[2019/10/08 04:10:13] [ info] [filter_kube] testing connectivity with API server...
[2019/10/08 04:10:13] [error] [io_tls] flb_io_tls.c:355 X509 - Certificate verification failed, e.g. CRL, CA or signature check
[2019/10/08 04:10:13] [error] [filter_kube] upstream connection error
[2019/10/08 04:10:13] [ warn] [filter_kube] could not get meta for POD logging-fluentbit-w2qng
[2019/10/08 04:10:13] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2019/10/08 04:10:13] [ info] [sp] stream processor started
[2019/10/08 04:10:13] [error] [io_tls] flb_io_tls.c:355 X509 - Certificate verification failed, e.g. CRL, CA or signature check
[2019/10/08 04:10:13] [error] [filter_kube] upstream connection error
[2019/10/08 04:10:13] [error] [io_tls] flb_io_tls.c:355 X509 - Certificate verification failed, e.g. CRL, CA or signature check
```

**Comment by Gerhut** [comment]
Also encountered in this issue.

I am using IP address (`https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}`) for `Kube_URL` but the ca only has subject alt name  : kubernetes, kubernetes.default, kubernetes.default.svc, kube
rnetes.default.svc.cluster.local, (My internet domain)

Might this be a cause after SNI enabled? If so, another `tls.vhost` is required in filter_kube plugin

**Comment by edsiper** [comment]
@Gerhut adding the normal tls.vhost feature would solve the problem ? (if so, we can add it before 1.4 release)

**Comment by Gerhut** [comment]
I think it would solve the problem base on my tests. If necessary I will hard code a kubernetes.default.svc records in my host mahcine to have a final test.

**Comment by edsiper** [comment]
Got it, I will push the changes shortly

**Comment by edsiper** [comment]
@Gerhut can you try the following ```release candidate``` image ?

```
fluent/fluent-bit:1.4.0-rc2
```

notes:

- this image is for x86_64 only
- you have to set the property ```tls.vhost``` in your Kubernetes filter

**Comment by Gerhut** [comment]
It works fine! After I did the following steps:

1. Upgrade image tag to 1.4.0-rc2
2. Replace `tls.verify Off` with `tls.vhost kubernetes.default.svc`

Really appreciate!

**Comment by Gerhut** [comment]
Share my final filter config

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        tls.vhost           kubernetes.default.svc

**Comment by edsiper** [comment]
awesome, thanks for confirming :)

The official release is on this Wednesday
