### ISSUE TITLE
Create a Counter Output from Record Count after Filtering

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit#1618]
Alerts do not require shipping files or centralization. 
We need a simple record counter that prometheus can scrape.
The Filter would simply count the number of records and output a label / count key value pair.
Then with the counter in prometheus format, a scrape would be applied thereby enabling alarms without moving logs off the machine. This is a very common use case.

**Comment by edsiper** [comment]
@kaizen1 

would the following workaround be suitable for your use case ?

```
[INPUT]
    Name     tail
    Alias    files
    Path     /some/path/20.log
    Routable off
```

then from when querying the metrics interface (using json / jq for the test):

```
$ curl -s http://127.0.0.1:2020/api/v1/metrics | jq .input.files.records
20
```

When setting an input as ```routable off```, means the records are discarded right away when hitting the storage or stream processor if any.

**Comment by kaizen1** [comment]
Thanks! I'll try it....

In my workaround, I used a file OUTPUT and then the fluent bit prometheus end point puts out the number of records that are in the file. I pull them into prometheus and alarm on that. Your idea is cleaner since no file is generated. Actually I want to do this off of systemd input.

**Comment by edsiper** [comment]
so it should work, ```Routable``` is a configuration property available on all input plugins

**Comment by kaizen1** [comment]
Related question, I have several different counters that I want to pull from the same INPUT --systemd (journald). Can I have multiple INPUTS that are the same and then have different FILTER and OUTPUT sections for each INPUT? It's not clear from the docs and I've never seen examples where the same INPUT is repeated.

**Comment by edsiper** [comment]
every input is a single instance of that collector input plugin running, you can enable multiple of them. Everyone get it own separate metrics. Data that flows to Filters and outputs depends on Tag and Matching rules:

ref: https://docs.fluentbit.io/manual/getting_started/routing

**Comment by kaizen1** [comment]
Great, but I can't get multiple INPUT instances to work. In the case below, the second INPUT output is always the same as the first INPUT instance, which is definitely not correct. Using different Name for each INPUT instance does not help. In fact, the agent won't start if I do that.
(side note I think "Name" should be called Type, because normally a Name is something a user can change, and it's not the case here.)

[INPUT]
    Name systemd
    Path /var/log/journal/
    Tag  host.*
    Tag ssh
    Parser: systemd-json
    Read_From_Tail true
    Routable off

[FILTER]
    Name   grep
    Match  *
    Regex  MESSAGE /preauth/

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Whitelist_key MESSAGE

[OUTPUT]
    Name  file
    Match *
    Path /etc/td-agent-bit/ssh.txt
    Format out_file

[INPUT]
    Name systemd
    Path /var/log/journal/
    Tag  host.*
    Tag ssh
    Parser: systemd-json
    Read_From_Tail true
    Routable off

[FILTER]
    Name   grep
    Match  *
    Regex  MESSAGE /systemctl/

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Whitelist_key MESSAGE

[OUTPUT]
    Name  file
    Match *
    Path /etc/td-agent-bit/system.txt
    Format out_file

**Comment by kaizen1** [comment]
I know. I figured that out. But multiple inputs with the same source (systemd) don't  work (config above.)
