### ISSUE TITLE
Upgrading td-agent-bit overwrites existing config without prompts (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Thericho** [fluent/fluent-bit#1619]
## Bug Report

**Describe the bug**
When I upgrade from version 1.2.2 to version 1.3.0, existing configuration files are overwritten by default configuration files from the package.

**To Reproduce**
- Install version 1.2.2 and update configuration files `parsers.conf` and `td-agent-bit.conf`
- Upgrade to version 1.3.0 with `apt install td-agent-bit=1.3.0`
- After the upgrade, neither service nor system was restarted but configuration files have been overwritten.

**Expected behavior**
- Upgrade to version 1.3.0 should retain existing configuration *or*
- prompt user for decision to keep existing config/overwrite with default

**Your Environment**
* Current version used: 1.2.2
* Upgrade version: 1.3.0
* Operating System and version: Ubuntu 18.04

**Additional context**
Minimal impact to operations but I am keeping to version 1.2.2 until this is fixed.

**Comment by edsiper** [comment]
thanks for reporting the issue.

I've pushed fix 676b9b1e, this will be part of v1.3.2 release this week.
