### ISSUE TITLE
NULL dereference on memory allocation error (plugins / in_tail)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1622]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/plugins/in_tail/tail_scan_glob.c 
91:            tmp = flb_malloc(PATH_MAX);
92:            snprintf(tmp, PATH_MAX -1, "%s%s", dir, p);

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
Thanks for reporting the missing check.

It has been fixed on e3984c20290f1241a94df21ddaba8bcf4f1d9019
