### ISSUE TITLE
NULL dereference on memory allocation error (plugins / out_nats)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1623]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/plugins/out_nats/nats.c
191:    request = flb_malloc(json_len + tag_len + 32);
192:    req_len = snprintf(request, tag_len + 32, "PUB %s %zu\r\n",
193:                       tag, json_len);

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
thanks.

Fixed missing validation in 64937a03c24d8dd6f18d1a71464ead779e834613
