### ISSUE TITLE
NULL dereference on memory allocation error (plugins / out_flowcounter)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1624]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/plugins/out_flowcounter/out_flowcounter.c
97:    ctx->buf = (struct flb_out_fcount_buffer*)
98:        flb_malloc(sizeof(struct flb_out_fcount_buffer)*ctx->size);
99:
100:    for (i=0; i<ctx->size; i++) {
101:        ctx->buf[i].until = base + ctx->tick*i;
102:        count_initialized(&ctx->buf[i]);
103:    }

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
Fixed by ccef9217.

thanks

**Comment by nokute78** [comment]
I sent a PR to use the validation result value.
