### ISSUE TITLE
NULL dereference on memory allocation error (plugins / in_mem)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1625]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/plugins/in_mem/proc.c
32:    char *buf = flb_malloc(len);
... (no operations on buf)
44:       snprintf(buf, len, "%ld %s", size, __units[0]);

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
Fixed by 478478de

thanks
