### ISSUE TITLE
NULL dereference on memory allocation error (plugins / in_netif)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1627]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/plugins/in_netif/in_netif.c
75:    ctx->entry = flb_malloc(sizeof(struct netif_entry) * ctx->entry_len);
76:    for(i=0; i<ctx->entry_len; i++) {
77:        ctx->entry[i].name     = entry_name_linux[i].name;

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
Fixed by 8b36716e

thanks

**Comment by nokute78** [comment]
8b36716e277ea2ec75fdba9de93626bcaefc7880 is incomplete.

I sent a patch to fix this issue.

**Comment by edsiper** [comment]
thanks @nokute78
