### ISSUE TITLE
NULL dereference on memory allocation error (flb_kernel)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1628]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code (2 issues): 
fluent-bit/src/flb_kernel.c
41:    kernel->s_version.data = flb_malloc(16);
42:
43:    len = snprintf(kernel->s_version.data, 16, "0.0.0");

(duplicate below)

119:    kernel->s_version.data = flb_malloc(16);
120:
121:    len = snprintf(kernel->s_version.data, 16, "%i.%i.%i", a, b, c);

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
Fixed by 59046f6d

thanks
