### ISSUE TITLE
NULL dereference on memory allocation error (flb_input)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#1629]
## Bug Report

**Describe the bug**
NULL dereference (value returned by flb_malloc is not checked) after memory allocation error (flb_malloc is wrapper on malloc returning NULL on unsuccessful allocation).
In most cases this issue will lead to crash via segmentation fault.

Vulnerable code:
fluent-bit/src/flb_input.c
520:    collector = flb_malloc(sizeof(struct flb_input_collector));
521:    collector->id          = collector_id(in);
(duplicates)
545:    collector = flb_malloc(sizeof(struct flb_input_collector));
546:    collector->id          = collector_id(in);
...
793:    collector = flb_malloc(sizeof(struct flb_input_collector));
794:    collector->type        = FLB_COLLECT_FD_SERVER;

**To Reproduce**
Problem was identified by source code review.

**Expected behavior**
Memory allocation errors should be handled by checking value returned by flb_malloc().

**Your Environment**
* Version used:
Current "master" branch

**Additional context**
See following recommendations for details:
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Comment by edsiper** [comment]
Fixed by f232f8d5
