### ISSUE TITLE
Typo error in error message

### ISSUE THREAD

**Issue by vmahe35** [fluent/fluent-bit#1638]
## Bug Report

In some conditions, there is an error message that contains "Length of content has execeded limit"
It should be corrected to "Length of content has exceeded limit"

See https://github.com/fluent/fluent-bit/blob/d19be0d7651eb2463e95ffbca9295bde95f50567/lib/monkey/mk_core/mk_rconf.c#L241

**Comment by nokute78** [comment]
@edsiper The message was added by #1488,
but we cannot find the message on monkey repo.
https://github.com/monkey/monkey/blob/master/mk_core/mk_rconf.c

How should we fix it ?
I sent a patch #1651 to fix fluent-bit repo.

**Comment by edsiper** [comment]
thanks everyone, this is fixed through a18c0f0c
