### ISSUE TITLE
Dockerfile for arm

### ISSUE THREAD

**Issue by huanggze** [fluent/fluent-bit#1639]
**Is your feature request related to a problem? Please describe.**

I found arm-based image available on Docker Hub, but didn't find relevant Dockfiles. Would you provide it or they are available somewhere else?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edsiper** [comment]
they are located here:

https://github.com/fluent/fluent-bit-docker-image/tree/1.3
