### ISSUE TITLE
Remove Output File / Restart Service Unit Does Not Recreate Output Files

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit#1641]
1. using td-agent-bit (latest) on Ubuntu 18.04
2. stop service using systemctl stop td-agent-bit
3. delete 2 outputs files (see config below)
4. start again using systemctl start td-agent-bit
5. OUTPUT FILES ARE NOT GENERATED AGAIN (I tried to restart the service unit many times). 
6. Also, before deleting the output files, the content of the two output files was exactly the SAME data. This cannot be correct with two different regexes. So this is another issue - i.e. two INPUT instances with the same source (systemd) does not work.

    
```
     Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.

    Log_Level error

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File parsers.conf

    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server  On
    HTTP_Listen 10.128.0.22
    HTTP_PORT 80

[INPUT]
    Name systemd
    Path /var/log/journal/
    Tag  host.*
    Parser: systemd-json
    Read_From_Tail true

[FILTER]
    Name   grep
    Match  *
    Regex  MESSAGE /preauth/

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Whitelist_key MESSAGE

[OUTPUT]
    Name  file
    Match *
    Path /etc/td-agent-bit/ssh1.txt
    Format out_file

[INPUT]
    Name systemd
    Path /var/log/journal/
    Tag  host.*
    Parser: systemd-json
    Read_From_Tail true

[FILTER]
    Name   grep
    Match  *
    Regex  MESSAGE /systemctl/

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Whitelist_key MESSAGE

[OUTPUT]
    Name  file
    Match *
    Path /etc/td-agent-bit/system2.txt
    Format out_file
```

**Comment by kaizen1** [comment]
Before deleting the output files, the content of the two files was the SAME. This is incorrect. So two INPUT instances with the same does not work.

**Comment by nigels-com** [comment]
Check the logs to confirm that fluent-bit is actually restarting. (I suspect not)

Try giving the two inputs unique tags rather than `host.*`.
Match the appropriate tag for the filters and output, rather than `*`.

**Comment by kaizen1** [comment]
It is running after restart. So it's a bug. Too many bugs in this project. I'm moving on. 

● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/lib/systemd/system/td-agent-bit.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-10-11 13:05:18 UTC; 46s ago
 Main PID: 644 (td-agent-bit)
    Tasks: 5 (limit: 4426)
   CGroup: /system.slice/td-agent-bit.service
           └─644 /opt/td-agent-bit/bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf

**Comment by edsiper** [comment]
data will be the same since your "Parser" in systemd config is not valid. Systemd input plugin don't support a parser definition., you have to enable filter parser for the purpose:

- https://docs.fluentbit.io/manual/input/systemd
- https://docs.fluentbit.io/manual/filter/parser

**Comment by kaizen1** [comment]
HAProxy has a configuration file checker. It parses, validates and outputs useful error messages. Your product needs a good validator.

**Comment by kaizen1** [comment]
FYI, it's not fixed. Restart Service Unit Does Not Recreate Output Files after deleting the files.

**Comment by nigels-com** [comment]
By my reading of the config file above I wouldn't be expecting any output.
The filters will be excluding just about everything.

```
[FILTER]
    Name   grep
    Match  *
    Regex  MESSAGE /preauth/

[FILTER]
    Name   grep
    Match  *
    Regex  MESSAGE /systemctl/
```
Tag the inputs with separate names and plumb those through the filters and the outputs.
See: https://docs.fluentbit.io/manual/v/1.3/getting_started

**Comment by kaizen1** [comment]
OK, you're correct. I changed Match from * to the tag value and I get 2 new files on restart - one for each INPUT. Thanks.

[INPUT]
    Name systemd
    Path /var/log/journal/
    Tag  systemctl
    Read_From_Tail true

[FILTER]
    Name   grep
    Match  systemctl
    Regex  MESSAGE /systemctl/
