### ISSUE TITLE
Windows DLL Error

### ISSUE THREAD

**Issue by plinkable** [fluent/fluent-bit#1646]
## Bug Report

**Describe the bug**
There is no download link for Windows on the download page. The only link I can find for Windows is on:

- https://docs.fluentbit.io/manual/installation/windows

Currently this is pointing to 1.3.1 rather than 1.3.2 and the downloaded binary doesn't run on any version of 64-bit Windows.

**To Reproduce**
Download and install from the above link. Run:

```
fluent-bit.exe -i dummy -o stdout
```

**Expected behavior**
Program runs and emits messages

**Screenshots**
![image](https://user-images.githubusercontent.com/30353910/66648640-f3372a00-ec23-11e9-95e0-d661acb3cd3a.png)
![image](https://user-images.githubusercontent.com/30353910/66649002-eb2bba00-ec24-11e9-9d4b-12fc202517ac.png)

**Your Environment**
* Version used: 1.3.1
* Configuration: none
* Environment name and version (e.g. Kubernetes? What version?): n/a
* Server type and version: 10, 2008, 2012, 2016
* Operating System and version: Windows 64 bit
* Filters and plugins: n/a

**Additional context**
This completely prevents me from using fluentbit on Windows hosts, and the download page needs to have up-to-date download links for Windows.

**Comment by plinkable** [comment]
The Windows page even says there should be links, but I only see one link for source:

> Download an EXE installer from the download page. It has both 32-bit and 64-bit builds. Choose one which is suitable for you.

**Comment by edsiper** [comment]
Information updated:

https://docs.fluentbit.io/manual/installation/windows

**Comment by edsiper** [comment]
thanks

**Comment by plinkable** [comment]
The new version hasn't fixed the problem, the same error is appearing

**Comment by edsiper** [comment]
@fujimotos

**Comment by fujimotos** [comment]
@plinkable Hi. Can you test this build?

https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/28110050/job/cte76oenarbvvkk9/artifacts

 `ssleay32.dll` is the OpenSSL library for Windows. The library was required because
we bundled `out_kafka` in the installer by default. I've just fixed that part in #1656.

**Comment by plinkable** [comment]
That version works as expected.

**Comment by JungleGenius** [comment]
Hello Can someone please tell me where I can download the Windows td-agent-bit installer for the version that doesn't have this missing DLL issue? I've got to get this agent installed this weekend.

**Comment by fujimotos** [comment]
Fixed by #1656.
