### ISSUE TITLE
Documentation has Nonsensical English

### ISSUE THREAD

**Issue by kaizen1** [fluent/fluent-bit#1652]
From:

https://docs.fluentbit.io/manual/configuration/file#config_input

These make no sense in English. So it's not clear what is trying to be conveyed.

```
Match
It sets a pattern to match certain records Tag. It's case sensitive and support the star (*) character as a wildcard.

Match_Regex
It sets a pattern to match certain records Tag.
```

**Comment by nigels-com** [comment]
Could you report this over on the documentation issue tracker?  Thanks.
https://github.com/fluent/fluent-bit-docs/issues

**Comment by kaizen1** [comment]
Done.
