### ISSUE TITLE
Please publish the GPG key fingerprint in your documentation

### ISSUE THREAD

**Issue by vaseeharan** [fluent/fluent-bit#1655]
https://docs.fluentbit.io/manual/installation/redhat_centos should contain the fingerprint of the yum repository signing key so that it can be independently verified after downloading.

$ gpg --fingerprint
...
pub   rsa2048 2015-09-01 [SC]
      F209 D876 2A60 CD49 E680  633B 4FF8 368B 6EA0 722A
uid           [ unknown] Eduardo Silva <eduardo@treasure-data.com>
sub   rsa2048 2015-09-01 [E]

also, please change the gpgkey URL in the yum repo config to https
gpgkey=http://packages.fluentbit.io/fluentbit.key

**Comment by vaseeharan** [comment]
I've proposed https://github.com/fluent/fluent-bit-docs/pull/225

**Comment by agup006** [comment]
Looks like this now exists on docs. Closing
