### ISSUE TITLE
Identify remote client

### ISSUE THREAD

**Issue by holyhope** [fluent/fluent-bit#1658]
I would like to **identify clients** on fluentbit with *forward* input and add a field with the identity to logs.

1. Identify by IP from the TCP connection. I looked for kind of remote address variable, but did not find what I expected (not the hostname of the fluentbit server, but the remote IP of the connection).
2. Identify by certificate. I would like to add CommonName from clients' certificate to a field. Still do not know hos to accomplish it.

I think the solution 2 is smarter than the first one.

### More context

For about 800 servers, I would like to setup fluentbit to push to some others fluentbit with forward input configuration (these fluentbit *servers* then forward logs to [OVH Logs Plateform](https://www.ovh.com/fr/data-platforms/logs/)).
I cannot trust fields sent by these servers since servers owners can update the fluentbit configuration and send fields they want.

**Comment by edsiper** [comment]
Thanks for sharing your use case. Your request makes sense, we will do this as an enhancement request, no ETA yet.

**Comment by seanshahkarami** [comment]
Hello! I'm following up to see if this feature or a recommended alternative was ever implemented.

I believe we have a requirement similar to the original post:

We want to tag logs and metrics sent from our edge clients to our main server side to prevent impersonation, in case they are ever compromised.

Either of the following would make it a lot easier to address our problem:
1. Add certificate common name as a user-specified field.
2. Verify certificate common name matches a user-specified field.

Thank you!
