### ISSUE TITLE
fluent-bit is not able to add the files to the scan queue if the log file is does not exists.

### ISSUE THREAD

**Issue by NikhilTejSR** [fluent/fluent-bit#1666]
fluent-bit is not able to add the files to the scan queue if the log file does not exists during the startup. After some time the log file gets created and fluent-bit is unable to the file to scan queue.

Steps to Reproduce:
1. start fluent-bit process with log file which does not exists should be configured.
2. After starting fluent-bit, create the log file.

Below is the fluent-bit log:
[2019/10/17 12:57:39] [debug] [in_tail] scanning path /logstore/**/RtpDump.log
[2019/10/17 12:57:39] [debug] [in_tail] Cannot read info from: /logstore/**/RtpDump.log

Below is the fluent-bit conf:
[SERVICE]
   Flush 1
   Log_Level debug
   Daemon on
   Log_File /home/rtp99/99/log/fluent-bit.log
   Plugins_File /fluent-bit/etc/plugins.conf
   Parsers_File /fluent-bit/etc/parser.conf

[INPUT]
   Name tail
   Tag dump.log
   Path /logstore/**/RtpDump.log
   Path_Key class

[OUTPUT]
   Name gstdout
   Match *

We are not able to send the log file to the required destination because of this issue.
Could you please help us to resolve the issue.

**Comment by NikhilTejSR** [comment]
We have also tried with the option Refresh_Interval 10 and it is not working.

**Comment by edsiper** [comment]
@NikhilTejSR 

One note, the wildcard expansion only will look for one subdirectory level, e.g: For the following content:

```
/path/something/test.log
/path/subdir/something/test.log
```

a configuration like ```Path /path/*/test.log``` will only process the data from ```/path/something/test.log``` file.

Now the __debug__ message you are posting ```Cannot read info from: /logstore//RtpDump.log``` is raised when the Glob pattern do not have matches or no entries found.

Would you please paste the content of your ```/logstore/``` directory ?
