### ISSUE TITLE
need fluent bit tail to avoid starting at head.

### ISSUE THREAD

**Issue by bcallanan** [fluent/fluent-bit#1667]
**Is your feature request related to a problem? Please describe.**

My enhancement doesn't seem to be a bug. More of a like/must have. I'm using a compiled version of fluent bit 1.3.0. I have found the the compile version memory footprint is ~27mb. Where the apt-get td-fluent-bit version is ~56mb. So I'd prefer the smaller footprint  as I am very memory conscious. 

Am I missing a flag in my config file?

**Describe the solution you'd like**

The log files I'd like to monitor/tail are long and I'm not able to truncate at all. The files are pre-existing and in some cases ~ a year old. I would like to just start at the end of the file and continue monitoring from there.  I'm retrofitting a tailing service on old servers that can't forward log data...

**Additional context**

When the files are as big as they are it causes my elasticsearch server to choke and die. I can't ingest files that large. 

My config. the log file maybe quite large and the initial start is very problematic. I cannot truncate the  log.

    @SET my_es_server=10.70.0.18
    @SET my_es_server_port=9200
    @SET my_hostip=192.168.1.8

    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    trace
        Parsers_File parsers.conf      
        LOG_FILE /var/log/fluent_bit.log

    [INPUT]
        Name             tail
        Path             /opt/logs/ops.queue
        Tag              ops.*
        Mem_Buf_Limit    3MB
        Multiline        On
        DB               /opt/logs/ops.queue.db
        Parser_Firstline opsqueue_head
        Parser_1         opsqueue_ltsv
        Parser_2         opsqueue_tail

    [FILTER]
        Name record_modifier
        Match *
        Record hostname ${HOSTNAME}
        Record hostip ${my_hostip}

    [OUTPUT]
        Name                es
        Match               ops.*
        Host                ${my_es_server}
        Port                ${my_es_server_port}
        Logstash_Format     On
        Logstash_Prefix     fluent_bit_ops_queue
        type                opsQueue
        Include_Tag_Key     Off
        Retry_Limit         False
        Logstash_Prefix_Key es_index

My parser file entries...

    [PARSER]
        Name    opsqueue_head
        Format  regex
        Regex   ^(?<opsQueueEntry>OPERATION.*)$
    
    [PARSER]
        Name    opsqueue_tail
        Format  regex
        Regex   (?m)^(OPERATION.*)(.*)$

    [PARSER]
        Name    opsqueue_ltsv
        Format  ltsv

A sample multi-line row of data

    OPERATION DETAILS

    Operation Id:	0012.000
    Type:		Import Schedule               
    Associated Data:	For : CSP for day: 12/16/17              
    Status:		Completed          
    Run Time:	12/14/17 at 06:20:18 MST
    Repeat:		-------
    Attempt:		1 of 3
    Owner:		

    Queued from machine 127.0.0.1 on port 10000

    Operation log:
    12/14/17 06:20:04 MST	Queued
    12/14/17 06:20:28 MST	Running
    12/14/17 06:20:30 MST	Complete

Sample of row in ES.

            {
                "_index": "fluent_bit_ops_queue-2019.10.18",
                "_type": "opsQueue",
                "_id": "2__Z320BGeP9YPH1kK0v",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2019-10-18T17:10:33.545Z",
                    "opsQueueEntry": "OPERATION DETAILS\nOperation Id:\t9593.000",
                    "Type": "\nAssociated Data:\tFor : PRT for day: 12/13/17              ",
                    "Status": "\nRun Time:\t12/13/17 at 10:05:26 MST",
                    "Repeat": "",
                    "Attempt": "",
                    "Owner": "\nQueued from machine 127.0.0.1 on port 10000\nOperation log:\n12/13/17 10:05:11 MST\tQueued\n12/13/17 10:05:26 MST\tRunning\n12/13/17 10:05:29 MST\tComplete",
                    "hostname": "vb1604b",
                    "hostip": "192.168.1.8"
                }
            },

**Comment by sysword** [comment]
Any updates on this?

**Comment by bcallanan** [comment]
For me the feature was/is a non starter. The log files I had were huge and I could not start monitoring immediately from the tail. I had to use filebeat instead.

**Comment by edsiper** [comment]
fixed in https://github.com/fluent/fluent-bit/commit/70e33fa2618227882d48faf690848bb4117cdb3e

This will be part of release v1.6 next week.
