### ISSUE TITLE
wrong path to /etc in file init/systemd.in 

### ISSUE THREAD

**Issue by x09** [fluent/fluent-bit#1676]
## Bug Report

**Describe the bug**
wrong path to /etc in file init/systemd.in 
need add leading slash to @CMAKE_INSTALL_SYSCONFDIR@
```

--- fluent-bit-1.3.2/init/systemd.in.orig       2019-10-22 14:32:53.487705959 +0500
+++ fluent-bit-1.3.2/init/systemd.in    2019-10-22 14:16:49.473138254 +0500
@@ -5,7 +5,7 @@
 
 [Service]
 Type=simple
-ExecStart=@CMAKE_INSTALL_FULL_BINDIR@/@FLB_OUT_NAME@ -c @CMAKE_INSTALL_SYSCONFDIR@/@FLB_OUT_NAME@/@FLB_OUT_NAME@.conf
+ExecStart=@CMAKE_INSTALL_FULL_BINDIR@/@FLB_OUT_NAME@ -c /@CMAKE_INSTALL_SYSCONFDIR@/@FLB_OUT_NAME@/@FLB_OUT_NAME@.conf
 Restart=always
 
 [Install]

```

**Comment by edsiper** [comment]
thanks for reporting the problem.

Recently we were asked to fix that in the other way back :/ :

- a3a2cede9b7d0328da7c0227125d7df657ffcd0c

would you please specify your distro and version? I think we will have to tweak the packager a bit depending on the target platform

**Comment by x09** [comment]
I make rpm package for AltLinux 8.x for private using ;) but i can put it in official repositories.
