### ISSUE TITLE
Secure forward output plugin should reload TLS certificate on connection failure

### ISSUE THREAD

**Issue by xjtian** [fluent/fluent-bit#1678]
## Bug Report

**Describe the bug**

When secure forward is enabled, fluent-bit caches the TLS client certificate for the connection and won't reload it if connection fails due to certificate expiration:

**To Reproduce**

1. Set up fluentd with secure input forwarding and mutual TLS authentication
2. Set up fluent-bit with secure output forwarding and use a client certificate which will expire quickly (e.g. 2 minutes in the future)
3. fluent-bit will successfully forward logs to fluentd until the client certificate expires, at which point you will see these logs:

```
td-agent-bit[25664]: [2019/10/22 20:49:12] [error] [out_fw] no upstream connections available
td-agent-bit[25664]: [2019/10/22 20:49:13] [error] [io_tls] flb_io_tls.c:355 SSL - A fatal alert message was received from our peer
```

4. Replace the expired cert with a valid one in-place; forwarding will continue to fail until fluent-bit is restarted

**Expected behavior**

fluent-bit reloads the TLS client certificate on connection failure to pick up a rotated certificate.

**Your Environment**

* Version used: fluent-bit 1.3.2
* Configuration:

**fluent-bit**:

```
# I use /etc/hosts to point fluentd.fluent.test to my host localhost
[OUTPUT]
    Name          forward
    Match         *
    Host          fluentd.fluent.test
    Port          24224

    tls on
    tls.verify off
    tls.debug 3
    tls.ca_file /path/to/rootCA.pem
    tls.crt_file /path/to/client.pem
    tls.key_file /path/to/client.key
```

**fluentd**:

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0

  <transport tls>
    cert_path /path/to/cert.pem
    private_key_path /path/to/cert.key

    client_cert_auth true
    ca_path /path/to/ca.pem
  </transport>
</source>
```

* Environment: fluent-bit in Virtualbox VM talking to fluentd in docker-compose
* Server type and version: fluentd 1.7 docker container
* Operating System and version: Debian 4.9.0-8 virtualized on MacOS
* Filters and plugins: secure forward

**Additional context**

I'm using fluent-bit to forward logs from basically an edge IoT device. We issue short-lived client certificates to these devices, which periodically re-negotiate with our server to fetch renewed certificates. At the moment I'm wrapping the fluent-bit service on my VM with a task that watches the client certs on the filesystem and restarts fluent-bit when a change is detected, but ideally fluent-bit would reload renewed certificates by itself on connection failure.

To generate some certs:

```
# SSL certs

openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 365000 \
        -out rootCA.pem -subj "/C=US/CN=rootca.fluent.test"
openssl req -new -key controller.key -out cert.csr \
        -subj "/C=US/CN=*.fluent.test"
openssl x509 -req -in cert.csr -CA rootCA.pem -CAkey rootCA.key \
        -CAcreateserial -out cert.pem -days 36400 -sha256

# CA cert

openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -sha256 -days 365000 \
        -out ca.pem -subj "/C=US/CN=certifier.fluent.test"

# Client cert

openssl genrsa -out client.key 2048
openssl req -new -key client.key -out client.csr -subj "/C=US/CN=client1"

# Replace startdate and enddate as necessary - format YYYYMMDDHHMMSSZ or YYMMDDHHMMSSZ
openssl x509 -req -in client.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out client.pem -startdate 20191022120000Z -enddate 20191022120500Z -sha256
```

**Comment by gecube** [comment]
I'm investigating the https://github.com/banzaicloud/logging-operator and it looks like that it does not correctly handle reissuing of fluent-bit certificate.
I wonder whether fluent-bit supports dynamical reload of certificates. Or probably it is good idea to make a special signal handler which will allow hot-reload of configuration and/or fluent-bit.

**Comment by UXabre** [comment]
Hi, as far as I can tell from quickly glancing at the code, it doesn't support a dynamic reload of the certificate.
A signal handler could do the trick; but I also think the OP's suggestion could work; at least as a last fallback in case everything goes haywire.
Another idea could be to request the expire date  of the certificate and only reload once it's almost expired... but there might be a whole pandora's box filled with dragons...
Finally, simply using the inotify handlers for filesystem changes... if something changes trigger either an entire reload / reload the TLS files. I'm not sure what _reloading the config_ implies...what happens with data in the queue for instance?

**Comment by aslafy-z** [comment]
@xjtian can you please reopen this issue? Thank you

**Comment by leonardo-albertovich** [comment]
This is a very old issue, if you are having a similar issue with one of the current versions please file a new issue so we can properly analyze it.


Thank you.

**Comment by aslafy-z** [comment]
I believe this is not a bug but a still to be implemented feature. I can see the same behavior with 1.9.x

**Comment by leonardo-albertovich** [comment]
Could you please reproduce this on 2.0 or master and if that's still the case open an improvement request explaining both the current and desired behaviors with examples? 

There have been substantial changes in the TLS layer in 2.0 so it's important to know if this is still relevant or not and doing that is the best you can do in order to expedite the process.

**Comment by wI2L** [comment]
Using `syslog` output plugin with Fluent Bit v4.0.2, with `tls.ca_file` defined, I also see that the certificate is not hot reloaded when the `/api/v2/reload` is called by [configmap-reload](https://github.com/jimmidyson/configmap-reload) container.
