### ISSUE TITLE
Support wildcard paths in configuration file on Windows

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1692]
**Is your feature request related to a problem? Please describe.**

Right now, Fluent Bit has a limited support for wildcard paths on Windows.
So, for instance, it is not possible to read multiple conf files using `@include *.conf`.

Some users requested this feature, so it is desirable to implement it.

**Describe the solution you'd like**

Sadly Windows does not provide a native support for glob. The best we can do
seems to use FindFirstFile() in kernel32 to imitate `glob(3)`.

**Describe alternatives you've considered**

Use exact file names in place of wildcard characters.

**Additional context**

See https://github.com/fluent/fluent-bit/issues/960#issuecomment-524706501 and https://github.com/fluent/fluent-bit/issues/960#issuecomment-546926651.

**Comment by fujimotos** [comment]
For what it's worth, I am right now working on this issue.
I think I can post a patch in a few days.

**Comment by fujimotos** [comment]
I posted a patch that fixes this issue at monkey/monkey/pull/305.

**Comment by pianohacker** [comment]
@fujimotos Would a port of your patch to fluent bit be possible? This is a bit of a blocker for our usage of Fluent Bit on Windows, and we'd be very appreciative.

**Comment by edsiper** [comment]
Thanks @fujimotos and @pianohacker 

1. https://github.com/monkey/monkey/pull/305 merged on monkey/monkey
2. monkey changes synced on fluent/fluent-bit master (04bfeffa)

If anyone needs this for a possible v1.3.6 during the holiday season, please open a new github issue for that.

**Comment by fujimotos** [comment]
@edsiper Thank you!
