### ISSUE TITLE
Add support for runing Fluent Bit as WIndows service

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1693]
**Is your feature request related to a problem? Please describe.**

Windows has a mechanism called "Service" that is equivalent of daemon in Unix.

We need to implement the Service Manager Control protocol to run Fluent Bit as
a long running process on Windows servers. This also should add ability to manage
Fluent Bit though the `sc` command.

**Describe the solution you'd like**

Implement the the following interfaces:

1. Register Fluent Bit to Service Manager
2. Run Fluent Bit as a Windows Service Program.
3. Unregister Fluent Bit from Service Manager

**Describe alternatives you've considered**

Use Fluentd (it has Windows Service support since v0.12.5)

**Additional context**

**Comment by xPB12** [comment]
Any updates on when we can expect this to be implemented for fluent bit?
Whats the best way to run the process in background?

**Comment by fujimotos** [comment]
No, we do not have the native support yet. You'll have to use a wrapper
program (like winsw) to run Fluent Bit as a service on Windows as of v1.3.

**Comment by bragi92** [comment]
Adding on to this. We would also love to use the native fluent-bit for windows as a service instead of adding on a wrapper on top of it.

Thanks for all the hard work you're doing on making fluent-bit production ready on windows @fujimotos

**Comment by bragi92** [comment]
@xPB12 I was able to use the a command similar to the following in powershell to run fluent-bit as a background process:

`Start-Job -ScriptBlock { Start-Process -NoNewWindow -FilePath "{Full-Path}\fluent-bit.exe" -ArgumentList @("-NoNewWindow", "-c", "{Full-Path}\fluent-bit.conf") }`

Hope this helps :)

**Comment by heyaWorld** [comment]
@fujimotos Hey, I just wanted to follow up and see, if there are any plans to add service capability to fluent-bit for Windows in the near future?

**Comment by plinkable** [comment]
This is an essential feature for us, and is stopping us from deploying.

**Comment by fujimotos** [comment]
@plinkable @heyaWorld JFYI this task is in my queue for the next
major version release (v1.5).
