### ISSUE TITLE
Add support for filesystem storage on Windows

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1694]
**Task Summary**

Implement file-chunk storage support using Win32 API.

The goal is to make the following configuration "just work" on Windows platforms.

```ini
[SERVICE]
    flush                     1
    log_Level                 info
    storage.path              C:\FluentBit\Storage\
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M
```

**Memo**

* chunkio currently falls back to dummy implementation on Windows.
  - https://github.com/edsiper/chunkio/blob/master/CMakeLists.txt#L32
* Need to implement interfaces in `chunkio/cio_file.h` using Win32 API.
  - https://github.com/edsiper/chunkio/blob/master/src/cio_file.c

The biggest blockage is the lack of `mmap()` on Windows.
We need to find some way to share file data among multiple processes.

**Comment by fujimotos** [comment]
For those who interested in this feature: I started to tinker with
the code to implement this feature today.

**Comment by zlymeda** [comment]
any updates on this, pls?

**Comment by fujimotos** [comment]
This task is being tracked by #2738. Hopefully we can make it
into the next v1.7.0 release...

**Comment by fujimotos** [comment]
Update: The support PR is submitted to #2810 (and edsiper/chunkio/pull/59).

**Comment by qingling128** [comment]
Any plan for a release that will include this change?

**Comment by fujimotos** [comment]
@qingling128 All the related patches are already in master.

I expect it to be included in the next v1.7.0 release (due February).

**Comment by qingling128** [comment]
I see. I guess because it's a new feature, it will not be backported to `1.6.*`, right?

**Comment by fujimotos** [comment]
> I see. I guess because it's a new feature, it will not be backported to 1.6.*, right?

@qingling128 Right. Since edsiper/chunkio/pull/59 contains 1000+ LoC changes,
I don't expect it to be backported.

FWIW, this is the milestone page for the next v1.7 release:
https://github.com/fluent/fluent-bit/milestone/10

**Comment by qingling128** [comment]
Thanks for the info. That's very helpful!

**Comment by sophieyfang** [comment]
Can it be sooner than that? our launch is around 1/27/2020. February would be too late.. As reliability is always the concern, buffering in the file system is  quite important for us.
