### ISSUE TITLE
in_netif output Invalid argument

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-bit#1695]
I test fluent-bit verion 1.3.2 like this:
fluent-bit -i netif -p interface=eth0 -o stdout

But it output network error and can't print network interface information
[root@ecs-2019625112055 ~]# fluent-bit -i netif -p interface=eth0 -o stdout
Fluent Bit v1.3.2
Copyright (C) Treasure Data

[2019/10/30 16:03:20] [ info] [storage] initializing...
[2019/10/30 16:03:20] [ info] [storage] in-memory
[2019/10/30 16:03:20] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/10/30 16:03:20] [ info] [engine] started (pid=12215)
[2019/10/30 16:03:20] [error] [plugins/in_netif/in_netif.c:76 errno=22] Invalid argument
[2019/10/30 16:03:20] [ info] [sp] stream processor started
[0] netif.0: [1572422602.000165789, {}]
[1] netif.0: [1572422603.000158765, {}]

my host system is CentOS Linux release 7.1.1503 and network interface is like this:
[root@ecs-2019625112055 ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:f2:8d:94 brd ff:ff:ff:ff:ff:ff
    inet 172.31.0.15/20 brd 172.31.15.255 scope global dynamic eth0
       valid_lft 64258sec preferred_lft 64258sec
    inet6 fe80::f816:3eff:fef2:8d94/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by nokute78** [comment]
@like-inspur Thank you for reporting.

This is similar to #1680 
The patch which is not merged yet is #1681 

Can you check them?

**Comment by like-inspur** [comment]
It works, thank you!

**Comment by nokute78** [comment]
@like-inspur Thank you for testing !
So I close this issue.
