### ISSUE TITLE
Input plugin 'systemd' cannot be loaded

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-bit#1696]
I build flunt-bit with self build, when I use fluent-bit to test systemd input, it outputs error
But when I build with cmake ../ -DFLB_IN_SYSTEMD=On, make, make install, the new fluent-bit still can't solve systemd input

**Comment by edsiper** [comment]
You have to install systemd headers (dev) package before running cmake

**Comment by like-inspur** [comment]
I have install libsystemd0 on Ubuntu or systemd on Centos referencing https://github.com/fluent-plugin-systemd/fluent-plugin-systemd, and then cmake but it doesn't work. Any other package do I need to install?

**Comment by like-inspur** [comment]
And what arguments need to be added to cmake, so enable FLB_IN_SYSTEMD to be included

**Comment by nokute78** [comment]
@like-inspur What we need is `systemd-devel.x86_64` if you try to build on CentOS.
dev/devel packages contain header files.

**Comment by like-inspur** [comment]
I use cmake on 1.3.2 version source code to build fluent-bit on ubuntu 16.04  system
root@log01:~# uname -a 
Linux log01 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by like-inspur** [comment]
Test on centos 7.7 cmake output many erros referencing #1700
