### ISSUE TITLE
thermal device file not found

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-bit#1698]
I run fluent-bit -i thermal -t my_thermal -o stdout -m '*' on a Linux physical server, but it outputs error:
[2019/10/31 14:54:55] [ info] [storage] initializing...
[2019/10/31 14:54:55] [ info] [storage] in-memory
[2019/10/31 14:54:55] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2019/10/31 14:54:55] [ info] [engine] started (pid=2464610)
[2019/10/31 14:54:55] [ warn] [in_thermal] thermal device file not found
[2019/10/31 14:54:55] [ info] [sp] stream processor started

[root@master1 ~]# lshw -class system
master1                     
    description: Rack Mount Chassis
    product: SA5212M4 (Default string)
    vendor: Inspur
    version: 01
    serial: 217413148
    width: 64 bits
    capabilities: smbios-3.0.0 dmi-3.0.0 smp vsyscall32
    configuration: boot=normal chassis=rackmount family=Default string sku=Default string uuid=B0D2F68A-ADB9-E711-84A9-6D6C2201FC01
  *-pnp00:00
       product: PnP device PNP0b00
       physical id: 95
       capabilities: pnp
       configuration: driver=rtc_cmos
  *-pnp00:01
       product: PnP device PNP0c02
       physical id: 96
       capabilities: pnp
       configuration: driver=system
  *-pnp00:02
       product: PnP device PNP0c02
       physical id: 97
       capabilities: pnp
       configuration: driver=system

**Comment by nigels-com** [comment]
Out of interest, what is the Linux kernel version?  `$ uname -a`

Is lmsensors installed? `$ sensors`

**Comment by like-inspur** [comment]
[root@master1 ~]# uname -a
Linux master1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@master1 ~]# sensors
i350bb-pci-0100
Adapter: PCI adapter
loc1:         +56.0°C  (high = +120.0°C, crit = +110.0°C)

i350bb-pci-0700
Adapter: PCI adapter
loc1:         +55.0°C  (high = +120.0°C, crit = +110.0°C)

power_meter-acpi-0
Adapter: ACPI interface
power1:      241.00 W  (interval =   1.00 s)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +41.0°C  (high = +80.0°C, crit = +90.0°C)
Core 0:         +34.0°C  (high = +80.0°C, crit = +90.0°C)
Core 1:         +36.0°C  (high = +80.0°C, crit = +90.0°C)
Core 2:         +36.0°C  (high = +80.0°C, crit = +90.0°C)
Core 3:         +34.0°C  (high = +80.0°C, crit = +90.0°C)
Core 4:         +35.0°C  (high = +80.0°C, crit = +90.0°C)
Core 8:         +35.0°C  (high = +80.0°C, crit = +90.0°C)
Core 9:         +36.0°C  (high = +80.0°C, crit = +90.0°C)
Core 10:        +35.0°C  (high = +80.0°C, crit = +90.0°C)
Core 11:        +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 12:        +34.0°C  (high = +80.0°C, crit = +90.0°C)

coretemp-isa-0001
Adapter: ISA adapter
Physical id 1:  +41.0°C  (high = +80.0°C, crit = +90.0°C)
Core 0:         +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 1:         +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 2:         +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 3:         +34.0°C  (high = +80.0°C, crit = +90.0°C)
Core 4:         +34.0°C  (high = +80.0°C, crit = +90.0°C)
Core 8:         +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 9:         +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 10:        +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 11:        +33.0°C  (high = +80.0°C, crit = +90.0°C)
Core 12:        +32.0°C  (high = +80.0°C, crit = +90.0°C)

**Comment by nigels-com** [comment]
I'm not sure which version of the Linux kernel introduced support for thermal zones.

To be honest I don't have a clear sense of how many bare-metal RHEL 7 systems are out there in the real world, it went out of full support by RedHat in August 2019.

https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates

**Comment by edsiper** [comment]
@like-inspur would you please dig into your filesystem (/proc and /sys) and see if you have any thermal information? maybe older Kernels expose the info in a different directory  ?

**Comment by like-inspur** [comment]
yes, I check that there are no any thermal on centos host, kernel version is 3.10.0-693
And there are some thremal information on ubuntu host, kernel version is 4.4.131-20190505
root@master1:/sys# find -type f -name *thermal*
./devices/platform/smb/smb:motherboard/80040000000.peu0-c0/pci0000:00/0000:00:02.0/0000:03:00.0/0000:04:16.0/0000:12:00.0/host25/scsi_host/host25/thermal_temp
./devices/platform/smb/smb:motherboard/80040000000.peu0-c0/pci0000:00/0000:00:02.0/0000:03:00.0/0000:04:16.0/0000:12:00.1/host26/scsi_host/host26/thermal_temp

**Comment by nigels-com** [comment]
The plugin is looking for these: (Ubuntu 18.04 4.15.0-66-generic)

```
$ find /sys/class/thermal/ -name "thermal_*"
/sys/class/thermal/thermal_zone2
/sys/class/thermal/thermal_zone0
/sys/class/thermal/thermal_zone1
```
