### ISSUE TITLE
out_http plugin occasionally fails to send data when used along with out_influxdb

### ISSUE THREAD

**Issue by dmamalis** [fluent/fluent-bit#1699]
## Bug Report
I am currently running fluent-bit with a configuration which sends metrics to a remote influxdb instance (out_influx) and logs to a remote logstash server (out_http plugin). Both output routes are defined to work with Auth and TTL/SSL. Sometimes the out_http plugin reports an error
```
[2019/10/31 21:36:56] [error] [io_tls] flb_io_tls.c:355 SSL - The connection indicated an EOF
[2019/10/31 21:36:56] [error] [out_http] no upstream connections available to host:port
```
After the error appears, `out_http` retries to send the data. Sometimes, the retry succeeds.
The problem persisted even when Auth was not used.

However, with a bit more testing I figured out that this only happens when both `out_influx` and `out_http` are active. Running `out_http` alone works flawlessly. This sows that there is no real connection issue neither due to server nor due to some erroneous configuration on either fluent-bit, influxdb or logstash.

Overall, it looks like there is some messing up when the `out_http` tries to set the connection. We even tried to change the order of the output plugins in the fluent-bit configuration (first output to logstash and then to influx) but with no success.

**To Reproduce**
Build a config with both `http` and `influxdb` plugins with TTL/SSL settings

**Your Environment**

* Version used: `v1.4.0`, `v1.3.2`
* Configuration:
```
[OUTPUT]
    Name http
    Match *_logs
    Host logstash.host
    Port 11112
    Format json
    HTTP_User user
    HTTP_Passwd password
    tls On
    tls.verify Off
    tls.debug 1
    tls.crt_file logstash-selfsigned.crt
    tls.key_file logstash-selfsigned.key

[OUTPUT]
    Name influxdb
    Match *_metrics
    Host influx
    Port 1111
    HTTP_User user
    HTTP_Passwd password
    Database database
    Sequence_Tag off
    Auto_Tags On
    tls On
    tls.verify Off
    tls.debug 1
    tls.crt_file influxdb-selfsigned.crt
    tls.key_file influxdb-selfsigned.key
```
* Operating System and version:
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
```
* Filters and plugins: `cpu`, `mem`, `netif`, `systemd`, `tecord_modifier`, `grep`, `stdout`, `http`, `infulxdb`

**Comment by edsiper** [comment]
@dmamalis 

thanks for sharing the info.

Looking at the error message, our TLS library is saying that the remote end-point accepted and then closed the connection for some reason ```The connection indicated an EOF```. Would you please take a look at the remote service or balancer logs ?

**Comment by dmamalis** [comment]
@edsiper 
The remote service (logstash) only logs something when the data is accepted. 
To assist more, I tested the same scenario on an Ubuntu 18.04 host and built-from-source fluent-bit v1.4.0. On the Ubuntu Host I used almost the same plugins (I just used `dummy` instead of `systemd`, shouldn't make a difference). It seems to work without issues.

If you have any suggestions on providing more info for you, please let me know.

**Comment by dmamalis** [comment]
@edsiper any updates on this? Has anyone managed to replicate it?

**Comment by sysword** [comment]
Any updates ? I have samilar problem using es_output with auth and tls, fluent-bit reports:
'''
[io_tls] flb_io_tls.c:355 SSL - The connection indicated an EOF
'''
and es reports 
'''
{"log":"{\"type\": \"server\", \"timestamp\": \"2019-12-01T12:34:13,056Z\", \"level\": \"WARN\", \"component\": \"o.e.x.s.t.n.SecurityNetty4HttpServerTransport\", \"cluster.name\": \"cluster\", \"node.name\": \"es-node-0\", \"message\": \"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/, remoteAddress=/}\", \"cluster.uuid\": \"VdVPa0WKRs-yR7APIoH18g\", \"node.id\": \"AcBAuI57St2oW7RS4xqXww\"  }\n","stream":"stdout","time":"2019-12-01T12:34:13.057440042Z"}
'''
have some hints on this?

**Comment by jsarkar** [comment]
I have a similar issue while sending log using 2 different output plugin (http and custom kinesis plugin).
The fluent bit works great if I use single output plugin (either http or custom Kinesis plugin)
Below are the logs with TLS
```[2020/05/04 14:46:15] [ warn] [engine] failed to flush chunk '1-1588603391.494078688.flb', retry in 9 seconds: task_id=2, input=tail.0 > output=kinesis.1
[2020/05/04 14:46:15] [error] [io_tls] flb_io_tls.c:364 SSL - The connection indicated an EOF
[2020/05/04 14:46:15] [error] [output:http:http.0] no upstream connections available to host.domain.com:443
```
and with out TLS:
```

[2020/05/04 15:20:59] [error] [output:http:http.0] could not flush records to host.domain.com:80 (http_do=-1)
[2020/05/04 15:20:59] [error] [output:http:http.0] could not flush records to host.domain.com:80 (http_do=-1)
```
@edsiper any help on this is greatly appreciated.
