### ISSUE TITLE
cmake error on centos 7.7

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-bit#1700]
I want to use cmake on 1.3.2 version source code on centos 7.7 sytsem, even if I have use yum to install gcc gcc-c++ cmake flex bison, but it still output many errors
[root@ecs-2019625112055 ~]# yum install gcc gcc-c++ cmake flex bison
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.huaweicloud.com
Package gcc-4.8.5-39.el7.x86_64 already installed and latest version
Package gcc-c++-4.8.5-39.el7.x86_64 already installed and latest version
Package cmake-2.8.12.2-2.el7.x86_64 already installed and latest version
Package flex-2.5.37-6.el7.x86_64 already installed and latest version
Package bison-3.0.4-2.el7.x86_64 already installed and latest version

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec719384703/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec719384703.dir/build.make CMakeFiles/cmTryCompileExec719384703.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec719384703.dir/CheckSymbolExists.c.o
/usr/bin/cc   -Wall -D__FILENAME__='"build/CMakeFiles/CMakeTmp/CheckSymbolExists.c"'  -fPIE   -o CMakeFiles/cmTryCompileExec719384703.dir/CheckSymbolExists.c.o   -c /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec719384703
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec719384703.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -D__FILENAME__='"$(subst /root/fluent-bit-1.3.2/,,$(abspath $<))"'     CMakeFiles/cmTryCompileExec719384703.dir/CheckSymbolExists.c.o  -o cmTryCompileExec719384703 -rdynamic
CMakeFiles/cmTryCompileExec719384703.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec719384703] Error 1
gmake: *** [cmTryCompileExec719384703/fast] Error 2

File /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec2857997077/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec2857997077.dir/build.make CMakeFiles/cmTryCompileExec2857997077.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2857997077.dir/CheckFunctionExists.c.o
/usr/bin/cc   -Wall -D__FILENAME__='"/usr/share/cmake/Modules/CheckFunctionExists.c"' -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE   -o CMakeFiles/cmTryCompileExec2857997077.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec2857997077
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2857997077.dir/link.txt --verbose=1
/usr/bin/cc   -Wall -D__FILENAME__='"$(subst /root/fluent-bit-1.3.2/,,$(abspath $<))"' -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec2857997077.dir/CheckFunctionExists.c.o  -o cmTryCompileExec2857997077 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec2857997077] Error 1
gmake: *** [cmTryCompileExec2857997077/fast] Error 2

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec2884632673/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec2884632673.dir/build.make CMakeFiles/cmTryCompileExec2884632673.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec2884632673.dir/src.cxx.o
/usr/bin/c++    -DMSGPACK_DEFAULT_API_VERSION=3 -std=c++98  -DMSGPACK_ENABLE_GCC_CXX_ATOMIC -fPIE   -o CMakeFiles/cmTryCompileExec2884632673.dir/src.cxx.o -c /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.cxx
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.cxx:2:28: fatal error: bits/atomicity.h: No such file or directory
 #include <bits/atomicity.h>
                            ^
compilation terminated.
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec2884632673.dir/src.cxx.o] Error 1
gmake: *** [cmTryCompileExec2884632673/fast] Error 2

Source file was:

#include <bits/atomicity.h>
int atomic_sub(int i) { return __gnu_cxx::__exchange_and_add(&i, -1) - 1; }
int atomic_add(int i) { return __gnu_cxx::__exchange_and_add(&i, 1) + 1; }
int main(int argc, char * argv[])
{
    atomic_sub(1);
    atomic_add(1);
}

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec1947521747/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1947521747.dir/build.make CMakeFiles/cmTryCompileExec1947521747.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1947521747.dir/src.c.o
/usr/bin/cc   -Wall -D__FILENAME__='"build/CMakeFiles/CMakeTmp/src.c"' -DHAVE_KQUEUE -fPIE   -o CMakeFiles/cmTryCompileExec1947521747.dir/src.c.o   -c /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.c
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.c:2:25: fatal error: sys/event.h: No such file or directory
   #include <sys/event.h>
                         ^
compilation terminated.
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec1947521747.dir/src.c.o] Error 1
gmake: *** [cmTryCompileExec1947521747/fast] Error 2

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec2689590983/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec2689590983.dir/build.make CMakeFiles/cmTryCompileExec2689590983.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2689590983.dir/src.c.o
/usr/bin/cc   -Wall -D__FILENAME__='"build/CMakeFiles/CMakeTmp/src.c"' -DFLB_HAVE_VALGRIND -fPIE   -o CMakeFiles/cmTryCompileExec2689590983.dir/src.c.o   -c /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.c
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.c:2:33: fatal error: valgrind/valgrind.h: No such file or directory
   #include <valgrind/valgrind.h>
                                 ^
compilation terminated.
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec2689590983.dir/src.c.o] Error 1
gmake: *** [cmTryCompileExec2689590983/fast] Error 2

Source file was:

  #include <valgrind/valgrind.h>
  int main() {
     return 0;
  }

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec338107672/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec338107672.dir/build.make CMakeFiles/cmTryCompileExec338107672.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec338107672.dir/src.c.o
/usr/bin/cc   -Wall -D__FILENAME__='"build/CMakeFiles/CMakeTmp/src.c"' -DFLB_HAVE_CLOCK_GET_TIME -fPIE   -o CMakeFiles/cmTryCompileExec338107672.dir/src.c.o   -c /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.c
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/src.c:2:26: fatal error: mach/clock.h: No such file or directory
   #include <mach/clock.h>
                          ^
compilation terminated.
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec338107672.dir/src.c.o] Error 1
gmake: *** [cmTryCompileExec338107672/fast] Error 2

Source file was:

  #include <mach/clock.h>
  #include <mach/mach.h>
  int main() {
      clock_serv_t cclock;
      mach_timespec_t mts;
      host_get_clock_service(mach_host_self(), CALENDAR_CLOCK, &cclock);
      clock_get_time(cclock, &mts);
      return mach_port_deallocate(mach_task_self(), cclock);
  }

**Comment by like-inspur** [comment]
Run Build Command:/usr/bin/gmake "cmTryCompileExec1734847822/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1734847822.dir/build.make CMakeFiles/cmTryCompileExec1734847822.dir/build
gmake[1]: Entering directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1734847822.dir/CheckSymbolExists.c.o
/usr/bin/cc   -Wall -D__FILENAME__='"build/CMakeFiles/CMakeTmp/CheckSymbolExists.c"'  -fPIE   -o CMakeFiles/cmTryCompileExec1734847822.dir/CheckSymbolExists.c.o   -c /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘accept4’ undeclared (first use in this function)
   return ((int*)(&accept4))[argc];
                   ^
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:13:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
gmake[1]: Leaving directory `/root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec1734847822.dir/CheckSymbolExists.c.o] Error 1
gmake: *** [cmTryCompileExec1734847822/fast] Error 2

File /root/fluent-bit-1.3.2/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <sys/socket.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef accept4
  return ((int*)(&accept4))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by nokute78** [comment]
@like-inspur cmake3 is needed to build on CentOS7.

This is a duplicated issue #1345

**Comment by like-inspur** [comment]
cmake3 ../ -DFLB_JEMALLOC=On -DFLB_HTTP_SERVER=On -DFLB_STREAM_PROCESSOR=Off -DFLB_IN_SYSTEMD=On
[root@icp-102 build]# make
[  1%] Built target jemalloc
[  3%] Built target backtrace
[  3%] Built target jsmn
[  4%] Built target sqlite3
[  5%] Built target xxd-c
[  7%] Built target onigmo
[  7%] Built target flb-plugin-proxy-go
[  9%] Built target luajit
[ 10%] Built target msgpackc-static
[ 11%] Built target mpack-static
[ 11%] Built target miniz
[ 12%] Built target cio-crc32
[ 14%] Built target chunkio-static
[ 14%] Built target rbtree
[ 14%] Built target co
[ 17%] Built target mk_core
[ 18%] Built target monkey-liana-static
[ 22%] Built target monkey-core-static
[ 35%] Built target mbedcrypto
[ 37%] Built target mbedx509
[ 39%] Built target mbedtls
[ 40%] Built target flb-ra-parser
[ 40%] Built target api-v1
[ 41%] Built target flb-http-server
[ 42%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_time.c.o
/root/fluent-bit-1.3.2/src/flb_time.c: In function ‘_flb_time_get’:
/root/fluent-bit-1.3.2/src/flb_time.c:54:5: warning: implicit declaration of function ‘timespec_get’ [-Wimplicit-function-declaration]
     return timespec_get(&tm->tm, TIME_UTC);
     ^
/root/fluent-bit-1.3.2/src/flb_time.c:54:34: error: ‘TIME_UTC’ undeclared (first use in this function)
     return timespec_get(&tm->tm, TIME_UTC);
                                  ^
/root/fluent-bit-1.3.2/src/flb_time.c:54:34: note: each undeclared identifier is reported only once for each function it appears in
/root/fluent-bit-1.3.2/src/flb_time.c:66:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [src/CMakeFiles/fluent-bit-static.dir/flb_time.c.o] Error 1
make[1]: *** [src/CMakeFiles/fluent-bit-static.dir/all] Error 2
make: *** [all] Error 2

**Comment by edsiper** [comment]
you can use as a reference how do we prepare our build environment for Centos 7 with Docker, take a look at the Yum commands, that might help:

https://github.com/fluent/fluent-bit-packaging/blob/master/distros/centos/7/Dockerfile.base#L4

note: always remove all content from your build/ directory to have a clean build

**Comment by like-inspur** [comment]
ok, now cmake3 works fine, thank you
