### ISSUE TITLE
out_kafka: implement message acknowledgement feature 

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#1701]
**Is your feature request related to a problem? Please describe.**

Kafka provides a feature called "Produce acknowledge" that ensures the
receipt of messages by (one of or all) brokers.

Currently we do not support that feature in `out_kafka`, so it is possible that
some messages gets lost in transmission.

**Describe the solution you'd like**

Add `require_ack` option that wait acknowledgement responses from kafka.

**Describe alternatives you've considered**

**Additional context**

* librdkafka has support for message acknowledgement.

**Comment by palmerabollo** [comment]
I can confirm this is failing and messages can be lost. Is there any plan to fix this?

**Comment by palmerabollo** [comment]
I'd reopen this issue, messages can still be lost.
