### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by bobykus31** [fluent/fluent-bit#1706]
## Bug Report
We run  td-agent-bit on Ubuntu 

uname -a
Linux base1 4.15.0-64-generic #73~16.04.1-Ubuntu SMP Fri Sep 13 09:56:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 curl -s http://127.0.0.1:2020/ 
{"fluent-bit":{"version":"1.3.2","edition":"Community","flags":["FLB_HAVE_PARSER","FLB_HAVE_RECORD_ACCESSOR","FLB_HAVE_STREAM_PROCESSOR","FLB_HAVE_TLS","FLB_HAVE_SQLDB","FLB_HAVE_TRACE","FLB_HAVE_METRICS","FLB_HAVE_HTTP_SERVER","FLB_HAVE_SYSTEMD","FLB_HAVE_VALGRIND","FLB_HAVE_FORK","FLB_HAVE_GMTOFF","FLB_HAVE_UNIX_SOCKET","FLB_IS_TD_AGENT","FLB_HAVE_PROXY_GO","FLB_HAVE_SYSTEM_STRPTIME","FLB_HAVE_JEMALLOC","FLB_HAVE_LIBBACKTRACE","FLB_HAVE_REGEX","FLB_HAVE_LUAJIT","FLB_HAVE_C_TLS","FLB_HAVE_ACCEPT4","FLB_HAVE_INOTIFY"]}}

cat /etc/td-agent-bit/td-agent-bit.conf
[SERVICE]
    Flush               3
    Daemon              off
    Log_Level           info
    HTTP_Server         On
    HTTP_PORT           2020

[INPUT]
    Name                systemd
    Max_Entries         5000
    DB                  /var/log/systemd.db
    Mem_Buf_Limit       1MB
    Tag                 journal.0

[OUTPUT]
    Name                forward
    Match               *
    Host                fluentd.host
    Port                24888

[FILTER]
    Name                record_modifier
    Match               *
    Record              host fluentbit.host

Currently td-agent-bit.service use 1.8G which is really insane. 

systemctl  status td-agent-bit.service
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/lib/systemd/system/td-agent-bit.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-10-29 09:16:26 UTC; 6 days ago
 Main PID: 3224 (td-agent-bit)
    Tasks: 5
   Memory: 1.8G
      CPU: 27min 53.527s

Most is anon according   by pmap

 pmap 3224 | grep anon
0000000000bf9000   2152K rw---   [ anon ]
00007f17116e5000 327680K rw---   [ anon ]
00007f1726e00000 700416K rw---   [ anon ]
00007f17533ec000 163840K rw---   [ anon ]
00007f1761200000  16384K rw---   [ anon ]

**Comment by edsiper** [comment]
troubleshooting

**Comment by edsiper** [comment]
Possible related to #1798 #1864. Fixed through a1b5344d. 

The patch will be backported to v1.3 series.
