### ISSUE TITLE
Memory leak when defined several filters

### ISSUE THREAD

**Issue by TetianaKuziaieva** [fluent/fluent-bit#1708]
### Bug Report

`fluentbit` gets killed by OOMKilled when several filters with dynamic tags are defined in the configuration file. 

Related issue [#693](https://github.com/fluent/fluent-bit/issues/693) has been closed, but the issue occurs with Fluentbit 1.3.2 only when a bunch of filters are enabled. 

#### Steps to reproduce the problem:

**Expected behavior**
Fluentbit filters contains tags to match the input log file and does filtering based on the defined regex. 

Issue does not occur when only one Filter is defined:
```
    [FILTER]
        Name    grep
        Match   *
        Regex   level ERROR
```

#### Screenshots
Fluentbit container is configured with 500MiB and 1Gi (two namespaces, both are failing with OOMKilled). The metrics:
* the container is configured with 500MiB
![Fluentbit_500Mb](https://user-images.githubusercontent.com/39550969/68196686-3aad9d80-ffb9-11e9-9fc2-76f4651efe1f.PNG)
* the container is configured with 1Gi
![Fluentbit_1Gi](https://user-images.githubusercontent.com/39550969/68196792-60d33d80-ffb9-11e9-85bf-b58791d82741.png)

**Environment**
* Version used: 1.3.2
* Configuration file:
```
apiVersion: v1
data:
  config.flb: |-
    [SERVICE]
        Flush       1
        Daemon      off
        Log_Level   debug
        Parsers_File    /etc/fluent-bit/parsers.conf

    @INCLUDE inputs.conf

    [FILTER]
        Name    grep
        Match   serverlog
        Regex   level ERROR|WARN

    [FILTER]
        Name    grep
        Match   mqlog
        Regex   level ERROR

    [FILTER]
        Name    grep
        Match   actlog
        Regex   level FAIL

    [FILTER]
        Name    grep
        Match   jboss-accesslog
        Regex   message .*HTTP\/.*?. ((4|5)0[0-9]) .*

    [OUTPUT]
        Name    as_prom_endpoint
        Match   *
        HTTP_Port   9145

  inputs.conf: |-
    [INPUT]
        Name    tail
        Tag     serverlog
        Path   /path_to_file/server*.log
        Key log
        Multiline On
        Parser_Firstline server_log_parser
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     mqlog
        Path    /path_to_file/messagingapi*.log
        Multiline On
        Parser_Firstline messaging_log_parser
        Key log
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     actlog
        Path   /path_to_file/act*.log
        Multiline On
        Parser_Firstline  act_log_parser
        Key log
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     jboss-accesslog
        Path    /path_to_file/access*.log
        Key log
        Parser jboss_access_log_parser
        Refresh_Interval 2
  parsers.conf: |-
    [PARSER]
        Name    server_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:,]+)+\s([0-9\/:,]+))\s(?<level>[^ ]*)\s\[(?<class>[a-zA-Z\.]+)]\s(?<message>[^ ][^\n]+(\n(((\t*)?at [^\n]+)|(Caused by: [^\n]+)|((\t*)?\.\.\. [^\n]+)))*)

    [PARSER]
        Name    messaging_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:;,.]+)) LogLevel=\"(?<level>[^ ;]*)\";\[class (?<class>[^ ]*)\](?<message>[^ ][^\n]+(\n(((\t*)?at [^\n]+)|(Caused by: [^\n]+)|((\t*)?\.\.\. [^\n]+)))*)

    [PARSER]
        Name    act_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:;.]+));(?<class>[^ ;]*);(?<level>[^ ;]*);(?<timespent>[\d]*)?;(?<message>[^ ][^\n]+(\n(((\t*)?at [^\n]+)|(Caused by: [^\n]+)|((\t*)?\.\.\. [^\n]+)))*)

    [PARSER]
        Name    jboss_access_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:,]+)+\s([0-9\/:,]+))\s(?<level>[^ ]*)\s+\[(?<class>[a-zA-Z\.]+)]\s(?<message>[^ ].*)
kind: ConfigMap

**Comment by edsiper** [comment]
thanks for reporting this issue. I will troubleshoot and try to replicate it.

Can you share some example log files that can be used to replicate the problem ?

**Comment by fujimotos** [comment]
I spent this morning trying to reproduce the memleak behaviour, without
any success. I made two text files with 30000 records (created by hand
to match the regular expressions in the posted config), and run fluent-bit
as follows.

    $ valgrind --leak-check=yes ./bin/fluent-bit -c issue-1703.conf

"issue-1703.conf" contains @TetianaKuziaieva's configuration (I used stdout
for the output though -- see below). The memory usage was just flat low, and
valgrind detected no leak.

    ==21147== HEAP SUMMARY:
    ==21147==     in use at exit: 0 bytes in 0 blocks
    ==21147==   total heap usage: 1,202,580 allocs, 1,202,580 frees, 3,684,183,388 bytes allocated
    ==21147== 
    ==21147== All heap blocks were freed -- no leaks are possible
    ==21147== 
    ==21147== For counts of detected and suppressed errors, rerun with: -v
    ==21147== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

Here are few questions:

> fluentbit gets killed by OOMKilled when several filters with dynamic tags are defined in the configuration file.

Actually I don't see any "filters with dynamic tags" in your configuration.
In fact, each grep filters have a static Match condition (e.g. `Match serverlog`)

Which part of the config do you mention by "several filters with dynamic tags"?

> Name    as_prom_endpoint

What is this output plugin? I could not find `out_as_prom_endpoint` anywhere.

Also, does the memory bloated behaviour still occur if you replace this plugin
with, say, `out_stdout` ?

**Comment by edsiper** [comment]
could be related to some memory buffer that is not released on runtime but freed properly on exit ?

**Comment by edsiper** [comment]
the test case should try to reproduce the increase of memory on runtime only

**Comment by fujimotos** [comment]
> could be related to some memory buffer that is not released on runtime but freed properly on exit ?

Probably, but memory usage while running was flat low either. I could not
reproduce the memory bloating behavior in any way.

The possibilities I can think of are 1) the output plugin was consuming too
much memory or 2) it was just a natural memory bloat due to `Mem_Buf_Limit`
being not set.

**Comment by fujimotos** [comment]
> the test case should try to reproduce the increase of memory on runtime only

@edsiper  Just for your interest, attached is the graph for the memory consumption.

I appended 30000 records per 5 seconds to two log files, and kept it running
for about an hour. More than 40 million records were processed, but the memory
usage was just low and not creeping.

![issue-1708](https://user-images.githubusercontent.com/8974561/68358454-e989df00-015b-11ea-8d1e-36951b96bfe2.png)

**Comment by TetianaKuziaieva** [comment]
Hello, 

Sorry, I did not have the access to the source code & namespace.

An example of the server.log and act.log:
```
server.log:

07/11/2019 08:56:44,785 WARN  [com...] (default task-110) jsessionId=  Exception thrown while building the Message [  Message [ ERROR AT END OF TRANSACTION TIME ] ]

act.log
07/11/2019;08:32:24.626;LogoutUserAction;FAIL;150011;UserNotAllowed: Message [ User is not logged in ] (150011);null;null;null;null;null;null;192.168.0.125;jsessionId=
```

And just for info, this is metrics from the namespace, that was not used last two day but has 4 restarts of fluentbit :
 
![image](https://user-images.githubusercontent.com/39550969/68375207-b7ba4d80-0146-11ea-803c-a3d5660c5b1c.png)

Indeed, I have no dynamic tags. What I wanted to say it's that the issue happened with several tags defined in the configmap. But it's not true anymore since the last monitoring has been done just with one Filter defined (still with grep plugin)
```
[FILTER]
    Name    grep
    Match   *
    Regex   level ERROR|WARN
```
I use custom output Go-Plugin as_prom_endpoint, that is does parsing of the log, registers metrics and sends them to Prometheus. Will let you know the result while using only stdout plugin

**Comment by TetianaKuziaieva** [comment]
Here is the update:
* Using stdout output plugin, fluentbit container has got restarted and OOMKilled (after 4 hours of running)
```
Container fluent-bit
State:
Running since Nov 7, 2019 2:57:13 PM
Last State
Terminated at Nov 7, 2019 2:57:11 PM with exit code 137 (OOMKilled)
Ready:
true
Restart Count:
1
```

Currently configmap looks like (just one Filter with grep plugin):
````
apiVersion: v1
data:
  config.flb: |
    [SERVICE]
        Flush       1
        Daemon      off
        Log_Level   debug
        Parsers_File    /etc/fluent-bit/parsers.conf

    @INCLUDE inputs.conf

    [FILTER]
        Name    grep
        Match   *
        Regex   level ERROR|WARN

    [OUTPUT]
        Name    stdout
        Match   *
        HTTP_Port   9145
  inputs.conf: |
    [INPUT]
        Name    tail
        Tag     serverlog
        Path  /logs/${ACS_COMPONENT}/${JBOSS_CONTAINER_NAME}/server*.log
        Key log
        Multiline On
        Parser_Firstline server_log_parser
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     mqlog
        Path    /logs/${ACS_COMPONENT}/${JBOSS_CONTAINER_NAME}/app/messagingapi*.log
        Multiline On
        Parser_Firstline messaging_log_parser
        Key log
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     actlog
        Path    /logs/${ACS_COMPONENT}/${JBOSS_CONTAINER_NAME}/app/actusermanagement*.log
        Multiline On
        Parser_Firstline  actusermanagement_log_parser
        Key log
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     jboss-accesslog
        Path    /logs/${ACS_COMPONENT}/${JBOSS_CONTAINER_NAME}/access*.log
        Key log
        Parser jboss_access_log_parser
        Refresh_Interval 2
  parsers.conf: |
    [PARSER]
        Name    server_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:,]+)+\s([0-9\/:,]+))\s(?<level>[^ ]*)\s\[(?<class>[a-zA-Z\.]+)]\s(?<message>[^ ][^\n]+(\n(((\t*)?at [^\n]+)|(Caused by: [^\n]+)|((\t*)?\.\.\. [^\n]+)))*)

    [PARSER]
        Name    messaging_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:;,.]+)) LogLevel=\"(?<level>[^ ;]*)\";\[class (?<class>[^ ]*)\](?<message>[^ ][^\n]+(\n(((\t*)?at [^\n]+)|(Caused by: [^\n]+)|((\t*)?\.\.\. [^\n]+)))*)

    [PARSER]
        Name    actusermanagement_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:;.]+));(?<class>[^ ;]*);(?<level>[^ ;]*);(?<timespent>[\d]*)?;(?<message>[^ ][^\n]+(\n(((\t*)?at [^\n]+)|(Caused by: [^\n]+)|((\t*)?\.\.\. [^\n]+)))*)

    [PARSER]
        Name    jboss_access_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:,]+)+\s([0-9\/:,]+))\s(?<level>[^ ]*)\s+\[(?<class>[a-zA-Z\.]+)]\s(?<message>[^ ].*)
kind: ConfigMap
```

Example of the log in Fluentbit terminal:
```
[2019/11/07 14:28:29] [debug] [task] created task=0x7ff51065afa0 id=0 OK
--
  | [2019/11/07 14:28:29] [debug] [task] destroy task=0x7ff51065afa0 (task_id=0)
  | [0] serverlog: [1573136909.017955872, {"timestamp"=>"07/11/2019 09:15:29,925", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 68) jsessionId=  java.lang.SecurityException: Not supported in log4j-jboss-logmanager"}]
  | [1] serverlog: [1573136909.017974936, {"timestamp"=>"07/11/2019 09:15:29,925", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 68) jsessionId=  	at "}]
  | [2] serverlog: [1573136909.017984079, {"timestamp"=>"07/11/2019 09:15:29,926", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 68) jsessionId=  	at "}]

```

**Comment by fujimotos** [comment]
@TetianaKuziaieva  Thank you. Does things get better if you
add `Mem_Buf_Limit` to each input section?

    [INPUT]
        Name    tail
        Tag     serverlog
        Mem_Buf_Limit 10MB
        ...

Add the option to all of your four input plugins like above and
please see if the memory usage improves.

**Comment by TetianaKuziaieva** [comment]
@fujimotos thank you for the quick. I'm gonna try this and see how the things go

**Comment by TetianaKuziaieva** [comment]
Hello @fujimotos , 
The update on my side:
`Mem_Buf_Limit` for all Inputs does not make things better. Fluentbit container has been restarted 4 times:

![image](https://user-images.githubusercontent.com/39550969/68463840-c9b3f300-020f-11ea-9015-db6015ae6be8.png)

Metrics:
![image](https://user-images.githubusercontent.com/39550969/68463723-92dddd00-020f-11ea-97d2-7e203ce5da6f.png)

**Comment by fujimotos** [comment]
@TetianaKuziaieva  Thank you. Now I'm very curious why this is happening.

I still cannot reproduce this issue locally, even though I use the same configuration
file that you posted in https://github.com/fluent/fluent-bit/issues/1708#issuecomment-551106245.

A few more questions:

* Can you post your fluent-bit log file?
* How many log files do you have in the `/logs/` directory?
  I'm suspecting that it might be related to the number of log files `in_tail` tracks.
* Does the memory bloating behaviour still occur if you use no `filter_grep`?

**Comment by TetianaKuziaieva** [comment]
@fujimotos 
* Currently I have only 1 file for each type of input (server, act etc) in my test namespace. And in fact, only server.log and accees.log are active 
* Here's an example with fluentbit log. I did a sanitary, if you need more information, we can see what can be done 
```
[2019/11/08 11:53:00] [debug] [in_tail] add to scan queue /logs/server.log, offset=0
[2019/11/08 11:53:00] [debug] [in_tail] append new file: /logs/server.log
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=32767 lines=208
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=32676 lines=238
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=32628 lines=228
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=32567 lines=102
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=32544 lines=117
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=32602 lines=107
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/server.log read=27779 lines=0
[2019/11/08 11:53:01] [error] [in_tail] file=/logs/server.log requires a larger buffer size, lines are too long. Skipping file.
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/access.log event
[2019/11/08 11:53:01] [debug] [in_tail] file=/logs/access.log read=185 lines=1
[2019/11/08 11:53:01] [debug] [task] created task= id=0 OK
[2019/11/08 11:53:01] [debug] [task] destroy task= (task_id=0)
[0] serverlog: [1573213981.017042722, {"timestamp"=>"07/11/2019 15:38:54,620", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 67) jsessionId=  "}]
[1] serverlog: [1573213981.017061341, {"timestamp"=>"07/11/2019 15:38:54,621", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 67) jsessionId=  	"}]
[51] serverlog: [1573213981.017408047, {"timestamp"=>"07/11/2019 15:38:54,630", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 67) jsessionId=  "}]
[52] serverlog: [1573213981.017416264, {"timestamp"=>"07/11/2019 15:38:54,740", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 67) jsessionId=  
07/11/2019 15:38:54,789 INFO  [stdout] (reactor ) jsessionId=  2019/11/07 15:38:54.788087 INFO com....
07/11/2019 15:38:54,793 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.792090 INFO com....
07/11/2019 15:38:54,794 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.793417 INFO com....
07/11/2019 15:38:54,796 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.795474 INFO com....
07/11/2019 15:38:54,796 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.795937 INFO com....
```
* Trying with no grep filter

**Comment by fujimotos** [comment]
@TetianaKuziaieva Aha it strikes me that the root cause might be `Multiline` mode.

If the firstline regex has some glitch, it can accumulate a very large number of lines
trying to find the beginning of the next record, and potentially eat up the memory.

In fact, I'm seeing several lines getting concatenated wrongly in your log file:

```
[52] serverlog: [1573213981.017416264, {"timestamp"=>"07/11/2019 15:38:54,740", "level"=>"ERROR", "class"=>"stderr", "message"=>"(ServerService Thread Pool -- 67) jsessionId=  
07/11/2019 15:38:54,789 INFO  [stdout] (reactor ) jsessionId=  2019/11/07 15:38:54.788087 INFO com....
07/11/2019 15:38:54,793 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.792090 INFO com....
07/11/2019 15:38:54,794 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.793417 INFO com....
07/11/2019 15:38:54,796 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.795474 INFO com....
07/11/2019 15:38:54,796 INFO  [stdout] (ServerService Thread Pool -- 67) jsessionId=  2019/11/07 15:38:54.795937 INFO com....
```

If my hypothesis is true, you'll see the memory issue resolved if you set `Multiline` to off on
each tail input plugin.  Can you try this and see if it works?

**Comment by TetianaKuziaieva** [comment]
Since even with no `filter_grep` the container has got OOMKilled, you may be right with the Multiline log. I'm trying to see whether it costs the leak

**Comment by TetianaKuziaieva** [comment]
Hello @fujimotos , 

The last update:
good news, `fluentbit` container is running since 08/11 without restarts. I did a setup of `Multiline` to off and it seems that it was causing the memory leak. Thank you, good spotted.

But in fact, for 3 types of log I still need to use `Multiline On`. Do you have an idea, how it can be done?

**Comment by fujimotos** [comment]
@TetianaKuziaieva Thank you for reporting back. Great to hear that.

> But in fact, for 3 types of log I still need to use Multiline On. Do you have an idea, how it can be done?

What's actually broken here is `Parser_Firstline` which fails to match the
beginning of each data record. It ends up making `in_tail` to accumulate
a very large number of log lines, and hence memory bloating occurs.

So the correct fix is to tweak the regexes in parsers.conf so that they match
log lines properly.

For instance, talking about `server_log_parser`, try the following regex:

```ini
[PARSER]
    Name    server_log_parser
    Format  regex
    Regex   ^(?<timestamp>[0-9\/:,]+\s[0-9\/:,]+)\s+(?<level>[^ ]*)\s+\[(?<class>[^]]*)\]\s+(?<message>.*)
```

... and see if the memory issue still occurs (with `Multiline On`).

**Comment by edsiper** [comment]
thanks @TetianaKuziaieva and @fujimotos for identify the root cause of the problem! , I am taking a look at the code

**Comment by TetianaKuziaieva** [comment]
Thanks @fujimotos and @edsiper for keeping the investigation, since it's already a bit different topic than I defined in the begin.

With the regex above, there's no memory issue. But it does not look as properly working.
As I mentioned, I use a custom Go-pllugin in order to scrape the metrics by Prometheus. 
With the regex 
```
Regex   ^(?<timestamp>[0-9\/:,]+\s[0-9\/:,]+)\s+(?<level>[^ ]*)\s+\[(?<class>[^]]*)\]\s+(?<message>.*)
```
and `Multiline On` the occurrence of the log entry is much higher that it is. For example, the test case contains 1 entry that should be detected, but I see the error more than 30 times. With my custom plugin I was able to see the number. But same can see in the log of the container when I use output plugin `stdout` .

Example of the multi line log entry (with sanity):
'''
13/11/2019 08:36:07,775 ERROR [...] (pool-/lean-1) jsessionId=  Unexpected exception occured in time measured session related task in category Could not get a resource from the pool
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
Caused by: ... No route to host (Host unreachable)
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	at ...
	... 22 more
'''

**Comment by fujimotos** [comment]
> For example, the test case contains 1 entry that should be detected, but I see the error more than 30 times. With my custom plugin I was able to see the number. But same can see in the log of the container when I use output plugin stdout .

@TetianaKuziaieva I'm confused. With that regex, your example log would
be parsed into a single record with a long "message" field (shown below).
Isn't this what you expect?

```
[0] serverlog: [1573701740.694949788, {"timestamp"=>"13/11/2019 08:36:07,775", "level"=>"ERROR", "class"=>"...", "message"=>"(pool-/lean-1) jsessionId=  Unexpected exception occured in time measured session related task in category Could not get a resource from the pool
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
Caused by: ... No route to host (Host unreachable)
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ...
    at ..."}]
```

**Comment by TetianaKuziaieva** [comment]
> With that regex, your example log would
> be parsed into a single record with a long "message" field (shown below)

Indeed, that's what I expect. And I have the log entry correctly parsed. But each entry (with the message above) has been counted many times. I assume that `tail` could process the whole file each and that's why the same entry has been counted multiple times

**Comment by TetianaKuziaieva** [comment]
Hello @fujimotos and @edsiper , 

After while (had another priorities to work on), I am coming back to the memory leak issue with Fluentbit, since it becomes more critical.

Even with better defined parser for multiline log and `Mem_Buf_Limit`, I am getting the OOMKiled container in the namespace that currently is not used.
Here is monitoring of the container, which got OOMKilled after 2 hours :

![image](https://user-images.githubusercontent.com/39550969/71174055-83b56a80-2264-11ea-8043-35b20fa39b6a.png)

Here's the config file: 

`apiVersion: v1
data:
  config.flb: |-
    [SERVICE]
        Flush       1
        Daemon      off
        Log_Level   debug
        Parsers_File    /etc/fluent-bit/parsers.conf

    @INCLUDE inputs.conf

    [FILTER]
        Name    grep
        Match   serverlog
        Regex   level ERROR|WARN

    [FILTER]
        Name    grep
        Match   mqlog
        Regex   level ERROR

    [FILTER]
        Name    grep
        Match   actlog
        Regex   level FAIL

    [FILTER]
        Name    grep
        Match   jboss-accesslog
        Regex   message .*HTTP\/.*?. ((4|5)0[0-9]) .*

    [OUTPUT]
        Name    as_prom_endpoint
        Match   *
        HTTP_Port   9145
  inputs.conf: |-
    [INPUT]
        Name    tail
        Tag     serverlog
        Mem_Buf_Limit 50MB
        Path  /logs/server*.log
        Key log
        Multiline On
        Parser_Firstline server_log_parser
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     mqlog
        Mem_Buf_Limit 50MB
        Path    /logs/app/messagingapi*.log
        Multiline On
        Parser_Firstline messaging_log_parser
        Key log
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     actlog
        Mem_Buf_Limit 50MB
        Path    /logs/app/actusermanagement*.log
        Multiline On
        Parser_Firstline  actusermanagement_log_parser
        Key log
        Refresh_Interval 2

    [INPUT]
        Name    tail
        Tag     jboss-accesslog
        Mem_Buf_Limit 50MB
        Path    /logs/access*.log
        Key log
        Parser jboss_access_log_parser
        Refresh_Interval 2
  parsers.conf: |-
    [PARSER]
        Name    server_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:,]+)+\s([0-9\/:,]+))\s(?<level>[^ ]*)\s\[(?<class>[a-zA-Z\.]+)]\s(?<message>.*)

    [PARSER]
        Name    messaging_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:;,.]+)) LogLevel=\"(?<level>[^ ;]*)\";\[class (?<class>[^ ]*)\](?<message>.*)

    [PARSER]
        Name    actusermanagement_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:;.]+));(?<class>[^ ;]*);(?<level>[^ ;]*);(?<timespent>[\d]*)?;(?<message>.*)

    [PARSER]
        Name    jboss_access_log_parser
        Format  regex
        Regex   ^(?<timestamp>([0-9\/:,]+)+\s([0-9\/:,]+))\s(?<level>[^ ]*)\s+\[(?<class>[a-zA-Z\.]+)]\s(?<message>[^ ].*)
`

Do you have any other idea what can be the root cause?  

Do I need change the issue title to the Memory leak due to `Multiline On` and `Firstline_Parser` ?
