### ISSUE TITLE
filter plugin causes segfault in some cases

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#171]
I tested filter plugin and I found it causes segfault in some cases.

## no options for filter plugin

These commands cause segfault. Because "match" is NULL.
```
$ fluent-bit -i cpu -o stdout -F stdout
```
and
```
$ fluent-bit -i cpu -o stdout -F stdout -m '*'
```
Is option '-m' for only output plugins?  

Grep plugin also causes.
```
$ fluent-bit -i cpu -o stdout -F grep
```

## parse error at set_rules

Illegal property (regex=aaa in this case)causes segfault.
This is a no regular expression error.
```
$ fluent-bit -i cpu -o stdout -F grep -p "match=*" -p "regex=aaa"
```

**Comment by edsiper** [comment]
thanks for reporting the errors, all of them are fixed now.

**Comment by nokute78** [comment]
Thank you for fixing.
It works correctly!
