### ISSUE TITLE
tail plugin throws SIGILL on musl when expanding tildes

### ISSUE THREAD

**Issue by jawi** [fluent/fluent-bit#1721]
## Bug Report

Running the tail plugin on a musl-based system causes it to throw an SIGILL. The bug is caused due to the way tildes are expanded for musl-based systems: it tries to free memory that shouldn't be freed at that moment.

**To Reproduce**
- run `fluent-bit -i tail -p path=/var/log/syslog -o stdout` on a musl system aborts with SIGILL. 

**Expected behavior**
The tail plugin shouldn't throw an exception on musl systems :)

**Additional context**
I've created #1719 which fixes this problem.

**Comment by edsiper** [comment]
Fluent Bit is not Musl compatible. well, musl is not glibc compatible.

**Comment by nigels-com** [comment]
Broader Musl compatibility aside, it seems like a harmless additional check.
Perhaps a comment there to clarify the reason for it?

**Comment by jawi** [comment]
@nigels-com I've expanded the comment a bit more to clarify what is happening.

**Comment by jawi** [comment]
@edsiper : I understand that support for musl is not the primary focus of this project, but aside from one missing feature (fts support that's used in chunkio) the project currently builds and runs fine on my musl-based systems. So hats off for that! :100:
