### ISSUE TITLE
Unable to parse time containing square brackets

### ISSUE THREAD

**Issue by xPB12** [fluent/fluent-bit#1726]
## Bug Report

Unable to parse time containing square brackets. Fluent bit throws invalid datetime format.

- Example log message if applicable:
```
[11-Nov-2019] [15:36:52:551] [INFO] [ENTRY] {[Method()][Entered into the match]
```
Tried below regex pattern 

[PARSER]
   Name        till1
   Format      regex
   Regex       ^(?<time>[^ ]+ [^ ]+)(?<message>.*)
   Time_Key    time
   Time_Format [%d-%b-%Y] [%H:%M:%S:%L]
   Time_Keep   On

Having square brackets in between the date and time causes the error.

**Comment by kantica** [comment]
Brackets are not the problem, %L fraction is. You can't have fraction of second separated by ":", use "," or "."

Take a look at ISO 8601. Excerpt from Wikipedia:

> Decimal fractions may be added to any of the three time elements. However, a fraction may only be added to the lowest order time element in the representation. A decimal mark, either a comma or a dot (without any preference as stated in resolution 10 of the 22nd General Conference CGPM in 2003,[24] but with a preference for a comma according to ISO 8601:2004)[25] is used as a separator between the time element and its fraction. To denote "14 hours, 30 and one half minutes", do not include a seconds figure. Represent it as "14:30,5", "1430,5", "14:30.5", or "1430.5". There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places needs to be agreed to by the communicating parties. For example, in Microsoft SQL Server, the precision of a decimal fraction is 3, i.e., "yyyy-mm-ddThh:mm:ss[.mmm]".[26]
