### ISSUE TITLE
Some input plugins don't support filter plugin

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#173]
We should add `flb_input_buf_write_start()` and `flb_input_buf_write_end()` at packing.
It needs to call the filter handler.

**Comment by nokute78** [comment]
Rest of input plugins are 
* in_forward
* in_http
* in_kmsg
* in_serial
* in_stdin
* in_tcp
* in_xbee

**Comment by edsiper** [comment]
thanks for the patches!

I will keep this open until we fix all of them. 

note: in_forward use 'dyntag' mechanism, I need to add filter support for that ingestion method.

**Comment by edsiper** [comment]
Updates:

- [ ] in_forward: pending until filtering support for dyntag plugins is added.
- [ ] in_http: this plugin is not functional yet
- [x] in_kmsg: fixed.
- [x] in_serial: fixed.
- [x] in_stdin: fixed.
- [x] in_tcp: fixed.
- [ ] in_xbee: should this plugin be deprecated ? (ref: #181)

**Comment by nokute78** [comment]
Thank you for fixing.
A little bit more!

**Comment by edsiper** [comment]
closing this issue, remaining ones are:

- in_http -> plugin not functional.
- in_xbee -> to be defined (#181).
