### ISSUE TITLE
Can one build a statically linked binary?

### ISSUE THREAD

**Issue by exquisitus** [fluent/fluent-bit#1736]
My problem begins by trying to deploy fluent-bit on machines running a somewhat older OS (SLES 12), for which there are no binaries offered by fluent-bit. I cannot use those machines themselves to build, but I have to use another computer.

Is there a way to build a statically linked fluent-bit binary for the linux amd64 architecture, which does not depend on shared libraries? For the moment, my built binary runs on the build machine but, perhaps unsurprisingly, fails when deployed with something like _/lib64/libc.so.6: version `GLIBC_2.27' not found (required by bin/fluent-bit)_

**Comment by nigels-com** [comment]
If it's possible to spin up a SLES 12 docker container, that might be a way to produce a fluent-bit binary that would run on the production machine.

**Comment by exquisitus** [comment]
Thank you for the idea!

**Comment by krezovic** [comment]
Hello, sorry to barge in here. I'm facing the same issue where I have to compile fluent-bit for SLES12 patchlevel 4. I'm unable to find any SLES docker image. I do not own any SLES license to be able to get it, but the machines on the customer's system run it.

**Comment by igorpeshansky** [comment]
If you run the binary out of a docker container, that container doesn't have to be based on SLES — it could just be a plain Debian container.

To answer the other question, we've had some luck with using an OpenSUSE container base for SLES builds of the collectd-based Stackdriver monitoring agent — see https://github.com/Stackdriver/agent-packaging/blob/master/build/x86_64_sles12/Dockerfile. You may be able to adapt it for fluent-bit.

**Comment by krezovic** [comment]
Thank you very much. I've tried to find a matching debian version that has less than but close enough libc and gcc. I could use jessie image, but it has too old cmake to be able to build fluent bit. Lets try with your approach.

**Comment by krezovic** [comment]
I managed to build it on debian jessie, as I couldn't use provided image. The resulting binary was able to run on SLES12.

Downside: I had to compile newer cmake than it was provided in debian jessie.

```
FROM debian:jessie

RUN apt-get update && \
    apt-get install -y build-essential bison flex wget libncurses5-dev libbz2-dev zlib1g-dev liblzma-dev libexpat1-dev libcurl4-openssl-dev && \
    wget https://github.com/Kitware/CMake/releases/download/v3.18.3/cmake-3.18.3.tar.gz && \
    tar xf cmake-3.18.3.tar.gz && \
    cd cmake-3.18.3 && \
    ./bootstrap --parallel=8 --system-curl --system-expat --system-zlib --system-bzip2 --system-liblzma && \
    make -j8 && \
    make install && \
    cd && \
    wget https://fluentbit.io/releases/1.5/fluent-bit-1.5.7.tar.gz && \
    tar xf fluent-bit-1.5.7.tar.gz && \
    cd fluent-bit-1.5.7/build && \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/fluent-bit -DFLB_SHARED_LIB=off -DFLB_TLS=on -DFLB_EXAMPLES=off .. && \
    make -j8 && \
    make install DESTDIR=$PWD/fluent-bit && \
    tar cf fluent-bit.tar fluent-bit && \
    xz fluent-bit.tar && \
    cp fluent-bit.tar.xz / && \
    apt-get purge -y build-essential bison flex wget libncurses5-dev libbz2-dev zlib1g-dev liblzma-dev libexpat1-dev libcurl4-openssl-dev && \
    apt-get autoremove -y --purge && \
    apt-get clean && \
    rm -rf /root/*
```
