### ISSUE TITLE
PostgreSQL Output Plugin

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#1739]
PostgreSQL has a neat feature to handle JSON documents, we can use that feature to aggregate logs.

@sxd from @2ndquadrant already wrote an external plugin with this functionality. I vouch to make this part of v1.4 release as a core plugin:

https://github.com/sxd/fluent-bit-pgsql

**Comment by sxd** [comment]
I've created the proper pull request for this feature here https://github.com/fluent/fluent-bit/pull/1931

**Comment by edsiper** [comment]
Fixed by #1931
