### ISSUE TITLE
Fluent-bit win 1.3.2-1 Output Retry_Limit=False not working

### ISSUE THREAD

**Issue by suxarik** [fluent/fluent-bit#1765]
## Bug Report

**Describe the bug**
Setting Output (forward type) Retry_Limit to "False" does not work. FLuent-bit tries for couple fo minutes, then just does nothing.

**Flow**
Text logs->fluent-bit->FluentD->Elasticsearch

**To Reproduce**
- Set Retry_Limit False
- Stop FluentD for 3 min
- Restart FluentD
- Watch Fluent-bit do nothing. No logs, no nothing

**Expected behavior**
After restarting FluentD, Fluent-bit should retry sending log events

**Environment**

* Version used: 1.3.2-1
* Configuration:
[Fluent Bit]
    Edition             Community Edition
    Version             1.3.2
    Built Flags          FLB_HAVE_PARSER FLB_HAVE_RECORD_ACCESSOR FLB_HAVE_STREA
M_PROCESSOR JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_TIMESPEC_GET FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_LUAJIT
* Operating System and version: Windows Server 2012 R2
* Filters and plugins:
[Built Plugins]
    Inputs              tail dummy stream_processor winlog lib random
    Filters             stdout grep parser modify lua record_modifier
    Outputs             counter datadog es file forward http kafka null splunk stdout tcp flowcounter

**Additional context**
Strange enough, settings Retry_Limit to something, like 1000 does work as expected

**Comment by edsiper** [comment]
is this only happening on windows ?

**Comment by suxarik** [comment]
> 
> 
> is this only happening on windows ?

As far as I can tell, yes. I do not use tail-type input on linux.

**Comment by edsiper** [comment]
please share your full configuration

**Comment by suxarik** [comment]
> 
> 
> please share your full configuration



[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Yes

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.
    Log_Level    debug
    Log_File    C:/Logs/fluent-bit/fb.log
    Buffer_Chunk_Size 128k
    Buffer_Max_Size   4096k

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

#---------------------------------------------------------------------------

[INPUT]
    Name tail
    Path C:/Logs/AM/application*.log
    Path_key FILEPATH
    Tag AM.application
    DB C:/Logs/fluent-bit/db/fluentbit_amapp.db

#---------------------------------------------------------------------------

[FILTER]
    Name record_modifier
    Match AM.application
    Record _HOSTNAME ${HOSTNAME}
    Record logtype Application
    Record PRODUCT AM

#---------------------------------------------------------------------------

[OUTPUT]
    Name          forward
    Match         *
    Host          10.0.162.20
    Port          24225
    Retry_Limit   100000

**Comment by fujimotos** [comment]
I believe this is fixed in the latest release (v1.4.6).
Please feel free to reopen if you see the same issue.
