### ISSUE TITLE
FLB_LOG_LEVEL not respected

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#1769]
## Bug Report

**Describe the bug**
While I can not find it in the docs, this old issue indicated that log level could be set by an env var: https://github.com/fluent/fluent-bit/issues/920

But setting `FLB_LOG_LEVEL` does not seem to do anything.

**To Reproduce**
- Steps to reproduce the problem:

```
docker run -it -e "FLB_LOG_LEVEL=debug" fluent/fluent-bit:latest
```

**Expected behavior**
Set log level via env var FLB_LOG_LEVEL.

**Your Environment**

* Version used: v1.2.2, v1.3.2, v1.3.3
* Configuration: Any

**Comment by PettitWesley** [comment]
I think I see the problem, the [commit](https://github.com/fluent/fluent-bit/commit/a27991b896a4160b8426e4fcfd9ed99daa58fc50) referenced in https://github.com/fluent/fluent-bit/issues/920#issuecomment-441276974 only adds env var interpolation in the in the config for LogLevel. So you can set your service section as:

```
[SERVICE]
    Log_Level ${FLB_LOG_LEVEL}
```

And then you can set FLB_LOG_LEVEL to anything at runtime. You could also change FLB_LOG_LEVEL to anything- there's no standard env var.

What I'd prefer is to have FLB_LOG_LEVEL as the standard env var for log level, and allow it to be used without setting a service section at all. I think that's what the OP in #920 wanted as well.

**Comment by PettitWesley** [comment]
I'd be happy to try to implement this; right now I'm just struggling to figure out the right place in the code to do the look up.

**Comment by edsiper** [comment]
it should be handled here:

https://github.com/fluent/fluent-bit/blob/master/src/flb_config.c#L392

note: not sure at the moment why is not working

**Comment by PettitWesley** [comment]
@edsiper `FLB_CONF_STR_LOGLEVEL` is [set to "Log_Level"](https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_config.h#L212).

Also `flb_env_var_translate` seems to [only process strings in the form of ${VAR](https://github.com/fluent/fluent-bit/blob/master/src/flb_env.c#L183)}. I think its for interpolation only?

I think the solution is to instead call [flb_env_get](https://github.com/fluent/fluent-bit/blob/master/src/flb_env.c#L124) with FLB_LOG_LEVEL as the input string. I'm gonna try that out.

**Comment by PettitWesley** [comment]
Hmm that doesn't work... [`flb_config_set_property()`](https://github.com/fluent/fluent-bit/blob/master/src/flb_config.c#L378) is only called if the [Service] section is set.

**Comment by edsiper** [comment]
from the command line, the log level is handled/increased by _-v_ , would you like an option to specify like -v debug ?

**Comment by PettitWesley** [comment]
@edsiper Yeah, that'd be nice, but I think environment variable is more convenient. 

Most users will run Fluent Bit in a container, and it's easier to set an env var than to override the default command. 

Part of the reason that I submitted this change is that I use `FLB_LOG_LEVEL` in the AWS Go plugins (since there's no way to pull the config log level in Go). Of course now that we plan to re-write those plugins in C, that does not matter as much.

I still think log level via env var is a nice convenience.

**Comment by nigels-com** [comment]
Chiming in to agree with @PettitWesley that logging via environment variables is very nice to have for docker deployments.  The key difference is that you'd typically need to bake a new container to change command-lines, but environment variables have first-class support for CLI docker **run** invocations.

**Comment by edsiper** [comment]
ready to go on #1771 once @nigels-com confirms :)

**Comment by pranavmarla** [comment]
FYI, looks like #1771 was successfully merged, so this issue is presumably solved and can be closed.
