### ISSUE TITLE
Configuration file loading in C/C++ application

### ISSUE THREAD

**Issue by jmarijan** [fluent/fluent-bit#1776]
Hi, I am having problem with my fluent-bit application in C++ on Ubuntu Linux.

Problem is occured when config file needs to be loaded. I am trying to set service, input and output parameters. 
I am using function `flb_lib_config_file` to upload a config file.
Your function description says:
`/* Load a configuration file that may be used by the input or output plugin */`
What does term "may be used" mean?

As an input, manual data ingestion("lib")  has been set, while as an output, I am using InfluxDB.

My configuration file is:
```
[SERVICE]
    Flush   1
    Daemon   off
    Log_Level   debug

[INPUT]
    Name   lib

[OUTPUT]
    Name          influxdb
    Match         *
    Host          _my_ip_address_
    Port          8086
    Database      _my_database_
    Sequence_Tag  _seq
```
When I start my application, despite config file values, fluent-bit always takes deafult parameters.
So for the InfluxDB hostname, it always takes _127.0.0.1_, instead of those stated in a config file.
It happens with every parameter in config file. It's like config file doesn't exist.

Currently, only solution for me is to hardcode values in the function `flb_output_set`. In that way, all parameters are set properly.

Regarding order of calling fluent-bit function, I am using the same flow as in the **td_cpp** example.

Am I doing something wrong, or some service/input/outputs values are unavailable to be overriden through config files?

Also, do you have in future plans to upload documentation for developers?

Thanks in advance.

**Comment by fujimotos** [comment]
> I am using function flb_lib_config_file to upload a config file.
> Your function description says:
> ...
> What does term "may be used" mean?

I think you're assuming that `flb_lib_config_file()` is a function to
apply configuration in bulk, but that's not the case.

What `flb_lib_config_file()` does is to tokenize the file content and
store the parsed tokens into `ctx->config->file`. This means that
the task to apply the configuration is left to you.

For instance, you need to do something like below to make `[SERVICE]`
settings actually effective.

```c
/* Load a configuration file (required by TD output plugin) */
ret = flb_lib_config_file(ctx, argv[1]);
if (ret != 0) {
    exit(EXIT_FAILURE);
}   

/* Apply the configuration manually */
struct mk_rconf_section *section;
struct mk_rconf_entry *entry;
struct mk_list *head;

section = mk_rconf_section_get(ctx->config->file, "SERVICE");
if (section) {
    mk_list_foreach(head, &section->entries) {
        entry = mk_list_entry(head, struct mk_rconf_entry, _head);
        flb_config_set_property(ctx->config, entry->key, entry->val);
    }   
}   
```

For a more complete example, please read [src/fluent-bit.c](https://github.com/fluent/fluent-bit/blob/master/src/fluent-bit.c#L381).
