### ISSUE TITLE
Full ca_chain not being sent by fluent-bit to fluentd as per TLS parameter

### ISSUE THREAD

**Issue by derryos** [fluent/fluent-bit#1788]
## Bug Report

Fluentd version (td-agent): 3.3.0 
Fluent Bit v1.2.2

Using vault  pkis to generate certificates for fluent-bit, we get the full ca_chain, cert and key. When we pass those to the fluent-bit config, we get errors on send and tcpdump/wireshark shows that the full ca_chain is not being sent and we see the following in fluent-bit debug logs:
```
[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_tls.c 2779: ssl->f_send() returned -80 (-0x0050)

[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_tls.c 3472: mbedtls_ssl_flush_output() returned -80 (-0x0050)

[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_tls.c 3315: ssl_write_record() returned -80 (-0x0050)

[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_cli.c 3168: mbedtls_ssl_write_handshake_msg() returned -80 (-0x0050)

[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_tls.c 8094: <= handshake

[2019/12/03 15:48:16] [error] [io_tls] flb_io_tls.c:348 NET - Connection was reset by peer
[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_tls.c 8934: => free

[2019/12/03 15:48:16] [debug] [io_tls] /lib/mbedtls-2.16.1/library/ssl_tls.c 8999: <= free

[2019/12/03 15:48:16] [error] [out_fw] no upstream connections available
```

If we edit the ca_chain to only include the root ca, and append the rest of the ca_chain to the cert (so we forcibly send), then the connection works.

Should the ca_chain parameter contain the full chain or not?

**Expected behavior**
Would like to use the vault generated certificates (ca_chain, cert, key) directly - and would expect fluent-bit to send the full chain as in the ca_file parameter

**Your Environment**
* Version used: (as above)
* Configuration:
```
[SERVICE]
    Flush      5
    Daemon     off
    Log_Level  trace

[INPUT]
    Name        tail
    Path        /var/log/*.*

[OUTPUT]
    Name          forward
    Match         *
    Host          <fluentdServer>
    Port          24224
    Self_Hostname <someValue>
    tls           on
    tls.verify    on
    tls.debug     4
    Shared_Key    secretValue
    tls.crt_file   /vault.cert
    tls.key_file  /vault.key
    tls.ca_file  /vault.cachain
```

* Environment name and version (e.g. Kubernetes? What version?):
1.15.3
* Server type and version:
Centos 7
* Operating System and version:
* Filters and plugins:

**Additional context**
Would like to use vault generated certs directly vs having to edit to get SSL comms working

**Comment by derryos** [comment]
Can someone please help with the above? This is still affecting us.

**Comment by amarkelov** [comment]
guys, please, take a look at this. The unusual workflow whereby you need to mess around with full chain of trust and cert is worrying and hard to automate.

**Comment by edsiper** [comment]
My apologies for the delay on this. 

We will do a troubleshooting tomorrow on this issue and provide some feedback shortly.

**Comment by fujimotos** [comment]
I spent this evening setting up a testing Vault instance and could reproduce
the issue.

The problem is actually a general problem that occurs when:

  1) A client uses a leaf certificate issued by an intermediate cert.
  2) And the intermediate cert is not known by the server.

As @derryos wrote, manually concatenating cert chain files would resolve
the error, but It would be better if we can avoid such a manual intervention.

@derryos @amarkelov Can you post your configuration for *fluentd*?
I want to take a look so that I can ponder possible solutions.

**Comment by amarkelov** [comment]
@fujimotos you are spot on about the client's cert. In our case it is issued by an intermediate not known to the server.
The fluentd config

```
<system>
  workers 1
#  log_level debug
</system>

# Listen to fluentd
<source>
  @type forward
  bind 0.0.0.0
  port 24224
  source_hostname_key _HOSTNAME
  <security>
    self_hostname server_fqdn_here
    shared_key secret
  </security>
  <transport tls>
    version TLSv1_2
    ciphers "TLSv1.2"
    ca_path /etc/td-agent/secure/full-chain.pem
    cert_path /etc/td-agent/secure/fluentd_ssl_crt.pem
    private_key_path /etc/td-agent/secure/fluentd_ssl_key.pem
    client_cert_auth false
    insecure false
  </transport>
</source>

<source>
  @type monitor_agent
</source>

# Exposes prometheus metrics
<source>
  @type prometheus
</source>

<source>
  @type prometheus_monitor
  <labels>
    host ${hostname}
  </labels>
</source>

<filter **>
  @type prometheus
  <metric>
    name fluentd_input_status_num_records_total
    type counter
    desc The total number of incoming records
    <labels>
      tag ${tag}
      hostname ${hostname}
    </labels>
  </metric>
</filter>

<source>
  @type prometheus_output_monitor
  <labels>
    host ${hostname}
  </labels>
</source>

# below was for debug
#<match **>
# @type stdout
#</match>

# count number of outgoing records per tag while forwarding to syslog
<match **>
  @type copy
  <store>
    @type remote_syslog
    host localhost
    port 514
    protocol udp
    facility local2
    packet_size 65536
    hostname ${_HOSTNAME}
    <buffer _HOSTNAME>
      @type file
      path /tmp/fluentd-syslog1
      overflow_action block
      flush_interval 10s
      retry_forever true
      retry_type periodic
      retry_wait 5s
      retry_randomize true
    </buffer>
    <format>
      @type json
    </format>
  </store>
  <store>
    @type prometheus
    <metric>
      name fluentd_output_status_num_records_total
      type counter
      desc The total number of outgoing records
      <labels>
        tag ${tag}
        hostname ${hostname}
      </labels>
    </metric>
  </store>
</match>
```

**Comment by derryos** [comment]
Thanks @amarkelov & @fujimotos

**Comment by fujimotos** [comment]
So the fundamental problem here is that we have *two separate* certificates.

1. `vault.cert` that (only) contains the leaf certificate.
2. `vault.ca_chain` that contain the intermediate certs.

A common solution for such a setup, I think, is to concatenate two files
into `fullchain.pem` and set the combined file to `tls.crt_file`:

```bash
$ cat vault.cert vault.ca_chain > fullchain.pem
```

... but you guys don't want to do it manually (right?)

I'm wondering what do you think is a desirable solution here. My very rough
idea is to allow specifying cert chains in the `tls.crt_file` option, like:

```
[OUTPUT]
   Name forward
   ...
   tls.crt_file vault.cert, vault.ca_chain
```

@amarkelov @derryos  Do you think this fix helps? I'd really appreciate
if I can hear your opinions.

**Comment by amarkelov** [comment]
@fujimotos no, we are not handling the files manually 😄 

The expected behavior was the same as with the server end config, you have one file the cert, one file the key and one file with full chain of trust.

```
    ca_path /etc/td-agent/secure/full-chain.pem
    cert_path /etc/td-agent/secure/fluentd_ssl_crt.pem
    private_key_path /etc/td-agent/secure/fluentd_ssl_key.pem
```

Concatenating cert and chain together is fine.

What was unexpected was the need to leave only root CA part in file that was supposed to have full chain of trust and concatenate the rest to the cert file. Hence the bug report. We haven't seen anything like this before, so have our security guys.

**Comment by fujimotos** [comment]
@amarkelov Thank you for the response!

> What was unexpected was the need to leave only root CA part in file that was supposed to have full chain of trust and concatenate the rest to the cert file. Hence the bug report. We haven't seen anything like this before, so have our security guys.

What's puzzling here is that the same setup that you described seems
working fine on my environment. Let me spell out how I set up things,
so we can find out what causes your problem.

Please feel free to comment anything you notice!

#### Software versions

* HashiCorp Vault v1.3.2
* Fluent Bit v1.3.7
* Fluentd v1.8.1

#### How I setup nodes

I created the following cert chains to reproduce your issue.


    +----------+     +---------------+     +------------+
    | root.crt |--+--| intermed1.crt |-----| server.crt |
    +----------+  |  +---------------+     +------------+
                  +--| intermed2.crt |-----| client.crt |
                     +---------------+     +------------+

... and make Fluentd to use the server chain (intermed1/server) and
Fluent Bit to use the client chain (intermed2/client).

You can view the full configuration files and setup scripts from here:
https://gist.github.com/fujimotos/180b2a8f8483f106e19e937dc25454cb

#### Test Result

I could confirm that Fluent Bit can transfer data to Fluentd without issues.

Moreover, I did not need to trim the root CA from the certificate chain file;
It just worked as long as the client cert (`tls.crt_file`) contains both the
client cert and its intermediate cert (namely client.crt and intermed2.crt).

(See [this line](https://gist.github.com/fujimotos/180b2a8f8483f106e19e937dc25454cb#file-generate-cert-sh-L40) for how I generated the fullchain file).

**Comment by amarkelov** [comment]
@fujimotos sorry for the delay! Crazy week here.

Our setup is more like this:

````
+----------+     +----------------+   +----------------+   +------------+
| root.crt |--+--| intermed1a.crt |---| intermed1b.crt |---| server.crt |
+----------+  |  +----------------+   +----------------+   +----------------+   +------------+
              +--| intermed2a.crt |---| intermed2b.crt |---| intermed2c.crt |---| client.crt |
                 +----------------+   +----------------+   +----------------+   +------------+
````
The depth is greater than in your test environment. Would that make a difference?
We have uncovered depth related bug in rsyslog (it was hardcoded for TLS depth 2), which was fixed in the recent build after we reported the bug to dev there.
Any chance we may have something similar at play here? That might explain why it works in our case when root CA has to be left on its own in the file that I would expect to have full chain of trust.

**Comment by fujimotos** [comment]
> The depth is greater than in your test environment. Would that make a difference?

Following your idea, I spent this evening experimenting with deeply-nested
cert chains, but failed to reproduce the issue. 

Indeed, I can confirm in the debug log that Fluent Bit is sending cert
chains properly (from leaf to root). Adding 3 intermediate CAs did not
break it.

Attached is the cert chain that I created for the testing. It looks as below:

```
+----------+     +-------------+   +-------------+   +-------------+
| root.crt |--+--| server1.crt |---| server2.crt |---| server.crt  |
+----------+  |  +-------------+   +-------------+   +-------------+   +------------+
              +--| client1.crt |---| client2.crt |---| client3.crt |---| client.crt |
                 +-------------+   +-------------+   +-------------+   +------------+
```

@amarkelov Can you experiment with the attached certificates on your
environemnt? I'm not entirely sure about what makes the difference,
but a bit suspecting that it might be in your certs.

**Attachment**

* [20200214-vault.zip](https://github.com/fluent/fluent-bit/files/4203638/20200214-vault.zip)

**fluent-bit.conf**

```ini
[INPUT]
  Name Dummy
  Tag debug.log

[OUTPUT]
  Name Forward
  Host 127.0.0.1
  Port 24224
  tls On
  tls.vhost    server.fluent.local
  tls.ca_file  root.crt
  tls.key_file client.key
  tls.crt_file client.full
  tls.verify   true
  tls.debug    3
```

**fluentd.conf**

```xml
<source>
  @type forward
  <transport tls>
    client_cert_auth true
    ca_path          server.full
    cert_path        server.crt
    private_key_path server.key
  </transport>
</source>

<match debug.**>
  @type stdout
</match>
```
