### ISSUE TITLE
[error] [src/flb_config.c:126 errno=12] Cannot allocate memory

### ISSUE THREAD

**Issue by huanggze** [fluent/fluent-bit#1791]
## Bug Report

**Describe the bug**

I had the following errors when deploying fluent bit on arm64-based Centos 7.6 BM machines.

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[2019/12/06 05:14:25] [error] [src/flb_config.c:126 errno=12] Cannot allocate memory
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

Fluent Bit runs with no error

**Screenshots**

**Your Environment**

* Version used: 1.3.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.14.2
* Server type and version: 
* Operating System and version: CentOS 7.6
* Filters and plugins:

**Additional context**

`getconf PAGESIZE` returns 65536

**Comment by edsiper** [comment]
are you building Fluent Bit from scratch or using some of our packages or docker image ?

**Comment by huanggze** [comment]
I am building image by myself with the following Dockerfile. (I changed one dependency from libssl1.0-dev to libssl1.1, due to errors reported in my case)

```
FROM arm64v8/debian:buster-slim as builder

# Fluent Bit version
ENV FLB_MAJOR 1
ENV FLB_MINOR 3
ENV FLB_PATCH 3
ENV FLB_VERSION 1.3.3

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      make \
      wget \
      unzip \
      libssl1.1 \
      libsasl2-dev \
      pkg-config \
      libsystemd-dev \
      zlib1g-dev \
      flex \
      bison

RUN mkdir -p /fluent-bit/bin /fluent-bit/etc /fluent-bit/log /tmp/src/
COPY . /tmp/src/
RUN rm -rf /tmp/src/build/*

WORKDIR /tmp/src/build/
RUN cmake -DFLB_DEBUG=Off \
          -DFLB_TRACE=Off \
          -DFLB_JEMALLOC=On \
          -DFLB_BUFFERING=On \
          -DFLB_TLS=On \
          -DFLB_SHARED_LIB=Off \
          -DFLB_EXAMPLES=Off \
          -DFLB_HTTP_SERVER=On \
          -DFLB_IN_SYSTEMD=On \
          -DFLB_OUT_KAFKA=On ..

RUN make -j $(getconf _NPROCESSORS_ONLN)
RUN install bin/fluent-bit /fluent-bit/bin/

# Configuration files
COPY conf/fluent-bit.conf \
     conf/parsers.conf \
     conf/parsers_java.conf \
     conf/parsers_extra.conf \
     conf/parsers_openstack.conf \
     conf/parsers_cinder.conf \
     conf/plugins.conf \
     /fluent-bit/etc/

#
EXPOSE 2020

# Entry point
CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
```

**Comment by edsiper** [comment]
just to clarify, the problem goes away using your own Dockerfile or the problem is faced with your Dockerfile ?, do you see the same problem with our docker image ?

**Comment by huanggze** [comment]
I faced this problem with my own Dockerfile. I didn't try with yours. because i wanna build image for arm-based machines.

Actually, I managed to fix this problem finally, by COPY so files from arm machines to image in Dockerfile directly. So i am using the same libraries with my arm machines in containers.

**Comment by edsiper** [comment]
out Docker images are for x86_64, armv7 and armv8 (multi-layer image)

**Comment by huanggze** [comment]
thanks for the info, I will try
