### ISSUE TITLE
Stream processor: Add support for "!=" condition in WHERE clause

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#1793]
**Describe the solution you'd like**
Allow `!=` in the WHERE clause. So that for example, a query can match all logs that do not have `level` as `error`:

```
SELECT * from TAG:'app*' WHERE request != 'error';
```

**Additional context**
While writing this blog I thought that such a feature would be useful: https://aws.amazon.com/blogs/opensource/splitting-application-logs-multiple-streams-fluent/

I have had several readers of it tell me that this would be useful for the sort of use case described in the blog. 

Specifically, this note in the post:

> The toy example shown in this section worked because all of our logs have a level field, and its value is one of five strings (debug, info, warning, error, and fatal). This made it possible to create stream queries which matched all of the logs. If this was not the case, we would run into a problem: Logs which do not match our stream queries would remain in the original heterogeneous log stream, which is discarded and not sent to a destination. If this is the case in your setup, read the Fluentbit streams processing documentation to see if you can write queries which will identify all of your logs. If you cannot, consider opening (or up-voting) an issue on the fluent/fluent-bit repository to support additional conditions in the where clause of stream queries.

The use case was to re-tag logs based on the value of a given key. However, this becomes difficult if the set of values for the key is unknown. 

Add `not equal` support would help. Or alternatively, the ability to re-tag logs based on the value of a key in a record.

**Comment by edsiper** [comment]
cc: @koleini

**Comment by koleini** [comment]
@PettitWesley Thanks for submitting the issue. For now, you can write `NOT request = 'error'`, but it is useful to add specific `not equal` operator(s) to the syntax. I will send a PR soon.

**Comment by edsiper** [comment]
Fixed by #1818
