### ISSUE TITLE
[not an issue / buffering setup] tail plugin (with database) looses records after restart

### ISSUE THREAD

**Issue by eldargab** [fluent/fluent-bit#1797]
## Bug Report

**Describe the bug**

Tail plugin will loose records if td-agent-bit restarts while upstream sink is unavailable.

**To Reproduce**

Setup:

```
[INPUT]
    Name tail
    Tag foo
    Path /foo.log
    DB /foo.db
    Parser json_lines

[OUTPUT]
    Name  http
    Match foo
    Retry_Limit False
    ...
```

Steps:

1. Disable upstream http server
2. Produce some logs
3. Restart td-agent-bit
4. Produce more logs
5. Enable upstream http server

**Expected behavior**

Logs from steps 2 and 4 are sent to upstream.

**Actual behavior**

Only logs from step 4 where sent.

**Your Environment**

* Version used: Fluent Bit v1.3.3

**Comment by fujimotos** [comment]
@eldargab Fluent Bit uses on-memory buffer by default, so it loses
pending records on each reboot. If you want to avoid that, you need
to use`filesystem` storage instead.

Try the following configuration:

```ini
[SERVICE]
    storage.path              /tmp/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    Name tail
    Tag foo
    Path /foo.log
    DB /foo.db
    Parser json_lines
    Storage.Type filesystem

[OUTPUT]
    Name  http
    Match foo
    Retry_Limit False
```

For more details, read https://docs.fluentbit.io/manual/configuration/buffering.

**Comment by eldargab** [comment]
Yes, somehow I missed that. Sorry for disturbance.
