### ISSUE TITLE
Support Amazon ElasticSearch Service with authentication

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#1804]
The newer versions of Amazon ES require Sigv4 auth with valid AWS credentials. 

Right now, Fluent Bit users have to use a proxy like this: https://github.com/abutaha/aws-es-proxy

It would be ideal if the Fluent Bit ES plugin natively supported Amazon ES. 

Prerequisites:
- [Completed by @edsiper] [Sigv4 Auth](https://github.com/fluent/fluent-bit/commit/e757ee8c84c817c68ae1029d8e2a9a6a40b20130)
- [WIP by @PettitWesley] [Standard AWS credential providers](https://github.com/PettitWesley/fluent-bit/commit/1314c9fb6510aa96831ae0a70465014cb3c27e05)

**Comment by Angry-Potato** [comment]
is this feature coming soon to a release near me?

**Comment by PettitWesley** [comment]
@Angry-Potato This was released in Fluent Bit 1.5 a few months ago.. merged via a different PR. Looks like I forgot to close this one.

Docs are here: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch##aws-es
