### ISSUE TITLE
Kubernetes installation yamls failed on 1.16

### ISSUE THREAD

**Issue by davix** [fluent/fluent-bit#1805]
## Bug Report

**Describe the bug**

Following doc https://docs.fluentbit.io/manual/installation/kubernetes#installation to install fluent-bit on kubernetes, see below error:

kubectl create -f https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/output/elasticsearch/fluent-bit-ds-minikube.yaml

> no matches for kind "DaemonSet" in version "extensions/v1beta1"

Per https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals, "extensions/v1beta1" is not supported.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"kubectl create -f https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/output/elasticsearch/fluent-bit-ds-minikube.yaml

no matches for kind "DaemonSet" in version "extensions/v1beta1"
","stream":"stdout","time":"2019-12-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): kubernetes 1.16.2
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by edsiper** [comment]
thanks for raising this issue.

Looking around I see that Kubernetes 1.14 in their changelog talk about the deprecation on 1.16:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations

```
DaemonSet, Deployment, and ReplicaSet resources will no longer be served from
extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1
API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.
```

So the Yaml file needs to be adjusted for Kubernetes 1.16 from ```extensions/v1beta1``` to ``` apps/v1```.

I've pushed an update to our documentation here:

https://docs.fluentbit.io/manual/installation/kubernetes#note-for-kubernetes-v-1-16
