### ISSUE TITLE
Wrong error message when using invalid filter parser

### ISSUE THREAD

**Issue by phiremande** [fluent/fluent-bit#1809]
## Bug Report

**Describe the bug**

When a filter parser is configured with a parser which is not present, the error message doesn't specify the name of the parser properly.
Example:
[FILTER]
    Name parser
    Match mysyslog
    Key_Name logmsg
    Parser myfinal1

When myfinal1 parser is not found, the error reported is as below
[2019/12/13 15:40:19] [error] [filter_parser] requested parser 'logmsg' not found
[2019/12/13 15:40:19] [error] [filter_parser] Invalid "parser"

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2019/12/13 15:40:19] [error] [filter_parser] requested parser 'logmsg' not found
[2019/12/13 15:40:19] [error] [filter_parser] Invalid "parser"
```
- Steps to reproduce the problem:
Use a similar configuration as provided above.

**Expected behavior**

The error reported should mention the name of the parser that is not found.

**Screenshots**

**Your Environment**

* Version used: Latest from master
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
Linux (Ubuntu)
* Filters and plugins:
Filter parser.
**Additional context**

Wrong error message is misleading.

**Comment by edsiper** [comment]
fixed in #1810 (merged)
