### ISSUE TITLE
in_xbee: should be deprecated ?

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#181]
I would like to know if someone is using this plugin, otherwise it could be removed from the next major release v0.11.

**Comment by nokute78** [comment]
In my opinion, in the next v0.11,
 it may be better to add warning message at in_xbee_init to notify in_xbee will be obsoleted.
If no one reports an issue about that, we will remove the plugin in v0.12 or later.

I'm concerned about the users who use in_xbee and don't see this issue.

**Comment by edsiper** [comment]
thanks for the idea, already implemented.

**Comment by nokute78** [comment]
Thanks!

**Comment by edsiper** [comment]
Plugin deprecated.
