### ISSUE TITLE
Directions for building on Windows?

### ISSUE THREAD

**Issue by krancour** [fluent/fluent-bit#1822]
I've been able to work backwards from `appveyor.yaml` to understand the prerequisites and process for building on Windows (the process seems different from building elsewhere). It "works," but I end up with a lot of warnings and therefore feel suspicious of the artifacts I'm producing.

Would it be a good idea to add specific prerequisites and instructions for building on Windows?

**Comment by barney-s** [comment]
Iam struggling with the same. Would you share your experience please ?

**Comment by krancour** [comment]
@barney-s I am so sorry. Over a year later and I am just now noticing your comment. This is so far in my rear view mirror now that I have no recollection that would be of any help to you. I'm sure that you also have either solved this or moved on by now. Cheers.
