### ISSUE TITLE
Windows fluent-bit support for in_forward plugin

### ISSUE THREAD

**Issue by jfeeny** [fluent/fluent-bit#1823]
I'd like support for the `in_forward` plugin for fluent-bit on windows.

I see in the [cmake config](https://github.com/fluent/fluent-bit/blob/master/cmake/windows-setup.cmake#L21) it is currently turned off.

Opening as a separate issue from windows support as per https://github.com/fluent/fluent-bit/issues/960#issuecomment-565439904

**Comment by fujimotos** [comment]
@jfeeny I ported the plugin to Windows and posted it as #1830. 

Also I published an integration testing build that contains the patch
at https://github.com/fluent/fluent-bit/issues/960#issuecomment-567836912.

I appreciate if you try it and see if the plugin works.

**Comment by fujimotos** [comment]
Now #1830 is merged. I close this issue as resolved.
