### ISSUE TITLE
Filter namespaces based on regex

### ISSUE THREAD

**Issue by rsingh2411** [fluent/fluent-bit#1826]
## Bug Report

**Describe the bug**
Negative look ahead with options is not getting picked up by fluent-bit.

**To Reproduce**
- Rubular link if applicable:
 https://rubular.com/r/LA2rSLh0kBwzUX
- Example log message if applicable:
following is regex expression with negative look ahead
^kube.(?!logging|testing|kube-system).*

```
fluent-bit configuration



file names are
ls  /var/log/containers/

- coredns-6fbfbf887c-25297_kube-system_coredns-6fd3aa1bf37df247ed70c1aaded1c4d4258ad8d8a24ae5bfa5882bc140780933.log

- elasticsearch-master-1_logging_elasticsearch-6f8db8566647e943dd58f4c26826555734313c2c93a0c3c1127faec7cfa83040.log
this works well in the rubular, but doesnt in fluent-bit
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:1.3.3
* Configuration:

[FILTER]
    Name kubernetes
    Match kube.*
    Kube_Tag_Prefix     kube.var.log.containers.*
    #Kube_URL https://kubernetes.default.svc:443
    #Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    #Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log           On
    Merge_Log_Key       processed_json
    K8S-Logging.Parser On
    K8S-Logging.Exclude On

[INPUT]
    Name             tail
    Path             /var/log/containers/\*.log
    Parser           docker
    Tag              kube.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[SERVICE]
    Daemon       Off
    Flush        10
    Log_Level    DEBUG
[OUTPUT]
    Name  stdout
    Log_Level    DEBUG
    Match ^(kube.(?!logging|test).*)

* Environment name and version (e.g. Kubernetes? What version?): 1.14
* Server type and version:
* Operating System and version: linux
* Filters and plugins:

**Additional context**
I am trying to add multiple namespaces as elasticsearch index, Elasticsearch will have 4 indexes
logging,kube-system,testing,infra. The first three will have data for specific namespaces and fourth one will have data for remaining ones.

followed the https://github.com/fluent/fluent-bit/issues/758 for the issue. It facilitates creation of the specific namespaces however when i try to use regex for remaining namespaces it doesnt work. The rubular expression works but the fourth index containing remaining namespaces doesnt get created.

**Comment by rsingh2411** [comment]
Any updates on this issue

**Comment by aranair** [comment]
I think it's `Match_Regex` instead of `Match`

**Comment by edsiper** [comment]
yes, it must be Match_Regex (thanks @aranair)
