### ISSUE TITLE
Connect to Elastic Cloud

### ISSUE THREAD

**Issue by talhelfgott-cx** [fluent/fluent-bit#1828]
## Bug Report

**Describe the bug**
Can't deliver logs to Elastic Cloud

Elastic Cloud is expecting me to provide:
cloud.id: "FOO"
cloud.auth: "elastic:<password>"

Do you support this integration?

Thanks

**Comment by edsiper** [comment]
AWS uses a different HTTP signed mechanism (compared to original Elasticsearch), please see more details on this thread (and possible workarounds):

https://github.com/fluent/fluent-bit/issues/1807
