### ISSUE TITLE
out_kafka_rest: HOST header not being added results in http error 400

### ISSUE THREAD

**Issue by phiremande** [fluent/fluent-bit#1836]
## Bug Report

**Describe the bug**

When using out_kafka_rest seeing 400 error. The configured destination is confluent kafka rest. A tcpdump shows that HOST header is missing the message being sent out.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2019/12/20 21:43:08] [debug] [out_kafka_rest] HTTP Status=400
[2019/12/20 21:43:08] [debug] [out_kafka_rest] Kafka REST response
<h1>Bad Message 400</h1><pre>reason: No Host</pre>
```
- Steps to reproduce the problem:
Built fluent-bit on ubuntu and ran it with following configuration:
[OUTPUT]
    Name        kafka-rest
    Match       my_syslog_test
    Host        <host_ip>
    Port        8082
    Topic       my_syslog_test

**Expected behavior**

HTTP Status should result in 200 OK.

**Screenshots**

**Your Environment**

* Version used: master
* Configuration: 
given above.
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
Ubuntu 18.04
* Filters and plugins:

**Additional context**
Trying to send messages by using in tail from a log file and sending to kafka rest .

In kafka.c I see that      c = flb_http_client(u_conn, FLB_HTTP_POST, ctx->uri,
                        js, js_size, NULL, 0, NULL, 0);
is constructed with host and port as NULL and 0.
Due to this fmt_vanilla is getting used I believe.
Is there anything that I am missing?
Shouldn't the caller pass host and port (from the connection)?

**Comment by phiremande** [comment]
diff --git a/plugins/out_kafka_rest/kafka.c b/plugins/out_kafka_rest/kafka.c
index 3aeb6b7a..44118cf9 100644
--- a/plugins/out_kafka_rest/kafka.c
+++ b/plugins/out_kafka_rest/kafka.c
@@ -221,7 +221,7 @@ static void cb_kafka_flush(const void *data, size_t bytes,

     /* Compose HTTP Client request */
     c = flb_http_client(u_conn, FLB_HTTP_POST, ctx->uri,
-                        js, js_size, NULL, 0, NULL, 0);
+                        js, js_size, u_conn->u->tcp_host, u_conn->u->tcp_port, NULL, 0);
     flb_http_add_header(c, "User-Agent", 10, "Fluent-Bit", 10);
     flb_http_add_header(c,
                         "Content-Type", 12,
I will raise a PR with this change, if the issue seems genuine. Else if I am missing something please let me know.

**Comment by vixns** [comment]
updated patch, add stripping the port from the host header, works for my use case (haproxy between fluent-bit and kafkarest).

```
diff --git a/plugins/out_kafka_rest/kafka.c b/plugins/out_kafka_rest/kafka.c
index 1cbf0b3b..6c232dd9 100644
--- a/plugins/out_kafka_rest/kafka.c
+++ b/plugins/out_kafka_rest/kafka.c
@@ -220,12 +220,17 @@ static void cb_kafka_flush(const void *data, size_t bytes,

     /* Compose HTTP Client request */
     c = flb_http_client(u_conn, FLB_HTTP_POST, ctx->uri,
-                        js, js_size, NULL, 0, NULL, 0);
+                       js, js_size, u_conn->u->tcp_host, u_conn->u->tcp_port, NULL, 0);
     flb_http_add_header(c, "User-Agent", 10, "Fluent-Bit", 10);
     flb_http_add_header(c,
                         "Content-Type", 12,
                         "application/vnd.kafka.json.v2+json", 34);

+    ret = flb_http_strip_port_from_host(c);
+    if (ret < 0) {
+        flb_plg_error(ctx->ins, "could not strip port from host");
+    }
+
     if (ctx->http_user && ctx->http_passwd) {
         flb_http_basic_auth(c, ctx->http_user, ctx->http_passwd);
     }
```
