### ISSUE TITLE
Where I can download the Windows td-agent-bit installer that doesn't have the missing DLL issue?

### ISSUE THREAD

**Issue by JungleGenius** [fluent/fluent-bit#1837]
## Bug Report

**Describe the bug**

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by fujimotos** [comment]
For anyone insterested, Windows builds that work without OpenSSL DLLs are
currently available at https://github.com/fluent/fluent-bit/issues/960#issuecomment-571906226.

The future Fluent Bit releases (v1.3.7 and v1.4.0; will be out shortly) will contain the fix
that resolves this issue too. So please stay tuned.
