### ISSUE TITLE
filter_kubernetes: static pod metadata missing due to not retry in case of 404 response from apiserver

### ISSUE THREAD

**Issue by patrickshan** [fluent/fluent-bit#1839]
## Bug Report

**Describe the bug**

Metadata for static pods (like kubernetes control plane pods) logs are missing due to 404 response from apiserver.  As static pods are started by kubelet and then registered back to apiserver, sometimes fluent-bit started monitoring those pods logs while they haven't registered back into apiserver. This causes query to apiserver response 404. In that case it will still have some metadata (pod name and namespace name)due to this: https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_meta.c#L619
which caused it to be added into hash table and no retry to get other metadata from apiserver.

**To Reproduce**
filter_kube plugin generates logs like this when querying those static pods from apiserver:
```
[2019/12/23 22:47:12] [debug] [filter_kube] API Server (ns=kube-system, pod=kube-apiserver-ip-10-1-139-117.us-west-1.compute.internal) http_do=0, HTTP Status: 404
[2019/12/23 22:47:12] [debug] [filter_kube] API Server response
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"kube-apiserver-ip-10-1-139-117.us-west-1.compute.internal\" not found","reason":"NotFound","details":{"name":"kube-apiserver-ip-10-1-139-117.us-west-1.compute.internal","kind":"pods"},"code":404}

[2019/12/23 22:47:12] [debug] [in_tail] file=/var/log/containers/kube-apiserver-ip-10-1-139-117.us-west-1.compute.internal_kube-system_kube-apiserver-c0ffbf1ec002d45b996a7eff37d757133ec661f1abf2a262c41e3edf29d79af6.log read=63999 lines=340
```
- Steps to reproduce the problem:
* use static pods for control plane components, like kube-apiserver, kube-scheduler and kube-controller-manager
* configure fluent-bit as daemonsets running on control plane nodes
* when start control plane nodes and they are turns ready, fluent-bit pods gets scheduled on them and started monitoring logs. But at the same time, control plane pods might not be ready which causes logs from those pods missing metadata. 

**Expected behavior**

fluent-bit should retry metadata query when response from apiserver is empty

**Your Environment**

* Version used: fluent-bit 1.3.5
* Configuration: 
```
# kube_filter configuration
    [FILTER]
        Name                kubernetes
        Alias               kubernetes_filter
        Match               kube.*
        Kube_Token_File    ***/token
        Kube_CA_File        ***/ca.crt
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Labels              On
        Annotations         On
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
```
* Environment name and version (e.g. Kubernetes? What version?): kubernetes 1.15.7
* Server type and version: EC2
* Operating System and version: CoreOS
* Filters and plugins: kube_filter

**Additional context**

**Comment by patrickshan** [comment]
added a PR to fix it: https://github.com/fluent/fluent-bit/pull/1851

**Comment by nvoskuilen** [comment]
While pod metadata like container_name were working in v1.4.3, it is now broken since v1.4.4+

Another user makes notice of this in #2249
