### ISSUE TITLE
filter-kubernetes: Analyze the Tag and extract the container 'Image' and 'Image ID' metadata

### ISSUE THREAD

**Issue by qqbuby** [fluent/fluent-bit#1842]
Analyze the Tag and extract the following metadata:
- Pod Name
- Namespace
- Container Name
- Container ID
- **Image**
- **Image ID**

**Comment by seeruk** [comment]
Yeah, just noticed that this is missing compared to fluentd, it's very handy to know because it's a good signal of what version of the app is being run if it doesn't log it's version itself.
