### ISSUE TITLE
Support for multiple ES outputs in same fluent-bit config

### ISSUE THREAD

**Issue by srivanibhompally** [fluent/fluent-bit#1847]
I am trying to send the various logs to different applications on a single server. I tried using different @inlcude configuration but ryt all the logs are being sent to one index on EFK. Please find the below configuration

td-agent-bit.conf
------
[SERVICE]
    Flush        5
    Log_Level    info
    Daemon       off
    Log_Level    info

    Parsers_File parsers.conf
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
@INCLUDE /etc/td-agent-bit/nginx.conf
@INCLUDE /etc/td-agent-bit/service.conf

------------------------------------------------------------
service.conf
------------
[INPUT]
    Name             tail
    Path             /etc/path/
    Multiline        On
    Parser_Firstline firstline
    Parser_1        second
[FILTER]
    Name            grep
    Match           *
    Exclude         LogLevel INFO
    Exclude         LogLevel DEBUG
    Exclude         LogLevel TRACE

[OUTPUT]
    Name             es
    Match            *
    Host             host
    Port             9200
    Logstash_Format On
    Logstash_Prefix X
    Logstash_DateFormat %Y.%m.%d
    Type            _doc
    Generate_ID      Y

[FILTER]
    Name   record_modifier
    Match  *
    Record hostname ${HOSTNAME}
    Record service ${SERVICE}
--------------------------------------------------

nginx.conf
----------------

[INPUT]
    Name             tail
    Path             /var/log/nginx/error.log
    Parser           nginx_error

[OUTPUT]
    Name             es
    Match            *
    Host             host
    Port             9200
    Logstash_Format On
    Logstash_Prefix X
    Type            _doc
    Generate_ID     Y
    Time_Key        @timestamp-es

Please let me know, what needs to be done

**Comment by PettitWesley** [comment]
AFAIK, all/most Fluent Bit plugins only support a single instance.

Each time Fluent Bit sees an elasticsearch `[OUTPUT]` configuration, it calls [cb_es_init](https://github.com/fluent/fluent-bit/blob/master/plugins/out_es/es.c#L423).

If you look at the ES config [struct](https://github.com/fluent/fluent-bit/blob/master/plugins/out_es/es.h#L37), there's a single type and index. 

I have not written any native C plugins for Fluent Bit (yet), but multiple configured instances is possible. The AWS Go Plugins can do this; it works by storing a list of configuration structures, and creating a new one each time init is called.

See:
- https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/master/fluent-bit-cloudwatch.go#L34
- https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/blob/master/fluent-bit-cloudwatch.go#L109

Similar code is possible in C.

**Comment by jonaz** [comment]
Just started migration from beats to fluent-bit. But could not complete the migration due to this issue. Have to stick on beats for the time beeing :(

**Comment by PettitWesley** [comment]
@jonaz Sorry my post here is old and might have even been incorrect at the time of writing. You can definitely have multiple ES outputs with the latest versions. Please try multiple output definitions and let me know.

**Comment by jonaz** [comment]
@PettitWesley i misunderstood the issue. This is the issue blocking us: #1340

**Comment by IslamNouh** [comment]
@PettitWesley  we are hitting the same for input plugins, we mainly want to add 2 input mqtt plugins with different buffer limits (Would that be possible out of the box ?)  can you give sample config if possible?
