### ISSUE TITLE
out_stackdriver: HOST header not being added results in metadata and stackdriver API issues

### ISSUE THREAD

**Issue by urtho** [fluent/fluent-bit#1850]
## Bug Report

**Describe the bug**
When out_stackdriver queries metadata.google.internal without HOST header the result is returned as application/text. This causes failure in json parsing of the text token. Also querying stackdriver /v2/entries:write endpoint results in 411 error.

**To Reproduce**
Happens everytime when out_stackdriver is used since the deletion of HOST header in "vanilla" scenario in flb_http_client.c 
 
- metadata query for token
```
[2020/01/01 21:02:43] [error] [oauth2] cannot parse payload:
access_token ...
expires_in 3096
token_type Bearer
```
- /v2/entries:write endpoint
```
[2020/01/01 21:22:39] [debug] [out_stackdriver] HTTP Status=411
[2020/01/01 21:22:39] [ warn] [out_stackdriver] error
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 411 (Length Required)!!1</title>
  <style>
```

**Expected behavior**
HOST header should be present in all HTTP/1.1 calls. 
HTTP Status should result in 200 OK.

**Your Environment**

* Version used: master

**Comment by urtho** [comment]
This can be fixed in out_stackdriver. 
But maybe the HOST header should not be omitted in vanilla scenario anyway ?

```
diff --git a/plugins/out_stackdriver/gce_metadata.c b/plugins/out_stackdriver/gce_metadata.c
index b2e80aa6..c03236ee 100644
--- a/plugins/out_stackdriver/gce_metadata.c
+++ b/plugins/out_stackdriver/gce_metadata.c
@@ -50,7 +50,7 @@ static int fetch_metadata(struct flb_upstream *ctx, char *uri,

     /* Compose HTTP Client request */
     c = flb_http_client(metadata_conn, FLB_HTTP_GET, uri,
-                        "", 0, NULL, 0, NULL, 0);
+                        "", 0, metadata_conn->u->tcp_host, metadata_conn->u->tcp_port, NULL, 0);

     flb_http_buffer_size(c, 4096);

diff --git a/plugins/out_stackdriver/stackdriver.c b/plugins/out_stackdriver/stackdriver.c
index bb9b08bb..d4b48a45 100644
--- a/plugins/out_stackdriver/stackdriver.c
+++ b/plugins/out_stackdriver/stackdriver.c
@@ -648,7 +648,7 @@ static void cb_stackdriver_flush(const void *data, size_t bytes,

     /* Compose HTTP Client request */
     c = flb_http_client(u_conn, FLB_HTTP_POST, FLB_STD_WRITE_URI,
-                        payload_buf, payload_size, NULL, 0, NULL, 0);
+                        payload_buf, payload_size, u_conn->u->tcp_host, u_conn->u->tcp_port, NULL, 0);

     flb_http_buffer_size(c, 4192);
```

**Comment by urtho** [comment]
I have a PR pending for k8s_container resource type support in out_stackdriver once this gets fixed. :D

**Comment by urtho** [comment]
I think that vanilla needs HOST header back :)
metadata queries in filter_kubernetes are broken as well.

**Comment by phiremande** [comment]
https://github.com/fluent/fluent-bit/issues/1836 - similar issue that I have raised for output plugin kafka-rest
