### ISSUE TITLE
Support for proxy for HTTPS

### ISSUE THREAD

**Issue by L3n41c** [fluent/fluent-bit#1860]
**Is your feature request related to a problem? Please describe.**

I’ve recently added in the `out_datadog` plugin the possibility to go through a proxy (#1844).
This work is based on the `flb_http_client` which already provides support for http proxies.
But a user of this plugin is requiring https through the proxy.

The documentation clearly says https proxy is not supported yet: see the [“Proxy” parameter of the `out_http` plugin](https://docs.fluentbit.io/manual/output/http#configuration-parameters).

However, such a thing has already been requested, for ex in #1323 or #1069.

**Describe the solution you'd like**

Should I add the support for https proxy for `out_datadog`, I’d rather implement it in [`flb_http_client`](https://github.com/fluent/fluent-bit/blob/master/src/flb_http_client.c).
This would also require some changes in [`flb_io`](https://github.com/fluent/fluent-bit/blob/e6506b7b5364c77bec186d94e51c4b3b51e6fbac/src/flb_io.c#L67-L197) since, today, [`flb_io_net_connect()`](https://github.com/fluent/fluent-bit/blob/e6506b7b5364c77bec186d94e51c4b3b51e6fbac/src/flb_io.c#L67-L197) does both the TCP connection and the TLS handshake.
In order to support https proxy, we would need to:
* first establish the TCP connection to the proxy, then
* issue a CONNECT command to the proxy, then
* perform the TLS handshake with the server through the connection.

**Describe alternatives you've considered**

I know that the proxy will not be able to introspect the TLS traffic and that it reduces its capabilities but people have use cases for proxying https.

**Additional context**

Does what I described above make sense ? Would it be OK for me to have a look at this ?

**Comment by vbousson** [comment]
Hello. I have users that have the exact same need to use TLS connection (with HTTP out plugin) through an HTTP proxy. We are quite interested to have it implemented / to implement it ourselves. Does some work have been done already on this topic ?
