### ISSUE TITLE
output file donot show chinease character

### ISSUE THREAD

**Issue by paulqi** [fluent/fluent-bit#1865]
## Bug Report

**Describe the bug**

output file is not used to display chinese character, this chinese character like '\u5165\u4f4f\u65e5\u671f' .
the chinese font is normal in this centos 7 system.
i change fluent-bit to fluentd, the chinese font is normal.
 
[INPUT]
        Name              tail
        Tag               a_log
        Path            /p1/code/a.log
        Parser            multiline
        DB                 /p1/code/a.log/flb_a.db
       Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
[OUTPUT]
Name            file
Match          *
Path            /var/log/td-agent/log

```
a_log: [1578630710.779803, {"log_time":"2020-01-10 04:31:50,776","module":"hotelservice.py[line:259]","log_level":"INFO","message":" ROOMID:S25194574$3,\u5165\u4f4f\u65e5\u671f:2020-03-15,**\u4ef7\u683c:-1.0,\u5e93\u5b58**:0","Host":" docker0963","IP":"  10.58.x.63"}]

```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by paulqi** [comment]
Version used:  1.3.5
Configuration:

[INPUT]
Name tail
Tag a_log
Path /p1/code/a.log
Parser multiline
DB /p1/code/a.log/flb_a.db
Mem_Buf_Limit 5MB
Skip_Long_Lines On
Refresh_Interval 10
[OUTPUT]
Name file
Match *
Path /var/log/td-agent/log

Environment name and version (e.g. Kubernetes? What version?):
servers
Server type and version:
virtual machine-- KVM
Operating System and version:
Cnetos 7
Filters and plugins:
input : Tail
output: File

**Comment by nigels-com** [comment]
Is the input file UTF-8 or some other encoding?  Do you know what encoding it is specifically?

**Comment by paulqi** [comment]
the issue does not occur whith fluentd, it only occurs with fluent bit

**Comment by paulqi** [comment]
[root@docker0963 Logs]# file -bi log.log
text/plain; charset=utf-8

**Comment by paulqi** [comment]
> 
> 
> Is the input file UTF-8 or some other encoding? Do you know what encoding it is specifically?
text/plain; charset=utf-8

**Comment by fujimotos** [comment]
This is because `flb_pack_json()` encodes non-ascii characters into codepoints.

https://github.com/fluent/fluent-bit/blob/master/src/flb_utils.c#L596

This is somewhat common behaviour among JSON encoders and
Fluent Bit does not have a toggle to modify the behaviour for now.

To circumvent this issue, you need to use other formats than JSON.
For example, use `ltsv` format instead of JSON as follows:

```ini
[INPUT]
  Name Dummy
  Dummy {"message": "漢字"}

[OUTPUT]
  Name file
  Path output.ltsv
  Format ltsv
```

... then you can have raw unicode characters in the output:

```bash
$ cat output.ltsv
"time":1579235990.000283	"message":"漢字"
"time":1579235991.000494	"message":"漢字"
"time":1579235992.000388	"message":"漢字"
"time":1579235993.000385	"message":"漢字"
"time":1579235994.000368	"message":"漢字"
```

**Comment by paulqi** [comment]
thanks . i change back fluentd to resolve the issue

**Comment by nigels-com** [comment]
@fujimotos fluent-bit is trying here in `flb_utils_write_str` to output ASCII JSON for portability reasons?
(Just curious)

```
/*
 * Write string pointed by 'str' to the destination buffer 'buf'. It's make sure
 * to escape sepecial characters and convert utf-8 byte characters to string
 * representation.
 */
int flb_utils_write_str(char *buf, int *off, size_t size,
                        const char *str, size_t str_len)
{
...
```

**Comment by fujimotos** [comment]
> fluent-bit is trying here in flb_utils_write_str to output ASCII JSON for portability reasons?

@nigels-com I'm guessing so.

As far as I can tell, this is somewhat common behaviour among JSON encoders.
For instance, Python's JSON encoder escapes Unicode characters by default.

```python3
>>> import json
>>> json.dumps({"key": "漢字"})
'{"key": "\\u6f22\\u5b57"}'
```

Admittedly, I'm not fully convinced that this behaviour is suited for our
particular usecase (is it really helpful for users if we escape Unicode?)

Probably we can just outputs raw Unicode characters here. This is just
allowed per JSON spec, and in accordance with Fluentd's behaviour

**Comment by jeremiahlee** [comment]
The [JSON spec](https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) requires UTF-8 support by decoders. As a result, all JSON decoders can handle UTF-8 just as well as they can handle the numeric escape sequences.
