### ISSUE TITLE
Fluent Bit for Microcontrollers

### ISSUE THREAD

**Issue by beriberikix** [fluent/fluent-bit#1868]
Has the project considered supporting tiny embedded microcontrollers? The two main challenges I see are RAM usage and OS dependency. 

At [450KB](https://docs.fluentbit.io/manual/about/fluentd_and_fluentbit), that's more than most embedded systems have for the entire device. Typical devices may have 128K~256K for the OS/runtime, networking and user application. Also, most embedded systems don't have a traditional operating system. They typically have a highly-optimized library called an [RTOS](https://en.wikipedia.org/wiki/Real-time_operating_system). Anything in Fluent Bit that assumes Linux (from stdlib to mmu to networking) won't work or need to be replaced with a smaller variant.

So how might Fluent Bit be able to target embedded system? I can imagine setting [low memory limits](https://docs.fluentbit.io/manual/configuration/memory_usage,) removing any OS dependencies, using more efficient libraries like [newlib](https://en.wikipedia.org/wiki/Newlib) and probably excluding certain features that just can't work in these types of environments.

Is that feasible and something that has been considered?

**Comment by edsiper** [comment]
> Has the project considered supporting tiny embedded microcontrollers? 

Yes

The question has always been: what's the desired feature set for an embedded platform ?

I think if the goal is to have a simple lib with basic API to ingest records in a few end-points we could write something from scratch

**Comment by beriberikix** [comment]
I think that would be useful. In particular, having a standardized Library API. For example, different MCU vendors have their own flavor of logging frameworks ([ex1 ](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v15.2.0%2Flib_nrf_log.html) [ex2](https://docs.zephyrproject.org/latest/reference/logging/index.html)) which could be implemented as inputs and more constrained-friendly output protocols (like MQTT and CoAP.)

**Comment by nigels-com** [comment]
We had some success using fluent-bit with uClibc on embedded ARM.  The three lowest hanging fruit I came across if I recall correctly:

1. FLB_SMALL build mode (-Os)  https://github.com/fluent/fluent-bit/pull/1459
2. Disable TLS, if you can do without the security.  We were considering linked shared-lib curl instead.
3. Disable regex support, it's quite large too.

**Comment by beriberikix** [comment]
@edsiper watching your [cloudnativesummit.online](https://cloudnativesummit.online/) reminded about this discussion! Have you looked into supporting the embedded MCU use case?

**Comment by edsiper** [comment]
@beriberikix thanks for participating :)

since we have our own event loop tied to an OS implementation, I am not confident it will be good for a MCU embedded use case. But I am pretty open to implement any input plugin that can help to connect those devices.

Anyways if stripping down even more Fluent Bit works, happy to help.

**Comment by beriberikix** [comment]
How tightly coupled is the event loop tied to the OS? Any pointers that might help me understand how it is implemented?

The reason I ask is because many embedded applications use a framework, aka RTOS, that provide OS primitives like threads, mutexes, semaphores, etc. Depending how the event loop is implemented, it may be possible to create thin layers that map to the popular implementations, like [mbed](https://os.mbed.com/docs/mbed-os/v5.15/apis/rtos.html), [Zephyr](https://docs.zephyrproject.org/1.9.0/kernel/kernel.html) & [FreeRTOS](https://www.freertos.org/features.html).

**Comment by edsiper** [comment]
on Linux we use epoll(7) and MacOS & BSD we use kqueue.

but for an embedded device like that, which specific features from Fluent BIt are you interested in ? (I want to understand the logging requirements for a such small device)

**Comment by beriberikix** [comment]
I've been thinking more about this lately and I'm still on the fence if it makes sense for Fluent Bit. However, here's the types of things that one might log on an embedded/IoT device in either a healthy or debug mode:

- RTOS info (Thread start, network interface up, etc.)
- System Error (Coredumps, backtraces, variables, registers, etc.)
- Networking metadata (IP, last ping, MAC, subnet, cell tower RSSI, carrier tracing info, etc.)
