### ISSUE TITLE
I want to create elasticsearchindex with ${tag},Does fluentbit have such features? 

### ISSUE THREAD

**Issue by fullee** [fluent/fluent-bit#1871]
**Is your feature request related to a problem? Please describe.**

Multiple Microservices output logs,Distinguish by `tag`, For example, there are two services for user and auth。

```
[OUTPUT]
    Name  es
    Match logtype.*
    Index user
    Type  logtype

[OUTPUT]
    Name  es
    Match logtype.*
    Index auth
    Type  logtype
```

I want to create elasticsearchindex with ${tag},Does fluentbit have such features? 

```
[OUTPUT]
    Name  es
    Match logtype.${tag}
    Index ${tag}
    Type  logtype
```

Adding a new service requires no changes to fluent-bit.conf

**Describe the solution you'd like**
Similar to the `fluentd` variable https://docs.fluentd.org/output/elasticsearch#index_name-optional
`index_name fluentd.${tag}`

**Describe alternatives you've considered**
```
[OUTPUT]
    Name  es
    Match foo.*
    Index user
    Type  logtype

[OUTPUT]
    Name  es
    Match bar.*
    Index auth
    Type  logtype
```

**Additional context**

**Comment by srkiNZ84** [comment]
+1 for this. I was looking to do the same as above, configuring the elasticsearch output to use a different index, depending on which kubernetes namespace the log record came from (based on kubernetes filter).

**Comment by novegit** [comment]
@srkiNZ84  
use the namespace-fieldname (created by the kubernetes-filter) with the _Logstash_Prefix_Key_ option, to create seperate indices per namespace

**Comment by srkiNZ84** [comment]
Ah, yes, I can see how this works now: https://github.com/fluent/fluent-bit/pull/698

Will give it a go. Thank you so much @novegit ! 🙂

**Comment by andye2004** [comment]
OK, stupid question time. I want to use a kubernetes attributes, e.g. `kubernetes.namespace_name`, but when I try to use this for `Logstash_Prefix_Key` nothing happens and it falls back to the setting in `Logstash_Prefix`.

I know this must be simple to do but I'm clearly missing something, any help much appreciated!

**Comment by edsiper** [comment]
The current implementation on Elasticsearch output plugin don't support placeholders in the Logstash_Prefix_Key.

Recently we introduced an internal feature called record_accessor that provides that capability, I will try to expose it for the next release. If you are curious about it flexibility take a look at the same feature exposed in the new rewrite_tag filter:

https://docs.fluentbit.io/manual/v/1.4-dev/pipeline/filters/rewrite-tag

for short: coming soon :)

**Comment by andye2004** [comment]
@edsiper Thanks! That looks like it will solve all the little niggles we currently have. I'm hoping 1.4 will also support #1670? 

Is there any date pencilled in for 1.4 release?

**Comment by test-account-0** [comment]
> OK, stupid question time. I want to use a kubernetes attributes, e.g. `kubernetes.namespace_name`, but when I try to use this for `Logstash_Prefix_Key` nothing happens and it falls back to the setting in `Logstash_Prefix`.
> 
> I know this must be simple to do but I'm clearly missing something, any help much appreciated!

I think You need to have some key in the record and index prefix is going to be the value.
I tried to do it: https://github.com/fluent/fluent-bit/issues/1775#issuecomment-582574843
But it's also not working for me, so I might be wrong.

**Comment by andye2004** [comment]
@test-account-0, thanks for the feedback! Yeah, your solution looks the deal. I did try to use a lua filter but the script wouldn't compile so I gave up in the end and just used the nest filter to lift the kubernetes fields up a layer and then we were good. I'll maybe look at this again when I get a little time.

**Comment by bbarman4u** [comment]
What if we are not using Kubernetes and are just using vanilla docker containers, has any one got it working exactly the way it was stated in the original question using tags ?

**Comment by andrew-shevchyk** [comment]
This improvement is still badly needed. If you use ElasticSearch Data Streams the workaround with `Logstash_Prefix_Key` will not work because of the added date suffix.

**Comment by sparrowt** [comment]
To expand on this for those wondering:
> PS. I used `opensearch` plugin istead, it supports required functionality

the config would look something like this:
```yaml
pipeline:
  ...
  outputs:
    - name: opensearch
      match: '*'
      ...
      index: yourprefix-$TAG-${SOME_ENV_VAR}-yoursuffix
```
Using the above config on Fluent Bit 3.2.7 it works and the index name in Elastic is `yourprefix-TheTagValue-TheEnvVarValue-yoursuffix` 🎉

This took me _way_ too long to figure out, especially due to the undocumented upper-case `$TAG` which I did not notice until carefully re-reading the previous message in this thread (`$tag` lower-case does not work, because 'tag' is not a field on the record - you can add it like [this](https://github.com/fluent/fluent-bit/discussions/8657#discussioncomment-12351065) but it turns out you can just use `$TAG` instead).
