### ISSUE TITLE
[elasticsearch output] Create template

### ISSUE THREAD

**Issue by naseemkullah** [fluent/fluent-bit#1872]
**Is your feature request related to a problem? Please describe.**
When using fluent bit, we have to manually manage template creation, whereas other log forwarders like logstash and filebeat can do this.
See: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-template.html for an example of how filebeat does it.

**Describe the solution you'd like**
I'd like a way to manage/configure templates through the es output plugin of fluent bit.

**Describe alternatives you've considered**
Switching over to filebeat, or continuing to manually manage these.

**Comment by amitsaha** [comment]
We have a setup where we are using fluent-bit to forward logs to an ES cluster. It is dynamically created an index using logstash prefix. This is good, but a problem appears if I want to force a certain data type for a certain field in the document. I believe this will really help here.

**Comment by zlosim** [comment]
+1

**Comment by jazoom** [comment]
I believe this is also the solution to allowing automatically adding an index management policy, such as deleting old logs.

Example: https://discuss.opendistrocommunity.dev/t/can-you-automatically-manage-indices/2034

**Comment by RainingNight** [comment]
Any news?
