### ISSUE TITLE
JSON parsing

### ISSUE THREAD

**Issue by g3kr** [fluent/fluent-bit#1877]
This is my log message before parsing:

> {
> "container_id": "14927aae39875c1cbdae3e41e6a25b19968aba3f24f09404e76190ef61670202",
> "container_name": "/ecs-LogisticsLDWtest-Logistics-17-LogisticsLDWtest-Logistics-cef884afc6c2dbe0db01",
> "ec2_instance_id": "i-0a1e58472dc0e9e96",
> "ecs_cluster": "LDWtest-Logistics",
> "ecs_task_arn": "arn:aws:ecs:us-west-2:418338086575:task/5372b32a-0894-464d-9da1-601ba33fe77d",
> "ecs_task_definition": "LogisticsLDWtest-Logistics:5",
> "log": "{"thread":"http-nginx-8080-exec-3","level":"INFO","loggerName":"com.enterprise.cloud.Logistics.api.v1.KafkaConsumerV1","reqMsg":"{\"requestId\" : \"45da14d9-bbb2-4906-988c-9e8aead17f59\", \"message\" : \"Request to list consumer details.\"}","endOfBatch":false,"loggerFqcn":"org.apache.log4j.Category","instant":{"epochSecond":1578674283,"nanoOfSecond":74902000},"contextMap":{},"threadId":23,"threadPriority":5}\r",
> "source": "stdout"
> }

Then with JSON parsing it looks like this if I only use the  **json** parser

> {
> "container_id": "14927aae39875c1cbdae3e41e6a25b19968aba3f24f09404e76190ef61670202",
> "container_name": "/ecs-LogisticsLDWtest-Logistics-17-LogisticsLDWtest-Logistics-cef884afc6c2dbe0db01",
> "contextMap": {},
> "ec2_instance_id": "i-0a1e58472dc0e9e96",
> "ecs_cluster": "LDWtest-Logistics",
> "ecs_task_arn": "arn:aws:ecs:us-west-2:418338086575:task/5372b32a-0894-464d-9da1-601ba33fe77d",
> "ecs_task_definition": "LogisticsLDWtest-Logistics:5",
> "endOfBatch": false,
> "instant": {
> "epochSecond": 1578690446,
> "nanoOfSecond": 571551000
> },
> "level": "INFO",
> "loggerFqcn": "org.apache.log4j.Category",
> "loggerName": "com.enterprise.cloud.Logistics.api.v1.KafkaConsumerV1",
> "reqMsg": "{"requestId" : "45da14d9-bbb2-4906-988c-9e8aead17f59", "message" : "Request to list consumer details."}",
> "source": "stdout",
> "thread": "http-nginx-8080-exec-3",
> "threadId": 23,
> "threadPriority": 5
> }
> 

The reqMsg field is JSON in itself and I am not sure why this is not getting formatted as JSON. Is there a different parser I need to use or a different regex to parse this? Any help is appreciated.

I tried with the following custom-parsers.conf

> [PARSER]
> Name json
> Format json
> Time_Key time
> Time_Format %d/%b/%Y:%H:%M:%S %z
> Decode_Field_As json message
> 
> [PARSER]
> Name docker
> Format json
> Time_Key time
> Time_Format %Y-%m-%dT%H:%M:%S.%L
> Time_Keep On
> Decode_Field_As escaped log
> Decode_Field_As escaped reqMsg

I tried both **json** and **escaped** decoder types here

and the fluent-bit.conf is as below

> [SERVICE]
> Parsers_File /fluent-bit/parsers/custom-parsers.conf
> Flush 1
> Grace 30
> [FILTER]
> Name parser
> Match *
> Key_Name log
> Parser json
> Reserve_Data True
> [FILTER]
> Name parser
> Match *
> Key_Name log
> Parser docker
> Reserve_Data True

**Comment by edsiper** [comment]
looks like your original JSON message is bad formed. validate it first with https://jsonlint.com/

**Comment by g3kr** [comment]
I was able to work around this with the following fluent-bit.conf 

```
[SERVICE]
    Parsers_File /fluent-bit/parsers/test_custom.conf
    Flush 1
    Grace 30

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser docker
    Reserve_Data True

[FILTER]
    Name parser
    Match *
    Key_Name reqMsg
    Parser docker
    Reserve_Data True
```

and the `test_custom.conf`

```
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
    # --
    # Since Fluent Bit v1.2, if you are parsing Docker logs and using
    # the Kubernetes filter, it's not longer required to decode the
    # 'log' key.
    #
    # Command      |  Decoder | Field | Optional Action
    # =============|==================|=================
    Decode_Field_As    json     log
```
