### ISSUE TITLE
404 on prometheus metrics endpoint

### ISSUE THREAD

**Issue by rmacian** [fluent/fluent-bit#1884]
## Bug Report

**Describe the bug**
One pod from a daemonset is marked as not ready beacuse it fails its readiness probe

**To Reproduce**
Use the readiness probe in a DaemonSet as described in https://github.com/fluent/fluent-bit-kubernetes-logging/blob/1cdfc96be5c265364095d5b3525c5d992a320aa9/output/kafka/fluent-bit-ds.yaml#L30

**Expected behavior**
The readiness probe should not fail

**Your Environment**
Openshift 3.11 
Fluentbit 1.3.5

**Additional context**
In my case I have 4 pods running in the daemonset and only one is failing. If I perform a curl to the failing pod it returns a 404 error
```
fluent-bit-p6trq       0/1       Running   0          22m       192.168.241.112
```
The api is up
```
curl  http://192.168.241.112:2020/api/v1 -v
* About to connect() to 192.168.241.112 port 2020 (#0)
*   Trying 192.168.241.112...
* Connected to 192.168.241.112 (192.168.241.112) port 2020 (#0)
> GET /api/v1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.241.112:2020
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Monkey/1.7.0
< Date: Thu, 16 Jan 2020 11:57:50 GMT
< Transfer-Encoding: chunked
<
* Connection #0 to host 192.168.241.112 left intact
{"fluent-bit":{"version":"1.3.5","edition":"Community","flags":["FLB_HAVE_PARSER","FLB_HAVE_RECORD_ACCESSOR","FLB_HAVE_STREAM_PROCESSOR","FLB_HAVE_TLS","FLB_HAVE_SQLDB","FLB_HAVE_METRICS","FLB_HAVE_HTTP_SERVER","FLB_HAVE_SYSTEMD","FLB_HAVE_FORK","FLB_HAVE_TIMESPEC_GET","FLB_HAVE_GMTOFF","FLB_HAVE_UNIX_SOCKET","FLB_HAVE_PROXY_GO","FLB_HAVE_SYSTEM_STRPTIME","FLB_HAVE_JEMALLOC","FLB_HAVE_LIBBACKTRACE","FLB_HAVE_REGEX","FLB_HAVE_LUAJIT","FLB_HAVE_C_TLS","FLB_HAVE_ACCEPT4","FLB_HAVE_INOTIFY"]}}
```
But the prometheus endpoint does not 

```
curl  http://192.168.241.112:2020/api/v1/metrics/prometheus -v
* About to connect() to 192.168.241.112 port 2020 (#0)
*   Trying 192.168.241.112...
* Connected to 192.168.241.112 (192.168.241.112) port 2020 (#0)
> GET /api/v1/metrics/prometheus HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.241.112:2020
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: Monkey/1.7.0
< Date: Thu, 16 Jan 2020 11:59:07 GMT
< Transfer-Encoding: chunked
<
* Connection #0 to host 192.168.241.112 left intact
```

set the logging to default but there are no errors:
```
Fluent Bit v1.3.5
Copyright (C) Treasure Data

[2020/01/16 12:26:23] [debug] [storage] [cio stream] new stream registered: tail.0
[2020/01/16 12:26:23] [debug] [storage] [cio stream] new stream registered: tail.1
[2020/01/16 12:26:23] [debug] [storage] [cio stream] new stream registered: tail.2
[2020/01/16 12:26:23] [debug] [storage] [cio stream] new stream registered: tail.3
[2020/01/16 12:26:23] [ info] [storage] initializing...
[2020/01/16 12:26:23] [ info] [storage] in-memory
[2020/01/16 12:26:23] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/01/16 12:26:23] [ info] [engine] started (pid=1)
[2020/01/16 12:26:23] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2020/01/16 12:26:23] [debug] [in_tail] inotify watch fd=20
[2020/01/16 12:26:23] [debug] [in_tail] scanning path /var/log/containers/*_ns1_*.log
[2020/01/16 12:26:23] [debug] [in_tail] Cannot read info from: /var/log/containers/*_ns1_*.log
[2020/01/16 12:26:23] [debug] [in_tail] inotify watch fd=26
[2020/01/16 12:26:23] [debug] [in_tail] scanning path /var/log/containers/*_ns2_*.log
[2020/01/16 12:26:23] [debug] [in_tail] Cannot read info from: /var/log/containers/*_ns2_*.log
[2020/01/16 12:26:23] [debug] [in_tail] inotify watch fd=32
[2020/01/16 12:26:23] [debug] [in_tail] scanning path /var/log/containers/*_ns3_*.log
[2020/01/16 12:26:23] [debug] [in_tail] add to scan queue /var/log/containers/rpp-7-r72kw_ns3_rap-c68718b206170c12c1bf76a6ecd336534a39ec90192de00a339f876f7cddd354.log, offset=11141072
[2020/01/16 12:26:23] [debug] [in_tail] inotify watch fd=39
[2020/01/16 12:26:23] [debug] [in_tail] scanning path /var/log/containers/*_orchestrator_*.log
[2020/01/16 12:26:23] [debug] [in_tail] add to scan queue /var/log/containers/api-gw-12-lfk5k_orchestrator_api-gw-54384fc2175d084179bc15684aae6c2ad06ced314969c911cd4978fb2dbdbe2b.log, offset=32675
[2020/01/16 12:26:23] [debug] [upstream_ha] opening file /fluent-bit/etc/..2020_01_16_12_26_16.289066575/upstream.conf
[2020/01/16 12:26:23] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2020/01/16 12:26:23] [ info] [filter_kube] local POD info OK
[2020/01/16 12:26:23] [ info] [filter_kube] testing connectivity with API server...
[2020/01/16 12:26:23] [debug] [filter_kube] API Server (ns=logging, pod=fluent-bit-srhn7) http_do=0, HTTP Status: 200
[2020/01/16 12:26:23] [ info] [filter_kube] API server connectivity OK
[2020/01/16 12:26:23] [debug] [router] match rule tail.0:forward.0
[2020/01/16 12:26:23] [debug] [router] match rule tail.0:forward.1
[2020/01/16 12:26:23] [debug] [router] match rule tail.1:forward.0
[2020/01/16 12:26:23] [debug] [router] match rule tail.1:forward.1
[2020/01/16 12:26:23] [debug] [router] match rule tail.2:forward.0
[2020/01/16 12:26:23] [debug] [router] match rule tail.2:forward.1
[2020/01/16 12:26:23] [debug] [router] match rule tail.3:forward.0
[2020/01/16 12:26:23] [debug] [router] match rule tail.3:forward.1
[2020/01/16 12:26:23] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2020/01/16 12:26:23] [ info] [sp] stream processor started
```

**Comment by edsiper** [comment]
are you using one of our official Docker images or did you build it from scratch ?

**Comment by rmacian** [comment]
Yes, I've been on official images always, this behaviour is not consistent. At first only 1 of 4 pods were failing, actually are 3 of 4. Indeed in another environment I have running 4/4. I've deleted the daemonset and redeployed everything again but I can't see anything. Is there any way to log the prometheus plugin ? I've tryed 1.3.5, 1.3.6 and 1.3.2. 
I also tryed to add a initdelay and been playing with the thresholds to see if the probes are giving up but is not the case

**Comment by edsiper** [comment]
hmm what do you get with this enpoint ? ```http://192.168.241.112:2020/api/v1/metrics```

**Comment by rmacian** [comment]
also a 404

**Comment by edsiper** [comment]
Run /fluent-bit/bin/fluent-bit -h and paste the full output

**Comment by rmacian** [comment]
`oc exec fluent-bit-7st77 --  /fluent-bit/bin/fluent-bit -h
Usage: fluent-bit [OPTION]

Available Options
  -b  --storage_path=PATH	specify a storage buffering path
  -c  --config=FILE	specify an optional configuration file
  -d, --daemon		run Fluent Bit in background mode
  -f, --flush=SECONDS	flush timeout in seconds (default: 5)
  -F  --filter=FILTER	 set a filter
  -i, --input=INPUT	set an input
  -m, --match=MATCH	set plugin match, same as '-p match=abc'
  -o, --output=OUTPUT	set an output
  -p, --prop="A=B"	set plugin configuration property
  -R, --parser=FILE	specify a parser configuration file
  -e, --plugin=FILE	load an external plugin (shared lib)
  -l, --log_file=FILE	write log info to a file
  -t, --tag=TAG		set plugin tag, same as '-p tag=abc'
  -T, --sp-task=SQL	define a stream processor task
  -v, --verbose		enable verbose mode
  -H, --http		enable monitoring HTTP server
  -P, --port		set HTTP server TCP port (default: 2020)
  -s, --coro_stack_size	Set coroutines stack size in bytes (default: 24576)
  -q, --quiet		quiet mode
  -S, --sosreport	support report for Enterprise customers
  -V, --version		show version number
  -h, --help		print this help

Inputs
  cpu                   CPU Usage
  mem                   Memory Usage
  thermal               Thermal
  kmsg                  Kernel Log Buffer
  proc                  Check Process health
  disk                  Diskstats
  systemd               Systemd (Journal) reader
  netif                 Network Interface Usage
  docker                Docker containers metrics
  tail                  Tail files
  dummy                 Generate dummy data
  head                  Head Input
  health                Check TCP server health
  collectd              collectd input plugin
  serial                Serial input
  stdin                 Standard Input
  syslog                Syslog
  exec                  Exec Input
  tcp                   TCP
  mqtt                  MQTT, listen for Publish messages
  forward               Fluentd in-forward
  random                Random

Outputs
  azure                 Send events to Azure HTTP Event Collector
  bigquery              Send events to BigQuery via streaming insert
  counter               Records counter
  datadog               Send events to DataDog HTTP Event Collector
  es                    Elasticsearch
  exit                  Exit after a number of flushes (test purposes)
  file                  Generate log file
  forward               Forward (Fluentd protocol)
  http                  HTTP Output
  influxdb              InfluxDB Time Series
  kafka                 Kafka
  kafka-rest            Kafka REST Proxy
  nats                  NATS Server
  null                  Throws away events
  plot                  Generate data file for GNU Plot
  splunk                Send events to Splunk HTTP Event Collector
  stackdriver           Send events to Google Stackdriver Logging
  stdout                Prints events to STDOUT
  tcp                   TCP Output
  td                    Treasure Data
  flowcounter           FlowCounter
  gelf                  GELF Output

Filters
  stdout                Filter events to STDOUT
  throttle              Throttle messages using sliding window algorithm
  grep                  grep events by specified field values
  kubernetes            Filter to append Kubernetes metadata
  parser                Parse events
  nest                  nest events by specified field values
  modify                modify records by applying rules
  lua                   Lua Scripting Filter
  record_modifier       modify record

Internal
 Event Loop  = epoll
 Build Flags =  FLB_HAVE_PARSER FLB_HAVE_RECORD_ACCESSOR FLB_HAVE_STREAM_PROCESSOR JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_METRICS FLB_HAVE_HTTP_SERVER FLB_HAVE_SYSTEMD FLB_HAVE_FORK FLB_HAVE_TIMESPEC_GET FLB_HAVE_GMTOFF FLB_HAVE_UNIX_SOCKET FLB_HAVE_PROXY_GO FLB_HAVE_SYSTEM_STRPTIME FLB_HAVE_JEMALLOC JEMALLOC_MANGLE FLB_HAVE_LIBBACKTRACE FLB_HAVE_REGEX FLB_HAVE_LUAJIT FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY`

**Comment by edsiper** [comment]
Very strange, the metrics are enabled, not sure why you get 404 , I will take a look at the code (first time I see this issue)

**Comment by rmacian** [comment]
The HTTP server cannot print its logs?

**Comment by edsiper** [comment]
The only case that it returns 404 is when there are no metrics reported (I will make sure to add a debug message)

Please paste your full config map

**Comment by rmacian** [comment]
It would be nice to have some debug messages 

How is this 'no metrics reported' condition met? I was cleaning some unused configs (filters and parsers) before posting and I restarted the pod and the metrics are working now. I've rolled back the changes and the pod is still starting ok so it's like there is something non related with the config. 

I will track the pods and restart them randomly during the weekend to see what happens.

**Comment by rmacian** [comment]
I think I will close this and reopen it if occurs again. I have deleted them many times and now is working fine.

**Comment by rmacian** [comment]
We are again on the same problem after some config changes:

`oc get pods -o wide
NAME                   READY     STATUS    RESTARTS   AGE       IP                NODE                                                       NOMINATED NODE
fluent-bit-jddnq       1/1       Running   0          1m        192.168.241.105   vepfoanvllbo002.mycompany.com   <none>
fluent-bit-ktd59       1/1       Running   0          1m        192.168.240.6     vepfoanvllbo001.mycompany.com   <none>
fluent-bit-lpmll       1/1       Running   0          1m        192.168.251.56    vepboanvllbo001.mycompany.com   <none>
fluent-bit-m78wf       0/1       Running   0          1m        192.168.250.21    vepboanvllbo002.mycompany.com   <none>`

and

`curl http://192.168.250.21:2020/api/v1/metrics/prometheus -v
* About to connect() to 192.168.250.21 port 2020 (#0)
*   Trying 192.168.250.21...
* Connected to 192.168.250.21 (192.168.250.21) port 2020 (#0)
> GET /api/v1/metrics/prometheus HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.250.21:2020
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: Monkey/1.7.0
< Date: Thu, 13 Feb 2020 10:36:12 GMT
< Transfer-Encoding: chunked
<
* Connection #0 to host 192.168.250.21 left intact`

**Comment by rmacian** [comment]
Some clue:

The node where was failing was by far the node with more pods. So more logs to process. I have defined a DB for each namespace

```
root@vepboanvllbo002:/var/log # ls -lah flb*
-rw-r--r--. 1 root root 576K Jan  9 17:16 flb_kube.db
-rw-r--r--. 1 root root  64K Feb 13 12:10 flb_kube_gvp.db
-rw-r--r--. 1 root root 8.0K Feb 13 04:44 flb_kube_gvp-redis-cluster.db
-rw-r--r--. 1 root root  28K Feb 13 12:10 flb_kube_orquestador-dev.db
-rw-r--r--. 1 root root 8.0K Jan  9 17:16 flb_kube_rap.db
-rw-r--r--. 1 root root  16K Feb 13 12:10 flb_kube_tid.db
-rw-r--r--. 1 root root 8.0K Jan  9 17:16 flb_kube_uux.db
root@vepboanvllbo002:/var/log # file flb_kube.db
flb_kube.db: SQLite 3.x database
```
So perhaps the pod was having some trouble with any of these files but We have not any clue in the logs and We cannot rsh on the pods because of the distroless. So the only thing I could do was delete the db and start from scratch
```
root@vepboanvllbo002:/var/log # rm -rf flb_kube*
root@vepboanvllbo002:/var/log # ls -lah flb*
ls: cannot access flb*: No such file or directory
```
and restart the pods
```
root@vepboanvllbo002:/var/log # ls -lah flb*
-rw-r--r--. 1 root root  16K Feb 13 12:16 flb_kube_gvp.db
-rw-r--r--. 1 root root 8.0K Feb 13 12:16 flb_kube_gvp-redis-cluster.db
-rw-r--r--. 1 root root 8.0K Feb 13 12:16 flb_kube_orquestador-dev.db
-rw-r--r--. 1 root root 8.0K Feb 13 12:15 flb_kube_rap.db
-rw-r--r--. 1 root root 8.0K Feb 13 12:16 flb_kube_tid.db
-rw-r--r--. 1 root root 8.0K Feb 13 12:15 flb_kube_uux.db
```
Now the prometheus endpoint is responding. So the question is, there was a corrupted file or I had lots and lots of logs  pending to forward and entered in a loop state where I cannot flush anything ?

**Comment by rmacian** [comment]
this is the configmap:

```
kind: ConfigMap
apiVersion: v1
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     ${FLB_LOG_LVL}
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Streams_File stream_processor.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-stdout.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*_tit_*.log
        Parser            docker
        DB                /var/log/flb_kube_tit.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*_ubx_*.log
        Parser            docker
        DB                /var/log/flb_kube_ubx.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*_rap_*.log
        Parser            docker
        DB                /var/log/flb_kube_rap.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*_orquestador-dev_*.log
        Parser            docker
        DB                /var/log/flb_kube_orquestador-dev.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*_gvc_*.log
        Parser            docker
        DB                /var/log/flb_kube_gvc.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*_gvc-redis-cluster_*.log
        Parser            docker
        DB                /var/log/flb_kube_gvc-redis-cluster.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  output-stdout.conf: |
    [OUTPUT]
        Name          forward
        Match         kube.*
        Upstream      upstream.conf
    # For debug purposes:
    #[OUTPUT]
    #    Name          forward
    #    Match         kube.var.log.containers.gvc-redis-cluster*
    #    Host          td-agent-bit.logging.svc.cluster.local
    #[OUTPUT]
    #    Name   stdout
    #    Match  *
    #    Format json_lines
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
  stream_processor.conf: |
    #[STREAM_TASK]
      #Name   kubernetes_test
      #Exec   CREATE STREAM kube WITH (tag='results') AS SELECT kubernetes,message from STREAM:fluentd;
  upstream.conf: |
    [UPSTREAM]
        name       forward-balancing
    [NODE]
        name       fluent1
        host       10.Y.194.30
        port       24224
    [NODE]
        name       fluent2
        host       10.X.194.32
        port       24224
```

**Comment by edsiper** [comment]
I had a Zoom meeting with Raul, this is no longer an issue. Fixed.

**Comment by rarruda** [comment]
We had the same issue ourselves. We solved it by increasing the number of readiness retries (`failureThreshold`) and `initialDelaySeconds`:

```
            failureThreshold: 6
            initialDelaySeconds: 20
            periodSeconds: 10
```

We also had to adjust the `initialDelaySeconds` to `210` in the `liveness` probes.

Seems like if the metrics buffer does not get populated, then these endpoints return `404` (both for `cb_metrics_prometheus()` / `/api/v1/metrics/prometheus` and  `cb_metrics()` / `/api/v1/metrics`):
https://github.com/fluent/fluent-bit/blob/1c4c200aa459dcd258746cd7fb25c07d44eba735/src/http_server/api/v1/metrics.c#L244-L249

For us, this was the case in the one node which had a larger number of files.

Leaving this note here just in case someone else has the same issue.

**Comment by kosyachniy** [comment]
> I had a Zoom meeting with Raul, this is no longer an issue. Fixed.

And what is the solution??!
What have you done?

**Comment by kosyachniy** [comment]
@edsiper

**Comment by tgrondier** [comment]
Also interested in knowing the fix, @edsiper / @rmacian

**Comment by rbitkuri** [comment]
@tgrondier what was the fix ? I am facing same error

**Comment by leonardo-albertovich** [comment]
Hello @rbitkuri , this is a very old issue related to fluent-bit 1.3. I just tested it in the current version and it worked as expected so if you are having issues with it I think you should open a new issue so we can properly address your particular case.

Same goes for @kosyachniy and @tgrondier of course.

**Comment by DutchEllie** [comment]
What was the solution 😭
