### ISSUE TITLE
Can't forward logs to Elasticsearch hosted on AWS

### ISSUE THREAD

**Issue by daparthi001** [fluent/fluent-bit#1887]
## Bug Report

Fluent-bit not able to send logs to aws hosted elastic search ,which port and url should be configured as the elastic serach host ?

$ kubectl logs pod/fluent-bit-9w82n -n logging
Fluent Bit v1.3.5
Copyright (C) Treasure Data

[2020/01/17 16:09:39] [ info] [storage] initializing...
[2020/01/17 16:09:39] [ info] [storage] in-memory
[2020/01/17 16:09:39] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/01/17 16:09:39] [ info] [engine] started (pid=1)
[2020/01/17 16:09:39] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2020/01/17 16:09:39] [ info] [filter_kube] local POD info OK
[2020/01/17 16:09:39] [ info] [filter_kube] testing connectivity with API server...
[2020/01/17 16:09:39] [ info] [filter_kube] API server connectivity OK
[2020/01/17 16:09:39] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2020/01/17 16:09:39] [ info] [sp] stream processor started

**Comment by PettitWesley** [comment]
Hey @daparthi001, I can try to help.

One thing first, your output does not help us very much- it just shows output from the kubernetes filter, not the elasticsearch plugin. Can you update the output?

As far as AWS/Amazon ElasticSearch goes, please note that if you require IAM authentication on your ES endpoint, you can't send logs to it from Fluent Bit. I am working on implementing IAM/Sigv4 Auth in the ElasticSearch plugin- though it will probably not make it into the next release. See #1804 and #1807 

> which port and url should be configured

Assuming auth is not your problem, you can find the host listed as "VPC endpoint" in the Amazon ElasticSearch Console when you select your domain. For the port, I use 443 and that works.

**Comment by PettitWesley** [comment]
Also, please change the title of the issue to something that describes the problem, for the benefit of others who may have the same question.

**Comment by PettitWesley** [comment]
See docs here: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch##aws-es

Re-open if you need more help.

**Comment by TarunAdityaRazor** [comment]
I was getting this error:
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet because no resource-based policy allows the es:ESHttpGet action"}

1) Fluenbit is not sending logs to the cluster
2) I am not able to access the dashboard.
could anyone please helpout.

My access policy:
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::257915852743:role/FluentBitOpenSearchRole"
            },
            "Action": "*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "es:*",
            "Resource": "*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "My-IP"
                    ]
                }
            }
        }
    ]
})

**Comment by TarunAdityaRazor** [comment]
And also please do explain how to sign the request for the IAM role.
