### ISSUE TITLE
Tail plugin : Path does not support nested wild card characters [ Windows ]

### ISSUE THREAD

**Issue by bragi92** [fluent/fluent-bit#1888]
## Bug Report

**Describe the bug**
Using nested wild cards in the Path gives the following error:

`[in_tail] Cannot read info from: C:\ProgramData\Docker\containers\**\*.log`

Running `dir **/*` in powershell works as expected and it lists out the said log files.

In Linux all '/var/log/containers/*.log' works as it searches the sub directories for log files too.

P.S. I've tried */*.log, *.log and it did not work for me.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
`[in_tail] Cannot read info from: C:\ProgramData\Docker\containers\**\*.log`
```
- Steps to reproduce the problem:

**Expected behavior**
I expect Path should be able to recursively search for *.log files in the location that I'm pointing to similar to how `dir` does it.

**Screenshots**

**Your Environment**

* Version used:
The current fluent-bit for windows exe on the official site: https://docs.fluentbit.io/manual/installation/windows gives an error related to missing DLL files.

I'm using the 64 bit version shared by @fujimotos : https://github.com/fluent/fluent-bit/issues/960#issuecomment-571906226 

* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

I'm trying to tail all of the docker container logs using fluent-bit for windows on a machine.

**Comment by fujimotos** [comment]
@bragi92 Thanks for your feedback.

> Using nested wild cards in the Path gives the following error:
> `[in_tail] Cannot read info from: C:\ProgramData\Docker\containers\**\*.log`

Yes, it's because we don't have a full support for wildcard path on WIndows.

This feature really should be implemented, but we are not getting there yet.
I'll follow up this issue, so please wait for me.

**Comment by bragi92** [comment]
Sorry for the delayed reply.

I see that the problem is caused [here](https://github.com/bragi92/fluent-bit/blob/master/plugins/in_tail/tail_scan_glob.c#L238) since do_glob function isn't able to understand the path. I will try to figure out what it would take to make it work and post back

**Comment by fujimotos** [comment]
Thank you for taking a look at the code.

> I see that the problem is caused here since do_glob function isn't able to understand the path. I will try to figure out what it would take to make it work and post back

Things are a bit more complicated since our Windows build does not rely
on `tail_scan_glob.c` (this is because Windows does not provide `glob.h`).
and it uses `tail_scan_win32.c` instead.

I spent this evening to prepare a fix proposal for this issue. Here is the branch
that contains the fix.

https://github.com/fujimotos/fluent-bit/commits/sf/win32-tail-glob

@bragi92 Can you check it out, and see if it works for your usecase?
If you can confirm it works fine, I think I can make it a pull request.

**Comment by bragi92** [comment]
@fujimotos Thanks for looking into this! ^_^ I would love to test the fix. 

Where can I find the fluent bit exe (64 bit) for this?

**Comment by fujimotos** [comment]
> Where can I find the fluent bit exe (64 bit) for this?

Wait for me. I think I can find some time to prepare a test build tomorrow.

**Comment by bragi92** [comment]
Sounds good, I'll wait for the test build.

**Comment by fujimotos** [comment]
@bragi92 Here is the test build that contains this fix.

* Development tip: f827dd26
* [32-bit installer for Windows](https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/30328472/job/mxugc4m7dko3dfqu/artifacts)
* [64-bit installer for Windows](https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/30328472/job/w5eq2xi6cr8uuj06/artifacts)

If it works as expected, I appreciate if you could comment back to #1906.
That will help the review process and make it easier to merge into main.

**Comment by bragi92** [comment]
Perfect, I'll report back here and in https://github.com/fluent/fluent-bit/pull/1906 once I'm able to test it.

**Comment by bragi92** [comment]
I used the 64-bit installer for Windows provided above and can confirm from my testing that inputs of the following format work as expected:

[INPUT]
  Name tail
  Tag  app.log
  Path C:\myapp\*\*.log


[INPUT]
  Name tail
  Tag  app.log
  Path C:\myapp\**\*.log


Thanks @fujimotos for the quick change. I'm closing this issue now.

**Comment by bragi92** [comment]
@fujimotos

I'm trying to containerize it by running it inside a nanoserver powershell image:  mcr.microsoft.com/powershell:preview-nanoserver-1903 but it doesn't seem to be working.
Running the dummy plugin does not give any result:
PS C:\>$url = "https://ci.appveyor.com/api/buildjobs/mnteb3875c92eb53/artifacts/build%2Ftd-agent-bit-1.4.0-win64.exe"
PS C:\>$output = "td-agent-bit-1.4.0-win64.exe"
PS C:\>Invoke-WebRequest -Uri $url -OutFile $output
PS C:\> .\td-agent-bit-1.4.0-win64.exe -i dummy -o stdout
PS C:\>
PS C:\> [Environment]::Is64BitOperatingSystem
True
Any idea what could be wrong?
