### ISSUE TITLE
tail multiline: can't parse multiline log

### ISSUE THREAD

**Issue by cronolio** [fluent/fluent-bit#1891]
## Bug Report

**Describe the bug**
fluent-bit didn't create message field but concatenate to previous field

**Your Environment**

* Version used: td-agent-bit 1.3.5
* Configuration:
```
[PARSER]
    Name    head_log
    Format  regex
    Regex   ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) (?<level>[A-Z]+)
    Time_Format %Y-%m-%d %H:%M:%S
    Time_Key time
[PARSER]
    Name    rest_log
    Format  regex
    Regex   (?m-ix)^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) (?<level>[A-Z]+)(?<message>.*)
    Time_Format %Y-%m-%d %H:%M:%S
    Time_Key time
[INPUT]
    Name tail
    Tag  sample.tag
    Path /etc/td-agent-bit/logs/pythonApp.log
    Multiline  On
    Parser_Firstline head_log
    Parser_1 rest_log
```
* Operating System and version:
debian 10
**To Reproduce**
https://rubular.com/r/fAZ2Lhl2y2P0qK
**Log sample**
```
2019-08-01 18:58:05 ERROR
Exception on main handler
Traceback (most recent call last):
  File "python-logger.py", line 9, in make_log
    return word[13]
IndexError: string index out of range
```
**Output**
```
td-agent-bit[1565]: Fluent Bit v1.3.5
td-agent-bit[1565]: Copyright (C) Treasure Data
td-agent-bit[1565]: [2020/01/18 15:22:18] [ info] [storage] initializing...
td-agent-bit[1565]: [2020/01/18 15:22:18] [ info] [storage] in-memory
td-agent-bit[1565]: [2020/01/18 15:22:18] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
td-agent-bit[1565]: [2020/01/18 15:22:18] [ info] [engine] started (pid=1565)
td-agent-bit[1565]: [2020/01/18 15:22:18] [ info] [sp] stream processor started
янв 18 15:22:23 rabcons td-agent-bit[1565]: [0] sample.tag: [1564685885.000000000, {"level"=>"ERROR
td-agent-bit[1565]: Exception on main handler
td-agent-bit[1565]: Traceback (most recent call last):
td-agent-bit[1565]:   File "python-logger.py", line 9, in make_log
td-agent-bit[1565]:     return word[13]
td-agent-bit[1565]: IndexError: string index out of range"}]
```
* **Expected behavior**
message field created and multiline log is there
* **Addition info**
if i'm writing into ```rest_log``` something like ```(?<exception>Exception)(?<message>.*)``` it can create correct exception filed and multiline message field. But exactly i don't know what will be placed in second line.
if i'm writing into ```rest_log``` something like ```(?<message>.*)``` or even ```(?m-ix)(?<message>.*)``` it create multiple message fileds and only last one available in kibana/elastic

**Comment by fujimotos** [comment]
@cronolio  Try the following configuration and see if it works.

**parser.conf**
```ini
[PARSER]
    Name    head_log
    Format  regex
    Regex   ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) (?<log>.+)
    Time_Format %Y-%m-%d %H:%M:%S
    Time_Key time

[PARSER]
    Name    rest_log
    Format  regex
    Regex   (?m-ix)^(?<level>[A-Z]+)\s*(?<message>.*)
```

**fluent-bit.conf**
```ini
[SERVICE]
    Parsers_File parser.conf

[INPUT]
    Name tail
    Tag  sample.tag
    Path conf/1891.txt
    Multiline  On
    Parser_Firstline head_log

[FILTER]
    Name parser
    Match sample.tag
    Key_Name log
    Parser rest_log

[OUTPUT]
    name stdout
```

**Comment by cronolio** [comment]
thank you. yes, it is possible to make it correct via addition filter.

maybe there some way to make all in INPUT notation ?

**Comment by fujimotos** [comment]
> maybe there some way to make all in INPUT notation ?

No, I'm not aware of. I think this is a limitation as of v1.3.6.

Since we don't have a way to express, say, "Please group the next lines into a field"
in the configuration, the best we can do right now is to 1) use `Multiline` to aggregate
lines and 2) split them into fields using an additional parser.

**Comment by cronolio** [comment]
ok , thank you again.
