### ISSUE TITLE
fluent-bit can't read Windows' docker containers' `config.v2.json` files in Kubernetes

### ISSUE THREAD

**Issue by aemengo** [fluent/fluent-bit#1899]
## Bug Report

**Describe the bug**
fluent-bit can't read Windows' docker containers' `config.v2.json` files in Kubernetes.

Fluent bit has the location of config files [hardcoded](https://github.com/fluent/fluent-bit/blob/e6506b7b5364c77bec186d94e51c4b3b51e6fbac/plugins/in_docker/docker.h#L40) to `/var/lib/docker/containers`. This path does not exist on Windows by default. If you mount a hostpath to that path on the container, it results in sym links that fluent-bit is unable to follow. 

We rebuilt fluent-bit having changed that path to `/ProgramData/docker/containers` and that solves the issue.

**To Reproduce**
1. Build fluent-bit docker image for windows (ours is `pivotalgreenhouse/fluent-bit-windows-syslog:latest`)
2. Run in Kubernetes with a volume mount with `hostpath=/programdata/docker/containers` and `mountpath=/var/lib/docker/containers`. Have an input configured to tail `/var/log/containers/*.log` with any output.
3. See that logs from `/var/log/containers/*.log` do not appear in output.

**Expected behavior**
Logs from `/var/log/containers/*.log` to appear in output.

**Your Environment**

* Version used: https://github.com/fluent/fluent-bit/tree/e6506b7b5364c77bec186d94e51c4b3b51e6fbac
* Environment name and version (e.g. Kubernetes? What version?): kubernetes 1.14.6
* Operating System and version: windows 2019
* Filters and plugins: syslog_out, docker_in

**Additional context**
We're trying to forward logs from inside windows containers on kubernetes to papertrail.

cc @jfeeny

**Comment by fujimotos** [comment]
@aemengo Thank you for reporting. 

> We rebuilt fluent-bit having changed that path to /ProgramData/docker/containers and that solves the issue.

Did `in_docker` work on Windows as expected except `DOCKER_LIB_ROOT`?

I'm curious because `in_docker` is pretty much constructed as Linux-specific
plugin (e.g. accessing `/sys/fs/cgroup` for  CPU stats) so I was thinking that it
won't work on Windows platforms without porting its core logic.

If you can share your experience, I'd very appreciate it.

**Comment by aemengo** [comment]
@fujimotos 

```
k -n pks-system log fluent-bit-windows-ckr4g
Fluent Bit v1.4.0
Copyright (C) Treasure Data

2020/01/29 15:49:00 [out_syslog] Initializing plugin pks-windows-sink for namespace pks-system to destination 169.46.82.168:59978
[2020/01/29 15:49:13] [ warn] net_tcp_fd_connect: getaddrinfo(host='kubernetes.default.svc.cluster.local'): No such host is known. 
[2020/01/29 15:49:13] [error] [filter_kube] upstream connection error
[2020/01/29 15:49:13] [ warn] [filter_kube] could not get meta for POD fluent-bit-windows-ckr4g
[2020/01/29 15:49:25] [ warn] net_tcp_fd_connect: getaddrinfo(host='kubernetes.default.svc.cluster.local'): No such host is known. 
[2020/01/29 15:49:25] [error] [filter_kube] upstream connection error
[2020/01/29 15:49:37] [ warn] net_tcp_fd_connect: getaddrinfo(host='kubernetes.default.svc.cluster.local'): No such host is known. 
[2020/01/29 15:49:37] [error] [filter_kube] upstream connection error

**Comment by fujimotos** [comment]
> Yes, we saw our logs get propogated to our syslog destination. It appears to have worked with just one change for windows

@aemengo That's great. Then,. I'm gonna prepare a fix for the issue, so that
we can use `in_docker` on Windows without rebuilds. WFM.
