### ISSUE TITLE
link libfluent-bit.so

### ISSUE THREAD

**Issue by takahasi** [fluent/fluent-bit#190]
Hi,
Could you tell me how to use libfluent-bit.so.

My program cannot link dynamically to libfluent-bit.so.
If I add all static libraries (libfluent-bit.a libflb-plugin-*.a), it will be success.

Is it correct usage?
I think just linking one library is better way.

```
$gcc test.c  -lfluent-bit -lpthread
...
/tmp/ccOjzZSF.o: In fuction `flb_thread_new' :
test.c:(.text+0x324): undefined reference to `flb_errno_print' 
/tmp/ccOjzZSF.o: In function `cb_output_thread_destroy' :
test.c:(.text+0x40b): undefined reference to `flb_worker_ctx'
test.c:(.text+0x41b): undefined reference to `flb_worker_ctx' 
test.c:(.text+0x45b): undefined reference to `flb_log_print' 
```

Thanks,

**Comment by nokute78** [comment]
If you want to use fluent-bit as a dynamic library, you can only use library APIs.
Could you see this document ?
http://fluentbit.io/documentation/0.10/development/library_api.html

And you can also see sample programs at `example` directory.
e.g. 
https://github.com/fluent/fluent-bit/blob/master/examples/hello_world

**Comment by takahasi** [comment]
Thanks.
Sorry for confusing you
I already know those APIs.
In this issue, 
"some headers require to link all plugin's static libraries"

I just use empty C source code.
For example;

```
#include <stdio.h>
#include <fluent-bit.h>
int main()
{
    pritnf("Hello, world.¥n");
    return 0;
} 
```

**Comment by edsiper** [comment]
hmm looks like shared mode requires some work for interfaces added after initial shared version.

**Comment by nokute78** [comment]
@takahasi Thank you for explanation.
I sent a patch to fix this issue.(#192)

This issue is caused by NON-inline functions which are  implemented in "header file".
The function is implemented a test.o and it will be conflicted with libfluent-bit.so.

**Comment by takahasi** [comment]
Thanks, great!
Now it became success.
