### ISSUE TITLE
Debian packages for raspbian buster

### ISSUE THREAD

**Issue by ryan-lane** [fluent/fluent-bit#1905]
Fluentbit is available as debian packages which is great, but there's no arm support. Can arm be added as a target for debian packages? I'm trying to use fluentbit on a raspberry pi, and would like to avoid building it from scratch every time.

**Comment by edsiper** [comment]
Here you can find the instructions to get the packages for Raspbian:

https://docs.fluentbit.io/manual/installation/raspberry_pi

**Comment by ryan-lane** [comment]
Oh this is great! It looks like buster isn't listed in the docs. I'll see
if it's included but the docs are out of date.

**Comment by ryan-lane** [comment]
Ah, yeah, there's no packaging for buster. It looks like the package for stretch installs and likely works for buster, but would nice to have buster specific packaging too :)

**Comment by patrick-stephens** [comment]
This has been done for a while and we will have Bullseye shortly so closing
