### ISSUE TITLE
Containerize fluent-bit for windows (missing dependencies?) does not work as expected.

### ISSUE THREAD

**Issue by bragi92** [fluent/fluent-bit#1908]
I'm using the 64-bit installer for Windows mentioned over here: https://github.com/fluent/fluent-bit/issues/1888#issuecomment-578131452 

It works as expected on my windows machine and is collecting logs from all the containers.

I'm trying to containerize it by running it inside a nanoserver powershell image: `mcr.microsoft.com/powershell:preview-nanoserver-1903` but it doesn't seem to be working.
Running the dummy plugin does not give any result:

From within the container ->
PS C:>$url = "https://ci.appveyor.com/api/buildjobs/mnteb3875c92eb53/artifacts/build%2Ftd-agent-bit-1.4.0-win64.exe"
PS C:>$output = "td-agent-bit-1.4.0-win64.exe"
PS C:>Invoke-WebRequest -Uri $url -OutFile $output
PS C:> .\td-agent-bit-1.4.0-win64.exe -i dummy -o stdout
PS C:>
PS C:> [Environment]::Is64BitOperatingSystem
True
Any idea what could be wrong?
Is there some dependency that I need to bring in my container for fluentd to work?

I also used the `mcr.microsoft.com/powershell:latest` image which is the full blown windows server core image but I'm facing the same issue over.

**Comment by fujimotos** [comment]
Windows Dockerfile is currently under development in #1760 and #1801.
We are currently wainting for revision update from developers, so they
are not merged into mainline yet.

The attached is a minimal Dockerfile that use the precompiled binary on
AppVeyor (created based on @paulbouwer's proposal).

I hope it works for you...

**Example Dockerfile**

```dockerfile
# escape=`

ARG WINDOWS_VERSION=1809

#
# Builder Image - Windows Server Core
# Assemble the components required to run Fluent Bit
#
FROM mcr.microsoft.com/windows/servercore:$WINDOWS_VERSION as builder

ARG FLUENTBIT_URL=https://ci.appveyor.com/api/buildjobs/37lho3xf8j5i6crj/artifacts/build%2Ftd-agent-bit-1.4.0-win64.zip

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Write-Host ('Creating folders'); `
    New-Item -Type Directory -Path /installation; `
    New-Item -Type Directory -Path /fluent-bit;

WORKDIR /installation

RUN Write-Host ('Installing Fluent Bit'); `
    Invoke-WebRequest -Uri $Env:FLUENTBIT_URL -OutFile /installation/td-agent-bit.zip; `
    Expand-Archive -Path /installation/td-agent-bit.zip -Destination /installation/fluent-bit; `
    Move-Item -Path /installation/fluent-bit/*/* -Destination /fluent-bit/;

#
# Technique from https://github.com/StefanScherer/dockerfiles-windows/blob/master/mongo/3.6/Dockerfile
# 
RUN Write-Host ('Installing Visual C++ Redistributable Package'); `
    $ProgressPreference = 'SilentlyContinue'; `
    Invoke-WebRequest -Uri 'https://aka.ms/vs/16/release/vc_redist.x64.exe' -OutFile /installation/vc_redist.x64.exe; `
    $ProgressPreference = 'Continue'; `
    Start-Process /installation/vc_redist.x64.exe -ArgumentList '/install', '/quiet', '/norestart' -NoNewWindow -Wait; `
    Copy-Item -Path /Windows/System32/msvcp140.dll -Destination /fluent-bit/bin; `
    Copy-Item -Path /Windows/System32/vccorlib140.dll -Destination /fluent-bit/bin; `
    Copy-Item -Path /Windows/System32/vcruntime140.dll -Destination /fluent-bit/bin;

#
# Runtime Image - Windows Server Nano
# Run Fluent Bit with appropriate configuration 
#
FROM mcr.microsoft.com/windows/nanoserver:$WINDOWS_VERSION as runtime

COPY --from=builder /fluent-bit /fluent-bit

ENTRYPOINT ["c:\\fluent-bit\\bin\\fluent-bit.exe", "-i", "dummy", "-o", "stdout"]
```

**Comment by bragi92** [comment]
Thanks for the information @fujimotos ! This is very promising and the example setup is working as expected.

I'll modify Dockerfile based on my needs and will test how the tail plugin performs with multiple containers logging at the same time.

**Comment by fujimotos** [comment]
@bragi92  That's nice to hear. Just beware the ZIP files on AppVeyor are
*ephemeral* and automatically deleted after 6 months.

Please change `FLUENTBIT_URL` in Dockerfile to the official ZIP file on
"fluentbit.io" once Fluent Bit v1.4.0 is officially released.
