### ISSUE TITLE
Support for windows servercore:ltsc2019

### ISSUE THREAD

**Issue by leandroandrade-hotmart** [fluent/fluent-bit#1918]
**Is your feature request related to a problem? Please describe.**
I have a k8s cluster with windows pods and i trying to install some app to get logs and send to AWS Kinesis, and in Linux pods i use the DaemonSet option of FluentBit, but for Windows i didnt found any solution yet.

**Describe alternatives you've considered**
I 'm trying to create a Docker image to run in my cluster, but at moment when i run the image, nothing happen. See the code below

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Metadata indicating an image maintainer.

ENV ENV_HOME 'C:'
ENV INSTALL_HOME $ENV_HOME'\install'

# Copy Files to Install
COPY ./fluentbit-kinesis-windows/* /install/
WORKDIR /install

RUN powershell -Command "ls C:\\install"

EXPOSE 2020 

CMD ["powershell","-Command", "C:\\install\\bin\\fluent-bit"]
```

**Additional context**
In the folder fluentbit-kinesis-windows/ there are all files extracted for http://fluentbit.io/releases/1.3/td-agent-bit-1.3.6-win64.zip

Anyone have some idea for this problem?
Thanks

**Comment by fujimotos** [comment]
Dockerfile for Windows is right now under development in #1801 and #1760.
You can check these PRs for working examples of Windows Dockerfile.

**Comment by fujimotos** [comment]
@leandroandrade-hotmart JFYI, Windows Dockerfile support has been merged.

Now you can build a Windows Docker image (servercore:ltsc2019) just by:

     $ docker -f Dockerfile.windows -t fluent-bit .

You can also compile the source by yourself (it takes time though):

     $ docker -f Dockerfile.windows.devel -t fluent-bit-dev .

I'll close this ticket for now; If you have anything unclear, please feel free to tell me.
