### ISSUE TITLE
Error: Invalid output target when using https

### ISSUE THREAD

**Issue by littlesandra88** [fluent/fluent-bit#1922]
## Bug Report

**Describe the bug**
Outputting to an https URI on command line doesn't seam to either work or be supported.

**To Reproduce**
```
$ mytag=example
$ mypath=/tmp/q.log
$ myuri="https://logstash.example.com/log_tst/xxx"
$ fluent-bit -R conf/parsers.conf -i tail -t $mytag -p parser=json -p path=$mypath -p tls=on -p tls.verify=on -o $myuri -o json -P 443 -m $mytag
Error: Invalid output target. Aborting
```

**Expected behavior**
I wanted to send a log using the command line.

I have tried to remove `-o json` and still got the same error.

**Screenshots**
None

**Your Environment**
* Version used: Fluent Bit v1.3.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
None

**Comment by PettitWesley** [comment]
@littlesandra88 I think you have to specify `http` not `https` and then set `tls` to be on.

See this comment in the code: https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_output.h#L81

Something like `https://logstash.example.com/log_tst` isn't actually interpreted as an endpoint. Instead the first bit is the plugin name (and `https` isn't the name of a plugin).
