### ISSUE TITLE
prometheus fluentbit_output_errors_total isn't increasing

### ISSUE THREAD

**Issue by devopsjonas** [fluent/fluent-bit#1935]
## Bug Report

**Describe the bug**

We would like to monitor when fluent-bit is misbehaving.

Currently we have a bunch of fluent-bits failing to push data to elasticsearch due to:

```
 [error] [out_es] could not pack/validate JSON response
{"took":215,"errors":true,"items":[{"index":{"_index":"bobausis-2020.02.07","_type":"flb_type","_id":"PgkhHnABJEiIX347nJyZ","status":400,"error":{"type":"mapper_parsing_exception","reason":"Could not dynamically add mapping for field [app.kubernetes.io/name]. Existing mapping for [kubernetes.labels.app] must be of type object but found [text]."}}},{"index":{"_index":"index-name,"_type":"flb_type","_id":"PwkhHnABJEiIX347nJyZ","status":400,"error":{"type":"mapper_parsing_exception","reason":"Could not dynamically add mapping for field [app.kubernetes.io/name]. Existing mapping for [kubernetes.labels.app] must be of type object but found [text]."}}},{"index":{"_index":"index-name,"_type":"flb_type","_id":"QAkhHnABJEiIX347nJyZ","status":400,"error":{"type":"mapper_parsing_exception","reason":"Could not dynamically add mapping for field [app.kubernetes.io/name]. Existing mapping for [kubernetes.labels.app] m
```

But all of the `fluentbit_output_errors_total` counters are `0`:

```
fluentbit_output_errors_total{controller_revision_hash="779bc6b95b",instance="172.16.129.205:2020",job="kubernetes-pods",k8s_app="fluent-bit-logging",name="es.0",namespace="sys-mon",pod="fluent-bit-cv5mq",pod_template_generation="3"} | 0
....

fluentbit_output_errors_total{controller_revision_hash="779bc6b95b",instance="172.16.135.207:2020",job="kubernetes-pods",k8s_app="fluent-bit-logging",name="es.3",namespace="sys-mon",pod="fluent-bit-7t8qx",pod_template_generation="3"} | 0

```

**To Reproduce**

- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: fluent/fluent-bit:1.3.4
* Configuration:

```
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name              tail
    Tag               kube-container.*
    Path              /var/log/containers/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name        record_modifier
    Match       kube-container.*
    Remove_key  annotations

[FILTER]
    Name                kubernetes
    Match               kube-container.*
    Kube_URL            https://kubernetes.default.svc.cluster.local:443
    Kube_Tag_Prefix     kube-container.var.log.containers.
    K8S-Logging.Parser  On
    K8S-Logging.Exclude true


[OUTPUT]
    Name            es
    Match           kube-container.*
    Host            ${FLUENT_ELASTICSEARCH_HOST}
    Port            ${FLUENT_ELASTICSEARCH_PORT}
    HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
    HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
    Logstash_Format On
    Logstash_Prefix ${FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX}
    Retry_Limit     False

```

* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:Kubernetes v1.15.7
* Operating System and version: CentOS
* Filters and plugins:

**Additional context**

We are scraping `/api/v1/metrics/prometheus` endpoint

I might be wrong but none of the prometheus counters increase when there are issues with fluent-bit and we would love to monitor & alert this using Prometheus, rather than parsing fluent-bit logs, etc.

**Comment by minhdanh** [comment]
Using fluentbit v1.4.2 and can confirm still having this issue as well.

**Comment by yutsengwei** [comment]
is this issue fixed? looking forward to the verification

**Comment by devopsjonas** [comment]
this is not fixed

**Comment by Blaumer** [comment]
looks like this is still an issue

**Comment by sandeepsingh0321** [comment]
I am using the  fluentbit:v1.5  and I still the see same issue

**Comment by davidmukiibi** [comment]
I'm using v1.7.5 and still have the same issue

**Comment by furstenbergs** [comment]
Seeing the same issue on v1.8.3.

**Comment by edsiper** [comment]
assigned to @nokute78

**Comment by nokute78** [comment]
`fluentbit_output_errors_total` will be added when output plugin flush callback returns `FLB_ERROR`.

In this case, the error message ` [error] [out_es] could not pack/validate JSON response` is raised from `elasticsearch_error_check` function.
https://github.com/fluent/fluent-bit/blob/c0a9d555c70e35c26926e480f15162b029f5d492/plugins/out_es/es.c#L634

However, if the function returns an error(it means `ret =FLB_TRUE`), out_es will retry and it returns `FLB_RETRY` not `FLB_ERROR`.
Then the counter is not added.
https://github.com/fluent/fluent-bit/blob/c0a9d555c70e35c26926e480f15162b029f5d492/plugins/out_es/es.c#L844-L858

**Comment by nokute78** [comment]
Should we retry for this error case `[error] [out_es] could not pack/validate JSON response` ?
If not, I will modify out_es to return `FLB_ERROR` in that error case.

**Comment by antoniocascais** [comment]
We are having the same issue here.

Our use case: fluent-bit sends logs to ES that are rejected due to `mapper_parsing_exception`. We would like to be notified when this happens and not have the logs being retried (i mean, retrying them won't solve the issue until someone fixes the field type in ES). 

Shouldn't fluent-bit record an error in this situation?

**Comment by ringerc** [comment]
I've reproduced this for both the s3 and kafka (including Azure Event Hub) plugins.

At least some mis-configurations and error conditions, including wrong DNS endpoint name, wrong bucket name, invalid credentials, etc, result in no increase of any of these metrics for either of the outputs in question:

* `fluentbit_output_errors_total`
* `fluentbit_output_retries_total`
* `fluentbit_output_retries_failed_total`
* `fluentbit_output_dropped_records_total`
* `fluentbit_output_retried_records_total`

and worse, the `fluentbit_output_proc_records_total` and `fluentbit_output_proc_bytes_total` metrics are still incremented, even though the docs state that these are only incremented on successful output.
