### ISSUE TITLE
GSoC2017 / Plugins development and extend Golang interface

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#194]
This issue belongs to a Google Summer of Code project idea. 

## Project Goals

This project idea aims to extend the current number of plugins available on Fluent Bit and fix the current ones to make them work in multi platforms, some of the requirements are:

- in_cpu: routines to gather CPU stats from OSX
- in_proc: add process stats for OSX
- in_disk: add disk stats for OSX
- in_mem: routines to gather memory stats from OSX
- in_syslog: implement syslog TCP input plugin
- out_kafka: implement output plugin to deliver logs/data to a Kafka Server
- Golang interface: extend golang support to give access to Fluent Bit internals. 
- Others.

The project ideas described are not restricted and will be discussed with applicants before their deadline for submission.

## Skills required

- C
- Golang
- TCP
- Sockets
- Threading
- CMake
- Linux

**Comment by nokute78** [comment]
Could you add these items?

* in_proc: routines to gather process stats from OSX
* in_disk: routines to gather disk stats from OSX

**Comment by edsiper** [comment]
@nokute78 done

**Comment by nokute78** [comment]
Thanks

**Comment by edsiper** [comment]
No applications received, closing this issue.

**Comment by bhavishyagopesh** [comment]
@edsiper I did this yr's GSoC with PSF and have been a k8s user but would now like to contribute too(may be build up for next yrs GSoC)... So I understand the issue at the surface but would like to know the present state and interest? And also will OSX be required necessarily for development? thanks
