### ISSUE TITLE
msgpack to json: incomplete message

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#195]
Migrating out_es plugin I found that when converting some msgpack messages to JSON are not completed, e.g:

Original msgpack:
```
{"date"=>1487366000, 
 "rand_value"=>14190504959783770716, 
 "rand_valuX"=>{"keyname_00"=>"valu0", 
                "keyname_01"=>{"subkey_a_b_c"=>14190504959783770716, 
                               "array_X"=>[12345]
                              }
               }
}
```

converted (incomplete):

```json
{"date":1487366000, 
  "rand_value":14190504959783770716, 
  "rand_valuX": {"keyname_00": "valu0", 
                 "keyname_01": {"subkey_a_b_c":
```

**Comment by edsiper** [comment]
cc: @nokute78

**Comment by edsiper** [comment]
Sorry for the noise. Looks like the problem was on my end in a new routine I was creating.

Anyways looking at out_file source code, I've found that it consider a success when msgpack_to_json returns zero (which is the case when there is no more space available to complete the JSON string).

**Comment by nokute78** [comment]
out_file uses `flb_msgpack_to_json` that user should care the buffer size for JSON string.
out_file seems not to consider that.

On the other hand, `flb_msgpack_to_json_str` is re-malloc the buffer internal if the buffer is short.
So, it may be prefer to use `flb_msgpack_to_json_str` in out_file.

**Comment by nokute78** [comment]
Oops, I found a bug. `flb_test_file` outputs incomplete JSON string.
If out_file uses `flb_msgpack_to_json_str`, the bug is reproduced.

The bug seems to be caused `flb_msgpack_to_json*` try to handle only single buffer.

Hmm, we may need a function `flb_pack_msgpack_state`, like a `flb_pack_json_state`.

**Comment by edsiper** [comment]
I cannot longer reproduce this on 0.11.5

**Comment by nokute78** [comment]
@edsiper Thank you for fixing.
