### ISSUE TITLE
Dynamically load config/plugins

### ISSUE THREAD

**Issue by jishminor** [fluent/fluent-bit#1959]
**Is your feature request related to a problem? Please describe.**
When being used with Kubernetes, fluent-bit must be restarted (pod stopped and started again), every time I would like to make a change to my configuration. Add a new output plugin for example.

**Describe the solution you'd like**
Make loading of configuration dynamic during runtime, such that the fluent-bit daemon listens for new plugins to be loaded, via a light weight http server for instance. This could also be done with a directory based config scan (new file in specified directory is automatically loaded into config). 

**Describe alternatives you've considered**
To replicate behavior like this with fluent-bit in its current state, you could possibly bring up a new instance of fluent-bit with your new config, before bringing down the previous instance, making sure that there would be no downtime, however there would be some duplication of data during this transition time, making it not so ideal.

**Additional context**

For sensor data collected on a compute node, we would like to have a fluent-bit instance running which we are able to dynamically configure without having to reboot the pod, in order to maximize uptime (k8s pod restart process can take a few seconds).

**Comment by jishminor** [comment]
This is a duplicate of an issue/feature-request opened a while back: #365. Closing.

**Comment by ringerc** [comment]
For other readers, note that `fluent-bit` already appears to support loading plugins with `dlopen()` and `dlsym()`. See `flb_plugin_load(...)` in `src/flb_plugin.c`.

It appears that the default cmake build statically links the plugins into the main binary, but there's dynamic loading support in the codebase.  There are some docs in https://github.com/ringerc/fluent-bit-docs/blob/master/development/developer-guide.md#plugin-api . There are also some notes on it in this blog post https://www.cncf.io/blog/2022/05/04/how-to-write-a-fluent-bit-plugin/ .

The point of this issue and why it's a dup of #365 is that there's no way to ask fluent-bit to reload its config at runtime, either for new plugins or for new config for existing plugins.
