### ISSUE TITLE
Datadog TLS not defaulting to 'on'

### ISSUE THREAD

**Issue by snoopdouglas** [fluent/fluent-bit#1962]
## Bug Report

**Describe the bug**

Datadog's `TLS` option doesn't appear to default to `on`, despite [the docs](https://docs.fluentbit.io/manual/output/datadog) stating otherwise.

**To Reproduce**

Example configuration:

```
[INPUT]
  Name        tcp
  Listen      0.0.0.0
  Port        3000
  Chunk_Size  32
  Buffer_Size 64
  Format      json

[OUTPUT]
  Name        datadog
  Match       *
  apikey      ${DATADOG_API_KEY}
  dd_source   source
  dd_service  service
```

Example submission shown on stdout:

```
fluentbit_1  | [2020/02/20 10:00:01] [ info] [out_datadog] http://http-intake.logs.datadoghq.com, port=80, HTTP status=200 payload={}
```

Note `http://` and `port=80`.

**Expected behavior**

The `https://` scheme and `port=443` should be used, as `TLS` isn't set in the config.

**Your Environment**

* Version used: 1.3.6
* Configuration: shown above
* Environment name and version (e.g. Kubernetes? What version?): Docker image, `fluent/fluent-bit:1.3.6`
* Operating System and version: Ubuntu Linux 18.04, Kernel 5.0.0-1037-oem-osp1
* Filters and plugins: shown above

**Comment by edsiper** [comment]
cc: @joyzhang-dd @clamoriniere

**Comment by snoopdouglas** [comment]
Seems to still be the case on 1.3.8.

Additionally, logs don't seem to reach Datadog on the arm32v7 build.

**Comment by clamoriniere** [comment]
Hi @snoopdouglas 
We did the doc update few months ago: https://github.com/fluent/fluent-bit-docs/pull/238

on the master branch the Datadog plugin doc is align with the implementation: https://github.com/fluent/fluent-bit-docs/blob/master/output/datadog.md

@edsiper  maybe I need to cherry pick the PR on a specific branch?

**Comment by edsiper** [comment]
yeah, I cherry-picked to 1.3 branch, it should update the docs shortly.

**Comment by edsiper** [comment]
thanks

**Comment by clamoriniere** [comment]
@edsiper thanks you  👍
