### ISSUE TITLE
filter (like throttle) per tag or some record attribute

### ISSUE THREAD

**Issue by test-account-0** [fluent/fluent-bit#1965]
**Is your feature request related to a problem? Please describe.**

I would like to throttle logs per kubernetes namespace.
I know how to send them to separate elasticsearch indices via lua filter and `Logstash_Prefix_Key`, but I don't think there is option to create dynamic number of throttle filters per namespace/tag/some key.

**Describe the solution you'd like**
Not sure. What I imagine might be:
  * filter that would split (aggregate?) records based on some key (tag?) between dynamically created filters. For example it could match `kube.*` and based on tag: `kube.<namespace>` it would create dynamic number of throttle filters.
  * just change in throttle filter allowing throttling per some key/tag/etc

**Describe alternatives you've considered**
I consider generating fluent-bit config with throttle filter per namespace and adding tags with lua, but I already don't like this solution.

**Comment by smil2k** [comment]
https://github.com/rubrikinc/fluent-plugin-throttle

Fluentd throttle plugin supports a group key in the attributes section which can be used just for that.

**Comment by g3kr** [comment]
@test-account-0 how did you workaround this? I think the issue is still valid. Its not available for fluent-bit throttle.

**Comment by ktlcove** [comment]
> https://github.com/rubrikinc/fluent-plugin-throttle
> 
> Fluentd throttle plugin supports a group key in the attributes section which can be used just for that. It would be good to see support for something similar.

I think we should not put throttle logical to fluntd/logstash or something else
for log system when it want throttle a log, best way is drop it at once without send it anymore, should not send it anyway drop it in fluentd/logstash(may be net traffic is too large to hold for the log system even make log system crash)
so I suggest we throttle log group some custom key and write something in record like this.
```
FILTER]
    Name     throttle
    Match    *
    Group_Key  $labels.group  # default is tag
    Send_Throllte_Msg false
    Throllte_Msg  "When from unthrottled change to throttled send me. (tag: $tag group: $label.group)"
    Throllte_Msg_Key msg  # put Throllte_Msg to this key
    Rate     1000
    Window   300
    Interval 1s
```
