### ISSUE TITLE
Add the ability to parse Envoy access logs

### ISSUE THREAD

**Issue by CarmenAPuccio** [fluent/fluent-bit#1973]
**Is your feature request related to a problem? Please describe.**
The ability to parse Envoy's access logs out of the box. The access log format is described in detail in Envoy's [documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log)

**Describe the solution you'd like**
The easiest solution would be to provide an additional parser in /conf

**Comment by edsiper** [comment]
#1974 merged. thanks
