### ISSUE TITLE
td-agent-bit cannot be started when daemon is set to on

### ISSUE THREAD

**Issue by ncepuwanghui** [fluent/fluent-bit#1977]
## Bug Report

**Describe the bug**

The td-agent-bit cannot be started when daemon is enabled.

**To Reproduce**
- Steps to reproduce the problem:
The configure of `td-agent-bit.conf` as follows:
```
[SERVICE]
    Flush     5
    Daemon    on
    Log_Level debug
    Log_File /apprun/fluent-bit/fluent-bit.log

[INPUT]
    Name cpu
    Tag test

[OUTPUT]
    Name stdout
    Match *
    Format json
```
Then start td-agent-bit use systemctl:
```
systemctl start td-agent-bit
```
Finally, check the service status by `systemctl status td-agent-bit`, and see the following log information:
```
# systemctl status td-agent-bit
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2020-02-26 12:00:26 CST; 1ms ago
  Process: 1309 ExecStart=/opt/td-agent-bit/bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf (code=exited, status=0/SUCCESS)
 Main PID: 1309 (code=exited, status=0/SUCCESS)

Feb 26 12:00:26 dev02 systemd[1]: td-agent-bit.service holdoff time over, scheduling restart.
Feb 26 12:00:26 dev02 systemd[1]: start request repeated too quickly for td-agent-bit.service
Feb 26 12:00:26 dev02 systemd[1]: Failed to start TD Agent Bit.
Feb 26 12:00:26 dev02 systemd[1]: Unit td-agent-bit.service entered failed state.
Feb 26 12:00:26 dev02 systemd[1]: td-agent-bit.service failed.
```

When the option `Daemon on` is set to `Daemon off`, td-agent-bit start successfully.

**Expected behavior**

If the option `Daemon` is set to `off`, it can alse be started successfully.

**Screenshots**

**Your Environment**

* Version used:  Fluent Bit v1.3.8 (td-agent-bit)
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: Linux dev02 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Filters and plugins:

**Additional context**

**Comment by edsiper** [comment]
the Systemd unit needs Fluent Bit runs as a normal process, not in daemon mode.
