### ISSUE TITLE
Can't Run LIKE inside a stream processor

### ISSUE THREAD

**Issue by appcardDorsivan** [fluent/fluent-bit#1980]
## Bug Report

**Describe the bug**
I have a stream processor and a few stream tasks. I cannot perform an SQL Query with a part such as 
```
CREATE STREAM test WITH (tag='simple') AS SELECT * from TAG:'app-firelens*' WHERE log LIKE '%analytics%'
```
While a query like
```
CREATE STREAM test WITH (tag='simple') AS SELECT * from TAG:'app-firelens*' WHERE log = 'analytics'
```
does work.

The error I get is,
```
[error] [sp] syntax error, unexpected IDENTIFIER, expecting ';' at 'CREATE STREAM different WITH (tag='simple') AS SELECT * from TAG:'app-firelens*' WHERE log LIKE '%analytics%';'
```
Note that if I were to write something like FOO instead of LIKE I would get the same error.

- Steps to reproduce the problem:

I am running this on an aws container with the latest version of the fluent-bit image. I can attach the task definition, if needed my fluent.conf looks like this:
```
[SERVICE]
    Flush        1
    Log_Level    info
    Streams_File stream_processor.conf

[OUTPUT]
    Name cloudwatch
    Match no
    auto_create_group true
    auto_create_stream true
    log_group_name logs-new-log-group
    log_stream_prefix fluent-logs-
    region us-east-1
    use_tag_as_stream true

[OUTPUT]
    Name cloudwatch
    Match simple
    auto_create_group true
    auto_create_stream true
    log_group_name streams-example
    log_stream_prefix fluent-logs-
    region us-east-1
    use_tag_as_stream true

[OUTPUT]
    Name cloudwatch
    Match without
    auto_create_group true
    auto_create_stream true
    log_group_name streams-example
    log_stream_prefix fluent-logs-
    region us-east-1
    use_tag_as_stream true
```

However, I assume I am just missing something here, since I don't know SQL, however, none of my peers was able to help me out here.

**Comment by edsiper** [comment]
the ```LIKE``` conditional statement is not supported (yet)

**Comment by appcardDorsivan** [comment]
Thanks for the answer,

Is there another option for me to use with similar results? (I just need to find if a string contains a word or even apply a regex)

**Comment by koleini** [comment]
@appcardDorsivan You can see latest syntax that Stream Processing supports here:

https://github.com/fluent/fluent-bit/tree/v1.3.9/src/stream_processor

Have you looked at `grep` filter to see if that might work for you?

https://fluentbit.io/documentation/0.12/filter/grep.html

**Comment by appcardDorsivan** [comment]
@koleini 
I have looked at grep, but in my case, I want to filter logs from the same Match multiple times, and send them to different log streams.
From what I understand, grep simply changes the entire input it works on
