### ISSUE TITLE
Default Retry_Limit is inconsistent with docs

### ISSUE THREAD

**Issue by l2dy** [fluent/fluent-bit#1981]
## Bug Report

**Describe the bug**
The default `retry_limit` seems to be 1.

https://github.com/fluent/fluent-bit/blob/3cf2dd856acb698f0315fc05717e42f02bf12bfe/src/flb_output.c#L288

But the [docs](https://github.com/fluent/fluent-bit-docs/blob/9edbe455026f4ccd00ed0c6e8e987f123d5cac4c/configuration/scheduler.md) says it defaults to 2.

**Comment by fujimotos** [comment]
@l2dy I posed a fix to the documentation project (fluent/fluent-bit-docs/pull/272).
This inconsistency should be resolved by that.

**Comment by edsiper** [comment]
thanks, fixed.
