### ISSUE TITLE
Increase log level for backpressure notice from debug to info/warning

### ISSUE THREAD

**Issue by JensErat** [fluent/fluent-bit#1982]
**Is your feature request related to a problem? Please describe.**

We suffered from bad backpressure issues. They have not really been obvious, but in the end increasing buffer size was part of the resolution. We would have realized much earlier that there are issues if backpressure would have had better observability. Running debug log with any kind of high work load is not really feasible, since the filters spam the debug log for each processed record. The backpressure notice was only visible after setting to debug log, though.

    [2020/02/26 17:46:06] [debug] [input] systemd.0 paused (mem buf overlimit)

**Describe the solution you'd like**

Increase the backpressure log level to info or even warning.

    [2020/02/26 17:46:06] [ warn] [input] systemd.0 paused (mem buf overlimit)

**Describe alternatives you've considered**

(Also) [exposing metrics on backpressure/pause events](https://github.com/fluent/fluent-bit/issues/1983). While log messages are helpful for understanding the issue, metrics would help at monitoring and continuous operation.

**Additional context**

**Comment by fujimotos** [comment]
> Increase the backpressure log level to info or even warning.

I took a brief look at the implementation this morning and found that
it was already fixed in master HEAD (via #1909).

So I believe this issue should be resolved in the next v1.4.0 release.

**Comment by JensErat** [comment]
I can confirm current master already has the changes I requested here.
