### ISSUE TITLE
Not able to install in Amazon Ec2 

### ISSUE THREAD

**Issue by git-neelesh** [fluent/fluent-bit#1989]
Hi Team,

I'm trying to install fluent-bit on ec2 (Linux x86_64 x86_64 x86_64 GNU/Linux) but not able to do so. Can someone please confirm if its compatible with  Linux's rhel flavour ?

```$ cat /etc/*release```
```
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2017.09
```
Thanks in advance for any help.

-Neelesh

**Comment by edsiper** [comment]
did you try the Centos 7 packages ?

note: we are going to ship native Amazon Linux 2 packages soon

**Comment by shivshankarb** [comment]
These steps worked for me to configure fluent-bit via td-agent-bit on 'Amazon Linux AMI 2'
https://fluentbit.io/documentation/0.8/installation/redhat_centos.html

**Comment by git-neelesh** [comment]
@edsiper Yes I tried centos 7 packages, but it was not working.
@shivshankarb not worked for me. I'll post the stack trace.

**Comment by git-neelesh** [comment]
@shivshankarb I am getting error this
![image](https://user-images.githubusercontent.com/1026717/75662873-ddd7a080-5c95-11ea-8845-058a44a9409b.png)

I tried to solve this issue but it leads many other issues.

-Neelesh

**Comment by shivshankarb** [comment]
@git-neelesh, looks like OS library specific issue. Sorry I am unable to comment about exactly but to me seems like Amazon Linux AMI release 2017.09 mssing one or many libraries used by fluent-bit.
I installed in on Amazon Linux release 2 (cpe:2.3:o:amazon:amazon_linux:2).
