### ISSUE TITLE
Unable to process log key value

### ISSUE THREAD

**Issue by hisrarul** [fluent/fluent-bit#2000]
Hi everyone
I have followed the official documentation by fluent bit to process the value of log key
https://docs.fluentbit.io/manual/filter/kubernetes#processing-the-log-value

I have written a parser and added it in the config file and also added annotation in my pod for the same.
As given in the screenshot I want to process the log key values. Please let me know any workaround if possible.
############## Pod #######
apiVersion: v1
kind: Pod
metadata:
  name: counter
  annotations:
    fluentbit.io/parser: israr
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date) Israrul Haque"; i=$((i+1)); sleep 1; done']
#################
Regular expression
^(?<lognumber>[^ ]*) (?<week>[^ ]*) (?<month>[^ ]*) (?<time>[^UTC]*)UTC (?<year>[^ ]*) (?<name>[^H]*)Haque$?
##########ConfigMap#########
apiVersion: v1
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
  parsers.conf: |
    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   israr
        Format regex
        Regex  ^(?<lognumber>[^ ]*) (?<week>[^ ]*) (?<month>[^ ]*) (?<time>[^UTC]*)UTC (?<year>[^ ]*) (?<name>[^H]*)Haque$?
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

**Comment by edsiper** [comment]
Your regex parser must use named capture feature, so you have to define groups name for the content of your log, the following quick regex works for your use case as an example, but of course is not flexible enough, you have to build a better one:

- https://rubular.com/r/gM4rJtAcUPeDMA

note: use the rubular site to compose your regex rules

**Comment by hisrarul** [comment]
Thank you edurado, The issue has been resolved.
