### ISSUE TITLE
Embed Kubernetes metadata if fluentbit is running as a sidecar

### ISSUE THREAD

**Issue by vaishali-prophecy** [fluent/fluent-bit#2002]
If fluentbit is running as sidecar in each of the application pods, how can i embed kubernetes metadata if filename doesn't have any such information. Also if application logs are coming to stdout and fluentbit is running as sidecar, how can the logs be tagged with kubernetes metadata?

**Comment by ymity** [comment]
you may construct filename from k8s metadata using https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ 
Did you check official k8s doc - https://kubernetes.io/docs/concepts/cluster-administration/logging/#sidecar-container-with-a-logging-agent ?

**Comment by renanqts** [comment]
I'm also looking for that. The plugin needs to get the data in Kubernetes API, but I couldn't find this feature available.

**Comment by patrick-stephens** [comment]
As suggested above, use the K8S downward API or pod spec to pass in variables with the metadata. I've done this before fine, it's not really anything Fluent Bit can do itself as it is down to the pod definition.
