### ISSUE TITLE
Fluent Bit Docker Image for Arm64

### ISSUE THREAD

**Issue by ndjhartman** [fluent/fluent-bit#2003]
**Is your feature request related to a problem? Please describe.**

There is no Arm based docker image for Fluent-Bit

**Describe the solution you'd like**

A Dockerfile to be created for Arm based platforms and submitted to Docker Hub

**Comment by PettitWesley** [comment]
@ndjhartman I believe the docker hub repo is multi-arch: https://hub.docker.com/r/fluent/fluent-bit/

**Comment by PettitWesley** [comment]
@ndjhartman https://github.com/fluent/fluent-bit-docker-image/blob/1.4/Dockerfile.arm64v8

**Comment by edsiper** [comment]
there was an issue with the :latest tag, already fixed.

thanks everyone.
