### ISSUE TITLE
could not pack/validate JSON response

### ISSUE THREAD

**Issue by shivshankarb** [fluent/fluent-bit#2004]
## Bug Report
This is similar to #1679 but raising it separately as it was waiting on customer..

**Describe the bug**
I come across with this error against Fluent Bit v1.3.7. Below is the log entry and we can clear see that closing braces '}}' are missing from the request.
Could this be related to the fact that it reached to the allowed character limit for the log document? And it is striping out the rest of the request. Below is my log entry for your reference. All my log entries it is failing has 937 character

```
[2020/02/28 08:08:53] [error] [out_es] could not pack/validate JSON response 
{"took":203, "errors":true, "items":[ {"index":{ "_index":"logs-2020.02.10", "_type":"_doc","_id":"xxxxxxxxxxxxxxxxxxx", "_version":1,"result":"created", "_shards":{"total":2,"successful":2,"failed":0}, "_seq_no":11379, "_primary_term":1, "status":201 } }, 
{"index":{ "_index":"logs-2020.02.10", "_type":"_doc", "_id":"xxxxxxxxxxxxxxxxxxx", "_version":1, "result":"created", "_shards":{"total":2,"successful":2,"failed":0}, "_seq_no":11455, "_primary_term":1, "status":201 } }, {"index":{ "_index":"logs-2020.02.10", "_type":"_doc", "_id":"xxxxxxxxxxxxxxxxxxx", "_version":1, "result":"created", "_shards":{"total":2,"successful":2,"failed":0}, "_seq_no":11380,"_primary_term":1,"status":201 } }, 
{"index":{ "_index":"logs-2020.02.10", "_type":"_doc", "_id":"xxxxxxxxxxxxxxxxxxx", "_version":1, "result":"created", "_shards":{"total":2,"successful":2,"failed":0}, "_seq_no":11456, "_primary_term":1, "status" 
[2020/02/28 08:08:53] [ warn] [engine] failed to flush chunk ''1-1582845332.575759250.flb', retry in 867 seconds: task_id=14, input=tail.0 > output=es.0 [2020/02/28 08:23:20] 
[error] [out_es] could not pack/validate JSON response {"took":97,"errors":true,"items":[{"index":{"_index":"logs-2020.02.10","_type":"_doc","_id":"xxxxxxxxxxxxxxxxxxx"
```
I observed that this error is followed by the warning against specific document only..
```
[2020/02/28 12:50:29] [ warn] [engine] failed to flush chunk '1-1582845332.575759250.flb', retry in 1863 seconds: task_id=14, input=tail.0 > output=es.0
.
.
.

Feb 28, 2020 @ 00:09:46.200 | [2020/02/28 00:09:46] [ warn] [engine] failed to flush chunk '1-1582845332.575759250.flb', retry in 364 seconds: task_id=14, input=tail.0 > output=es.0
```
Is there any way I can get rid of this specific document or instruct fluent-bit to ignore?

**Comment by Baryczka** [comment]
Could you ensure that throughput of your Elastisearch is capable to write all these log in given time?
Finally this document being written  to ES or not?

**Comment by GangaramD** [comment]
Do we have solution for the above error ? as i too started facing the same error as above.
`[2020/04/23 19:56:42] [error] [out_es] could not pack/validate JSON response
{"took":1577,"errors":true,"items":[{"index":{"_index":"logstash-2020.04.23","_type":"flb_type","_id":"6m-dqHEBx1o-qy4GHJLH","status":400,"error":{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [logstash-2020.04.23] as the final mapping would have more than 1 type: [_doc, flb_type]"}}},{"index":{"_index":"logstash-2020.04.23","_type":"flb_type","_id":"62-dqHEBx1o-qy4GHJLH","status":400,"error":{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [logstash-2020.04.23] as the final mapping would have more than 1 type: [_doc, flb_type]"}}},{"index":{"_index":"logstash-2020.04.23","_type":"flb_type","_id":"7G-dqHEBx1o-qy4GHJLH","status":400,"error":{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [logstash-2020.04.23] as the final mapping would have more than 1 type: [_doc, flb_type]"}}},{"index":{"_index":"logstash-2020.04.23","_type":"flb_type","_id":
[2020/04/23 19:56:42] [ warn] [engine] failed to flush chunk '1-1587671760.111888234.flb', retry in 677 seconds: task_id=14, input=tail.0 > output=es.0`

Have just followed the 4 commands of kubectl apply from the official web [github.](https://github.com/fluent/fluent-bit-kubernetes-logging) 

No modification in any parser or i/p o/p streams, expect the ES_HOST which is reachable from the pod network of k8s cluster.

@Baryczka Can you help here.

**Comment by Baryczka** [comment]
@GangaramD For me it looks like configuration for Elasticsearch was set `_doc` and now is set `flb_type` which are different format of storing data in indices. Check your configmaps or directly [OUTPUT] configuration in fluentbit
