### ISSUE TITLE
After configMap change, fluent-bit's pod on running by sidecar not response

### ISSUE THREAD

**Issue by wangyushuai** [fluent/fluent-bit#2005]
## Bug Report

**Describe the bug**

After configMap change, fluent-bit's pod on running by sidecar not response,  its pod is still using the older configuration.

**Expected behavior**

The pod can sense the configMap change and then automatically use the new configuration.

**Your Environment**
fluent-bit 1.2, k8s 1.4

**Additional context**
How do I configure fluent-bit so that the pod can sense the configMap change and then automatically use the new configuration.  If i not restart this pod!

**Comment by ymity** [comment]
It is not related to fluentbit. it is generic k8s problem - https://github.com/kubernetes/kubernetes/issues/22368

**Comment by patrick-stephens** [comment]
Fluent Bit requires a restart to pick up new config, you can potentially adopt a similar approach to various operators that watch the mounted config map location for changes then restart Fluent Bit internally or just restart the pods directly.
See #365 for discussions in this area.
