### ISSUE TITLE
Ability to specify JSON output fields as null per RFC7159 instead of excluded via the parsers

### ISSUE THREAD

**Issue by Obsecurus** [fluent/fluent-bit#2007]
## Enhancement

**Summary**
The JSON output in the file output plugin excludes empty keys rather than specifying them as `null` per RFC7159. Adding this ability would make it possible to construct strict schemas for upstream consumers. 

- Example log:
```
{"eventid": "cowrie.session.connect", "timestamp": "2019-11-19T16:09:06.112827Z", "session": "fc6cca5b", "message": "New connection: 1.2.3.4:48139 (172.31.10.12:23) [session: TT3]", "src_port": 48139, "system": "cowrie.telnet.transport.HoneyPotTelnetFactory", "isError": 0, "src_ip": "1.2.3.4", "dst_port": 23, "dst_ip": "172.31.10.12", "sensor": "ip-172-31-10-12"}
{"eventid": "cowrie.login.failed", "username": "enable\\x00", "timestamp": "2019-11-19T16:09:08.032622Z", "message": "login attempt [enable\\x00/linuxshell\\x00] failed", "system": "CowrieTelnetTransport,3,1.2.3.4", "isError": 0, "src_ip": "", "session": "fc6cca5b", "password": "linuxshell\\x00", "sensor": "ip-172-31-10-12"}
```
**Expected behavior**
The second output line should contain `"dst_port": null` but the field just doesn't exist.
**Your Environment**

* Version used: 1.3.3
* Environment name and version: Docker Desktop 2.1.0.5
* Server type and version: Container
* Operating System and version: ubuntu:16.04
* Filters and plugins: Firehose

**Comment by Obsecurus** [comment]
I have even tried passing them from a lua script as `nil` but it appears the default behavior is to drop the keys. Maybe this should be configurable I guess in the output plugins.

**Comment by Obsecurus** [comment]
You could default a different name with `0` and then use `Hard_rename` however in this case and others like it there is an important distinction between `0` and `null` because you can technically bind on port `0`. 

```
[FILTER]
    Name record_modifier
    Match telnet
    Record destination_port 0
[FILTER]
    Name modify
    Match telnet
    Hard_rename dst_port destination_port 
```

**Comment by Obsecurus** [comment]
Seems like a good place for this might be on the json/regex parser and I'm thinking I should have marked this as an enhancement. The way it could work is compare the specified `Types` to the extracted fields and output `null` if the field is missing with a setting like Use_Nulls or something.

**Comment by Obsecurus** [comment]
Another possibility would be the ability to default a record as null in record_modifier and then use a Hard_rename. However, right now it injects the literal string "null" 

```
[FILTER]
    Name record_modifier
    Match telnet
    Record destination_port null
[FILTER]
    Name modify
    Match telnet
    Hard_rename dst_port destination_port 
```

**Comment by jamiees2** [comment]
We also ran into this, it would be helpful to at least document this behavior - or better, just pass null fields on, like fluentd does :)

**Comment by spiliopoulos** [comment]
@edsiper  can we mark this issue as not stale and get some clarity as to whether this is intended behavior or a bug? If it's a bug can you point us to the right direction (to save some time) and we can try to make a PR?

**Comment by spiliopoulos** [comment]
@edsiper  checking in here.
