### ISSUE TITLE
Support date_nanos with Elasticsearch output plugin

### ISSUE THREAD

**Issue by jtackaberry** [fluent/fluent-bit#2014]
Fluent Bit otherwise generally supports nanosecond resolution on timestamps, but the Elasticsearch output plugin always rounds to millisecond precision.

Elasticsearch now has a `date_nanos` type which supports nanosecond resolution.  Fluent Bit should optionally allow using this type for `@timestamp`.

Dynamic mapping doesn't automatically detect `date_nanos` so Fluent Bit would need to explicitly set the type when writing to an index for the first time.

**Comment by edsiper** [comment]
Fixed by #2544 (to be released as part of Fluent Bit v1.6)
