### ISSUE TITLE
Ignore files not changed in specific time interval in fluent bit tail 

### ISSUE THREAD

**Issue by xPB12** [fluent/fluent-bit#2017]
**Problem Statement:**
Currently fluent bit has an ignore_older option which reads the record and ignores the records which are older than the time specified in the ignore_older option. When a particular directory has thousands of files, this approach reads all the files leading to open file descriptors and then ignores the records after reading. We have seen this causing unnecessary resource spikes during initial read when dealing with large number of files.

**Solution:**
There should be an equivalent in fluent bit of **limit_recently_modified** parameter that is available in fluentd as it scans the last modified time of files before reading.

**References:** 
https://github.com/fluent/fluent-bit/issues/716#issuecomment-414460134

**Comment by atheriel** [comment]
I'm also very interested in this feature and would take a stab at implementing it if it's desirable.

**Comment by xPB12** [comment]
This would definitely be helpful when reading files from a directory which has a huge number of files & the wildcard pattern cannot exclude those files & the only remaining option is the file age.
The ignore_older option does work but it still reads/parses the file and then ignore the records on the basis of timestamp (no timestamp in the record means they can't be ignored). This is inefficient when running fluent bit for the first time reading from a directory which has a lot of files to be read & can't be ignored due to lack of file age parameter.

**Comment by atheriel** [comment]
The other issue is that tailing thousands of (mostly older) files consumes a large number of kernel resources when using `inotify`, potentially hitting the watch limit and requiring kernel parameter tuning (which is what I encountered).

**Comment by edsiper** [comment]
v1.7 fixes the behavior of ignore_older. It applies to startup and also for monitored files being no longer modified.
