### ISSUE TITLE
Custom fields in MessagePack

### ISSUE THREAD

**Issue by sharadgaur** [fluent/fluent-bit#202]
@edsiper 

Is it possible to add custom fields in MessagePack? For example if Fluent-bit is running on 100s of nodes and collecting 100s of different kinds of log files and I would like to add some custom metadata in MessagePack before sending it to Fluentd like:
1) Hostname
2) File Path (sometime file path or name may contains metadata)
3) Sometime hardcoded metadata like client id etc.

Adding custom metadata fields will help later in Data Mining and other scenarios.

**Comment by edsiper** [comment]
hi @sharadgaur,

The record_transformer filter it's in the TO-DO list, it have a high priority. Likely to be implemented once we finish the Kubernetes filter (this week).

So, stay tuned :)

**Comment by sharadgaur** [comment]
Thanks for the quick reply @edsiper. I'm Looking forward to it. Do you have any time line for this feature?

**Comment by edsiper** [comment]
within March 2017.

**Comment by f0** [comment]
Like to see this too, adding e.g the hostname would be really good

**Comment by sharadgaur** [comment]
Thank you

**Comment by jpackagejasonc** [comment]
another 👍 for record_transformer in fluent-bit

**Comment by nokute78** [comment]
I added a filter plugin to add/remove fields.(#235)
I also wrote a configuration to append hostname to each record.

Could you check #235 ?

**Comment by edsiper** [comment]
this is already implemented in #235, will be available on 0.12 release.
