### ISSUE TITLE
Fluent-bit doesn't work on Windows. No error, no message in event viewer.

### ISSUE THREAD

**Issue by heyaWorld** [fluent/fluent-bit#2022]
Hey, I am having a small issue while running fluent-bit on windows.

This is the command that I am running from Powershell: ".\bin\fluent-bit.exe -i dummy -o stdout"

The artifacts that have tried: 

https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/31266794/job/i4259y6xfb77greb/artifacts

https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/30328472/job/w5eq2xi6cr8uuj06/artifacts

https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/28110050/job/cte76oenarbvvkk9/artifacts

Also the version here: https://docs.fluentbit.io/manual/installation/windows

There is nothing that happens on the PowerShell, no output, no error, nothing. There is also nothing in the event manager too, anyone has any clue about this?

PS C:> [Environment]::Is64BitOperatingSystem
True

![image](https://user-images.githubusercontent.com/47616490/76478455-fea2a300-63c5-11ea-9e0f-aad4fa18c81c.png)

**Comment by fujimotos** [comment]
> There is nothing that happens on the PowerShell, no output, no error, nothing. There is also nothing in the event manager too, anyone has any clue about this?

@heyaWorld Hmm, it should work fine. 

Indeed, I've just tested it out on a Windos machine and could confirm that
the following procedure just work well:

```powershell
PS C:\Users\Public> wget -o td-agent-bit-1.3.10-win64.zip http://fluentbit.io/releases/1.3/td-agent-bit-1.3.10-win64.zip
PS C:\Users\Public> expand-archive -Dest . -Path .\td-agent-bit-1.3.10-win64.zip
PS C:\Users\Public> cd td-agent-bit-1.3.10-win64
PS C:\Users\Public> .\bin\fluent-bit.exe -i dummy -o stdout
Fluent Bit v1.3.10
Copyright (C) Treasure Data

[2020/03/12 13:04:57] [ info] [storage] version=1.0.2, initializing...
[2020/03/12 13:04:57] [ info] [storage] in-memory
[2020/03/12 13:04:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/03/12 13:04:57] [ info] [engine] started (pid=13352)
[2020/03/12 13:04:57] [ info] [sp] stream processor started
[0] dummy.0: [1583985898.550465400, {"message"=>"dummy"}]
```

Can you try the procedure above and see if it works?

If it still fails on your environment, I'd appreciate if you can share the details of
your system information (Windows verson etc).

**Comment by heyaWorld** [comment]
@fujimotos Thanks for your reply.

So, I tried the exactly same steps, but didn't work for me. Here is the snippet.

![image](https://user-images.githubusercontent.com/47616490/76559359-3f4cfb80-645c-11ea-98ae-74ea5a566f61.png)


**Here is the system info:**
This is a VM installed on Azure: Standard D2 (2 vcpus, 7 GiB memory)
Operating System:  Windows 10 Pro, Version 1809
PowerShell version: 5.1.17763.771

I tried this in couple of VMs too, with same config.

One thing I suspect is that, Fluent-Bit is trying to download some dependencies and is unable to do that because of some firewall or port issues?

**Comment by fujimotos** [comment]
@heyaWorld It occurred to me that your environment probably does not
have VC runtime and that's the root cause.

Since VC runtime is what provides the standard libc functions on Windows,
Fluent Bit requires them in order to be functional.

Check our Dockerfile on how to install it:

https://github.com/fluent/fluent-bit/blob/master/Dockerfile.windows#L55

... and see if this fixes the problem for you.

**Comment by heyaWorld** [comment]
Indeed, that was the issue.
Thanks @fujimotos 

For other folks: here is the powershell command that you need to run.
`Start-Process vc_redist.x64.exe -ArgumentList '/install', '/quiet', '/norestart' -NoNewWindow -Wait; `

Here is the download link for "vc_redist.x64.exe": https://www.microsoft.com/en-us/download/details.aspx?id=52685
