### ISSUE TITLE
Ability to remove Sequence Key in influxDB output

### ISSUE THREAD

**Issue by senses0** [fluent/fluent-bit#2023]
Hi,

I'm using TAIL input plugin to read a log file, process the input with STREAM PROCESSOR then output the processed data with tags to an influx an database instance. 

```
[OUTPUT]
    Name          influxdb
    Match         aggregated_stats
    Host          127.0.0.1
    Port          8086
    Database      testing
    Tag_Keys      state_code device_name alarm_category alarm_source_description
```

Tag keys in the config are the only keys that I'm interested in storing in the influxDB.

My problem is that fluentbit also sends the default "_seq" as a key to influxDB which gets stored as a tag.

Since the values for "_seq" keeps on incrementing, it will end up resulting in a high series cardinality

https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#series-cardinality [More about Series Cardinality]

Is there are way I can tell the output plugin not to include the sequence key when sending data to influxDB?

Thanks,

**Comment by senses0** [comment]
For anyone trying to solve the same problem:

This is not yet in the documentation, but I managed to figure this out by reading through the source code https://github.com/fluent/fluent-bit/blob/master/plugins/out_influxdb/influxdb.c 

Using this config output plugin section solves the problem. I'm no longer seeing the default sequence tag "_seq" in influx database.
```
    sequence_tag  off
```

**Comment by scriptmaster** [comment]
Confirmed closed. I had the same problem I tried `Sequence_Tag ""` but that created a key named `""` and after setting `Sequence_Tag off` I can confirm it doesn't create the _seq and saves indexing/series-cardinality.

Quoting source code plugins/out_influxdb/influxdb.c:
```
    /* sequence tag */
    tmp = flb_output_get_property("sequence_tag", ins);
    if (!tmp) {
        ctx->seq_name = flb_strdup("_seq");
    }
    else if (strcmp(tmp, "off") == 0) {
        ctx->seq_name = flb_strdup("");
    }
    else {
        ctx->seq_name = flb_strdup(tmp);
    }
    ctx->seq_len = strlen(ctx->seq_name);
```
