### ISSUE TITLE
Centos7 package is not available due to 404

### ISSUE THREAD

**Issue by SockenSalat** [fluent/fluent-bit#2034]
## Bug Report

Following the installation manual leads to:

`http://packages.fluentbit.io/centos/7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`

had been working some days ago ...

**Comment by edsiper** [comment]
@SockenSalat 

Yesterday we migrated our server to a new location and all repositories were re-created.

For CentOS case, the only available version in the old path is the new td-agent-bit 1.3.11. If you need to get older versions please use the updated Yum file which adds $basearch as part of the path:

https://docs.fluentbit.io/manual/installation/redhat_centos#configure-yum

**Comment by edsiper** [comment]
ah, also change it to: https

**Comment by edsiper** [comment]
note: I've copied new path content to the old path to avoid this issue. But please update your Yum path.

**Comment by SockenSalat** [comment]
@edsiper :sunglasses: thank you!

**Comment by MuhammadNaeemAkhtar** [comment]
Hi @edsiper @SockenSalat,
I am getting the same error. Didn't understand how you solved it.
Getting the following error.
`Error: Package: td-agent-bit-1.8.13-1.x86_64 (td-agent-bit)
           Requires: libsasl2.so.3()(64bit)
Error: Package: td-agent-bit-1.8.13-1.x86_64 (td-agent-bit)
           Requires: libsystemd.so.0()(64bit)
Error: Package: td-agent-bit-1.8.13-1.x86_64 (td-agent-bit)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest`

**Comment by SockenSalat** [comment]
@MuhammadNaeemAkhtar yours is a different issue. It is more about _broken_ dependencies.

**Comment by MuhammadNaeemAkhtar** [comment]
@SockenSalat 
Can you please help me in that how to resolve it.
Thank You!

**Comment by SockenSalat** [comment]
@MuhammadNaeemAkhtar sorry but no. We switched to loki/promtail a while ago. But I feel with you since I know dependency-mess-up can be very _unpleasant_.

You may want to check your repositories and the source of any conflict regarding required libraries ... good luck! :four_leaf_clover:

**Comment by MuhammadNaeemAkhtar** [comment]
Thank You @SockenSalat 
Apart form dependency , I am also seeing the following error
`https://packages.fluentbit.io/amazonlinux/2/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`
