### ISSUE TITLE
Can't resolve an environment variable as referenced in record_modifier

### ISSUE THREAD

**Issue by Badawekoo** [fluent/fluent-bit#2037]
## Bug Report

**Describe the bug**

I'm using a fluentbit image as a sidecar container to my application and I want fluentbit to log some metadata about my application.
So I defined dynamic environment variables in my application and wanted to record it in fluentbit then stream it to elasticsearch
But I got a warning message that env variable is used but no set
I tried to record a static value and it works so I need support to record a dynamic environment variable
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
I got this warning message and nothing streamed to elastic
[ warn] [env] variable ${MY_POD_NAMESPACE} is used but not set
```

- Steps to reproduce the problem:

**Expected behavior**

To resolve the value of the defined environment variable successfully
**Screenshots**

**Your Environment**

* Version used:
Fluent Bit v1.3.10
* Configuration:
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name        tail
    Path        /var/log/app/*.log
    Refresh_Interval 5
    Parser  ntgParserFields
    Tag     orderMng
[Filter]
    Name   record_modifier 
    Match  *
    Record nodename ${MY_NODE_NAME}
    Record podname $MY_POD_NAME
    Record podnamespace ${MY_POD_NAMESPACE}
    Record podip ${MY_POD_IP}
    Record podserviceaccount ${MY_POD_SERVICE_ACCOUNT}
    Record test "TEST HELLO"
[OUTPUT]
    Name    es
    Host    XXXX
    Port    XXXX
    Match   orderMng
    HTTP_User   XXXX
    HTTP_Passwd XXXX
    Logstash_Format True
    Logstash_Prefix logstash-sdsl-om
    Type    _doc
* Environment name and version (e.g. Kubernetes? What version?):
OCP 3.11
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by ymity** [comment]
I used similar config and all env variables were populated.
If you run 'env' or 'printenv' in container, do you see that variable have value ?

**Comment by patrick-stephens** [comment]
Yeah this all works fine for me as long as variables are set properly, as in they must be set in the container when Fluent Bit is launched so make sure they are.
