### ISSUE TITLE
Fluent-bit on Windows exits with SIGSEGV

### ISSUE THREAD

**Issue by cristianciutea** [fluent/fluent-bit#2042]
## Bug Report

**Describe the bug**

Running fluent-bit on Windows 10 with 'Windows Event Log' input configuration exits with the following message:
`[engine] caught signal (SIGSEGV)`

**To Reproduce**
- This seems to happen only when a DB file is configured
- Doesn't seems to matter if you choose a clean Channel (without log entries) or a channel that has log entries.

**Expected behavior**

In case that something is wrong with the configuration/log entries I would expect a stderr message that give a hint to the problem
<img width="913" alt="Screen Shot 2020-03-24 at 10 29 43 AM" src="https://user-images.githubusercontent.com/15685307/77409996-858a4f00-6dba-11ea-8c0f-e6e1245074ef.png">

**Your Environment**

* Version used:
Windows fluent-bit 1.3.10 and 1.3.11
* Configuration:
<img width="425" alt="Screen Shot 2020-03-24 at 10 23 19 AM" src="https://user-images.githubusercontent.com/15685307/77409427-866eb100-6db9-11ea-9a89-f7def8e066de.png">
* Operating System and version:
<img width="224" alt="Screen Shot 2020-03-24 at 10 24 49 AM" src="https://user-images.githubusercontent.com/15685307/77409567-c03fb780-6db9-11ea-802c-e0b0e6ba75b1.png">

**Additional context**

**Comment by fujimotos** [comment]
Thank you for reporting. I have investigated the issue and just posted a fix to #2049.

**Comment by edsiper** [comment]
thanks. this will be part of v1.4.1 release
