### ISSUE TITLE
Add Transit logo to users

### ISSUE THREAD

**Issue by naseemkullah** [fluent/fluent-bit#2047]
Hi @edsiper,

Please add Transit's logo to the users collage.

Here are two options for our logo:

- [First Option](https://uce8dba3a2e0ed01a76a86827382.previews.dropboxusercontent.com/p/thumb/AAuhuOZH-hxNyhO7M1wnbU7gQB8U_2WJOa2bSopNOWFLkZdIwwpld8WhyBIkogY-zr-xeeWZCHuCEjny_8ccvpZ_BXaF6jFScUnLn7ctV5G0N1sTKaeBtStSGxfSR0z2QPvTWME3ZDaJXW289HzLCvQ-1U62p-JmFDSMwGlceAwTPS6c-UFpnuMZilyQwieyAWy1dEpSsaqVzSxF392NsJEStYfYqHKmrrVpznQ7GAJw_A4xSfDjVX44dyxdK9lzKK7uQiUcZh8Imf-MKN3sFLhxP4YNP30Qd6VWIi1A9IE2eydfjmBFW763m3KxF8GM_-N7Gl7-Gih1If4zZyigux7_gDevlBURi2fdrff084OxTxNhXYOPl2MqqtX3WWR4XqtozAahCpYx_WuZG_zzB66D6gUDngiGDIq6DM3wRZNpTA/p.png?fv_content=true&size_mode=5)

- [Second Option](https://uc354c672b32e591139891ebead7.previews.dropboxusercontent.com/p/thumb/AAtdBebY43kh2bg4nvUQxawGD4enSaahO7ZuCdPxu9xEW2ruPh_VpitTOBOqWHM642DLdFMIOPUHCUWFnrEr7JU7i4cUAHmdLiQSvMCG3vbjwlcKLtK3JgJM0zSCrpF3Cz4rtl2l8EYcM9fd7BERkuIiJwVue4CyckEESLEWG8iYgj0dArK7efiE_xHnVE7aCyW6zoUBuAytDIJ_IG2n35L6LGiP9AZ0MVDUI1rp6AlufD5GTms-23kGWLizH9licc3V0F6yM1EPW-kzSDxZCQGvHJfqkKt1Nl9qtXemC0tri3msr7pTWVRQfrU5TBzdZjk8SJyROBeeuMy7HMIJ10l-Y83R-MG6sHL7XFyzqzb_Ag/p.png?fv_content=true&size_mode=5)

Thanks!

**Comment by edsiper** [comment]
ooops, I just tried the links but they are not available, can you attach the files to this ticket ?

**Comment by naseemkullah** [comment]
![transit icon](https://user-images.githubusercontent.com/24660299/78090461-2e771200-7398-11ea-8ff8-6c59531cc380.png)
![transit logo](https://user-images.githubusercontent.com/24660299/78090463-320a9900-7398-11ea-91bc-4ca3b7490718.png)

**Comment by edsiper** [comment]
thanks @naseemkullah 

Fixed by 9b4dae61
