### ISSUE TITLE
FluentBit Tail DB and Memory Buffer behave as two independent systems -- Need to be one.

### ISSUE THREAD

**Issue by Jeremyhoc** [fluent/fluent-bit#2051]
## Bug Report

**Describe the bug**
What is FluentBit's order of operations when it comes to enabling the DB, Memory Buffer (filesystem storage), and the Output Plugin failing? Is it the following?...:
1. Read from tail a new message
2. Write to DB that it read this message
3. Attempt to send to Output Plugins
4. Output Plugin does not receive ACK, fails, reports back to Input Plugin
5. Input Plugin writes to Memory Buffer (via filesystem)

The time it takes to do steps 3-5 is that there is a 1-3 second delay.. meanwhile, the DB was written to even before step 3. **So the true problem is, if a message is written to the file, FluentBit Tail reads it, then crashes... FluentBit will resume on the NEXT log line, and the crashed line will forever be lost to FluentD/Outputs**.

The Tail Reads write to the DB... but the Buffer is written to only upon failure of Output Plugin. The two processes seem independent.

**To Replicate This Bug**
Start FluentBit, add a log to the file it's watching via Tail Input Plugin, then stop FluentBit **immediately**. The record is written to the DB, but not the Memory Buffer due to Output Plugin Failure didn't report back in time.

**Expected behavior**
We need the record to be written to the DB **if and only if the Output Plugin succeeded**.  If a message is written to the file, and Tail picks it up, it should ensure that the Output Plugins were sent successfully before writing to the DB. If upon failure, a memory buffer should be written to, and **no record should be written to DB**. this way, if FluentBit for some reason crashes right after a log was written to the file, it successfully picks up where it left off.

**Your Environment**
amzlnx 1 on AWS

* Version used: 
Fluent Bit v1.3.11
fluentd 1.7.4

* Configuration:
**FluentBit**
```
[SERVICE]
    Flush                     1
    Daemon                    off
    Log_Level                 info
    Parsers_File              td-agent-bit.parser
    storage.path              /var/log/somewhere/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 1mb

[INPUT]
    Name              tail
    Path              /var/log/somewhere/test.log
    Tag               discovery:${HOSTNAME}
    Multiline         On
    Parser_Firstline  log_attributes
    DB                /var/log/somewhere/fluentProcesser.db
    Mem_Buf_Limit     1mb
    storage.type      filesystem

[OUTPUT]
    #Name                   stdout
    Name                    forward
    Match                   *
    Host                    fluentd
    Port                    24224
    Require_ack_response    True
    Retry_Limit             False
```

**FluentD**
```
<system>
  workers 3
</system>

<source>
  @type         forward
  bind          0.0.0.0
  port          24224
</source>

<match *.**>
  @type elasticsearch
  <buffer>
    @type file
    path /fluentd/log/es.buffer
    flush_thread_count 2
    flush_interval '15s'
    chunk_limit_size '100K'
    retry_forever true
    overflow_action "block"
    flush_at_shutdown true
  </buffer>
  host <URL>.es.amazonaws.com
  port 443
  scheme https
  logstash_format true
  logstash_prefix fluentd
  logstash_dateformat %Y%m%d
  include_tag_key true
  index_name fluentd
  type_name access_log
  tag_key @log_name
</match>
```

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: 
* Filters and plugins: 

**Additional context**

**Comment by edsiper** [comment]
thanks for opening this ticket.

If there is a crash, I would like to know more details, if the crash mentioned is just a use case, please confirm.

The main requirement in place here is the ability to update the database files offset ONLY if the data was delivered properly. Note that this is an enhancement and let me explain why (and the proper workaround).

In Fluent Bit, the records can go to multiple places, even if the output destination is just one, the ingestion rate will be depending on the outgoing rate. If we implement a configuration property for this behavior, the service will process data very slow. What would happen if the new data that arrives in the file is not able to be processed before a file gets rotated ?, there are many corner cases here, so what's the ideal workaround?: filesystem buffering.

If you enable file system buffering, any data that was not able to be delivered will be retried even after a crash, filesystem buffering aims to provide a reliable mechanism to route ingested data:

- https://docs.fluentbit.io/manual/concepts/buffering
- https://docs.fluentbit.io/manual/administration/buffering-and-storage 

So the database for in tail is used to know from where to continue reading to ingest data, in the meanwhile the storage layer (file system buffering) will continue processing any undelivered records.

pls let me know your comments

**Comment by Jeremyhoc** [comment]
The main issue here is the following two:

> The Tail Reads write to the DB... but **the Buffer is written to only upon failure of Output Plugin**.
In other words, the record is written to the DB, but not the Memory Buffer due to Output Plugin Failure didn't report back in time. So if the crash happens before Output Plugin responds.. (Tail->DB->Output Plugin->Crash), then we lose the record.

The current process is: Tail->DB->Output Plugin->(Success? ..) || (Failure?->WritesToBuffer)
What we need is a more intelligent DB record tracking system: Tail->DB (with field "Sending")->Output Plugin->(Success? (Update DB Field Sending to Sent) || (Failure?->WritesToBuffer)

And then when FluentBit starts back up, we take it from the LAST Sent Record row... not the first buffer item.
