### ISSUE TITLE
Does ES [OUTPUT] works in Windows container. ?

### ISSUE THREAD

**Issue by sachinmsft** [fluent/fluent-bit#2057]
## Bug Report

**Describe the bug**
I am trying the fluent-bit container image to forward the logs to ES output. Is this output have been ported to Windows ?

**Comment by fujimotos** [comment]
Yes, out_es is usable and enabled by default in 1.4 series
Try the following with https://docs.fluentbit.io/manual/installation/windows

```powershell
PS> fluent-bit.exe -i dummy -o es -p es
```
