### ISSUE TITLE
in_tail: add filepath field

### ISSUE THREAD

**Issue by infoMatt** [fluent/fluent-bit#206]
Currently the ```in_tail``` plugin of fluent-bit doesn't add the file path in the message, unlike the ```in_tail``` plugin of fluent version >0.14... Could it be added?

I really appreciate how lightweight fluent-bit is, but it lacks something...

Thanks.

**Comment by nokute78** [comment]
@infoMatt 
I added a new option 'path_key' which is similar to fluentd. 
This feature will come in v0.11.

This is a example.
```
$ bin/fluent-bit -i tail -p path=sample/a.txt -p path_key=FILEPATH -o stdout
.
[0] tail.0: [1489577779, {"FILEPATH"=>"sample/a.txt", "log"=>"aaa"}]
[1] tail.0: [1489577779, {"FILEPATH"=>"sample/a.txt", "log"=>"bbb"}]
```

The 0.11-dev documentation is here.
https://github.com/fluent/fluent-bit-docs/blob/master/input/tail.md

**Comment by edsiper** [comment]
just in case, dev docs are being published here:

http://fluentbit.io/documentation/0.11/

**Comment by edsiper** [comment]
closing since is already implemented.

thanks to @nokute78 for work on this!
