### ISSUE TITLE
how to get rid of "log" key

### ISSUE THREAD

**Issue by g3kr** [fluent/fluent-bit#2061]
echo -n "{\"key\": \"$(date)\"}" | fluent-bit -i stdin -t testcase -o stdout

produces

[0] testcase: [1558366818.274547608, {"key"=>"Mo 20. Mai 17:40:18 CEST 2019"}]

but when I used tail instead of stdin, my log object is put into the key log.

$ echo  "{\"key\": \"$(date)\"}" >> /tmp/example
$ fluent-bit -i tail -p path=/tmp/example -t testcase -o stdout
produces

[0] testcase: [1558367061.534409505, {"log"=>"{"key": "Mo 20. Mai 17:43:38 CEST 2019"}"}]

How to get rid of the log key when the input is tail type?

**Comment by fujimotos** [comment]
What you need to do is to define the parser for your log format.

Try the following:

```bash
$ echo '{"key": "Tue 31 Mar 2020 09:08:19 AM JST"}' > /tmp/example
$ fluent-bit -R parsers.conf -i tail -p path=/tmp/example -p parser=json -o stdout
...
[0] tail.0: [1585613482.501315148, {"key"=>"Tue 31 Mar 2020 09:08:19 AM JST"}]
```

Use parsers.conf is available [here](https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf). (It is included in the installer by default too, btw).
