### ISSUE TITLE
Output File doesn't read template pattern after upgrade to 1.4.1

### ISSUE THREAD

**Issue by Funzinator** [fluent/fluent-bit#2069]
## Bug Report

**Describe the bug**
After Updating to 1.4.1 the Output "file" with Template options doesn't work anymore. It just uses the default "{time} {message}" instead of the configured pattern. It worked fine in 1.3.9

**To Reproduce**
- Example log message if applicable:
Instead of the file format I configured, I only see
```
1585728545.000000 {message}
1585728545.000000 {message}
```

- Steps to reproduce the problem:
```
[OUTPUT]
    Name file
    Path /var/tmp/access.log
    Match *
    Format template
    Template anything here
```

Even without using any of the parsed variable, it can be reproduced. With above config the log should just output a line `anything here` for each match it got instead `1585728545.000000 {message}` is printed.

**Expected behavior**
The template option to be considered.

**Your Environment**
* Version used: 1.4.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): n/a
* Build Flags: ` Build Flags =  FLB_HAVE_PARSER FLB_HAVE_RECORD_ACCESSOR FLB_HAVE_STREAM_PROCESSOR JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SIGNV4 FLB_HAVE_SQLDB FLB_HAVE_FORK FLB_HAVE_GMTOFF FLB_HAVE_UNIX_SOCKET FLB_HAVE_PROXY_GO FLB_HAVE_SYSTEM_STRPTIME FLB_HAVE_LIBBACKTRACE FLB_HAVE_REGEX FLB_HAVE_UTF8_ENCODER FLB_HAVE_LUAJIT FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4`

* Operating System and version: FreeBSD 12.1
* Filters and plugins: regexp, syslog, output

**Comment by fujimotos** [comment]
I can confirm this is broken. `out_file` uses the default template
regardless of what is specified in the configuration file.

I posted a fix to #2070 .
