### ISSUE TITLE
filter_rewrite_tag will consume memory unbounded during a period of heavy load

### ISSUE THREAD

**Issue by zackwine** [fluent/fluent-bit#2073]
## Bug Report

**Describe the bug**

While load testing a fluentbit build from the tip (as of about a week ago), we started seeing OOM crashes on our fluentbit daemonset.  I tracked the memory usage to the emitter buffer of the rewrite_tag filter.  See the dumps below for details:

Dump from just at the start of load test:

```
[2020/04/01 19:31:49] Fluent Bit Dump

===== Input =====
tail.0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 48.8M (51200000 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0

emitter_for_rewrite_tag.11 (emitter)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 189.2M (198359188 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 275
│  ├─ new           : 2
│  ├─ running       : 273
│  └─ size          : 189.2M (198359188 bytes)
│
└─ chunks
   └─ total chunks  : 275
      ├─ up chunks  : 275
      ├─ down chunks: 0
      └─ busy chunks: 275
         ├─ size    : 189.2M (198359188 bytes)
         └─ size err: 0


===== Storage Layer =====
total chunks     : 275
├─ mem chunks    : 275
└─ fs chunks     : 0
   ├─ up         : 0
   └─ down       : 0

```

Dump a few minutes later (just before Kubernetes killed my container)
```
[2020/04/01 19:33:31] Fluent Bit Dump

===== Input =====
tail.0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 48.8M (51200000 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0

emitter_for_rewrite_tag.11 (emitter)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 334.4M (350656693 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 518
│  ├─ new           : 3
│  ├─ running       : 515
│  └─ size          : 334.4M (350656693 bytes)
│
└─ chunks
   └─ total chunks  : 518
      ├─ up chunks  : 518
      ├─ down chunks: 0
      └─ busy chunks: 518
         ├─ size    : 334.4M (350656693 bytes)
         └─ size err: 0


===== Storage Layer =====
total chunks     : 518
├─ mem chunks    : 518
└─ fs chunks     : 0
   ├─ up         : 0
   └─ down       : 0
```

I started to open a PR of this diff (https://github.com/zackwine/fluent-bit/commit/e38df301821eac2e00539ceb1b6daac9d0fcf799) to address the issue, but was unsure if this was the correct approach in limiting the memory usage, so I'm here opening this bug.

Can we put a limit on the memory rewrite_tag uses?

**To Reproduce**

Send high rate of logs to fluent bit with rewrite_tag filter emitting records to an output that provides backpressure.  We have a lua filter that does some heavy processing, that seems to make the issue occur at lower rates, but sending to the kinesis at a higher rate (250K per minute of logs of size 1K) will reproduce it without our filter in place.

**Expected behavior**

Memory usage should not grow unbounded within the rewrite_tag filter during a period of heavy load.

**Screenshots**

Below is a graph of the memory usage of fluent-bit during our scale test.  The crash gap represents the restart of the container when it was OOM killed:

![Screen Shot 2020-04-01 at 3 49 12 PM](https://user-images.githubusercontent.com/3758233/78180162-5c0f9a00-7430-11ea-8c3a-81b20fd63856.png)

**Your Environment**

* Version used:  Build from the tip from a week ago (git hash: f6bcb997b37298b94da9c4a76ae1f95c4e5259ea)
* Configuration: See below
* Environment name and version:  Kubernetes 1.7
* Operating System and version:  Distroless container image on top of Centos 7.6.1810 kernel 
* Filters and plugins: See below

Our use case is a fluenbit-daemonset that forwards logs from many varying components:

```
pod -> docker-json-driver -> fluenbit-daemonset -> kinesis
```

This is an snippet of our config: 

```
[SERVICE]
  # Flush
  # =====
  # Set an interval of seconds before to flush records to a destination
  Flush        1

  # Daemon
  # ======
  # Instruct Fluent Bit to run in foreground or background mode.
  Daemon       Off

  # Log_Level
  # =========
  # Set the verbosity level of the service, values can be:
  #
  # - error
  # - warning
  # - info
  # - debug
  # - trace
  #
  # By default 'info' is set, that means it includes 'error' and 'warning'.
  Log_Level    info

  # Parsers_File
  # ============
  # Specify an optional 'Parsers' configuration file
  Parsers_File parsers.conf
  Parsers_File parsers-custom.conf
  Plugins_File plugins.conf

  # HTTP Server
  # ===========
  # Enable/Disable the built-in HTTP Server for metrics
  HTTP_Server  On
  HTTP_Listen  0.0.0.0
  HTTP_PORT    24231

  # Define stream processors
  #Streams_File stream_processor.conf

[INPUT]
  Name              tail
  Tag               kube.*
  Path              /var/log/containers/*.log
  Parser            docker
  DB                /var/log/containers/flb_kube.db
  Buffer_Chunk_Size 512K
  Buffer_Max_Size   5120K
  Mem_Buf_Limit     51200K
  Skip_Long_Lines   On
  Refresh_Interval  2
  Rotate_Wait       10
  Exclude_Path      /var/log/containers/lmm-fluentd-daemonset-kinesis*,/var/log/containers/lmm-fluentbit-daemonset*

[FILTER]
  Name                 kubernetes
  Match                kube.*
  Kube_URL             https://kubernetes.default.svc:443
  Kube_CA_File         /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  Kube_Token_File      /var/run/secrets/kubernetes.io/serviceaccount/token
  Kube_Tag_Prefix      kube.var.log.containers.

# Drop logs missing the annotation logForwardStdOut_<container_name>: true
[FILTER]
  Name      lua
  Match     kube.*
  script    /lua/forward-opt-in.lua
  call      forward_opt_in
  Alias     lua.forward_opt_in

# Decorate logs from containers
[FILTER]
  Name   modify
  Match  kube.*
  Add    dc sturgill
  Add    logsource container-log
  Alias  modify.decorate

# Parse Logs
[FILTER]
  Name      lua
  Match     kube.*
  script    /lua/logging-standard.lua
  call      parse_logging_standard
  Alias     lua.parse_logging_standard

# Prune fields
[FILTER]
  Name record_modifier
  Match kube.*
  Remove_key kubernetes
  Remove_key stream
  Remove_key docker_timestamp
  Remove_key logtime
  Alias   record_modifier.prune

[FILTER]
  Name                     rewrite_tag
  Match                    kube.*
  Rule  $loglane           ^.*$ $loglane.$TAG false

[OUTPUT]
  Name            kinesis
  Match           infra.*
  region          us-east-1
  stream          sturgill-infra
  append_newline  true
  Alias           kinesis.infra
#... Other kinesis outputs
```

**Additional context**

Our platform supports forwarding logs from many different applications running in the same Kubernetes cluster.  We are currently scale testing fluentbit as a Daemonset to understand the limitations of how many records/second we can sustain.  In this case we would like to be able to set reasonable memory limits on the Daemonset, and avoid continuous OOM restarts on the fluentbit Daemonset.

**Comment by edsiper** [comment]
thanks for reporting the problem and providing a fix :)

If the emitter is facing backpressure due to slow delivery, the mem_buf_limit option will only restrict the amount of data once it hits the limit (so next data will be discarded), so the ideal solution are two things:

1. Add support for mem_buf_limit as you said (with a default value of 10M maybe?)
2. Enable file system storage type

For 1, I suggest that your patch to change the property name to ```emitter_mem_buf_limit```.

For 2, upgrade to v1.4.2 (just released) that exposes the property ```emitter_storage.type```. So you can set it as ```emitter_storage.type filesystem```

**Comment by zackwine** [comment]
@edsiper  Thanks for your quick response.

I opened this PR: https://github.com/fluent/fluent-bit/pull/2079

I updated the property name based on your suggestion, and added a default of `10M`.

Thanks for the tip on the storage type.

Off topic:  Does there exist a performance tuning thread/wiki/doc?  Any suggestions for getting the most throughput from fluentbit.

**Comment by edsiper** [comment]
thanks for the PR, just merged.

I am currently writing a Performance/Benchmark section.

**Comment by edsiper** [comment]
Closing since the PR is already merged.

**Comment by zackwine** [comment]
@edsiper Is the Performance/Benchmark section published anywhere?

**Comment by edsiper** [comment]
not yet, planed for 1.5 release.
