### ISSUE TITLE
Can't Adjust Amount Of Data Flushed Through Out Forward Plugin

### ISSUE THREAD

**Issue by agarwri** [fluent/fluent-bit#2074]
## Bug Report

**Describe the bug**
data flow looks like this:
fluentbit (input=tail, output=forward) --> fluentbit (input=forward, output=stdout).
I'm getting an error on the second fluentbit instance that looks like this:
[in_fw] fd=25 incoming data exceed limit (1000000 bytes)

fluentbit instance 1 config:
[INPUT]
    Name                tail
    Path                /usr/local/logs/benchmark_1gb.log
    Buffer_Chunk_Size   10KB
[OUTPUT]
    Name          forward
    Match         *
    Host           XXXX
    Port            24224

fluentbit instance 2 config:
[INPUT]
    Name              forward
    Listen              0.0.0.0
    Port                 24224
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size   1MB
[OUTPUT]
    Name          stdout
    Match         *

fluentbit instance 1 log (relevant lines)
one chunk is <10KB:
[in_tail] file=/usr/local/logs/benchmark_1gb.log read=9862 lines=4
flushed data is >2MB:
[out_forward] request 2053834 bytes to flush

fluentbit instance 2 logs (relevant lines)
incoming data exceeds 1MB:
[in_fw] fd=24 incoming data exceed limit (1000000 bytes)

**Expected behavior**
I expect each chunk of flushed data from the first fluentbit instance to be less than 1MB. How can i make this happen? buffer chunk size for first fluentbit instance is less than buffer chunk size for second fluentbit instance (10KB < 1MB), and i've tried reducing the flush interval but this hasn't worked--the amount of data flushed is always ~2050000 bytes.

**Your Environment**
* Version used: td-agent-bit-1.2.2-1.x86_64.rpm
* Operating System and version: rhel7

**Additional context**
I'm attempting to use fluentbit to replicate logs and forward them to another fluentbit instance running on a remote host, and from there forward them to kafka. The reason i need an additional fluentbit instance is because i can't connect directly from my application host to the kafka cluster due to security constraints.

**Comment by mpern** [comment]
I'm seeing exactly the same issue. The forward input plugin rejects chunks, but the chunk sizes of all pipeline elements are the same.

@agarwri have you ever solved this issue?

**Comment by tpetrov-lp** [comment]
@edsiper @PettitWesley Can you guys, please help, giving more details here how this all works? Should we configure the tail input and the forward input/output differently or is it some problem in the code?
Similar to @agarwri I have fluent-bit deployed as a daemonset on each k8s node forwarding to another fluentbit (k8s deployment) which writes to stackdriver.  I see `[ warn] [input:forward:forward.1] fd=89 incoming data exceed limit (8000000 bytes)` periodically with fluentbit **1.7.7**.

DS (applications):

```
    [INPUT]
        Name              tail
        Tag               stackdriver.json.istio-proxy.*
        Path              /var/log/containers/*_istio-proxy*.log
        Parser            istio_json
        DB                /var/log/ds/flb_istio_proxy.db
        DB.Sync           Normal
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Buffer_Chunk_Size 2MB
        Buffer_Max_Size   4MB
        
    # + a few more inputs configured similarly as above
    
    [OUTPUT]
        Name    forward
        Match   stackdriver.json.*
        Host    fluentbit-upload.logging-upload.svc.cluster.local
        Port    24225
```

Deployment (uploader):

```
    [INPUT]
        Name              forward
        Listen            0.0.0.0
        Port              24225
        Buffer_Chunk_Size 4MB
        Buffer_Max_Size   8MB
```

I doubt that any single event exceeds 8MB, but even if it does, I would expect this to be rejected on the ds fluentbit with the tail input rather than on the uploader one with the forward input. Please advise.

**Comment by nokute78** [comment]
When in_forward plugin tries to extend buffer, in_forward check if `current buffer size + Buffer_Chunk_Size` is bigger than `Buffer_Max_Size`.
When ` Buffer_Chunk_Size` is 4MB and `Buffer_Max_Size` is 8MB, it will be error if  4MB < `current buffer size`  < 8MB.

So, smaller `Buffer_Chunk_Size` may be good (e.g. 1MB in this case)

https://github.com/fluent/fluent-bit/blob/c8c8414e126b66a3cc4db13bd3610609c46d182e/plugins/in_forward/fw_conn.c#L45-L54

**Comment by tpetrov-lp** [comment]
@nokute78 thanks for the quick answer! What's not clear here is how many events we buffer in memory.

We start with an empty buffer `conn->buf_size=0`, the very first time we call `fw_conn_event`, it will resize the buffer to 4MB. Later on, we call `fw_conn_event` more times. At some point `buf_size=4MB` is not enough and we resize to `4MB + 4MB (buffer_chunk_size) = 8MB`. If we need another resize, it will fail. If `Buffer_Chunk_Size=1MB`, it will just take more iterations (1MB, 2MB and so on, but I don't understand how it would prevent me from getting the same error eventually). 

I need to see what's going on in `fw_prot_process` but I want to understand what causes the buffer to resize over and over again. If I put `storage.type=filesystem`, shouldn't we stop pushing to memory over and over again?

I'll appreciate if someone provides more details what goes to disk, what goes to memory and how this works together with `Buffer_Chunk_Size ` and `Buffer_Max_Size `.

**Comment by mpern** [comment]
Here is my wild guess:

The `tail` input keeps a buffer _per file_
But (mayne) the `forward` output combines and sends the buffers of all file simultaneously.

Worst case: forward sends num files * Buffer_Max_Size at once -> input rejects

**Comment by nokute78** [comment]
I read the in_forward code.
I think `Buffer_Max_Size` < `incoming messagepack size` causes shortage. 
It depends on out_forward side buffering and sending.

## in_forward side
The buffer of in_forward is allocated by each connections (= each fd)
In my environment, out_forward establishes 3 connections, so in_forward allocated 3 buffers.

In `fw_prot_process` , in_forward tries to unpack the buffer as messagepack.
If the buffer of data is incomplete, in_forward doesn't clear buffer and waits to receive next data.
If next received data is bigger than the left of the buffer, in_forward tries to extend the butter.

**Comment by tpetrov-lp** [comment]
What @nokute78 has described above is correct, but I think the filters are a key factor here. With tail buffer size of 4MB and in_forward buffer size of 8MB, it's hard to imagine that incoming message pack size will exceed 8MB, however the kubernetes filter adds significant amount of bytes to be sent as well. Assuming that this does not form another chunk, the original one can now exceed the 8 MB buffer of in_forward.
For my case, I reduced the tail buffer to 1 MB and increased the in_forward to 16MB and the error is now gone and the log drops coming from this are not there any more.

Hope that this helps.
