### ISSUE TITLE
[plugins/out_file/file.c:340 errno=2] No such file or directory\n"

### ISSUE THREAD

**Issue by rahulchandravanshi** [fluent/fluent-bit#2077]
## Bug Report
[plugins/out_file/file.c:340 errno=2] No such file or directory\n"

**Describe the bug**

While running fluent bit  fluent/fluent-bit:1.3.10 docker image in kubernetes 
I am getting below issue (fluent bit log output):
+++++++++++++++++++++++++++++++
 {"log":"\u001b[1mFluent Bit v1.3.10\u001b[0m\n","stream":"stderr","time":"2020-04-02T00:39:01.74016073Z"}
{"log":"\u001b[1m\u001b[93mCopyright (C) Treasure Data\u001b[0m\n","stream":"stderr","time":"2020-04-02T00:39:01.740243173Z"}
{"log":"\n","stream":"stderr","time":"2020-04-02T00:39:01.740248234Z"}
{"log":"[2020/04/02 00:39:01] [ info] [storage] version=1.0.2, initializing...\n","stream":"stderr","time":"2020-04-02T00:39:01.741872043Z"}
{"log":"[2020/04/02 00:39:01] [ info] [storage] in-memory\n","stream":"stderr","time":"2020-04-02T00:39:01.74189449Z"}
{"log":"[2020/04/02 00:39:01] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128\n","stream":"stderr","time":"2020-04-02T00:39:01.741898687Z"}
{"log":"[2020/04/02 00:39:01] [ info] [engine] started (pid=1)\n","stream":"stderr","time":"2020-04-02T00:39:01.741901751Z"}
{"log":"[2020/04/02 00:39:01] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443\n","stream":"stderr","time":"2020-04-02T00:39:01.744520484Z"}
{"log":"[2020/04/02 00:39:01] [ info] [filter_kube] local POD info OK\n","stream":"stderr","time":"2020-04-02T00:39:01.744962247Z"}
{"log":"[2020/04/02 00:39:01] [ info] [filter_kube] testing connectivity with API server...\n","stream":"stderr","time":"2020-04-02T00:39:01.745335932Z"}
{"log":"[2020/04/02 00:39:01] [ info] [filter_kube] API server connectivity OK\n","stream":"stderr","time":"2020-04-02T00:39:01.765417155Z"}
{"log":"[2020/04/02 00:39:01] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020\n","stream":"stderr","time":"2020-04-02T00:39:01.767330142Z"}
{"log":"[2020/04/02 00:39:01] [ info] [sp] stream processor started\n","stream":"stderr","time":"2020-04-02T00:39:01.767344113Z"}
{"log":"[2020/04/02 00:39:01] [error] [plugins/out_file/file.c:340 errno=2] No such file or directory\n","stream":"stderr","time":"2020-04-02T00:39:02.000311621Z"}
{"log":"[2020/04/02 00:39:01] [error] [plugins/out_file/file.c:340 errno=2] No such file or directory\n","stream":"stderr","time":"2020-04-02T00:39:02.000341411Z"}
{"log":"[2020/04/02 00:39:02] [error] [plugins/out_file/file.c:340 errno=2] No such file or directory\n","stream":"stderr","time":"2020-04-02T00:39:03.000224643Z"}
{"log":"[2020/04/02 00:39:09] [error] [plugins/out_file/file.c:340 errno=2] No such file or directory\n","stream":"stderr","time":"2020-04-02T00:39:10.000263543Z"}

here is my yaml file :
++++++++++++++++
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.3.10
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
      #restartPolicy: Never        
        env:
     #- name: FLUENT_ELASTICSEARCH_HOST
         # value: "elasticsearch"
        #- name: FLUENT_ELASTICSEARCH_PORT
         # value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      #restartPolicy: Never        
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

Fluent bit should report error saying "[error] [plugins/out_file/file.c:340 errno=2] No such file or directory\n""

**Your Environment**

* Version used: fluent/fluent-bit:1.3.11

* Configuration: kubernetes
* Environment name and version (Kubernetes):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

* Server type and version:
uname -a
Linux <somename> 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Operating System and version:
uname -a
Linux <somename> 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

* Filters and plugins:
I am trying to use ouput "file" plugins in fluentbit

**Additional context**

Using fluentbit I am trying to collect logs from all my nodes to a shared volume.

**Comment by rahulchandravanshi** [comment]
I had mount issue. it's got fixed now

**Comment by vedantjoshi84** [comment]
@rahulchandravanshi  can you elaborate what exactly did you do?

**Comment by rahulchandravanshi** [comment]
@vedantjoshi84 : Fluent-bit's fluent-bit-configmap.yaml file copies content inside pod, I needed to do volume mount in fluent-bit-ds.yaml file.
What is issue you are facing? share your sample fluent-bit-configmap.yaml and  fluent-bit-ds.yaml files.

**Comment by vedantjoshi84** [comment]
fluent-bit-cm.yaml : [fluent-bit-cm.txt](https://github.com/fluent/fluent-bit/files/8582135/fluent-bit-cm.txt)
fluent-bit-ds.yaml : [fluent-bit-ds.txt](https://github.com/fluent/fluent-bit/files/8582136/fluent-bit-ds.txt)

I understood that we get the logs inside the pod.
