### ISSUE TITLE
tail only works for Linux

### ISSUE THREAD

**Issue by girgen** [fluent/fluent-bit#208]
Hi. I see that plugin/in_tail is only activated for LInux. How come, what special tricks are used that fail on other systems? How can I get it running on *BSD?

I tried it and it seems to work OK, but issues an error message each Refresh_Interval seconds:
```
[2017/03/12 23:54:52] [error] [:328 errno=2] No such file or directory
```
Running with truss(8) show:
```
readlink("/proc/12851/fd/16",0x801492000,1024)	 ERR#2 'No such file or directory'
```
which is of course Linux specific. 

So it looks like it will fail when files are rotated?

```
/*
 * Given an open file descriptor, return the filename. This function is a
 * bit slow and it aims to be used only when a file is rotated.
 */
char *flb_tail_file_name(struct flb_tail_file *file)
{
    int ret;
    ssize_t s;
    char tmp[128];
    char *buf;

    ret = snprintf(tmp, sizeof(tmp) - 1, "/proc/%i/fd/%i", getpid(), file->fd);
...
```

Is the fix as complicated as actually keep a list of all open filenames?

**Comment by edsiper** [comment]
thanks for raising this issue. This is not hard to fix and indeed it needs a different workaround for non-Linux systems. 

I will make sure to provide it within the next days. I will keep you posted.

**Comment by girgen** [comment]
Excellent Thanks!

**Comment by edsiper** [comment]
Handle new file names for rotated files will need some work:

http://unix.stackexchange.com/questions/123602/portability-of-file-descriptor-links

**Comment by edsiper** [comment]
Looks like in BSD the program _fstat_ can give us some lights:

http://code.metager.de/source/xref/freebsd/usr.bin/fstat/fstat.c

that tool is able to determinate the file descriptors that current process have open and gather info from them.

**Comment by girgen** [comment]
How about tail? If does what you want to achieve when -F is set in http://code.metager.de/source/xref/freebsd/usr.bin/tail/forward.c

**Comment by brifordwylie** [comment]
Can we document this, since many examples use tail they should have a disclaimer that tail is Linux only at this point. I installed several versions on my Mac laptop trying to get tail input plugin to build/work and only came across this issue after burning a couple of hours :)

**Comment by edsiper** [comment]
@brifordwylie on GIT master I have enabled in_tail for OSX.

**Comment by edsiper** [comment]
for FreeBSD, we are marking this as Help Wanted:

https://github.com/fluent/fluent-bit/issues/208#issuecomment-289152812
