### ISSUE TITLE
[newbie] Cannot build fluent-bit

### ISSUE THREAD

**Issue by dongnt1612** [fluent/fluent-bit#2081]
## Bug Report

**Describe the bug**
I cloned the fluent-bit source code from github, then tried to build the source code as in https://fluentbit.io/documentation/0.8/installation/build_install.html
But when I run cmake ../, it said that could not find jounald, gtest, postgresql... 
As the document said, fluent-bit doesnot need any dependency package, so, should I try to fix all problems manually, or am I doing any wrong thing?

**To Reproduce**
- git clone https://github.com/fluent/fluent-bit
- cd fluent-bit
- mkdir build
- cd build
- cmake ../

**Expected behavior**
- If fluent-bit need dependency packages, the documentation should mention about them
- Correct me if I am doing any wrong thing
- Should I tried to fix all the error manually? or any other guidelines?

**Screenshots**

**Your Environment**

* Version used: lastest
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: Centos 7
* Filters and plugins:

**Additional context**

**Comment by sxd** [comment]
Hi @dongnt1612 

You should be reading this documentation https://docs.fluentbit.io/manual/installation/sources/build-and-install  the other one it's a bit outdated on a lot of things.

Let me know if it works for you

**Comment by nokute78** [comment]
@dongnt1612 Would you try to use `cmake3` ?

https://docs.fluentbit.io/manual/development/developer-guide#testing

**Comment by darksied9x** [comment]
> @dongnt1612 Would you try to use `cmake3` ?
> 
> https://docs.fluentbit.io/manual/development/developer-guide#testing

That is. CMAKE3 is the keypoint. Why isn't it included in https://docs.fluentbit.io/manual/installation/sources/build-and-install ?

**Comment by dongnt1612** [comment]
> @dongnt1612 Would you try to use `cmake3` ?
> 
> https://docs.fluentbit.io/manual/development/developer-guide#testing

That fixed my problem. Thank you very much. And hope that build-and-install document mentions about cmake3 in it.

**Comment by fujimotos** [comment]
> And hope that build-and-install document mentions about cmake3 in it.

Should be fixed by fluent/fluent-bit-docs/pull/287
