### ISSUE TITLE
error: unable to recognize "daemonset.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by joeldeteves** [fluent/fluent-bit#2084]
## Bug Report

**Describe the bug**
In the fluent-bit docs, it says when using version 1.4x to replace

`apiVersion: apps/v1`

with

`apiVersion: extensions/v1beta1`

However I am presented with the following error:
`error: unable to recognize "fluent-bit-ds.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"`

It seems extensions/v1beta1 has been deprecated according to the Kubernetes changelogs for version 1.16.x:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals

**To Reproduce**
- Steps to reproduce the problem:
Try to apply the fluent-bit daemonset on Kubernetes v1.16.6 or higher

**Expected behavior**
fluent-bit should revert to using apps/v1 as per Kubernetes documentation

**Screenshots**
N/A

**Your Environment**
* Version used: Fluent-bit version 1.4.2
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): DOKS (Digital Ocean Managed Kubernetes) version 1.16.6
* Server type and version: N/A
* Operating System and version: Ubuntu 18.04
* Filters and plugins: N/A

**Additional context**
I am unable to upgrade Fluent-bit to version 1.4x

**Comment by edsiper** [comment]
https://docs.fluentbit.io/manual/installation/kubernetes#note-for-kubernetes-less-than-v-1-16

**Comment by pmalek** [comment]
@edsiper The link you've provided describes a situation when a kubernetes version lower than `v1.16` is used whereas @joeldeteves uses `v1.16.6` which deprecates `apiVersion: extensions/v1beta1` which is mentioned there.

There's a PR that seems to fix this issue: https://github.com/fluent/fluent-bit-kubernetes-logging/pull/79

**Comment by edsiper** [comment]
closing as it's already fixed on https://github.com/fluent/fluent-bit-kubernetes-logging/pull/79
