### ISSUE TITLE
[centos 7] TCP connection failed. No upstream connections available

### ISSUE THREAD

**Issue by darksied9x** [fluent/fluent-bit#2088]
## Bug Report

**Describe the bug**
I want to integrate with my C project to send log to server.
I am using code like below:

`#include <fluent-bit.h>

static flb_ctx_t           *flb_ctx;
static int32_t     flb_in;

int32_t
main(void)
{
	/**
	 * 	STEP 1
	 */
    flb_ctx = flb_create();
    if(flb_ctx == NULL)
    {
        exit("Cannot create fluent-bit context!");
    }
    flb_in = flb_input(flb_ctx, "lib", NULL);
    if (-1 == flb_in)
    {
        flb_destroy(flb_ctx);
        exit("Cannot set fluent-bit 'lib' input!");
    }
    int32_t flb_out = flb_output(flb_ctx, "tcp", NULL);
    flb_output_set(flb_ctx, flb_out,
                   "tag", "myproject.darksied9x",
                   "host", "192.168.23.49",
                   "port", "24224",
                   "format", "json",
                   NULL);
    if (-1 == flb_out)
    {
        flb_destroy(flb_ctx);
        exit("Cannot set fluent-bit 'tcp' input!");
    }
    printf("Start fluent-bit tcp service to %s / %d\n",
            log_cfg->log_if.remote_ip_string,
            log_cfg->log_if.remote_port);
    if (-1 == flb_start(flb_ctx))
    {
        flb_destroy(flb_ctx);
        exit("Cannot start fluent-bit engine!");
    }

    ...

	/**
	 * 	STEP 2
	 */
    for(i = 0; i < 100; i++)
    {
    	flb_lib_push(flb_ctx, flb_in, buffer, len);
    }

    ...

    return 0;
}`

While run, the program cause 
TCP connection failed: 192.168.23.49:24224 (Connection timeout)
no upstream connections available

I am sure that my server work at 192.168.23.49:24224 (run fluentd) work properly. So, what am I doing wrong here?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: lastest
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Centos 7
* Filters and plugins:

**Additional context**

**Comment by darksied9x** [comment]
I found that, because of the server running the code has multiple NIC, while capturing packet tcp with port 24224 from any interface, I found them in a NIC that has vlan, so the tcp setup flow is not completed. Is it related? and how to change the source ip address of fluent-bit?

**Comment by edsiper** [comment]
@darksied9x we don't have that feature to choose the NIC to use for connections, but is a fair requirement. Would you please open a new ticket as an enhancement request for this ?

**Comment by darksied9x** [comment]
I will open new ticket for new feature about it. Thank you~
