### ISSUE TITLE
How could fluent-bit choose source address (nic, ip, port) to send TCP/HTTP message to target

### ISSUE THREAD

**Issue by darksied9x** [fluent/fluent-bit#2089]
## Bug Report

**Describe the bug**
+ my server has multiple NIC, with/without vlan assigned 
+ my application run on server, using fluent-bit to send log to remote server, output plugin is tcp
+ when my application start, the fluent-bit engine is started, and it chooses one ip on one NIC to setup tcp connection
+ tcp connection setup failed

**To Reproduce**

**Expected behavior**
- can set fluent-bit to choose source ip address to setup tcp connection

**Screenshots**

**Your Environment**

**Additional context**

**Comment by edsiper** [comment]
thanks for your suggestion, the feature has been just implemented in our GIT master branch (upcoming v1.5 release), documentation here:

https://docs.fluentbit.io/manual/v/master/administration/networking#tcp-source-address

Closing this ticket as fixed
