### ISSUE TITLE
Unhandled data types by msgpack2json

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#209]
@nokute78:

Just got a report where a user testing receiving data from in_forward (fluentd in_tail:out_forward -> fluent bit in_forward) it do not handle some msgpack types.

These are all data types that needs to be handled:

- [x] MSGPACK_OBJECT_NIL 0x00
- [x] MSGPACK_OBJECT_BOOLEAN 0x01,
- [x] MSGPACK_OBJECT_POSITIVE_INTEGER 0x02,
- [x] MSGPACK_OBJECT_NEGATIVE_INTEGER 0x03,
- [ ] MSGPACK_OBJECT_FLOAT32 0x0a,
- [x] MSGPACK_OBJECT_FLOAT64 0x04,
- [x] MSGPACK_OBJECT_FLOAT 0x04,
- [x] MSGPACK_OBJECT_STR 0x05,
- [x] MSGPACK_OBJECT_ARRAY 0x06,
- [x] MSGPACK_OBJECT_MAP 0x07,
- [x] MSGPACK_OBJECT_BIN 0x08,
- [ ] MSGPACK_OBJECT_EXT 0x09

So likely the bug could be triggerd by MSGPACK_OBJECT_FLOAT32 or MSGPACK_OBJECT_EXT. 

I think adding support MSGPACK_OBJECT_FLOAT32 is straighforward, for MSGPACK_OBJECT_EXT and any other unknown can be skipped.

But the user reported that skipping a unknown type lets Fluent Bit in a loop, would be this an issue because skipping a field is not updating the offset ?

**Comment by nokute78** [comment]
I sent a PR #210 to support float32 and ext.

>  (fluentd in_tail:out_forward -> fluent bit in_forward)

Hmm, msgpack2json is not called in that path. 

> But the user reported that skipping a unknown type lets Fluent Bit in a loop, would be this an issue because skipping a field is not updating the offset ?

Unknown format doesn't cause infinite loop. 
Well, the root cause seems not to be msgpack2json.

**Comment by rtartler-desres** [comment]
With 7b30b344e1d2d74380ea9fff721050d32b65cdaa, I'm starting `fluent-bit` like this:

```
   fluent-bit -i forward -o es -v
```

This results in tons of output like this:

```
[2017/03/15 07:54:26] [ warn] [msgpack2json] unknown msgpack type 9
[2017/03/15 07:54:26] [ warn] [msgpack2json] unknown msgpack type 9
[2017/03/15 07:54:26] [ warn] [msgpack2json] unknown msgpack type 9
[2017/03/15 07:54:26] [ warn] [msgpack2json] unknown msgpack type 9
[2017/03/15 07:54:26] [ warn] [msgpack2json] unknown msgpack type 9
[2017/03/15 07:54:26] [ warn] [msgpack2json] unknown msgpack type 9
```

My td-agent config looks like this:

```
2017-03-15 07:54:14 -0400 [info]: using configuration file: <ROOT>
  <source>
    @type tail
    format syslog
    path "/var/log/local1"
    tag "syslog.local1"
    <parse>
      @type syslog
    </parse>
  </source>
  <match **>
    @type forward
    flush_interval 1s
    <server>
      name "fluentbit on elasticsearch"
      host "virtenlogstash1.virten"
    </server>
    <buffer tag>
      flush_interval 1s
    </buffer>
  </match>
</ROOT>
```

The bug is triggered only after I syslog something with this command: `logger -p local1.info test message4`. Syslog is configured to write to `/var/log/local1` in this case, and the message indeed appears there.

**Comment by edsiper** [comment]
@rtartler-desres 

would you please paste the full output of Fluentd as well details of the version you are using ?

**Comment by nokute78** [comment]
@edsiper 
Is a problem that fluent-bit can't handle Eventtime of fluentd?
Eventtime is represented with MSGPACK_OBJECT_EXT (#193 I researched)

I added a skeleton to support nanosecond. Just work in progress...
https://github.com/nokute78/fluent-bit/tree/nanosec1

**Comment by edsiper** [comment]
@nokute78 

> Can fluent-bit handle Eventtime of fluentd?

Not yet

Thanks for pointing out your work on nanosecond support stuff. Actually is very related, I will jump into looking at it after 0.11 release.

**Comment by rtartler-desres** [comment]
@edsiper 

I'm using the td-agent RPM for centos6: `td-agent-2.3.4-0.el6.x86_64`

With commit 22fdf0f31cb149ce25dfbce18e25fbeb5a787d7b I no longer see the message about unknown message type, but the message does not make it to es.

To confirm, I've added an additional source to the config:

```
<source>
  @type forward
</source>                                                                                                                          
```

And could confirm that messages submitted with my simple https://github.com/fluent/fluent-logger-python application do get routed to es, but not messages that came in via `in_tail`.

Is this because `in_tail` contains Eventtime data that fluent-bit does not understand? That would disqualify fluent-bit for my use-case :-(

**Comment by edsiper** [comment]
Even if you are not getting your messages on elasticsearch the missing nanosecond resolution stuff should not be an issue.

**Comment by edsiper** [comment]
@rtartler-desres 

One more favor, since we need an easy case to replicate the problem would you please help us to collect the raw message sent by Fluentd out forward ?, this can be done easily: Instead of run Fluent Bit with in_forward, start netcat tool:

```
$ netcat -l 24224 > forward.dat
```

Once fluentd flushes the data, netcat will write the raw TCP message to forward.dat

**Comment by rtartler-desres** [comment]
@edsiper 

When I try that, the foward.dat file remains at 0 bytes all the times. In addition, I see this in td-agent.log:

```
2017-03-15 14:34:00 -0400 [warn]: temporarily failed to flush the buffer. next_retry=2017-03-15 14:34:34 -0400 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3ff0c4654ce0"
2017-03-15 14:34:00 -0400 [warn]: suppressed same stacktrace
```

**Comment by edsiper** [comment]
hmmm so Fluentd could not reach netcat (TCP port 24224)

**Comment by nokute78** [comment]
The command name is "nc" on CentOS.( not netcat)

The log of msgpack2json means fluentbit got a record from fluentd.

How about using filter_stdout to reveal records between in_forward and out_es?
You can use filter_stdout with appending "-F filter_stdout -m '*'"

**Comment by edsiper** [comment]
I faced a similar issue where I cannot longer ingest data into elasticsearch. 

I've logged this issue for troubleshooting:

https://github.com/fluent/fluent-bit/issues/211

**Comment by edsiper** [comment]
for the record: #211 have been fixed.
