### ISSUE TITLE
Windows version depends on Microsoft Visual C++ 2015 Redistributable

### ISSUE THREAD

**Issue by farcop** [fluent/fluent-bit#2101]
## Bug Report

https://fluentbit.io/releases/1.4/td-agent-bit-1.4.2-win64.exe
Reproduces @ td-agent-bit-1.5.0-win64.exe too.
Windows Server 2016 Standart

Without Microsoft Visual C++ 2015 Redistributable installed fluent-bit.exe hangs with
![изображение](https://user-images.githubusercontent.com/3578167/79133969-97f21a00-7db5-11ea-9f89-670854f63467.png)

After Microsoft Visual C++ 2015 Redistributable installed from https://www.microsoft.com/en-us/download/confirmation.aspx?id=52685 fluent-bit.exe works as expected.

**Comment by farcop** [comment]
12 runtime librarys in dependancy absent at clean install of Windows Server 2016 with Dependancy Walker
![изображение](https://user-images.githubusercontent.com/3578167/79155201-7440cb00-7dd9-11ea-86c4-0dcc29aa559d.png)

**Comment by fujimotos** [comment]
@farcop I've been aware of this problem. Right now we need to install MSVC
DLLs to run Fluent Bit, which is somewhat cumbersome.

My current idea is to static link them to fluent-bit.exe, so that we can run the
executable on systems without required DLLs. I'll find some time to work on this
issue, so wait for me.

**Comment by fujimotos** [comment]
@farcop FYI, I have posted a fix for this issue to #2170 .
A test build is available on https://github.com/fluent/fluent-bit/issues/960#issuecomment-626422545.

I appreciate if you can test it and see if it works for you.

**Comment by farcop** [comment]
Fixed. 
This issue can be closed now.
@fujimotos Thank you!
