### ISSUE TITLE
Kafka ouput doesnt support in td-agent-bit windows 1.4.2v

### ISSUE THREAD

**Issue by 27bharath** [fluent/fluent-bit#2103]
As per the release td-agent-bit 1.4.2 , Kafka (Output) is enabled, but not able to load kafka plugin

OS : windows 

C:\Program Files\td-agent-bit\bin>fluent-bit -c ..\conf\fluent-bit.conf

Fluent Bit v1.4.2
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Output plugin 'kafka' cannot be loaded
Error: You must specify an output target. Aborting

**Comment by fujimotos** [comment]
Yes, we don't enable out_kafka by default on Windows build.

This is due to `out_kafka`'s dependance on OpenSSL and it caused deployment
problems to many users. You can still enables the plugin by setting
`-DFLB_OUT_KAFKA` to the build configuration.

```
% cmake .. -DFLB_OUT_KAFKA=On`
% cmake --build .
```

**Comment by fujimotos** [comment]
Close this issue as duplication of #1944
