### ISSUE TITLE
tail input Format option not working in v1.4.2

### ISSUE THREAD

**Issue by k-y** [fluent/fluent-bit#2106]
## Bug Report

**Describe the bug**
The `Format` option of the tail input plugin is no longer working after upgrading from 1.3.7 to 1.4.2.  Downgrading back to 1.3.7 restores the previous working operation.

**To Reproduce**
Upgrade to 1.4.2; systemctl start td-agent-bit and check syslog for error
- Snippet of td-agent-bit.conf:
```
[INPUT]
    Name        tail
    Format      regex
    Parser      syslog-rfc5424
    Path        /var/log/*.log
...
```
- Example syslog message:
```
[error] [config] tail: unknown configuration property 'Format'
```

**Expected behavior**
A working td-agent-bit.conf should not require any changes when upgrading to 1.4.2

**Your Environment**

* Version used: v1.4.2
* Configuration:
* Operating System and version: Debian Buster 10.3 
* Filters and plugins: tail

**Comment by edsiper** [comment]
@k-y 

We unlikely break a configuration name, unless it is necessary and when done is advised with a deprecation notice for months. In this case I think you had a configuration issue just noticed on 1.4

On Fluent Bit v1.4 we added an extra layer of configuration validation so any unknown property given to a plugin will raise an error. For short, ```Format``` is not a property supported by ```tail``` input plugin. 

I think the ```Format``` you have there is wrong and likely you want to have it in the parsers configuration file.
