### ISSUE TITLE
Microsoft Defender reports td-agent-bit-1.4.2-win64.exe might be harmful

### ISSUE THREAD

**Issue by pjxiao** [fluent/fluent-bit#2108]
## Bug Report

**Describe the bug**

After the installer downloaded using Edge (81.0.416.53), Microsoft Defender reported the installer might be harmful

**To Reproduce**

1. Download td-agent-bit from [the official web site](https://docs.fluentbit.io/manual/installation/windows) using Edge
2. Wait for download to finish
3. Edge reports that warning

**Expected behaviour**

Download is completed without any warnings

**Screenshots**

![2020-04-16_17h05_26](https://user-images.githubusercontent.com/1007994/79434190-f3681600-8008-11ea-84a6-aaf7ea68e2fc.png)

**Your Environment**

* Version used: `td-agent-bit-1.4.2-win64.exe` (installer)
* Configuration: n/a
* Environment name and version (e.g. Kubernetes? What version?): n/a
* Server type and version: n/a
* Operating System and version:
    * Windows 10 Pro 10.0.18363 Build 18363
    * Edge (Chromium based) 81.0.416.53
* Filters and plugins: n/a

**Additional context**

* A lack of a sign or publisher of the installer may cause this problem.
* This problem may be Defender's one
* The hash was matched:

```pwsh
C:\Users\xiao\Downloads> Get-FileHash .\td-agent-bit-1.4.2-win64.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          F022AE48797E905CED9F9FE52B9B395605BF20AD4CAD22AA216D359927468ACE       C:\Users\xiao\Downloads\td-agent-bit-1.4.2-win64.exe

C:\Users\xiao\Downloads> $(Get-FileHash .\td-agent-bit-1.4.2-win64.exe).Hash -eq 'f022ae48797e905ced9f9fe52b9b395605bf20ad4cad22aa216d359927468ace'
True
```

**Comment by fujimotos** [comment]
The EXE binary is a legitimate one. It is exactly the same file with
the one fresh out of our build server.

```
$ wget -q -O fluent-bit-1.4.2-win64.exe https://ci.appveyor.com/api/buildjobs/4qid6pw1it34wld9/artifacts/build%2Ftd-agent-bit-1.4.2-win64.exe
$ sha256sum fluent-bit-1.4.2-win64.exe 
f022ae48797e905ced9f9fe52b9b395605bf20ad4cad22aa216d359927468ace  fluent-bit-1.4.2-win64.exe
```

Probably we need to sign the binary to prevent that security alerts on Windows.
We need to find some way to automate the signing.
