### ISSUE TITLE
could not get meta for POD <pod_name> and no kubernetes metadata for fluentbit sidecar

### ISSUE THREAD

**Issue by kiich** [fluent/fluent-bit#2111]
## Bug Report

**Describe the bug**
I'm using fluentbit 1.3.11 as a side car to my pod to collect my app's gc.log and using input `tail` to collect using the following config:
```
    [INPUT]
      Name              tail
      Tag               gc.${POD_NAME}_${POD_NAMESPACE}.*
      Path              /tomcat/logs/gc.log
      Path_Key          source_path
      Parser            gc
```
with filter config of:
```
    [FILTER]
        Name                kubernetes
        Match               gc.*
        Kube_Tag_Prefix     gc.
        Regex_Parser        k8s-metadata
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        tls.verify          Off
        Merge_Log           Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
```

with parser config for k8s-metadata looking like:
```
    [PARSER]
      Name         k8s-metadata
      Format       regex
      Regex        ^(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^.]+)\.(.*)\.log$
```

But i see in the fluentbit side car log:
```
Fluent Bit v1.3.11
Copyright (C) Treasure Data

[2020/04/17 20:26:49] [ info] [storage] version=1.0.3, initializing...
[2020/04/17 20:26:49] [ info] [storage] in-memory
[2020/04/17 20:26:49] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/04/17 20:26:49] [ info] [engine] started (pid=1)
[2020/04/17 20:26:49] [ info] [filter_kube] https=1 host=kubernetes.default.svc.cluster.local port=443
[2020/04/17 20:26:49] [ info] [filter_kube] local POD info OK
[2020/04/17 20:26:49] [ info] [filter_kube] testing connectivity with API server...
[2020/04/17 20:26:49] [error] [filter_kube] upstream connection error
[2020/04/17 20:26:49] [ warn] [filter_kube] could not get meta for POD podname-8d96f89b9-jr2f2
[2020/04/17 20:26:49] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2020/04/17 20:26:49] [ info] [sp] stream processor started
```

Notice the warn of not being able to get the metadata for POD.
And when i query the result in Splunk, i do not see any kubernetes metadata there.

However, everything i have seen from other github issues on this issues checks out.
1) Connectivity to the API server is fine in that it does connect and not blocked.
2) The service account for namespace does have the necessary rbac configured to be able to do the verbs as per docs
3) tail Tag regex and parser regex also checks out ok on rublur and does capture the right fields ok.
4) Even though the error is there, when i put tls.debug to 4, the log does show some information about the namespace/pod so it does look like it is getting the info -> this is the bit i do not understand as it does seem to be able to connect to api server ok but no metadata is present in Splunk event.

I've tried to put level to `trace` but nothing obvious i can see.
thanks

**Comment by kiich** [comment]
As further info, in debug mode, i can see:

[2020/04/20 13:49:34] [debug] [filter_kube] API Server (ns=namespace, pod=podname-8d96f89b9-jr2f2) http_do=0, HTTP Status: 200

so it does seem to be able to connect to API server fine

**Comment by teoincontatto** [comment]
Seems that if the pod resource JSON returned by the kubernetes REST API is bigger than `Buffer_Size` the plugin fail silently. IMO is a bug since the `flb_http_do` should return an error when response is bigger than what was set with `flb_http_buffer_size` (see https://github.com/fluent/fluent-bit/blob/ff0874f9cdeb0a7e3dfcc663f5088f64b2eba33e/plugins/filter_kubernetes/kube_meta.c#L240).

To solve the problem I had to increase `Buffer_Size`.

**Comment by slewiskelly** [comment]
I'm seeing the same thing, I only see this error for Fluent Bit pods.

I set `Buffer_Size 0`, but this still does not seem to resolve it

>  A value of 0 results in no limit, and the buffer will expand as-needed.

**Comment by teoincontatto** [comment]
@slewiskelly not sure if we have the same exact issue. I tested using `Buffer_Size 0` and it also fix the behavior.

**Comment by awprice** [comment]
We've experienced this as well after upgrading to Kubernetes 1.18. Kubernetes 1.18 introduces a new field called `managedFields`, which allows the server-side apply functionality - https://kubernetes.io/docs/reference/using-api/server-side-apply/

So when performing a get for the pod, this new field was included in the response. This field is really large and verbose, as it contains metadata about the fields in the pod spec. As a result this exceeded the buffer size and no metadata is retrieved for pods that are large enough.

There is some discussion about the `managedFields` here - https://github.com/kubernetes/kubernetes/issues/90066

**Comment by lucasvmiguel** [comment]
Lost a good few days trying to find what was the issue with my cluster. Although is documented [here](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#configuration-parameters), it's hard to connect this silently drop of logs with logs not showing up in `fluentd`.

Therefore, it would be good to have some kind of `warn`/`error` log in `fluent-bit` to detect this "failure".

**Comment by Queetinliu** [comment]
I face the problem because fluent-bit parse wrong pod name,i had to combine tag with Kube_Tag_Prefix, i can not use default value.
