### ISSUE TITLE
Kafka output to Azure event Hub | security.protocol property error - ubuntu 18.04.4 - Fluent-Bit 1.4.2

### ISSUE THREAD

**Issue by anagha-microsoft** [fluent/fluent-bit#2115]
## Bug Report

**Issue:**
Running into issues producing to Kafka with the error:
[2020/04/19 23:44:47] [ info] [storage] version=1.0.3, initializing...
[2020/04/19 23:44:47] [ info] [storage] in-memory
[2020/04/19 23:44:47] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/04/19 23:44:47] [ info] [engine] started (pid=85205)
[2020/04/19 23:44:47] **[error] [output:kafka:kafka.0] cannot configure 'security.protocol' property**
[2020/04/19 23:44:47] [ warn] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:app]: Configuration property `sasl.mechanism` set to `PLAIN` but `security.protocol` is not configured for SASL: recommend setting `security.protocol` to SASL_SSL or SASL_PLAINTEXT
....

**Kafka specifics:**
Producing to Azure Event Hub with Kafka protocol - compatible with Apache Kafka
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quickstart-kafka-enabled-event-hubs

**Conf:**
Ubuntu 18.04.4 VM 
Fluent-Bit 1.4.2
FLB_TLS is on

[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path                apache-sample.log
    Parser            apache
    DB                /var/log/flb_tail.db
    Mem_Buf_Limit     7MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     myEventHubNamespace.servicebus.windows.net:9093
    Topics      apache-log-topic
    Retry_Limit    2
    rdkafka.security.protocol SASL_SSL
    rdkafka.sasl.mechanism PLAIN
    rdkafka.sasl.username "$ConnectionString"
    rdkafka.sasl.password "myEventHubConnectionString"
    rdkafka.....

**Attempted:**
I read this issue -> https://github.com/fluent/fluent-bit/issues/632
Assumed that installing equivalent of openssl-devel on centos, I think its libssl-dev for Ubuntu, would resolve.  But it did not help.

**Impact:**
Blocked by this issue for a customer;  Very new to Fluent-Bit.  Appreciate your support very much.

**Comment by l2dy** [comment]
> Assumed that installing equivalent of openssl-devel on centos, I think its libssl-dev for Ubuntu, would resolve. But it did not help.

Did you compile Fluent Bit with libssl-dev installed? Installing the OpenSSL headers without re-compiling the binary would not work.

**Comment by anagha-microsoft** [comment]
Thanks.
I switched to working on containers and am unblocked.
For anyone wanting to integrate with Azure Event Hub...
`
    Brokers     YourAzureEventHubNamespace.servicebus.windows.net:9093
    Topics      YourAzureEventHub
    rdkafka.security.protocol SASL_SSL
    rdkafka.sasl.mechanism PLAIN
    rdkafka.sasl.username $ConnectionString
    rdkafka.sasl.password YourAzureEventHubNamespaceConnectionString
    rdkafka.ssl.sa.location "/usr/lib/ssl/certs/"
`

This ticket can be closed.
Will share an end to end sample shortly featuring container logging on Azure Kubernetes Service, with output to Azure Event Hub and log analytics with Azure Data Explorer.

**Comment by jmcshane** [comment]
Just a note for future readers of this issue, the rdkafka property is:

```
rdkafka.ssl.ca.location "/usr/lib/ssl/certs/"
```

**Comment by joshuafernandes** [comment]
@anagha-microsoft many thanks for the tip for the docker container, for some bizarre reason the native package doesn't quite work but the container does and am unblocked as well

**Comment by MagicJohnJang** [comment]
Worked for me using kafka output to Azure EventHub

_td-agent-bit.conf_
```
[INPUT]
  Name                tail
  Path                xxx.log
  Refresh_Interval    10

[OUTPUT]
  Name        kafka
  Match       *
  brokers     xxx.xxx.windows.net:9093
  topics      xxx
  rdkafka.security.protocol   SASL_SSL
  rdkafka.sasl.username       $ConnectionString
  rdkafka.sasl.password       Endpoint=sb://xxx.xxx.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxx
  rdkafka.sasl.mechanism      PLAIN

[OUTPUT]
  name  stdout
  match *
```

Inside docker container (MUST HAVE or broker down/ssl fail)
_docker-compose.yml_
```
version: "3.7"
services:
  fluent-bit:
    image: fluent/fluent-bit:1.6.2
    container_name: fluentbit
    restart: always
    volumes:
      - ./td-agent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./xxx.log:/fluent-bit/etc/xxx.log:ro
```

**Comment by iljoong** [comment]
I build custom 'fluent-bit' from the latest source and it works well. Please see my [my build script](https://gist.github.com/iljoong/1f0edabd6e6fbd05272b71f1f141bf86) for more information.
