### ISSUE TITLE
After a crash, fluent-bit send the same event multiple times

### ISSUE THREAD

**Issue by rmarchei** [fluent/fluent-bit#2123]
## Bug Report

**Describe the bug**
when using the tail input plugin, after fluent-bit crashes and restarts, some events are sent to the output multiple times

**To Reproduce**
Use the following conf:
```
[SERVICE]
    flush                     1
    daemon                    off
    log_level                 info
    storage.path              /var/lib/fluentbit/storage
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5m
```
```
[PARSER]
    Format              regex
    Name                test
    Regex               ^(?<time>\s+): (?<message>.+)$
    Time_Format         %s
    Time_Keep           On
    Time_Key            time
```
```
[INPUT]
    Alias               tail.test
    DB                  /var/lib/fluentbit/test.db
    DB.Sync             Full
    Key                 test
    Multiline           Off
    Name                tail
    Parser              test
    Path                /tmp/test.log
    Refresh_Interval    10
    Rotate_Wait         10
    Tag                 test
    storage.type        filesystem
```
```
[OUTPUT]
    Format              plain
    Match               test
    Name                file
    Path                /tmp/test.json
```

- Steps to reproduce the problem:
We can generate a random log with unique events using this command:
```
for n in $(seq 1 100000); do echo "$(date +%s): $n" >> /tmp/test.log; sleep 0.001; done
```
input log (`/tmp/test.log`) will then look like:
```
1587477157: 1
1587477157: 2
...
1587477333: 20484
1587477333: 20485
```

output log (`/tmp/test.json`) will look like:
```
{"test":"1587477157: 1"}
{"test":"1587477157: 2"}
```
while the for loop is running, kill fluent-bit to force a crash recovery:
```
killall -9 fluent-bit
```
Once fluent-bit restarts, it keeps applying new events and recovers the missing ones, while adding lots of duplicates.

If you stop the for loop now and wait few seconds, you can check the input log and the output:
```
# wc -l /tmp/test.log /tmp/test.json
  23536 /tmp/test.log
  24068 /tmp/test.json
  47604 total
```
the output file `test.json` contains all the previous events that fluent-bit didn't send while crashing, but also some duplicated events. After removing duplicated events, it's possible to confirm it didn't miss a single entry, but just duplicated some of them:
```
# uniq /tmp/test.json |wc -l
23536
```
Checking the content of the output file, it's possible to see that an event has been sent multiple times, while present only once in the input log:
```
# cat /tmp/test.json|sort|uniq -c|sort -nr|head -n 3
    533 {"test":"1587477240: 4922"}
      1 {"test":"1587477333: 20485"}
      1 {"test":"1587477333: 20484"}
```

**Expected behavior**
fluent-bit doesn't send the same event multiple times

**Your Environment**
* Version used: 1.4.2
* Operating System and version: Ubuntu 18.04
* Filters and plugins: Tail and File Output

**Comment by rmarchei** [comment]
this seems not to be resolved yet

**Comment by keeth** [comment]
seeing that here too, using the s3 plugin. service restart causes fluent-bit to push duplicates to GCS. this behavior makes fluent-bit unusable for me unfortunately.
