### ISSUE TITLE
Environment variable for http_passwd causes 401

### ISSUE THREAD

**Issue by nicknickel** [fluent/fluent-bit#2124]
## Bug Report

**Describe the bug**
I'm using fluentbit in kubernetes to forward to elastic. I've got a kubernetes secret that is set to the HTTP_passwd for elasticsearch and is set as an environment variable on the fluentbit daemonset. It gets exported in such a way where I can use ${ELASTICSEARCH_PASSWORD} in the configmap for the HTTP_Passwd value in the es output configuration. When I set the HTTP_passwd option to the ${ELASTICSEARCH_PASSWORD} variable, I get a 401 error. When I set it to the password in plain text, it works. I verified that the variable is getting set correctly by setting the pipeline configuration value to ${ELASTICSEARCH_PASSWORD} and saw in the elastic ingester logs that fluentbit was trying to send to `_bulk/?pipeline=<my​​​​​​​_password>`. There are no spaces or special characters in the password.

**To Reproduce**
WORKS
```
    [OUTPUT]
        Name            es
        ...
        HTTP_Passwd    <plain_text_password_removed>
	...
```

DOES NOT WORK
```
    [OUTPUT]
        Name            es
        ...
        HTTP_Passwd     ${ELASTICSEARCH_PASSWORD}
        ...
```

SENDS TO `_bulk/?pipeline=<plain_text_password_removed>`
```
    [OUTPUT]
        Name            es
        ...
        HTTP_Passwd    <plain_text_password_removed>
        Pipeline        ${ELASTICSEARCH_PASSWORD}
        ...
```

- Steps to reproduce the problem:
1. Create a kubernetes secret that is the password for your elasticsearch instance
2. Set that as an environment variable on your fluentbit daemonset
3. Set that environment variable as the HTTP_Passwd configuration value in the es output configuration in your daemonset's configmap
4. Try to forward logs to elasticsearch

**Expected behavior**
Basic authentication to occur using the contents of the variable for the password.

**Your Environment**
* Version used: 1.3.4
* Configuration: also forwarding to splunk, which works as expected with a token. We also use other environment variables in our configmap that work as expected.
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.15.6
* Filters and plugins: es plugin

**Additional context**
We don't want to store the password as plain text in our helm chart we use to generate the fluentbit configuration. We'd like to store the password as a secret.

**Comment by chantal-rose** [comment]
Did you find a fix for this issue?

**Comment by nicknickel** [comment]
I did not. I ended up using a plain text password.

**Comment by manusabu11** [comment]
Hi , anyone got a solution for this
