### ISSUE TITLE
shutdown delayed, grace period has finished but some tasks are still running

### ISSUE THREAD

**Issue by yiwenshao** [fluent/fluent-bit#2135]
## Bug Report

**Describe the bug**
I am trying to test how fluent-bit ensure data integrity under network failure. I used tail as input and elasticsearch as output. The storage.type was filesystem. Since network was unreachable, fluent-bit stored data in local buffer, in my case in the tail.0 directory. Then I tried to update configuration of fluent-bit, so I used `kill pidof fluent-bit` to shutdown fluent-bit gracefully. 
However, I got the error **shutdown delayed, grace period has finished but some tasks are still running** and fluent-bit wouldn't shutdown. I had  to use `kill -9 pidof fluent-bit` to restart fluent-bit, but this method seemed to result in `invalid crc32` error, which caused data lose.

**To Reproduce**

my configuration is as follws

+ fluent-bit.conf

```
[SERVICE]
    # This is a commented line
    Daemon    off
    flush                     1
    log_Level                 debug
    storage.path              /data/hostpath/fluent-bit/buffer
    storage.sync              normal
    storage.checksum          on
    storage.backlog.mem_limit 30M
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020

@INCLUDE conf/*.conf

```
+ the configuration in conf/

```
[INPUT]
    Name tail
    Mem_Buf_Limit 1M
    Buffer_Chunk_Size 32KB
    storage.type  filesystem
    Buffer_Max_Size  64KB
    Path /data/hostpath/fluent-bit/logs/log.block
    DB /data/hostpath/fluent-bit/pos/log.block.pos
    Tag log.block.*
    Path_Key file

[OUTPUT]
    Name  es
    Retry_Limit False
    Match log.block.*
    Host 192.168.0.12
    Port 9201
    Index test
    Type _doc
```

- Steps to reproduce the problem:

    + the elasticsearch port 9201, which is used only to mock network failure, is not reachable. Simple shell script is used to generate log in log.block.

    ```
    for i in {1..100};do echo $i >> log.block ;done
    ```

    + since port 9201 is unreachable, data is stored in /data/hostpath/fluent-bit/buffer/tail.0/

    + use `kill pidof fluent-bit` to try to restart fluent-bit, and fluent-bit keeps printing the following message:
    ```
    [ warn] [engine] service will stop in 5 seconds
    [ info] [engine] service stopped
    [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.
    [ info] [task] tail/tail.0 has 1 pending task(s):
    ..... 
    ```
    + if I use `kill -9 pidof  fluent-bit`to restart fluent-bit, then fluent-bit will complain
    ```
    [debug] [storage] [cio file] invalid crc32 at 794-1588045968.68490874.flb/ /data/hostpath/fluent-bit/buffer/tail.0/794-1588045968.68490874.flb
    ```
    those data could not be deviered to elasticsearch even when the port is changed to 9200(which is the correct elasticsearch port).

**Expected behavior**

+ `kill pidof fluent-bit` is able to shutdown fluent-bit gracefully

**Your Environment**

* Version used: 1.4 
I used tag 1.4: https://github.com/fluent/fluent-bit/tree/1.4 to build docker image for my testing

**Comment by luxmeter** [comment]
Encountered this today also with 1.4.6.
Fluent-bit is running as a side-car container in a job but it doesn't want to shut down gracefully. It just delays the shutdown forever. Have to force kill it now 😢
