### ISSUE TITLE
[out_kafka] Generate_ID feature request

### ISSUE THREAD

**Issue by simonasr** [fluent/fluent-bit#2139]
**Is your feature request related to a problem? Please describe.**
We want to prevent log duplicates when re-consumed from Kafka backlog (in case we need to 'replay' logs from Kafka to fix some data loss caused by fluentd or ES problem)
Our pipeline:
```
+-----------+        +-----------+        +-----------+        +-----------+
| Fluentbit |  ----> |   KAFKA   |  ----> |   Fluend  |  ----> |   ES      |
+-----------+        +-----------+        +-----------+        +-----------+
```
**Describe the solution you'd like**
`out_kafka` plugin could generate and add key with `random ID` to the record.
This key later would be used as `_id` in ElasticSearch.

**Describe alternatives you've considered**
Currently we are using Fluentd plugin `genhashvalue` which calculates hash for the log, but this is not very elegant solution for the problem.
It would be great if Fluentbit adds random ID to the record

**Additional context**
🙏

**Comment by vikasmishra17** [comment]
Hi,

we have followed the same configuration as shown in https://github.com/fluent/fluent-bit/pull/2268

But in the output the hash id is not generating 

My output configuration

[OUTPUT]
    name  kafka
    match *
    brokers X.XX.XX.XX:9092,XX.XX.XX.:9092,XX.XX.XX:9092
    topics syslogs-id
    Hash On
    Hash_Key _myid
    retry_Limit false
