### ISSUE TITLE
When non utf 8 character is encountered, rest of the line should be processed

### ISSUE THREAD

**Issue by olagacek** [fluent/fluent-bit#2142]
## Bug Report

**Describe the bug**

When incorrect, non UTF 8 character is encountered fluent bit skips the rest of the log line, while it would be better to just skip incorrect character end process the rest of the log line.

See https://github.com/fluent/fluent-bit/blob/ed823cf5cbdc89db1f304a6716b633c51d1c933e/src/flb_sds.c#L255

- Steps to reproduce the problem:
[INPUT]
    Name tail
    Path file.incorrect
[OUTPUT]
    Name file
    Path output

put incorrect character in file.incorrect (for example editing with hexedit and creating incorrect sequence)
**Expected behavior**

Incorrect character is skipped while the rest is processed as usual.

**Your Environment**

* Version used: 1.4

**Comment by juliohm1978** [comment]
Just ran into this issue. Can this be reopened?

**Comment by agup006** [comment]
@juliohm1978 would you be able to create a new issue with a repro with the latest version?

**Comment by juliohm1978** [comment]
Thanks, @agup006.

I hope this can be treated or worked around somehow: https://github.com/fluent/fluent-bit/issues/5035
