### ISSUE TITLE
Build a Monitoring Web UI 

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#2147]
[DISCLAIMER] This is a CNCF community bridge project

Fluent Bit exposes internal metrics from the data processing pipeline through its HTTP interface. This project aims to build a Web UI to show the components of the data pipeline and its continuous metrics with dashboards and further info. The metrics are exposed in JSON format and should be scrapped by the UI. 

The UI must have a professional-looking and should be written with extensibility in mind. Note that the Web UI must not depend on NodeJS, it needs to be deployable from any web server.

The project will be in a continuously evolving model. So we expect the intern to be available for continuous work for the whole period. 

## Intern Requirements

- General
  - Invest at least 30 hours per week
  - Daily communication with the mentor
  - Aligned with America's timezone. We primary look for candidates in America's time zone, but open for other timezones for the right person (proof of skills and similar work done in the past)
- Mandatory Skills
  - Javascript
  - Vue JS 
  - CSS
  - HTML
  - Design

## How to Apply

Please submit an introductory email with the subject "CNCF / Fluentd Internship" to _eduardo at treasure-data.com_ with the following information:

- Github Profile 
- Do you have a blog ?, URL ?
- URLs of previous work associated with Vue JS, Javascript, and CSS
- Experience with REST APIs ?
- Have you used Fluent Bit ?, if so, please share your use case and experience
- Besides the bounty ($$), what's attractive for you to contribute to this project?
- In which country you will perform your work?
- Can you invest at least 30 hours a week in the project ? (continuous business days) 
- Are you willing to learn ?
- Tell us more about you

**Comment by championshuttler** [comment]
Hey @edsiper! I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it?


Thanks

**Comment by edsiper** [comment]
All, please check the new "How to apply" section above.

**Comment by Dhiraj240** [comment]
@edsiper I have just sent you the email using my gmail id dhiraj.8.sharma@gmail.com where I wrote about the detailed specifications of my expertise.
Also I have applied on Community Bridge.
Hoping to getting interviewed and selected.
Looking forward to it.

**Comment by edsiper** [comment]
@Dhiraj240 thanks, email received.

**Comment by ojaswa1942** [comment]
Hello @edsiper ! This seems interesting, however, are you also considering ReactJs for the project?

**Comment by agarwalrounak** [comment]
Hi @edsiper! I have applied on Community Bridge for this project and have even sent you an email with all the information. 
I have earlier worked on building a web UI for [Kruize](https://github.com/kruize/kruize) where I created dashboards for resource monitors. This helped users get a better visual sense of the recommendations offered by the tool and helped adoption of containers in general.
I suggest that we use [chart.js](https://www.chartjs.org/) to build the dashboards. There is even a Vue.js wrapper for Chart.js: https://vue-chartjs.org/. This will enable us to create reusable chart components.

**Comment by Dhiraj240** [comment]
@edsiper Sir I have mailed you my reference and personal issue.
Also, I would like to work on the issue which I asked to get it assigned to me. Can I fix that?

**Comment by ojaswa1942** [comment]
@edsiper Has there been some changes regarding fluentd or this project ? Can't find the same in selected projects at [cncf/mentoring](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/selected_projects.md) :confused:.

**Comment by edsiper** [comment]
CNCF will announce results shortly
