### ISSUE TITLE
Fluentbit to Splunk HEC forwarding issue

### ISSUE THREAD

**Issue by lordfrimpong** [fluent/fluent-bit#2150]
Good Afternoon,

I currently have Fluentbit deployed in an AWS EKS cluster, per the documentation I see there is an option to send output to Splunk but does it support Splunk HEC forwarding?  Please see error message below along with output config.  Thank you.

Error: Error: [2020/05/01 15:29:52] [ warn] net_tcp_fd_connect: getaddrinfo(host='https://splunk-hec.uscis.dhs.gov:8088/services/collector'): Name or service not known
[2020/05/03 18:38:56] [ warn] [engine] failed to flush chunk '1-1588531130.7570918.flb', retry in 10 seconds: task_id=0, input=tail.0 > output=splunk.0
[2020/05/03 18:38:56] [ warn] [input] tail.0 paused (mem buf overlimit)
[2020/05/03 18:38:56] [ warn] [engine] failed to flush chunk '1-1588531130.37208447.flb', retry in 7 seconds: task_id=1, input=tail.0 > output=splunk.0

    [FILTER]
        Name        modify
        Match       *
        Add index   <Splunk_Index>
        Add host    <EKS_Host_URL>

    [OUTPUT]
        Name        splunk
        Match       *
        Host        https://splunk-hec-url:8088/services/collector
        Splunk_Token <hec_token>
        Splunk_Send_Raw O

**Comment by edsiper** [comment]
what you are describing is a networking issue (not Fluent Bit), specifically in your DNS, for some reason your Pod cannot reosolve splunk-hec.uscis.dhs.gov:8088/services/collector:

```
Error: Error: [2020/05/01 15:29:52] [ warn] net_tcp_fd_connect: getaddrinfo(host='https://splunk-hec.uscis.dhs.gov:8088/services/collector'): Name or service not known
```

**Comment by edsiper** [comment]
I am closing this ticket since is not a Fluent Bit issue.
