### ISSUE TITLE
Apply `Tag` or `Merge_Log_Key` in `kubernetes` filter based on pod annotation value

### ISSUE THREAD

**Issue by astorath** [fluent/fluent-bit#2153]
**Is your feature request related to a problem? Please describe.**

Because elasticsearch indicies have strict mappings, it is sometimes difficult to route all json logs to one index type and have same parsing rules for them.

**Describe the solution you'd like**

I want to have an option to apply filters in kubernetes environment based on pod annotations. Very much like parsers work right now:

E.G.:
1. I annotate the pod with 'fluentbit.io/tag=my-service'.
2. `kubernetes` filter uses the annotation to build record `Tag` based on it: `kube.tag.my-service.container....` or smth via `K8S-Logging.Tag` option.
3. I can apply `modify` filter based on this `Tag` to alter the record: copy parsed field to specific container with predefined mappings in es index, e.g.: copy "parsed" json filed to `my-service` field.
4. I can use different es output based on tag to use separate index name.

**Describe alternatives you've considered**

1. I've tried to apply `rewrite_tag` filter to extract annotation values from pods meta, but it failed due to #2151
2. Now I have to use separate `fluentd` forwarder to modify records before sending them to elasticsearch

**Additional context**

An alternatives may be 
- creating a new parser that work with json data much like `modify` filter (e.g. not only parses incoming json, but also modifies it in some way).
- using annotation value described above to _name_ the `Merge_Log_Key` instead of just using a constant value.

**Comment by astorath** [comment]
Another case is defining ingestion pipeline based on some service annotations

**Comment by rjshrjndrn** [comment]
@astorath Did you figure out any solution for this ?

**Comment by astorath** [comment]
> @astorath Did you figure out any solution for this ?

I still use separate fluentd log aggregator due to #2152. Using lua is not an option: main fluent-bit selling point is memory efficiency and performance.
