### ISSUE TITLE
Removing Type Key on ES Output

### ISSUE THREAD

**Issue by ClavinJune** [fluent/fluent-bit#2155]
According to this [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html), **type** will be removed completely in v8.0.

Since the current *default key* is `flb_type` and uses custom_type, should the default key removed or changed the default key to `_doc` (typeless)?

**Comment by ted-sigsci** [comment]
I'm curious why this was self-closed.

**Comment by edsiper** [comment]
```
@ClavinJune ClavinJune closed this on May 11
```

**Comment by ted-sigsci** [comment]
To put it another way, I'm curious what @ClavinJune 's answer or workaround was.

**Comment by ClavinJune** [comment]
Hi @ted-sigsci I closed this because I saw this was the same issue with #1750
