### ISSUE TITLE
some of the Logs\data is missing when using fluentbit (windows).

### ISSUE THREAD

**Issue by vikranth06** [fluent/fluent-bit#2157]
## Bug Report

**Describe the bug**
We are using fluentbit as a forwarder of ours logs & data to fluentd, there is a mismatch in the log statements generated by our application and those reaching the defined output plugins (stdout, file, fluentd etc..). Sometimes we get all the logs, otherwise it would be 10% or 20 % of the statements we are supposed to receive.

**To Reproduce**
- Ours is a .Net application with log4net appender for logging, we are using a git hub project suggested in fluentbit documentation page https://github.com/fluent/NLog.Targets.Fluentd for integration and writing it to fluentbit. Apart from data loss we also see messages like below in fluentbit console:
```
 [ warn] [input:tcp:tcp.0] invalid JSON message, skipping
```
- Steps to reproduce the problem:
Simple integration with above git hub project should reproduce the issue.
**Expected behavior**
All logs are getting dumped if connected to FluentD, only when connecting to fluentbit we observe data loss.

**Screenshots**

**Your Environment**

* fluentbit Version used: 1.4.2
* Configuration:
[SERVICE]
    Flush      1
    Daemon     off
    Log_Level  info
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Tag	        xxxxxxx
    storage.type  memory

[OUTPUT]
    Name file
    Match xxxxxxx
    Path output.txt
* Operating System and version: Win 10 x64
* Filters and plugins:

**Additional context**
We want to ensure no logs or data is missed, so the data flow is Fluentbit -->FluentD --> ElasticSearch. For some reason if fluentd is down fluentbit would buffer all the data and same would be pushed once it is back.
Currently we are testing fluentbit on Win10, if all goes good then it would be deployed on Win2019 server. 
We have tried all possible configuration settings w.r.t fluentbit but nothing is working for us. 
Everything works fine if we connect to FluentD directly.
**Please help us out with this data loss issue on fluentbit.**

**Comment by edsiper** [comment]
would you please provide me a simple reproducible app that uses nlog that I can run on LInux to test it ?

**Comment by vikranth06** [comment]
Can a windows sample app do?? As we use .Net4.5 framework. Otherwise i would have to build the application using .Net core.

**Comment by vikranth06** [comment]
> would you please provide me a simple reproducible app that uses nlog that I can run on LInux to test it ?

@edsiper : i could create a simple app using .Net core, if you provide me your machine OS details then i can create a self contained app to be run as per https://stackoverflow.com/questions/46843863/how-to-run-a-net-core-console-application-on-linux . We are using fluentbit as a localhost running on port 5170, have configured the same in app too.

**Comment by edsiper** [comment]
ubuntu 20.04 here.

**Comment by vikranth06** [comment]
> ubuntu 20.04 here.

I am able build the application till 19.10, looks like for 20.04 appropriate runtime libraries are not released as i am getting this error "error NETSDK1083: The specified RuntimeIdentifier 'ubuntu.20.04-x64' is not recognized."
Can i share any of the previous OS binaries??

**Comment by edsiper** [comment]
or can you provide the payload that Fluent Bit receives and reproduce the issue ?

**Comment by vikranth06** [comment]
> or can you provide the payload that Fluent Bit receives and reproduce the issue ?

no, that wont help. Since even a simple payload like "hi" when sent 10 times is not reaching the o\p destination all the time. We are using the same mechanism or code to send data to Fluentbit & FluentD. In case of FluentD it's all good, but with fluentbit its the issue. Should the implementation differ for both of them?
Any other way to share the sample app so that you can help us with this issue?

**Comment by rahil-r** [comment]
Facing same issue: invalid JSON message, skipping

When trying to send 5 logs only 2 are written to target and rest are getting skipped with the above warning. Is there a fix? And the 6th log is giving 504 timeout. 

Input is of "http" type
And output is for a "file"
