### ISSUE TITLE
Neither "Daemon on" nor -d flag run fluent-bit process in background when using a flb.conf file

### ISSUE THREAD

**Issue by estroz** [fluent/fluent-bit#216]
After going through standard installation instructions (no flags used) and running `fluent-bit -c flb.conf`, the conf file containing the `Daemon on` k/v pair under "[SERVICE]", the `fluent-bit` file did not run as a background process. Neither did `fluent-bit -d -c flb.conf`, but `fluent-bit -d -i tail -p "Path=/var/log/test.log" -o stdout` daemonizes correctly.

fluent-bit version: `v0.10.1`

flb.conf file:
```
[SERVICE]
    Flush 5
    Daemon on

[INPUT]
    Name tail
    Path /var/log/test.log

[OUTPUT]
    Name stdout
    Match *
```

**Comment by edsiper** [comment]
hi @estroz 

thanks for report this problem.

I've just pushed a fix for this situation, would you please re-confirm in your side that the latest changes make it work properly ?

**Comment by estroz** [comment]
@edsiper thank you, the config file works with 'on' now. However it does not work with 'yes', and as per [the docs](http://fluentbit.io/documentation/0.11/configuration/file.html) the `Daemon` key should work with any of `yes`,`no`,`on`,`off`. As an enhancement/suggestion, I would restrict the options to `on` and `off` for simplicity, unless `yes`/`no` have special meaning in this context.

**Comment by edsiper** [comment]
thanks for catching up that missing part.

As a workaround I've just enabled: on, true and yes. The boolean value for the configuration needs to be flexible enough as the meaning comes from the variable name. Right now there are not many but that could change shortly.

**Comment by gopalakrishna-ch** [comment]
Daemon on config is not working

**Comment by edsiper** [comment]
it does:

![fork](https://user-images.githubusercontent.com/369718/82686029-63724900-9c12-11ea-9b18-45993a776cb1.png)

please open a new issue with further details.

**Comment by ripx80** [comment]
Hey, 
i try to use the "daemon on" in my config file on Windows Server but it always run in fg mode. 
If I try to start it as a service it always in state starting (because not switch to bg). 
And no -d flag on the command line but I found nothing about that in the documentation. Do you plan this in the future?
Any advice? Thanks for responding!
