### ISSUE TITLE
Mismatch in the time field in kibana UI and the time available in the log message [Log message is parsed using fluentd configuration]

### ISSUE THREAD

**Issue by VarunSrinivasa** [fluent/fluent-bit#2163]
Mismatch in the time field in kibana UI and the time available in the log message [Log message is parsed using fluentd configuration]

I have time stamp in the log message and time stamp is 2020-05-04T03:46:12.495Z and we are parsing the timestamp using below fluentd configuration
![image](https://user-images.githubusercontent.com/44157326/81194332-2b47f500-8fda-11ea-98b8-fe83cef41f74.png)

But there is mismatch in time field in kibana UI and the time available in the log message. Please refer the attached screenshot for reference.
![image](https://user-images.githubusercontent.com/44157326/81194463-4d417780-8fda-11ea-9796-f2975ff5a482.png)

Can you guys please help here.

**Comment by edsiper** [comment]
@VarunSrinivasa 

This is the [Fluent Bit](https://fluentbit.io) repository, not [Fluentd](https://www.fluentd.org), please open a new issue on Fluentd repository here:

https://github.com/fluent/fluentd/issues/new/choose
