### ISSUE TITLE
Multiple output plugin without parsing the data

### ISSUE THREAD

**Issue by basireddym** [fluent/fluent-bit#2164]
**Is your feature request related to a problem? Please describe.**

In current environment Kubernetes logs type "tail" is parsed using fluentbit to output Graylog in glef.
I've a requirement now, to have one more output plugin where the data should not be parsed by fluentbit and sent the raw data which is coming from kubernetes.

**Describe the solution you'd like**

Requirement is
![image](https://user-images.githubusercontent.com/64943722/81255208-bbbe1e00-904a-11ea-91f4-53a7dd117da0.png)

**Describe alternatives you've considered**

**Additional context**

Unfortunately, the gelf format logs are getting rejected by elastic search, due to the time_key parser which is added as metadata.

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

Change in the above parser will affect the graylog.

**Comment by edsiper** [comment]
if you put Kubernetes out of the equation, please provide a source log line in a file and the configuration that aims to ship it as a reproducible test case
