### ISSUE TITLE
[windows] Unable to recieve docker metric through stable in_docker metrics in docker desktop

### ISSUE THREAD

**Issue by Logixgroup** [fluent/fluent-bit#2165]
As far as I can tell, the in_docker plugin is released but un-documented.

I am using in_docker plugin with following cmd line  docker run -t -i --privileged --network=docker-efk_default 90fd123158fc  /fluent-bit/bin/fluent-bit -i docker -t docker -o stdout --verbose

Second approch is through configuration file 
[SERVICE]
      Flush 10
      Daemon off
      #Log_Level info
      Parsers_File parsers.conf

[INPUT]
      Name docker
      Include f3a124963829
      Tag docker
      Parser docker

[OUTPUT]
      Name es
      Match **
      Host elasticsearch
      Port 9200
      Index fluentbix-syslog
      Type dockerm

!Stdout results are not visible](https://user-images.githubusercontent.com/4848900/81262535-a7365180-905b-11ea-837c-44d8f46b6fcd.png)

We are unable to receive output in console or elastic search with both the above approaches.

**Expected** container metrics should be results of cmd i.e Docker stats: 

![Test](https://user-images.githubusercontent.com/4848900/81262767-10b66000-905c-11ea-9ef5-a55dbf630eb4.png)

------------------------------------------**Docker enviroment details** ------------------------------------
Server:
 Containers: 22
  Running: 5
  Paused: 0
  Stopped: 17
 Images: 27
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.846GiB
 Name: docker-desktop
 ID: ZZYW:KKM5:5JGF:SPKF:3XP5:K67P:3JQ4:4IXX:5CHG:6FJ6:LE64:BFZH
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 42
  Goroutines: 59
  System Time: 2020-05-07T06:46:25.570752217Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

PS D:\efk\elk\docker-efk>

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by edsiper** [comment]
I got confused, your configuration says "send the data to Elasticsearch", so why to expect to receive the data in the standard output interface ?, if that's your goal, you can add an extra [OUTPUT] section using the ```stdout``` output plugin.

**Comment by Logixgroup** [comment]
I have already tried with extra output section.. issue is Docker_metrics are not being captured. 

So i dont see them in elasticsearch or STDOUT with extra [OUTPUT] section. In logs too i doesnt print anything.

**Comment by edsiper** [comment]
@fujimotos can you take a look ?

**Comment by Logixgroup** [comment]
@fujimotos Pls take a look , here! thanks

**Comment by fujimotos** [comment]
@Logixgroup  I think I can have a look at this issue Monday.
Please wait for me.

**Comment by fujimotos** [comment]
>  I think I can have a look at this issue Monday.

So I was looking at this issue.

My memory is a bit fuzzy but AFAICT we never ported `in_docker` to
Windows. The only reason why we have this plugin in the current build
is that Ashutosh did not bother disabling the build toggle in #790.

As I'm looking at the code, I see several things to do to make the
plugin usable on Windows:

 * Convert various paths to match the file layout in Windows
 * Teach in_docker to retrive CPU metrics on Windows
 * Teach in_docker to retrive Memory metrics on Windows

Without these migrations, `in_docker` won't work properly on Windows.
