### ISSUE TITLE
out_http creates too many connections for sending backlog

### ISSUE THREAD

**Issue by r0naldt** [fluent/fluent-bit#2171]
**Is your feature request related to a problem? Please describe.**

I'm experiencing overload of my system when fluent-bit tries to send a backlog of logs at once through out_http with TLS enabled, creating tens of new http/tls connections simultaneously.

Examples when this can happen:
- The system was offline, logs were stored on disk. If after reboot (of system or fluent-bit) the system is online, then fluent-bit tries to send a lot of the stored data at once.
- Sending systemd logs via fluent-bit, from the beginning of journal. When starting fluent-bit there is lots of backlog to send.

**Describe the solution you'd like**
Could there be (or is there already?) a parameter to limit the number of simultaneous http connections?

**Describe alternatives you've considered**
I didn't succeed in limiting the amount of simultaneous outgoing connections with throttling. Or may be I didn't know how to do it properly.

**Comment by edsiper** [comment]
In your main [SERVICE] section you can add the following parameter:

```
storage.backlog.mem_limit 10M
```

that one will limit to process backlog data in rounds of 10M, that might reduce the number of outgoing connections required
