### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by SidGrundfos** [fluent/fluent-bit#2174]
Dear Team,
I am new to Fluent-bit configuration. Can you please help me with my issue here ?

Fluent bit is integrated with Humio in kubernetes cluster - 
fluentbit-input.conf
---------------------
[INPUT]
    Name             tail
    Path             /var/log/containers/*.log
    Parser           docker
    Tag              audit.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

fluentbit-filter.conf
---------------------
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_Tag_Prefix     kube.var.log.containers.
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log           On
    Merge_Log_Key       log_processed
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On

fluentbit-output.conf
---------------------
[OUTPUT]
    Name            es
    Match           kube.*
    Host            cloud.humio.com
    Port            9200
    Logstash_Format On
    Retry_Limit     False
    Type            flb_type
    Time_Key        @timestamp
    Replace_Dots    On
    Logstash_Prefix FluentBitHelmChart
                    
    HTTP_User       ***
    HTTP_Passwd     none

    tls             on
    tls.verify      on
    tls.debug       1
    tls.ca_file     /secure/es-tls-ca.crt 

=================================
This is working perfectly, Now I need to output to a new humio repo based on filter Category:Audit
--------------------------------------------
The JSON is below 
`{
  "Level": "Information",
  "MessageTemplate": "Updated {type} {@model}",
  "Properties": {
    "Actor": {
      "Id": "***",
      "Ip": "***",
      "Name": "***",
      "Type": "User",
      "_typeTag": "ActorModel"
    },
    "Category": "Audit",
    "CorrelationId": "***",
    "Logger": "WasteWaterMutation",
    "MachineName": "grundfosgicwwncapi-5455585cbd-hdxvl",
    "ServiceName": "Grundfos.GiC.WWNC.API",
    "ServiceVersion": "0.1.1.996",
    "model": {
      "DeviceId": "",
      "Devices": [
        {
          "Capabilities": [
            
          ],
          "DeviceID": "gfpitq010000004",
          "Gua": "***",
          "MacAddress": "",
          "MetaJSON": "",
          "Model": "Pit",
          "Name": "",
          "Order": 0,
          "Status": "Active",
          "Type": "Pit",
          "_typeTag": "Device"
        },
        {
          "Capabilities": [
            
          ],
          "DeviceID": "gfcdq010000030",
          "Gua": "***",
          "MacAddress": "***",
          "MetaJSON": "",
          "Model": "Beckhoff PLC",
          "Name": "Beckhoff PLC",
          "Order": 0,
          "Status": "Active",
          "Type": "Communication",
          "_typeTag": "Device"
        },
        {
          "Capabilities": [
            "CapFlowLevel",
            "CapPressure"
          ],
          "DeviceID": "gfclq010000019",
          "Gua": "***",
          "MacAddress": "32",
          "MetaJSON": "",
          "Model": "CU362",
          "Name": "",
          "Order": 0,
          "Status": "Active",
          "Type": "Controller",
          "_typeTag": "Device"
        },
        {
          "Capabilities": [
            "CapRainLevel"
          ],
          "DeviceID": "gfeqq010000037",
          "Gua": "***",
          "MacAddress": "",
          "MetaJSON": "",
          "Model": "NA",
          "Name": "",
          "Order": 0,
          "Status": "Active",
          "Type": "Io",
          "_typeTag": "Device"
        },
        {
          "Capabilities": [
            "CapPump"
          ],
          "DeviceID": "gfeqq010000038",
          "Gua": "***",
          "MacAddress": "32",
          "MetaJSON": "{"Specs":"AGM 190/2 GLRED ED (15kW motor)","StopLevel":0.4,"StartLevel":0.85}",
          "Model": "CU362",
          "Name": "Pump 1",
          "Order": 1,
          "Status": "Active",
          "Type": "Controller",
          "_typeTag": "Device"
        },
        {
          "Capabilities": [
            "CapPump"
          ],
          "DeviceID": "gfeqq010000039",
          "Gua": "***",
          "MacAddress": "32",
          "MetaJSON": "{"Specs":"AGM 190/2 GLRED ED (15kW motor)","StopLevel":0.4,"StartLevel":0.85}",
          "Model": "CU362",
          "Name": "Pump 2",
          "Order": 2,
          "Status": "Active",
          "Type": "Controller",
          "_typeTag": "Device"
        }
      ],
      "Display": true,
      "GeoPoint": {
        "Latitude": 55.969036,
        "Longitude": 9.881484,
        "_typeTag": "GeoPoint"
      },
      "InstallationStatus": "Active",
      "InstallationType": "Pit",
      "MetaJSON": "{"IndexNo":0,"SurfaceArea":2.5,"SurfaceDescription":"Cilindric with a diameter of 180 cm","InletHeight":4.3,"HighWaterAlarm":2.0,"OverflowLevel":4.0,"Mode":"Mode 2A","InstallationType":"pit","RainSensorPit":"DSS WWNC Pit 1 - FileUpload","RainRunOffDelay":2.0}",
      "Name": "DSS WWNC Pit 1 - FileUpload",
      "PitDeviceID": "",
      "SectionID": "***",
      "Settings": {
        "AlgorithmModes": [
          "AlPower",
          "AlPressure",
          "AlSpeed"
        ],
        "InletHeight": 4.3,
        "MaxWaterLevel": 0.85,
        "MinWaterLevel": 0,
        "PitArea": 2.5,
        "RuninDelay": 2,
        "_typeTag": "Settings"
      },
      "SharedDevices": [
        
      ],
      "UUID": "***",
      "UpstreamPitUUID": "",
      "_typeTag": "Pit"
    },
    "type": "pit"
  },
  "Timestamp": "2020-05-13T08:24:45.5310849+00:00"
}`

=====================================

now my new config is 

`[INPUT]
    Name             tail
    Path             /var/log/containers/*.log
    Parser           docker
    Tag              audit.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[INPUT]
    Name             tail
    Path             /var/log/containers/*.log
    Parser           docker
    Tag              kube.*
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_Tag_Prefix     kube.var.log.containers.
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log           On
    Merge_Log_Key       log_processed
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On

[FILTER]
    Name   grep
    Match  audit.*
    Regex  Properties.Category Audit    

[OUTPUT]
    Name            es
    Match           kube.*
    Host            cloud.humio.com
    Port            9200
    Logstash_Format On
    Retry_Limit     False
    Type            flb_type
    Time_Key        @timestamp
    Replace_Dots    On
    Logstash_Prefix FluentBitHelmChart
                    
    HTTP_User       ***
    HTTP_Passwd     none

    tls             on
    tls.verify      on
    tls.debug       1
    tls.ca_file     /secure/es-tls-ca.crt

[OUTPUT]
    Name            es
    Match           audit.*
    Host            cloud.humio.com
    Port            9200
    Logstash_Format On
    Retry_Limit     False
    Type            flb_type
    Time_Key        @timestamp
    Replace_Dots    On
    Logstash_Prefix FluentBitHelmChart
                    
    HTTP_User       ***
    HTTP_Passwd     none

    tls             on
    tls.verify      on
    tls.debug       1
    tls.ca_file     /secure/es-tls-ca.crt    
                

`

This is not working
Is there a way to debug or I am doing something wrong?

**Comment by edsiper** [comment]
I don't understand the requirement. 

Do you want to remove specific records from the pipeline ?

**Comment by SidGrundfos** [comment]
yes, but I solved the issue. I added 2 different inputs with different Match and then filtered them separately to 2 different output repos.
I am closing this.
