### ISSUE TITLE
Add option to validate configuration

### ISSUE THREAD

**Issue by kangaechu** [fluent/fluent-bit#2178]
**Is your feature request related to a problem? Please describe.**

same issue as #1787.

Fluent Bit does not have the option to test whether its configuration is valid.

**Describe the solution you'd like**

Some projects have added the Fluent Bit configuration file into the Git repository.
When I change Fluent Bit's configuration file or command line options, I want to check if the configuration file is valid via CI such as GitHub Actions or CircleCI.
However, there is no option to check the settings, so I have to run the command manually to make sure it runs correctly.

In order to automatically check its configuration validness, we need an option to validate configuration

Many applications allow you to check if their configuration contains errors, e.g.:

```
nginx -c /etc/nginx/nginx.conf -t
apachectl configtest
```

**Describe alternatives you've considered**

Add option to validate configuration.

**Comment by edsiper** [comment]
thanks for opening this ticket, definitely will be implemented.

**Comment by 0x1a0b** [comment]
Cool feature, do we know when the PR will be merged?
