### ISSUE TITLE
Multiline not working

### ISSUE THREAD

**Issue by sdonepudy** [fluent/fluent-bit#2182]
I have turned on the the multiline feature and I still do not see it working here are the sample configs. I am using fluent-bit on EKS with AWS elasticsearch. I have tried the parser on https://rubular.com/ and see it successfully parsing the new lines. What else am I missing here. Appreciate any help have been trying multiple combinations with no luck.

---- sample log entries ----
2020-05-16 22:21:32.786 DEBUG [main] (LogApplication) - This is a sample DEBUG message
2020-05-16 22:21:33.788 DEBUG [main] (LogApplication) - This is a sample DEBUG message
2020-05-16 22:21:34.792 INFO  [main] (LogApplication) - This is a sample INFO message
2020-05-16 22:21:35.801 ERROR [main] (LogApplication) - This is a sample ERROR message
java.lang.Exception: Some error
	at LogApplication.main(LogApplication.java:31)
2020-05-16 22:21:36.802 ERROR [main] (LogApplication) - This is a sample ERROR message
java.lang.Exception: Some error
	at LogApplication.main(LogApplication.java:31)

---- config file -------
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Multiline         On
        Parser_Firstline  java_multiline

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            vpc-xxxxx-.us-east-1.es.amazonaws.com
        Port            443
        Logstash_Prefix myindex
        Logstash_Format On
        #Replace_Dots    On
        #Retry_Limit     False
        tls             On

  parsers.conf: |
    [PARSER]
        Name        java_multiline
        Format      regex
        Regex       /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}) (?<level>[^\s]+)(\s.*)\[(?<thread>.*)\] \((?<logger>[^\s]+)\) - (?<message>.*)$/

----- Out put in the Kibana for an error message----
{"log":"java.lang.Exception: Some error\n","stream":"stdout","time":"2020-05-18T19:37:18.869495727Z"}
{"log":"\u0009at LogApplication.main(LogApplication.java:31)\n","stream":"stdout","time":"2020-05-18T19:37:18.869503857Z"}
{"log":"2020-05-18 19:37:18.869 ERROR [main] (LogApplication) - This is a sample ERROR message\n","stream":"stdout","time":"2020-05-18T19:37:18.869440116Z"}

**Comment by AshutoshNirkhe** [comment]
Same here, fluent-bit just throws 'invalid parser' as soon as multi-line is turn on, even though regex is correct.

**Comment by pauloduartepinho** [comment]
I'am having the same issue.

**Comment by pauloduartepinho** [comment]
Did some digging, seems to me that the problem should be here 
`
struct flb_parser *flb_parser_get(const char *name, struct flb_config *config)
{
    struct mk_list *head;
    struct flb_parser *parser;
    mk_list_foreach(head, &config->parsers) {
        parser = mk_list_entry(head, struct flb_parser, _head);
        if (strcmp(parser->name, name) == 0) {
            return parser;
        }
    }
    return NULL;
}`

there must be some problem with parser values resolution or name comparison...

**Comment by edsiper** [comment]
# Multiline Update

As part of Fluent Bit v1.8, we have released a new Multiline core functionality. This new big feature allows you to configure new `[MULTILINE_PARSER]`s that support multi formats/auto-detection, new multiline mode on Tail plugin, and also on v1.8.2 (to be released on July 20th, 2021) a new Multiline Filter. 

For now, you can take at the following documentation resources:

- [Multiline Parsers / Concepts and Configuration](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing)
- [Tail + New Multiline Core Feature](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support)
- [New Multiline Filter](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace)

Documentation pages now point to complete config examples that are available on our repository.

Thanks everyone for supporting this!

**Comment by lyoshakarpenko** [comment]
@edsiper Please show how to write rule for different variants of the second and subsequent lines in a multiline parser. I have different types of multiline log not only a stack trace. I need to know the syntax, how to write a lot of rules.
