### ISSUE TITLE
[windows] KeepAlive is crashing fluentbit

### ISSUE THREAD

**Issue by theggelund** [fluent/fluent-bit#2189]
## Bug Report

**Describe the bug**
The new keep alive property in 1.4.x crashes the process when the receiver is not able to receive data because of buffer full.

**To Reproduce**
Run a receiver fluentbit. Buffer_Max_Size must be set to a low enough number. 
`.\fluent-bit.exe -i forward -p Buffer_Max_Size=1M -p Buffer_Chunk_Size=1M -o file -p Path=output.log`

Run a sender fluentbit on the same machine with the following configuration
```
[SERVICE]
    Log_Level debug
    Parsers_File parsers.conf

[INPUT]
    Name    tail
    Tag     format.afile
    Path    test.log 
    Parser  test
    DB      input.DB
    Buffer_Chunk_Size   512k
    Buffer_Max_Size     1M    
    Mem_Buf_Limit       50M

[OUTPUT]
    Name    forward
    Match   *
    KeepAlive On
```
Parsers.conf
```
[PARSER]
    Name test
    Format regex
    Regex ^(?<log_time>\d{8} \d{2}:\d{2}:\d{2},\d{3})(?<msg>.*)$
    Time_Format %Y%m%d %H:%M:%S.%L
    Time_Keep   Off
    Time_Key log_time
```

test.log is a 95MB file with the same line duplicated
"20200520 06:52:04,285 abcdefg"

[Fluent Bit v1.4.4 log](https://github.com/fluent/fluent-bit/files/4655331/Fluent.Bit.v1.4.4.txt)

**Expected behavior**
Should not crash. Disabling KeepAlive will prevent the error from occuring. Also downloaded 1.5 and compiled it. I am able to reproduce the same error when using that version.

**Screenshots**
![image](https://user-images.githubusercontent.com/648714/82419804-24f85500-9a7f-11ea-9b21-36f246cfb9b6.png)

**Your Environment**
Windows 10
![image](https://user-images.githubusercontent.com/648714/82419723-101bc180-9a7f-11ea-9fe5-1c951fc6af3a.png)

**Comment by edsiper** [comment]
cc: @fujimotos

**Comment by fujimotos** [comment]
> The new keep alive property in 1.4.x crashes the process when the receiver is not able to receive data because of buffer full.

@theggelund I'm investigating this issue along with #2189. I found
a bug in the keepalive logic, so posted a fix to #2192 

I think it might resolve the issue you have described; I appreciate
if you can confirm that on your environment.

**Comment by theggelund** [comment]
I testet it and the change fixes the issue I had with keepalive

**Comment by edsiper** [comment]
thanks for the update and thanks @fujimotos for do the fix.
