### ISSUE TITLE
Extracting Custom Fields from Logs

### ISSUE THREAD

**Issue by marvinestreet** [fluent/fluent-bit#2190]
My apologies, but this is more a request for guidance than a feature request.

I am in the process of setting up fluent bit to transport logs from AWS EKS kube-system containers to AWS elasticsearch. Everything seems to be working smoothly (notwithstanding a few hiccups that needed working out). I just need assistance figuring out a simple way to extra the Log Level from log entries.

This is the sample log entry:
`{"log":"I0511 15:54:55.115466       1 controller.go:121] kubebuilder/controller \"level\"=0 \"msg\"=\"Starting EventSource\"  \"controller\"=\"alb-ingress-controller\" \"source\"={\"Type\":{\"metadata\":{\"creationTimestamp\":null},\"spec\":{},\"status\":{\"loadBalancer\":{}}}}\n","stream":"stderr","time":"2020-05-11T15:54:55.118896763Z"}`

The `I` in `I0511` means this log level is "Info". Is there a simple way to modify the fluentbit config to extra this value and give it's own field in elasticsearch? Bonus points if there's a way to transform `I` to `Info`, `E` to `error`, etc, as well.

Thanks for any and all guidance on this!

**Comment by edsiper** [comment]
I think you will need to build a regex for that purpose, meaning a custom parser configuration.

**Comment by marvinestreet** [comment]
That's what I figured. No bonus points, I take it?

**Comment by edsiper** [comment]
try to build and test  your rule here: https://rubular.com/

**Comment by marvinestreet** [comment]
Thanks! One more quick question, there's no way to do any sort of text substitution, right?
Extract the `I` and maybe do a text replacement for `Info` before sending to Elasticsearch, correct?

**Comment by marvinestreet** [comment]
I've gone the parser route to do this. Can someone let me know what the format is for specifying multiple parsers on Input configs? I'm trying to apply both the docker parser as well as my custom one to each. 

Thanks!

**Comment by marvinestreet** [comment]
@edsiper any help on specifying multiple parsers for an input?

**Comment by bluebike** [comment]
Without making totally new parser I would first split message to few parts parts first in with rubular parser  (date, ..., key-values-parts , ... )
Then I would write customer filter with in Lua to split or key-value pairs.

**Comment by marvinestreet** [comment]
@bluebike I'm hoping not to have to duplicate work already done by the docker parser. If you look at the [parser filter doc](https://docs.fluentbit.io/manual/pipeline/filters/parser) it specifies `Multiple Parser entries are allowed (one per line).`

However, doing something like this:
`[FILTER]
    Name parser
    Match dummy.*
    Key_Name data
    Parser dummy_test
    Parser dummy_test_2`
Doesn't work.
