### ISSUE TITLE
make install error in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Dhiraj240** [fluent/fluent-bit#2194]
I followed the documentation for building it.
cmake worked fine.

But,
The error was generated after doing make install.
```
./library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): In function `process_config':
rewrite_tag.c:(.text+0x9e4): undefined reference to `flb_ra_create'
rewrite_tag.c:(.text+0xad1): undefined reference to `flb_ra_destroy'
rewrite_tag.c:(.text+0xb13): undefined reference to `flb_ra_create'
rewrite_tag.c:(.text+0xb73): undefined reference to `flb_ra_destroy'
../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): In function `process_record':
rewrite_tag.c:(.text+0xfd6): undefined reference to `flb_ra_regex_match'
rewrite_tag.c:(.text+0x1044): undefined reference to `flb_ra_translate'
../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): In function `destroy_rules':
rewrite_tag.c:(.text+0x13a2): undefined reference to `flb_ra_destroy'
rewrite_tag.c:(.text+0x13b2): undefined reference to `flb_ra_destroy'
collect2: error: ld returned 1 exit status
src/CMakeFiles/fluent-bit-bin.dir/build.make:265: recipe for target 'bin/fluent-bit' failed
make[2]: *** [bin/fluent-bit] Error 1
CMakeFiles/Makefile2:4372: recipe for target 'src/CMakeFiles/fluent-bit-bin.dir/all' failed
make[1]: *** [src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
Makefile:171: recipe for target 'all' failed
make: *** [all] Error 2

```
The fluent-bit version I compiled was of this repository itself using git clone, I guess it is 1.5

My OS was Ubuntu 18.04 LTS

**Comment by edsiper** [comment]
When creating issues, please provide enough information so the maintainers can reproduce the problem like:

- what's your OS ?
- which command did you run with cmake ?
- build log ?
- Fluent BIt version
- etc...

**Comment by fujimotos** [comment]
@Dhiraj240 Run the following command from the command line
and see if it resolve your issue.

```
$ sudo apt install bison flex
```

**Comment by Dhiraj240** [comment]
The error was because of dependencies which were not installed.
Those were flex, bison, postgres, libsystem-dev.
People who fall in such trouble should read the log files of Cmake and I lately recognized it.
Sorry, hence closing the issue as it is no more.

**Comment by Bhavanaashok33** [comment]
Hi,
While installing Fluent-bit VERSION 2.8 on Ubuntu 20.04, even after installing all the dependencies(flex, bison, postgres, libsystem-dev,etc) , I am still see this issue. 

Command used while running cmake : Cmake ../
 
Logs:

[ 80%] Built target flb-plugin-in_cpu
[ 80%] Linking C executable ../bin/fluent-bit
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function `rule_create':
/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:93: undefined reference to `flb_ra_create'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:107: undefined reference to `flb_ra_create'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function `rule_destroy':
/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:125: undefined reference to `flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function `rule_apply':
/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:278: undefined reference to `flb_ra_get_value_object'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:281: undefined reference to `flb_ra_key_value_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:305: undefined reference to `flb_ra_key_value_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:327: undefined reference to `flb_ra_key_value_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:350: undefined reference to `flb_ra_key_value_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:375: undefined reference to `flb_ra_key_value_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o):/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:382: more undefined references to `flb_ra_key_value_destroy' follow
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function `process_config':
/home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:141: undefined reference to `flb_ra_create'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:155: undefined reference to `flb_ra_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:162: undefined reference to `flb_ra_create'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:166: undefined reference to `flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function `process_record':
/home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:304: undefined reference to `flb_ra_regex_match'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:319: undefined reference to `flb_ra_translate'
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function `destroy_rules':
/home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:423: undefined reference to `flb_ra_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:424: undefined reference to `flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function `delete_rules':
/home/noiro/fluent-bit-1.4.5/plugins/filter_grep/grep.c:48: undefined reference to `flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function `set_rules':
/home/noiro/fluent-bit-1.4.5/plugins/filter_grep/grep.c:122: undefined reference to `flb_ra_create'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function `grep_filter_data':
/home/noiro/fluent-bit-1.4.5/plugins/filter_grep/grep.c:158: undefined reference to `flb_ra_regex_match'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:246: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:5142: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2

**Comment by edsiper** [comment]
please open a new issue since this one is closed. Make sure to provide your cmake build line and output log
