### ISSUE TITLE
Fluent-bit snap - path and run issues

### ISSUE THREAD

**Issue by tlefevre** [fluent/fluent-bit#2203]
I  have installed fluent-bit via snap, to try and troubleshoot some issues. 

snap install fluent-bit
fluent-bit 1.4.1 from Eduardo Silva (edsiper) installed

Would be nice to have channels for minor versions, as is it doesn't seem like you can actually get a 1.3 version from a channel.

**1. There's no fluent-bit bin registered?** 
I would expect to be able to do a "fluent-bit" from command line and the bin would be on path. 

**2. Missing shared libraries** 
When I dig down and run fluent-bit directly from "/snap/fluent-bit/3/bin/fluent-bit" I get the following output: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory

**Comment by edsiper** [comment]
latest v1.4.6 should be ok (on stable channel)

**Comment by tlefevre** [comment]
Yeps, fixed :)
