### ISSUE TITLE
[windows] output plugin 'influxdb' cannot be loaded on td-agent-bit-1.4.4-win64

### ISSUE THREAD

**Issue by richerrerag** [fluent/fluent-bit#2205]
## Bug Report

**Describe the bug**
Not able to send data to influxdb output on Windows, getting Output plugin 'influxdb' error "Error: You must specify an output target. Aborting" even when configuration is correct.

**To Reproduce**
- Configured basic influxdb output setup:
```
[OUTPUT]
    Name                influxdb
    Match               *
```
- Example log message if applicable:
```
C:\td-agent-bit-1.4.4-win64\bin>fluent-bit.exe -c ..\conf\fluent-bit-test.conf
Fluent Bit v1.4.4
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Output plugin 'influxdb' cannot be loaded
Error: You must specify an output target. Aborting
```
- Steps to reproduce the problem:

**Expected behavior**

Expected to be able to send data to influxdb output

**Your Environment**

* Version used: td-agent-bit-1.4.4-win64
* Configuration: basic configuration
* Server type and version: VM
* Operating System and version: Windows Server 2012 R2 Datacenter
* Filters and plugins: influxdb

**Additional context**
This is stopping us from using InfluxDB as log and metric storage.

**Comment by edsiper** [comment]
cc: @fujimotos

**Comment by fujimotos** [comment]
@edsiper I took a quick look at this issue this morning and posted
a fix for the issue to #2207. 

While I investigating the issue I found a bug in the memory stack
in v1.5 series, so I posted #2206 to resolve that issue too.

Just ping me back if there is anything unclear about those fixes.

**Comment by fujimotos** [comment]
@edsiper I took a quick look at this issue this morning and posted
#2207 as a fix. 

While I investigating the issue I found a bug in the network stack
of v1.5 series, so I posted #2206 to resolve that issue too.

Just ping me back if there is anything unclear about those fixes.

**Comment by edsiper** [comment]
done: https://fluentbit.io/announcements/v1.4.6/
