### ISSUE TITLE
Merge_Log emiting invalid JSON

### ISSUE THREAD

**Issue by slobo** [fluent/fluent-bit#2209]
## Bug Report

**Describe the bug**

We had an issue with multiple-processes running in single k8s pod container were trampling each other STDERR log messages, resulting in invalid JSON. Meanwhile, `Merge_Log` gets tricked into constructing invalid JSON document.

**To Reproduce**
It's hard to dig out exactly which messages mess up Merge_Log, but I think this is one of them.
```
{"log":"{\"message\":\"Auto Rollback ProxyDB singleton\",\"packag\":\"Root.pm:94\",\"kind\":\"INFO\",\"sub\":\"ping_filings_db\",\"message\":\"PONG\",\"package\":\"IRProxy::Controller::Root\"}\n","stream":"stderr","time":"2020-05-28T18:00:12.21709544Z"}
```

ES Indexing files with something like this:
```
"reason": "Duplicate field 'message'\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2855ae72; line: 1, column: 537]"
```

**Expected behavior**

`Merge_Log` should notice that invalid JSON was provided in `log`, and just send the raw log entry to output.

**Comment by GeorgFleig** [comment]
Unfortunately JSON syntax does not forbid duplicate keys, so this JSON is not invalid. But many tools such as Elasicsearch won't accept it. See https://github.com/fluent/fluent-bit/issues/1835 for a similar discussion.

The expected behavior there is different though as de discussion started around duplicate fields after applying multiple filters but also affects your described `Merge_Log` scenario (discussed further down).

**Comment by slobo** [comment]
Thanks for the pointer Georg! Seems that the flexibility of fluent-bit (multiple inputs and multiple outputs) works against us here. 

For our use case, it would seem that having an option to skip Merging if result is not compatible with the ultimate log destination would make sense. Something like `Merge_Log_ElasticSearch_Compatible On` only with a better name :). Perhaps analogous to how `Keep_Log On` controls if original `log` lines are kept in the output, this new directive could control if processed fields are actually injected.
