### ISSUE TITLE
"type":"json_parse_exception","reason":"Duplicate field 'time'

### ISSUE THREAD

**Issue by tirelibirefe** [fluent/fluent-bit#2219]
## Bug Report

**Describe the bug**
I did everything as described here:
[https://hub.helm.sh/charts/fluent/fluent-bit](https://hub.helm.sh/charts/fluent/fluent-bit)

**To Reproduce**
helm install fluentbit fluent/fluent-bit
```
"type":"json_parse_exception","reason":"Duplicate field 'time'
```
Be careful: it crashes ElasticSearch.

- Steps to reproduce the problem:

Default kubespray kubernetes installation.
Default fluent-bit installation.
Default ES - Kibana installation.

**Expected behavior**
I expect it work.

**Additional context**
`"type":"json_parse_exception","reason":"Duplicate field 'time'`

**Comment by rajeeshckr** [comment]
I am also getting the same error, is there a workaround?

**Comment by 123BLiN** [comment]
What I don't understand is who is producing this field actually?
This is not docker parser theoretically as I have `TimeKeep Off` set up, so who is this?
I have only one suspect - it is kubernetes filter, but it does not have options to exclude some fields, and current helm chart is not able to add multiple filters one by one in config to remove this field in next filter manually - check and mate!

I'm so tired :(
