### ISSUE TITLE
update centos 7 rpm to 0.11.0

### ISSUE THREAD

**Issue by jpackagejasonc** [fluent/fluent-bit#222]
latest from http://packages.fluentbit.io/centos/7 is td-agent-bit-0.10.1-1.x86_64.rpm, can this please be updated to 0.11.0? Thanks!

**Comment by edsiper** [comment]
thanks for reaching out. Packages should be ready within this week, I will keep you posted.

**Comment by jpackagejasonc** [comment]
awesome, thanks!

**Comment by edsiper** [comment]
Fluent Bit v0.11.1 have been just released, CentOS 7 packages published too.

thanks,

**Comment by uttamanand** [comment]
Not able to find rpm for fluent bit. Can anyone of you please send the correct link to download the same?

**Comment by edsiper** [comment]
this should work:

apt.fluentbit.io/centos/7/td-agent-bit-0.12.9-1.x86_64.rpm

**Comment by uttamanand** [comment]
Thanks @edsiper . Is it the lastest one?

**Comment by uttamanand** [comment]
Hi Eduardo,

I have made a tar file of fluent bit and i have contents like below -:

/etc/td-agent-bit
/etc/td-agent-bit/parsers.conf
/etc/td-agent-bit/td-agent-bit.conf
/lib/libfluent-bit.so
/lib/systemd/system/td-agent-bit.service
/usr/local
/usr/local/bin
/usr/local/bin/td-agent-bit

Now I want to start the td-agent-bit ( Substitute for command -: service td-agent-bit start).
I tried to start it manually by executing usr/local/bin/td-agent-bit , but getting below error -:

**Fluent-Bit v0.12.9
Copyright (C) Treasure Data

Error: No Input(s) have been defined. Aborting**

Also tried giving input as  usr/local/bin/td-agent-bit start , but still the same error.

Do you know how to start fluent bit manually without using service command? I am doing like this as I don't have root access to the RHEL 7 server which I am using.

Thanks
Uttam Anand

**Comment by uttamanand** [comment]
I got the solution -:

/td-agent-fluent-bit/usr/local/bin/td-agent-bit -c /td-agent-fluent-bit/etc/td-agent-bit/td-agent-bit.conf
