### ISSUE TITLE
Systemd Input: Read_From_Tail true but not honored

### ISSUE THREAD

**Issue by tgraskemper** [fluent/fluent-bit#2229]
## Bug Report

**Describe the bug**
Using the Read_From_Tail setting with the systemd input plugin was not working as intended.  I was still getting historical logs ingested into our logging platform.

**To Reproduce**
- Steps to reproduce the problem:
Restart fluent-bit daemonset in kubernetes
``kubectl rollout restart daemonset fluent-bit``

**Expected behavior**
Historical log data from systemd should not be read by fluent-bit.

**Screenshots**
![image](https://user-images.githubusercontent.com/4392178/83790874-b524c580-a64d-11ea-8b5d-684904b23586.png)

**Your Environment**

* Version used: 1.4.5
* Configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: sumologic
  labels:
    app: fluent-bit
    release: fluent-bit
data:
  fluent-bit-service.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Parsers_File parsers_custom.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  fluent-bit-filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name         modify
        Match        host.*
        Copy         MESSAGE log
        Copy         _HOSTNAME host
        Remove_regex [_A-Z].*
    [FILTER]
        Name     grep
        Match    containers.*
        Exclude  log kube-probe

  fluent-bit-output.conf: |
    [OUTPUT]
        Name          forward
        Match         *
        Host          ${CHART}.${NAMESPACE}.svc.cluster.local.
        Port          24321
        Retry_Limit False

  fluent-bit.conf: |
    @INCLUDE fluent-bit-service.conf
    @INCLUDE fluent-bit-filter.conf
    [INPUT]
      Name             tail
      Path             /var/log/containers/*.log
      Exclude_Path     /var/log/containers/janitor*.log,/var/log/containers/*_kube-system_*.log,/var/log/containers/*_default_*.log,/var/log/containers/*_drone-builds_*.log
      Multiline        On
      Ignore_Older     30m
      Parser_Firstline multi_line
      Tag              containers.*
      Refresh_Interval 1
      Rotate_Wait      60
      Mem_Buf_Limit    5MB
      Skip_Long_Lines  On
      DB               /tail-db/tail-containers-state-sumo.db
      DB.Sync          Normal
    [INPUT]
      Name             tail
      Path             /var/log/containers/janitor*.log
      Multiline        On
      Ignore_Older     30m
      Parser_Firstline ruby_on_rails
      Tag              containers.*
      Refresh_Interval 1
      Rotate_Wait      60
      Mem_Buf_Limit    5MB
      Skip_Long_Lines  On
      DB               /tail-db/tail-janitor-state-sumo.db
      DB.Sync          Normal
    [INPUT]
      Name            systemd
      Tag             host.*
      Systemd_Filter  _SYSTEMD_UNIT=addon-config.service
      Systemd_Filter  _SYSTEMD_UNIT=addon-run.service
      Systemd_Filter  _SYSTEMD_UNIT=cfn-etcd-environment.service
      Systemd_Filter  _SYSTEMD_UNIT=cfn-signal.service
      Systemd_Filter  _SYSTEMD_UNIT=clean-ca-certificates.service
      Systemd_Filter  _SYSTEMD_UNIT=containerd.service
      Systemd_Filter  _SYSTEMD_UNIT=coreos-metadata.service
      Systemd_Filter  _SYSTEMD_UNIT=coreos-setup-environment.service
      Systemd_Filter  _SYSTEMD_UNIT=coreos-tmpfiles.service
      Systemd_Filter  _SYSTEMD_UNIT=dbus.service
      Systemd_Filter  _SYSTEMD_UNIT=docker.service
      Systemd_Filter  _SYSTEMD_UNIT=efs.service
      Systemd_Filter  _SYSTEMD_UNIT=etcd-member.service
      Systemd_Filter  _SYSTEMD_UNIT=etcd.service
      Systemd_Filter  _SYSTEMD_UNIT=etcd2.service
      Systemd_Filter  _SYSTEMD_UNIT=etcd3.service
      Systemd_Filter  _SYSTEMD_UNIT=etcdadm-check.service
      Systemd_Filter  _SYSTEMD_UNIT=etcdadm-reconfigure.service
      Systemd_Filter  _SYSTEMD_UNIT=etcdadm-save.service
      Systemd_Filter  _SYSTEMD_UNIT=etcdadm-update-status.service
      Systemd_Filter  _SYSTEMD_UNIT=flanneld.service
      Systemd_Filter  _SYSTEMD_UNIT=format-etcd2-volume.service
      Systemd_Filter  _SYSTEMD_UNIT=kube-node-taint-and-uncordon.service
      Systemd_Filter  _SYSTEMD_UNIT=kube-apiserver.service
      Systemd_Filter  _SYSTEMD_UNIT=kube-controller-manager.service
      Systemd_Filter  _SYSTEMD_UNIT=kube-scheduler.service
      Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
      Systemd_Filter  _SYSTEMD_UNIT=ldconfig.service
      Systemd_Filter  _SYSTEMD_UNIT=locksmithd.service
      Systemd_Filter  _SYSTEMD_UNIT=logrotate.service
      Systemd_Filter  _SYSTEMD_UNIT=lvm2-monitor.service
      Systemd_Filter  _SYSTEMD_UNIT=mdmon.service
      Systemd_Filter  _SYSTEMD_UNIT=nfs-idmapd.service
      Systemd_Filter  _SYSTEMD_UNIT=nfs-mountd.service
      Systemd_Filter  _SYSTEMD_UNIT=nfs-server.service
      Systemd_Filter  _SYSTEMD_UNIT=nfs-utils.service
      Systemd_Filter  _SYSTEMD_UNIT=node-problem-detector.service
      Systemd_Filter  _SYSTEMD_UNIT=ntp.service
      Systemd_Filter  _SYSTEMD_UNIT=oem-cloudinit.service
      Systemd_Filter  _SYSTEMD_UNIT=rkt-gc.service
      Systemd_Filter  _SYSTEMD_UNIT=rkt-metadata.service
      Systemd_Filter  _SYSTEMD_UNIT=rpc-idmapd.service
      Systemd_Filter  _SYSTEMD_UNIT=rpc-mountd.service
      Systemd_Filter  _SYSTEMD_UNIT=rpc-statd.service
      Systemd_Filter  _SYSTEMD_UNIT=rpcbind.service
      Systemd_Filter  _SYSTEMD_UNIT=set-aws-environment.service
      Systemd_Filter  _SYSTEMD_UNIT=system-cloudinit.service
      Systemd_Filter  _SYSTEMD_UNIT=systemd-timesyncd.service
      Systemd_Filter  _SYSTEMD_UNIT=update-ca-certificates.service
      Systemd_Filter  _SYSTEMD_UNIT=user-cloudinit.service
      Systemd_Filter  _SYSTEMD_UNIT=var-lib-etcd2.service
      Max_Entries     1000
      Read_From_Tail  true

    @INCLUDE fluent-bit-output.conf

  parsers.conf: |
    [PARSER]
        Name        multi_line
        Format      regex
        Regex       (?<log>^{"log":"\d{4}-\d{1,2}-\d{1,2}.\d{2}:\d{2}:\d{2}.*)
    [PARSER]
        Name        ruby_on_rails
        Format      regex
        Regex       (?<log>^{"log":"\d{2}:\d{2}:\d{2}.*Started.*)
```

* Environment name and version (e.g. Kubernetes? What version?):
Kubernetes v1.17.5
* Server type and version:
AWS t3 and m5 series
* Operating System and version:
Ubuntu Xenial 16.04
Linux 4.15.0-1063-aws #67-Ubuntu SMP Mon Mar 2 07:24:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Filters and plugins:
systemd
tail

**Comment by nikinaydenov** [comment]
I have let say the same problem. I avoid the use of DB with systemd. It costs a lot in terms of IOPS put on disk system (around 10 IOPS persistent load). It is a lot in AWS when you use a small disk (bellow 32GB) that have only 100 IOPS. Fluent-bit is a perfect fit for such a small VM, but with exception of systemd input used with DB. So far for the history here.
Now to the solution. It looks like the systemd input tolerates the  Read_From_Tail, but only for let say fresh data - not rotated. I solve my problem by just:
 sudo journalctl --vacuum-time=30d
I am in situation that I am not interested in the older data. After the vacuum the problem disappear and systemd input with Read_From_Tail behaves as expected. 
Better solution will be to set retention on journald config, but this is a completely another problem. 
Hope that will help you. 
For me using the DB that keep the track to where the input stream was is a better solution but I can not tolerate the disk IOPS needed.

**Comment by edsiper** [comment]
@Akinari1087 I've verified that if you set the database option, it will override the read_from_tail behavior (which is expected), but I don't see that property in your configuration. Are you able to reproduce the problem locally outside of kubernetes ?

@nikinaydenov I've pushed some improvements to in_systemd today:

- when updating the cursor in the database, do it in one query instead of two
- optimize query parsing (prepend query)
- new db.sync option to set filesystem sync mode, options:
  - extra
  - full
  - normal
  - off

by default without the db.sync option, every database write performs filesystem sync which is expensive, with this new option you will be able to accommodate to your use case. You can read more about these modes here: https://www.sqlite.org/pragma.html#pragma_synchronous

**Comment by nikinaydenov** [comment]
@edsiper Thank you for kind response. I will take a look and do some test with DB again. 
I am able to reproduce the problem of @Akinari1087. In fact I work with pure docker (docker-compose). As I mention it is somehow related to the volume of logs. If they are less in numbers (after the vacuum) in most of the cases it start to work and I do not see old lines reaching the output, but there are still cases when I continue to see them. I talk for production and test system with 800+ VMs in total so: Yes, it is reproducible.

**Comment by Akinari1087** [comment]
@edsiper Adding the DB option to my configuration is my current workaround for this issue.  This is working as expected.

**Comment by edsiper** [comment]
@nikinaydenov if you do journalctl -f for your logs, do you get a different behavior than Fluent Bit ?, I am trying to guess if is Systemd API usage or not...

**Comment by zerkms** [comment]
Not stale.

**Comment by zerkms** [comment]
Not stale.
