### ISSUE TITLE
Using environment variable in conf

### ISSUE THREAD

**Issue by tomqwu** [fluent/fluent-bit#224]
Is this supported similarly to fluentd?

**Comment by edsiper** [comment]
@tomqwu 

For specific details for usage of environment variables please refer to the following documentation section:

http://fluentbit.io/documentation/0.11/configuration/variables.html

Note: I just added the info since it was not there before your request.

**Comment by tomqwu** [comment]
Thank you for your fast response!

**Comment by rolandjitsu** [comment]
@edsiper do env vars work with the `@INCLUDE` cmd? I'm getting some errors right now if I do try to use it:
```
@INCLUDE inputs.${DEV_MODE}.conf
```

**Comment by rolandjitsu** [comment]
My bad, was not setting the var properly 🤦‍♂

**Comment by frosiere** [comment]
> @edsiper do env vars work with the `@INCLUDE` cmd? I'm getting some errors right now if I do try to use it:
> 
> ```
> @INCLUDE inputs.${DEV_MODE}.conf
> ```
> 
> ```
> Jul 05 09:05:00 breadpi bash[9198]: [2019/07/05 09:05:00] [Warning] [config] I cannot open /home/pi/config/fluent-bit//inputs.${DEV_MODE}.conf file
> Jul 05 09:05:00 breadpi bash[9198]: Error: Configuration file contain errors. Aborting
> ```

https://github.com/fluent/fluent-bit/issues/2020
