### ISSUE TITLE
Make install errors on Ubuntu 20.04 with Fluent-bit VERSION 1.4.5

### ISSUE THREAD

**Issue by Bhavanaashok33** [fluent/fluent-bit#2242]
Hi,
[CMakeOutput.log](https://github.com/fluent/fluent-bit/files/4749056/CMakeOutput.log)

While installing Fluent-bit VERSION 1.4.5 on Ubuntu 20.04, I am seeing the below error. Cmake went through without any issues and I have installed all the dependencies pointed by that.

Cmake build line : In the build dir, I ran "cmake ../"

Followed the instructions using this link : https://fluentbit.io/documentation/0.8/installation/build_install.html 

Errror Logs:
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function rule_create': /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:93: undefined reference to flb_ra_create'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:107: undefined reference to flb_ra_create' /usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function rule_destroy':
/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:125: undefined reference to flb_ra_destroy' /usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function rule_apply':
/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:278: undefined reference to flb_ra_get_value_object' /usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:281: undefined reference to flb_ra_key_value_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:305: undefined reference to flb_ra_key_value_destroy' /usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:327: undefined reference to flb_ra_key_value_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:350: undefined reference to flb_ra_key_value_destroy' /usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:375: undefined reference to flb_ra_key_value_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o):/home/noiro/fluent-bit-1.4.5/plugins/filter_expect/expect.c:382: more undefined references to flb_ra_key_value_destroy' follow /usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function process_config':
/home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:141: undefined reference to flb_ra_create' /usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:155: undefined reference to flb_ra_destroy'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:162: undefined reference to flb_ra_create' /usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:166: undefined reference to flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function process_record': /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:304: undefined reference to flb_ra_regex_match'
/usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:319: undefined reference to flb_ra_translate' /usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function destroy_rules':
/home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:423: undefined reference to flb_ra_destroy' /usr/bin/ld: /home/noiro/fluent-bit-1.4.5/plugins/filter_rewrite_tag/rewrite_tag.c:424: undefined reference to flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function delete_rules': /home/noiro/fluent-bit-1.4.5/plugins/filter_grep/grep.c:48: undefined reference to flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function set_rules': /home/noiro/fluent-bit-1.4.5/plugins/filter_grep/grep.c:122: undefined reference to flb_ra_create'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function grep_filter_data': /home/noiro/fluent-bit-1.4.5/plugins/filter_grep/grep.c:158: undefined reference to flb_ra_regex_match'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:246: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:5142: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2

**Comment by edsiper** [comment]
Please use the updated documentation (we are in v1.4)

- https://docs.fluentbit.io/manual/installation/requirements
- https://docs.fluentbit.io/manual/installation/sources/build-and-install
