### ISSUE TITLE
[Question] Sending logs generated during kafka broker downtime after brokers are back again

### ISSUE THREAD

**Issue by birdy81** [fluent/fluent-bit#2244]
## Bug Report

**Describe the bug**
We use fluentbit input tail plugin and output kafka plugin in our kubernetes cluster (Version 1.3.9). See configuration attached. 

Sometimes the kafka brokers are down and not accessible. In case this is happening and after a while the broker are available again, fluentbit does not send the logs that are generated during the downtime. Only the new logs are send. But the logs are still available on the hosts.

**To Reproduce**
- Start fluentbit agent in our cluster and send logs to Kafka broker
- Stop Broker for a while
- Start Broker
- Sometimes we have to restart fluent-bit because after broker downtime the logs are not send anymore 
- The logs during the downtime are not send again. Only the new logs. 

**Expected behavior**
I expect that the logs that where not able to be send during the broker downtime, are then send afterwards. Or is this the expected behavior? Is there a way to configure fluent-bit that these logs are also send?

**Your Environment**

* Version used: 1.3.9
* Configuration:

  fluent-bit.conf: |
    [SERVICE]
        Flush           1
        Log_Level       info
        Daemon          off
        Parsers_File    parsers.conf
        HTTP_Server     On
        HTTP_Listen     0.0.0.0
        HTTP_PORT       2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-kafka.conf

  input-kubernetes.conf: |
    [INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        Parser              cri
        DB                  /var/log/flb_kube.db
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Docker_Mode         On

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  output-kafka.conf: |
    [OUTPUT]
        Name                kafka
        Match               *
        Format              json
        Brokers             <broker>
        Topics              <topics>
        Timestamp_Key       @timestamp
        Timestamp_Format    iso8601

  parsers.conf: |
    [PARSER]
        Name          cri
        Format        regex
        Regex         ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key      time
        Time_Format   %Y-%m-%dT%H:%M:%S.%L%z

* Kubernetes Version 1.18
* ContainerD log format cri
* Filters and plugins:
  * tail input
  * kafka output
  * kubernetes filter

**Comment by shyimo** [comment]
seems to be the same as #2161
