### ISSUE TITLE
Fluent-bit crashes with OOM when using in-memory buffer

### ISSUE THREAD

**Issue by ts3ng** [fluent/fluent-bit#2247]
## Bug Report

**Describe the bug**
We are seeing fluent-bit run crash with OOM when using in-memory buffers when the upstream service is down (in our case splunk) responds with a non 200 HTTP code. 

We tried increasing the memory but of our fluent-bit services but that doesn't seem to alleviate the issue.  In our graphs we had 500mb memory allocated and we see the memory shoot up immediately (screenshot below).  We were still able to reproduce with a 1Gi limit as well.

Switching to filesystem storage helps but we are running into issues with not able to limit the scratch buffer_chunk_size files in the storage.path.  We see these directories continually grow without any bound, there doesn't seem like there is a setting limit the storage.path buffer files.

**To Reproduce**
If you have k8s cluster you can load the following k8s manifest configuration and watch it crash with OOM issues.  You will need to alter the output plugin to point to a service that  returns a response that causes the buffer to fill.  an invalid URL does not seem to cause the issue.
[fluent-bit-oom.zip](https://github.com/fluent/fluent-bit/files/4762014/fluent-bit-oom.zip)

otherwise extract the configmap and pointthe output plugin to a service that will return a invalid response code, we were able to reproduce it consistently when we got 400 and 500 responses.

we're logging at a rate of 2.5mb a sec in our test service but i think the idea is to overflow the in memory buffer.

**Expected behavior**
Fluent-bit would drop logs from buffer and continue to process logs without OOM.

**Screenshots**
memory graphs:
![fluent-bit-oom2](https://user-images.githubusercontent.com/18268735/84330115-61c5e200-ab3b-11ea-8471-827d5a4e6a23.png)
![fluent-oom1](https://user-images.githubusercontent.com/18268735/84330119-62f70f00-ab3b-11ea-9a36-06d2ada2e6c1.png)

**Your Environment**

* Version used: 1.4.6
* Configuration: see included file.
* Environment name and version: Kubernetes version: 1.16.9
* Server type and version:  Coreos
* Operating System and version: n/a
* Filters and plugins: tail, lua, splunk

**Comment by edsiper** [comment]
You are facing backpressure and your configuration don't have control over memory usage, please take a look at this section:

https://docs.fluentbit.io/manual/administration/backpressure

additional notes:

- upgrade to fluent bit v1.4.6
- your parsers.conf has old definitions, please read the [upgrade notes](https://docs.fluentbit.io/manual/installation/upgrade-notes#fluent-bit-v-1-2), your configuration has not been migrated properly (I refer to the decoders)

**Comment by ts3ng** [comment]
@edsiper sorry about that i included the wrong manifest here ist he one that crashes...
we do set mem_buff_limit

```
      # Read logs from the Docker or CRI-O logging driver
      # https://git.corp.adobe.com/adobe-platform/k8s-docker-logging-driver
      # https://git.corp.adobe.com/adobe-platform/k8s-cri-logging-driver
      # https://docs.fluentbit.io/manual/input/tail
      Name tail
      Parser ${LOG_PARSER}
      # If you are using Docker and you need to parse log lines larger than
      # 16k in size, uncomment the Docker_Mode line.
      # Leave this disabled if using CRI-O
      #Docker_Mode On
      Path /logging-volume/*.log
      DB /var/fluent-bit/logs.db
      Tag in_tail
      Path_Key file_path
      Mem_Buf_Limit 350M
```

**Comment by dharmab** [comment]
@edsiper we intentionally use a custom parser- the decoders are for parsing JSON-within-JSON, not for decoding the Docker JSON.

**Comment by ts3ng** [comment]
After taking the 1.4.6 image we are not seeing the OOM issues anymore, closing issue.  Thanks @edsiper !

**Comment by ts3ng** [comment]
Actually we still see a few OOM issues  with 1.4.6 that are cropping up not as frequently but there still seems to be a leak, reopening issue.
```
  fluent-bit:
    Container ID:   docker://30e52eae4eb891650c8df1650d41808afd6f4f147fb59a4fdf3ba71bec3b1f4e
    Image:          461989703686.dkr.ecr.us-east-1.amazonaws.com/ethos/66131456-5bcb-11e9-8647-d663bd873d93/fluent/fluent-bit:1.4.6-debug
    Image ID:       docker-pullable://461989703686.dkr.ecr.us-east-1.amazonaws.com/ethos/66131456-5bcb-11e9-8647-d663bd873d93/fluent/fluent-bit@sha256:0b5732ec83411b0632d5cbb5dcadf16c737c1e2d5713e83c9e2dd74072341691
    Port:           2020/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 17 Jun 2020 09:41:25 -0700
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 17 Jun 2020 09:34:36 -0700
      Finished:     Wed, 17 Jun 2020 09:36:21 -0700
    Ready:          True
    Restart Count:  7
    Limits:
      memory:  500Mi
    Requests:
      cpu:     100m
      memory:  20Mi
    Liveness:  http-get http://:2020/ delay=5s timeout=10s period=30s #success=1 #failure=3
```

**Comment by ts3ng** [comment]
Here are the memory graphs when fluent-bit OOM.
![Screen Shot 2020-06-17 at 11 16 52 AM](https://user-images.githubusercontent.com/18268735/84934670-83b7eb00-b08c-11ea-9526-8e37024c659e.png)

**Comment by ts3ng** [comment]
attaching reproduction manifest.  apply to a namespace.  

[fluent-bit-1.4.6.zip](https://github.com/fluent/fluent-bit/files/4794778/fluent-bit-1.4.6.zip)

**Comment by ts3ng** [comment]
There seems to be something around setting the MEM_BUF_LIMIT that helps stabilize fluent-bit. we set a container limit of 512Mb (see our sidecar manifest) for our fluent-bit service but allocating 350Mb as the Mem_Buf_Limit causes OOM. Reducing it to 250Mb seems to avoid the OOM issues we're seeing.  Here are our test results:
250Mb w/ 512Mb mem limit.
```
fluent-buffer-250-7554b876b9-4n4tm            2/2     Running            0          158m
fluent-buffer-250-7554b876b9-ckrmv            2/2     Running            0          158m
fluent-buffer-250-7554b876b9-p26w6            2/2     Running            0          158m
fluent-buffer-250-7554b876b9-vlr78            2/2     Running            0          158m
fluent-buffer-250-7554b876b9-znb6z            2/2     Running            0          158m
```

350Mb w/ 512Mb mem limit.
```
fluent-buffer-350-5dbb757546-4rr8z            0/2     CrashLoopBackOff   35         82m
fluent-buffer-350-5dbb757546-5bqtg            2/2     Running            0          92m
fluent-buffer-350-5dbb757546-f2mb2            0/2     CrashLoopBackOff   36         85m
fluent-buffer-350-5dbb757546-mdtxr            2/2     Running            0          89m
fluent-buffer-350-5dbb757546-qppd6            2/2     Running            0          90m
```
This seems to happen with 1.4.2 and 1.4.6.  @edsiper is there any information about how much overhead memory we should allocate accordingly to increasing the in-memory buffer?
