### ISSUE TITLE
[Feature] Add build info metric

### ISSUE THREAD

**Issue by tinproject** [fluent/fluent-bit#2262]
**Is your feature request related to a problem? Please describe.**

I want to know what versions of fluentbit are deployed using monitoring tools

**Describe the solution you'd like**

The fluentbit version is already exposed by the API, but not on prometheus metrics.

Add a `fluentbit_build_info` metric, e.g.: `fluentbit_build_info{version="1.4.6",edition="Community"} 1`

**Describe alternatives you've considered**

**Additional context**

https://www.robustperception.io/exposing-the-software-version-to-prometheus

**Comment by edsiper** [comment]
implemented.
