### ISSUE TITLE
[Feature] Allow metric/config correlation

### ISSUE THREAD

**Issue by tinproject** [fluent/fluent-bit#2263]
**Is your feature request related to a problem? Please describe.**

I couldn't find a way to correlate exposed metrics with the config items.

For example, I have this metrics:
```
# HELP fluentbit_input_bytes_total Number of input bytes.
# TYPE fluentbit_input_bytes_total counter
fluentbit_input_bytes_total{name="tail.0"} 8957 1592218293104
fluentbit_input_bytes_total{name="tail.1"} 0 1592218293104
fluentbit_input_bytes_total{name="tail.2"} 0 1592218293104
fluentbit_input_bytes_total{name="tail.4"} 30101 1592218293104
fluentbit_input_bytes_total{name="tail.5"} 0 1592218293104
```
I do not know which metric corresponds to each tail input.
(Could be dependent on the config file order, but this is not consistent with dynamic multiple config files)

**Describe the solution you'd like**

Add a way to change the number by some defined keyword or something like that.

**Describe alternatives you've considered**

**Additional context**

**Comment by hectorhuertas** [comment]
You can use aliases to name your configs https://docs.fluentbit.io/manual/administration/monitoring#configuring-aliases

**Comment by tinproject** [comment]
Thanks @hectorhuertas! 
Do not know the Alias config, I've had missed from release notes at some point.
