### ISSUE TITLE
Setting GELF output (short_message key) via command line

### ISSUE THREAD

**Issue by TobiMichael96** [fluent/fluent-bit#2267]
Example command line: `bin/fluent-bit -H -i cpu -o gelf://X.X.X.X:12202 -p mode=udp Gelf_Short_Message_Key=cpu_p -m '*'`

Gives me this log ouputs:
`fluent-bit_1  | [2020/06/16 07:00:21] [error] [flb_msgpack_to_gelf] missing short_message key
fluent-bit_1  | [2020/06/16 07:00:21] [error] [output:gelf:gelf.0] error encoding to GELF`

The error is pretty easy to understand, but how to set the short_message key correctly via command line?

**Comment by timurb** [comment]
@TobiMichael96 How did you end up with setting that eventually?

**Comment by TobiMichael96** [comment]
@timurb To be honest I don't remember what we did there, but I'm pretty sure we used a config file and did not provide the key via the command line. I'm sorry I can't help you.

**Comment by timurb** [comment]
No worries, thanks for the response!
