### ISSUE TITLE
Change plugin es docs to be consistent with codes 

### ISSUE THREAD

**Issue by xuyang1996** [fluent/fluent-bit#2276]
For plugin es, 
The config **Type** in code is _doc (See FLB_ES_DEFAULT_TYPE), but in docs is fluentbit (See Type name). 
It seems the docs aren't consistent with codes.

# Code 
https://github.com/fluent/fluent-bit/blob/master/plugins/out_es/es.h

![image](https://user-images.githubusercontent.com/16434756/85098528-8e5db600-b22d-11ea-859d-a95f96cd488c.png)

# Docs
https://docs.fluentbit.io/manual/v/master/pipeline/outputs/elasticsearch
![image](https://user-images.githubusercontent.com/16434756/85098567-afbea200-b22d-11ea-8835-6803a2776fad.png)

**Comment by alitoufighi** [comment]
Even default index is not the same.

**Comment by ted-sigsci** [comment]
changed in #1750 to `_doc`, and might be causing other problems.

**Comment by edsiper** [comment]
thanks, it has been just fixed:

https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
