### ISSUE TITLE
Fluentbit logs parse hits an error although regex matches

### ISSUE THREAD

**Issue by RashaHaj** [fluent/fluent-bit#2293]
Hello, I'm using fluentbit to export logs to fluentd. The parse of logs doesn't work, although regex expression matches the log lines

To Reproduce

Rubular link : https://rubular.com/r/4uiMOVlHZHF7Xo
Fluentular link : http://fluentular.herokuapp.com/parse?regexp=%5E%5Cs*%28%3F%3Cdate%3E%5B%5E+%5D*%29%5Cs%2B%28%3F%3Ctime%3E%5B%5E+%5D*%29%5Cs%2B%5Cs%2B%28%3F%3Clog_level%3E%5B%5E+%5D*%29%5Cs%2B%28%3F%3Ccode%3E%5B%5E+%5D*%29%5Cs%2B---%5Cs%2B%5C%5B%28%3F%3Chost_thread%3E%5Ba-zA-Z1-9%5C-%5Cs%5D*%29%5C%5D%5Cs%2B%28%3F%3Cmessage%3E.*%29&input=2020-06-22+16%3A18%3A55.669++ERROR+7+---+%5B+++++++++++main%5D+o.apache.catalina.core.StandardService+++%3A+Failed+to+start+connector+%5BConnector%5BHTTP%2F1.1-9191%5D%5D%0D%0A2020-06-22+18%3A50%3A57.779++WARN+307+---+%5B+++++++++++main%5D+aWebConfiguration%24JpaWebMvcConfiguration+%3A+spring.jpa.open-in-view+is+enabled+by+default.+Therefore%2C+database+queries+may+be+performed+during+view+rendering.+Explicitly+configure+spring.jpa.open-in-view+to+disable+this+warning%0D%0A2020-06-22+18%3A51%3A16.682++WARN+307+---+%5B127-9191-exec-1%5D+c.o.o.b.a.c.JwtAuthenticationFilter++++++%3A+couldn%27t+find+bearer+string%2C+will+ignore+the+header%0D%0A&time_format=

{"Error log from fluentbit":"    
    <parse>
      @type "regexp"
      expression /^\s*(?<date>[^ ]*)\s+(?[^ ]*)\s+\s+(?[^ ]*)\s+(?[^ ]*)\s+---\s+\[(?[a-zA-Z1-9\-\s]*)\]\s+(?.*)/
      unmatched_lines 
    </parse>"}"}
Steps to reproduce the problem:
Expected behavior

Your Environment

Version used: fluentd="1.11.1" ruby="2.4.10"
Environment : Kubernetes
Operating System and version: CentOS Linux release 7.8.2003 (Core)
Configuration:

{"td-agent.conf":"    

 <match fluent.**>
   type null
  </match>

<source>
  @type tail
  path /logs/access.log
  pos_file /var/log/td-agent/person.log.pos
  tag person.log
  read_from_head true
  format /^\s*(?<date>[^ ]*)\s+(?<time>[^ ]*)\s+\s+(?<log_level>[^ ]*)\s+(?<code>[^ ]*)\s+---\s+\[(?<host_thread>[a-zA-Z1-9\-\s]*)\]\s+(?<message>.*)/
</source>

<match *.**>
  @type forward
  @id forward_output
  heartbeat_type none
 <buffer time,tag,message>
    @type memory
    timekey 2s
    timekey_wait 1s
    flush_mode interval
    flush_interval 1s
    # use smaller retry setting for test
     retry_max_interval 2s
     retry_timeout 10s
  </buffer>

  <server>
# host fluentd
    host 10.104.97.224
  </server>
</match>

  "}

Any help please ? thanks !

**Comment by nokute78** [comment]
The issue is about fluentd, right ?
Your configuration file seems to be for fluentd and it means fluentd tries to parse logs.

If so, would you open an issue on fluentd repository ?

**Comment by RashaHaj** [comment]
No , it's about fluentbit not fluentd. The parse is on source, meant to be done by fluentbit (td-agent).  My problem is that although regex matches the logs on both rubular and fluentular, fluentbit still generates a parse error "**unmatched_lines**" .

[https://rubular.com/r/4uiMOVlHZHF7Xo](url)

Here is the configuration file **td-agent.conf** content ( section source): 

> \<source>
  @type tail
  path /logs/access.log
  pos_file /var/log/td-agent/person.log.pos
  tag person.log
  read_from_head true
  format /^\s*(?<date>[^ ]*)\s+(?<time>[^ ]*)\s+\s+(?<log_level>[^ ]*)\s+(?<code>[^ ]*)\s+---\s+\[(?<host_thread>[a-zA-Z1-9\-\s]*)\]\s+(?<message>.*)/
\</source>

**Comment by nokute78** [comment]
td-agent is not fluentbit. 

https://www.fluentd.org/faqs
`In one word, td-agent is a stable distribution package of Fluentd.`

`unmached_line` log seems to be generated in_tail plugin of “fluentd”.
https://github.com/fluent/fluentd/blob/6beca80f6467fd2e12ea25b21e0474d978007b08/lib/fluent/plugin/in_tail.rb#L453

**Comment by edsiper** [comment]
thanks @nokute78 

@RashaHaj pls open a ticket in Fluentd repo to get assistance.

**Comment by RashaHaj** [comment]
@nokute78 Thanks for your reply :)

**Comment by nokute78** [comment]
@RashaHaj You're welcome.
