### ISSUE TITLE
filter_kubernetes does not read token file unless /var/run/secrets/kubernetes.io/serviceaccount/namespace exists

### ISSUE THREAD

**Issue by storpipfugl** [fluent/fluent-bit#2299]
## Bug Report

**Describe the bug**
If /var/run/secrets/kubernetes.io/serviceaccount/namespace does not exists reading of token file is skipped: https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_meta.c#L100:L114

**To Reproduce**
1) Run fluent-bit (not k8s deployed) on host with token file for valid fluent-bit k8s serviceaccount set for Kube_Token_File and set Kube_URL and Kube_CA_File to appropriate cluster values.
2) fluent-bit now gets k8s auth denied for filter_kubernetes
3) Create /var/run/secrets/kubernetes.io/serviceaccount/namespace on the host and now the filter works

**Additional context**
This is for the case when fluent-bit already runs as a service on the host so daemonset deployment is not desired

**Comment by m4rcu5** [comment]
I'd like to confirm this bug. I am glad to find this report, as it is a pretty hard one to debug.
The logs do not show an error regarding the Kubernetes filter, but just don't enrich the logs.

I am running the exact same use-case, where I already have other data collected on the host, and would like to ingest the Kubernetes logs as well, using a ready created service account. Creating the namespace file does indeed solve it, but is not a solution for production. 

Looking at the code comment I an afraid the indented use-case of fluent-bit outside of a container is only for testing, using the `kubectl proxy` to handle authentication. 

I hope someone could implement a fix for this, that would be highly appreciated.
