### ISSUE TITLE
Kube_filter : Extracting ip address of the pod as one of the metadata 

### ISSUE THREAD

**Issue by Bhavanaashok33** [fluent/fluent-bit#2301]
Hi, 
I am not sure if this feature is already available.. so reaching out to your guys. Please let me know.. 

I  have deployed Fluentbit Daemonset on the Kubernetes cluster. I have followed everything from the below instructions and things are working as expected.
https://docs.fluentbit.io/manual/installation/requirements
https://docs.fluentbit.io/manual/installation/sources/build-and-install

I was thinking, if there is a way to query Kubernetes API Server to extract Pod IP address. Does Fluentbit Kubernetes filter supports this feature ? 

Thanks

**Comment by edsiper** [comment]
do you want to append Pod IP to the records ?

we don't process such information at the moment

**Comment by Bhavanaashok33** [comment]
Yes, that's exactly what I am looking for.

**Comment by edsiper** [comment]
is this info exposed as part of the metadata from API server ?

**Comment by Bhavanaashok33** [comment]
It should be. I am assuming if not, then "kubectl get pods" wouldn’t be able to print it
