### ISSUE TITLE
Support tailing multiple subdirectories with the recursive glob pattern **

### ISSUE THREAD

**Issue by jsubirat** [fluent/fluent-bit#2310]
**Is your feature request related to a problem? Please describe.**
When specifying a `Path` to the `tail` plugin, I can specify wildcards to collect multiple files based on their filename, but there is no wildcard support for the recursive glob pattern **. I would like to be able to specify a folder and collect all the logs from all the files and subfolders (and subfolders of subfolders) within that folder.

**Describe the solution you'd like**
I have been using Fluent Bit to tail multiple files within a directory using a wildcard in the "Path" parameter of the tail input plugin, like:
```
[INPUT]
    Name        tail
    Path /var/log/*.log
```

I would like to have a way to target all the files and files within the subdirectories of a given path. Something like this:
```
[INPUT]
    Name        tail
    Path /var/log/**/*.log
```

Or even:
```
[INPUT]
    Name        tail
    Path /var/log/**/*
```

**Describe alternatives you've considered**
A possible alternative would be to create a new _Folder_ configuration parameter, which will include all  the subfolders and files within that folder:
```
[INPUT]
    Name        tail
    Folder /var/log
```

**Additional context**
Having logs coming from potentially multiple different files and/or services can make it harder to identify a log record source later. If possible, I think it would be useful if the outgoing log record contained, apart from the `log/message` field, a `file` field, like so:

```
{
    "log": "Log message as collected from the file",
    "file": "/var/log/apache2/apache2.log"
}
```

**Comment by ace03uec** [comment]
Hey! Has this been addressed in any way ? I see https://github.com/fluent/fluent-bit/issues/1508 was created for including multiple files as csv, but that could still pose issue if the names are created dynamically.
