### ISSUE TITLE
Cannot turn FLB_STREAM_PROCESSOR and FLB_RECORD_ACCESSOR general options off

### ISSUE THREAD

**Issue by mepeccin** [fluent/fluent-bit#2314]
Linking problems when turning FLB_STREAM_PROCESSOR and FLB_RECORD_ACCESSOR options off:
...
[ 98%] Linking C executable ../bin/fluent-bit
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function 'rule_create':
expect.c:(.text+0x5de): undefined reference to 'flb_ra_create'
...

**To Reproduce**
1 - get source code from https://fluentbit.io/releases/1.4/fluent-bit-1.4.6.tar.gz
2 - untar
3 - run "cd fluent-bit-1.4.6/build/"
4 - run "cmake -DFLB_STREAM_PROCESSOR=No -DFLB_RECORD_ACCESSOR=No ../"
5 - run "make"

**Expected Behavior**
Build to completion without errors, so I can run "make install" next.

**Actual Result**
...
[ 98%] Linking C executable ../bin/fluent-bit
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function 'rule_create':
expect.c:(.text+0x5de): undefined reference to 'flb_ra_create'
/usr/bin/ld: expect.c:(.text+0x6e4): undefined reference to 'flb_ra_create'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function 'rule_destroy':
expect.c:(.text+0x7d2): undefined reference to 'flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o): in function 'rule_apply':
expect.c:(.text+0xe25): undefined reference to 'flb_ra_get_value_object'
/usr/bin/ld: expect.c:(.text+0xe4e): undefined reference to 'flb_ra_key_value_destroy'
/usr/bin/ld: expect.c:(.text+0xfc4): undefined reference to 'flb_ra_key_value_destroy'
/usr/bin/ld: expect.c:(.text+0x1152): undefined reference to 'flb_ra_key_value_destroy'
/usr/bin/ld: expect.c:(.text+0x12e0): undefined reference to 'flb_ra_key_value_destroy'
/usr/bin/ld: expect.c:(.text+0x149c): undefined reference to 'flb_ra_key_value_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_expect.a(expect.c.o):expect.c:(.text+0x14b6): more undefined references to 'flb_ra_key_value_destroy' follow
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function 'process_config':
rewrite_tag.c:(.text+0x9f5): undefined reference to 'flb_ra_create'
/usr/bin/ld: rewrite_tag.c:(.text+0xb62): undefined reference to 'flb_ra_destroy'
/usr/bin/ld: rewrite_tag.c:(.text+0xba4): undefined reference to 'flb_ra_create'
/usr/bin/ld: rewrite_tag.c:(.text+0xc44): undefined reference to 'flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function 'process_record':
rewrite_tag.c:(.text+0x10a9): undefined reference to 'flb_ra_regex_match'
/usr/bin/ld: rewrite_tag.c:(.text+0x1117): undefined reference to 'flb_ra_translate'
/usr/bin/ld: ../library/libflb-plugin-filter_rewrite_tag.a(rewrite_tag.c.o): in function 'destroy_rules':
rewrite_tag.c:(.text+0x13d5): undefined reference to 'flb_ra_destroy'
/usr/bin/ld: rewrite_tag.c:(.text+0x13e5): undefined reference to 'flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function 'delete_rules':
grep.c:(.text+0x4f2): undefined reference to 'flb_ra_destroy'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function 'set_rules':
grep.c:(.text+0x885): undefined reference to 'flb_ra_create'
/usr/bin/ld: ../library/libflb-plugin-filter_grep.a(grep.c.o): in function 'grep_filter_data':
grep.c:(.text+0xa96): undefined reference to 'flb_ra_regex_match'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:240: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:4796: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Environment**
OS: Ubuntu 18.04
CMake command: cmake -DFLB_STREAM_PROCESSOR=No -DFLB_RECORD_ACCESSOR=No ../
Fluent Bit version: fluent-bit-1.4.6

**Additional Comment**
It doesn't matter having Flex and Bison installed.
Functions like 'flb_ra_create' and 'flb_ra_destroy' shouldn't be called anywhere as FLB_RECORD_ACCESSOR option is set to No.
Or this particular subset of functions should be available even when FLB_RECORD_ACCESSOR option is set to No (because other features may need them).
Or FLB_RECORD_ACCESSOR cannot be turned off while some other feature is on (in which case the configuration consistency check is failing and an error should be reported while running 'cmake ...').

**Comment by edsiper** [comment]
thanks for reporting the problem. 

I've pushed the fixes to GIT master.
