### ISSUE TITLE
Warn messages with 'Invalid time format' does not print the configured Time_Format

### ISSUE THREAD

**Issue by rmacian** [fluent/fluent-bit#2315]
## Bug Report

**Describe the bug**
When you define a different Time_Format in a parser section if the timestamp does not match does not show your configured Time_Format.

This misleads the debugging because you think it's not taking your Time_Format, in my case my error was I have included a T character between date and time and this app takes a white space so I had this timestamp in my logs:

```
2020-07-01 02:27:16.578
```
and this was my expression with a .%L added at the end
```
Time_Format %Y-%m-%dT%H:%M:%S.%L
```
but the correct expression was (note that I put a T but I had a blank space) :
```
Time_Format %Y-%m-%d%t%H:%M:%S.%L
```
but the warning printed a Time_Format without the .%L  added 
```
2020/07/01 10:50:27] [ warn] [parser:resumes-api] Invalid time format %Y-%m-%dT%H:%M:%S for '2020-07-01 10:50:27.006'.
```
**To Reproduce**

My paser:
```
    [PARSER]
        Name my-api
        Format Regex
        Regex ^.*supercomplicatedregex
        Time_Key timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
```
log example:
```
{"log":"{\"component\": \my-api\", \"timestamp\": \"2020-07-01 02:27:16.577\", \"level\": \"INFO\", \"message\": \"Random message.\", \"scope\": \"\", \"requestId\": \"962e115ca8\"}\n","stream":"stdout","time":"2020-07-01T02:27:16.588317992Z"}
```
The warning:
```
2020/07/01 10:50:27] [ warn] [parser:resumes-api] Invalid time format %Y-%m-%dT%H:%M:%S for '2020-07-01 10:50:27.006'.
```

**Expected behavior**

The warning should output:
```
2020/07/01 10:50:27] [ warn] [parser:resumes-api] Invalid time format %Y-%m-%dT%H:%M:%S.%L for '2020-07-01 10:50:27.006'.
```

**Your Environment**

* Version used: 1.4.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Openshift 3.11
* Server type and version:
* Operating System and version: RHEL7
* Filters and plugins:

**Comment by edsiper** [comment]
thanks for reporting this problem.

It has been fixed on 0bd9b04 and will be part of v1.5 release
