### ISSUE TITLE
[Feature] Expose metrics in Prometheus format

### ISSUE THREAD

**Issue by sdurrheimer** [fluent/fluent-bit#233]
Hi there,

As a hosted project of the CNCF, it would be nice to expose native Prometheus metrics like it has been done with a [plugin](https://github.com/kazegusuri/fluent-plugin-prometheus) for Fluentd.

**Comment by edsiper** [comment]
thanks. Definitely something to do.

**Comment by prune998** [comment]
where is it located in the todo-list ?

**Comment by edsiper** [comment]
@prune998 this issue, it's labeled as enhancement.

**Comment by lpic10** [comment]
I'm waiting for this feature to migrate from Fluentd

**Comment by prune998** [comment]
waiting is the new dying :)

**Comment by edsiper** [comment]
Work in process, current status

- [x] create internal generic metrics interface
- [x] input plugins use metrics interface 
- [x] metrics exporter
- [ ] http server interface (work in process, this week)
- [ ] metrics exporter, register HTTP endpoints and share metrics

**Comment by edsiper** [comment]
Some progress, HTTP Server functional

![fluentbit_rest](https://user-images.githubusercontent.com/369718/31159650-2854f746-a890-11e7-8558-e50d8c5762a0.jpg)

**Comment by prune998** [comment]
That's great news ! thanks for the effort !

**Comment by edsiper** [comment]
We are getting closer:

- [x] create internal generic metrics interface
- [x] input plugins use metrics interface
- [x] metrics exporter
- [x] http server interface (work in process, this week)
- [ ] metrics exporter, register HTTP endpoints and share metrics

the last part is to add Prometheus format, we have plain JSON for now:

![flb_input_metrics](https://user-images.githubusercontent.com/369718/31521476-4494e8e0-af6f-11e7-8e4c-b318ab5289d1.jpg)

**Comment by edsiper** [comment]
looks like we are done
![prom](https://user-images.githubusercontent.com/369718/32087878-6c659920-badf-11e7-9e11-3ea9582b5938.jpg)

**Comment by prune998** [comment]
that's great ! thanks

**Comment by jsravn** [comment]
Any plans to incorporate fields into this? E.g. in Kubernetes it'd be nice to see the various values per pod or namespace.

**Comment by azweb76** [comment]
This is awesome. Are we ready to merge?

**Comment by azweb76** [comment]
Looks like this is already available. Thanks all! Should this be resolved?

**Comment by Quentin-M** [comment]
Hi there,

How can we get the queue length, in other words, how can we estimate how far behind fluent-bit gets reading/processing/sending the logs to the output(s)?

**Comment by discordianfish** [comment]
@edsiper Guess this can be closed then?
Probably makes sense to track further improvements in #516

**Comment by edsiper** [comment]
Metrics already implemented: 

https://docs.fluentbit.io/manual/configuration/monitoring

Fixed.

**Comment by bobykus31** [comment]
Wonder why metrics show up with strange numbers


cat /etc/td-agent-bit/td-agent-bit.conf 
```
[SERVICE]
    Flush               10
    Daemon              off
    Log_Level           debug
    HTTP_Server         On
    HTTP_PORT           2020

[INPUT]
    Name                systemd
    Max_Entries         5000
    DB                  /var/log/systemd.db
    Mem_Buf_Limit       5MB
    Tag                 journal.0

[OUTPUT]
    Name                forward
    Match               *
    Host                forward.com
    Port                24888

[FILTER]
    Name                record_modifier
    Match               *
    Record              host me.com


```

curl -s http://127.0.0.1:2020/api/v1/metrics | jq

```
{
  "input": {
    "systemd.0": {
      "records": 11,
      "bytes": 6540
    }
  },
  "filter": {
    "record_modifier.0": {
      "drop_records": 0,
      "add_records": 0
    }
  },
  "output": {
    "forward.0": {
      "proc_records": **0**,
      "proc_bytes": **101869**,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0
    }
  }
}

```

So the same is   curl -s http://127.0.0.1:2020/api/v1/metrics/prometheus, why  fluentbit_output_proc_records_total is zero while  fluentbit_output_proc_bytes_total is 101869 or whatever?
