### ISSUE TITLE
Content-Type set via Header yields to duplicate HTTP headers

### ISSUE THREAD

**Issue by LionelCons** [fluent/fluent-bit#2336]
When configuring the `http` output, one can set headers via the `Header` option.

When setting the `Content-Type` header, this yields to duplicate HTTP headers.

This is because the `Content-Type` header is always hard-coded (see https://github.com/fluent/fluent-bit/blob/master/plugins/out_http/http.c#L122), regardless of whether this header is explicitly set in the configuration file or not.

The default `Content-Type` (from `ctx->out_format`) should only be used when there is no explicit `Content-Type` defined.

**Comment by edsiper** [comment]
Fixed in 8d59c2fad3d11abea777bda1bd25f07be2ef44ac
