### ISSUE TITLE
tcp sessions

### ISSUE THREAD

**Issue by eskornev** [fluent/fluent-bit#234]
Hello, I can see that fluent-bit (v0.11.2) constantly originates new tcp sessions to fluentd server.
For about one day it creates more than 2000 sessions:

root@fluentbit-4zg6h:/# netstat -anpet |grep 24224 |wc -l
2186

It works in Kubernetes, config is like this:

    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    debug
        Log_File     /fluent-bit/log/fluent-bit.log
        Parsers_File parsers.conf

    [INPUT]
        Name tail
        Path /mnt/*.log
        Exclude_Path /mnt/fluentbit*
        DB /tmp/files.db
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB

    [FILTER]
        Name   kubernetes
        Match kube.*

    [OUTPUT]
        Match *
        Name forward
        Host 192.168.242.110
        Port 24224

How can I eliminate such situation?

**Comment by edsiper** [comment]
thanks for reporting this problem, it was introduced by a silly mistake on my end.

I am pushing a new hot-fix release in a couple of minutes.

**Comment by edsiper** [comment]
FYI: v0.11.3 have been just released.

- Docker images updated, please use tag 0.11.3
- Tarballs available on fluentbit.io
- RPM/Deb packages are still being build.

thanks again for reporting this issue.

**Comment by eskornev** [comment]
Superb!
