### ISSUE TITLE
[question] control output availability

### ISSUE THREAD

**Issue by liamstask** [fluent/fluent-bit#2340]
The network gateway on my system supports connectivity via multiple interfaces, and I would like to ensure that fluentbit only attempts log offload when a specific interface is enabled.

This gateway device provides an api to determine the active interface - is there a way to make fluentbit aware of this state, to restrict when it attempts to actually send data to the configured output destinations?

The C api initially appeared to possibly be an option here, but I'm not sure it provides this level of control. ie, the engine must remain running to ensure that `tail` inputs continue to be monitored & stored, it's just the output that needs to be gated.

Thanks for any suggestions!

**Comment by edsiper** [comment]
@liamstask thanks for reaching out.

Fluent Bit v1.5 (to be released in July 13th), comes with a new networking setup options for all plugins that relies in network I/O. One of the new options introduced is called ```net.source_address``` which allows to specify your desired network interface. 

We don't provide a dynamic mechanism to decide which interface to use, but what you can do is to use an environment variable to set the required interface, but note the value will persist after the service starts:

https://docs.fluentbit.io/manual/v/master/administration/networking#configuration-options

**Comment by liamstask** [comment]
Thanks for the quick response 🙏

That seems useful 👍 though in this particular case, the gateway device (effectively the router) on my network is the device that supports multiple interfaces, switching between them based on availability.

The device actually running fluent-bit in this case would actually only have a single network interface.

Is it possible to indicate to fluent-bit whether to attempt to make outbound connections based on the status of the gateway device (which has its own custom api to query the active interface)?

Thanks again.

**Comment by edsiper** [comment]
Such feature is not available. what's your device use case / general purpose ?

**Comment by liamstask** [comment]
This is a system that supports both LTE and WiFi connectivity - depending on location, one or the other might be available. Due to the cost & bandwidth of LTE data transfer, and the fact that slightly delayed offload is tolerable, it's preferable to only offload when WiFi is available.

Please let me know if that's too vague - attempting to limit the amount of info disclosed.

**Comment by edsiper** [comment]
thanks for the info. 

Interesting use case but the feature to solve the problem is not available.

**Comment by liamstask** [comment]
thanks for the confirmation.

is this worth adding a request for, or does this diverge enough from the cases that fluent-bit aims to support that it doesn't really make sense?

**Comment by edsiper** [comment]
you can add the request but if this is your unique use case and nobody else need it, it will lack of priority.
