### ISSUE TITLE
fluentbit forward to fluentd HA aggregator

### ISSUE THREAD

**Issue by adasari** [fluent/fluent-bit#2343]
Hello,

Is it possible to forward logs to fluentd aggregator from fluentbit ? fluentd supports forwarding logs to fluentd aggregator 
fluentd configuration is 
```
# Log Forwarding
<match mytag.**>
  @type forward

  # primary host
  <server>
    host 192.168.0.1
    port 24224
  </server>
  # use secondary host
  <server>
    host 192.168.0.2
    port 24224
    standby
  </server>
</match>

```

i couldnt find standbyy configuration in fluentbit forward. Please advise.

Thanks.

**Comment by toan-hf** [comment]
Nope, FluentBit support to forward log over TCP. But there is no support for HA (Active - Standby) like you want.
