### ISSUE TITLE
Windows Development for Fluent Bit v1.6.0

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#2351]
Fluent Bit v1.6 development cycle has started. This cycle (according to
the milestone) is expected to be about 3 months from today.

https://github.com/fluent/fluent-bit/milestone/9

For Windows subsystem, I'm currently thinking to work on `in_tail`'s large
file support #2208 first, but do not have much concrete plans other than that.

I'm trying to incorporate your (Windows users) voice to this development cycle,
so please comment here if you have ideas or issues.

**Comment by PettitWesley** [comment]
@fujimotos Is there any place with a full list of features that work on Windows?

**Comment by fujimotos** [comment]
> Is there any place with a full list of features that work on Windows?

@PettitWesley `cmake/windows-setup.cmake` contains the list of features
and plugins confirmed to work on Windows.

https://github.com/fluent/fluent-bit/blob/master/cmake/windows-setup.cmake

**Comment by k3nny0ne** [comment]
Any plans to enable Kafka Output support in 1.6.0 cycle?

**Comment by theggelund** [comment]
Are there any thoughts or plans about porting filesystem storage and metrics http endpoint support?

**Comment by fujimotos** [comment]
> Any plans to enable Kafka Output support in 1.6.0 cycle?

@k3nny0ne There is no ETA. The problem is the dependency on OpenSSL.
It caused so many deployment troubles, so we cannot turn it on by deafult.

For now, you need to turn on the build flag manually to use `out_kafka` on Windows.

> Are there any thoughts or plans about porting filesystem storage and metrics http endpoint support?

@theggelund HTTP endpoint support requires porting Monkey web server
to Windows. I don't think it comes soon.

Porting filesystem storage is a bit easier and probably can be ported on the next 
development cycle (= v1.7.0 cycle).

**Comment by fujimotos** [comment]
Released.
