### ISSUE TITLE
Add an option not to set the date in JSON

### ISSUE THREAD

**Issue by LionelCons** [fluent/fluent-bit#2352]
When using a JSON output format, the event date is always set. One can change the key name via `json_date_key` but there is no way not to set the date.

In case the receiver needs a specific data format which is not handled via `json_date_format`, it is easy to set the date in Lua. As an example, the receiver might expect a date as the number of milliseconds since the Epoch. We can easily use:
```
  record.timestamp = math.floor(timestamp * 1000 + 0.5)
```
but Fluent Bit will also put the date in another key.

Something like:
```
    json_date_key none
```
could tell Fluent Bit not to add the date in JSON.

**Comment by edsiper** [comment]
which output plugin are you referring to ?

**Comment by LionelCons** [comment]
In my use case, this is the `http` output plugin sending JSON data to an infrastructure that expects the date to be the number of milliseconds since the Epoch.

**Comment by LionelCons** [comment]
FWIW, I have tested this on master and it works fine. Thanks!

**Comment by edsiper** [comment]
thanks. Closing.
