### ISSUE TITLE
The http output plugin does not properly detect empty responses

### ISSUE THREAD

**Issue by LionelCons** [fluent/fluent-bit#2358]
When using the `http` output plugin to POST log entries to a server, fluent-bit's log file contains empty lines (between the `HTTP status` lines):
```
[2020/07/15 11:01:01] [ info] [output:http] server.acme.com:12345, HTTP status=200

[2020/07/15 11:01:01] [ info] [output:http] server.acme.com:12345, HTTP status=200

[2020/07/15 11:01:01] [ info] [output:http] server.acme.com:12345, HTTP status=200
```

Looking at the code (https://github.com/fluent/fluent-bit/blob/master/plugins/out_http/http.c#L191) this is maybe because the check is on `c->resp.payload` and not on `c->resp.payload_size`.

**Comment by LionelCons** [comment]
And while you're at it...

Should these messages rather be `debug` instead of `info`?

In my environment, `fluent-bit` issues POST requests frequently so the log file contains mostly these (useless) `HTTP status` lines. If I change the log level to `warning`, I will miss the other useful `info` messages logged by other parts of `fluent-bit`.

**Comment by edsiper** [comment]
@LionelCons thanks, yeah, it should check payload and payload size for the message, just fixed in 67866082

About the log_level, note that you can set a custom log_level into the plugin configuration section only.

**Comment by LionelCons** [comment]
Thanks for the fix!

I did not know about the per plugin `log_level` setting. This is excellent. I did not find it in the documentation. Maybe it should be given more visibility?

**Comment by LionelCons** [comment]
I have tried and in fact found a bug in the documentation...

The documented log level is `warning` (https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file) but `warn` must be used.

I have created https://github.com/fluent/fluent-bit-docs/pull/342 to fix this.

**Comment by nikhithakarennagari** [comment]
@LionelCons 
There are many HTTP status=200 log lines which are spamming the log file and leading to high memory usage. Can we have only a single log stating something like "connection established" (until dis connectivity)instead of these many logs.
