### ISSUE TITLE
 'Can't merge a non object mapping [kubernetes.labels.app] with an object mapping [kubernetes.labels.app]

### ISSUE THREAD

**Issue by tirelibirefe** [fluent/fluent-bit#2368]
## Bug Report

**Describe the bug**
Fluent-bit cannot parse Kubernetes logs properly.

`#0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: illegal_argument_exception [reason]: 'Can't merge a non object mapping [kubernetes.labels.app] with an object mapping [kubernetes.labels.app]'"`

**To Reproduce**

Nothing special; 

helm install fluent/fluent-bit --version 0.6.0

- Rubular link if applicable:
- Example log message if applicable:

`#0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: illegal_argument_exception [reason]: 'Can't merge a non object mapping [kubernetes.labels.app] with an object mapping [kubernetes.labels.app]'

- Steps to reproduce the problem:

**Expected behavior**

I expect fluent-bit can parse k8s logs and forward them to fluentd.

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by srideok2** [comment]
Any update on how this issue is resolved?

**Comment by mm3906078** [comment]
I have same issue.
