### ISSUE TITLE
Tail plugin multiline option not working

### ISSUE THREAD

**Issue by pauloduartepinho** [fluent/fluent-bit#2372]
## Bug Report

**Describe the bug**
Fluent bit server stops with message of "[error] [input:tail:tail.0] multiline: invalid parser 'multi_line_logs'". I am attemping to process multiline logs

**To Reproduce**
- Run fluent-bit as normal, using the configuration on the enviroment part of this bug report
- Fluent bit gets following error on start up
```
[2020/07/20 16:12:28] [ info] [engine] started (pid=1)
[engine] caught signal (SIGSEGV)
[2020/07/20 16:12:28] [ info] [storage] version=1.0.4, initializing...  
[2020/07/20 16:12:28] [ info] [storage] in-memory  
[2020/07/20 16:12:28] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128  
[2020/07/20 16:12:28] [error] [input:tail:tail.0] multiline: invalid parser 'multi_line_logs'
```

**Expected behavior**
fluent bit starts up correctly.

**Your Environment**

* fluent bit 1.5.1
* Configuration:
```
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    verbose
        Parsers_File parsers.conf

    [INPUT]
        Name                    tail
        Multiline_Flush         5
        Multiline               On
        Parser_Firstline        multi_line_logs
        Path                    /var/log/containers/pos*.log
        Tag                     kube.*

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        
    [PARSER]
        Name multi_line_logs
        Format regex
        Regex ^(?[^\s]+:) (?.+)$
```
* Kubernetes v1.15.5
* Filters and plugins:
none

Is there a problem with my configuration? What is the problem with the parser?
If there is some information missing, please tell me.

Thanks in advance.

**Comment by xmcqueen** [comment]
It seems odd to have that Parsers_File config option, and the it looks like the PARSER is there in the same file.  Is there a parser file somehwere?

**Comment by pauloduartepinho** [comment]
Yes there is, this is being installed into kubernetes cluster via helm tool. So I simplified the output config a bit.

**Comment by pauloduartepinho** [comment]
```  
  fluent-bit-filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Merge_Log           On
  fluent-bit-input.conf: |
    [INPUT]
        Name                tail
        Multiline_Flush     5
        Multiline           On
        Parser_Firstline    multi_line_logs
        Path                /var/log/containers/pos*.log
        Tag                 kube.*
  fluent-bit-output.conf: |
    [OUTPUT]
        Name                stdout
        Match               *
  fluent-bit-service.conf: |
    [SERVICE]
        Flush               1
        Daemon              Off
        Log_Level           verbose
        Parsers_File        parsers.conf
  fluent-bit.conf: |
    @INCLUDE fluent-bit-service.conf
    @INCLUDE fluent-bit-input.conf
    @INCLUDE fluent-bit-filter.conf
    @INCLUDE fluent-bit-output.conf
  parsers.conf: |
    [PARSER]
        Name                multi_line_logs
        Format              regex
        Regex               ^(?[^\s]+:) (?.+)$
```

full unedited config

**Comment by xmcqueen** [comment]
Hmmm. We need some other opinions. I don't see any problem with that config.

**Comment by pauloduartepinho** [comment]
Thank you for your help!

**Comment by pauloduartepinho** [comment]
Solved it. Turns out it was Parsers_File config option, but withing a different scope, fluent bit helm chart uses a "subPath" option on its configmap/volume configuration (which I don't fully understand as I am now starting with kubernetes environments so I won't go into detail) that caused parsers.conf to have the "default" fluent-bit parsers file.

This can be closed, but I would like to suggest that fluent-bit could be more verbose in its output when starting up, in order to inform what parsers have been loaded, maybe outputting trace or debug messages in that effect.

**Comment by edsiper** [comment]
# Multiline Update

As part of Fluent Bit v1.8, we have released a new Multiline core functionality. This new big feature allows you to configure new `[MULTILINE_PARSER]`s that support multi formats/auto-detection, new multiline mode on Tail plugin, and also on v1.8.2 (to be released on July 20th, 2021) a new Multiline Filter. 

For now, you can take at the following documentation resources:

- [Multiline Parsers / Concepts and Configuration](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing)
- [Tail + New Multiline Core Feature](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support)
- [New Multiline Filter](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace)

Documentation pages now point to complete config examples that are available on our repository.

Thanks everyone for supporting this!
