### ISSUE TITLE
Help Question: Wildcard usage in SQL Stream Processors

### ISSUE THREAD

**Issue by moserke** [fluent/fluent-bit#2373]
Trying to determine if wildcards are usable in SQL Statement Syntax in the streams processor (https://github.com/fluent/fluent-bit/tree/master/src/stream_processor)

Essentially what I am trying to do is something like:

```
[STREAM_TASK]
  | Name   example
  | Exec   CREATE STREAM example WITH (tag='example') AS SELECT * from STREAM:kubernetes_logs WHERE kubernetes['namespace_name']='example-*';
```

I've tried all of the SQL wildcards I can think of (`LIKE`, `*`, `%`) but none seem to work.  Just looking for validation if it's possible and perhaps a note in the docs if it's not.

Thanks so much in advance!

**Comment by koleini** [comment]
@moserke Unfortunately, wildcard is not currently supported in WHERE clause.
