### ISSUE TITLE
Nginx access log fields are always strings

### ISSUE THREAD

**Issue by okossuth** [fluent/fluent-bit#2378]
Hello
I'm using fluent/fluent-bit:1.4.6 on kubernetes to send nginx access log data to elasticsearch and it is working correctly. However i have noticed the data is being sent as strings for all the fields. Is there a way to make fluentbit aware that some fields should be treated as integers, numbers or floats so elasticsearch can recognize them as such and not as strings?

for example the field size_bytes should be treated as an integer/number so i can use it with elasticsearch to aggregate data based on that field. I'm attaching the config being used:
 
  fluent-bit.conf: |
    [SERVICE]
        Flush         10
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
 
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
 
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/nginx*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  60
 
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes 
        Match               kube.*
        Kube_URL            https://xxxxxxxxxxxxxxxx:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        K8S-Logging.Parser  On
        Merge_Log_Trim      On
 
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Retry_Limit     False
 
  parsers.conf: |
 
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
 
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
 
    [PARSER]
        Name   nginx
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<suser>[^ ]*) \[(?<dtime>[^\]]*)\]  "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<status_code>[^ ]*) (?<size_bytes>[^ ]*) $
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

Thanks!

**Comment by okossuth** [comment]
Ok i was able to solve the issue with this config and using a lua script in case anyone needs it :

 [FILTER]
        Name    lua
        Match    *
        script    numbers.lua
        call       conv
        Type_int_key sbytes   #cbytes is not here because its a double. sbytes should be an integer always

  numbers.lua:

       function conv(tag, timestamp, record)
           record["sbytes"] = tonumber(record["sent_http_bytes"])
           record["cbytes"] = tonumber(record["sent_http_compression"])
           return 1, timestamp, record
       end

**Comment by bohrasd** [comment]
Actually there's a `Types` key in parser metioned in 1.3 documents: https://docs.fluentbit.io/manual/v/1.3/parser

> Specify the data type of parsed field. The syntax is types <field_name_1>:<type_name_1> <field_name_2>:<type_name_2> .... The supported types are string(default), integer, bool, float, hex. ltsv, logfmt and regex supports this option.

I dont know why I can't find this anywhere in the latest version of documents.

Make sure the name of your parser dont overlapped with the preset parsers or your parser wont be used.
https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf

**Comment by okossuth** [comment]
@bohrasd Thanks for the tip good to know!

**Comment by okossuth** [comment]
@bohrasd Thanks for the tip good to know!

**Comment by okossuth** [comment]
Hello
I'm reopening this issue because it seems that what @bohrasd pointed out does not work with version 1.4.6 and i assume the same with 1.5.  https://docs.fluentbit.io/manual/v/1.3/parser the Types config is not showing in the latest docs, so can any developer confirm that the Types statement in parsers doesnt work anymore?

**Comment by okossuth** [comment]
Anyone?

**Comment by bohrasd** [comment]
@okossuth It worked for me.
Is there any logs metion that the fluent-bit use the preset parser configuration when the fluent-bit start?
Try change the name of your parser and see if it works

**Comment by okossuth** [comment]
@bohrasd I was able to make it work after i deleted the elasticsearch index completely. Just a question, i assume using Types offers better performance than using the lua script conversion? I plan to use fluentbit in a cluster that has a very CPU intensive service logging constantly to disk so it would be important not to burden the CPU more...
