### ISSUE TITLE
tail: allow starting from the end of a (new) file

### ISSUE THREAD

**Issue by LionelCons** [fluent/fluent-bit#2392]
When using the `tail` input plugin with a database (`DB` option), it would be useful to have an option to start at the end of a newly found file (i.e. not known in the database). A typical use case would be a first deployment of Fluent Bit where you do not want to read all the logs but only start fresh.

The `tail` input plugin does have an `Ignore_Older` option but it is only "available when a Parser is specified and it can parse the time of a record".

Starting at the end of new files does not need any parser or any knowledge of time.

FWIW, this would correspond to `start_position=end` in Logstash file input plugin.

**Comment by edsiper** [comment]
@LionelCons recently we fixed the Tail behavior where now it always reads from the end of the file.

can we consider this ticket most like an enhancement request for the ```ignore_older``` behavior ?

**Comment by LionelCons** [comment]
The new tail behaviour indeed fixes this issue. Thanks!
