### ISSUE TITLE
The time format in the syslog-rfc5424 parser is incorrect

### ISSUE THREAD

**Issue by ThomasEscobar** [fluent/fluent-bit#2407]
## Bug Report

**Bug description**

The time format provided in the parser (found here https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf) doesn't match the format described in the [RFC5424](https://tools.ietf.org/html/rfc5424#section-6.2.3). This causes an error when parsing the logs.

**To Reproduce**

The parser used : 

```
[PARSER]
    Name        syslog-rfc5424
    Format      regex
    Regex       ^\<(?<pri>[0-9]{1,5})\>1 (?<time>[^ ]+) (?<host>[^ ]+) (?<ident>[^ ]+) (?<pid>[-0-9]+) (?<msgid>[^ ]+) (?<extradata>(\[(.*?)\]|-)) (?<message>.+)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On
```

Example of the time format as described in the [RFC5424](https://tools.ietf.org/html/rfc5424#section-6.2.3) : 
`1985-04-12T19:20:50.52-04:00`

Looking at the [Ruby strftime lib](https://ruby-doc.org/stdlib-2.6.1/libdoc/date/rdoc/DateTime.html), it shows that %Z should be used instead of %z to include the ':'

> Time zone:
  %z - Time zone as hour and minute offset from UTC (e.g. +0900)
          %:z - hour and minute offset from UTC with a colon (e.g. +09:00)
          %::z - hour, minute and second offset from UTC (e.g. +09:00:00)
          %:::z - hour, minute and second offset from UTC
                                            (e.g. +09, +09:30, +09:30:30)
  %Z - Equivalent to %:z (e.g. +09:00)

- Steps to reproduce the problem:

Try to parse logs in the IETF syslog format using the RFC5424 parser provided in the parsers.conf file.

**Error message**

`[2020/07/30 16:08:11] [ warn] [input:syslog:syslog.1] error parsing log message with parser 'syslog-rfc5424'`

**Environment**

* Version used: 1.5.2-debug
* Environment name and version: Kubernetes 1.18.5
* Filters and plugins: syslog plugin

**Resolution**

Replacing the %z by %Z solved the issue.

**Comment by yrro** [comment]
According to [the parsers documentation](https://docs.fluentbit.io/manual/data-pipeline/parsers/configuring-parser#configuration-parameters), fluent-bit uses the C library's `strptime` function. The Glibc [strptime](https://www.gnu.org/software/libc/manual/html_node/Low_002dLevel-Time-String-Parsing.html) function appears to accept `+00:00` as input to the `%z` format string component just fine.
