### ISSUE TITLE
Yocto build, parsers and  "no debug info in ELF executable " (Warrior)

### ISSUE THREAD

**Issue by Minipada** [fluent/fluent-bit#2413]
## Bug Report

**Describe the bug**
I am building fluent bit 1.6.0 using the recipe available [here](https://github.com/fluent/fluent-bit/blob/master/fluent-bit_git.bb).

I had no problems until parsers got involved. This is now what I get only when using "Parser" in my exec instruction:

```
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1
```
I am using Yocto Warrior and start fluent bit with systemd

**To Reproduce**
1. Build a yocto image with fluent bit
2. Run with this configuration:
```
[SERVICE]
    flush        5
    daemon       Off
    log_level    trace

    parsers_file parsers.conf
    plugins_file plugins.conf

    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    storage.metrics on

[INPUT]
    Name          exec
    Tag           foo
    Command       cat /data/iot
    Parser        utf8
    Interval_Sec  1
    Interval_NSec 0
    Buf_Size      8mb

[OUTPUT]
    Name   http
    Match  *
    Host   <logstash-ip>
    Port   12345
    Format json
```

The parser:
```
[PARSER]
    Name        utf8
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S %z
```

- Example log message if applicable:

```
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1
```

**Your Environment**
* Version: 1.6.0 (commit [11ebff45f791b64a2b062450d7adbbb62b0812a3](https://github.com/fluent/fluent-bit/commit/11ebff45f791b64a2b062450d7adbbb62b0812a3))
* Configuration: `-DGNU_HOST=${HOST_SYS} -DFLB_LUAJIT=Off -DFLB_FILTER_LUA=Off -DFLB_SHARED_LIB=Off -DFLB_EXAMPLES=Off `
* Environment name and version (Yocto Warrior):
* Server type and version:
* Operating System and version: Yocto custom built
* Filters and plugins: No plugins, no filters

**Additional context**
I am trying to record a JSON using exec command. Except the encoding is wrong (the json is a string).
This is imo not the big issue here as I will need more parsers later on.

**Comment by edsiper** [comment]
what is the parser configuration that you are using ?

**Comment by Minipada** [comment]
Sorry, I forgot to add it

```
[FILTER]
    Name modify
    Match *
    Set vehicle.name: foo
```

**Comment by Minipada** [comment]
Sorry, forgot to add it
```
[PARSER]
    Name        utf8
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S %z
```
