### ISSUE TITLE
WinLog input plugin stopped reporting the EventId

### ISSUE THREAD

**Issue by jsubirat** [fluent/fluent-bit#2426]
## Bug Report

**Describe the bug**
In [this pull request](https://github.com/fluent/fluent-bit/pull/2322), the parsing of the log records coming from the `winlog` INPUT plugin was fixed. However, it seems that the `EventId`, which [was being included before the fix](https://github.com/fluent/fluent-bit/pull/2322/files#diff-0890d3b5666d8c56708c223ac7bc54a3L239-L241), it [was not included in the new implementation](https://github.com/fluent/fluent-bit/pull/2322/files#diff-44387dae255041c828cb88280efd027fR350). This is an important field  which should be kept.

**To Reproduce**
- Simply capture a Windows event/log with the `winlog` plugin: the `EventId` field is not there anymore:

**Expected behavior**
`EventId` should be included in the `winlog` log records.

**Your Environment**
* Version used: FluentBit 1.5.1
* Configuration:
```
[INPUT]
    Name         winlog
    Channels     Windows PowerShell
    Interval_Sec 1

[OUTPUT]
    Name                stdout
    Match               *
```
* Server type and version: MacBook Pro
* Operating System and version: Windows 10 Pro
* Filters and plugins: `winlog` INPUT plugin

**Comment by fujimotos** [comment]
@jsubirat I submitted a patch to take the field back to the event message (#2108).
This issue will be resolved after the patch being merged.
