### ISSUE TITLE
tail input doesn't "tail" files on overlayfs kernel v4

### ISSUE THREAD

**Issue by andywinslow** [fluent/fluent-bit#2428]
## Bug Report

**Describe the bug**
tail input doesn't "tail" files on overlay filesystems using linux kernel v4

**To Reproduce**
- On an ubuntu 16.04 system (which has kernel v4.4)...
- Install docker
- Create Dockerfile with these contents:
```
FROM ubuntu:bionic
SHELL ["/bin/bash", "-c"]

RUN apt-get update \
&& apt-get install wget gnupg -y

RUN wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add -
RUN echo "deb https://packages.fluentbit.io/ubuntu/bionic bionic main" >> /etc/apt/sources.list
RUN apt-get update \
&& apt-get install td-agent-bit -y
```
- docker build -t fluent-bit-overlayfs-bug .
- docker run -it fluent-bit-overlayfs-bug /bin/bash
- verify your current directory is using overlay fs: `findmnt -T .`
- create a test log file: `bash -c 'while true; do echo "logtest-$(date --iso-8601=seconds)" >> test.log; sleep 5; done' &`
- tail the file with fluent-bit: `/opt/td-agent-bit/bin/td-agent-bit -i tail -p path=test.log -o stdout`

**Expected behavior**
roughly every 5 seconds fluent-bit should output a line like this to stdout: `[0] tail.0: [1596747168.615093330, {"log"=>"logtest-2020-08-06T20:52:48+00:00"}]`
but only the initial contents of the file are output, contents added after the fluent-bit process starts are not output

**Your Environment**
* Version used: tested with fluent-bit 1.4 and 1.5
* Operating System and version: ubuntu 16.04

**Additional context**
Some of our containers are currently run on ubuntu 16.04 hosts. These are managed by a vendor so we can't upgrade them to ubuntu 18. We would like to use fluent-bit to forward logs but it won't work on these systems because of this issue with overlay and the kernel version.
I did some debugging and found on these systems inotify events are not sent when lines are added to files on overlayfs.
I performed the same test on ubuntu 18.04 and it does work, presumably because of improvements in the newer version of the kernel.
There are probably enough of these systems still running to merit adding a polling fallback to the tail input when inotify isn't functioning.

**Comment by edsiper** [comment]
hi @andywinslow 

we have some plans to enable polling mechanism together with inotify and make it optional for the user. The current workaround is to re-build Fluent Bit turning off the CMake option -DFLB_INOTIFY=off.

**Comment by andywinslow** [comment]
Wouldn't it make sense to use the same approach as unix tail, which prefers inotify but falls back to polling when inotify isn't functioning? That way recompiling wouldn't be needed. In our case we're using fluent-bit because it comes packaged with the New Relic Infrastructure Agent and so we can't easily control the version of fluent-bit or how it's compiled.
