### ISSUE TITLE
Extract error level from logs when is has absent in jsonPayload

### ISSUE THREAD

**Issue by PDVJAM** [fluent/fluent-bit#2429]
**Is your feature request related to a problem? Please describe.**
We use fluent-bit with stackdriver output plugin. And sometimes there is no error level in json payload, but it is inside log record.
For example, look at [this](https://ibb.co/XpNX0rp) screenshot.

**Describe the solution you'd like**
It would be nice to extract it somehow and work with it as with error level from json payload.

**Describe alternatives you've considered**
Don't know but if there are any - would be interesting to hear.

**Comment by edsiper** [comment]
what's the context of use ? are you using the Stackdriver output plugin ? (note that each output plugin perform it own formatting)

**Comment by PDVJAM** [comment]
Ah, yes, we use Stackdriver output plugin. And most of logs can be easily sorted by severity, but some - and we can't change their log representation, coz they are external libraries - can't be.
