### ISSUE TITLE
flb_strptime.c misses **%L** Millisecond of the second

### ISSUE THREAD

**Issue by git001** [fluent/fluent-bit#2437]
**Is your feature request related to a problem? Please describe.**

In commit https://github.com/fluent/fluent-bit/commit/f142d932077e9833db25eeb2825e91dae8115935 is the  `fluent-bit/src/flb_strptime.c` now the default time parsers in fluent-bit.  
My timestamp look like this `06/Aug/2020:01:36:32.378` and I can use in fluentd this **time_format** `%d/%b/%Y:%H:%M:%S.%L`.

The **%L** is also described in https://docs.ruby-lang.org/en/2.6.0/Time.html#method-c-strptime

**Describe the solution you'd like**
It would be nice to have the **%L** in the `flb_strptime.c`

**Describe alternatives you've considered**
None.

**Additional context**
--

**Comment by edsiper** [comment]
Our parser wrapper on top of flb_strptime() supports %L

**Comment by git001** [comment]
@edsiper ah you mean that?  
https://github.com/fluent/fluent-bit/blob/master/src/flb_parser.c#L230

**Comment by edsiper** [comment]
Yes

**Comment by git001** [comment]
okay, thanks
