### ISSUE TITLE
How to get float value using out_influxdb and parser_regex?

### ISSUE THREAD

**Issue by majoyz** [fluent/fluent-bit#2462]
After using regex parser, the metrics would be like this: `"value"=>"float value"`(like `"value"=>"0.34"`). Then the value would be string in out_influxdb. 
```
name: ztest
fieldKey fieldType
-------- ---------
value    string
```

What can I do if I need a float value in influxdb? I think it should be like `"value"=>0.34`

**Comment by bluebike** [comment]
I think that by default  regex parser parses everything to string. 
After that out_influxdb assumes value being string value and escapes it. 
You should add something like  ```Types value:float``` (assuming that field is **value**) to you your parser conf. 

I think that parser **Types**  parameter is not very well documented (or I cannot find documentation).

**Comment by bluebike** [comment]
Note:   plugin out_infuxdb  could output integers  with as **123i**  ('i'-ending).  In that case InfluxDB would think value as 64-integer, which is useful with something like very big counters.    By default all numbers are understood as double by influxDB.

**Comment by majoyz** [comment]
> I think that by default regex parser parses everything to string.
> After that out_influxdb assumes value being string value and escapes it.
> You should add something like `Types value:float` (assuming that field is **value**) to you your parser conf.
> 
> I think that parser **Types** parameter is not very well documented (or I cannot find documentation).

Thanks for your help, it works. Yes, it can't be find in parser's document.
