### ISSUE TITLE
Support alpine musl

### ISSUE THREAD

**Issue by wenerme** [fluent/fluent-bit#2464]
Try to add fluent-bit to alpine repo by this [pr](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/11350)

**Is your feature request related to a problem? Please describe.**

Alpine build get this error

```
Error: Invalid coroutine stack size. Aborting
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I do found [Why there is no Fluent Bit Docker image based on Alpine Linux ?](https://docs.fluentbit.io/manual/installation/docker#why-there-is-no-fluent-bit-docker-image-based-on-alpine-linux), but I still think support alpine is a long term goal.

jemalloc are woking on the musl support, https://github.com/jemalloc/jemalloc/issues/1443 , I thinks if this can be solved, other problem can solve too.

**Comment by wenerme** [comment]
The default `-s, --coro_stack_size Set coroutines stack size in bytes (default: 3072)` will cause the error, but manually set `-s 4096` can start

**Comment by wenerme** [comment]
Build pass, and works, but some internal test failed, need help, build log and detail test log [here](https://gitlab.alpinelinux.org/wener/aports/-/jobs/185189#L2167)

failed tests

```
 The following tests FAILED:
 	  7 - flb-it-network (Failed)
 	 16 - flb-it-stream_processor (Failed)
```

the dmesg

```
[2858202.952603] flb-it-network[28842]: segfault at 0 ip 00007fc90523be35 sp 00007ffc4e982bb8 error 4 in ld-musl-x86_64.so.1[7fc9051ff000+47000]
[2858202.952616] Code: 05 89 45 00 4c 89 f7 e8 f3 e3 ff ff 5b 44 89 e0 5d 41 5c 41 5d 41 5e c3 64 48 8b 04 25 00 00 00 00 48 8b 80 88 00 00 00 89 ff <48> 8b 04 f8 c3 41 56 41 55 49 89 d5 41 54 55 48 89 f5 53 4
8 89 fb

[2858208.588460] traps: flb-it-stream_p[28876] trap invalid opcode ip:55b3924b0d58 sp:7ffd8de8bbe0 error:0 in flb-it-stream_processor[55b3924ae000+1c2000]
[2858208.591456] traps: flb-it-stream_p[29717] trap invalid opcode ip:55b3924b169d sp:7ffd8de8bb60 error:0 in flb-it-stream_processor[55b3924ae000+1c2000]
```

**Comment by ericonr** [comment]
The coroutine stack size happens due to https://github.com/fluent/fluent-bit/blob/5ffc991b71cd06cfa2f2f7a764e634af053776bd/src/fluent-bit.c#L1111 and https://github.com/fluent/fluent-bit/blob/5ffc991b71cd06cfa2f2f7a764e634af053776bd/include/fluent-bit/flb_coro.h#L68

musl defines `PTHREAD_STACK_MIN` to 2048, which means that the result of `PTHREAD_STACK_MIN * 3 / 2` is 3072, which is definitely smaller than what `getpagesize()` returns (4096 on most platforms). I'm not sure what the best solution here is, either their check for minimum stack size is bad, or the define is.

**Comment by wenerme** [comment]
build with static conf can resolve this, https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/fluent-bit/APKBUILD#L42 ,but some test will crash

**Comment by wenerme** [comment]
Still valid ?

**Comment by ericonr** [comment]
Still valid.

Having a bot close issues where maintainers haven't answered yet is a really unwelcoming experience.

**Comment by ericonr** [comment]
No maintainer has answered yet.

**Comment by edsiper** [comment]
It has been answered many times and documented here:

https://docs.fluentbit.io/manual/installation/docker#why-there-is-no-fluent-bit-docker-image-based-on-alpine-linux

**Comment by wenerme** [comment]
The Jemalloc are resolved in latest musl, other problems is not sure, but should be tracked

**Comment by wenerme** [comment]
Currently only tow test failed, maybe this is not that hard to solve ?

If you think this not matter, you can close now.

```
The following tests FAILED:
          7 - flb-it-network (Failed)
         20 - flb-it-stream_processor (Failed)
```

```
Test ipv6_client_server...                      [2021/06/29 15:55:04] [error] Error binding socket
[2021/06/29 15:55:04] [ warn] Cannot listen on ::1 port 41322
  Test interrupted by SIGSEGV.
FAILED: 1 of 2 unit tests has failed.
```

```
[21236.210243] flb-it-network[1513]: segfault at 0 ip 00007f556a125852 sp 00007ffe552459d8 error 4 in ld-musl-x86_64.so.1[7f556a0e7000+48000]
[21236.210248] Code: 2b ff ff 48 81 c4 88 00 00 00 44 89 e0 5b 5d 41 5c 41 5d 41 5e 41 5f c3 64 48 8b 04 25 00 00 00 00 48 8b 80 80 00 00 00 89 ff <48> 8b 04 f8 c3 41 56 41 55 49 89 d5 41 54 55 48 89 f5 53 48 89 fb
```

---

```
[21258.567468] traps: flb-it-stream_p[1740] trap invalid opcode ip:55d7425beffa sp:7ffcf2d2f490 error:0 in flb-it-stream_processor[55d7425bc000+214000]
[21258.570078] traps: flb-it-stream_p[1789] trap invalid opcode ip:55d7425bf933 sp:7ffcf2d2f410 error:0 in flb-it-stream_processor[55d7425bc000+214000]
```

**Comment by wenerme** [comment]
imo, I really want to use fluent bit to collect the log in containers, vms and hosts, my hosts and vms is also alpine, runs fine for years. fluent-bit should be more flex about the env, like log collect is very low level tasks.

Anyway, fluent bit is great, thanks for your work.

**Comment by ericonr** [comment]
@edsiper should I open a separate issue for https://github.com/fluent/fluent-bit/issues/2464#issuecomment-786191656, then? It's an actual issue and broken on platforms other than musl.

**Comment by edsiper** [comment]
> @edsiper should I open a separate issue for [#2464 (comment)](https://github.com/fluent/fluent-bit/issues/2464#issuecomment-786191656), then? It's an actual issue and broken on platforms other than musl.

Yes please, separate issue is better to discuss that specific problem

**Comment by edsiper** [comment]
> imo, I really want to use fluent bit to collect the log in containers, vms and hosts, my hosts and vms is also alpine, runs fine for years. fluent-bit should be more flex about the env, like log collect is very low level tasks.
> 
> Anyway, fluent bit is great, thanks for your work.

I understand, but the majority of our use cases have strong security requirements, not sure what's the status of Alpine but also jemalloc and Go shared libs integration is a must.

**Comment by wenerme** [comment]
@edsiper is there any test case for jemalloc and  Go shared libs or is there any related issues I can track ?

**Comment by wenerme** [comment]
I found the musl golang shared issues https://github.com/golang/go/issues/13492

**Comment by wenerme** [comment]
Close now, nothing can do here
