### ISSUE TITLE
 Usage of Ignore_Older with Multiline

### ISSUE THREAD

**Issue by vsinghal13** [fluent/fluent-bit#2466]
## Bug Report

**Describe the bug**
According to the docs, the `Ignore_older` property is only available when a Parser is specified:

```Ignores records which are older than this time in seconds. Supports m,h,d (minutes, hours, days) syntax. The default behavior is to read all records from specified files. Only available when a Parser is specified and it can parse the time of a record.```

Does this imply that Ignore_older will not work when you have Multiline turned on and Parser no longer works, as it is replaced by Parser_Firstline and Parser_N ? The comment does not explicitly state this, but it could be inferred from how it is worded. I also cannot get this to work, so I assume it is the case, but would like confirmation.

**To Reproduce**
- Steps to reproduce the problem:
Use `Ignore_Older` with `Multiline` On. 

**Expected behavior**
Expected the `Ignore_Older` config to work and drop data based on the config provided.

**Your Environment**
* Environment name and version (e.g. Kubernetes? What version?): K8s 1.15

**Additional context**
The issue here is what led to the above section in the docs, but I can't tell if it explicitly means it only works with Parser and not multiline. https://github.com/fluent/fluent-bit/issues/716#issuecomment-414460134

**Comment by frankreno** [comment]
Hi folks, can we get any update on this? cc @edsiper

**Comment by Adhira-Deogade** [comment]
Hey, any updates on the issue?

**Comment by frankreno** [comment]
Hi folks, can we get any update on this? cc @edsiper

**Comment by cheewai-bash** [comment]
fluent-bit v2.2.2

This works as described in documentation - `Ignore_Older` correctly filters out:
a) log files based on their last-modification timestamp
b) individual log record based on log timestamp

```
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    parser docker, cri
    Tag kube.*
    Ignore_Older 1d
```

But, when I replace `parser docker, cri` with `multiline.parser docker, cri`, (a) still works but not (b)
i.e. fluent-bit does not use `Ignore_Older` to filter individual log record.

In other words, `multiline.parser` unexpectedly impairs `Ignore_Older` functionality. 

Is this a bug or merely an undocumented feature?
