### ISSUE TITLE
[Bug] "Too many open files" (errno=24) || [Feature proposal] - Only tail logs younger than x seconds/hours/days

### ISSUE THREAD

**Issue by lacksfish** [fluent/fluent-bit#2474]
## Bug Report

**Describe the bug**

We have logs all piling up in one folder. Fluentbit tail eventually fails with the error "Too many open files" (errno=24)
We can not remove logs from this folder, but new ones will be constantly added. Once a new log exists, there will be no new logs lines written into the older log files.

**To Reproduce**

Possibly, create a bunch of log files (we have 8261), and tail all of them. It might fail beyond the 82XX files mark.

**Expected behavior**

Keep logging. But I guess a limit on the allowed max open file handles is preventing this. 
**Thus, i propose a config option for fluentbit tail parser to only tail files younger than x seconds/hours/days**

**Your Environment**

* Version used: I'm assuming 1.5, one of the latest versions for sure
I'm running fluentbit on a regular Windows Server 2016 x64

**Additional context**

We are simply logging .log files in a folder which has too many log files. We can not remove old ones - but the old ones will be never updated with new loglines once there is a fresher file. How can we make fluentbit only tail files fresher than a certain timedelta?

**Comment by jsubirat** [comment]
We have observed the exact same behavior on a Windows Server running Fluent Bit 1.5.4. In our case, Fluent Bit was able to start when the folder contained 7430 files to be tailed, but not when the folder contained 7524 files.

I would even add: wouldn't it be desirable to limit the amount of simultaneously opened files by the Fluent Bit `tail` plugin, via a configuration in the `SERVICE` section? The `tail` plugin should not attempt to open them all at once, but in chunks.

**Comment by lacksfish** [comment]
Not stale AFAIK

**Comment by jsubirat** [comment]
What about this other proposal:
> wouldn't it be desirable to limit the amount of simultaneously opened files by the Fluent Bit tail plugin, via a configuration in the SERVICE section? The tail plugin should not attempt to open them all at once, but in chunks.
