### ISSUE TITLE
log buffer: Restarting fluent-bit results in CRC32 errors

### ISSUE THREAD

**Issue by phiremande** [fluent/fluent-bit#2475]
## Bug Report

**Describe the bug**
If log buffering is configured and there are pending chunks (due to n/w issues), in this case, killing fluent-bit results in CRC32 errors.

**To Reproduce**

```
[2020/08/18 05:03:08] [debug] [storage] [cio file] invalid crc32 at 18004-1597751841.447180882.flb/<storage_path>/tcp.0/18004-1597751841.447180882.flb
[2020/08/18 05:03:08] [error] [storage] format check failed: tcp.0/18004-1597751841.447180882.flb
```
- Steps to reproduce the problem:
Configure log buffering and ensure that logs are buffered to disk by bringing down the connectivity to the server. We are using kafka rest proxy as the output plugin.
Once a few chunks are stored, restart the fluent-bit process.

**Expected behavior**
format check shouldn't fail.

**Screenshots**

**Your Environment**

* Version used: 1.5.3
* Configuration:
[SERVICE]
storage.path $CONF_FILE_PATH/storage
storage.sync normal
storage.checksum on
storage.backlog.mem_limit 10M

#tcp
[INPUT]
    Name tcp
    Listen      127.0.0.1
    Port        $IN_TCP_PORT
    Format      json
    Tag         <tag>

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Linux / Centos
* Filters and plugins:

**Additional context**
killed fluent-bit process using "kill -9 <pid>".

**Comment by edsiper** [comment]
are you able to replicate the problem using ```storage.sync full``` ?

**Comment by phiremande** [comment]
@edsiper , Yes, I am seeing it with storage.sync full too.

**Comment by phiremande** [comment]
@edsiper , this is happening with ext3 filesystem and not seen on ext4. Any suggestions on how to go about this?

**Comment by phiremande** [comment]
@edsiper, appreciate if you can provide some pointers.
