### ISSUE TITLE
Fluentbit output to elasticsearch is missing milliseconds on @timestamp

### ISSUE THREAD

**Issue by FarhadF** [fluent/fluent-bit#2476]
## Bug Report

**Describe the bug**

Fluentbit output to elasticsearch is missing milliseconds on @timestamp

config:
```
[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser json
    Reserve_Data True

[OUTPUT]
    Name es
    Match *
    Host XXX
    Logstash_Prefix my_prefix
    Logstash_Format On
    Type _doc
    Trace_Output On
```
Version: Fluent Bit v1.4.2

Example record(please note the 000 in @timestamp (this is from the trace output of es plugin):

```
{"@timestamp":"2020-08-19T09:39:29.000Z","level":"error","timestamp":"2020-08-19T09:39:29.996959864Z","message":"Failed to retrieve queue url"}
```

Actual log line from the application:
```
{"level":"error","timestamp":"2020-08-19T09:39:29.996959864Z","message":"Failed to retrieve queue url"}
```

**Comment by FarhadF** [comment]
Things I tried:
  - changing Flush to 0.5, still no milliseconds.
  - set Time_Key_Format
  - trying my config locally (just changed INPUT to tail to read from file) -> this works correctly 
```
{"@timestamp":"2020-08-19T11:47:06.540Z","level":"error","timestamp":"2020-08-19T09:57:29.996959864Z","message":"Failed to retrieve queue url"}
```

**Comment by FarhadF** [comment]
One workaround would be to parse application timestamp key in parser and replace @timestamp

**Comment by zihengCat** [comment]
@FarhadF Hi, check this PR https://github.com/fluent/fluent-bit/pull/2544 out.
