### ISSUE TITLE
Timestamp_Key in kafka output

### ISSUE THREAD

**Issue by dexter-hwang** [fluent/fluent-bit#2477]
in kafka output's config, `Timestamp_Key` must not be empty.

## disable Timestamp_Key

any solution of prevent from attach `Timestamp_Key`?
because, I don't want to change my original data.

like this
```
Timestamp_Add       Off
```

## nested key support

or, any solution of assign Timestamp_Key to nested field?

like this
```
Timestamp_Key       @metadata.@timestamp
Timestamp_Key       @metadata/@timestamp
```

**Comment by yongtang** [comment]
Added a PR #3050 for the support. In the PR a new option `Timestamp_Mode = on|off (default on)` has been added. With `off` the timestamp will be disabled.

**Comment by NikNikM** [comment]
In my case, I had already field timestamp (in the value) and this will override the @timestamp field (it doesn't appear). Btw. it would be great to have this change in _out_kafka_rest_ as well.
