### ISSUE TITLE
out_es: option for Elasticsearch 5.x basic authentication

### ISSUE THREAD

**Issue by bonczj** [fluent/fluent-bit#248]
Looking at the out_es documentation, I do not see where it would be possible to supply the HTTP basic authentication account information in the configuration file. Elasticsearch 5.x + Kibana require the use of their new X-Pack with includes authentication out of the box.

I compared this to the Fluentd out_es plugin, and in that plugin, it is possible to supply the ES username/password for HTTP basic authentication.

**Comment by edsiper** [comment]
thanks for this requirement.

Since this is pretty straightforward it will be implemented shortly.

**Comment by edsiper** [comment]
@bonczj 

I've just added HTTP Basic Auth support. The incoming v0.11.6 will contain this new feature, the options name are:

- http_user
- http_passwd

ref: d636e491e0b83540fc88546310aab1db23695ac9

**Comment by Globegitter** [comment]
@edsiper just getting started with fluent-bit and it would be great it the HTTP plugin would support basic auth as well. We currently have that set up  in our system so can't actually use it.

**Comment by edsiper** [comment]
@Globegitter please open it, it should be quickly to.implement.
