### ISSUE TITLE
out_kafka: auto convert float to integer

### ISSUE THREAD

**Issue by liweitianux** [fluent/fluent-bit#2482]
## Bug Report

**Describe the bug**
The `kafka` output plugin auto converts float numbers that don't have a fractional part (e.g., `2.0`) to integers (e.g., `2.0` get auto converted to `2` in the Kafka topic).  However, float numbers with a fractional part (e.g., `3.6`) are not affected.

**To Reproduce**
1. Use the following config `test.conf`
```
SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    name         dummy
    dummy        {"integer": 1, "float": 2.0, "float2": 3.60}

[OUTPUT]
    name         stdout
    match        *

[OUTPUT]
    Name             kafka
    Match            *
    Format           json
    Brokers          broker1:port,broker2:port,broker3:port
    Topics           default

    rdkafka.socket.keepalive.enable  true
    rdkafka.linger.ms                5000
    #rdkafka.retries                  2
    rdkafka.retry.backoff.ms         5000
    rdkafka.request.timeout.ms       30000
    rdkafka.request.required.acks    1
    rdkafka.log.connection.close     false
    rdkafka.security.protocol        ssl
    rdkafka.ssl.ca.location          ca.crt
    rdkafka.ssl.certificate.location host.crt
    rdkafka.ssl.key.location         host.key
```
2. Run `td-agent-bit -c test.conf`, the `stdout` output looks like:
```
[0] dummy.0: [1598013854.083880134, {"integer"=>1, "float"=>2.000000, "float2"=>3.600000}]
[0] dummy.0: [1598013855.083961213, {"integer"=>1, "float"=>2.000000, "float2"=>3.600000}]
[0] dummy.0: [1598013856.083911472, {"integer"=>1, "float"=>2.000000, "float2"=>3.600000}]
[0] dummy.0: [1598013857.083871363, {"integer"=>1, "float"=>2.000000, "float2"=>3.600000}]
```
3. Examine the messages in the Kafka topic `default`, looks like:
```
{"@timestamp":1598013953.083872,"integer":1,"float":2,"float2":3.6}
{"@timestamp":1598013954.084044,"integer":1,"float":2,"float2":3.6}
{"@timestamp":1598013955.083936,"integer":1,"float":2,"float2":3.6}
{"@timestamp":1598013959.083911,"integer":1,"float":2,"float2":3.6}
```
4. The float number `2.0` has been converted to an integer `2` by the `kafka` output plugin.

**Expected behavior**
The `kafka` output plugin should not change data types.

**Your Environment**
* Version used: 1.5.3 (official RPM package)
* Configuration: (see above)
* Operating System and version: CentOS 7.4 (64bit)

**Comment by liweitianux** [comment]
I was using Fluent Bit 1.3.11 (installed from the official RPM), which didn't have such an issue.

**Comment by jpaskhay** [comment]
It appears that #1439 is the root cause of this issue. This effects all output plugins when specifying JSON format.

@liweitianux If you change the `Format` to `json` in your `stdout` output (it defaults to `msgpack`), you should also see the issue there.

```bash
$ # Using a version prior to the referenced PR's change
$ docker run -it fluent/fluent-bit:1.4.3 /fluent-bit/bin/fluent-bit -i dummy -p Dummy='{"key": 2.0}' -o stdout -p format=json_lines -f 1
...
{"date":1599094819.903610,"key":2.000000}
```

```bash
$ # Using a version after the referenced PR's change
$ docker run -it fluent/fluent-bit:1.5 /fluent-bit/bin/fluent-bit -i dummy -p Dummy='{"key": 2.0}' -o stdout -p format=json_lines -f 1
...
{"date":1599095577.908472,"key":2}
```

You can even see the difference by just using `awk`:

```bash
$ # Using previous format
$ echo 2.0 | awk '{ printf("%f\n",$1) }'
2.000000
```
```bash
$ # Using new format
$ echo 2.0 | awk '{ printf("%.16g\n",$1) }'
2
```

**Comment by liweitianux** [comment]
@jpaskhay Cool. Good catch!

I've never know such a behavior of the `g` conversion.  So I just had a read about it; quoting from "C: A Reference Manual" (5ed):

> The `g` conversion begins the same as either the `f` or `e` conversions ....
> The converted value (whether by `f` or `e`) is then further modified by stripping off trailing zeros to the right of the decimal point.
> **If the result has no digits after the decimal point, the the decimal point is also removed.**
> If the `#` flag is present, this stripping of zeros and the decimal point does not occur.

So I think we may need to use `%#.16g` here. e.g.,

```sh
% echo 2.0 | awk '{ printf("%#.16g\n",$1) }'
2.000000000000000
```

Regards

**Comment by jpaskhay** [comment]
> So I think we may need to use `%#.16g` here. e.g.,
> 
> ```shell
> % echo 2.0 | awk '{ printf("%#.16g\n",$1) }'
> 2.000000000000000
> ```

I took a look at one of the JSON libraries Fluentd uses (Oj) to see how they handle it, and I like the way they explicitly handle the use case: https://github.com/ohler55/oj/blob/v3.10.13/ext/oj/dump_strict.c#L100-L101. Feels a little cleaner and could cut down on the extra bytes for all the 0's getting serialized in the string (it's not a lot, but could potentially be at scale).
