### ISSUE TITLE
Does all ouputs share the same buffer？

### ISSUE THREAD

**Issue by debu99** [fluent/fluent-bit#2490]
We use fluentbit to send multiple application logs to es index and s3 bucket, and we found out if one index has some issue and got rejected by Elasticsearch(this will cause the sending retries infinitely if don't want lose log and set the Retry_Limit to false), after some time, all outputs will stop ingest new logs, may I know how to avoid this?I don't want one index issue blocks all others.

**Comment by PettitWesley** [comment]
All outputs share the same buffer yes; though there is work underway to support per-output buffering closer to what Fluentd has.

Read the backpressure section of the docs: https://docs.fluentbit.io/manual/administration/backpressure
