### ISSUE TITLE
Do not use both warn and warning

### ISSUE THREAD

**Issue by LionelCons** [fluent/fluent-bit#2492]
As discussed in https://github.com/fluent/fluent-bit-docs/pull/342, Fluent Bit uses both [warn](https://github.com/fluent/fluent-bit/blob/master/src/flb_log.c#L180) and [warning](https://github.com/fluent/fluent-bit/blob/master/src/flb_config.c#L383) to specify log levels.

This is _very_ confusing.

Please use only one of these, consistently.

**Comment by edsiper** [comment]
docs updated, thanks.

**Comment by LionelCons** [comment]
The documentation has been updated but the code still uses both.

`warn` in `flb_log_get_level_str`: https://github.com/fluent/fluent-bit/blob/master/src/flb_log.c#L182

`warning` in `set_log_level`: https://github.com/fluent/fluent-bit/blob/master/src/flb_config.c#L393

It would be simpler to use the same string to mean warning throughout the configuration.

**Comment by edsiper** [comment]
oh I see.... 

to avoid breaking things I think is safer to allow both for now and encourage just one in the docs
