### ISSUE TITLE
Parsers example

### ISSUE THREAD

**Issue by Darkheir** [fluent/fluent-bit#250]
Hi, 

I would like to try fluent bit and I didn't find any documentation or example on how to use parsers.
It seems that the official documentation about it is not yet written so would it be possible to have an example on how to use it along with the available ones ?

**Comment by edsiper** [comment]
Docs will be updated shortly.

As a quick reference, parsers can be used by plugins who are aware of it, e.g: in_tail and in_stdin. A parser can be based on "json" or a "regular expressions", a default parsers file is provided in Fluent Bit:

https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf

In the meanwhile if you have specific questions about it usage, feel free to post them here.

**Comment by Darkheir** [comment]
I' having some troubles to make it work.

I have the following configuration

```
[SERVICE]
    Flush        5
    Log_Level    trace

[INPUT]
    Name        tail
    Path        /var/log/my.log


[OUTPUT]
    Name        es
    Match       *
    Host        elasticsearch
    Port        9200
    Index       fluentbit
```
When I launch fluent-bit the index is created in elastic so I guess the connection is okay. 

When I add a new log I can see this in fluent-bit:

> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log event
> [2017/05/01 12:09:29] [debug] [input tail.0] [mem buf] size = 387
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log read=374 lines=1
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log event
> [2017/05/01 12:09:29] [debug] [input tail.0] [mem buf] size = 813
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log read=413 lines=1
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log event
> [2017/05/01 12:09:29] [debug] [input tail.0] [mem buf] size = 1372
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log read=546 lines=1
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log event
> [2017/05/01 12:09:29] [debug] [input tail.0] [mem buf] size = 1828
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log read=443 lines=1
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log event
> [2017/05/01 12:09:29] [debug] [input tail.0] [mem buf] size = 2387
> [2017/05/01 12:09:29] [debug] [in_tail] file=/var/log/thiapp/json.log read=546 lines=1
> [2017/05/01 12:09:30] [debug] [in_tail] file=/var/log/thiapp/json.log event
> [2017/05/01 12:09:30] [debug] [input tail.0] [mem buf] size = 2757
> [2017/05/01 12:09:30] [debug] [in_tail] file=/var/log/thiapp/json.log read=357 lines=1
> [2017/05/01 12:09:32] [trace] [dyntag tail.0] 0x7f93dea0d0c0 tag=tail.0
> [2017/05/01 12:09:32] [trace] [task 0x7f93dec0d0e0] created (id=0)
> [2017/05/01 12:09:32] [debug] [task->buffer] worker_id=0
> [2017/05/01 12:09:32] [debug] [task] created task=0x7f93dec0d0e0 id=0 OK
> [2017/05/01 12:09:32] [trace] [thread 0x7f93dea0d120] created (custom data at 0x7f93dea0d140, size=64
> [2017/05/01 12:09:32] [trace] [upstream] connection in process
> [2017/05/01 12:09:32] [trace] [engine] resuming thread=0x7f93dea0d120
> [2017/05/01 12:09:32] [trace] [io] connection OK
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [net_write] trying 96 bytes
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [fd 24] write_async(2)=96 (96/96)
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [net_write] ret=96 total=96/96
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [net_write] trying 3153 bytes
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [fd 24] write_async(2)=3153 (3153/3153)
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [net_write] ret=3153 total=3153/3153
> [2017/05/01 12:09:32] [trace] [io thread=0x7f93dea0d120] [net_read] try up to 8191 bytes
> [2017/05/01 12:09:33] [trace] [engine] resuming thread=0x7f93dea0d120
> [2017/05/01 12:09:33] [trace] [io thread=0x7f93dea0d120] [net_read] ret=2879
> [2017/05/01 12:09:33] [debug] [out_es] HTTP Status=200
> [2017/05/01 12:09:33] [trace] [upstream] [fd=24] releasing connection 0x7f93de40d0e0
> [2017/05/01 12:09:33] [trace] [engine] [task event] task_id=0 thread_id=0 return=OK
> [2017/05/01 12:09:33] [trace] [thread] destroy thread=0x7f93dea0d120 data=0x7f93dea0d140
> [2017/05/01 12:09:33] [debug] [task] destroy task=0x7f93dec0d0e0 (task_id=0)
> [2017/05/01 12:09:33] [debug] [dyntag tail.0] 0x7f93dea0d0c0 destroy (tag=tail.0)

And in elasticsearch logs I only see one line:

> [2017-05-01T12:09:33,006][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

**Comment by Darkheir** [comment]
Thank you, I managed to use it !
