### ISSUE TITLE
Does fluent-bit forwarder supports require_ack_response

### ISSUE THREAD

**Issue by git001** [fluent/fluent-bit#251]
I haven't seen in the code that the forward plugin supports the feature require ack response

http://docs.fluentd.org/v0.12/articles/out_forward#requireackresponse

Do I have overseen it, does the msgpack supports this out of the box or is it just not yet implemented?

Please can you also answer the same question for <server> (at least one is required)

http://docs.fluentd.org/v0.12/articles/out_forward#ltservergt-at-least-one-is-required

**Comment by edsiper** [comment]
ack response is not implemented yet. But it will be done during 0.12 development (our current GIT master).

**Comment by git001** [comment]
coole thanks

**Comment by edsiper** [comment]
let's keep this ticket open until it get fixed :)

**Comment by git001** [comment]
as you wish ;-)

**Comment by Misterhex** [comment]
is this implemented yet? doesn't see it in 0.12 release notes. thanks.

**Comment by jinhyukchang** [comment]
@edsiper Do you know if this has been implemented?

**Comment by edsiper** [comment]
already implemented, please refer to the docs:

https://docs.fluentbit.io/manual/output/forward
