### ISSUE TITLE
Dynamic creation of Elasticsearch indexes

### ISSUE THREAD

**Issue by marklinders-planon** [fluent/fluent-bit#2514]
**Is your feature request related to a problem? Please describe.**
I am not able to dynamically create Elasticsearch indexes based on the Kubernetes namespace name. Because in our setup the namespace name is customer separated and from a platform perspective we are not aware of the customers that get created, we cannot pre-provision the indexes.

**Describe the solution you'd like**
To be able to use the Kubernetes namespaces as an Elasticsearch index name dynamically.

**Describe alternatives you've considered**
We currently have to run multiple fluentd pods just to do the dynamic index creation for us. Because all logs have to go through the fluentd pods they are becoming a bottleneck.

**Additional context**
Ideally it would be as simple as using a variable for the Elasticsearch index name, that gets substituted with the kubernetes namespace name. Perhaps via Tags.

**Comment by GitSnafu** [comment]
I second this request. We have many services that output more than one log stream; regular application logs and ad hoc JSON document logs (typically trace logs of particularly important categories of data). The JSON document log events always specify a custom elasticsearch index field. We are currently logging to file and logstash then puts the logs into the relevant elasticsearch index. As we migrate these services into kubernetes we'd like to avoid logging to file. My preference would be to output all log streams to stdout, then configure fluent-bit to tag the streams appropriately (app_log and json_log, for example). The app_log would be pushed to an elasticsearch output with a pre-defined index (defined by the cluster environment) while the json_log would go to another elasticsearch output configured to use the index specified in the log event, i.e. like the target_index_key in the fluentd plugin (https://github.com/uken/fluent-plugin-elasticsearch#target_index_key).

Without this we would have to either forward the json_log tagged events to fluentd to benefit from its elasticsearch plugin (target_index_key, as mentioned above) but that means we'll have to run both fluent-bit and fluentd. Alternatively, we don't use fluent-bit at all, but it seems to me fluent-bit is the newer and preferred option so I'd like to use that if I can. With the proposed change, we could get rid of fluentd altogether in our cluster. (At least that's my understanding, but I'm only just starting to dip my toes into this so I might be missing a more obvious solution.)

**Comment by marklinders-planon** [comment]
Still on my wishlist so we can finally remove fluentd out of our deployment.

**Comment by gvfnix** [comment]
Hi. Got my hand up for this issue. Logstash_Prefix_Key is not always suitable. Also, it does not allow to drop the key before indexing the record.

**Comment by kfantonio** [comment]
Logstash_Prefix_Key is not totally usefull if we can't drop the date suffix entirely. In other words, we need a field to set the index name. Or the 'Index' field has to be dynamic (accessors). This is obvious for anyone using fluentd and fluentbit intensively. This feature is missing in FluentBit.

**Comment by ligol** [comment]
Hello, is there anything planned for this feature, it would allow pushing log into ES DataStream with dynamic index name got from the log. 
This could be working like the Logstash_Prefix_Key but for Index

**Comment by sparrowt** [comment]
There are 2 workarounds AFAICS:
1. Use the `opensearch` output plugin instead, which supports record accessors in `index`
2. With the `elasticsearch` output plugin if you set `logstash_dateformat` to a fixed string (no strftime placeholders) then the date is not appended - this only works if you're happy to have a non-empty fixed suffix appended to all your index names (after the dynamic field value - if not, see 1. above)

Both are described with examples here: https://github.com/fluent/fluent-bit/issues/8878#issuecomment-2690701788
