### ISSUE TITLE
Support bearer_token_file option on HTTP output plugin

### ISSUE THREAD

**Issue by rakelkar** [fluent/fluent-bit#2517]
**Describe the solution you'd like**
Would be great if the HTTP plugin supported reading a file to retrieve the token to use for the HTTP auth header. This is similar to the `bearer_token_file` option on [Prometheus remote write config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). 

**Describe alternatives you've considered**
The plugin does support headers as part of its configuration, however as noted in #365 since dynamic config reload is not supported, workarounds are required to refresh the token.

**Comment by ecusnir** [comment]
The code includes `bearer_token_file` [parameter](https://github.com/grafana/loki/blob/master/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L45-L46).

Unfortunately, it is only [read once](https://github.com/grafana/loki/blob/master/cmd/fluentd/lib/fluent/plugin/out_loki.rb#L116), unlike prometheus that [uses a round tripper to update the token](https://github.com/grafana/loki/blob/fd451d97f4d6a51ea1f67c1959def077ffb78ee4/vendor/github.com/prometheus/common/config/http_config.go#L189).
