### ISSUE TITLE
Lua filter either truncates or corrupts Fluent Bit's nanosecond-resolution timestamp

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit#2519]
## Bug Report

**Describe the bug**
I am trying to inject Fluent Bit's nanosecond-resolution timestamp into the log itself. As per [the docs](https://docs.fluentbit.io/manual/pipeline/filters/lua), the recommended approach is to use a Lua filter -- unfortunately, in practice, Lua either loses some of the resolution (drops some of the decimal places) or appears to actually corrupt the timestamp (i.e. it keeps all the decimal places, but the digits are different).

**To Reproduce**

- Lua Filter Config:
```
function injectTimestamp(tag, timestamp, record)
    new_record = record
    
    -- Line 1
    new_record["epoch_timestamp"] = timestamp

    -- Line 2
    new_record["epoch_timestamp_str"] = tostring(timestamp)

    -- Line 3
    new_record["epoch_timestamp_str_formatted"] = string.format("%.9f", timestamp)

    -- Line 4: Replacing timestamp with itself should imply no actual change in timestamp. Thus, this should be exactly the same as returning a code of 2.
    -- return 1, timestamp, new_record

    return 2, timestamp, new_record
end
```
- Example log message if applicable:
```
{"time":"2020-09-01T01:41:43.057155568Z", "log":"My app container log", "stream":"stdout",}
```
Note that the original log time (`2020-09-01T01:41:43.057155568Z`) is equivalent to the following timestamp in epoch format: `1598924503.057155568`

- Steps to reproduce the problem:
Create a simple Fluent Bit config that tails Kubernetes container logs (`/var/log/containers/*.log`), applies the above Lua filter, and then prints the log to stdout. Deploy Fluent Bit on a Kubernetes cluster as a daemonset.

**Expected behavior**
In the logs of the Fluent Bit daemonset, I expect to see the following log (formatted for clarity):
```
kube.var.log.containers.app.log 
[
  1598924503.057155568, 
  {
    "time"=>"2020-09-01T01:41:43.057155568Z", 
    "epoch_timestamp"=>1598924503.057155568, 
    "epoch_timestamp_str"=>"1598924503.057155568", 
    "epoch_timestamp_str_formatted"=>"1598924503.057155568", 
    "log"=>"My app container log","stream"=>"stdout"
  }
]
```
(i.e. All the timestamps, including Fluent Bit's timestamp, should be the same value as the log time (but in epoch format), and should contain all 9 decimal places).

Instead, this is the log I actually see:
```
kube.var.log.containers.app.log 
[
  1598924503.057155568, 
  {
    "time"=>"2020-09-01T01:41:43.057155568Z", 
    "epoch_timestamp"=>1598924503.057156, 
    "epoch_timestamp_str"=>"1598924503.0572", 
    "epoch_timestamp_str_formatted"=>"1598924503.057155609", 
    "log"=>"My app container log","stream"=>"stdout"
  }
]
```

Specifically, the actual log has the following problems (corresponding to the numbering in the comments of the Lua filter):
1. epoch_timestamp: Last 3 decimal places are lost
2. epoch_timestamp_str: Last 5 decimal places are lost
3. epoch_timestamp_str_formatted: No decimal places are lost, but the last 3 digits do NOT match the original timestamp -- unclear how they were generated. Appears as if the last 3 digits of the original timestamp were corrupted.

4. In addition, there appears to be a related problem with the Lua filter's _return_ statement.  
In theory, both of the following _return_ statements are equivalent, and should behave identically:
- 
```
-- Do not modify the Fluent Bit timestamp
return 2, timestamp, new_record
```
-
```
-- Replace the Fluent Bit timestamp with itself
return 1, timestamp, new_record
```

But, in practice:
- If I use the first _return_ statement, it behaves as expected -- i.e. in the resulting log, the Fluent Bit timestamp (`1598924503.057155568`) has the same 9 decimal digits as the original log time (`2020-09-01T01:41:43.057155568Z`).
- If I were to use the second _return_ statement, it would NOT behave as expected  -- i.e. in the resulting log, the Fluent Bit timestamp (eg. `1598934178.153782367`) does NOT always have the same 9 decimal digits as the original log time (eg. `2020-09-01T04:22:58.153782464Z`).

**Your Environment**
* Configuration: (see Lua filter config above)
* Environment name and version:
   - Kubernetes
   - fluent-bit Docker image: `1.5.2-debug`
* Filters and plugins: 
   - Input tail plugin
   - Docker parser
   - Lua filter
   - Output stdout plugin

**Additional context**
If this is not a bug, and is merely a user error, please let me know what I'm doing wrong.

**Comment by edsiper** [comment]
thanks for raising this issue. 

I have pushed an enhancement that will be available in Fluent Bit v1.6. Please check the notes in this commit: 1204440746c6e38671407466591711746c07465e

**Comment by pranavmarla** [comment]
Thank you @edsiper . Do you happen to have any documentation/examples on how to make use of your new enhancement?

**Comment by edsiper** [comment]
@pranavmarla not yet, it will be available as 1.6 release in a week or so.

the timestamp field is now a lua table with two keys: 

```
  ['sec']  => timestamp seconds
  ['nsec'] => timestamp nanoseconds
```

just use/adjust that table content if required.

**Comment by edsiper** [comment]
ah, and enable ```time_as_table``` option

**Comment by pranavmarla** [comment]
Great, thanks!
