### ISSUE TITLE
Error: Configuration file contains format errors. Aborting

### ISSUE THREAD

**Issue by krithiga90** [fluent/fluent-bit#252]
Fluentbit is complaining about erroneous configuration. Even the default fluent-bit configuration provided is giving the same error. Error details:
Fluent-Bit v0.11.4
Copyright (C) Treasure Data

Invalid configuration value at INPUT.Name
Error: Configuration file contains format errors. Aborting

Fluent bit configuration file content:

[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.
    Log_Level    info

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File parsers.conf

[INPUT]
    Name   tail
    Path   /Users/Documents/config/log/*

[OUTPUT]
    Name   forward
    Host   0.0.0.0
    Port   24224
    Match  *

Please help me out.

**Comment by edsiper** [comment]
Make sure sections.content (key values) are indented (usually 4 spaces.from left), e.g

```
[INPUT]
    Name tail
    Path /Users/Documents/config/log/*
```

For more details you can learn here about the schema:

http://fluentbit.io/documentation/0.11/configuration/schema.html

**Comment by krithiga90** [comment]
@edsiper We have verified the indentation as mentioned in the docs. The key is preceded by 4 spaces. I believe no specific conditions apply for spaces between key and value?  Is there someway we could debug to find out what is the issue here?
<img width="669" alt="screenshot at may 08 10-37-27" src="https://cloud.githubusercontent.com/assets/20185171/25790921/6068b2b0-33da-11e7-9d9a-d02f6914f09e.png">

**Comment by edsiper** [comment]
Looks like is related to the blank space "before" every section, lines: 6, 11, 24 and 32.

**Comment by krithiga90** [comment]
@edsiper No even removing spaces dint resolve the issue. Do you have any tool which could validate the fluentbit configuration file?
<img width="722" alt="screenshot at may 09 10-58-14" src="https://cloud.githubusercontent.com/assets/20185171/25836725/c104751a-34a6-11e7-988c-f399520c97b9.png">

**Comment by edsiper** [comment]
Please download (no copy paste) and test this new file:

http://edsiper.linuxchile.cl/test.conf

note: your Output "host" needs to be an IP address, not "0.0.0.0"

**Comment by krithiga90** [comment]
@edsiper I tried the same file to start up fluent bit. Getting same error.
bin/fluent-bit -c test.conf
Invalid configuration value at INPUT.Name
Error: Configuration file contains format errors. Aborting

**Comment by nokute78** [comment]
@krithiga90 Hi. What is OS are you using?
in_tail is supported only for Linux now.

**Comment by edsiper** [comment]
@nokute78 thanks for catching that.

@krithiga90 there is a small bug where if a plugin is not found, the error message is wrong. This have been fixed in https://github.com/fluent/fluent-bit/commit/c1689b75e2f885c1cec8fa71c24cbed88ba491eb and will be part of the next releases.

Closing for now.

**Comment by dsoria** [comment]
hi, my error 

Fluent Bit v1.0.4
Copyright (C) Treasure Data

Error: Could not open configuration file. Aborting

**Comment by mrsiejas** [comment]
Validating config files has been added and is available using `-D` or `--dry-run` flags.

```
fluent-bit -i dummy -c validate_fluentbit.conf -D                                                                                                                                                                               ✔
Fluent Bit v1.7.4
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

configuration test is successful
```

**Comment by CodeSammich** [comment]
For future Googlers, I had an issue similar with:

> Configuration file contains errors. Aborting

Turns out my "Parsers_File" field under [SERVICE] was misnamed. I used fluent-bit.cfg instead of fluent-bit.conf (depending on the file name in the directory).
