### ISSUE TITLE
Kubernetes metadata no longer present in logs when upgrading beyond 1.5.0.

### ISSUE THREAD

**Issue by jonathanjuursema** [fluent/fluent-bit#2522]
## Bug Report
I'm not absolute positive this is a bug, it might very well be a configuration issue on our side. Any help in troubleshooting would be immensely helpful.

**Describe the issue**
We're using fluentbit as part of [aws-for-fluentbit](https://github.com/aws/aws-for-fluent-bit) in an EKS cluster on AWS. Upgrading from aws-for-fluentbit 2.3.1 (fluentbit 1.4.2) to 2.6.1 (fluentbit 1.5.2) leaves us without Kubernetes metadata in our logs on CloudWatch and ElasticSearch.

**To Reproduce**
We're using the following configuration:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File  /fluent-bit/etc/parsers.conf
    
    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        crio
        Tag           kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines   On

    [FILTER]
        Name   kubernetes
        Match  kube.*

    [FILTER]
        Name nest
        Match *
        Operation lift
        Nested_under kubernetes
        Prefix_with kubernetes_

    [FILTER]
        Name record_modifier
        Match *
        Remove_key kubernetes_container_name
        Remove_key kubernetes_docker_id

    [OUTPUT]
        Name cloudwatch
        Match *
        region eu-west-1
        log_group_name /applications/eks-fluentbit/{{ eks.name }}
        log_stream_prefix fluentbit-
        auto_create_group false
  parsers.conf: |
    [PARSER]
        # http://rubular.com/r/izM6olvshn
        Name crio
        Format Regex
        Regex /^(?<time>.+)\b\ (?<stream>stdout|stderr)\ (?<partialflag>F|P)\b\ (?<log>.*)$/
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
...
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: kube-system
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      serviceAccountName: fluentbit-serviceaccount
      containers:
        - name: aws-for-fluent-bit
          image: amazon/aws-for-fluent-bit:VERSION
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cloudwatch-credentials
                  key: accesskeyid
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-cloudwatch-credentials
                  key: secretaccesskey
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: mnt
              mountPath: /mnt
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: mnt
          hostPath:
            path: /mnt
```

This is a configuration that we've been using for some time, unfortunately I'm not the one who created this configuration.

When we take 2.3.1 (fluentbit 1.4.2) for VERSION, we've got log messages like this:
```json
{
    "kubernetes_container_name": "kube-proxy",
    "kubernetes_docker_id": "70d7b94397f621c557f42239319bb4e8e7bea4a651be2eadb9b115edd15612a6",
    "kubernetes_namespace_name": "kube-system",
    "kubernetes_pod_name": "kube-proxy-qm5vx",
    "log": "{\"log\":\"I0903 08:12:19.006415       1 proxier.go:793] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-03T08:12:19.00654917Z\"}"
}
```

After changing VERSION to 2.6.1 (fluentbit 1.5.2) we start seeing log messages like this:
```json
{"log":"{\"log\":\"I0903 07:59:18.193128       1 proxier.go:793] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-03T07:59:18.193358872Z\"}"}
```

Note the missing kubernetes_* fields. Reverting back to the old version also means we get our kubernetes_* fields back.

I've tried updating the Kubernetes filter according to the installation manual [here](https://docs.fluentbit.io/manual/installation/kubernetes):
```
    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_URL         https://kubernetes.default.svc:443
        Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix  kube.var.log.containers.
        Merge_Log        On
        Merge_Log_Key    log_processed
```

Which yields the following log syntax:
```json
{"log":"{\"log\":\"I0903 10:13:52.654444       1 main.go:72] Initializing vpc-admission-webhook version 0.2.3.\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-03T10:13:52.655445952Z\"}","log_processed":{"log":"I0903 10:13:52.654444       1 main.go:72] Initializing vpc-admission-webhook version 0.2.3.","stream":"stderr","time":"2020-09-03T10:13:52.655445952Z"}}
```

**Your Environment**
* Environment name and version (e.g. Kubernetes? What version?): AWS EKS 1.16
* Server type and version: AWS EC2 Nodes
* Operating System and version: AMI based on "EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.16.13, docker:19.03.6ce-4.amzn2)"
* Filters and plugins: [aws-for-fluentbit](https://github.com/aws/aws-for-fluent-bit)

**Additional context**
I'm looking for guidance regarding troubleshooting this issue and preferably getting our output as close as possible to the early log output:
```json
{
    "kubernetes_container_name": "kube-proxy",
    "kubernetes_docker_id": "70d7b94397f621c557f42239319bb4e8e7bea4a651be2eadb9b115edd15612a6",
    "kubernetes_namespace_name": "kube-system",
    "kubernetes_pod_name": "kube-proxy-qm5vx",
    "log": "{\"log\":\"I0903 08:12:19.006415       1 proxier.go:793] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-03T08:12:19.00654917Z\"}"
}
```
I'm not very familiar with fluentbit, so any guidance would be greatly appreciated!

**Comment by PettitWesley** [comment]
@jonathanjuursema Not certain of the cause of this... it is suspicious that the exact same config works in a previous version.

I suggest testing the config by isolating portions of it (strip it down to just the input and the output, see what you get, and then keep adding plugins/configs back in). That might illuminate some insights.

I also want to suggest that you should try the new `cloudwatch_logs` plugin which was released in the core of Fluent Bit in 1.5 (once you/we get 1.5 working and you can update). It has a slightly reduced memory and CPU footprint, and supports reading and sending logs at a much higher throughput.

**Comment by jonathanjuursema** [comment]
@PettitWesley thanks for getting back! I've tried to minimize the config as you requested. In the config of my original message, I've changed the config map as follows:

```
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File  /fluent-bit/etc/parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            crio

    [FILTER]
        Name          kubernetes
        Match         kube.*

    [OUTPUT]
        Name        es
        Match       *
        Host        es-endpoint
        Port        443
        Index       fluent-bit
        Type        doc
        AWS_Auth    On
        AWS_Region  eu-west-1
        tls         On

  parsers.conf: |
    [PARSER]
        # http://rubular.com/r/izM6olvshn
        Name          crio
        Format        Regex
        Regex         /^(?<time>.+)\b\ (?<stream>stdout|stderr)\ (?<partialflag>F|P)\b\ (?<log>.*)$/
        Time_Key      time
        Time_Format   %Y-%m-%dT%H:%M:%S.%L
        Time_Keep     On
```

With the container version `2.3.1` this results in the following documents in ElasticSearch:
```json
{
  "_index": "fluent-bit",
  "_type": "doc",
  "_id": "RSnfWHQBt7OFHWRhmqCw",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-09-04T11:27:58.728Z",
    "log": "{\"log\":\"I0904 11:27:58.728030       1 reflector.go:383] k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:246: Watch close - *v1.Node total 14 items received\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-04T11:27:58.728215885Z\"}",
    "kubernetes_pod_name": "cluster-autoscaler-758b4846b7-mx5v7",
    "kubernetes_namespace_name": "kube-system",
    "kubernetes_container_name": "cluster-autoscaler",
    "kubernetes_docker_id": "839998ab05e8cfae1a5ce78eaf8e6354430fb7562974d4e3649e53a7ebe8a64d"
  },
  "fields": {
    "@timestamp": [
      "2020-09-04T11:27:58.728Z"
    ]
  },
  "sort": [
    1599218878728
  ]
}
```

When upgrading to `latest`, these documents are submitted:
```json
{
  "_index": "fluent-bit",
  "_type": "doc",
  "_id": "Wyr0WHQBt7OFHWRhVB0e",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-09-04T11:50:37.497Z",
    "log": "{\"log\":\"I0904 11:50:37.496969       1 reflector.go:158] Listing and watching *v1.StorageClass from k8s.io/client-go/informers/factory.go:134\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-04T11:50:37.497114415Z\"}"
  },
  "fields": {
    "@timestamp": [
      "2020-09-04T11:50:37.497Z"
    ]
  },
  "sort": [
    1599220237497
  ]
}
```

For good measure, I also removed the Kubernetes filter to make sure the metadata was indeed coming from that filter.
`2.3.1`
```json
{
  "_index": "fluent-bit",
  "_type": "doc",
  "_id": "TqkAWXQBd4xu_Dm8cmNH",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-09-04T12:03:50.474Z",
    "log": "{\"log\":\"I0904 12:03:50.474313       1 pre_filtering_processor.go:66] Skipping ip-10-34-40-26.eu-west-1.compute.internal - node group min size reached\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-04T12:03:50.474394606Z\"}"
  },
  "fields": {
    "@timestamp": [
      "2020-09-04T12:03:50.474Z"
    ]
  },
  "sort": [
    1599221030474
  ]
}
```
`latest `
```json
{
  "_index": "fluent-bit",
  "_type": "doc",
  "_id": "qyr7WHQBt7OFHWRhMSHu",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-09-04T11:58:09.054Z",
    "log": "{\"log\":\"I0904 11:58:09.053923       1 scale_up.go:270] Pod default/windows-server-iis-7cff879775-vqssz is unschedulable\\n\",\"stream\":\"stderr\",\"time\":\"2020-09-04T11:58:09.054190862Z\"}"
  },
  "fields": {
    "@timestamp": [
      "2020-09-04T11:58:09.054Z"
    ]
  },
  "sort": [
    1599220689054
  ]
}
```

If there's anything you can say about whether or not this could be a bug, that'd be really helpful. If there's additional troubleshooting I can do, please do let me know.

Thanks!

**Comment by PettitWesley** [comment]
@jonathanjuursema the only thing I see which is interesting about your config is that the kubernetes filter lacks many of the options which I normally see: https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/output/elasticsearch/fluent-bit-configmap.yaml

The fact that this stopped working when you upgraded is odd and does make it seem like its a bug... on the other hand... 1.5.x has been out for a while and I am not aware of widespread complaints, which would be expected if there was a bug.

**Comment by jonathanjuursema** [comment]
@PettitWesley regarding the options you normally see: the Kube_* options anyway are, in the file you linked and in the documentation, explicitly set to the default value as far as I can make up from the documentation itself. This is not applicable to the Merge_* and K8S-Logging* options.

For our use-case, we will stay on fluentbit 1.4.2 for now and will take some time in the near future to spend more effort in getting the Kubernetes metadata to work.

In the mean time, is there anything I can do to help assess whether or not this is a bug?

**Comment by osela** [comment]
@jonathanjuursema we also had an issue with missing k8s metadata some time ago and the solution was setting the filter's `Buffer_Size` field to a much higher value (1MB). It's possible your k8s resources are big and don't fit in the default 32kb.

**Comment by jonathanjuursema** [comment]
@osela thanks for the suggestion!

I've tried the following filter config:
```
    [FILTER]
        Name          kubernetes
        Match         kube.*
        Buffer_Size   0
```

Versus what we were using:
```
    [FILTER]
        Name          kubernetes
        Match         kube.*
```

In both fluentbit `1.4.2` and `1.5.2` this made no difference in our configuration. In the old version the kubernetes information was present, in the newer version the metadata disappeared. :(

**Comment by jonathanjuursema** [comment]
We've spent some more time on this issue and we think we've identified the cause.

We've had a misconfiguration in the Kubernetes filter with regards to the Kubernetes filter `Kube_URL` parameter and the `automountServiceAccountToken` setting in the ServiceAccount, which resulted in fluentbit being unable to connect to the Kubernetes control plane for additional information about pods.

In `1.4.2`, the filter would still append the information it could get without accessing the control plane (pod name, namespace, container name and container ID) and just not append the rest (pod ID, labels and annotations).

In `1.5.2`, it looks like the filter will now now longer append these "basic" properties of the connection to the control plane fails, even though the control plane connection is not necessary for these "basic" properties.

I'm not sure if this should be considered a bug or intended behaviour, so I'll leave this issue open for now. :)

But for us, everything now works after correctly setting the Kube_URL and `automountServiceAccountToken` setting!

**Comment by nipuna-perera** [comment]
I am having this same issue! I am on EKS 1.17 and I am using the non amazon fluentbit version 1.7.1 to push logs to Splunk HEC. @jonathanjuursema I am assuming the default Kube_URL does not work for EKS? How do I figure out the correct Kube_URL for my cluster?

**Comment by jonathanjuursema** [comment]
Hey @nipuna-perera! The value for Kube_URL you're looking for can be found in the [AWS EKS web console](https://eu-west-1.console.aws.amazon.com/eks/home). You want the `API server endpoint` of your cluster, under "Configuration" > "Details".

**Comment by nipuna-perera** [comment]
@jonathanjuursema thank you for the response but that did not work for me. When I put that url from the AWS console, I got 'cannot connect to API' on fluentbit logs. For me, it's a curious situation where the kube metadata is actually available *only* for fluentbit container logs. No other container has any kube metadata in them. I removed everything and stripped my config to just the kube filter and I still don't see the metadata.

**Comment by PettitWesley** [comment]
@nipuna-perera Have you given your fluent bit pod proper permissions to call the API server and get metadata?

**Comment by nipuna-perera** [comment]
@PettitWesley , thanks for the question and this got me thinking. We have restrictions at an enterprise level so we can't create cluster roles and cluster role bindings. So what was happening was my role and rolebinding did not give the fluentbit SA access to read pods in other namespaces. Do you see a way around having to create clusterroles? Fluentbit should at a minimum parse the tag to get certain metadata even if it doesn't have access to the pods.

pod_name
container_name
docker_id
namespace_name

can all be derived just by the tag. (I have done so for my setup with LUA)

**Comment by PettitWesley** [comment]
@nipuna-perera Yeah the filter should be able to do that, I am not sure if it does though: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes

The logic may have been built to assume it can always call the API server and fail if it doesn't.

Unfortunately I am not very knowledgable with k8s, so I do not know a workaround here. We recently added a new option (which will be released soon) to tell fluent bit to get metadata from the kubelet instead of the API server. But I think that still requires a role to grant access to the kubelet...

**Comment by AndrewGrachov** [comment]
Can confirm lack of metadata. Downgraded to 2.3.1 image and everything works

**Comment by TimSin** [comment]
I'm having the same issue as the original reporter, and my configuration is almost identical too. Metadata is present when using version 1.4.2, but not in any later versions.

The k8s cluster is running on EKS, and RBAC is set up correctly. I've tried altering the API endpoint as per the suggestion above, but that has made no difference. The `Buffer_Size` config option has no impact either.

**Comment by TimSin** [comment]
After some further investigation it was apparent that my role mappings were not functioning as expected. Running the command `kubectl auth can-i list pods --as=system:serviceaccount:elastic-logs:fluent-bit` indicated that there was an access issue to the k8s API from the daemon set. Deleting and recreating the `ClusterRoleBinding` element of the installation fixed things and metadata is being transferred with the latest version.

**Comment by da-head0** [comment]
@TimSin Can I ask how did you recreating `ClusterRoleBinding`?
which configuration did you change?

**Comment by TimSin** [comment]
@da-head0 I removed the original `ClusterRoleBinding` and applied the manifests again with `kubectl apply -f ....`. In my case there was an issue with the namespace being incorrect, so it couldn't bind the role.
