### ISSUE TITLE
Failing to find files in missing folders in tail input should be considered as errors

### ISSUE THREAD

**Issue by viacheslave** [fluent/fluent-bit#2526]
**Is your feature request related to a problem? Please describe.**
The problem:
Fluent-bit reports errors and warnings when log files (are directories) are not there. The messages come up every `Refresh_Interval` which clutter up fluent-bit logs (we have a rich configuration with a lot of such path patterns).
Logs at `/logs/service/*/requests/*` may not be there a the moment, but may arrive there later. 
It's not a permissions issue - there are no objects at all.

fluent-bit v1.5.4 in kubernetes cluster on linux node

The logs I'm getting:
```
[2020/09/04 10:23:02] [ warn] [input:tail:tail.1] error scanning path: /logs/service/*/requests/*
[2020/09/04 10:23:02] [error] [input:tail:tail.1] read error, check permissions: /logs/service/*/requests/*
```

Part of my config:
```
[INPUT]
      Name tail
      Tag service-requests
      Parser json_parser
      Path /logs/service/*/requests/*
      Ignore_Older 5m
      Refresh_Interval 60
      Buffer_Max_Size 2048k
      storage.type  filesystem
      db /db/service-webrequests.db
```

**Describe the solution you'd like**
Missing input content should not be treated as errors. Probably warnings as OK.

**Describe alternatives you've considered**
A flag of an option not to treat this case as errors or warnings.

**Comment by viacheslave** [comment]
This is somewhat resembles [#525](https://github.com/fluent/fluent-bit/issues/525)

**Comment by agup006** [comment]
@pwhelan @patrick-stephens curious if this would be an easy log level fix, adding as I recall we did some similar changes earlier on this.

**Comment by patrick-stephens** [comment]
Yeah probably, really it would be nice to decrement the level after the first report -it's very useful to know when you've messed up your permissions (there are plenty of other issues raised in the past that boil down to that). I think a good halfway house may be we drop to warning level?
