### ISSUE TITLE
Reachability of kafka-rest proxy via custom path

### ISSUE THREAD

**Issue by phiremande** [fluent/fluent-bit#2528]
**Is your feature request related to a problem? Please describe.**
If there exists a load balancer in front of the kafk-rest proxy and strips paths the kafka-rest proxy cannot be reached due to fixed URL path.

**Describe the solution you'd like**
Provide a configuration parameter for appending URL path.

**Describe alternatives you've considered**
None.

**Additional context**
kafka-rest proxy sits behind a load balancer which exposes different paths and strips the prefixed path.

kafka-rest output plugin assumes that the path is always "/topics".
```
snprintf(ctx->uri, sizeof(ctx->uri) - 1, "/topics/%s", ctx->topic);
```

**Comment by zsoltkacsandi** [comment]
If it is still actual, there is an undocumented Url_Path parameter for the kafka-rest-proxy output:

https://github.com/fluent/fluent-bit-docs/pull/1203
