### ISSUE TITLE
Add Trend Micro logo to Fluent Bit users

### ISSUE THREAD

**Issue by zihengCat** [fluent/fluent-bit#2535]
Hi @edsiper and Fluent Bit core dev team,

Thanks for developing such a great tool.
[Trend Micro](https://www.trendmicro.com/en_us/business.html) use `fluent-bit` as our new logs collection solution. We marvel at its high performance and flexibility. 
Hopes that CNCF makes Fluent Bit grow rapidly.
 
Please add Trend Micro's logo to the users collage. Thanks!

![Trend-Micro-Logo svg](https://user-images.githubusercontent.com/19472493/92362072-05fefb00-f122-11ea-9af3-c6c9206fee02.png)

**Comment by edsiper** [comment]
thank you!, I will follow up by email, I will merge the PR this week.

**Comment by edsiper** [comment]
Company logo merged!:

https://github.com/fluent/fluent-bit#fluent-bit-in-production

thanks again!
