### ISSUE TITLE
Windows executable missing gelf output

### ISSUE THREAD

**Issue by jacekmackiewicz** [fluent/fluent-bit#2547]
## Bug Report

**Describe the bug**
Tried using gelf output on Windows but receiving 'gelf cannot be loaded'.

**To Reproduce**
Follow instructions in docs:
https://docs.fluentbit.io/manual/installation/windows
Add gelf output described in docs:
https://docs.fluentbit.io/manual/pipeline/outputs/gelf

**Expected behavior**
Agent starts sending logs to Graylog gelf input.

**Screenshots**
`Fluent Bit v1.5.6
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Output plugin 'gelf' cannot be loaded
Error: You must specify an output target. Aborting`

**Your Environment**
* Version used: 1.5.6 also tried few older versions, checked down to 1.3.8.
* Configuration: 
`[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on

[INPUT]
    Name              tail
    Path              c:\\ProgramData\\Docker\\containers\\*\\*-json.log
    Refresh_Interval  5
    Ignore_Older      10s
    Rotate_Wait       5
    DB                c:\\DB\\logs.db

[OUTPUT]
    Name          gelf
    Match         *
    Host          <graylog-server>
    Port          12201
    Mode          tcp
    Gelf_Short_Message_Key log`
* Environment name and version: Windows local development
* Operating System and version: Windows 10 2004
* Filters and plugins: gelf plugin

**Comment by jacekmackiewicz** [comment]
.\fluent-bit.exe -h doesn't show gelf in Outputs :(

**Comment by fujimotos** [comment]
> .\fluent-bit.exe -h doesn't show gelf in Outputs :(

@jacekmackiewicz This is because we have not ported `out_gelf` to Windows yet.

I'm currently looking at the code, and it seems that we need to clean up a few things
to get it compilable on Windows...

**Comment by jacekmackiewicz** [comment]
Ok, in the meantime I'm looking into http output and it seems to be working fine.
`[OUTPUT]
    Name                    http
    Match                   *
    Host                    
    Port                    12201
    URI                     /gelf
    Format                  gelf
    Gelf_host_key           stream
    Gelf_short_message_key  log`

**Comment by fujimotos** [comment]
> Ok, in the meantime I'm looking into http output and it seems to be working fine. Just not sure yet if it's a good workaround.

@jacekmackiewicz It is OK. the HTTP plugin also supports Graylog format.
`out_gelf` has some additional feature (like sending packets via UDP), but
the basic functionality is same.

By the way, I am currently working on the Windows port of `out_gelf`. I'll
post update here once I've finished the porting.

**Comment by fujimotos** [comment]
OK. Now the Windows port patch has been land on the main line.

You will see the GELF plugin enabled on Windows builds since the
next major release.

As such, I close this issue as resolved.
