### ISSUE TITLE
Rewrite Tag filter not working with STDIN Input

### ISSUE THREAD

**Issue by juls** [fluent/fluent-bit#2551]
## Bug Report

**Describe the bug**
I want to test configurations by piping messages into Fluent Bit via STDIN. When I do that, the _Rewrite Tag_ filter behaves different than with other input sources: it's not re-emitting matching messages.

**To Reproduce**
The following configuration is working as expected (tested with `docker run --rm -i -v $(pwd)/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf`):

```
[SERVICE]
    Flush        1

[INPUT]
    NAME   dummy
    Dummy  {"tag": "newtag", "log": "some message"}
    Tag    sometag

[FILTER]
    Name          rewrite_tag
    Match         sometag
    Rule          $tag ^(.*)$ $tag true

[OUTPUT]
    Name   stdout
    Match  *
```
It results in a correct output:
```
[0] sometag: [1600163728.497457100, {"tag"=>"newtag", "log"=>"some message"}]
[0] newtag: [1600163728.497457100, {"tag"=>"newtag", "log"=>"some message"}]
```

But when I try the same with STDIN as input (called with `echo '{"tag": "newtag", "log": "some message"}' | fluent-bit -c /fluent-bit/etc/fluent-bit.conf`) and this configuration:
```
[SERVICE]
    Flush        1

[INPUT]
    Name stdin
    Tag sometag

[FILTER]
    Name          rewrite_tag
    Match         sometag
    Rule          $tag ^(.*)$ $tag true

[OUTPUT]
    Name   stdout
    Match  *
```
It just emits the original message, not the rewritten message:
```
[0] sometag: [1600163820.178867800, {"tag"=>"newtag", "log"=>"some message"}]
```

**Expected behavior**
The _Rewrite Tag_ filter should also work with _stdin_ as input source.

**Your Environment**
I used the latest Docker image, `docker run --rm -i fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -V`returns _Fluent Bit v1.5.6_.

**Comment by fujimotos** [comment]
> It just emits the original message, not the rewritten message:

This seems to be a timing issue. Indeed, I can confirm the following works
as expected:

```bash
$  ( echo '{"tag": "newtag", "log": "some message"}'; sleep 3; ) | ./bin/fluent-bit -c test.c
...
[0] sometag: [1600304088.238072927, {"tag"=>"newtag", "log"=>"some message"}]
[0] newtag: [1600304088.238072927, {"tag"=>"newtag", "log"=>"some message"}]
```

Essentially `in_stdin` is too fast to shutdown the instance; The engine halts even
before rewrite-tag filter handle that event, hence causes the issue.
