### ISSUE TITLE
Filter Regex not work

### ISSUE THREAD

**Issue by jj891070** [fluent/fluent-bit#2556]
### My target
 {"@type":"Log","name": "..."}

### My Regex
[FILTER]
        Name    grep
        Match   *
        Regex   @type Log

**Comment by edsiper** [comment]
The current implementation doesn't allow us to have a ```@``` as part of the key name. 

I will check how hard will be to add support for it

**Comment by jj891070** [comment]
@edsiper  okay~thank you so much for responding to my question
