### ISSUE TITLE
Document missing `grace` key in  Service  section

### ISSUE THREAD

**Issue by ken5scal** [fluent/fluent-bit#2563]
## Bug Report

**Describe the bug**
https://docs.fluentbit.io/ seems missing  `grace` key in  Service  section once existed in the document for ver1.3

**To Reproduce**
- visit https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
- [Service] section is missing a description abount `Grace key`
- [v1.3 document](https://docs.fluentbit.io/manual/v/1.3/service) has the `Grace` key

**Expected behavior**
- have a description about `Grace` Key

**Screenshots**
* v1.3
![image](https://user-images.githubusercontent.com/9734362/93552959-d6b37e00-f9ac-11ea-9ee2-9d35910d1cd6.png)
* v1.4/v1.5
![image](https://user-images.githubusercontent.com/9734362/93552993-e763f400-f9ac-11ea-93cf-4b85835160c9.png)

**Your Environment**
na

**Additional context**
na

**Comment by zihengCat** [comment]
Yes, the description of key `grace` missing in the document now.

> https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_config.h#L50

Maybe we could add it to [fluent-bit-docs](https://github.com/fluent/fluent-bit-docs).

**Comment by ken5scal** [comment]
Oh, I didn't read the Readme carefully enough. Let me send the pr to fluent-bit-docs

**Comment by ken5scal** [comment]
I think this issue is irrelevant from the docs. So I will close it.
