### ISSUE TITLE
td-agent-bit extremely high IO% on DB.Sync Full|Normal

### ISSUE THREAD

**Issue by ndemeshchenko** [fluent/fluent-bit#2564]
## Bug Report

**Describe the bug**
td-agent-bit process utilizing up to 30% of IO on the virtual machine. writing 2-3Mb/sec.
If only set `DB.Sync Off` issue is gone. However, that can cause other issues if system crash.

Setup: td-agent-bit version 1.5.2 on Centos 7. Using tail input type and streaming to fluentd server

**To Reproduce**
- During high rate of new log lines fluentbit IOPS utilization skyrocketing up to 30%. writing 2-3Mb/sec
- looking at the `strace -e trace=write -p $(pgrep td-agent-bit) -y` most of the writes goes to sqlite DB

**Expected behavior**
td-agent-bit do not utilize 30% of IOPS

**Your Environment**
* Version used: 1.5.2
* Configuration:
sample INPUT block
```
[INPUT] 
    Name                tail    
    Path                /projects/file.log
    Tag                 stream.host.example.process.log
    Refresh_Interval    60
    Buffer_Max_Size     5MB
    Buffer_Chunk_Size   1MB
    DB                  /var/log/flb-db/tail-example-process.db
    DB.Sync             Full
```

* Operating System and version:  Centos 7
* Filters and plugins: tail

**Comment by edsiper** [comment]
data integrity with persistence has a cost: frequent I/O. 

If you want 100% data integrity in the database file that's the cost, but you can try a medium level of synchronization which is ```normal```, it should be less frequent than ```full``` and might help. Please test and let me know how it goes

**Comment by ndemeshchenko** [comment]
Sure, that make sense. However, changing db.sync option to normal made **almost** no difference for IO utilization, at the current load, I see 1-1.5% difference in IO

**Comment by edsiper** [comment]
@ndemeshchenko 

I've pushed some updates to GIT Master to improve the database I/O overhead. would you please take a look and give it a try ?

note: db.sync now defaults to ```normal```, it makes a big difference.

**Comment by agup006** [comment]
hey folks, it looks like this has been fixed and now is available in 1.7.0 - I'm going to close for now. Please re-open if we feel this is not resolved

**Comment by big-loser** [comment]
I'm facing the same issue。 1.5k/s IOPS， that`s crazy !!! 

i'm try disabled sqlite DB .  no effect at all.

**Comment by agup006** [comment]
I’d recommend a new issue @big-loser , also making sure you are trying the latest (4.0.4)

**Comment by big-loser** [comment]
> I’d recommend a new issue [@big-loser](https://github.com/big-loser) , also making sure you are trying the latest (4.0.4)

I have created a new issue, but there has been no response. Also, after upgrading to the latest version, there was no improvement.
