### ISSUE TITLE
Fluent Bit is unable to recover from too many accumulated buffers with filesystem storage type

### ISSUE THREAD

**Issue by simbou2000** [fluent/fluent-bit#2566]
## Bug Report

**Describe the bug**
Fluent Bit becomes unable to recover when too many buffers have been created with filesystem storage type due to loss of connectivity with an output server.
This works correctly when it's for a short duration (up to 1 or 2 minutes), but the issue starts to show up as more time passes and becomes apparent when it reaches 10+ minutes at 1500 records with a record payload of about 1.75KB each.
The backlog kept increasing even when the output server became available until the partition where the buffers are stored became full and started losing records while never being able to recover.

Monitoring the buffers folder at the beginning, I see the files created are around 2MB each, sometimes less depending on the flush time set in the config and when the count reaches 128 files, every new files becomes a single record. I have observed hundreds of thousand of around 2KB files when Fluent Bit is unable to recover.
The CPU usage of Fluent Bit is at around 8% during a normal load I have tested, then goes to around 6-11% when the output server connection is down until 128 buffers have been created, then the CPU usage jumps to 100% when writing each record as single files.

During the recovery, the CPU usage of Fluent Bit appears to vary depending on how many buffer files have been created and if the CPU usage reaches 100%, it can become unlikely to fully recover unless the traffic of new records is significantly lowered.

Limiting the partition size of the Fluent Bit buffers folder is a workaround I have found so Fluent Bit never falls into an unrecoverable situation, but this means losing most of the records during a syslog connectivity downtime.

**To Reproduce**
- Steps to reproduce the problem:
1. Simulate a high load (1500 records of ~1.75KB each) on Fluent Bit's input forward.
2. Stop the output server. (ie.: stopping the rsyslog service on the output's server)
3. Check the Fluent Bit buffers folder to see files slowly accumulating until it reaches 128, then the number of files rapidly increase.
4. Restart the output server when more than 1GB of buffers have been accumulated. (ie.: restart the rsyslog service on the output's server)
5. Check if Fluent Bit is able to recover from the accumulated backlog. The folder should slowly empty over time.

Which output server type used doesn't appear to change the result. (Also tried with ElasticSearch)

**Expected behavior**
When the output server goes down, Fluent Bit will keep creating new buffer files to keep all the incoming records from the forward input until the output server becomes available again.
Once the output server is back, Fluent Bit should be able to process the incoming records from the input forward while slowly emptying the accumulated backlog.
The buffer files should respect the configured flush time and/or up to 2MB in size. (Not single record per file)

**Screenshots**
![FluentBit_unrecoverable_situation](https://user-images.githubusercontent.com/71025844/93654697-d33fe700-f9ec-11ea-834d-a1f55fa6e838.PNG)
I added information of where the events happened in the timeline.

**Your Environment**
* Version used: 1.5.4
* Configuration:
```
[SERVICE]
    # Flush records to destinations every 5s
    Flush        5

    # Run in foreground mode
    Daemon       Off

    # Use 'info' verbosity for Fluent Bit logs
    Log_Level    info

    # Standard parsers & plugins
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # Enable built-in HTTP server for metrics
    # Prometheus metrics: <host>:24231/api/v1/metrics/prometheus
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    24231

    # Persistent storage path for buffering
    storage.path /var/log/fluent/buf/

[INPUT]
    Name   forward
    Port   24224
    storage.type  filesystem

# Remote syslog output
[OUTPUT]
    Name  syslog
    Match system.*
    Retry_Limit False

    # CONFIG: Syslog host
    Host 192.168.1.68
    # CONFIG: Syslog port
    Port 514
    Mode       tcp

    Syslog_Severity_Key log.syslog.severity.code
    Syslog_Facility_Key log.syslog.facility.code
    Syslog_Hostname_Key host.name
    Syslog_AppName_Key  process.name
    Syslog_ProcID_Key   process.pid
    Syslog_Message_Key  message
    Syslog_SD_Key       labels
```

* Environment name and version: KVM VM using 4 CPU cores and 2GB of ram
* Server type and version: QEMU/KVM LXC ESX / libvirt 4.5.0
* Operating System and version: CentOS 7
* Filters and plugins: None (Adding filters greatly reduces the chance of recovery)

**Additional context**
We had various issues in the past when the connection to the syslog server was lost for a long period of time and wanted to confirm Fluent Bit would be able to work correctly after a very long downtime. (15+ minutes)

We intended to use a partition size of several GB in size for the buffers to be sure we don't lose any record during a loss of connectivity, but this cause Fluent Bit to never recover when it happens.

This issue was first noticed when we had simple filters to add id/type/hostname/name/ip informations and encode json message which limited the CPU usage available to process the backlog but can be reproduced without any filter.

**Comment by simbou2000** [comment]
I investigated more and found the 128 buffers "limit" before Fluent Bit writes every messages in their own files causing the CPU usage to go high very fast is the limit of "up" chunks allowed and this can be tweaked with the parameter "storage.max_chunk_up". The downside to increase this value is how much RAM Fluent Bit will use since these chunks are mapped into memory and asynchronously synched to the disk when filesystem storage type is used.

As all received messages are eventually saved in their own files, writing about 1500 files per second, most of the CPU usage is lost at 2 places.
Both places (flb_input_chunk_total_size and input_chunk_get) seems to loop through all the chunks (or files) created so far at every message, so it is clear the system cannot handle a very high number of small files.
![FB-perf](https://user-images.githubusercontent.com/71025844/96631788-c876bb80-12e4-11eb-80e7-7b1e25bee3aa.PNG)

Another way to flush the up chunks to a down state I found is by setting a "mem_buf_limit", but these chunks will immediately be written to the disk when the threshold is met. There's also the possibility the chunk will stay in the up state if the threshold is not met and will have the same behavior of high CPU usage as I was seeing.

From what I can see, there's already a mechanism in place to flush the up chunks onto the filesystem when the input source is set as such, but there's no definitive way of using it at this time.
I was thinking there could be another threshold or number of up chunks is reached before Fluent Bit starts to flush older chunks down to the disk so the system can accumulate a certain number of chunks in memory before actively starting to write to disk. This will free up the available up chunks so newly received messages can continue be bundled in chunks and not encounter the scenario where a high number of files are created.

**Comment by simbou2000** [comment]
Hi @edsiper, noticed you did optimizations with the number of chunks used when the system is under load in #2025 (commit 9420ed9) and thought it was similar to the issue I am currently having.

As I previously mentioned, I tried different configuration parameters but it always come down to creating 1 file per message when the number of chunks up is reached. Increasing the limit of up chunks is not easily feasible since it requires enough ram to keep them even though we specified to use the file system storage.
From what I understand, they are put in ram with async option to write on the disk, but the cpu usage spikes high fast when it starts creating a large number of files instead of packing them in the usual large chunks.

I am currently looking into modifying the code to allow putting down older up chunks to free that resource for newer chunks to be created as usual when the output has connection issues. So it can be able to continue ingesting messages and later be able to process them when the output is working again. Although the current behavior is able to resume, a lot of CPU utilization is lost in just trying to iterate the large amount of tiny chunks it created and is unable to sustain the current load anymore which we will lose messages eventually as the messages are now mostly backing up in this scenario.

**Comment by simbou2000** [comment]
Something I noticed is when the output is having issues (ie.: lost of connection), chunks are being rescheduled and all of the available up chunks becomes busy/locked, which cause new messages to be written in separated files.
`
[engine] caught signal (SIGCONT)
[2020/10/28 18:18:50] Fluent Bit Dump
===== Input =====
systemd.0 (systemd)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 14.2K (14555 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 4
│  ├─ new           : 0
│  ├─ running       : 4
│  └─ size          : 14.2K (14555 bytes)
│
└─ chunks
└─ total chunks  : 8
├─ up chunks  : 4
├─ down chunks: 4
└─ busy chunks: 4
├─ size    : 14.2K (14555 bytes)
└─ size err: 0
forward.1 (forward)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 57.5K (58922 bytes)
│     └─ mem limit  : 195.3K (200000 bytes)
│
├─ tasks
│  ├─ total tasks   : 148
│  ├─ new           : 0
│  ├─ running       : 148
│  └─ size          : 57.7M (60467836 bytes)
│
└─ chunks
└─ total chunks  : 148
├─ up chunks  : 1
├─ down chunks: 147
└─ busy chunks: 148
├─ size    : 57.5K (58922 bytes)
└─ size err: 0
storage_backlog.2 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
└─ total chunks  : 0
├─ up chunks  : 0
├─ down chunks: 0
└─ busy chunks: 0
├─ size    : 0b (0 bytes)
└─ size err: 0
===== Storage Layer =====
total chunks     : 156
├─ mem chunks    : 0
└─ fs chunks     : 156
├─ up         : 5
└─ down       : 151
`

**Comment by simbou2000** [comment]
I did a quick prototype test by preventing all up chunks to be queued up in the stalled output pipeline and setting the mem_buf_limit greatly improved the situation by maximizing the size of unqueued up chunk and putting them down once full, freeing up this resource for new chunks.

Configuration:
```
[SERVICE]
    # Flush records to destinations every 5s
    Flush        5

    # Run in foreground mode
    Daemon       Off

    # Use 'info' verbosity for Fluent Bit logs
    Log_Level    info
    Log_File     fluent-dbg.log

    # Standard parsers & plugins
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # Enable built-in HTTP server for metrics
    # Prometheus metrics: <host>:24231/api/v1/metrics/prometheus
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    24231

    # Persistent storage path for buffering
    storage.path /var/log/fluent/buf/
    storage.max_chunks_up 20

[INPUT]
    Name   forward
    Port   24224
    storage.type  filesystem
    mem_buf_limit 16M

...
```

```
[engine] caught signal (SIGCONT)
[2020/10/28 20:23:23] Fluent Bit Dump
===== Input =====
forward.0 (forward)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 14.0M (14727034 bytes)
│     └─ mem limit  : 15.3M (16000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 6
│  ├─ new           : 0
│  ├─ running       : 6
│  └─ size          : 3.3M (3441738 bytes)
│
└─ chunks
└─ total chunks  : 29
├─ up chunks  : 11
├─ down chunks: 18
└─ busy chunks: 6
├─ size    : 2.2M (2291026 bytes)
└─ size err: 0
storage_backlog.1 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
└─ total chunks  : 0
├─ up chunks  : 0
├─ down chunks: 0
└─ busy chunks: 0
├─ size    : 0b (0 bytes)
└─ size err: 0
===== Storage Layer =====
total chunks     : 29
├─ mem chunks    : 0
└─ fs chunks     : 29
├─ up         : 11
└─ down       : 18

```

Buffers in the storage folder:
```
-rw-------. 1 root root  578856 Oct 28 20:16 5954-1603930581.746944624.flb
-rw-------. 1 root root  571924 Oct 28 20:16 5954-1603930586.735355049.flb
-rw-------. 1 root root  568458 Oct 28 20:16 5954-1603930591.736801067.flb
-rw-------. 1 root root  568458 Oct 28 20:16 5954-1603930596.718469255.flb
-rw-------. 1 root root  585788 Oct 28 20:16 5954-1603930601.724399662.flb
-rw-------. 1 root root  568458 Oct 28 20:16 5954-1603930606.730495031.flb
-rw-------. 1 root root 2048440 Oct 28 20:17 5954-1603930611.714796268.flb
-rw-------. 1 root root 2048440 Oct 28 20:17 5954-1603930629.592419106.flb
-rw-------. 1 root root 2048440 Oct 28 20:17 5954-1603930647.295586332.flb
-rw-------. 1 root root 2048440 Oct 28 20:18 5954-1603930665.6428074.flb
-rw-------. 1 root root 2048440 Oct 28 20:18 5954-1603930682.984355360.flb
-rw-------. 1 root root 2048440 Oct 28 20:18 5954-1603930700.808840321.flb
-rw-------. 1 root root 2027644 Oct 28 20:18 5954-1603930718.652711968.flb
-rw-------. 1 root root 2027644 Oct 28 20:19 5954-1603930736.253400180.flb
-rw-------. 1 root root 2027644 Oct 28 20:19 5954-1603930753.905524770.flb
-rw-------. 1 root root 2027644 Oct 28 20:19 5954-1603930771.439453064.flb
-rw-------. 1 root root 2027644 Oct 28 20:20 5954-1603930789.162426468.flb
-rw-------. 1 root root 2027644 Oct 28 20:20 5954-1603930807.10417755.flb
-rw-------. 1 root root 2027644 Oct 28 20:20 5954-1603930824.631370736.flb
-rw-------. 1 root root 2027644 Oct 28 20:21 5954-1603930842.446099466.flb
-rw-------. 1 root root 2027644 Oct 28 20:21 5954-1603930860.277407848.flb
-rw-------. 1 root root 2027644 Oct 28 20:21 5954-1603930878.119367166.flb
-rw-------. 1 root root 2027644 Oct 28 20:21 5954-1603930895.717437409.flb
-rw-------. 1 root root 2027644 Oct 28 20:22 5954-1603930913.243858007.flb
-rw-------. 1 root root 2027644 Oct 28 20:22 5954-1603930930.989415174.flb
-rw-------. 1 root root 2027644 Oct 28 20:22 5954-1603930948.622358854.flb
-rw-------. 1 root root 2027644 Oct 28 20:23 5954-1603930966.265366854.flb
-rw-------. 1 root root 2027644 Oct 28 20:23 5954-1603930984.92358508.flb
-rw-------. 1 root root 2027644 Oct 28 20:23 5954-1603931001.781400778.flb
-rw-------. 1 root root 2027644 Oct 28 20:23 5954-1603931019.631324408.flb
-rw-------. 1 root root 2027644 Oct 28 20:24 5954-1603931037.291357443.flb
-rw-------. 1 root root 2027644 Oct 28 20:24 5954-1603931054.868396366.flb
-rw-------. 1 root root 2027644 Oct 28 20:24 5954-1603931072.572386921.flb
-rw-------. 1 root root 2027644 Oct 28 20:25 5954-1603931090.187240267.flb
-rw-------. 1 root root 2027644 Oct 28 20:25 5954-1603931108.66357215.flb
-rw-------. 1 root root 2027644 Oct 28 20:25 5954-1603931125.654374802.flb
-rw-------. 1 root root 2027644 Oct 28 20:26 5954-1603931143.433975442.flb
-rw-------. 1 root root  102400 Oct 28 20:26 5954-1603931161.166341214.flb

```

**Comment by edsiper** [comment]
@simbou2000 

first of all, thanks for your detailed report and PR submitted on #2816 

The perf report has been very useful, I was able to replicate similar numbers on this scenario: high load and all destinations down.

I realized a couple of problems in the current code (input chunk) implementation:

- find a candidate chunk to write data is expensive, the linear check won't scale: O(n)

- if all chunks are down in the filesystem due to a contingency mechanism for low memory usage, it simply creates a new chunk instead of doing some little extra work to append data to an existing chunk instead of creating a new one. 

Based on that I will put PR review #2816 on hold until fixing the root cause of the problem described above. RIght now I am testing the following fixed in a private branch:

- Create an in-memory index for the chunks per input instance, so using a hash table is pretty easy to look up a candidate chunk, actually, I was able to reduce the time lookup of flb_input_chunk_get() from 43.59% to 2.5%. (Yes, a major improvement).

- Improved the logic to append data to a chunk, now the chunks are no longer 120 bytes but growing to 36KB. Here there is still room for improvement.

I will publish the work-in-process branch tomorrow so you can take a look at it.

regards,

**Comment by edsiper** [comment]
@simbou2000 I've pushed a couple of fixes that address the root cause of the problem:

#### Before

![chunk_1](https://user-images.githubusercontent.com/369718/100690045-5b2a6180-334b-11eb-9b14-2b06b1b816be.png)

#### After

![chunk_2](https://user-images.githubusercontent.com/369718/100690084-6d0c0480-334b-11eb-9a81-95ece1d789d9.png)

The main commit in question is this: 1dc6c19ac87e4e91b6fbec92a93bdc6255a08031

note: there are others in GIT master

Please re-test GIT Master and share some feedback.

**Comment by simbou2000** [comment]
Hi @edsiper,
Did most of the problematic test cases I had found which worked great.
I was also surprised one of the corner case I found seems to be covered by the commit which happens in low load during the downtime to increase up_chunks and letting it reach to the configured max_up_chunks, but was now following the mem_buf_limit restriction even though it was making more up_chunks and was not creating a file for each message anymore.

**Comment by simbou2000** [comment]
I tried with a 10GB partition to see how it would react due to the large number of files and I encountered some weird behavior where it cannot recover due to several errors related to:
- [error] [sched] a 'retry request' could not be scheduled. the system might be running out of memory or file descriptors. The scheduler will do a retry later.
- [  Error] timerfd: Too many open files, errno=24 at /tmp/fluent-bit-1.7.0/lib/monkey/mk_core/mk_event_epoll.c:193

Even when I stop the load, it keeps on failing and appears to not process anything.

```
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: [2020/12/03 14:05:25] Fluent Bit Dump
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ===== Input =====
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: systemd.0 (systemd)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ status
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  └─ overlimit     : no
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │     ├─ mem size   : 64.5K (66055 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │     └─ mem limit  : 3.8M (4000000 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ tasks
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ total tasks   : 38
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ new           : 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ running       : 38
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  └─ size          : 49.4K (50557 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ chunks
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ total chunks  : 48
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ up chunks  : 45
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ down chunks: 3
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ busy chunks: 38
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ size    : 49.4K (50557 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ size err: 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: forward.1 (forward)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ status
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  └─ overlimit     : yes
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │     ├─ mem size   : 1.6G (1763631554 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │     └─ mem limit  : 122.1M (128000000 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ tasks
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ total tasks   : 2007
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ new           : 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ running       : 2007
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  └─ size          : 3.5G (3790891669 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ chunks
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ total chunks  : 2912
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ up chunks  : 930
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ down chunks: 1982
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ busy chunks: 2007
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ size    : 48.4M (50762351 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ size err: 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: storage_backlog.2 (storage_backlog)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ status
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  └─ overlimit     : no
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │     ├─ mem size   : 5.9M (6148168 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │     └─ mem limit  : 0b (0 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ tasks
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ total tasks   : 3
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ new           : 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  ├─ running       : 3
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │  └─ size          : 5.9M (6148168 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: │
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ chunks
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ total chunks  : 3
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ up chunks  : 3
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ down chunks: 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ busy chunks: 3
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ size    : 5.9M (6148168 bytes)
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ size err: 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ===== Storage Layer =====
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: total chunks     : 5879
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ mem chunks    : 0
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ fs chunks     : 5879
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: ├─ up         : 978
Dec 03 14:05:28 ids-simon.local td-agent-bit[11377]: └─ down       : 4901

```

**Comment by simbou2000** [comment]
Fluent-bit is in a deadlock state since it had over 900 files opened and the application has 1025 file descriptor.
The output can't establish a connection due to no more file descriptor available and can't process any chunks.
It is weird it has this many open file / up_chunks.

**Comment by edsiper** [comment]
Please share your configuration

**Comment by simbou2000** [comment]
Mostly the same configuration, but with mem_buf_limit set for the inputs:
```
[SERVICE]
    # Flush records to destinations every 5s
    Flush        5

    # Run in foreground mode
    Daemon       Off

    # Use 'info' verbosity for Fluent Bit logs
    Log_Level    info

    # Standard parsers & plugins
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # Enable built-in HTTP server for metrics
    # Prometheus metrics: <host>:24231/api/v1/metrics/prometheus
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    24231

    # Persistent storage path for buffering
    storage.path /var/log/fluent/buf/
    storage.max_chunks_up 128

[INPUT]
    Name systemd
    Tag  system.journal.*
    Path /var/log/journal
    DB   /var/log/fluent/journald-cursor.db
    storage.type  filesystem
    mem_buf_limit 4M

[INPUT]
    Name   forward
    Port   24224
    storage.type  filesystem
    mem_buf_limit 128M

[OUTPUT]
    Name  syslog
    Match system.*
    Retry_Limit False

    # CONFIG: Syslog host
    Host 192.168.1.68
    # CONFIG: Syslog port
    Port 514
    Mode       tcp

    Syslog_Severity_Key log.syslog.severity.code
    Syslog_Facility_Key log.syslog.facility.code
    Syslog_Hostname_Key host.name
    Syslog_AppName_Key  process.name
    Syslog_ProcID_Key   process.pid
    Syslog_Message_Key  message
    Syslog_SD_Key       labels

```

**Comment by simbou2000** [comment]
Hi again,
Since the potential of the deadlock due to using all of the available file descriptors, we made a custom build using the proposed changes and we didn't encounter any weird issues.
We still are interesting to use the original code there's a way to prevent the deadlock problem to occur.
So far, I found that restarting the service helps to put it back again until it happens again.

Perhaps limiting the number of opened files similar to how I initially proposed or a different way could solve that issue?

**Comment by nike38rus** [comment]
Hi there! We're facing the same issue when trying to implement reliable log shippment with storage-backed buffers on fluent-bit side. And this is kinda critical bug IMO when logs is not just a regular text in cases e.g. when fluent-bit is using for business-critical data forwarding (my case).

@edsiper is there any updates on this issue?

**Comment by acastong** [comment]
Commenting to prevent issue from becoming stale.  This is issue is still applicable: if we need to process a large number of messages with filesystem storage type, a build from the pull request #2804 MUST be used.

**Comment by acastong** [comment]
Commenting to prevent issue from being closed. Fluentbit is still unable to process a large rate of messages with filesystem storage type.  To go around this issue, a build from the pull request #2804 MUST be used.

**Comment by JeffLuoo** [comment]
Seeing similar issue when too many backlogs chunks are registered.

**Comment by simbou2000** [comment]
Hi @qingling128,
We were able to test Fluent Bit version 1.8.8 and seems to have our major issues resolved.
We'll be continuing using the official version of Fluent Bit instead.

**Comment by mselinger75** [comment]
I see this issues still exists in 2.1.6 version. I have `threaded on` for input tail, and I see a ton of

```
[2023/07/05 20:16:01] [error] [input:tail:al_input_tail_k8s_audit] could not enqueue records into th │
│ e ring buffer                                                                                        │
│ [al_input_tail_k8s_audit] failed buffer write, retries=0                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=1                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=2                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=3                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=4                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=5                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=6                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=7                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=8                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=9                                             │
│ [2023/07/05 20:16:02] [error] [input:tail:al_input_tail_k8s_audit] could not enqueue records into th │
│ e ring buffer                                                                                        │
│ [al_input_tail_k8s_audit] failed buffer write, retries=0                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=1                                             │
│ [al_input_tail_k8s_audit] failed buffer write, retries=2  
```

**Comment by peter-gz** [comment]
> 

same issue in 2.1.8. it could not recover and I had to restart the agent.

**Comment by peter-gz** [comment]
> same issue in 2.1.8. it could not recover and I had to restart the agent.

My issue turned out to be memory allocation issue. I ran it on a container with memory request < limit, and used a Mem_Buf_Limit config which is bigger than the memory request.
After I set the request = limit, the issue is resolved.

However, a clearer logging about such memory allocation problem would be much helpful : )
