### ISSUE TITLE
pack: bad JSON convertion when str size == 0

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#257]
Some plugins like elasticsearch uses the pack routines to convert msgpack to json.

In cases where a map field have a string of length zero, the pack routine generate invalid data:

https://github.com/fluent/fluent-bit/blob/master/src/flb_pack.c#L355

try_to_write() should allow a string of length zero, meaning: add nothing:

https://github.com/fluent/fluent-bit/blob/master/src/flb_pack.c#L300

otherwise this ended up in corrupted fields

**Comment by edsiper** [comment]
@nokute78 ^

**Comment by edsiper** [comment]
should this fix the issue ?

```C
    case MSGPACK_OBJECT_STR:
        if (try_to_write(buf, off, left, "\"", 1) &&
            (o->via.str.size > 0 ?
             try_to_write(buf, off, left, (char*)o->via.str.ptr, o->via.str.size) : 1
             ) &&
            try_to_write(buf, off, left, "\"", 1)) {
            ret = FLB_TRUE;
        }
        break;

```

**Comment by nokute78** [comment]
@edsiper Thank you for reporting that!
The patch is LGTM and I pushed as #260.

This is a note of this issue.

## How to reproduce the issue
Using shell script like this. The point is that the value is ""

```sh
#!/bin/sh

while :; do
  echo -n "{\"key\": \"\"}"
  sleep 1
done
```

in_stdin -> out_file( which passes null string to try_to_write )
```
$ ./test.sh | bin/fluent-bit -i stdin -o file
```

The data will be broken.
```
$ cat stdin.0 
stdin.0: [1494419187.554960, {"key":"key�"}]
stdin.0: [1494419264.135817, {"key":"key���"}]
stdin.0: [1494419265.139927, {"key":"key���"}]
stdin.0: [1494419266.145376, {"key":"key���"}]
stdin.0: [1494419267.149958, {"key":"key���"}]
stdin.0: [1494419268.154727, {"key":"key�"}]
```

**Comment by edsiper** [comment]
thanks
