### ISSUE TITLE
rewrite_tag keep flag is not behaving as intended

### ISSUE THREAD

**Issue by trondhindenes** [fluent/fluent-bit#2570]
## Bug Report

**Describe the bug**
When `rewrite_tag:keep` is set to `false`, fluentbit's behavior doesn't match the documentation

**To Reproduce**
Given this config:
```

[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    #Parsers_File  dummy-parser.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name         dummy
    Dummy        {"message":"dummy", "what": "stuff", "log_processed": {"log_source": "nginx-v1"}}

[FILTER]
    Name           modify
    Match          *
    Condition      Key_exists log_processed
    Set            keep true

[FILTER]
    Name    grep
    Match   *
    Regex keep true

[FILTER]
    Name    rewrite_tag
    Match   *
    Rule    $log_processed['log_source']    "nginx-v1"    "nginx-v1"    true

[FILTER]
    Name    lua
    Match   *
    script  test.lua
    call    cb_print

[OUTPUT]
    Name   stdout
    Match  nginx*
```

I can see that both the "rewritten" and the "original" events pass thru the lua script (line 1 and 2), and that the "rewritten" event gets processed by the output (line 3)
```
dummy.0:  [1600704454.200857, {  what => stuff, log_processed => table: 0x417e6160, message => dummy, keep => true }]
nginx-v1:  [1600704454.200857, {  what => stuff, log_processed => table: 0x417e0458, message => dummy, keep => true }]
[0] nginx-v1: [1600704454.200857332, {"message"=>"dummy", "what"=>"stuff", "log_processed"=>{"log_source"=>"nginx-v1"}, "keep"=>"true"}]
```
This indicates that my filter pipeline is working as intended. However, if I change the `rewrite_tag:rule` to 
```Rule    $log_processed['log_source']    "nginx-v1"    "nginx-v1"    false``` 
my expectation is that only the "rewritten" event gets passed on to the lua filter and the output. However, nothing gets processed by either, 

**Expected behavior**
Events with the rewritten tag should be processed by both lua filter and output plugin

**Screenshots**
N/A, description above is hopefully good enough.

**Your Environment**
* Version used: 1.5 using docker image `fluent/fluent-bit:1.5` See config file for list of plugins, filters, etc

**Additional context**
Just trying to get basic functionality to work according to docs

**Comment by trondhindenes** [comment]
Looking closer at this, if I replace the `Match` statement in the `rewrite_tag` it works.
```
[FILTER]
    Name    rewrite_tag
    Match   dummy*
    Rule    $log_processed['log_source']    "nginx-v1"    "nginx-v1"    false
```
I don't quite understand why tho. It would be good to get that explained - it feels like the documentation is missing out on some key info.

**Comment by jcdauchy** [comment]
I have had the same issue. The only solution was tous leave the "true"  flag :(

**Comment by AyliD** [comment]
same here )-:

**Comment by AyliD** [comment]
No matter when in the pipeline if i set the rule not to keep original records with old tags the processing is just blocked.

**Comment by briend** [comment]
I just got hit by this too, and it's not really a bug. . . the docs are not super clear that the emitted record from `rewrite_tag` starts at the _beginning_ of the pipeline, not where-ever the rewrite_tag filter exists.  So, when that new record reaches your rewrite_rule again, it will match `Match *` and, that's right, it will create an infinite loop!  I suppose once the buffer fills up for that emitter those records get discarded.  That's why it works when you set the flag to `true`: those records avoid the loop since they "continue onwards".

At least, I am fairly sure that's what is happening.  Make sure your `rewrite_tag` will NOT match the emitted records.

**Comment by jcdauchy-moodys** [comment]
Thanks @briend for clarifying this, I will test that later. Good that you mention it in the docs !

**Comment by edsiper** [comment]
thanks everyone, a doc issue, thanks to @briend the doc is fixed (changes being deployed now).

**Comment by AyliD** [comment]
But with if i use fluentbit as log driver to docker compose file, my match is unknown cause its container id and i need to use '*' then fluentbit just hangs.

**Comment by AyliD** [comment]
also for AWS firelens using fluentbit match tags are automanaged. "FireLens manages the match configuration. This configuration is not specified in your task definition." thats mean that first match has to be * which cause infinite loop
