### ISSUE TITLE
Huge fluent-bit buffer chunk file

### ISSUE THREAD

**Issue by erain** [fluent/fluent-bit#2578]
## Bug Report

**Describe the bug**

We use fluent-bit running as DaemonSet on K8s cluster nodes as log forwarder, and see *HUGE* buffer chunk file (see the 27G tail.0 file below):

```
root@user1-app-12:/var/log# du -sh /var/log/fluent-bit-buffers
29G     /var/log/fluent-bit-buffers

root@user1-app-12:/var/log/fluent-bit-buffers# du -sh *
392K    systemd.10
1.3G    systemd.11
128M    systemd.12
100K    systemd.9
27G     tail.0
282M    tail.1
4.0K    tail.2
4.0K    tail.3
4.0K    tail.4
4.0K    tail.5
4.0K    tail.6
4.0K    tail.7
4.0K    tail.8
```

**Expected behavior**

Buffer chunk file should within reasonable size. 

**Your Environment**

* Version used: v1.4.2
* Configuration: relevant part
```
        storage.path               /var/log/fluent-bit-buffers/
        storage.sync               normal
        storage.checksum           off
        storage.backlog.mem_limit  10M
```
* Environment name and version (e.g. Kubernetes? What version?): GKE v1.16.8-gke.6 
* Server type and version: linux
* Operating System and version: Ubuntu 18.04.4 LTS
* Filters and plugins: tail / systemd / record_modifier /  forward

**Comment by erain** [comment]
@edsiper is this a known issue in v1.4? 

Also I this is another important reason to move forward with https://github.com/fluent/fluent-bit/pull/2520

**Comment by edsiper** [comment]
what's the average size of each file inside the directories mentioned above ?, e.g: tail.0, systemd.N ..

**Comment by erain** [comment]
Quote from my colleague:

"
I see avg size of those flb files being 2MB through early August…

rising to 4MB in mid-August
"

**Comment by edsiper** [comment]
if the queue size is "huge" means that is not able to flush the data and is just buffering. I think this is something related to the ability to dispatch data faster than the incoming data. 

Please attach config file and log file for that deployment

**Comment by erain** [comment]
Thanks for the help @edsiper ! 

We currently this the following setup:
- fluent-bit runs per node as log forwarder (daemonset)
- fluentd runs as log aggregator (statefulset)

And we have the following: 
```
  output-fluentd.conf: |
    [OUTPUT]
        Name        forward
        Match       *
        Host        <log-aggragator url>
        Port         <log-aggragator port>
        Retry_Limit False
```

I just confirmed from the colleague that fluentd was not healthy, which in combination of `Retry_Limit False` resulted in the data on the disk became too big. So this is not a bug in fluent-bit, however https://github.com/fluent/fluent-bit/pull/2520 could still be an enhancement in this situation. 

I am going to close this and thanks again!
