### ISSUE TITLE
Publish Dockerfile.windows to fluent-bit dockerhub

### ISSUE THREAD

**Issue by CandiedCode** [fluent/fluent-bit#2588]
**Is your feature request related to a problem? Please describe.**
I want to use fluent-bit on window k8s nodes.

**Describe the solution you'd like**
We currently use the Linux containers in https://hub.docker.com/r/fluent/fluent-bit/ but would like the windows container to be published as well.

**Describe alternatives you've considered**
Currently, we build https://github.com/fluent/fluent-bit/blob/master/Dockerfile.windows to our local registry.

**Comment by fujimotos** [comment]
> We currently use the Linux containers in https://hub.docker.com/r/fluent/fluent-bit/ but would like the windows container to be published as well.

I think this proposal is legitimate. It would be useful for developers if we
publish official Docker images.

In the meantime, if we ever decide to do that, I really want to automate the
publishing process. Without some smart way to automate it, I don't believe
docker images can be maintained over the long term.

https://www.appveyor.com/docs/server/

I've not studied the documentation closely yet, but I'm feeling that we may
be able to leverage AppVeyor to accomplish this. Does anyone have any
suggestions?

**Comment by danjagnow** [comment]
AppVeyor can be used to publish Docker images.  See [appveyor-docker-images.yml](https://github.com/appveyor/build-images/blob/master/appveyor-docker-images.yml) for some example steps.  It looks like this repo is already using Travis CI, which also supports [building a Docker image](https://docs.travis-ci.com/user/docker/#building-a-docker-image-from-a-dockerfile) and [pushing it to a registry](https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry).  You could also [publish Docker images via GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images).
