### ISSUE TITLE
Liveness probe metrics

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#2591]
**Is your feature request related to a problem? Please describe.**
K8s fluentbit POD shall have an liveness probe.

This is what I am using now, mostly due the fact that 1y ago I faced the issue that fluentbit out_forward did stuck if is upstream was restarted - so the liveness probe detected errors and caused fluentbit restart within cca 10min.
```sh
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -exc
            - errcount=$(curl -s -f http://localhost:65012/api/v1/metrics/prometheus
              | grep fluentbit_output_retries_failed_total | awk '{print $2}'| tail
              -1); if [ $errcount -gt 60 ]; then echo "Found ${errcount} output errors";
              exit 1; fi
          failureThreshold: 10
          initialDelaySeconds: 120
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
```

**Describe the solution you'd like**

However above solution is to raw. Instead of comparing "total" error count (which ultimately will reach its treshold) is essential to provide metric,  that will trigger restart if things go wrong:
- an error failed retry in last 5 - 10 minutes,
- compare sent, retried, retry failed in 5-10 min window

**Additional context**

Mind, comparing only failed_retry is not the good thing (ie: with ES output, you may constantly fail to write "broken data" while other will process correctly). So required to compare ratio between sucesfull, failed. And provide vector indicating current state.

**Comment by avdhoot** [comment]
@epcim nice raw solution. I faced same issue when we evaluating fluent-bit. But for us v1.5 fixed the issue where fluent-bit needs restart if upstream is restarted.

**Comment by epcim** [comment]
1.5.7 seems fixes original issue, but that is not subject to remove the above liveness probe, and that one needs to be current trend not long term collected errors cause restart even all ok in past few hours ?

**Comment by epcim** [comment]
better probe

```
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -exc
            - >
              function getOutTotalF0() { curl -s --connect-timeout 5 --retry 3 -f http://localhost:65012/api/v1/metrics/prometheus |grep '^fluentbit_output_proc_records_total{name="forward.0"}' | awk '{print $2}' ;};
              T=$(getOutTotalF0);test -e ./m_oprtf0 && { test $(cat ./m_oprtf0) -ge $T && { echo "OutputRecordsTotal Forward0 freeze: $T"; exit 1;} ;}; test $T -ge -10 && { echo "$T" >| ./m_oprtf0; } || true;
          initialDelaySeconds: 120
          periodSeconds: 60
          failureThreshold: 8
          timeoutSeconds: 5

```

**Comment by rmacian** [comment]
In the docs they establish a liveness probe based on metrics response that I think it's not a good one:

https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/output/kafka/fluent-bit-ds.yaml#L33

If you don't have anything to monit the metrics returns a 404 so the pod enters in a non ready state or even worse a crashloopbackoff

**Comment by epcim** [comment]
honestly, we were all good with v.1.4.4, then 1.5.5-.1.5.7 have had some sort of issues. This particular one was that there was no new log reading. Now on 1.6.1 (which I still dont trust much) but all the issues we had disappeared. Note there is new feature, that 1.6.x does - reading files from end rather from beggining (it's possibly related).

the link/code for liveness is not that bad. Yes I know the 404 issue. Anyway, if metrics are up and doing something - whole pod is up healthy. For your case I would recommend to set any rate limiting (then you have one line a minute at least ;)

the other question what "job" the liveness probe does. In my usecase I want to ensure I have **all logs** in time collected on the backend. We went this discussion few times and its really hard to figure out whether you have "all" the logs or just portion (especially if you have 15 nodes). So the outcome from that was, the liveness probe rather restart fluentbit on any issue with out_forward (errors, retries, no progress).

**Comment by eugenesotnikov** [comment]
How can you use livenessProbe with /bin/bash if bash is absent in fluent-bit image?
I tryed to use this liveness and got mistakes that bash is absent.

**Comment by epcim** [comment]
> How can you use livenessProbe with /bin/bash if bash is absent in fluent-bit image?
> I tryed to use this liveness and got mistakes that bash is absent.

Good point, well we do build own.

**Comment by eugenesotnikov** [comment]
hmm. ok..
i have trouble with 1.7.2. It's stoped forward log. But k8s mean that it's live by httpget livenessprobe. And i wanted to change liveness probe to exec...
Maybe exist another default variant livenessprobe for k8s for freeze pod?

**Comment by debu99** [comment]
same issue in latest 1.7

**Comment by kkujawa-sumo** [comment]
@epcim What is `m_oprtf0` which you proposed to use in livenessProbe in https://github.com/fluent/fluent-bit/issues/2591#issuecomment-707082441?

**Comment by epcim** [comment]
Just an env.variable populated by parsed metric.On 21 Sep 2021 10:33, Katarzyna Kujawa ***@***.***> wrote:
@epcim What is m_oprtf0 which you proposed to use in livenessProbe in #2591 (comment)?

**Comment by lunarfs** [comment]
So we had an issue where the metrics endpoint did not answer (due to some kubernetes API issue), resulting in an empty T and  the pod not restarting. Modified the script sligtley to
`
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -exc
              - >
                function getOutTotalF0() { set  -o pipefail;curl -s --connect-timeout 5 --retry 3 -f http://localhost:65012/api/v1/metrics/prometheus |grep '^fluentbit_output_proc_records_total{name="kafka.0"}' | awk '{print $2}' || echo 0;};
                T=$(getOutTotalF0);test -e ./m_oprtf0 && { test $(cat ./m_oprtf0) -ge $T && { echo "OutputRecordsTotal Kafka0 freeze: $T"; exit 1;} ;}; test $T -ge -10 && { echo "$T" >| ./m_oprtf0; } || true;
          failureThreshold: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 300`
