### ISSUE TITLE
log errors for http backed

### ISSUE THREAD

**Issue by sbvitok** [fluent/fluent-bit#2593]
I write to clickhouse through http backed.
if an error occurred, CH return http status 4xx or 5xx and error message in body, and the problem is, that fluent-bit don't display this message in logs, and it's a pain to find out way error happened.
I try to set logltvel to debug , but it's not help

**Comment by fujimotos** [comment]
> if an error occurred, CH return http status 4xx or 5xx and error message in body, and the problem is, that fluent-bit don't display this message in logs, and it's a pain to find out way error happened.

@sbvitok As far as I can tell, it should print the error log message.
The code path is here:

https://github.com/fluent/fluent-bit/blob/master/plugins/out_http/http.c#L186

Fluent Bit will display a message like "localhost:80 HTTP status=400"  if it
encounters status code other than 2xx.

**Comment by sbvitok** [comment]
resp.body need to display to, not only resp.status
error message from CH will be in resp.body

**Comment by edsiper** [comment]
Fixed in e605e675
