### ISSUE TITLE
Merge_Log for Docker Logs or JSON Logs 

### ISSUE THREAD

**Issue by hypePG** [fluent/fluent-bit#2607]
**Is your feature request related to a problem? Please describe.**
Hey, I am receiving logs form Docker via the in_forward plugin. At the moment I am able to parse the application logs, which are nested under the key "log". After parsing the data is saved as json key/value pairs. 

The Kubernetes filter plugin has a similiar functionality with the additional feature to parse the content **AND** at all fields with a user definied prefix. The option is missing for a "normal" parser.

**Describe the solution you'd like**
When parsing logs it would be great to have the oportunity to specify a Merge_Log and Merge_Log_Key. At least for parser using json. The code for this should already exist in the kubernetes filter plugin.

**Describe alternatives you've considered**
I considered using the "nest" filter. I tried to lift the JSON map under the key "log" and than add a prefix. But since the JSON map is escaped with "\" in front of '"' fluent-bit doesnt recognize the map as a map...

**Comment by hypePG** [comment]
solved it with the help of LUA

**Comment by zoobab** [comment]
Any idea how you solved it with lua?

**Comment by hypePG** [comment]
> Any idea how you solved it with lua?

`json = require("/fluent-bit/etc/json")

function parseLog(tag , timestamp, record)
  if record.log ~= nil then
    local status, res = pcall(json.decode, record['log'])
    if status then
      record['log_message'] = res
    else
      record['log_message'] = { message = record['log']}
    end
    record['log'] = nil
	return 1, timestamp, record
  else
    return 0, timestamp, record
  end
end`

and i used this json lua library:
https://github.com/rxi/json.lua/blob/master/json.lua

hope thats helps

**Comment by yjqg6666** [comment]
I got a similar issue. Need to merge docker log message starting with date/time in log with the following logs which are not starting with date/time.

> {"log":"2023-02-22 16:46:14.040 [INFO ] | main|  | c.c.m.a.example:33 | msg\n","stream":"stdout","time":"2023-02-22T08:50:12.263337097Z"}
>{"log":"(msg-continued)\n","stream":"stdout","time":"2023-02-22T08:50:12.263337099Z"}

-- input.conf
[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    multiline.parser  multiline-regex

-- parsers.conf
[MULTILINE_PARSER]
    name          multiline-regex
    type          regex
    flush_timeout 1000
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule      "start_state"   "/\"log\":\s*\"\d\d\d\d-/"         "cont"
    rule      "cont"          "/\\"log\":\s*\"[^\d].+/"          "cont"
    key_content log

--filter.conf
[FILTER]
    name lua
    match *
    script merge_log.lua
    call   merge_log

--merge_log.lua
function merge_log(tag, timestamp, record)
       nlog = ''
       for a, l, c in string.gmatch(record['log'], '(log":%s*)"([^"]+)"(,%s*"stream")') do
         nlog = nlog .. l
       end
       if (nlog == '')
       then
         return 0, 0, 0
       end
       record['log'] = nlog
       return 1, timestamp, record
end
