### ISSUE TITLE
[Documentation] document usage of parser plugins

### ISSUE THREAD

**Issue by martin21** [fluent/fluent-bit#261]
I tried to setup Fluent Bit to deliver Apache log messages. Tail input plugin currently does not seem to implement forward parsing, but puts the whole message in "log" field. I think it would be beneficial if Fluent Bit could parse the messages already to offload this to Fluent Bit clients. And also to simply the setup.

Currently I have the following solution.

Fluent Bit config:

```
[INPUT]
    Name tail
    Tag fluentbit.apache
    Path /var/log/apache2/access.log
    DB /var/lib/fluentbit/apache-access.db

[OUTPUT]
    Name  Forward       
    Match *
    Host logfluentd
    Port 12225
```

Fluentd config:

```
<source>
        type forward
        bind 0.0.0.0
        port 12225
        source_hostname_key logsource
</source>

# https://github.com/tagomoris/fluent-plugin-parser
<filter fluentbit.apache>
  @type parser
  format apache
  key_name log
</filter>

<match fluentbit.apache>
  @type copy

        <store>
                @type stdout
        </store>

  <store>
        @type elasticsearch
        host localhost
        port 9200
        logstash_format true
        logstash_prefix fluentbit-apache
  </store>
</match>
```

This is a fairly complex solution which has Fluentd do all the work. Also it has an unsolved issue regarding hostname:

- I let Fluentd add hostname of logsource into logsource field, as Fluent Bit doesn´t seem to do it (see issue #259)
- ParserFilter plugins removes that field. I can set "preserve_data" but it seems it would also preserve the complete log message as is, I would like that it only preserves the logsource field (I will report there)
- Also I need to a name different to "host" for logsource, as "apache" format parses HTTP Client host name already into "host" field.

Thus I suggest in case you implement this, you use name for fields and do not clash with for example standard Fluentd Syslog input plugin which uses "host" as logsource. Use something like "client_host" or "client.host" or something like that.

**Comment by nokute78** [comment]
Fluent-bit can parser apache2 log files with parsers_file like this.
The point is to use "Parsers_file" at [SERVICE] section and "parser" at [INPUT] section.

The parsers_file is https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf
It contains regexes to parse records.

```python
[SERVICE]
    Parsers_File /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/conf/parsers.conf

[INPUT]
    Name tail
    Tag  hoge
    Path /home/taka/git/oss/pull_req/fluentbit_env/fluent-bit/build/apache2.log
    Parser apache2

[OUTPUT]
    Name stdout
    Match *
```

**Comment by martin21** [comment]
nokute78: Thank you. This works

```
[SERVICE]
    Parsers_File /etc/td-agent-bit/parsers.conf

[INPUT]
    Name tail
    Tag fluentbit.apache
    Path /var/log/apache2/access.log
    Parser apache2
    DB /var/lib/fluentbit/apache-access.db
```

There is still the name clash that Apache2 parser uses `host` as field name for HTTP client host and Fluentd syslog input plugin uses `host` for the hostname of the logsource, but when I tell Fluentd forward plugin to stuff the hostname of the logsource into `logsource` this works okayish enough. I may report this name clash. (I know it can be easily fixed in that `parsers.conf` and I may have a go at it at a later time).

**Comment by martin21** [comment]
Well it would be good to have this in the documentation. There is

http://fluentbit.io/documentation/0.11/getting_started/parser.html

but it has no explaination on how these are configured (and only links to itself)

And in 

http://fluentbit.io/documentation/0.11/input/tail.html

there is no hint about parsers.

Thus reopening. I can close again and open a new issue to track it, but I think it would be easier to just rename this issue.

**Comment by nokute78** [comment]
@martin21  Thank you for testing and comments.

About documentation of parser, it follows at document repository  https://github.com/fluent/fluent-bit-docs/pull/20
It is just work in progress.

**Comment by edsiper** [comment]
Docs updated: http://fluentbit.io/documentation/0.11/parser/
