### ISSUE TITLE
config file option (-c or --config) does not work with Fluentbit Ubuntu installation

### ISSUE THREAD

**Issue by vishalbharg** [fluent/fluent-bit#2615]
## Bug Report

**Describe the bug**
Install fluent-bit from Ubuntu Software Service. It always give error :
[Warning] [config] I cannot open my_conf.conf file
Error: Configuration file contains errors. Aborting
While my_conf.conf file presented in current directory and it does not have any error.

**To Reproduce**
- Open Ubuntu Software, search fluentbit and install it. 
- Create a configure file, here I just give name my_conf.conf.
- From same directory where my_conf.conf exist. Run "fluent-bit -c my_conf.conf ".

**Expected behavior**
If I download code and build fluent-bit binary via make command. It works fine without error. Same way Ubuntu 
installed binary should work.

**Screenshots**
![fb_error](https://user-images.githubusercontent.com/59958058/94539968-89b09100-0263-11eb-923c-989c5fdf477c.png)

**Your Environment**

* Version used: 1.5.7
* Operating System and version: Ubuntu 18.04

**Additional context**

**Comment by edsiper** [comment]
what's the output of ```ls -l``` in the directory where you are running fluent-bit ?

**Comment by vishalbharg** [comment]
-rwxrwxrwx 1 user user  148 Sep 25 16:32 my_conf.conf
drwxr-xr-x 2 user user 4096 Sep 29 21:55 output

**Comment by edsiper** [comment]
please attach your config file, it says "Configuration file contains errors"

**Comment by vishalbharg** [comment]
Here is the file attached
[my_conf.zip](https://github.com/fluent/fluent-bit/files/5300583/my_conf.zip)

But same file, same command works well, when we build code ourselves using make command.  Only issue came when fluent-bit directly install on ubuntu.

**Comment by edsiper** [comment]
Looks like the file is missing an ending new line to finish the last configuration line, try this:

```
echo >> my_conf.conf
```

**Comment by vishalbharg** [comment]
Now getting
Error: Could not open configuration file. Aborting

But why it works well when we build the code on my machine?

**Comment by edsiper** [comment]
hmm get this 3 files in the same directory and give it a try (no copy paste)

- [conf.zip](https://github.com/fluent/fluent-bit/files/5300701/conf.zip)

**Comment by vishalbharg** [comment]
Same 
Error: Could not open configuration file. Aborting

**Comment by edsiper** [comment]
hmm that's weird, the basic question: can you cat that file from there ?

**Comment by vishalbharg** [comment]
yes

**Comment by edsiper** [comment]
if you run ```strace``` before the fluent-bit command line program what's the output ?

**Comment by vishalbharg** [comment]
Attached
[strace_fb.txt](https://github.com/fluent/fluent-bit/files/5307541/strace_fb.txt)

**Comment by edsiper** [comment]
ah! you are using Snap!  there is a kind of fs access restriction, checking that out...

**Comment by vishalbharg** [comment]
yes, that I can see. Installed fluentbit from ubuntu software center
![Screenshot from 2020-10-01 00-04-11](https://user-images.githubusercontent.com/59958058/94725667-c2db2500-0379-11eb-8833-0d218089436a.png)

**Comment by gagansingh355** [comment]
@vishalbharg , did you got any resolution to this?
