### ISSUE TITLE
Expose buffer and storage metrics in Prometheus

### ISSUE THREAD

**Issue by tomerleib** [fluent/fluent-bit#2620]
**Describe the solution you'd like**
I would like the option to view in Grafana the current metrics of the storage and buffers system.
When 

**Describe alternatives you've considered**
In 1.5 Storage metrics were added but they're not exported to Prometheus. 

**Additional context**

I wish to optimize the current setup, having those metrics exposed in Prometheus will help to understand how my system is behaving under stress-tests. I would like to know what is the correct buffer size to provide instead of trying to provide a higher value and hope that it will be enough.
I wish to know when I've reached the limits of MEM_BUFFER_SIZE, BUFFER_CHUNK_SIZE, and also when my storage buffer is being overloaded.

**Comment by Blobonat** [comment]
I created a quick and dirty [Fluent Bit Storage Metric Exporter](https://github.com/Blobonat/fluent-bit-storage-metric-exporter) for this reason. Maybe it can help you.
