### ISSUE TITLE
CentOS 7 repo does not provide new td-agent-bit package versions

### ISSUE THREAD

**Issue by Fil0sOFF** [fluent/fluent-bit#2622]
## Bug Report

**Describe the bug**
I'm not sure if this is the right place to report it, but the latest version available from CentOS 7 repository (https://docs.fluentbit.io/manual/installation/linux/redhat-centos) is 1.3.11, while it should be 1.5.+

**To Reproduce**
- Install td-agent-bit on CentOS 7 by following the official docs
- Alternatively, analyze the content of "primary" package list which is returned on https://packages.fluentbit.io/centos/7/repodata/repomd.xml
 
**Expected behavior**
- td-agent-bit v1.5.7 is available for installation

**Comment by edsiper** [comment]
I think your Yum repo is pointing out to the old address, this is the correct one:

https://docs.fluentbit.io/manual/installation/linux/redhat-centos#configure-yum

**Comment by Fil0sOFF** [comment]
You are right . Thank you!
