### ISSUE TITLE
Filter ordering is not preserved

### ISSUE THREAD

**Issue by neilwashere** [fluent/fluent-bit#2646]
## Bug Report

**Describe the bug**
rewrite_tag filter appears to occur before kubernetes filter despite location in file

**To Reproduce**
I have the following configuration
```
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        # drop unwanted logs from the k8s cluster components
        Name grep
        Match kube.containers.*
        Exclude $kubernetes['namespace_name'] kube-system
        Exclude $kubernetes['namespace_name'] kubernetes-dashboard

    [FILTER]
        Name rewrite_tag
        Match kube.*
        Rule $kubernetes['namespace_name'] ^(.*)$ kube.containers.$1.$TAG[4] false

    [OUTPUT]
        Name file
        Match kube.*
        Path /var/log
        # File will be the tag name
```
However, when run the following errors are seen indicating that rewrite_tag occurs before kubernetes filter
```
[2020/10/06 09:12:23] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.containers.testns.test-service-869dc7c949-zms5c_test_proxy-937e6b55ec2af6874ec30f7059f8424b2bf26953d54639e8a1db88297f61332f
[2020/10/06 09:12:23] [error] [filter:kubernetes:kubernetes.0] incoming record tag (kube.containers.testns.) is shorter than kube_tag_prefix value (kube.var.log.containers.), skip filter
```
- Steps to reproduce the problem:
run above config in k8s/minikube

**Expected behavior**
I expected the kubernetes filter to work first
Then have some log values excluded
Then have the remaining logs re-tagged
Then one output file per remaining container with the namespace as a delimited part of the tag

**Your Environment**

* flb 1.5.6
* minikube 1.5.1 k8s 1.16.1
* running on ubuntu 18.04

**Additional context**
My intention is to eventually define different output targets per k8s namespace. My first attempt is to simply try to make the namespace part of the tag such that I can match on the namespace explicitly (or dynamically)

**Comment by edsiper** [comment]
Your kubernetes filter is catching the re-emitted records since the matching rule is ``` kube.*```, you have to restrict it only for the data coming from the Tail section (e.g: ```kube.var.*```)
