### ISSUE TITLE
Add command line option to validate configuration file without running fluent bit

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#2667]
There are use cases where it would be nice to validate the configuration file without actually running fluent bit and consuming logs.

Something like:

```
./bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf --validate
```

The exit code for Fluent Bit would then tell you if the config was valid or not (may be print a message too).

**Comment by fujimotos** [comment]
> The exit code for Fluent Bit would then tell you if the config was valid or not (may be print a message too).

Proably https://github.com/fluent/fluent-bit/pull/2179?

**Comment by fujimotos** [comment]
> The exit code for Fluent Bit would then tell you if the config was valid or not (may be print a message too).

Probably the patch #2179 (from @kangaechu) will resolve this.

**Comment by prithviramesh** [comment]
would also be nice to expose some sort of library that we can use to validate the config **without attempting to run fluent-bit at all**
