### ISSUE TITLE
New metrics for ingestion failures.

### ISSUE THREAD

**Issue by one1zero1one** [fluent/fluent-bit#2674]
**Is your feature request related to a problem? Please describe.**

When dealing with very high throughput > (20k/s) fluent-bit can encounter issues that result in some entries not being ingested.

 The issues are observable only in the fluent bit won logs, for example: 

- long lines:
```
[2020/10/12 12:26:37] [ warn] [input:tail:tail.0] file=/var/log/containers/container.log have long lines
```
- maxed out buffers:
```
 [2020/10/12 12:23:16] [ warn] [input] tail.0 paused (mem buf overlimit)
 [2020/10/12 12:23:17] [ info] [input] tail.0 resume (mem buf overlimit)
```
Both such cases are causing entries to be missed, but there is no metric that can be used to monitor/alert for the operator to ensure as much as possible the ingestion.

All metrics are that have the tail plugin as a label value (asking prometheus) ```count({name="tail.0"}) by (__name__)```

```
fluentbit_input_files_opened_total{}
fluentbit_input_files_rotated_total{}
fluentbit_input_records_total{} 
fluentbit_input_bytes_total{} 
fluentbit_input_files_closed_total{}
```

However none have any variation based on the failures caused by buffer or long lines.

**Describe the solution you'd like**

At minimum: 
- a basic generic counter metric that counts the amount of _warn|info|error_ log entries of fluentbit.
Ideal (per tail plugin): 
- a metric that logs the count of long lines skipped.
- a metric that counts memory buffer overlimit encounters.

**Describe alternatives you've considered**

I'm considering using a second fluentbit ingesting the logs of the main fluentbit, passing that info over to fluentd where I use the prometheus plugin to compute the metrics.

**Additional context**

One of the main concern when operating fluent pipelines is ensuring logs are not dropped, at minimum having visibility over the blind spots where logs are dropped.

**Comment by one1zero1one** [comment]
This was handled by switching `fluent-bit` from a `DaemonSet` to a sidecar pattern such that the very high throughput pods had each a `fluent-bit` instance.

While this does not solve the problem (visbility of the intestion failures) it most certainly reduces the pressure.

**Comment by agup006** [comment]
Hey @one1zero1one, glad to hear that changing to a sidecar pattern was helpful. Also good to see which metrics would be useful to expose. Our next version of fluent bit 1.7.0 (coming in next few weeks) includes multi worker and increased performance as well which should help with the traditional daemon set deployment.

happy to chat about it in more detail if you are interested
