### ISSUE TITLE
Customizing blob path in azure_blob output plugin

### ISSUE THREAD

**Issue by acidmind** [fluent/fluent-bit#2687]
Now we using fluent.d for storing Kubernetes pods logs in Azure blobs with following config
  path                     %Y/%-m/%-d/%-H/
  azure_object_key_format  %{path}%{time_slice}_%{index}.gz
  time_slice_format        %Y%m%d%H%M
This config makes me separate blob objects by path (for example 2020/10/14/5/202010140440_1.gz).
Is there any way to do somethink like this in fluent-bit azure_blob plugin?

The next one is fluent.d now aggregate logs flom all pods in one namespace to one blob. 
Is it possible to realise by fluent-bit?

Thanks a lot!

**Comment by pushkargr** [comment]
+1 For the request above. There is already support for custom key path for S3 (https://docs.fluentbit.io/manual/pipeline/outputs/s3#s3-key-format-and-tag-delimiters) , can the same be ported to Azure Blob Storage?

**Comment by shilpi5** [comment]
Any update on this ? Does fluent-bit support path customisation as it is done in S3 output from fluent-bit?

**Comment by linuraj** [comment]
Hello Team,

Are we supporting customization for the `path` field? 

Thanks
