### ISSUE TITLE
[kube-filter] StatefulSets have meta permanently cached

### ISSUE THREAD

**Issue by dshackith** [fluent/fluent-bit#2690]
**Is your feature request related to a problem? Please describe.**
When using statefulSets, the pod_name and namespace will not change on a new deployment, even though the metadata might change. This will cause fluent-bit to cache the meta for only the initial deployment. This means that changes to annotations and labels will not be reflected in logs, and if these are used for log processing upstream, the results may be unexpected.

**Describe the solution you'd like**
There should be some other data used to either expire local cache (eg. a TTL record or timestamp), or some other fields used for key pair that would invalidate the cached meta when a new deployment occurs.

**Describe alternatives you've considered**
At the moment the solution is to roll the fluent-bit pods to clear the local caches. Changing pod_name or namespace for a statefulSet is impractical.

**Additional context**
We use fluent-bit daemonSet to collect logs and forward to Fluentd for processing and aggregation. We rely on the kubernetes metadata that is added by fluent-bit for some of that processing:
We use an annotation to set a custom logging topic for Fluentd to use when sending logs to Kafka. For most workloads, if a team needs to update their topic, a redeploy is sufficient. We have a search infrastructure team that leverages statefulSets and they also sometimes need to update their logging topic, but fluent-bit does not pick up the change.

**Comment by dshackith** [comment]
This is still an ongoing concern for us

**Comment by szpak** [comment]
We also experience that problem. Please re-open.

**Comment by thanhiro** [comment]
A big problem for us too.

**Comment by abealsaleh** [comment]
Please reopen. I can't turn off logging for pods in a statefulset because the annotations are cached (pods now have fluentbit.io/exclude: "true" but old metadata is cached.)
