### ISSUE TITLE
Official Windows build for 1.6.1 does not support built-in HTTP server

### ISSUE THREAD

**Issue by swisspol** [fluent/fluent-bit#2696]
## Bug Report

**Describe the bug**
`HTTP_Server   On` has no effect using Windows official build of Fluent Bit 1.6.1

**To Reproduce**
Use this config file and start Fluent Bit:
```
[SERVICE]
    HTTP_Server   On

[INPUT]
    Name         winlog
    Channels     System,Application,ThreatStack
    DB           winlog.db

[OUTPUT]
    Name            es
    Match           *
    Host            <REDACTED>
    Port            80
    Retry_Limit     5

```

The log indicates that the HTTP server is not started:
```
PS C:\FluentBit> .\fluent-bit.exe -c .\fluent-bit.conf
Fluent Bit v1.6.1
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/10/17 07:44:11] [ info] [engine] started (pid=6324)
[2020/10/17 07:44:11] [ info] [storage] version=1.0.6, initializing...
[2020/10/17 07:44:11] [ info] [storage] in-memory
[2020/10/17 07:44:11] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/10/17 07:44:12] [ info] [sp] stream processor started
[2020/10/17 07:44:41] [engine] caught signal (SIGINT)
[2020/10/17 07:44:41] [ info] [input] pausing winlog.0
[2[2020/10/17 07:44:41] [error] [C:\projects\fluent-bit-2e87g\src\flb_utils.c:339 errno=0] No error
020/10/17 07:44:41] [ info] [input] pausing tail.1
[2020/10/17 07:44:41] [error] [C:\projects\fluent-bit-2e87g\src\flb_utils.c:339 errno=0] No error
[2020/10/17 07:44:41] [ warn] [engine] service will stop in 5 seconds
[2020/10/17 07:44:46] [ info] [engine] service stopped
```

**Expected behavior**
HTTP server works

**Your Environment**
"Windows_Server-2019-English-Full-ContainersLatest-2020.04.15" AMI on AWS

**Comment by edsiper** [comment]
cc: @fujimotos

**Comment by swisspol** [comment]
I realized after looking at the docs that the HTTP Server is not enabled by default for Windows when building from source, but I think it should really be enabled in the official builds:
1) All the docs mention monitoring as something working out of the box, but this requires the HTTP server, so it's not true for Windows
2) HTTP server is enabled by default in the official Docker images
3) Building fluent-bit for Windows is non-trivial and having to host and rollout your own executable is quite annoying

PS: Thanks for an awesome product :)

**Comment by fujimotos** [comment]
> HTTP_Server On has no effect using Windows official build of Fluent Bit 1.6.1

@swisspol We need a bit more work to support HTTP monitoring on Windows.

The big picture here is that HTTP server requires a functional Windows
port of Monkey HTTP server (monkey/monkey), but we're not getting there yet.

Probably we can work on this task after the persistent file chunk
support https://github.com/fluent/fluent-bit/pull/2632#issuecomment-703254445, considering that HTTP monitiroing feature is
being requested by several users.

**Comment by swisspol** [comment]
Thanks for the info! In the meantime you may want to update the docs to indicate HTTP monitoring is not available on Windows - it nah save people time

**Comment by fujimotos** [comment]
> In the meantime you may want to update the docs to indicate HTTP monitoring is not available on Windows - it nah save people time

Should be resolved by fluent/fluent-bit-docs#405.

**Comment by lacksfish** [comment]
That's hella skuffed. Can we expect a fix for this soonish?

Any other way of having fluentbit report health status to prometheus apart from the nonfunctional API?

**Comment by lacksfish** [comment]
Maybe a possible easy remedy would be to have an `[Output]` option for a `File` regarding fluentbit health and plugin stats?

https://docs.fluentbit.io/manual/pipeline/outputs/file

It seems fairly doable to write the internal health files into either a JSON or prometheus formatted file. All the code, beside writing to file (overwriting previous content preferred over append), should already exist in the HTTP API code.

If that approach would be interesting, I could dig into the codebase and see if I can help put this functionality together.

**Comment by fujimotos** [comment]
> That's hella skuffed. Can we expect a fix for this soonish?

@lacksfish The full support will take several weeks at least.

I'm currently working on File Chunk support for Windows #1694;
Probably I can work on it after that.

> Maybe a possible easy remedy would be to have an [Output] option for a File regarding fluentbit health and plugin stats?

I think the best way to go is to add a new input plugin `in_monitor_agent`
that emits health metrics as events. Fluentd provies [a similar plugin by default](https://docs.fluentd.org/input/monitor_agent),
so it should make a good sense for Fluent Bit to have one.

**Comment by qingling128** [comment]
Hi @fujimotos - Any update regarding this feature request?

**Comment by fujimotos** [comment]
@qingling128 I'm currently planning to work on this task in the next v1.8 dev cycle.

**Comment by qingling128** [comment]
Thanks for the heads up! We'll plan our work accordingly.

**Comment by qingling128** [comment]
I was about to draft a PR to update the doc at https://docs.fluentbit.io/manual/administration/monitoring, but it seems like the master branch has been updated already: https://github.com/fluent/fluent-bit-docs/commit/7bdc708e079289eec6ef1b03fcb5327bf79889d9. Any idea why the doc page is not updated?

**Comment by fujimotos** [comment]
@qingling128 My understanding is that the master branch points to 

https://docs.fluentbit.io/manual/v/master/administration/monitoring

while `1.6` branch points to:

https://docs.fluentbit.io/manual//administration/monitoring

My guess is that the commit was merged but not cherry-picked to `v1.6` branch,
so it's not appearing on the current page.

**Comment by qingling128** [comment]
Ah I see. That makes sense. Thanks for checking!

**Comment by vahric** [comment]
Any change to have this feature on 1.7 version ?

**Comment by gillg** [comment]
Still not present in 1.7, it would be very great to have it.

**Comment by edsiper** [comment]
Fixed by https://github.com/fluent/fluent-bit/commit/6efe5c9b0974b7935d28b6f49270bc15be907bbf , this will be part of Fluent v1.8 release.
