### ISSUE TITLE
version of fluentbit in image fluent/fluent-bit:1.6.1 is wrong

### ISSUE THREAD

**Issue by jmw847** [fluent/fluent-bit#2707]
## Bug Report

**Describe the bug**

In our Kubernetes cluster we use Fluentbit, Loki and Grafana.
Since the fluentbit image 1.6.1 contains a Loki output plugin, we wanted to use the fluentbit image 1.6.1.
When I run the image with version 1.6.1 locally, the logs say that it is fluentbit 1.6.0.

Is it possible that the image was tagged incorrectly because the version in the logs is wrong ?

**To Reproduce**
- Example log message if applicable:
```
Fluent Bit v1.6.0
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/10/20 09:34:52] [ info] [engine] started (pid=1)
[2020/10/20 09:34:52] [ info] [storage] version=1.0.6, initializing...
[2020/10/20 09:34:52] [ info] [storage] in-memory
[2020/10/20 09:34:52] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/10/20 09:34:52] [ info] [sp] stream processor started
^C[2020/10/20 09:34:55] [engine] caught signal (SIGINT)
[2020/10/20 09:34:55] [ info] [input] pausing cpu.0
```
- Steps to reproduce the problem:

`
docker run -it fluent/fluent-bit:1.6.1
`

**Expected behavior**
I expect the version of fluentbit to be 1.6.1 when I use the docker image with version 1.6.1

**Screenshots**

**Your Environment**

* Version used: fluent/fluent-bit:1.6.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins: 

**Additional context**

**Comment by edsiper** [comment]
thanks for reporting this issue. It has been fixed.
