### ISSUE TITLE
Add "key_value" line format for loki plugin

### ISSUE THREAD

**Issue by jcdauchy-moodys** [fluent/fluent-bit#2711]
**Is your feature request related to a problem? Please describe.**
Original Grafana implements a "key_value" format which is more readable than JSON format

**Describe the solution you'd like**

When sending the message, concatenate the key=value with a space in between.

https://grafana.com/docs/loki/latest/clients/fluentbit/

![2020-10-20 16_29_53-Grafana](https://user-images.githubusercontent.com/56868940/96600960-c9fab080-12f1-11eb-84a1-d23527d9fb2c.png)

**Additional context**
It helps reading the message in Grafana UI.

**Comment by edsiper** [comment]
This feature has been added as part of v1.6.5:

- https://fluentbit.io/announcements/v1.6.5/

Note: formatting of nested maps and arrays is not pretty clear in terms of requirements, for hence if you find an issue please open a new ticket with further details.
