### ISSUE TITLE
Syslog output plugin should be available to use json object as a message for syslog

### ISSUE THREAD

**Issue by ashum81** [fluent/fluent-bit#2717]
**Is your feature request related to a problem? Please describe.**
I am sending a json log to syslog collector.
It's simple. I use tail input plugin without parsing json, get string and use syslog output plugin.

Now I need to remove some keys from json before sending because it exceeds syslog message size.
If I apply parser json and then apply filter record_modifier remove_key to json log I receive an object, and syslog can not use it to put in a message field. 

**Describe the solution you'd like**
Syslog output plugin should be available to use json object as a message for syslog.

**Comment by reddysrikesh** [comment]
I am trying to do the same thing, but syslog server keeps dropping tcp connection. Could be because of mismatch of formats. Can you give your fluent-bit-config ConfigMap and syslog.conf ?

**Comment by ashum81** [comment]
My fluentbit.conf:
```
[SERVICE]
    Parsers_File        /fluent-bit/etc/parsers.conf
    storage.path        /fluent-bit/buffer
    storage.type        filesystem

[INPUT]
    Name                tail
    Path                /gitlab_logs/gitlab-rails/production_json.log
    Path_Key            sourceFile
    DB                  /fluent-bit/db/logs.db
    Tag                 gitlab.rails
    storage.type        filesystem

[FILTER]
    Name                record_modifier
    Match               gitlab.rails
    Record hostname     git01
    Record appname      gitlab
    Record procid       production_json

[Output]
    name                syslog
    match               gitlab.rails
    host                log01.server.com
    port                514
    mode                udp
    syslog_format       rfc5424
    syslog_hostname_key hostname
    syslog_appname_key  appname
    syslog_procid_key   procid
    syslog_message_key  log
```
This is my log:
`{"method":"HEAD","path":"/-/readiness","format":"html","controller":"HealthController","action":"readiness","status":200,"duration":0.89,"view":0.21,"db":0.0,"time":"2020-10-31T10:04:45.584Z","params":[],"remote_ip":null,"user_id":null,"username":null,"ua":null,"queue_duration":null,"correlation_id":"EbLlyqPciI6","cpu_s":0.004744530999232666}`

Now I am sending it as a string without parsing.
Sometimes the field "params" has a huge size and does not fit to 2048 bytes of syslog message field. And such messages are lost.
So I need to remove a field "params" at all.
I try to apply the parser "docker" to log message. Get an obect. Then apply filter "record_modifier"and use "remove_key params". Get an obect again.
And now I can't send it to syslog output plugin.

**Comment by mareklubinski** [comment]
we're having exactly the same issue, so any help to get this fixed is highly appreciated, thank you! :)
