### ISSUE TITLE
TCP input doesn't work properly when there are mixed JSON and non-JSON logs

### ISSUE THREAD

**Issue by wtchangdm** [fluent/fluent-bit#2719]
## Bug Report

**Describe the bug**
Hi, I am considering using TCP as input to send our logs.

When using `tcp` input with `Format` set to `JSON`, it works fine with JSON-only logs.
However, if there are both JSON and non-JSON logs, fluent-bit doesn't seem to work as expected.

At first, I thought that's because it doesn't support non-JSON content, but if it's the case, the following log file shouldn't have more than one line of JSON.

**To Reproduce**

- Rubular link if applicable: **N/A**
- Example log message if applicable:
```
{"count":2795}
not json
```
- Steps to reproduce the problem:

1. test.sh

```bash
#!/bin/bash

count=0

while [[ count -lt 10000 ]]; do
  echo "{\"count\": $count}"
  echo 'not json'
  ((count++))
done
```

2. Create a **log.txt**:

```bash
$ touch log.txt
```

3. Create **fluent-bit.conf**:

```
[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        7777
    Chunk_Size  32
    Buffer_Size 64
    Format      JSON
    Tag         input

[OUTPUT]
    Name        file
    Path        /var/log/test/
    File        test.log
    Match       *

# This doesn't seem to work properly as well
# [OUTPUT]
#     Name        stdout
#     Match       *
```

4. Execute fluent-bit:

```bash
$ docker run --rm -p 7777:7777 -v $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro -v $PWD/log.txt:/var/log/test/test.log fluent/fluent-bit:1.6.1
```

5. Sending logs

```bash
$ chmod +x test.sh
$ ./test.sh | nc localhost 7777
```

**Expected behavior**

All json line generated at `echo "{\"count\": $count}"` should be saved in the log file.

It only saved the following lines:
```
input: [1603372635.691357000, {"count":921}]
input: [1603372635.770651500, {"count":2086}]
input: [1603372635.783400000, {"count":2261}]
input: [1603372635.787590000, {"count":2310}]
input: [1603372635.805267400, {"count":2491}]
input: [1603372635.810647100, {"count":2516}]
input: [1603372635.835018000, {"count":2687}]
input: [1603372635.837986200, {"count":2703}]
input: [1603372635.840412100, {"count":2727}]
input: [1603372635.850850200, {"count":2795}]
input: [1603372635.852998900, {"count":2811}]
input: [1603372636.110232200, {"count":5886}]
input: [1603372636.250780300, {"count":7796}]
input: [1603372636.256571000, {"count":7846}]
input: [1603372636.269567600, {"count":7950}]
input: [1603372636.351309100, {"count":9121}]
```

However, commenting out the `echo 'not json'` line works as expected.

**Screenshots**

N/A

**Your Environment**

* Version used: 1.6.1
* Configuration: _Please check step 3 above_
* Environment name and version (e.g. Kubernetes? What version?):
  - macOS 10.15.7 (19H2) with Docker engine 19.03.13
  - Amazon EKS 1.15
* Server type and version: **N/A**
* Operating System and version: macOS 10.15.7（19H2)
* Filters and plugins:
  - Input: `tcp`
  - Output: `file` and `stdout`

**Additional context**

I am trying to use fluent-bit as a sidecar container in Kubernetes. It's used for a special purpose so we will not let cluster-level log shippers collect these logs.

Since our worker nodes are regular EC2 with EBS attached, directly write log files will likely consume the EBS burstable credits when under heavy loading, so I'd like to use the TCP server as an input method and then send to specified destinations.

But this context seems irrelevant as it can be reproduced in a relatively simple environment.

**Comment by wtchangdm** [comment]
I think this is still worth a check?

**Comment by nokute78** [comment]
Is your log Jsonl ?
If so, this pipeline may help you.

1. in_tcp receives raw text and it converts `{"log":"{"count": 9992}"}` or `{"log":"not json"}`
2. filter_parser parses as json, then the record will be `{"count":9992}`. `'not json'` line is not parsed because it is not json format.
3. filter_grep excludes if the record has `log` key. It means not parsed records `{"log":"not json"}` are removed.
4. out_file outputs file.

```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name tcp
    Listen 127.0.0.1
    Port 7777
    Chunk_Size 32
    Buffer_Size 64
    Format none

[FILTER]
    Name parser
    Match *
    Parser json
    Key_Name log

[FILTER]
    Name grep
    Match *
    Exclude log .+

[OUTPUT]
    Name File
```

**Comment by wtchangdm** [comment]
@nokute78 Yes, it's json line.

It was an experiment using `./someapp 2>&1 | nc localhost 7777` to pipe logs to flb directly without logs landing on disk.

I will test your suggestion when have time. Thanks!
