### ISSUE TITLE
Enrich record with namespace labels and annotations

### ISSUE THREAD

**Issue by mxmorin** [fluent/fluent-bit#2724]
**Describe the solution you'd like**
In the kubernetes filter add namespace_labels and namespace_annotation parameters to enrich record with namespace labels or annotation like fluentd plugin kubernetes_metadata_filter

**Comment by mmerickel** [comment]
Ran into this as well as I was comparing fluent-bit to fluentd... the namespace labels are critical for my workflow so it'd be great to have an option to turn them on. In fluentd with the kubernetes_metadata_filter they show up in a log record in the `kubernetes.namespace_labels` map.

**Comment by beth2016** [comment]
I need this as well.

**Comment by jangraefen** [comment]
We would also like to have this feature. Right now, this forces us on Fluentd, eventhoug we would much rather use Fluentbit.

**Comment by mxmorin** [comment]
Any work on this issue ?

**Comment by xiaoluhong** [comment]
Any work on this issue ?
