### ISSUE TITLE
Intput forward command line is not works

### ISSUE THREAD

**Issue by swkwon** [fluent/fluent-bit#2727]
## Bug Report

**Describe the bug**
I tried practicing `$ fluent-bit -i forward://0.0.0.0:9090 -o stdout` but an error occurs.
Same goes for TCP plugin.

**To Reproduce**
- Rubular link if applicable: https://docs.fluentbit.io/manual/pipeline/inputs/forward
- Example log message if applicable:
```
Error: Invalid input type. Aborting
```
- Steps to reproduce the problem:

**Expected behavior**
Forward plugin is should be bound to "0.0.0.0:9090".

**Your Environment**

* Version used: 1.6.2, 1.5.7
* Configuration:
* Environment name and version docker 19
* Server type and version: 
* Operating System and version: centos7, windows10
* Filters and plugins:

**Comment by snoopdouglas** [comment]
Can reproduce this. The following command [from the docs](https://docs.fluentbit.io/manual/pipeline/inputs/tcp) doesn't work:

```bash
fluent-bit -i forward://0.0.0.0:9090 -o stdout
```

**Comment by snoopdouglas** [comment]
This never got fixed as far as I know, don't close.

**Comment by nokute78** [comment]
Workaround is like this.
`listen` property is for ip address / hostname, `port` property is for port.
TCP also works with such properties.

```
fluent-bit -i forward -p listen=localhost -p port=9090 -o stdout
```
