### ISSUE TITLE
docker_mode does not work for our docker logs format

### ISSUE THREAD

**Issue by 123BLiN** [fluent/fluent-bit#2733]
## Bug Report

**Describe the bug**
Fluentbit does not recombine docker logs in docker_mode

**To Reproduce**
- Example split docker log in json fomat 
```
{"log":"{\"@timestamp\":\"2020-10-28T15:53:14.460060-04:00\",first part of the huge one line JSON here\n","stream":"stderr","time":"2020-10-28T19:53:13.080198941Z"}
{"log":"second part of huge one line JSON here\n","stream":"stderr","time":"2020-10-28T19:53:13.080332682Z"}
{"log":"last part of huge one line JSON here\"}\n","stream":"stderr","time":"2020-10-28T19:53:13.080332682Z"}
```
- Steps to reproduce the problem:

**Expected behavior**
I expect one event combined of these 3 lines

**Your Environment**

* Version used: 1.6.1
* Configuration: banzai cloud logging-operator
* Environment name and version (e.g. Kubernetes? What version?): Kops 1.16
* Server type and version: AWS EC2
* Operating System and version: Ubuntu 18.04
* Filters and plugins: default

**Additional context**
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    storage.path  /buffers

[INPUT]
    Name         tail
    Buffer_Chunk_Size  500KB
    Buffer_Max_Size  5MB
    DB  /tail-db/tail-containers-state.db
    Docker_Mode  On
    Mem_Buf_Limit  5MB
    Parser  docker
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  On
    Tag  kubernetes.*

[FILTER]
    Name        kubernetes
    Annotations  Off
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Tag_Prefix  kubernetes.var.log.containers
    Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_URL  https://kubernetes.default.svc:443
    Match  kubernetes.*
    Merge_Log  Off

[OUTPUT]
    Name          forward
    Match         *
    Host          logging-operator-fluentd.logging.svc
    Port          24240
    
    Retry_Limit   False
```
@sumo-drosiek Sorry for pinging you directly but as I understand from other issues you were working on this feature, I have a question regarding test log files here https://github.com/fluent/fluent-bit/tree/master/tests/runtime/data/tail/log
in our case we have new line character at the end of every split log lines, but in test log files "\n" is only present at the end of the split event. Could it be that assumtions about docker split logic are wrong on your side or is it depends on docker version or so?
Sorry again if my assumtion is wrong and logic behind docker_mode is correct.

**Comment by sumo-drosiek** [comment]
Hi @123BLiN,

As I know and remember the newline `\n` is the only way to figure out if line is split or not.

So, I have one question which can help with investigation/reproduction of the issue:
Do the `docker/kubectl logs` show this long line as one or multiple lines?

**Comment by 123BLiN** [comment]
@sumo-drosiek yep, the same result with kubectl logs - it breaks stream with new lines :angry: 
We have `Docker version 18.09.9, build 039a7df9ba`
it seems that the only way to get full event in elastic is to ask developers to add to stdout/err logs some attributes of the start and the end of the event and combine log based on them and also removing trailing new lines.

thank you!

Closing, but maybe it can be helpful for others to add some info about this to the docs.

**Comment by sumo-drosiek** [comment]
@123BLiN No problem, happy to help :)
