### ISSUE TITLE
unable to forward logs to syslog server using syslog output plugin

### ISSUE THREAD

**Issue by reddysrikesh** [fluent/fluent-bit#2736]
I am trying to forward logs to syslog server using syslog output plugin(fluent bit version 1.5.6) using below output conf.

name                 syslog
        match                *
        host                 127.0.0.1  
        port                 601
        mode                 tcp
        syslog_format        rfc5424
        #syslog_maxsize       2048
        syslog_procid_key    procid
        syslog_msgid_key     msgid
        syslog_message_key   message

syslog server keeps dropping connection with this error. Any idea what is going ?

Oct 29 19:07:07 syslog-ng-577d449f7c-c4p9s syslog-ng[1]: Invalid frame header; header=''
Oct 29 19:07:07 syslog-ng-577d449f7c-c4p9s syslog-ng[1]: Syslog connection closed; fd='19', client='AF_INET(100.98.233.240:37202)', local='AF_INET(0.0.0.0:601)'

I trie d with RFC3164 too, same problem.

**Comment by L4rS6** [comment]
@reddysrikesh Were you able to solve that problem? I'm running into the same issue.
