### ISSUE TITLE
syslog plugin to use

### ISSUE THREAD

**Issue by reddysrikesh** [fluent/fluent-bit#2737]
I am trying to forward Kubernetes container logs to syslog server using fluent bit, which plugin do I need to use to parse incoming messages? I tried both RFC3164 and RFC5424 formats via tcp/udp, can't seem to get it working. I am using syslog-ng. Here is my syslog-ng.conf file:

 @version: 3.26
    #@include "scl.conf"

    source s_local {
        internal();
    };

    source s_network {
        syslog(
           ip(0.0.0.0)
           port(601)
           transport("tcp")
        );

        syslog(
           ip(0.0.0.0)
           port(514)
           transport("udp")
        );
    };

    destination d_local {
            file("/var/log/messages");
            file("/var/log/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
    };

    log {
           source(s_local);
           source(s_network);
           destination(d_local);
    };

syslog server spits out this message in logs, which seems to indicate mismatch in format.

Oct 29 21:42:07 syslog-ng-58cc9c5878-2xccj syslog-ng[1]: Invalid frame header; header=''
Oct 29 21:42:07 syslog-ng-58cc9c5878-2xccj syslog-ng[1]: Syslog connection closed; fd='17', client='AF_INET(100.98.233.253:44116)', local='AF_INET(0.0.0.0:601)'

**Comment by czanik** [comment]
You should try the network() source: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.26/administration-guide/20#TOPIC-1430975 as the syslog() source is for RFC5424 with proper framing.
