### ISSUE TITLE
General Windows development 

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#2738]
This is the ticket to keep track of the current Windows development.

As of writing, we are in Fluent Bit v1.7.0 development phase.

**Planned Tasks**

 * #1694 Add support for filesystem storage on Windows
 * #2210 support subsecond resolution with colon (%s:%L) 
 * #2625 Support syslog-rfc5424 format in flb_strptime

**Memo**

* The current biggest task is #1694, which adds "file chunk" support
  to Windows (requested in #2351).

* The file chunk support should also enable us to use S3 plugin on
  Windows as discussed in #2632.

* The previous ticket was #960 (very long) and #2351.

**Comment by fujimotos** [comment]
Memo: The previous threads were #960 and #2351.

**Comment by nweseloh** [comment]
It is not exactly a "windows-only" issue, but we have a Windows container setup and would love to use Loki with Grafana cloud.  
fluent-bit is  the only reasonable choice for a log collector agent due to it's great windows support.  

But unfortunately, the loki output plugin does not support HTTPs & Basic Auth yet, so we have no way at all to use  the Grafana cloud-hosted Loki on Windows right now.  A fix for that would be greatly appreciated by your windows users.  #2735

**Comment by fujimotos** [comment]
> But unfortunately, the loki output plugin does not support HTTPs & Basic Auth yet, so we have no way at all to use the Grafana cloud-hosted Loki on Windows right now, see #2735. A fix for that would be greatly appreciated by your windows users.

@nweseloh Hm. So you want Loki plugin to have TLS (and Basic Auth) support
so that it can connect to cloud hosting instance.

Can you submit a new issue ticket for that task so that we can follow up?

**Comment by nweseloh** [comment]
Sure, I added a feature request in #2791.  Thanks for looking into this!

**Comment by fujimotos** [comment]
Fluent Bit v1.7 was released last month.

https://fluentbit.io/announcements/v1.7.0/

The major Windows-related topics were:

1. New filesystem chunk support (presitent log buffer in disk)
2. Port `out_s3` to Windows
3. Port `filter_geoip2` to Windows

Overall, "filesystem chunk support" was landed as planned, and
I observe some users already make use of the feature.

Some additional notes:

* There was a bug in the official binary builds of v1.7.x that inadvertently
   depends on OpenSSL DLLs.
* This is already fixed in HEAD by #3149 and the fix should be included in v1.7.3.

**Comment by joefreyk** [comment]
Is there a method to silently install the Windows Fluent Bit agent w/o using the ZIP file?

Thank you.

**Comment by joefreyk** [comment]
Good day. 

The documentation for the Windows agent doesn't discuss a silent installation method. After trying all of the standard switches "/?", "/q", "/qn", "/s", etc I found the switches for Nullsoft installers are "/S" and "/D". It would probably be useful to have these in the docs.

Thank you to all who create this software.
