### ISSUE TITLE
fluentbit 1.6.3 performance issues compared to 1.5.2

### ISSUE THREAD

**Issue by dengalebr** [fluent/fluent-bit#2749]
## Bug Report

We are using Fluentbit 1.5.2 which process around 7-8k EPS which forward to Splunk and recently we are trying to upgrade to fluentbit 1.6.3 as it has storage.total_limit_size which control disk usage. Only change we are doing is updating latest image and adding total_limit_size and this version stop us at 3k EPS only and fill up disk specified and stop after that.

We wanted the combination of control and throughput for shipping splunk. Are we missing anything?

**Below is our configurations:**
#Configurations:
[FILTER]
Name kubernetes
Match kube.*
Kube_Tag_Prefix kube.var.log.containers.
Kube_URL https://kubernetes.default.svc:443
Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
Keep_Log off
Merge_Log_Key log
K8S-Logging.Parser On
K8S-Logging.Exclude On

[FILTER]
fluent-bit-input.conf: "[INPUT]
Name tail
Path /var/log/containers/*.log
Parser docker
Tag kube.
Refresh_Interval 5
Mem_Buf_Limit 2G
Skip_Long_Lines On
storage.type filesystem
Buffer_Chunk_Size 128k
Buffer_Max_Size 1MB
Ignore_Older 5h
DB /tail-db/tail-containers-state.db
DB.Sync Normal
Docker_Mode On
Docker_Mode_Flush 4
Docker_Mode_Parser identify_firstline
Exclude_Path /var/log/containers/splunk-kubernetes-logging-fluent-bit.log

fluent-bit-output.conf:
[OUTPUT]
Name splunk
Match *
Host
Port >
Splunk_Token
Splunk_Send_Raw
off
TLS on
TLS.Verify off
tls.debug 1
Message_Key kubernetes
Retry_Limit False

fluent-bit-service.conf: "[SERVICE]
Flush 2
Daemon Off
Log_Level info
Parsers_File parsers.conf
storage.path /var/log/fluent-bit/
storage.sync normal
storage.checksum off
storage.backlog.mem_limit 2G
Parsers_File parsers_custom.conf

parsers.conf: |
[PARSER]
    [PARSER]
        Name identify_firstline
        Format regex
        Regex (?<log>^{"log":"\d{4}-\d{2}-\d{2}.*)

**Our Environment**

Version used: 1.5.2

Configuration: kubernetes 1.18.5

Filters and plugins: tail

We wanted to understand what we are missing in latest version of fluent-bit so we can get same throughput, we have tried out most of the parameters. 

Thank you.

**Comment by edsiper** [comment]
@dengalebr would you please try out v1.6.4 ? it was just released and comes with a sync/async setup problem for sockets, some users reported an increase of 2.5x in throughput

**Comment by dengalebr** [comment]
Thanks @edsiper, appreciate quick suggestion, This improved a lot in 1.6.4 now. we see similar behaviour like earlier version now.
