### ISSUE TITLE
Fluentbit HTTP output - send one log per http request

### ISSUE THREAD

**Issue by yorondevops** [fluent/fluent-bit#2752]
## Bug Report

**Describe the bug**

I need to forward logs via HTTP in JSON format to an HTTP endpoint that can only accept 1 log per POST, but the `HTTP` output plugin sends log lines in batches when using the JSON format, seemingly with no option to send 1 log line per request. 

**To Reproduce**
Use the following configuration:
```
[SERVICE]
    flush 2
    daemon off
    log_level debug
    
[INPUT]
    name tail
    path c:\something\*.log
    refresh_interval 2

[OUTPUT]
    name http
    match *
    host myhost
    port 1234
    uri /something/logs
    header content-type application/json
    format json
```
I have tried the `json` and `json_stream` formats from the plugin's docs, but both batch the messages (`json` incapsulates them in an array and `json_stream` separates them with commas)

**Expected behavior**

I expect/want fluentbit to send a single log per HTTP POST.
**Screenshots**

**Your Environment**

* Version used: td-agent-bit-1.6.3
* Configuration: listed above
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: Windows Server
* Filters and plugins: Using the `tail` input plugin and `HTTP` output plgin

**Additional context**

**Comment by a-thaler** [comment]
I'm having a similar problem. I want to create logs in my multiple applications in a well-defined json format whenever an audit relevant event happens. Then I want to use fluent-bit to filter the relevant audit logs, transform them into the right format and send them to the appropriate service for the audit logs. Unfortunately, this proprietary service has a simple REST API only and does not provide any bulk format.

I would not call it a bug of the http plugin but a missing feature. 
A possible solution could be to add a new format type like "json_single" which is sending one line per request. I would like to contribute that feature together with my colleagues.

@edsiper what do you think about that feature? Does it sound meaningful and you would accept such a contribution?
Any hints on where to look in the sources in regards to switching the retry logic from a chunk-based level to a log entry based one? I saw the same json format types in the stdout plugin, that probably should be adjusted as well to be consistent?

**Comment by erichorwath** [comment]
push

**Comment by a-thaler** [comment]
In fluentd it looks like that you can specify the buffer per output plugin and with that you can set the [`chunk_limit_records`](https://docs.fluentd.org/configuration/buffer-section#buffering-parameters) to `1` potentially solving the problem.
Is there anything similar planned for fluent-bit?

**Comment by ciastooo** [comment]
Bump, this would be really useful for my case

**Comment by apratina** [comment]
Can we get some update on this? If there is a way to do this today?
Otherwise can we consider this as a feature request. It would provide good flexibility to integrate with custom http server.

**Comment by apratina** [comment]
push

**Comment by a-thaler** [comment]
unstale

**Comment by juzy** [comment]
I have the same problem, did you solve it?

**Comment by jacobnollette** [comment]
Did we ever figure this out?

**Comment by DMaxter** [comment]
I am also facing a similar issue

Is there an option to prevent grouping the logs?

**Comment by baonq-me** [comment]
Same issue here

**Comment by agup006** [comment]
Happy to reopen this, though we don’t have someone scoped to this asap. Maybe we could have this under a webhook plugin type option?

**Comment by DMaxter** [comment]
Any updates here?

**Comment by sergeye-boltinc** [comment]
Any updates?
This issue also affects the Splunk output plugin while using Splunk_Send_Raw On

**Comment by makserik** [comment]
So is this abandoned?

**Comment by CauchY75** [comment]
Is there any progress on the issue?

**Comment by garrington** [comment]
This still seems to be an issue.

**Comment by acamara-res** [comment]
Is there any progress on the issue?

**Comment by jjgrinwis** [comment]
having the same problems Using some lua scripts to transform data but endpoint expects single json not combined in any shape or form.

**Comment by pgr-matt-barr** [comment]
+1 FWIW

**Comment by pikhovkin** [comment]
normal fluentd has the same issue
