### ISSUE TITLE
fluent-bit sporadically fails with EINVAL 

### ISSUE THREAD

**Issue by vbichov** [fluent/fluent-bit#2753]
## Bug Report

**Describe the bug**
fluentbit is failing with SIGSEGV, at this point all I have is the error message as the binary is compiled without debug flags.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2020/11/08 12:39:50] [ info] [input:storage_backlog:storage_backlog.2] queueing app_logs:1-1604748656.798383295.flb
[2020/11/08 12:39:50] [ warn] [input chunk] no matching route for backoff log chunk 1-1604748656.798383295.flb
[2020/11/08 12:39:50] [ info] [input:storage_backlog:storage_backlog.2] queueing app_logs:1-1604748656.811630919.flb
[2020/11/08 12:39:50] [ warn] [input chunk] no matching route for backoff log chunk 1-1604748656.811630919.flb
[2020/11/08 12:39:50] [ info] [input:storage_backlog:storage_backlog.2] queueing app_logs:1-1604748656.814257242.flb
[2020/11/08 12:39:50] [ warn] [input chunk] no matching route for backoff log chunk 1-1604748656.814257242.flb
[2020/11/08 12:39:52] [ info] [input:tail:app_logs] inotify_fs_add(): inode=15253799 watch_fd=36 name=/var/log/api-gateway-server/agc_logstash_json.log
[2020/11/08 12:39:53] [ info] [input:tail:app_logs] inotify_fs_add(): inode=15253819 watch_fd=37 name=/var/log/cloud-mt-server/cloud-mt-server_logstash_json.log
[2020/11/08 12:39:55] [ info] [output:s3:app_logs] Successfully initiated multipart upload for /fluentbit-app-logs-java/dc1/ip-10-85-63-92.eu-west-1.compute.internal/2020/11/08/12/39/55/app_logs.api-gateway-server.agc_logstash_json.log, UploadId=Rq1exK2eHiOXYjbltxg6bbkpCUcW040r.2RuXXCC7.1dCNiscbHr_nYI00Rlhv5yA5PTW6fh1PyBauh3VY4d1kA39mrLuq1hUJmbIh_LgA.Fom.MFftV.fhMXBD2yD4p
[2020/11/08 12:39:56] [ info] [output:s3:app_logs] UploadPart http status=200
[2020/11/08 12:39:56] [ info] [output:s3:app_logs] Successfully uploaded part #1 for /fluentbit-app-logs-java/dc1/ip-10-85-63-92.eu-west-1.compute.internal/2020/11/08/12/39/55/app_logs.api-gateway-server.agc_logstash_json.log, UploadId=Rq1exK2eHiOXYjbltxg6bbkpCUcW040r.2RuXXCC7.1dCNiscbHr_nYI00Rlhv5yA5PTW6fh1PyBauh3VY4d1kA39mrLuq1hUJmbIh_LgA.Fom.MFftV.fhMXBD2yD4p, ETag=789b2f6c3854a57f063b71ad4989bc15
[lib/chunkio/src/cio_file.c:899 errno=22] Invalid argument
[2020/11/08 12:39:56] [engine] caught signal (SIGSEGV)
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)%
```
- Steps to reproduce the problem: the issue seems to be sporadic

**Your Environment**

* Version used: 1.6.3
* Configuration: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: fluentbit
  labels:
    k8s-app: fluentbit
data:
  fluent-bit.conf: |-
    [SERVICE]
        Log_Level                 info
        Daemon                    off
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 2020
        mem_buf_limit             2G
        storage.path              /var/lib/fluentbit/storage
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 250M
        Parsers_File              /opt/bitnami/fluent-bit/conf/parsers.conf
        storage.metrics           on
        tls.verify                false
        tls                       off

    [INPUT]
        name                tail
        path                /var/log/*/*_logstash_json.log,/var/log/*/identification-server.log,/var/log/*/authorization-server.log
        Alias               app_logs
        parser              json
        Path_Key            filename
        Exclude_Path        *.gz,*.zip,*k8s-canary-ds*
        Tag                 app_logs.*
        Refresh_Interval    5
        Buffer_Max_Size     64k
        Skip_Long_Lines     On
        DB                  /var/lib/fluentbit/logstash_json.db
        DB.locking          true
        Mem_Buf_Limit       300M
        storage.type        filesystem

    [INPUT]
        name                tail
        path                "/var/log/envoy/ingress.log,/var/log/envoy-dispatcher/egress.log,/var/log/envoy-dispatcher/egress.json
        parser              json
        Path_Key            filename
        Alias               envoy_logs
        Exclude_Path        *.gz,*.zip
        Tag                 envoy_logs.*
        Refresh_Interval    5
        Buffer_Max_Size     64k
        Skip_Long_Lines     On
        DB                  /var/lib/fluentbit/envoy_logs.db
        DB.locking          true
        Mem_Buf_Limit       400M
        storage.type        filesystem

    [FILTER]
        Name    lua
        Match   app_logs.*
        script  /opt/bitnami/fluent-bit/conf/transforms.lua
        call    fix_app_log

    [FILTER]
        Name parser
        Match envoy_logs.*
        Key_Name request_uri
        Parser split_question_mark
  
    [FILTER]
        Name    lua
        Match   envoy_logs.*
        script  /opt/bitnami/fluent-bit/conf/transforms.lua
        call    fix_app_log

    [OUTPUT]
        Name                         s3
        Alias                        app_logs
        Match                        app_logs.*
        bucket                       fluentbit-logs
        region                       us-east-1
        total_file_size              50M
        upload_timeout               30s
        store_dir                    /var/lib/fluentbit/s3
        s3_key_format                /fluentbit-app-logs-java/${DC}/${NODE_NAME}/%Y/%m/%d/%H/%M/%S/$TAG
        s3_key_format_tag_delimiters .-_

    [OUTPUT]
        Name                         s3
        Alias                        envoy_logs
        Match                        envoy_logs.*
        bucket                       fluentbit-logs
        region                       us-east-1
        total_file_size              50M
        upload_timeout               30s
        store_dir                    /var/lib/fluentbit/s3
        s3_key_format                /fluentbit-envoy/${DC}/${NODE_NAME}/%Y/%m/%d/%H/%M/%S/$TAG
        s3_key_format_tag_delimiters .-_
  
  parsers.conf: |-
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name split_question_mark
        Format regex
        Regex ^(?<request_uri>[^\?]+)\??.*$

  
  transforms.lua: |-
  
    function table.removeKey(table, key)
      local element = table[key]
      table[key] = nil
      return element
    end


    function fix_app_log(tag, timestamp, record)
      new_record = record
      if new_record['request_id'] == nil then
        new_record['request_id']= '-'
      end
      if new_record["@timestamp"] ~= nil then
        new_record['timestamp'] = record["@timestamp"]
      end
      if new_record['log_level'] ~= nil then
        new_record['level'] = record['log_level']
      end
      new_record['pipeline'] = "app-logs-java"

      new_record['artifact_id'] = string.match(record['filename'], "/var/log/([^/]*)/.*")

      return 1, timestamp, new_record
    end

    function fix_envoy_log(tag, timestamp, record)
      new_record = record
      if record["grpc-status"] ~= "-" then
        new_record["status"] = record["grpc-status"]
      end

      _artifact_id = string.match(record["upstream_cluster"], "_(.*)_")
      if _artifact_id then
        new_record["artifact_id"] = string.gsub(_artifact_id, "__", ".")
      else
        new_record["artifact_id"] = ""
      end

      new_record["ms"] = string.match(record["timestamp"], "%d*.(%d*)")
      new_record["ms"] = tonumber(new_record["ms"])

      new_record["pipeline"] = 'envoy'
      new_record["x-seen-by"] = nil
      return 1, timestamp, new_record
    end

```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes with fluent-bit running as a daemon set
* Server type and version: EKS managed Kubernetes
* Operating System and version:
* Filters and plugins: lua, regex, s3

**Comment by avdhoot** [comment]
Facing similar issue. 

We restarted fluent-bit pods on cluster some of them started some goes into crashbackloop with below error

1st problem is fluent-bit container goes into crashbackloop because out.s3 giving error. expected behavior is failure from one out put should not affect other output.  

```
[2020/12/01 09:05:15] [error] [output:s3:s3.2] Could not extract upload data from: 4873555510130270329-4946877267709263262
[2020/12/01 09:05:15] [error] [output:s3:s3.2] Could not process multipart upload data in 4873555510130270329-4946877267709263262
[lib/chunkio/src/cio_file.c:899 errno=22] Invalid argument
[2020/12/01 09:05:24] [engine] caught signal (SIGSEGV)
#0  0x5573f4afa06e      in  flb_fstore_file_meta_set() at src/flb_fstore.c:82
#1  0x5573f4ad64ee      in  s3_store_file_upload_put() at plugins/out_s3/s3_store.c:465
#2  0x5573f4ad74e1      in  save_upload() at plugins/out_s3/s3_multipart.c:297
#3  0x5573f4ad887b      in  upload_part() at plugins/out_s3/s3_multipart.c:652
#4  0x5573f4ad2fcf      in  upload_data() at plugins/out_s3/s3.c:748
#5  0x5573f4ad5073      in  cb_s3_flush() at plugins/out_s3/s3.c:1326
#6  0x5573f4a3364c      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:472
#7  0x5573f4e87ec6      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#8  0xffffffffffffffff  in  ???() at ???:0

@PettitWesley @edsiper

**Comment by edsiper** [comment]
would you please attach the problematic chunk/file 4873555510130270329-4946877267709263262 or similar to this ticket ?

**Comment by PettitWesley** [comment]
@edsiper I spent some time looking through the S3 code to try to figure out what might be going wrong... I wonder if part of it is this line: https://github.com/fluent/fluent-bit/blob/master/plugins/out_s3/s3_store.c#L465

That function currently sets the metadata every single time a part is uploaded (which should be unnecessary, the metadata is the S3 key + upload ID and is static). 

That shouldn't cause any problems though, unless may be the file has been corrupted or deleted. 

@avdhoot @vbichov the files in your `multipart_upload_metadata` directory at the time of crash would be very useful. Those don't contain your log data, just part numbers and ETags and upload IDs- it should be safe to share those with us. (And if you don't want to share publicly we can use email or the fluent slack).

**Comment by avdhoot** [comment]
@PettitWesley Please find attached file. even after cleaning the cache file we are seeing this issue after some time. Let me know if need more data. 
[4873555510130270329-4946877267709263262.zip](https://github.com/fluent/fluent-bit/files/5629970/4873555510130270329-4946877267709263262.zip)

**Comment by PettitWesley** [comment]
@avdhoot Can you share your full config? It does look like that file is corrupted, with the part upload data and the upload metadata mangled all together.

**Comment by avdhoot** [comment]
@PettitWesley  Below is config

```  fluent-bit-service.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    warn
        Parsers_File parsers.conf
        Parsers_File parsers_custom.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 5M

  fluent-bit-input.conf: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Multiline        Off
        Parser_Firstline multi_line
        Parser_1         docker
        Tag              containers.*
        Refresh_Interval 1
        Rotate_Wait      60
        Mem_Buf_Limit    5MB
        storage.type     filesystem
        Skip_Long_Lines  On
        DB               /data/tail-containers-state.db
        DB.Sync          Normal
        Ignore_Older     60m

  fluent-bit-filter.conf: |
    [FILTER]
        Name                kubernetes
        Match               containers.*
        Kube_Tag_Prefix     containers.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  fluent-bit-output.conf: |
    [OUTPUT]
        Name          forward
        Match         *
        Host          fluentd-logs.fluent.svc.cluster.local
        Port          24321
        Retry_Limit False

  fluent-bit-loki-output.conf: |
    [OUTPUT]
        Name          loki
        Match         *
        host          loki.loki.svc.cluster.local
        port          3100
        labels        job="fluent-bit",pod=$kubernetes['pod_name'], namespace=$kubernetes['namespace_name']
        label_keys    $kubernetes['host']
        auto_kubernetes_labels off

  fluent-bit-s3-output.conf: |
    [OUTPUT]
        Name  s3
        Match containers.*
        bucket ******-logs
        s3_key_format /us-sandbox/containers/$TAG[6]/$TAG[5]/%Y/%m/%d/%H
        s3_key_format_tag_delimiters ._
        store_dir /data/s3-output-cache-container
        region us-west-2
        total_file_size 50M
       upload_timeout 1m


  parsers.conf: |
    [PARSER]
        Name        multi_line
        Format      regex

**Comment by PettitWesley** [comment]
@avdhoot Is there anything about your setup which is possibly unique? (What is the local file system/storage?) I think you multipart uplaod metadata cache files are getting corrupted somehow, but I can't figure out how. I have been unable to reproduce it. 

However, as I mentioned in an earlier comment, the code does seem to unnecessarily set the metadata in the cache file more than once. So I removed that code.

Can you try running this image: `094266400487.dkr.ecr.us-west-2.amazonaws.com/s3-store-issue:latest`

That image can be pulled from any AWS account. 

If your company requires you to build your own images or something- the code is here: https://github.com/PettitWesley/fluent-bit/tree/s3-store-metadata

**Comment by PettitWesley** [comment]
@vbichov Please try out that image as well.

I will put up a pull request for the change, but since I can't reproduce this issue, without your help we won't know if the fix actually works.

**Comment by avdhoot** [comment]
We use host machine to store fluent-bit data(cache/tail-db) which use aws EBS volume. 
We have deployed given build. I have not seen any `crashbackloop` in update phase. Will update here after 24hr. @PettitWesley

**Comment by PettitWesley** [comment]
@avdhoot is it still working?

**Comment by avdhoot** [comment]
@PettitWesley For some pod it fixed after increasing memory for fluent bit pod because we saw loot `oom`  in `dmesg`. That might explain file corruption.  For few pod i cleaned up everything(all cache) & increased memory still see the issue.  Also this started when we configured s3 out.

**Comment by PettitWesley** [comment]
@avdhoot How much available space do you have on your EBS volume on these nodes? Are you running out of disk space.

I am still trying to figure out what causes this issue... not having a ton of luck. Presumably the comes from here: https://github.com/fluent/fluent-bit/blob/master/lib/chunkio/src/cio_file.c#L1025

Its not clear that's why it crashes though. And I can't figure out how the files would get corrupted.

**Comment by adinaclaudia** [comment]
I am facing same issue but with Azure Blob output plugin. I tried all 1.6.x versions and all crash eventually (some versions run out of memory or stop responding to liveness probes in k8s). 
```
[2020/12/08 13:33:21] [ warn] [engine] failed to flush chunk '1-1607434393.967383841.flb', retry in 11 seconds: task_id=9, input=tail.0 > output=es.0
[2020/12/08 13:33:21] [ warn] [engine] failed to flush chunk '1-1607434394.70654065.flb', retry in 7 seconds: task_id=10, input=tail.0 > output=es.0
[2020/12/08 13:33:21] [ info] [output:azure_blob:azure_blob.1] content appended to blob successfully
[2020/12/08 13:33:21] [ info] [output:azure_blob:azure_blob.1] blob id ZmxiLTE2MDc0MzQ0MDEuMTcxMy5pZA== committed successfully
[2020/12/08 13:33:22] [ warn] [engine] failed to flush chunk '1-1607434400.967468964.flb', retry in 6 seconds: task_id=1, input=tail.0 > output=es.0
[2020/12/08 13:33:22] [ warn] [engine] failed to flush chunk '1-1607434401.169775787.flb', retry in 11 seconds: task_id=8, input=tail.0 > output=es.0
[2020/12/08 13:33:22] [ info] [output:azure_blob:azure_blob.1] content appended to blob successfully
[2020/12/08 13:33:22] [ info] [output:azure_blob:azure_blob.1] blob id ZmxiLTE2MDc0MzQ0MDIuMTcwMy5pZA== committed successfully
[2020/12/08 13:33:27] [ warn] [engine] failed to flush chunk '1-1607434402.741153588.flb', retry in 8 seconds: task_id=4, input=tail.0 > output=es.0
[2020/12/08 13:33:27] [ warn] [engine] failed to flush chunk '1-1607434407.15776933.flb', retry in 8 seconds: task_id=17, input=tail.0 > output=es.0
[2020/12/08 13:33:27] [ info] [output:azure_blob:azure_blob.1] content appended to blob successfully
[2020/12/08 13:33:27] [ info] [output:azure_blob:azure_blob.1] blob id ZmxiLTE2MDc0MzQ0MDcuMTc4MC5pZA== committed successfully
[2020/12/08 13:33:28] [ warn] [engine] chunk '1-1607434400.967468964.flb' cannot be retried: task_id=1, input=tail.0 > output=es.0
[2020/12/08 13:33:28] [ warn] [engine] chunk '1-1607434394.70654065.flb' cannot be retried: task_id=10, input=tail.0 > output=es.0
[2020/12/08 13:33:30] [engine] caught signal (SIGSEGV)
#0  0x55f72d985c03      in  ???() at lib/monkey/deps/flb_libco/libco.c:0
```

If don't use the Azure Blob ouput plugin or i revert to 1.5.7, it works. CPU and memory consumption are well within limits.
Also, I do get some logs in the Azure blobs, so connection works.
Any help would be appreciated.

**Comment by edsiper** [comment]
@adinaclaudia I think the issue you just mentioned is different, the original issue is triggered from S3 output plugin and this one at a co-routine level. Would you please open a new ticket so we can troubleshoot there? (we need to separate issues for a clean troubleshooting and further fix)

**Comment by adinaclaudia** [comment]
@edsiper ok, thanks. I opened a separate issue #2839

**Comment by avdhoot** [comment]
@PettitWesley We have enabled s3 out again without cache(multipart-upload). We are seeing below error please let me know if you need separate issue. 
``` 
[2020/12/11 09:16:23] [error] [output:s3:s3.1] PutObject request failed
[2020/12/11 09:16:23] [ warn] [engine] failed to flush chunk '1-1607678178.586003765.flb', retry in 6 seconds: task_id=0, input=tail.0 > output=s3.1
[2020/12/11 09:16:33] [error] [tls] SSL error: NET - Connection was reset by peer
[2020/12/11 09:16:33] [error] [src/flb_http_client.c:1129 errno=25] Inappropriate ioctl for device
[2020/12/11 09:16:33] [error] [output:s3:s3.1] PutObject request failed
[2020/12/11 09:16:33] [ warn] [engine] failed to flush chunk '1-1607678188.559029868.flb', retry in 8 seconds: task_id=0, input=tail.0 > output=s3.1
[2020/12/11 09:16:53] [error] [tls] SSL error: NET - Connection was reset by peer
[2020/12/11 09:16:53] [error] [src/flb_http_client.c:1129 errno=25] Inappropriate ioctl for device
[2020/12/11 09:16:53] [error] [output:s3:s3.1] PutObject request failed
[2020/12/11 09:16:53] [ warn] [engine] failed to flush chunk '1-1607678211.406654969.flb', retry in 11 seconds: task_id=5, input=tail.0 > output=s3.1

```

**Comment by PettitWesley** [comment]
@avdhoot Yeah, this one needs a separate issue. Is it a consistent issue? When I run the S3 plugin I do very occasionally see connection reset messages, but the retries always succeed and the errors are very infrequent.

**Comment by marklinders-planon** [comment]
@PettitWesley We have updated our fluent-bit daemonsets to use the custom image. Usually we have the segfault errors within the week on multiple fluent-bit pods. I will update next week with results or earlier if the problem returns before then.

**Comment by PettitWesley** [comment]
For everyone else who is tracking this issue, #2859 looks like a duplicate and per my comment there, I am continuing to try to evaluate other things which might be causing this bug. As noted by most reports it happens infrequently which makes repro + testing difficult and slow. 

If anyone has a config/setup in which the error happens quite frequently and repeatably- I'd be very interested to see details on that.

@marklinders-planon Thank you.

**Comment by marklinders-planon** [comment]
@PettitWesley I can confirm that we still have the issue using image _094266400487.dkr.ecr.us-west-2.amazonaws.com/s3-store-issue:latest_

We had 4 restarts due to `[engine] caught signal (SIGSEGV)` on 3 different fluent-bit pods in the eu-central-1 (frankfurt) region. Interestingly we also have around 10 fluent-bit pods running in the ap-south-1 (mumbai) region, which have 0 restarts.

**Comment by PettitWesley** [comment]
@marklinders-planon Please share all stack traces if you have them. I just realized that the trace you shared previously is different than then all the others I have seen.

**Comment by PettitWesley** [comment]
Also, @edsiper is it possible that this could be caused by a bug in fstore or chunkio? I was reading the warning here, that calls to ftruncate can crash the program in rare cases: https://github.com/fluent/fluent-bit/blob/master/lib/chunkio/src/cio_file.c#L1039

I checked and when I run the S3 output ftruncate calls are made. Will ftruncate only crash the program if the disk fills up or are there are other cases?

**Comment by PettitWesley** [comment]
I've been feeling bad about this issue and how much trouble its causing folks, so I posting live updates as I keep working. I think I am very close to figuring out the root cause.

Basically, the stack trace is correct, its crashing on this line, which is an error message: https://github.com/fluent/fluent-bit/blob/master/src/flb_fstore.c#L82

Sometimes when that function is run, the stream has not actually been initialized yet, so when it tries to print the error, it crashes. I am not sure what causes the call above that error message to fail, but I think the crash is actually caused by the log message. 

I am not certain of this yet... the setup which I am using the test things is a bit artificial. 

I will have a new image ready for folks to try in a few hours, that should not crash if my hypothesis is correct, and will also print some useful debug information just in case its actually something else. 

@marklinders-planon

**Comment by PettitWesley** [comment]
Alrighty, I am 90% confident that I have actually solved it this time. It took a little longer than I expected, because I found another bug in the process, which might have been the other issue reported in #2859 

Everyone, please try out this image and let me know if the problem is fixed: 

```
094266400487.dkr.ecr.us-west-2.amazonaws.com/fstore-crash-fix:latest
```

If it does, @edsiper has agreed to rush out a new release this friday.

**Comment by PettitWesley** [comment]
@marklinders-planon See above

**Comment by marklinders-planon** [comment]
Hi @PettitWesley, update from our end. We have not seen the SIGSEGV messages yet. So far so good. We'll keep monitoring it. What I did notice is the following messages that I can't recall having seen before in my logs:

```
[2021/01/07 10:05:57] [ info] [output:s3:s3.1] upload_timeout reached for logs.kube.var.log.containers.aajakk221-test.accesslog.tomcat-5f4884b6b5-b7bl2.e09a9c4e92285d6ea3faae075e2294d17488b9285f4aeea1f591c0a82ee4d688
[2021/01/07 10:05:57] [error] [tls] SSL error: NET - Connection was reset by peer
[2021/01/07 10:05:57] [error] [src/flb_http_client.c:1129 errno=25] Inappropriate ioctl for device
[2021/01/07 10:05:57] [error] [output:s3:s3.1] PutObject request failed
[2021/01/07 10:05:57] [ warn] [engine] failed to flush chunk '1-1610013957.324498868.flb', retry in 8 seconds: task_id=0, input=tail.0 > output=s3.1
[2021/01/07 10:06:05] [ info] [output:s3:s3.1] upload_timeout reached for logs.kube.var.log.containers.aajakk221-test.accesslog.tomcat-5f4884b6b5-b7bl2.e09a9c4e92285d6ea3faae075e2294d17488b9285f4aeea1f591c0a82ee4d688
```

According to the message the upload_timeout is reached which causes the PutObject request to fail. It does work on a retry. So I guess that is the problem that @avdhoot mentioned in his previous comment.

**Comment by PettitWesley** [comment]
I've seen those connection errors sporadically as well myself, its definitely not related to this patch. Fluent Bit 1.7 will apparently include some major improvements in performance from switching to openssl (from mbedtls) for https connections, though I have no clue if that will fix the connection issues (or may be its not a real issue, occasional connection drops can happen).

**Comment by marklinders-planon** [comment]
The connection issues are not a problem for us, as the retry works without issues. I did see another occurrence of the SIGSEGV errors.

```
[2021/01/07 18:18:40] [error] [fstore] could not write metadata to file: 6476594258187946672-460271924326400256, root_dir=/tmp/fluent-bit/s3/fluent-log-plnd-fr-2045454REDACTED00554500000b
[2021/01/07 18:18:40] [engine] caught signal (SIGSEGV)
[2021/01/07 18:18:40] [error] [output:s3:s3.1] error writing tag metadata
```

**Comment by PettitWesley** [comment]
@marklinders-planon Can you send me more logs before and after the crash (either here or by email)? Does the crash occur as frequently as before? Do any of the crashes have a stacktrace?

**Comment by marklinders-planon** [comment]
@PettitWesley, i don't really know if it happens more often. The pods have been running for 24 hours with the custom image and in the eu-central-1 region one of them restarted with the error. There were 6 fluentbit pods running in that region.
The ap-south-1 region has 9 fluent-bit pods running, but show no errors in the past 24 hours.

In another AWS account where we still use the original image _fluent/fluent-bit:1.6.8_ we see that one of the pods was up for 16 days in which it restarted 3 times. Another pod with almost 3 days of uptime restarted once. I sent the logs by e-mail.

**Comment by mikhno-s** [comment]
Same problem with after upgrading v1.7
See in logs:
```
PutObject request failed
```
and then
```
failed to flush chunk '1-xxxx.xxxxxx.flb', retry in 8 seconds
```
s3 too often rejects the PUT requests, hence we have a lot of chunks that were not flushed.

As a result - tons of .flb chunks in `./storage/<input_name>/` dir that cannot be flushed and cannot be destroyed, due to not working `storage.total_limit_size` parameter https://github.com/fluent/fluent-bit/issues/2688

**Comment by PettitWesley** [comment]
@mikhno-s try updating your 1.7 image, there was a bug that broke AWS plugins ability to make connections (certs weren't included properly in the image) and the upstream maintainers re-uploaded the images.

AFAIK this bug was fixed in upstream. @marklinders-planon and I worked on it for a while and resolved this and other related issues.

**Comment by PettitWesley** [comment]
@mikhno-s Please post a fuller set of logs which shows the EINVAL error/crash.
