### ISSUE TITLE
Input plugin exec: run only once at startup

### ISSUE THREAD

**Issue by HontoNoRoger** [fluent/fluent-bit#2757]
The original fluentd input plugin for exec supports [running only once](https://docs.fluentd.org/input/exec#run_interval) at start of the daemon by setting `run_interval` to `nil`.
I'd like to get this feature for fluent-bit as well, currently [setting the interval to something <= 0 will result in use of the default of 1 second delay](https://github.com/fluent/fluent-bit/blob/master/plugins/in_exec/in_exec.c#L187).

My use case is to fetch kernel logs which happened prior to the start of fluent-bit. This approach worked well with fluentd.

**Comment by fujimotos** [comment]
> I'd like to get this feature for fluent-bit as well, currently setting the interval to something <= 0 will result in use of the default of 1 second delay.

@HontoNoRoger I posted a patch #2789 that implements that feature.
I appreciate it if you could check that patch and give us some feedback.

**Comment by LukasJerabek** [comment]
Hi, could someone advise me, how can I achieve the same in latest version?

**Comment by LukasJerabek** [comment]
I have found the issues, bool parameter works for me... However I was hoping to be able to use exec for command like 
`mpstat 5`
which actually works in fluentd and continuously emits records as mpstat outputs to stdout. Using fluentbit I see records getting flushed only on shutdown, even though I have set flush 1. Am I missing something, or it is not possible to follow output of evergoing command like mpstat <number>?
