### ISSUE TITLE
No matching route for backoff logs

### ISSUE THREAD

**Issue by phiremande** [fluent/fluent-bit#2765]
## Bug Report

**Describe the bug**
Seeing the below error when file system storage is enabled and some logs are buffered. If fluent-bit restarts I see this below error.
![image](https://user-images.githubusercontent.com/16595434/98903168-0f6b6180-24dd-11eb-9d42-95605cc62780.png)

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
![image](https://user-images.githubusercontent.com/16595434/98903192-1b572380-24dd-11eb-9fa7-6a04cdd4ffda.png)

- Steps to reproduce the problem:

Enable storage type filesystem. Bring down the connectivity to fluent-bit destination. Check that some logs are buffered on the file system. Restart fluent-bit.

**Expected behavior**
Backed off logs should be routed properly instead of getting dropped.

* Version used: 1.6.3
* Configuration:
INPUT plugin is tcp, and OUTPUT plugin is kafka-rest.
storage.type if filesystem.

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
Linux (Centos).
* Filters and plugins:

**Comment by rmacian** [comment]
also in 1.6.4

**Comment by JeffLuoo** [comment]
Hi @rmacian @phiremande 

I guess it is caused by that there are new features introduced in 1.6.3 for filesystem storage. And those new features relies on the new class members added in 1.6.3 as well. However, those buffered logs on your disk might not contain the information of newly added class members.

Could you please try clean up those back logs before restarting the new fluent bit? I feel sorry that this result in any inconvenience.

@edsiper Is there any idea to avoid cleaning up back logs on file system before restarting the fluent bit?

**Comment by phiremande** [comment]
@JeffLuoo , cleaning up of logs would mean losing the backed-up logs right and in any case the logs are deleted because the of empty route. It didn't required any manual cleanup. But this would mean, logs cannot be buffered across reboots (at least for now). Please do let me know if I have misunderstood anything?

**Comment by phiremande** [comment]
@JeffLuoo , just to clarify this is not an upgrade scenario. Logs buffered were from 1.6.3 and restart caused this issue. Hope it helps.

**Comment by JeffLuoo** [comment]
@phiremande Sorry for missing for first message. For some reason I did not receive the update. Could you please share me your fluent-bit configuration?

**Comment by phiremande** [comment]
`
[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    #Flush        5

    # Daemon
    # ======
    # Instruct Fluent Bit to run in foreground or background mode.
    Daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # By default 'info' is set, that means it includes 'error' and 'warning'.
    Log_Level    debug
    Log_File     /tmp/fblog.log

    storage.path     ./fluent-bit/
    storage.sync     full
    storage.checksum     off

    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File ./fluent-bit/fb_parsers.conf
    #Plugins_File plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server  On
    HTTP_Listen  127.0.0.1
    HTTP_Port    5190

[INPUT]
    Name tcp
    Listen      127.0.0.1
    Port        5170
    Format      json
    Tag         mytag
    Mem_Buf_Limit 8MB
    storage.type        filesystem


[OUTPUT]
    Name        kafka-rest
    Match       mytag
    Host        abc
    Port        443
    Topic       mymsg
    Message_Key my_key
    Time_Key    timestamp
    tls         On
    tls.verify  On
    tls.ca_file     /home/etc/certs/serverCAs.txt
    tls.crt_file    /home/etc/certs/cert.pem   
    tls.key_file    /home/etc/certs/key.pem
    Retry_Limit False
`

**Comment by phiremande** [comment]
A config similar to above if the kafka rest server is unreachable for some time (and logs get buffered), and then fluent-bit restarts, that is when the issue is seen.

**Comment by rmacian** [comment]
In my case is an upgrade scenario

**Comment by JeffLuoo** [comment]
@phiremande Thanks for sharing your config file. However I wasn't able to reproduce this error by steps you mentioned "Bring down the connectivity to fluent-bit destination. Check that some logs are buffered on the file system. Restart fluent-bit.". My fluent-bit (1.6.4) is able to deliver those buffered logs to the destination. Could you please try reproduce the issue with the newest fluent-bit to see if this is an update scenario? Thank you.

**Comment by phiremande** [comment]
@JeffLuoo , I have two setups and one (ubuntu) this works, while it doesn't work on (centos). I added some debug log
`
diff --git a/src/flb_router.c b/src/flb_router.c
index 7d27f50..9008a68 100644
--- a/src/flb_router.c
+++ b/src/flb_router.c
@@ -268,6 +268,8 @@ uint64_t flb_router_get_routes_mask_by_tag(const char *tag, int tag_len,
         o_ins = mk_list_entry(o_head,
                               struct flb_output_instance, _head);

+        flb_debug("[router] matching rule for output %s:%d, tag:%s",
+              o_ins->name, o_ins->mask_id, tag);
         if (flb_router_match(tag, tag_len, o_ins->match
 #ifdef FLB_HAVE_REGEX
                              , o_ins->match_regex
@@ -298,6 +300,7 @@ uint64_t flb_router_get_routes_mask_by_tag(const char *tag, int tag_len,
              *    00001 |= 4 -> 00001 |= 00100 -> 00101
              */
             routes_mask |= o_ins->mask_id;
+            flb_debug("[router] routes_mask: %llu", routes_mask);
         }
     }
`
And I see the below logs:

`
[2020/11/19 04:19:28] [debug] [storage] tcp.0:11275-1605788259.225975967.flb mapped OK
[2020/11/19 04:19:28] [ info] [input:storage_backlog:storage_backlog.4] queueing tcp.0:11275-1605788259.225975967.flb
[2020/11/19 04:19:28] [debug] [router] matching rule for output kafka-rest.0:1, tag:(null)
[2020/11/19 04:19:28] [debug] [router] matching rule for output kafka-rest.1:2, tag:(null)
[2020/11/19 04:19:28] [debug] [router] matching rule for output kafka-rest.2:4, tag:(null)
[2020/11/19 04:19:28] [debug] [router] matching rule for output kafka-rest.3:8, tag:(null)
[2020/11/19 04:19:28] [ warn] [input chunk] no matching route for backoff log chunk 11275-1605788259.225975967.flb
`
Any idea what could have caused tag to be null.

**Comment by phiremande** [comment]
On working setup:
```
210 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[92m info^[[0m] [input:storage_backlog:stora    ge_backlog.2] queueing cpu.0:23204-1605793412.240302064.flb
211 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[93mdebug^[[0m] [router] matching rule for o    utput http.0:1, tag:(null), tag_len:-148872320
212 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[93mdebug^[[0m] [router] routes_mask: 1
213 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[93mdebug^[[0m] [storage] cpu.0:23204-160579    3417.239891969.flb mapped OK
214 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[92m info^[[0m] [input:storage_backlog:stora    ge_backlog.2] queueing cpu.0:23204-1605793417.239891969.flb
215 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[93mdebug^[[0m] [router] matching rule for o    utput http.0:1, tag:(null), tag_len:-148872320
216 ^[[1m[^[[0m2020/11/19 19:16:24^[[1m]^[[0m [^[[93mdebug^[[0m] [router] routes_mask: 1
```
While routes_mask log isn't seen on the non-working setup.

**Comment by phiremande** [comment]
@JeffLuoo , please do let me know if you have any updates on this issue.

**Comment by wildhemp** [comment]
I also have a this issue. Some additional information to the above is that since I have two outputs, stackdriver and stdout (see blow), the backlogs after restart are all sent to stdout, whereas all should be sent to stackdriver. This is with version 1.6.4 (and 1.6.5 as well, but that has other issues).
Config

[SERVICE]
    Flush               1
    Log_Level           info
    storage.path        storage.tmp
    HTTP_Server         On
    HTTP_Listen         0.0.0.0
    HTTP_PORT           2020

[INPUT]
    Name        forward
    Listen      127.0.0.1
    Port        24224
    Buffer_Chunk_Size  32KB
    Buffer_Max_Size  128MB
    storage.type  filesystem

[OUTPUT]
    Name                          stackdriver
    Match_Regex              ^.+?\.test$
    resource                      gce_instance
    labels_key                    labels
    severity_key                 severity

[OUTPUT]
    Name        stdout
    Match_Regex       ^.+(?<!\.test)$

I didn't try with simple Match, but I'm pretty certain it would have the same problem based on the other config in this thread.

**Comment by JeffLuoo** [comment]
@phiremande Sure I will. I will take a look into it after finishing my school project.

**Comment by phiremande** [comment]
@JeffLuoo , looks to be stack corruption:

src/flb_router.c
```
265
266     flb_debug("PHK [router] tag: %s, %d", tag, tag_len);
267     /* Find all matching routes for the given tag */
268     mk_list_foreach(o_head, &in->config->outputs) {
269         o_ins = mk_list_entry(o_head,
270                               struct flb_output_instance, _head);
271
272         flb_debug("PHK [router] matching rule for output %s:%d, tag:%s, tag_len:%d",
273               o_ins->name, o_ins->mask_id, tag, tag_len);

```

Logs:
```
[[1m[^[[0m2020/11/24 11:45:28^[[1m]^[[0m [^[[92m info^[[0m] PHK[input] triggering collector callback cpu.0, my_cpu, 6
^[[1m[^[[0m2020/11/24 11:45:28^[[1m]^[[0m [^[[93mdebug^[[0m] [storage] cpu.0:10648-1606198528.975115785.flb mapped OK
^[[1m[^[[0m2020/11/24 11:45:28^[[1m]^[[0m [^[[93mdebug^[[0m] PHK [router] tag: my_cpu, 6
^[[1m[^[[0m2020/11/24 11:45:28^[[1m]^[[0m [^[[93mdebug^[[0m] PHK [router] matching rule for output http.0:1, tag:(null), tag_len:164959888
^[[1m[^[[0m2020/11/24 11:45:28^[[1m]^[[0m [^[[93mdebug^[[0m] [router] routes_mask: 1
```

**Comment by JeffLuoo** [comment]
@wildhemp Thanks for the information. I looked at your config file and found that you used the `forward` input plugin and this plugin does not require a tag field in the configuration. However the routing algorithm will use the tag value of the input plugin to match. Could you please try to add a tag value to your forward plugin and then try it again?

**Comment by JeffLuoo** [comment]
@phiremande From logs you provided, I found that there are tags printed out as `null`. I think this is the root cause for the debug message `No matching route for ...`. Are you running fluent-bit on a cluster (like k8s) ?

**Comment by phiremande** [comment]
@JeffLuoo , sure. Just wanted to point out one thing though, maybe you have noticed. In case you haven't,

```
265
266     flb_debug("PHK [router] tag: %s, %d", tag, tag_len);
267     /* Find all matching routes for the given tag */
268     mk_list_foreach(o_head, &in->config->outputs) {
269         o_ins = mk_list_entry(o_head,
270                               struct flb_output_instance, _head);
271
272         flb_debug("PHK [router] matching rule for output %s:%d, tag:%s, tag_len:%d",
273               o_ins->name, o_ins->mask_id, tag, tag_len);
```
the first log has values from actual input plugin but once the list iteration starts the tag has gone bad
```
/11/24 11:45:28^[[1m]^[[0m [^[[93mdebug^[[0m] PHK [router] tag: my_cpu, 6
^[[1m[^[[0m2020/11/24 11:45:28^[[1m]^[[0m [^[[93mdebug^[[0m] PHK [router] matching rule for output http.0:1, tag:(null), tag_len:164959888
```

**Comment by JeffLuoo** [comment]
@phiremande I noticed that but don't have any idea about that atm. I just pushed a patch #2806 and once it is merged could you please try again to see if the issue still happens? Thank you so much.
