### ISSUE TITLE
in_tail: send file offset in addition to filename to the output

### ISSUE THREAD

**Issue by yiwenshao** [fluent/fluent-bit#2770]
**Is your feature request related to a problem? Please describe.**
I use [tail](https://docs.fluentbit.io/manual/pipeline/inputs/tail) to collect log. Currently, tail provides Path_Key option to append filename to log record, but there is no way to add file offset to log record. I need something similar to log.offset option in   [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-log.html).

**Describe the solution you'd like**
add Offset_key option to the tail plugin, which appends the offset of each line to the log record.

**Comment by edsiper** [comment]
thanks for opening this ticket.

just curious, what's the use case where the offset is needed ? who is it used in your environment ?

**Comment by martinkubrak** [comment]
That would be useful for me as well. In my particular case, it's for Apache Airflow to be able to read logs from Elasticsearch - it requires 'offset' filled to be present.

**Comment by yiwenshao** [comment]
> thanks for opening this ticket.
> 
> just curious, what's the use case where the offset is needed ? who is it used in your environment ?

In my environment, this offset is used for sorting the log in our log processing system.

**Comment by yongtang** [comment]
Added a PR #3038 to provide `Offset_Key` support in tail plugin.

**Comment by MPeli** [comment]
Hi,
    
     Thank you for adding the new option. This is exactly what I need. I am trying to use it. I had to build fluent-bit because there is no official release with the new feature implemented. I am able to get offset as long as `Multiline` is set to `Off`. Once I turned it `On`, the offset is missing in all records. I am not sure whether I built it correctly. Does it work for you?

Thank you, Martin.

[sos-report.log](https://github.com/fluent/fluent-bit/files/6066998/sos-report.log)
