### ISSUE TITLE
Support TLS on Forward Input plugin

### ISSUE THREAD

**Issue by vizcay** [fluent/fluent-bit#2772]
According to https://docs.fluentbit.io/manual/administration/security TLS is only supported in output plugins. I will be great also to have support for input plugins. Mostly because we prefer to use fluent-bit over fluentd as it is simpler and has a lower footprint.

**Comment by vizcay** [comment]
Still relevant.

**Comment by vizcay** [comment]
Still relevant.

**Comment by vizcay** [comment]
Still relevant.

**Comment by vizcay** [comment]
Still relevant.

**Comment by liuchintao** [comment]
So, is there anyone know why input plugins do not support tls?

**Comment by vizcay** [comment]
Still relevant.

**Comment by edsiper** [comment]
bump

**Comment by vizcay** [comment]
> Hello, I think I know why input plugins do not support TLS.

Why that will be? `fluentd` supports TLS for this.

**Comment by bbeattie-phxlabs** [comment]
Is the desired design that folks use a service mesh to handle the TLS between pods? Either way, the ticket is still relevant!

**Comment by LukasJerabek** [comment]
After problems with fluentd and seeing old same issues without any answer there I thought maybe fluent-bit is better, but it does not seem to. Is fluentd not maintained anymore?

**Comment by vizcay** [comment]
Bump.

**Comment by vizcay** [comment]
Bump.

**Comment by rohitkg** [comment]
Is there any way to use https for prometheus_scrape input endpoint?

**Comment by leonardo-albertovich** [comment]
I don't think it's possible at the moment but it will be in 2.0 (which will also include TLS support for input plugins)

**Comment by vizcay** [comment]
@leonardo-albertovich this has been implemented finally? 🎉

**Comment by leonardo-albertovich** [comment]
Yes, it came out in 2.0 and I have fixed a few issues that were identified in latest version (I think it came out yesterday).

**Comment by shvc** [comment]
Per https://docs.fluentbit.io/manual/administration/transport-security  bluent-bit 2.0 input tls just supports `MQTT`, `TCP`, `HTTP` and `OpenTelemetry`,  no `forward`

**Comment by leonardo-albertovich** [comment]
It seems like there's an error in the documentation. The forward input plugin has TLS support in Fluent-bit 2.0+

**Comment by SharathSunny** [comment]
If yes, I can't find any documentation related to that, and even when I tried using the input HTTP pulgin it is throwing an error.

**Comment by aval13** [comment]
> @leonardo-albertovich If yes, I can't find any documentation related to that, and even when I tried using the input HTTP pulgin it is throwing an error.

The documentation we used is exactly the one mentioned 3 comments above:
https://docs.fluentbit.io/manual/administration/transport-security
We are successfully using it with forward plugin both as input and output.

**Comment by SharathSunny** [comment]
@aval13 Ok, I have followed the same.

let me show the conf file I am doing 
Before that I have created a self signed cert based on [TLS](https://banzaicloud.com/blog/k8s-logging-tls/)  and I am using in a k8's env, I have a fluentbit container in my cluster and another fluentbit server at ec-2instance(allowed the traffic).

conf:
`[OUTPUT]
    Name forward
    Match *
    Host <host> (ec2-host where I have configured the input)
    Port <port>
    Retry_Limit False
    tls  On
    tls.verify Off
    tls.debug 4
    tls.ca_file <path>/<cafilename>
    tls.crt_file <path>/<clinetcrtfilepath>
    tls.key_file <path>/<clientcrtkeypath>
    tls.key_passwd <password>
    Shared_Key <password>`

an other end I am an ec-2 instance with Ubuntu os
Input at the other end 
`[INPUT]
    Name forward
    Listen 0.0.0.0
    Port <port> (same port)
    tls  On
    tls.verify Off
    tls.debug 4
    tls.ca_file <path>/<cafilename>
    tls.crt_file <path>/<servercrtpath>
    tls.key_file <path>/<servercrtkeypath>
    tls.key_passwd <password>`

**Comment by aval13** [comment]
@SharathSunny 

and the errors you're getting since you're saying it's not working are....?

> [OUTPUT]
>     Name forward
[snip]
>     tls.crt_file <path>/<clinetcrtfilepath>
>     tls.key_file <path>/<clientcrtkeypath>
>     tls.key_passwd <password>

So I guess you're trying to do mTLS? you didn't say anywhere you're trying to do mTLS.

>     Shared_Key <password>

where in the documentation at the link 2 comments above did you find a "Shared_Key" option?
I did find it in the forward output plugin where it clearly states this:
"Shared_Key
A key string known by the remote **Fluentd** used for authorization."
You said you use 2 fluentbits, not a fluentbit sending to a fluentd.

> [INPUT]
>     Name forward
[snip]
>     tls.verify Off
>     tls.ca_file <path>/<cafilename>

so... mTLS I guess.
Do you really need to try mTLS first?
I'd say try first simple TLS, then extend to mTLS.

But without any error logs I'm not sure anybody can help (at least on this closed issue).
My best guess at this moment is that the Shared_Key breaks the comms (i've seen a fluentd with a <security> section causing weird error logs on a fluentbit which on input forward does not support something similar).
