### ISSUE TITLE
FluentBit CPU bottleneck when higher EPS | Best practices for high EPS

### ISSUE THREAD

**Issue by dengalebr** [fluent/fluent-bit#2790]
We are using 1.6.4 with filesystem storage options. In our environment we have high EPS and during spikes each nodes generate 10k+ events. We have seen 5k-7k is managed well with fluent-bit but after than CPU stuck at ~990 and later it can not keep up and storage goes up.

How can we increase more than 1 CPU? How to control this so throughput remain high?

Below is our configurations:
#Configurations:
[FILTER]
Name kubernetes
Match kube.*
Kube_Tag_Prefix kube.var.log.containers.
Kube_URL https://kubernetes.default.svc:443
Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
Keep_Log off
Merge_Log_Key log
K8S-Logging.Parser On
K8S-Logging.Exclude On

[FILTER]
fluent-bit-input.conf: "[INPUT]
Name tail
Path /var/log/containers/*.log
Parser docker
Tag kube.
Refresh_Interval 5
Mem_Buf_Limit 2G
Skip_Long_Lines On
storage.type filesystem
Buffer_Chunk_Size 128k
Buffer_Max_Size 1MB
Ignore_Older 5h
DB /tail-db/tail-containers-state.db
DB.Sync Normal
Docker_Mode On
Docker_Mode_Flush 4
Docker_Mode_Parser identify_firstline
Exclude_Path /var/log/containers/splunk-kubernetes-logging-fluent-bit.log

fluent-bit-output.conf:
[OUTPUT]
Name splunk
Match *
Host
Port >
Splunk_Token
Splunk_Send_Raw  off
TLS on
TLS.Verify off
tls.debug 1
Message_Key kubernetes
Retry_Limit False

fluent-bit-service.conf: "[SERVICE]
       Flush 2
       Daemon Off
       Log_Level info
       Parsers_File                parsers.conf
        storage.path                /var/log/fluent-bit/
        storage.sync                normal
        storage.checksum            Off
        storage.max_chunks_up       256
        storage.backlog.mem_limit   2G

  fluent-bit-filter.conf: |
    [FILTER]
        Name nest
        Match *
        Operation lift
        Nested_under kubernetes

    [FILTER]
        Name record_modifier
        Match *
        Remove_key container_hash
        Remove_key stream
        Record cluster_name {{ .Values.kubernetes.clusterName }}

    # add event metadata
    [FILTER]
        Name      modify
        Match     *
        Copy      pod_name sourcetype
        Rename    host node_name
        Rename    pod_name pod
        Rename    pod_id pod_uid
        Rename    namespace_name namespace
        Rename    docker_id container_id

 parsers.conf: |
      [PARSER]
        Name identify_firstline
        Format regex
        Regex ({"log":(?<message>"([0-9]{4}[-\/]|(Sun|Mon|Tue|Wed|Thu|Fri|Sat|Jan|Feb|Mar|Apr|May|June|July|Aug|Sep|Oct|Nov|Dec)[ ,]|\[?(INFO|WARNING|DEBUG|ERROR|SEVERE|info|warning|debug|error|severe)[:\]]).*),"stream":.*)

Our Environment

Version used: 1.6.4

Configuration: kubernetes 1.18.5

Filters and plugins: tail, splunk

CPU Caps at 1 only, we would like to use more CPU so it can support more EPS
NAME                                         CPU(cores)   MEMORY(bytes)   
splunk-kubernetes-logging-fluent-bit-zbfx4   958m         135Mi 

We wanted to understand what we are missing in latest version of fluent-bit so we can get same throughput, we have tried out most of the parameters.

Thank you.

**Comment by edsiper** [comment]
@dengalebr 

thanks for reaching out. I think you will bit a bit more of tweaks in the pipeline to achieve higher throughput. Fluent Bit 1.7 will come with multi-threading support.

if it makes easier we can join a call, pls pick up a time here so we can troubleshoot: https://calendly.com/c/GFGSTINNRFL6KRX5?month=2020-11

**Comment by dengalebr** [comment]
Thanks @edsiper,  I have scheduled time for tomorrow. Looking forward to discuss with you.

**Comment by agup006** [comment]
@dengalebr with 1.7.0 available and multi-workers out in open source, I'm going to close this for now. Please re-open if additional help is needed.

**Comment by Infusible** [comment]
Not working.
image: fluent/fluent-bit:1.9.1

cpu used fluent-bit
last 2days
<img width="1801" alt="image" src="https://user-images.githubusercontent.com/31616457/161272947-5d009358-ac6d-4b5a-8ce0-b2c6ce1c717e.png">

last 12h
<img width="1993" alt="image" src="https://user-images.githubusercontent.com/31616457/161275016-32d95eaf-ce44-41ea-a441-644f825950d4.png">

last 7days
<img width="1955" alt="image" src="https://user-images.githubusercontent.com/31616457/161275605-22ea3c1f-5481-44ad-867e-230224edd27e.png">


my logs one pod
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/31616457/161274785-ae9e61d2-c6c5-4cf1-aeb0-9352bbb6d3a5.png">


_**configs:**_
**custom_parsers.conf**
`[PARSER]
  Name   json
  Format json
  Time_Key time
  Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
  Name        docker
  Format      json
  Time_Key    time
  Time_Format %Y-%m-%dT%H:%M:%S.%L
  Time_Keep   On`

**fluent-bit.conf**
`[SERVICE]
  Daemon Off
  Flush 10
  Log_Level info
  Parsers_File parsers.conf
  Parsers_File custom_parsers.conf
  HTTP_Server On
  HTTP_Listen 0.0.0.0
  HTTP_Port 2020
  Health_Check On

[INPUT]
  Name              tail
  Tag               kube.*
  Path              /var/log/containers/*.log
  Parser            docker
  DB                /var/log/flb_kube.db
  Skip_Long_Lines   On
  Refresh_Interval  10

[FILTER]
  Name                kubernetes
  Match               kube.*
  Kube_URL            https://kubernetes.default.svc:443
  Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
  Kube_Tag_Prefix     kube.var.log.containers.
  Merge_Log           On
  Keep_Log            Off
  K8S-Logging.Parser  On
  K8S-Logging.Exclude Off

[FILTER]
  Name    lua
  Match   kube.*
  script  /fluent-bit/etc/kubeparse.lua
  call    set_topic

[FILTER]
  Name                nest
  Match               kube.*
  Operation           lift
  Nested_under        kubernetes
  Add_prefix          kubernetes_

[FILTER]
  Name                nest
  Match               kube.*
  Operation           lift
  Nested_under        kubernetes_labels
  Add_prefix          kubernetes_labels_

[FILTER]
  Name    modify
  Match   kube.*
  Rename  kubernetes_labels_pod-template-hash kubernetes_labels_pod_template_hash


[OUTPUT]
  workers 4
  Name           kafka
  Match          kube.*
  Brokers        ${KAFKA_BROKERS}
  Topics         logs.unparsed
  dynamic_topic  true
  topic_key      topic_key
  rdkafka.debug All
  rdkafka.security.protocol sasl_ssl
  rdkafka.enable.ssl.certificate.verification false
  rdkafka.sasl.username <user_name>
  rdkafka.sasl.password ${KAFKA_PASSWORD}
  rdkafka.sasl.mechanism SCRAM-SHA-512
  Timestamp_Key  @timestamp
  Retry_Limit    false
  
  rdkafka.log.connection.close false
  
  rdkafka.queue.buffering.max.kbytes 10240
  
  rdkafka.request.required.acks 1
  rdkafka.compression.codec snappy
  rdkafka.queue.buffering.max.ms 20`

**kubeparse.lua**
`function set_topic(tag, timestamp, record)
    if record["kubernetes"]["namespace_name"] ~= nil then
      record["topic_key"] = "logs."
        .. record["kubernetes"]["namespace_name"]
    end
  return 2, timestamp, record
end`


plz help, @agup006 @dengalebr and reopen issues
