### ISSUE TITLE
Loki output plugin: Support HTTPS

### ISSUE THREAD

**Issue by nweseloh** [fluent/fluent-bit#2791]
**Is your feature request related to a problem? Please describe.**
The Loki output currently does not support HTTPS scheme. 

**Describe the solution you'd like**
Support HTTPS in Loki output plugin. Add a config option for the protocol scheme (HTTP / HTTPS).

**Additional context**
The missing HTTPS support prevents us from using the Loki output plugin in production scenarios and especially with Grafana cloud, as mentioned in #2735.

**Comment by edsiper** [comment]
Not documented inside the plugin (to be fixed) but every output plugin in Fluent Bit that does Network I/O can enable TLS on demand, please refer to this section:

https://docs.fluentbit.io/manual/administration/security

you can enable any TLS feature in the Loki output section
