### ISSUE TITLE
kmsg not initializing

### ISSUE THREAD

**Issue by yitzchak-eleff** [fluent/fluent-bit#2796]
## Bug Report

**Describe the bug**
When deploying fluent-bit (appVersion: 1.3.7) to kubernetes with kmsg enabled, I keep getting this error:
- "[error] Failed initialize input kmsg.1"

I've added the kmsg capability in accordance with this tutorial:
- https://docs.fluentbit.io/manual/pipeline/inputs/kernel-logs 

I've granted fluent-bit "CAP_SYSLOG" privileges in accordance with this documentation:
- https://www.docker.com/blog/capturing-logs-in-docker-desktop/ 
"Note that reading kernel logs via /dev/kmsg is a privileged operation and so the kmsg service needs the capability CAP_SYSLOG."

I've also tried several other privileges, none have worked:

#  capabilities:
#    add:   ["CAP_SYS_ADMIN"]
#    add:   ["CAP_SYSLOG"]
#    add:   ["SYSLOG"]

Only "privileged: true" seems to work

**To Reproduce**
- Example log message if applicable:
```
"[error] Failed initialize input kmsg.1"
```

**Expected behavior**
kmsg should run, and I should be able to see kernel logs (when searching in Kibana)

**Screenshots**
![image](https://user-images.githubusercontent.com/74900957/99947065-15383100-2d80-11eb-9744-3387f1f45e5b.png)

**Your Environment**
Kubernetes cluster
Fluent-bit appVersion: 1.3.7

**Additional context**
No access to kernel logs. These are needed in order to debug none-level problems

**Comment by andriyvasylyna** [comment]
I hit the same issue
k8s version 1.25
fluent-bit version: 1.8.9

To make it work I had to either use `privileged: true`  or set  `kernel.dmesg_restrict=0` parameter by sysctl.
I don't think it is actually a fluent-bit problem as with `CAP_SYSLOG` set I was able to use dmesg or read from `/proc/kmsg`. 
It is just `/dev/kmsg` not working.
