### ISSUE TITLE
NO_PROXY not supported

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit#2805]
## Bug Report

**Describe the bug**
I am using Fluent Bit to send logs from EKS to CloudWatch. Unfortunately, I am running into the following issue:
- If I don't set proxies, Fluent Bit cannot connect to CloudWatch
- If I do set proxies, Fluent Bit can connect to CloudWatch, but the Kubernetes Metadata Filter can no longer connect to the Kubernetes API, meaning that the logs no longer have any Kubernetes metadata.

The obvious solution is to add the Kubernetes API host (`kubernetes.default.svc`) to the `NO_PROXY` environment variable -- unfortunately, that doesn't seem to have any effect. Whether I add the Kubernetes API host to `NO_PROXY` or not, I get the same error in Fluent Bit's logs, where it tries (and fails) to connect to the Kubernetes API server through the proxy:

```
Fluent Bit v1.6.4
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/11/25 02:16:49] [ info] [engine] started (pid=1)
[2020/11/25 02:16:49] [ info] [storage] version=1.0.6, initializing...
[2020/11/25 02:16:49] [ info] [storage] in-memory
[2020/11/25 02:16:49] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/11/25 02:16:49] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2020/11/25 02:16:49] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2020/11/25 02:16:49] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2020/11/25 02:16:49] [error] flb_establish_proxy error: 
(HTML error page returned by my proxy, including the requested URL below)
...
ERROR: The requested URL could not be retrieved: https://kubernetes.default.svc/*

[2020/11/25 02:16:49] [error] [filter:kubernetes:kubernetes.0] upstream connection error
[2020/11/25 02:16:49] [ warn] [filter:kubernetes:kubernetes.0] could not get meta for POD fluentbit
```

**Thus, it appears that Fluent Bit does not respect NO_PROXY and, even if a particular host is listed in NO_PROXY, still attempts to connect to that host via the proxy.**

**To Reproduce**
- Configure `HTTP_PROXY` and `NO_PROXY` as environment variables.
- Add Kubernetes API host to `NO_PROXY`
- See that calls to the Kubernetes API still try to go through the proxy defined in `HTTP_PROXY`

**Expected behavior**
If a host is defined in `NO_PROXY`, then any calls Fluent Bit makes to those hosts should NOT go through any proxies.

**Your Environment**

* Fluent Bit Docker Image Version: `1.6.4-debug`

* Configuration:
-- Proxy config:
```
...
containers:
- name: fluent-bit
  env:
    - name: HTTP_PROXY
      value: ...
    - name: HTTPS_PROXY
      value: ...
    - name: NO_PROXY
      value: kubernetes.default.svc,localhost,127.0.0.1,169.254.169.254,...
```

-- Kubernetes Filter:
```
[FILTER]
  Name                    kubernetes
  Match                   kube.*
  Kube_Tag_Prefix         kube.var.log.containers.
  K8S-Logging.Parser      On
  K8S-Logging.Exclude     On
```

* Environment: Kubernetes (EKS)

* Filters and plugins:
-- Tail input
-- Kubernetes filter
-- CloudWatch Logs (`cloudwatch_logs`) output

**Additional Context**
I see that global support for `HTTP_PROXY` was added in #2694 -- however, looking at that pull request, I do not see any mention of `NO_PROXY`, which makes me suspect that Fluent Bit does not currently support the `NO_PROXY` environment variable.

(Incidentally, although I initially assumed it must be there, I also see no mention of `HTTPS_PROXY` -- thus, since Fluent Bit apparently only supports `HTTP_PROXY`, there is no way to potentially send HTTP traffic to one proxy, and HTTP**S** traffic to a different proxy -- I don't know how likely a situation that is though).

**Comment by pranavmarla** [comment]
@erain @edsiper I'm sure you're all busy but, when you have time, would appreciate any help you can provide!

**Comment by erain** [comment]
Hi @pranavmarla , AFAIK `NO_PROXY` is currently not supported yet. So this is more like a feature request. 

Unfortunately I don't have much bandwidth recently. So I would suggest you to open a new "Feature Request" issue with requirements clearly declared, and see whether someone from the community (or yourself!) can help implement it. 

If nobody sign up for that, I may give it a try when I get bored during the end of year holidays

**Comment by pranavmarla** [comment]
Thanks for confirming, @erain!

**Comment by PettitWesley** [comment]
Sorry this might be dumb... I am not a real k8s person, but isn't the API server `https://kubernetes.default.svc.cluster.local:443`

**Comment by pranavmarla** [comment]
@PettitWesley Hey, thanks for looking at this -- and don't worry, I'm not exactly a Kubernetes expert either ;)

I'm assuming that the Kubernetes API server URL that is being called by the built-in Kubernetes metadata filter (i.e. the endpoint of the call that is failing when I set HTTP_PROXY) is `https://kubernetes.default.svc` because that is what it says in the logs (generated by the Kubernetes metadata filter) as well as in the HTML error page returned by my proxy.

Also, as confirmed by _erain_ above, it appears that NO_PROXY is simply not supported by Fluent Bit at this time, implying that it doesn't actually matter what URL I do/don't mention in NO_PROXY.

**Comment by edsiper** [comment]
Quick workaround would be to turn off proxy for Kubernetes filter... (this need some coding)

**Comment by pranavmarla** [comment]
Thanks @edsiper , the ability to tell the Kubernetes metadata filter to ignore `HTTP_PROXY` would definitely be a good short-term fix as it would solve this immediate issue.

Long term of course, there may be other plugins that also should not be going through `HTTP_PROXY` -- so, I think adding `NO_PROXY` support is still a good long-term solution, as it grants that flexibility (to ignore `HTTP_PROXY`) to all of Fluent Bit.

**Comment by Fodoj** [comment]
As a workaround, you can use VPC endpoints to avoid going over internet, thus removing the need for proxy: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_sts_vpce.html.

**Comment by pranavmarla** [comment]
bump

**Comment by pranavmarla** [comment]
bump

**Comment by erain** [comment]
I am going to work on this feature.

**Comment by qingling128** [comment]
+1 for this feature.

**Comment by pranavmarla** [comment]
bump
