### ISSUE TITLE
Support managed identity for Azure Blob output

### ISSUE THREAD

**Issue by nilsga** [fluent/fluent-bit#2814]
In addition to shared key authorization for Azure Blob output, it would be nice to be able to use managed identities in environments that support this, such as Azure Kubernetes Service. Managed identities makes it easier to manage fine grained access, and to avoid having secrets that need to be rotated.

**Comment by nilsga** [comment]
Although this has been inactive, I think it is sill valid.

**Comment by david-yu** [comment]
Agreed this is still valid and looks like it is required if you are building managed applications that also need to have logging enabled without manually updating credentials when they are expired.

**Comment by OpzekerIT** [comment]
We also have this issue. Is there a possibility that this will be implemented in the future ?

**Comment by michelefa1988** [comment]
Also have this issue

**Comment by jrcast** [comment]
+1

**Comment by jrcast** [comment]
For anyone looking for a solution, as a workaround, you can use the CSI Blob Driver for Azure. See: https://github.com/kubernetes-sigs/blob-csi-driver 

You can authenticate the blob driver using an Azure Identity, mount the blob in the FluentBit pod as a PVC, and use the "file" FluentBit output pointed to the corresponding volume path. Note: The CSI driver stores files in the PVC as block blobs.

**Comment by sstarcher** [comment]
Can we stop making this as stale?

**Comment by vladimirglazkov** [comment]
Plus from my side, can help with testing.

**Comment by dhilipkumars** [comment]
+1

**Comment by dhilipkumars** [comment]
@edsiper @leonardo-albertovich this request seems still relevant.  Can we re-open this issue please.

**Comment by prateek1192** [comment]
I would be happy to contribute as well if this would be accepted

**Comment by mansi1597** [comment]
Is someone working on this? I am looking for a solution to send logs from fluent bit container to kusto. Currently, we use client id and secret. We are trying to move away from secret. Is there any way we can atleast move to certificate instead of secret if managed identity solution is going to take time?

**Comment by atul-ram** [comment]
+1

**Comment by sstarcher** [comment]
Can this please be reopened or do we need to open a new ticket?
