### ISSUE TITLE
Loki plugin - remove labels from Loki fields

### ISSUE THREAD

**Issue by jcdauchy-moodys** [fluent/fluent-bit#2821]
## Bug Report

**Describe the bug**
Using line_format=key_value, labels are pushed as fields to LOKI

**To Reproduce**
Here is an example of parsed fields, the following attributes are "labels" : 
- k8s_pod_name
- k8s_namespace_name
- k8s_container_name

```
k8s_pod_name="grafana-xxxxxx" k8s_namespace_name="monitoring" k8s_host="ip-xxxxxxxx.xxxxx-1.compute.internal" k8s_container_name="grafana" level="info" message="Request Completed" logger="context" userId="0" orgId="0" uname=null method="GET" path="/" status="302" remote_addr="172.17.0.1" time_ms="0" size="37" referer=null
```
- Steps to reproduce the problem:

Here is my configuration : 
```
[OUTPUT]
    Name loki
    # For the moment, we send all containers kube
    Match kube.*
    # For fluent-bit native loki plugin
    #host loki-distributor.monitoring.svc.cluster.local
    host ${LOKI_IP}
    # Port 3100
    port ${LOKI_PORT}
    # List of keys to use as Labels in Loki
    labels component=k8s-containers
    # Which fields are used as labels : https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/record-accessor
    label_keys $k8s_namespace_name,$k8s_container_name,$k8s_pod_name
    # Send as logfmt format
    line_format key_value
```
**Expected behavior**

All labels should be removed from fields sent to LOKI

**Screenshots**

![image](https://user-images.githubusercontent.com/56868940/100761246-fa566400-33f2-11eb-868a-9fb2a8be52d0.png)

**Your Environment**

* Version used: 1.6.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.16
* Operating System and version: Linux AWS
* Filters and plugins: Loki  plugin

**Comment by zhiguangwang** [comment]
Same here: using fluent-bit 1.6.8, can reproduce with either `line_format=key_value` or `line_format=json`.

It would be nice to provide a configuration parameter `remove_label_fields`, like [vector](https://vector.dev/docs/reference/sinks/loki/#remove_label_fields).

**Comment by l2dy** [comment]
FYI, Loki's official Fluent Bit output plugin (written in Go) supports this and it's the default behavior. https://github.com/grafana/loki/tree/master/cmd/fluent-bit

**Comment by phin1x** [comment]
The loki team plans to deprecate their go plugin. From the loki 2.1 release notes:

"...In time our plan is to deprecate and eliminate our output plugin in favor of the native Loki support. However until then you can continue using the plugin with the following change..."

In my opinion the missing remove_label_fields parameter is the reason not to use the output plugin. I don't want to have the time or labels, which i already send as stream labels in the log line.
The loki go plugin also converts the log line from kv/json to a single plain log line, if only the log key remains. this is also a nice feature because we don't need to parse the log line in loki again.

**Comment by l2dy** [comment]
> In my opinion the missing remove_label_fields parameter is the reason not to use the output plugin. I don't want to have the time or labels, which i already send as stream labels in the log line.

I have implemented this in #2995, try it out.

> The loki go plugin also converts the log line from kv/json to a single plain log line, if only the log key remains. this is also a nice feature because we don't need to parse the log line in loki again.

Is that the `DropSingleKey` option from the grafana-loki Go plugin?

**Comment by phin1x** [comment]
Thanks for implementing the drop label feature. i will try it out in the next days.

> Is that the `DropSingleKey` option from the grafana-loki Go plugin?

yes, i meant the option `DropSingleKey` (i thought this is the default behavior).

**Comment by jcdauchy-moodys** [comment]
Testing the master branch + your PR for the last 2 days (not on heavy load) but it seems to work !

Any other inputs ? Hope it will go inside the next 1.7.0 release ?

**Comment by l2dy** [comment]
> > Is that the `DropSingleKey` option from the grafana-loki Go plugin?
> 
> yes, i meant the option `DropSingleKey` (i thought this is the default behavior).

@phin1x Yes, this option is on by default. You should open another issue for this feature. I have refactored my code to make it easier to implement.

**Comment by phin1x** [comment]
@l2dy i opened a new issue #3005

**Comment by edsiper** [comment]
The problem has been solved on GIT master (upcoming v1.7 release)

- new ```remove_keys``` option. This supports the record accessor feature so you can remove a nested key if required.
- auto-remove of keys that are handled as labels

**Comment by baurine** [comment]
hi, it seems there are no related documents about this change in https://docs.fluentbit.io/manual/pipeline/outputs/loki

**Comment by baurine** [comment]
Hi, is this feature released in version 1.7? I tried 1.7.7, it seems the `remove_keys` doesn't work.

fluent-bit version:

```
Fluent Bit v1.7.7
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
```

My fluent-bit loki plugin config:

```
    [Output]
        name loki
        match kube.*
        host logs-prod-us-central1.grafana.net
        port 443
        tls On
        tls.verify Off
        http_user ***
        http_passwd ***
        tenant_id ""
        labels job=fluent-bit-bao, namespace=$kubernetes['namespace_name'], app=$kubernetes['labels']['app'], release=$kubernetes['labels']['release'], node=$kubernetes['host'], container=$kubernetes['container_name'], instance=$kubernetes['pod_name'], syslog=$kubernetes['SYSLOG_IDENTIFIER'], node=$kubernetes['_HOSTNAME'], stream=$stream
        remove_keys kubernetes
        auto_kubernetes_labels Off
        line_format json
```

What I get:

`kubernetes` key and value are still in the log body.

![image](https://user-images.githubusercontent.com/1284531/120354076-c1ad2e00-c334-11eb-986c-d5a3c3a7cf63.png)

What I expect:

(the below result is generated by grafana-loki fluent-bit plugin which `RemoveKeys` works fine in)

![image](https://user-images.githubusercontent.com/1284531/120354657-32544a80-c335-11eb-9557-6a12fc012786.png)

**Comment by baurine** [comment]
> The problem has been solved on GIT master (upcoming v1.7 release)
> 
> * new `remove_keys` option. This supports the record accessor feature so you can remove a nested key if required.
> * auto-remove of keys that are handled as labels

Hi @edsiper , I checked the release notes from v1.7.0 to v1.7.7, it seems nowhere mentioned these changes, only the version [v.17.5 release note](https://fluentbit.io/announcements/v1.7.5/) mentioned the implementation of `drop_single_key`.

Can you help confirm it? thanks!

**Comment by nokute78** [comment]
@baurine You can see the option of loki like this.
`fluent-bit  -o loki -h`

I saw old commits and there are supported versions.

`remove_keys` is supported from v1.7.0.
`drop_single_key` is supported from v1.7.5.

**Comment by baurine** [comment]
> @baurine You can see the option of loki like this.
> `fluent-bit -o loki -h`
> 
> I saw old commits and there are supported versions.
> 
> `remove_keys` is supported from v1.7.0.
> `drop_single_key` is supported from v1.7.5.

Got it, thank you! Can you guys help update the document in https://docs.fluentbit.io/manual/pipeline/outputs/loki ? The above 2 properties are not mentioned in the doc totally.

**Comment by baurine** [comment]
> @baurine You can see the option of loki like this.
> `fluent-bit -o loki -h`
> 
> I saw old commits and there are supported versions.
> 
> `remove_keys` is supported from v1.7.0.
> `drop_single_key` is supported from v1.7.5.

Got it, thank you! @nokute78 , Can you guys help update the document in https://docs.fluentbit.io/manual/pipeline/outputs/loki ? The above 2 properties are not mentioned in the doc totally.

**Comment by mierzej91** [comment]
Why this issue is closed? As a @baurine mentioned remove_keys doesn't work for an array key's such as kubernetes. I have this same problem and it's so frustrating
