### ISSUE TITLE
output plugin http incorrect link to tls/ssl docs

### ISSUE THREAD

**Issue by Globegitter** [fluent/fluent-bit#285]
On this page: http://fluentbit.io/documentation/0.11/output/http.html one gets referred to http://fluentbit.io/documentation/0.11/getting_started/tls_ssl.md for TLS/SSL docs, which leads to a dead end.

**Comment by edsiper** [comment]
thanks for report this problem.

It have been fixed on https://github.com/fluent/fluent-bit-docs/commit/5d9cba00be40d7164b90500c1035292d29ae0dc9 .
