### ISSUE TITLE
 fluent-bit_1.6.8.bb: FLB_IN_SYSTEMD input plugin not included

### ISSUE THREAD

**Issue by Styne13** [fluent/fluent-bit#2851]
## Bug Report

**Describe the bug**
Build option FLB_IN_SYSTEMD=On is not taken into account when building via fluent-bit_1.6.8.bb yocto bitbake. Also tried global option `FLB_ALL=Yes` without success.

Steps to Reproduce:
- Add `EXTRA_OECMAKE += "-DFLB_IN_SYSTEMD=On "` to bitbake recipe and build `bitbake fluent-bit`

Errors:
- `fluent-bit --help` does not display input option `systemd` and Build Flags are not shown
- `fluent-bit -i systemd -o stdout` displays `Error: Invalid input type. Aborting`

**Comment by edsiper** [comment]
I think in addition to enable the plugin you have to include the dev dependency in your image, so Fluent Bit build system can check for systemd headers

**Comment by Styne13** [comment]
Thank you for your quick reply @edsiper

Does `dev` mean device or development here?
Can you give an advise how to add it to the recipe?
Is it something like `DEPENDS += `

**Comment by ygoyal18** [comment]
@Styne13 We also ran into the same issue. Adding the `systemd` as depends and CMake flag `DFLB_IN_SYSTEMD` in the recipe seems to fix it. 

```
DEPENDS += "systemd"
EXTRA_OECMAKE += "-DFLB_IN_SYSTEMD=On "
```

**Comment by Styne13** [comment]
@ygoyal18: Thanks for your reply. 👍 Will check if this works.

**Comment by DK999** [comment]
> 
> 
> @Styne13 We also ran into the same issue. Adding the `systemd` as depends and CMake flag `DFLB_IN_SYSTEMD` in the recipe seems to fix it.
> 
> ```
> DEPENDS += "systemd"
> EXTRA_OECMAKE += "-DFLB_IN_SYSTEMD=On "
> ```

Works fine, fixed the issue for me too.

**Comment by edsiper** [comment]
thanks for the comments.

FYI: v1.7.0 will come with Systemd support enabled (6e63092d)
