### ISSUE TITLE
enable cache off on kubernetes filter.

### ISSUE THREAD

**Issue by aheeruru** [fluent/fluent-bit#2858]
**Is your feature request related to a problem? Please describe.**

When use same pod_name on same namespace, it cached until restart fluent bit.
So fluent bit gather log on same file even if different pod has same name and namespace as previous pod. 

**Describe the solution you'd like**

I used kubeflow's(https://www.kubeflow.org/) PytorchJob, TfJob.
If i create PytorchJob named 'AAA', it creates pods with specific format likes statefulset. ex ) 'AAA-worker-0' 'AAA-worker-1'.
So I create new PytorchJob named 'AAA' after old PytorchJob 'AAA' ended, new PytorchJob create pod 'AAA-worker-0' 'AAA-worker-1' likes previous Job. 
They are different job and pod but Fluent bit recognize same pod cause cached namespace and pod,  so gather log on same file.

I deleted option "Kube_meta_preload_cache_dir" but it seems to fluent bit cache data continuous.

**Describe alternatives you've considered**

There are two way.
1. Add cache off option on kubernetes filter.
2. Cache pod_uid option
   - pod_uid is unique, so it can distinguish old pod and new pod have same name.

**Comment by donbowman** [comment]
the preload cache dir is more for testing than run time.
you want a watch on the kubernetes resources to flush the internals of fluent-bit.
this has been discussed before but it is not yet implemented.

**Comment by aheeruru** [comment]
Thanks to reply :)
Is there plan to implement it?
