### ISSUE TITLE
Elasticsearch output throws content-type rest warning in elasticsearch

### ISSUE THREAD

**Issue by gamer22026** [fluent/fluent-bit#286]
Using elasticsearch output on latest fluent-bit docker image (0.11.6) writing to elasticsearch 5.4 causes the following error each time fluent-bit connects.

`[2017-05-31T18:07:25,001][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.`

**Comment by edsiper** [comment]
Thanks for reporting this issue. 

I have merged a fix on master and in 0.11 branch (to be released as 0.11.8 soon)
