### ISSUE TITLE
Dump event details on GELF encoding errors

### ISSUE THREAD

**Issue by stephan2012** [fluent/fluent-bit#2863]
**Is your feature request related to a problem? Please describe.**

When seeing messages like

```
[2020/12/14 14:51:41] [error] [flb_msgpack_to_gelf] missing short_message key
[2020/12/14 14:51:41] [error] [output:gelf:gelf.0] error encoding to GELF
```

it would be quite helpful to see the event and its fields that caused the error. 

**Describe the solution you'd like**

Dump all information available when an encoding error occurs. Optionally, introduce a switch that enables detailed information.

**Describe alternatives you've considered**

Adding another `OUTPUT` to `stdout` does not always help due to the vast amount of messages that fluent-bit processes. Also, the event causing the encoding error may not be easily reproducible.

**Additional context**

It sometimes really drives me nuts finding the source of failed processing Kubernetes Pods logs …

**Comment by stephan2012** [comment]
Would still be nice to have.

**Comment by stephan2012** [comment]
Still desirable …

**Comment by stephan2012** [comment]
Still helpful to track down the source of missing information …

**Comment by pschichtel** [comment]
@stephan2012 I guess this still an issue, right?

**Comment by pschichtel** [comment]
@stephan2012 I tried this which helped a little: https://github.com/pschichtel/fluent-bit/commit/cc5152674ae59af12335fec05928b731ace1b380

A container based on that state can be found at: https://hub.docker.com/repository/docker/pschichtel/fluent-bit-gelf-debug

**Comment by stephan2012** [comment]
@pschichtel Yes, this is still an issue. Thank you for your efforts. I’ll try to test your build within the following days.
