### ISSUE TITLE
Ability to mark all fields as json.

### ISSUE THREAD

**Issue by maheskrishnan** [fluent/fluent-bit#2877]
Currently we have to specify what fields are in json format explicitly. for example

```
Decode_Field_As   escaped    message
Decode_Field_As   escaped    log
Decode_Field_As   escaped    userInfo
```

it would be nice if we can specify something like this
`Decode_Field_As   escaped    * # means all fields should be treated as json.
`
Thanks

**Comment by edsiper** [comment]
FYI: this is not necessary, decoders should not be user if you are using docker parser, it works without problems.
