### ISSUE TITLE
out_splunk: "Invalid data format"

### ISSUE THREAD

**Issue by logston** [fluent/fluent-bit#2881]
## Bug Report

Consistently getting the following error in the fluentbit logs when using the `out_splunk` plugin:

```
{"text":"Invalid data format","code":6,"invalid-event-number":0}
```

I'm running fluentbit in a k8s environment as a daemonset and my `ConfigMap` is as follows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |-
    [SERVICE]
        # Flush
        # =====
        # Set an interval of seconds before to flush records to a destination
        Flush        1

        # Daemon
        # ======
        # Instruct Fluent Bit to run in foreground or background mode.
        Daemon       Off

        # Log_Level
        # =========
        # Set the verbosity level of the service, values can be:
        #
        # - error
        # - warning
        # - info
        # - debug
        # - trace
        #
        # By default 'info' is set, that means it includes 'error' and 'warning'.
        Log_Level    trace

        # Parsers_File
        # ============
        # Specify an optional 'Parsers' configuration file
        Parsers_File parsers.conf
        Plugins_File plugins.conf

        # HTTP Server
        # ===========
        # Enable/Disable the built-in HTTP Server for metrics
        HTTP_Server  Off
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    @INCLUDE inputs.conf
    @INCLUDE outputs.conf

  inputs.conf: |-
    [INPUT]
        Name        tail
        Path        /var/log/app-logs/date.log

  outputs.conf: |-
    [OUTPUT]
        Name            stdout
        Match           *

    [OUTPUT]
        Name            splunk
        Match           *
        Host            http-inputs-app.splunkcloud.com
        Port            443
        TLS             On
        Splunk_Token    ${SPLUNK_HEC_TOKEN}
```

I've used the standard fluentbit:1.6.8 image as well as my own 1.6.8 image. Both yield the same result. My custom image contains a minor change allowing me to see the body sent to Splunk. The diff for my image is here:

```
diff --git a/plugins/out_splunk/splunk.c b/plugins/out_splunk/splunk.c
index 2ef9bd7b..7cc4118b 100644
--- a/plugins/out_splunk/splunk.c
+++ b/plugins/out_splunk/splunk.c
@@ -204,6 +204,7 @@ static void cb_splunk_flush(const void *data, size_t bytes,
             if (c->resp.payload_size > 0) {
                 flb_plg_warn(ctx->ins, "http_status=%i:\n%s",
                          c->resp.status, c->resp.payload);
+    			flb_plg_warn(ctx->ins, "http_body_from_cb_splunk_flush=\n'%s'", buf_data);
             }
             else {
                 flb_plg_warn(ctx->ins, "http_status=%i", c->resp.status);
diff --git a/src/flb_http_client.c b/src/flb_http_client.c
index 470926ad..47d286a2 100644
--- a/src/flb_http_client.c
+++ b/src/flb_http_client.c
@@ -1122,6 +1122,7 @@ int flb_http_do(struct flb_http_client *c, size_t *bytes)
     }
 
     if (c->body_len > 0) {
+        flb_debug("[http_client] body=\n'%s'", c->body_buf);
         ret = flb_io_net_write(c->u_conn,
                                c->body_buf, c->body_len,
                                &bytes_body);
```

It yields logs like the following...

```
[2020/12/21 01:20:53] [debug] [input:tail:tail.0] inode=15869132 events: IN_MODIFY 
[2020/12/21 01:20:54] [debug] [task] created task=0x7f82282555a0 id=0 OK
[0] tail.0: [1608513653.964218170, {"log"=>"Mon Dec 21 01:20:53 UTC 2020"}]
[2020/12/21 01:20:54] [debug] [http_client] not using http_proxy for header
[2020/12/21 01:20:54] [debug] [http_client] header=POST /services/collector/event HTTP/1.1
Host: http-inputs-app.splunkcloud.com
Content-Length: 73
User-Agent: Fluent-Bit
Authorization: Splunk XXXXXXXXXXXXXXXXXXXXX



[2020/12/21 01:20:54] [debug] [http_client] body=
'{"time":1608513653.964218,"event":{"log":"Mon Dec 21 01:20:53 UTC 2020"}}'
[2020/12/21 01:20:54] [ warn] [output:splunk:splunk.1] http_status=400:
{"text":"Invalid data format","code":6,"invalid-event-number":0}
[2020/12/21 01:20:54] [ warn] [output:splunk:splunk.1] http_body_from_cb_splunk_flush=
'{"time":1608513653.964218,"event":{"log":"Mon Dec 21 01:20:53 UTC 2020"}}'
[2020/12/21 01:20:54] [debug] [upstream] KA connection #37 to http-inputs-app.splunkcloud.com:443 is now available
[2020/12/21 01:20:54] [debug] [task] destroy task=0x7f82282555a0 (task_id=0)
```

This appears to be the format of the body: 

`{"time":1608513653.964218,"event":{"log":"Mon Dec 21 01:20:53 UTC 2020"}}'`

The value of the "log" key is just the output of `date` in order to demonstrate this issue. This is also happening with other longer log lines.

**To Reproduce**
To reproduce, you can run a busybox image that logs to a mounted volume. That volume will be a `hostPath` volume. From the fluenbit daemonset, mount the same host path at a path of your choosing. Tail the logs files in the mounted path. Set up the splunk plugin to forward to splunkcloud. 

**Expected behavior**

I expect the logs to be forwarded without issue. (No http 400 response)

**Screenshots**
These are the settings for the HEC token in Splunk Cloud

<img width="794" alt="Screen Shot 2020-12-20 at 4 37 10 PM" src="https://user-images.githubusercontent.com/2641765/102730585-00e94480-42ea-11eb-97d0-f0817ae2f5ff.png">

**Your Environment**
* Fluentbit 1.6.8
* K8s Rev: v1.15.12-eks-31566f
* Splunk Cloud 8.1.2009

I've tried turning on and off `splunk_send_raw` and adding filters to nest the logs under the event key, eg:

```
# nest the record under the 'event' key
[FILTER]
    Name nest
    Match *
    Operation nest
    Wildcard *
    Nest_under event

# add event metadata
[FILTER]
    Name      modify
    Match     *

[OUTPUT]
    Name        splunk
    Match       *
    Host        127.0.0.1
    Splunk_Token xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
    Splunk_Send_Raw On
```

I've also enabled and disabled indexer-acknowlegement within splunk cloud. Neither option worked.

**Comment by agup006** [comment]
I've been using Splunk Enterprise 8.1 with Fluent Bit 1.6.9 - here is my configuration for HEC. Only difference I see is the JSON source type. I haven't tried Splunk Cloud but will give it a shot as they have a 15 day free trial

![image](https://user-images.githubusercontent.com/3642874/102744874-a5ca4880-430f-11eb-8f85-ba1f0a94e6eb.png)

**Comment by agup006** [comment]
Tried out Splunk Cloud- same `_json` source type seems to work as well. Here's my output configuration with K8s filter + container log input
```
    [OUTPUT]
        name splunk
        Match  *
        Host   <WORKSPACE>.splunkcloud.com
        Splunk_Token <TOKEN>
        tls on
        tls.verify off
```
and here's the output in Splunk Cloud 
![image](https://user-images.githubusercontent.com/3642874/102745474-e70f2800-4310-11eb-8a99-0d6464a43a28.png)

**Comment by agup006** [comment]
Ah, I also noticed that I did not specify the port -  which may make a difference too. 8088 is used by default vs 443 not 100% sure if that makes a difference.

**Comment by logston** [comment]
Thanks @agup006. I've tried changing the source type to `_json` but that does not do the trick. 

After piping the contents to a Request Bin and reviewing the results, it appears that the last two bytes are shaved off of the POST request:

```

{"time":1608580690.955052,"event":{"log":"Mon Dec 21 19:58:10 UTC 2020"
```

Notice also that the payload has a line break before the JSON object. I'm not sure why or how this is being inserted into the payload. 

I can confirm this with this patch: 

```
diff --git a/plugins/out_splunk/splunk.c b/plugins/out_splunk/splunk.c
index 2ef9bd7b..415c6aaa 100644
--- a/plugins/out_splunk/splunk.c
+++ b/plugins/out_splunk/splunk.c
@@ -186,6 +186,8 @@ static void cb_splunk_flush(const void *data, size_t bytes,
     }
     payload = (flb_sds_t) buf_data;
 
+	buf_size += 2;
+
     /* Compose HTTP Client request */
     c = flb_http_client(u_conn, FLB_HTTP_POST, FLB_SPLUNK_DEFAULT_URI,
                         buf_data, buf_size, NULL, 0, NULL, 0);
```

Just by adding two to the `buf_size`, everything seems to come through to Splunk and the Request Bin just fine.

**Comment by logston** [comment]
As it turns out, there was an extra `\n` at the end of my Authorization key. This pushed the payload by just enough to shave off the `}}` at the end of the JSON object.

**Comment by agup006** [comment]
Glad this resolved @logston and thank you for reporting, was really puzzling. Let me add a troubleshooting section to the Splunk output in case others run into the same issue
