### ISSUE TITLE
Feature request: Mechanism for multi-line strings as values in configuration file

### ISSUE THREAD

**Issue by cjoster** [fluent/fluent-bit#2887]
I'm proposing a mechanism to have a multi-line value in a key:value pair in the configuration file. I ran into a need for this specifically attempting to use a feature exposed to the kafka output plugin by the [librdkafka](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) library, although I imagine there could be, or are, other reasons for which this feature would be useful. The specific option we were looking at is `rdkafka.ssl.certificate.pem`, which, at least at the librdkafka library, takes an entire new-line-containing string of the PEM encoded TLS certificate as the parameter and there's no way to achieve this in the Fluent Bit configuration file.

I'm ready to write the PR, I just wanted to get a little discussion going on regarding exactly what the syntax of the mechanism (or mechanisms) should be and whether it should be gated with a new cli flag. Some ideas are:

- Escaping the new-line with a backslash (`\`) just prior to the new-line. This can be complicated by the existence other whitespace between the `\` and the new-line.
- Quoting a block of text. Parsing for nested quotations or escaping the quote could cause challenges.
- Not escaping any backslashes that proceed `n`s that might exist in an otherwise "single line" string. This could cause the most unintended consequences.
- Setting off a block of text yaml-style with a special character such as a pipe and/or greater-than. This option affords the most flexibility and customizations, but could prove challenging with indentation requirements.
- Any other option such as `<<EOF` a-la bash.

If this hasn't been discussed and refused before, I'm happy to contribute it. What should it look like and should a new CLI option be added to gate it?

**Comment by edsiper** [comment]
reopened.
