### ISSUE TITLE
Feature request: InfluxDB2 Support

### ISSUE THREAD

**Issue by runminlook** [fluent/fluent-bit#2896]
**Is your feature request related to a problem? Please describe.**

InfluxDB2 Support
InfluxDB2 need token authorization, which is different from InfluxDB1.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agup006** [comment]
This has been merged as an experimental feature for the next release (1.7.1)

**Comment by agup006** [comment]
Commit: 2af2bc44
