### ISSUE TITLE
Feature request: Support "tag" as a variable in cloudwatch_logs output plugin

### ISSUE THREAD

**Issue by wtchangdm** [fluent/fluent-bit#2899]
**Is your feature request related to a problem? Please describe.**

Hi all, this feature request is related to #2898, where we have a lot of CloudWatch Log Groups to send, according to the k8s workloads' namespace.
But the number of output is more than 32 it starts acting incorrectly.

Our current config for this purpose is:

1. Get information like namespace, pod, in `Tail` input plugin
    ```
    [INPUT]
            Name              tail
            Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})
            Tag               kube__<namespace_name>__<pod_name>__<container_name>__<docker_id>
            Path              /var/log/containers/*.log
            # ...(omitted)
    ```
1. Then leverage Helm Chart to render the outputs for the namespaces we set
    ```
    {{- range .Values.fluentbit.collectNamespaces }}
        [OUTPUT]
            Name                      cloudwatch_logs
            Match                     kube__{{ . }}__*
            region                    {{ $.Values.aws.region }}
            auto_create_group         On
            # Log group name will look like: "/some-prod-k8s-cluster/some-namespace"
            log_group_name            {{ $.Values.aws.logGroupPrefix }}/{{ . }}
            log_stream_name           {{ . }}-via-${HOSTNAME}
            # ...(omitted)
    {{- end }}
    ```
This will of course generate a lot of output blocks, and it's relatively difficult to read.

**Describe the solution you'd like**

I was checking on the previous [`cloudwatch`][1] output plugin, which supports variables like `$(tag)` in the `log_group_name` field.

If newer, more efficient `cloudwatch_logs` plugin supports this feature, I think all we need is:
1.  A slight tag change in tail input
2. Single output block with **`match`** set to **`*`** and **`log_group_name`** set to **`$(tag)`** (or in the form of **`$tag`** like [`rewrite_tag`][2] filter plugin).

**Describe alternatives you've considered**

For the issue we encountered in #2898, the fastest workaround is to migrate to the previous `cloudwatch` plugin, with the changes mentioned above. However, it looks like I will have to use another image to achieve this, where other bug fixes/improvements might take longer to deliver.

**Additional context**

All described above!

[1]: https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit#templating-log-group-and-stream-names
[2]: https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#new-tag

**Comment by wtchangdm** [comment]
I'd like to know is it possible to put into consideration?

**Comment by wmz7year** [comment]
Looks great, I also need this feature.

like this:
```
    [OUTPUT]
        Name              cloudwatch
        Match             kube-system
        region            cn-north-1
        log_group_name    /aws/cluster/#(kubernetes['namespace_name'])/#(kubernetes['container_name'])
        log_stream_name   #(kubernetes['pod_name'])-#(kubernetes['pod_id'])
        log_key           log
        auto_create_group true
```
