### ISSUE TITLE
"[error] [storage] cannot adjust chunk size" when using NFS mount for buffer file storage

### ISSUE THREAD

**Issue by theblop** [fluent/fluent-bit#2906]
## Bug Report

**Describe the bug**
fluentbit can't fallocate file chunks when storage is configured on an NFS mount.
Here is the relevant error message:
```
fluentbit_1      | [lib/chunkio/src/cio_file.c:332 errno=95] Operation not supported
fluentbit_1      | [2021/01/06 13:13:18] [error] [storage] cannot adjust chunk size '/fluent-bit/log/buffer//forward.0/1-1609938798.627941001.flb' to 4096 bytes
fluentbit_1      | [2021/01/06 13:13:18] [error] [input chunk] could not create chunk file: forward.0:1-1609938798.627941001.flb
fluentbit_1      | [2021/01/06 13:13:18] [error] [input chunk] no available chunk
```

This seems to be the root cause, and an additional check should be done for NFS mounts (or FS that don't support fallocate) and not just checking if fallocate() is available:
https://github.com/fluent/fluent-bit/blob/7aec5628df42408284f3b29a121efc8e90730e4d/lib/chunkio/src/cio_file.c#L1033

**To Reproduce**
- Steps to reproduce the problem:
Set storage.path to an NFS mount

**Expected behavior**
storage should work on NFS mounts

**Your Environment**

* Version used: fluentbit 1.6
* Operating System and version: fedora 32 + docker-compose 1.25.4, NFS version 3

**Comment by aditmeno** [comment]
@theblop I confirm I'm facing this same issue as well

**Comment by theblop** [comment]
actually the safest fix would be to try fallocate() if available and fall back to ftruncate() if it fails at runtime

**Comment by maglenno** [comment]
@theblop I too can confirm this is broken.

Fluentbit 1.7.1 
K8S 1.18 with Oracle FSS

[2021/03/02 20:07:13] [error] [storage] cannot adjust chunk size '/tmp/forward_external/1-1614715633.531236389.flb' to 4096 bytes
[2021/03/02 20:07:13] [error] [input chunk] could not create chunk file: forward_external:1-1614715633.531236389.flb
[2021/03/02 20:07:13] [error] [input chunk] no available chunk
[lib/chunkio/src/cio_file.c:332 errno=95] Operation not supported

**Comment by edsiper** [comment]
Most than "broken" I'd say "NFS is not supported yet". Even if the file allocation is done through a different syscall we will hit the problem with mmap. Fluent Bit uses mmap to manage the content of files, I am not confident mmap(2) + NFS is safe enough. 

This will need that we extend the support of the storage layer to support normal read/write operations.

**Comment by rajibmitra** [comment]
when can we expect to have this support @edsiper

**Comment by kuacuia2** [comment]
Hi @theblop we are facing similar issues when using AWS EFS in AWS EKS. 
fluentbit helm chart: fluent/fluent-bit, version 0.17.0
EKS version: v1.18.20-eks-8c49e2

Sample errors: 
[2022/02/20 22:25:11] [error] [fstore] cannot adjust chunk size '/tmp/buffer2/ndia-zscaler-logs/2022-02-20T22:11:38/12169912559166381988-17413663435888690454' to 4096 bytes
[2022/02/20 22:25:11] [error] [fstore] could not create file: 2022-02-20T22:11:38:12169912559166381988-17413663435888690454
[2022/02/20 22:25:11] [error] [output:s3:s3.0] could not create the file '12169912559166381988-17413663435888690454' in the store
[2022/02/20 22:25:11] [ warn] [output:s3:s3.0] Could not buffer chunk. Data order preservation will be compromised

Tried both emptydir and aws ebs persistent volumes as store_dir to locally buffer data for the fluent-bit S3 output plugin and they both worked fine. When switching back to efs persistent volumes, it failed right away with the above error messages. 

#fluent-bit configMap:
[OUTPUT]
    Name                         s3
    Match                        user_activity_logs
    bucket                       zscaler-logs
    region                       ap-southeast-2
    role_arn                     arn:aws:iam::1234567890123:role/s3-log-role
    total_file_size              3M
    upload_chunk_size            1M
    s3_key_format                /user-activity/%Y/%m/%d/%H/$UUID
    workers                      1
    store_dir                    /tmp/buffer2
    upload_timeout               2m

**Comment by frankfong0208** [comment]
Hi @theblop  we are currently facing similar issues when using AWS EFS in AWS EKS.
fluentbit helm chart: fluent/fluent-bit, version 0.17.0
EKS version: v1.18.20-eks-8c49e2

Sample errors:
[2022/02/20 22:25:11] [error] [fstore] cannot adjust chunk size '/tmp/buffer2/ndia-zscaler-logs/2022-02-20T22:11:38/12169912559166381988-17413663435888690454' to 4096 bytes
[2022/02/20 22:25:11] [error] [fstore] could not create file: 2022-02-20T22:11:38:12169912559166381988-17413663435888690454
[2022/02/20 22:25:11] [error] [output:s3:s3.0] could not create the file '12169912559166381988-17413663435888690454' in the store
[2022/02/20 22:25:11] [ warn] [output:s3:s3.0] Could not buffer chunk. Data order preservation will be compromised

Tried both emptydir and aws ebs persistent volumes as store_dir to locally buffer data for the fluent-bit S3 output plugin and they both worked fine. When switching back to efs persistent volumes, it failed right away with the above error messages.

#fluent-bit configMap:
[OUTPUT]
Name s3
Match user_activity_logs
bucket zscaler-logs
region ap-southeast-2
role_arn arn:aws:iam::1234567890123:role/s3-log-role
total_file_size 3M
upload_chunk_size 1M
s3_key_format /user-activity/%Y/%m/%d/%H/$UUID
workers 1
store_dir /tmp/buffer2
upload_timeout 2m

**Comment by frankfong0208** [comment]
Does someone know when this can be fixed?

**Comment by srideok2** [comment]
Any update on this issue? I am also facing this with NFS deployment on EKS.

**Comment by agup006** [comment]
@srideok2 @frankfong0208 no updates, is this something you would be able to help contribute?
