### ISSUE TITLE
Race condition in master branch

### ISSUE THREAD

**Issue by hsmatulisgoogle** [fluent/fluent-bit#2908]
Here is a race condition I found when debugging on `master`:

`ch_parent_events` is created in the worker thread without any signalling, so the parent can attempt to use it before its been defined:
https://github.com/fluent/fluent-bit/blob/530866b640f16eb0147e0bc8fd3a6054366a4a29/src/flb_output_thread.c#L176-L188
https://github.com/fluent/fluent-bit/blob/530866b640f16eb0147e0bc8fd3a6054366a4a29/src/flb_output_thread.c#L325
I imagine `ch_thread_events` would have a similar issue
https://github.com/fluent/fluent-bit/blob/530866b640f16eb0147e0bc8fd3a6054366a4a29/src/flb_output_thread.c#L198-L202

**Comment by edsiper** [comment]
ah! good one. So the pipe must be created in the output_thread interface before the thread is created, so it's just shared..

**Comment by edsiper** [comment]
Fixed in 78b0f6d97f6d
