### ISSUE TITLE
Timestamp sometimes disappears when using http output

### ISSUE THREAD

**Issue by tscully49** [fluent/fluent-bit#2913]
## Bug Report

**Describe the bug**
When we use a filter to COPY the "timestamp" attribute to a new attribute called "time", it seems like only one gets sent through.  If we use the ADD feature to create the "time" field, they both seem to get sent through.  We have only tested this using the http output with setting the Json_date_key to either "time" or "timestamp".  It seems like whichever we set as Json_date_time gets sent and the other gets dropped. 

**Expected behavior**
We are expecting that both "timestamp" and "time" are sent in the http call when using a COPY. 

**Your Environment**
* Version used:
  * AWS for Fluent Bit Container Image Version 2.10.0
  * Fluent Bit v1.6.8 
* Configuration:
```
[OUTPUT]
    Name             http
    Match            *
    Host             my-loggly-url.com
    Port             443
    tls              On
    URI              /bulk/${LOGGLY_TOKEN}/tag/${LOGGLY_TAG}/
    Format           json_lines
    Json_date_key    time
    Json_date_format iso8601
    Retry_Limit      False

[FILTER]
    Name             modify
    Match            *
    Copy             timestamp time
```
* Server type and version:
* Operating System and version:
  * AWS fargate with firelens
* Filters and plugins:

**Comment by tscully49** [comment]
We are wondering if fluentbit is getting rid of the timestamp field before it sends along the request or if there is something we are simply missing about the behavior here.

**Comment by edsiper** [comment]
Hi, thanks for reaching out.

So the workflow is always ```input``` > ```filter``` > ```output```. I tested the following config:

```
[SERVICE]
    flush            1
    log_level        info

[INPUT]
    name             dummy
    dummy            {"key1": 123, "timestamp": 1610064082}
    samples          1

[FILTER]
    name             modify
    match            *
    copy             timestamp time

[FILTER]
    name             stdout
    match            *
    
[OUTPUT]
    name             stdout
    match            *
    format           json_lines
    json_date_key    time
    json_date_format iso8601
```

the ```modify``` filter will "try" to copy the __key__ ```timestamp``` into ```time```. If the original record don't have such key nothing will happen. In my example, I created generated the ```timestamp``` key with value ```1610064082```

Then the ```stdout``` output will do a similar thing than the http output, but this time the json encoder appends a new ```time``` key at the beginning of the record and later the final record appends the original (copied) ```time``` key. Since there is a duplicated key the latest key is always preserved. Now if you set ```json_date_key``` to a different name, you will get all the expected values, e.g:

```
[SERVICE]
    flush            1
    log_level        info

[INPUT]
    name             dummy
    dummy            {"key1": 123, "timestamp": 1610064082}
    samples          1

[FILTER]
    name             modify
    match            *
    copy             timestamp time

[FILTER]
    name             stdout
    match            *
    
[OUTPUT]
    name             stdout
    match            *
    format           json_lines
    json_date_key    real_time
    json_date_format iso8601
```

output:

```
$ ../../build/bin/fluent-bit -c conf 
Fluent Bit v1.6.10
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/01/07 18:14:17] [ info] [engine] started (pid=2757251)
[2021/01/07 18:14:17] [ info] [storage] version=1.0.6, initializing...
[2021/01/07 18:14:17] [ info] [storage] in-memory
[2021/01/07 18:14:17] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/01/07 18:14:17] [ info] [sp] stream processor started
[0] dummy.0: [1610064857.922890228, {"key1"=>123, "timestamp"=>1610064082, "time"=>1610064082}]
{"real_time":"2021-01-08T00:14:17.922890Z","key1":123,"timestamp":1610064082,"time":1610064082}
```
