### ISSUE TITLE
Tag in Output plugins

### ISSUE THREAD

**Issue by yvvarun** [fluent/fluent-bit#2922]
I wanted to know if it's possible to add a Tag key in Output plugins like forward for example?
I'm using multiple forward plugins and I want to rewrite the Tag and assign a different Tag for each of them.

Example:

```
[INPUT]
    Name            tail
    Path            /mnt/ops/logs/darti_all*.log
    Tag             all 
    Skip_Long_Lines On
    DB              /mnt/ops/db/td-agent-all.db

[INPUT]
    Name            tail
    Path            /mnt/ops/logs/darti_ops*.log
    Tag             ops
    Skip_Long_Lines On
    DB              /mnt/ops/db/td-agent-ops.db

[OUTPUT]
    Name          forward
    Match          all 
    Tag              a/b/c
    Host            10.100.24.150
    Port             24224

[OUTPUT]
    Name          forward
    Match          ops
    Tag              x/y/z
    Host            10.100.24.150
    Port             24224
```

Fluentd is unable to recognize the rewritten tags (a/b/c, x/y/z). It's only able to recognize the original tags (all, ops) in the input plugins of fluent bit.

**Comment by agup006** [comment]
@yvvarun if you need the tag to be different in successive Fluent instances, it would probably be best to use rewrite tag filter first then have the forward output plugins match the new tag.

https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#configuration-example

**Comment by yvvarun** [comment]
I want to use different tags for different outputs, so how would rewrite tag filter help in such a case?
As per my understanding, rewrite tag filter might be helpful if all the output plugins used a single tag, right?

**Comment by agup006** [comment]
rewrite tag does not stop you from using different outputs, it allows you change the tag of inflight data which will influence your downstream pipeline in Fluentd. My understanding is you want to take darti_all*.logs give them a tag of a/b/c then have Fluentd perform some successive processing.

tail (tag: ops) ---> rewrite filter (tag:a) ---> output forward (tag:a) ---> | Fluentd | (performs pipeline based on tag:a)
tail (tag: all) ---> rewrite filter (tag: x) ----> output forward (tag:x) ---> | Fluentd | (performs pipeline based on tag:x)

**Comment by yvvarun** [comment]
tail (tag: ops) ---> output forward (match tag:ops, rewrite tag:/a/b/c) ---> | Fluentd | (performs pipeline based on tag:a)
tail (tag: ops) ---> rewrite filter (match tag:all --- convert to tag: x) ----> output forward (match tag:x) ---> | Fluentd | (performs pipeline based on tag:x)

**Comment by anuj-sharma-ibm** [comment]
hi i am looking for a solution where we can modify output configuration(s) in fluentbit's configuration so that it drops all data belonging to tags starting with example : **capacity.***  In other words - logs belonging to such tags should not reach logDNA
