### ISSUE TITLE
loki output performance issue and huge memory footprint

### ISSUE THREAD

**Issue by levindecaro** [fluent/fluent-bit#2931]
## Bug Report

**Describe the bug**

I'm running into performance issue on fluent-bit 1.6.9 docker image and td-agent-bit-1.6.9 rpm on a testing environment, the loki version is 2.0 and 2.1. Both combination appear slow log delivery when under loads (avg 500 message per sec), logs are so lag about 10 sec to be appeared in loki, and then getting slower and slower after hours, sometime the log was dropped out without seeing "out of sync", the logs aren't delivered ultimately. Also, the fluent-bit process often hit >4GB of memory or sometime just OOM.  

The same setup on same cluster with using "out_grafana_loki.so" from grafana do not have such issue, the log message are shown up in loki in 2 or 3 sec and didn't drop out for days, the memory footprint just as 80MB~140MB.

I'd tried to narrow down the problem by different input and filter, there are no problem once using syslog or stdout. So I came across to report this finding here to catch your attention.  

**To Reproduce**
- Setup Loki single instance, local filesystem blobdb
- Setup 10 nodes of OpenShift 4.6 with fluent-bit privileged daemonset,
- Configure fluent-bit input tail /var/logs/container/*.log mount from hostpath
- Configure fluent-bit output loki with kubernetes filter
- Generate loads and observe the performance keep dropping over time.

**Expected behavior**

- Log should delivered within reasonable time and predicable, no record drop without visible errors. 
- Memory footprint should be lower
 

**Screenshots**

**Your Environment**

* Version used: 1.6.9
* Configuration: loki output, tail input, Kubernetes filter
* Environment name and version (e.g. Kubernetes? What version?): openshift 4.6, k8s 1.19
* Server type and version: VM
* Operating System and version: rhcos4,rhel8.2
* Filters and plugins: Kubernetes, loki

**Additional context**

**Comment by agup006** [comment]
Hey @levindecaro thanks for filing, would you be able to attach your configuration as well as log file?

**Comment by jcdauchy** [comment]
Would be great to have more information @levindecaro

**Comment by levindecaro** [comment]
Hi, here is the config I'm using, 3 output are going to same loki, I cannot capture the flunet-bit log output, since the testing farm already put into production. thanks.

```
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    Parsers_File parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.sync normal


[OUTPUT]
    name                   loki
    match                  kube.*
    host                   ${LOG_HOST_ADDR}
    port                   ${LOG_HOST_PORT}
    labels                 job=openshift-logging,namespace=$kubernetes_namespace_name,host=$kubernetes_host,container=$kubernetes_container_name,pod=$kubernetes_pod_name
    #labels                 job=openshift-logging,namespace=$namespace_name,host=$host,container=$container_name,pod=$pod_name
    auto_kubernetes_labels off

[OUTPUT]
    name                   loki
    match                  host.*
    host                   ${LOG_HOST_ADDR}
    port                   ${LOG_HOST_PORT}
    labels                 job=host-logging,host=${NODE_NAME},log=$logtype,unit=$SYSTEMD_UNIT

[OUTPUT]
    name                   loki
    match                  openshift.*
    host                   ${LOG_HOST_ADDR}
    port                   ${LOG_HOST_PORT}
    labels                 job=openshift-audit,host=${NODE_NAME}

[FILTER]
    Name   modify
    Match  host.*
    Rename MESSAGE message

[FILTER]
    Name   record_modifier
    Match  host.journald.*
    Record logtype journald

[FILTER]
    Name   record_modifier
    Match  host.audit.*
    Record logtype audit


[FILTER]
    Name   kubernetes
    Match  kube.*
    Kube_Tag_Prefix  kube.var.log.containers.
    Merge_Log On
    Merge_Log_Trim On
    Buffer_Size 1MB
    Merge_Log_Key    log_processed


[FILTER]
    Name                nest
    Match               kube.*
    Operation lift
    Nested_under kubernetes
    Add_prefix   kubernetes_

[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Exclude_Path  /var/log/containers/*_openshift-logging_*.log,/var/log/containers/*_openshift-image-registry_*.log,/var/log/containers/*_olm-operator-*.log
    DB /var/log/fluent-bit-containers-log.db
    Parser cri
    Tag kube.*
    Mem_Buf_Limit 512MB
    Buffer_Max_Size  2MB
    Skip_Long_Lines On


[INPUT]
    Name systemd
    #Path /var/log/journal
    DB /var/log/fluent-bit-host-log.db
    Tag host.journald.*
    Strip_Underscores On
    Systemd_Filter _SYSTEMD_UNIT=kubelet.service
    Systemd_Filter _SYSTEMD_UNIT=crio.service
    Systemd_Filter _SYSTEMD_UNIT=chronyd.service
    

[INPUT]
    Name systemd
    #Path /var/log/journal
    DB /var/log/fluent-bit-ssh-log.db
    Tag host.audit.*
    Strip_Underscores On
    Systemd_Filter _SYSTEMD_UNIT=sshd.service

[INPUT]
    Name tail
    Path /var/log/openshift-apiserver/audit.log
    DB /var/log/fluent-bit-ocp-api-log.db
    Tag openshift.audit.*
    Parser json
```

**Comment by d-huynh** [comment]
I also have this problem, running on Kubernetes 1.19.3.
I tried increasing Mem_Buf_Limit to 100 MB and give the pods 300 MB to work with.

```
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        Exclude_Path        /var/log/containers/addon*,/var/log/containers/azure*
        Tag                 kube.*
        Mem_Buf_Limit       100MB
        Skip_Long_Lines     On
        Ignore_Older        3h
        Refresh_Interval    30
        DB                  /var/log/fluentbit_tail.db
        DB.locking          true
        Multiline           On
        Multiline_Flush     1
        Parser_Multiline    multiline

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           Off
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [OUTPUT]
        name                    loki
        match                   *
        host                    loki
        port                    3100
        tenant_id               ""
        labels                  pod=$kubernetes['pod_name'], namespace=$kubernetes['namespace_name'], node=$kubernetes['host'], app=$kubernetes['container_name'], docker_id=$kubernetes['docker_id']
        auto_kubernetes_labels  off
        line_format             json

    [PARSER]
        Name        multiline
        Format      regex
        Regex       /^(?<time>\d{4}-\d{2}-\d{2}[T ]?\d{2}:\d{2}:\d{2}\.\d+[Z]?)\s([a-zA-Z]*)\s[F].*(?<time2>\[?\d{4}.\d{2}.\d{2}[T ]?\d{2}:\d{2}:\d{2}[\.\dZ\]]*)(?<log>.*)/
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
```

Even though our input rate is low (prometheus: `rate(fluentbit_input_records_total[5m])` ~2.5 record/s), fluent-bit goes through memory quickly. I had to set a memory limit, the pods restarts quite often.

```
NAME                                                   CPU(cores)   MEMORY(bytes)
fluent-bit-65nzm                             3m           316Mi
fluent-bit-6d9x4                             2m           247Mi
fluent-bit-btqdk                             3m           315Mi
fluent-bit-dgnwv                             2m           195Mi
fluent-bit-ltktt                             2m           29Mi
fluent-bit-mh5hg                             2m           63Mi
fluent-bit-xb5k6                             2m           290Mi
```

We had no limit on memory, the pods took as much as 2 GB. The memory usage only grows and doesn't go down.

**Comment by tjorri** [comment]
We're also seeing this issue with fluent-bit 1.7.9. With around 80 records/s and leaving a pod to run its course, memory usage just kept steadily rising (imposing no memory limits, we ended up easily at around 14GB after running a week and a few days). Our configuration was very similar to what @d-huynh lists above.
