### ISSUE TITLE
syslog output plugin doesn't send application logs as expected

### ISSUE THREAD

**Issue by yukselao** [fluent/fluent-bit#2932]
![ss](https://user-images.githubusercontent.com/2484823/104168224-c5d0c180-540e-11eb-98ce-eaab07a52b9b.png)
## Bug Report

syslog output plugin sends null messages

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
Follow instructions in install.sh:
https://github.com/yukselao/fluent-bit


```
- Steps to reproduce the problem:
Follow instructions in install.sh:
https://github.com/yukselao/fluent-bit
**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 16
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): 19.1
* Server type and version: kind
* Operating System and version:
* Filters and plugins: syslog

**Additional context**

I am trying to send all applications log to an external syslog server.

**Comment by agup006** [comment]
Hi @yukselao, are you able to try with the latest version of Fluent Bit 1.6.10?

In your configmap: https://github.com/yukselao/fluent-bit/blob/main/fluent-bit-ds.yaml#L27, try using `fluent/fluent-bit:1.6.10`

**Comment by yukselao** [comment]
Hi @agup006  I am using latest version now but the result is the same.

I updated scripts if you want to reproduce the issue in your side.

What do you think about my output configuration?  Should we use a variable for message_key part?

  output-syslog.conf: |
    [OUTPUT]
        name                 syslog
        match                *
        host                 172.16.60.130
        port                 1515
        mode                 tcp
        syslog_format        rfc5424
        syslog_maxsize       65536
        syslog_severity_key  debug
        syslog_facility_key  facility
        syslog_hostname_key  hostname
        syslog_appname_key   appname
        syslog_procid_key    procid
        syslog_msgid_key     msgid
        syslog_sd_key        sd
        syslog_message_key   message

I changed ds:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
with:
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
but it didn't help.

**Comment by edsiper** [comment]
assigned to @nokute78

**Comment by srajeshinfotech** [comment]
I'm also facing this issue with latest v1.7.2 release. 

My config:-
[SERVICE]
    flush        2
    daemon       Off
    log_level    debug
[INPUT]
    Name tail
    Path /var/log/syslog
[OUTPUT]
    name                 syslog
    match                *
    host                 10.10.10.5
    port                 514
    mode                 udp
    syslog_format        rfc5424
    syslog_maxsize       2048
    syslog_severity_key  err
    syslog_facility_key  syslog
    syslog_hostname_key  Mazda2
    syslog_appname_key   fluentbit
    syslog_procid_key    procid
    syslog_msgid_key     1000
    syslog_sd_key        sd
    syslog_message_key   message

Attached the wire-shark capture for your info..

![image](https://user-images.githubusercontent.com/4629683/111540592-558b4700-8795-11eb-91f4-c24a95c88725.png)

This is very basic things. Request you to fix this issue asap..

Best Regards,
Rajesh~ 
+91-9600635770
iRxTx.com

**Comment by srajeshinfotech** [comment]
Added the below patch. working fine..

Please someone review my patch..

PATCH file : -
[output_syslog.txt](https://github.com/fluent/fluent-bit/files/6161690/output_syslog.txt)

Best Regards,
Rajesh~
+91-9600635770
iRxTx.com

**Comment by nokute78** [comment]
@srajeshinfotech  Thank you for information.
Can you open a pull request for reviewing ?

**Comment by nokute78** [comment]
@srajeshinfotech Thank you for creating #3249
I'll check it later.

**Comment by nokute78** [comment]
@yukselao @srajeshinfotech 
`syslog_*_key` property is to get the value from incoming record.

For example
```
syslog_message_key message
```
In this case, syslog output plugin expects incoming record has "message" key and the plugin treats the value of the key as a message.


If the configuration file is like this, `syslog_message_key` is  `log_body` and dummy plugin sends `{"log_body":"hoge"}`.
Then syslog plugin uses the value `hoge` as message.
```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    name dummy
    dummy {"log_body":"hoge"}

[OUTPUT]
    name syslog
    match *
    host 127.0.0.1
    mode tcp
    syslog_message_key log_body
```

**Comment by yukselao** [comment]
I think this item still needs development, I see application logs without metadata; it means that we cannot see details like pod name, node name or application name. We just see application's log stream. Unfortunately from security operation perspective these logs are useless. If you fix it, I will be happy to test. @edsiper

**Comment by aronneagu** [comment]
I am facing the same issue on 1.7.3. I can set `syslog_message_key log` (when using the kubernetes filter), but attempting to set any other syslog_*_key with values from $kubernetes['labels']['XXX'] (for example) those keys are empty on syslog side.

This feels like a basic feature to have, syslog is widely used and at the moment it's unusable.

**Comment by sara-hann** [comment]
I am still encountering this issue in version 1.9.6. Can this please be reopened?

**Comment by Cajga** [comment]
We have the same issue here. Basically empty messages end up in syslog.

**Comment by zekker6** [comment]
For the future readers, here is the config which worked for me with chart version 0.24.0:
```
      [OUTPUT]
          Name syslog
          Match kube.*
          Host x.x.x.x
          Port 514
          Mode tcp
          syslog_format        rfc5424
          syslog_maxsize       2048
          syslog_hostname_key  hostname
          syslog_appname_key   appname
          syslog_procid_key    procid
          syslog_msgid_key     msgid
          syslog_sd_key        uls@0
          syslog_message_key   log
```

**Comment by zanoni23** [comment]
I left out the extra filter and added more fields.
This doesn't however copy the original time for the pod logs, hopefully that is in the log message.
```
      outputs: |
         [OUTPUT]
             name                 syslog
             match                host.*
             host                 rsyslog.cluster-ops.svc.cluster.local
             port                 514
             mode                 tcp
             syslog_format        rfc5424
             syslog_maxsize       2048
             syslog_severity_key  PRIORITY
             syslog_facility_preset  3
             syslog_hostname_key  _HOSTNAME
             syslog_appname_key   SYSLOG_IDENTIFIER
             syslog_procid_key    _PID
             syslog_message_key   MESSAGE
         [OUTPUT]
             name                 syslog
             match                kube.*
             host                 rsyslog.cluster-ops.svc.cluster.local
             port                 514
             mode                 tcp
             syslog_format        rfc5424
             syslog_maxsize       2048
             syslog_severity_key  severity
             syslog_facility_preset  16
             syslog_hostname_key  namespace_name
             syslog_appname_key   pod_name
             syslog_procid_key    container_name
             syslog_message_key   log
             #syslog_sd_key        kubernetes  - doesn't work, hence nest filters
      service: |
        [SERVICE]
            Daemon Off
            Flush {{ .Values.flush }}
            Log_Level {{ .Values.logLevel }}
            Parsers_File parsers.conf
            Parsers_File custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port {{ .Values.metricsPort }}
            Health_Check On
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
        [FILTER]
            Name                nest
            Match               *
            Wildcard            pod_name
            Wildcard            namespace_name
            Wildcard            container_name
            Operation           lift
            Nested_under      kubernetes
```

**Comment by zanoni23** [comment]
I solved the empty logs of apps that log in JSON format by turning Merge_log Off in the Kuberbernetes filter.  Merge_Log is not useful for sending to syslog.

**Comment by nikitamishagin** [comment]
I recommend that anyone who has this problem check that parser is not used anywhere in the configuration. For example, in the input `tail` module I had the `Parser json` parameter. After removing this setting the problem was resolved.

**Comment by larkinflight** [comment]
If your logs are empty, first check if syslog_message_key is properly set. The documentation states: 'Note that this property is mandatory, otherwise the message will be empty'
