### ISSUE TITLE
Restart whenever configuration is updated

### ISSUE THREAD

**Issue by gagansingh355** [fluent/fluent-bit#2936]
I am looking for a way so that fluentbit will restart whenever i update xyz.conf file
Is it possible in fluentbit currentlt?

**Comment by agup006** [comment]
Not possible today in the current Fluent Bit version. We can look at adding hot reload capabilities in a future version though.

**Comment by gagansingh355** [comment]
Thanks for the clarification!  @agup006

**Comment by agup006** [comment]
I'm going to leave this one closed as we are tracking in another issue
