### ISSUE TITLE
Regex parser multiline flag

### ISSUE THREAD

**Issue by maggiedeuitch** [fluent/fluent-bit#2938]
## Bug Report

I have a regex parser as follows and I want to use the multiline flag `\m`. My input uses `forward` and not `tail`, so I'm assuming I don't use the Fluent Bit Multiline feature, but just the regular regex flag.

My regex: 
```^(\d{4}-\d{2}-\d{2}T\d{1,2}:\d{1,2}:\d{1,2}.\d{3}Z) (?<level>\w+) \[(?<deliveryWorker>[^ ]*)\] - (?<errorMessage>.*) due to error: (?<errorType>.*)/m```

I've checked that it works on Rubular
https://rubular.com/r/EuMvOFmaUFnQBO

Example log:
```
2020-06-22T16:06:28.055Z ERROR [serviceworker] - encountered error while acting on job: [delivery-provider.execute.error] - Unable to execute job due to error: foo
foo
foo
```

Expected output:

level:  ERROR
deliveryWorker: serviceworker
errorMessage:  encountered error while acting on job: [delivery-provider.execute.error] - Unable to execute job
errorType: foo 
                  foo
                  foo

It doesn't work as expected with Fluent Bit though. The log lines end up empty and the fields are not captured, as if there was no match. Is there a different syntax for the flags with Fluent Bit?

**Comment by agup006** [comment]
Hey @maggiedeuitch, thanks for submitting the issue. The problem will be that regex, though it has multiline turned on, will be run against a single line coming from forward input. You are correct that we only have multiline for tail today, so the short term solution (not ideal) would be to go forward -> output file -> in_tail w/ multiline -> output.

We are looking at creating a multiline filter that should start to help unlock this if you are interested in chatting more about it, happy to sync

**Comment by maggiedeuitch** [comment]
Hi @agup006,
Thank you for the quick response. So let's say I have the above log again without the `/m` flag.

```
2020-06-22T16:06:28.055Z ERROR [serviceworker] - encountered error while acting on job: [delivery-provider.execute.error] - Unable to execute job due to error: foo
foo
foo
```
I've been able to match it in Fluent Bit up to ```...due to error: foo```. 
What happens to the two `foo` that follows? Do they just get deleted?

**Comment by agup006** [comment]
Fluent Bit would read it in as a new line: "foo" and result in no matches: https://rubular.com/r/4h70AS28dn2L3s

**Comment by maggiedeuitch** [comment]
Ok, thank you

**Comment by maggiedeuitch** [comment]
A couple of more follow up questions:
1. If I had multiple parsers and the line doesn't match any of the parsers, what happens to the line? My understanding is the the line will be preserved as is as should show up in Kibana under the "log" field?

2. Would the new lines in my previous multiline example not fall under that?

Example
```
{log: "None of the the parsers match this line"}
```

fluent-bit.conf
```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name forward
    unix_path /var/run/fluent.sock

# parsers are configured in parsers.conf
[FILTER]
    Name parser
    Match **
    Parser PM2_logs
    Key_Name log
    Reserve_Data True

[FILTER]
    Name parser
    Match **
    Parser PM2_logs_2
    Key_Name log
    Reserve_Data True

```

parsers.conf
```

[PARSER]
    Name PM2_logs
    Format regex
    Regex ^(\d{1,2}:\d{1,2}:\d{1,2}) (?<process>\d)\W*(?<service>[^ ]*)\W*(\d{4}-\d{2}-\d{2}T\d{1,2}:\d{1,2}:\d{1,2}.\d{3}Z) (?<level>\w+)[^:]*(?<ip>[^ ]*) - (?<method>[^ ]*) (?<path>[^ ]*) (?<protocol>[^ ]*) (?<code>[^ ]*) (?<size>\d*) - (?<responseTime>.*)

[PARSER]
    Name PM2_logs_2
    Format regex
    Regex ^(\d{2}:\d{2}:\d{2}) (?<process>\d)\W*(?<service>[^ ]*)\W*(?<message>.*)
   
  ```

**Comment by agup006** [comment]
You may need to use the parameter `Preserve_Key` instead of only `Reserve_Data`, and then it would show up under log in Kibana if no matches are made

**Comment by maggiedeuitch** [comment]
Thank you, I will try that. I will close this now.
