### ISSUE TITLE
[1.6.10] sc.exe can't start fluent-bit without hardcoded absolute path in @INCLUDE [Windows 2019]

### ISSUE THREAD

**Issue by binarytrails** [fluent/fluent-bit#2943]
There seems to be an issue relative to the ```@INCLUDE``` path in its statement in relation to the ```sc.exe```.

What is expected is that there is a way of specifying a working path variable in the include statement or in the command itself for the process to be able to pick up the configuration files found from its working directory instead of having manually adding a prefix in each include statement one by one.

Here is the folder layout:
```
PS C:\test> ls
    Directory: C:\test
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/13/2021  11:42 AM                input
-a----        1/13/2021  10:20 AM        3641344 fluent-bit.dll
-a----        1/13/2021  10:20 AM        4362752 fluent-bit.exe
-a----        1/13/2021  11:47 AM            119 test.conf
PS C:\test> ls .\input\
    Directory: C:\test\input
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/13/2021  11:47 AM            164 powershell.conf
```
Here are my configurations files: 
```
# test.conf 
@SET WORKING_PATH=C:\test\
@INCLUDE ${WORKING_PATH}input\powershell.conf
[OUTPUT]
    Name    stdout
    Match   *

# input/powershell.conf
[INPUT]
    Name         winlog
    storage.type memory
    Interval_Sec 2
    DB           ${WORKING_PATH}winlog.sqlite
    Channels     Windows PowerShell
```
Let's attempt to create and run the service:
```
PS C:\test> sc.exe create fluent-bit binPath= "C:\test\fluent-bit.exe -c C:\test\test.conf"
[SC] CreateService SUCCESS

PS C:\test> net start fluent-bit
The fluent-bit service is starting.
The fluent-bit service could not be started.

A system error has occurred.
System error 1067 has occurred.
The process terminated unexpectedly.
```
Let's edit ```test.conf``` file: ```PS C:\test> notepad.exe .\test.conf```

New ```test.conf``` content for include will be: ```@INCLUDE input\powershell.conf```. Let's run it:
```
PS C:\test> net start fluent-bit
The fluent-bit service is starting.
The fluent-bit service could not be started.

A system error has occurred.
System error 1067 has occurred.
The process terminated unexpectedly.
```
Let's edit ```test.conf``` file: ```PS C:\test> notepad.exe .\test.conf```

New ```test.conf``` content (see the absolute path after include statement): ```@INCLUDE C:\test\input\powershell.conf```

Let's start to start the process now:
```
PS C:\test> net start fluent-bit
The fluent-bit service is starting.
The fluent-bit service was started successfully.

PS C:\test> sc.exe qc fluent-bit
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: fluent-bit
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\test\fluent-bit.exe -c C:\test\test.conf
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : fluent-bit
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem
PS C:\test> sc.exe query fluent-bit

SERVICE_NAME: fluent-bit
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
It works!! :confetti_ball:  also note that the ```${WORKING_PATH}``` worked in ```input/powershell.conf``` and it has created ```winlog.sqlite``` file:
```
PS C:\test> ls
    Directory: C:\test
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/13/2021  11:42 AM                input
-a----        1/13/2021  10:20 AM        3641344 fluent-bit.dll
-a----        1/13/2021  10:20 AM        4362752 fluent-bit.exe
-a----        1/13/2021  12:18 PM            117 test.conf
-a----        1/13/2021  12:18 PM          12288 winlog.sqlite
```
It seems to be clear with these steps to reproduce it that there is a need to be able to specify a working dir to avoid unnecessary repetition of absolute paths prefixes in each include (image in a real world scenario you might split it into many folders and many files to keep things organized).

**Comment by fujimotos** [comment]
> It seems to be clear with these steps to reproduce it that there is a need to be able to specify a working dir to avoid unnecessary repetition of absolute paths prefixes in each include

Hm. I think we have two separate problems here:

1. Fluent Bit won't resolve relative paths as expected when started by Windows Service Manager.
2. `@INCLUDE` does not support variable syntax.

(1) is easier one to fix. It occurs just because a Windows service uses
`%WinDir%\System32` as the working directory by default. 

So a straight forward fix is to call `SetCurrentDirectory()` on startup to cd
to the executable path. It will make the following configuration just work:

```ini
@INCLUDE input\powershell.conf
[OUTPUT]
    Name    stdout
    Match   *

# input/powershell.conf
[INPUT]
    Name         winlog
    storage.type memory
    Interval_Sec 2
    DB           winlog.sqlite
    Channels     Windows PowerShell
```

@binarytrails  Does this solution sound good to you? If so, I'll fix Fluent Bit
accordingly.

**Comment by binarytrails** [comment]
@fujimotos thank you for the swift reply! Yes, that would be great.

Another possible solution is to add a parameter to the fluent-bit binary to be able to pass a home / working directory path which will have the configuration files. This way the binaries can stay in their respective directories while the configurations in their own. However, you're in the best position to know what is the best solution in this situation.

**Comment by fujimotos** [comment]
> Another possible solution is to add a parameter to the fluent-bit binary to be able to pass a home / working directory path which will have the configuration files. This way the binaries can stay in their respective directories while the configurations in their own. However, you're in the best position to know what is the best solution in this situation.

@binarytrails I spent some time experimenting with those ideas and
ended up implementing both.

* #2946 (set the default working dir for WIndows Service)
* #2947 (Add a new workdir command-line option)

I believe your issue should be resolved once these PRs get merged.

**Comment by binarytrails** [comment]
@fujimotos this is amazing news! thank you so much. It is greatly appreciated! :octopus: :tada:
