### ISSUE TITLE
Entry out of order issue when sending consul or traefik log files to Loki and parsing timestamp.

### ISSUE THREAD

**Issue by kago-dk** [fluent/fluent-bit#2951]
## Bug Report

**Describe the bug**
When you try to send consul or traefik log files to the Loki utilizing the built-in output plugin Loki and parse the Time_Key, then Loki reports back:
```
[2021/01/16 20:42:31] [error] [output:loki:loki.1] lokiserver:3100, HTTP status=400
entry with timestamp 2021-01-16 19:22:08.331542 +0000 UTC ignored, reason: 'entry out of order' for stream: {job="fluentbit"},
total ignored: 1 out of 1
```

**To Reproduce**

**parsers.conf**
```
[PARSER]
    Name         dummydate
    Format       json
    Time_Key     @timestamp
    Time_Format  %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep    On
```

**fluent-bit.conf**
```
[SERVICE]
    flush        1
    daemon       Off
    log_level    trace
    Log_File     log/fluentbit.log
    parsers_file parsers.conf

[INPUT]
    name      dummy
    dummy     {"log":"{\"@level\":\"info\",\"@message\":\"Exit code\",\"@module\":\"agent\",\"@timestamp\":\"2021-01-16T19:22:08.331542-08:00\",\"code\":1}"}

[FILTER]
    Name parser
    Match *
    Parser dummydate
    Key_name log

[OUTPUT]
    name                   stdout
    match                  *

[Output]
    Name loki
    Match *
    host                   lokiserver
    port                   3100
    Labels                 job=fluentbit
```

**Expected behavior**
Fluent bit and Loki should be able to consume and store standard log files produced by Consul and/or Traefik.

**Your Environment**

* Version used: td-agent-bit-1.6.10-win64 and Loki 2.1.0.
* Operating System and version: WIndows Server 2019
* Filters and plugins: N/A

**Comment by kago-dk** [comment]
Still open

**Comment by kago-dk** [comment]
Still open

**Comment by JeffLuoo** [comment]
What Loki recommends is using more static labels. Reference: https://grafana.com/docs/loki/latest/best-practices/

Could you please follow the best practices and to see if adding more labels will reduce some `out-of-order` errors?

**Comment by Z18Aplha** [comment]
I have similar issues the last few days with fluentbit and loki. My fluentbit container works well with ´´´stdout´´´:
```
[0] dummy.0: [1610853728.331542000, {"@level"=>"info", "@message"=>"Exit code", "@module"=>"agent", "@timestamp"=>"2021-01-16T19:22:08.331542-08:00", "code"=>1}]
[1] dummy.0: [1610853728.331542000, {"@level"=>"info", "@message"=>"Exit code", "@module"=>"agent", "@timestamp"=>"2021-01-16T19:22:08.331542-08:00", "code"=>1}]
[2] dummy.0: [1610853728.331542000, {"@level"=>"info", "@message"=>"Exit code", "@module"=>"agent", "@timestamp"=>"2021-01-16T19:22:08.331542-08:00", "code"=>1}]
[3] dummy.0: [1610853728.331542000, {"@level"=>"info", "@message"=>"Exit code", "@module"=>"agent", "@timestamp"=>"2021-01-16T19:22:08.331542-08:00", "code"=>1}]
```
but the loki-[OUTPUT] always has a timestamp error:
```
[error] [output:loki:loki.0] loki:3100, HTTP status=400 entry for stream '{agent="fluentbit", job="docker-forward"}' has timestamp too old: 1970-01-01 00:00:01.71656344 +0000 UTC
```
It seems the timestamp is zero? Or nearly close to it? I have absolutely no idea. The timestamps in stdout are correct.
I already tried a ton of configs (Time_as_integer in INPUT-forward and different input types). 

Any ideas?

Sometimes there is a parseInt error
```
[error] [output:loki:loki.0] loki:3100, HTTP status=400 parseInt Error .... value x out of range
```
I will edit this logout as soon as i get this error again. But the info ```value x out of range``` (x is a big number, similar to the nano-second unix timestamp, but 40 years in the future) tells me, there must be a problem formatting the timestamp reporting to loki.

**Comment by Z18Aplha** [comment]
Apparently my assumption is right. Right now I am testing 
```
curl -v -H "Content-Type: application/json" -XPOST -s "http://192.168.178.56:3100/loki/api/v1/push" --data-raw '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1610853728331542000", "fizzbuzz" ] ] }]}'
```
from my machine and it works. No parse Error and no too old timestamp from 1970 (this time a too old timestamp but this time with the correct date set in the dummy post). 

Maybe I am just blind, but is there a possibility to force fluentbit to send the timestamp as an integer?

**Comment by JeffLuoo** [comment]
@Z18Aplha How do you configure your input plugin?

**Comment by Z18Aplha** [comment]
@JeffLuoo
I configured it as a dummy input.
```
[INPUT]
    name      dummy
    dummy     {"log":"{\"@level\":\"info\",\"@message\":\"Exit code\",\"@module\":\"agent\",\"@timestamp\":\"2021-01-16T19:22:08.331542-08:00\",\"code\":1}"}
```

Was this your question?
