### ISSUE TITLE
My production enviroment is Red Hat Enterprise Linux 6.5, can i build fluent-bit 1.6.10 on this paltform  succesfully?

### ISSUE THREAD

**Issue by maoyaowu** [fluent/fluent-bit#2952]
**Is your feature request related to a problem? Please describe.**
I want to use fluent-bit on Red Hat Enterprise Linux 6.5, so i have to build fluent-bit from source on this platform?  or i can use  another solution, such as useing Fluent Bit container images.

thanks a lot!

**Comment by l2dy** [comment]
Yes, but you need to install newer versions of cmake, flex and bison.

**Comment by maoyaowu** [comment]
thank you.
I know that cmake shoud be CMake3+.  for flex and bison which version should be use to build fluent-bit 1.16.10 from source on  Red Hat Enterprise Linux 6.5?
 I looking forward to hearing from you.

**Comment by l2dy** [comment]
For flex and bison, you can try the same version as packages on CentOS 7.
