### ISSUE TITLE
out_s3: Add support for specific keys per output

### ISSUE THREAD

**Issue by gregmankes** [fluent/fluent-bit#2964]
**Is your feature request related to a problem? Please describe.**
The aws s3 sdk allows the user to specify the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for a particular aws client. Per the credential provider chain [here](https://github.com/fluent/fluent-bit/blob/22f932549d77b3c9f75e5c39a9f3e93a7bb814f6/src/aws/flb_aws_credentials.c#L53-L65), support for specific credentials for an output is not possible.

**Describe the solution you'd like**
The ability to specify the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the output configuration.

**Describe alternatives you've considered**
The [predecessor to the core fluent-bit s3 output plugin](https://github.com/cosmo0920/fluent-bit-go-s3) has the ability to specify aws credentials per output, but it is no longer maintained. Also fluentd's s3 output plugin has support for specifying the access keys, but unfortunately the resource usage of fluentd would not fit this application. Alternatively, we have been looking at creating our own golang s3 output plugin. 

**Additional context**
We are trying to forward logs from the same input to one or more buckets that are in different accounts (with different access keys and permissions). We are using an aws s3 compatible api (not aws s3), so ARN roles are not applicable.

**Comment by gregmankes** [comment]
bump on this

**Comment by TDanielsHL** [comment]
Looking for additional ways to use the [OUTPUT] section to define Credentials / Authorization of the AWS, particularly for distroless containers. We are running on an EKS Cluster and have access to a ROLE_ARN and WEB_IDENTITY_TOKEN_FILE in the environment. Documentation on the Fluent-Bit website seems underdeveloped in this area.
