### ISSUE TITLE
BigQuery output plugin doesn't recognize and report insert errors

### ISSUE THREAD

**Issue by michaeltalyansky** [fluent/fluent-bit#2966]
## Bug Report

**Describe the bug**

BigQuery output plugin doesn't report errors on table insert in BigQuery. Makes it very difficult to diagnose insert errors.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

create a BQ table with a schema. Send JSON record that doesn't match the schema to FluentBit. FB doesn't report any errors, although table insert will have failed in BQ.

**Expected behavior**

Error log message should have been written out to the log file, describing the error.

**Screenshots**

**Your Environment**

* Version used: 1.6.9.
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: Ubuntu 18.04
* Operating System and version:
* Filters and plugins:

FB version 1.6.9
Ubuntu 18.04
TCP input, BQ output plugin

**Additional context**

Here is my analysis:

BQ returns HTTP 200 OK with a payload that contains the insert errors, as follows (produced by nodejs BQ client):

{ kind: 'bigquery#tableDataInsertAllResponse',
  insertErrors:
   [ { index: 0,
       errors:
        [ { reason: 'invalid',
            location: '',
            debugInfo: '',
            message: 'Missing required field: Msg_0_CLOUD_QUERY_TABLE.timestamp.' },
          [length]: 1 ] },
     [length]: 1 ] }
[ { errors:
     [ { message: 'Missing required field: Msg_0_CLOUD_QUERY_TABLE.timestamp.',
         reason: 'invalid' },
       [length]: 1 ],
    row: (description of my record I was trying to insert)
  [length]: 1 ]

Upon successful insert, response payload is as follows:

{"kind":"bigquery#tableDataInsertAllResponse"}

In plugins/out_bigquery/bigquery.c, the following code:

        /* The request was issued successfully, validate the 'error' field */
        flb_plg_debug(ctx->ins, "HTTP Status=%i", c->resp.status);
        if (c->resp.status == 200) {
            ret_code = FLB_OK;
        }
        else {
            if (c->resp.payload_size > 0) {
                /* we got an error */
                flb_plg_warn(ctx->ins, "error\n%s",
                             c->resp.payload);
            }
            else {
                flb_plg_debug(ctx->ins, "response\n%s",
                              c->resp.payload);
            }
            ret_code = FLB_RETRY;
        }

unconditionally sets ret_code to FLB_OK on 200 status, without examining the payload.

Here is the proposed fix:

        /* The request was issued successfully, validate the 'error' field */
        flb_plg_debug(ctx->ins, "HTTP Status=%i", c->resp.status);
        if (c->resp.status == 200 && (!c->resp.payload_size || !strstr(c->resp.payload, "insertErrors"))) {
            ret_code = FLB_OK;
        }
        else {
            if (c->resp.payload_size > 0) {
                /* we got an error */
                flb_plg_warn(ctx->ins, "error\n%s",
                             c->resp.payload);
            }
            else {
                flb_plg_debug(ctx->ins, "response\n%s",
                              c->resp.payload);
            }
            ret_code = FLB_RETRY;
        }

WIth this fix, FB correctly produces logfile warning message:

^[[1m[^[[0m2021/01/23 06:03:10^[[1m]^[[0m [^[[93m warn^[[0m] [output:bigquery:bigquery.0] error
{
  "kind": "bigquery#tableDataInsertAllResponse",
  "insertErrors": [
    {
      "index": 0,
      "errors": [
        {
          "reason": "invalid",
          "location": "aurl",
          "debugInfo": "",
          "message": "no such field."
        }
      ]
    }
  ]
}

**Comment by Amindv1** [comment]
Can someone take a look at this? Has the proposed fix been merged? I'm noticing the same thing - failure to insert aren't logged, and entire batches are being dropped due to one bad data entry. 

@michaeltalyansky did they fix this issue?

**Comment by lebergarrett** [comment]
This has become a very annoying part of my experience with fluent-bit. I've had to spent a lot of time troubleshooting because of the lack of errors when this happens. I would love for this fix to be implemented, as it does not appear to be already.
