### ISSUE TITLE
[windows] runtime Chunk I/O crc32 error off tag v1.7.0-rc1

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#2978]
## Bug Report

**Describe the bug**
Build windows agent by following this guide: https://github.com/fluent/fluent-bit-docs/blob/master/installation/windows.md#compilation

**To Reproduce**
git checkout tags/v1.7.0-rc1 -b 1.7.0-rc1
Then compiling it by https://github.com/fluent/fluent-bit-docs/blob/master/installation/windows.md#compilation
<img width="1380" alt="Screen Shot 2021-01-27 at 1 59 30 PM" src="https://user-images.githubusercontent.com/8354694/106043464-77791f00-60ac-11eb-8ec8-f4684253748a.png">

The working hash commit that has no runtime error or buildtime error is `f53b48880916c20fc7434d23a32e2588075d1b98`

**Comment by edsiper** [comment]
@sophieyfang 

Looks like the latest GIT master (future -rc2) is building fine, I just did a test, here are the build logs and artifacts:

https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/37480911

**Comment by sophieyfang** [comment]
yes, but master branch has run-time error: https://github.com/fluent/fluent-bit/issues/2976

**Comment by edsiper** [comment]
@sophieyfang does revert f53b4888091 works (just that commit) ?. that commit only change the first 4 bytes of the crc32

**Comment by sophieyfang** [comment]
I don't think we want to revert https://github.com/fluent/fluent-bit/commit/f53b48880916c20fc7434d23a32e2588075d1b98... As i tested so far with many different commit hashes, git checkout f53b48880916c20fc7434d23a32e2588075d1b98 is the only one that has no run-time error or build-time error

**Comment by sophieyfang** [comment]
This has been fixed in v1.7.0-rc3
