### ISSUE TITLE
Is the golang output plugin usable?

### ISSUE THREAD

**Issue by adieu** [fluent/fluent-bit#298]
We've developed a golang output plugin for [Aliyun](https://www.aliyun.com). Before introducing this to the users, I wanted to make sure this feature is stable and usable. Since there aren't much information in the repo, I think it's better asking for help.

Do we have any real world use cases for the golang plugin? How is the performance under high load? Any caveats?

Thanks a lot.

**Comment by edsiper** [comment]
@adieu the interface is fully usable and I am aware of the implementations of other plugins (out_kafka). The only missing feature is the interface to expose Fluent Bit configuration into the plugin, besides that it should be fine. 

Under high loads, is always recommendable to use [Mem_Buf_Limit](http://fluentbit.io/documentation/0.11/configuration/backpressure.html) option to make sure backpressure is not an issue in your environment. 

I am pretty interested into learn more from your use case, if you can join our [slack channel](http://slack.fluentd.org)(#fluent-bit) would be appreciated.

cc: @agup006

**Comment by adieu** [comment]
@edsiper thanks for your reply. It's good know the golang plugin is in good shape.

The repo for our plugin is at https://github.com/kubeup/fluent-bit-aliyun. We use environment variables to config it. When the configuration interface is available, we'd love to use that as well.

The link to the `Mem_Buf_limit` is really helpful. I didn't think much about backpressure and I have double checked our configuration. The config for k8s does already have `Mem_Buf_limit`. But it seems that we can't set `Mem_Buf_limit` when use `forward` as the input plugin.

I've joined the slack channel. We could exchange some ideas about our plugin.

**Comment by edsiper** [comment]
@adieu please check the current progress on Fluent Bit 0.12 support for the golang package:

https://github.com/fluent/fluent-bit-go/issues/6
