### ISSUE TITLE
[AWS Go plugin] panic: reflect: call of reflect.Value.Index on int64 Value

### ISSUE THREAD

**Issue by jgante** [fluent/fluent-bit#2980]
## Bug Report

**Describe the bug**
panic: reflect: call of reflect.Value.Index on int64 Value

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
panic: reflect: call of reflect.Value.Index on int64 Value
goroutine 17 [running, locked to thread]:
reflect.Value.Index(0x7f7c8f716aa0, 0xc0005de380, 0x86, 0x0, 0x0, 0x693fc, 0x1)
        /usr/local/go/src/reflect/value.go:956 +0x1b1
github.com/cosmo0920/fluent-bit-go-s3/vendor/github.com/fluent/fluent-bit-go/output.GetRecord(0xc0006560e0, 0x3, 0x3, 0xc00068e000, 0x693fc)
        /go/src/github.com/cosmo0920/fluent-bit-go-s3/vendor/github.com/fluent/fluent-bit-go/output/decoder.go:80 +0x106
main.(*fluentPlugin).GetRecord(0x7f7c8fdfbe40, 0xc0006560e0, 0x690f1, 0xc000079c00, 0x30a, 0x7f7c8f4a2029)
        /go/src/github.com/cosmo0920/fluent-bit-go-s3/out_s3.go:70 +0x2d
main.FLBPluginFlushCtx(0x7f7c90209270, 0x7f7c6586e0d3, 0x7f7c00068f2d, 0x7f7c90241400, 0x28)
        /go/src/github.com/cosmo0920/fluent-bit-go-s3/out_s3.go:327 +0x110
main._cgoexpwrap_792aac5a4913_FLBPluginFlushCtx(0x7f7c90209270, 0x7f7c6586e0d3, 0x726f777200068f2d, 0x7f7c90241400, 0x782d633464626336)
        _cgo_gotypes.go:88 +0x49 

- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:     [INPUT]
        Name                tail
        Tag                 application.*
        Exclude_Path        /var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/ebs*, /var/log/containers/efs*, /var/log/containers/kube-proxy*
        Path                /var/log/containers/*log
        Docker_Mode         On
        Docker_Mode_Flush   20
        Docker_Mode_Parser  container_firstline
        Parser              docker
        DB                  /var/fluent-bit/state/flb_container.db
        Mem_Buf_Limit       50MB
        Skip_Long_Lines     Off
        Refresh_Interval    10
        Rotate_Wait         60
        storage.type        filesystem

    [FILTER]
        Name                kubernetes
        Match               application.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix      application.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off

    [FILTER]
        Name                nest
        Match               *
        Operation           lift
        Nested_under        kube*
        Add_prefix           kube_

    [FILTER]
        Name                grep
        Match               kube*
        Exclude             kube_namespace_name, kube-system, amazon-cloudwatch

    [FILTER]
        Name                modify
        Match               application.*
        Rename              Nested.docker_id Docker.container_id

    [FILTER]
        Name                nest
        Match               application.*
        Operation           nest
        Wildcard            Nested.*
        Nested_under        kubernetes
        Remove_prefix        Nested.

    [FILTER]
        Name                nest
        Match               application.*
        Operation           nest
        Wildcard            Docker.*
        Nested_under        docker
        Remove_prefix        Docker.
        
    [OUTPUT]
        Name                s3
        LogLevel            info
        Match               application.*
        bucket              myBucket
        region              eu-central-1
        store_dir           /var/
        use_put_object      On
        total_file_size      300M
        upload_timeout      60m
        role_arn            <arn_assume_role>
        sts_endpoint        https://sts.eu-centra-1.amazonaws.com
        AccessKeyID         xxxxxxxxxxxxxx
        SecretAccessKey     xxxxxxxxxxxxxx
        S3Prefix             orion
        SuffixAlgorithm      sha256
        Compress            gzip
* Environment name and version (e.g. Kubernetes? What version?): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by nokute78** [comment]
The issue is about fluent-bit-go-s3 , but the plugin is already deprecated.
https://github.com/cosmo0920/fluent-bit-go-s3

The point is `panic: reflect: call of reflect.Value.Index on int64 Value` .
This issue is already fixed on fluent-bit-go repo. https://github.com/fluent/fluent-bit-go/issues/34 / https://github.com/fluent/fluent-bit-go/pull/35

However, it  may not be merged to fluent-bit-go-s3 yet.
https://github.com/cosmo0920/fluent-bit-go-s3/blob/master/vendor/github.com/fluent/fluent-bit-go/output/decoder.go
