### ISSUE TITLE
Feature Request: Ability to see final resolved Fluent Bit config

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit#2987]
**Is your feature request related to a problem? Please describe.**
Recently, I ran into an issue where I was trying to `@INCLUDE` a file in my Fluent Bit config, but it wasn't being substituted properly. Unfortunately, debugging this was pretty much impossible, since there's no way to see how exactly the final Fluent Bit config file looks AFTER the `@INCLUDE` is resolved.

**Describe the solution you'd like**
Ability to, on demand, see the final Fluent Bit config (after all `@INCLUDE` have been resolved).

OPTIONAL: Maybe also show the result of all the environment variable substitutions? 
The reason I classify this as an optional goal is because I don't know if this would be considered a security risk, since a common pattern is to include secret info in environment variables -- so perhaps we never want to print out environment variable values in plaintext?

**Describe alternatives you've considered**
In my test setup, I have Fluent Bit deployed on Kubernetes via Helm. As such, I tried to get the final config using the following approaches:
1. `helm get manifest "${RELEASE_NAME}"`
2.
   - Log in to the Fluent Bit container: `kubectl exec -it "${POD_NAME}" -- sh`
   - Print out the Fluent Bit config file: `cat /fluent-bit/etc/fluentbit.conf`

Unfortunately, in both cases, all I see is `@INCLUDE my-file.conf` -- what I want to see is how the config looks AFTER that `@INCLUDE` is resolved.

**Additional context**
I believe Fluentd does this by default, where it prints out the entire final resolved config on startup. Personally, I think that approach is overkill -- we don't need to see the entire config every time we restart Fluent Bit, especially on the default `INFO` log level -- but the ability to do so when desired, on demand, would be very useful.

**Comment by pranavmarla** [comment]
bump

**Comment by nokute78** [comment]
How about `--sosreport` option?

I tested two simple configuration files.
a.conf:
```
[INPUT]
    Name cpu
    Tag a

@INCLUDE stdout.conf
```

stdout.conf:
```
[OUTPUT]
    name stdout
```

If fluent-bit is executed with `--sosreport` option, fluent-bit outputs internal information and exit.
```
$ bin/fluent-bit -c a.conf --sosreport
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
<snip>
[SERVER] Runtime configuration
    Flush		5.000000
    Daemon		Off
    Log_Level		Info

[INPUT] Instance
    Name		cpu.0 (cpu, id=0)
    Flags		
    Threaded		No
    Tag			a
    Routes		stdout.0 


[OUTPUT] Instance
    Name		stdout.0 (stdout, id=0)
    Match		*
    TLS Active		No
    Retry Limit		1
```

**Comment by pranavmarla** [comment]
@nokute78 That's awesome! I've never seen that flag mentioned in any of the Fluent Bit documentation but, based on your test, that seems to be exactly what I was looking for -- thanks!!
