### ISSUE TITLE
Unable to build bundled LuaJIT on macOS

### ISSUE THREAD

**Issue by l2dy** [fluent/fluent-bit#2993]
## Bug Report

**Describe the bug**
```
==== Building LuaJIT 2.1.0-beta3 ====
Makefile:319: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.
make[3]: *** [default] Error 2
make[2]: *** [luajit-prefix/src/luajit-stamp/luajit-build] Error 2
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2
```

**To Reproduce**
- Steps to reproduce the problem:
1. `cmake -DFLB_TESTS_INTERNAL=On -DFLB_TESTS_RUNTIME=On ..`
2. `make`

**Expected behavior**
Build passes.

**Your Environment**

* Version used: 6e63092d1f8f064526b13239af6c4b81492346da
* Configuration: N/A
* Operating System and version: macOS 10.15, Xcode 12.3

**Additional context**

**Comment by jlunavtgrad** [comment]
I found this article helpful
https://medium.com/@anujarosha/how-to-build-fluent-bit-source-on-macos-d7424558614c

**Comment by l2dy** [comment]
Thanks, but in previous versions of Fluent Bit, this was not necessary, so I would consider this a regression.

**Comment by bluebike** [comment]
Try this before make (worked for me ... some time ago..)
```sh
export MACOSX_DEPLOYMENT_TARGET=10.15
```
