### ISSUE TITLE
How do we access kubernetes metadata?

### ISSUE THREAD

**Issue by beth2016** [fluent/fluent-bit#3000]
A newbie question.   I am unable to access anything in kubernetes metadata in fluent-bit.
    [FILTER]
        Name record_modifier
        Match *
        Record hostname kubernetes,host

It is showing the constant string "kubernetes.host"  And not the value.   
I tried $kubernetes.host and $kubernetes['host'] - not working

I can see this value is populated in the output.  I am expecting it to return the value "abc12345host".  Please advise.

kube.var.log.containers.static-egressip-controller-xdb6f_kube-system_static-egressip-controller-3f9f59fceaecd956741261650bf59cf4be339a334
57d76d5f0db4f3f5ca9adc6.log: [1612110095.732755688, {"event"=>{"source"=>"/var/log/containers/static-egressip-controller-xdb6f_kube-system_stat
ic-egressip-controller-3f9f59fceaecd956741261650bf59cf4be339a33457d76d5f0db4f3f5ca9adc6.log", "log"=>"I0131 16:21:35.732675       1 director.go
:114] Created ipset name: EGRESS-IP-FUJ6L2WY6GPSBN6U
", "stream"=>"stderr", "time"=>"2021-01-31T16:21:35.732755688Z", "kubernetes"=>{"pod_name"=>"static-egressip-controller-xdb6f", "namespace_name
"=>"kube-system", "pod_id"=>"fdccc08d-c2d9-11ea-9f5e-005056ab3b00", "labels"=>{"controller-revision-hash"=>"76477959b", "k8s-app"=>"static-egre
ssip-controller", "pod-template-generation"=>"2", "tier"=>"node"}, "host"=>"abc12345host", "container_name"=>"static-egressip-controller", "
docker_id"=>"3f9f59fceaecd956741261650bf59cf4be339a33457d76d5f0db4f3f5ca9adc6", "container_hash"=>"nirmata/static-egressip-controller@sha256:4b
7a93761aabc0b07f42687a7ed9a88b83f18358f49b92e100c61f4cd444daef", "container_image"=>"nirmata/static-egressip-controller:latest"}}}]

**Comment by dharmab** [comment]
You probably want to use the Modify plugin's `Copy` rule instead of the Record Modifier plugin: https://docs.fluentbit.io/manual/pipeline/filters/modify#rules. That copies the value an existing key.

**Comment by beth2016** [comment]
@dharmab thanks for replying.    Regardless if it is modify or modifier plugin, i am unable to read any variables.
For example, if i have myvar = "abc" in the record.  How do i access the variable in the filter section?
    [FILTER]
        Name      modify
        Match     *
        Set realvar myvar

I want "realvar" to get the value "abc", instead of  "myvar"

**Comment by dharmab** [comment]
You want to use `Copy` instead of `Set`:

```ini
[FILTER]
Name modify
Match *
Copymyvar realvar 
```

**Comment by beth2016** [comment]
@dharmab thanks for your response.   COPY also doesn't work for me.  The only way i can get it to work is to use LUA.  
record["realvar"]=record["myvar"]
I am using this image: fluent/fluent-bit:1.6.8

**Comment by agup006** [comment]
Throwing a wild guess, that perhaps the copy function was failing because of nested fields, and the proper accessor not being used? 

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/record-accessor

**Comment by beth2016** [comment]
@agup006 I had tried both nested fields and non-nested fields.  same issue for me
