### ISSUE TITLE
[1.7rc3] Missing log message when retry succeeded

### ISSUE THREAD

**Issue by elruwen** [fluent/fluent-bit#3001]
## Bug Report

**Describe the bug**
Sometimes a chunk can't be delivered and fluent-bit is retrying it. When that retry succeeds in 1.6.10, I receive a message like this:
```
[ info] [engine] flush chunk '1-1612248354.875642810.flb' succeeded at retry 1: task_id=1, input=forward.3 > output=syslog.0
```
In 1.7rc3 (I use the fluent/fluent-bit:1.7.0-rc3 docker image) this message is not there anymore.

**To Reproduce**
- Create a pipeline where the output talks to another process, for example syslog
- Turn off the output consuming process
- Send messages
- Turn on the output consuming process

**Expected behavior**
If a chunk was successfully retried, I except in the logs 
```
[ info] [engine] flush chunk '1-1612248354.875642810.flb' succeeded at retry 1: task_id=1, input=forward.3 > output=syslog.0
```
**Your Environment**
* Version used: fluent/fluent-bit:1.7.0-rc3 docker image
* Configuration: Input fluentd via tcp, output syslog
* Environment name and version (e.g. Kubernetes? What version?): Just playing with containers on my local machine
* Server type and version: Laptop :D
* Operating System and version: Debian Stable
* Filters and plugins:

**Additional context**
When I do turn off the output processing process and turn it on again, there is always one chunk stuck. That log message made watcihing the process easier. Now I use the CONT signal. For that issue I will try to create a minimal example and create another bug.

**Comment by elruwen** [comment]
This is still an issue with 1.7.

**Comment by JeffLuoo** [comment]
see https://github.com/fluent/fluent-bit/issues/3014#issuecomment-802044327 if config file is the same.

**Comment by elruwen** [comment]
No difference.

**Comment by JeffLuoo** [comment]
I guess the reason you didn't see log like 
```
[ info] [engine] flush chunk '1-1612248354.875642810.flb' succeeded at retry 1: task_id=1, input=forward.3 > output=syslog.0
```

is because that fluent bit failed to flush chunk to the destination. Could you please check the fluent bit log to see if there is any connection issue to the destination?

**Comment by elruwen** [comment]
It is the same situation as in #3014

1. Log destination is down.
2. I produce a lot of logs.
3. I start the log destination.
4. Fluentbit starts to retry and manages to send the majority of logs. In 1.6 I got a message letting me know when a retry succeeded, in 1.7 not anymore.

**Comment by elruwen** [comment]
No idea how to remove the stale label, but it is still an issue. Happy to help out with running debug builds etc

**Comment by pierluigilenoci** [comment]
@edsiper could you please take a look?

**Comment by pierluigilenoci** [comment]
Why nobody take care of this ticket?

**Comment by elruwen** [comment]
This is still an issue

**Comment by pierluigilenoci** [comment]
@edsiper could you please take a look?

**Comment by pierluigilenoci** [comment]
@edsiper @fujimotos @koleini Why doesn't anyone give even half a feedback about it?

**Comment by elruwen** [comment]
If I have the choice, I would like to get https://github.com/fluent/fluent-bit/issues/3014 fixed first. That might also fix this, too ;)
Happy to join the issues.

**Comment by jaydp17** [comment]
Would be nice to see this implemented.

I'm in the same boat where some of the chunks fail to be uploaded (with HTTP status = 0), I'm using AWS S3 as the destination.
Anyway, I'm trying to test if it's something with the chunk that makes the request fail & for that it'd be good to see a log for each retry attempt.

**Comment by elruwen** [comment]
> Would be nice to see this implemented.
> 
> I'm in the same boat where some of the chunks fail to be uploaded (with HTTP status = 0), I'm using AWS S3 as the destination.
> Anyway, I'm trying to test if it's something with the chunk that makes the request fail & for that it'd be good to see a log for each retry attempt.

The last time I checked, the message was still in the code. So I guess something in the logic has changed so that message is no longer emitted.

**Comment by elruwen** [comment]
Still an issue with v1.8.3.

**Comment by pierluigilenoci** [comment]
@edsiper @fujimotos @koleini why doesn't anyone give even half a feedback about it?

It's amazing that no one even deigns to look at all these reports of fluent-bit problems. 😢

**Comment by elruwen** [comment]
Still an issue

**Comment by elruwen** [comment]
Just in case anyone watches this issue. There are still issues with chunks getting stuck (see https://github.com/fluent/fluent-bit/issues/3014). Once that is fixed, I will check if the log messages reappear, if not, I will reopen the issue.

**Comment by agup006** [comment]
@patrick-stephens as someone who has been modifying log message levels lately, would this be something you might be open to adding :)

**Comment by patrick-stephens** [comment]
Yeah I can see what's up, it's a little vague but I'll try to figure out where. Most of my changes have been dropping noisy logs so might as well add one!
