### ISSUE TITLE
out_loki: implement DropSingleKey option

### ISSUE THREAD

**Issue by phin1x** [fluent/fluent-bit#3005]
**Is your feature request related to a problem? Please describe.**

Feature Request

**Describe the solution you'd like**

The grafana-loki go plugin has a option `DropSingleKey`:

_If set to true and after extracting label_keys a record only has a single key remaining, the log line sent to Loki will just be the value of the record key._

It would be nice if you could implement the feature

**Describe alternatives you've considered**

**Additional context**

**Comment by edsiper** [comment]
please paste an example of the record before and after.

**Comment by phin1x** [comment]
this is my current output configuration (grafana-loki plugin):
```
    [OUTPUT]
        Name grafana-loki
        Match *
        URL xxx
        Labels {job="fluent-bit"}
        # remove all keys except log
        # the plugin will convert the json into a plain line of text if only the log key remains
        # otherwise the data will be send as json
        RemoveKeys kubernetes,stream,time
        # add all kubernetes labels
        AutoKubernetesLabels true
        # DropSingleKey default value is true!
        DropSingleKey true
```

a sample input could be (json representation):
```
{
    "kubernetes": { ... kubernetes data from kubernetes filter ... },
     "time": 1612390633,
     "stream"; "stderr",
     "message": "this is a sample log line" 
}
```

The output plugin would drop the keys kubernetes, time and stream and only the key message remains. Without the option, the log line sent to loki would be `message=this is a sample log line`.  With the option DropSingleKey enabled, the output login would only send the value of the remaining key and the log line sent to loki would be `this is a sample log line`.

**Comment by zhiguangwang** [comment]
This is a very useful feature, wishing to see this in 1.7 release along with #2821

**Comment by l2dy** [comment]
In `key_value` line_format, Fluent Bit sends log lines like `test="message"`. Should we keep the quotation marks after enabling `drop_single_key`?

**Comment by zhiguangwang** [comment]
The quotation marks should be dropped as well.

So `test="This is a message"` should become `This is a message`, NOT `"This is a message"`.

**Comment by phin1x** [comment]
@l2dy yes, quotation marks should be dropped

**Comment by l2dy** [comment]
The issue is still relevant and has a PR.

**Comment by phin1x** [comment]
The issue is still relevant and has a PR.
