### ISSUE TITLE
Install of v1.6.10 on SLES12SP3 fails with a Bison error: Version requirements?

### ISSUE THREAD

**Issue by pawsey-kbuckley** [fluent/fluent-bit#3009]
More a request for info/ doc update/ than a package bug, 

in that I have previously built  1.3.2 on the platform in question
but have seen this error as far back as v.1.44.

```
[ 29%] [FLEX][lexer] Building scanner with flex 2.6.4
[ 29%] [BISON][parser] Building parser with bison 2.7
ra.y: conflicts: 1 shift/reduce
ra.y:39.9-19: error: %define variable 'parse.error' is not used
src/record_accessor/CMakeFiles/flb-ra-parser.dir/build.make:61: recipe for target 'src/record_accessor/ra_parser.c' failed
```

I fully appreciate that this platform in "old enough to have long 
since retired", but, what can I tell you ...

I just wondered what the specific version requirements were,
given that the Requirements page at

https://docs.fluentbit.io/manual/installation/requirements

is a little vague

- Compiler: GCC or clang
- CMake
- Flex & Bison: only if you enable the Stream Processor or Record Accessor feature (both enabled by default)

**Comment by edsiper** [comment]
Can you try bison 3.x ?

**Comment by pawsey-kbuckley** [comment]
Apologies for not replying to clarfiy that 

my issue was not with the version on our current resource, so trying bison 3.x
isn't something we'll be doing.

The issue here was of version info in the docs.

Feel free to close this issue as you see fit.
