### ISSUE TITLE
Config file line buffer is not big enough

### ISSUE THREAD

**Issue by pragkent** [fluent/fluent-bit#301]
From file https://github.com/fluent/fluent-bit/blob/master/lib/monkey/mk_core/mk_rconf.c, the line buffer size for configuration file is `255`, which is not enough in some cases, especially for parser regex configuration option.

In my case, I wrote a parser for kubernetes nginx log format as below:

```config
[PARSER]
    Name        nginx-ingress
    Format      regex
    Regex       ^(?<remote>[^ ]*) - \[(?<forwarded_for>[^\]]*)\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +(?<http_version>\S*)?))?" (?<status>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)") (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<upstream_name>[^\]]*)\] (?<upstream_addr>[^ ]*) (?<upstream_size>[^ ]*) (?<upstream_time>[^ ]*) (?<upstream_status>[^ ]*)$
    Time_Key    time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```

Then, I got a error from fluent-bit:
```
[2017/06/20 07:01:34] [  Error] File parsers.conf
[2017/06/20 07:01:34] [  Error] Error in line 32: Invalid indentation level
```

**Comment by edsiper** [comment]
thanks for catching this.

I've pushed fix 521b75abdf546fa70f80819ff264eb46aaa421e0 that will be part of 0.11.10 release (to be released this week).

Fixed.
