### ISSUE TITLE
s3 output - PutObject request failure with AWS EC2 IMDSv2

### ISSUE THREAD

**Issue by robinwolny** [fluent/fluent-bit#3012]
## Bug Report

**Describe the bug**
EC2 instances with IMDSv2 cannot upload logs to s3 bucket even EC2 has valid IAM role with a proper policy. EC2 instances with IMDSv1 are working fine. Seems there is an issue to sign the PutObject request (_see the log below_).

Honestly I'm not quite sure if it's a bug but couldn't find anything in the fluentbit documentation. As a workaround we can run the td-agent-bit service with AWS secrets but we consider this as a potential security risk. Using IAM roles with specific policies is preferable. 

Details regarding AWS EC2 roles IMDSv1 vs IMDSv2 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html

Thank you.

**To Reproduce**
- Rubular link if applicable: N/A
- Example log message if applicable:
```
Jan 31 03:15:45 xxxx td-agent-bit: [2021/01/31 03:15:45] [error] [signv4] Provider returned no credentials, service=s3
Jan 31 03:15:45 xxxx td-agent-bit: [2021/01/31 03:15:45] [error] [aws_client] could not sign request
Jan 31 03:15:45 xxxx td-agent-bit: [2021/01/31 03:15:45] [error] [output:s3:s3.0] PutObject request failed
Jan 31 03:15:45 xxxx td-agent-bit: [2021/01/31 03:15:45] [ warn] [engine] failed to flush chunk '27431-1612062943.185337733.flb', retry in 7 seconds: task_id=0, input=tail.3 > output=s3.0
```
- Steps to reproduce the problem:
Run td-agent-bit on AWS EC2 with IMDSv2 and with s3 output.

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: Fluent Bit v1.6.10
* Configuration: s3 output
```
[OUTPUT]
    Name                         s3
    Match                        *
    region                       xx-xxxx-x
    bucket                       xxxx-xxxx-xxxx
    s3_key_format                /ec2-logs/$TAG[0]/%Y-%m-%d/$TAG[1]_$TAG[2]_%Y%m%d%H%M%S
    s3_key_format_tag_delimiters ._
    upload_timeout               20m
    total_file_size              5G
    storage.total_limit_size     10G
```
* Environment name and version (e.g. Kubernetes? What version?): AWS EC2 instance with IMDSv2
* Server type and version: AWS EC2 instance IMDSv2
* Operating System and version: CentOS Linux release 7.9.2009 (Core)
* Filters and plugins: s3 

**Additional context**

**Comment by SamuelDudley** [comment]
Likely related: https://github.com/fluent/fluent-bit/issues/2840

**Comment by kharouny** [comment]
I am having issues using an AWS IAM role to push logs to S3. I am using kub2iam and when I exec into the pod I see that the role is available through sts. 
``` 
[OUTPUT]

        Name                         s3

        role_arn                     arn:aws:iam::*:role/*

        sts_endpoint                 sts.us-west-1.amazonaws.com

        Match                        auditkube.*

        bucket                       ******

        region                       us-west-1

        total_file_size              250M

        s3_key_format                /fluentbit/%Y/%m/%d/%H/%M/%S
```

That is the output I am using. In the logs I am seeing fluent-bit attempting to use the aws credentials.
`[2021/02/10 16:17:34] [error] [aws_credentials] Could not read shared credentials file /root/.aws/credentials
[2021/02/10 16:17:34] [error] [aws_credentials] Failed to retrieve credentials for AWS Profile default
[2021/02/10 16:17:34] [ warn] [aws_credentials] No cached credentials are available and a credential refresh is already in progress. The current co-routine will re
try.`

How do I get fluent-bit to use the IAM role?
