### ISSUE TITLE
Allow the ability to lift from arrays in nested JSON

### ISSUE THREAD

**Issue by morfie78** [fluent/fluent-bit#3013]
**Is your feature request related to a problem? Please describe.**
We have JSON that contains an array of items.  We'd like to lift those to the root for processing by ElasticSearch.

**Describe the solution you'd like**
For the example JSON:
`{"timestamp": "2021-02-03T22:08:46.114752",  ... , "watermarks": [{ "key": "value" }, { "key": "value" }], ... }`

And given the config:
```
[FILTER]
    Name nest
    Match *
    Operation lift
    Nested_under watermarks
```

The output should be
```
{
  ...,
  watermarks.1.key: value,
  watermarks.2.key: value,
  ...
}
```

**Describe alternatives you've considered**
I haven't been able to discern any alternatives except doing this transform upstream, either via FluentD or ElasticSearch Pipelines.

**Additional context**
It would be helpful if component-specific td-agent-bit agents can flatten JSON in a simple and flexible way, instead of having to write a more complex transform upstream, where things might not be specifically dedicated to the component that needs it.

**Comment by amodam-user** [comment]
We're also looking for this - are there any updates on whether this feature is something y'all would be willing to look at?
