### ISSUE TITLE
chunks are getting stuck

### ISSUE THREAD

**Issue by elruwen** [fluent/fluent-bit#3014]
## Bug Report

**Describe the bug**
When I retry forever in the output plugins and the output destinations are unreliable, then chunks sometimes get stuck.

I see messages like 
```
[engine] failed to flush chunk '1-1612396545.855856569.flb', retry in 1485 seconds: task_id=143, input=forward.0 > output=tcp.0
```
but sometimes this is the last thing I see of the chunk. If I send the CONT signal to fluentbit I see that fluentbit still has them.

**To Reproduce**
I got currently a Java dummy application (if required, I can try to trim it down show I can share it easily) which starts 25 threads. Once those threads are all started, each thread sends 2570 log messages, no ack, each around 4500 bytes, to fluent-bit (via https://github.com/komamitsu/fluency). Between each message, each thread sleeps 10ms. The application is a webserver which logs on startup a couple of lines. The actual log messages I trigger via curl.
This application runs on my laptop.

My fluent-bit config
```
[SERVICE]
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_PORT 2020
    Flush 2
    log_level TRACE
    storage.path /fluent-bit/log
    storage.metrics on

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24225
    Buffer_Chunk_Size 64k
    Buffer_Max_Size 2M


[OUTPUT]
    Name   syslog
    Match  *

    host   TARGET_IP
    port   514
    mode   tcp

    syslog_format rfc5424
    syslog_message_key log
    Syslog_maxsize 65534
    syslog_appname_key logdest

    # retry forever
    retry_Limit False
    net.connect_timeout 30
    net.keepalive on
    net.keepalive_idle_timeout 10
    storage.total_limit_size 1G
```

My dockerfile
```
FROM fluent/fluent-bit:1.6.10
ADD fluent-bit.conf /fluent-bit/etc/fluent-bit.conf
```
Started via 
```
docker build --no-cache -f Dockerfile -t ruwen-fluent-bit-bug .
docker run -p 24225:24225 -it ruwen-fluent-bit-bug:latest
```
on my laptop.

I connect to TARGET_IP via a VPN. TARGET_IP is a t2.micro with rsyslog.

Now the following is happening:
- I connect to the VPN
- rsyslog is already running on TARGET_IP
- I start fluentbit on my laptop
- I start the webserver on my laptop
- I disconnect the vpn
- I trigger the endpoint to send all the log messages
- Once all messages are sent (the last few might still be buffered and send a second later), I reconnect to the VPN
- Now fluentbit is successfully sending some of the messages. The little rsyslog box is sometimes a bit overwhelmed so I need more retries.
- The VPN sometimes dies during this process, so I have to reconnect.
- I am keeping an eye on the logs. Since the logs tell me when a retry is expected, I kinda know when to wait and when not. And I always wait some additional time.

This way I can reproduce the issue reliable. This produces the following log:
[fluentbit_syslog.log](https://github.com/fluent/fluent-bit/files/5922699/fluentbit_syslog.log)

I tried to reproduce it by running syslog locally and use iptables to sometimes drop packages and sometimes not. Without success. But I managed to reproduce the same problem with the tcp output plugin. I tried that to make sure that the problem is unrelated to the syslog output plugin.

The config is used for that:
```
[SERVICE]
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_PORT 2020
    Flush 2
    log_level TRACE
    storage.path /fluent-bit/log
    storage.metrics on

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24225
    Buffer_Chunk_Size 64k
    Buffer_Max_Size 2M


[OUTPUT]
    Name   tcp
    Match  *

    host   TARGET_IP
    port   514
    format   json

    # retry forever
    retry_Limit False
    net.connect_timeout 30
    net.keepalive on
    net.keepalive_idle_timeout 10
    storage.total_limit_size 1G
```

I followed the same procedures as described. On my aws box I initially used nc, which stopped after each connection. Then I used it with the -k option, but that didn't help. I ended up installed ncat via 
```
ncat -l -k  514 > /dev/null
```
The whole restarting nc causes even more havoc. With the syslog test, I normally get 1 chunk stuck. Now I got even more.
The resulting logfile.
[fluentbit_tcp.log](https://github.com/fluent/fluent-bit/files/5922714/fluentbit_tcp.log)

To see which chunks are missing, I wrote a little python script which parses those logs. It might be helpful.
```
#!/usr/bin/env python3

outstanding_chunks_to_error_msgs = dict()

with open('/tmp/fluentbit.log', 'r') as f:
    for line in f:
        line = line.strip()
        line = line.replace("\x1b[1m[\x1b[0m", "").replace("\x1b[1m]\x1b[0m", "")
        if 'failed to flush chunk' in line:
            chunk = line.split("'")[1]
            errors = outstanding_chunks_to_error_msgs.get(chunk)

            parts = line.split(" ")
            error_msg = f"{parts[0]} {parts[1]}: {parts[12]} {parts[13][:-1]}"
            if errors:
                errors.append(error_msg)
            else:
                outstanding_chunks_to_error_msgs[chunk]=[error_msg]
        elif 'flush chunk' in line and 'succeeded at retry' in line:
            chunk = line.split("'")[1]
            del outstanding_chunks_to_error_msgs[chunk]

for chunk, errors in outstanding_chunks_to_error_msgs.items():
    print(f"{chunk}: {errors}")

print(f"{len(outstanding_chunks_to_error_msgs)} missing")
```

**Expected behavior**
Chunks being retried until they succeed.

**Your Environment**
* Version used: Docker fluent/fluent-bit:1.6.10. I also tried Docker fluent/fluent-bit:1.7.0-rc3, without success. Since some log messages are now missing, tracing the issue is harder, see https://github.com/fluent/fluent-bit/issues/3001
* Configuration: see reproduce section
* Environment name and version: local laptop
* Server type and version: 16 GB RAM, 8 Cores (Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz), SSD
* Operating System and version: 
```
uname -a
Linux ruwenwork 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```
* Filters and plugins: see reproduce section

**Additional context**
How has this issue affected you? What are you trying to accomplish?

I am currently building a logging pipeline to use fluent-bit. My goal is to be able to ingest 256 MB/minute (that's peak, I normally don't need that) and to be able buffer data for a while when upstream is having issues. I am currently not imposing a memory limit, I didn't get that far in my tests.

Please let me know if you need any further details. I am more than happy to build any other branch and try my luck with it.

Cheers
Ruwen

**Comment by marckamerbeek** [comment]
Experiencing the same issue here. Using fluentbit version 1.6.6 and output to Elastic Search. No error back from elastic. It only happens to one of many tail input>->k8s filter -> elastic output. In my case to nginx-ingress logs. I got many more (same) input-filter-output flows and they work without any problems. 

Tried to turn on Debug, but no succes in finding an error.

**Comment by elruwen** [comment]
Same problem happens with 1.7.0. Tracing down the issue became harder due to https://github.com/fluent/fluent-bit/issues/3001

So that little python script I posted doesn't detect anymore if a chunk has been properly retried.

**Comment by JeffLuoo** [comment]
@elruwen Could you please try the latest master code to see if that still happens?

**Comment by elruwen** [comment]
Sorry for the delayed answer. Yes it still happens. I tried commit 555b22a026c83ad26677cd98d8d78c8b6b82d5e0. See attached logs.
[555b22a026c83ad26677cd98d8d78c8b6b82d5e0.log](https://github.com/fluent/fluent-bit/files/6120028/555b22a026c83ad26677cd98d8d78c8b6b82d5e0.log)

**Comment by elruwen** [comment]
If you want to reproduce it yourself, the following java code might help (see attachment).

- Start fluentbit with the following config, again, adjust the IP (127.0.0.1 might be fine, depending on if you run fluent-bit in a docker container or not)
```
[SERVICE]
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_PORT 2020
    Flush 2
    log_level TRACE
    storage.path /fluent-bit/log
    storage.metrics on

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24225
    Buffer_Chunk_Size 64k
    Buffer_Max_Size 2M


[OUTPUT]
    Name   tcp
    Match  *

    host   192.168.188.29
    port   5140
    format   json

    # retry forever
    retry_Limit False
    net.connect_timeout 30
    net.keepalive on
    net.keepalive_idle_timeout 10
    storage.total_limit_size 1G
```

- 
[fluentbitbugjava.zip](https://github.com/fluent/fluent-bit/files/6127913/fluentbitbugjava.zip)
Unpack the zip file. The dir structure should look like this:
```
find .      
.
./src
./src/test
./src/test/java
./src/test/java/ruwen
./src/test/java/ruwen/MyAppenderTest.java
./src/main
./src/main/java
./src/main/java/ruwen
./src/main/java/ruwen/MyAppender.java
./src/main/resources
./src/main/resources/logback.xml
./pom.xml

```

- Create somewhere a folder where java can cache its downloaded dependency.

Enter the directory and then run maven (a java build tool) via docker like this (adjust the java cache path and IP)
```
docker run --network=host -it --rm --name fluentbitbug-java-repro -e FLUENTBIT_HOST=192.168.188.29 -v "$(pwd)":/usr/src/mymaven -v /path/to/java/cache:/root/.m2  -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
```
- wait for the java program to exit
- run `nc -l -k  5140 > /dev/null`
- wait until everything is suppose to be consumed

**Comment by JeffLuoo** [comment]
@elruwen Could you please try adding `storage.type  filesystem` to your input plugin configuration? If this is not set then Fluent bit is going to use memory to buffer chunks and if filesystem is not enabled.

**Comment by elruwen** [comment]
That doesn't make a difference :(

**Comment by elruwen** [comment]
Yes. Just to clarify. It is not only one chunk. At the moment I got 25 chunks stuck and 25 chunks on disk.

**Comment by JeffLuoo** [comment]
`storage.total_limit_size` is not stable @1.6.10. Could you please try without that option?

**Comment by elruwen** [comment]
My last try was still on commit id 555b22a026c83ad26677cd98d8d78c8b6b82d5e0.

I used now 1.7.2. The problem still persists (both, the chunks stuck and the missing log messages). But I got now a new error message:
```
[2021/03/23 03:01:19] [error] [upstream] connection #100 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #65 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #84 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #78 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #94 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #72 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #79 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #68 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #68 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #68 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:19] [error] [upstream] connection #72 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #41 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #48 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #47 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #57 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #63 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #72 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #65 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #49 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #50 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #68 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #64 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #58 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #77 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #79 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #83 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #72 to 192.168.188.29:5140 timed out after 30 seconds
[2021/03/23 03:01:20] [error] [upstream] connection #100 to 192.168.188.29:5140 timed out after 30 seconds

```

This gets spammed quite a lot. The weird thing about it is that this message gets logged imho too often. Look at connection #100. The first log message says it timed out after 30 seconds. I would expect the next "timeout after 30 seconds" message in 30 seconds and not one second later.

Here is the complete log: 
[fluentbit-1.7.2.log.gz](https://github.com/fluent/fluent-bit/files/6186632/fluentbit-1.7.2.log.gz)

Used config:
```
[SERVICE]
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_PORT 2020
    Flush 2
    log_level TRACE
    storage.path /fluentbitstorage
    storage.metrics on

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24225
    Buffer_Chunk_Size 64k
    Buffer_Max_Size 2M
    storage.type filesystem


[OUTPUT]
    Name   tcp
    Match  *

    host   192.168.188.29
    port   5140
    format   json

    # retry forever
    retry_Limit False
    net.connect_timeout 30
    net.keepalive on
    net.keepalive_idle_timeout 10
    #storage.total_limit_size 1G
```

Are you happy for me to use 1.7.2? As offered before, I am happy to use any branch/commit etc. Or shall I go back to 1.6.10?

**Comment by JeffLuoo** [comment]
From logs you provided, it looks like the chunk issue is caused by the bad upstream connection:
```
[2021/03/23 03:01:20] [error] [upstream] connection #58 to 192.168.188.29:5140 timed out after 30 seconds
```

If the chunk can't be shipped to its destination, then it will stuck on your disk as you configured `retry_Limit False`. There is a ticket reporting the timeout issue #3192 that didn't happen before in the older version (v.1.6.x). I suspect your case is related to that ticket, do you mind waiting for that issue to be resolved and test it again?

**Comment by elruwen** [comment]
Sure.
Just to clarify: I am using netcat as a destination. I expect a lot of issues with my upstream connection. But I would expect that at some point they are resolved.
If you want, I can also test the PR linked in #3192.

**Comment by JeffLuoo** [comment]
#3202 Looks like has been merged. Could you please give it a try?

**Comment by elruwen** [comment]
[fluentbit-1938ec84.log.gz](https://github.com/fluent/fluent-bit/files/6202211/fluentbit-1938ec84.log.gz)

The message is gone, the problem persists. After pressing ctrl+c once to initiate shutdown, I restarted netcat. But that still didn't help.

**Comment by pierluigilenoci** [comment]
@JeffLuoo #3202 is not merged. It has a conflict on the file `src/flb_upstream.c`

**Comment by elruwen** [comment]
Something got merged that made the time-out spam go away, see my attached logs.

**Comment by JeffLuoo** [comment]
@pierluigilenoci Sorry mb. The code has been merged into master by maintainer https://github.com/fluent/fluent-bit/commit/1938ec845255dd27a1b0ad39e1654b3b351277be

**Comment by JeffLuoo** [comment]
I noticed a lot of logs like
```
[1m[[0m2021/03/25 04:15:24[1m][0m [[91merror[0m] [plugins/out_tcp/tcp.c:96 errno=32] Broken pipe
```

Looks like the connection issue is still not resolved by the merged code..?

**Comment by elruwen** [comment]
I run as a target service netcat for testing. This isn't able to handle all the connections which fluent-bit wants to do. Which is fine.
You see those messages:
```
[engine] failed to flush chunk '1-1616645726.798535377.flb', retry in 803 seconds: task_id=46, input=forward.0 > output=tcp.0 (out_id=0)
```
And some point, I get one of those messages, but it is NOT retrying in 803 seconds. While I see those messages I am fine. But the retries are not happening.

To help me, I use this little script to determine after which date all chunks should have been retried:
```python
#!/usr/bin/env python3
import datetime
import pytz

max_date = datetime.datetime.utcnow() - datetime.timedelta(days=42)

with open('fluentbit-1938ec84.log', 'r') as f:
    for line in f:
        line = line.strip()
        line = line.replace("\x1b[1m[\x1b[0m", "").replace("\x1b[1m]\x1b[0m", "")
        if 'failed to flush chunk' in line:
            parts = line.split(" ")
            date_time_obj = datetime.datetime.strptime(f"{parts[0]} {parts[1]}", '%Y/%m/%d %H:%M:%S')
            end = date_time_obj + datetime.timedelta(seconds=int(parts[12]))
            end.replace(tzinfo=pytz.UTC)

            if end > max_date:
                max_date = end


print(max_date)
```

You can verify that via the timestamps of the logs.

So "The chunk will be shipped when the connection issue is resolved." is not happening.

**Comment by elruwen** [comment]
Let me try to explain more:
I am currently preparing to move some systems into docker and I want to use fluent-bit as a log shipper.
So I started to do some tests. My performance tests went all well. Then I started to test how things are going when my logging cluster has issues. So I started to play around, initially just via a box in AWS. Since I found issues, I tried to isolate the issue and also to make it reproducible. That's why I am using netcat as a logging destination.

**Comment by Z18Aplha** [comment]
something happening here? I have the same problems with my fluent-bit docker container. I try to get the logs of my containers to loki and it fails with the same error message: ```failed to flush chunk``` and then ```chunk cannot be retried```
It says something like ```HTTP status=400``` but my loki instance is working and I triple checked the connection settings.

**Comment by elruwen** [comment]
I tested it the last time with `1.7.3`. Still an issue.

**Comment by pierluigilenoci** [comment]
@edsiper could you please take a look?

**Comment by lazystone** [comment]
@elruwen could you try 1.7.4? After update to 1.7.4 we haven't had that problem yet, but I don't know if it's just pure luck or it was fixed somehow.

**Comment by elruwen** [comment]
Problem still exists with 1.7.4. My other ticket (the one about the log message) is also still happening.

https://github.com/fluent/fluent-bit/blob/master/src/flb_engine.c#L198

I never see that message, even though I used to see it. Maybe that helps pointing in the right direction.

**Comment by staniondaniel** [comment]
I encountered similar issues here https://github.com/fluent/fluent-bit/issues/3299 but even after i disable the retry forever the logs are not being sent anymore(old or new chunks) and they just gather in memory until the process crash due to OOM . The problem persists even with the latest version
My only workaround was to increase Emitter_Mem_Buf_Limit for each filter to very high values (like a few GB) and pray that the buffer doesn't get filled or any logs won't be sent to ES anymore

**Comment by konstantin-kornienko** [comment]
Same issue with all versions, including 1.7.5 and forward output. Only restarting of td-agent-bit helps.

**Comment by JeffLuoo** [comment]
Setting `workers` in the output section might speed up the chunk processing time. Does this help?

**Comment by elruwen** [comment]
> Setting `workers` in the output section might speed up the chunk processing time. Does this help?

How and where? https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file doesn't mention workers, https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls neither.

**Comment by JeffLuoo** [comment]
```
[OUTPUT]
    Name   tcp
    Match  *

    host   192.168.188.29
    port   5140
    format   json

    # retry forever
    retry_Limit False
    net.connect_timeout 30
    net.keepalive on
    net.keepalive_idle_timeout 10
    workers         5
```

**Comment by elruwen** [comment]
I used 1.7.6 with and without the workers statement. In both cases the result is the same and way worse than before.
Before only a few chunks got stuck, no none of them of them are retried.

Previously a log message was emitted which said something like
```[engine] failed to flush chunk '1-1613013266.34830441.flb', retry in 9 seconds: task_id=0, input=tcp.0 > output=tcp.0```
see https://github.com/fluent/fluent-bit/blob/master/src/flb_engine.c#L281

This log message is completely missing. I attached the logs from the run without workers being set.
[log-1.7.6.zip](https://github.com/fluent/fluent-bit/files/6536443/log-1.7.6.zip)

**Comment by pierluigilenoci** [comment]
I don't understand why nobody takes care of this problem that seems evident is affecting a lot of users. 

@edsiper @fujimotos @koleini could you please take a look?

**Comment by JeffLuoo** [comment]
@elruwen I saw a flood of connection time_out in the logs you attached. Is it because the output endpoint it not reachable?

**Comment by elruwen** [comment]
> @elruwen I saw a flood of connection time_out in the logs you attached. Is it because the output endpoint is not reachable?
> 
> Update: Just wanna test a case that the output endpoint is reachable before running the Fluent Bit.

Correct. When I start to send messages, the output endpoint is not reachable. When I initially reported the problem, my setup was:
- send a couple of messages (they got delivered)
- shut down the destination
- send a lot of logs
- start the destination again

I haven't tested that in a while.

Now my tests are always:
- start fluent-bit
- send a lot of logs
- wait a minute
- start the destination

**Comment by JeffLuoo** [comment]
thanks for providing the info. Probably we can narrow down the problem by trying this order to see whether this is an issue of upstream connection:
- start the destination
- start fluent-bit
- send a lot of logs
- wait a minute to see if logs arrive

**Comment by elruwen** [comment]
I did that and my results are:
```
1.6.10: some arrive, some get stuck
1.7.4: some arrive, some get stuck
1.7.6: nothing arrives
1.7.7: some arrive, some get stuck
```
I ran tcpdump for 20 minutes after the last chunk arrived for 1.7.7, but no further traffic. I always got 26 or 27 chunks missing.

I was wondering if it is a problem with nc, so I wrote a small Java server. Exactly the same issue.

I removed storage, same problem exists.

**Comment by pierluigilenoci** [comment]
@elruwen let me thank you for all your effort to address this problem. 🙇🏻

**Comment by elruwen** [comment]
Anything else I can do so that this gets addressed? I am happy to create an end2end runnable test in java which can run as part of the build, but since I don't know C, I would write it in Java. Not sure how keen you are to have Java in your project. I could try my luck in Go, but I never wrote something like that in Go before... ;)

**Comment by pierluigilenoci** [comment]
@edsiper @fujimotos @koleini why doesn't anyone give even half a feedback about it?

**Comment by Kampe** [comment]
Seeing the same issues still with 1.8.1

**Comment by ivangrynkoring** [comment]
The same with 1.8.3, we stuck with 1.6.10 last working version

**Comment by pierluigilenoci** [comment]
@elruwen have you tried v1.8.*?

**Comment by agup006** [comment]
There were a few fixes in 1.8.3 that include chunk handling after failure. I'm wondering if the retry forever paired with some bad messages cause chunks to never be flushed or dropped. 

@ivangrynkoring  did you see a lot of 400 errors in the logs? Also curious what outputs you were using

**Comment by elruwen** [comment]
I just tried 1.8.3.

- 16 chunks missing (that is a record low)
- all 16 chunks are on disk
- I see error messages that a chunk can't be flushed "[ warn] [engine] failed to flush chunk '1-1628553346.148642522.flb', retry in 321 seconds: task_id=25, input=forward.0 > output=tcp.0 (out_id=0)" (which is good!)
- I see generic error messages pointing to the underlying issue "[error] [plugins/out_tcp/tcp.c:96 errno=32] Broken pipe" I find that error message a bit confusing, because I would derive from it that the connection was established. It used to be "[error] [upstream] connection #41 to 192.168.188.29:5140 timed out after 30 seconds", which is imho the better error message.
- There is still no error message indicating that the chunk could be flushed, even though the log message exists in the code https://github.com/fluent/fluent-bit/blob/v1.8.3/src/flb_engine.c#L202 (see also issue #3001)

As said before, happy to help out further if I can somehow.

**Comment by pierluigilenoci** [comment]
@edsiper @fujimotos @koleini why doesn't anyone give even half a feedback about it?

It's amazing that no one even deigns to look at all these reports of fluent-bit problems. 😢

**Comment by agup006** [comment]
@elruwen thanks for running that test - when the chunk couldn't be flushed are you seeing any error codes from the end output (Syslog server / Splunk or Elasticsearch) such as a 400 bad message error? Also do you have some information regarding the I/O on the machine as the chunks get stuck - looking for some patterns

@pierluigilenoci I am looking at this :) - a few folks are working on DNS TCP / UDP resolution improvements / IO improvements and chunk optimizations within the 1.8.x series. We do need to do a better job of showcasing what folks are working on and we welcome ideas from the community on how best to demonstrate that. I would ask if you can join our next [community meeting](https://docs.google.com/document/d/1vJvsn8E0SanLO1R0X3RC1qTw0XQK_7q75sZ8IbWAu-g/edit#heading=h.nowdn7qwlldd) (Last Thursday of each August) with suggestions on how best to view what folks are working on as well as ways that you could help contribute in that process.

**Comment by elruwen** [comment]
@agup006 the receiving end is ncat. No HTTP. I don't see any errors. ncat just dumps the stuff to /dev/null. It all runs on my local laptop.

I don't know much about the tooling landscape in C, but if it would be in Java, I would do the following:

1. Reproduce it locally on your machine (See https://github.com/fluent/fluent-bit/issues/3014#issuecomment-797257579), reproduce it 3 times so you know it can be reproduced reliable.
2. Run it once again, but in debug mode. Wait until the chunks are stuck. Add a breakpoint to the main event loop and have  a look. Or get a thread-dump (not sure if you can get that for coroutines).

**Comment by elruwen** [comment]
@agup006 could you reproduce it locally?

**Comment by agup006** [comment]
@elruwen I have a local repo of an issue that has very similar behavior (High EPS and events get stuck) to this and trying to debug that one first prior to jumping into this one. I do appreciate the easy repro steps though that should hopefully make it easy to see if it is fixed for this use case

**Comment by rpuserh** [comment]
Hi,
I have similar problem where http output delivery fails and chunks stuck. 
All other outputs stop delivering logs.

**Comment by lazystone** [comment]
My observation that on 1.8.6 it became much worse. On 1.8.5 it mostly worked, but on 1.8.6 it constantly stuck, basically unusable.

**Comment by agup006** [comment]
Unfortunately the dns fixes in 1.8.6 did not work as intended, need to see what we can do to fix

**Comment by elruwen** [comment]
@agup006 I offered it earlier: If I would write some end2end regression tests in Java. Would you guys use them? Or not since it is another language?

**Comment by agup006** [comment]
We are open if they are simple to run, for example our current e2e for Splunk / elasticsearch use a combination of go / terraform and the C API. Adding @niedbalski who wrote those

**Comment by elruwen** [comment]
Cool, can you please point me to that code? So I can add mine to the same place. Thanks!

**Comment by agup006** [comment]
Sorry clicked close on mobile https://github.com/calyptia/fluent-bit-ci

**Comment by elruwen** [comment]
Hmm I had a look. Those tests spin up real clusters etc. Mine are a number smaller. Maybe the term integration test is better? 

One Java process which starts/stops the fluent-bit binary and does everything. Ideally those would run on every commit of this repo.

To get you an idea, I commited my tests: https://github.com/elruwen/fluent-bit/commit/11f6b8106ca20c573dcceb0191ee7a14e93230c5

It would for example have caught the issues with the 1.7.6 release, which was more broken then the releases before and after.

Once the docker containers and the java libraries are downloaded, the actual build takes only 75s on my machine. That could be speed up if I could configure the time between retries to be shorter.

Overall I think it think they should go into the build of this repo.

**Comment by elruwen** [comment]
Oh and with my tests I can also reproduce chunks getting stuck with just high load. Do you want to open a new case for that?

**Comment by agup006** [comment]
@elruwen would you be open to a Zoom sync? Anurag at Calyptia dot com

**Comment by agup006** [comment]
Hey folks, updating @elruwen gave us a really nice repro and we will be freeing up after fixing some of the odd DNS timeout issues in 1.8.7. Realistically, will have some more details after FluentCon NA (Oct 12). I'll also bring up this issue in the community meeting Thursday Sept 30 @ 9:00 AM PST

**Comment by hansh0801** [comment]
track

**Comment by rumstead** [comment]
Has anyone tried this with 1.8.9?

**Comment by elruwen** [comment]
> Has anyone tried this with 1.8.9?

Yes, still doesn't work.

**Comment by Minutis** [comment]
And still does not work with 1.8.10.

**Comment by elruwen** [comment]
Just tested it with 1.18.11. Same issue.

**Comment by rumstead** [comment]
Going to take a wild guess that the 1.18.12 release has the same issue?

**Comment by elruwen** [comment]
> Going to take a wild guess that the 1.18.12 release has the same issue?

Correct :(

**Comment by agup006** [comment]
@elruwen we have a couple PRs for this by @leonardo-albertovich , would you be able to help us test it out? 
https://github.com/fluent/fluent-bit/pull/5111
https://github.com/fluent/fluent-bit/pull/5110

**Comment by elruwen** [comment]
Amazing job @leonardo-albertovich, both branches pass the tests!

The log messages to notify that the retry was successful are still missing (see https://github.com/fluent/fluent-bit/issues/3001).

And are you guys still interested in the tests? https://github.com/fluent/fluent-bit/pull/4162

**Comment by agup006** [comment]
Awesome to hear @elruwen! These should be merged and available in 1.9.1

we used the Java pieces for repro, I'm not sure if our current integration has the ability for Java tests though I'll defer to @patrick-stephens and @niedbalski on that question

**Comment by patrick-stephens** [comment]
We can add but it'll need proper integration so might need some more work on that PR. As long as they're stable, more tests are better.

**Comment by agup006** [comment]
1.9.1 is now avialable, going to close this issue - finally! We can track the log message updates in the other issue.
