### ISSUE TITLE
SIGSEGV error occurred in fluent bit, resulting in process crash

### ISSUE THREAD

**Issue by wgb1990** [fluent/fluent-bit#3023]
## Bug Report

**Describe the bug**
We use the version of fluent bit v1.6.9 to collect logs and send them to fluentD. It is found that there is a probability of SIGSEGV error in the production environment, which eventually leads to frequent crash of the process. Then SYSTEMd will pull up the process again, and finally the disk of the machine is full

**To Reproduce**
fluent-bit logs
![image](https://user-images.githubusercontent.com/7124162/106988326-80ec4080-67aa-11eb-9ee5-f5cb11c25d26.png)

![image](https://user-images.githubusercontent.com/7124162/106998853-1f36d100-67c0-11eb-9e11-b6d64fc07dba.png)
@SET log_dir=/logs
@SET service=deposit-interfaces

config file content

[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush       5

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  On
    http_listen  0.0.0.0
    http_port    2021

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' optoin is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    storage.path /var/log/td-agent-bit/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    storage.backlog.mem_limit 20M

[INPUT]
    Name tail
    Ignore_Older 1m
    DB tail_info.db
    DB.Sync OFF
    Path ${log_dir}/*.${log_file_suffix}
    Exclude_Path *20*.log,*access.log,*sql.log,*spring*.log,gc.log,heap.log
    Multiline On
    Parser_Firstline logback
    Tag logs.${domain}.${service}.${HOSTNAME}.${loki_tenantid}
    Buffer_Chunk_Size 256K
    Buffer_Max_Size  256K
    Skip_Long_Lines On
    Mem_Buf_Limit 5M
    storage.type filesystem
    
[INPUT]
    Name tail
    Ignore_Older 1m
    DB tail_access.db
    DB.Sync OFF
    Path ${log_dir}/deposit-interfaces-access.log
    Multiline On
    Parser_Firstline access_logback
    Tag access.logs
    Buffer_Chunk_Size 512K
    Buffer_Max_Size  512K
    Skip_Long_Lines On
    Mem_Buf_Limit 10M
    storage.type filesystem

[OUTPUT]
    Name        kafka
    Match       access.logs
    Format      json
    Brokers     xxxx
    Topics      trade_cycle_center
    
[OUTPUT]
    Name          forward
    Match         logs.*
    Host          xxxx
    Port          24224

**Comment by stevehipwell** [comment]
@wgb1990 have you taken a look at issue #2937? I don't think it's the same issue but they might be related?

**Comment by edsiper** [comment]
I am wondering if Kafka plugin was buffering most of the data and is not flusing the data fast enough, so it get's up in memory.

If you disable kafka do you see the same issue ?
