### ISSUE TITLE
How to deal with kafka Broker: Policy violation

### ISSUE THREAD

**Issue by AntonDobshikov** [fluent/fluent-bit#3030]
We are using Azure Event Hub as an output of the fluent-bit.
It has two limitations around the ingress rate: maximum throughput in MB/s and maximum events rate in counts/second.
For example, if we order Azure Event Hub  1TU that will be limited to 1 MB/second or 1000 events/second whatever comes first.
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-scalability

Eventually, we have a lot of
`[2021/02/06 11:45:14] [ warn] [output:kafka:kafka.0] message delivery failed: Broker: Policy violation`
in our logs. And it seems they might cause a major fluent-bit failure like here  #3029 
We know exactly what limits we have. 
Can we somehow configure fluent-bit to not reach these limits?

**Comment by agup006** [comment]
One option could be to use throttle to rate limit the max throughput: https://docs.fluentbit.io/manual/pipeline/filters/throttle

Rate right now depends on message count so there would need to be an estimation at what to set the limits to

**Comment by AntonDobshikov** [comment]
yes, thanks this one should help us to avoid events/second policy violation, and we also need something for overall throughput.
 in our environment, we can't calculate a good estimation of mean message size.
