### ISSUE TITLE
Allow plugins to expose metrics as floating values

### ISSUE THREAD

**Issue by yongtang** [fluent/fluent-bit#3031]
**Is your feature request related to a problem? Please describe.**

While trying to develop a fluent-bit plugin and expose some metrics, I noticed that at the moment, fluent-bit always expose metrics as unsigned 64-bit integers, see:

https://github.com/fluent/fluent-bit/blob/master/src/http_server/api/v1/metrics.c#L326

This might not be flexible as some plugins may want to expose float64 value metrics. It would be great if fluent-bit can support exposing metrics with float64.

**Describe the solution you'd like**

The related code are mostly in those two places:
https://github.com/fluent/fluent-bit/blob/master/src/flb_metrics.c#L159
https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_metrics.h#L45

There might be two ways to add float64 support:
1. We can change the `val` field to `double` and always use float64. Some precision might be lost though.
2. We can change the `val` field to union of uint64 and float64, add a type field to indicate the type, and process the value based on the type.

Happy to create PR if possible.

cc @edsiper

**Comment by edsiper** [comment]
@yongtang 

there is a new ```native``` metrics interface coming up in Fluent Bit, that interface will deprecate the current implementation and support float64.
