### ISSUE TITLE
out_influxdb support for v2 API

### ISSUE THREAD

**Issue by fopina** [fluent/fluent-bit#3032]
## Bug Report

**Describe the bug**

Unable to ship data to an InfluxDB 2.0 instance as it only supports `Token` authorization header, not basic auth (as currently implemented in out_influxdb)

I've modified the built-in out_influxdb to support v2 (in https://github.com/fopina/fluent-bit-out-influxdb-v2). Should I submit it as PR? If so, should it be added to `out_influxdb`or kept as separate output plugin?

**Comment by edsiper** [comment]
Hi, thanks for this.

I am totally OK to receive a PR to update this, my only question is: how many users are still in v1 of the protocol ? I am not aware of more details but if most of users are running v2 we should be ok, but hard to say...

Is there a way to make v2 the default one but add an option to enable the old mechanism ?

**Comment by fopina** [comment]
I don't have any data to support this, but I'm pretty sure most will be on v1, as v2 is not so stable yet (only now adding arm builds).

If we'd add as parameter of same plugin, I think default should stay v1 (also to avoid breaking changes).

But not sure how to name the parameters in the scenario though.
Database becomes bucket. But organization is new. And authentication only requires one parameter(token) which is neither of the existing two.

Would something like adding:

API_version: default to v1, support option v2
Database: update documentation to reflect it's the bucket name in v2
Http_user/passwd: update doc to say it's only used in v1
Http_token: doc saying it's only used in v2
Org: same as token

would this make sense? Or too confusing?

**Comment by agup006** [comment]
>API_version: default to v1, support option v2
Database: update documentation to reflect it's the bucket name in v2
Http_user/passwd: update doc to say it's only used in v1
Http_token: doc saying it's only used in v2
Org: same as token

These options look good to me. The only note is if "Bucket" is the new terminology in v2, I would opt for a dedicated setting of "Bucket" vs using Database for both v1 / v2. I'm not an InfluxDB expert

**Comment by fopina** [comment]
Good point. I guess it makes sense, as bucket is not only new terminology but also different as it is both database and retention policy.

So maybe have bucket as separate setting and, if defined, ignore database and use v2 URLs (and drop api version parameter)

**Comment by agup006** [comment]
>So maybe have bucket as separate setting and, if defined, ignore database and use v2 URLs (and drop api version parameter)

+1 from me, I'll need to learn a bit more about InfluxDB sounds pretty cool :)

**Comment by fopina** [comment]
@edsiper let me know if there's anything else required for #3040 as this is my first contribution to the project :)
