### ISSUE TITLE
Missing header when outputting to a S3 bucket with Object Lock enabled

### ISSUE THREAD

**Issue by brunosimsenhor** [fluent/fluent-bit#3035]
When I tried the the [Object Lock](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock-overview.html) in the target bucket I got `InvalidRequest` errors from the PutObject API.

According to the output error and the AWS documentation, the `Content-MD5` header is missing from the request and is necessary to .

Is there any plans to include this header?
This header could be flagged to be sent under an option like `send_content_md5_header` or something better than that.

```
[2021/02/08 13:50:16] [error] [output:s3:s3.2] PutObject API responded with error='InvalidRequest', message='Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters'
[2021/02/08 13:50:16] [error] [output:s3:s3.2] Raw PutObject response: HTTP/1.1 400 Bad Request
x-amz-request-id: xxx
x-amz-id-2: xxx
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 08 Feb 2021 13:50:16 GMT
Server: AmazonS3
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters</Message><RequestId>xxx</RequestId><HostId>xxx</HostId></Error>
[2021/02/08 13:50:16] [error] [output:s3:s3.2] PutObject request failed
[2021/02/08 13:50:16] [error] [output:s3:s3.2] Could not send chunk with tag my-application-tag
```

PS: this was already requested by @bksteiny in https://github.com/fluent/fluent-bit/issues/2700#issuecomment-717487047.

**Comment by edsiper** [comment]
assigned to @PettitWesley

**Comment by brunosimsenhor** [comment]
Do we have any updates? :D

**Comment by PettitWesley** [comment]
No update as of now beyond that we will track this on our backlog.

CC @zhonghui12

**Comment by zhonghui12** [comment]
This issue has been mentioned in #2700 which is a public issue for us to track S3 requests, so this separate one will be closed. We will keep tracking it in #2700.
