### ISSUE TITLE
HTTP keepalive does not work on big endian systems

### ISSUE THREAD

**Issue by erikmaas** [fluent/fluent-bit#3037]
## Bug Report

**Describe the bug**

On big endian systems, like the Philips Hue bridge, the HTTP keep-alive of the HTTP output plugin does not work as expected.
The connection is closed immediately after the response to the first HTTP post, regardless of the keep-alive setting in the configuration files.

This is caused in `flb_upstream.c` in the first element of the `upstream_net struct` where the configuration value is parsed.
A bool value is written as a `char` into `flb_net_setup.keepalive` which is an `int`. The first byte of keepalive will be written.
On a little endian system this does not cause a problem, but on big endian systems the `int` value will be read back as `0x01000000` instead of `1`.

As an effect, in `create_conn()` the comparison of `u->net.keepalive` against `FLB_TRUE` will never match. Therefore on big endian systems `flb_upstream_conn_recycle(conn, FLB_FALSE)` will always be executed when creating the connection.

**To Reproduce**
Use a big endian system and try the HTTP output plugin.
Examples of that are many (but not all) routers with a MIPS and running OpenWrt.

**Expected behavior**
After a single HTTP post, the connection should remain open until the server decides to close the connection.

**Solution**

We tried a few fixes for this issue.

* Change the type of `flb_net_setup.keepalive` to `char`
or
* Change the type of any `bool` value from `char` to `int`

**Your Environment**
OpenWrt17 on a big endian MIPS.

* Version used: 1.6.8
* Configuration: -
* Environment name and version (e.g. Kubernetes? What version?): -
* Server type and version: -
* Operating System and version: Philips Hue bridge, derived from OpenWrt 17, Big endian.
* Filters and plugins: http output

**Additional context**
Not having keep-alive increases load and cost for our cloud infrastructure.

**Comment by edsiper** [comment]
would you please retry GIT Master ?

**Comment by erikmaas** [comment]
Problem is solved.
