### ISSUE TITLE
splunk index_key

### ISSUE THREAD

**Issue by beth2016** [fluent/fluent-bit#3048]
In fluentd, we can set index_key to specify the variable that will contain the splunk index.
So we can send logs to different splunk index based on a pod label.
Can we implement something silimar in fluent-bit?

**Comment by agup006** [comment]
Hi @beth2016, I'm wondering if we could use the HTTP event collector's feature to specify a field: `index` and then have Splunk index based of that field. Prior to the output of sending the data we could add a modify filter that adds the new index name

```
[FILTER]
    name modify
    match *
    add index CUSTOM_INDEX

[OUTPUT]
    name splunk
    ....
```

From this documentation: https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/FormateventsforHTTPEventCollector
![image](https://user-images.githubusercontent.com/3642874/108443646-042b7e80-720e-11eb-8146-0d938cf4d1bb.png)

**Comment by beth2016** [comment]
Hi @agup006 Thanks for responding.   Already tried that, it doesnt work.   It's not taking variable.   Any variable I put there, its taking it as constant.  So, in your example, it will try to use CUSTOM_INDEX literally.
