### ISSUE TITLE
HTTP_Output gzip data not being automatically decompressed by my HTTP server.

### ISSUE THREAD

**Issue by arianitu** [fluent/fluent-bit#3049]
## Bug Report

**Describe the bug**
I assumed my HTTP library would handle the fluent-bit output for gzip compression, but it does not. I think http_out should set the `Content-Encoding` header to `gzip`?

It looks like I have to manually decompress the data with the way the http_out module sends it?

**To Reproduce**
Set `Compression gzip` on HTTP output and send it to a standard HTTP server. The Body will not be decompressed automatically.

**Expected behavior**
My HTTP server should decompress the body automatically.

**Your Environment**
* Version used: 1.6

**Additional context**

**Comment by arianitu** [comment]
I guess this would be a breaking change since now I am manually decoding the payload and if newer versions set `Content-Encoding` my decoding will fail since the HTTP server would decode it.

I am unsure what the best way to handle this situation is?

**Comment by arianitu** [comment]
Actually, looking at `http.c`, it appears it is being set under:

```
    /* Content Encoding: gzip */
    if (compressed == FLB_TRUE) {
        flb_http_set_content_encoding_gzip(c);
    }
```

I'll close this issue until I validate that the above code is not working.

**Comment by edsiper** [comment]
yup, server must handle the content encoding.
