### ISSUE TITLE
Multiple forward outputs

### ISSUE THREAD

**Issue by martinhynar** [fluent/fluent-bit#305]
I am thinking about having multiple forward outputs to lower pressure on subsequent fluentd agents. It is, the setup would look like this

fluent-bit (e.g. 100 instances)  -> fluentd (e.g. 2 instances) -> some other processing

This means, fluent-bit will have
```
[OUTPUT]
    Name          forward
    Match         *
    Host          fluentd1.example.com
    Port          1234

[OUTPUT]
    Name          forward
    Match         *
    Host          fluentd2.example.com
    Port          1234
```

+ Will this work? Yes, it will send data.
+ Will this work in a load balancing fashion? No, it will send all events to both outputs. Is there a way to change this?

**Comment by edsiper** [comment]
There is an enhancement request to add balancing capabilities: https://github.com/fluent/fluent-bit/issues/203 . No workaround to accomplish balancing at the moment.

Please upvote #203 

Closing this as a dup of #203.

**Comment by dennyzhang** [comment]
@martinhynar When you say it will send data, do you mean 2 output will all get the data, or just the second one? Thanks in advance.

**Comment by martinhynar** [comment]
It is year old stuff but at that time I was considering usage of fluent bit
I was expecting that those 2 outputs will be loadbalanced in some way.
Compare it to Elastic's beat that is able to have e.g. more logstash output
nodes confiured and makes round-robin loadbalalancing between them. The
same applies to beat when it connects to fluentd with beats input, beats
does loadbalancing to multiple targets.
