### ISSUE TITLE
[libco] race condition

### ISSUE THREAD

**Issue by hsmatulisgoogle** [fluent/fluent-bit#3055]
## Bug Report

There seems to be a race condition in libco:
https://github.com/fluent/fluent-bit/blob/56470696968322edae26e63006dc3e60e65b8839/lib/flb_libco/amd64.c#L132-L135
Here `co_swap` is a static function pointer, which is assigned to a bunch of data in `co_swap_function` that corresponds to assembly instructions before first use.

However this code assume that pointer assignment is regular, which is likely platform dependent. Better to use `pthread_once` rather than checking if its `null`.

This code should probably be using inline assembly macros instead of writing data to an `unsigned char` and interpreting it as a function, then they wouldn't have to worry about initializing things before first use in the first place.

**Comment by edsiper** [comment]
I think the libco backend must be updated, there is some modifications in the newer versions:

https://github.com/libretro/RetroArch/blob/master/libretro-common/libco/amd64.c

**Comment by hsmatulisgoogle** [comment]
I don't know where they are getting updates from, as I couldn't find a libco repo to update to. Looks like they are using inline assembly in the following case 
```
#if defined(__GNUC__) && !defined(_WIN32) && !defined(__cplusplus)
#define CO_USE_INLINE_ASM
#endif
```
So if we are on windows, compiling with C++ or don't have GNU extensions we'd still have the race condition. In the remaining cases this updated version doesn't have the race condition

**Comment by edsiper** [comment]
so I see two things to do:

- update libco
- on windows, use maximum 1 worker

**Comment by edsiper** [comment]
issue has been fixed. Now the first initialization of ```co_swap``` is protected

**Comment by edsiper** [comment]
refs:

- b058febaa764bcb6238b560a388803b61f10cbf9
- b48e6583b41c7276096f2506af300882bd4a2476
