### ISSUE TITLE
Getting error "cannot open database /var/log/flb_kube.db"

### ISSUE THREAD

**Issue by rubans** [fluent/fluent-bit#3056]
## Bug Report

**Describe the bug**
I need to be able to run the fluentbit as non-root on kubernetes (GKE). 
I guess this is a pretty normal environment as most clusters should really be locked down against privileged/root containers.
I get errors related to access in the pod logs when running as above.
Not sure if the errors are actual blockers though, as the pod is still running fine. Any ideas how I can confirm everything is ok if I should ignore them?

**To Reproduce**
- Rubular link if applicable:
- https://github.com/fluent/fluent-bit-kubernetes-logging
- When I try and run it with the following security context changes to the daemonset:
- securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

- Example log message if applicable:
```
All I get is the following in the logs:
2021/02/10 20:17:50] [ info] [engine] started (pid=1)
[2021/02/10 20:17:50] [ info] [storage] version=1.0.5, initializing...
[2021/02/10 20:17:50] [ info] [storage] in-memory
[2021/02/10 20:17:50] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/02/10 20:17:50] [error] [sqldb] cannot open database /var/log/flb_kube.db
[2021/02/10 20:17:50] [error] [input:tail:tail.0] could not open/create database
[2021/02/10 20:17:50] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2021/02/10 20:17:50] [ info] [filter:kubernetes:kubernetes.0] local


```
- Steps to reproduce the problem:
- Run daemonset as non-root

**Expected behavior**

**Screenshots**

**Your Environment**
* Version used: GKE v1.18 / fluent-bit v 1.15
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

Pls let me know if more info is required.

**Comment by rubans** [comment]
Anyone? surely this is a common requirement. 
Appreciate some feedback. Let me know if any further info is required.

**Comment by mtparet** [comment]
I have exactly the same issue..

**Comment by wenchajun** [comment]
I have exactly the same issue.

**Comment by wlawton** [comment]
Me too.

**Comment by freesinger** [comment]
I have exactly the same issue..

**Comment by hylowaker** [comment]
Why is this closed? 

The helm chart value has 'securityContext' section, but if I set runAsUser other than 0, it fails to run.
