### ISSUE TITLE
Stack driver output plugin dropping logs

### ISSUE THREAD

**Issue by anishk25** [fluent/fluent-bit#3057]
## Bug Report

**Describe the bug**
I am currently using the stack driver output plugin to send logs to Google Cloud.  We have multiple machines that send logs to Google Cloud (all to one project). For some reason all logs are not making it to google cloud. I have verified this by comparing the number of logs written locally on our linux machines to the number of logs present in Google Cloud for a certain time period.

Logs are produced at a high rate in our application and my initial guess to why this could be happening is that we are hitting the Google Cloud quota limits for logging (https://cloud.google.com/logging/quotas#api-limits). But the limit is on number of writes per minute. In each log write request,  multiple logs can be sent (https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write). The limit is set to 120K writes / minute, but in theory the log rate can be much higher if multiple logs are included in a write request. 

I am wondering if the stackdriver plugin is batching the logs in each write request or is sending one log per write request. 

**Expected behavior**
All logs should be written to Google Cloud

**Your Environment**

* Version used: 1.6.10, (running td-agent-bit on linux)
* Operating System and version:  Ubuntu 16.04.6
* Filters and plugins: stackdriver

**Fluent Bit Config**
```
[SERVICE]
    Flush        10
    Daemon       Off
    Log_File     /var/log/fluent_bit.log
    Log_Level    info
    storage.path    /var/cache/fluent-bit-log-buffer/
    Plugins_File plugins.conf
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    mem_buf_limit 50M
    Parser json_parser
    Name syslog
    Port 520
    storage.type filesystem
    Tag app_logs
    Mode tcp

[OUTPUT]
    Match app_logs
    resource global
    severity_key level
    google_service_credentials /etc/logging/gcp/log_writer_credentials.json
    Name stackdriver
```

**Comment by hsmatulisgoogle** [comment]
Log entries are being batched by the stackdriver plugin. Could you estimate the following:
- How many entries per second are you sending to fluent-bit?
- What is the size of each entry?

**Comment by anishk25** [comment]
@hsmatulisgoogle 
On average each log entry is around 700 bytes. 
Each machine on average is sending 60 logs / second to fluent bit. In total we have 5 machines so that's 300 logs / second in total going to google cloud.

**Comment by hsmatulisgoogle** [comment]
That should be very far away from fluent-bit / API limits, do you have your fluent-bit logs?

**Comment by anishk25** [comment]
No errors reported in the fluent bit logs. I also did a small load test by sending 1200 logs / second for 5 seconds (6000 total). All the logs didn't make it to google cloud. Around 30 logs were dropped.

**Comment by anishk25** [comment]
@hsmatulisgoogle any insight on what could be going wrong?

**Comment by hsmatulisgoogle** [comment]
There is no parameter to specify the batch size. Its not obvious to me whats going, could you upload the following after fluent-bit has dropped some logs:
1. Your fluent-bit logs
2. Turn on the fluent-bit http server and query metrics and storage
   * `curl -s http://127.0.0.1:2020/api/v1/metrics`
   * `curl -s http://127.0.0.1:2020/api/v1/storage`

**Comment by anishk25** [comment]
Here are the logs: [fluent_bit.log](https://github.com/fluent/fluent-bit/files/5991386/fluent_bit.log)
Output of `curl -s http://127.0.0.1:2020/api/v1/metrics`:
```
{
  "input": {
    "syslog.1": {
      "records": 5700,
      "bytes": 1558098
    },
    "storage_backlog.2": {
      "records": 0,
      "bytes": 0
    }
  },
  "output": {
    "stackdriver.0": {
      "proc_records": 5700,
      "proc_bytes": 1558098,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0
    }
  }
}
```

Output of `curl -s http://127.0.0.1:2020/api/v1/storage`:
```
{
  "fluent-bit": {
    "version": "1.6.10",
    "edition": "Community",
    "flags": [
      "FLB_HAVE_PARSER",
      "FLB_HAVE_RECORD_ACCESSOR",
      "FLB_HAVE_STREAM_PROCESSOR",
      "FLB_HAVE_TLS",
      "FLB_HAVE_AWS",
      "FLB_HAVE_SIGNV4",
      "FLB_HAVE_SQLDB",
      "FLB_HAVE_TRACE",
      "FLB_HAVE_METRICS",
      "FLB_HAVE_HTTP_SERVER",
      "FLB_HAVE_SYSTEMD",
      "FLB_HAVE_VALGRIND",
      "FLB_HAVE_FORK",
      "FLB_HAVE_GMTOFF",
      "FLB_HAVE_UNIX_SOCKET",
      "FLB_IS_TD_AGENT",
      "FLB_HAVE_PROXY_GO",
      "FLB_HAVE_JEMALLOC",
      "FLB_HAVE_LIBBACKTRACE",
      "FLB_HAVE_REGEX",
      "FLB_HAVE_UTF8_ENCODER",
      "FLB_HAVE_LUAJIT",
      "FLB_HAVE_C_TLS",
      "FLB_HAVE_ACCEPT4",
      "FLB_HAVE_INOTIFY"
    ]
  }
}
```

The number of records sent to google cloud should have been 6000 but the metrics show that only 5700 were actually processed.

**Comment by hsmatulisgoogle** [comment]
Hmm thats really weird. Looks like it might be an issue with the syslog input plugin. Do you have this issue with any other input plugin? Is there any pattern to the logs being dropped (eg. first 300 are dropped, last 300, its random etc)

**Comment by anishk25** [comment]
There was an issue with the rsyslog service. All the logs were not being forwarded to fluent bit and logs were getting dropped. Now its able to send all the logs.
