### ISSUE TITLE
Single quoted characters for json not parsed

### ISSUE THREAD

**Issue by Padarn** [fluent/fluent-bit#3070]
## Bug Report

Sorry this probably isn't a bug, but I'm not sure if this is someone that should be possible with fluentbit or not.

**Describe the bug**
I would like to be able to parse logs like:
```
{'test':'dog'}
```
unfortunately, it seems that this is parsed to
``` 
 {"log"=>"{'test':'dog'}"}]
```

**To Reproduce**

Steps to reproduce the problem:
- start fluent-bit docker container with below config 
- write log above to file watched

`fluent-bit.conf`:
```
[SERVICE]
    Flush         1
    Log_Level     trace
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Tag                *
    Path              /log/*.log
    Parser            docker

[OUTPUT]
    Name            stdout
    Match           *
```

`parsers.conf`:
```
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
```

**Expected behavior**
Log parsed as ```{"test"=>"dog"}```

**Your Environment**

* Version used: 1.6
* Configuration: given above
* Environment name and version (e.g. Kubernetes? What version?): docker on osx

**Comment by nokute78** [comment]
`"` is defined as quotation-mark refer to [RFC7159](https://tools.ietf.org/html/rfc7159#section-7).  `'` is not.
Could you replace `'` -> `"` ?

Then, the filter parser plugin helps your use case.
https://docs.fluentbit.io/manual/pipeline/filters/parser

```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.7.0
(snip)
[0] tail.0: [1613171828.865883679, {"test"=>"dog"}]
```


a.conf:
```
[SERVICE]
    Flush         1
    Log_Level     trace
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              ./*.log

[FILTER]
    Name          parser
    Match         *
    Parser        sample
    Key_name      log

[OUTPUT]
    Name            stdout
    Match           *
```

parsers.conf:
```
[PARSER]
    Name         sample
    Format       json
```

**Comment by Padarn** [comment]
You're right on both counts. Thanks @nokute78. We will just fix the output format of our logs.
