### ISSUE TITLE
Out-of-bounds write caused by incorrect error handling of flb_malloc in cb_throttle_init (throttle.c:203)

### ISSUE THREAD

**Issue by cve-reporting** [fluent/fluent-bit#3075]
## Bug Report

Fluent Bit Throttle filter is vulnerable to OOB write attack while initialization of the filter.

Incorrect handling of the value returned by flb_malloc (malloc wrapper) in cb_throttle_init may lead to:
- out-of-bound write attempt and segmentation fault error in case of restrictive memory protection,
- near NULL out-of-bound overwrite in case of limited memory restrictions (e.g. in embedded environments).

Vulnerable code (plugins/filter_throttle/throttle.c):

	203:    ticker_ctx = flb_malloc(sizeof(struct ticker));
	204:    ticker_ctx->ctx = ctx;
	205:    ticker_ctx->done = false;
	206:    ticker_ctx->seconds = parse_duration(ctx, ctx->slide_interval);

**To Reproduce**

The issue can be reproduced and tested using ErrorSanitizer (https://gitlab.com/ErrorSanitizer/ErrorSanitizer).

Reproduction steps:

0. Install gdb

1. Download and unpack code of ErrorSanitizer (https://gitlab.com/ErrorSanitizer/ErrorSanitizer)

2. Perform compilation of ErrorSanitizer according to the manual (https://gitlab.com/ErrorSanitizer/ErrorSanitizer#compilation)

	cd ErrorSanitizer; make

3. Set ESAN to the path of ErrorSanitizer directory

	export ESAN=/opt/...

4. Download and unzip attached map temp_141.cur_input
[temp_141.cur_input.zip](https://github.com/fluent/fluent-bit/files/5977343/temp_141.cur_input.zip)

5. Run fluent-bit with ErrorSanitizer in gdb using:

gdb -batch -ex='run' -ex='backtrace' -ex='backtrace full' --args env LD_PRELOAD="$ESAN/error_sanitizer_preload.so" ./fluent-bit/build/bin/fluent-bit -i cpu -f 1 -F throttle -p 'rate=1' -m '*' -o stdout temp_141.cur_input 

You should receive similar output:

	process 7397 is executing new program: fluent-bit/build/bin/fluent-bit
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
	Fluent Bit v1.7.0
	* Copyright (C) 2019-2020 The Fluent Bit Authors
	* Copyright (C) 2015-2018 Treasure Data
	* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
	* https://fluentbit.io

	[New Thread 0x7ffff5763700 (LWP 7402)]
	[New Thread 0x7ffff4f62700 (LWP 7403)]
	[2021/02/13 18:46:32] [ info] [engine] started (pid=7397)
	[2021/02/13 18:46:32] [ info] [storage] version=1.1.0, initializing...
	[2021/02/13 18:46:32] [ info] [storage] in-memory
	[2021/02/13 18:46:32] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128

	Thread 2 "flb-pipeline" received signal SIGSEGV, Segmentation fault.
	[Switching to Thread 0x7ffff5763700 (LWP 7402)]
	0x0000555555697755 in cb_throttle_init (f_ins=0x555555c14cc0, config=0x555555c193c0, data=0x0) at fluent-bit/plugins/filter_throttle/throttle.c:204
	204	    ticker_ctx->ctx = ctx;
	#0  0x0000555555697755 in cb_throttle_init (f_ins=0x555555c14cc0, config=0x555555c193c0, data=0x0) at fluent-bit/plugins/filter_throttle/throttle.c:204
	#1  0x00005555555ba03c in flb_filter_init_all (config=0x555555c193c0) at fluent-bit/src/flb_filter.c:431
	#2  0x00005555555c9fbf in flb_engine_start (config=0x555555c193c0) at fluent-bit/src/flb_engine.c:507
	#3  0x00005555555ad7ea in flb_lib_worker (data=0x555555c13980) at fluent-bit/src/flb_lib.c:493
	#4  0x00007ffff79946db in start_thread (arg=0x7ffff5763700) at pthread_create.c:463
	#5  0x00007ffff67aba3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
	#0  0x0000555555697755 in cb_throttle_init (f_ins=0x555555c14cc0, config=0x555555c193c0, data=0x0) at fluent-bit/plugins/filter_throttle/throttle.c:204
		ret = 0
		tid = 93824995908634
		ticker_ctx = 0x0
		ctx = 0x7ffff0004750
	#1  0x00005555555ba03c in flb_filter_init_all (config=0x555555c193c0) at fluent-bit/src/flb_filter.c:431
		ret = 32767
		name = 0x555555c14cc8 "throttle.0"
		tmp = 0x555555c19550
		head = 0x555555c14d30
		config_map = 0x555555c100a0
		p = 0x555555c0e410
		ins = 0x555555c14cc0
	#2  0x00005555555c9fbf in flb_engine_start (config=0x555555c193c0) at fluent-bit/src/flb_engine.c:507
		ret = 0
		tmp = "24.0K\000\000\000;\364\214UUU\000"
		t_flush = {tm = {tv_sec = 0, tv_nsec = 0}}
		event = 0x0
		evl = 0x7ffff00015c0
		sched = 0x0
	#3  0x00005555555ad7ea in flb_lib_worker (data=0x555555c13980) at fluent-bit/src/flb_lib.c:493
		ret = 0
		ctx = 0x555555c13980
		config = 0x555555c193c0
	#4  0x00007ffff79946db in start_thread (arg=0x7ffff5763700) at pthread_create.c:463
		pd = 0x7ffff5763700
		now = <optimized out>
		unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737311553280, -1406562917378786864, 140737311550720, 0, 93824999307648, 140737488346432, 1406539902247926224, 1406545061883312592}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
		not_first_call = <optimized out>
	#5  0x00007ffff67aba3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
	No locals.

**Expected behavior**

See following recommendations for details (especially the calloc example):
https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors

**Your Environment**
Current master branch of https://github.com/fluent/fluent-bit

**Additional context**

**Comment by edsiper** [comment]
fixed in c7769903 , thanks
