### ISSUE TITLE
in_cpu or in_head: add cpu temperature?

### ISSUE THREAD

**Issue by mahdi-asadpour-rr** [fluent/fluent-bit#308]
CPU temperature is reported in "/sys/class/thermal/thermal_zone0/temp" (Linux), which is an important metric to monitor in embedded systems. Would it be possible to include this somehow?

- include temperature in the in_cpu, OR

- it's actually possible to use in_head on this file, but the read value is outputted as **"string" and not "number"**, which makes it not usable to visualize in Kibana when output_es is used.

Thanks.

**Comment by edsiper** [comment]
Actually reading from a file will be considered as a string. No workaround at the moment but I will flag this issue as an enhancement request to see how this can be accomplished in the future.

**Comment by edsiper** [comment]
@nokute78 what about an option on in_head to force a atoll() over the read data ?

**Comment by nokute78** [comment]
@edsiper In my opinion, it will be nice to support "types" feature of parser like fluentd.

Because type casting is helpful for not only in_head but also other input plugins.

**Comment by edsiper** [comment]
@nokute78 so for Parsers context it would be to add a new format(ter) backend-type, e.g:

- Regex
- JSON
- Number (handle integer and double)

**Comment by nokute78** [comment]
I pushed #310 to update parser.

@edsiper It is different from parser of fluentd.
Could you check this?
http://docs.fluentd.org/v0.12/articles/parser_regexp#types

**Comment by mahdi-asadpour-rr** [comment]
@nokute78 I can confirm that #310 -- adding types -- solves the issue/feature mentioned here.

**Comment by nokute78** [comment]
@mahdi-asadpour-rr
Thank you for reporting.

@edsiper Could you review #310 ?

**Comment by edsiper** [comment]
@nokute78 sure, shortly (~tomorrow)

**Comment by edsiper** [comment]
thanks!, merged.

fixed.
