### ISSUE TITLE
Default cri parser does not output time field due to missing Time_Keep parameter

### ISSUE THREAD

**Issue by sibradzic** [fluent/fluent-bit#3085]
## Bug Report

**Describe the bug**
The default parsers.conf **cri** parser is missing `Time_Keep` setting.

**To Reproduce**
Run fluent-bit that parses logs produced by cri (containerd).

**Your Environment**

* Version used: 1.6.10-debug
* Configuration:
```
[SERVICE]
    Flush        1
    Grace        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    Coro_Stack_Size    24576
    storage.path  /buffers
[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    Mem_Buf_Limit  5MB
    Parser  cri
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  On
    Tag  kubernetes.*
[FILTER]
    Name        kubernetes
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Tag_Prefix  kubernetes.var.log.containers
    Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_URL  https://kubernetes.default.svc:443
    Match  kubernetes.*
    Merge_Log  On
[OUTPUT]
    Name          forward
    Match         *
    Host          rancher-logging-fluentd.cattle-logging-system.svc
    Port          24240
    Retry_Limit  False
```
* Environment name and version: Azure AKS k8s v19.6
* Server type and version: Azure VM
* Operating System and version: Ubuntu 18.04.5 LTS
* Filters and plugins: none

**Additional context**
Analysed fluent-bit raw output with tcpdump. Without `Time_Keep On` the `time` tag is missing completely. With `Time_Keep On` the `time` tag is present in the raw output.

This only affects **cri** parser, and although it is easily fixable by adding the parameter to the parsers.conf, the way the fluent-bit is "distributed" by the common logging operators the default config is impossible to change without generating and using customized fluent-bit images.

**Comment by sibradzic** [comment]
```
diff --git a/conf/parsers.conf b/conf/parsers.conf
index 77f61ce0..06fce363 100644
--- a/conf/parsers.conf
+++ b/conf/parsers.conf
@@ -109,6 +109,7 @@
     Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
     Time_Key    time
     Time_Format %Y-%m-%dT%H:%M:%S.%L%z
+    Time_Keep   On
 
 [PARSER]
     Name    kube-custom
```

**Comment by sibradzic** [comment]
Does fluent-bit allow community PRs?

**Comment by agup006** [comment]
> Does fluent-bit allow community PRs?

Yes , definitely

**Comment by donbowman** [comment]
https://github.com/microsoft/fluentbit-containerd-cri-o-json-log
is also needed i think

**Comment by sibradzic** [comment]
> https://github.com/microsoft/fluentbit-containerd-cri-o-json-log
> is also needed i think

Thanks for the hint, seems that Microsoft was facing similar issues. The Microsoft issue is more about aligning the output format to the docker parser output. Yet this issue is solely about missing `time` in the fluent-bit cri parser output.

**Comment by toabi** [comment]
This is still an open bug!

**Comment by icelynjennings** [comment]
This needs reopening

**Comment by idrissneumann** [comment]
> This needs reopening

And this pr should be considered as the right fix: https://github.com/fluent/fluent-bit/pull/4133

**Comment by Drupi** [comment]
Any updates on that?
