### ISSUE TITLE
Fluent bit stops sending logs to Loki when any of the outputs goes offline

### ISSUE THREAD

**Issue by annie1404** [fluent/fluent-bit#3088]
## Bug Report

**Describe the bug**
When any one of the Elastic search output plugins goes offline there are no more logs available to query from the Loki instance (running in the container)
When the offline output plugin is commented and restart fluent bit, the logs are resumed to be generated

**To Reproduce**
- Use a similar configuration as below
- For a few minutes initially some logs are produced after which within 20 -30 mins no more new logs are seen.

```
[SERVICE]
    Flush 5
    Daemon Off
    Log_Level info
    Parsers_File parsers-eos.conf
    Plugins_File plugins.conf

    HTTP_Server Off
    HTTP_Listen 0.0.0.0
    HTTP_Port   2020

[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224
    Chunk_Size  32
    Buffer_Size 64

[INPUT]
    Name              systemd
    Path              /run/log/journal/
    Read_From_Tail    On 
    Strip_Underscores On
    Mem_Buf_Limit     10MB
    Tag journal

[OUTPUT]
    name            loki
    match           *
    host            localhost
    port            3100
    labels          job=fluentbit

# Elasticsearch running on Azure
[OUTPUT]
    Name  es
    Match *
    Host  ..cloudapp.azure.com
    Port  9200
    Type  docker
    Logstash_Format On
    Time_Key        @fbTimestamp
    Trace_Output  Off
    Trace_Error   On

# Elasticsearch running on local machine
[OUTPUT]
    Name  es
    Match *
    Host  192.168.1.1
    Port  9200
    Type  docker
    Logstash_Format On
    Time_Key        @fbTimestamp
    Retry_Limit     1
```
**Expected behavior**
No stoppage of the logs to the connected loki output

**Your Environment**
* Version used: Fluent Bit v1.6.9 , /grafana-loki:2.1.0
* Operating System and version: Linux aarch64

**Comment by giovanni-ferrari** [comment]
Same issue here. 
I prepared a small docker-compose to replicate the issue. In case the connection to ES is lost (in my test, stopping the EG container) then fluent-bit stops forwarding logs to loki. 

What's the relation between these two plugins? 
Why stdout output plugin keeps showing logs? 

Fluent-bit-config.yaml
`[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush 5

    Daemon Off

   
    Log_Level info

        # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server Off
    HTTP_Listen 0.0.0.0
    HTTP_Port   2020

[INPUT]
    Name        tail
    Path        /var/log/test.log

[OUTPUT]
    name            loki
    match           *
    host            loki
    port            3100
    labels          job=fluentbit

[OUTPUT]
    name            stdout
    match           *

[OUTPUT]
    Name es
    match *
    Host elasticsearch
    Port 9200
    Replace_Dots On
    Trace_Output  On
    Retry_Limit     1`

**Comment by giovanni-ferrari** [comment]
Hello everyone, 
same problem here. 
I have prepared the configuration file you can see here below. 
When the connection to elasticsearch is lost then the STDOUT plugin keeps working and showing logs, but the loki one stops forwarding logs to loki.

`[SERVICE]
    # Flush
    # =====
    # Set an interval of seconds before to flush records to a destination
    Flush 5

    Daemon Off

    Log_Level info

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    HTTP_Server Off
    HTTP_Listen 0.0.0.0
    HTTP_Port   2020

[INPUT]
    Name        tail
    Path        /var/log/test.log

[OUTPUT]
    name            loki
    match           *
    host            loki
    port            3100
    labels          job=fluentbit

[OUTPUT]
    name            stdout
    match           *

[OUTPUT]
    Name es
    match *
    Host elasticsearch
    Port 9200
    Replace_Dots On
    Trace_Output  On
    Retry_Limit     1`

**Comment by giovanni-ferrari** [comment]
still interested in this issue

**Comment by giovanni-ferrari** [comment]
Keeping this up because the issue is still present

**Comment by giovanni-ferrari** [comment]
Still interested in this issue

**Comment by kishaningithub** [comment]
The same issue occurs in v1.8.1 as well

**Comment by diegoaguilar** [comment]
@kishaningithub did you figure this out?

**Comment by sigfridh** [comment]
same issue in v1.8.10

**Comment by synchris** [comment]
I second this; experiencing the same issue with Loki.

**Comment by korenlev** [comment]
Same here

**Comment by leonardo-albertovich** [comment]
Could you please test this on 1.8.15 or 1.9.2?

**Comment by Cerebus** [comment]
This looks similar to #3328, and I'm seeing it on 1.9.3 as well.  See this comment: https://github.com/fluent/fluent-bit/issues/3328#issuecomment-1115238211

I think what happens is the loki plugin is returning an unrecoverable error, which is why the retry logic doesn't fire.

**Comment by lecaros** [comment]
Hello everyone,
does any of you have a repro for this using the latest versions? (either 1.8.15 or 1.9.3)

**Comment by edepremare-cs** [comment]
Hello,
I am running fluent-bit 1.9.3 and loki 2.5.0, and still have this issue. Sometimes, because of an internal error, Loki sends an error 500: 
`[2022/05/23 11:36:07] [error] [output:loki:loki.0] loki-distributor.logging.svc.cluster.local:3100, HTTP status=500`
The loki output then stops working and never restarts...

**Comment by lecaros** [comment]
Hi @edepremare-cs
Can you share your configuration?
Does this occur upon error 500 only? Does it happen when Loki goes offline?

**Comment by edepremare-cs** [comment]
Here is my fluent-bit conf: 
``` 
[INPUT]
  Name             tail
  Multiline.parser cri
  Tag              processing.log.*
  Path             /var/log/containers/*.log
  DB               /var/log/fluentbit_processing_log.db
  DB.Sync          Normal
  Rotate_Wait      10
  Buffer_Max_Size  1MB
  Mem_Buf_Limit    50MB
  storage.type     filesystem
[...]
[OUTPUT]
  Name loki
  Match processing.log.*
  Labels log_type=container,pod=$pod_name,namespace=$namespace_name,node=$host,container=$container_name,container_image=$container_image
  Host loki-distributor.logging.svc.cluster.local
  Remove_keys container_hash,container_image,container_name,docker_id,host,namespace_name,pod_id,pod_name,pod_name
  Drop_single_key true
  Line_format key_value
  Retry_Limit     4
  Port 3100
```
The error 500 happens somewhat randomly (probably linked to https://github.com/grafana/loki/issues/6227) and makes the output stop permanently.
If if delete the loki service for a few minutes, fluent-bit throws: 
```
[ warn] [engine] failed to flush chunk '1-1653901354.863465632.flb', retry in 11 seconds: task_id=27, input=tail.0 > output=loki.0 (out_id=0)                                                                      │
[error] [output:loki:loki.0] loki-distributor.logging.svc.cluster.local:3100, HTTP status=504 
[error] [output:loki:loki.1] no upstream connections available
``` 
and the plugin does not recover.
Errors 400 also happens for different reasons but the loki output plugins recovers afterwards.

**Comment by ebarped** [comment]
Hi, still happenning with fluent-bit 1.9.5 and loki 2.5.0.

Config:
```
    [OUTPUT]
        name                   loki
        match                  *
        labels                 namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],app=$kubernetes['labels']['k8s-app'] 
        Host                   loki
        Port                   3100
        auto_kubernetes_labels Off
        net.connect_timeout    120
```

**Comment by sigfridh** [comment]
Hi, still happenning with fluent-bit 1.9.9 and loki 2.6.1.

**Comment by sigfridh** [comment]
> Hi, still happenning with fluent-bit 1.9.9 and loki 2.6.1.

**Comment by sigfridh** [comment]
Actually not, its working, nothing to do with the exponenetial retry strategy values but after a moment it reconnect successfully
