### ISSUE TITLE
TCP SYN flood circuit breaker

### ISSUE THREAD

**Issue by kabakaev** [fluent/fluent-bit#3103]
We send logs from hundreds of servers into a central location via `out_forward`. Everything works as expected, thanks to `net.keepalive`.

But if the receiving side is down, then the log shippers start sending thousands of TCP SYN packets, which creates considerable load on stateful firewalls and TLS proxy. Our network team is unhappy about it.

Frequency of SYN packets varies depending on Retry_Limit, Mem_Buf_Limit and the inflow of logs from disk.

It seems, the `out_forward` plugin tries to connect to the remote host on each retry of each chunk.

**Solution**

I would like to have some sort of circuit breaker, which should disable an output (or a `node` in the `upstream` list) whenever the upstream connection cannot be established at least `X` times in the last `Y` seconds.

Then, as soon as circuit breaker is triggered, it should initiate only one connection request per `Z` seconds to test if the upstream is up again.

**Steps to reproduce**

In first terminal, run `fluent-bit` container for 60 seconds with output plugin pointing to a closed port at localhost:
```bash
docker run  --rm -ti fluent/fluent-bit:1.7-debug timeout -s SIGQUIT 60s  /fluent-bit/bin/fluent-bit -i dummy -p 'rate=1000000' -o forward://172.17.0.1:24284 -p 'retry_limit=1'
```

On another terminal, see that the container sends 536 SYN packets in 1 minute:
```bash
tcpdump -lnn -i docker0 dst host 172.17.0.1 and dst port 24284
# 16:48:46.499293 IP 172.17.0.2.56228 > 172.17.0.1.24284: Flags [S], seq 2898211674, win 64240, options [mss 1460,sackOK,TS val 21057999 ecr 0,nop,wscale 7], length 0
#...
# 536 packets captured
# 560 packets received by filter
```

**Comment by edsiper** [comment]
wip

**Comment by edsiper** [comment]
bump
