### ISSUE TITLE
Msg timestamp OutOfRange in out_flowcounter

### ISSUE THREAD

**Issue by FUSAKLA** [fluent/fluent-bit#311]
Hi, we encouraged problem with the time precision change in `out_flowcounter`. 

With forward from `fluentd v0.14.13` 
```html
<match **>
  @type forward
  buffer_type file
  buffer_path /www/fluentd/buffers*
  buffer_chunk_limit 8m
  buffer_queue_limit 2048
  flush_interval 10s
  retry_wait 20s
  retry_limit 30
  max_retry_wait 120s
  send_timeout 120s
  recover_wait 5s
  time_as_integer true
  require_ack_response true
  ack_response_timeout 190
  <server>
    name fluent-bit
    host fluent-bit.logs
    port 24224
  </server>
</match>
```

to `fluentbit v.0.11.11` with config
```yaml
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Log_File     /dev/stdout

[INPUT]
    Name        forward
    Listen      0.0.0.0
    Port        24224
    Chunk_Size  8096
    Buffer_Size 80960

[OUTPUT]
    Name es
    Match *
    Host elasticsearch.logs
    Port 9200
    Logstash_Format On
    Logstash_DateFormat %Y.%m.%d
    Time_Key _flb_time
    Time_Key_Format %Y-%m-%dT%H:%M:%S
    Include_Tag_Key On
    Tag_Key tag
    Type fluentd

 [OUTPUT]
     Name flowcounter
     Match *
     Unit second
```
both running in docker in kubernetes. 

If `time_as_integer` is set to `false` in fluentd forward we get on stdout dozens of same messages messages
```
[out_flowcounter] [1498655312, {"counts":0, "bytes":0, "counts/second":0, "bytes/second":0 }]
```

It never counts any data. That is IMHO caused by the malformed timestamp (we already troubleshooted issue with the `time_as_integer` and without it fluentbit interpreted timestamp from fluentd as from year 3072 or st like that) thus those messages doesn't fit to any buckets and therefore no flow is observed. 

If we set `time_as_integer` to `true` the timespamps are ok but we get on stdout dozens of messages like this
```
[2017/06/28 10:02:02] [ warn] [out_flowcounter] Out of range. Skip the record.                                         
```
I'm not sure if `out_flowcounter` is already prepared for the `fluentd` time change
I found this issue https://github.com/fluent/fluent-bit/issues/193

where is referenced commit https://github.com/fluent/fluent-bit/commit/fc36996ca345335662bc3646a1b94ae38347d452

which should probably fix it and is already in master and in `0.11.11` version which we are now trying but problem remains. 

Another related commit might be https://github.com/fluent/fluent-bit/commit/a62372d268f453c0288f8f6223f343ec219dc05e
but i don't have the insight to tell.

**Comment by FUSAKLA** [comment]
@FuFikCZ You might be interested.

**Comment by edsiper** [comment]
cc: @nokute78

**Comment by nokute78** [comment]
I pushed #314 to fix this issue.

**Comment by FUSAKLA** [comment]
Great thanks a lot!
I'll test it asap.
