### ISSUE TITLE
HTTP status code 413 - Payload Too Large

### ISSUE THREAD

**Issue by rubans** [fluent/fluent-bit#3123]
I'm getting Http Status 413 - Request payload messages in fluentbit pod logs which presumably is related to ElasticSearch HTTPS connection.
The ES output connection is over HTTPS and seems to be working in principle but wanted to fix this warning.
I have modified HTTP content size on ES to 500mb but still getting the warnings on fluentbit.
The warning refers to chunking of a *.flb file which I can't find on the Host Node so any help would be appreciated.
Let me know if further info is required.

**Comment by vakaobr** [comment]
@rubans are you able to fix it ? having the same issue
