### ISSUE TITLE
http: panic serving 127.0.0.1:60276: interface conversion: interface {} is uint8, not map[interface {}]interface {}

### ISSUE THREAD

**Issue by ewirch** [fluent/fluent-bit#3127]
## Bug Report

**Describe the bug**
We found the above message in our logs. Here's the stack trace:
```
goroutine 2594159 [running]:
net/http.(*conn).serve.func1(0xc000b546e0)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0xff1f00, 0xc0009db980)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
main.GetRecord(0xc000390d20, 0x0, 0x2c42e6ae, 0xed7c8f713, 0x1967000, 0xc0009db950)
	/go/src/gke-logmon/fluent-bit/decoder.go:80 +0x2a5
main.HandleLogs.func1(0x12c0e80, 0xc0000f7ce0, 0xc0001ba600)
	/go/src/gke-logmon/fluent-bit/server.go:75 +0x1ab
net/http.HandlerFunc.ServeHTTP(0xc000433760, 0x12c0e80, 0xc0000f7ce0, 0xc0001ba600)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x1966be0, 0x12c0e80, 0xc0000f7ce0, 0xc0001ba600)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0000f61c0, 0x12c0e80, 0xc0000f7ce0, 0xc0001ba600)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000b546e0, 0x12c3900, 0xc00074aa40)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```

**Your Environment**

* Version used: `gke.gcr.io/fluent-bit:v1.3.11-gke.0`
* Environment name and version (e.g. Kubernetes? What version?): Google Cloud Kubernetes 1.18.15-gke.800

**Comment by bpg130** [comment]
We are seeing the same errors coming from containers running the following image
`gke.gcr.io/fluent-bit-gke-exporter:v0.14.2-gke.0` 
on the following kubernetes version
`1.19.7-gke.1302`.

It appears to be causing certain log messages to not show up in GCP log explorer.

**Comment by nokute78** [comment]
It is a golang backtrace and fluent-bit is written in C.
It may be a GKE specific issue.

Similar situation is #2956 .
Could you ask Google Team like that issue ?

**Comment by ewirch** [comment]
Thanks for the hint. I reported the issue here: https://issuetracker.google.com/issues/181493710
