### ISSUE TITLE
fluent-bit log level warn not respected

### ISSUE THREAD

**Issue by agup006** [fluent/fluent-bit#3128]
## Bug Report

**Describe the bug**

Setting `Log_Level warn` does not work, but using `warning` does.

**To Reproduce**
Set `Log_Level warn` in SERVICE block

**Expected behavior**

`Log_Level warn` should only print out warning and error

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by agup006** [comment]
https://github.com/fluent/fluent-bit-docs/issues/451

**Comment by a-thaler** [comment]
Relates to https://github.com/fluent/fluent-bit/issues/2492
The described behaviour I found on version 1.5.7

**Comment by nokute78** [comment]
An example such log is
```
[2021/03/03 17:44:09] [ info] [input] pausing cpu.0
```
Signal handler outputs it when Ctrl+C is pressed.

The log level configuration is saved on thread local storage (flb_worker_ctx), but it may not be initialized on signal handler.
If it is not initialized, the log level is default level (=info). So the log is not suppressed.
