### ISSUE TITLE
[Windows] Elastic Output Plugin stalling for several minutes for 2GB dataset

### ISSUE THREAD

**Issue by simonvanbernem** [fluent/fluent-bit#3129]
First of all: Sorry for not going through the slack-channel first, as recommended, but I simply could not get it to work. It says channel not found, and if I try to create an account, it wants me to have an email from the @linuxfoundation domain, which I don't have...? So a github issue will have to do.

I am testing fluent-bit for use at my company at the moment. Our usage scenario are large sets of json-logs (up to 100GB) that need to be uploaded to an elastic cluster in the shortest time possible. The performance focus of fluent-bit seemed promissing for this usecase, but upon testing, I found a couple of performance issues that led me to believe the elastic plugin wasn't thoroughly with datasets of more than a gigabyte(?). The situation looks like this:

On Windows, for a dataset of 2GB of json-logs, input with tails, I could identify two bottlenecks in the elastic plugin, that severely hamper performance. **fluent-bit will start to consume a lot of memory and then stall for multiple minutes or crash. No data is leaving fluent-bit in the first 5 minutes at all.**

Before I go into the details, here is my configuration:

```
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on
 
[INPUT]
    name tail
    Path O:\log_folder\*.json
    Read_From_Head On
    Mem_Buf_Limit 1g
 
[OUTPUT]
    name es
    match *
    host 127.0.0.1
    index fluentd-test-index
```

I used yesterdays state of the masters branch on Windows10 64bit, built with Visual Studio 2019. The latest binary release for windows has the same issues.

The first bottleneck is `es_bulk_append`. This function reallocs every time it runs out of memory for the bulk-buffer. This happens in a linear fashion: `new_size = bulk->size + available + required + ES_BULK_CHUNK`. Realloc completely dominates the performance in my usecase, the profiler reveals that >80% of the entire time is spent in this realloc-call. **I propose as a fix to make the buffer size grow exponentially.** A change like this worked great for me: `new_size = 2 * bulk->size + required + ES_BULK_CHUNK`.

Since exponential growth is usually the default in dynamic arrays, I suspect that the linear growth here was chosen deliberately to reduce memory waste. If that is that case, and you have concerns about exponential growth making it worse, I propose to either have a lower exponential factor than 2, or to clamp the growth with a configurable upper limit, that a person in my usecase could increase. I personally don't think any of this would be necessary, since small workloads won't go far into the exponential growth anyway, but I thought I'd mention it.

With this change, and another configuration change, which prevented back-pressure from tails to completely overwhelm the elastic plugin, the logs are reaching elastic, but not very fast, and not even in full.

I suspect the bad performance to be caused by huge bulk-sizes: Elastic is quite sensitive (>3x perf. diff.) to the number of docs in a single bulk.  Our cluster likes around 3000, but the elastic plugin seemed to be somewhere around 27000. **I propose to add a new parameter Max_Bulk_Size that lets the user configure an upper bound for the number of documents in a single bulk request.** Code-wise, as far as I can tell, this would only need some changes in `cb_es_flush` and `elasticsearch_format`. Basically putting the entire conversion and http logic in a while loop, and limiting the number of `msgpack_unpack_next` that are made.

I have currently no idea why not all logs are making it to elastic, that should never happen period, but 27000 docs per bulk is an extreme case, so maybe that will also go away with 3000 docs per request.

I didn't make a pull request for either of these changes because I am new to fluent-bit and didn't dive into your procedures yet. Also, there are probably more qualified people to do this. But if it is wanted, a pull request certainly is an option.

**Comment by simonvanbernem** [comment]
I just realized there is a bug template, that I somehow couldn't chose when creating the issue. Sorry for that, I hope its not a problem, I basically did all the debugging myself already :D

**Comment by edsiper** [comment]
@simonvanbernem no worries, so the ticket can be closed ?

I got interested in how to optimize for the realloc() scenario. Every flush callback payload is about 2MB, so maybe we can make a better job to reduce memory reallocations

**Comment by simonvanbernem** [comment]
@edsiper I mean - if there is no fix in the repo yet the bug is not fixed right? Or did someone already commit one? I don't know if you handle it differently with this project, but usually an issue is only closed when the bugfix was successfully merged into master. So if there is no bugfix yet then I wouldn't close the ticket.

Also: how do we go from here? Is there some maintainer for the elastic plugin that is willing to fix this, or should I provide pull-requests? I am a bit confused right now tbh.

**Comment by edsiper** [comment]
In the ticket I see 2 things mentioned:

- Bottleneck: on heavy load, realloc(2) is slowing down things, so a better memory allocation strategy will solve it.

- Crash: how the crash can be reproduced locally ? did you get any stacktrace when this happened ? (did the crash happens only on Windows or Linux too?)

**Comment by simonvanbernem** [comment]
I should have been clearer there: I only saw crashes when running the program in a local debugger, so I suspect some weird interactions going on there that probably wont reproduce. So forget the crash, it didn't happen with the unmodified binary distribution, it shouldn't be a problem.

The two things that actually need fixing are:
- A better allocation strategy for the elastic plugin to avaoid realloc(2) calls. (like you said)
- A new configuration parameter Max_Bulk_Size that controls the maximum number of messages the elastic plugin sends in a single bulk request to elastic.

**Comment by simonvanbernem** [comment]
Why is there still the waiting-for-user label on this issue? I think I provided all the information necessary for a fix.

**Comment by MPeli** [comment]
Hi, I have a very similar problem. I have got hundreds of files in a folder and I am trying to push them to ElasticSearch. Fluent bit crashes very soon after it starts. I am able to reproduce the issue.

[sos-report-and-log.log](https://github.com/fluent/fluent-bit/files/6067399/sos-report-and-log.log)
[fluent-bit-winDbg.dml.txt](https://github.com/fluent/fluent-bit/files/6067400/fluent-bit-winDbg.dml.txt)

**Comment by simonvanbernem** [comment]
Thank you bot, but I am still planning on providing a repro once I get to it :D
