### ISSUE TITLE
Cannot build version past v1.5.6 using yocto

### ISSUE THREAD

**Issue by Epictek** [fluent/fluent-bit#3133]
## Bug Report

**Describe the bug**
Cannot build any version of fluent-bit past v1.5.6 (tried v1.5.7, v1.6.10, v1.7.0 v1.7.1), I am targeting the raspberrypi4.

**To Reproduce**
- Steps to reproduce the problem:
git clone https://github.com/Epictek/fluent-test
./build.sh

make logs:
https://gist.github.com/Epictek/dc55afd856c07ecd9b7e3f4c1d5c30c4

**Comment by gravufo** [comment]
I have the same issue. Did you manage to get it working @Epictek ?

**Comment by Epictek** [comment]
No I did not :( @gravufo

**Comment by gravufo** [comment]
damn :(
Thanks for the fast reply anyway!
