### ISSUE TITLE
Current loki plugin option provides two attributes: host and port. I can not establish fluentbit stream to loki K8s pod by using proxy LB. FluentD loki plugin provides only one attribute URL that easily allow to establish stream from remote fluentbit to loki on k8s

### ISSUE THREAD

**Issue by pakita** [fluent/fluent-bit#3167]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pakita** [comment]
example below is belong to fluentd and it works because uses url entry only ( end point is aws k8s  loki LB) 
<match fluentbitwin.**>
  @type copy
  <store>
    @type file
    @id fluentbitwin_output_file
    path /var/log/td-agent/fluentbitwin
    compress gzip
  </store>
  <store>
  @type loki
  url "https://internal-XXX-observabilit-XXX-XXX.us-east-1.XXX.amazonaws.com"
  insecure_tls true
  extra_labels {"source":"xxx.xxx.xxx"}
  flush_interval 60s
  flush_at_shutdown true
  buffer_chunk_limit 1m
  </store>
</match>

**Comment by pakita** [comment]
Example below for fluent bit does not work:
[OUTPUT]
       Name   loki
       Match  *       
       host  "https://internal-XXX-observabilit-XXX-XXX.us-east-1.XXX.amazonaws.com"
       port 3100	   
       labels job=fluentbit
       line_format json

**Comment by edsiper** [comment]
when you mention a proxy load balancer, are you referring to a DNS balancer ?

note: please use a shorter subject for the issue and then details as body in the ticket, that makes easier to process it
