### ISSUE TITLE
in_tail: control name of message field

### ISSUE THREAD

**Issue by katrielt** [fluent/fluent-bit#317]
Currently, the message field is hard coded to "log". It would be nice to be able to control that with a configuration (Say, change it to "message") for better compatibility.
So, a log entry with no parser will be {"message": "log line"} instead of {"log": "log line"}

**Comment by edsiper** [comment]
@katrielt 

I've added a new _key_ option for tail input plugin, when set it value is used to store unstructured messages (available on GIT master)

**Comment by edsiper** [comment]
Fixed.
