### ISSUE TITLE
Apply parser filter to log_processed

### ISSUE THREAD

**Issue by ogarcia** [fluent/fluent-bit#3176]
I have the following config:
```
[FILTER]
    Name                kubernetes
    Match               kube.*app*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix     kube.var.log.containers.
    Merge_Log           On
    Merge_Log_Key       log_processed
    Merge_Parser        merge_parser_app
    K8S-Logging.Parser  On
    K8S-Logging.Exclude Off

[FILTER]
    Name                parser
    Match               kube.*app*
    Key_Name            $log_processed['message']
    Parser              log_processed_app
    Preserve_Key        On
    Reserve_Data        On

[PARSER]
    Name        merge_parser_app
    Format      regex
    Regex       \[(?<level>[^\]]+)\] (?<logger>[^ ]+) in (?:(?<thread_name>.+?)-(?<thread_id>[\d-]+)) (?:(?<marker_name>[^= ]+)=(?<marker_id>[^ ]+))? - (?<message>(.|\n|\r)*)

[PARSER]
    Name        log_processed_app
    Format      regex
    Regex       ^(?<request_uri>[^\s]+)\s+(?<method>[^\s]+)\s+(?<headers>.*?)\s*(?:(?<status>(\d+|null))\s(?<request_time>\d+))?$

```

The first parser works well and extract the fields to `log_processed` without problems. Is possible have a second filter that parses `message` field extracted by first filter?

**Comment by agup006** [comment]
I'm not sure I fully understand the request - do you want another parser to run after message? This would be adding another parser filter in the pipeline. 

If you want a copy of the field you will first need to run the modify filter and then you can run multiple parser filters.

**Comment by ogarcia** [comment]
I explain, in my sample I have two filters. The first one (kubernetes) extracts well the fields with parser `merge_parser_app` to key `log_processed`. At this moment in `log_processed` I have:
```
{
  "log_processed": {
    "level": "INFO",
    "logger": "my_logger",
    "thread_name": "my_thread",
    "thread_id": 1,
    "marker_name": "Marker",
    "marker_id": 100,
    "message": "https://github.com GET Host: github.com 200 50"
  }
}
```

Now, I want parse the `message` field of `log_processed` with `log_processed_app` parser. I added the second filter (parser) to do this but it doesn't do anything.

I have two questions about this. The first one is. I can do this? And the second one is. I can do this but only when in other field I have a determined value (for example when field `level` contains `INFO`)?

**Comment by ogarcia** [comment]
Bump

**Comment by ogarcia** [comment]
Bump

**Comment by ogarcia** [comment]
Bump

**Comment by ogarcia** [comment]
Bump

**Comment by taspac** [comment]
I'm facing similar issue while trying to filter encapsulated into syslog apache's log: parser on [INPUT] (syslog-rfc5424, out of syslog-ng via dgram socket) works fine - can grab all apache's stuff in "message", then on the 2nd stage [FILTER] parser does nothing on _Key_Name. message_

**Comment by ogarcia** [comment]
Bump

**Comment by adriannieto-attechnest** [comment]
We also suffer this issue

**Comment by ogarcia** [comment]
Bump

**Comment by agup006** [comment]
I'm wondering if the log_processed field is messing up record modifier

could you try changing the `Merge_Log_Key log_processed` to `log`?

**Comment by nokute78** [comment]
@ogarcia Currently filter_parser doesn't support record accessor like `$log['message']`.
Workaround is to use filter_nest .

A pipeline is 
filter_kubernetes -> **filter_nest(lift)** -> filter_parser -> **filter_nest(nest)** 

Below is an example configuration.
Dummy generates record https://github.com/fluent/fluent-bit/issues/3176#issuecomment-793492790 that imitates filter_kubernetes.
```
[SERVICE]
    Parsers_File parsers.cnf

[INPUT]
    Name dummy
    Dummy {"log_processed": {"level": "INFO","logger": "my_logger","thread_name": "my_thread","thread_id": 1,"marker_name": "Marker","marker_id": 100,"message": "https://github.com GET Host: github.com 200 50"}}

[FILTER]
    Name nest
    Match *
    Operation lift
    Nested_Under log_processed
    Add_Prefix LIFT_

[FILTER]
    Name parser
    Match *
    Parser log_processed_app
    Key_Name LIFT_message
    Preserve_Key        On
    Reserve_Data        On

[FILTER]
    Name nest
    Match *
    Operation nest
    Nest_Under log_processed
    WildCard LIFT_*
    Remove_Prefix LIFT_

[OUTPUT]
    Name stdout
```

Output is 
```
[0] dummy.0: [1657972437.869785051, {"request_uri"=>"https://github.com", "method"=>"GET", "headers"=>"Host: github.com", "status"=>"200", "request_time"=>"50", "log_processed"=>{"level"=>"INFO", "logger"=>"my_logger", "thread_name"=>"my_thread", "thread_id"=>1, "marker_name"=>"Marker", "marker_id"=>100, "message"=>"https://github.com GET Host: github.com 200 50"}}]
```

**Comment by ogarcia** [comment]
@nokute78 many thanks for the workaround!

Anyway I think I should leave this ticket open so that somehow filter_parser can support record accessor like `$log['message']`.

**Comment by ogarcia** [comment]
Bump

**Comment by ogarcia** [comment]
Bump

**Comment by ogarcia** [comment]
Bump

**Comment by ogarcia** [comment]
Bump
