### ISSUE TITLE
Disk based backpressure mechanism

### ISSUE THREAD

**Issue by katrielt** [fluent/fluent-bit#318]
Would like to see a disk based (As opposed to memory / Mem_Buf_Limit) back-pressure, like fluentd.
In many cases, RAM is expensive or not readily available (i.e. taken up by the application).
Not having a disk based buffer can mean lost logs or hanged application threads that are waiting to write logs.

**Comment by edsiper** [comment]
@katrielt are you using a source of data different than log files in the file system ?

**Comment by katrielt** [comment]
Most of my logs come over in_forward from a java process using a fluentd appeder roughly based on [fluent-logger-java](https://github.com/fluent/fluent-logger-java).
Currently, fluentd's "store-and-forward" disk buffering mechanism is used to make sure logs are not lost if the logs aggregator has any problems.

**Comment by edsiper** [comment]
sorry for the late reply.

Disk-buffering mechanism in Fluent Bit is not designed to work as an aggregator, there is an enhancement request on that area but no ETA yet. For a strong aggregator I recommend you use Fluentd instead

**Comment by edsiper** [comment]
for the record: file system buffering mechanism already exists:

https://docs.fluentbit.io/manual/configuration/buffering
