### ISSUE TITLE
CentOS old td-agent-bit old packages not available

### ISSUE THREAD

**Issue by andrunah** [fluent/fluent-bit#3183]
I'm unable to install 1.3.11 which was available last week.

Downloading packages:
td-agent-bit-1.3.11-1.x86_64.r FAILED
https://packages.fluentbit.io/centos/7/./td-agent-bit-1.3.11-1.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found

Direct link does not work either.

Is something broken, or any way to get this package back?

**Comment by spaulg** [comment]
Ditto - running in to the same problem. 

Started happening for me on the 6th March. On the 5th everything was fine.

Effecting all my RH based systems using the YUM repository method of install. :(

**Comment by edsiper** [comment]
Hi, 

make sure you are pointing to the right path in your Yum repo file:

https://docs.fluentbit.io/manual/installation/linux/redhat-centos#configure-yum

**Comment by evgkrsk** [comment]
Still hitting the issue. Copy pasting from https://docs.fluentbit.io/manual/installation/linux/redhat-centos#configure-yum isn't working:

```
[root] /etc (git)-[master] # cat yum.repos.d/td-agent-bit.repo
[td-agent-bit]
baseurl = https://packages.fluentbit.io/centos/7/$basearch/
enabled = 1
gpgcheck = 1
gpgkey = https://packages.fluentbit.io/fluentbit.key
name = TD Agent Bit

[root] /etc (git)-[master] # yum list available --showduplicates  td-agent-bit
Loaded plugins: etckeeper, fastestmirror, protectbase
Loading mirror speeds from cached hostfile
 * base: ftp.halifax.rwth-aachen.de
 * epel: ftp.plusline.net
 * extras: ftp.rz.uni-frankfurt.de
 * updates: ftp.rrzn.uni-hannover.de
0 packages excluded due to repository protections
Available Packages
td-agent-bit.x86_64                                                                    1.7.4-1                                                                     td-agent-bit
```
