### ISSUE TITLE
Fluent bit .EXE is complaining about missing libcrypto-1_1-x64.dll in  1.7.1 and 1.7.2 installer and zip packages 

### ISSUE THREAD

**Issue by famousit** [fluent/fluent-bit#3186]
## Bug Report

**Describe the bug**
After downloading either package

and following the instructions under 
https://github.com/fluent/fluent-bit-docs/blob/master/installation/windows.md

on a windows server 2019 an error is shown complaining the  library libcrypto-1_1-x64.dll was not found

![image](https://user-images.githubusercontent.com/4939733/110323892-893bd380-8015-11eb-8f81-62a78185e7df.png)

Are there additional prerequisites for running fluentbit ? version 1.6.3 which I used before was workingfine
**To Reproduce**
- download 64bit package from https://docs.fluentbit.io/manual/installation/windows#compile-from-source
- follow instructiosn https://github.com/fluent/fluent-bit-docs/blob/master/installation/windows.md
- .\bin\fluent-bit.exe -i dummy -o stdout will reproduce the error

**Expected behavior**
package runs without prerequisite out of the box or the prerequisites are mentioned in the installation guide

**Screenshots**

**Your Environment**

* Version used: Windows server 2019
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: VMSphere
* Operating System and version: windows server 2019
* Filters and plugins:

**Additional context**

**Comment by agup006** [comment]
@fujimotos @edsiper OpenSSL is probably not common on Windows, would it be worth defaulting to mbed TLS for Windows and optional OpenSSL builds available?

**Comment by fujimotos** [comment]
@agup006 I posted a patch #3193 that enables static linking of OpenSSL
on Windows build.

With this merged, users should now be able to run Fluent Bit without
preinstalling OpenSSL on Windows servers.

**Comment by agup006** [comment]
Awesome thanks @fujimotos , @edsiper should we rebuild 1.7.2 with the libraries link or wait until 1.7.3?

**Comment by famousit** [comment]
it would be great if I the 1.7.2 version would be rebuild with this fix.

**Comment by rifftual** [comment]
What's the status of this?

**Comment by fujimotos** [comment]
> What's the status of this? All 1.7 versions have the same error, 1.6.10 works. Tried only 64-bit releases.

@rifftual  Fixed in master HEAD. Should be resolved in v1.7.3.
The exact date for the release is not yet determined.

**Comment by RainingNight** [comment]
v1.7.3 have the same error!

**Comment by rifftual** [comment]
> v1.7.3 have the same error!

Confirmed!

**Comment by agup006** [comment]
@RainingNight @rifftual we re-released the windows version of 1.7.3, are you able to give it a try now?

**Comment by RainingNight** [comment]
@agup006 Thanks, It's resolved.

**Comment by fujimotos** [comment]
@agup006 Thank you for taking care of re-releasing `v1.7.3`.
Now, I'm going to close this issue.
