### ISSUE TITLE
Any plans for Docker container monitoring in plugins?

### ISSUE THREAD

**Issue by spatialvlad** [fluent/fluent-bit#319]
Hi,

I wonder if you guys have any plans to implement Docker container monitoring with Fluent Bit.

You already have node monitoring in plugins (cpu, mem, disk). It is also possible to use Fluent Bit instead of Fluentd as a Docker logging driver.

If you also had some In plugins for monitoring Docker containers (e.g. something similar to cAdvisor, Dockbeat, Docker stats) it would be possible to have most of the needed monitoring and log collection for Docker microservices/containers using Fluent Bit, Elasticsearch and Kibana.

Without the container monitoring, it looks like it's needed to also run other tools like cAdvisor to get a good setup for Docker/Docker Swarm deployments.

It looks like cAdvisor (with its web server and other goodies) will be much less efficient than Fluent Bit. Plus Fluent Bit is already somewhat in the same territory (cpu, mem and disk monitoring, Docker logging drivers).

It would be great to have only one extra tool per node (Fluent Bit, of course) to collect and forward all Docker-related info into ES.

Thus, I wonder if:
1. You have any plans to add Docker container monitoring as some kind of in plugins.
2. You might have some working current workarounds that allow full Docker container monitoring using just Fluent Bit.

Thank you.

**Comment by spatialvlad** [comment]
I guess what I described in the post above is conceptually similar to Docker Input Plugin in Telegraph:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker

There also was some somewhat similar in Fluentd:
https://github.com/kiyoto/fluent-plugin-docker-metrics

Thanks.

**Comment by edsiper** [comment]
@spatialvlad 

no plans yet but sounds interesting to implement. One question, since there are many metrics, for your use case what are the most relevant ones ?

note: thinking if we should query metrics directly from cgroups info or talk to docker api (there are other engines like rkt and the one made by Oracle).

**Comment by spatialvlad** [comment]
I would say that the primary metrics would be those that could help make decisions which services/containers eat too many resources and need more instances launched and/or optimization from the development team.

Thus, primary metrics would be:
**I. Most important:**
1. Memory usage
2. CPU usage
**II. Also good to have ones:**
3. network traffic (bytes and # of packets, in and out).
4. disk I/O 

As for the best way to integrate it (cgroups vs docker api) it's hard to tell for me, not sure what will be easier.
I guess I would choose docker api, since some other metrics they provide or will provide later might be easier to get and add if it becomes needed.
Other container engines will likely have much fewer users, at least for foreseeable future. Plus bumping all container engines in one plugin might end up in making it more difficult to change and maintain this plugin, as well as setup for end users.
But, of course, these are just my 2 cents.

**Comment by nokute78** [comment]
@spatialvlad 

> network traffic (bytes and # of packets, in and out).

I pushed #324 to monitor network traffic. Could you check it?

**Comment by spatialvlad** [comment]
@nokute78 , I'll try to check it later today or tomorrow.

As far as I understand, this will be combined network traffic monitoring, not per Docker container (as we've been discussing in this topic)?

**Comment by edsiper** [comment]
@spatialvlad the plugin provided by @nokute78 will not work with Docker API, it can consume local info only

**Comment by nokute78** [comment]
Oops, I had misunderstood.

@spatialvlad The plugin isn't related to Docker, so it is not what you want.

**Comment by hasseio** [comment]
+1

**Comment by edsiper** [comment]
there is a "monitoring plugin for Docker" under development. I hope to publish some news in a few weeks.

**Comment by ashutoshdhundhara** [comment]
Is someone working on this FR? If not, can I pick this?

**Comment by chrfergen** [comment]
It would be interesting to have something like this:
https://github.com/Ingensi/dockbeat
fluent-bit works very well for Docker logs collection, it would be nice to use it even for Docker metrics collection.

**Comment by edsiper** [comment]
This plugin was contributed and merged into v1.3 release, documentation will arrive shorlty.

This is the commit reference: https://github.com/fluent/fluent-bit/commit/d19be0d7651eb2463e95ffbca9295bde95f50567
