### ISSUE TITLE
Add Option to Disable retries (or allow 0 for retries)

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#3190]
**Is your feature request related to a problem? Please describe.**

In some cases, logs are coming in at such high throughput that even trying to retry is not ideal. May be buffering options are limited.

I have a customer who would prefer to be able to set retries to be 0, which is not possible today: https://docs.fluentbit.io/manual/administration/scheduling-and-retries

It should be super simple to enable this.

**Comment by cristiamu** [comment]
I'd like to add, when a output starts throttling, backoff mechanisms should be triggered to allow it to recover. This just basically drop some records while the output is recovering. 
Records dropped due to output throttling or backoff should count towards the drop count metrics.

**Comment by nokute78** [comment]
I sent a patch https://github.com/fluent/fluent-bit/pull/3219

**Comment by PettitWesley** [comment]
@nokute78 Much appreciated!
