### ISSUE TITLE
How I can parse urlencode?

### ISSUE THREAD

**Issue by vanokg** [fluent/fluent-bit#3194]
Hi every one, I have an trouble with parsing nginx logs witch contain urlencoded json in log.

encoded:
`%7B%22first%22%3A%22yes%22%2C%22child%22%3A%22no%22%2C%22locale%22%3A%22ru%22%2C%22os%22%3A%22ios%22%2C%22userType%22%3A%22DEFAULT%22%7D`

after docoding in https://www.urldecoder.org
`{"first":"yes","child":"no","locale":"ru","os":"ios","userType":"DEFAULT"}`

How I can do this in fluent-bit via FILTERS or PARSERS?

**Comment by agup006** [comment]
If there is a library that does this you could potentially do this via a filter and a lua script. If it is an online resource it is still achievable, but throughput would be a problem
