### ISSUE TITLE
TCP input not taken custom port

### ISSUE THREAD

**Issue by hardwaysun** [fluent/fluent-bit#3201]
## Bug Report

**Describe the bug**

Can't use the custom tcp port in td-agent-bit
[root@xisun-centos-168 td-agent-bit]# /opt/td-agent-bit/bin/td-agent-bit -i tcp:\\0.0.0.0:5170 -o stdout -v
Error: Invalid input type. Aborting

with attached config which define INPUT as tcp , the service won't start.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
[root@xisun-centos-168 td-agent-bit]# /opt/td-agent-bit/bin/td-agent-bit --input=tcp:\\10.4.168.20:601 -o stdout -v
Error: Invalid input type. Aborting

[root@xisun-centos-168 td-agent-bit]# /opt/td-agent-bit/bin/td-agent-bit -i tcp:\\0.0.0.0:601 -o stdout -v
Error: Invalid input type. Aborting

[root@xisun-centos-168 td-agent-bit]# /opt/td-agent-bit/bin/td-agent-bit -v
Fluent Bit v1.7.2
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Error: No Input(s) have been defined. Aborting

not even the default port

[root@xisun-centos-168 td-agent-bit]# /opt/td-agent-bit/bin/td-agent-bit -i tcp:\\0.0.0.0:5170 -o stdout -v
Error: Invalid input type. Aborting

without custom  address and port the process can start without issue
[root@xisun-centos-168 td-agent-bit]# /opt/td-agent-bit/bin/td-agent-bit -i tcp -o stdout
Fluent Bit v1.7.2
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/03/09 22:01:34] [ info] [engine] started (pid=2422)
[2021/03/09 22:01:34] [ info] [storage] version=1.1.1, initializing...
[2021/03/09 22:01:34] [ info] [storage] in-memory
[2021/03/09 22:01:34] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/03/09 22:01:34] [ info] [input:tcp:tcp.0] listening on 0.0.0.0:5170
[2021/03/09 22:01:34] [ info] [sp] stream processor started

^C[2021/03/09 22:01:39] [engine] caught signal (SIGINT)
[2021/03/09 22:01:39] [ warn] [engine] service will stop in 5 seconds
[2021/03/09 22:01:43] [ info] [engine] service stopped

- Steps to reproduce the problem:
/opt/td-agent-bit/bin/td-agent-bit -i tcp:\\0.0.0.0:5170 -o stdout -v
**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:  Fluent Bit v1.7.2
* Configuration: 
```
 [SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        5

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    # storage.path /tmp/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    # storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    # storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    # storage.backlog.mem_limit 5M

[INPUT]
    Name        tcp
    Listen      0.0.0.0.  //// If I remove the Listen, only specify Port then it will work.
    Port        601
    Chunk_Size  32
    Buffer_Size 64
    Format      none

[OUTPUT]
    name  stdout
    match *
```

With about config, if try to start service will have error

[root@xisun-centos-168 etc]# systemctl status td-agent-bit
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2021-03-09 21:14:39 EST; 19min ago
  Process: 2327 ExecStart=/opt/td-agent-bit/bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf (code=exited, status=255)
 Main PID: 2327 (code=exited, status=255)

Mar 09 21:14:38 xisun-centos-168.20 systemd[1]: td-agent-bit.service: main process exited, code=exited, status=255/n/a
Mar 09 21:14:38 xisun-centos-168.20 systemd[1]: Unit td-agent-bit.service entered failed state.
Mar 09 21:14:38 xisun-centos-168.20 systemd[1]: td-agent-bit.service failed.
Mar 09 21:14:39 xisun-centos-168.20 systemd[1]: td-agent-bit.service holdoff time over, scheduling restart.
Mar 09 21:14:39 xisun-centos-168.20 systemd[1]: Stopped TD Agent Bit.
Mar 09 21:14:39 xisun-centos-168.20 systemd[1]: start request repeated too quickly for td-agent-bit.service
Mar 09 21:14:39 xisun-centos-168.20 systemd[1]: Failed to start TD Agent Bit.
Mar 09 21:14:39 xisun-centos-168.20 systemd[1]: Unit td-agent-bit.service entered failed state.
Mar 09 21:14:39 xisun-centos-168.20 systemd[1]: td-agent-bit.service failed.

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by agup006** [comment]
I modified your comment to reformat the config, for the listen parameter looks like you have an extra `.` at the end of `0.0.0.0`. Additionally to run on command line you will want to use the following: `fluent-bit -i tcp://192.168.3.2:9090 -o stdout`
