### ISSUE TITLE
tail with multiline segfaults

### ISSUE THREAD

**Issue by dusty73** [fluent/fluent-bit#321]
Hi,
   I'm trying the new feature multiline of tail input plugin. I've built from using fluent-bit-packaging, running on Centos 7.
This is the relevant configuration snippets:

td-agent-bit.conf

[INPUT]
    Name        tail
    Path        /var/log/custom/custom.log
    Multiline   On
    DB          /var/log/custom_tail.db
    Parser_Firstline custom_start
    Parser_1    custom
    Tag         custom.app

in parsers.conf I've added custom and custom_start parsers:

[PARSER]
    Name        custom_start
    Format      regex
    Regex       /^\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}/

[PARSER]
    Name        custom
    Format      regex
    Regex       /^(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<priority>\w+)\s*:(?<thread>.*?):(?<message>.*) \[(?<AppUserId>.*?)\]: \[(?<TenantId>.*?)\]: (?<category>.*)/

Then when I append a line to to the log the td-agent-bit service exits with a segfault:
kernel: td-agent-bit[4578]: segfault at 0 ip           (null) sp 00007ffea712b8e8 error 14 in td-agent-bit[400000+2b5000]

If I disable the multline feature the process doesn't segfault anymore.

**Comment by edsiper** [comment]
@dusty73 thanks for testing it.

Would you please provide the multiline file that makes Fluent Bit crash ? (that will be easier to reproduce)

**Comment by dusty73** [comment]
Actually it segfaults with any content, in any case, this is a sample:

2017-06-08 00:00:00,598:WARN   :INVItemVelocityCacheThread: ItemNodeVelocity cache cleared for all items.                [system]: [ ]: INVItemNodeVelocityCacheImpl

**Comment by edsiper** [comment]
I've found there is a problem when working with invalid regex rule, working in a fix.

For now please check your _custom_ rule which is invalid:

```
/^(?\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?\w+)\s*:(?.?):(?.) [(?.?)]: [(?.?)]: (?.*)/
```

**Comment by edsiper** [comment]
@dusty73 I pushed a fix in our GIT master repo. Also please make sure to validate your regex as it have some errors.

This is a good site to test expressions and texts: http://rubular.com/

**Comment by dusty73** [comment]
Ok, thank you. I mistakenly added / as regex delimiter.

Now I'm facing a problem on parsing multiline log lines. What I'm trying to do is to parse a log generated by a java application, so I wrote this regexp.

`^(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<priority>\w+)\s*:(?<thread>.*?):(?<message>.*) \[(?<AppUserId>.*?)\]: \[(?<TenantId>.*?)\]: (?<category>.*)$`

The "message" field can span on multiple lines, but it seems that the regexp can't match beyond the first line. Normally I would add the "m" flag to the regexp, is it possible to add it in some way?

**Comment by edsiper** [comment]
Please share an example from rubular.com (fill the fields and click on "permanent link"), then share the link. 

I am not an expert on regex, but I can pass the link to some folks for review.

**Comment by dusty73** [comment]
Here's an example: http://rubular.com/r/a0hMfhg1HB. If you 
From what I understand, the lines are appended to a buffer until the "Parser_Firstline" is matched, then the buffer is matched against Parser_1. The problem is that the buffer contains also the newlines, and any regexp without the "m" flag will stop the parsing to the first newline.

Thank you

**Comment by nokute78** [comment]
A header `?(m-ix)` may help.
```
(?m-ix)^(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<priority>\w+)\s*:(?<thread>.*?):(?<message>.*) \[(?<AppUserId>.*?)\]: \[(?<TenantId>.*?)\]: (?<category>.*)$
```

We use onigmo as regex engine.

The document is here.
https://github.com/fluent/fluent-bit/blob/master/lib/onigmo/doc/RE#L259



I tested like this.
http://rubular.com/r/2An6TnHeJ5

**Comment by dusty73** [comment]
Tried in fluentbit conf, the pattern written in this way is invalid:
`Jul 11 15:15:17 tgt td-agent-bit: [parser] Invalid regex pattern ?(m-ix)^(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<priority>\w+)\s*:(?<thread>.*?):(?<message>.*) \[(?<AppUserId>.*?)\]: \[(?<TenantId>.*?)\]: (?<category>.*)$`

So I changed a bit, inserting the modifier after the caret: 
`^?(m-ix)(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<priority>\w+)\s*:(?<thread>.*?):(?<message>.*) \[(?<AppUserId>.*?)\]: \[(?<TenantId>.*?)\]: (?<category>.*)$`

Now fluentbit doesn't discard the pattern but the pattern doesn't match the lines.

**Comment by edsiper** [comment]
What about if you put the pattern between / /, e.g:

```
/?(m-ix)^(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<priority>\w+)\s*:(?<thread>.*?):(?<message>.*) \[(?<AppUserId>.*?)\]: \[(?<TenantId>.*?)\]: (?<category>.*)$/
```

**Comment by dusty73** [comment]
Same as before:
`Jul 12 09:25:09 td-agent-bit[3071]: [parser] Invalid regex pattern /?(m-ix)^(?<time>\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2},\d{3}):(?<...ry>.*)$/
`

IMO the regex parser should accept the / / delimiters that are the standard way of writing regex.

**Comment by nokute78** [comment]
> A header ?(m-ix) may help.

Oops, I had a typo...

`(?m-ix)` is right format...

**Comment by edsiper** [comment]
@dusty73 is it working now ?

**Comment by VinkDong** [comment]
How to meger docker log by multiline,
docker logs like:
```
{"log":"2017-07-26 07:54:42.130  WARN parse organization id exception\n","stream":"stdout","time":"2017-07-25T07:54:42.131621351Z"}
{"log":"\n","stream":"stdout","time":"2017-07-25T07:54:42.13171348Z"}
{"log":"java.lang.NumberFormatException: For input string: \"PodQueryBykind\"\n","stream":"stdout","time":"2017-07-25T07:54:42.131723859Z"}
```
and how to get log like this:
```
"log"=>"2017-07-26 07:54:42.130  WARN parse organization id exception\n
\n
java.lang.NumberFormatException: For input string: \"PodQueryBykind\"\n",
"time"=>"2017-07-25T07:54:42.131621351Z"
```

I have tried:
```
[INPUT]
    Name              tail
    Tag               Test.*
    Path              /root/docker_err.log
    Multiline         On
    Parser_Firstline  Frist
    Parser_N          ErrLines
    Mem_Buf_Limit     5MB
```

Parser like below
```
[PARSER]
    Name        Frist
    Format      regex
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Regex       ^{"log":"(?<logtime>[^ ]* [^ ]*)  (?<level>[^ ]*) (?<result>.*)time":"(?<time>[^"]*)\"}$

[PARSER]
    Name   ErrLines
    Format regex
    Regex  \\u.+\\n
```

I am confused at how to write ErrLines Parser

**Comment by edsiper** [comment]
@VinkDong 

according the use case where multilines are nested JSON strings, there is no solution at the moment:

```
{"log":"2017-07-26 07:54:42.130  WARN parse organization id exception\n","stream":"stdout","time":"2017-07-25T07:54:42.131621351Z"}
{"log":"\n","stream":"stdout","time":"2017-07-25T07:54:42.13171348Z"}
{"log":"java.lang.NumberFormatException: For input string: \"PodQueryBykind\"\n","stream":"stdout","time":"2017-07-25T07:54:42.131723859Z"}
```

the current implementation will handle the 3 entries as 3 separate records. Docker cannot detect multiline messages so it means we will have to implement a workaround in our side to get this fixed. 

I've created a new issue to handle that specific case: https://github.com/fluent/fluent-bit/issues/337

Closing this ticket as the main issue about segfault with multiline messages have been fixed.

**Comment by nsaud01** [comment]
What was the solution here?

**Comment by edsiper** [comment]
@nsaud01 it required two fixes:

- Fluent Bit side: https://github.com/fluent/fluent-bit/commit/9d940d07ac3b9272648b96e57ecbdb0aa2364275
- Invalid Regular Expression provided, so use: rubular.com to validate your regex
