### ISSUE TITLE
Add identifier field to each section to be used in metrics

### ISSUE THREAD

**Issue by javipolo** [fluent/fluent-bit#3213]
I'm monitoring fluent-bit with prometheus/grafana and I cannot identify which stream is which in the metrics
For example, I have multiple (+50) tail sections reading different files, but for the sake of identification all I can see is the name of the plugin, being it "tail.1" "tail.2" and so on:

```
fluentbit_input_bytes_total{container="fluent-bit",endpoint="metrics",instance="10.1.12.9:2020",job="monitoring/fluent-bit",name="tail.0",namespace="logs",pod="fluent-bit-vkvl8"}
```

It would be cool if a new field could be added to each of the configuration sections that will act as an identifier to be used later in metrics, like:

```
[INPUT]
name=tail
id=frontend-nginx
```
```
fluentbit_input_bytes_total{container="fluent-bit",endpoint="metrics",instance="10.1.12.9:2020",job="monitoring/fluent-bit",name="tail.0",id="frontend-nginx",namespace="logs",pod="fluent-bit-vkvl8"}
```
and that field be reflected in the metrics, so I can properly identify and label each stream/plugin in the dashboards

I tried to use name=tail.myid as a workaround, but it's not working. Anyway it would be way cleaner something as the proposed solution

Thank you very much

**Comment by agup006** [comment]
@javipolo @gcasanova could you use Alias? https://docs.fluentbit.io/manual/administration/monitoring#configuring-aliases

**Comment by javipolo** [comment]
Sure!!
I didnt know about this field, it is exactly what I needed

Tested and works like a charm!
Thank you :)
