### ISSUE TITLE
Fluent-bit crashed  at startup when use custom plugin

### ISSUE THREAD

**Issue by xiviu123** [fluent/fluent-bit#3221]
## Bug Report

**Describe the bug**

I  build a test plugin from this source https://github.com/fluent/fluent-bit-plugin
Fluent-bit crashed  at startup when i added this plugin.

**To Reproduce**
- Log startup:
```
fluent_bit    | Fluent Bit v1.7.2
fluent_bit    | * Copyright (C) 2019-2021 The Fluent Bit Authors
fluent_bit    | * Copyright (C) 2015-2018 Treasure Data
fluent_bit    | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent_bit    | * https://fluentbit.io
fluent_bit    | 
fluent_bit    | [2021/03/15 10:45:55] [engine] caught signal (SIGSEGV)
fluent_bit    | #0  0x0                 in  ???() at ???:0
fluent_bit exited with code 139
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.7.2
* Configuration:
```
[SERVICE]
# This is the main configuration block for fluent bit.
# Ensure the follow line exists somewhere in the SERVICE block
  Log_Level debug
  Plugins_File plugins.conf
# [INPUT]
#   Name tail
#   Buffer_Chunk_Size 32k
#   Buffer_Max_Size 32k
#   Path /logs/*.log
  
#   Read_from_Head True
#   Refresh_Interval 60
#   Rotate_Wait 5
#   DB log.pos
#   Mem_Buf_Limit 100m
[INPUT]
  Name cpu
  Tag  cpu.local
  # Interval Sec
  # ====
  # Read interval (sec) Default: 1
  Interval_Sec 1

[OUTPUT]
  Name stdout2
  #Format json
  

```
* Environment name and version : 
MacOS 11.2.3 docker.io/fluent/fluent-bit:1.7-debug

**Additional context**

**Comment by edsiper** [comment]
Can you try it on Linux ?

**Comment by xiviu123** [comment]
> Can you try it on Linux ?

Image **docker.io/fluent/fluent-bit:1.7-debug** use Debian os!  
You mean must host docker on Linux OS?

**Comment by xiviu123** [comment]
@edsiper 
I did a test on ubuntu.
```
root@005f74ee9382:/tmp/fluent-bit/build# bin/fluent-bit -e ./out_stdout2.so -i cpu -o stdout -f 1
[2021/03/16 03:03:28] [engine] caught signal (SIGSEGV)
#0  0x0                 in  ???() at ???:0
Aborted

```

Same error appeared.
May be the ploblem in plugin file? 
Please help.

**Comment by xiviu123** [comment]
humm, seem to be i saw the ploblem.
the plugin is built on ubuntu env and i ran fluent on debian.
i will close this issue.

**Comment by xiviu123** [comment]
Fluent Bit caught error when mount plugin as docker volume.
How can i  use plugin without rebuild docker image?
