### ISSUE TITLE
agent failed to resolve pod metadata if Kube_meta_preload_cache_dir and use_kubelet are enabled in kubernetes filter.

### ISSUE THREAD

**Issue by MartinForReal** [fluent/fluent-bit#3223]
## Bug Report

**Describe the bug**
agent failed to resolve pod metadata if Kube_meta_preload_cache_dir and use_kubelet are enabled  in kubernetes filter.

**To Reproduce**
enable tls config in kubelet
set Kube_meta_preload_cache_dir 
enable use_kubelet 

```
Client sent an HTTP request to an HTTPS server.
```
**Expected behavior**

agent should resolve pod metadata successfully

**Screenshots**

**Your Environment**
* Version used: v1.7.2

**Additional context**

https://github.com/fluent/fluent-bit/blob/7114027056f78ff24e255f9f5ae72765b79aad45/plugins/filter_kubernetes/kube_conf.c#L84-L87

**Comment by MartinForReal** [comment]
I think it is good idea if we add another parameter to disable tls

**Comment by 0123hoang** [comment]
I think this issue should not be closed.\
All google searching only suggest set  Buffer_Size  to 0.\
So I will drop some keywords here :).\
fluent bit  could not get meta for pod
