### ISSUE TITLE
output cloudwatch metrics support for metric_dimensions ${HOSTNAME}

### ISSUE THREAD

**Issue by markuman** [fluent/fluent-bit#3240]
**Is your feature request related to a problem? Please describe.**
We want to use `${HOSTNAME}` as a dimension in cloudwatch metrics

**Describe the solution you'd like**

```
[OUTPUT]
    Name cloudwatch_logs
    Match mem
    log_stream_name mem_${HOSTNAME}
    log_group_name fluent-bit-cloudwatch
    region eu-central-1
    log_format json/emf
    metric_namespace fluent-bit-metrics
    metric_dimensions memory,${HOSTNAME}
    auto_create_group true
```

**Describe alternatives you've considered**

Rollout config with ansible

```
[OUTPUT]
    Name cloudwatch_logs
    Match mem
    log_stream_name mem_${HOSTNAME}
    log_group_name fluent-bit-cloudwatch
    region eu-central-1
    log_format json/emf
    metric_namespace fluent-bit-metrics
    metric_dimensions memory,{{ inventory_hostname }}
    auto_create_group true
```

**Comment by raykrueger** [comment]
Can we bring this back from the dead? I'm using fluentbit to send logs to cloudwatch via on-premises Kubernetes cluster. I don't see a way to add hostname as a dimension. I tried applying the kubernetes filter so I could use $kubernetes['host'], but that just errors with `incoming record tag (cpu) is shorter than kube_tag_prefix value (kube.var.log.containers.), skip filter`
