### ISSUE TITLE
AWS ES TLS is unreachable

### ISSUE THREAD

**Issue by a8j8i8t8** [fluent/fluent-bit#3241]
## Bug Report

**Describe the bug**
I am getting below error with version `1.7.2`.
```
fluent-bit-hkgms fluent-bit [2021/03/17 08:09:13] [error] [upstream] connection #258 to search-doamin-logssystem-REDACTED.zone.es.amazonaws.com:443 timed out after 10 seconds
```

Is [this PR](https://github.com/fluent/fluent-bit/pull/3043) related to above?
Appreciate your help.

**Additional context**
With version `1.6.10` it's not an issue BTW.

~Ajit

**Comment by gitfool** [comment]
Also seeing this.

**Comment by mcanaves** [comment]
+1

**Comment by Dgadavin** [comment]
Me too. And after some time fluent bit stop sending logs to AWS ES

**Comment by a8j8i8t8** [comment]
I think it's a config issue, with below config I don't see the issue in `1.7.3`.
```
    tls                 On
    tls.verify          Off
    Trace_Error         On
    net.keepalive       On
    Buffer_Size         100M
```
