### ISSUE TITLE
flb_utils_size_to_bytes returns different value if str includes 'B' or not

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#325]
`flb_utils_size_to_bytes` returns value like this.

```
"1k" -> 1024
"1kB" -> -1
"1m" -> 1
"1mB" -> 1048576
```

If we use unit "KB", the string should __not__ contain character "B".
If we use unit "MB", the string should contain character "B".

I prefer it returns value if string contains "B" or not. How about this ? :)

**Comment by edsiper** [comment]
@nokute78 it ended up like this:

- k, kb, KB = 1000 bytes
- m, mb, MB = 1000 * 1000 bytes
- g, gb, GB = 1000 * 1000 * 1000 bytes

more details on #327.

thanks for helping troubleshoot. Closing for now.

**Comment by nokute78** [comment]
@edsiper Thanks!
