### ISSUE TITLE
Fluent bit is dropping the HTTP body for the HTTP Output plugin

### ISSUE THREAD

**Issue by p1kumarn** [fluent/fluent-bit#3250]
## Bug Report

**Describe the bug**

The below is my input plugin
[INPUT]
    Name tail
    Tag  shopAlert
    # Interval Sec
    # ====
    # Read interval (sec) Default: 1
    path /opt/hal/logs/central/shopAlert.log
    Interval_Sec 1

The below is my http output plugin config
[OUTPUT]
    name http
    match shopAlert
    host host
    port 443
    uri /api/terminal/alerting
    tls        On
    tls.verify Off
    header apiKey value
    header access_token value
    header Content-Type application/json
    #format json
    # path  C:/var/log/fluentbit/output

when i am getting the information in the logs at the HTTP consumer end - its missing the entire body.

Could you please suggest if anything is wrong with our configuration

**Comment by edsiper** [comment]
would you please point us to the HTTP consumer project or source code to validate on that end too ?.
