### ISSUE TITLE
Can't turn off WAL

### ISSUE THREAD

**Issue by tlefevre** [fluent/fluent-bit#3255]
## Bug Report

The documentation is not clear on how to turn off DB.wal. I have tried Off, off and false. Nothing really works it seems? 

Error posted on start up in stdout -> [2021/03/19 12:33:24] [error] [lib] backend failed. 

There's nothing in the log file.

**Comment by nokute78** [comment]
WAL off feature will be supported from v1.7.3 , however it is not released yet. (latest version is v1.7.2)
https://docs.fluentbit.io/manual/pipeline/inputs/tail#wal-and-memory-usage

**Comment by tlefevre** [comment]
Ah ok, thanks! I didn't catch that.

"Note that WAL is not compatible with shared network file systems" - I need to turn it off, since we're using Fluent-bit in Kubernetes and storing the files on a GlusterFS mounted volume. 

Reading the docs, it seems that it is not a good idea to use WAL.

**Comment by nokute78** [comment]
Thank you for comment. So, please be waiting next release.
Note: We supported this feature to  fix #3073 memory resource issue.

I'm not familiar with WAL. 
It is good information for me. Thank you.

https://sqlite.org/wal.html#concurrency
```
The wal-index greatly improves the performance of readers, but the use of shared memory means that all readers must exist on the same machine. This is why the write-ahead log implementation will not work on a network filesystem.
```

**Comment by tlefevre** [comment]
Do you know of anyone familiar with "why" it's a problem on shared network file systems?

We're so far just planning to run a single fluent-bit instance, so it might not be a problem at all even though it's on a Gluster filesystem.

**Comment by nokute78** [comment]
I don't know.

I think the hint is `shared-memory`. It is usually used for inter-process, not for inter-machine.
Refer to the sqlite document, wal-index is implemented using shared memory.
https://sqlite.org/wal.html#implementation_of_shared_memory_for_the_wal_index

**Comment by tlefevre** [comment]
Thanks for the help :)

**Comment by nokute78** [comment]
v1.7.3 has been released.
The option to handle WAL is `db.journal_mode`. (`db.wal` option is not supported)

We can set the following value.
https://github.com/fluent/fluent-bit/pull/3239#issuecomment-801213997
