### ISSUE TITLE
CMake installs systemd files to /lib instead of /usr/lib

### ISSUE THREAD

**Issue by grawlinson** [fluent/fluent-bit#3264]
According to [systemd.unit](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#System%20Unit%20Search%20Path) documentation, systemd searches for units in `/usr/lib` and not `/lib`.

Current `fluent-bit` code uses a hardcoded path:

https://github.com/fluent/fluent-bit/blob/e34f061396f95955af828049feaa0baedfb60a47/src/CMakeLists.txt#L412-L419

Seems to be somewhat related to #2657. I've just looked at the suse branch, relevant code here:

https://github.com/fluent/fluent-bit/blob/22aa0c6a2bb1f0d68c8e855c1e90b08b2808eebf/src/CMakeLists.txt#L382-L389

It doesn't seem to work because on a lot of distros `/lib` is a symlink to `/usr/lib` so that if/else statement will always execute that first case. The comment is on the right track, using a cmake variable to declare the directory for systemd unit(s).

A quick search shows a battle-tested implementation by ClamAV, using a CMake recipe for [systemd](https://github.com/clamwin/clamav/blob/0.103.0/cmake/FindSYSTEMD.cmake), and the relevant [CMakeLists.txt](https://github.com/clamwin/clamav/blob/0.103.0/clamd/CMakeLists.txt#L50-L57) showing the usage of the recipe.

**Comment by grawlinson** [comment]
Still relevant, however PR #3394 should fix this issue if it gets merged.

**Comment by nokute78** [comment]
I merged #3394 . 
Can we close this issue ?

**Comment by grawlinson** [comment]
Absolutely! Thanks for merging that PR.
