### ISSUE TITLE
Support merging back logs after being split

### ISSUE THREAD

**Issue by saif-romdhane** [fluent/fluent-bit#3273]
In the context of using AWS ECS backed by fargate with fluent-bit to ship the JSON formatted logs produced by the application container to Datadog (more details about the integration can be found in Datadog's documentation - [link](https://docs.datadoghq.com/integrations/ecs_fargate/?tab=fluentbitandfirelens)). Docker truncates logs at 16KB which leads to having invalid JSON logs sent to Datadog. This is frustrating as it doesn't allow for example to display a valid exception stack where logs are most useful.

Currently, the available options to fix this are all bound to using the tail input plugin ([link](https://docs.fluentbit.io/manual/v/1.2/input/tail)) which doesn't work in ECS context where the Forward input plugin is the only solution. Moreover, fargate version 1.4 uses containerd which doesn't add the partial_message key when the log message is split.

As a solution, I suggest adding support of multiline logs to Forward input plugging just like the tail plugin even when it means dropping JSON logs in favor of raw logs. I think this would be the most self-sufficient solution as other solutions like Docker_mode relies on the Docker daemon behavior (partial_message).

**Comment by computerwizjared** [comment]
Hi, we are encountering the same issue. Was this ever addressed or did you find a solution?

**Comment by drewagentsync** [comment]
Having this issue still with no clear workaround. Does anyone have any possible solutions for this?

**Comment by Cherepoc** [comment]
Same, would really like the solution for this

**Comment by remiflament** [comment]
Hello, in my stack I have the partial attributes added by the runtime. 

> stack: Running ecs containers on EC2 pool configured with Bottlerocket in the latest version. Application Rails configured with lograge to render JSON logs in STDOUT.

If you do have these attributs, you have the solution to re-combine the logs that were split with the FILTER [plugin multiline](https://docs.fluentbit.io/manual/v/1.9-pre/pipeline/filters/multiline-stacktrace#docker-partial-message-use-case) of fluentbit

You have a [demo on how to configure Firelens with the extra configuration](https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/filter-multiline-partial-message-mode) required to support partial messages.

**Comment by remiflament** [comment]
To give more update on this, Fargate now supports multiline logs 🚀
See my previous message to configure your filter plugin to re-combine split logs.

Ressources:
- https://aws.amazon.com/about-aws/whats-new/2022/06/aws-fargate-supports-multiline-logging-powered-fluent-bit/
- https://github.com/aws/shim-loggers-for-containerd/issues/23
