### ISSUE TITLE
Tail exit_on_eof allow pipeline to complete first

### ISSUE THREAD

**Issue by patrick-stephens** [fluent/fluent-bit#3274]
**Is your feature request related to a problem? Please describe.**

I'm currently using a CI pipeline where I process some logs and check their output.
As part of this I was using rewrite tag to generate a filename for the output and then reading from a known input file with `exit_on_eof on`.
Unfortunately it looks like tail just stops the rest of the pipeline as soon as it hits EOF so I don't get any files output as the rewrite-tag is paused.

**Describe the solution you'd like**
Allow the full tail pipeline to complete and then exit.

**Describe alternatives you've considered**
I cannot see any alternative, currently I'm just running with timeouts to then kill fluent bit but that's less than ideal.

**Additional context**
Automated testing of parsers and other configuration to confirm we can parse some known input against expected output.

**Comment by patrick-stephens** [comment]
This is more of a feature request so not sure if should be closed or not.

**Comment by IlyaShestakov** [comment]
I'd like to use fluentbit to read files, process and write to the output. Current behavior when pipeline is aborted does not allow to do it.

**Comment by b3n3d1k7** [comment]
Ran into the same issue trying to set up a test-pipeline to ensure the configuration works as expected.
With fluent-bit not waiting until all logs from tail-input have been fully processed and written to the output file this does not really work.

**Comment by PuppetA17** [comment]
Is there any progress in this problem? sometimes I just need an one-time tail to output the offline text file, and then exit_on_eof exits before the output is finished, resulting in some data loss

**Comment by mjarosie** [comment]
I've found a workaround that works if you have a way to modify the input file - append enough empty lines to the file, so that the ones that you care about get processed and flushed before Fluent Bit reads the rest of the file and finally exits. Not a foolproof solution, doesn't address the core issue, but might work in some cases. In my case adding 200-300 empty lines was enough.
