### ISSUE TITLE
buffering - how to configure

### ISSUE THREAD

**Issue by wittenst** [fluent/fluent-bit#328]
We're looking for disk based buffering where if fluentbit gets shut down for whatever reason, or if the fluentbit process can't forward to fluentd because fluentd is down.  It looks like there is some sort of buffering available:

http://fluentbit.io/documentation/0.11/getting_started/buffer.html

But I'm not sure how to configure.  I see a couple of options in the configure help screen:

Usage: fluent-bit [OPTION]

Available Options
  -b  --buf_path=PATH   specify a buffering path
  -B  --buf_workers=N   number of workers for buffering

And I see an entry where it can be enabled in the compile in General Options

FLB_BUFFERING | Enable buffering support | No

But I'm not sure how to enable it in the configuration.  I tried including the above entries in a configuration file, 

Please advise, and thanks as always

Dan

**Comment by edsiper** [comment]
To see if this options are enabled in your binary, please provide the output of:

```
fluent-bit -c yourconffile.conf --sosreport
```

**Comment by wittenst** [comment]
When I run the above, I just get back the usual startup output:

[root@host ~]# /opt/fluentbit/usr/local/bin/fluent-bit -c /opt/fluentbit/etc/fluentbit.conf --sosreport
Fluent-Bit v0.11.12
Copyright (C) Treasure Data

Are you referring to the output of: fluent-bit --help ? It shows as enabled there:

[root@host ~]# /opt/fluentbit/usr/local/bin/fluent-bit --help
Usage: fluent-bit [OPTION]

Available Options
  **-b  --buf_path=PATH   specify a buffering path
  -B  --buf_workers=N   number of workers for buffering**
  -c  --config=FILE     specify an optional configuration file
  -d, --daemon          run Fluent Bit in background mode
  -f, --flush=SECONDS   flush timeout in seconds (default: 5)
  -F  --filter=FILTER    set a filter
  -i, --input=INPUT     set an input
  -m, --match=MATCH     set plugin match, same as '-p match=abc'
  -o, --output=OUTPUT   set an output
  -p, --prop="A=B"      set plugin configuration property
  -R, --parser=FILE     specify a parser configuration file
  -e, --plugin=FILE     load an external plugin (shared lib)
  -l, --log_file=FILE   write log info to a file
  -t, --tag=TAG         set plugin tag, same as '-p tag=abc'
  -v, --verbose         enable verbose mode
  -q, --quiet           quiet mode
  -S, --sosreport       support report for Enterprise customers
  -V, --version         show version number
  -h, --help            print this help

Inputs
  cpu                   CPU Usage
  mem                   Memory Usage
  kmsg                  Kernel Log Buffer
  tail                  Tail files
  proc                  Check Process health
  disk                  Diskstats
  head                  Head Input
  health                Check TCP server health
  serial                Serial input
  stdin                 Standard Input
  tcp                   TCP
  mqtt                  MQTT, listen for Publish messages
  forward               Fluentd in-forward
  random                Random
  syslog                Syslog

Outputs
  counter               Records counter
  es                    Elasticsearch
  exit                  Exit after a number of flushes (test purposes)
  forward               Forward (Fluentd protocol)
  http                  HTTP Output
  influxdb              InfluxDB Time Series
  nats                  NATS Server
  null                  Throws away events
  plot                  Generate data file for GNU Plot
  file                  Generate log file
  stdout                Prints events to STDOUT
  td                    Treasure Data
  flowcounter           FlowCounter

Filters
  grep                  grep events by specified field values
  stdout                Filter events to STDOUT
  kubernetes            Filter to append Kubernetes metadata

Internal
 Event Loop  = epoll
 Build Flags =  JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB **FLB_HAVE_BUFFERING** FLB_HAVE_FLUSH_LIBCO FLB_HAVE_FORK FLB_HAVE_PROXY_GO FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_SETJMP FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

**Comment by edsiper** [comment]
Buffering is enabled. Note that buffering is a backup system to store records while they are sending to the destination. 

Just append -b /path/to/ flag to your command line with a directory where fluent bit can write to

**Comment by wittenst** [comment]
OK I follow now, thank you, I was able to get it to work.  It doesn't seem to keep the files though if it can't reach a destination.  For instance, I changed the server it was sending to (basically it was a box where fluentd wasn't running) and I was hoping it would hold the files until it could send the data in them.  It looks like it deletes them if they can't be sent after a few seconds.  Is there an option to hold the data until fluentd (or whatever process we're sending to) comes back?

**Comment by edsiper** [comment]
In the output section you can set Retry_Limit to false, e.g:

```
[OUTPUT]
    Name es
    Match *
    Retry_Limit False
```

that will let Fluent Bit retry until it succeed

**Comment by edsiper** [comment]
Setting the main question as answered. 

Closing as FIXED.

**Comment by Globegitter** [comment]
@edsiper just running into this also, can the buffering behaviour also be set in the config file, or just on the command line? Would be nice to have something about that in the docs, I could not see anything. Would also be happy to add it myself once I understand this fully.

I am also not seeing much documentation about the `Retry_Limit`. Does it also work for the HTTP plugin? And can it be just set to `False`, or also to an integer, let's say `10` so it gives up after 10 tries?

**Comment by garbetjie** [comment]
@Globegitter I'm commenting here as I had the same questions you regarding `Retry_Limit`, and hopefully this comment will help anyone else 😊.

After digging through the source code (disclaimer: I'm not a C developer _at all_), it appears as if `Retry_Limit` is a setting that applies to all outputs. [As seen here](https://github.com/fluent/fluent-bit/blob/0.14/src/flb_output.c#L365-L380), it can have a value of `off`, `false` or `-1` to disable the retry limit (ie: retry forever). Otherwise, it'll make the given number of attempts at delivery (how long this is would be determined by your flush interval in the output - `Retry_Limit 10` with `Flush 1` will ensure it only hangs around for 10 seconds).

I also tested this in one of my own projects, and it buffered and kept retrying everything, functioning as expected.

I hope this helps, if you haven't yet managed to find out any more about this.

**Comment by edsiper** [comment]
Retry logic is documented in the Scheduler section:

https://docs.fluentbit.io/manual/configuration/scheduler
