### ISSUE TITLE
Fluent Bit mishandles japanese characters

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#3280]
## Bug Report

Here's my config:

```
[INPUT]
    Name        tail
    Path        /home/ec2-user/config/logs/japan.log
    Read_from_Head On

[OUTPUT]
    Name stdout
    Match *
    Format json_lines
```

And my log file:
(*Content Warning: I can't read Japanese so I don't know what this means... I got it from a user who reported this issue*)
```
someasciiilogline
あいうえお
asciiagain
```

When the format is json, these characters aren't handled properly:

```
{"date":1616654459.55218,"log":"someasciiilogline"}
{"date":1616654459.552188,"log":"\u3042\u3044\u3046\u3048\u304a"}
{"date":1616654459.55219,"log":"asciiagain"}
```

But when I change the format to `msgpack` we get:

```
[0] tail.0: [1616654319.474995365, {"log"=>"someasciiilogline"}]
[1] tail.0: [1616654319.475004612, {"log"=>"あいうえお"}]
[2] tail.0: [1616654319.475007521, {"log"=>"asciiagain"}]
```

**Comment by PettitWesley** [comment]
I'm pretty sure this function is where the problem is: https://github.com/fluent/fluent-bit/blob/master/src/flb_utils.c#L605

**Comment by nokute78** [comment]
The point is this else case.
https://github.com/fluent/fluent-bit/blob/master/src/flb_utils.c#L710
In this else case, fluent-bit encode UTF8 bytestring to Unicode string.

https://unicode.scarfboy.com/?s=U%2B3042
UTF8 byte string of `あ` is `0xe38182`. Unicode string is `\u3042` in ascii.
Fluent-bit converts `0xe38182` -> `0x5c7533303432` (= `\u3042` in ascii).

We should  print `0xe38182`.

**Comment by nokute78** [comment]
@PettitWesley Could you check if #3284 addresses  your customer issue?
I only tested using out_stdout and didn't test out_s3.

**Comment by nigels-com** [comment]
> あいうえお

@PettitWesley I am not fluent in Japanese.  But I know enough to recognise these as the five "base vowels" in Japanese - a, e, i, e, o.  Seems entirely appropriate for testing UTF handing of Japanese hiragana (phonetic glyphs) in particular.

**Comment by PettitWesley** [comment]
@nigels-com Thanks and cool!

**Comment by PettitWesley** [comment]
@nokute78 It works, thanks!
