### ISSUE TITLE
out_kinesis_streams:  Add KPL aggregation support to the kinesis_streams output.

### ISSUE THREAD

**Issue by zackwine** [fluent/fluent-bit#3293]
**Is your feature request related to a problem? Please describe.**

Sending smaller records/logs via kinesis PUT records is less efficient than using the KPL (Kinesis Producer Library) format.  The KPL format aggregates up to 1MB of records into a protobuf format only counting as single record to Kinesis thus increasing the throughput per Kinesis shard for smaller records.

**Describe the solution you'd like**

Add an option to the `kinesis_streams` output to support the KPL format described here:

https://github.com/awslabs/amazon-kinesis-producer/blob/master/aggregation-format.md

When this new option is enabled records will be posted to kinesis in the `protobuf` format described in the link above.

**Describe alternatives you've considered**

Continuing to use the Golang kinesis output that supports KPL is the most likely alternative.  Early testing of the native C implementation (kinesis_streams) of kinesis shows a decent improvement in CPU usage at scale, so this feature would allow an apples to apples comparison in performance between the golang and C implementations.

**Additional context**

Using the KPL format in combination with a Firehose kinesis consumer is far cheaper than using the current PUT records method.  This is a non-starter for moving from the golang implementation to the C implementation of the kinesis output for our company.

**Comment by stephanebruckert** [comment]
Would also like to see the `aggregation` field inside `kinesis_streams`
