### ISSUE TITLE
Add ability to set object suffixes in S3 stored data

### ISSUE THREAD

**Issue by adam-olema** [fluent/fluent-bit#3296]
**Is your feature request related to a problem? Please describe.**

Some tools rely on certain suffixes added to object stored in S3.  For example, AWS Athena requires that gzip compressed json files in S3 end with `.json.gz` suffix and will refuse to parse them correctly otherwise.  Currently, the S3 output, especially when using put_object has no suffixes of any kind added.   There does not appear to be any option to set a suffix.

**Describe the solution you'd like**

1) Allow setting of a suffix based on content (.json, .csv, etc)
2) Automatically set .gz suffix as well when using gzip compression.

OR

1) A config option to always add a specified suffix to all uploaded objects.

**Describe alternatives you've considered**

The only other alternative is some kind of cron job to rename files on S3, which is less than ideal.

**Additional context**

Mainly I wan to use a canned tool and queries to do some log analysis (AWS Athena), but Athena will not recognize the file formats without suffxes.

**Comment by NeckBeardPrince** [comment]
Agreed. Currently, all the logs get uploaded to S3 with a `-objectRandonID` which means files are named without a valid file extension. Confusing decision to force a random suffix that would break some automated jobs that would scrap that data based on file type.

**Comment by zhonghui12** [comment]
Hi @adam-olema @NeckBeardPrince, we have merged the code to support key suffix and the feature will be available in next release. After it is released, we will update the official doc for more guidance.

Thanks for the suggestion.

**Comment by adam-olema** [comment]
Thank you for addressing so quickly!

**Comment by adam-olema** [comment]
Could you point to the merged code?  I may want to build early and use it, depending on when you think the next release will be.

**Comment by PettitWesley** [comment]
@adam-olema The 1.7 branch has it. Here are the docs: https://github.com/fluent/fluent-bit-docs/pull/483/files

**Comment by zhonghui12** [comment]
Hello @adam-olema @NeckBeardPrince, the feature is released now: https://fluentbit.io/announcements/v1.7.3/. And we also updated the S3 docs: https://github.com/fluent/fluent-bit-docs/pull/504/files.

**Comment by adam-olema** [comment]
Working great!  Thank you!
