### ISSUE TITLE
Add Couchbase logo for in-production usage

### ISSUE THREAD

**Issue by patrick-stephens** [fluent/fluent-bit#3300]
![CB logo H_R_B_B_W](https://user-images.githubusercontent.com/6388272/112868778-589b0700-90b4-11eb-8bbb-a0da48d33664.png)

Please can you add the attached logo to the in-production usage of Couchbase.
Feel free to link to the repo we're using to keep the customisation in: https://github.com/couchbase/couchbase-operator-logging.

@agup006 I know you asked for SVG but I got given a PNG plus Github won't let me update the SVG!

**Comment by patrick-stephens** [comment]
![CB logo Red with Black](https://user-images.githubusercontent.com/6388272/113112363-01ef1380-9201-11eb-8746-757c74cf5440.png)
![CB logo Red with White Stacked](https://user-images.githubusercontent.com/6388272/113112366-0287aa00-9201-11eb-9298-f1b6d3332be8.png)
![CB logo Red with White](https://user-images.githubusercontent.com/6388272/113112372-03204080-9201-11eb-9381-224af0995e32.png)

Some additional versions in case these are easier to use.

**Comment by agup006** [comment]
Thanks @patrick-stephens , I'll add the logo

**Comment by l2dy** [comment]
> I know you asked for SVG but I got given a PNG plus Github won't let me update the SVG!

You can zip the file and upload the .zip archive.
