### ISSUE TITLE
Output ES fails to flush chunk with status 0

### ISSUE THREAD

**Issue by konradasb** [fluent/fluent-bit#3301]
## Bug Report

**Describe the bug**
Constantly (but not always) fails to flush chunks with `HTTP status=0` from ES in Kubernetes. Debug/Trace logs don't show anything specific, even with `Trace_Error On`

```
[fluent-bit-5gqwz] [2021/03/29 21:53:42] [ warn] [engine] failed to flush chunk '1-1617054818.967282961.flb', retry in 9 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0) 
[fluent-bit-mw7sw] [2021/03/29 21:54:03] [ warn] [engine] failed to flush chunk '1-1617054839.820871907.flb', retry in 7 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0) 
[fluent-bit-5gqwz] [2021/03/29 21:55:32] [error] [output:es:es.0] HTTP status=0 URI=/_bulk 
[fluent-bit-5gqwz] [2021/03/29 21:55:32] [ warn] [engine] failed to flush chunk '1-1617054927.935218441.flb', retry in 10 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0) 
[fluent-bit-2z84q] [2021/03/29 21:55:47] [error] [output:es:es.0] HTTP status=0 URI=/_bulk 
[fluent-bit-2z84q] [2021/03/29 21:55:47] [ warn] [engine] failed to flush chunk '1-1617054942.558870892.flb', retry in 10 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0) 
[fluent-bit-mw7sw] [2021/03/29 21:56:23] [error] [output:es:es.0] HTTP status=0 URI=/_bulk 
[fluent-bit-mw7sw] [2021/03/29 21:56:23] [ warn] [engine] failed to flush chunk '1-1617054978.505299097.flb', retry in 11 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0) 
```

**Your Environment**
* Version used: 1.7.0 and 1.7.1
* Configuration:
Tried to remove everything and leave only `in_tail` and `out_es`. Results are the same.
```
  config:
    service: |
      [SERVICE]
          Flush         5
          Grace         120
          Log_Level     info
          Daemon        off
          Parsers_File  parsers.conf
          Parsers_File  custom_parsers.conf
          HTTP_Server   On
          HTTP_Listen   0.0.0.0
          HTTP_PORT     2020
    customParsers: |
        [PARSER]
            Name        CRI
            Format      regex
            Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    filters: |
        # -- Applied to All --
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Merge_Log           Off
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
        [FILTER]
            Name                nest
            Match               kube.*
            Operation           lift
            Nested_Under        kubernetes
        # -- Ingress Nginx --
        [FILTER]
            Name                rewrite_tag
            Match               kube*ingress-nginx*
            Rule                $stream ^(stderr)$  ingress-nginx.error false
            Rule                $stream ^(stdout)$  ingress-nginx.access false
        [FILTER]
            Name                parser
            Match               ingress-nginx.access
            Parser              json
            Key_Name            log
    inputs: |
        [INPUT]
            Name                tail
            Tag                 kube.*
            Path                /var/log/containers/*.log
            DB                  /var/log/flb_kube_containers.db
            Parser              CRI
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
            Refresh_Interval    10
            Skip_Long_Lines     On
        # -- SystemD --
        [INPUT]
            Name                systemd
            Alias               systemd-kubelet
            Tag                 systemd-kubelet
            Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
            Path                /var/log/journal
            DB                  /var/log/kubelet.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
        [INPUT]
            Name                systemd
            Alias               systemd-kube-node-installation
            Tag                 systemd-kube-node-installation
            Systemd_Filter      _SYSTEMD_UNIT=kube-node-installation.service
            Path                /var/log/journal
            DB                  /var/log/kube-node-installation.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
        [INPUT]
            Name                systemd
            Alias               systemd-kube-node-configuration
            Tag                 systemd-kube-node-configuration
            Systemd_Filter      _SYSTEMD_UNIT=kube-node-configuration.service
            Path                /var/log/journal
            DB                  /var/log/kube-node-configuration.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
        [INPUT]
            Name                systemd
            Alias               systemd-kube-logrotate
            Tag                 systemd-kube-logrotate
            Systemd_Filter      _SYSTEMD_UNIT=kube-logrotate.service
            Path                /var/log/journal
            DB                  /var/log/kube-logrotate.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
        [INPUT]
            Name                systemd
            Alias               systemd-node-problem-detector
            Tag                 systemd-node-problem-detector
            Systemd_Filter      _SYSTEMD_UNIT=node-problem-detector.service
            Path                /var/log/journal
            DB                  /var/log/node-problem-detector.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
        [INPUT]
            Name                systemd
            Alias               systemd-kube-container-runtime-monitor
            Tag                 systemd-kube-container-runtime-monitor
            Systemd_Filter      _SYSTEMD_UNIT=kube-container-runtime-monitor.service
            Path                /var/log/journal
            DB                  /var/log/kube-container-runtime-monitor.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
        [INPUT]
            Name                systemd
            Alias               systemd-kubelet-monitor
            Tag                 systemd-kubelet-monitor
            Systemd_Filter      _SYSTEMD_UNIT=kubelet-monitor.service
            Path                /var/log/journal
            DB                  /var/log/kubelet-monitor.db
            Mem_Buf_Limit       5MB
            Buffer_Max_Size     1MB
    outputs: |
        [OUTPUT]
            Name                   gelf
            Match                  systemd*
            Gelf_Short_Message_Key MESSAGE
            Gelf_Host_Key          _HOSTNAME
            Host                   ${GRAYLOG_HOST}
            PORT                   ${GRAYLOG_PORT}
            Mode                   udp
        [OUTPUT]
            Name                   gelf
            Match                  kube*
            Gelf_Short_Message_Key log
            Gelf_Host_Key          host
            Host                   ${GRAYLOG_HOST}
            PORT                   ${GRAYLOG_PORT}
            Mode                   udp
        # -- Ingress Nginx --
        [OUTPUT]
            Name                   gelf
            Match                  ingress-nginx.error
            Gelf_Short_Message_Key log
            Gelf_Host_Key          host
            Host                   ${GRAYLOG_HOST}
            PORT                   ${GRAYLOG_PORT}
            Mode                   udp
        [OUTPUT]
            Name                   es
            Match                  ingress-nginx.access
            Index                  nginx
            Logstash_Format        On
            Host                   ${ES_HOST}
            Http_User              ${ES_USERNAME}
            Http_Passwd            ${ES_PASSWORD}
            Logstash_Prefix        nginx
            Logstash_DateFormat    %Y%m%d
            Retry_Limit            5
            Type                   _doc
            Port                   443
            Tls                    On
            Buffer_Size            50M
```

**Comment by nokute78** [comment]
Would you testing `Log_Level     trace` to enable debug/trace log?

**Comment by konradasb** [comment]
This is all I see with `trace` mode and `Trace_Error On`
```
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [debug] [output:es:es.0] HTTP Status=0 URI=/_bulk 
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [error] [output:es:es.0] HTTP status=0 URI=/_bulk 
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [debug] [socket] could not validate socket status for #46 (don't worry) 
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [debug] [input:tail:tail.0] inode=522249 events: IN_MODIFY  
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [debug] [out coro] cb_destroy coro_id=3 
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [debug] [retry] new retry created for task_id=0 attempts=1 
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [ warn] [engine] failed to flush chunk '1-1617087699.450368073.flb', retry in 9 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0) 
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [debug] [input:tail:tail.0] inode=522249 events: IN_MODIFY  
```

**Comment by konradasb** [comment]
I think it should show some more verbose output here
```
[fluent-bit-4fm8g] [2021/03/30 07:01:44] [error] [output:es:es.0] HTTP status=0 URI=/_bulk 
```
It's hard to understand what's happening behind the scenes as some of the logs are being sent and delivered with 200 status,
but some of them fail like this. This happens at least 40 times in 5 minutes, with around 200-400 log entries being sent to ES successfully

**Comment by staniondaniel** [comment]
This seems similar to the problem that i am having here: https://github.com/fluent/fluent-bit/issues/3299 

I seem to hit the max  request size configured in AWS for ES installation.  Can you enable this option in ElasticSearch output plugin and see if you see the same error? 
```
    [OUTPUT]
        Name  es
        Match sendtoes.*
        Host  ${FLUENT_ELASTICSEARCH_HOST}
        Port  ${FLUENT_ELASTICSEARCH_PORT}
        Buffer_Size False
        Trace_Error On

```

**Comment by konradasb** [comment]
Enabling `Buffer_Size False` solved the issues (monitored with `kubetail` for at least 30-40 minutes - not sure if long term), but memory usage jumped from 1G~ to 70-80G.

**Comment by konradasb** [comment]
Increasing Buffer_Size to 1G still shows these errors, disabling Buffer_Size increases memory usage to an absurd amount, but doesn't show any errors then. I need a  way to find out why it's failing with 0 status. We are running Elasticsearch behind proxies and it seems that all of the requests from FluentBit were with 200 status from Elasticsearch proxy perspective.

**Comment by staniondaniel** [comment]
> Increasing Buffer_Size to 1G still shows these errors, disabling Buffer_Size increases memory usage to an absurd amount, but doesn't show any errors then. I need a way to find out why it's failing with 0 status. We are running Elasticsearch behind proxies and it seems that all of the requests from FluentBit were with 200 status from Elasticsearch proxy perspective. No errors in datanodes too :(

O partially fixed my problem by rasing my the filter Emitter_Mem_Buf_Limit to close to 100M but it still fails sometimes because the chunksize is bigger . Try to play with these buffer sizes and limit and see if it helps you.

```   
 [FILTER]
        Emitter_Mem_Buf_Limit 90MB
        Name rewrite_tag
        Match kube.*

```

Also try to run this command
```
kill -CONT `pidof fluent-bit`
```


 as instructed here:

https://docs.fluentbit.io/manual/administration/dump-internals-signal

when the memory usage is high , from the host level to see exactly where the memory is used

**Comment by atheriel** [comment]
I am observing this exact error behaviour with the Splunk plugin as well:

```
[2021/04/06 21:30:06] [ warn] [output:splunk:splunk.0] http_status=0
```

From looking at the source, `flb_http_do()` can return successfully if it fills its internal buffer before reading the whole request. The Elasticsearch plugin doesn't explicitly handle this case (which can result in a broken response object) and there is no existing logging for when this occurs (though I added it in #3339, which you can try to see if it surfaces in your environment).

This is probably why setting `Buffer_Size false` fixes things, but that's not a great solution if you're hitting OOM issues. Try something more reasonable like `32K` instead; the default is `4K`.

However, I suspect there is a serious underlying bug that is causing the response buffer to explode and OOM your process -- I am also seeing the same thing for Splunk in my testing.

**Comment by marckamerbeek** [comment]
Same here....struggling with this for over a month now. Played with all kind of memory settings in the tail input and the elastic output. This http status=0 is telling me nothing.  It seems te be better with version 1.7.3.

@atheriel I've tried so many values for the buffer size. Its even on 25Mb right now. Setting it on False resulted in OOM Killed.

**Comment by atheriel** [comment]
@marckamerbeek I think it's just less frequent with 1.7.3, likely due to some of the connection management fixes. I originally thought the source was bad behaviour on the Splunk server side, but since it manifests with Elasticsearch as well it's almost certainly a Fluent Bit issue.

**Comment by marckamerbeek** [comment]
@atheriel Yes, I saw the changes in 1.7.3. One of them was something with context reset in case of an error. 

I was thinking, I have the buffer_size set to 25M. I can't imagine that Elastic would send a response bigger then that. 
BTW,,,that extra log line you added is a big improvement for people to understand what is going on!

**Comment by konradasb** [comment]
Tried 1.7.3, same errors appearing at the same rate. Setting Buffer_Size to 2G doesn't even solve it fully. I can't imagine getting response from Elasticsearch bigger than 25M. Need to figure out what that Status=0 really means

**Comment by atheriel** [comment]
I've played around with an instrumented build and observed various things:

* It's possible for the HTTP status to be zero because it's unparseable -- specifically, the source uses `atoi()` -- but `flb_http_do()` will still return successfully. Under this scenario what I believe is happening is that the buffer is filled with junk but Fluent Bit keeps looking for the end of the HTTP header block and reading more bytes if it can't find it; this never occurs so eventually the buffer is filled (or not and we OOM, if there is no size limit). Once the buffer is filled `flb_http_do()` will return successfully even though the response object is totally invalid. I intend to submit a PR that will bail early if the status code is invalid instead of waiting to fill the whole buffer, but that doesn't answer the "why are we reading in junk" question.

* It's possible for the HTTP status to be normal but the buffer to be filled anyway. I'm not sure what is happening here, it seems that Fluent Bit can't find the end of the header block.

**Comment by marckamerbeek** [comment]
@atheriel Maybe good to mention...i have a haproxy in between fluentbit and elastic as a load balancer. Are you happend to have one aswell maybe? Tomorrow I will build one myself with some debug lines aswell.

**Comment by konradasb** [comment]
We use Nginx for Elasticsearch as a proxy and a loadbalancer, all requests from Fluentbit to that proxy succeeded with 200 from logs

**Comment by atheriel** [comment]
Further questions for the crowd:

* Is everyone using TLS or does this happen even without it?
* OpenSSL or mbedTLS build?
* Is anyone seeing this issue on HTTP 1.0 connections or with keep-alive disabled somehow?

**Comment by marckamerbeek** [comment]
@atheriel  I'm sorry....i thought I already answer your question. But not...

- Yes...using TLS
- OpenSSL
- With keep-alive on

This is my config:
`[SERVICE]
    Flush 1
    Daemon Off
    Log_Level {{ fluentbit_log_level }}
    Parsers_File custom_parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020

[INPUT]
    Alias k8s-platform-{{ environment_name }}
    Buffer_Chunk_Size 2M
    Buffer_Max_Size 10M
    DB /var/log/containers/fluentbit-k8s-platform.db
    Exclude_Path ****************
    Mem_Buf_Limit 50MB
    Name tail
    Parser docker
    Docker_Mode On
    Path /var/log/containers/*.log
    Refresh_Interval 5
    Skip_Long_Lines On
    Tag k8s-platform.*

[FILTER]
    Alias k8s-platform-{{ environment_name }}
    K8S-Logging.Parser On
    K8S-Logging.exclude On
    Kube_Tag_Prefix k8s-platform.var.log.container.
    Kube_URL https://${KUBERNETES_SERVICE_HOST}:443
    Match k8s-platform*
    Merge_Log On
    Name kubernetes
    tls.verify Off

[OUTPUT]
    Alias k8s-platform-{{ environment_name }}
    HTTP_Passwd {{ fluentbit_elasticsearch_password }}
    HTTP_User {{ fluentbit_elasticsearch_username }}
    Host {{ fluentbit_elasticsearch_host }}
    Include_Tag_Key On
    Logstash_DateFormat %Y-%m-%d
    Logstash_Format On
    Logstash_Prefix fluentbit-{{ fluentbit_image_version }}-{{ environment_name }}-k8s-platform
    Match k8s-platform*
    Name es
    Port {{ fluentbit_elasticsearch_port }}
    Replace_Dots On
    Generate_ID On
    Retry_Limit 10
    Time_Key flb_ts
    tls On
    tls.verify Off
    Trace_Error On
    net.keepalive On
    Buffer_Size 25M
    Suppress_Type_Name On`

**Comment by marckamerbeek** [comment]
I turned off the net.keepalive and I have not seen any errors for a while now.

**Comment by marckamerbeek** [comment]
Found the culprit! At least in my case. I have a HAProxy in front of Elasticsearch with version 1.8.24 and its not supporting keepalive connections. It only supports HTTP 2 keepalive from version 1.9. 

@atheriel & @konradasb ... I should definitely check all the component in the chain on support of keepalive connections.

**Comment by konradasb** [comment]
@marckamerbeek we use nginx instead of haproxy, but it seems backends(upstreams) don't have keepalive enabled as well. Turning off `net.keepalive` solved this issue. Still, I would like to see more detailed logs about what's happening here from Fluentbit side.

**Comment by brsolomon-deloitte** [comment]
Still an issue, should be re-opened. Seeing this with fluent-bit 1.8.12 from the https://fluent.github.io/helm-charts Helm chart version 0.19.19 writing to Elasticsearch.

**Comment by lifeofmoo** [comment]
Also seeing this with fluent-bit v1.9.3 and AWS Opensearch version 1.1 - initial set of of logs get sent to the correct index in OpenSearch and then I just see lines of _flush chunk with status 0_

**Comment by lifeofmoo** [comment]
> I saw the same issue with fluent-bit v1.9.3 and AWS Opensearch version 1.2 ....... even though I turned off net.keepalive, also set Buffer_Size False, but cannot solve the issue. just like @lifeofmoo mentioned, initially everything went well in OpenSearch then the issue of "failed to flush chunk" came out... I think the issue should be re-opened!

Issue now fixed as per:

https://github.com/fluent/fluent-bit/issues/5438

**Comment by terrificdm** [comment]
> > I saw the same issue with fluent-bit v1.9.3 and AWS Opensearch version 1.2 ....... even though I turned off net.keepalive, also set Buffer_Size False, but cannot solve the issue. just like @lifeofmoo mentioned, initially everything went well in OpenSearch then the issue of "failed to flush chunk" came out... I think the issue should be re-opened!
> 
> Issue now fixed for me as per:
> 
> #5438

Thanks a lot, I will try!

**Comment by rafamiga** [comment]
Just FYI, in my deployment I was chasing kind of the same problem:

`fluentbit-fbit-1  | [2022/09/22 18:17:51] [ warn] [engine] failed to flush chunk '1-1663870669.19806325.flb', retry in 6 seconds: task_id=0, input=tail.0 > output=es.0 (out_id=0)
`
Lots of these messages appeared in the log. But the data went through, sometime later I always was getting:

`fluentbit-fbit-1  | [2022/09/22 18:17:56] [ info] [engine] flush chunk '1-1663870669.19806325.flb' succeeded at retry 1: task_id=0, input=tail.0 > output=es.0 (out_id=0)`

I didn't find a clue on what to do in this situation – no changes to configuration seemed to work, Google didn't help either. Then I tried:

```
[OUTPUT]
  Match app.log
  Name es
  Host xxxx.xxx
  Port xxxx
  Replace_Dots On
  Logstash_Format True
  Logstash_Prefix app.log
  Buffer_Size 128K
#  Generate_ID On
  Suppress_Type_Name On
  Workers 4
```

When I commented out **Generate_ID** out it fixed the problem, no more failed-then-succeeded cases.

The funny thing is that the records in Elastic do have **_id** with **Generate_ID** commented out. Anyway, this was a strange behaviour since all logs went through only at the second try. Turning on **Trace_Error** didn't help since it showed tons of chunks with no failures and the output was cut in a middle of JSON output – I'd guess at a 1023rd or 1024th character.

**Comment by hedeesaa** [comment]
By adding `Trace_Error On` to the es OUTPUT , I saw the problem was mapping conflict in es. After solving the issue the error got solved completely.

**Comment by dko-slapdash** [comment]
> When I commented Generate_ID out it fixed the problem

@atheriel I think I found the repro usecase, how generate_id affects this all; commented here:
https://github.com/fluent/fluent-bit/issues/2664#issuecomment-1415142230
