### ISSUE TITLE
id_key ElasticSearch Support

### ISSUE THREAD

**Issue by cocheok** [fluent/fluent-bit#3303]
**Is your feature request related to a problem? Please describe.**
I need to set up my keys as the _id keys on ElasticSearch and I can't do it with this agent. FluentD supports it https://github.com/uken/fluent-plugin-elasticsearch#id_key

**Describe the solution you'd like**
I would like to add the same solution as fluentD offers at https://github.com/uken/fluent-plugin-elasticsearch#id_key

**Describe alternatives you've considered**
With the following configuration

id_key $.nested.request_id
and the following nested record

{"nested":{"name": "Johnny", "request_id": "87d89af7daffad6"}}

so the config file must be 

[OUTPUT]
    Name  es
    Match test
    Host  elasticsearch
    Port  9200
    Index test_index
    **id_key $.nested.request_id**

**Comment by edsiper** [comment]
Fixed in #3320
