### ISSUE TITLE
no output when installed on Windows core

### ISSUE THREAD

**Issue by andreabolandrina** [fluent/fluent-bit#3305]
## Bug Report

**Describe the bug**
I'm not sure whether this is a bug or either the docs or myself are missing something.

I installed fluent-bit on a Windows core K8s worker node and I get no output from the following command: "C:\fluent-bit\bin\fluent-bit.exe -i dummy -o stdout"

Furthermore after creating a service (with svc.exe) and try to run it I get:
% sc.exe start fluent-bit
[SC] StartService FAILED 1053:
The service did not respond to the start or control request in a timely fashion.

**To Reproduce**
Run a Windows core kubernetes VM (I'm on AWS and use exactly this one: "Windows_Server-2019-English-Core-EKS_Optimized-1.18-2021.02.10")
the execute these exact commands:
`
#start a powershell prompt
powershell
New-Item -Type Directory -Path /local
New-Item -Type Directory -Path /fluent-bit
cd /local

Invoke-WebRequest -Uri "https://fluentbit.io/releases/1.7/td-agent-bit-1.7.0-win64.zip" -OutFile td-agent-bit.zip
Expand-Archive -Path td-agent-bit.zip -Destination /local/fluent-bit
Move-Item -Path /local/fluent-bit/*/* -Destination /fluent-bit/

Invoke-WebRequest -OutFile vc_redist.x64.exe -Uri https://aka.ms/vs/15/release/vc_redist.x64.exe
Start-Process /local/vc_redist.x64.exe -ArgumentList '/install', '/quiet', '/norestart' -NoNewWindow -Wait
Copy-Item -Path /Windows/System32/msvcp140.dll -Destination /fluent-bit/bin/
Copy-Item -Path /Windows/System32/vccorlib140.dll -Destination /fluent-bit/bin/
Copy-Item -Path /Windows/System32/vcruntime140.dll -Destination /fluent-bit/bin/

sc.exe create fluent-bit binpath= "\fluent-bit\bin\fluent-bit.exe -c \fluent-bit\conf\fluent-bit.conf"
`

**Expected behavior**
I would expect to see some output (possibly with some error) or the service to start.

**Screenshots**
![fluent-bit_on_Windows-core](https://user-images.githubusercontent.com/922382/113054176-05eb4900-91a1-11eb-87d5-9291262947cc.png)

**Your Environment**
* Version used: 1.7.0
* Configuration: left as default
* Environment name and version AWS EKS v1.18
* Server type and version: "Windows_Server-2019-English-Core-EKS_Optimized-1.18-2021.02.10" Virtual Machine
* Operating System and version: Windows Server 2019 Core EKS Optimized 1.18-2021.02.10
* Filters and plugins: nothing applied yet

**Additional context**
I just need to collect the logs from the Windows worker nodes (the linux ones already work, albeit with v1.13 due to some other bug)

**Comment by fujimotos** [comment]
There is  an outstanding bug of requiring OpenSSL DLLs in v1.7.x series.
This is fixed in HEAD by #3193, but the fix is not yet included in the official release.

v1.6 series is not affected, so please use v1.6 for now.

**Comment by agup006** [comment]
This should be fixed with 1.7.3 windows release, can you retry with 1.7.3?

**Comment by andreabolandrina** [comment]
Hi,

Thank you both.

I was getting some output with 1.6.10 (which I did not get with 1.7.0) and then I saw @agup006 's message, so I continued my testing with 1.7.3.

I can report that with 1.7.3 I managed to get the docker log messages from the Windows host to ElasticSearch.

Regards,
Andrea
