### ISSUE TITLE
Splunk output plugin: Data channel is missing

### ISSUE THREAD

**Issue by ardove** [fluent/fluent-bit#3314]
**Is your feature request related to a problem? Please describe.**
I already logged this story over in the fluent-bit-docs repo, but haven't heard a response in over a week, so I'm raising it here.
https://github.com/fluent/fluent-bit-docs/issues/496

The root of this problem is based on "indexer acknowledgement" in splunk. In a perfect world, the fluent-bit plugin would support indexer acknowledgement (I haven't looked at the source, so I don't know if it does), but this is helpful because it allows splunk to indicate (to fluent-bit) that the specified index isn't correct at the time of request (so fluent bit can log an error if a bad index is used). 

When indexer acknowledgement is enabled, the `x-splunk-request-channel` header is required to be specified as an HTTP header on the request to the HEC endpoint, but there's no way to specify that as part of the splunk plugin configuration. 

**Describe the solution you'd like**
I think it'd be possible to specify a static request channel string as part of the output section for the splunk plugin. 

**Describe alternatives you've considered**
The alternative is to just disable indexer acknowledgement. The trouble here is that fluent bit will believe everything is working correctly, but logs will be mysteriously missing. 

**Additional context**
n/a

**Comment by agup006** [comment]
I took a look at the Splunk documentation and it looks like Version 8.x will need a custom header to specify channel

My thoughts is to add a new parameter like the following. @nokute78 since Splunk inherits from the out_http is this something we could add quickly?

```
splunk_request_channel <INSERT CUSTOM>
```

**Comment by nokute78** [comment]
I have no test environment, so I can test only to get fluent-bit's http request using dummy http server.
I may be able to add `X-Splunk-Request-Channel` header using configuration parameter.

By the way, fluentd's plugin supports `channel` property to support same functionality.
Is it better to support same name?
https://github.com/fluent/fluent-plugin-splunk/blob/master/README.hec.md#channel

**Comment by ardove** [comment]
Wow, these docs are far more complete than those listed on the docs site. 

Are there other places where that's the case? This would've saved me hours had I known about it.

**Comment by agup006** [comment]
@ardove note that is for the Fluentd Splunk plugin not fluent bit

@nokute78 +1 to using the same as Fluentd channel parameter

**Comment by nokute78** [comment]
I created PR https://github.com/fluent/fluent-bit/pull/3318
Would you test it ? 
I don't have splunk account so I tested dummy http server.

**Comment by ardove** [comment]
@nokute78 how do I test it? I need to somehow access a copy of fluent-bit that has your fix in it? Plus, I looked at the PR and it looks like you already tested it..

**Comment by nokute78** [comment]
@ardove This is the first time I use splunk :)
Is [the test](https://github.com/fluent/fluent-bit/pull/3318#issuecomment-813123677) what you want?

If it is not enough , you can build and test using following commands.
```
git clone https://github.com/nokute78/fluent-bit.git
cd fluent-bit/build
git checkout fix_3314
cmake .. && make
bin/fluent-bit -c /your/config/path/test.conf
```
