### ISSUE TITLE
Pass ENV to LUA script

### ISSUE THREAD

**Issue by olegtrautvein** [fluent/fluent-bit#3322]
**Is your feature request related to a problem? Please describe.**
Hello. 
I need access ENV param in the  lua script, which I use in fluentbit config files.
My config file example:
```
[FILTER]
    Name             kubernetes
...
    Merge_Log_Key    ${PARSED_JSON_FIELD_NAME}
```

**Describe the solution you'd like**
Ability to use ENV (os.getenv()). Now it return nil.

**Describe alternatives you've considered**
As the work around I use /tmp/param_for_lua file which read in lua script.

**Additional context**
It is fluentbit 1.7.2 in a docker.

I use lua script to convert tree-like parsed json to flat list (a->b->c being a.b=c), else Elasticsearch discard some records.
For example,  the second record will be discarded by Elasticsearch:
Record 1: { "status": "OK" }
Record 2: {"status": { "code": 200, "desc": "OK } }
I cannot write to different indices by some reason (lot of different applications in the k8s cluster)

**Comment by nokute78** [comment]
Hmm, I tested the configuration and script.
It can get environment variable `SHELL`.

a.conf:
```
[INPUT]
    Name dummy

[FILTER]
    Name lua
    Match *
    script test.lua
    call test

[OUTPUT]
    Name null
```

test.lua:
```lua
function test(tag, timestamp, record)
         print(os.getenv("SHELL"))
         return 0, timestamp, record
end
```

output log is here. `/bin/bash` is environment variable `SHELL`.
```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.8.0
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/04/05 08:47:04] [ info] [engine] started (pid=24159)
[2021/04/05 08:47:04] [ info] [storage] version=1.1.1, initializing...
[2021/04/05 08:47:04] [ info] [storage] in-memory
[2021/04/05 08:47:04] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/05 08:47:04] [ info] [sp] stream processor started
/bin/bash
/bin/bash
^C[2021/04/05 08:47:06] [engine] caught signal (SIGINT)
[2021/04/05 08:47:06] [ warn] [engine] service will stop in 5 seconds
^C[2021/04/05 08:47:07] [engine] caught signal (SIGINT)
taka@locals:~/git/fluent-bit/build/3322$ 
```

**Comment by nokute78** [comment]
I also tested docker image.`SHELL` is not defined in the docker image.
On the other hand I can get another environment variable `HOME`.
Would you check if the environment variable is set or not?

```lua
function test(tag, timestamp, record)
         print(os.getenv("HOME"))
         return 0, timestamp, record
end
```

output is 
```
$ sudo docker run   -v ~/git/fluent-bit/build/3322:/a  -it --rm fluent/fluent-bit:1.7.2 /fluent-bit/bin/fluent-bit -c /a/a.conf
Fluent Bit v1.7.2
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/04/05 00:07:33] [ info] [engine] started (pid=1)
[2021/04/05 00:07:33] [ info] [storage] version=1.1.1, initializing...
[2021/04/05 00:07:33] [ info] [storage] in-memory
[2021/04/05 00:07:33] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/05 00:07:33] [ info] [sp] stream processor started
/root
/root
/root
^C[2021/04/05 00:07:36] [engine] caught signal (SIGINT)
[2021/04/05 00:07:36] [ warn] [engine] service will stop in 5 seconds
^C[2021/04/05 00:07:36] [engine] caught signal (SIGINT)
```

**Comment by olegtrautvein** [comment]
Hello.
Thank you for research.
It was my mistake, I didn't uppercased the variable name.
