### ISSUE TITLE
Fluent-bit windows support for [SAC] Windows Server, version 2004

### ISSUE THREAD

**Issue by Aqilmirza** [fluent/fluent-bit#3325]
Could anyone confirm whether fluent-bit supports Windows Server 2004 or not as [dockerfile.windows](https://github.com/fluent/fluent-bit/blob/master/dockerfiles/Dockerfile.windows) has ltsc2019 mentioned.

Use-case: EKS recommends using Windows 2004 as it has fixes on HNS Load balancer Port exhaustion.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/common-problems

We want to run fluent-bit pod on windows 2004 for logging

**Comment by fujimotos** [comment]
> Could anyone confirm whether fluent-bit supports Windows Server 2004 or not as dockerfile.windows has ltsc2019 mentioned.

@Aqilmirza If you mean "Windows 10 version 2004", it should work.

If you mean a very old Windows distribution released >15 years ago,
Fluent Bit probably won't work with it. The oldest release on which I tested
Fluent Bit is Windows Server 2012.
