### ISSUE TITLE
centos6.9 doen't work well

### ISSUE THREAD

**Issue by AlenJun** [fluent/fluent-bit#334]
i build fluent-bit from source on centos6.9, fluent-bit release is v0.11.13, i found it can't work well, here some information for it.
```
Fluent-Bit v0.11.13
Copyright (C) Treasure Data

Output plugin 'sls' cannot be loaded
Error: Configuration file contain errors. Aborting
```
fluent-bit.conf
```
[OUTPUT]
    Name sls
    Match *
```

**Comment by edsiper** [comment]
as described in the error, the output plugin 'sls' does not exists, the list of available destinations are here:

http://fluentbit.io/documentation/0.11/output/

Note: Please use Fluent Bit 0.11.15.

Closing this questions, feel free to open a new issue if you find another problem.
