### ISSUE TITLE
Fluent treats empty array as object when using Lua

### ISSUE THREAD

**Issue by sakno** [fluent/fluent-bit#3343]
## Bug Report

**Describe the bug**
I'm using Lua post-processing which is configured to run immediately after JSON parser. After JSON parsing, some fields in the log may have empty array as a value:
```json
{
  "field" : [ ]
}
```
Transforming JSON to Lua and back again leads to loss of type information. After running Lua script I have the following document:
```json
{
  "field": { }
}
```
This is happening because in Lua empty array is not distinguishable from empty object. To be more precisely, Lua doesn't have array type at all.

**To Reproduce**
Put trivial Lua script into pipeline after JSON parser:
```lua
function append_tag(tag, timestamp, record)
    return 2, timestamp, record
end
```

**Expected behavior**
A way to specify empty array should exist. For instance, `empty_array` global variable can be introduced for that. If set to field, fluent converter must apply `[ ]` when converting back to JSON.

**Your Environment**
Not relevant

**Comment by nokute78** [comment]
Currently, we convert LUA_TTABLE to msgpack map if the length is 0.
https://github.com/fluent/fluent-bit/blob/1e8c00240903ebc71a9092313fd8b620e10632bc/plugins/filter_lua/lua.c#L237-L245



> empty_array 

We already have `type_int_key` property to indicate the value is integer.
How about `type_array_key` ?
In this case , `type_array_key` should be  `field`.

**Comment by sakno** [comment]
@nokute78 , that's would be fine.

**Comment by nokute78** [comment]
I sent a patch https://github.com/fluent/fluent-bit/pull/3487
