### ISSUE TITLE
can't work well on Centos6.8

### ISSUE THREAD

**Issue by AlenJun** [fluent/fluent-bit#335]
I build it from source with release v0.11.13; but it can't work well on centos6.8. some information for it.
```
command: /usr/local/fluent-bit-0.11.13/bin/fluent-bit -c /usr/local/fluent-bit-0.11.13/fluent-bit.conf -R /usr/local/fluent-bit-0.11.13/parsers.conf
```
parsers.conf
```
[INPUT]
    Name tail
    Path /var/log/nginx/access.log
    Parser nginx
    Tag nginx_tail

[OUTPUT]
    Name sls
    Match *
```
stdout
```
Fluent-Bit v0.11.13
Copyright (C) Treasure Data
Output plugin 'sls' cannot be loaded
Error: Configuration file contain errors. Aborting
```

**Comment by nokute78** [comment]
"sls" output plugin is not supported.
If you try to use fluent-bit, how about using "stdout" ?

note: 'fluent-bit -h' will show the list of supported plugins.

**Comment by edsiper** [comment]
@AlenJun list of available output plugins is here:

http://fluentbit.io/documentation/0.11/output/

If you face any further issue, please open a new ticket.

Closing this as fixed.

**Comment by AlenJun** [comment]
I'm so sorry about it, the same config of fluent-bit, i build it from source on centos7.2, it can work well, but i build source on centos6.8, it can't work. i use another plugins, so i use 'sls'.
plugin is here:
https://github.com/kubeup/fluent-bit-aliyun

**Comment by edsiper** [comment]
@AlenJun thanks for confirming. Centos 6 is not a supported platform for the community edition.

**Comment by baseely** [comment]
@edsiper Do we have a package for RHEL 6 ?
