### ISSUE TITLE
Error: Invalid input type. Aborting

### ISSUE THREAD

**Issue by vishwasKadam** [fluent/fluent-bit#3382]
**Fluent-bit configuration to read http log ** 

[INPUT]
    name http
    host 0.0.0.0
    port 8888

[OUTPUT]
    type stdout
    match *

>fluent-bit -i http -p port=8888 -o stdout
Showing below error

![image](https://user-images.githubusercontent.com/38124121/115243167-41de5200-a140-11eb-98f5-df3ea4c3eca6.png)

we are using fluet- bit 1.7.3 verion, please assist.

**Comment by vishwasKadam** [comment]
referring document from 
https://docs.fluentbit.io/manual/pipeline/inputs/http

**Comment by nokute78** [comment]
Is the host windows?

in_http is not supported on Windows.
https://github.com/fluent/fluent-bit/blob/v1.7.4/cmake/windows-setup.cmake#L22
