### ISSUE TITLE
Windows: Wildcard paths without drive letter are not supported.

### ISSUE THREAD

**Issue by jeremyje** [fluent/fluent-bit#3387]
**Is your feature request related to a problem? Please describe.**

Fluent-bit configuration files do not apparently support wildcard when using UNIX like file paths.

Example:
```
[INPUT]
    Name             tail
    Alias            kube_containers
    Tag              kube_<namespace_name>_<pod_name>_<container_name>
    Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
    Path             C:\var\log\containers\*.log
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    Refresh_Interval 5
    DB               flb_kube.db
```
will work but change `Path             /var/log/containers/*.log` and Fluent-bit will report 0 files found regardless of how many files are in there.

**Describe the solution you'd like**

I'd be nice to support wildcard in UNIX style name patterns. Fluent-bit does support paths like `/var/log/my-log.txt` for single files but won't match `/var/log/*.txt`.

**Describe alternatives you've considered**

Using `C:\` instead of `/` works.

**Additional context**

**Comment by agup006** [comment]
I’m not 100% sure I follow this issue

is it that fluent bit Unix paths with wildcards do not work on windows?
