### ISSUE TITLE
fluentbit output error metric doesn't get updated when output plugin fails to connect to ES.

### ISSUE THREAD

**Issue by asherf** [fluent/fluent-bit#3389]
## Bug Report

Using the ES output plugin (using AWS ElasticSearch) when fluentbit fails to connect to the endpoint, i.e. this error shows up in the log:
` [error] [upstream] connection #64 to REFACTED.es.amazonaws.com:443 timed out after 10 seconds`

However the prometheus metric: `fluentbit_output_errors_total` values stays at zero and doesn't increment to report the error.

- Steps to reproduce the problem:
point fluentbit to a non-existant ES endpoint and see if the error counter increments (via the `api/v1/metrics/prometheus` endpoint on the builtin web server.

**Expected behavior**
The value should increment as errors occur.

**Your Environment**

* Version used: 1.7.3
* Configuration: Kuberenets (EKS) v1.19, fluent-bit 1.7.3 installing using the fluentbit helm chart
fluent bit config:
```
   [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     15MB
        Skip_Long_Lines   On

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix      kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       logJson
        K8S-Logging.Exclude On

    [OUTPUT]
        Name  es
        Match *
        Host  REFACTED.es.amazonaws.com
        Port  443
        Logstash_Format On
        Retry_Limit 3
        Type  flb_type
        Time_Key @timestamp
        Replace_Dots On
        Logstash_Prefix  prod-logs
        tls On
        AWS_Auth On
        AWS_Region  REDACTED
```

  custom_parsers.conf:
```
    [PARSER]
      Name        docker
      Format      json
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
```

**Comment by asherf** [comment]
@edsiper ping

**Comment by gchamon** [comment]
@asherf did you manage to solve this?

**Comment by asherf** [comment]
no.. but I closed the issue since I failed to get any feedback.

**Comment by gchamon** [comment]
@asherf take a look at this issue comment: https://github.com/fluent/fluent-bit/issues/1942#issuecomment-727109055

**Comment by asherf** [comment]
@gchamon the issue for me was not the AWS IAM permissions issue... I figured that out.
the problem for me that fluentbit metrics scraped by prometheus didn't show any errors, so I am not able to alert on this condition (or similar condition) when it happens from the fluentbit side.
which is unfortunate.

**Comment by gchamon** [comment]
Same here

**Comment by zhaomuzhi** [comment]
why is it issue closed?
