### ISSUE TITLE
Fails to connect to AWS STS service

### ISSUE THREAD

**Issue by rifftual** [fluent/fluent-bit#3395]
## Bug Report

**Describe the bug**
Connection to AWS STS service fails. Tested both Cloudwatch and ElasticSearch output plugins.  This started to occur with FluentBit **1.7.3**. Version **1.6.10** works (Versions in between don't work on Windows because of a OpenSSL bug).

**To Reproduce**
_conf.txt_
```
[SERVICE]
    Log_Level trace

[INPUT]
    Name                dummy

[OUTPUT]
    Name cloudwatch_logs
    Match   *    
    log_group_name fluent-bit-cloudwatch
    log_stream_prefix from-fluent-bit-
    auto_create_group On
    role_arn arn:aws:iam::1234:role/foobar
    region eu-central-1
```
_Command_
`& 'C:\Program Files\td-agent-bit\bin\fluent-bit.exe' -c .\conf.txt`
- Steps to reproduce the problem:

**Expected behavior**
Connection to STS should work as it did with a previous minor version of FluentBit (1.6.10)

**Your Environment**
* Version used: 1.7.3
* Environment name and version (e.g. Kubernetes? What version?): Windows
* Operating System and version: Windows 10 / Windows Server 2019

**Comment by rifftual** [comment]
Possibly related: #3154

Also worth noting that `aws sts assume-role` CLI command works. So this is a FluentBit issue apparently.

**Comment by fujimotos** [comment]
This might be the same issue with #3496. I'm going to have a look...
