### ISSUE TITLE
Fluent-bit v1.7.4 deadlocks on ubuntu-2004-lts

### ISSUE THREAD

**Issue by hsmatulisgoogle** [fluent/fluent-bit#3398]
## Bug Report

After running fluent-bit at a high load (150MB/s, 150k entry/s, 1kb/entry), fluent-bit deadlocked after ~20 minutes.

This was on ubuntu v1.7.4 with the following config:
[fluent-bit-config.txt](https://github.com/fluent/fluent-bit/files/6346652/fluent-bit-config.txt) and log file [fluent_bit_log.txt](https://github.com/fluent/fluent-bit/files/6346653/fluent_bit_log.txt).

### Stack traces

I used `eu-stack` from `elfutils` to get stack traces for fluent-bit after it stopped sending the backend any logs. Here are 6 stack traces. There was a waiting period of minutes between some of these traces:
* [stack.1.txt](https://github.com/fluent/fluent-bit/files/6346694/stack.1.txt) 
* [stack.2.txt](https://github.com/fluent/fluent-bit/files/6346695/stack.2.txt)
* [stack.3.txt](https://github.com/fluent/fluent-bit/files/6346696/stack.3.txt)
* [stack.4.txt](https://github.com/fluent/fluent-bit/files/6346697/stack.4.txt)
* [stack.5.txt](https://github.com/fluent/fluent-bit/files/6346698/stack.5.txt)
* [stack.6.txt](https://github.com/fluent/fluent-bit/files/6346699/stack.6.txt)

In these traces, each output thread is still on the same code path likely due to deadlock.

### Metrics

We can see evidence of the deadlock when we look at fluent-bit metrics:

#### Input records per second reported by fluent-bit

![input records](https://user-images.githubusercontent.com/69014250/115464639-5fbcbd00-a1fb-11eb-83a9-0880a2688165.png)

#### Output records per second reported by fluent-bit

![output plugin records](https://user-images.githubusercontent.com/69014250/115464695-77944100-a1fb-11eb-9d93-dbec0a07464b.png)

#### Output records per second reported by backend

![backend records](https://user-images.githubusercontent.com/69014250/115464760-94c90f80-a1fb-11eb-95cc-83f2c2b4642c.png)

#### Bytes sent by VM

![VM bytes sent](https://user-images.githubusercontent.com/69014250/115464886-c17d2700-a1fb-11eb-8648-70cbeee54715.png)

#### Fluent-bit CPU usage

![cpu usage](https://user-images.githubusercontent.com/69014250/115464946-d5288d80-a1fb-11eb-888c-3d198f8c1c16.png)

#### Fluent-bit virtual memory usage

![VM usage](https://user-images.githubusercontent.com/69014250/115465011-eb364e00-a1fb-11eb-8c7e-33b457633a06.png)

#### Fluent-bit RSS

![RSS usage](https://user-images.githubusercontent.com/69014250/115465027-f2f5f280-a1fb-11eb-85ae-74d53af537a1.png)

#### Fluent-bit chunks up

![chunks up](https://user-images.githubusercontent.com/69014250/115465050-fdb08780-a1fb-11eb-8402-3094986ea4b4.png)

#### Fluent-bit total chunks

![chunks total](https://user-images.githubusercontent.com/69014250/115465082-0bfea380-a1fc-11eb-9263-9b560e343c07.png)

### Fluent-bit dump

A fluent-bit dump (with sigcont) is at the end of the log file:

```
===== Input =====
input_main (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 1010.8M (1059893178 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 512
│  ├─ new           : 0
│  ├─ running       : 512
│  └─ size          : 1010.8M (1059893178 bytes)
│
└─ chunks
   └─ total chunks  : 5178
      ├─ up chunks  : 513
      ├─ down chunks: 4665
      └─ busy chunks: 512
         ├─ size    : 1010.8M (1059893178 bytes)
         └─ size err: 0

storage_backlog.1 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0


===== Storage Layer =====
total chunks     : 5178
├─ mem chunks    : 0
└─ fs chunks     : 5178
   ├─ up         : 513
   └─ down       : 4665
```

**Comment by qingling128** [comment]
Turned out there is indeed a deadlock when Fluent Bit tries to grab mutex lock to refresh Google Oauth token.

This should have been fixed by https://github.com/fluent/fluent-bit/pull/3516 (out_stackdriver: implement cache for oauth2 token at thread level) and released in https://github.com/fluent/fluent-bit/releases/tag/v1.7.6.

Kudos to @hsmatulisgoogle @edsiper @igorpeshansky !
