### ISSUE TITLE
packages.fluentbit.io is down

### ISSUE THREAD

**Issue by arunavamagi** [fluent/fluent-bit#3399]
wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add -
This command is failing with gpg: no valid OpenPGP data found.
As a result following also fails
deb https://packages.fluentbit.io/ubuntu/focal focal main

**Comment by lordzorn** [comment]
I´m getting 'Could not resolve 'packages.fluentbit.io' when executing 'apt-get udate'. 
Seems packages.fluentbit.io is down.

**Comment by geo-matheou** [comment]
I have the same issue

**Comment by jagdishpatil** [comment]
Temporary solution Until **_packages.fluentbit.io_** comes back up, 

Ex: For Amazon linux 2
```
git clone https://github.com/fluent/fluent-bit-packaging.git
cd fluent-bit-packaging
./build.sh -v 1.7.4 -d amazonlinux/2
```

Above will create a RPM file: (check output of **_build.sh_**  script)
`Package(s) generated at: /root/fluent-bit-packaging/packages/amazonlinux/2/1.7.4/2021-04-21-10_16_30/td-agent-bit-1.7.4-1.x86_64.rpm`


Ref: https://github.com/fluent/fluent-bit-packaging

**Comment by agup006** [comment]
This should now be resolved, had a few DNS issues last night

**Comment by geo-matheou** [comment]
Thank you very much!

**Comment by evgkrsk** [comment]
I had now:

```
failure: repodata/repomd.xml from td-agent-bit: [Errno 256] No more mirrors to try.
https://packages.fluentbit.io/centos/7/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Unable to communicate securely with peer: requested domain name does not match the server's certificate."
```

**Comment by evgkrsk** [comment]
Debug:
```
# curl -vsI https://packages.fluentbit.io/centos/7/x86_64/repodata/repomd.xml
*   Trying 31.31.205.163:443...
* Connected to packages.fluentbit.io (31.31.205.163) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: none
  CApath: none
* loaded libnssckbi.so
* Server certificate:
*       subject: CN=*.domainparking.ru
*       start date: Feb 18 07:05:32 2021 GMT
*       expire date: Mar 22 07:05:32 2022 GMT
*       common name: *.domainparking.ru
*       issuer: CN=AlphaSSL CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE
* NSS error -12276 (SSL_ERROR_BAD_CERT_DOMAIN)
* Unable to communicate securely with peer: requested domain name does not match the server's certificate.
* Closing connection 0
```

**Comment by evgkrsk** [comment]
Will is self-resolve over time?

**Comment by evgkrsk** [comment]
Yep, issue really resolved.
