### ISSUE TITLE
Urgent: Prod issue: fluentbit.io is not getting resolved cant install/update

### ISSUE THREAD

**Issue by ajosep514** [fluent/fluent-bit#3402]
## Bug Report

**Describe the bug**
apt-update is failing

Note: because of this, all ansible scripts are failing even those that are doing the update for purposes (other than installation of td-agent-bit)

found same issue with bionic and xenial

**To Reproduce**

```
sudo apt-get update
Err:3 https://packages.fluentbit.io/ubuntu/xenial xenial InRelease
  Could not resolve 'packages.fluentbit.io'

Reading package lists... Done
W: Failed to fetch https://packages.fluentbit.io/ubuntu/xenial/dists/xenial/InRelease  Could not resolve 'packages.fluentbit.io'
W: Some index files failed to download. They have been ignored, or old ones used instead.


 sudo apt-get update
Err:1 https://packages.fluentbit.io/ubuntu/bionic bionic InRelease
  Could not resolve 'packages.fluentbit.io'
Hit:2 https://yumrepo.sys.comcast.net/ubuntu bionic InRelease
Hit:3 https://yumrepo.sys.comcast.net/ubuntu bionic-updates InRelease
Hit:4 https://yumrepo.sys.comcast.net/ubuntu bionic-backports InRelease
Hit:5 https://yumrepo.sys.comcast.net/ubuntu bionic-security InRelease
Reading package lists... Done
W: Failed to fetch https://packages.fluentbit.io/ubuntu/bionic/dists/bionic/InRelease  Could not resolve 'packages.fluentbit.io'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

* Version used:Fluent Bit v1.7.3
* Operating System and version: Ubuntu 18.04.5 LTS

**Comment by ajosep514** [comment]
@edsiper  please take a look when you can.

**Comment by ajosep514** [comment]
FYI, I found similar issue had happened earlier https://github.com/fluent/fluent-bit/issues/1314

**Comment by edsiper** [comment]
cc: @niedbalski

**Comment by niedbalski** [comment]
@ajosep514 can you check dig +short packages.fluentbit.io @1.1.1.1 or @8.8.8.8 on those systems? we made a change in the upstream DNS that should be propagated downstream already.

**Comment by ajosep514** [comment]
thanks for the response @niedbalski 
I see mixed responses on different machines. 

```
dig +short packages.fluentbit.io @8.8.8.8
139.178.85.103
dig +short packages.fluentbit.io @1.1.1.1
139.178.85.103


dig +short packages.fluentbit.io @8.8.8.8
;; connection timed out; no servers could be reached
dig +short packages.fluentbit.io @1.1.1.1
;; connection timed out; no servers could be reached
```

Has the change propagated everywhere ? when was the change made ?

**Comment by niedbalski** [comment]
> thanks for the response @niedbalski
> I see mixed responses on different machines.
> 
> ```
> dig +short packages.fluentbit.io @8.8.8.8
> 139.178.85.103
> dig +short packages.fluentbit.io @1.1.1.1
> 139.178.85.103
> 
> 
> dig +short packages.fluentbit.io @8.8.8.8
> ;; connection timed out; no servers could be reached
> dig +short packages.fluentbit.io @1.1.1.1
> ;; connection timed out; no servers could be reached
> ```
> 
> Has the change propagated everywhere ? when was the change made ?

~9 hours ago. Check this link https://www.whatsmydns.net/#A/packages.fluentbit.io , should be propagated at this point.
* Perhaps you have a resolver cache with a long TTL?

**Comment by ajosep514** [comment]
thanks for the responses, it wasn't propagated fully across my company's dns resolvers at that time. 
Just FYI, in the link that was shared, there are still some where its not resolved.
https://www.whatsmydns.net/#A/packages.fluentbit.io

Closing the issue.
