### ISSUE TITLE
Centos 7 fluent bit version is very old

### ISSUE THREAD

**Issue by ajosep514** [fluent/fluent-bit#3406]
The Centos 7 fluent bit version is at td-agent-bit-1.3.11-1.x86_64.

Can someone please update to the 1.7 series ?

Thanks,
Abhijit

**Comment by ajosep514** [comment]
@edsiper  can you please update the centos binary to latest stable one ?

**Comment by edsiper** [comment]
Likely you are using a very old Yum repo path, you should use the latest one:

https://docs.fluentbit.io/manual/installation/linux/redhat-centos#configure-yum

**Comment by ajosep514** [comment]
thanks @edsiper  you were right. 
It seems the download link also changed, the below link works, however it i try with the new version (td-agent-bit-1.7.4-1.x86_64.rpm) it doesnt.
http://apt.fluentbit.io/centos/7/td-agent-bit-1.3.11-1.x86_64.rpm

**Comment by edsiper** [comment]
This should be the path:

http://packages.fluentbit.io/centos/7/x86_64/td-agent-bit-1.7.4-1.x86_64.rpm

**Comment by ajosep514** [comment]
thank you @edsiper I see it.
I was looking to do an offline kind of install, I tried to install just with rpm, but seems like it needs a lot of dependencies. Is there a final version which I can use incase there are network problems?
