### ISSUE TITLE
Output elasticsearch plugin do not show full error trace on stdout

### ISSUE THREAD

**Issue by ndhcoder** [fluent/fluent-bit#3427]
## Bug Report

**Describe the bug**

Output elasticsearch plugin do not show full error response from elasticsearch, i can not trace error
**To Reproduce**
- Steps to reproduce the problem:
Collect some logs 
Setup output plugin es.
Sorry i can not copy configuratio. from system
**Expected behavior**

Fluent bit show full error response
**Screenshots**

![image](https://user-images.githubusercontent.com/41509130/116374536-8fda1080-a838-11eb-8760-a86f8c838794.jpeg)
**Your Environment**

* Version used:1.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Docker
* Server type and version: linux
* Operating System and version: Red hat 6
* Filters and plugins:
Elasticsearch output
**Additional context**

V

**Comment by agup006** [comment]
Two notes,

1. The version says 1.1, can you try the latest 1.7.4 version release?
2. With the configuration, in order to print out the full error you need to enable `Trace_Error On`

**Comment by agup006** [comment]
https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
