### ISSUE TITLE
add custom fields

### ISSUE THREAD

**Issue by AlenJun** [fluent/fluent-bit#343]
example:
- test.log
```
10.32.197.76 100.116.204.44 "/usr/share/nginx/index.php"
```
- parsers.conf:
```
Regex ^(?<server_addr>[^ ]*) (?<remote_addr>[^ ]*) "(?<request_filename>[^\"]*)"?$
```
i want add custom fields from INPUT plugin,what shoud i do,results as this.
```
server_addr	10.32.197.76
remote_addr	100.116.204.44
request_filename	/usr/share/nginx/index.php
hostname    nginx_server
```
hostname    nginx_server      -> **this is add fileds and valus**

**Comment by nokute78** [comment]
This is duplicated issue.(#202)
The feature will support v0.12(dev) with filter_record_modifier. 

Could you see #235 ?
