### ISSUE TITLE
outfile to file on intervals

### ISSUE THREAD

**Issue by gfrankliu** [fluent/fluent-bit#3431]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Match the feature in fluentd.

**Describe alternatives you've considered**

**Additional context**

In fluentd, I can output to the file at every predefined interval. We would like to do the same in fluent bit?

eg, fluentd config:
```
<source>
 @type forward
 port 9090
 bind 0.0.0.0
</source>
<match mytag.**>
  @type file
  path /opt/data/mytag/${tag}
  <buffer tag,time>
   timekey 30
   timekey_wait 1s
   flush_at_shutdown true
  </buffer>
  add_path_suffix false
  append true
  format json
</match>
```

**Comment by gfrankliu** [comment]
refresh the ticket to remove stale label.

**Comment by gfrankliu** [comment]
refresh the ticket to remove stale label.

**Comment by ai-denlim** [comment]
I require the same requirement with the S3 output plugin. Any plans on supporting what fluentd supports with [time](https://docs.fluentd.org/configuration/buffer-section#time) and timekey parameters? 

@gfrankliu btw, did you get to solve this problem? If yes, then how did you do it?

**Comment by gfrankliu** [comment]
Unfortunately there is no comment here, and it seems fluent-bit community is not very active. I also tried fluent-bit mailing list, and got zero replies. 
At this point, I am looking at alternatives such as [vector](https://github.com/timberio/vector/).

**Comment by gfrankliu** [comment]
refresh the ticket to remove stale label.

**Comment by gfrankliu** [comment]
@edsiper refresh ticket to remove stale label.

**Comment by gfrankliu** [comment]
refresh ticket to remove stale label.

**Comment by gfrankliu** [comment]
refresh ticket to remove stale label.
