### ISSUE TITLE
Please support Google application default credentials, GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by rvandegrift** [fluent/fluent-bit#3437]
Providing credentials for the stackdriver output is harder than necessary due to not using their SDK's standard credential loading mechanisms. This page provides a good overview of how that should work: https://cloud.google.com/docs/authentication/production

If that's not practical, it'd be great to at least be able to use the env var GOOGLE_APPLICATION_CREDENTIALS.

**Comment by jiang-wei** [comment]
it uses GOOGLE_SERVICE_CREDENTIALS.

see https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver

**Comment by rquinlivan** [comment]
I am having trouble using this plugin as well. @jiang-wei  is the json file referred to be `google_service_credentials` the same as the service account key json provided by GCP?
