### ISSUE TITLE
Stackdriver output plugin causes memory leak

### ISSUE THREAD

**Issue by ErezT94** [fluent/fluent-bit#3448]
## Bug Report

**Describe the bug**
When using the stackdriver output plugin there is a memory leak.
The logs reaches to the destination but over few hours there is a pretty big leak, on my system it was more than 200KB per minute (and I wasn't sending a lot of logs).
It looks like the leak is starting after about an hour, maybe it has something to do with the token refreshment logic that was updated not long ago.

**To Reproduce**
Run a configuration that tries to send logs through stackdriver output plugin.
My configuration can be found below.

**Expected behavior**
Have no memory leak.

**Screenshots**
![image](https://user-images.githubusercontent.com/12459745/117114820-fa3d0480-ad94-11eb-8c6f-3e565a8dfdd2.png)

**Your Environment**
* Version used: 1.7.4 (docker image)
* Environment name and version: Kubernetes/k3s version v1.20.4+k3s1
* Operating System and version: Ubuntu 18.04
* Configuration:
```
    [SERVICE]
         Flush     2
         Daemon    off
 
    @INCLUDE input.conf
    @INCLUDE output.conf
 -----------------------
    [INPUT]
         Name tail
         Path /var/log/*.log
         Tag appliance.*
         Mem_Buf_Limit 16MB
         Skip_Long_Lines On
 -----------------------
    [OUTPUT]
         Name  stackdriver
         Match *
         resource generic_node
         location location_placeholder
         namespace namespace_placeholder
         node_id node_id_placeholder
         log_name_key fluent-bit-log
         google_service_credentials <relevant sa file>
```

**Additional Context**
I used the same configuration with stdout instead of stackdriver as an output and the memory remained flat.

**Comment by cdelacruzpinto** [comment]
I just updated to the latest version because I was having an issue with Google oauth token. Then now I get this:

![image](https://user-images.githubusercontent.com/1537621/117284492-29bc4180-ae67-11eb-805a-b4ab96d68b33.png)

So apparently at some point it enters an infinite loop of retrieving the token each second

**Comment by JeffLuoo** [comment]
Hi all, I have pushed a patch to fix the token issue: https://github.com/fluent/fluent-bit/commit/7bc64f4d6f2f14ad4db7cf0d50683ad9abd6f3e0

Please test with this patch to see if the issue still happens.

**Comment by ErezT94** [comment]
Hi,
First of all, thanks Jeff, the fix has highly improved the leak rate.
Unfortunately, a leak is still there (about 200-500KB per hour). According to the previous fix which significantly reduced it I assume that the leak is somewhere in the process of refreshing the token.
