### ISSUE TITLE
Add optional support for X509_V_FLAG_PARTIAL_CHAIN

### ISSUE THREAD

**Issue by sondinhnwv** [fluent/fluent-bit#3449]
**Is your feature request related to a problem? Please describe.**
Our kube-apiserver doesn't present a self-signed CA but instead an intermediate one (that's accepted in our trust store) and so OpenSSL isn't verifying it. Adding support for this would allow us to accept such a CA when presented.

**Describe the solution you'd like**
Add option to set the `X509_V_FLAG_PARTIAL_CHAIN` like [curl does](https://github.com/curl/curl/blob/67d3afa73f4cdb8a6c473f911c8af800121e0a49/lib/vtls/openssl.c#L3049-L3074).

This would allow the user to choose whether to set it or not in case they have security concerns.

**Describe alternatives you've considered**
The only alternatives I can think of are migrating to a true self-signed root CA for our api-server (this is a lot of work) or setting tls.verify=off (we've done the latter).

**Additional context**
This behaviour changed on the switchover of the TLS library to using OpenSSL in 1.7. It worked for us before that.

Previous discussion here https://github.com/fluent/fluent-bit/issues/3077#issuecomment-828393663.

**Comment by grpatter** [comment]
This is still a need, still seeing the same behavior described here and a ticket was requested in the linked issue, #3077, here: https://github.com/fluent/fluent-bit/issues/3077#issuecomment-828560417
