### ISSUE TITLE
Support an "auto-detect" option for setting Parser parameter in Tail Plugin on Kubernetes

### ISSUE THREAD

**Issue by gsmith-sas** [fluent/fluent-bit#3451]
**Problem**
Different Kubernetes clusters can be configured with different container runtimes such as Docker, containerd, etc.  I believe a single Kubernetes cluster can even include nodes running different container runtimes (although I assume a node is limited to a single container runtime).  The Tail plugin within Fluent Bit includes a Parser parameter that requires a different value when running on a Kubernetes node configured for the Docker runtime than it does for a node running containerd.  However, developers working on a solution leveraging Fluent Bit may not know ahead of time what container runtime is being used in a particular cluster.  This is especially true if the solution is intended for an external customer.

**Proposed Solution**
It would be very helpful to Fluent Bit users if Fluent Bit could detect the container runtime and automatically set the Parser parameter of the Tail plugin accordingly.  This would allow users to develop more generic Kubernetes solutions without having to worry about low-level Kubernetes architecture details.  To preserve compatibility and to support flexibility, I would vote for maintaining the ability for Fluent Bit users to provide their own value for the Parser parameter if they choose to.  Whether the suggested "auto-detect" behavior becomes the new default behavior (i.e. in the absence of the Parser parameter being explicitly set) is probably something that requires further discussion and thought.

**Alternatives/Work-arounds**
Without this sort of "auto-detect" behavior, developers using Fluent Bit will be forced to put the burden on their users.  I would imagine we will need to support some mechanism for the users to indicate the details of their cluster configuration.  In our use case, my current thinking is that we will ask users to set an environment variable to indicate the appropriate parser for their cluster's container runtime and we will write our Fluent Bit configuration files to depend on that environment variable to be set correctly.  

Unfortunately, I think that most likely limits us to deploying on clusters in which every node uses the same container runtime since we would have a single environment variable.  I am not sure how significant this limitation might be.  It might be possible to define a set of environment variables, one per node, that allows the users to define container runtimes on a per-node basis.  However, given that we are deploying Fluent Bit as a daemonset (i.e. a single Fluent Bit configuration used for all nodes), I'm not sure how to get the individual Fluent Bit instances to use these node-specific environment variables.  I also think asking users to define 8 or 16 (or 32) environment variables (depending on the size of their Kubernetes cluster) may be unreasonable.  

It is entirely possible that there is a more elegant way to handle all of this that I have not considered.  I am very open to hearing any suggestions you might have.

**Comment by edsiper** [comment]
@gsmith-sas 

thanks for raising this topic, we are actually hard working on this challenge for Fluent BIt v1.8.

Our current GIT version contains a new "multiline interface" that comes with built-in modes for docker, cri, java, python, go, etc. Current work is extending Tail input to support a single built-in mode like:

```
[INPUT]   
    name           tail
    path           /var/log/containers/*.log
    multiline.mode cri
```

of course this is not limited to that, you can also use an environment variables.  

The current scope of mulitiline work, aims also to address auto detection of stacktraces from different languages through filters (pretty much like Fluentd stacktrace exception detector). 

This ticket is mostly about container runtime and log format, let's keep it open to continue informing about the ongoing work we are doing on this area.

**Comment by agup006** [comment]
+1 thanks for filing @gsmith-sas

**Comment by gsmith-sas** [comment]
@edsiper The new multi-line functionality you described sounds interesting and useful.  Would Fluent Bit set the multiline.mode parameter correctly if the user does not provide a value?  If so, then it sounds like it could automatically set the parser parameter as well.
