### ISSUE TITLE
Segfault in TLS with Fluent Bit 1.7.4

### ISSUE THREAD

**Issue by zhonghui12** [fluent/fluent-bit#3454]
## Bug Report

**Describe the bug**

Our customers reported that the issue still exists in Fluent Bit 1.7.4: #3331.

**To Reproduce**
- Steps to reproduce the problem:
Our customer uses docker -Fluent Bit 1.7.4 to test it and here you can reproduce it: https://github.com/fluent/fluent-bit/issues/3331#issuecomment-816643574

**Your Environment**

* Version used: 1.7.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by zhonghui12** [comment]
@edsiper please take a look at this issue as #3331 is not fixed by 1.7.4.

**Comment by edsiper** [comment]
the information provided in #3331 is not enough to reproduce the problem.

how can we reproduce the issue ?
