### ISSUE TITLE
[parser] timezone and nanoseconds in timeformat 

### ISSUE THREAD

**Issue by keyolk** [fluent/fluent-bit#346]
I use 0.11.9 version of fluent-bit

I have log like below
```
time="2017-06-22T11:36:59.810694666+09:00" level=info msg="stopping containerd after receiving terminated"
```

to parse its time
what I tried ...
- %Y-%m-%dT%H:%M:%S.%L%z --> ignores timezone
- %Y-%m-%dT%H:%M:%S.%L%Z --> ignores timezone
- %Y-%m-%dT%H:%M:%S.%L%:z --> ignores timezone
- %Y-%m-%dT%H:%M:%S.%L%:Z --> ignores timezone
- %Y-%m-%dT%H:%M:%S.%N%:z --> invalid time format
- %Y-%m-%dT%H:%M:%S.%N%Z  --> invalid time format
- %Y-%m-%dT%H:%M:%S.000000000%:z  --> invalid time format
- %Y-%m-%dT%H:%M:%S.000000000%:Z  --> invalid time format
...

But those seems not works.
nanosec supporting is not necessary but I needs timezone info.

Is there a way to parse timezone to get accurate epoch time?

**Comment by edsiper** [comment]
@keyolk thanks for report the problem.

I've found the issue was a wrong "string length" passed to the internal function that does the time lookup. I've pushed the fix to git mater and 0.11 branches (and unit case to avoid future regressions).

Fixed.

**Comment by konstantin-kornienko** [comment]
Could you please share the correct time format string?

**Comment by edsiper** [comment]
@konstantin-kornienko should be something like "H:%M:%S.%L"
