### ISSUE TITLE
Multiline On disables Path_key

### ISSUE THREAD

**Issue by zmichael** [fluent/fluent-bit#347]
Hello!

I try to parse tomcat logs into single event with multiline
Without multiline filename added to log
with multiline and this parser:
```
[PARSER]
    Name notnull
    Format regex
    Regex  ^(?<log>[a-zA-Z0-9].*)
```
no more filename in message, please advice why ?
tail config:
```
[INPUT]
    Name tail
    Tag tomcat8-catalina
    Path /var/log/tomcat8/catalina.out
    path_key filename
    Multiline On
    Parser_Firstline notnull
    DB /var/lib/fluent-bit/logs.db
```

regards

**Comment by edsiper** [comment]
Thanks for catching up this problem. Indeed the functionality of path_key is missing from the multiline handler, this will be fixed shortly.

**Comment by edsiper** [comment]
Functionality has been implemented.

Fixed.
