### ISSUE TITLE
pod error and CrashLoopBackOff when I use azure blob output 

### ISSUE THREAD

**Issue by JamesIsHuang** [fluent/fluent-bit#3470]
pod log:
fluent-bit: /tmp/fluent-bit/lib/monkey/deps/flb_libco/amd64.c:121: crash: Assertion `0' failed.
[2021/05/10 09:47:54] [engine] caught signal (SIGSEGV)
#0  0x7f881fa36611      in  ???() at ???:0
#1  0x7f881fa3640e      in  ???() at ???:0
#2  0x7f881fa44101      in  ???() at ???:0
#3  0x5570184fdfe9      in  crash() at lib/monkey/deps/flb_libco/amd64.c:121
#4  0xffffffffffffffff  in  ???() at ???:0

**Comment by liammoat** [comment]
Duplicate of #2839?
