### ISSUE TITLE
Stackdriver plugin cannot auth and doesn't log anything

### ISSUE THREAD

**Issue by rquinlivan** [fluent/fluent-bit#3484]
## Bug Report

**Describe the bug**

Following the directions [here](https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver), I am unable to configure the Stackdriver output. Furthermore, the plugin does not log anything on startup, so I'm unable to debug the issue myself.

If I include the stackdriver output section in the config (see below), the `td-agent-bit` process fails to start. Nothing is logged (even at trace).

**To Reproduce**

- Create a service account in GCP
- Grant that service account the following roles: "Logging Admin", "Logs Bucket Writer",  "Logs Writer", "Logs Viewer"
- Create a service account key and download the JSON
- Configure fluentbit with a config that configures a Stackdriver output (copying the JSON key to `/app/service-account-key.json`) with `trace` level logging such as below:

```
[SERVICE]
    flush        5
    daemon       Off
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on
    log_level    trace
    log_file     /var/log/fluentbit.log
    
[INPUT]
    name cpu
    tag  cpu.local

    # Read interval (sec) Default: 1
    interval_sec 1

[OUTPUT]
        Name        stdout
        Match       *

[OUTPUT]
        Name        stackdriver
        Match       *
        Resource    global
        google_service_credentials /app/service-account-key.json
        namespace   test
        job         test
        tag_prefix  test
```

**Expected behavior**

I expect that the configuration above would write data from the CPU input to Stackdriver interface and also to stdout. 

I expect that the Stackdriver plugin would log something at `trace` level if there is an error connecting on startup.

**Screenshots**

**Your Environment**

* Version used: `td-agent-bit/now 1.7.4 amd64`
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): Debian
* Server type and version:
* Operating System and version: Debian Buster with a 5.10.x kernel
* Filters and plugins: Nothing but the standard plugins

**Additional context**

**Comment by JeffLuoo** [comment]
Could you attach the logs written into `log_file     /var/log/fluentbit.log`?
