### ISSUE TITLE
Plan for docker log input plugin ?

### ISSUE THREAD

**Issue by keyolk** [fluent/fluent-bit#349]
How about supporting docker logs input ?
Currently Docker supports fluentd log-driver but when I use it 
I cant use "docker logs" CLI.
the CLI only supports for "json-file", "journald" log-driver.

In my case I use non-systemd based System.
To aggregate containers logs, \
  polling target containers logs using docker, \
  get diff, \
  append it to file, \
  read it using fluent-bit, \
  then send it to central elasticsearch.

If I can push some of docker containers log to fluent-bit directly it would be helpful.

**Comment by edsiper** [comment]
Actually Fluent Bit can consume Docker logs from json files. Do you need also to collect specific metadata as container name, container id, etc ?

**Comment by keyolk** [comment]
@edsiper 
Yes I can use json file.
But you know, it is hard to check its location before it launch.
My situation is ... get some logs from the container named "A" or labeled "B", and put them to fluent-bit.

**Comment by edsiper** [comment]
where are your docker logs located now ? how the path looks like ?

**Comment by keyolk** [comment]
@edsiper 

like below
```
/var/lib/docker/containers/9e7a986f0456f03c73dee1140c7102158a35b8b31257e76435b48637e516245e/9e7a986f0456f03c73dee1140c7102158a35b8b31257e76435b48637e516245e-json.log
```

yeah, I may can make the container to dump its log to specific path, and bind it to host.
but in this case I have to change its Dockerfile or its own confinguration file.

for example, consul.
it doesn't have configuration for log file. it just put its log to stdout/stderr.
if I want to see its log using "docker logs" and also from file,
I need to rewrite or extend its Dockerfile to use tee.
It's simple but I don't want to edit all of docker images.

**Comment by marcbachmann** [comment]
It would be nice to support `docker logs` somehow.
Docker has now a nice plugin api for that: https://docs.docker.com/engine/extend/plugins_logging/
E.g. I want to forward to elasticsearch and also support `docker logs` output.
Currently I have to use journald to support that.

**Comment by blaggacao** [comment]
Native support for `docker logs` would be nice, although I see how difficult it might be to fetch that data back from the different back-ends... Or maintain an internal buffer when acting as docker logging driver? out of band solutions are really just another moving part, which we all try to avoid...

**Comment by adeelamin15** [comment]
As of now fluentd logging works with fluent-bit as well.
