### ISSUE TITLE
Incomplete dockerfiles on `master` and `release` tag

### ISSUE THREAD

**Issue by erain** [fluent/fluent-bit#3528]
It looks like we have inconsistent dockerfiles on `master` and `release` tag/branch
- https://github.com/fluent/fluent-bit/tree/master/dockerfiles master branches contains many dockerfiles for different settings and arch. 
- https://github.com/fluent/fluent-bit/tree/v1.7.6/dockerfiles the latest `1.7.6` branch only contains one dockerfile. 

Is this expected?

**Comment by erain** [comment]
@qingling128 @edsiper WDYT?

**Comment by edsiper** [comment]
Expected, dockerfiles were only updated on GIT master (upcoming v1.8), since we are almost finishing v1.7 release cycle there is no need to move and change our release/deployment model of v1.7.x.. 

Actually we build docker images using : https://github.com/fluent/fluent-bit-docker-image/tree/1.7

**Comment by erain** [comment]
Thanks for the explanation. We will resolve this internally with our release pipeline.
