### ISSUE TITLE
Missing multiline logs split across files during log rotation.

### ISSUE THREAD

**Issue by hegderohit89** [fluent/fluent-bit#3538]
## Bug Report

**Describe the bug**
If the multiline log gets split into two files during log rotation, then the joined single log entry is incomplete or missing the lines after the end of current file.

**To Reproduce**
Deployed a test app that generates a JSON response an ID passed from query param.
Run the a simple script to hit the application with incrementing `id` param.
Optionally update the docker daemon config to rotate the files quickly (in terms of log file max size)
Once the rotation is triggered tail the last lines from log.1 file to capture the json id
Then check the upstream sink (dataDog in my case) for this entry:

What is observed:
Last entry is pushed without joining full json.
You will also see the remaining lines from the new log file (current indexed file) pushed as individual log entires.

End of log.1 has half data fr record `e-833`:
```
# tail -n 20 812428e5150652251b7f535fddc8710d423210cb3c4f1cd8ebd6b1bb4766fba2-json.log.1
{"log":"}\n","stream":"stdout","time":"2021-05-12T20:34:06.953467863Z"}{"log":"[2021-05-12 20:34:06.893] INFO LoggerMessageProcessor [[abc].uber.13: [test-sample-json-1].sample-json-backendFlow.CPU_INTENSIVE @5108e0ba] [event: 65f88ec0-b361-11eb-ad96-aaa05347a452]: {\n","stream":"stdout","time":"2021-05-12T20:34:06.953471587Z"}
{"log":" \"id\": \"e-833\",\n","stream":"stdout","time":"2021-05-12T20:34:06.95347622Z"}
{"log":" \"index\": 10,\n","stream":"stdout","time":"2021-05-12T20:34:06.953480101Z"}
{"log":" \"phone\": \"+1 (962) 552-3728\",\n","stream":"stdout","time":"2021-05-12T20:34:06.953577953Z"}
{"log":" \"about\": \"Test Data\",\n","stream":"stdout","time":"2021-05-12T20:34:06.953588153Z"}
```

rest of log is written in new file, after e-833 ends e-834 starts:
```# head -20 812428e5150652251b7f535fddc8710d423210cb3c4f1cd8ebd6b1bb4766fba2-json.log
{"log":" \"registered\": \"2016-10-25T07:24:50 -08:00\",\n","stream":"stdout","time":"2021-05-12T20:34:06.953592321Z"}
{"log":" \"longitude\": -166.312889\n","stream":"stdout","time":"2021-05-12T20:34:06.953815068Z"}

{"log":"}\n","stream":"stdout","time":"2021-05-12T20:34:06.953920017Z"}{"log":"[2021-05-12 20:34:06.898] INFO LoggerMessageProcessor [[MuleRuntime].uber.13: [test-sample-json-1].sample-json-backendFlow.CPU_INTENSIVE @5108e0ba] [event: 65f97920-b361-11eb-ad96-aaa05347a452]: {\n","stream":"stdout","time":"2021-05-12T20:34:06.953924017Z"}
{"log":" \"id\": \"e-834\",\n","stream":"stdout","time":"2021-05-12T20:34:06.953928556Z"}
{"log":" \"index\": 10,\n","stream":"stdout","time":"2021-05-12T20:34:06.953480101Z"}
```

**Expected behavior**
Every time the log file gets rotated, FluentBit flushes the record as it looses the file handler (EOF). Then on the new log file it flushes the first few lines of log entries as is ( till it can find the next matching first line).
Can it handle the rotation more gracefully by storing the record rebuild the compete log entry before flushing.

**Screenshots**
![Screen Shot 2021-05-12 at 3 41 41 PM](https://user-images.githubusercontent.com/22915489/119369395-bc3b4e00-bc79-11eb-90f1-86dc9f51dde2.png)

**Your Environment**
* Version used: 1.7.4
* Configuration:
```
[INPUT]
   Name tail
   Tag kube.*
   Path ${LOG_PATH}
   Parser docker
   DB ${DB_FILE_PATH}
   Mem_Buf_Limit 5MB
   Skip_Long_Lines On
   Refresh_Interval 10
   Docker_Mode On
   Docker_Mode_Flush 5
   Docker_Mode_Parser multiline
```

**Comment by hegderohit89** [comment]
Any update on this issue ?

**Comment by hegderohit89** [comment]
Any update on this? Thanks

**Comment by libinglong** [comment]
Fanny, the issue is valuable.

**Comment by Dimledumlus** [comment]
I have the same problem :S Is there anyone who can look into this issue?  :)
