### ISSUE TITLE
Possible to set a specific parser from the command line ?

### ISSUE THREAD

**Issue by stanimirovv** [fluent/fluent-bit#356]
Hey,

Apologies for writing here if this isn't the correct place to ask questions.

Summary:
I am getting different output than expected when parsing apache logs from the documentation.
I think I haven't set up fluent bit to use the apache parser. Is that so?
Command:
`fluent-bit -i tail -p path=apache.log -t apache --parser=parser.conf -o stdout
`

Detailed version:
I was reading the official docs and following along when I hit an issue here:http://fluentbit.io/documentation/current/parser/regular_expression.html

I running this command:
`fluent-bit -i tail -p path=apache.log -t apache --parser=parser.conf -o stdout
`
The contents of apache.log are like the example:
`192.168.2.20 - - [29/Jul/2015:10:27:10 -0300] "GET /cgi-bin/try/ HTTP/1.0" 200 3395
`
and the full contents of parser.conf are like the example:
```
[PARSER]
    Name apache
    Format regex
    Regex ^(?<host>[^ ]*) (?<size>[^ ]*) (?<time>[^ ]*)$
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z

```
When I run the command, however, I don't get the output split into, fields, the entire message is treated as a single field:
`[0] apache: [1502893740, {"log"=>"192.168.2.20 - - [29/Jul/2015:10:27:10 -0300] "GET /cgi-bin/try/ HTTP/1.0" 200 3395"}]
`
It looks like the output of the "None" parser.

How can I force fluent-bit to use the apache Parser in the config file ? (Assuming this is the issue that is)

Edit: I am currently only using just fluent-bit, not the entire fluentd stack.

Thanks in advance!

**Comment by edsiper** [comment]
@stanimirovv Actually this is a good place to ask questions :)

When using Fluent Bit from the command line, to specify a "parsers" file you have to use the __-R__ argument (-R conf/parsers.conf). Then if you look carefully at the file you pointed you will see there are many parsers registered, so in_tail just need to know which parser registered it must use, e.g:

```
$ fluent-bit  -R conf/parsers.conf -i tail -p path=/apache.log -p parser=apache -o stdout -f 1
```

let me know if that works.

**Comment by stanimirovv** [comment]
Thanks a lot for the assistance. That worked as expected.
