### ISSUE TITLE
Decode_Field_As not returning expected data

### ISSUE THREAD

**Issue by dod-jwhite** [fluent/fluent-bit#3567]
## Bug Report

**Describe the bug**

Per the Fluent Bit documentation:
- Decode_Field: if the content can be decoded in a structured message, append that structure message (keys and values) to the original log message.
- Decode_Field_As: any content decoded (unstructured or structured) will be replaced in the same key/value, no extra keys are added.

My results for using both of these settings leads to the same result.  The documentation leads me to picture the below logic with results.

Decode_Field { "log": { \"app\": \"App1\", \"msg\": \"Broken\" } }
  Expected - { "app": "App1", "msg": "Broken" }
  Received - { "app": "App1", "msg": "Broken" }

Decode_Field_As { "log": { \"app\": \"App1\", \"msg\": \"Broken\" } }
  Expected - { "log": { "app": "App1", "msg": "Broken" } }
  Received - { "app": "App1", "msg": "Broken" }

**To Reproduce**
Fluent bit container:
```
docker run -p 2020:2020/tcp \
--log-driver=fluentd \
--log-opt fluentd-address=localhost:2020 \
-v $(pwd)/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf \
-v $(pwd)/server.conf:/fluent-bit/etc/server.conf \
fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
```
Test container:
```
docker run \
--log-driver=fluentd \
--log-opt fluentd-address=localhost:2020 \
ubuntu:latest echo '{ "app": "App1", "msg": "Broken" }'
```

**Your Environment**

* Version used: 1.7.2
* Configuration: 
fluentbit.conf
```
[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     warning
    Parsers_File  parsers.conf

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   2020

@INCLUDE server.conf
```

* Environment name and version (e.g. Kubernetes? What version?): Docker version 20.10.5
* Filters and plugins:
server.conf
```
[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser docker
    Reserve_Data On

[OUTPUT]
...
```
parsers.conf
```
[PARSER]
    Name docker
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
    Time Keep On
    Decode_Field_As json log
```

**Additional context**

We're trying parse the log with stringified JSON, but keep them under the "log" key.  The behavior change compared to normal string (which we also log) makes the event hard to search.

**Comment by edsiper** [comment]
what's the original content of the record ?

**Comment by nokute78** [comment]
I think this configuration is to generate docker like log.

```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name dummy
    Dummy { "log":"{ \"app\": \"App1\", \"msg\": \"Broken\" }" }

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser docker
    Preserve_Key on
    

[OUTPUT]
    Name stdout
```

```
[PARSER]
    Name docker
    Format json
    Decode_Field_As json log
```

Output is 
```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.7.8
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/06/02 21:01:46] [ info] [engine] started (pid=5921)
[2021/06/02 21:01:46] [ info] [storage] version=1.1.1, initializing...
[2021/06/02 21:01:46] [ info] [storage] in-memory
[2021/06/02 21:01:46] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/06/02 21:01:46] [ info] [sp] stream processor started
[0] dummy.0: [1622635307.778135967, {"app"=>"App1", "msg"=>"Broken"}]
[1] dummy.0: [1622635308.778115114, {"app"=>"App1", "msg"=>"Broken"}]
```

**Comment by nokute78** [comment]
I think @dod-jwhite wants the output `"log":{"app"=>"App1", "msg"=>"Broken"}`
However `log` key is removed and flatten `{"app"=>"App1", "msg"=>"Broken"}`

I tested some configuration but I can't get @dod-jwhite's expected output..

**Comment by dod-jwhite** [comment]
@nokute78, that's exactly the issue.  The documentation leads me to believe that `Decode_Field` would remove `log` and flatten the output, but `Decode_Field_As` shouldn't.  Is my understanding wrong?  Both options give me the same output.

**Comment by dod-jwhite** [comment]
@edsiper We're abandoning the use case, but I'm still curious.  What is the intended functionality of `Decode_Field`, and `Decode_Field_As`?
