### ISSUE TITLE
kube meta: no meta attached to log although flb_http_client is able to fetch meta from kube API

### ISSUE THREAD

**Issue by kushwiz** [fluent/fluent-bit#358]
I am not sure if this is possible to replicate. But for one pod I am having this weird `111b` preppended in the response received from `/api/v1/namespaces/<ns>/pods/<pod>`

I printed the response `c->resp.payload` and it starts like this:
```
111b
{"kind":"Pod","apiVersion":"v1","metadata
```

c->resp.data looks like this
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 16 Aug 2017 17:40:59 GMT
Connection: close
Transfer-Encoding: chunked

111b
{"kind":"Pod","apiVersion":"v1","metadata"
```

Whereas, it should start like this:
`{"kind":"Pod","apiVersion":"v1","metadata`

Although, `curl` from the API server seems to be returning so such `111b`.
Let me try debugging this as well.

**Comment by edsiper** [comment]
that's the chunked transfer header (hex number plus \r\n specifying the number of bytes on that chunk)

**Comment by kushwiz** [comment]
So, because of that `flb_pack_json` is not able to parse the JSON.

**Comment by edsiper** [comment]
so there is a problem since the header should be dropped

**Comment by kushwiz** [comment]
Ok. I see that there is some code present that does drop the header. Let me try to debug this using gdb, I am not a C guy :)

**Comment by kushwiz** [comment]
Figured it out: 
https://github.com/fluent/fluent-bit/blob/23844d0bdd078646ff885e3c86a83ff63ba9e299/include/fluent-bit/flb_http_client.h#L28

I increased the `FLB_HTTP_DATA_SIZE_MAX` to 8196 as my Pod information was well over 4096 and the errors stopped.

We could make it 6k bytes instead of 8k for lesser memory? Suggest please. 

111b -> 4379 (well over 4096)
128c -> 4748 (well over 4096)

**Comment by edsiper** [comment]
@kushwiz thanks for catching that!

I've pushed a change where now the HTTP client have by default a maximum buffer of 32KB (grows up to 32KB), this can be changed too using the new _buffer\_size_ configuration option.

Please send me some feedback.

**Comment by kushwiz** [comment]
I will test this out later today. Thanks !

**Comment by kushwiz** [comment]
@edsiper  Thanks. it works now! 
I cherry picked your commit 7ca5cb4 on top of 0.11 branch and built and tested.
