### ISSUE TITLE
Can't download fluentbit because website links are broken.

### ISSUE THREAD

**Issue by simonvanbernem** [fluent/fluent-bit#3580]
## Bug Report

I am literally failing at just downloading fluent-bit. I start on the [Getting Started Page](https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit), then click on the link Under "Install on Windows", Windows EXE (for Windows 10) 
![image](https://user-images.githubusercontent.com/10748498/120173748-a2af7e80-c204-11eb-9561-cb36bf1648db.png)
which leads me to [this](https://docs.fluentbit.io/manual/installation/windows#installing-from-exe-installer) page, which has a link to the download page
![image](https://user-images.githubusercontent.com/10748498/120173820-b8bd3f00-c204-11eb-86dc-cc39a6c8bcc2.png)
but that just leads back to the [Getting Started Page](https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit).

Links on the [main page](https://fluentbit.io/) 
![image](https://user-images.githubusercontent.com/10748498/120174022-ec986480-c204-11eb-852c-5806a0c5581f.png)
also don't lead to a download section but to the documentation.

I literally can not find where to download fluent bit.

### Edit:
When I enter [https://fluentbit.io/download](https://fluentbit.io/download) I get redirected to the documentation. When I enter [https://www.fluentbit.io/download/](https://www.fluentbit.io/download/) I get to an actual download page. But that page only contains a link to a single .tar.gz that doesn't contain windows binaries.

### Edit 2:
I found the installers on the [getting started page](https://docs.fluentbit.io/manual/installation/windows#installing-from-exe-installer). I didn't see them before because the link from the main page starts you exactly at the paragraph underneath those links so you only see them when you scroll up. This is just super confusing.

**Comment by nokute78** [comment]
Thank you for reporting.

Is it website issue? If so, can you open an issue at https://github.com/fluent/fluentbit-website-v3 ?
It is website repo.

**Comment by simonvanbernem** [comment]
Yep, reported it there.

**Comment by nokute78** [comment]
Thank you, so I close this issue.

Note:  https://github.com/fluent/fluentbit-website-v3/issues/22
