### ISSUE TITLE
Linux packages not working for redhat/centos (aarch64 / arm64v8)

### ISSUE THREAD

**Issue by tejunior** [fluent/fluent-bit#3584]
## Bug Report

**Describe the bug**

I'm getting an error installing FB in Centos 7/8 and RedHat. I have 2 issues:

1. Package manager is not working properly;
2. Trying the manual installation (dowloaded from fluent-bit repo), the binary didn't work.

**To Reproduce**
Package error:
- Start a Centos 7/8 or RedHat linux instance for arm64 (AWS, GCP, etc..):
- Follow the installation process https://docs.fluentbit.io/manual/installation/linux/redhat-centos:

Manual installation:
Since the package manager didn't work, I downloaded the binary from here https://packages.fluentbit.io/centos/7/aarch64/td-agent-bit-1.7.4-1.aarch64.rpm 
- `sudo yum localinstall td-agent-bit-1.7.4-1.aarch64.rpm`

**Expected behavior**

Install Fluent-bit properly

**Screenshots**

_Package error:_

```
Downloading packages:
td-agent-bit-1.7.4-1.centos-7. FAILED
https://packages.fluentbit.io/centos/7/aarch64/td-agent-bit-1.7.4-1.centos-7.arm64.rpm: [Errno 14] HTTPS Error 404 - Not Found |    0 B  --:--:-- ETA
Trying other mirror.
To address this issue please refer to the below wiki article
https://wiki.centos.org/yum-errors
```

_Manual install error:_
```
> sudo yum localinstall td-agent-bit-1.7.4-1.aarch64.rpm
(success)
> /opt/td-agent-bit/bin/td-agent-bit -i cpu -t my_cpu -o stdout -m '*'
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
malloc: Cannot allocate memory
```

**Your Environment**

* Version used: fluent-bit 1.7.4
* Configuration: default/standard
* Environment: AWS Linux Centos 7 and RHEL 8

**Additional context**

**Comment by beatsandpics** [comment]
Also for x86_64 Centos 7 they don't exist 

`http://packages.fluentbit.io/centos/7/./td-agent-bit-1.3.11-1.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found`
