### ISSUE TITLE
How do in_tail deal with Scroll log

### ISSUE THREAD

**Issue by VinkDong** [fluent/fluent-bit#359]
I am sorry to trouble you again ··
I have a little test with in_tail a scrolling log and find a problem:

- first I touch a log file by `echo aaa > a.log` and run flb
```
./fluent-bit-dev -i tail -p path=$(pwd)/a.log -o stdout
```

- then append content by echo 

```
echo bbb >> a.log
echo ccc >> a.log
echo ddd >> a.log
```
since now out put is correct
```
Fluent-Bit v0.12.0
Copyright (C) Treasure Data

[2017/08/17 03:33:49] [ info] [engine] started
[0] tail.0: [1502940829.966728341, {"log"=>"aaa"}]
[0] tail.0: [1502940841.515776656, {"log"=>"bbb"}]
[0] tail.0: [1502940850.129314776, {"log"=>"ccc"}]
[0] tail.0: [1502940856.325415717, {"log"=>"ddd"}]
```
- then I clean flie and append other  content
```
echo eee > a.log 
echo fff >> a.log
```
Now can't get new record, like docker log if limit the log's max-size and max-file it will do a similar operation, so there is any way to deal with it?

**Comment by edsiper** [comment]
@VinkDong 

in_tail always follow the file changes like _tail -F_ command does. Meaning it keep tracks of the last position read, if you truncate the file (clear file content) Fluent Bit will not read new changes as there is no way to track backward changes.

When Docker engine rotates a file, what it does is that it rename the file, then Fluent Bit catch that change and assumes the file was rotated. The in a new scan to lookup for new files will pick up the new generated file by Docker engine.

**Comment by VinkDong** [comment]
I got it, Thanks
