### ISSUE TITLE
[ warn] [parser:apache] invalid time format %d/%b/%Y:%H:%M:%S %z

### ISSUE THREAD

**Issue by AmourLDY** [fluent/fluent-bit#3599]
Hi, I am a chinese user, In order to collect k8s cluster log I find the fluent-bit and use it.
I got a warning when I collect apache log.

My enviroment:
docker image version: `fluent/fluent-bit:1.7`
Apache LOG:  `{"log": "205.225.0.158 - - [04/Jun/2021: 6:07:15 +0000] \"GET /aerotonometry HTTP/1.0\" 404 2216\n","stream":"stdout", ,"time":"2021-06-04T06:07:15.332473464Z"}`

K8s configMap: 
```yaml 
[PARSER]
Name   apache2
Format regex
Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
Time_Key time
Time_Format %d/%b/%Y:%H:%M:%S %z
```
fluent-bit log 
```yaml
[ warn] [parser:apache] invalid time format %d/%b/%Y:%H:%M:%S %z for '04/Jun/2021: 8:14:40 +0000'\n","stream":"stderr","time":"2021-06-04T08:14:41.004108101Z"}
[error] [parser] cannot parse '04/Jun/2021: 8:16:06 +0000'\n","stream":"stderr","time":"2021-06-04T08:16:06.980142805Z"}
```
Is the same as [https://github.com/fluent/fluent-bit/issues/231]() ？

**Comment by agup006** [comment]
It looks like there is an extra space in the time format that is causing issues

from https://config.calyptia.com/#/regex (signup required)

Adding a space in the time format between %Y and %H allowed the parsing to occur

![image](https://user-images.githubusercontent.com/3642874/120900572-44aade80-c5ea-11eb-9858-89da66e9b9e3.png)

**Comment by AmourLDY** [comment]
oh so excited, very thanks
