### ISSUE TITLE
Regex Parser Output - Not well structured and not indexed as expected in ES

### ISSUE THREAD

**Issue by arniesaha** [fluent/fluent-bit#3608]
## Bug Report
Regex Parser -> output JSON not well-structured and hence not getting indexed in ES as expected

**To Reproduce**
- Rubular link if applicable: https://rubular.com/r/s57nUe3Ii0GjMB
- Example log message if applicable:
```
time="2021-06-07T18:21:48.936Z" level=info msg="Enforcing history limit for 'asdsa-atlan-jdbc-crawler-default-cron'" namespace=default workflow=asdsa-atlan-jdbc-crawler-default-cron
```
- Steps to reproduce the problem:

**Expected behavior**
Expecting a well structured json such that the are indexed as key/val in ES/Kibana to be searchable

**Screenshots**
![image](https://user-images.githubusercontent.com/3646287/121069876-a25a4900-c7eb-11eb-9e6b-df07045b9915.png)

**Your Environment**

* Version used: 1.7 
* Configuration: helm charts - https://github.com/fluent/helm-charts
* Environment name and version (e.g. Kubernetes? What version?): 1.17
* Server type and version: EKS

Following is the config I'm using:
```
    [INPUT]
        Name              tail
        Tag               argo
        Path              /var/log/containers/*argo*.log
        Parser            argo-parser
        DB                /var/log/flb_kube_argo.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
```
Note: logs are from argo containers

```
    [PARSER]
        Name          argo-parser
        Format        regex
        Regex         ^time="(?<time>[^ ]*)" level=(?<level>[^ ]*) msg="(?<msg>[\S^ ]*)" namespace=(?<namespace>[^ ]*) workflow=(?<workflow>[^ ]*)$
        Time_Key      time
        Time_Format   %Y-%m-%dT%H:%M:%S.%L
        Time_Keep     Off
        Decode_Field_As   escaped_utf8    log    do_next
        Decode_Field_As   json       log
```

```
    [FILTER]
        Name                kubernetes
        Match               argo
        Kube_Tag_Prefix     argo.kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
```

```
    [OUTPUT]
        Name            es
        Match           argo
        Host            uflog-elasticsearch-master
        Logstash_Format On
        Logstash_Prefix argo-container
        Retry_Limit     False
```

Have tried several different configurations referenced here: https://github.com/fluent/fluent-bit/issues/1278 as well as the latest documentation: https://docs.fluentbit.io/manual/

But, clearly something isn't working as expected or is breaking. 

Whereas, if container logs are json or if input type tcp, http are used -> The json is indexed as expected on ES. 

Any assistance in this much appreciated. 

Thanks!
Arnab

**Comment by agup006** [comment]
It might be easier to do the parsing in a parser filter after the Kubernetes filter

**Comment by arniesaha** [comment]
Hi @agup006 

Thanks for checking this! Yes, adding a different filter worked out in this case

The following change in the pipeline worked.. 

```
    [INPUT]
        Name              tail
        Tag               argo
        Path              /var/log/containers/*argo*.log
        Parser            docker
        DB                /var/log/flb_kube_argo.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
```
```
    [FILTER]
        Name                kubernetes
        Match               argo
        Kube_Tag_Prefix     argo.kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On

    [FILTER]
        Name                parser
        Match               argo
        Key_Name            log
        Parser              argo-parser
        Reserve_Data        On
        Preserve_Key        On
```

The output and parser sections are similar to what's described in the original post. 

Thanks again! Closing this :)
