### ISSUE TITLE
aarch64 Debian Package Build Error

### ISSUE THREAD

**Issue by joshughes** [fluent/fluent-bit#361]
Building with regular methods on aarch64 works but when executing ./debian.sh and specifically the `fakeroot debian/rules binary` I get the following error. 

```
brary/libmbedcrypto.a ../../library/libco.a ../../lib/libjemalloc_pic.a ../../lib/libonigmo.a ../../library/libsqlite3.a -ldl -Wl,-rpath,/fluent-bit-0.12.0/obj-aarch64-linux-gnu/lib
/usr/bin/ld: ../../bin/hello_world: hidden symbol `pthread_atfork' in /usr/lib/aarch64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
examples/hello_world/CMakeFiles/hello_world.dir/build.make:181: recipe for target 'bin/hello_world' failed
make[3]: *** [bin/hello_world] Error 1
make[3]: Leaving directory '/fluent-bit-0.12.0/obj-aarch64-linux-gnu'
CMakeFiles/Makefile2:3009: recipe for target 'examples/hello_world/CMakeFiles/hello_world.dir/all' failed
make[2]: *** [examples/hello_world/CMakeFiles/hello_world.dir/all] Error 2
make[2]: Leaving directory '/fluent-bit-0.12.0/obj-aarch64-linux-gnu'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/fluent-bit-0.12.0/obj-aarch64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
debian/rules:4: recipe for target 'binary' failed
make: *** [binary] Error 2
```

To reproduce the error you can use the following dockerfile. 

```
FROM resin/aarch64-debian:latest

CMD [ "/bin/bash" ]

ENV DEBIAN_FRONTEND noninteractive

RUN cross-build-start
# Install development packages
RUN apt-get update -y && apt-get install -y \
    build-essential \
    g++ \
    make \
    git

ENV FLB_VERSION 0.12.0
ENV FLB_TAR https://github.com/fluent/fluent-bit/archive/v$FLB_VERSION.zip

RUN apt-get install -y wget libpthread-stubs0-dev unzip cmake fakeroot lsb-base lsb-release bash  dh-make
RUN wget -O "fluent-bit-$FLB_VERSION.zip" --no-check-certificate $FLB_TAR 
RUN unzip "fluent-bit-$FLB_VERSION"
RUN cd fluent-bit-$FLB_VERSION &&\
    ./debian.sh

RUN cross-build-end
```

**Comment by joshughes** [comment]
this may or may not be relevant. 

https://answers.launchpad.net/ubuntu/+question/271372

**Comment by edsiper** [comment]
@joshughes 

do you need official deb packages for aarch64 ?, if so, would you please elaborate your use case meaning how Fluent Bit will be used  ? (this info is important to assign priority)

**Comment by joshughes** [comment]
We have a robot that runs on [TX2](http://www.nvidia.com/object/embedded-systems-dev-kits-modules.html). We would like to use fluent-bit to ship logs since Fluentd is a much larger package and also does not have ARM support. 

I can build my own package from the output of `make` in the meantime... but would like an official package or at least be able to build a single binary in the future. 

Our goal would eventually be to have thousands of robots in the field all using fluent-bit to send logs and possibly other diagnostic statistics for analysis and monitoring.

**Comment by joshughes** [comment]
and to clarify I am happy to build from a branch or implement a fix on a fork or something if the team can provide me with a little guidance. I don't need something official right away... I just want to get this working ASAP.

**Comment by joshughes** [comment]
@edsiper are you able to provide any advice or update on this?

**Comment by edsiper** [comment]
I am doing some tests, I will provide an update before the end of the week.

**Comment by edsiper** [comment]
I've pushed a test repo with the required package, would you please give it a try ?

```
deb http://packages.fluentbit.io/debian jessie main
```

then: 

```
$ apt-get install td-agent-bit
```

**Comment by edsiper** [comment]
@joshughes did u manage to test the package ?

**Comment by edsiper** [comment]
@joshughes ping

**Comment by joshughes** [comment]
@edsiper yes it worked... thank you!

**Comment by edsiper** [comment]
thanks.

I will push the new packages over the weekend (and update the docs)

**Comment by edsiper** [comment]
@joshughes please re-try

**Comment by edsiper** [comment]
packages are updated.
