### ISSUE TITLE
[Bug] Health input example error and SIGSEGV

### ISSUE THREAD

**Issue by verbunk** [fluent/fluent-bit#3615]
## Bug Report

**Describe the bug**
Running the example from the docs for health yields error,

`./td-agent-bit -i health://127.0.0.1 -o stdout
Error: Invalid input type. Aborting`

Running by taking cues from process and setting params crashes.

`./td-agent-bit -i health -p host=127.0.0.1 -p port=80 -o stdout
Fluent Bit v1.7.4
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/06/09 23:03:05] [ info] [engine] started (pid=45480)
[2021/06/09 23:03:05] [ info] [storage] version=1.1.1, initializing...
[2021/06/09 23:03:05] [ info] [storage] in-memory
[2021/06/09 23:03:05] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/06/09 23:03:05] [ info] [sp] stream processor started
[2021/06/09 23:03:05] [engine] caught signal (SIGSEGV)
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)Aborted (core dumped)`

**Your Environment**
* Version used: 1.7.4
* Configuration: No conf, running on CLI
* Environment name and version (e.g. Kubernetes? What version?): linux / RHEL
* Operating System and version: RHEL 8
* Filters and plugins: health

**Comment by nokute78** [comment]
I sent a patch to fix SIGSEGV #3629 
But it still be buggy if the patch is applied.
