### ISSUE TITLE
fluent-bit can support multiple parser  in kubernetes one pod multiple cotainers?

### ISSUE THREAD

**Issue by DeyunLuo** [fluent/fluent-bit#3616]
I hava one problem to parser the docker json log in one pods.
If one pod has two containers nginx and apache 
the log file directory like this
```json
# /var/log/pods/default_my-nginx-77b9765968-v5rhd_737fef9a-0932-4ee9-a293-2724e674d129/my-nginx
{"log":"2021-06-09T08:10:32+00:00 172.23.38.61 - - 172.18.9.217 \"GET /app/kibana HTTP/1.1\" 200 16554 \"http://172.23.38.61:80/\" \"kube-probe/1.15\" 0.089\n","stream":"stderr","time":"2021-06-10T02:55:41.236003786Z"}

# /var/log/pods/default_my-nginx-77b9765968-v5rhd_737fef9a-0932-4ee9-a293-2724e674d129/my-apache
{"log":"47.29.201.179 - - [28/Feb/2019:13:17:10 +0000] \"GET /?p=1 HTTP/2.0\" 200 5316 \"https://domain1.com/?p=1\" \"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36\" "2.75"","stream":"stderr","time":"2021-06-10T02:55:41.236003786Z"}
```
I want to parse the log
I know the kubernetes parser support K8S-Logging.Parser according the pod annotations, but I want to parse the json's key log. parse result like:
```bash
# nginx container log
{
  "parsed": {
    "time_iso8601": "2021-06-09T08:10:32+00:00",
    "host": "172.23.38.61",
    "http_client_ip": "-",
    "http_x_haproxy_for": "-",
    "remote_addr": "172.18.9.217",
    "method": "GET",
    "path": "/app/kibana",
    "status": "200",
    "body_bytes_sent": "16554",
    "http_referer": "http://172.23.38.61:80/",
    "http_user_agent": "kube-probe/1.15",
    "request_time": "0.089"
  }
}
# apache log
{
  "parsed": {
    "host": "127.0.0.1",
    "user": "frank",
    "method": "GET",
    "path": "/apache_pb.gif",
    "code": "200",
    "size": "2326",
    "referer": "http://www.example.com/start.html",
    "agent": "Mozilla/4.08 [en] (Win98; I ;Nav)"
  }
}
```
I dont't know how to implement it, 
the parser kubernetes has one key called Merge_Parser, this key not support annotations ?
It means every container  need to write one parser config file ?

**Comment by m44soroush** [comment]
@DeyunLuo Did you find the solution?

**Comment by DeyunLuo** [comment]
> 

you can try this K8S-Logging.Parser
https://docs.fluentbit.io/manual/pipeline/filters/kubernetes

**Comment by m44soroush** [comment]
thank you @DeyunLuo , can I ask you another question?
I installed fluent-bit on my k8s cluster via helm chart, and this is the default config of k8s filter:
```
[FILTER]
    Name kubernetes
    Match kube.*
    Merge_Log On
    Keep_Log Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude On
```
There are lots of pods in the cluster, and among them I have ingress-nginx controller pod, and also logs output is elasticsearch.
By default the nginx log is not parsed and kibana is showing logs like this:
```
...
    "log": [
      "10.0.0.173 - - [23/Dec/2021:07:10:42 +0000] \"GET / HTTP/2.0\" 200 47706 \"https://test.com" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\" 59 0.011 [test-frontend-client-3000] [] 10.232.87.52:3000 47743 0.012 200 ...\n"
    ],
...
```
according to the docs you've sent, I should create [PARSER] config in fluent-bit for nginx and add annotation to nginx controller pod, right?

**Comment by DeyunLuo** [comment]
> thank you @DeyunLuo , can I ask you another question? I installed fluent-bit on my k8s cluster via helm chart, and this is the default config of k8s filter:
> 
> ```
> [FILTER]
>     Name kubernetes
>     Match kube.*
>     Merge_Log On
>     Keep_Log Off
>     K8S-Logging.Parser On
>     K8S-Logging.Exclude On
> ```
> 
> There are lots of pods in the cluster, and among them I have ingress-nginx controller pod, and also logs output is elasticsearch. By default the nginx log is not parsed and kibana is showing logs like this:
> 
> ```
> ...
>     "log": [
>       "10.0.0.173 - - [23/Dec/2021:07:10:42 +0000] \"GET / HTTP/2.0\" 200 47706 \"https://test.com" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36\" 59 0.011 [test-frontend-client-3000] [] 10.232.87.52:3000 47743 0.012 200 ...\n"
>     ],
> ...
> ```
> 
> according to the docs you've sent, I should create [PARSER] config in fluent-bit for nginx and add annotation to nginx controller pod, right?

yes, you can see this [Kubernetes Annotations](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations)
