### ISSUE TITLE
td-agent-bit should sign repo metadata for yum/dnf repos

### ISSUE THREAD

**Issue by justchris1** [fluent/fluent-bit#3618]
**Is your feature request related to a problem? Please describe.**
td-agent-bit won't operate as a repo on Redhat / Centos 8 (maybe 7 as well?) machines if repo_gpgcheck=1 is specified in the /etc/yum.repos.d configuration file.  This prevents the repo metadata from be cryptographically validated to increase the confidence that the proper updates are being applied/installed.

**Describe the solution you'd like**
TD should sign its metadata in the yum/dnf repository that it distributes so that it can be validated.

**Describe alternatives you've considered**
No other automated options to validate metadata published by a yum/dnf repository exist in Redhat / Centos distributions.

**Additional context**
Some high compliance environments are not permitted to use repositories unless repo_gpgcheck=1 due to the potential avenues for targeted attacks on systems.  Signing repository metadata enables users to be assured that the published data is valid and made available by the signer.  If you enable repo_gpgcheck=1, the output is as follows:
```
TD Agent Bit                                                                                                                                                                 8.9 kB/s | 1.7 kB     00:00    
TD Agent Bit                                                                                                                                                                 374  B/s | 162  B     00:00    
TD Agent Bit                                                                                                                                                                 9.7 kB/s | 1.7 kB     00:00    
TD Agent Bit                                                                                                                                                                 365  B/s | 162  B     00:00    
Errors during downloading metadata for repository 'td-agent-bit':
  - Status code: 404 for https://packages.fluentbit.io/centos/7/x86_64/repodata/repomd.xml.asc (IP: 139.178.85.103)
Error: Failed to download metadata for repo 'td-agent-bit': GPG verification is enabled, but GPG signature is not available. This may be an error or the repository does not support GPG verification: Status code: 404 for https://packages.fluentbit.io/centos/7/x86_64/repodata/repomd.xml.asc (IP: 139.178.85.103)

```

**Comment by justchris1** [comment]
This is still an issue.  Please do not close.

**Comment by justchris1** [comment]
This issue is unaddressed and is still an issue.

**Comment by kenhys** [comment]
FYI:

Expected td-agent-bit.repo

```
[td-agent-bit]
name = TD Agent Bit
baseurl = https://packages.fluentbit.io/centos/7/$basearch/
gpgcheck=1
gpgkey=https://packages.fluentbit.io/fluentbit.key
enabled=1
repo_gpgcheck=1
```

What should be done:

```
gpg --detach-sign --armor --local-user F209D8762A60CD49E680633B4FF8368B6EA0722A centos/7/x86_64/repodata/repomd.xml
```

It will generates centos/7/x86_64/repodata/repomd.xml.asc.

**Comment by justchris1** [comment]
This issue is unaddressed and is still an issue.

**Comment by justchris1** [comment]
I believe this is actually fixed as I was prompted to trust the new keys in the repo.  I will need to double check tomorrow on a clean build.  I tried verifying on a FIPS machine, but that is still failing.  However, this ticket is only focused on the repo_gpgcheck.  I will build a clean machine without FIPS mode tomorrow to verify.

**Comment by justchris1** [comment]
I verified that (in non-fips mode) that `repo_gpgcheck=1` is now supported.  I might recommend that you update the install instructions for the repo file to include this for added security: https://docs.fluentbit.io/manual/installation/linux/redhat-centos#configure-yum

**Comment by patrick-stephens** [comment]
Yeah I will aim to do that next chance I get but feel free to submit a PR here: https://github.com/fluent/fluent-bit-docs/blob/master/installation/linux/redhat-centos.md

Glad it's sorted anyway.

**Comment by justchris1** [comment]
@patrick-stephens I created PR #752

**Comment by patrick-stephens** [comment]
Cheers, I merged that. During testing of other updates to packaging I realised we also need to update the one-line install script as well: `install.sh`

**Comment by patrick-stephens** [comment]
@justchris1 you'll be happy to know that staging tests picked up a problem with this in the latest build staging build (i.e. not released) so hopefully we should prevent any regressions.
