### ISSUE TITLE
NO_PROXY checking does not function as documented.

### ISSUE THREAD

**Issue by AbrohamLincoln** [fluent/fluent-bit#3619]
## Bug Report

As documented, the NO_PROXY values should follow the curl convention:  
https://github.com/fluent/fluent-bit/blob/03f3339594bdb472315823db78ca209b7ba319fb/include/fluent-bit/flb_config.h#L161-L167

Curl will match on domains as well as hosts.  For example; a host of `www.example.com` will match a NO_PROXY entry of `.example.com`.  The current NO_PROXY implementation appears to perform an exact match of host to the NO_PROXY entry.  
https://github.com/fluent/fluent-bit/blob/eb77d0953f27b000695a941900655152372f13c1/src/flb_upstream.c#L282

This is the curl implementation for reference:
https://github.com/curl/curl/blob/d8dcb399b8009df09551fca3f58ed85cead07bbe/lib/url.c#L2179-L2256

**Expected behavior**
Setting `HTTP_PROXY="proxy.example.com:1234"` and `NO_PROXY="127.0.0.1,localhost,.svc.cluster.local,.default.svc"` results in external requests being made via the proxy and internal requests being directly.

**Comment by pranavmarla** [comment]
bump

**Comment by pranavmarla** [comment]
bump
