### ISSUE TITLE
Add 'fluentbit.io/include' (opposite of 'fluentbit.io/exclude') annotation

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit#3620]
**Is your feature request related to a problem? Please describe.**
Currently, Fluent Bit supports an opt-**out** annotation that tells Fluent Bit to ignore certain Kubernetes pods when collecting logs: `fluentbit.io/exclude` ([link](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#request-to-exclude-logs))

This works great if we want Fluent Bit to monitor most of the pods in a cluster, and only want to ignore a few pods.

However, if we have the opposite situation -- i.e. we want Fluent Bit to IGNORE most of the pods in a cluster, and only want to MONITOR a few pods -- then this is very inconvenient, since we need to add the same opt-out annotation to the majority of the pods, which takes more time and effort.

**Describe the solution you'd like**
It would be convenient to have a new opt-**in** annotation (`fluentbit.io/include`) that performs the opposite function to the existing annotation: i.e. Fluent Bit will only collect logs from pods containing the opt-in annotation, and will ignore all other pods.

**Describe alternatives you've considered**
N/A

**Additional context**
This is particularly useful when migrating large clusters from a different log collection agent to Fluent Bit. Initially only a few pods will have completed the migration and will be ready for Fluent Bit so, with an opt-**in** annotation, you only have to modify those few pods.
Right now though, because you only have an opt-**out** annotation, you have to put in a lot more work and modify the majority of the pods (that are not yet ready to be migrated) to ensure that Fluent Bit does not collect their logs.

**Comment by pranavmarla** [comment]
bump

**Comment by pranavmarla** [comment]
bump

**Comment by pranavmarla** [comment]
bump

**Comment by anekdoti** [comment]
In our case, we have a lot of components that are externally implemented and do not necessarily adher to our logging conventions. In this scenario, it would be very helpful to have an opt-in model instead of opt-out.
