### ISSUE TITLE
Parser Filter not works well

### ISSUE THREAD

**Issue by keyolk** [fluent/fluent-bit#363]
from this, https://github.com/fluent/fluent-bit/issues/348
I tried it with 0.12 of fluent-bit

first I tested 
```
[INPUT]
    Name Tail
    Tag dockerd
    Path /fluent-bit/var/log/dockerd.log
    Mem_Buf_Limit 10MB
    Rotate_Wait 5
    Refresh_Interval 10
    Parser dockerd
```
it's parser works well

```
[INPUT]
    Name Tail
    Tag dockerd
    Path /fluent-bit/var/log/dockerd.log
    Mem_Buf_Limit 10MB
    Rotate_Wait 5
    Refresh_Interval 10

[FILTER]
    Name parser
    Match dockerd
    Parser dockerd
    Key_Name *
```
but it doesn't work at all.
Changing Key_Name to "dockerd", "level", "msg", "time" also doenst affect to
Is there a way to debug filter parser ?

below is my parser
```
[PARSER]
  Name dockerd
  Format regex
  Regex time="(?<time>[^ ]*)" level=(?<level>[^ ]*) msg="(?<msg>[^ ].*)"
  Time_Key time
  Time_Format %Y-%m-%dT%H:%M:%S.%L%Z
```

I strongly need parser filter with forward input : (

**Comment by nokute78** [comment]
Could you try to test `Key_Name log` ?

in_tail sends record like `"log":"a line of log"` by default .
That configuration is to parse the field of "log".

**Comment by keyolk** [comment]
@nokute78 You saved me : D
