### ISSUE TITLE
Basic Security for ES output

### ISSUE THREAD

**Issue by joechromo** [fluent/fluent-bit#364]
We do not have Elastic X-Pack access set up in our ES cluster, however we do have HTTP basic security set up for our ES endpoint.  

First question, do we need to have X-Pack set up for basic security config to work?

(Documentation suggests X-Pack is needed for basic security -
 http://fluentbit.io/documentation/0.11/output/elasticsearch.html )

Secondly, if X-Pack is not required, what would be causing the following error in the td-agent-bit logs- 

.... td-agent-bit[22057]: [2017/08/23 20:30:46] [error] [tls] SSL error: NET - Connection was reset by peer
.... td-agent-bit[22057]: [2017/08/23 20:30:46] [error] [src/flb_http_client.c:754 errno=25] Inappropriate ioctl for device

My configuration for es output is as follows: 

[OUTPUT]
    Name  es
    Match *
    Host  {{ elastic_search_host }}
    Port  443
    Index fluent-bit
    Type  {{ ansible_product_serial }}_logs
    HTTP_User {{ elastic_search_user_name }}
    HTTP_Passwd {{ elastic_search_password }}
    tls        On
    tls.verify Off
    tls.ca_file /etc/pki/tls/certs/ca-bundle.crt

Tried several combinations of tls on/off and tls.verify on/off

**Comment by edsiper** [comment]
which version of Fluent Bit are you using ?

**Comment by joechromo** [comment]
Version     : 0.11.15

**Comment by edsiper** [comment]
for some reason your load balancer or proxy where Fluent Bit is connecting to is closing the connection:

```
[2017/08/23 20:30:46] [error] [tls] SSL error: NET - Connection was reset by peer
```

do you have access to that service logs ?

note: not related but I strongly suggest you upgrade to v0.12.0 or v0.11.17 version

**Comment by joechromo** [comment]
@edsiper 

So we figure out the issue with the connection.  It was being rejected by our proxy:

**Comment by joechromo** [comment]
Now I am seeing a buffer size issue for the tail input - 

td-agent-bit[21810]: [2017/08/24 15:33:39] [error] [in_tail] file=/var/log/messages requires a larger buffer size, lines are too long. Skipping file.

So I have upgraded to v0.12.0 and will try to use the new system d input config as an alternative to regex match on giant catch-all log (/var/logs/messages)

**Comment by joechromo** [comment]
@edsiper 

so now we are getting this: 

td-agent-bit[32331]: Input plugin 'systemd' cannot be loaded
td-agent-bit[32331]: Error: Configuration file contain errors. Aborting
td-agent-bit[32331]: Fluent-Bit v0.12.0

My new config is as follows- 
[INPUT]
    Name            systemd
    tag             logs_gateway
    Systemd_Filter  _SYSTEMD_UNIT=enablement-gateway.service

Any suggestions on what might be causing this?

**Comment by edsiper** [comment]
regarding the in_tail part, that error means that someline (or multiple ones) are bigger than 32kb (a very long line), please adjust the value Buffer_Chunk_Size option as described in [Tail documentation](http://fluentbit.io/documentation/0.12/input/tail.html)

abouto systemd , please set Log_Level trace in your main SERVICE section, e.g:

[SERVICE]
    Log_Level  trace
    ...

**Comment by joechromo** [comment]
I get nothing extra in the logs... same message.  Do you know if anyone has successfully used systemd plugin with td-agent-bit?

**Comment by edsiper** [comment]
Yes, it's being used in Kubernetes without problems. 

What about if in your OUTPUT/systemd section you append:

```
path /var/log/journal
```
or any alternative path where your Journal log files are located ?

**Comment by joechromo** [comment]
I am not 100% sure what you mean be that.. I am using an ES output config.  Are you saying to switch that too a file output and forward logs to a file in /var/journal?

**Comment by edsiper** [comment]
When using the systemd plugin, this one is failing. As a workaround I would like to see what's the behavior if you specify a manual path for systemd journal files, e.g:

```
[INPUT]
    Name systemd
    tag logs_gateway
    Systemd_Filter _SYSTEMD_UNIT=enablement-gateway.service
    path /var/log/journal
```

**Comment by joechromo** [comment]
Still get the exact same result in the logs.. Not sure if it makes a difference, but we are using fluentbit on remote servers deployed in the field running Fedora 25.  The way we are installing the RPM is by building using fluent-bit packaging:

./build.sh 0.12.0 fedora/25

**Comment by edsiper** [comment]
hmm note that build rules for Fedora is not including systemd devel libraries which are required

**Comment by joechromo** [comment]
I installed systemd-devel with dnf: 

```
sudo dnf info systemd-devel
Last metadata expiration check: 0:00:38 ago on Thu Aug 24 18:27:20 2017.
Installed Packages
Name        : systemd-devel
Arch        : x86_64
Epoch       : 0
Version     : 231
Release     : 17.fc25
Size        : 254 k
Repo        : @System
From repo   : updates
Summary     : Development headers for systemd
URL         : http://www.freedesktop.org/wiki/Software/systemd
License     : LGPLv2+ and MIT
Description : Development headers and auxiliary files for developing applications linking
            : to libudev or libsystemd.


```

still getting the same issue

**Comment by edsiper** [comment]
would you please retry packaging version 0.12 ?, I've updated fluent-bit-packaging repo, I suspect the __build container__ miss the systemd dev package (which is a must)

**Comment by edsiper** [comment]
Closing this issue assuming systemd devel was missing when building Fluent Bit (similar problems reported by other users).

If the issue persists, we can re-open it.
