### ISSUE TITLE
in_http plugin to support different return code

### ISSUE THREAD

**Issue by rikatz** [fluent/fluent-bit#3644]
**Is your feature request related to a problem? Please describe.**
Looking to in_http plugin to receive some webhook logs, I've figured out that some services (like Minio) expect the return code of the webhook to be 200-OK.

fluentbit plugin returns 201-CREATED, which is not supported by some services that tend to mark this webhook as unhealthy.

Other projects (most notably Fluentd and logstash) have this option configurable, or returns 200-OK so this does not show to be a problem there

**Describe the solution you'd like**
Turn the in_http plugin return code configurable between at least 200 or 201 return codes

**Describe alternatives you've considered**

**Additional context**
thread started [here](https://fluent-all.slack.com/archives/C0CTQGHKJ/p1623690720190300)

**Comment by nokute78** [comment]
I sent a patch https://github.com/fluent/fluent-bit/pull/3669
