### ISSUE TITLE
Source download of v1.7.9 is not available

### ISSUE THREAD

**Issue by kishaningithub** [fluent/fluent-bit#3672]
## Bug Report

**Describe the bug**
The URL https://fluentbit.io/releases/1.7/fluent-bit-1.7.9.tar.gz gives a 404

**To Reproduce**

```bash
$ wget https://fluentbit.io/releases/1.7/fluent-bit-1.7.9.tar.gz
```

**Expected behavior**
The source should get downloaded

**Comment by nokute78** [comment]
Currently, the link is not broken.
Can you check it again ?

**Comment by kishaningithub** [comment]
The sources are available now


Closing the issue
