### ISSUE TITLE
S3 Output Compression not working

### ISSUE THREAD

**Issue by justchris1** [fluent/fluent-bit#3676]
## Bug Report

**Describe the bug**
Using td-agent-bit version 1.7.8 with the S3 output, the compression setting seems to be ignored, even when using `use_put_object true`

**To Reproduce**
Here is my configuration of the output s3 block.  
```
[OUTPUT]
    name s3
    match *
    region us-east-2
    bucket my-bucket-name
    s3_key_format /fluent-bit-logs/$TAG/%Y/%m/%d/%H/%M/%S/$UUID.gz
    use_put_object On
    total_file_size 40M
    upload_timeout 1m
    compression gzip
```
Regardless if compression setting is missing (inferring none) or present with gzip, the uploaded files are always cleartext / uncompressed.

**Expected behavior**
Logs uploaded would be compressed with gzip before upload.

**Your Environment**
* Version used: 1.7.8
* Configuration: (See above)
* Environment name and version (e.g. Kubernetes? What version?): RPM install
* Server type and version: AWS t3a instance
* Operating System and version:  Centos 8, fully patched as of 2021-06-23
* Filters and plugins: none

I can find nothing in the error logs about a failed compression.  Every upload, I get a 'happy' message: `Successfully uploaded object`.  However, the file is still cleartext.  I saw references in @PettitWesley thread in #2700 that this was working, so I am unsure if this is a regression or something else.

**Comment by mtparet** [comment]
I have the same issue, I wondering if setting the content encoding to gzip is the issue. Does S3 automatically decompress the file on its side ?

**Comment by justchris1** [comment]
> I have the same issue, I wondering if setting the content encoding to gzip is the issue. Does S3 automatically decompress the file on its side ?

I know of no AWS S3 function that would be capable of doing that.  S3 is just an object store.  I verified this issue by downloading the S3 object directly after it was uploaded to eliminate the fluentd input that was pulling it down as the source of the problem.

**Comment by mtparet** [comment]
AWS S3 is capable of that, it is written directly in the documentation.

> Content-Encoding
Specifies what content encodings have been applied to the object and thus what decoding mechanisms must be applied to obtain the media-type referenced by the Content-Type header field. For more information, see

https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

**Comment by justchris1** [comment]
I should have been more specific in my reply, my apologies.  Certainly the
Content-Type field is available to store what you want in it.  However, to
my knowledge, S3 won't mutate the data object stored in any way based on
the value of that field.

**Comment by canidam** [comment]
I have the same issue using **fluent/fluent-bit:1.7.9**. Any idea if the configuration is wrong, or this is an actual bug?

Is it possible there's a threshold for compression? for example, if the file is less than 1K it skips the compression part?

**Comment by justchris1** [comment]
> I have the same issue using **fluent/fluent-bit:1.7.9**. Any idea if the configuration is wrong, or this is an actual bug?

Nope.  I haven't even seen any comment from someone at the project even acknowledging the issue.

**Comment by PettitWesley** [comment]
@DrewZhang13 @zhonghui12

**Comment by DrewZhang13** [comment]
ACK, issue is reproduced with the same config and fluent bit version. 
The uploaded file is always cleartext / uncompressed.

**Comment by DrewZhang13** [comment]
After some more test, the file will auto decompressed if downloaded on Macbook, but uploaded file is already compressed after size-based comparison.
So I didn't see the real uncompressed file issue in my testing machine.

Could you provide the comparison of size for the file uploaded in S3 and in your local before uploaded to confirm if it's really uncompressed?

**Comment by justchris1** [comment]
> @justchris1 @mtparet After some more test with the same config provided in this issue, the file will auto decompressed if downloaded on Macbook, but uploaded file in S3 is already compressed after size-based comparison.
> So I didn't see the real uncompressed file issue in my testing machine.
> 
> Could you provide the comparison of size for the file uploaded in S3 and in your local before uploaded to confirm if it's really uncompressed?

@DrewZhang13 - When I was debugging this, I eliminated the automated ingestion of the file into fluentd on the other side.  To confirm it was uncompressed, I downloaded the file directly from S3 after it was uploaded by fluent-bit.  When I inspect the file stored in S3, it is uncompressed.  S3 has no 'auto-compress' or 'uncompress' functions, so downloading it represents what was stored in S3.  The content is plaintext & readable.

**Comment by DrewZhang13** [comment]
@justchris1 So i have verified from both Macbook and Linux, no similar uncompressed situation comes at my side. 
I used the same configuration you provided and compared the file I download from S3. 
The file size I download is 679B before decompression and 31KB after decompression. 
I could use VI to see the cleartext when the file is compressed. I wonder if this is the situation you mean for the cleartext?

**Comment by justchris1** [comment]
> I could use VI to see the cleartext when the file is compressed. I wonder if this is the situation you mean for the cleartext?

No, I meant from a 'dumb' text editor like Windows Notepad.  When I download the file that was uploaded by fluent-bit with the configuration file shown in the issue from the AWS console, I am able to open the file in Notepad immediately and see clear text.

**Comment by canidam** [comment]
@DrewZhang13 
There's a weird behavior here. I've a file on S3 with the size 2.3KB
When I download it on my Mac, the size grows to 17K and the file type is `JSON Data`

```
➜ file 0N285h0f.gz
0N285h0f.gz: JSON data
```

I did another test. I use fluentd to consume these log files, and when I use `text` type it prints binary data. When I use `gzip` type, it works. So I guess compression works, but something weird is going on when downloading the objects from S3 on a Mac.

**Comment by DrewZhang13** [comment]
@canidam yeah Mac will automatically decompressed when you download from S3. I think this is the reason why you are seeing wired behavior.

**Comment by justchris1** [comment]
I still see this behavior.  Please do not close.

**Comment by ssc-ksaitou** [comment]
This is occurred by the attribute "Content-Encoding: gzip" tagged with the log.gz file fluent-bit have uploaded.

![image](https://user-images.githubusercontent.com/22065693/135614714-3f5c617f-0889-4a43-a626-890104cc279e.png)

When you download the file tagged as `Content-Encoding: gzip`, user agent (e.g. Chrome, curl) will automatically decode the content as same as downloading gzipped stream on HTTP since `Content-Encoding: gzip` header is appended to the response header.
Yes, it's obviously been compressed on S3.

An easy solution is to just remove off `.gz` extension from `s3_key_format`.

There seems to be no way to turn off `Content-Encoding: gzip`.

**Comment by justchris1** [comment]
This would not explain why I would get parsing errors in fluentd with compression turned on (and the corresponding configuration in fluentd indicating it was compressed, but working immediately after disabling the fluentd side only to indicate no compression).  I still see this behavior. Please do not close.

**Comment by justchris1** [comment]
I still see this behavior.  Issue is not resolved.

**Comment by gjirm** [comment]
I can see this behavior on multiple systems too with fluentbit 1.8.10 (standalone fluentbit and fluentbit in the docker container). I also experienced this behavior on previous 1.8.x versions.

This is my config:

```
[OUTPUT]
    Name                            s3
    Match                           auth
    bucket                          server-logs
    region                          eu-west-1
    tls                             On
    s3_key_format                   /auth-logs/$TAG/%Y/%m/%d/h%H/%M-$UUID.gz
    s3_key_format_tag_delimiters    .-_
    compression                     gzip
    use_put_object                  On
    total_file_size                 50M
    upload_timeout                  10m
```

**Comment by Spritekin** [comment]
I don't think this is working.
I have a similar configuration to the ones reported before:
```
        [OUTPUT]
            Name s3
            Match *
            bucket mybucket
            region ap-southeast-2
            store_dir /home/ec2-user/buffer
            s3_key_format /logging/$TAG[2]/$TAG[0]/%Y/%m/%d/%H/%M/%S/$UUID.gz
            s3_key_format_tag_delimiters .-
            compression gzip
            use_put_object On
            total_file_size 50M
```

And I got my files in S3. I.E.
s3://mybucket/fluentbit/log/kube/2022/02/23/01/35/48/15BRQR03.gz

Then I select the file in S3 and in the object actions I select "Query with S3 Select"
<img width="1055" alt="Screen Shot 2022-02-23 at 4 05 42 pm" src="https://user-images.githubusercontent.com/13467740/155264625-87251652-ef4f-4224-bdf0-3ab6ae8de47e.png">

So in the S3 select I configure like:

<img width="626" alt="Screen Shot 2022-02-23 at 4 08 53 pm" src="https://user-images.githubusercontent.com/13467740/155264903-91f04f1d-78dc-46c2-970d-327cc9b2fb97.png">
<img width="668" alt="Screen Shot 2022-02-23 at 4 08 23 pm" src="https://user-images.githubusercontent.com/13467740/155264931-2c3965d4-44eb-4f18-9413-15e99a8ef975.png">

Now you will notice I select one JSON per line and gzip compression as it is the expected output, however it returns an error that says GZIP is not applicable.

However, if I change the compression to None, I get a proper response on the same query:
<img width="950" alt="Screen Shot 2022-02-23 at 4 14 28 pm" src="https://user-images.githubusercontent.com/13467740/155265430-535a2c7a-7670-4d73-913f-3b9518bf5443.png">

While I got a Mac, these queries are being run inside AWS and the files won't touch my laptop so I can say with a level of certainty the files are not being gzipped.

**Comment by marcosdiez** [comment]
It works for me (i.e. I checked on S3 and the results are gzipped. Athena can read them because the files end with `.gz`). Here are my settings:
```
[OUTPUT]
    name s3
    match *
    bucket XXXXXXXXXXXXX
    region us-east-1
    s3_key_format /prod-sslv-nginx/$TAG/%Y/%m/%d/%H/%M/%S-$UUID.gz
    total_file_size 1M
    upload_timeout 1m
    compression gzip
```

**Comment by Spritekin** [comment]
@marcosdiez 

Sure I tried that, please read my result. Maybe it has been fixed but I was using a recent helm installation.
```
  repository = "https://fluent.github.io/helm-charts"
  chart      = "fluent-bit"
  version    = "0.19.19"
```

One thing, not sure that configuration you use works as I'm quite sure you need to set the "use_put_object On" option (I got an error saying I had to turn in on when I omitted the option and the container wouldn't start). If you don't get the error then its another sign the version you are testing might have been updated.

**Comment by PettitWesley** [comment]
@Spritekin Compression has always only worked wtih Use_Put_object On

**Comment by Spritekin** [comment]
@PettitWesley 
I'm not claiming otherwise, as you can see in my analysis above the flag is configured. My comment was because Marcos submitted a configuration with the gzip compression enabled but no "use_put_object On" option and said it worked ok. I just pointed his config would be wrong because the use_put_object flag was not set.

**Comment by logston** [comment]
```
$ aws --profile 1234567890 s3 cp s3://mybucket/path/to/file/ItWLhdDe.log.gz ~/Downloads/ItWLhdDe.log.gz
$ ls -la ~/Downloads/ItWLhdDe.*
-rw-r--r--  1 paul  staff  2554 Mar 15 17:00 /Users/paul/Downloads/ItWLhdDe.log.gz
$ gunzip ~/Downloads/ItWLhdDe.log.gz
$ ls -la ~/Downloads/ItWLhdDe.*     
-rw-r--r--  1 paul  staff  22264 Mar 15 17:00 /Users/paul/Downloads/ItWLhdDe.log
```
WHY CHROME, WHY!?

**Comment by afroald** [comment]
I experience this exact issue, please reopen.

**Comment by xposionn** [comment]
for who still facing this issue.
After deep dive, seems that compression does work but taking a look in the response header seems my .log (which compressed into .gz) has a content-type of application/octet-stream.
After adding  `content_type text/plain` in the s3 output plugin config, the downloaded file has .txt end instead of .gz (which was compressed on s3 but decompressed after downloading with wrong file extension.)

**Comment by dnguyen-anomali** [comment]
It down not work
