### ISSUE TITLE
0.12.0 docker image has 0.12.1 executable

### ISSUE THREAD

**Issue by adinaclaudia** [fluent/fluent-bit#369]
Hi,

We are using fluent-bit docker images and pinning them to a last known good version. We also have a process that reprovisions regularly, which means the docker images are pulled from docker hub every time fresh. And we noticed that fluent-bit docker image 0.12.0 actually contains executable version 0.12.1, which is not what we wanted. If we wanted to get the latest patch version, we would pin to 0.12 and then expect to get any available updates. In our case, we want to update consciously to a new version, in order not to get surprises.

This isn't the first time either, we had the same issue before with 0.11.13 docker image that at one point contained 0.11.15 executable. Usually, we probably wouldn't notice this, but we do notice when logging does not work anymore as expected, probably because of a change that is introduced.

Is it possible that in your build process, you don't overwrite tags for previous patch versions and just tag the minor version (like 0.12)?

Thank you,
Adina

**Comment by edsiper** [comment]
hi @adinaclaudia 

thanks for raising this issue. Effectively the source image does not have proper tagging, I will make sure to fix that in the following days

**Comment by adinaclaudia** [comment]
@edsiper thank you, that would be very helpful for us

**Comment by edsiper** [comment]
@adinaclaudia what's your company name ?

**Comment by adinaclaudia** [comment]
@edsiper I am working for Haufe :)

**Comment by edsiper** [comment]
@adinaclaudia 

new images are properly tagged and aligned: 

- fluent/fluent-bit:0.12.1   -> Fluent Bit 0.12.1
- fluent/fluent-bit:0.12.2   -> Fluent Bit 0.12.2 (released today)

**Comment by edsiper** [comment]
images documented here:

http://fluentbit.io/documentation/0.12/installation/docker.html

**Comment by adinaclaudia** [comment]
@edsiper Thank you, it works as expected now!
