### ISSUE TITLE
Specifying Splunk metadata in raw event broken in v1.7.5+

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluent-bit#3699]
## Bug Report

**Describe the bug**
v`1.7.5` broke the [Splunk output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/splunk), and it remains broken as of v`1.8.2`: 
Specifically, it is no longer possible to customize the 'reserved' Splunk metadata (eg. `index`, `source`, etc.) by configuring `splunk_send_raw on` as described [here](https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/splunk#data-format) and specifying the Splunk metadata in the top-level of the record -- it is treated as if `splunk_send_raw` was set to `off` (i.e. the Splunk metadata in the top-level of the record is treated as part of the actual log).

**To Reproduce**
Steps to reproduce the problem:
- Create a Fluent Bit config that uses the `splunk_send_raw on` feature to inject Splunk metadata into the record:
This can be any config similar to the sample one given [here](https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/splunk#data-format). 
Eg.:
```
[INPUT]
  ...

# Nest the entire log that exists at this point under the 'event' key
[FILTER]
  name                nest
  match               *
  operation           nest
  wildcard            *
  nest_under          event

# Add Splunk metadata to the top level of the record
[FILTER]
  name                modify
  match               *
  add                 index my-index
  add                 source my-source

[OUTPUT]
  name                splunk
  match               *
  host                http-inputs-....com
  port                443
  tls                 on
  tls.verify          on
  splunk_token        ...
  # Enable raw mode
  splunk_send_raw     on
```
- Set the Fluent Bit version < `1.7.5` -- see that, in Splunk, the record has been processed as expected -- i.e. the log has been extracted from the `event` key and the Splunk metadata has been set to the values specified in our Splunk metadata keys.
- Change the Fluent Bit version to >= `1.7.5` -- see that the record in Splunk has NOT been processed as expected -- the `event` key and our Splunk metadata keys are treated as part of the log itself (i.e. as if `splunk_send_raw` was set to `off`).

**Expected behavior**
See above.

**Screenshots**
(Unnecessary info redacted)

The below screenshots were produced by the exact same Fluent Bit configuration -- the only change (which broke the log processing in Splunk) was changing the Fluent Bit version. Note that `splunk_send_raw` is set to `on`.

- `1.7.4`: Splunk successfully extracts the log from the `event` key; Splunk metadata is set to the values we specified in the Splunk metadata keys
![good](https://user-images.githubusercontent.com/6486632/123712275-ff23af00-d83f-11eb-9db5-be649d4b01a0.PNG)

- `1.7.5+`: Log is not extracted from the `event` key -- Splunk thinks the `event` key and top-level Splunk metadata keys are all part of the log; Splunk metadata is not set to the values we specified in the Splunk metadata keys. This is what we would expect to see if `splunk_send_raw` was set to `off`, even though in this case it is still set to `on`.
![bad](https://user-images.githubusercontent.com/6486632/123712138-bbc94080-d83f-11eb-8ab3-f64622ed488d.PNG)

**Your Environment**
* Fluent Bit Container Version: `1.7.5-debug`
* Configuration: (See above).
* Filters and plugins: Splunk output plugin

**Additional context**

- If we want to dynamically specify Splunk index, source, sourcetype, etc. for each log using the 'raw data' approach as recommended in Fluent Bit docs [here](https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/splunk#data-format), our config only works for older versions of Fluent Bit (< `1.7.5`) -- as soon as we upgrade to `1.7.5+`, it breaks.
- See [here](https://github.com/fluent/fluent-bit/issues/3699#issuecomment-870786283) for the breaking commit.
- See [here](https://github.com/fluent/fluent-bit/issues/3699#issuecomment-885963110) for what I believe to be the cause of the issue, as well as some suggested solutions.

**Comment by ariksidney** [comment]
I just hit the exact same issue as you. Thanks for your detailed report, I haven't been able to figure out that the `splunk_send_raw` option is the problem. I just saw `[upstream] connection #49 failed to <host>:<port>` in the fluentbit log.

**Comment by agup006** [comment]
@pranavmarla what version of Splunk are you using? I believe we had to adjust the endpoint for send raw as it was technically not going to the right endpoint

**Comment by pranavmarla** [comment]
@agup006 I believe it's the latest version, but I'd have to look that up. However, does it really matter here? If the issue was on the Splunk side (with the Splunk endpoint), I assume it would be broken for all versions of Fluent Bit -- instead, it is only broken for v1.7.5+ of Fluent Bit, which makes me think that the bug is on the Fluent Bit side (and was introduced in v1.7.5).

**Comment by pranavmarla** [comment]
@agup006 Not sure if this is what you were referring to but, looking at the [changelog](https://fluentbit.io/announcements/v1.7.5/) for Fluent Bit v1.7.5, I see that it mentions this:
> Splunk (Output): New event_key option and fixes for raw mode
Looks like [this](https://github.com/fluent/fluent-bit/commit/aeb18f77b3eb83ca9d2ec6511f6fe7c275fe79a3#diff-318200a778f9d91353eb03e3aefe07dc83c8a58ede34ebe58e39718af3de5aa3) is the commit containing those changes.

**So, either this commit containing "fixes for raw mode" ironically broke it, or there is some [undocumented](https://docs.fluentbit.io/manual/pipeline/outputs/splunk) config change that we need to make in Fluent Bit to get the new fixed raw mode to work as expected.**

@edsiper: It looks like you're listed as the author of that commit -- would you be able to shed any light on this?

**Comment by edsiper** [comment]
@pranavmarla there are a couple of fixes and enhancements upcoming for v1.8 on Splunk connector, release date is July 5th.

**Comment by pranavmarla** [comment]
Thanks @edsiper -- so, does that mean this issue will go away (without any config changes on our end) when that version comes out?

**Comment by edsiper** [comment]
I am not aware of your production setup details so I cannot confirm issues will go away. I recommend you to build an image from GIT master and give it a try

**Comment by pranavmarla** [comment]
Thanks @edsiper, let me clarify: I'm asking if this raw mode issue is a known bug that was introduced in v1.7.5, that you're saying will be fixed in v1.8. 
Or, if you don't believe a bug was introduced in v1.7.5, is there some change that we need to make to our Splunk plugin config to get it working with v1.7.5+?

If it helps, here is our current Splunk output plugin config in Fluent Bit -- @agup006 mentioned an endpoiint change; could you please let us know if you see anything below that needs to be changed to work with Fluent Bit v1.7.5+? This config works fine for older versions of Fluent Bit, prior to 1.7.5:

```
[OUTPUT]
    name            splunk
    match           *
    host            http-inputs-....com
    port            443
    tls             on
    tls.verify      on
    splunk_token    ...
    splunk_send_raw on
```

**Comment by edsiper** [comment]
@pranavmarla yeah, there is a URI endpoint change in v1.8 plus other new options for metadata set. 

I encourage you to build an image from v1.8 (git master), that might clarify all doubts (my apologies but we are pretty busy preparing the next big release).

**Comment by pranavmarla** [comment]
Sure, thank you @edsiper , appreciate you taking the time to comment!

**Comment by Niksko** [comment]
Our splunk config is identical to @pranavmarla, except we also have `Retry_Limit False`. We're also observing this issue, and using the latest master build doesn't fix things.

**Comment by pranavmarla** [comment]
@Niksko Great catch!! I'm not a C++ expert either but, given that your interpretation of that code matches the behaviour we're seeing (Fluent Bit always thinks raw mode is disabled), I'm fairly certain you've identified the bug. That line [remains unchanged](https://github.com/fluent/fluent-bit/blob/master/plugins/out_splunk/splunk.c#L475) in the latest, master branch, which would also explain why you saw no improvement from building the master branch.

Of course, the best way to confirm would be to change that line of code, generate a new custom build of Fluent Bit, and see if raw mode now works properly.

**Comment by Niksko** [comment]
@pranavmarla I had a go at modifying that line on master, didn't help. I tried adding `Event_Key $event` to my config, but that didn't help either.

Can we get some clarification here? Is `Event_Key` a mandatory field, and how is it meant to be used to emulate the previous behaviour of raw mode?

**Comment by pranavmarla** [comment]
@Niksko Ah, that's unfortunate; really seemed promising.

Regarding `event_key`, as far as I'm aware, it has nothing to do with whether or not raw mode is enabled. It is a new, optional feature, similar to the other new, optional features added [here](https://github.com/fluent/fluent-bit/commit/aaecf64b3a3bc8afc726716d05820c164100dca7#diff-318200a778f9d91353eb03e3aefe07dc83c8a58ede34ebe58e39718af3de5aa3).

**Comment by Niksko** [comment]
Looking at the source again, unless I'm mistaken, prior to 1.7.5, all events were sent to the `/services/collector/event` endpoint, with the difference between raw and non-raw events being how they were packed. Now, raw events go to `/services/collector/raw`. On paper this seems like it should work, based on reading the Splunk API docs. However it also worked previously, so there's clearly some information that's missing here.

**Comment by matthewjstanford** [comment]
The only way to customize Splunk metadata [is to set the `fields` key](https://docs.splunk.com/Documentation/Splunk/8.1.1/Data/IFXandHEC#Add_a_fields_property_at_the_top_JSON_level) and then send it to Splunk using `splunk_send_raw`. However, the [`fields` key is not honored on the `/services/collector/raw` endpoint](https://docs.splunk.com/Documentation/Splunk/8.2.1/Data/FormateventsforHTTPEventCollector#Event_metadata). 

> The fields key isn't applicable to raw data. This key specifies a JSON object that contains explicit custom fields to be defined at index time. Requests containing the "fields" property must be sent to the /collector/event endpoint, or else they aren't indexed.

It would be desirable to make the endpoint configurable, instead of simply relying on `splunk_send_raw`.

[from splunk.c:](https://github.com/fluent/fluent-bit/blob/1.8/plugins/out_splunk/splunk.c#L474-L480)
```
    if (ctx->splunk_send_raw) {
        endpoint = FLB_SPLUNK_DEFAULT_URI_RAW;
    }
    else {
        endpoint = FLB_SPLUNK_DEFAULT_URI_EVENT;
    }
```

As it stands there is no way to set custom metadata because this requires `splunk_send_raw` to be enabled, but then at the same time `splunk_send_raw` forwards the events to an endpoint that doesn't honor custom metadata.

**Comment by Niksko** [comment]
@matthewjstanford this makes sense, and explains why this used to work, even though the plugin used to send data to the `/collector/event` endpoint.

It seems like perhaps the issue has been fixed in 1.8? @edsiper can you confirm? I see lots of new options to configure different splunk metadata fields. I'll report back if I have time to play around.

**Comment by pranavmarla** [comment]
> The only way to customize Splunk metadata is to set the fields key ... the /services/collector/raw endpoint doesn't honor custom metadata.

Hmm, I think there's some confusion here because of my use of the phrase 'custom Splunk metadata' in my original post (which I've since edited for clarity) -- the `fields` key is only required for "explicit custom fields" (i.e. fields that you make up -- eg. `my-custom-key: my-custom-value`). 
To be clear, it has nothing to do with specifying/customizing the pre-existing, 'reserved' Splunk metadata fields like `index`, `source`, etc., which is what this ticket is concerned with. So, it is absolutely possible to specify Splunk metadata when sending the log as a raw event (i.e. to the raw endpoint).
For example, check out Splunk's list of event metadata [here](https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Event_metadata) -- as you can see, `index`, `source`, etc. do not depend on `fields`.

I also personally confirmed (via `curl`) that you can specify Splunk metadata when sending data to the raw endpoint. In fact, in the process of confirming this, I believe I may have stumbled across the reason this functionality is now broken in v`1.7.5+` of Fluent Bit -- see my post below for details.

> It seems like perhaps the issue has been fixed in 1.8?

I just tested the latest version of Fluent Bit (v`1.8.2`) and can confirm that this functionality is still broken -- i.e. specifying Splunk metadata in the top level of the record in 'raw mode', using the config listed in my original post, still does not work.
The good news though is that the new features introduced in v`1.8+` offer a viable alternative -- see my post below for details.

**Comment by pranavmarla** [comment]
# Contents

* [Problem](#problem)
* [Solution](#solution)
* [Alternative (Better?) Solution](#alternative-better-solution)
* [Best solution](#best-solution)

# Problem

To recap, prior to v`1.7.5`, Fluent Bit allowed you to enable 'raw mode' and specify Splunk metadata (eg. `index`, `source`) in the record sent to Splunk. For v`1.7.5+`, that functionality no longer works (Splunk no longer recognizes the Splunk metadata -- it thinks it's just part of the log). The easiest way to explain what Fluent Bit was doing earlier, and why it no longer works now, is via the equivalent `curl` commands:

1. What Fluent Bit was doing prior to v`1.7.5`:
```
# Correct way to specify Splunk metadata for EVENT data
curl \
    -k https://http-inputs-....com/services/collector/event \
    -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
    -d '{"index":"my-index", "source":"my-source", "event":"My log"}'
```
i.e. As Niksko pointed out [above](https://github.com/fluent/fluent-bit/issues/3699#issuecomment-873544305), even though we ostensibly enabled raw mode by setting `splunk_send_raw` to `on`, internally Fluent Bit was sending the record to the **event** endpoint. 
This worked anyway because the Splunk metadata was also specified the way it's meant to be for **event** data, so the event endpoint was able to correctly process the record -- i.e. it understood that the actual log was confined to the `event` key and correctly interpreted the `index` and `source` keys as Splunk metadata.

2. What Fluent Bit is doing now, for v`1.7.5+`:
```
# WRONG way to specify Splunk metadata for raw data!
curl \
    -k https://http-inputs-....com/services/collector/raw \
    -H "X-Splunk-Request-Channel: ${RANDOM_GUID}" \
    -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
    -d '{"index":"my-index", "source":"my-source", "event":"My log"}'
```
I accidentally did this myself and immediately noticed that the resulting log looked identical to what Fluent Bit v`1.7.5+` produces. Thus, after skimming Fluent Bit source code, I believe this is essentially what it is doing internally:
The fix that was [introduced](https://github.com/fluent/fluent-bit/issues/3699#issuecomment-870786283) in v`1.7.5` was to ensure that, when raw mode is enabled (`splunk_send_raw` set to `on`), the record is sent to the actual raw endpoint. Unfortunately, as you can see, **this is only a partial fix** because the Splunk metadata is still specified the same way -- i.e. the way it's meant to be specified for **event** data!
Thus, this does not work because the raw endpoint is not able to correctly process the record -- i.e it thinks the entire record (not just the `event` key) is the actual log, and does not interpret the `index` and `source` keys as Splunk metadata.

# Solution

What Fluent Bit SHOULD have been doing, for v`1.7.5+`:
```
# Correct way to specify Splunk metadata for raw data
curl \
    -k "https://http-inputs-....com/services/collector/raw?index=my-index&source=my-source" \
    -H "X-Splunk-Request-Channel: ${RANDOM_GUID}" \
    -H "Authorization: Splunk ${SPLUNK_HEC_TOKEN}" \
    -d 'My log'
```
As you can see, we are now sending the record to the raw endpoint AND we are specifying the Splunk metadata the way it's [meant](https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTinput#services.2Fcollector.2Fraw) to be specified for raw data -- i.e. as query string parameters in the raw endpoint URL. Also, there is no longer a JSON wrapper around the actual log -- it is sent 'raw'.
If implemented in Fluent Bit, this would work as now the raw endpoint would be capable of correctly processing the record -- i.e. it would correctly interpret the entire record (in this case, `My log`) as the actual log, and it would interpret the query string parameters as Splunk metadata.

# Alternative (Better?) Solution

Part of the confusion, at least for me, was that Fluent Bit's [documentation](https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/splunk#data-format) for the Splunk plugin wrongly conflates 'specifying Splunk metadata' with 'sending logs as raw data':
> If you would like to customize any of the Splunk event metadata, such as the host or target index, you can set Splunk_Send_Raw On in the plugin configuration, and add the metadata as keys/values in the record.

For people who are not that familiar with Splunk (like myself), you might assume that this is a restriction on the Splunk side -- i.e. even if you are not using Fluent Bit, if you want to specify Splunk metadata, Splunk requires you to send the log as raw data. However, if you actually read Splunk's documentation ([link1](https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Event_metadata), [link2](https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTinput#services.2Fcollector.2Fraw)), you'll see that this is not true -- as my `curl` examples above show, you can specify Splunk metadata when sending logs as raw data AND when sending logs as (JSON) event data.
The restriction was on the Fluent Bit side, not the Splunk side.

So, when I realized that the first (raw) approach was broken in v`1.7.5+`, I immediately assumed I had no other option to specify Splunk metadata. And, prior to v`1.8.0`, that was true because of Fluent Bit's restriction. In v`1.8.0` though, several new parameters for the Splunk plugin were [introduced](https://github.com/fluent/fluent-bit/commit/aaecf64b3a3bc8afc726716d05820c164100dca7#diff-f77c91b8bd465e1a6b1fb6490a6630bd9941e87fb42a365bff78dee52617aa6c), such as `event_index` and `event_source` -- although it wasn't clear to me at the time, these new parameters give us an alternative (event) approach, which does NOT require us to enable raw mode (and, thus, bypasses this bug).

i.e.
**Approach 1 (raw mode): (Currently broken!)**
```
[INPUT]
  ...

# Nest the entire log that exists at this point under the 'event' key
[FILTER]
  name                nest
  match               *
  operation           nest
  wildcard            *
  nest_under          event

# Add Splunk metadata to the top level of the record
[FILTER]
  name                modify
  match               *
  add                 index my-index
  add                 source my-source

[OUTPUT]
  name                splunk
  match               *
  host                http-inputs-....com
  port                443
  tls                 on
  tls.verify          on
  splunk_token        ...
  # Enable raw mode
  splunk_send_raw     on
```

**is EQUIVALENT to**

**Approach 2 (event mode)**
```
[INPUT]
  ...

# Do not need to manually nest the log under the 'event' key

# Do not need to manually inject the Splunk metadata into the top level of the record

[OUTPUT]
  name                splunk
  match               *
  host                http-inputs-....com
  port                443
  tls                 on
  tls.verify          on
  splunk_token        ...
  # DISABLE raw mode
  splunk_send_raw     off
  # Use new params
  event_index         my-index
  event_source        my-source
```

Thus, this 'event' approach provides a viable alternative to the currently broken 'raw' approach -- in fact, given that, when Fluent Bit sends a log to Splunk, it always sends it in a well-formatted JSON wrapper, it seems more logical (and I believe results in faster processing on the Splunk side) if we send it to the (JSON) event endpoint rather than the raw endpoint.

# Best solution

As matthewjstanford pointed out though, this new 'event' approach does have one downside, which is that we lose the flexibility that we had when setting the Splunk metadata values:
In the original 'raw' approach, we had to manually inject the Splunk metadata values into the record, which meant that we had full control over what Splunk metadata values ultimately got populated -- in this new 'event' approach however, we are limited to whatever the new `event_...` parameters happen to support.

Eg. There are two new parameters to help us specify sourcetype:
- `event_sourcetype`: Only accepts a hardcoded string value
- `event_sourcetype_key`: Accepts a log key (via record accessor syntax) -- if that key is present in the log, its corresponding value takes precedence over `event_sourcetype`.

Thus, using the 'event' approach, you can configure Fluent Bit to do the following:
1. Look for sourcetype in an optional log key
2. If that optional log key is not present, fall back to a hardcoded default value.

What you CANNOT do with the 'event' approach though is configure Fluent Bit to do the following:
1. Look for sourcetype in an optional log key
2. If that optional log key is not present, fall back to a different, *mandatory* log key.

In the 'raw' approach though, we could have implemented this functionality via a Lua filter.

**Thus, the ideal solution would be a mix of both approaches: The ability to send the log to the event endpoint, and the ability to fully control what Splunk metadata values get injected into the record -- i.e. what we originally had prior to v`1.7.5`, even if we didn't know it at the time.**

**Comment by pranavmarla** [comment]
@edsiper @pwhelan
I believe I have identified the cause of the bug as well as some potential solutions (see my post above for details) -- please let me know if my hypothesis makes sense and, if it does, if one of these solutions can be implemented in a future release of Fluent Bit.

**Comment by Niksko** [comment]
@pranavmarla thank you for your detailed assessment. I agree with your conclusion: there are some workarounds that were released in 1.8, but it would still be desirable to have the ability to just send the log to the event endpoint.

It would be great to have some consistency in how the raw event parameters work. At the moment we have:

* some fields like `event_source` and `event_sourcetype` which specify a value directly
* fields like `event_host` which specify a key whose value is used as the event value. It feels like this should be `event_host_key`.
* `event_sourcetype_key` which specifies the key whose value is used
* `event_field` which can be set multiple times, but something like `event_field_key` is actually what we'd want, because we already have a `field` key that has all of the data we want to send in it.

**Comment by pranavmarla** [comment]
Thanks @Niksko ! 

Regarding the `event_...` parameters, I agree completely -- it would definitely be simpler to use if the names (and descriptions) were standardized.
Quick clarification: I believe all the `event_...` parameters only apply when you're sending the log as (JSON) event data, not as raw data.

**Comment by agup006** [comment]
Thanks for the write up @pranavmarla , we need more time to review this

**Comment by brian-maloney** [comment]
I just ran into this today, trying to convert from using a splunk universal forwarder to forward logs from systemd journald to splunk to using fluentbit for the same purpose.  My intention is to lift all of the journald fields except for MESSAGE into the event fields and rename MESSAGE to event, therefore I definitely still need the ability to pass a JSON message "crafted" using filters to the event endpoint.  So this is just a +1 to @pranavmarla's "best" solution.

**Comment by brian-maloney** [comment]
Just an additional followup for folks struggling with this.  I have my Splunk HEC behind a traefik proxy, which returns 404 if all HEC instances are down, which in turn causes Fluent Bit to drop messages (since this is a deviation of the return code behavior from the HEC itself, where a 4XX is an unrecoverable error).  I decided to try using the Fluent Bit HTTP output instead of Splunk (using the same event crafting filters I was using with Splunk Raw) and that works fine for me, even with recent versions of Fluent Bit.  Here's my output config if anyone's interested:

```
[OUTPUT]
    name          http
    log_level     warning
    match         *
    tls           on
    host          <HOST>
    port          443
    uri           /services/collector/event
    header        Authorization Splunk <TOKEN>
    format        json_stream
    json_date_key time
    retry_limit   false
```

**Comment by agup006** [comment]
Thanks for the update @brian-maloney , I appreciate everyones input in this and if folks are interested perhaps we could setup some time to quickly run through options and move forward with a decision. @pranavmarla @Niksko 

One option I feel makes more sense after seeing @brian-maloney using HTTP output plugin makes me feel we should route users who want to use Splunk_Send_Raw to use the HTTP output plugins with guidance on endpoint URI's such as `/raw` or /event`. The only difference I am seeing between the plugin vs. HTTP output plugin setup for a user is the URI / Header, and Format fields being required.

**Comment by rumstead** [comment]
So there is a supported workaround here? Do I actually need to use an HTTP output over Splunk?

**Comment by pranavmarla** [comment]
> So there is a supported workaround here? Do I actually need to use an HTTP output over Splunk?

Yes, as @brian-maloney and @agup006 pointed out, at this point the easiest option is to go with the HTTP output plugin -- it doesn't come with convenient, Splunk-specific features out of the box but it does give you the most control and flexibility in terms of how the payload is structured.
