### ISSUE TITLE
tail plugin should just skip long lines rather than full file

### ISSUE THREAD

**Issue by rksatyam** [fluent/fluent-bit#370]
A long line bigger than Buffer_Max_Size is causing the full file to skipped. This is really bad and kills us. The log line could be skipped but not the complete file.

**Comment by edsiper** [comment]
Enhancement request: add option to let tail find a breakline and skip that content

**Comment by edsiper** [comment]
I've pushed the changes for a new option called _skip_long_lines_:

```
By default when there is no more room in the internal buffer to read a
complete line, the file is not longer monitored. There are situations
where users wants to just skip long lines and keep processing other
lines.

This patch introduce a new option to in_tail called 'skip_long_lines',
when the buffer is full and a line has not been processed due to a
missing \n, this option makes to discard that current line content
and process other new lines that fits into the buffer size.
```

This will be part of 0.12.3 release.

**Comment by edsiper** [comment]
0.12.3 has been released:

- http://fluentbit.io/announcements/v0.12.3/
- http://fluentbit.io/documentation/0.12/input/tail.html
