### ISSUE TITLE
Fluent-bit mapping error when forwarding to AWS ElasticSearch

### ISSUE THREAD

**Issue by hieu29791** [fluent/fluent-bit#3713]
**Describe the bug**
Fluent-bit work normally as expected. But when I upgraded K8s node group, new nodes is born to replace old nodes. Then fluent-bit can't forward log to ES anymore.  

**To Reproduce**
- Steps to reproduce the problem:
+ Fluent-bit deployed inside EKS cluster, forward log to AWS ElasticSearch, working as expected. I can view log on Kibana.
+ Upgraded EKS node group, new nodes is born to replace old nodes (rolling update), fluent-bit starting have error log message, related to mapping issue.
+ Error: 
![image](https://user-images.githubusercontent.com/10827875/124107386-608d8d00-da8f-11eb-9d2b-47f06ae8381d.png)

**Expected behavior**
- Fluent-bit work normally when add/update/delete node group.

**Your Environment**
- AWS EKS version 1.19
- AWS ElasticSearch version 7.10

**Comment by hoangphan1509** [comment]
I think it's a problem with your ES  mapping. Check this issue: https://github.com/fluent/fluent-bit/issues/3052
