### ISSUE TITLE
Co-routine stack size check is failure prone

### ISSUE THREAD

**Issue by ericonr** [fluent/fluent-bit#3716]
## Bug Report

**Describe the bug**

As seen in #2464, launching fluent-bit makes it spit out this error message:

> Error: Invalid coroutine stack size. Aborting

This happens due to https://github.com/fluent/fluent-bit/blob/5ffc991b71cd06cfa2f2f7a764e634af053776bd/src/fluent-bit.c#L1111 and https://github.com/fluent/fluent-bit/blob/5ffc991b71cd06cfa2f2f7a764e634af053776bd/include/fluent-bit/flb_coro.h#L68

musl defines `PTHREAD_STACK_MIN` to 2048, which means that the result of `PTHREAD_STACK_MIN * 3 / 2` is 3072, which is definitely smaller than what `getpagesize()` returns (4096 on most platforms). I'm not sure what the best solution here is, either don't use `getpagesize` as the basis for the check, or use the maximum between `getpagesize` and `PTHREAD_STACK_MIN * 3 / 2`.

This also fails on platforms that support 64k pages (aarch64 and ppc64), even when using glibc. Most aarch64 machines won't be configured that way, but to my knowledge all ppc64 distros besides Void Linux use 64k pages.

**To Reproduce**

Simply try to launch fluent-bit when built against musl libc.

**Expected behavior**

It will at least launch.

**Your Environment**

* Version used: built from master (305590f8d4e1b6125ff1047bf3344e089fddeca9)
* Operating System and version: any musl based distro

**Comment by bgdnlp** [comment]
The same thing happens on FreeBSD. Running just `fluent-bit` immediately complains that
```
Fluent Bit v1.7.9
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Error: Invalid coroutine stack size. Aborting
```

 `fluent-bit --help` says:
```
  -s, --coro_stack_size   set coroutines stack size in bytes (default: 3072)
```

Would it be acceptable to simply set coro_stack_size to getpagesize() if the default is smaller and it isn't otherwise configured?

**Comment by ericonr** [comment]
I would ask of the repo maintainers to remove the auto stale bot. I have nothing to do with upstream not answering this issue yet. If the bot pings the issue again I will just close it and give up on the bug report.

**Comment by girgen** [comment]
It seems stupid that the binary just fails to run unless you set the coro_stack_size?

I maintain the FreeBSD port, and I'm patching the source to double the stack size, in wait for a better fix.

**Comment by bgdnlp** [comment]
Could someone please have a look at this issue, maybe it's not controversial and can be fixed easily?

**Comment by bgdnlp** [comment]
Aaaand, bump

**Comment by krystiannowak** [comment]
another bump

**Comment by edsiper** [comment]
note: we are adjusting the auto-stale bot, quite noisy. 

assigning @nokute78 to review this.

**Comment by nokute78** [comment]
> Would it be acceptable to simply set coro_stack_size to getpagesize() if the default is smaller and it isn't otherwise configured?

I agree.

I sent a patch #4434 to change the default size if it is smaller than page size.
User can overwrite via config/option.
