### ISSUE TITLE
rewrite_tag with filesystem storage takes huge amount of space on disk, causing disk pressure and eviction

### ISSUE THREAD

**Issue by tpetrov-lp** [fluent/fluent-bit#3718]
## Bug Report

**Describe the bug**
I have fluent-bit configured like this:

```
    [SERVICE]
        Flush                     5
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 2020
        coro_stack_size           245760
        storage.path              /flb-logs/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 50M
```
+ rewrite_tag filter

```
    [FILTER]
        Name                  rewrite_tag
        Match                 stackdriver.tcp.all.*
        Emitter_Storage.type  filesystem
        Rule                  $app ^(.*)$  stackdriver.tcp.$app.$version.$podName false
        Emitter_Name          app-version-pod-emitted
```

After a few days (2-3) with log-ingestion rate of 100MB/sec. I can see that the storage occupied on disk from the emitter is huge: **30-50GB**.

```
/ # du -h /flb-logs
55.7G	/flb-logs/flb-storage/emitter.13
55.7G	/flb-logs/flb-storage
55.7G	/flb-logs
```

I also checked one 26h pod and the size used there was quite smaller.

```
/ # du -h /flb-logs
293.0M	/flb-logs/flb-storage/emitter.13
293.0M	/flb-logs/flb-storage
293.0M	/flb-logs
```

At some point, pods on k8s are evicted because of Disk pressure, which is causing logs loss.

It seems like in some scenarios emitter storage is not cleaned up. Even if output cannot process records for some time, 55GB @ 100MBs rate is ~10min.

**To Reproduce**
I don't have steps to reproduce just yet, because it's observed on the prod environment under high load.

**Expected behavior**
My expectation is that the storage used by the emitter will be a reasonably small (not more than a few GBs) and if there is any problem being cleaned up, some logs should indicate what problem is causing it.
Disk pressure, causes immediate pod eviction on k8s and logs are lost. This is not acceptable for a prod environment, please advise if this is a configuration issue.

**Your Environment**

* Fluent-bit version used: 1.7.7
* K8s version: 1.17.17 on GKE
* Configuration: fluent-bit pods requesting 0.4 cpu and 200Mi RAM
* Filters and plugins: tcp and forward inputs + lua and rewrite_tag filters + stackdriver output. 

**Additional context**
We've been with a very old customised version (1.0.1) for 2 years and now we changed to 1.7.7 and added the the tag rewriting. The environment is not very stable. Pods are being evicted, we experience some log drops + stackdriver output plugin loses connection much more frequently. This is too risky for the production environment.

**Comment by edsiper** [comment]
@tpetrov-lp 

thanks for opening this ticket.

I am not sure of the whole variables in your environment, but with Google team and Stackdriver we have a pretty close work relationship, in the tests they are currently handling around 200k messages per second without any issue: all of this in production.

what would be relevant to troubleshoot this issue is:

- minimal reproducible test case
- I see you have "emitter.13", meaning that you have multiple rewrite tag filters in place
- full configuration

**Comment by tpetrov-lp** [comment]
@edsiper 

I don't actually have multiple rewrite tag filters, but I have multiple TCP inputs (11) + one forward input i.e. a total of 12 and the rewrite tag is immediately after that. That's why I guess it's 13.

Please take a look at 
[emitter_storage_0655.txt](https://github.com/fluent/fluent-bit/files/6769590/emitter_storage_0655.txt)
[emitter_storage_0702.txt](https://github.com/fluent/fluent-bit/files/6769591/emitter_storage_0702.txt)

This is the content of the emitter storage at 6:55 and 7:02. You can see that some old files from previous day or several hours earlier are hanging around and are never cleaned up.

I can send you the full configuration for running it on k8s and a java app writing to the TCP inputs. I am not sure I will be able to reproduce it with this single log source (will leave it running overnight). The errors are from the prod system where we have multiple apps running and writing to the TCP inputs + a lot of apps writing to stdout with a fluentbit as a DS forwarding to this failing fluent-bit deployment. The failing fluent-bit deployment is ~200 pods.

You can see the prod setup on the following diagram.

![FluentBitSetupDiagram](https://user-images.githubusercontent.com/71340394/124596317-ce103380-de6a-11eb-8c8e-a34c39cb1f43.png)

So, please give me an email or anything else which works for sending the configuration and the app privately and I'll do.

**Comment by tpetrov-lp** [comment]
In the meantime (while investigating), I will put a liveness check if the storage stays above some threshold (like 1GB) for let's say 15 mins and if that happens, k8s will restart the pod. Would this cause any problems?

**Comment by tpetrov-lp** [comment]
@edsiper A few more details:

1. I ran a test using a single pod and a single source of logs flushing with 5K msg/sec, using the same configuration as we use in prod but the issue did not happen this way. So I suspect something related to (a) k8s auto-scaling (b) multiple apps sending logs using forward or tcp (c) an error while flushing the output (d) even higher load.
2. Killing the fluent-bit container seems to catch-up with the accumulated tasks in emitter.13 after the pod is restarted. In a few mins, even a few GBs of data is processed.

I am attaching the state of the files for another corrupted pod before restarting within a 4 min difference:
[emitter_storage_1.7g_0543.txt](https://github.com/fluent/fluent-bit/files/6776979/emitter_storage_1.7g_0543.txt)
[emitter_storage_1.7g_0547.txt](https://github.com/fluent/fluent-bit/files/6776980/emitter_storage_1.7g_0547.txt)

I am also attaching two files representing the age of the pods on the system (100+ pods) and the size of the emitter folder respectively.
[fluentbit_pods_storage_size.txt](https://github.com/fluent/fluent-bit/files/6777001/fluentbit_pods_storage_size.txt)
[pods_status_202107070546.txt](https://github.com/fluent/fluent-bit/files/6777002/pods_status_202107070546.txt)

And finally, two logs representing the errors/warnings for two pods for the last few hours.

[fluentbit-upload-1.7.7-debug-5f6cd7fbbf-6fx5c.log](https://github.com/fluent/fluent-bit/files/6777007/fluentbit-upload-1.7.7-debug-5f6cd7fbbf-6fx5c.log)
[fluentbit-upload-1.7.7-debug-5f6cd7fbbf-k8r2b.log](https://github.com/fluent/fluent-bit/files/6777008/fluentbit-upload-1.7.7-debug-5f6cd7fbbf-k8r2b.log)

Stackdriver output is failing periodically for some reason. Not sure if this can be related or not.

Other errors, I have seen in the other logs are:

- timed out after 10 seconds
- Resource temporarily unavailable
- TCP connection failed
- error sending data to
- could not connect to
- could not write forward entries
- could not write forward header
- connect event handler error
- Connection reset by peer
- no upstream connections available
- error registering chunk with tag
- Broken pipe

Something is causing fluent-bit to stop processing  data until restarted at some time. It can be related to other issues reporting freezes under high load.

**Comment by tpetrov-lp** [comment]
I checked our staging environment and there is no problem there. It's running for 23 days without issues. The load there is minimal. That's likely related.

**Comment by tpetrov-lp** [comment]
@edsiper Hey, Eduardo, I see the issues flagged as "waiting for user". Please let me know what else do you need as info.

**Comment by todor** [comment]
@edsiper This is a serious issue, please mark it somehow to not become stale every 30 days.

**Comment by todor** [comment]
Still valid.

**Comment by tpetrov-lp** [comment]
Still valid. @edsiper is there any progress on this?

**Comment by tpetrov-lp** [comment]
Keep open.

**Comment by tpetrov-lp** [comment]
It was better with 1.8.12, but I cannot confirm yet if problem is solved. Once I have time to update all production clusters to latest fluentbit and checks its stability, I'll update the thread.

**Comment by davpate** [comment]
This GitHub Actions bot really doesn't help with closing these issues that are still valid and actively occurring...

**Comment by leonardo-albertovich** [comment]
Hi @davpate, are you able to reproduce this with fluent-bit 2.0?

**Comment by cdancy** [comment]
@edsiper @davpate @tpetrov-lp can we re-open this issue? This is still happening even on fluentbit 4.x.
