### ISSUE TITLE
extend windows builds support

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#3720]
#### Improve windows CI/build.

1. Build docker windows images for windows-2019/windows-latest.

- [x] Master images
- [ ] Release (tags) images

2. Demote appveyor in favor of github actions: we can keep both co-existing (as a reference: cmetrics)
but ideally the same workflows (unit test / functional ) should apply for windows.

3. Add fluent-bit-ci support for integration tests using the docker images / k8s.

**Comment by patrick-stephens** [comment]
- [ ] Add smoke testing similar to Linux.

**Comment by patrick-stephens** [comment]
Roll up into #5196
