### ISSUE TITLE
winlog returning 0xc0000005/3221225477 (Access Violation) when reading the Application channel

### ISSUE THREAD

**Issue by jsubirat** [fluent/fluent-bit#3736]
## Bug Report

**Describe the bug**
Fluent Bit is not able to start when reading the Application channel in some Windows machines. It exits unexpectedly and it returns the 0xc0000005/3221225477 (Access Violation) error code. We have observed this on a Windows 2012 R2 Standard running on a physical host. Nevertheless, I couldn't reproduce it on a Windows 2012 running on AWS or GCP.

**To Reproduce**
- Start Fluent Bit with: `.\fluent-bit.exe -i winlog -p 'channels=Application' -o stdout -vv`
- Under certain Windows environments, this causes Fluent Bit to crash and return the exit code 0xc0000005/3221225477. Attaching screenshot.

**Expected behavior**
- `winlog` should be able to read the `Application` channel without any problem.

**Screenshots**
Execution causing the crash. Note how the -1073741819 status code is actually 0xc0000005 but with extra bits in the 64-32 range (I believe these can be safely ignored):
<img width="1182" alt="Screen Shot 2021-07-07 at 8 35 19 PM" src="https://user-images.githubusercontent.com/6243832/124811532-dba8e480-df62-11eb-8d18-172ecfc0e3b5.png">

**Your Environment**
* Version used: 1.7.3
* Configuration: `-i winlog -p 'channels=Application' -o stdout`
* Environment name and version (e.g. Kubernetes? What version?): Windows 2012 R2
* Server type and version: HP ProLiant BL460c Gen9
* Operating System and version:  Microsoft Windows Server 2012 R2 Standard | 6.3.9600 Build 9600
* Filters and plugins: None.

**Additional context**
We have observed this in two customer servers running Microsoft Windows Server 2012 R2 Standard | 6.3.9600 Build 9600

**Comment by leonardo-albertovich** [comment]
@jsubirat I have a few questions about this issue : 

1 - would you be able to help me figure it out testing a few special builds with additional debug output? 
2 - would you be able to tell me what the system name is (particularly, if it contains unicode characters).
3 - would you be able to test the latest build (just in case)

Thanks for your cooperation!
