### ISSUE TITLE
rpm's lack service enable

### ISSUE THREAD

**Issue by ruilapa** [fluent/fluent-bit#3747]
## Bug Report

**Describe the bug**
service td-agent-bit does not get enabled on RH based OS.

**To Reproduce**
Follow steps described in:
- https://docs.fluentbit.io/manual/installation/linux/redhat-centos
OR
- https://docs.fluentbit.io/manual/installation/linux/amazon-linux

This can be confirmed by:
1. checking systemctl status
```
$ systemctl status td-agent-bit
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```

2. checking rpm scripts
```
$ rpm -q --scripts td-agent-bit
preinstall program: /bin/sh
postinstall program: /bin/sh
preuninstall program: /bin/sh
postuninstall program: /bin/sh
```

**Expected behavior**
rpm postinstall should
`systemctl enable td-agent-bit`

**Comment by edsiper** [comment]
we faced some issues with the packaging rules, please refresh your repo and install the latest td-agent-bit (1.8.1), it should be ok

**Comment by edsiper** [comment]
dup of #3742

**Comment by ruilapa** [comment]
Unfortunately, service is still not enabled on:
- amzn2 arm64
- amzn2 amd64
- rhel7 amd64
- debian9 amd64
- debian10 amd64
- ubuntu18 amd64
- ubuntu20 amd64
