### ISSUE TITLE
Multi line parser not working in K8s environment ( but works fine in local setup )

### ISSUE THREAD

**Issue by mayuraviraj** [fluent/fluent-bit#3751]
## Bug Report

**Describe the bug**
My target is to push java pods logs to Elasticsearch. The problem is when there is java stack trace those are not put in to elastic search. Only the first line of exception log is put to es. But same parser works fine locally.

**To Reproduce**
User following configurations in k8s setup.

````
[FILTER]
    Name                   kubernetes
    Match                    kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File       /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix   kube.var.log.containers.
    Merge_Log            On
    Merge_Log_Key     log_processed
    K8S-Logging.Parser  Off
    K8S-Logging.Exclude Off
    Buffer_Size         0

[SERVICE]
    Flush         1
    Log_Level     debug
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020
@INCLUDE input-kubernetes.conf
@INCLUDE filter-kubernetes.conf
@INCLUDE output-elasticsearch.conf
@INCLUDE output-s3.conf

[INPUT]
    Name           tail
    Tag               kube.dev.*
    Path              /var/log/containers/*dev*.log
    DB                /var/log/kube_dev.db
    Refresh_Interval  10
    Read_from_head    true        
    Multiline         On
    Parser_Firstline  multiline

[OUTPUT]
    Name            es
    Match           kube.dev.*
    Host            es-host
    Port            443
    TLS             On
    Retry_Limit     6
    Buffer_Size     32KB

[PARSER]
    Name         multiline
    Format       regex
    Regex        /^(?<time>(\d)+(-\d+)+(\S)+\W(\S)+)(?<message>.*)/
    Time_Key     time
    Time_Format  %Y-%m-%d %H:%M:%S.%L
    Time_Keep    On
```


**Expected behavior**
Logs push to elastic search with java stack trace as a single document. But no stack trace appear in es.

**Additional context**
Same parser with same configuration tested locally with locally running ES server. Then stack trace was successfully pushed. Therefore parser is working. Multi-line parser works locally but not in k8s environment. Note : Logs are not in json format.

similar issue : https://groups.google.com/g/fluent-bit/c/XoOibAxGGeI

**Comment by kien-truong** [comment]
Using `Parser_Firstline` doesn't work because K8S modify your log output to add extra information.

You would need to first use a `docker` or `cri-o` parser in the tail input, depending on your K8S installation, to extract the original log lines. Afterward, you can use the newly-added `multiline` parser and filter in version `1.8` to concatenate them.

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing
https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace

**Comment by driftertest** [comment]
I test 1.8.2 this setup (with filter and without) and it does not work:

```
    [SERVICE]
        Flush 5
        Daemon Off
        Log_Level debug
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
    [INPUT]
        Name              tail
        Tag               flink.*
        Path              /var/log/containers/-*.log
        # Parser            cri
        multiline.parser  docker, cri
        DB                /var/log/flb_flink.db
        Skip_Long_Lines    off
        Refresh_Interval   20
        Multiline_Flush    20
        Buffer_Chunk_Size  1G
        Buffer_Max_Size    1G
        Ignore_Older       1D
    [OUTPUT]
        Name es
        Match flink.*
        Host el-0001.***.ru
        Port 9200
        Logstash_Format On
        Logstash_Prefix fluent-flink
        Trace_Error On
        Retry_Limit False
        Buffer_Size False
        Replace_Dots On
    #[FILTER]
    #    name multiline
    #    match flink.*
    #    multiline.key_content log
    #    multiline.parser multiline_flink
    [MULTILINE_PARSER]
        name          multiline_flink
        type          regex
        key_content   log
        flush_timeout 5000
        trace_error on
        #
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules |   state name  | regex pattern                                 | next state
        # ------|---------------|-----------------------------------------------|-----------------
        rule      "start_state"   "/^^([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})(.*)/"               "cont"
        rule      "cont"          "/^(Exception.*|java.*|\\tat.*|\s+.at*|\\u0009at.*)/"       "cont"
```

log form pod:
`2021-07-21 17:55:53,210 INFO  com.nsct.streams.kafka.streams.explode.RecordExplode [] - Cannot parse string: 250-01-33571. Throws an exception:
java.lang.NumberFormatException: For input string: "343434"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_201]
	at java.lang.Integer.parseInt(Integer.java:583) ~[?:1.8.0_201]
	at com.nsct.streams.kafka.streams.explode.RecordExplode.parseLacCell(WebVisitRecordExplode.java:94) ~[orc-writer-0.4.206-all.jar:0.4.206]
	at com.nsct.streams.kafka.streams.explode.RecordExplode.getLacCellId(WebVisitRecordExplode.java:124) ~[orc-writer-0.4.206-all.jar:0.4.206]
	at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:47) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollectWithTimestamp(StreamSourceContexts.java:322) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collectWithTimestamp(StreamSourceContexts.java:426) [flink-dist_2.11-1.12.2.jar:1.12.2]
	at org.apache.flink.streaming.connectors.kafka.internals.AbstractFetcher.emitRecordsWithTimestamps(AbstractFetcher.java:365) [orc-writer-0.4.206-all.jar:0.4.206]
	at org.apache.flink.streaming.connectors.kafka.internals.MyKafkaFetcher.partitionConsumerRecordsHandler(MyKafkaFetcher.java:182) [orc-writer-0.4.206-all.jar:0.4.206]`

and log node created by docker:
`{"log":"2021-07-21 15:21:08,125 INFO  com.nsct.streams.kafka.streams.explode.RecordExplode [] - Cannot parse string: 250-01-33571. Throws an exception:\n","stream":"stdout","time":"2021-07-21T15:21:08.134430745Z"}
{"log":"java.lang.NumberFormatException: For input string: \"3434343\"\n","stream":"stdout","time":"2021-07-21T15:21:08.134432967Z"}
{"log":"\u0009at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_201]\n","stream":"stdout","time":"2021-07-21T15:21:08.134435005Z"}
{"log":"\u0009at java.lang.Integer.parseInt(Integer.java:583) ~[?:1.8.0_201]\n","stream":"stdout","time":"2021-07-21T15:21:08.134437102Z"}
{"log":"\u0009at com.nsct.streams.kafka.streams.explode.RecordExplode.parseLacCell(WebVisitRecordExplode.java:94) ~[orc-writer-0.4.206-all.jar:0.4.206]\n","stream":"stdout","time":"2021-07-21T15:21:08.134439199Z"}
{"log":"\u0009atcom.nsct.streams.kafka.streams.explode.RecordExplodegetLacCellId(WebVisitRecordExplode.java:124) ~[orc-writer-0.4.206-all.jar:0.4.206]\n","stream":"stdout","time":"2021-07-21T15:21:08.134441458Z"}
{"log":"\u0009at com.nsct.streams.kafka.streams.explode.RecordExplode.setLacCell(WebVisitRecordExplode.java:323) ~[orc-writer-0.4.206-all.jar:0.4.206]\n","stream":"stdout","time":"2021-07-21T15:21:08.134444075Z"}
{"log":"\u0009at com.nsct.streams.kafka.streams.explode.RecordExplode.explode(WebVisitRecordExplode.java:387) ~[orc-writer-0.4.206-all.jar:0.4.206]\n","stream":"stdout","time":"2021-07-21T15:21:08.134450019Z"}`

In Elastic i see every record in each string, where i make mistake?

**Comment by mayuraviraj** [comment]
I also tested 1.8.2 release and new multi-line parser not working as expected. This seems to take too much time for such mandatory use case.

**Comment by mayuraviraj** [comment]
@driftertest In your code, you have not used `multiline_flink` parser. It should be used in `multiline.parser  docker, cri` as `multiline.parser  docker, multiline_flink`

**Comment by driftertest** [comment]
@mayuraviraj i tried several configurations like this and no one is worked
1:
```
    [INPUT]
        multiline.parser  docker, multiline_flink
    #[FILTER]
    #    name multiline
    #    match flink.*
    #    multiline.key_content log
    #    multiline.parser multiline_flink
```
2:
```
    [INPUT]
        multiline.parser  docker, cri
    [FILTER]
        name multiline
        match flink.*
        multiline.key_content log
        multiline.parser multiline_flink
```
3:
```
    [INPUT]
        parser docker
    [FILTER]
        name multiline
        match flink.*
        multiline.key_content log
        multiline.parser multiline_flink
```

**Comment by mayuraviraj** [comment]
@driftertest Yes, I also tried with various configurations but no luck. I think its better to move to something like file-beat.

**Comment by alexku7** [comment]
me too :(. something wrong with multi line support
