### ISSUE TITLE
Cross Compilation Error ARM x32

### ISSUE THREAD

**Issue by lucask18** [fluent/fluent-bit#3754]
Hi, I've been trying to cross-compile Fluent Bit to an ARM x32 platform, but I'm getting errors with the onigmo/st.h. It's giving me errors with line 65 (the comparison between SIZEOF_VOIDP and sizeof(st_index_t)).

**Comment by jan-hudec** [comment]
Additional CMake option `-DHOST=arm-v7a-linux-gnueabihf` (or whatever the target triplet is) is required for cross-compiling that does not seem to be documented. Unfortunately CMake does not have standard variable for the host ID in this format.

**Comment by jan-hudec** [comment]
… and `luajit` requires similar additional variable `CROSS_PREFIX` with the compiler prefix (in my case that contains a path).
