### ISSUE TITLE
[CI] missing tar.gz error

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#3756]
## Bug Report

**Describe the bug**

https://github.com/fluent/fluent-bit/runs/3031641835

CI tried  to get missing tar.gz and it failed.
```
curl -L -o "/tmp/fluent-bit.tar.gz" https://github.com/fluent/fluent-bit/archive/v1.9.0.tar.gz     
```

https://github.com/fluent/fluent-bit/archive/v1.9.0.tar.gz   
and redirected URL
https://codeload.github.com/fluent/fluent-bit/tar.gz/v1.9.0 
are 404.

**To Reproduce**
- Rubular link if applicable: None 
- Example log message if applicable: None
- Steps to reproduce the problem: 

**Expected behavior**
No error.

**Screenshots**
None

**Your Environment**

* Version used: master
* Configuration: None
* Environment name and version (e.g. Kubernetes? What version?): CI
* Server type and version: CI
* Operating System and version: Ubuntu 20.04.2
* Filters and plugins: None

**Additional context**
None

**Comment by edsiper** [comment]
1.9.0 has not been released, we just released 1.8

**Comment by edsiper** [comment]
oops

**Comment by nokute78** [comment]
We bump next version after releasing.

However, below Dockerfile links to missing bumped version.

https://github.com/fluent/fluent-bit/blob/99d29a8a7d253e4874468f58ea1ccf33c04361c5/dockerfiles/Dockerfile.x86_64-master_debug#L4-L9

**Comment by edsiper** [comment]
ahh right, tag will never exists. cc: @niedbalski I think this should point to master.zip
