### ISSUE TITLE
Splunk output - raw endpoint behavior

### ISSUE THREAD

**Issue by sbellan** [fluent/fluent-bit#3762]
Fluent Bit Version: 1.8.1

As per the splunk output documentation, you can customize the host, source, sourcetype by adding them as attributes as part of the event. But Splunk does not work well with that. for eg.

```
curl -k "https://prd-p-egvmw.splunkcloud.com:8088/services/collector/raw?channel=00872DC6-AC83-4EDE-8AFE-8413C3825C4C" -H "Authorization: Splunk XXXXX" -d '{"time": "1626000536.234512596", "event": "Hello, world! new3", "sourcetype":"mydata", "host" : "myhost", "source" : "mysource"}'
```

What you see in Splunk is this,

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/428882/125211631-9c2d1180-e25c-11eb-9842-2e4c7f489970.png">

Notice the multiple source, host and sourcetype attributes at the bottom and they are not indexed too...(search for "host=myhost" does not work)

But if we set them as query params,

```
curl -k "https://prd-p-egvmw.splunkcloud.com:8088/services/collector/raw?channel=00872DC6-AC83-4EDE-8AFE-8413C3825C4C&sourcetype=mydata&source=mysource&host=myhost" -H "Authorization: Splunk XXXXXX" -d '{"time": "1626000536.234512596", "event": "Hello, world! new4"}'
```

it shows up properly in Splunk,

<img width="961" alt="image" src="https://user-images.githubusercontent.com/428882/125211690-19588680-e25d-11eb-8f70-522a63de9466.png">

and a search like "host=myhost" also works fine.

Ideally splunk out shoud have a mode to add source, host and sourcetype as query params.

**Comment by agup006** [comment]
This can be done with the configuration settings

https://docs.fluentbit.io/manual/pipeline/outputs/splunk

```
event_host
Specify the key name that contains the host value. This option allows a record accessors pattern.

event_source
Set the source value to assign to the event data.

event_sourcetype
Set the sourcetype value to assign to the event data.

event_sourcetype_key
Set a record key that will populate 'sourcetype'. If the key is found, it will have precedence over the value set in event_sourcetype.

event_index
The name of the index by which the event data is to be indexed.

event_index_key
Set a record key that will populate the index field. If the key is found, it will have precedence over the value set in event_index.
```

**Comment by bobbygryzynger** [comment]
I'm seeing similar behavior. 

Setting the following doesn't seem to have any effect: 
```
[OUTPUT]
    Name            splunk
    Match           *
    # ...
    Event_Source    mysource
    Event_Index     myindex
    Event_Host      myhost.com
```

**Comment by bobbygryzynger** [comment]
Actually, when using the `1.8.1`+, I'm seeing this work as expected.

**Comment by agup006** [comment]
This was added since 1.7.5 in case that was the issue - closing for now, please re-open if needed
