### ISSUE TITLE
[2021/02/10 14:07:34] [ warn] [engine] failed to flush chunk '1-1612965549.930585548.flb', retry in 815 seconds: task_id=175, input=tail.0 > output=es.0 (out_id=0)

### ISSUE THREAD

**Issue by jilan804** [fluent/fluent-bit#3769]
I am getting these error on fluentbit logs:-[2021/02/10 14:07:34] [ warn] [engine] failed to flush chunk '1-1612965549.930585548.flb', retry in 815 seconds: task_id=175, input=tail.0 > output=es.0 (out_id=0)

[error] [out_es] cloud not pack/validate JSON response

**Comment by hoangphan1509** [comment]
You can try to enable **Trace_Output** and **Trace_Error** then recheck your log for more details. Seem like ES response HTML page instead of JSON.
https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

**Comment by fyzn12** [comment]
I have met this problem and it has been solved. I wonder if I can help you.
1、Check your username and password
2、My OUTPUT configuration is as follows：
output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Logstash_Prefix k8s-fluentbit
        Replace_Dots    On
        Retry_Limit     2
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PWD}
        tls.verify      Off
        tls             On
        #Trace_Output    On
        #Trace_Error     On
