### ISSUE TITLE
Document CVE for all versions of fluent bit in the docs

### ISSUE THREAD

**Issue by kishaningithub** [fluent/fluent-bit#3812]
It would be great if there can be a page where we can see CVEs affecting each version of fluent bit

A link is also fine page need not describe the CVEs in detail

## Scenario

There are several fluent bit agents running in the eco system with different versions. We need to know if any of the deployed version is vulnerable. If so upgrade it to the version with the fix as soon as possible

**Comment by edsiper** [comment]
Thanks for raising this issue. 

We have seen recently a high trend of individuals mentioning or pre-registering CVE for very old issues, in some "sad" cases just to "get attention". I think encouraging CVE documentation for this case might hurt than benefit. 

On the other side, I agree to have security updates on every release note.

**Comment by kishaningithub** [comment]
Thanks for the quick response @edsiper !

Release notes are definitely a great place for this

We are mostly in older versions <= 1.7.x, it would be great if the older release notes can also be updated

**Comment by edsiper** [comment]
1.7 is not longer maintained, upgrades are encouraged.

**Comment by kishaningithub** [comment]
@edsiper I agree

Anyway for people(like me) who are anyway looking for CVEs for older versions of fluent bit to help push upgrades to the latest version, you can find the same here

https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query=cpe%3A2.3%3Aa%3Atreasuredata%3Afluent_bit%3A*%3A*%3A*%3A*%3A*%3A*%3A*%3A*&search_type=all&isCpeNameSearch=true
