### ISSUE TITLE
Nested fields are not removed with modify filter

### ISSUE THREAD

**Issue by wiegandf** [fluent/fluent-bit#3819]
## Bug Report

**Describe the bug**
The modify remove_regex action doesn't seem to work with nested fields. If I change remove_regex from below regex to kubernetes, it successfully removes all fields nested under kubernetes. If I specify kubernetes.pod_name (to keep it more simple than what we try to achieve below), it doesn't delete the pod_name key.

**To Reproduce**
- Rubular link if applicable: https://rubular.com/r/HZz3tYAahj6JCd
- Example log message if applicable: 
```
[4] kube.var.log.containers.fluent-bit-9g7mq_logging_fluent-bit-b3584f72c914ae40d8fba187aaf5bfb32df25d698295f551b6e47e8ba9972e14.log: [1626853783.675011873, {"log"=>"[1] kube.var.log.containers.fluent-bit-9g7mq_logging_fluent-bit-b3584f72c914ae40d8fba187aaf5bfb32df25d698295f551b6e47e8ba9972e14.log: [1626853782.000000000, {"log"=>"[2021/07/21 07:49:42] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
", "cluster_name"=>"cds-dev", "stream"=>"stdout", "time"=>"2021-07-21T07:49:43.675011826Z", "kubernetes"=>{"host"=>"<host>", "pod_id"=>"<pod_id>", "labels"=>{"app_kubernetes_io/name"=>"fluent-bit", "controller-revision-hash"=>"6c68974c44", "app_kubernetes_io/instance"=>"fluent-bit", "pod-template-generation"=>"152"}, "docker_id"=>"<docker_id>", "container_image"=>"fluent-bit/fluent-bit:1.8.1", "pod_name"=>"fluent-bit-9g7mq", "container_name"=>"fluent-bit", "namespace_name"=>"logging"}}]
```
- Steps to reproduce the problem:

**Expected behavior**
All Kubernetes labels except kubernetes.labels.app are removed

**Actual behavior**
Nothing is removed 

**Your Environment**

* Version used: 1.8.1
* Configuration:
```
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Merge_Log           On
        Merge_Log_Key       logs
        Annotations         Off
    [FILTER]
        Name                modify
        Match               kube.*
        Remove_regex        ^(kubernetes\.labels\.(?!app$).*)$
```
* Environment name and version (e.g. Kubernetes? What version?): k8s v1.19.12
* Filters and plugins: kubernetes and modify filters

**Additional context**
We're trying to drop all keys under kubernetes['labels'] except kubernetes['labels']['app']

**Comment by kien-truong** [comment]
I don't think it's really a bug since `.` is also valid character in key field , i.e `{"kubernetes.labels.app" : "app_name"}` is as much valid as `{"kubernetes": {"labels": {"app" : "app_name"}}}`, but they're represented differently in the code. You filter will probably match the first case, but not the second case.

Personally, I've never seen `modify` working with deeply nested map. I've always have to combine it with the `nest` filter such as `unnest/lift -> modify -> nest` if I want to change some nested fields.

**Comment by atheriel** [comment]
This is probably a dupe of #2152, which had some progress made recently in #3695.
