### ISSUE TITLE
Release notes are missing for v1.8.1

### ISSUE THREAD

**Issue by kishaningithub** [fluent/fluent-bit#3826]
## Bug Report

**Describe the bug**
In the [release notes page](https://fluentbit.io/announcements/) the release notes for v1.8.1 is missing after the new v1.8.2 release

**Screenshot**

<img width="892" alt="Screenshot 2021-07-22 at 12 06 52 PM" src="https://user-images.githubusercontent.com/763760/126598701-eb294507-93b9-42a1-901e-3cf593b125fb.png">

**Comment by stevehipwell** [comment]
@kishaningithub I think v1.8 is v1.8.1 as there was an issue with the v1.8.0 release based on the response I got to https://github.com/fluent/fluent-bit/issues/3765.

**Comment by kishaningithub** [comment]
Thanks for the clarification @stevehipwell
