### ISSUE TITLE
Kubernetes filter regex failures can cause a denial of service

### ISSUE THREAD

**Issue by atheriel** [fluent/fluent-bit#3829]
## Bug Report

**Describe the bug**

At present the Kubernetes filter is usually combined with the Tail plugin to watch container logs. When configured correctly it will parse the tag to determine which container to look up in the Kubernetes API.

However, in some cases, for unknown reasons, the regular expression will fail for one of these log files. This has been reported before, and I've seen it happen in practice many times (even if manual verification of the regex looks fine).

When this occurs, the Kubernetes filter returns `FLB_FILTER_NOTOUCH` and the record is passed on unmodified. Importantly, Fluent Bit also issues a warning:

```
[ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag ...
```

An extremely dangerous case is when the regex fails for a Fluent Bit pod. If that occurs, the warning log itself gets picked up by **the same pod**, re-triggering a new warning message, and so on, and so on:

```
$ kubectl --context <cluster> -n logging logs --tail=10 logging-fluent-bit-j8c7p
[2021/07/22 13:35:57] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.logging-fluent-bit-j8c7p_logging_fluent-bit-091b61479c684c338cda975aeb6a31ff10e148dea90fa9702eb27100fb54f399.log
[2021/07/22 13:35:57] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.logging-fluent-bit-j8c7p_logging_fluent-bit-091b61479c684c338cda975aeb6a31ff10e148dea90fa9702eb27100fb54f399.log
[2021/07/22 13:35:57] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.logging-fluent-bit-j8c7p_logging_fluent-bit-091b61479c684c338cda975aeb6a31ff10e148dea90fa9702eb27100fb54f399.log
```

I've seen this condition lead to immediate 100% CPU consumption and many MB/s written to outputs as Fluent Bit processes the warning messages it's writing as fast as possible. (And in fact it took down an internal Splunk instance by overwhelming it with data in multiple occasions.) This is why I have termed it a "denial of service".

**To Reproduce**

I don't have a way of reproducing the regex failures that lead to this issue, but it happens in our clusters every few hours.

**Expected behavior**

Ideally the regular expression wouldn't fail, but that's not what this issue is about.

I expect Fluent Bit to handle this state more gracefully. Either (1) drop these records instead; or (2) implement some kind of circuit breaking to prevent the runaway behaviour.

Currently it's possible to "fix" this issue by adding another filter that will drop records if they don't have any Kubernetes metadata, but I don't think this is a good solution.

**Your Environment**

* Version used: 1.8.2
* Configuration:
```
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Tag kube.*

[FILTER]
    Name kubernetes
    Match kube.*
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes (observed for various versions)
* Filters and plugins: Kubernetes filter, Tail input plugin

**Comment by edward-bear** [comment]
With fluentd you get round this self-ingestion of logs issue by exluding the fluentd logs 

with something like:  exclude_path ["/var/log/containers/fluentd*"]

How about this for fluent bit? Haven't tried it, but would also like to know the best solution for this issue.
https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#kubernetes-annotations

Maybe you do want the fluent bit logs though, but you just want to avoid the ddos loop scenario..?

**Comment by atheriel** [comment]
Unfortunately the Kubernetes exclude annotation doesn't work in this case (it was my first thought), because the error happens before we get any pod metadata at all (including annotations).

But more generally:

> Maybe you do want the fluent bit logs though, but you just want to avoid the ddos loop scenario..?

I'd like to avoid ignoring other issues surfaced in Fluent Bit's logs, yes.

After some more thought: what is particular about this case is that once the regex fails, it seems to continue failing indefinitely. I don't think you want to warn on every log record if the underlying problem is the same, so it may be better to teach the Kubernetes filter plugin to cache tags failing to match the regex and warn only once -- after which it will silently ignore them.

**Comment by gabegorelick** [comment]
I just ran into this. My node was running fine and then all of a sudden experienced this issue. It would be nice to fix the underlying issue (why does fluent-bit get into this state where the regex fails), separate from the issue that is the huge volume of logs that can be generated
