### ISSUE TITLE
Uuid filter

### ISSUE THREAD

**Issue by kishaningithub** [fluent/fluent-bit#3848]
**Is your feature request related to a problem? Please describe.**
Because of the atleast once delivery semantics there are duplicate messages ingested into the outputs

Eg: Say if 1000 records are being flushed and the output plugin sends out 100 at a time (batch size 100) and the failure happens for the last batch. Then the fluent bit retry flushes the 1000 records once again. Now we have 900 duplicate records

**Describe the solution you'd like**
I would like a uuid filter to be added so that we can add uuid per record that way we can perform deduplication in the downstream systems

**Describe alternatives you've considered**
We have cooked up a uuid filter using Lua but I feel having it in C would be much much better

**Additional context**
We are ingesting log information from various sources making deduplication hard without a uuid in place

**Comment by kishaningithub** [comment]
Notstale

**Comment by kishaningithub** [comment]
I feel this utility function can be used to implement this

https://github.com/fluent/fluent-bit/blob/85a69a11e522f95291f6d521f44ce64069fe5cd1/src/flb_utils.c#L1024

**Comment by kishaningithub** [comment]
Notstale

**Comment by kishaningithub** [comment]
Notstale

**Comment by kishaningithub** [comment]
Notstale

**Comment by patrick-stephens** [comment]
Please submit a PR
