### ISSUE TITLE
Toggle ANSI color characteres from k8s

### ISSUE THREAD

**Issue by kadooster** [fluent/fluent-bit#3861]
Whenever we are treating logs from Kubernetes of Java applications, some are filled with ANSI characters based on developers will. This is expected to happen on k8s part, as it colorizes the different information if tailed over kubectl. Java logging format sometimes adds colorization on top of that. E.g.:
>{"log":"2021-07-14T03:23:44.315Z / \u001b[32minfo\u001b[39m: Server started on port: 3000 - Environment \"\"\r\n","stream":"stdout","time":"2021-07-14T03:23:44.32473488Z"}

Fluent-bit properly handles '\u001b' in accordance with the [escaped_utf8 decoders example](https://docs.fluentbit.io/manual/pipeline/parsers/decoders#escaped_utf8) and, as previous discussions, isn't even necessary to request this parser as fluent-bit applies it automatically. Amazing!

ANSI characters, however, are still passing ahead to desired storage (E.S. in my case) and dirty up the logs with this data:
> `log_processed.log.keyword: [37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:`

The JSON field in ES looks like this:
>`"log_processed.log": [
      "\u001b[37;40mnpm\u001b[0m \u001b[0m\u001b[31;40mERR!\u001b[0m\u001b[35m\u001b[0m A complete log of this run can be found in:\r"
    ],`

This is an issue if we save those logs in any storage. In previous E.S. versions we could "decorate" those chars and ignore them with the help of a plugin, although they were being undesirably stored. A better approach would be to trim out those values in processing time.

As grep filter deals with full fields, exclusion over a string doesn't work as it would result in loosing the whole field. Also, reverse regex didn't worked as expected, as it would create a regex group for each character in the log and mess up the output, dramatically reducing performance too. Having this pattern tested, we could filter in all those values, but the idea would be to filter it out:
`\[[0-9\;]{1,}m`

An interesting feature would be to "invert" regex parsers, as it would give us flexibility or, ideally, the kubernetes filter could handle this case as well, with a possible toggle in or out to this feature.

**Comment by liyuntao** [comment]
IMO this should be configured properly on the application side. Sample codes below in my Spring Boot project:

For benefits of both local development(pretty log output) and online environment
1. When the program starts, make a simple detection of whether process is running under a container environment. 
2. If so, simply change the logger to format without ANSI color characters.

```java
@SpringBootApplication
public class Starter {
    public static void main(String[] args) {
        SpringApplication app = new SpringApplication();
        app.addListeners(new ChangeLogger());
        app.setSources(new HashSet(Collections.singletonList(Starter.class)));
        app.run(args);
    }
}

@Slf4j
class ChangeLogger implements ApplicationListener<ApplicationContextInitializedEvent> {
    public static Boolean isRunningInsideDocker() {
        try (Stream<String> stream =
                     Files.lines(Paths.get("/proc/1/cgroup"))) {
            return stream.anyMatch(line -> line.contains("/docker"));
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public void onApplicationEvent(ApplicationContextInitializedEvent event) {
        if (isRunningInsideDocker()) {
            final LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
            final org.apache.logging.log4j.core.config.Configuration config = ctx.getConfiguration();
            org.apache.logging.log4j.core.config.LoggerConfig rootLoggerConfig = config.getLoggers().get("");
            rootLoggerConfig.removeAppender("Console");
            rootLoggerConfig.addAppender(config.getAppender("ConsoleInDocker"), null, null);
            ctx.updateLoggers();
        }
    }
}
```


parts in log4j.xml
```xml
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%d{DEFAULT} %highlight{%-5level }[%style{%t}{bright,blue}] [%X{TRACE_LOG_ID}] %style{%C}{bright,yellow}: %msg%n%throwable" />
        </Console>

        <Console name="ConsoleInDocker" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%d{DEFAULT} %-5level [%t] [%X{TRACE_LOG_ID}] %C: %msg%n%throwable" />
        </Console>
    </Appenders>
```

**Comment by kadooster** [comment]
Hello @liyuntao, thanks for the reply and thank you so much for the detailed info on how to proceed. I'll definitely take this in consideration.

Still, this is the only action I could take before this issue, so I stick with the idea that this capability in fluent-bit would be welcomed. As commented, being able to invert the grep would bring a lot of flexibility, and a new parser for this purpose would also be very interesting. 

Please, let me know if the feature is not useful or to demanding and I'll close the issue.

**Comment by edward-bear** [comment]
Our setup --

apps log with ANSI codes.. this is fine for kubectl logs, and also Rancher UI will display these colours for you.

Even Grafana UI it seems can decode most of these.. maybe not all of them.. I'm testing this with my logs now and trying to get this work... 

Otherwise .. if they are written to disk via docker full of ANSI codes.. it's not really a problem as long as they look good in the UI like Grafana.

So if the apps stopped producing ANSI codes.. fine.. but we would loose the colours from some services like Rancher. 

It may be possible to strip them.. with a regex that was used in the FluentD plugin (no longer maintained) here https://github.com/mattheworiordan/fluent-plugin-color-stripper

The regex you will find in the code.

This is my last resort if I can't get this to work.. because, again, ideally I want the log colours to display in grafana UI.

...

**Comment by kadooster** [comment]
Indeed @edward-bear , being able to strip out these from a specific output is the best scenario, because we'll be able to choose where this colorization is useful and where it is not. I'll find some way to hide it from Kibana interface, that might work for my scenario at least. I'll update here if any idea comes to mind.

**Comment by ThangLeQuoc** [comment]
You can easily deal with this ANSI color scheme issue by applying a Lua filter that detect and remove all ANSI shell color code
```
    [FILTER]
        Name                lua
        Match               *
        code                function strip_ansi_color_code(tag, timestamp, record) if type(record["log"]) == "string" then record["log"] = record["log"]:gsub('[\27\155][][()#;?%d]*[A-PRZcf-ntqry=><~]', '') return 2, 0, record end return 0, 0, 0 end
        call                strip_ansi_color_code

```

https://github.com/fluent/fluent-bit/issues/4491#issuecomment-1985451574

**Comment by numbpun** [comment]
Even after applying the lua filter to remove the ANSI color scheme, it is still not removing the ANSI characters and is output to Opensearch with them. When I use stdout, I cannot see any ASCI .
