### ISSUE TITLE
[Kubernetes filter] Add namespace_labels to the metadata 

### ISSUE THREAD

**Issue by bodz1lla** [fluent/fluent-bit#3865]
Dear Fluent-bit Team,

At the moment we're using the `splunk-connect` which sends all events to Splunk by filtering only namespaces with labels `splunk=true` and `splunk_index=`.

Since the `fluent-bit:1.8.2` has recently been released, we would like to try `multiline parser` of the `CRI` log and to replace the `fluentd`. 

Unfortunately, we unable to proceed with that due to missing `namespace_labels` in the Kubenetes metadata. 

Any comments and suggestion will be appreciated.

**Comment by AndreyBar** [comment]
Guys, any news on this topic?
