### ISSUE TITLE
[Tail] Ignore_Older not working on 1.7.X and 1.8.X

### ISSUE THREAD

**Issue by DandyDeveloper** [fluent/fluent-bit#3873]
## Bug Report

**Describe the bug**
`Ignore_Older` as a parameter is not working at all in verions 1.7.X or 1.8.X. 

I have a very simple fluentbit config that I'm mounting a log into, echoing a newline into that file with a `time` of older then the configured time results in that content being processed as normal. But it should not.

Do the exact same steps / logic through 1.6.10, it works perfectly. 

**To Reproduce**
Use the following instructions to reproduce. 

Fluentbit Config:
```sh
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name     tail
    Path     /var/log/containers/*
    Parser docker
    Refresh_Interval     5
    Skip_Long_Lines     true
    Ignore_Older     5m
    Tag     kube.*

[OUTPUT]
    Name          stdout
    Match         kube.*
```

Mount a file with this content (Intentionally old):
temp.log
```sh
{"log":"2021-07-28 00:22:21.646467 I | exec: Running command: udevadm info --query=property /dev/sdh","stream":"stderr","time":"2021-07-28T00:23:21.646513926Z"}
```

Run the container: 

```sh
docker run  -v <LOCATION>/fleunt-bit.conf:/fluent-bit/etc/fluent-bit.conf \
-v <LOCATION>/temp.log:/var/log/containers/temp.log \
fluent/fluent-bit:1.8-debug 
```

Then exec into the container running fluent and do the following:
```sh
echo '{"log":"2021-07-28 00:22:21.646467 I | exec: Running command: udevadm info --query=property /dev/sdh","stream":"stderr","time":"2021-07-27T00:23:21.646513926Z"}' >> /var/log/containers/temp.log
```

**Expected behavior**
I would expect nothing to be output in stdout as the line has a `time` of older then the specified 5 minutes. 

This is what happens on 1.6.10, not on 1.7.X or 1.8.X

I.E: **NOT WORKING EXAMPLE**

```sh
[2021/07/28 02:32:06] [ info] [sp] stream processor started
[2021/07/28 02:32:06] [ info] [input:tail:tail.0] inotify_fs_add(): inode=584309 watch_fd=1 name=/var/log/containers/temp.log
[2021/07/28 02:32:24] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.temp.log
[0] kube.var.log.containers.temp.log: [1627345401.646513926, {"log"=>"2021-07-28 00:22:21.646467 I | exec: Running command: udevadm info --query=property /dev/sdh", "stream"=>"stderr", "time"=>"2021-07-27T00:23:21.646513926Z"}]
[2021/07/28 02:32:26] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.temp.log
[0] kube.var.log.containers.temp.log: [1627345401.646513926, {"log"=>"2021-07-28 00:22:21.646467 I | exec: Running command: udevadm info --query=property /dev/sdh", "stream"=>"stderr", "time"=>"2021-07-27T00:23:21.646513926Z"}]
```

**Your Environment**
* Version used: 1.6.10 (Working), 1.7.8 & 1.8.2 (Not working)
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): Docker / Kubernetes
* Server type and version: N/A
* Operating System and version: N/A
* Filters and plugins: See above configuration.

**Comment by thodquach** [comment]
I met the same problem with fluenbit 1.7.x

**Comment by DandyDeveloper** [comment]
Oh woops. Keep open. This seems like a big problem, why is no one giving input on this?

**Comment by venugopalthati** [comment]
Came across the same issue in version 1.8.8 as well. Reverted to version 1.6.10

**Comment by nokute78** [comment]
I think https://github.com/fluent/fluent-bit/commit/ee77895320f75a0863b821df496d8b4bb2a4e515#diff-e5b311cc52054c16cd47444778c37e0b272cbbb885096e6e25b5ea5a8abd2df9 changed the behavior.
