### ISSUE TITLE
 HTTP status=400 Not retrying.    has timestamp too new: 2021-07-28 16:35:00.551992233 +0300 MSK

### ISSUE THREAD

**Issue by justknife** [fluent/fluent-bit#3876]
Good afternoon.
An error of the following nature has occurred
My surrounding:
containerd
fluent bit
loki.
Log fluent bit:
[2021/07/28 13:36:00] [error] [output: loki: loki.0] loki-distributed-gateway: 80, HTTP status = 400 Not retrying. │
│ entry for stream '{app_kubernetes_io_instance = "fluent-bit", app_kubernetes_io_name = "fluent-bit", controller_revision_hash = "568885cb56", pod_template_generation = "1"}' has timestamp too new: 2021-07-28 16: 35: 17.12 +0300 MSK 
Problems:
1. Time is not parsed in parser.multiline cri
2. Data is sent as is to locks.
During the analysis of the problem, it was revealed:
```
{
  "streams": [
    {
      "stream": {
        "label": "value"
      },
      "values": [
          ["<unix epoch in nanoseconds>", "<log line>"],
          ["<unix epoch in nanoseconds>", "<log line>"]
      ]
    }
  ]
}
```
Instead of " < unix epoch in nanoseconds > ", we have 0

**Comment by mkenne11** [comment]
I am also experiencing the same error when trying to write the fluent-bit "loki" output plugin:
```
[2021/10/20 02:48:03] [error] [output:loki:loki.1] loki.netanalysis.svc.cluster.local:3100, HTTP status=400 Not retrying.
entry for stream '{job="network"}' has timestamp too new: 2021-10-20 13:48:03 +0000 UTC
```

I am using the standard fluent-bit container build on docker hub. I believe the problem is because the time on the fluent-bit container is using UTC (Greenwich time) and the label passed uses my local time i.e. UTC +11:00.

See my loki output plugin config:
```
    [OUTPUT]
        Name          loki
        Match         syslog.*
        Host          loki.netanalysis.svc.cluster.local
        Port          3100
        labels        job=network_analysis
```
