### ISSUE TITLE
fips compliance

### ISSUE THREAD

**Issue by ericmillin** [fluent/fluent-bit#3879]
@agup006 inidcates that FIPS compliance may be in the works (https://github.com/fluent/fluent-bit/issues/1453#issuecomment-781742395). Are you planning on supporting FIPS and if so, what is the relative priority of the work?

**Comment by agup006** [comment]
hey @ericmillin we have changed to OpenSSL however do not have supporting FIPS on the roadmap for near term / mid term (6 month). Priority is quite low as we haven't had many users ask for it to be honest

If you are interested in contributing and submitting a PR we would gladly welcome it

**Comment by ericmillin** [comment]
@agup006 Thanks for the update. I'll talk to my team and check on the feasibility of a PR. I'll let you know once we reach a decision.

**Comment by ericmillin** [comment]
@agup006 We will submit a PR in the next couple months. Thanks.
