### ISSUE TITLE
[Tail] File rotation causing data shuffle

### ISSUE THREAD

**Issue by StephenLeeY** [fluent/fluent-bit#3883]
## Bug Report

**Describe the bug**

Very rarely, when rotating an input file, the tail input plugin scatters the last bit of data of the rotated file (a couple hundred lines) with the beginning of the next file.

For example, if we have file 1 with 1000 lines and file 2 with 1000 lines, the data might look like this:
```
line 948
line 949
line 950
line 1000 (file 2)
line 1001
...
line 1015
line 951 (file 1)
line 952
line 953
line 1016
line 1017
...
line 1025
line 954 (file 1)
line 955
...
```

**To Reproduce**
- Steps to reproduce the problem: When encountering this bug, I was running an instance of FluentBit where there were multiple tail input plugins and multiple output plugins. In each run where I was reading ~2 GB of data, this issue occurred about once, usually fairly far into the run where around ~1.7 GB had already been read.

**Expected behavior**

Data shuffling should not occur, and all log lines should be in the order that they were read.

**Screenshots**

**Your Environment**

* Version used: Master
* Configuration:
```
[SERVICE]
    Flush 10
    storage.path /tmp/fluent-bit/output-buffer

[INPUT]
    name tail
    ...
    db /tmp/fluent-bit/database.db
    db.locking true
    read_from_head true
    refresh_interval 10
    buffer_max_size 8M
    mem_buf_limit 8M
    skip_long_lines on
    storage.type filesystem

[INPUT]
    name tail2
    ...

[INPUT]
    name tail3
    ...

< Insert 5 output plugins here >
```

**Comment by PettitWesley** [comment]
@StephenLeeY An example using the file output might be interesting. The upstream maintainers can easily repro with that. And the file output should be the simplest test case. You read a file, and output the results to another file, and then check if the ordering is broken in the output file. 

Just a suggestion if this makes sense.
