### ISSUE TITLE
Docker multiline parser errors

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluent-bit#3886]
## Bug Report

**Describe the bug**
When using the docker multiline parser we get a lot of errors in the following format.

```
[2021/07/29 08:27:45] [error] [multiline] invalid stream_id 1817450727403209240, could not append content to multiline context
```

**To Reproduce**
Our fluent-bit config which is running via the official Helm chart on an EKS cluster.

```
[SERVICE]
  Daemon Off
  Flush 1
  Log_Level info
  HTTP_Server On
  HTTP_Listen 0.0.0.0
  HTTP_Port 2020
  storage.path /var/log/flb-storage/
  storage.sync normal
  storage.checksum off
  storage.max_chunks_up 128
  storage.backlog.mem_limit 16M
  storage.metrics on
  Parsers_File parsers.conf
  Parsers_File custom_parsers.conf

[INPUT]
  Name tail
  Path /var/log/containers/*.log
  multiline.parser docker, cri
  Tag kube.*
  Skip_Long_Lines On
  Buffer_Chunk_Size 32k
  Buffer_Max_Size 256k
  DB /var/log/flb-storage/tail.db
  DB.Sync normal
  storage.type filesystem

[FILTER]
  Name kubernetes
  Match kube.*
  Merge_Log On
  Merge_Log_Key log_processed
  Merge_Log_Trim On
  Keep_Log Off
  K8S-Logging.Parser On
  K8S-Logging.Exclude On

[OUTPUT]
  Name forward
  Match *
  Host fluentd.logging.svc
  Port 24224
```

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: v1.8.2
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): EKS v1.21
* Server type and version: n/a
* Operating System and version: n/a
* Filters and plugins: See above

**Additional context**

**Comment by agup006** [comment]
Hey @stevehipwell thanks for reporting, there were quite a few issues with 1.8.2 and we did fix a few in 1.8.3. Would you be able to retry with that version?

**Comment by stevehipwell** [comment]
@agup006 I'll test this once https://github.com/fluent/helm-charts/pull/145 is merged.

**Comment by jankosecki** [comment]
I've pinned image version to 1.8.3 manually and can unfortunately say the error is still happening. Reboot seems to help temporarily. I managed to spot a moment when this error starts for the first time before the buffer gets flooded with error lines:
```
[2021/08/03 08:44:16] [ info] [input:tail:tail.0] inode=1557613 handle rotation(): /var/log/containers/kafka-4_dev_kafka-f97e589f47fc9ab06afc29de75be59626703adf2a86dbc268cdc6d582e2a3edb.log => /var/lib/docker/containers/f97e589f47fc9ab06afc29de75be59626703adf2a86dbc268cdc6d582e2a3edb/f97e589f47fc9ab06afc29de75be59626703adf2a86dbc268cdc6d582e2a3edb-json.log.1
[2021/08/03 08:44:16] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1557613 watch_fd=16
[2021/08/03 08:44:16] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1557613 watch_fd=31 name=/var/lib/docker/containers/f97e589f47fc9ab06afc29de75be59626703adf2a86dbc268cdc6d582e2a3edb/f97e589f47fc9ab06afc29de75be59626703adf2a86dbc268cdc6d582e2a3edb-json.log.1
[2021/08/03 08:44:18] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1557743 watch_fd=32 name=/var/log/containers/kafka-4_dev_kafka-f97e589f47fc9ab06afc29de75be59626703adf2a86dbc268cdc6d582e2a3edb.log
[2021/08/03 08:44:23] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1557613 watch_fd=31
[2021/08/03 08:44:23] [error] [multiline] invalid stream_id 9275124730216209964, could not append content to multiline context
```
Seeing the error starts happening just after log rotation is detected by the `tail` input, I think they must be related?

**Comment by lhelman** [comment]
Also, worth mentioning that, I don't see these errors getting surfaced on the metrics.

So fluent-bit might not be collecting a single log line, and metrics say it is healthy.

**Comment by rsumukha** [comment]
Tested with 1.8.3 seeing the same with cri parser. Logs fail to ship once it goes thru log rotation. Fluent-bit errors out with `could not append content to multiline context`.

**Comment by stevehipwell** [comment]
@edsiper is there any progress on this?

**Comment by michaelgeorgeattard** [comment]
We are encountering the same issue on `1.8.3`, I can gladly attach more details if needed.

**Comment by PettitWesley** [comment]
@edsiper We have seen this issue in my team at AWS as well.

**Comment by rsumukha** [comment]
We are seeing the same issue on `1.8.3` for cri logs.

**Comment by edsiper** [comment]
thanks for reporting the issue, would you please provide example log files that helps to reproduce the issue ?

**Comment by rsumukha** [comment]
Fluent-bit config 
```
   [INPUT]
       Name tail
       Tag kube.*
       DB /var/log/flb_kube.db
       Mem_Buf_Limit 10MB
       multiline.parser cri
       Path /var/log/containers/*.log
       Refresh_Interval 10
       Rotate_Wait 30
       Skip_Long_Lines On

    [OUTPUT]
        Name stdout
        Match * 
```
Tail plugin works fine until the log-rotation. Once log rotates then we see `could not append content to multiline context`

```
        2021-08-02T14:07:51.231-07:00	{"log":"[2021/08/02 21:07:51] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1727284 watch_fd=2 name=/var/log/containers/multiline-demo_default_test-2-a22fdaa97fbcad64fd66ad10c390198c083d38d993d86f9df891941d759f7b65.log"}
	2021-08-02T14:07:55.968-07:00	{"log":"time=\"2021-08-02T21:07:55Z\" level=info msg=\"[cloudwatch 0] Created log stream from-fluent-bit-kube.var.log.containers.multiline-demo_default_test-2-a22fdaa97fbcad64fd66ad10c390198c083d38d993d86f9df891941d759f7b65.log in group filter-cm-test\""}
	2021-08-02T17:32:10.275-07:00	{"log":"[2021/08/03 00:32:10] [ info] [input:tail:tail.0] inode=1727102 handle rotation(): /var/log/containers/multiline-demo_default_test-531a293af516b7148c09b5316c5c99161e2ce31a1a7ad0636b44b8bf8ddd9127.log =\u003e /var/log/pods/default_multiline-demo_1ea2d294-9b72-4e55-b41b-0949c55faf4d/test/0.log.20210803-003210"}
	2021-08-02T17:32:10.275-07:00	{"log":"[2021/08/03 00:32:10] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1727102 watch_fd=1"}
	2021-08-02T17:32:10.276-07:00	{"log":"[2021/08/03 00:32:10] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1727102 watch_fd=3 name=/var/log/pods/default_multiline-demo_1ea2d294-9b72-4e55-b41b-0949c55faf4d/test/0.log.20210803-003210"}
	2021-08-02T17:32:10.941-07:00	{"log":"[2021/08/03 00:32:10] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1727311 watch_fd=4 name=/var/log/containers/multiline-demo_default_test-531a293af516b7148c09b5316c5c99161e2ce31a1a7ad0636b44b8bf8ddd9127.log"}
	2021-08-02T17:32:40.897-07:00	{"log":"[2021/08/03 00:32:40] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1727102 watch_fd=3"}
	2021-08-02T17:32:42.854-07:00	{"log":"[2021/08/03 00:32:42] [error] [multiline] invalid stream_id 8649363796039376046, could not append content to multiline context"}
	2021-08-02T17:32:42.854-07:00	{"log":"[2021/08/03 00:32:42] [error] [multiline] invalid stream_id 8649363796039376046, could not append content to multiline context"}
```

**Comment by yurymuski** [comment]
same issue for me
any workarounds besides restarting fluent-bit pods?

**Comment by tonychoe** [comment]
We're having the same issue with FluentBit v1.8.3. 

```
[2021/08/23 15:40:48] [error] [multiline] invalid stream_id 6842456611372491590, could not append content to multiline context
[2021/08/23 15:40:48] [error] [multiline] invalid stream_id 4350310108622390529, could not append content to multiline context
```

```
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc.cluster.local:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix     kube.var.log.containers.
    Merge_Log           Off
    Keep_Log            Off
    Merge_Log_Trim      Off
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Annotations         Off
    Use_Kubelet         true
    Kubelet_Port        10250
    Buffer_Size         0
```

Kubernetes versions
- v1.19.7
- v1.20.8

The error come up gradually and no logs are collected by FluentBit eventually. We had to restart the FluentBit Pods.

**Comment by tlamr** [comment]
We hit this with cri-o and k8s 1.19.8 on EKS.

**Comment by zhonghui12** [comment]
Hi @edsiper, is there any update on this issue?

**Comment by stevehipwell** [comment]
@edsiper is `v1.8.5` (or `v1.8.4`) expected to resolve this?

**Comment by stevehipwell** [comment]
@cdobbyn have you tried `v1.8.6`?

**Comment by pavankumar-go** [comment]
@stevehipwell I confirm  `v1.8.6` has this problem

**Comment by stevehipwell** [comment]
Thanks @pavankumar-go & @cdobbyn.

@edsiper do you need anything else to help fix this?

**Comment by lubingfeng** [comment]
Another user encountered this issue. Do we have a timeline for the fix?

**Comment by pranavmarla** [comment]
Just encountered the same issue as well when running a performance test (app container generating a lot of logs; Fluent Bit tailing that container log file). 

Specifically, here is what we observed:
- The error is triggered by a log rotation of the input container log file
- Fluent Bit generates hundreds of error messages like this:
`[2021/09/03 18:47:40] [error] [multiline] invalid stream_id 4395029823782301522, could not append content to multiline context`
- More importantly, **Fluent Bit seems to drop the input logs!**
- Interestingly, even though this is a multiline parser issue, none of the logs in our performance test were multiline -- the max length of any of our logs was 1055 characters (~1KB), which is too small to be split into multiple lines by containerd.
- A few people mentioned that they only saw the issue with Docker-formatted logs, but we experienced this same issue with CRI (specifically, containerd) formatted logs.
- Also, we tried both the following multiline parser settings, in our _tail_ input plugin, but it made no difference -- we got the same error in both cases:
  - `multiline.parser  cri, docker`
  - `multiline.parser  cri`
- We experienced the same error for the following versions of Fluent Bit:
  - `1.8.5`
  - `1.8.4`

**Comment by vkudrik** [comment]
> Just encountered the same issue as well when running a performance test (app container generating a burst of logs; Fluent Bit tailing that container log file).
> 
> Specifically, here is what we observed:
> 
>     * The error is triggered by a log rotation of the input container log file
> 
>     * Fluent Bit generates hundreds of error messages like this:
>       `[2021/09/03 18:47:40] [error] [multiline] invalid stream_id 4395029823782301522, could not append content to multiline context`
> 
>     * More importantly, **Fluent Bit seems to drop the input logs!**
>       i.e. Shortly after we see the above multiline error messages in Fluent Bit, the logs stop showing up in our output destination -- in fact, it looks like the logs are no longer even making it to our output plugin.
> 
>     * Interestingly, even though this is a multiline parser issue, none of the logs in our performance test were multiline -- the max length of any of our logs was 1055 characters (~1KB), which is too small to be split into multiple lines by containerd.
> 
>     * A few people mentioned that they only saw the issue with Docker-formatted logs, but we experienced this issue with CRI (specifically, containerd) formatted logs.
> 
>     * Also, we tried both the following multiline parser settings, in our _tail_ input plugin, but it made no difference -- we got the same error in both cases:
>       
>       * `multiline.parser  cri, docker`
>       * `multiline.parser  cri`
> 
>     * We experienced the same error for the following versions of Fluent Bit:
>       
>       * `1.8.5`
>       * `1.8.4`
> 
>     * Fluent Bit config:
> 
> 
> ```
> [INPUT]
>   name              tail
>   tag               kube.*
>   path              /var/log/containers/*.log
>   path_key          log_file
>   read_from_head    false
>   refresh_interval  2
>   rotate_wait       5
>   db                /var/log/fluentbit-container-logs.db
>   db.sync           normal
>   db.locking        true
>   buffer_chunk_size 128KB
>   buffer_max_size   1MB
>   skip_long_lines   on
>   mem_buf_limit     199800KB
>   multiline.parser  cri, docker
> ```

We're experiencing the same issue with same conditions. Just after error firstly occurs, **logs are dropped** from output.
None of our config changes made it work as expected.

**Comment by vkudrik** [comment]
Found solution by rolling back to legacy multiline parser:
```
[INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        Parser              docker
        # ...
        Docker_Mode         On
        Docker_Mode_Flush   5
        Docker_Mode_Parser  docker_read_firstline
 [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%L
        Time_Keep           On
[PARSER]
        Name                docker_mufirstline
        Format              regex
        Regex               (?<log>(?<="log":")\d{4}[\/-]\d{1,2}[\/-]\d{1,2}[ T]\d{2}:\d{2}:\d{2}(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
```

**Comment by vkudrik** [comment]
Found solution by rolling back to legacy multiline parser:
```
[INPUT]
        Name                tail
        Tag                 kube.*
        Path                /var/log/containers/*.log
        Parser              docker
        # ...
        Docker_Mode         On
        Docker_Mode_Flush   5
        Docker_Mode_Parser  docker_multiline
 [PARSER]
        Name                docker
        Format              json
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%L
        Time_Keep           On
[PARSER]
        Name                docker_multiline
        Format              regex
        Regex               (?<log>(?<="log":")\d{4}[\/-]\d{1,2}[\/-]\d{1,2}[ T]\d{2}:\d{2}:\d{2}(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
```

**Comment by lubingfeng** [comment]
Do we have a plan to get this issue addressed in next release?

**Comment by edsiper** [comment]
FYI: we are taking a look at this

**Comment by lubingfeng** [comment]
Do we have an ETA for this one?

**Comment by bitwalker** [comment]
I'll chime in and confirm that I'm seeing this on GKE, 1.20.9-gke.701, COS-based nodes, with `multiline.parser cri` (and `multiline.parser cri, docker`). Errors start appearing eventually and it seems like the longer you wait, fewer logs get collected. Same basic thing as the other reports. Definitely seems to be related to log rotation as others have observed.

It wouldn't be super pressing if the logs still got delivered, just in maybe less-than-ideal format, but since it results in the logs just being dropped, its critical. I'm going to give the workaround by @vkudrik a shot, and hopefully that'll work in the short term until a new release with a fix is dropped.

**Comment by stevehipwell** [comment]
@edsiper do you have any more info on this?

**Comment by coreders** [comment]
We have the exact same issue on EKS with kubernetes 1.19 (v1.19.13-eks-8df270) and containerd cri logs. 

We did not find any workaround for support of multiline  CRI logs.

**Comment by mikebarais** [comment]
We have hit the same issue with:
- EKS 1.19
- CRI
- amazon/aws-for-fluent-bit:2.19.1 (based on fluent-bit 1.8.6)
- amazon/aws-for-fluent-bit:2.20.0 (based on fluent-bit 1.8.7)

**Comment by stevehipwell** [comment]
@edsiper would you expect v1.8.8 to resolve this issue?

**Comment by debu99** [comment]
i have the same issue with 1.8.8

**Comment by aaabdallah** [comment]
> 
> 
> @PettitWesley (or anyone else) have you tested that this does actually fix the issue?
> 
> I've also opened [fluent/helm-charts#175](https://github.com/fluent/helm-charts/pull/175) to update the Helm chart to use this version.

My test rig where I was using td-agent-bit from the command line (without Kubernetes or Docker), and pushing large files through it while tailing... on 1.8.5 this would fail very fast, very consistently. As in within 2-3 rotations of large files.
On 1.8.9, I have yet to encounter the "invalid streamid" error after twenty rotations. That may seem like a little, but actually it was more than enough to see multiple failures before.

**Comment by Jonomir** [comment]
I have had 1.8.9 deployed for a few days now. Didn't occur again, would happen multiple times per day before. Looks like it's fixed. Thanks @nokute78

**Comment by PettitWesley** [comment]
Let's close this issue @nokute78 ? 🎉

**Comment by stevehipwell** [comment]
I can confirm that this is now working as expected.
