### ISSUE TITLE
[Feature] Support Splunk HEC Indexer Acknowledgment

### ISSUE THREAD

**Issue by qudongfang** [fluent/fluent-bit#3887]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when the logs are lost when something unusual happens.

It would be great if the [Splunk output ](https://docs.fluentbit.io/manual/pipeline/outputs/splunk)could support indexer acks as defined [here](https://docs.splunk.com/Documentation/Splunk/latest/Data/AboutHECIDXAck). We like to enable it by default in our Splunk environment.

**Describe the solution you'd like**

**Describe alternatives you've considered**

We have to go with `fluent-bit -> Splunk Universal Forwarder -> Splunk indexer(or HEC)` if ACK is a must.
Despite the extra effort required by the Splunk Universal Forwarder service, that's going to be an absolute nightmare to debug.

**Additional context**

I'm trying to forward logs from Kube to Splunk.
We cannot use the official Splunk forwarder because it doesn't support enriching the log entries coming from the container with Kube metadata/labels.

It appears that no logging agent that does the Kube log enrichment supports Splunk HEC Indexer Acknowledgment at the moment.

There is a feature request for this to the [fluent-plugin-splunk-hec](https://github.com/splunk/fluent-plugin-splunk-hec/issues/45) project

https://docs.fluentbit.io/manual/pipeline/outputs/splunk

**Comment by agup006** [comment]
This is a nice feature @qudongfang , is this something you are looking to contribute? Happy to look at a PR
