### ISSUE TITLE
Document what way to test/check regex format. Features available.

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#389]
Worth to mention what online tool to use to test/parse regex on parsers. 
Also, I bit miss a way to configure pcre flags (aka /gml).

For example, I have a problem with this one:
https://regex101.com/r/zGYU05/2

```(?<message>(?s)^(.*?)(?:(?:[\r*\n]+)))$``` This is the issue, but I failed to find an online tool to test or a better way to properly encode it.

Log from fluentbit:
```Oct 02 14:21:49 ctl01 td-agent-bit[2439]: [2017/10/02 14:21:49] [error] [parser:rabbitmq] Invalid regex pattern ^=(?<severity>[^ ].*)\s+REPORT[=\s]*(?<time>[^ =]*)\s*[=]*\n(?<message>(?s)^(.*?)(?:(?:[\r*\n]+)))$
Oct 02 14:21:49 ctl01 td-agent-bit[2439]: [2017/10/02 14:21:49] [ info] [engine] started
Oct 02 14:21:49 ctl01 td-agent-bit[2439]: [2017/10/02 14:21:49] [error] [in_tail] parser 'rabbitmq' is not registered
```

**Comment by edsiper** [comment]
it's documented here:

http://fluentbit.io/documentation/0.12/parser/regular_expression.html

at bottom it mentions Rubular site, but it's not easy to catch it

**Comment by epcim** [comment]
[**@edsiper**](https://github.com/edsiper) commented on [Oct 6, 2017, 6:51 PM GMT+2](https://github.com/fluent/fluent-bit/issues/389#issuecomment-334810377 "2017-10-06T16:51:31Z - Replied by Github Reply Comments"):
> it's documented here:
> 
> [http://fluentbit.io/documentation/0.12/parser/regular_expression.html](http://fluentbit.io/documentation/0.12/parser/regular_expression.html)
> 
> at bottom it mentions Rubular site, but it's not easy to catch it

Well I would say fluent-bit is pure C. The problem I have is here:
http://rubular.com/r/eX8UjwGLEI

(the example works in online-editor, but in reallity, the multiline message will never stop to read to first record)

**Comment by edsiper** [comment]
@epcim 

I've updated the documentation to avoid future confusions:

http://fluentbit.io/documentation/0.12/parser/regular_expression.html

Now as stated in the doc-update, if you are using Tail input plugin, you should use instead the Multiline feature instead of a multiline regex.

**Comment by epcim** [comment]
Oh, Well I had known the multiline option but as I failed it to use first time and understood documentation wrong I give up as I understood it's for another use-case.

I would suggest highlight the rubular or regex101.com on the parse page (move it top).

Also, can you explain whether there is a relation to the ruby if any? regarding the implementation, performance etc?

well, "multiline" `/m` is just one option, do you count to support other flags?
![image](https://user-images.githubusercontent.com/1211552/31347954-5dc4d8be-ad1e-11e7-976e-c50c766b5940.png)

**Comment by edsiper** [comment]
> I would suggest highlight the rubular or regex101.com on the parse page (move it top).

done: http://fluentbit.io/documentation/0.12/parser/

> Also, can you explain whether there is a relation to the ruby if any? regarding the implementation, performance etc?

Since Fluentd uses Ruby regular expressions, we want our users can use the same regex setup on Fluent Bit without pain.

> well, "multiline" /m is just one option, do you count to support other flags?

we support all of them listed here: https://ruby-doc.org/core-2.2.0/Regexp.html

**Comment by epcim** [comment]
Ok, thank you. Ticket can be closed.

For others, I am adding few complex examples below for multiline. Consider adding them to doc. 
Others can be found here: https://github.com/salt-formulas/salt-formula-fluentbit/tree/master/metadata/service/config

```

[INPUT]
    Name tail
    DB /tmp/rabbitmq.flb.db
    #Buffer_Chunk 1k
    Buffer_Chunk_Size 4k
    Buffer_Max_Size 64k
    Chunk_Size 4k
    Exclude_Path *.gz,*.xz
    Multiline On
    Multiline_Flush 5
    Parser_Firstline rabbitmq_f
    Parser_1 rabbitmq_1
    Path /var/log/rabbitmq/rabbit*
    Path_Key path
    Tag rabbitmq

[PARSER]
    Name rabbitmq_f
    Format regex
    Regex ^=(?<severity>[^ ]\w+)\s+REPORT[=\s]*(?<time>[^ =][-:.\d\w]+)[\s=]+$
    # 2-Oct-2017::10:20:14
    Time_Format %d-%b-%Y::%H:%M:%S
    Time_Keep On
    Time_Key time
    Types serverity:string

[PARSER]
    Name rabbitmq_1
    Format regex
    Regex ^(?<message>.*?(?=\R\R|\z))$
    Types message:string
```

and

```
[INPUT]
    Name tail
    DB /tmp/postgresql.flb.db
    Buffer_Max_Size 64k
    Chunk_Size 32k
    Exclude_Path *.gz,*.xz,*.bz2
    Parser_Firstline postgresql_statement_s
    Parser_1 postgresql_statement_e
    Parser_2 postgresql_statement_d
    Multiline On
    Multiline_Flush 4
    Path /var/lib/pgsql/data/pg_log/postgresql*
    Path_Key path
    Tag postgresql.statements

# not worked
[PARSER]
    Name postgresql_statements
    Format regex
    Regex ^STATEMENT:\s*(?<statement>[^$].*?)[\s\n\r]+ERROR:\s*(?<error>[^$].*?)[\s\n\r]+DETAIL:\s*(?<detail>[^$].*?)$
    Time_Keep On

[PARSER]
    Name postgresql_statement_s
    Format regex
    Regex ^STATEMENT:\s*(?<statement>[^$].*?)$
    Time_Keep On

[PARSER]
    Name postgresql_statement_e
    Format regex
    Regex ^ERROR:\s*(?<error>[^$].*?)$
    #Time_Keep On

[PARSER]
    Name postgresql_statement_d
    Format regex
    Regex ^DETAIL:\s*(?<detail>[^$].*?)$
    #Time_Keep On
```

**Comment by edsiper** [comment]
thanks, I will make sure to extend multiline docs.
