### ISSUE TITLE
DNS queries force TCP instead of trying UDP first

### ISSUE THREAD

**Issue by treythomas123** [fluent/fluent-bit#3890]
## Bug Report

**Describe the bug**
Fluent Bit forces DNS queries to use TCP, rather than the typical behavior of trying UDP first and only falling back to TCP when a truncated response is received. We have an environment where UDP traffic is allowed on port 53, but TCP on this port is blocked by a firewall. Lots of other DNS-reliant services run successfully in this environment, because the DNS queries complete successfully over UDP, but Fluent Bit fails to resolve hostnames because the TCP DNS query is blocked.

**To Reproduce**
Block TCP traffic to the DNS server, and configure Fluent Bit to try to connect to a hostname served by DNS.
- Example log message if applicable:
```
[2021/07/29 16:38:08] [ warn] [net] getaddrinfo(host='loki.example.com'): Unknown error
[2021/07/29 16:38:08] [error] [output:loki:loki.1] no upstream connections available
```

**Expected behavior**
DNS query uses UDP and completes successfully.

**Your Environment**
* Version used: 1.7.9 (issue also occurs with 1.8.2)
* Configuration: Loki output configured with a DNS name (also happens with other plugins configured to use DNS names)

**Additional context**
Unblocking DNS over TCP in this environment is a possible fix, but we would like to understand why that is necessary for Fluent Bit but not for other applications.

The firewall blocking issue notwithstanding, UDP is also generally preferred over TCP for DNS queries due to performance/overhead, so we'd prefer to see UDP attempted first for that reason as well.

We tried with version 1.7.8, and the issue doesn't occur there. This behavior seems to have changed with the following PR (and was cherry picked into 1.7.9):
https://github.com/fluent/fluent-bit/pull/3664

The PR and code comments don't really explain why the change was made. If this is required to fix some issue, an explanation would be appreciated.

**Comment by ahaid** [comment]
+1 for this bug

**Comment by gca3020** [comment]
Another +1 Here. I see a config file option has been added to master, but it looks like that isn't in the 1.8 branch. Any ETA on when we might see that in a stable release?

**Comment by edsiper** [comment]
In latest version now is UDP first
