### ISSUE TITLE
RemoveContainer failure caused by container log file access is denied 

### ISSUE THREAD

**Issue by lizhuqi** [fluent/fluent-bit#3892]
## Bug Report

**Describe the bug**
See the error message:
RemoveContainer "[ID]" from runtime service failed: rpc error: code = Unknown desc = failed to remove container "[ID]": Error response from daemon: unable to remove filesystem for [ID]: CreateFile C:\ProgramData\docker\containers[ID][ID]-json.log.4: Access is denied.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:
1. Start a cluster with Windows node pool
2. kubectl apply -f https://gist.githubusercontent.com/lizhuqi/e350d322c0c2b7ef1a9fcae42eb96961/raw/857a52a56b16a02732d966a5ed3421c0a4c897c3/log-test.yaml
3. wait several seconds and you will see some error like "RemoveContainer "[ID]" from runtime service failed: rpc error: code = Unknown desc = failed to remove container "[ID]": Error response from daemon: unable to remove filesystem for [ID]: CreateFile C:\ProgramData\docker\containers[ID][ID]-json.log.4: Access is denied." in the kubelet log. 

If we stop fluent-bit, this error will stop accumulating in kubelet log.

**Expected behavior**
No "Access is denied" error happens during remove container.

**Screenshots**

**Your Environment**

* Version used: fluent-bit v1.7.7
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): GKE 1.21
* Server type and version: 
* Operating System and version: Windows 2019
* Filters and plugins:

**Additional context**

We used the yaml file to repro the access is denied error when we investigate the pod stuck in termination issue. The [fix](https://github.com/fluent/fluent-bit/issues/2027) for the pod stuck in termination issue is available in fluentbit v1.5 however, we still see the access is denied error in v1.7.7 so it seems that some edge case like the repro here still can trigger the error.

**Comment by djsly** [comment]
we are seeing this also from time to time, currently we are running version: fluentbit_image_tag = "1.6.10"

**Comment by djsly** [comment]
still present

**Comment by ssinha3** [comment]
Was there a workaround for this, we still hit this issue on fluent-bit:1.9.5
