### ISSUE TITLE
Windows edition AWS instance profile/IAM role support

### ISSUE THREAD

**Issue by jianglei-els** [fluent/fluent-bit#3893]
**Is your feature request related to a problem? Please describe.**
Current Windows version fluent bit can't pick aws credential from attached IAM role.  

**Describe the solution you'd like**
Please add this, as current it only fetch aws credential from HOME path .aws folder

**Comment by fujimotos** [comment]
> Current Windows version fluent bit can't pick aws credential from attached IAM role.

@jianglei-els I first heard this. Can you point me to a relevant spec/documentation?

**Comment by jianglei-els** [comment]
I don't find it's not support in spec and document, and I don't find document that it's supported on Windows. 

I tested on Windows and Linux, where Linux works, but Windows doesn't.

**Comment by fujimotos** [comment]
@jianglei-els Can you provide full steps to reproduce your issue?

I suppose that you're trying to use one of the following credential providers,
which happens to be not working on your case. I'm not sure which one is the
problematic one, so it will help if you can provide full reprdocution steps.

```
 * 1. Environment variables
 * 2. Shared credentials file (AWS Profile)
 * 3. EKS OIDC
 * 4. EC2 IMDS
 * 5. ECS HTTP credentials endpoint
```

**Comment by jianglei-els** [comment]
Hi, @fujimotos 

Thanks for replying. I'm using '4. EC2 IMDS', no existing AWS profile or Environment variables setup on EC2(Windows 2019 Server ), output is 'Kinesis Data Stream'.  Example fluent-bit.conf
[INPUT]
    name winlog
    channels System,Security
    Interval_Sec 1
    DB           winlog.sqlite

[OUTPUT]
    Name  kinesis_streams
    Match *
    region cn-northest-1
    endpoint kinesis.cn-northwest-1.amazonaws.com.cn
    stream stream1
    time_key timestamp

Thanks.
