### ISSUE TITLE
Add in_forward plugin

### ISSUE THREAD

**Issue by salekseev** [fluent/fluent-bit#39]
Please. So it can be used as a lightweight agent to collect from docker containers for example.

**Comment by edsiper** [comment]
Good idea, it will be added. Not sure if there is room for 0.7 release, most likely 0.8.

**Comment by edsiper** [comment]
@salekseev the plugin will be implemented, I just want to get some info:

1. are you using Fluent Bit currently in some environment ?
2. are you facing some performance problem using Fluentd with Docker ?

**Comment by nokute78** [comment]
Already implemented, so it's hard to say...
Would you rename in_forward in_fluentd?

I think it is symmetrical that fluentbit has in/out_fluentd( or in/out_forward).

**Comment by edsiper** [comment]
yeah, out_fluentd will be out_forward

**Comment by edsiper** [comment]
Pieces are in place, to make in_forward work properly it's only required to adjust the routing mechanism for dynamic tags. 

Closing this issue as the plugin is in place.
