### ISSUE TITLE
Fluent-bit container crashes with exit code 136 on k8s logging to AWS ES 

### ISSUE THREAD

**Issue by 97turbotalon** [fluent/fluent-bit#3905]
## Bug Report

I'm new to fluent-bit and using the the provided example yaml files with k8s 1.19.12 and AWS ES 7.9.  No customization to the provided yaml files except configured ES endpoint.
Containers will start properly with logs flowing to ES.
After approximately 60-120s, all fluent-bit containers will go into a crashloop with an error stating exit code 136.
Configured fluent-bit system to debug log, no additional information about the crash.

v1.8.3 - Container crash
v1.8.2 - Container crash
v1.8.1 - Works properly
v1.7.9 - Works properly

**Comment by stephanlindauer** [comment]
We are seeing the exact same issue. Additional observations we have made:
- It seems to only manifest on certain nodes. Other nodes don't seem to have an issue. (-> race condition?)
- We are seeing that the kubelet logs the following line when this happens:
```Aug  3 21:37:09 ip-XXX-XXX-XXX-XXX kubelet[10587]: I0803 21:37:09.886901   10587 kuberuntime_manager.go:425] No sandbox for pod "fluent-bit-fmfxr_logging(f60ef10c-21f7-4d5b-90df-7265f4859f1c)" can be found. Need to start a new one```

**Comment by nokute78** [comment]
Sorry.
My patch #3788 may cause this crash...
I sent a patch #3931 to fix this issue.

#3788 can divide by 0, it causes SIGFPE and fluent-bit exits code 136.
