### ISSUE TITLE
Minor, Parser not found if multi-line is used

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#391]
setup:
When tail input plugin with Multiline On, so an entry `Parser_Firstline xyz` is in the conf 

issue:
if the parser conf file also contain `Parser myparser123` option (not expected to be used, ignored) in case the `myparser123` is not found it throws an error.

(I am 80% sure I saw the issue, but count I may be also wrong)

**Comment by edsiper** [comment]
A parser not found will always throws an error, it's an invalid setup (despite is multiline mode or not), on that way we encourage right setup.

As an additional check, I have added a warn message if Multiline mode is On and a Parser exists (just to clarify and avoid confusion from an user perspective).

Closing this as not an issue.
