### ISSUE TITLE
flb disk buffering not working as expected with stackdriver

### ISSUE THREAD

**Issue by bharatnc** [fluent/fluent-bit#3911]
## Bug Report

**Describe the bug**

Fluentbit is not buffering the data when stackdriver is available. Instead it's actually dropping it.

**To Reproduce**

- Use the following `fluentbit` config file:

```bash
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file /etc/flb/parsers.conf
    plugins_file /etc/flb/plugins.conf
    http_server  On
    http_listen  0.0.0.0
    http_port    3281
    storage.metrics On
    storage.path /fluentbit-buffer
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit  8M
    storage.max_chunks_up  128

[INPUT]
    Name  tail
    Alias  test_tail
    Path  /var/log/test.log
    Read_from_Head  Off
    Path_Key  filename
    Tag  syslog
    Key  event
    exit_on_eof  false
    Rotate_Wait  5
    Refresh_Interval  60
    Skip_Long_Lines  Off
    DB.sync  normal
    DB.locking  false
    Buffer_Chunk_Size  32k
    Buffer_Max_Size  8M
    Multiline  Off
    Multiline_Flush  4
    Parser_Firstline  8192
    Docker_Mode  Off
    Docker_Mode_Flush  4

[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}

[OUTPUT]
    name stackdriver
    match *
    resource global
    google_service_credentials /etc/flb/fluentbit-google-service-credentials.json
    tls On
    tls.verify On
    IPv6 On
    storage.total_limit_size  128M
    Retry_Limit  False
```

- Simulated temporary unavailability of stackdriver by restricting the permissions to the service account requires to write to stackdriver while Fluentbit was running.

**Expected behavior**

I would expect the data to be buffered in `/fluentbit-buffer`. But instead I'm not seeing anything store under `/fluentbit-buffer` and my prometheus metrics showns that the data is being dropped steadily.
Please note that I've used `Retry_Limit False` - so ideally it should retry until it succeeds.

**Your Environment**

* Version used: `1.7.9`
* Configuration: `fluentbit.conf file as shown above with default parsers and plugins conf files that ships with Fluentbit.`
* Environment name and version (e.g. Kubernetes? What version?): `systemd on server`
* Server type and version: `Intel x86_64`
* Operating System and version: `debian buster`
* Filters and plugins: As shown in the config above : `file input, hostname filter and stackdriver output`

**Comment by JeffLuoo** [comment]
Prob you are missing the `storage.type filesystem` in your configuration?

```
[SERVICE]
    flush                     1
    log_Level                 info
    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    name          cpu
    storage.type  filesystem

[INPUT]
    name          mem
    storage.type  memory
```

**Comment by bharatnc** [comment]
@JeffLuoo thank you. I added `storage.total_limit_size`. I can see a file get's written intermittently but doesn't seem to be 
persistent and disappears and a new file is written and again disappears and so on. The file written looks like the following:

```
-rw------- 1 root      root      4.0K Aug  5 02:24 1351604-1628130244.963198517.flb
``
```

Wouldn't this file grow in size after in memory limit is reached until the retry is successful or is my assumption wrong ?

**Comment by JeffLuoo** [comment]
If filesystem buffer is enabled, the disappear of the chunk means that the logs stored in the chunk are already flushed out to the destination. Please read https://docs.fluentbit.io/manual/administration/buffering-and-storage for more information.
