### ISSUE TITLE
1.8.3 chunk validation failures

### ISSUE THREAD

**Issue by apollo13** [fluent/fluent-bit#3915]
## Bug Report

**Describe the bug**
I am seeing chunk validation errors on 1.8.3. I can mail the chunk in question. The log file contains:
```
[2021/08/05 09:50:03] [error] [input:storage_backlog:storage_backlog.5] chunk validation failed, data might be corrupted. No valid records found, the chunk will be discarded.
[2021/08/05 09:50:03] [error] [input:storage_backlog:storage_backlog.5] removing chunk tail.1:837-1628114443.364245184.flb from the queue
[2021/08/05 09:50:03] [ info] [input:storage_backlog:storage_backlog.5] queueing tail.1:837-1628116102.165605216.flb
```

I decoded the chunk as far as I could, this is what I get:
```
\xc1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\raudit.ro-gate

\x92
Array Size 2

\xd7\x00a\x0b\r\xe03\xdb%\x80
ExtType(code=0, data=b'a\x0b\r\xe03\xdb%\x80')

\x84
fixmap 4

\x92
Array Size 2

\xd7\x00a\x0b\r\xe04\x08\xec@
ExtType(code=0, data=b'a\x0b\r\xe04\x08\xec@')

\x85\xa4txId\xadibudc5tb-3m3a\xa8clientIp\xaf192.168.220.130\xaftxExecutionTime\xa5189ms\xa7message\xd9'SYSTEM authenticated successfully 'cm'.\xa6source\xbeXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
{'txId': 'ibudc5tb-3m3a',
 'clientIp': '192.168.220.130',
 'txExecutionTime': '189ms',
 'message': "SYSTEM authenticated successfully 'cm'.",
 'source': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}

\x92
Array Size 2

\xd7\x00a\x0b\r\xe05\x0cR\x80
ExtType(code=0, data=b'a\x0b\r\xe05\x0cR\x80')

\x85\xa4txId\xads66fpbot-n997\xa8clientIp\xaf192.168.220.130\xaftxExecutionTime\xa5187ms\xa7message\xd9'SYSTEM authenticated successfully 'cm'.\xa6source\xbeXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
{'txId': 's66fpbot-n997',
 'clientIp': '192.168.220.130',
 'txExecutionTime': '187ms',
 'message': "SYSTEM authenticated successfully 'cm'.",
 'source': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}

\x92
Array Size 2

\xd7\x00a\x0b\r\xff\x13\xd9-@
ExtType(code=0, data=b'a\x0b\r\xff\x13\xd9-@')

\x84
fixmap 4

\x92
Array Size 2

\xd7\x00a\x0b\r\xff\x14\x166@
ExtType(code=0, data=b'a\x0b\r\xff\x14\x166@')

\x85\xa4txId\xad8051zp1d-wh7j\xa8clientIp\xaf192.168.220.130\xaftxExecutionTime\xa5224ms\xa7message\xd9'SYSTEM authenticated successfully 'cm'.\xa6source\xbeXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
{'txId': '8051zp1d-wh7j',
 'clientIp': '192.168.220.130',
 'txExecutionTime': '224ms',
 'message': "SYSTEM authenticated successfully 'cm'.",
 'source': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}


\x92
Array Size 2

\xd7\x00a\x0b\r\xff\x15(\xde\xc0
ExtType(code=0, data=b'a\x0b\r\xff\x15(\xde\xc0')

\x84
fixmap 4
```
What is weird is that the data in the chunk is mostly fine, but it seems the beginning got overwritten with zeroes?

- Steps to reproduce the problem: No idea :)

**Comment by ramilmsh** [comment]
@apollo13 are you using filesystem storage?

**Comment by apollo13** [comment]
@ramilmsh Yes, this is the storage configuration:
```
[SERVICE]
    Daemon Off
    Parsers_File parsers.conf
    # Plugins_File plugins.conf
    Log_File /var/log/td-agent-bit.log
    Log_Level info
    Grace 5

    storage.path /var/lib/flb-storage/
    storage.sync normal
    storage.metrics on

    HTTP_Server  On
    HTTP_Listen  127.0.0.1
    HTTP_PORT    2020

[INPUT]
    Name tail
    Path /var/opt/ra/log/ra-gate-audit-general.log
    DB /var/lib/flb-storage/audit.ra-gate.log.db
    Tag audit.ra-gate
    Key message
    Multiline On
    Parser_Firstline audit-firstline
    storage.type filesystem
    mem_buf_limit 5M
```

I am currently locally trying to recreate such a broken chunk, but not much luck. It also is weird that fluentbit would write empty (?) fix maps with size 4.

**Comment by apollo13** [comment]
I actually just noted that every chunkfile has this header:
```
0000000 301  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
0000020  \0  \0  \0  \0  \0  \0  \0  \r   a   u   d   i   t   .   r   o
```
so this might be okay?! So the issue might be the empty map of size 4?

**Comment by apollo13** [comment]
I have written a python parser for the chunks files, by making some assumptions on the structure to be able to pinpoint errors. So far my parser found the following:
 * All chunk files have the proper structure of "chunk_header, metadata, 1 or more msgpack arrays"
 * Every array in there consists of two elements, the first being an extension with code 0 (timestamp) and a map containing the message.

Now it does get interesting:
 * If the message is written properly it has a map header with a count of **N** followed by **N*2** items. This is expected reading the msgpack spec
 * If the message errors out it has a map header with a count of **N-1** (!) followed by **0** items. This in turn makes the chunk validator unhappy and results in throwing away the whole chunk.

I am a little bit surprised why the failing messages think they would have **N-1** items, this seems to be something systematic. The one thing that is common through all those messages is that I have a filter attached ala:
```
[FILTER]
    Name record_modifier
    Match *
    Record source ${HOSTNAME}
```
which should set the hostname for all of them, could this fail sometimes? I have no idea why the message might get shorter sometimes otherwise…

@edsiper Any more information I could provide?

**Comment by ramilmsh** [comment]
@apollo13 Based on you config i can recommend trying `storage.sync full`.

I was using 
```conf
[SERVICE]
    storage.sync normal
    storage.checksum on
[INPUT]
    storage.type filesystem
```

and I got CRC32 errors (checksums were failing, e.g. chunks) all the time, until i switched to `storage.sync full`, which fixed the issue

**Comment by apollo13** [comment]
Are there any docs on the difference between the two storage sync methods? All in all (given the otherwise valid data of the chunk file) it seems weird that this would simply be a sync error 🤔

**Comment by ramilmsh** [comment]
@apollo13 it does indeed. I asked the question in slack, but got no response on this particular issue (they do a good job answer, mostly. maybe you can ask there).

I could be wrong, but I did consistently get errors with `storage.sync normal` and get none with `storage.sync full`. Though I do realize it's a bit weird.

If I were you, I would add `storage.checksum on` and change log level to either debug of trace and see if you get checksum failures. Maybe it'll point you in the right directon
