### ISSUE TITLE
ElasticSearch output: dead letter index

### ISSUE THREAD

**Issue by vrivellino** [fluent/fluent-bit#3924]
**Is your feature request related to a problem? Please describe.**

Unfortunately, our log data is pretty heterogeneous and we occasionally run into field mapping conflicts in Elasticsearch. Eg: The index has a field typed as an integer, but some log messages have the same field name as string. This causes ES to return a 400 - with I believe a mapper parser exception - and log messages are lost.

**Describe the solution you'd like**

Add a configuration option to the Elasticsearch output plugin to write these log messages to a different index. Records in this index could contain a json dump of an offending log message, the index the message was supposed to go into, and the response body from the original Elasticsearch push

**Describe alternatives you've considered**

Writing a custom service that sits in between fluent-bit and Elasticsearch

**Additional context**

N/A

**Comment by VSilantyev** [comment]
@vrivellino Did you solve this problem? We are stuck with the same problem.
