### ISSUE TITLE
Fluency buffer error with Fluent Bit 1.8.3 upgrade

### ISSUE THREAD

**Issue by erancx** [fluent/fluent-bit#3928]
## Bug Report

**Describe the bug**
After upgrading to 1.8.3 we encounter errors like:
`[Log4j2-TF-16-AsyncLoggerConfig-13 []] ERROR org.komamitsu.fluency.Fluency - emit() failed due to buffer full. Flushing buffer. Please try again...`. 
We're working with GCS storage.

**To Reproduce**
service.conf
```
[INPUT]
    Name        forward
    Listen      127.0.0.1
    Port        24224
    Buffer_Chunk_Size  32KB
    Buffer_Max_Size  128MB
    storage.type  filesystem

[INPUT]
    Name        forward
    Listen      127.0.0.1
    Port        24225
    Buffer_Chunk_Size  32KB
    Buffer_Max_Size  128MB
    storage.type  filesystem

[OUTPUT]
    Name          forward
    Match_Regex   ^.+(?<!\.stackdriver)$
    Upstream      /etc/waze/fluent-bit/${REGION}/upstream.conf

[OUTPUT]
    Name          stackdriver
    Match_Regex   ^.+?\.stackdriver$
    resource      gce_instance
    labels_key    labels
    severity_key  severity
```

```
[Log4j2-TF-16-AsyncLoggerConfig-13 []] ERROR org.komamitsu.fluency.Fluency - emit() failed due to buffer full. Flushing buffer. Please try again...`
```
- Steps to reproduce the problem:
Install td-bit version 1.8.3 and use the config above.

**Expected behavior**
No buffer full errors.

**Your Environment**

* Version used: 1.8.3
* Configuration: Included above
* Environment name and version: VM
* Operating System and version: Ubuntu 20.04

**Comment by nokute78** [comment]
`[Log4j2-TF-16-AsyncLoggerConfig-13 []] ERROR org.komamitsu.fluency.Fluency - emit() failed due to buffer full. Flushing buffer. Please try again...` 

The log is not about Fluent-bit. 
It is a log of Fluency.
https://github.com/komamitsu/fluency/blob/0aae92a7d03dbe1c2f2a27374f59a5dfea7b528b/fluency-core/src/main/java/org/komamitsu/fluency/Fluency.java#L200

- How do you use Fluent-bit and Fluency ?
  -  e.g. system.log -> Fluent-bit -> Java app which uses Fluency 
- What is an output plugin ? There is no [OUTPUT] description in service.conf.

**Comment by erancx** [comment]
sorry, updated the thread with the right service config including OUTPUT.

the way we use it is application log -> fluent-bit -> java app with fluency -> fluentd forwarders -> Google Cloud Logging (Stackdriver)/BigQuery

**Comment by nokute78** [comment]
Thank you for updating.

https://github.com/fluent/fluent-bit/compare/v1.8.2...v1.8.3
Hmm. No commits seems to relate to the issue...

https://github.com/fluent/fluent-bit/commit/8f613f1399caab4af2ee0ea51865450738f9842d
It is an only commit for output plugin. 
However it may not cause this issue.

**Comment by erancx** [comment]
any suggestion on how to debug this? what additional information should I gather up?

**Comment by agup006** [comment]
@erancx We really need a solid repro in a local environment with fluent bit isolated - there are quite a few services interacting in your use case and it is hard to know which one is failing or causing issue: Fluency / Google / Fluentd?

I noted that 1.8.2 downgrade worked so perhaps you can start there with looking what a message looks like with 1.8.2 std output and if there are any differences in 1.8.3 std output. Additionally, if there are none perhaps you can inspect the wire traffic between Fluent Bit and the output to see if the output plugin formatting might be a culprit.
