### ISSUE TITLE
1.8.3 is not installable via apt on Raspbian buster on ARM x32

### ISSUE THREAD

**Issue by elcreator** [fluent/fluent-bit#3933]
## Bug Report

**Describe the bug**

**To Reproduce**
- Example log message if applicable:
```
pi@raspberrypi:~ $ sudo apt-get install td-agent-bit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 td-agent-bit : Depends: libpq5 (>= 9.0~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
- Steps to reproduce the problem:
curl https://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
echo deb https://packages.fluentbit.io/raspbian/buster buster main | sudo tee /etc/apt/sources.list
sudo apt-get update
sudo apt-get install td-agent-bit

**Expected behavior**

Installation successful

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Server type and version: Raspberry Pi 4B
* Operating System and version: ```Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux```
* Filters and plugins:

**Additional context**

Build from sources is successful, everything works as expected

**Comment by agup006** [comment]
Hey @elcreator thanks for filing, this looks like a sub package is not installing - are you able to install the libpq package and try again? perhaps an update prior to installing?

**Comment by elcreator** [comment]
I'm not able to install it.

pi@raspberrypi:~ $ sudo apt-get update
Get:1 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Hit:2 https://packages.sury.org/php buster InRelease                           
Get:3 https://packages.fluentbit.io/raspbian/buster buster InRelease [9,025 B] 
Get:4 http://archive.raspberrypi.org/debian buster/main armhf Packages [378 kB]
Fetched 419 kB in 3s (131 kB/s)   
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get install libpq5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libpq5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpq5' has no installation candidate

**Comment by agup006** [comment]
Perhaps you could compile from source? Since libpq is not being found in the CMAKE you should be able to disable the postgres output plugin to remove that dependency

**Comment by elcreator** [comment]
yes as I mentioned

> Build from sources is successful, everything works as expected

**Comment by elcreator** [comment]
but it was compiled successfully without disabling this plugin
