### ISSUE TITLE
Is FLB_TESTS_RUNTIME unnecessary?

### ISSUE THREAD

**Issue by takahasi** [fluent/fluent-bit#394]
FLB_TESTS_RUNTIME is disabled since July. 
Now cannot compile it.
I think the runtime tests are useful for the regression tests of plugins.
So I will make that PR if necessary.

How you do you feel about it?

**Comment by edsiper** [comment]
@takahasi 

Yes, they are useful, I think the required change is:

- port runtime tests from *.cpp to *.c and use [acutest](https://github.com/mity/acutest) unit test lib

**Comment by edsiper** [comment]
I did a few changes to make easier to port runtime tests:

- acutest now is exposed in tests/lib/acutest
- check the following header helper that tests use: https://github.com/fluent/fluent-bit/blob/master/tests/internal/flb_tests_internal.h.in
- helper is generated here: https://github.com/fluent/fluent-bit/blob/master/tests/internal/CMakeLists.txt#L30

**Comment by takahasi** [comment]
Thanks! I will try.

**Comment by takahasi** [comment]
I have one more question.
How about the data directory of internal and rutime?
Separate or same?

**Comment by edsiper** [comment]
I think runtime should have it own data directory ordered in paths according to the plugin being tested., e.g:

```
runtime/data/in_tail/
runtime/data/in_syslog/
```

**Comment by takahasi** [comment]
I agree. Thanks.

**Comment by edsiper** [comment]
closing due to #395
