### ISSUE TITLE
Forward input plugin does not work

### ISSUE THREAD

**Issue by tjjkj** [fluent/fluent-bit#3958]
I'm running Fluentbit as a docker container with input plugin as "Forward" but when I send any data to the TCP port, I dont see them collected. Not sure what I'm missing here.

To test the Forward input plugin, I have a .net code from the link [TcpClient demo](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient?view=net-5.0) to post to the port 24224 but nothing is collected by fluentbit .

**Docker command:**
`docker run --rm  -p 24224:24224/tcp -ti fluent/fluent-bit:1.8 /fluent-bit/bin/fluent-bit -i forward -p listen=127.0.0.1 -p port=24224 -o stdout -f 10
Fluent Bit v1.8.1
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/08/16 13:40:50] [ info] [engine] started (pid=1)
[2021/08/16 13:40:50] [ info] [storage] version=1.1.1, initializing...
[2021/08/16 13:40:50] [ info] [storage] in-memory
[2021/08/16 13:40:50] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/08/16 13:40:50] [ info] [cmetrics] version=0.1.1
[2021/08/16 13:40:50] [ info] [input:forward:forward.0] listening on 127.0.0.1:24224
[2021/08/16 13:40:50] [ info] [sp] stream processor started`

**Environment**:
Version used: 1.8.1
Configuration: refer above
Server type and version: Windows 10
Operating System and version: Windows 10 Enterprise
Filters and plugins: Forward input plugin

**Comment by nokute78** [comment]
What is the data you sent ?
We need to sent a data which meets below spec.
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1

We also support tcp input plugin.
`The tcp input plugin allows to retrieve structured JSON or raw messages over a TCP network interface (TCP port).`
https://docs.fluentbit.io/manual/pipeline/inputs/tcp
