### ISSUE TITLE
in_tail: slow DB option with SQLite

### ISSUE THREAD

**Issue by nikitka** [fluent/fluent-bit#396]
Hi!

I'm using fluent-bit to parse nginx log files and forward log messages to fluentd instance. Sometimes I would like to restart the fluent-bit instance, but there is not a way to start reading from the tail except of using the DB option to keep last file position state. Unfortunately I can't use the DB option because writing to sqlite db affecting my disk io performance, but start reading from the tail of file with data loss between stop-start will solve my problem. Could you please provide this option?

**Comment by edsiper** [comment]
@nikitka 

would you please elaborate more about the performance problem with SQLite ?, also provide the following information:

1. output of: fluent-bit -c yourconffile.conf --sosreport
2. how many files are you tailing at the same time (in average) ?
3. how many new log lines are generated per second in your nginx logs ?

**Comment by nikitka** [comment]
> would you please elaborate more about the performance problem with SQLite ?

I'm using bare-metal server with 2 SATA drives in RAID 1. I don't have too much load, normally ~1% disk utilization. 

Typical `iostat -xk 30` is
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.12    0.00    0.04    0.08    0.00   99.77

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.77    0.00    1.20     0.00     9.87    16.44     0.03   22.44    0.00   22.44   8.89   1.07
```

When I enable DB option I get ~ 30% disk usage. 

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.10    0.00    0.06    2.03    0.00   97.81

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00    35.77    0.00   29.13     0.00   298.00    20.46     0.35   12.11    0.00   12.11  11.52  33.57
```

I'm trying to analyze system calls via strace, I ran `timeout 10 strace -ttf -e trace=file,desc -p 11242 -o ~/tmp/fluetbit.strace `

Output (I masked ip addresses): https://gist.github.com/nikitka/36ae32b77d28e40b8171d15f2fff7ac1

`lsof -p 11242` output here (I masked sensitive names): https://gist.github.com/nikitka/84f22262c76fc2442f8350a72fe0511c

In strace output I see too many open/close journal and write requests to SQLite database file. 

>, also provide the following information:
> output of: fluent-bit -c yourconffile.conf --sosreport

```
[Fluent Bit]
    Edition             Community Edition
    Version             0.12.6
    Built Flags          JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_SQLDB FLB_HAVE_BUFFERING FLB_HAVE_FLUSH_LIBCO FLB_HAVE_SYSTEMD FLB_HAVE_FORK FLB_IS_TD_AGENT FLB_HAVE_PROXY_GO FLB_HAVE_JEMALLOC JEMALLOC_MANGLE FLB_HAVE_REGEX FLB_HAVE_C_TLS FLB_HAVE_SETJMP FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

[Operating System]
    Name                Linux
    Release             3.16.0-4-amd64
    Version             #1 SMP Debian 3.16.39-1 (2016-12-30)

[Hardware]
    Architecture        x86_64
    Processors          8

[Built Plugins]
    Inputs              cpu mem kmsg tail proc disk systemd netif dummy head health serial stdin tcp mqtt lib forward random syslog 
    Filters             grep stdout kubernetes parser record_modifier 
    Outputs             counter es exit file forward http influxdb kafka-rest nats null plot stdout retry td lib flowcounter 

[SERVER] Runtime configuration
    Flush               5
    Daemon              Off
    Log_Level           Info

[INPUT] Instance
    Name                tail.0 (tail, id=0)
    Flags               DYN_TAG 
    Threaded            No
    Tag                 land.XXXX.index
    Path                /var/log/nginx/XXXX.access.tsv.log
    DB                  /var/lib/fluent-bit/landings_files.sqlite

[FILTER] Instance
    Name                parser.0 (parser, id=0)
    Match               land.*
    Key_Name            log
    Parser              landing_generic

[OUTPUT] Instance
    Name                forward.0 (forward, mask_id=1)
    Match               land.*
    TLS Active          No
    Retry Limit         1
    Host.TCP_Port       24225
    Host.Name           YY.YY.2.5
    Time_as_Integer     True
```

> how many files are you tailing at the same time (in average) ?

Only one file

> how many new log lines are generated per second in your nginx logs 

This is a small file. ~3 rps, (~270k records per day / 86400 seconds)


As workaround I point DB path to tmpfs and all works great, but if I'll reboot machine I'll get my logs records for current day twice.

**Comment by edsiper** [comment]
I did a _quick_ research and found that using default settings (as we are doing) can hit a high I/O to disk.

In the meanwhile I learn more about scaling up sqlite performance I'd suggest you try the following workaround to decrease system calls usage:

Set the option Buffer_Chunk_Size  to 256k, e.g:

```
[INPUT]
    Name tail
    Buffer_Chunk_Size 256k
    ...
```

that option will make Fluent Bit use a higher buffer size which will lead to fewer sqlite offset updates. Please test that and let me know if it improves...

**Comment by nikitka** [comment]
Unfortunately, increasing `Buffer_Chunk_Size` and `Buffer_Max_Size` options does not improve performance.

**Comment by edsiper** [comment]
@nikitka 

I did some local tests, but only on a SSD disk:

when the database option is used, Fluent Bit in_tail plugin requires to save the current offset of that file, sqlite3 does an explicit I/O sync, which is safer.

If Fluent Bit have too much data to process one option is to try to reduce the number of offset writes to the database, the workaround is to play with buffers, in my experiment I could reduce I/O significantly by setting:

```
buffer_chunk_size 1M
buffer_max_size 1M
```

that means that in_tail will try to read 1M of data each time, so will only update the offset to the database every 1M, the default is 32k so now that means that you are doing 32 writes less to the disk.

Other solution might be to expose a flag into in_tail to let sqlite3 sync to disk not on every write but at certain intervals of time, it will be faster but that is not 100% safe as if your system goes down before flushing to disk you will lose that offset and keep only the previous one.

**Comment by edsiper** [comment]
@nikitka did you try the setup suggested above ?

**Comment by nikitka** [comment]
Sorry for late answer, I tried today. Unfortunately, this is not solve my problem. I think my problem is that I have small RPS and the `flb_tail_file_chunk` function read a few hundred bytes and save sqlite database.  Typical my verbose log is like that:

```
[2017/11/08 12:34:30] [debug] [dyntag tail.0] 0x7f343b27b0c0 destroy (tag=tail.0)
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:30] [debug] [input tail.0] [mem buf] size = 695
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log read=677 lines=1
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:30] [debug] [input tail.0] [mem buf] size = 1137
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log read=424 lines=1
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:30] [debug] [input tail.0] [mem buf] size = 1859
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log read=704 lines=1
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:30] [debug] [input tail.0] [mem buf] size = 2339
[2017/11/08 12:34:30] [debug] [in_tail] file=access.tsv.log read=462 lines=1
[2017/11/08 12:34:31] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:31] [debug] [input tail.0] [mem buf] size = 2811
[2017/11/08 12:34:31] [debug] [in_tail] file=access.tsv.log read=454 lines=1
[2017/11/08 12:34:32] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:32] [debug] [input tail.0] [mem buf] size = 3240
[2017/11/08 12:34:32] [debug] [in_tail] file=access.tsv.log read=411 lines=1
[2017/11/08 12:34:32] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:32] [debug] [input tail.0] [mem buf] size = 3686
[2017/11/08 12:34:32] [debug] [in_tail] file=access.tsv.log read=428 lines=1
[2017/11/08 12:34:32] [debug] [in_tail] file=access.tsv.log event
[2017/11/08 12:34:32] [debug] [input tail.0] [mem buf] size = 4066
[2017/11/08 12:34:32] [debug] [in_tail] file=access.tsv.log read=362 lines=1
[2017/11/08 12:34:34] [debug] [task->buffer] worker_id=0
[2017/11/08 12:34:34] [debug] [task] created task=0x7f343b3ee0e0 id=0 OK
[2017/11/08 12:34:34] [debug] [task] destroy task=0x7f343b3ee0e0 (task_id=0)
```

I'm not good at sqlite, but I think the in_tail plugin should always keep the database file open and let sqlite3 save and sync the database file via WAL checkpoints. But I understand that it can be difficult and a solution with exposing a flag to sync every N seconds might be easier and solve the problem.

**Comment by edsiper** [comment]
Please check the new DB.Sync option available on 0.12.14 release:

http://fluentbit.io/announcements/v0.12.14/

docs: http://fluentbit.io/documentation/0.12/input/tail.html

**Comment by willmao** [comment]
After setting the DB.sync option to Normal，under high load pressure, the iowait still can reach 14%, and that is too high for us, it would be nice to sync every N records

**Comment by benkap** [comment]
I can confirm that every settings expect sync = Off is causing us a very high write ops on disk (SSD) much more then reasonable. We have a heavy system generating high volume of logs (sending to firehose) and with syn = normal fluent-bit writes **2M per second** which is crazy... only setting sync to off fix the issue. I don't think this issue is closed

**Comment by willmao** [comment]
@edsiper could you reopen this issue as the iowait is still very high when the sync is not Off?

**Comment by MrsZ** [comment]
hi  ，how to set expect sync = Off  to resove the issue？disk io very very high。
