### ISSUE TITLE
conan package recipe

### ISSUE THREAD

**Issue by SteRoh** [fluent/fluent-bit#3962]
**Is your feature request related to a problem? Please describe.**
Hi together,
I'm wondering why there is no conan package available for fluent bit?
Nowadays we are working heavily with conan as a package manager for our C++ projects, and it would be awesome to use fluent bit in a easy and common way in our CI/CD. :)

**Describe the solution you'd like**
Provide a suitable package recipe and upload the package to conan.io

**Comment by Parcley** [comment]
I am wondering if providing a conan package of fluentbit was really considered.
Conan is the de-facto package manager for C++ (https://docs.conan.io/en/latest/) and fluentbit could benefit from offering a conan package:
Developers could easily retrieve the fluentbit conan package and integrate fluentbit's features into their own projects within minutes. 

I vote for providing a conan package. If @SteRoh  and me are not the only ones who see a use-case for a conan-package I might even try to provide a conan-recipe if you are interested?
