### ISSUE TITLE
Tail plugin sometimes reads first line incorrectly after file rotation

### ISSUE THREAD

**Issue by tporeba** [fluent/fluent-bit#3963]
Sometimes after log rotation the first line in file is not read correctly - looks like it is read starting from some non zero offset. 

Unfortunately the effect seems to be random, I do not have a way to reproduce it for now. 
It happened on 9 messages out of 3 million processed so far. 

Example log message in input file (obfuscated, sorry). This was the first line in that file.
```
{"uuid":"9ccc2fe3-253f-4617-aa32-7e86d1038946","id":2750311297,"aaaaaaaaaa":11111,"bbbbbbbb":2222222,"cccccccccc":"CCCC_CCCC_CCCCCC_CCCCCC","ddddddddddd":21,"timestamp":"2021-08-09T14:09:00+0200","ffffffffffffffff":8,"ggggggggggg":8,"hhhhhhhhhhhh":13,"iiiiiiiiiii":1244,"jjjjjjjjjjjjjjj":"XXXX_XXXXXX","kkkkkkkkkk":2331645,"mmmmmmmmmmmm":"11.111.1.111","nnnnnnnnnnnnnnnnnn":1,"oooooooooooooooo":1,"ppppppppppppppppppp":1230,"qqqqqqqqqqqq":"xxx.xxxxxxx.xxxxxxxxxx.xxxxxxxxxxxxxxxx: xxxxxxx xxxx.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxx: xxxxx x xxx xx xxxxxx xxx xxxxxx x ([XX] xxxxxxxxxxxxxxxxxxx#00) xx [XX] xxxxxxxxxxxxxxxxxxx xx xxxx xxxxxx 49","wwwwwwwwwwww":33,"apiCallTime":501,"serverName":"xxx02","status":"FINISHED"}
```
The same message in target kafka topic:
```
{"@timestamp":"2021-08-09T12:09:11.380928Z","log":"piCallTime\":501,\"serverName\":\"xxx02\",\"status\":\"FINISHED\"}","hostname":"os-xxx02.example.com","agent":"fluentbit"}
```

You can see the line is read starting from offset 659 - `piCallTime...`. 

Fluent-bit log from that moment. There is a correlation between timestamp assigned to the request `2021-08-09T12:09:11.380928Z` and time when fluentbit added newly discovered file after previous one was rotated `Aug  9 14:09:11` - this is the same instant, I'm in tz +0200.
```
Aug  9 14:09:02 os-xxx02.example.com td-agent-bit[27616]: [2021/08/09 14:09:02] [ info] [input:tail:tail.0] inode=416770 handle rotation(): /opt/service/businessActivity.log => /opt/service/businessActivity.log.2021-08-09-13
Aug  9 14:09:02 os-xxx02.example.com td-agent-bit[27616]: [2021/08/09 14:09:02] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=416770 watch_fd=69
Aug  9 14:09:02 os-xxx02.example.com td-agent-bit[27616]: [2021/08/09 14:09:02] [ info] [input:tail:tail.0] inotify_fs_add(): inode=416770 watch_fd=71 name=/opt/service/businessActivity.log.2021-08-09-13
Aug  9 14:09:11 os-xxx02.example.com td-agent-bit[27616]: [2021/08/09 14:09:11] [ info] [input:tail:tail.0] inotify_fs_add(): inode=416761 watch_fd=72 name=/opt/service/businessActivity.log
Aug  9 14:09:21 os-xxx02.example.com td-agent-bit[27616]: [2021/08/09 14:09:21] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=416770 watch_fd=71
```

I suspect the problem is as early as in tail plugin, because my messages are json and I can see that the parser handles that message as it is an incorrect json - whole line is escaped and put into "log" field, unlike for correct lines. I guess it wouldn't look like this if the problem was somewhere later for example in kafka output.

**Expected behavior**
No corrupted lines. 

**Your Environment**

* Version used: 1.7.9 installed from official packages
* Operating System and version: Oracle Linux Server 7.9
* Configuration:
```
[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on

[INPUT]
    name tail
    path /opt/service/businessActivity.log*
    tag  someTag
    Mem_Buf_Limit 50MB
    refresh_interval 10
    rotate_wait 10
    ignore_older 1h
    db  /opt/fluentbit/data/registry.db
    read_from_head on
    parser json

[OUTPUT]
    name kafka
    match someTag
    format json
    message_key_field uuid
    brokers broker1:9092, broker2:9092, broker3:9092
    topics someName
    timestamp_format iso8601
    Retry_Limit false
    queue_full_retries 10
    rdkafka.message.timeout.ms 3600000
    rdkafka.queue.buffering.max.messages 100000
    rdkafka.queue.buffering.max.kbytes 51200
    rdkafka.queue.buffering.max.ms 5
    rdkafka.log.connection.close false
    rdkafka.request.required.acks 1
    rdkafka.security.protocol ssl
    rdkafka.ssl.ca.location /opt/fluentbit/etc/ca-cert
    rdkafka.ssl.endpoint.identification.algorithm none
    rdkafka.ssl.key.location  /opt/fluentbit/etc/client.key
    rdkafka.ssl.key.password ********
    rdkafka.ssl.certificate.location  /opt/fluentbit/etc/client-cert-signed

[FILTER]
    name record_modifier
    Match *
    Record hostname ${HOSTNAME}
    Record agent fluentbit
```
Note: I am already aware that `path` in this config should not include `*` at the end as this may cause rotated file to be scanned again and cause duplicates. Still I decided to include that original config I used when corrupted lines occurred. I will let know in comments if I see corrupted lines for config without `*`. Funny thing is that this duplication may actually fix that data loss by overwriting the event, but this is not something we should rely on.  

**Additional context**
I use fluent-bit to tail a log with json events and send them to kafka. Of course every such corrupted line is a data loss. 
It also forced me to implement a workaround on kafka to filter out corrupted messages - I use one of the field from json message as a required key in kafka topic. Corrupted message are not valid json (and field may be missing), so in effect kafka key is empty which may block further processing.

**Comment by tporeba** [comment]
issue is still affecting us, please reopen

**Comment by Fyne5** [comment]
> 

Yes, me too and not found solution yet
