### ISSUE TITLE
does storage buffering apply to all INPUTS

### ISSUE THREAD

**Issue by bharatnc** [fluent/fluent-bit#3964]
I'm trying to understand if the storage buffering explained in the docs: https://docs.fluentbit.io/manual/administration/buffering-and-storage is applicable to all types of inputs & will the bufferning mechanism be the same?

For example, I'm using a tcp INPUT:

```
[SERVICE]
    flush                     1
    log_Level                 info
    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    Name        tcp
    Listen      127.0.0.1
    Alias       tcp_test
    Tag         tcp_test
    Port        12345
    Chunk_Size  32k
    Buffer_Size 64k
    Format      none
    storage.type  filesystem 
    Separator   \n

[OUTPUT]
    name                      stackdriver
    match                     *
    storage.total_limit_size  5M
```

Will the buffering work the same way with all inputs and all settings available under https://docs.fluentbit.io/manual/administration/buffering-and-storage#service-section-configuration is applicable to the `tcp` input as well ?

**Comment by bharatnc** [comment]
@JeffLuoo thank you. Yes I can confirm that buffering works for all inputs. 

I would like the same issue to clarify another question that I had. Does the stackdriver output plugin support the `workers` argument just the like some of the other plugins support ? Example: https://docs.fluentbit.io/manual/pipeline/outputs/kinesis#worker-support. In other words, does fluentbit output to stackdriver work in multiple threaded mode to push faster?

**Comment by JeffLuoo** [comment]
Yes it does. You can start from setting the worker to 1 and slowly increase it to the workers you need.

**Comment by bharatnc** [comment]
Thanks @JeffLuoo .
