### ISSUE TITLE
zero new files found on path for container logs

### ISSUE THREAD

**Issue by eagle4567** [fluent/fluent-bit#3975]
## Bug Report

##[input:tail:tail.0] 0 new files found on path '/var/log/containers/*.log'

I set up logging of kubernetes with output to splunk. I see this in debug:

[2020/07/22 17:02:21] [debug] [input:tail:tail.0] scanning path /var/log/containers/*.log
[2020/07/22 17:02:21] [debug] [input:tail:tail.0] skip (invalid) entry=/var/log/containers/calico-node-tsft7_kube-system_calico-node-324fafed5cf300cbeb621276d15f60ade06cf9b2b3f93c9e48e993967f7e7fcf.log
[2020/07/22 17:02:26] [debug] [input:tail:tail.0] 0 new files found on path '/var/log/containers/*.log'

There is symlink from /var/log/containers/*.log to /var/log/pods/*/*/*.log and /splunk-uf-sidecar/0.log and I have added all these paths in my config below but still encounter the above messages that there are 0 files found on /var/log/containers/*.log.

##My config
---
apiVersion: v1
kind: Namespace
metadata:
  name: loggings
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/proxy
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: loggings
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: loggings
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: loggings
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        storage.path  /buffers
        storage.type  filesystem
        ipv6          On
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-systemd.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-systemd.conf
    @INCLUDE output-splunk.conf

 input-systemd.conf: |
    [INPUT]
      Name            systemd
      Tag             systemd.*
      Path            /run/log/journal
      
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kubernetes.<namespace_name>.<container_name>.<pod_name>.<docker_id>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>.+).log$
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Buffer_Max_Size   5M
        Chunk_Size        32K
        Skip_Long_Lines   Off
        Mem_Buf_Limit     5MB
        Refresh_Interval  10
        DB.Sync           Normal
        Multiline          On
        Parser_Firstline   multiline

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kubernetes.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kubernetes.
        Regex_Parser        k8s-custom-tag
        Keep_Log            On
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         On
        Labels              On
        
   [FILTER]
        Name    modify
        Match   *
        Add KEY VALUE
        Add cluster devcluster
        Set     sourcetype xxx_logs
        Set     source app_xxx
 
  filter-systemd.conf: |
    [FILTER]
        Name modify
        Match systemd.*
        Rename _SYSTEMD_UNIT systemd_unit
        Rename _HOSTNAME hostname

    [FILTER]
        Name record_modifier
        Match systemd.*
        Remove_Key _CURSOR
        Remove_Key _REALTIME_TIMESTAMP
        Remove_Key _MONOTONIC_TIMESTAMP
        Remove_Key _BOOT_ID
        Remove_Key _MACHINE_ID
        
  output-splunk.conf: |
    [OUTPUT]
        Name            splunk
        Match           *
        Host            ${SPLUNK_HOST}
        Port            ${SPLUNK_PORT}
        Splunk_Token    xxx-xxx-xxxx-xxxx-xxx
        TLS             On
        TLS.Verify      Off

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped         log
        Decode_Field_As   escaped_utf8    log
        Decode_Field_As   json            log

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
        
    [PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   ^(?<namespace_name>[^.]+)\.(?<container_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<docker_id>[^.]+)$
        
    [PARSER]
        Name multiline
        Format regex
        Regex /(?<time>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)/
        Time_Key  time
        Time_Format %b %d %H:%M:%S

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: loggings
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: harbor.outpost.ws/library/fluent/fluent-bit:1.5
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: SPLUNK_HOST
          value: "splunkidx.demo.org"
        - name: SPLUNK_PORT
          value: "8088"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: splunkuf
          mountPath: /splunk-uf-sidecar
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: journal
          mountPath: /run/log/journal
          readOnly: true
        - name: splunklogs
          mountPath: /logs/splunk
          readOnly: true
      - name: machineid
          mountPath: /etc/machine-id
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      hostNetwork: true
     dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
          type: ""
      - name: varlogpods
        hostPath:
          path: /var/log/pods
          type: ""
      - name: splunkuf
        hostPath:
          path: /splunk-uf-sidecar
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
          type: ""
      - name: journal
        hostPath:
          path: /run/log/journal
      - name: splunklogs
        hostPath:
          path: /logs/splunk
     - name: machineid
        hostPath:
          path: /etc/machine-id
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      securityContext: 
        runAsUser: 0
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"

**Your Environment**
Using fluent-bit:1.5 image

**Comment by eagle4567** [comment]
Still cannot resolve

**Comment by kartikzheng** [comment]
I also encountered the same problem, and the mount directory has been confirmed. Have you solved it？

**Comment by eagle4567** [comment]
Yes, solved the issue by adding the correct mount path below:

name: docker
hostPath:
path: /var/vcap/store/docker/docker #Docker path in Host System

**Comment by kartikzheng** [comment]
> Yes, solved the issue by adding the correct mount path below:
> 
> name: docker hostPath: path: /var/vcap/store/docker/docker #Docker path in Host System

Thank you very much, the previous default docker path is changed, mount the new docker path is good.
