### ISSUE TITLE
Logs in UTF-8 with BOM: BOM is included in the first record

### ISSUE THREAD

**Issue by Lumiond** [fluent/fluent-bit#3976]
## Bug Report

**Describe the bug**
Our logs in UTF-8 with BOM.
The BOM markup (\ufeff) is included on begin of the first record and I think it's bug (it breaks parsing in fluentd and we lose every first line in logs).

**To Reproduce**
Example content of the log file saved as UTF-8 with BOM:
```
00:09.375, First message
00:09.377, Second message
```
Steps to reproduce the problem:
Run fluent-bit configured with tail input plugin and save the result into file result.txt (the simplest way, we use kafka as messages buffer).
The content of the result.txt file:

```
tail.0: [1616161296.897021300, {"log":"\ufeff00:09.375, First message"}]
tail.0: [1616161296.897031500, {"log":"00:09.377, Second message"}]
```

**Expected behavior**
The expected content of the result.txt should be:

```
tail.0: [1616161296.897021300, {"log":"00:09.375, First message"}]
tail.0: [1616161296.897031500, {"log":"00:09.377, Second message"}]
```

**Your Environment**

Version used: 1.8.0, I built it myself, cause we need kafka plugin.
Configuration:
```
[INPUT]
    name tail    
    Path C:\tmp-logs\input\*.log
    Read_from_Head true
    
[OUTPUT]
    name file
    match *
    path C:\tmp-logs\output
    file results.txt
```
Operating System and version: Windows 10
Filters and plugins: tail

**Additional context**
I tried to cut this prefix on fluentd but unsuccessfully. After that I found this bug: #3256.
I can't provide our logs so I use some info from 3256 🤔
Also, any workaround can be acceptable (but we can't change logs encoding)

**Comment by Lumiond** [comment]
Still need assistance.

**Comment by Lumiond** [comment]
Still have problems with BOM symbols 😐

**Comment by Lumiond** [comment]
@edsiper can you help me? How can I remove BOM from messages? Unfortunately, logs can be only in UTF-8 with BOM.

**Comment by simonvanbernem** [comment]
I also ran into this exact issue. In my case the symptom was that `Decode_Field_As json` wasn't working as expected for the first record of the file. Seems like the first record included the byte order mark, and that made the json parsing fail, causing elastic to receive a string where there should be a json object, and returning an error.

**Comment by simonvanbernem** [comment]
@Lumiond I found a workaround: You can detect and remove the BOM in a lua filter. For this to work, the parser must run AFTER the lua filter. So you need a separate parser-filter and must not use the parser option in the tails input! The dataflow looks like this:

Input  ---(text with bom)--->  lua-filter  ---(text without bom)--->  parser-filter   -----(json)---->   other filters/output.

The lua-filter in the configuration:

    [FILTER]
        Name lua
        Match *
        Script lua_scripts.lua
        call remove_utf8bom

The lua_scripts.lua file:

    function remove_utf8bom(tag, timestamp, record)
        utf8_bom = string.char(0xEF, 0xBB, 0xBF)
        if(string.sub(record["log"],1, 3) == utf8_bom) then
            record["log"] = string.sub(record["log"], 4, -1)
            return 2, timestamp, record
        else
            return 0, timestamp, record
        end
    end
