### ISSUE TITLE
Ambiguous message when S3 output can't parse TAG

### ISSUE THREAD

**Issue by yuranos** [fluent/fluent-bit#3979]
## Bug Report
My config is as follows:
```
tail
kubernetes
rewrite_tag
s3
```
By rules in rewrite_tag are not suitable for some tags and as a result the tag is rewritten to:
`..kube-proxy-pqwgz_kube-system_kube-proxy-d67f25f48573cde41c2528f7ddb873705953fe633b7c7b7419704d6e57139a74`
Notice 2 dots in the beginning. It means that the TAG indices I was trying to use were not available.

As a result S3 output outputs a warning:
`[2021/08/20 07:38:09] [ warn] [s3_key] Invalid / Out of bounds tag part: At most 10 tag parts ($TAG[0] - $TAG[9]) can be processed. tag=..kube-proxy-pqwgz_kube-system_kube-proxy-d67f25f48573cde41c2528f7ddb873705953fe633b7c7b7419704d6e57139a74, format=/$TAG[0]/$TAG[1]/$TAG[2]/%Y-%m-%d-%H-%M-%S-$UUID.json, delimiters=.`
Which is really ambiguous because it's not that I use TAG parts in >10 range, but rather that the lower indices are not available(TAG[0-2]).

**Comment by ssplatt** [comment]
I just hit this error as well. with `$TAG[2]`. Some logs still seem to go through without issue.

**Comment by ssplatt** [comment]
I just removed `workers 1` and the tag processing is working again.

**Comment by benjaminwood** [comment]
Following up here in 2023 👋🏻 

[The docs](https://docs.fluentbit.io/manual/pipeline/outputs/s3#worker-support) mention

> The plugin can only support a single worker; enabling multiple workers will lead to errors/indeterminate behavior.

However, it appears that the **default** is now `workers 1`. Which means, you'll get the "errors/indeterminate behavior" described if you're using more than one S3 output in your configuration unless you explicitly specify `workers 0`.

I'd like to take this opportunity to link future readers to this absolute gem of a blog post: https://www.stilldrinking.org/programming-sucks
