### ISSUE TITLE
Sporadic SIGSEGV crashloop with k8s helm chart

### ISSUE THREAD

**Issue by nijave** [fluent/fluent-bit#3983]
## Bug Report

**Describe the bug**

Sporadic SIGSEGV on pods using daemonset helm chart
```
 [2021/08/21 01:36:51] [ info] [input:tail:tail.0] inotify_fs_add(): inode=525368 watch_fd=7 name=/var/log/containers/traefik-658f9b7576-bp2wv_traefik-v2_traefik-cea7e3ea184264c5286049e3187f8bbe828df67fbb2ca72724a65f2225d89095.log
 [2021/08/21 01:36:52] [engine] caught signal (SIGSEGV)
 [2021/08/21 01:36:52] [debug] [socket] could not validate socket status for #35 (don't worry)
 #0  0x55cd9d6be058      in  mk_list_is_empty() at lib/monkey/include/monkey/mk_core/mk_list.h:100
 #1  0x55cd9d6be2a6      in  is_healthy() at src/http_server/api/v1/health.c:75
 #2  0x55cd9d6be8ab      in  cb_health() at src/http_server/api/v1/health.c:266
 #3  0x55cd9daac57b      in  thread_cb_init_vars() at lib/monkey/mk_server/mk_http_thread.c:69
 #4  0x55cd9dab7786      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
 #5  0xffffffffffffffff  in  ???() at ???:0
```

**To Reproduce**
Deploy the helm chart `fluent/fluent-bit` (fluent-bit-0.16.2) with the following values
```
image:
  tag: 1.8

readinessProbe:
  httpGet:
    path: /api/v1/health
    port: http
  initialDelaySeconds: 0

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
config:
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        # Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail Off

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name modify
        Match *.*
        Add index k8s 

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name stdout
        Match *.*
        Format json_lines

logLevel: debug
```

**Expected behavior**

All pods start successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/384474/130307842-5c08fb2b-3e36-48cc-9bfa-233f65219b7c.png)
(so 1 pod has some issues then starts, 1 pod starts fine, the last pod is stuck in a crash loop)
![image](https://user-images.githubusercontent.com/384474/130307850-7b5c7892-cbfc-4dc8-938c-e3cac6944f6d.png)

**Your Environment**

* Version used: 1.8.3
* Configuration: (see above)
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.22.0 (it is vanilla on VMs w/ kubeadm)
* Operating System and version: Ubuntu 20.04 (running k8s)
* Filters and plugins: (see above)

**Additional context**

I cherry-picked a couple 1.8.x versions and it seemed to effect them all. Pods seem to start reliably with `readinessProbe` set to `initialDelaySeconds: 5` so I'm thinking maybe there's a race condition here

See also (another user) https://fluent-all.slack.com/archives/C0CTQGHKJ/p1628585157230400
Possibly same issue here https://repo1.dso.mil/platform-one/big-bang/bigbang/-/issues/595#note_372064

**Comment by nokute78** [comment]
Thank you for reporting. I can reproduce this issue.

1. run `curl.sh`
2. run `fluent-bit`

curl.sh:
```sh
while true
do
    curl -s localhost:2020/api/v1/health
done
```

fluent-bit.conf:
```
[SERVICE]
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020
    Health_Check On 
    HC_Errors_Count 5 
    HC_Retry_Failure_Count 5 
    HC_Period 5 

[INPUT]
    Name  cpu

[OUTPUT]
    Name  null
    Match *
```

**Comment by nokute78** [comment]
I sent a patch #4056
