### ISSUE TITLE
Memory footprint of fluent-bit keeps on increasing even after Mem_Buf_Limit is reached

### ISSUE THREAD

**Issue by utkmishr** [fluent/fluent-bit#3988]
## Bug Report

**Describe the bug**
I am running fluent-bit (1.8) in a pod to collect log records from other applications. I have set Mem_Buf_Limit on the input plugin as 5MB.  I am pushing data from http output plugin to the remote server. I am observing that memory footprint of fluent-bit keeps on increasing when upstream connectivity is lost. Looks like fluent-bit is not respecting the Mem_Buf_Overlimit value.I can see in logs that Mem_Buffer_Overlimit is reached,  so as per documentation - https://docs.fluentbit.io/manual/administration/buffering-and-storage , input plugin should be paused and stop processing any more data , but looks like this is not happening.

(I have disable all the filters/parsers but then also I was able to reproduce this issue.)
       I  am running 35 test pods and configure fluent-bit to collect logs from them . Each of the test pods are emitting logs at the rate of 100KB/s.
Memory usage -

Observations - 
```
memory foot print increase linearily, after memory buffer is full -
[2021/08/23 09:22:09] [ warn] [input] tail.0 paused (mem buf overlimit)
----------------------------------------------
$ kubectl top pods -n obs
NAME                                  CPU(cores)   MEMORY(bytes)
fluent-bit-obs-sd9kq                  2m           30Mi
--------------------------------------------
$ kubectl top pods -n obs
NAME                                  CPU(cores)   MEMORY(bytes)
fluent-bit-obs-sd9kq                  1m           35Mi
------------------------
$ kubectl top pods -n obs
NAME                                  CPU(cores)   MEMORY(bytes)
fluent-bit-obs-sd9kq                  27m          40Mi
--------------------
$ kubectl top pods -n obs
NAME                                  CPU(cores)   MEMORY(bytes)
fluent-bit-obs-sd9kq                  2m           52Mi

```

**Expected behavior**
Input plugin should be paused on reaching the Mem_Buf_Overlimit and memory footprint of fluent-bit should stop growing.

**Your Environment**
* Version used: 1.8.0
* Configuration:
```
fluent-bit.conf: |
    [SERVICE]
        Flush  1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        DB /tail-db/tail-containers-state.db
        DB.Sync Normal
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
    [INPUT]
        Name tail
        Path /var/log/syslog
        Parser syslog
        Tag syslog.*
        Refresh_Interval 5
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name tail
        Path /var/log/auth.log
        Parser syslog
        Tag syslog.*
        Refresh_Interval 5
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        DB /tail-db/tail-authlog-state.db
        DB.Sync Normal

    [OUTPUT]
        Name  http
        Match *
        Log_Level  info
        Host  logsth.thp.svc.cluster.local
        Port  9090
        URI   /calTh-test
        Retry_Limit   false
        Format        json
        Compress      gzip
        json_date_key @timestamp
        json_date_format iso8601
        header_tag    X-LOGS

```

* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.15
* Operating System and version: Ubuntu 18.04
* Filters and plugins: same as above

**Additional context**
Had same tests on v1.7.0 and 1.7.8 but found same behaviour

**Comment by utkmishr** [comment]
[logs_fluentbit_mem.txt](https://github.com/fluent/fluent-bit/files/7043793/logs_fluentbit_mem.txt)
^^ attached fluent-bit logs. Might be helpful in debugging.

**Comment by utkmishr** [comment]
Ran the same configuration with valgrind for v1.7.0 and v1.8.6 .
command : /usr/bin/valgrind --leak-check=full --log-file=val_70.txt fluent-bit/bin/fluent-bit  -c  /fluent-bit/etc/fluent-bit.conf
v1.7.0 logs :
[val_70.txt](https://github.com/fluent/fluent-bit/files/7121201/val_70.txt)

1. from above Logs -
#####
==22== Memcheck, a memory error detector
==22== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22== Command: fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
==22== Parent PID: 6
==22== 
==22== 
==22== HEAP SUMMARY:
==22==     in use at exit: 112,087,090 bytes in 8,147 blocks
==22==   total heap usage: 327,755 allocs, 319,608 frees, 1,977,143,071 bytes allocated
==22== 
==22== 4 bytes in 1 blocks are possibly lost in loss record 3 of 605
==22==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22==    by 0x36C6C9: strdup_with_null (regparse.c:279)
==22==    by 0x36C6C9: name_add (regparse.c:791)
==22==    by 0x36C6C9: parse_enclose (regparse.c:5053)
==22==    by 0x36C6C9: parse_exp (regparse.c:6534)
==22==    by 0x36CB65: parse_branch (regparse.c:6892)
==22==    by 0x36CB65: parse_subexp (regparse.c:6938)
==22==    by 0x36D051: parse_regexp (regparse.c:6987)
==22==    by 0x36D051: onig_parse_make_tree (regparse.c:7032)
==22==    by 0x37CF77: onig_compile (regcomp.c:5754)
==22==    by 0x37DABA: onig_new (regcomp.c:5982)
==22==    by 0x24841A: str_to_regex (flb_regex.c:78)
==22==    by 0x2484A9: flb_regex_create (flb_regex.c:108)
==22==    by 0x23BCD1: flb_parser_create (flb_parser.c:206)
==22==    by 0x23CAE6: flb_parser_conf_file (flb_parser.c:568)
==22==    by 0x224FDF: flb_config_set_property (flb_config.c:463)
==22==    by 0x18C1FD: flb_service_conf (fluent-bit.c:714)
==22== 
==22== 4 bytes in 1 blocks are possibly lost in loss record 4 of 605
==22==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22==    by 0x6DEB592: re_node_set_init_copy (regex_internal.c:1023)
==22==    by 0x6DEB592: create_cd_newstate (regex_internal.c:1662)
==22==    by 0x6DEB592: re_acquire_state_context (regex_internal.c:1534)
==22==    by 0x6DF2AF5: create_initial_state (regcomp.c:1043)
==22==    by 0x6DF2AF5: re_compile_internal (regcomp.c:804)
==22==    by 0x6DF83C1: regcomp (regcomp.c:498)
==22==    by 0x6FDF9B: str_to_regex (mk_vhost.c:48)
==22==    by 0x6FE803: mk_vhost_handler_match (mk_vhost.c:336)
==22==    by 0x6FC8DD: mk_vhost_handler (mk_lib.c:489)
==22==    by 0x3203E1: api_v1_uptime (uptime.c:109)
==22==    by 0x31F75D: api_v1_registration (register.c:31)
==22==    by 0x2548F9: flb_hs_create (flb_hs.c:90)
==22==    by 0x22D59A: flb_engine_start (flb_engine.c:581)
==22==    by 0x210703: flb_lib_worker (flb_lib.c:493)
######


from the above logs the 'possibly-lost' bytes keeps on  growing  like below - >


==22== 887,555 bytes in 23 blocks are possibly lost in loss record 599 of 605
==22==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22==    by 0x217EF5: flb_malloc (flb_mem.h:62)
==22==    by 0x218114: sds_alloc (flb_sds.c:40)
==22==    by 0x218250: flb_sds_create_size (flb_sds.c:92)
==22==    by 0x217172: flb_msgpack_raw_to_json_sds (flb_pack.c:699)
==22==    by 0x217A33: flb_pack_msgpack_to_json_format (flb_pack.c:973)
==22==    by 0x2B46AC: cb_http_flush (http.c:319)
==22==    by 0x21D779: output_pre_cb_flush (flb_output.h:463)
==22==    by 0x717106: co_init (amd64.c:117)
==22== 
==22== 1,254,400 bytes in 50 blocks are possibly lost in loss record 600 of 605
==22==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22==    by 0x717220: co_create (amd64.c:142)
==22==    by 0x21DE36: flb_output_coro_create (flb_output.h:508)
==22==    by 0x21DE36: flb_output_task_flush (flb_output.c:197)
==22==    by 0x22E241: flb_engine_dispatch_retry (flb_engine_dispatch.c:74)
==22==    by 0x231508: flb_sched_event_handler (flb_scheduler.c:404)
==22==    by 0x22DA0C: flb_engine_start (flb_engine.c:659)
==22==    by 0x210703: flb_lib_worker (flb_lib.c:493)
==22==    by 0x4E456DA: start_thread (pthread_create.c:463)
==22==    by 0x6E1871E: clone (clone.S:95)
==22== 
==22== 2,424,832 bytes in 74 blocks are possibly lost in loss record 602 of 605
==22==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22==    by 0x26D7EC: flb_malloc (flb_mem.h:62)
==22==    by 0x26FB26: flb_tail_file_append (tail_file.c:706)
==22==    by 0x2745ED: tail_scan_path (tail_scan_glob.c:255)
==22==    by 0x2748AD: flb_tail_scan (tail_scan.c:42)
==22==    by 0x26AAB7: in_tail_init (tail.c:297)
==22==    by 0x21AB32: flb_input_instance_init (flb_input.c:483)
==22==    by 0x21AC0F: flb_input_init_all (flb_input.c:519)
==22==    by 0x22D2F0: flb_engine_start (flb_engine.c:501)
==22==    by 0x210703: flb_lib_worker (flb_lib.c:493)
==22==    by 0x4E456DA: start_thread (pthread_create.c:463)
==22==    by 0x6E1871E: clone (clone.S:95)
==22== 
==22== LEAK SUMMARY:
==22==    definitely lost: 0 bytes in 0 blocks
==22==    indirectly lost: 0 bytes in 0 blocks
==22==      possibly lost: 6,641,680 bytes in 3,501 blocks
==22==    still reachable: 105,445,410 bytes in 4,646 blocks
==22==                       of which reachable via heuristic:
==22==                         length64           : 440,808 bytes in 183 blocks
==22==                         newarray           : 792 bytes in 9 blocks
==22==         suppressed: 0 bytes in 0 blocks
==22== Reachable blocks (those to which a pointer was found) are not shown.
==22== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==22== 
==22== For counts of detected and suppressed errors, rerun with: -v
==22== ERROR SUMMARY: 353 errors from 353 contexts (suppressed: 0 from 0)
#####
this eventuality causes the pod to go OOM and crash.

2. while did the same test with v1.8.6 under the load where 20 pods are running and each pod is emitting 130 log lines per second and each log is 350 bytes long , observed that valgrind logs "invalid read" 
######
==17== Invalid read of size 8
==17==    at 0x785A9B: mk_event_add (mk_event.c:96)
==17==    by 0x235694: net_connect_async (flb_network.c:405)
==17==    by 0x236C52: flb_net_tcp_connect (flb_network.c:1138)
==17==    by 0x263813: flb_io_net_connect (flb_io.c:89)
==17==    by 0x2443D6: create_conn (flb_upstream.c:523)
==17==    by 0x24493A: flb_upstream_conn_get (flb_upstream.c:666)
==17==    by 0x2DEE24: http_post (http.c:86)
==17==    by 0x2DFC44: cb_http_flush (http.c:326)
==17==    by 0x22A0DE: output_pre_cb_flush (flb_output.h:509)
==17==    by 0x788026: co_init (amd64.c:117)
==17==  Address 0x3533643338633942 is not stack'd, malloc'd or (recently) free'd
==17== 
==17== Invalid read of size 8
==17==    at 0x6874506: ??? (in /lib/x86_64-linux-gnu/libgcc_s.so.1)
==17==    by 0x687508C: _Unwind_Backtrace (in /lib/x86_64-linux-gnu/libgcc_s.so.1)
==17==    by 0x210AC8: backtrace_full (backtrace.c:127)
==17==    by 0x194EAD: flb_stacktrace_print (flb_stacktrace.h:71)
==17==    by 0x1968B6: flb_signal_handler (fluent-bit.c:559)
==17==    by 0x6ABB03F: ??? (in /lib/x86_64-linux-gnu/libc-2.27.so)
==17==    by 0x785A9A: mk_event_add (mk_event.c:96)
==17==    by 0x235694: net_connect_async (flb_network.c:405)
==17==    by 0x236C52: flb_net_tcp_connect (flb_network.c:1138)
==17==    by 0x263813: flb_io_net_connect (flb_io.c:89)
==17==    by 0x2443D6: create_conn (flb_upstream.c:523)
==17==    by 0x24493A: flb_upstream_conn_get (flb_upstream.c:666)
==17==  Address 0x2b0919a0 is 0 bytes after a block of size 25,088 alloc'd
==17==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17==    by 0x788140: co_create (amd64.c:142)
==17==    by 0x22A7D2: flb_output_coro_create (flb_output.h:554)
==17==    by 0x22A7D2: flb_output_task_flush (flb_output.c:199)
==17==    by 0x23DAA7: tasks_start (flb_engine_dispatch.c:183)
==17==    by 0x23DCEB: flb_engine_dispatch (flb_engine_dispatch.c:290)
==17==    by 0x23B4FC: flb_engine_flush (flb_engine.c:115)
==17==    by 0x23CC85: flb_engine_handle_event (flb_engine.c:396)
==17==    by 0x23CC85: flb_engine_start (flb_engine.c:686)
==17==    by 0x21BB68: flb_lib_worker (flb_lib.c:627)
==17==    by 0x4E456DA: start_thread (pthread_create.c:463)
==17==    by 0x6B9D71E: clone (clone.S:95)
==17== 
==17== 
==17== Process terminating with default action of signal 6 (SIGABRT): dumping core
==17==    at 0x6ABAFB7: raise (raise.c:51)
==17==    by 0x6ABC920: abort (abort.c:79)
==17==    by 0x1968BB: flb_signal_handler (fluent-bit.c:561)
==17==    by 0x6ABB03F: ??? (in /lib/x86_64-linux-gnu/libc-2.27.so)
==17==    by 0x785A9A: mk_event_add (mk_event.c:96)
==17==    by 0x235694: net_connect_async (flb_network.c:405)
==17==    by 0x236C52: flb_net_tcp_connect (flb_network.c:1138)
==17==    by 0x263813: flb_io_net_connect (flb_io.c:89)
==17==    by 0x2443D6: create_conn (flb_upstream.c:523)
==17==    by 0x24493A: flb_upstream_conn_get (flb_upstream.c:666)
==17==    by 0x2DEE24: http_post (http.c:86)
==17==    by 0x2DFC44: cb_http_flush (http.c:326)
==17== 
==17== HEAP SUMMARY:
==17==     in use at exit: 62,253,986 bytes in 7,097 blocks
==17==   total heap usage: 116,913 allocs, 109,816 frees, 599,238,612 bytes allocated
####

Logs attached 
[val_86.txt](https://github.com/fluent/fluent-bit/files/7121237/val_86.txt)

**Comment by holstvoogd** [comment]
fwiw, I'm seeing similar issues. Configured Mem_Buf_Limit at 5M & the container runs uyp to 128mb & gets OOM'ed after 5 minutes consistently. I don't have a clue what is going on, nothing useful in the logs
