### ISSUE TITLE
Can I remove exit() in flb_utils_error_c()?

### ISSUE THREAD

**Issue by takahasi** [fluent/fluent-bit#400]
Hi,

flb_utils.c:flb_utils_error_c() has exit().
I think this spec is inconvenient in the case of using the library.
Also, the runtime test programs may finish at the unnecessary timing. 

For example, the error case of in_disk.c:296 could not do the finalize routine.

```
if (ret < 0) {
    flb_utils_error_c("could not set collector for disk input plugin");                                 
    goto init_error;
 }

init_error:
    flb_free(disk_config->read_total);
    flb_free(disk_config->write_total);
    flb_free(disk_config->prev_read_total);
    flb_free(disk_config->prev_write_total);
    flb_free(disk_config);
    return -1;
```

**Comment by edsiper** [comment]
yes, it's inconvenient, you can remove it. it should be dropped and instead use flb_error() which is safe.

**Comment by takahasi** [comment]
Thanks!
