### ISSUE TITLE
Windows Exporter Metrics

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#4026]
This enhancement request is filed to track the progress of the implementation of the _Windows Exporter Metrics_ input plugin. This plugin will replicate the functionality from [Prometheus Windows Exporter](https://github.com/prometheus-community/windows_exporter) .

Assigned to @leonardo-albertovich (Calyptia)

**Comment by adamdepollo** [comment]
@edsiper is there any idea when you might start working on this? My team is using FluentBit as a system monitor for our Linux servers and would like to do the same for Windows

**Comment by hisa-tanaka** [comment]
upvote for @adamdepollo. 
Btw, as I mentioned in the [issue](https://github.com/fluent/fluent-bit/issues/5337), we would like to see memory related metrics as we have ones for CPU today.

**Comment by kstkrv** [comment]
Hey, any updates on this?

**Comment by edsiper** [comment]
this was fixed while ago: https://docs.fluentbit.io/manual/pipeline/inputs/windows-exporter-metrics

closing.
