### ISSUE TITLE
out_s3 memory usage since adding data ordering preservation feature 

### ISSUE THREAD

**Issue by psoaresgit** [fluent/fluent-bit#4038]
## Bug Report

The commit (8cd50f8) via #3842 seems to occasion a runaway increase in memory usage.

Using `preserve_data_ordering false` does not prevent the memory usage increase.

I've reverted 8cd50f8 manually, and, with HEAD at 2696f7c via #3805, I don't see the increase in memory usage.

**Screenshots**
![ECS Memory Utilization metrics screenshot](https://user-images.githubusercontent.com/928889/131734809-a93a8cbd-cd50-487a-94cf-ff947951241c.png)

The peaks/drops are the ECS task becoming unhealthy and a new one being run in the ECS service.

The later flat-line is with the commit in question reverted.

**Your Environment**
* Version used: 1.8.3 via aws-for-fluent-bit 2.19.0
* Configuration:
```
 [OUTPUT]
    Name            s3
    Match           *
    bucket          ${BUCKET}
    region          ${AWS_REGION}
    s3_key_format   /${PREFIX}%Y/%m/%d/%H/$UUID.gz
    total_file_size 1M
    upload_timeout  1m
    use_put_object  true
    compression     gzip
    log_key         log
```
* Environment name and version:
ECS
* Server type and version:
EC2
* Operating System and version:
AL2

**Comment by PettitWesley** [comment]
@psoaresgit Since this issue might be very AWS specific, can you please open an issue at our distro and reference this one? That will be used for our tracking purposes. 

https://github.com/aws/aws-for-fluent-bit
