### ISSUE TITLE
4096 bytes are not enough to process cloudwatch response

### ISSUE THREAD

**Issue by somdoron** [fluent/fluent-bit#4044]
## Bug Report

**Describe the bug**

When using cloudwatch output the plugin sometimes fails to process the response from cloudwatch due to the max data size set to 4096.

**To Reproduce**

```
[2021/09/02 11:49:52] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/09/02 11:49:52] [error] [output:cloudwatch_logs:cloudwatch_logs.1] Recieved code 200 but response was invalid, x-amzn-RequestId header not found
```

**Expected behavior**
fluentbit should be able to process the cloudwatch response.

**Your Environment**

* Version used: 1.8.2
* Configuration:

```         
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Parser docker
            Tag kube.*
            Buffer_Max_Size 1MB
            Mem_Buf_Limit   20MB
            Skip_Long_Lines On
            Docker_Mode     On
            Docker_Mode_Parser docker_multiline
            
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc.cluster.local:443
            Merge_Log           On
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On            
            
        [OUTPUT]
            Name                  cloudwatch_logs
            Match                 kube.*
            region                us-east-1
            log_group_name        /aws/eks/fluentbit-cloudwatch/logs
            log_stream_prefix     fluentbit-
            auto_create_group     false    
```            

* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.19
* Operating System and version: AWS EKS
* Filters and plugins: kubernetes, cloudwatch

**Comment by PettitWesley** [comment]
We noticed this issue this week as well. We want to set the http buffer for AWS to be unlimited I think. 

@hossain-rayhan Did we contribute this change already?

**Comment by hossain-rayhan** [comment]
>@hossain-rayhan Did we contribute this change already?

Hey @PettitWesley , Not yet. We were looking for more stable version for our firehose issue. I think we can send the PR against master and v1.8 branch.

**Comment by PettitWesley** [comment]
The fix has been contributed and released in 1.8.8

**Comment by PettitWesley** [comment]
Sorry, I meant 1.8.7

**Comment by gabegorelick** [comment]
For the record, https://github.com/fluent/fluent-bit/pull/4047 was the PR that fixed this.

**Comment by welcor** [comment]
#4045 still needs to be merged to fix this for the http output.
