### ISSUE TITLE
Fluent Bit Docker Input plugin -  mem_limit wrong value

### ISSUE THREAD

**Issue by szalaci** [fluent/fluent-bit#4083]
Fluent Bit -> Input plugin for docker metrics - mem_limt values
docker-compose.yml mem_limit -- FluentBit mem_limit
512M                                              -- 536,870,912              -- OK
2G                                                  -- 2,147,483,648           -- OK
7G                                                   -- 3,221,225,472           -- wrong
unlimited                                        -- 4,294,963,200          -- wrong

**Screenshots**
![image](https://user-images.githubusercontent.com/11660135/132988810-807a9bfb-3d58-469b-8c0d-38600785fd28.png)

![image](https://user-images.githubusercontent.com/11660135/132988895-a9a7e819-cfe7-4892-b8c6-5e5a3fa57d4d.png)

Fluent Bit docker-compose.yml:
version: '3'

services:
  fluent-bit:
    image: fluent/fluent-bit:1.8
    container_name: fluent-bit
    restart: unless-stopped
    volumes:
      # conf
      - ./conf:/fluent-bit/etc:ro
      # date
      - /etc/localtime:/etc/localtime:ro
      # docker metrics
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

**Comment by nokute78** [comment]
Thank you for reporting issue.
I sent a patch https://github.com/fluent/fluent-bit/pull/4154.
