### ISSUE TITLE
Fluent-Bit 1.8.6 - Ubuntu TLS Issue

### ISSUE THREAD

**Issue by joeyberkovitz** [fluent/fluent-bit#4085]
## Bug Report

**Describe the bug**
Ubuntu build of Fluent-Bit v1.8.6 throws an error while parsing a CA certificate that is accepted on CentOS 7 using the same version of Fluent-Bit.

**To Reproduce**
- Error message
```
[tls] /tmp/fluent-bit-1.8.6/src/tls/mbedtls.c:178 X509 - The extension tag or value is invalid : ASN1 - ASN1 tag was of a
```

**Your Environment**

* Version used: 1.8.6
* Configuration:
```
[OUTPUT]
    name es
    ...
    tls on
    tls.verify on
    tls.ca_file PATH_TO_CERT.pem
    ...
```

* Environment name and version (e.g. Kubernetes? What version?): Ubuntu 20.04.3

**Comment by edsiper** [comment]
Looks like you are building it from scratch, you should use OpenSSL instead of mbedtls which is being deprecated (install your openssl dev dependencies before running cmake)

**Comment by joeyberkovitz** [comment]
I was using the official Fluent-Bit package for Ubuntu 20.04 from: https://docs.fluentbit.io/manual/installation/linux/ubuntu
Is it possible to get that build switched over to OpenSSL?

**Comment by agup006** [comment]
@joeyberkovitz the packaged versions should already be using OpenSSL, perhaps something strange triggering mbed

**Comment by joeyberkovitz** [comment]
Is there any way to verify that the binary has OpenSSL support enabled?
Other than that, is there anything that I can do to help debug this? As I mentioned earlier, using the same CA cert and same version, official package on CentOS 7 has no issues

**Comment by agup006** [comment]
Giving this a shot on Ubuntu 20.04 LTS on my side, I'll try to update within the next few hours

**Comment by agup006** [comment]
Installed on Ubuntu 20.04, believe I have OpenSSL, will confirm with folks on this output tomorrow

```
{"fluent-bit":{"version":"1.8.6","edition":"Community","flags":["FLB_HAVE_PARSER","FLB_HAVE_RECORD_ACCESSOR","FLB_HAVE_STREAM_PROCESSOR","FLB_HAVE_TLS","FLB_HAVE_METRICS","FLB_HAVE_AWS","FLB_HAVE_AWS_CREDENTIAL_PROCESS","FLB_HAVE_SIGNV4","FLB_HAVE_SQLDB","FLB_HAVE_TRACE","FLB_HAVE_METRICS","FLB_HAVE_HTTP_SERVER","FLB_HAVE_SYSTEMD","FLB_HAVE_VALGRIND","FLB_HAVE_FORK","FLB_HAVE_GMTOFF","FLB_HAVE_UNIX_SOCKET","FLB_IS_TD_AGENT","FLB_HAVE_PROXY_GO","FLB_HAVE_JEMALLOC","FLB_HAVE_LIBBACKTRACE","FLB_HAVE_REGEX","FLB_HAVE_UTF8_ENCODER","FLB_HAVE_LUAJIT","FLB_HAVE_C_TLS","FLB_HAVE_ACCEPT4","FLB_HAVE_INOTIFY"]}}
```

**Comment by educriado** [comment]
I had the same issue on Ubuntu 20.04.3, using td-agent-bit package version 1.8.10.
When I built the source from scratch after installing libssl-dev the service worked fine.

**Comment by joeyberkovitz** [comment]
haven't had a chance to test for a while, but seems to me that maybe the official fluent-bit packages on Ubuntu might not be built against OpenSSL

**Comment by educriado** [comment]
Yes, that's my suspicion as well. Should this issue be reopened?

**Comment by joeyberkovitz** [comment]
Fix pushed here, https://github.com/fluent/fluent-bit-packaging/pull/26, and tested on Ubuntu 20.04
