### ISSUE TITLE
FluentBit's tls wrapper function for SSL_read returns SSL errors as positive numbers indicating bytes read.

### ISSUE THREAD

**Issue by krispraws** [fluent/fluent-bit#4098]
## Bug Report

**Describe the bug**
The openssl implementation of the flb_tls api has a bug in SSL_read. When `tls_net_read` gets a non-retryable error code like `SSL_ERROR_SSL`, it returns the value as-is instead of changing to -1. The SSL_ERROR_* enums have positive values. In my workflow, it made the caller think that it read 1 byte and it made the `flb_http_client` go into an endless loop thinking it read one byte. The http code retries endlessly till it gets a valid end of header marker or until it runs of response buffer space, 
We also had an unlimited http max response buffer size so the output thread was locked up till it would have eventually run out of memory.

I discovered the bug in 1.7.5 but the issue exists in master as well.
 
I fixed it and a few other things in https://github.com/fluent/fluent-bit/compare/v1.7.5...krispraws:v1_7_5_openssl_fix?expand=1
There are 5 commits in it
1. The first one is an aws issue we recently fixed in 1.8.x and master. You can ignore that.
2. Second is a one line vanilla fix for the bug we found.
3. Third commit has a few other minor fixes I noticed.
4. Fourth is a refactored version of logging and error handling for SSL_read, SSL_write, SSL_connect.
5. Fifth is another small fix where ERR_get_error() and ERR_get_string(ERR_get_error()) were both logged but they wouldn’t match because ERR_get_error removes the error from the queue so the second call would return a different value.

I have tested these against 1.7.5 with the tail plugin feeding logs to kinesis firehose.
 
There is one potential issue(?) I noticed but don’t yet have a fix for:
The code does not retry when SSL_ERROR_WANT_WRITE is returned from SSL_read. The documentation says it can happen and should be handled by retrying the same function. I saw multiple versions of how it should be handled and it was not very clear to me so I punted on it.

Additionally, it would be good to impose a configurable  limit on either the number of times or the time the http_client calls read to get a response. It is an unlikely scenario but it is the reverse of a slow Loris attack targeting a client instead of server.

**To Reproduce**
- Rubular link if applicable: N/A
- Example log message if applicable:
Lack of logs made it difficult to debug this. No useful info was logged even with trace level. The only indication was a constant stream of net_read trace log messages indicating that 1 byte was read.
- Steps to reproduce the problem:
<TODO>

**Expected behavior**
The SSL error codes must be mapped to the format that the caller expects to indicate success or failure.

**Screenshots**
N/A

**Your Environment**
* Version used: 1.7.5
* Configuration: <TODO>
* Environment name and version (e.g. Kubernetes? What version?): EC2
* Server type and version:
* Operating System and version: AL2
* Filters and plugins: tail, kinesis.firehose

**Comment by krispraws** [comment]
Sorry for the confusion about `openssl implementation of the flb_tls api`. I am referring to tls/openssl.c in the fluent-bit src folder.
This line is the bug: https://github.com/fluent/fluent-bit/blob/master/src/tls/openssl.c#L362
it treats only negative values as errors but the SSL_get_error return values are positive for errors.
This is the fix for it: https://github.com/fluent/fluent-bit/commit/ed947a6c6e31f1a30b296517d68b9ef7b7c0bd5a

**Comment by krispraws** [comment]
@edsiper - I think the current PR fixes the reported bug. There might be more enhancements or rewrites for the whole SSL implementation but I think those can be addressed in a separate issue.

**Comment by PettitWesley** [comment]
We still ultimately need a fully upstream solution to this problem.

**Comment by nokute78** [comment]
#4100 is merged into master.
#4584 is for v1.8.x and it is not merged yet.
