### ISSUE TITLE
Cannot start service in Docker container

### ISSUE THREAD

**Issue by KellyBennett** [fluent/fluent-bit#4115]
## Bug Report

**Describe the bug**
I'm unable to run fluent-bit from within an ubuntu Docker container

**To Reproduce**
- Example log message if applicable:
```
td-agent-bit: unrecognized service
```
- Steps to reproduce the problem:

To reproduce the issue yourself, start a container with this Dockerfile definition to reproduce the error:
```
FROM amd64/ubuntu:18.04
RUN apt update && apt install sudo -y
RUN sudo apt install -y gnupg
RUN sudo apt install -y wget
RUN sudo wget -qO - http://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
RUN sudo echo 'deb https://packages.fluentbit.io/ubuntu/bionic bionic main' >> /etc/apt/sources.list
RUN sudo apt update
RUN sudo apt install -y td-agent-bit
CMD ["sudo", "service", "td-agent-bit", "start"]
```
This Dockerfile just automates the steps from https://docs.fluentbit.io/manual/installation/linux/ubuntu so you don't have to do the install manually. If you do all the steps manually, you get the same outcome.

Everything works until the step where you start the td-agent-bit service, at which point you get the message
`td-agent-bit start: unrecognized service`

**Expected behavior**
Expect td-agent-bit service to start

**Comment by nokute78** [comment]
I think there is no symlink at /etc/init.d .
`ln -s /opt/td-agent-bit/bin/td-agent-bit /etc/init.d/td-agent-bit` is needed.

```Dockerfile
FROM amd64/ubuntu:18.04
RUN apt update && apt install sudo -y
RUN sudo apt install -y gnupg
RUN sudo apt install -y wget
RUN sudo wget -qO - http://packages.fluentbit.io/fluentbit.key | sudo apt-key add -
RUN sudo echo 'deb https://packages.fluentbit.io/ubuntu/bionic bionic main' >> /etc/apt/sources.list
RUN sudo apt update
RUN sudo apt install -y td-agent-bit
RUN ln -s /opt/td-agent-bit/bin/td-agent-bit /etc/init.d/td-agent-bit
CMD ["sudo", "service", "td-agent-bit", "start"]
```

**Comment by KellyBennett** [comment]
@nokute78 Thanks for the response. I'm a bit confused by the need for a symlink to something on my computer. I'm going to be having this Docker container running in a cloud service, how can I be required to have a sim link to `/opt/td-agent/bin/td-agent-bit` ?

**Comment by charlessensibill** [comment]
I am having this exact same challenge with td-agent v4 and the symlink did not seem to work for me, or maybe I am using it wrong for td-agentv4. 

I get `td-agent: unrecognized service` from the below Dockerfile and I've been on this for days now. Any help will be deeply appreciated

```bash
FROM    node:16-bullseye-slim

RUN     apt-get update && apt-get -y install sudo
RUN     adduser --disabled-password chalu --uid 9001 --gecos '' --home /home/chalu --shell /bin/bash
RUN     adduser chalu sudo
RUN     echo '%chalu ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ARG     DEBIAN_FRONTEND=noninteractive
RUN     apt-get update \
        && apt-get install -y ca-certificates-java \
        && update-ca-certificates -f \
        && apt-get -qq update \
        && apt-get install -q --yes software-properties-common

RUN     apt-get -y install curl procps
RUN     curl -fsSL https://toolbelt.treasuredata.com/sh/install-debian-bullseye-td-agent4.sh | sh


ENV     APP_HOME /home/chalu/api
RUN     mkdir -p $APP_HOME

COPY    start.js /home/chalu/api/start.js
# RUN     ln -s /opt/td-agent/bin/td-agent /etc/init.d/td-agent

USER    root
CMD     ["sudo", "service", "td-agent", "start"]
```
