### ISSUE TITLE
I can not transform JSON parser  

### ISSUE THREAD

**Issue by KKulishov** [fluent/fluent-bit#4118]
## I can not transform JSON parser  

Colleagues, can you tell me.
Trying to parse docker log via Fluent Bit  (v1.8.7) 

Here is an example of log output  docker json.log 
`{"log":"{ orderID: 12345, shopperName: Test test, TestEmail: test@example.com }\r\n","stream":"stdout","time":"2021-09-23T06:35:09.774585192Z"}`

Here is my example config
```
[SERVICE]
    Flush     1
    Log_Level info
    parsers_file /etc/td-agent-bit/parsers.conf
    plugins_file plugins.conf

[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On

[INPUT]
    Name   tail
    Path /var/lib/docker/containers/0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548/0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548-json.log
    Tag    test.*
    Parser       docker

[OUTPUT]
    Name   stdout
    Match  test.*

[OUTPUT]
    Name            es
    Host            10.130.0.28
    Port            9200
    Match           test.*
    Logstash_Format On
    Logstash_Prefix front-test
    Type            logs
    Include_Tag_Key On
    Tag_Key         tag
```

start Fluent Bit
`/opt/td-agent-bit/bin/td-agent-bit -c td-agent-bit.conf
`

so he outputs to me:

`[0] test.var.lib.docker.containers.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548-json.log: [1632379182.880928157, {"log"=>"{ orderID: 12345, shopperName: Test test, TestEmail: test@example.com }
", "stream"=>"stdout", "time"=>"2021-09-23T06:39:42.880928157Z"}]
`
but at the docks https://docs.fluentbit.io/manual/pipeline/parsers/json  

it is specified what it should output
`[1154103724, {"key1"=>12345, "key2"=>"abc"}] `

in my case, it should be something like this:
`[1632379182.880928157,  {“orderID”=> “12345”, “shopperName”=>”Test test”}]`

can you tell me what my mistake is. You just need to add json objects to elasticsearch, but it only adds them this way
`
log    { orderID: 12345, shopperName: Test test, TestEmail: test@example.com }
`
And I need json objects to be entered

`orderID 	 12345
 shopperName  Test test 
 TestEmail    test@example.com`
 
 Tried to do through https://docs.fluentbit.io/manual/v/1.0/parser/decoder
 
 ```
  [PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
    Decode_Field_As    json        log  try_next
    Decode_Field_As    escaped_utf8     log
 ```
but still gives
`
[0] test.var.lib.docker.containers.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548-json.log: [1632381118.693428313, {"log"=>"{ orderID: 12345, shopperName: Test test, TestEmail: test@example.com }
`

Can you help with this problem?

**Comment by novegit** [comment]
have a look to "Merge_Log" option in the kubernetes filter. This will add the fields from json formatted logmessages into new field "log_json":
[FILTER]
    Name                kubernetes
    Match               generic-kubernetes.*
    Kube_URL            https://kubernetes.default.svc.cluster.local:443 
    Merge_Log           On
    Merge_Log_Key       log_json
    Keep_Log            Off
    K8S-Logging.Parser  Off
    Kube_Tag_Prefix     test.var.lib.docker.containers.

**Comment by KKulishov** [comment]
@novegit thanks, but this example doesn't work. You can check it yourself

```
[SERVICE]
    Flush     1
    Log_Level info
    parsers_file /etc/td-agent-bit/parsers.conf
    plugins_file plugins.conf

[INPUT]
    Name tail
    Path /var/lib/docker/containers/0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548/0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548-json.log
    Tag test.*
    Parser test

[OUTPUT]
    Name   stdout
    Match  test.*

[OUTPUT]
    Name            es
    Host            10.130.0.28
    Port            9200
    Match           test.*
    Logstash_Format On
    Logstash_Prefix front-test
    Type            logs
    Include_Tag_Key On
    Tag_Key         tag

```
```
[PARSER]
    Name        test
    Format      json
    Time_Key    time       Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
    Decode_Field_As   json         log try_next
    Decode_Field_As   escaped      log
```
docker stdout
```
echo {"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z"} >> /proc/1/fd/1
```
fluentbit stdout
```
[0] test.var.lib.docker.containers.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548-json.log: [1632403686.138536748, {"log"=>"{key1: 12345, key2: abc, time: 2006-07-28T13:22:04Z}
", "stream"=>"stdout", "time"=>"2021-09-23T13:28:06.13830673Z"}]
```

log docket json
`{"log":"{key1: 12345, key2: abc, time: 2006-07-28T13:22:04Z}\r\n","stream":"stdout","time":"2021-09-23T13:28:06.13830673Z"}
`

**Comment by KKulishov** [comment]
@novegit sorry
the problem is on my side, during debugging

docker stdout
`echo {\"orderID\": 12345, \"key1\": \"test\"} >> /proc/1/fd/1`

then fluentbit stdout
`[0] test.var.lib.docker.containers.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548.0018421b1122c9380811af6cf215137e000d3f7b1d00028f4f4990d21a8fc548-json.log: [1632406081.992868910, {"log"=>{"orderID"=>12345, "key1"=>"test"}, "stream"=>"stdout", "time"=>"2021-09-23T14:08:01.992540896Z"}]
`
this is how it works

**Comment by KKulishov** [comment]
@novegit thanks for the help
