### ISSUE TITLE
Conan Package

### ISSUE THREAD

**Issue by Parcley** [fluent/fluent-bit#4121]
I am picking up on an already closed issue (https://github.com/fluent/fluent-bit/issues/3962)

Conan is the de-facto package manager for C++ (https://docs.conan.io/en/latest/) and fluentbit could benefit from offering a conan package:
Developers could easily retrieve the fluentbit conan package and integrate fluentbit as a library into their own projects within minutes.

Is this something you are interested in or do you disagree with my idea?

I vote for providing a conan package. If @SteRoh and me are not the only ones who see a use-case for a conan-package I might even try to provide a conan-recipe.

As an alternative, it is possible to create a conan-package without directly committing to this repository: The conan- recipe can be located at https://github.com/conan-io/conan-center-index and the recipe will download the fluentbit sources from the fluentbit repo. The created conan packages will be uploaded to conan center.

**Comment by agup006** [comment]
@Parcley @SteRoh I'm +1 if you want to create a conan-package outside of the repo and then us linking some docs on getting started / maybe a blog as well. 

I don't think we would have enough folks within the fluent community to maintain.
