### ISSUE TITLE
Escape hell - record key is missing first letter

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#414]
Linking https://github.com/fluent/fluentd/issues/1736

>50% that the issue is in fluentbit.

(@edsiper please feel free to close if inappropriate. I see this on 0.12.4. Today I will update to .0.12.7 and will provide feedback.)

**Comment by edsiper** [comment]
per your comments on fluent/fluentd#1736:

```
For now, I can't reproduce. Will provide you the logs. I have them actually. For now I can say that the escapes probably don't come from in_forward. But are somehow created while processing in fluentd
```

are you OK with closing this issue on Fluent Bit side ?

**Comment by epcim** [comment]
sure, close
