### ISSUE TITLE
[out_pgsql] Add schema support

### ISSUE THREAD

**Issue by itajaja** [fluent/fluent-bit#4141]
reopening https://github.com/fluent/fluent-bit/issues/2233 by @sxd, this would be very useful, and should be not too difficult to add. any comment on feasibility from the team?

**Comment by sxd** [comment]
Yes indeed is something useful! since you detected that and pointed me that out I can actually put this a high priority on my tasks =) will work and you will have news soon

**Comment by itajaja** [comment]
ha! amazing @sxd! appreciated
