### ISSUE TITLE
Logstash Prefix without date possible?

### ISSUE THREAD

**Issue by alyabievgy** [fluent/fluent-bit#4144]
I want to set up index rotation in elastic using Index Lifecycle Policies. The problem is that the date in the index name gets in the way. How can I prevent it from being added in my configuration?

output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     2
        tls             On
        tls.verify      Off
        Logstash_Prefix logging
        Logstash_Prefix_Key $kubernetes['labels']['app']
        Trace_Error On
        Logstash_DateFormat   %Y.%m
        Workers         2

**Comment by alyabievgy** [comment]
My crunch atm:

Logstash_DateFormat %C

**Comment by zhuzhiyang** [comment]
i  have save problem!

**Comment by 12monkey12** [comment]
Your problem solved my problem
