### ISSUE TITLE
Clean-up and document cross-compilation

### ISSUE THREAD

**Issue by jan-hudec** [fluent/fluent-bit#4149]
**Is your feature request related to a problem? Please describe.**

I tried cross-compiling fluent-bit to our armv7a box and struggled to get over two issues:

1. I had problems getting Onigmo to compile (see also #3754). Reading the build files revealed that I need to add `-DHOST=`*target-triplet*.
2. I had to disable Luajit. I found I need to provide `-DCROSS_PREFIX` to the compiler prefix, but then it fails to cross-compile from 64-bit target to a 32-bit one anyway.

**Describe the solution you'd like**

1. Unfortunately CMake does not seem to have a standard variable for the target triplet, so it should be documented.
  - The `.bb` file suggests adding `-DGNU_HOST` instead, but the option that produces gets overridden; the `.bb` files probably don't work any more.
2. If `CMAKE_CROSSCOMPILING` is set, which *is* a standard variable, it would be nice if the main `CMakeLists.txt` tried to guess the needed values, or at least aborted with an error if they are not provided.
  - For gcc it can be obtained by executing `${CMAKE_C_COMPILER} -dumpmachine`)
  - For clang there `-target` option is set with `CMAKE_C_COMPILER_TARGET`, so that value can be used *if* set.
  - If the target (well, host) platform is 32-bit and the build is 64-bit, the `HOST_CC=gcc -m32` suggested by the luajit makefile could be guessed and added for building the luajit project.

**Additional context**

I am considering adding fluent-bit to our embedded Linux boxes to enable customized log processing. So I created a package definition for ptxdist, and had to hunt for combination of options that compiles. If it ends up being used, we may need Yocto definitions too as we target several different platforms (and they are being added and removed over time).

**Comment by jan-hudec** [comment]
… maybe should be a bug on https://github.com/fluent/fluent-bit-docs (too?)

**Comment by SarimMuqeet** [comment]
Hi @jan-hudec, I am currently also having to disable LuaJIT for my buildroot project. Were you able to find a way to enable it for your ARM64 or a workaround to still use the Lua filters on your device? My project builds fine and even works on my device when I disable LuaJIT (although I can't use Lua filters) but once I enable it, I start seeing errors for multiple header files not found, and I was wondering if you experienced something similar?
