### ISSUE TITLE
default format `out_file` of file output plugin is not recognized

### ISSUE THREAD

**Issue by planetmarshall** [fluent/fluent-bit#4152]
## Bug Report

Fluent-bit fails if a file plugin is used where the default format `out_file` is specified explicitly.

### Steps to reproduce

Create a config file with the following content:

```
[INPUT]
  Name cpu
  Tag my_cpu

[OUTPUT]
  Name file
  Match *
  Path /data
  Format out_file 
```

Run fluent-bit
```
docker run -v $(pwd):/data docker.io/fluent/fluent-bit:1.8.7 /fluent-bit/bin/fluent-bit -c /data/fluent.conf
```

### Expected results

Logs should be written to the `my_cpu` file in the current folder

### Actual results

Fluent-bit exits with the following message:

```
[2021/10/02 18:10:11] [error] [output:file:file.0] unknown format out_file. abort.
[2021/10/02 18:10:11] [error] [output] failed to initialize 'file' plugin
[2021/10/02 18:10:11] [ info] [input] pausing cpu.0
[2021/10/02 18:10:11] [error] [lib] backend failed
```

### Workaround

Omit the format specification in the configuration file. According to the [Documentation](https://docs.fluentbit.io/manual/pipeline/outputs/file) - `out_file` is the default.

**Comment by nokute78** [comment]
Thank you for reporting.
I sent a patch #4153
