### ISSUE TITLE
A way to determine start time of fluent-bit service startup?

### ISSUE THREAD

**Issue by jbhilton11** [fluent/fluent-bit#417]
I'm able to tell in the output logs the time at which the service starts up. However, is there a way through configuration to figure out that same time?

**Comment by edsiper** [comment]
besides log file or through querying systemd there is no way at the moment. 

what's your specific use-case where uptime is required ?

**Comment by jbhilton11** [comment]
Yes, it would be where uptime is required. Just need to make sure the log forwarder is alive.

**Comment by jbhilton11** [comment]
I was curious if there has been any further thought on this issue?

**Comment by edsiper** [comment]
The uptime information has been implemented through e3c938d0, it's available through the Monitoring Rest Interface, docummented here:

https://docs.fluentbit.io/manual/configuration/monitoring#rest_api

the changes are merged in GIT master and will be available also in the next release of 0.14 series. 

thanks again.
