### ISSUE TITLE
Installation of td-agent-bit via Debian repos is not possible

### ISSUE THREAD

**Issue by fsperling** [fluent/fluent-bit#4181]
## Bug Report

**Describe the bug**
The doc (https://docs.fluentbit.io/manual/installation/linux/debian#debian-9-stretch) says to use the following repo url:
deb https://packages.fluentbit.io/debian/stretch stretch main

However I get 403 forbidden:
```
$ curl -I  https://packages.fluentbit.io/debian/stretch/
HTTP/1.1 403 Forbidden
Server: nginx/1.18.0 (Ubuntu)
Date: Tue, 12 Oct 2021 08:32:48 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
```

This error happens for all Debian versions.

**Expected behavior**
td-agent-bit packages can be installed via the td-agent debian repo.

**Comment by AlbertoGODev** [comment]
I had the same problem from aws instances and solved it like this:
[https://aws.amazon.com/es/premiumsupport/knowledge-center/ec2-expired-certificate/](url)

**Comment by mrzor** [comment]
The repository still returns 403 reliably.

**Comment by edsiper** [comment]
The repositories are not open to being browsed, if you use APT it should be fine.
