### ISSUE TITLE
Log event too large: xxxxx bytes exceeds limit of 262144\n" Causes Fluentbit to silently stop sending log events

### ISSUE THREAD

**Issue by sarath-pillai** [fluent/fluent-bit#4203]
## Bug Report

**Describe the bug**
We have observed multiple instances where fluentbit silently stops sending log events for some of our pods. The interesting aspect about this is that the fluentbit daemonset does not give any details about this. Basically it does not tell that it wont be sending newer events to cloudwatch. The only errors that we found in fluentbit logs are below. 

```
time="2021-09-29T11:08:39Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
time="2021-09-29T11:08:40Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
time="2021-09-29T11:08:44Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
time="2021-09-29T11:08:45Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
time="2021-09-29T11:08:49Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
time="2021-09-29T11:08:51Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
time="2021-09-29T11:08:52Z" level=error msg="[cloudwatch 0] InvalidParameterException: Log event too large: 298678 bytes exceeds limit of 262144\n"
```

Fixing this issue is simple. The moment we restart the POD, the issue is gone. Newly created PODs will resume sending log events to cloudwatch. 

The version we are using is amazon/aws-for-fluent-bit:2.7.0

**To Reproduce**
- Create a POD with lot of metadata
- Ensure the POD creates events that are bigger than Cloudwatch permitted limit after several successful events.
- See if the POD's latest events are appearing in cloudwatch. 

This is a bit difficult to reproduce, as we are not seeing this all the time. Its sporadic and happens intermittently. 

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: amazon/aws-for-fluent-bit:2.7.0, helm.sh/chart: aws-for-fluent-bit-0.1.7
* Configuration: The configmap used is below..
```
fluent-bit.conf: |
    [SERVICE]
        Parsers_File /fluent-bit/parsers/parsers.conf

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Parser            docker
        Docker_Mode       On
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Merge_Log_Key       data
        Buffer_Size         5MB
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [OUTPUT]
        Name                  cloudwatch
        Match                 *
        region                us-east-1
        log_group_name        /aws/eks/fluentbit-cloudwatch/logs
        log_stream_prefix     fluentbit-
        auto_create_group     true
```

* Environment name and version (e.g. Kubernetes? What version?): EKS kubernetes cluster(AWS). 1.18 version of kubernetes.
* Server type and version: AWS managed EKS agent nodes , more details below.
```
Kernel Version:             4.14.238-182.421.amzn2.x86_64
  OS Image:                   Amazon Linux 2
  Operating System:           linux
  Architecture:               amd64
```
* Operating System and version: see above.
* Filters and plugins: Mentioned above in the config map section

**Additional context**

**Comment by nokute78** [comment]
It may be better to report this issue to https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit at first.
In my understanding, `cloudwatch` plugin is above golang plugin.(`cloudwatch_logs` is supported on this repo)

The same log error was reported but it was already fixed. Hmm...
https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/issues/85
https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit/pull/98

**Comment by sarath-pillai** [comment]
Hi @matthewfala Thanks for your response.. I will try v2.21.0 and let you know how that goes..

**Comment by ckoredla** [comment]
@sarath-pillai Did it work when you updated to v2.21.0?
