### ISSUE TITLE
Experiencing "timestamp" too new for Loki output plugin.

### ISSUE THREAD

**Issue by mkenne11** [fluent/fluent-bit#4206]
## Bug Report

I am also experiencing the same error when trying to write the fluent-bit "loki" output plugin:
```
[2021/10/20 02:48:03] [error] [output:loki:loki.1] loki.netanalysis.svc.cluster.local:3100, HTTP status=400 Not retrying.
entry for stream '{job="network"}' has timestamp too new: 2021-10-20 13:48:03 +0000 UTC
```

I am using the standard fluent-bit container build on docker hub (v1.8.8). I believe the problem is because the time on the fluent-bit container is using UTC (Greenwich time) and the label passed uses my local time i.e. UTC +11:00.

See my loki output plugin config:
```
    [OUTPUT]
        Name          loki
        Match         syslog.*
        Host          loki.netanalysis.svc.cluster.local
        Port          3100
        labels        job=network_analysis
```
This seems similiar to issue #3876.

My environment setup is:
- 2 node Rpi cluster running Ubuntu 21.04.3 64-bit
- k3s v1.21.5+k3s1
- Latest version of the fluent-bit container (v1.8.8)

**Comment by robin850** [comment]
Hello,

Just a tiny message in case that can help anyone, I had the exact same problem, and fixed it using:

~~~yaml
pipeline_stages:
    - regex:
        expression: '...'
    - timestamp:
        source: ...
        format: RFC3339Nano
~~~

(Source: [here](https://stackoverflow.com/a/65405840/2663959))

**Comment by mkenne11** [comment]
Thanks @robin850 I will give it a try :)

**Comment by sujairamprasathc** [comment]
@robin850 The config you have posted is for Promtail, not FluentBit

**Comment by digital88** [comment]
If you are writing logs in non-UTC format, specify Time_Offset in parser settings. I had same problem and Time_Offset fixed it.
