### ISSUE TITLE
Using Filters to send logs to mutltiple outputs

### ISSUE THREAD

**Issue by X013983** [fluent/fluent-bit#4209]
Im using FluentBit with EKS Fargate
https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html#fargate-logging-troubleshooting

and im trying to send logs to multiple outputs, however, INPUT is not supported in Fargate. 
What I would like to do is to use a FILTER to route logs that contain a phrase to go to one output, and another FILTER that contains a different phrase to go to a different output.

Is something like this possible?

**Comment by novegit** [comment]
yes, look to the rewrite_tag filter: https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag
