### ISSUE TITLE
rewrite_tag "could not compose tag" with slashes around variable

### ISSUE THREAD

**Issue by kc8421** [fluent/fluent-bit#4212]
## Bug Report

**Describe the bug**
I have been trying to utilize tags to build reasonable path for azure_blob output. In most cases they do work, but when trying to form string that is having values from certain record fields, it doesn't seem to work with slashes. Slash before and/or after variable is causing error. Without slashes variables in tag are being formed as expected.

Workaround can be developed with lua filter, but would be nice to have this working to reduce amount of custom scripts.

**To Reproduce**
```
[FILTER]
    name                rewrite_tag
    match               iis*
    rule                $datetime "^(\d{2}-\d{2}-\d{2}) (\d{2}):" "forward.iis/$application_name/$1/$1.$2.$application_name.$hostname.log" true
    emitter_name        re_emitted_iisforward

Example input for this filter:
{
    "hostname": "COMPUTERNAME",
    "datetime": "2020-06-12 02:56:42",
    "log": "2020-06-12 02:56:42 10.17.199.69 58688 10.17.196.41 443 HTTP/1.1 GET /status - 503 1 Disabled WsAPI",
    "filename": "httperr25.log",
    "application_name": "WsAPI"
}
```

**Expected behavior**
With given examples expected tag would be following:
```
forward.iis/WsAPI/2020-06-12/2020-06-12.02.WsAPI.COMPUTERNAME.log
```

**Actual behavior**
Fluent Bit 1.8.8 with log_level debug
```
[2021/10/21 20:16:44] [error] [record accessor] bad input character '/' at line 33554500
[2021/10/21 20:16:44] [error] [lib] backend failed
[2021/10/21 20:16:44] [error] [record accessor] syntax error, unexpected '$', expecting $end at '$application_name/$1/$1'
[2021/10/21 20:16:44] [error] [filter:rewrite_tag:rewrite_tag.13] could not compose tag: forward.foo/$application_name/$1/$1.$2.$application_name
[2021/10/21 20:16:44] [error] Failed initialize filter rewrite_tag.13
```

Fluent Bit 1.6.10 with log_level debug
```
[2021/10/21 20:18:33] [error] [sp] bad input character '/' at line 33554500
[2021/10/21 20:18:33] [error] [lib] backend failed
[2021/10/21 20:18:33] [error] [record accessor] syntax error, unexpected '$', expecting $end at '$application_name/$1/$1'
[2021/10/21 20:18:33] [error] [filter:rewrite_tag:rewrite_tag.13] could not compose tag: forward.foo/$application_name/$1/$1.$2.$application_name
```

**Environment**
* td-agent-bit-1.8.8-win64 zip package
* td-agent-bit-1.6.10-win64 zip package
* Windows 10 Pro (19043.1288)

**Comment by ethinx** [comment]
https://github.com/fluent/fluent-bit/issues/604#issuecomment-717780827

**Comment by sshipway** [comment]
I'm wanting to do this (so that we can replace rsyslog entirely with fluent)
```
[FILTER]
    name rewrite_tag
    match app
    rule $timestamp ^(....)-(..)-(..)T app/$source_site/$1/$2/$3/app.log false
[OUTPUT]
    name file
    format plain
    path /var/logs/fluent/
    match app/*
    mkdir true
```

We have way too many different logs, and keep them for way too many days, for us to throw the whole lot into the same directory.  Using Lua to make a temporary field to hold the path is ugly and computationally expensive when there log stream is so full.

A workaround is to use
```
    rule $timestamp ^(....)-(..)-(..)T app/$source_site./$1./$2./$3./app.log false
```
but this is ugly as well.  It does not make sense to me that other non-alphanumerics are not accepted as delimiters.

**Comment by m17kea** [comment]
For anyone finding themselves here, as per the [docs](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor), the only acceptable character after a $ expression seems to be a '.'
