### ISSUE TITLE
Skip_Empty_Lines in Tail doesn't work

### ISSUE THREAD

**Issue by Albelt** [fluent/fluent-bit#4215]
version: 1.8
deployment: kubernetes  
image:   fluent/fluent-bit:1.8
problem: `Skip_Empty_Line` seems doesn't work in input plugin Tail
my config file: 
``` 
[INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
        Refresh_Interval  10
.......

[OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
```
record in elasticsearch:
``` 
  "_source": {
    "@timestamp": "2021-10-22T02:49:09.952Z",
    "log": "\n",
    "time": "2021-10-22T02:49:09.952519448Z",
    "kubernetes_pod_name": "accountservice-7766f4b7bf-nv9xf",
    "kubernetes_namespace_name": "backend",
    "kubernetes_host": "k8s-node2-238"
  }
```
the `log` field of some records is '\n', shouldn't it be skip by this configuration?

**Comment by avizen-j** [comment]
I have encountered the same issue. Sharing in case someone else is trying to figure out what is happening.

`Skip_Empty_Lines` works only for `LF` empty lines, so in case you are running container on windows and while testing you manually create "log", your empty line will contain `CR LF` which is ignored by this setting.

`CR LF` case:
![image](https://github.com/fluent/fluent-bit/assets/54904772/1db9b102-5ac6-4cc0-8730-76c238179d43)

`LF` case:
![image](https://github.com/fluent/fluent-bit/assets/54904772/a5e0f7f3-1b3b-424c-8693-f83262c720bf)

Result:
![image](https://github.com/fluent/fluent-bit/assets/54904772/7c4d3fa4-4744-49fb-9457-e6c3be3fdecc)


Config just for the reference:
```
[INPUT]
    Name tail
    Skip_Empty_Lines On
    Path /app-logs/*

[OUTPUT]
    Name stdout
```
