### ISSUE TITLE
Fluent Bit restart or unexpected VM shutdown can lose logs

### ISSUE THREAD

**Issue by kc8421** [fluent/fluent-bit#4225]
## Bug Report
As far as I know, Fluent-bit should write data into a filesystem if the service has storage.path defined and input's storage.type is the filesystem. However, there is no clear documentation of what should happen when service is being stopped, but few existing issues have been suggesting that it should flush buffer into the filesystem with proper configuration. There is in documentation mention about each plugin taking care of their state and mention that tail is one of the best examples in that. One [issue](https://github.com/fluent/fluent-bit/issues/2274) did target only Linux version and therefore not sure if it's comparable to this case and decided to create new issue.

For example, tail input does have a DB parameter that does write the state of files and their offsets into the SQLite database. If I have one tail input, no filters, and one forward output (see reproduce) where output endpoint is not accessible, offset for each file being read is set to end of the file if buffer can ingest all the read data from files. It is not a problem when service is up and running if having an infinite amount of retries in output, but when you stop the service (or server loses power)… in-memory data is being lost and the next startup seems to care only about the tail's database and its offsets.

Should Fluent Bit be able to continue processing/sending records that were left behind when the stop command did occur or after whole server did lost its power?

**To Reproduce**
```
[SERVICE]
    flush        5
    grace        17
    daemon       Off
    storage.path            C:\ProgramData\Fluent-bit\storage
    storage.max_chunks_up   1024
    storage.checksum        on
    storage.sync            full

[INPUT]
    name                tail
    path                C:\temp\logs\input\**\*.log
    db                  C:\ProgramData\Fluent-bit\fluent-bit.db
    buffer_chunk_size   1MB
    buffer_max_size     1MB
    read_from_head      true
    refresh_interval    20
    path_key            filepath
    storage.type        filesystem

[OUTPUT]
    name                        forward
    host                        127.0.0.1
    port                        24224
    require_ack_response        true
    match                       *
    storage.total_limit_size    2048M
    retry_limit                 false
```
- Place some logs for tail
- Run with a configuration like above and make sure you do not have forward endpoint available in localhost
- Wait for at least one retry from the output plugin
- Stop Fluent Bit
- Make forward endpoint available in localhost
- Start Fluent Bit service and see if all logs have been pushed through forward output

**Expected behavior**
- All logs are being processed after service shutdown and start sequence has been completed and output endpoint is available.

**Your Environment**
- td-agent-bit-1.8.8-win64 zip package
- Windows 10 Pro (19043.1288)

**Additional context**
- https://github.com/fluent/fluent-bit/issues/2274
- I did also try with rewrite_tag and making its emitter_storage.type to filesystem. Same end result.
- I did also try with 1.6.10 version as 1.8.x versions does not work with azure_blob output, but apparently 1.6 doesn't support filesystem backend with Windows: `[cio] file system backend not supported`. [Documentation](https://docs.fluentbit.io/manual/v/1.6/administration/buffering-and-storage) doesn't say anything about restricted support.

**Comment by kc8421** [comment]
Still persists with the current 1.8.10 version.

**Comment by dalaomai** [comment]
I have the same problem too, is there a solution please?

**Comment by dalaomai** [comment]
I found that it may be related to docker deployment.`readdir()` This method cannot read the properties of the file mounted by docker.
