### ISSUE TITLE
tail + multiline.parser adds an extra carriage return to log message

### ISSUE THREAD

**Issue by sbouchex** [fluent/fluent-bit#4227]
## Bug Report

**Describe the bug**
I'm using the tail input with "multiline.parser" a followed:
```
      [INPUT]
                Name              tail
                Tag               iv.zk.*
                Path              /log/zookeeper.log
                DB                /var/log/fluentbit-zk.db
                multiline.parser      java
```

Every detected log message in the /log/zookeeper.log file is having a extra carriage return added. If I remove the "multiline.parser" option, everything is fine.

**To Reproduce**
- Steps to reproduce the problem:
Start zookeeper in a folder
Start fluentbit to parse zookeeper and output everything with the "output" filter.

The message looks like:

```
[114] iv.zk.log.zookeeper.log: [1635234691.652954641, {"log"=>"2021-10-26 07:50:40,113 [myid:1] - INFO  [NIOWorkerThread-2:NIOServerCnxn@514
] - Processing ruok command from /0:0:0:0:0:0:0:1:53768
", "node_name"=>"dev-sbo-telemetry-lnx8.iv.local", "application_name"=>"zookeeper", "
product_name"=>"ivt", "pod_name"=>"ivt-zk-0", "hostname"=>"ivt-zk-0"}] 
```

**Expected behavior**
The carriage return line should not be added

**Screenshots**

**Your Environment**

* Version used: 1.8.8
* Configuration:
* Server type and version: linux
* Operating System and version: CentOS 8
* Filters and plugins: tail + output

**Comment by dr3amville** [comment]
This is still happening, has anyone dealt with this or found a workaround?

`parsers.conf`
```
[MULTILINE_PARSER]
    Name          java_multiline
    Type          regex
    Flush_Timeout 1000
    Rule      "start_state"   "/^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\s+(?<host>[\w-]+)\s+(?<jar>[^\[]+)\[(?<pid>\d+)\]\s+(?<log_level>\w+)\s+\[(?<logger>[^\]]+)\]\s+\((?<thread>[^\)]+)\)\s+(?
<message>.+)$/" "cont"
    Rule      "cont"          "/^(?!\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}).*$/" "cont"

[PARSER]
    Name java
    Format regex
    Regex  /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\s+(?<host>[\w-]+)\s+(?<jar>[^\[]+)\[(?<pid>\d+)\]\s+(?<log_level>\w+)\s+\[(?<logger>[^\]]+)\]\s+\((?<thread>[^\)]+)\)\s+(?<message>.+)$/m
```

`fluent-bit.conf`
```
[INPUT]
    Name         tail
    Path         <logfile>
    Tag          <tag>
    multiline.parser       java_multiline

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser java

[OUTPUT]
    Name stdout
    Match *

[OUTPUT]
    Name         loki
    line_format  key_value
    Match        *
    Uri          /loki/api/v1/push
    Host         <host>
    Port         <port>
    Labels       job=fluent-bit
```

This always seems to append a newline/carriage return character to the end of each log line, and the example I used to create the multiline parser is based out of the documentation.

Example log line one (last part of stacktrace):
```
        [CIRCULAR REFERENCE:java.lang.IllegalStateException: Retries exhausted: 3/3]

"}]
```

Single line log:
```
[0] <logname>: [[1717074901.915522611, {}], {"time"=>"2024-05-30 13:15:01,461", "host"=>"unknown-host", "jar"=>"some.jar", "pid"=>"pidnum", "log_level"=>"WARN", "logger"=>"logger.className", "thread"=>"threadname-01", "message"=>"some UUID: connection closed
"}]
```

Sanitized the logs a bit but you can see the close of the message object is always adding a newline character.

**Comment by duj4** [comment]
@sbouchex @dr3amville have you found any solution for this? I met the same issue.

**Comment by dr3amville** [comment]
@duj4 Unfortunately I did not, I moved on to FluentD which doesn't have this issue. 🤷

**Comment by duj4** [comment]
@dr3amville Thanks for the update, then I have to open a new one for this issue.
