### ISSUE TITLE
Generate _id inside of ES output plugin to prevent log dupes

### ISSUE THREAD

**Issue by jsravn** [fluent/fluent-bit#423]
If a post to ES times out, and the ES plugin retries the message, it's possible to get duplicate log lines. An example where this is somewhat common is AWS ES which has a 60s limit on queries. In these cases, when under load, the query may time out but still proceed to be executed on the underlying ES cluster. If the client retries, the retried document will get a new `_id` generated and duplicate the previous document.

The solution is to generate a uuid in the `_id` field on the client side and ensure we reuse the `_id` on retries.

**Comment by agup006** [comment]
Looks like this functionality has been merged. Closing
