### ISSUE TITLE
Release Process Improvement Proposal: Strictly follow Semver, new cadence for minor versions

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#4235]
I want Fluent Bit to follow a more standard OSS release process similar to what many other projects follow. There would be three key parts to this.

### Strictly follow Semantic Versioning

https://semver.org/

Semantic Versioning is really nice for users, because they can determine their upgrade risk directly from the version numbers.

If you have a version, X.Y.Z:
* Bumping X means we made some major backwards breaking change. Ideally we never do this.
* Bumping Y means there are new features
* Bumping Z means there are bug fixes/patches only

Today we don't follow this strictly. For example, 1.8.7 added net new features on top of 1.8.6, not just bug fixes: https://fluentbit.io/announcements/v1.8.7/

If we followed SemVer strictly, new features would only come out in new minor version- 1.8.0, 1.9.0, etc

### Monthly cadence for minor versions

If we follow SemVer, then new features can only be released in minor version bumps. This means we need to increase the frequency of minor version releases. My proposal is that they have a monthly cadence

### Backport patches to at least one previous minor version

Some users stick on Fluent Bit versions for a decent time period; only a few folks upgrade to the latest immediately. While a full LTS guaranteed release might be a vendor specific thing, I think the community can work to support previously released minor versions for at least two months. This means we would always be actively patching 2 series at a time. 

Let's explain this via an example. Say that November introduces 1.9.0 (1.9 series), and December introduces 1.10.0 (1.10 series).

On December 24th, the latest 1.9.x version is 1.9.4 and the latest in the 1.10 series is 1.10.1, and a major bug is found and fixed that affects both.

In this case, the community performs 2 patch releases: 1.9.5 and 1.10.2

I think this should not a be big burden for the maintainers; we already always patch the latest series, now we'd just be additionally back-porting those fixes to the last minor version series as well. Since we'd be doing minor versions much more frequently. Currently we do minor versions roughly once per quarter, and do patches (and some new features) for 3 months. In the new model, patches are only added to series for 2 months.

**Comment by lubingfeng** [comment]
@edsiper  based on what we discussed two weeks, what is the next step?

**Comment by edsiper** [comment]
As stated in the meeting my comments are:

- Flexible SemVer
  - On a fixed series (e.g: 1.8.x) do not perform breaking or invasive changes, stability overall
  - If a maintainer from X company want's to enhance or extend it "plugin" it's ok. They assume responsibility for the changes.
- Backporting fixes 
  - Once a new major version is out (e.g: 1.9), the "past" series like "1.8" will receive critical bug fixes over the period of 6-8 weeks maximum. The changes will be available on the affected branch, the new version will be tagged but __no__ packaging will be performed.

**Comment by PettitWesley** [comment]
@edsiper Thanks. With which version series will we start this practice? 1.9?

**Comment by edsiper** [comment]
I think it should be now with v1.8.x, no need to delay it

**Comment by lubingfeng** [comment]
If we are adoption semversion for FluentBit v1.8.x and above, we can close this issue.
