### ISSUE TITLE
SIGSEGV at startup when a rewrite_tag filter has no Match

### ISSUE THREAD

**Issue by smckay-signifyd** [fluent/fluent-bit#4246]
## Bug Report

**Describe the bug**
SIGSEGV at startup when a rewrite_tag filter has no Match, like when Match_Regex is in use. Bug was introduced by 191f7fb, `is_wildcard()` doesn't null check.

- Steps to reproduce the problem:
start up fluent bit with a config that has a rewrite_tag filter with no Match, such as:
```
[FILTER]
    Name               rewrite_tag
    Match_Regex        traefik\..*
    Rule               $BackendName .*  traefik.access.logs false
    Rule               $RouterName .*  traefik.access.logs false
```

**Expected behavior**
No SEGV

**Your Environment**
git 09473749ec724d50fb12ef707f6d136d7816c3ca

**Comment by nokute78** [comment]
@smckay-signifyd Oops, thank you for pointing it.

I sent a patch #4261 to fix this issue.
