### ISSUE TITLE
[flb_network] DNS auto retry (Timeout while contacting DNS servers) 🌐

### ISSUE THREAD

**Issue by matthewfala** [fluent/fluent-bit#4257]
**Is your feature request related to a problem? Please describe.**

Some Fluent Bit users are experiencing DNS timeout errors every now and then which lead to log loss. The current solution is to set retry_limit to a value above 2, as proposed by @ssplatt and @PettitWesley. This however may be too broad of a solution to address transient DNS errors. See https://github.com/aws/aws-for-fluent-bit/issues/253#issuecomment-954934306

**Describe the solution you'd like**

A cleaner solution than having DNS failure fail the entire request would be to add a DNS retry on DNS timeout directly to the DNS lookup method.

This could be implemented with a for loop around the `ares_getaddrinfo()` and timer block here https://github.com/fluent/fluent-bit/blob/231ef4b38f312eb981583d8f1c2441f7313f128d/src/flb_network.c#L941 The condition could be `result_code == ARES_ETIMEOUT` [From here](https://github.com/matthewfala/fluent-bit/blob/666b93b22ccd5eb428639c2fa4e7547a4e41cf8b/lib/c-ares-809d5e84/include/ares.h#L114) Corresponding to your error message [here](https://github.com/matthewfala/fluent-bit/blob/666b93b22ccd5eb428639c2fa4e7547a4e41cf8b/lib/c-ares-809d5e84/src/lib/ares_strerror.c#L37)

**Describe alternatives you've considered**

This issue could also be mitigated with:
1. DNS caching
- very difficult to do and not recommended by developers online.

2. Configurable DNS retry
- This may be overkill to have people specify a DNS retry limit, since most people would probably want DNS to be retried.

**Additional context**

**Comment by matthewfala** [comment]
It appears the DNS timeout was introduced as a fairly highlevel design decision (not part of the unix api response) 2 months ago in [this commit](https://github.com/fluent/fluent-bit/pull/4018/commits/4bd9eee403c67f734aaf50a1adef274346baecfd).
[Here](https://github.com/fluent/fluent-bit/pull/4018/commits/4bd9eee403c67f734aaf50a1adef274346baecfd#diff-59d9305c29b68398d2602ac5fb8a6b824ea6df0faf5ac800187b747ee35855d1R677) is the line that sets the timeout error which is invoked when the DNS [lookup timer](https://github.com/fluent/fluent-bit/pull/4018/commits/4bd9eee403c67f734aaf50a1adef274346baecfd#diff-59d9305c29b68398d2602ac5fb8a6b824ea6df0faf5ac800187b747ee35855d1R957) times out

~~One design flaw may be that the timer times out based on connect_timeout [Here](https://github.com/matthewfala/fluent-bit/blob/03c6b0508cc66fa97d76cfcbc4f63e314d92d39e/src/flb_network.c#L1079) That means that if some one sets flb_upstream u->net.connect_timeout to something unreasonably small which previously works for their connection timeout use case but is too short a time for the DNS lookup (in some cases) the DNS might be prone to failure. I'm thinking maybe the DNS lookup timeout needs to be separate from connect_timeout with its own default value for backwards compatibility.~~

Actually it doesn't seem like anyone is setting the `connect_timeout` other than AWS credential provider services(which don't use dns?). The default value is [10s](https://github.com/matthewfala/fluent-bit/blob/03c6b0508cc66fa97d76cfcbc4f63e314d92d39e/src/flb_network.c#L109) which seems reasonably high. Not sure what the DNS lookup behavior was before this commit, when a DNS call would take more than 10 seconds.

**Comment by PettitWesley** [comment]
> other than AWS credential provider services(which don't use dns?).

The STS and EKS providers do use DNS since they have to find the STS service.

**Comment by matthewfala** [comment]
I see. The sts connect timeout which is set to [FLB_AWS_CREDENTIAL_NET_TIMEOUT](https://github.com/matthewfala/fluent-bit/blob/794a3d9b96d4c86f28e73e50f487af87c6c44272/include/fluent-bit/flb_aws_credentials.h#L35) is also a generous value - 5 seconds. Not apparent that this would be a problem.

**Comment by matthewfala** [comment]
Seems like most DNS problems are a byproduct of other fluent bit issues, and not really a DNS resolution failure. Seeing less DNS related problems lately and can close this.
