### ISSUE TITLE
v1.8.9 throughput dropped a lot

### ISSUE THREAD

**Issue by wubn2000** [fluent/fluent-bit#4269]
## Bug Report

**Describe the bug**
By using latest v1.8.9, my throughput is dropped from 15k/s(using 1.8.2, 1.8.8) to only 7-8k/s with same configuration and same type of machine. My log contains mixed single line and multi line messages and each message is about 1.5K bytes. Usually I have 1000 files for fluent bit to monitor and in total they receive 15k/s incoming messages.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by edsiper** [comment]
would you please provide your full configuration and repro case ?

**Comment by edsiper** [comment]
not an issue, 1.8 did not support multi-threading for golang plugins. handled internally.
