### ISSUE TITLE
Fluentbit does not store logs on filesystem when kafka output is down

### ISSUE THREAD

**Issue by merveyilmaz-netrd** [fluent/fluent-bit#4280]
## Bug Report

**Describe the bug**
 Hi, I am new on Fluentbit and still trying to understand the working process. I use tail plugin and read logs from file and then try to forward logs to kafka output. I am working on product enviroment so if an output fails i should not lose any data and store them to filesystem. So i am using filesystem buffering.  When using filesystem buffering on splunk and elastic search outputs, if these outputs fail(for example  elasticsearch service does not work), fluentbit stores data chunks in the filesystem. However, this is not done in kafka, as far as I understand kafka puts these chunks in a queue. But after restart kafka service i see that some of logs are missing.

 I have a bash script that generates log and logs are contain counter value. I stopped kafka.service when counter value is 635 and after a while i re-started the kafka service and run the consumer. As you can see below the logs between 635-3853 is missing. I want to see all data.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:
  Setting retry_limit parameter to false.

**Expected behavior**
store data chunks on filesystem and sent them after output plugin is available. 

**Screenshots**
<img width="567" alt="log_60000" src="https://user-images.githubusercontent.com/82662465/140314902-adc71ee6-6239-4b25-a445-77a4fbfe11c3.PNG">

**Your Environment**

* Version used: 1.8.8
* Configuration:  here is my configuration file:
[INPUT]
    Name  tail
    path  /var/log/fail_es.log
    Tag   tail_log
    storage.type filesystem
[OUTPUT]
    Name        kafka
    Match       tail_log
    Brokers     192.168.56.103:9092
    Topics      last_topic
    timestamp_key @timestamp
    queue_full_retries 0
    Retry_Limit False

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: CentOS Linux release 7.9.2009 (Core)
* Filters and plugins: tail and kafka plugin

**Additional context**

**Comment by danlenar** [comment]
@merveyilmaz-netrd 

Try increasing rdkafka.message.timeout.ms.
I believe the default is 5 minutes, so if kafka can't deliver message successfully in under 5 minutes, it will give up and drop those records.

**Comment by merveyilmaz-netrd** [comment]
> @merveyilmaz-netrd
> 
> Try increasing rdkafka.message.timeout.ms. I believe the default is 5 minutes, so if kafka can't deliver message successfully in under 5 minutes, it will give up and drop those records.

Thanks, i tried to set rdkafka.message.timeout.ms to 0. I stopped kafka.service for 3 hours. I did not lose any data but i have concerns. Is it okay to set this parameter to 0?  I searched but i did not find any info about that

**Comment by tiagokrebs** [comment]
I've seen this problem recently in my environment too. My scenario is pretty much the same, a log tail with output to Kafka. During the last maintenance, the Kafka cluster went down 30 minutes, the events read by FluentBit in this period were not produced on the topic.  

As I can see just `Retry_Limit False` doesn't solve this problem right?

@merveyilmaz-netrd about your question, the [librdkafka configuration](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) says this
> rdkafka.message.timeout.ms
Local message timeout. This value is only enforced locally and limits the time a produced message waits for successful delivery. A time of 0 is infinite. This is the maximum time librdkafka may use to deliver a message (including retries). Delivery error occurs when either the retry count or the message timeout are exceeded. The message timeout is automatically adjusted to transaction.timeout.ms if transactional.id is configured.  

Two things to consider here:
- Yes, you can use zero, but Kafka has timeouts on its side too ,`transaction.timeout.ms` and `transactional.id`. If your requests take longer than this the broker will terminate the connection.
- The retry is not the same as the FluentBit retry but the producer retry (when you define `rdkafka.retries`). Normally this is used only with `enable.idempotence` set to true.

If you solve this in some way please let us know.

**Comment by vikasmishra17** [comment]
Facing the same issue, fluentbit is not storing any logs on filesystem, when Kafka is down.

[INPUT]
    Name tail
    Path /var/log/syslog
    Tag  syslogs-kafka
    DB  /etc/td-agent-bit/db/syslog-kafka-latest.db
    DB.locking true
    DB.sync full
    Refresh_Interval 10
    Rotate_Wait      5
    storage.type     filesystem
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size   5MB
    Mem_Buf_Limit     100MB

[OUTPUT]
    name  kafka
    match syslogs-kafka
    brokers  XX.XX.XX:9092
    topics   syslogs-test
    Retry_Limit false
    queue_full_retries 2
    rdkafka.request.timeout.ms 0
    rdkafka.linger.ms 500
    rdkafka.log.connection.close true
    rdkafka.message.max.bytes 41943040
    rdkafka.metadata.max.age.ms 5000
    rdkafka.queue.buffering.max.kbytes 100000
    rdkafka.request.required.acks 1
    rdkafka.security.protocol plaintext
    rdkafka.socket.keepalive.enable true
