### ISSUE TITLE
Respect OpenSSL error messages

### ISSUE THREAD

**Issue by aytekinar** [fluent/fluent-bit#4289]
## Bug Report

`fluent-bit` does not respect the error messages that `openssl` reports when checking the private key.

### Actual Behavior

I had a flawed configuration file as follows (note the typo in `tls.crt_tile`):

```ini
[OUTPUT]
  Name              forward
  Host              fluentd
  Port              24224
  tls               on
  tls.debug         4
  tls.verify        on
  Self_Hostname     fluentbit
  tls.ca_file       /etc/fluentbit/ca.crt
  tls.crt_tile      /etc/fluentbit/fluentbit.crt
  tls.key_file      /etc/fluentbit/fluentbit.key
```

which resulted in the following error message:

```cmd
[2021/11/07 15:34:11] [error] [tls] private_key '/etc/fluentbit/fluentbit.key' and password don't match
```

Clearly, the reason is _not_ the password mismatch, and I needed to compile `fluent-bit` from a modified branch to reveal the actual OpenSSL error message. Only then, I could realize that something was wrong with my certificate file, and hence, I could notice the stupid typo in my configuration.

### Expected Behavior

Much like the other checks in function `tls_context_create`, the output of `SSL_CTX_check_private_key` should also be forwarded to the user (in case of erroneous outputs) properly. If done properly, the following OpenSSL error message would be forwarded to the user:

```cmd
error:140A80B1:SSL routines:SSL_CTX_check_private_key:no certificate assigned
```

Currently, any exit code other than `1` is [assumed to be a password mismatch](https://github.com/fluent/fluent-bit/blob/v1.8.9/src/tls/openssl.c#L265), which is wrong [per the documentation](https://www.openssl.org/docs/man1.1.1/man3/SSL_check_private_key.html).

**Comment by aytekinar** [comment]
Remove the `stale` label.

**Comment by Ostromix** [comment]
fluent bit [error] [tls] private key and password don't match
but key is not protected by password at all!
