### ISSUE TITLE
kubernetes filter memory leak in metadata cache

### ISSUE THREAD

**Issue by jsravn** [fluent/fluent-bit#430]
As far as I can tell the metadata cache grows indefinitely. This is problematic:
1. cache key is `namespace:podname`.
2. As pods are continually being deployed this cache will grow larger and larger.
3. Memory use will grow unbounded with the number of pods seen by fluent-bit over time.
4. Metadata lookup will become slower and slower as the table fills up.

Ideally it should be setting a hard limit on the number of cache entries and removing old entries.

**Comment by jsravn** [comment]
Took a stab at this in https://github.com/fluent/fluent-bit/pull/431 - let me know your thoughts. Lots of ways to tackle it.

**Comment by edsiper** [comment]
Fixed by #431.
