### ISSUE TITLE
POD Annotations Multilines parser not found

### ISSUE THREAD

**Issue by Christophe73** [fluent/fluent-bit#4322]
## Bug Report

**Describe the bug**
I'm using POD annotation for fluent-bit parser.
It works with a single parser, but failed with a multilines parser ( not found ).

**To Reproduce**

- Annotate the POD with the parser name : 

```
kind: Pod
apiVersion: v1
metadata:
  name: zookeeper-2
  generateName: zookeeper
  namespace: kafka
  annotations:
    fluentbit.io/parser: kafka
```

- Create a multiline parser config : Failed
```
    [MULTILINE_PARSER]
        Name kafka
        Type regex 
        Flush_timeout 5000
        # Regex rules for multiline parsing
        # ---------------------------------
        # configuration hints:
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        # rules |   state name  | regex pattern                  | next state
        # ------|---------------|--------------------------------------------        
        rule      "start_state"   "/^\[(?<level>\w*)\]\s(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\s\[(?<thread>.*)\]\s(?<message>.*)$/"  "cont"
        rule      "cont"          "/^.*/"                     "cont"
```

- Create a Single line parser config : Works
```
    [PARSER]
        Name kafka
        Format regex 
        Regex  "^\[(?<level>\w*)\]\s(?<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\s\[(?<thread>.*)\]\s(?<message>.*)$" 
```

**Expected behavior**

Parser found.

**Screenshots**

Fluent-bit logs : 
[2021/11/12 14:56:41] [ warn] [filter:kubernetes:kubernetes.0] annotation parser 'kafka' not found (ns='kafka' pod_name='zookeeper-2', container_name='zookeeper')

**Your Environment**
* Version used: Fluent-bit 1.8.9 deployed with Helm Chart fluent-bit-0.19.2 
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):  Kubernetes 1.19.7
* Server type and version: N/A
* Operating System and version: Ubuntu 20.04
* Filters and plugins:

**Additional context**

**Comment by DrissiReda** [comment]
I also have the same issue ! The multiline feature has been expected for a while so it'd be nice if we could enable it for custom parsers. In a kubernetes cluster, it's expected to have a lot of parsers...

**Comment by DrissiReda** [comment]
Can this be reopened? I still have the same issue.

**Comment by hsharrison** [comment]
Same here, would love a way to set a multiline parser via annotation.
