### ISSUE TITLE
Fluentbit does not send logs to Elastic search

### ISSUE THREAD

**Issue by merveyilmaz-netrd** [fluent/fluent-bit#4330]
## Bug Report

**Describe the bug**
I have script that generates 60 mb logs per minute and i am trying to send these logs to elastic search output. I am using filesystem buffering. I saw that fluentbit store the data chunks on filesystem but it could not send these logs to elastic search. When i try to restart td-agent-bit service i saw below logs. It seems that fluentbit trying to send logs. 

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=121 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=122 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=123 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=124 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=125 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=126 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task]   task_id=127 still running on route(s): es/es.0
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ info] [task] storage_backlog/storage_backlog.1 has 0 pending task(s):
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [trace] [engine] flush enqueued data
Nov 16 13:27:16 104-1 td-agent-bit: [2021/11/16 13:27:16] [ warn] [engine] service will stop in 5 seconds
Nov 16 13:27:21 104-1 td-agent-bit: [2021/11/16 13:27:21] [ info] [engine] service stopped
Nov 16 13:27:21 104-1 td-agent-bit: [2021/11/16 13:27:21] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.

```
- Steps to reproduce the problem:
Changing memory limit which does not work.

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.8.9
* Configuration: 
/etc/td-agent-bit/td-agent-bit.conf:
[SERVICE]
    Flush     5
    Daemon    off
    Log_Level trace
    HTTP_Server on
    HTTP_Listen 127.0.0.1
    HTTP_Port 2020
    storage.path /var/log/flb-storage
    storage.sync normal
    storage.backlog.mem_limit 1GB
@INCLUDE es.conf

/etc/td-agent-bit/es.conf

`[INPUT]
    Name  tail
    Path  /var/log/log_files/log_file1
    Tag   es_logs
    storage.type filesystem
    Mem_Buf_Limit 500MB

[OUTPUT]
    Name  es
    Match es_logs
    Host  XX.XXX.XXX.XXX
    Port  9200
    Index logs-fluentbit
    Type  my_type
    Trace_Error On
`
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: Centos7.9
* Operating System and version:Centos7.9
* Filters and plugins: No filter. Es and tail plugin.

**Additional context**

**Comment by bartlomiejdanek** [comment]
@merveyilmaz-netrd this one might be related to https://github.com/fluent/fluent-bit/issues/4273#issuecomment-962521166

**Comment by merveyilmaz-netrd** [comment]
> @merveyilmaz-netrd this one might be related to [#4273 (comment)](https://github.com/fluent/fluent-bit/issues/4273#issuecomment-962521166)

I tried to increase mem_buf_limit to 2 gb but result is same. Fluentbit does not send logs to Elasticsearch.

**Comment by bartlomiejdanek** [comment]
@merveyilmaz-netrd could you try the previous version 1.8.8?

**Comment by merveyilmaz-netrd** [comment]
> @merveyilmaz-netrd could you try the previous version 1.8.8?

Thank you so much. It works with 1.8.8 version. I guess the problem is related to 1.8.9

**Comment by zhaoyuepj** [comment]
It also happens from v1.7.9.

**Comment by zhaoyuepj** [comment]
It also happens from 1.7.9.
Example log message if applicable:
{"log":"[2021/12/02 11:11:44] [ info] [input] tail.0 resume (mem buf overlimit)\n","stream":"stderr","time":"2021-12-02T03:11:44.232101427Z"}
{"log":"[2021/12/02 11:11:44] [ warn] [input] tail.0 paused (mem buf overlimit)\n","stream":"stderr","time":"2021-12-02T03:11:44.280592546Z"}
{"log":"[2021/12/02 11:11:44] [engine] caught signal (SIGTERM)\n","stream":"stderr","time":"2021-12-02T03:11:44.58866573Z"}
{"log":"[2021/12/02 11:11:44] [ info] [input] pausing tail.1\n","stream":"stderr","time":"2021-12-02T03:11:44.588688135Z"}
{"log":"[2021/12/02 11:11:44] [ info] [input:tail:tail.1] flushing pending multiline data...\n","stream":"stderr","time":"2021-12-02T03:11:44.588692042Z"}
{"log":"[2021/12/02 11:11:44] [ info] [input] pausing tail.2\n","stream":"stderr","time":"2021-12-02T03:11:44.588695184Z"}
{"log":"[2021/12/02 11:11:44] [ info] [input] pausing tail.3\n","stream":"stderr","time":"2021-12-02T03:11:44.588698081Z"}
{"log":"[2021/12/02 11:11:44] [ info] [input] pausing tail.4\n","stream":"stderr","time":"2021-12-02T03:11:44.58870105Z"}
{"log":"[2021/12/02 11:11:44] [ info] [input] pausing tail.5\n","stream":"stderr","time":"2021-12-02T03:11:44.588703823Z"}
{"log":"[2021/12/02 11:11:44] [ warn] [engine] service will stop in 5 seconds\n","stream":"stderr","time":"2021-12-02T03:11:44.592936388Z"}
{"log":"[2021/12/02 11:11:49] [ info] [engine] service stopped\n","stream":"stderr","time":"2021-12-02T03:11:49.234906277Z"}
{"log":"[2021/12/02 11:11:49] [ warn] [engine] shutdown delayed, grace period has finished but some tasks are still running.\n","stream":"stderr","time":"2021-12-02T03:11:49.234916199Z"}
{"log":"[2021/12/02 11:11:49] [ info] [task] tail/tail.0 has 1179 pending task(s):\n","stream":"stderr","time":"2021-12-02T03:11:49.234920103Z"}
{"log":"[2021/12/02 11:11:49] [ info] [task]   task_id=53 still running on route(s): forward/forward.0 \n","stream":"stderr","time":"2021-12-02T03:11:49.234923449Z"}
...
...
{"log":"[2021/12/02 11:11:54] [ info] [task]   task_id=1435 still running on route(s): forward/forward.0 \n","stream":"stderr","time":"2021-12-02T03:11:54.242825104Z"}
{"log":"[2021/12/02 11:11:54] [ warn] [engine] service will stop in 5 seconds\n","stream":"stderr","time":"2021-12-02T03:11:54.242827852Z"}

**Comment by merveyilmaz-netrd** [comment]
> > @merveyilmaz-netrd could you try the previous version 1.8.8?
> 
> Thank you so much. It works with 1.8.8 version. I guess the problem is related with 1.8.9

Actually when we are trying to send around 100 mb data per minute it fails and accumulated the data in the file system.
