### ISSUE TITLE
Unable to automatically create a Kafka topic longer than 64 characters

### ISSUE THREAD

**Issue by aseev-xx** [fluent/fluent-bit#4337]
## Bug Report

**Describe the bug**
An attempt to start writing to a topic with a name greater than 64 characters is impossible due to a direct limitation in the code.
https://github.com/fluent/fluent-bit/blob/master/plugins/out_kafka/kafka.c#L221-L225

```
[2021/11/17 15:37:06] [ warn]  dynamic kafka topic length > 64 not allowed
[2021/11/17 15:37:15] [ warn]  dynamic kafka topic length > 64 not allowed
[2021/11/17 15:37:21] [ warn]  dynamic kafka topic length > 64 not allowed
[2021/11/17 15:37:23] [ warn]  dynamic kafka topic length > 64 not allowed
```

**To Reproduce**
You must enable the automatic creation of topics (auto.create.topics.enable=true) and try to write to a topic with a name exceeding 64 characters

**Expected behavior**
According to the documentation, the length of the topic name should not exceed 249 characters. Therefore, it seems correct to support such a possibilityю

https://kafka.apache.org/documentation/:
"Each sharded partition log is placed into its own folder under the Kafka log directory. The name of such folders consists of the topic name, appended by a dash (-) and the partition id. Since a typical folder name can not be over 255 characters long, there will be a limitation on the length of topic names. We assume the number of partitions will not ever be above 100,000. Therefore, topic names cannot be longer than 249 characters. This leaves just enough room in the folder name for a dash and a potentially 5 digit long partition id."

**Your Environment**
Reproduced in all versions

**Additional context**
If such a restriction is not accidental and is not planned to be changed, I would like to hear a detailed answer for what this was done, since this would at least help us to write a specific patch for ourselves that removes this restriction

**Comment by mickymiek** [comment]
Hi,
Does someone has an answer? This issue is still relevant event with fluentbit latest version. The limit should be equal to kafka one, or is there something else to consider?

I'm willing to contribute this change if needed.

**Comment by mickymiek** [comment]
I see. If this get no answer we'll consider forking/patching this as well, but such a quick (and necessary) fix should normally be in main branch rather quickly.

**Comment by patrick-stephens** [comment]
I would say the best thing here is to send a PR - we rely on contribution for OSS so if you have a patch then it helps both us and you to get it merged.
