### ISSUE TITLE
How to use in_systemd_plugin

### ISSUE THREAD

**Issue by wst-casd** [fluent/fluent-bit#434]
I want to collect log messages from the Journald daemon on Linux environments, and I find that the Systemd/Journald input plugin has been developed. Yesterday, I got the latest source code from Github. But when I try to use that input plugin, the fluent-bit.conf is as flowing:
/---------------------------------------------------------------------------------/
[INPUT]
    Name systemd
    Path /home/xh/Desktop/logdata/journal/*
    Tag  k8s-system

[OUTPUT]
    Name  stdout
    Match *
/---------------------------------------------------------------------------------/

I got the following error log:

/---------------------------------------Error------------------------------------------/
Input plugin 'systemd' cannot be loaded
/---------------------------------------------------------------------------------/

So I try to find out why got this, I find that 
     1.  fluent-bit.c     
                   /* Create configuration context */
                   config = flb_config_init();

     2.  flb_config.c  
                   /* Register plugins */
                   flb_register_plugins(config);

     3.   flb_plugin.h
     
The flb_plugin.h is produced during compling period according to flb_plugin.h.in.
During the compling, I got this 
/---------------------------------------------------------------------------------/
-- Could NOT find Journald (missing: JOURNALD_LIBRARY JOURNALD_INCLUDE_DIR) 
/---------------------------------------------------------------------------------/

then I further to find that in Findjournal.cmake
/----------------------------------------------------------------------------------------------------/
find_package(PkgConfig)
pkg_check_modules(PC_JOURNALD QUIET systemd)

/----------------------------------------------------------------------------------------------------------/

In fact，I find that the package pkg-config is existed , so find_package(PkgConfig) is true.

If I use pkg_check_modules(PC_JOURNALD REQUIRED systemd),  I find the systemd are existed.
/----------------------------------------------------------------------------------------------------------/
-- Checking for module 'systemd'
--   Found systemd, version 229
/----------------------------------------------------------------------------------------------------------/
 And the PC_JOURNALD_FOUND ia assigned 1. But PC_JOURNALD_CFLAGS_OTHER, PC_JOURNALD_INCLUDEDIR, PC_JOURNALD_INCLUDE_DIRS, PC_JOURNALD_LIBDIR and PC_JOURNALD_LIBRARY_DIRS are not assigned. 

My OS is Ubuntu 16.04. The cmake version is 3.9.4. The pkg-config version is 0.29.1. The systemd version is 229. 

So I hope someone can tell me how to do, if I want to use in_systemd_plugin. Thanks very much!

**Comment by nokute78** [comment]
Do you install a header of systemd ? (e.g. systemd-devel in CentOS)
libsystemd-dev may help to build.

**Comment by wst-casd** [comment]
Thanks very much，I will make sure whether or not a header of systemd have been installed and have a try of libsystemd-dev.

**Comment by wst-casd** [comment]
@nokute78   @edsiper   Thanks, I install the libsystemd-dev on my os and alter  pkg_check_modules(PC_JOURNALD QUIET systemd) to pkg_check_modules(PC_JOURNALD QUIET libsystemd),  then solve the problem.
