### ISSUE TITLE
Log drop issue in Tail plugin 1.7.1 version

### ISSUE THREAD

**Issue by Yadumathur** [fluent/fluent-bit#4351]
## Bug Report

**Describe the bug**
We have a K8 set up where the fluent bit is running as DS, we are seeing a log drop issue, and later on debugging we did observe the logs getting dropped just after INPUT config tail plugin, we did STDOUT after INPUT and validated the number of events on both ends.

- Steps to reproduce the problem:
We are using 1.7.1 version and our INPUT config is as below

[INPUT]
Name tail
Path /var/log/containers/.log
Tag kube.
Parser docker
Skip_long_lines true
Docker_Mode On
Refresh_Interval 2
Ignore_older 1s
Rotate_Wait 5s
Buffer_Chunk_Size 10k
Buffer_Max_Size 15k
Mem_Buf_Limit 5G

after the INPUT we are directly doing [FILTER] to STDOUT and doing events count to source files

**Expected behavior**
There should be an equal no of log events from source and STDOUT

**Your Environment**

* Version used: 1.7.1
* Configuration: DaemonSet on K8
* Environment name and version (e.g. Kubernetes? What version?): K8 

**Additional context**
We could replicate the issue by increasing the load and seeing a drop of 50% and more just after tail but when we revert 1.6.10 we do not see the issue as much. There is still a log loss but which can handled better by changing buffer sizes.
I can see a bug on Ignore_older not working as expected #3873 in tail plugin which is kind of working in 1.6.10

We have a theory on high load this could be an issue with less buffer size ? Is this a known issue or any findings which I can look into ?

**Comment by kc-dot-io** [comment]
I am also seeing this with containerd. Have tried removing Ignore_Older as well as downgrading to 1.6.x to 1.8.x

I have increased resource thresholds as well but the issue doens't seem to be a load bearing issue to me as we're seeing it even on low volume systems repeatedly but inconsistently.

**Comment by Yadumathur** [comment]
@kc-dot-io how are you doing the analysis? 

We are comparing a number of events after the Input plugin vs the source file and observe it happens just after load starts to increase.
