### ISSUE TITLE
Please, provide Fluentbit's packages for Fedora

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit#4356]
Hello.
I've followed these instructions: https://docs.fluentbit.io/manual/installation/linux/redhat-centos but I get this error (which seems related to some bad system's libraries' linking):

![fluentbit-fedora](https://user-images.githubusercontent.com/7274874/142744692-c6f2224a-76f9-4507-b281-11ef6ae74245.png)

Thanks!

**Comment by nokute78** [comment]
@edsiper 
FYI: Amazon Linux 2022 will be based on Fedora.
I think we will need to support Fedora.
https://github.com/amazonlinux/amazon-linux-2022#benefits-of-amazon-linux-2022

**Comment by gavenkoa** [comment]
Please review what is required by `td-agent-bit`:

```
sudo dnf repoquery --requires --resolve td-agent-bit
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
bash-0:4.4.20-1.el8_4.x86_64
compat-openssl10-1:1.0.2o-3.el8.x86_64
cyrus-sasl-lib-0:2.1.27-5.el8.x86_64
glibc-0:2.28-151.el8.i686
glibc-0:2.28-151.el8.x86_64
libgcc-0:8.4.1-1.el8.x86_64
libpq-0:13.3-1.el8_4.x86_64
systemd-libs-0:239-45.el8_4.3.x86_64
zlib-0:1.2.11-17.el8.x86_64
```

I use RHEL subscription. In Fedora's EPEL there is `fluent-bit` package but many features are disabled:

```
%cmake\
    -DCMAKE_BUILD_TYPE=RelWithDebInfo\
    -DFLB_EXAMPLES=Off\
    -DFLB_OUT_SLACK=Off\
    -DFLB_IN_SYSTEMD=On\
    -DFLB_OUT_TD=Off\
    -DFLB_OUT_ES=Off\
    -DFLB_SHARED_LIB=Off\
    -DFLB_TESTS_RUNTIME=On\
    -DFLB_TESTS_INTERNAL=Off\
    -DFLB_RELEASE=On\
    -DFLB_DEBUG=Off\
    -DFLB_TLS=On
```

so I have to use upstream build instead of EPEL package.
