### ISSUE TITLE
Log entries with same timestamp get shipped to loki in random order.

### ISSUE THREAD

**Issue by maaltan** [fluent/fluent-bit#4363]
## Bug Report

**Describe the bug**
Log entries with same timestamp get shipped to loki in random order.

**To Reproduce**
* Set up a mock docker log file that includes several log entries with same docker timestamp.  ex:
```
{"log":"YOUR LOG MESSAGE HERE(before)","stream":"stdout","time":"2018-06-11T14:37:29.000000000Z"}
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"YOUR LOG MESSAGE HERE2","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"YOUR LOG MESSAGE HERE3","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"YOUR LOG MESSAGE HERE4","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
{"log":"YOUR LOG MESSAGE HERE(after)","stream":"stdout","time":"2018-06-11T14:37:31.000000000Z"}
```
* (Probably optional/unrelated)  Set up a multiline block in this log file and the appropriate parsers.
*  Parse the time out of the docker log and ship the events to loki and  (optional) file outputs.

**Expected behavior**
Log entries are reported to loki in the same order as in the original file.

**Screenshots**
N/A

**Your Environment**
* Version used:  fluent-bit 1.8.9, loki 2.3.0, grafana 8.2.3
* Configuration:  See below
* Environment name and version:  Rancher/RKE kubernetes v2.5.8 
* Server type and version: Vsphere VM
* Operating System and version: k8s host os is Centos 7 in various configurations/ minor version.  container OS: various.
* Filters and plugins:  
  * INPUT:  tail
  * filters:  multiline, grep, modify, kubernetes
  * parsers: regex and multiline regex
  * Output:  Loki (and file for troubleshooting.)

**Additional context**
I am trying to set up a logging stack for a custom application with very unique log format.   I have been trying to set up multiline logging and works for the most part, but i noticed that every once in a while the records appear to show up in random order in loki/grafana which breaks the multiline parse.  While troubleshooting this i noticed this is occuring for non-parsed lines as well.   The only thing that appears to be the same is that the nanosecond timestamp is identical between the affected records.

Some of the unfortunate quirks of this application is:
* It loads the entire log entry in a string buffer in memory and dumps the entire record to file in one disk operation.  This means that the adjacent docker log entries'  timestamps are much more  likely to have the same timestamp.
* Some of these log blocks are thousands of lines and/or thousands of characters longs.   (I thought maybe the chunking was screwing stuff up for these large logs but i've increased tail's chunk size and chunk buffer size to 10MB and behavior is unchanged.) 
* While these long log entries are the most likely to be affected,  extremely short entries get out of order as well.
* If i activate the file output the records get recorded in the correct order, but the long entries still get split.

The primary purpose of this bug report is to discuss the "same timestamp loki order" problem, but I would appreciate some suggestions on how to bypass the large log block splitting problem as well if it turns out to be unrelated.

--------------
Addendum:  The timestamp docker is using reports nanoseconds, but the granularity of the timestamps seem to be more around the order of miliseconds.  When adjacent docker log entries do not have the same timestamp they are several hundred thousand nanoseconds apart.  This fits my expectations of the linux time APIs behaved in the past so didn't think to mention it immediately.   Is there maybe a flag i should be setting somewhere that would enable true NS granularity?  I think this problem would still occur, but be much less likely.

**Comment by bharatazmera** [comment]
@maaltan I have a question. Did you initially face any issue of missing logs in Loki with the same time stamp?

**Comment by maaltan** [comment]
I had some missing logs, but I believe that was caused my things wrong in my parser regex causing labels to be null or malformed.  At that point In time I was parsing the timestamp out of the log text which only had second granularity.  I am thinking in that case it was overwriting records because all the labels and timestamp we're identical.
