### ISSUE TITLE
Record Accessor not recognize key that contains special characters

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#4370]
## Bug Report

**Describe the bug**
Record Accessor not recognize key that contains special characters, e.g. `logging.googleapis.com/severity`
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/record-accessor

**To Reproduce**
fluentbit.conf
```
[INPUT]
    name   tail
    path   lines
    Read_from_Head true
[FILTER]
    name   modify
    add    logging.googleapis.com/severity INFO
    match  *
[FILTER]
    name     grep
    match    *
    exclude  logging.googleapis.com/severity INFO
[OUTPUT]
    name   stdout
    match  *
```
file: lines
```
bar
app
"wo":"ccc"
```
$ ./fluent-bit --config fluentbit.conf -v

**Additional context**
We try to exclude logs e.g. if the severity is info.

**Comment by nokute78** [comment]
Reopen this issue since the patch #4619 caused regression.

**Comment by luked-mappedin** [comment]
I am facing a similar issue with the record accessor selecting a key with `@` character (@timestamp in this case). Are there any known workarounds currently?

**Comment by vchirikov** [comment]
and record accessors with `@` doesn't work too.
cc: @edsiper

**Comment by Ch00k** [comment]
Same here. Record accessor is not recognizing `$fluentbit.es-index`

```
[OUTPUT]
    Name                opensearch
    Host                opensearch
    Index               $fluentbit.es-index
```
