### ISSUE TITLE
Infinite loop for `time string length is too long`

### ISSUE THREAD

**Issue by Tinche** [fluent/fluent-bit#4377]
## Bug Report

**Describe the bug**
I'm running Fluent Bit as a daemonset using the offical Helm chart on Kubernetes 1.21.

Sporadically, a Fluent Bit pod will start generating tons of errors that look like this:
```
[2021/11/28 23:08:02] [error] [parser] time string length is too long
[2021/11/28 23:08:02] [ warn] [parser:_ml_cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2021-11-28T23:08:02.628369631Z stderr F [2021/11/28 23:08:02] [ warn] [parser:_ml_cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2021-11-28T23:08:02.626780815Z'
```

When it happens, I restart the pod, it gets recreated and continues on working properly.

The date format in the error message cannot be parsed by the CRI parser, true (it contains nanoseconds). We don't log timestamps in our services though, so I guess this timestamp is generated by the container runtime? But only very sporadically?

The bigger issue is that this case seems to put Fluent Bit into a loop somehow. Is Fluent Bit attempting to parse this timestamp from its own error logs? In any case, the CPU use of the pod goes up 5x, and our logging database gets swamped with these errors.

**To Reproduce**
I'm unsure how to reproduce this. It happens about once a day for us, randomly.

**Expected behavior**
Fluent Bit doesn't generate large amounts of error messages.

**Screenshots**

**Your Environment**
* Version used: 1.8.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.21.4
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
The Helm values file being used:
```
image:
  tag: "1.8.9"

serviceMonitor:
  enabled: true

dashboards:
  enabled: true
  labelKey: grafana_dashboard
  annotations: {}

config:
  inputs: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        multiline.parser docker, cri
        Tag              kube.*
        Mem_Buf_Limit    50MB
        Skip_Long_Lines  Off
        Skip_Empty_Lines On
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
  outputs: |
    [OUTPUT]
        Name                es
        Match               kube.*
        Host                xxxx
        Port                443
        Logstash_Format     On
        Retry_Limit         False
        Time_Key            @timestamp
        Replace_Dots        On
        Logstash_Prefix     kubernetes_cluster
        Logstash_DateFormat %y-%m-%d-%H
        tls                 on
        tls.verify          on
        tls.debug           1
        Trace_Error         On
        Suppress_Type_Name  On
```

**Comment by sossickd** [comment]
The same happened when using the following helm values:

```yaml
image:
  tag: "1.8.9"

config:
  filters: |
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Merge_Log           On
      Merge_Log_Key       log_processed
      Merge_Log_Trim      On
      Keep_Log            On
      K8S-Logging.Parser  On
      K8S-Logging.Exclude On

    [FILTER]
      Name         nest
      Match        kube.*
      Operation    lift
      Nested_under kubernetes_annotations
      Add_prefix   kubernetes_annotations_
  inputs: |
    [INPUT]
      Name              tail
      Path              /var/log/containers/*.log
      multiline.parser  cri
      Tag               kube.*
      Skip_Long_Lines   On
      Buffer_Chunk_Size 32k
      Buffer_Max_Size   256k
      DB                /var/log/flb-storage/tail.db
      DB.Sync           normal
      storage.type      filesystem

    [INPUT]
      Name              systemd
      Systemd_Filter    _SYSTEMD_UNIT=docker.service
      Systemd_Filter    _SYSTEMD_UNIT=containerd.service
      Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
      Tag               host.*
      Strip_Underscores On
      DB                /var/log/flb-storage/systemd.db
      DB.Sync           normal
      storage.type      filesystem
  outputs: |
    [OUTPUT]
      Name  forward
      Match *
      Host  xxxxxxxxxxxxx
      Port  24224
  service: |
    [SERVICE]
      Daemon                    Off
      Flush                     1
      Log_Level                 info
      HTTP_Server               On
      HTTP_Listen               0.0.0.0
      HTTP_Port                 2020
      storage.path              /var/log/flb-storage/
      storage.sync              normal
      storage.checksum          off
      storage.max_chunks_up     128
      storage.backlog.mem_limit 16M
      storage.metrics           on
      Parsers_File              parsers.conf
      Parsers_File              custom_parsers.conf
dashboards:
  enabled: true
serviceMonitor:
  enabled: true

```

Unfortunately the final destination for the logs was expensive Azure storage which proved to be costly as the log ingestion went up 250 fold whilst fluent-bit was in this infinite loop.

We would like to use the multi-line cri parser but can't until this issue has been resolved.

**Comment by Protopopys** [comment]
Are there any updates?
I get the same error.

Fluent hangs and cyclically writes an error:
```
[2022/02/09 14:27:52] [ warn] [parser:_ml_cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2022-02-09T14:27:52.034027686+00:00 stderr F [2022/02/09 14:27:52] [ warn] [parser:_ml_cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2022-02-09T14:27:51.820848929+00:00'
[2022/02/09 14:27:52] [error] [parser] time string length is too long
```

Then there is a failure with an error:
```
[2022/02/09 16:24:53] [engine] caught signal (SIGSEGV)
#0  0x0                 in  ???() at ???:0
```

%Y-%m-%dT%H:%M:%S.%L%z **not** matches with 2022-02-09T14:27:52.034027686+00:00

%Y-%m-%dT%H:%M:%S.%L%:z matches with 2022-02-09T14:27:52.034027686+00:00  - https://www.strfti.me/?f=%25Y-%25m-%25dT%25H%3A%25M%3A%25S.%25L%25%3Az


Your Environment

- Version used: 1.8.12
- Configuration:
- Environment name and version (e.g. Kubernetes? What version?): Openshift v4.8.0+
- Server type and version:
- Operating System and version:
- Filters and plugins:

**Comment by Tinche** [comment]
Thanks!
