### ISSUE TITLE
Enable retries when using as a docker log driver

### ISSUE THREAD

**Issue by lktslionel** [fluent/fluent-bit#438]
Hi,
Please, Is there any plan, to support the following docker log driver options as fluentd does ? 
```
--log-opt fluentd-async-connect=true \
--log-opt fluentd-retry-wait=60s \
--log-opt fluentd-max-retries=1440
```  

These enable any containers forwarding logs to fluentd, to retry if fluentd  is down.

Thanks

**Comment by edsiper** [comment]
hi @lktslionel 

If I am not wrong you are referring to the "Fluentd Log Driver" that's part of Docker. That plugin aims to talk to Fluentd or Fluent Bit since both speak the "forward" protocol. 

Would you please clarify where you would like to see those options ?

**Comment by lktslionel** [comment]
HI,
You're right ! I mislead you with my question. This question is related to the docker fluentd plugin instead. 
Thanks for your answer.
