### ISSUE TITLE
infra: add x86 and amd64 dedicated builders.

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#4380]
* Allocate 2 dedicated machines using Equinix/Packet through the automation (https://github.com/calyptia/fluent-bit-infra/blob/main/terraform/machines.tf) 

* Create a cloud-init script to auto-register them in the fluent organization as builders.

* Tag them for later usage.

**Comment by patrick-stephens** [comment]
Resolved by https://github.com/calyptia/fluent-bit-infra/pull/23
