### ISSUE TITLE
object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value

### ISSUE THREAD

**Issue by isatfg** [fluent/fluent-bit#4386]
## Bug Report

**Describe the bug**
Im running fluent-bit to push logs from our kubenetes cluster to elasticsearch. However some application logs are not being pushed and have the following error 

> status":400,"error":{"type":"mapper_parsing_exception","reason":"object mapping for [kubernetes.labels.app] tried to parse field [app] as object, but found a concrete value"}}}

**To Reproduce**
Install fluent-bit helm chart (https://fluent.github.io/helm-charts/) on a k8s cluster and you will see the error.

**Expected behavior**
The logs should be pushed to Elasticsearch

**Your Environment**

* Version used: fluent-bit:1.8.10  / Elasticsearch 7.15.2 / 
* Configuration: I have kep the default values in the helm chart except for the Host and Port 
* Environment name and version Kubenetes 1.21

**Comment by novegit** [comment]
it an elasticsearch problem. It cant import msg to the index  with a field name as "normal string" and later as beginning of a nested field. 

msg with label app=app1                => elasticsearch string field 'app'
msg with label app.io.prometheus  => elasticsearch "nested field" app.io.prometheus

a filter renaming  labelname 'app' to 'app_' solves it.

**Comment by isatfg** [comment]
Can you please give me an filter renaming label name example.

**Comment by lichuan6** [comment]
You should set `Replace_Dots On` in the elasticsearch output, see more https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

**Comment by lichuan6** [comment]
Here is an example:

```
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           kongingress.log
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        TLS             On
        Logstash_Format On
        Logstash_Prefix logstash
        Replace_Dots    On
        Type            _doc
        Retry_Limit     2
```

**Comment by novegit** [comment]
we export the messages to kafka, and then import them to elasticsearch.

we rename label 'app' with a lua script like:
```
...
if msg.kubernetes.labels ~= nil  and msg.kubernetes.labels.app ~= nil then
   msg.kubernetes.labels.app_ = msg.kubernetes.labels.app
   msg.kubernetes.labels.app = nil
end
...
```

**Comment by isatfg** [comment]
I have tried the Replace_Dots    On  however the error persists. I know the issue is with pods with the label
`app: SOMETHING
`

not with something that has dots in the key

`k8s.app: SOMETHING
`

**Comment by novegit** [comment]
after enabling 'Replace_Dots', its only solved after a new index creation in elasticsearch. Messages with 'app' label will still run in the import issue. In that case you would need to rename "app" to "app_"

**Comment by shikharagarwal19** [comment]
I was facing the same issue, I was using >

- fluent-operator for fluent-bit ( v2.0.11 ) deployment
- opster/opensearch operator for opensearch( v2.3.0)  deployment. 

What I did, I used lua scrpipt mentions [here](https://github.com/fluent/fluent-bit/issues/1134#issuecomment-776614151) with some amendment. I used below lua script --> 

`

     function dedot(tag, timestamp, record)
        if record["kubernetes"] == nil then
            return 0, 0, 0
        end
        if (record["kubernetes"]["labels"]["app"] ~= nil and type(record["kubernetes"]["labels"]["app"]) ~= "table") then
          record["kubernetes"]["labels"]["app"] = {appName = record["kubernetes"]["labels"]["app"]}
        end

        dedot_keys(record["kubernetes"]["annotations"])
        dedot_keys(record["kubernetes"]["labels"])
        
        return 1, timestamp, record
    end

    function dedot_keys(map)
        if map == nil then
            return
        end
        local new_map = {}
        local changed_keys = {}
        for k, v in pairs(map) do
            local deslashed = string.gsub(k, "%/", "_")
            local dedotted = string.gsub(deslashed, "%.", "_")
            if dedotted ~= k then
                new_map[dedotted] = v
                changed_keys[k] = true
            end
        end
        for k in pairs(changed_keys) do
            map[k] = nil
        end
        for k, v in pairs(new_map) do
            map[k] = v
        end
    end
`


If you look closely I added a snippet before dedoting the keys, which is putting app as object. 


   ```
if (record["kubernetes"]["labels"]["app"] ~= nil and type(record["kubernetes"]["labels"]["app"]) ~= "table") then
      record["kubernetes"]["labels"]["app"] = {appName = record["kubernetes"]["labels"]["app"]}
    end
```

I created a lua filter with above lua script. 

And also I modified my opensearch output config to have below settings --> 

```
    writeOperation: upsert
    generateID: true
    replaceDots: true
```

This is it, the error goes away and I can see all my logs being delivered to opensearch successfully.
