### ISSUE TITLE
SIGSEGV in flb-rt-out_file test on arm32v7 architecture

### ISSUE THREAD

**Issue by bkircher** [fluent/fluent-bit#4395]
## Bug Report

**Describe the bug**
1.8.10 version receives a SIGSEGV on arm32v7 in runtime test `flb-rt-out_file`

**To Reproduce**
- Steps:
```
cmake\
    -DCMAKE_BUILD_TYPE=RelWithDebInfo\
    -DFLB_EXAMPLES=Off\
    -DFLB_OUT_SLACK=Off\
    -DFLB_IN_SYSTEMD=On\
    -DFLB_OUT_TD=Off\
    -DFLB_OUT_ES=Off\
    -DFLB_SHARED_LIB=Off\
    -DFLB_TESTS_RUNTIME=On\
    -DFLB_TESTS_INTERNAL=Off\
    -DFLB_RELEASE=On\
    -DFLB_DEBUG=Off\
    -DFLB_TLS=On
ctest
```
- Output:
```
19/35 Test #22: flb-rt-out_file ..................***Failed   14.00 sec
Test json_invalid...                            [ OK ]
Test json_long...                                 Test interrupted by SIGSEGV.
Test json_small...                              [ OK ]
Test format_csv...                              [ OK ]
Test format_ltsv...                             [ OK ]
Test format_invalid...                          [2021/12/06 11:56:45] [error] [lib] backend failed
```

**Your Environment**

* Version used: 1.8.10
* Configuration: Linux 32-bit armv7hl
* Filters and plugins: runtime

**Additional context**
Link to complete build output: https://kojipkgs.fedoraproject.org//work/tasks/2178/79642178/build.log

**Comment by patrick-stephens** [comment]
I'll see if this is reproducible with the staging build updates, I did add some missing dependencies so possibly related to those.

**Comment by patrick-stephens** [comment]
@bkircher are you cross-compiling or using a native arm32 host?

**Comment by patrick-stephens** [comment]
Seeing failures but no SIGSEGV with 1.8.11
```
      Start 23: flb-rt-out_file
23/37 Test #23: flb-rt-out_file ..................***Failed    8.05 sec
```
Ran this by tweaking the `Dockerfile` to do the tests:
```
$ git diff
diff --git a/dockerfiles/Dockerfile.arm32v7 b/dockerfiles/Dockerfile.arm32v7
index 5c161504..d776e3bb 100644
--- a/dockerfiles/Dockerfile.arm32v7
+++ b/dockerfiles/Dockerfile.arm32v7
@@ -45,6 +45,8 @@ RUN cmake -DFLB_RELEASE=On \
           -DFLB_TRACE=Off \
           -DFLB_JEMALLOC=On \
           -DFLB_TLS=On \
+          -DFLB_TESTS_RUNTIME=On\
+          -DFLB_TESTS_INTERNAL=Off\
           -DFLB_SHARED_LIB=Off \
           -DFLB_EXAMPLES=Off \
           -DFLB_HTTP_SERVER=On \
@@ -53,6 +55,7 @@ RUN cmake -DFLB_RELEASE=On \
           -DFLB_OUT_PGSQL=On ..
 
 RUN make -j $(getconf _NPROCESSORS_ONLN)
+RUN make test
 RUN install bin/fluent-bit /fluent-bit/bin/
```
Then run the build and test:
`docker build -t arm32-test --build-arg FLB_TARBALL=https://github.com/fluent/fluent-bit/archive/v1.8.11.tar.gz -f dockerfiles/Dockerfile.arm32v7 ./dockerfiles/`

**Comment by bkircher** [comment]
@patrick-stephens Hey, sorry for late response. Missed first notification somehow. 

> are you cross-compiling or using a native arm32 host?

Native. But, uh, I now see that my reproduce above looks wrong. There are probably some Fedora-specific build flags I totally forgot to mention. Sorry for that.

Let me try to get complete build logs and paste them here. (Above build logs have been garbage collected.)

**Comment by patrick-stephens** [comment]
Ah great, that'd be ideal to try to figure out.

**Comment by bkircher** [comment]
OK. The actual CMake command line was 
```
/usr/bin/cmake \
-S . \
-B redhat-linux-build \
-DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=/usr \
-DINCLUDE_INSTALL_DIR:PATH=/usr/include \
-DLIB_INSTALL_DIR:PATH=/usr/lib \
-DSYSCONF_INSTALL_DIR:PATH=/etc \
-DSHARE_INSTALL_PREFIX:PATH=/usr/share \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DFLB_EXAMPLES=Off \
-DFLB_OUT_SLACK=Off \
-DFLB_IN_SYSTEMD=On \
-DFLB_OUT_TD=Off \
-DFLB_OUT_ES=Off \
-DFLB_SHARED_LIB=Off \
-DFLB_TESTS_RUNTIME=On \
-DFLB_TESTS_INTERNAL=Off \
-DFLB_RELEASE=On \
-DFLB_DEBUG=Off \
-DFLB_TLS=On

```

The build can be seen here until it is GC'ed again: https://koji.fedoraproject.org/koji/taskinfo?taskID=80342438

Complete logs: [build.log](https://github.com/fluent/fluent-bit/files/7765528/build.log)

**Comment by patrick-stephens** [comment]
Is it still failing on 1.8.11?

**Comment by bkircher** [comment]
> Is it still failing on 1.8.11?

Yep. Attached build log is with 1.8.11.

**Comment by patrick-stephens** [comment]
OK, I'm sorting out some native builders so will investigate once we have those as seems to be specific to that. I'll re-attempt with your settings using the Docker build as well although if you can reproduce without needing a native host it would help.

**Comment by bkircher** [comment]
Yep, will do.  (Although, AFK for the next couple of days.)

**Comment by patrick-stephens** [comment]
Have you got details of the setup you did to the build machine as well?
