### ISSUE TITLE
http output plugin supports PUT request

### ISSUE THREAD

**Issue by gjp0609** [fluent/fluent-bit#4401]
**Is your feature request related to a problem? Please describe.**
http output plugin only support POST request.

**Describe the solution you'd like**
http output plugin supports PUT request.

**Describe alternatives you've considered**
None.

**Additional context**
I use a logging system only support PUT request to ingestion log

**Comment by lecaros** [comment]
Hey @gjp0609 
What's your use case?
What's the logging system you are using?
