### ISSUE TITLE
net.tcp_keepalive* not supported

### ISSUE THREAD

**Issue by mxmorin** [fluent/fluent-bit#4415]
## Bug Report

**Describe the bug**
Documentation at  https://docs.fluentbit.io/manual/administration/networking expose net.tcp_keepalive* params.
When setting these parameters to forward or tcp output, I got 

`[error] [config] tcp: unknown configuration property 'net.tcp_keepalive' . The following properties are allowed: net.dns.mode, net.keepalive, net.keepalive_idle_timeout, net.connect_timeout, net.source_address, and net.keepalive_max_recycle.`

Tested on version 1.7.7 and 1.8.10

**Comment by patrick-stephens** [comment]
This looks like a documentation bug so simplest option is to remove those from the docs for now, the features do not seem to exist that they refer to.

**Comment by patrick-stephens** [comment]
@agup006 probably want to remove this - I can do it if you prefer?

**Comment by lecaros** [comment]
Hi @mxmorin, since we don't currently support these settings, they have been removed from documentation.
Thanks for reporting it!
