### ISSUE TITLE
After docker stops the container, the logs uploaded to S3 will be lost. What is a good way to solve this problem

### ISSUE THREAD

**Issue by shaojielinux** [fluent/fluent-bit#4426]
After docker stops the container, the logs uploaded to S3 will be lost. What is a good way to solve this problem

**Comment by patrick-stephens** [comment]
Can you clarify the use case? Please use the template provided for the issue.

Which container is being stopped? 
Why are logs lost? They will be in S3 already.

Do you mean that you're running a Fluent Bit container to forward logs to S3 and how to handle container restart? It might be worth looking at the database to store where Fluent Bit gets up to in each tailed file: https://docs.fluentbit.io/manual/pipeline/inputs/tail#keep_state
