### ISSUE TITLE
td-agent-bit running on rhel as service problem with STDIN input

### ISSUE THREAD

**Issue by lugospod** [fluent/fluent-bit#4430]
## Bug Report

After installing td-agent-bit on RHEL 8, and applying the following configuration the service returns an error.
### Configuration:    
[SERVICE]
    flush        1
    daemon       Off
    log_level    debug
    parsers_file parsers.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
[INPUT]
    Name stdin
[OUTPUT]
    Name  stdout
    Match *

### Error:
[ee@q8fpoc01 td-agent-bit]$ sudo systemctl status td-agent-bit
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-12-10 16:33:55 CET; 7s ago
 Main PID: 2688863 (td-agent-bit)
    Tasks: 3 (limit: 384641)
   Memory: 15.4M
   CGroup: /system.slice/td-agent-bit.service
           └─2688863 /opt/td-agent-bit/bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf

Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [ info] [storage] version=1.1.4, initializing...
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [ info] [storage] in-memory
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [ info] [cmetrics] version=0.2.2
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [debug] [input:stdin:stdin.0] buf_size=16000
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [debug] [stdout:stdout.0] created event channels: read=20 write=21
**Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [  Error] epoll_ctl: Operation not per}itted, errno=1 at /tmp/fluent-bit-1.8.9/lib/monk>**
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [error] [input collector] COLLECT_EVENT registration failed
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [debug] [router] match rule stdin.0:stdout.0
Dec 10 16:33:55 q8fpoc01 td-agent-bit[2688863]: [2021/12/10 16:33:55] [ info] [sp] stream processor started

**To Reproduce**
- Steps to reproduce the problem:
Install, set configuration to the one above, 
start service using `sudo systemctl start td-agent-bit`
check status using `sudo systemctl status td-agent-bit`

**Expected behavior**
Expecting the service to wait for some process to start writing to service STDIN and not return an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/29342608/145601524-450f7efd-19e8-48f5-b78e-606fd81d79aa.png)

**Your Environment**

* Version used: Fluent Bit v1.8.9
* Configuration: pasted aboive
* Operating System and version: RHEL 8

**Additional context**
We would like our systemd services to write logs to standard input of td-agent-bit std input.

**Comment by patrick-stephens** [comment]
Personally this seems a strange idea to me, why is it required? The pipes are all actual file descriptors anyway, this has no security benefits I can see and also would prevent any multiplexing of input/output without more work. You can forward to files from the standard output pipe.

Actually looking at the RHEL documentation it explicitly says this is not possible: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/chap-managing_services_with_systemd#sect-Managing_Services_with_systemd-Compatibility_Changes

`System services are unable to read from the standard input stream. When systemd starts a service, it connects its standard input to /dev/null to prevent any interaction with the user.`

You might be able to force it to work with some custom systemd configuration to allow it: have you set up your service to do it? Can you share the service config?
e.g. https://unix.stackexchange.com/a/454098 or https://www.golinuxcloud.com/read-user-input-during-boot-stage-linux/

However I suspect this would move you out of support with Red Hat so again seems unwise.

**Comment by lugospod** [comment]
Hi @patrick-stephens!
Tnx for your feedback.

I was going in a direction "why should I use files for logging if there is a fluentbit that accepts STDIN as input". This approach avoids additional hassle that arises when using files (log rotation, ...).

The main goal is to store data to Splunk. I went with FluentBit because it said it supports STDIN as input (which it truly does, when running it as a standard process). So I wanted FluentBit to take care of "Buffering", "Storing on file system as backup", "sending to splunk",.... but unfortunately I wasnt aware of the part that you quoted, that systemd blocks STDIN to processes running under systemd. 

If I am going down the "files" route... then I guess I can use splunk forwarder.

tnx for your help
KR

**Comment by edsiper** [comment]
Closing ticket as main question has been addressed
