### ISSUE TITLE
Encountered an error during s3 upload

### ISSUE THREAD

**Issue by shaojielinux** [fluent/fluent-bit#4438]
Encountered an error during s3 upload
The following is the error of the context
[2021/12/13 08:53:55] [engine] caught signal (SIGSEGV)
#0  0x7f08906746ff      in  ???() at ???:0
#1  0x561d40637cb4      in  cio_file_write() at lib/chunkio/src/cio_file.c:881
#2  0x561d406341a6      in  cio_chunk_write() at lib/chunkio/src/cio_chunk.c:183
#3  0x561d40438a78      in  flb_fstore_file_append() at src/flb_fstore.c:258
#4  0x561d4040bbd7      in  s3_store_buffer_put() at plugins/out_s3/s3_store.c:182
#5  0x561d40409507      in  buffer_chunk() at plugins/out_s3/s3.c:1570
#6  0x561d4040b048      in  cb_s3_flush() at plugins/out_s3/s3.c:2096
#7  0x561d4032ef8f      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:514
#8  0x561d4082a106      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#9  0xffffffffffffffff  in  ???() at ???:0
kubectl logs -f -n logging fluent-bit-84cddbf5c7-8d9hw
Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/13 08:54:12] [error] [src/flb_http_client.c:1172 errno=32] Broken pipe
[2021/12/13 08:54:12] [error] [output:s3:s3.0] PutObject request failed
[2021/12/13 08:54:14] [error] [src/flb_http_client.c:1172 errno=32] Broken pipe
[2021/12/13 08:54:14] [error] [output:s3:s3.0] PutObject request failed
[2021/12/13 08:54:14] [error] [src/flb_http_client.c:1172 errno=32] Broken pipe
[2021/12/13 08:54:14] [error] [output:s3:s3.0] PutObject request failed
[2021/12/13 08:54:14] [error] [src/flb_http_client.c:1172 errno=32] Broken pipe
[2021/12/13 08:54:14] [error] [output:s3:s3.0] PutObject request failed
[2021/12/13 08:54:14] [error] [src/flb_http_client.c:1172 errno=32] Broken pipe
[2021/12/13 08:54:14] [error] [output:s3:s3.0] PutObject request failed

**Comment by patrick-stephens** [comment]
Can you provide the detail from the issue template and your config if possible, i.e. what platform, etc.?

**Comment by shaojielinux** [comment]
aws eks 

Fluent Bit v1.8.11
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/12/16 09:57:08] [engine] caught signal (SIGSEGV)
[2021/12/16 09:57:08] [engine] caught signal (SIGSEGV)
#0  0x7f6f31d1b6ff      in  ???() at ???:0
#1  0x7f6f31d1b6ff      in  ???() at ???:0
#2  0x55eb969e00a6      in  cio_file_content_copy() at lib/chunkio/src/cio_file.c:501
#3  0x55eb969e00a6      in  cio_file_content_copy() at lib/chunkio/src/cio_file.c:501
#4  0x55eb969dd332      in  cio_chunk_get_content_copy() at lib/chunkio/src/cio_chunk.c:247
#5  0x55eb969dd332      in  cio_chunk_get_content_copy() at lib/chunkio/src/cio_chunk.c:247
#6  0x55eb967e1a32      in  flb_fstore_file_content_copy() at src/flb_fstore.c:245
#7  0x55eb967e1a32      in  flb_fstore_file_content_copy() at src/flb_fstore.c:245
#8  0x55eb967b53e2      in  s3_store_file_read() at plugins/out_s3/s3_store.c:414
#9  0x55eb967b53e2      in  s3_store_file_read() at plugins/out_s3/s3_store.c:414
#10 0x55eb967b0c69      in  construct_request_buffer() at plugins/out_s3/s3.c:1158
#11 0x55eb967b23d7      in  send_upload_request() at plugins/out_s3/s3.c:1549
#12 0x55eb967b4002      in  cb_s3_flush() at plugins/out_s3/s3.c:2087
#13 0x55eb967b0c69      in  construct_request_buffer() at plugins/out_s3/s3.c:1158
#14 0x55eb967b23d7      in  send_upload_request() at plugins/out_s3/s3.c:1549
#15 0x55eb967b4002      in  cb_s3_flush() at plugins/out_s3/s3.c:2087
#16 0x55eb966d7f8f      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:514
#17 0x55eb96bd3106      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#18 0xffffffffffffffff  in  ???() at ???:0



config:
[OUTPUT]
        Name s3
        Match *
        region ap-southeast-1
        bucket flunet-bit
        upload_timeout 4m
        store_dir /data/s3
        s3_key_format /$TAG[1]/$TAG[3]/%Y/%m/%d/
        s3_key_format_tag_delimiters .
        #use_put_object On
        workers 4
        total_file_size 5M
        upload_chunk_size 2M
        #compression gzip
        #auto_retry_requests true

**Comment by shaojielinux** [comment]
It's been bothering me for a long time
