### ISSUE TITLE
Fluent Bit for Solaris can't be installed with message Can't open perl script "/tmp/fluent-bit/fluent-bit-solaris/scripts/config.pl

### ISSUE THREAD

**Issue by dmitriklein** [fluent/fluent-bit#4444]
## Bug Report

**Describe the bug**

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Need some more details here: which version, how are you installing? Please fill out the template in the issue.

Are you building from source or using an OS package? It's not one of the listed platforms here: https://docs.fluentbit.io/manual/installation/supported-platforms

**Comment by dmitriklein** [comment]
Hello Patrick. Many thanks for replying. We are installing fluent-bit for Solaris from this only one available 
source : https://gitlab.cncf.ci/fluent/fluent-bit/tree/solaris . We install it as following: 
$ cd build
$ cmake ..
$ make
$ bin/fluent-bit -i cpu -o stdout

No idea about the version. Installation log file is attached FYI. Many thanks for your expertise! 
[log.txt](https://github.com/fluent/fluent-bit/files/7712827/log.txt)

**Comment by dmitriklein** [comment]
[log.txt](https://github.com/fluent/fluent-bit/files/7712848/log.txt)

**Comment by edsiper** [comment]
Solaris is not a supported platform. You can try making your Solaris logging output to use Syslog and use Fluent Bit receive those messages over the network

**Comment by dmitriklein** [comment]
Thank you for the clarification. Can you recommend any supported tool/agent for OS Solaris, like Filebeat, FluentBit, etc. which allows parsing log files. We use collectd at the moment, and it doesn't allow to do much with different log files. Many thanks!

**Comment by patrick-stephens** [comment]
As @edsiper suggests, I think your best bet is to forward to a non-Solaris node using syslog. On this you'll then have the ability to do a lot more including running Fluent Bit to do what you need.
Supporting Solaris for OSS is very tricky as it is Oracle proprietary solution. I would discuss with your vendor if there is no alternative.
