### ISSUE TITLE
Multi-line configuration error

### ISSUE THREAD

**Issue by linuxxin** [fluent/fluent-bit#4448]
## Bug Report

**Describe the bug**

I have solved the problem of multi-line log, but it appears that multi-line log does not belong to any service, how to solve this problem, thank you as shown in the following picture

**Your Environment**

* Version used: 1.8.8
* Configuration: 
*     [FILTER]
        name                  multiline
        match                 kube.*
        multiline.key_content log
        multiline.parser      multiline-regex-test

*  [MULTILINE_PARSER]
        name              multiline-regex-test
        type                regex
        flush_timeout 1000
        rule          "start_state"   "/^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}|^\d{2}:\d{2}:\d{2}.\d{3}|^\d{2}-[a-zA-Z]{3}-\d{4} \d{2}:\d{2}:\d{2}.\d{3})(.*)$/"  "cont"
        rule          "cont"          "/^\s(.*)$/" "cont"

* Environment name and version (e.g. Kubernetes? What version?): v1.18.0
* Server type and version: x86_64
* Operating System and version: ubuntu~16.04.12
* Filters and plugins:

**Additional context**

![145787592-010a578f-f65e-41fd-9289-624c84c687e3](https://user-images.githubusercontent.com/73919673/145919731-a49f99f5-9e25-419a-9a34-8d982ac289db.png)

**Comment by PettitWesley** [comment]
@linuxxin Sorry I am still not completely understanding what you mean by the logs not belonging to a service I think... a field is missing?

Can you please give an example log before processing, an example of what you expect the log to look like, as well as your full Fluent Bit config file? Also, if you can paste all of the logs (including the one with the missing field) as text, not screenshots/pictures, that would help too. Thanks.

**Comment by linuxxin** [comment]
This is my configuration file
[fluent-bit-configmap.txt](https://github.com/fluent/fluent-bit/files/7711311/fluent-bit-configmap.txt)
This is my error log
[mistake.txt](https://github.com/fluent/fluent-bit/files/7711313/mistake.txt)
That's my expectation
[anticipate.txt](https://github.com/fluent/fluent-bit/files/7711315/anticipate.txt)
First you see the error log, which does not belong to any pod，I want to know the error log source is from which POD error log，It's my configuration file again？
![1639482237](https://user-images.githubusercontent.com/73919673/145992182-717ca8a4-c639-4a59-a928-83ca55919ef0.jpg)

**Comment by PettitWesley** [comment]
@linuxxin I think I understand now... so the multiline processed logs lack kubernetes metadata? Do they lack all k8s metadata or only the pod_name?

I see you are using the multiline filter... if you are using the tail input, you should not use the filter. Use the multiline support in the tail plugin itself, it supports the same API, but because it operates in the input, its more performant and can give a better guarantee that all multiline logs will be concatenated. As noted in my re-design (the issue you originally commented on), right now the filter will only be able to concatenate multilines if they are read all together, which basically means its slightly random.

Here is the multiline support in tail docs, please try it and let us know: https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-core-v1.8

**Comment by linuxxin** [comment]
Hello, I have modified the multi-line configuration according to your instructions,It still doesn't work, it's a single line, so here's the line I added: multiline.parser  docker,cri,java,go,python

**Comment by linuxxin** [comment]
I use standard output to the , is normal multiple lines，But to collect Kibana, it will be a single line output, using K8S logs ,Using the built-in multi-line configurator is also ineffective, and standard output can also be multi-line;

**Comment by PettitWesley** [comment]
@linuxxin Sorry, I went on vacation for a while. Can you please post your new config where you switched to using multiline in the tail input instead of the filter: https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-core-v1.8

**Comment by linuxxin** [comment]
hi，Ok, that's solved thank you, I just want to ask a question how to collect docker metadata ，Only docker is collected, because some services have not been migrated to K8S and still need to run in Docker ：containername，Whether this function is available

**Comment by PettitWesley** [comment]
@linuxxin Unfortunately, there is no generic metadata filter for Docker. It might be possible to accomplish something with a custom lua script, not sure: https://docs.fluentbit.io/manual/pipeline/filters/lua
