### ISSUE TITLE
docker log rotation isn't working with in_tail (truncate mode)

### ISSUE THREAD

**Issue by jsravn** [fluent/fluent-bit#445]
After the log is rotated, in_tail stops reading in new logs.

It looks to me the detection is not working. I'm not sure exactly how docker rotates logs, but I'm guessing it does a truncate.

Here is the log that has stopped being shipped, notice it is only 1Gi:
```
# ls -li /var/lib/docker/containers/f146a6d1305d5f56e09737b59d4a05690abf2bbb3669003f58bd076ff2866f7d/
total 1028560
138802546 -rw-rw-rw- 1 root root       8876 Nov 20 15:31 config.v2.json
138802542 -rw-r----- 1 root root 1028018636 Nov 22 11:26 f146a6d1305d5f56e09737b59d4a05690abf2bbb3669003f58bd076ff2866f7d-json.log
138802547 -rw-rw-rw- 1 root root       2020 Nov 20 15:31 hostconfig.json
```

In the sqlite3 db:
```
sqlite> SELECT * FROM in_tail_files where NAME like '%rl7fw%';
id     name                                                               offset        inode         created     rotated   
-----  -----------------------------------------------------------------  ------------  ------------  ----------  ----------
42     /var/log/containers/abcdefh-bcdefgh-abcefgh-3275728838-rl7fw_vm-c  2000001289    138802542     1511191918  0         
```

The inode and created timestamp are correct, but offset is wrong. We limit docker logs to 2Gi in size - so looks like the offset prior to a rotation.

**Comment by edsiper** [comment]
once a file is rotated, Fluent Bit needs to re-scan the path to find new ones and this is handled by the Refresh_Interval option in in_tail. What refresh_interval do you have ?

**Comment by jsravn** [comment]
@edsiper It is set to 10 seconds. But I don't think that's the issue. docker does copy truncate on rotation. In my case I set `max-file` to 1, so there's never any new files. Docker simply truncates the existing log file, after which fluent bit will stop shipping from it. I think fluent-bit would need to check the size of the file to detect truncation.

**Comment by jsravn** [comment]
This must be a docker quirk. When I sent `max-file` > 1, then indeed a new file gets created on rotation. When set to 1 it looks like it just truncates... (or it's deleting then recreating, and linux is recycling the prior inode - but I imagine inotify would pick that up).

**Comment by edsiper** [comment]
ah ! because Truncate mode is not supported (and not intended to be :)

**Comment by jsravn** [comment]
@edsiper Does fluent-bit handle reused inodes correctly?  e.g. it rotates and creates a new file, which gets the same inode # as old rotated-off file.

**Comment by jsravn** [comment]
Cool I made https://github.com/fluent/fluent-bit-docs/pull/44 to document the rotation behavior.

**Comment by edsiper** [comment]
docs merged, thanks.

**Comment by PettitWesley** [comment]
Has anyone else ever run into this?

>This must be a docker quirk. When I sent max-file > 1, then indeed a new file gets created on rotation for new logs. When set to 1 it looks like it just truncates... (or it's deleting then recreating, and linux is recycling the prior inode - but I imagine inotify would pick that up).

> So as a workaround I can set max-file = 2 in docker.

Max-file is set to 1 by default in docker: https://docs.docker.com/config/containers/logging/json-file/

You can update it with a custom docker daemon.json on your host.
