### ISSUE TITLE
in_forward: add support to configure tags for records ingested using the forward input

### ISSUE THREAD

**Issue by ridwanmsharif** [fluent/fluent-bit#4455]
Currently the Forward Input plugin doesn't allow overwriting or customizing Tags for log records in any way.
I'm trying to add support for a `forward` receiver  in the Ops Agent. But doing so requires that the Ops Agent be able to route records to processors/filters and outputs using Tags. It can't do that with the existing Fluent Bit _Forward_ receiver as it doesn't allow the Ops Agent to control the Tags of records.

**Describe the solution you'd like**
If the Forward receiver exposed a configuration field like "Tag_Prefix" (defaulted to "") that would prefix the tags from logs ingested with a configurable string - it would allow the Ops Agent to better control the data pipeline.

**Describe alternatives you've considered**
The Forward [output](https://docs.fluentbit.io/manual/pipeline/outputs/forward) plugin allows a configuration option that overwrites the Tag. We could have the same for the Input plugin.
_Cons_: The old tag is discarded and this is not good. It could be used for further processing, routing etc. If this is done, we should figure out where to store the old tag (push it into the message?)

**Additional context**

"Tags" aren't exposed by the Ops Agent to its users, and alternatives we've considered (like using rewrite_tag don't work with multiple forward inputs). Allowing an option like "Tag_Prefix" would let the Ops Agent prefix the record tags with some other string (like [receiver ID](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#logging-receiver-structure)) and so would let the Ops Agent continue routing and processing records.

**Comment by edsiper** [comment]
Implementation submitted on #4466

**Comment by qingling128** [comment]
This PR above has been tested and verified. It fulfilled our need.

**Comment by qingling128** [comment]
Note: Looks like it's not documented yet.
