### ISSUE TITLE
Unable to reload fluent-bit.conf in running docker container. 

### ISSUE THREAD

**Issue by mahima145** [fluent/fluent-bit#4456]
Fluent-bit.conf file is updated dynamically every time the docker service should read it.
 Isn't? Is it configuration issue?

Please help me this.

**Comment by patrick-stephens** [comment]
No, it is not reloaded dynamically - Fluent Bit has to be restarted to pick up config changes.

There are options, e.g. provide a watcher entrypoint that launches Fluent Bit and watches for changes to the config then restarts Fluent Bit. This is what the Fluent operator image does for example: https://github.com/fluent/fluentbit-operator

**Comment by patrick-stephens** [comment]
See https://github.com/fluent/fluent-bit/issues/365 for the enhancement request and associated discussion.
