### ISSUE TITLE
s3 output plugin complete upload with interval

### ISSUE THREAD

**Issue by dlsrb6342** [fluent/fluent-bit#4459]
**Is your feature request related to a problem? Please describe.**

* I am using s3 output plugin with parameter `--prop=S3_Key_Format=/service/year=%Y/month=%m/day=%d/hour=%H/minute=%M/$UUID `
* partitioning with minute doesn't work as expected
* If `upload_timeout` is `2m` and `total_file_size` is `128M`, Multipart upload that is created at 08:03:32, can have `08:03:32 ~ 08:05:31` logs. this case, makes partitioning with minutes meaningless.
* This is because s3 output plugin checks only two paramter, `upload_timeout` and `total_file_size`.

**Describe the solution you'd like**

* Add configration parameter `upload_interval`. 
* Possible values include: 'daily', 'hourly', 'minutely'
* Before append log to chunk, check interval

**Describe alternatives you've considered**

**Additional context**

* Without this feature, I need to query with padding in time. It spend more time and cost.

**Comment by shinefreak** [comment]
!? upvote, please consider including this requested feature
