### ISSUE TITLE
fluent-bit doesn't link if in_storage_backlog plugin is off

### ISSUE THREAD

**Issue by rschwebel** [fluent/fluent-bit#4464]
The toplevel CMakeLists.txt has an option -DFLB_IN_STORAGE_BACKLOG that enables or disables the plugins/in_storage_backlog plugin off.

Since commit ba58aa0783d6b5029c51f9524f0df303b2250417 (authored by Leonardo Alminana <leonardo@calyptia.com> and part of fluent-bit-1.8.8), src/flb_engine.c calls sb_segregate_chunks() unconditionally, which is defined in the in_storage_backlog plugin. 

So if we switch the plugin off with  -FLB_IN_STORAGE_BACKLOG=Off, fluent-bit doesn't link any more:

...
[100%] Linking C executable ../bin/fluent-bit
<Toolchain-Path>/bin/ld: ../library/libfluent-bit.a(flb_engine.c.o): in function `flb_engine_start':
fluent-bit-1.8.11-build/src/platform-v7a/build-target/fluent-bit-1.8.11/src/flb_engine.c:684: undefined reference to `sb_segregate_chunks'

Switching -DFLB_IN_STORAGE_BACKLOG=On makes it link again, but that's certainly not intended.

**Comment by rschwebel** [comment]
sb_get_releasable_output_queue_space is also undefined if in_storage_backlog is switched off.

**Comment by leonardo-albertovich** [comment]
Hi Robert, could you check this branch out? https://github.com/fluent/fluent-bit/pull/4471
I understand that you are running the 1.8 branch but if you could verify if this branch works then I might be able to backport the correction once it's cleared.

**Comment by rschwebel** [comment]
The branch fixes the issue.

**Comment by rschwebel** [comment]
#4471 is merged, so this can be closed.
