### ISSUE TITLE
fluent-bit process zombie

### ISSUE THREAD

**Issue by 519859716** [fluent/fluent-bit#4465]
**Is your feature request related to a problem? Please describe.**
if  fluent-bit process is in zombie status ,it can not recover by itself ,

**Describe the solution you'd like**
At present there is no way to solve this issue , can't add liveness probe or do something for heatbeat 

**Describe alternatives you've considered**
if we can expose the network with service or  do something with heatbeat

**Comment by agup006** [comment]
@519859716 would you be able to provide repro steps and more information - the issue template should guide on what information is most helpful. The ticket as it is now is very hard to troubleshoot, replicate, and fix

**Comment by 519859716** [comment]
hello 
hello 
this is just our test case for DFX 
1、find out the  fluent-bit docker process
[root@k8s-1 ~]# docker ps |grep fluent-bit
ece46bf9225f        rvm:5100/kubesphere/fluent-bit                                    "/fluent-bit/bin/flu…"   5 days ago          Up 5 days                                                         k8s_fluent-bit_fluent-bit-4kntn_kubesphere-logging-system_23c601f2-fa80-4e48-b152-40879da8276e_0
06eb8773e423        rvm:5100/fitcontainer/pause:3.2                                   "/pause"                 5 days ago          Up 5 days                                                         k8s_POD_fluent-bit-4kntn_kubesphere-logging-system_23c601f2-fa80-4e48-b152-40879da8276e_0
[root@k8s-1 ~]# 

2、 check the docker process
[root@k8s-1 ~]# docker top ece46bf9225f
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                8986                20929               0                   12月10               ?                   00:33:37            /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
root                20929               20912               0                   12月10               ?                   00:00:00            /fluent-bit/bin/fluent-bit-watcher
[root@k8s-1 ~]# 
[root@k8s-1 ~]# ps aux |grep 8986
root      3903  0.0  0.0 112712   956 pts/1    S+   14:35   0:00 grep --color=auto 8986
root      8986  0.4  0.0 1116984 109576 ?      Sl   Dec10  33:37 /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
[root@k8s-1 ~]# 
3、Simulate this zombie scenario
[root@k8s-1 ~]# kill -STOP 8986
[root@k8s-1 ~]# 
[root@k8s-1 ~]# ps aux |grep 8986
root      5703  0.0  0.0 112712   956 pts/1    S+   14:35   0:00 grep --color=auto 8986
root      8986  0.4  0.0 1116984 109576 ?      Tl   Dec10  33:37 /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
[root@k8s-1 ~]#

4、 our recover benchmark is less than 10min 。after 10min this process still Tl  . and i see the log is also stuck.

**Comment by lecaros** [comment]
Hello,
Would you mind clarifying some information from your environment?
Version used:
Configuration:
Environment name and version (e.g. Kubernetes? What version?):
Server type and version:
Operating System and version:
Filters and plugins:

This information could help narrow down the issue better. It's preferable to fill in the Bug Report template instead of this intended for Feature requests.

**Comment by 519859716** [comment]
Version used: v1.8.3
Configuration: 
Environment name and version (e.g. Kubernetes? What version?): k8s， v1.19.10-32493
Server type and version: 
Operating System and version: CentOS Linux release 7.7.1908 (Core)
Filters and plugins: 
![image](https://user-images.githubusercontent.com/40968187/146853675-3a4206bb-4c06-49f3-8fb7-26f1750d5eb5.png)


maybe it has nothing to do with  fluentbit self . it need to add some Highly reliable ways to check fluentbit process whether it is normal .  liveness probe or exec probe  and so on. is that possible to add ?
