### ISSUE TITLE
Apply multiple filter on the same pool of logs and output each one on a different ES indexs

### ISSUE THREAD

**Issue by mikrammo** [fluent/fluent-bit#4468]
## Bug Report

**Describe the bug**
Using the same pool of logs, I want to apply 2 filters and output them on 2 differents elastic search indexs
Here is my configuration :
I'm on EKS ( AWS kubernetes cluster )
I'm using fluentbit 1.8

config : 
...
image:
  repository: fluent/fluent-bit
  tag: "1.8.11"
  pullPolicy: Always
serviceAccount:
  annotations: 
    eks.amazonaws.com/role-arn: ${ROLE_ARN}
  name: ${SERVICE_ACCOUNT_NAME}
config:
  service: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level trace
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.service.port }}

  inputs: |
%{ for application in APPLICATIONS ~} 
    [INPUT]
        Name              tail
        Tag               kube.${application.app_name}.*
        Path              /var/log/containers/${application.app_name}*.log
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Buffer_Max_Size   20MB
        DB                /var/log/containers/fluent-bit.db
        DB.Sync            Normal
        Docker_Mode        On
        Docker_Mode_Flush  5
        Docker_Mode_Parser multi_line
        Parser             docker
        Buffer_Chunk_Size  512KB
        Rotate_Wait        30
        Mem_Buf_Limit      30MB
%{ endfor ~}
%{ for application in APPLICATIONS ~} 
    [INPUT]
        Name              tail
        Tag               grep
        Path              /var/log/containers/${application.app_name}*.log
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Buffer_Max_Size   20MB
        DB                /var/log/containers/fluent-bit.db
        DB.Sync            Normal
        Docker_Mode        On
        Docker_Mode_Flush  5
        Docker_Mode_Parser multi_line
        Parser             docker
        Buffer_Chunk_Size  512KB
        Rotate_Wait        30
        Mem_Buf_Limit      30MB
%{ endfor ~}

  filters: |
%{ for application in APPLICATIONS ~} 
    [FILTER]
        Name                kubernetes
        Match               kube.${application.app_name}.*
        Buffer_Size         0
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.${application.app_name}.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         Off
        Kube_meta_preload_cache_dir /tmp
%{ endfor ~}
%{ for application in APPLICATIONS ~} 
    [FILTER]
        Name                grep
        Match               grep
        regex               eventType .*XYZ_TRACE.*
%{ endfor ~}

  outputs: |
%{ for application in APPLICATIONS ~}
    [OUTPUT]
        Name es
        Match kube.${application.app_name}.*
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        AWS_Auth On
        AWS_Region eu-west-3
        Generate_ID On
        Logstash_Format On
        Retry_Limit 6
        TLS             On
        Logstash_Prefix kubernetes-${application.app_name}
        Logstash_DateFormat %Y.%m
        Trace_Error Off
%{ endfor ~}
%{ for application in APPLICATIONS ~}
    [OUTPUT]
        Name es
        Match *
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        AWS_Auth On
        AWS_Region eu-west-3
        Generate_ID On
        Logstash_Format On
        Retry_Limit 6
        TLS             On
        Logstash_Prefix grep-${FLUENT_INDEX_NAME}
        Logstash_DateFormat %Y
        Trace_Error Off
%{ endfor ~}
  customParsers: |
    [PARSER]
        Name                     multi_line
        Format                   regex
        Regex                    (?<log>^{"log":"\d{4}-\d{2}-\d{2}.*)

**Expected behavior**
I'm expecting that 
logs filtered by kubernetes filter goes to index kubernetes-xxxx 
and the same logs filtred by grep goes to index grep-xxxx

But I only see in my elasticsearch logs filtred by kubernetes filter

**Comment by patrick-stephens** [comment]
I think you're confused what `grep` does - it only includes/excludes records in the stream it matches. It does not create new streams. You need to create two streams using `rewrite-tag` and match them to whatever output plugin provides each index I think.

**Comment by mikrammo** [comment]
Thanks @patrick-stephens for your reply,
I was confused about what [INPUT] does, for me if I created 2 Input with 2 differents tag from the same logs as I do that will create 2 differents stream.
As you recommand I used rewrite-tag it works for my use case ;)

Here is my new config
config:
  service: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.service.port }}

  inputs: |
%{ for application in APPLICATIONS ~} 
    [INPUT]
        Name              tail
        Tag               kube.${application.app_name}.*
        Path              /var/log/containers/${application.app_name}*.log
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Buffer_Max_Size   20MB
        DB                /var/log/containers/fluent-bit.db
        DB.Sync            Normal
        Docker_Mode        On
        Docker_Mode_Flush  5
        Docker_Mode_Parser multi_line
        Parser             docker
        Buffer_Chunk_Size  512KB
        Rotate_Wait        30
        Mem_Buf_Limit      30MB
%{ endfor ~}

  filters: |
%{ for application in APPLICATIONS ~} 
    [FILTER]
        Name                kubernetes
        Match               kube.${application.app_name}.*
        Buffer_Size         0
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.${application.app_name}.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         Off
        Kube_meta_preload_cache_dir /tmp
%{ endfor ~}
%{ for application in APPLICATIONS ~} 
    [FILTER]
        Name                rewrite_tag
        Match               kube.${application.app_name}.*
        Rule                $eventType .*SWIFT_TRACE.* qos.$TAG true
%{ endfor ~} 

  outputs: |
%{ for application in APPLICATIONS ~}
    [OUTPUT]
        Name es
        Match kube.${application.app_name}.*
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        AWS_Auth On
        AWS_Region eu-west-3
        Generate_ID On
        Logstash_Format On
        Retry_Limit 6
        TLS             On
        Logstash_Prefix ${FLUENT_INDEX_NAME}-${application.app_name}
        Trace_Error Off
%{ endfor ~}
%{ for application in APPLICATIONS ~}
    [OUTPUT]
        Name es
        Match qos.kube.${application.app_name}.*
        Host ${FLUENT_ELASTICSEARCH_HOST}
        Port ${FLUENT_ELASTICSEARCH_PORT}
        AWS_Auth On
        AWS_Region eu-west-3
        Generate_ID On
        Logstash_Format On
        Retry_Limit 6
        TLS             On
        Logstash_Prefix qos-${FLUENT_INDEX_NAME}
        Trace_Error Off
%{ endfor ~}
  customParsers: |
    [PARSER]
        Name                     multi_line
        Format                   regex
        Regex                    (?<log>^{"log":"\d{4}-\d{2}-\d{2}.*)

**Comment by patrick-stephens** [comment]
Great to hear, can we close?

**Comment by mikrammo** [comment]
thanks again 
yes you can close it ;)
