### ISSUE TITLE
Output kafka avro: schema not found

### ISSUE THREAD

**Issue by lzwaan** [fluent/fluent-bit#4488]
## Bug Report
Not sure if this a known bug, but couldn't fine any solution here...

**Describe the bug**
When sent messages to kafka with avro enabled, no schema is created, but shows some generated id?

**To Reproduce**
Fluentbit config (output) and there were 2 messages sent, see screenshot...
```
[OUTPUT]
    Name                                kafka
    Match                               lease
    Brokers                             kafka1:10091,kafka2:10092
    topics                              input.fluentbit.b2b.dhcp.lease
    Format                              avro
    Schema_str                          {"namespace":"com.github.lzwaan.avro","type":"record","name":"dhcp_lease","fields":[{"name":"TIMESTAMP","type":"string"},{"name":"CID","type":"string"},{"name":"LEASE","type":"string"},{"name":"TOPIC","type":"string"}]}
    Schema_id                           12345
    timestamp_key                       TIMESTAMP
    timestamp_format                    iso8601
    message_key_field                   CID
    rdkafka.client.id                   fluentbit_dhcp_clientid
    rdkafka.debug                       All
    rdkafka.security.protocol           plaintext
    rdkafka.request.required.acks       1
    rdkafka.log.connection.close        false
    rdkafka.log_level                   7
    rdkafka.metadata.broker.list        kafka1:10091,kafka2:10092
```

**Screenshots from AKHQ**
<img width="1166" alt="schema_not_found" src="https://user-images.githubusercontent.com/549919/146822563-49f1396a-cebb-44d2-b05b-70cd6a50e63f.png">

**Your Environment**
Debian

**Comment by lzwaan** [comment]
Is there anybody who has used fluentbit succesfull wih avro enabled inside docker containers?

**Comment by flarno11** [comment]
> Is there anybody who has used fluentbit succesfull wih avro enabled inside docker containers?

yes works here. by manually compiling with `-DFLB_AVRO_ENCODER=On` and the fix from https://github.com/fluent/fluent-bit/pull/5435

**Comment by shuishou1983** [comment]
Hi @flarno11, could you share me which code base did you use for customized build? I tried 2.0.9 but got error with avro format in kafka output. TIA.

**Comment by flarno11** [comment]
@shuishou1983 I don't remember the exact version, but it was already on the 2.x branch, cherry-picked the fix and recompiled

**Comment by ppenpraze** [comment]
I ended up using the HTTP output plugin and made a Kafka/Avro bridge in Python, works well.

**Comment by shuishou1983** [comment]
Thank your comments, @flarno11 @ppenpraze. I'm new to Fluent Bit. I will try kafka output first to see could make it work. Now my customized build failed at following error:
[2023/02/21 06:26:50] [debug] got key:container_image:

[2023/02/21 06:26:50] [debug] avro_value_add:key:container_image:avro error::

[2023/02/21 06:26:50] [debug] added

[2023/02/21 06:26:50] [debug] calling avro_value_get_by_name

[2023/02/21 06:26:50] [debug] called avro_value_get_by_index

[2023/02/21 06:26:50] [debug] in msgpack2avro

[2023/02/21 06:26:50] [debug] got a string: "
6.270001.6-20230106.1673017923830[2023/02/21 06:26:50] [engine] caught signal (SIGSEGV)
[2023/02/21 06:26:50] [debug] "

[2023/02/21 06:26:50] [debug] setting string:6.270001.6-20230106.1673017923830:

[2023/02/21 06:26:50] [debug] set string

[2023/02/21 06:26:50] [debug] before avro_writer_memory

#0  0x7f8d18f8dda7      in  ???() at ???:0
#1  0x7f8d18f5bb25      in  ???() at ???:0
#2  0x7f8d18f4a8e0      in  ???() at ???:0
#3  0x7f8d18f4a847      in  ???() at ???:0
#4  0x98dda3            in  flb_msgpack_raw_to_avro_sds() at src/flb_avro.c:350
#5  0x7c32d1            in  produce_message() at plugins/out_kafka/kafka.c:337
#6  0x7c3a55            in  cb_kafka_flush() at plugins/out_kafka/kafka.c:500
#7  0x4b2f16            in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:528
#8  0xf17426            in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#9  0xffffffffffffffff  in  ???() at ???:0
Aborted (core dumped)
