### ISSUE TITLE
reserve_data on doesn't seem to work in filter_parser

### ISSUE THREAD

**Issue by jsravn** [fluent/fluent-bit#449]
http://fluentbit.io/documentation/0.12/filter/parser.html

I've copied the example config and parser, and set `Reserve_Data True`. However, the original field is not preserved.

**Comment by jsravn** [comment]
Also, if I add an additional field it segfaults.

**Comment by jsravn** [comment]
May be related to https://github.com/fluent/fluent-bit/issues/450

**Comment by jsravn** [comment]
It appears _all_ fields are deleted by default without this on. Is that intended? `filter_parser` only parses a single field - why would it delete all other record fields? I don't think that behavior is correct. `Reserve_Data` should be just about preserving the field that gets parsed, I think. Also it should be renamed `Preserve_Data`, `Reserve` is the wrong word I think.

**Comment by jsravn** [comment]
I've opened #451 with tests showing the problems.

**Comment by nokute78** [comment]
Thank you for reporting issue.

@edsiper The patch to “support multiple parsers” seems to break the reserve_data feature.
Could you check it?

@jsravn This feature is imitated the plugin of “fluentd”.
The name and behavior comes from it.

**Comment by jsravn** [comment]
@nokute78 Okay thank you. I think you are right, this is just an issue on master. I'll see if I can fix it in #451 which will also add some test coverage.

**Comment by jsravn** [comment]
Okay, I've fixed this in #451.

**Comment by edsiper** [comment]
fixed.
