### ISSUE TITLE
in_exec cannot parse json when execed command doesn't print trailing newline

### ISSUE THREAD

**Issue by rschwebel** [fluent/fluent-bit#4493]
Hi,

we are trying to curl some json from a local web service, and fluent-bit logs this to the output:

`[2021/12/01 01:59:12] [error] [input:exec:exec.0] parser returned an error`

Turns out that it works if the execed script outputs a trailing newline and fails if not, due to this code:
https://github.com/fluent/fluent-bit/blob/master/plugins/in_exec/in_exec.c#L69

The code clamps the string by changing the last character to \0, which works perfectly when the execed script has a trailing newline (which is overwritten), but kills the last json character if not. In this case, the jsmn parser fails with an incomplete token.

Example input config to trigger the issue:

```
[INPUT]
     Name          exec
     Tag           exec_adc
     Command       echo -n '{"foo": "bar"}'
     Parser        json
     Interval_Sec  5
     Interval_NSec 0
     Buf_Size      8mb

```
Remove the -n in the Command line and it works, leave it in and it fails.

**Comment by rschwebel** [comment]
Is there anything I can do to help moving #4496 forward?

**Comment by agup006** [comment]
@lecaros do you think we could add as 1.9?
