### ISSUE TITLE
malformed field causes segfault in filter_parser

### ISSUE THREAD

**Issue by jsravn** [fluent/fluent-bit#450]
Setup a parser like in http://fluentbit.io/documentation/0.12/parser/regular_expression.html.

```
[PARSER]
    Name dummy_test
    Format regex
    Regex ^(?<time>.*)$
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
```

Pass in dummy data with a malformed date and some extra fields
```
[SERVICE]
    Parsers_File parsers.conf
    Flush 1

[INPUT]
    Name dummy
    Tag  dummy.data
    Dummy {"@timestamp":"20517_-11-24T02:26:21.123Z","log":"hi there"}

[FILTER]
    Name parser
    Match dummy.*
    Key_Name @timestamp
    Parser dummy_test

[OUTPUT]
    Name stdout
    Match *

```

Run fluent-bit against this. It will segfault. If you remove the "log" field then it prints an error about malformed date, and seems to eat the whole log line.

What I expect to happen:
* If field is unparseable, it should simply return `FLB_FILTER_NOTOUCH` and not do anything with it.
* It shouldn't segfault in any case.

**Comment by jsravn** [comment]
I'm also noticing I can get a segfault if I set `Reserve_Data` to on and add an additional field to the dummy record. I'm slightly confused on the behavior. filter_parser should not be deleting all other fields in the record right? It should parse the specified field then merge it with the rest of the record fields?

**Comment by jsravn** [comment]
I made https://github.com/fluent/fluent-bit/pull/451 with several tests showing some problems. Seems like there are quite a few issues with this filter that need sorting.

**Comment by edsiper** [comment]
@jsravn do you see this problem on 0.12 series ?, I made a set of incomplete changes on GIT master, just want to check if that could be the root cause

**Comment by jsravn** [comment]
@edsiper Ah okay, it is against master that I see the problem. So it might be fine on 0.12.

**Comment by jsravn** [comment]
Fixed this in master on https://github.com/fluent/fluent-bit/pull/451. @edsiper
