### ISSUE TITLE
fluent-bit in dead status, looks like too many ESTABLISHED tcp connection not release

### ISSUE THREAD

**Issue by zhanghe9702** [fluent/fluent-bit#4507]
## Bug Report

**Describe the bug**

k8s environment, fluent-bit pod can't send any packet to fluentd,  i have used nettools show some state info
**|># ip netns exec ns-117151 ss -tnap | grep 10.100.168.238:24240 |  wc -l**
217

|root@l-172016023031-ops /home/he.zhang
**|># ip netns exec ns-117151 ss -tnap | grep 10.100.168.238:24240 |  wc -l**
217
and has  no respond conntrack info in node
**|># conntrack -L | grep 10.100.168.238**
conntrack v1.4.4 (conntrack-tools): 20855 flow entries have been shown.
and use CONT signal dump fluent-bit internal state twice
**kill -CONT 117151**
**first run**
[2021/12/21 06:57:23] Fluent Bit Dump

===== Input =====
tail.0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 204.0M (213920717 bytes)
│     └─ mem limit  : 953.7M (1000000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 610
│  ├─ new           : 0
│  ├─ running       : 610
│  └─ size          : 204.0M (213919645 bytes)
│
└─ chunks
   └─ total chunks  : 611
      ├─ up chunks  : 611
      ├─ down chunks: 0
      └─ busy chunks: 610
         ├─ size    : 204.0M (213919645 bytes)
         └─ size err: 0
**second run**
[2021/12/21 11:13:51] Fluent Bit Dump

===== Input =====
tail.0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 204.0M (213920717 bytes)
│     └─ mem limit  : 953.7M (1000000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 610
│  ├─ new           : 0
│  ├─ running       : 610
│  └─ size          : 204.0M (213919645 bytes)
│
└─ chunks
   └─ total chunks  : 611
      ├─ up chunks  : 611
      ├─ down chunks: 0
      └─ busy chunks: 610
         ├─ size    : 204.0M (213919645 bytes)
         └─ size err: 0

**To Reproduce**
- Steps to reproduce the problem:
don't know the condition, 9 nodes k8s cluster, deploy an fluent-bit daemonset, but only one node works error
**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:|># kubectl exec -it -n gemcloud-logging-system  gems-logging-fluentbit-kp5sr -- /fluent-bit/bin/fluent-bit  --version
Fluent Bit v1.8.8

* Configuration:

[SERVICE]
    Flush        1
    Grace        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    Coro_Stack_Size    24576
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    storage.backlog.mem_limit  128M
    storage.path  /var/log/log-buffer
[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    Docker_Mode  false
    Mem_Buf_Limit  1G
    Parser  docker
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Rotate_Wait  5
    Skip_Long_Lines  true
    Tag  kubernetes.*
[FILTER]
    Name        kubernetes
    Buffer_Size  0
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Tag_Prefix  kubernetes.var.log.containers
    Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_URL  https://kubernetes.default.svc:443
    Match  kubernetes.*
    Merge_Log  On
    Use_Kubelet  false
[OUTPUT]
    Name          forward
    Match         *
    Host          gems-logging-fluentd.gemcloud-logging-system.svc
    Port          24240
    net.connect_timeout 30
    net.keepalive_idle_timeout 60
    Require_ack_response  true
    Retry_Limit  False

* Environment name and version (e.g. Kubernetes? What version?):
kubernetes
* Server type and version:
kubectl get nodes -o wide
NAME                                STATUS                     ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION           CONTAINER-RUNTIME
l-172016023031 Ready                      <none>   657d    v1.18.12   172.16.23.31   <none>        Ubuntu 18.04.2 LTS   4.15.18-041518-generic   docker://18.9.8
* Operating System and version:
* |># lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

* Filters and plugins:
show in configuration
**Additional context**

**Comment by zhanghe9702** [comment]
#4505

**Comment by lecaros** [comment]
Hi @zhanghe9702 
The failing node never worked? Or was it working then started to fail?
Have you seen any errors in the failing node? Can you share the log file?

**Comment by zhanghe9702** [comment]
> Hi @zhanghe9702 The failing node never worked? Or was it working then started to fail? Have you seen any errors in the failing node? Can you share the log file?

1.INFO LEVEL log has very limit information
2.no,at start,in this node,pod is working normal,but after a whlie,go to this status
i have gdb contanier process, same call stack info as #2661, so i think should be same problem

**Comment by zhanghe9702** [comment]
#4505

**Comment by lecaros** [comment]
Hi @zhanghe9702 can you confirm you no longer see this in the latest version? (1.8.15, 1.9.1)

**Comment by zhanghe9702** [comment]
@lecaros , you can close it, i solved this issue by increase PIPE resource buffer size, however, in our cluster , fluent-bit also encounter dead status very rare for some unknown reason, i haven' found the root cause:)

**Comment by mcauto** [comment]
Hello :) @lecaros @zhanghe9702 
The conntrack of the netlifer and the tcp_allocated of the socket are constantly increasing. Do you have any additional information?

**Comment by zhanghe9702** [comment]
@mcauto ,i havn't meet that, just flunet-bit pipeline stop work, the title maybe  misleading you, fluent-bit upstream connection should has keep-alive configuration option, you could take a try config short-time `keep-alive`
