### ISSUE TITLE
Can fluent bit support to collect information of docker not in kubenetes

### ISSUE THREAD

**Issue by wst-casd** [fluent/fluent-bit#452]
I know fluent bit can collect log data for Kubernetes and work stable. And if we want to collect data for docker on machine which are not managed by Kubernetes, whether or not fluent bit support it so far.

Thanks for enthusiastic man tell me.

**Comment by jsravn** [comment]
@wst-casd It can collect logs using `tail` from any log file. That is how it works with kubernetes - it tails the docker json log files on disk.

**Comment by wst-casd** [comment]
@jsravn  Thanks. I also want to know whether it support to collect metrics, for example CPU, Disk, Memory of dockers not in kubenetes.
