### ISSUE TITLE
Document tail plugin as not being supported on FreeBSD

### ISSUE THREAD

**Issue by abh** [fluent/fluent-bit#4521]
## Bug Report

Fluent-bit is documented as supporting BSD; but the tail plugin doesn't work on BSD without a mention of this in the documentation.

**To Reproduce**

See #208, #2897, #3774

**Expected behavior**

Documentation being comprehensive (or better the tail plugin working ...).

**Additional context**

I wasted a bunch of time pursuing a fluent-bit configuration just to learn that it wouldn't work on one of our platforms.

There are many functioning tail implementations on FreeBSD, so fluent-bit not supporting it "because of lack of platform support" (as mentioned in #2897) seems a bit ... much.

**Comment by patrick-stephens** [comment]
Do you mean here https://docs.fluentbit.io/manual/installation/supported-platforms? 
`Fluent Bit can work also on OSX and *BSD systems, but not all plugins will be available on all platforms. `

Or was there somewhere it explicitly says it works on FreeBSD? I've had a quick search and cannot see anything. We can probably make it more explicit on the `tail` plugin though over at https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/inputs/tail.md if you want to submit a PR with a `Caveats` section or similar.
