### ISSUE TITLE
Add ability to handle index name template in ES output

### ISSUE THREAD

**Issue by dshmatov** [fluent/fluent-bit#454]
So, as I understand correctly Fluentbit has an ability (if I use `Logstash_Format  True`) to get timestamp from incoming data (e.g. `@timestamp` field). But it would be great to set index template   time format (`index-name-%Y%m%d`) from local host not from incoming data. I don't want to use Logstash format, but I want to handle index name via time or env template from local host.

**Comment by onorua** [comment]
Will that help, if `Index` will support templating similar to  `Logstash_DateFormat`?
Basically if we would treat Index field as `strftime` template instead of just string. That should solve your problem, and unify the approach with fluentd:
```
index_name fluentd-%Y%m%d 
```

**Comment by dshmatov** [comment]
@onorua yep, It would be great!

**Comment by edsiper** [comment]
Fixed by 455eae05
