### ISSUE TITLE
S3 output plugin doesn't work with insecure Minio installation

### ISSUE THREAD

**Issue by nika-nii** [fluent/fluent-bit#4549]
## Bug Report

**Describe the bug**
S3 output plugin causes segmentation fault when uploading logs to S3 with plain http; https works fine.

**To Reproduce**
Use S3 output plugin with http endpoint
Sample config:
```
[OUTPUT]
    Name s3
    Match *
    endpoint http://localhost:9000
    bucket fluentbit
    s3_key_format /%Y/%m/%d/$TAG-%H:%M:%S-$UUID.log
    total_file_size 500M
    upload_timeout 10s
    store_dir .
```
Application command line: `fluent-bit -c config.conf -i cpu`

**Expected behavior**
Logs uploading to S3 without TLS.

**Screenshots**
![A problem](https://user-images.githubusercontent.com/24593943/147571795-359248e1-c698-431c-aa7d-2707885e31f3.png)

**Your Environment**
* Version used: built from master at https://github.com/fluent/fluent-bit/commit/e0f3877b843bf62ccd655ec5761efb5261d162ee

**Additional context**
Got it working changing field `flags` in `out_s3_plugin` struct from `FLB_IO_TLS` to `FLB_IO_OPT_TLS`. Not sure if it breaks something else.

**Comment by agup006** [comment]
Minio insecure support has been merged as part of https://github.com/fluent/fluent-bit/pull/3215, give it a try with `tls_verify false` setting on top of master branch

**Comment by nika-nii** [comment]
Looks like `tls_verify` option is not presented:

```[error] [config] s3: unknown configuration property 'tls_verify'. The following properties are allowed: json_date_format, json_date_key, total_file_size, upload_chunk_size, upload_timeout, bucket, region, role_arn, endpoint, sts_endpoint, canned_acl, compression, content_type, store_dir, s3_key_format, s3_key_format_tag_delimiters, auto_retry_requests, use_put_object, send_content_md5, preserve_data_ordering, log_key, and static_file_path.```

However, i've read carefully https://github.com/fluent/fluent-bit/pull/3215 and found out the recommendation to use `tls off` option, which worked just as expected.

Thanks for help!
