### ISSUE TITLE
Add compatibility for self-hosted OpenSearch servers in "es" output plugin, please!

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit#4550]
This FR is due to being hit by issue https://github.com/fluent/fluent-bit/issues/4336#issuecomment-1001786601
Thanks!

**Comment by q2dg** [comment]
Well, I've configured OpenSearch withouth Security Plugin (as it can be seen here:

![Captura de 2022-01-02 19-16-58](https://user-images.githubusercontent.com/7274874/147885687-9ceb96a8-8313-42b8-a1ea-1bb3f42133a2.png)

and I still get errors when trying to send data from FluentBit to it:

![Captura de 2022-01-02 19-16-29](https://user-images.githubusercontent.com/7274874/147885710-ab1b30f7-f627-4062-bdd5-672afe7d099c.png)

So it's not a problem from TLS/Auth

**Comment by q2dg** [comment]
I show here debug lines using verbose mode in former shown fluent-bit command, for completeness...

![Captura de 2022-01-03 21-59-04](https://user-images.githubusercontent.com/7274874/147979851-12ebe7a6-3fca-4cc7-905e-da4fae48e137.png)

**Comment by q2dg** [comment]
On the other hand, in OpenSearch logs appears this sentence: "Specifying types in bulk requests is deprecated"

**Comment by q2dg** [comment]
I just want to notice that doing a _bulk insert with _curl_ (like it's explained here: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gsgupload-data.html) just works (even using snake-oil TLS certificate) so it's seems clear Fluentbit is doing something wrong when pushing data to OpenSearch.

Thanks, anyway

**Comment by q2dg** [comment]
Well, now I see in https://github.com/fluent/fluent-bit/tree/c6e98c053cb092d4a04f073a02d52fda1cf05c5c/plugins/out_es that last commit was from three years ago! Oh my god! It's time to look for another log forwarder

**Comment by q2dg** [comment]
Adding _compatibility.override_main_response_version:true_ option to OpenSearch (as it's said in https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index) doesn't help, neither
I give up.
I'll let open this issue if someone someday wants to get the challenge

**Comment by patrick-stephens** [comment]
There is some work looking at supporting OpenSearch ongoing at the moment so I'll ping @agup006 so he's aware of this.

**Comment by q2dg** [comment]
It seems solved now (v.1.9.1)
Thanks!
