### ISSUE TITLE
Cannot parse multiline logs from CRI-O 

### ISSUE THREAD

**Issue by raklev20** [fluent/fluent-bit#4551]
In order to parse logs using Kubernetes v1.22 and CRI-O we had some troubles. Currently we are using Fluentbit version 1.8.11 and we defined a custom multiline parser (inspired by: [https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing].) Our logs from container look like this:

```
2021-12-28T10:26:45.134374524+02:00 stdout F 2021-12-28 10:26:45.134 ERROR 1 --- [   scheduling-1] ro.tst.es.MiddlewareWorker               : Topic error events im-to-bo-am 404 Not Found: "{"timestamp":"2021-12-28T08:26:45.131+00:00","status":404,"error":"Not Found","path":"/im/asdad/fetch"}"
2021-12-28T10:26:45.134374524+02:00 stdout F
2021-12-28T10:26:45.134374524+02:00 stdout F org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"timestamp":"2021-12-28T08:26:45.131+00:00","status":404,"error":"Not Found","path":"/im/asdad/fetch"}"
2021-12-28T10:26:45.134374524+02:00 stdout F    at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113) ~[spring-web-5.3.13.jar!/:5.3.13]
2021-12-28T10:26:45.134374524+02:00 stdout F    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.13.jar!/:5.3.13]
2021-12-28T10:26:45.134374524+02:00 stdout F    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.13.jar!/:5.3.13]
2021-12-28T10:26:45.134374524+02:00 stdout F    at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:172) ~[spring-security-oauth2-2.2.1.RELEASE.jar!/:na]
2021-12-28T10:26:45.134374524+02:00 stdout F    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.13.jar!/:5.3.13]
2021-12-28T10:26:45.134374524+02:00 stdout F    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.13.jar!/:5.3.13]

```

Our fluentbit config look like this:

```
input-kubernetes.conf: |
    [INPUT]
        Name              tail
        storage.type      filesystem
        Path              /var/log/pods/*/*/*.log
        Multiline.parser  multiline-regex
        Exclude_Path      /var/log/pods/*monitoring_fluentbit*/*/*.log
        DB                /var/log/flb_kube.db
        Tag               kube.<pod_id>.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         /var/log/pods/(?<namespace_name>[^_/]+)_(?<pod_name>[^_/]+)_(?<pod_id>[^_/]+)/(?<container_name>[^/]+)/.*
        Buffer_Max_Size   5M
        Buffer_Chunk_size 5M
        Mem_Buf_Limit     100m
        Skip_Long_Lines   On
        Refresh_Interval  10

    [MULTILINE_PARSER]
        name           multiline-regex
        type           regex
        parser         cri
        flush_timeout  1000
        rule           "start_state" "/([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3})(.*)/" "cont"
        rule           "cont"        "/\s*org.*/"                                                             "cont"


```
My kindly request for you is to help me to identify what cause the problem, because in Kibana multiline doesn't work as I expected. The final result should look like this:
```

 2021-12-28 10:26:45.134 ERROR 1 --- [   scheduling-1] ro.tst.es.MiddlewareWorker               : Topic error events im-to-bo-am 404 Not Found: "{"timestamp":"2021-12-28T08:26:45.131+00:00","status":404,"error":"Not Found","path":"/im/asdad/fetch"}"
 org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"timestamp":"2021-12-28T08:26:45.131+00:00","status":404,"error":"Not Found","path":"/im/asdad/fetch"}"
    at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113) ~[spring-web-5.3.13.jar!/:5.3.13]
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168) ~[spring-web-5.3.13.jar!/:5.3.13]
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122) ~[spring-web-5.3.13.jar!/:5.3.13]
    at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:172) ~[spring-security-oauth2-2.2.1.RELEASE.jar!/:na]
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.13.jar!/:5.3.13]
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.13.jar!/:5.3.13]

```

My opinion is that the built-in parser cri doesn't work. 
Let me know if you have any questions or doubts. Many thanks in advance.

**Comment by eugenesotnikov** [comment]
Hi. I have same task. Built-in cri doesn't work for spring stacktrace.
I found this "solution". I changed your config. Try this.
This is not good variant, but it is works. I will be glad if someone offers a more beautiful solution.

    [INPUT]
        Name              tail
        storage.type      filesystem
        Path              /var/log/pods/*/*/*.log
        Multiline.parser  cri
        Exclude_Path      /var/log/pods/*monitoring_fluentbit*/*/*.log
        DB                /var/log/flb_kube.db
        Tag               kube.<pod_id>.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex         /var/log/pods/(?<namespace_name>[^_/]+)_(?<pod_name>[^_/]+)_(?<pod_id>[^_/]+)/(?<container_name>[^/]+)/.*
        Buffer_Max_Size   5M
        Buffer_Chunk_size 5M
        Mem_Buf_Limit     100m
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        name                  multiline
        match                 *
        multiline.key_content log
        multiline.parser      multiline_regex

    [MULTILINE_PARSER]
        name           multiline-regex
        type           regex
        flush_timeout  1000
        rule      "start_state"   "/(.*)/"  "cont"
        rule      "cont"          "/^\s+at.*/"  "cont"

**Comment by VitaliZhur** [comment]
@eugenesotnikov I had a similar configuration, but in my case the exception still splitting:

![image](https://user-images.githubusercontent.com/28760259/149374599-39640dde-7f2b-475e-87e6-80eb78fbd027.png)

Configuration:

output.conf: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix h3
        Time_Key        timestamp
        Retry_Limit     False
        tls             On
        tls.verify      Off
        Replace_Dots    On
        Trace_Error     On
        Trace_Output    Off
    

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*_default_*.log,/var/log/containers/*_gatekeeper-system_*.log,/var/log/containers/*_kube-node-lease_*.log,/var/log/containers/*_kube-public_*.log,/var/log/containers/*_kube-system_*.log,/var/log/containers/*_logging_*.log,/var/log/containers/*_logging-elk_*.log,/var/log/containers/*_moon_*.log,/var/log/containers/*_poc_*.log,/var/log/containers/*_sonarqube_*.log
        Tag               kube.*
        read_from_head    true
        DB                /var/log/flb_kube.db
        Multiline.parser  cri
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
        Buffer_Max_Size   5M
        Buffer_Chunk_size 5M
        Mem_Buf_Limit     100m
        Refresh_Interval  10
    
    

  filter-kubernetes.conf: |
    
    [FILTER]
        Name                  multiline
        Match                 *
        Multiline.key_content log
        Multiline.parser      multiline-regex
parsers.conf: |   
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        
    [MULTILINE_PARSER]
        name          multiline-regex
        type          regex
        flush_timeout 1000
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        #
        # rules   |   state name   | regex pattern                   | next state name
        # --------|----------------|--------------------------------------------------
        rule         "start_state"  "^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3})(.*)$"     "cont"
        rule         "cont"         "^(?!(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}))(.*)$" "cont"

**Comment by TimSin** [comment]
I'm facing the same issue. I imagine parsing multiline Java logs from a kubernetes cluster is a pretty common use case, so it would be good to see a definitive example somewhere. The examples in the documentation regarding this feature are pretty sparse at the moment.

**Comment by eugenesotnikov** [comment]
> @eugenesotnikov I had a similar configuration, but in my case the exception still splitting:
> 
> ![image](https://user-images.githubusercontent.com/28760259/149374599-39640dde-7f2b-475e-87e6-80eb78fbd027.png)
> 
> Configuration:
> 
> ```
> output.conf: |
>     [OUTPUT]
>         Name            es
>         Match           kube.*
>         Host            ${FLUENT_ELASTICSEARCH_HOST}
>         Port            ${FLUENT_ELASTICSEARCH_PORT}
>         HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
>         HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
>         Logstash_Format On
>         Time_Key        timestamp
>         Retry_Limit     False
>         tls             On
>         tls.verify      Off
>         Replace_Dots    On
>         Trace_Error     On
>         Trace_Output    Off
>     
> 
>   input-kubernetes.conf: |
>     [INPUT]
>         Name              tail
>         Path              /var/log/containers/*.log
>         Exclude_Path      /var/log/containers/*_default_*.log
>         Tag               kube.*
>         read_from_head    true
>         DB                /var/log/flb_kube.db
>         Multiline.parser  cri
>         Skip_Long_Lines   On
>         Skip_Empty_Lines  On
>         Buffer_Max_Size   5M
>         Buffer_Chunk_size 5M
>         Mem_Buf_Limit     100m
>         Refresh_Interval  10
>     
>     
> 
>   filter-kubernetes.conf: |
>     
>     [FILTER]
>         Name                  multiline
>         Match                 *
>         Multiline.key_content log
>         Multiline.parser      multiline-regex
> parsers.conf: |   
>     [PARSER]
>         Name        cri
>         Format      regex
>         Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
>         Time_Key    time
>         Time_Format %Y-%m-%dT%H:%M:%S.%L%z
>         
>     [MULTILINE_PARSER]
>         name          multiline-regex
>         type          regex
>         flush_timeout 1000
>         # Regex rules for multiline parsing
>         # ---------------------------------
>         #
>         # configuration hints:
>         #
>         #  - first state always has the name: start_state
>         #  - every field in the rule must be inside double quotes
>         #
>         #
>         # rules   |   state name   | regex pattern                   | next state name
>         # --------|----------------|--------------------------------------------------
>         rule         "start_state"  "^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3})(.*)$"     "cont"
>         rule         "cont"         "^(?!(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}))(.*)$" "cont"
> ```

With my config I got this result
![image](https://user-images.githubusercontent.com/60689184/149883290-7cf4c745-88fe-4e64-ae50-e7c803af37fb.png)

**Comment by TimSin** [comment]
I've taken a similar approach to you using the config below, with similar results. When using a filter, the logs are duplicated, with one multiline entry being correctly formatted, and the log entries being received again as separate lines, which makes sense as the `tail` input `cri` parser would have generated the duplicated set of log entries. When I place the `multiline_regex` parser directly on the `tail` input, the log entries are no longer correctly formatted as I'm taking the log format into account in my regex, rather that the entire log entry output from k8s.

I think what's required here is the ability to chain parsers together. What I want to do is to use the `cri` parser to extract the log information from the k8s container logs, and then run a regex multiline parser on the extracted log information to perform the multiline transformation. I could go ahead and combine the cri and multiline parsing into one regex, but at that point it becomes too complex and unwieldy.

```
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        # This is the point at which I want to be able to chain parsers as the transformation has to 
        # happen here, rather than in a multiline filter. My particular use case would be cri -> multiline_regex
        multiline.parser  multiline_regex
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```

 ```
  parsers-multiline.conf: |
       [MULTILINE_PARSER]
        name           multiline-regex
        type           regex
        rule      "start_state"   "^(?<time>\d+(?:-\d+){2}\s+\d+(?::\d+){2}\.\d+)\s*(?<level>\S+) (?<correlationId>\[.*\] )?(?<pid>\d+) --- \[(?<thread>[\s\S]*?)\] (?<class>\S+)\s*:\s*(?<message>[\s\S]*?)(?=\g<time>|\Z)"  "cont"
        rule      "cont"          "/^\s+at.*/"  "cont"
```
```
  filter-kubernetes.conf: |
    [FILTER]
        name                  multiline
        match                 *
        multiline.key_content log
        multiline.parser      multiline_regex

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Buffer_Size         0
        Kube_URL            https://kubernetes.default.svc
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
```

**Comment by TimSin** [comment]
I've done some more work on this and got an almost fully functional config. This uses a multiline parser to construct the data from the `tail` input plugin. It then uses a filter to try and strip the additional log info that is left behind (for example `2022-01-18T18:43:21.697964822Z stderr F `) from the k8s logs. Unfortunately this only works on the first line, and there isn't the option to enable the global flag on a regex as far as I can see. I'm also filtering out some namespaces with the additional filters.

```
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers-multiline.conf
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        multiline.parser  cri_multiline_regex
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name parser
        Match *
        Key_Name log
        Parser cleanup

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Buffer_Size         0
        Kube_URL            https://kubernetes.default.svc
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        Name         nest
        Match        *
        Operation    lift
        Nested_under kubernetes

    [FILTER]
        Name    grep
        Match   *
        Exclude namespace_name ingress-nginx

    [FILTER]
        Name    grep
        Match   *
        Exclude namespace_name spinnaker

    [FILTER]
        Name    grep
        Match   *
        Exclude namespace_name elastic-logs

    [FILTER]
        Name    grep
        Match   *
        Exclude namespace_name kube-system

    [FILTER]
        Name    grep
        Match   *
        Exclude namespace_name lens-metrics

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWD}
        tls             On
        tls.verify      Off
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False

  parsers-multiline.conf: |
    [MULTILINE_PARSER]
        name          cri_multiline_regex
        type          regex
        flush_timeout 10000
        key_content   log

        rule      "start_state"   "^(?<time>.+) (?<stream>stdout|stderr) (?<_p>F|P) (?<message>.*)$" "cont"
        rule      "cont"          "^(?<time>.+) (?<stream>stdout|stderr) (?<_p>F|P) (?<message>\s+at.*)$" "cont"

  parsers.conf: |
    [PARSER]
        Name cleanup
        Format regex
        Regex (?<time>.+) (?<stream>stdout|stderr) (?<_p>F|P) (?<log>(.|\n)*)
        Types log:string
```
The output of this looks like the following:

```
com.yyyy.exception.NotFoundException: Project with id XXX not found
  2022-01-18T18:43:21.697964822Z stderr F 	at com.yyyy.ProjectController.getProject(ProjectController.java:135)
  2022-01-18T18:43:21.698208916Z stderr F 	at jdk.internal.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
  2022-01-18T18:43:21.698536694Z stderr F 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  2022-01-18T18:43:21.698681894Z stderr F 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  ...
```

**Comment by ajurge** [comment]
We also have a similar issue when parsing Spring logs on EKS as described above.  None of the fluent-bit configs work properly: 

The following config uses default fluent bit parsers from https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf however some exceptions are still split into separate entries

```
[INPUT]
  Name                        tail
  Path                           /spring.log
  Parser                        cri
  Read_From_Head      true

[FILTER]
    Name                         multiline
    Match                         *
    multiline.key_content message
    multiline.parser          java

[OUTPUT]
  Name  es
  Host  elasticsearch
```
` {
                "_index": "fluent-bit",
                "_type": "_doc",
                "_id": "0bHV338Bpi24tssXLy-y",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2022-03-24T14:34:46.911Z",
                    "stream": "stdout",
                    "logtag": "F",
                    "message": "2022-03-24 14:34:46.911 ERROR 1 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Get items with exception always throws an exception.] with root cause"
                }
            },
            {
                "_index": "fluent-bit",
                "_type": "_doc",
                "_id": "0rHV338Bpi24tssXLy-y",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2022-03-31T11:56:03.896Z",
                    "log": "2022-03-24T14:34:46.911527783Z stdout F"
                }
            },
            {
                "_index": "fluent-bit",
                "_type": "_doc",
                "_id": "07HV338Bpi24tssXLy-y",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2022-03-24T14:34:46.911Z",
                    "stream": "stdout",
                    "logtag": "F",
                    "message": "java.lang.RuntimeException: Get items with exception always throws an exception.\n at com.swisscom.blu.service.ItemsService.getItemsWithException(ItemsService.java:45) ~[classes/:na]\n        at com.swisscom.blu.controller.ItemsController.getItemsWithException(ItemsController.java:31) ~[classes/:na]\n        at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source) ~[na:na]\n        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]\n        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]\n        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.15.jar:5.3.15]\n  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.15.jar:5.3.15]\n at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.15.jar:5.3.15]\n at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]\n        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.15.jar:5.3.15]\n        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.6.3.jar:2.6.3]\n        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.15.jar:5.3.15]\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]"
                }
            },
            {
                "_index": "fluent-bit",
                "_type": "_doc",
                "_id": "1LHV338Bpi24tssXLy-y",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2022-03-31T11:56:03.896Z",
                    "log": "2022-03-24T14:34:46.912539677Z stdout F"
                }
            },
            {
                "_index": "fluent-bit",
                "_type": "_doc",
                "_id": "1bHV338Bpi24tssXLy-y",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2022-03-31T11:56:03.896Z",
                    "log": "sh-4.2# tail -f backend-6db6b986d4-lc9vp_dev_app-f3cae65d463c267a501d3ed16d077a75afd192cc3629bc4000880d4168a29134.log"
                }
            },
            {
                "_index": "fluent-bit",
                "_type": "_doc",
                "_id": "1rHV338Bpi24tssXLy-y",
                "_score": 1.0,
                "_source": {
                    "@timestamp": "2022-03-24T14:34:46.911Z",
                    "message": "        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.56.jar:9.0.56]\n at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]"
                }
            },`


It would be really appreciated if fluent-bit could support such use cases out of the box. Or perhaps i have configured something wrong in this case could someone please provide some suggestions?

**Comment by geowalrus4gh** [comment]
This is not stale. Please provide a sample for Java error stack trace in CRI pattern

**Comment by duj4** [comment]
@andreifer20 may I know if you've solved this issue yet?

**Comment by andreifer20** [comment]
Haven't solved it yet :(

**Comment by duj4** [comment]
hi @andreifer20 ,

I just found a way out for my stack logs.

Original logs:
![image](https://github.com/user-attachments/assets/cf873633-7f26-4e49-b2be-32a8be1ebbfb)

Configuration:
![image](https://github.com/user-attachments/assets/bb9dfab5-26cd-4733-b751-2029477ffd2c)

After processing:
![image](https://github.com/user-attachments/assets/e3ea87ac-83e9-43d5-be25-c68072538f63)

In json format:
![image](https://github.com/user-attachments/assets/0aab50e4-b5ab-4ecd-812a-3ae277e37e7d)

Hope this helps.

**Comment by mohannara** [comment]
Hi @duj4 ,
I am getting the below error. It seems processors doesn't support classic but yaml configurations.
[2025/01/07 12:15:00] [error] [config] error in /fluent-bit/etc/..2025_01_07_12_14_42.905077529//application-log.conf:15: undefined value - check config is in valid classic format

I'am using below image.  does it support fluentbit 1.9.10?  Could you please share the image you used here?
image --> public.ecr.aws/aws-observability/aws-for-fluent-bit:stable

Thanks.

**Comment by duj4** [comment]
> Hi @duj4 , I am getting the below error. It seems processors doesn't support classic but yaml configurations. [2025/01/07 12:15:00] [error] [config] error in /fluent-bit/etc/..2025_01_07_12_14_42.905077529//application-log.conf:15: undefined value - check config is in valid classic format
> 
> I'am using below image. does it support fluentbit 1.9.10? Could you please share the image you used here? image --> public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
> 
> Thanks.

hi @mohannara ,

I am using Fluent-Bit image with version 3.2.2 as since 3.2.1 it starts support YAML fully along with pipeline mode, I am afraid 1.9.10 does not.
