### ISSUE TITLE
Increase in memory and receive bandwidth over time

### ISSUE THREAD

**Issue by srinidhis94** [fluent/fluent-bit#4570]
## Bug Report

**Describe the bug**
 I am seeing an increase in memory in our fluentbit pods over time. From our monitoring dashboard, there seems to be some correlation between receive bandwidth of the pod and increasing memory usage. Our configuration is we tail the files as input, we have some filters and have our custom plugin to write the logs to gcs. I am not sure why the receive bandwidth is increasing linearly over time, while transmit bandwidth is not showing the same behaviour {ideally i was expecting only transmit bandwidth to be significant as we're reading from disk and we're uploading it and received bandwidth should be whatever response we get while uploading logs which should be very insignificant and shouldn't increase linearly }. Can you guys provide any insights as to how I can proceed further ?

**To Reproduce**
- We're able to consistently reproduce this in cases where we're logging a lot. Larger the rate at which logs are added to input files, greater is the increase in memory. 
- We've also seen some cases where it increases to some extent and eventually stabilises.
- We wanted to have a consistent resource utilisation irrespective of log size by using buffering. 

- Steps to reproduce the problem:
    -  Run a pod which produced logs at a size of about 3MB/s.
    -  Run fluentbit as daemonset. We can provide our docker version with our custom plugin. But we've verified using go pprof that our plugin is not responsible for majority of the memory usage while it's still pretty high. The entire container is consuming around 2.5GB and using pprof, we saw that our output plugin is utilising around 900Mb. We couldn't figure how much memory is used by various other components {INPUT,BUFFER,FILTER}. Also we're trying to identify what's accounting for this 900Mb. None of the memory usage is related to our core changes and it's related to buffered writer by grpc transport / tls handshake verification. I have attached pprof report if you'd like to have a look at it.
    - Over time we observe that both receive bandwidth and memory utilised by fluentbit daemonset keeps increasing. It increases even up to 4GB which is the limit we've set for the pod and it gets killed due to OOM issue.

**Expected behavior**
     - Irrespective of input log size, we'd like to have a linear usage in memory.
     - I believe 4GB memory should be more than sufficient to handle our load and we should make use of buffers.
     - Since we read from file and upload to gcs bucket, we expect receive bandwidth to be less and not increase over time. In our case, it is increasing upto 500kB/s over time.

**Screenshots**
![image](https://user-images.githubusercontent.com/16812641/148219918-70fe009a-12cb-4750-ba47-daf27a610185.png)

![pprof001](https://user-images.githubusercontent.com/16812641/148222631-ad012bba-b125-45f0-8634-5f2b4ee202f4.png)

**Your Environment**

* Version used: Using fluent/fluent-bit:1.7.7-debug as base docker
* Configuration:
```
fluent-bit.conf: |
    [SERVICE]
        Flush        {{ $service.service.flush_interval }}
        Log_Level    debug
        Parsers_File parsers.conf
        storage.path /var/log/fluent-bit/
        storage.sync normal
        storage.checksum Off
        storage.max_chunks_up 256
        storage.backlog.mem_limit 100MB
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-forward.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               dam/<namespace_name>/<component>
        Tag_regex         \/var\/log\/pods\/(?<namespace_name>[^_]+)_(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<id>[\-a-z0-9]+)\/(?<component>[-a-zA-Z0-9]+)\/.*.log
        Path              /var/log/pods/*/*/*.log
        Exclude_Path     /var/log/pods/kube-system*/*/.*.log,/var/log/pods/*istio-system_*/*/.*.log,/var/log/pods/*knative-serving*/*/.*.log,/var/log/pods/*gke-system*/*/.*.log,/var/log/pods/*config-management-system*/*/.*.log
        DB                /tmp/fluentbit_daemonset.db
        Parser            cri
        storage.type      filesystem
        Mem_Buf_Limit     250MB
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Buffer_Chunk_Size 50MB
        Buffer_Max_Size   100MB
  filter-kubernetes.conf: |
    [FILTER]
        Name parser
        Match dam/*
        Parser json
        Key_Name log
        Reserve_Data True
  output-forward.conf: |
    [OUTPUT]
        Name          gcs
        bucket        {{ $.Values.setup }}-logs-bucket
        prefix        k8s
        FilterErrors  True
        ProjectID     {{ $.Values.project}}
        TopicName     {{ $.Values.setup }}-{{ $.Release.Namespace }}-component-error-logs
        Match         dam/*
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   Off
    [PARSER]
        Name        json
        Format      json
``` 
* Environment name and version (e.g. Kubernetes? What version?): 1.20.10-gke.1600
* Server type and version:
* Operating System and version: Running docker built using fluent/fluent-bit:1.7.7-debug as base docker.
* Filters and plugins: We're using custom output plugin to upload to gcs.

**Additional context**

- We don't know what's the memory we should provide to the pod to handle this gracefully as it keeps increasing. We've provided high ram so that it doesn't restart frequently. But if we can optimise this, it'd save a lot of cost. We might also lose logs at the time of restart.

**Comment by edsiper** [comment]
if you use a built-in output plugin do you face the same issue ?

We have seen on some cases it's due the use of custom plugins, not sure what `gcs` is.

**Comment by srinidhis94** [comment]
gcs is the name of our custom plugin but will get back to you after using one of  the default output plugin
