### ISSUE TITLE
Start package name migration: td-agent-bit to fluent-bit

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#4571]
For the upcoming Fluent Bit 1.9 packages, we will start the transition from `td-agent-bit` to `fluent-bit` packages. 

For some months (TBD) we will package both variants at the same time, so current users can still use `td-agent-bit` while we will encourage new users to use `fluent-bit`. 

The packaging process will be performed by the new CI system.

refs:

```
- -DFLB_TD=On -> it will package as td-agent-bit
- Default -> it will package as fluent-bit
```

**Comment by patrick-stephens** [comment]
The simple approach above of just building everything with different flags is low risk and straightforward at the cost of doubling build time/resources. This is likely good enough though particularly as we are going to be deprecating the `td-agent-bit` package anyway so any work may be wasted effort (unless we want to do other things in the future).

It may be an idea to explore the alternative approach of reusing the `fluent-bit` package that is built and providing a `td-agent-bit` package that only contains configuration and depends on the `fluent-bit` package so it installs all the binaries. This is more work and may require changes to support configuration in `fluent-bit` (e.g. to allow for customisation of paths, service name, etc.) package.

**Comment by patrick-stephens** [comment]
It looks like we'll need to support some customisation of the build process as currently this is all using hardcoded flags within the container building each target. It's probably a good idea to have some general customisation support so we can turn flags on/off more easily anyway.

E.g. https://github.com/fluent/fluent-bit/blob/master/packaging/distros/debian/bullseye/Dockerfile#L23
```
    cmake  -DCMAKE_INSTALL_PREFIX=/opt/td-agent-bit/ -DCMAKE_INSTALL_SYSCONFDIR=/etc/ \
           -DFLB_RELEASE=On -DFLB_TRACE=On -DFLB_TD=On \
           -DFLB_SQLDB=On -DFLB_HTTP_SERVER=On \
           -DFLB_OUT_KAFKA=On \
           -DFLB_OUT_PGSQL=On ../
```
In this case some of these parameters can be using build-args with default values to allow us to easily override them. For our usage here we primarily need the `-DFLB_TD=${FLB_TD}` where `ARG FLB_TD=On` to give a default of the current value then we invoke this build container twice: once with it `On` and once with it `Off`
