### ISSUE TITLE
modify: add tag/regex to ADD field in modify plugin

### ISSUE THREAD

**Issue by ridwanmsharif** [fluent/fluent-bit#4572]
**Is your feature request related to a problem? Please describe.**
 In Fluent Bit, We should add support for a way to add a key to a record that can use the value of the Tag. Currently, The modify filter allows you to add a key with a string value that is specified in the config. It would be useful to have this value be a regex string that can reference the Tag. This is similar to the `rewrite_tag` plugin that allows the New Tag to use the old tags value using the string $TAG in the regex.

**What exactly do you need?**
We have log records with the following tag: <pipeline_id>.<receiver_id>.<some_arbitrary_string>
We would like to add a field to the record with the key `logging.googleapis.com/logName` valued to: <receiver_id>.<some_arbitrary_string>

The <some_arbitrary_string> above is not something _known_ at the time of config generation. These come from the log record itself. The tags aren't controlled by the Ops Agent but rather by the clients own Fluent[d/Bit] system they forwarded to us from.

**Describe the solution you'd like**
_NOTE: This might be very perf draining. Its an example solution that shows one way this can be achieved but it likely is better to introduce new syntax and language so records can be modified using other fields in the records as well._

Ability to add a key value pair to the log record that can use the tag as the value. 
In the example above the value for the new key is a subset of the Tag on the record. This would be possible if the Modify filter supported the following syntax
```
[FILTER]
Name   modify
Match  ^(pipeline_id).(receiver_id).(.*)$
Add    logging.googleapis.com/logName $1.$2
```

Context for the question: For the Ops Agent we want to preserve the Tags of records ingested by the Forward receiver (since logs already come with tags), and we were thinking of doing that by having the logName (special key that the ops agent configures) contain the tag the record came with.

**Describe alternatives you've considered**
Primary alternative:
- We would not set the logName to anything in the Ops Agent configuration where input is from the forward plugin.
- We would then at the end of all processors rewrite_tag the tag from pipeline_id.receiver_id.... to receiver_id....
- the stackdriver output plugin would then use the logName from the tag

Cons:
- Other processors can't assume in out pipeline that logName is set correctly
- The new record with the tag receiver_id.... makes its way through the whole system just to get to the stackdriver output
- rewrite_tags introduced issues in the past

Alternative2: In the forward plugin - there could be an option to add a key which which would be added to the log record with the tag (but we need the tag plus the receiver_id).

Alternative 3: The Add value string could use other fields in the record like $name.$id. And separately the Forward input plugin could optionally allow the user to add a key which will store the old tag (which will)

**Comment by qingling128** [comment]
We managed to get things work with the LUA script. Closing this one for now, as it probably won't be more performant than the current implementation we have.

**Comment by sudeshjethoe** [comment]
Curious to know how you managed to do this with LUA, perphaps you could share the LUA script for reference?
