### ISSUE TITLE
How to use HTTP output plugin to send data to OpenSearch (Before: Add missing "Exec" output plugin)

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit#4575]
I'd want to execute a command every time a new line is detected in origin (at the end of a file by Tail input plugin, for instance).

(In fact, what I want is to send every new line that appears on origin to a remote OpenSearch server by using _curl -X POST_)

Thanks.

**Comment by patrick-stephens** [comment]
It feels like https://docs.fluentbit.io/manual/pipeline/outputs/http might be a better fit, possibly with an update/extension to provide more configurable output. Or really the ES output plugin but sending to Opensearch rather than Elastic version.

I'm not sure executing bespoke commands is a good fit - it'll impact security and also things like storage/buffering, what happens on failure, etc.. However please expand the details of the use case a bit so we can clarify what's required.

**Comment by q2dg** [comment]
Thanks! I've see the http plugin, surely it'll fit my needs, thanks!
As I said in https://github.com/fluent/fluent-bit/issues/4550 , currently "es" is not an option, sadly.
Taking into account what you say about security impact and storage/buffering issues, I'll close this issue as it seems it's not a valid generic proposal...if http plugin can send data to be indexed into OpenSearch, I'll be fine.
Thanks again!

**Comment by q2dg** [comment]
Well, I reopen the issue because I have problems.

If I do: _fluent-bit -i cpu -t cpu -o http -p Host=192.168.1.148 -p Port=9200 -p Uri=anIndex/_bulk -p Format=json -p HTTP_User=admin -p HTTP_Passwd=admin -p Tls=on -p Tls.verify=off -m "*"_  against my OpenSearch server, I get this error:
"
![Captura de 2022-01-06 12-43-56](https://user-images.githubusercontent.com/7274874/148378054-00116c69-43d4-4dfe-94a6-2a37da80626f.png)

If I change Format= value by "json_lines", I get this error instead:

![Captura de 2022-01-06 12-45-27](https://user-images.githubusercontent.com/7274874/148378244-3a73e62b-c719-4d43-be02-4cccb4f2ca10.png)

Other formats complain about illegal characters. Adding _-p Header=Content-type:whatever_ argument doesn't solve this issue, neither

I've seen in ElasticSearch forum that using curl first error was solved manually adding Content-Type=application/x-ndjson AND replacing "-d" argument with "--data-binary" ...I don't know if this can be a clue...

Thanks, and sorry!

**Comment by q2dg** [comment]
I've tried this, which seems the most reasonable format: _fluent-bit -i cpu -t cpu -o http -p Host=192.168.1.148 -p Port=9200 -p Uri=anIndex/\_bulk **-p Format=json_lines -p Header=Content-Type=application/x-ndjson** -p HTTP_User=admin -p HTTP_Passwd=admin -p Tls=on -p Tls.verify=off -m "*"_  but I get this error from OpenSearch and I don't know how to suppress http headers from messages generated by FluentBit inside FluentBit.

![Captura de 2022-01-06 15-41-54](https://user-images.githubusercontent.com/7274874/148400128-34e86ff9-caf7-4a23-9432-a2c85f1c6eac.png)

**Comment by q2dg** [comment]
Well, I think that I can achieve my particular goal of sending data to an OpenSearch server from Fluentbit, but not through the "http" output file but with the "file" output file using the "plain" format, and then running (asynchronously!!) this command: _curl -X POST -u "admin:admin" -k --data-binary @data.txt -H "Content-Type:application/json" https://192.168.1.148:9200/anindex/\_bulk_  where "data.txt" is the file generated by "file" output.

BUT, doing this, I first had this error "The bulk request must be terminated by a newline" which is the same that former error I had using "http". Fortunately, now I've recongnized the issue: before each line another line should be inserted to be compliatn with bulk API, this one: _{ "index":{}}_  Adding manuallyt (with sed) this line to "data.txt" and rerunning former curl command has been a success, finally.

So I infer that if a achieve some kind of FluentBit filtert that could add this line ({"index":{}}) before every document is sent to OpenSearch, I could use raw http output server to fill an index.

I'll keep this issue open until I get the needed filter and then I'll post here, to complete the journey.
Thanks!

**Comment by q2dg** [comment]
Well, bad news. 
Having a "data.json" with the right format (as explained in above post) doesn't work with this command: 
 _fluent-bit -i tail -p path=dades.json -o http -p Host=192.168.1.148 -p Port=9200 -p Uri=anindex/\_bulk -p Format=json -p HTTP_User=admin -p HTTP_Passwd=admin -p Tls=on -p Tls.verify=off -m "_

The error is exactly the same ("The bulk request must be terminated by a newline") than when running curl command with -d argument instead of --data-binary. So I suspect Fluentbit's http output plugin doesn't send data as curl --data-binary does.

I can't keep on with this output plugin, therefore. I'll stick with manual executions of curl by pushing data from a file previously saved by Fluentbit (and processed to ad the line "i{ndex{}}" I don't know how yet

Thanks

**Comment by q2dg** [comment]
Well, I kinda solved the problem of not being able to send data to an OpenSearch server with this ugly hack:

**1.-** I run FluentBit with an output of "file" type with "plain" format. Be sure saved records have a timestamp field. For instance:

fluent-bit -i cpu -F record_modifier -p "record=timestamp $(date '+%Y-%m-%dT%T.%NZ')" -m "*" -o file -p dades.json -p format=plain

**2.-** I run this script, which continously watches new content appended to above file. When it detects new data, it uses sed to  format the lines in order to be accepted through the opensearch's "_bulk" API (basically, I prepend the line {"index":{}} before every document to be sent) and then sends it to the OpenSearch server using raw curl request.. This script needs three parameters: the watched file name, the OpenSearch server IP address and the index name where sent data will be indexed.

```
#!/bin/bash
#"Inotify-tools" package must have been installed before to be able to run this script

if [[ $# -ne 3 ]]; then
    echo "Usage: $0 watched_json_file OS_IP_address index_name"
    exit 1
fi

if [[ ! -f $1 ]]; then 
    touch $1;
else
    rm $1 && touch $1
fi

while [[ true ]]; do
    inotifywait -q -e modify $1
    sed -i "1,$ i {\"index\":{}}" $1
    curl -X POST -u "admin:admin" -k --data-binary @$1 -H "Content-Type:application/x-ndjson" https://$2:9200/$3/_bulk
    rm $1 && touch $1
done

```

And that's all. I'll close this issue, taking into account that there is this one still opened: https://github.com/fluent/fluent-bit/issues/4550
