### ISSUE TITLE
ci: integration test for GCP is failing (terraform)

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#4576]
## Bug Report

https://github.com/fluent/fluent-bit/runs/4723271722?check_suite_focus=true#logs

**Comment by edsiper** [comment]
hmm another issue, not sure if related:

https://github.com/fluent/fluent-bit/runs/4723360683?check_suite_focus=true

**Comment by patrick-stephens** [comment]
Entirely my fault, it's picking up the self hosted runners due to the label used so I'll resolve that to limit their usage.
