### ISSUE TITLE
How to collect Docker  Metadata information？

### ISSUE THREAD

**Issue by linuxxin** [fluent/fluent-bit#4580]

**Comment by linuxxin** [comment]
I need to collect docker logs separately, but no metadata information is found

**Comment by lecaros** [comment]
Hi @linuxxin we'd like to keep these issues for bugs and feature requests. A good place for questions would be http://slack.fluentd.org/ or StackOverflow.

**Comment by linuxxin** [comment]
> 嗨@linuxxin我们想保留这些问题的错误和功能请求。提问的好地方是http://slack.fluentd.org/或 StackOverflow。

Do we not support the collection of docker metadata information?  You still need to configure it
