### ISSUE TITLE
Add to "modify" filter the ability to set a new key value derived from the old one, please

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit#4587]
Currently, with Set option we can overwrite the value of an existing key by an arbitrary new value.
What I propose is that we can reuse the old value to establish the new value from it, "à la s/../../ of sed".

I mean...for instance we could prepend or append the old value with some strings to get the new value, or upper/lower it, etc. 
There are many possibilities...maybe too much, but I think some kind of "transformations" over input values could be a great enhancement to filter capabilities of Fluenbit.

Many thanks!

**Comment by nokute78** [comment]
>  some kind of "transformations" over input values

I think filter_lua helps your use case.
https://docs.fluentbit.io/manual/pipeline/filters/lua

**Comment by q2dg** [comment]
Oh, I see.
Thanks a lot!
Sorry for the inconvenience, I'll close the issue, then
