### ISSUE TITLE
out_nats: protocol info before TLS handshake

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#46]
When a connection is issued to a NATS server, the client receives an INFO message as soon the connection is established, e.g:

``` json
{"server_id":"e1d84d38a2c8f11f4209f079d8c82203",
 "version":"0.7.5",
 "go": "go1.5.3", 
 "host":"0.0.0.0", 
 "port":4449,
 "auth_required":true,
 "ssl_required":true,
 "tls_required":true,
 "tls_verify":true,
 "max_payload":1048576
}
```

so based on this information the client (out_nats) must be able to switch to TLS mode. Fluent Bit already supports TLS but we need a tweak to do:
- connect to NATS server
- parse INFO message
- if TLS is enable, use Fluent Bit I/O TLS support, otherwise raw TCP backend

**Comment by edsiper** [comment]
NATS + TLS support will come in v0.8

**Comment by edsiper** [comment]
Marking this enhancement request as "wonfix-until-requested", meaning, we will reconsider it implementation until some users really require it.

**Comment by jm-amt** [comment]
Is TLS for the NATS output still not supported?
