### ISSUE TITLE
Please, homogenize case-sensitiveness for key names in filter's options

### ISSUE THREAD

**Issue by q2dg** [fluent/fluent-bit#4602]
For instance, the key name written in record_modifier filter's "allowlist_key" option is case-insensitive while the same element in grep filter's "regex" option or rewrite_tag filter's "rule" option are case-sensitive instead. It's a mess. Please choose a standard and go for it.
Thanks!

**Comment by trallnag** [comment]
Overall documentation of case sensitivity would be great. For me it is not even clear if the "core" keys are all case-insensitive. Also there does not seem to be a recommendation on what to use.

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/format-schema

**Comment by adrian-skybaker** [comment]
Would be good to at least document the approach, I can't really work it ou.

**Comment by q2dg** [comment]
Closing issues because they are stalled is lousy
