### ISSUE TITLE
Add language support in Multiline parser

### ISSUE THREAD

**Issue by sophieyfang** [fluent/fluent-bit#4611]
**Is your feature request related to a problem? Please describe.**
For test.log shown as below,  the java stacktraces scattered across multiple **structured logs**. 
Currently there is no way to use the [built-in-multiline-parsers](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#built-in-multiline-parsers) on such case. 

```
{"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z", "my_message": "Dec 14 06:41:08 Exception in thread \"main\" java.lang.RuntimeException: Something has gone wrong, aborting!"
{"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z", "my_message": "    at com.myproject.module.MyProject.badMethod(MyProject.java:22)"
{"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z", "my_message": "    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)"
{"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z", "my_message": "    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)"
{"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z", "my_message": "    at com.myproject.module.MyProject.someMethod(MyProject.java:10)"
{"key1": 12345, "key2": "abc", "time": "2006-07-28T13:22:04Z", "my_message": "    at com.myproject.module.MyProject.main(MyProject.java:6)"
```
**Describe the solution you'd like**
Add another optional field `language` into the multiline-parsers and make fields `rules` and `type` optional
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing#configurable-multiline-parsers
#### main.conf
```
[SERVICE]
    flush                 1
    log_level             info
    parsers_file          parsers.conf

[INPUT]
    name                  tail
    path                  test.log
    read_from_head        true
    multiline.parser      multiline-regex-test

[OUTPUT]
    name                  stdout
    match                 *
```
### parsers.conf
```
[PARSER]
    Name        parse_json_0
    Format      json
[MULTILINE_PARSER]
    name          multiline-regex-test
    key_content   my_message
    language          java
    parser        parse_json_0 
    flush_timeout 1000
```

**Describe alternatives you've considered**
@qingling128 another way to solve without any code change in fluent-bit when client has such test.log shown as above and client enables detecting java exception. Underneath in ops-agent main.conf file(a file we hide it from client), we write the rules that match any java exceptions. 

**Additional context**
This is a common customer use case

**Comment by qingling128** [comment]
Do you know what the difference is between https://github.com/fluent/fluent-bit/blob/master/src/multiline/flb_ml_parser_java.c and https://github.com/fluent/fluent-bit/blob/master/src/multiline/flb_ml_mode_java.c? The content seems relatively identical. Only java has the mode_XX.c file. Other languages do not have it (We are trying to see if we can use custom rules to bypass the limitation above,)
