### ISSUE TITLE
[tail] Support adding the original log file path as a log entry label

### ISSUE THREAD

**Issue by qingling128** [fluent/fluent-bit#4612]
**Is your feature request related to a problem? Please describe.**
When users use a blob / wildcard in the `path` config of the tail plugin, they no longer can tag the files differently. As a result, it's hard to distinguish logs from different files.

**Describe the solution you'd like**
A new feature in the tail plugin to support adding log file path as a log entry label. e.g.

```
[INPUT]
    Name                            tail
    Path                            /var/log/my-app/*.log
    Tag                             my-app
    RECORD_FILE_PATH                true
```

**Describe alternatives you've considered**
The workaround is for users to list all logs files and tag them individually. The downside is that when a new log file is created, they need to re-configure and restart Fluent Bit on all applicable VMs.

**Additional context**
We have a few customers who ask for this feature.

**Comment by patrick-stephens** [comment]
Previously I've used the `Path_Key` setting for this: https://docs.fluentbit.io/manual/pipeline/inputs/tail
Not sure I see how this setting is different? Is it just the tagging aspect, again I'm not sure I follow what specifically is requested so be good to have examples with different log files to show what you mean?

**Comment by qingling128** [comment]
OH! I did not realize this config exists (browsed the documentation too quickly. Thought it was a structure log entry field key). NVM. Silly me. Closing this.

**Comment by patrick-stephens** [comment]
Ah right, glad it already exists so I'll close.
