### ISSUE TITLE
Intermittent upstream connection errors

### ISSUE THREAD

**Issue by JonKusz** [fluent/fluent-bit#4613]
## Bug Report

**Describe the bug**

In a single Fluent-bit pod, part of a DaemonSet, I am seeing the following error intermittently. 

```
[2022/01/14 03:35:38] [ warn] [net] getaddrinfo(host='kubernetes.default.svc.cluster.local'): Name or service not known
[2022/01/14 03:35:38] [error] [filter:kubernetes:kubernetes.0] kubelet upstream connection error
```
This issue appears to happen intermittently, and only for a minute or so, afterwards the kubernetes filter functions correctly and can pull metadata as expected. 

I also see that on pod start, connectivity is otherwise fine, which leads me to believe this is not a configuration error. I have also verified that DNS is able to resolve `kubernetes.default.svc.cluster.local` and no other workloads appear to have any issues with DNS resolution.

```
[2022/01/13 20:47:04] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc.cluster.local port=443
[2022/01/13 20:47:04] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2022/01/13 20:47:09] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2022/01/13 20:47:09] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
```

**To Reproduce**

- Deploy Fluent-bit using the [aws-for-fluent-bit](https://github.com/aws/eks-charts/tree/master/stable/aws-for-fluent-bit) helm chart, using helm chart version 0.1.11.
- I am using the default pre-configured Kubernetes filter that the chart creates.
- This issue generally happens at random, so you may need to wait a few hours for the issue to happen.

**Expected behavior**

I expect `filter:kubernetes:kubernetes.0` to maintain its connectivity to `kubernetes.default.svc.cluster.local` for the duration of the pods lifetime.

**Your Environment**
* Version used:
  - aws-for-fluent-bit helm chart: 0.1.11
  - Container image: amazon/aws-for-fluent-bit:2.13.0
* Environment name and version (e.g. Kubernetes? What version?): 
  - AWS EKS 1.19.
* Filters and plugins: 
  - tail inputs
  - kubernetes filter
  - cloudwatch output.

**Comment by JonKusz** [comment]
It looks like issue #2369 is related, however no resolution was determined.

**Comment by lecaros** [comment]
Hi @JonKusz,
Do you still see this using the latest version?
Can you reproduce this issue at will?

It seems to be a network issue, tho.

**Comment by JonKusz** [comment]
Bump.
