### ISSUE TITLE
Support regular expressions in Lua

### ISSUE THREAD

**Issue by jefferbrecht** [fluent/fluent-bit#4615]
**Is your feature request related to a problem? Please describe.**
We are investigating using a Lua filter as a replacement for modify/grep for logs filtering, however the current Lua implementation does not expose regular expression functionality which we need.

**Describe the solution you'd like**
A built-in callable function or operator in Lua that allows testing a string for a match against a regular expression. The specific syntax is not too important; essentially we want access to the same regex engine used by modify & grep, but in Lua scripts.

Example of a potential solution using a hypothetical built-in `regex_match` function:

Fluent Bit config:
```
[FILTER]
    Name  lua
    Match *
    Call  filter
```

Lua script:
```lua
function filter(tag, timestamp, record)
    if regex_match(record["field"], "^[xyz]$") then
        return -1, 0, 0
    end
    return 0, 0, 0
end
```

**Additional context**
We are investigating Lua as a more performant alternative to modify/grep for logs filtering. Example of how we currently implement logs filtering: https://github.com/GoogleCloudPlatform/ops-agent/blob/jefferbrecht-filter/confgenerator/testdata/valid/linux/logging-processor_exclude_logs/golden_fluent_bit_main.conf#L65:L92

[Lua patterns](http://lua-users.org/wiki/PatternsTutorial) are not sufficient for our use case; we require regular expressions.

**Comment by tarruda** [comment]
If you install a Lua package using [luarocks](https://luarocks.org/), it will be available from your filter with `require`. That means you can install a regular expression package such as [lrexlib-posix](https://luarocks.org/modules/rrt/lrexlib-posix) and it will provide both Perl and POSIX regular expressions.

An even better option is to use [LPeg](https://luarocks.org/modules/gvvaughan/lpeg), which allows you to define parsers for PEG grammars using Lua's builtin syntax.

Here's an example of a Lua filter that uses LPeg to do some simple csv parsing: https://github.com/calyptia/fluent-talks/blob/main/episodes/2022-02-25-fluentbit-lua/csv_lpeg.lua

Here is a Dockerfile that shows how you can install the required Lua packages into a docker image: https://github.com/calyptia/fluent-talks/blob/main/episodes/2022-02-25-fluentbit-lua/Dockerfile

**Comment by jefferbrecht** [comment]
Thanks! Is there a way to install lrexlib-posix without having a separate lua interpreter installed? It looks like luarocks requires an interpreter on $PATH.

**Comment by tarruda** [comment]
> Thanks! Is there a way to install lrexlib-posix without having a separate lua interpreter installed? It looks like luarocks requires an interpreter on $PATH.

Here's an example of using PCRE in a lua filter: https://github.com/calyptia/fluent-bit-lua-samples/tree/main/array-base64-pcre-example . You can run locally with docker, and the Dockerfile shows how to install the necessary packages.

**Comment by quentinmit** [comment]
Why was this marked as completed? This feature has never been added.
