### ISSUE TITLE
out_stackdriver: Use GOOGLE_APPLICATION_CREDENTIALS as env variable to specify service account credentials

### ISSUE THREAD

**Issue by ridwanmsharif** [fluent/fluent-bit#4617]
## Bug Report

**Describe the bug**
The stackdriver output plugin uses `GOOGLE_SERVICE_CREDENTIALS` to configure the credentials for google cloud but it is standard convention to use `GOOGLE_APPLICATION_CREDENTIALS` instead (see https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable)

**Comment by qingling128** [comment]
For backward compatibility, we might need to make it configurable while defaulting to the `GOOGLE_SERVICE_CREDENTIALS` one.

**Comment by qingling128** [comment]
Where the incorrect variable is used today: https://github.com/fluent/fluent-bit/blob/0ba2dc2196e4c2c19a6075f8154afe7be137119d/plugins/out_stackdriver/stackdriver_conf.c#L206

**Comment by qingling128** [comment]
Discussed offline with Eduardo and Anurag. The preferred solution is to add a fallback:

Check whether `GOOGLE_APPLICATION_CREDENTIALS` is set first. If so, use that. Otherwise try to use `GOOGLE_SERVICE_CREDENTIALS`.

**Comment by qingling128** [comment]
Related issue: https://github.com/fluent/fluent-bit/issues/4664
