### ISSUE TITLE
enhancement: ability to check consistency on the other side

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#462]
Do something like adding unique, incremental id to every record, so we may finally recognize the other side gaps in data received. 

Assuming these seq id's are added to the output and they are used on input in (in_forward) etc. Evaluated for consistency in ES etc.. 

If filters were applied on the record, then we obviously can't send such sequences, however, I quite believe there will be some kind of distributed pattern that we may implement to achieve this anyway. We don't have to count, but check for lost records (ie, cras, network, reject?)

**Comment by edsiper** [comment]
hi @epcim 

Next version of Fluent Bit v0.12.10 is coming with that feature through the following contribution:

https://github.com/fluent/fluent-bit/pull/447

FYI: For Next series of Fluent Bit (0.14) I am designing a new way so each record will always have a UUID for internal identification and optionally used for checking purposes.

**Comment by edsiper** [comment]
Fixed by https://github.com/fluent/fluent-bit/pull/447
