### ISSUE TITLE
Different naming of config files causes a "backend failed" error

### ISSUE THREAD

**Issue by herangstl** [fluent/fluent-bit#4629]
I have a very strange behavior with Fluent Bit. After installing it on a new machine I get this line:

`[error] [lib] backend failed`

- the _identical_ configuration (I use Ansible) is running on many machines without issues
- all machines run Ubuntu 20.04.3 LTS; the new machine that has the issues also runs 20.04.3, but because it’s a fresh install maybe _some OS components_ might be different from the older machines
- I have tried various versions of Fluent Bit, from v1.7.9 up to 1.8.11. With all of them I get this error
- my Fluent Bit setup has a central config file that uses `@INCLUDE specific/*.conf` to included various files that contain` [INPUT]` and `[FILTER`] definitions. There are no dependencies between those config files
- after lots of fiddling around I figured out that when I change the names of those *.conf files I don’t get this “backend failed” error any more -> I added prefixes like “00_” or  “01_”, possibly this changes the order in which the files are loaded/parsed

Questions: 
(1) Why does the order of the files that are included via @INCLUDE make a difference?
(2) How can I debug this “backend failed” error? The verbose output is pretty useless.

My suspicion is that there’s some really nasty stuff going on (e.g. memory leak) that intermittently causes Fluent Bit to fail. In the past I had cases where it core dumped without any obvious reason; after adding a space characters to the config files, or re-ordering some lines, it worked again. Really strange.

The issue is perfectly reproducible. I can provide a full installation for your developers if needed.

**Comment by nokute78** [comment]
> (2) How can I debug this “backend failed” error?

The workaround is to use valgrind.
https://github.com/fluent/fluent-bit/issues/3295#issuecomment-812280772

Could you check this?

**Comment by pwhelan** [comment]
can you create a simple reduced example to test this @herangstl?

**Comment by herangstl** [comment]
I don't think I can, because even changing the order in which config files are parsed has influence on the bug.

Can I send it to you directly  @pwhelan? I don't want to post it here publicly on the Internet.

**Comment by pwhelan** [comment]
> I don't think I can, because even changing the order in which config files are parsed has influence on the bug.
> 
> Can I send it to you directly @pwhelan? I don't want to post it here publicly on the Internet.

Sure, I can be messaged on the fluent-bit slack.

**Comment by lecaros** [comment]
Hi @herangstl,
Have you reached out to @pwhelan? Do you still see this issue? Do you have a repro for this that we can use? have you set log_level to debug?

**Comment by bodhi-one** [comment]
bump, @herangstl , can you respond?  I'm having similar issues like this with fluent-bit 1.8.13.  Using valgrind in my case did not provide extra debugging info.
