### ISSUE TITLE
windows 2019 fluent bit service start fail

### ISSUE THREAD

**Issue by chals-chu** [fluent/fluent-bit#4631]
## Bug Report

**Describe the bug**
[]
(https://docs.fluentbit.io/manual/installation/windows
I installed it as described in the installation guide, but the service is not running.)

**To Reproduce**
C:\Windows\system32>sc.exe create fluent-bit binpath= "\"C:\Program Files\fluent-bit\bin\fluent-bit.exe\" -c \"C:\Program Files\fluent-bit\conf\fluent-bit.conf\""
[SC] CreateService SUCCESS

C:\Windows\system32>sc.exe start fluent-bit

SERVICE_NAME: fluent-bit
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 5584
        FLAGS              :

C:\Windows\system32>sc.exe query fluent-bit

SERVICE_NAME: fluent-bit
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1067  (0x42b)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23470930/150087593-a1f06ddf-0f09-491a-be9f-4deabcc8cd7e.png)

**Your Environment**

* Version used: td-agent-bit-1.8.11-win64.exe
* Configuration: not change default config
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: aws ec2
* Operating System and version: windows 2019 data center
* Filters and plugins: no

**Additional context**

**Comment by walbers** [comment]
The default config is bad. I already created an issue for that bug. Change you config to this [one ](https://docs.fluentbit.io/manual/pipeline/inputs/windows-event-log)and it will work.

**Comment by chals-chu** [comment]
@walbers Thank you. I'll try setting it up again.

**Comment by lecaros** [comment]
Hi @chals-chu , did you solve this by using the example in https://github.com/fluent/fluent-bit-docs/pull/676 ?

**Comment by jansony1** [comment]
Still not work with with above conf.

My environments:
1. fluent-bit-1.9.4-win64.exe
2. Windows_Server-2019-English-Full-ContainersLatest-2022.05.2
