### ISSUE TITLE
"PutObject request failed" on all S3 uploads on 1.8.11 with windows server 2019

### ISSUE THREAD

**Issue by chals-chu** [fluent/fluent-bit#4632]
## Bug Report

**Describe the bug**
"PutObject request failed" on all S3 uploads on 1.8.11 with windows server 2019

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2022/01/19 10:37:17] [debug] [aws_credentials] Initialized EC2 Provider in standard chain
[2022/01/19 10:37:17] [debug] [aws_credentials] Sync called on the EC2 provider
[2022/01/19 10:37:17] [debug] [aws_credentials] Init called on the env provider
[2022/01/19 10:37:17] [debug] [aws_credentials] Init called on the EC2 IMDS provider
[2022/01/19 10:37:17] [debug] [aws_credentials] requesting credentials from EC2 IMDS
[2022/01/19 10:37:17] [debug] [http_client] not using http_proxy for header
[2022/01/19 10:37:17] [debug] [http_client] server 169.254.169.254:80 will close connection #1084
[2022/01/19 10:37:17] [debug] [aws_client] (null): http_do=0, HTTP Status: 401
[2022/01/19 10:37:17] [debug] [http_client] not using http_proxy for header
[2022/01/19 10:37:17] [debug] [http_client] server 169.254.169.254:80 will close connection #1084
[2022/01/19 10:37:17] [debug] [imds] using IMDSv2
[2022/01/19 10:37:17] [debug] [http_client] not using http_proxy for header
[2022/01/19 10:37:17] [debug] [http_client] server 169.254.169.254:80 will close connection #1104
[2022/01/19 10:37:17] [debug] [aws_credentials] Requesting credentials for instance role Server-Role
[2022/01/19 10:37:17] [debug] [imds] using IMDSv2
[2022/01/19 10:37:17] [debug] [http_client] not using http_proxy for header
[2022/01/19 10:37:17] [debug] [http_client] server 169.254.169.254:80 will close connection #1084
[2022/01/19 10:37:17] [ info] [output:s3:s3.0] Sending locally buffered data from previous executions to S3; buffer=/tmp/fluent-bit/s3/log-bucket
[2022/01/19 10:37:17] [debug] [upstream] connection #1100 failed to s3.ap-northeast-1.amazonaws.com:443
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.8.11
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: ec2 
* Operating System and version: windows 2019
* Filters and plugins:

**Additional context**

**Comment by agup006** [comment]
Adding @PettitWesley from AWS team

**Comment by PettitWesley** [comment]
@chals-chu Please provide your full configuration file. Also- I do not see any errors here, I see debug messages... the debug messages about connections failing are normal...

**Comment by chals-chu** [comment]
@PettitWesley 
The aws cli command is operating normally.


fluent-bit.conf
[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        5

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    debug

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    # storage.path /tmp/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    # storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    # storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    # storage.backlog.mem_limit 5M

[INPUT]
    name            winlog
    Channels        Application,Security,System,Setup,OpenSSH/Operational,Windows PowerShell,Remote Desktop Services
    interval_sec    1
    DB              winlog.sqlite

[OUTPUT]
    name  s3
    match *
    bucket log-bucket
    region ap-northeast-1
    compression gzip
    use_put_object On
    total_file_size 1M
    s3_key_format /winlog/Beta/year=%Y/month=%m/day=%d/%Y-%m-%d-$UUID.gz

**Comment by PettitWesley** [comment]
@chals-chu 

> The aws cli command is operating normally.

Cool- but which command?

And again- can you please provide the error log output for Fluent Bit. Full output is preferable- you can attach a log file into the issue.

**Comment by chals-chu** [comment]
@PettitWesley 

fluent-bit logs
[fluent-bit.log](https://github.com/fluent/fluent-bit/files/7912491/fluent-bit.log)


aws command

PS C:\tmp\fluent-bit\s3\twod-tk-log-bucket> pwd

Path
----
C:\tmp\fluent-bit\s3\twod-tk-log-bucket


PS C:\tmp\fluent-bit\s3\twod-tk-log-bucket>
PS C:\tmp\fluent-bit\s3\twod-tk-log-bucket>
PS C:\tmp\fluent-bit\s3\twod-tk-log-bucket> aws s3 cp --recursive .\2022-01-21T10-27-09\ s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/
upload: 2022-01-21T10-27-09\3915943859-2876633184 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-2876633184
upload: 2022-01-21T10-27-09\3915943859-1931443668 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-1931443668
upload: 2022-01-21T10-27-09\3915943859-1662186944 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-1662186944
upload: 2022-01-21T10-27-09\3915943859-3937969100 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-3937969100
upload: 2022-01-21T10-27-09\3915943859-2540477968 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-2540477968
upload: 2022-01-21T10-27-09\3915943859-500945092 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-500945092
upload: 2022-01-21T10-27-09\3915943859-1340068612 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-1340068612
upload: 2022-01-21T10-27-09\3915943859-3996062672 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-3996062672
upload: 2022-01-21T10-27-09\3915943859-731783820 to s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/3915943859-731783820
PS C:\tmp\fluent-bit\s3\twod-tk-log-bucket> aws s3 ls s3://twod-tk-log-bucket/winlog/Beta/year=2022/month=01/day=21/
2022-01-21 10:32:12    2526907 3915943859-1340068612
2022-01-21 10:32:12    3398251 3915943859-1662186944
2022-01-21 10:32:12     548304 3915943859-1931443668
2022-01-21 10:32:12    2843882 3915943859-2540477968
2022-01-21 10:32:12     546063 3915943859-2876633184
2022-01-21 10:32:12    2603314 3915943859-3937969100
2022-01-21 10:32:12    3412562 3915943859-3996062672
2022-01-21 10:32:12    2935915 3915943859-500945092
2022-01-21 10:32:12    2387345 3915943859-731783820

**Comment by chals-chu** [comment]
@PettitWesley 
ec2 is on private subnet.
s3 communicates with the vpc private endpoint.

**Comment by PettitWesley** [comment]
> [2022/01/21 10:27:20] [debug] [upstream] connection #976 failed to s3.ap-northeast-1.amazonaws.com:443
> s3 communicates with the vpc private endpoint.

I think this is the source of the problem somehow... these two must be connected.

I think you need to set the `endpoint` option on the S3 output to be your VPC endpoint DNS.

https://docs.fluentbit.io/manual/pipeline/outputs/s3

**Comment by chals-chu** [comment]
@PettitWesley 
The s3 vpc endpoint type is gateway .

Here is an example of how we set it up.
https://tomgregory.com/when-to-use-an-aws-s3-vpc-endpoint/

The gateway type vpc endpoint cannot use the fluent-bit endpoint option.

python boto3, awsclie, go aws sdkv2 s3 upload all work fine.


ec2 server is in private subnet but nat gateway
With curl, test-netconnection in powershell, the url "s3.ap-northeast-1.amazonaws.com:443" is normally accessed.

PS C:\Windows\system32> Test-NetConnection -ComputerName s3.ap-northeast-1.amazonaws.com -Port 443
ComputerName     : s3.ap-northeast-1.amazonaws.com
RemoteAddress    : 52.219.137.8
RemotePort       : 443
InterfaceAlias   : Ethernet 2
SourceAddress    : 10.200.40.148
TcpTestSucceeded : True

**Comment by PettitWesley** [comment]
@chals-chu Sorry I forgot about this issue. I think you need to use the endpoint option in s3 like this:

```
[OUTPUT]
    name  s3
    match *
    bucket twod-tk-log-bucket
    region ap-northeast-1
    compression gzip
    use_put_object On
    total_file_size 1M
    s3_key_format /winlog/Beta/year=%Y/month=%m/day=%d/%Y-%m-%d-$UUID.gz
    # Add
    endpoint {Add your VPC endpoint for S3 here}
```

https://docs.fluentbit.io/manual/pipeline/outputs/s3

**Comment by chals-chu** [comment]
@PettitWesley It doesn't work even if you specify the vpc endpoint.
Even if you set ec2 elasticip, the upload to s3 fails.
Linux(amazon linux, centos, ubunt) works perfectly on the same vpc.

**Comment by agup006** [comment]
Hey folks, are we able to try with the latest 1.9.x? Adding @leonardo-albertovich in case there are any new Windows features that might alleviate this
