### ISSUE TITLE
hotreload in k8s enviroment and support tenant concept route

### ISSUE THREAD

**Issue by zhanghe9702** [fluent/fluent-bit#4648]
**Is your feature request related to a problem? Please describe.**

when process huge log traffic, fluent-bit+fluentd will encounter GC problem, that is the collected log will delay hours to DB(fluentd 100% cpu load),
**Describe the solution you'd like**

consider fluent-bit high performance, it should be perfect solution by add these function.  
**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Can you clarify the request here? It sounds like a fluentd issue. 
By GC do you mean garbage collection, Fluent Bit is written in C so not sure what you are referencing here?

What use case are you trying to solve and what problem are you seeing? 
How should we test and verify the feature?

Note that for K8S there is also the Fluent Operator which handles config reload as well: https://github.com/fluent/fluent-bit/issues/365
https://github.com/fluent/fluentbit-operator

**Comment by zhanghe9702** [comment]
![image](https://user-images.githubusercontent.com/16931323/150522136-14047397-d5a8-4f4f-9fff-db55241e0d5a.png)

**Comment by zhanghe9702** [comment]
sry.,i will clarify it later

**Comment by patrick-stephens** [comment]
OK, it might be a better fit for the existing open-source fluent bit operator as well: https://github.com/fluent/fluentbit-operator

**Comment by zhanghe9702** [comment]
> OK, it might be a better fit for the existing open-source fluent bit operator as well: https://github.com/fluent/fluentbit-operator

if fluentbit-operator could route different namespace logs to configurable output, it is a better fit, but it can't

**Comment by patrick-stephens** [comment]
Yeah but it might be an issue for the operator then rather than here.

**Comment by zhanghe9702** [comment]
maybe,but if we connect input instance with output instance not only by tag match ,and also accept an map<string,string>，this should be enough

**Comment by patrick-stephens** [comment]
Is that what you want then? Can you update the original request?
I think it'll need some good examples as I still not entirely certain. 
How does it differ from wildcard matching or just splitting the stream before matching? I think those examples will help flesh it out quite a bit to explain it in detail and why the current solutions are not enough.

**Comment by zhanghe9702** [comment]
> Is that what you want then? Can you update the original request? I think it'll need some good examples as I still not entirely certain. How does it differ from wildcard matching or just splitting the stream before matching? I think those examples will help flesh it out quite a bit to explain it in detail and why the current solutions are not enough.

sry,i made a mistake, and thanks ,i close it
