### ISSUE TITLE
Add logo to list of companies using fluent-bit

### ISSUE THREAD

**Issue by rparth** [fluent/fluent-bit#4653]
We use fluent-bit in our company to enable data collection for a variety of platforms. We would like our company logo listed. As suggested in the README, we are raising a request for the same. Thanks in advance and kudos on such a useful tool that should be in every enterprise arsenal!
![Group 33](https://user-images.githubusercontent.com/28794607/150585086-6dc19f8e-6407-4675-8245-243672d4264a.png)

**Comment by agup006** [comment]
@rparth awesome! Yes let's add the logo we are targeting a new version of the site shortly, let's see if we can get this as part of the new assets

**Comment by rparth** [comment]
Thanks @agup006 look forward to the new site.

**Comment by agup006** [comment]
target is this Friday

**Comment by agup006** [comment]
This has been launched as of last week and is live on the new fluentbit.io, thanks folks!

**Comment by rparth** [comment]
Awesome thank you
