### ISSUE TITLE
out_stackdriver: plugin seg faults when using creds file passing in using env variable or the config option

### ISSUE THREAD

**Issue by ridwanmsharif** [fluent/fluent-bit#4664]
## Bug Report

**Describe the bug**
When using the google_service_credentials field in https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver or the $GOOGLE_SERVICE_CREDENTIALS environment failure, fluent bit fails with a seg fault when a message is matched with the plugin, causing it to crash. Here is the stacktrace of the seg fault:

```
[2022/01/22 05:00:44] [debug] [output:stackdriver:stackdriver.1] task_id=0 assigned to thread #0 
[2022/01/22 05:00:44] [debug] [out flush] cb_destroy coro_id=0
[2022/01/22 05:00:44] [debug] [output:stackdriver:stackdriver.1] [logging.googleapis.com/monitored_resource] not found in the payload
[2022/01/22 05:00:44] [engine] caught signal (SIGSEGV)                                                                                                                                          
#0  0x5590e37d1331      in  flb_sds_len() at lib/monkey/include/monkey/mk_core/mk_list.h:51                                                                                                     
#1  0x5590e37d6044      in  stackdriver_format() at include/fluent-bit/flb_time_utils.h:1638                                                                                                    
#2  0x5590e37d7a64      in  cb_stackdriver_flush() at include/fluent-bit/flb_time_utils.h:2131                                                                                                  
#3  0x5590e371a1f0      in  output_pre_cb_flush() at include/fluent-bit/flb_mem.h:511                                                                                                           
#4  0x5590e3a589a6      in  co_init() at build/lib/monkey/deps/flb_libco//usr/local/google/home/ridwanmsharif/Software/src/github.com/google/fluent-bit/lib/monkey/deps/flb_libco/libco.c:117   
#5  0xffffffffffffffff  in  ???() at ???:0                                                                                                                                                      
[1]    2607035 IOT instruction  bin/fluent-bit -c config.conf -v  

```

**To Reproduce**
- Create a service account and download credentials: https://cloud.google.com/logging/docs/agent/logging/authorization#create-service-account
- Use the environment variable $GOOGLE_SERVICE_CREDENTIALS or use the `google_service_credentials` option in the plugin and provide the absolute path to the JSON cred file
- Start the agent and log something to cloud monitoring
-Error appears

**Expected behavior**
It should not error out and work as it does in the default case (where it looks up from the metadata server)

**Notes/Investigation**
So when the credentials are set, the private key is picked up from the cred file and so `ctx->metadata_server_auth` is set to `False` by default.

https://github.com/fluent/fluent-bit/blob/83300142acdda4c79a5ac358047a7ef1b374602e/plugins/out_stackdriver/stackdriver_conf.c#L273-L277

As such, `gce_metadata_read_zone` is never called (https://github.com/fluent/fluent-bit/blob/83300142acdda4c79a5ac358047a7ef1b374602e/plugins/out_stackdriver/stackdriver.c#L1071-L1081) and so `ctx->zone` is never set (https://github.com/fluent/fluent-bit/blob/83300142acdda4c79a5ac358047a7ef1b374602e/plugins/out_stackdriver/gce_metadata.c#L183).

Because of this, https://github.com/fluent/fluent-bit/blob/83300142acdda4c79a5ac358047a7ef1b374602e/plugins/out_stackdriver/stackdriver.c#L1638 here we fail because we expect `ctx->zone` but it isn't there.

**Comment by edsiper** [comment]
@ridwanmsharif thanks for reporting the issue, the following PRs will ship the fix:

- master: https://github.com/fluent/fluent-bit/pull/4677
- 1.8: https://github.com/fluent/fluent-bit/pull/4678
