### ISSUE TITLE
tail with multiline does not behave as expected

### ISSUE THREAD

**Issue by hackeracc** [fluent/fluent-bit#467]
Hi,
I am using the multiline feature in tail input plugin in fluent bit. I am running on Centos 7.
My relevant config snippets are as follows:

[INPUT]
    Name tail
    Tag custom
    Path /var/log/custom.log.*
    Exclude_Path *.gz
    Multiline On
    Parser_Firstline custom_start
    Parser_1 custom1

in parsers.conf, I have added the definitions for custom_start and custom1

[PARSER]
    Name custom_start
    Format regex
    Regex \d{4}-\d{1,2}-\d{1,2}

[PARSER]
    Name custom1
    Format regex
    Regex (?<time>[^INFO|DEBUG|ERROR|WARN]*)(?<type>[^ ]*) (?<message>.*)

My sample log line is: 
2017-12-10 15:52:17 INFO test_log message multiline

I am not getting any log lines as output. Any pointers on what I am missing ?

**Comment by edsiper** [comment]
what about this regex rule:

(?<time>\d{4}-\d{1,2}-\d{1,2} \d{2}:\d{2}:\d{2})(?<message>.*)$

you can test it on rubular.com

**Comment by monotek** [comment]
You could also try to use the detect-exceptions plugin mentioned in https://github.com/fluent/fluent-bit/issues/476

https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions

**Comment by edsiper** [comment]
@hackeracc any luck with the regex provided above ?

**Comment by edsiper** [comment]
Question answered, closing this issue. If you have more questions please open a new ticket.
