### ISSUE TITLE
Push own metrics to fluentbit daemon for prometheus upload

### ISSUE THREAD

**Issue by flrkli** [fluent/fluent-bit#4674]
Hello, first of all I have to say that you have created a wonderful tool. We love to use fluentbit. 
Though for one use case we are a bit puzzled currently: we want to push our own application metrics via fluentbit to a prometheus. 
What is the best way to push metrics (not logs) from our application to the fluentbit daemon? 
We tried the C API (https://docs.fluentbit.io/manual/development/ingest-records-manually) but we’re not able to include it in our app (I think it is not an API to talk to the daemon) and we tried the HTTP input plugin but it does not use metrics. 

Thanks in advance

**Comment by jasonhadi** [comment]
@edsiper I've see you've done some work with a [prometheus_scrape](https://github.com/fluent/fluent-bit/tree/master/plugins/in_prometheus_scrape) plugin for 1.9. Do you know if that plugin satisfies this use case? We want to do something similar; send custom metrics up to a prometheus remote_write output.
