### ISSUE TITLE
FluentBit windows agent stops sending log records to Loki server

### ISSUE THREAD

**Issue by matt985** [fluent/fluent-bit#4684]
## Bug Report

**Describe the bug**

FluentBit agent td-agent-bit-1.8.11-win64 installed on Windows Server 2019 as a service starts up correctly and sends logs to a Loki server but, after a while (usually a few minutes), it stops dispatching logs for no clear reason. 
Loki interface only shows the log records that were dispatched at the startup of the fluentbit agent service.

**To Reproduce**

This is the configuration file I used to setup the agent:

```
[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on

[INPUT]
    Name         winlog
    Channels     Setup,System,Security,Application
    Interval_Sec 1

[OUTPUT]
    name  	           loki
    match		   *
    host                   loki-server.com
    port                   443
    tls                    On
    tls.verify             Off
    tls.debug              0
    labels                 job=winlog
```

The FluentBit agent is "td-agent-bit-1.8.11-win64" which is installed as a windows service:

```
New-Service fluent-bit -BinaryPathName '"C:\Program Files\FluentBit\bin\fluent-bit.exe" -c "C:\Program Files\FluentBit\conf\win-to-loki.conf"' -StartupType Automatic
Start-Service fluent-bit
```

**Expected behavior**

The agent starts up, collects logs from windows log channels and seamlessly sends them to Loki.

**Your Environment**
Loki server is installed on top of Kubernetes
No errors in nginx ingress controller logs

Is there something I am doing wrong? Can you give me a hint on the best way to troubleshoot this issue?
Thank you very much

**Comment by lecaros** [comment]
Hi @matt985,
what do you see in the fluent-bit log with debug level enabled?
If you set output stdout, does it continue processing and sending to that output?
Is this reproducible in the latest version? (either 1.8.15 or 1.9.2)
