### ISSUE TITLE
New packages and container images must link to libyaml

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#4690]
Since v1.9 will support additional YAML format config,  once #4621 get merged, we need all packaging systems to install libyaml (devel headers and runtime lib) so the Fluent Bit binary can take advantage of this feature.

**Comment by patrick-stephens** [comment]
Why do we need the devel headers in production?

**Comment by edsiper** [comment]
sorry, I meant devel headers at configure level so Fluent Bit is aware about YAML support in that target platform

**Comment by patrick-stephens** [comment]
Ah I see, so in the build and then just the runtime libraries for the actual deliverable.

**Comment by edsiper** [comment]
yup. YAML support was just merged in GIT master

**Comment by edsiper** [comment]
Fixed in #4814
