### ISSUE TITLE
Dynamic filter names for prometheus metrics

### ISSUE THREAD

**Issue by LeonD9** [fluent/fluent-bit#4694]
**Is your feature request related to a problem? Please describe.**

I want to use prometheus metrics to create alarms per filter, but the metrics names are too vague and i can't specify on which filter the issue is, for example:

```fluentbit_filter_drop_records_total{kubernetes_pod_name="fluent-bit-gaosj5", name="throttle.4", release="fluent-bit"}```

<br class="Apple-interchange-newline">

**Describe the solution you'd like**

I would like to use specific names i choose instead of `throttle.4` for filters

**Additional context**

I am trying to add throttling per namespace, which works but i want to get alarms when specific throttle is triggered and it's hard to know by the name of the filter to which namespace its attached.

Would be great to be able to add dynamic names to filters when multiple filters are used to be able to know to which filter the metric is related in prometheus.

Thanks!

**Comment by novegit** [comment]
try 'alias' option - https://docs.fluentbit.io/manual/administration/monitoring#configuring-aliases

**Comment by LeonD9** [comment]
Thanks it worked!
@novegit Another question:
is it possible to add additional label in the metric called namespace from where the log came from (and not the namespace of the fluentbit)?

**Comment by novegit** [comment]
thats not possible. I added a streams output about processed "logmessages per namespace", so i have this information in the logoutput
