### ISSUE TITLE
Crash lib mode if use more than 1 context

### ISSUE THREAD

**Issue by satharasidinesh** [fluent/fluent-bit#470]
In library mode fluent bit crashing if we send more than 3 time same request 

below code will reproduce issue 

```
#include <stdio.h>
#include <fluent-bit.h>
int main() {
int i = 0;
for (i = 0;i<3;i++){
flb_ctx_t *ctx;
ctx = flb_create();
if (!ctx) {
 return -1;
}
int in_ffd;
in_ffd = flb_input(ctx, "cpu", NULL);
int out_ffd;
out_ffd = flb_output(ctx, "stdout", NULL);
int ret;
ret = flb_start(ctx);
}
while(1){
}
return 0;
}
```

regards ,
Dinesh S.

**Comment by edsiper** [comment]
the code you have provided is wrong. In the loop you are overriding the main context which will lead to a segmentation fault. Please refer to the following test case as a functional example:

https://github.com/fluent/fluent-bit/blob/master/examples/hello_world/hello_world.c

**Comment by satharasidineah** [comment]
HI ,

In my logic i am creating 3 diffrent context for 3 different data collection with same input and output plugins  , all the 3 context are local to for loops i.e am not overriding any context.

if something wrong in my understanding let me know.

**Comment by edsiper** [comment]
Trying to isolate the problem I've found that is not possible to use more than one main context, test case here:

```C
int main()
{
    flb_ctx_t *ctx1;
    flb_ctx_t *ctx2;

    ctx1 = flb_create();
    ctx2 = flb_create();

    flb_service_set(ctx1, "Flush", "1", NULL);

    flb_input(ctx1, "cpu", NULL);
    flb_output(ctx1, "stdout", NULL);
    flb_start(ctx1);

    while (1) {
        sleep(1);
    }
l.
    return 0;

}
```

If ctx2 is allocated we get a segmentation fault.

Marking this behavior as a bug, as a workaround do not use more than one context.

**Comment by edsiper** [comment]
This is already fixed in git master.
