### ISSUE TITLE
is it possible to emitting multiple records with different tags using rewrite_tag filter plugin if the record match multiple rules 

### ISSUE THREAD

**Issue by wangyuan0916** [fluent/fluent-bit#4708]
I'm using rewrite_tag filter plugin with multiple rules and want to retag one record to multiple records if it matches several rules defined in rewrite_tag, then forwarding the same log content to different destinations. I noticed that there's a field we can configure to let fluent-bit to keep the origin record, but no matter what value I set, it seems if the record matches one rule, it will not going to check other rules below. 
My request is to let on record match different rules and rewrite its tag and generate multiple records with different tags. It will be appreciate to implement this. Thanks a lot!

**Comment by timcosta** [comment]
the closest i've found is to do something like this:

```
    # takes all messages from kube.* and rewrites them to secondary.*, but keeps them in kube.*
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule            $log .* secondary.$TAG true

    # duplicates all messages from kube.* a second time and puts them into tertiary.*
    # Sets KEEP to false which doesnt keep the message in kube.*, so now we have every 
    # message in secondary.* and tertiary.*, but kube.* is terminated
    [FILTER]
        Name          rewrite_tag
        Match         kube.*
        Rule            $log .* tertiary.$TAG false
```

it's kinda messy, but it works.

**Comment by wangyuan0916** [comment]
@timcosta  Thanks a lot, I've tried this workaround before and met record missing [issue](https://github.com/fluent/fluent-bit/issues/4518)
the second problem is that multiple rewrite_tag will create multiple internal input emitters, which will cost a lot of memory if there's too much rewrite_tags. It seems better to check all rules and maintain just one rewrite_tag in this scenario. Thanks anyway
