### ISSUE TITLE
Fluent Bit simplified install script

### ISSUE THREAD

**Issue by agup006** [fluent/fluent-bit#4733]
**Is your feature request related to a problem? Please describe.**
When installing Fluent Bit with package builds there are a few steps that would be great if they could be simplified into a single script similar to Fluentd

**Describe the solution you'd like**
Fluentd has a simplified install script that would be useful to mimic, we would also need to update documentation to point to this new install script.

**Comment by patrick-stephens** [comment]
We can do it via a single package install, i.e. download the RPM/DEB for a specific release and install that. However I think it will be better to set up a repository to do the install so we can also do simple updates easily too when new versions come out. The new S3 release bucket actually includes the repo config to simplify all this during testing.
