### ISSUE TITLE
How to use OpenSearch ISM with fluent-bit?

### ISSUE THREAD

**Issue by malcolm061990** [fluent/fluent-bit#4743]
## Bug Report

**Describe the bug**
How can we create [ISM](https://opensearch.org/docs/latest/im-plugin/ism/policies/#example-policy) using fluent-bit?

**To Reproduce**
We use self-managed OpenSearch 1.2.4 in k8s.
Previously we used Elastic beats with Elasticsearch and In Elastic filebeat it can be created via config file mounted to k8s pod:
```json
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_size": "5GB",
                "max_age": "1d"
              }
            }
          },
          "delete": {
            "min_age": "7",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }

```
**Expected behavior**
Ability to create ISM via fluent-bit configuration "as a code" without any manual actions using OpenSearch API.

**Your Environment**

* Version used: Fluent Bit v1.8.12
* Configuration: helm default
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: kubernetes, v1.20.11-eks-f17b81

**Additional context**

For some reason almost same issue was closed without answer - #4229

**Comment by agup006** [comment]
I'm not sure if this would be something that lands in the 1st opensearch connector we are building, probably worth investigating and figuring out where it can land on the roadmap

Adding @cosmo0920 to see if this is something supported in Fluentd opensearch plugin too

**Comment by cosmo0920** [comment]
The official documentation of OpenSearch says that this ISM feature couldn't be created with logging agent event if LogStash OpenSearch output. Theoretically, we cannot use it from logging agents.
Instead, OpenSearch users must build it with OpenSearch Dashboards:
https://opensearch.org/docs/latest/im-plugin/ism/index/

**Comment by malcolm061990** [comment]
> The official documentation of OpenSearch says that this ISM feature couldn't be created with logging agents even if LogStash OpenSearch output. Theoretically, we cannot use it from logging agents for now.
> 
> Instead, OpenSearch users must build it with OpenSearch Dashboards: https://opensearch.org/docs/latest/im-plugin/ism/index/
> 
> I'm not sure why OpenSearch community decides that it is only for OpenSearch Dashboards feature.

Thanks for your support. I think we can close this issue.
