### ISSUE TITLE
[ warn] [input:http:http.1] invalid JSON message, skipping

### ISSUE THREAD

**Issue by rahil-r** [fluent/fluent-bit#4744]
When trying to send 5 logs only 2 are written to target and rest are getting skipped with the above warning. Is there a fix? And the 6th log is giving 504 timeout.

Input is of "http" type
And output is for a "file"

below is the configuration

[INPUT]
    Name     syslog
    Parser   syslog-rfc5424
    Listen   0.0.0.0
    Port     5170
    Mode     tcp
    Tag      syslog

[INPUT]
    Name                http
    Host                0.0.0.0
    Port                5172
    Buffer_Chunk_Size   32000
    Buffer_Max_Size     64000
    Tag                 httpweb
    

[OUTPUT]
    Name     file
    Match    syslog
    Path     /fluent-bit/path
    File     Logs.log

[OUTPUT]
    Name     file
    Path	 /fluent-bit/path
    File	 http_logs.log
    Match	 httpweb

**Comment by patrick-stephens** [comment]
What's the input? That's probably the key thing, have you got a simple reproducer? 

Is it valid JSON? What are the messages triggering the problem?

**Comment by rahil-r** [comment]
Thank you @patrick-stephens for responding.
The payload is a simple json without any special characters. Below is the input
`{"Troubleshooting_Logs":"Hello world"}`
However the issue seems to be solved. I was on the fluent-bit v1.7.1. upgrading to v1.8.12 solved the issue.
