### ISSUE TITLE
Slow performance when output to Loki

### ISSUE THREAD

**Issue by DesmondH0** [fluent/fluent-bit#4754]
## Bug Report

**Describe the bug**
Loki output not catching up the logs from tail input even in low traffic environment, also stacking up memory in time.

**Environment**
- `EKS v1.20.11`
- `fluent-bit v1.8.12`
- `loki v2.4.1`

fluent-bit config:
```
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        DB /var/log/flb_kube.db
        multiline.parser docker
        Tag kube.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On
        Skip_Empty_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        name                 loki
        host                   ${loki_host}
        match                kube.*
        labels                 source=fluent-bit, namespace=$kubernetes['namespace_name'], node_name=$kubernetes['host'], pod=$kubernetes['pod_name']
```

**Steps to reproduce the problem**
- Deployed fluent bit into EKS cluster
- My node throughput is quite low, for example:
![image](https://user-images.githubusercontent.com/39398132/152615853-73ea5f74-4f8b-4c9e-be82-b2dd189cb8a5.png)
- Memory is stacking up as well:
![image](https://user-images.githubusercontent.com/39398132/152615908-c23f4c06-7535-4604-a25b-2215bdb821f9.png)
- The processed log entries also having delay and never catch up:
```
{
  "input": {
    "tail.0": {
      "records": 5421,
      "bytes": 1886254,
      "files_opened": 24,
      "files_closed": 0,
      "files_rotated": 0
    }
  },
  "filter": {
    "kubernetes.0": {
      "drop_records": 31,
      "add_records": 0
    }
  },
  "output": {
    "loki.0": {
      "proc_records": 3180,
      "proc_bytes": 3582855,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0,
      "dropped_records": 0,
      "retried_records": 0
    }
  }
}
```

**Expected behavior**
Fluent-bit should able to process such low traffic without any issue

**Additional context**
- I tried to use file-system as storage, but getting `SIGSEGV` error after running a while:
```
[2022/02/04 22:39:41] [engine] caught signal (SIGSEGV)
#0  0x55a90ce9b2ee      in  pack_labels() at plugins/out_loki/loki.c:358
#1  0x55a90ce9d600      in  loki_compose_payload() at plugins/out_loki/loki.c:1139
#2  0x55a90ce9d73b      in  cb_loki_flush() at plugins/out_loki/loki.c:1177
#3  0x55a90cdf9aa7      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:514
#4  0x55a90d2fed66      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#5  0xffffffffffffffff  in  ???() at ???:0
```

**Comment by JeffLuoo** [comment]
Does this help by adding worker:
```
 [OUTPUT]
        name                 loki
        host                   ${loki_host}
        match                kube.*
        labels                 source=fluent-bit, namespace=$kubernetes['namespace_name'], node_name=$kubernetes['host'], pod=$kubernetes['pod_name']
        workers              8
```

**Comment by sujairamprasathc** [comment]
Setting workers improves the performance

**Comment by lecaros** [comment]
Hi @DesmondH0,
Do you still see this behavior?
How many files are in there? We solved an issue that didn't handle a large number of files well.
If you still see this, can you provide repro steps?
Thanks!

**Comment by DesmondH0** [comment]
Hi all,

Thanks for the comments and sorry for late reply.
I had done 2 update to my config:
- update fluent-bit to v1.8.15
- added `workers  8`
(Loki is accepting out-of-orders already)

Long story short, I still see the same behaviour as before
for e.g.: here is one of my fluent-bit stats after running around 30mins:
```
{
  "input": {
    "tail.0": {
      "records": 355126,
      "bytes": 87914331,
      "files_opened": 22,
      "files_closed": 18,
      "files_rotated": 4
    }
  },
  "filter": {
    "kubernetes.0": {
      "drop_records": 54,
      "add_records": 0
    }
  },
  "output": {
    "es.0": {
      "proc_records": 355070,
      "proc_bytes": 385488246,
      "errors": 0,
      "retries": 1,
      "retries_failed": 0,
      "dropped_records": 0,
      "retried_records": 1
    },
    "loki.1": {
      "proc_records": 76419,
      "proc_bytes": 82686707,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0,
      "dropped_records": 0,
      "retried_records": 0
    }
  }
}
```

There are not much files to tail on this node, only around 10 files there

**Comment by YvesZelros** [comment]
I am face to same performance issue on the loki output plugin.
Cpu is low but the throughput is really low and after a time fluent-bit buffer are full and writer is paused then we loose some logs ....

Setting "workers 8" help but have a side effect, the value of tenant_id_key is sometime null where was never the case without the configuration workers.

Look that loki output isn't thread safe ....

I have switch to the _grafana-loki_ output => https://grafana.com/docs/loki/latest/clients/fluentbit/
That fix the performance issue ! 
But this plugin don't support the configuration "tenant_id_key" that I need :-(
