### ISSUE TITLE
Output entries are sent out-of-order in fluent-bit when associated output target gets restarted.

### ISSUE THREAD

**Issue by sathya1meda** [fluent/fluent-bit#4757]
### Problem
When an output target is down temporarily (say for a few seconds) and is back online, the entries at the target can be out-of-order.
The failed entries get on a retry queue and they do not get handled as soon as the target is detected to be online by fluent-bit.

### Setup
Both fluent-bit (v1.8.12) and nc (OpenBSD netcat) are running on the same node (Ubuntu 20.04.3 LTS)
Fluent-bit input plugin is of type dummy - generates a dummy entry every minute with a timestamp
Fluent-bit output plugin is of type TCP - sends the input entries every minute in json format to the target (netcat listening on port 9876)

### Procedure
Run Fluent-bit and netcat
Ensure entries are appearing in sequence (fifo order) at netcat
Stop the netcat, wait 2 seconds, and start it back
Entries that were not sent due to netcat being down appear several seconds after the newer entries, causing out-of-order sequence

### Session Log at Fluent-bit
![image](https://user-images.githubusercontent.com/5119088/152734799-935c08ba-eeeb-4eb9-9d6f-a748ce725f5f.png)

### Session Log at the Output Target
![image](https://user-images.githubusercontent.com/5119088/152735006-c4f87bb8-ca0a-4ad0-a3e1-095163e5bd85.png)

**Comment by lecaros** [comment]
Hi @sathya1meda,
This is working as expected; however, we'd like to know what impact this may have on your end. Thanks

**Comment by sathya1meda** [comment]
Thanks for looking into this. Our expectation is that older entries will get pushed out first, as soon as connection is re-established, esp since connection is on TCP (or fluent-forward). The impact of leaving current scenario as is, is that we have to include a timestamp within the payload and our client will have to to use that timestamp for reordering in their analytics.

**Comment by lecaros** [comment]
Hi @sathya1meda,
there's already a timestamp in the payload. The basic composition of an event is timestamp+message. What kind of backend do you have on the output side? (the TCP you mention).
Please refer to https://docs.fluentbit.io/manual/concepts/key-concepts#event-or-record and let us know if you need further assistance on this.

**Comment by sathya1meda** [comment]
We actually use FORWARD (which uses TCP) - the issue is seen in both FORWARD and TCP outputs. As I understand, you are NOT considering this as a bug. Out-of-order entries on TCP/FORWARD seems odd. The impact for us remains the same (though explicit timestamp can be avoided).

**Comment by sathya1meda** [comment]
Backend would be fluentd

**Comment by lecaros** [comment]
Hi @sathya1meda 
This is working as expected.  Every record has a timestamp, you don't need to include an additional one.
If you have a use case you can create a feature request for evaluation.
