### ISSUE TITLE
Fluent bit doesnt forward logs and memory consumption of fluent-bit keeps steadily growing in a loaded k8s cluster

### ISSUE THREAD

**Issue by brucelee138** [fluent/fluent-bit#4760]
## Bug Report

**Describe the bug**

We have deployed fluent-bit as daemonset in a large k8s cluster with workload. We have noticed that some of the fluent-bit pods stop forwarding logs and their memory consumption steadily increasing over time (crosses 5Gi and still increases over time) 
There are no specific error logs from the pod logs and have attached the pod logs.
From fluent-bit metrics (:2020/api/v1/metrics), we could see that though the input bytes counter keeps increasing, the output bytes counter remains unchanged and even packet capture confirmed that logs were not getting forwarded.
[METRICS.txt](https://github.com/fluent/fluent-bit/files/8015569/METRICS.txt)

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

Steady rise of mem usage of the pod (mem consumption in Mb)
![fluent-bit-86hvm](https://user-images.githubusercontent.com/19279243/152792654-28e65275-13fb-42d7-8782-05a433fd05d3.PNG)

**Your Environment**

* Version used: Fluent Bit v1.8.10
* Configuration:
[SERVICE]
    Daemon Off
    Flush 1
    Log_Level info
    Parsers_File parsers.conf
    Parsers_File custom_parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Health_Check Off

[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Parser docker
    Tag kube.*
    Mem_Buf_Limit 200MB
    Skip_Long_Lines On
[INPUT]
    Name tail
    Path /var/log/messages
    Parser docker
    Tag messages.*
    Mem_Buf_Limit 200MB
    Skip_Long_Lines On
[INPUT]
    Name tail
    Path /var/log/audit/audit.log
    Parser docker
    Tag node-audit.*
    DB /var/log/flb_audit.db
    Mem_Buf_Limit 10MB
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size 1MB
    Skip_Long_Lines On
[INPUT]
    Name tail
    Path /var/log/kube-apiserver/kube-apiserver-audit.log
    Parser docker
    Tag kube-audit.*
    DB /var/log/audit.db
    Mem_Buf_Limit 35MB
    Buffer_Chunk_Size 2MB
    Buffer_Max_Size 10MB
    Skip_Long_Lines On

[FILTER]
    Name kubernetes
    Match kube.*
    Kube_Tag_Prefix kube.var.log.containers.
    Kube_URL https://kubernetes.default.svc.cluster.local:443
    Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log On
    Keep_Log Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude On

[OUTPUT]
    Name forward
    Match *
    Host fluentd
    Port 24224
    tls On
    tls.verify On
    tls.ca_file /fluentbit-tls/ssl/ca.crt.pem
    tls.crt_file /fluentbit-tls/ssl/client.crt.pem
    tls.key_file /fluentbit-tls/ssl/client.key.pem

* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.23.3
* Server type and version:
* Operating System and version:
* Filters and plugins: 

**Additional context**

Some fluent-bit stops forwarding logs and also later get OOMKilled due to continue increase in memory usage.

**Comment by lecaros** [comment]
Hi @brucelee138,
do you see any connection issues messages when enabling debug log level?
If you enable output stdout, do you see records being sent?
If you see those, it's highly likely you were affected by something we've already fixed (see https://github.com/fluent/fluent-bit/issues/4505).
Please test this in the latest version (1.8.15 or 1.9.2) and let us know if this is still an issue.
