### ISSUE TITLE
Built-in multiline.parser flush lines in nondeterministic way

### ISSUE THREAD

**Issue by przeszlo** [fluent/fluent-bit#4769]
## Bug Report

**Describe the bug**
We are using the built-in multline **crio** parser. Usually it concatenates logs in crio format correctly (crio split long line into 8KB chunks). Our applications logs in JSON format and from time to time, especially when long stacktraces are logged, there are situations where the logs are not concatenated. This of course leads to serious problems when reading logs from Loki (json parsing).

I did a brief code analysis. The first thing I noticed is that there is default value: FLB_ML_FLUSH_TIMEOUT (include/fluent-bit/multiline/flb_ml.h) which probably can't be overwritten by configuration? I have an impression that this timeout is for a mechanism that causes flush regardless of parser state, so it may write lines that have not yet been properly concatenated. (logs of type 'P' - partial in crio).
The second thing I noticed is that this built-in parser does not work properly with many streams (multiple files): 

**`flb_ml.c: 603`**
```
if (lru_parser && lru_parser-> last_stream_id == stream_id) 
```

if this condition is not met then flushing occurs, which of course also breaks the partial line collection. 

I made a test change in the code, which I have been testing for some time and it looks like it solves the problem:
- commenting code which enables auto flushing: 

**`tail_config.c:363`**
```
#ifdef FLB_HAVE_PARSER
    /* Multiline core API */
    if (ctx->multiline_parsers && mk_list_size(ctx->multiline_parsers) > 0) {
        ret = multiline_load_parsers(ctx);
        if (ret != 0) {
            flb_plg_error(ctx->ins, "could not load multiline parsers");
            flb_tail_config_destroy(ctx);
            return NULL;
        }

        /* Enable auto-flush routine */
        //ret = flb_ml_auto_flush_init(ctx->ml_ctx);
        //if (ret == -1) {
        //    flb_plg_error(ctx->ins, "could not start multiline auto-flush");
        //    flb_tail_config_destroy(ctx);
        //    return NULL;
        //}
        flb_plg_info(ctx->ins, "multiline core started - pp");
    }
#endif
```
- commenting flushing when there is change in different stream: 

**`flb_ml.c:603`**
```
        if (lru_parser && lru_parser->last_stream_id == stream_id) {
            ret = ml_append_try_parser(lru_parser, lru_parser->last_stream_id, type,
                                       tm, buf, size, NULL);
            if (ret == 0) {
                processed = FLB_TRUE;
                break;
            }
            else {
                flb_error(" .. notProcessed1");
                flb_ml_flush_parser_instance(ml,
                                             lru_parser,
                                             lru_parser->last_stream_id);
            }
        }
        //else if (lru_parser && lru_parser->last_stream_id > 0) {
        //    flb_error(" .. notProcessed2 %i", lru_parser->last_stream_id);
        //    flb_ml_flush_parser_instance(ml,
        //                                 lru_parser,
        //                                 lru_parser->last_stream_id);
        //}
```

I certainly miss the algorithms and assumptions in this application and probably the workarounds I'm doing are not safe, but I hope to explain where I am wrong and maybe  some correction/improvements can be done in this matter.

**To Reproduce**
- Steps to reproduce the problem:
Watching multiple log files with one  "INPUT". Files are logs in cri-o format which contains long partial records (with short lines it's harder to reproduce). 
Configure stdout or file output. 
When watching single file it's enough to append partial logs with delays > 4s (FLB_ML_FLUSH_TIMEOUT).
When watching multiple files, delay can be shorter (1s), because changes in one file will flush lines from another one.

**Expected behavior**
I would expect that built in parser use separate buffer per file (stream). I would also expect that "flush timeout" is counted from the last change on the given file and is possible to be configured.

**Your Environment**

* Version used: 1.8.11
* Configuration:
```  
service: |
    [SERVICE]
        Flush          1
        Daemon         Off
        Log_Level      info
        Parsers_File   parsers.conf
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_PORT      2020
  inputs: |
    [INPUT]
        Name              tail
        DB                /var/log/loki_fluentbit.db
        Path              /var/log/containers/*.log
        Tag               kube.*
        Refresh_Interval  120
        Rotate_Wait       40
        multiline.parser  cri
        Buffer_Max_Size   1MB
        Mem_Buf_Limit     128MB
        Inotify_Watcher   false
  filters: |  
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Merge_Log      On
        Keep_Log       Off
        K8S-Logging.Exclude On
        K8S-Logging.Parser On
  outputs: |
    [OUTPUT]
        Name grafana-loki
        Match *
        Url http://loki-gateway/api/prom/push
        TenantID ""
        BatchWait 1
        BatchSize 1048576
        RemoveKeys kubernetes,stream
        AutoKubernetesLabels true
        LineFormat json
        LogLevel warn
```
* Environment name and version (e.g. Kubernetes? What version?):  Openshift  4.7.40

**Comment by Fullplate** [comment]
This might be of interest: https://github.com/fluent/fluent-bit/issues/3938
