### ISSUE TITLE
Time_Key on Elasticsearch output when Logstash format is on

### ISSUE THREAD

**Issue by jaul** [fluent/fluent-bit#480]
As far as I understand from the documentation and the code v0.12, when `Logstash_Format` is on, fluentbit will just ignore the value on `Time_Key` coming from parser and insert a new field named accordingly to `Time_Key` parameter on es output.

For instance:
```
        "@timestamp" : "2018-01-04T10:04:45.3Z",
        "timestamp" : "2018-01-04T10:04:22",
```
where `@timestamp` is the default for `Time_Key` and `timestamp` comes from the parser.

Is there a way to force `es` output to use the log emission time on `Time_Key` instead of current timestamp?

**Comment by jaul** [comment]
Ok, that was just a wrong setting. Thanks!

**Comment by lqdflying** [comment]
May  I know how to resolve it? i faced the same confused part.
