### ISSUE TITLE
Multiline parser breaks in Fluentbit 1.8.12 under docker/debian

### ISSUE THREAD

**Issue by lecaros** [fluent/fluent-bit#4818]
## Bug Report

**Describe the bug**
Fluent Bit 1.8.12 fails with 
```[error] [filter:expect:expect.1] exception on rule #0 'key_exists', key 'message' not found``` when running in docker container. The same config won't fail if run in local.
Version 1.8.11 won't fail in docker or host.

**To Reproduce**
```bash
git clone https://gitlab.com/tensibai/fluentbit-multiline-issue.git
cd fluentbit-multiline-issue
```
For local repro, compile or download the desired version. Then:
```bash
/path/to/fluent/bit/fluent-bit -c etc/fluent.conf
```

Both versions, 1.8.11 and 1.8.12, behave the same when running locally.

To run using docker images:

* 1.8.11 - Working
```bash
docker run -it --name repro_key_exists_1.8.11-debug -v $(pwd)/etc:/fluent-bit/etc -v $(pwd)/sources:/sources fluent/fluent-bit:1.8.11-debug sh -c "/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent.conf"
```

* 1.8.12 - Failing
```bash
docker run -it --name repro_key_exists_1.8.12-debug -v $(pwd)/etc:/fluent-bit/etc -v $(pwd)/sources:/sources fluent/fluent-bit:1.8.12-debug /bin/bash -c "/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent.conf"
```

**Expected behavior**

It should have consistent behavior. It currently displays the following error message when running 1.8.12 in docker:

```
[2022/02/14 20:21:17] [error] [filter:expect:expect.1] exception on rule #0 'key_exists', key 'message' not found. Record content:
{"log":"INFO: Deploying web application directory [/usr/local/tomcat/webapps/ROOT]\n"}
```

**Comment by patrick-stephens** [comment]
One of the changes from 1.8.11 to 1.8.12 (and current `master`) was the step up to Debian 11 from Debian 10. I therefore built a version using Debian 10 but still see the failures using current `master`:

```
$ git diff dockerfiles/Dockerfile.x86_64-master
diff --git a/dockerfiles/Dockerfile.x86_64-master b/dockerfiles/Dockerfile.x86_64-master
index 1701f5148..3a994aee4 100644
--- a/dockerfiles/Dockerfile.x86_64-master
+++ b/dockerfiles/Dockerfile.x86_64-master
@@ -1,9 +1,10 @@
-FROM debian:bullseye-slim as builder
+FROM debian:buster-slim as builder
 RUN mkdir -p /fluent-bit/bin /fluent-bit/etc /fluent-bit/log
 ENV DEBIAN_FRONTEND noninteractive
 
 ADD . /source
 
+RUN echo "deb http://deb.debian.org/debian buster-backports main" > /etc/apt/sources.list.d/backports.list
 # hadolint ignore=DL3008
 RUN apt-get update && \
     apt-get install -y --no-install-recommends \
@@ -16,7 +17,7 @@ RUN apt-get update && \
     libssl-dev \
     libsasl2-dev \
     pkg-config \
-    libsystemd-dev \
+    libsystemd-dev/buster-backports \
     zlib1g-dev \
     libpq-dev \
     postgresql-server-dev-all \
@@ -54,7 +55,7 @@ COPY conf/fluent-bit.conf \
      /fluent-bit/etc/
 
 # hadolint ignore=DL3006
-FROM gcr.io/distroless/cc-debian11
+FROM gcr.io/distroless/cc-debian10
 LABEL description="Fluent Bit docker image" vendor="Fluent Organization" version="1.9.0" author="Eduardo Silva <eduardo@calyptia.com>"
 
 # Copy certificates
@@ -67,6 +68,7 @@ COPY --from=builder /usr/lib/x86_64-linux-gnu/libz* /usr/lib/x86_64-linux-gnu/
 COPY --from=builder /lib/x86_64-linux-gnu/libz* /lib/x86_64-linux-gnu/
 COPY --from=builder /usr/lib/x86_64-linux-gnu/libssl.so* /usr/lib/x86_64-linux-gnu/
 COPY --from=builder /usr/lib/x86_64-linux-gnu/libcrypto.so* /usr/lib/x86_64-linux-gnu/
+COPY --from=builder /lib/x86_64-linux-gnu/libgcrypt.so* /lib/x86_64-linux-gnu/
 
 # These below are all needed for systemd
 COPY --from=builder /usr/lib/x86_64-linux-gnu/libsystemd* /usr/lib/x86_64-linux-gnu/
```

Build and run:
```
$ docker build -t test -f dockerfiles/Dockerfile.x86_64-master .
$ docker run --rm -it -v $PWD/etc:/fluent-bit/etc -v $PWD/sources:/sources test

**Comment by patrick-stephens** [comment]
For completeness I grabbed the latest staging build for my local PC (Ubuntu 20.04) to confirm this does work, again making the paths absolute to their specific location on my PC:
```
wget https://github.com/fluent/fluent-bit/releases/download/unstable/packages-master-ubuntu-20.04-fluent-bit_1.9.0_amd64.deb
sudo apt install ./packages-master-ubuntu-20.04-fluent-bit_1.9.0_amd64.deb
$ /opt/fluent-bit/bin/fluent-bit -c /tmp/fluentbit-multiline-issue/etc/fluent-bit.conf 
Fluent Bit v1.9.0 | NIGHTLY_BUILD=2022-02-13-02_13_43 - DO NOT USE IN PRODUCTION!
```
There must be something the parser is relying on that is not available in the container is my only thought, either a dependency or a specific call, etc.

If someone has a Debian 11 machine it would be useful to test the package for this as well, i.e. what the container builds are doing.

**Comment by patrick-stephens** [comment]
Interestingly this also seems to fail on another container target, I used the CentOS 7 compile test we already have just as a test case:
```
$ docker build -t fb-centos7 -f dockerfiles/Dockerfile.centos7 .
$ docker run --rm -it -v $PWD/etc:/fluent-bit/etc -v $PWD/sources:/sources fb-centos7 /src/build/bin/td-agent-bit -c /fluent-bit/etc/fluent-bit.conf
```
It does not seem related to the OS in the container but using them explicitly.

**Comment by patrick-stephens** [comment]
I've also repeated the failure using the actual package builder image for Debian.

However, when I use the Ubuntu builder image (matching my local PC), this works correctly:
```
$ export DOCKER_BUILDKIT=1
$ docker build --build-arg CMAKE_INSTALL_PREFIX=/opt/td-agent-bit/ --build-arg FLB_TD=On --build-arg FLB_VERSION=master --build-arg FLB_PREFIX= --build-arg FLB_NIGHTLY_BUILD=master --build-arg BASE_BUILDER=ubuntu-20.04-base --target builder -t flb-master-ubuntu/20.04 /home/pat/github/fluent/fluent-bit/packaging/distros/ubuntu
...
$ docker run --rm -it -v $PWD/etc:/fluent-bit/etc -v $PWD/sources:/sources flb-master-ubuntu/20.04 /bin/bash -c "make -j 12 && bin/td-agent-bit -c /fluent-bit/etc/fluent-bit.conf"
```
This suggests some kind of issue in the Debian build has been introduced recently - the container uses this OS as the base but it also seems to be in CentOS too.

@lecaros do we know what the original host target was that was working? Do you have a Debian machine you can test the packages on?

**Comment by patrick-stephens** [comment]
Also confirmed it fails with the UBI 8 image we're building here: https://github.com/calyptia/fluent-bit/tree/master/calyptia/ubi8
1.8.12 fails but 1.8.11 does not.

**Comment by patrick-stephens** [comment]
Tried latest packaging containers but using previous 1.8.11 source:
```
$ docker build --build-arg CMAKE_INSTALL_PREFIX=/opt/td-agent-bit/ --build-arg FLB_TD=On --build-arg FLB_VERSION=1.8.11 --build-arg FLB_PREFIX=v --build-arg FLB_NIGHTLY_BUILD=1.8.11 --build-arg BASE_BUILDER=debian-bullseye-base --target builder -t flb-1.8.11-debian/bullseye /home/pat/github/fluent/fluent-bit/packaging/distros/debian
...
$ docker run --rm -it -v $PWD/etc:/fluent-bit/etc -v $PWD/sources:/sources flb-1.8.11-debian/bullseye /bin/bash -c "make -j 12 && bin/td-agent-bit -c /fluent-bit/etc/fluent-bit.conf"
...
```
This works fine so it suggests a source code change is triggering this.

**Comment by patrick-stephens** [comment]
It looks like it is something from https://github.com/fluent/fluent-bit/commit/f8ef094ce7ae912877d366cf0155035273a32f49 triggering it. If I build this commit it fails, if I build it's parent then it passes: https://github.com/fluent/fluent-bit/commit/80d7fd1d73f26f23facf9fc9059495c22b4f04e0

**Comment by patrick-stephens** [comment]
https://github.com/fluent/fluent-bit/pull/4846 may help with this as well as it triggers a non-zero exit code on `expect` failure now for 1.8 branch.
