### ISSUE TITLE
beginner contributing to C project

### ISSUE THREAD

**Issue by AbdulHaseebHussain** [fluent/fluent-bit#482]
Would it be possible to lower the learning curve associated with contributing by including the basics within the contributing document. I've only just started contributing to open source and have have been contributing with basic features and fixes to the Logstash Plugins, within the contributing documents of Logstash Plugins it is specified for beginners how to build and run the tests e.g. using bundle, rspec and rake, and create their own plugins. 

As someone who has used C off and on I can understand the code though with regards to contributing I'm not sure how to build and test individual plugins.

Is the process cmake -> make -> make changes with tests -> submit pull request?

**Comment by edsiper** [comment]
hi @AbdulHaseebHussain 

thanks for reaching out. 

There are many areas to contribute, the workflow to start learning which I suggest is the following:

- Clone our GIT master repo
- build it with: cd build/ && cmake -DFLB_DEV=On -DFLB_TESTS_RUNTIME=On ../
- make

then you will realize that some unit tests generated specific tests for the plugins that we have. These tests uses Fluent Bit in it library mode, some runtime tests here:

- https://github.com/fluent/fluent-bit/tree/master/tests/runtime

If you are going to add a new test file make sure to register it in the CMakeLists.txt file.

Let me know how that goes.

**Comment by edsiper** [comment]
Question answered, closing this issue. If you have more questions please open a new ticket.
