### ISSUE TITLE
Elasticsearch output plugin is not working when facing latest Elasticsearch 8.0.0

### ISSUE THREAD

**Issue by zihengCat** [fluent/fluent-bit#4825]
Already fixed! https://github.com/fluent/fluent-bit/pull/3140

## Bug Report

Elasticsearch output plugin fails to send log data when facing latest Elasticsearch 8.0.0. Due to the removal of mapping types `_type`.

```
[2022/02/15 07:43:54] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}
```

<img width="1190" alt="Screen Shot 2022-02-15 at 15 46 15" src="https://user-images.githubusercontent.com/19472493/154016411-ce2f1ef7-370b-4d89-be9e-8ec908c5c862.png">

See Elasticsearch 8.0 Breaking Changes.

> https://www.elastic.co/guide/en/elasticsearch/reference/8.0/migrating-8.0.html#breaking-changes-8.0

**Comment by pxchen** [comment]
meet the same problem...

**Comment by zihengCat** [comment]
@pxchen 

Enable `Suppress_Type_Name` parameter to ignore `_type` option.

> https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch 

![Screen Shot 2022-02-15 at 18 17 37](https://user-images.githubusercontent.com/19472493/154041593-c7d38ef2-4d4e-49e3-ad86-8521c4be8f65.png)
