### ISSUE TITLE
Using multiple filters for the same record - is it possible?

### ISSUE THREAD

**Issue by felipejfc** [fluent/fluent-bit#483]
Is it possible to use multiple filters for the same record?

I'm trying to do the following:

```
  filter-kubernetes.conf: |
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_JSON_Log On
        Annotations    Off

  filter-logging.conf: |
    [FILTER]
        Name           grep
        Match          kube.*
        Regex          kubernetes.namespace_name logging

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  output-fluentd.conf: |
    [OUTPUT]
        Name            forward
        Match           *
        Host            ${FLUENTD_HOST}
        Port            ${FLUENTD_PORT}

  fluent-bit.conf: |
    [SERVICE]
        Flush         10
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-logging.conf
    @INCLUDE output-fluentd.conf

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
```

however it does not seems to be working fine, what I wanted to happen is that filter-kubernetes add kubernetes metadata into the log and then filter-logging excludes the logs coming from logging namespace.

**Comment by edsiper** [comment]
I think the missing feature is at this level:

```
    Regex          kubernetes.namespace_name logging
```

In the record, _namespace_ likely is a map key of _kubernetes_, but Regex configuration in the filter assumes you are asking for a key called "kubernetes.namespace" so that may be the reason why it's not working.

**Comment by loburm** [comment]
@edsiper can it be resolved on fluentd side? If yes, then I think it would be nice to have it here also.

**Comment by wpalmeri** [comment]
@edsiper I have a similar request. I'd like to prune some of the added kubernetes fields, for example remove the `kubernetes.docker_id` field via a `record_modifier` filter after the `kubernetes` filter, but it won't match due to the reason you stated. Does the filter chain pass along the full json representation of a record allowing this functionality. Or is there a better way to do this? Thanks!

**Comment by edsiper** [comment]
definitely this is an enhancement request. 

@loburm @wpalmeri for your specific use case, do you need it only on Grep Filter ?

**Comment by loburm** [comment]
@edsiper I think that should be enough.

Main use cases for me: read logs from specified namespaces only or ignore some namespaces.

**Comment by wpalmeri** [comment]
@edsiper I would request this enhancement for the RecordModifier filter as well

**Comment by MihaiAnei** [comment]
@edsiper 
Having:
```
"kubernetes": {
        "pod_name": "***",
        "namespace_name": "logging",
        "pod_id": "216cd7ae-1c7e-11e8-bb40-000c298df552",
        "labels": {
            "app": "***",
            "pod-template-hash": "3079797978"
        },
        "host": "***",
        "container_name": "***",
        "docker_id": "370face382c7603fdd309d8c6aaaf434fd98b92421ce7c7c8aafe7697d4aa362"
    }
```
and 
```
[FILTER]
        Name           grep
        Match          kube.*
        Regex          kubernetes logging
```
it doesn't work either. It think it might be because the value of "kubernetes" is another JSON object upon which, right now, regexp don't apply. Maybe it should be treated as a string in this case or be able to have a 'nested' field like `kubernetes.labels.app` on plugins that use this, like record_modifier or grep.

What do you guys think?

**Comment by MihaiAnei** [comment]
Meanwhile, I am using fluent-bit with `forward` to a fluentd server configured something like this:
```
    <source>
      @type forward
      port 24284
    </source>
    
    <filter kube.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern logging
      </regexp>
    </filter>

    <match kube.**>
      @type file
      path /tmp/logging
      time_slice_format %Y%m%d
      time_slice_wait 10m
      time_format %Y%m%dT%H%M%S%z
    </match>
```
It's a good enough workaround for me at the moment.

**Comment by tweettypography** [comment]
I believe I'm looking for the same thing here - the ability to apply regex / exclude patterns on nested keys - so I'll add my vote for this enhancement.

**Comment by edsiper** [comment]
tip: why not to take advantage of the [_Exclude_Path_](http://fluentbit.io/documentation/0.13/input/tail.html) configuration property ?

In Kubernetes every logfile have the namespace name in the same log file, so you can do it there. Note that I think that the ideal solution is to add a kind of _Exclude_Namespace_ in Kubernetes filter configuration.

**Comment by DeploymentKing** [comment]
@MihaiAnei I don't think this is a workaround, I prefer the approach of just forwarding to a fluentd aggregator with minimal parsing or filtering in fluent-bit. Then make the aggregator do the grunt work as this tends to be a "bigger" resource

**Comment by vsamidurai** [comment]
anybody managed exclude certain namespace logs without using fluntd aggregator?

**Comment by DigitalRogues** [comment]
Since the path and exclude_path variables can handle wildcards I'm able to exclude namespaces.

exclude_path  /var/logs/containers/*preprod*.log

**Comment by mbelchin** [comment]
I have the similar request, would like to apply the kubernetes filter to enrich my logs and then apply a grep filter to only output log with errors.

Is this already possible in the latest 0.13.8 version somehow ?

**Comment by edsiper** [comment]
I've logged the following enhancement request for filter kubernetes:

https://github.com/fluent/fluent-bit/issues/755

the other requirement I see on this thread is about improve Grep to support nested fields, no ETA for that one yet.

**Comment by tuxtof** [comment]
Same problem for me too, i want grep log coming from kubernetes by regex matching on specific annotation

[FILTER]
        Name                grep
        Match               kube.*
        Regex               kubernetes.annotations.log true

it search a "kubernetes.annotations.log" field but kubernetes output is  a map like
"kubernetes"=>{"annotations"=>{"log"=>"true"}}

how to specify this in the Regex ???

**Comment by tuxtof** [comment]
@yann-soubeyrand yes this is the same idea, but i want just select few container to log among a large number of them, so i can change all my container to put exclude annotations, i want no log by default and just activate some of them

**Comment by karthikeayan** [comment]
Can we extract the multiple fields from single field by doing multiple filters?

For example: the field "log" has string '172.17.0.1 - - [02/Nov/2018:13:16:02 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.61.1" "-" '

I want to do one more filtering and extract the fields, such as "client", "time", "http_method", "path" and so on. is this possible with fluent-bit?

**Comment by edsiper** [comment]
@karthikeayan yes it possible, please refer to the Annotations support in filter kubernetes for such specific case:

https://docs.fluentbit.io/manual/filter/kubernetes#kubernetes-annotations

**Comment by dguendisch** [comment]
Thanks @igoryak for that hint. Here's an example of excluding e.g. a k8s namespace provided at the key `kubernetes.namespace_name`:
```
[FILTER]
    Name                kubernetes
    Match               kube.*
    Merge_Log           On
    K8S-Logging.Parser  On
[FILTER]
    Name         nest
    Match        *
    Operation    lift
    Nested_under kubernetes
[FILTER]
    Name    grep
    Match   *
    Exclude namespace_name kube-system
```

**Comment by ialidzhikov** [comment]
fluent/fluent-bit-docs#156 proposed with approach how to handle nested fields for now.

**Comment by johnmarcou** [comment]
Hi, thanks @dguendisch for your example.

Here is what I am using to keep the kubernetes structure intact (since we have kibana visualisations and dashboards already based on the es docs structure).

```
    [FILTER]
        Name         modify
        Match        *
        Copy         kubernetes kubernetes_copy
    [FILTER]
        Name         nest
        Match        *
        Operation    lift
        Nested_under kubernetes_copy
        Add_prefix   kubernetes_
    [FILTER]
        Name    grep
        Match   *
        Regex kubernetes_namespace_name kube-system
    [FILTER]
        Name         modify
        Match        *
        Remove_wildcard kubernetes_
```

**Comment by kristofferahl** [comment]
This is how we ended up solving the issue with conflicting Kubernetes labels when logs are indexed in Elasticsearch...

kubernetes.labels.app=foo   
kubernetes.labels.app.kubernetes.io/name=foo

```yaml
filter-kubernetes.conf: |
  [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            <REDACTED>
      Merge_Log           On
      K8S-Logging.Parser  On

  [FILTER]
      Name                nest
      Match               *
      Operation           lift
      Nested_under        kubernetes
      Add_prefix          kubernetes_

  [FILTER]
      Name                nest
      Match               *
      Operation           lift
      Nested_under        kubernetes_labels
      Add_prefix          kubernetes_labels_

  [FILTER]
      Name                modify
      Match               *
      Rename              kubernetes_labels_app kubernetes_labels_app.kubernetes.io/name

  [FILTER]
      Name                nest
      Match               *
      Operation           nest
      Wildcard            kubernetes_labels_*
      Nest_under          kubernetes.labels
      Remove_prefix       kubernetes_labels_

  [FILTER]
      Name                nest
      Match               *
      Operation           nest
      Wildcard            kubernetes_*
      Nest_under          kubernetes
      Remove_prefix       kubernetes_

  [FILTER]
      Name                modify
      Match               *
      Remove_wildcard     kubernetes_
```

It seems to work well but is there really no better way of doing this? It would be great to be able to do something similar to this, without using nest/lift:

```yaml
  [FILTER]
      Name                modify
      Match               *
      Rename              kubernetes.labels.app kubernetes.labels.app.kubernetes.io/name
```

**Comment by sjentzsch** [comment]
@kristofferahl Looks ugly, but works fine :-) But, I would use `Hard_Rename` instead of `Rename`, otherwise you still run into the issue when both versions (`app` and `app.kubernetes.io/name`) already exist. Do you already have an insight into performance implications of those filtering steps?

**Comment by edsiper** [comment]
FYI: Filter grep already supports nested records, it works for the main issue in question:

https://docs.fluentbit.io/manual/pipeline/filters/grep#nested-fields-example

**Comment by pajel** [comment]
> https://docs.fluentbit.io/manual/pipeline/filters/grep#nested-fields-example

It would be awesome if the Modify filter worked with nested fields same as the Grep filter does.
It would remove the need to do the ugly lifting, copying, renaming, removing.
Is there a feature request opened for this? Or should I create one?
