### ISSUE TITLE
Kubernetes Merge_Log can result in conflicting field types and rejection by elastic search

### ISSUE THREAD

**Issue by awangptc** [fluent/fluent-bit#4830]
## Bug Report

**Describe the bug**
When the Merge_Log capability is enabled, conflicting field types can cause elastic search to reject records, and possibly cause a DoS of logging.  When the example logs below are generated and Trace_Error is turned on the following error will be logged on the output
```
{"create":{"_index":"<index>","_type":"_doc","_id":"<id>","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [log_json.message] of type [text] in document with id '<id>'. Preview of field's value: '{body=text}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:179"}}}}]}
```
**To Reproduce**
- Example log message if applicable:
```
{ "name": "pod", "message": "test" }
{ "name": "pod", "message": { "body": "text" } }
```

The `message="test"` field and the `message= {"body": "text"}` fields are incompatible because the former is a string text type and the latter is an OBJECT type.  Elastic search is apparently incapable of coercing text into object and object into text so it does not appear possible to configure the same field mapping in the same elastic search index to handle this conflict.

- Steps to reproduce the problem:
Enable Merge_Log and use elastic search output
```
[FILTER]
  Name                kubernetes
  Match               kube.*
  Kube_Tag_Prefix     kube.var.log.containers.
  Kube_URL            https://kubernetes.default.svc:443
  Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
  K8S-Logging.Parser  On
  K8S-Logging.Exclude On
  Merge_Log On
  Merge_Log_Key log_json
  Buffer_Size         0
```

**Expected behavior**

Expect log records to make it to elastic search without error.

**Additional context**
I posted for some suggestions on the fluent-bit slack channel and got some good ones, including using a Lua filter to manipulate  this.  I'm looking into that as a possibility but I feel like this is a fundamental problem with the Kubernetes Merge_Log capability that should be addressed without the need for external manipulation.  In our case, someone was spamming access logs with message=<json map>, which actually resulted in logs being dropped as elastic tried to work through the rejection/retries.  The solution that case was to tell the service to fix their logs, but the fact that someone can cluelessly break log ingestion so easily is a little scary.

**Comment by awangptc** [comment]
Here's a workaround using a Lua script.  The script depends this Lua library - https://github.com/rxi/json.lua - picked due to it's lightweight nature.  I could have written my own table "stringifier" but I don't know how much I trust myself right now with lua.

The Lua script is mounted in via a ConfigMap subPath
```
  log_json_message_filter.lua: |
    json = require "fluent-bit/etc/json"

    function cb_log_json_message_filter(tag, timestamp, record)
      code = 0
      local log_json_record = record["log_json"]
      if log_json_record ~= nil then
        for k, v in pairs(log_json_record) do
          if type(v) == "table" then
            log_json_record[k] = json.encode(v)
            code = 2
          end
        end
      end
      return code, timestamp, record
    end

  json.lua: |
    --
    -- json.lua
    --
    -- Copyright (c) 2020 rxi
    ... library truncated ...
```
and here's the volume mounts into the container
```
  - mountPath: /fluent-bit/etc/log_json_message_filter.lua
    name: config
    subPath: log_json_message_filter.lua
  - mountPath: /fluent-bit/etc/json.lua
    name: config
    subPath: json.lua
```

**Comment by kinseii** [comment]
Here's an example of a solution to the problem. We append the container name to the field name. We use the helm-chart values of fluent-bit and lua.

```
---
luaScripts:
  alter_fields.lua: |
    function alter_fields(tag, timestamp, record)
        new_record = record
        if (record.log_parsed and record.kubernetes.container_name) ~=nil then
            local log_container_parsed = {}
            log_container_parsed[record.kubernetes.container_name] = record.log_parsed
            new_record.log_container_parsed = log_container_parsed
            new_record.log_parsed = nil
        end
        return 1, timestamp, new_record
    end
   
  config:
    filters: |
       [FILTER]
            Name kubernetes
            Match kube.*
            Buffer_Size 256KB
            Merge_Log On
            Merge_Log_Key log_parsed
            Merge_Log_Trim Off
            Keep_Log On
      [FILTER]
            Name lua
            Match kube.*
            script /fluent-bit/scripts/alter_fields.lua
            call alter_fields
```

**Comment by alphabet5** [comment]
I solved this by setting Keep_Log (to keep the original, unparsed log message) along with ignore_malformed. This will just drop any fields that are the wrong type, but keep the rest. 

This also requires @timestamp to disable ignore_malformed

```
{
  "numeric_detection": false,
  "dynamic_date_formats": [
    "strict_date_optional_time",
    "yyyy/MM/dd HH:mm:ss Z||yyyy/MM/dd Z"
  ],
  "dynamic": "true",
  "dynamic_templates": [],
  "date_detection": true,
  "properties": {
    "@timestamp": {
      "ignore_malformed": false,
      "type": "date"
    }
  }
}
```

**Comment by kinseii** [comment]
@alphabet5 Could you specify where you set the `ignore_malformed` parameter?
I have set this parameter at the index level in index templates, but ignoring object data types does not seem to be supported.

**Comment by kinseii** [comment]
Here is the solution to the problem with data type conflict in fields: https://github.com/kinseii/fluent-bit-lua-scripts
