### ISSUE TITLE
Parser filter & Input 'Path Key' option not working with Modify filter

### ISSUE THREAD

**Issue by da-head0** [fluent/fluent-bit#4834]
## Bug Report

**Describe the bug**

I used `Parser` filter, and it worked like a charm.
But when I added `Modify` filter and `Path Key` option in Input plugin, log is not parsed with `Parser` filter and Path Key is not working either.
With annotation of `Modify` filter, log is parsed as I expected & `Path Key` is working.
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:

original log:
* 2022-02-16 05:26:43,828 [Timer-0] INFO  |c.e.demo.SpringBootLoggerApplication: 05:26:43 ::: Hello World ::: 1781 springboot-logger-66b9c88769-j2ljq 
  

without(annotating) Parser filter & Using Modify filter:
{"path"=>"/var/log/containers/test.log", "message"=>"* 2022-02-16 12:34:44,245 [Timer-0] INFO  |c.e.demo.SpringBootLoggerApplication: 12:34:44 ::: Hello World ::: 1791"}
* Path key is applied
* key 'filename' is modified to 'path'
* key 'log' is modified to 'message'

->
without(annotationg) Modify filter & Using Parser filter:
{"time_local"=>"2022-02-16 12:24:43,863", "thread"=>"Timer-0", "level"=>"INFO", "marker"=>" ", "logger"=>"c.e.demo.SpringBootLoggerApplication", "log_message"=>"12:24:43 ::: Hello World ::: 1781"}
* Path Key is not applied
* log was parsed

- Steps to reproduce the problem:
First using Parser filter then adding Modify filter & Path Key option in Input Plugin
**Expected behavior**

a parsed, key modified, path added log with `Parser` filter
**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): EKS 1.8
* Server type and version: ec2
* Operating System and version: entos7
* Filters and plugins:
```
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               appexception.*
        Path              /var/log/containers/test/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Path_Key          filename
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name      parser
        Match     userlog.*
        Key_Name  log
        Parser    userlog_parser

    [FILTER]
        Name    modify
        Match   appexception.*
        Rename  log  message

    [FILTER]
        Name    modify
        Match   etc.*
        Rename  log  message

    [FILTER]
        Name    modify
        Match   appexception.*
        Rename  filename  path

    [FILTER]
        Name    modify
        Match   etc.*
        Rename  filename  path

  parsers.conf: |
    [PARSER]
        Name userlog_parser
        Format regex
        Regex ^* (?<time_local>[0-9-]+ [0-9:,]+) \[(?<thread>.*?)\] (?<level>\S+) (?<marker>.*?)?\|(?<logger>.*?)\: (?<log_message>.*)$
```

**Additional context**

I used 4 Modify filter, but Modify filter was not working when I put 1 Modify filter.

**Comment by nokute78** [comment]
Could you check `Reserve_Data` property ?
https://docs.fluentbit.io/manual/pipeline/filters/parser

```
$ ../bin/fluent-bit -c a.conf 
Fluent Bit v1.9.0
* Copyright (C) 2015-2021 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/02/19 07:27:11] [ info] [engine] started (pid=11596)
[2022/02/19 07:27:11] [ info] [storage] version=1.1.6, initializing...
[2022/02/19 07:27:11] [ info] [storage] in-memory
[2022/02/19 07:27:11] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/02/19 07:27:11] [ info] [cmetrics] version=0.2.3
[2022/02/19 07:27:11] [ info] [sp] stream processor started
[2022/02/19 07:27:11] [ info] [output:stdout:stdout.0] worker #0 started
[2022/02/19 07:27:11] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1453492 watch_fd=1 name=a.log
[0] appexception.a.log: [1645223231.335723864, {"time_local"=>"2022-02-16 05:26:43,828", "thread"=>"Timer-0", "level"=>"INFO", "logger"=>"c.e.demo.SpringBootLoggerApplication", "log_message"=>"05:26:43 ::: Hello World ::: 1781 springboot-logger-66b9c88769-j2ljq", "path"=>"a.log"}]
^C[2022/02/19 07:27:17] [engine] caught signal (SIGINT)

```


a.conf
```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Tag               appexception.*
    Path              a.log
    Parser            docker
    Skip_Long_Lines   On
    Path_Key          filename
    Refresh_Interval  10
    Read_From_Head    on

[FILTER]
    Name      parser
    Match *
    Key_Name  log
    Parser    userlog_parser
    Reserve_Data on

[FILTER]
    Name    modify
    Match   appexception.*
    Rename  log  message

[FILTER]
    Name    modify
    Match   appexception.*
    Rename  filename  path

[OUTPUT]
    Name stdout
    Match *
```

a.log
```
2022-02-16 05:26:43,828 [Timer-0] INFO |c.e.demo.SpringBootLoggerApplication: 05:26:43 ::: Hello World ::: 1781 springboot-logger-66b9c88769-j2ljq

```

parsers.conf
```
[PARSER]
    Name userlog_parser
    Format regex
    Regex (?<time_local>[0-9-]+ [0-9:,]+) \[(?<thread>.*?)\] (?<level>\S+) (?<marker>.*?)?\|(?<logger>.*?)\: (?<log_message>.*)$

[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On

```

**Comment by da-head0** [comment]
@nokute78 
Oh I missed that option. Thanks!
