### ISSUE TITLE
CI / Windows artifacts have the wrong name

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#4837]
Windows artifacts expect td-agent-bit name but those are missing due to the migration to fluent-bit:

- https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/42601093/job/8ym7lh4wr11wyhf3#L3198

this should be fixed in appveyor.yml

**Comment by patrick-stephens** [comment]
This was resolved a while ago so that it looks for either name and uploads whatever it finds.
In the run linked you can see it finding the `fluent-bit` ones.
The error above is to do with uploading after that by the looks of it.

**Comment by patrick-stephens** [comment]
A later build looks fine for example: https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/build/job/6cd3i1genxr71xsm

**Comment by patrick-stephens** [comment]
@edsiper do you want both artefacts to build or just one (and which)?
