### ISSUE TITLE
Should DB section of in_tail input plugin have unique or shared path (pros/cons)?

### ISSUE THREAD

**Issue by gavenkoa** [fluent/fluent-bit#4838]
I have several files to ship and each is covered by a separate `[INPUT]` section so I can name `tag` and `[FILTER]` them separately.

I don't understand from the documentation https://docs.fluentbit.io/manual/pipeline/inputs/tail : should I refer to the same DB file or use a separate one for each `[INPUT]`?

I saw people reuse DB, like here https://github.com/fluent/fluent-bit/issues/3111 but there is no official statement in the docs about such an option. **Use of a separate file might impose extra resource usage, usage of the same might lead to locks...**

**Comment by gavenkoa** [comment]
up

**Comment by cveilleux** [comment]
I have the same question.. doc is unclear. It seems to work with the same db..

**Comment by aenshin-pp** [comment]
The same question here :)

@donbowman might now? :)

**Comment by donbowman** [comment]
I believe its a sqlite3 db, so it can be shared since it has locks.
