### ISSUE TITLE
Document log rotation mechanisms supported by In_tail plugin.

### ISSUE THREAD

**Issue by gavenkoa** [fluent/fluent-bit#4839]
https://docs.fluentbit.io/manual/pipeline/inputs/tail states:

> File rotation is properly handled, including logrotate's copytruncate mode.

Bold statement! copytruncate mode means file is copied in the background and than truncated. As Fluent Bit isn't aware of a new file name I don't understand how it prevents data loss on truncation? Copying and truncation could be very fast (less then a second) while Fluent Bit looks for changes with intervals like 5 sec (or based on inotify?)

I see only the safe mode when apps write files with time series names, like `app-YYYY-MM-dd.XXX.log` so no need to rename/copy, just the need to delete outdated: Fluent Bit will have enough time to find the file before it will be deleted (after a few days!).

**Comment by EKwongChum** [comment]
Maybe you can create a symbolic link to your log file, and symbolic link keeps point to current day log file .
In  fluent bit config, use symbolic link as In_tail.

**Comment by gavenkoa** [comment]
Nice idea with symlink. Still there is a need to manage symlinks rotation. I'm using mostly Java  logging frameworks, I don't know ready solution with symlinks, probably custom rotation manager need to be implemented. 

Also the behavior is not clear when symlink disappears and file is renamed: won't it lead to occasional data duplication?

At the end I decided to avoid any rotation: just files with time & sequence numbers: `app-YYYY-MM-dd.NNN.ndjson`. Java logging frameworks remove outdated files automatically, no need to bother with the package `logrotate`.

**Comment by gavenkoa** [comment]
Compare with [Log rotation results in lost or duplicate events by Flebeat](https://www.elastic.co/guide/en/beats/filebeat/current/file-log-rotation.html).

**Comment by cobb-tx** [comment]
yes i hava same problem
