### ISSUE TITLE
Tail input plugin dosen't close file descriptor properly. 

### ISSUE THREAD

**Issue by intelliguy** [fluent/fluent-bit#486]
I run a docker image (docker.io/fluent/fluent-bit:0.12.9) on a kubernetes cluster.
I found that fluentbit is always not working after some time. 
There so many file descriptors for the fluentbit process in the container.
Multiple FDs are open for a log file as below.
The number of FDs is increased continually and the fluentbit is stopping after reaching the limit. 
I doubt that the tail input plugin doesn't close the connection to the orphaned file.

-----
Mutiple FDs for a log 
-----
root@s40:/proc/38376/fd# ls -al | grep /var/lib/docker/containers/01318066a03d>
lr-x------ 1 root root 64 Jan 14 04:42 1102 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 14 05:24 1246 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 14 07:37 1392 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 14 12:29 1538 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 14 17:22 1685 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 14 22:14 1832 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 15 03:07 1981 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 15 08:00 2126 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 13 10:40 222 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 15 12:52 2273 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 15 17:45 2420 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 15 21:50 2567 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 15 22:37 2718 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 16 03:30 2859 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 16 08:23 3006 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 13 16:59 369 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 13 20:37 516 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 13 21:51 662 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 13 10:40 70 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 13 22:16 808 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log
lr-x------ 1 root root 64 Jan 14 02:44 954 -> /var/lib/docker/containers/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a/01318066a03ddb3bf06479d57337ea11bf4ec620a6e4f2553e63976f0e037a6a-json.log

**Comment by edsiper** [comment]
how are you deploying Fluent Bit ?, would you please share your Pod Yaml file and further configuration in Fluent Bit ?

**Comment by intelliguy** [comment]
I uses fluent-logging chart on openstack-helm-infra (https://github.com/openstack/openstack-helm-infra/tree/master/fluent-logging)
Whole yaml is like below.

apiVersion: v1
kind: Pod
metadata:
  annotations:
    configmap-etc-hash: 53ff21fdd4bf8c6c998f799a3c09ea78f9443971faf231232d1a1dc46520c844
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"openstack","name":"fluentbit","uid":"1b84b50e-f84e-11e7-9d9e-3ca82a1c8f58","apiVersion":"extensions","resourceVersion":"2623673"}}
  creationTimestamp: 2018-01-13T10:40:01Z
  generateName: fluentbit-
  labels:
    application: fluentbit
    component: daemon
    controller-revision-hash: "1138201063"
    pod-template-generation: "1"
    release_group: fluent
  name: fluentbit-f5tp6
  namespace: openstack
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: fluentbit
    uid: 1b84b50e-f84e-11e7-9d9e-3ca82a1c8f58
  resourceVersion: "2623702"
  selfLink: /api/v1/namespaces/openstack/pods/fluentbit-f5tp6
  uid: 1b8d8f32-f84e-11e7-9d9e-3ca82a1c8f58
spec:
  containers:
  - command:
    - /tmp/fluent-bit.sh
    env:
    - name: FLUENTD_HOST
      value: fluentd-logging
    - name: FLUENTD_PORT
      value: "24224"
    image: docker.io/fluent/fluent-bit:0.12.9
    imagePullPolicy: IfNotPresent
    name: fluentbit
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/fluent-bit.sh
      name: fluent-logging-bin
      readOnly: true
      subPath: fluent-bit.sh
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /fluent-bit/etc/fluent-bit.conf
      name: fluent-logging-etc
      readOnly: true
      subPath: fluent-bit.conf
    - mountPath: /fluent-bit/etc/parsers.conf
      name: fluent-logging-etc
      readOnly: true
      subPath: parsers.conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fluentbit-token-fwfct
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  hostPID: true
  initContainers:
  - command:
    - kubernetes-entrypoint
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INTERFACE_NAME
      value: eth0
    - name: DEPENDENCY_SERVICE
      value: openstack:elasticsearch-logging
    - name: DEPENDENCY_JOBS
    - name: DEPENDENCY_DAEMONSET
    - name: DEPENDENCY_CONTAINER
    - name: COMMAND
      value: echo done
    image: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    imagePullPolicy: IfNotPresent
    name: init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fluentbit-token-fwfct
      readOnly: true
  nodeName: s40
  nodeSelector:
    openstack-control-plane: enabled
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fluentbit
  serviceAccountName: fluentbit
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.alpha.kubernetes.io/notReady
    operator: Exists
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: varlibdockercontainers
  - configMap:
      defaultMode: 365
      name: fluent-logging-bin
    name: fluent-logging-bin
  - configMap:
      defaultMode: 292
      name: fluent-logging-etc
    name: fluent-logging-etc
  - name: fluentbit-token-fwfct
    secret:
      defaultMode: 420
      secretName: fluentbit-token-fwfct

**Comment by edsiper** [comment]
so looking at the initial ls -la it's like: Fluent Bit opened multiple times the same file and never closed the file descriptors ? some questions:

- what's the file system involved ?
- is there any specific tool doing log rotation ?, if so, please share the config

**Comment by edsiper** [comment]
ping ^

**Comment by intelliguy** [comment]
As mentioned above, It is working on kubernetes cluster and follow the default logging mechanism on k8s (https://kubernetes.io/docs/concepts/cluster-administration/logging/). 
My cluster's rotate log size is 50MB and There is no other specific setting on each container log.

**Comment by edsiper** [comment]
@intelliguy would you please test the following docker image and see if the issue persist ?

```
fluent/fluent-bit-0.13-dev
```

**Comment by intelliguy** [comment]
fluent/fluent-bit-0.13-dev

It seems that the fluent-bit(0.13-dev:0.6) does not open fd again on a same file.  But, it also cannot gather logs after some times.

**Comment by edsiper** [comment]
@intelliguy 

I've just released 0.12.14, notes here:

http://fluentbit.io/announcements/v0.12.14/ (docs: http://fluentbit.io/documentation/0.12/input/tail.html)

All docker images have been updated, if you are testing 0.13-dev, check this repo info instead:

https://github.com/fluent/fluent-bit-kubernetes-logging/tree/0.13-dev

Please test and send me some feedback

**Comment by edsiper** [comment]
Fix confirmed on #508

**Comment by intelliguy** [comment]
👍  
The patch-set is working well without incresing fds
