### ISSUE TITLE
Add missing config_map support to plugins

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#4863]
## Bug report

After landing the implementation of https://github.com/fluent/fluent-bit/issues/1672 some plugins are missed
to be migrated to the new configuration structure. This issue tracks down the progress on implementing
config maps and serves as a reference bug to track down and link any PR or bugs to be discovered
during the implementation.

### input plugins
- [x] cpu (#4898)
  - [x] unit tests
  - [x] test run
- [x] mem (#4900)
  - [x] unit tests
  - [x] test run
- [x] themal (#4901)
  - [x] unit tests
  - [x] test run
- [x] kmsg (#4920)
  - [x] unit tests
  - [x] test run
- [x] proc (#4902)
  - [x] unit tests
  - [x] test run
- [x] disk (#4899)
  - [x] unit tests
  - [x] test run
- [x] systemd (#4921)
  - [x] unit tests
  - [x] test run
- [x] netif (#4906)
  - [x] unit tests
  - [x] test run
- [x] docker
  - [x] unit tests
  - [x] test run
- [x] dummy (#4924 )
  - [x] unit tests
  - [x] test run
- [x] dummy_thread (#4925)
  - [x] unit tests
  - [x] test run
- [x] head (#4903)
  - [x] unit tests
  - [x] test run
- [x] health (#4907)
  - [x] unit tests
  - [x] test run
- [x] collectd (#5046)
  - [x] unit tests
  - [x] test run
- [x] statsd (#5047)
  - [x] unit tests
  - [x] test run
- [x] serial (#4931)
  - [x] unit tests
  - [x] test run
- [x] stdin (#4922)
  - [x] unit tests
  - [x] test run
- [x] syslog (#4981)
  - [x] unit tests
  - [x] test run
- [x] exec (#4932)
  - [x] unit tests
  - [x] test run
- [x] tcp (#4929)
  - [x] unit tests
  - [x] test run
- [x] random (#4904)
  - [x] unit tests
  - [x] test run

## output plugins

- [x] azure (#4926)
  - [x] unit tests
  - [ ] test run (CREDENTIALS ISSUE, PENDING)
- [x] bigquery (#5030)
  - [x] unit tests
  - [x] test run
- [x] counter (#4953)
  - [x] unit tests
  - [x] test run
- [x] kafka (#4951)
  - [x] unit tests
  - [x] test run
- [x] plot (#4941)
  - [x] unit tests
  - [x] test run
- [x] retry (#4952)
  - [x] unit tests
  - [x] test run
- [x] stackdriver (#5044)
  - [x] unit tests
  - [x] test run
- [x] td (#4984)
  - [x] unit tests
  - [x] test run

## filter plugins

- [x] record_modifier (#4870)
  - [x] unit tests
  - [x] test run
- [x] throttle (#5013)
  - [x] unit tests
  - [x] test run
- [x] type_converter (#4871)
  - [x] unit tests
  - [x] test run
- [x] modify (#4909)
  - [x] unit tests
  - [x] test run
- [x] nest (#4936)
  - [x] unit tests
  - [x] test run
- [x] parser
  - [x] unit tests
  - [x] test run
- [x] grep (#4872)
  - [x] unit tests
  - [x] test run
- [x] stdout (#5012)
  - [x] unit tests
  - [x] test run
- [x] geoip2 (#5019)
  - [x] unit tests
  - [x] test run

**Comment by nokute78** [comment]
I created PR #4870 for filter_record_modifier.

**Comment by nokute78** [comment]
I create PR https://github.com/fluent/fluent-bit/pull/4871 for filter_type_converter.

**Comment by edsiper** [comment]
everything is in place now! thanks @pwhelan and @nokute78 for working on this!

re: https://github.com/fluent/fluent-bit/pull/5064
