### ISSUE TITLE
out_kafka cannot connect via SASL on fluent-bit 1.9

### ISSUE THREAD

**Issue by tarruda** [fluent/fluent-bit#4866]
## Bug Report

**Describe the bug**

On fluent-bit 1.9, out_kafka SASL doesn't seem to be working. We see an error about not being able to configure `security.protocol` property:

![image](https://user-images.githubusercontent.com/842846/154764728-8b38e367-4616-4519-b424-2bd83023e5a8.png)

@agup006

**Comment by edsiper** [comment]
sasl libraries and headers must be available in the system when compiling, otherwise, SASL support is disabled.

**Comment by patrick-stephens** [comment]
@tarruda is this sorted for the staging builds? These should build properly so want to check. You can download a package from the last run here: https://github.com/fluent/fluent-bit/actions/workflows/staging-build.yaml
The containers are available directly from ghcr.io/fluent/fluent-bit/staging

**Comment by tarruda** [comment]
> @tarruda is this sorted for the staging builds? These should build properly so want to check. You can download a package from the last run here: https://github.com/fluent/fluent-bit/actions/workflows/staging-build.yaml The containers are available directly from ghcr.io/fluent/fluent-bit/staging

I will close this for now. IIRC someone mentioned that I had used the wrong version of libsasl to compile, that's what caused the problem. When I have more time I will investigate and reopen if needed.
