### ISSUE TITLE
epoll_ctl: File exists, errno=17

### ISSUE THREAD

**Issue by solsson** [fluent/fluent-bit#488]
I run https://github.com/fluent/fluent-bit-kubernetes-logging/pull/16 with modest load and very tight memory limits, 10MB. This triggers occasional restarts of the daemonset pods. Despite this it all works very well, but now I have one pod that repeatedly logs the following error:

```
[2018/01/22 09:08:15] [  Error] epoll_ctl: File exists, errno=17 at /tmp/src/lib/monkey/mk_core/mk_event_epoll.c:133
```

Before I kill the pod, is there anything I should investigate?

**Comment by edsiper** [comment]
@solsson is the HTTP Server enabled ?, if so, if you disable it do you see the same issue ?

**Comment by solsson** [comment]
What HTTP Server are you referring to?

**Comment by StevenACoffman** [comment]
Prometheus endpoint requires the HTTP server (monkey is the one in fluent-bit). The config that enables the HTTP_Server is [here in the fluent-bit-configmap](https://github.com/fluent/fluent-bit-kubernetes-logging/blob/0.13-dev/output/kafka/fluent-bit-configmap.yaml)

```
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
```

**Comment by solsson** [comment]
Thanks. Yes, I run the exact config from https://github.com/fluent/fluent-bit-kubernetes-logging/pull/16, bar memory limit changes for https://github.com/fluent/fluent-bit-kubernetes-logging/pull/18. The pod is gone now, so I'll have to see if I run into this again, and next time I will check if I get any prometheus metrics for the pod.

**Comment by solsson** [comment]
Nope, not seen. It might have been a rare error though, and the new tag hasn't been running for long.

**Comment by edsiper** [comment]
thanks, I will close it for now.
