### ISSUE TITLE
Collect Docker metadata  

### ISSUE THREAD

**Issue by linuxxin** [fluent/fluent-bit#4894]
**Is your feature request related to a problem? Please describe.**

Hello, I observed the document but did not find it. I want to collect docker metadata information such as container name 
**Describe the solution you'd like**

Is there any plug-in to get it?
**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
From what kind of host or platform? 

A kubernetes one? There's the kubernetes filter for that if so.

**Comment by nokute78** [comment]
in_docker plugin may help.
https://docs.fluentbit.io/manual/pipeline/inputs/docker-metrics
