### ISSUE TITLE
Configure FluentBit to collect Pod logs - Error invalid pattern for given tag pod.var.log.pods.

### ISSUE THREAD

**Issue by sriharsha-ZS** [fluent/fluent-bit#4896]
## Bug Report

**Describe the bug**
Configured Fluent Bit to collect Pod level logs in EKS and forward to OpenSearch. Getting below error with with below configuration. All pod level logs which has location in node level like /var/log/pods/<<podname_dockerid>>/containername/0.log

invalid pattern for given tag pod.var.log.pods.logging_fluent-bit-4zj9w_e922a1f9-187e-4409-af72-a4ed696c1ca1.fluent-bit.0.log
invalid pattern for given tag pod.var.log.pods.logging_fluent-bit-4zj9w_e922a1f9-187e-4409-af72-a4ed696c1ca1.fluent-bit.0.log

Fluent Bit Configuration:
  input-kubernetes-pods.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/pods/*/*/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
    [FILTER]
        Name                kubernetes
        Match               pod.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     pod.var.log.pods.*.*
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

- Steps to reproduce the problem:

Configure Fluent Bit with above POD level configuration to collect the logs.

Environment:

* Fluent Bit Version used: 1.5
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): AWS Kubernetes 1.21 
* OS: Amazon Linux 2
* Filters and plugins:

Additional context:

The decoding of log messages is also not working, which might related to this error.

**Comment by patrick-stephens** [comment]
Is it reproducible on a more recent version?

**Comment by bharathiram** [comment]
> 

@patrick-stephens Yes, it is reproducible in 1.9.0

**Comment by bharathiram** [comment]
Most likely due to this condition here 

https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_regex.h#L25

**Comment by bharathiram** [comment]
Here is a reason for moving from `/var/log/containers` to `/var/log/pods`

https://github.com/kubernetes/kubernetes/issues/53022

**Comment by patrick-stephens** [comment]
Yeah I know it's being deprecated although we still have to support the old approach as well whilst it is in use.

I did see this as well: https://github.com/fluent/fluent-bit/discussions/4365#discussioncomment-1701271

**Comment by patrick-stephens** [comment]
@bharathiram can you provide your full pod spec as well to see the mounts, etc.? Are you using the helm chart for this? 

What's the reason for tailing from both containers and pods subdirectories? I know on some platforms they're now symlinked as logs from containers to the pods directory to keep compatibility.
