### ISSUE TITLE
Windows Event Logs are sent to Syslog with wrong timestamp

### ISSUE THREAD

**Issue by BenoitPoulet** [fluent/fluent-bit#4897]
## Bug Report

**Describe the bug**
Windows Event Logs are sent with wrong timestamp, they are sent in UTC but with the timezone specified.
For my case Rsyslog log theses messages with one hour back in time. (my timezone is UTC+1)

**The problem was not present in Fluent Bit 1.7.7**

**To Reproduce**
Start Fluent-bit in console with Output to STDOUT enabled and Output to Syslog..
```
C:\Program Files\td-agent-bit>bin\fluent-bit.exe -c conf\fluent-bit.conf -vvv
```

Generate an event 
```
$date = Get-Date -Format FileDateTime ; eventcreate /t WARNING /id 100 /l application /d "Create event in application log : $date"
```

I see this 
`
[1] eventlogs: [1645519913.250534100, {"Channel"=>"Application", "EventID"=>100, "Qualifiers"=>0, "EventCategory"=>0, "EventType"=>"Warning", "TimeWritten"=>"2022-02-22 09:51:52 +0100", "EventTypeCode"=>4, "Data"=>"", "Sid"=>"S-1-5-21-385092596-3084104424-2559391544-500", "StringInserts"=>["Create event in application log : 20220222T0951528610"], "Message"=>"Application. Create event in application log : 20220222T0951528610. ", "ComputerName"=>"piwv-monitoring-02", "RecordNumber"=>1464, "TimeGenerated"=>"2022-02-22 09:51:52 +0100", "SourceName"=>"EventCreate"}]
`

But when i do a capture with Wireshark i see in the packet :
`
<14>Feb 22 08:51:53 piwv-monitoring-02 EventCreate[100]: Application. Create event in application log : 20220222T0951528610. 
`

I ask to my Rsyslog to dump the content of the messages he received. "timestamp_original" contain the timestamp seen in the packet :
`
{"timestamp_original":"2022-02-22T08:51:53+01:00", "host":"piwv-monitoring-02", "severity":"info", "facility":"user", "programname":"EventCreate", "procid":"100", "message":" Application. Create event in application log : 20220222T0951528610. "}
`

As you can the time is incorrect : "2022-02-22T0**8**:51:53+01:00"
The message was sent at : "2022-02-22T0**9**:51:53+01:00"

**Expected behavior**

**Your Environment**

* Version used: 1.8.12
* Server type and version: Rsyslog 8.2102.0
* Operating System and version: Windows 2016 US, Windows 2019 FR Standard 1809
* fluent-bit.conf :
```
[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        5

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    # storage.path /tmp/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    # storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    # storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    # storage.backlog.mem_limit 5M

[INPUT]
    Name         winlog
    Channels     Setup,Application,Security,System
    Interval_Sec 1
    DB           winlog.sqlite
    Tag          eventlogs

[FILTER]
    Name     lua
    Match    eventlogs
    script   eolas_siem.lua
    call     normalize_msg

[FILTER]
    Name     lua
    Match    eventlogs
    script   eolas_siem.lua
    call     eventtype_to_int

# Pour le debug en console
# -------------------------
[OUTPUT]
    name  stdout
    match *

[OUTPUT]
    name                 syslog
    match                eventlogs
    host                 pirv-siem-relay.services.com
    port                 514
    mode                 tcp
    syslog_format        rfc3164
    syslog_message_key   Message
    syslog_hostname_key  ComputerName
    syslog_procid_key    EventID
    syslog_appname_key   SourceName

```

* Filters and plugins: 
My LUA filters :
```
function normalize_msg(tag, timestamp, record)
    if record["Message"] == "" or record["Message"] == nil then
        return -1, 0, 0
    else
        record["Message"] = record["Message"]:gsub("[\r\n]+", ". ")
        record["Message"] = record["Message"]:gsub("[\t]", " ")
        record["Message"] = record["Channel"] .. ". " .. record["Message"]
        record["SourceName"] = record["SourceName"]:gsub(" ", "-")
        return 2, timestamp, record
    end
end

function eventtype_to_int(tag, timestamp, record)
    new_record = record
    if record["EventType"] == "Error" then
        new_record["EventTypeCode"] = 3
    elseif record["EventType"] == "Warning" then
        new_record["EventTypeCode"] = 4
    elseif record["EventType"] == "Information" then
        new_record["EventTypeCode"] = 6
    elseif record["EventType"] == "SuccessAudit" then
        new_record["EventTypeCode"] = 5
    elseif record["EventType"] == "FailureAudit" then
        new_record["EventTypeCode"] = 1
    end
   return 2, timestamp, new_record
end
```

**Additional context**

**Comment by BenoitPoulet** [comment]
still relevant

**Comment by braydonk** [comment]
There is another issue #2941 that reports this issue occurring even earlier. That has been open for some time but there isn't any indication of a solution at the moment.

**Comment by cancastilho** [comment]
I'm facing the same issue with Fluentbit version 3.4.2. Fluentbit is running on a Windows Server 2019 and sending syslog messages to a Linux server running rsyslogd. 

The the messages arrive in the syslog server as follows:

2025-01-22T**17**:12:00-03:00 winserver2019 Create event in application log : 20250122T1411593821

But, it should be: 

2025-01-22T**14**:12:00-03:00 winserver2019 Create event in application log : 20250122T1411593821

Is there any workaround for this?
