### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [fluent/fluent-bit#49]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [flb_input_exit_all](https://github.com/fluent/fluent-bit/blob/28e75989ff3cc2be3dba3fe241da26429390efef/src/flb_input.c#L184)
* [flb_output_exit](https://github.com/fluent/fluent-bit/blob/5c3ef57a2b29c67e19b57f6935a43aef0ff017f3/src/flb_output.c#L66)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") to find more update candidates?
```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by edsiper** [comment]
I pushed the changes, if you find more, please let me know :)

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/fluent/fluent-bit/commit/371f18a46b271d293532561b44d47360604ffc93 "Deletion of unnecessary null pointer checks").

Did you try the shown SmPL script example out?

**Comment by edsiper** [comment]
I just tested the script and I found a few matches in plugins/in_xbee/lib/libxbee-v3 only (which is a third party component)
