### ISSUE TITLE
Need an option in config file to load the external plugin

### ISSUE THREAD

**Issue by hackeracc** [fluent/fluent-bit#490]
Currently, an external plugin can be loaded in fluent-bit using a CLI parameter -e.
This request is to add this option from config file as well.

**Comment by edsiper** [comment]
@hackeracc 

I've pushed the enhancement on GIT master which will be available once 0.13 is released. Now in fluent-bit.conf you have a new option called __plugins_file__ which aims to point a file that list the available external plugins. The pointed file schema is as follows:

```
[PLUGINS]
    Path   /path/to/plugin1.so
    Path   /path/to/plugin2.so
```

Closing this enhancement as fixed now, if you have questions don't hesitate to let me know.
