### ISSUE TITLE
Elasticsearch Output - Rejected log messages get retried forever

### ISSUE THREAD

**Issue by cinder-fish** [fluent/fluent-bit#4905]
## Bug Report

**Describe the bug**
Elasticsearch may reject log messages outright, e.g.
```
[2022/02/22 15:11:22] [ warn] [engine] failed to flush chunk '1-1645542682.297643029.flb', retry in 11 seconds: task_id=1, input=tail.container-
logs > output=es.app-logs (out_id=0)
[2022/02/22 15:11:33] [error] [output:es:es.app-logs] error: Output
{"took":2,"ingest_took":0,"errors":true,"items":[{"create":{"_index":"applicationlogs-2022.02.22","_type":"_doc","_id":"616e00e6-588e-98ba-0b96-f67b0ae2ee25","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[616e00e6-588e-98ba-0b96-f67b0ae2ee25]: version conflict, document already exists (current version [1])","index_uuid":"L3YmCYOtRsysm3XT6jEzzg","shard":"2","index":"applicationlogs-2022.02.22"}}},{"create":{"_index":"applicationlogs-2022.02.22","_type":"_doc","_id":"61f120a9-4f41-debc-73ff-711df4dc71bf","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [email] of type [keyword] in document with id '61f120a9-4f41-debc-73ff-711df4dc71bf'. Preview of field's value: '{emailAddress=****@****, data={****}}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:556"}}}}]}
```
This is a retried chunk where; 
  * one message in the chunk has previously been accepted and is now `409`'ing since the id already exists (this is handled by the output) 
  * but another is being rejected with a `400` due to a structural issue with the message (a `mapper_parsing_exception`) and will never be accepted.

Messages like this will repeatedly fail until the retry limit is hit as they will constantly cause a `400` error.

If enough of these messages come through at the same time the throughput of fluent-bit can completely stop due to the backpressure caused by waiting for these messages to finish retrying and fail.

**To Reproduce**
The most common scenario we encounter this with is indexes that have dynamic mappings where a key appears in the input as both an object and a primitive value (which is invalid for ES).

So, an ES index with an index_template like:
```
{
  "index_patterns": [
    "applicationlogs-*"
  ],
  "settings": {
    "number_of_shards" : 1,
    "number_of_replicas": 0
    }
  },
  "mappings": {
    "dynamic_templates": [
      {
        "nested_fields":{
          "match":"*",
          "match_mapping_type":"object",
          "mapping":{
            "type":"object"
          }
        }
      },
      {
        "all_fields":{
          "match":"*",
          "mapping":{
            "type":"keyword",
            "ignore_above": 256
          }
        }
      }
    ]
  }
}
```

fluent-bit:
```
[SERVICE]
    Flush                      1
    Grace                      5
    Log_Level                  warn
    Daemon                     off

    HTTP_Server                On
    HTTP_Listen                0.0.0.0
    HTTP_Port                  2020

[INPUT]
    Name               tail
    Alias              tail.container-logs
    Tag                kube.*
    Path               /var/log/containers/*.log
    Refresh_Interval   10
    Parser             cri
    Docker_Mode        On
    Docker_Mode_Parser docker_multi_line
    DB                 /fluent-bit/data/flb_tail_container-logs.db
    DB.Sync            Normal
    Mem_Buf_Limit      1MB
    Skip_Long_Lines    On
    Storage.Type       memory
    Read_from_Head     false

[OUTPUT]
    Name             es
    Match            kube.*
    Alias            es.app-logs
    Retry_Limit      3

    Host             ${ELASTICSEARCH_HOST}
    Port             ${ELASTICSEARCH_PORT}
    tls              On
    http_user        ${ELASTICSEARCH_USER}
    http_passwd      ${ELASTICSEARCH_PASSWORD}

    Logstash_Format  On
    Logstash_Prefix  applicationlogs
    Buffer_Size      False
    Trace_Error      On
    Pipeline         flb-application-logs-{{ .Files.Get "files/ingestion-pipelines/flb-application-logs.json" | sha256sum }}
    Generate_ID      On
    Type             _doc
```

And sending the following messages
```
{"log": "Message", "example": "value"}
{"log": "Message", "example": {"subkey": "value"}}
{"log": "Message", "example.subkey": "value"}
```
_(Note: ES turns dotted-keys into sub-documents, I've included examples of both here)_

We see fluent-bit treats the rejected messages as errors and keeps retrying them.

These errors are also sometimes difficult to debug because the response logged from ES is partial if the response is too large. i.e. When there are lots of messages in the request / chunk and the rejected message is at the end of the list then you never see the cause in the fluent-bit logs.

**Expected behavior**
Minimally that these messages do not tie-up fluent-bit's pipeline as retrying them will never succeed. 

Additionally that visibility for these errors is improved. It would be nice to see per-message errors (and to ignore the `409`s).

And more generally for our situation we would really like to setup a dead-letter-queue for these messages so we can investigate their cause, some proposals for this:
 * add an option for `es_out` to log these messages / chunks to a file
 * add an option for `es_out` to re-emit these messages with updated tags like `rewrite_tag` does so we can reroute these messages using standard fluent-bit configuration

**Your Environment**

* Version used: `1.8.8` (`fluent/fluent-bit:1.8.8-debug` image)
* Configuration: (see above)
* Environment name and version (e.g. Kubernetes? What version?): Elasticsearch: `7.16.2`
* Filters and plugins: `es_out`

**Comment by leandropineda** [comment]
I had pretty much the same issue with `opensearch` output. In my case I don't quite understand yet why fluentbit is generating a document with the same ID but I get rid of the errors by changing `Write_Operation` to `upsert`.

[Write_Operation](https://docs.fluentbit.io/manual/pipeline/outputs/opensearch#write_operation)

**Comment by michaelswierszcz** [comment]
getting this as well. started after upgrading to eks 1.21 with containerd runtime.

**Comment by GuillaumeSmaha** [comment]
> I had pretty much the same issue with `opensearch` output. In my case I don't quite understand yet why fluentbit is generating a document with the same ID but I get rid of the errors by changing `Write_Operation` to `upsert`.
> 
> [Write_Operation](https://docs.fluentbit.io/manual/pipeline/outputs/opensearch#write_operation)

I am also trying `upsert` for `elasticsearch`. I will check in a few days if the issue is still happening or not.

**Comment by CrazyMushu** [comment]
> I am also trying `upsert` for `elasticsearch`. I will check in a few days if the issue is still happening or not.

@GuillaumeSmaha hello!

Do you checked new configuration "Write_Operation upsert" ? maybe you found another solution to this problem ?

**Comment by GuillaumeSmaha** [comment]
> > I am also trying `upsert` for `elasticsearch`. I will check in a few days if the issue is still happening or not.
> 
> @GuillaumeSmaha hello!
> 
> Do you checked new configuration "Write_Operation upsert" ? maybe you found another solution to this problem ?


Hi @CrazyMushu, using `Write_Operation upsert` solved my issue and it unblock all my fluent-bit pods.
See the graph of indexing rate after I changed the value to  `Write_Operation upsert`:
![image](https://user-images.githubusercontent.com/1287922/189542153-ea72fd90-b794-4999-99ad-1cd17b37342f.png)

**Comment by chicofranchico** [comment]
Having the same issue

```fluent-bit-qxvps fluent-bit [2022/10/24 14:07:20] [error] [output:opensearch:opensearch.0] error: Output
fluent-bit-qxvps fluent-bit {"took":9,"errors":true,"items":[{"create":{"_index":"kube-system-2022.10","_type":"_doc","_id":"vx5RCoQBgTanOZEIvo-t","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [log_processed.LB SGs] of type [text] in document with id 'vx5RCoQBgTanOZEIvo-t'. Preview of field's value: '{$ref=#/resources/AWS::EC2::SecurityGroup/ManagedLBSecurityGroup/status/groupID}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:505"}}}},{"create":{"_index":"kube-system-2022.10","_type":"_doc","_id":"wB5RCoQBgTanOZEIvo-t","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":1314948,"_primary_term":1,"status":201}}]}
fluent-bit-qxvps fluent-bit [2022/10/24 14:07:20] [ warn] [engine] failed to flush chunk '1-1666620414.391417856.flb', retry in 41 seconds: task_id=0, input=tail.0 > output=opensearch.0 (out_id=0)
```

The log_processed.LB SGs is set as text:

```      
          "LB SGs" : {
              "type" : "text",
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
```

Fluentbit will simply become a zombie after a while due to too many retries of these messages.

How can I tell the index creation to either ignore that or treat the json as text verbatim?

**Comment by simbou2000** [comment]
Fixing this issue would make Fluent-Bit more resilient in case of erroneous data within some records that can lead to continuously sending lots of junk and filling up memory/filesystem because it won't discard those.

**Comment by Stono** [comment]
+1 also getting this issue!

**Comment by LHozzan** [comment]
Hi guys.
Try you please a higher FluentBit version?
We using FluentBit v2.0.8 with OpenSearch 2.2.0.
If some problems occurred, FluentBit retry sent data provided times and if problem is persistent, he discard them. Looks like:
![FluentBitStats](https://user-images.githubusercontent.com/24796361/219298909-0140d22a-bea3-437e-a569-e0b5c495d729.png)

Our config:
```
[OUTPUT]
    Name                opensearch
    Match               kube.*
    Host                ${FLUENT_HOST}
    Port                ${FLUENT_PORT}
    HTTP_User           ${FLUENT_USER}
    HTTP_Passwd         ${FLUENT_PASSWORD}
    Logstash_Format     On
    Logstash_Prefix     containers
    Replace_Dots        On
    Retry_Limit         25
    Trace_Error         On
    Suppress_Type_Name  On
    Include_Tag_Key     Off
    Time_Key_Nanos      On
    Generate_ID         On
    tls                 On
    tls.Verify          On
    tls.ca_file         /fluent-bit/ssl/root-ca.pem
    tls.crt_file        /fluent-bit/ssl/admin.pem
    tls.key_file        /fluent-bit/ssl/admin-key.pem
    Buffer_Size         1024kb
```
Hope that get you closer to the solution!

**Comment by acastong** [comment]
The one worry I have with using Retry_Limit is that if the interruption in service is due to a networking issue or a temporary interruption in the destination, all records could be dropped once the Retry_Limit is reached.  In case of such an issue, I would prefer to retry forever. It would be interesting to make a distinction between connection issues and actual error codes returned by the destination.

**Comment by tiimbz** [comment]
Also seeing this issue with Elasticsearch output: Our error messages were not network-related but related to formatting of log fields. They got retried forever as the fields had an incorrect format. The unlimited retries completely blocked the shipping of other logs. Changing `Retry_Limit false` to `Retry_Limit 5` fixed the issue.

> It would be interesting to make a distinction between connection issues and actual error codes returned by the destination.

+1 for this approach.

**Comment by marcelofabricanti** [comment]
Same here. FB 3.1.9 

Changed to upsert, no more warning logs, despite the increase of cluster overhead.


Is there a wish to fix this at some time?
