### ISSUE TITLE
Dependency to EOL postgresql-lib 9.2

### ISSUE THREAD

**Issue by mathias-burkl** [fluent/fluent-bit#4910]
## Bug Report

**Describe the bug**
During the installation on RHEL 7 the td-agent-bit has a dependency to postgresql-libs in version 9.2.24
This version is already end of live and rather the libpq in version 13 shall be used

**Expected behavior**
 dependency to libpq in version 13 is expected

**Screenshots**

**Your Environment**
* Version used: 1.18.12-1
* Server type and version: virtual server
* Operating System and version: Red Hat Linux 7 kernelVersion 3.10.0-1160.25.1.el7.x86_64

**Additional context**
Trying to install the latest New Relic agent in version 1.23.2 which uses the above mentioned td-agent-bit version 1.18.12-1

**Comment by sxd** [comment]
@mathias-burkl Red Hat 7 support is until 2026 following [this link](https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates) but if you look into the PostgreSQL availability in the distributions [here](https://www.postgresql.org/download/linux/redhat/) you will see that top package supported there is PostgreSQL 10, which will be EOL by the end of 2022.

Some recap, this is what RHEL7 provides, can we create the packages using SCL? probably the answer is no, but I'm not fully qualify to define if Red Hat allows to build packages with the SCL group of packages.

On the other hand, forcing the dependency of  PostgreSQL 13 in Red Hat 7 may break others people deployment using Red Hat 7, and in this case, you have already all the security patches and in our case, Fluentbit use only the PostgreSQL protocol, so is really weird that it could security bug, and in that case, the distribution provides a really LTS for that version.

@mathias-burkl are you actually having an error or a bug? or this is just a desirableness behavior ?f

Regards!

**Comment by patrick-stephens** [comment]
I agree with you @sxd: we need to ensure installation on a vanilla RHEL 7 target works without any extra set up for SCL, etc.
As you say Red Hat are supporting it themselves so it is not EOL until the later date and not subject to the same restrictions.

It may be we can support an update in the CentOS 8 packages to a more recent version so please submit a PR for that if so: https://github.com/fluent/fluent-bit/blob/cd92cf36099e69c09b0448e6bc0032bd4ac81ac5/packaging/distros/centos/Dockerfile#L64
However, CentOS 8 itself is EOL as well now so we need an alternative there too.

As @sxd asks, is this causing a specific issue @mathias-burkl ?
