### ISSUE TITLE
Feature request : out_stackdriver : Add instance_name as label in stackdriver output plugin.

### ISSUE THREAD

**Issue by franciscovalentecastro** [fluent/fluent-bit#4912]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Add the name of the vm as a label when using the stackdriver output plugin.

![Screen Shot 2022-02-23 at 16 07 17](https://user-images.githubusercontent.com/1435136/155417202-48bef2c9-ab74-41fc-ac1b-11bf57d24552.png)

**Describe alternatives you've considered**
We tried the approach of configuring Fluent Bit to use a filter with `modify` + `nest` the following way :

```
[FILTER]
    Add   compute.googleapis.com/resource_name test_vm
    Match *
    Name  modify

[FILTER]
    Match      *
    Name       nest
    Nest_under logging.googleapis.com/labels
    Operation  nest
    Wildcard   compute.googleapis.com/resource_name*
```

But there is noticeable CPU usage increase (being `perf-fcovalent-3-1` the one using the filter) with this approach, so it's not the best solution for a high load use case.
![Screen Shot 2022-02-23 at 16 14 39](https://user-images.githubusercontent.com/1435136/155418149-1c82a308-382a-4cc8-8eb2-6a584dfe79bf.png)

We propose two other solutions as updates in the out_stackdriver plugin :  

- Getting the `instance_name` in the same way as [other](https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/gce_metadata.h#L35) metadata values and add it as a static value in the [labels](https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/stackdriver.c#L1897) section of the pack entry.
- Adding the more general feature of setting static [label](https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/stackdriver.c#L1897) values during configuration of the stackdriver output plugin.

**Comment by franciscovalentecastro** [comment]
Discussed with @qingling128 about this feature request. What are your thoughts this approaches @edsiper ?

**Comment by lecaros** [comment]
hi @franciscovalentecastro do we need anything else here?

**Comment by franciscovalentecastro** [comment]
Hello @lecaros ! No, there is nothing left to do for this issue. Closing it.
