### ISSUE TITLE
is it possible to copy one record value into another record

### ISSUE THREAD

**Issue by jaisharma0009** [fluent/fluent-bit#492]
I looked at record_modifier plugin. Not sure if i can use that to copy value from another field.

**Comment by edsiper** [comment]
hi @jaisharma0009, this is not a supported feature. 

what's your specific use case ?

**Comment by edsiper** [comment]
feature not supported.

**Comment by mentalblock** [comment]
Hello, im looking into this as well.

I have an event that comes in as {"message": "some unstructured string"}
I use a [Parser Filter](http://fluentbit.io/documentation/current/filter/parser.html) to parse the string into fields. I still need the original "message" key along with all the fields created by the parser. I do not see an easy way to do this.

I would like to copy "message" to "messagecopy" and run the filter against the new copy. This will allow me to retain the original "message" key as well as have new fields from the parsing. Can you suggest an alternative?
