### ISSUE TITLE
logfmt parser falsely recognizes non-logfmt logs

### ISSUE THREAD

**Issue by trutty** [fluent/fluent-bit#4927]
## Bug Report

**Describe the bug**
The [logfmt](https://docs.fluentbit.io/manual/pipeline/parsers/logfmt) parser also recognized non-logfmt logs.

I have different containers that use different log formats such as JSON, logfmt or just plain text etc.. All of them have to be supported and parsed by fluent-bit. Unfortunately, the `logfmt` parser falsely recognizes everything as logfmt format - not just plain text but also e.g. JSON structures. Because of this behaviour I  can not use logfmt altogether because it breaks log messages.

**To Reproduce**

Install fluent-bit in cluster (e.g. minikube) with `helm upgrade --install fluent-bit fluent/fluent-bit -f values.yaml` (see `values.yaml` below). With this config, I create a debug containers that logs the following messages:

|container log|stdout in fluentd|comment|
|--|--|--|
|{"key1":"json","key2":"some text"}|[0] tail.0: [1645784180.306673842, {"key1"=>"json", "key2"=>"some text"}]|first specified parsed (json) correctly parses input|
|key1=logfmt key2="some text"|[0] tail.0: [1645784180.306673842, {"key1"=>"logfmt", "key2"=>"some text"}]|first parser (json) passes; second parser (logfmt) correctly parses input|
|some|[0] tail.0: [1645784180.306673842, {"message"=>"some"}]|first two parsers pass; last parser (universal) correctly parses input|
|some text|[0] tail.0: [1645784180.306673842, {"some"=>nil}]|logfmt parser falsely parses input|

If I specify the `logfmt` parser as first of the three parsers, then also the JSON log messages get falsely "parsed" by logfmt.

**Expected behavior**
Only logfmt messages (`key=value`) get recognized as logfmt format by the logfmt parser. Strings such as `{"key1":"json","key2":"some text"}` or `some text` should not be recognizes as logfmt.

**Screenshots**
-

**Your Environment**

* Version used: Fluent Bit v1.8.12
* Configuration:
```
config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*debug*.log
        multiline.parser docker, cri

  filters: |
    [FILTER]
        Name parser
        Match *
        Key_Name log 
        Parser json
        Parser logfmt
        Parser universal

  outputs: |
    [OUTPUT]
        Name  stdout
        Match *

  customParsers: |
      [PARSER]
          Name        universal
          Format      regex
          Regex       ^(?<message>.*)$

      [PARSER]
          Name        logfmt
          Format      logfmt
```

**Additional context**
-

**Comment by trutty** [comment]
After looking a bit more into the [formal definition of the logfmt format](https://pkg.go.dev/github.com/kr/logfmt), I think that the actual logfmt parser is correct according to the definition but that the definition is just really broad. __Basically anything__ matches the definition of logfmt:

The string `"application started in 35s"` is valid logfmt
-> `"application":true,"started":true,"in":true,"35s":true`,

such is the JSON string `{"message":"application started in 35s"}` valid logfmt
-> `"{message:application started in 35s}":true`

where _valid_  means that the string matches the formal description and not that the result makes any sense, because the format does not require the string to have any `key=value` pairs. I am not sure where to go from here, because it means that I can not use the `logfmt` to recognize logs.

Any help is appreciated. Thanks.

**Comment by applike-ss** [comment]
I just ran into the same issue while trying to write a generic enough logging pipeline.

It seems we have to properly select by tag/wildcard here what our input is.
