### ISSUE TITLE
Multiline parser results not consistent

### ISSUE THREAD

**Issue by tom-dierckx** [fluent/fluent-bit#4928]
## Bug Report

**Describe the bug**

We are trying to create a (custom) multiline filter for dotnetcore logs in kubernetes. Currently we are able to match some multiline logs not all of them. We are unable to see why some logs are merged and some are not.

Folowing multiline parser is used:
```
[MULTILINE_PARSER]
          name          multiline-dotnetcore-logs
          type          regex
          flush_timeout 3s
          rule      "start_state"   "/(?:\\u001b\[[0-9]+m)?(?:\\u001b\[[0-9]+m)?[a-z]{4}(?:\\u001b\[[0-9]+m)?(?:\\u001b\[[0-9]+m)?(?:\\u001b\[[0-9]+m)?(.*)\[[0-9]+\]([\\n]*)?$/"  "cont"
          rule      "cont"          "/^\s{6}.*([\\n]*)?$/"     
```

Example:
Merged successfully:
```
\u001b[40m\u001b[37mdbug\u001b[39m\u001b[22m\u001b[49m: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[11]\n      List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter\n
```
Didn't Merge:
```
\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Microsoft.EntityFrameworkCore.Database.Command[20101]\n
      Start processing event candidate 492137.\n
      Entity Framework Core 5.0.6 initialized 'EntityContext' using provider 'Npgsql.EntityFrameworkCore.PostgreSQL' with options: SensitiveDataLoggingEnabled \n
```

Rubular link to the logs that where not merged: [here](https://rubular.com/r/MpcQCUrFqsdHYA)

-  We have not been able to reproduce the issue on a smaller scale.

**Expected behavior**
Merging all the multiline logs that match the regex and reduce the amount of logs.

**Screenshots**
Resulting logs in opensearch:
![someworksomedont](https://user-images.githubusercontent.com/6592971/155714403-7e4f4c50-7c40-4157-98dc-362b2633e4ea.png)

**Your Environment**

Kubernetes -> fluentbit pod -> kafka -> logstash -> OpenSearch
* Version used: 1.8.12
* Configuration: Example setup of how it is setup config can be found [here](https://github.com/tom-dierckx/fluentbit-dotnetcore-multiline)
* Environment name and version (e.g. Kubernetes? What version?): Multiple versions Openshift and kubernetes
* Filters and plugins: Multiline filter

**Additional context**
As this is most likely an issue on our end how would we proceed in debugging this issue?

Regards,

Tom

**Comment by tom-dierckx** [comment]
We also see this issue for the same pod sometimes it works and sometimes it does not. Are there parameters we can tweak?

**Comment by tom-dierckx** [comment]
Still present after upgrade to 1.8.13.

**Comment by yangzan0816** [comment]
i have the same problem,
Do you have a solution to the problem?

**Comment by trallnag** [comment]
I also noticed something similar. Directly after deleting the Helm release and redoing everything from scratch the multiline filter works. Logs get aggregated. But after some time it seems to just stop working. I already assumed something is wrong with my mind but maybe there's a general issue with the parser.
