### ISSUE TITLE
Avoid dns timeout null event injection

### ISSUE THREAD

**Issue by matthewfala** [fluent/fluent-bit#4957]
Fluent Bit segfaults periodically due to dns timeout null event injection.
Bug introduced in 1.8.12

Essentially, Fluent Bit expects on connection timeout that upstream u_conn->event is an event that will resume the coroutine that is blocked on the network call and manually triggers this event. This is not true for DNS coroutine yields. Before DNS yeild, event remains uninitialized. When timeout occurs, null event injected which is actually a custom event of handler 0x0. This event when processed causes a segfault.

Timeline:

1. Flush code makes network call
2. DNS timeout (10 seconds pass, DNS timeout callback not called due to other coroutines taking time)
https://github.com/fluent/fluent-bit/blob/56713bdb0839aa8ab00429931792c133b7a65f52/src/flb_network.c#L1089
At this point, u_conn->event.status is `MK_EVENT_NONE` due to:
https://github.com/fluent/fluent-bit/blob/56713bdb0839aa8ab00429931792c133b7a65f52/src/flb_upstream.c#L545
3. Callback timer flb_upstream_conn_timeouts triggered
https://github.com/fluent/fluent-bit/blob/56713bdb0839aa8ab00429931792c133b7a65f52/src/flb_engine.c#L121
4. DNS event injected (this event is blank, MK_EVENT_NEW() event, so it is Custom event of handler 0x0)
https://github.com/fluent/fluent-bit/blob/56713bdb0839aa8ab00429931792c133b7a65f52/src/flb_upstream.c#L843-L850
5. Injected event handler 0x0 executed. Segfault.
https://github.com/fluent/fluent-bit/blob/56713bdb0839aa8ab00429931792c133b7a65f52/src/flb_engine.c#L798-L800

How to test problem:

 1. Add a 10 second sleep to the coro_yield in the flb_net_getaddrinfo right before the flb_coro_yield.
```
diff --git a/src/flb_network.c b/src/flb_network.c
index 32311dbe0..350a7c829 100644
--- a/src/flb_network.c
+++ b/src/flb_network.c
@@ -1064,6 +1064,7 @@ int flb_net_getaddrinfo(const char *node, const char *service, struct addrinfo *
                     flb_net_dns_lookup_context_drop(lookup_context);
                 }
                 else {
+                    sleep(10);
                     flb_coro_yield(coroutine, FLB_FALSE);
                 }
             }
```
2. Test fluent bit
```
[SERVICE]
    Flush           1
    Daemon          off
    Log_Level       info

[INPUT]
     Name dummy
     Tag dummy

[OUTPUT]
     name                kinesis_firehose
     match               *
     region              us-west-2
     delivery_stream     firehose-compression-4-0
     workers             1
     Retry_Limit         5
```
3. View segfault after 25 seconds
```
Fluent Bit v1.8.13
* Copyright (C) 2015-2021 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/02 01:23:32] [ info] [engine] started (pid=15071)
[2022/03/02 01:23:32] [ info] [storage] version=1.1.6, initializing...
[2022/03/02 01:23:32] [ info] [storage] in-memory
[2022/03/02 01:23:32] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/02 01:23:32] [ info] [cmetrics] version=0.2.2
[2022/03/02 01:23:32] [ info] [output:kinesis_firehose:kinesis_firehose.0] worker #0 started
[2022/03/02 01:23:32] [ info] [sp] stream processor started
[2022/03/02 01:23:53] [error] [upstream] connection #-1 to firehose.us-west-2.amazonaws.com:443 timed out after 10 seconds
[2022/03/02 01:23:53] [error] [upstream] connection #-1 to firehose.us-west-2.amazonaws.com:443 timed out after 10 seconds
[2022/03/02 01:24:26] [engine] caught signal (SIGSEGV)
#0  0x0                 in  ???() at ???:0
```
Segfault from 
https://github.com/fluent/fluent-bit/blob/887c29486de0c425726794f0addaebc99ab498fa/src/flb_output_thread.c#L296
since event is:
```
// MK_EVENT_ZERO() from mk_inject on connection timeout when blocking on DNS
{
  fd: -1
  type: 4
  mask: 5
  status: 1
  data: 0x0
  handler: 0x0
}
```
Solution attempt https://github.com/fluent/fluent-bit/pull/4956 (needs review before merging. I think this only affects DNS yield and timeouts):
Add injection guard. Do not resume coroutine (Expected DNS timeout callback to resume the coroutine)
https://github.com/fluent/fluent-bit/pull/4956 suspect cause coroutine hang on DNS timeout

Coroutine blocked on DNS code will resume here after DNS timeout callback occurs:
https://github.com/fluent/fluent-bit/blob/887c29486de0c425726794f0addaebc99ab498fa/src/flb_network.c#L547-L565

~~Solution attempt problem:
It turns out that there is no DNS timeout callback resume functionality, so the solution is incorrect. Will cause certain timeouts to hang.~~

~~Another solution:
Better solution is to actually create correct resume event before DNS yield. Not sure if the timeout code is set currently to handle proper timeout resumes.~~

## Bug Report

**Describe the bug**

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by matthewfala** [comment]
Merged to Master. May need 1.8 backport.

**Comment by patrick-stephens** [comment]
Yeah it will, master is 1.9
