### ISSUE TITLE
Input plugin 'systemd' cannot be loaded

### ISSUE THREAD

**Issue by trstringer** [fluent/fluent-bit#496]
I'm getting the following error:

```
Fluent-Bit v0.13.0                     
Copyright (C) Treasure Data            

Input plugin 'systemd' cannot be loaded                                        
Error: Configuration file contain errors. Aborting    
```

Is there something else I need to do to use the `systemd` input plugin?

Fluent Bit config file:

```
[SERVICE]
    Flush 1
    Log_Level info

[INPUT]
    Name systemd
    Tag host.*
    Systemd_Filter _SYSTEMD_UNIT=mydaemon.service

[OUTPUT]
    Name stdout
    Match *
```

Thank you in advance!

**Comment by edsiper** [comment]
In order to check if you have systemd support in Fluent Bit just start it with the option __-h__, that will list all input, filters and outputs available.

Likely you have a configuration indentation problem, please refer to the following docs about how to fix it:

http://fluentbit.io/documentation/0.12/configuration/schema.html

**Comment by trstringer** [comment]
@edsiper thank you for the quick reply!

Looks like I don't have `systemd` as an input:

![fluentbit_systemd](https://user-images.githubusercontent.com/1445483/35546966-6b4c4584-0544-11e8-992d-0988b45aab50.png)

What do I need to do to "enable" the `systemd` input?

**Comment by edsiper** [comment]
if you have created a package or compiled yourself and there is no systemd support, means that your build system did not have systemd development libraries at build time.

I suggest you use our available packages (deb/rpm)

**Comment by trstringer** [comment]
Ok I see. I'll play around with the rpm.

In the event a user did want to build from source _and_ have systemd support, what's the way to go about that?

**Comment by edsiper** [comment]
Fluent Bit build system (CMake) try to detect if Systemd library and development headers are in place, if so, it will include Systemd input plugin. Once compiled/packaged the only need is systemd shared library (not headers).

**Comment by trstringer** [comment]
It looks like, on CentOS, the existence of `systemd-devel` includes the libs that cmake uses to determine `FLB_HAVE_SYSTEMD`.

```
# yum install -y systemd-devel
$ cd fluent-bit/build
$ cmake ..
$ make
$ bin/fluent-bit -h | grep systemd
```

Outputs:

```
  systemd               Systemd (Journal) reader
```

Thanks for the help, @edsiper!!
