### ISSUE TITLE
config_map:  add support for enumerations to config_map.

### ISSUE THREAD

**Issue by pwhelan** [fluent/fluent-bit#4965]
For the 1.9 milestone we are  moving heavily towards the use of config_map,  especially to support different  configuration formats.  One feature that is missing is the support for enumerations, ie:  string constants that are then converted into numerical values. At the moment all of my work has been using a parallel field with the `_str` suffix to  parse and then assign the value to the configuration context.

I  do not currently have a fully working solution. To continue using the current workflow I believe the solution has to:

- allow for easy literal declarations, no constructing the config_map enumerations with runtime calls
- be a direct part of the `struct flb_config_map` type

The current declaration of `struct flb_config_map` is such:

```c
struct flb_config_map {
    /* Public fields used by plugins at registration */
    int type;                      /* type */
    flb_sds_t name;                /* property name */
    flb_sds_t def_value;           /* default value */
    int flags;                     /* option flags (e.g: multiple entries allowed) */
    int set_property;              /* set context property ? (use offset ?) */
    uintptr_t offset;              /* member offset */
    flb_sds_t desc;                /* description */

    struct flb_config_map_val value; /* lookup value */
    struct mk_list _head;
};
```

I am in no way committed to this implementation but it serves, at least for now, as a basic workable solution.

This has at the very least the gotcha that we cannot put  a zero-length array of enumerations right after the description even if we wanted to since it would overwrite the value and _head values. These values are used in the copies of the config_map that each  plugin instance uses to store the values before they are copied into the plugin's context structure. These values might also be used for reference when calling flb_config_prop_get or flb_input_config_get_property but I am not sure.

If we use a method similar to what is done with flb_sds_t we could simply move the value and _head properties into a separate header. This would require reallocating the flb_config_map when a plugin is loaded.

At the moment I am working with this base structure for the actual enumerations:

```c
struct flb_config_map_enum {
    char *name;
    int value;
};
```

At the moment I have tried literal declarations by defining the enumerations as a pointer to a pointer of flb_config_map_enum. This might be a total dead end if the compiler is unable to sort out the pointers from the literal declaration.

**Comment by pwhelan** [comment]
Nested flexible arrays are not a thing in the current version of C... so  the current workaround I'm trying is to simply limit the amount of numeric values:

```c
struct flb_config_map {
    /* Public fields used by plugins at registration */
    int type;                      /* type */
    flb_sds_t name;                /* property name */
    flb_sds_t def_value;           /* default value */
    int flags;                     /* option flags (e.g: multiple entries allowed) */
    int set_property;              /* set context property ? (use offset ?) */
    uintptr_t offset;              /* member offset */
    flb_sds_t desc;                /* description */

    struct flb_config_map_enum enums[32];
};
```

**Comment by edsiper** [comment]
for another use case (groups) I was thinking about making an union for def_value, e.g:

```c
struct flb_config_map_enum {
    char *name;
    int value;
};
```

```c
struct flb_config_map {
    /* Public fields used by plugins at registration */
    int type;                      /* type */
    flb_sds_t name;                /* property name */
    union {
        char *def;
        struct flb_config_map_group *group_def;
        struct flb_config_map_enum *enum;
    }'
    int flags;                     /* option flags (e.g: multiple entries allowed) */
    int set_property;              /* set context property ? (use offset ?) */
    uintptr_t offset;              /* member offset */
    flb_sds_t desc;                /* description */
};
```

potentially the developer can do:

```c
static struct flb_config_map config_map[] = {
    {
     FLB_CONFIG_MAP_ENUM, "compress_mode", {.enum = myenum},
     0, FLB_FALSE, 0,
     "...."
    },

```

**Comment by pwhelan** [comment]
I really like the idea of using a union for the default values.
