### ISSUE TITLE
filter "rewrite_tag" rule cannot extract values from multiple field

### ISSUE THREAD

**Issue by yong-jie-gong** [fluent/fluent-bit#4976]
## Bug Report

**Describe the bug**
If filter "rewrite_tag"  Rule contains filed, fluent-bit fails to start

**To Reproduce**
version: fluent-bit 1.9.0-rc2
1) use fluebit configuration below
```
[SERVICE]
    Flush     1
    Log_Level info

[INPUT]
    NAME   dummy
    Dummy  {"tool": "fluent", "type": "test01",  "sub": {"s1": {"s2": "bit"}}}
    Tag    test_tag

[FILTER]
    Name          rewrite_tag
    Match         test_tag
    Rule          $tool ^(fluent)$  /dir1/$TAG/$tool/$type/tool.out false
    Emitter_Name  re_emitted

[OUTPUT]
    Name file
    Mkdir true
    Match *

```
3) .fluentbit failed to start with errors below

```
-bash-4.2# ./fluent-bit -c fb.rewrite.conf

[2022/03/03 19:12:51] [ info] [engine] started (pid=3843)
[2022/03/03 19:12:51] [ info] [storage] version=1.1.6, initializing...
[2022/03/03 19:12:51] [ info] [storage] in-memory
[2022/03/03 19:12:51] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/03 19:12:51] [ info] [cmetrics] version=0.2.3
**[2022/03/03 19:12:51] [error] [record accessor] syntax error, unexpected '$', expecting $end at '$tool/$type/tool'**
[2022/03/03 19:12:51] [error] [filter:rewrite_tag:rewrite_tag.0] could not compose tag: /dir1/$TAG/$tool/$type/tool.out
[2022/03/03 19:12:51] [error] Failed initialize filter rewrite_tag.0
[2022/03/03 19:12:51] [error] [lib] backend failed

```
Note:
if Rule changes to     "Rule          $tool ^(fluent)$  /dir1/$TAG/$tool.out false", it works

- Steps to reproduce the problem:

**Expected behavior**
fluent-bit should not fail, rules should be allowed to construct from multipel field

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by m17kea** [comment]
For anyone finding themselves here, as per the [docs](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor), the only acceptable character after a $ expression seems to be a '.'
