### ISSUE TITLE
No error message for missing parser file

### ISSUE THREAD

**Issue by mmariani** [fluent/fluent-bit#498]
fluent-bit prints a nice message when a configuration file is missing:

```
#  docker run -p 127.0.0.1:24224:24224 fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit --config /tmp/missing --verbose
Fluent-Bit v0.12.12
Copyright (C) Treasure Data

Error: Could not open configuration file. Aborting
```

Interestingly, the error message may appear either before or after the version number, should stdout be flushed?

Anyway, nothing is displayed when a parser file is not found:

```
#  docker run -p 127.0.0.1:24224:24224 fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit --parser /tmp/missing --verbose
#  echo $?
1
```

**Comment by edsiper** [comment]
thanks @mmariani for catching up this.

I've pushed a fix into GIT master (and will be available in the next 0.12.13 too).

ref: https://github.com/fluent/fluent-bit/commit/23b617124f8ed9edab02d79daa45a9eb7da16efb
