### ISSUE TITLE
Windows options are not useable. FLB_OUT_LIB needed under Windows.

### ISSUE THREAD

**Issue by SteRoh** [fluent/fluent-bit#4985]
Is it possible to enable/disable plugins under Windows?

Found these lines of code which override my cmake options.
https://github.com/fluent/fluent-bit/blob/17d14e79f7885d3942188a5529786945123928a7/CMakeLists.txt#L301

I really need the FLB_OUT_LIB under Windows and it works as expected. :)
The only Problem is that I can not set any build options from outside within my cicd.

**Comment by edsiper** [comment]
please submit a PR

**Comment by SteRoh** [comment]
#5011  
Currently I´m using this feature already in our code.
Your build environment fells a little bit Linux heavy. I guess most of your features start under Linux development.

How well is windows tested? Which compiler are u testing during ci/cd?
 Its hard to find anything related to windows stuff :)

**Comment by patrick-stephens** [comment]
Windows is currently built by Appveyor for release: https://github.com/fluent/fluent-bit/blob/master/appveyor.yml
However we are transitioning this to Github Actions: https://github.com/fluent/fluent-bit/issues/3720
There is a CI job currently but it only builds: https://github.com/fluent/fluent-bit/actions/workflows/windows-build.yaml

I was pulling together a smoke test for Windows here but had to abandon it until after the 1.9 release: https://github.com/fluent/fluent-bit/pull/4718

Love to get a PR in this area, although in this case the main change is to CMake support I think.

You're right that a lot of the Windows side of things can be improved so please submit PRs, even docs ones, so we can merge them - it's all OSS after all.

**Comment by SteRoh** [comment]
Thank you for your fast replies.
I really appreciate to collaborate a bit more for fluent-bit. 
We are using GitLab ci/cd with container (windows vs 2019, debain11 ubuntu-20.04), so I'm not familiar with actions.
Buildsystem is Conan + CMake.

I´m going to check the whole Windows related stuff. Maybe I can help in other areas as well

**Comment by patrick-stephens** [comment]
@SteRoh shall we get this sorted next week? Be good to get it fixed

**Comment by SteRoh** [comment]
@patrick-stephens  Actually I'm not sure what to do :). #5011 needs code owner review.

As far es i know, CMake is not able to determine if a Option was set "from outside". Therfore it is hard to check if Windows options shall be overriden or not. 
We could think about an options which uses the windows defaults like: `-DFLB_WINDOWS_DEFAULTS=` 
At least advanced windows user can deactivate the include file than https://github.com/fluent/fluent-bit/blob/17d14e79f7885d3942188a5529786945123928a7/CMakeLists.txt#L299-L302

And which stuff is really required by windows?
https://github.com/fluent/fluent-bit/pull/5011#discussion_r823552544

**Comment by SteRoh** [comment]
i updated my PR:
https://github.com/fluent/fluent-bit/pull/5011/commits/7cdbf8c097f7789dcfe6489d75e1539f9bba085d

**Comment by patrick-stephens** [comment]
Closed as pr is merged.
