### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fluent/fluent-bit#50]
Would you like to add more error handling for return values from functions like the following?
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [flb_message](https://github.com/fluent/fluent-bit/blob/dcb4533bbd1ec6ab1f467d1c3fe7ac1e66f055ee/src/flb_utils.c#L123)
- [signal](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "Signal management") ⇒ [flb_signal_init](https://github.com/fluent/fluent-bit/blob/f7a92376c356d8a28a3273c4a2ac01ec8386a954/src/fluent-bit.c#L113)

**Comment by edsiper** [comment]
which specific call you see it needs a specific validation ?, in flb_message it's unlikely something may fail, worse case string output is truncated. 

In the flb_signal_init, the only error possible is "EINVAL signum is invalid", since we are passing POSIX values I don't see how it could fail.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by edsiper** [comment]
I agree on that, but looking at the current flb_message() it's a function that will not affect any further call after it's used.

For static code analysis we are using Coverity, it have been very helpful.

https://scan.coverity.com/projects/fluent-bit

**Comment by elfring** [comment]
* Do you care for a file output failure?
* I suggest to let such calls acknowledge explicitly that the desired function succeeded.

**Comment by edsiper** [comment]
current functions in question does not require the check of return values. For other cases I totally agree. At the moment Fluent Bit does not write content to the file system. 

Closing this issue as the described functions in case of fail, will not affect the program workflow.
