### ISSUE TITLE
multiline cri parser fails to parse timestamp

### ISSUE THREAD

**Issue by wengyao04** [fluent/fluent-bit#5010]
## Bug Report

**Describe the bug**

Hi, we use builtin multiline parser cri in our tail plugin like
```
input.conf: |
    [INPUT]
      Name             tail
      Tag              kube.*
      Path             /var/log/containers/*.log
      multiline.parser cri
      DB               /var/log/flb_kube.db
      Mem_Buf_Limit    5MB
      Skip_Long_Lines  On
      Refresh_Interval 10
```
But we see error in 
```
{"stream":"stderr","log":"[2022/03/07 18:30:02] [ warn] [parser:_ml_cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2022-03-07T18:29:56.454636802Z'"}
```
Not quite sure what `2022-03-07T18:29:56.454636802Z` is invalid time format.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by wengyao04** [comment]
Hi Do we have a timeline for https://github.com/fluent/fluent-bit/pull/5078 ? Is it ready to be merged and create a new release ? Thanks !!

**Comment by wengyao04** [comment]
Or do we have any temporary solution for parsing cri multiline log ?

**Comment by Antiarchitect** [comment]
Experiencing the same problem. New release with #5078 is desirable.
