### ISSUE TITLE
tail.0 paused (mem buf overlimit) with Mem_Buf_Limit setup

### ISSUE THREAD

**Issue by wengyao04** [fluent/fluent-bit#5014]
## Bug Report

**Describe the bug**

Hi, we are using fluent-bit to convert containerD log and see some warning in fluent-bit log like the following. Tail pauses and then resumes to consume tail record. 

We see recommendation from https://github.com/fluent/fluent-bit/issues/1768#issuecomment-564680740 and the issue is from back pressure. Therefore we override `Mem_Buf_Limit    5MB` in tail plugin, I can increase the limit. But I am wondering where this `128` comes from as we already set limit to `5MB` ? 

```
{"log":"[2022/03/07 19:16:19] [ warn] [input] tail.0 paused (mem buf overlimit)\n","stream":"stderr","time":"2022-03-07T19:16:19.284109089Z"}
{"log":"[2022/03/07 19:16:19] [ info] [input] tail.0 resume (storage buf overlimit 145/128)\n","stream":"stderr","time":"2022-03-07T19:16:19.286714328Z"}
```

```
input.conf: |
    [INPUT]
      Name             tail
      Tag              kube.*
      Path             /var/log/containers/*.log
      multiline.parser cri
      DB               /var/log/flb_kube.db
      Mem_Buf_Limit    5MB
      Skip_Long_Lines  On
      Refresh_Interval 10
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
It's the storage chunk limit:
`{"log":"[2022/03/07 19:16:19] [ info] [input] tail.0 resume (storage buf overlimit 145/128)\n","stream":"stderr","time":"2022-03-07T19:16:19.286714328Z"}`

See https://docs.fluentbit.io/manual/concepts/buffering but you can have in-memory and on-disk buffering.

Full details are here: https://docs.fluentbit.io/manual/administration/buffering-and-storage:
```
By default, the engine allows to have 128 Chunks up in memory in total (considering all Chunks), this value is controlled by service property storage.max_chunks_up. The active Chunks that are up are ready for delivery and the ones that still are receiving records. Any other remaining Chunk is in a down state, which means that's only in the filesystem and won't be up in memory unless is ready to be delivered.
```

I'm going to close as I think this is more a question and configuration change. Feel free to re-open or create a more specific issue with any problems you see.
