### ISSUE TITLE
Loki plugin not connecting to grafana cloud

### ISSUE THREAD

**Issue by smitsr72** [fluent/fluent-bit#5016]
## Bug Report

**Describe the bug**
Grafana cloud requires the following URL: https://logs-prod-us-central1.grafana.net:443/loki/api/v1/push.
Not possible to configure that in the loki plugin.

**To Reproduce**

[OUTPUT]
    name        loki
    match       *
    host        https://logs-prod-us-central1.grafana.net/loki/api/v1/push
    port        443

produces: 
[2022/03/08 07:36:06] [debug] [upstream] connection #-1 failed to https://logs-prod-us-central1.grafana.net/loki/api/v1/push:443

**Expected behavior**
https://logs-prod-us-central1.grafana.net:443/loki/api/v1/push

**Your Environment**
* Version used: Fluent Bit v1.8.11
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Windows
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
I just did this https://github.com/calyptia/openshift-fluent-bit-examples/blob/main/grafana-cloud/values-grafana-cloud.yaml

Works fine for me.

**Comment by smitsr72** [comment]
In your example the URL is "hostname=logs-prod-eu-west-0.grafana.net:443"
Advice from Grafana support is to put /loki/api/v1/push behind it.

I also tried your example, 
[OUTPUT]
    name        loki
    match       *
    host        logs-prod-us-central1.grafana.net
    port        443
    http_user   xxxxx
    http_passwd xxxx
    tls         on

but then I get this

**[2022/03/08 13:25:44] [ info] [output:loki:loki.2] configured, hostname=logs-prod-us-central1.grafana.net:443**
[2022/03/08 13:25:44] [debug] [router] match rule tail.0:stdout.0
[2022/03/08 13:25:44] [debug] [router] match rule tail.0:file.1
[2022/03/08 13:25:44] [debug] [router] match rule tail.0:loki.2
[2022/03/08 13:25:44] [ info] [sp] stream processor started
002-2021-12-18-22-00.log promote to TAIL_EVENT
[2022/03/08 13:25:49] [debug] [task] created task=000002C063AE00E0 id=0 OK
[2022/03/08 13:25:49] [debug] [out coro] cb_destroy coro_id=0
[2022/03/08 13:25:49] [debug] [out coro] cb_destroy coro_id=0
**[2022/03/08 13:25:49] [debug] [upstream] connection #868 failed to logs-prod-us-central1.grafana.net:443
[2022/03/08 13:25:49] [error] [output:loki:loki.2] no upstream connections available**
[2

**Comment by patrick-stephens** [comment]
Yes, the Loki plugin does that for you and it was working fine for me with that configuration.

**Comment by agup006** [comment]
I can also confirm I've been able to send data to Grafana Cloud Loki. config and guidance in the following blog: https://calyptia.com/2021/08/11/use-fluent-bit-to-send-logs-and-metrics-to-grafana-cloud/

**Comment by smitsr72** [comment]
In what direction should I look then for the "[2022/03/08 13:25:49] [error] [output:loki:loki.2] no upstream connections available" error message?

**Comment by patrick-stephens** [comment]
> Can you confirm you can actually connect to the explicit URL you need from wherever you are running, i.e. it is not a networking issue?

I would confirm your particular node can connect to the appropriate URL first.
