### ISSUE TITLE
Grep filter not accepting Regex that works in Rubular

### ISSUE THREAD

**Issue by StevenACoffman** [fluent/fluent-bit#502]
We use fluent-bit in kubernetes and wish to omit unstructured logs. 

I have a regular expression [that works in rubular here](http://rubular.com/r/6V0CRVwjKt). 
However, when I run it with fluent-bit (0.13-dev branch) I get:

```
[2018/02/04 17:36:40] [error] [filter_grep]: Failed to compile regex: Invalid regular expression
```

This is the configuration I am using:
```
[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name                grep
    Match               kube.*
    Regex               log ^[^\{]*(\{.*\})[^\s]*$
```

**Comment by edsiper** [comment]
@StevenACoffman 

I've found that the old filter_grep implementation uses common regex.h implementation instead of onigmo as all other components of Fluent Bit.

**Comment by edsiper** [comment]
Fixed by 7759ecd1b011383ad30005c0c68c07cdf48e7446

**Comment by StevenACoffman** [comment]
Thanks!
> filter_grep: use internal regex engine instead of regex.h (#502)

> the old implementaion of filter_grep uses the system regex.h
> engine instead of libonigmo which is the default solution.
> 
> This patch deprecate the usage of regex.h.
> 
> note: this plugin should behave as Fluentd grep plugin, it needs
> to be fixed to work with rules in 'pipe' mode instead of a simple
> ACL.

What does ACL mean compared to pipe?

**Comment by edsiper** [comment]
ACL (like access control list) works like first match = accept or reject right away, In "pipe mode" means that the records must match each regex defined and do not match the excludes (e.g: cat a.log | grep aa | ,,,)
