### ISSUE TITLE
Implement follow inodes to avoid duplicated records after logs rotation

### ISSUE THREAD

**Issue by latuszek** [fluent/fluent-bit#5024]
**Is your feature request related to a problem? Please describe.**
A problem: Fluent Bit is working on a node tailing docker containers logs. The logs are configured to rotate every 1 minute or every 10 MB (whichever is first), and unfortunately, the config is hard to change as it will require a change in hundreds of apps. Assume Fluent Bit crash for more than a minute in which time log file has been rotated (maybe even a couple of times). I couldn't find a way to configure Fluent Bit so it is not missing log entries or not producing duplicates.

**Describe the solution you'd like**
Having the same config property as in Fluentd would be helpful: [follow_inodes](https://docs.fluentd.org/input/tail#follow_inodes).

**Describe alternatives you've considered**
I don't know any in the Fluent Bit. Fluend may be considered as a replacement.

**Comment by latuszek** [comment]
Will you consider implementing such a flag or do you recommend a switch to the fluentd?

**Comment by latuszek** [comment]
The issue is still important to us.

**Comment by latuszek** [comment]
Bump.

**Comment by xplg** [comment]
@latuszek did you find a solution for this?
Having same issue exactly and really don't want to switch hundreds of servers to Fluentd...

**Comment by latuszek** [comment]
Nope. We plan to change our config not to rotate the files each minute. However, it will be a long process as we have hundreds of apps across different teams. It would be good to have some other solution in the meantime.

Our current workaround is to have some directory where we can place log files manually, so in case we are missing some logs we can repopulate them on demand just by copying the files.

**Comment by xplg** [comment]
Thanks Adam. Pretty annoying but that’s life ha.
I am trying to resolve it differently, our software is the part the receives the logs so I am trying to build a mechanism where only the online log is processed and available for the users, and any data that arrives from a log which complies with a rotated log will be archived and not used.
Hope it will work.

Take care.


[signature_4049413642]
Omry Koschitzky

IL +972 54 5500235<tel:+97237942255>
US +1 516<tel:+972522926055> 340 3094
***@***.******@***.***>
https://xplg.com<https://xplg.com/>

**Comment by latuszek** [comment]
I would still like to see it resolved.

**Comment by latuszek** [comment]
Don't close it please.

**Comment by latuszek** [comment]
Are there any future plans for this?

**Comment by kffallis** [comment]
Team, can we reconsider opening this issue?  It seems like is a simple one liner.  People dont want to have custom spins, they want it out of the box
