### ISSUE TITLE
[Feature] Allow for Kubernetes Filter to Use Alternative Directory

### ISSUE THREAD

**Issue by ayenter** [fluent/fluent-bit#503]
#### My Issue
My container puts custom logs in a different directory on the node. Tailing the logs in this directory causes the Kubernetes Filter to be unable to gather the metadata. I used the same naming convention as the logs in the containers directory, but the filter is currently specific to `/var/logs/containers/*.log`.

#### Feature Request
Change the Kubernetes filter to ignore the location of the logs.

**Comment by edsiper** [comment]
@ayenter 

I've extended filter_kubernetes configuration to allow to specify an alternative regex parser so when processing log files from a different location, you can get the metadata. 

Now in the filter kubernetes configuration append a "regex_parser  PARSER_NAME", where PARSER_NAME is an existing/registered parser from your parsers.conf file, e.g:

https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf#L81

on that example you can use 'kube-custom', also you can tweak the regex according to the path of your log files as required.

The changes are available on GIT Master (upcoming 0.13 release).

**Comment by edsiper** [comment]
FYI: you can experiment the latest change on this dev image:

https://github.com/fluent/fluent-bit-kubernetes-logging/tree/0.13-dev

**Comment by ayenter** [comment]
@edsiper Thank you immensely! This works perfectly!
