### ISSUE TITLE
Invalid UTF-8 bytes causes the remaining of the log message to be stripped away

### ISSUE THREAD

**Issue by juliohm1978** [fluent/fluent-bit#5035]
## Bug Report

As some developers prefer to use Windows, more often than not, source code ends up commited with [CP-1252 encoding](https://en.wikipedia.org/wiki/Windows-1252). Since most linux installations use UTF-8 as a default, conflicts with character encoding sometimes are inevitable. Log messages wtih accented characters is one common example. Unfortunately, we are unable to control or enforce which encoding developers should use. Therefore, we end up with log messages like this:

```
Estagiário visualizou o processo
```

![image](https://user-images.githubusercontent.com/4145456/157575598-55d149f7-dfa3-463f-8e1f-321f6adaed38.png)

Most applications processing that content will simply replace the character `á` for a symbol, like `�`. In general, that is acceptable.

Fluent-bit, however, seems to run a loop to decode UTF-8 characters ([seems to be here](https://github.com/fluent/fluent-bit/blob/6af60e6d75d3196d67cb041fc51dff14a9dd4da7/src/flb_sds.c#L376)), and when it finds an invalid character, the loop breaks, effectively ignoring all other characters in the log message.

In the above example, fluent-bit logs show this error message:

```
[2022/03/10 02:09:50] [ warn] [pack] invalid UTF-8 bytes, skipping
```

And the resulting log message is stripped down to:

```
Estagi
```

An expected output would be:

```
Estagi�rio visualizou o processo
```

## How to reproduce

[fluentbit.zip](https://github.com/fluent/fluent-bit/files/8219811/fluentbit.zip)

A reproducible use case with docker-compose is attached. A dummy netcat container simulates a receiving endpoint and fluent-bit will display the error while trying to parse the log message. A standard `docker-compose up` should be able to run this locally. Watch the netcat container for the output:

```
{"version":"1.1", "short_message":"Estagi", "timestamp":1646879559.374}
```

## Notes

Please, note that the issue is not easily reproducible with the Dummy input or the Stdout output. The failing code at `flb_sds.c` seems to be only triggered when certain Outputs are used, ie: gelf. The attached log example can be easily changed by an unsuspecting text editor by saving the file back with another encoding, causing it not to reproduce the scenario.

## Expected result

The log message should not be stripped. Invalid characters should be replaced with either a standard � or some user configurable value, preserving the rest of the message that still contains valid utf-8 character sequences.

**Comment by patrick-stephens** [comment]
Thanks for the report, do you have a PR that fixes it?

**Comment by wangjiqing** [comment]
We also encountered this problem, which resulted in incorrect log collection. It is unclear whether the problem is log encoding or other problems

**Comment by grandstairs** [comment]
Also encountering this issue using AWS cloud. Unsure what is the issue is as running the official docker hub image against the client works fine: https://hub.docker.com/r/fluent/fluent-bit
