### ISSUE TITLE
Stackdriver Output Plugin doesn't support EKS nodes.

### ISSUE THREAD

**Issue by HarleyB123** [fluent/fluent-bit#5038]
## Bug Report

When using the`k8s_node` type in the Stackdriver Output plugin, EKS nodes recieve an `error parsing local_resource_id`. This is because an EKS node is in the format `ip-0-0-0-0.region.compute.internal`, with the additional dots being interpolated as the format - making it invalid for the k8s_node type.

**Comment by patrick-stephens** [comment]
Any chance of a PR to resolve it?

**Comment by JeffLuoo** [comment]
You can use fluent-bit's filter plugin to add an entry:
```
logging.googleapis.com/local_resource_id k8s_node.<replace with your node name>
```

and the error `error parsing local_resource_id` will be gone for the node logs collected.

**Comment by HarleyB123** [comment]
Thanks @JeffLuoo 

This error occurs when I am using the filter plugin in such a way (using an init-container to get the correct node name for each daemonset like so):

```
initContainers:
- name: init-myservice
   image: busybox:1.28
   command:
     - sh
     - -c
     - |
       cp /fluent-bit/etc/* /config/
       cd /config
       cat << EOF >>filter-system.conf
       [FILTER]
           Name              record_modifier
            Match_Regex       \b(?!\bkube\b)\w+\b
            Record logging.googleapis.com/local_resource_id k8s_node.${NODE_ID//./-}
       EOF
   env:
     - name: NODE_ID
        valueFrom:
           fieldRef:
              fieldPath: spec.nodeName
```

**Comment by JeffLuoo** [comment]
Oops. I should really finish the doc early : )

Please take a look of my pending docs: https://github.com/fluent/fluent-bit-docs/pull/542

**Comment by HarleyB123** [comment]
Ah I see, good to know!
