### ISSUE TITLE
hello, I  need help!

### ISSUE THREAD

**Issue by ffcczz** [fluent/fluent-bit#504]
hello,     I want to ask you a question.I have three hosts:host1,host2,host3. There are log files on host1  and host2.I want to know how do I merge log files from host1 and host2 to host3 via fluent bit.  Thank you!

**Comment by edsiper** [comment]
please do not post in two channels.

Already replied in the mailing list: https://groups.google.com/forum/#!topic/fluent-bit/7tkurKrUY-w
