### ISSUE TITLE
syslog structured data broken in fluentbit 1.8

### ISSUE THREAD

**Issue by matthewjchou** [fluent/fluent-bit#5053]
## Bug Report

After running a record through multiple parsers to get a structured log message, attempting to output to a remote syslog server results in meta data and an empty log.

I can send a single field by specifying the ```syslog_message_key``` and because an entry is created on the syslog side, I know for sure I'm reaching the server.

This is what I get on stdout after it goes through all the filters and a nest operation. I also pipe it through ```jq```.
```
[OUTPUT]
    name stdout
    match syslog.tag
    format json_lines
```
- Example log message:
```
{
  "date": 1646974911.537643,
  "nested": {
    "level": "info",
    "ts": "2022-03-11T05:01:51.537Z",
    "caller": "xxxxxxx",
    "msg": "xxxxxxxx",
    "service": "unknownPod",
    "pod": "unknownPod-1",
    "hostname": "xxxxxxxxx",
    "TxId": "xxxxxxxxx"
  },
  "nodename": "xxxxxxxxx",
  "appname": "xxxx"
}
```

This is the result on the syslog side:
```
Mar 11 05:01:51 xxxxxxx xxxx:
```
- Steps to reproduce the problem:

**Expected behavior**
the fields in the record should show up on the syslog server

**Your Environment**

* Version used: 1.8
* Filters and plugins:
```
[OUTPUT]
    name syslog
    match syslog.tag
    host xxxx
    port xxx
    mode tcp
    syslog_format rfc3164
    syslog_hostname_key nodename
    syslog_appname_key appname
    syslog_sd_key nested
    syslog_message_key nested
```
I know the ```syslog_message_key``` won't work on the nested data here, but ```syslog_sd_key``` should be set right - it's basically identical to the fluentbit syslog output docs.

**Comment by patrick-stephens** [comment]
Any chance you can provide a reproducer using a dummy input or similar? 

Also, I'm not sure I follow the last bit about failing keys. Does it work if you modify those? 
Does the actual example in the docs work? If so, what is the delta that breaks it?
