### ISSUE TITLE
Missing tooling in fluentbit-debug container

### ISSUE THREAD

**Issue by TheSilentRinger** [fluent/fluent-bit#5074]
## Bug Report

It was suggested I create an issue to add missing tooling to fluentbit-debug on this issue: https://github.com/fluent/fluent-bit/issues/4986 @patrick-stephens 

I was trying to use the image on kubernetes and run netstat -tulpn to check out some ports, but when running netstat, it doesn't exist, so when I try to run apt update or apt-get to grab netstat, it doesn't have permissions, so then you try to use sudo, and sudo doesn't exist :(

To repro:
Get into fluentbit-debug container
Try to run netstat and see it doesn't exist
Run an apt update or apt-get to get netstat, but get permission denied
try to use sudo, sudo doesn't exist

* Version used: 1.8.12
* Configuration: fluentbit-debug 
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes
* Operating System and version: Linux

**Comment by patrick-stephens** [comment]
I'm a little confused about the original reason why you cannot install it as there should be no reason for that: we install packages during the build process fine and I've just tested as well with 1.9.0-debug as well as 1.8.12-debug:
```
$ docker run --rm -it fluent/fluent-bit:1.8.12-debug sh
# apt-get update
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]       
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [121 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
Fetched 8506 kB in 7s (1159 kB/s)                                                                                                                              
Reading package lists... Done
# apt-get install net-tools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 250 kB of archives.
After this operation, 1015 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 net-tools amd64 1.60+git20181103.0eebece-1 [250 kB]
Fetched 250 kB in 3s (77.4 kB/s) 
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package net-tools.
(Reading database ... 14650 files and directories currently installed.)
Preparing to unpack .../net-tools_1.60+git20181103.0eebece-1_amd64.deb ...
Unpacking net-tools (1.60+git20181103.0eebece-1) ...
Setting up net-tools (1.60+git20181103.0eebece-1) ...
# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
```

However I agree that netstat and some of the other tools are very useful so worth adding.

**Comment by TheSilentRinger** [comment]
@patrick-stephens still seeing this issue on v 1.9.0-debug?
![image](https://user-images.githubusercontent.com/19805418/160011896-41ef272b-aa5d-4889-bc3b-ad45d85acacc.png)
![image](https://user-images.githubusercontent.com/19805418/160012295-19bdba08-b22f-4003-98ad-50bc6d126c15.png)

**Comment by TheSilentRinger** [comment]
@patrick-stephens To confirm, I'm using Kubernetes, have a fluentbit container running the docker image fluent/fluent-bit 1.9.0-debug

run a kubectl exec -it <pod-name> -c fluentbit --sh (or bash) and try to run apt-get update, sudo, etc.. and just keep hitting walls

**Comment by patrick-stephens** [comment]
Not sure why, do you have a security context or similar setting the user it is run as? 

What if you just run the debug container locally?

**Comment by TheSilentRinger** [comment]
Hmmm, here is out container security set up:

```
containerSecurityContext:
      enabled: true
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        drop: ['ALL']
```

**Comment by TheSilentRinger** [comment]
it does work locally though if i just run in PowerShell

![image](https://user-images.githubusercontent.com/19805418/160030823-7891728f-3e18-4af1-98e1-de8ea74e8dc5.png)

**Comment by TheSilentRinger** [comment]
ahhhh, i found it. another security context was overwriting it, sorry for taking your time, thank you for your help and fast responses. cheers!
