### ISSUE TITLE
Create json schema for yaml configuration

### ISSUE THREAD

**Issue by lecaros** [fluent/fluent-bit#5083]
**Is your feature request related to a problem? Please describe.**
IDEs can use JSON schemas to help users define their YAML configurations through completion.

**Describe the solution you'd like**
To have a JSON schema available either through public repo or published in https://www.schemastore.org.

**Comment by niedbalski** [comment]
@patrick-stephens please lets add the fluent-bit -J output to the nightly/unstable + released artefacts.

**Comment by patrick-stephens** [comment]
In progress, should be ready once the automation is running correctly.

**Comment by patrick-stephens** [comment]
This should be present in the release jobs now. It'll be in the S3 bucket @niedbalski but we could also copy to the packages server, although I'd say let's align with #5098 and stop duplicating things.

Re-open if you want it elsewhere.

**Comment by ffflabs** [comment]
> Manually deployed here:
> 
> * https://releases.fluentbit.io/1.9/fluent-bit-schema.json

@patrick-stephens I used that schema to infer a json-schema compliant with draft 7. I believe schemastore would ask for that format.

**Comment by patrick-stephens** [comment]
@ffflabs just checking that is a good thing right or do we need to do something else? Sorry, I'm not really an expert on schema store so just checking if there is more stuff that needs doing.

**Comment by henrysachs** [comment]
i couldn't find schemas for the latest releases. Did I miss something or did this get lost?

**Comment by patrick-stephens** [comment]
They should be around somewhere but it has been a while - they're just generated from the build anyway via the `-J` parameter, e.g. `docker run --rm -it fluent/fluent-bit -J`

**Comment by patrick-stephens** [comment]
It is being generated: https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/.github/workflows/call-build-images.yaml#L179

We then push it to the bucket: https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/.github/workflows/staging-build.yaml#L111
That does ignore errors - older builds cannot support it.

I cannot see any specific filtering of it: https://github.com/fluent/fluent-bit/blob/5686334b56ee9d92f0654b0a621113943b175b94/.github/workflows/staging-release.yaml#L388

My guess is some of the refactoring we have had to do elsewhere may have affected it.

**Comment by henrysachs** [comment]
Okay thanks a lot for digging into this!

**Comment by henrysachs** [comment]
I'm not that deep into json schemas, but this version seems like a version of json schema other tools won't understand. How is this schema generated?

**Comment by patrick-stephens** [comment]
I would raise a separate issue for problems with it @henrysachs. I don't really know how it is generated other than we invoke the `-J` option. No one else will see these comments so asking it here is probably not best!

**Comment by henrysachs** [comment]
okay owm :)

**Comment by JustinGrote** [comment]
I generated a schema here since @ffflabs is 404'd
https://github.com/fluent/fluent-bit/issues/9289#issuecomment-2316416611
