### ISSUE TITLE
Syslog input plugin parser does not properly map severity and facility

### ISSUE THREAD

**Issue by idimou** [fluent/fluent-bit#5088]
**Is your feature request related to a problem? Please describe.**
When using the syslog input plugin the corresponding RFC5424 parser extracts the priority in the "pri" field. This however is not recognized by downstream systems such as Loki and Grafana to properly visualize the event's severity. Based on [RFC5424](https://datatracker.ietf.org/doc/html/rfc5424#page-191) the priority is a composite number made of the severity and facility numbers. Without these classifying and filtering events on severity is very much hindered.

**Describe the solution you'd like**
I would be really useful if the fluent-bit syslog input plugin could extract and calculate the severity and facility from a syslog RFC5424 event.

**Describe alternatives you've considered**
I've tried defining a custom parser for that, but since regex can only do field mapping and not the calculation needed to calculate severity from priority, we need it to be implemented inside fluent-bit itself.

**Additional context**
It doesn't allow me to classify events by severity and visualize them in Grafana explorer via Loki.

**Comment by idimou** [comment]
Can this be done with a Lua script filter?

**Comment by idimou** [comment]
OK Solved:
You need to add a filter in your fluent-bit.conf
```
[Filter]
	Name    lua
	Match   *
	script  pritolevel.lua
	call    pritolevel
```
and:
```
[OUTPUT]
	Name  loki
	match  *
	labels job=fluentbit, level=$level, host=$host
	host telemetry_loki
	port 3100
	line_format key_value
```


And put in the same folder the following pritolevel.lua scripti file:
```
function pritolevel(tag, timestamp, record)
    priority = tonumber(record["pri"]);

    facility = math.floor(priority / 8)
    severity = priority % 8
        
    if (severity == 0) then level =  "emerg" end
    if (severity == 1) then level =  "alert" end
    if (severity == 2) then level =  "critical" end
    if (severity == 3) then level =  "error" end
    if (severity == 4) then level =  "warning" end
    if (severity == 5) then level =  "notice" end
    if (severity == 6) then level =  "info" end
    if (severity == 7) then level =  "debug" end

    record["facility"]=tostring(facility)
    record["level"]= level
    return 2, timestamp, record
end
```
Loki can then pick up the "level" label and show nice colored event graphs in Grafana.

**Comment by JustinGrote** [comment]
@idimou great solution, I made an enhancement to use tables and then also pick up the facility.
```lua
function priToLevel(tag, timestamp, record)
    priority = tonumber(record["pri"]);

    facility = math.floor(priority / 8)
    severity = priority % 8

		local levelValues =
		{
			[0] = "emerg",
			[1] = "alert",
			[2] = "critical",
			[3] = "error",
			[4] = "warning",
			[5] = "notice",
			[6] = "info",
			[7] = "debug"
		}

		local facilityValues =
		{
			[0] = "kern",
			[1] = "user",
			[2] = "mail",
			[3] = "daemon",
			[4] = "auth",
			[5] = "syslog",
			[6] = "lpr",
			[7] = "news",
			[8] = "uucp",
			[9] = "cron",
			[10] = "authpriv",
			[11] = "ftp",
			[12] = "ntp",
			[13] = "security",
			[14] = "console",
			[15] = "solaris-cron",
			[16] = "local0",
			[17] = "local1",
			[18] = "local2",
			[19] = "local3",
			[20] = "local4",
			[21] = "local5",
			[22] = "local6",
			[23] = "local7"
		}

    record["level"]= levelValues[level]
		record["facility"]= facilityValues[facility]
    return 2, timestamp, record
end
```
