### ISSUE TITLE
Undefined Reference to __atomic_compare_exchange

### ISSUE THREAD

**Issue by flrkli** [fluent/fluent-bit#5089]
When building fluent bit from master (commit: cd92cf36099e69c09b0448e6bc0032bd4ac81ac5) on a fresh Raspbian bullseye lite with a RPI4, I get the following error

`
[ 87%] Linking C executable ../bin/fluent-bit
/usr/bin/ld: ../library/libcmetrics.a(cmt_atomic_gcc.c.o): in function `cmt_atomic_compare_exchange':
/home/pi/fluent-bit/lib/cmetrics/src/cmt_atomic_gcc.c:30: undefined reference to `__atomic_compare_exchange_8'
/usr/bin/ld: ../library/libcmetrics.a(cmt_atomic_gcc.c.o): in function `cmt_atomic_store':
/home/pi/fluent-bit/lib/cmetrics/src/cmt_atomic_gcc.c:36: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../library/libcmetrics.a(cmt_atomic_gcc.c.o): in function `cmt_atomic_load':
/home/pi/fluent-bit/lib/cmetrics/src/cmt_atomic_gcc.c:41: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:337: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:6768: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
`

I see in the CMakeList that the flag is set but still sems to be a problem:

`if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "armv7l")
  set(CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} -latomic")
  set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")
endif()
`
Any ideas here?

Thanks

**Comment by patrick-stephens** [comment]
The builds at the moment use a containerised approach so we can run them in CI: https://github.com/fluent/fluent-bit/blob/master/packaging/distros/raspbian/Dockerfile

Can you check what cmake options and libraries you're using against that? 
What is your full build config from scratch (including any package installation, etc.)?

**Comment by flrkli** [comment]
I verified it again on a fresh Raspbian Buster (32bit) and the same error comes again. I go with the default settings and just execute `cmake .. ` and `make` on master branch.
Interesting is that it runs without any problems on Raspbian buster and bullsyeye (64 bit)

**Comment by patrick-stephens** [comment]
Can you try it with the options here just in case it is CFlags or some other defaulted value? https://github.com/fluent/fluent-bit/blob/4653b3fab0979e37b37e34575dd1f1d600b13075/packaging/distros/raspbian/Dockerfile#L51-L61

**Comment by smartdings** [comment]
Thanks...I tried it with CFLAGS="-std=gnu99"  but still getting the same error.

**Comment by patrick-stephens** [comment]
Ok, I'm due to get some actual hardware so will test it once that arrives.

**Comment by patrick-stephens** [comment]
Submit a PR and we can get more people to look plus run it through CI. Fixes are good! 👍
