### ISSUE TITLE
Question: How to specify fluentbit version when installing via yum?

### ISSUE THREAD

**Issue by brycefisher** [fluent/fluent-bit#509]
I'm trying to make a quasi-reproducible build of my infrastructure and I plan to include fluentbit as a key piece of that infrastructure. I'm on CentOS and I've found the installation instructions to be very helpful.

However, I worry that the version of fluentbit installed on my system by [following the instructions](http://fluentbit.io/documentation/0.12/installation/redhat_centos.html) (today 0.12.) might change once version 0.13 or 1.0 is released.

My questions are:

 1. When using the CentOS / RHEL installation method, is it possible to ensure a specific version of fluentbit is installed?
 2. If not, is there a recommended way to install a specific version, particularly for a CentOS 7 machine?

Thanks so much for this amazing project!!

**Comment by edsiper** [comment]
@brycefisher 

I think that's a CentOS specific question ,but if I am not wrong you can do:

```
$ yum install td-agent-bit-0.12.14
```

Otherwise you can use a direct download link:

```
http://apt.fluentbit.io/centos/7/td-agent-bit-0.12.14-1.x86_64.rpm
```

**Comment by heyaWorld** [comment]
@edsiper Hey, what is the direct download link for ubuntu bionic? Is there a repo of direct download links for different flavors and version of Linux? Similar to how it is for fluentd: https://www.fluentd.org/download?

Thanks,

**Comment by heyaWorld** [comment]
We can use this in ubuntu to get the specific version of the package:

> apt-get --print-uris --yes install td-agent-bit | grep ^\' | cut -d\' -f2 >package.txt

For bionic: https://packages.fluentbit.io/ubuntu/bionic/pool/main/t/td-agent-bit/td-agent-bit_1.3.6_amd64.deb

**Comment by ndhcoder** [comment]
Can I download rpm file fluent bit 1.2 for Redhat 6 ? I can't find that link? Please help me. @edsiper

**Comment by tguenneguez** [comment]
Have you find a version off fluent bit for redhat 6 ?
