### ISSUE TITLE
GetTCP input processor

### ISSUE THREAD

**Issue by hafkaM** [fluent/fluent-bit#5093]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Connects over TCP to the provided endpoint(s). Received data will be written as content to the FlowFile

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Not sure I follow, can you clarify what is required as sounds like the TCP input plugin? 
https://docs.fluentbit.io/manual/pipeline/inputs/tcp

**Comment by hafkaM** [comment]
Thank you for answer.
I need to listen on a remote port. TCP in requires a local bind.
M.

Example:

[SERVICE]
    flush                     1
    Log_Level                 info
    coro_stack_size 65536
##  storage.metrics           off
#   Parsers_File              /fluent-bit/etc/parsers.conf
#   Streams_File              /fluent-bit/etc/stream_processing.conf

[INPUT]
    name   tcp
    tag    oss-hua
    listen 10.44.150.6          **#This is the IP address and port on the remote server**
    port   8765
    buffer_size 16000

[OUTPUT]
    Name        stdout
    Match       *

--------------------------------------------------------------
su_netdata@tnif06blade02:~/software$ docker-compose -f ./fb-oss-hua-in.yml up
Creating software_fb-oss-hua-in_1 ... done
Attaching to software_fb-oss-hua-in_1
fb-oss-hua-in_1  | Fluent Bit v1.8.13
fb-oss-hua-in_1  | * Copyright (C) 2015-2021 The Fluent Bit Authors
fb-oss-hua-in_1  | * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fb-oss-hua-in_1  | * https://fluentbit.io
fb-oss-hua-in_1  |
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [ info] [engine] started (pid=1)
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [ info] [storage] version=1.1.6, initializing...
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [ info] [storage] in-memory
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [ info] [cmetrics] version=0.2.2
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [error] Error binding socket
**fb-oss-hua-in_1  | [2022/03/18 12:34:45] [ warn] Cannot listen on 10.44.150.6 port 8765**
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [error] [input:tcp:tcp.0] could not bind address 10.44.150.6:8765. Aborting
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [error] Failed initialize input tcp.0
fb-oss-hua-in_1  | [2022/03/18 12:34:45] [error] [lib] backend failed
su_netdata@tnif06blade02:~/software$

**Comment by hafkaM** [comment]
Example - connect to remote TCP port via telnet and listen

su_netdata@tnif06blade02:~/software$ telnet 10.44.150.6 8765
Trying 10.44.150.6...
Connected to 10.44.150.6.
Escape character is '^]'.
<+++>
HandShake  =  2022-03-18 13:44:35
<--->
^]

**Comment by patrick-stephens** [comment]
It's probably easier to use a tunnel instead I imagine but I see what you're asking: essentially you want to intercept traffic to a remote server. 

Can you clarify the use case? 
Why can't you just send to the location of the Fluent Bit instance or use the remote server to forward it for you?

**Comment by hafkaM** [comment]
We have several applications that expose stream data on their TCP port (such as mobile network events). I process most of the streamed data using fluentbit / fluentd containers (normalization and kafka bus storage). Here I have to use Apache Nifi TCP get processor. Which destroys the homogeneity of tooling.
