### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [fluent/fluent-bit#51]
[The function "flb_debug"](https://github.com/fluent/fluent-bit/blob/fae8571a60441515e6b39bdab8eecd5769359392/include/fluent-bit/flb_utils.h#L34 "Formatted output") does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
How do you think about to delete its call from your function "[flb_signal_handler](https://github.com/fluent/fluent-bit/blob/f7a92376c356d8a28a3273c4a2ac01ec8386a954/src/fluent-bit.c#L98 "Check signal handling implementation")"?

**Comment by edsiper** [comment]
thanks.

**Comment by elfring** [comment]
The function "flb_engine_shutdown" is also async-signal-unsafe because the function "free" will be called.

Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")
