### ISSUE TITLE
Feature Request: port fluentd fluent-plugin-detect-exceptions 

### ISSUE THREAD

**Issue by StevenACoffman** [fluent/fluent-bit#510]
For java applications, the fluent-bit multiline parser is useful for keeping stack traces together.
However, for other languages, stack traces can be difficult to re-assemble after shipping. 

Currently, in fluentd the [fluentd plugin detect exceptions](https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions) detects the beginning of stack traces for many languages, and assembles multiple lines into a single message. It would be very helpful if similar functionality was possible in fluent-bit.

**Comment by robertrbruno** [comment]
Any chance of this one happening or should I explore if Fluentd meets my performance needs?

**Comment by StevenACoffman** [comment]
@robertrbruno This is a difficult issue to solve. I don't expect this to happen anytime soon.

**Comment by loburm** [comment]
Is there any chance to prioritize this effort? What is the biggest problem in implementing it? Do I understand correctly, that Fluent Bit can't merge multiple records in one plugin?

**Comment by loburm** [comment]
@edsiper any updates?

**Comment by edsiper** [comment]
(our new built-in parsers supports cri, docker, go, python, java)..

# Multiline Update

As part of Fluent Bit v1.8, we have released a new Multiline core functionality. This new big feature allows you to configure new `[MULTILINE_PARSER]`s that support multi formats/auto-detection, new multiline mode on Tail plugin, and also on v1.8.2 (to be released on July 20th, 2021) a new Multiline Filter. 

For now, you can take at the following documentation resources:

- [Multiline Parsers / Concepts and Configuration](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing)
- [Tail + New Multiline Core Feature](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support)
- [New Multiline Filter](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace)

Documentation pages now point to complete config examples that are available on our repository.

Thanks everyone for supporting this!
