### ISSUE TITLE
occasionally new inode is not detected during file rotation

### ISSUE THREAD

**Issue by jsammut1976** [fluent/fluent-bit#5114]
I'm using Fluent Bit 1.8.13 (latest) to forward k8s apiserver audit logs to Graylog.

The configuration is as follows:

```
    config:
      service: |
        [SERVICE]
          Flush 1
          Daemon Off
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          storage.path /flb-storage/
          storage.sync normal
          storage.checksum off
          storage.max_chunks_up 128
          storage.backlog.mem_limit 5M
          storage.metrics on
      inputs: |   
        [INPUT]
          Name tail
          Path /var/log/kube-apiserver/audit.log
          Parser json
          DB /var/log/flb_kubeapiserver.db
          DB.locking true
          Tag kubeapiserver.*
          Mem_Buf_Limit 25MB
          Buffer_Chunk_Size 256k
          Buffer_Max_Size 1M
          Skip_Long_Lines Off
          storage.type filesystem 
      filters: |
        [FILTER]
          Name modify
          Match kubeapiserver.*
          Add temp_key kubernetes_event
          Rename level event_level
        [FILTER]
          Name throttle
          Match *
          Rate 1250
          Window 100
          Interval 1s
          Print_Status true
      outputs: |
        [OUTPUT]
          Name gelf
          Match kubeapiserver.*
          Host <my-hostname>
          Port 12201
          Mode tcp
          Gelf_Host_Key stream
          Gelf_Short_Message_Key temp_key
          storage.total_limit_size 100M
```

The above works, however occasionally a fluentbit pod does not detect a new inode during the `audit.log` file rotation.  
I'm detecting this from the throttle logs reporting `current rate is: 0 per interval`.

During normal operation, I can follow this pattern in the logs when a file is rotated:

```
2022/03/18 12:48:42] [ info] [input:tail:tail.0] inode=1048679280 handle rotation(): /var/log/kube-apiserver/audit.log => /var/log/kube-apiserver/aud
it-2022-03-18T12-48-42.521.log
[2022/03/18 12:48:42] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1048679280 watch_fd=21
[2022/03/18 12:48:42] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1048679280 watch_fd=22 name=/var/log/kube-apiserver/audit-2022-03-18T12-48-4
2.521.log
[2022/03/18 12:48:42] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1048679284 watch_fd=23 name=/var/log/kube-apiserver/audit.log
[2022/03/18 12:48:47] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1048679280 watch_fd=22
```

Note that a new inode 1048679284 was successfully detected at time 12:48:42.  Some time later, the file was rotated again, this time undetected as follows:

```
[2022/03/18 12:53:28] [ info] [input:tail:tail.0] inode=1048679284 handle rotation(): /var/log/kube-apiserver/audit.log => /var/log/kube-apiserver/audit-2022-03-18T12-53-28.477.log
[2022/03/18 12:53:28] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1048679284 watch_fd=23
[2022/03/18 12:53:28] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1048679284 watch_fd=24 name=/var/log/kube-apiserver/audit-2022-03-18T12-53-28.477.log
[2022/03/18 12:53:37] [ info] [input:tail:tail.0] inotify_fs_remove(): inode=1048679284 watch_fd=24
```

Note that new inode is not detected at time 12:53:28.

Has anyone encountered this?  Any idea how to solve this issue?

**Comment by Jonomir** [comment]
I have the same problem, we lost a few hours of important logs.
I recently upgraded fluent-bit from 1.8.12 fo 1.8.13. I'll downgrade again hoping 1.8.12 does not have that problem.

**Comment by Jonomir** [comment]
There have been a bunch of changes in the file handling of the tail plugin between 1.8.12 and 1.8.13: https://github.com/fluent/fluent-bit/commit/c2519cbbbc168603dc30dc904ab8742b6c6e024e

**Comment by Jonomir** [comment]
Maybe already fixed in 1.8.14: https://github.com/fluent/fluent-bit/commit/de69a6a95969eb2a54ff2586931940d9039ee715
I'll try it out.

**Comment by lecaros** [comment]
Yeah, it's a good idea to test 1.8.14. We've shipped some fixes related to file handling between those versions. (1.8.15 was already released too)
Refresh_interval default is 60 (secs). You should expect to see the rotation handled within that time; I'm not sure if you waited for enough or checked the rest of the log file looking for the rotation. If you expect that file to be rotated more often, try setting the Refresh_interval to a lower value.

**Comment by jsammut1976** [comment]
We tried 1.8.14 and the issue seems to have been resolved.

Our file rotates typically every 7 minutes, so the default Refresh_interval default is 60 (secs) works fine.

**Comment by lecaros** [comment]
Good to know. I'll close this issue. If you see the issue again, please re-open this or open a new one.
