### ISSUE TITLE
td-agent-bit.service incorrectly reports success to systemd even if service fails

### ISSUE THREAD

**Issue by gitstashpop** [fluent/fluent-bit#5120]
## Bug Report

**Describe the bug**

The systemd service for fluent bit falsely reports a successful start up to systemd. Any number of things could cause this, but the easiest way to reproduce this is a bad configuration option.

**To Reproduce**
- Insert a bad configuration option to `td-agent-bit.conf` such as ```    syslog_format   rfc5424``` to `INPUT` for syslog.
- Start the systemd service
- If you check the status immediately, systemd reports the service succeeded
- If you check again in a few seconds, the service fails

Here is an example config:

```
[root@idz5upgn5fddzovma5emrv5eq4 centos]# cat /etc/td-agent-bit/td-agent-bit.conf
[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off


[INPUT]
    name            syslog
    path            /run/postgres-audit.socket
    tag             postgres
    syslog_format   rfc5424
```

Reproducible output:

```sh
[root@p7pr5sptqjg6naij2zi6ein4di centos]# systemctl start td-agent-bit ; systemctl status td-agent-bit; sleep 3; systemctl status td-agent-bit
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/td-agent-bit.service.d
           └─override.conf
   Active: active (running) since Fri 2022-03-18 19:04:27 UTC; 21ms ago
     Docs: https://docs.fluentbit.io/manual/
 Main PID: 4109 (td-agent-bit)
    Tasks: 1 (limit: 49859)
   Memory: 7.8M
   CGroup: /system.slice/td-agent-bit.service

Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di systemd[1]: Started TD Agent Bit.
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di td-agent-bit[4109]: Fluent Bit v1.9.0
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di td-agent-bit[4109]: * Copyright (C) 2015-2021 The Fluent Bit Authors
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di td-agent-bit[4109]: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di td-agent-bit[4109]: * https://fluentbit.io
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di td-agent-bit[4109]: [2022/03/18 19:04:27] [error] [lib] backend failed
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di td-agent-bit[4109]: [2022/03/18 19:04:27] [ info] [engine] started (pid=4109)
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Main process exited, code=exited, status=255/n/a
Mar 18 19:04:27 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Failed with result 'exit-code'.
● td-agent-bit.service - TD Agent Bit
   Loaded: loaded (/usr/lib/systemd/system/td-agent-bit.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/td-agent-bit.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Fri 2022-03-18 19:04:28 UTC; 1s ago
     Docs: https://docs.fluentbit.io/manual/
  Process: 4128 ExecStart=/opt/td-agent-bit/bin/td-agent-bit -c //etc/td-agent-bit/td-agent-bit.conf (code=exited, status=255)
 Main PID: 4128 (code=exited, status=255)

Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Main process exited, code=exited, status=255/n/a
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Failed with result 'exit-code'.
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Service RestartSec=100ms expired, scheduling restart.
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Scheduled restart job, restart counter is at 5.
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: Stopped TD Agent Bit.
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Start request repeated too quickly.
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: td-agent-bit.service: Failed with result 'exit-code'.
Mar 18 19:04:28 p7pr5sptqjg6naij2zi6ein4di systemd[1]: Failed to start TD Agent Bit.
```

**Expected behavior**
I expect the service file to use `type=notify` or `forking` in the systemd.service section. If `notify` is chosen, it require the td-agent-bit to use `sd_notify()` when started in daemon mode to indicate to systemd that the service started successfully. Additionally, the service file would need to be updated to start td-agent-bit in daemon mode.

Here is further [documentation](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) from systemd:

> It is generally recommended to use Type=simple for long-running services whenever possible, as it is the simplest and fastest option. However, as this service type won't propagate service start-up failures and doesn't allow ordering of other units against completion of initialization of the service (which for example is useful if clients need to connect to the service through some form of IPC, and the IPC channel is only established by the service itself — in contrast to doing this ahead of time through socket or bus activation or similar), it might not be sufficient for many cases. If so, notify or dbus (the latter only in case the service provides a D-Bus interface) are the preferred options as they allow service program code to precisely schedule when to consider the service started up successfully and when to proceed with follow-up units. The notify service type requires explicit support in the service codebase (as sd_notify() or an equivalent API needs to be invoked by the service at the appropriate time) — if it's not supported, then forking is an alternative: it supports the traditional UNIX service start-up protocol.
 
**Your Environment**

* Version used: v1.9.0
* Configuration: See above
* Operating System and version: Alma Linux 8.5

**Comment by patrick-stephens** [comment]
Yeah this should be sorted and sounds straightforward, do you have a PR we can merge?

**Comment by patrick-stephens** [comment]
Systemd only restarts 5 times (the default) I believe, not infinite - it's pointless if there is a config error to do so until you have fixed the config error.

This issue is not about restarting it, it was about reporting incorrectly that it was successful when it had failed. Are you saying the Fluent Bit process is failing but reporting as OK in systemd?
