### ISSUE TITLE
out_opensearch individual message error handling

### ISSUE THREAD

**Issue by ryn9** [fluent/fluent-bit#5121]
**Is your feature request related to a problem? Please describe.**

Trying to output to OpenSearch can fail for individual messages due to a number of issues.
Examples: 
bulk operations can fail for individual message due to permissions for an index
bulk operations can fail for individual message due to mapping errors
etc...

**Describe the solution you'd like**

provide a mechanism to handle individual message failures, provide context of the failure, and output via a fallback output

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by agup006** [comment]
I believe there is a need here of a general fallback output mechanism that we don't really have in Fluent Bit at the moment. Ideally, we would be able to customize particular error encounters to trigger that backup mechanism

**Comment by ryn9** [comment]
While some issues need to be ironed out - the logic written into the fluentd opensearch plugin would be a great place to start modeling this ...
https://github.com/fluent/fluent-plugin-opensearch/blob/main/lib/fluent/plugin/opensearch_error_handler.rb
