### ISSUE TITLE
how Send logs to Elasticsearch8.1

### ISSUE THREAD

**Issue by huweikkk** [fluent/fluent-bit#5138]
I`am install eck on my k8s,and run fluent-bit1.9,it run good on Elasticsearch7.x，But i`am update Elasticsearch8.1，it`s don`t send log to Elasticsearch8.1.this is info:
fluent-bit version: 1.9.0
Elasticsearch version :8.1

fluent-bit configmaps:

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-es
  namespace: monitor
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     20MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        Buffer_Size     False
        Trace_Error On
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        TLS             On
        TLS.verify      Off
        Suppress_Type_Name On

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

fluent-bit  daemonsets :
`
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit-es
  namespace: monitor
  labels:
    k8s-app: fluent-bit-logging
    version: v1beta1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
      version: v1beta1
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1beta1
        kubernetes.io/cluster-service: "true"
    spec:
      imagePullSecrets:
      - name: registry.dcdn.baidu.com.key
      containers:
      - name: fluent-bit
        image: hub.ote.baidu.com:8443/ote/fluent-bit:1.9.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2020        
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "v2x-es-http"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_USER
          value: "elastic"
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value: "UYKKH8ip1UI6"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: v2xapplog
          mountPath: /home/v2xapp/logs/
        - name: homedockerdatacontainers
          mountPath: /home/docker/data/containers
          readOnly: true
        - name: fluent-bit-config-es
          mountPath: /fluent-bit/etc/
          readOnly: true
      terminationGracePeriodSeconds: 5
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: v2xapplog
        hostPath:
          path: /home/v2xapp/logs/
      - name: homedockerdatacontainers
        hostPath:
          path: /home/docker/data/containers
      - name: fluent-bit-config-es
        configMap:
          name: fluent-bit-config-es
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
`

this is pod info
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/11644448/159234382-3ed3e30f-5f8a-4984-a0c4-7dd1774e61c3.png">

<img width="1768" alt="image" src="https://user-images.githubusercontent.com/11644448/159234438-8ac9fc04-5c2d-4c63-a851-6abe59c86f0c.png">

**Comment by patrick-stephens** [comment]
Please post logs as text rather than images.

I can send to Elasticsearch 8 (on Elastic Cloud) with this configuration: https://github.com/calyptia/openshift-fluent-bit-examples/blob/main/elastic-cloud/values-elastic-cloud.yaml

TLS is complaining a bit so are you sure that your certificates are valid?

**Comment by huweikkk** [comment]
I have see: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
Fluent Bit + Elastic Cloud Example configuration:
[OUTPUT]
    Name es
    Include_Tag_Key true
    Tag_Key tags
    tls On
    tls.verify Off
    cloud_id elastic-obs-deployment:ZXVybxxxxxxxxxxxg==
    cloud_auth elastic:2vxxxxxxxxYV

and this`s you Example configuration:
    [OUTPUT]
        name                es
        match               *
        tls                 On
        tls.verify          On
        Suppress_Type_Name  On
        Index               logs-fluent-bit
        Cloud_Auth          $ELASTIC_CLOUD_AUTH
        Cloud_ID            $ELASTIC_CLOUD_ID

I can refer to your configuration and test it again tomorrow.

**Comment by patrick-stephens** [comment]
Yeah my main point was I did not have to do anything for v8 of Elastic other than the `Suppress_Type_Name On` to get it to work. It looks more like a general comms issue just looking at your logs hence my query on whether your certificates are correct?

**Comment by huweikkk** [comment]
when I change my configmaps  as this ,it run good.

    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        TLS    Off
        TLS.verify Off
        Logstash_Format On
        Logstash_Prefix xxl-job-vehicle
        Retry_Limit     False
        Replace_Dots    On
        Suppress_Type_Name On

**Comment by patrick-stephens** [comment]
Disabling TLS then? Or something else? 

I don't think there is any inherent issue with the output, just configuration so I'll close but feel free to reopen.
