### ISSUE TITLE
out_kafka doesn't resume once saturated

### ISSUE THREAD

**Issue by homer6** [fluent/fluent-bit#514]
Hi Eduardo,

We’re having a bit of an issue with fluent-bit and I was wondering if you can help me overcome some of these challenges.

Right now, we have IN_TAIL to OUT_KAFKA, but we’re experiencing high memory usage and lockups when fluent-bit can’t flush to kafka. I would expect that fluent-bit would block until the data could be drained. But, it doesn’t drain (even if left for days). However, killing the process and running it again allows fluent-bit to start from the latest file offsets (because the offset is stored in the sqlite db) and no issues with saturating kafka exist, so it doesn’t lock up and can run for days as expected.

I would expect that:

1. When using IN_TAIL from a large file, reading from the file would block when the memory buffer is saturated. I believe that you said that fluent-bit does this. However, there’s a bit of a missed step in that, if the process dies or must be killed before flushing to its output, the messages in the buffer should not be lost. It appears that they are lost, though.
2. When the OUT_KAFKA channel is saturated, it should block and resume when not saturated. Right now, it appears that it does not resume.

Am I right to expect these two behaviors? If so, what can I do to contribute to a solution?

Thanks in advance,

Steve

**Comment by edsiper** [comment]
I will take a look. Would you please share your configuration file ?

**Comment by homer6** [comment]
I have something more to add to this. Fluent-bit was running for several days and was successfully tailing a large file (with the offset db turned on). When I killed the process and started it again immediately after, it still saturated the OUT_KAFKA channel and memory usage climbed to 256MB. Upon checking the logs, it reports that the attempt to resume was tried 10 times, then stopped. This lead me to believe that there is something else going on that I'm not understanding. Because, if it was working as I expected, it should resume from the near-tail offset and thus have not enough data to saturate kafka.

```
$ tail -f fluentbit.log
[2018/02/19 09:21:55] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:21:56] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:21:57] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:21:58] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:21:59] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:22:00] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:22:01] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:22:02] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:22:03] [ warn] [out_kafka] internal queue is full, retrying in one second
[2018/02/19 09:22:04] [ warn] [out_kafka] internal queue is full, retrying in one second
```

**Comment by homer6** [comment]
Config file (not the real paths):

```
[SERVICE]
    Flush          1
    Daemon         on
    Log_Level      info
    Log_File       /fluentbit.log
    Parsers_File   parsers.conf

[INPUT]
    Name              tail
    Path              /file-to-tail.log
    #Parser            json-test
    DB                /flb_file_offsets.db
    Mem_Buf_Limit     100MB
    Buffer_Chunk_Size 128k
    Buffer_Max_Size   4096k
    Refresh_Interval  5

[OUTPUT]
    Name           kafka
    Match          *
    Brokers        my.kafka.broker
    Port           9092
    Topics         my.logging.topic
    Timestamp_Key  @timestamp
    Retry_Limit    False
```

**Comment by edsiper** [comment]
thanks.

Note that Fluent Bit in_tail is trying to enqueue at maximum of 100MB and when the data is processed and ingested into the out_kafka, the kafka library have it own in-memory buffering mechanism, so it's expected you see a high memory usage like 256MB or a bit more until it can flush it.

Now there is another problem, if you enqueued 100MB of data in-memory, in_tail update the offset to that position and if you restart, it will resume from it latest offset, so likely these 100MB will be skipped if out_kafka did not flush the data. Since Fluent Bit allows to sends data to multiple destinations, it's not that easy to implement that on in_tail side. The solution is a stronger file-system buffering mechanism.

As a partial workaround, I would suggest you reduce your mem_buf_limit, also you can tweak out_kafka internals through rdkafka.* properties (e.g: rdkafka.queued.max.messages.kbytes) listed here:

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by homer6** [comment]
The main issue is that it doesn't resume once saturated. Doesn't `Retry_Limit False` mean that it will not give up on retrying? How do I stop fluent-bit from giving up after 10 seconds (10 retries)?

**Comment by edsiper** [comment]
out_kafka logic is like this: enqueue message into rdkafka, if the queue is full, try again to enqueue up to a maximum of 10 times. When the 10 times limit is reach, issue a Fluent Bit engine retry, which means, try again later in a couple of seconds. 

How are you realizing that Fluent Bit is not retrying after that ?

**Comment by homer6** [comment]
No more data is sent to kafka after this limit is hit. Also, I would expect that additional attempts would also result in more fluent-bit log entries noting the retry (which I don't see).

**Comment by edsiper** [comment]
actually the log entries for re-tries are only in debug mode, make sense to make them available in normal logging level.

**Comment by homer6** [comment]
Good to know. Will change that and see if I notice a difference.

**Comment by homer6** [comment]
Just to be clear, I'm still able to reproduce the issue with no new messages being sent to kafka after kafka saturation. The logging was just a signal that I expected to be there, but there is definitely still an issue with no new messages being sent.

**Comment by AkashKrDutta** [comment]
Is this issue resolved? I have fluent-bit not able to process logs after this warning is hit. Similar config. Version used - 0.13.4

**Comment by Charles-WYC** [comment]
Same Problem. And for more detail, out_kafka is keeping retry, but queue is always full.
and after a long term of retry, it raise error as follow:
```
[error] [out_kafka] fluent-bit#producer-1: [thrd:kafka1:9092/1]: kafka1:9092/1: Receive failed: Disconnected
...
[error] [out_kafka] fluent-bit#producer-1: [thrd:kafka1:9092/bootstrap]: kafka1:9092/bootstrap: Receive failed: Disconnected
```
Waiting for solution

**Comment by Charles-WYC** [comment]
Bug discovered! @edsiper 
For the problem described above, I find it is a bug in out_kafka plugin.
in `kafka.c : produce_message`there is a logic as follow:
```
    if (ret == -1) {
        fprintf(stderr,
                "%% Failed to produce to topic %s: %s\n",
                rd_kafka_topic_name(topic->tp),
                rd_kafka_err2str(rd_kafka_last_error()));

        if (rd_kafka_last_error() == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
            flb_warn("[out_kafka] internal queue is full, "
                     "retrying in one second");

            ctx->blocked = FLB_TRUE;

            flb_time_sleep(1000, config);

            queue_full_retries++;
            goto retry;
        }
    }
    else {
        flb_debug("[out_kafka] enqueued message (%zd bytes) for topic '%s'",
                  out_size, rd_kafka_topic_name(topic->tp));
    }
    ctx->blocked = FLB_FALSE;

    rd_kafka_poll(ctx->producer, 0);
    if (ctx->format == FLB_KAFKA_FMT_JSON) {
        flb_free(out_buf);
    }

    msgpack_sbuffer_destroy(&mp_sbuf);
    return FLB_OK;
```
there is a problem that, once we get a QUEUE_FULL error, we will never call `rd_kafka_poll` to update rdkafka's queue's status, the queue's status keep full. that's why once a message failed, the following retry will all failed.
so I recommend we can add a line `rd_kafka_poll(ctx->producer, 0);` after `flb_time_sleep(1000, config);`, as follow:
```
        if (rd_kafka_last_error() == RD_KAFKA_RESP_ERR__QUEUE_FULL) {
            flb_warn("[out_kafka] internal queue is full, "
                     "retrying in one second");

            ctx->blocked = FLB_TRUE;

            flb_time_sleep(1000, config);
            rd_kafka_poll(ctx->producer, 0);

            queue_full_retries++;
            goto retry;
        }
```
We have finished the test to the new code, and it works well.
pull request: https://github.com/fluent/fluent-bit/pull/923
If you want to reappear this problem you can set `rdkafka.queue.buffering.max.messages` to a small value like 10000
