### ISSUE TITLE
Memory leak in kubernetes filter plugin when using K8S-Logging.Exclude: On in fluent-bit version 1.9.0 and 1.8

### ISSUE THREAD

**Issue by KrishnaKant1509** [fluent/fluent-bit#5147]
## Bug Report

**Describe the bug**

There is a memory leak in kubernetes filter when using ```K8S-Logging.Exclude On``` to block logs from pods.

**To Reproduce**
Run fluent-bit version 1.9.0, 1.8.13, 1.8.12 or 1.8.4 with the kubernetes filter using ```K8S-Logging.Exclude On``` and some pods annotated with ```fluentbit.io/exclude: "true"```

**Current behavior**

when the K8S-Logging.Exclude option is turned On, memory leakage occurs. It remains constant when the option is turned Off. 

**Expected behavior**

Memory usage stays constant with constant load.

**Screenshots**

<img width="1772" alt="Screenshot 2022-03-22 at 7 51 01 AM" src="https://user-images.githubusercontent.com/61928269/159402317-39246873-52d4-47c9-b613-af806044d0b9.png">
The memory usage start increasing with K8S-Logging.Exclude option turned On. It remains constant when it is turned Off.

**Your Environment**

* Version used: fluent-bit v1.9.0, v1.8.13, v1.8.12, v1.8.4
* Configuration: A simpler version of the configuration we used will include a ```systemd input plugin```, ```kubernetes filter plugin``` and ```forward output plugin```.
<img width="403" alt="Screenshot 2022-03-22 at 10 02 03 AM" src="https://user-images.githubusercontent.com/61928269/159409617-1afb1316-5b84-4841-8a10-35660e09abbf.png">

* Running on Kubernetes v1.21 on top of linux/amd64 in a single node cluster.

**Additional context**

similar issue https://github.com/fluent/fluent-bit/issues/1068 for reference.

**Comment by danielserrao** [comment]
In my case I'm getting this issue when using the Kubernetes filter, with "K8S-Logging.Exclude Off" and with "K8S-Logging.Exclude On".

I tested this with versions: 

- 1.7.7
- 1.7.9
- 1.8.11 (Our current version)
- 1.8.12
- 1.8.14
- 1.9.0 (Latest)
- 1.9.0-debug

My config is the following config:

`data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level debug
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 3000
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 200MB
        DB /var/log/fluentbit_tail.db
        DB.locking  true
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off
        tls.debug 4

    [OUTPUT]
        Name loki
        Match kube.*
        Host loki-distributed-distributor.monitoring.svc.cluster.local
        Labels job=fbit_k8s, $kubernetes['pod_name'], $kubernetes['namespace_name'], $kubernetes['container_name']
        auto_kubernetes_labels on`

I'm deploying fluentbit as DaemonSet on a K8s cluster with 4 nodes and with the config above, the memory of fluentbit pods increases forever until it crashes in 2 nodes but not in the other 2.

If I switch from debug to info mode, the memory increases way slower but still increases forever.

If I remove the Filter and switch from debug to info mode, then the memory becomes stable in all nodes.

When looking for filter logs in the fluentbit pod where I get the most memory increasing, I see the following log:

```
[2022/03/23 16:43:42] [debug] [filter:kubernetes:kubernetes.0] Send out request to API Server for pods information
[2022/03/23 16:43:42] [debug] [filter:kubernetes:kubernetes.0] Request (ns=kube-system, pod=kube-proxy-9glsb) http_do=0, HTTP Status: 200
```

Any idea on how this can be fixed?

**Comment by danielserrao** [comment]
When changing to debug mode I don't see any errors or warnings. I only see a debug message that could be related which is the following:

`[debug] [input:tail:tail.0] scan_blog add(): dismissed: /var/log/containers/velero-57975cd8c-whpf6_velero_velero-plugin-for-aws-a8bb9ec020f448819747b0b837e76bbcd40f3ad858b7842c97d7983b444442a3.log, inode 923404`

I already increased the ingesters limits on Loki.

I also added the following on the tail input plugin:

```
Buffer_Chunk_Size 100MB
Buffer_Max_Size 200MB
Refresh_Interval 100
```

Also added "Buffer_Size 100MB" in the K8s Filter plugin.

None of the above solved the issue.

**Comment by edsiper** [comment]
FYI:

https://github.com/fluent/fluent-bit/pull/5179

this fix is for the journal mode use case

**Comment by ozhankaraman** [comment]
this is an blocker issue for using fluent-bit on K8s environments

**Comment by edsiper** [comment]
I am reopening this issue to validate the last status.

@patrick-stephens can you pls re-evaluate this ? (is the leak happening with latest 1.9 version ?)

**Comment by patrick-stephens** [comment]
OK I will have a look shortly

**Comment by patrick-stephens** [comment]
I've knocked up a simple test script with KIND using the helm charts to try to reproduce it but not seeing it there: the pods stay at around 10Mi for me locally.

https://gist.github.com/patrick-stephens/05d0fab2dd2567df394246cb25c43253

In this case it is using the default Helm chart inputs (tail and systemd) with the configuration for the service and K8S filter shown above (debug level logging and using exclude off). I have got Loki deployed but am using the null output as Loki backs up too much locally - this issue though is around the K8S filter and not Loki output I believe.

```shell
$ kubectl describe -n fluentbit cm/fluent-bit
Name:         fluent-bit
Namespace:    fluentbit
Labels:       app.kubernetes.io/instance=fluent-bit
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=fluent-bit
              app.kubernetes.io/version=1.9.9
              helm.sh/chart=fluent-bit-0.20.9
Annotations:  meta.helm.sh/release-name: fluent-bit
              meta.helm.sh/release-namespace: fluentbit

Data
====
custom_parsers.conf:
----
[PARSER]
    Name docker_no_time
    Format json
    Time_Keep Off
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L

fluent-bit.conf:
----
[SERVICE]
    Flush 1
    Daemon Off
    Log_Level debug
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Log_Level debug
    Health_Check On

[INPUT]
    Name tail
    Path /var/log/containers/*.log
    multiline.parser docker, cri
    Tag kube.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[INPUT]
    Name systemd
    Tag host.*
    Systemd_Filter _SYSTEMD_UNIT=kubelet.service
    Read_From_Tail On

[FILTER]
    Name kubernetes
    Match kube.*
    Merge_Log On
    Keep_Log Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude Off
    tls.debug 4

[OUTPUT]
    Name        null
    Match       *

#[OUTPUT]
#    Name        loki
#    Match       *
#    Host        loki
#    Labels job=fbit_k8s, $kubernetes['pod_name'], $kubernetes['namespace_name'], $kubernetes['container_name']
#    auto_kubernetes_labels on


BinaryData
====

Events:  <none>
```

I've deployed metrics server along with Prometheus and just using `kubectl top pods -n fluentbit` to check the pod usage.

We can probably look to deploy at scale in a cloud platform although it would be useful to know which one and/or use Grafana Cloud too to verify.

**Comment by patrick-stephens** [comment]
With [revision 2](https://gist.github.com/patrick-stephens/05d0fab2dd2567df394246cb25c43253/acf167ea8a554edc4dc1282fa77d437a76b7aba5), I've tweaked things to follow the original issue to use journaling and exclude being on.
I'm also excluding both the FB and metrics server pods but not the others (Prometheus, Loki, Grafana and kube-system ones).

I cannot see any memory usage increase using `kubectl top pods -n fluentbit` locally at least.

```shell
$ kubectl describe -n fluentbit cm/fluent-bit
Name:         fluent-bit
Namespace:    fluentbit
Labels:       app.kubernetes.io/instance=fluent-bit
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=fluent-bit
              app.kubernetes.io/version=1.9.9
              helm.sh/chart=fluent-bit-0.20.9
Annotations:  meta.helm.sh/release-name: fluent-bit
              meta.helm.sh/release-namespace: fluentbit

Data
====
custom_parsers.conf:
----
[PARSER]
    Name docker_no_time
    Format json
    Time_Keep Off
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L

fluent-bit.conf:
----
[SERVICE]
    Flush 1
    Daemon Off
    Log_Level debug
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Log_Level debug
    Health_Check On

[INPUT]
    Name tail
    Path /var/log/containers/*.log
    multiline.parser docker, cri
    Tag kube.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[INPUT]
    Name systemd
    Tag host.*
    Systemd_Filter _SYSTEMD_UNIT=kubelet.service
    Read_From_Tail On

[FILTER]
    Name kubernetes
    Match kube.*
    Use_journal On
    K8S-Logging.Exclude On

[OUTPUT]
    Name        null
    Match       *

#[OUTPUT]
#    Name        loki
#    Match       *
#    Host        loki
#    Labels job=fbit_k8s, $kubernetes['pod_name'], $kubernetes['namespace_name'], $kubernetes['container_name']
#    auto_kubernetes_labels on


BinaryData
====

```

**Comment by patrick-stephens** [comment]
I notice in both cases above, the memory buffer limit is ~256Mb which is a lot more than the defaults (which I was using of ~5Mb) - the pod resource limits need to also allow this along with memory available on the nodes themselves to prevent OOM kills or eviction. We could do with checking K8S events and a full pod spec around this if we can reproduce it.

**Comment by JasperWey** [comment]
Has anyone update? I met this issue with version 2.0.9.
```
[root@localhost test]# kubectl top pod -n xdr
NAME                                     CPU(cores)   MEMORY(bytes)
fluent-bit-847xk                         3m           2547Mi
gateway-nginx-5bcd645967-5r6pm           0m           341Mi
```

the config as follow:
```
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=k3s.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name file
        Match *
        Format plain
        Path /logStorage

```
