### ISSUE TITLE
Does not tail the logs on windows kubernetes node

### ISSUE THREAD

**Issue by vakkursw** [fluent/fluent-bit#5157]
## Bug Report

**Describe the bug**
I am running fluent-bit on a windows node in an EKS cluster, the fluent-bit tails the var/log/containers and reports 0 new log files.
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2022/03/22 19:06:14] [debug] [input:tail:tail.0] 0 new files found on path 'C:\\var\\log\\containers\\*.log'
```

**Screenshots**
![2022-03-22_14-57-43](https://user-images.githubusercontent.com/95715828/159566140-945ffc42-57ac-4157-9904-8236f38444f3.png)
![2022-03-22_14-58-24](https://user-images.githubusercontent.com/95715828/159566169-d0822629-3c3b-4e4f-bc3c-f5c00b04f667.png)

**Your Environment**

* Version used: 1.8.10
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): 1.21
* Server type and version: Windows
* Operating System and version:
* Filters and plugins:
[SERVICE]
    Flush         5
    Log_Level     debug
    Daemon        off
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              C:\\var\\log\\containers\\*.log
    Parser            docker
    DB                C:\\var\\log\\flb_kube1.db
    Skip_Long_Lines   On
    Refresh_Interval  60

[OUTPUT]
    Name             http
    Match            *

**Comment by patrick-stephens** [comment]
Have you checked the permissions match the container user? It may be that from the perspective of that user there are no files (it has permission to see or read).
