### ISSUE TITLE
fluentbit could not open configuration file. aborting

### ISSUE THREAD

**Issue by jangid21** [fluent/fluent-bit#5163]
I am trying to launch the fluentbit as a sidecar.I am trying to deploy on Eks cluster using Harness. I am using Splunk for showing logs. I have checked the configuration from the official site but still getting this error. What could be the reason for it?

Error: Could not open configuration file. Aborting
I dont know if there is something that needs to be modified in the config file also.

**Comment by jangid21** [comment]
Hi this is the config file I am using.

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  ## https://docs.fluentbit.io/manual/pipeline/parsers
  custom_parsers.conf: |
    ## required for parsing multi-line log messages
    [PARSER]
        Name   service_line_beginning
        Format regex
        Regex  ^(?<event>\[\d{4}.*)

  fluent-bit.conf: |
    ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file#config_section
    [SERVICE]
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/custom_parsers.conf
        HTTP_Server On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    [INPUT]
        Name             tail
    	Alias            logfiles
    	Path             *.log
    	Path_Key         source
    	DB               fluent-bit.db
    	DB.locking       true
    	Refresh_Interval 20
    	Rotate_Wait      60
    	Multiline        On
        Parser_Firstline service_line_beginning

 

    [FILTER]
        Name nest
        Match *
        Operation nest
        Wildcard fields.*
        Nest_under fields
        Remove_prefix fields.

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    [OUTPUT]
        Name  splunk
        Match *

        Host  splunkcloud.com
    	uri  /services/collector/event
        Port 443
        tls  On

        header Authorization    ${SPLUNK_TOKEN}
        Splunk_Send_Raw On

**Comment by jangid21** [comment]
annotations:
        sidecar.istio.io/inject: "true"
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      containers:

      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.12.0
        ports:
        - name: http-fluent
          containerPort: 2021
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http-fluent
        readinessProbe:
          httpGet:
            path: /
            port: http-fluent
        volumeMounts:
        - name: logs
          mountPath: /logs
        - name: fluentbit-config
          mountPath: /fluent-bit/etc
       
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

**Comment by patrick-stephens** [comment]
It's hard to tell from the limited information here, but I think the issue is you're mounting the config map over the whole `/fluent-bit/etc` directory and you have no definition for `parsers.conf` so it is missing.

Yes, it may be in the container image but you're overwriting the whole directory so it is removed. You should mount sub paths for specific files or duplicate the file in your config.
