### ISSUE TITLE
Fluent-Bit fails to (re)start if too many buffers have been accumulated on the filesystem storage

### ISSUE THREAD

**Issue by simbou2000** [fluent/fluent-bit#5166]
## Bug Report

**Describe the bug**
When using the filesystem storage and have Fluent-Bit accumulate a lot of files (ie.: output down) until thousands of files have been created, Fluent-Bit will be unable to restart/start correctly and will constantly loop with errors. This can increase the issue because a feedback loop of writing to the journal and reading from it will make both td-agent-bit and the journal services use a lot of cpu usage.

This seems related to the number of handles Fluent-Bit has opened:
```
lsof -p `pidof td-agent-bit` | wc -l
2041
```

Been looking at the code and seems like the function cb_queue_chunks in plugins/in_storage_backlog/sb.c is trying to load all of the chunks that are on the disk into memory.
Some of the issues I found when Fluent-Bit tries to load buffers from the filesystem:
* "ctx->mem_limit" is set to FLB_STORAGE_BL_MEM_LIMIT if "storage.backlog.mem_limit" is not set and becomes 100MB by default when the documentation (https://docs.fluentbit.io/manual/administration/buffering-and-storage) indicates 5MB.
* The inner loop in the function cb_queue_chunks never stops if the "total" goes over the ctx->mem_limit threshold.
* When modifying the loop to break when "total >= ctx->mem_limit" is reached, the function cb_queue_chunks will be called every second, but "flb_input_chunk_total_size(in)" will always return "0" even if the previously loaded chunks have never been processed. Loading another batch of 100MB of buffers each time for example. This could lead to a situation where either the ram will be completely used or the limit of handles it can use will be reached if too many buffers have been accumulated.
* Calling "cio_chunk_down(chunk_instance->chunk);" before "sb_remove_chunk_from_segregated_backlogs(chunk_instance->chunk, ctx);" ([Code](https://github.com/fluent/fluent-bit/blob/9c2868fc841e1f0d9e0fd96a4bd8da164741906c/plugins/in_storage_backlog/sb.c#L570)) to close the handles make it possible to go through all the buffers, but I noticed a lot of timers have been created by "_mk_event_timeout_create" until this function also gave errors because it created too many. Fluent-Bit did manage to eventually recover with a lot of errors, but I did not inspect that part too much to understand what it does.

**To Reproduce**
Using a configuration that writes buffers to the filesystem, force Fluent-Bit to accumulate a lot of buffers by having the output down or pointing to an invalid address.

Example of bash script used to write to the journal, called multiple times as a background process with a different parameter to simulate logs from different applications which the INPUT will split into different buffers, easily increasing the number of buffers created:
```
#!/bin/bash
while true
do
    echo "$1 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." | systemd-cat -t $1 -p warning
done
```

Once a lot of buffers have been accumulated (ie.: ~2000 in my case), restart rd-agent-bit service and during the start up, it will register/queue all the buffers until it fails to load any more buffer and keep on looping indefinitely.

```
[...]
[error] [storage] cannot open/create /var/log/fluent/buf//systemd.0/1131418-1647664248.725660271.flb
[error] [storage] [cio file] cannot open chunk: systemd.0/1131418-1647664248.725660271.flb
[error] [storage] cannot open/create /var/log/fluent/buf//systemd.0/1131418-1647664248.725660271.flb
[error] [storage] [cio file] cannot open chunk: systemd.0/1131418-1647664248.725660271.flb
[lib/chunkio/src/cio_file.c:432 errno=24] Too many open files
[lib/chunkio/src/cio_file.c:432 errno=24] Too many open files
[error] [storage] cannot open/create /var/log/fluent/buf//systemd.0/1131418-1647664248.725660271.flb
[error] [storage] [cio file] cannot open chunk: systemd.0/1131418-1647664248.725660271.flb
[error] [storage] cannot open/create /var/log/fluent/buf//systemd.0/1131418-1647664248.725660271.flb
[...]
```

**Expected behavior**
Fluent-Bit should only load as many buffers the storage.max_chunks_up or memory constraints have been configured, then load more when it is possible to do so.

**Your Environment**
* Version used: td-agent-bit 1.8.12
* Configuration:
```
[SERVICE]
    # Flush records to destinations every 5s
    Flush        5

    # Run in foreground mode
    Daemon       Off

    # Use 'info' verbosity for Fluent Bit logs
    Log_Level    info

    # Standard parsers & plugins
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # Enable built-in HTTP server for metrics
    # Prometheus metrics: <host>:24231/api/v1/metrics/prometheus
    HTTP_Server  On
    HTTP_Listen  192.168.128.2
    HTTP_Port    24231

    # Persistent storage path for buffering
    storage.path /var/log/fluent/buf/
    storage.max_chunks_up 128

[INPUT]
    Name systemd
    Tag  system.journal.*
    Path /var/log/journal
    DB   /var/log/fluent/journald-cursor.db
    storage.type  filesystem
    mem_buf_limit 64M

# BEGIN Elasticsearch output
[OUTPUT] # elasticsearch destination 1
    Name  es
    Match *
    Retry_Limit False

    Host 192.168.128.200
    Port 9200
    Index filebeat-7.2.0
    tls Off
    tls.verify On
    # elasticsearch output HTTP_User placeholder
    # elasticsearch output HTTP_Passwd placeholder

    Type  _doc
    Generate_ID true

# END Elasticsearch output
```
* Environment name and version (e.g. Kubernetes? What version?): td-agent-bit service 1.8.12
* Operating System and version: AlmaLinux 8

**Additional context**
This could happen in a situation where we update/restart systems or if a crash occurred when a lot of buffers have been accumulated.

**Comment by simbou2000** [comment]
About the patch I did in the fourth point to prevent keeping all chunks up and have issues with memory/handles when a large number of buffers have been accumulated on the filesystem, here is the change I did:
https://github.com/simbou2000/fluent-bit/commit/304282baa6580ca4cbeab04d7b4fb7c29f6f05c2

Every chunk from the filesystem will still be all be queued up due to the other issues I described, but at least they will be put down until they are eventually processed, freeing both memory and the file handles.

I did get a lot of errors related to unable to create timers when there's a lot of buffers, but it did manage to eventually recover when the output was available.

**Comment by simbou2000** [comment]
I've updated to Fluent-Bit version 1.9.3 and had the same behavior as initially described.

There's currently no way of limiting how much memory to use when Fluent-Bit restarts with a lot of chunks on the filesystem storage. 
It will try to load everything into memory upon starting which can lead to out-of-memory issues and crash.

I've noticed when poking at "/api/v1/storage", it mentions a storage backlog mem_limit of "0b" and this value doesn't seem to be configurable at this time and doesn't seem to be used to limit the number of chunks read from the filesystem upon starting.
ie.:
```
    "storage_backlog.2": {
      "status": {
        "overlimit": false,
        "mem_size": "0b",
        "mem_limit": "0b"
      },
```

When this scenario happens, Fluent-Bit keeps on crashing unless the chunks on the filesystem are deleted or have a limit of chunks to be saved to the disk being less than the memory available.

**Comment by lecaros** [comment]
Hi @simbou2000,
Have you tested this using the latest version in 1.8 or 1.9?
Are you using the same config you posted here?

We've done testing using about 50k chunk files pending at the start time of Fluent-Bit with no issues. This was after we introduced the ```static_batch_size``` config parameter in the Tail plugin. This parameter limits the amount of data to be processed from static files before start sending them to the output. Its default value is 50M, but you can try lower values to fit your particular case.
IRT ```Too many open files``` it will depend on your O.S. configured limits. Our recommendation would be to increase such value to fit your need.

If you still see this issue using the latest version, please provide your config (if different from the one posted here) and Fluent-Bit's log file for further analysis.

**Comment by simbou2000** [comment]
Hi @lecaros,
This was tested with both 1.8 and 1.9.

The issue is not just how many chunks but also the size of these chunks that were already present upon start of Fluent-Bit when using filesystem storage.

What I saw when debugging with gdb is that the function loading these chunks from the disk were checking if it was still under a memory limit, but the calculation of memory used so far was always returning zero. So it was loading all chunks into memory and this becomes an issue when you have hundreds of megabytes to gigabytes of accumulated buffer.

**Comment by acastong** [comment]
This is a critical bug that prevents using filesystem buffering under high load. It needs to remain open.

**Comment by lecaros** [comment]
hello,
>If you still see this issue using the latest version, please provide your config (if different from the one posted here) and Fluent-Bit's log file for further analysis.

If you have a repro, please share it with us (along with the corresponding log files) and we'll take a look.

**Comment by simbou2000** [comment]
Hi again,

I retested with both td-agent-bit 1.9.10 and fluent-bit 2.0.8 with the same result as previously described.

**Configuration files**
```
### parsers.conf ###
[PARSER]
    Name   syslog-custom
    Format regex
    Regex ^(?<eventoriginal>(?<time>(\D{1,}\s\d{1,}\s\d{1,}\:\d{1,}\:\d{1,}\s))(?<systemname>(\S+)) (?<appname>(\S+))\[(?<pid>(\d+))\]:(?<loglevel>([a-zA-Z]*)) (?<message>(.*)))?$
    Time_Key time
    Time_Format %B %d %H:%M:%S
```
```
### td-agent-bit.conf ###
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  On
    HTTP_Listen  192.168.128.2
    HTTP_Port    24231
    storage.path /var/log/fluent/buf/
    storage.max_chunks_up     128
    storage.backlog.mem_limit 64M

[INPUT]
    name                tail
    path                /logs/*
    path_key            log.file.path
    exclude_path        *.gz,*.zip
    db                  /var/log/fluent/fluenttest.db
    parser              syslog-custom
    tag                 system.logs.<filename>
    tag_regex           \/(?<path1>(.*))\/(?<filename>(.*))$
    storage.type        filesystem
    read_from_head      true
    Offset_Key          source.bytes
    refresh_interval    5
    Buffer_Chunk_Size   64KB
    Buffer_Max_Size     1MB
    Mem_Buf_Limit       8MB
    Key                 message

[OUTPUT]
    Name syslog
    Match       system.*
    Retry_Limit False
    Host      <syslog server>  # Replace with a syslog server address
    Port 514
    Mode tcp

    Syslog_Severity_Key log.syslog.severity.code
    Syslog_Facility_Key log.syslog.facility.code
    Syslog_Hostname_Key host.name
    Syslog_AppName_Key  process.name
    Syslog_ProcID_Key   process.pid
    Syslog_Message_Key  message
    Syslog_SD_Key       labels

    storage.total_limit_size  460M
```

**Script files**
Requires a testdata file in the same folder for what is the string to log into the log files, I had about 700 bytes line of text in mine.
Path for the logs are /logs/*, but this can be changed in startlogging.sh

startlogging.sh:
```
#!/bin/bash
echo "Number of instances: $1"
START=1
END=$1

for (( i=$START; i<=$END; i++ ))
do
  ./logging.sh "/logs/test$i.log" "./testdata" "Script$i" &
done

echo "Done!"
```

logging.sh:
```
#!/bin/bash
echo "File path: $1"
echo "Input file: $2"
echo "Instance name: $3"
COUNTER=0
TESTDATA=$(cat $2)

while true; do
  let COUNTER++
  echo "$(date -u +"%b %d %H:%M:%S") $3 MainLoop[1]:INFO Line $COUNTER $TESTDATA" >> "$1"
  sleep 0.1
done
```

killlogging.sh:
```
#!/bin/bash
pkill -9 -f logging.sh
```

**To reproduce**
While I use a syslog OUTPUT, it should be working the same with any OUTPUT, we just need one you can shutdown/stop working midway to increase the logs generated on the filesystem.
In my case, I have a syslog server running on another machine.

Start Fluent-Bit and then start the scripts with a dummy testdata file in the same folder that is the data to write to the log files and the number of files to write to, ie.:
```
# ./startlogging.sh 50
```

Stop/shutdown the syslog server to force Fluent-Bit to accumulate logs.
Monitor the storage.path to check when it reach the limit:
```
# du -h /var/log/fluent/buf/
443M    /var/log/fluent/buf/tail.0
443M    /var/log/fluent/buf/
```

Fluent-Bit Dump information at that time:
```
[2023/03/07 20:48:29] Fluent Bit Dump
===== Input =====
tail.0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 3.4M (3575946 bytes)
│     └─ mem limit  : 7.6M (8000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 2048
│  ├─ new           : 0
│  ├─ running       : 2048
│  └─ size          : 434.1M (455195998 bytes)
│
└─ chunks
   └─ total chunks  : 2095
      ├─ up chunks  : 47
      ├─ down chunks: 2048
      └─ busy chunks: 2048
         ├─ size    : 0b (0 bytes)
         └─ size err: 0
storage_backlog.1 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0
===== Storage Layer =====
total chunks     : 2095
├─ mem chunks    : 0
└─ fs chunks     : 2095
   ├─ up         : 47
   └─ down       : 2048
```

Number of handles being used by Fluent-Bit:
```
# lsof -p `pidof td-agent-bit` | wc -l
318
```

Then kill the Fluent-Bit process:
```
kill -9 `pidof td-agent-bit`
```

Once restarting Fluent-Bit, it will try to load all chunks that were written to the disk into memory all at once and either go over the memory limits specified or open too many handles (About 1024 per process in my case).

```
# lsof -p `pidof td-agent-bit` | wc -l
1986
```

Since Fluent-Bit has reached the limit, it will go into an infinite loop of errors trying to open more files:
```
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [2023/03/07 20:55:28] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [2023/03/07 20:55:28] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [2023/03/07 20:55:29] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [2023/03/07 20:55:29] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [2023/03/07 20:55:29] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [2023/03/07 20:55:29] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [2023/03/07 20:55:29] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [build/lib/chunkio/src/CMakeFiles/chunkio-static.dir/compiler_depend.ts:410 errno=24] Too many open files
td-agent-bit[2820389]: [2023/03/07 20:55:29] [error] [storage] [cio file] cannot open chunk: tail.0/1509102-1678221676.65975298.flb
```
This will not stop and even if the syslog server is running, Fluent-Bit will not try sending any data and be stuck in an error loop. The only way to fix would be to stop Fluent-Bit again, delete all accumulated buffers and restart.

This is not okay since we would not want to lose any records and the filesystem storage was chosen to store records we can't push to a logging server in case of a temporary problem and able to stream once it can.

From my previous investigation, the problem seem to occur inside the function cb_queue_chunks where it load each file to check if it is valid and never close them, increasing the number of handles and memory usage. The loop should also be respecting the memory constraint, but doesn't.
While increasing the number of handles could allow to go past the above error, Fluent-Bit may exceed the memory usage and crash the process or evict the container it is running in.

A local patch I made was to close the chunks after the check was done to close the handle and had no issue with it, but I think there should be a better solution to prevent this problem to occur.

**Comment by lecaros** [comment]
Hi,
I'm seeing the `Too many open files` error message there.
What's your ulimit configuration?
`ulimit -a`

**Comment by simbou2000** [comment]
Hi,

```
# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 14758
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2048
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by lecaros** [comment]
There you go. The `open files` setting is too low to handle that load. Please change it to a higher number or unlimited. You'll usually have to change such configuration when running applications in prod.

We've pointed out this before in https://github.com/fluent/fluent-bit/issues/5166#issuecomment-1219577963

**Comment by simbou2000** [comment]
Hi,
As I also mentioned, even if I increase the number of handles a process is allowed to open, they will all be loaded into memory, so instead of having an infinite loop of errors, I will get a hard crash from running out of memory or container being evicted from using too much memory.
This seem to go beyond the number of chunks to be loaded into memory and does not respect memory usage.

Backpressure is supposed to load a certain amount of chunks over time in a normal operation, but this does not happen at all when a restart of Fluent-Bit occur.

This makes using filesystem unusable if a crash/reset/upgrade occurs with a lot of chunks onto the filesystem due to backpressure. It would be fine if it was a small amount, but having the possibility to have gigabytes in backpressure with a restart of Fluent-Bit will just make it impossible to continue without losing any record.

**Comment by simbou2000** [comment]
Ran the test with unlimited handles to fill up 2GB of filesystem and created about 2629 files in the storage filesystem.
Fluent-Bit memory usage when reaching 2GB on the filesystem: 251,556K

I killed Fluent-Bit and restarted it.

Fluent-Bit memory usage peaked at 1,166,940K during the restart of the process.
The dump information:
```
[2023/03/09 20:56:16] Fluent Bit Dump

===== Input =====
tail.0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 7.6M (8000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0

storage_backlog.1 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 2048
│  ├─ new           : 0
│  ├─ running       : 2048
│  └─ size          : 1.0G (1095156604 bytes)
│
└─ chunks
   └─ total chunks  : 2624
      ├─ up chunks  : 576
      ├─ down chunks: 2048
      └─ busy chunks: 2048
         ├─ size    : 0b (0 bytes)
         └─ size err: 0


===== Storage Layer =====
total chunks     : 2624
├─ mem chunks    : 0
└─ fs chunks     : 2624
   ├─ up         : 576
   └─ down       : 2048
```

This shows it has 576 up chunks when the limit in the config was 128 and there is no way to limit memory usage which is now more than 4 times what it used prior to the restart and there's no logs being processed by the INPUT yet.

**Comment by lecaros** [comment]
Hi @simbou2000,
Thanks for further testing this.
I've been able to reproduce part of this: chunks up are beyond the limit set. However, Fluent Bit keeps working, and the chunks are delivered once the output endpoint goes up. 

In your case, isn't Fluent Bit processing any more records or not sending them to the output endpoint?
Can you please share the Fluent Bit's log?

Note: I've added `retry false` so we don't _lose_ chunks because of the retries.

**Comment by simbou2000** [comment]
Hi @lecaros 

In my last test, I did not write any logs to have an idea of how much memory it could use, I know I had cases where it went more than the 1GB of memory usage, but looking at the code loading the chunks at the start, it appears the check for memory usage is not working as intended.

Also, there were no errors in the logs beside the syslog server being intentionally down.

**Comment by lecaros** [comment]
From the code, it seems it's not honoring the `max_chunks_up` setting while loading backlog from the storage, aka chunk files. As for the memory check, I saw that it's keeping it under the configured value. Keep in mind that you have `storage.backlog.mem_limit` which will only limit the memory used by chunks from the backlog, and `Mem_Buf_Limit       8MB` which will limit the Tail plugin only.
This ticket was initially opened to deal with Fluent Bit not (re)starting, but we can see that it's coming up if proper ulimit settings are in place.
We could open a new ticket to deal with the max_chunks_up and other for the memory (if you want further discussion on that). You're most welcome to do so, and I'll take it from there.

**Comment by simbou2000** [comment]
I agree it is starting in an environment with more memory available, but it is not respecting max_chunks_up, which is also related to the large number of handles being opened. This also cause using more memory usage too.
It seems that setting ulimit -n unlimited is more like a band-aid that will cause using more memory, causing containers to be evicted from it.

**Comment by Minaly212** [comment]
@simbou2000 @lecaros 
Any solution for this issue?
