### ISSUE TITLE
Support for json arrays

### ISSUE THREAD

**Issue by apratina** [fluent/fluent-bit#5167]
**Is your feature request related to a problem? Please describe.**
We are trying to build json payload that can be sent to http server. We wanted to understand if there is a way to add JSON array to one of the fields.

Here is our sample /fluent-bit-mount/test.log file:

```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request"}
```

Here is our sample fluent-bit.conf file:

```
[INPUT]
    Name            tail
    Path            /fluent-bit-mount/test.log
    Parser          docker
[OUTPUT]
    Name                stdout
    Match               *
    Format              json
    json_date_key       false
[FILTER]
    Name            modify
    Match           *
    Add             time    2022-03-20T20:10:35.266+0000 
    Add             project foo
    Add             environment  stage
[FILTER]
    Name            nest
    Match           *
    Operation       nest
    Wildcard        kind
    Wildcard        apiVersion
    Wildcard        level
    Nest_under      data
[FILTER]
    Name            nest
    Match           *
    Operation       nest
    Wildcard        time
    Wildcard        project
    Wildcard        environment
    Wildcard        data*
    Nest_under      events
```

Here is the output of above configuration:

```
{
	"events": {
		"time": "2022-03-20T20:10:35.266+0000",
		"project": "foo",
		"environment": "stage",
		"data": {
			"kind": "Event",
			"apiVersion": "audit.k8s.io/v1",
			"level": "Request"
		}
	}
}
```

But I am interested in something like this. Note: events is a JSON array.

```
{
	"events": [{
		"time": "2022-03-20T20:10:35.266+0000",
		"project": "foo",
		"environment": "stage",
		"data": {
			"kind": "Event",
			"apiVersion": "audit.k8s.io/v1",
			"level": "Request"
		}
	}]
}
```

**Describe the solution you'd like**
We would like to use filter plugin to make a custom json payload that can be sent to http server via http output plugin.

**Describe alternatives you've considered**
In absence of this we are planning to develop custom go output plugin that will allow us to build json payload that has support for json array.

**Comment by penkendo** [comment]
I'm having the same issue with json output that needs nested arrays.  I'm sure I'm missing something simple... how did you solve this with Lua?

**Comment by gh-kgangineni** [comment]
Hi @apratina ,
Having similar problem. Can you please share your Lua function .
