### ISSUE TITLE
Tail input possibly violates path restriction

### ISSUE THREAD

**Issue by Antiarchitect** [fluent/fluent-bit#5168]
## Bug Report

**Describe the bug**
Experiencing some strange behavior with tail plugin and the directory with symlinks. In some rare cases tail plugin restriction fails

Most of the config (see Configuration) is not important. What is it should only search files under `/var/log/containers` directory. In case of k8s node all entities inside the `/var/log/containers` are symlinks (do not know if actually matter). In some rare cases I have some logs with the  `source` field starting with `/var/log/pods` which is a bug because of the `path` restriction. Do not know how to reproduce it, but having log rate about 9k records/s I have about 1.4M such records per 8 hours which is about 50 records/s. So it's very rare. Could it be some race condition during k8s is switching symlink from one file to another?

**Your Environment**

* Version used: 1.9.0
* Configuration:

```
    [INPUT]
        name             tail
        tag              k8s
        path             /var/log/containers/*.log
        db               /var/log/containers-logs.db
        key              raw
        path_key         source
        multiline.parser cri
        ignore_older     1d
        mem_buf_limit    256MB
        refresh_interval 10
        skip_long_lines  on
```

* Environment name and version (e.g. Kubernetes? What version?): 1.22.7
* Server type and version: bare metal
* Operating System and version: CentOS 7
* Filters and plugins:

**Comment by patrick-stephens** [comment]
It's valid for files to be symlinked so not sure what you mean by path restriction? If the symlink is there in containers and the destination is present, i.e. you have mounted pods, it will be followed. This is desired behaviour for container runtimes like crio that have their logs symlinked for backwards compatibility like you see.

If you don't want them then remove the pod mount point or drop the logs before output.

**Comment by Antiarchitect** [comment]
To clarify. According to the `path` directive it should only watch `/var/log/containers` directory and set `source` field accordingly. There is a small percentage of records that contains `/var/log/pods/...` in the `source` field.

**Comment by patrick-stephens** [comment]
Are they symlinked on your system though? From the Fluent Bit perspective those files ae in `/var/logs/containers` - the entries appear in the listing. The actual file may be elsewhere which then presumably is what is being resolved for the `source` field. As I say, on some platforms containers --> pods and this can be version dependent as the runtime or its configuration updates - if it  did not follow the links then you would lose all those logs.

Note this is standard K8S architecture: https://github.com/kubernetes/design-proposals-archive/blob/main/node/kubelet-cri-logging.md

What is it you want to achieve?

1. No logs from /var/logs/pods? Remove the the mount points in your pod spec then those logs will not resolve and not appear, or use a `grep` filter to drop these before they are sent.
2. Always report /var/logs/containers for `source` even if the actual file is in /var/logs/pods? Add a modify or other mutation filter to change them.

I do not think the current behaviour is a bug: without it then it would trigger a lot of reports of missing logs when users transition between platforms or versions of their platforms that start using the `/var/logs/pods` directory. At some point though the `/var/logs/containers` will disappear although when it does we still have to support older platforms that are using it.

https://github.com/kubernetes/kubernetes/issues/53022

**Comment by Antiarchitect** [comment]
I will try to rewrite my regex filters to match /var/log/pods because of /var/log/containers possible deprecation. This will solve the problem. Thank you for your time.
