### ISSUE TITLE
kubernetes filter error ( connecting to API server)

### ISSUE THREAD

**Issue by bat9r** [fluent/fluent-bit#517]
Hi
I have created a kubernetes cluster 1.7.9, wanna use elasticsearch+flunt-bit for log pods.
When i start DeamonSet i get this error in flunt-bit pod log
```
[2018/02/21 17:11:01] [ info] [engine] started
[2018/02/21 17:11:01] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2018/02/21 17:11:01] [ info] [filter_kube] local POD info OK
[2018/02/21 17:11:01] [ info] [filter_kube] testing connectivity with API server...
[2018/02/21 17:11:02] [error] [filter_kube] could not get meta for POD fluent-bit-r91pg
```
I think this is related #332 but i use fluent/fluent-bit:0.12.14, and this bug still not fixed.
My fluent-bit ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: elk
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf


    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name            kubernetes
        Match           kube.*
        Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_URL        https://kubernetes.default.svc:443
        Merge_JSON_Log  On

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Retry_Limit     False

  parsers.conf: |
    [PARSER]
        Name   json-test
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
```

**Comment by edsiper** [comment]
Definitely it's not related to #332, since that one is about Systemd/Journal connector.

would you please try changing Kube_URL parameter to "https://kubernetes.default.svc.cluster.local:443" ?

**Comment by bat9r** [comment]
I changed this line,but it still didn't work.
Forgot to write, i using RBAC authorization in kubernetes cluster. But fluent-bit have similar role as fluentd.
My role configs.
``` 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: elk
```

**Comment by edsiper** [comment]
@bat9r please validate your rules against the rules suggested here:

https://github.com/fluent/fluent-bit-kubernetes-logging

**Comment by edsiper** [comment]
@bat9r any luck with the suggested recipes/rules ?

**Comment by bat9r** [comment]
@edsiper I started use kubernetes 1.8.7, and everything is going worked.
Thank you very much for help.

**Comment by bat9r** [comment]
I still had to run this plugin on kubernetes 1.7.9, and i did it with this config.
`
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: swagger-reader-fluent-bit
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- nonResourceURLs:
  - /swagger-2.0.0.pb-v1 
  - /swagger.json
  - /swaggerapi
  - /swaggerapi/*
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: elk
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: swagger-reader
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: elk
roleRef:
  kind: ClusterRole
  name: swagger-reader-fluent-bit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: elk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: elk
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
    
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10 
  filter-kubernetes.conf: |
    [FILTER]
        Name           grep
        Match          kube.*
        Regex          [ ](?i)warn|error|warning|err[ ]
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc.cluster.local:443
        Merge_JSON_Log On
  output-elasticsearch.conf: |
    [OUTPUT]
        Name              es
        Match             *
        Host              ${FLUENT_ELASTICSEARCH_HOST}
        Port              ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format   On
        Index             fluentbit
        Type              flb_type
        Include_Tag_Key   On
        Retry_Limit       False
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: elk
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.12.14
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-v"]
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "es5-master-svc.elk.svc.cluster.local"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
`

**Comment by alecrajeev** [comment]
Just in case anybody sees this error again I got it for a different reason. I turned on verbose logging (adding --verbose to the start command with `c:\fluent-bit\bin\fluent-bit.exe --verbose`)
Then it showed me this:

```
[2021/03/27 23:50:46] [ info] [filter:kubernetes:kubernetes.0] Wait 30 secs until DNS starts up (1/6)
[2021/03/27 23:51:16] [debug] [http_client] server kubernetes.default.svc.cluster.local:443 will close connection #728
[2021/03/27 23:51:16] [debug] [filter:kubernetes:kubernetes.0] API Server (ns=logging, pod=cc-fluent-bit-windows-test-00000) http_do=0, HTTP Status: 403
[2021/03/27 23:51:16] [debug] [filter:kubernetes:kubernetes.0] API Server response
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"cc-fluent-bit-windows-test-0000\" is forbidden: User \"system:serviceaccount:logging:cc-fluent-bit-windows-test\" cannot get resource \"pods\" in API group \"\" in the namespace \"logging\"","reason":"Forbidden","details":{"name":"cc-fluent-bit-windows-test-98knk","kind":"pods"},"code":403}

[2021/03/27 23:51:16] [ warn] [filter:kubernetes:kubernetes.0] could not get meta for POD cc-fluent-bit-windows-test-00000
```

The error was that my clusterrolebinding had the wrong namespace. It has to match the namespace of the pod. Once I set the namespace here to logging it fixed my issue.

```
subjects:
  - kind: ServiceAccount
    name: cc-fluent-bit-windows-test
    namespace: logging
```
