### ISSUE TITLE
[error] [sqldb] cannot open database /var/log/flb_kube.db

### ISSUE THREAD

**Issue by andutt** [fluent/fluent-bit#5180]
## Bug Report

**Describe the bug**
Openshift 4
CoreOS cri-o
fluent-bit v1.8.10 deployed in logging namespace as HOWTO.
Role, Rolebinding and serviceaccount created as HOWTO. Deploying daemonset and following errormessage occours.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[1mFluent Bit v1.8.10[0m
* [1m[93mCopyright (C) 2019-2021 The Fluent Bit Authors[0m
* [1m[93mCopyright (C) 2015-2018 Treasure Data[0m
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/03/25 09:51:42] [ info] [engine] started (pid=1)
[2022/03/25 09:51:42] [ info] [storage] version=1.1.5, initializing...
[2022/03/25 09:51:42] [ info] [storage] in-memory
[2022/03/25 09:51:42] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/03/25 09:51:42] [ info] [cmetrics] version=0.2.2
[2022/03/25 09:51:42] [error] [sqldb] cannot open database /var/log/flb_kube.db
[2022/03/25 09:51:42] [error] [input:tail:tail.0] could not open/create database
[2022/03/25 09:51:42] [error] Failed initialize input tail.0
[2022/03/25 09:51:42] [error] [lib] backend failed
```
- Steps to reproduce the problem:
Deploy daemonset

**Expected behavior**
Fluent-bit starts and transfer logs to "outside" elasticsearch solution.

**Your Environment**
Openshift 4
CoreOS cri-o
fluent-bit v1.8.10

**Additional context**
The only thing changed is Path since pod logs have a different path on CoreOS, like below. Where does fluent-bit want to create this database, is it in the filesystem on the nodes or on a mounted pvc? Since permissions to write on the nodes must likely is prohibited by permissions and security contexts.

[INPUT]
    Name              tail
    Tag               kube.*
    Path              /host/var/log/pods/*.log
    Parser            cri
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10

**Comment by patrick-stephens** [comment]
There's not really much point to using the database inside a pod - it's intended to be persistent so if a pod is evicted, dies, restarts then it can be used to start forwarding logs from where the previous one left off.

The directory for it needs to be persistent and writable. There are a few issues with security contexts you have to resolve for Openshift to allow that as the defaults are locked down to prevent it for good reasons. If you're using PVCs make sure to mount the relevant PVC to get the DB for the node it is running on: the DB keeps track of the host log offsets so if you need to make sure the logs being handled match the DB, i.e. are for the same host.

Note that pod logs are symlinked to the /var/logs/containers still as that is standard Kubernetes architecture. As long as you mount both `/var/logs/containers` and the symlink target of `/var/logs/pods` then it will work fine: this is what the default helm chart does to allow similar configuration across infrastructures.

I do not believe this is an issue with Fluent Bit, it seems to be configuration. I'm going to tag as question and close in a bit unless there is some more detail indicating a Fluent Bit issue.

See also:
- https://docs.fluentbit.io/manual/installation/kubernetes#note-for-openshift
- https://calyptia.com/2022/03/23/how-to-send-openshift-logs-and-metrics-to-datadog-elastic-and-grafana/#gather
