### ISSUE TITLE
Version parameter in the packaging/build.sh is not registered and used so it doesn't build the version asked

### ISSUE THREAD

**Issue by mlcdf** [fluent/fluent-bit#5184]
## Bug Report

Hello,

**Describe the bug**
I'm trying to build fluent-bit version 1.7.2 for centos/7 using the build.sh script in `/packaging` and it builds the version v.1.9.1 instead.

**To Reproduce**
```
git clone github.com/fluent/fluent-bit
cd fluent-bit/packaging
./build.sh -v 1.7.2 -d centos/7 
tree packages/centos/7
└── 2022-03-25-11_59_22
    ├── td-agent-bit-1.9.1-1.x86_64-headers-extra.rpm
    ├── td-agent-bit-1.9.1-1.x86_64-headers.rpm
    └── td-agent-bit-1.9.1-1.x86_64.rpm
    
rpm -qip 2022-03-25-11_59_22/td-agent-bit-1.9.1-1.x86_64.rpm | grep Version
Version     : 1.9.1
```

**Expected behavior**
It should build the version 1.7.2 like the [doc](https://github.com/fluent/fluent-bit/tree/master/packaging) says.

**Your Environment**
I'm running the script from a Debian 10 machine, with Bash 5.0.3

**Comment by patrick-stephens** [comment]
This script is not for 1.7 I'm afraid, anything prior to 1.9 is built via a separate repo.
https://github.com/fluent/fluent-bit-packaging
Apologies for the confusion, there is ongoing work to improve though.

**Comment by mlcdf** [comment]
@patrick-stephens no worries, I just tried with the old repo and it works like a charm. Thanks for the quick response :)
