### ISSUE TITLE
[output --> kafka](1.9.0) adds an invalid key value field to messages

### ISSUE THREAD

**Issue by nickytd** [fluent/fluent-bit#5187]
## Bug Report

**Describe the bug**
In 1.9.0 kafka output plugin an extra field is added with empty key and non null value (most probably timestamp)
```{"":1648246867.385769,"cpu_p":6.375,"user_p":5.25,"system_p":1.125,"cpu0.p_cpu":2.0,"cpu0.p_user":1.0,"cpu0.p_system":1.0,"cpu1.p_cpu":14.0,"cpu1.p_user":11.0,"cpu1.p_system":3.0,"cpu2.p_cpu":6.0,"cpu2.p_user":5.0,"cpu2.p_system":1.0,"cpu3.p_cpu":3.0,"cpu3.p_user":3.0,"cpu3.p_system":0.0,"cpu4.p_cpu":12.0,"cpu4.p_user":11.0,"cpu4.p_system":1.0,"cpu5.p_cpu":2.0,"cpu5.p_user":1.0,"cpu5.p_system":1.0,"cpu6.p_cpu":6.0,"cpu6.p_user":5.0,"cpu6.p_system":1.0,"cpu7.p_cpu":6.0,"cpu7.p_user":5.0,"cpu7.p_system":1.0}```

In 1.8.15 the output is according the configuration  and expected. There is no field with "" key.
```{"@timestamp":"2022-03-25T22:23:36.212822Z","cpu_p":63.125,"user_p":56.00000000000001,"system_p":7.124999999999999,"cpu0.p_cpu":41.0,"cpu0.p_user":28.0,"cpu0.p_system":13.0,"cpu1.p_cpu":34.0,"cpu1.p_user":29.0,"cpu1.p_system":5.0,"cpu2.p_cpu":91.0,"cpu2.p_user":69.0,"cpu2.p_system":22.0,"cpu3.p_cpu":81.0,"cpu3.p_user":78.0,"cpu3.p_system":3.0,"cpu4.p_cpu":50.0,"cpu4.p_user":43.0,"cpu4.p_system":7.0,"cpu5.p_cpu":89.0,"cpu5.p_user":87.0,"cpu5.p_system":2.0,"cpu6.p_cpu":45.0,"cpu6.p_user":43.0,"cpu6.p_system":2.0,"cpu7.p_cpu":75.0,"cpu7.p_user":71.0,"cpu7.p_system":4.0}```

The empty key value is a problem as later opensearch rejects indexing because the record is not valid (empty key)

**To Reproduce**
The case can be easily reproduce and demonstrated with following  [docker-compose](https://github.com/nickytd/docker-compose-fluentbit-kafka-logstash-opensearch) 

The working case can be demonstrated when fluent-bit image is fluent/fluent-bit:1.8.15. 
The error case is reproduced with fluent/fluent-bit:1.9.0. 
The configuration remains the same in both cases.

The messages in kafka topic can be dumped with ```docker exec -ti kafka /opt/bitnami/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic containers```

**Comment by nokute78** [comment]
Could you check https://github.com/fluent/fluent-bit/issues/5097 ?

**Comment by nickytd** [comment]
Thanks. Yes it is the same issue. I will close this as duplicate.
