### ISSUE TITLE
How to remove @timestampt or convert it to ISO8601

### ISSUE THREAD

**Issue by scila1996** [fluent/fluent-bit#5194]
Hi

I'm using fluentbit to craw log file and put to Kafka Output, then from Logstash, I set input to Kafka and put it to Elasticsearch. Message log from fluentbit to kafka always @timestampt with UNIX style, I want to remove @timestampt field or convert it to ISO8601 format, how can i do it ! tks !

**Comment by JeffLuoo** [comment]
lua script could be a good option here: https://docs.fluentbit.io/manual/pipeline/filters/lua
