### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [fluent/fluent-bit#52]
I would like to point out that an identifier like "[`__flb_config_verbose`](https://github.com/fluent/fluent-bit/blob/1d4fd8433b7dda1feed72192c5b9bdd8a96c4afc/include/fluent-bit/flb_config.h#L83 "Update candidate")" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by edsiper** [comment]
Agree, that's something should go away, I will make it configurable from the lib context. I will keep this issue open until it get fixed. 

thanks for the reviews!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/fluent/fluent-bit/commit/4f7548b8db68bc826426d2638718926a79ecfdac "Deletion of a questionable identifier").
