### ISSUE TITLE
fluent-bit   ES output with incorrect fileds mapping

### ISSUE THREAD

**Issue by jenningsloy318** [fluent/fluent-bit#520]
I have a log with following content, want to save into ES and visulize in kibana, it is parsed correctly in fluent-bit via the parser but stored in ES, they are all in _source but invidual fileds.

```
Unavailable 13.12.2017 02:12:56 - 13.12.2017 02:14:56
Available   13.12.2017 02:15:56 - 13.12.2017 02:19:56
Unavailable 13.12.2017 02:20:56 - 13.12.2017 02:20:56
Unavailable 14.12.2017 11:01:32 - 14.12.2017 11:02:32
Available   14.12.2017 11:03:32 - 16.12.2017 02:27:36
Unavailable 28.12.2017 07:30:16 - 28.12.2017 07:32:37
Available   28.12.2017 07:33:37 - 29.01.2018 09:17:24
Available   29.01.2018 09:22:00 - 29.01.2018 09:22:00
Unavailable 29.01.2018 09:23:00 - 29.01.2018 09:24:00
Available   29.01.2018 09:25:00 - 29.01.2018 09:30:02
Unavailable 29.01.2018 09:31:02 - 29.01.2018 09:31:02
Available   29.01.2018 09:32:02 - 30.01.2018 07:47:06
Unavailable 30.01.2018 07:48:06 - 30.01.2018 08:25:06
Unavailable 30.01.2018 08:27:24 - 30.01.2018 08:29:24
Available   30.01.2018 08:30:24 - 31.01.2018 09:00:47
Unavailable 31.01.2018 09:01:47 - 31.01.2018 09:02:47
Available   31.01.2018 09:03:47 - 01.02.2018 02:54:50
```

```
[INPUT]
    Name        tail
    Path       /var/log/db/available.log
    Tag         db-available
[FILTER]
    Name parser
    Key_Name log
    Match db-available
    Parser db-available
```

for the `OUTPUT` section, I have tried following three settings:

```
[OUTPUT]
Name es
Match db-available
Host 192.168.59.130
Port 9200
```
or 
```
[OUTPUT]
Name es
Match db-available
Host 192.168.59.130
Port 9200
Type log
```

or 
```
[OUTPUT]
Name es
Match db-available
Host 192.168.59.130
Port 9200
Logstash_Format on
Logstash_Prefix db-availabl
```
and the parser
```
[PARSER]
    Name db-available
    Format regex
    Regex  ^(?<STATUS>^[AU]?.*) (?<CHANGETIME>[^ ]*\ [^ ]*) - (?<ENDTIME>[^ ]*\ [^ ]*)$
```
but all the log content is parsed correctly, but when stored in ES, they are all in _source 
```
  "_source": {
    "@timestamp": "2018-02-01T07:18:57.699Z",
    "STATUS": "Unavailable",
    "CHANGETIME": "25.01.2018 03:30:12",
    "ENDTIME": "01.02.2018 06:48:18"
  }
```
What I want to is for STATUS, CHANGETIME,ENDTIME are separate filed, not in _source filed, thus I can visulize these fileds in kibana. 
```
  "_source": {
    "@timestamp": "2018-02-01T07:18:57.699Z",
  }
    "STATUS": "Unavailable",
    "CHANGETIME": "25.01.2018 03:30:12",
    "ENDTIME": "01.02.2018 06:48:18"
```

**Comment by jenningsloy318** [comment]
@edsiper 
so fluent-bit didn't produce the output as ES expetcts ?  How can I test if the output is conformed to ES  data format?

**Comment by edsiper** [comment]
__If__ I am not wrong that's the default behavior but I am not an expert on elasticsearch.

@solsson @StevenACoffman do you know anything about the expected Elasticsearch behavior ?

**Comment by solsson** [comment]
Nope, haven't tried the ES output. @jenningsloy318 How about using the kafka output, then ingesting to ES using Logstash's Kafka input? It'll let you transform to an intermediate topic if you need to.

**Comment by edsiper** [comment]
personally I have two comments:

- records are stored in elasticsearch under _source field. I think this is OK.
- question: should parsed records of _source be stored out of that specific map entry ?

**Comment by jenningsloy318** [comment]
@solsson this is one option but I didn't test,  but for my initial purpose i don't want to introduce extra layer ,just want fluentbit to ES.
@edsiper if there is an option  to set the ES output field ,that will be great! default we can store in _source ,and we can also change it to standalone fields.

**Comment by jenningsloy318** [comment]
@edsiper 

I used filebeat to collect logs and send to logstash. 
logstash conf
```


filter {

 

  if "db-available" in [tags] {

    grok {

      match => { "message" => "%{WORD:STATUS}\s+%{DATESTAMP:CHANGETIME}\s-\s%{DATESTAMP:ENDTIME}" }

    }

  }

}

 

output {



 

  if "hana-available" in [tags] {

    elasticsearch {

      hosts => "10.180.1.71:9200"

      manage_template => false

      index => "filebeat-6.1.1-db-available-%{+YYYY.MM.dd}"

    }

  }

}
```

**Comment by edsiper** [comment]
after some research I've found that mapping looks correct when Fluent Bit or Fluentd is used. Note that the _source field is something specific about Elasticsearch. Despite you see the content there (which is expected) you can query the document with Kibana without any problems, e.g:

![kibana](https://user-images.githubusercontent.com/369718/37731721-83a96b2a-2d08-11e8-9708-76c818288121.png)

what you are seeing is how the record is stored internally but not the end-representation.

**Comment by jenningsloy318** [comment]
@edsiper Thanks for you info, my misunderstanding of the visulizaiton in kibana, I don't  configure Buckets (X-Axis and Y-Axis).
