### ISSUE TITLE
Add octet_count framing option to syslog input

### ISSUE THREAD

**Issue by weh** [fluent/fluent-bit#5203]
We have a syslog source that is using octet count as message delimiter. Instead of a newline or zero byte it defines the message length as prefix. Newslines get ignored, and the octet_count at the beginning of the message defines its length.

Example from fluentd documentation: `43 <6>Sep 10 00:00:00 localhost logger: hello!`

fluentd has an option `frame_type` to enable this.
- https://docs.fluentd.org/input/syslog#frame_type
- https://datatracker.ietf.org/doc/html/rfc6587#section-3.4

if possible i would suggest to also add a config option `frame_type` which accepts the values `traditional` (default) and `octet_count`.

**Comment by dgsardina** [comment]
I have hit this very same limitation and was forced to use fluentd instead. Would be interested in this feature too

**Comment by weh** [comment]
we also switched to fluentd. but i still think this would be nice, and also not that much work. but i am not a C guy, and don't dare to implement this.

**Comment by dgsardina** [comment]
> we also switched to fluentd. but i still think this would be nice, and also not that much work. but i am not a C guy, and don't dare to implement this.

Which is exactly my case...
