### ISSUE TITLE
0 new files found on path

### ISSUE THREAD

**Issue by jangid21** [fluent/fluent-bit#5208]
Configurations  I am using - 
## https://docs.fluentbit.io/manual/pipeline/inputs
[INPUT]
    Name             tail
	Alias            logfiles
	Path             *.log
	Path_Key         source
	DB               fluent-bit.db
	DB.locking       true
	Refresh_Interval 20
	Rotate_Wait      60
	Multiline        On
    Parser_Firstline service_line_beginning

[FILTER]
    Name nest
    Match *
    Operation nest
    Wildcard fields.*
    Nest_under fields
    Remove_prefix fields.

## https://docs.fluentbit.io/manual/pipeline/outputs
[OUTPUT]
    Name  splunk
    Match *

    Host  splunkcloud.com
	
    Port 449
    tls  On

    header Authorization    ${SPLUNK_TOKEN}
    Splunk_Send_Raw On

fluentbit container- 
spec:
  containers:

  - name: fluent-bit
    image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.12.0
    ports:
    - name: http-fluent
      containerPort: 2021
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: http-fluent
    readinessProbe:
      httpGet:
        path: /
        port: http-fluent
    volumeMounts:
    - name: logs
      mountPath: /logs
    - name: fluentbit-config
      mountPath: /fluent-bit/etc
   
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

These configurations are deployed on kubernates but I am getting logs as-
0 new files found on path '*.log'
cannot read info from: *.log

**Comment by patrick-stephens** [comment]
The path presumably should be `/logs/*.log` as that seems to be the mount point, otherwise it'll be looking in the same folder as the config file.
