### ISSUE TITLE
Parser filter lost config option 'Unescape_Key' without warning in 1.9.1

### ISSUE THREAD

**Issue by fpytloun** [fluent/fluent-bit#5210]
## Bug Report

**Describe the bug**
Since update to 1.9.1 I am seeing this issue:

```
[error] [config] parser: unknown configuration property 'Unescape_Key'. The following properties are allowed: Key_Name, Parser, Preserve_Key, and Reserve_Data.
```

Because parameter `Unescape_Key` disappeared. I found no information in changelog or upgrade notes. This might be just missing.

In 1.8, this was still present: https://docs.fluentbit.io/manual/v/1.8/pipeline/filters/parser

I can't trace any information about why it was removed.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by nokute78** [comment]
The property seems not to be supported but it is documented. 
https://github.com/fluent/fluent-bit/pull/4874#issuecomment-1046161504

Could you check https://github.com/fluent/fluent-bit/issues/453#issuecomment-375066882 ?

**Comment by fpytloun** [comment]
Thank you for further info and MR to mark it as deprecated (and therefore keeping config backward-compatible) 👍 

Can you please also check this one regression I've found in 1.9.1? https://github.com/fluent/fluent-bit/issues/5209
