### ISSUE TITLE
`Time_Keep On` creates a double field `time` when the log itself contains `time` field

### ISSUE THREAD

**Issue by hagaivcita** [fluent/fluent-bit#5216]
## Bug Report

**Describe the bug**

running EFK stack i found out that some logs are not reaching ES.
looking in `debug` mode i found that i get an error of duplicate `time` field.  
it appears that whenever the `log` has a field `time` in it, there is a duplication and ES rejects the sent document (there is a mapping to `time` field).

1. changing to `Time_Keep Off` indeed eliminated the issue **BUT** now logs which doesnt have `time` field doesnt have `time` field at all
2. changing to `Time_Key log_time` had no effect at all on the result, is was all dependent on the `Time_Keep` On/Off

maybe i didnt understand the documentation but it implies that:
assuming `Time_key` and `Time_Format` is set
1. if `Time_Keep Off` & no `Time_Key` found -> use current time
2.  if `Time_Keep Off` & `Time_Key` found -> try to parse, if fails, simply use what is there
3. if `Time_Keep On` -> expect double fields if the `log` has `Time_Key` field

### **To Reproduce**
- Example log message if applicable:
```
"status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"i_o_exception","reason":"Duplicate field 'time'\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@38d82cb1; line: 1, column: 1073]"}}}}]}
```
- Steps to reproduce the problem:

1. EFK stack
2. have mapping `"time": {
          "type": "date"
        }`
5. `fluent-bit.conf`:
```yaml
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name  stdout
        Match kube.*

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        # This is the section who does the 'log' merging!
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        
    [FILTER]
        Name  stdout
        Match kube.*

  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*service-demo*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Logstash_Prefix fluent-bit
        Retry_Limit     False
        
    [OUTPUT]
        Name             stdout
        Match            kube.*
        json_date_format iso8601
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
```

9. fire logs with field `time`

### **Expected behavior**

1. when `Time_Keep Off` and failed to find and parse the field in `Time_Key` produce one with the current time.
2. when `Time_Keep Off` but success to find and parse, extract the `Time_Key` field outside the `log` field
3. when merging logs using `kubernetes` filter overwrite existing fields

### **Examples**
so i have ran debug mode with `stdout` filter on after every change and `stdout` output to view the result:
**after parser**
note first `time` field in current time OUTSIDE of `log` (i assume thats the [docker json driver](https://docs.docker.com/config/containers/logging/json-file/) but `Time_Keep Off` would eliminate it)  
the second `time` field is INSIDE the `log` field
```
[0] kube.var.log.containers.service-demo_kube-logging_service-demo-28e7cbe6daf26538c596d92967271ffbedb55a87899475e96e873483f63dcf42.log: [1648668456.364385100, {"log"=>"{"pid":986,"thread":985,"platform":"linux","application_time":"2022-03-30T19:27:36.362Z","level":"INFO","message":"A message","trace":null,"time":"2023-01-01T13:55:55.555Z","foo":"bar2baz2shnaz"}
", "stream"=>"stdout", "time"=>"2022-03-30T19:27:36.3643851Z"}]
```

**after kubernetes plugin filter **
here using `Merge_Log On` merges out the log, but instead of overwriting the `time` field, it is join, causing the JSON to have duplicates! (valid JSON but unexpected one!)
```
[0] kube.var.log.containers.service-demo_kube-logging_service-demo-28e7cbe6daf26538c596d92967271ffbedb55a87899475e96e873483f63dcf42.log: [1648668456.364385100, {"log"=>"{"pid":986,"thread":985,"platform":"linux","application_time":"2022-03-30T19:27:36.362Z","level":"INFO","message":"A message","trace":null,"time":"2023-01-01T13:55:55.555Z","foo":"bar2baz2shnaz"}
", "stream"=>"stdout", "time"=>"2022-03-30T19:27:36.3643851Z", "pid"=>986, "thread"=>985, "platform"=>"linux", "application_time"=>"2022-03-30T19:27:36.362Z", "level"=>"INFO", "message"=>"A message", "trace"=>nil, "time"=>"2023-01-01T13:55:55.555Z", "foo"=>"bar2baz2shnaz", "kubernetes"=>{"pod_name"=>"service-demo", "namespace_name"=>"kube-logging", "pod_id"=>"6678d973-bc62-45cf-8152-fb2f68d9f926", "labels"=>{"run"=>"service-demo"}, "host"=>"minikube", "container_name"=>"service-demo", "docker_id"=>"28e7cbe6daf26538c596d92967271ffbedb55a87899475e96e873483f63dcf42", "container_hash"=>"sha256:f8ffb30ba197a3e99d8e7e8d34f5e53800d735751edc5d290668f08acbb8aa1a", "container_image"=>"service-demo:1"}}]
```
**output**
same as after kubernetes plugin

### **Your Environment**

* Version used: `1.3.7`, `1.4.3`, `1.7.2`, `1.9.1` (latest)
* Configuration: as above
* Environment name and version (e.g. Kubernetes? What version?): kubernetes `1.19.15`
* Operating System and version: ubuntu, linux/amd64
* Filters and plugins: parser: json, filter: kubernetes, output: es

**Comment by pschichtel** [comment]
@hagaivcita did you find a solution for this?
