### ISSUE TITLE
Fluent-bit don't stop when SIGTERM

### ISSUE THREAD

**Issue by tguenneguez** [fluent/fluent-bit#5223]
## Bug Report

**Describe the bug**
When we send a SIGTERM to fluent-bit, it doesn't stop.
We have got messages in loop :
[2022/03/30 13:28:19] [ info] [task] task_id=0 still running on route(s): loki/loki.0
We have to send a SIGKILL to stop it.

**Your Environment**
* Version used: v1.8.7
* Server type and version: Linux redhat 7
* Filters and plugins:
loki
tail modif
grep

**Comment by lecaros** [comment]
Hi @tguenneguez,
Can you share a repro of this?
Is this happening in the latest version? (1.8.15 or 1.9.1)

**Comment by tguenneguez** [comment]
Hello,

I can't share the repo, but it's I can send you the information you wan.
It will be deficult to test with 1.8.15 et 1.9.1.

Thanks
Thomas

**Comment by tguenneguez** [comment]
@lecaros have look this issue ?

**Comment by tguenneguez** [comment]
How to not close this issue automaticly ?

**Comment by lecaros** [comment]
@tguenneguez hello!
If you have a repro for this issue, we'll gladly look into it. Otherwise, we can't mak.progress on it.
