### ISSUE TITLE
FluentBit CPU bottleneck when higher EPS | Best practices for high EPS

### ISSUE THREAD

**Issue by Infusible** [fluent/fluent-bit#5225]
Not working.
image: fluent/fluent-bit:1.9.1

cpu used fluent-bit
last 2days
<img width="1801" alt="image" src="https://user-images.githubusercontent.com/31616457/161272947-5d009358-ac6d-4b5a-8ce0-b2c6ce1c717e.png">

last 12h
<img width="1993" alt="image" src="https://user-images.githubusercontent.com/31616457/161275016-32d95eaf-ce44-41ea-a441-644f825950d4.png">

last 7days
<img width="1955" alt="image" src="https://user-images.githubusercontent.com/31616457/161275605-22ea3c1f-5481-44ad-867e-230224edd27e.png">

my logs one pod
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/31616457/161274785-ae9e61d2-c6c5-4cf1-aeb0-9352bbb6d3a5.png">

_**configs:**_
**custom_parsers.conf**
`[PARSER]
  Name   json
  Format json
  Time_Key time
  Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
  Name        docker
  Format      json
  Time_Key    time
  Time_Format %Y-%m-%dT%H:%M:%S.%L
  Time_Keep   On`

**fluent-bit.conf**
`[SERVICE]
  Daemon Off
  Flush 10
  Log_Level info
  Parsers_File parsers.conf
  Parsers_File custom_parsers.conf
  HTTP_Server On
  HTTP_Listen 0.0.0.0
  HTTP_Port 2020
  Health_Check On

[INPUT]
  Name              tail
  Tag               kube.*
  Path              /var/log/containers/*.log
  Parser            docker
  DB                /var/log/flb_kube.db
  Skip_Long_Lines   On
  Refresh_Interval  10

[FILTER]
  Name                kubernetes
  Match               kube.*
  Kube_URL            https://kubernetes.default.svc:443
  Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
  Kube_Tag_Prefix     kube.var.log.containers.
  Merge_Log           On
  Keep_Log            Off
  K8S-Logging.Parser  On
  K8S-Logging.Exclude Off

[FILTER]
  Name    lua
  Match   kube.*
  script  /fluent-bit/etc/kubeparse.lua
  call    set_topic

[FILTER]
  Name                nest
  Match               kube.*
  Operation           lift
  Nested_under        kubernetes
  Add_prefix          kubernetes_

[FILTER]
  Name                nest
  Match               kube.*
  Operation           lift
  Nested_under        kubernetes_labels
  Add_prefix          kubernetes_labels_

[FILTER]
  Name    modify
  Match   kube.*
  Rename  kubernetes_labels_pod-template-hash kubernetes_labels_pod_template_hash

[OUTPUT]
  workers 4
  Name           kafka
  Match          kube.*
  Brokers        ${KAFKA_BROKERS}
  Topics         logs.unparsed
  dynamic_topic  true
  topic_key      topic_key
  rdkafka.debug All
  rdkafka.security.protocol sasl_ssl
  rdkafka.enable.ssl.certificate.verification false
  rdkafka.sasl.username <user_name>
  rdkafka.sasl.password ${KAFKA_PASSWORD}
  rdkafka.sasl.mechanism SCRAM-SHA-512
  Timestamp_Key  @timestamp
  Retry_Limit    false
  
  rdkafka.log.connection.close false
  
  rdkafka.queue.buffering.max.kbytes 10240
  
  rdkafka.request.required.acks 1
  rdkafka.compression.codec snappy
  rdkafka.queue.buffering.max.ms 20`

**kubeparse.lua**
`function set_topic(tag, timestamp, record)
    if record["kubernetes"]["namespace_name"] ~= nil then
      record["topic_key"] = "logs."
        .. record["kubernetes"]["namespace_name"]
    end
  return 2, timestamp, record
end`

service runed to k8s
not  limits for cpu and memory
only one kernel is used
we want more than one kernel to be used

plz help, @agup006 @dengalebr and reopen issues

_Originally posted by @Infusible in https://github.com/fluent/fluent-bit/issues/2790#issuecomment-1085921108_

**Comment by Infusible** [comment]
last 30days
<img width="1975" alt="image" src="https://user-images.githubusercontent.com/31616457/161283325-57798079-9f5b-4420-9574-2e51172d3ac2.png">

**Comment by Infusible** [comment]
plz update

**Comment by jgq2008303393** [comment]
Has the problem been solved？

**Comment by agup006** [comment]
I've reopened, though I'm not sure what a good fix here could be. @jgq2008303393 anything you would suggest or can contribute here?

**Comment by andreaiannacone** [comment]
do you have any news about this?

**Comment by Andexrian** [comment]
do you have any news about this problem?
