### ISSUE TITLE
Kubernetes - Fluent-bit  - Splunk 

### ISSUE THREAD

**Issue by jino-mariath** [fluent/fluent-bit#5229]
Could you help me to direct the Fluent-bit  -  Splunk log shipping using HEC (HTTP Event Collector)?

**Comment by patrick-stephens** [comment]
What's the problem? You'll need to provide some more details on the issue, including config.

Have you followed the docs? 
https://docs.fluentbit.io/manual/pipeline/outputs/splunk
Did you hit a specific issue?

**Comment by jino-mariath** [comment]
Thank you. This is fixed.
