### ISSUE TITLE
in_node_exporter_metrics: add Disk Space Used Basic (node_filesystem_avail_bytes)

### ISSUE THREAD

**Issue by gabrielSoudry** [fluent/fluent-bit#5236]
**Is your feature request related to a problem? Please describe.**

While using prometheus agent I have the pane "Disk Space Used Basic" working: 
![image](https://user-images.githubusercontent.com/40856463/161585960-8896b8eb-2d46-4944-92a6-0d7af1a67674.png)

Is it possible and in the roadmap to make it work using this plugin?

The query : 
`100 - ((node_filesystem_avail_bytes{instance="$node",job="$job",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance="$node",job="$job",device!~'rootfs'})
`
Thanks in advance :) 
fluentbit 1.9 with the prometheus scrape plugin allowed me to replace prometheus-agent, I just miss this feature :)

**Comment by LeoWinterDE** [comment]
This would be nice to have, for every partition just like node exporter from Prometheus.

My pipeline includes logs and metric information form devices in the field, collected by fluent-bit forwarded to redundant fluentd instances and saved in Prometheus (metrics) and opensearch (logs).
