### ISSUE TITLE
Allow using ENV variable is tag name

### ISSUE THREAD

**Issue by Clausewitz45** [fluent/fluent-bit#5240]
As far as I learnt the Environment Variables used in filter/parser/input/output sections only, but not in other places within the configuration ([2020](https://github.com/fluent/fluent-bit/issues/2020)). We are using it in the Tag part of the configuration, which is not resolved there and during the startup we got an error message regarding the not valid characters. 

We would like to use it, because we are sending the logs with different tags based on the environment and project environment variables. Please let me know if you think it is feasible.

**Comment by vikasmishra17** [comment]
We need the same feasibility, currently, we are using tag_regex instead of the tag. But the error we are getting is env variable is used but not set.
