### ISSUE TITLE
Failing to find a file for tail input should not be an error

### ISSUE THREAD

**Issue by Markbnj** [fluent/fluent-bit#525]
fluent-bit version: 0.13-dev-0.8

Our approach using fluentd was to keep all of our log inputs (fluentd sources) grouped logically into a small set of files. If a specific log file wasn't found then the tail input logged an event at (iirc) warn level that it was ignoring that spec. What we see in the same situation with fluent-bit is that it generates an error. I think you can make good arguments either way, but practically speaking many people will keep a global list of inputs rather than splitting them up and installing them on a per-application basis. For that reason I would vote in favor of this being a warning, or even info level.

**Comment by edsiper** [comment]
@Markbnj would you please paste here the exact error ? (there are many checks)

**Comment by Markbnj** [comment]
@edsiper sure, for example:

[2018/03/01 21:43:22] [debug] [in_tail] scanning path /var/log/upstart/olark*.log                                                                                                                             
[2018/03/01 21:43:22] [error] [in_tail] Cannot read info from: /var/log/upstart/olark*.log

So in this case this is running on a host where that log is not expected to be present. Note also in case I wasn't clear this does not cause the program to exit or anything, so it is really more a matter of semantics I guess.

Thanks!

**Comment by edsiper** [comment]
Fixed by 5dfdb74f

All "no matches" have been converted from "error" to "debug" messages

thanks.

**Comment by qqbuby** [comment]
@edsiper 

All "no matches" should be converted from "error" to "warn" messages?

**Comment by xPB12** [comment]
I agree with @qqbuby, it shouldn't be debug. Instead it should be warn.
