### ISSUE TITLE
Add missing docker tag for latest 1.9

### ISSUE THREAD

**Issue by pc-jedi** [fluent/fluent-bit#5254]
Currently the is only a `1.8` tag on docker hub pointing to the latest `1.8.x` release.
It would be great to have also a `1.9` tag pointing to the latest `1.9.x` release.

@patrick-stephens

**Comment by patrick-stephens** [comment]
Needs feeding in as part of changes for #4875 to make sure the automated releases also do a major version tag for both 1.8 and 1.9. Just a change to the reusable job hopefully.

**Comment by aflinchb** [comment]
I still dont see the docker tag for 1.9 

@patrick-stephens

**Comment by patrick-stephens** [comment]
Hmmm ok, I'll have a look next time I'm in the office

**Comment by patrick-stephens** [comment]
Looks like this is because the skopeo sync on release is not doing the major version tag: https://github.com/fluent/fluent-bit/blob/4e7ff2970b4d0192b6a6acc7c379a308bf1cd32b/.github/workflows/staging-release.yaml#L153

They are built in staging now:
```
$ docker pull ghcr.io/fluent/fluent-bit:1.9
Error response from daemon: manifest unknown

$ docker pull ghcr.io/fluent/fluent-bit/staging:1.9
1.9: Pulling from fluent/fluent-bit/staging
Digest: sha256:899fc9d4e363b059d4e48fb0b6184bd5312363c4baa406e911baf3d8e935090a
Status: Downloaded newer image for ghcr.io/fluent/fluent-bit/staging:1.9
ghcr.io/fluent/fluent-bit/staging:1.9

$ docker pull ghcr.io/fluent/fluent-bit/staging:1.9.3
1.9.3: Pulling from fluent/fluent-bit/staging
Digest: sha256:899fc9d4e363b059d4e48fb0b6184bd5312363c4baa406e911baf3d8e935090a
Status: Downloaded newer image for ghcr.io/fluent/fluent-bit/staging:1.9.3
ghcr.io/fluent/fluent-bit/staging:1.9.3
```

**Comment by patrick-stephens** [comment]
@aflinchb hopefully next 1.9 release this should finally be covered - I'd missed the sync from staging to release unfortunately. The images are definitely built with the tags in staging.

**Comment by patrick-stephens** [comment]
@aflinchb the 1.9.4 release seems to cover all the bases now - that ok for you?

**Comment by aflinchb** [comment]
@patrick-stephens - Yes - thank you!
