### ISSUE TITLE
Async Lock - Cloudwatch Logs Async Networking

### ISSUE THREAD

**Issue by matthewfala** [fluent/fluent-bit#5255]
# Cloudwatch Logs Async Networking
## Problem
Currently the cloudwatch_logs output plugin experiences networking errors frequently due to using a less tested and supported networking mode called synchronous networking. Customers constantly report seeing broken pipe and broken connection errors on cloudwatch due to sync networking as shown in the following tickets:
- https://github.com/aws/aws-for-fluent-bit/issues/293
- https://github.com/aws/aws-for-fluent-bit/issues/292

To resolve these problems, the team points users to set keep_alive to off. While this resolves broken pipe issues, it makes networking less efficient, and that coupled with the already inefficient synchronous networking, makes the cloudwatch_logs plugin very inefficient.

## Sync to Async Networking Migration Issues
Synchronous networking is a less supported networking mode that is used by the cloudwatch_logs plugin. Synchronous networking forces network calls to block a Fluent Bit thread rather than yielding to other work until the network call completes. In contrast to the more supported networking mode, async networking, async networking does not block Fluent Bit, but instead yeilds to the event loop durring network calls and allows other work to be accomplished until the network call is completed.

Cloudwatch_logs can't trivially switch from sync networking to use async networking because cloudwatch API requires each PutLog request to present information from the last request. This information is called the sequence token, and it enforces that only one cloudwatch PutLogEvents request to a given log stream can occur at a given time. With async networking turned on, we might start two PutLogEvents cloudwatch API requests at the same time with the same sequence token causing one of the requests to fail. If sync networking is used, we guarantee that we will complete one PutLogEvents request first, save the sequence token from the api response, and then begin the next PutLogEvents request with the updated sequence token.

Although we are compelled to use sync networking, the problem with using sync networking is:
- Inefficent - If there are multiple cloudwatch streams we are writing data to at the same time, we should record a sequence token per each stream and have each stream's networking occur sequentially in regards to itself but in parallel in regards to other streams. Currently, with sync networking, multiple streams will not be processed in parallel.
- No multi-worker support - Cloudwatch_logs currently doesn't support more than 1 worker. With multiple workers, the guarantee that sync networking will only allow one cloudwatch PutLogEvents request to happen at a given time is removed. Multiple workers are multiple threads that pay no attention to synchronicity of other threads when it comes to networking.
- Buggy - The sync networking option is less used and less supported by the Fluent Bit maintainers. Broken_pipe issues due to keep_alive problems are less likely to be resolved.

## Migrating to Async Networking
To migrate to async networking, we need a mechanism to synchronize network calls artificially, without using sync network mode. The goal is to have a system where only one thread can make an async network call to cloudwatch PutLogEvents api at a given time, and if another coroutine tries to make a call before PutLogEvents api completes, then the other coroutine is forced to wait. This way, we can guarantee that only one PutLogEvents api call happens at a given time, and we are able to update our sequence token with each request.  

An initial, but incorrect, thought to achieve this synchronization may be to have some sort of lock and busy wait system, where on starting a concurrent call to cloudwatch api PutLogEvents, the code will preempt the network call, and busy wait till the concurrent call is completed. This could allow for us to ensure that only one PutLogEvents api call happens at a time. Unfortunately, busy waiting is not an option. Fluent Bit may try to run multiple network calls on the same thread. If a second network call is preempted by a busy wait for a network call started on that same thread, then the busy wait of the second network call will never end, since it is blocked by and blocking the first network call's completion.

A better solution is to replace busy waiting with a non-blocking waiting system that allows for other work to be completed. A non blocking waiting system can enable concurrent requests to complete and signal pending requests on the same thread to begin. In terms of the cloudwatch api, we can begin to rely on a non-blocking wait to preserve synchronization, rather than the sync networking mode. If multiple cloudwatch api network calls to the same stream are about to be made, all but one network call can wait until signalled by the completion of an api call. Each pending network call's wait can end in a cascaded manner that enforces only one network call to be active at a given time.

The following document outlines an interface for implementing this non-blocking waiting system. It is called synchronizer.

Any time when Fluent Bit has concurrent code that needs to be synchronized, and that synchronized segment may make a network call or invoke `coro_yield`, traditional locks and busy waiting cannot be used, as deadlock may occur if one blocked synchronized section is blocking and being blocked by another active synchronized section that is yielded. This document aims to create a minimal synchronization system that can be repurposed for any concurent synchronization.  

> Comment: While the interfaces functionality is very similar to the flb_mutex api, the interface's methods are geared towards simplicity rather than consistancy with the flb_mutex api. The api could be reformatted to match flb_mutex (flb_async_mutex) if desired, or another layer could be added to make an flb_async_mutex, which would do the same thing as flb_mutex, except that the async mutex blocks by yeilding to the event loop rather than busy waiting.

## Artificial Synchronization Mechanism

The proposed synchronization interface is `coroutine_synchronizer`. Coroutine Synchronizer has only two main methods, `synchronize(synchronizer, execution_channel)` and `release_channel(synchronizer, execution_channel)`. Any code between synchronize(..., execution_channel) and release_channel(..., execution_channel) can be guaranteed to have only one coroutine and thread running it at a given time. This is useful for critical sections that may call `coro_yield()`.

On initializing a cloudwatch api PutLogEvents request for a given stream, `synchronize(..., cloudwatch_stream_name)` can be called to prevent any other threads or coroutines from entering the critical section. If another coroutine calls sychronize, it is suspended and added to a fifo queue structure that will allow for it to be resumed when the critical section of code is finished. Within the critical section, the code is free to make as many network calls and coro_yeilds as it desires without jepordizing deadlock or a race condition. At the end of the critical section after cloudwatch api's PutLogEvents request is completed, `release_channel(..., cloudwatch_stream_name)` is called, which queues the resuming of zero or one waiting coroutine.

This way, cloudwatch_logs plugin can guarantee only one PutLogEvents request occurs on a given log stream at a given time and the appropriate sequence token can be provided from the prior request on each new request.

The following sections of the document outline the interface for and implementation of this synchronization mechanism.

# Coroutine Synchronizer Specs

## Synchronizer API
Synchronizer api provides a simple interface for creating non-parallelized blocks of code that run sequentially.  
A synchronizer can be thought of conceptually as a lock that is made to work well with the asynchronous event loop.  
On waiting to enter a critical section of code with a synchronizer, instead of busy waiting, the active coroutine yields to other coroutines until the lock can be obtained.

**synchronizer_synchronize**
```
int synchronizer_synchronize(struct synchronizer *synchronizer, char *execution_channel); [Async blocking]
```
Bind active coroutine to an execution channel and asynchronously block if the channel is already in use.  
Multiple execution_channels can be used by the same synchronizer.

Returns `FLB_SYNCHRONIZER_ASYNC_BLOCK` if has blocked and and `FLB_SYNCHRONIZER_NON_BLOCK` if has not blocked

**synchronizer_release_channel**
```
synchronizer_release_channel(struct synchronizer *synchronizer, char *execution_channel); [Non blocking]
```
Release execution channel, only if coroutine has previously synchronized on that channel.  
Will trigger another coroutine that has blocked on that channel to resume.

**synchronizer_create**  
**synchronizer_destroy**  
```
struct synchronizer *synchronizer_create(); [Non blocking]
void synchronizer_destroy(struct synchronizer *synchronizer); [Non blocking]
```
Create and destroy the synchronizer context.

## Synchronizer State
```
/* Typescript Notation */

/* High level synchronizer state */
type synchronizer {
    execution_channels: Array<{
        bin_name: char *,
        coro_exec: struct flb_coro
    }>,
    refrigerator: struct refrigerator*,
    mutex: pthread_mutex_t
}
```
```
/* C Struct Notation */

/* High level synchronizer state */
struct synchronizer {
    struct execution_channel *execution_channels;
    struct refrigerator *refrigerator;
    pthread_mutex_t mutex;
};

/* Manage separate execution channels */
struct execution_channel {
    char *bin_name;
    flb_coro coro_exec;
};
```

## Synchronizer Implementation
**synchronizer_synchronize**
```
int synchronizer_synchronize(struct synchronizer *synchronizer, char *execution_channel); [Async blocking]
```
Depends on:
- `refrigerator_freeze`

Algorithm:
- Lock synchronizer
- Checks if `execution_channel` with `bin_name` == `execution_channel` exists.
    - if not exists, create and add to `execution_channel` list as `coro_exec`; return `FLB_SYNCHRONIZER_NON_BLOCK`;
    - if exists, continue;
- Calls `refrigerator_freeze(synchronizer->refrigerator, execution_channel)`
- Set `coro_exec` to the active coroutine [after unfreeze] 
- Unlock synchronizer
- Return `FLB_SYNCHRONIZER_ASYNC_BLOCK`

Notes:
- Uses synchronizer lock to lock the synchronizer struct, refrigerator obtains refrigerator lock. This may be inefficient and it may be better to share a lock between the two structures, ie expose the refrigerator lock.

**synchronizer_release_channel**
```
int synchronizer_synchronize(struct synchronizer *synchronizer, char *execution_channel); [Async blocking]
```
Depends on:
- `refrigerator_unfreeze_from_bin`

Algorithm:
- Obtain synchronizer lock
- Checks if corresponding `execution_channel`'s `coro_exec` is the active coro.
    - if not active -> return -1 or error code
    - if active -> continue
- Set `coro_exec` on `execution_channel` to `NULL`
- Call `refrigerator_unfreeze_from_bin(synchronizer->refrigerator, execution_channel)`
- Release synchronizer lock
- Return 0 or success code

# Coroutine Refrigerator Specs
Coroutine refrigerator provides a lower level interface to suspend coroutines and queue coroutine resumes. There is no concept of active coroutines in the coroutine refrigerator. Only inactive coroutines are freezed to refrigerator bins, and can be resumed by calling unfreeze on the containing bin. On calling unfreeze, only one coroutine from the specified bin will be queued for resume. Synchronizer API adds on top of this layer logic to enforce one active coroutine. Synchronizer API uses refrigerator to freeze and unfreeze coroutines.  

## Refrigerator API

**refrigerator_freeze**
```
void refrigerator_freeze(struct refrigerator *refrigerator, char *bin_name); [Async blocking] (utill unfreeze called)
```
Any coroutine can call `refrigerator_freeze()` to suspend its execution until refrigerator_unfreeze_from_bin is called by another coroutine.  
The frozen coroutine will be stored in a first in first out bin which is used as a handle to signal resume.

This is an async blocking call. The call will block and yield to other execution on the event loop until the coroutine is unfrozen by `refrigerator_unfreeze_from_bin()`

**refrigerator_unfreeze_from_bin**
```
flb_coro refrigerator_unfreeze_from_bin(struct refrigerator *refrigerator, char *bin_name); [Non blocking] (signals appropriate thread to resume coroutine when ready)
```
Signals one coroutine from the selected bin, by first in first out ordering, to resume execution.  
This is a non-blocking call. It does not resume the coroutine's execution immediately but rather queues the coroutine to be resumed at the next availiable time.  

Coroutines are guaranteed to be resumed on the thread they were originally executed on.

`refrigerator_unfreeze_from_bin()` can be called on any thread regardless of the signalled coroutine's execution thread.  

Returns the coroutine that was unfreezed.

**refrigerator_lock ***(deprecated)*****  
**refrigerator_unlock ***(deprecated)*****
```
int refrigerator_lock(struct refrigerator *refrigerator) [Sync blocking]
int refrigerator_unlock(struct refrigerator *refrigerator) [Non blocking]
```
Neither of these functions need to be used along with `refrigerator_freeze()` or `refrigerator_unfreeze_from_bin()` as both functions will lock and unlock themself.

Refrigerator lock and unlock functionality adds complexity that may not be needed. May only be required if client wishes to view the refrigerator structs internal contents, and correspondingly act on that information. If locking is not enabled, then there would be no guanrantee of state
refrigerator_lock 

## Refrigerator State
```
/* Typescript Notation */

/* High level refrigerator state */
type IRefrigerator {
    bins: Array<{
        name: char *
        coroutine_records: Array<
        {
            coro: flb_coro *,
            thread_id: int
        }
        >
    }>
    channels: Array<{
    {
        thread_id: int,
        channel: flb_pipefd_t[2] /*  [read, write] */
    }
    }>,
    mutex: pthread_mutex_t
}
```
```
/* C Struct Notation */

/* High level refrigerator state */
struct refrigerator {
    struct bin *bins;
    struct monitored_channel *channels;
    pthread_mutex_t mutex;
};

/* Manage coroutines by bin catigory */
struct bin {
    char *name;
    struct coroutine_record *coroutine_records;
};

/* Associate coroutine with thread_id, original execution thread */
struct coroutine_record {
    int thread_id;
    struct flb_coro *coro;
};

/* Associate thread_id with channel */
struct monitored_channel {
    int thread_id;
    flb_pipefd_t ch_resume_signal;
};
```

## Implementation
The implementation of coroutine refrigerator involves creating a callback event pipe for each thread. On calling unfreeze on a bin, one coroutine from the selected bin is identified and the corresponding thread is looked up via the coroutine_record and monitored_channel lists, and the coroutine is written to the callback event pipe for that thread. The data in the pipe triggers the event pipe's callback, which reads from the event pipe the coroutine that is to be resumed, and calls coro_resume in place. Since we write coroutines to event pipes that exist on particular threads, the coroutine is guaranteed to be resumed on the thread coresponding to the pipe of our choosing, which determined by the coroutine_record and monitored_channel list, and is the resume coroutine's original thread. Further implementation details are omitted but can be added if needed in the future.

## Note
In the above "Refrigerator State" lists are written as array pointers for simplicity. This will likely be changed in most cases to mk_lists for expansability.

## Locks
Three locks are required. 
```
static pthread_mutex_t mutex_synchronizer_init;
synchronizer->mutex;
refrigerator->mutex;
```
The mutex_synchronizer_init lock should exist as a static variable accessible by the code responsible for initializing the refrigerator.  
Once initialized, the synchronizer and refrigerator API will handle all locking and unlocking.

Synchronizer will obtain its mutex any time the synchroizer state is observed or modified.
Refrigerator will obtain its mutex any time the refrigerator bin state is observed or modified.

**Comment by PettitWesley** [comment]
👏 👏  Great writeup!

Feedback:

1. nit 1: CW API is PutLogEvents, not PutLogs
2. Nit 2: I'm not really convinced there's a need for the separate "refrigerator" API, it feels like it could just be part of the synchronizer?
~~nit 3: I think the fact that the synchronizer has a context that has to be created might not be perfectly ideal, it'd be better if it was a global utility somehow:~~

> synchronizer_create
> synchronizer_destroy
> struct synchronizer *synchronizer_create(); [Non blocking]
> void synchronizer_destroy(struct synchronizer *synchronizer); [Non blocking]
> Create and destroy the synchronizer context.

~~So this means that each plugin instance must hold its own synchronizer, and thus, synchronization is within a plugin instance. This is fine... today we use sync IO for synchronization and its only within each plugin instance (if you enable workers). There'd be no way to sync up multiple instances that are trying to write to the same stream and group. Having a global synchronizer with a global context would be more complicated of course.~~

Never mind, the above doesn't work right since each output instance with workers is sort of like its own event loop?

**Comment by matthewfala** [comment]
Resolved with an alternate implementation: the Sync Scheduler: https://github.com/fluent/fluent-bit/pull/6413, which CloudWatch opts into.
