### ISSUE TITLE
Latest stable release URL

### ISSUE THREAD

**Issue by adichiru** [fluent/fluent-bit#529]
Hello,

This is more a question or idea of improvement:

I'd like to be able to easily download the sources for the latest stable release from a build pipeline I have created for my infrastructure; for example from a URL like https://github.com/fluent/fluent-bit/latest that would always bring the latest tar.gz file.

I could not find the "Latest release" button/link on your Github releases page. Maybe it is a good idea to activate this feature. Take a look here: https://stackoverflow.com/questions/24827437/github-latest-release-button-capability

While I could come up with some less elegant solution using the Github API and grepping and ordering numbers and strings, the above button may streamline the process.

Thanks,
Adi

**Comment by edsiper** [comment]
done!
