### ISSUE TITLE
Linker error in Alpine 3.13.2 for fts library

### ISSUE THREAD

**Issue by akioyamamoto1977** [fluent/fluent-bit#5311]
## Facing linker errors in Apline 3.13.2 with fts & fts-dev installed

**Description**
We are targeting to use fluent-bit in a Docker image of Alpine 3.13.2.
According to our situation, we are using a own made fluent-bit plugin so we need fluent-bit core built from source code with some FLAGS (-DFLB_DEBUG=On -DFLB_PROXY_GO=On) for cmake.

after a successful run of cmake, make fails with below outputs.
```
[ 87%] Linking C executable ../bin/fluent-bit
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ../library/libchunkio-static.a(cio_utils.c.o): in function `cio_utils_recursive_delete':
/usr/local/src/fluent-bit/lib/chunkio/src/cio_utils.c:55: undefined reference to `fts_open'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/local/src/fluent-bit/lib/chunkio/src/cio_utils.c:62: undefined reference to `fts_read'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/local/src/fluent-bit/lib/chunkio/src/cio_utils.c:92: undefined reference to `fts_close'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/fluent-bit-bin.dir/build.make:341: bin/fluent-bit] Error 1
make[1]: *** [CMakeFiles/Makefile2:6837: src/CMakeFiles/fluent-bit-bin.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
bash-5.1#
```

Does anyone know the way to link to fts library ?

**To Reproduce**
Make a Docker image as below.
```
FROM alpine:3.13.2

# port
EXPOSE 80

ARG FLUENTBIT_REPO=https://github.com/fluent/fluent-bit.git
ARG FLUENTBIT_BRANCH=master

# Install APK Modules (including dependencies for other apps)
RUN apk --update add openjdk11 bash curl sudo openssl openssl-dev php8-fpm php8-mbstring php8-curl tzdata git lua lua-dev make unzip nginx redis gcc g++ libc-dev maven php8-pdo_pgsql php8-openssl rsyslog php8-dom php8-xml php8-json cmake dnsmasq go flex bison fts fts-dev file python3 autoconf

<omitting running part>
```

And obtaininig the fluent-bit source code with git command as below.
```
git clone https://github.com/fluent/fluent-bit.git
```

Then go into the fluent-bit folder and cmake & make as above,

** My Environment **
alpine:3.13.2
fts-1.2.7-r1 x86_64 {fts} (BSD-3-Clause) [installed]
fts-dev-1.2.7-r1 x86_64 {fts} (BSD-3-Clause) [installed]

fluent-bit 1.9.3 (source code set from the github https://github.com/fluent/fluent-bit.git master branch)

**Comment by patrick-stephens** [comment]
Note https://docs.fluentbit.io/manual/installation/docker#why-there-is-no-fluent-bit-docker-image-based-on-alpine-linux

**Comment by akioyamamoto1977** [comment]
@patrick-stephens 
Thank you very much for your quick response. I see the reason!!
