### ISSUE TITLE
fluent-bit siliently stops pushing to outputs some time after a retry-able error

### ISSUE THREAD

**Issue by wc-s** [fluent/fluent-bit#5312]
## Bug Report

**Describe the bug**

We're migrating to fluent-bit, and we run fluent-bit as a Daemonset in kubernetes, pushing to both s3 and elasticsearch. In our cluster there's an imperfection - when a fluentbit pod spins up, depending on a race condition, it may or may not have AWS credentials fully loaded initially (but it eventually will). This means sometimes there'll be "s3 PutObject Access Denied" error, but the PutObject will succeed a bit later. That's fine. What's not fine is that, sometime after such an error, fluent-bit will suddenly and silently stop pushing logs at all to both s3 and elasticsearch.

We've consistently observed this issue happening in our fluentbit pods. A step-by-step:
- fluent-bit pod starts up
- It will correctly push stuff to elasticsearch
- If it's one of the pods that doesn't have AWS creds ready, then the first time it tries to upload to AWS, it will run into an Access Denied error
- After such an Access Denied error, it will continue to correctly push stuff to elasticsearch for a while
- It will also have some log lines indicating it has correctly pushed objects up to s3 (meaning, by this time the Pod has been correctly loaded with the AWS credentials)
- But after a while, it will silently stop pushing anything - neither to elasticsearch nor to s3
- This "silent failure" is not reflected in either the `output_error` or the `retries_failure` metrics that we gather in prometheus. Those metrics always stay at 0 even during the time periods where this definitely happened. Also it doesn't cause the pod to terminate. So it will just silently sit there, doing nothing, without giving any indication for us to monitor and alert on.

**To Reproduce**

We ourselves can consistently observe it in our clusters. For other people to reproduce, I imagine the same s3 issue can be emulated by making the pod use a role that does not have the right AWS permissions to write to the bucket, and then after running the pod for a while, to adjust the AWS IAM permissions with the correct bucket credentials.

**Expected behavior**
It should not silently fail to push. At least we need some `error` metrics to use in the healthcheck so that we can alert and recover.

**Logs and Screenshots**
We enabled verbose logging and have captured the following example (the log is sanitized to remove actual application log lines and object names):  
[fluent-bit.log](https://github.com/fluent/fluent-bit/files/8490553/fluent-bit.log)

- When the fluent-bit pod just starts up, it can correctly push to elasticsearch, for example in log lines 432 - 433
- Then, it'll run into the "s3 access denied" error, in lines 2321 - 2322
- After that, it'll continue to successfully push to elasticsearch, for example in lines 2820 - 2821
- (In our other cases but unfortunately not in captured here, we also have here log lines of fluent-bit successfully uploaded objects to s3.)
- However, the last successful `[output` push is around line 6000; after that, there's no more pushing attempts
- This is despite the fact that there definitely are new logs to be pushed. For example, in line 19001, we can see fluent-bit start tailing the log of a pod with hash `77h57`. We have a screenshot of that pod definitely producing logs - attached below.
- On the server, we can also see the files `xxx.flb` continue to accumulate.
![application-pod_has-logs-sanitized](https://user-images.githubusercontent.com/15850705/163427788-46e24793-6e7a-4e0a-8d53-b92234191761.png)

**Your Environment**

* Version used: 1.9.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): k8s v1.21.8
* Server type and version: AWS EC2
* Operating System and version: `Flatcar Container Linux by Kinvolk 2905.2.6 (Oklo)`
* Filters and plugins:
```
    [SERVICE]
        Flush 5
        Grace 30
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        storage.path /var/log/fluent-bit-test//storage
        storage.sync normal
        storage.checksum off
        storage.backlog.mem_limit 20M
        storage.metrics on

    [INPUT]
        Name            tail
        Path            /var/log/containers/*_test_*.log
        Parser          docker
        Tag             kube.*
        Path_Key        log.file
        mem_buf_limit   10MB
        storage.type    filesystem
        Rotate_Wait     60
        DB              /var/log/fluent-bit-test/log.db
        DB.sync         normal
        DB.locking      true
        DB.journal_mode WAL
        Read_from_Head  true

    [FILTER]
        Buffer_Size 128k
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Labels On
        Annotations On
        Kube_Tag_Prefix kube.var.logs.container.

    [FILTER]
        Name modify
        Match kube.*
        Rename log msg

    [FILTER]
        Name modify
        Match kube.*
        Remove date
        Remove @timestamp

    [FILTER]
        Name modify
        Match kube.*
        Set cluster development

    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/fixKubernetesInfo.lua
        call transform

    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/fixErrorObject.lua
        call transform


    [OUTPUT]
        Name s3
        Match *
        bucket mybucket
        region eu-west-1
        store_dir /var/log/fluent-bit-test//s3
        canned_acl bucket-owner-full-control
        s3_key_format /year=%Y/month=%m/day=%d/hour=%H/namespace=test/$TAG[4]_$UUID.json.gz
        s3_key_format_tag_delimiters ._
        compression gzip
        use_put_object True
        total_file_size 50M
        upload_timeout 5m
        auto_retry_requests True
        Retry_Limit False
        workers 1



    [OUTPUT]
        Name es
        Match *
        Host redacted.com
        Port 1234
        HTTP_User myuser
        HTTP_Passwd verysecret
        Index app-logs
        Include_Tag_Key On
        Tag_Key log.tags
        Time_Key log.read_at_time
        tls On
        tls.verify On
        Retry_Limit False
        Trace_Error On
```

**Comment by yackushevas** [comment]
Similar issue with output_kafka, but so far I haven't been able to find anything that would somehow indicate a problem in the debug log.
The problem was in 1.8 and exists now in 1.9, I'm not sure about 1.7 and older.

**Comment by andrewnazarov** [comment]
Recently we've started experiencing kind of a weird issue when fluentbit stops sending logs. During this time we don't see any input or output traffic on the Grafana dashboard. However, we do see retry errors metrics. The errors we see in logs are known to us and we are ok with them. These are mapping errors only for one index out of many and for one output configuration out of two. It really strange that after a while fluentbit just stops any activity. The only thing we can think of is this retry error since there is nothing more in logs (we tried debug too). We are wondering if fluenbit has any threshold/retry budget after which it just stops the operation.

This is quite annoying and we have to restart fluenbit pods to make it work again.

**Comment by burkesbi** [comment]
Similar problem here; logging to elasticsearch only, running on aws k8s 1.21.

We upgraded fluentbit recently from 1.8.8 to 1.8.13 and encountered this issue. Restarting all the pods in the cluster would cause the logs to properly flow though, but then it would silently drop logs over time.

Nodes with fluentbit running on them would have their pods regularly sending logs, but they wouldn't arrive in elasticsearch, and there were no errors at all in fluentbit's k8s logs, just the original 5 lines of start up/copyright text.

Not all nodes in a cluster would have fluentbit fail in this way, and it seemed to be gradual process, you'd see a nice graceful curve down over 24 hours for a cluster that should have had a constant amount of logs coming in.

Won't have a chance to dig in further for a while, but this might give a starting point to working out what change may have caused issues.

**Comment by andrewnazarov** [comment]
Tried 1.7.9 - same thing.

**Comment by andrewnazarov** [comment]
It seems that we can see the correlation between the retry/failed ratio and the responsiveness of a fluentbit worker. We tried to deal with Elasticsearch errors that weren't crucial for us and decrease the amount of errors we have in logs. And it seems it helped. However, we would like to see either the error in fluentbit that indicates that it stops processing logs or a continuation of sending logs no matter what the retry ratio is.

As I mentioned earlier only one index out of many had errors and only one output out of two.

I've attached the screenshot with a Grafana dashboard with fluentbit metrics. Arrows indicate time frames when no logs were sent even though fluentbits were working.

<img width="1622" alt="Screenshot 2022-04-25 at 09 06 33" src="https://user-images.githubusercontent.com/11255710/165030184-5dae94e9-95c7-47f0-8d45-df723d788260.png">

**Comment by aliazlan-t** [comment]
We are seeing same issue in ver 2.0.8 with splunk backend.

**Comment by leonardo-albertovich** [comment]
It seems like this has been stalled for far too long so we need to ensure we're on the same page.

Could you folks please test fluent-bit 2.1?

We will need to gather context information from your particular cases and put together a reproduction case so one of our team members can work on the issue.

**Comment by Coalmine-Canary** [comment]
I am still seeing this issue on 2.1.4

Looking at fluent-bit's metrics server, all inputs and filters are processing records, but the output plugin isn't (it isn't dropping them either, just 0 proc_records and a number of retries that doesn't change. )

I am using the forward output plugin to send to fluentd. The issue isn't happening on all pods, and is quite inconsistent. 

I used tshark to look at traffic on the node and found that fluent-bit is doing no requests at all, all I can see is queries to the metrics server. Not even any DNS requests, it seems to have just stopped

**Comment by kjumin** [comment]
Is there any update on this? We just upgraded tot 2.2.0 from 1.8.13 and started experiencing this issue with UDP traffic originating from our firewalls. 

Traffic flows normally until it just stops. No traces in the logs whatsoever. We use TCPdump to verify what goes in and what goes out of the fluentbit container. Traffic is coming in, like it should, but it doesn't leave the container.
