### ISSUE TITLE
FluentBit 1.9.0 appears to cause high CPU utilisation on IIS web server (possibly)

### ISSUE THREAD

**Issue by marketier** [fluent/fluent-bit#5327]
I have a .net website running in IIS on two Windows Server 2016 instances. This app generates it's own logs using log4net to the D: drive on each instance. Logging level has been set to ALL for many months. FluentBit tails and forwards these logs to New Relic using the New Relic output plugin. 

The FluentBit forwarding was enabled on Monday last week and on Thursday we started seeing high CPU utilisation on both web servers. The worker process associated with the site was fluctuating between 50% to 100%, and staying at 100% for long periods causing slow response times on both servers. The FluentBit service/process appeared to be running within normal CPU and memory ranges compared with previous days.

I stopped the Fluentbit service and changed the log4net logging level from ALL to INFO and restarted the website in IIS on both instances. The CPU has returned to normal levels on both web servers.

Can Fluentbit cause an IIS worker process to overload the CPU as the website writes logs to disk? Could it be that Fluentbit is holding onto logs as they are being written causing IIS to keep processes running for longer?

This is just guess work but any guidance would be appreciated.

**Reproduce**

- Steps to reproduce the problem:

Install IIS on Windows Server 2016.
Install Fluentbit 1.9.0 on the same server.
Add the following configuration to fluent-bt.conf

```
[INPUT]
    Name tail
    Tag MyWebsite
    Path D:\Website\Log*.log
    Skip_Empty_Lines On
    Skip_Long_Lines On
    Ignore_Older 1h

[FILTER]
    Name modify
    Match MyWebsite
    Add hostname ${COMPUTERNAME}
    Add application MyWebsite
    Add category iis
    Add processhost web

[FILTER]
    Name grep
    Match *
    Regex log (?i)warn|error|exception|critical|warning|err|debug|address|request|user|value
    Exclude log /.*Catalog.*/

[OUTPUT]
    Name newrelic
    Match *
    licenseKey somelicencekey
```

**Expected behavior**

Fluentbit log forwarding should not impact IIS worker process CPU utilisation.

**Your Environment**

* Version used: 1.9.0
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): IIS
* Server type and version: 
* Operating System and version: Windows Server 2016
* Filters and plugins: Tail and New Relic Output Plugin

**Comment by patrick-stephens** [comment]
Could this be related to https://github.com/fluent/fluent-bit/issues/4711? I think @leonardo-albertovich was investigating that.

**Comment by leonardo-albertovich** [comment]
It doesn't sound related to it. Would you be able to use a profiler to take samples with and without fluent-bit running in background? Have you monitored resource usage? I'm not aware of any problems related to tailing high throughput log files but I would start with those two at least.

**Comment by marketier** [comment]
@leonardo-albertovich Thanks for your feedback. What's a good profiler to use in this case? Also, I will attempt to recreate some load on the web server as that's when we started seeing 100% CPU usage. It's been a few days since we stopped the Fluentbit service forwarding logs to New Relic and the web server has been behaving and performance at normal levels. 

When the issue occurred, this is what we were seeing in New Relic and on web servers, before stopping Fluentbit at around 10.15 am (BST). 

CPU
![image](https://user-images.githubusercontent.com/38507513/164650510-546bff42-7927-4fb9-944b-f83006796ffd.png)

Memory
![image](https://user-images.githubusercontent.com/38507513/164650707-25bf76f9-5f2e-4275-84f6-5f83af124d5e.png)

Load average
![image](https://user-images.githubusercontent.com/38507513/164650760-edd19e49-5f7a-4f6a-87be-5637bedff506.png)

Network In (packets/s)
![image](https://user-images.githubusercontent.com/38507513/164651230-af1dc53c-f18f-4483-8522-c8b3d22d3f82.png)

Network Out (packets/s)
![image](https://user-images.githubusercontent.com/38507513/164651271-8515ede8-b88f-47fa-af30-c770a893b39a.png)

**Comment by leonardo-albertovich** [comment]
You don't happen to have disk stats for that period right? I'm definitely not an expert on that but was wondering if this could be related to IOPS or something like that. As for profiling, I'm not familiar either, the only one I know is dotTrace.

The one thing I'd be most interested in initially would be measuring the time spent in the log4net functions both with and without fluent-bit running which overlaps with what could be obtained through the resource monitor.

Once again, these are just ideas, if you manage to reliably reproduce the issue let me know, I'd be happy to help.

**Comment by marketier** [comment]
@leonardo-albertovich Yes, disk metrics are available. 

Below metrics are from 8.30am on Apr 21, a couple of days after stopping Fluentbit and performance back to normal:
![image](https://user-images.githubusercontent.com/38507513/164757735-632759ce-5ae4-4d89-839b-29305999024c.png)

The below shows metrics for when the incident occurred at 8.30am BST on Apr 19 (as above but showing the entire dashboard):
![image](https://user-images.githubusercontent.com/38507513/164757451-9e4f81a8-7e0c-42df-99cb-f36ee558611f.png)

For comparison, these are the metrics from 8.30am on Apr 12, day after deploying Fluentbit with no issues reported:
![image](https://user-images.githubusercontent.com/38507513/164758071-aba4adb1-9611-4f68-86b7-796301ab5cf8.png)

I'll keep you posted about my progress with the profiler and reproducing the issue.

**Comment by leonardo-albertovich** [comment]
That'll be greatly appreciated. I don't see any clear reasons for it in those graphs, there are slight variations but nothing obvious (at least to me) so I guess it'll be a matter of trying to reproduce it.
