### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by korenlev** [fluent/fluent-bit#5329]
## Bug Report

**Describe the bug**
docker build from 'dockerfiles':

Removing intermediate container e2d17ffbc15b
 ---> 1a5928c4d0ee
Step 15/46 : RUN cmake -DFLB_RELEASE=On           -DFLB_TRACE=Off           -DFLB_JEMALLOC=On           -DFLB_TLS=On           -DFLB_SHARED_LIB=Off           -DFLB_EXAMPLES=Off           -DFLB_HTTP_SERVER=On           -DFLB_IN_EXEC=Off           -DFLB_IN_SYSTEMD=On           -DFLB_OUT_KAFKA=On           -DFLB_OUT_PGSQL=On           -DFLB_NIGHTLY_BUILD="$FLB_NIGHTLY_BUILD"           ..
 ---> Running in 19ed7c342326
CMake Error: The source directory "/tmp/fluent-bit" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
The command '/bin/sh -c cmake -DFLB_RELEASE=On           -DFLB_TRACE=Off           -DFLB_JEMALLOC=On           -DFLB_TLS=On           -DFLB_SHARED_LIB=Off           -DFLB_EXAMPLES=Off           -DFLB_HTTP_SERVER=On           -DFLB_IN_EXEC=Off           -DFLB_IN_SYSTEMD=On           -DFLB_OUT_KAFKA=On           -DFLB_OUT_PGSQL=On           -DFLB_NIGHTLY_BUILD="$FLB_NIGHTLY_BUILD"           ..' returned a non-zero code: 1

**Comment by patrick-stephens** [comment]
Which branch, etc. are you using? The container builds are done nightly, on every master push as well so not sure why they would fail.

Did you run from the repository root?

**Comment by korenlev** [comment]
Not running from root, spent a day trying to debug closing this one
