### ISSUE TITLE
Using cloud storage for database doens't work

### ISSUE THREAD

**Issue by Monnoroch** [fluent/fluent-bit#533]
I run fluent-bit as a DaemonSet in a Kubernetes cluster. `tail` and `systemd` inputs that I use have a `db` parameter that allows me to specify the file name for the SQL database that stores file offsets. The official documentation advises me to store this file on each host in `/var/log/`. However, this is not very reliable as data might get lost or corrupted, so instead I want to use cloud storage to store this file. This scenario is not supported right now. And here's why.

Because fluent-bit is ran as a daemonset it has multiple pods, one per machine. And now I have several "options":

1. I create one persistent volume for each pod and each pod uses a different volume. This option is not supported, because I can't mount different persistent volumes to different pods in a daemonset, only a statefulset. Making fluent-bit a statefulset with appropriate affinity is a maintenance burden because if the number of nodes change you need to remember to manually increase the number of replicas. This will never work in big clusters.
2. I create a single persistent volume and mount it in all pods and each pod creates a separate file. In this case however I have no way to configure fluent-bit to create files with different names on different instances, so it's also not supported.
3. And finally, I could use a single volume with a single file, but the database schema would be able to distinguish between files with the same name on different nodes. This case is not supported for two reasons:
  - Right now it doens't do that.
  - Even if it did, the database file would be asynchronously manipulated by multiple nodes and AFAIK this is not supported either.

In conclusions, there's no way to store the database in a cloud (or any other network using) storage and this is a significant problem if you want reliability.

Right now, my feeling is that the best solution would be to support using remote databases like CocroachDB or PostgreSQL for cache and support an instance-id using a done IP address somehow. The next best thing would be to be able to configure different names for this file in different pods, using the node IP address.

**Comment by StevenACoffman** [comment]
Can you not take advantage of [dynamic provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) with each Daemonset Pod?

**Comment by Monnoroch** [comment]
I do provision volumes dynamically, yes. But there's no way to use a different claim for individual pods in a daemonset, this feature is only available for statefulsets.

**Comment by StevenACoffman** [comment]
Please correct me if my understanding is incorrect. I assume the logs you are tailing are being produced to a cloud storage (e.g. EBS volume in AWS), and if the ephemeral kubernetes worker node (e.g. EC2 instance in AWS) is terminated and replaced, you wish to have similarly reliable storage of the fluent-bit database file, or the logs may be re-processed by fluent-bit and duplicates will appear in your output sink (e.g. ElasticSearch, Kafka, etc.). I assume your output sink does not de-duplicate based upon the log data identifiers.

I know many fields in the fluent-bit configuration can be replaced based on Environment variables (`${DB_FILE_NAME}`). I am not sure if the SQLite database file name is one of them. An init container could set an environment variable based on some unique metadata, and that could be the referenced prefix of the name of the SQLite database file to keep track of monitored files and offsets.

**Comment by Monnoroch** [comment]
Yes, this is exactly what I want, though I actually am building a cluster on my own hardware. Supporting environment variables would definitely help, though it's not entirely clear how would one prefix the file name. Using the pod host name/ip doesn't work because it's unstable. Using the node host name/ip is better for private hardware, but maybe not so much on public cloud when the same hard drive can be re-mounted on a different machine or the IP address can change on restart.

**Comment by StevenACoffman** [comment]
I am still not sure I understand. So if the persistent volume you are using for the fluent-bit SQLite database file is potentially shared between multiple nodes (e.g. NFS, EFS, etc.) you want that file name identified in a way that matches the node-specific log file persistent volume (e.g. EBS) it was tailing. The init container could look that up for you, correct?

**Comment by StevenACoffman** [comment]
You could have the DaemonSet include a sidecar container that periodically copies the fluent-bit SQLite database file to a durable location (s3) matching the node log volume unique identifier. The the init Container could also restore that SQLite database file backup. Then you wouldn't really need to retain the persistent volume at all.

Honestly, a lot of these headaches are solved by de-duplicating in your log pipeline after log shipping (in ElasticSearch, Kafka, whatever).

**Comment by Monnoroch** [comment]
Indeed it is, but the point of the database is to optimize and it's a good thing to do in any case. And right now it doesn't work on "discless" machines.

**Comment by StevenACoffman** [comment]
Ah, that makes more sense now. You are netbooting raspberry pi's (or some such),  but you chose a shared volume for all nodes to pool logs, instead of a volume per node. If the node has it's own unique log volume, you can just keep the SQLite database file backup in that same directory, with a non-unique name. When the node is restarted, everything just picks up where it left off.

**Comment by Monnoroch** [comment]
> You are netbooting raspberry pi's 

That's not quite true, I have dedicated storage machines with a distributed FS agents and other "app" machines don't have any hard drives (well, almost, only for the linux to boot and some space to store temp files that don't survive reboots). This is done so that it's definitely 100% not important to be careful about rebooting/replacing these "app" servers which are the majority of our hardware. So any file I have on a node doesn't survive reboots and thus I want to put the fluent-bit cache in my distributed FS which is mounted as a persistent volume[s]. 

> instead of a volume per node

I don't even have an option of having a volume per node because daemonsets don't support claim templates, only claim volumes.

**Comment by StevenACoffman** [comment]
Since fluent-bit already mounts the log volume it is tailing, why can't you choose to put the SQLite database file backup in that same directory on the same distributed FS, so when you reboot the server, they stay married together?

**Comment by Monnoroch** [comment]
Yep, that's what I'm doing right now: making an exception for the log dir so it actually does survive reboots. Not something I'm super happy about though.

**Comment by StevenACoffman** [comment]
How well does Fluent-bit log shipping keep up with log production in your setup? Also, do you try to drain nodes before restarting hardware?

**Comment by Monnoroch** [comment]
Very well I would say. Though I process logs with fluentd and only use fluent-bit as a shallow sender, so it's basically network bound. And of course nodes are NORMALLY drained, but you know, things not always go very well. 

Anyway, I'm not saying that this is a huge problem, just a case that might be worth keeping in mind. Of course I myself found ways around it, but I think it's worth the effort to at least support env variables in DB file names.

**Comment by edsiper** [comment]
@Monnoroch you can use an environment variable to define any parameter in the configuration.

**Comment by edsiper** [comment]
Final solution for your use case is to store SQLite database file in a persistent path of the node (/var/log works), using a remote database to keep offset of files is not ideal since it would be a pain in high traffic log nodes.

Closing this as fixed, in any case if you have some pending question feel free to post it.
