### ISSUE TITLE
Does fluent bit support token refresh in kubernetes plugin

### ISSUE THREAD

**Issue by jyotimahapatra** [fluent/fluent-bit#5332]
## Bug Report

Hi 👋 . I'm a kubernetes cluster operator in AWS EKS. While looking at some of the call patterns from `UserAgent` [Fluent-Bit](https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/plugins/filter_kubernetes/kube_meta.c#L389), i realized that fluent bit kubernetes plugin [does not refresh the token](https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/plugins/filter_kubernetes/kube_meta.c#L167-L172) periodically. Starting kubernetes 1.21, BoundServiceAccountTokens became enabled by default in kubernetes. This means that tokens mounted on the pod are refreshed at least every day and the clients must refresh the token in the calls to apiserver.

I'm not sure if my understanding around the token refresh is accurate, since i am not familiar with fluent bit code and C in general. I'd appreciate guidance around it. If the assumption is correct, with guidance I can help create a PR to fix the token refresh too :)

**Comment by PettitWesley** [comment]
Clarification: Currently in Kubernetes a grace period for the expired token can be set, for example in EKS we set it to be 90 days, which is probably why only a few customers have complained about this. In a future version of k8s, the grace period may be removed. So this is a bug which will become a worse bug in the future.

**Comment by PettitWesley** [comment]
Probably the way this should work in the code should be to store the token read time with the token, and refresh it after one day. The refresh time can be made user configurable. That's my proposal for the implementation.

**Comment by novegit** [comment]
https://github.com/fluent/fluent-bit/pull/4487 solves it.
