### ISSUE TITLE
Fluent Bit v.1.9 - Windows metrics request

### ISSUE THREAD

**Issue by hisa-tanaka** [fluent/fluent-bit#5337]
**Is your feature request related to a problem? Please describe.**
As we started to use and having the server metrics through fluent bit is great to have. I would like to use the metrics for the infrastructure monitoring / troubleshooting purpose by getting metrics related to memory on top of what we get from the current fluent bit v.1.9.1. (some cpu related metrics today).
Also the metrics will be utilized for performance engineering purpose as well.

**Describe the solution you'd like**
\Memory\Available Mbytes
\Memory\Pages/sec
\Paging File(_Total)\Usage
\Memory\Free System Page Table Entries

Thank you very much for your attention.

**Comment by LeoWinterDE** [comment]
Same as #4026

**Comment by kcsun33** [comment]
I need this function too. Which version of Fluent-bit will be released?
