### ISSUE TITLE
Fluent Bit v1.9 or future release: Migrate to use from NSIS to WiX for flexible installation phases and restrict permissions

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-bit#5338]
**Is your feature request related to a problem? Please describe.**

Currently, Fluent Bit uses NSIS (Null Soft Installer Script) to create Fluent Bit installer for Windows.
But, this system does not have the following features in core:

* Specifying user permissions strictly like as td-agent:
    * See: https://github.com/fluent/fluent-package-builder/blob/master/td-agent/msi/source.wxs#L30-L74
* Register and launch Fluent Bit as Windows service during the installation process
   * WiX can handle these requirements with `CustomAction`.

**Describe the solution you'd like**

Migrating from NSIS to WiX as title is mentioned.

**Describe alternatives you've considered**

Install _NSIS_ plugin to handle Windows Service registering and specifying user permissions. But I'm not sure where they are located in.

**Additional context**

**Comment by patrick-stephens** [comment]
@cosmo0920 can we close this now?

**Comment by cosmo0920** [comment]
Yes. We can close this issue. In OSS version, we just put WiX templates and settings for now.
NSIS installer is enought for folks who are using OSS version.
