### ISSUE TITLE
Rotation log_file

### ISSUE THREAD

**Issue by tguenneguez** [fluent/fluent-bit#5345]
There is no mechanism to enable automatic fluent-bit log rotation.
On Unix OS, logrotate allows rotation. On the other hand, on Windows, there is no equivalent system.
It would be interesting to configure fluent-bit so that it can manage its own log rotation (gender in relation to size or in relation to duration).
Something like :
   log_file_rotation_interval 1d
   log_file_rotation_max_size 2MB

**Comment by patrick-stephens** [comment]
See https://github.com/fluent/fluent-bit/pull/1890

**Comment by tguenneguez** [comment]
Thanks
