### ISSUE TITLE
How do I output logs to PostgresQL on Windows

### ISSUE THREAD

**Issue by hiseth** [fluent/fluent-bit#5352]
I'm sorry that I'm new to Fluent-bit and I use it to read a text file to write to PGSQL, but I find that Fluent-bit-h does not list output-PGSQL related plug-ins. How do I load this plug-in?   
https://docs.fluentbit.io/manual/pipeline/outputs/postgresql

**Comment by agup006** [comment]
On Windows you might need to build with the Postgres headers as it's not their by default

To be honest though, I'm not sure if that library is supported on WIndows
