### ISSUE TITLE
Custom Http headers?

### ISSUE THREAD

**Issue by JDKardia** [fluent/fluent-bit#536]
I'm currently working with a Kafka REST proxy, and have been using Fluent-bit as a lightweight log forwarder. However, I'm hoping to convert my log collection over to Avro to take advantage of the schema validation that's built into that protocol. 

Thankfully Avro takes json as input, but to tell the REST proxy that you're sending Avro messages, you need to specify the header `Content-Type: application/vnd.kafka.avro.v2+json`. Is there any plan or interest in adding custom headers to either the out_kafka_rest or out_http plugins?

**Comment by edsiper** [comment]
hi @JDKardia 

this sounds a reasonable enhancement, we will implement it (no ETA yet)

thanks

**Comment by edsiper** [comment]
this is already implemented, documentation here (example at bottom):

https://docs.fluentbit.io/manual/output/http
