### ISSUE TITLE
Basic auth for Influxdb 

### ISSUE THREAD

**Issue by JAtula** [fluent/fluent-bit#537]
Hi!

As ES and HTTP plugins got their basic auth included, would be awesome if InfluxDB would support it as well.

**Comment by edsiper** [comment]
hi @JAtula 

thanks for the requirement. The enhancement has been implemented and will be part of 0.13 release.

**Comment by edsiper** [comment]
0.13 Documentation for InfluxDB + Basic Auth:

http://fluentbit.io/documentation/0.13/output/influxdb.html
