### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by crybabykillzz** [fluent/fluent-bit#5371]
Keep getting this error when trying to make, cant figure out what is wrong, maybe some dependencies not set
/fluent-bit-1.8.12/lib/chunkio/src/cio_utils.c:29:10: fatal error: fts.h: No such file or directory

**Comment by patrick-stephens** [comment]
Which target? You can see all the dependencies used for the current targets (1.9) here: https://github.com/fluent/fluent-bit/tree/master/packaging/distros

Each container image builds for the specific distro target and installs dependencies first, e.g. for Ubuntu 20.04: https://github.com/fluent/fluent-bit/blob/20acf10d9d2dbd7666428075faac32dc16fd8415/packaging/distros/ubuntu/Dockerfile#L74

**Comment by crybabykillzz** [comment]
i guess i figured out whats the problem, alpine...

**Comment by crybabykillzz** [comment]
is there any chance of building fluent-bit binary on alpine?

**Comment by patrick-stephens** [comment]
This is probably relevant: https://docs.fluentbit.io/manual/installation/docker#why-there-is-no-fluent-bit-docker-image-based-on-alpine-linux

**Comment by Sfinx** [comment]
> is there any chance of building fluent-bit binary on alpine?

Just add fts-dev to Dockerfile and use this patch:

```
diff --git a/lib/chunkio/src/CMakeLists.txt b/lib/chunkio/src/CMakeLists.txt
index a4fc2d37b..5805368a6 100644
--- a/lib/chunkio/src/CMakeLists.txt
+++ b/lib/chunkio/src/CMakeLists.txt
@@ -12,7 +12,7 @@ set(src
   chunkio.c
   )
 
-set(libs cio-crc32)
+set(libs cio-crc32 -lfts)
 
 if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   set(src
```
