### ISSUE TITLE
Update to version 1.9.3 from the ubuntu apt repo?

### ISSUE THREAD

**Issue by LeoWinterDE** [fluent/fluent-bit#5375]
## Bug Report

**Describe the bug**
Using the `fluent-bit` package for Ubuntu focal from `http://packages.fluentbit.io/ubuntu` as describe here [here](https://docs.fluentbit.io/manual/installation/linux/ubuntu).
I just got **signed** an update to version `1.9.3` but on fluentbit.io on the announcements page or here on [releases](https://github.com/fluent/fluent-bit/releases) i don't see any new version besides `1.9.2` O_o

Is this just a build pipeline error/bug or some kind of package takeover aka. security incident?
Just stumbled over it because the update also blew away my configuration (`/etc/fluent-bit/fluent-bit.conf`), hopefully not intentionally?

**To Reproduce**
- Use the ubuntu repo and you install fluent-bit you get version 1.9.3
```
root@TEST/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

root@TEST:/# systemctl status fluent-bit
● fluent-bit.service - Fluent Bit
     Loaded: loaded (/lib/systemd/system/fluent-bit.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-04-27 14:04:29 UTC; 10min ago
       Docs: https://docs.fluentbit.io/manual/
   Main PID: 5063 (fluent-bit)
      Tasks: 7 (limit: 19105)
     Memory: 6.7M
     CGroup: /system.slice/fluent-bit.service
             └─5063 /opt/fluent-bit/bin/fluent-bit -c //etc/fluent-bit/fluent-bit.conf
<SOME DEDACTED LOG>

root@TEST:/# cat /etc/apt/sources.list.d/fluentbit.list 
deb https://packages.fluentbit.io/ubuntu/focal focal main

root@TEST:/# apt-cache policy fluent-bit
fluent-bit:
  Installed: 1.9.3
  Candidate: 1.9.3
  Version table:
 *** 1.9.3 500
        500 https://packages.fluentbit.io/ubuntu/focal focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1.9.2 500
        500 https://packages.fluentbit.io/ubuntu/focal focal/main amd64 Packages
     1.9.1 500
        500 https://packages.fluentbit.io/ubuntu/focal focal/main amd64 Packages
     1.9.0 500
        500 https://packages.fluentbit.io/ubuntu/focal focal/main amd64 Packages

root@TEST:/# sha256sum /opt/fluent-bit/bin/fluent-bit
23944a3ebe87a69bc696ef1aa07f9b77140ff542dbe54e45803ed1ac730bb123  /opt/fluent-bit/bin/fluent-bit
```

**Expected behavior**
Updates are published (and/or build) on github and afterwords published to the apt repo.

**Environment**
* Version used: 1.9.2 and 1.9.3 (?!)
* Configuration: defualt form apt
* Environment name and version: Ubuntu focal
* Server type and version: VM
* Operating System and version: Ubuntu focal
* Filters and plugins: /

**Comment by patrick-stephens** [comment]
You'll see the tag is present in git, it's just not been announced is all

**Comment by LeoWinterDE** [comment]
Okay good to know. Then it's just the bug the configuration blow after updating or is this Intended?

**Comment by patrick-stephens** [comment]
No, that sounds like an issue: there should be no difference there I'm aware of from previous versions. Apologies I only saw the first bit about 1.9.3 so covered that.

Might be worth reopening and editing the title or splitting the relevant details into a new issue. Just to make it clear.
