### ISSUE TITLE
Adding custom label to  Prometheus Scrape metric

### ISSUE THREAD

**Issue by ycyr** [fluent/fluent-bit#5376]
**Is your feature request related to a problem? Please describe.**
Hello, thanks for adding the Prometheus Scrape metric input plugin, it's a great addition. I would like to use Fluent-bit as a hub/proxy to retrieve all the metrics from all exporters installed on a node. But I would need to add custom labels at the scrape before the ingestion of metrics in Fluent-bit. In fact, similar to Prometheus Exporter parameter "add_label". 

Thanks 

**Describe the solution you'd like**
```
[INPUT]
    name prometheus_scrape
    host 0.0.0.0 
    port 8201
    tag vault 
    metrics_path /v1/sys/metrics?format=prometheus 
    scrape_interval 10s
    add_label  exporter vault   
    add_label  foo bar

[INPUT]
    name prometheus_scrape
    host 0.0.0.0 
    port 9100
    tag node-exporter
    metrics_path /metrics
    scrape_interval 10s`
    add_label  exporter node-exporter  
    add_label  bar foo 
```

**Comment by ycyr** [comment]
Any update ?

**Comment by rlynch-bitpusher** [comment]
This would indeed be a cleaner approach than adding labels during the output... We need this feature to improve our ability to centralize our AWS monitoring infrastructure - the current approach dictates creating tons of superfluous additional internal fluent-bit routing to send metrics via dedicated OUTPUT blocks..

**Comment by shubham1172** [comment]
@edsiper could you please reopen this issue (and maybe `pin` it), it's a very useful ask!

**Comment by hsavy** [comment]
@edsiper hello, could you consider reopening this issue ? I think that it is a awaited feature. 
 Without labelling at the input, fluent-bit could not be used correctly as a metric proxy.  The only solutions without this are workarounds that are non viable in production environnement.

**Comment by Z4ck404** [comment]
+1 on this feature.

**Comment by noahbailey** [comment]
Is there any effective workaround for source-level metrics until this feature is implemented? 
My usual hacks like using a `record_modifier` filter to add labels don't seem to work correctly on metrics, only logs.

**Comment by ealgra** [comment]
+1 for this feature request
