### ISSUE TITLE
Update 1.9.3: overwrites existing configuration

### ISSUE THREAD

**Issue by LeoWinterDE** [fluent/fluent-bit#5377]
## Bug Report

**Describe the bug**
Rel: #5375

The update from 1.9.2 to 1.9.3 on Ubuntu focal blows the configuration. Getting the package from the apt repository into Ubuntu.

**Expected behavior**
fluent-bit.yml config stays the same even after updating the version, or you get ask to replace the configuration with the default.

**Comment by patrick-stephens** [comment]
Can confirm that the default configuration file seems to be overwritten with each version (tested 1.9.3 and 1.9.4) - note not the YAML config file listed above but the default classic one at `/etc/fluent-bit/fluent-bit.conf`.

Reproducible by adding a simple comment in the config file like so:
```
$ docker run --rm -t ubuntu:20.04 /bin/sh -c "\
apt-get update && apt-get install -y curl gpg && \
curl https://packages.fluentbit.io/fluentbit.key | gpg --dearmor > /usr/share/keyrings/fluentbit-keyring.gpg && \
echo 'deb [signed-by=/usr/share/keyrings/fluentbit-keyring.gpg] https://packages.fluentbit.io/ubuntu/focal focal main' >> /etc/apt/sources.list && \
apt-get update && apt-get install -y fluent-bit=1.9.2 && \
echo '# EXTRA LINE' >> /etc/fluent-bit/fluent-bit.conf && \
cat /etc/fluent-bit/fluent-bit.conf && \
apt-get update && apt-get install -y fluent-bit=1.9.3 && \
cat /etc/fluent-bit/fluent-bit.conf && \
grep -q EXTRA /etc/fluent-bit/fluent-bit.conf "
```
This fails and shows the file has been overwritten:
```
...
Setting up fluent-bit (1.9.2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
[SERVICE]
...
[OUTPUT]
    name  stdout
    match *
# EXTRA LINE
...
Unpacking fluent-bit (1.9.3) over (1.9.2) ...
Setting up fluent-bit (1.9.3) ...
[SERVICE]
...
[OUTPUT]
    name  stdout
    match *
$ echo $?
1
```

**Comment by patrick-stephens** [comment]
@niedbalski can you look at the CPack config for this?
I think we should also add an upgrade smoke test for this too based on the above (with more stuff to come in the future).

**Comment by niedbalski** [comment]
This should use CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA, with a conffiles entry for deb, CPACK_RPM_<COMPONENT>_USER_FILELIST with a %config(noreplace) option.
