### ISSUE TITLE
Parser keeps the record if no matches found

### ISSUE THREAD

**Issue by akrus** [fluent/fluent-bit#538]
Hi,

was trying to find similar report or something in the docs, but haven't found.

Question is I have a parser:

^(?<time>[^\|]+)\| \[(?<level>\w+)\s*\] (?<my_integer>\d+)$

So I expect if my_integer is not matched (e.g. there is only text, no numbers), message will not have my_integer key, but instead I can see:
tail.0: [1521111680.000000, {"file":"/tmp/file", "level":"INFO", "my_integer":""}]

How to get rid of it properly?

**Comment by edsiper** [comment]
please provide your example log line that you are matching against that regex rule

**Comment by edsiper** [comment]
ping ^

**Comment by akrus** [comment]
@edsiper, sorry for late response, forgot to update the ticket. My real parser is a bit different, here is a real world example:

```
Name system
Format regex
Regex ^(?<time>[^\|]+)\|\[(?<level>\w+)\s*\] (?<message>attempt: (?<attempt>\d+)|.*)$
Time_Key time
Time_Format %Y-%m-%d %H:%M:%S.%L
Time_Keep Off
Types attempt:integer
```

And messages:
```
2018-03-29 01:40:38.385|[WARN ] attempt: 3
2018-03-29 01:40:38.385|[WARN ] other random message
```

And output will be:
```
message: attempt: 3
attempt: 3

message: other random message
attempt:
```

For the second type of message I don't need this 'attempt' field, but it's added anyway.

**Comment by edsiper** [comment]
thanks for the clarification.

Test case on Rubular: http://rubular.com/r/Ktpq4JI9fz

**Comment by akrus** [comment]
As modify filter is now available, I'm returning back here for some help.

It works well with 'Condition Key_Value_Equals <something> ' and matches when string is empty.
Although I have a parser with:
Types my_int:integer

And 'Condition Key_Value_Equals my_int 0' doesn't work there. Also using empty instead of 0 or Key_Value_Matches with ^0$ doesn't help. Is it a bug?

**Comment by akrus** [comment]
In case someone had a similar problem we've changed regex parser with lua.
