### ISSUE TITLE
the certificate expired for fluentbit.io

### ISSUE THREAD

**Issue by renanqts** [fluent/fluent-bit#5395]
## Bug Report

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/3486802/166235407-64010c8b-32ab-40ae-90a1-c9279768daf5.png)

**Your Environment**

**Additional context**

**Comment by danielfelgar** [comment]
The same issue here.

**Comment by ironzep** [comment]
Here too, it is breaking my pipeline.

**Comment by renanqts** [comment]
closing in favor of https://github.com/fluent/fluent-bit/issues/5389
