### ISSUE TITLE
New YAML format is unable to reliably order filters in includes when mixing with filters in the main file

### ISSUE THREAD

**Issue by pwhelan** [fluent/fluent-bit#5397]
## Bug Report

Since includes exist outside the main `pipeline` declaration and instead under a separate `includes` key it is impossible to reproduce configurations that use includes to load filters in a certain order if they also define some in the main configuration file. At the very least we should consider documenting this.

**To Reproduce**

This specific fluent-bit.conf cannot be directly translated into a fluent-bit.yaml:

fluent-bit.conf:
```ini
[INPUT]
    Name  dummy
    Dummy {"type": "destroyer"}
    Tag    generator

@include 'rewrite_operator.conf'

[FILTER]
    Name   record_modifier
    Match  operator
    Record powered_by fbit

[OUTPUT]
    Name  stdout
    Match operator
```

rewrite_operator.conf:
```ini
[FILTER]
    Name rewrite_tag
    Match generator
    Rule   $type ^destroyer$ operator false
```

**Expected behavior**

Be able to add the include in the main configuration file in a compatible way.

**Comment by belo4ya** [comment]
@pwhelan, were you able to get more detailed information about this or not? Have you found any opinions on whether full compatibility of the `@INCLUDE` and YAML `includes` instructions will be implemented? Or is this use of `includes` not intended?
Maybe it's worth reopening this issue?

**Comment by pwhelan** [comment]
At the moment this kind of work has not been prioritized.

**Comment by belo4ya** [comment]
I see, thanks for the reply. I also found your proposal about this in the discussions, I'll leave it here: https://github.com/fluent/fluent-bit/discussions/6029
