### ISSUE TITLE
systemd plugin stopped working in 1.9.3

### ISSUE THREAD

**Issue by afedorenchik-li** [fluent/fluent-bit#5401]
## Bug Report

**Describe the bug**
After upgrading to **1.9.3**, agent can't start with the following error:
```
May 03 08:36:21 webapp-7 systemd[1]: Started TD Agent Bit.
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: Fluent Bit v1.9.3
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: * Copyright (C) 2015-2022 The Fluent Bit Authors
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: * https://fluentbit.io
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: [2022/05/03 08:36:21] [ warn] [env] variable ${HOST_IP} is used but not set
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: [2022/05/03 08:36:21] [ info] [fluent bit] version=1.9.3, commit=, pid=1605907
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: [2022/05/03 08:36:21] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: [2022/05/03 08:36:21] [ info] [cmetrics] version=0.3.1
May 03 08:36:21 webapp-7 td-agent-bit[1605907]: [2022/05/03 08:36:21] [error] [config] systemd: unknown configuration property 'Refresh_Interval'. The following properties are allowed: path, max_fields, max_entries, systemd_filter_type, systemd_filter, read_from_tail, lowercase, strip_underscores, db_sync, and db.
```

Config:
```
[INPUT]
    Name        systemd
    Tag         systemd.*
    DB          /tmp/td-agent-bit-systemd.sqllite
    Mem_Buf_Limit     10MB
    Refresh_Interval    10
```

Same config works fine on **1.8.13**

**To Reproduce**
Steps to reproduce the problem:
* Install fluent bit agent version 1.9.3
* configure systemd plugin with `Refresh_Interval` parameter
* observe fluent bit agent fails to start with the following logs:
```
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [ warn] [env] variable ${HOST_IP} is used but not set
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [ info] [fluent bit] version=1.9.3, commit=, pid=1411
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [ info] [cmetrics] version=0.3.1
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [error] [lib] backend failed
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [error] [config] systemd: unknown configuration property 'Refresh_Interval'. The following properties are allowed: path, max_fields, max_entries, systemd_filter_type, systemd_filter, read_from_tail, lowercase, strip_underscores, db_sync, and db.
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [ help] try the command: /opt/td-agent-bit/bin/td-agent-bit -i systemd -h
Apr 30 10:06:36 webapp-7 td-agent-bit[1411]: [2022/04/30 10:06:36] [ info] [input] pausing tail.0
```

**Expected behavior**
Any updated to plugins should be backward compatible.

**Your Environment**

* Version used: 1.9.3
* Configuration: See in description
* Environment name and version (e.g. Kubernetes? What version?): systemd input plugin
* Server type and version:
* Operating System and version: Ubuntu 20.04.4 LTS
* Filters and plugins: systemd

**Comment by patrick-stephens** [comment]
It looks like refresh interval is not a documented parameter in 1.8, 1.7 or 1.6: 
https://docs.fluentbit.io/manual/v/1.8/pipeline/inputs/systemd

I can't see it in the source either: https://github.com/fluent/fluent-bit/blob/1.8/plugins/in_systemd/systemd_config.c

It seems to be something specific to the tail input plugin: https://github.com/fluent/fluent-bit/blob/0c95ac96106f8b3880ae2207fca8aa500c4cc0f8/plugins/in_tail/tail.c#L547
Or: https://github.com/fluent/fluent-bit/blob/0c95ac96106f8b3880ae2207fca8aa500c4cc0f8/plugins/in_tail/tail_config.c#L141

Not sure if it was just being silently ignored before.

**Comment by afedorenchik-li** [comment]
> Not sure if it was just being silently ignored before.

I think so. I think main issue is how unexpected this was for us. We will review our configuration as it looks like `refresh_interval` was never intended in `systemd` plugin.

If needed, we can close this and just leave for people to look if they experience similar issues after upgrading to never version.

**Comment by patrick-stephens** [comment]
1.9 has some updates to configuration handling to standardise and improve it which is why you're likely seeing this to prevent people pushing unsupported configuration in the future expecting it to do things when it just silently fails.
