### ISSUE TITLE
Message Field is Empty for Channels Other than PowerShell in Winlog Logs

### ISSUE THREAD

**Issue by adamdepollo** [fluent/fluent-bit#5402]
## Bug Report

**Describe the bug**

The Winlog input generates a "Message" field which is meant to include a human-readable version of the StringInserts field (https://github.com/fluent/fluent-bit/issues/2427). However, this field is consistently empty in logs generated by the plugin from channels other than PowerShell:
<img width="855" alt="Screen Shot 2022-05-03 at 12 56 15 PM" src="https://user-images.githubusercontent.com/55102313/166503989-521c1b88-8112-4634-94a0-72e39c2133a1.png">

I'm currently using the following channels:
`[INPUT]
Name winlog
Channels Security,System,Windows Powershell,Microsoft-Windows-TaskScheduler/Operational,Microsoft-Windows-PowerShell/Operational,Application,Microsoft-Windows-Windows Firewall With Advanced Security/Firewall,Microsoft-Windows-WindowsUpdateClient/Operational,Setup
Interval_Sec 10
Tag winlog`

**To Reproduce**
Set up a deployment with Winlog input. 

**Expected behavior**
"Message" field should include a human-readable version of the StringInserts field.

**Screenshots**
**Your Environment**
* Version used:1.9.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):Windows
* Server type and version:Windows Server 2016
* Operating System and version: Windows Server 2016
* Filters and plugins: Winlog

**Additional context**

**Comment by ralphw** [comment]
Still seeing inconsistent behavior on this topic 
Directory Services log have an empty message field, although StringInserts values are populated.
This make no sense, since the Windows registry is supposed to contain formatting which allows StringInserts to be fully populated (as far as I know)
