### ISSUE TITLE
fluent-bit kubernetes logging not showing enriched logs i.e. pod name

### ISSUE THREAD

**Issue by jonathan-kosgei** [fluent/fluent-bit#541]
I get logs like

![image](https://user-images.githubusercontent.com/6712914/37555264-fb44e9c2-29f5-11e8-8f64-eabc533c098f.png)

The documentation says;

> When Fluent Bit runs, it will read, parse and filter the logs of every POD and will enrich each entry with the following information (metadata):
> 
> POD Name
> POD ID
> Container Name
> Container ID
> Labels
> Annotations
> 

It says that this should happen automatically but from the logs this isn't the case. What do I need to do to get this working?

Also the logs here are in json but the log entry in Kibana shows text. How would I get the output to be processed as json?

There're other log items that are not json.

**Comment by edsiper** [comment]
hi @jonathan-kosgei 

please use our latest _dev_ version of Fluent Bit which have several improvements for handling of escaped characters:

https://github.com/fluent/fluent-bit-kubernetes-logging/tree/0.13-dev

in the link above you will find Yaml files to make deployment easier, let me know how it goes...

**Comment by marckamerbeek** [comment]
hi @jonathan-kosgei

Could you please give me your configuration. Its working for me, so maybe I could compare your config with mine.

I'm also using the new feature in 0.13 to put a suggested parser name as kubernetes pod annotation. You could use that to differ between json and non json pods.

**Comment by jonathan-kosgei** [comment]
My serviceaccount had been created in a different namespace. Once I fixed that I was able to get everything to work!
