### ISSUE TITLE
Authenticate to GCP using service account impersonation

### ISSUE THREAD

**Issue by jmcarp** [fluent/fluent-bit#5410]
**Is your feature request related to a problem? Please describe.**

GCP supports [service account impersonation](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials) to allow one service account to act on behalf of another. This is useful for segmenting permissions across service accounts. For example, if running fluent-bit with both the stackdriver and bigquery output plugins, we might want to use a base service account for fluent-bit, then impersonate one service account with fine-grained permissions for stackdriver and another with fine-grained permissions for bigquery.

As far as I can tell, service account impersonation isn't supported in the stackdriver or bigquery plugins. However, the analogous AWS feature is supported in the cloudwatch plugin via the `role_arn` option.

**Describe the solution you'd like**

It would be helpful to add support to output plugins that write to GCP services. Concretely, this might look like adding an `impersonate_service_account_email` configuration option. Service account impersonation also supports impersonating a [chain of delegated accounts](https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-delegated), so ideally this would support a list of service accounts to impersonate.

**Describe alternatives you've considered**

- Use coarse GCP IAM permissions. The purpose of GCP service account impersonation and delegation is to support fine-grained permissions. We can simply not do that!
- Segment IAM access across output plugins by attaching multiple static credential files to the host running fluent-bit. However, it's generally recommended to associate IAM roles to workloads using [VM metadata](https://cloud.google.com/compute/docs/metadata/overview) rather than static credentials.

cc @adwittumuluri

**Additional context**

**Comment by logston** [comment]
I'm taking a look at this now on my flex friday.

**Comment by logston** [comment]
Looking into just the `out_stackdriver` plugin at the moment.

It looks like an OAuth2 token is fetched or renewed in `stackdriver.c` for flushing the logs records out.
https://github.com/fluent/fluent-bit/blob/36e62e7bc47a4eb6eb418cc5e818b2dc0d57c767/plugins/out_stackdriver/stackdriver.c#L2250

The `get_google_token` function then calls `get_oauth2_token` here:
https://github.com/fluent/fluent-bit/blob/36e62e7bc47a4eb6eb418cc5e818b2dc0d57c767/plugins/out_stackdriver/stackdriver.c#L344

That function breaks down into two halves as I see it; a flow with a metadata server and a flow with a private key. I'm going to focus on the flow with the metadata server. 

https://github.com/fluent/fluent-bit/blob/36e62e7bc47a4eb6eb418cc5e818b2dc0d57c767/plugins/out_stackdriver/stackdriver.c#L268-L271

The `gce_metadata_read_token` function seems to fetch the token from 

`http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/<SERVICE_ACCOUNT_EMAIL>/token`

https://github.com/fluent/fluent-bit/blob/36e62e7bc47a4eb6eb418cc5e818b2dc0d57c767/plugins/out_stackdriver/gce_metadata.c#L115-L120

This is a very different endpoint than `https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/SA_NAME@PROJECT_ID.iam.gserviceaccount.com:generateAccessToken` which is described here: https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-oauth

I wonder if `http://metadata.google.internal/...` is just a proxy for `https://iamcredentials.googleapis.com/...`? Right now, there's nothing added to the body of the `http://metadata.google.internal/...` request. I'm going to do some cross account testing to see if by simply adding in the delegates/scope/lifetime info a token can be generated.

**Comment by logston** [comment]
I had one SA due to turn on the GCE service:  100237134624-compute@developer.gserviceaccount.com 
I've created two new SAs to act as the delegates:
- second@fluent-bit-issue-5410.iam.gserviceaccount.com 
- finale@fluent-bit-issue-5410.iam.gserviceaccount.com 

I created a VM and attempted to `generateAccessToken` for the default compute account. Interestingly,  this failed. 

```
paul_logston@instance-1:~$ gcloud config list account --format "value(core.account)"
100237134624-compute@developer.gserviceaccount.com
paul_logston@instance-1:~$ cat request.json 
{
  "scope": [
    "https://www.googleapis.com/auth/cloud-platform"
  ],
  "lifetime": "60"
}
paul_logston@instance-1:~$ curl -X POST \
-H "Authorization: Bearer "$(gcloud auth application-default print-access-token) \
-H "Content-Type: application/json; charset=utf-8" \
-d @request.json \
"https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:generateAccessToken"
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "service": "iamcredentials.googleapis.com",
          "method": "google.iam.credentials.v1.IAMCredentials.GenerateAccessToken"
        }
      }
    ]
  }
}
```

And getting the IAM policy was a no go either:
```
paul_logston@instance-1:~$ cat getIamPolicy.json 
{
  "options": {
    "requestedPolicyVersion": 3
  }
}
paul_logston@instance-1:~$ curl -X POST \
-H "Authorization: Bearer "$(gcloud auth application-default print-access-token) \
-H "Content-Type: application/json; charset=utf-8" \
-d @getIamPolicy.json \
"https://iam.googleapis.com/v1/projects/fluent-bit-issue-5410/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:getIamPolicy"
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "service": "iam.googleapis.com",
          "method": "google.iam.admin.v1.IAM.GetIamPolicy"
        }
      }
    ]
  }
}
```

Ah, it looks like the scopes on the VM were too narrow:
<img width="654" alt="Screen Shot 2022-05-28 at 4 54 51 AM" src="https://user-images.githubusercontent.com/2641765/170788391-a8623612-83ef-4e98-bad0-067a9c1bebaf.png">

Enabling the "Cloud Platform" API (not shown above but present when editing the VM) got me past this error. I then got this issue:

```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @getIamPolicy.json "https://iam.googleapis.com/v1/projects/fluent-bit-issue-5410/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:getIamPolicy"
{
  "error": {
    "code": 403,
    "message": "Identity and Access Management (IAM) API has not been used in project 100237134624 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=100237134624 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/iam.googleapis.com/overview?project=100237134624"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "iam.googleapis.com",
          "consumer": "projects/100237134624"
        }
      }
    ]
  }
}
```
Enabling the  Identity and Access Management (IAM) API  here did the trick: https://console.cloud.google.com/apis/library/iam.googleapis.com?project=fluent-bit-issue-5410

```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @getIamPolicy.json "https://iam.googleapis.com/v1/projects/fluent-bit-issue-5410/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:getIamPolicy"
{
  "etag": "ACAB"
}
```
The GCE account still does not have permission to get an access token though...
```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:generateAccessToken"
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

After adding the Service Account Token Creator role to 100237134624-compute@developer.gserviceaccount.com, I was able to run 
```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:generateAccessToken"
{
  "accessToken": "ya29.c.b0...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................",
  "expireTime": "2022-05-27T21:22:09Z"
}
```

But I don't think that's what we want because I was also able to create a token for second@fluent-bit-issue-5410.iam.gserviceaccount.com without specifying any delegates.

```
paul_logston@instance-1:~$ cat request.json 
{
  "scope": [
    "https://www.googleapis.com/auth/cloud-platform"
  ],
  "lifetime": "60s"
}
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/second@fluent-bit-issue-5410.iam.gserviceaccount.com:generateAccessToken"
{
  "accessToken": "ya29.c.b0...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................",
  "expireTime": "2022-05-27T21:25:15Z"
}
```

By adding a new permission to second@fluent-bit-issue-5410.iam.gserviceaccount.com, I was able to get a token for that service account but not the requesting service account (as is desired).
 
<img width="1091" alt="Screen Shot 2022-05-28 at 5 35 39 AM" src="https://user-images.githubusercontent.com/2641765/170792245-243600cb-41da-49c7-b08f-00d8e907d74e.png">

```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/second@fluent-bit-issue-5410.iam.gserviceaccount.com:generateAccessToken"
{
  "accessToken": "ya29.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................",
  "expireTime": "2022-05-27T21:35:23Z"
}
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/100237134624-compute@developer.gserviceaccount.com:generateAccessToken"
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

The compute service account still does not have the ability to get an access token for finale@fluent-bit-issue-5410.iam.gserviceaccount.com. 

```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/finale@fluent-bit-issue-5410.iam.gserviceaccount.com:generateAccessToken"
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

Even after granting `second@` permission to create tokens for `finale@`...
<img width="1166" alt="Screen Shot 2022-05-28 at 5 40 55 AM" src="https://user-images.githubusercontent.com/2641765/170792701-02438296-9efd-4ae0-bf33-73979e4e3189.png">

... the request still fails...

```
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/finale@fluent-bit-issue-5410.iam.gserviceaccount.com:generateAccessToken"
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```
 
And, as expected, after adding in a `delegates` key, the request succeeds.

```
paul_logston@instance-1:~$ cat request-no-delegates.json 
{
  "scope": [
    "https://www.googleapis.com/auth/cloud-platform"
  ],
  "lifetime": "60s"
}
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request-no-delegates.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/finale@fluent-bit-issue-5410.iam.gserviceaccount.com:generateAccessToken"
{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
paul_logston@instance-1:~$ cat request.json 
{
  "delegates": [
    "second@fluent-bit-issue-5410.iam.gserviceaccount.com"
  ],
  "scope": [
    "https://www.googleapis.com/auth/cloud-platform"
  ],
  "lifetime": "60s"
}
paul_logston@instance-1:~$ curl -X POST -H "Authorization: Bearer "$(gcloud auth application-default print-access-token) -H "Content-Type: application/json; charset=utf-8" -d @request.json "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/finale@fluent-bit-issue-5410.iam.gserviceaccount.com:generateAccessToken"
{
  "accessToken": "ya29.c.b................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................",
  "expireTime": "2022-05-27T21:47:03Z"
}
```

However, we are still not using the internal metadata server. I'm not sure what endpoint would be correct. Using the `/token` endpoint from above...
```
paul_logston@instance-1:~$ curl -H "Metadata-Flavor:Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/100237134624-compute@developer.gserviceaccount.com/token
{"access_token":"ya29.c.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................","expires_in":2287,"token_type":"Beare...}

paul_logston@instance-1:~$ curl -H "Metadata-Flavor:Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/second@fluent-bit-issue-5410.iam.gserviceaccount.com/token
{"error":"invalid_request","error_description":"Service account not enabled on this instance"}
```

We get `Service account not enabled on this instance`, which makes sense because we have not assigned `second@` to this VM. From digging around in the metadata tree with cURL, I do not see any place besides `/token` for fetching a service account token. My guess is that we'll have to use the token we get from `/token` to authn/z our request to `https://iamcredentials.googleapis.com/`. Please correct me if I'm wrong.

I think I have enough context now to draft a patch.

**Comment by logston** [comment]
@joshimhoff for viz as @jmcarp may be occupied.
