### ISSUE TITLE
Kubernetes default Kube_URL is not as documented

### ISSUE THREAD

**Issue by bivas** [fluent/fluent-bit#542]
According to the code at https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_conf.h#L52 the value is default to `kubernetes.default.svc.cluster.local` while in the [docs](http://fluentbit.io/documentation/0.12/filter/kubernetes.html) the default is `kubernetes.default.svc`

The value defaulted by the code is causing issues (as clusters change the domain to other than `cluster.local`) and users are not aware the value *must* be changed for flunet-bit kubernetes filter to work.

The value stated in the docs (`kubernetes.default.svc`) is the value fluent-bit should be using.

**Comment by edsiper** [comment]
thanks for raising this. 

The default value kubernetes.default.svc.cluster.local is the right one for any default Kubernetes environment, if a cluster requires a different one this can be tweaked into the proper configmap (we validate this with the community).

For now I've fixed the documentation which was not updated after we did the change in the code base:

http://fluentbit.io/documentation/0.12/filter/kubernetes.html

**Comment by bivas** [comment]
@edsiper while what you're saying is true for default installation - it's a (small) hassle to configure it. When using the shorter version it will work on any cluster installation, even with domain name changed.

**Comment by bivas** [comment]
Side note - Kubernetes filter requires proper role binding to work (when RBAC enabled). When users are using the Helm chart it's configured for them but normal installation will fail to fetch Kubernetes metadata.

I think the docs should state that.

**Comment by edsiper** [comment]
actually it was changed because in some clusters it was not working :) , I will make sure to update the documentation, the source docs for Kubernetes users is here:

https://github.com/fluent/fluent-bit-kubernetes-logging

For the upcoming 0.13 here:

https://github.com/fluent/fluent-bit-kubernetes-logging/tree/0.13-dev

**Comment by edsiper** [comment]
note: 0.13-dev states the RBAC rules. 

primary topic has been fixed. Closing this issue for now
