### ISSUE TITLE
The systemd input plugin errors with `db.sync`

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluent-bit#5426]
## Bug Report

**Describe the bug**
The systemd input plugin errors with `db.sync`.

**To Reproduce**
Use the systemd input with `db.sync`.

```
[2022/05/06 17:00:11] [error] [config] systemd: unknown configuration property 'db.sync'. The following properties are allowed: path, max_fields, max_entries, systemd_filter_type, systemd_filter, read_from_tail, lowercase, strip_underscores, db_sync, and db.
```
- Steps to reproduce the problem:

**Expected behavior**
The documented config should work.

**Screenshots**
n/a

**Your Environment**

* Version used: 1.9.3
* Configuration: n/a
* Environment name and version (e.g. Kubernetes? What version?): AKS v1.22
* Server type and version: n/a
* Operating System and version: n/a
* Filters and plugins: n/a

**Additional context**

**Comment by patrick-stephens** [comment]
It looks like it wants `db_sync` so is it a docs PR?

**Comment by stevehipwell** [comment]
@patrick-stephens docs PR? The fact that it's different to the tail input makes me think it's a bug?

**Comment by nokute78** [comment]
I think it should be a bug.
v1.8.15 supports `db.sync`.
https://github.com/fluent/fluent-bit/blob/v1.8.15/plugins/in_systemd/systemd_config.c#L118

It was changed from v1.9.0 when we supported config_map.
https://github.com/fluent/fluent-bit/commit/2f28ee57668db28e9338b468dc80bda5dda508be#diff-286fb1d6dda90a3a6f8b0907800d35b8848c725b7d0634777120e79a5e375985R506

**Comment by nokute78** [comment]
I sent a patch https://github.com/fluent/fluent-bit/pull/5429
