### ISSUE TITLE
Fluentbit service start  error

### ISSUE THREAD

**Issue by jegadjame** [fluent/fluent-bit#5442]
Hi,
I am trying to create Fluent bit as service
 When i run the command '.\bin\fluent-bit.exe -c .\etc\fluent-bit.conf' from fluent-bit folder with powershell, It is working fine

But when i try to create windows service with this command,  'sc.exe create fluent-bit binpath= "\"C:\Program Files\fluent-bit\bin\fluent-bit.exe\" -c \"C:\Program Files\fluent-bit\etc\fluent-bit.conf\""' 

It is creating service. but, When i start service, it is throwing error as 'windows could not start fluent bit service on local computer . Error 1067: error 1067 the process terminated unexpectedly'

Below is my conf file
[service]
    Flush        5
    Daemon       Off
    Log_Level    debug
    Log_File     d:/temp/stdout
    Parsers_File parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

[filter]
    Name record_modifier
    Match *
    Record server_name ${HOSTNAME}
    Record service_name J_Service

[INPUT]
    Name         Forward
    Port 	24224

[OUTPUT]
    name  tsp
    match *

**Comment by patrick-stephens** [comment]
Does it show similar errors to https://github.com/fluent/fluent-bit/issues/5519?

**Comment by dauchande** [comment]
I was having this exact error.  

It turned out to be that the ImagePath set for the config file was C:\program files\fluent-bit\bin\fluent-bit.exe -c C:\program files\fluent-bit\conf\fluent-bit.conf.  

Debugging it and the config file passed to main was "C:\program". 

Adding quotes around the config file fixed the issue for me.
