### ISSUE TITLE
New Feature Request: Support alternate Kubernetes pod annotations to identify suggested parser

### ISSUE THREAD

**Issue by gsmith-sas** [fluent/fluent-bit#5447]
**Is your feature request related to a problem? Please describe.**
The Kubernetes filter supports identifying a specific parser to use for log messages coming from a particular pod via a the **fluentbit.io/parser** annotation.  This is very helpful.  However, it is also Fluent Bit-specific.  It would be great if we could identify another annotation to contain this same information.  This would allow users to use a vendor-neutral annotation to identify the log format and/or log parser.   I've encountered resistance to adding the **fluentbit.io/parser** annotation to our application's pods since it is (or appears to be) a "Fluent Bit specific" annotation and some of our customers may be using other log 
collection/monitoring technologies.

**Describe the solution you'd like**
I envision adding a new parameter to the Kubernetes filter, perhaps _**Log_Parser_Annotation**_ or _**K8S-Logging.Suggested_Parser_Annotation**_, that would identify the pod annotation that identifies the name of the appropriate parser.  The functionality would be identical to the current functionality supporting the **fluentbit.io/parser** annotation; the only difference would be the ability to use a different annotation.  Ideally, some day there could be a well-established "standard" annotation (perhaps: **app.kubernetes.io/log-format**?) that everyone could use and Fluent Bit could support.  But, until then, it would be nice to allow us to point to any annotation we choose to use for identifying the appropriate parser.

Here's how it might look in operation:
```
    [FILTER]
       Name                    kubernetes
       Match                   kube.*
       K8S-Logging.Parser      On
       K8S-Logging.Suggested_Parser_Annotation   app.kubernetes.io/log-format

```
**Describe alternatives you've considered**
Given that the **fluentbit.io/parser** annotation does just what we need, that's the only alternative I've considered.  But, as I mentioned above, that annotation appears to be tying us too tightly to Fluent Bit.

**Comment by gsmith-sas** [comment]
@patrick-stephens , thanks for responding.  Sorry, I think I confused the issue by also raising the idea of a potential "standard" K8s annotation.  Ignore that part of the discussion.  

My request is just for Fluent Bit to support users identifying another (arbitrary) K8s annotation (in addition to the current fluentbit.io/parser one) that can be used to identify the name of the parser to be used to parse the log messages coming from a particular pod.  This would allow users to a) re-use an existing annotation already on the pod, or, b) create a new annotation that fits their own corporate standards for this purpose.

My company develops solutions used by other companies.  I work on a log monitoring solution that uses Fluent Bit that we make available for those customers.  However, some customers choose to use other tools/solutions for the log monitoring.  It would be nice annotate our pods with something like sas.com/log-format=foo.  For our log monitoring solution, built with Fluent Bit, that annotation would point to the parser in the Fluent Bit parser.conf file.  But, customers using some other monitoring solution could use the same annotation to do whatever is appropriate for that solution.    I hope that clarifies the use-case a bit.

I think a key difference between the Fluent Bit and Prometheus use-case, is the fact that Prometheus has really become the de facto standard for logs.  While Fluent Bit is very widely used, it hasn't quite reached that level of acceptance.  Thanks!

**Comment by patrick-stephens** [comment]
Ah I see, I think if you submit a PR then providing the configuration option (plus docs PR of course) that would be helpful. 

It probably needs to consider backwards compatibility (what happens when you specify the new annotation but only the old one is present) and what happens when both annotations are present but different.
