### ISSUE TITLE
install.sh generates incorrect yum repo file

### ISSUE THREAD

**Issue by atitan** [fluent/fluent-bit#5459]
## Bug Report

**Describe the bug**
install.sh in master branch generates incorrect yum repo file.
previous commit 20ed0df053349923e8afaade22b5e472a35298b3 is working fine.

**To Reproduce**
```sh
# curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh
================================
 Fluent Bit Installation Script
================================
This script requires superuser access to install packages.
You will be prompted for your password by sudo.
rpmkeys: no arguments given
Loaded plugins: priorities, update-motd, upgrade-helper
Repository 'fluent-bit': Error parsing config: Error parsing "baseurl = '/amazonlinux/2/x86_64/'": URL must be http, ftp, file or https not ""
Nothing to do

Installation completed. Happy Logging!

# cat /etc/yum.repos.d/fluent-bit.repo
[fluent-bit]
name = Fluent Bit
baseurl = /amazonlinux/$releasever/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=
enabled=1
```

**Expected behavior**
Generate correct yum repo file
```sh
# curl https://raw.githubusercontent.com/fluent/fluent-bit/20ed0df053349923e8afaade22b5e472a35298b3/install.sh | sh
================================
 Fluent Bit Installation Script
================================
This script requires superuser access to install packages.
You will be prompted for your password by sudo.
Loaded plugins: priorities, update-motd, upgrade-helper
fluent-bit/2/x86_64/signature                                                                                              |  866 B  00:00:00
fluent-bit/2/x86_64/signature                                                                                              | 2.9 kB  00:00:00 !!!
Package fluent-bit-1.9.3-1.x86_64 already installed and latest version
Nothing to do

Installation completed. Happy Logging!

# cat /etc/yum.repos.d/fluent-bit.repo
[fluent-bit]
name = Fluent Bit
baseurl = https://packages.fluentbit.io/amazonlinux/$releasever/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.fluentbit.io/fluentbit.key
enabled=1
```

**Screenshots**

**Your Environment**

* Version used: master branch
* Configuration: N/A
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version: 
  - `ami-0934e28fe3e390537`
  - `amzn2-ami-ecs-hvm-2.0.20191114-x86_64-ebs`
  - `Linux hostname 4.14.146-120.181.amzn2.x86_64 #1 SMP Fri Oct 18 17:01:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Looks like I missed some issue with the base path variable when I made the last change so apologies. Will fix asap although traveling today.

**Comment by jcbjoe** [comment]
The issue seems to be still happening for me on Amazon Linux. 
Im using:
```
curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sh
```

**Comment by patrick-stephens** [comment]
@jcbjoe I think this should be resolved now - seems to be for me.
A quick tell if you have the right version is it should dump the contents of the repo configuration file now during installation.

**Comment by jcbjoe** [comment]
Hey @patrick-stephens 

Yep, seems to be working now!

Thanks
