### ISSUE TITLE
stackdriver: log_name is not url-encoded

### ISSUE THREAD

**Issue by alison0211** [fluent/fluent-bit#5475]
## Bug Report

**Describe the bug**
log with special characters ('/', '.', '-') in log_name will be rejected with warning:
```
[2022/03/24 18:54:28] [ warn] [output:stackdriver:stackdriver.0] error
{
  "error": {
    "code": 400,
    "message": "Received unexpected value parsing name \"projects/jefferbrecht-sandbox/logs//a/b/c\": c. Expected the form projects/[PROJECT_ID]/logs/[ID]",
    "status": "INVALID_ARGUMENT"
  }
}
```

**To Reproduce**
- Rubular link if applicable:
- Example config file:
```
[INPUT]
    Name        tail
    Path        /var/log/messages, /var/log/syslog
    Tag         default_pipeline./a/b/c

[OUTPUT]
    Name   stdout
    Match  *
[OUTPUT]
    Match                         *
    Name                          stackdriver
    Retry_Limit                   3
    net.connect_timeout_log_error False
    resource                      gce_instance
    stackdriver_agent             Google-Cloud-Ops-Agent-Logging/2.11.0 (BuildDistro=buster;Platform=linux;ShortName=debian;ShortVersion=10.11)
    tls                           On
    tls.verify                    Off
    workers                       8
```
- Steps to reproduce the problem:
```
bin/fluent-bit --config test.conf 
```
**Expected behavior**
there should not be warnings/errors when processing the above sample config file.

**Screenshots**
N/A

**Your Environment**

* Version used: 1.9.4
* Operating System and version: Debian 5.16.18-1rodete2 (2022-04-07) x86_64
* Filters and plugins: out_stackdriver

**Comment by patrick-stephens** [comment]
Tweaked it slightly to make it clear it is specific to stackdriver - users may not want logs encoded for other outputs.
