### ISSUE TITLE
Feature Request: Worker Support for Tail Plugin

### ISSUE THREAD

**Issue by zhonghui12** [fluent/fluent-bit#5477]
**Is your feature request related to a problem? Please describe.**

There comes an customer issue to us that single tail plugin is insufficient for throughput for their use cases (2GB/s).

**Describe the solution you'd like**

Achieve high throughput for tail input plugin. (2GB/s)

**Comment by lubingfeng** [comment]
Per discussion with @edsiper we have seen 200MB/s in total. this is also environment dependent.

**Comment by Andexrian** [comment]
any news about high throughput tail??
