### ISSUE TITLE
OutOfMemoryError despite using default Retry_Limit=1

### ISSUE THREAD

**Issue by dtreskunov** [fluent/fluent-bit#5479]
## Bug Report

**Describe the bug**
We are using FluentBit as distributed in [aws-for-fluent-bit](https://github.com/aws/aws-for-fluent-bit) (version 2.20.0, [Changelog](https://github.com/aws/aws-for-fluent-bit/blob/mainline/CHANGELOG.md)). We have two outputs, `kafka-rest` and `cloudwatch`. Recently we had an incident where the `kafka-rest` output stopped working. About 90 minutes later the `cloudwatch` output sent the last event, and 5 hours later, the FluentBit container ran out of memory and got killed.

Per [Scheduling and Retries](https://docs.fluentbit.io/manual/administration/scheduling-and-retries), the default value for `Retry_Limit` is `1`, so the Engine only retries one time to send the events to `kafka-rest`. FluentBit logs indicate this is indeed the case.

```
[2022/05/19 10:28:54] [ warn] [engine] failed to flush chunk '10-1652956133.780265319.flb', retry in 6 seconds: task_id=286, input=forward.1 > output=kafka-rest.1 (out_id=1)
[2022/05/19 10:29:00] [ warn] [engine] chunk '10-1652956133.780265319.flb' cannot be retried: task_id=286, input=forward.1 > output=kafka-rest.1
```

Timeline:
```
2022-05-19T03:17:36.724-07:00: `kafka-rest` output becomes blocked
2022-05-19T04:52:57.606-07:00: `cloudwatch` output last event
2022-05-19T09:46:57.993-07:00: killed due to OutOfMemoryError
```

**To Reproduce**
Config file:
```
[SERVICE]
    Flush 1
    Grace 30

[FILTER]
    Name                modify
    Match               ${project_name}*
    Add                 environment ${environment}-${region}
    Add                 platform ecs
    Add                 sourcetype ${odp_kafka_topic_name}
    Add                 tz Etc/UTC
    Copy                container_id host

[FILTER]
    Name                nest
    Match               ${project_name}*
    Operation           nest
    Wildcard            container_*
    Wildcard            ecs_*
    Nest_under          ecs

[OUTPUT]
    Name                cloudwatch
    Match               ${project_name}*
    region              ${region}
    log_key             log
    log_group_name      ${project_name}
    log_stream_name     ecs/${project_name}/$(ecs_task_id)
    auto_create_group   false

[OUTPUT]
    Name                kafka-rest
    Match               ${project_name}*
    Host                ${odp_kafka_endpoint}
    Port                443
    Topic               ${odp_kafka_topic_name}
    tls                 On
    tls.verify          Off
    tls.crt_file        ./${odp_certificate}
    tls.key_file        ./fluentbit.key
```

**Expected behavior**
1. Output `cloudwatch` should keep working despite errors in the other output.
2. OutOfMemoryError should not occur with reported configuration.

**Screenshots**

**Your Environment**

* Version used: Fluent Bit [1.8.7](https://fluentbit.io/announcements/v1.8.7/), via [aws-for-fluent-bit](https://github.com/aws/aws-for-fluent-bit) (version 2.20.0, [Changelog](https://github.com/aws/aws-for-fluent-bit/blob/mainline/CHANGELOG.md))
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: AWS Fargate
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by mengtaosun** [comment]
Any update on this?
