### ISSUE TITLE
unable to use ENV variable in tag and in kafka output

### ISSUE THREAD

**Issue by vikasmishra17** [fluent/fluent-bit#5480]
Trying to use ENV Variable in fluent-bit input and output config files, when trying to use ENV variable in input filter for tag and in Kafka output filter for match and topics. Getting error as [env] variable ${FOO} is used but not set

Followed this documentation - https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/variables

Tried to set env variable in both ~/.profile and /etc/environment, but facing the same issue.

**Comment by patrick-stephens** [comment]
Please provide the full config you're using, there's a few ways to interpret what you've said above. What version of Fluent Bit, etc. are you using and on what OS too? 

Please follow the issue template as it captures all this.

**Comment by vikasmishra17** [comment]
Hi, @patrick-stephens here is the config I am using -
[INPUT]
    Name  tail
    Path   /var/log/syslog
    Tag   ${FOO}
    Read_from_Head True
    DB /etc/td-agent-bit/db/file.db

[OUTPUT]
    Name    kafka
    Match   ${FOO}
    Brokers  Brokers_list
    Topics   ${FOO}

Tried to set environment variable value for {FOO} in both ~/.profile and /etc/environment, but facing the same issue.

ERROR - environment variable {FOO} is used but not set.

**Comment by vikasmishra17** [comment]
Hi @patrick-stephens adding some additional information, which I missed adding 

Fluent-bit version - 1.8.12

Running on VM - Ubuntu 20.04.3

**Comment by nokute78** [comment]
> Tried to set environment variable value for {FOO} in both ~/.profile and /etc/environment, but facing the same issue.

How did you set ? You need to set `FOO` not `{FOO}`.

**Comment by patrick-stephens** [comment]
And if you're running through systemd or another init system then you need to set variables in the correct fashion for that init system, rather than user variables.
