### ISSUE TITLE
Document site crash

### ISSUE THREAD

**Issue by yang953** [fluent/fluent-bit#5497]
## Bug Report

**Describe the bug**
Document site crash

**To Reproduce**
- open https://docs.fluentbit.io/manual/pipeline/filters/kubernetes
- rolling, rolling,  crash

**Screenshots**
![image](https://user-images.githubusercontent.com/43697164/170410852-a736a3dc-5cc4-42a9-bf60-81c1afbdfa02.png)

**Your Environment**

* system: window 10
* browser:  chrome  101.0.4951.67

**Comment by agup006** [comment]
Thanks for reporting @yang953 , I checked the page and all looks well on my side. I also checked our provider (GitBook) and all looks well on their side too. Perhaps resetting cache might do the trick?

**Comment by patrick-stephens** [comment]
Looks fine for me too both this morning and last night. On Chrome but Ubuntu & Android.

**Comment by agup006** [comment]
I'm going to close for now as we can't repro this and I don't think there is much action

**Comment by yang953** [comment]
Maybe i am in china,  then some url not friendly for us,  thanks

**Comment by patrick-stephens** [comment]
The documentation all comes from markdown here so that's always an alternative: https://github.com/fluent/fluent-bit-docs/
