### ISSUE TITLE
Add source file [TAIL] to output as a field

### ISSUE THREAD

**Issue by mitchellmaler** [fluent/fluent-bit#550]
Hello, 

I am parsing json files using the TAIL input and the JSON parser. I was hoping I could add a field using the filter that states the source file. I am aggregating over a few different json log files in a directory so I cant hard code it unless I start fluent-bit up multiple times with different configurations.

**Comment by edsiper** [comment]
hi @mitchellmaler 

You can add a field into the log with the filename using the property [Path_Key](http://fluentbit.io/documentation/0.12/input/tail.html), e.g:

```
[INPUT]
    Name      tail
    Path      /var/log/myjsonlogs/*.log
    Parser    json-test
    Path_Key  my_filename
```

let me know how it goes

**Comment by mitchellmaler** [comment]
@edsiper That worked. I can't believe I missed that configuration. Thanks!
