### ISSUE TITLE
Control the mechanism how fluentbit sends single or batch log entries using the out http plugin

### ISSUE THREAD

**Issue by hochdorf** [fluent/fluent-bit#551]
Hello,

I'm trying to create a configuration for fluentbit where I have a tail input plugin and an http output plugin with mutual TLS authentication.
My goal would be to send the collected logs in batches and not one by one because of the big bandwidth overhead of the TLS handshake. So for example send one POST message in every minute with all of the collected logs in that period (or earlier if the log data reaches a defined size limit).
I analyzed the traffic between fluentbit and the other endpoint and it seems that sometimes only a single log entry is sent and sometimes more entries.
I tried to play with the Buffer_Chunk_Size parameter of the tail plugin but it had no effect on this batch functionality.

So my question is that is it somehow possible to control/modify the parameters how fluentbit decides to send one or more entries in one HTTP message?

I use the 13-dev version.

Thanks!

**Comment by edsiper** [comment]
hi @hochdorf 

Indeed Fluent Bit create a batch of logs called a _chunk_. A chunk internally do not exceed 2MB and is flushed to the destination upon expiration, you can control that with the _Flush_ property that's inside the main _[SERVICE]_ section. For short: we send data upon flush time, not based in the number of records.

Please share your configuration file so I can provide some advice,

**Comment by hochdorf** [comment]
Thank you for your fast response! 
Yes, this Flush parameter is what I need. I increased this Flush value to 60 sec and according to the logs, the tail plugin collects 70-80 KB data during this period. The collected data is sent in 7 HTTP messages.

What is the segmentation logic for the data sent in the http messages? As I saw the max content length in one message is around 16 KB.

Can I be sure that this segmentation logic takes care to always include full log lines and create valid JSON payload?
I'm asking this because I turned on the tls debug mode and I have such log entries where the beginning (or the end) of the JSON is missing:

```
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 7143: => write
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 2701: => write record
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 1258: => encrypt buf
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 1269: dumping 'before encrypt: output payload' (7372 bytes)
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 1269: 0000:  34 61 34 61 62 30 64 36 31 22 7d 7d 2c 20 7b 22  4a4ab0d61"}}, {"
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 1269: 0010:  64 61 74 65 22 3a 31 35 32 32 33 30 37 35 38 36  date":1522307586
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 1269: 0020:  2e 35 37 31 30 38 30 2c 20 22 6c 6f 67 22 3a 22  .571080, "log":"
[2018/03/29 07:13:17] [debug] [io_tls] /lib/mbedtls-2.6.0/library/ssl_tls.c 1269: 0030:  45 30 33 32 39 20 30 37 3a 31 33 3a 30 36 2e 35  E0329 07:13:06.5
```

Here is my config:
```
  fluent-bit.conf: |
    [SERVICE]
        Flush         60
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-http.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kubernetes.*
        Exclude_Path      /var/log/containers/fluent*.log 
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Buffer_Chunk_Size 1MB
        Buffer_Max_Size   1MB
  filter-kubernetes.conf: |
    [FILTER]
        Name           kubernetes
        Match          kubernetes.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_JSON_Log On      
  output-http.conf: |
    [OUTPUT]
        Name         http
        Match        *
        Host         logs.endpoint
        Port         443
        tls          on
        tls.verify   on
        tls.ca_file  /etc/fluent/server.crt     
        tls.crt_file /etc/fluent/client.pem 
        tls.key_file /etc/fluent/client.key 
        tls.debug    1
        Format       json        
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped    log
```

**Comment by edsiper** [comment]
segmentation happens based in Tags, there are two types: static tags (e.g: mytag) and dynamic tags which are composed with filenames (e.g: var.log.container.1.log, var.log.container.2.log...), so based in the output routes they will go (they can hit multiple destinations) they are grouped. 

A record or log line, is never split and is send in full, that's up to the TLS handler or TCP stack on how to send the bytes over the wire, Fluent Bit only prepare the data and enqueue it for delivery.

**Comment by hochdorf** [comment]
Ahh ok, it is clear now. 
Thanks for your efforts!

**Comment by hafkaM** [comment]
Hi
Is it already possible to use a partition key for kafka output?
Thanks
