### ISSUE TITLE
doc(elastic): message about unknown type parameter also applies to opensearch

### ISSUE THREAD

**Issue by dmpe** [fluent/fluent-bit#5515]
## Bug Report

**Describe the bug**

https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch#action-metadata-contains-an-unknown-parameter-type correctly suggests that `Suppress_Type_Name` must be `On`. 

With a recently released opensearch 2.0 version, this message also applies to this new product as well. 
It would have been nice, if documentation for https://docs.fluentbit.io/manual/pipeline/outputs/opensearch#about-opensearch-field-names could have been updated as well. 

For opensearch 1.x this was not necessary, but given lucene upgrade as well, I assume that this is now new "normal" :)

**Your Environment**
* Version used: 1.9.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): k8s 1.21 rancher
* Operating System and version: centos 7.9
* Filters and plugins: opensearch & elasticsearch

**Comment by dmpe** [comment]
Hi @patrick-stephens, 

thanks. I have opened PR in the docs repo.

**Comment by patrick-stephens** [comment]
Excellent, appreciate it - I've merged it now so should appear in the docs shortly.
