### ISSUE TITLE
update unit test instructions

### ISSUE THREAD

**Issue by itoffshore** [fluent/fluent-bit#552]
I'm trying to update the `td-agent-bit` package in [Alpine Linux](https://pkgs.alpinelinux.org/packages?name=td-agent-bit&branch=edge). By default now we run unit tests on all packages. The [Unit Test instructions](https://github.com/fluent/fluent-bit-docs/blob/master/installation/unit_tests.md) need to be updated as running `cmake` with `-DFLB_TESTS` gives:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    FLB_TESTS
```
I have `g++` & [`gtest-dev`](https://pkgs.alpinelinux.org/packages?name=gtest-dev&branch=edge) in the build environment & run the tests with:

```
check() {
        cd "$builddir"/build
        cmake -DFLB_TESTS=ON ../
        make test
}
```

**Comment by nokute78** [comment]
Could you try this cmake options?
```
cmake -DFLB_TESTS_RUNTIME=ON -DFLB_TESTS_INTERNAL=ON ../
```

**Comment by nokute78** [comment]
First, we don't support Alpine Linux now.
See also https://github.com/fluent/fluent-bit/issues/377#issuecomment-330347984

Hmm, the root cause is missing CMakeLists.txt at tests/runtime .
```
CMake Error at CMakeLists.txt:453 (add_subdirectory):
  The source directory

    /home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.12.17/tests/runtime

  does not contain a CMakeLists.txt file.
```

@edsiper tests/runtime/CMakeLists.txt is missing at v0.12.17 and it causes this error.
Could you add it?

**Comment by itoffshore** [comment]
getting closer - the tests begin to build but require `systemd`:

```
/home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.13.2/tests/runtime/filter_kubernetes.c: In function 'file_to_buf':
/home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.13.2/tests/runtime/filter_kubernetes.c:39:17: error: storage size of 'st' isn't known
     struct stat st;
                 ^~
/home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.13.2/tests/runtime/filter_kubernetes.c:41:11: warning: implicit declaration of function 'stat' [-Wimplicit-function-declaration]
     ret = stat(path, &st);
           ^~~~
/home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.13.2/tests/runtime/filter_kubernetes.c:39:17: warning: unused variable 'st' [-Wunused-variable]
     struct stat st;
                 ^~
/home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.13.2/tests/runtime/filter_kubernetes.c: At top level:
/home/stuart/aports/testing/td-agent-bit/src/fluent-bit-0.13.2/tests/runtime/filter_kubernetes.c:355:32: fatal error: systemd/sd-journal.h: No such file or directory
 #include <systemd/sd-journal.h>
                                ^
compilation terminated.
make[2]: *** [tests/runtime/CMakeFiles/flb-rt-filter_kubernetes.dir/build.make:63: tests/runtime/CMakeFiles/flb-rt-filter_kubernetes.dir/filter_kubernetes.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5752: tests/runtime/CMakeFiles/flb-rt-filter_kubernetes.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Many thx for looking at this issue - I think for the moment I will just disable the tests to update the package in Alpine Linux to `0.13.2` as it builds successfully

**Comment by jlpettersson** [comment]
When I add -DFLB_TESTS_RUNTIME=On
I get this error

> CMake Error at tests/runtime/CMakeLists.txt:75 (add_sanitizers):
  Unknown CMake command "add_sanitizers".

**Comment by Antiarchitect** [comment]
@jlpettersson Trying to build the project from 1.0 branch and getting the same error:
```
CMake Error at CMakeLists.txt:217 (add_sanitizers):
  Unknown CMake command "add_sanitizers".
```
Everything the Google shows is your comment and some other project where is no answer either.

**Comment by edsiper** [comment]
options are documented here now:

https://docs.fluentbit.io/manual/installation/sources/build-and-install

also builds should be ok now.
