### ISSUE TITLE
invalid pattern for given tag

### ISSUE THREAD

**Issue by snirbenyosef** [fluent/fluent-bit#5522]
## Bug Report

**Describe the bug**
I'm running fluent-bit binary from inside a Kubernetes pod. and the Kubernetes labels or metadata are not working.
invalid pattern for given tag kube.logs

**To Reproduce**
```
[0] kube.logs: [1654068810.842208138, {"job_id"=>"sdf", "job_type"=>"sdf", "owner"=>"sdf", "project"=>"testing", "model"=>"2", "event_time"=>1654068810.821105, "input"=>"input", "output"=>"{"model_id": sadf, "model_version": 1854086819354475703, "state": "Online", "payload": "530EI5794Z2GSM2YPCLPM49ROJPS97ZSKCUZ1XZ5", "extraValues": 1854086819354475703}", "start_time"=>"2022-06-01 07:33:30", "elapsed_time"=>2}]
```
- Steps to reproduce the problem:

**Expected behavior**
add metadata of Kubernetes like pod_name , namespace etc.

**Your Environment**

* Version used: 1.7.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):Kubernetes-lateast
* Operating System and version: ubuntu 18.04
* Filters and plugins: 
[INPUT]
    Name                  tail
    Tag                   kube.logs
    Path                /conf/file_log
[OUTPUT]
    Name                  stdout
    Match                 *
[FILTER]
    Name                  kubernetes
    Match                 *
    Kube_URL              https://kubernetes.default.svc:443
    Kube_CA_File          /var/run/secrets/.../ca.crt
    Kube_Token_File       /var/run/secrets/...token
    Kube_Tag_Prefix       kube.*
    Merge_Log             On
    K8S-Logging.Parser    On
    tls.debug             4
    Annotations           On
    K8S-Logging.Exclude   Off
~

**Comment by adecchi-2inno** [comment]
I am not able to add the kubernetes metadata using fluentbit as daemon at version 1.9.6
My config:

`
 [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri, java, go
        Multiline On
        Parser_Firstline java_multiline
        Tag kube.<namespace_name>.<pod_name>.<container_name>.<docker_id>
        Tag_Regex (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Mem_Buf_Limit 5MB
        
 [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.
        Regex_Parser k8s-custom-tag
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

[OUTPUT]
        Name opensearch
        Current_Time_Index On
        Match kube.api-*
        Host logs.xxx.com
        Port 443
        Type doc
        TLS On
        Logstash_Format On
        Logstash_Prefix applications
        Time_Key @timestamp
        Retry_Limit 1
        Generate_ID On
        Replace_Dots On
        Buffer_Size False
        Trace_Error On
        Suppress_Type_Name On
        Time_Key_Nanos On
    
    [PARSER]
        Name k8s-custom-tag
        Format regex
        Regex ^(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})-$
`

Logs:

`
[ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.logging.fluentbit-fluent-bit-vs48l.fluent-bit.8288327c0f929f41c6146592829b5ee1032f9707c032cbb3661123ad62e78670
`

**Comment by patrick-stephens** [comment]
I think what that warning is saying is that your regex does not match the tag provided: https://github.com/fluent/fluent-bit/blob/472918bd44fb1b109dc1cc296212fa13afa1c977/plugins/filter_kubernetes/kube_meta.c#L1268

Does it work if you switch to using a default tail + kubernetes filter approach? https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-+-kubernetes-filter

**Comment by adecchi-2inno** [comment]
@patrick-stephens 
Yes, using the standard `kube.*` as Tag it works and teh metadadta is added. But I need to split it by namespace.
So,  for example everything at `kube-system` go to elasticsearch infra index and the namespace that start with bff for example to application index.

**Comment by patrick-stephens** [comment]
`rewrite_tag` using the `kubernetes.namespace` key value after the kubernetes filter?

OK, so sounds like this is an issue with the parser then and/or the tag being used.

**Comment by sagarm-traveloka** [comment]
I am also facing the same problem. Do you find any work around to fix this issue?

**Comment by Queetinliu** [comment]
it's different from https://github.com/fluent/fluent-bit/issues/661?

**Comment by mgoltzsche** [comment]
I have the same problem and I did not even specify the `Regex_Parser` option within my Fluent Bit configuration for the kubernetes filter plugin.
Though, in my case the problem seems to be caused by the container name length: As soon as I reduced the container name length from 63 to 53 characters, the problem disappeared, Fluent Bit does not log the error anymore and properly uploads the corresponding logs.
(In every case both the namespace name and the container ID that is used as suffix each have a length of 63 characters.)

**Comment by wchaws** [comment]
This is caused by incorrect regex. The `Regex_Parser` match group must containers at least `pod_name`, `namespace_name`, `container_name`. Otherwise it will SEG FAULT. 

Here's my example:

```
invalid pattern for given tag log.d027ef1d-f85b-4055-800d-11d53609efb6.d24ac719-f2a6-408b-9065-7a81d17234b5.v1.var.log.changan.tu.logs.tu-5b6994b8cc-2vbw6.tu-#console#-default.log
```

The correct regex is:
```
    [PARSER]
      Name        kube-custom-meta
      Format      regex
      Regex       \.logs\.(?<pod_name>[^-]+)-(?<container_name>[^-]+-[^-]+)\.[^-]+-.(?<namespace_name>.+).-.*\.log
```
