### ISSUE TITLE
out_stackdriver: Introduce an API for Generically Assigning Resource Labels

### ISSUE THREAD

**Issue by YoussefRizkalla** [fluent/fluent-bit#5525]
**Objective**

To introduce a generic mechanism for assigning fields into the resource/labels section with different ways to the Stackdriver output plugin by adding a configuration parameter.

**Is your feature request related to a problem? Please describe.**

In the past, supporting a new monitored resource type required writing a LUA script or adding a specific configuration parameter with custom logic in the plugin. This process can be tedious and often results in redundant code.

**Describe the solution you'd like**

We propose a configuration parameter `resource_labels` that supports assigning fields into the resource labels section in Stackdriver’s output plugin using a list of comma seperated strings (similar to the `labels` parameter). This parameter will support assigning entries to a plaintext value, an environment variable, or a remapping from another key in the log entry. Thus, supporting a new resource type becomes trivial, as configuring this one parameter is all that is needed.

This API will be completely disjoint from other methods historically used to assign resource labels. Initially, Stackdriver will attempt to use this method. If the API is not configured correctly, the program will fallback to the existing methods.

***

As mentioned, the API will support three types of assignments:

***Plaintext***
The user can input a plaintext assignment, which will pack a new key-value pair exactly as inputted.

For example, the user can specfiy `resource_labels keyA=valA`, which will produce the following result:

```
{
  "resource": {
      "labels": {
          "keyA": "valA"    
      }  
   }
}
```
***Remapping from payload field***
The user can input a remapping from a field present in the log entry using the syntax `destination=$original`. This will make use of fluent-bit's existing [record accessor](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor) to support accessing nested fields.

The original key can be selected from any field present in the log while processed by the Stackdriver plugin.

The destination key will be limited to [resource labels](https://cloud.google.com/monitoring/api/resources).

Note that we are assigning the value for a new key (the destination key) to the value of the original key. This will not delete the original field.

***Environment Variables***
We will also support assigning using environment variables, which is also supported by the record accessor.

***

**Full Example**:

The original log payload before stackdriver processing:
```
{
  "keyA": "valA",
  "toplevel": {
    "keyB": "valB"
  }
}
```
The fluent-bit configuration used:
```
[OUTPUT]
    Name stackdriver
    Match *
    resource_labels  keyC=$keyA,keyD=$toplevel['keyB'],keyE=valC
```

The desired log entry after stackdriver processing:
```
{
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "fluent-bit",
      "keyC": "valA",
      "keyD": "valB",
      "keyE": "valC"
    }
  },
  "entries": [
    {
      "jsonPayload": {
        "keyA": "valA",
        "toplevel": {
           "keyB": "valB"
        }
      },
    }
  ]
}
```
***
**Additional context**
I will be working on this feature and will submit a PR to resolve it.

**Comment by JeffLuoo** [comment]
Also cc: @qingling128 @edsiper
