### ISSUE TITLE
Unable to use @ character in proxy password - url-encoding not supported

### ISSUE THREAD

**Issue by jfleming135** [fluent/fluent-bit#5530]
## Bug Report

**Describe the bug**
If a user wishes to use Fluent-Bit through a proxy with basic authentication, this can be set through the HTTP_PROXY environment variable. This can be seen from the example provided in the [docs](https://docs.fluentbit.io/manual/administration/http-proxy#http-proxy): 
```
HTTP_PROXY='http://example_user:example_pass@proxy.example.com:8080'
```
However, this currently doesn't allow the @ character to exist in the proxy password. If a proxy password containing @ is passed into the HTTP_PROXY environment variable, for example:
```
HTTP_PROXY='http://example_user:example_pass_w_@_char@proxy.example.com:8080'
```
then the Fluent-Bit client will try to connect to a proxy with domain name: `_char@proxy.example.com` instead of `proxy.example.com`.

Ideally, Fluent-Bit would support url encoding, so it would support the proxy credentials being passed in like so:
```
HTTP_PROXY='http://example_user:example_pass_w_%40_char@proxy.example.com:8080'
```

**To Reproduce**
- log messages:
```
[2022/06/02 23:40:39] [ warn] [net] getaddrinfo(host='_char@proxy.example.com', err=4): Domain name not found
[2022/06/02 23:40:39] [debug] [upstream] connection #-1 failed to _char@proxy.example.com:8080
[2022/06/02 23:40:39] [error] [output:http:placeholder] no upstream connections available to _char@proxy.example.com:8080
```
- Steps to reproduce the problem:
1. Configure a proxy server
2. Add a user for the proxy server to authenticate via Basic Authentication, with a password containing the url-encoded @ character (%40)
3. Configure Fluent-Bit to connect through the proxy via the `HTTP_PROXY` environment variable
4. Run Fluent-Bit

**Expected behavior**
Fluent-Bit supports proxy Basic Authentication credentials containing url-encoded special characters, and is able to connect through the proxy.

**Your Environment**

* Version used: Fluent Bit v1.9.1
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version: Debian GNU/Linux 10 (buster)
* Filters and plugins:
  * Output plugins:
    * [http](https://docs.fluentbit.io/manual/pipeline/outputs/http)  (most relevant plugin)
    * [tls-configuration-parameters](https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls#tls-configuration-parameters)

**Comment by nokute78** [comment]
Thank you for reporting.
I sent a patch https://github.com/fluent/fluent-bit/pull/5534 .
