### ISSUE TITLE
E2E test for fluent-bit

### ISSUE THREAD

**Issue by aman556** [fluent/fluent-bit#5538]
**Describe the solution you'd like**

I have used Fluent-bit in [Tanzu Community Edition](https://github.com/vmware-tanzu/community-edition). There we need a e2e test for it. I am thinking that If we can create a test here and fetch and run in Tanzu Community Edition then in this manner we can use test at both places. 

Please let me know if i am unable to search the test in the repo.

The language which is common at both the places in shell script. I would love to know what others will suggest.

I am also UP to take the issue and start my contribution journey with Fluent-bit :).

**Comment by patrick-stephens** [comment]
We actually have a few things in progress on this:
* There are the existing integration tests from the fluent/fluent-bit-ci repo.
* #3753 
* #4533 & #4534 
* #5177 with the AWS folks are looking to contribute their testing as well although this is primarily load testing

Wwhat specifically do you mean by e2e (of every combination of input and output with filtering?!)?

More is good but probably need to align on things to ensure the best amount of non-duplicate work as well. It's probably best to keep things on that #5177 discussion I think.
