### ISSUE TITLE
Could the in_kafka be used in production?

### ISSUE THREAD

**Issue by vinson-zhang** [fluent/fluent-bit#5545]
**Is your feature request related to a problem? Please describe.**
I want to consume Kafka data  using fluent_bit in production

**Comment by patrick-stephens** [comment]
It is currently experimental and subject to change so is disabled by default, no official packages or containers will have it enabled so you would have to build it yourself (and maintain this build plus investigate any issues with building). This is also the reason it is not documented on the official site currently I believe, to prevent any accidental usage or implied support.

If you need to use it then of course always test before deployment to production. I will not be offering any guarantees for your production environment and I don't think an OSS project could, particularly with the current state of this feature.

Saying that, testing and providing feedback would be useful as well as any contributions to improve the OSS solution. We would like to get it out there as soon as possible so your help would be invaluable for both the OSS community and yourselves if you need the feature.

Be aware though of the caveats on change with any future release.

**Comment by vinson-zhang** [comment]
Thank you for your answer！
