### ISSUE TITLE
winlog output as xml (Render_Event_As_XML)

### ISSUE THREAD

**Issue by LeoWinterDE** [fluent/fluent-bit#5547]
**Is your feature request related to a problem? Please describe.**
The [winevtlog input module](https://docs.fluentbit.io/manual/pipeline/inputs/windows-event-log-winevtlog) has the option _Render_Event_As_XML_ which works fine, but only on Windows Server 2019 and newer.
Unfortunately, I also have to collect logs from Windows Server 2016. There is only the old [winlog input module](https://docs.fluentbit.io/manual/pipeline/inputs/windows-event-log), which does not support any XML output, is it possible to add xml output? I would be delighted.

**Describe the solution you'd like**
Use the option _Render_Event_As_XML_ on the 'old' winlog input.

**Comment by patrick-stephens** [comment]
Would another option be to have a lua (or similar) filter trigger on those platforms and do the xml formatting you need?

**Comment by LeoWinterDE** [comment]
> Would another option be to have a lua (or similar) filter trigger on those platforms and do the xml formatting you need?

Sure, that would work, but then I would have to cover every edge case inside the old windows version logs.
