### ISSUE TITLE
Systemd plugin sometimes missing SYSLOG_TIMESTAMP field

### ISSUE THREAD

**Issue by Dim-P** [fluent/fluent-bit#5552]
## Bug Report

**Describe the bug**
As the title says, logs collected using the systemd input plugin are sometimes missing the RFC 3164 syslog format timestamp. I picked it up using Fluent-Bit in a WSL2 Ubuntu distribution and enabling systemd via https://github.com/arkane-systems/genie (it doesn't exist by default on WSL2). But I think I saw it when sending logs to journald via `echo 'hello' | systemd-cat` on another system, so it can be reproduced that way too.

**To Reproduce**
Seems to happen with logs emmited via WSL2. Example of a log output via `journalctl -r` that is missing the syslog timestamp:
```
Jun 09 12:48:13 WORK-PC-wsl WSL2: Performing memory compaction.
```
Output via `fluent-bit -i systemd -p read_from_tail='on' -o stdout`:
```
{"_TRANSPORT"=>"kernel", "_BOOT_ID"=>"330f3123634741f2baf29e71e47d33dc", 
"_MACHINE_ID"=>"6aedafd306b97ac6302a6a076278e88b", "_HOSTNAME"=>"WORK-PC-wsl", "PRIORITY"=>"4", 
"SYSLOG_FACILITY"=>"1", "SYSLOG_IDENTIFIER"=>"WSL2", "MESSAGE"=>"Performing memory compaction.", 
"_SOURCE_MONOTONIC_TIMESTAMP"=>"169813762893"}
```

But should also be reproducible using `echo 'hello' | systemd-cat`. 

**Expected behavior**
`SYSLOG_TIMESTAMP` using the systemd input plugin should always be available. 

**Your Environment**

* Version used: 1.9.4
* Configuration: `fluent-bit -i systemd -p read_from_tail='on' -o stdout -v`
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version: Ubuntu 20.04 focal on WSL2
* Filters and plugins: in: systemd, out: stdout

**Comment by nokute78** [comment]
I think it is not a bug of fluent-bit.
It means a client didn't append SYSLOG_TIMESTAMP field.

I tested `logger` and `systemd-cat` command on Ubuntu v20.04.
`logger` appends `SYSLOG_TIMESTAMP` field.
However `systemd-cat` doesn't.
```
echo "hoge logger" | logger
echo "hoge systemd-cat" | systemd-cat
journalctl -r -o verbose
```

An Output of `logger`. It contains `SYSLOG_TIMESTAMP=Jun 11 06:40:39 `.
```
Sat 2022-06-11 06:40:39.870082 JST [s=41d863945d2144fb876c4334090771be;i=1021b9;b=9539caea05ae4e28b9040650d35e7c3a;m=71fd9387;t=5e11eca1f4a96;x=881b996aa8eda640]
    _UID=1000
    _GID=1000
    _CAP_EFFECTIVE=0
    _SELINUX_CONTEXT=unconfined
    _AUDIT_LOGINUID=1000
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_UNIT=user@1000.service
    _SYSTEMD_SLICE=user-1000.slice
    _MACHINE_ID=4bca5af3f22c446f8e92fd877aced271
    _HOSTNAME=locals
    PRIORITY=5
    _TRANSPORT=syslog
    _AUDIT_SESSION=4
    _SYSTEMD_USER_SLICE=apps-org.gnome.Terminal.slice
    SYSLOG_FACILITY=1
    SYSLOG_IDENTIFIER=taka
    _COMM=logger
    _EXE=/usr/bin/logger
    _CMDLINE=logger
    _BOOT_ID=9539caea05ae4e28b9040650d35e7c3a
    SYSLOG_TIMESTAMP=Jun 11 06:40:39 
    MESSAGE=hoge logger
    _PID=3210
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/user@1000.service/apps.slice/apps-org.gnome.Terminal.slice/vte-spawn-9459f59a-d9d4-492a-9da2-18c856d80d6f.scope
    _SYSTEMD_USER_UNIT=vte-spawn-9459f59a-d9d4-492a-9da2-18c856d80d6f.scope
    _SYSTEMD_INVOCATION_ID=2adcf4bc676b471b82f3208c0a206e59
    _SOURCE_REALTIME_TIMESTAMP=1654897239870082
```

An output of `systemd-cat`. It doesn't contain `SYSLOG_TIMESTAMP` field.
```
Sat 2022-06-11 06:40:49.655122 JST [s=41d863945d2144fb876c4334090771be;i=1021ba;b=9539caea05ae4e28b9040650d35e7c3a;m=7292e242;t=5e11ecab49952;x=8324556f10e6f212]
    PRIORITY=6
    _UID=1000
    _GID=1000
    _CAP_EFFECTIVE=0
    _SELINUX_CONTEXT=unconfined
    _AUDIT_LOGINUID=1000
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_UNIT=user@1000.service
    _SYSTEMD_SLICE=user-1000.slice
    _MACHINE_ID=4bca5af3f22c446f8e92fd877aced271
    _HOSTNAME=locals
    _TRANSPORT=stdout
    _AUDIT_SESSION=4
    _COMM=cat
    _EXE=/usr/bin/cat
    _CMDLINE=/bin/cat
    _SYSTEMD_USER_SLICE=apps-org.gnome.Terminal.slice
    _BOOT_ID=9539caea05ae4e28b9040650d35e7c3a
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/user@1000.service/apps.slice/apps-org.gnome.Terminal.slice/vte-spawn-9459f59a-d9d4-492a-9da2-18c856d80d6f.scope
    _SYSTEMD_USER_UNIT=vte-spawn-9459f59a-d9d4-492a-9da2-18c856d80d6f.scope
    _SYSTEMD_INVOCATION_ID=2adcf4bc676b471b82f3208c0a206e59
    _STREAM_ID=2129d1436bdb4fa9a9179f74f9fb7c83
    MESSAGE=hoge systemd-cat
    _PID=3213
```

**Comment by Dim-P** [comment]
Thanks for testing and clarifying this @nokute78 . Seem you are right, I will close the issue.
