### ISSUE TITLE
please support directory path or glob in @INCLUDE

### ISSUE THREAD

**Issue by nathwill** [fluent/fluent-bit#556]
supporting either a `@INCLUDE /etc/td-agent-bit/conf.d' (directory arg), or `@INCLUDE /etc/td-agent-bit/conf.d/*.conf` (glob) would be very helpful in config mgmt context.

right now it seems that unless a full file path is provided, fluent-bit crashes on startup complaining of configuration file errors.

**Comment by edsiper** [comment]
Fixed by https://github.com/monkey/monkey/pull/282
