### ISSUE TITLE
out_bigquery plugin new authorize method

### ISSUE THREAD

**Issue by chris-lee-lb** [fluent/fluent-bit#5572]
**Is your feature request related to a problem? Please describe.**
out_bigquery plugin can be authorized by metadata server just like out_stackdriver plugin

**Describe the solution you'd like**
nope

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by lecaros** [comment]
Hi @chris-lee-lb
can you clarify this issue?
would you like to contribute a PR?
