### ISSUE TITLE
Could not configure property 'storage.type' on input plugin with section name 'tcp'

### ISSUE THREAD

**Issue by OleksiyIvanov** [fluent/fluent-bit#5576]
## Bug Report

**Describe the bug**
According to https://github.com/fluent/fluent-bit-docs/blob/master/administration/buffering-and-storage.md I have configured TCP input plugin with "Mem_Buf_Limit 128MB" to control RAM usage and "storage.type filesystem" to use disk buffers in case RAM is not enough. However while starting fluent-bit using command "/opt/fluent-bit/bin/fluent-bit --config=/etc/fluent-bit/fluent-bit.conf --storage_path=/var/tmp/flb-storage/ --http" I am getting error:
[2022/06/14 18:36:55] [error] [config] could not configure property 'storage.type' on input plugin with section name 'tcp'

**To Reproduce**
Config file is
[SERVICE]
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020
    Health_Check On
    Parsers_File  parsers.conf
    log_Level        info
    storage.path     /var/tmp/flb-storage/
    storage.sync     normal
    storage.checksum on
    storage.max_chunks_up 256
    storage.backlog.mem_limit 64MB
    storage.metrics on
    Retry_Limit False

[INPUT]
    Name        tcp
    Tag         abcd
    Listen      0.0.0.0
    Port        10514
    Format      none
    Chunk_Size  512    # means 512KB
    Mem_Buf_Limit 128MB
    storage.type filesystem # it will use memory first but overflow to disk if needed

[OUTPUT]
    Name file   # this is for easy reproduction of error, in real life my output is bigquery
    Match abcd
    Path /var/tmp/abcd.test001.out
    Mkdir true
    Format plain

- Steps to reproduce the problem:
/opt/fluent-bit/bin/fluent-bit --config=/etc/fluent-bit/fluent-bit.conf --storage_path=/var/tmp/flb-storage/ --http
Error
[2022/06/14 18:36:55] [error] [config] could not configure property 'storage.type' on input plugin with section name 'tcp'
will show up in output.

**Expected behavior**
I expect TCP input plugin to be able to perform as described here https://github.com/fluent/fluent-bit-docs/blob/master/administration/buffering-and-storage.md
"If the input plugin has enabled mem_buf_limit and storage.type as filesystem, when reaching the mem_buf_limit threshold, instead of the plugin being paused, all new data will go to Chunks that are down in the filesystem. This allows to control the memory usage by the service but also providing a a guarantee that the service won't lose any data."

**Your Environment**
* Version used:
* 1.9.4
* Configuration:
* Operating System and version:
* * Debian 11 amd64
* Filters and plugins:
TCP input plugin and file output plugin, no filters.
**Additional context**
Without "storage.type filesystem" set for TCP input plugin I may loose data in case output (bigquery) can't temporarily keep up with amount of data coming in. That is why I need TCP plugin to use filesystem as storage in case RAM allocated to TCP input plugin using "mem_buf_limit" is not enough.

**Comment by nokute78** [comment]
Hmm, I removed comment from your config file and it worked.
I think it may be a parser bug.

```
[SERVICE]
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_PORT 2020
    Health_Check On
    Parsers_File parsers.conf
    log_Level info
    storage.path test.bin
    storage.sync normal
    storage.checksum on
    storage.max_chunks_up 256
    storage.backlog.mem_limit 64MB
    storage.metrics on
    Retry_Limit False

[INPUT]
    Name tcp
    Tag abcd
    Listen 0.0.0.0
    Port 10514
    Format none
    Chunk_Size 512
    Mem_Buf_Limit 128MB
    storage.type filesystem

[OUTPUT]
    Name file
    Match abcd
    Path /var/tmp/abcd.test001.out
    Mkdir true
    Format plain
```

**Comment by OleksiyIvanov** [comment]
Yes it helps indeed ! Thanks !

--
Alex.

**Comment by Jess-Izen** [comment]
I ran into the same bug, tore my hair out thinking I had an issue with my config, until I came across this thread. Recommend tracking this as an active parser bug, or maybe a doc change if no plan to fix.

Old config:
```
[INPUT]
    Name              tcp
    Tag               AuthApplicationLogs
    Listen            0.0.0.0
    Port              ${AUTH_REVERSE_PROXY_APPLICATION_LOG_PORT}
    Format            none
    Mem_Buf_Limit     30MB     # up to 60MB incl. output buffering
```

resulted in:
`could not configure property 'Mem_Buf_Limit' on input plugin with section name 'tcp'`

This config works:
```
[INPUT]
    Name              tcp
    Tag               AuthApplicationLogs
    Listen            0.0.0.0
    Port              ${AUTH_REVERSE_PROXY_APPLICATION_LOG_PORT}
    Format            none
    # up to 60MB incl. output buffering
    Mem_Buf_Limit     30MB
```
