### ISSUE TITLE
td-agent-bit taking 15-35% usr cpu time once a 5s

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#558]
Long-term running td-agent-bit process was found that in loop (about ~5s) consuming 15-35% of usr cpu time.

![image](https://user-images.githubusercontent.com/1211552/38680354-6a08dfec-3e66-11e8-9a62-14f83a36473e.png)

![image](https://user-images.githubusercontent.com/1211552/38680359-6de63dee-3e66-11e8-8909-e6e74be13244.png)

Configuration: 
~25 in_tail log sources from openstack + kmsg and messages
```
# cat td-agent-bit.conf
@INCLUDE service_defaults.conf
@INCLUDE filter_record_hostname.conf
@INCLUDE input_system.conf
@INCLUDE output_forward.conf
@INCLUDE input_nova.conf
@INCLUDE input_keystone.conf
@INCLUDE input_neutron.conf
@INCLUDE input_glance.conf
@INCLUDE input_cinder.conf
@INCLUDE input_pacemaker.conf
@INCLUDE input_chef.conf
@INCLUDE input_heat.conf


# cat /etc/td-agent-bit # cat input_system.conf

[INPUT]
    Name kmsg
    Tag system.log.kernel
[INPUT]
    Name tail
    DB /var/lib/fluentbit/messages.flb.db
    Buffer_Max_Size 5M
    Chunk_Size 128k
    Exclude_Path *.gz,*.xz
    Multiline On
    Multiline_Flush 5
    Parser_Firstline syslog-sles
    Path /var/log/messages
    Tag system.log.syslog
```

Findings:
- memory/writes were on minimum
- on restarted td-agent-bit the problem did not appear. It took hours before the process was again in the bad shape.
- **The only other strange thing, besides cpu utilization, on the process behaviour was high minflt/s once a minute or so.**

```
#      Time   UID       PID    %usr %system  %guest    %CPU   CPU  minflt/s  majflt/s     VSZ    RSS   %MEM   kB_rd/s   kB_wr/s kB_ccwr/s iodelay threads   fd-nr  Command
 1523538874     0     41298   16.00    1.00    0.00   17.00    11   5647.00      0.00  281136 264224   0.05      0.00      0.00      0.00       0       2     223  /usr/bin/td-agent-bit -c /etc/td-agent-bit/td-agent-bit.conf
```

**minflt/s - desc:**
Total number of minor faults the task has made per second, those which have not required loading a memory page from disk.

That seems a bit like a bug in memory management but I just guess. Actually I have no longer access to environment to debug it more.

Commands used for the testing

```
pidstat 1 -p $(pidof td-agent-bit)  -d -r -v  -h -l -u
strace -p $(pidof td-agent-bit)
```

Attached screenshots show the frequency of the occurrence.

By stracing the process it was quite visible, that high peaks correspond to the events when in_tail plugin reads OpenStack logs, but quite sure possibly other input's are processed as well. Finally during the peak io reads/writes are 0 and memory don't move as well.

Worth, if someone may 
- review on his environment
- evaluate what are default 5s loops in the configuration (ie: multiline flush)

**Comment by agup006** [comment]
Doing some cleanup - I think this issue is a bit old, and there have been significant performance improvements in last few releases. 

Are you able to see if there are still problems with the latest 1.7.0? I will close for now and we can reopen if there is anything further we can do
