### ISSUE TITLE
flb-pipeline crashes at window_get():61

### ISSUE THREAD

**Issue by sganiger1** [fluent/fluent-bit#5581]
## Bug Report

**Describe the bug**

Currently fluent-bit/td-agent-bit is used in Magma AGW to collect and forward the events to fluentd. The events are fired periodically. We are observing periodic crashes of flb-pipeline at window_get(). Following is the screenshot of initial core file analysis, where it has the invalid address of "tw->table".
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/87134057/174001634-74ba1337-2209-4e77-a40c-8d51fd29c945.png">

Following are the frequency of crashes.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/87134057/174002253-e92dc84d-6b4d-471a-8e4c-8db37411615c.png">

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
Attached the tar file which has syslogs and core file.

- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.9.4
<img width="814" alt="image" src="https://user-images.githubusercontent.com/87134057/174001752-d24f5c0d-178d-44c1-8b46-d01545175c72.png">

* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Ubuntu
<img width="576" alt="image" src="https://user-images.githubusercontent.com/87134057/174001345-4f7a207e-d259-4875-8ec3-f761d63cb48d.png">

* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by sganiger1** [comment]
Core file and logs link
https://www.dropbox.com/s/wrvbqu9r7lkiq5c/core-1655351784-flb-pipeline-2663160.tgz?dl=0

https://www.dropbox.com/s/ra6u4r3u4nbwi10/core-1655319572-flb-pipeline-2400423.tgz?dl=0

**Comment by sganiger1** [comment]
> What's the configuration you are using for fluent bit and fluentd? Do you have a reproducer?

Hi Pat,
Yeah it can be reproducible let us know what you want us to collect? Following is the configuration
[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        5

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.
    #
    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).
    #
    # storage.path /tmp/storage

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.
    #
    # storage.sync normal

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.
    #
    # storage.checksum off

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.
    #
    # storage.backlog.mem_limit 5M

[INPUT]
    name cpu
    tag  cpu.local

    # Read interval (sec) Default: 1
    interval_sec 1

[OUTPUT]
    name  stdout
    match *

**Comment by sganiger1** [comment]
> I guess by Magma AGW you mean this? https://docs.magmacore.org/docs/lte/deploy_install Apologies but I've no idea what that is so just clarifying for anyone who can look at it.
[Shiv]No issues, yeah it is the LTE in the above mentioned link.

> 
> Looking at that you have to deploy it on an OS, presumably Ubuntu 20.04? AMD 64 architecture or is it ARM64? Can you fill in the relevant sections in the template above (it just says Ubuntu at the moment)?
[Shiv]Yes I have seen on Ubuntu 20.04. Following screen shot provides you the CPU info.
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/87134057/174557863-696954f1-e56e-4d5a-9bcc-b5ca166d90ea.png">

> 
> Looking at your config it is just the default CPU input and standard output.
> 
> Is it reproducible on a machine without AGW installed but otherwise the same? How long does it take to reproduce? The reason I ask is that my local device is Ubuntu 20.04 and I've not seen this issue so I'm wondering if it takes a while and/or is related to some additional dependency changes that AGW makes.
[Shiv] Nope it is not reproducible local machines. It is reproducible only in AGW that too when UE/Subscribers are trying to come-up, which trigger events that are sent to fluent-bit. The frequency is may be every 2hrs.

**Comment by sganiger1** [comment]
Hi Patrick,
Does the following fix solves this issue ?
https://github.com/fluent/fluent-bit/pull/4792

**Comment by patrick-stephens** [comment]
No idea, you can test easily enough if you want with the overnight builds if you want: https://github.com/fluent/fluent-bit/actions/runs/2526933598

It sounds like it is something related to AGW by the sounds of your comment above and that's not a platform we have easy access to currently so I think you can speed things up by testing yourself.

**Comment by sganiger1** [comment]
Okay fine once the changes for https://github.com/fluent/fluent-bit/pull/4792 are merged I will give a try. If not, I will check, if I can share the device where it is reproducible for debugging.
@ptsneves

**Comment by sganiger1** [comment]
@ptsneves Could you provide the steps to do so?

**Comment by ptsneves** [comment]
@sganiger1 instead of launching fluentbit directly launch it through valgrdin like this
```valgrind --tool=memcheck --trace-children=yes --leak-check=full --track-origins=yes /opt/td-agent-bit/bin/td-agent-bit -c /var/opt/magma/tmp/td-agent-bit.conf``` and share the output

I manually wrote the path to your executable because you pasted a screenshot so I might have made a typo :). Adjust at your discretion.

**Comment by sganiger1** [comment]
Thanks @ptsneves , yeah will make the changes and share you the requested info.

**Comment by sganiger1** [comment]
@patrick-stephens @ptsneves 
A new crash has been seen recently and I have raised the following bug for that. Please check if you can let me know if the issue is already fixed in LATEST, v1.9.6.
https://github.com/fluent/fluent-bit/issues/5762

**Comment by ptsneves** [comment]
Hey @sganiger1 crashes in C are not as useful as they seem at first sight. If code corrupts memory it does not necessarily crash. Actually it may corrupt other unrelated parts of the memory, leading to crashes in completely unrelated places. o you have the valgrind report that was requested?

**Comment by sganiger1** [comment]
> requested

Hi @ptsneves, We are running the td-agent-bit with the latest version(v1.9.6) to confirm that we are not hitting crashes as reported in this git issue. 
The issue https://github.com/fluent/fluent-bit/issues/5762, is seen only once unlike earlier crashes. We will try to repro and get you the valgrind report.

**Comment by ptsneves** [comment]
@sganiger1 but this is the thing. There is no guarantee that the new crash is unrelated due to the random nature of memory corruption.

**Comment by sganiger1** [comment]
> @sganiger1 but this is the thing. There is no guarantee that the new crash is unrelated due to the random nature of memory corruption.
Got your point, after upgrading to LATEST(1.9.6) till now(after nearly 15hrs), we have not hit any flb crashes. We are keeping an eye on it. If we hit the issue then we will run the same test with valgrind and provide you requested logs.

**Comment by sganiger1** [comment]
> > @sganiger1 but this is the thing. There is no guarantee that the new crash is unrelated due to the random nature of memory corruption.
> 
> Got your point, after upgrading to LATEST(1.9.6) till now(after nearly 15hrs), we have not hit any flb crashes. We are keeping an eye on it. If we hit the issue then we will run the same test with valgrind and provide you requested logs.

@ptsneves 
We have monitored the td-agent-bit with the LATEST(1.9.6) for couple of days and we have not observed any crashes. Thus closing this issue.
Thank for your active support.
