### ISSUE TITLE
Did Elasticsearch out plugin support compression yet?

### ISSUE THREAD

**Issue by april4** [fluent/fluent-bit#5588]
**Is your feature request related to a problem? Please describe.**

Current es out plugin seems not enabled compression, and also no params/option to controll that.  
If sent out content not compressed, then Elasticsearch's response will also no compress, which will cause significant in/out bandwidth usage, especially when Fluent-bit and Elasticsearch are not in same region.
  
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

ref: https://github.com/fluent/fluent-bit/issues/3971

**Comment by patrick-stephens** [comment]
https://github.com/fluent/fluent-bit/pull/5557

**Comment by rarruda** [comment]
It should now support compression (as of 1.9.7 IIRC), but the PR for documenting the feature has not been approved/merged yet.

**Comment by rarruda** [comment]
The (currently unmerged) PR with the documentation on how to enable compression can be found at: https://github.com/fluent/fluent-bit-docs/pull/824

**Comment by rarruda** [comment]
@april4 Short answer: yes, compress is now supported in the elasticsearch output. 

See https://docs.fluentbit.io/manual/v/2.0-pre/pipeline/outputs/elasticsearch and compress parameter on how to configure it in the latest version of fluentbit.
