### ISSUE TITLE
Elasticsearch out plugin index name not generated by local time zone

### ISSUE THREAD

**Issue by april4** [fluent/fluent-bit#5589]
## Bug Report

**Describe the bug**

The es out plugin generated index name's date part is based on UTC, not host that run fluent-bit's local time.  
i.e.
local time is: 2022-06-18T02:56:20.436299200+03:00
but the es out plugin generated index name will still be indexname-20220617, only when local time is "2022-06-18T03:00:00.000000000+03:00" or later the index name will change to 20220618.
Seems it only care UTC time, this is a little bit inconvenient.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
2022-06-18 02:53:15.913 [operate] INFO  ...
2022-06-18 03:03:05.419 [msg] INFO  ...
2022-06-18 03:04:17.710 [submit] INFO  ...
```
- Steps to reproduce the problem:
Original parser & output conf:  
```
[PARSER]
    Name parser0
    Format regex
    Regex ^(?<time>\d+\-.*\.\d+)\s+(?<msg>\[.*)$
    Time_Key time
    Time_Format %Y-%m-%d %H:%M:%S.%L
    Time_Offset +0300

[OUTPUT]
    Name es
    Match *
    Host 192....
    Port 9200
    HTTP_User user
    HTTP_Passwd password
    Logstash_Format On
    Logstash_Prefix log-app
    Logstash_DateFormat %Y%m%d
    Time_Key_Nanos On
```
This will work like previous I described above situation, when local time is "2022-06-18T02:56:20.436299200+03:00",
generated index name will still be log-app-20220617.  
Later I added "Current_Time_Index On" to output conf:
```
[OUTPUT]
    Name es
    Match *
    Host 192....
    Port 9200
    HTTP_User user
    HTTP_Passwd password
    Logstash_Format On
    Logstash_Prefix log-app
    Logstash_DateFormat %Y%m%d
    Time_Key_Nanos On
    Current_Time_Index On
```
As the document say "Current_Time_Index On" will make it `Use current time for index generation instead of message record`.  
I expected it to generate new index name by local time, like when local time is "2022-06-18T02:56:20.436299200+03:00", the index name will be "indexname-20220618", not still be "indexname-20220617".  
Also, "Current_Time_Index On" will make log entry stored in Elasticsearch's timestamp become fluent-bit host's local time, not extracted from log record's timestamp like "Current_Time_Index Off" before.  
That's odd, may I understand it in the wrong way.

**Expected behavior**

Index name's date part generated by local time, not UTC.

**Screenshots**

**Your Environment**

* Version used: Fluent Bit v1.9.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: Linux x86_64
* Operating System and version:  CentOS-7
* Filters and plugins:

**Additional context**

**Comment by oneisall8955** [comment]
Is it supported now?
