### ISSUE TITLE
Azure Data Explorer (Kusto) Output Plugin

### ISSUE THREAD

**Issue by papigers** [fluent/fluent-bit#5591]
**Is your feature request related to a problem? Please describe.**
There's no way to directly ingest logs collected by fluent-bit into a kusto cluster.

**Describe the solution you'd like**
It would be great if we'd have a kusto output plugin.
The output would require the user to configure credentials in the form of AAD application details (tenant ID, client ID, and client secret), the cluster's ingestion endpoint, database and table names. 
Additionally it would be great to allow the user to configure [ingestion mapping](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings#json-mapping), to customize how records are mapped into the table. 

**Describe alternatives you've considered**
The alternative is using the azure blob output, and to configure the cluster to watch the blob and ingest from there, but this solution is more complicated, slow (in terms of latency), and pricey. 

**Additional context**
I'd be happy to contribute myself, and create the plugin on my own. I already have some snippet that retrieves an oauth AAD token, and ingests json data to kusto, so I don't expect it to take too long.
I should probably note that I'm a rookie at C, but I'd still be happy to contribute :)

**Comment by patrick-stephens** [comment]
Always happy to have contribution but take note of the various contributing docs to give you pointers on what to do: 
* https://github.com/fluent/fluent-bit/blob/master/CONTRIBUTING.md
* https://docs.fluentbit.io/manual/development/developer-guide
Remember as well that it will have to compile for all supported targets (Windows and Linux) so there are various utility methods to help with this and the CI will check too once you submit a PR.

**Comment by papigers** [comment]
Thanks @patrick-stephens

I'd be sure to check these out before submitting my PR :)

**Comment by agup006** [comment]
In the iinterim @papigers it seems we could use the following REST API interface: https://github.com/MicrosoftDocs/dataexplorer-docs/blob/main/data-explorer/kusto/api/rest/streaming-ingest.md with Fluent Bit out HTTP plugin

**Comment by papigers** [comment]
@patrick-stephens just letting know I created a PR :)

**Comment by patrick-stephens** [comment]
@papigers is this just awaiting a release now?

**Comment by papigers** [comment]
@patrick-stephens AFAIK, yes.

**Comment by patrick-stephens** [comment]
yeah I can't see it in 1.9.8 so must be on the 2.0 branch
