### ISSUE TITLE
How about the kafka output plugin to call rd_kafka_flush when shutdown?

### ISSUE THREAD

**Issue by jinyongchoi** [fluent/fluent-bit#5593]
## Bug Report

**Describe the bug**
When fluent-bit shutdown for out_kafka plugin with rdkafka.linger.ms and rdkafka.batch.size and then we show the warn message and lose the message.
Even if the Grace option is set to a high value.

**To Reproduce**

- Example log message if applicable:
```
[2022/06/20 06:30:53] [ warn] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:app]: Producer terminating with 5000 messages (285000 bytes) still in queue or transit: use flush() to wait for outstanding message delivery
```
- Steps to reproduce the problem:
1) Run kafka broker and create topic ( report_test ).
2) mkdir storage path ( mkdir -p /var/lib/td-agent-bit/ )
3) Run fluent-bit with config.
```
/opt/td-agent-bit/bin/td-agent-bit -v -c /etc/td-agent-bit/td-agent-bit.conf
```
4) Write to the log file of tail plugin watched.
```
#!/bin/bash
for i in {1..5000}
do
    echo 'TEST' >> /root/test.log
done
```
5) Shutdown fluent-bit (Ctrl + C)
6) Check the warn log and message in kafka topic.
7) if see the warn message in log, we lose the message.

**Expected behavior**

When fluent-bit shutdown, all message must be flush to kafka if possible.

**Screenshots**

**Your Environment**

* Version used:
  * 1.9.4
* Configuration:
```
[SERVICE]
    flush 600
    grace 120
    log_level trace
    storage.path /var/lib/td-agent-bit/
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 10M

[INPUT]
    Name tail
    Path /root/test.log
    Tag test
    DB /var/lib/td-agent-bit/tail.db
    DB.sync normal

[OUTPUT]
    name kafka
    match test
    Brokers x.x.x.x:9092

    Topics report_test
    timestamp_format iso8601
    queue_full_retries 0
    Retry_Limit False

    rdkafka.log.connection.close false
    rdkafka.compression.codec gzip
    rdkafka.compression.level 5

    rdkafka.batch.size 10485760
    rdkafka.linger.ms 10000

    rdkafka.request.required.acks all
    rdkafka.enable.idempotence true
    rdkafka.max.in.flight.requests.per.connection 1
    rdkafka.message.timeout.ms 0
    rdkafka.message.send.max.retries 2147483647
    rdkafka.retries 2147483647

```
* Environment name and version (e.g. Kubernetes? What version?):
  * Docker version 20.10.16
  * no k8s
* Server type and version:
* Operating System and version:
  * CentOS docker image
  * CentOS Linux release 7.9.2009 (Core)
* Filters and plugins:
  * out_kafka

**Additional context**

So, what if the `cb_kafka_exit` function in kafka.c to call the `rd_kafka_flush` function of rdkafka?
like this.
```
in kafka_config.c
int flb_out_kafka_flush_force(struct flb_out_kafka *ctx, struct flb_config *config)
{
    if (!ctx) {
        return 0;
    }

    if (ctx->kafka.rk) {
        rd_kafka_flush(ctx->kafka.rk, config->grace * 1000);
    }
}

in kafka.c
static int cb_kafka_exit(void *data, struct flb_config *config)
{
    struct flb_out_kafka *ctx = data;

    flb_out_kafka_flush_force(ctx, config); <= call the function
    flb_out_kafka_destroy(ctx);
    return 0;
}

```

is it bad idea?

**Comment by patrick-stephens** [comment]
Could you submit a PR for it then we can review and it'll speed up any change then for you?
