### ISSUE TITLE
FEATURE REQUEST - Prometheus Output Plugin or format

### ISSUE THREAD

**Issue by snowjunkie** [fluent/fluent-bit#560]
Is there any plan or option to output the system collected metrics to Prometheus?

I know that you expose an endpoint for the fluentbit agent metrics itself, just wondering whether we can have the other metrics from the system plugins exported too like:

CPU, MEM. Process, Health, Disk etc..

I guess there's a memory overhead of holding them for the scrape to occur.
Not sure whether there's a preferred route to this, or whether you'd expect to push them to a Fluentd aggregator instance instead?

**Comment by edsiper** [comment]
do you mean to gather metrics from the running container or running node ?

**Comment by snowjunkie** [comment]
Yes that's the intent.  FluentBit has a significantly smaller footprint than other solutions, so would be awesome if it could export these node or container metrics.

**Comment by discordianfish** [comment]
As a maintainer of the prometheus node-exporter I might be biased but I think providing these metrics is a very different concern than the logshipping fluent-bit does, so not sure it makes sense to add that here?

**Comment by Globegitter** [comment]
While I do agree that duplicating the works of the node-exporter seems a bit much a generic prometheus output plugin, that makes it possible to turn logs into metrics does sound pretty great and something that would imo be quite useful.

**Comment by snowjunkie** [comment]
Ok so maybe my request hasn't been clear.
As far as I understand fluentbit already has inputs to collect cpu, memory, io, disk so in that regard I believe it is already duplicating 'some' node exporter features.
My request was more about providing the capability to expose the above mentioned collected data for Prometheus.

For context, my rationale here is that FluentBit IMO is ideally positioned to be the best lightweight collector capable of BOTH text and numeric data i.e. logs and metrics.  Other such solutions tend to focus on one or the other, and as much as I recognise that fluentbit is predominantly interested in logs, the fact remains that it can and does collect some base useful metrics.  So as a way to reduce the footprint on the host, a single lightweight agent would really be appealing.

Hopefully that helps explain my ask, and hopefully my current understanding is correct.

**Comment by edsiper** [comment]
FYI: this is something we already started (at least from a design perspective). WIP

**Comment by Isnor** [comment]
I understand this is an older issue, I just wanted to chime in and say I would very much like this feature. My use case is parsing log files that have performance and progress metrics (using filters) and charting those in real-time (e.g. the bitrate or speed of an encoding process). Right now I have this somewhat working by dumping the parsed metrics to InfluxDB and using Grafana to visualize the data, but I'm interested in Prometheus more than InfluxDB and I prefer fluent-bit to the native logging routers for prometheus and influx (in part due to my production environment being AWS).

Thanks a ton @edsiper !

**Comment by edsiper** [comment]
noted

**Comment by TechIsCool** [comment]
Just adding on another one. I would love to use stream processing to collect some metrics for prometheus.
Examples
  - I want to know which kubernetes namespace / pod is producing logs
  - I want to know how many logs are error vs warning etc.

**Comment by Stono** [comment]
We'd love this too.  We currently use fluentbit to get everything into ES, but the we run another process which queries ES to find level > error and alert on it.

It'd be a far simpler pipeline if we also had metrics with dimensions of the kubernetes pod, and log level

**Comment by agup006** [comment]
@Stono @TechIsCool  we have some work starting on this, would you be open to a call to give us comments on design / prototypes?

**Comment by Stono** [comment]
Absolutely :-)

**Comment by TechIsCool** [comment]
Yes, I have time for a meeting to discuss this.

**Comment by kyrogue** [comment]
Love to have a prometheus output too. Use case is this,

1. fluentbit input for CPU metrics etc
2. output as prometheus format 
3. prometheus will scrape for the metrics

So now fluentbit can be used for log and metrics

**Comment by TechIsCool** [comment]
@agup006 Wanted to check and see if this was still being looked into. The meeting sounded promising when we talked in March. I see #2968 exists and has some improvement that are beneficial as well.

**Comment by agup006** [comment]
Hey all, this is definitely still underway for 1.8, some portions are already merged into main branch. we are aiming for that to be released later in June

**Comment by vrivellino** [comment]
Question for the fluent-bit maintainers (@agup006 @edsiper et al): Will the feature improvements that will address this issue (and possible #2968) allow fluent-bit users to record metrics based based on tag?

We recently migrated from fluentd to fluent-bit, and out fluentd configs implemented the following example:

https://docs.fluentd.org/monitoring-fluentd/monitoring-prometheus#step-1-counting-incoming-records-by-prometheus-filter-plugin

Input metrics (and even output metrics, to some degree, when we were sending some namespaces to null) per tag is extremely useful when tracking down broken applications (or when a software engineer prints SQL statements to stdout in a dev environment for debugging).

**Comment by agup006** [comment]
With 1.8.2 this is live! We are working on Prometheus Remote Write output plugin and support Prometheus Exporter with custom label support today

Docs:
1. Input - https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-exporter
2. Output - https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-exporter

Would love to chat with folks if they have questions or feature requests as we are going to be working on more metric support throughput 1.8.x

**Comment by jkowall** [comment]
> With 1.8.1 this is live! We are working on Prometheus Remote Write output plugin and support Prometheus Exporter with custom label support today

Is there a tracking issue for remote write support? This is a common request from users of fluentbit we hear. Thanks!

**Comment by edsiper** [comment]
@jkowall https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-remote-write
