### ISSUE TITLE
In the latest Windows packages, the "path" parameter in in_tail does not track the wildcard path "/.. / *. Log"

### ISSUE THREAD

**Issue by lihuilang** [fluent/fluent-bit#5611]
## Bug Report

**Describe the bug**
The tail input plug-in cannot track wildcard file paths

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**
![1655889373(1)](https://user-images.githubusercontent.com/107991152/174992372-7d5ff365-1c0b-4ba4-b1cc-be1011be784f.png)

**Your Environment**

* Version used:fluentbit v1.9.4
* Configuration:
* 
![1655889373(1)](https://user-images.githubusercontent.com/107991152/174992691-b304c0f8-4dd6-485e-b680-ffd0270879cf.png)

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
How do you know it is not tracking? 
Are those logs are definitely being updated? `tail` functions as `tail -f` by default, with a `db` set it will start from the last offset in the `db` so if you run multiple times it will not pick up anything new in the file unless that file is being updated whilst being tailed.

Can you provide a full log with `log_level debug` in the `[SERVICE]` configuration?
What happens if you use the native `\` slashes for Windows paths?
Did this configuration previously work (in what version) and now does not?
Which version of Windows are you using and arch (32/64?)?
What is your full config?

**Comment by lihuilang** [comment]
> How do you know it is not tracking? Are those logs are definitely being updated? `tail` functions as `tail -f` by default, with a `db` set it will start from the last offset in the `db` so if you run multiple times it will not pick up anything new in the file unless that file is being updated whilst being tailed.
> 
> Can you provide a full log with `log_level debug` in the `[SERVICE]` configuration? What happens if you use the native `\` slashes for Windows paths? Did this configuration previously work (in what version) and now does not? Which version of Windows are you using and arch (32/64?)? What is your full config?

"/" can be used to trace a single file, such as "c:/tmp/record.log", but the trace log file is invalid under the "c:/tmp/*.log" configuration, and replacing "/" with "" can trace the contents of the log file under the wildcard path, but even if db is configured, the rotation log is collected repeatedly

**Comment by lihuilang** [comment]
> > How do you know it is not tracking? Are those logs are definitely being updated? `tail` functions as `tail -f` by default, with a `db` set it will start from the last offset in the `db` so if you run multiple times it will not pick up anything new in the file unless that file is being updated whilst being tailed.
> > Can you provide a full log with `log_level debug` in the `[SERVICE]` configuration? What happens if you use the native `\` slashes for Windows paths? Did this configuration previously work (in what version) and now does not? Which version of Windows are you using and arch (32/64?)? What is your full config?
> 
> "/" can be used to trace a single file, such as "c:/tmp/record.log", but the trace log file is invalid under the "c:/tmp/*.log" configuration, and replacing "/" with "" can trace the contents of the log file under the wildcard path, but even if db is configured, the rotation log is collected repeatedly

"/" can be used to trace a single file, such as "c:/tmp/record.log", but the trace log file is invalid under the "c:/tmp/*.log" configuration, and replacing "/" with "\" can trace the contents of the log file under the wildcard path, but even if db is configured, the rotation log is collected repeatedly

**Comment by lihuilang** [comment]
> > > How do you know it is not tracking? Are those logs are definitely being updated? `tail` functions as `tail -f` by default, with a `db` set it will start from the last offset in the `db` so if you run multiple times it will not pick up anything new in the file unless that file is being updated whilst being tailed.
> > > Can you provide a full log with `log_level debug` in the `[SERVICE]` configuration? What happens if you use the native `\` slashes for Windows paths? Did this configuration previously work (in what version) and now does not? Which version of Windows are you using and arch (32/64?)? What is your full config?
> > 
> > 
> > "/" can be used to trace a single file, such as "c:/tmp/record.log", but the trace log file is invalid under the "c:/tmp/*.log" configuration, and replacing "/" with "" can trace the contents of the log file under the wildcard path, but even if db is configured, the rotation log is collected repeatedly
> 
> "/" can be used to trace a single file, such as "c:/tmp/record.log", but the trace log file is invalid under the "c:/tmp/*.log" configuration, and replacing / with \ can trace the contents of the log file under the wildcard path, but even if db is configured, the rotation log is collected repeatedly



> How do you know it is not tracking? Are those logs are definitely being updated? `tail` functions as `tail -f` by default, with a `db` set it will start from the last offset in the `db` so if you run multiple times it will not pick up anything new in the file unless that file is being updated whilst being tailed.
> 
> Can you provide a full log with `log_level debug` in the `[SERVICE]` configuration? What happens if you use the native `\` slashes for Windows paths? Did this configuration previously work (in what version) and now does not? Which version of Windows are you using and arch (32/64?)? What is your full config?

"/" can be used to trace a single file, such as "c:/tmp/record.log", but the trace log file is invalid under the "c:/tmp/*.log" configuration, and replacing / with \ can trace the contents of the log file under the wildcard path, but even if db is configured, the rotation log is collected repeatedly

**Comment by patrick-stephens** [comment]
So, I think you're saying that `\` works with wildcards but `/` does not for Windows. To be honest I'm not surprised with Windows path handling being "interesting".

Can you answer the other questions as well please?

> Can you provide a full log with log_level debug in the [SERVICE] configuration?
> Did this configuration previously work (in what version) and now does not?
> Which version of Windows are you using and arch (32/64?)?
> What is your full config?

**Comment by lihuilang** [comment]
> 



> So, I think you're saying that `\` works with wildcards but `/` does not for Windows. To be honest I'm not surprised with Windows path handling being "interesting".
> 
> Can you answer the other questions as well please?
> 
> > Can you provide a full log with log_level debug in the [SERVICE] configuration?
> > Did this configuration previously work (in what version) and now does not?
> > Which version of Windows are you using and arch (32/64?)?
> > What is your full config?



> So, I think you're saying that `\` works with wildcards but `/` does not for Windows. To be honest I'm not surprised with Windows path handling being "interesting".
> 
> Can you answer the other questions as well please?
> 
> > Can you provide a full log with log_level debug in the [SERVICE] configuration?
> > Did this configuration previously work (in what version) and now does not?
> > Which version of Windows are you using and arch (32/64?)?
> > What is your full config?

1、In \ state, fluentbit cannot collect log records even if there is a new log appended to the rotation log. The fluentbit log content is as follows, and no error is reported.

2、This is my first test of fluentbit, and the version is 1.9.5

3、Version 1.9.5, arch 32

4、full config
![1656467777(1)](https://user-images.githubusercontent.com/107991152/176334501-6c78f529-619b-45dc-9561-a2a2520c929e.png)

**Comment by i12batree** [comment]
I also have this issue on windows

[INPUT]
    Name        tail
    Path        C:/temp/Log2023033112.txt
    DB          C:/temp/fluent.db
    Tag         Test

[OUTPUT]
    name  stdout
    match *

works fine

 [2023/03/31 12:08:30] [debug] [input:tail:tail.0] 1 new files found on path 'C:/temp/Log2023033112.txt'
[2023/03/31 12:08:30] [debug] [stdout:stdout.0] created event channels: read=864 write=868
[2023/03/31 12:08:30] [ info] [sp] stream processor started
[2023/03/31 12:08:30] [ info] [output:stdout:stdout.0] worker #0 started
[2023/03/31 12:08:30] [debug] [input:tail:tail.0] inode=165788761282763180 file=C:\temp\Log2023033112.txt promote to TAIL_EVENT
....
then the log contents output ok, tail works fine

BUT

[INPUT]
    Name        tail
    Path        C:/temp/Log*.txt
    DB          C:/temp/fluent.db
    Tag         Test

you just get
2023/03/31 12:40:50] [debug] [input:tail:tail.0] 0 new files found on path 'C:/temp/Log*.txt'

patterns

Log[1-9][1-9][1-9][1-9][1-9][1-9][1-9][1-9][1-9][1-9].txt

and

Log??????????.txt

also fail


this means tail is useless to me as it cannot read our log files, as they are dated.
