### ISSUE TITLE
Add Support for Golang's logfmt

### ISSUE THREAD

**Issue by blaggacao** [fluent/fluent-bit#562]
Please consider adding a parser, similar to json, for https://godoc.org/github.com/kr/logfmt
which is the default way of logging in everything golang, if no TTY is attached.

About 40% of my infrastructure containers speak this format, this might be quite average in some containerized environments, where everything's golang now a days...

**Comment by blaggacao** [comment]
@edsiper I'd put a bounty out of current budget of USD 150,- on it :stuck_out_tongue_winking_eye: Let me know where to reward...

**Comment by edsiper** [comment]
@blaggacao please coordinate with @manuelluis, he just implemented this feature.

**Comment by blaggacao** [comment]
Great news. @manuelluis, could you contact me on dar@xoe.solutions for tx details.

**Comment by bluebike** [comment]
Just comment to current structure of parsers. 

I'm implementing parser for MariaDB audit logging  currently it's just a filter,
but I could make that parser also, becuase it can parse (some) csv-files.

Currently parsers are "hardcoded" in flb_parsers.c/h.     
Maybe  parsers should be refactored to plugins (or similar structure). 
There should be some kind of  init/config,  execute, close methods for those.
