### ISSUE TITLE
'timestamp' value not set correctly when multiline-parser's regexp doesn't match a line

### ISSUE THREAD

**Issue by zerroage** [fluent/fluent-bit#5624]
## Bug Report

**Describe the bug**

When using fluent-bit 1.8+ multiline parser configuration, the internal `timestamp` value doesn't get updated properly if a multiline parser's regex doesn't match a log line.

**To Reproduce**

To reproduce the issue, use the configuration files provided below.

**fluentbit.conf**
```
[SERVICE]
    Daemon              Off
    Flush               1
    Log_Level           trace
    Parsers_file        parsers.conf

[INPUT]
    Name                tail
    Path                *.log
    Read_from_Head      True
    Multiline.parser    simple-multiline-parser
    Tag                 kube.*
    Mem_Buf_Limit       2MB
    Skip_Long_Lines     On

[OUTPUT]
    Name                file
    Match               *
    Path                output_dir
    Mkdir               True
```
**parsers.conf**
```
[MULTILINE_PARSER]
    Name          simple-multiline-parser
    Type          regex
    Flush_timeout 1000
    Parser        docker
    key_content   log
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern   | next state
    # ------|---------------|-----------------|-----------
    Rule      "start_state"   "^Line.*"        "cont"
    Rule      "cont"          "^(?!Line).*"    "cont"
```
**example.log**
```
Line 1
- subline 1
- subline 2
Line 2
Line 3
```

**Success run**
* Put all the above files into a single directory
* Execute in the same directory the following command:
```shell
fluent-bit -c fluentbit.conf
```
* In the `output_dir` directory, check the output log file. In my case, it was:

**Successful output**
```
kube.example.log: [1655999156.400745600, {"log":"Line 1\n- subline 1\n- subline 2"}]
kube.example.log: [1655999156.400757400, {"log":"Line 2"}]
kube.example.log: [1655999156.400878400, {"log":"Line 3"}]
```
So we can see that it worked as expected and multiple lines were joined into a single line. Please also take note of the nanoseconds part of the timestamps – they all are different.

**Steps to reproduce the problem:**

* Now alter the `example.log` file as shown below:

**example.log**
```
Another Line 1
- subline 1
- subline 2
Another Line 2
Another Line 3
```
* Execute fluent-bit once again:
```shell
fluent-bit -c fluentbit.conf
```
* And check the output:
```
kube.example.log: [1655999695.803012700, {"log":"Another Line 1"}]
kube.example.log: [1655999695.803012700, {"log":"- subline 1"}]
kube.example.log: [1655999695.803012700, {"log":"- subline 2"}]
kube.example.log: [1655999695.803012700, {"log":"Another Line 2"}]
kube.example.log: [1655999695.803012700, {"log":"Another Line 3"}]
```

Please notice that the `timestamp` value is exactly the same for all log records.

**Expected behavior**

The `timestamp` value should be set correctly to the current time moment. The initlal `timestamp` value shouldn't be cached and re-used.

**Your Environment**

* Version used: 1.9.4 and 1.9.5 (didn't test earlier versions)
* Environment name and version:
  * Initially the problem was observed on several Kubernetes clusters (tested on v1.19.2 and v1.24.0)
  * Then I managed to reproduce it locally in a command-line mode on Ubuntu (22.10) with the same result
* Filters and plugins:
  * multiline parser 

**Additional context**

The internal `timestamp` value is used by the *Elasticsearch* output plugin to generate a `@timestamp` value, which is used as an index field by default. Having all values the same makes new log lines almost undiscoverable in tools like Kibana. 

There are several workarounds for this issue.

1. Use the `Current_Time_Index On` setting for the [*Elasticsearch*](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch) output plugin
2. Use another field (for example, `time` when working with docker logs) as a primary index in Elasticsearch
3. Write a Lua-filter to generate a `timestamp` value (probably by parsing the `time` field when working with docker logs)

**Comment by manster18** [comment]
HI guys! Do you have any updates?

**Comment by RicardoAAD** [comment]
Hello @vovtz and @manster18 

The fix for this issue was included in the master branch and backported to 1.9; The current behavior when the multiline parser doesn't match is to add the timestamp when the record was processed. 

https://github.com/fluent/fluent-bit/pull/6371
https://github.com/fluent/fluent-bit/pull/6381



Your config and log example:

test log:
 cat example2.log

```
Another Line 1
- subline 1
- subline 2
Another Line 2
Another Line 3
```

Output after processing the log example:
$ cat output_dir/kube.example2.log

```
kube.example2.log: [1675974320.920710000, {"log":"Another Line 1"}]
kube.example2.log: [1675974320.920711000, {"log":"- subline 1"}]
kube.example2.log: [1675974320.920711000, {"log":"- subline 2"}]
kube.example2.log: [1675974320.920712000, {"log":"Another Line 2"}]
kube.example2.log: [1675974320.920712000, {"log":"Another Line 3"}]
```


cat fluent-bit.conf
```
[SERVICE]
    Daemon              Off
    Flush               1
    Log_Level           trace
    Parsers_file        parsers.conf

[INPUT]
    Name                tail
    Path                *.log
    Read_from_Head      True
    Multiline.parser    simple-multiline-parser
    Tag                 kube.*
    Mem_Buf_Limit       2MB
    Skip_Long_Lines     On

[OUTPUT]
    Name                file
    Match               *
    Path                output_dir
    Mkdir               True
```
cat parsers.conf
```
[MULTILINE_PARSER]
    Name          simple-multiline-parser
    Type          regex
    Flush_timeout 1000
    Parser        docker
    key_content   log
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern   | next state
    # ------|---------------|-----------------|-----------
    Rule      "start_state"   "^Line.*"        "cont"
    Rule      "cont"          "^(?!Line).*"    "cont"
```

**Comment by thedayofcondor** [comment]
Hi, I am having the same issue, is this fix in the latest version?

I can reproduce it using 2.0.9 and 1.9.10 

My usage is slightly different as I am using multiline as a filter - every line in my log has a timestamp, so I have a regex parser stripping the log timestamp (without `Time_Key`) as I prefer using the parsing time (my log time has seconds granularity)

```
[PARSER]
  Name                logline
  Format              regex
  Regex               ^(?<discard>.+? .+?) (?<message>.+)$
```

and then I use multiline to concatenate the `message` - but all the multiline messages are lumped with the timestamp of the first multiline parsing.

**Comment by leonardo-albertovich** [comment]
I think you should open a new issue where you thoroughly explain your issue with reproduction instructions if possible.
If you want to test the current version you could use the container in `ghcr.io/fluent/fluent-bit/test/master` which I built yesterday.

**Comment by thedayofcondor** [comment]
Thank you for the quick response, I have tried the master version and that does not solve it either, I will open a new issue trying to provide a sample log with some trimmed out rules, it could well be I am doing something wrong.

Unfortunately for now I have to resort to forgetting about multiline parsing and  try to strip the CR when logging - I have over 4000 multiline messages lumped into the same timestamp in cloudwatch...
