### ISSUE TITLE
Suggesting to Revisit #2498

### ISSUE THREAD

**Issue by GLStephen** [fluent/fluent-bit#5629]
There is an existing bug reporting which went stale.

https://github.com/fluent/fluent-bit/issues/2498

I suggest revisiting this item. Auto conversion of this type is causing major issues for us with guids that contain numbers and letters. If the GUID starts with a number then it converts it to an integer. There seems to be no way to disable this auto conversion other than to prepend values with junk data.

**Comment by GLStephen** [comment]
No response? This should be reconsidered. Magic handling of conversion of data types that truncates data at the ingestion layer is bad form. Magic conversion to a data type (string for instance) that maintains the data is much more interoperable.

**Comment by vlcinsky** [comment]
I hit exactly the same issue.
The conversion of strings into integers is:
- undocumented
- not being implemented correctly

I would invite an implementation which does conversion to integer only on numbers.

**Comment by GLStephen** [comment]
Still not really stale!

**Comment by sameerchandra** [comment]
@GLStephen We are facing this issue as well. This is a really bad implementation of forced type conversion. Any String that starts with numbers (most uids) are being converted to numbers. Do you have any workarounds for this?

**Comment by GLStephen** [comment]
@sameerchandra not a good one, we added a string value "::" to the front of our GUIDs at the ingestion point so that they are always processed as strings, then we pull that out later in a later transformation process. It's not ideal for sure.

**Comment by leonardo-albertovich** [comment]
TBH I'm the least knowledgeable around when it comes to the SP, I don't even know how to use it but if you are willing to help me get started with the SP and reproduce the issue I'll give it a try next week (sorry but I'm completely booked this week).

**Comment by GLStephen** [comment]
@leonardo-albertovich I saw you on some merges and thought I would reach out to someone who at least seemed more active on the project. Would you recommend I reach out to someone else on the project? Fixing it is one thing, but at least getting it evaluated as "will fix" in the near term would be nice.

**Comment by sameerchandra** [comment]
@leonardo-albertovich I can reliably reproduce this issue. Let me know if you need more details.

**Comment by leonardo-albertovich** [comment]
Let's take a look at it next week to determine the complexity of the issue and then we'll see if it's something I can fix or if it's something we can ping past contributors about.

As for the reproduction, I'd really appreciate it if you shared it with me @sameerchandra but please be aware that I won't be able to look at it until next week.

Feel free to reach out to me in slack or tag me again if you want to stay on top of it.

**Comment by sameerchandra** [comment]
@leonardo-albertovich thanks for the response. I will provide the required details for reproducing the issue and also understand that you won't be able to look into this till next week.

**Comment by GLStephen** [comment]
Please add exempt-stale to this item. This is important to resolve.

**Comment by nokute78** [comment]
Note:
https://github.com/fluent/fluent-bit/pull/7005 is merged into master.
