### ISSUE TITLE
Question: Why no true multiline regex parsing is supported?

### ISSUE THREAD

**Issue by blaggacao** [fluent/fluent-bit#564]
To the extend of an expert opinion to feed back to [this](https://www.postgresql.org/message-id/flat/886A32D6-110D-4F4A-B3D1-5D5AEB86BC99%40thebuild.com#886A32D6-110D-4F4A-B3D1-5D5AEB86BC99@thebuild.com) postgres logging thread, especially [this](https://www.postgresql.org/message-id/886A32D6-110D-4F4A-B3D1-5D5AEB86BC99%40thebuild.com)  suggestion, the question I rise is:

#### "What is the underlying reason no true multi line regex parsing is supported?"

I assumed performance reason in the discussion, but maybe you can elaborate as an expert to inform the discussion on the PostgreSQL mailing list?

Quoting my "best guess" response in that thread:
>I believe the (valid) root reason behind this assumption [one line one event] is to care for resource consumption during stream processing. There are solutions to that problem (as the multi line mode of fuent bit already exposed before in this thread), but they are not specifically reliable, nor easy to maintain. Not claiming this assumption does imply parsing of a rolling set of log lines with previously unkown cardinality. That's expensive on computing resources. I don't have actual numbers, but it doesn't seem too far fetched, neither.

**Comment by edsiper** [comment]
Hi @blaggacao, 

> What is the underlying reason no true multi line regex parsing is supported?

From a log processor perspective and talking specifically Fluentd and Fluent Bit, our _input_ streams can be anything coming from the file system (log files, systemd..) or through the network (tcp, udp). Note that not all messages can be processed using a regex engine, so what make sense is to collect each each _message_ and consider it a log entry, from a file system/log file perspective this means a 'line'. 

So it's time better to correlate multiline logs after they have been generated than letting the regex engine validate an entry over and over until it succeed. Also consider that in not all scenarios full multiline logs are flushed right away, sometimes there are delays.

Btw, we would be happy to work together with PostreSQL community to support an official parser for your multiline logs. Have you faced any specific issue with our multiline Parser mode ?

**Comment by blaggacao** [comment]
Currently, as a facilitator, I try to distill the problems. I don't really feel in the position to speak for the Postgres community as I joined the mailing list only to rise this issue, but what's so far on the problem definition table is:

**Core-Problem:** "Multi line logs are unnecessarily inconvenient to parse and are not compatible with the design of some (commonly used) logging aggregation flows."

**2nd-order Problem 1:** "Logging space increasingly moves towards the adoption of structured logging formats around json / logfmt. Compatibly options (plural!) with main stream (not necessarily standard) tooling is a value proposition of it's own kind. It helps increase odds of responsible deployments and improves the overall experience in adopting PostgreSQL."

**2nd-order Problem 2:** "Encoding of logging can differ per database, this inhibits the objective of reliable log stream parsing"

I'll update as issues rise in the mailing list...

**Comment by agup006** [comment]
Hey all, we have some work scheduled for multiline in this release 1.7.x - I'd like to close this issue for cleanup purposes. If there are updates to the discussion or need for follow-up please re-open

**Comment by edsiper** [comment]
just for the record:

# Multiline Update

As part of Fluent Bit v1.8, we have released a new Multiline core functionality. This new big feature allows you to configure new `[MULTILINE_PARSER]`s that support multi formats/auto-detection, new multiline mode on Tail plugin, and also on v1.8.2 (to be released on July 20th, 2021) a new Multiline Filter. 

For now, you can take at the following documentation resources:

- [Multiline Parsers / Concepts and Configuration](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing)
- [Tail + New Multiline Core Feature](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support)
- [New Multiline Filter](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace)

Documentation pages now point to complete config examples that are available on our repository.

Thanks everyone for supporting this!
