### ISSUE TITLE
How to configure fluent-bit can be high-availability as fluentd

### ISSUE THREAD

**Issue by Barbazoo** [fluent/fluent-bit#565]
I want to configure fluent-bit as td-agent collection application logs, but I can't find some features in fluentd, such as high-availability,
How to configure fluent-bit can be high-availability as fluentd,thanks very much

**Comment by edsiper** [comment]
hi @Barbazoo 

the only HA mode supported is in-memory buffering, meaning: if the logs cannot be shipped to the destination there is a retry logic in place.

If you refer to HA where having primary and secondary destinations as well with balancing support that feature has not been implemented yet.

**Comment by Barbazoo** [comment]
@edsiper thank you for your answer and thank you anyway

**Comment by karthikeayan** [comment]
Any future plans to implement this for fuent-bit?
