### ISSUE TITLE
Export DNS metrics

### ISSUE THREAD

**Issue by laurivosandi** [fluent/fluent-bit#5654]
We had Fluent bit hang up due to DNS resolution failure, but it seems `/api/v1/metrics/prometheus` endpoint does not provide any useful metrics to monitor for this. The `fluentbit_output_errors_total` stays at 0

**Comment by EppO** [comment]
I think this feature request is legit, we're also having some DNS errors that would be worth exposing as stats:
```
[2022/10/18 13:02:52] [ warn] [net] getaddrinfo(host='logging-operator-logging-fluentd.logging-operator.svc', err=12): Timeout while contacting DNS servers
```

**Comment by laurivosandi** [comment]
We just gave up using Fluent Bit. It just does not work reliably
