### ISSUE TITLE
Error when running cmake

### ISSUE THREAD

**Issue by davidacb** [fluent/fluent-bit#5661]
## Bug Report

**Describe the bug**
When doing a docker build if fails when doing:
```
RUN cmake -DFLB_RELEASE=On \
          -DFLB_TRACE=Off \
          -DFLB_JEMALLOC=On \
          -DFLB_TLS=On \
          -DFLB_SHARED_LIB=Off \
          -DFLB_EXAMPLES=Off \
          -DFLB_HTTP_SERVER=On \
          -DFLB_IN_EXEC=Off \
          -DFLB_IN_SYSTEMD=On \
          -DFLB_OUT_KAFKA=On \
          -DFLB_OUT_PGSQL=On \
          -DFLB_NIGHTLY_BUILD="$FLB_NIGHTLY_BUILD" \
          ..
```

- Steps to reproduce the problem:
docker build -t fluent/fluent-bit --target=production  .

**Expected behavior**
It should build a local docker image in my computer 

**Screenshots**
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/49650425/176704555-373255e3-76b6-401d-806f-3069bb61cfd1.png">
 This is a screenshot of the error itself

**Your Environment**
* Version used: docker version: Docker version 20.10.14, build a224086
+* Environment name and version (e.g. Kubernetes? What version?): Running locally on my computer
* Operating System and version: macOS Monterey Version 12.4

**Additional context**
I am trying to build a docker build to test out a branch with some changes. It currently has a PR opened. https://github.com/fluent/fluent-bit/pull/5564

**Comment by patrick-stephens** [comment]
You need to run from the base of the repo and not from the dockerfiles directory.
