### ISSUE TITLE
Support kubernetes Filter for Syslog Input

### ISSUE THREAD

**Issue by Mouad-B** [fluent/fluent-bit#5674]
Hello,

I've set my fluent-bit input to receive logs from syslog as shown bellow:
```

[INPUT]
  Name              syslog
  Tag               kube.syslog.*
  Parser            syslog-rfc5424
  Listen            0.0.0.0
  Port              5140
  Mode              tcp
```
Logs are retrieved as expected and sent to the configured output. 
Afterwards, I needed to enrich them with k8s filter. The  Filter which I configured this way always throws errors stating that `incoming record tag is shorter than kube_tag_prefix value`
```
[FILTER]
  Name kubernetes
  Match kube.syslog.*
  Merge_Log On
  Keep_Log Off
  Kube_Tag_Prefix  kube.syslog.
  K8S-Logging.Parser On
  K8S-Logging.Exclude On
  Labels Off
  Annotations Off
```

So my question is: Is the kubernetes Filter supposed to be compatible with a syslog input? If so, what configuration should be passed to the filter in this case?

**Comment by patrick-stephens** [comment]
No, it uses filename info to retrieve the pod name, etc to then query the K8S API for more data.

Other inputs would need to follow the specific tag format you get by default from tail of Kubernetes logs. Run that with stdout to see.
