### ISSUE TITLE
Does fluent-bit filter order

### ISSUE THREAD

**Issue by mohamedrasvi** [fluent/fluent-bit#5684]
Fluent-bit filter order 
When I apply two filter in fluent-bit I see it is not applying in order 
i would like to know does fluent-bit apply filter in order or apply randomly?

**Comment by edsiper** [comment]
filters are applied in order (top to bottom), if that is not the case, please provide the example that is not working for you.

**Comment by patrick-stephens** [comment]
@mohamedrasvi it applies in the order they are seen in the configuration. 

If you use a config map and/or `@include <file>` then the order in the config map is not necessarily the order in the configuration, e.g.:

```
@include <file with FILTER 1 & 2 in it>
[FILTER] <-- this is now filter 3
```

If you do wildcard includes then you will get them in whatever order the filesystem provides them to Fluent Bit in: https://github.com/fluent/fluent-bit/issues/5612
