### ISSUE TITLE
"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Duplicate field 'log

### ISSUE THREAD

**Issue by yonchin** [fluent/fluent-bit#569]
When I used flubent-bit, the following error occurred:

`"took":11,"errors":true,"items":[{"index":{"_index":"logstash-2018.04.19","_type":"flb_type","_id":"ReBJ3WIBJdTnAySXBQJM","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1468,"_primary_term":1,"status":201}},{"index":{"_index":"logstash-2018.04.19","_type":"flb_type","_id":"RuBJ3WIBJdTnAySXBQJM","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Duplicate field 'log'\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@6061e176; line: 1, column: 188]"}}}},{"index":{"_index":"logstash-2018.04.19","_type":"flb_type","_id":"R-BJ3WIBJdTnAySXBQJM","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Duplicate field 'log'\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStrea`

my config：

`  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/kube*.log
        Parse            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Merge_JSON_Log On
        Annotations    Off

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Retry_Limit     False

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On`

I haven't found the cause for a long time？

**Comment by edsiper** [comment]
Looks like one of your records contains the "log" key duplicated which raised an exception on elasticsearch:

```
Duplicate field 'log'\n at
```

**Comment by fruuf** [comment]
I had the same issue, turned out my parsers.conf was not wired up correctly, its all working fine now.
