### ISSUE TITLE
fluent-bit 1.9.6 for Windows and lack of OpenSSL dlls (again?)

### ISSUE THREAD

**Issue by andrico21** [fluent/fluent-bit#5703]
## Bug Report

**Describe the bug**
![image](https://user-images.githubusercontent.com/44984087/178145788-9e820286-1f60-4837-95fc-16f4cf7515d2.png)
![image](https://user-images.githubusercontent.com/44984087/178145796-1d36c944-55bd-4cc0-982b-69500e692307.png)

**To Reproduce**
Just try to exec the binary with or without any parameters

OS: Windows 11 Pro and the latest (1.9.6) version of fluent-bit downloaded from official Download page

**Comment by lecaros** [comment]
The package download link is: https://releases.fluentbit.io/1.9/fluent-bit-1.9.6-win64.zip
the exe file should be around 8Mb; instead of this, the current exe is about 5Mb

**Comment by patrick-stephens** [comment]
My suspicion is this might be to do with the deprecation of AppVeyor builds. For 1.9.6 we switched to using the Github built binaries for Windows so @andrico21 could you check if these AppVeyor binaries work for you?
https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/44112467

If so there must be some hidden dependency/config in the build to pick up the packages - it is probably assuming they exist in a location on the runner. We must fix that but I want to confirm first.

I can also revert to the AppVeyor builds for 1.9.6 until we sort it if they work.

**Comment by andrico21** [comment]
> For 1.9.6 we switched to using the Github built binaries for Windows so @andrico21 could you check if these AppVeyor binaries work for you? https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/44112467

Yes, it works!

**Comment by patrick-stephens** [comment]
OK cool, thanks for confirming. I'll update the release binaries so they use AppVeyor ones and we need to keep this issue open to cover the actual changes required to use Github binaries.

**Comment by patrick-stephens** [comment]
@andrico21 can I ask which variant you are using? Win32 or Win64?

**Comment by patrick-stephens** [comment]
@andrico21 can you confirm which architecture you were using 32 or 64?

It looks like the linkage is static for 32 and dynamic for 64 (thanks @leonardo-albertovich for checking) so it may just be a case of repeating this vpkg build for 64-bit: https://github.com/fluent/fluent-bit/blob/326d2e4988405de7c0aedc3873ab75481830fa8b/.github/workflows/call-build-windows.yaml#L78-L82

What do you think @cosmo0920 ?

**Comment by lecaros** [comment]
@patrick-stephens from the screenshot, @andrico21 is using the 64bits version, downloaded from here: https://releases.fluentbit.io/1.9/fluent-bit-1.9.6-win64.zip

**Comment by andrico21** [comment]
> @andrico21 can you confirm which architecture you were using 32 or 64?
x64

**Comment by cosmo0920** [comment]
Yup, we should do.

And I investigate the difference between AppVeyor and GitHub Actions.

#### AppVeyor 32bit

> -- Found OpenSSL: optimized;C:/OpenSSL-v111-Win32/lib/VC/static/libcrypto32MT.lib;debug;C:/OpenSSL-v111-Win32/lib/VC/static/libcrypto32MTd.lib (found version "1.1.1p")  

ref: https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/44242525/job/ka2crsvjf0ne8uk5?fullLog=true#L689

#### AppVeyor 64bit

> -- Found OpenSSL: optimized;C:/OpenSSL-v111-Win64/lib/VC/static/libcrypto64MT.lib;debug;C:/OpenSSL-v111-Win64/lib/VC/static/libcrypto64MTd.lib (found version "1.1.1p")  

ref: https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/44242525/job/43hvyel6evecf009?fullLog=true#L689

#### GitHub Actions

> -- Found OpenSSL: C:/Strawberry/c/lib/libcrypto.a (found version "1.1.1i")  

ref: https://github.com/fluent/fluent-bit/runs/7489575140?check_suite_focus=true#step:6:883

This seems to be odd.

**Comment by cosmo0920** [comment]
So, we have to use slproweb's OpenSSL installer on our GitHub Actions.

**Comment by patrick-stephens** [comment]
@andrico21 are you able to test the installer in the `windows-packages.zip` here: https://github.com/fluent/fluent-bit/actions/runs/2732639226

We think it's right but the proof is in the pudding so be great to confirm prior to next release.

**Comment by andrico21** [comment]
> @andrico21 are you able to test the installer in the `windows-packages.zip` here: https://github.com/fluent/fluent-bit/actions/runs/2732639226
> 
> We think it's right but the proof is in the pudding so be great to confirm prior to next release.

it started at least :)
```
cd C:\Program Files\fluent-bit\bin

C:\Program Files\fluent-bit\bin>fluent-bit.exe
Fluent Bit v2.0.0 | NIGHTLY_BUILD=2022-07-25-13_28_37 - DO NOT USE IN PRODUCTION!
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/07/25 21:25:21] [ info] [fluent bit] version=2.0.0, commit=660a4fc01d, pid=6720
[2022/07/25 21:25:21] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/07/25 21:25:21] [ info] [cmetrics] version=0.3.5
[2022/07/25 21:25:21] [ info] [sp] stream processor started
```

**Comment by patrick-stephens** [comment]
Really appreciate you testing it @andrico21 and looks fine but raise anything else you might see. We want to deprecate the AppVeyor build for various reasons but will not until this is stable.

**Comment by patrick-stephens** [comment]
@andrico21 a heads up, 1.9.7 was just released and I've not used the AppVeyor binaries for it so let me know if you're still seeing issues but hopefully we can now just use the full automation release.

**Comment by patrick-stephens** [comment]
@andrico21 it looks like we're still seeing issues on this for #5885

**Comment by andrico21** [comment]
I'm gonna check it today later, had no opportunity yet

**Comment by andrico21** [comment]
> @andrico21 it looks like we're still seeing issues on this for #5885
cannot confirm, on my x64 system it works fine:
```
PS > [System.Environment]::OSVersion | fl
Platform      : Win32NT
ServicePack   :
Version       : 10.0.22000.0
VersionString : Microsoft Windows NT 10.0.22000.0
```
and outputs:
```
PS Z:\fluent-bit> .\fluent-bit.exe --version
Fluent Bit v1.9.7
Git commit: 265783ebe99590cf1687d2f48b300f58febb883d
PS Z:\fluent-bit> .\fluent-bit.exe
Fluent Bit v1.9.7
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/08/18 23:48:43] [ info] [fluent bit] version=1.9.7, commit=265783ebe9, pid=6232
[2022/08/18 23:48:43] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/08/18 23:48:43] [ info] [cmetrics] version=0.3.5
[2022/08/18 23:48:43] [ info] [sp] stream processor started
```
![image](https://user-images.githubusercontent.com/44984087/185492982-d78864e5-cc40-4bf5-8e55-97a49c9f7977.png)
