### ISSUE TITLE
Use git submodules for dependencies

### ISSUE THREAD

**Issue by Garfield96** [fluent/fluent-bit#5713]
**Is your feature request related to a problem? Please describe.**
The `lib` folder contains copies of projects fluent-bit is depending on. In many cases, this is reasonable, because the projects are no longer maintained and it is easier to patch bugs. However, some projects are maintained by fluent-bit maintainers, e.g. chunkio, cmetrics and monkey. For these projects, the aforementioned advantages do not apply. Even worse, there are several disadvantages:
* new contributors sometimes create PRs for these dependencies in the fluent-bit repo, although they should be done in the dependency repo.
* updating the dependencies requires additional work from fluent-bit maintainers
* the dependencies are not always up-to-date
* the git history of the dependencies is not preserved

**Describe the solution you'd like**
Use git submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules), for dependencies, which are maintained by fluent-bit maintainers, and use dependabot to keep the versions up to date. Dependabot currently creates a new update for every update of the referenced branch in the submodule (https://github.com/dependabot/dependabot-core/issues/1639). Even though it would be preferred to be able to restrict dependabot updates to releases, I think this is an acceptable setting for these dependencies, as there aren't too many updates.

**Describe alternatives you've considered**
Alternatively, Cmake could be used to download these dependencies. Unfortunately, this solution does not support automatic updates with dependabot and is more complex.

**Additional context**
If this solution gets accepted, I can provide an implementation.

**Comment by edsiper** [comment]
thanks for raising this topic.

Indeed most of the time we need to do some simple patching on dependencies, and there are a couple of areas we care a lot about: build stage (as we need), add missing CMakeLists.txt file, and security updates..

Being up-to-date with dependabot is not something we want, if we upgrade a library must be a reason and not just an automated process around it. Yes, this is more work from a maintenance perspective but give us more control and safety.
