### ISSUE TITLE
Tail input plugin tests fail in v1.9.6

### ISSUE THREAD

**Issue by bkircher** [fluent/fluent-bit#5723]
## Bug Report

**Describe the bug**
Testing fails for Fedora package with
```
[ FAILED ]
  in_tail.c:1493: Check num == 2... failed
    num error. expect=2 got=1
```

Complete build log attached.

**To Reproduce**
```
/usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFLB_EXAMPLES=Off -DFLB_OUT_SLACK=Off -DFLB_IN_SYSTEMD=On -DFLB_OUT_TD=Off -DFLB_OUT_ES=On -DFLB_SHARED_LIB=Off -DFLB_TESTS_RUNTIME=On -DFLB_TESTS_INTERNAL=Off -DFLB_RELEASE=On -DFLB_DEBUG=Off -DFLB_TLS=On
```

**Your Environment**

* Version used: v1.9.6
* Operating System and version: Fedora x86_64
* Filters and plugins: Tail input plugin

**Additional context**
[build.log](https://github.com/fluent/fluent-bit/files/9120926/build.log)

**Comment by nokute78** [comment]
Thank you for reporting.
I think below commit will fix issue and it is not released yet.
https://github.com/fluent/fluent-bit/commit/9104c18476f19c94d094bb7a626c9409e76e7e77

**Comment by bkircher** [comment]
Hey thanks for the pointer! With that patch applied tests pass.
