### ISSUE TITLE
Add HTTP header to the record

### ISSUE THREAD

**Issue by jp** [fluent/fluent-bit#5725]
As a user I would like to be able to add the HTTP headers received in the HTTP input to the logger.

I'm looking for a solution similar to that fluentd is providing: https://docs.fluentd.org/input/http#add_http_headers

I considered adding an nginx and Lua script upfront that could manipulate the payload, but I really don't like the approach.

**Comment by nokute78** [comment]
Similar request: https://github.com/fluent/fluent-bit/issues/5386

**Comment by jp** [comment]
Closing as it is a duplicate of the request above
