### ISSUE TITLE
GELF output plugin stops reconnecting to the remote service

### ISSUE THREAD

**Issue by PabloCamino** [fluent/fluent-bit#5726]
## Bug Report

**Describe the bug**
The GELF output plugin stops reconnecting to the remote service forever.
We are using tail input and GELF output within a kubernetes deployment.
From time to time remote service disconnects the keep alive connection.
Fluent-Bit reconnects afterwards but at some point it just doesn't.
There are no connection attempts not any traffic flowing to/from Fluent-Bit pod.
This status could last for days and logs will not be forwarded until we delete the pod to recreate the Fluent-Bit process.

**To Reproduce**
- Example log message:
```
[2022/07/12 04:17:51] [debug] [upstream] KA connection #30 to 172.20.21.43:12201 has been disconnected by the remote service
```
After the above no more messages with the [upstream] tag are logged.
Checking with {{netstat}} and {{tcpdump}} also shows no connection attempts or any network activity.
```
kubectl -n rtf exec external-log-forwarder-2f26c -- netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:2020            0.0.0.0:*               LISTEN
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
```
```
tcpdump -nnvp -i vethe956b2f9 'host 172.20.21.43' -s0
tcpdump: listening on vethe956b2f9, link-type EN10MB (Ethernet), capture size 262144 bytes
```
- Steps to reproduce the problem:
   We have not been able to reproduce this on a test or lab environment.
   It's happening on a daily basis for a productive environment.
   Currently the only workaround we have is a premature restart of Fluent-Bit before this happens.

**Expected behavior**
We expect the output to attempt to reconnect to the upstream service all the time and not require Fluent-Bit to be restarted.

**Your Environment**

* Version used: 1.8.12
* Configuration:
```
[SERVICE]
    Flush         5
    Config_Watch  On
    Log_Level     info
    Daemon        Off
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_PORT     2020
    Parsers_File  parsers.conf

[INPUT]
    Name               tail
    Tag                kube.*
    Path               /var/log/containers/*.log
    Parser             docker
    DB                 ${DB_FILE_PATH}
    Mem_Buf_Limit      ${MEM_BUF_LIMIT}
    Skip_Long_Lines    On
    Refresh_Interval   10
    Rotate_Wait        10
    Docker_Mode        On
    Docker_Mode_Flush  5
    Docker_Mode_Parser mule
    Exclude_Path    /var/log/containers/*_kube-system_*.log, /var/log/containers/*_monitoring_*.log, /var/log/containers/*_rtf_*.log

[OUTPUT]
    Name    gelf
    Tls.verify    Off
    Match    *
    Host    172.20.21.43
    Port    12201
    Mode    tcp
    Tls    Off
    Gelf_Short_Message_Key    log
    Gelf_Timestamp_Key    timestamp
    Gelf_Host_Key    host
    Gelf_Full_Message_Key    full_message
    Gelf_Level_Key    level
    Packet_Size    1420
    Compress    true
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes Version:   1.13.13
* Server type and version:
* Operating System and version: 
* Filters and plugins: Gelf only

**Additional context**
Fluent-Bit is being used as the log forwarding solution for the entire Kubernetes cluster.
Logs are being output to SEQ server using GELF ingest.
When forwarding hangs this way we see no longs being ingested and eventually we loose log data if it rotates in this state.

I tried to disable keep alive connections but even if I set {{net.keepalive off}} the debug logs still show KA connections being used.

When forwarding is stopped the Fluent-Bit process is still running though.
We are able to check the metrics endpoint and get a reply that confirms not a single byte is going in or out of the pipeline.

**Comment by digvijaysk19** [comment]
Any updates on this?

**Comment by aqurishi-mulesoft** [comment]
hello, does anyone have any update on this?

**Comment by pgulian-mulesoft** [comment]
Hello, does anyone have any update on this?
