### ISSUE TITLE
Latest version 0.12.19 or 0.13.0?

### ISSUE THREAD

**Issue by ilovezfs** [fluent/fluent-bit#575]
I can't tell from https://github.com/fluent/fluent-bit/releases

**Comment by edsiper** [comment]
Fixed, thanks.

**Comment by ilovezfs** [comment]
Thanks! Voilà https://github.com/Homebrew/homebrew-core/pull/27334

**Comment by edsiper** [comment]
awesome!, feel free to add instructions to the official docs: https://github.com/fluent/fluent-bit-docs

**Comment by edsiper** [comment]
@ilovezfs as a reference you can validate with the website release notes, e.g:

https://fluentbit.io/announcements/v0.13.1/

if there is no release notes, so the release is still in work in process.

**Comment by ilovezfs** [comment]
@edsiper https://fluentbit.io/announcements/v0.13.6/ is posted but https://github.com/fluent/fluent-bit/releases/latest points to 0.13.5
