### ISSUE TITLE
Add a custom_headers parameter to the Elasticsearch output plugin

### ISSUE THREAD

**Issue by rkuchan** [fluent/fluent-bit#5759]
**Is your feature request related to a problem? Please describe.**

I’m trying to use the [Elasticsearch output plugin](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch) to write data to [EraSearch](https://era.co/). EraSearch requires a bearer token and won’t work with the output plugin’s existing auth parameters.

**Describe the solution you'd like**

I'd like a configuration parameter for adding custom HTTP headers. Here's what that could look like, where `12345678` is the bearer token:

```
Custom_Headers "Authorization: Bearer 12345678"
```

**Describe alternatives you've considered**

Here's how I've seen it work in other tools:

- Fluentd: `custom_headers "Authorization: Bearer 12345678"`
- Telegraf: `auth_bearer_token = "12345678"`
- Logstash:
  ```
    custom_headers => {
        "Authorization" => "Bearer 12345678"
    }
  ```
- Vector: `request.headers.Authorization = "Bearer 12345678"`

**Additional context**

FYI @rossmcdonald and @toddboom

**Comment by tregusti** [comment]
Until this is added, is there a workaround? I implementing fluent-bit in a kubernetes cluster with an external ES-instance. Should add a fluentd instance in my cluster just to pipe the data through it and let it authorize itself to ES?

**Comment by edgarjariamobbiz** [comment]
This should not be closed as it is a basic security requirement.

**Comment by edgarjariamobbiz** [comment]
Please, reopen the issue
