### ISSUE TITLE
Endless retries after loki output was responding with errors for several minutes

### ISSUE THREAD

**Issue by otbe** [fluent/fluent-bit#5774]
Hi there,

we experienced a strange behaviour after one of our loki clusters went unhealthy for quite some time. We use fluentbit in a sidecar setup on AWS ECS + firelens. Usually this works quite nice even if loki scales in or out.

## Bug Report

Whenever 
- the output (loki) returns a 5xx/gets unhealthy and
- the log producer keeps producing logs and
- the amount of time (aka log lines) is too big 

fluentbit gets into a state where it logs exactly the same log line for the rest of its runtime. Theres no way (for us) to recover fluentbit/log shipping on this task besides restarting the whole ECS task.

**How did we came to this conclusion?**
First we used the default value for `Retry_Limit` (=1). In a previous loki incident we noticed for all applications that log via fluentbit into loki all logs that were buffered to disk in time where loki was unhealthy were lost. We thought its related to the `Retry_Limit` because we only retried it once and then the chunk gets discarded but no, after analysing the logs of fluentbit around this time it indicates that even after loki was healthy again all retries lead to discarded chunks and only "fresh" logs were shipped successfully. Please note: we set the `Retry_Limit` to `no_limits` to make this issue more obvious to analyse and we also would like to keep it that way. 

We are able to reproduce this issue with a testing setup. Therefore we have a dedicated loki that is scaled to 1 (unhealthy) or 2 (healthy) instances for its write side. 

We tested different scenarios and these are our results:

_1. Scenario: Keep producing logs all the time_

Loki is healthy,  logs are being produced and are visible in grafana. Then we scale loki down to 1 instance, after some time we see (the log lines where loki output complains about 5xx error is missing from this screenshot)
<img width="1689" alt="Screenshot 2022-07-22 at 11 42 16" src="https://user-images.githubusercontent.com/3391052/180433193-58c0cb23-e487-4ec6-bc65-c29d7a57e830.png">
and also our filesystem buffer fills up nicely
<img width="655" alt="Screenshot 2022-07-22 at 11 44 16" src="https://user-images.githubusercontent.com/3391052/180433287-6e70d6bd-807a-46d1-b8d9-b7e84fd0f2f2.png">

Some time later we scale loki back to 2 instances but fluentbits log output will not change. Other services are able to ship their logs but fluentbit does not receover. We will see this log line `re-schedule retry=XXXXX X in the next XX seconds` for the rest of the lifetime of fluentbit. Please note that theres not a single other line logged after the first reschedule log line. Which make me think its somehow deadlocked (or an off by one error or something like this) .

_2. Scenario: Stop log producing shortly after Loki gets unhealthy_

Same procedure as 1 but then we stop to produce logs shortly after we made loki unhealthy and fluentbits logs will look like this:
<img width="1729" alt="Screenshot 2022-07-22 at 12 07 41" src="https://user-images.githubusercontent.com/3391052/180444175-8e015d02-5e81-42c8-bc8f-3c9dab61d604.png">

Please note: we have more than 5 retry attempts for whatever reason in this example. In the first scenario it always stop at 5. Once I kept loki unhealthy for 45minutes and fluentbit kept retrying until loki was healthy again.
Also the filesystem cache will be empty after all chunks were flushed and newly generated logs are happily flowing.

**Final thoughts**
I assume something is wrong in fluentbits retry/buffering mechanism. Whenever we see `re-schedule retry=XXXXX X in the next XX seconds` in such a situation it basically means logs are lost and we have to restart the Task/Container. It entirely depends on the fact whether we keep going to produce logs (increasing chunks in up&down state) or not which may or may not be related to #2566 and #2804.

There are also #5485, #5312, #5217 and #4707 which may or may not be related. 

This behaviour was tested on fluentbit docker images 1.9.4 and 1.9.6.

I would really appreciate some help here. I can also test certain fixes in our logging test infrastructure at any time.

Thank you very much!

**Your Environment**
* Version used: official fluentbit docker images; 1.9.4 and 1.9.6
* Configuration:
```
[SERVICE]
    flush                     1
    grace                     30
    storage.path              /tmp/flb-storage/input
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    Name forward
    unix_path /var/run/fluent.sock
    storage.type filesystem
    Mem_Buf_Limit 50MB

[Output]
    Name loki
    Match *
    Retry_Limit no_limits
    host ${LOKI_HOST}
    port ${LOKI_PORT}
    tenant_id ${TENANT_ID}
    line_format json
    labels $source, $container_id, service=${SERVICE}
    remove_keys ecs_task_arn,ecs_task_definition,source,ecs_cluster,container_name
    tls on
    tls.verify off
    storage.total_limit_size 1G
```
* Environment name and version: AWS ECS (Fargate 1.4)

**Comment by aslafy-z** [comment]
I see the same issue for fluent-bit to fluentd. Relates to https://github.com/fluent/fluent-bit/issues/6010

**Comment by cbi-at-varian** [comment]
I see the same issue with fluent-bit `2.0.4`, I'm only able to recover from it with the poor man's solution described in https://github.com/fluent/fluent-bit/issues/5217#issuecomment-1118427200

Basically doing:
`find /var/log/flb-storage -type f -name "*.flb" -mmin +60 | xargs rm -f || true`

**Comment by balonik** [comment]
I have the same issue with fluent-bit `1.9.9` and loki `2.6.1`. It happened after restart of loki (after config change). Loki returned `500` once and since then fluent-bit stopped sending logs with endless retry loop even after Loki is available again. A workaround is to restart fluent-bit process and it starts to send logs again just fine.

```
2022/12/29 10:43:59] [error] [output:loki:loki.0] loki.loki:3100, HTTP status=500
rpc error: code = Unknown desc = Ingester is shutting down

[2022/12/29 10:43:59] [ warn] [engine] failed to flush chunk '1-1672310519.912081369.flb', retry in 6 seconds: task_id=0, input=tail.0 > output=loki.0 (out_id=0)
[2022/12/29 10:44:00] [error] [output:loki:loki.0] no upstream connections available
[2022/12/29 10:44:00] [ warn] [engine] failed to flush chunk '1-1672239911.303384380.flb', retry in 9 seconds: task_id=6, input=storage_backlog.1 > output=loki.0 (out_id=0)
[2022/12/29 10:44:02] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1713606 watch_fd=100 name=/var/log/containers/prometheus-kube-prometheus-stack-prometheus-0_monitoring_config-reloader-8fafc26e16ec6fb9c3f04fb25cb35a2371fad743818cb246a13022fadb92b188.log
[2022/12/29 10:44:02] [ info] [input:tail:tail.0] inotify_fs_add(): inode=272437420 watch_fd=101 name=/var/log/containers/prometheus-kube-prometheus-stack-prometheus-0_monitoring_init-config-reloader-e31315ccfd2924c67a1a556baa95dc409e913726b24d893452e407968e48405f.log
[2022/12/29 10:44:02] [ info] [input:tail:tail.0] inotify_fs_add(): inode=204442075 watch_fd=102 name=/var/log/containers/prometheus-kube-prometheus-stack-prometheus-0_monitoring_linkerd-init-6448e50677c5473730d09b3a85c7eb6c28b6612e597da6be4160d1951e9bcbe2.log
[2022/12/29 10:44:02] [ info] [input:tail:tail.0] inotify_fs_add(): inode=204447130 watch_fd=103 name=/var/log/containers/prometheus-kube-prometheus-stack-prometheus-0_monitoring_linkerd-proxy-0893ff11fe70a36de58a7d72610f770b3bedca521d7c3524ecd3904e1537450a.log
[2022/12/29 10:44:02] [ info] [input:tail:tail.0] inotify_fs_add(): inode=1711188 watch_fd=104 name=/var/log/containers/prometheus-kube-prometheus-stack-prometheus-0_monitoring_prometheus-39980a58517513fac19835cfeabb54b7b934ddf44e2cfaf40238bbd0bfef9862.log
[2022/12/29 10:44:05] [ info] [task] re-schedule retry=0x7f473ba3a9c8 0 in the next 11 seconds
[2022/12/29 10:44:09] [ info] [task] re-schedule retry=0x7f473ba3aa40 6 in the next 6 seconds
[2022/12/29 10:44:15] [ info] [task] re-schedule retry=0x7f473ba3aa40 6 in the next 6 seconds
```

**Comment by balonik** [comment]
I have tested fluent-bit 2.0.9 and cannot replicate the issue anymore.

**Comment by dumunari** [comment]
I'm having same issue as @otbe, running on AKS with Loki on v2.7.5

I have tried fluent-bit 2.0.9 and 2.0.10, and still happening

**Comment by otbe** [comment]
Seems like in 2.0.11 it finally works. I cannot reproduce this issues anymore in our testing infra. Ill deploy it now as a sidecar of one of our services and test it a bit in the real world :)

**Comment by carlosrmendes** [comment]
I got the same issue on 2.2.0, with the logsatsh server down (tcp ouput), after ~1h  the fluentbit stops to print the warn (retries) and error message of the rejected requests, even if I put logstash server up again, the fluentbit does not recover and starts to send the backlog logs again, only with a restart.

this is my config:
```
    service:
      flush: 5
      http_server: on
      log_level: debug
      scheduler.cap: 75
      storage.path: /data/logs/
      storage.max_chunks_up: 256
      storage.backlog.mem_limit: 32M
      storage.delete_irrecoverable_chunks: on
      #parsers_file: parsers.conf

    pipeline:
      inputs:
        - name: tail
          refresh_interval: 5
          db: /data/fluentbit.db
          # buffer_max_size: 256K
          buffer_max_size: 4M
          buffer_chunk_size: 256K
          static_batch_size: 256M
          storage.type: filesystem
          multiline.parser: docker, cri
          tag: <namespace>.<workload>.<container>
          tag_regex: (?<workload>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container>.+)-([a-z0-9]{64})\.log$
          path: /var/log/containers/*_kelvin-admin_*.log,/var/log/containers/*_kelvin_*.log,/var/log/containers/*_app_*.log

      filters:
        - name: record_modifier
          match: "*"
          remove_key: _p

        - name: record_modifier
          match: "*"
          remove_key: stream

        - name: modify
          match: "*"
          add: cluster ${KELVIN_CLUSTER_NAME}

        - name: modify
          match: "*"
          add: node ${KUBERNETES_NODE_NAME}

        - name: lua
          match: "*"
          call: tag_fields
          code: |
            function tag_fields(tag, timestamp, record)
              tags = {}

              for t in string.gmatch(tag, "[^%.]+") do
                table.insert(tags, t)
              end

              record["namespace"] = tags[1]
              record["pod"] = tags[2]

              if record["namespace"] == "app" then
                record["workload"] = string.gsub(tags[2], "-0$", "")
              end

              record["container"] = tags[3]

              return 1, timestamp, record
            end

        - name: lua
          match: "*"
          call: log_fields
          code: |
            function log_fields(tag, timestamp, record)
              cjson = require("cjson")

              log = record["log"]
              status, parsed_log = pcall(cjson.decode, log)

              if status and type(parsed_log) == "table" then
                if parsed_log["level"] then
                  record["level"] = string.lower(parsed_log["level"])
                end
                if parsed_log["logger"] then
                  record["logger"] = parsed_log["logger"]
                end
              end
            
              return 1, timestamp, record
            end

      outputs:
        - name: http
          match: "*"
          host: logstash-001
          port: 443
          tls: on
          tls.verify: off
          compress: gzip
          format: json_lines
          workers: 5
          retry_limit: no_limits
          log_response_payload: false
          storage.total_limit_size: 5G
```

**Comment by ivanguravel** [comment]
Hello dear community! 
We have the similar behaviour for fluentbit-kinesis connection. 
So, the bug is still present

**Comment by Venture200** [comment]
[ info] [task] re-schedule retry=0x7fbc510411c8 3 in the next 8 seconds

seeing this any fixes ?
