### ISSUE TITLE
Fluent Bit does not send close_notify on SSL Forward

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-bit#5791]
## Bug Report

**Describe the bug**
We are using Fluent Bit that forwards messages to a FluentD instance via Forward protocol.

With the use of fluentd (td-agent) on the newer Ubuntu 22.04, which uses OpenSSL 3 now, instead of OpenSSL 1.1.1, we are receiving warnings on fluentd side: 

```
│ 2022-07-25 09:09:34 +0000 [warn]: #0 close socket due to unexpected ssl error: SSL_read: unexpected eof while reading
│ 2022-07-25 09:09:42 +0000 [warn]: #0 close socket due to unexpected ssl error: SSL_read: unexpected eof while reading
```

As mentioned here https://github.com/fluent/fluentd/issues/3833#issuecomment-1195150635, it looks like Fluent Bit does not send `close_notify` alerts on connection shutdown. This leads into the warnings on the receiver side.

**To Reproduce**
- Set up Fluent Bit and Fluentd
- Create config for forwarding messages from Fluent Bit to Fluentd via SSL Forward
- See warnings in Fluentd logs

**Expected behavior**
No SSL warnings

**Your Environment**
* Version used: Fluent Bit 1.9.6
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.23.4
* Operating System and version: Ubuntu 22.04
* Filters and plugins: Input File, Output Forward

**Comment by drbugfinder-work** [comment]
still existing in Fluent Bit 1.9.9

**Comment by bubkoltet** [comment]
Still an issue with fluent-bit 3.0.7 and fluent-package 5.0.5.
