### ISSUE TITLE
In running fluent-bit docker file: "failed to compute cache key: "/fluent-bit.conf" not found: not found" 

### ISSUE THREAD

**Issue by pmeaney-sqrt** [fluent/fluent-bit#5793]
## Bug Report

**Describe the bug**

Copy the Dockerfile here: https://hub.docker.com/r/fluent/fluent-bit/dockerfile
into a Docker file.
then add "bash" to line 30, because I want a shell in my container.
then run: `docker build .` from the same directory as the Dockerfile.

result: "failed to compute cache key: "/fluent-bit.conf" not found: not found" 
(Screenshot attached)

**Screenshots**

Added bash to be installed via apt-get
<img width="1210" alt="Screen Shot 2022-07-26 at 11 28 54 AM" src="https://user-images.githubusercontent.com/102547768/181060433-6d087ddf-642f-46ed-b404-a481a8394629.png">

ran it... errored out.
<img width="1295" alt="Screen Shot 2022-07-26 at 11 25 52 AM" src="https://user-images.githubusercontent.com/102547768/181060296-038dce05-ad5e-4611-93ee-7cece9b48cfd.png">

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by pmeaney-sqrt** [comment]
I tried two filepaths for the section "# Configuration files"

original:
```Dockerfile
# Configuration files
COPY fluent-bit.conf \
  parsers.conf \
  parsers_java.conf \
  parsers_extra.conf \
  parsers_openstack.conf \
  parsers_cinder.conf \
  plugins.conf \
  /fluent-bit/etc/
```

attempt #1
```Dockerfile
# Configuration files
COPY /etc/fluent-bit/fluent-bit.conf \
  /etc/fluent-bit/parsers.conf \
  /etc/fluent-bit/parsers_java.conf \
  /etc/fluent-bit/parsers_extra.conf \
  /etc/fluent-bit/parsers_openstack.conf \
  /etc/fluent-bit/parsers_cinder.conf \
  /etc/fluent-bit/plugins.conf \
  /fluent-bit/etc/
```

attempt #2:
```Dockerfile
# Configuration files
COPY /fluent-bit/etc/fluent-bit.conf \
  /fluent-bit/etc/parsers.conf \
  /fluent-bit/etc/parsers_java.conf \
  /fluent-bit/etc/parsers_extra.conf \
  /fluent-bit/etc/parsers_openstack.conf \
  /fluent-bit/etc/parsers_cinder.conf \
  /fluent-bit/etc/plugins.conf \
  /fluent-bit/etc/
```

Still getting the same error about the conf files not being found in the given filepath.
For example, ""/fluent-bit/etc/plugins.conf" not found" ...but any of those conf files will have the same issue.

<img width="1631" alt="Screen Shot 2022-07-26 at 1 11 07 PM" src="https://user-images.githubusercontent.com/102547768/181081012-2f3d18b0-0b46-4b31-9d9e-f370ba5bc309.png">

**Comment by pmeaney-sqrt** [comment]
Also,
"MAINTAINER" is deprecated in favor of "LABEL"

<img width="729" alt="Screen Shot 2022-07-26 at 1 16 06 PM" src="https://user-images.githubusercontent.com/102547768/181081459-e88d6142-aaf3-4a7f-b040-3738baf4f409.png">

**Comment by patrick-stephens** [comment]
The dockerfiles require building from the root of the git repo since 1.8.12+, that's what it's trying to copy in: https://github.com/fluent/fluent-bit/tree/master/dockerfiles#build-and-test

The debug images contain a shell btw, along with a myriad of other things.

**Comment by patrick-stephens** [comment]
@pmeaney-sqrt did this sort your issue btw? I know we still need to fix DockerHub.
