### ISSUE TITLE
Dynamic naming of Elasticsearch indexes

### ISSUE THREAD

**Issue by ligol** [fluent/fluent-bit#5803]
**Is your feature request related to a problem? Please describe.**
I don't have any way to create dynamic Index on the ES output without using the Logstash_Prefix_Key parameter.
The issue is that passing by this parameter impose having an index with a date in the end, therefore not allowing us to use the Data Stream of ES

**Describe the solution you'd like**
Some parameter like the Logstash_Prefix_Key for getting the index name from a key of the message would be really nice and completely fix this issue.

**Describe alternatives you've considered**
The other alternative I have is to define multiple ES output for each index I want to use and then Rewrite_Tag to be able to send log to correct output. Which make this system really hard to maintain and error prone due to being able to forget to add the correct input when deploying a new service with a custom Index.

**Comment by lanmarti** [comment]
I would also love to see this feature. I don't know how fluent-bit handles multiple elasticsearch output configurations, but if it's similar to logstash, where each configuration creates their own connections, a dynamic index for the output plugin would also save resources compared to separate configurations for each index.

**Comment by sparrowt** [comment]
AFAICS this is a duplicate of https://github.com/fluent/fluent-bit/issues/2514 which has 2 workarounds listed [here](https://github.com/fluent/fluent-bit/issues/2514#issuecomment-2690737227)
