### ISSUE TITLE
stdin regex parser runaway memory

### ISSUE THREAD

**Issue by nakato** [fluent/fluent-bit#582]
## Problem

When ingesting continual streams of data into a fluent-bit and parsing it with the regex parser, I am able to take kilobytes of data and cause fluent-bit to consume all the available memory on the system in a very short period of time.

I noticed this problem due to production fluent-bit processes getting OOMKilled, and follows is the only way I've found to reliably reproduce the issue, or one that looks exactly like it.

The original stream that triggered this issue for me was from [mesos-external-container-logger](https://github.com/digitalocean/mesos-external-container-logger) piping data to fluent-bit.

## Reproduction

On my personal laptop I was able to reproduce it reliably with the difference being 1 line of base64 output (14468 vs 14469 lines) read out of a file.  But also with much less when the stream is much slower.

### 1. Create content to ingest

We'll pull the data from /dev/zero, but /dev/urandom could also be used.
`dd if=/dev/zero bs=1M count=100 | base64 > base64_lines`

and make some small files to test with, which is not strictly nesessary, it's possible to test with the ~136MB file just fine.

```
# dd if=base64_lines of=slow_lines bs=1k count=200
# dd if=base64_lines of=fast_lines bs=1M count=1
# dd if=base64_lines of=large_lines bs=1M count=3
```

### 2. create fluent-bit parser

```
[PARSER]
    Name    plaintext
    Format  regex
    Regex   ^(?<message>.*)$
```

### 3. Install PV if you do not have it

Can be skipped but PV will be used for the slow_lines.

### 4.  Tests

* Quickly pipe the 1MB of lines
  * `pv fast_lines | /fluent-bit/bin/fluent-bit --parser=parser.conf  -i stdin -p 'Parser=plaintext' -o stdout`
  * This should succeed 
* Quickly pipe the 3MB of lines (fails somewhere between 1.1MB and 1.2MB on my system)
  * `pv large_lines | /fluent-bit/bin/fluent-bit --parser=parser.conf  -i stdin -p 'Parser=plaintext' -o stdout`
  * This fails for me, resulting in fluent-bit requesting all the memories.
* Slowly pipe the small file
  * `pv -L 10k slow_lines | /fluent-bit/bin/fluent-bit --parser=parser.conf  -i stdin -p 'Parser=plaintext' -o stdout`
  * This fails as well, resulting in memory exhaustion again.

### Dockerfile

I do not have access to gist.github from my current location, so I'm adding a dockerfile here for reproduction.

```
FROM fluent/fluent-bit:0.13.0

RUN apt-get update \
    && apt-get install -y pv

RUN mkdir /test \
    && echo "[PARSER]\n    Name    plaintext\n    Format  regex\n    Regex   ^(?<message>.*)\$\n" > /test/parser.conf \
    && echo "IyEvYmluL2Jhc2gKCmNkIC90ZXN0CgpkZCBpZj0vZGV2L3plcm8gYnM9MU0gY291bnQ9MTAwIHwgYmFzZTY0ID4gYmFzZTY0X2xpbmVzCgpjYXNlICQxIGluCiAgICBzbWFsbCkKICAgICAgICBlY2hvICJSdW5uaW5nICdmYXN0X2xpbmVzJywgc2hvdWxkIHN1Y2NlZCBhbmQgZHVtcCBhIGxvdCBvZiB0ZXh0IgogICAgICAgIGRkIGlmPWJhc2U2NF9saW5lcyBvZj1mYXN0X2xpbmVzIGJzPTFNIGNvdW50PTEKICAgICAgICBwdiBmYXN0X2xpbmVzIHwgL2ZsdWVudC1iaXQvYmluL2ZsdWVudC1iaXQgLS1wYXJzZXI9cGFyc2VyLmNvbmYgIC1pIHN0ZGluIC1wICdQYXJzZXI9cGxhaW50ZXh0JyAtbyBzdGRvdXQKICAgICAgICA7OwogICAgbGFyZ2UpCiAgICAgICAgZWNobyAiUnVubmluZyAnbGFyZ2VfbGluZXMnLCBzaG91bGQgcnVuIG91dCBvZiBtZW1vcnkgYW5kIGJlIE9PTUtpbGxlZCIKICAgICAgICBkZCBpZj1iYXNlNjRfbGluZXMgb2Y9bGFyZ2VfbGluZXMgYnM9MU0gY291bnQ9MwogICAgICAgIHB2IGxhcmdlX2xpbmVzIHwgL2ZsdWVudC1iaXQvYmluL2ZsdWVudC1iaXQgLS1wYXJzZXI9cGFyc2VyLmNvbmYgIC1pIHN0ZGluIC1wICdQYXJzZXI9cGxhaW50ZXh0JyAtbyBzdGRvdXQKICAgICAgICA7OwogICAgc2xvdykKICAgICAgICBlY2hvICJSdW5uaW5nICdzbG93X2xpbmVzJywgc2hvdWxkIHJ1biBvdXQgb2YgbWVtb3J5IGFuZCBiZSBPT01LaWxsZWQiCiAgICAgICAgZGQgaWY9YmFzZTY0X2xpbmVzIG9mPXNsb3dfbGluZXMgYnM9MWsgY291bnQ9MjAwCiAgICAgICAgcHYgLUwgMTBrIHNsb3dfbGluZXMgfCAvZmx1ZW50LWJpdC9iaW4vZmx1ZW50LWJpdCAtLXBhcnNlcj1wYXJzZXIuY29uZiAgLWkgc3RkaW4gLXAgJ1BhcnNlcj1wbGFpbnRleHQnIC1vIHN0ZG91dAogICAgICAgIDs7CiAgICAqKQogICAgICAgIC90ZXN0L3Rlc3Quc2ggc21hbGwKICAgICAgICAvdGVzdC90ZXN0LnNoIGxhcmdlCiAgICAgICAgL3Rlc3QvdGVzdC5zaCBzbG93CiAgICAgICAgOzsKZXNhYwo=" | base64 -d > /test/test.sh \
    && chmod a+x /test/test.sh

ENTRYPOINT ["/test/test.sh"]
CMD ["large"]
```

**Comment by nakato** [comment]
@edsiper Thank you for such an amazing tool and thanks for the fix!

I've compiled a copy with the patch and can confirm the fix from here as well.

I agree, the ability to specify a delimiter would be extremely useful.

**Comment by edsiper** [comment]
thanks again, closing as fixed.
