### ISSUE TITLE
TLS issue with Windows fluent-bit plugins

### ISSUE THREAD

**Issue by rawahars** [fluent/fluent-bit#5820]
## Bug Report

**Describe the bug**

Windows packages for fluent-bit encounter a TLS issue when running them from inside a Windows container.

In short, I mounted the fluent-bit artifacts inside a Windows container and then ran the output TCP plugin with TLS.

```
./fluent-bit.exe -i dummy -o tcp://127.0.0.1:5170 -p tls=On
```

The following error was encountering-

```
[2022/08/02 09:35:08] [error] [tls] error: unexpected EOF
```

The error seems to be coming from the fluent-bit from here-https://github.com/fluent/fluent-bit/blob/c0a764533e7087972dd75fb2f53f7350e3a983c0/src/tls/openssl.c#L488

Can you please help us with how to debug this issue?

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:

```
[2022/07/29 13:55:23] [error] [tls] error: unexpected EOF
```

- Steps to reproduce the problem:

    - Download the official Windows package (https://fluentbit.io/releases/1.9/fluent-bit-1.9.6-win64.zip)
    - Extract it in a folder (`C:\fluent-bit-1.9.6`)
    - Run a Windows container with this folder mounted inside it
        - `docker run --rm -it -v C:\fluent-bit-1.9.6:C:\fluent-bit mcr.microsoft.com/windows/servercore:ltsc2019 powershell`
    - Inside the container (`C:\fluent-bit\bin`), run fluent bit-
        - `./fluent-bit.exe -i dummy -o tcp://127.0.0.1:5170 -p tls=On`
    - TLS error is encountered in the logs-
        - `[error] [tls] error: unexpected EOF`

**Expected behavior**

There should not be any TLS errors which should be encountered.

**Screenshots**

**Your Environment**

* Version used: 1.9.6
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): Fluent-bit inside Windows containers
* Server type and version: 
* Operating System and version: Windows Server 2019
* Filters and plugins: Input Dummy plugin and Output TCP plugin

**Additional context**

**Comment by patrick-stephens** [comment]
Clarified with @rawahars that the packages work fine on a full OS/VM, it is just when extracted and used inside a container they seem to be failing.

**Comment by rawahars** [comment]
So I was able to resolve this issue. 
On Windows Containers, by default, only the Root CA certs from Microsoft are installed. Therefore, we need to manually install other required certificates as required by the plugin.

**Comment by patrick-stephens** [comment]
Can you clarify how to do this for others, e.g. with a docs update or just a comment here?

**Comment by rawahars** [comment]
Yeah definitely.

So, the certificates need to be installed based on the plugin which you want to use. For example- Cloudwatch, Kinesis Streams, and Kinesis Firehose interact with AWS endpoints for sending the logs to AWS destinations. Therefore, they need Amazon Root CA certs for server cert validation in TLS.

```
$AmazonRootCA1 = "https://www.amazontrust.com/repository/AmazonRootCA1.cer"
Invoke-WebRequest -URI $AmazonRootCA1 -OutFile "C:\AmazonRootCA1.cer"
Import-Certificate -FilePath C:\AmazonRootCA1.cer -CertStoreLocation Cert:\LocalMachine\Root\
```

This installs Amazon Root CA cert which can then allow FLB to interact with AWS endpoints.
