### ISSUE TITLE
Libyaml and libyaml-devel are installed but fluentbit is not finding it

### ISSUE THREAD

**Issue by pedrooct** [fluent/fluent-bit#5821]
## Bug Report

**Describe the bug**
Fluentbit is not compiling with the flag for yaml on. Do i need other steps?

CMake Error at CMakeLists.txt:695 (message):
YAML development dependencies required for YAML configuration format handling.
This is a build time dependency, you can either install the dependencies or
   disable the feature setting the CMake option -DFLB_CONFIG_YAML=Off .
 -- Configuring incomplete, errors occurred!

**To Reproduce**
Install:
On CentOS 7:
- RUN yum -y groupinstall "Development Tools"     && yum -y install wget unzip cmake libyaml libyaml-devel pkgconfig
- After this compile fluentbit version 1.9.6 

**Expected behavior**
Fluentbit should have found yaml.h

**Your Environment**
CENTOS 7 docker container
CMAKE 3.12

**Comment by pedrooct** [comment]
yaml-0.1.pc exists
![imagem](https://user-images.githubusercontent.com/24395675/182413421-4c710752-6cc8-4909-813f-7c9a370f7db2.png)

**Comment by patrick-stephens** [comment]
I would look at the CI build here, this builds CentOS 7 with YAML support: https://github.com/fluent/fluent-bit/blob/master/dockerfiles/Dockerfile.centos7

Your output only shows yaml lib exists, not necessarily the headers. My suspicion is something went wrong and/or your container cache may be interfering.

**Comment by pedrooct** [comment]
Hi @patrick-stephens 
Yes, i checked the centOS7 Dockerfile. I tested it with --no-cache on build, still the same issue.
I'm installing libyaml libyaml-devel pkgconfig, can this packages cause issues? If that's the case, Could it be a path issue?

Thank you.

**Comment by pedrooct** [comment]
Hi @patrick-stephens 
Found the issue, i was being a bit dumb! 

Sorry for wating your time!

**Comment by freesinger** [comment]
> 

Having the same issue, how did you solve it ?

**Comment by freesinger** [comment]
> Hi @patrick-stephens Found the issue, i was being a bit dumb!
> 
> Sorry for wating your time!
Having the same issue, how did you solve it? @pedrooct

**Comment by Beauxrel** [comment]
If anyone else has this issue, I just installed with the flag -DFLB_CONFIG_YAML=Off, not sure if it broke anything. but I got the install to finish

**Comment by patrick-stephens** [comment]
> If anyone else has this issue, I just installed with the flag -DFLB_CONFIG_YAML=Off, not sure if it broke anything. but I got the install to finish

Well you won't be able to use yaml config
