### ISSUE TITLE
Question: Does fluent-bit only support window server 2019 and  windows 10 

### ISSUE THREAD

**Issue by ischenxin** [fluent/fluent-bit#5838]
## Question Report

I have such a server which platform named `Microsoft Windows Server 2012 R2 Standard` 

![image](https://user-images.githubusercontent.com/89346248/182985096-9ed864df-c7b2-4e63-8718-c72c8e8fb238.png)

 Can Fluent-bit work well on this machine

**Comment by patrick-stephens** [comment]
The OSS project provides packages intended for those platforms yes, as described here: https://docs.fluentbit.io/manual/installation/supported-platforms

It's likely it will run on your platform but it depends on the specific configuration you're using so we cannot guarantee any more than that. 

For support you should engage a commercial provider who do support your specific target: https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit#enterprise-packages
