### ISSUE TITLE
[exec plugin]: Parser not found, but no parser specified

### ISSUE THREAD

**Issue by DCCSKrezovic** [fluent/fluent-bit#5848]
## Bug Report

**Describe the bug**

I am using exec plugin to store the output of a script. In fluent-bit version 1.6.10 it worked without any problem. After update to fluent-bit 1.9.6 the following error is shown in the log
```
[2022/08/07 14:12:03] [error] [input:exec:exec.3] requested parser 'og' not found
```
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2022/08/07 14:12:03] [error] [input:exec:exec.3] requested parser 'og' not found
```
- Steps to reproduce the problem:

```
[INPUT]
    Name          exec
    Tag           tag
    Command       /path/to/script.sh
    Interval_Sec  300
```

**Expected behavior**

Script output is forwarded to the output plugin
**Screenshots**

**Your Environment**

* Version used: 1.9.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Linux server
* Server type and version:
* Operating System and version: Suse Linux Enterprise 12.5
* Filters and plugins: exec

**Additional context**

**Comment by DCCSKrezovic** [comment]
Issue is not observed on fluent-bit 1.8.15

**Comment by patrick-stephens** [comment]
Can you show the full config and script content?

**Comment by nokute78** [comment]
I think https://github.com/fluent/fluent-bit/issues/5715 is same issue since valgrind reports using uninitialized `ctx->parser_name`.
A patch is https://github.com/fluent/fluent-bit/pull/5720.

**Comment by markuman** [comment]
I hit a similar issue with fluent-bit 1.9.9

> [2022/11/01 11:17:30] [error] [input:exec:exec.0] requested parser '0�' not found


while it works with 1.8.12

**Comment by patrick-stephens** [comment]
Try 2.0.3, patches to master may have been for 2.0+ release rather than the 1.9 branch.
