### ISSUE TITLE
COLLECT_TIME registration failed on SUSE Linux Enterprise 12.5

### ISSUE THREAD

**Issue by DCCSKrezovic** [fluent/fluent-bit#5849]
## Bug Report

**Describe the bug**

When starting fluent-bit 1.9.6 with exec plugin configured, there is an error message in the system log:

```
[2022/08/07 14:12:03] [  Error] timerfd_settime: Invalid argument, errno=22 at /root/fluent-bit-1.9.6/lib/monkey/mk_core/mk_event_epoll.c:214
[2022/08/07 14:12:03] [error] [input collector] COLLECT_TIME registration failed
```

exec plugin produces no output after the given interval.

exec plugin worked in fluent-bit 1.6.10 just fine. Everything stopped working after update to 1.9.6

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.9.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Linux server
* Server type and version:
* Operating System and version: SUSE Linux Enterprise 12.5
* Filters and plugins: exec

**Additional context**

**Comment by DCCSKrezovic** [comment]
Issue is not observed on fluent-bit 1.8.15

**Comment by patrick-stephens** [comment]
Note that SUSE 12 is not a supported platform unfortunately for OSS (some of the Enterprise options do though: https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit#enterprise-packages): https://docs.fluentbit.io/manual/installation/supported-platforms

The error message looks to be in the dependency as well: http://monkey-project.com/
