### ISSUE TITLE
Package for Ubuntu Bionic 18.04

### ISSUE THREAD

**Issue by sandstrom** [fluent/fluent-bit#585]
Thanks for an awesome project! 🏅 

Since Ubuntu 18.04 (Bionic Beaver) is now out, do you have any plans to release a package for it?

This page only lists 16.04 at the moment:
https://fluentbit.io/documentation/0.13/installation/ubuntu.html

**Comment by edsiper** [comment]
thanks for raising this issue.

I've updated our repositories and now Debian 9 and Ubuntu 18.04 packages are available:

- [Debian](https://fluentbit.io/documentation/0.13/installation/debian.html)
- [Ubuntu](https://fluentbit.io/documentation/0.13/installation/ubuntu.html)

regards,

**Comment by sandstrom** [comment]
@edsiper Awesome! 🎉
