### ISSUE TITLE
fluent-bit unable to send logs/events to Elasticsearch.

### ISSUE THREAD

**Issue by srinathjamboju92** [fluent/fluent-bit#5852]
## Bug Report

**Describe the bug**
Fluent-bit agent running as DaemonSet in AWS EKS failing to send the container logs to Elasticsearch.

**To Reproduce**
- Install the helm chart 0.19.22, that installs the fluent bit agent 1.8.14
- Example log message if applicable:  

```
[0] kube.var.log.containers.reconciliation-loader-service-dc7c65c5f-zxhz7_dev_istio-proxy-cd16346c22127791b4e8768c151d197ffbc10536a867c1cbe766021bcd581974.log: [1658786065.456468415, {"log"=>"[2022-07-25T21:49:24.475Z] "- - -" 0 - - - "-" 176 598 300106 - "-" "-" "-" "-" "10.31.32.220:9092" outbound|9092||infra-kafka-headless.dev.svc.cluster.local 10.31.26.62:60076 10.31.32.220:9092 10.31.26.62:60074 

```

- Steps to reproduce the problem:
- Install the helm chart 0.19.22

**Expected behavior**
logs should be sent to Elasticsearch

**Screenshots**
[ warn] [engine] failed to flush chunk '1-1659950903.31709681.flb', retry in 1900 seconds: task_id=36, input=tail.0 > output=es.0 (out_id=0)

**Your Environment**

* Version used: Fluent bit : 1.8.14, Elasticsearch : 8.1.0-10

* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): kubernetes version: 1.21.1
* Operating System and version: Amazon Linux 2
* Filters and plugins:

Fluent Bit Configuration:
apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 20MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
        Mem_Buf_Limit 20MB

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 128k

    [FILTER]
        Name modify
        Match kube.*
        Add kubernetes_cluster_name prod_eks_1

    [OUTPUT]
        Name es
        Match kube.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USERNAME}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Retry_Limit False
        Replace_Dots    Off
        tls             On
        Generate_ID     On
        Suppress_Type_Name On
        net.keepalive on
        net.keepalive_idle_timeout 60
        Buffer_Size 1024KB
    [OUTPUT]
        Name es
        Match host.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User       ${FLUENT_ELASTICSEARCH_USERNAME}
        HTTP_Passwd     ${FLUENT_ELASTICSEARCH_PASSWORD}
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Replace_Dots    Off
        tls             On
        Generate_ID     On
        Suppress_Type_Name On
        net.keepalive on
        net.keepalive_idle_timeout 60
        Buffer_Size 1024KB

kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: fluent-bit-fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.8.14
    helm.sh/chart: fluent-bit-0.19.22
  name: fluent-bit
  namespace: fluent-bit

**Additional context**

No logs are being sent to ES from fluent-bit

**Comment by srinathjamboju92** [comment]
Observed that the Fluent Bit agent is converting the incoming JSON Object(log) as a STRING and hence Elastic rejects it. This appears to be the problem with Fluent Bit. 
Is there anyone here to guide or help on how to proceed with this? Unfortunately documentation is not at all helpful and its just confusing.

**Comment by srinathjamboju92** [comment]
@edsiper Can you please help here?

**Comment by srinathjamboju92** [comment]
can anyone help here please?

**Comment by srinathjamboju92** [comment]
@opklnm102 The issue is not with Dots.

**Comment by lecaros** [comment]
Hi @srinathjamboju92,
Is this also reproducible using the latest version in 1.8 or 1.9?
Are you seeing any dropped records on the metrics endpoint?
Have you validated the output by sending it to stdout? If not, this is a good start to troubleshoot this issue.
If you still see this, please provide the Fluent-Bit log file. We need to see more context on that warning.
