### ISSUE TITLE
How to change the default UTC timestamp on fluent-bit logs?

### ISSUE THREAD

**Issue by raj13aug** [fluent/fluent-bit#5860]
## Bug Report

**Describe the bug**

The Fluent Bit Docker container is running as default UTC timestamp  . But our server timezone is refer to different time zone(AEST ).

During the debug mode, it's difficult to understand the different between both timezone. Is there any another way to change the default UTC timezone according to system time zone?

**Log**

See different between both time zone 

[Tue 09/08 09:18 PM] ec2-user@ip:~$ date
**Tue Aug  9 21:18:55 AEST 2022**
[Tue 09/08 09:18 PM] ec2-user@ip:~$ kubectl logs fluent-bit | grep error
**[2022/08/09 11:18:11]** [error] [output:cloudwatch_logs:cloudwatch_logs.0]

**Comment by ym1085** [comment]
I want to know about this issue, too. Is the issue resolved?
