### ISSUE TITLE
Can fluent-bit collect mysql or rds‘s  log ?

### ISSUE THREAD

**Issue by XiaoGe2030** [fluent/fluent-bit#5863]
**Is your feature request related to a problem? Please describe.**

Our mysql cluster is already  deployed in k8s，needs to collect slow logs、error logs . I found Flunet has [mysql-slow-log input plugin](https://github.com/yuku/fluent-plugin-mysqlslowquery) , But flunet-bit dont't have ? 

**Describe the solution you'd like**

Where is the mysql log  input plugin? 

**Describe alternatives you've considered**

Or how to implement a custom input plugin for mysql in flunet-bit?
**Additional context**

**Comment by patrick-stephens** [comment]
Presumably the log you want is on disk, e.g.`/var/log/mysql/mysql-slow.log`

If so just use the tail plugin to read it: you may need to expose the volume it is on to a Fluent Bit sidecar rather than a daemonset deployment.

**Comment by XiaoGe2030** [comment]
> 

I don't just want to store a line by line log , I want to format the log and provide an interface to query it . 
For Example:

---mysql slow log ---
```
# Time: 2022-08-02T12:49:20.223377-00:00
# User@Host: root[root] @ localhost []  Id:     8
# Query_time: 5.03537  Lock_time: 0.000000 Rows_sent: 1  Rows_examined: 1
SET timestamp=1659444555;
select sleep(5);
``` 

--- format and output  es or other storage --- 
```
{
    "user":"root[root]",
    "host":"localhost",
    "host_ip":"",
    "rows_sent":1,
    "sql":"SET timestamp=1660281564; select sleep(5);",
    "last_errno":null,
    "kill":null,
    "lockTime":0,
    "queryTime":5.002687,
    "rowsAffected":null,
    "rowsExamined":1,
    "rowsSent":null,
    "schema":null,
}
```
--- query slow log by es api --- 
```
GET /index/slowlog/xxxx

Can get above  slow log. 
```

I think fluent(td-agent) can meet，because there is mysql-slow-log plugin , td-agent conf like this 
```
<source>
    @type mysql_slow_query
    path /var/lib/mysql/slow-log.log
    tag mysqld.slow_query
    <parse>
        @type none
    </parse>
</source>

<filter *.**>
 @type record_transformer
 enable_ruby true
  <record>
     xxxx   xxxx
  </record>
</filter>

<filter pattern>
  @type record_modifier

  <record>

  </record>
</filter>


<match *.**>
  @type copy

  <store>
    @type elasticsearch
    host 192.168.56.1
    port 9200
    logstash_format true
    index_name fluentd.${tag}.%Y%m%d
  </store>

  <store>
    @type stdout
  </store>
</match>

```

stdout 
```
2022-08-12 05:19:24.000000000 +0000 mysqld.slow_query: {"user":"root[root]","host":"localhost","host_ip":"","rows_sent":1,"sql":"SET timestamp=1660281564; select sleep(5);","msg_last_errno":null,"msg_kill":null,"msg_lockTime":0.0,"msg_queryTime":5.002687,"msg_rowsAffected":null,"msg_rowsExamined":1,"owsSent":null,"chema":null,"slowlog":{"user":"root[root]","host":"localhost","host_ip":"","query_time":5.002687,"lock_time":0.0,"rows_sent":1,"rows_examined":1,"sql":"SET timestamp=1660281564; select sleep(5);","db":null}}
```

I can deploy fluent(td-agent) as daemonset in k8s to collect slow log .

But i just want to know , if fluent-bit has some plugin can finish this work? Or how can I implementing slow-log plugin in fluent-bit .

**Comment by patrick-stephens** [comment]
I'm not sure about the "I want to format it" aspect, you can process, filter and parse a log file in various ways - you don't have to just detain it as-is. Looking at your config, this seems to be exactly what the FluentD plugin is doing anyway:
```
<source>
    @type mysql_slow_query
    path /var/lib/mysql/slow-log.log
    tag mysqld.slow_query
    <parse>
        @type none
    </parse>
</source>
```
Notice it is reading the log file, then presumably just processing it.

There is no bespoke plugin to collect this. I've no idea what databases support but if it can stream logs out then that can be collected via http, syslog, etc.

The exec plugin can make calls and you receive the results to process but this is not available in the official distroless containers as it requires a shell.

In Fluent Bit 2.0, Golang input plugins will be available but until then follow the advice here to create a new plugin in C: https://docs.fluentbit.io/manual/development/developer-guide#input

**Comment by XiaoGe2030** [comment]
邮件已收到！
