### ISSUE TITLE
[latency] with many log files in `/var/log/*` fluentbit has latency with loki plugin.

### ISSUE THREAD

**Issue by RRoundTable** [fluent/fluent-bit#5868]
## Bug Report

**Describe the bug**

**To Reproduce**

- config: helm chart
```
    service: |
      [SERVICE]
          log_level {{ .Values.logLevel }}
          parsers_file parsers.conf
          parsers_file custom_parsers.conf
          http_server On
          http_listen 0.0.0.0
          http_port {{ .Values.metricsPort }}
          health_check On
          storage.path              /var/log/flb-storage/
          storage.sync              normal
          storage.checksum          off
          storage.backlog.mem_limit 100M
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 50MB
          Skip_Long_Lines On
      [INPUT]
          name cpu
          storage.type  filesystem

    outputs: |
      [OUTPUT]
          name   loki
          match  *
          labels job=fluentbit, mystream=$stream, container_name=$kubernetes['container_name'], pod_name=$kubernetes['pod_name'], pod_host=$kubernetes['host'], namespace=$kubernetes['namespace_name']
          host  loki.default.svc.cluster.local
          port 3100
          auto_kubernetes_labels on

```

- with 2 pod log file, tail has no latency (total log interval is about `0.04sec`) 

```
# curl -s http://127.0.0.1:2020/api/v1/metrics/prometheus
# with 2 pod(container) log file 
{
  "input": {
    "tail.0": {
      "records": 7839,
      "bytes": 985479,
      "files_opened": 2,
      "files_closed": 0,
      "files_rotated": 0
    },
    "cpu.1": {
      "records": 431,
      "bytes": 165073
    },
    "storage_backlog.2": {
      "records": 11349,
      "bytes": 4346667
    }
  },
  "filter": {
    "kubernetes.0": {
      "drop_records": 0,
      "add_records": 0
    }
  },
  "output": {
    "loki.0": {
      "proc_records": 7968,
      "proc_bytes": 4821545,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0,
      "dropped_records": 0,
      "retried_records": 0
    }
  }
}
```

- with 5 pod(container) log file, tail has latency (total log interval is about `0.04sec`) 
```
# curl -s http://127.0.0.1:2020/api/v1/metrics/prometheus
# with 5 pod(container) log file
{
  "input": {
    "tail.0": {
      "records": 8677,
      "bytes": 1091045,
      "files_opened": 5,
      "files_closed": 0,
      "files_rotated": 0
    },
    "cpu.1": {
      "records": 338,
      "bytes": 129454
    },
    "storage_backlog.2": {
      "records": 12749,
      "bytes": 4882867
    }
  },
  "filter": {
    "kubernetes.0": {
      "drop_records": 0,
      "add_records": 0
    }
  },
  "output": {
    "loki.0": {
      "proc_records": 2346,
      "proc_bytes": 1473916,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0,
      "dropped_records": 0,
      "retried_records": 0
    }
  }
}
```

- Steps to reproduce the problem:

**Expected behavior**

Regardless of log files, fluentbit has a similar performance with similar log interval.

**Screenshots**

loki + grafana dashboard

![image](https://user-images.githubusercontent.com/27891090/184082978-8b91a975-5ce6-4585-af41-c16484c83830.png)

**Your Environment**

* Version used: v1.9.6
* Configuration:
* Environment name and version minikube version: v1.26.0
* Server type and version:
* Operating System and version: MacOS
* Filters and plugins:

**Additional context**

**Comment by sflanker** [comment]
I don't think this is limited to environments with "many log files" I have created a minimal reproducible example of the Loki output plugin falling gradually behind in sending logs to Loki: https://github.com/revacomm-pwheeler/fluent-bit-loki-grafana

The [3rd party Grafana plugin](https://grafana.com/docs/loki/latest/clients/fluentbit/) has no such issue.

Additionally, if I configure two output plugins side-by-side where one is not the native Loki pipeline (for example the s3 output plugin or the 3rd party Grafana plugin), then the other plugin does fine and the native Loki plugin **drops logs** and does not ship them to Loki at all.

I believe this is a critical issue and the native Loki plugin has some critical flaws. It absolutely cannot be used in production in its current state.

**Comment by sflanker** [comment]
I have added a branch to my repo which demonstrates the loss of log data when configuring a second type of output plugin along side the native Loki output plugin: https://github.com/revacomm-pwheeler/fluent-bit-loki-grafana/tree/multiple-plugins

I've attached an excel spreadsheet that compares the output of the following LogQL queries for the same time window:

Native: `{namespace="flux-system",job="fluent-bit"}|json log,time|line_format "{{.time}}"`

Grafana: `{namespace="flux-system",job="grafana"}|json log,time|line_format "{{.time}}"`

If you look at the "Native" tab you will see that every log entry has a corresponding entry from the Grafana plugin back to the point in time at which the Grafana plugin query hit the 1K line limit. However, if you look at the Grafana tab you will see that there are substantial gaps where the Grafana plugin correctly sent logs to Loki but the Native plugin skipped those logs completely.

[Grafana vs Native Plugin Comparison.xlsx](https://github.com/fluent/fluent-bit/files/9682277/Grafana.vs.Native.Plugin.Comparison.xlsx)

**Comment by sflanker** [comment]
It is possible that adding the following to the `[OUTPUT]` configuration for the loki plugin fixes the issue:

```
workers 2
```

I am still investigating why the performance with the default configuration is so abysmal.

**Comment by sflanker** [comment]
I think the issue stems from or is related to the fact that the Loki plugin has the `FLB_OUTPUT_NO_MULTIPLEX` flag set. This seems to limit the Loki output plugin to processing one "task" per flush, and `flb_engine_dispatch.c` ends up simply skipping a longer and longer list of tasks per cycle.

Note: It takes the loki plugin almost no time at all to actually process a flush task (I've added tracing to report when a flush starts and completes and how much time it takes, and the whole thing including the HTTP post takes a fraction of a second).

**Comment by sflanker** [comment]
I've recompiled without the `FLB_OUTPUT_NO_MULTIPLEX` flag set for the Loki plugin and it seems to resolve the issue in my preliminary testing. @edsiper as the original author of this plugin do you have any thoughts regarding the rationale for having this flag set? It looks like Loki is the only plugin using it. Would you expect the behavior to be so radically different with and without this flag?

**Comment by RRoundTable** [comment]
> I don't think this is limited to environments with "many log files" I have created a minimal reproducible example of the Loki output plugin falling gradually behind in sending logs to Loki: https://github.com/revacomm-pwheeler/fluent-bit-loki-grafana I have all of 10 or 11 files in `/var/log/containers/` which is the only source that I'm loading with the `tail` input plugin.
> 
> The [3rd party Grafana plugin](https://grafana.com/docs/loki/latest/clients/fluentbit/) has no such issue.
> 
> Additionally, if I configure two output plugins side-by-side where one is not the native Loki pipeline (for example the s3 output plugin or the 3rd party Grafana plugin), then the other plugin does fine and the native Loki plugin **drops logs** and does not ship them to Loki at all.
> 
> I believe this is a critical issue and the native Loki plugin has some serious flaws. I absolutely cannot use it in production in its current state.

Thanks, I edited the title of issue.

**Comment by edsiper** [comment]
@sflanker we created that flag since Loki did not supported records out of order (we don't guarantee order, e.g: network issue when delivering a chunk), that flag ensure only one Chunk is delivered at a time.

but this is a good call, since I remember that now Loki provides records out of order, so we could remove that flag that restricts multiplexing multiple chunks. If you confirm removing it works as expected, happy to get rid of it.

**Comment by sflanker** [comment]
Ah, that explains a lot, thank you! Loki does indeed support out of order writes now, [as of v2.4  release December of last year](https://grafana.com/blog/2021/12/03/new-feature-in-loki-2.4-no-more-ordering-constraint/).

I've been running with this flag removed in my test environment for several hours now and things seem to be working perfectly.

Is there any concern about breaking backward compatibility for folks still running older versions of Loki, or using the `unordered_writes` setting in their Loki config? Is the project tracking towards a 2.x release? If so it might make sense to hold the change until then. And even if the default is changed, it might be necessary to provide a configurable option to preserve the current behavior (although when Loki is configured side-by-side with another plugin the current behavior is pretty sub-optimal).

**Comment by sflanker** [comment]
@edsiper Glad to.

PR: https://github.com/fluent/fluent-bit/pull/6136
Issue: https://github.com/fluent/fluent-bit/issues/6137

Thank you for your help!
