### ISSUE TITLE
Support Wildcard for nest lift keys

### ISSUE THREAD

**Issue by adaniline-rkt** [fluent/fluent-bit#5869]
**Is your feature request related to a problem? Please describe.**
I have some applications outputting flat logs, and some JSON logs with messages ending up under `log_processed.message`.
I would like to modify the logs to have log messages under the same key in Kibana.
The first solution was to to use Modify raname filter:
```
    [FILTER]
        name                 modify
        match                java*
        Rename             log message

    [FILTER]
        name                 modify
        match                json*
        Rename             log_processed.message message

```
It renames the root keys, but looks like Modify does not work with nested keys (#2152).
I think a useful feature would to be able selectively lift keys with nest filter using Wildcard, as with nest.

**Describe the solution you'd like**
Input: 
```json
{
 "nested": {
   "k1": "v1",
   "k2": "v2"
  }
}
```
Config:
```
[FILTER]
    Name nest
    Match *
    Operation lift
    Nested_under nested
    Wildcard k1
```
Output:
```json
{
  "k1": "v1",
 "nested": {
   "k2": "v2"
  }
}
```

**Comment by SebastianScherer88** [comment]
to clarify: as the poster implied (though not explicitly) the wildcard can be used in `nest` mode to define the scope of the fields to be `nest`ed, but is not supported in `lift` mode. expanding the wildcard feature to the `lift` mode of this filter only makes sense imo, and is needed to be able to use `lift` and `nest` as inverse of each other. i'm sure that for that reason alone there are many use cases of this
