### ISSUE TITLE
Multiline will never flush

### ISSUE THREAD

**Issue by YoussefRizkalla** [fluent/fluent-bit#5871]
## Bug Report

Currently, multiline flushing is invoked via a callback according to the flush timeout set. However, the callback has a [condition](https://sourcegraph.com/github.com/fluent/fluent-bit@fc325524d50fe179b76f127243ab9e03ddbdaaa4/-/blob/src/multiline/flb_ml.c?L155) which can prevent the flush.

Due to this condition, it is possible for the `last_flush` to permanently fall behind the timestamp, as it will never be updated. There is currently no recovery mechanism for this, which can permanently stop flushing. 

I have noticed that the scheduler will continue to correctly invoke the callback according to the set flush timeout, but it will never flush as the function returns after the condition. Is there a reason this condition is needed?

Version used: 1.9.6

**Comment by JeffLuoo** [comment]
@leonardo-albertovich @PettitWesley @edsiper For visibility

**Comment by ptsneves** [comment]
Hey @YoussefRizkalla Do you also interpret the issue in that the condition is inverted? From what i understand of these types of conditions is that you should not handle them if the expected timer expiry is in the future. Here it is the opposite?

**Comment by YoussefRizkalla** [comment]
> Hey @YoussefRizkalla Do you also interpret the issue in that the condition is inverted? From what i understand of these types of conditions is that you should not handle them if the expected timer expiry is in the future. Here it is the opposite?

I think that may be a reasonable interpretation - it looks like there is some discussion about this in #5937

**Comment by ptsneves** [comment]
Great, i independently came up with the patch and it works for me. Have you tried it?

**Comment by YoussefRizkalla** [comment]
> Great, i independently came up with the patch and it works for me. Have you tried it?

I no longer have access to the exact environment in which I initially observed this issue. Though it works perfectly during my local testing and it checks out logically so I will be closing the issue.

Thanks for bringing this up and to @frdeboffles for the work on this!
