### ISSUE TITLE
1.9.7 config errors are misleading and mention classic mode unnecessarily

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#5880]
## Bug Report

**Describe the bug**

If you have an invalid config you get this error now:

```
[2022/08/12 21:32:51] [error] [config] error in /fluent-bit/etc/fluent-bit.conf:9: undefined key - check config is in valid classic format
```

However, this is not caused by an invalid key option, just a key lacking a value:

```
[INPUT]
    Name dummy
    Tag dummy

[FILTER]
    Name modify
    Match *
    ADD foo bar
    ADD

[OUTPUT]
    Name stdout
    Match *
    Format
```

**Comment by PettitWesley** [comment]
I want to reference this issue too, we need to get better at user experience: https://github.com/fluent/fluent-bit/issues/3505

Difficult to understand user experience around configuration and errors is the most common type of complaint I get from my customers. 

@patrick-stephens

**Comment by nokute78** [comment]
I sent a patch #5881.
