### ISSUE TITLE
fluent-bit-1.9.7-win64 fails to be executed

### ISSUE THREAD

**Issue by NakagawaMakoto** [fluent/fluent-bit#5885]
## Bug Report

fluent-bit-1.9.7-win64 fails to be executed. fluent-bit-1.9.6-win64 works fine.

`> fluent-bit-1.9.7-win64\bin\fluent-bit.exe -i dummy -o stdout`
fails with the dialog saying "The code execution cannot proceed because libssl-1_1-x64__.dll was not found."

I tested on Windows10 and Windows Server 2019. Does nobody else have this issue?

**Comment by vishwa-trulioo** [comment]
I'm having the same issue. The 64 bit version of fluent bit is not working. However, the 32 bit one is working fine. I did the same experiment as @NakagawaMakoto and experienced the same behaviour.

**Comment by patrick-stephens** [comment]
Apologies, this feels like the same AppVeyor issue we had with 1.9.6 so let me see if I can resolve it again.

**Comment by patrick-stephens** [comment]
Ah, the resolution is on `master` and not the `1.9` branch so let's get that merged across: https://github.com/fluent/fluent-bit/commit/8a38831885366389b5bb816df31cd5a2525742bd

**Comment by patrick-stephens** [comment]
Should be resolved now for these:
```
e44dbd55298c2885a40a54cd2cc252ba6f9256a73fee155373044b4fd75bf3b9  fluent-bit-1.9.7-win32.exe
6767fca161d36ee38e24e775a3579f046a1ca6c97c92c6f8e1205cb1cefc10d1  fluent-bit-1.9.7-win32.zip
b6fcd36f12e7520485c6a8dda5851899e4ab0e65c2601fb699aaffe70bc7c86f  fluent-bit-1.9.7-win64.exe
6f1c9d8a5bfff47b309d892419c9c2515a1d1030f937406e419074403d788043  fluent-bit-1.9.7-win64.zip
08326e9b72194b05383ae8c72d476c2fd4f1895ae330eb91db21504ca9d67477  td-agent-bit-1.9.7-win32.exe
a5a10f33abaf9f4f64759ffac3dd95565ebb57887faef3b00d4885e264a1bb5b  td-agent-bit-1.9.7-win32.zip
bbc2db85811d39ace04831d2e9543ff62f1126a8fd0ef3e1ab50894bb7eb47a6  td-agent-bit-1.9.7-win64.exe
c3d1f2b52df92b9500c5bbed9f0042ae1758fc67b6ff96aa5d19dd97143292af  td-agent-bit-1.9.7-win64.zip

```

**Comment by patrick-stephens** [comment]
@NakagawaMakoto is this resolved with the updated binaries?

**Comment by NakagawaMakoto** [comment]
@patrick-stephens thank you for your prompt action. I have verified fluent-bit-1.9.7-win64.zip works without any errors.
