### ISSUE TITLE
Unable to send prometheus metrics to elastic

### ISSUE THREAD

**Issue by m-pavel** [fluent/fluent-bit#5895]
## Bug Report

**Describe the bug**
It says 
```
data generated by prometheus_scrape.0 input are metrics, but matching destination plugin es.0 don't handle metrics.Skipping destination.
```
Ok, but how can I convert metrics to es message, or whatever it need ?
 
** Config **
```
[INPUT]
  name prometheus_scrape
  host 127.0.0.1
  port 8080
  metrics_path /actuator/prometheus
[OUTPUT]
  Name  es
  Match *
  Host  elastic
  Port  9200

```

**Comment by patrick-stephens** [comment]
Elastic requires metrics in their format unfortunately and the current elastic output plugin copes with logs only (for now).

You can send metrics to any Prometheus compatible endpoint but for Elastic this may require a proxy via something like metricbeat or similar: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html

If you have a Prometheus instance then it is trivial to scrape or remote write to it as per the docs.
