### ISSUE TITLE
fluentbit-debug images sets log level to debug

### ISSUE THREAD

**Issue by marwansalem** [fluent/fluent-bit#5897]
I was using this image `fluent/fluent-bit:1.8.12-debug`.
I had the log level set to info in the conf files.

I found out that there are a lot of logs produced from fluent-bit.
I assumed that the debug image provides the shell which is missing from the other images.

But now my only guess for the massive log volume that the debug image sets the log level to a lower level, hence the log volume.
Please correct me if my last assumption is incorrect

**Comment by patrick-stephens** [comment]
That image is quite old and unsupported now, please retry with the latest (1.9.7) version then provide details of configuration and example logs, etc.
