### ISSUE TITLE
input tail not work in centos 6.3

### ISSUE THREAD

**Issue by show168** [fluent/fluent-bit#590]
in centos 6.3：
fluent-bit -i tail -p path=/var/log/syslog -o stdout
echo "something" >> /var/log/syslog
nothing appear in the stdout

in centos7
fluent-bit -i tail -p path=/var/log/syslog -o stdout
echo "something" >> /var/log/syslog
something appear in the stdout

why input tail not work in centos6.3? how to let it work?

**Comment by edsiper** [comment]
For the moment we support Centos >= 7
