### ISSUE TITLE
fluent-bit(15986,0x30e320000) malloc: Incorrect checksum for freed object 0x7ff5b580aa00: probably modified after being freed.

### ISSUE THREAD

**Issue by hpwahyao** [fluent/fluent-bit#5909]
Hi, 

I run fluent-bit in iMac (M1 chip), and forward PM2 log to Fluentd. Fluent-bit keeps crashing with the following message: 
**fluent-bit(15986,0x30e320000) malloc: Incorrect checksum for freed object 0x7ff5b580aa00: probably modified after being freed.**

Any idea how to fix it? 

Full log as below: 

iMac ~ % fluent-bit -i tail -p path=~/.pm2/logs/SSOBackend-out-0.log -o forward://127.0.0.1:24224              
Fluent Bit v1.9.7
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/08/18 10:34:47] [ info] [fluent bit] version=1.9.7, commit=, pid=15986
[2022/08/18 10:34:47] [ info] [storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/08/18 10:34:47] [ info] [cmetrics] version=0.3.5
[2022/08/18 10:34:47] [ info] [output:forward:forward.0] worker #0 started
[2022/08/18 10:34:47] [ info] [output:forward:forward.0] worker #1 started
[2022/08/18 10:34:47] [ info] [sp] stream processor started
fluent-bit(15986,0x30e320000) malloc: Incorrect checksum for freed object 0x7ff5b580aa00: probably modified after being freed.
Corrupt value: 0x32203a534e442074
fluent-bit(15986,0x30e320000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      fluent-bit -i tail -p path=~/.pm2/logs/SSOBackend-out-0.log -o

**Comment by hpwahyao** [comment]
same issue still appearing ...

**Comment by Dieken** [comment]
same issue here, can't believe fluent-bit still has memory bugs after 8 years development.

```
$ lldb /usr/local/bin/fluent-bit 

(lldb) target create "/usr/local/bin/fluent-bit"
Current executable set to '/usr/local/bin/fluent-bit' (x86_64).
(lldb) run -c agent.conf
Process 86409 launched: '/usr/local/bin/fluent-bit' (x86_64)
Fluent Bit v2.0.6
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/12/13 12:37:58] [ info] [fluent bit] version=2.0.6, commit=, pid=86409
[2022/12/13 12:37:58] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/12/13 12:37:58] [ info] [cmetrics] version=0.5.7
[2022/12/13 12:37:58] [ info] [ctraces ] version=0.2.5
[2022/12/13 12:37:58] [ info] [input:tail:tail.0] initializing
[2022/12/13 12:37:58] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2022/12/13 12:37:58] [ info] [sp] stream processor started
[2022/12/13 12:37:58] [ info] [output:forward:forward.0] worker #0 started
[2022/12/13 12:37:58] [ info] [output:forward:forward.0] worker #1 started
fluent-bit(86409,0x700002866000) malloc: Incorrect checksum for freed object 0x102018210: probably modified after being freed.
Corrupt value: 0x0
fluent-bit(86409,0x700002866000) malloc: *** set a breakpoint in malloc_error_break to debug
Process 86409 stopped
* thread #5, name = 'flb-out-forward.0-w1', stop reason = signal SIGABRT
    frame #0: 0x00007ff81465100e libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`:
->  0x7ff81465100e <+10>: jae    0x7ff814651018            ; <+20>
    0x7ff814651010 <+12>: movq   %rax, %rdi
    0x7ff814651013 <+15>: jmp    0x7ff81464b1c5            ; cerror_nocancel
    0x7ff814651018 <+20>: retq   
Target 2: (fluent-bit) stopped.
(lldb) 
error: No auto repeat.
(lldb) bt
* thread #5, name = 'flb-out-forward.0-w1', stop reason = signal SIGABRT
  * frame #0: 0x00007ff81465100e libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007ff8146871ff libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007ff8145d2d24 libsystem_c.dylib`abort + 123
    frame #3: 0x00007ff8144b0357 libsystem_malloc.dylib`malloc_vreport + 551
    frame #4: 0x00007ff8144c4308 libsystem_malloc.dylib`malloc_zone_error + 178
    frame #5: 0x00007ff8144a903d libsystem_malloc.dylib`small_free_list_remove_ptr_no_clear + 1251
    frame #6: 0x00007ff8144a6024 libsystem_malloc.dylib`free_small + 619
    frame #7: 0x000000010003d5b3 fluent-bit`flb_output_flush_finished + 219
    frame #8: 0x000000010003fa39 fluent-bit`output_thread + 2234
    frame #9: 0x0000000100055f56 fluent-bit`step_callback + 34
    frame #10: 0x00007ff8146874e1 libsystem_pthread.dylib`_pthread_start + 125
    frame #11: 0x00007ff814682f6b libsystem_pthread.dylib`thread_start + 15
(lldb) 
```

Fluent-Bit 2.0.6, macOS 12.5.1, Intel CPU.

**Comment by leonardo-albertovich** [comment]
This bug  is being addressed and will be fixed in the next release.

**Comment by prasiraj** [comment]
Had similar error... tried with -v option and it worked with out the failure... without -v option it is throwing out same errors.. Just to help debug the issue... Thanks.
