### ISSUE TITLE
How do I retrieve docker metrics with cgroup v2

### ISSUE THREAD

**Issue by sudoalyona** [fluent/fluent-bit#5949]
The documentation for docker metrics plugin needs to be extended. The plugin doesn't work if implemented just the way it's given in the example. [This issue](https://github.com/fluent/fluent-bit/issues/3882) sheds more light on how to make it work, however it's completely inapplicable to cgroups v2. How do I make docker metrics work in case of v2?

**Comment by robinwkurtz** [comment]
Looks like it's being worked on: https://github.com/fluent/fluent-bit/pull/6658

But I see no mention of when it might be available.

@sudoalyona, did you find a work around?
