### ISSUE TITLE
syslog support in the output side.

### ISSUE THREAD

**Issue by manu844** [fluent/fluent-bit#595]
Right now there is no support for forwarding logs to remote syslog endpoint in Output plugins. It would be great to have the support in fluent bit.

**Comment by DennyZhang** [comment]
Yes, we get the same requirements

**Comment by hellojukay** [comment]
we have the same requirements!

**Comment by edsiper** [comment]
would you please describe the syslog formats you mostly need ?

**Comment by manu844** [comment]
@edsiper the standard syslog format supported is `rfc5424`, I don't think `rfc3164` is still in use anywhere, but i will leave to others if they require it.

**Comment by edsiper** [comment]
already being addressed on these PRs (we are evaluating which approach to follow)

- https://github.com/fluent/fluent-bit/pull/1551
- https://github.com/fluent/fluent-bit/pull/1601

**Comment by coolpalani** [comment]
Could you finalize any one of the PR which is more flexible/suitable to community needs and followed as per community standards. So that this syslog output request will be fully complete.
