### ISSUE TITLE
OUT_KAFKA cannot use rdkafka.compression.type zstd

### ISSUE THREAD

**Issue by 0123hoang** [fluent/fluent-bit#5957]
## Bug Report

**Describe the bug**
I cannot use rdkafka.compression.type/rdkafka.compression.codec which value is "zstd", but snappy/lz4 it work normally.

**To Reproduce**
```
[OUTPUT]
    Name            kafka
    Match           kube.*
    Topics          fluentbit
    Timestamp_format  iso8601
    Brokers         []
    Queue_full_retries  0
    Storage.total_limit_size  20M
    Retry_Limit     no_limits
    rdkafka.socket.keepalive.enable         true
    rdkafka.broker.address.ttl              86400000
    rdkafka.security.protocol  SSL
    rdkafka.ssl.key.location  /certkafka/ca-key
    rdkafka.ssl.certificate.location  /certkafka/ca-cert
    rdkafka.ssl.ca.location  /certkafka/ca-root
    rdkafka.enable.ssl.certificate.verification  false
    rdkafka.enable.idempotence  false
    rdkafka.queue.buffering.max.ms  200
    rdkafka.compression.type zstd
    #rdkafka.compression.level  4
    rdkafka.log.connection.close  false
```
- Log
```
[2022/08/30 02:07:37] [error] [flb_kafka] cannot configure 'compression.type' property
```

**Comment by 0123hoang** [comment]
I use fluent-bit 1.9.7.

**Comment by sisteinmetz** [comment]
Same behaviour with 1.9.9

**Comment by alt-dima** [comment]
@sisteinmetz @0123hoang Is this a problem with fluent-bit in the official container (cr.fluentbit.io/fluent/fluent-bit:1.9.9) or binary/packed (ubuntu deb)?
Because I see, that containers being build with all libraries
https://github.com/fluent/fluent-bit/actions/runs/3227515877/jobs/5282437264#step:7:362

But binaries/packages are not
https://github.com/fluent/fluent-bit/actions/runs/3227515877/jobs/5282436311#step:6:94

I'm not 100% expert and may be wrong with my findings.
Can you try the same config with docker image?

**Comment by alt-dima** [comment]
Probably, zstd dev lib is not included. Only zlib1g-dev
https://github.com/fluent/fluent-bit/actions/runs/3227515877/jobs/5282437264#step:7:476

Here we can see
https://github.com/edenhill/librdkafka#requirements
```
zlib-dev (optional, for gzip compression support)
libzstd-dev (optional, for ZStd compression support)
```
And lz4 is "build-in"

**Comment by sisteinmetz** [comment]
i tried with docker image (image: fluent/fluent-bit:1.9.9) and it is worst.
Whatever i use as rdkafka.compression.type message in topics are not compressed:

[appuser@broker bin]$ kafka-run-class kafka.tools.DumpLogSegments --files /var/lib/kafka/data/dummy-lz4-2-0//00000000000000000000.log  --print-data-log | grep compresscodec
baseOffset: 0 lastOffset: 0 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 0 CreateTime: 1666086211823 size: 118 magic: 2 **compresscodec: none** crc: 2899118956 isvalid: true
baseOffset: 1 lastOffset: 1 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 118 CreateTime: 1666086212823 size: 118 magic: 2 **compresscodec: none** crc: 2338074787 isvalid: true
baseOffset: 2 lastOffset: 2 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 236 CreateTime: 1666086213824 size: 118 magic: 2 **compresscodec: none** crc: 3477678429 isvalid: true
baseOffset: 3 lastOffset: 3 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 354 CreateTime: 1666086214823 size: 118 magic: 2 **compresscodec: none** crc: 1891027680 isvalid: true
baseOffset: 4 lastOffset: 4 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 472 CreateTime: 1666086215824 size: 117 magic: 2 **compresscodec: none** crc: 2778248999 isvalid: true
baseOffset: 5 lastOffset: 5 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 589 CreateTime: 1666086216823 size: 118 magic: 2 **compresscodec: none** crc: 1884779545 isvalid: true
baseOffset: 6 lastOffset: 6 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 707 CreateTime: 1666086217823 size: 118 magic: 2 **compresscodec: none** crc: 3659995757 isvalid: true
baseOffset: 7 lastOffset: 7 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 825 CreateTime: 1666086218823 size: 118 magic: 2 **compresscodec: none** crc: 4015698214 isvalid: true
baseOffset: 8 lastOffset: 8 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 943 CreateTime: 1666086219823 size: 118 magic: 2 **compresscodec: none** crc: 2001445236 isvalid: true
baseOffset: 9 lastOffset: 9 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1061 CreateTime: 1666086220824 size: 118 magic: 2 **compresscodec: none** crc: 2516137566 isvalid: true
baseOffset: 10 lastOffset: 10 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1179 CreateTime: 1666086221823 size: 117 magic: 2 **compresscodec: none** crc: 1153710011 isvalid: true
baseOffset: 11 lastOffset: 11 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1296 CreateTime: 1666086222826 size: 118 magic: 2 **compresscodec: none** crc: 45941754 isvalid: true

Here is fluent-bit.conf:
[INPUT]
    name dummy
    tag  dummy.local

[OUTPUT]
    name  stdout
    match *


[OUTPUT]
    Match *
    Name        kafka
    Brokers     broker:29092
    Topics      dummy-lz4-2
    rdkafka.receive.message.max.bytes    2147483647
    rdkafka.security.protocol   PLAINTEXT
    rdkafka.request.required.acks 0
    rdkafka.log.connection.close false
    rdkafka.client.id lz4
    rdkafka.compression.type lz4
    rdkafka.compression.codec lz4

**Comment by sisteinmetz** [comment]
Hello, 

"Probably, zstd dev lib is not included. Only zlib1g-dev"

How and where can i include this lib ? on librdkafka build ? on fluentbit build ? on the target engine ? I just need to install libzstd-dev on the server ?

**Comment by sisteinmetz** [comment]
I installed libzstd-dev on my server but i still got the problem running output kazfka plugin with zstd compression :

admin@ip-172-31-14-209:~$ sudo apt-get install libzstd-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
**libzstd-dev is already the newest version (1.3.8+dfsg-3+deb10u2).**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

admin@ip-172-31-14-209:~$ sudo service fluent-bit status
● fluent-bit.service - Fluent Bit
   Loaded: loaded (/lib/systemd/system/fluent-bit.service; disabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-10-18 10:15:49 UTC; 2min 26s ago
     Docs: https://docs.fluentbit.io/manual/
 Main PID: 15854 (fluent-bit)
    Tasks: 10 (limit: 4915)
   Memory: 52.4M
   CGroup: /system.slice/fluent-bit.service
           └─15854 /opt/fluent-bit/bin/fluent-bit -c //etc/fluent-bit/fluent-bit.conf

Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [storage] version=1.3.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [cmetrics] version=0.3.7
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [input:http:http.2] listening on 0.0.0.0:8888
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [input:node_exporter_metrics:node_exporter_metrics.3] path.procfs = /proc
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [input:node_exporter_metrics:node_exporter_metrics.3] path.sysfs  = /sys
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [output:prometheus_exporter:prometheus_exporter.0] listening iface=0.0.0.0 tcp_port=2021
**Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [error] [flb_kafka] cannot configure 'compression.type' property
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [error] [flb_kafka] cannot configure 'compression.codec' property**
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [output:kafka:kafka.1] brokers='localhost:9092' topics='cpu-zstd'
Oct 18 10:15:49 ip-172-31-14-209 fluent-bit[15854]: [2022/10/18 10:15:49] [ info] [sp] stream processor started

**Comment by alt-dima** [comment]
With
```
rdkafka.compression.type lz4
rdkafka.compression.codec lz4
```
Did you saw `[error] [flb_kafka] cannot configure 'compression.codec' property` error? Or error was not appeared , but messages are not being compressed (by lz4)?

What compression.type	is set for topic? May be should be `producer`, which means retain the original compression codec set by the producer?
https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-properties.html

To enable zstd you need to install `libzstd-dev` on the build node and build fluent-bit image.
On the target server (where fluent-bit will run), probably, libzstd should be installed (not libzstd-dev!)

**Comment by alt-dima** [comment]
I checked my topic config
```
dmitrii:fluent-bit dmitriialtukhov$ kafka-configs --bootstrap-server b-1.stagmazonaws.com:9092 --entity-type topics --describe --all --entity-name app-logs
All configs for topic app-logs are:
  compression.type=producer sensitive=false synonyms={DEFAULT_CONFIG:compression.type=producer}
```

**Comment by sisteinmetz** [comment]
My  compression.type for topic is always producer

**Comment by sisteinmetz** [comment]
_Did you saw [error] [flb_kafka] cannot configure 'compression.codec' property error? Or error was not appeared , but messages are not being compressed (by lz4)?_

=> The error not appeared but messages are not being compressed :
 
Fluentbit conf:
_[INPUT]
    name dummy
    tag  dummy.local
[OUTPUT]
    name  stdout
    match *
[OUTPUT]
    Match *
    Name        kafka
    Brokers     broker:29092
    Topics      dummy-lz4-3
    rdkafka.receive.message.max.bytes    2147483647
    rdkafka.security.protocol   PLAINTEXT
    rdkafka.request.required.acks 0
    rdkafka.log.connection.close false
    rdkafka.client.id lz4
    rdkafka.compression.type lz4
    rdkafka.compression.codec lz4_

Fluentbit log:
_Fluent Bit v1.9.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/18 11:03:38] [ info] [fluent bit] version=1.9.9, commit=5c03b2e555, pid=1
[2022/10/18 11:03:38] [ info] [storage] version=1.3.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[2022/10/18 11:03:38] [ info] [cmetrics] version=0.3.7
[2022/10/18 11:03:38] [ info] [output:stdout:stdout.0] worker #0 started
[2022/10/18 11:03:38] [ info] [output:kafka:kafka.1] brokers='broker:29092' topics='dummy-lz4-3'
[2022/10/18 11:03:38] [ info] [sp] stream processor started_

Messages compressions
_[appuser@broker bin]$ kafka-run-class kafka.tools.DumpLogSegments --files /var/lib/kafka/data/dummy-lz4-3-0/00000000000000000000.log  print-data-log | grep compresscodec
baseOffset: 0 lastOffset: 28 count: 29 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 0 CreateTime: 1666091047808 size: 648 magic: 2 compresscodec: lz4 crc: 2924653062 isvalid: true
baseOffset: 29 lastOffset: 47 count: 19 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 648 CreateTime: 1666091066808 size: 472 magic: 2 compresscodec: lz4 crc: 918331225 isvalid: true
baseOffset: 48 lastOffset: 48 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1120 CreateTime: 1666091067808 size: 118 magic: 2 compresscodec: none crc: 4040891323 isvalid: true
baseOffset: 49 lastOffset: 49 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1238 CreateTime: 1666091068808 size: 118 magic: 2 compresscodec: none crc: 1138678094 isvalid: true
baseOffset: 50 lastOffset: 50 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1356 CreateTime: 1666091069808 size: 117 magic: 2 compresscodec: none crc: 2998087229 isvalid: true
baseOffset: 51 lastOffset: 51 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1473 CreateTime: 1666091070808 size: 118 magic: 2 compresscodec: none crc: 4275125421 isvalid: true
baseOffset: 52 lastOffset: 52 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1591 CreateTime: 1666091071808 size: 118 magic: 2 compresscodec: none crc: 2703696981 isvalid: true
baseOffset: 53 lastOffset: 53 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1709 CreateTime: 1666091072808 size: 118 magic: 2 compresscodec: none crc: 3242196296 isvalid: true_

**Comment by alt-dima** [comment]
I see `compresscodec: lz4` and next time `compresscodec: none`
Very weired
```
baseOffset: 29 lastOffset: 47 count: 19 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 648 CreateTime: 1666091066808 size: 472 magic: 2 compresscodec: lz4 crc: 918331225 isvalid: true
baseOffset: 48 lastOffset: 48 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false position: 1120 CreateTime: 1666091067808 size: 118 magic: 2 compresscodec: none crc: 4040891323 isvalid: true
```

**Comment by sisteinmetz** [comment]
Yes, true ! Sometimes, the firsts messages are compressed... But not the other...

I rebuild a docker image from master but i got the same result.....

I will try to rebuild an image from tag 1.9.9....

**Comment by sisteinmetz** [comment]
I rebuild an image from tag 1.9.9

Topics compression.type are always 'producer'

with :
rdkafka.compression.type zstd
rdkafka.compression.codec zstd

I have the error message "cannot configure 'compression.codec' property" and messages are not compressed

with :
rdkafka.compression.type lz4
rdkafka.compression.codec lz4

I do not have the error message but messages are not compressed....

Tell me if you want i do more tests...

**Comment by alt-dima** [comment]
Now I'm trying to check messages compression in AWS MSK (AWS managed kafka), because we do not have an access to kafka's storage and use DumpLogSegments.

Before that I was happy and thought that compression works :)

**Comment by alt-dima** [comment]
@sisteinmetz for now you can check with direct/manual compressed messages sending to kafka 
`kafka-console-producer --compression-codec gzip ....`
and check test messages = all of them will be compressed?

**Comment by sisteinmetz** [comment]
I have another env. (EC2 on AWS (Debian10)) and fluentbit is installed (v1.9.9) (not a container)
Oct 18 12:09:28 ip-172-31-14-209 fluent-bit[16218]: [2022/10/18 12:09:28] [ info] [fluent bit] version=1.9.9, commit=, pid=16218

On this env, i configure fluentbit to compress with lz4 and all messages are well compressed

On this env, if i configure fluentbit to compress with zstd, i have error message "cannot configure 'compression.codec' property" and messages are not compressed

**Comment by sisteinmetz** [comment]
Still not work with v2.x.x

**Comment by yackushevas** [comment]
Not stale.
