### ISSUE TITLE
FluentBit loss of logs with logstash disconnection

### ISSUE THREAD

**Issue by shashankshukla2** [fluent/fluent-bit#5959]
## Bug Report

**Describe the bug**

When running the fluentbit with output to logstash i see loss of logs when logstash gets disconnected and starts again.
That is, fluentbit is not able to handle the buffer in the time logstash starts up.

mem_buff_limit is used but no change in result i.e loss of logs with increasing or decreasing the limit.

**To Reproduce**
- Steps to reproduce the problem:

1) Run logstash and fluentbit.
2) Disconnect logstash for few seconds.
3) Restart logstash.

**Expected behavior**

No loss of logs if logstash gets disconnected and starts again.

**Screenshots**

**Your Environment**

* Version used: 1.8.11
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): kubernetes-1.22.4
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Can you reproduce with the latest 1.9 version (1.9.8 at the moment)?
Please provide your exact configuration as well so we can see the set up, along with the logs from Fluent Bit.

**Comment by shashankshukla2** [comment]
Below is the config i have been using.

    [SERVICE]
        flush           5
        grace           3
        log_level       info
        parsers_file    /etc/fluent-bit/parsers.conf
        http_server     on
        http_listen     0.0.0.0
        http_port       2020
        storage.path    /logs/
        storage.sync    normal
        storage.checksum off
        storage.metrics on
        storage.backlog.mem_limit 40M

    [INPUT]
        name              tail
        tag               event.file0
        alias             file0
        buffer_chunk_size 32k
        buffer_max_size   32k
        read_from_head    true
        refresh_interval  60
        rotate_wait       10
        skip_empty_lines  off
        skip_long_lines   off
        key               message
        db                /logs/file0.db
        db.sync           normal
        db.locking        true
       db.journal_mode   off
       path              /logs/gen0.log
       path_key          filename
       exclude_path      /logs/logshipper.log
       parser            json
  
    [OUTPUT]
        name   file
        match  *
        path   /logs
        file   fluentbit.output
    [OUTPUT]
        name                 http
        match                event.*
        alias                  <>
        json_date_key        false
        storage.total_limit_size  20M
        host                 <>
        port                 9443
        retry_limit        false
        log_response_payload false
        format              json
        tls                     on
        tls.verify           true
        tls.ca_file          <>
        tls.crt_file         <>
        tls.key_file         <>

    [PARSER]
        name   json
        format json
    [MULTILINE_PARSER]
        name multiline-test
        type regex
        flush_timeout 1000
        rule "start_state" "(Dec \d+ \d+\:\d+\:\d+)(.*)" "cont1"
        rule "cont1" "^com.*" "cont1"

**Comment by shashankshukla2** [comment]
Below is the memory dump when there is loss of logs.
Sometimes there is no loss of logs with same configuration and sometimes there is. It's not consistent. 

[2022/09/21 11:48:11] Fluent Bit Dump 

===== Input =====
file0 (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 412.1K (421968 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 8
│  ├─ new           : 0
│  ├─ running       : 8
│  └─ size          : 412.1K (421968 bytes)
│
└─ chunks
   └─ total chunks  : 8
      ├─ up chunks  : 8
      ├─ down chunks: 0
      └─ busy chunks: 8
         ├─ size    : 412.1K (421968 bytes)
         └─ size err: 0

storage_backlog.1 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0


===== Storage Layer =====
total chunks     : 8
├─ mem chunks    : 8
└─ fs chunks     : 0
   ├─ up         : 0
   └─ down       : 0

**Comment by shashankshukla2** [comment]
As i can see from the memory dump that the storage layer has mem chunks which are not cleared and sent forward to the pipeline. This is seen multiple times in my testing. Is this an issue already present in fluentbit? Or any configuration needs to be modified for it?
I found a similar issue where flb chunks are not flushed(https://github.com/fluent/fluent-bit/issues/5217).

**Comment by Sindhu379** [comment]
Loss of Logs still observed even upgraded to 1.9.9

Testcase1 : 
1. Generate logs without initial logstash(Log Transformer) connection and deploying after few minutes.
2. **No logs of logs observed**

Test case 2:
1. Generate logs with initial logstash(Log Transformer) connection.
2. disconnect logstash(Log Transformer) for few minutes and re-scalling/re-deploying it up.
3. **Logs of logs observed.**

**Comment by Sindhu379** [comment]
Below is the metrics monitored when sent 200 logs with initial logstash connection and disconnected for 5 mins and redeployed it.
Loss of Logs are still observed.

bash-4.4$ curl -s http://127.0.0.1:2020/api/v1/metrics | jq
{
  "input": {
    "file0": {
      "records": 200,
      "bytes": 129000,
      "files_opened": 1,
      "files_closed": 0,
      "files_rotated": 0
    }
  },
  "filter": {
    "nest.0": {
      "drop_records": 0,
      "add_records": 0
    },
    "nest.1": {
      "drop_records": 0,
      "add_records": 0
    },
    "nest.2": {
      "drop_records": 0,
      "add_records": 0
    },
    "modify.3": {
      "drop_records": 0,
      "add_records": 0
    },
    "modify.4": {
      "drop_records": 0,
      "add_records": 0
    },
    "nest.5": {
      "drop_records": 0,
      "add_records": 0
    },
    "nest.6": {
      "drop_records": 0,
      "add_records": 0
    },
    "modify.7": {
      "drop_records": 0,
      "add_records": 0
    },
    "modify.8": {
      "drop_records": 0,
      "add_records": 0
    },
    "modify.9": {
      "drop_records": 0,
      "add_records": 0
    },
    "grep.10": {
      "drop_records": 0,
      "add_records": 0
    }
  },
  "output": {
    "log_transformer": {
      "proc_records": 98,
      "proc_bytes": 79282,
      "errors": 0,
      "retries": 34,
      "retries_failed": 34,
      "dropped_records": 102,
      "retried_records": 102
    }
  }
}
