### ISSUE TITLE
Please implement basic auth on forward

### ISSUE THREAD

**Issue by fouts-bnet** [fluent/fluent-bit#596]
Please implement basic auth on fluent-bit, fluentd has the capability but fluent-bit does not.
Currently we use basic auth (username/password) + certificates for authentication.

**Comment by edsiper** [comment]
thanks for raising this request. It will be implemented shortly.

**Comment by DStorck** [comment]
@edsiper did this ever get resolved? I am hoping to implement this on the fluent-bit side as well

**Comment by edsiper** [comment]
cc: @fujimotos ^

**Comment by chs-bnet** [comment]
This is still really important to us and would be nice to have.

**Comment by fujimotos** [comment]
I began working on secure forward/authentication support this week.

I'm aware that a number of features are available on Fluentd but missing
from Fluent Bit's `in_forward`. For instance:

1. SSL/TLS support
2. Client cert authentication support
3. Password authentication support
4. ...

This is quite a lot of works so will take a while to materialize. Just wait for me.

**Comment by edsiper** [comment]
@fujimotos this requirement is only for out_forward

**Comment by edsiper** [comment]
already implemented.
