### ISSUE TITLE
Update Minimum Version of CMake to 3.9+

### ISSUE THREAD

**Issue by Garfield96** [fluent/fluent-bit#5987]
**Is your feature request related to a problem? Please describe.**
Fluent-Bit currently requires at least CMake version 3.0 (released in 2014). While having such low requirements enables building Fluent-Bit on many different machines, it makes the adoption of new build related features more difficult. A good example is LTO. In CMake version 3.9+, LTO can be enabled in a single line by setting [`CMAKE_INTERPROCEDURAL_OPTIMIZATION`](https://cmake.org/cmake/help/latest/variable/CMAKE_INTERPROCEDURAL_OPTIMIZATION.html) to `true`. In earlier versions, one would need to provide different configurations for different compilers, which is more complex and error-prone.

**Describe the solution you'd like**
Increase the minimum CMake version to at least 3.9 (released in 2017). Afterwards, LTO can be introduced for release builds (issue for LTO: https://github.com/fluent/fluent-bit/issues/4304). Besides LTO, other new features of the new version should be evaluated whether they are suitable for Fluent-Bit.

**Comment by edsiper** [comment]
For now, we aim to be able to provide binaries for very old distributions, and upgrading CMake versions has always been a challenge. 

I don't think we can update CMake without breaking all the new CI systems and packages builder. If you can point out CMake packages for Centos 7 and Ubuntu 16.04 maybe we can give it a try.

adding @patrick-stephens for visibility

**Comment by Garfield96** [comment]
Kitware offers an own repo with up-to-date packages back to Ubuntu 16.04: https://apt.kitware.com/
I'm not sure about Centos 7. Looking at the build logs it looks like it already uses CMake 3.17:
```
2022-09-05T03:11:44.0635690Z #7 160.4 ---> Package cmake3.x86_64 0:3.17.5-1.el7 will be installed
```
Alternatively, we could install CMake using pip (https://pypi.org/project/cmake/).

Please let me know, which option you prefer and I'll create a PR. It would be great, if this change could be included in Fluent-Bit 2.0.

**Comment by patrick-stephens** [comment]
Technically you can pull a complete cmake binary as it is statically compiled but the challenge is always the other dependencies it requires - e.g. for CentOS 6 builds I do this but then we also have to compile things like autotools and m4 from source.

From my perspective we already have packaging tests to verify PRs can be built on the other targets so I am happy to include a PR if these pass: https://github.com/fluent/fluent-bit/blob/master/packaging/local-build-all.sh
This will ensure we can build the legacy targets and should cover any cmake issues.

**Comment by Garfield96** [comment]
Ok, thanks. I'll open a PR soon (today or tomorrow).

**Comment by patrick-stephens** [comment]
I think there are actually some implicit dependencies on CMake 3.12 somewhere - I vaguely recall some particular constructs that are only available with this version.

Be aware I'm looking at a separate packaging failure with a couple of targets as covered here: https://github.com/fluent/fluent-bit/issues/6007
So if you see those failures then it's not your fault @Garfield96 !

**Comment by patrick-stephens** [comment]
Coming back to this just for info, the Raspbian Buster builds have to pin cmake to 3.13.
