### ISSUE TITLE
upgrade dependencies: Fluent Bit 2.0

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#5992]
More news about Fluent Bit v2.0 here: https://github.com/fluent/fluent-bit/discussions/5993

This issue is to track the dependencies needed for Fluent Bit v2.0 (pls do not submit any PR):

- [x] Jemalloc v5.3.0 (#5999)
- [ ] LuaJIT (latest github commits)
- [x] SQLite v3.39.3 (#6005)
- [x] c-ares (we are in the latest version: v1.18.1)
- [x] MbedTLS - RIP (#5874)
- [ ] Chunk I/O
  - [x] upgrade to v1.3.0 (#6027)
- [ ] Monkey
- [x] Onigmo / Migrate to new maintained & patched Onigmo:
    - [x]  https://github.com/fluent/fluent-bit/issues/6090
    - [x] PR: https://github.com/fluent/fluent-bit/pull/6097
- [x] xxHash (this should be consumed from CFL wrapper, we no longer need a bundled copy) (#6041)
- [x] librdkafka (#6148)
- [x] libbacktrace (#6148)
- [x] mpack (#6148)
- [x] miniz (#6148)
- [x] snappy (#6148)
- [x] ~~lwrb~~ -> it won't be updated since newer versions requires stdatomic.h which generate issues in Windows builds
- [ ] wasm-micro-runtime
- [ ] flb_libco
- [x] avro (#6148)
- [x] jansson (#6148)
- [x] CMetrics: [Calyptia](https://calyptia.com) contribute [calyptia/cmetrics](https://github.com/calyptia/cmetrics) as [fluent/cmetrics](https://github.com/fluent/cmetrics)
- [x] CTraces: [Calyptia](https://calyptia.com) contribute [calyptia/ctraces](https://github.com/calyptia/ctraces) as [fluent/ctraces](https://github.com/fluent/ctraces)
- [x] Bundle new C Floppy library (https://github.com/fluent/cfl) (#6041)
  - [x] CFL v0.1.7 https://github.com/fluent/fluent-bit/pull/6106

**Comment by Garfield96** [comment]
@edsiper Could you please have a look at issue #5713, which would make updating of a few dependencies much easier. Thanks.

**Comment by patrick-stephens** [comment]
@edsiper for CFL we need to resolve https://github.com/fluent/cfl/issues/17 as well
