### ISSUE TITLE
Windows EXE download links are misleading

### ISSUE THREAD

**Issue by erSitzt** [fluent/fluent-bit#6015]
In the docs section for installing the windows exe (https://docs.fluentbit.io/manual/installation/windows#installing-from-exe-installer)  there is a link to the "download page" ( https://fluentbit.io/download/ ) which redirects back to https://docs.fluentbit.io/manual/installation/windows#installing-from-exe-installer

Instead it should scroll to the anchor https://docs.fluentbit.io/manual/installation/windows#installation-packages

**Comment by patrick-stephens** [comment]
Please submit a PR on the docs repo: https://github.com/fluent/fluent-bit-docs
