### ISSUE TITLE
out_opentelemetry docs state it exports logs but this is not implemented

### ISSUE THREAD

**Issue by arminru** [fluent/fluent-bit#6018]
## Bug Report

https://docs.fluentbit.io/manual/pipeline/outputs/opentelemetry states that the OTLP exporter (`out_opentelemetry`) exports logs but this is not implemented yet. So far it only exports metrics and the documented config property `logs_uri` does not exist in the plugin.

It would be great if you could update the docs to not be misleading in that regard until the OTLP exporter is extended to actually support logs. I think this will be implemented with #5559 but don't know if #5747 is the only missing piece for OTLP logs support in fluentbit.

**Comment by lecaros** [comment]
Hi @arminru, thanks for reporting this. The feature will be available in 2.0, not in 1.x.
We've fixed the documentation with this pr https://github.com/fluent/fluent-bit-docs/pull/891

**Comment by arminru** [comment]
Hey @lecaros! Thank you for clearing it up in the docs.

Note that #5747 is blocked on "docs-required" although @Syn3rman already provided them in https://github.com/fluent/fluent-bit-docs/pull/852.
If the implementation PR is merged, the now reverted docs could just be added again.

Is there any targeted release date for 2.0 already?
Would be nice to see OTel/OTLP logs support in fluentbit 🙂

**Comment by lecaros** [comment]
Hi @arminru
the issue is not blocked due to docs-required. It's just we didn't remove that tag once the docs PR was added (it's fixed now).
IRT 2.0, please see https://github.com/fluent/fluent-bit/discussions/5993
