### ISSUE TITLE
fluent-bit not able to parse envoy metrics

### ISSUE THREAD

**Issue by marcelb98** [fluent/fluent-bit#6021]
## Bug Report

**Describe the bug**
fluent-bit is not able to parse the prometheus export of Envoy. It logs a not really verbose error.

Prometheus data produced by envoy: [envoy.txt](https://github.com/fluent/fluent-bit/files/9498397/envoy.txt)

**To Reproduce**
- install Envoy
- add prometheus_scrape input in fluent-bit config
```
[input:prometheus_scrape:prometheus_scrape.1] error decoding Prometheus Text format
```

**Expected behavior**
Metrics getting processed by fluent-bit

**Your Environment**

* Version used: 1.9.8
* Operating System and version: Ubuntu 22.04

**Comment by tarruda** [comment]
Fixed in https://github.com/calyptia/cmetrics/pull/144
