### ISSUE TITLE
Is it possible to configure fluent-bit to get data from multiple inputs ?

### ISSUE THREAD

**Issue by vbmade2000** [fluent/fluent-bit#603]
I want to get data from file as well as syslog.

 Is it possible to configure fluent-bit to get data from multiple inputs ?

**Comment by michiel** [comment]
Yes, it is possible to get data from multiple inputs.

You probably want to use one of the community channels (Slack or Google Groups) if you're looking for assistance. See [https://fluentbit.io/community/](https://fluentbit.io/community/)

**Comment by vbmade2000** [comment]
@michiel Thanks. I tried Slack but didn't get any response for long time. vl try Google group next time.
