### ISSUE TITLE
Output plugins file to specify a directory in the path

### ISSUE THREAD

**Issue by krafts** [fluent/fluent-bit#604]
Hi, 

Currently the output file plugin does not take a path which is a directory. By default it just outputs to the `/` in the filesystem, if a dir is provided, for example:
```
  output-file.conf: |
    [INPUT]
        Name cpu
        Tag  cpu
    [OUTPUT]
        Name            file
        Match           *
        Path            /logs
```

it complains:
```
[2018/05/29 17:13:50] [error] [plugins/out_file/file.c:200 errno=21] Is a directory
[2018/05/29 17:13:50] [error] [plugins/out_file/file.c:200 errno=21] Is a directory
[2018/05/29 17:13:51] [error] [plugins/out_file/file.c:200 errno=21] Is a directory
[2018/05/29 17:13:51] [error] [plugins/out_file/file.c:200 errno=21] Is a directory
```

And there is no variable present to specify the filename with the a tag, the following:
```
  output-file.conf: |
    [INPUT]
        Name cpu
        Tag  cpu
    [OUTPUT]
        Name            file
        Match           *
        Path            /logs/logs_${tag}_____${tag[0]}.log
```

produces, file with underscores, (this is understable as tag is not a documented var, i based this off fluentd docs (https://www.fluentd.org/blog/fluentd-v0.14.0-has-been-released), hoping it was coding in and would works. )

```
-rw-r--r--  1 root root    57821280 May 29 17:10 logs______.log
```

Docs that I referenced:
https://fluentbit.io/documentation/0.13/output/file.html

Anyway around this where I can create tags with the file name as the tag name in a specific directory?  (such as `/logs`)

Thanks!

**Comment by edsiper** [comment]
Ref: similar to #421

**Comment by chenjpu** [comment]
+1

**Comment by edward2a** [comment]
Hey guys, I'm backing up container logs with file output (as a secondary output) and the lack of a configurable dynamic path is a big limitation.
Also the config specifies that by not setting the path, the tag is used as the filename, however I was unable to find the file in the whole system, so I assume it was not created.

**Comment by Sherler** [comment]
+1 also has the requirments

**Comment by chilinhnet** [comment]
+1

**Comment by elvarb** [comment]
I have a tiny use case where a lightweight log tool is needed to read a log from an application that only writes to a single log file, read that log and write to a different log file on the same machine. One file per day, where the date value is parsed from the log itself.

**Comment by jmorcar** [comment]
Is there any update about this?

**Comment by anandr781** [comment]
+1. Need this functionality badly

**Comment by raine** [comment]
I think this is implemented since v1.4.6.

See Path argument in https://docs.fluentbit.io/manual/pipeline/outputs/file

**Comment by hhsel** [comment]
Using the Path parameter and omitting the File parameter, now you can output to files dynamically based on the tag associated with the records, though the base directory is fixed, and file name will always be the tag itself, which is "tag1.tag2.,....".

To deal with this, though a little hacky, you can use the ``rewrite_tag`` filter plugin to modify the file name to what you want, based on tags and other entries on the record.

For example,

```
[FILTER]
    Name   rewrite_tag
    Match _Regex ^(?!/log).+$
    Rule   $myfield ^(.*)$ /log/$TAG[1]_$TAG[2]_$0 false

[OUTPUT]
    Name        file
    Format      template
    Template    {message}
    Match       /log*
```

will output logs to /log directory, with the filename based on the first two tags, with an arbitrary field added to the end of the filename (in this case myfield).

This is possible because fluent-bit tags can contain ``/`` and if the File and Path fields are omitted in the file output plugin, the full path will be the entire tag itself.


The problem here is, however, the base output directory is still fixed.  
Of course you can modify ``Rule`` section to output to any subdirectories you want.

```
Rule   $myfield ^(.*)$ /log/$TAG[1]/$TAG[2]/$0.out false
```

But fluent-bit tries to open that full path with ``fopen``, which means that the directory must exist before you try to write logs, otherwise you got "No such file or directory" error and the records will be discarded.  

In this case you can modify ``out_file/file.c`` to create directory if "No such file directory" error is returned inside the block below:
https://github.com/fluent/fluent-bit/blob/master/plugins/out_file/file.c#L350

After that, I successfully route logs to any directory with any filename I want, based on tags.

**Comment by roboslone** [comment]
+1

**Comment by cobb-tx** [comment]
> Using the Path parameter and omitting the File parameter, now you can output to files dynamically based on the tag associated with the records, though the base directory is fixed, and file name will always be the tag itself, which is "tag1.tag2.,....".
> 
> To deal with this, though a little hacky, you can use the `rewrite_tag` filter plugin to modify the file name to what you want, based on tags and other entries on the record.
> 
> For example,
> 
> ```
> [FILTER]
>     Name   rewrite_tag
>     Match _Regex ^(?!/log).+$
>     Rule   $myfield ^(.*)$ /log/$TAG[1]_$TAG[2]_$0 false
> 
> [OUTPUT]
>     Name        file
>     Format      template
>     Template    {message}
>     Match       /log*
> ```
> 
> will output logs to /log directory, with the filename based on the first two tags, with an arbitrary field added to the end of the filename (in this case myfield).
> 
> This is possible because fluent-bit tags can contain `/` and if the File and Path fields are omitted in the file output plugin, the full path will be the entire tag itself.
> 
> The problem here is, however, the base output directory is still fixed.
> Of course you can modify `Rule` section to output to any subdirectories you want.
> 
> ```
> Rule   $myfield ^(.*)$ /log/$TAG[1]/$TAG[2]/$0.out false
> ```
> 
> But fluent-bit tries to open that full path with `fopen`, which means that the directory must exist before you try to write logs, otherwise you got "No such file or directory" error and the records will be discarded.
> 
> In this case you can modify `out_file/file.c` to create directory if "No such file directory" error is returned inside the block below:
> https://github.com/fluent/fluent-bit/blob/master/plugins/out_file/file.c#L350
> 
> After that, I successfully route logs to any directory with any filename I want, based on tags.

——————————————————————————————————————————
I modified the related code but included another error
https://github.com/fluent/fluent-bit/blob/master/plugins/out_file/file.c#L329：
    char *argv = "mkdir -p  ";
    char *eval_string = (char *) malloc(strlen(argv) + strlen(ctx->out_path));
    system(eval_string);

the new error：
[2021/01/30 16:48:22] [ info] [engine] started (pid=9)
[2021/01/30 16:48:22] [ info] [storage] version=1.0.6, initializing...
[2021/01/30 16:48:22] [ info] [storage] in-memory
[2021/01/30 16:48:22] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/01/30 16:48:22] [ info] [sp] stream processor started
[2021/01/30 16:48:23] [engine] caught signal (SIGSEGV)
#0  0x7ff128319181      in  ???() at ???:0
#1  0x55fa12c39425      in  ???() at ???:0
#2  0x55fa12bd6f14      in  ???() at ???:0
#3  0x55fa1302ac86      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#4  0xffffffffffffffff  in  ???() at ???:0
Aborted (core dumped)


How did you solve the problem？

**Comment by cobb-tx** [comment]
I solved the problem

**Comment by hypnoce** [comment]
While it's possible to create a `gofile` output plugin, it would be nice if this plugin could handle dynamic directory creation.

**Comment by edsiper** [comment]
this is solved with `path` config property: https://docs.fluentbit.io/manual/pipeline/outputs/file#configuration-parameters

**Comment by Shekhar0989** [comment]
> this is solved with `path` config property: https://docs.fluentbit.io/manual/pipeline/outputs/file#configuration-parameters

Could you explain how it is solved using path config property as I tried using $TAG and as well as {record_key} while defining path in file output plugin, but Its not evaluating to actual value rather treating it as a String. 

I tried below approaches without success.

```
[OUTPUT]
    Name file
    Match test.*
    Path /test/logs/$TAG/
    File test.log
    Mkdir true
    Format plain
```

```
[OUTPUT]
    Name file
    Match test.*
    Path /test/logs/{transactionId}/
    File test.log
    Mkdir true
    Format plain
```

**Comment by sudo-hmmanshu** [comment]
> Using the Path parameter and omitting the File parameter, now you can output to files dynamically based on the tag associated with the records, though the base directory is fixed, and file name will always be the tag itself, which is "tag1.tag2.,....".
> 
> To deal with this, though a little hacky, you can use the `rewrite_tag` filter plugin to modify the file name to what you want, based on tags and other entries on the record.
> 
> For example,
> 
> ```
> [FILTER]
>     Name   rewrite_tag
>     Match _Regex ^(?!/log).+$
>     Rule   $myfield ^(.*)$ /log/$TAG[1]_$TAG[2]_$0 false
> 
> [OUTPUT]
>     Name        file
>     Format      template
>     Template    {message}
>     Match       /log*
> ```
> 
> will output logs to /log directory, with the filename based on the first two tags, with an arbitrary field added to the end of the filename (in this case myfield).
> 
> This is possible because fluent-bit tags can contain `/` and if the File and Path fields are omitted in the file output plugin, the full path will be the entire tag itself.
> 
> The problem here is, however, the base output directory is still fixed. Of course you can modify `Rule` section to output to any subdirectories you want.
> 
> ```
> Rule   $myfield ^(.*)$ /log/$TAG[1]/$TAG[2]/$0.out false
> ```
> 
> But fluent-bit tries to open that full path with `fopen`, which means that the directory must exist before you try to write logs, otherwise you got "No such file or directory" error and the records will be discarded.
> 
> In this case you can modify `out_file/file.c` to create directory if "No such file directory" error is returned inside the block below: https://github.com/fluent/fluent-bit/blob/master/plugins/out_file/file.c#L350
> 
> After that, I successfully route logs to any directory with any filename I want, based on tags.

Will this work now if we set the newly added Mkdir parameter to true? Has anyone tried this?
