### ISSUE TITLE
FluentBit move fractional seconds

### ISSUE THREAD

**Issue by LHozzan** [fluent/fluent-bit#6073]
Hello.

I am not sure, that this is bug or feature or problem somewhere else, but I discovered, that FluentBit moving with timestamp, see this examples:

**Example #1:**
_Raw record (exact line from log file):_
`2022-09-07T11:52:55.505530838Z stdout F [2022-09-07 11:52:55] Working on ADDED configmap monitoring/prometheus-stack-kube-prom-grafana-overview`

_FluentBit processing (processed line on FluentBit output, CSV format):_
```
1662551575.505530834,
"[2022-09-07 11:52:55] Working on ADDED configmap monitoring/prometheus-stack-kube-prom-grafana-overview",
"stdout","F",
{"labels"=>
  {"pod-template-hash"=>"69f7c847f7",
   "app_kubernetes_io/name"=>"grafana",
   "app_kubernetes_io/instance"=>"prometheus-stack"},
   "namespace_name"=>"monitoring",
   "pod_id"=>"3947599e-6663-4619-aa25-3c779c39edae",
   "container_name"=>"grafana-sc-dashboard",
   "host"=>"ip-XX-XX-XX-XX.eu-central-1.compute.internal",
   "container_hash"=>...common.cdn.repositories..../kiwigrid/k8s-sidecar@sha256:1f025ae37b7b20d63bffd179e5e6f972039dd53d9646388c0a8c456229c7bbcb,
   "docker_id"=>"c1f7296f593eeff90a87d19c555490a285cca4cfd0c69dd060d789b229d3b7cd",
   "container_image"=>"...common.cdn.repositories..../kiwigrid/k8s-sidecar:1.15.6",
   "pod_name"=>"prometheus-stack-grafana-69f7c847f7-rk2bc"},
"2022-09-07T11:52:55.505530838Z"
```

**Jump is 4 fractional seconds in the future.**

**Example #2:**
_Raw record:_
`2022-09-07T11:52:55.505561119Z stdout F [2022-09-07 11:52:55] Found 'data' on configmap`

_FluentBit processing:_
```
1662551575.505561113,
"[2022-09-07 11:52:55] Found 'data' on configmap",
"stdout","F",
{"labels"=>
  {"pod-template-hash"=>"69f7c847f7",
   "app_kubernetes_io/name"=>"grafana",
   "app_kubernetes_io/instance"=>"prometheus-stack"},
   "namespace_name"=>"monitoring",
   "pod_id"=>"3947599e-6663-4619-aa25-3c779c39edae",
   "container_name"=>"grafana-sc-dashboard",
   "host"=>"ip-XX-XX-XX-XX.eu-central-1.compute.internal",
   "container_hash"=>...common.cdn.repositories..../kiwigrid/k8s-sidecar@sha256:1f025ae37b7b20d63bffd179e5e6f972039dd53d9646388c0a8c456229c7bbcb,
   "docker_id"=>"c1f7296f593eeff90a87d19c555490a285cca4cfd0c69dd060d789b229d3b7cd",
   "container_image"=>"...common.cdn.repositories..../kiwigrid/k8s-sidecar:1.15.6",
   "pod_name"=>"prometheus-stack-grafana-69f7c847f7-rk2bc"},
"2022-09-07T11:52:55.505561119Z"
```

**Jump is 6 fractional seconds in the future.**

**Example #3:**
_Raw record:_
`2022-09-07T11:52:55.505566066Z stdout F [2022-09-07 11:52:55] Writing grafana-overview.json`

_FluentBit processing:_
```
1662551575.505566120,
"[2022-09-07 11:52:55] Writing grafana-overview.json",
"stdout","F",
{"labels"=>
  {"pod-template-hash"=>"69f7c847f7",
   "app_kubernetes_io/name"=>"grafana",
   "app_kubernetes_io/instance"=>"prometheus-stack"},
   "namespace_name"=>"monitoring",
   "pod_id"=>"3947599e-6663-4619-aa25-3c779c39edae",
   "container_name"=>"grafana-sc-dashboard",
   "host"=>"ip-XX-XX-XX-XX.eu-central-1.compute.internal",
   "container_hash"=>...common.cdn.repositories..../kiwigrid/k8s-sidecar@sha256:1f025ae37b7b20d63bffd179e5e6f972039dd53d9646388c0a8c456229c7bbcb,
   "docker_id"=>"c1f7296f593eeff90a87d19c555490a285cca4cfd0c69dd060d789b229d3b7cd",
   "container_image"=>"...common.cdn.repositories..../kiwigrid/k8s-sidecar:1.15.6",
   "pod_name"=>"prometheus-stack-grafana-69f7c847f7-rk2bc"},
"2022-09-07T11:52:55.505566066Z"
```

**Jump is 54 fractional seconds in the past.**

**Expected behavior**
FluentBit will not change timestamp fractional seconds.

**Your Environment**

* Version used: 1.9.5 / 1.9.7
* Configuration: docker image `fluent/fluent-bit` on containerd
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.24.3
* Server type and version: AWS c5.xlarge (CPU: 4, Memory: 8GB)
* Operating System and version: `gardenlinux v: 576.11.0` (Debian 11 derivate)
* Filters:
  - lua
  - kubernetes
* Plugins:
  - systemd
  - tail
  - opensearch

**Additional context**

When you have few log records per seconds, this probably not hit you, but when you have million and above log records from exact pods, output is unusable, you need fractional seconds scale. In this scenario records are mixed over time due to moved fractional seconds from (for me) unknown reason.

I wrote small script to generate marked lines and from output it seems, that ordering isnt correct:
![Missordering](https://user-images.githubusercontent.com/24796361/191255135-6cdfbec0-2799-425f-916c-21e2252f59b4.png)

Have we something set wrong on our side? If yes, can you please pointing me to the right direction? Is this really bug?

Thank you!

**Comment by patrick-stephens** [comment]
Are you parsing the timestamp from the raw record? If not it will be using the local time.

**Comment by patrick-stephens** [comment]
What's your parser config? 
What field is it using for the timestamp and is it parsing the fractional seconds?

**Comment by LHozzan** [comment]
Hi @patrick-stephens .

I am not sure, that I understand you, so, maybe I am wrong.

Parser config:
```
[PARSER]
    Name        kube-tag
    Format      regex
    Regex       ^(?<pod_id>[^_/]+)\.(?<namespace_name>[^_/]+)\.(?<pod_name>[^_/]+)\.(?<container_name>[^/]+)$
    Time_Format %Y-%m-%dT%H:%M:%S.%L%Z
```

We using `@timestamp` field.

Here is processed record from OpenSearch from my test cluster (FluentBit in this scenario feeding directly OpenSearch, no another component on the way):
![EgRecordFromOpenSearch](https://user-images.githubusercontent.com/24796361/191706310-d7e64e39-431e-440f-9389-11bc90c554a0.png)

If you need any additional information, please, let me know. My goal is understand, why this "jumps" occurring OR fix the problem.

**Comment by nokute78** [comment]
@LHozzan 
- Could you share your config file and lua script to clarify the pipeline ?
- How did you get CSV output ? using out_file plugin ?

**Comment by nokute78** [comment]
@LHozzan  Thank you for information I can reproduce it.
Could you use code = 2 at lua script ?
https://docs.fluentbit.io/manual/pipeline/filters/lua#return-values
```
 If code equals 2, means the original timestamp is not modified and the record has been modified
```

I think data conversion lua <-> C causes this issue.

I tested following config.

a.conf:
```
[SERVICE]
    parsers_file parsers.conf

[INPUT]
    Name tail
    Path a.log
    Read_From_Head on
    multiline.parser cri

[FILTER]
    Name lua
    Match *
    script a.lua
    call a

[OUTPUT]
    Name stdout
    Match *
```

a.lua:
```lua
function a(tag, timestamp, record)
    return 1, timestamp, record
end
```

a.log:
```
2022-09-07T11:52:55.505530838Z stdout F [2022-09-07 11:52:55] Working on ADDED configmap monitoring/prometheus-stack-kube-prom-grafana-overview
```



Output is 
```
[0] tail.0: [1662551575.505530834, {"_p"=>"F", "time"=>"2022-09-07T11:52:55.505530838Z", "log"=>"[2022-09-07 11:52:55] Working on ADDED configmap monitoring/prometheus-stack-kube-prom-grafana-overview", "stream"=>"stdout"}]
```

```
$ ../../bin/fluent-bit -c a.conf 
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/05 20:47:09] [ info] [fluent bit] version=2.0.0, commit=8a4ded6f66, pid=16631
[2022/10/05 20:47:09] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/10/05 20:47:09] [ info] [cmetrics] version=0.4.0
[2022/10/05 20:47:09] [ info] [input:tail:tail.0] initializing
[2022/10/05 20:47:09] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2022/10/05 20:47:09] [ info] [input:tail:tail.0] multiline core started
[2022/10/05 20:47:09] [ info] [sp] stream processor started
[2022/10/05 20:47:09] [ info] [input:tail:tail.0] inotify_fs_add(): inode=4730770 watch_fd=1 name=a.log
[2022/10/05 20:47:09] [ info] [output:stdout:stdout.1] worker #0 started
[2022/10/05 20:47:09] [ info] [output:file:file.0] worker #0 started
[0] tail.0: [1662551575.505530834, {"_p"=>"F", "time"=>"2022-09-07T11:52:55.505530838Z", "log"=>"[2022-09-07 11:52:55] Working on ADDED configmap monitoring/prometheus-stack-kube-prom-grafana-overview", "stream"=>"stdout"}]
```

**Comment by LHozzan** [comment]
Hi @nokute78 .

Thank you for your effort I really appreciate it.

Just for clarify: Mean you this file

`dedot.lua`
```
function dedot(tag, timestamp, record)
  if record["kubernetes"] == nil then
    return 0, 0, 0
  end
  dedot_keys(record["kubernetes"]["annotations"])
  dedot_keys(record["kubernetes"]["labels"])
  return 1, timestamp, record
end

function dedot_keys(map)
    if map == nil then
        return
    end
    local new_map = {}
    local changed_keys = {}
    for k, v in pairs(map) do
        local dedotted = string.gsub(k, "%.", "_")
        if dedotted ~= k then
            new_map[dedotted] = v
            changed_keys[k] = true
        end
    end
    for k in pairs(changed_keys) do
        map[k] = nil
    end
    for k, v in pairs(new_map) do
        map[k] = v
    end
end
```
change to this state:
```
function dedot(tag, timestamp, record)
  if record["kubernetes"] == nil then
    return 0, 0, 0
  end
  dedot_keys(record["kubernetes"]["annotations"])
  dedot_keys(record["kubernetes"]["labels"])
  return 2, timestamp, record --[[ previous 1, now 2]]
end

function dedot_keys(map)
    if map == nil then
        return
    end
    local new_map = {}
    local changed_keys = {}
    for k, v in pairs(map) do
        local dedotted = string.gsub(k, "%.", "_")
        if dedotted ~= k then
            new_map[dedotted] = v
            changed_keys[k] = true
        end
    end
    for k in pairs(changed_keys) do
        map[k] = nil
    end
    for k, v in pairs(new_map) do
        map[k] = v
    end
end
```
?

Many thanks!

**Comment by nokute78** [comment]
@LHozzan Thank you for testing. I'm glad to hear that.

> Is this problem in our script and we dont understand documentation or is this bug in FluentBit and can occur anytime in future, when somebody attempt to use Lua script to modify his workflow and timestamps?

Current Lua API can cause rounding error and it cause this issue.
I think it needs to change API, but it will cause breaking change.

Lua supports Number type and it is double-precision floating-point type.
https://www.lua.org/pil/2.3.html

Fluent-bit supports `flb_time` and it is a wrapper of `timespec`. It represents a timestamp using integer types.
```
struct timespec {
    time_t   tv_sec;        /* seconds */
    long     tv_nsec;       /* nanoseconds */
};
```

Floating-point types can cause rounding error.
Following code can reproduce issue.
```c
#include <stdio.h>

int main() {
  int a = 1662551575;
  int b = 505530838;
  double val = (double)a + ((double)b/(double)1000000000);

  printf("val=%.9lf\n", val);

  return 0;
}
```

The same result in golang.
https://go.dev/play/p/dV7o70r3ZRP

**Comment by LHozzan** [comment]
Thank you very much for explanation! I really appreciate it!

This solution is actually working for us and not bring any overheat or any limitation. Please, consider my problem as a solved.

> Current Lua API can cause rounding error and it cause this issue.
> I think it needs to change API, but it will cause breaking change.

If you wish, you can close this issue, or let it opened for somebody, who will have similar problems :).

I hope, that this problem will disappear over time ...
