### ISSUE TITLE
out_http: Setting the value of `Json_Date_Format` property to `iso8601` has no effect.

### ISSUE THREAD

**Issue by vgramer** [fluent/fluent-bit#608]
Hello,

In the `http output` plugin  setting the value of `Json_Date_Format` property to `iso8601` has no effect. The `double` format is allways used.

Configuration:
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    trace 
    Log_File     /fluent-bit/log/fluent-bit.log
    Parsers_File parsers.conf

[INPUT]
    Name          random
    Samples      -1
    Interval_Sec  1
    Interval_NSec 0
    Tag aa

[OUTPUT]
    Name  http 
    Match *
    Host 127.0.0.1 
    Port 8080
    URI /v1/sendlogs
    tls.verify off
    tls off
    Format json_stream
    json_date_format iso8601 

```
**Actual result:**
```
{"date":1527599027.002163, "rand_value":16995394648344596114} 
```

**Expected Result:**
```
{"date":"2018-05-30T09:39:52.000681Z", "rand_value":8547899446852466802}
```
The bug seems to be  [here](https://github.com/fluent/fluent-bit/blob/master/plugins/out_http/http.c#L353)

i made the PR: #607 
Best Regards

**Comment by chlunde** [comment]
Hi @vgramer, I can't reproduce this issue, and I can't see anything in #607 which should change the behavior of fluent-bit.

Here I have a dummy server on localhost:8080 which dumps the POST body.  It looks like json_date_format works as expected:

```
echo '{"1":2}' | ./build/bin/fluent-bit  -i stdin -o http -p host=127.0.0.1 -p port=8080  -p format=json_stream -p  json_date_format=iso8601
2018/06/19 21:52:50  {"date":"2018-06-19T19:52:50.656434Z", "1":2}
```

```
echo '{"1":2}' | ./build/bin/fluent-bit  -i stdin -o http -p host=127.0.0.1 -p port=8080  -p format=json_stream
2018/06/19 21:52:53  {"date":1529437973.700180, "1":2}
```

Anyway, thanks for your report!

Best regards

**Comment by vgramer** [comment]
Hi @chlunde 

sorry for the delay of my response but i find a way to parse the date on http server side. So this bug is not blocking for me. 

I have done the test again with  the last version `0.13.4`. I also have a dummy http server. I use the fluent-bit of the docker image (ie i exec into the container)

If i run your command, i have the expected output:
```
$ echo '{"1":2}' | ./fluent-bit  -i stdin -o http -p host=127.0.0.1 -p port=8080  -p format=json_stream -p  json_date_format=iso8601

{"date":"2018-07-11T11:05:08.923171Z", "1":2} 
```

but i use a config file the date is not formatted with `iso8601`
```
$ ./fluent-bit -c fluent.conf Fluent-Bit v0.13.4

 {"date":1531307184.896396, "log":"{\"1\":2}"} 
```

Here is my ` fluent.conf ` config file:
```
[SERVICE]
   Flush         1
   Log_Level     info
   Daemon        off

[INPUT]
   Name              tail
   Tag               host.audit
   Path              /var/log/test
   DB                /var/log/test.db


[OUTPUT]
   Name  http
   Match *
   Host  127.0.0.1 
   Port  8080
   URI   /
   tls.verify off
   Format json_stream
```

Thanks for your time !

**Comment by edsiper** [comment]
@vgramer looks like you are missing the option _json_date_format_ in your configuration file.

**Comment by vgramer** [comment]
@chlunde , @edsiper 

Your're right. I can not reproduce the bug. My config file should be wrong :/

Sorry for the inconvenience and thanks a lot for your help.
