### ISSUE TITLE
Add support for Workload Identity Federation in Stackdriver output plugin

### ISSUE THREAD

**Issue by DeanBrunt** [fluent/fluent-bit#6083]
**Is your feature request related to a problem? Please describe.**
We're currently deploying new infrastructure in AWS but want to be able to keep our logs backend and dashboard as Stackdriver/Google Cloud Logging.
This is possible with the Stackdriver exporter but requires explicit passing of the long lived private key which is not ideal.

Given that Workload Identity Federation exists between GCP and AWS (and other providers), it would be great to leverage this instead to avoid the need to manage long lived private keys for the cross-cloud authentication.
The Bigquery exporter plugin already supports this.

**Describe the solution you'd like**
Ability to opt into using Workload Identity Federation with the Stackdriver exporter so that I can send logs from AWS to Stackdriver without needing to manage long lived private keys.

**Describe alternatives you've considered**
- Fluent Bit -> Fluentd -> Stackdriver
    - Not possible as the Google Auth Ruby Gem also doesn't support WI federation (notwithstanding [this](https://github.com/googleapis/google-auth-library-ruby/pull/386) PR)
- Passing private keys to fluent bit directly
    - This works fine, but lacks the security benefits of WI federation.
- Fluent Bit -> OpenTelemetry Collector -> Stackdriver
    - This is the option I'll likely go with for now to leverage the power of Fluent Bit's log agent and k8s log processing config that I know works, whilst being able to offload via Otel collector to Stackdriver (Go auth library supports WI federation).

**Comment by gfrankliu** [comment]
There is a workaround by running the gke-addon-sidecar as the metadata server. That sidecar supports the Workload Identity Federation, and re-expose as a metadata server on localhost. In the [stackdriver output config](https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver/), you can then point metadata_server to it. Sidecar image can be found at gcr.io/gke-multi-cloud-release/gke-addon-sidecar

**Comment by DeanBrunt** [comment]
> There is a workaround by running the gke-addon-sidecar as the metadata server. That sidecar supports the Workload Identity Federation, and re-expose as a metadata server on localhost. In the [stackdriver output config](https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver/), you can then point metadata_server to it. Sidecar image can be found at gcr.io/gke-multi-cloud-release/gke-addon-sidecar

Ah interesting, thanks for this, this is potentially a neat workaround.
Do you know if there's some docs for the configuration surface of this sidecar?
I'm struggling to find anything when searching for it.

**Comment by JeffLuoo** [comment]
There is an example of using the sidecar in our another repo: https://github.com/GoogleCloudPlatform/anthos-samples/blob/main/aws-logging-monitoring/logging/forwarder.yaml#L94-L115

If you find this useful and we can add this to the documentation of Fluent Bit.

@DeanBrunt
