### ISSUE TITLE
Build error on FreeBSD

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#61]
I found  this issue when I tested #48.
My environment is FreeBSD 10.2 , ~~gcc 4.8.5.~~ clang 3.4.1.

There are 2 issues.
I want to know how we fix issue1

## 1. unknown type name 'ucontext_t'

This is compatibility issue.

This is caused these codes at lib/monkey/mk_core/mk_thread.c.
(Monkey project has same issue.)

``` c
#if defined (__linux__)
#include <ucontext.h>
#elif defined (__APPLE__)
#include <sys/ucontext.h>
#endif
```
There is no 'else' case.
It is very simple to replace #elif to #else or add FreeBSD define.

## ucontext.h may be obsolete.
On the other hand, I found these articles. 

That header is removed on 'POSIX issue7' .
http://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap13.html

OpenBSD doesn't have ucontext.h 
https://groups.google.com/forum/#!topic/v8-dev/seLPS6grC2A

They recommended to replace these API to POSIX threads.
http://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xsh_chap03.html

```
getcontext(), makecontext(), swapcontext()
Due to portability issues with these functions, especially with the manipulation of contexts, applications are recommended to be rewritten to use POSIX threads.
```

## Build log
``` make
[  3%] Built target msgpack-static
[  4%] Built target jsmn
[  4%] Building C object lib/monkey/mk_core/CMakeFiles/mk_core.dir/mk_thread.c.o
fluent-bit/lib/monkey/mk_core/mk_thread.c:60:5: error: unknown type name 'ucontext_t'
    ucontext_t context;
    ^
fluent-bit/lib/monkey/mk_core/mk_thread.c:72:5: error: unknown type name 'ucontext_t'
    ucontext_t main;
    ^
fluent-bit/lib/monkey/mk_core/mk_thread.c:258:5: warning: implicit declaration of function 'swapcontext' is invalid in C99 [-Wimplicit-function-declaration]
    swapcontext(&dt->context, &sch->main);
    ^
fluent-bit/lib/monkey/mk_core/mk_thread.c:287:9: warning: implicit declaration of function 'getcontext' is invalid in C99 [-Wimplicit-function-declaration]
        getcontext(&dt->context);
        ^
fluent-bit/lib/monkey/mk_core/mk_thread.c:287:9: warning: declaration of built-in function 'getcontext' requires inclusion of the header <ucontext.h> [-Wbuiltin-requires-header]
fluent-bit/lib/monkey/mk_core/mk_thread.c:299:9: warning: implicit declaration of function 'makecontext' is invalid in C99 [-Wimplicit-function-declaration]
        makecontext(&dt->context, (void (*)(void))_mk_thread_entry_point, 1, sch);
        ^
4 warnings and 2 errors generated.
*** Error code 1

Stop.
make[2]: stopped in fluent-bit/build
*** Error code 1

Stop.
make[1]: stopped in fluent-bit/build
*** Error code 1

Stop.
make: stopped in fluent-bit/build
```

**Comment by nokute78** [comment]
## 2. use of undeclared identifier 'IPPROTO_TCP'

This is simple issue.
It is better to include 'netinet/in.h' which has the define 'IPPROTO_TCP'.

## Build log
``` make
[ 58%] Built target cJSON
[ 59%] Building C object src/CMakeFiles/fluent-bit-static.dir/flb_network.c.o
fluent-bit/src/flb_network.c:123:30: error: use of undeclared identifier 'IPPROTO_TCP'
    ret = setsockopt(sockfd, SOL_TCP, TCP_NODELAY, &on, sizeof(on));
                             ^
fluent-bit/src/flb_network.c:40:17: note: expanded from macro 'SOL_TCP'
#define SOL_TCP IPPROTO_TCP
                ^
fluent-bit/src/flb_network.c:151:31: error: use of undeclared identifier 'IPPROTO_TCP'
    return setsockopt(sockfd, SOL_TCP, TCP_FASTOPEN, &qlen, sizeof(qlen));
                              ^
fluent-bit/src/flb_network.c:40:17: note: expanded from macro 'SOL_TCP'
#define SOL_TCP IPPROTO_TCP
                ^
fluent-bit/src/flb_network.c:341:63: error: incomplete definition of type 'struct sockaddr_in'
        if ((inet_ntop(AF_INET, &((struct sockaddr_in *)&addr)->sin_addr,
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
fluent-bit/src/flb_network.c:341:43: note: forward declaration of 'struct sockaddr_in'
        if ((inet_ntop(AF_INET, &((struct sockaddr_in *)&addr)->sin_addr,
                                          ^
fluent-bit/src/flb_network.c:349:65: error: incomplete definition of type 'struct sockaddr_in6'
        if ((inet_ntop(AF_INET6, &((struct sockaddr_in6 *)&addr)->sin6_addr,
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
fluent-bit/src/flb_network.c:349:44: note: forward declaration of 'struct sockaddr_in6'
        if ((inet_ntop(AF_INET6, &((struct sockaddr_in6 *)&addr)->sin6_addr,
                                           ^
4 errors generated.
*** Error code 1

Stop.
make[2]: stopped in fluent-bit/build
*** Error code 1

Stop.
make[1]: stopped in fluent-bit/build
*** Error code 1

Stop.
make: stopped in fluent-bit/build
```

**Comment by edsiper** [comment]
thanks for catching these problems.

ucontext_t is being deprecated from POSIX years ago, but the main problem and suggestion is to use POSIX threads, for performance reasons this is not good, and that's why ucontext is still around.

In a next version of Fluent Bit I plan to replace ucontext by the workaround with sigsetjmp(3).

About the missing header for FreeBSD I found the following:

- FreeBSD: http://www.unix.com/man-page/freebsd/3/ucontext/
- NetBSD: https://www.freebsd.org/cgi/man.cgi?query=ucontext&sektion=3&apropos=0&manpath=FreeBSD+6.1-RELEASE
- OSX: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/ucontext.3.html

so all of them claim that _#include <ucontext.h>_ is the right path, but looks like OSX is wrong. 

Anyways I just pushed a fix for Monkey here: https://github.com/monkey/monkey/commit/62f1aa2f01c0e5b668bd3a1b58ab1db4a1460be7 and merged into Fluent Bit here: 00e5194f88b9600f74a684b2abb49ba66d4da7a8

Second issue for missing _in.h_ fixed here: d4e3943d3c637f04c0082118abfbe583de1bfb76

would you please check if the fixes pushed are working ?

**Comment by nokute78** [comment]
Thank you for your information and updating.

d4e3943d3c637f04c0082118abfbe583de1bfb76 can be built on FreeBSD.
These issues has been fixed. Thanks!

However, Monkey can't be built yet.
I opened new issue. https://github.com/monkey/monkey/issues/235

**Comment by nokute78** [comment]
Note...

> NetBSD: https://www.freebsd.org/cgi/man.cgi?query=ucontext&sektion=3&apropos=0&manpath=FreeBSD+6.1-RELEASE

Well, it's a FreeBSD's.
NetBSD : http://netbsd.gw.com/cgi-bin/man-cgi?ucontext+2.i386

> My environment is FreeBSD 10.2 , gcc 4.8.5.

Sorry , I wrote a wrong information.
I used clang 3.4.1.
