### ISSUE TITLE
chunk: provide an ability to use both memory and filesystem storage.types at the same time

### ISSUE THREAD

**Issue by Dentrax** [fluent/fluent-bit#6113]
**Is your feature request related to a problem? Please describe.**
﻿According to [input chunk documentation](https://docs.fluentbit.io/manual/administration/buffering-and-storage#input-section-configuration) and the [source code](https://github.com/fluent/fluent-bit/blob/f4789db068b755943bb3a0275ae0bbf9c2d7e672/src/flb_input_chunk.c#L1464), `in->storage_type` is mutually exclusive with `memory` and `filesystem`.

People may not want to use the `filesystem` due to `securityContext.readOnlyRootFilesystem` policy enforcement. So they prefer to use `memory`. We may want to use `filesystem` to get more resiliency during incidents or network problems.

Memory is a limited space, which makes it easy to fill. But it's much faster and no I/O required.

The use case here is we don't want any log lost/drop issues. It's about to create eventually consistent architecture. We want _that log_ to be redirected to the _output_, no matter what.

**Describe the solution you'd like**

Add a new option called `both` (or something) to `in->storage_type`. It should use _memory_ to read/create the chunks until memory buffer limit gets exceeded, like as-is. When ring-buffer reached the limit, then it should start to use filesystem as a fallback mechanism. But should not overwrite/clear the memory buffer.

Open Question:
* What if filesystem also reached the limit? By default, if it has less than 1% of it capacity as available space, fd will be [released](https://github.com/fluent/fluent-bit/blob/f4789db068b755943bb3a0275ae0bbf9c2d7e672/src/flb_input_chunk.c#L1680-L1693). (overwrite?)
* In case container/pod restarts, both memory and file systems will be reset. (See the below: remote storage idea)

**Describe alternatives you've considered**
Remote write/read for chunks. i.e. remote storage solutions for better resiliency.

**Additional context**
`-`

**Comment by PettitWesley** [comment]
Read this more carefully: https://docs.fluentbit.io/manual/administration/buffering-and-storage

> When the Filesystem buffering is enabled, the behavior of the engine is different, upon Chunk creation, it stores the content in memory but also it maps a copy on disk (through [mmap(2)](https://man7.org/linux/man-pages/man2/mmap.2.html)), this Chunk is active in memory and backed up in disk is called to be up which means "the chunk content is up in memory".
