### ISSUE TITLE
Multiline parser in filter does not split by matches according the regular expression

### ISSUE THREAD

**Issue by Maksim-ops** [fluent/fluent-bit#6122]
## Bug Report

**Describe the bug**
Multiline parser described in module [MULTILINE_PARSER](https://docs.fluentbit.io/manual/v/2.0-pre/pipeline/filters/multiline-stacktrace) does not split the log into the corresponding fields specified in the regular expression. 

**To Reproduce**
- Rubular link: [Regex](https://rubular.com/r/jKx0g4QYg85wml) 
- Steps to reproduce the problem:
1) fluent-bit.conf
```
[SERVICE]
    flush 1
    log_level info
    parsers_file parsers_multiline.conf

[INPUT]
    name tail
    path test.log
    read_from_head true

[FILTER]
    name multiline
    match *
    multiline.key_content log
# the same behaviour using python and java parser
    multiline.parser go, multiline-regex-test

[OUTPUT]
    name stdout
    match *
```
2) parsers_multiline.conf
```
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    rule      "start_state"   "/^(?<date>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)/"  "cont"
    rule      "cont"             "/^\s+at.*/"  "cont"
```
3) Start fluent-bit
```
/opt/fluent-bit/bin/fluent-bit -c /etc/fluent-bit/fluent-bit.conf -vvv
```
4) Paste string to test.log and save
```
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
```
5) output
```
[0] tail.0: [1664378447.205420472, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!"}]
```

**Expected behavior**
Expected as in this case
1) fluent-bit.conf
```
[SERVICE]
    flush 1
    log_level debug
    parsers_file parsers.conf

[INPUT]
    Name tail
    Path test.log

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser regex-test

[OUTPUT]
    Name stdout
    Match *
```
2) parser.conf
```
[PARSER]
    Name regex-test
    Format regex
    Regex ^(?<date>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)
```
**Note: the regular expression is the same as in the previous version**
3) Start fluent-bit
```
/opt/fluent-bit/bin/fluent-bit -c /etc/fluent-bit/fluent-bit.conf -vvv
```
4) Paste string to test.log and save
```
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
```
5) output
```
[0] tail.0: [1664378106.593967211, {"date"=>"Dec 14 06:41:08", "message"=>" Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!"}]
```
Parser splitted the log to date and message fields by regex

**Your Environment**

* Version used: Fluent Bit v1.9.8
* Configuration: 
[fluent bit] version=1.9.8, commit=, pid=1861447
[storage] version=1.2.0, type=memory-only, sync=normal, checksum=disabled, max_chunks_up=128
[cmetrics] version=0.3.6
* Operating System and version: Ubuntu 20

**Additional context**

I forward logs to newrelic using multiline parser. Multiline logs work perfectly but are not inserted into the corresponding fields specified in the regular expression.

**Screenshots**
The case with multiline parser
![newrelic-multiline_parser](https://user-images.githubusercontent.com/72493054/192962112-086b3fd8-e0f3-4fb9-b05a-6862fd22a047.png)
The expected behaviour as in case with parser
![newrelic-parser-expected](https://user-images.githubusercontent.com/72493054/192962181-c2c51cb0-c3b0-4f02-90f7-8dcd3990795d.png)

**Comment by nokute78** [comment]
multiline filter is to concatenate logs.

How about using `filter_multiline` and `filter_parser` ? 
A pipeline is `in_tail` -> `filter_multiline`(concatenate) -> `filter_parser`(named capture) -> `out_stdout`.


a.conf:
```
[SERVICE]
    flush 1
    log_level info
    parsers_file parsers_multiline.conf
    Parsers_file p.conf

[INPUT]
    name tail
    path test.log
    read_from_head true

[FILTER]
    name multiline
    match *
    multiline.key_content log
# the same behaviour using python and java parser
    multiline.parser go, multiline-regex-test

[FILTER]
    Name parser
    match *
    Key_Name log
    Parser sample

[OUTPUT]
    name stdout
    match *
```

test.log:
```
Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge
New line
```

parsers_multiline.conf:
```
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    rule      "start_state"   "/^(?<date>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)/"  "cont"
    rule      "cont"             "/^\s+at.*/"  "cont"
```

p.conf:
```
[PARSER]
    Name sample
    Format regex
    Regex /^(?<date>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)/m
```

Output will be 
```
[0] tail.0: [1664572997.472881928, {"log"=>"Dec 14 06:41:08 Exception in thread "main" java.lang.RuntimeException: Something has gone wrong, aborting!
  at.hoge
  at.moge"}]
[1] tail.0: [1664572997.472889636, {"log"=>"New line"}]
```

**Comment by Maksim-ops** [comment]
Your pipeline works perfectly. Thank you.
There is slightly non-obvious difference between multiline parsers in Input and Filter (Parser_Firstline&Parser_N or multiline.parser)

**Comment by nokute78** [comment]
Thank you for testing.

> Parser_Firstline&Parser_N

They are old style configuration parameters. 
Could you try `mutline.parser` ? It is a new style.

**Comment by nokute78** [comment]
Hmm fluent-bit seems to fail parse a pattern like `/PATTERN/m`.

Following `/m` is to parse multiline , but it doesn't work using fluent-bit.
```
Regex /^(?<date>Dec \d+ \d+\:\d+\:\d+)(?<message>.*)/m
```

I tested on Rubular and it worked on rubular.
https://rubular.com/r/8KyQSdg5zBvSyH

**Comment by nokute78** [comment]
@BlackJohnny  I sent a patch to support `/pattern/m` .
