### ISSUE TITLE
Fluent-bit TCP bug

### ISSUE THREAD

**Issue by vikasmishra17** [fluent/fluent-bit#6125]
## Bug Report

Fluent-bit is not picking the picking the messages that the server is receiving through tcpdump, Instead of that  Fluent-bit is sending the system syslogs to the server itself. 

My configuration

[INPUT]
    Name        syslog
    mode        tcp
    Listen      0.0.0.0
    Port        514
    tag         syslog.tcp
    Parser      syslog-modified

[FILTER]
    Name           parser
    Match          syslog.*
    Parser         syslog-modified
    Preserve_Key   On
    Reserve_Data   On
    Key_Name       log

[OUTPUT]
    name    stdout
    match   *
& We are not getting any thing in the logs too

**Comment by RicardoAAD** [comment]
Hello @vikasmishra17 

Could you please provide more detailed information to understand what is the issue that you are experiencing with Fluent-Bit? 

Please provide the full Fluent Bit configuration and other information as per the issue template [https://github.com/fluent/fluent-bit/blob/master/.github/ISSUE_TEMPLATE/bug_report.md](https://github.com/fluent/fluent-bit/blob/master/.github/ISSUE_TEMPLATE/bug_report.md.)

Is any output being pushed to the standard output?
is there any error shown after you run Fluent-Bit using this configuration?
Please provide:
-  The full config file.
- The logs from Fluent-Bit running in debug mode.
- A brief description of your use case.
- Details about your environment:
       -Version used
       -Environment name and version (e.g. Kubernetes? What version?):
       -Server type and version:
       -Operating System and version:
       -Filters and plugins
       -custom parser used
Please add as many details as you can so we can fully understand the issue and help you.

Th@nks
