### ISSUE TITLE
Add a configuration option for output plugins to guarantee ordered writes.

### ISSUE THREAD

**Issue by sflanker** [fluent/fluent-bit#6137]
Currently there is a flag for output plugins that limits the engine to only starting one flush task at a time: `FLB_OUTPUT_NO_MULTIPLEX`. This flag is enabled for the Loki output plugin because historically Loki was unable to accept out-of-order writes. However, this behavior does not have very good performance characteristics (see #5868), and Loki now supports out of order writes. I have submitted a PR (#6136) to remove that flag from the Loki plugin, but that will break backward compatibility. In order to support users who wish to upgrade to Fluent Bit 2.x but who are still using Loki < 2.4, a configuration option will be need to support the ordered-write guarantee.

Note: the reason the current behavior has such poor performance is that it "solves" the out-of-order write problem by only doing one task per flush so if multiple tasks are consistently generated between flushes there is no way for the output plugin to keep up even if each flush task actually only takes a fraction of a second. It would be really neat if the solution could merge the pending flush tasks or still process multiple tasks per flush while maintaining the ordered guarantee (i.e. not parallelizing) however I do not know enough about the architecture to say how feasible that is.

**Additional context**

[Loki release notes about allowing unordered writes](https://grafana.com/blog/2021/12/03/new-feature-in-loki-2.4-no-more-ordering-constraint/)
[The Fluent Bit release that added Loki and the `FLB_OUTPUT_NO_MULTIPLEX` flag](https://fluentbit.io/announcements/v1.6.1/index.html)

**Comment by JeffLuoo** [comment]
It worths making this option configurable but we need to make sure to document it in details.
