### ISSUE TITLE
Support Other Azure Clouds

### ISSUE THREAD

**Issue by cfBrianMiller** [fluent/fluent-bit#6138]
**Is your feature request related to a problem? Please describe.**
I am attempting to utilize the Azure Output Plugin in other Azure clouds and discovered the value for the ops insights is hard coded.

**Describe the solution you'd like**
I would like to see this change from a constant to a specified variable.
https://github.com/fluent/fluent-bit/blob/02447c83a59f40fb73cdf0300403e2a67f916d08/plugins/out_azure/azure.h#L24

**Describe alternatives you've considered**
Given this is a hard coded value no alternatives exist past passing this through a proxy

**Comment by PettitWesley** [comment]
@cfBrianMiller The quickest way to fix this is probably to just submit a PR yourself. 

All you need to do probably is to add a config map entry for the host and if its configured override the constant: https://github.com/fluent/fluent-bit/blob/master/DEVELOPER_GUIDE.md#config-maps
