### ISSUE TITLE
Storage type filesystem is not working for Kafka output

### ISSUE THREAD

**Issue by vikasmishra17** [fluent/fluent-bit#6144]
## Bug Report

**Describe the bug**
 The "storage.type filesystem" for output Kafka is not working the fluent-bit. Kafka was down for 15 minutes, and 36KB buffer file was created, once Kafka is up fluentbit is pushing data but the time Kafka was down, the logs were lost for those 15 minutes.

Note - Buffer file is created but it is deleting and creating a new .flb file, when it reach 36k size of file

- Steps to reproduce the problem:

**Expected behavior**
If Kafka cluster is down, logs should be stored in buffer file and once Kafka is working, data should be flushed from buffer file.

**Your Environment**

 Version used: 1.9.8

[SERVICE]
    flush        6
    daemon       Off
    log_level    debug
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  On
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on
    storage.path /etc/td-agent-bit/buffer/
    storage.sync normal
    storage.checksum off
    storage.backlog.mem_limit 5M

[INPUT]
    Name tail
    Path /var/log/syslog
    Tag  syslogs-kafka
    DB  /etc/td-agent-bit/db/syslog-kafka-latest.db
    DB.locking true
    DB.sync full
    Refresh_Interval 10
    Rotate_Wait      5
    storage.type     filesystem
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size   5MB
    Mem_Buf_Limit     100MB

[OUTPUT]
    name  kafka
    match  syslogs-kafka
    brokers XX.XX.XX.XX:9092,XX.XX.XX.XX:9092,XX.XX.XX.XX:9092
    topics  syslogs-test
    Retry_Limit false
    queue_full_retries 2
    rdkafka.request.timeout.ms 0
    rdkafka.linger.ms 500
    rdkafka.log.connection.close true
    rdkafka.message.max.bytes 41943040
    rdkafka.metadata.max.age.ms 5000
    rdkafka.queue.buffering.max.kbytes 100000
    rdkafka.request.required.acks 1
    rdkafka.security.protocol plaintext
    rdkafka.socket.keepalive.enable true

* Environment name and version : Ubuntu 20.04.3 LTS , Codename : focal

**Comment by JeffLuoo** [comment]
Can you attach debug logs generated by Fluent Bit?
