### ISSUE TITLE
OS disk queue depth is increasing if we have more pods in AKS cluster

### ISSUE THREAD

**Issue by prydeep** [fluent/fluent-bit#6146]
Team,

We are using 10 node AKS cluster with Standard_D32as_v4 (32 vcpu, 128 GiB RAM, 64000iops, 1024gb os disk). There are more than 300 pods running on the cluster. 

without fluentbit the os queue depth is < 1, after deploying the it going more than >15 consistently and which is slowing down the AKS cluster, k8s version is 1.22.  Please review my below configuration and let me know if I am not doing correctly. This is affecting our production cluster, please help. Thank you.

[SERVICE]
    Daemon Off
    Flush 1
    Log_Level info
    Parsers_File parsers.conf
    Parsers_File custom_parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 50M
    Health_Check On

[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Exclude_Path  /var/log/containers/*_kube-system_*.log,/var/log/containers/*_ingress-controller_*.log,/var/log/containers/*_kube-node-lease_*.log,/var/log/containers/*_kube-public_*.log,/var/log/containers/*_proxy-installer_*.log
    multiline.parser docker, cri
    Tag kube.*
    DB  /var/log/flb_kube.db
    storage.type filesystem 
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[INPUT]
    Name systemd
    Tag host.*
    Systemd_Filter _SYSTEMD_UNIT=kubelet.service
    Read_From_Tail On

[FILTER]
    Name kubernetes
    Match kube.*
    Merge_Log On
    Keep_Log Off
    K8S-Logging.Parser On
    K8S-Logging.Exclude On

[OUTPUT]
    Name es
    Match *
    Host elk-host
    Port 9200
    HTTP_User username
    HTTP_Passwd pwd
    Logstash_Format On
    Logstash_Prefix fluent-bit
    Retry_Limit False
    Buffer_Size false
    Replace_Dots On
    Suppress_Type_Name On
    Trace_Error On
    tls On
    tls.verify Off

**Comment by edsiper** [comment]
version ?

**Comment by prydeep** [comment]
@edsiper Thank you for responding. fluent-bit:1.9.7 is the version we are using right now.

**Comment by prydeep** [comment]
Hi @edsiper, Can you please review my config and let me know if I have to do anything to decrease the OS disk Queue depth.

**Comment by prydeep** [comment]
Team, Can anyone respond for this please.

**Comment by prydeep** [comment]
@edsiper @endersonmaia @repeatedly Can you please look into this, we are facing the OS queue depth issue from longtime
