### ISSUE TITLE
Nest parser filter keys

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#6158]
**Is your feature request related to a problem? Please describe.**
Given a log structure like so:

```json

{
  "log": {
    "header": {
      "key": "value",
      "nested": "{\"key1\":\"value\",\"key2\":\"value\"}",
      "dateTime": "2019-05-08T20:58:06+00:00"
    },
    "body": {
      "path": "/request/path/",
      "method": "POST",
      "ua": "curl/7.54.0",
      "resp": 200
    }
  }
}
```

I would like to use the `parser` filter to make sure the nested keys are parsed but stay in `log.header.nested` Right now if you use the parser your output will result in

```json

{
  "log": {
    "header": {
      "key": "value",
      "dateTime": "2019-05-08T20:58:06+00:00"
    },
    "body": {
      "path": "/request/path/",
      "method": "POST",
      "ua": "curl/7.54.0",
      "resp": 200
    }
  },
  "key1": "value",
  "key2": "value"
}
```

Where the desired is actually:

```json

{
  "log": {
    "header": {
      "key": "value",
      "nested": {"key1":"value","key2":"value"},
      "dateTime": "2019-05-08T20:58:06+00:00"
    },
    "body": {
      "path": "/request/path/",
      "method": "POST",
      "ua": "curl/7.54.0",
      "resp": 200
    }
  }
}
```

**Describe the solution you'd like**
I would like the parser to accept another property, something like `prefix` (so keys can be prefixed and then use the `nest` filter to nest them properly) or `nest` to directly specify where you want the parsed keys to be placed.

**Describe alternatives you've considered**
As far as I know there is no other alternative if you do not know the resulting keys ahead of time.

**Comment by braunsonm** [comment]
Bump

**Comment by braunsonm** [comment]
Bump

**Comment by jelsdon** [comment]
I've been stuck on this as well whilst using the json parser (is this the same for you?)

I've got a working alternative now and that's instead to use place everything in a regex parser and have it json decoded from there

```
[PARSER]
    Name nested_string_to_json
    Format regex
    Regex ^(?<nested>.*)$
    Decode_Field_As json nested
```

Then from a filter
```
[FILTER]
    name parser
    parser nested_string_to_json
    match *
    Key_Name log.header.nested
    Preserve_key Off
    Reserve_Data On
````
