### ISSUE TITLE
Problem with kerberos auth in out_kafka plugin on Windows.

### ISSUE THREAD

**Issue by Lumiond** [fluent/fluent-bit#6162]
## Bug Report

**Describe the bug**
I have tried to connect to kafka with GSSAPI authentification method from windows host (host in AD), but get this error: "Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown". When I have catched packets through Wireshark I have seen strange sname: only first symbol from config (or first symbol from default value, i.e. letter k). I have also tested example from librdkafka and it works! So I think something wrong with fluentbit.

**To Reproduce**
- Steps to reproduce the problem:
1) Set up Kerberos sasl method on kafka server
2) Set up this settings in fluentbit config for kafka output:
rdkafka.security.protocol SASL_PLAINTEXT
rdkafka.sasl.kerberos.service.name kafka
3) Start fluentbit (run as domain user)

**Expected behavior**
Fluentbit is connected to kafka server without any errors.

**Screenshots**
Some screenshots of packets in wireshark:
sname from fluentbit packet:
![image](https://user-images.githubusercontent.com/51132430/194711385-0cbaf5b7-11cb-4ff3-86e6-dae6234f462e.png)
sname from rdkafka_example.exe: 
![image](https://user-images.githubusercontent.com/51132430/194711508-145a42aa-9151-48ee-8806-8bb0f342314e.png)

**Your Environment**

* Version used: 1.8.11 (also tested on 1.9.7), both version was built from sources
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Windows Server 2019 (build 1809)
* Filters and plugins: input - tail, filter - record_modifier, output - kafka

**Comment by Lumiond** [comment]
A bit new information: librdkafka example works only if it have been built with visual studio. If I build it with cmake - same behaviour like fluentbit. Any workarounds for building?

**Comment by alt-dima** [comment]
@Lumiond hi! probably the same problem as was for me with compression (gzip) support in out_kafka
check my PR
https://github.com/fluent/fluent-bit/pull/6214/files#diff-d75427907b4a97ca122ccabc30454afd418e1a1152c474d3297d1b5c0d701d14R41
We need the same (install SASL library)

**Comment by Lumiond** [comment]
@alt-dima , it's not sasl library problem in my case.
After a little research I found that the problem in librdkafka function:
https://github.com/confluentinc/librdkafka/blob/master/src/rdkafka_sasl_win32.c#L513 - this is the key for correct/incorrect work. When I build project with msvs everything ok, when with cmake - it doesn't work, but if I delete L in L"%hs/%hs" I get warning and working build. So, I think, we need some flags for compilation, but I don't know which.
