### ISSUE TITLE
How to use the tcp input plugin to receive unstructured messages

### ISSUE THREAD

**Issue by 666MrFang** [fluent/fluent-bit#6167]
How to use the tcp input plugin to receive unstructured messages, the tcp input plugin seems to only support receiving data in json format. When the Format optional field is none, no field is provided to provide a parser to parse non-structured messages.

[INPUT]
    Name              tcp
    Listen            0.0.0.0
    Port              5170
    Chunk_Size        32
    Buffer_Size       64
    Format            none

[OUTPUT]
    Name   stdout
    Match  *

Then i echo `{"data":"100 0.5 true This is example"}`，no output.

**Comment by RicardoAAD** [comment]
Hello @666MrFang.
I believe you missed the part where Netcat is used to forward your echo to your server.

I used the same config you are using
```
[INPUT]
   Name tcp
   Listen 0.0.0.0
   Port 5170
   Chunk_Size 32
   Buffer_Size 64
   Format none

[OUTPUT]
   Name stdout
   Match *
```
In another terminal tab, I used the same message that you posted in your example: 

`student@ubuntu:~$ echo {"data":"100 0.5 true This is example"}| nc 127.0.0.1 5170`
In the example that we have in our documentation, you will see that netcat is used to send the message to the Fluent-bit
https://docs.fluentbit.io/manual/pipeline/inputs/tcp#testing

```
student@ubuntu:~/caliptia/fluent-bit/build/bin$ ./fluent-bit -c config-6167.conf
Fluent Bit v2.0.0
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/18 13:14:17] [ info] [fluent bit] version=2.0.0, commit=f092885a4b, pid=887738
[2022/10/18 13:14:17] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/10/18 13:14:17] [ info] [cmetrics] version=0.5.2
[2022/10/18 13:14:17] [ info] [input:tcp:tcp.0] initializing
[2022/10/18 13:14:17] [ info] [input:tcp:tcp.0] storage_strategy='memory' (memory only)
[2022/10/18 13:14:17] [ info] [sp] stream processor started
[2022/10/18 13:14:17] [ info] [output:stdout:stdout.0] worker #0 started
**[0] tcp.0: [1666098861.991122741, {"log"=>"{data:100 0.5 true This is example}"}]**
```


Please give it a try and let us know.
Ricardo.
