### ISSUE TITLE
high latency from log generation to grafana presentation

### ISSUE THREAD

**Issue by allenhaozi** [fluent/fluent-bit#6168]
## Bug Report

**Describe the bug**

fluent-bit + loki + grafana

There is a high latency from log generation to presentation
<img width="2430" alt="image" src="https://user-images.githubusercontent.com/5318541/194845231-5aa55056-3b6f-4b80-96f9-1978c01d7e73.png">

I started a script that requested a web server in real time, and the web server generated the log

**To Reproduce**

- Steps to reproduce the problem:
+ use helm charts deploy fluent-bit
+ loki
+ grafana

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
    fluent-bit:1.8.14 
    loki:2.6.1
   
* Configuration:
```
apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level debug
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Exclude_Path *_kube-system_*.log,*_logging_*.log,*_airflow_*.log
        Refresh_Interval 5
        Skip_Long_Lines Off
        DB /var/log/flb_kube.db
        Mem_Buf_Limit 1024MB

    [FILTER]
        Name kubernetes
        Match kube.*
        Buffer_Size 512KB
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name loki
        Match kube.*
        Host loki
        Port 3100
        tenant_id ""
        Labels agent=fluent-bit,pod=$kubernetes['pod_name'],namespace=$kubernetes['namespace_name'],name=$kubernetes['labels']['app.kubernetes.io/name'],version=$kubernetes['labels']['app.kubernetes.io/version'],node=$kubernetes['host'],container=$kubernetes['container_name'],instance=$kubernetes['labels']['app.kubernetes.io/instance']
        Label_Keys $stream
        auto_kubernetes_labels off
kind: ConfigMap
metadata:

```

* Environment name and version (e.g. Kubernetes? What version?):
   kubernetes:  v1.20.11
* Server type and version:
* Operating System and version:
CentOS Linux 7
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Possibly related to https://github.com/fluent/fluent-bit/issues/5868 which I believe has a PR in the works for: my understanding (but may be wrong) is that Loki did not support out-of-order writes until 2.4 so previously the Loki plugin had to manage this which now leads to performance issues that are unnecessary with more recent versions of Loki.

I would delve into the linked issue though and it's subsequent links out to understand.

**Comment by allenhaozi** [comment]
Thank you for your reply @patrick-stephens . I'll check it

**Comment by allenhaozi** [comment]
This problem was solved by following @sflanker strategy

https://github.com/fluent/fluent-bit/issues/5868#issuecomment-1263282983
