### ISSUE TITLE
geoip2 module fails to locate the database via relative path

### ISSUE THREAD

**Issue by vaygr** [fluent/fluent-bit#6177]
## Bug Report

**Describe the bug**

Not sure if by design, but fluentbit fails to locate GeoIP database if specified not by a full path, like it's done for parsers and plugins config files.

**To Reproduce**

```
[2022/10/10 22:19:37] [error] [filter:geoip2:geoip2.1] Cannot open geoip2 database: GeoLite2-City.mmdb: Error opening the specified MaxMind DB file
[2022/10/10 22:19:37] [error] Failed initialize filter geoip2.1
[2022/10/10 22:19:37] [error] [lib] backend failed
```

- Steps to reproduce the problem:

Filter section in the config file:

```
[FILTER]
    name         geoip2
    match        syslog
    database     GeoLite2-City.mmdb
    lookup_key   source_ip
    record       country source_ip %{country.names.en}
    record       isocode source_ip %{country.iso_code}
    record       city source_ip %{city.names.en}
```

**Expected behavior**

`GeoLite2-City.mmdb` would be found as `parsers.conf` and `plugins.conf`, relative to `/fluent-bit/etc/fluent-bit.conf` file location.

Changing it to `/fluent-bit/etc/GeoLite2-City.mmdb` fixes the problem.

**Screenshots**

N/A

**Your Environment**

* Version used: 1.9.9
* Configuration: N/A
* Environment name and version (e.g. Kubernetes? What version?): Docker 20.10.3
* Server type and version: N/A
* Operating System and version: N/A
* Filters and plugins: `parser` and `geoip2` filters

**Additional context**

**Comment by MinskLeo** [comment]
I was able to reproduce it in 2024. 2 years and it was not fixed. But ok, at least it works with absolute path.

**Comment by vaygr** [comment]
cc @edsiper
