### ISSUE TITLE
How can I not collect logs for some Pods,not by configuration "annotations: fluentbit.io/exclude: "true" "

### ISSUE THREAD

**Issue by changdongkai** [fluent/fluent-bit#6191]

**Comment by patrick-stephens** [comment]
grep filter to drop, do not collect them in `tail` (e.g. Exclude options), do not match on output, lots of other approaches and depends on config.

**Comment by changdongkai** [comment]
In this way, you can only filter out A certain part of logs in pod. But my idea is that there are three pods,pod A,pod B and pod C. I hope to collect only logs of pod A and pod B without changing the configuration files of the three pods

**Comment by changdongkai** [comment]
@patrick-stephens In this way, you can only filter out A certain part of logs in pod. But my idea is that there are three pods,pod A,pod B and pod C. I hope to collect only logs of pod A and pod B without changing the configuration files of the three pods

**Comment by changdongkai** [comment]
Is to skip logs for the entire pod, not just a portion of the pod
