### ISSUE TITLE
Logs on stackdriver contain wrong container_name

### ISSUE THREAD

**Issue by marwansalem** [fluent/fluent-bit#6193]
According to the documentation the `container_name` should be `gc-logs-test`
instead it is `dashboard-logs`.

`dashboard-logs` is part of the `logName` for another input which shares the output with `gc-logs-test`
![image](https://user-images.githubusercontent.com/47162862/195593102-e6752900-cb44-445b-b14f-a199d60b1194.png)

I am using `fluentbit-1.8`

here is the conf

```conf
    [SERVICE]
        Flush        1   
        Daemon       Off 
        Log_Level    info
        Parsers_File <parser_1>
        Parsers_File <multiline_parser>
    [INPUT]
        Name             tail
        Alias            dashboards
        Tag              k8s_container.<some_namespace>.logger.dashboard-logs
        Path             <path>
        Parser_Firstline <parser_1>
        Path_Key  filename
        Multiline        on  
        Mem_Buf_Limit    1G  
        Refresh_Interval 5
        Skip_Long_Lines true
    [INPUT]
        Name             tail
        Alias            gcs 
        Tag              k8s_container.<some_namespace>.logger.gc-logs-test
        Path             <another_path>
        read_from_head   false
        Mem_Buf_Limit    100MB
        Refresh_Interval 10
        Path_Key  filename

    [OUTPUT]
        Name    stackdriver
        Match  k8s_container.*
        resource  k8s_container
        k8s_cluster_name  <cluster name>
        k8s_cluster_location  <some_location>
    [FILTER]
        Name    lua
        Match   k8s_container.*
        script  log_print.lua
        call    append_filename

    [FILTER]
        Name record_modifier
        Match dashboards
        Record logging.googleapis.com/local_resource_id k8s_container.<some_namespace>.logger.dashboard-logs
    [FILTER]
        Name record_modifier
        Match k8s_container.*
        Record cluster <some_namespace>

    [FILTER]
        Name record_modifier
        Match k8s_container.*
        Record <another_field> <another_value>

# other config
```

**Comment by JeffLuoo** [comment]
`logging.googleapis.com/local_resource_id k8s_container.<some_namespace>.logger.dashboard-logs`

`dashboard-logs` is set to container name based on you configuration. The order is following:

```
k8s_container_<namespace>_<pod_name>_<container_name>
```

**Comment by marwansalem** [comment]
in the record I have shown the logName was `k8s_container.<namespace>.logger.gc-logs-test`
the `container_name` should have been `gc-logs-test`

**Comment by marwansalem** [comment]
also the filter should apply for `dashboards` input only, am I right?

**Comment by JeffLuoo** [comment]
```
    [FILTER]
        Name record_modifier
        Match dashboards
        Record logging.googleapis.com/local_resource_id k8s_container.<some_namespace>.logger.dashboard-logs
```

I don't see any tag `dashboards` in your configuration. `Alias` doesn't mean the tag. You will need to update the tag in the input plugins if you want to modify the `local_resource_id` with `record_modifier` filter.

For the container name `dashboard_logs` with a logName ending with `gc-logs-test`, I cannot tell the root cause based on the configuration you provided. We don't usually predefine information in tag like:

```
k8s_container.<some_namespace>.logger.dashboard-logs
```
