### ISSUE TITLE
Unable to use message compression with kafka output plugin 

### ISSUE THREAD

**Issue by sisteinmetz** [fluent/fluent-bit#6196]
## Bug Report

**Describe the bug**
Due to this issue: https://github.com/fluent/fluent-bit/issues/5957
I rebuild fluentbit from source from master (i have to do it from master due to this issue: https://github.com/fluent/fluent-bit/issues/5300). I used Kafka output plugin and tried to compress messages (gzio, lz4, zstd,...)

**To Reproduce**
i followed this doc: https://docs.fluentbit.io/manual/installation/macos
I do th cmake:
sudo cmake -DFLB_OUT_KAFKA=Yes -DCMAKE_INSTALL_PREFIX=/opt/fluent-bit ../

and then :
sudo make -j 16

and then:
sudo make install

Everything seems ok

i used this conf:

[INPUT]
name dummy
tag dummy.local

[OUTPUT]
name stdout
match *

[OUTPUT]
Name kafka
Match *
Brokers localhost:9092
Topics dummy-gzip
rdkafka.client.id gzip
rdkafka.compression.type gzip
rdkafka.compression.codec gzip

and i start fluentbit:
ssteinmetz@XXXXXX build % sudo /opt/fluent-bit/bin/fluent-bit -c ~/Documents/Siemens/fluent-bit.conf
Fluent Bit v2.0.0

Copyright (C) 2015-2022 The Fluent Bit Authors
Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
https://fluentbit.io/
[2022/10/13 16:53:21] [ info] [fluent bit] version=2.0.0, commit=, pid=61073
[2022/10/13 16:53:21] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/10/13 16:53:21] [ info] [cmetrics] version=0.5.2
[2022/10/13 16:53:21] [ info] [input:dummy:dummy.0] initializing
[2022/10/13 16:53:21] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2022/10/13 16:53:21] [ info] [output:stdout:stdout.0] worker #0 started
[2022/10/13 16:53:21] [ info] [output:kafka:kafka.1] brokers='localhost:9092' topics='dummy-gzip'
[2022/10/13 16:53:21] [ info] [sp] stream processor started
[0] dummy.local: [1665672802.143611000, {"message"=>"dummy"}]
[0] dummy.local: [1665672803.142710000, {"message"=>"dummy"}]
[0] dummy.local: [1665672804.142563000, {"message"=>"dummy"}]

All messages arrive in dummy-gzip topic.
I use kafka 3.1.0.
On this topic compression.codec is producer.

When i check the message compression:

ssteinmetz@Yoga460-90KRVPB Documents % ./confluent-7.2.2/bin/kafka-run-class kafka.tools.DumpLogSegments --files "/Users/ssteinmetz/Library/Application Support/conduktor/jumpstart/3fbc7d57-46de-49b1-bfb7-7eeae91d17ca/data/kafka/dummy-gzip-0/00000000000000000000.log" --print-data-log | grep compresscodec

baseOffset: 0 lastOffset: 0 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false deleteHorizonMs: OptionalLong.empty position: 0 CreateTime: 1665672803143 size: 118 magic: 2 compresscodec: none crc: 1422198876 isvalid: true
baseOffset: 1 lastOffset: 1 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false deleteHorizonMs: OptionalLong.empty position: 118 CreateTime: 1665672804142 size: 117 magic: 2 compresscodec: none crc: 3493017080 isvalid: true
baseOffset: 2 lastOffset: 2 count: 1 baseSequence: -1 lastSequence: -1 producerId: -1 producerEpoch: -1 partitionLeaderEpoch: 0 isTransactional: false isControl: false deleteHorizonMs: OptionalLong.empty position: 235 CreateTime: 1665672805143 size: 118 magic: 2 compresscodec: none crc: 1915063210 isvalid: true

All compression codec are none

I have the same beaviour if i use rdkafka.compression.codec lz4, zstd, ....

**Expected behavior**
All message have to be compress as the producer compression.codec configuration

**Your Environment**
* Version used: Build from master
* Configuration: Macos arm64 M1
* Operating System and version: Macos Monterey 12.4
* Filters and plugins: Kafka output plugin

**Comment by alt-dima** [comment]
@sisteinmetz Hi! Please try to install zlib1g-dev (zlib-dev)

**Comment by alt-dima** [comment]
@sisteinmetz but `brew install zlib` probably only installs binaries and not development files (C++ headers) needed for cmake to find_package.
Please check this: https://stackoverflow.com/a/52511069

**Comment by sisteinmetz** [comment]
i follow this instruction (https://stackoverflow.com/a/52511069):

_Go to https://www.zlib.net/ and download source code. 
Select the "US (zlib.net)" hyperlink about halfway down the page for the tar.xz version.
Then find the download on your local machine and double click on the file. This will unzip the download and create a new folder in the same directly.
Then in Terminal:
cd into the directory with the download
then tar -xvf zlib-1.2.11.tar.xz (Note that zlib-1.2.11.tar.xz may change depending on the latest version you've downloaded. Just run whatever file you're just downloaded.)
Change directories cd zlib-1.2.11
./configure
make
make install_

Everything ok.

I then rebuild Fluentbit from master but i still have the same behaviour...  No errors in starting log but kafka messages are uncompressed....

**Comment by alt-dima** [comment]
Wait, interesting, I also use `rdkafka.compression.codec gzip` and do not see any error message at fluent-bit start.
Maybe it is the same for me and my messages are not compressed :/ 
Will check
