### ISSUE TITLE
Packing on engine side.

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#62]
Now, each input plugin packs their data.
I want to change it.
## New packing method
-  Input plugin passes a input context,data,size and data format to new flb_input API. (not use msgpack)
- Engine enqueues  and packs them in a msgpack of each context.
## Why ?

Engine will be able to add a data to msgpack before flush.
## Usecase

I want to add unique ID(like MAC address, hostname, UUID, etc)  to msgpack.
If thousands of fluent-bit send data to one fluentd, user wants to know which fluent-bit sent the data.

ID doesn't  depend on input plugin, but we add codes to all input plugins.
However, using new method, we only add them to engine.

It is useful to another  data which doesn't depend on input plugin. (e.g timestamp)

**Comment by edsiper** [comment]
sorry for talking too long to reply on this.

The original idea was that Fluent Bit core uses it own MsgPack format to store records, and based on that the input plugin encode their data on that format. In the other side the output plugin re-format or do whatever is required to send the data to the destination.

From your comments I think that there is one thing that may need to be solved:

- Add feature to ingest custom fields into the records before hitting the output plugin.

definitely something that *must* be there and now is missing. 

note: if you see there is still an issue with packaging method let me know.

**Comment by nokute78** [comment]
Thank you for your comment.

First, this is just proposal, not issue.
And I don't want to change until contrary to the policy of fluentbit.

> the output plugin re-format

I think it is difficult, because each input plugin has own format.
Output plugin needs to parse their formats to append additional information.
It is simple to append at input plugins,isn't it?


Sorry to be sidetracked. I want to propose another idea.

Now, almost input plugins 
* allocate msgpack buffer at cb_init().
* destroy and re-init msgpack at cb_flush().
* release msgpack at cb_exit().

So, I think that engine may be able to  manage the lifecycle of msgpack.
I mean flb_input_instance contains msgpack_packer and msgpack_sbuffer.
And engine does 
* allocate msgpack buffer after cb_init() at engine.
* destroy and re-init msgpack after cb_flush().
* release msgpack after cb_exit().

Input plugin only pushes  their data to msgpack. It may be  easy to write/maintain input plugin.

**Comment by edsiper** [comment]
```
So, I think that engine may be able to manage the lifecycle of msgpack.
I mean flb_input_instance contains msgpack_packer and msgpack_sbuffer.
And engine does

    allocate msgpack buffer after cb_init() at engine.
    destroy and re-init msgpack after cb_flush().
    release msgpack after cb_exit().
```

I think that's a good approach, I was also thinking that keeping buffering in the input plugin side could lead to many problems, better to unify. You are right, it's better to let the input plugin to register the record (and forget about buffering and msgpack state).

**Comment by nokute78** [comment]
Thank you for your comment.

I will write a patch that engine manages the msgpack of input plugins.

**Comment by edsiper** [comment]
Now each input plugin instance have it own mspack buffer, each input plugin use it directly. 

Note that if the flush callback (cb_flush_buf()) is set, the engine will use it, otherwise the instance buffer.

Implemented.

**Comment by nokute78** [comment]
@edsiper Thank you for implementing.

Some variables of input plugins are useless with this PR.
(e.g. `buffer_id` of in_stdin. )
