### ISSUE TITLE
How do I not collect logs for specific Pods without changing the pod configuration file

### ISSUE THREAD

**Issue by changdongkai** [fluent/fluent-bit#6203]
For example, there are three pods,pod A,pod B, and pod C. Without changing the configuration files of these three pods, only collect the logs of pod A and pod B, and skip the entire log content of pod C.

**Comment by patrick-stephens** [comment]
Use the exclude annotation: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#request-to-exclude-logs
