### ISSUE TITLE
Spaces in 'add' values cause configuration problems in modify filter

### ISSUE THREAD

**Issue by wtobis** [fluent/fluent-bit#6206]
## Bug Report

**Describe the bug**
When modify filter's `Add1 is the value with spaces in it, it doesn't work as expected.

**To Reproduce**
Add a modify filter to your `fluent-bit.conf` as follows (value with more than one space):
```
[FILTER]
	Name modify
	Match *
	Add key1 "Test Record Value"
```
Then `fluent-bit` fails to start:
```
[2022/10/14 11:12:44] [error] [filter:modify:modify.0] Invalid config for Add
[2022/10/14 11:12:44] [error] Failed initialize filter modify.0
```

When the value has only one space:
```
[FILTER]
	Name modify
	Match *
	Add key1 "Test RecordValue"
```
It doesn't fail but it's ignored in results:
```
[0] tail.0: [1665745827.609156981, {"log"=>"Test log message"}]
```

**Expected behavior**
The filter rule should be applied.

**Additional context**
We have attributes that can contains spaces.

**Comment by phwissmann** [comment]
This is still relevant

**Comment by andrewbeard** [comment]
This may have been addressed here:
https://github.com/fluent/fluent-bit/pull/6387
