### ISSUE TITLE
Get headers from http input 

### ISSUE THREAD

**Issue by IAlexEgorov** [fluent/fluent-bit#6216]
## Bug Report

**Describe the bug**
I try to get some response from service which send it in Fluent Bit (http input) in k8s cluster. I need get data and some headers from this request but when I try to get them, I only get data section in json.  

**To Reproduce**
- Log message:
```
{
	"@timestamp": 555,
	"data": {
		"names": [],
		"tensor": {
			"shape": [
				1
			],
			"values": [
				1
			]
		}
	},
	"meta": {
		"requestPath": {
			"test": "some-regestry"
		}
	},
}

{
	"@timestamp": 555,
	"data": {
		"names": [
			"sex",
			"age",
			"car"
		],
		"tensor": {
			"shape": [
				1,
				1
			],
			"values": [
				1,
				1,
				1,
			]
		}
	}
}
```

This is 2 types of logs I get from service. They don't have some headers

My config:
```
[SERVICE]
    Daemon Off
    Flush 1
    Log_Level info
    Parsers_File parsers.conf
    Parsers_File custom_parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Health_Check On

[INPUT]
    Name http
    Host 0.0.0.0
    Tag seldon

[FILTER]
    Name modify
    Match seldon
    Add header.ce-modelid classifier
    Add header.ce-namespace seldon
    Add header.ce-requestid 33fb419e-8d6b-44e0-a084-8bd4bd4dbf7b

[FILTER]
    Name nest
    Match seldon
    Operation nest
    Wildcard header.*
    Nest_under headers
    Remove_prefix header.

[OUTPUT]
    Name stdout
    Match seldon

``` 
I should use received data from headers (requestid) in filters.

**Expected behavior**
I expect what I get headers from request from service and then use it in filters 

**My Environment**

* Version used: Fluent Bit v1.9.9
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 
* Server type and version: Major:"1", Minor:"22"
* Operating System and version: Ubuntu 22.04

**Comment by ryn9** [comment]
I think this is related to https://github.com/fluent/fluent-bit/issues/5386

**Comment by ryn9** [comment]
@IAlexEgorov want to give a thumbs up on https://github.com/fluent/fluent-bit/issues/5386 ?
