### ISSUE TITLE
Build requirements version 1.9.4 vs 1.9.5

### ISSUE THREAD

**Issue by FSys77** [fluent/fluent-bit#6217]
I was building my dockerized my FluentBit container since a couple of years now. No problems so was.

Base is a Ubuntu 20.04 LTS image (`FROM ubuntu:focal`).

The last working Fluent Bit version was 1.9.4 for me.

From version 1.9.5 onward it started complaining in the `cmake` phase:

```
/usr/bin/env: 'python3': No such file or directory
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
```

Questions:
(1) Why is Python now required?
(2) What was changed regarding OpenSSL?

**Comment by patrick-stephens** [comment]
I can't comment on the dependency changes @FSys77 (I think mbedssl was removed but I believe the official packages have been using OpenSSL for a while now) but the packages are produced in a containerised fashion like so if it helps you: https://github.com/fluent/fluent-bit/blob/00c54dc03f2dd5ed49272b1635292aa503eaf601/packaging/distros/ubuntu/Dockerfile#L72-L81

`./packaging/build.sh -d ubuntu/20.04` should do the build for you, with the `-d` referring to "distro".
