### ISSUE TITLE
Unexpected, repeated calls to `inotify_fs_add()` from `in_tail` plugin

### ISSUE THREAD

**Issue by jamesawebb** [fluent/fluent-bit#6220]
## Bug Report

**Describe the bug**
I am outputting logs from four independent systems with *identical configurations* via a docker container to GCP Ops logs.  Two of the four systems are *constantly and consistently* logging calls to `inotify_fs_add()` for the *same* fluent-bit configuration.

- Example log message:
```
inotify_fs_add(): inode=131185 watch_fd=5 name=/var/lib/docker/containers/406531464f23495c624273f622739dd83357d94eeef6e34b24b5c86241fbb3e9/406531464f23495c624273f622739dd83357d94eeef6e34b24b5c86241fbb3e9-json.log
```

**Expected behavior**
Two systems (correctly) will only register "watched files" once at the start of the container.

**Your Environment**
Fluentbit (1.9.9) is running under a docker (v20.10.10) container on Debian 11 nodes.

**Comment by megaloni** [comment]
@jamesawebb - are your containers (or host nodes) 32 bit or 64 bit? If they are 32 bit, there was a fix recently merged for a similar issue.

https://github.com/fluent/fluent-bit/pull/6199

**Comment by jamesawebb** [comment]
Indeed, these are `armv7l` (32-bit) hosts.  Thanks for the pointer.
