### ISSUE TITLE
Docker debug image, Fluent Bit 1.9: section 'in_exec' tried to instance a plugin name that don't exists

### ISSUE THREAD

**Issue by Neki** [fluent/fluent-bit#6236]
## Bug Report

**Describe the bug**

The Fluentbit 1.9 Docker image does not start when the exec input plugin is used, even with the "debug" image.

**To Reproduce**

Run

```
docker run fluent/fluent-bit:1.9.9-debug /fluent-bit/bin/fluent-bit -i exec -p 'command=ls /etc' -o stdout
```

Output:
```
Fluent Bit v1.9.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/10/19 08:24:43] [error] [config] section 'exec' tried to instance a plugin name that don't exists
[2022/10/19 08:24:43] [error] configuration file contains errors, aborting.
```

**Expected behavior**

The Fluent Bit container should start.

**Your Environment**

* Version used: 1.9.9, "debug" Docker image
* Configuration: see arguments above
* Environment name and version: local (Mac M1, Apple Silicon)
* Server type and version: N/A
* Operating System and version: Mac OS 12.5.1
* Filters and plugins: exec input plugin

**Additional context**

I'm trying to use the exec plugin in a configuration file, but Fluent Bit always fails with `[error] [config] section 'in_exec' tried to instance a plugin name that don't exists`.

The command line above is the simplest way to reproduce the error.

**Comment by patrick-stephens** [comment]
The `exec` plugin is disabled for containers - it cannot work in the production image as it requires `/bin/sh` and the debug image uses the same binary as the production image.

- https://github.com/fluent/fluent-bit/blob/19690076e619f420e89539b6b795bc68401f9871/dockerfiles/Dockerfile#L71
- https://github.com/fluent/fluent-bit/pull/4719
