### ISSUE TITLE
How to define source_type and index in fluentbit-splunk output configuration

### ISSUE THREAD

**Issue by AkshayDubey29** [fluent/fluent-bit#624]
Hi, 
If I would like to specify specific source type and using HEC I would like to send the message to the specific index how do I configure the same in fluentBit-Splunk output configuration.

[OUTPUT]
    Name        splunk
    Match       *
    Host        127.0.0.1
    Port        8088
    TLS         On
    TLS.Verify  Off
    Message_Key my_key

**Comment by michiel** [comment]
We use `out_http` for this, a working example is here https://github.com/michiel/docker-compose-splunk-fluentbit/blob/master/volumes/fluent-bit-etc/fluent-bit.conf

This is part of a docker-compose example project that demonstrates it end-to-end https://github.com/michiel/docker-compose-splunk-fluentbit

**Comment by AkshayDubey29** [comment]
@michiel Thanks :-)

**Comment by AkshayDubey29** [comment]
why are we not using splunk output plugin directly by which we can skip Splunk-forwarder, I think?

**Comment by michiel** [comment]
@AkshayDubey29  - Mainly for the following reasons,

 - The connection between UF and HF does not use the HEC interface but Splunk data forwarding
 - We use a tight coupling between fluent-bit and UF in pods so that the UF can load balance over a pool of HFs

**Comment by AkshayDubey29** [comment]
@michiel  Thank you so much for the inputs but my question was since we are using Splunk as an Output plugin we are bound with some limitations as we can only send the logs to particular index using HEC (We need to Hard Code the index name) there is not an option to push it dynamically.

If we will use HTTP plugin as an output we can push the details in json in which we can push the index name (I am assuming) as of now it didn't work for me due to a different bug in which HTTP plugin is not getting the URI.
