### ISSUE TITLE
expand node_exporter plugin with more metrics

### ISSUE THREAD

**Issue by zyxep** [fluent/fluent-bit#6252]
**Describe the solution you'd like**
The grafana dashboard (Node exporter full, ID: 1860) has way more panels than there are metrics exposed from the implementation of node_exporter.

I would like to see:
`node_filesystem*` metrics exposed as well so there are full disk information in the dashboard. 

**Describe alternatives you've considered**
Add full node_exporter instead of the fluent-bit implementation.

**Comment by patrick-stephens** [comment]
Possibly related to #6250

**Comment by zyxep** [comment]
I think this is still relevant.
It should cover #6250 since that issue is only 1-2 specific metrics.

**Comment by zyxep** [comment]
i still find this relevant :)

**Comment by leonardo-albertovich** [comment]
Hi @zyxep, those should be available in linux, could you please give the latest version a try?

**Comment by zyxep** [comment]
i still need to test the latest update.
