### ISSUE TITLE
Tag variable reference in config file

### ISSUE THREAD

**Issue by UnoSD** [fluent/fluent-bit#6253]
**Is your feature request related to a problem? Please describe.**
I would like to have the input tag in the output as an additional field

**Describe the solution you'd like**
Would be ideal to have a keyword to reference a tag in config ($TAG, %TAG% or anything else)

**Describe alternatives you've considered**
I am currently creating a record_modifier filter for each input:

```
[FILTER]
    name   record_modifier
    match  kernel
    record tag kernel

[FILTER]
    name   record_modifier
    match  netif
    record tag netif

[FILTER]
    name   record_modifier
    match  syslog
    record tag syslog
```

ideally I would like to write a single one like this so it will scale so much better:

```
[FILTER]
    name   record_modifier
    match  *
    record tag %TAG%
```

Thank you

**Comment by patrick-stephens** [comment]
You should be able to do this with LUA I think already.

**Comment by tarruda** [comment]
Can you see if this works?

```
[FILTER]
    Name    lua
    Match   *
    code    function cb(a,b,c)c.tag=a;return 2,b,c end
    call    cb
```

**Comment by UnoSD** [comment]
thank you very much @patrick-stephens and @tarruda, that worked; I also realised this very example is on the LUA page: https://docs.fluentbit.io/manual/pipeline/filters/lua

```
[FILTER]
	Name Lua
	Match *
	call append_tag
	code function append_tag(tag, timestamp, record) new_record = record new_record["tag"] = tag return 1, timestamp, new_record end
​```

I have used that replacing 1 with 2; given only the record has chanced, it made more sense.
