### ISSUE TITLE
How to use the flunet bit kubernetes plugin to collect files in the container

### ISSUE THREAD

**Issue by jacky68147527** [fluent/fluent-bit#6258]
The flunet bit kubernetes plugin is very easy to collect stdout/stderr of the container. 
But sometimes the program writes logs to the container directory, e.g. /data/logs/system-${date}.log
I want to get the kubernetes metadata of /data/logs/system-${date}.log,  file path as stream.
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/6057029/197395526-be8852f7-ff30-4007-9894-e43dfd72bdcc.png">

This problem has been bothering me for a long time, please someone help me, thank you very much.

My filter config is:
```
[FILTER]
    Name           kubernetes
    Match          kube.*
    Kube_URLh      https://kubernetes.default.svc:443
    Merge_Log      On
    Kube_Tag_Prefix  kube.var.log.containers.
    Regex_Parser logfile
    K8S-Logging.Exclude Off
    K8S-Logging.Parser Off
```
My parser config is:
```
[PARSER]
    Name    logfile
    Format  regex
    Regex   (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})(?<stream>.+)$
```

I created a symlink inside the daemonset container to point to the /data/logs/myapp-${date}.log
```
/var/log/containers/gindemo-dev-66cd58c496-67v6r_default_gindemo-3c09c801a4adc73a654be4b40f883d8a69871cbe15466faaec34a2c6878b96b8 -> /data/docker
/overlay2/828f1cae46d6bd6cd7063f27fae921ca42e344e40c321f861bb40e9cc5652352/merged/
```
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/6057029/197394836-80382fbd-db17-4ba4-b6f5-4a1b6d6f8f6e.png">

My input config is:
```
[INPUT]
 Name tail
 Tag kube.*
 Key logfile
 Path /var/log/containers/gindemo-dev-66cd58c496-67v6r_default_gindemo-3c09c801a4adc73a654be4b40f883d8a69871cbe15466faaec34a2c6878b96b8/data/logs/*.log
 Path
 Parser logfile
 DB /run/fluent-bit/flb_kube.db
 Mem_Buf_Limit 250MB
 Buffer_Chunk_size 128k
```

But I fail and the error message I get is: invalid pattern for given tag
```
[2022/10/23 13:28:58] [debug] [task] created task=0x7fe70a031560 id=0 OK
level=debug caller=loki.go:48 id=0 msg="processing records" records="map[gindemo-dev_deployment_default_gindemo-dev-66cd58c496-67v6r_gindemo-file:{\"client_ip\":\"127.0.0.1\",\"latency
_time\":61425,\"level\":\"info\",\"msg\":\"\",\"req_method\":\"GET\",\"req_uri\":\"/\",\"status_code\":200,\"time\":\"2022-10-23 21:28:57\"}]"
[2022/10/23 13:28:58] [debug] [task] destroy task=0x7fe70a031560 (task_id=0)
[2022/10/23 13:28:58] [debug] [input:tail:tail.0] inode=51520995 events: IN_MODIFY
[2022/10/23 13:28:58] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.gindemo-dev-66cd58c496-67v6r_default_gindemo-3c09c801a4adc73a654be4
b40f883d8a69871cbe15466faaec34a2c6878b96b8.data.logs.system.log.20221023.log
```

**Comment by patrick-stephens** [comment]
Your symlink does not match the expected format of K8S log filenames. The K8S filter uses this to extract some metadata about a container log and then query the K8S server for the rest.

Now, as your log is not a container log but an application log the K8S filter probably should not be used anyway for it. You will be getting container logs (stdout/stderr output) already for the container that is generating this separate application log and these will be handled correctly.

Personally I would mount a separate volume for these application logs, either as  FBa sidecar in your pod or using the FB daemonset, and just tail that volume with a separate input as it is a separate pipeline so you can tag differently to avoid the K8S filter. With a sidecar you can easily append any metadata you want, e.g. the DownwardAPI can push in env vars to use for pod name, annotations, etc.
