### ISSUE TITLE
Duplicate logs are forwarded to elasticsearch 

### ISSUE THREAD

**Issue by emilio-cea** [fluent/fluent-bit#6272]
Opening a new issue for visibility, previous one https://github.com/fluent/fluent-bit/issues/5123
> Have you checked the output via stdout output, does that also show duplicates or is the duplicate just in Opensearch?

@patrick-stephens 
Hi, just for confirmation, I also noticed this on my python app. Some log appears as a duplicate on my ES: it has the same timestamp but contains a different _id. 

I checked the stdout plugin and it shows the two logs as well. **Were you looking for a different behaviour?**

This is my `td-agent-bit` config:
```
[SERVICE]
    Flush 5
    Log_Level info
    Daemon Off
    Parsers_File parsers.conf
    Plugins_File plugins.conf

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[OUTPUT]
    Name es
    Host my_es_uri
    Port 8081
    Index fluent_logger_test
    Type type_logger
    Trace_Output on
    Trace_Error on
    Match *
[OUTPUT]
    Name stdout
    Match *
```

I **know these are duplicate** and should not because my app logs to stdout as well, so I can check both the output of the app **in real time**, the stdout of fluentbit and the ES results.

I am using this python logger library for fluentd: https://pypi.org/project/fluent-logger/

```py       
def get_logger(name, populate = None):

    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    log_filter=DatalogFilter()
    logger.addFilter(log_filter)

    log_handler = handler.FluentHandler('test', host='localhost', port=24224, nanosecond_precision=True)
    formatter = handler.FluentRecordFormatter(log_format, fill_missing_fmt_key=True)
    log_handler.setFormatter(formatter)
    logger.addHandler(log_handler)

    return logger
```

When I need to send a log, I call this function and then the appropriate level (debug, info, warning, etc). The DatalogFilter is just to set the json formatting I use.

An extract of fluentbit logs:

```
[2] flogger: [1666614354.900363206, {"url"=>"redacted", "domain"=>"redacted", "log_calling"=>"redacted, line 50, in redacted", "traceback"=>nil, "datetime"=>"2022-10-24T12:25:54.900701+00:00", "hostname"=>"redacted", "loglevel"=>"ERROR", "task_id"=>"6899581c-6e1c-48ad-b0e8-1c2711cee6c7", "worker_id"=>"f71i6ffuiu", "name"=>"redacted", "auth"=>"False", "message"=>"Could not determine page type"}]
[3] flogger: [1666614354.900363206, {"url"=>"redacted", "domain"=>"redacted", "log_calling"=>"redacted, line 50, in redacted", "traceback"=>nil, "datetime"=>"2022-10-24T12:25:54.900701+00:00", "hostname"=>"redacted", "loglevel"=>"ERROR", "task_id"=>"6899581c-6e1c-48ad-b0e8-1c2711cee6c7", "worker_id"=>"f71i6ffuiu", "name"=>"redacted", "auth"=>"False", "message"=>"Could not determine page type"}]

...

{"@timestamp":"2022-10-24T12:25:54.900Z","url":"redacted","domain":"cracked.io","log_calling":"redacted, line 50, in redacted","traceback":null,"datetime":"2022-10-24T12:25:54.900701+00:00","hostname":"redacted","loglevel":"ERROR","task_id":"6899581c-6e1c-48ad-b0e8-1c2711cee6c7","worker_id":"f71i6ffuiu","name":"redacted","auth":"False","message":"Could not determine page type"}
{"index":{"_index":"fluent_logger_test","_type":"type_logger"}}
{"@timestamp":"2022-10-24T12:25:54.900Z","url":"redacted","domain":"redacted","log_calling":"redacted, line 50, in redacted","traceback":null,"datetime":"2022-10-24T12:25:54.900701+00:00","hostname":"redacted","loglevel":"ERROR","task_id":"6899581c-6e1c-48ad-b0e8-1c2711cee6c7","worker_id":"f71i6ffuiu","name":"redacted","auth":"False","message":"Could not determine page type"}
``` 

This is the previous ES log result:
![image](https://user-images.githubusercontent.com/23096738/197533119-f6727189-d00e-42bf-a32a-eb3f24591849.png)

As you can see they have the same exact timestamp, which is weird

_Originally posted by @emilio-cea in https://github.com/fluent/fluent-bit/issues/5123#issuecomment-1289000597_

**Comment by YikaiHu** [comment]
Hi team, same issue.

Our customer is using Flunet-bit to parse multiline log and send through Kinesis Data Stream to Amazon OpenSearch.

The log volume of the user's original log is **18,000** multi-line logs, but after writing to OpenSearch, there are **55,686+** logs, and it **continues to increase**. 

We know that Fluentbit's retries will produce duplicate logs, but we think it's not normal to have duplicate logs that are several times the original log volume.

We have checked the Fluent-bit log, we didn't find any error log but found some warnning like this:

```
[ warn] [output:kinesis_streams:kinesis_streams.0] Discarding large or unprocessable record, LogHub-AppPipe-64239-Stream790BDEE4-lHP7zA5MAoCM
```
And the attachment is the monitoring of the Kinesis Data stream. You can have a check on that.

<img width="975" alt="Xnip2022-10-26_11-18-06" src="https://user-images.githubusercontent.com/34271744/197926570-d12665d5-5d89-433f-9c19-2c6505d4141e.png">



We have also closed the `kinesis_streams` Output and used `stdout` output to check if the multiline parser is working correctly. And we found that when using **stdout**, the parsing is **correct and there is no duplicate data**.

Since we used Lambda to consume Kinesis messages and send them to OpenSearch, we also counted the amount of logs received on the Lambda side to rule out that Lambda caused duplicate data. The experimental results show that there has been a lot of repetition in the data received by Lambda. Therefore, we think that when Fluent-bit sends data to Kinesis, the log is duplicated for some reason.

### System Info

- Fluent-bit Version: 1.9.3
- Instance OS: Amazon Linux2
- Kinesis Data Stream shard number: **16**
- Totle size of customer's log file: 3MB
- Pipeline Architect: EC2 (Fluentbit) -> Kinesis Data Stream(16 shards) -> Lambda -> OpenSearch




### Appendix

Here is the fluent-bit config file, parser file, and sample data:

**Config file:**

```
[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    log_File /tmp/log-agent.log
    http_server  On
    http_listen  0.0.0.0
    http_port    2022
    storage.path /opt/fluent-bit/flb-storage/
    Parsers_File /opt/fluent-bit/etc/applog_parsers.conf

[FILTER]
    Name aws
    Match *
    az true
    ec2_instance_id true
    ec2_instance_type false
    private_ip true
    ami_id false
    account_id false
    hostname true
    vpc_id false

[INPUT]
    Name tail
    # log file location
    Path /tmp/ruikang/*.log
    #Lambda will use Path_key to get file name
    Path_Key file_name
    Tag  c9c2c671-9f8a-49e1-86cd-cbf77d4dbb83_fe992725-cb24-465f-88f7-ed82c3a48e9b
    Read_from_head true
    #use this as checkpoint
    #DB   /tmp/checkpoint-kervin022.db
    #DB.locking  True
    #DB.Sync Normal
    # https://docs.fluentbit.io/manual/administration/backpressure#mem_buf_limit
    Mem_Buf_Limit 30M
    storage.type      filesystem
    # Since "Skip_Long_Lines" is set to "On", be sure to adjust the "Buffer_Chunk_Size","Buffer_Max_Size" according to the actual log. If the parameters are adjusted too much, the number of duplicate records will increase. If the value is too small, data will be lost. 
    # https://docs.fluentbit.io/manual/pipeline/inputs/tail
    Buffer_Chunk_Size 512k
    Buffer_Max_Size   5M
    Skip_Long_Lines   On
    Skip_Empty_Lines  On
    Refresh_Interval  10
    Rotate_Wait       30

[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      multiline-regex-concat

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser oracle

# [OUTPUT]
#     Match *
#     Name                stdout
#     Format              json_lines
#     json_date_format    iso8601
#     json_date_key       _time_


[OUTPUT]
    # KDS plugin name, it means output to KDS.
    Name kinesis_streams
    # Match Tag
    Match c9c2c671-9f8a-49e1-86cd-cbf77d4dbb83_fe992725-cb24-465f-88f7-ed82c3a48e9b
    # AWS region
    Region us-east-1
    # KDS stream name
    #Stream LogHub-AppPipe-fe992-Stream790BDEE4-0hBbkEgwtnrw
    Stream 	LogHub-AppPipe-d78d7-Stream790BDEE4-QDSeGPzeb1J5
    #Role_arn arn:aws-cn:iam::122917663350:role/LogHub-AppPipe-fe992-DataBufferKDSRole7BCBC833-1EFCWEIJPZHWJ
    Role_arn arn:aws:iam::691546483958:role/LogHub-AppPipe-d78d7-DataBufferKDSRole7BCBC833-G8X6N13GQOF1
    # The number of retries after data transmission fails. "False" means no limit, "1" means 1 retry.
    Retry_Limit False
    # Immediately retry failed requests to AWS services once.
    Auto_retry_requests True
    time_key  time
```


**Parser file:**

```
[PARSER]
    Name        oracle
    Format      regex
    Regex       ^(?<time>\w+\s\w+\s\d+\s\d+:\d+:\d+\s\w+\s\d+)[\r\n]?(?<log_detail>[\s\S]*)
    Time_Key    time
    Time_Offset +0800
    Time_Format %a %b %d %H:%M:%S CST %Y

[MULTILINE_PARSER]
    name          multiline-regex-concat
    type          regex
    flush_timeout 1000
    key_content   log
    #
    # Regex rules for multiline parsing
    # ---------------------------------
    #
    # configuration hints:
    #
    #  - first state always has the name: start_state
    #  - every field in the rule must be inside double quotes
    #
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule      "start_state"   "/^\w+\s\w+\s\d+\s\d+:\d+:\d+\s\w+\s\d+.*$/"  "cont"
    rule      "cont"          "/^(?!\w+\s\w+\s\d+\s\d+:\d+:\d+\s\w+\s\d+).*$/" "cont"
```

**Sample Log**

```
Mon Oct 10 15:42:39 CST 2022
Thread 1 advanced to log sequence 252283 (LGWR switch)
  Current log# 1 seq# 252283 mem# 0: /oraclxxxxxxxxxxxxx
Mon Oct 10 15:42:40 CST 2022
LNS: Standby redo logfile selected for t/oraclxxxxxxxxxxxxx
Mon Oct 10 15:44:27 CST 2022
Thread 1 advanced to log sequence 252284 (LGWR switch)
  Current log# 2 seq# 252284 mem# 0: /or/oraclxxxxxxxxxxxxx
Mon Oct 10 15:44:27 CST 2022
LNS: Standby redo logfile selected for thr/oraclxxxxxxxxxxxxx
Mon Oct 10 15:46:03 CST 2022
Thread 1 advanced to log sequence 252285 (LGWR switch)
  Current log# 5 seq# 252285 mem# 0: /oracle//oraclxxxxxxxxxxxxx
Mon Oct 10 15:46:03 CST 2022
LNS: Standby redo logfile selected for thread 1/oraclxxxxxxxxxxxxx
```

**Comment by emilio-cea** [comment]
Sadly we put testing this method on hold for the time being but I have something else to add.

Since I am using the Elastic output, I re-read the docs and noticed the following parameter:

Generate_ID

 Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1

**Comment by sanjinp** [comment]
Just stumbled on this one, and in my case it was related with helm default values where one of recent versions introduced:
```
aws-for-fluent-bit:
  input:
    multilineParser: docker, cri
```
configuration parameter, overriding my previous value `cri`.
So overriding this to single parser fixed it to me, haven't looked further but have an assumption that during send retries single message gets parsed by both of parsers and sent that way.
Hopefully will help someone else.

**Comment by Venture200** [comment]
Hello, @emilio-cea thanks for answer. I wonder if I add this Generate_ID field to my output, will it affect overall log flow in fluent-bit / Elasticsearch side ? Atm i dont have this field enabled and elastic assigns its own _id
