### ISSUE TITLE
Add official Windows OCI image

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluent-bit#6278]
**Is your feature request related to a problem? Please describe.**

We would like to run Fluent Bit as a Windows container but there is no official OCI image.

**Describe the solution you'd like**

We'd like an official Windows OCI image for Fluent Bit to be published to Docker Hub supporting both Windows Server 2019 & 2022.

**Describe alternatives you've considered**

n/a

**Additional context**

Now that Microsoft has [changed the Windows container redistribution rights](https://techcommunity.microsoft.com/t5/containers/announcing-windows-container-base-image-redistribution-rights/ba-p/3645201) to allow Windows to be distributed outside of an organization this should be an easier task.

**Comment by patrick-stephens** [comment]
Does anything need changing in the unofficial image we currently build @stevehipwell ? Or is this just a case of pushing it to Docker Hub?

**Comment by stevehipwell** [comment]
@patrick-stephens what you've currently got in your Windows image deployed to Docker Hub would be a good start as we could iterate from there. I think supporting Windows Server 2022 (I assume you can do multi-arch Windows?) would be pretty high on the requirements list as AKS only supports that OS from AKS v1.25 onwards.

As an aside, given the Fluent Bit v2 support for Windows metrics and the lack of a Prometheus Windows Exporter OCI image; if we can get a Windows Fluent Bit OCI image available I think there is the potential to benefit from being the first mover.

**Comment by patrick-stephens** [comment]
I'll confirm with @edsiper what he wants but from a technical perspective pushing to Docker Hub is trivial.

Note that we already build and push to ghcr.io, e.g. staging for 2.0.3: ghcr.io/fluent/fluent-bit/staging:windows-2019-2.0.3
https://github.com/fluent/fluent-bit/actions/runs/3345512750/jobs/5541145876#step:4:1

It's more the "official" support and test of those images is slightly trickier - Windows containers and K8S nodes are not something we currently have plumbed into full CI testing so I think that needs considering as well. Yes we can push containers to Docker Hub but we also need a bit more testing around them to make them "official" is my personal opinion.

**Comment by stevehipwell** [comment]
@patrick-stephens do you know how much complexity it'd add to support Windows Server 2022?

I could get you some initial feedback on the Windows images, this wouldn't do away with the need for Windows in the CI system long term but could help the initial iteration. I think that having Windows images on Docker Hub would aid discoverability and provide the kind of feedback needed to progress the maturity; assuming they were documented as experimental and "best effort".

**Comment by patrick-stephens** [comment]
I'll submit a PR to update the release workflow to sync them over from staging as an initial thing as that is relatively simple and then can be approved by the relevant authorities if they agree easily.

For Windows Server 2022 I'm afraid I have no idea, I think it is a build argument so maybe just give it a go? I don't have a Windows dev env available at the moment - I'll look at adding one to the CI though to simplify this moving forward if we can (depending on cost/licensing/all the fun things!).

**Comment by stevehipwell** [comment]
> For Windows Server 2022 I'm afraid I have no idea, I think it is a build argument so maybe just give it a go? I don't have a Windows dev env available at the moment - I'll look at adding one to the CI though to simplify this moving forward if we can (depending on cost/licensing/all the fun things!).

@patrick-stephens I think it'd just be a build arg integrated into the GH Actions matrix. AFAIK the licencing is at the VM not the container and the announcement in the issue description makes the whole thing much simpler.

**Comment by patrick-stephens** [comment]
@stevehipwell ok, I can probably make an update around the build matrix too then the nightly build should pick it up if you can test it easily?

**Comment by stevehipwell** [comment]
@patrick-stephens we have end-users waiting to test this, ideally I'd wait for any changes to the publishing pattern (e.g. no longer staging and/or Docker Hub) before testing but if that's going to take some time we could try what's there right now.

**Comment by patrick-stephens** [comment]
On another note, if there is any way to speed up the image build as well for Windows please let me know as well @stevehipwell - Windows runners cost more than Linux ones and the build takes an absolute age to make a rather large image so likely needs some optimisation if we can.

**Comment by stevehipwell** [comment]
@patrick-stephens I'm not a Windows expert and we don't have any Windows tooling which is why we need official images for Windows. We do have end-users wanting Windows support so we're trying to give them as close an experience to Linux as possible and can get "official" Windows images tested.

I think this suggestion works for both Linux & Windows. I'm a proponent of building binary artifacts separately to OCI images, so I'd suggest that the binaries be built and signed independently to creating the images. This would reduce what I assume is the longest part of the image build and mean that it only needs to be run once per OS architecture? I'd also suggest only running the Windows CI when everything else is working or via a specific label to keep costs down to a minimum.

**Comment by thebridge90** [comment]
@patrick-stephens Hello I am interested in using the official Windows 2022 build as well. I see that https://github.com/fluent/fluent-bit/pull/6315 and https://github.com/fluent/fluent-bit/issues/6356 have been merged.
Is it now possible to pull the image from the non staging registry? If so what is the URL?
Thanks.

**Comment by patrick-stephens** [comment]
Not yet, still having some issues but hopefully next release. However the image is identical to the staging one - we copy it over unchanged just with a new tag.

**Comment by patrick-stephens** [comment]
Finally up folks, a little large so we need to look at optimisation if possible but they are there...
* https://hub.docker.com/r/fluent/fluent-bit/tags
*https://hub.docker.com/layers/fluent/fluent-bit/windows-2022-2.0.6/images/sha256-4c32e21865f278d2ad65015c499462475df6a55717bc0b01dd6c01e9163d25d6?context=explore
* https://hub.docker.com/layers/fluent/fluent-bit/windows-2019-2.0.6/images/sha256-2bb42a94822bd266e2867c702ba0a1f9af8bcaa3ab074ad1979c00a775adffe0?context=explore

![Screenshot from 2022-11-23 08-43-35](https://user-images.githubusercontent.com/6388272/203503666-180dd9df-6214-4e93-8209-7303820b9205.png)

**Comment by djsly** [comment]
that's awesome ! right on time, Thanks!

**Comment by patrick-stephens** [comment]
Any feedback folks? I think it would be good to close this issue off and raise specific issues for anything that comes up.

**Comment by stevehipwell** [comment]
@patrick-stephens I'll be testing the image a part of the `fluent-bit-collector` Helm chart I'm working on but I don't think this will be until the new year. I can see the image in the registry so I would say that you've met the issue requirements and any changes required should be tracked as separate issues.
