### ISSUE TITLE
in_node_exporter_metrics: add filesystem collector

### ISSUE THREAD

**Issue by psoares** [fluent/fluent-bit#6279]
**Is your feature request related to a problem? Please describe.**
I'm using the grafana dashboard [Node Exporter Full](https://grafana.com/grafana/dashboards/1860-node-exporter-full/).
The widgets displaying information about the file system are empty.

**Describe the solution you'd like**
I'd like to have a fully functional dashboard. In particular, I'd like to see the data of the "Root FS Used" and "Disk Space Used Basic" widgets.

**Describe alternatives you've considered**
- Using a different dashboard.
- Running a full-fledged node_exporter container.

**Additional context**
N.A.

**Comment by braunsonm** [comment]
Disk space usage is a really important and basic metric that should be supported. Often we also use this collector to monitor the space of various mounts too.

**Comment by ichasco-heytrade** [comment]
Does anyone know if this will be implemented? This is really useful
