### ISSUE TITLE
Output plugin isn't processing all the records in the pipeline

### ISSUE THREAD

**Issue by aashishgaba-cn** [fluent/fluent-bit#6283]
## Bug Report

**Describe the bug**
- Context
   - I've got a log file with approx 200k entries. And I need to process
      - existing entries as well as
      - any new entries that come into that file
   - I'm using tail plugin for this functionality
- Bug
   - There is huge difference in the expected processed logs vs the actual processed logs
      - There are certain logs getting dropped due to filters but the dropped log counts is very less. `740+108=848`
   - Stats 
       - Re-emmited records: 260360
       - Dropped logs: 848
       - Expected records to be processed by output = 260360 - 848 = 259512
       - BUT, the processed logs by Kinesis Output plugin is very less 29799.
   - There's no error in sending records to Kinesis Data Stream as per monitoring
   - Details about all these were obtained from the http monitoring server's `/api/v1/metrics` endpoint. You can find the response below.
```
{
    "input": {
        "tail.0": {
            "records": 260502,
            "bytes": 39958392,
            "files_opened": 2,
            "files_closed": 0,
            "files_rotated": 0
        },
        "storage_backlog.1": {
            "records": 0,
            "bytes": 0
        },
        "re_emitted": {
            "records": 260360,
            "bytes": 45143761
        }
    },
    "filter": {
        "parser.0": {
            "drop_records": 0,
            "add_records": 0
        },
        "rewrite_tag.1": {
            "drop_records": 260502,
            "add_records": 0,
            "emit_records": 260360
        },
        "parser.2": {
            "drop_records": 0,
            "add_records": 0
        },
        "filter-other-anti-spoofing-events": {
            "drop_records": 740,
            "add_records": 0
        },
        "parser.4": {
            "drop_records": 0,
            "add_records": 0
        },
        "filter-other-ips-events": {
            "drop_records": 108,
            "add_records": 0
        },
        "nest.6": {
            "drop_records": 0,
            "add_records": 0
        },
        "lua.7": {
            "drop_records": 0,
            "add_records": 0
        }
    },
    "output": {
        "kinesis_streams.0": {
            "proc_records": 29799,
            "proc_bytes": 12268228,
            "errors": 0,
            "retries": 0,
            "retries_failed": 0,
            "dropped_records": 0,
            "retried_records": 0
        }
    }
}
```

**Expected behavior**
- The processed record by Kinesis output plugin to be equal to the emmited - dropped logs

**Your Environment**
* Version used: 1.9
* Configuration:
* Operating System and version: Ubuntu 20.04
* Filters and plugins:
- Filters:
   - re-write tag
   - parser
   - nest
   - grep
- Output
   - Kinesis Data Stream

**Comment by edsiper** [comment]
config ?

**Comment by aashishgaba-cn** [comment]
The issue was that the ingestion rate was too much and the logs were getting dropped. Upon controlling the rate of ingestion using  `Mem_Buf_Limit` at input level, there was no log loss.
