### ISSUE TITLE
Regex not matching on integer values in records

### ISSUE THREAD

**Issue by Fritte795** [fluent/fluent-bit#6284]
## Bug Report

**Describe the bug**
When using filters on the input generated by the plugin winevtlog regular expressions are not matching integer values. "key": "foo" can be matched. "id": 1 will not be matched. Therefore filters like "rewrite_tag" or "grep" can't filter by "id".

**To Reproduce**
Example Output of "stdout" (added linebreaks for readability):  
```
[1666788644.396360200, 
{"ProviderName"=>"Microsoft-Windows-Servicing", 
"ProviderGuid"=>"{BD12F3B8-FC40-4A61-A307-B7A013A069C1}", 
"Qualifiers"=>"", 
"EventID"=>1, 
"Version"=>0, 
"Level"=>0, 
"Task"=>1, 
"Opcode"=>0, 
"Keywords"=>"0x8000000000000000", 
"TimeCreated"=>"2022-01-17 09:04:35 +0100", 
"EventRecordID"=>23, 
"ActivityID"=>"", 
"RelatedActivityID"=>"", 
"ProcessID"=>4688, 
"ThreadID"=>12720, 
"Channel"=>"Setup", 
"Computer"=>"censored", "UserID"=>"censored", 
"Message"=>"censored"}]
```
Using filters as in the config below shows that a Regex /1/ on "EventID" will not match. Otherwise a Regex "/Setup/" on "Channel" will match. 

**Expected behavior**
It should be possible to use filters with regular expressions matching non-stringified IDs in combination with the winevtlog plugin.

**Your Environment**

* Version used: 1.9.9
* Configuration:
```
[SERVICE]
    flush        1
    daemon       Off
    log_level    debug
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on

[INPUT]
    Name                    winevtlog
    tag                     winlog.delete
    Channels                Application,Setup,Windows PowerShell,System
    Interval_Sec            1
    Read_Existing_Events    true
    # String Inserts won't be parsed to json by http output
    String_Inserts          false

[FILTER]
    Name    rewrite_tag
    Match   winlog.delete
    Rule    $EventID /4/ winlog.keep false

[FILTER]
    Name    modify
    Match   winlog.keep
    Add     beaker_type WINLOG

[OUTPUT]
    Name    null
    Match   *.delete

[OUTPUT]  
    Name    stdout
    Match   *.keep
```

* Filters and plugins: rewrite_tag or grep, winevtlog

**Additional context**
The goal is to send Windows Event Logs to Opensearch. Each client should be able to filter by certain EventIDs so that no unneccessary data must leave the clients machine. Only certain EventIDs are needed for further analysis.

**Comment by msobkowiak-olx** [comment]
I must say I am running into the same issue on 1.9.8, simple regexp against integer field fails for various combinations.
To name a few:
`
Exclude status .*
Exclude status 200
Exclude status (200|404)
Exclude status ^(2[0-9]{2})$
`
Even tried using $status, no luck.

Any way I can avoid converting it into string ? Would trying matching against \xC8 or other magic work ?

**Comment by Fritte795** [comment]
@msobkowiak-olx One temporary solution might be to use the lua filter with custom scripts. In my case I could change the tag if an ID occured I want to drop.

**Comment by msobkowiak-olx** [comment]
I am going to duplicate my field (its HTTP status codes) as string this time, it is much easier for me.

**Comment by itsyuvalcohen** [comment]
This is also an issue when trying to filter boolean values.
I'm using rewrite_tag to catch all record where a specific field equals true and it doesn't work because its in a boolean form and not string.

The following config won't output anything.

`[INPUT]
          Name   dummy
          Tag    dummy
          Dummy  {"test": {"is_true": true}}
[FILTER]
          Name          rewrite_tag
          Match         dummy
          Rule          $test['is_true'] ^(true)$  test true
          Emitter_Name  re_emitted
[OUTPUT]
          Name stdout
          Match test
          `

**Comment by qmonitoring** [comment]
Any update on this issue?

**Comment by qmonitoring** [comment]
I ran into this issue while trying to filter messages by EventID.
Simple configuration to reproduce the issue:
```
[INPUT]
    Name               winlog
    Channels           Windows PowerShell
    Tag                win
    Interval_Sec       1
    
[FILTER]
    Name              grep
    Match             win
    Exclude           EventID 800    

[OUTPUT]
    Name              file
    Match             win
    Path              .\logs\
```

**Comment by CarliJoy** [comment]
This is also true with `Key_value_equals`.
Acutally it seems that `modify` Condition do not work at all if the given value is not a string.

That is pretty annoying.

**Comment by CarliJoy** [comment]
Ok the solution is to convert it to string first and remove the string later:

```
[INPUT]
    Alias        input_kernel
    Name         kmsg
    Tag          kernel
    
[FILTER]
    Alias        filter_kernel_add_prio_string
    Name         type_converter
    Match        kernel
    # modify condition only work with string
    uint_key     priority priority_str string

[FILTER]
    Alias        filter_kernel_level0
    Name         modify
    Match        kernel
    # maybe set level to cirtical?
    Set          level   ERROR
    # From: https://linuxconfig.org/introduction-to-the-linux-kernel-log-levels
    # The first log level is 0, identified by the KERN_EMERG string. This is the highest level in order of severity: it’s adopted by messages about system instability or imminent crashes.
    Condition    Key_value_equals priority_str 0

[FILTER]
    Alias        filter_drop_temp_field
    Name         modify
    Match        kernel
    Remove       priority_str
```

Works like expected
