### ISSUE TITLE
in_tail: Ignore_Older does not work properly on Windows

### ISSUE THREAD

**Issue by davsan-0** [fluent/fluent-bit#6294]
## Bug Report

**Describe the bug**
The configuration option `Ignore_Older` for `in_tail` has no effect. It still registers files older than what is configured.

**To Reproduce**
*Windows only*
If you add a new file that matches the Path pattern in your `in_tail` config, you will see while debugging the application that [this](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.h#L46) line does not *"return the file modification time in seconds since epoch"* as expected, but rather an 18-digit long LDAP timestamp.

**Expected behavior**
The `Ignore_Older` configuration should work. The function mentioned above should return a Unix epoch timestamp for Windows.

**Your Environment**

* Version used: 2.0.0
* Configuration:
```
[SERVICE]
    flush 5
    log_level debug

[INPUT]
    name tail
    path Path/To/Folder/*.log
    ignore_older 60

[OUTPUT]
    name stdout
    match *
```
* Environment name and version (e.g. Kubernetes? What version?): N/A
* Server type and version: N/A
* Operating System and version: Any Windows (tried on 10 and Windows Server 2019)
* Filters and plugins: in_tail

**Additional context**

This issue has caused fluent-bit on the server to open all the log files from ages ago until it gets an error `Too many files open`. Then it can't open the files I actually want it to open and my logs don't get forwarded.

**Comment by davsan-0** [comment]
I opened a Pull Request that fixes this issue https://github.com/fluent/fluent-bit/pull/6291

**Comment by edsiper** [comment]
assigned to @leonardo-albertovich
