### ISSUE TITLE
Improve build times for arm64v8

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#6300]
## Bug Report

**Describe the bug**

CI Build times for release are taking very long for some jobs, in particular amazon linux 2, arm64v8.
https://github.com/fluent/fluent-bit/actions/runs/3339871136/jobs/5529341698

Identify the root cause of the slowness and possibly run in a dedicated arm64v8 worker.

**Expected behavior**

Should take average times for any arm64v8 job.

**Comment by patrick-stephens** [comment]
Running on a dedicated ARM builder seems to be as performant as expected so this is likely an issue with the containerised build and/or QEMU. There were other issues with the latest AL2022 when testing due to cgroups changes as well.

**Comment by patrick-stephens** [comment]
See https://github.com/fluent/fluent-package-builder/pull/416#issuecomment-1245042522 as well, seems to be a common issue for this particular target.

**Comment by patrick-stephens** [comment]
@PettitWesley is there anyone we can reach out to on the AWS side to give us a hand with these very extended build times?

**Comment by alexellis** [comment]
@patrick-stephens asked me to drop a link to what we're working on, it would solve this problem:

Two case-studies:

https://actuated.dev/blog/case-study-bring-your-own-bare-metal-to-actions
https://actuated.dev/blog/native-arm64-for-github-actions

**Comment by patrick-stephens** [comment]
Possibly related to https://github.com/amazonlinux/amazon-linux-2023/issues/218

**Comment by patrick-stephens** [comment]
Using a dedicated self-hosted runner configured through actuated.dev shows a build in the 4 minute time frame which is nice!
This was on our commercial LTS offering so I need to figure out the best option for CNCF OSS inclusion of the build infrastructure to get it over here.
