### ISSUE TITLE
fluent bit is crashing  with exit code 139 without logging any error

### ISSUE THREAD

**Issue by bikkinamahesh369** [fluent/fluent-bit#631]
Image:		fluent/fluent-bit-0.13-dev:0.13
    Image ID:		docker-pullable://fluent/fluent-bit-0.13-dev@sha256:d0c6d67ed3cce0dd40eb1d33a8a4c79b8ba340ed548d186b96105a865b6fa4fc
    Port:		
    State:		Running
      Started:		Wed, 13 Jun 2018 14:52:01 +0530
    Last State:		Terminated
      Reason:		Error
      Exit Code:	139
      Started:		Wed, 13 Jun 2018 14:37:01 +0530
      Finished:		Wed, 13 Jun 2018 14:52:00 +0530
    Ready:		True
    Restart Count:	224

**Comment by chlunde** [comment]
Hi, exit code 139 means segfaults.  I believe this was fixed with 175bc1a6d9cd3d58f5ba6b4a8aa0ea2e1fc94bcc and 274fc36f0d104d8bbe7485a1b7a37e93c4f283ec.  Can you check the latest version, `fluent/fluent-bit:0.13.4`?  Thanks

**Comment by agup006** [comment]
Hi I'm performing some cleanup and this looks like an old issue. Additionally, looks like a very old version of Fluent Bit, would be great to check 1.7.0 to see if this still persists. I'm going to close for now, feel free to re-open if needed

**Comment by riteshsoni10** [comment]
@chlunde I am facing the similar issue on EKS cluster with fluent-bit containers.

EKS Version: 1.20

```
  fluent-bit:
    Container ID:   docker://f0d37ac31064bc4d1f81a5c406e13f4b4a9056a2342bbefed07df09b9f88392e
    Image:          amazon/aws-for-fluent-bit:2.14.0
    Image ID:       docker-pullable://amazon/aws-for-fluent-bit@sha256:df5224e71959299c8a940ddf213cf691508a8bc2b2c08b62049e59894cc88f22
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 27 May 2021 10:41:41 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    139
      Started:      Thu, 27 May 2021 10:12:26 +0800
      Finished:     Thu, 27 May 2021 10:41:32 +0800
    Ready:          True
    Restart Count:  4
```
