### ISSUE TITLE
Get OS Version as environment variable

### ISSUE THREAD

**Issue by LeoWinterDE** [fluent/fluent-bit#6314]
**Is your feature request related to a problem? Please describe.**
Is there a way to ship the system OS version/build (`uname -a` and the windows equivalent) just like the the $HOSTNAME environment variable inside a [record_modifier](https://docs.fluentbit.io/manual/pipeline/filters/record-modifier)?

**Describe the solution you'd like**
```
[FILTER]
    Name                              record_modifier
    Match                             *
    Record hostname                   ${HOSTNAME}
    Record fluentbit-version          ${FLUENT_BIT_VERSION}
    Record os-version                 ${OS_VERSION}
```

Rel: `${FLUENT_BIT_VERSION}` #5344

**Comment by patrick-stephens** [comment]
Use the `exec` plugin to do it maybe? Or as per the discussion on #5344 set it as a variable in your init system.
HOSTNAME is not set by Fluent Bit, it's set by the OS that runs it.

**Comment by LeoWinterDE** [comment]
Sure, but shipping your own systemd/init configuration when using the official repository directly is quite painful.

With `exec` there are some problems, e.g. the exec key overwrites itself if we use two of them:
```
[INPUT]
    Name              exec
    Command           (lsb_release -ds || cat /etc/*release || uname -om) 2>/dev/null | head -n1
    Interval_Sec      1
#    Oneshot           true
    Tag               log
[FILTER]
    Name              modify
    Match             log
    Rename            exec os-version
[INPUT]
    Name              exec
    Command           uname -r
    Interval_Sec      1
    Oneshot           true
    Tag               log
[FILTER]
    Name              modify
    Match             log
    Rename            exec os-kernel
```

Is there a way to name the key differently (then exec) that emerges from exec?
