### ISSUE TITLE
Hang on HTTP/1.0 Request, Unexpected EOF. (Nignx upstream)

### ISSUE THREAD

**Issue by pythonwood** [fluent/fluent-bit#6317]
## Bug Report

**Describe the bug**

`timeout 5 curl --http1.0 http://127.0.0.1:2020/api/v1/metrics/prometheus/`

... get output ...
...
fluentbit_build_info{version="1.9.9",edition="Community"} 1
(hang on 5 seconds)

`curl --http1.0 http://127.0.0.1:2020/api/v1/metrics/prometheus/ # not ok`
(hang on long time)

`curl --http1.1 http://127.0.0.1:2020/api/v1/metrics/prometheus/ # just ok`

**Your Environment**
version 1.9.9 metrics on 
run in docker fluent/fluent-bit:1.9.9

**Additional context**

It happend to me when use nignx reverse proxy for fluent-bit metrics.
nginx upstream defaul http 1.0, I fix it in some day later with `proxy_http_version 1.1;`

It is a feature or bug ?

**Comment by ywsswy** [comment]
@pythonwood 借楼问个问题

'https://qa.1r1g.com/' 这个网站是你在维护的吗？（我是通过网站备案信息查询到的）

虽然备案信息写的是“个人经验分享”，但是实际上我发现这个网站的内容都是从stackoverflow网站上“盗”来的。
举例来说，[https://qa.1r1g.com/sf/ask/20465021/](https://qa.1r1g.com/sf/ask/20465021/) 这个页面的原始来源是 [https://stackoverflow.com/questions/292357/what-is-the-difference-between-git-pull-and-git-fetch/44672602#44672602](https://stackoverflow.com/questions/292357/what-is-the-difference-between-git-pull-and-git-fetch/44672602#44672602)

这给我最大的困扰在于，“盗”用国外网站，使用机器自动翻译成中文可能并不利于解决问题（因为机器翻译可能语义不通顺），在这种情况下，为什么不备注清楚“转载来源”呢？这样的话当中文有歧义的时候网友们还可以去看原始网页

**Comment by pythonwood** [comment]
@ywsswy 你好，歪楼是恶习请注意。我有邮箱，虽然不常看，你申请加我微信，备注问题就行。下一版本会带上。

**Comment by ywsswy** [comment]
好的，谢谢
