### ISSUE TITLE
Kafka authentication and TLS support in fluent-bit kafka output plugin.

### ISSUE THREAD

**Issue by abhishekkumarsingh1** [fluent/fluent-bit#632]
It seems as of now there is no support of TLS and authentication for kafka_out plugin. This support is important for forwarding logs securely to kafka.

**Comment by mplachter** [comment]
Is there any work to include SSL through `librdkafka` properties?

**Comment by gabe-sorensen** [comment]
This should be supported. I was able to get it to connect with the following section of properties:

    rdkafka.security.protocol    ssl
    rdkafka.ssl.ca.location      /tmp/ca.cert
    rdkafka.ssl.certificate.location /tmp/cert.pem
    rdkafka.ssl.key.location         /tmp/cert.key

**Comment by mplachter** [comment]
I will test again but when I did the same fluent-bit would start up and say something to the effect of these settings are ignored

**Comment by gabe-sorensen** [comment]
I'm using 1.0.4, but I was seeing this error when I was running: 

[error] [out_kafka] cannot configure 'certificate.location' property

I forgot to add the .ssl before the property, which was my issue

**Comment by michaeltravisuk** [comment]
I'm still having trouble with this.  Getting the following in my fluent-bit logs:

`[2019/04/09 15:04:17] [error] [out_kafka] cannot configure 'security.protocol' property
[2019/04/09 15:04:17] [error] [out_kafka] cannot configure 'ssl.ca.location' property
[2019/04/09 15:04:17] [error] [out_kafka] cannot configure 'ssl.certificate.location' property
[2019/04/09 15:04:17] [error] [out_kafka] cannot configure 'ssl.key.location' property`

I've double checked the librdkafka parameters and made sure that all the referenced certificates/keys are valid and readable.  This is on fluent-bit 1.0.6 (td-agent-bit).

**Comment by edsiper** [comment]
for anyone facing an issue please paste full configuration and fluent bit output

**Comment by michaeltravisuk** [comment]
fluent-bit (1.0.6) config is:

`[SERVICE]
    Daemon       Off
    Parsers_File /etc/td-agent-bit/parsers.conf

[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5170
    Chunk_Size  32
    Buffer_Size 64

[FILTER]
    Name     parser
    Match    *
    Key_Name message
    Parser   logformat

[OUTPUT]
    Name Kafka
    Match *
    Topics {{topic-name}}
    Timestamp_Key time
    Brokers {{kafka-broker:9093}}
    rdkafka.request.required.acks 1
    rdkafka.log.connection.close false
    rdkafka.compression.codec snappy
    rdkafka.security.protocol    ssl
    rdkafka.ssl.ca.location /etc/td-agent-bit/kafka-ca.crt
    rdkafka.ssl.certificate.location /etc/td-agent-bit/kafka-client.crt
    rdkafka.ssl.key.location /etc/td-agent-bit/kafka-client.key`

The output I get is:

`Fluent Bit v1.0.6
Copyright (C) Treasure Data

[2019/04/10 11:08:42] [ info] [storage] initializing...
[2019/04/10 11:08:42] [ info] [storage] in-memory
[2019/04/10 11:08:42] [ info] [storage] normal synchronization mode, checksum disabled
[2019/04/10 11:08:42] [ info] [engine] started (pid=98108)
[2019/04/10 11:08:42] [error] Error binding socket
[2019/04/10 11:08:42] [ warn] Cannot listen on 0.0.0.0 port 5170
[2019/04/10 11:08:42] [error] [in_tcp] could not bind address 0.0.0.0:5170. Aborting
[2019/04/10 11:08:42] [error] Failed initialize input tcp.0
[2019/04/10 11:08:42] [error] [out_kafka] cannot configure 'security.protocol' property
[2019/04/10 11:08:42] [error] [out_kafka] cannot configure 'ssl.ca.location' property
[2019/04/10 11:08:42] [error] [out_kafka] cannot configure 'ssl.certificate.location' property
[2019/04/10 11:08:42] [error] [out_kafka] cannot configure 'ssl.key.location' property
[2019/04/10 11:08:42] [ info] [out_kafka] brokers='broker-name:9093' topics='topic.name'
[2019/04/10 11:08:43] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: kafka-broker:9093/bootstrap: Receive failed: Connection reset by peer (after 3ms in state UP)
[2019/04/10 11:08:43] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: kafka-broker:9093/bootstrap: Receive failed: Connection reset by peer (after 3ms in state UP)
[2019/04/10 11:08:43] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:08:44] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:08:45] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:08:46] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:08:47] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:08:48] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-broker:9093/bootstrap]: 1/1 brokers are down`

**Comment by michaeltravisuk** [comment]
Done a bit more local testing, Got a basic setup capturing CPU stats and sending to a secured topic.  The output config looks like this:

```[OUTPUT]
  Name Kafka
  Match *
  Topics secure-logs
  Timestamp_Key time
  Brokers kafka-0:9093
  rdkafka.request.required.acks 1
  rdkafka.log.connection.close false
  rdkafka.compression.codec snappy
  rdkafka.security.protocol ssl
  rdkafka.ssl.ca.location /etc/fluent-bit/ca.crt
  rdkafka.ssl.certificate.location /etc/fluent-bit/client.crt
  rdkafka.ssl.key.location /etc/fluent-bit/client.key```

On fluent-bit 0.13.7 this works correctly (no output is reported and the messages appear on the queue).

On fluent-bit 1.0.6 with the exact same config and file locations:

```Fluent Bit v1.0.6
Copyright (C) Treasure Data

[2019/04/10 11:00:48] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-0:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:00:49] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-0:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:00:50] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-0:9093/bootstrap]: 1/1 brokers are down
[2019/04/10 11:00:51] [error] [out_kafka] fluent-bit#producer-1: [thrd:kafka-0:9093/bootstrap]: 1/1 brokers are down```

**Comment by michaeltravisuk** [comment]
Any update on this?  We're still unable to use current versions of fluent-bit to output messages to our Kafka cluster.  Any attempt to set `librdkafka` SSL configuration fails (other `librdkafka` config works:

Using fluent-bit 1.0.6 in debug mode:

```[2019/05/20 10:10:55] [error] [out_kafka] cannot configure 'security.protocol' property
[2019/05/20 10:10:55] [error] [out_kafka] cannot configure 'ssl.ca.location' property```

**Comment by michaeltravisuk** [comment]
I've managed to get it working, but I've had to compile the binary myself.
Even with the build option `FLB_TLS` set to `On` I had to also have the `openssl-devel` package installed (this is on CentOS - we run a combination of CentOS 6 and 7) for the resulting binary to actually allow me to send messages to an SSL fronted Kafka cluster.

Assuming that the `td-agent-bit` CentOS RPMs are built from:
https://github.com/fluent/fluent-bit-packaging/blob/master/distros/centos/7/Dockerfile.base

`openssl-devel` isn't included, and `FLB_TLS` isn't specified in:
https://github.com/fluent/fluent-bit-packaging/blob/master/distros/centos/7/Dockerfile#L12
It is is set to `Off` by default as I understand it.

**Comment by den-is** [comment]
so still no definitive fix to that issue?

`Aug 03 15:22:46 ip-10-70-28-193.ec2.internal td-agent-bit[2849]: [2019/08/03 15:22:46] [error] [out_kafka] cannot configure 'security.protocol' property`

i'm getting same'ysh issue while trying to use fluentbit with AWS MSK (managed kafka) which is TLS.
At the same time absolutely same config is working fine with fluentbit running in container in kubernetes cluster as daemon set.

Debug shows no additional informative messages.
```
[OUTPUT]
    Name             kafka
    Match            *
    Brokers          worker1:9094,worker2:9094,worker3:9094
    Topics           logstash
    Timestamp_Key    @timestamp
    Timestamp_Format iso8601
    rdkafka.security.protocol          ssl
    rdkafka.log.connection.close       false
    rdkafka.request.required.acks      1
    rdkafka.queue.buffering.max.kbytes 10240
```

**Comment by edsiper** [comment]
thanks for the info.

Indeed the Dockerfiles build images used to package don't have openssl-devel (RPM) and libssl/libssl-dev on Debian based systems, so when librdkafka builds there is no SSL support.

Future release will come with proper dependency linked.

**Comment by lifeofguenter** [comment]
@edsiper is this still an issue? Seems like it is fixed?

**Comment by Hichem-BenJeddi** [comment]
I had the same issue with the old version. The latest version has fixed the issue now the SSL authentication with kafka is working correctly

**Comment by edsiper** [comment]
this is fixed, thanks for the follow up.

closing it.

**Comment by nealflux** [comment]
which version of Kafka output has fixed this I have to use Logstash 5.6 as I am getting data out of elastic 2.3.5 and want to put that to Kafka

**Comment by aderuwe** [comment]
This does not seem fixed in the packages for ubuntu in version 1.4.5 as I still get this error?

**Comment by deepankarmalhan** [comment]
Still running into this issue @edsiper for v1.5.0 as well. Running v1.3.2 in a container works (the docker image is built differently so that makes sense).

**Comment by paul-greidanus-hs** [comment]
I just submitted an issue against the packaging repo: https://github.com/fluent/fluent-bit-packaging/issues/13

**Comment by atalukdar** [comment]
Still running into issue for v1.7.0 for Redhat / CentOS

failed to create producer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN

**Comment by itskannanraj** [comment]
This does not seem fixed in the packages for Ubuntu 18.04.5 in version 1.8.3 as I still get this error?

> [OUTPUT]
    Name                           kafka
    Brokers                        hostname:9093
    Topics                         logs
    rdkafka.security.protocol      SASL_SSL
    rdkafka.sasl.mechanism         PLAIN
    rdkafka.sasl.username          username
    rdkafka.sasl.password          password
    rdkafka.ssl.ca.location        ServerCA.crt
    rdkafka.request.required.acks  0
    Match                          syslog

Error log:

> td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] cannot configure 'security.protocol' property
td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] cannot configure 'ssl.ca.location' property
td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:hostname:9093/bootstrap]: 1/1 brokers are down
td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:hostname:9093/bootstrap]: 1/1 brokers are down
td-agent-bit[8679]: [2021/08/16 12:37:25] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:hostname:9093/bootstrap]: 1/1 brokers are down

**Comment by gai6948** [comment]
> This does not seem fixed in the packages for Ubuntu 18.04.5 in version 1.8.3 as I still get this error?
> 
> > [OUTPUT]
> > Name                           kafka
> > Brokers                        hostname:9093
> > Topics                         logs
> > rdkafka.security.protocol      SASL_SSL
> > rdkafka.sasl.mechanism         PLAIN
> > rdkafka.sasl.username          username
> > rdkafka.sasl.password          password
> > rdkafka.ssl.ca.location        ServerCA.crt
> > rdkafka.request.required.acks  0
> > Match                          syslog
> 
> Error log:
> 
> > td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] cannot configure 'security.protocol' property
> > td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] cannot configure 'ssl.ca.location' property
> > td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:hostname:9093/bootstrap]: 1/1 brokers are down
> > td-agent-bit[8679]: [2021/08/16 12:37:24] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:hostname:9093/bootstrap]: 1/1 brokers are down
> > td-agent-bit[8679]: [2021/08/16 12:37:25] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:hostname:9093/bootstrap]: 1/1 brokers are down

Getting the same issue on Ubuntu 20.04.2 using package V1.8.3

```
[OUTPUT]
    name kafka
    match logs
    retry_limit 2
    format json
    brokers b-3.msk-test-cluster-1.fhov1n.c10.kafka.us-west-2.amazonaws.com:9096,b-2.msk-test-cluster-1.fhov1n.c10.kafka.us-west-2.amazonaws.com:9096,b-1.msk-test-cluster-1.fhov1n.c10.kafka.us-west-2.amazonaws.com:9096
    topics ${KAFKA_TOPIC}
    rdkafka.compression.codec snappy
    rdkafka.max.in.flight.requests.per.connection 5
    rdkafka.batch.num.messages 1000
    rdkafka.batch.size 1000000
    rdkafka.message.max.bytes 100000000
    rdkafka.enable.idempotence true
    rdkafka.client.id ${HOSTNAME}
    rdkafka.security.protocol SASL_SSL
    rdkafka.sasl.username ${KAFKA_USERNAME}
    rdkafka.sasl.password ${KAFKA_PASSWORD}
    rdkafka.sasl.mechanism SCRAM-SHA-512
```

**Comment by itskannanraj** [comment]
Fixed the issue using custom build

**Comment by kartikzheng** [comment]
> Still running into issue for v1.7.0 for Redhat / CentOS
> 
> failed to create producer: No provider for SASL mechanism GSSAPI: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN

I also encountered this mistake. Have you solved it? thank you

**Comment by patrick-stephens** [comment]
thanks @nikitka , just missing the Raspbian PR I think
