### ISSUE TITLE
TraceId, SpanId and other log record fields support in Open Telemetry output plug-in

### ISSUE THREAD

**Issue by zaq-at-varian** [fluent/fluent-bit#6323]
**Is your feature request related to a problem? Please describe.**

Fluent-bit 2.0.0 has introduced support for Open Telemetry logs, which is a welcome feature for those of us dreaming of unified approach to observability. However, with the exception of _Body_ and _Timestamp_, the first implementation doesn't allow to control the contents of any other [Log and Event Record fields](https://opentelemetry.io/docs/reference/specification/logs/data-model/#log-and-event-record-definition) defined by Open Telemetry. Most notably, dedicated handling of _TraceId_, _SpanId_, _SeverityText_ and _SeverityNumber_ is missing.

**Describe the solution you'd like**

I would like the ability to control the contents of the aforementioned fields (_TraceId_, _SpanId_, etc.) in the Open Telemetry output plug-in configuration. What I could imagine working is a syntax similar to JSON parser, where we can define _Key_ name of time attribute. For Open Telemetry output, this could like this:

```plaintext
[OUTPUT]
    Name              opentelemetry
    ...               ...      # (existing configuration options skipped for brevity)
    TraceId_Key       trace-id # Copies contents of `trace-id` from the log event map and uses it for `TraceId` field
    SpanId_Key        span-id  # Ditto, only with `SpanId`
    SeverityName_Key  severity # Ditto, only with `SeverityName`
```

By default the selected keys could be removed from the log event map.

**Describe alternatives you've considered**

There are several alternatives, though they feel a lot more complicated.

One alternative is for fluent-bit to detect the known field names in JSON and assign them automatically to appropriate Open Telemetry fields.

Another alternative is for fluent-bit to assume (via configuration or auto-detection), that the internal map has already format of the [JSON protobuf-encoded](https://opentelemetry.io/docs/reference/specification/protocol/otlp/#json-protobuf-encoding) log event and send the entire chunk without any remapping. This would give the user the ultimate control and potentially make the implementation easier.

**Additional context**

The ultimate problem we're trying to address is the ability to parse logs coming from 3rd party applications, extracting as much information as possible, and integrating them with our observability framework. The ability to assign appropriate values for trace ID, span ID, severity and other Open Telemetry fields already at the application pod boundary by using a fluent-bit side-car reduces the complexity required to manage central log collector, which otherwise would have been tasked with log rewriting.

**Comment by edsiper** [comment]
cc @Syn3rman

**Comment by Syn3rman** [comment]
Hey @zaq-at-varian I'm checking this out. If Fluent Bit adds the trace_id and other details from the log data we get from the OpenTelemetry input, does it solve your use case? The input structure should look something like [this](https://github.com/open-telemetry/opentelemetry-proto/blob/d8729d40f629dba12694b44c4c32c1eab109b00a/opentelemetry/proto/collector/logs/v1/logs_service.proto#L36) 
and a [json encoded example](https://pastebin.com/e5AgPL9k)

**Comment by zaq-at-varian** [comment]
Hi @Syn3rman, thanks for picking this up! I'm not sure if I understand the question, so let me try to paraphrase.

The use case that I described in the original post concerns solely Open Telemetry **output** plug-in. We need the ability to control the contents of _observed_time_unix_nano_, _trace_id_, _span_id_, _severity_text_ and other fields from [OTel LogRecord](https://github.com/open-telemetry/opentelemetry-proto/blob/d8729d40f629dba12694b44c4c32c1eab109b00a/opentelemetry/proto/logs/v1/logs.proto#L115) that fluent-bit is currently leaving empty when sending a log event (or so it appears from [the source code](https://github.com/fluent/fluent-bit/blob/master/plugins/out_opentelemetry/opentelemetry.c#L716)).

How the control of these fields is achieved I leave entirely up to you. If the suggestion is that we could use fluent-bit parsers and filters to "build" a structured message according to the [JSON Protobuf Encoding rules](https://opentelemetry.io/docs/reference/specification/protocol/otlp/#json-protobuf-encoding) defined by Open Telemetry, e.g.

```json
{
  "trace_id": "5B8EFFF798038103D269B633813FC60C",
  "span_id": "103D269B633813FC60C5B8EFFF798038",
  "observed_time_unix_nano": "1668440700845712",
  "body": {
    "stringMessage": "Hello World!"
   }
}
```

that will solve our problem. Though I'm not sure if that's what you have in mind.

**Comment by markuman** [comment]
Have you tried stream processing in fluent-bit and fix this with sql?

**Comment by zaq-at-varian** [comment]
Do you have a suggestion how would stream processing help? As far as I can tell, the challenge here is that the Open Telemetry output plug-in allows only to control `body` and `time_unix_nano` fields of the Open Telemetry log record before sending it (see [out_opentelemetry/opentelemetry.c](https://github.com/fluent/fluent-bit/blob/f5f408e7d20b7ef5c81c1324f1629a4ae1caaa3a/plugins/out_opentelemetry/opentelemetry.c#L772). Regardless then of the prior processing, the Open Telemetry endpoint will receive a log record without, say, `trace_id`.

**Comment by Syn3rman** [comment]
That is correct @zaq-at-varian 
It is WIP and I think [this](https://github.com/Syn3rman/fluent-bit/commit/894f90bd82b0ab1ecf70855089d852b9e8d9555c) should address your requirements.
