### ISSUE TITLE
workflows: fix PR lint action

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#6331]
New problem in CI system:

- https://github.com/fluent/fluent-bit/actions/runs/3373915181/jobs/5598975765

```
Error: .github/workflows/build-master-packages.yaml:26:14: workflow command "set-output" was deprecated. use `echo "{name}={value}" >> $GITHUB_OUTPUT` instead: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions [deprecated-commands]
   |
```

**Comment by patrick-stephens** [comment]
Duplicate of https://github.com/fluent/fluent-bit/issues/6221.

Looks like Action Lint updated to make it an error although it only highlights files changed.

**Comment by niedbalski** [comment]
Closing in favor of #6221
