### ISSUE TITLE
fluent-bit by default converts timestamp into UNIX time

### ISSUE THREAD

**Issue by AkashKrDutta** [fluent/fluent-bit#634]
I don't want the logs going out from fluentbit to have `@timestamp` field in UNIX time as per my use case. Consider the parser as: 

```
[PARSER]
        Name        syslog-rfc5424
        Format      regex
        Regex       ^\<(?<pri_syslog>[0-9]{1,5})\>1 (?<time_syslog>[^ ]+) (?<host_syslog>[^ ]+) (?<ident_syslog>[^ ]+) (?<pid_syslog>[\-0-9]+) (?:[^\:]*\:)[ ]*(?<message>.+)$
        Time_Key    time_syslog
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

```
The `@timestamp` that comes out from the logs in this case is a UNIX based time stamp (epoch time). Isn't there a provision for `@timestamp` to be a stored as a different time object?

**Comment by petrkr** [comment]
How to make this "Time_Keep" tag to be in parsed format (timestamp) and not in original String format?
