### ISSUE TITLE
Fluent-bit shutdown due to SIGSEGV signal caught

### ISSUE THREAD

**Issue by alfredwkh** [fluent/fluent-bit#6349]
**Slack**: https://app.slack.com/client/T0CSKNZLK/C0CTQGHKJ/thread/C0CTQGHKJ-1667676821.659029

**Fluent-bit**: v2.0.3

**OS Env**: Amazon Linux 2 (EC2) - AArch64

**Issue** 
After fluent-bit run for sometime, it shutdown unexpected, checking logs found details below:
...
[2022/11/05 11:21:42] [engine] caught signal (SIGSEGV)
#0  0xffff8d005160      in  sha1_block_armv8() at ???:0

**Fluent-bit conf**

[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  On
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on
    storage.path /home/tester/fluent-bit/storage
    storage.backlog.mem_limit 100M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               ms_log
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample2.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample3.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample4.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample5.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample6.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample7.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample8.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample9.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample10.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample11.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs1
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample12.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs1
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample13.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs2
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample14.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample15.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs3
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample16.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs4
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample17.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs5
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample18.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs6
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample19.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs7
    Buffer_Max_Size   1M

[INPUT]
    Name              tail
    Path              /home/tester/logs/sample20.log
    Multiline         On
    Parser_Firstline  xx-multiline
    Refresh_Interval  1
    Rotate_Wait       60
    DB                /home/tester/fluent-bit/db/fluent-bit.db
    Mem_Buf_Limit     100M
    storage.type      filesystem
    Skip_Long_Lines   On
    Tag               xx_logs8
    Buffer_Max_Size   1M

[FILTER]
    Name throttle
    Match *
    Rate 10000
    Window 100
    Interval 1s
    #Print_Status True

[OUTPUT]
    Name             es
    Match            xx_logs
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs1
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs1
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs3
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs3
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs4
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs4
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs5
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs5
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs6
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs6
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs7
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs7
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

[OUTPUT]
    Name             es
    Match            xx_logs8
    Host             ..
    Port             443
    HTTP_User        ..
    HTTP_Passwd      ..
    Index            fluent-bit
    Type             _doc
    AWS_Auth         Off
    AWS_Region       ..
    tls              On
    tls.verify       Off
    Trace_Output     Off
    Trace_Error      On
    Logstash_Format  On
    Logstash_Prefix  xx_logs8
    Buffer_Size      False
    Retry_Limit      False
    Workers          20

**Parser**

[PARSER]
    Name        zt-multiline
    Format      regex
    Regex       /(?<time>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{3})\s*(?<loglevel>[^ ]*)\s*\[(?<hostname>[^\]]*)\]\s*\[(?<appname>[a-zA-Z0-9]*),(?<traceId>[a-zA-Z0-9]*),(?<spanId>[a-zA-Z0-9]*),(?<parentId>[a-zA-Z0-9]*),(?<sampled>[a-zA-Z0-9]*)\]\s*\[(?<threadname>[a-zA-Z0-9-\s\[\]]*)\]\s*(?<message>.*)/
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S.%L

**NOTES**: I had remove other input, output as there are similar, just the path different.

**Logs**:
[fluent-bit.log](https://github.com/fluent/fluent-bit/files/9947927/fluent-bit.log)

**Comment by agup006** [comment]
Hi Alfred, could you still include the other input and outputs as a combination could be causing these

**Comment by alfredwkh** [comment]
@agup006 i had update the full fluent-bit.conf in my early comments, but for privacy i did high those credential and change the log file & tag name a bit, hope you don't mind about that

**Comment by alfredwkh** [comment]
hi @agup006 do u need any other info from my site for the investigation? do appreciate if you can share to me any info you found, as fluent-bit auto shutdown in our production environment few times per day still..

**Comment by alfredwkh** [comment]
hi @agup006 , i still facing the issues, will it be fix in the upcoming new release? any target date?
