### ISSUE TITLE
Kafka REST & ES output plugins do not format fractional seconds correctly

### ISSUE THREAD

**Issue by gasmith-nutanix** [fluent/fluent-bit#635]
The kafka REST and ES output plugins misrepresent fractional seconds, because they do not include leading zeros in the `snprintf()` call:

plugins/out_es/es.c:
```
239         len = snprintf(time_formatted + s, sizeof(time_formatted) - 1 - s,
240                        ".%" PRIu64 "Z", (uint64_t) tms.tm.tv_nsec);
```

plugins/out_kafka_rest/kafka.c:
```
134         len = snprintf(time_formatted + s, sizeof(time_formatted) - 1 - s,
135                        ".%" PRIu64 "Z", (uint64_t) tms.tm.tv_nsec);
```

**Comment by edsiper** [comment]
#636 merged in separate commits. 

fixed

**Comment by gasmith-nutanix** [comment]
Thanks! May I request that we cherry-pick these commits to the 0.13 branch?
