### ISSUE TITLE
Memory usage is continuous growing for tail input plugin and s3 and ES output plugin

### ISSUE THREAD

**Issue by atiwari-cloudera** [fluent/fluent-bit#6351]
Slack: https://app.slack.com/client/T0CSKNZLK/C0CTQGHKJ/thread/C0CTQGHKJ-1667367343.824169

Fluent-bit: v2.0.3

Env: Deployed as a daemonset on the k8 environment

Issue
Memory usage is continuously growing for the tail input plugin and s3 and ES output plugin

Configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: s3-logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    
    [SERVICE]
        flush                     1
        Log_Level                 info
        Daemon                    off
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 2020
        Parsers_File              parsers.conf
        health_check              On
        storage.path              /var/log/flb-storage/

    @INCLUDE input-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE filters.conf

  input-kubernetes.conf: |
    
    [INPUT]
      Name              tail
      Tag               kube.*
      Path              /var/log/containers/*.log
      Exclude_Path      /var/log/containers/*fluent*.log
      multiline.parser  docker, cri
      storage.type      filesystem
      Refresh_Interval  1
      Skip_Long_Lines   Off
      Mem_Buf_Limit     100M

  filters.conf: |

    [FILTER]
      Name                  kubernetes
      Match                 kube.*
      Merge_Log             On
      Labels                On
      Keep_Log              Off
      Annotations           Off
      K8S-Logging.Parser    On
      K8S-Logging.Exclude   On
    
    [FILTER]
      name                  multiline
      match                 kube.*
      multiline.key_content log
      multiline.parser      java,go,python
      Emitter_Storage.type filesystem

    [FILTER]
      Name          rewrite_tag
      Match         kube.var.log.containers.input1-**
      Rule          $kubernetes['labels']['release'] ^(.+)$ $1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         input1-**
      Rule          $kubernetes['pod_name'] ^(.+)$ input2.$TAG/$1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         input2**
      Rule          $kubernetes['container_name'] ^(.+)$ input3.$TAG/$1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         kube.var.log.containers.input4-**
      Rule          $kubernetes['labels']['job-name'] ^(.+)$ $1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         input4-**
      Rule          $kubernetes['container_name'] ^(.+)$ input5.$TAG/system-test-logs/$1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         kube.var.log.containers.input6-**
      Rule          $kubernetes['labels']['job-name'] ^(.+)$ $1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         kube.var.log.containers.input7-**
      Rule          $kubernetes['labels']['job-name'] ^(.+)$ $1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         kube.var.log.containers.input8-**
      Rule          $kubernetes['labels']['job-name'] ^(.+)$ $1 false
      Emitter_Storage.type filesystem
    
    [FILTER]
      Name          rewrite_tag
      Match         kube.var.log.containers.input9-**
      Rule          $kubernetes['labels']['job-name'] ^(.+)$ $1 false
      Emitter_Storage.type filesystem

  parsers.conf: |
    

    [PARSER]
      Name            json
      Format          json
      Time_Key        time
      Time_Format     %Y-%m-%dT%H:%M:%S

    [PARSER]
      Name            regexp
      Format          regex
      Regex           /(?<datetime>\[[0-9]+\-[0-9]+\-[0-9]+ [0-9]+:[0-9]+:[0-9]+ \+[0-9]+\]) \[[0-9]+] \[(?<loglevel>(DEBUG|ERROR))\] (?<data>.*)$/
      Time_Key        time
      Time_Format     %d/%b/%Y:%H:%M:%S

    [PARSER]
      Name            kube_regex
      Format          regex
      Regex           /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
      Time_Key        time
      Time_Format     %d/%b/%Y:%H:%M:%S %z

  output-sd.conf: |
    
    [OUTPUT]
      Name            stdout
      Match           *

  output-elasticsearch.conf: |
    
    [OUTPUT]
      Name                         s3
      Match                        input5**
      Tls                          On
      tls.verify                   Off
      bucket                       ${S3_BUCKET_NAME}
      region                       ${S3_BUCKET_REGION}
      canned_acl                   public-read
      static_file_path             true
      content_type                 text
      s3_key_format                ${S3_BASE_PATH}/$TAG[1]/cluster-log-%Y%m%d%H%M.txt
      s3_key_format_tag_delimiters .
      log_key                      log
      Retry_Limit                  10

    [OUTPUT]
      Name                         s3
      Match                        input3**
      Tls                          On
      tls.verify                   Off
      bucket                       ${S3_BUCKET_NAME}
      region                       ${S3_BUCKET_REGION}
      canned_acl                   public-read
      static_file_path             true
      content_type                 text
      s3_key_format                ${S3_BASE_PATH}/$TAG[2]/cluster-log-%Y%m%d%H%M.txt
      s3_key_format_tag_delimiters .
      log_key                      log
      Retry_Limit                  10

    [OUTPUT]
      Name                         s3
      Match                        input6-**
      Tls                          On
      tls.verify                   Off
      bucket                       ${S3_BUCKET_NAME}
      region                       ${S3_BUCKET_REGION}
      canned_acl                   public-read
      static_file_path             true
      content_type                 text
      s3_key_format                ${S3_BASE_PATH}/$TAG/cluster-log-%Y%m%d%H%M.txt
      log_key                      log
      Retry_Limit                  10

    [OUTPUT]
      Name                         s3
      Match                        input7-**
      Tls                          On
      tls.verify                   Off
      bucket                       ${S3_BUCKET_NAME}
      region                       ${S3_BUCKET_REGION}
      canned_acl                   public-read
      static_file_path             true
      content_type                 text
      store_dir                    /tmp/fluent-bit/input7-logs/
      s3_key_format                ${S3_BASE_PATH}/$TAG/cluster-log-%Y%m%d%H%M.txt
      log_key                      log
      Retry_Limit                  10

    [OUTPUT]
      Name                         s3
      Match                        input8-**
      Tls                          On
      tls.verify                   Off
      bucket                       ${S3_BUCKET_NAME}
      region                       ${S3_BUCKET_REGION}
      canned_acl                   public-read
      static_file_path             true
      content_type                 text
      s3_key_format                ${S3_BASE_PATH}/$TAG/cluster-log-%Y%m%d%H%M.txt
      log_key                      log
      Retry_Limit                  10

    [OUTPUT]
      Name                         s3
      Match                        input9-**
      Tls                          On
      tls.verify                   Off
      bucket                       ${S3_BUCKET_NAME}
      region                       ${S3_BUCKET_REGION}
      canned_acl                   public-read
      static_file_path             true
      content_type                 text
      s3_key_format                ${S3_BASE_PATH}/$TAG/cluster-log-%Y%m%d%H%M.txt
      log_key                      log
      Retry_Limit                  10

<img width="1405" alt="Screenshot 2022-11-07 at 2 51 02 PM" src="https://user-images.githubusercontent.com/110112679/200282494-bae9ab33-3b20-4d7e-a129-59e2b8d565fc.png">
<img width="1396" alt="Screenshot 2022-11-02 at 4 31 00 PM" src="https://user-images.githubusercontent.com/110112679/200282556-b8491100-2d0d-4635-b0f1-53cc3097dfcd.png">
<img width="1325" alt="Screenshot 2022-11-02 at 10 58 41 AM" src="https://user-images.githubusercontent.com/110112679/200282575-7457bf0f-0169-4e8d-b973-005309b59661.png">

**Comment by agup006** [comment]
Can you try the following combos to narrow it down

1. Only stdout
2. Only 1 filter + stdout
3. Only s3 
4. 1 filter + 1 s3

**Comment by atiwari-cloudera** [comment]
@agup006 Sure, will try those combinations and get back to you.

**Comment by atiwari-cloudera** [comment]
@agup006 
I followed the below scenarious but still seeing the same trend.

- Removed multiline filters. Executed the fluent bit with tail input, rewrite_tag filters and s3 output.
- Removed rewrite_tag filters. Executed the fluent bit with tail input, multiline filters and s3 output.
- Removed s3 output. Executed the fluent bit with tail input, rewrite_tag filters, multiline filters and stdout output.
- Removed s3 output,  rewrite_tag filters and multiline filters. Executed the fluent bit with tail input and stdout output.(Adding the graph for this)
![Uploading Screenshot 2022-11-08 at 6.32.42 PM.png…]()

**Comment by nokute78** [comment]
|Leak|in_tail|filter_k8s|filter_multiline|filter_rewrite_tag|out_s3|Note|
|---|---|---|---|---|---|---|
|Yes|✔|✔?|✔|✔|✔|Original issue|
|Yes|✔|✔?||✔|✔||
|Yes|✔|✔?|✔||✔||
|Yes|✔|✔?|✔|✔||Using out_stdout|
|Yes|✔|✔?||||Using out_stdout|

**Comment by atiwari-cloudera** [comment]
We are still seeing very high memory usage with our s3 as well as elasticsearch setup.
ES:
<img width="1406" alt="Screenshot 2022-11-15 at 1 34 56 PM" src="https://user-images.githubusercontent.com/110112679/201863741-b73f579f-b3ea-4e9b-9200-91a8bad46dbd.png">
S3:
<img width="1401" alt="Screenshot 2022-11-15 at 1 34 15 PM" src="https://user-images.githubusercontent.com/110112679/201863800-a0675976-8863-461f-987b-04a39c9be066.png">

**Comment by TomasKohout** [comment]
We have the same issue with the memory leak. We observe the issue only when `ExcludePath` in `tail` plugin is used. When it's not, memory leak is not occuring.

`tail` config with leak
```
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*_cc_*.log,/var/log/containers/*_kube-system_*.log
        Tag               kube-common.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
        Tag_Regex         (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        multiline.parser  docker, cri
        Mem_Buf_Limit     500MB
        Skip_Long_Lines   On
        Read_from_Head    False
        Refresh_Interval  5
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   100M
        DB                /var/log/fluent-bit-system.db
        DB.locking        True
        storage.type      filesystem
```

`tail` config without leak

```

    [INPUT]
        Name              tail
        Path              /var/log/containers/*_cc_*.log
        Tag               kube-common.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
        Tag_Regex         (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        multiline.parser  docker, cri
        Mem_Buf_Limit     500MB
        Skip_Long_Lines   On
        Read_from_Head    False
        Refresh_Interval  5
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   100M
        DB                /var/log/fluent-bit-cc.db
        DB.locking        True
        storage.type      filesystem
```
