### ISSUE TITLE
Systemd Node Exporter Collector

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#6360]
**Is your feature request related to a problem? Please describe.**
It is not possible to monitor crashed services with the currently exported node exporter metrics

**Describe the solution you'd like**
Support the `collectors.systemd` collector from node exporter

**Describe alternatives you've considered**
Using another agent instead of fluent-bit

**Comment by agup006** [comment]
Thanks for adding this request @braunsonm

**Comment by cosmo0920** [comment]
Already merged in https://github.com/fluent/fluent-bit/pull/7319.
