### ISSUE TITLE
fluent-bit 2.0.4 crashes on shutdown when using prometheus exporter

### ISSUE THREAD

**Issue by jefferbrecht** [fluent/fluent-bit#6367]
## Bug Report

**Describe the bug**
On Windows, when shutting down fluent-bit, the process crashes and the service does not shut down gracefully. This occurs regardless of whether fluent-bit is run standalone or as a Windows service.

**To Reproduce**
1. Start fluent-bit, e.g. `fluent-bit.exe -c fluent_bit_main.conf`
2. Stop fluent-bit e.g. with Ctrl+C

**Expected behavior**
No crashes (and a graceful service shutdown if running as a service)

**Screenshots**
Process crashes and produces an error in the Event Log. When run as a service, it additionally produces a service error:

![image](https://user-images.githubusercontent.com/89024676/200863835-bec3cfb1-c4bb-4bed-86db-52936b9c3b55.png)

```
Log Name:      Application
Source:        Application Error
Date:          11/9/2022 9:52:41 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      windows.test.example.com
Description:
Faulting application name: fluent-bit.exe, version: 2.0.4.0, time stamp: 0x6369cbd1
Faulting module name: fluent-bit.exe, version: 2.0.4.0, time stamp: 0x6369cbd1
Exception code: 0xc0000409
Fault offset: 0x0000000000590264
Faulting process id: 0x1fc8
Faulting application start time: 0x01d8f44ae45c0b6d
Faulting application path: C:\Program Files\Google\Cloud Operations\Ops Agent\bin\fluent-bit.exe
Faulting module path: C:\Program Files\Google\Cloud Operations\Ops Agent\bin\fluent-bit.exe
Report Id: 0ae1a634-d90b-4149-bb08-32930c0b762c
Faulting package full name: 
Faulting package-relative application ID: 
```

**Your Environment**

* Version used: 2.0.4
* Configuration:
  ```
  [OUTPUT]
      Match *
      Name  prometheus_exporter
      host  0.0.0.0
      port  20202
  ```
* Environment name and version (e.g. Kubernetes? What version?): Windows Server 2019
* Server type and version: Windows Server 2019
* Operating System and version: Windows Server 2019
* Filters and plugins: `prometheus_exporter`

**Additional context**
This is 100% reproducible. I have not been able to reproduce this without using `prometheus_exporter`.

The crash occurs about 2 seconds into the 5 second grace period on shutdown.

The fluent-bit log does not show anything suspect but here it is anyway:

```
[2022/11/09 09:52:30] [ info] [fluent bit] version=2.0.4, commit=abb65a1f31, pid=8136
[2022/11/09 09:52:30] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/11/09 09:52:30] [ info] [cmetrics] version=0.5.6
[2022/11/09 09:52:30] [ info] [ctraces ] version=0.2.5
[2022/11/09 09:52:30] [ info] [output:prometheus_exporter:prometheus_exporter.0] listening iface=0.0.0.0 tcp_port=20202
[2022/11/09 09:52:30] [ info] [sp] stream processor started
[2022/11/09 09:52:40] [ warn] [engine] service will shutdown in max 5 seconds
[2022/11/09 09:52:41] [ info] [engine] service has stopped (0 pending tasks)
```

**Comment by braydonk** [comment]
This was cause by my [change in monkey]() that fixed some memory leaks on shutdown. I thought I'd tested it on Windows but I was clearly mistaken. :upside_down_face: 

There is a function for freeing up server listeners in `MK_SCHEDULER_FAIR_BALANCING` mode that uses a Linux specific function to close the server socket/pipe. I opened https://github.com/monkey/monkey/issues/382 with accompanying PR to address it upstream.

**Comment by braydonk** [comment]
The fix is [merged into master](https://github.com/fluent/fluent-bit/commit/9eed4251c35881ea0507d8ff813b553c6423fb71). Not sure if that means the issue is closed or if it's closed when it's part of a release?

**Comment by jefferbrecht** [comment]
I think we can close it. Thanks for the quick fix!
