### ISSUE TITLE
Firehose and Kinesis Streams Log Duplication

### ISSUE THREAD

**Issue by matthewfala** [fluent/fluent-bit#6369]
## Firehose and Kinesis Streams Log Duplication

Firehose and Kinesis Streams plugins are prone to have some minor log duplication as documented [here](https://github.com/aws/aws-for-fluent-bit/blob/mainline/troubleshooting/debugging.md#kinesis_streams-or-kinesis_firehose-partially-succeeded-batches-or-duplicate-records)

> unfortunately Fluent Bit can sometimes upload the same record multiple times due to retries that partially succeeded. While this is a problem with Fluent Bit outputs in general, it is especially a problem for Firehose and Kinesis since their service APIs allow a request to upload data to partially succeed:
> [PutRecords](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html)
> [PutRecordBatch](https://docs.aws.amazon.com/firehose/latest/APIReference/API_PutRecordBatch.html)

>Each API accepts 500 records in a request, and some of these records may be uploaded to the stream and some may fail. As noted in the [duplication section of this guide](#throttling-log-duplication--ordering), when a chunk partially succeeds, Fluent Bit must retry the entire chunk. That retry could again fail with partial success, leading to another retry (up to your configured `Retry_Limit`). Thus, log duplication can be common with these outputs. 

>When a batch partially fails, you will get a message like:
```
[error] [output:kinesis_streams:kinesis_streams.0] 132 out of 500 records failed to be delivered, will retry this batch, {stream name}
```
>Or:
```
[error] [output:kinesis_firehose:kinesis_firehose.0] 6 out of 500 records failed to be delivered, will retry this batch, {stream name}
```
Fluent Bit should have enough information from the AWS Kinesis and Firehose [APIs](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html) to avoid sending out duplicated log data. In each API response we get an entry for each log record showing it's success status. If Fluent Bit keeps track of successful and unsuccessful records, it should be able to avoid resending the successful logs.

## Implementation Ideas
We would most likely just make a hash map with a key based on the partially failed chunk's memory address. The value would be a boolean array of true and false flags based on each records success status. Always check the hash map before sending logs and avoid sending duplicates.

We do have to consider clean up. We could probably just keep track of the retries and if we're on the last attempt, then get rid of the hash entry.

**Comment by wchaws** [comment]
And the full batch retry will make kinesis/ throttling worse because it needs more API calls to send just a batch.

**Comment by matthewfala** [comment]
Good call out @wchaws.

**Comment by wchaws** [comment]
prevent stale

**Comment by flozano** [comment]
this is still relevant
