### ISSUE TITLE
Update 2.0.X purges existing configuration (fluent-bit.conf)

### ISSUE THREAD

**Issue by LeoWinterDE** [fluent/fluent-bit#6377]
## Bug Report

**Describe the bug**
The fluent-bit update on ubuntu to version 2.0.4 again purges the existing configuration file fluent-bit.conf 😠 Just like #5377 and noted [here](https://github.com/fluent/fluent-bit/issues/6281#issuecomment-1307743657
) from @markstos

**To Reproduce**
- Update to 2.0.4 on Ubuntu from the [deb repository](https://docs.fluentbit.io/manual/installation/linux/ubuntu) -> `fluent-bit.conf` is back to default

**Expected behavior**
- fluent-bit.conf file stays the same even after updating

**Your Environment**
* Version used: 2.0.3 -> 2.0.4
* Operating System and version: Ubuntu 22.04 LTS

**Comment by markstos** [comment]
The linked comment I made clarifies that is is a Ubuntu/Debian packaging bug, not a Fluent Bit bug: 

https://github.com/fluent/fluent-bit/issues/6281#issuecomment-1307743657

**Comment by markstos** [comment]
It looks like the packages are generated with `cpack` and `cpack` needs to set CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA` and use that to define `/etc` files with `conffiles`

https://cmake.org/cmake/help/latest/cpack_gen/deb.html#variable:CPACK_DEBIAN_%3CCOMPONENT%3E_PACKAGE_CONTROL_EXTRA

**Comment by patrick-stephens** [comment]
Any chance you can submit a PR @markstos ?

**Comment by markstos** [comment]
I'm not familiar with Fluent Bit development or `.deb` packaging, so I've already used Ansible to workaround the issue by deleting the files that the package puts in `/etc` and having my `fluent-bit` service load files from a non-default location that won't be overwritten. That will address the current problem and accidental regressions in the future. So I don't plan to work on a PR. Maybe @LeoWinterDE could use the hints I've provided to dive in and try to patch this.

**Comment by nickbroon** [comment]
[17004cac4](https://github.com/fluent/fluent-bit/commit/17004cac4e973ace96f6a40557340f186ad4c43b#diff-721f00f74d57215dc3130c2b8e94535d6728ac3ab57db44990b4fb6426fce70d) which is in v2.0.0.0 removed `debian/conffiles` which cpack is configured to use:
https://github.com/fluent/fluent-bit/blob/0ed5e39147ad681d8d2b0e52344bb1253e6e1874/CMakeLists.txt#L1141

This file should probably be restored.

**Comment by nickbroon** [comment]
Running [lintian](https://lintian.debian.org/tags) on the generated .deb also reports the conffile error.

```
$ cmake -D CMAKE_INSTALL_PREFIX=/usr ../
$ make -j8
$ cpack -G DEB
$ lintian *.deb

E: fluent-bit: file-in-etc-not-marked-as-conffile etc/fluent-bit/fluent-bit.conf
E: fluent-bit: file-in-etc-not-marked-as-conffile etc/fluent-bit/parsers.conf
E: fluent-bit: file-in-etc-not-marked-as-conffile etc/fluent-bit/plugins.conf
E: fluent-bit: no-changelog usr/share/doc/fluent-bit/changelog.gz (native package)
E: fluent-bit-headers: no-changelog usr/share/doc/fluent-bit-headers/changelog.gz (native package)
E: fluent-bit-headers-extra: no-changelog usr/share/doc/fluent-bit-headers-extra/changelog.gz (native package)
E: fluent-bit: no-copyright-file
E: fluent-bit-headers: no-copyright-file
E: fluent-bit-headers-extra: no-copyright-file
E: fluent-bit: unstripped-binary-or-object lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so
E: fluent-bit: unstripped-binary-or-object usr/bin/fluent-bit
W: fluent-bit: executable-stack-in-shared-library lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so
I: fluent-bit: extended-description-is-probably-too-short
I: fluent-bit-headers: extended-description-is-probably-too-short
I: fluent-bit-headers-extra: extended-description-is-probably-too-short
I: fluent-bit: hardening-no-bindnow lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so
I: fluent-bit: hardening-no-bindnow usr/bin/fluent-bit
I: fluent-bit: hardening-no-fortify-functions lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so
I: fluent-bit: hardening-no-fortify-functions usr/bin/fluent-bit
I: fluent-bit: spelling-error-in-binary lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so "allows to" "allows one to"
I: fluent-bit: spelling-error-in-binary lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so Recieved Received
I: fluent-bit: spelling-error-in-binary lib/x86_64-linux-gnu/fluent-bit/libfluent-bit.so apEnd append
I: fluent-bit: spelling-error-in-binary ... use --no-tag-display-limit to see all (or pipe to a file/program)

```

It might be worth running lintian as part of any CI that builds/publishes the packages, to catch debian packaging errors.

**Comment by markstos** [comment]
I think you nailed it @nickbroon ! Thanks. It's hard to spot problems in mega-commits like the one you linked to.

**Comment by patrick-stephens** [comment]
Any chance someone could send a PR? I can approve it then, the lintian stuff sounds a good idea as well.

**Comment by patrick-stephens** [comment]
Thanks @nickbroon for the fix as well :+1:
