### ISSUE TITLE
Typo error in packaging/distros/debian/Dockerfile#L82

### ISSUE THREAD

**Issue by ngc703** [fluent/fluent-bit#6382]
https://github.com/fluent/fluent-bit/blob/56674a3b7b60aa2c8285eec33dc4430ce9da2ef0/packaging/distros/debian/Dockerfile#L82

i guess it should be `/opt/fluent-bit` 😉

**Comment by patrick-stephens** [comment]
Ah good catch, feel free to submit a PR.
The CI actually overrides it I think...

**Comment by patrick-stephens** [comment]
Yeah looks like it is overridden here in the builds at least: https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/.github/workflows/call-build-linux-packages.yaml#L143

We had to in the past when we were building `td-agent-bit` so this is a legacy of that which thankfully prevents a bug in the official packages!
