### ISSUE TITLE
out_stackdriver: dropped logs when access token is expired

### ISSUE THREAD

**Issue by ridwanmsharif** [fluent/fluent-bit#6393]
Currently when the access token is expired, a fluent bit out_stackdriver worker will go ahead and update it in the shared (among other workers) context. The problem is,
if other workers need to process a log entry and need to use the token while it is being updated - it will fail to acquire the mutex lock and will proceed with its cached token:
https://github.com/fluent/fluent-bit/blob/7634d9f73278e08cbbb52dc90cd34984653173db/plugins/out_stackdriver/stackdriver.c#L325-L335

This leads to issues since the token could be expired (we don't check for that since it needs the lock to check this). This causes an error when flushing:
```
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_EXPIRED",
        "domain": "googleapis.com",
        "metadata": {
          "method": "google.logging.v2.LoggingServiceV2.WriteLogEntries",
          "service": "logging.googleapis.com"
        }
      }
    ]
  }
}
```

Fluent bit recovers quickly from this problem as the other thread will update the shared context with a new token and all subsequent log entries will flush without issue.
The problem however is that the failed requests are not retried and logs are dropped as a result

Potential solutions:
1) Have the cache also store the expiration time so we can check expiration in a lockless manner. In the event that a cached token is locked, we would need to either wait for it to be updated or update it ourselves.
2) Wait on every request to get a non-expired token. This needs to be rejected since then all threads will be bottlenecked by this process.
3) Retry the logs that that happen as a result of an expired token (maybe all `401` error codes). Retries only happen 3 times so this may be a safe stop gap. Also is the easiest fix

Option 1 seems the most reasonable to me but more investigation is probably warranted.

**Comment by JeffLuoo** [comment]
I personally prefer option 3 to benefits from the existing retry feature in the Fluent Bit engine, @qingling128 Hi Ling, WDYT?

**Comment by qingling128** [comment]
I kinda like option 3.

One question:

For Ops Agent, we use `Retry_Limit 3`, so it should be fine for our cases. users that set `Retry_Limit` to `no_limits` (https://docs.fluentbit.io/manual/v/1.9-pre/administration/scheduling-and-retries#configuring-retries), would option 3 cause some endless retrying for them when a token expires and is not able to renew due to extra permission issues?
