### ISSUE TITLE
ApiVersionRequest failed for output Kafka

### ISSUE THREAD

**Issue by vikasmishra17** [fluent/fluent-bit#6399]
## Bug Report

**Describe the bug**
I have updated my Kafka version from Kafka 3.1.1  to Kafka 3.2.3 , After updating there is an error in my fluent-bit status "ApiVersionRequest failed: Local: Timed out: probably due to broker version < 0.10" , But the data flow from fluent-bit to Kafka is fine.

- Example log message if applicable:
```
{"log":"Nov 14 15:31:59 myhostname td-agent-bit[3257977]: [2022/11/14 15:31:59] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:app]: fluent-bit#producer-1: XX.XX.XX.XX:9093/1: ApiVersionRequest failed: Local: Timed out: probably due to broker version < 0.10 (see api.version.request configuration) (after 10008ms in state APIVERSION_QUERY)"}
```
```
{"log":"Nov 14 15:31:59 myhostname td-agent-bit[3257977]: [2022/11/14 15:31:59] [error] [output:kafka:kafka.1] fluent-bit#producer-2: [thrd:app]: fluent-bit#producer-2: XX.XX.XX.XX:9093/1: ApiVersionRequest failed: Local: Timed out: probably due to broker version < 0.10 (see api.version.request configuration) (after 10008ms in state APIVERSION_QUERY)"}
```

- Steps to reproduce the problem:

**Expected behavior**
As of now there is no interruption of dataflow but need to overcome this error soon.

**Your Environment**

* Version used: fluent-bit 1.8.12
* Configuration:
[INPUT]
    Name tail
    Path  /var/log/syslog
    Tag  syslog-server01
    DB  /etc/td-agent-bit/db/file_status_syslog.db
    Multiline On
    Parser_Firstline multiline
    Skip_Long_Lines Off
    Skip_Empty_Lines On
    Exclude_Path *.gz,*.zip
    DB.sync normal
    DB.locking true
    Refresh_Interval 10
    storage.type     memory
    Buffer_Chunk_Size 2MB
    Buffer_Max_Size   5MB
    Mem_Buf_Limit     512MB

[FILTER]
    Name record_modifier
    Match *
    record host.hostname ${HOSTNAME}

[OUTPUT]
    name  kafka
    match syslog-server01
    brokers XX.XX.XX.XX:9093,XX.XX.XX.XX:9093,XX.XX.XX.XX:9093
    topics Syslog
    retry_Limit false
    storage.total_limit_size 20GB
    rdkafka.request.required.acks all
    rdkafka.message.timeout.ms  0
    rdkafka.log.connection.close false
    rdkafka.queue.buffering.max.kbytes 102400

* Environment name and version (e.g. Kubernetes? What version?): Ubuntu 20.04.3 LTS
* Server type and version: Onpremise
* Operating System and version: Linux Ubuntu 20.04.3 LTS

Please help me to solve this issue.

Thanks & Regards,
Vikas Mishra.

**Comment by patrick-stephens** [comment]
1.8.12 is unsupported now, please try with the latest version to confirm if this is still an issue or resolved already.

**Comment by vikasmishra17** [comment]
Hi @patrick-stephens We also tried with fluent-bit version 1.9.6 , But the same error is coming.

**Comment by patrick-stephens** [comment]
2.0.5 is the most recent version of Fluent Bit, I would try with a 2.0 version at least as various dependencies were updated so it might have resolved this one.

Another note is that `td-agent-bit` has been deprecated since 1.9.0 and removed from 1.9.9 onwards, the correct package name to use is `fluent-bit`: https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit

**Comment by vikasmishra17** [comment]
Hi @patrick-stephens we have tried in the fluent-bit version 2.0.0 , But the error still remains the same
