### ISSUE TITLE
http input does not Deflate compressed data sent via http output

### ISSUE THREAD

**Issue by naveenkumarsp** [fluent/fluent-bit#6401]
## Bug Report

**Describe the bug**
I have been trying to receive the compressed http data and prase it using http input.  the http input is failing with the below error
`[input:http:http.0] invalid JSON message, skipping`

**Note:** We are not using forwarder as we wanted to use oauth2 based authentication for the data transfer; hence, we have used HTTP output. 
 **To Reproduce**
- Output configuration at remote end is as follows
```
    [OUTPUT]
        Name            http
        Alias           remotelogs
        Match           *
        Host            test.example.com
        Port            443
        URI             /remotelogs
        format          json
        compress        gzip
        tls             on
        tls.verify      off
```
- Input config at remote side
```
    [INPUT]
    Name http
    Tag edgelogs_edgekubeauditlogs
    Host 0.0.0.0
    Port 9880
```
**Expected behavior**

Compressed data sent from remote fluent-bit should be able to deflate at remote end and process it. 

 **Screenshots**

**Your Environment**

* Version used: 2.0.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes, - 1.23.5 [both sender and receivers]
* Server type and version:
* Operating System and version: Ubuntu 18.04
* Filters and plugins: HTTP(for both output and input)

**Additional context**

**Comment by lucasoares** [comment]
Same here. I think the HTTP input should be able to receive compressed JSON (like using gzip)
