### ISSUE TITLE
Node exporter filesystem collector

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#6412]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to monitor the disk usage of various mounts on linux like you can with the regular node_exporter. It would be good to have the `filesystem` collector

**Describe the solution you'd like**
The metrics from the `filesystem` node exporter collector

**Describe alternatives you've considered**
Deploy both fluent-bit and node-exporter and have fluent-bit scrape node-exporter for aggregation

**Comment by patrick-stephens** [comment]
I think this is probably the same as #6279

**Comment by braunsonm** [comment]
It is, my mistake. Closing in favour of that.
