### ISSUE TITLE
Add swyftlogistics logo to list of companies using fluent-bit

### ISSUE THREAD

**Issue by armujahid** [fluent/fluent-bit#6414]
>>

    If your company uses Fluent Bit and is not listed, feel free to open a GitHub issue and we will add the logo.

We at [Swyft logistics](https://swyftlogistics.com/) use fluent-bit in our multiple systems (k8s and non-k8s workloads). This unified logging layer is incredibly fast (thanks to all the awesome contributors) and it has reduced our logging complexity very much. 
![image](https://user-images.githubusercontent.com/3725386/202397307-f0957aed-92e9-4346-8319-29e57af0878f.png)
![image](https://user-images.githubusercontent.com/3725386/202397484-2f349869-10d0-447c-8243-99e83197843d.png)

**Comment by agup006** [comment]
Awesome @armujahid , Let me work with the team to add the logo to fluentbit.io

**Comment by agup006** [comment]
Thanks again @armujahid! This has been uploaded to the Fluent Bit website!!! I'd love to get a CNCF blog, use case if interested
