### ISSUE TITLE
Forward (out_forward) plugin configured with Unix_Path sends corrupt data

### ISSUE THREAD

**Issue by AaronRM** [fluent/fluent-bit#6416]
## Bug Report

**Describe the bug**
When using the [out_forward plugin](https://docs.fluentbit.io/manual/pipeline/outputs/forward) and specifying a Unix_Path, fluent-bit will send corrupt data (invalid msgpack binary) to the listening server when Workers > 1 (by default, Workers == 2).

When using Unix_Path, fluent-bit apparently only makes a single socket connection to the server and attempts to share that among multiple workers. The result is interleaved (corrupted) messages are seen in the server process.

*This issue does not repro when using TCP mode.* In TCP mode, each worker appears to make a separate connection to the server process.

**To Reproduce**
1. Run the following python script to listen for forward protocol traffic on unix socket at /tmp/fluent_listen.socket. Listener will create a new thread for each incoming connection, and report the number of records received:
``` python
#!/usr/bin/python3
import socket
import msgpack
import threading
import os

addr = '/tmp/fluent_listen.socket'
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

if os.path.exists(addr):
  os.unlink(addr)
s.bind(addr)
s.listen(1)

def receive_msgpack(connection, address):
    print("opened connection at " + str(connection))
    unpacker = msgpack.Unpacker(use_list=False, raw=False)
    while True:
        data = connection.recv(1024)
        if not data:
            break
        unpacker.feed(data)
        for unpacked in unpacker:
            print("Received " + str(len(unpacked[1])) + " records on " + str(connection))

while True:
    connection, address = s.accept()
    thread = threading.Thread(target=receive_msgpack, args=(connection,address,))
    thread.start()
```
2. Run `fluent-bit -c ./fb.conf` to send a high volume of dummy data to the listener process using the following configuration file (`fb.conf`):
```
[SERVICE]
        Flush 1
        Daemon    off
        Log_Level Info

[INPUT]
        Name  dummy
        Tag   myevent
        Dummy {"message":"The quick brown fox jumps over the lazy dog.","message2":"This is message2.","user":"somebody"}
        Rate  5000

[OUTPUT]
        Name       forward
        Match      *
        Unix_Path   /tmp/fluent_listen.socket
```

Note the following example output from the listener:
```
$ sudo ./fluent_listener.threads.unix.py
opened connection at <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aaronm/./fluent_listener.threads.unix.py", line 24, in receive_msgpack
    for unpacked in unpacker:
  File "msgpack/_unpacker.pyx", line 540, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 463, in msgpack._cmsgpack.Unpacker._unpack
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 13: invalid start byte
```

**Expected behavior**
Expected to see multiple "opened connection" lines from the listener and to only see valid data coming on each connection.

**Your Environment**

* Version used: v1.9.6
* Configuration: See Repro Steps above
* Environment name and version (e.g. Kubernetes? What version?): n/a
* Server type and version: 
* Operating System and version: Ubuntu 22.04
* Filters and plugins:

**Additional context**
We have a custom C++ application that implements a forward protocol listener and does something similar to the above python code. Fluent-bit instances with out_forward & Unix_Path are not able to send data to the application (unless Workers is explicitly set to 0 or 1) due to this issue.

**Comment by leonardo-albertovich** [comment]
Hi @AaronRM, I discovered the same thing yesterday while investigating issue #6384. We are working on a fix.

**Comment by leonardo-albertovich** [comment]
I just sent PR #6417 I'm still testing it to ensure that there are no memory leaks, file descriptor leaks or any other type of side effect but if you want to give it a try that would be great!

**Comment by AaronRM** [comment]
@leonardo-albertovich Sorry for the long delay in responding! Thank you for the fix in your previous PR.

I am trying out version 2.0.9 now and there is an improvement, but I am still observing corrupt data sent *during fluent-bit shutdown* when there are still messages buffered to send.

Taking the above example, simulate a slow reader. For example, add a one second sleep call after each batch is read:

``` python
#!/usr/bin/python3
import socket
import msgpack
import threading
import os
import time

addr = '/tmp/fluent_listen.socket'
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

if os.path.exists(addr):
  os.unlink(addr)
s.bind(addr)
s.listen(1)

def receive_msgpack(connection, address):
    print("opened connection at " + str(connection))
    unpacker = msgpack.Unpacker(use_list=False, raw=False)
    while True:
        data = connection.recv(1024)
        if not data:
            break
        unpacker.feed(data)
        for unpacked in unpacker:
            print("Received " + str(len(unpacked[1])) + " records on " + str(connection))
            time.sleep(1)

while True:
    connection, address = s.accept()
    thread = threading.Thread(target=receive_msgpack, args=(connection,address,))
    thread.start()
```

Use the same config as above, but increase the rate to 100000:

```
[SERVICE]
        Flush 1
        Daemon    off
        Log_Level Info

[INPUT]
        Name  dummy
        Tag   myevent
        Dummy {"message":"The quick brown fox jumps over the lazy dog.","message2":"This is message2.","user":"somebody"}
        Rate  100000

[OUTPUT]
        Name       forward
        Match      *
        Unix_Path   /tmp/fluent_listen.socket
```

Let it run for a minute or so to allow data to buffer in fluent-bit, then `CTRL+C` to shutdown fluent-bit and observe the following:

1. Fluent-bit reports there are still many tasks running. E.g.:
```
[2023/02/16 14:09:03] [ info] [task]   task_id=189 still running on route(s): forward/forward.0
[2023/02/16 14:09:03] [ info] [task]   task_id=403 still running on route(s): forward/forward.0
[2023/02/16 14:09:03] [ info] [task]   task_id=404 still running on route(s): forward/forward.0
[2023/02/16 14:09:03] [ info] [task]   task_id=405 still running on route(s): forward/forward.0
...
```
2. In the listener process, we then observe an exception like the following indicating the listener received corrupt msgpack data:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./fluentListener.py", line 25, in receive_msgpack
    for unpacked in unpacker:
  File "msgpack/_unpacker.pyx", line 540, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 463, in msgpack._cmsgpack.Unpacker._unpack
ValueError: int is not allowed for map key when strict_map_key=True
```
3. In the listener process, we then observe fluent-bit opening a new connection (to replace the previous crashed connection) which then receives much larger (apparently corrupt?) batches:

opened connection at <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>
**Received 2048087 records on <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>**
Received 19141 records on <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>
**Received 2048087 records on <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>**
Received 937427 records on <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>
**Received 2048087 records on <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>**
**Received 2048087 records on <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>**
**Received 2048087 records on <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=/tmp/fluent_listen.socket>**

Prior to shutdown, each connection received batches of approx. 20000 records at a time whereas our listener then reports receiving 2048087 records at a time.

If you would like, I can create a new issue to track if you think this is unrelated.
