### ISSUE TITLE
tls.verify option for es plugin has no effect

### ISSUE THREAD

**Issue by dgrittma** [fluent/fluent-bit#6431]
## Bug Report

**Describe the bug**
Attempting to connect to a locally signed instance of elastic with haproxy running in front, using port 443. Other tools, such as metricbeats, are able to connect right now, as long as we disable ssl verification

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2022/11/21 11:57:45] [error] [tls] error: error:00000005:lib(0):func(0):DH lib
[2022/11/21 11:57:45] [error] [C:\projects\fluent-bit-2e87g\src\flb_http_client.c:1199 errno=0] No error
[2022/11/21 11:57:45] [ warn] [engine] failed to flush chunk '10444-1669053464.744281300.flb', retry in 11 seconds: task_id=1, input=winlog.0 > output=es.0 (out_id=0)
```
- Steps to reproduce the problem:

**Expected behavior**
Allow connection even with TLS mismatch

**Your Environment**

* Version used: Fluentbit version=1.9.8, commit=97a5e9dcf3
* Configuration:
 [OUTPUT]
    Name  es
    Match *
    Host  https://elastic.apps.contoso.local
    Port  443
    HTTP_User  elastic
    HTTP_Passwd  <pwd>
    tls  On
    tls.verify  Off
    tls.debug  4
    Index auth_test
    Type  my_type
* Environment name and version (e.g. Kubernetes? What version?):
* Operating System and version:  windows server 2019
* Filters and plugins: es

**Comment by agup006** [comment]
Hmm I wonder if this is orthogonal to tls.verify / would you be able to try with the latest 2.0.5? I saw another issue that had a similar TLS error

**Comment by agup006** [comment]
Not directly related, but perhaps this PR might help here too? @dgrittma can you build a version and test with 
 that PR? https://github.com/fluent/fluent-bit/issues/6418#issuecomment-1320419732

**Comment by dgrittma** [comment]
> Hmm I wonder if this is orthogonal to tls.verify / would you be able to try with the latest 2.0.5? I saw another issue that had a similar TLS error

I'm trying to download the latest 2.0.5 release, but the downloads aren't showing for windows, is the download link broken right now?

**Comment by nokute78** [comment]
Peer may send unexpected EOF.

```
[2022/11/21 11:57:45] [error] [tls] error: error:00000005:lib(0):func(0):DH lib
[2022/11/21 11:57:45] [error] [C:\projects\fluent-bit-2e87g\src\flb_http_client.c:1199 errno=0] No error
```
It means tls error is `SSL_ERROR_SYSCALL` (=5) and errno is 0.
https://github.com/fluent/fluent-bit/blob/v2.0.6/src/tls/openssl.c#L540

**Comment by agup006** [comment]
Thanks @nokute78 , lets aim for this in next 2.0.x release

**Comment by leonardo-albertovich** [comment]
I just verified this and what I found was that : 

1. The TLS verification setting does work as intended both on 1.9.8 and master
2. I could not get fluent-bit to accept the pattern used in the example for the `Host` setting. I could get it to work both with hostnames and IP addresses but not with a URL.

When TLS verification is enabled but the check fails, fluent-bit does print an ambiguous message reporting an unexpected EOF which we should improve but the feature does work as intended.

Note: There is a function named `flb_upstream_create_url` which creates an upstream from a URL but at least in 1.9.8 it's not widely used, in fact, it's only used by `stackdriver`, `bigquery`, `nightfall`, `azure_blob` and the `oauth2` provider so I'm confused. Could you please clarify that about your configuration @dgrittma?
