### ISSUE TITLE
Custom parser throws not registered error.

### ISSUE THREAD

**Issue by venkat-rafay** [fluent/fluent-bit#644]
# Error
`[2018/06/16 07:50:04] [error] [in_tail] parser 'log-custom' is not registered`

# Conf
```
[INPUT]
    Name     tail
    Parser    jmeter-custom
    Path       results/out.log

[OUTPUT]
    Name   stdout
    Match  *

[FILTER]
    Name   grep
    Match  *
    Regex  log summary
```

# parsers.conf
```
[PARSER]
    Name   jmeter-custom
    Format regex
    Regex  ^(?<date>[^ ]*)[ ]*(?<time>[^ ]*)[ ]*(?<level>[A-Z]*)[ ]*(?<info>[\D:]*)[ ]*(summary)[ ]*(?<operator>[+|=])[ ]*(?<count>[\d]*)[ ]*(in)[ ]*(?<elapsed_time>[^\ ]*)[ ]*(=)[ ]*(?<threads_per_sec>[\d+(\.\d+)?]*(\/s))[ ]*(Avg:)[ ]*(?<average_calls>[\d+(\.\d+)?]*)[\s\S]*(Err:)[ ]*(?<error_count>[\d+(\.\d+)?]*)[ ]*[\(](?<error_rate>[\d+(\.\d+)?]*)[%][\s\S]*$
```
Rubular link: http://rubular.com/r/FEqvZCz5C7

Rubular validates the regex without errors. But td-agent-bit throws an error saying parser isn't registered.

**Comment by nokute78** [comment]
Can you modify parsers.conf? 
`jmeter-custom` -> `log-custom`.

**Comment by venkat-rafay** [comment]
@nokute78 I changed it while uploading to github. Both my conf files contain jmeter-custom. Fixed the issue description. Issue exists even when both the names are consistent.

**Comment by nokute78** [comment]
@venkat-rafay Oops.
Can you add `[SERVICE]` section to configuration file?
It needs to indicate the path of parsers.conf.
See also: https://fluentbit.io/documentation/0.13/configuration/file.html

```python
[SERVICE]
    # Parsers_File
    # ============
    # Specify an optional 'Parsers' configuration file
    Parsers_File /path/to/parsers.conf
```

**Comment by venkat-rafay** [comment]
@nokute78  I append my config to the parsers.conf file present in `etc/td-agent-bit` and run the td-agent-bit with ` -P /etc/td-agent-bit/parsers.conf`
