### ISSUE TITLE
Forwarding OpenTelemetry Traces to Tempo

### ISSUE THREAD

**Issue by cbi-at-varian** [fluent/fluent-bit#6441]
## Bug Report

**Describe the bug**
Traces do not arrive at Tempo, when forwarding opentelemetry traces via fluentbit.
Using http/protobuf format and opentelemetry input and opentelemetry output plugin

**To Reproduce**
basic setup and description to reproduce provided here: https://github.com/cbi-at-varian/otlp-forwarding

**Expected behavior**
When using Fluentbit as a trace forwarded, traces should arrive at tempo the same way as I would write them directly to tempo.

**Your Environment**

* Version used: Fluent Bit v2.0.5
* Configuration:
 [INPUT]
    Name             opentelemetry
    raw_traces      false
    host               127.0.0.0
    port               4318

[OUTPUT]
    name                    opentelemetry
    match                   *
    host                      tempo
    port                      4318
    Traces_uri              /v1/traces
    log_response_payload    true
    add_label             app fluent-bit

**Additional context**
We are using fluentbit as a log forwarder in an heterogeneous system, with the support of opentelemetry in v2 we would like to use the existing forwarding infrastructure not only for logs but for traces too.
With reusing the existing infrastructure we could save resources and we wouldn't have to implement another infrastructure for traces.

**Comment by tcinbis** [comment]
Maybe related? #6323
