### ISSUE TITLE
Float numbers in JSON stdout and http output plugin misformatted

### ISSUE THREAD

**Issue by jennuineness** [fluent/fluent-bit#6447]
## Bug Report

**Describe the bug**
Hi, I noticed certain float numbers such as 0.072 in a JSON data structure is being rewritten as 0.07199999999999999 when using the `Format json` option for the [stdout](https://docs.fluentbit.io/manual/v/1.3/output/stdout) and [http](https://docs.fluentbit.io/manual/v/1.3/output/http) output plugin.

I am sending out logs to a service that only accepts numbers with Decimal positions to be less than 16 digits. I am unable to find a way to preserve the number as-is when using the `Format json` option through the output plugins. 

Any help with a fix/workaround is much appreciated!

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"test": 0.072}
```
- Steps to reproduce the problem:

**tail.conf**
```
[SERVICE]
    Parsers_File parsers.conf
    Flush 0.1

[INPUT]
    Name            tail
    Path              /test.log
    Parser json

[OUTPUT]
    Name stdout
    Match *
    Format json
    json_date_key false
```

**parsers.conf**
```
[PARSER]
    Name   json
    Format json
```

**test.log**
```
{"test": 0.072}
```

1. Setup environment with files listed above.
2. Run following command in terminal where tail.conf is located: `fluent-bit -c tail.conf`
3. Run the following command in a new terminal where test.log is located: `echo '{"test": 0.072}' >> test.log` 

**Expected behavior**
Expect output to be `[{"test":0.072}]` instead of `[{"test":0.07199999999999999}]`.

**Your Environment**

* Version used: Fluent Bit v2.0.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: MacOS Monterey v12.6
* Filters and plugins: tail Input plugin, JSON parser plugin, stdout Output plugin, and HTTP Output plugin

**Additional context**

Possibly, allow an option to preserve the number types without being reformatted when parsing.

**Comment by nokute78** [comment]
Note: The issue is related `%.16g`.
https://github.com/fluent/fluent-bit/blob/v2.0.6/src/flb_pack.c#L596

```c
#include <stdio.h>
#include <stdlib.h>

int main() {
  char *a = "0.072";
  double val = atof(a); 

  printf("%lf, %.16g\n", val, val);
  return 0;
}
```

```
$ ./a.out 
0.072000, 0.07199999999999999
```

Related PR:
https://github.com/fluent/fluent-bit/pull/1439
https://github.com/fluent/fluent-bit/pull/2592

**Comment by vitaly-sinev** [comment]
This is still reproducible on current `master` — the `Format json` path in `flb_pack.c` still uses `%.16g`, so `0.072` serializes as `0.07199999999999999`.

I've opened #12129 with a fix: a shared `flb_pack_double_to_str()` helper that uses the already-vendored yyjson dtoa to emit the **shortest decimal string that round-trips back to the same double** (so `0.072` → `"0.072"`), while still guaranteeing round-trip precision (unlike a plain `%.15g`). Non-finite values keep their previous formatting.

Could a maintainer please reopen this issue? Thanks to @nokute78 for pinpointing the `%.16g` root cause.
