### ISSUE TITLE
Hi, not support in_http right now？

### ISSUE THREAD

**Issue by felixzh2015** [fluent/fluent-bit#645]
![360 20180616174654617](https://user-images.githubusercontent.com/16359007/41497718-6f4e4b36-718d-11e8-9096-0712ace54971.jpg)

I change No to Yes. And make cmd get error as follows:
Scanning dependencies of target flb-plugin-in_http
[ 79%] Building C object plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/in_http.c.o
In file included from /home/fluent-bit-0.13.3/lib/monkey/include/monkey/mk_socket.h:32:0,
                 from /home/fluent-bit-0.13.3/lib/monkey/include/monkey/mk_server.h:24,
                 from /home/fluent-bit-0.13.3/lib/monkey/include/monkey/monkey.h:43,
                 from /home/fluent-bit-0.13.3/plugins/in_http/in_http.c:20:
/home/fluent-bit-0.13.3/lib/monkey/include/monkey/mk_config.h:26:28: fatal error: monkey/mk_info.h: No such file or directory
 #include <monkey/mk_info.h>
                            ^
compilation terminated.
make[2]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/in_http.c.o] Error 1
make[1]: *** [plugins/in_http/CMakeFiles/flb-plugin-in_http.dir/all] Error 2
make: *** [all] Error 2

**Comment by felixzh2015** [comment]
@repeatedly

**Comment by felixzh2015** [comment]
@michiel @frsyuki @mikekap @komamitsu

**Comment by michiel** [comment]
@felixzh2015 I haven't worked on this but it looks like it's still in development stage at the moment. I assume that's why it's disabled by default. See also #18

**Comment by felixzh2015** [comment]
@mikekap 
 I get it, thanks.
