### ISSUE TITLE
Occasional segmentation fault in out_kafka

### ISSUE THREAD

**Issue by qbx2** [fluent/fluent-bit#6451]
## Bug Report

**Describe the bug**
Segmentation fault is caused occasionally. Actually, I did core file analysis using gdb and identified how to fix. I'll submit a PR soon.

Stacktrace:

```
Nov 23, 2022 @ 00:53:23.362 | [2022/11/22 15:53:23] [engine] caught signal (SIGSEGV)
-- | --

  | Nov 23, 2022 @ 00:53:23.473 | #0  0xaaaad87abb10      in  produce_message() at plugins/out_kafka/kafka.c:189

  | Nov 23, 2022 @ 00:53:23.473 | #1  0xaaaad87ac50b      in  cb_kafka_flush() at plugins/out_kafka/kafka.c:483

  | Nov 23, 2022 @ 00:53:23.473 | #2  0xaaaad84a4a17      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:519

  | Nov 23, 2022 @ 00:53:23.473 | #3  0xaaaad8ede3fb      in  co_switch() at lib/monkey/deps/flb_libco/aarch64.c:133

  | Nov 23, 2022 @ 00:53:23.473 | #4  0xffffffffffffffff  in  ???() at ???:0
```

**To Reproduce**
I don't know how to reproduce. I tried to input the same message, but it did not crash.

**Expected behavior**
It should not happen.

**Your Environment**
* Version used: fluent-bit:2.0.3-debug (https://hub.docker.com/layers/fluent/fluent-bit/2.0.3-debug/images/sha256-16b44e6a80ef583e780889bc05de0c18aa556243d0c863d0d4fddfd32a89f600?context=explore)
* Configuration: in_tail / filter_modify / out_kafka
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.22, attached to a pod as sidecar
* Server type and version: kafka
* Operating System and version: bottlerocket 1.9.2 on arm64
* Filters and plugins: filter_modify / out_kafka

**Comment by agup006** [comment]
@qbx2 do you have a copy of the configuration?
