### ISSUE TITLE
metrics: let plugins expose their own metrics

### ISSUE THREAD

**Issue by chlunde** [fluent/fluent-bit#647]
I would like to detect if fluent-bit is keeping up with the new data coming in.  This could happen if one application is logging in a tight loop, throttling inside fluent-bit or CPU-throttling in Kubernetes/cgroups.

I think this should be exposed via metrics to be out of band from normal logging.

Do you think this is a good idea?  I can implement this.

Questions:
- Current counters are `_total` in prometheus.  pending bytes should not have such a ending.  Should we rename the counters in the code where they are defined, or add a type field (complicated?)
- How frequent should we update?
- Should we have a both a `pending_bytes` counter and `pending_files`/`active_files`?

**Comment by edsiper** [comment]
so this is likely related to the feature to expose specific plugin metrics (which are different than engine metrics), that feature is not exposed yet but I think is something that needs to be implemented.

I will set this ticket as an enhancement request.

**Comment by edsiper** [comment]
fluent bit and components already exposes it own metrics. closing as fixed.
