### ISSUE TITLE
Logs that are saved to buffer when Output becomes unavailable, are lost when Output becomes available again

### ISSUE THREAD

**Issue by kealanodoherty** [fluent/fluent-bit#6470]
## Bug Report

**Describe the bug**
We currently have Fluent Bit agents set up on our microservices, that push logs to a central application called “Logship”. This application has FluentD running on it, that takes in these logs and stores them in a file share.
In the event of an outage, say for example the “Logship” application goes offline, or there are network issues, such that logs cannot reach FluentD, we want to ensure any logs being sent during the outage are picked up once FluentD becomes available again. We’ve tried various different buffer config settings to implement this but in each case we are losing all the logs sent during an outage.

**To Reproduce**
[FluentD_and_FluentBit_Config_Files.zip](https://github.com/fluent/fluent-bit/files/10105757/FluentD_and_FluentBit_Config_Files.zip)
td-agent.conf and td-agent-bit.conf files included in Zip File.

1. Stop td-agent service on the VMs running FluentD (In our case, the "Logship" Application)
2. The applications running Fluent Bit should now begin saving chunks to the buffer location, as it has detected that the Output is unavailable
3. After a while (a few minutes or a few hours), start the td-agent service again
4. On the VMs running Fluent D, notice how logs from the outage period were not received.

**Expected behavior**
It is expected that when FluentD is running again, all logs that have built up in the buffer on the applications running Fluent Bit will be flushed and sent to the "Logship" application. 

**Your Environment**
* Version used: td-agent-4.3.0, td-agent-bit-1.8.12
* OS: Centos 7
* Configuration: 
 
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
It's vital for us to have no log loss, even in the event of an outage. We need any logs during the outage to be stored until they are able to be received by FluentD.
In the td-agent-bit.conf file, for Storage.type, we have tried both memory and file, with no success with either.
Other than during an outage, everything works fine, we do not experience any log loss once both FluentD and FLuentBit are running.

**Comment by kealanodoherty** [comment]
For context:
td-agent-bit.conf (comments removed):

[SERVICE]
    flush        5
    daemon       Off
    log_level    trace
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on
    storage.path /data/buffer/
    storage.sync full
    storage.checksum on
    storage.backlog.mem_limit 10M

[INPUT]
    name tail
    path /var/log/sensu/*sensu-go-agent.log
    path_key log_file
    tag i2.6y.dep.${HOSTNAME}.<filename>
    tag_regex (\/.*\/)(?<filename>.+)
    Storage.type memory
    DB /data/buffer/tail-0.db
    DB.locking true
    #Read_from_Head True
    DB.journal_mode WAL

[OUTPUT]
    Name forward
    Match *
    Host ie2-logship-nxt.nxt.betfair
    Port 80
    Compress gzip
    Require_ack_response True

-----------------------------------------------------------------------

td-agent.conf

<system>
    workers 1
    rpc_endpoint 0.0.0.0:24724
    log_level trace
</system>

<source>
    @type forward
    port 24224
    @id forward
</source>

<match i2**>
    @type file
    @id file
    compress gzip
    path /data/${tag[1]}/%Y/%m/%d/${tag[2]}/${tag[3]}.${tag[4]}.${tag[5]}-${tag[6]}_%Y%m%d_01a
    append
    <buffer tag,time>
        @type memory
        flush_thread_count 8
        chunk_limit_size 8M
        queue_limit_length 64
        retry_max_interval 30
        retry_max_times 1000
        flush_mode interval
        flush_interval 20s
    </buffer>
    <format>
        @type single_value
        message_key log
    </format>
</match>

<source>
@type monitor_agent
bind 0.0.0.0
port 24220
@id monitor_agent
</source>

**Comment by lecaros** [comment]
Hi @kealanodoherty 
You have `storage.type memory`, it means that you'll lose in-transit records upon restart. If you want to accomplish what you described, you must set `storage.type filesystem`.
Also, it would be best if you upgrade to a newer version, either 2.x or 1.9.

Regards

**Comment by kealanodoherty** [comment]
Hi Lecaros,
I've tried the filesystem storage.type as well but with no luck. I'll try upgrading to a newer version though, thanks for the heads up. I'll let you know how it goes.
Kealan

**Comment by patrick-stephens** [comment]
Note td-agent-bit is no longer built so latest versions require you use `fluent-bit`.

https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit

**Comment by lecaros** [comment]
@kealanodoherty, which version are you running now?
Can you share the config and Fluent-Bit log file?

**Comment by kealanodoherty** [comment]
[TDAgent-TDAgentBit-Config-and-Logs.zip](https://github.com/fluent/fluent-bit/files/10155216/TDAgent-TDAgentBit-Config-and-Logs.zip)
You should be able to view the td-agent.conf file, the td-agent-bit.conf file, and a sample of fluent bit logs from when I have simulated an outage on FluentD
