### ISSUE TITLE
Add preserve_raw to Syslog

### ISSUE THREAD

**Issue by agup006** [fluent/fluent-bit#6476]
When capturing syslog messages  I would also like to keep the raw message of the syslog message in a separate field, instead of the message being fully parsed.

This would similar to a parser filter that can preserve the raw record: https://docs.fluentbit.io/manual/pipeline/filters/parser

Configuration options:

```
# whether to keep the raw message of syslog, unparsed
preserve_raw on
# what field to put the raw message under
preserve_raw_key log
```

**Comment by edsiper** [comment]
@agup006 similar to what you proposed, would the single config option work ? , e.g: `message_raw_key` ? if set, the raw message is stored on the key mentioned, e.g:

```
message_raw_key ABC
```

so it becomes:

```json
{"pri": "1", "time": "12345", "host": "localhost", "ABC": "myrawmessage"}
```

**Comment by agup006** [comment]
Ah yes that works better, and is simpler to configure

**Comment by edsiper** [comment]
fixed in https://github.com/fluent/fluent-bit/pull/6481
