### ISSUE TITLE
2.0.x, Segfault on Connection Timed Out

### ISSUE THREAD

**Issue by matthewfala** [fluent/fluent-bit#6490]
## 2.0.x Segfault on Connection Timed Out
I'm not sure if this was resolved in the latest Fluent Bit 2.0.x releases but a series of long running tests on 2.0.5 revealed a segfault that happens around every 100h of testing when using async networking along with the CloudWatch plugin. (We used this PR to test async networking in CloudWatch on 2.0.5 [pr](https://github.com/fluent/fluent-bit/pull/6413) which was since merged into 2.0.6)

This segfault did not occur in 1.9.9 with CloudWatch when used with [async networking](https://github.com/fluent/fluent-bit/pull/6339) or 1.9.10.

2.0.6 was not stability tested, so this issue may have been recently fixed.

It appears that every time a connection timeout occurs there is a segfault.

## Description of Test
- Start 100 ECS tasks with aws-for-fluent-bit running in one container and a load testing "firelens-datajet" app as a second container.
- Wait 17hours
- Count how many tasks are alive
- Check logs of dead tasks for segfault messages

## Test Results
- After 17 hours, 83/100 tasks remain (17 tasks die).
- Check logs of dead tasks:
Error logs are similar. Here are how the tasks end:
```
2022-11-15T05:02:26.749-08:00    [2022/11/15 13:02:26] [ info] [engine] flush chunk '1-1668517309.219438680.flb' succeeded at retry 1: task_id=0, input=tcp.0 > output=cloudwatch_logs.0 (out_id=0)
    2022-11-15T06:04:08.999-08:00    [2022/11/15 14:04:08] [error] [upstream] connection #107 to tcp://52.46.216.63:443 timed out after 10 seconds (connection timeout)
    2022-11-15T06:04:08.999-08:00    [2022/11/15 14:04:08] [engine] caught signal (SIGSEGV)
```
```
2022-11-15T01:35:25.645-08:00    [2022/11/15 09:35:25] [error] [tls] error: error:00000005:lib(0):func(0):DH lib
    2022-11-15T01:35:25.645-08:00    [2022/11/15 09:35:25] [error] [/tmp/fluent-bit-1.9.9/src/flb_http_client.c:1201 errno=25] Inappropriate ioctl for device
    2022-11-15T01:43:51.948-08:00    [2022/11/15 09:43:51] [engine] caught signal (SIGSEGV)
    2022-11-15T01:43:51.948-08:00    [2022/11/15 09:43:51] [error] [upstream] connection #104 to tcp://52.119.171.221:443 timed out after 10 seconds (connection timeout)
```
```
    [2022/11/15 06:23:02] [ warn] [engine] failed to flush chunk '1-1668493376.329779199.flb', retry in 10 seconds: task_id=7, input=tcp.2 > output=cloudwatch_logs.2 (out_id=2)
    2022-11-14T22:23:02.997-08:00    [2022/11/15 06:23:02] [error] [output:cloudwatch_logs:cloudwatch_logs.2] Failed to send events
    2022-11-14T22:23:13.188-08:00    [2022/11/15 06:23:13] [ info] [engine] flush chunk '1-1668493376.329779199.flb' succeeded at retry 1: task_id=7, input=tcp.2 > output=cloudwatch_logs.2 (out_id=2)
    2022-11-14T22:23:53.174-08:00    [2022/11/15 06:23:53] [2022/11/15 06:23:53] [error] [upstream] connection #105 to tcp://52.119.174.206:443 timed out after 10 seconds (connection timeout)
    2022-11-14T22:23:53.174-08:00    [engine] caught signal (SIGSEGV)
```

## Stability Score
With (17%) of tasks fail after 17 hours, we have an expected time to failure of 100hours. So Fluent Bit has an expected stability of **100hours** under high throughput.

## Test Configuration
Task Configuration

Fluent Bit Configuration
```
[SERVICE]
     # See:
     # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_firelens.html
     # https://github.com/aws-samples/amazon-ecs-firelens-under-the-hood/tree/master/generated-configs/fluent-bit
     Flush        10
     Grace        30
     Log_Level    info
     HTTP_Server  On
     HTTP_Listen  0.0.0.0
     HTTP_PORT    2020
     storage.metrics On
[INPUT]
     Name        tcp
     Tag         TCP_A
     Listen      0.0.0.0
     Port        6270
     Format      json
[INPUT]
     Name        tcp
     Tag         TCP_B
     Listen      0.0.0.0
     Port        6271
     Format      json
[INPUT]
     Name        tcp
     Tag         TCP_C
     Listen      0.0.0.0
     Port        6272
     Format      json
[INPUT]
     Name        tcp
     Tag         TCP_D
     Listen      0.0.0.0
     Port        6273
     Format      json
[OUTPUT]
     Name cloudwatch_logs
     Match TCP_A
     log_stream_prefix TCP_A
     log_group_name ${RAND}
     auto_create_group true
     region us-west-2
     log_key log
     workers 1
[OUTPUT]
     Name cloudwatch_logs
     Match TCP_B
     log_stream_prefix TCP_B
     log_group_name ${RAND}
     auto_create_group true
     region us-west-2
     log_key log
     workers 1
[OUTPUT]
     Name cloudwatch_logs
     Match TCP_C
     log_stream_prefix TCP_C
     log_group_name ${RAND}
     auto_create_group true
     region us-west-2
     log_key log
     workers 1
[OUTPUT]
     Name cloudwatch_logs
     Match TCP_D
     log_stream_prefix TCP_D
     log_group_name ${RAND}
     auto_create_group true
     region us-west-2
     log_key log
     workers 1
```

FireLens Datajet Configuration
([FireLens Datajet](https://github.com/aws/firelens-datajet/tree/0.2) routes test data flexibly to fluent bit for load testing & fuzzing)
- 8000 logs per second split between 4 tcp inputs
- 200 byte logs

```
  {
      "component": "synchronizer",
      "config": {
          "repeat": 100,
          "waitBefore": 5,
          "waitAfter": 10,
          "waitBetween": 0,
          "isAsync": true
      },
      "children": [
          {
              "generator": {
                  "name": "basic",
                  "config": {
                      "contentLength": 200,
                      "batchSize": 2000,
                      "key": "log"
                  }
              },
              "datajet": {
                  "name": "tcp",
                  "config": {
                      "host": "0.0.0.0",
                      "port": 6270
                  }
                  },
              "stage": {
                  "batchRate": 1,
                  "maxBatches": 1000000
              }
          },
          {
              "generator": {
                  "name": "basic",
                  "config": {
                      "contentLength": 200,
                      "batchSize": 2000,
                      "key": "log"
                  }
              },
              "datajet": {
                  "name": "tcp",
                  "config": {
                      "host": "0.0.0.0",
                      "port": 6271,
                      "key": "log"
                  }
                  },
              "stage": {
                  "batchRate": 1,
                  "maxBatches": 1000000
              }
          },
          {
              "generator": {
                  "name": "basic",
                  "config": {
                      "contentLength": 200,
                      "batchSize": 2000,
                      "key": "log"
                  }
              },
              "datajet": {
                  "name": "tcp",
                  "config": {
                      "host": "0.0.0.0",
                      "port": 6272
                  }
                  },
              "stage": {
                  "batchRate": 1,
                  "maxBatches": 1000000
              }
          },
          {
              "generator": {
                  "name": "basic",
                  "config": {
                      "contentLength": 200,
                      "batchSize": 2000,
                      "key": "log"
                  }
              },
              "datajet": {
                  "name": "tcp",
                  "config": {
                      "host": "0.0.0.0",
                      "port": 6273
                  }
                  },
              "stage": {
                  "batchRate": 1,
                  "maxBatches": 1000000
              }
          }
      ]
  }
```

**Comment by nokute78** [comment]
Are there any backtraces ?

Note:
```
2022-11-15T01:35:25.645-08:00    [2022/11/15 09:35:25] [error] [tls] error: error:00000005:lib(0):func(0):DH lib
    2022-11-15T01:35:25.645-08:00    [2022/11/15 09:35:25] [error] [/tmp/fluent-bit-1.9.9/src/flb_http_client.c:1201 errno=25] Inappropriate ioctl for device
    2022-11-15T01:43:51.948-08:00    [2022/11/15 09:43:51] [engine] caught signal (SIGSEGV)
    2022-11-15T01:43:51.948-08:00    [2022/11/15 09:43:51] [error] [upstream] connection #104 to tcp://52.119.171.221:443 timed out after 10 seconds (connection timeout)
```
This may be same issue.
https://github.com/fluent/fluent-bit/issues/5705

**Comment by matthewfala** [comment]
@nokute78 I believe that these issues are different. The 5705 issue is the Fluent Bit hang problem which affected cloudwatch. It should be resolved by this pr: 
https://github.com/fluent/fluent-bit/pull/6339

**Comment by matthewfala** [comment]
No backtraces yet

**Comment by gwny** [comment]
I have the same problem in v2.0.5, and the stacktrace like below:
<code>
#1  0x560146534e9b      in  tls_net_handshake() at src/tls/openssl.c:505  
#2  0x5601465359f7      in  flb_tls_session_create() at src/tls/flb_tls.c:443
#3  0x56014656aa67      in  flb_io_net_connect() at src/flb_io.c:162
#4  0x5601464e6206      in  create_conn() at src/flb_upstream.c:533
#5  0x5601464e6714      in  flb_upstream_conn_get() at src/flb_upstream.c:682
#6  0x560146786727      in  cb_forward_flush() at plugins/out_forward/forward.c:1325
#7  0x5601464abda0      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:519
#8  0x560146edbe46      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
<code>

sometimes,  the stacktrace like below:
<code>
#1  0x55aba4462ec7      in  tls_net_handshake() at src/tls/openssl.c:509
#2  0x55aba44639f7      in  flb_tls_session_create() at src/tls/flb_tls.c:443
#3  0x55aba4498a67      in  flb_io_net_connect() at src/flb_io.c:162
#4  0x55aba4414206      in  create_conn() at src/flb_upstream.c:533
#5  0x55aba4414714      in  flb_upstream_conn_get() at src/flb_upstream.c:682
#6  0x55aba46b4727      in  cb_forward_flush() at plugins/out_forward/forward.c:1325
#7  0x55aba43d9da0      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:519
#8  0x55aba4e09e46      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
<code>

different line in `tls_net_handshake() at src/tls/openssl.c`, one in line 505 and the other in line 509.

**Comment by gwny** [comment]
The problem seems to be caused by using memory that has already been freed.
During the handshake of the tls connection, the co-routine will yield back to engine and waiting for the next execution, the related code is [https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/flb_tls.c#L513](https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/flb_tls.c#L513).
If the connection timeout occurs before the tls handshake co-routine resumed, it will destroy the connection and free some memory.
[https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/flb_upstream.c#L850](https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/flb_upstream.c#L850)
[https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/flb_tls.c#L549](https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/flb_tls.c#L549)
When the tls handshake co-routine resumed, it will call net_handshake() again.
[https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/flb_tls.c#L443](https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/flb_tls.c#L443)
In tls_net_handshake(), it uses freed memory thus causing segfault.
[https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/openssl.c#L504](https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/openssl.c#L504)
Sometimes, it will stuck on getting the lock.
https://github.com/fluent/fluent-bit/blob/8e5f9f910694e059d692438d51d7dc3b46e63e18/src/tls/openssl.c#L505

The newer version(v2.0.8) has solved this problem by determining net error after the co-routine resumed.
https://github.com/fluent/fluent-bit/blob/9444fdc5ee858a42b58b9a97010d997096e63634/src/tls/flb_tls.c#L611

**Comment by gwny** [comment]
By the way, it can be reproduced by the following steps:
1. In output side, send data to Fluentd by Forward plugin.
2. In Fluentd side, run `tc qdisc add dev eth0 root netem loss 30%` , dropping packets randomly to simulate network problem.
3. Then the fluent-bit will exit with signal SIGSEGV or the fluent-bit will stuck.

**Comment by leonardo-albertovich** [comment]
You are right about the UAF being the culprit but this bug was fixed in 2.0.6 on Nov 22 2022. 

You should be able to reproduce it using this configuration : 

```
[SERVICE]
    flush 1
    grace 10
    log_level info

[INPUT]
    name dummy
    samples 1

[OUTPUT]
    name tcp
    match *
    host 127.0.0.1
    port 3000
    workers 1
    tls on
    retry_limit no_retries
    net.connect_timeout 2
```

All you have to do is start a dummy listener on port 3000 using netcat like this `nc -k -l 3000` and leave it just like that so the client connects, starts the handshake and times out.

Grace is not that important in this case but usually it helps keep the noise down and having no retries in this case does the same.

If you check out v2.0.5 and run fluent-bit under valgrind it will immediately trigger and you can repeat the same test with v2.0.6 to verify the results.

The most important aspect of the correction was not that conditional (which is important on its own) but the fact that `connection->tls_session` is not prematurely set.

Are you still having issues with this or did you conduct your RCA just to have a better understanding of the situation?

**Comment by gwny** [comment]
> You are right about the UAF being the culprit but this bug was fixed in 2.0.6 on Nov 22 2022.
> 
> You should be able to reproduce it using this configuration :
> 
> ```
> [SERVICE]
>     flush 1
>     grace 10
>     log_level info
> 
> [INPUT]
>     name dummy
>     samples 1
> 
> [OUTPUT]
>     name tcp
>     match *
>     host 127.0.0.1
>     port 3000
>     workers 1
>     tls on
>     retry_limit no_retries
>     net.connect_timeout 2
> ```
> 
> All you have to do is start a dummy listener on port 3000 using netcat like this `nc -k -l 3000` and leave it just like that so the client connects, starts the handshake and times out.
> 
> Grace is not that important in this case but usually it helps keep the noise down and having no retries in this case does the same.
> 
> If you check out v2.0.5 and run fluent-bit under valgrind it will immediately trigger and you can repeat the same test with v2.0.6 to verify the results.
> 
> The most important aspect of the correction was not that conditional (which is important on its own) but the fact that `connection->tls_session` is not prematurely set.
> 
> Are you still having issues with this or did you conduct your RCA just to have a better understanding of the situation?

Thanks for your reply, we are going to upgrade to v2.0.8. What I'm doing is to have a clearly understanding of this issue, then I can confirm that the issue can be fixed by upgrading version. It may also be of a little help to other people who have this problem. Thanks.

**Comment by leonardo-albertovich** [comment]
That's awesome, I'm glad you took the time to analyze it and decided to share with the community.
As for the update, I think if you are about to do it, you might want to hold on for a few days because I think a new version is about to be released and it will include important fixes.

**Comment by gwny** [comment]
Ok, thanks.
