### ISSUE TITLE
Systemd input doesn't work properly with SELinux policy deny_execmem

### ISSUE THREAD

**Issue by schoentoon** [fluent/fluent-bit#6491]
## Bug Report
When first enabling the `deny_execmem` SELinux policy (a policy which will deny mapped memory to be both executable and writable at the same time). And after that running fluent-bit with the systemd input, it will get denied by this policy and just hang there forever doing nothing. I ran into this when upgrading from fluent-bit 1.9.6 to 2.0.4 (and I confirmed this is still the case with 2.0.6)

**To Reproduce**
```
[root@localhost ~]# /opt/fluent-bit/bin/fluent-bit -i systemd -o stdout > /dev/null 
Fluent Bit v2.0.6
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/12/02 09:55:20] [ info] [fluent bit] version=2.0.6, commit=, pid=36650
[2022/12/02 09:55:20] [ info] [storage] ver=1.3.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2022/12/02 09:55:20] [ info] [cmetrics] version=0.5.7
[2022/12/02 09:55:20] [ info] [ctraces ] version=0.2.5
[2022/12/02 09:55:20] [ info] [input:systemd:systemd.0] initializing
[2022/12/02 09:55:20] [ info] [input:systemd:systemd.0] storage_strategy='memory' (memory only)
[2022/12/02 09:55:20] [ info] [sp] stream processor started
[2022/12/02 09:55:20] [ info] [output:stdout:stdout.0] worker #0 started
^C[2022/12/02 09:55:21] [engine] caught signal (SIGINT)
[2022/12/02 09:55:21] [ warn] [engine] service will shutdown in max 5 seconds
[2022/12/02 09:55:21] [ info] [input] pausing systemd.0
[2022/12/02 09:55:22] [ info] [engine] service has stopped (0 pending tasks)
[2022/12/02 09:55:22] [ info] [input] pausing systemd.0
[2022/12/02 09:55:22] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2022/12/02 09:55:22] [ info] [output:stdout:stdout.0] thread worker #0 stopped
[root@localhost ~]# setsebool -P deny_execmem on
[root@localhost ~]# /opt/fluent-bit/bin/fluent-bit -i systemd -o stdout
Fluent Bit v2.0.6
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
```
It will hang like this forever and it doesn't respond to SIGTERM either, has to be killed from another session. I also added some additional logs from /var/log/audit/audit.log
```
[root@localhost log]# cat /var/log/audit/audit.log | grep -i fluent
type=AVC msg=audit(1669972062.414:96): avc:  denied  { execmem } for  pid=1817 comm="fluent-bit" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
type=SYSCALL msg=audit(1669972062.414:96): arch=c000003e syscall=10 success=no exit=-13 a0=7f5ec3aab000 a1=800000 a2=7 a3=ffffffffffffffc0 items=0 ppid=1692 pid=1817 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=1 comm="fluent-bit" exe="/opt/fluent-bit/bin/fluent-bit" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null)ARCH=x86_64 SYSCALL=mprotect AUID="root" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root"
```

**Steps to reproduce the problem:**
- Install a SELinux distro, I initially ran into it on Fedora CoreOS with the docker images. But I confirmed this behavior on CentOS 9 as well.
- Install fluent-bit, I followed the instructions on the website https://docs.fluentbit.io/manual/installation/linux/redhat-centos#install-on-redhat-centos
- Enable the deny_execmem flag using `setsebool -P deny_execmem on`
- Run fluent-bit with the systemd input enabled `/opt/fluent-bit/bin/fluent-bit -i systemd -o stdout` for example

**Expected behavior**
I would expect fluent-bit to run as normal

**Your Environment**
* Version used: 2.0.6
* Configuration: None, I narrowed it down enough that it can run from command line right away `fluent-bit -i systemd -o stdout`
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: CentOS 9
* Filters and plugins: systemd

**Additional context**
I ran into this while upgrading fluent-bit on a hardened server, where we set a lot of extra SELinux policies. And it basically stopped working completely with our existing configuration.

**Comment by nokute78** [comment]
Note: `mprotect` returns EACCES (=13) when `deny_execmem` is on.

```
$ find . -name "*.[ch]"| xargs grep mprotect --color | grep -i exec
./lib/flb_libco/ppc.c:    mprotect((void*)begin, end - begin, PROT_READ | PROT_EXEC);
./lib/flb_libco/x86.c:    mprotect((void*)base, size, PROT_READ | PROT_EXEC);
./lib/flb_libco/arm.c:  mprotect((void*)base, size, PROT_READ | PROT_EXEC);
./lib/flb_libco/amd64.c:    mprotect((void*)base, size, PROT_READ | PROT_EXEC);
./lib/monkey/deps/flb_libco/ppc.c:    mprotect((void*)begin, end - begin, PROT_READ | PROT_EXEC);
./lib/monkey/deps/flb_libco/x86.c:    mprotect((void*)base, size, PROT_READ | PROT_EXEC);
./lib/monkey/deps/flb_libco/arm.c:  mprotect((void*)base, size, PROT_READ | PROT_EXEC);
./lib/monkey/deps/flb_libco/amd64.c:    mprotect((void*)base, size, PROT_READ | PROT_EXEC);
./lib/luajit-3065c9/src/lj_ccallback.c:  mprotect(p, sz, (PROT_READ|PROT_EXEC));
```

**Comment by nokute78** [comment]
Workaround is to disable `FLB_WASM`.
Some wasm sources try to call `mprotect` and it failed.
Cc @cosmo0920 
```
cmake .. -DFLB_WASM=off && make
```

```
$ find . -name "*.[ch]"|xargs grep os_mprotect --color
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_loader.c:        os_mprotect(mmap_addr, total_size, map_prot);
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_loader.c:        os_mprotect(module->extra_plt_data, module->extra_plt_data_size,
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_loader.c:            os_mprotect(data_section->data, data_section->size, map_prot);
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_runtime.c:    if (os_mprotect(p, total_size, MMAP_PROT_READ | MMAP_PROT_WRITE) != 0) {
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_runtime.c:    if (os_mprotect(memory_inst->memory_data_end.ptr,
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/rt-thread/rtt_platform.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/riot/riot_platform.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/windows/win_memmap.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/alios/alios_platform.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/zephyr/zephyr_platform.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/include/platform_api_vmcore.h:os_mprotect(void *addr, size_t size, int prot);
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/common/posix/posix_memmap.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/common/posix/posix_thread.c:    if (os_mprotect(stack_min_addr, page_size * guard_page_count,
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/common/posix/posix_thread.c:    os_mprotect(stack_min_addr, page_size * guard_page_count,
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/linux-sgx/sgx_platform.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/linux-sgx/sgx_platform.c:        os_printf("os_mprotect(addr=0x%" PRIx64 ", size=%u, prot=0x%x) failed.",
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/nuttx/nuttx_platform.c:os_mprotect(void *addr, size_t size, int prot)
./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/shared/platform/esp-idf/espidf_memmap.c:os_mprotect(void *addr, size_t size, int prot)
```

**Comment by cosmo0920** [comment]
> ./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_loader.c:        os_mprotect(mmap_addr, total_size, map_prot);
> ./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_loader.c:        os_mprotect(module->extra_plt_data, module->extra_plt_data_size,
> ./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_loader.c:            os_mprotect(data_section->data, data_section->size, map_prot);
> ./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_runtime.c:    if (os_mprotect(p, total_size, MMAP_PROT_READ | MMAP_PROT_WRITE) != 0) {
> ./lib/wasm-micro-runtime-fast-jit-06-29-2022/core/iwasm/aot/aot_runtime.c:    if (os_mprotect(memory_inst->memory_data_end.ptr,

For ordinary WASM usecases on fluent-bit, it might be enough to specify FLB_WAMR_DISABLE_AOT_LOADING=On to avoit calling `os_mprotect`.

**Comment by schoentoon** [comment]
What I wonder about more here. Why is this WASM library being called at all? If I were to use the wasm filter, sure. But I'm not.

**Comment by nokute78** [comment]
Note:
When `FLB_WASM` is enabled, `hello_world` doesn't work because of "permission denied".

Following command also fails with same error.
`hello_world` also doesn't use wasm plugin..
```
ldd build/bin/hello_world
/lib64/ld-linux-x86-64.so.2 build/bin/hello_world
```

**Comment by nokute78** [comment]
It may cause executable `GNU_STACK` of `libfluent-bit.so`.
```
$ readelf -Wa libfluent-bit.so  |grep GNU_STACK
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
```

`FLB_WASM=on` :
```
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
```


`FLB_WASM=off`:
```
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
```


Refs: 
https://jira.mongodb.org/browse/SERVER-24117
https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart

**Comment by nokute78** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-load.c;h=650e4edc35e5e582652c1167f4275a93e8c33120;hb=ae37d06c7d127817ba43850f0f898b793d42aea7#l1333

glibc seems to call `mprotect` to change stack is executable.
I think it will be failed when `deny_execmem` is enabled.

**Comment by nokute78** [comment]
https://github.com/fluent/fluent-bit/blob/v2.0.6/lib/wasm-micro-runtime-fast-jit-06-29-2022/CMakeLists.txt#L114-L120
I think these lines relate this issue.

I enabled these lines, but the file was not used to build fluent-bit.

@cosmo0920 Any ideas ?

**Comment by cosmo0920** [comment]
Hmm..., interesting. Then, I'd like to provide an option to use these lines. It's like FLB_WASM_HARDENED loption.

**Comment by cosmo0920** [comment]
I'd created for enabling string stack protector: https://github.com/cosmo0920/fluent-bit/commit/dd669d4bd47f580cbdd89e714b116c74d6035033
I'll test for SELinux enabled environment.

**Comment by nokute78** [comment]
@cosmo0920 Thank you for the patch.
I tested following steps on CentOS Stream 9, but it didn't solve this issue ...
Hmm..

```
git clone https://github.com/cosmo0920/fluent-bit.git
git checkout wasm-stack-protector
cd build
cmake .. -DFLB_WASM_STACK_PROTECT=on -DFLB_CONFIG_YAML=off && make
bin/hello_world
```

**Comment by nokute78** [comment]
Note: I tried to build iwasm.

Not changed.
```
$ readelf -Wa iwasm | grep GNU_STACK
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
```

Enabled [these lines](https://github.com/fluent/fluent-bit/blob/v2.0.6/lib/wasm-micro-runtime-fast-jit-06-29-2022/product-mini/platforms/linux/CMakeLists.txt#L153-L159)
```
$ readelf -Wa iwasm | grep GNU_STACK
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
```

Steps to build iwasm.
```
cd lib/wasm-micro-runtime-fast-jit-06-29-2022/product-mini/platforms/linux
mkdir build
cd build
cmake .. && make
readelf -Wa iwasm | grep GNU_STACK
```

**Comment by nokute78** [comment]
I also tried to load `libiwasm.so` using following c code.
The code invokes `mprotect(PROT_EXEC)`.

`ret` is valid pointer when I enable [these lines](https://github.com/fluent/fluent-bit/blob/v2.0.6/lib/wasm-micro-runtime-fast-jit-06-29-2022/product-mini/platforms/linux/CMakeLists.txt#L153-L159)
On the other hand, `ret` is `NULL` when I disable lines.

It means [these lines](https://github.com/fluent/fluent-bit/blob/v2.0.6/lib/wasm-micro-runtime-fast-jit-06-29-2022/product-mini/platforms/linux/CMakeLists.txt#L153-L159) should relate this issue.

```c
#include <stdio.h>
#include <dlfcn.h>

int main(void) {
    void *ret;
    ret = dlopen("./libiwasm.so", RTLD_NOW);
    printf("ptr=%p\n", ret);
}
```

Step to build libiwasm.so
```
cd lib/wasm-micro-runtime-fast-jit-06-29-2022/product-mini/platforms/linux
mkdir build
cd build
cmake .. && make
```

**Comment by cosmo0920** [comment]
Hmm..., intersting. I'll take a look later

**Comment by cosmo0920** [comment]
Ah, got it. Maybe these lines should be affective entire project.

**Comment by nokute78** [comment]
@cosmo0920 Thank you for pointing it.
I tested following diff for root CMakeLists.txt and it changed GNU_STACK.

```
$ readelf -Wa build/lib/libfluent-bit.so |grep GNU_STACK
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10
```

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 96074359a..8db537469 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -54,6 +54,9 @@ if (MSVC)
   add_compile_options(/MT)
 else()
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
+  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -ftrapv -D_FORTIFY_SOURCE=2")
+  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fstack-protector-strong --param ssp-buffer-size=4")
+  set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")
 endif()
 
 set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__FLB_FILENAME__=__FILE__")
```
