### ISSUE TITLE
in_stdin, out_stdout: Simple non-JSON test causes crash

### ISSUE THREAD

**Issue by chlunde** [fluent/fluent-bit#650]
A simple test like this might be one of the first things a new user tries, but it causes a crash:
```
echo '2018-01-01T18:00:00 foo' | ./build/bin/fluent-bit  -i stdin -o stdout
```
This is probably because in_stdin expects JSON.  I think this should not crash because it will not leave a good first impression.  I'm not sure what the best solution is, maybe it should print a warning once if we get invalid JSON?

Actual output:
```
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/06/19 21:08:20] [ info] [engine] started (pid=53252)
[2018/06/19 21:08:20] [ warn] [in_stdin] end of file (stdin closed by remote end)
[2018/06/19 21:08:20] [ info] [input] pausing stdin.0
[engine] caught signal (SIGSEGV)
[0] stdin.0: [#0  0x444471            in  flb_time_pop_from_msgpack() at src/flb_time.c:155
#1  0x473dee            in  cb_stdout_flush() at plugins/out_stdout/stdout.c:56
#2  0x4339c2            in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:311
#3  0x4f9765            in  co_init() at lib/flb_libco/amd64.c:117
#4  0xffffffffffffffff  in  ???() at ???:0
Aborted (core dumped)
```

In general, I wonder if there should be some more asserts for msgpack types.  Here it crashes because it expects an array but it gets a number.

**Comment by edsiper** [comment]
thanks for reporting this issue.

I've pushed the fix 2a4d62b3 which allows to detect the content type and pack as raw text if is not a valid JSON (it should be merged shortly in GIT master)
