### ISSUE TITLE
Remove Gitlab Mirror of fluent/fluent-bit

### ISSUE THREAD

**Issue by meehanman** [fluent/fluent-bit#6514]
The GitLab Mirror of [fluent/fluent-bit](https://gitlab.com/fluent/fluent-bit) is currently outdated with the last commit being `01 Nov, 2019` and release was [v1.1.1](https://gitlab.com/fluent/fluent-bit/-/releases/v1.1.1) (While the [fluent/fluentd](https://gitlab.com/fluent/fluentd) last commit was `1 week ago`).

I believe this should either be removed or at the least a message that forwards users to this codebase.

**Comment by agup006** [comment]
Oh wow I didn’t realize we had this mirror

**Comment by meehanman** [comment]
Can we re-open this case?

**Comment by agup006** [comment]
We can re-open but I'm not sure an action here, I don't know who owns that org on GitLab so we can delete or at least re-direct.

**Comment by meehanman** [comment]
@edsiper Would you be able to have a look at this issue? It shows you as the owner of the Gitlab Fluent namespace. (If you still have access)
