### ISSUE TITLE
Some container log lines are not parsed

### ISSUE THREAD

**Issue by msvticket** [fluent/fluent-bit#6515]
## Bug Report

I’m trying to switch from from filebeat to fluent bit for sending logs from pods in k8s v1.24 to Elasticsearch. It mostly works, but a small percentage of the log messages doesn’t get parsed.

The raw string from the container log is added to the `log` field in elasticsearch instead of being parsed. So it typically starts something like: 

`2022-12-05T15:35:00.592945978Z stdout F {"@timestamp":"2022-12-05T15:35:00.591Z","level":"ERROR","message":"Error in parsing` 

The filters work, including the addition of kubernetes fields. I note that the field `_p` isn’t populated in the records that are not parsed. I suppose that field normally originates from the multiline parser for cri.

I see nothing logged by fluent bit itself at the time of faulty logging.

I started out with the current default configuration from the helm chart (version 0.21.4) but have tried solving the problem by tweaking it. The tail input is currently configured like this:

```
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser cri, java, go, python
          Tag kube.*
          Buffer_Chunk_Size 256KB
          Buffer_Max_Size 5MB
          Mem_Buf_Limit 25MB
          Skip_Long_Lines On
```

**Environment**
* Version used: 2.0.6
* Environment name and version: Kubernetes 1.24
* Operating System and version: Amazon Linux 2 and Bottlerocket (latest versions supplied by AWS)

**Comment by msvticket** [comment]
I keep having this problem

**Comment by msvticket** [comment]
I have now returned to this issue to investigate more.

Apart from the problem I stated in the original report I recently discovered another variety of the problem: Log lines are sent twice to ElasticSearch, first unparsed and then parsed correctly. Both these cases happened alternately. Most of the time both problems occured in bursts for a particular pod.

I've now done a couple of more things to try to fix these problems.

First I upgraded to the latest version of the helm chart (0.27.0), which implied version 2.0.11 of fluent-bit. That didn't make a discernible difference.

Then I changed the multiline.parser settings stated above to the input now looks like this:

      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser cri
          Tag kube.*
          Buffer_Chunk_Size 256KB
          Buffer_Max_Size 5MB
          Mem_Buf_Limit 25MB
          Skip_Long_Lines On

**Comment by kinseii** [comment]
We have the same problem:

fluent-bit tail settings:
```
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri, go, python, java
        Tag kube.*
        Skip_Long_Lines On
        Buffer_Max_Size 5MB
        Mem_Buf_Limit 500MB
        Storage.Type filesystem
```

I don't understand how leaving only the cri parser solves this problem. I think there is some issue with the CRI parser not adding the `_p` field and consequently the kubernetes filter not removing the metadata from the `log` field.
