### ISSUE TITLE
AWS EC2 documentation page is deprecated.

### ISSUE THREAD

**Issue by rifftual** [fluent/fluent-bit#6517]
## Bug Report

**Describe the bug**
EC2 installation page is deprecated in favor of https://docs.fluentbit.io/manual/installation/linux/amazon-linux

**To Reproduce**
Installation instructions in https://docs.fluentbit.io/manual/installation/amazon-ec2 do not work. The package `td-agent-bit` is no longer available in the corresponding repo.

**Comment by patrick-stephens** [comment]
Thanks, can you submit a PR to the docs repo? 
github.com/fluent/fluent-bit-docs

It probably needs updating on the AWS repo too as that has some config.

**Comment by rifftual** [comment]
https://github.com/fluent/fluent-bit-docs/issues/999
