### ISSUE TITLE
Frequent TCP session setup and teardown between fluent-bit to fluentd

### ISSUE THREAD

**Issue by gayatk** [fluent/fluent-bit#6523]
### Describe the bug

The versions of fluentd and fluent-bit which are being used in my environment

Fluentd version : 1.15.3
Fluent-bit version: 2.0.4

The tcp connection between fluent-bit and fluentd are not constant. There is a frequent connection teardown and setup happening between fluent-bit and fluentd.

### To Reproduce

Collect the tcp dump from calico interface of fluentd.
There is a frequent connection setup and reset happening between fluentd and fluent-bit.

### Expected behavior

Constant TCP connection between fluent-d and fluentbit.

### Your Environment

```markdown
- Fluentd version:1.15.3
- TD Agent version:
- Operating system:
- Kernel version:
```

### Your Configuration

```apache
<source>
                  @type forward
                  port 24224
                  bind 0.0.0.0
                  <transport tls>
                    version                TLSv1_2
                    ca_path                /fluentd-tls/ssl/ca.crt.pem
                    cert_path              /fluentd-tls/ssl/server.crt.pem
                    private_key_path       /fluentd-tls/ssl/server.key.pem
                  </transport>
                </source>
                
                ports:
                - name: fluentd
                  protocol: TCP
                  containerPort: 24224
```

### Your Error Log

```shell
There is a multiple tcp connection getting established between fluentd and fluent-bit 
eccd@worker-pool1-2e7ezn1z-ezghodh-ibd-stack:~> sudo nsenter -t 36861 -n lsof -i -P -n | grep 24224
ruby.ruby 37000 messagebus   18u  IPv4 158496      0t0  TCP *:24224 (LISTEN)
ruby.ruby 37000 messagebus   20u  IPv4 158497      0t0  UDP *:24224
ruby.ruby 37000 messagebus   22u  IPv4 162474      0t0  TCP 192.168.135.78:24224->192.168.103.64:23443 (ESTABLISHED)
ruby.ruby 37000 messagebus   22u  IPv4 162474      0t0  TCP 192.168.135.78:24224->192.168.103.64:23443 (ESTABLISHED)
eccd@worker-pool1-2e7ezn1z-ezghodh-ibd-stack:~>
```

**Comment by gayatk** [comment]
HI team, 
Any update on the above issue reported ?

**Comment by gayatk** [comment]
Hi, below is the fluent-bit output configuration, but still I see the connection reset between fluent-bit and fluentd
[OUTPUT]
        Name forward
        Match *
        Host fluentd
        Port 24224
        tls On
        **net.keepalive on**
        tls.verify On
        tls.ca_file /fluentbit-tls/ssl/ca.crt.pem
        tls.crt_file /fluentbit-tls/ssl/client.crt.pem
        tls.key_file /fluentbit-tls/ssl/client.key.pem

**Comment by Sunnatillo** [comment]
The error message: 
[2023/01/12 06:08:36] [error] [upstream] connection https://github.com/fluent/fluent-bit/pull/174 to tcp://x.x.x.x:24224 timed out after 10 seconds (connection timeout)

**Comment by gayatk** [comment]
The above error is seen in fluent-bit logs, which indicates the connection reset between fluentd and fluent-bit.

**Comment by gayatk** [comment]
I have uplifted the **fluent-bit to 2.0.8**, but still facing the same issue.

eccd@director-0-n92-ci-ibd-32-jenkins:~> helm list -A | grep fluent
**fluent-bit                              ccd-logging     1               2023-01-24 12:59:26.782945641 +0000 UTC deployed        fluent-bit-0.22.0                                2.0.8**
fluentd                                 ccd-logging     1               2023-01-24 12:59:54.700479485 +0000 UTC deployed        fluentd-0.3.9                                    v1.14.6
eccd@director-0-n92-ci-ibd-32-jenkins:~>

in fluent-bit logs I can these below errors continuously 
**[2023/01/25 05:02:26] [ info] [input] tail.0 resume (mem buf overlimit)
[2023/01/25 05:02:26] [ warn] [input] tail.0 paused (mem buf overlimit)**
[2023/01/25 05:02:26] [ info] [input] pausing tail.0
eccd@director-0-n92-ci-ibd-32-jenkins:~>


[2023/01/24 14:49:29] [error] [upstream] connection #144 to tcp://10.102.224.136:24224 **timed out after 10 seconds (connection timeout)**
[2023/01/24 14:49:29] [error] [upstream] connection #146 to tcp://10.102.224.136:24224 timed out after 10 seconds (connection timeout)
[2023/01/24 14:49:29] [error] [output:forward:forward.0] no upstream connections available
[2023/01/24 14:49:29] [error] [output:forward:forward.0] no upstream connections available
[2023/01/24 14:49:32] [error] [upstream] connection #142 to tcp://10.102.224.136:24224 timed out after 10 seconds (connection timeout)
[2023/01/24 14:49:32] [error] [output:forward:forward.0] no upstream connections available

**Comment by gayatk** [comment]
Hi Team, please support me in this issue.

**Comment by leonardo-albertovich** [comment]
Is there any way you could help minimize the reproduction case? I'd like to take a look at it but I think I'm misinterpreting your report since you seem to have an issue with connections being dropped but also a problem reconnecting.

**Comment by gayatk** [comment]
yes, there is a connection being dropped out between fluent-bit and fluentd.

**Comment by kashifest** [comment]
@edsiper any thoughts on this issue ?

**Comment by leonardo-albertovich** [comment]
What stands out to me is that after the connection is dropped other connection attempts time out but I don't see a clear way to reproduce it locally.

I will try to take a look but I don't have high hopes with the information I have at the moment.

**Comment by gayatk** [comment]
HI Team, let me know if any findings on this.

**Comment by patrick-stephens** [comment]
I think the key here is simple reproduction:

- Simplify the stack as much as possible to reproduce the problem
- Provide a script/packer/vagrantfile/docker-compose/pod-spec that anyone can use both to reproduce and then verify a fix

At the moment there is a vague statement of how to deploy a very large stack so lots of things can differ between the original infrastructure and any we would create. There is no definition of which platform or fluent bit config used for example - this is all part of the issue template so please do not ignore.

Let's start as basic as possible and add stuff until it breaks:

1. Docker compose
2. Fluent Bit to Fluent Bit with no TLS
3. Fluent Bit to Fluent Bit with TLS
4. Fluent Bit to Fluentd with/without TLS
5. KIND with container deployments of the same
7. Vagrantfile or similar single VM for specific OS
8. Multiple VMs (e.g. podman images or Vagrantfiles or Packer)
9. Calico
