### ISSUE TITLE
Fluent-bit v2.0.4 and v2.0.5 have memory leak issue in Windows. v1.8.12 has no this issue.

### ISSUE THREAD

**Issue by sudahang** [fluent/fluent-bit#6525]
## Bug Report

**Describe the bug**
Fluent-bit v2.0.4 and v2.0.5 have memory leak issue in Windows. v1.8.12 has no this issue. 

**To Reproduce**
- Steps to reproduce the problem:
Use one tail input and one forward output, the configuration like this
[INPUT]
    Name                tail
    Path                D:\share\log
    Tag                 trwork-text

[OUTPUT]
    name  forward
    match *
    host example.net
    port 9995
    tls on
    tls.verify off
Run fluent-bit for several hours.

**Expected behavior**
The memory should not have big growth.

**Screenshots**
Start fluent-bit
![image](https://user-images.githubusercontent.com/4025059/206702881-3a3c2c94-1ec3-4418-bda2-a1a3957600e4.png)
![image](https://user-images.githubusercontent.com/4025059/206702926-d89f30a2-a405-4904-96b2-a9e47ce172ad.png)

After 1 hour
 
![image](https://user-images.githubusercontent.com/4025059/206702995-57b22128-26bd-4e59-bcc1-682495b496cd.png)
![image](https://user-images.githubusercontent.com/4025059/206703040-38de43ba-67af-4812-832e-8836164ec364.png)

 
Two hours later
 
![image](https://user-images.githubusercontent.com/4025059/206703098-a46bc483-e0af-4b38-a2a9-098f74727765.png)
![image](https://user-images.githubusercontent.com/4025059/206703127-bed9c775-8477-4067-bf1a-cb1bb7e82ce2.png)
 

Three hours later
 
![image](https://user-images.githubusercontent.com/4025059/206703178-7450cae2-a80a-4753-a18d-e2cd2e31f018.png)
![image](https://user-images.githubusercontent.com/4025059/206703215-ab762433-fdc7-49cf-a8a4-3965af1789c1.png)
 

4 hours later
 
![image](https://user-images.githubusercontent.com/4025059/206703269-453b6974-60a4-4e1c-b2ad-322326061820.png)
![image](https://user-images.githubusercontent.com/4025059/206703299-21dc5f29-633e-4ff8-afbd-b048ceda3d27.png)

Before stopping fluent-bit
 
![image](https://user-images.githubusercontent.com/4025059/206703453-69e270f4-012e-48e1-8c23-6b5184b9e7f1.png)
![image](https://user-images.githubusercontent.com/4025059/206703506-62a3003b-4018-4415-b1c9-bab650250838.png)

After fluent-bit is stopped
 
![image](https://user-images.githubusercontent.com/4025059/206703584-2ec0bc00-a0c3-435d-ba89-dd4596e40d2d.png)

Some errors in the last hour
[2022/12/09 13:59:24] [error] [sched]  'retry request' could not be created. the system might be running out of memory or file descriptors.
[2022/12/09 13:59:24] [ warn] [engine] retry for chunk '28628-1670565563.149409700.flb' could not be scheduled: input=tail.0 > output=forward.0
socketpair: No error
[2022/12/09 13:59:24] [error] [sched] cannot do timeout_create()
[2022/12/09 13:59:24] [ warn] [net] getaddrinfo(host='******', err=24): DNS query cancelled
[2022/12/09 13:59:24] [debug] [upstream] connection #-1 failed to ********
[2022/12/09 13:59:24] [error] [output:forward:forward.0] no upstream connections available

**Your Environment**

* Version used: v2.0.4 and v2.0.5
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: Windows Server 2019 and Windows 10
* Filters and plugins:

**Additional context**
I verified this issue in v1.8.12 , it does not exist.

**Comment by sudahang** [comment]
This issue is quite similar with https://github.com/fluent/fluent-bit/issues/6497, they both have high non-paged pool. In last two days, I did the same test for v1.9.6, v1.9.9 and v2.0.0. I found this issue was introduced from v2.0.0.

**Comment by sudahang** [comment]
I did some investigation for the high non-paged pool.
After running v2.0.0 for 3 hours with the same config as I mentioned above, I captured the non-paged pool data.
![image](https://user-images.githubusercontent.com/4025059/207234704-a69d7cbb-01af-4b1e-b198-d451e6815d3c.png)
![image](https://user-images.githubusercontent.com/4025059/207234743-866d4294-5883-4b30-9024-d59b638dcd62.png)

The top 3 driver tags with high non-paged pool are: Nnnn, Nph1 and AfdB. And their mapped drivers are netio.sys and afd.sys. So It looks like this issue was caused by some network related change. Hopefully this clue is helpful for the trouble-shooting.

**Comment by tandrez** [comment]
Hello,
Same issue here with v2.0.6.

**Comment by leonardo-albertovich** [comment]
I was able to reproduce the issue and I'm working on it but sadly I still don't have an ETA for the fix.

**Comment by sudahang** [comment]
Hi @leonardo-albertovich，how is the progress of this issue？Can you add it to the high priority list considering it blocks the Windows users？Thank you.

**Comment by hmax-72** [comment]
I had the same problem. Stepping back to 1.9.10 using the same config "solved" it.

**Comment by leonardo-albertovich** [comment]
Sorry for the delay, a while ago I commented in a related issue I can't find at the moment, it included the root cause analysis and a fix proposal that I wouldn't be able to implement at the moment due to time constraints, that is on my queue and I intend to get to it as soon as possible but I can't give an ETA at the moment. 

If anyone has a link to that message I'd appreciate it if you  shared it since I can't seem to find it using the githubs notification search system.

I think switching the DNS client mode to `LEGACY` will probably help you. If I'm correct issue is not limited to DNS queries because it's rooted in the timer component but the DNS client is the one subsystem that massively uses timers at the moment so this should mellow out the symptoms.

Please don't hesitate to ping me.

**Comment by danivendetta** [comment]
I have the same issue, also I can see the number of Handles, PM, WS and CPU(s) is increasing constantly. 

`PS C:\inetpub\wwwroot> while ($true) {get-process -name fluent-bit; sleep 10}`

```
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    341     130    10300      16156       0.20  17464  16 fluent-bit
    341     129    10300      16164       0.20  17464  16 fluent-bit
    340     128    10300      16172       0.20  17464  16 fluent-bit
    344     132    10396      16224       0.25  17464  16 fluent-bit
    344     131    10396      16236       0.25  17464  16 fluent-bit
...
...
...

    443     624    11012      17472       1.11  17464  16 fluent-bit
    441     629    10928      17428       1.11  17464  16 fluent-bit
    442     636    11000      17468       1.13  17464  16 fluent-bit
    443     650    11024      17508       1.13  17464  16 fluent-bit
    444     661    11308      17540       1.14  17464  16 fluent-bit
    445     669    11200      17396       1.16  17464  16 fluent-bit
```

How result, this container is getting npm memory of the server and finally crash. Notice microsoft in their [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-7.0
![fluentbit](https://user-images.githubusercontent.com/11478965/225284820-159039ff-fdb0-4c0a-8ed0-264d04930d82.png)
):

**_" Handles are an extremely valuable resource, so leaking handles is more virulent than leaking memory."_**


I'm using fluent-bit 2.0.9 In Kubernetes: EKS in Windows workers with Windows server core 2022.

**Comment by leonardo-albertovich** [comment]
There is an issue in the timer backend used for the asynchronous DNS client which we are in the process of fixing, meanwhile, I think you should be able to overcome it if you set fluent-bit to use the LEGACY resolver and I would really appreciate it if you reported the results.

**Comment by danivendetta** [comment]
I've changed all outputs with `net.dns.resolver LEGACY`. After one hour using fluent-bit 2.0.9 It seems works correctly. 

`PS C:\fluent-bit> while ($true) {get-process -Name fluent-bit ;sleep 10}

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    330     123    10100      15752       0.09  17268  16 fluent-bit
    328     121    10100      15776       0.14  17268  16 fluent-bit
    330     123     9836      15784       0.17  17268  16 fluent-bit
    330     123    10256      15808       0.17  17268  16 fluent-bit
    330     122    10224      15892       0.17  17268  16 fluent-bit
	...
	... # 1 hour later.
	...
	356     123    11456      17308       4.23  17268  16 fluent-bit
    354     121    11456      17308       4.23  17268  16 fluent-bit
    356     123    11456      17308       4.27  17268  16 fluent-bit
    356     123    11456      17308       4.28  17268  16 fluent-bit
    354     121    11456      17308       4.30  17268  16 fluent-bit
    357     123    11456      17312       4.31  17268  16 fluent-bit	`

![fluentbit_ok](https://user-images.githubusercontent.com/11478965/225317100-db30fe93-5adb-4cb4-82b4-a63f4a9af817.png)

Thank you so much @leonardo-albertovich. I'm tracking the issue until will be fixed, then I'll be able to put resolver in AYNSC mode again.

**Comment by leonardo-albertovich** [comment]
Thank you for reporting the results, they cement my theory (which I'm sure I shared in a different issue with code references and an explanation of what needed to be fixed in case someone else wanted to give it a shot but can't find anywhere) which will make it way easier to apply the correct patch once I manage to secure the time for it.

And once again, sorry about the inconvenience.

**Comment by hpernu** [comment]
What is the status for fixing this issue (not just the workaround i.e. using legacy for dns resolver)?
This crashed some production servers a while ago. A more permanent fix than a workaround is appreciated. I understood someone had already made a patch, it is just not in the mainline.

**Comment by braydonk** [comment]
I believe I fixed this in #6748. This issue appears to refer to the same bug.

**Comment by dakkkob** [comment]
Beware of 2.0.10, the workaround "net.dns.resolver LEGACY" stopped to work with this version.

**Comment by leonardo-albertovich** [comment]
Really? That surprises me, I'll save this post so I can verify it as soon as I'm back from kubecon, I can't remember anything that should affect it but I'm glad you're letting me know so we can rectify it ASAP.

I will verify this and get back to you on the 25th.

**Comment by braydonk** [comment]
I'm also experimenting to verify if the legacy workaround only stopped working on 2.0.10. That would track with our experience but it did look like the root bug equally affected all versions, so I'm not sure if there is something else that changed.

**Comment by braydonk** [comment]
So far it's looking like 2.0.9 isn't leaking handles while 2.0.10 is.

2.1/2.0.12 will have the fix for this anyway, but I am very curious why the `legacy` workaround stopped working on 2.0.10 specifically.

**Comment by leonardo-albertovich** [comment]
I'm surprised about that side effect, it seems like I don't have enough context to link the two together but I remember making the change you linked. 

I'll come back to it on Tuesday and message you so I get a better picture of it and then we can figure out what needs to be fixed.

**Comment by dansimov04012022** [comment]
Hi @leonardo-albertovich, sorry for disturbing you but can you please tell me if this issue with the async DNS resolver was fixed in some latest release? 

I faced that same non-paged memory pool issue on my Windows Server 2019R2 instances with `2.0.9` release while using `nrlogs`, `http` and `prometheus_remote_write` output plugins,  so applied the hotfix by switching to the legacy resolver, but wondering if I can just update to some newer release if that issue was fixed there.

Great thanks in advance.
