### ISSUE TITLE
GELF messages cannot be ingested

### ISSUE THREAD

**Issue by rifftual** [fluent/fluent-bit#6526]
## Bug Report

**Describe the bug**
There is no input plugin for Graylog's GELF messages and TCP input cannot ingest them.

**To Reproduce**
*fluent-bit.conf*:
```
[SERVICE]
  Flush                       10
  Log_Level                   debug

[INPUT]
  Tag                 gelf
  Name                tcp
  Listen              0.0.0.0
  Port                12201
  Format              none
  Separator           "\0"

[OUTPUT]
  Match                     *
  Name                      stdout
```
*command (As instructured [here](https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html#GELFviaTCP))*:
```
[root@foo.bar bin]# echo -n -e '{ "version": "1.1", "host": "example.org", "short_message": "A short message", "level": 5, "_some_info": "foo" }'"\0" | nc -w0 localhost 12201
[root@foo.bar bin]#
```
*FluentBit logs*:
```
Dec 09 14:39:05 foo.bar fluent-bit[22909]: [2022/12/09 14:39:05] [debug] [input chunk] skip ingesting data with 0 bytes
```
**Expected behavior**
FluentBit would ingest the messages using null byte as a separator.

**Your Environment**
* Version used: 2.0.6
* Environment name and version: AWS EC2
* Operating System and version: Amazon Linux 2
* Filters and plugins: TCP input, STDOUT output

**Comment by nokute78** [comment]
@rifftual Thank you for reporting.
I sent a patch #6620 to support '\0' as a separator.
