### ISSUE TITLE
fluent-bit.conf overwritten on apt upgrade

### ISSUE THREAD

**Issue by noahbailey** [fluent/fluent-bit#6527]
When performing an `apt upgrade` on a Debian-based system (Ubuntu, etc), the configure stage will overwrite the config file, reverting the system's fluent-bit configuration to the default that just logs CPU to journald. 

The desired behaviour is to not overwrite the config file without prompting first, or to avoid overwriting it at all. 

As a workaround, I believe this can be prevented by using `-o Dpkg::Options::="--force-confold"` in apt upgrade commands (I have not verified this yet).

**Comment by patrick-stephens** [comment]
Yeah this should be in the next 2.0 release, it just missed 2.0.6.
