### ISSUE TITLE
Support for filtering on kubernetes labels?

### ISSUE THREAD

**Issue by dpgeekzero** [fluent/fluent-bit#653]
I may be missing something, but I only want to export logs for some subset of my kubernetes pods.

Can I use the filtering to only pass through logs from pods with a label like app=iwanttolog?

**Comment by michiel** [comment]
The `grep` filter might be what you're looking for. Something like this perhaps?

```
[FILTER]
    Name   grep
    Match  k8s.*
    Regex  app iwanttolog
```

https://fluentbit.io/documentation/0.13/filter/grep.html

**Comment by jinchaoxiang** [comment]
这样写不行

**Comment by jinchaoxiang** [comment]
can't work

**Comment by michiel** [comment]
If you need flexibility in matching the keys or values, you might also consider the following solution. In 0.14 (not yet released), you can apply conditions with regex matchers to the modify filter. [This PR](https://github.com/michiel/fluent-bit-docs/blob/172d0e8538603229e61b7e1b9cc52b7933569a72/filter/modify.md) has the documentation.

```
[FILTER]
    Name   modify
    Match  k8s.*
    Condition Key_value_matches log regex_to_match.* 
    Set DROP_THIS true

[FILTER]
    Name   grep
    Match  k8s.*
    Regex  DROP_THIS true
```

**Comment by rlguarino** [comment]
@michiel how can we try 0.14? Is there a docker image build somewhere. Is there an ETA?

**Comment by michiel** [comment]
This build is from the current master at 6764ac7 , it should have everything you need.

 - Tag : `travis-122`
 - Docker : [https://hub.docker.com/r/sddmelb/fluent-bit/tags/](https://hub.docker.com/r/sddmelb/fluent-bit/tags/)
 - Build history : [https://travis-ci.org/michiel/fluent-bit/builds/413818971](https://travis-ci.org/michiel/fluent-bit/builds/413818971)

**Comment by MohdAhmad** [comment]
@michiel thanks for sharing this. Quick question, any thoughts on what the more efficient method is? The aim for me is drop all records outside of the kube-system namespace.

**Comment by kaspernissen** [comment]
I'm looking for a similar thing. I'm trying to discard logs that doesn't match a label on pods. I have tried many different combinations of conditions without any luck. I only want to pass logs a long that has the following label `k8s.labels.type` equals to service.

https://github.com/michiel/fluent-bit-docs/blob/172d0e8538603229e61b7e1b9cc52b7933569a72/filter/modify.md 

```
[FILTER]
  Name                kubernetes
  Match               *
  Kube_URL            https://kubernetes.default.svc:443

[FILTER]
  Name     modify
  Match    *
  Rename   kubernetes k8s

[FILTER]
  Name     modify
  Match    *
  Condition Key_Value_Equals k8s.labels.type service
  Set testing MATCH
```
If I try the condition `Key_exists k8s` then i get the field testing with the value MATCH. But how to test nested conditions? 

I'm migrating from fluentd, where we could do something like this with the record_modifier:
``` 
<filter application.**>
  @type record_modifier
  <record>
    disable "${(record['kubernetes']['labels']['type'] == 'service') ? false : true}"
  </record>
</filter>
```
Is there any way to do something similar with fluent-bit?

**Comment by ciastooo** [comment]
For the record, I was able to do it with [record accessor](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/record-accessor):
```
    [FILTER]
        Name                  grep
        Match                 *
        Regex                 $kubernetes['labels']['myLabelName'] someLabelValue
``` 
So it's possible now and this issue could be probably closed

**Comment by rajat-rafay** [comment]
Hi Everyone, my goal is to extract logs specifically for a pod within a given namespace and print those logs. Below is the config map I am using, and I have attempted to use RecordAccessor for this purpose, but it's not working as expected. Can anyone help me identify what I might be doing wrong or guide me in the right direction? I have a pod running with the same label but fluentBit not giving the logs for the same. 
@ciastooo @thspinto @kaspernissen Any help would be much appreciated 🙏 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-http.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*fluent-bit*.log,/var/log/containers/*kube-system*.log
        multiline.parser  multiline-docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Kube_Tag_Prefix     kube.var.log.containers
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

    [FILTER]
        Name    grep
        Match   *
        Regex   $kubernetes['labels']['foo'] test

  output-http.conf: |
    [OUTPUT]
        Name    stdout
        Match   *
        Format  json_lines

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        ```
