### ISSUE TITLE
out_file plugin postfix or tag in file option

### ISSUE THREAD

**Issue by SamuelDeal** [fluent/fluent-bit#6533]
**Is your feature request related to a problem? Please describe.**
I would like to have my log files named ```${tag}.log```

**Describe the solution you'd like**
I have two solutions (the easiest one first):
1) Implement a ```file_postfix``` parameter (so we can set it to ```".log"```)
2) implement ```${tag}``` replacement in the ```file``` parameter (so we can set it to ```"${tag}.log"``` )

**Describe alternatives you've considered**
I I've thought about putting the ```.log``` directly in my tag by it is kind of ugly and disrupt the routing.
I can also create a file output plugin per tag, but it's a lot of repeating for no value and need a need a new output config for every new tag. 

**Additional context**
I use the ```out_file``` to store docker-compose output to ```/var/log```
So specifying the ```file``` parameter make me loose the log file by container
A basic logrotate configuration without the ```*.log``` end up rotating the ```filename-timstamp``` files as well

**Comment by patrick-stephens** [comment]
In case it helps I did something similar a while back by using the filename key to set the tag, in this case I wanted to set up an expected vs actual input but you could modify: https://github.com/couchbase/couchbase-fluent-bit/blob/f89cef79954e59c0c1eff8151c92d618e594df8c/test/conf/file-transfer/test-file-transfer-dest.conf#L12

It would be nicer to have the stuff you suggest though, I just wanted to lend a hand.

**Comment by SamuelDeal** [comment]
.
