### ISSUE TITLE
Response for new metrics exported with "fluentbit_metrics" missing "Content-Type" header

### ISSUE THREAD

**Issue by krunalnsoni** [fluent/fluent-bit#6554]
## Bug Report

**Describe the bug**

The new 2.x metrics exported with "fluentbit_metrics" plugin is missing "Content-Type" header in the response.
This breaks metrics scraper such as DataDog.

Here are the curl responses for traditional metrics and new metrics:
*Tradition Metrics*
```
>curl -i  http://localhost:2020/api/v1/metrics/prometheus
HTTP/1.1 200 OK
Server: Monkey/1.7.0
Date: Wed, 14 Dec 2022 15:06:39 GMT
Transfer-Encoding: chunked
Content-Type: text/plain; version=0.0.4

# HELP fluentbit_filter_add_records_total Fluentbit metrics.
# TYPE fluentbit_filter_add_records_total counter
....
```

*New  "fluentbit_metrics"*
```
>curl -i  http://localhost:2021/metrics
HTTP/1.1 200 OK
Server: Monkey/1.7.0
Date: Wed, 14 Dec 2022 15:08:27 GMT
Transfer-Encoding: chunked

# HELP fluentbit_uptime Number of seconds that Fluent Bit has been running.
# TYPE fluentbit_uptime counter
...
```

**To Reproduce**
Follow https://docs.fluentbit.io/manual/pipeline/inputs/fluentbit-metrics to setup new fluent-bit metrics with fluent-bit:2.0.6-debug container with port 2021.
Inside the container run, `curl -i  http://localhost:2021/metrics`.

**Expected behavior**

api/v1/metrics endpoint should provide "Content-Type" header in the response.

**Screenshots**

**Your Environment**

* Version used: 2.0.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes:1.22
* Server type and version:
* Operating System and version:
* Filters and plugins: fluentbit_metrics

**Additional context**

We are trying to collect new storage metrics to improve fluent-bit monitoring. We cannot use new metrics since DataDog fluent-bit integration is expecting "Content-Type" header.

**Comment by nokute78** [comment]
I sent a patch #6572
