### ISSUE TITLE
1.9.10 docker hub push

### ISSUE THREAD

**Issue by jamespgrant3** [fluent/fluent-bit#6555]
## Bug Report

**Describe the bug**
I just wanted to raise awareness. Your release notes for [1.9.10](https://github.com/fluent/fluent-bit/releases/tag/v1.9.10) indicate no container was pushed. However, [it was](https://hub.docker.com/r/fluent/fluent-bit/tags?page=1&name=1.9.10). Something in this release actually broke us in production.

We were referencing the image in our task definition as `1.9`, completely our fault. Once we updated it to `1.9.9` we were operational. However, anyone else referencing the version like so, may be broken.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by edsiper** [comment]
@jamespgrant3 would you please elaborate on the technical issue you have faced with the newest version ?, sorry about that, but 1.9 should be super stable.

**Comment by jamespgrant3** [comment]
Hello @edsiper. I actually have not gone back and done any further troubleshooting since I resolved the issue, so I am not sure what the root cause is. But, we host hasura within an ECS task and run fluent-bit as a sidecar container.

For whatever reason, we had two environments where the tasks would register with the alb just fine, but upon the initial request to hasura, the ECS task would exception, stop, and restart. After narrowing down the issue to be something within the task, my first step was to remove fluent-bit, and log directly to cloud watch. That resolved the issue.

I then went to see what changed in fluent-bit. That's when I realized you guys pushed a new image 2 weeks ago, `1.9.10`. A little more research showed me that the 2 effected environments had secrets rotated...and they received the updated image after they were restarted. All the other environments had tasks that had been running for 30+ days....so they were running on `1.9.9`.

In the task definition, I had the image declaration as `fluent/fluent-bit:1.9`.  I noticed `1.9.9` was several months old. Once I updated the task definition to explicitly pull `1.9.9`....the task ran as desired...no further issues.

Not sure what it is in the `1.9.10` release, but it bit us. We have .5 core and 512mb of memory allocated to that container. I initially beefed up the task and container cpu/memory...but that didn't help.

I am not sure how to troubleshoot this container, but happy to help in any way I can.

**Comment by patrick-stephens** [comment]
The 1.9.10 release did include containers, this was my fault as I triggered the process to push them based on the tag before realising this was a code-only release.

We can manually remove them but I think it would be better to understand what was wrong. There are debug images if that helps (they're a lot bigger but have shell, package manager and a suite of debug tools pre-installed).

**Comment by jamespgrant3** [comment]
I am very curious as to what the issue is. I will try using the debug container in a lower environment this week.
