### ISSUE TITLE
Record accessors with @ char not working in grep filters 

### ISSUE THREAD

**Issue by BlaBlaGITTE** [fluent/fluent-bit#6560]
## Bug Report

**Describe the bug**
Record accessors in filters with @ character causing fluent-bit error during filtering

**To Reproduce**
error in **/var/log/fluent-bit/fluent-bit.log** file: 
[2022/12/14 11:39:22] [error] [record accessor] bad input character '@' at line 1701606259
```
- Steps to reproduce the problem:
Filter used:
[FILTER]
    Name   grep
    Match  nginx
    Exclude $@fields['status'] 200

**Expected behavior**
I want exclude from my nginx logs, in JSON format, all occurrences that have HTTP status code equal 200.

single JSON line from log:
{
	"@timestamp": "2022-12-12T11:28:46+01:00",
	"@fields": {
		"msec": "1670840926.039",
		"remote_addr": "10.167.225.2",
		"remote_user": "-",
		"bytes": "70",
		"req_time": "0.057",
		"status": "200",
		"request": "GET /get_health_status HTTP/1.1",
		"verb": "GET",
		"real_ip": "10.10.9.8",
		"http_user_agent": "-"
	}
}

**My Environment**
* Version fluent-bit client used:
**fluent-bit-1.9.9**-1.x86_64
* Environment name:
nginx
* Server type and version:
Linux red-hat 7.x

**Related issue**
Similar issue already reported here:
https://github.com/aws/aws-for-fluent-bit/issues/311

**Comment by patrick-stephens** [comment]
A workaround might be to use a lua filter to strip all special characters for keys so you can then use the grep filter afterwards.

We probably need to capture the limitation as well here: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

**Comment by BlaBlaGITTE** [comment]
Ok thanks, is clear, I've solved with this workaround (no LUA for me) :
```

[FILTER]
    Name modify
    Match nginx
    Rename @fields fields
```
but, indeed, the problem still remain.
