### ISSUE TITLE
Trouble reading Ubuntu Environment variables

### ISSUE THREAD

**Issue by snowjunkie** [fluent/fluent-bit#657]
Hi,

I am having an issue with reading environment variables set in Ubuntu.
I set them in /etc/environment as per the ubuntu documentation https://help.ubuntu.com/community/EnvironmentVariables 

From a term I can see the variable from printenv and echo.

However when I run the fluent-bit record-modifier filter to add a tag to the record I receive a warning "[warn] [env] variable $myvar is used but not set". then [error] [filter_record_modifier] invalid record parameters, expects 'KEY VALUE'
I replaced with $HOSTNAME which works, and with a static value, but my own variable is not working.

Can you confirm a solution for Ubuntu 16.04 for this.  I thought setting variables in /etc/environment should work but seems to be a problem.
I'm assuming that it might be some profile that is resetting the variables such as sudo does.  In which case it would be good to have some clear guidance regarding this.

Thanks

**Comment by edsiper** [comment]
@snowjunkie how are you running fluent bit ?, through td-agent-bit package ?

**Comment by snowjunkie** [comment]
Yes through td-agent-bit running under systemctl management.

**Comment by edsiper** [comment]
Environment variables are functional through the new translator implemented some months ago. Closing this issue as fixed, if the issue persist, please let me know and we can re-open it.
