### ISSUE TITLE
request: new membership

### ISSUE THREAD

**Issue by Arhell** [fluent/fluent-bit#6576]
### GitHub Username

@Arhell

### List of contributions to the fluent project

https://github.com/fluent/fluentd-website/commits?author=arhell
https://github.com/fluent/fluent-bit-website-hugo/commits?author=Arhell

I want to support the project and help fix bugs and other problems that I find.

https://github.com/fluent/fluentd-website
https://github.com/fluent/fluent-bit-website-hugo

Thank you for your attention

**Comment by patrick-stephens** [comment]
Please raise on those projects.
