### ISSUE TITLE
http out plugin support PUT method

### ISSUE THREAD

**Issue by freesinger** [fluent/fluent-bit#6580]
**Is your feature request related to a problem? Please describe.**

I am using fluent-bit to export log of an OLAP DB named Doris, then storing log into an instance of Doris. Found stream_load API of Doris only support PUT, however, http out plugin supports only POST. It seems I have no idea to realize my purpose via http out plugin?
Or there is a solution for this scenario?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
A workaround might be to do an HTTP PUT call in a LUA filter and just have a null output after that. It's a bit dirty but should work until the feature is implemented.

**Comment by freesinger** [comment]
@patrick-stephens I have used Lua script to modify some fields of raw records, will this method make changes lost? Since OUTPUT stage is a dummy here

**Comment by patrick-stephens** [comment]
Filters are applied in order so just put one after your current one - or update your current one if it is the last one to send the data as well once it is finished?

**Comment by freesinger** [comment]
OK, can I get set multiple `call` in single Filter, instead of adding several Filters? Like:
```conf
[FILTER]
    Name    lua
    Match   *
    script  test.lua
    call    transform
    call    http.Put

**Comment by patrick-stephens** [comment]
Just put it in your function
