### ISSUE TITLE
mem_buf_limit for systemd input ?

### ISSUE THREAD

**Issue by Misterhex** [fluent/fluent-bit#659]
Tail plugin support "mem_buf_limit" for dealing with backpressure. Is this available for systemd input? if not, is there a way to control backpressure for this input?

Thanks.

**Comment by edsiper** [comment]
mem_buf_limit is a restriction applied to each input plugin that define that specific property. When a limit is reached (pause) or when a plugin can continue ingesting data (resume) is handled by specific callbacks. in_systemd supports that feature.

**Comment by Misterhex** [comment]
Thanks for helping, it seems the behaviour of `Mem_Buf_Limit` doesn't apply to this plugin still. 

It's seems memory usage would keep surging up, i am not sure if this is a memory leak issue or the backpressure mechanism (Mem_Buf_Limit) was not kicking in.

I am running this on openshift kubernetes:
fluentbit/fluentbit:0.13.7

my configuration is as follows:

```
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2021

@INCLUDE input-systemd.conf
@INCLUDE output-systemd-forward.conf

==== input-systemd.conf ====
[INPUT]
    Name            systemd
    Path            /var/log/journal
    Tag             systemd
    Systemd_Filter  _SYSTEMD_UNIT=atomic-openshift-master-api.service
    Systemd_Filter  _SYSTEMD_UNIT=atomic-openshift-master-controllers.service
    Systemd_Filter  _SYSTEMD_UNIT=atomic-openshift-node.service
    Systemd_Filter  _SYSTEMD_UNIT=etcd_container.service
    Systemd_Filter  _SYSTEMD_UNIT=docker.service
    Systemd_Filter  _SYSTEMD_UNIT=systemd-machined.service
    DB              /var/log/systemd.db
    Mem_Buf_Limitt  5MB

====output-systemd-forward.conf====
[OUTPUT]
    Name          forward
    Match         systemd
    Host          ${FORWARD_HOST}
    Port          ${FORWARD_SYSTEMD_PORT}
    Retry_Limit   False
 
$ oc adm top pod --containers
POD                              NAME                 CPU(cores)   MEMORY(bytes)
fluent-bit-cfz8t                 fluent-bit-systemd   22m          189Mi
fluent-bit-k4ghj                 fluent-bit-systemd   992m         295Mi
```

Thanks for helping

**Comment by Misterhex** [comment]
@edsiper , would you be able to help verify if my config is correct? thanks and much appreciated!

Not sure if this is related to #693

**Comment by edsiper** [comment]
Systemd plugin has been refactored since then and we have not seen any issue as this one reported.

Please upgrade to the last v1.3 release, if the issue persist we can re-open the ticket.
