### ISSUE TITLE
filter_kube: Invalid pattern for given tag

### ISSUE THREAD

**Issue by AkashKrDutta** [fluent/fluent-bit#661]
I am not able to get docker container logs and enrich them with kubernetes meta data. I keep on getting the following warning repeatedly and my logs are not enriched by K8s metadata. Warning is:
``` 
[ warn] [filter_kube] invalid pattern for given tag abc.def.var.lib.docker.containers.8af9d2b4e1f6d16ac0ac342ffaf24317557a873d6a343825de75b4436f580817.8af9d2b4e1f6d16ac0ac342ffaf2431
7557a873d6a343825de75b4436f580817-json.log
```

My config file for fluent-bit is:
```
    fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-*.conf
    @INCLUDE filter-*.conf
    @INCLUDE output-*.conf

    input-container.conf: |
   [INPUT]
       Name            tail
       Tag             abc.def.*
       Path            /var/lib/docker/containers/*/*.log
       Parser          docker

    filter-containers.conf: |
    [FILTER]
      Name                kubernetes
      Match               abc.def.*
      Kube_URL            https://kubernetes.default.svc.cluster.local:443
      Merge_Log           Off
      K8S-Logging.Parser  Off
      # Use_Journal         On

    [FILTER]
      Name        record_modifier
      Match       abc.def.*
      Record      tag abc.def


    output-containers.conf: |
   [OUTPUT]
       Name           kafka
       Match          abc.def.*
       Brokers        kafka-0:9092
       Topics         containers-logs-fluentbit.stream
       Timestamp_Key  @timestamp
       Retry_Limit    false
       rdkafka.log.connection.close false
       rdkafka.queue.buffering.max.kbytes 10240
       rdkafka.request.required.acks 1
    
```
What is the utility of `tag` in case of kubernetes filter. Is there a specific pattern that I must use for this variable when using kube_filter? 
Please help.

**Comment by edsiper** [comment]
You should try the path _/var/log/containers/*.log_, otherwise the regex will not be able to lookup pod_name and others generated in the symbolic links

**Comment by AkashKrDutta** [comment]
okay :)

**Comment by salla2** [comment]
> I am not able to get docker container logs and enrich them with kubernetes meta data. I keep on getting the following warning repeatedly and my logs are not enriched by K8s metadata. Warning is:
> 
> ```
> [ warn] [filter_kube] invalid pattern for given tag abc.def.var.lib.docker.containers.8af9d2b4e1f6d16ac0ac342ffaf24317557a873d6a343825de75b4436f580817.8af9d2b4e1f6d16ac0ac342ffaf2431
> 7557a873d6a343825de75b4436f580817-json.log
> ```
> 
> My config file for fluent-bit is:
> 
> ```
>     fluent-bit.conf: |
>     [SERVICE]
>         Flush         1
>         Log_Level     info
>         Daemon        off
>         Parsers_File  parsers.conf
>         HTTP_Server   On
>         HTTP_Listen   0.0.0.0
>         HTTP_Port     2020
> 
>     @INCLUDE input-*.conf
>     @INCLUDE filter-*.conf
>     @INCLUDE output-*.conf
> 
>     input-container.conf: |
>    [INPUT]
>        Name            tail
>        Tag             abc.def.*
>        Path            /var/lib/docker/containers/*/*.log
>        Parser          docker
> 
>     filter-containers.conf: |
>     [FILTER]
>       Name                kubernetes
>       Match               abc.def.*
>       Kube_URL            https://kubernetes.default.svc.cluster.local:443
>       Merge_Log           Off
>       K8S-Logging.Parser  Off
>       # Use_Journal         On
> 
>     [FILTER]
>       Name        record_modifier
>       Match       abc.def.*
>       Record      tag abc.def
> 
> 
>     output-containers.conf: |
>    [OUTPUT]
>        Name           kafka
>        Match          abc.def.*
>        Brokers        kafka-0:9092
>        Topics         containers-logs-fluentbit.stream
>        Timestamp_Key  @timestamp
>        Retry_Limit    false
>        rdkafka.log.connection.close false
>        rdkafka.queue.buffering.max.kbytes 10240
>        rdkafka.request.required.acks 1
>     
> ```
> 
> What is the utility of `tag` in case of kubernetes filter. Is there a specific pattern that I must use for this variable when using kube_filter?
> Please help.

Did u able to figure out this.. i'm having same issue so.. Thanks!

**Comment by alitoufighi** [comment]
@edsiper What if we want to use our tag pattern? The default pattern is hard and dirty to parse to use with other things like different outputs for different namespaces, etc. and we tried another tagging pattern, which caused us "invalid pattern for given tag" error for filter_kube.
I don't think adding metadata using name of file is a good idea (unless we don't have any other source of information), or at least, can Kubernetes filter use pattern used in tail input, and not the default one?
Or, how can we change Match pattern of Kubernetes filter to match our tagging pattern?

Here's our config:
```[INPUT]
        Name              tail
        #Tag               kube.*  # <-- This is the thing that kubernetes filter seems to use
        Tag               kube.<namespace_name>.<pod_name>.<container_name>   # This is what we want to use
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        K8S-Logging.Parser On
        Merge_Log         On
        Refresh_Interval  10

[FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log_Key       log
        Merge_Log           On
        Keep_Log            Off
```

**Comment by ankit1mg** [comment]
> @edsiper What if we want to use our tag pattern? The default pattern is hard and dirty to parse to use with other things like different outputs for different namespaces, etc. and we tried another tagging pattern, which caused us "invalid pattern for given tag" error for filter_kube.
> I don't think adding metadata using name of file is a good idea (unless we don't have any other source of information), or at least, can Kubernetes filter use pattern used in tail input, and not the default one?
> Or, how can we change Match pattern of Kubernetes filter to match our tagging pattern?
> 
> Here's our config:
> 
> ```
> [INPUT]
>         Name              tail
>         #Tag               kube.*  # <-- This is the thing that kubernetes filter seems to use
>         Tag               kube.<namespace_name>.<pod_name>.<container_name>   # This is what we want to use
>         Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
>         Path              /var/log/containers/*.log
>         Parser            docker
>         DB                /var/log/flb_kube.db
>         Mem_Buf_Limit     5MB
>         Skip_Long_Lines   Off
>         K8S-Logging.Parser On
>         Merge_Log         On
>         Refresh_Interval  10
> 
> [FILTER]
>         Name                kubernetes
>         Match               kube.*
>         Merge_Log_Key       log
>         Merge_Log           On
>         Keep_Log            Off
> ```
> 
> EDIT: I just figured out **`Regex_Parser`** in Kubernetes Filter is for this purpose. So, nothing. :))

@alitoufighi Is there any update on this? I am also trying to read logs from the different path from /var/log/containers/*.log path. Due to that, I am not able to add kubernetes metadata in the logs.

**Comment by da-head0** [comment]
@ankit1mg  did you solve using different path instead of /var/log/containers/*.log path & adding kubernetes metadata?

**Comment by DmitriGekhtman** [comment]
Same question here.

**Comment by heniamiri** [comment]
Any update on this ? I'm having exactly the same problem with the same configs

**Comment by alitoufighi** [comment]
@heniamiri You should set your `tail` input `Path` parameter to `/var/log/containers/*.log` instead of `/var/lib/docker/containers/*/*.log`

Note that Kubernetes Filter finds pod information only using the log file names, and these metadata are only present in the first mentioned format (which are symlinks to actual files in second format).

**Comment by NamelessHH** [comment]
So I had the same issue and I realized that this is happening because I'm not setting the `Kube_Tag_Prefix` option which defaults to `kube.var.log.containers.` which the filter attempts to remove and gives you this error warning if you don't have it set correctly.  like everyone here I shorent the prefix to `kube.` instead of the `kube.var.log.containers.` default that its set to.  if you just add that portion in your config it works like a charm.

WORKING
```
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Regex_Parser        k8s-custom-tag
        Kube_Tag_Prefix     kube.
```

NOT WORKING
```
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Regex_Parser        k8s-custom-tag
```

**Comment by michael-trusov** [comment]
Maybe it will be useful for somebody. You can find working configuration below.

Main points:
1. My configuration assumes that logs are located in '/var/log/services/*.log' folder (which is differ from the default location)
2. In my case log file name should have format ```<pod_name>_<namespace_name>_<container_name>.log```. Kubernetes plugin relies only on file name (in other words you need to have information about pod, namespace etc in file name), for my case I've excluded 'docker_id' part for file name (see kubernetes-tag parser)
4. It is important to specify Regex_Parser  in filter section and be sure that it describes file name format
5. It is important to specify Kube_Tag_Prefix  in filter section and be sure that it describes log file location

```
 fluent-bit.conf: |
    [SERVICE]
        Flush             5
        Log_Level         debug
        Daemon            off
        Parsers_File      parsers.conf
        HTTP_Server       Off
        HTTP_Listen       0.0.0.0
        HTTP_Port         2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/services/*.log
        parser            docker
        Tag               kube.*        
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  5

  filter-kubernetes.conf: |
    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_URL          https://kubernetes.default.svc:443
        Merge_Log         On          
        Keep_Log          Off
        Kube_Tag_Prefix   kube.var.log.services.
        Regex_Parser      kubernetes-tag

  output-elasticsearch.conf: |
    [OUTPUT]
        Name                 es
        Match                *
        Host                 ${FLUENT_ELASTICSEARCH_HOST}
        Port                 ${FLUENT_ELASTICSEARCH_PORT}
        HTTP_User            ${FLUENT_ELASTICSEARCH_USER}
        HTTP_Passwd          ${FLUENT_ELASTICSEARCH_PASSWD}
        Logstash_Format      On
        Logstash_Prefix      core-services-logs
        Replace_Dots         On
        Retry_Limit          False
        Suppress_Type_Name   On
        tls                  On        
        tls.verify           Off
        tls.ca_file          /opt/es/certs/ca.crt
        tls.crt_file         /opt/es/certs/tls.crt
        tls.key_file         /opt/es/certs/tls.key

  parsers.conf: |
    [PARSER]
        Name                 docker
        Format               json
        Time_Key             instant
        Time_Format          %Y-%m-%d %H:%M:%S.%L
        Time_Keep            On

    [PARSER]
        Name                 kubernetes-tag
        Format               regex
        Regex                (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)\.log$

```
