### ISSUE TITLE
fluentbit POD log type designation inquiry

### ISSUE THREAD

**Issue by audwl** [fluent/fluent-bit#6639]
Hello
AWS EKS is currently configured and Fluentbit is displayed as Daemonset to forward the log.
When sending logs from Fluentbit, is it possible to specify and separate types for each log?
I would like to ask if it is possible to apply Filter and deliver it separately by log such as Processing and Service.

**Comment by patrick-stephens** [comment]
Yes, look at the documentation on routing: https://docs.fluentbit.io/manual/concepts/data-pipeline/router
