### ISSUE TITLE
fluentbit send data to two kinesis stream 

### ISSUE THREAD

**Issue by Devatorres9** [fluent/fluent-bit#6640]
I am working on a system where in i need to filter data into 2 parts and send one part to one kinesis stream and another to the other kinesis stream. I have tried out grep but in that i am not able to filter the data into 2. 

[INPUT]
   Name forward
   unix_path /var/run/fluent.sock
   Mem_Buf_Limit 100MB
   Tag test_tag
[INPUT]
   Name forward
   unix_path /var/run/fluent.sock
   Mem_Buf_Limit 100MB
   Tag test_tag_dev

[FILTER]
   Name grep
   Match test_tag_dev
   Regex log INFO:root:

[OUTPUT]
   Name kinesis_firehose
   Match * 
   Region us-west-2
   delivery_stream devansh_stream

[OUTPUT]
   Name kinesis_firehose
   Match * 
   Region us-west-2
   delivery_stream dev_stream

**Comment by agup006** [comment]
Rewrite tag is going to be the best way to perform this
