### ISSUE TITLE
Error with v2.0.8

### ISSUE THREAD

**Issue by ashraf133** [fluent/fluent-bit#6643]
## Bug Report

**Describe the bug**
errors in logs after execution 

**To Reproduce**
Run fluentbit v2.0.8 and v2.0.4 with same conf file

@INCLUDE /tmp/inout.conf-{UID}

[SERVICE]

    flush        1
    daemon       Off
    log_level    debug
    parsers_file /tmp/parsers.conf-{UID}
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics off

```
V2.0.8 : 

Fluent Bit v2.0.8
--
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2023/01/04 15:38:24] [error] [/tmp/fluent-bit/src/config_format/flb_cf_fluentbit.c:290 errno=2] No such file or directory
[2023/01/04 15:38:24] [error] file=/tmp/plugins.conf
[2023/01/04 15:38:24] [ info] Configuration:

```
```
V2.0.4 : 


Fluent Bit v2.0.4
--
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
[2023/01/04 15:39:34] [ info] Configuration:
```

**Expected behavior**
No error in logs

**Comment by nokute78** [comment]
I think v2.0.4 ignores error silently.
Does v2.0.4 work correctly with that configuration file ?

https://github.com/fluent/fluent-bit/pull/6575 is to report error explicitly.
The patch was merged from v2.0.7.

**Comment by ashraf133** [comment]
Hello,

Both work correctly and i have logs collected but i don't know why he shows ``file=/tmp/plugins.conf``

**Comment by ashraf133** [comment]
I think the error is here : 

``
https://github.com/fluent/fluent-bit/blob/v2.0.8/src/config_format/flb_cf_fluentbit.c#L152

    if (ctx->root_path && path[0] != '/') {
        snprintf(tmp, PATH_MAX, "%s/%s", ctx->root_path, path);
        glb_path = tmp;
    }
    else {
        glb_path = path;
    }
``
he will find the relative path : plugins.conf
then he will concatinate 'root_path' i think it is equal to /tmp but i dont why lol
after that the result is : /tmp/plugins.conf


==>

So should we put absolute path or it will be fixed ?

**Comment by nokute78** [comment]
> Run fluentbit v2.0.8 and v2.0.4 with same conf file

Did you save the configuration file at /tmp ?
If so, Fluent-bit tries to load other configuration files from /tmp.

**Comment by ashraf133** [comment]
Yes the main configuration file is in /tmp. So i will put absolute path in the place of the relative and it will be fixed ;)
