### ISSUE TITLE
How should I install fluent-bit binary offline

### ISSUE THREAD

**Issue by DesireWithin** [fluent/fluent-bit#6649]
Our CentOS is offline, How should I download fluent-bit binary?
There is no related description in the document.
I try to visit `https://packages.fluentbit.io/centos/7/x86_64/`, but only 403 returned.
Here is a similar  stale issue #3469

**Comment by patrick-stephens** [comment]
It's a Yum repo so just do the standard thing of mirroring it in some fashion. There is plenty of information on doing this online, it's nothing specific to Fluent Bit:
- https://access.redhat.com/solutions/10154
- https://linuxtechlab.com/yum-to-download-packages-without-installing/

Various tools can handle this for you (e.g. Artifactory, etc. to create internal mirrors) or you can follow the instructions above/elsewhere to download the RPMs you need on a machine with access to the internet and then transfer them to your offline machine.

You cannot browse the site directly but you can pull the relevant files you need, this is why you get the 403.

**Comment by DesireWithin** [comment]
I notice that `https://packages.fluentbit.io/` is visible now. Thank you.
