### ISSUE TITLE
Fluentbit kafka config

### ISSUE THREAD

**Issue by AkshayDubey29** [fluent/fluent-bit#666]
Hi, We would like to configure the batch size and Kafka buffer parameter in fluent-bit Kafka configuration, Can anyone please help us to configure the same?

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     192.168.1.3:9092
    Topics      test

**Comment by yubobo** [comment]
like this:

  output-kafka.conf: |
    [OUTPUT]
        Name           kafka
        Match          *
        Brokers        10.196.99.99:9292
        Topics         test
        Timestamp_Key  @timestamp
        Retry_Limit    2
        rdkafka.log.connection.close false
        rdkafka.queue.buffering.max.ms 1000
        rdkafka.queue.buffering.max.messages 10000
        **rdkafka.batch.num.messages 2000**
        rdkafka.compression.codec none
        rdkafka.request.required.acks 1

**Comment by whithajess** [comment]
That rdkafka stuff is documented as available here: https://fluentbit.io/documentation/0.13/output/kafka.html and can be any: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
