### ISSUE TITLE
[2.x master] storage max_chunks_up is compared with total_chunks

### ISSUE THREAD

**Issue by PettitWesley** [fluent/fluent-bit#6663]
## Bug Report

storage `max_chunks_up` is compared with `total_chunks` instead of CIO `total_chunks_up`. 

I'm not an expert on this bit of the code base but this seems incorrect to me. The max chunks up option should be checked against the number of chunks up right? Am I misunderstanding how these parameters work?

See code here: https://github.com/fluent/fluent-bit/blob/master/src/flb_input_chunk.c#L1311

**Comment by edsiper** [comment]
hi @PettitWesley , thanks for catching this, it seems to be a bug.

@pwhelan can you take a look at this pls ? https://github.com/fluent/fluent-bit/commit/c42c4faf8e9aad87f9cfc20b535b3f0092c8af7a#diff-400dc531b019fa683ed5b361a69088bf0741d159d5408473a4801edbab5edae1R764

**Comment by pwhelan** [comment]
I believe @PettitWesley is correct. I'll open up a PR and do testing today.

**Comment by PettitWesley** [comment]
@pwhelan @edsiper Wait I think there's still a possible issue here or the designed/desired experience is not clear to me. 

So `storage.pause_on_chunks_overlimit` is a per-input setting. However, the `storage.max_chunks_up` is a global service level setting. 

However, the way the code actually works is that both of these are per-input settings. There is a separate CIO instance I think for each input, managing its chunks AFAICT, and each gets the same global limit. 

**Hence question**: Is the fact that you can't control `storage.max_chunks_up` on a per-input basis a user experience bug/gap? Since its equivalent to Mem_Buf_limit for filesystem storage case, and that setting is per input, I think we need this on a per input basis too. 

Below is current code after Phillip's change:
```
if (storage->type == FLB_STORAGE_FS) {
        if (i->storage_pause_on_chunks_overlimit == FLB_TRUE) {
            if (storage->cio-> total_chunks_up >= storage->cio->max_chunks_up) {
                return FLB_TRUE;
            }
        }
    }
```

**Comment by PettitWesley** [comment]
Also @pwhelan sorry there is another bug related to your change, the wrong value is used in the overlimit log messages as well: https://github.com/fluent/fluent-bit/blob/master/src/flb_input_chunk.c#L1394

**Comment by PettitWesley** [comment]
This was implemented

**Comment by agup006** [comment]
Closing
