### ISSUE TITLE
logs with opentelemetry

### ISSUE THREAD

**Issue by Gauravmeenu** [fluent/fluent-bit#6668]
Actually I'm just sending the apache logs to opentelemetry receiver (fluentforward) but I got stuck with fluent-bit.conf file can anyone help me to configure the  INPUT and OUTPUT in   fluent-bit.conf  so it should work with opentelemetry .

here is my fluent-bit.conf file looks like .

[SERVICE]
  Parsers_File          ./parsers.conf
  Flush                 1
  Log_level             info

[INPUT]
  Name                  tail
  Refresh_interval      5
  Path                  /var/log/app.log
  Read_from_head        true

[OUTPUT]
  Name  stdout
  Match *

[OUTPUT]
  Name forward 
  Match *
  Host localhost
  Port 8006

**Comment by Gauravmeenu** [comment]
@Syn3rman thank you for replying me actuallly fluent bit give me error like ( no up stream connection) means fluent can access with the opentelemetry .

**Comment by Syn3rman** [comment]
can you post your collector config as well? I'm assuming you've built a custom distribution using the [OpenTelemetry Collector Builder ](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder) (I'd also if you're running it in docker/there are any other possible sources for a networking issue)
I'm pretty sure that Fluent Bit is unable to reach the collector

**Comment by Gauravmeenu** [comment]
Yes @Syn3rman you are right I'm using my own collector distribution is there any issue regarding to this?

**Comment by Syn3rman** [comment]
No, I just wanted to have a look at the config file. Can you post this in the [FluentBit slack channel](https://launchpass.com/fluent-all) as well?

**Comment by Gauravmeenu** [comment]
Hey, @Syn3rman I got a solution maybe I think I did some mistake in my collector distribution with the components.go file with the receiver now it's running  thank you @Syn3rman for helping me and replying to me.
