### ISSUE TITLE
install.sh fails with error: /fluentbit.key: import read failed(2)

### ISSUE THREAD

**Issue by jelsdon** [fluent/fluent-bit#6679]
## Bug Report

**Describe the bug**
install.sh fails with `error: /fluentbit.key: import read failed(2).`
when FLUENT_BIT_PACKAGES_URL is undefined

**To Reproduce**
- Execute ./install.sh with FLUENT_BIT_PACKAGES_URL undefined
```
error: /fluentbit.key: import read failed(2).`
```

**Expected behavior**
Key is parsed successfully

**Your Environment**
* Version used: master branch / 16c4ec43079f220bdea3dab5269f1d65bd67a5c0

**Comment by patrick-stephens** [comment]
Yeah apologises, this crept in with some other packaging changes I did yesterday but thanks for the PR.

**Comment by patrick-stephens** [comment]
@jelsdon and others, there are a couple of other issues I'm resolving on https://github.com/fluent/fluent-bit/pull/6686 but depends on your specific target
