### ISSUE TITLE
Parser for Snort Alert

### ISSUE THREAD

**Issue by 19914039** [fluent/fluent-bit#6689]
as Fluent-bit supports reading log from snort alert file, we need to have a corresponding parser. 

I tried to form an REGEX expression that could parse the snort alert. Please find the same and add to the repository after testing and validating, so that it could be helpful to the community.

[PARSER]
    # for snort
    Name snort
    Format regex
    Regex /^((?:[0-9]{2}[-\/:.]){5}[0-9]{6}).*[{]TCP[}]\s*(((?:[0-9]{1,3}[.]){1,3}[0-9]{1,3}):([0-9]{1,6}))\s*->\s*(((?:[0-9]{1,3}[.]){1,3}[0-9]{1,3}):([0-9]{1,6}))
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep   On
    Time_Key start_time

**Comment by patrick-stephens** [comment]
Could you submit a PR for this?
