### ISSUE TITLE
in_tail: Increasing Mem_Buf_Limit leads to losing logs 

### ISSUE THREAD

**Issue by AkashKrDutta** [fluent/fluent-bit#669]
I have a configuration file that uses in_tail for reading docker container logs and out_kafka as the output. The problem that I face is that increasing the Mem_Buf_Limit to 100 MB leads to losing some of the logs while lowering the value to something like 5MB leads to ingressing more logs (that is the usual amount of log that doesn't miss any container logs). 

What is the role of Mem_Buf_Limit in this case? I read that it's useful parameter for avoiding backpressure. I must say I have large log files with high logging rate. AFAIK, Mem_Buf_Limit should be kept low in case fluent-bit is restarted as we might lose some MBs of log data. I don't see my fluent-bit being restarted, still increasing the value leads to log loss. 

The configuration is : 
```
input-container.conf: |
   [INPUT]
       Name              tail
       Tag               kube.*
       Path              /var/log/containers/*.log
       Parser            docker
       Mem_Buf_Limit     100MB
       Refresh_Interval  5
       Buffer_Chunk_Size 128k
       Buffer_Max_Size   4096k

filter-containers.conf: |
    [FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc.cluster.local:443
      Merge_Log           On
      K8S-Logging.Parser  On
      # Use_Journal         On

    [FILTER]
      Name        record_modifier
      Match       kube.*
      Record      tag cdp.containers

output-containers.conf: |
   [OUTPUT]
       Name           kafka
       Match          kube.*
       Brokers        kafka-0:9092
       Topics         containers-logs-fluentbit.stream
       Timestamp_Key  @timestamp
       Retry_Limit    false
       rdkafka.log.connection.close false
       rdkafka.queue.buffering.max.kbytes 10240
       rdkafka.request.required.acks 1

```
Thanks in advance!

**Comment by darashenka** [comment]
+1

**Comment by edsiper** [comment]
Mem_Buf_Limit aims to "limit" the amount or rate of data ingestion. If at some point its restricted it won't process more logs until the buffer is cleared up.

To avoid this situation enable file system buffering mechanism for the involved input plugin.

**Comment by arabustams** [comment]
Is it make sense to set "storage.type  filesystem" and "Mem_Buf_Limit     100MB" in input section at same time ?
```
[SERVICE]
    flush                     1
    log_Level                 info
    storage.path              /var/log/flb-storage/
    storage.sync              normal
    storage.checksum          off
    storage.backlog.mem_limit 5M

[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    storage.type      filesystem
    Mem_Buf_Limit     100MB
```

Also, I'm worried that buffer files will be stored unlimitedly, until backend comes back.
Can I monitor it?

**Comment by edsiper** [comment]
Yes, it makes sense. 

Mem_buf_Limit will ensure memory usage for the plugin and when the limit reaches, if filesystem buffering is enabled, will put new chunks into the file system and only load them once your memory usage by the plugin gets down.

**Comment by arabustams** [comment]
Thank you. I got it.

**Comment by rmacian** [comment]
> Yes, it makes sense.
> 
> Mem_buf_Limit will ensure memory usage for the plugin and when the limit reaches, if filesystem buffering is enabled, will put new chunks into the file system and only load them once your memory usage by the plugin gets down.

This should be noticed in the documentation. As it is, looks like you have to choose mem o disk, but does not explains that after memory is filled then is dumped to disk

**Comment by edsiper** [comment]
@rmacian thanks, I will make sure to add more details.

**Comment by arpit728** [comment]
What is default value of `Mem_Buf_Limit` doc. says it is disabled by default, does that mean buffer can grow till "out of memory" occurs.

**Comment by edsiper** [comment]
yes, no limits.

**Comment by Blobonat** [comment]
> > Yes, it makes sense.
> > Mem_buf_Limit will ensure memory usage for the plugin and when the limit reaches, if filesystem buffering is enabled, will put new chunks into the file system and only load them once your memory usage by the plugin gets down.
> 
> This should be noticed in the documentation. As it is, looks like you have to choose mem o disk, but does not explains that after memory is filled then is dumped to disk

Does this mean that if I use filesystem and have Mem_Buf_Limit set, the logs will ONLY be saved to disk when Mem_Buf_Limit is reached? My current understanding according to the documentation is that if File System is enabled, the logs are always saved to disk...

**Comment by georgej-github** [comment]
> > > Yes, it makes sense.
> > > Mem_buf_Limit will ensure memory usage for the plugin and when the limit reaches, if filesystem buffering is enabled, will put new chunks into the file system and only load them once your memory usage by the plugin gets down.
> > 
> > 
> > This should be noticed in the documentation. As it is, looks like you have to choose mem o disk, but does not explains that after memory is filled then is dumped to disk
> 
> Does this mean that if I use filesystem and have Mem_Buf_Limit set, the logs will ONLY be saved to disk when Mem_Buf_Limit is reached? My current understanding according to the documentation is that if filesystem is enabled, the logs are always saved to disk...

Also seeking clarification regarding the above question.

**Comment by trallnag** [comment]
@Blobonat, @georgej-github, the short answer is no. The official docs have a great page regarding this topic:

https://docs.fluentbit.io/manual/administration/buffering-and-storage

> Filesystem buffering enabled helps with backpressure and overall memory control.
Behind the scenes, Memory and Filesystem buffering mechanisms are not mutual exclusive, indeed when enabling filesystem buffering for your input plugin (source) you are getting the best of the two worlds: performance and data safety.

**Comment by liguangcheng** [comment]
@edsiper i do a test found that, fluent bit memory always growing, i set mem_buf_limit to 20M and set 3 input, so according to documentation, the fluent bit memory consume may by equal 60M or greater, but actually it consumes about 10G and finally oom, i can not understand why, can you give me a little  hint

**Comment by ahkui** [comment]
@liguangcheng 

maybe this default config `storage.max_chunks_up 128`

20M * 128 * 3 * 1.2 ≈ 10G

**Comment by leonardo-albertovich** [comment]
Could you please create a new issue with the appropriate context information @liguangcheng?

**Comment by liguangcheng** [comment]
@leonardo-albertovich @ahkui thanks for your advice, I tested past few days found there should be a problem with the way I use fluent-bit, fluent-bit acts as a stream processing, In principle, the files it monitors should not increase infinitely, In a system, the number of files it monitors should be limited, and the number should not be too many. If the number of files is unlimited, then the file handles opened in fluent bit are unlimited, because fluent bit does not know when these files will end , so it may cache a lot of file handles, so as the number of files keeps growing, the memory will keep rising.

So as a summary, we can either reduce the number of monitored files, or reduce the number of open file handles as soon as possible when there are many files.

Of course, unless we redesign the system, we can fundamentally reduce the number of files, but we can also reduce memory usage by setting `Ignore_Older` to close the file handle as soon as possible without redesigning
