### ISSUE TITLE
Authentication error while sending logs to GCP (2.0.8)

### ISSUE THREAD

**Issue by npvinhphat** [fluent/fluent-bit#6691]
## Bug Report

**Describe the bug**

Currently, there is an issue with sending logs to GCP. Authentication works at first (using supplied `GOOGLE_APPLICATION_CREDENTIALS`), however, when logs are ingested authentication failed.

Tested on `2.0.6` and there is no problem, so suggesting something changes in `2.0.8`

**To Reproduce**
- Example log message if applicable:
```
[2023/01/16 04:47:42] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal/
[2023/01/16 04:47:42] [debug] [output:stackdriver:stackdriver.1] JWT signature: [redacted]
[2023/01/16 04:47:42] [debug] [http_client] not using http_proxy for header
[2023/01/16 04:47:43] [ info] [oauth2] HTTP Status=200
[2023/01/16 04:47:43] [debug] [oauth2] payload
...
[2023/01/16 04:48:01] [debug] [output:stackdriver:stackdriver.1] [logging.googleapis.com/monitored_resource] not found in the payload
[2023/01/16 04:48:01] [debug] [http_client] not using http_proxy for header
[2023/01/16 04:48:01] [debug] [output:stackdriver:stackdriver.1] HTTP Status=401
[2023/01/16 04:48:01] [ warn] [output:stackdriver:stackdriver.1] error
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_TYPE_UNSUPPORTED",
        "metadata": {
          "service": "logging.googleapis.com",
          "method": "google.logging.v2.LoggingServiceV2.WriteLogEntries"
        }
      }
    ]
  }
}
```
- Steps to reproduce the problem:
Run the following command:
```
/opt/fluent-bit/bin/fluent-bit \
-v \
-i tail \
  -p "path=$HOME/logs/build_log.txt" \
-F record_modifier \
  -p 'Record=step mock-step' \
  -p 'Record=runner mock-runner' \
  -p 'Record=job_id mock-id' \
  -p 'Record=repository mock-org/mock-repo' \
  -m '*' \
-o file \
  -p "path=$HOME/logs" \
  -p 'file=build_log_structured.txt' \
  -m '*' \
-o stackdriver \
  -p "google_service_credentials=$HOME/google-creds" \
  -m '*' \
&
```

**Expected behavior**

Logs should be sent to GCP instead.

**Screenshots**

N/A

**Your Environment**

* Version used: 2.0.8
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): docker image myoung34/github-runner:ubuntu-bionic
* Server type and version: N/A
* Operating System and version: ubuntu
* Filters and plugins: tail/stackdriver

**Additional context**

Reported in Slack: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1673844884969809

**Comment by ridwanmsharif** [comment]
This was a bug introduced in 2.0.8. It's since been reverted but waiting on 2.0.9 to be released: https://github.com/fluent/fluent-bit/pull/6594 is the PR that merges the fix for what you're seeing.

**Comment by RicardoAAD** [comment]
I confirmed the issue is no longer reproducible in the master branch. PR https://github.com/fluent/fluent-bit/pull/6594 solved this issue.

**Comment by npvinhphat** [comment]
I can confirm that `2.0.9` fixed this issue. THanks for the support.
