### ISSUE TITLE
Linux packages script with specific version

### ISSUE THREAD

**Issue by npvinhphat** [fluent/fluent-bit#6692]
**Is your feature request related to a problem? Please describe.**

There is currently a bug on version `2.0.8` which prevents us from sending logs to GCP (https://github.com/fluent/fluent-bit/issues/6691). We use the common script provided to [install Linux version](https://docs.fluentbit.io/manual/installation/linux) of fluent-bit, and there is no way to specify the correct version.

**Describe the solution you'd like**

We would like to have a way to specify the version of fluent-bit to be installed.

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
The script is just a yum/apt helper, it sets up the repos for you and then you can just use a yum/apt method to pin the version you want.

We could possibly make the actual install optional so the repos are set up and then people can specify it that way using their tooling of choice.

**Comment by patrick-stephens** [comment]
Actually it was a quick one so set up https://github.com/fluent/fluent-bit/pull/6693

**Comment by patrick-stephens** [comment]
You can pull that commit until it is merged to use it: `curl https://raw.githubusercontent.com/fluent/fluent-bit/1db6cc0de8ce8f79a0188b6769e5178c3e1d1297/install.sh ...`

**Comment by npvinhphat** [comment]
Thanks for the quick response @patrick-stephens!
