### ISSUE TITLE
aborting with invalid flush value when launch with config file

### ISSUE THREAD

**Issue by freesinger** [fluent/fluent-bit#6696]
## Bug Report

**Describe the bug**
I'm using a custom output pugin, when starting flb it will report like:
![image](https://user-images.githubusercontent.com/20896930/212713784-8bf2d635-a58d-416f-9b16-efb263ff5dbd.png)

**To Reproduce**
fe-log.conf
![image](https://user-images.githubusercontent.com/20896930/212714245-789dd183-07df-4d03-a5db-aca72653f85d.png)

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 2.0.8
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Linux
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Can you include the raw text file in case there is a hidden character or similar in it?
Does it do it without any of the other extra parameters and custom plugins, i.e. is it definitely just the config file causing it rather than any complications around the extra plugin (e.g. memory corruption, etc.)?

**Comment by freesinger** [comment]
Here's raw text file of conf:
```conf
[SERVICE]
    flush 5
    log_level debug
    parsers_file fe-parser.conf

[INPUT]
    Name tail
    Path /home/wzy/selectdb/fe/log/fe.log
    Tag fe.log
    Parser fe-parser

[FILTER]
    Name lua
    Match fe.*
    Script filter.lua
    Call fe_filter

[OUTPUT]
    Name selectdb
    Match *
    host 127.0.0.1
    port 8030
    uri /api/doirs/dorislog/_stream_load
    format json
    strip_outer_array true
    enable_vectorized_engine true
    authorization Basic xxx
    expect 100-continue
```

I tried run my custome plugin by command
`fluent-bit -e /data/shane/flb/selectdb-logs-for-fluent-bit/output/flb_selectdb_output.so -i cpu -o selectdb`, which seems give right output after running(error log can be ignored)
![image](https://user-images.githubusercontent.com/20896930/212835600-eab14798-d3e7-40c3-84a0-eee4f41f0ccd.png)

Also tried to change `flush` to `1` and ran command `fluent-bit -e /data/shane/flb/selectdb-logs-for-fluent-bit/output/flb_selectdb_output.so -f fe-log.conf`, still got the `invalid flush value, aborting.` error.

Confused whether it blames conf or my implemtation of output plugin.
