### ISSUE TITLE
How do I add an 'AND' clause to the grep filter

### ISSUE THREAD

**Issue by mukundjalan** [fluent/fluent-bit#6708]
I am using fluentbit for my EKS cluster. I have setup everything that I had previously using fluentd but I am unable to configure this last bit.

    [FILTER]
        # remove service monitor metrics logs
        Name    grep
        Match   *
        Exclude $log_processed['authority'] /(.*:9090)/
        Exclude $log_processed['path'] /^/metrics$/

In the above filter, I want to exclude all those logs which fulfil `condition1 AND condition2` whereas the above filter works like `condition1 OR condition2`. How can I change this behaviour?

In fluentd, I had achieved the same using the `<and>` & `<exclude>` tags in xml configuration.

**Comment by RicardoAAD** [comment]
Hello @mukundjalan 
As you can see, @nokute78 has created this PR https://github.com/fluent/fluent-bit/pull/6721 to support multiple conditions.
You can achieve the AND condition by adding a second filter with the second condition as a workaround.
```
[FILTER]
    # remove service monitor metrics logs
    Name    grep
    Match   *
    Exclude $log_processed['authority'] /(.*:9090)/

[FILTER]
    # remove service monitor metrics logs
    Name    grep
    Match   *
    Exclude $log_processed['path'] /^/metrics$/
```

**Comment by mukundjalan** [comment]
@RicardoAAD thanks for suggesting the workaround but that won't work as I have other filters as well which are supposed to work independently of this filter and mixing this might cause other side effects I believe.

I will wait for PR created by @nokute78 to be merged.
