### ISSUE TITLE
Fluent Bit + Elastic Cloud providing just the API Key

### ISSUE THREAD

**Issue by berry2012** [fluent/fluent-bit#6727]
**Describe the solution you'd like**
The ability to use API key for `cloud_auth` 
Fluent Bit supports connecting to [Elastic Cloud](https://www.elastic.co/guide/en/cloud/current/ec-getting-started.html) providing just the cloud_id and the cloud_auth settings. cloud_auth uses the elastic user and password provided when the cluster was created. 

**Additional context**
To improve security posture, it can be safer to use API key to connect that using the username and password when the cluster was created. 

For example - send a request with an Authorization header that contains an ApiKey prefix followed by the API key credentials 
```
curl -H "Authorization: ApiKey VnVhQ2ZHY0JDZGJrUW0tZTVhT3g6dWkybHAyYXhUTm1zeWFrdzl0dk5udw==" \
http://localhost:9200/_cluster/health\?pretty 
```

Example configuration:
```
[OUTPUT]
    Name es
    Include_Tag_Key true
    Tag_Key tags
    tls On
    tls.verify Off
    Suppress_Type_Name On
    cloud_id elastic-obs-deployment:ZXVybxxxxxxxxxxxg==
    cloud_auth VnVhQ2ZHY0JDZGJrUW0tZTVhT3g6dWkybHAyYXhUTm1zeWFrdzl0dk5udw==
```

**Comment by patrick-stephens** [comment]
Just to check @berry2012, those are not valid credentials for your deployment right? If so you likely should rotate them.

**Comment by berry2012** [comment]
😃 those are not valid credentials

**Comment by flaschenpost** [comment]
Another option would be the possibility to add a generic HTTP_HEADER option and use it like in the curl call.
