### ISSUE TITLE
Feature Request: Add Geo-UP Filter/Plugin

### ISSUE THREAD

**Issue by sfrique** [fluent/fluent-bit#675]
It would be great if fluent-bit would add geo-ip info before sending to the output!

https://docs.fluentd.org/v0.12/articles/out_geoip

This way we can output directly to es or others.

Thanks!

**Comment by dperetti** [comment]
This is what we all crave for.

**Comment by aliasmee** [comment]
+1

**Comment by qnapnickchang** [comment]
+1

**Comment by dmarkey** [comment]
Possibly with a Lua plugin?

**Comment by agup006** [comment]
New GeoIP Filter available with 1.7.0 https://docs.fluentbit.io/manual/pipeline/filters/geoip2-filter Thanks all!
