### ISSUE TITLE
How to remove "log" field in Splunk event?

### ISSUE THREAD

**Issue by duj4** [fluent/fluent-bit#6757]
## Bug Report

**Describe the bug**
Once log is sent to Splunk via HEC, there is a field named "log" in event, how could I remove it?

**To Reproduce**
```
"ftw test"
```
- Steps to reproduce the problem:
1. Configure Splunk output plugin
2. Disable Splunk_Send_Raw

**Expected behavior**
No "log" field in event.

**Screenshots**
![Snipaste_2023-01-31_13-24-08](https://user-images.githubusercontent.com/19278537/215684748-fdf1caad-d3a9-476f-ac15-cc0571cb4b9f.png)

**Your Environment**
* Version used:2.0.8
* Configuration:`
[INPUT]
    Name              tail
    Tag               jsm_on_centos8-2
    Path              /home/dujas/fluent-bit/conf/inputs/event_fields_test.log
    DB                /home/dujas/fluent-bit/db/test.db
    Read_from_Head    True
    Buffer_Chunk_Size 20480KB
    Buffer_Max_Size   20480KB
    multiline.parser  java

[OUTPUT]
    Name             Splunk
    Match            *
    Host             centos8-1
    Port             8043
    tls              on
    tls.verify       on
    tls.ca_file      /home/dujas/certs/ca.pem
    tls.crt_file     /home/dujas/certs/centos8-2_all.pem
    tls.key_file     /home/dujas/certs/centos8-2.key
    tls.key_passwd   <password>
    Splunk_Token     493e8d74-cd37-4397-9e2b-5c04d586ab2b
    Splunk_Send_Raw  off
    event_host       ${HOSTNAME}
    event_source     fluent-bit
`
* Environment name and version (e.g. Kubernetes? What version?): Virtual Machine
* Server type and version:Virtual Machine
* Operating System and version: centos8
* Filters and plugins: tail for input and splunk for output

**Additional context**
No idea why log file sent to Splunk via splunk output plugin will be added a field named "log".

**Comment by patrick-stephens** [comment]
It's the actual log message line from the file.

The tail plugin adds the line as a key if no parsing is done, you can control the name but it defaults to OR which `log`

https://docs.fluentbit.io/manual/pipeline/inputs/tail

The docs cover what you need to do in raw mode and say you need to populate the event key if you use it: https://docs.fluentbit.io/manual/pipeline/outputs/splunk

You can use a parser to convert your log data into various formats as appropriate for your needs.
- https://docs.fluentbit.io/manual/concepts/data-pipeline/parser
- https://docs.fluentbit.io/manual/concepts/data-pipeline/filter

**Comment by duj4** [comment]
> It's the actual log message line from the file. Can you confirm raw mode is disabled as I think it should be nested under the event key if it is? Is it under the event key there?
> 
> The tail plugin adds the line as a key if no parsing is done, you can control the name but it defaults to OR which `log`
> 
> https://docs.fluentbit.io/manual/pipeline/inputs/tail
> 
> The docs cover the data format and raw mode: https://docs.fluentbit.io/manual/pipeline/outputs/splunk
> 
> You can use a parser to convert your log data into various formats as appropriate for your needs.
> 
> * https://docs.fluentbit.io/manual/concepts/data-pipeline/parser
> * https://docs.fluentbit.io/manual/concepts/data-pipeline/filter

Hi Patrick,
Yes, field "log" is under event and "Splunk_Send_Raw" is turned off. Well, I just want to remove the field and leave the log as it is.

**Comment by duj4** [comment]
close issue for now
