### ISSUE TITLE
NO_PROXY matches only exact domain names

### ISSUE THREAD

**Issue by seblaz** [fluent/fluent-bit#6759]
## Bug Report

**Describe the bug**
It's the same as described in #3907 and #3619

**Comment by seblaz** [comment]
No stale

**Comment by zisom-hc** [comment]
This long-standing issue has caused significant pains when utilizing fluent bit for log forwarding. Please consider implementing the proposed change that a member attempted to implement [here](https://github.com/fluent/fluent-bit/pull/3913)

**Comment by phwissmann** [comment]
This is a serious defect, especially since it is documented differently.

Also, I really don't understand why these issues get closed by a bot after short time of 5 days....

**Comment by michael-o** [comment]
Same issue within a corporate environment.
