### ISSUE TITLE
Storage metrics are confusing

### ISSUE THREAD

**Issue by cameronattard** [fluent/fluent-bit#6764]
**Is your feature request related to a problem? Please describe.**

Looking at the current storage metrics available:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/8992761/215912401-6c71335a-0c42-45fa-8bd1-311c0b92c5c4.png">

The relationship and/or difference between the `fluentbit_storage_*` metrics and the `fluentbit_input_storage_*` metrics is not immediately clear in the documentation, nor from my searches in Slack. My assumption is that `fluentbit_input_storage_*` each have unique series for each input plugin. However, what are the `fluentbit_storage_*` metrics actually measuring? What I'm particularly interested in is if they are simply aggregating all of the `fluentbit_input_storage_*` metrics, or if they're actually measuring the output buffers as opposed to the input buffers.

**Describe the solution you'd like**
Clarify in the documentation or provide an answer here and I can raise a PR.

**Describe alternatives you've considered**

**Additional context**

**Comment by Syn3rman** [comment]
FWICT, fluentbit_input_storage_* provides data about the number of chunks used by the input plugins while fluentbit_storage_* provides data about the global storage system (plugins and core engine)
