### ISSUE TITLE
in_tail: remove pod stuck in terminating when in_tail plugin monitor pod's mounting volume file

### ISSUE THREAD

**Issue by geniusjoe** [fluent/fluent-bit#6770]
## Bug Report

**Describe the bug**
I often use in_tail plugin to collect logs in following 2 ways:
way1: If one monitored pod print log to stdout, then fluent-bit pod needs to mount node root path and monitor file like
 `/rootfs/var/log/pods/<namespace>_<pod_name>_<pod_id>/<container_name>`, this work fine.
way2: If one monitored pod is important and print log to a **mounted volume**, then fluent-bit pod needs to mount node root path and monitor file like `/var/lib/docker/overlay2/<container_id>/merged/<path-to-monitor-file>` (assume using docker runtime with [overlay2 storage](https://www.adaltas.com/en/2021/06/03/linux-overlay-filesystem-docker/#:~:text=Overlay%20in%20Docker&text=Docker%20uses%20the%20overlay%20filesystem,lib%2Fdocker%2Foverlay2%20folder.)). 

Sometimes when I need to restart a way2 monitored pod, I notice this pod will stuck in terminating status, and 
kubelet delete pod containers timeout.
![image](https://user-images.githubusercontent.com/37236056/215760320-38cfc264-3fd3-444d-9a2d-7b6739da1a49.png)

There are some [discussions](https://stackoverflow.com/a/57023736/10064702) about deleting pod failed. One of possible reasons is docker mount leaking into some other namespace:
A pod needs to unmount all volumes before finish terminating, and [it's necessary](https://unix.stackexchange.com/a/502516/382799)  to close all related file descriptors before unmount one volume. Kubenetes will kill all processes in this deleting pod, so file descriptor can automatically be closed and it's ok. But once fluent bit starts to monitor a mounted volume file using path like `/var/lib/docker/overlay2/<container_id>/merged/<path-to-monitor-file>`, fluent-bit it's in fact holding mounted volume file descriptors and never close them. So that the deleting pod is waiting for closing all file descriptors forever and stuck in terminating. 

**To Reproduce**
- create a pod1 with a mounted volume(both pvc or nfs are ok) in namespace1
- create a file1 in pod1 mounted volume, and print log to it
- create a pod2 which contains fluent-bit container in namespace2, and mount node root path
- get pod1 container id, and edit fluent-bit config to monitor file1 using path like `/<mount_node_root_path>/var/lib/docker/overlay2/<container_id>/merged/<path-to-monitor-file>`
- delete pod1 so that pod1 will stuck in terminating status

**Expected behavior**
Pod1 needs to be deleted successful.

**Your Environment**
* Version used: 
1.7.9 with official dockerfile, but change base image to debian:buster-slim
* Configuration: 
```
[INPUT]
    Name                 tail
    Mem_Buf_Limit        10MB
    Buffer_Chunk_Size    32k
    Buffer_Max_Size      32k
    Path                 <path_to_my_log>  # here I add a soft link to mounted file so that the path can fulfill custom parser format
    Path_Key             @filepath
    Tag                  test1.*
    Db                   <path_to_flb_db>
    Db.sync              full
    Rotate_Wait          60
    Skip_Long_Lines      On
    Read_from_Head       True
    Alias                test1_input

[FILTER]
    Name                 kubernetes
    Match                test1.*
    Kube_URL             https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
    Kube_CA_File         /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File      /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix      test1.<path_to_my_log>.
    Regex_Parser         my_custom_regex
    Merge_Log            On
    Alias                test1_filter

[OUTPUT]
    Name                 kafka
    Match                test1.*
    Brokers              <kafka_ip>:9092
    Topics               kafkaTest1
    Timestamp_Key        @timestamp
    Timestamp_Format     double
    Alias                test1_output
```
* Environment name and version:
Kubernetes 1.18.4 and 1.20.6
* Server type and version:
Intel Xeon Cascade Lake 8255C
* Operating System and version:
TencentOS Server 3.1 (seems like centos)
* Filters and plugins:
in_tail and out_kafka plugins

**Additional context**
I think we can regularly delete out-dated files to fix this issue:

1. We can add a code snippet in flb_tail_file_purge function, it will delete all files in files_event list which are not updated for a long time. Code example below:
```
#ifdef FLB_HAVE_SQLDB
    mk_list_foreach_safe(head, tmp, &ctx->files_event) {
        file = mk_list_entry(head, struct flb_tail_file, _head);
        time_t mtime = flb_tail_stat_mtime(&st);
        if (mtime > 0) {
            if (now - mtime > 15*60L) {    # files which are not updated in 15mins will be deleted
                flb_tail_file_remove(file);
            }
        }
    }
#endif
```

2. we also need to set older_than property after first call to `flb_tail_scan` function, so that we can only add currently updated files to files_static list. Code example below:
```
    /* Scan path */
    flb_tail_scan(ctx->path_list, ctx);

    /*
     * After the first scan (on start time), all new files discovered needs to be
     * read from head, so we switch the 'read_from_head' flag to true so any
     * other file discovered after a scan or a rotation are read from the
     * beginning.
     */
    ctx->read_from_head = FLB_TRUE;
    
#ifdef FLB_HAVE_SQLDB
    ctx->ignore_older = 5*60L;   # only updated in 5mins file will be added to files_static list
#endif
```
There are some scenarios after code updated:
1. constantly writing data to a file:
This file will be moved from files_static list to files_event list after in_tail plugin finishes scaning all content in the file. In_tail plugin uses inotify to monitor file changes in file_event list. Once new data arrive, inotify will send an event signal to in_tail plugin to collect in-coming data. This file is still being updated, so it will not be deleted from the files_event list. Code changes will not affect on the file.
2. stop writing data to a file:
This file will be removed from files_event list after a period of time. Due to no new data coming in, file will not be added to files_static list. This can also decrease file descripor number and ease inotify pressure.
3. stop writing data to a file then start to write again after a period:
This file will be removed from files_event list after a period of time. Then `flb_tail_scan_callback` function will find this file has been updated recently and add this file to files_static list after rewriting data to this file. Since `flb_tail_file_remove` function does not clean file offset in sql db, we can easily track previous file offset from db and continue to collect data again.
4. delete a pod:
Kubernetes will send SIGTERM and SIGKILL signals to all processes in the deleting pod. And after killed process stop writing data, this file will be removed from files_event list and file descriptor will be closed. Then It's possible for kubelet to unmount volume and success to terminate this pod.

Are there any questions or advice? Please feel free to let me know and I can also make a PR.

**Comment by geniusjoe** [comment]
I'm sorry but this issue bother me for a few while. Feel free to contact to me if you need any further information. 😂
@patrick-stephens  @edsiper

**Comment by edsiper** [comment]
Hey! Please check if the issue is reproducible with v2.0.9

**Comment by geniusjoe** [comment]
> Hey! Please check if the issue is reproducible with v2.0.9

@edsiper Hey edsiper! Last months I'm a little busy and I'm sorry for late reply.
I tested this issue with v2.0.9 fluent-bit, and I find this problem still exists. And I think v.2.0.9 fluent-bit still hold file descriptors and never purge them.
```
{"log":"Fluent Bit v2.0.9\n","stream":"stderr","time":"2023-05-02T17:51:38.22529963Z"}
{"log":"* Copyright (C) 2015-2022 The Fluent Bit Authors\n","stream":"stderr","time":"2023-05-02T17:51:38.225323391Z"}
{"log":"* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd\n","stream":"stderr","time":"2023-05-02T17:51:38.225328192Z"}
{"log":"* https://fluentbit.io\n","stream":"stderr","time":"2023-05-02T17:51:38.225332185Z"}
......
[2023/05/03 15:31:37] [debug] [input:tail:test1_input] scan_blog add(): dismissed: /var/log/test1/xxxxxxxxxxxx/dpkg.log, inode 196741
```
The monitored pod with a nfs mounted volume still stuck in terminating status.
```
spec:
  volumes:
  - name: test1
    nfs:
      path: /wydy7frk
      server: 10.0.96.46
......
status:
    state:
      terminated:
        containerID: docker://e3f608f1108afc11dc97e5b59221300e6a71df9b295bb32cb495ee8fdd1b0777
        exitCode: 0
        finishedAt: "2023-05-02T18:38:37Z"
        reason: Completed
        startedAt: "2023-04-04T12:56:11Z"
```
I notice that fluent-bit can purge outdated files from `files_event` list if we set `ignore_older` property. 
```
    if (ctx->ignore_older > 0) {
        mtime = flb_tail_stat_mtime(&st);
        if (mtime > 0) {
            if ((ts - ctx->ignore_older) > mtime) {
                flb_plg_debug(ctx->ins, "purge: monitored file (ignore older): %s",
                              file->name);
                flb_tail_file_remove(file);
                return FLB_TRUE;
            }
        }
    }
```
So I think we can check if user set `ignore_older` properties, and if not, then we can set a default `ignore_older` properties after `flb_tail_scan` function call to pruge monitored files automatically. Like below:
```
    /* Scan path */
    flb_tail_scan(ctx->path_list, ctx);

    /*
     * After the first scan (on start time), all new files discovered needs to be
     * read from head, so we switch the 'read_from_head' flag to true so any
     * other file discovered after a scan or a rotation are read from the
     * beginning.
     */
    ctx->read_from_head = FLB_TRUE;

    if(ctx->ignore_older == 0){
          ctx->ignore_older = 5 * 60L;
    }

```
I add these codes and test again. Now monitored pods can be terminated successfully and everything work just fine.
So should we add an `auto_purge` property, or should we add a default `ignore_older` property value to auto purge outdated files into the main stream? 😂
