### ISSUE TITLE
filter_lua: tostring appends type information. string.format causes PANIC.

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#678]
## Bug Report

**Describe the bug**
`tostring`  appends type information. (e.g. `10ULL`)
`string.format` causes PANIC.
```sh
[taka@localhost build]$ bin/fluent-bit -c dummy.conf 
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/10 20:51:28] [ info] [engine] started (pid=18759)
PANIC: unprotected error in call to Lua API (./cat.lua:4: bad argument #2 to 'format' (number expected, got cdata))
```

**To Reproduce**

dummy.conf:
```python
[INPUT]
    Name dummy
    Tag  test
    Dummy  {"id":10, "prefix":"id_is_"}

[FILTER]
    Name   lua
    Match  *
    script ./cat.lua
    call   cat

[OUTPUT]
    Name  stdout
    Match *
```

cat.lua:
```lua
function cat(tag, timestamp, record)
   new_record = record
   new_record["NEW"] = record["prefix"] .. tostring(record["id"])
--    {"NEW"=>"id_is_10ULL", "prefix"=>"id_is_", "id"=>10}]

--   new_record["NEW"] = record["prefix"] .. string.format("%u",record["id"])
--   PANIC: unprotected error in call to Lua API (./cat.lua:4: bad argument #2 to 'format' (number expected, got cdata))

   return 1, timestamp, new_record
end
```

result is
```
[taka@localhost build]$ bin/fluent-bit -c dummy.conf 
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/10 20:59:23] [ info] [engine] started (pid=19294)
[0] test: [1531223964.000382184, {"NEW"=>"id_is_10ULL", "prefix"=>"id_is_", "id"=>10}]
[1] test: [1531223965.000737905, {"NEW"=>"id_is_10ULL", "prefix"=>"id_is_", "id"=>10}]
[2] test: [1531223966.001210927, {"NEW"=>"id_is_10ULL", "prefix"=>"id_is_", "id"=>10}]
[3] test: [1531223967.000512599, {"NEW"=>"id_is_10ULL", "prefix"=>"id_is_", "id"=>10}]
```

**Expected behavior**
```
[0] test: [1531223964.000382184, {"NEW"=>"id_is_10", "prefix"=>"id_is_", "id"=>10}]
```

**Your Environment**
* Version used: v0.14 (11b89869bc74b9ca070f015fe1ba77b29137022c)
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): ? 
* Server type and version: ?
* Operating System and version: CentOS 6.10
* Filters and plugins: see above

**Note**

There is a workaround.  `string.match` helps us.
```lua
function cat(tag, timestamp, record)
   new_record = record
   new_record["NEW"] = record["prefix"] .. string.match(tostring(record["id"]), '-*%d+')
   return 1, timestamp, new_record
end
```

**Cc**
 @manuelluis 
Sorry to bother you again..

**Comment by manuelluis** [comment]
From: http://luajit.org/ext_ffi_api.html

## Extended Standard Library Functions
The following standard library functions have been extended to work with cdata objects:

**n = tonumber(cdata)**
    Converts a number cdata object to a double and returns it as a Lua number. This is particularly useful for boxed 64 bit integer values. Caveat: this conversion may incur a precision loss.

**s = tostring(cdata)**
    Returns a string representation of the value of 64 bit integers ("nnnLL" or "nnnULL") or complex numbers ("re±imi"). Otherwise returns a string representation of the C type of a ctype object ("ctype<type>") or a cdata object ("cdata<type>: address"), unless you override it with a __tostring metamethod (see ffi.metatype()).

**iter, obj, start = pairs(cdata)**
**iter, obj, start = ipairs(cdata)**
    Calls the __pairs or __ipairs metamethod of the corresponding ctype.


You can use **tonumber**
```
function cat(tag, timestamp, record)
   new_record = record
   new_record["NEW"] = record["prefix"] .. tonumber(record["id"])
   return 1, timestamp, new_record
end
```
```
$ bin/fluent-bit -c t1.conf 
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/10 16:55:08] [ info] [engine] started (pid=1844)
[0] test: [1531234509.000293254, {"NEW"=>"id_is_10", "prefix"=>"id_is_", "id"=>10}]
```

I can check if it's possible and make sense to overwrite tostring for 64 bit integers.

**Comment by edsiper** [comment]
Since 0.14 release will be shortly (1-2 weeks) I suggest we manage all these integer/float changes support in a future version (0.14.x) and in the meanwhile just manage all returned numbers as double. Comments ?

**Comment by manuelluis** [comment]
This is not a bug. It's how cdata and lua jit works.
The function **tostring** works as expected with cdata integers (appending LL or ULL)  and the call to **string.format** has wrong arguments.

If we do not want to deal with the "limitations'' or ''complexities''  of cdata integers, we can use only LUA_TNUMBER but I think that cause some problems if they are all converted to double.

For example if we have some field in a log that is an UNIX timestamp and we send the output as json maybe the destination cannot parse the field since it would be decimal number and it's expecting a integer.

1531347837 vs 1531347837.000000 

For me, the use LUA_TNUMBER with the distinction of integers is ok, but it has some inconsistencies as we have seen. We will have the same type of problems if all integers that pass through the lua filter are converted to doubles. At least if we distinguish between integer an doubles in LUA_TNUMBER  we can preserver integers at the cost of converting some doubles to integers, but this numbers as strings are perfectly parseable as doubles in the other case (all doubles) not .

**Comment by manuelluis** [comment]
With #679 fluent-bit will not exit on Lua VM panic.

```
$ bin/fluent-bit -c test.conf 
Fluent-Bit v0.14.0
Copyright (C) Treasure Data

[2018/07/12 02:30:36] [ info] [engine] started (pid=9772)
[2018/07/12 02:30:36] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[2018/07/12 02:30:37] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[2018/07/12 02:30:38] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[2018/07/12 02:30:39] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[2018/07/12 02:30:40] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[0] test: [1531355437.000052689, {"id"=>10, "prefix"=>"id_is_"}]
[1] test: [1531355438.000038403, {"id"=>10, "prefix"=>"id_is_"}]
[2] test: [1531355439.000052808, {"id"=>10, "prefix"=>"id_is_"}]
[3] test: [1531355440.000021073, {"id"=>10, "prefix"=>"id_is_"}]
[4] test: [1531355441.000028442, {"id"=>10, "prefix"=>"id_is_"}]
[2018/07/12 02:30:41] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[2018/07/12 02:30:42] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
[2018/07/12 02:30:43] [error] [filter_lua] Lua PANIC: ./cat.lua:6: bad argument #2 to 'format' (number expected, got cdata)
```

**Comment by nokute78** [comment]
@manuelluis  Thank you for your advice!

@edsiper If it will be released soon, I think it is better to announce filter_lua is "experimental".
(e.g. help text or release note)

> integer / double 

I propose an new option to indicate a key name which will be converted integer.
```
C - (LUA_TNUMBER) -> Lua - (double (default) ) -> C
C - (LUA_TNUMBER) -> Lua - (integer (If the option is defined) ) -> C
```

The behavior I reported is a spec of lua, but I think it seems to be odd for users who don't know filter_lua treats cdata as a number.
And the number which is generated in lua  will be double in C, can't be integer.


```lua
function add_int(tag, timestamp, record)
   new_record = record
   new_record["int"] = 10 -- will be double
   
   return 1, timestamp, new_record
end
```

It is the reason why filter_lua needs the option to convert integer.

**Comment by edsiper** [comment]
I am wondering if end-users really cares about decimal v/s integer..

**Comment by nokute78** [comment]
> decimal v/s integer

Some users are interested in type casting, so I think they wants to take care about int/double.

e.g 
Fluentd supports type casting feature.
https://github.com/fluent/fluentd/pull/224

refer to https://www.fluentd.org/plugins
filter_typecast plugin is downloaded 25000+

Some questions are posted.
https://stackoverflow.com/questions/39525696/fluentd-convert-field-to-integer
https://stackoverflow.com/questions/43497042/how-in-fluentd-convert-field-type

**Comment by edsiper** [comment]
Since #679 is in place I think we are good. @manuelluis @nokute78 are you OK to close this ticket?

**Comment by nokute78** [comment]
@edsiper 
#679 is not a patch to fix this issue.

I prefer 220b8b0ca53f3bd25928594e1808ac06e67b3d5f is proper to release as 0.14 currently.
The commit is to treat LUA_TNUMBER as integer/double.

This issue is caused by treating CDATA as integer/double.
I think LUA_TNUMBER is better for user. 
It's a standard way to deal with number and I believe it helps to be widely used.
(refer to luajit type conversion document http://luajit.org/ext_ffi_semantics.html)

We still have type conversion issue even if we use CDATA.
> the number which is generated in Lua will be double in C, can't be integer.

So I follow your opinion. (We try to fix conversion error at 0.14.x.)

**Comment by edsiper** [comment]
thanks for the feedback, for now for 0.14 release I have reverted the following commits in GIT Master

- 11b89869
- 44dabecc
- 399953ae

**Comment by nokute78** [comment]
Close this issue. Filter_lua is reverted and we treat LUA_TNUMBER as integer/double.
