### ISSUE TITLE
Can't configure parser for displaying log in Grafana

### ISSUE THREAD

**Issue by rafalwolny** [fluent/fluent-bit#6791]
## Bug Report / question

I have a problem with configuring FluentBit to parse the JSON log, in the way Grafana can display it correctly, which means for me:

- encoding UTF8 characters in the log message, not displaying them as a plain text
- showing only log message (value of the "log" key) in Grafana, not the whole JSON

Initially there was no problem with FluentBit in its default config, which comes with [loki-stack 2.8.8](https://github.com/grafana/helm-charts/tree/loki-stack-2.8.8/charts/loki-stack) helm chart, but we wanted S3 output as well and it's not supported in that version. **Now I'm trying to achieve the same thing, with the same Loki but different FluentBit deployed with this chart -> [fluent-bit 0.23.0](https://github.com/fluent/helm-charts/tree/fluent-bit-0.23.0)**

I went through the documentation, I tried many different configs to get it right, as it was with loki-stack and I did it but not exactly - many important kubernetes labels were not mapped (container, namespace, pod) and even lost, **so I reverted changes and best I can get is this:**

<img width="1207" alt="Screenshot 2023-02-06 at 14 59 37" src="https://user-images.githubusercontent.com/47817187/216991607-3cb81fcb-bee4-49bc-b495-29ffb428eecf.png">

**Config I use right now and used to produce the log in the screenshot above**
```
  custom-parsers.conf: |
    [PARSER]
        Name custom_docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Decode_Field_As escaped_utf8 log
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Parser custom_docker

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log Off
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Labels On

    [OUTPUT]
        Name loki
        Match *
        host loki-stack
        port 3100
        labels job=fluent-bit, container=$kubernetes['container_name'], namespace=$kubernetes['namespace_name']
        drop_single_key on
        remove_keys kubernetes
```

**Config which solved the problem only partly:**
_which means I was able to encode UTF8 characters and log message was displayed instead of the whole JSON_

```
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
          Parser docker
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Merge_Log Off
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Labels On
    outputs: |
      [OUTPUT]
          Name loki
          Match *
          host loki-stack
          port 3100
          labels job=fluent-bit
          drop_single_key on
          line_format key_value
          remove_keys kubernetes
          auto_kubernetes_labels on
    customParsers: |
      [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Decode_Field_As escaped_utf8 log
```

**Expected behavior**

- encoding UTF8 characters in the log message, not displaying them as a plain text
- showing only log message (value of key "log") in Grafana, not the whole JSON
- mapping kubernetes labels such as container_name -> container, namespace_name -> namespace, pod_name -> pod etc.
- example expected log in Grafana:

<img width="958" alt="Screenshot 2023-02-06 at 15 22 43" src="https://user-images.githubusercontent.com/47817187/216996553-da5fe772-7eff-4c82-bff8-b7245a8effdd.png">

**Your Environment**

* FluentBit version used: v2.0.8
* FluentBit helm chart: [fluent-bit 0.23.0](https://github.com/fluent/helm-charts/tree/fluent-bit-0.23.0)
* Kubernetes version: 1.24.8
* Loki version: 2.6.1
* Loki helm chart: [loki-stack 2.8.8](https://github.com/grafana/helm-charts/tree/loki-stack-2.8.8/charts/loki-stack)

**Additional context**
If it's not a bug please let me know what I'm doing wrong, I already spent to much hours on that :(

**Comment by patrick-stephens** [comment]
One thing to note is the Grafana Fluent Bit image uses an entirely different Loki output plugin, or at least used to as there was some discussion about deprecating it.

Is the behaviour different for the plugins then? It sounds like something we should resolve.

Can you show the stdout plugin output with your config along with what that should be? That should narrow the issue down then to either something before output or the output plugin itself.

**Comment by patrick-stephens** [comment]
One thing to note is the Grafana Fluent Bit image uses an entirely different Loki output plugin, or at least used to as there was some discussion about deprecating it.

Is the behaviour different for the plugins then? It sounds like something we should resolve.

Can you show the stdout plugin output with your config along with what that should be? That should narrow the issue down then to either something before output or the output plugin itself.

You're also saying to add Kubernetes keys but then also remove them which is strange.

**Comment by rafalwolny** [comment]
Hmm I think I didn't explain it well. Long story short - I can't make fluent to parse/remove unwanted part of the JSON, so Grafana would display only the log message, not the whole JSON.

expected log in Grafana:
```
2023-02-06T14:22:16.686152666Z stdout F 14:22:16.685 [Timer-1] c.a.p.PostgresSpaceProvisioner - Checked 'test-dev-po 
stgres-database' Postgres space state
```
actual log in Grafana:
```
{"log":"2023-02-06T13:57:44.924366162Z stdout F \u001b[36m13:57:44.924\u001b[0;39m \u001b[1;30m[pool-3-thread-1]\u001b[0,39m \u001b[31mWARN \u001b[0;39m \u0 01b[35mo.apache.kafka.clients.NetworkClient\u001b[0;39m - [Consumer clientId=enrichment-service-kafka-schema-repository-notifications-consumer, groupId=enri chment-service_f2ff168b-4d7d-4042-b7e7-8be247082e61] Error while fetching metadata with correlation id 6377172 : {schema-repository-notification=UNKNOWN_TOP IC_OR_PARTITION}",
"kubernetes":{"pod_name":"enrichment-service-f6fcff8b6-bdj49","namespace_name":"instance-perf0"}
...
}
```
Except that I see UTF-8 color and formatting codes like e.g. `\u001b[36m`
It seems like it could be related to an opened [issue-5546](https://github.com/fluent/fluent-bit/issues/5546)

**Comment by david-nano** [comment]
@rafalwolny is there any news related? I saw `promtail` is parse the Kubernetes in the right way.
I still want to use Flunetbit but Loki can't parse it well.
