### ISSUE TITLE
Prometheus metrics on Windows container expose (wrong?) timestamp

### ISSUE THREAD

**Issue by Jeinhaus** [fluent/fluent-bit#6793]
## Bug Report

**Describe the bug**

Prometheus metrics on Windows container adds a timestamp value to each sample, that is not in the [required exposition format of "milliseconds since epoch"](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#comments-help-text-and-type-information).
Currently, on Feb 6, 2023 the metrics look like this:

```
# HELP fluentbit_output_retries_failed_total Number of abandoned batches because the maximum number of re-tries was reached.
# TYPE fluentbit_output_retries_failed_total counter
fluentbit_output_retries_failed_total{name="loki.0"} 0 658639125
```

Prometheus then rejects these with the following error:

```
scrape_pool=serviceMonitor/monitoring/fluent-bit/0 target=http://<rejected>:2020/api/v1/metrics/prometheus msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=21
Stream closed EOF for monitoring/prometheus-prometheus-stack-kube-prom-prometheus-0 (init-config-reloader)
```

**Expected behavior**

I expect a valid timestamp (or none) to be set on the metrics.

**Your Environment**

* Version used: `image: cr.fluentbit.io/fluent/fluent-bit:windows-2019-2.0.8`
* Environment name and version (e.g. Kubernetes? What version?): EKS (Kubernetes 1.24.9)
* Operating System and version: Windows Server 2019 (`10.0.17763.3887`)

Deployed via the fluent-bit Chart.

**Additional context**

To circumvent this, we will create a `ServiceMonitor` that sets `honorTimestamp: false`, which might mitigate this problem for now.

**Comment by nader-dabbabi** [comment]
Experiencing the same issue using the image `aws-for-fluent-bit:2.31.12-windowsservercore` on EKS (kubernetes version 1.31) with Daemonset deployed on Windows Server 2022 Core nodes.

The provided workaround in this issue solves the problem for now:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # ...
spec:
  endpoints:
  - honorTimestamps: false
    # ...
```
