### ISSUE TITLE
Feature Request: HTTP OUTPUT - Add configuration option to not group messages into JSON array

### ISSUE THREAD

**Issue by aa23** [fluent/fluent-bit#680]
**Is your feature request related to a problem? Please describe.**
Not a problem, more of a limitation.
I'm trying to use the **HTTP Output** plugin to POST log events formatted as JSON to an endpoint that can't handle a JSON array.

This works:
```
$ echo "{\"iamkey\":\"iamvalue\"},{\"who\":\"you\"}" | curl -X POST "http://example.com" -v --data-binary @-
...
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
...
```

This doesn't:
```
$ echo "[{\"iamkey\":\"iamvalue\"},{\"who\":\"you\"}]" | curl -X POST "http://example.com" -v --data-binary @-
...
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=UTF-8
< 
* Connection #0 to host example.com left intact
{"malformedLines":1,"oversizedLines":0,"successfulLines":0}
```

**Describe the solution you'd like**
Add a configuration option to not group log events into an array, and instead, every HTTP POST includes just one log event.

**Describe alternatives you've considered**
The logging SaaS does not have plans to accept a JSON array.

Obviously, grouping these into an array is more efficient, but I don't have control over the behavior of the SaaS.

**Comment by michiel** [comment]
@aa23 For the HTTP output, have you tried setting `format json_stream`? This outputs [Concatenated JSON](https://en.wikipedia.org/wiki/JSON_streaming#Concatenated_JSON), which does not have a comma (`,`) separator but might be a format your SaaS accepts.

See https://github.com/fluent/fluent-bit/pull/477

**Comment by aa23** [comment]
Thank you @michiel , using the Format `json_stream` resolved the issue for me.
I saw that in the docs and tried it before, but I must have had something else mis-configured at the time.

For those curious, this should be how the message body is structured with the `json_stream` option:
```
$ echo "{\"iamkey\":\"iamvalue\"},{\"who\":\"you\"},{\"k\":\"v\"},{\"what\":\"yeah\"}" | curl -X POST "http://example.com" -v --data-binary @-
...
< HTTP/1.1 200 OK
...
```
Closing issue - my fault.

**Comment by tuluce** [comment]
Note that using `json_stream` doesn't fully solve this problem in the case the service emits two logs within a short time period.

e.g., For two logs `{"key1": "value1"}` and `{"key2": "value2"}` with close timestamps, there will be a single HTTP request with the request body where JSONs are concatenated: `{"key1": "value1"}{"key2": "value2"}` rather than having two separate HTTP requests.

Being tracked here: https://github.com/fluent/fluent-bit/issues/2752
