### ISSUE TITLE
Addition of our company logo for using Fluentbit

### ISSUE THREAD

**Issue by vishal-android-freak** [fluent/fluent-bit#6801]
Thank you for some brilliant work with Fluentbit. It has helped us reduce a lot of components on the edge devices and made our lives easier. Not sure, if this is the way mentioned in the README to add our company logo to the list of companies using Fluentbit. The company name is R.U.D.R.A Cyber Security Pvt. Ltd. and we have built a security product for the maritime space.

Company website: [here](https://rudrasecure.com)

**Comment by patrick-stephens** [comment]
Please provide the actual logo image as well to use along with any relevant guidance on text, etc.
