### ISSUE TITLE
Incomplete SSL certificate validation

### ISSUE THREAD

**Issue by pludov** [fluent/fluent-bit#6804]
## Bug Report

**Describe the bug**

During ssl handshake - as a client - fluentbit doesn't correctly validate the peer's certificate.
It fails to check that the server's certificate covers the hostname

**To Reproduce**

- Setup fluentbit with an http output, tls & verify on
- Target a server with a certificate for a wrong domain (valid, but not for the targeted domain). 
- HTTP request will be sent to the server, regardless of its actual certificate.

Remark: to easily target a server with a wrong cert, you can target a google.com's IP using a random hostname, with the following entry added into /etc/hosts
```
108.177.15.106       www.random-hostname.com
```

**Expected behavior**

Server's certificate should be rejected if it doesn't cover the targeted hostname

**Your Environment**
* Tested with 1.9.9 & 2.0.8 using openssl library (linux amd64).

**Additional context**

This is a security concern about SSL reliability. This opens opportunity for an attacker to spoof the target server's identity (possibly MITM) and extract logs

**Comment by pludov** [comment]
This patch fixes it for openssl builds:

[fluentbit-openssl-sethost.patch](https://github.com/fluent/fluent-bit/files/10684909/fluentbit-openssl-sethost.patch)

**Comment by leonardo-albertovich** [comment]
Would you be able to create a pull request for this improvement?

**Comment by pludov** [comment]
Relative pull request: https://github.com/fluent/fluent-bit/pull/6805
