### ISSUE TITLE
Pods running out of memory before reach memory limit.

### ISSUE THREAD

**Issue by nicolastakashi** [fluent/fluent-bit#6806]
## Bug Report

**Describe the bug**

I'm getting pods running out of memory before the memory limit is reached, and I already enabled the memory limit and add a storage file system to backpressure and avoid this, but seems this is not working.

**To Reproduce**
- Tail input on kubernetes pod logs
- Kubernetes Filter
- HTTP Output

**Expected behavior**

Run pods without getting OOMKill

**Screenshots**

Memory Consumption.
![image](https://user-images.githubusercontent.com/8205546/217560857-e33b73c7-24ad-4a5c-8323-47bb172e29b7.png)

Input Storage over the limit

![image](https://user-images.githubusercontent.com/8205546/217561110-50eb2f9f-1f48-4a3b-a385-3fd8b3014478.png)

**Your Environment**

* Version used: 2.0.8
* Configuration:
```
[SERVICE]
        Daemon Off
        Flush 1
        Log_Level warn
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /var/log/fluent-bit/buffer
        storage.sync full
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Refresh_Interval 5
        Skip_Long_Lines On
        Mem_Buf_Limit 5MB
        storage.type filesystem
        DB /var/log/fluentbit-tail.db
    [OUTPUT]
        Name                  http
        Match                 *
        Host                  ${ENDPOINT}
        Port                  443
        URI                   /logs/rest/singles
        Format                json_lines
        TLS                   On
        Header                private_key ${PRIVATE_KEY}
        compress              gzip
        Retry_Limit           False
        net.keepalive         off
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.23
* Server type and version:
* Operating System and version: 
* Filters and plugins: Kubernetes, AWS

**Additional context**

**Comment by patrick-stephens** [comment]
It looks like there might be some conflicting config: https://docs.fluentbit.io/manual/administration/buffering-and-storage

> Please note that Mem_Buf_Limit only applies when storage.type is set to the default value of memory.

I think you might need to tune the chunks up value? I'm not an expert though.

**Comment by nicolastakashi** [comment]
Hi @patrick-stephens thanks for your reply.

I tried other configs like this one.

```
[SERVICE]
        Daemon Off
        Flush 1
        Log_Level warn
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /var/log/fluent-bit/buffer
        storage.sync full
        storage.checksum On
        pause_on_chunks_overlimit On
        storage.backlog.mem_limit 5M
        storage.max_chunks_up 20

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Refresh_Interval 5
        Skip_Long_Lines On
        threaded on
        storage.type filesystem
        DB /var/log/fluentbit-tail.db

    [OUTPUT]
        Name                  http
        Match                 *
        Host                  ${ENDPOINT}
        Port                  443
        URI                   /logs/rest/singles
        Format              json_lines
        TLS                   On
        Header              private_key ${PRIVATE_KEY}
        compress              gzip
        Retry_Limit           False
        net.keepalive         off
        storage.total_limit_size 5M
```

But I'm still getting OMKills, one thing I noticed is that this OMKills is happening when the number of opened files increases, as you can see in the image below.

At 16:10 when it reached 25 opened files I got an OMKill

![image](https://user-images.githubusercontent.com/8205546/218144579-ff2010ad-d895-4084-bcc1-1d9e0ebdb703.png)

Those are the pod logs during the OMKill time range.

```

log:[2023/02/10 16:09:21] [error] [storage] format check failed: tail.0/1-1676031205.903043787.flb
log:[2023/02/10 16:09:21] [error] [storage] format check failed: tail.0/1-1676031210.904073769.flb
log:[2023/02/10 16:09:21] [error] [storage] format check failed: tail.0/1-1676031206.647750968.flb
log:[2023/02/10 16:14:19] [error] [input chunk] no available chunk
log:[2023/02/10 16:14:19] [error] [input chunk] chunk 1-1676045659.647759406.flb would exceed total limit size in plugin http.0
```

**Comment by nicolastakashi** [comment]
Hi, @patrick-stephens sorry to bother you.
Do you think that this could be another internal error that exited container with code 137?

**Comment by patrick-stephens** [comment]
> Do you think that this could be another internal error that exited container with code 137?

It could be but I think generally 137 is "not enough memory". I'm not an expert though and it depends on your specific infra set up so worth checking with the docs.

**Comment by nicolastakashi** [comment]
@patrick-stephens tbh I already went across the docs, not clear about doing a capacity plan for a fluent bit.

And as you can see in the images, I don't have overcommit inputs and the only recommendation that I have on the docs is with the relation between chunks up in memory vs the avg size of chunks.

BUt I decreased the amount of chunks up in memory to 10
