### ISSUE TITLE
Enhance OpenSearch plugin to allow raw ctrace (JSON format)

### ISSUE THREAD

**Issue by agup006** [fluent/fluent-bit#6807]
**Is your feature request related to a problem? Please describe.**

Currently OpenSearch output plugin can only receive logs, we should allow sending ctrace in JSON format similar to S3 format

**Describe the solution you'd like**
If reading traces via OpenTelemetry plugin we should allow users to send that to OpenSearch

@Syn3rman

**Comment by YANG-DB** [comment]
this is great - please take a look at the next PR draft for traces https://github.com/opensearch-project/observability/pull/1403
