### ISSUE TITLE
website slack invite times out

### ISSUE THREAD

**Issue by gattytto** [fluent/fluent-bit#6809]
hello, sorry for spamming here, actually my issue is about cri-o, nginx ingress-controller and kubernetes but I can't get into the slack server, please help. https://launchpass.com/fluent-all gives a time out

**Comment by gattytto** [comment]
this is the related issue: https://github.com/fluent/fluentd-website/issues/251

**Comment by patrick-stephens** [comment]
Seems to work fine for me...
Possibly a transient error.
