### ISSUE TITLE
config file option -c does not work with Fluentbit windows installation

### ISSUE THREAD

**Issue by Tamil-RK** [fluent/fluent-bit#6812]
## Bug Report

**Describe the bug**
 I downloaded the fluent bit zip file and tested the '-i dummy -o stdout' it works, but I updated the fluent bit config file and while running the config command it gives an error:
 [error] could not open configuration file, aborting.

**To Reproduce**
- Download the fluent-bit-2.0.9-win64.zip in windows and extract the zip file
- open the cmd and select the fluent bit bin file path
- Run the command 'fluent-bit -c <config file path>'
```
[error] could not open configuration file, aborting.
```

**Expected behavior**
I configured the log file path in fluent-bit.conf file, it needs to read log data from the input path.

**Screenshots**
![image](https://user-images.githubusercontent.com/124819107/217645143-f78cf0e6-40a4-4c10-a336-3f257c1f5311.png)
![image](https://user-images.githubusercontent.com/124819107/217645629-bf41fab9-b7db-4d90-9311-1087e40ef040.png)

**Your Environment**

* Version used:2.09
* Operating System and version: windows 10

**Comment by patrick-stephens** [comment]
Did you actually provide the path to the file after the option?

**Comment by Tamil-RK** [comment]
yes, I provided the config file path. Please check the screenshot.

**Comment by Norfolc** [comment]
You need to enclose the path in quotes since it contains spaces: 
`fluent-bit -c "d:\path with spaces\config.conf"`

**Comment by Tamil-RK** [comment]
Yes. it works.

Thank you so much!!
