### ISSUE TITLE
[warning] failed to flush chunk 

### ISSUE THREAD

**Issue by BlaBlaGITTE** [fluent/fluent-bit#6815]
Describe the bug
[warning] failed to flush chunk 

To reproduce
error in /var/log/fluent-bit/fluent-bit.log file:
[2023/02/09 13:56:09] [ warn] [engine] failed to flush chunk '25309-1675947361.378959602.flb', retry in 19 seconds: task_id=12, input=tail.2 > output=http.0 (out_id=0)

- Steps to reproduce the problem:

[INPUT]
    name tail
    path /opt/ad.log
    tag  ad
    Refresh_Interval 30
    Skip_Long_Lines  On
    Skip_Empty_Lines On

Output section:

[OUTPUT]
    Name http
    Match *
    Host myhost.xxx
    Port 8443
    Format json
    HTTP_User myuser
    HTTP_Passwd mypass
    tls.ca_file file.pem
    tls On
    tls.verify Off
    json_date_key @timestamp
    json_date_format iso8601
    net.keepalive On
    Retry_Limit 5
    log_response_payload false

**My Environment**
* Version fluent-bit client used:
**fluent-bit-2.0.8-1.x86_64
* Environment name:
nginx
* Server type and version:
Linux red-hat 7.x

**Comment by patrick-stephens** [comment]
That is a pretty generic warning saying it cannot send to that output at that particular time. It could be various things outside of Fluent Bit, e.g. networking failures, the output itself failing or not accepting the data, etc.

Fluent Bit will also retry flushing until it can do it may recover from a transient failure of the output is unavailable for whatever reason, hence the generic warning.

What have you done to debug the failure? Was the output working then stopped or never worked? Did you confirm the output was available from wherever Fluent Bit is running?

**Comment by BlaBlaGITTE** [comment]
Hi Patrick, yes indeed we've some issure about DNS resolution:
[ warn] [net] getaddrinfo(host='myhost', err=12): Timeout while contacting DNS servers
