### ISSUE TITLE
compilerd binary or packages

### ISSUE THREAD

**Issue by mhf-ir** [fluent/fluent-bit#683]
binary files for just download and use.
At least packages for popular linux dist like ubuntu

**Comment by edsiper** [comment]
Packages are available, please refer to the official documentation:

https://fluentbit.io/documentation/0.13

I will make sure to link those in the web site as well.

**Comment by kSandr-ki** [comment]
+1 why you don't release a binnaries ?

**Comment by edsiper** [comment]
@kSandr-ki 

- https://docs.fluentbit.io/manual/installation
- debian: https://docs.fluentbit.io/manual/installation/debian
- ubuntu: https://docs.fluentbit.io/manual/installation/ubuntu
- centos: https://docs.fluentbit.io/manual/installation/redhat_centos
- raspbian: https://docs.fluentbit.io/manual/installation/raspberry_pi
- windows: https://docs.fluentbit.io/manual/installation/windows

**Comment by kSandr-ki** [comment]
@edsiper 
I mean just put binaries for downloads without repos  ...  you're have a download page but , there only sources , on github release page also no binaries .
Why you make download page if there only sources ? if somebody wanted sources he will go to github.

I really like your product, but it is some strange and not very convenient.

**Comment by defo89** [comment]
@edsiper would it be possible to revisit this issue? It would be super convenient just to be able to download latest stable binary and run it. I like how tailscale does it https://pkgs.tailscale.com/stable/#static
