### ISSUE TITLE
Fluent-bit forward protocol does NOT support EventTime of fluentd

### ISSUE THREAD

**Issue by Gabriel1688** [fluent/fluent-bit#684]
## Bug Report

**Describe the bug**

The format of time does NOT include the nanosecond part although I have put the nanosecond timestamp in the fluentbit forward message

2018-07-16T20:34:02-04:00   xxx.com HttpClient "DEBUG "  "HttpClient::startTimer() event_type: 0, timer_id: 29201, 1ms"

in the demo program
  56     for (i = 0; i < 10000; i++) {
  57         n = snprintf(tmp, sizeof(tmp) - 1,
  58                      "[%f, {\"key\": \"val %i\"}]",
  59                      **flb_time_now(),** i);
  60         printf("%s\n", tmp);
  61         **flb_lib_push(ctx, in_ffd, tmp, n);**
  62     }

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
 2018-07-16 20:34:05 -0400 [trace]: #0 [input_forward] connected fluent socket addr="192.168.0.16" port=42742
 2018-07-16 20:34:05 -0400 [trace]: #0 [input_forward] accepted fluent socket addr="192.168.0.16" port=42742
 **2018-07-16 20:34:05 -0400 [warn]: #0 emit transaction failed: error_class=ArgumentError error="time must be a Fluent::EventTime (or Integer): Float" location="/opt/td-**agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.2.2/lib/fluent/plugin/output.rb:791:in `metadata'" tag="xxx"
 2018-07-16 20:34:05 -0400 [warn]: #0 suppressed same stacktrace
 **2018-07-16 20:34:05 -0400 [error]: #0 [input_forward] unexpected error on reading data host="192.168.0.16" port=42742 error_class=ArgumentError error="time must be a Fluent::EventTime (or Integer): Float"**
 2018-07-16 20:34:05 -0400 [error]: #0 suppressed same stacktrace
```
- Steps to reproduce the problem:

**Expected behavior**

 the Normal format of time should like as following:
**2018-07-16T20:34:02.778120**-04:00   xxx.com HttpClient "DEBUG "  "HttpClient::startTimer() event_type: 0, timer_id: 29201, 1ms"

**Screenshots**

**Your Environment**

* Version used:
    td-agent-bit-0.13.3-1.x86_64   ( Fluent Bit v0.13.3  )
    td-agent-3.2.0-0.el7.x86_64

* Configuration:
   <source>
     @type forward
     bind 0.0.0.0
     port 24224
     @id input_forward
     tag foo
   </source>
  
   <match foo>
     @type file
     @id output_file
     path /var/log/td-agent/access
      format csv
      fields time, Host,Module,LogLevel,Context,Message
      force_quotes false
      delimiter " "
      time_key time
      time_key_format %Y-%m-%dT%H:%M:%S.%N%z
      include_time_key true
  </match>

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
  Cent OS 7
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.13.1.el7.x86_64
      Architecture: x86-64

* Filters and plugins:
   application side:  integrate two plugins:
       fluentbit - lib 
       fluentbit forward protocol
  Fluentd side
       <input>in-forward 
       <output> file

**Additional context**

**Comment by nokute78** [comment]
This is a specification of library mode.

`flb_lib_push` supports UNIX_TIMESTAMP (= integer) only.
https://fluentbit.io/documentation/0.14/development/ingest_records_manually.html

**Comment by edsiper** [comment]
as @nokute78  said, lib mode only support seconds resolution. Not an out forward issue.
