### ISSUE TITLE
Splunk event metadata "source" is not set with expected value

### ISSUE THREAD

**Issue by duj4** [fluent/fluent-bit#6840]
## Bug Report

**Describe the bug**
"source" in Splunk event metadata is not set as the log path.

**To Reproduce**
Using Splunk output plugin and set event_source as "$path".

**Expected behavior**
I hope the field source could be updated with the log path though I could set event_source manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/19278537/218453107-68c195f6-e82f-417c-bf97-cd95e2b2337d.png)

**Your Environment**
* Version used: 2.0.8
* Configuration:
```
[INPUT]
    Name              tail
    Tag               jsm_on_centos8-2
    Path              /home/dujas/fluent-bit/conf/inputs/atlassian-jira-snip3.log
    DB                /home/dujas/fluent-bit/db/test.db
    Read_from_Head    True
    Buffer_Chunk_Size 20480KB
    Buffer_Max_Size   20480KB
    multiline.parser  jsm

[MULTILINE_PARSER]
    name          jsm
    type          regex
    flush_timeout 1000
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule      "start_state"   "/(\d{4}\-\d{2}-\d{2} \d{2}\:\d{2}\:\d{2}\,\d+[\+\-]\d+)(.*)/"  "cont"
    rule      "cont"          "/^[\s+at|java|Caused]/"            "cont"

[PARSER]
    Name jsm
    Format regex
    Regex /^(?<time>\d{4}\-\d{2}-\d{2} \d{2}\:\d{2}\:\d{2}\,\d+[\+\-]\d+) (?<message>.*)/m
    Time_Key time
    Time_Format %Y-%m-%d %H:%M:%S,%L%z
    Time_Keep   On

[OUTPUT]
    Name             Splunk
    Match            *
    Host             centos8-1
    Port             8043
    tls              on
    tls.verify       on
    tls.ca_file      /home/dujas/certs/ca.pem
    tls.crt_file     /home/dujas/certs/centos8-2_all.pem
    tls.key_file     /home/dujas/certs/centos8-2.key
    tls.key_passwd   <key password>
    Splunk_Token     <splunk token>
    Splunk_Send_Raw  off
    event_host       ${HOSTNAME}
    event_source     $path
    event_key        $time $message
```
* Environment name and version (e.g. Kubernetes? What version?): virtual machine
* Server type and version: virtual machine
* Operating System and version: centos8
* Filters and plugins: tail input and splunk output

**Additional context**
Please correct me if there is anything missed.

**Comment by RicardoAAD** [comment]
Hello @duj4 

You should add the configuration parameter "Path_key" to the input section of your tail plugin; when enabling this option, the monitored file name and its path will be stored as part of the record, and then you can retrieve its value to use it as input for the option "event_source" in the Splunk output section. 

This is an example based on your config:

```
  fluent-bit.conf: |
    [INPUT]
        name tail
        Tag jsm_on_centos8-2
        Path /var/log/containers/*.log
        Read_from_Head True
        Path_Key MySource # <=== key to store the path and name of the monitored file
        Exclude_Path /var/log/containers/*fluent-bit*.log
    [OUTPUT]
        name Splunk
        Match *
        Host splunk-master
        Port 8088
        Splunk_Token my-secret-token
        tls on
        tls.verify off
        Splunk_Send_Raw off
        event_host myhost
        event_source $MySource.   # <=== key used to send the source to Splunk.
        event_key $log
        event_index_key my-index
```

stdout plugin log example
```
[0] jsm_on_centos8-2: [1676316615.323574930, {"MySource"=>"/var/log/containers/loki-grafana-5bd8dd4879-49tls_loki_grafana-06b61e3f1333936db22803b766bac1d1bd0ff3efb7b7d65fab79f5093a1a5e3b.log", "log"=>"{"log":"t=2023-02-13T19:30:15+0000 lvl=warn msg=\"[Deprecated] the datasource provisioning config is outdated. please upgrade\" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/loki.yaml\n","stream":"stdout","time":"2023-02-13T19:30:15.322397632Z"}"}]
```

This is what the source looks like in Splunk:

![image](https://user-images.githubusercontent.com/112411485/218562129-479813bf-52a8-471f-89a3-d793c50f24be.png)


Please let us know if this suggestion helped to get the source from the tail plugin to your Splunk output.

Regards,
Ricardo.

**Comment by duj4** [comment]
Hi @RicardoAAD,

Thank you very much and apologies for my tardy reply.

I followed your guidance and added "Key_Path", here are the full config:
fluent-bit.conf:
```
[SERVICE]
    flush        5
    daemon       Off
    log_file     /home/dujas/fluent-bit/log/fluent-bit.log
    log_level    debug
    parsers_file /home/dujas/fluent-bit/conf/parsers/parsers.conf
    parsers_file /home/dujas/fluent-bit/conf/parsers/parsers_multiline.conf

@INCLUDE inputs/jsm.conf

@INCLUDE filter/jsm.conf

@INCLUDE outputs/splunk_test7.conf
```

```
[INPUT]
    Name              tail
    Tag               jsm_on_centos8-2
    Path              /home/dujas/fluent-bit/conf/inputs/atlassian-jira-snip2.log
    Path_Key          logpath
    DB                /home/dujas/fluent-bit/db/test.db
    Read_from_Head    True
    Buffer_Chunk_Size 20480KB
    Buffer_Max_Size   20480KB
    multiline.parser  jsm

[OUTPUT]
    Name             Splunk
    Match            *
    Host             centos8-1
    Port             8043
    tls              on
    tls.verify       on
    tls.ca_file      /home/dujas/certs/ca.pem
    tls.crt_file     /home/dujas/certs/centos8-2_all.pem
    tls.key_file     /home/dujas/certs/centos8-2.key
    tls.key_passwd   <password>
    Splunk_Token     <token>
    Splunk_Send_Raw  off
    event_host       ${HOSTNAME}
    event_source     $logpath
    event_key        $time $message
```
parsers/parsers_multiline.conf, by this could handle the multiline logs from the application:
```
[MULTILINE_PARSER]
    name          jsm
    type          regex
    flush_timeout 1000
    # rules |   state name  | regex pattern                  | next state
    # ------|---------------|--------------------------------------------
    rule      "start_state"   "/(\d{4}\-\d{2}-\d{2} \d{2}\:\d{2}\:\d{2}\,\d+[\+\-]\d+)(.*)/"  "cont"
    rule      "cont"          "/^[\s+at|java|Caused]/"            "cont"
```
filter/jsm.conf, invoking the parser below:
```
[FILTER]
    name             parser
    match            *
    key_name         log
    parser           jsm
```
parsers/parsers.conf, by which it splits the log line into "time" and "message", afterwards combine them in outputs so that "time" will replace the search time in splunk and the log will handled as expected:
```
[PARSER]
    Name jsm
    Format regex
    Regex /^(?<time>\d{4}\-\d{2}-\d{2} \d{2}\:\d{2}\:\d{2}\,\d+[\+\-]\d+) (?<message>.*)/m
    Time_Key time
    Time_Format %Y-%m-%d %H:%M:%S,%L%z
    Time_Keep   On
```
The screenshot from splunk is as below:
![image](https://user-images.githubusercontent.com/19278537/219051971-363fbcd7-cfd9-4ad3-a741-c0b59b0d11f5.png)

I am afraid this is owning to the filter and parser but I failed to figure out which part is incorrect, could you please help check it further?

Appreciate.

**Comment by duj4** [comment]
Once I commented out the filter, the source part came out as expected:
![image](https://user-images.githubusercontent.com/19278537/219059815-5f21b3bc-e76f-457a-a40f-6ea6af82ec36.png)

However, the time part is my concern. Since I am searching the old log files, I hope the _time could match the log's.

**Comment by duj4** [comment]
Hi @RicardoAAD,
I think I have found the solution, which is adding "reserve_data" in my PARSER filter:
```
[FILTER]
    name             parser
    match            *
    key_name         log
    parser           jsm
    reserve_data     on
```
According to fluent-bit's doc:
"By default, the parser plugin only keeps the parsed fields in its output", which means all other fields will be discarded, in my case the "all other fields" include "logpath".

Now the output of Splunk looks good:
![image](https://user-images.githubusercontent.com/19278537/219850374-e3485074-a068-489a-a151-55990c93f831.png)

Thanks again for your help.
