### ISSUE TITLE
filterting logs and sending the logs to 2 stream.

### ISSUE THREAD

**Issue by devanshawasthi** [fluent/fluent-bit#6848]
## Bug Report

**Describe the bug**
Working on a system where in I need to filter data (logs) into 2 parts and send one part to kinesis data stream and another to kinesis delivery stream. I have tried out grep tag but in that I am not able to filter the data into 2. I am aware that it will be solved using re-write tag but not getting the correct result.

[INPUT]
Name forward
unix_path /var/run/fluent.sock
Mem_Buf_Limit 100MB
Tag test_tag
[INPUT]
Name forward
unix_path /var/run/fluent.sock
Mem_Buf_Limit 100MB
Tag test_tag_dev

[FILTER]
Name grep
Match test_tag_dev
Regex log INFO:root:

[OUTPUT]
Name kinesis_firehose
Match *
Region us-west-2
delivery_stream devansh_stream

[OUTPUT]
Name kinesis_firehose
Match *
Region us-west-2
delivery_stream dev_stream 

**Expected behavior**
 to filter out telemetry logs from application logs and send the filter logs into kinesis stream but working as expected.

**Comment by patrick-stephens** [comment]
What's the issue? There is just a config. Please follow the template to also capture other relevant details like version, os, etc

**Comment by RicardoAAD** [comment]
Hello @devanshawasthi 

I can see you have two forward inputs plugins with different tags; you also have one filter to grep for "INFO:root:" when the logs have the tag "test_tag_dev", then you are sending everything (the filtered messages from the second Input and also the messages from the first input) to both outputs.

If you want to send filtered messages to any of the outputs, you have to change the Match option in your ouputs, to match the tag of your input.

In this config, the first input is going to the output with delivery_stream devansh_stream, and the second input is going to be filtered and then sent to the second output with delivery_stream dev_stream
```
[INPUT]
Name forward
unix_path /var/run/fluent.sock
Mem_Buf_Limit 100MB
Tag test_tag

[INPUT]
Name forward
unix_path /var/run/fluent.sock
Mem_Buf_Limit 100MB
Tag test_tag_dev

[FILTER]
Name grep
Match test_tag_dev
Regex log INFO:root:

[OUTPUT]
Name kinesis_firehose
Match test_tag
Region us-west-2
delivery_stream devansh_stream

[OUTPUT]
Name kinesis_firehose
Match test_tag_dev 
Region us-west-2
delivery_stream dev_stream
```
Please let us know if this helps with your use case.

Regards,
Ricardo.
