### ISSUE TITLE
Parser Decoders does NOT work in the filter parser properly. 

### ISSUE THREAD

**Issue by Gabriel1688** [fluent/fluent-bit#685]
## Bug Report
Parser decoders with keyword: **Decode_Field_as escaped xx do_next** is very useful when removing escaped string from a given field, but it does NOT used by fluentd in the filter parser.

Introduction about the parser decod.
https://fluentbit.io/documentation/current/parser/decoder.html

**Describe the bug**

Output from the td-agent log regarding of the filter parser initialization.
2018-07-18 15:57:36 -0400 **[warn]: parameter 'Decode_Field_as' in <filter xxx>**
   @type parser
   format json
   key_name "Message"
   reserve_data true
   Decode_Field_as escaped Message do_next
   <parse>
      @type json
    </parse>
  </filter> **is not used.**

202 2018-07-18 15:57:50 -0400 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not match with data                                '{\"Content\"=>\"xxxxChannelClient::onResponse() location : \\\\\\\"\\\\/services\\\\/server\\\\/config\\\\\\\"\"}'" location=nil tag="media"                    time=1531943867 record={"Timestamp"=>"2018-07-18 15:57:47.156182", "Host"=>"xxxx.com", "Module"=>"Server", "LogLevel"=>"DEBUG ", "context"=>"Context = ",        "Message"=>{"Content"=>"xxxCtrlChannelClient::onResponse() location : \\\"\\/services\\/server\\/config\\\""}}

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
2018-07-18T15:57:47-04:00   media  {"Timestamp":"2018-07-18 15:57:47.156245","Host":"xxx.com","Module":"Server","LogLevel":"INFO  ","context":"Context = ","Message":{"Content":"location: \\\"\\/services\\/server\\\""}}
```
- Steps to reproduce the problem:

**Expected behavior**

the final output after filter parser should look like following, without escaped string anymore.
2018-07-18T15:57:47-04:00   media  {"Timestamp":"2018-07-18 15:57:47.156245","Host":"xxx.com","Module":"Server","LogLevel":"INFO  ","context":"Context = ","Content":**"location: "/services/server"**}}
**Screenshots**

**Your Environment**

* Version used:
   td-agent-bit-0.13.3-1.x86_64 ( Fluent Bit v0.13.3 )
   td-agent-3.2.0-0.el7.x86_64
* Configuration:

   < source >  // source

        @type forward

        bind 0.0.0.0

        port 24224

        @id input_forward

        tag media

   < /source >  // end of source

  

   < filter media > // filter media

        @type parser

        format json

        key_name Content

        reserve_data true

        Decode_Field_As escaped Content do_next

   <  /filter >  // end of filter media

   < match media >  // match media

        @type file

        @id output_file

        path /var/log/td-agent/access

   < /match >  // end of match media 

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
   Cent OS 7
   Operating System: CentOS Linux 7 (Core)
   CPE OS Name: cpe:/o:centos:centos:7
   Kernel: Linux 3.10.0-327.13.1.el7.x86_64
   Architecture: x86-64
* Filters and plugins:
   application side: integrate two plugins:
       fluentbit - lib
       fluentbit forward protocol
   Fluentd side
      in-forward
      filter parser
      file
**Additional context**

**Comment by edsiper** [comment]
Parser decoders are a specific Fluent Bit feature. Please log an issue in Fluentd github repo for further assistance.
