### ISSUE TITLE
File starting with single quote (') not recognized

### ISSUE THREAD

**Issue by mdicerbo** [fluent/fluent-bit#6856]
## Bug Report

**Describe the bug**
I'm trying to ingest data with tail plugin with file starting with single quote ' file is not recognized
and not ingested.
example file 

'[cloud][d2ccloudopstest][sql server][datasource-ale].2023-02-13.log'

I've already tried to escape quotes but without success
Are there any kind of regex to enable file with quotes?

**Comment by RicardoAAD** [comment]
Hello @mdicerbo 

If you file name is '[cloud][d2ccloudopstest][sql server][datasource-ale].2023-02-13.log' you should scape each of the single quotes and also each of the square brackets in the file name, so your config should look like this:

```
[INPUT]
    Name            tail
    Path            \'\[cloud\]\[d2ccloudopstest\]\[sql\ server\]\[datasource-ale\].2023-02-13.log\'
 ```

Please give it a try and let us know if this helped.

Regards,

**Comment by mdicerbo** [comment]
Hi @RicardoAAD thank you for your fast reply, i've tried escaping quotes and square brackets but it doesn't work

**Comment by patrick-stephens** [comment]
What platform are you on? OS, container, etc.?
