### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by mrkmcnamee** [fluent/fluent-bit#6860]
On the reference page for Syslog it says that the transport type (mode) can be set to `tls`:
https://docs.fluentbit.io/manual/pipeline/outputs/syslog
However on the security page Syslog is not listed as one of the output plugins that supports TLS.
https://docs.fluentbit.io/manual/administration/security
I'm guessing the list needs to be updated.

**Comment by patrick-stephens** [comment]
Thanks @mrkmcnamee , can you raise a PR on the docs repo? fluent/fluent-bit-docs

**Comment by mrkmcnamee** [comment]
Done
