### ISSUE TITLE
in_node_exporter_metrics: add textfile collector support

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#6878]
The following ticket is to track the implementation of a textfile collector, references:

- Prometheus node exporter:
  - description: https://github.com/prometheus/node_exporter#textfile-collector
  - Go implementation: https://github.com/prometheus/node_exporter/blob/master/collector/textfile.go

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluent-bit/pull/7030
