### ISSUE TITLE
Duplicate logs are forwarded to logstash

### ISSUE THREAD

**Issue by natalia-k** [fluent/fluent-bit#6886]
## Bug Report

**Describe the bug**
Using fluent-bit v2.0.9 (running on EKS) with the following config to send the exists large json file to logstash.
Sometimes, the duplicate data sent.
For example, file with 2,781,074 lines there were sent 2,899,185, so 118111 duplicate lines were sent.

Any idea why this happen? what should I change in config to prevent this?
fluent-bit started after file already created and no change.

* Version used: v2.0.9
* Configuration:

```
[SERVICE]
    flush        1
    daemon       Off
    log_level    debug 

[INPUT]
    Name         tail
    Buffer_Chunk_Size 128KB
    Buffer_Max_Size 128KB
    Path         /opt/output.log
    DB           /tmp/output.log.db
    Tag          message
    exit_on_eof true
    read_from_head true

[OUTPUT]
    Name          tcp
    Match         *
    Host          logstash.svc.cluster.local
    Port          8080
    Format        json
```
    
* Environment name and version : EKS v1.22

**Comment by lecaros** [comment]
Hi,
How are you measuring those lines?
Is that the full config?
Is it from a single run? (you have `read_from_head true`)
Can you reproduce it at will?
Can you share the input log file?

**Comment by natalia-k** [comment]
with the following config  the issue was resolved

`[INPUT]
    Name         tail
    Buffer_Chunk_Size 1M
    Buffer_Max_Size 8M
    Path         output.log
    DB           /tmp/output.log.db
    Tag          message
    exit_on_eof true
    read_from_head true`
