### ISSUE TITLE
[error] [engine] chunk '1-1676890282.464880152.flb' cannot be retried: task_id=1, input=tail.0 > output=es.0

### ISSUE THREAD

**Issue by yasinmoha** [fluent/fluent-bit#6888]

**Comment by yasinmoha** [comment]
I have dual logging implemented where fluentbit is running on AKS collecting kubernetes logs and shipping them to Azure log analytics. 

Fluentbit version --> version=2.0.9
AKS version --> 1.24.9

Logs are shipped to azure log analytics no issues but logs to ES get dropped.  It retries 5 times and it gets dropped sometime it they get flushed within 3-4 retries. 

[engine] failed to flush chunk '1-1676890762.463914719.flb', retry in 23 seconds: task_id=3, input=tail.0 > output=es.0 (out_id=0)
[error] [engine] chunk '1-1676890762.463914719.flb' cannot be retried: task_id=3, input=tail.0 > output=es.0


` ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.*
        multiline.parser docker, cri
        Tag kube.*
        Skip_Long_Lines On
        storage.type filesystem
        Buffer_Chunk_Size 5M
        Buffer_Max_Size 7M
        Mem_Buf_Limit 10M

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
 

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 7M

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host exhort
        Port 9200
        Index kube  
        Buffer_Size 32M
        Retry_Limit 5

    [OUTPUT]
        Name            azure
        Match           kube.*
        Customer_ID     ${WorkspaceId}
        Shared_Key      ${SharedKey}
        log_type        kube`

**Comment by lecaros** [comment]
Hi,
What's your expected behavior?
We have a template to log issues; please provide the requested information per the template.

**Comment by yasinmoha** [comment]
Closing the issue as its fixed on enabling trace with elastic output plugin it turned out to be kubernetes annotation label field issue. enabled the replace_dots function in ES output and its working
