### ISSUE TITLE
Should we need to keep parsers_multiline.conf as separate file ( can we use parsers_multiline.conf in side fluent-bit.conf ? )

### ISSUE THREAD

**Issue by potlapudirajeev** [fluent/fluent-bit#6891]
## Bug Report
https://github.com/fluent/fluent-bit/blob/master/documentation/examples/multiline/regex-001/fluent-bit.conf

1) Should we need to keep parsers_multiline.conf as separate file ( can we use parsers_multiline.conf in side fluent-bit.conf ? )

2) can you please share sample  app-deployment file ( how to provide path for parsers_multiline.conf  in volumeMounts )

**Comment by patrick-stephens** [comment]
1. The parsers file is a separate configuration file, you cannot embed it directly into the general configuration. You can however define multiple parsers in the same file.
2. Have a look at the helm chart, it's all just a standard mount though - just mount the file and then reference the location (you can use absolute or relative paths but I would start with absolute).

https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit

If you want to just run locally then you can use docker-compose or directly with the local path, e.g. https://github.com/fluent/fluent-bit/blob/master/examples/perf_test/docker-compose.yml
