### ISSUE TITLE
syslog output does excessive dns lookups

### ISSUE THREAD

**Issue by johnl** [fluent/fluent-bit#6900]
## Bug Report

**Describe the bug**

in tcp mode, if you use a fqdn as the host, the syslog output seems to do a dns lookup for every single log line that it sends.

Not tested with udp mode.

**To Reproduce**

```
    [OUTPUT]
        name   syslog
        match   *
        host   syslog.example.com
        port   514
        mode   tcp
```
**Your Environment**
* Version used: 2.0.9
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.22
* Operating System and version: Ubuntu Focal

**Additional context**

This would also suggest that persistent connections to the syslog servers aren't being used - that alone would reduce the dns lookups and otherwise improve performance too.

**Comment by artheus** [comment]
This is very true for the HTTP Output as well. It seems to make one DNS lookup for every outgoing message. So any type of DNS caching mechanism would be a great improvement. Since our internal DNS is now facing around 30K unnecessary lookups per every 5 minutes. Which the DNS server is not very happy about, fluent-bit is basically DDoS'ing our DNS server...

**Comment by bmarinov** [comment]
> That's definitely part of the roadmap. In the meantime you might be able to overcome this by setting the `dns.resolver` to `LEGACY` in the service section or `net.dns.resolver` to `LEGACY` in specific output plugin sections if needed.
> 
> Although there is no ETA yet this issue will remain open until the improvement is merged.
> 
> Note: Setting the dns resolver to legacy mode will cause DNS lookups to be performed in synchronous mode which is not desirable when output plugins are set to run in the main pipeline thread (ie. `workers 0`) so if you do set the option be sure to check that your output plugins have a `workers` value of `1` or more.

This issue seems to also impact the Loki output, probably as it is also runs on HTTP. Does the loki output also support the workers setting? I didn't find any references in the output implementation, and I would really like to try this workaround.

**Comment by bmarinov** [comment]
@leonardo-albertovich can you reopen the issue and maybe set a `exempt-stale ` label? Thanks :)
