### ISSUE TITLE
Stackdriver Output Plugin Sets Unstable resource_labels leading to misidentified logs.

### ISSUE THREAD

**Issue by sharkymcdongles** [fluent/fluent-bit#6901]
## Bug Report

**Describe the bug**
Using tail input with cri regex parser, and kubernetes filter to stackdriver output plugin causes logs to have wrong resource_ids despite having proper kubernetes labels. Even explicitly setting them in config with resource_labels fails.

**To Reproduce**
my config:

service:
```
[SERVICE]
            Flush         5
            Grace         120
            Log_Level     info
            Daemon        off
            Parsers_File  custom_parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_PORT     2020
```
inputs:
```
        [INPUT]
            Name             tail
            Alias            kube_containers
            Tag              kube.<namespace_name>.<pod_name>.<container_name>
            Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
            Path             /var/log/containers/*.log
            Exclude_Path     *_kube-system_*,*_logging_*,*_monitoring_*,*_harbor_*,*_flux-system_*
            DB               /var/run/google-fluentbit/pos-files/fluentbit.db
            Buffer_Max_Size  8MB
            Inotify_Watcher  false
            Mem_Buf_Limit    100MB
            Skip_Empty_Lines On
            Skip_Long_Lines  On
            Refresh_Interval 5
            Read_from_Head   True
            Parser           cri
```
filters:
```
       [FILTER]
            Name            grep
            Match_Regex     kube\.flux-system\.(kustomize-controller|helm-controller).*
            Exclude         $severity info

        [FILTER]
            Name                kubernetes
            Match               kube.*
            Buffer_Size         0
            Keep_Log            Off
            K8S-Logging.Exclude On
            K8S-Logging.Parser  On
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Tag_Prefix     kube.
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_URL            https://kubernetes.default.svc:443
            Merge_Log           On
            Regex_Parser        pod-tag-parser
            Use_Kubelet         Off
```
outputs:
```
        [OUTPUT]
            Name                       stackdriver
            Match                      kube.*
            Resource                   k8s_container
            metadata_server            http://metadata.google.internal
            k8s_cluster_name           CLUSTER_NAME
            k8s_cluster_location       europe-west4
            resource_labels            container_name=$kubernetes['container_name'],namespace_name=$kubernetes['namespace_name'],pod_name=$kubernetes['pod_name']
            severity_key               level
            tag_prefix                 kube.
```
customParsers:
```
        [PARSER]
            Name cri
            Format regex
            Regex ^(?<time>[0-9]{4}-[0-9]{2}-[0-9]{2}[Tt ][0-9]{2}:[0-9]{2}:[0-9]{2}(?:\.[0-9]+)?(?:[Zz]|[+-][0-9]{2}:[0-9]{2})) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z

        [PARSER]
            Name        json
            Format      json

        [PARSER]
            Name        logfmt
            Format      logfmt

        [PARSER]
            Name        syslog
            Format      regex
            Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
            Time_Key    time
            Time_Format %b %d %H:%M:%S

        [PARSER]
            Name        glog
            Format      regex
            Regex       ^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source_file>[^ \]]+)\:(?<source_line>\d+)\]\s(?<message>.*)$
            Time_Key    time
            Time_Format %m%d %H:%M:%S.%L

        [PARSER]
            Name        network-log
            Format      json
            Time_Key    timestamp
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z

        [PARSER]
            Name    pod-tag-parser
            Format  regex
            Regex   (?<namespace_name>[^\.]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)
```

- Steps to reproduce the problem:

**Expected behavior**
logs are consistently named

**Your Environment**
gke 1.24.x with containerd nodes
2.0.9 fluentbit

**Comment by sharkymcdongles** [comment]
I suspect this could be related to this #6492

**Comment by sharkymcdongles** [comment]
I downgraded my version to 1.8.3 and it now works again. To me it seems there is some instability that leads to the resource_label not matching the log message perhaps due to a queue or something in the db not being in sync.

**Comment by cliles** [comment]
I can confirm this behavior on 2.x. In my testing using an image from master, I'm not seeing any restarts, but simply immediate incorrect resource_labels.

The labels are being set to the incorrect values.

**Comment by cliles** [comment]
+ @YoussefRizkalla and + @edsiper

**Comment by YoussefRizkalla** [comment]
I think your issue might be due to mixing two different methods for assigning resource labels.  The `resource_labels` option was a new option introduced in 2.0 (but it is still optional). If you choose to use it, then you should assign all your resource labels using it, meaning that you should not have the fields `k8s_cluster_name` or `k8s_cluster_location`. `tag_prefix` would also be unnecessary as it's used by the `local_resource_id` method. 

So I would suggest taking one of these approaches:

- If fluent-bit was working for your prior to migrating to 2.x, then you likely don't need to use the `resource_lables` option at all and could continue using the old method.
- If you would like to migrate to the new API, then remove the fields mentioned above. You will need to then also assign  `k8s_cluster_name` and `k8s_cluster_location` in the `resource_labels` option, which should be a simple plaintext assignment.

Hopefully this can help with this issue.

**Comment by cliles** [comment]
>which should be a simple plaintext assignment.

The API supports resource_labels based on mappings from an original field in the log entry to a destination field, but this  does not always seem to map correctly. In my testing, a majority of logs that are ingested to stackdriver have incorrect values from the mapping.

From a trace it seems to not work correctly when multiple records are sent to the output plugin in a single list. The mapping will only map from the first record even if each record has different values.

Example mapping config:

    [OUTPUT]
        Name stackdriver
        Match *
        resource k8s_container
        Labels_key labels
        Resource_labels cluster_name=$orig_resource['labels']['cluster_name'],location=$orig_resource['labels']['location'],container_name=$orig_resource['labels']['container_name'],namespace_name=$resource_namespace,pod_name=$orig_resource['labels']['pod_name']
        Alias stackdriver_out


A simplified trace shows:

```json
{
    "date": 1679536305.908259,
    "type": 3,
    "trace_id": "1",
    "plugin_instance": "forward.0",
    "records": [
        {
            "timestamp": 1679536240,
            "record": {
                "logger": "controller",
                "msg": "A message",
                "process": "audit",
                "resource_api_version": "v1",
                "resource_group": "",
                "resource_kind": "Pod",
                "resource_name": "deployment-2-java-775fccdf8b-6tfqn",
                "resource_namespace": "java-test-app",
                "severity": "INFO",
                "ts": 1679536239.344208,
                "timestamp": "2023-03-23T01:50:39.344479607Z",
                "audit_id": "2023-03-23T01:50:13Z",
                "logName": "projects/project_id/logs/stderr",
                "constraint_action": "dryrun",
                "receiveTimestamp": "2023-03-23T01:50:39.468186991Z",
                "insertId": "01t5inyudaw39mfl",
                "labels": {
                    "k8s-pod/policycontroller_configmanagement_gke_io": "true",
                    "k8s-pod/control-plane": "audit-controller",
                    "k8s-pod/gatekeeper_sh/system": "yes",
                    "k8s-pod/gatekeeper_sh/operation": "audit",
                    "k8s-pod/monitored": "true",
                    "k8s-pod/pod-template-hash": "5f5b476f",
                    "compute.googleapis.com/resource_name": "Name"
                },
                "orig_resource": {
                    "labels": {
                        "location": "region",
                        "namespace_name": "gatekeeper-system",
                        "project_id": "project_id",
                        "cluster_name": "cluster_name",
                        "pod_name": "gatekeeper-audit-5f5b476f-4nx4b",
                        "container_name": "manager"
                    },
                    "type": "k8s_container"
                },
                "constraint_kind": "K8sPSPCapabilities",
                "constraint_api_version": "v1beta1",
                "constraint_name": "psp-capabilities",
                "constraint_group": "constraints.gatekeeper.sh",
                "constraint_namespace": "",
                "details": {},
                "event_type": "violation_audited"
            }
        },
        {
            "timestamp": 1679536240,
            "record": {
                "logger": "controller",
                "msg": "A Second Message",
                "process": "audit",
                "resource_api_version": "v1",
                "resource_group": "",
                "resource_kind": "Pod",
                "resource_name": "thing-5d98fb48b8-lrmdc",
                "resource_namespace": "thingspace",
                "severity": "INFO",
                "ts": 1679536239.24347,
                "timestamp": "2023-03-23T01:50:39.243695664Z",
                "audit_id": "2023-03-23T01:50:13Z",
                "logName": "projects/project_id/logs/stderr",
                "constraint_action": "dryrun",
                "receiveTimestamp": "2023-03-23T01:50:39.468186991Z",
                "insertId": "rq87tiubytgwn97j",
                "labels": {
                    "k8s-pod/policycontroller_configmanagement_gke_io": "true",
                    "k8s-pod/control-plane": "audit-controller",
                    "k8s-pod/gatekeeper_sh/system": "yes",
                    "k8s-pod/gatekeeper_sh/operation": "audit",
                    "k8s-pod/monitored": "true",
                    "k8s-pod/pod-template-hash": "5f5b476f",
                    "compute.googleapis.com/resource_name": "Name"
                },
                "orig_resource": {
                    "labels": {
                        "location": "region",
                        "namespace_name": "gatekeeper-system",
                        "project_id": "project_id",
                        "cluster_name": "cluster_name",
                        "pod_name": "gatekeeper-audit-5f5b476f-4nx4b",
                        "container_name": "manager"
                    },
                    "type": "k8s_container"
                },
                "constraint_kind": "K8sPSPFSGroup",
                "constraint_api_version": "v1beta1",
                "constraint_name": "k8spspfsgroup",
                "constraint_group": "constraints.gatekeeper.sh",
                "constraint_namespace": "",
                "details": {},
                "event_type": "violation_audited"
            }
        }
    ],
    "start_time": 1679536299,
    "end_time": 1679536305
}
```

In this example, the desired behavior for the 2nd log entry would be to have the resource label namespace_name value equal to `thingspace`, but it will show as `java-test-app`. I didn't do much testing, but at a glance seems to be the 1st record in the resource trace is used for the mapping.

How is this suppose to work when the values are different and only known at runtime?

**Comment by cliles** [comment]
Maybe it would be helpful to provide any http-client debug, but I can't seem to figure out how to enable this. Is there some such setting at compile time?

**Comment by gerry-tock** [comment]
This is still an issue in `v2.2.1`. The values of `resource.labels.` is intermittently being populated with wrong data. 

I can provide more detailed debugging info, but just wanted to open this issue again. These resource labels are used to display log streams within the GKE UI and this ruins the user experience when trying to view logs there: https://console.cloud.google.com/kubernetes/pod/<region>/<cluster-name>/<workload-name>/<pod_name>/logs

**Comment by patrick-stephens** [comment]
@braydonk were you looking at something around this, I recall seeing some PRs/issues but it may be unrelated?

**Comment by braydonk** [comment]
The reason for the restarting could be related to #7552. Unfortunately I don't deeply understand how `out_stackdriver` handles these fields directly, so I don't have any ideas offhand why setting the resource label would somehow stop working due to a restart (or really behave inconsistently in any way based on my surface-level knowledge).

I'll reopen this and see if I can figure anything out.

**Comment by gerry-tock** [comment]
Thanks for all the help today @braydonk @patrick-stephens! Super quick response and helped me resolve my problem!
 We discussed this over [slack](https://fluent-all.slack.com/archives/C0CTQGHKJ/p1705009786525839) today and it's worth reading our convo for more context.

The tldr is that fluentbit sends log records to stackdriver in batches (proper term is chunk I believe). When they are sent, all of the fields have the correct information. Somewhere along the line, the resource labels for each log in a batch ends up being populated with the values of just one of the log records. This is the behavior described [here](https://github.com/fluent/fluent-bit/issues/6901#issuecomment-1480495791).

There is a way to avoid this behavior. The logs are grouped into batches based on their [Tags
](https://docs.fluentbit.io/manual/concepts/key-concepts#tag). My tags were generic, so no matter what container they were coming from, they had a Tag of `gcp_console_logs`. By updating the [Rewrite Tag](https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag) to include the pod name in the Tag, we can ensure that each log batch has records that come from the same pod. We specifically need to use the pod name, because it is the only unique key/value pair within a container's resource labels. 

This is the Rewrite Tag rule I used to resolve this in my environment:

`Rule   $kubernetes['pod_name'] ^(.+)$          gcp_console_logs_$1      true`

If you run into issues or just want to see the raw logs for better understanding, you can add this to your fluent-bit config:

```
      [OUTPUT]
          Name                      stdout
          Match                     gcp_console_logs_*
```

and you will see something like the following in your logs (where `[6]` is the index of this log in the current chunk and everything after `gcp_console_logs_` is the name of the pod that produced this log):

```
[6] gcp_console_logs_myservice-66487597f-c4lgr:
```

Please note `gcp_console_logs` is arbitrary within all of this, and just a tag that's useful within my env.

**Comment by braydonk** [comment]
Thank you for updating here! I took a deeper look so I could understand this behaviour in the plugin (I don't work on or near GKE so this part was all a mystery to me before).

I can 100% confirm that using the `logging.googleapis.com/local_resource_id` field does not work like the docs say it should. It will only look for the field in the first log event of the chunk sent to the plugin, and if it's found will use that mapping for the whole chunk. I am pretty sure this isn't the intended functionality.

I will speak to the team in charge of this and come up with a plan for how we will fix it.
