### ISSUE TITLE
lua filter can not get HOSTNAME env value in systemd service

### ISSUE THREAD

**Issue by freesinger** [fluent/fluent-bit#6910]
## Bug Report

**Describe the bug**

I start flb to collect logs by command line `/opt/fluent_bit/fluent-bit -e /opt/fluent_bit/flb_selectdb_output.so -c /opt/fluent_bit/conf/log.conf` and lua filter goes well with records processed.

But when running fluent-bit in systemd service, code `local landscape = os.getenv("HOSTNAME")` get a nil value.

**To Reproduce**
- Steps to reproduce the problem:
- systemd service:
```service
[Unit]
Description=Fluent-bit Service
After=network.target network-online.target remote-fs.target
[Service]
ExecStart=/opt/fluent_bit/fluent-bit -e /opt/fluent_bit/flb_selectdb_output.so -c /opt/fluent_bit/conf/log.conf
Restart=always
RestartSec=60
StartLimitInterval=3600
StartLimitBurst=5
[Install]
WantedBy=multi-user.target
```
- nohup
`nohup /opt/fluent_bit/fluent-bit -e /opt/fluent_bit/flb_selectdb_output.so -c /opt/fluent_bit/conf/log.conf > /dev/null 2>&1 &`

- log.conf
```conf
[SERVICE]
    flush 1
    log_level info
    parsers_file selectdb-parsers.conf

[INPUT]
    Name tail
    Multiline On
    Multiline_Flush 25
    Parser_Firstline be-parser
    Path /opt/selectdb/be/log/be.INFO
    Tag be.log
    db /home/selectdb/.flb/be.db
    Mem_Buf_Limit 200MB

[FILTER]
    Name lua
    Match be.*
    Script filter.lua
    Call be_filter

[OUTPUT]
    Name stdout
    Match be.*
```

- filter.lua
```lua
function be_filter(tag, timestamp, record)
    new_record = record
    local landscape = os.getenv("HOSTNAME")
    if landscape then
        new_record["hostname"] = landscape
        new_record["log_time"] = os.date("%Y-%m-%d") .. " " .. record["log_time"]
        new_record["collect_time"] = os.date("%Y-%m-%d %H:%M:%S")
        new_record["path"] = "/opt/selectdb/be/log/be.INFO"
        new_record["log_type"] = "be"
        new_record["msg"] = record["thread"] .. " " .. record["position"] .. " " .. record["msg"]
    end
    return 1, timestamp, new_record
end
```

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 2.0.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
What env vars are set for your process?
Does another filter like modify get the env var if you use it as a filter? 
What OS, etc?
