### ISSUE TITLE
feature: Use json exporter to convert json metrics to prometheus metrics format

### ISSUE THREAD

**Issue by rgomezceis** [fluent/fluent-bit#6920]
We need to use some inputs like MQTT but they only works with standard output.
Could it possible to add json exporter as a parser to convert json metrics to prometheus metrics with fluent bit?

https://github.com/prometheus-community/json_exporter

**Comment by agup006** [comment]
There is an experimental log to metric filter that you could use for this (https://github.com/fluent/fluent-bit/pull/6674). It's not merged yet but you could try building from the PR?
