### ISSUE TITLE
systemd input plugin doesn't report invalid filters which are (silently) rejected by systemd

### ISSUE THREAD

**Issue by phaas** [fluent/fluent-bit#6951]
Journal filters are required to follow a [specific format](https://www.freedesktop.org/software/systemd/man/sd_journal_add_match.html#):

> Parameter data must be of the form "FIELD=value", where the FIELD part is a short uppercase string consisting only of 0–9, A–Z and the underscore; it may not begin with two underscores or be the empty string. The value part may be anything, including binary

Users that accidentally specify an invalid FIELD (e.g. lowercase, double underscores, non-alphanum characters) will cause the journald match to be rejected. This can happen due to user confusion when e.g. also specifying the `Lowercase` attribute, since users may not be aware of the internals (which Filter is evaluated by systemd, while other processing is done post-filtering.)

```
[INPUT]
    Name            systemd
    Tag             host.*
    Systemd_Filter  _systemd_unit=docker.service
    Lowercase  true
```

The journal input [configuration code](https://github.com/fluent/fluent-bit/blob/3cc91564ea0614d70cb3cbfdb6b90aafd8d5eb9a/plugins/in_systemd/systemd_config.c#L175) **does not** check the return value.

```
    if (ctx->systemd_filters) {
        flb_config_map_foreach(head, mv, ctx->systemd_filters) {
            flb_plg_debug(ctx->ins, "add filter: %s (%s)", mv->val.str,
                journal_filter_is_and ? "and" : "or");
            sd_journal_add_match(ctx->j, mv->val.str, 0);
            if (journal_filter_is_and) {
                sd_journal_add_conjunction(ctx->j);
            }
            else {
                sd_journal_add_disjunction(ctx->j);
            }
```

**Please add return-value checks** for `sd_journal_add_match` (and the conjuction/disjuction calls?) and report this as a fatal error (this is only evaluated on startup and indicates a misconfiguration.)

> sd_journal_add_match(), sd_journal_add_disjunction() and sd_journal_add_conjunction() return 0 on success or a negative errno-style error code.

**Comment by nokute78** [comment]
Note: A patch #6952 was merged.

**Comment by ehienabs** [comment]
Hello, @phaas does the patch work for you now?

**Comment by phaas** [comment]
Hi @ehienabs , yes, the patch looks good. Thanks!
