### ISSUE TITLE
CRI Parser does not merge splittet Log Lines when K8s rotates the log files

### ISSUE THREAD

**Issue by frankhetterich** [fluent/fluent-bit#6957]
## Bug Report

**Describe the bug**
It happens that K8s rotates the logfile and truncates the JSON logline randomly:
`2023-01-27T13:40:28.92620435Z stdout P {"Timestamp":"2023-01-27T13:40:28.9222232+00:00","Level":"Information","MessageTemplate":"Request finished in {ElapsedMilliseconds}ms {StatusCode} {ContentType}","RenderedMessage":"Request finished in 0ms 200 null","Properties":{"ElapsedMilliseconds":0,"St`

The log then continues in a new File:
`2023-01-27T13:40:28.92735586Z stdout F atusCode":200,"ContentType":null,"EventId":{"Id":2,"Name":"RequestFinished"}`

Fluent-bit is sending these two lines as separate events.

**Expected behavior**
The CRI parser should notice by the P flag that it is an incomplete line and merge it with the next line in the new log file

**Your Environment**
* Version used: 2.0.8
* Configuration:
```
[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*_default_*.log
    multiline.parser  docker, cri
    DB                /var/log/fluentbit_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   Off
    Refresh_Interval  10`
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.23.14

**Comment by dvmdb** [comment]
This looks similar to #4387

**Comment by frankhetterich** [comment]
Is it similar to https://github.com/fluent/fluent-bit/issues/4387 or is it some different issue?

**Comment by frankhetterich** [comment]
We´re still facing these issues in out K8s clusters, even with the actual version of fluent-bit (3.2.4)

**Comment by frankhetterich** [comment]
Create new issue https://github.com/fluent/fluent-bit/issues/10041
