### ISSUE TITLE
Docker build Compile Avro

### ISSUE THREAD

**Issue by mooneym17** [fluent/fluent-bit#6962]
**Is your feature request related to a problem? Please describe.**
Docker builds missing -DFLB_AVRO_ENCODER=On flag. 

**Describe the solution you'd like**
Add -DFLB_AVRO_ENCODER=On to compile time options

**Describe alternatives you've considered**
lazy :) user builds own docker containers

**Comment by patrick-stephens** [comment]
I looked at this a while ago and it is a shed load of extra dependencies from memory, although that may be the Apache Arrow support as well.

However, feel free to submit a PR for it and I can review/merge. We would need to consider the impact on CVEs for it as well if there are extra dependencies but it does feel like a good idea.
