### ISSUE TITLE
Fluent Bit only receiving logs on first connection

### ISSUE THREAD

**Issue by Tamil-RK** [fluent/fluent-bit#6964]
## Bug Report

**Describe the bug**
if I start Fluentbit, then run my app, the logs get processed as expected. However, without restarting Fluentbit. but if I stop my app and then run my app again fluent bit is not working it requests to restart the fluent bit.

**To Reproduce**
- conf file settings
```
[SERVICE]
    Flush 1
    Log_Level debug
[INPUT]
    Name tcp
    Listen 127.2.2.1
    Port 5170
    Chunk_Size 32
    Buffer_Size 64
    Format json
[OUTPUT]
    Name file
    Match *
    Path E:\fluentbit
```

**Expected behavior**
fluent bit should receive input data without restarting.

**Testing video**
https://ttprivatenew.s3.amazonaws.com/pulse/tamil-rk/attachments/21099599/TinyTake08-03-2023-12-39-58.mp4

**Your Environment**
* Version used:2.09
* Operating System and version:windows 10

**Comment by sirwio** [comment]
Since you are using the tcp input plugin I am fairly sure your reported issue is a duplicate of:
https://github.com/fluent/fluent-bit/issues/6671
