### ISSUE TITLE
Want to filter specific logs from a log group and send it to Elastic

### ISSUE THREAD

**Issue by girishms-sentient** [fluent/fluent-bit#6965]
## Bug Report

**Describe the bug**
I want to send a log group's specific logs to ElasticSearch after filtering them.

Example:
Log has content:
`{ "foo" : "bar" }`
`{ "foo" : "bar1"}`
`{ "foo1" : bar2"}`

want to filter only `foo` logs from above.

**Expected behavior**
Filter specified log.

**Your Environment**

* Version used: Fluent Bit v2.0.9 Linux and 0.20.2 K8's
* Filters and plugins:

**Comment by ehienabs** [comment]
Hello @girishms-sentient could you include your parser and filter configuration or a similar dummy version? Thanks.
