### ISSUE TITLE
Tail input plugin with or without wild card paths separated with comma not being able to tail the files

### ISSUE THREAD

**Issue by NarineM** [fluent/fluent-bit#6967]
## Bug Report 
Can not see any data forwarded by fluent if configuration path contains multiple files separated by comma. Are there any known issues with fluentbit version 1.9? If yes, what version you would recommend to update to where these issues will not be seen?

Example of config path that does not work without wildcards:

[SERVICE]
    flush    5
    daemon    Off
    log_level    info
    log_file    /var/opt/microsoft/azuremonitoragent/log/fluentbit.log
    http_server    Off
[INPUT]
    Name    tail
    Path    /home/mrajput/customlogfolder/armand.txt, /home/mrajput/customlogfolder/customfolder2/MRajput.txt
    db    /etc/opt/app1/fluentbit/db/c9258482690911779810_2750851566672475290.db
    tag    c9258482690911779810_2750851566672475290
    key    RawData
    Buffer_Max_Size    1mb

Example of config path that does not work with wildcards:
[SERVICE]
    flush    5
    daemon    Off
    log_level    info
    log_file    /var/opt/microsoft/azuremonitoragent/log/fluentbit.log
    http_server    Off
[INPUT]
    Name    tail
    Path  //opt//kx//kdb//logs//*log,//opt//kx//do//logs//*log,//opt//kx/olek//*log
    db    /etc/opt/app1/fluentbit/db/c9258482690911779810_2750851566672475290.db
    tag    c9258482690911779810_2750851566672475290
    key    RawData
    Buffer_Max_Size    1mb

**Describe the bug**
Tail input plugin with or without wild card multi file path separated by comma is not working

**To Reproduce**

**Expected behavior**

This should have worked similar to having multiple input plugins in the config with a single file path in "Path" configuration setting.

**Your Environment**

Azure VM
Fluentbit version 1.9
Ubuntu 20.04/Redhat 8.7

**Additional context**

We have setup fluentbit to forward some logs to our application. Here is a snippet from fluentbit.log for the second repro:
[2023/02/08 11:49:01] [debug] [in_tail] scanning path //opt//kx//kdb//logs//*log,//opt//kx//do//logs//*log,//opt//kx/olek//*log
[2023/02/08 11:49:01] [debug] [in_tail] Cannot read info from: //opt//kx//kdb//logs//*log,//opt//kx//do//logs//*log,//opt//kx/olek//*log

For the first issue with no wild cards, there are no error messages in fluentbit.log.

**Comment by RicardoAAD** [comment]
Hello @NarineM,

I tested your configuration in master branch and also in Fluent-bit 1.9 and it is working fine, no issues when tailing two path at the same time.
Could you please:
* Share the whole config file, I would like to check the output section.
* Set log_level to debug and share Fluent-Bit logs.

Thanks,
Ricardo

**Comment by NarineM** [comment]
We found a workaround by converting single fluent config that has a path property with comma separated file paths into multiple fluent configuration entries each with a single file path and no longer use comma separated paths.
