### ISSUE TITLE
Large audit logs being dropped

### ISSUE THREAD

**Issue by ades6960** [fluent/fluent-bit#6974]
## Bug Report

**Describe the bug**
We are using fluent-bit to pass audit logs to CloudWatch from ECS. We have observed that large logs with approximately more than 920 lines are been dropped. Sample audit log format is as follows.
```
{
    "@timestamp": "2023-03-08T13:29:19.699Z"
    "auditMessage": { large JSON object },
    "level": "INFO",
    "logger": "Audit",
}
```

**To Reproduce**

fluent-bit configuration
```
[PARSER]
    Name   json
    Format json

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser regex

[OUTPUT]
    Name cloudwatch
    Match *firelens*
    region ${REGION}
    log_key log
    log_group_name ${LOG_GROUP_NAME}
    log_stream_prefix ${LOG_STREAM_PREFIX}
```
note: default input configurations are used

**Expected behavior**
Expected behavior is for all audit logs to be pushed to CloudWatch regardless of the size.

**Your Environment**

* Version used: latest
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): Cloudwatch
* Server type and version: ECS
* Operating System and version: Linux
* Filters and plugins: parser and cloudwatch

**Comment by lecaros** [comment]
You're missing the INPUT config and the parser. The input is for sure relevant here.

**Comment by ades6960** [comment]
> You're missing the INPUT config and the parser. The input is for sure relevant here.

Updated the report with the missing configs.
