### ISSUE TITLE
chunk '1-1678325690.177395536.flb' cannot be retried: task_id=3, input=tail.0 > output=es.5 ISSUE

### ISSUE THREAD

**Issue by audwl** [fluent/fluent-bit#6976]
Hello
Fluentbit is configured in the Kubernetes environment to transmit logs to Elasticsearch and SSDM for monitoring.
Through the test, we confirmed that the log was delivered to ElasticSearch,
We proceeded with distribution using Helm and confirmed the log delivery of Fluentbit, but it was confirmed that the log was not delivered to ElasticSearch.
I have configured the Fluentbit-configmap.yaml file as below.
----------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: (Monitoring namespace)
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                     5
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf
        #        Streams_File              streams.conf
        HTTP_Server               ${HTTP_SERVER}
        HTTP_Listen               0.0.0.0
        HTTP_Port                 ${HTTP_PORT}
        storage.path              /var/fluent-bit/state/flb-storage1/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 500M
....
[OUTPUT]
        Name                es
        Match               *
        Host                (Domain Endpoint)
        Port                443
        HTTP_User           User ID
        HTTP_Passwd         User Password
        Index               fluentbit
        Type                doc
        tls                 On
        tls.verify          Off
        #        Suppress_Type_Name  On
        #        AWS_Auth            On
        AWS_Region          ap-northeast-1
        #tls                 On
----------------------------------------------------------------------------------------------------------------------
I tried to check the log delivery, but I checked the error message regarding the log delivered to ElasticSearch.
=======================================================================
[2023/03/09 01:35:03] [ warn] [engine] chunk '1-1678325690.177395536.flb' cannot be retried: task_id=3, input=tail.0 > output=es.5
[2023/03/09 01:35:04] [ warn] [engine] chunk '1-1678325690.380914216.flb' cannot be retried: task_id=5, input=tail.3 > output=es.5
[2023/03/09 01:35:06] [ warn] [engine] chunk '1-1678325690.146729171.flb' cannot be retried: task_id=4, input=tail.1 > output=es.5
=======================================================================

**Comment by agup006** [comment]
heya try trace_error and trace_output which can give more details on the error. One common one is replace dots configuration parameter
