### ISSUE TITLE
out_forward plugin never recycles TCP connections

### ISSUE THREAD

**Issue by gwny** [fluent/fluent-bit#6977]
## Bug Report

**The out_forward plugin closes tcp connection immediately after flushing the data, the option `net.keepalive` is nor working.**

**To Reproduce**
Fluent-bit output config:
```
[OUTPUT]
    Name          forward
    Match_Regex  <record-tag>
    Host          <fluentd-host>
    Port          43000
    Retry_Limit   5
    net.keepalive_max_recycle   2000
    Compress      gzip
```
The network packets which captured by `tcpdump` likes below:
![fluent_bit_forward_plugin_packets](https://user-images.githubusercontent.com/6380723/223963072-55ca0c4e-726d-42aa-acfb-6732031014be.png)
The out_forward plugin closes tcp connection immediately after flushing the data.

**Expected behavior**
The tcp connections can be recycled when using out_forward plugin.

**Your Environment**

* Version used: v2.0.8, but the latest version should have the same problem.
* Environment name and version (e.g. Kubernetes? What version?): AWS EC2
* Filters and plugins: in_tail and out_forward

**Additional context**
The problem seems to be caused by the value of `conn->recycle`.
1. After flushing data, the out_forward plugin will call `flb_upstream_conn_release()` to try to release the connection.
    [https://github.com/fluent/fluent-bit/blob/v2.0.8/plugins/out_forward/forward.c#L1602](https://github.com/fluent/fluent-bit/blob/v2.0.8/plugins/out_forward/forward.c#L1602)
2. In flb_upstream_conn_release(), fluent-bit will decide whether to recycle the connection based on `u->base.net.keepalive ==FLB_TRUE && conn->recycle == FLB_TRUE && conn->fd > -1`
    [https://github.com/fluent/fluent-bit/blob/v2.0.8/src/flb_upstream.c#L717](https://github.com/fluent/fluent-bit/blob/v2.0.8/src/flb_upstream.c#L717)
3. The `conn->recycle` value was set in function `create_conn()` by the result from `flb_stream_is_keepalive()`.
    [https://github.com/fluent/fluent-bit/blob/v2.0.8/src/flb_upstream.c#L515](https://github.com/fluent/fluent-bit/blob/v2.0.8/src/flb_upstream.c#L515)
4. In `flb_stream_is_keepalive()`, fluent-bit will read flag bit `FLB_IO_TCP_KA`, but it seems that the flag bit FLB_IO_TCP_KA was not set anywhere, so the `conn->recycle` is always false.
    [https://github.com/fluent/fluent-bit/blob/v2.0.8/include/fluent-bit/flb_stream.h#L134](https://github.com/fluent/fluent-bit/blob/v2.0.8/include/fluent-bit/flb_stream.h#L134)

While in 1.x version, the `conn->recycle` value was directly set by option `net.keepalive`, such as:
[https://github.com/fluent/fluent-bit/blob/v1.9.10/src/flb_upstream.c#L538](https://github.com/fluent/fluent-bit/blob/v1.9.10/src/flb_upstream.c#L538)

**Comment by leonardo-albertovich** [comment]
Good catch, it seems like that one slipped through the cracks but your RCA is spot on.

Please correct me if I'm wrong but the problem seems to be that in `flb_output_upstream_set` the stream flags are set with just the flags that are inferred from the plugin instance [here](https://github.com/fluent/fluent-bit/blob/9444fdc5ee858a42b58b9a97010d997096e63634/src/flb_output.c#L1305) but without taking in account the `net_setup` data.

Would you be able to add something like this in line 1303 to validate the approach : 

```
if (net->keepalive) {
    flags |= FLB_IO_TCP_KA;
}
```

I would really appreciate it if you were able to test this and I'm sure it would greatly expedite the process. 
If you choose to do so and send a PR to fix it ping me and I will attend to it as soon as possible. 

Thank you for your contribution!

**Comment by gwny** [comment]
> Good catch, it seems like that one slipped through the cracks but your RCA is spot on.
> 
> Please correct me if I'm wrong but the problem seems to be that in `flb_output_upstream_set` the stream flags are set with just the flags that are inferred from the plugin instance [here](https://github.com/fluent/fluent-bit/blob/9444fdc5ee858a42b58b9a97010d997096e63634/src/flb_output.c#L1305) but without taking in account the `net_setup` data.
> 
> Would you be able to add something like this in line 1303 to validate the approach :
> 
> ```
> if (net->keepalive) {
>     flags |= FLB_IO_TCP_KA;
> }
> ```
> 
> I would really appreciate it if you were able to test this and I'm sure it would greatly expedite the process. If you choose to do so and send a PR to fix it ping me and I will attend to it as soon as possible.
> 
> Thank you for your contribution!

Thanks for your reply and pointing out the position which the flag should be set, I have tested it and submitted a PR https://github.com/fluent/fluent-bit/pull/6992, please review it.
