### ISSUE TITLE
Changing how build tools are built.

### ISSUE THREAD

**Issue by raumanm** [fluent/fluent-bit#6980]
**Is your feature request related to a problem? Please describe.**
Defining FLB_STATIC_CONF on Yocto recipe for arm architecture on x86_64  linux host prevents the compilation. 

**Describe the solution you'd like**
Build time tools should be compiled for host architecture, not target architecture: 'xdd-c' binary gets compiled into arm binary on a x86_64 host and CMake cannot use it. 

**Additional context**
Currently using bitbake recipe for version 1.9.7 of fluentbit on yocto thud.

**Comment by patrick-stephens** [comment]
Can you provide a PR to resolve this? The Yocto recipe is hard for us to maintain as we do not have easy access to it.
