### ISSUE TITLE
SIGSEGV at startup when a rewrite_tag filter has no Match

### ISSUE THREAD

**Issue by lilhore** [fluent/fluent-bit#6991]
## Bug Report

**Describe the bug**
fluentbit pod start fail with below error k8s 1.23 and fluentbit v1.9.9

[2023/03/10 13:05:21] [engine] caught signal (SIGSEGV)
[2023/03/10 13:05:21] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag application.bdl.log
#0  0x55962368cb2a      in  cb_rewrite_tag_filter() at plugins/filter_rewrite_tag/rewrite_tag.c:412
#1  0x559623563896      in  flb_filter_do() at src/flb_filter.c:124
#2  0x55962359fe7c      in  input_chunk_append_raw() at src/flb_input_chunk.c:1585
#3  0x5596235a01b6      in  flb_input_chunk_append_raw2() at src/flb_input_chunk.c:1707
#4  0x5596235ca9b0      in  process_content() at plugins/in_tail/tail_file.c:536
#5  0x5596235ccd72      in  flb_tail_file_chunk() at plugins/in_tail/tail_file.c:1326
#6  0x5596235c47d3      in  in_tail_collect_static() at plugins/in_tail/tail.c:188
#7  0x559623563379      in  flb_input_collector_fd() at src/flb_input.c:1239
#8  0x55962357744b      in  flb_engine_handle_event() at src/flb_engine.c:440
#9  0x55962357744b      in  flb_engine_start() at src/flb_engine.c:763
#10 0x559623556994      in  flb_lib_worker() at src/flb_lib.c:626
#11 0x7f8ec570aea6      in  ???() at ???:0
#12 0x7f8ec4fdaaee      in  ???() at ???:0
#13 0xffffffffffffffff  in  ???() at ???:0
v 

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 1.9.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by lilhore** [comment]
When the fix will be integrated into fluentbit and when it will be available ?

**Comment by lilhore** [comment]
There is no action on PR https://github.com/fluent/fluent-bit/pull/6998, Please let us know when it will be available ?

**Comment by nokute78** [comment]
Could you try v2.1.0+ ?

We added a new decoding layer from v2.1.0 and it may solve this issue.
