### ISSUE TITLE
Domains without tld fail to with "Misformatted domain name" using ASYNC resolver

### ISSUE THREAD

**Issue by jsoo1** [fluent/fluent-bit#7002]
## Bug Report

**Describe the bug**

What constitutes a valid domain name seems to be different between legacy and async dns resolvers.

**To Reproduce**
```
[OUTPUT]
    Name loki
    ...
    Host examplehostname
    net.dns.resolver ASYNC
```
`/etc/hosts`:
```
192.168.1.3 examplehostname
```
- Example log message if applicable:
```
[ warn] [net] getaddrinfo(host='examplehostname', err=8): Misformatted domain name
```
... But dns resolution succeeds with `net.dns.resolver LEGACY`.

**Expected behavior**

Valid domain names should be the same between dns resolvers.

**Your Environment**
* Version used: `2.0.9`
* Environment name and version (e.g. Kubernetes? What version?): nixos/systemd
* Operating System and version: NixOS 21.11

**Additional context**
I upgraded from 1.8.9 and found missing logs.

**Comment by leonardo-albertovich** [comment]
Uhm, that's puzzling, I just tested it on my machine and it worked as expected. 

What I can say is that fluent-bit does not impose any restrictions on it, all it does is forward that information the either the system or c-ares so I suspect something very specific might be happening here and I wonder how could we troubleshoot it.

Do you think you would be able to provide a container spec that reflects your system and reproduces the issue?

**Comment by jsoo1** [comment]
Hm. I will try making a minimal reproducer for you.
