### ISSUE TITLE
Kafka output is not enabled in the Windows build

### ISSUE THREAD

**Issue by BenoitPoulet** [fluent/fluent-bit#7010]
## Bug Report

**Describe the bug**
Kafka output is not enabled in the Windows build

**To Reproduce**
- edit your fluent-bit.conf and add this :
```
[OUTPUT]
    Name        kafka
    Match       *
    Brokers     siem-kafkas-preprod.schnappi.com:9092
    Topics      logsappli
    Timestamp_Format iso8601
```

Then try to run Fluent-bit
```
PS C:\Program Files\fluent-bit> .\bin\fluent-bit.exe -c .\conf\fluent-bit.conf -v
Fluent Bit v2.0.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/03/09 16:38:37] [error] [config] section 'kafka' tried to instance a plugin name that don't exists
[2023/03/09 16:38:37] [error] configuration file contains errors, aborting.
```

**Expected behavior**
Kafka must be available as an output, 

**Your Environment**

* Version used: v2.0.9
* Operating System and version: Windows 2019 server

**Additional context**
I would like to use the Kafka ouput on Windows as we can do this under Linux distributions.

**Comment by patrick-stephens** [comment]
I'm not sure it builds @tarruda?

**Comment by patrick-stephens** [comment]
I don't think this is a bug though, it's a feature request as it was deliberately disabled.

**Comment by BenoitPoulet** [comment]
Sad, this info could be added in the Kafka output module : 
https://docs.fluentbit.io/manual/pipeline/outputs/kafka/
 
It could be nice if the feature can be added, librdkafka is supported under Windows.

**Comment by tarruda** [comment]
> I'm not sure it builds @tarruda?

I never tried. If librdkafka can be built on windows, I don't see why it wouldn't work

**Comment by atharva29** [comment]
Please provide any update on this issue. As this is critical thing.
