### ISSUE TITLE
Not able to use environment variable as a (Splunk HEC) token. 

### ISSUE THREAD

**Issue by BlueCog** [fluent/fluent-bit#7011]
## Bug Report

**Describe the bug**

I'd like to use an environment variable from a k8s secret. When I read the docs this seems possible.
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/variables

But when i'm trying to implement this I cannot connect:

For example:

```
    [OUTPUT]
        Match *
        Name splunk
        Host endpoint.end
        Port 8088
        Splunk_Token ${SPLUNK_TOKEN}
```

Container spec:

```
        - name: SPLUNK_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunktoken
              key: token
```

When accessing the shell:

```
echo ${SPLUNK_TOKEN}
```
The correct token is displayed. 

But when running a test I get:

```
[2023/03/13 16:27:12] [ warn] [output:splunk:splunk.1] http_status=400:
{"text":"Invalid data format","code":6,"invalid-event-number":0}

```

I've also tried quoting `"${SPLUNK_TOKEN}"` but that didn't do anything. 

When I add the HEC Token in the config file (without env) I can connect and everything works like expected. 

**Expected behavior**

I would expect to be able to use an evironment variable for a Splunk (HEC) Token

**Your Environment**

Fluent Bit: v2.0.5
Image: [calyptia-fluent-bit](https://catalog.redhat.com/software/container-stacks/detail/61d87331e4578f8bf95ed96f)

**Additional context**
OpenShift Platform

**Comment by RicardoAAD** [comment]
Hello @BlueCog 

The error that you are getting is not related to an incorrect token; when there's a problem with tokens you will see something like this: 
`[2023/03/14 13:46:48] [ warn] [output:splunk:splunk.2] http_status=403: {"text":"Invalid token","code":4}`

One reason for getting this error `{"text":"Invalid data format","code":6,"invalid-event-number":0}"`  is that, Splunk by default only accepts events with a max size of 5MB; anything larger than 5MB will be discarded, and this error will be seen
Check the Splunk documentation:
https://docs.splunk.com/Documentation/Splunk/latest/admin/inputsconf

You can also see this error when the format of the message is not correct, this is why I'd like to know if Splunk_Send_Raw is enabled in your config if it does the wrong fields in the event could be the reason why you are seeing this error.

Could you please provide:
* The fluent-bit logs with log_level set as debug
* The whole fluent-bit config

**Comment by BlueCog** [comment]
Thanks @RicardoAAD,

`Splunk_Send_Raw `is not defined in the config.

> You can also see this error when the format of the message is not correct,

The weird part is that if i copy paste the HEC Token into the config it works without a porblem. But when I use ${SPLUNK_TOKEN} and provide the token via ENV this issue arrises... so the only difference in the context is the way the HEC Token is provided to the config.....

The config (i'll try to generate a clear log file lateron):

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluent-bit-splunk
data:
  fluent-bit.conf: >-
    [SERVICE]
        Parsers_File /fluent-bit/etc/parsers.conf
        Daemon Off
        Log_Level debug
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name forward
        Port 24224

    [FILTER]
        Name modify
        Match *
        Add sourcetype elastic-audit

    [FILTER]
        Name parser
        Match *
        Key_Name message
        Parser elastic_parser
        Reserve_Data On

    [FILTER]
        Name grep
        Match *
        Regex type node

    [OUTPUT]
        Name stdout
        Match *

    [OUTPUT]
        Match *
        Name splunk
        Host splunkhfwd.endpoint.com
        Port 8088
        Splunk_Token ${SPLUNK_TOKEN}
        event_host fluent-bit
```

**Comment by RicardoAAD** [comment]
Can you paste the section of your daemonset where you are defining the env variable for fluent-bit pod?
