### ISSUE TITLE
Fluent-bit packages repository for Ubuntu returns 403 using User-Agent

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#7014]
## Bug Report

**Describe the bug**
All requests with a user agent specifying the urllib python package results in a 403 when calling `packages.fluentbit.io`.

**To Reproduce**
- `curl -H 'User-Agent: Python-urllib/2.6' https://packages.fluentbit.io/ubuntu/focal/dists/focal/main/binary-amd64/Packages -v`

**Expected behavior**
The request should not 403. This behaviour changed since the release of 2.0.9, 2.0.8 worked.

**Additional context**
We use concourse to monitor for updates to the package, which uses a Python resource to make calls to this repository and check the versions available.

**Comment by patrick-stephens** [comment]
Very strange, this was all working so I will investigate what could have changed (not much did here for 2.0.9).

**Comment by patrick-stephens** [comment]
Yeah so it works fine without the user agent config.
Makes me suspect it is something on the nginx config then: https://github.com/fluent/fluent-bit-infra/blob/main/terraform/provision/package-server-provision.sh.tftpl

We had an old legacy server (un-managed) in a data centre to be decommisioned so have migrated to a fully managed set up now and looks like this has impacted some specific settings.

**Comment by patrick-stephens** [comment]
I'll see if I can figure out what is going on with the server either rejecting it or Cloudflare.

**Comment by braunsonm** [comment]
Thanks @patrick-stephens this is really important for us!

**Comment by patrick-stephens** [comment]
We're getting a lot of crawling of the auto-indexed repos so I may disable that as well as it is just spamming the logs.
Looking at the server side logs we see nothing for the failure and I do see the successful access for non-agent curl.

**Comment by braunsonm** [comment]
Unclear from your comment @patrick-stephens are you saying you're still working on fixing it for the server or you're saying that you want us to use the S3 bucket from now on?

**Comment by patrick-stephens** [comment]
I will (attempt to) fix it but if you're desperate for a workaround then the S3 bucket is available, just do not rely it long term.

**Comment by patrick-stephens** [comment]
This was Cloudflare triggering a "Browser integrity check" so I have added an exception.

**Comment by braunsonm** [comment]
Hey @patrick-stephens I'm still getting 403's depending on the python version used. The one I sent you above was just an example of what it would look like. For instance this also 403's

```
curl -H 'User-Agent: Python-urllib/3.6' https://packages.fluentbit.io/ubuntu/focal/dists/focal/main/binary-amd64/Packages -v
```

**Comment by patrick-stephens** [comment]
Ah ok, I only did a specific rule so please let me know what should be allowed.

Also, this seems to be a Cloudflare standard rule so I'm not sure why.

**Comment by braunsonm** [comment]
To be honest @patrick-stephens I think you should be disabling the browser integrity check. It doesn't make much sense to have a browser integrity check on something that will not be used by browsers (like an APT repo).

You can do this globally on the domain under the security settings. Or on your specific packages subdomain with a page rule. 

I could tell you to allow the one I sent above, but as soon as python is updated that will just change again.

Also please reopen this issue if you have a chance.

**Comment by patrick-stephens** [comment]
I can do, it's just part of the standard ruleset so I'd not realised it even was there.

**Comment by braunsonm** [comment]
Confirmed it's working well for us now! Thanks a bunch @patrick-stephens
