### ISSUE TITLE
CentOS package repository is incorrectly putting aarch64 packages into the x86_64 repository

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#7015]
## Bug Report

**Describe the bug**
Since Fluent Bit 2.0.9, CentOS packages for aarch64 are also being published to the x86_64 repository. This causes `dnf` to return two results when calling `dnf info fluent-bit` even if you `--forcearch x86_64` and use the x86_64 URL `https://packages.fluentbit.io/centos/7/x86_64/`

**To Reproduce**
- Add `https://packages.fluentbit.io/centos/7/x86_64/` to your CentOS repository
- Call `dnf info fluent-bit`
- Notice two versions are being returned, one for x86_64 and one for aarch64. Only x86_64 should be returned in the x86_64 subpath

Note if you also just explore the repodata.xml files under that path, you can see the extra architecture in the XML.

**Expected behavior**
Only x86_64 packages should be published to the x86_64 path

**Additional context**
This is used to monitor for releases of fluent-bit to update our systems. This breaks some parsing because only one version is expected for that package, not two dupilcates.

**Comment by patrick-stephens** [comment]
This is down to how the old repos were constructed (per arch) and the new ones (multiarch). Unfortunately the docs follow the old approach so we provided a symlink to handle it which unfortunately means you therefore see multiarch.

There is only one repo, it just looks like two to allow anyone using the old documented approach to carry on working.

**Comment by patrick-stephens** [comment]
I will update the docs to make it clearer.
