### ISSUE TITLE
CentOS fluent-bit packages repository is not indexing new packages

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#7016]
## Bug Report

**Describe the bug**
Fluent-bit rpm's are released in the CentOS repository, but it looks like the repodata (which dnf, yum use) has not been updated correctly so the operating system is unaware there is an update.

**To Reproduce**
- Go to `https://packages.fluentbit.io/centos/7/x86_64/repodata/`
- If you download the `repomd.xml` you will see the primary database that is being referenced. This is an old index from January and is not the newest which includes 2.0.9. It looks like the new index should be `https://packages.fluentbit.io/centos/7/x86_64/repodata/e7f0d5f9ce01be8238af0127051bf0b760cdadc18155e210bfe5ce2e0fb4089c-primary.xml.gz` but it is not being referenced right now.

**Expected behavior**
The CentOS package repository is correctly updated.

**Comment by patrick-stephens** [comment]
I will check the server has sync'd from the S3 bucket correctly. We did have an issue with Cloudflare caching the metadata but that should be resolved now.

**Comment by patrick-stephens** [comment]
There was a failure due to disk space on the runner for the 2.0.9 release which meant I had to retry the repo update so wondering if that is related? 

Separately we have a test to verify we can install the correct version of the package after release but this works with the S3 bucket directly so makes me suspect an issue with the sync to the server.

**Comment by patrick-stephens** [comment]
Yeah, the S3 bucket seems to have it correct:
```shell
$ curl http://packages.fluentbit.io.s3.amazonaws.com/centos/7/repodata/repomd.xml
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
  <revision>1675680680</revision>
  <data type="primary">
    <checksum type="sha256">e7f0d5f9ce01be8238af0127051bf0b760cdadc18155e210bfe5ce2e0fb4089c</checksum>
    <open-checksum type="sha256">fda8fadda86b31086c00d7c4505f64cc4baddd7facf91bf517c02a25f14762bc</open-checksum>
    <location href="repodata/e7f0d5f9ce01be8238af0127051bf0b760cdadc18155e210bfe5ce2e0fb4089c-primary.xml.gz"/>
    <timestamp>1675680680</timestamp>
    <size>38971</size>
    <open-size>844442</open-size>
  </data>
```
vs the server sync'd version:
```shell
$ curl https://packages.fluentbit.io/centos/7/repodata/repomd.xml
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
  <revision>1673886886</revision>
  <data type="primary">
    <checksum type="sha256">577f465a88688aecb0d1d2e72537ae9a687b15d533ab3565b056da5f25296513</checksum>
    <open-checksum type="sha256">390b1c86eb8181f506ad35b492db6f7dd1281c43fbc2ba144eae91bcb6d2ece3</open-checksum>
    <location href="repodata/577f465a88688aecb0d1d2e72537ae9a687b15d533ab3565b056da5f25296513-primary.xml.gz"/>
    <timestamp>1673886886</timestamp>
    <size>38425</size>
    <open-size>833407</open-size>
  </data>
```

So, looks like the release built correctly and did everything but the `aws s3 sync` has not updated the contents on the server side. I may have to force it to for metadata depending on how the `aws` client decides a file has changed. I'll also check that Cloudflare is not caching it and providing a cached copy.

**Comment by patrick-stephens** [comment]
This was a fun ride, turns out the aws sync ignores timestamps locally unless you force it: https://github.com/aws/aws-cli/issues/1074

Metadata files do not change size generally so required me to add the `--exact-timestamps` flag to get it working on the packages server.
