### ISSUE TITLE
Input Forward plug-in support socket activation on UNIX socket

### ISSUE THREAD

**Issue by elafontaine** [fluent/fluent-bit#7026]
**Is your feature request related to a problem? Please describe.**
As I'm using fluent-bit for sending logs since the boot of my machine to a centralized logging solution, I would love to receive any messages that were sent to fluent-bit prior to the application starting up.  Especially when fluent-bit is started from within a container (which require other services to have been started).  

**Describe the solution you'd like**
A way to do so is to use the socket activation feature of systemd if it's available.  This would enable the socket to be deposited very early in the boot process and fluent-bit to pick up those messages when it's ready.  

It's currently not possible to just put socket activation in place due to the removal of the unix socket file, so this feature request would require 2 steps probably (see link) ; 
https://github.com/fluent/fluent-bit/blob/master/plugins/in_forward/fw.c#L73

For more details on socket activation and it's inner workings; http://0pointer.de/blog/projects/socket-activation.html

**Describe alternatives you've considered**
Sending the logs from docker and other services directly to another machine... but kind of defeat the purpose.

**Additional context**

I'm trying to get a way to reliably gets logs into my centralized logging solution.  fluent-bit is the agent we decided to use for it's ease-of-use, but we've hit this limitation that all logs on the unix socket are dropped in between fluent-bit restart.

Enabling the unix socket to be reused if it's passed or already exist would enable other apps to have their logs generated prior to the start of the fluent-bit to still be considered.

**Comment by leonardo-albertovich** [comment]
Sounds like a good improvement to me, I can't commit to a time table at the time but I agree about the importance of it.

**Comment by elafontaine** [comment]
Hi, I can look into contributing a bit in my lost time.

My proposition would be to look into using a socket in the following conditions; 
1-  If a file descriptor is passed as a program parameter, use it and go to step 4 (using the things from systemd article for detecting it)
2- if unix, configure the listening socket (not the file descriptor) (without deleting the existing socket file if it's rightly configured)
3- try to reserve the socket resource (unix socket or tcp socket)
4- run the rest of the program as is


This would enable the forward plug-in to not mind if the socket file already exist (for unix) or to pass it as a "socket activation"-like feature.

It's high-level, but it's what I would look to implement.  thoughts ?

**Comment by elafontaine** [comment]
Can I request for it to not be stale ?

**Comment by elafontaine** [comment]
Could I get a exempt ?

**Comment by elafontaine** [comment]
Hi Folks, 

What would you like to do about this one ?

**Comment by elafontaine** [comment]
Hi Folks,

What would you like to do about this one ?
