### ISSUE TITLE
Failed to use fluent-bit as dynamic library

### ISSUE THREAD

**Issue by jeongukjae** [fluent/fluent-bit#7028]
## Bug Report

**Describe the bug**

Cannot build a program with fluent bit dynamic library.

The error log:

```
In file included from stdout.c:22:
In file included from ../tmp/usr/local/include/fluent-bit/flb_filter.h:26:
In file included from ../tmp/usr/local/include/fluent-bit/flb_regex.h:27:
In file included from ../tmp/usr/local/include/fluent-bit/flb_compat.h:34:
../tmp/usr/local/include/monkey/mk_core.h:33:10: fatal error: 'mk_core/mk_core_info.h' file not found
#include <mk_core/mk_core_info.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
- Steps to reproduce the problem:

Clone and set the working directory to fluent-bit.

1. `brew install libyaml openssl bison` (cmake is already installed in my env and version is 3.17.3)
2. `cmake ..`
3. `make`
4. `make DESTDIR=`pwd`/../tmp` install 

And try to build any arbitrary filter plugin to a shared object. (I tried this with filter_stdout)

**Expected behavior**

Compiled successfully.

**Screenshots**

**Your Environment**

* Version used: tag: v2.0.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Mac Monterey 12.4
* Filters and plugins:

**Additional context**

I think configured files/libraries like the following links are not installed.

* https://github.com/fluent/fluent-bit/blob/eb70ee72edfedc66afb038e1ce323469fd44457e/lib/monkey/mk_core/CMakeLists.txt#L146-L149
* cmetrics
* cfl
* ...

**Comment by parvit** [comment]
Hi, i've also run into this issue trying to build a custom plugin using only the packages provided via apt.
I have the following installed:
`fluent-bit` `fluent-bit-headers` `fluent-bit-headers-extra` at version `2.1.4`

The file `mk_core_info.h` does not seem to be installed along with the other headers:

https://github.com/fluent/fluent-bit/blob/2060c69cad82656abed590fca051842859cb5230/lib/monkey/include/CMakeLists.txt#L1-L11

It would be great if this could be fixed, i'm open to providing a patch if this expedites the release.

**Comment by jeongukjae** [comment]
do not close this
