### ISSUE TITLE
`prometheus_scrape` input plugin can't handle metrics when the response is larger than 10Mb

### ISSUE THREAD

**Issue by tomasz-sel** [fluent/fluent-bit#7032]
## Bug Report

**Describe the bug**

Prometheus scrape input plugin can't  handle metrics when the response is larger than 10Mb.
This is hardcoded in the plugin code
[https://github.com/fluent/fluent-bit/blob/eb70ee72edfedc66afb038e1ce323469fd44457e/plugins/in_prometheus_scrape/prom_scrape.c#L101](https://github.com/fluent/fluent-bit/blob/eb70ee72edfedc66afb038e1ce323469fd44457e/plugins/in_prometheus_scrape/prom_scrape.c#L101)

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2023/03/14 22:42:10] [ warn] [http_client] cannot increase buffer: current=10240000 requested=10272768 max=10240000
[2023/03/14 22:42:10] [error] [input:prometheus_scrape:prometheus_scrape.1] error decoding Prometheus Text format
```
- Steps to reproduce the problem:
Expose Prometheus metrics  endpoint with a huge amount of metrics (Http response has to be larger than 10Mb)
**Expected behavior**

Should be available a configuration parameter to change the buffer size 

**Screenshots**

**Your Environment**

* Version used:  2.0.9
* Configuration:
```
[INPUT]
    name prometheus_scrape
    host localhost 
    port 80
    tag metrics
    metrics_path /metrics
    scrape_interval 60s

[OUTPUT]
    Name stdout
    match metrics
```

* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: 
* Operating System and version: Debian 11.6
* Filters and plugins:  prometheus_scrape, stdout

**Additional context**

**Comment by leonardo-albertovich** [comment]
Great, that seems like a simple improvement, would you like to give it a shot with some guidance or would you rather wait for someone else to take care of it? If you are interested in sending a PR feel free to contact me if you need guidance or help, I'd be glad to assist you.

Thanks for pointing out the issue!

**Comment by sklgromek** [comment]
Thanks @leonardo-albertovich, I made a draft PR, could you please take a look https://github.com/fluent/fluent-bit/pull/7040

**Comment by leonardo-albertovich** [comment]
I have already reviewed it and I'll merge it as soon as CI finishes, thanks a lot for the contribution!

**Comment by patrick-stephens** [comment]
Note this was completed but no docs PR was done for it so it only shows in the help output:

```shell
$ docker run --rm -it fluent/fluent-bit -i prometheus_scrape --help
...
buffer_max_size                
                               > default: 10M, type: size
```
