### ISSUE TITLE
Grep filter only respects the first Match.

### ISSUE THREAD

**Issue by CatherineF-dev** [fluent/fluent-bit#7035]
## Bug Report

**Describe the bug**
When multiple Match are defined in grep, only the first one will be used.
https://github.com/fluent/fluent-bit/blob/v2.0.10/plugins/filter_grep/grep.c#L175
[
](https://github.com/fluent/fluent-bit/blob/v2.0.10/plugins/filter_grep/grep.c#L175)

```
        [FILTER]
            Name           grep
            Match_Regex    *
            Regex          k1 v1
            Regex          k2 v2
            Regex          k3 v3
```
**To Reproduce**

**Expected behavior**

All Regexes should be used.

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by RicardoAAD** [comment]
Hello @CatherineF-dev 

You can try this workaround while [PR 6721](https://github.com/fluent/fluent-bit/pull/6721) is merged:
You should add one grep filter for each condition you need to achieve logical AND with the regexes.

```
[INPUT]
    Name dummy
    Dummy {"k1":"v1","k2":"v2","k3":"v3","k4":"v4"}
[FILTER]
    Name grep
    Match *
    Regex k2 v2
[FILTER]
    Name grep
    Match *
    Regex k1 v1
[FILTER]
    Name grep
    Match *
    Regex k3 v3
[OUTPUT]
    Name stdout
    Match *
```

Please let us know if this works for you.

Regards,
Ricardo

**Comment by CatherineF-dev** [comment]
Want to have logical OR with the regexes.
