### ISSUE TITLE
fluent bit crash after a while

### ISSUE THREAD

**Issue by juanmolle** [fluent/fluent-bit#7036]
## Bug Report

**Describe the bug**
After running for some time the process crash, this is happening with the amd64 build running on a M1 Mac

**To Reproduce**
After some time running with 2.0.9
/usr/local/bin/fluent-bit -c /<PATH>/fluent/main.conf -w /tmp

this issue is only observed in an emulated environment on M1

```
#0  0x40006862f0        in  mpack_load_u8() at lib/mpack-amalgamation-1.1/src/mpack/mpack.h:2689
#1  0x400068cd53        in  mpack_parse_tag() at lib/mpack-amalgamation-1.1/src/mpack/mpack.c:3297
#2  0x400068d895        in  mpack_read_tag() at lib/mpack-amalgamation-1.1/src/mpack/mpack.c:3654
#3  0x400068d956        in  mpack_discard() at lib/mpack-amalgamation-1.1/src/mpack/mpack.c:3703
#4  0x400017f7f1        in  flb_mp_count_remaining() at src/flb_mp.c:54
#5  0x400017f795        in  flb_mp_count() at src/flb_mp.c:39
#6  0x40000b06d3        in  flb_pack_msgpack_to_json_format() at src/flb_pack.c:927
#7  0x40003ccbcc        in  compose_payload() at plugins/out_http/http.c:390
#8  0x40003cd688        in  cb_http_flush() at plugins/out_http/http.c:584
#9  0x40000d63ec        in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:528
#10 0x400094acc6        in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#11 0xffffffffffffffff  in  ???() at ???:0
qemu: uncaught target signal 6 (Aborted) - core dumped
```
- Steps to reproduce the problem:

**Your Environment**
* Version used: 1.8.0  to 2.0.9
* Configuration:
* Environment name and version running on a linux ubuntu x86_64 docker image using docker desktop on a Mac M1
* Server type and version:
* Operating System and version: Mac M1 Ventura 13.2.1
* Filters and plugins:

**Comment by leonardo-albertovich** [comment]
Could you please share your configuration file and any instructions needed to reproduce the issue?

**Comment by Shobu12** [comment]
I am getting same error for below setting

**Comment by FeiYing9** [comment]
I have the same problem，， have no idea how to deal it
