### ISSUE TITLE
S3 output appended random letters to folder names since v2.0.9

### ISSUE THREAD

**Issue by siulunlee** [fluent/fluent-bit#7045]
## Bug Report

**Describe the bug**
S3 output appended random letters to folder names if S3 folder exist since v2.0.9. The folder name is defined by TAG.
v2.0.8 has no problem.

**To Reproduce**
Configure S3 Output with folder name defined by two consecutive tags. During upload, if the folder name exist, the folder name will be appended by 2 or 3 random letters. For example, below will create "/myfolder/alpha/betaXX/..." folder instead of saving files into existing folder "/myfolder/alpha/beta/..."
```
[INPUT]
    Name tail
    Path /var/log/xxx.log
    Tag alpha/beta

[OUTPUT]
    Name s3
    Match *
    bucket mybucket
    region eu-west-1
    s3_key_format   /myfolder/$TAG[0]/$TAG[1]/%Y/%m/%d/%H/%M
    total_file_size 1M
    s3_key_format_tag_delimiters /
    upload_timeout 1m
    use_put_object True
    compression gzip
```

**Expected behavior**
The folder name will not have random letters appended.

**Your Environment**

* Version used: v2.0.9 and v2.0.10
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Standalone server
* Server type and version: Standalone server
* Operating System and version: Rocky Linux 8
* Filters and plugins: N/A

**Additional context**
This behaviour looks similar to static_file_path config option. Prior to v2.0.9, the static_file_path appends to filename only; since v2.0.9, the TAG folder name is affected.
Once restarted fluent-bit, the log files will split into another high-level folder, which is not desirable.

**Comment by leonardo-albertovich** [comment]
@siulunlee I noticed that you mentioned you tested both 2.0.9 and 2.0.10 but I wanted to double check to be sure you are positive about 2.0.10 being affected, could you confirm that?

@PettitWesley If the user correctly tested this in 2.0.10 this could be related to an error in the tag patch.

**Comment by siulunlee** [comment]
Sorry that I incorrectly described the version tested. It is confirmed that 2.0.9 has the random letters issue.
I did not test this happen or not in 2.0.10 (because I found some issue similar to #6981 in 2.0.10 and I need further testing, and fallback to 2.0.9 and found this issue)
