### ISSUE TITLE
Fluent Bit v2.1 release date

### ISSUE THREAD

**Issue by emadmohammedelbieh** [fluent/fluent-bit#7046]
Hello,

My name is Emad Elbieh, I work for IBM in the Open Source Support department, we work as partner for FluentBit for our clients and we do provide technical support and advises.

There is a client asks us this question:
The selective control on certain metric types features for both Linux and Windows were developed by the community and will be ready in Fluent Bit v2.1.x.
https://github.com/fluent/fluent-bit/pull/6737
https://github.com/fluent/fluent-bit/pull/6766
As far as we can tell there is no release date yet for the enclosed , we need to apply this to thousands of SAN connected servers and the scheduling cannot be implemented without a release date

IBM Case ID:
TS012435500

So may I know what is roughly the release date for Fluent Bit v2.1 ? and what new features it will have?

**Comment by edsiper** [comment]
The current ETA is April 16th. Note that if anything needs more time than expected, the date might be extended.

**Comment by emadmohammedelbieh** [comment]
Thanks for the feedback
