### ISSUE TITLE
kafka sasl auth

### ISSUE THREAD

**Issue by turbotankist** [fluent/fluent-bit#706]
We need to able connect to kafka with sasl plain auth.

librdkafka-0.11.4 has already sasl mechanism but kafka_out hasn't

**Comment by edsiper** [comment]
hi @turbotankist 

Our out_kafka plugin uses librdkafka behind the scenes. From a configuration perspective you can use any rdkafka configuration parameter listed here:

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

The only change to configure the parameter is to add the prefix _rdkafka._, e.g:

if you can to enable the configuration security.protocol from rdkafka, in Fluent Bit you use rdkafka.security.protocol

**Comment by turbotankist** [comment]
Thx @edsiper 
Do I just need to add parameters as this ?
```
[OUTPUT]
***
rdkafka.sasl.username <USERNAME> 
***

```
That's all?

**Comment by edsiper** [comment]
all rdkafka configuration required to perform sasl auth (and encryption)

**Comment by turbotankist** [comment]
I had rebuilt docker-image from your official dockerfile with added apt-get install -y libsasl2-dev befor cmake
And now it's working! thanks
