### ISSUE TITLE
"Modify" condition not work with bool value in message?

### ISSUE THREAD

**Issue by Garved** [fluent/fluent-bit#7075]
### Discussed in https://github.com/fluent/fluent-bit/discussions/7065

<div type='discussions-op-text'>

<sup>Originally posted by **Garved** March 24, 2023</sup>
I try to use a fluent-bit filter "modify" with condition "Key_value_matches" 
In docs, this filter are use how: Key_value_matches | STRING:KEY | REGEXP:VALUE | Is true if key KEY exists and its value matches VALUE .
But, in my message, VALUE type is boolean and the filter cannot find a match in the message.
Is it possible to use "MODIFIY" filter with a boolean value type in the "Key_Value_Match" condition?

</div>

**Comment by Garved** [comment]
I'm sorry, but my problem is not the meaning of "KEY". Conditions is checked by "VALUE", and it is not "STRING" or "INTEGER" - it is "boolean". I was trying to build a filter so that the VALUE would be recognized, but failed.
If I need to check the "KEY" containing the "boolean" type, is it possible to take it into account in the future?

**Comment by raghibomar786** [comment]
HI @Garved , I see that you're adding to TAG. I'm trying to use the TAG value in my output path like:

I've several modules deployed in my kubernetes cluster and I use fluentBit to read logs for all modules from /var/log/containers folder and write them to a file on a persistent volume. I'm able to successfully write all log files to a single folder in my output path. Now, I want to write the logs of each module in a separate subfolder in my output path named as deployment/release name of each module. The log file is named in the following format pod-name_namespace-name_deployment-name (i.e, each of the name is separated by an underscore _). How do I extract this information from my log file name and use it in the output path in FluentBit configuration?

My current configuration looks like this:

    [SERVICE]
        Flush 1
        Log_Level info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines Off
        Read_from_Head true
        Inotify_Watcher false

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        Labels Off
        Annotations Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name file
        Match kube.*
        Path /output/path
        Mkdir True
And this makes my tag value of the form kube.var.log.containers.pod-name_namespace-name_chart-name, I want to do something like:

[OUTPUT]
        Name file
        Match kube.*
        Path /output/path/${TAG[0]}/${TAG[1]}.log
        Mkdir True
```
But I keep getting [warn] [env] variable ${TAG} is used but not set. How do we correctly use this TAG? (not directly related to your question, but I'm stuck on this for several days and would really appreciate some help)

**Comment by patrick-stephens** [comment]
> variable ${TAG} is used but not set

I think the error is pretty clear there: you are specifying to use a variable called `TAG` but have not set it, it's the same as using any variable. The `${NAME}` syntax means to use a variable.

I think what you wanted was to use the tag of the record via the record accessor syntax?
- https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

You'll notice in the various examples there are no curly braces, e.g. https://docs.fluentbit.io/manual/pipeline/outputs/s3#s3-key-format-and-tag-delimiters, $TAG.

Now, record accessor syntax may not be available for every option on every plugin I'm afraid so I've no idea if you can use it with the `file` plugin path but you can test.

**Comment by raghibomar786** [comment]
Thanks @patrick-stephens for the response. Yes, I want to use the Tag and No, file output plugin doesn't support record accessor syntax (just tested). Any other workaround you can suggest for dynamically creating an output path for each deployment name? [Issue](https://github.com/fluent/fluent-bit/discussions/7107)

**Comment by patrick-stephens** [comment]
Rewrite tag is what I used previously to handle paths into tail - you can use the tag as the path for output so if you set up your tag correctly then that should work, rather than try to extract bits of the tag just make it what you want. However your use case is probably a bit more complex than my test one.

Anyway, it's not really related to this issue so we should probably discuss in Slack or a separate issue.

**Comment by raghibomar786** [comment]
Makes sense, I'll try that out and post it on the correct [issues](https://github.com/fluent/fluent-bit/discussions/7107). Appreciate your help, thanks a ton!

**Comment by Garved** [comment]
Hello, @raghibomar786 
I'm sorry for my absence and long reply. 
An additional "TAG" is used in the message body as a "key" for further output.
My main problem is the missing definition of "boolean" in the key:value pair of the "modify filter". To then add additional "key:value" to the message as "TAG:Log" of my message from the monitoring application.
If it is possible to add the use in conditions by the value of the "boolean" type, many colleagues who have encountered such a problem will be grateful.
