### ISSUE TITLE
Add Amazon Linux 2023 Support

### ISSUE THREAD

**Issue by dededecline** [fluent/fluent-bit#7077]
**Is your feature request related to a problem? Please describe.**
Currently, AL2023 is not supported.

**Describe the solution you'd like**
A path to install and run fluent-bit on Amazon Linux 2023

**Describe alternatives you've considered**
I've attempted to get the AL2 and AL2022 versions of fluent-bit working on AL2023.

**Additional context**
AL2023 is now GA and considered the default Amazon Linux version. It would be useful to have fluent-bit releases that are compatible with AL2023.

**Comment by patrick-stephens** [comment]
The builds are all containerised for this here: https://github.com/fluent/fluent-bit/blob/master/packaging/distros/amazonlinux/Dockerfile
Likely we just need to provide a target Dockerfile for it along the lines of the AL2022 one and then the `packaging/build.sh -d amazonlinux/2023` call should build it.

Note that there is an issue with the ARM builds for AL2022 - they take far too long for some reason specific to that target so had to be disabled.

Is AL2023 what AL2022 should have been so should we remove AL2022?

**Comment by patrick-stephens** [comment]
It appears yes, AL2022 just redirects to AL2023 now: https://github.com/amazonlinux/amazon-linux-2022

In which case this is a general transition from AL2022 to AL2023 then rather than support both.

**Comment by patrick-stephens** [comment]
Also, it is only GA for two weeks: https://github.com/amazonlinux/amazon-linux-2023/discussions/131#discussioncomment-5326462
Plus the recommendation is to start with 2023 base image: https://github.com/amazonlinux/amazon-linux-2023/issues/280

**Comment by dededecline** [comment]
> Also, it is only GA for two weeks: https://github.com/amazonlinux/amazon-linux-2023/discussions/131#discussioncomment-5326462

Yep, definitely not saying it's a long-overdue release for fluent-bit but certainly worthwhile now. Thanks for opening a PR for the AL2022 --> AL2023 migration!

**Comment by patrick-stephens** [comment]
Just to be clear the changes are merged but we won't get any packages until the next release.
