### ISSUE TITLE
Automatic index template and data stream creation for OpenSearch 

### ISSUE THREAD

**Issue by adiforluls** [fluent/fluent-bit#7079]
**Is your feature request related to a problem? Please describe.**

Fluentd OpenSearch plugin supports automatic creation of data streams and index templates https://github.com/fluent/fluent-plugin-opensearch#configuration---opensearch-output-data-stream and https://github.com/fluent/fluent-plugin-opensearch#template_file
I think that it'd be a good idea to have this in fluentbit OpenSearch output plugin as well. FluentBit being the logging agent that sends data to an output, will be able to send data to new indexes and data streams with predefined mappings/settings.

**Describe the solution you'd like**

An equivalent to what fluentd plugin has for index template and data stream creation:
- Be able to write to a data stream
- Be able to specify a template_file or an equivalent
- Be able to specify data_stream_name and data_stream_template_name or an equivalent

**Describe alternatives you've considered**

**Additional context**

**Comment by adiforluls** [comment]
@edsiper what do you think?
I can look to make a contribution

**Comment by adiforluls** [comment]
cc: @patrick-stephens @lecaros what do you think? This is going to be a feature enhancement, and it's an important one from opensearch's perspective. See https://opensearch.org/docs/2.6/im-plugin/data-streams/

I'm happy to make a contribution if you guys think it's a good idea

**Comment by patrick-stephens** [comment]
Sure, I'd say raise a PR for review is the best way - it's all OSS so go ahead, you don't need permission :)

**Comment by adiforluls** [comment]
re-open
