### ISSUE TITLE
Support gzip compression in out_stackdriver plugin

### ISSUE THREAD

**Issue by CatherineF-dev** [fluent/fluent-bit#7089]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

When sending logs into google cloud logging, use gzip compression.

**Describe alternatives you've considered**

**Additional context**

Haven't found a flag in stackdriver output to enable gzip compression. https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver

**Comment by leonardo-albertovich** [comment]
As far as I can see there is no code to back that feature in the plugin, could you please create a PR to add it?

**Comment by CatherineF-dev** [comment]
https://github.com/fluent/fluent-bit/pull/7101
