### ISSUE TITLE
Support Dynamic Kafka Topic with Topic_key derived from the namespace annotations

### ISSUE THREAD

**Issue by nareshku** [fluent/fluent-bit#7090]
**Is your feature request related to a problem? Please describe.**

We have a lot of namespaces that contain a ton of pods and we would like to create an isolation for the Pod logs as we are facing scaling issues. In other words, pod logs belonging to an NS will be forwarded to a defined Kafka topic created for that NS.

**Describe the solution you'd like**

We would like to see an option that allows fluent-bit to retrieve Kafka Topic names based on the Namespace annotations. This way we can avoid adding an output configuration for every namespace as that will be too much to maintain.

Now with this feature, we can easily inject the `Topic_key` into the log stream using a Kubernetes Filter (Hoping this is where the feature will be added). If needed, create a lua script to rename the Topic annotation field into Topic_Key and send it to the Output for processing.

**Describe alternatives you've considered**

Figure out a way to get the annotation in a Lua script and add it to the log stream. However, this feels expensive.

**Additional context**

**Comment by patrick-stephens** [comment]
I think this is two separate features, there is a related request around extending the K8S filter to handle namespace annotations I believe somewhere. Once we have that then this would be record accessor syntax support for the topic key then (if not already supported).

However, you could quite easily also use the DownwardAPI to inject the namespace of the pod in as an environment variable and then use that variable directly in your config too.
- https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

If using the example in the K8S docs then something like:
```
[OUTPUT]
    Name        kafka
    Match       *
    Topics      ${MY_POD_NAMESPACE}
```

**Comment by nareshku** [comment]
@patrick-stephens Thanks for the reply.
Regarding the alternate method of using the env variable. How does this work when the Topic_key is defined as an annotation in the namespace? I believe this requires us to propagate the namespace annotation to all the Pods (also, this creates an overhead as we need to now inject an env var somehow for all the workloads).

Essentially what we are looking for is.
```
[OUTPUT]
    Name        kafka
    Match       *
    Topics      ${MY_POD_NAMESPACE.METADATA.ANNOTATIONS.FLUENT_BIT_TOPIC_KEY}
```

Also, it would be great if you could point to me the existing feature request for the first half.

**Comment by patrick-stephens** [comment]
Sure, I appreciate it requires pod spec updates (that could be handled via an admission controller or some other mechanism of course). I was just trying to suggest a workaround.

Apologies I meant to search the issues for the namespace annotation one...
