### ISSUE TITLE
Tail path wildcards do not work in windows

### ISSUE THREAD

**Issue by i12batree** [fluent/fluent-bit#7095]
## Bug Report

**Describe the bug**

When using tail on windows, log files are read fine if you define the path explicitly. However as soon as you add a wildcard, no files are detected.

**To Reproduce**

i have an app writing constantly to the file C:/temp/Log2023033112.txt
I expect you could manually reproduce just by adding lines to this file using a text editor and saving.

i start fluent bit with the command

fluent-bit.exe -c ../conf/fluent-bit.conf

configuration file is as follows:

<-  default from installation above this point apart from changing log level to debug
[INPUT]
Name tail
Path C:/temp/Log2023033112.txt
DB C:/temp/fluent.db
Tag Test

[OUTPUT]
name stdout
match *

this works as expected

[2023/03/31 12:08:30] [debug] [input:tail:tail.0] 1 new files found on path 'C:/temp/Log2023033112.txt'
[2023/03/31 12:08:30] [debug] [stdout:stdout.0] created event channels: read=864 write=868
[2023/03/31 12:08:30] [ info] [sp] stream processor started
[2023/03/31 12:08:30] [ info] [output:stdout:stdout.0] worker #0 started
[2023/03/31 12:08:30] [debug] [input:tail:tail.0] inode=165788761282763180 file=C:\temp\Log2023033112.txt promote to TAIL_EVENT

....
then the log contents output continuously, tail works fine

BUT, if you change to the following and restart:

[INPUT]
Name tail
Path C:/temp/Log*.txt
DB C:/temp/fluent.db
Tag Test

you just get
2023/03/31 12:40:50] [debug] [input:tail:tail.0] 0 new files found on path 'C:/temp/Log*.txt'

i aslo tried the following patterns:

Log[1-9][1-9][1-9][1-9][1-9][1-9][1-9][1-9][1-9][1-9].txt
Log??????????.txt

these also fail

**Expected behavior**

I expect it to find all files matching the wildcard pattern and tail them

**Your Environment**

windows 10

fulent-bit 2.0.9 windows 64

**Additional context**

This means I cannot use fluent bit as it cannot tail logs...

Many thanks

**Comment by igorpeshansky** [comment]
You *have* to use backslashes with wildcard paths on Windows:
```
[INPUT]
Name tail
Path C:\temp\Log*.txt
DB C:/temp/fluent.db
Tag Test
```
Other paths can use either backslashes or forward slashes.

**Comment by patrick-stephens** [comment]
Probably should be made clearer in the docs I think, feels like the usual "paths are weird on windows" problem :)

**Comment by i12batree** [comment]
Hi,

Thanks for the reply.
This did not occur to me to try as I'm sure that the documentation
explicitly stated that you cant use backslashes with wildcards.
