### ISSUE TITLE
New ASYNC net.dns.resolver fails with getaddrinfo(err=12): Timeout while contacting DNS servers with Elasticsearch shipper

### ISSUE THREAD

**Issue by gavenkoa** [fluent/fluent-bit#7105]
Reproduced in v1.8.11 & 1.9.7 with Elasticsearch plugin & `net.dns.resolver ASYNC`:

```
[ warn] [net] getaddrinfo(host='evil.com', err=12): Timeout while contacting DNS servers
```

```
[OUTPUT]
    # https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
    Name            es
    Match           app
    Host            ${es_host}
    Port            9200
    HTTP_User       ${es_user}
    HTTP_Passwd     ${es_pass}
    Retry_Limit     False

    Logstash_Format  On
    Logstash_Prefix  app
    Logstash_DateFormat %Y-%m-%d
    Current_Time_Index Off

    Include_Tag_Key Off
    Generate_ID     Off
    Trace_Output    On
    Trace_Error     On

    tls on
    tls.verify off

    # TCP or UDP
    net.dns.mode UDP
    # true / false
    # net.dns.prefer_ipv4 true
    # LEGACY or ASYNC
    net.dns.resolver ASYNC
```

Changing `net.dns.resolver` to `LEGACY` resolved the problem in both versions. `net.dns.resolver` is documented only in v1.9:

https://docs.fluentbit.io/manual/v/1.9-pre/administration/networking

Similar reports:

* https://github.com/fluent/fluent-bit/issues/4050
*  https://github.com/fluent/fluent-bit/issues/4260
* https://github.com/aws/aws-for-fluent-bit/issues/233
* https://github.com/aws/aws-for-fluent-bit/issues/253

**Comment by gavenkoa** [comment]
OS Windows Server 2012 R2, 64bit. With `net.dns.mode TCP` fails as corporate environment forbids it.

**Comment by patrick-stephens** [comment]
Do you know if the 2.0.10 releases work correctly?
There will be no further official 1.8 or 1.9 releases hence the query to see if it is an issue we need to resolve for the 2.0 and upcoming 2.1 series.

**Comment by wtchangdm** [comment]
I have the same problem and saw this on both 2.0.10, 2.0.11 and 2.1.0. I am using the `loki` output though.

Some info:

1. Haven't explicitly set anything for `net.dns.resolver`.
2. We are running daemonsets (with 2.0.11) on a EKS cluster.
3. The cluster has NodeLocal DNSCache. The DNS resolution time shouldn't be an issue.

```bash
[2023/04/19 05:15:00] [ warn] [net] getaddrinfo(host='<REDACTED>.', err=12): Timeout while contacting DNS servers
[2023/04/19 05:15:00] [error] [output:loki:loki.0] no upstream connections available
[2023/04/19 05:15:00] [ warn] [net] getaddrinfo(host='<REDACTED>.', err=12): Timeout while contacting DNS servers
[2023/04/19 05:15:00] [error] [output:loki:loki.0] no upstream connections available
[2023/04/19 05:15:00] [error] [upstream] connection #-1 to tcp://unavailable:0 timed out after 10 seconds (connection timeout)
...
```

Also, the CPU spikes when DNS resolution issues occurs.

![img](https://i.imgur.com/wzM5FM2.png)

The output looks like the following:

```
[Output]
        Name loki
        Match *
        host    <REDACTED>
        port    443
        tls     On
        workers 1
        labels service=$kube_namesapce
```

Will try `net.dns.resolver LEGACY` and report here if it helps.

**Comment by wtchangdm** [comment]
Almost 24 hours later, the DNS error seems gone after setting `net.dns.resolver` to `LEGACY` with Version 2.1.0.

**Comment by terencebor** [comment]
I'm having the same issue. We upgraded Fluent-bit from v2.0.9 to v3.0.0. After that Fluent-bit starts, works for 20-30 minutes, then it stops sending data to Opensearch, and I see next logs:
[ warn] [net] getaddrinfo(host='opensearch-cluster-master.logging.svc.cluster.local', err=12): Timeout while contacting DNS servers
[error] [upstream] connection #102 to tcp://192.24.40.158:9200 timed out after 10 seconds (connection timeout)
[error] [upstream] connection #-1 to tcp://unavailable:0 timed out after 10 seconds (connection timeout)

**Comment by naegelin** [comment]
I realize this issue is closed. I just wanted to update incase anyone running 3.1 comes across the same issue. We experienced this same issue on fluentbit 3.1 using the HTTP output plugin. Setting `net.dns.resolver LEGACY` worked for us - no more `Timeout while contacting DNS servers` error

**Comment by privx-de** [comment]
We also had `Timeout while contacting DNS servers` with our Gelf setup. A switch to `net.dns.resolver LEGACY` has solved the issue. Fluentbit version: 3.1.7
