### ISSUE TITLE
FluentBit 1.9 parse log file by namespace

### ISSUE THREAD

**Issue by milank78git** [fluent/fluent-bit#7108]
Hi,

I would like to split messages from different namespaces into correct kafka topics according to the namespace Topics will always be named the same as the namespace
namespace are 01234 and 02356 and 04646 ... etc
topic name are 01234 and 02356 and 04646 ... etc

    [INPUT]
        Name         tail
        Path         /var/log/containers/*_0[0-9]{4}*.log
        Tag          kube.*
        Multiline    On
        Parser       cri
        DB           /var/log/flb-storage/offset-apps.db
        Mem_Buf_Limit 50MB
        Skip_Long_Lines Off
        Rotate_Wait  15
        Refresh_Interval 1
        Buffer_Chunk_Size 2k

  [FILTER]
      Name modify
      Match *
     Add namespace ${tag_parts[3]}

    [OUTPUT]
        Name                                         kafka
        Match_Regex                             ${namespace}.*
        Brokers                                      ${KAFKA_HOST}
        Topics                                       ${filename}
        Topic_Key                                    topic

But this is wrong Filter modify 
Please help. How filter by namespace and send  message

**Comment by patrick-stephens** [comment]
Can you use the record access syntax to do this with the kubernetes filter?

**Comment by milank78git** [comment]
@patrick-stephens  
I don't know what you mean.
This is the contents of the log from fluentbit /var/log/container/...
`2023-04-13T09:38:55.759617122+02:00 stderr F {"level":"info","ts":1681371535.759455,"logger":"camel-k.cmd","msg":"maxprocs: Updating GOMAXPROCS=[1]: determined from CPU quota"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"info","ts":1681371535.7596042,"logger":"camel-k.cmd","msg":"Go Version: go1.18.10"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"info","ts":1681371535.7596326,"logger":"camel-k.cmd","msg":"Go OS/Arch: linux/amd64"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"info","ts":1681371535.759643,"logger":"camel-k.cmd","msg":"Camel K Operator Version: 1.12.0"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"info","ts":1681371535.759656,"logger":"camel-k.cmd","msg":"Camel K Default Runtime Version: 1.17.0"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"info","ts":1681371535.7596605,"logger":"camel-k.cmd","msg":"Camel K Git Commit: a62a06f7261436641850abcb1b2e01afafd4be3d"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"info","ts":1681371535.7596722,"logger":"camel-k.cmd","msg":"Camel K Operator ID: camel-k"}
2023-04-13T09:38:55.759762973+02:00 stderr F {"level":"debug","ts":1681371535.7596796,"logger":"camel-k.cmd","msg":"*** DEBUG level messages will be logged ***"}
2023-04-13T09:38:56.043127085+02:00 stderr F {"level":"info","ts":1681371536.0430243,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
2023-04-13T09:38:56.049341589+02:00 stderr F {"level":"info","ts":1681371536.049--More-- `

**Comment by patrick-stephens** [comment]
If you use the kubernetes filter it will add the metadata for you including the namespace directly into the record: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes
Record accessor syntax then is this but I'm not sure if it is supported for kafka output: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

Otherwise a LUA filter can probably chop up the tag for you: https://docs.fluentbit.io/manual/pipeline/filters/lua

**Comment by milank78git** [comment]
@patrick-stephens  Thanks but I try configuration 
[INPUT]
    Name              tail
    Path              /var/log/containers/*.log
    Tag               kube.*

[FILTER]
    Name              kubernetes
    Match             kube.*
    Kube_Tag_Prefix   kube.var.log.containers.

[FILTER]
    Name              lua
    Match             kube.*
    script            |
        function emit(tag, timestamp, record)
            local namespace = record["kubernetes"]["namespace_name"]
            local topic = "namespace-" .. namespace
            record["topic"] = topic
            return 2, timestamp, record
        end

[OUTPUT]
    Name              kafka
    Match             kube.*
    brokers           kafka:9002
    topic             namespace-${record["kubernetes"]["namespace_name"]}
    output_format     json

Don't load the topic name

**Comment by patrick-stephens** [comment]
As I say, I'm not sure if the Kafka output supports it either at all or for the specific setting you need.
Multiline (your lua script) is not supported in legacy config mode either so I suspect your configuration is failing anyway.
Plus this `${record["kubernetes"]["namespace_name"]}`is not record accessor syntax - curly braces indicate variables so check the docs: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

What is the FB log showing?

Now, your LUA script sets up a `topic` key but you do not actually use it - why don't you just use that as per the docs?
https://docs.fluentbit.io/manual/pipeline/outputs/kafka

If your LUA filter is correctly configured then you can just use the `topic` key in the record like so I think:
```
[OUTPUT]
Name kafka
Match kube.*
brokers kafka:9002
topic_key topic
output_format json
```
