### ISSUE TITLE
Record Accessor not available in file output plugin

### ISSUE THREAD

**Issue by raghibomar786** [fluent/fluent-bit#7109]
**Is your feature request related to a problem? Please describe.**
I have multiple modules/services running in kubernetes. I use flunetBit to aggregate logs from /var/log/containers folder, append kubernetes metadata to them and then store them onto a file (connected to a persistent volume). I have a hard requirement to put the log file for each module in a separate subdirectory (currently, I get all these files in a single repo), with each subdirectory being created dynamically by the "deployment/release name". I have this information in kubernetes metadata, but I cannot access it in the file output plugin to define the path.

**Describe the solution you'd like**
If I can use record accessor in the file output plugin, then a config like:
```
[OUTPUT]
        Name file
        Match kube.*
        Path /output/path/$kubernetes["deployment_name"]/
        Mkdir True
```
would solve the issue. 
Fluentd supports usage of $tag as well as record accessor in file output but none of this is available in fluentBit.

**Describe alternatives you've considered**
I tried updating Rewrite tag to have the tag value as deployment_name hoping to directly partition the data based on the same, but this creates a separate output file named after the tag for each service but does not create subfolders for each deployment-name. And since new tag can only contain a-z,A-Z, 0-9 and .-, ([ref](https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#new-tag)), I cannot put a '/' in my tag that may create a subdirectory. 

**Additional context**

This is a blocker for a major release we have coming up

**Comment by guptashivam1987** [comment]
We are also having similar requirement but could not find a solution yet

**Comment by sshipway** [comment]
This is a problem for us as well, as we try to move from using rsyslog to using fluent-bit.
With rsyslog, we have logs written to a file structure under `/var/log/syslog/$source/$year/$month/$day/$logtype.log`
Under fluent-bit, we are not able to use these fields in the file output stanza.
You can tweak a bit using tags (which DO allow a / even though the doc says not) but then field names must be terminated by one of '-.' or EOL.

**Comment by nasioman** [comment]
We are having the same problem
