### ISSUE TITLE
JSON parser doesn't correctly parse most variations of floating-point numbers with an exponent

### ISSUE THREAD

**Issue by giuliano-sider** [fluent/fluent-bit#7113]
## Bug Report

**Describe the bug**
In the ECMA-404 standard for the syntax of floating-point numbers in JSON (https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf), there are 6 variations of exponent suffixes for a float:
1. e<one or more digits>
2. e+<one or more digits>
3. e-<one or more digits>
4. E<one or more digits>
5. E+<one or more digits>
6. E-<one or more digits>

It looks like only 3 is correctly parsed by fluent-bit's JSON parser. It appears case 3 was fixed by https://github.com/fluent/fluent-bit/issues/2746, but the others weren't.

**To Reproduce**
- Example log message
```
{"num1": 1e2, "num2": 1e+2, "num3": 1e-2, "num4": 1E2, "num5": 1E+2, "num6": 1E-2}
```
- Steps to reproduce the problem:
Create the following config with a dummy input plugin having an example JSON and name it `experiment_float_parsing.conf`:
```
[SERVICE]
    Flush             5
    Grace            10
    Log_Level     debug
    Log_File        /fluentbit.log
    Daemon        off

[INPUT]
    Name            dummy
    Tag                dummy.log
    Dummy         {"num1": 1e2, "num2": 1e+2, "num3": 1e-2, "num4": 1E2, "num5": 1E+2, "num6": 1E-2}

[OUTPUT]
    Name        stdout
    Match       *
```
Run the following shell script in the same directory:
```
#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

FLUENT_BIT_IMAGE="fluent/fluent-bit:2.0.10"

SCRIPT_PATH="$(dirname "$(realpath "$0")")"
cd "${SCRIPT_PATH}"

CONFIG_FILE="$(realpath experiment_float_parsing.conf)"

mkdir -p test_output/
FLUENT_BIT_LOG_FILE="$(realpath test_output/)/fluentbit-$(date +%s.%N).log"
touch "$FLUENT_BIT_LOG_FILE"


docker run --name fluentbit-experiment \
	-it \
	--rm \
	-v "${CONFIG_FILE}":/experiment_float_parsing.conf \
	-v "${FLUENT_BIT_LOG_FILE}":/fluentbit.log \
	"${FLUENT_BIT_IMAGE}" \
	/fluent-bit/bin/fluent-bit \
		-c /experiment_float_parsing.conf
```
**Expected behavior**
I expected to see some records like
```
[0] dummy.log: [1680578106.694134251, {"num1"=>100.000000, "num2"=>100.000000, "num3"=>0.010000, "num4"=>100.000000, "num5"=>100.000000, "num6"=>0.010000}]
```

Instead, I got
```
[0] dummy.log: [1680578106.694134251, {"num1"=>1, "num2"=>1, "num3"=>0.010000, "num4"=>1, "num5"=>1, "num6"=>1}]
```

It looks fluent-bit's JSON parser doesn't realize that those are floats, and parses them into an integer instead (see https://github.com/fluent/fluent-bit/issues/2746 for why that might be the case).

**Comment by djj0809** [comment]
Can anyone reopen this? It is not fixed and we are hitting this as well

**Comment by shaowan-msft** [comment]
The problem I meet is it can parse 4.60E-05 to 0.000046(which is right behavior), but parse 2.00E-06 to 2.
