### ISSUE TITLE
Unable to read the logs in the console using the tail plugin in windows 

### ISSUE THREAD

**Issue by rajatsharma4318** [fluent/fluent-bit#7115]
I'm facing issue to read the log file using the tail plugin in windows.  
I have used this plugin `[](url)`
`[SERVICE]
    Flush         1
    Log_Level     debug
    Daemon        off
[INPUT]
    Name                     tail
    Path                       D:/OpenSearch/log/server.log
    Mem_Buf_Limit     100MB
    Skip_Long_Lines    Off
    Refresh_Interval     10
    Buffer_Max_Size     90MB

[OUTPUT] 
    Name          stdout
    Match         *
`

file size is 3MB(server.log) but even I tried with the 1kb file also but can't see the logs in the console

can someone help me to to resolve the issue.
![Screenshot (41)](https://user-images.githubusercontent.com/68428798/229718294-93c8c8fb-8ec0-4ced-a66a-39703187acea.png)

**Comment by patrick-stephens** [comment]
Remember tail by default acts as `tail -f` so only sees new data added since the file was opened: <https://docs.fluentbit.io/manual/pipeline/inputs/tail>

If you use `read_from_head on` then this will get existing data in the file.

**Comment by rajatsharma4318** [comment]
@patrick-stephens  I tried to add this property but getting error.
	**Read_from_Head    true**
invalid indentation level
[error] configuration file contains errors, aborting.

**Comment by rajatsharma4318** [comment]
@patrick-stephens Yes..it works , thank you

**Comment by patrick-stephens** [comment]
You should have a look at the docs really to figure out what you want to do, that setting is not recommended as you'll get duplicate logs each time you restart - it will re-read from the start of the log file each time. This may be what you want but I would recommend looking at the configuration (e.g. the `DB` setting) to figure out your use case.
