### ISSUE TITLE
CMake config to disable all plugins

### ISSUE THREAD

**Issue by braydonk** [fluent/fluent-bit#7126]
**Is your feature request related to a problem? Please describe.**
We use fluent-bit in a very particular way, with only 10 or so plugins being necessary. To only build the plugins we need, we'd need to provide a very large set of flags to disable a lot of plugins that are set to `Yes` by default.

**Describe the solution you'd like**
It would be great to instead provide a CMake variable that will disable all plugins by default, followed by only turning on the plugins we need. This would lead to a lot less CMake flags being passed in a build with limited plugins, and make it obvious from the flags which plugins are explicitly included.

**Describe alternatives you've considered**
The current setup of turning off all the plugins we don't need does work, but it leads to a very large number of flags and makes it less obvious which plugins are included.

**Comment by patrick-stephens** [comment]
CMake presets might be a good idea now: https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
We could have a minimal preset to satisfy this need (all plugins off) and a default one as well, plus other ones.
