### ISSUE TITLE
Fluent bit (deployed by fluent-operator) does not seem to work with systemd v237

### ISSUE THREAD

**Issue by rucciva** [fluent/fluent-bit#7128]
## Bug Report

**Describe the bug**
No log are ingested to fluent-bit when using systemd input on systemd v237

**To Reproduce**
- Deploy fluentbit with fluent-operator on host with systemd v237
- exec into the pod
- run 
    ```
    fluent-bit -i systemd \
             -p systemd_filter=_SYSTEMD_UNIT=docker.service \
             -p tag='host.*' -o stdout
    ```

**Expected behavior**
Log from systemd are ingested to fluent-bit

**Screenshots**
<img width="933" alt="Screen Shot 2023-04-06 at 11 20 59" src="https://user-images.githubusercontent.com/4647473/230272680-9ea64594-c57f-450a-a1ae-8914d2f87c8c.png">
<img width="908" alt="Screen Shot 2023-04-06 at 11 20 35" src="https://user-images.githubusercontent.com/4647473/230273398-b5c6e083-1e82-46a8-abbb-70f29963425b.png">

**Your Environment**

* Version used: 2.0.10 (fluent operator 2.10.0)
* Configuration:
    fluent-bit -i systemd \
             -p systemd_filter=_SYSTEMD_UNIT=docker.service \
             -p tag='host.*' -o stdout
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.23
* Server type and version: 
* Operating System and version: Ubuntu 18.04 
* Filters and plugins: -

**Additional context**

**Comment by rucciva** [comment]
hi @patrick-stephens , thanks for the suggestion, though its still not working.

<img width="872" alt="Screen Shot 2023-04-13 at 13 35 22" src="https://user-images.githubusercontent.com/4647473/231674299-c29da9da-1b0d-45f8-9bc5-9f7be25e30ad.png">

**Comment by patrick-stephens** [comment]
I'm intrigued you have a shell in the distroless production image, I'm guessing you're deploying a different image (debug maybe)?

I suspect some incompatibility somewhere in the systemd libs or the mount. Does journalctl work in the container?

Can you run directly on the host with the Ubuntu package installed using systemd?

**Comment by rucciva** [comment]
> I'm intrigued you have a shell in the distroless production image, I'm guessing you're deploying a different image (debug maybe)?

yes, i switched to debug just to make sure it's not the problem with the output

> I suspect some incompatibility somewhere in the systemd libs or the mount. Does journalctl work in the container?

i don't think the debug image have journalctl , and i'm not quite sure how to install it in the container

> Can you run directly on the host with the Ubuntu package installed using systemd?

yes, fluent-bit successfully grep the journal log 

<img width="1132" alt="Screen Shot 2023-04-13 at 20 48 07" src="https://user-images.githubusercontent.com/4647473/231779183-e76419ec-2ff5-4f9b-a595-71eee3eee63a.png">

**Comment by rucciva** [comment]
hi @patrick-stephens , i think i fixed it, by add /run/log to the fluentbit contianer, i'm not sure why though

**Comment by 0xAl3xH** [comment]
this worked for me but for posterity, I had to remove `-v /var/log/journal:/run/log/journal:ro` and add `-v /run/log/journal:/run/log/journal:ro`

Full working docker invocation you can test with to see if it works:
```
docker run --user root -v /etc/machine-id:/etc/machine-id:ro -v /run/log/journal:/run/log/journal:ro -v /run/systemd/journal:/run/systemd/journal:ro -v /var/run/systemd/journal:/var/systemd/journal:ro -it fluent/fluent-bit:1.8 bash
```
then inside the container shell
```
/fluent-bit/bin/fluent-bit -i systemd -p read_from_tail=On -o stdout -m "*"
```
This just reads your host's systemd messages to stdout as a test.
