### ISSUE TITLE
Unique ID not getting assigned

### ISSUE THREAD

**Issue by Balukn11** [fluent/fluent-bit#7136]
## Bug Report

**Describe the bug**

I'm just trying to assign unique id for each of the network flow logs. While creating the below specified configuration, the fluent-bit service is not starting.

**Expected behavior**

When multiple inputs are flowing, the filter plugin needs to provide a check for unique ID assignment. Which is, when the flow encountered for first time then it needs to assign new id similarly when the previous flow is encountered, the previously assigned ID need to be assigned for that flow.

**Your Environment**

* Configuration:

[INPUT]
    Name               tail
    Path               /var/log/suricata/eve.json
    Tag                suricataeve
    Parser             json
    Threaded           On          
    Mem_Buf_Limit      5MB

[FILTER]
    Name record_modifier
    Match suricataeve
    Record flow_id ${UUID}
    Condition *

[OUTPUT]
    Name               es
    Match              suricataeve
    Host               xx.xxx.xx.xxx
    Port               9200
    Index              evejson

* Operating System and version:
 Ubuntu 22.04

**Additional context**

If this functionality doesn't work, can you suggest some other solutions like creating custom plugins or any such to enable this functionality

**Comment by Balukn11** [comment]
How to set UUID ?

**Comment by patrick-stephens** [comment]
It's an environment variable so set however is appropriate for your target OS.
