### ISSUE TITLE
Unused option throws no warning ...

### ISSUE THREAD

**Issue by sylr** [fluent/fluent-bit#715]
This really sucks to have commented out this and give no warning to the user in the logs ...

https://github.com/fluent/fluent-bit/blob/c8ea0166572ef07fd364b53ac6155b52e8e37340/plugins/filter_kubernetes/kube_conf.c#L104-L117

We spent 3H trying to understand what we were doing wrong.

**Comment by edsiper** [comment]
My apologizes for that, you are right. I will make sure to fix that pending.

**Comment by edsiper** [comment]
@sylr the fixes are already in place for v0.14 release (to be released shortly). Note the option has be renamed to __merge_log_key__.

**Comment by sylr** [comment]
Hi @edsiper we tried to use merge_log_key this morning with the latest docker image but this does not work, the json map still gets merged at the root of the json object.
