### ISSUE TITLE
SIGSEGV with CloudWatch Logs output

### ISSUE THREAD

**Issue by txigreman** [fluent/fluent-bit#7150]
## Bug Report

**Describe the bug**
I'm getting a SIGSEGV while trying to send logs to CloudWatch

**To Reproduce**
- Extract attached file named `fluentbit_sigsegv.zip`
- Configure AWS credentials in file `docker-compose.yml` [Optional]
- Run `docker compose up`

After some seconds a SIGSEGV will appear:
```
[2023/04/08 16:04:31] [engine] caught signal (SIGSEGV)
#0  0x555d360e36cb      in  flb_task_retry_create() at src/flb_task.c:122
#1  0x555d360da6b2      in  handle_output_event() at src/flb_engine.c:343
#2  0x555d360dbc61      in  flb_engine_start() at src/flb_engine.c:986
#3  0x555d36082b24      in  flb_lib_worker() at src/flb_lib.c:629
#4  0x7efc2cdfcea6      in  start_thread() at reate.c:477
#5  0x7efc2c6afa2e      in  ???() at sysv/linux/x86_64/clone.S:95
#6  0xffffffffffffffff  in  ???() at ???:0
```

Full output log is attached in `output.log` file.

[fluentbit_sigsegv.zip](https://github.com/fluent/fluent-bit/files/11185167/fluentbit_sigsegv.zip)
[output.log](https://github.com/fluent/fluent-bit/files/11185168/output.log)

**Your Environment**

* Version used: I've tested it with 2.0-debug, 2-0, 1.9-debug, and 1.9
* Environment name and version: Docker v20.10.23, Docker Compose v2.15.1
* Operating System and version: Windows 11

**Additional context**
If valid AWS credential are configured, with CloudWatchLogs write permissions granted, some unexpected `SerializationException` errors will appear in the log.

**Comment by ypicard** [comment]
I'm seeing the same behavior.
