### ISSUE TITLE
ExecStart=/opt/fluent-bit/bin/fluent-bit -c //etc/fluent-bit/fluent-bit.conf (code=exited, status=255)

### ISSUE THREAD

**Issue by pranavsankar07** [fluent/fluent-bit#7152]
## Bug Report

**Describe the bug**
I'm testing fluentbit grep filter and sending some nginx logs to my output, but after restating the config file post adding the filter condition it throws me an error

**To Reproduce**
[FILTER]
        Name grep
        Match *
        Regex failed

Full log
● fluent-bit.service - Fluent Bit
   Loaded: loaded (/usr/lib/systemd/system/fluent-bit.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2023-04-10 07:38:43 UTC; 13s ago
     Docs: https://docs.fluentbit.io/manual/
  Process: 8359 ExecStart=/opt/fluent-bit/bin/fluent-bit -c //etc/fluent-bit/fluent-bit.conf (code=exited, status=255)
 Main PID: 8359 (code=exited, status=255)
Apr 10 07:38:43 nginx-1 systemd[1]: Unit fluent-bit.service entered failed state.
Apr 10 07:38:43 nginx-1 systemd[1]: fluent-bit.service failed.
Apr 10 07:38:43 nginx-1 systemd[1]: fluent-bit.service holdoff time over, scheduling restart.
Apr 10 07:38:43 nginx-1 systemd[1]: Stopped Fluent Bit.
Apr 10 07:38:43 nginx-1 systemd[1]: start request repeated too quickly for fluent-bit.service
Apr 10 07:38:43 nginx-1 systemd[1]: Failed to start Fluent Bit.
Apr 10 07:38:43 nginx-1 systemd[1]: Unit fluent-bit.service entered failed state.
Apr 10 07:38:43 nginx-1 systemd[1]: fluent-bit.service failed.

**Expected behavior**

Your Environment

Version used: 2.0.11

**Comment by patrick-stephens** [comment]
I think you need to provide the full log - this is just showing the output of systemd which is saying it failed but not why. Use the appropriate tool for your system (you do not indicate what target but probably `journalctl -u fluent-bit`).

I suspect the full log will tell you what is failing, you can also increase `log_level debug` too.

**Comment by pranavsankar07** [comment]
@patrick-stephens Please find the full log
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [fluent bit] version=2.0.11, commit=, pid=4072
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=1
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [cmetrics] version=0.6.0
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [ctraces ] version=0.3.0
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [input:tail:tail.0] initializing
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] [filter:grep:grep.0] invalid regex, expected field and regular expression
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] Failed initialize filter grep.0
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] [engine] filter initialization failed
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] [lib] backend failed
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [ info] [input] pausing tail.0
Apr 13 05:39:29 nginx-1 systemd[1]: fluent-bit.service: main process exited, code=exited, status=255/n/a
Apr 13 05:39:29 nginx-1 systemd[1]: Unit fluent-bit.service entered failed state.
Apr 13 05:39:29 nginx-1 systemd[1]: fluent-bit.service failed.
Apr 13 05:39:30 nginx-1 systemd[1]: fluent-bit.service holdoff time over, scheduling restart.
Apr 13 05:39:30 nginx-1 systemd[1]: Stopped Fluent Bit.
Apr 13 05:39:30 nginx-1 systemd[1]: Started Fluent Bit.
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: Fluent Bit v2.0.11
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: * Copyright (C) 2015-2022 The Fluent Bit Authors
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: * https://fluentbit.io
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [fluent bit] version=2.0.11, commit=, pid=4076
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=1
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [cmetrics] version=0.6.0
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [ctraces ] version=0.3.0
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [input:tail:tail.0] initializing
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [error] [lib] backend failed
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [error] [filter:grep:grep.0] invalid regex, expected field and regular expression
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [error] Failed initialize filter grep.0
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [error] [engine] filter initialization failed
Apr 13 05:39:30 nginx-1 fluent-bit[4076]: [2023/04/13 05:39:30] [ info] [input] pausing tail.0
Apr 13 05:39:30 nginx-1 systemd[1]: fluent-bit.service: main process exited, code=exited, status=255/n/a
Apr 13 05:39:30 nginx-1 systemd[1]: Unit fluent-bit.service entered failed state.
Apr 13 05:39:30 nginx-1 systemd[1]: fluent-bit.service failed.
Apr 13 05:39:30 nginx-1 systemd[1]: fluent-bit.service holdoff time over, scheduling restart.
Apr 13 05:39:30 nginx-1 systemd[1]: Stopped Fluent Bit.
Apr 13 05:39:30 nginx-1 systemd[1]: start request repeated too quickly for fluent-bit.service
Apr 13 05:39:30 nginx-1 systemd[1]: Failed to start Fluent Bit.
Apr 13 05:39:30 nginx-1 systemd[1]: Unit fluent-bit.service entered failed state.
Apr 13 05:39:30 nginx-1 systemd[1]: fluent-bit.service failed.

**Comment by patrick-stephens** [comment]
Yes, so the error is right there:
```
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] [filter:grep:grep.0] invalid regex, expected field and regular expression
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] Failed initialize filter grep.0
Apr 13 05:39:29 nginx-1 fluent-bit[4072]: [2023/04/13 05:39:29] [error] [engine] filter initialization failed
```
