### ISSUE TITLE
No documentation for Unix socket input plugin?

### ISSUE THREAD

**Issue by ccampo133** [fluent/fluent-bit#7153]
## Bug Report

Apparently a Unix socket input plugin exists (https://github.com/fluent/fluent-bit/tree/master/plugins/in_unix_socket), however so far as I can tell, there is no documentation for it (https://docs.fluentbit.io/manual/pipeline/inputs). It would be nice to have some documentation publicly available.

**Comment by patrick-stephens** [comment]
A PR would be great to add it here: https://github.com/fluent/fluent-bit-docs/tree/master/pipeline/inputs

**Comment by ccampo133** [comment]
Haven't got around to this yet.

**Comment by Kikiodazie** [comment]
Hey @ccampo133 @patrick-stephens,

Still possible to work on this?

**Comment by patrick-stephens** [comment]
> Hey @ccampo133 @patrick-stephens,
> 
> Still possible to work on this?

Anyone can submit a PR so feel free to @Kikiodazie

**Comment by seblaz** [comment]
Hi, although it's not documented, is it possible to use this plugin?

**Comment by ccampo133** [comment]
> Hi, although it's not documented, is it possible to use this plugin?

It does appear usable. Unfortunately you'll need to parse the code and figure out the inputs for yourself. Start here: https://github.com/fluent/fluent-bit/tree/master/plugins/in_unix_socket

**Comment by patrick-stephens** [comment]
Btw, you can get plugin config via the `--help` parameter as well in case it helps, e.g. `docker run --rm -it fluent/fluent-bit:2.2.1 -i udp --help` (replace `-i udp` with your choice of plugin and whether it is an input, output or filter).
