### ISSUE TITLE
Sending logs from fluentbit forward plugin to fluentbit input plugin :: parser : expecting an array (type=2), skip

### ISSUE THREAD

**Issue by raulgupto** [fluent/fluent-bit#7154]
## Fluentbit input plugin does not understand what it listens on the port

**Input plugin expects an array**
[input:forward:forward.0] parser : expecting an array (type=2), skip

I'm using fluentbit on one host to send logs via forward plugin to a different host where fluentbit is listening to a port. The forward plugin on my receiving host logs above issue.

My sender host running fluentbit has similar config as below:
[SERVICE]
    Log_Level  debug

[INPUT]
    Name       cpu
    Tag        cpu_usage

[OUTPUT]
    Name          forward
    Match         *
    Host          myhostname
    Port          24224
    Shared_Key    mysecret
    Self_Hostname ${HOSTNAME}
    tls           on
    tls.verify    off
   tls.ca_file /path/to/pem.file

My receiver host has similar input config:

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    Buffer_Chunk_Size 1M
    Buffer_Max_Size   6M

[OUTPUT]
    Name   stdout
    Match  *

**Your Environment**
* Version used: 2.0.10
* Environment name and version : RHEL7

The stdout in my source/sender host for the log after parsing by fluentbit (if stdout instead of forward) is in this format:
[0] cpu_usage : [1234567890.012345678, {"name"=>"/path/to/log/file", "ip"=>"1.1.1.1", "time"=>"10/Apr/2023:07:47:43 -0400"}]
I found one issue which is similar to https://github.com/fluent/fluent-bit/issues/1468 where log flow is like fluentD -> fluentbit. 
Is there a way to configure inputs forward plugin, so that it can handle json/non-json formats ?

**Comment by patrick-stephens** [comment]
I think the issue might be you have TLS on output but not input...

**Comment by raulgupto** [comment]
Yes, you're correct. this issue was related to tls. We enabled tls on both input and output side by providing all these 3 fields " tls.ca_file", "tls.crt_file","tls.key_file". However, we found a bigger issue https://github.com/fluent/fluent-bit/issues/6690 . The cpu impact shooooots up by 25-30% for 3 minutes (for our case) till this tls log is flooded. Hope this is fixed up soon.
