### ISSUE TITLE
the  ignore_older of tail config is of no effect

### ISSUE THREAD

**Issue by yubobo** [fluent/fluent-bit#716]
![image](https://user-images.githubusercontent.com/4443390/44295357-d29e6900-a2d9-11e8-9a6e-e9f9bacb2f72.png)
but，in fact，add all files to scan the queue whenever the file is generated.

**Comment by yubobo** [comment]
![image](https://user-images.githubusercontent.com/4443390/44295390-70923380-a2da-11e8-82cd-54010fa767f9.png)

**Comment by yubobo** [comment]
![image](https://user-images.githubusercontent.com/4443390/44295394-84d63080-a2da-11e8-8fc2-d5624fe05afb.png)

**Comment by yubobo** [comment]
I change the value of ignore_older to **1m** ,the problem is the same.

**Comment by edsiper** [comment]
The ignore_older option is only available when a Parser is specific and that parser matched a line, so  when the parser lookup the time of that specific record it checks if is older than ignore_older or not.

**Comment by acarsercan** [comment]
Someone be kind enough to paste an example config with ignore_older & parser

Thanks

**Comment by avdhoot** [comment]
@acarsercan Might late.  Set `parser=myparser` in input plug-in `tail`. `tail` plugin will use `Time_Key` & `Time_Format` find out correct time to compare. 
```                                                                                                                                                     
[PARSER]                                                                                                                                                                
    Name         myparser                                                                                                                                                 
    Format       json                                                                                                                                                   
    Time_Key     time                                                                                                                                                   
    Time_Format  %Y-%m-%dT%H:%M:%S.%L                                                                                                                                   
    Time_Keep    On
[INPUT]
    Name             tail
    Path             /var/log/containers/*.log
    Tag              containers.*
    Refresh_Interval 1
    Rotate_Wait      60
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
    DB               /tail-db/tail-containers-state-sumo.db
    DB.Sync          Normal
    Ignore_Older 1m
    Parser  myparser
   
```
