### ISSUE TITLE
Public-consumable fluent-bit.h should not reference unnecessary dependencies

### ISSUE THREAD

**Issue by nrdvana** [fluent/fluent-bit#7165]
I'm attempting to use libfluent-bit.so as per [this example](https://docs.fluentbit.io/manual/development/ingest-records-manually)  The instructions don't say where to get fluent-bit.h but I found it in the package "fluent-bit-headers" which was added to my debian sources via the fluent-bit install process.

My problem is that fluent-bit.h includes <monkey/mk_core.h> and (assuming this is the monkey http server) that package is not available from debian, making it look like I have to manually install the monkey project just to be able to use the headers of libfluent-bit.  Meanwhile I have no way of knowing if the version I install is the same that was used to compile libfluent-bit.so from your repos.

I also don't know how deep this rabbit hole goes, because you have over a hundred headers that reference all kinds of things and hopefully I don't need to install headers for dependencies for every single one of them?

Meanwhile, the public api in flb_lib.h does not make any reference to these other libraries, so I ought to be able to have just the public structs declared in a standalone file and skip all the mess.  Are there reasons why you can't just have a "public-only" header file, or is this just an oversight in the tooling?

I worked around it using this custom header:

```
#ifndef FLB_LIB_H
#define FLB_LIB_H

#define FLB_EXPORT extern

/* Lib engine status */
#define FLB_LIB_ERROR     -1
#define FLB_LIB_NONE       0
#define FLB_LIB_OK         1
#define FLB_LIB_NO_CONFIG_MAP 2


/* Used on out_lib to define a callback and further opaque data */
struct flb_lib_out_cb {
    int (*cb) (void *record, size_t size, void *data);
    void *data;
};

/* For Fluent Bit library callers, we only export the following symbols */
struct flb_lib_ctx;
typedef struct flb_lib_ctx         flb_ctx_t;

FLB_EXPORT void flb_init_env();
FLB_EXPORT flb_ctx_t *flb_create();
FLB_EXPORT void flb_destroy(flb_ctx_t *ctx);
FLB_EXPORT int flb_input(flb_ctx_t *ctx, const char *input, void *data);
FLB_EXPORT int flb_output(flb_ctx_t *ctx, const char *output, struct flb_lib_out_cb *cb);
FLB_EXPORT int flb_filter(flb_ctx_t *ctx, const char *filter, void *data);
FLB_EXPORT int flb_input_set(flb_ctx_t *ctx, int ffd, ...);
FLB_EXPORT int flb_input_property_check(flb_ctx_t *ctx, int ffd, char *key, char *val);
FLB_EXPORT int flb_output_property_check(flb_ctx_t *ctx, int ffd, char *key, char *val);
FLB_EXPORT int flb_filter_property_check(flb_ctx_t *ctx, int ffd, char *key, char *val);
FLB_EXPORT int flb_output_set(flb_ctx_t *ctx, int ffd, ...);
FLB_EXPORT int flb_output_set_test(flb_ctx_t *ctx, int ffd, char *test_name,
                                   void (*out_callback) (void *, int, int,
                                                         void *, size_t, void *),
                                   void *out_callback_data,
                                   void *test_ctx);
FLB_EXPORT int flb_output_set_callback(flb_ctx_t *ctx, int ffd, char *name,
                                       void (*cb)(char *, void *, void *));

FLB_EXPORT int flb_filter_set(flb_ctx_t *ctx, int ffd, ...);
FLB_EXPORT int flb_service_set(flb_ctx_t *ctx, ...);
FLB_EXPORT int  flb_lib_free(void *data);
FLB_EXPORT double flb_time_now();

/* start stop the engine */
FLB_EXPORT int flb_start(flb_ctx_t *ctx);
FLB_EXPORT int flb_stop(flb_ctx_t *ctx);
FLB_EXPORT int flb_loop(flb_ctx_t *ctx);

/* data ingestion for "lib" input instance */
FLB_EXPORT int flb_lib_push(flb_ctx_t *ctx, int ffd, const void *data, size_t len);
FLB_EXPORT int flb_lib_config_file(flb_ctx_t *ctx, const char *path);

#endif

```

**Comment by braydonk** [comment]
One of the maintainers may have a better answer for you here, but it's worth clarifying that `monkey/mk_core.h` is very much a necessary dependency. Much of the stuff in `fluent-bit.h` use `mk_core` constructs heavily, primarily `mk_event` and everything that comes with that, and `mk_list`.

I don't know why `fluent-bit-headers` does not include the `mk_core` headers as well. That seems like a bug. `fluent-bit.h` is unusable without the stuff from monkey as well, and I don't see why all those shared objects wouldn't already be on the system after a fluent bit install.

[This file](https://github.com/fluent/fluent-bit/blob/af70da56c6284accef01512852d39d1d1e60b741/include/CMakeLists.txt) seems to suggest that the `mk_core` headers should all be packed in. I don't actually know anything about how those headers are packaged though, so I may just be looking in the wrong place. @patrick-stephens I wonder if you might know whether this is a bug or not?

**Comment by patrick-stephens** [comment]
The dependencies are all vendored, i.e. built with Fluent Bit using fixed versions rather than whatever the OS decides is right, so it probably should be. I guess the issue is fixing them may involve changes to those dependencies rather than Fluent Bit so bit chicken and egg.

For my side, it would be nice to have a standalone test case we could use to verify all this along with a PR to make any necessary changes. I very much dislike just adding "fixes" without verification to prevent it happening again.

@nrdvana if we can get a simple standalone example that we can add to CI to verify things that would help. Everything required.

**Comment by nrdvana** [comment]
@braydonk I can see that mk_list and friends are very much a dependency for the implementation of libfluent-bit and its plugins, but I'm focused on the "public API" described in the documentation that I linked.  Usually C projects have a top-level header for the most stable outer public APIs, then you can include additional headers to discover deeper less-public parts of the library if you need them.  The topmost fluent-bit.h seems to be everything needed for compilation of libfluent-bit itself.

I dug through the headers and made up a list:
  * jemalloc
  * cmetrics
  * monkey
  * ctraces
  * cfl

Stated differently, when I saw the documentation at [manual/development/ingent-records-manually](https://docs.fluentbit.io/manual/development/ingest-records-manually) it looked like I could just install packages for fluent-bit and fluent-bit-headers and then compile that example code, but instead it looks like I need every dependency used to compile libfluent-bit.  Maybe fluent-bit-headers was not intended for public consumption?  I didn't see any compilation instructions for 3rd party integration in the docs, and just guessed.  Usually a debian package for integrating a library would be named XXXX-dev, but I didn't see a "fluent-bit-dev".

The header I put inline above is what I would expect the project to provide for 3rd-party integration.

@patrick-stephens You can use the example right from fluent-bit's own documentation for a unit test.  It can't compile with just the distributed debian packages.

**Comment by nrdvana** [comment]
@patrick-stephens Actually, the fastest unit test to validate the headers would be

  echo "#include <fluent-bit.h>" | cpp -I/opt/fluent-bit/include/ >/dev/null;

If any headers are missing that will return a nonzero exit code.

**Comment by nrdvana** [comment]
Interestingly, when I compile fluent-bit from source, the "make install" does copy the monkey library, but misses msgpack.h and a few others.

I'm packaging this library for [use in perl](https://metacpan.org/release/NERDVANA/Fluent-LibFluentBit-0.01_01/view/lib/Fluent/LibFluentBit.pm), and it would be nice to get the headers fixed.  I'm including my header above as the fluent-bit.h distributed with the perl module, just so things can work.

**Comment by js290** [comment]
Thanks for pointing out #7346 is a duplicate; I should have searched more carefully before opening.

I waded through the headers, and most fundamentally, it seems like `fluent-bit` is violating the _Dependency Inversion Principle_.  I suspect there will not be a quick and dirty fix for this in `v2.1` nor `v2.0`.

**Comment by nrdvana** [comment]
BTW, I finished integrating libfluent-bit with Perl: [Fluent::LibFluentBit](https://metacpan.org/pod/Fluent::LibFluentBit)

In order to make it work, I added a new header [fluent-bit-minimal.h](https://metacpan.org/release/NERDVANA/Alien-FluentBit-0.01/source/include/fluent-bit-minimal.h) which is basically just the stuff I pasted above in this issue.

I think it would make a lot of sense if the fluent-bit project distributed ``fluent-bit-minimal.h`` alongside ``fluent-bit.h``, and then nobody needs to change the structure of the headers in this project.  It does make a small maintenance burden that these few functions would need maintained in two places.

**Comment by js290** [comment]
@nrdvana I stand corrected; there is a quick & dirty solution.  Appropriately abstracting the public API and private utility modules, like monkey, jemalloc, etc, would take more work and maybe prevent maintaining the same functions in multiple headers.  Your `fluent-bit-minimal.h` is a first step in that abstraction, i.e. everything else that need those functions should include `fluent-bit-minimal.h`.

**Comment by patrick-stephens** [comment]
@nrdvana can you submit a PR for your change?

**Comment by nrdvana** [comment]
I should be able to get a PR soon.  I got distracted by also wanting an output plugin for pure json output, but I'll get back to a branch with just this change in it.

**Comment by mavam** [comment]
For our solution, I went with the middle-ground of declaring `flb_lib_ctx` as:

```c
struct flb_lib_ctx {
    int status;
    void *event_loop;
    void *event_channel;
    void *config;
};
```

This allows me to poll `status` but ignore internals. (I need to poll `status` because I cannot use `flb_loop` and sleep in my calling context.)
