### ISSUE TITLE
Use of @include on YAML configuration files

### ISSUE THREAD

**Issue by mp3monster** [fluent/fluent-bit#7171]
Fluentd and Fluentbit support the use of @include so that large configuration files can be decomposed.  This currently doesn't work for YAML configuration files. However, given YAML files are highly sensitive to change, it makes it all the more valuable for the ability to break the sections into separate inclusions

Note without this it could impact the ability for people to migrate from the legacy format to YAML

**Describe the solution you'd like**
suggest a file preprocessor that performs simple text substitution before processing the file as a YAML file. This would make the mechanism pretty simple to achieve, even if that means a more elegant needs to follow later.

Alternatively, you could simplify both YAML and traditional formats by processing the use of @include as a substitution preprocessor  and creating a temporary config file; this would then mean that you could implement the inclusions at the same level of granularity as Fluentd. The upside of this approach is that then the result of the inclusions could also be easily seen in the event of an error

**Describe alternatives you've considered**
YAML-type declaration for inclusion. While syntactically correct would be less consistent and may limit the ability to migrate

**Comment by mp3monster** [comment]
It would be great if this could be identified on a roadmap

**Comment by patrick-stephens** [comment]
I think this is what you mean? https://github.com/fluent/fluent-bit/blob/ca0ccc30c2744824a9ec260c083e27b859b3e777/tests/internal/data/config_format/yaml/fluent-bit.yaml#L4-L5

Probably the docs need updating though.

**Comment by mp3monster** [comment]
it is indeed what I was looking for. 

I'd be happy to fix doc.  What's the best way - fork + pull request ?

**Comment by patrick-stephens** [comment]
Yup, just link it back so this can be closed

**Comment by pwhelan** [comment]
I can attest to the fact that this documentation is now live: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file#config_env-1.

Good work! 👍
