### ISSUE TITLE
How to sort the fields

### ISSUE THREAD

**Issue by yonchin** [fluent/fluent-bit#718]
Because of the need to customize regular expressions, some log fields are out of order, and sometimes fields need to be sorted so that multiple definitions of regular expressions are no longer needed

**Comment by JavaCS3** [comment]
Can you please provide sample log?

Does log fields out of order look like below？
```
<@timestamp> <level> <module> <message>
<@timestamp> <message> <level> <module>
```

I think the best way is to fix your log format.

**Comment by yonchin** [comment]
@JavaCS3 thks,  I  fix  my log format.
