### ISSUE TITLE
Fail to build docker image with avro encoder in output_kafka plugin

### ISSUE THREAD

**Issue by shuishou1983** [fluent/fluent-bit#7180]
## Bug Report

**Describe the bug**
Fail to build docker image if set -DFLB_AVRO_ENCODER=On

**To Reproduce**
- Steps to reproduce the problem:
  1. Clone the latest code
  2. Apply fix #5435 
  3. Update dockerfiles/Dockerfile and CMakeLists.txt to enable DFLB_AVRO_ENCODER. Attached the files for reference.
     [files.zip](https://github.com/fluent/fluent-bit/files/11220050/files.zip)
  4. Got to repo folder and run docker build command:
      docker build -t fluent-bit:v2.1.0 -f dockerfiles/Dockerfile .

**Expected behavior**
The command run without error and generate the docker image, but it got following error. 

- Example log message if applicable:
```
#26 8.298 CMake Error at lib/avro/CMakeLists.txt:39 (message):
#26 8.298   Cannot determine Avro version number
#26 8.298
#26 8.306 -- Configuring incomplete, errors occurred!
#26 8.306 See also "/src/fluent-bit/build/CMakeFiles/CMakeOutput.log".
#26 8.306 See also "/src/fluent-bit/build/CMakeFiles/CMakeError.log".
------
executor failed running [/bin/sh -c cmake -DFLB_RELEASE=On     -DFLB_OUT_KAFKA=On     -DFLB_TLS=On     -DFLB_HTTP_SERVER=On     -DFLB_AVRO_ENCODER=On     ..]: exit code: 1

```

**Your Environment**

* Version used: 2.1.0
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): Windows and Ubuntu
* Server type and version:
* Operating System and version:
* Filters and plugins: output_kafka

**Comment by patrick-stephens** [comment]
Possibly a duplicate of https://github.com/fluent/fluent-bit/issues/7175 and therefore resolved by https://github.com/fluent/fluent-bit/pull/7176

Could you try the changes on https://github.com/fluent/fluent-bit/pull/7176 to see if they resolve it @shuishou1983 ?
