### ISSUE TITLE
How to use multiple filters in Grep Filters

### ISSUE THREAD

**Issue by pranavsankar07** [fluent/fluent-bit#7181]
I`m using fluent-bit:2.0.11, i want grep and send logs to destination both are nginx logs.
1. GET logs 
2. SSL Handshaking 
  Problem what i observed is only SSL handshaking is sending not the GET logs (Both are sending live logs)

Kindly let me know how to send both regex

This is part of my config.

[FILTER]
    Name grep
    Match *
    Regex log GET\s?[^HTTP]+.+bytes_sent\=\d+
[FILTER]
    Name grep
    Match *
    Regex log SSL\shandshaking

**Comment by patrick-stephens** [comment]
Is this a duplicate of https://github.com/fluent/fluent-bit/issues/7168?

**Comment by pranavsankar07** [comment]
@patrick-stephens  Yes, I'm not sure why its only sending one type for regex logs but not other

**Comment by patrick-stephens** [comment]
2.1.0 is out with improvements for logical operations
