### ISSUE TITLE
Whitespace does not work in HTTP header values with the http output plugin

### ISSUE THREAD

**Issue by graniterocks** [fluent/fluent-bit#719]
## Bug Report

**Describe the bug**
If the value of an http header has whitespaces everything before the first whitespace in the value gets stripped away. The header key is read correctly. 

**To Reproduce**
I'm trying to set up fluent-bit with http output. My intention is to post to an Azure Evenhub 
endpoint and for that to work I need to send an HTTP header with an authorization token on the form:
Authorization: SharedAccessSignature sr=https%3A%2F%2F ....

What happens is that the SharedAccessSignature part of my config gets stripped away.  So that what the http plugin reads is a header with key: Authorization and value: sr=https%3A%2F%2F ....

This is my config: 
[OUTPUT]
        Name        http
        Match         *
        Host          <name>.servicebus.windows.net
        Port          443
        URI           /<EventHub>/messages
        header      Authorization SharedAccessSignature sr=<sr> sig=&skn=<skn>RootManageSharedAccessKey
        tls           On

**Expected behavior**
The full http header value should be read. 

**Your Environment**
* Version used: latest
* Operating System and version: ubuntu
* Filters and plugins: http output plugin

**Comment by edsiper** [comment]
thanks for reporting this problem.

The solution proposed worked for this very special case but it did not worked for others. 

A fix was placed by improving flb_utils_split() and doing extra checks in out_http. Upcoming 0.14.2 will have the fix in place, 

thanks again.
