### ISSUE TITLE
caught signal (SIGSEGV) sha1_block_data_order_shaext

### ISSUE THREAD

**Issue by markuman** [fluent/fluent-bit#7212]
## Bug Report

**Describe the bug**

it's dying.

```
Apr 17 14:10:31 someinstance fluent-bit: [2023/04/17 14:10:31] [ info] [input:tail:tail.3] inode=81789122 handle rotation(): /var/log/audit/audit.log => /var/log/audit/audit.log.1
Apr 17 14:10:31 someinstance fluent-bit: [2023/04/17 14:10:31] [ info] [input:tail:tail.3] inotify_fs_remove(): inode=81789122 watch_fd=33
Apr 17 14:10:31 someinstance fluent-bit: [2023/04/17 14:10:31] [ info] [input:tail:tail.3] inotify_fs_add(): inode=81789122 watch_fd=34 name=/var/log/audit/audit.log.1
Apr 17 14:10:31 someinstance fluent-bit: [2023/04/17 14:10:31] [ info] [input:tail:tail.3] inotify_fs_add(): inode=81789123 watch_fd=35 name=/var/log/audit/audit.log
Apr 17 14:10:36 someinstance fluent-bit: [2023/04/17 14:10:36] [ info] [input:tail:tail.3] inotify_fs_remove(): inode=81789122 watch_fd=34
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [engine] caught signal (SIGSEGV)
Apr 17 19:41:36 someinstance fluent-bit: #0  0x7b19579ff7d3      in  sha1_block_data_order_shaext() at ???:0
Apr 17 19:41:36 someinstance systemd: fluent-bit.service: main process exited, code=killed, status=6/ABRT
Apr 17 19:41:36 someinstance systemd: Unit fluent-bit.service entered failed state.
Apr 17 19:41:36 someinstance systemd: fluent-bit.service failed.
Apr 17 19:41:36 someinstance systemd: fluent-bit.service holdoff time over, scheduling restart.
Apr 17 19:41:36 someinstance fluent-bit: Fluent Bit v2.0.8
Apr 17 19:41:36 someinstance fluent-bit: * Copyright (C) 2015-2022 The Fluent Bit Authors
Apr 17 19:41:36 someinstance fluent-bit: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
Apr 17 19:41:36 someinstance fluent-bit: * https://fluentbit.io
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [ info] [fluent bit] version=2.0.8, commit=, pid=14640
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [ info] [storage] ver=1.4.0, type=memory+filesystem, sync=normal, checksum=off, max_chunks_up=128
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [ info] [storage] backlog input plugin: storage_backlog.7
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [ info] [cmetrics] version=0.5.8
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [ info] [ctraces ] version=0.2.7
Apr 17 19:41:36 someinstance fluent-bit: [2023/04/17 19:41:36] [ info] [input:tail:tail.0] initializing

```

**To Reproduce**

no idea atm.

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 2.0.8
* Configuration: just tails of some files and forward them to aws cloudwatch logs
* Environment name and version (e.g. Kubernetes? What version?): native installation
* Server type and version: amd64
* Operating System and version: Oracle Linux 7.9
* Filters and plugins:

**Additional context**

**Comment by nokute78** [comment]
I think it is a bug of openssl.
https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/openssl-sha-crash-bug-requires-application-update.html
```
OpenSSL* 1.0.2 beta (Jun 2014) to OpenSSL 1.0.2k (Jan 2017) contain bugs 
that either cause a crash or bad SHA (Secure Hash Algorithm) values on processors with the SHA extensions,
such as the recently released 10th Generation processor. 
```

I tested following commands and openssl 1.0.2k-26.el7_9 was installed. It is an affected version.
```
sudo docker run -it --rm oraclelinux:7.9
yum install openssl
```

```
=============================================================================================================
 Package               Arch                 Version                           Repository                Size
=============================================================================================================
Installing:
 openssl               x86_64               1:1.0.2k-26.el7_9                 ol7_latest               494 k
Installing for dependencies:
 make                  x86_64               1:3.82-24.el7                     ol7_latest               420 k

Transaction Summary
=============================================================================================================
Install  1 Package (+1 Dependent package)
```

**Comment by markuman** [comment]
That's interesting. openssl it not installed on that machine.  
We're using the centos 7 packages from https://packages.fluentbit.io/centos/7/x86_64/

**Comment by patrick-stephens** [comment]
A few things here:
- Have you tried the most recent 2.0.11 or even better the 2.1.1 version to confirm this is not resolved already?
- Oracle Linux is not officially supported (but may work)

We build using the CentOS 7 libraries so the RPMs are for CentOS but *can* be used on compatible targets.
So it may be there is an incompatibility between the libraries provided, or a bug fixed in a more recent version.

> openssl it not installed on that machine

I'm impressed you have a node without OpenSSL on it, that's pretty tricky as it is generally provided by the OS install - are you sure or do you mean you've not installed it (in which case something else may have)? 

@nokute78 I think is indicating that the OpenSSL provided by Oracle has the issue in it. Even the bare bones container image has it:
```shell
$ docker run --rm -it oraclelinux:7.9 rpm -qa|grep -i ssl
pyOpenSSL-0.13.1-4.el7.x86_64
openssl-libs-1.0.2k-26.el7_9.x86_64
```

Now, when you install the package provided for CentOS 7 it will end up with a binary that is linked to OpenSSL and then depends on the version you have installed locally:

```shell
$ docker run --rm -it oraclelinux:7.9
[root@7c8542e96cf2 /]# curl -O https://packages.fluentbit.io/centos/7/x86_64/fluent-bit-2.1.1-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.9M  100  9.9M    0     0  3108k      0  0:00:03  0:00:03 --:--:-- 3109k
[root@7c8542e96cf2 /]# yum install ./fluent-bit-2.1.1-1.x86_64.rpm -y
...
Complete!
[root@7c8542e96cf2 /]# ldd /opt/fluent-bit/bin/fluent-bit |grep -i ssl
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f3b6e6cd000)
	libssl3.so => /lib64/libssl3.so (0x00007f3b6a3b5000)
[root@7c8542e96cf2 /]# rpm -q --whatprovides /lib64/libssl.so.10
openssl-libs-1.0.2k-26.el7_9.x86_64
```

This is all using the container image so please confirm on your node but ultimately the issue is with the OS provided OpenSSL libraries which Fluent Bit uses, and the version used on Oracle Linux seems to have the issue @nokute78 identified.

From memory, Oracle Linux also provides two kernels: one that is RHEL-compatible and one that is... not. 
Make sure your kernel is right too.

**Comment by markuman** [comment]
> Have you tried the most recent 2.0.11 or even better the 2.1.1 version to confirm this is not resolved already? (I don't think so because it is an issue with Oracle Linux provided libraries - see below).

I've updated to 2.1.1 today.  
In the past it happens every few days

```
Apr  2 20:54:56 someinstance fluent-bit: #0  0x7bdd6670a794      in  sha1_block_data_order_shaext() at ???:0
Apr  5 13:48:31 someinstance fluent-bit: #0  0x7f829f23d794      in  sha1_block_data_order_shaext() at ???:0
Apr  9 21:38:36 someinstance fluent-bit: #0  0x74e00882d7a5      in  sha1_block_data_order_shaext() at ???:0
Apr 17 19:41:36 someinstance fluent-bit: #0  0x7b19579ff7d3      in  sha1_block_data_order_shaext() at ???:0
Apr 21 03:33:36 someinstance fluent-bit: #0  0x7a87c92087a5      in  sha1_block_data_order_shaext() at ???:0
Apr 23 21:44:31 someinstance fluent-bit: #0  0x7d3ef7df7794      in  sha1_block_data_order_shaext() at ???:0
```

So it needs to be observed a few days.

---

> I'm impressed you have a node without OpenSSL on it, that's pretty tricky as it is generally provided by the OS install - are you sure or do you mean you've not installed it (in which case something else may have)?

The libs are installed. In the first moment I was search checking the availability of the cli command `openssl` only.

```
$ yum list installed |grep -E 'ssl|tls'
gnutls.x86_64                        3.3.29-9.el7_6                @ol7_latest  
openssl-libs.x86_64                  1:1.0.2k-25.el7_9             @ol7_latest 
```

---

**Comment by markuman** [comment]
> Oracle Linux is not officially supported (but may work)

In the past we build it ourself based on a Docker image

```
FROM oraclelinux:7

RUN yum groupinstall "Development Tools" -y
RUN yum install wget flex bison  gcc-c++ libyaml yaml-cpp-devel openssl-devel -y

RUN wget https://github.com/Kitware/CMake/archive/refs/tags/v3.14.5.tar.gz && \
    tar xf v3.14.5.tar.gz && \
    cd CMake-3.14.5/ && \
    ./configure && \
    make && \
    make install

RUN yum install https://yum.oracle.com/repo/OracleLinux/OL7/optional/developer/x86_64/getPackage/libyaml-devel-0.1.4-11.el7_0.x86_64.rpm -y

COPY Makefile /Makefile
```

and that Makefile build target 

```
fbit: ## build fluent-bit binary
	wget https://github.com/fluent/fluent-bit/archive/v$(VERSION).tar.gz
	tar xf v$(VERSION).tar.gz
	cd fluent-bit-$(VERSION)/build && cmake .. -DFLB_HTTP_SERVER=on -DFLB_TLS=on -DFLB_SMALL=on -DFLB_CONFIG_YAML=on && make -j 2
	mkdir -p /mnt/$(OS)/
	cp -a fluent-bit-$(VERSION)/build/bin/fluent-bit /mnt/$(OS)/fluent-bit-$(VERSION)
	cp -a fluent-bit-$(VERSION)/build/bin/fluent-bit /mnt/$(OS)/fluent-bit-latest
```

but it was a time waster, because we've got only 7 OL instances for properitary 3rd party software.  
So is your recommendation to build it again directly for OL instead of using the cent os build?

Atm I cannot say if it is really a serious crash, because systemd is restarting it very quickly and we're just tailing on log files.

And another point is, that OL 7 becomes EOL next year  (_basic support_) and we're forced to go with OL 8 soon.  


---
https://endoflife.date/oraclelinux

**Comment by markuman** [comment]
> From memory, Oracle Linux also provides two kernels: one that is RHEL-compatible and one that is... not.
Make sure your kernel is right too.

```
uname -a
Linux someinstance 5.4.17-2136.315.5.el7uek.x86_64 #2 SMP Wed Dec 21 19:57:57 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I'm not very familar with RH/OL...

**Comment by markuman** [comment]
```
rpm -q --whatprovides /lib64/libssl.so.10
openssl-libs-1.0.2k-25.el7_9.x86_64
```

maybe we're lacking some patchlevel. Yours is `1.0.2k-26`

**Comment by patrick-stephens** [comment]
I think the issue is in OpenSSL on your OS per @nokute78 analysis above: I cannot really comment on that though. 

If it is that, then there's nothing we can really do in Fluent Bit to resolve it - possibly different versions (of either FB or OpenSSL) will show it more/less and building it yourself may change things but ultimately if it's the OpenSSL issue then it needs a resolution in that library.

A patch level change I do not think will fix it but I cannot say - it depends what is in the patch. The original advisory says:
```
OpenSSL* 1.0.2 beta (Jun 2014) to OpenSSL 1.0.2k (Jan 2017) contain bugs that either cause a crash or bad SHA (Secure Hash Algorithm) values on processors with the SHA extensions
```
Therefore the OS needs to be using greater than a 1.0.2k version from what that says.

Note that the doc linked above suggests there are potential ways to disable the SHA extensions so you could look at those: https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/openssl-sha-crash-bug-requires-application-update.html

```
OpenSSL provides an environment variable control for enabling features, including one that modifies the Intel® CPU identification, [OPENSSL_ia32cap](https://www.openssl.org/docs/manmaster/man3/OPENSSL_ia32cap.html)
```

This will be likely very specific to your OS and processor config.

**Comment by markuman** [comment]
> A patch level change I do not think will fix it but I cannot say - it depends what is in the patch. The original advisory says:

Yes, It does not change/fix it. It still rarely crashes and systemd is quickly restarting it.  
Because it depends on the openssl version, I close this issue now.
