### ISSUE TITLE
hi, about Regarding implementing an output plugin with C++.

### ISSUE THREAD

**Issue by suppersam1** [fluent/fluent-bit#7216]
I tried to write a custom output plugin using C++ code, but the .a file was not generated. Strangely, no error messages were reported.

**Comment by patrick-stephens** [comment]
How did you do it and with what source? This sounds like an issue with your environment but hard to tell.

**Comment by Suppertian** [comment]
> How did you do it and with what source? This sounds like an issue with your environment but hard to tell.
I created a directory named "out_custom" in the plugins directory and added relevant CPP code to it. Then, I registered my plugin in the CMakeLists.txt file in the plugins directory by following the example of other code.

**Comment by Suppertian** [comment]
> > How did you do it and with what source? This sounds like an issue with your environment but hard to tell.
> 
> I created a directory named "out_custom" in the plugins directory and added relevant CPP code to it. Then, I registered my plugin in the CMakeLists.txt file in the plugins directory by following the example of other code.

set(src
  custom.cpp
  handle.cpp
  jsoncpp.cpp
  PgSqlConnector.cpp
)

FLB_PLUGIN(out_custom "${src}" "")

target_link_libraries(flb-plugin-out_custom -lpqxx -lpq)

**Comment by patrick-stephens** [comment]
Can you provide the actual code? Or a simple reproducible example?
