### ISSUE TITLE
Parsing JSON log message issue with Fluent Bit and containerd (CRI) logging format

### ISSUE THREAD

**Issue by Laakso** [fluent/fluent-bit#7218]
I'm currently attempting to parse a JSON log message from a stdout stream using Fluent Bit. Recently we started using containerd (CRI) for our workloads, resulting in a change to the logging format. I was able to find a solution to this issue in the Fluent Bit documentation (https://docs.fluentbit.io/manual/installation/kubernetes#container-runtime-interface-cri-parser), and it successfully parses the log. However, I've encountered a problem where the message section of the log isn't being correctly parsed into Elasticsearch fields. To illustrate the issue, please see the attached image. Is there any way to address this problem?

Container Runtime Version:  `containerd://1.6.19`

Fluent bit input and parser configuration:
```
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    Parser cri
    Tag kube.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[PARSER]
    Name cri
    Format regex
    Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```
<img width="1257" alt="Logs" src="https://user-images.githubusercontent.com/6129901/232848096-33f5f743-aa57-4c19-8bdd-c083c8487f64.png">

**Comment by nokute78** [comment]
If you want to parse json value, could you try filter_parser plugin ?
in_tail -> "filter_parser" -> out_es

Following configuration is an example to parse json.
The value of `message` is a JSON. filter_parser parses it.

a.conf:
```
[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name dummy
    Dummy {"a":"b", "A":"B", "message":"{\"json_key\":\"json_val\"}"}

[FILTER]
    Name parser
    Match *
    Parser json
    Key_Name message
    Reserve_Data on

[OUTPUT]
    Name stdout
    Match *
```

parsers.conf:
```
[PARSER]
    Name   json
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```

**Comment by Laakso** [comment]
@nokute78 thanks :)

I was able to solve the issue by using [multiline parser](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-core-v1.8).

I basically changed my INPUT configuration to following
```
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    multiline.parser cri
    Tag kube.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On
```

**Comment by purohit14** [comment]
@Laakso I am also facing the same issue after switching the K8s cluster to use Containerd. Elasticsearch indexes are having a message field that contains the original log message in JSON format. 

The message field and value are the same as yours. I want to index each and every field in the message JSON like traceid, thread_name etc. 

Does your solution perform this thing? By setting the multiline parse as cri, can we index all the fields in the  message JSON ? 

thanks in Advance
