### ISSUE TITLE
Fluent-bit only sending time and host to syslog

### ISSUE THREAD

**Issue by Kris33** [fluent/fluent-bit#7221]
## Bug Report

**Describe the bug**
Fluent-bit only sending time and host to syslog

**To Reproduce**
Apr 19 09:19:03 t8925
Apr 19 09:19:56 t8925
Apr 19 09:32:15 t8925
Apr 19 09:32:15 t8925
Apr 19 09:32:15 t8925
Apr 19 09:33:25 t8925

```
Installed fluent-bit 2.0.10 on windows 10 
configured it like so :

`[SERVICE]
    flush        5
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

[INPUT]
    Name         winlog
    Channels     System,Application
    Interval_Sec 1
    DB           winlog.sqlite

[OUTPUT]
    name                 syslog
    match                *
    host                 10.40.20.2
    port                 514
    mode                 udp
    syslog_format        rfc5424
    syslog_maxsize       2048
    syslog_severity_key  severity
    syslog_facility_key  facility
    syslog_hostname_key  computer
    syslog_appname_key   application
    syslog_procid_key    processid
    syslog_msgid_key     eventid
    syslog_sd_key        structured_data
    syslog_message_key   log


[OUTPUT]
    Name   stdout
    Match  *`

**Expected behavior**
log to RFC5424 Format with expected fileds

**Your Environment**
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used: Windows10 / Fluent-bit 2.0.10
* Configuration: 
* Environment name and version: Windows 
* Operating System and version: windows 10,2016,2019,
* Filters and plugins: none . only trying to send logs to syslog-ng


Stdout works fine. syslog does not. although this syslog server collects events from other devices and servers via rsyslog, Nxlog at FortiSyslogd

**Comment by agup006** [comment]
The syslog output key fields are selectors on top of the current records. the key fields will need to map the Windows structure to the Syslog output structure, if they do not exist it could cause issues with the format

With stdout you can see the structure of the Windows Log and choose appropiate mappings

**Comment by zifengyu** [comment]
We are facing the same issue. Is it possible to output the whole records (encoded to a json string) as the syslog message?

> The syslog output key fields are selectors on top of the current records. the key fields will need to map the Windows structure to the Syslog output structure, if they do not exist it could cause issues with the format
> 
> With stdout you can see the structure of the Windows Log and choose appropiate mappings

**Comment by leonardo-albertovich** [comment]
This could be a good fit for a JSON serialization processor but honestly I don't think we'll be able to do it in the short term so I would suggest creating a wasm filter script to use with `filter_wasm` or a lua script (although I think for this use case wasm would be a better choice if possible).
