### ISSUE TITLE
Missing 2.0.11 Windows release binary

### ISSUE THREAD

**Issue by hcderaad** [fluent/fluent-bit#7227]
**Is your feature request related to a problem? Please describe.**
The problem is that Windows builds of fluent-bit seem to lag behind releases pretty long. 2.0.11 was released mid March and 2.1.0 has been released today, but neither 2.0.11 or 2.1.0 have made it to the releaases site yet.

**Describe the solution you'd like**
Shorter release gaps between the release tagged on GH and the Windows binaries being published on https://releases.fluentbit.io/2.0/

**Describe alternatives you've considered**
Compiling myself, yet without a valid code signing cert this does not result in a universally usable binary.

**Comment by patrick-stephens** [comment]
There should be no lag, it's all the same workflow.

There was an issue with the 2.1.0 upload but that was resolved: https://releases.fluentbit.io/2.1/

These builds come from Appveyor:
I'll have to check what happened on 2.0.11 for that.

We have Github built ones though, we want to deprecate that and they cover all releases:  
https://packages.fluentbit.io/windows/

**Comment by patrick-stephens** [comment]
The issue seems to be there is no build on Appveyor for the 2.0.11 tag: https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/history

I am not sure why, possibly some issue that side at the same time meant it was missed.

**Comment by patrick-stephens** [comment]
Separately I will tweak the release workflow to ensure it properly fails at that point: https://github.com/fluent/fluent-bit/actions/runs/4619227098/jobs/8167702537
![Screenshot from 2023-04-20 08-48-01](https://user-images.githubusercontent.com/6388272/233297052-c623b5dc-bc25-4916-821f-4dfee341ec9b.png)

**Comment by hcderaad** [comment]
Thanks @patrick-stephens there is indeed a build for 2.1, we're going to continue with that.

I'm closing this issue as the cause has been addressed and a new version is available.
