### ISSUE TITLE
Is there any grok support

### ISSUE THREAD

**Issue by ksemaev** [fluent/fluent-bit#723]
Just wanted to ask if there is any grok support (for example https://github.com/fluent/fluent-plugin-grok-parser), or I still need logstash/fluentd between fluentbit and elastic to parse logs the way I need them?

**Comment by edsiper** [comment]
There is no Grok support in Fluent Bit. What you can use instead is Regex (ruby like) expressions or direct JSON. You can learn more about the parser backends available here:

https://docs.fluentbit.io/manual/parser

note: Fluent Bit uses the same Regex engine than Fluentd

**Comment by windware-ono** [comment]
I'd like to see Grok support in fluent bit.
It's safer and cleaner to write parsing rules than DIY regex.

Why are there no interest for it?

**Comment by yakir-shriker** [comment]
I would also like to see Grok support in fluent-bit.
We did migration from other log aggregator with heavy grok usage, wanted to use fluent-bit but ended using fluentd just because grok missing.
