### ISSUE TITLE
HTTP 204 response header contains Content-Length value

### ISSUE THREAD

**Issue by szgy** [fluent/fluent-bit#7231]
## Bug Report

**Describe the bug**
The http_prot.c (https://github.com/fluent/fluent-bit/blob/master/plugins/in_http/http_prot.c) line 73 contains this code:

`
flb_sds_printf(&out,
    "HTTP/1.1 204 No Content\r\n"
    "Server: Fluent Bit v%s\r\n"
    "%s"
    "Content-Length: 0\r\n\r\n",
    FLB_VERSION_STR,
    context->success_headers_str);
`

which is in contradiction with the [RFC 9110 HTTP Semantics](https://www.rfc-editor.org/rfc/rfc9110.html) / [Content Length](https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length) :

A server MUST NOT send a Content-Length header field in any response with a status code of 1xx (Informational) or 204 (No Content). A server MUST NOT send a Content-Length header field in any 2xx (Successful) response to a CONNECT request (Section 9.3.6).

**To Reproduce**
NA: Was a code review

**Expected behavior**
HTTP Response should follow specifications

**Screenshots**
NA: Was a code review

**Your Environment**
NA: Was a code review

**Additional context**

**Comment by nokute78** [comment]
Thank you for pointing it.
I sent a patch #7291
