### ISSUE TITLE
[Parser:cri] Invalid TimeStamps

### ISSUE THREAD

**Issue by knechtionscoding** [fluent/fluent-bit#7233]
## Bug Report

**Describe the bug**

After upgrading from 2.0.11 to 2.1.0 the CRI Parser is failing to known good timestamps properly.

```bash
fluent-bit [2023/04/20 14:28:08] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2023-04-20T14:28:�'
fluent-bit [2023/04/20 14:28:08] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2023-04-20T�'
fluent-bit [2023/04/20 14:28:13] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2023-04-20T14:2�'
fluent-bit [2023/04/20 14:28:29] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2023-04-20T14:28:29.046922�'
fluent-bit [2023/04/20 14:28:31] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2023-04-20�'
fluent-bit [2023/04/20 14:29:01] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '2023-04-2�'
fluent-bit [2023/04/20 14:33:13] [ warn] [parser:cri] invalid time format %Y-%m-%dT%H:%M:%S.%L%z for '�'
```

**To Reproduce**

I've been unable to generate the logs that show the actual message that is being parsed, but the log messages don't change between 2.0.11 and 2.1.0

I've set fluentbit to trace to try to get the parser to print the failed log message and it isn't

**Expected behavior**

Timestamps to be parsed correctly

**Screenshots**

**Your Environment**

* Version used: 2.1.0
* Configuration: Default CRI Parser
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.24
* Server type and version: cr.fluentbit.io/fluent/fluent-bit:2.1.0

**Additional context**

About 10% of all logs are failing to be parsed now

**Comment by patrick-stephens** [comment]
What text format are the logs in? It looks like you're getting a special character there.
