### ISSUE TITLE
Filter on systemd not working

### ISSUE THREAD

**Issue by rucciva** [fluent/fluent-bit#7234]
## Bug Report

Filter section is not executed when using systemd 

**To Reproduce**
- create config that use rewrite tag to change systemd tag
```
[Input]
    Name    systemd
    Tag    systemd.*
    Systemd_Filter    _SYSTEMD_UNIT=containerd.service
    Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
[Filter]
    Name    rewrite_tag
    Match    systemd.*
    Rule    $log (.+) loki.$TAG false
    Emitter_Name    systemd_loki
[OUTPUT]
    Name   stdout
    Match  systemd.*
```

- run fluentbit with said config

**Expected behavior**
No output are generated since the filter is executed and the tag is rewritten

**Screenshots**

<img width="931" alt="Screen Shot 2023-04-20 at 22 30 27" src="https://user-images.githubusercontent.com/4647473/233414940-5a40e022-fcee-42f4-af2c-bcdb5665f56e.png">

**Your Environment**

* Version used: 2.0.11
* Configuration: as above
* Environment name and version (e.g. Kubernetes? What version?): kubernetes 1.23 with fluent operator 2.2
* Server type and version: 
* Operating System and version: ubuntu 18.04
* Filters and plugins: rewrite_tag and stdout

**Additional context**

If i change the config to this
```
[Input]
    Name    systemd
    Tag    systemd.*
    Systemd_Filter    _SYSTEMD_UNIT=containerd.service
    Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
[Filter]
    Name    rewrite_tag
    Match    systemd.*
    Rule    $log (.+) loki.$TAG false
    Emitter_Name    systemd_loki
[OUTPUT]
    Name   stdout
    Match  loki.systemd.*
```
no output are displayed

**Comment by patrick-stephens** [comment]
Your output is still matching the original input: rewrite tag creates effectively a duplicate stream of it, it does not stop the current tag at that point.

**Comment by rucciva** [comment]
> it does not stop the current tag at that point.

i specified keep as false (`Rule    $log (.+) loki.$TAG false`) as noted in <https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#keep>. Won't that make the original record dropped and doesn't continue in pipeline?

besides, using this output step didn't produce anything, which should output the same line if the filter match right?
```
[OUTPUT]
    Name   stdout
    Match  loki.systemd.*
```

**Comment by patrick-stephens** [comment]
Ah yeah, my bad for skimming over it on mobile.

Does the example in the docs work? 
https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#configuration-example

**Comment by rucciva** [comment]
yes the example works
<img width="933" alt="Screen Shot 2023-04-21 at 17 30 42" src="https://user-images.githubusercontent.com/4647473/233614452-6c768b5f-8149-4d1a-b4a5-893332d3198b.png">

**Comment by nokute78** [comment]
Could you try following `Rule` config ?
```
    Rule    $MESSAGE (.+) loki.$TAG false
```

Output of systemd plugin doesn't contain the key `log`.

**Comment by rucciva** [comment]
ah i see, thanks @nokute78 , it works
