### ISSUE TITLE
out_prometheus_remote_write: add compress 'gzip'/'zstd' support

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#7239]
VictoriaMetrics team reach out on KubeCon asking if we support compression on remotewrite side. Mostly interest on gzip and zstd.

**Comment by leonardo-albertovich** [comment]
I don't know how to link the PR to this issue but this is the implementation #7318

**Comment by valyala** [comment]
It would be great to have the ability to use zstd compression for Prometheus remote_write protocol - see https://victoriametrics.com/blog/victoriametrics-remote-write/

**Comment by leonardo-albertovich** [comment]
Zstd is definitely still in the roadmap.

**Comment by cdancy** [comment]
@leonardo-albertovich is there some road map users can see? We'd certainly benefit from using zstd, especially for S3 output plugin, to give better compression ratios resulting in smaller file part sizes (with bigger contents).

**Comment by leonardo-albertovich** [comment]
https://github.com/fluent/fluent-bit/wiki/Fluent-Bit although zstd isn't there, I think it fell through the cracks, what do you think @edsiper?
