### ISSUE TITLE
Integrating Fluent-bit into existing CMake project

### ISSUE THREAD

**Issue by UkrainianProgrammer** [fluent/fluent-bit#724]
Hello, I am getting the following error when trying to add fluent-bit directory to my existing CMake build:

```
CMake Error at cots/fluentbit/fluent-bit/lib/monkey/mk_core/CMakeLists.txt:117 (configure_file):
 configure_file attempted to configure a file:
 /usr/cots/fluentbit/fluent-bit/lib/monkey/mk_core/../include/monkey/mk_core/mk_core_info.h
 into a source directory.

-- Configuring incomplete, errors occurred!
```

The `/usr/cots/` path is located on my Docker Alpine image used for my container build. I simply add the line `add_subdirectory (cots)` to my top-level CMakeLists.txt. Is this not enough for CMake to build it properly? Thank you!

**Comment by edsiper** [comment]
it can be integrated, would you please provide me a simple structure of directories and CMakeLists.txt that you are using to reproduce the problem ?

note: Alpine linux is not supported by Fluent Bit (musl and other compatibility issues)

**Comment by UkrainianProgrammer** [comment]
Thanks for helping on this one, @edsiper. Here is my CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.0.0)

include (ExternalProject)
externalproject_add (fluent-bit
  PREFIX            ${CMAKE_CURRENT_BINARY_DIR}/fluent-bit
  URL               "${CMAKE_CURRENT_SOURCE_DIR}/fluent-bit"
  BUILD_IN_SOURCE   1
  BUILD_ALWAYS      1
  BUILD_COMMAND     make
  INSTALL_COMMAND   make install
)
```
The folder structure is as follows: `code/cots/fluentbit/fluent-bit`. The CMakeLists.txt from above resides in fluent-bit folder and I keep calling `add_subdirectory()` as I go up in each folder's CMakeLists.txt. The code above works but my question is: can we integrate Fluent-bit without using `externalproject_add()`? Thanks again.

**Comment by robweiss** [comment]
Has any progress been made on this?

**Comment by Minipada** [comment]
Still nothing on this?
