### ISSUE TITLE
log based metrics to be exposed using output prometheus or prometheus_remote_write

### ISSUE THREAD

**Issue by joaopl-worten** [fluent/fluent-bit#7246]
The idea of the request is to be able to expose log-based metrics directly to Prometheus without having to collect them from logs, aggregate them, and have them exposed to Prometheus.

**Comment by agup006** [comment]
Curious on why not use the node_exporter_metrics input plugin?

**Comment by joaopl-worten** [comment]
Hi @agup006, we have fluent bit running as a sidecar of our tasks (we use AWS ECS for orchestration) node would be giving us the metrics of the node not the metrics of the fluent-bit container, at least from what is my knowledge.
