### ISSUE TITLE
Fluenbit config after the output plugin number 256 is not working

### ISSUE THREAD

**Issue by kavinkumar1999** [fluent/fluent-bit#7263]
## Bug Report

**Describe the bug**
We are using fluentbit to ship the logs of multiple services. We have a separate config file for each service with around 2-5 input tail plugins, 4 filter plugins and 1 output plugin(kafka). In the fluent-bit.conf file, we are using @INCLUDE  option to add the config files of these services. We have noticed that the config after output plugin number **256** is becoming stale and not working. This has resulted in logs being not shipped from service no 257, but for services from 1 to 256, fluentbit is working as expected.

**To Reproduce**

Steps to reproduce the problem:

1. Create a fluent-bit.conf file with dummy input plugin and stdout output plugin numbered from 1 to 300 as shown below, 

```
[SERVICE]
    Flush  3
    Daemon       Off
    Mem_Buf_Limit 50MB
    Log_Level    info
[INPUT]
    Name dummy
    Tag  dummy1
[OUTPUT]
    Name  stdout
    Match dummy1
[INPUT]
    Name dummy
    Tag  dummy2
[OUTPUT]
    Name  stdout
    Match dummy2
...
...
...

[INPUT]
    Name dummy
    Tag  dummy300
[OUTPUT]
    Name  stdout
    Match dummy300
```

2. Run the process and check for the logs, and logs until the output plugin number 256 will be coming, but logs for the dummy plugins with tags numbered 257 to 300 will not be flowing.

**Expected behavior**
We would expect the logs for all the services from service 1 to 300 to get shipped by fluentbit.
 
**Screenshots**

<img width="368" alt="Screenshot 2023-04-25 at 3 44 08 PM" src="https://user-images.githubusercontent.com/77623860/234248095-1175b042-f840-4999-9de7-c04f1780c539.png">
<img width="598" alt="Screenshot 2023-04-25 at 3 44 26 PM" src="https://user-images.githubusercontent.com/77623860/234248207-e4c6f4fc-aa18-4a45-b399-190f293be9de.png">
<img width="1107" alt="Screenshot 2023-04-25 at 3 48 38 PM" src="https://user-images.githubusercontent.com/77623860/234248272-8909c3a7-1552-4540-a4ae-f3f179fa22dc.png">
<img width="1161" alt="Screenshot 2023-04-25 at 3 49 19 PM" src="https://user-images.githubusercontent.com/77623860/234253291-b903fc91-1410-4a51-9efa-96ab542037e8.png">

Screen recording:
The quality of the video was affected after compression, but have used the same dummy config as mentioned above

https://user-images.githubusercontent.com/77623860/234250591-bc8d02eb-7106-4420-a62d-5b36aa7c79d0.mov

**Your Environment**

* Version used: 2.0.6
* Environment name: Kubernetes
* Operating System and version: CentOS 7

**Additional context**

This issue has led to logs not being shipped for a few services and the service owners were unable to debug some prod issues because the logs were not available for these services in the centralised logging platform.

Our current number of output plugins is around 270, this might reach 600 in the near future. The number of output plugins limit was not mentioned in the documentation. Please include the limit for the number of input, filter and output plugins in the documentation if there is any limit as such.

**Comment by adiforluls** [comment]
See https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file#config_output
