### ISSUE TITLE
Fluent Bit in Production: Add LeanIX logo

### ISSUE THREAD

**Issue by dan-leanix** [fluent/fluent-bit#7265]
Hey everyone,

[LeanIX](https://www.leanix.net/) has been a user of Fluent Bit since the last year when we migrated from Azure Monitor to Fluent Bit for our log collection. We really enjoy the performance and the configuration flexibility with Fluent Bit. If you would like to add our logo to the `Fluent Bit in Production` section.

![leanix](https://user-images.githubusercontent.com/51328018/234262203-e0a0bf36-b488-4945-bc14-659727a7eaa0.png)

You find the brand guidelines at https://www.leanix.net/hubfs/2019-LX-Website/Company/LX-Brand-Guide.pdf

Thanks,
Daniel

**Comment by dan-leanix** [comment]
@agup006 Are you the correct person for this? :)

**Comment by agup006** [comment]
Whoa so sorry for missing this

**Comment by dan-leanix** [comment]
@agup006 No worries. We recently finished the last part of our migration replacing InsightOps with FluentBit. So, Fluent Bit is now our backbone for log collection, and we highly appreciate the work you and the other maintainers and contributors put into this project. Thanks a lot.
