### ISSUE TITLE
Fluent-bit can't collect log normally when the number of log files is too large.

### ISSUE THREAD

**Issue by hoperays** [fluent/fluent-bit#728]
## Bug Report

**Describe the bug**
I collect kvm vm boot logs using fluent-bit. After creating and deleting vm automated test for a long time in the environment, the number of log files is too large, this causes fluent-bit can't collect log normally.

**Screenshots**
```
[root@node-1 ~]# ls -l /var/log/libvirt/qemu/ | wc -l
60875
[root@node-1 ~]# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127700
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 102400
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 102400
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Your Environment**
* Version used:
  - fluent-bit: 0.12.14
* Configuration:
```
[INPUT]
    Buffer_Max_Size 2MB
    DB /var/log/flb_host.db
    DB.Sync OFF
    Mem_Buf_Limit 5MB
    Name tail
    Path /var/log/libvirt/qemu/*.log
    Tag ${HOSTNAME}.host.*

[OUTPUT]
    Host ${FLUENTD_HOST}
    Match *
    Name forward
    Port ${FLUENTD_PORT}
```
* Environment name and version (e.g. Kubernetes? What version?):
  - Kubernetes v1.9.8
* Operating System and version:
  - CentOS 7.4.1708
* Filters and plugins:
  - Input Plugin: Tail
  - Output Plugin: Forward

Strangely, there is no any relevant abnormal log output. I have temporarily cancelled the collection of vm boot logs. What should I do next? Sorry to bother you.

**Comment by edsiper** [comment]
how many log files do you have there and what's the average size of those files ?

**Comment by hoperays** [comment]
@edsiper This is one of the nodes:
```
[root@node-1 ~]# ls -l /var/log/libvirt/qemu/ | wc -l
60875
[root@node-1 ~]# ls -lh /var/log/libvirt/qemu/
......
-rw------- 1 root root 2.5K 8月  27 13:57 instance-00000003.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-0000000d.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-00000016.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-00000019.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-0000001c.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-00000022.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-0000002e.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-00000031.log
-rw------- 1 root root 2.5K 8月  27 13:58 instance-00000037.log
......
```

**Comment by userguy** [comment]
Any update on this ???

**Comment by jstaffans** [comment]
@edsiper, is there some documentation on how file handles are managed by Fluent Bit? Are handles released at some point, even if the log file is still there?

**Comment by userguy** [comment]
In My case the kafka client give this error and does not resume after retry limit the logs sending is paused . 
I think i have to explore other tools to send data to kafka
