### ISSUE TITLE
sigsegv while using hot reload with prometheus_exporter

### ISSUE THREAD

**Issue by pabloxxl** [fluent/fluent-bit#7297]
## Bug Report

**Describe the bug**
While using hot reload feature (both SIGHUP and /reload endpoint), if prometheus_exporter is being used fluent-bit crashes. It is reproducible with 100% rate

**To Reproduce**
```
$> cat config
[SERVICE]
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_PORT     2202
[OUTPUT]
    name            prometheus_exporter
    host            0.0.0.0
    port            2203
```

```
$> /opt/fluent-bit/bin/fluent-bit -c config -v -Y
```

**Expected behavior**
Fluent-bit is reloaded

**Screenshots**
[log.txt](https://github.com/fluent/fluent-bit/files/11372150/log.txt)
Log with valgrind -s (reproduces also without valgrind)

**Your Environment**
* Version used: 2.1.1 (I checked version delivered by apt and binary I've built myself)
* Configuration: reproduces on Fedora and Ubuntu on WSL
* Environment name and version (e.g. Kubernetes? What version?): Just raw binary
* Server type and version: desktop
* Operating System and version: reproduces on Fedora and Ubuntu on WSL
* Filters and plugins: prometheus_exporter

**Additional context**
I'm testing hot reload with
- `sudo pkill -f -HUP fluent-bit`
- `curl -XPOST -d {} 0.0.0.0:2202/api/v2/reload`

**Comment by leonardo-albertovich** [comment]
Hi @pabloxxl, we are aware of this issue and I just submittted this [PR](https://github.com/monkey/monkey/pull/395) to fix it so I think the fix will likely be included in the next release (which if I'm correct should be published sooner rather than later).

**Comment by pabloxxl** [comment]
Oh, I wasn't aware that this is a general problem with multiple http servers - thats why I've created a new issue.
I will close mine as duplicate.
