### ISSUE TITLE
Allow filter_rewrite_tag to modify records in-place

### ISSUE THREAD

**Issue by mikaelmello** [fluent/fluent-bit#7300]
**Is your feature request related to a problem? Please describe.**

Apologies if my understanding of fluent-bit's architecture is vastly wrong and I misunderstood how it works. The problem is easily reproducible though and that's the main thing I'm trying to solve.

I've got the following logging pipeline:

> **Forwarder** (DaemonSet, 1 per node)
> 
> - Input (Tail) [TAIL]
> - Output (Forward to Aggregator) [OUTFWD]
> 
> **Aggregator** (Deployment, scales up and down based on load)
> 
> - Input (Forward) [INAGG]
> - Filter (json parser) [JSON]
> - Filter (Lua) [LUA]
>   - Adds a new `src` property with an expression in the form of `$record['EventName']:lower() .. "logs"`
> - Filter (rewrite_tag) [RETAG]
>   - `Rule $src .* $src false`
> - Output (Forward to internal service) [OUTAGG]

The main issue I'm facing is that, when our log load suddenly increases and there is not enough CPU (in the form of several aggregator instances) to process them all, each aggregator fills up their respective input buffers and the inputs are paused.

So far great, as long as INAGG gets paused, OUTFWD will keep it stored in the fs and retrying. The storage `filesystem` takes care of keeping things under control.

The problem comes from the fact that rewrite_tag RETAG has its own emitter. When this emitter is overlimit and gets paused, any logs the filter processes seem to get dropped. As I understand it, this in turns clears INAGG's buffer unpausing it, allowing for more logs to arrive and get lost because RETAG is already saturated.

**Describe the solution you'd like**

Ideally, all memory management should be controlled by INAGG so that the backpressure works E2E across all different services.

I've seen that `filter_multiline` seems to allow not using a buffer, which looks like what I'd want here?

**Describe alternatives you've considered**

- Setting RETAG to use `filesystem` storage. This gets tricky because
  1. On scale down, backlogged chunks are not flushed I think, so I still have a chance of losing these logs.
  2. When having multiple aggregator instances on the same node, Disk IO goes through the roof and everything gets slowed down, latency goes up etc. CPU-wise it was fine but overall the situation was worse.
- Putting the RETAG step in the forwarder which is already backed by fs storage.
  - This is equivalent to not needing an aggregator at all as I'd need to move the LUA filter to the forwarder as well.
  - In high-load scenarios (over 30k records tailed per sec) the pipeline gets saturated, CPU is at the limit, and tail can't keep up with the files.
    - For that, I tried using `tail` with `Threaded On`, but it worsened performance because the ringbuffer was not being cleared fast enough, leading to tons of `failed buffer write` and logs dropped.
- Setting RETAG to use `memrb` storage. Not a valid config and it would lead to log drops any way.
- Looking for another way to retag the records, but didn't find any.

The only real solution I have is to put a very large Mem_Buf_Limit and scale out my aggregator instances _way before_ (at like 25% of usage) so that the limit is never reached. With this solution I'm wasting more resources than I'd like but it's the only thing I got now.

**Additional context**

**Comment by leonardo-albertovich** [comment]
Hello @mikaelmello, although I can't dedicate the time to go through the code to validate the emitter issue claims at the moment IIRC you are right.

The thing is that due to how chunks are stored / grouped changing the tag of an already persisted chunk requires this and I don't see that changing in the short term, however, I think we might be able to improve the "processor" system to allow this.

I'll assign this issue to myself to keep track of it and even though I can't give you an ETA I'll try to prioritize this change (because the processor system is still young and flexible so now is the best time to make such a change).

**Comment by mikaelmello** [comment]
> The thing is that due to how chunks are stored / grouped changing the tag of an already persisted chunk requires this and I don't see that changing in the short term

That makes sense, thanks for the explanation.

I was in fact taking a look at the two processor-related PRs you recently merged just a couple of days ago!

Do you expect it to support the json+lua processing? (or something else that's not lua). Unfortunately I don't have much of a choice when it comes to extracting the tag from the record's property.

**Comment by mikaelmello** [comment]
Also, do you know of any generic recommendations for high-load scenarios? I understand how nothing beats actual testing, but I'd like to at least make sure I am not doing anything counter-productive lol

**Comment by mikaelmello** [comment]
> Could you elaborate on that JSON+lua thing? I don't think I understand what you meant by it, do you mean re-tagging from within a lua script?

I meant that on my pipeline, the new tag is derived from a property of my record's log message, which is serialized in JSON. So I  currently need to deserialize the record, concat `"Source"` to a property called `EventName`, and from that new value I have my new tag.

> Whenever possible use the new processor feature, either by using the labels / attributes native processors or by transparently chaining filters in the processor stack.

I look around (a little bit though) and couldn't quite understand how to use processors, neither could find any docs, could you give me some pointers here?

As for everything else I think I've got it covered so that's great :)
