### ISSUE TITLE
in_kafka: update the code to use the log event abstraction layer

### ISSUE THREAD

**Issue by leonardo-albertovich** [fluent/fluent-bit#7301]
The kafka input plugin uses mpack to manually produce log records. 
This needs to be replaced with the corresponding `log_event_encoder` based code.

A basic example of the required code can be found in the [in_event_type](https://github.com/fluent/fluent-bit/blob/master/plugins/in_event_type/event_type.c#L73) and some of the more advanced examples can be found in [in_tail](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_file.c#LL311C22-L311C62).

**Comment by edsiper** [comment]
assigned to @tarruda

**Comment by tarruda** [comment]
@Syn3rman already fixed in #7359
