### ISSUE TITLE
add missing .note.GNU-stack sections

### ISSUE THREAD

**Issue by balazshasprai** [fluent/fluent-bit#7315]
**Is your feature request related to a problem? Please describe.**
I'm building fluent-bit from source for SUSE Linux Enterprise 15 / openSUSE Leap 15.
During `make` there's a lot of:
```
missing .note.GNU-stack section implies executable stack
NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```
**_And_** after the make / make install / packaging is done, rpmlint gives two warnings about libfluent-bit.so and the fluent-bit executable, saying:
```
fluent-bit.x86_64: W: executable-stack /lib64/fluent-bit/libfluent-bit.so
fluent-bit.x86_64: W: executable-stack /usr/bin/fluent-bit
The binary declares the stack as executable.  Executable stack is usually an
error as it is only needed if the code contains GCC trampolines or similar
constructs which uses code on the stack.  One common source for needlessly
executable stack cases are object files built from assembler files which don't
define a proper .note.GNU-stack section.
```
And for some build targets these two warnings are enough to make the build fail. (rpmlint says not good enough = flagged as failed)

**Describe the solution you'd like**
I'd like it if the `missing .note.GNU-stack sections` were added to the code.
I'm not a C/C++ developer, so I don't really know where they'd go.
One thing I found while looking for answers is [this gentoo wiki page, called Hardened/GNU stack quickstart](https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart) 
It says patching with something like this is the way to go:
```
#if defined(__linux__) && defined(__ELF__)
.section .note.GNU-stack,"",%progbits
#endif
```

**Describe alternatives you've considered**
Since I have no idea where or how to apply that patch, I went with adding `-DFLB_WASM_STACK_PROTECT=On` to cmake, 
which in turn sets these:
```
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fstack-protector-strong --param ssp-buffer-size=4")
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")
```
With the `-z,noexecstack` the files are no longer built with executable stacks, but every source is telling me that this is just a workaround, adding the proper .note.GNU-stack parts is the better way of fixing it.

**Additional context**
Trying to build and package fluent-bit for SUSE / openSUSE for work and homelab use.
For openSUSE Tumbleweed the two execstack warnings actually make the packaging fail.

Here's an example of the warnings during the `make` process:
```
[ 75%] Linking C executable ../bin/fluent-bit
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: invokeNative_em64.s.o: missing .note.GNU-stack section implies executable stack
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
[ 75%] Built target fluent-bit-bin
...
...
[ 84%] Linking C shared library ../lib/libfluent-bit.so
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: invokeNative_em64.s.o: missing .note.GNU-stack section implies executable stack
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
[ 84%] Built target fluent-bit-shared
...
...
[ 94%] Linking C executable ../../bin/flb-rt-filter_modify
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: invokeNative_em64.s.o: missing .note.GNU-stack section implies executable stack
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
[ 94%] Built target flb-rt-filter_modify
[ 94%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_multiline.dir/filter_multiline.c.o
[ 94%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_multiline.dir/__/__/lib/lwrb/lwrb/src/lwrb/lwrb.c.o
[ 94%] Linking C executable ../../bin/flb-rt-filter_multiline
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: invokeNative_em64.s.o: missing .note.GNU-stack section implies executable stack
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
[ 94%] Built target flb-rt-filter_multiline
[ 94%] Building C object tests/runtime/CMakeFiles/flb-rt-out_opensearch.dir/out_opensearch.c.o
[ 94%] Building C object tests/runtime/CMakeFiles/flb-rt-out_opensearch.dir/__/__/lib/lwrb/lwrb/src/lwrb/lwrb.c.o
[ 94%] Linking C executable ../../bin/flb-rt-out_opensearch
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: invokeNative_em64.s.o: missing .note.GNU-stack section implies executable stack
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
[ 94%] Built target flb-rt-out_opensearch
[ 94%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_ecs.dir/filter_ecs.c.o
[ 94%] Building C object tests/runtime/CMakeFiles/flb-rt-filter_ecs.dir/__/__/lib/lwrb/lwrb/src/lwrb/lwrb.c.o
[ 94%] Linking C executable ../../bin/flb-rt-filter_ecs
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: invokeNative_em64.s.o: missing .note.GNU-stack section implies executable stack
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
[ 94%] Built target flb-rt-filter_ecs
```

**Comment by patrick-stephens** [comment]
I will start by saying this is not a supported target but any contribution to improve it is of course appreciated.

I think your issue may be solved by https://github.com/fluent/fluent-bit/pull/6087 @Garfield96 ?

**Comment by Garfield96** [comment]
From my experience fluent-bit also works on SLES. #6087 does not fix this issue, but I could extend it to include `-z noexecstack`. While I agree that fixing the object files is a better solution, we would first need to analyze which files causes the issue and I fear they are imported from upstream projects.

@patrick-stephens Shall I add `-z noexecstack` to the PR?

Off-topic: If you build fluent-bit on SLES, I highly recommend to not use the default compiler, but instead get gcc-11 (available in the package repos), since this will allow you to build the binary with LTO/IPO, which will compensate the performance degradation caused by security flags.

**Comment by balazshasprai** [comment]
Yes I know it's not a supported platform, but thought I'd give it a try, maybe it could benefit the other distros too.
And yes it does work on SLES. It's just their Open Build Service shows the above warnings.

But if it's too much hassle for an unsupported platform I understand, I'll just keep building it with the noexecstack flag.
And will go with gcc11 thanks for the tip!

And thank you both for your time!

(I'm not sure if I should close this issue, or as not planned, or leave it open just in case?)

**Comment by patrick-stephens** [comment]
We used to do SLES as well for some Enterprise offerings so yeah it does work but just from an OSS perspective not supported. If @Garfield96 resolves the issue then we can close this as well.
