### ISSUE TITLE
fluentbit.io down

### ISSUE THREAD

**Issue by anthonybgale** [fluent/fluent-bit#7320]
## Bug Report

**Describe the bug**
fluentbit.io is down

**To Reproduce**
```
curl -v https://packages.fluentbit.io
```
```
(curl: (28) Failed to connect to packages.fluentbit.io port 443 after 129531 ms: Connection timed out)
```

**Additional context**
https://github.com/fluent/fluent-bit/issues/1314

**Comment by patrick-stephens** [comment]
Resolved DNS issue.
