### ISSUE TITLE
Appending timestamp on raw message

### ISSUE THREAD

**Issue by HemantDubey-ACS** [fluent/fluent-bit#7327]
## Bug Report

**Describe the bug**
There is an extra string is get appending on my logs "2023-05-05T13:32:20.493387331Z stdout F", this breaking my json logs. I don't want to add any extra value in my logs

`{
    "log": "2023-05-05T13:32:20.493387331Z stdout F {\"level\":\"info\",\"time\":\"2023-05-05T13:32:20Z\",\"caller\":\"handler/routes.go:48\",\"msg\":\"Interceptor\",\"RequestID\":\"3b487753-c9c3-4737-93d3-955057797a73\",\"log\":{\"APIUrl\":\"/api/v1/config\",\"Latency\":0,\"PublicIP\":\"xxx.xx.18.13\",\"StatusCode\":200,\"Request\":null,\"Response\":null,\"UserAgent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36\",\"Err\":\"\",\"Headers\":{\"ClientVersion\":\"\",\"ClientId\":\"\",\"ClientBuild\":\"\",\"ClientIP\":\"\",\"AppId\":\"\",\"ApplicationName\":\"\"}}}",
    "xkubernetes": {
        "container_hash": "ccc.dkr.ecr.ap-south-1.amazonaws.com/gauntlet-be@sha256:098c8c08a204948e4514652f8304e79a6c7268c2f76e3b97bba546f4e9ecee53",
        "container_image": "ccc.dkr.ecr.ap-south-1.amazonaws.com/gauntlet-be:staging-CB-4b6a9cff63e513149a6c976400cbc3756988bc31-x86_64",
        "container_name": "aaaa-be",
        "host": "ip-172-30-18-163.ap-south-1.compute.internal",
        "labels": {
            "app": "gauntlet-be",
            "pod-template-hash": "ccc"
        },
        "namespace_name": "staging",
        "pod_id": "8592378a-810c-4d58-a9f4-5730711b4266",
        "pod_name": "gauntlet-be-5fb98585d9-x6nmr"
    }
}`

My raw logs 

`{"level":"info","time":"2023-05-05T13:32:20Z","caller":"handler/routes.go:48","msg":"Interceptor","RequestID":"3b487753-c9c3-4737-93d3-955057797a73","log":{"APIUrl":"/api/v1/config","Latency":0,"PublicIP":"xxx","StatusCode":200,"Request":null,"Response":null,"UserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","Err":"","Headers":{"ClientVersion":"","ClientId":"","ClientBuild":"","ClientIP":"","AppId":"","ApplicationName":""}}}`

- Steps to reproduce the problem:

**Expected behavior**

My expected log should be 
```
{
    "log": {"level":"info","time":"2023-05-05T13:32:20Z","caller":"handler/routes.go:48","msg":"Interceptor","RequestID":"3b487753-c9c3-4737-93d3-955057797a73","log":{"APIUrl":"/api/v1/config","Latency":0,"PublicIP":"xxx","StatusCode":200,"Request":null,"Response":null,"UserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","Err":"","Headers":{"ClientVersion":"","ClientId":"","ClientBuild":"","ClientIP":"","AppId":"","ApplicationName":""}}},
    "xkubernetes": {
        "container_hash": "ccc.dkr.ecr.ap-south-1.amazonaws.com/gauntlet-be@sha256:098c8c08a204948e4514652f8304e79a6c7268c2f76e3b97bba546f4e9ecee53",
        "container_image": "ccc.dkr.ecr.ap-south-1.amazonaws.com/gauntlet-be:staging-CB-4b6a9cff63e513149a6c976400cbc3756988bc31-x86_64",
        "container_name": "aaaa-be",
        "host": "ip-172-30-18-163.ap-south-1.compute.internal",
        "labels": {
            "app": "gauntlet-be",
            "pod-template-hash": "ccc"
        },
        "namespace_name": "staging",
        "pod_id": "8592378a-810c-4d58-a9f4-5730711b4266",
        "pod_name": "gauntlet-be-5fb98585d9-x6nmr"
    }
}
```

**Your Environment**

      containers:
      - name: fluent-bit-compatible
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        imagePullPolicy: Always

**Additional context**

**Comment by patrick-stephens** [comment]
That looks like the standard CRI format log so are you using that parser?

Please follow the issue template and provide full config plus version, target, etc.

**Comment by HemantDubey-ACS** [comment]
I have follow this article for setting up the fluent in my EKS.

[AWS fluentbit setup](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs-FluentBit.html
)
User the below file for setting up the pod and config.

`kubectl apply -f https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit-compatible.yaml`

MY EKS: 1.26

**Comment by patrick-stephens** [comment]
@PettitWesley I'm guessing with more recent EKS the log format may have changed due to DockerShim deprecation? It may be that we need to update to use the new `multiline.parser` approach with `docker, cri` configured but it's not my area of expertise and seems to be all in the AWS docs.

**Comment by HemantDubey-ACS** [comment]
Are you sure it not due to fluent bit? DO we have any reference for the same?

**Comment by PettitWesley** [comment]
This confuses me, because we enable the `cri` multiline parser: https://github.com/aws-samples/amazon-cloudwatch-container-insights/blob/main/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit.yaml#L71

@HemantDubey-ACS when did you apply it?

When I check the latest config map linked in the docs its now up to date with the multiline cri parser: https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit/fluent-bit.yaml

Can you please try re-deploying.
