### ISSUE TITLE
Why doesn’t fluent-bit’s nats output support configuring subject?

### ISSUE THREAD

**Issue by M4n5ter** [fluent/fluent-bit#7333]
When I get content from input, I want to send the content to a specified nats subject. However, I found that the nats output plugin does not support configuring subject.

**Comment by leonardo-albertovich** [comment]
It seems like the nats output plugin is fairly old and basic and could really use a bit of improvement so you would be more than welcome if you decided to contribute some of the improvements (such as this particular setting).

If you decide to give it a try and need some guidance don't hesitate to contact me here or in slack and I'll assist you as much as possible.
