### ISSUE TITLE
PID in CPU input plugin not working

### ISSUE THREAD

**Issue by jadiym** [fluent/fluent-bit#7338]
## Bug Report

**Describe the bug**
In the fluentbit cpu input plugin documentation it is stated that by default it measures the cpu metrics of the whole system however we can add PID if we want to find metrics of a particular process.  When I try to do it it gives the error below. 
I've already checked that the file exists and also it has read access.  Without providing PID it works just fine
 
**Logs**

```
2023/05/08 07:40:10] [error] [/src/fluent-bit/plugins/in_cpu/cpu.c:186 errno=2] No such file or directory
[2023/05/08 07:40:10] [error] [input:cpu:cpu.0] error opening stats file /proc/85432/stat
[2023/05/08 07:40:10] [error] [cpu] Could not obtain CPU data
[2023/05/08 07:40:10] [error] failed initialize input cpu.0
[2023/05/08 07:40:10] [error] [engine] input initialization failed
[2023/05/08 07:40:10] [error] [lib] backend failed
```
- Steps to reproduce the problem:

**Expected behavior**
It should show cpu metrics of given PID. 

 **Pod Detail**
```namespace   fluent-bit-85zbb                                  0/1     CrashLoopBackOff   1          6s```

**Your Environment**
Using a VM and it has a k8s-cluster running on  it. 
* Version used: 2.0.6
* Configuration: 
```
filter-kubernetes.conf: |
    [FILTER]
      name kubernetes
      match kubernetes.*
      kube_url https://kubernetes.default.svc:443
      Kube_Tag_Prefix kubernetes.var.log.containers.
      tls.verify False
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
  fluent-bit.conf: |
    [SERVICE]
      flush 1
      log_level info
      daemon off
      parsers_file parsers.conf
    [INPUT]
      Name cpu
      Tag  my_cpu
      PID 85432
    [INPUT]
      Name   mem
      Tag    memory
    [OUTPUT]
      Name  file
      Match memory
      Mkdir true
      Path /var/log/kubelet
    [OUTPUT]
      Name  file
      Match my_cpu
      Mkdir true
      Path /var/log/kubelet
    [OUTPUT]
      Name  counter
      Match *

    @INCLUDE filter-kubernetes.conf
    @INCLUDE input-tail-kube-system.conf
    @INCLUDE output-file-kube-system.conf
  input-tail-kube-system.conf: |
    [INPUT]
      Name tail
      Tag kube*
      Path /var/log/pods/*/log-generator/*.log
      Parser docker
      refresh_interval 30
      mem_buf_limit 10MB
      DB /var/log/flb_kube.db
  output-file-kube-system.conf: |
    [OUTPUT]
      Name file
      Match *
      Mkdir true
      Path /var/log/kubelet
  parsers.conf: |-
    [PARSER]
      Name        docker
      Format      json
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
      Time_Keep   On
      Decode_Field_As   escaped    log

    [PARSER]
      Name        syslog
      Format      regex
      Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
      Time_Key    time
      Time_Format %b %d %H:%M:%S

    [PARSER]
      Name        apache
      Format      regex
      Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
      Name        apache2
      Format      regex
      Regex       ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
      Name        apache_error
      Format      regex
      Regex       ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$
```
* Operating System and version: CentOS
* Filters and plugins: as mentioned in the cm above

**Comment by leonardo-albertovich** [comment]
Please correct me if I'm wrong but it seems that you are running fluent-bit in a way in which it's isolated in its own container instance which is why it can't access the `/proc` entry for that process you are trying to monitor.

**Comment by jadiym** [comment]
Ok that idea came to my mind but if that's the case then how it was working when no PID was passed. I.e. when it was monitoring the whole system.  
If that is actually the case then can you help me how I can use cpu plugin to monitor a particular process.

**Comment by jadiym** [comment]
Yes. It's true

**Comment by leonardo-albertovich** [comment]
If that's the case then I recon that the instance where fluent-bit is running should be able to access the `/proc/PID/` entry for the PID you've set as long as it exists (maybe a followup good question would be how are you getting this PID number?) and since I'm not a kubernetes expert I don't think I'm the right person to take this any further.

It's odd to me that the error message clearly states that fluent-bit tried to open the `stat` pseudo file but couldn't because to the PID directory doesn't exist at that point in time and to be honest, I don't know how would you have that PID file before fluent-bit starts so maybe we should take a step back and talk a little bit about your use case so we ensure that everyone is on the same page (including the more qualified folks who will take this over).

**Comment by jadiym** [comment]
Ok. So I wanted to check fluentbit cpu usage using this plugin. But as you have mentioned that PID file won't exist before fluentbit is started. So, for that I ran two instances of fluentbit in which one was doing the actual job (let's say 1st) i.e. to send logs and in another one I used the cpu plugin (2nd). So, in this scenario since 1st fluentbit process is running all along and so have a PID associated with it. I used this PID in my 2nd fluentbit config to monitor.  According to me this would have worked right ?? 

Also, lets take a step back and forget the upper points which I have mentioned. I used another process running in my k8s-cluster and used that process's PID to monitor its cpu usage.  Even that was not working.  Error remains the same.

**Comment by leonardo-albertovich** [comment]
Uhm yeah, I don't think this is something I'm qualified to help with. Could you please share a minimal spec that reproduces this bug? That way others will be able to chime in, validate it and help complete the triage.

**Comment by jadiym** [comment]
Sure. 
```
  fluent-bit.conf: |
    [SERVICE]
      flush 1
      log_level info
      daemon off
      parsers_file parsers.conf
    [INPUT]
      Name cpu
      Tag  my_cpu
      PID <PID_you _want_to_use>
  
    [OUTPUT]
      Name  file
      Match my_cpu
      Mkdir true
      Path /var/log/kubelet
 
    @INCLUDE input-tail-kube-system.conf
    @INCLUDE output-file-kube-system.conf
  input-tail-kube-system.conf: |
    [INPUT]
      Name tail
      Tag kube*
      Path <directory from where you need to tail logs>
      refresh_interval 30
      mem_buf_limit 10MB
      DB /var/log/flb_kube.db
  output-file-kube-system.conf: |
    [OUTPUT]
      Name file
      Match *
      Mkdir true
      Path <destination_directory>
```

Just make sure that this runs in k8s-cluster in a VM.  This should be good enough, I suppose.

**Comment by jadiym** [comment]
@patrick-stephens  One question I want to ask is that when I do not provide any PID in the cpu plugin, How does it work ?? Does it fetches system data from /proc only ? If that's a yes then why only create a problem when PID is specified. When for the whole system it works just fine.
I want to know the working of cpu plugin. Because fluentbit runs in a container so how it can give me system info? Kindly brief me about the same ??

**Comment by patrick-stephens** [comment]
`/proc` is always available to a container (well any process, it's not a container thing), it won't be the "whole" system though - it'll be the process namespace configured for that container. It's just a slice, it may or may not be correct for what you want. The point is you always get a "valid" `/proc`, but being valid does not require it to be complete.

This is more a question of cgroups and container runtimes, I would look into those if you're interested.
