### ISSUE TITLE
Podman input plugin errors because of undefined pointer

### ISSUE THREAD

**Issue by kramik1** [fluent/fluent-bit#7340]
## Bug Report

I am testing the podman metric plugin on Ubuntu 22.04 and it has errors when trying to gather data. The biggest issue is the undefined pointer that then shows in the logs.
[2023/05/08 15:23:55] [ warn] [input:podman_metrics:podman_metrics.0] Failed to open /proc/18446744073709551615/net/dev

It also seems to be trying to gather data for metric point that do not exist. For example, it is looking for memory.max but it seems that it meant to look for memory.max. These metric points are all hard coded at the moment. I don't know if offhand all cgroup metrics points are the same between all Linux distros.

It does collect a number of points successfully but it needs to be tweaked for at least Ubuntu 22.04.
 
I am on the master branch, compiling locally, with a very simple config:
[INPUT]
    Name podman_metrics
    Tag  podman

**Comment by leonardo-albertovich** [comment]
Actually, that's the value of `UINT64_MAX`  and there are some code paths where `get_data_from_sysfs` could return prematurely such as `get_container_sysfs_subdirectory` not being able to get `systemd_path` in line 325 and passing `NULL` in `dir`.

**Comment by vrga** [comment]
> Hey, 18446744073709551615 doesn't seem like a correct pid and you are for sure right - this comes from unitialized memory. Can you share more logs (or at least ones surrounding this error)?
> 
> > for example, it is looking for memory.max but it seems that it meant to look for memory.max.
> 
> Can you be more specific? It looks like the same names to me

i believe they might've meant memory.peak.


Here's my [log](https://gist.github.com/vrga/70d8a47aaa4daf36c4f1695a75be4d89) and [config file](https://gist.github.com/vrga/266b5ee35a9c8edceaffa30d2372c119), basically, not working.

**Comment by pabloxxl** [comment]
> > Hey, 18446744073709551615 doesn't seem like a correct pid and you are for sure right - this comes from unitialized memory. Can you share more logs (or at least ones surrounding this error)?
> > > for example, it is looking for memory.max but it seems that it meant to look for memory.max.
> > 
> > 
> > Can you be more specific? It looks like the same names to me
> 
> i believe they might've meant memory.peak.
> 
> Here's my [log](https://gist.github.com/vrga/70d8a47aaa4daf36c4f1695a75be4d89) and [config file](https://gist.github.com/vrga/266b5ee35a9c8edceaffa30d2372c119), basically, not working.

1. For memory.max vs memory.peak - I've checked plugin code and it collects both - do you think that their relation to particular metrics is mixed?
2. I will create a PR for detecting this missing /proc/net data soon
3. @vrga can you check, if any of files mentioned in your log file is readable by the user which is used to run fluent-bit binary? I see that you are using custom path for podman config json, is there a possiblity that other files are also located elsewhere?

**Comment by vrga** [comment]
fluent-bit is running as root. 
`cgroup.procs` is empty, `memory.max` exist, but value is "max", `memory.peak` doesnt seems to exist.
not sure on the custom paths, i genuinely dont think it would affect the stuff in `/proc` or `/sys`

here's my podman version:
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.15
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```
and [podman info](https://gist.github.com/vrga/9d3b5caf89999d00cdfb114914d5f5e0) as well.
This is on debian 11, hence why the potentially old version of podman.

**Comment by pabloxxl** [comment]
@vrga I've checked stock podman on latest Ubuntu LTS - cgroup.procs was indeed empty - but - containers/cgroup.procs was filled correctly. Can you check that behavior on your machine?

**Comment by vrga** [comment]
sorry, took a bit to get back to this, yes, `containers/cgroup.procs` has PIDs in them.

**Comment by pabloxxl** [comment]
Well, it behaves the same on my Ubuntu vm - I think I will just add a fallbacking mechanism for detecting pids in different location - I will create a PR for that + max int issue - probably in a week or two
