### ISSUE TITLE
Grep not work corect or I'm doing something wrong

### ISSUE THREAD

**Issue by SkyV0x** [fluent/fluent-bit#735]
Examples of config on the side td-agent-bit:
-----------------------------------------------------------------------------------------
```
[SERVICE]
    Flush       5
    Daemon       Off
    Log_Level    debug
    Log_File /var/log/td-agent-bit/td-agent-bit.log
    Parsers_File parsers.conf
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
[INPUT]
    Name cpu
    Tag  cpu.beta
    Interval_Sec 10
[INPUT]
    Name mem
    Tag  memory.beta
    Interval_Sec 10
[INPUT]
    Name tail
    Path /var/log/td-agent-bit/tcp-out.log
    Tag tcp.beta
[FILTER]
    Name grep
    Math tcp.beta
    Regex log example.fluentd
[OUTPUT]
    Name file
    Path /var/log/td-agent-bit/result.log
    Match *.beta

    #------include conf.d----------#
@INCLUDE ./conf/tcp.beta.conf
    #------end include conf.d------#
```
-----------------------------------------------------------------------------------------
Second config (included)
-----------------------------------------------------------------------------------------
```
[SERVICE]
    Flush           5
    Daemon          off
    Log_Level       debug
[INPUT]
    Name tcp
    Tag tcp.inc
    Port 5180
    Interval_Sec 1
    Chunk_Size  16
    Buffer_Size 64
[OUTPUT]
    Name  file
    Path /var/log/td-agent-bit/tcp_out.log
    Match tcp.inc
```
======================================================

And one simple question: why does the filter grep not output in the stdout that 100% is in the log output file tcp
The standard tail -f result.log | grep example.fluentd all perfectly displayed in CLI

The following is output to the log-file of the td-agent-bit:
----------------------------------------------------------------------------------------------
```
[2018/09/02 14:23:29] [debug] [in_tail] inotify watch fd=19
[2018/09/02 14:23:29] [debug] [in_tail] scanning path /var/log/td-agent-bit/tcp-out.log
[2018/09/02 14:23:29] [debug] [in_tail] Cannot read info from: /var/log/td-agent-bit/tcp-out.log
[2018/09/02 14:23:29] [debug] [in_tcp] Listen='0.0.0.0' TCP_Port=5180
[2018/09/02 14:23:29] [ info] [in_tcp] binding 0.0.0.0:5180
[2018/09/02 14:23:29] [ warn] [filter] NO match rule for grep.0 filter instance, unloading.
```
----------------------------------------------------------------------------------------------

**Comment by edsiper** [comment]
You have a 'Math' instead of 'Match'

**Comment by SkyV0x** [comment]
How I wanted to believe that fixing one letter will solve everything. But, alas, the miracle did not happen - the selection of data from the file does not happen. I have another question, but can such a configuration work? The ultimate goal is to throw data from the tcp stream into elasticsearch. In the raw form, this data is not accepted. Can eat ready recipes as a conclusion from a stream tcp to throw in elasticsearch

**Comment by SkyV0x** [comment]
And another question. Why is the log written like if the file is created by the td-bit-agent itself. What does it lack to take data from a file?

```
[2018/09/03 09:07:56] [debug] [in_tail] inotify watch fd=19
[2018/09/03 09:07:56] [debug] [in_tail] scanning path /var/log/td-agent-bit/tcp-out.log
[2018/09/03 09:07:56] [debug] [in_tail] Cannot read info from: /var/log/td-agent-bit/tcp-out.log
```

**Comment by edsiper** [comment]
Before the analysis I would suggest a bit of cleanup in the configuration:

- Do not add two [SERVICE] sections, just one is required.

Now looking at the configuration I see the following:

- The grep rule aims to Match any record which have a Tag equals to _tcp.beta_, but looking at the records generated there is no one that matches the rule, so the filter is not applied. 

- Not sure if is intentional or not but one tail section monitors _/var/log/td-agent-bit/tcp-out.log_ file while an output section writes to _/var/log/td-agent-bit/tcp_out.log_ (which are different: tcp-out v/s tcp_out)

**Comment by SkyV0x** [comment]
Maybe I'm doing something wrong, I do not fully understand the concept of the fluent work, but the concept was this: to view the incoming data from tcp and output to the log only what corresponds to a certain pattern. Initially, I tried to select regex data directly from the tcp stream. It did not work. Then I decided to collect all the data in the log file tcp-out.log and already from it with the grep filter select only what I need. But this also does not work. Therefore I turned to you. Regretfully, I have to admit that the documentation explains very little, especially if you first encounter your really cool decision. I'm interested in this.

**Comment by SkyV0x** [comment]
Can you any help me? Please!!!!

**Comment by agup006** [comment]
Hey all, I'm doing some cleanup for issues and see this is still open. @SkyV0x if you still need some help, I'm happy to give some assistance though I know it has been quite some time. We are working on more documentation, resources, trainings that will help folks get up and running for the project and will be happy to share with you.

I'm going to close this issue for now, please feel to re-open if there is more to tackle here
