### ISSUE TITLE
Fluent-bit 2.1 returns errors instead of proc_records when querying metrics endpoint.

### ISSUE THREAD

**Issue by Tony-AJ-Martin** [fluent/fluent-bit#7362]
## Bug Report

**Describe the bug**
After FB 2.1, an API call to the http_server metrics (http://localhost:2020/api/v1/metrics) returns a growing list of `errors` and 0 `proc_records` while at the same time, there are no actual errors showing in the FB container logs.

```
root@deab8f298aac:/# curl http://localhost:2020/api/v1/metrics
{"input":{"cpu.0":{"records":32395,"bytes":19145445}},"filter":{},"output":{"stdout.0":{"proc_records":0,"proc_bytes":0,"errors":6479,"retries":0,"retries_failed":0,"dropped_records":32393,"retried_records":0}}}
```

**To Reproduce**
* Build the standard FB docker image with the following configuration file: 

```
[SERVICE]
    # Flush
    Flush        5

    # Daemon
    Daemon       Off

    # Log_Level
    Log_Level    trace

    # Parsers_File
    Parsers_File parsers.conf
    Plugins_File plugins.conf

    # HTTP Server
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Health_Check On
    HC_Errors_Count 5
    HC_Retry_Failure_Count 5
    HC_Period 5

[INPUT]
    Name cpu
    Tag  cpu.local
    # Interval Sec
    # ====
    # Read interval (sec) Default: 1
    Interval_Sec 1

[OUTPUT]
    Name  stdout
    Match *
```
* Run and then exec into the container.
* From within the container, curl the metrics API `http://localhost:2020/api/v1/metrics`

The response will contain a value for `errors`. This value will grow each time the API call is made. There will be no actual errors in the FB container logs. `proc_records` will also be 0 and will not grow.

**Expected behavior**
`proc_errors` should return a non-zero value. `errors` should return 0 (assuming there are no errors in the FB container logs).

**Your Environment**

* Version used: 2.1
* Operating System and version: Debian
* Filters and plugins: none

**Additional context**
We have an auto-upgrade mechanism for our docker images with FB and we have goss tests to ensure that the upgrades work. Our tests caught this error. We are not sure if this has any effect on our usage of FB in production environments.

**Comment by leonardo-albertovich** [comment]
Thank you very much for taking the time to report this issue @Tony-AJ-Martin, we will look into it and get back to you as soon as possible!

**Comment by nokute78** [comment]
https://github.com/fluent/fluent-bit/blob/v2.1.2/src/flb_log_event_decoder.c#L291
Log decoder returns `FLB_EVENT_DECODER_ERROR_INSUFFICIENT_DATA` when msgpack API returns `MSGPACK_UNPACK_CONTINUE`.

out_stdout treats it is an error.
https://github.com/fluent/fluent-bit/blob/v2.1.2/plugins/out_stdout/stdout.c#L252

**Comment by leonardo-albertovich** [comment]
Yes, there's a patch for that we've been applying in other plugins which conditionally switches the result code when it's `FLB_EVENT_DECODER_ERROR_INSUFFICIENT_DATA` and the input buffer offset matches the input buffer size (in the decoder state). 

Maybe we should do that internally and define a new status code on the lines of `FLB_EVENT_DECODER_FINISHED` and then modify the plugins so their conditionals are something like `if (ret == FLB_EVENT_DECODER_FINISHED)`. 

What do you think?

**Comment by nokute78** [comment]
If so many plugins should check the "FLB_EVENT_DECODER_ERROR_INSUFFICIENT_DATA " and the buffer offset, it is better to check it at log decoder.

**Comment by leonardo-albertovich** [comment]
Exactly, I didn't do it at the moment because my brain was fried but it seems like the most rational approach.

**Comment by SvenScheurer** [comment]
Hi all,
is there any news on that issue?

**Comment by SvenScheurer** [comment]
Hi all,
is there any news on the issue?
This currently blocks us from updating to v.2.1.
