### ISSUE TITLE
Fluent-bit Podman Container using External input/output config files

### ISSUE THREAD

**Issue by oneofthemany** [fluent/fluent-bit#7363]
## Bug Report

**Describe the bug**
Cannot get fluent-bit to use external config files when using a podman container

**To Reproduce**
- Set fluent-bit to send data to influxdb v2
- Example log message:
```
{"Fluent Bit v2.1.2
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io/
[2023/05/11 12:16:15] [ info] Configuration:
[2023/05/11 12:16:15] [ info]  flush time     | 1.000000 seconds
[2023/05/11 12:16:15] [ info]  grace          | 5 seconds
[2023/05/11 12:16:15] [ info]  daemon         | 0
[2023/05/11 12:16:15] [ info] ___________
[2023/05/11 12:16:15] [ info]  inputs:
[2023/05/11 12:16:15] [ info] ___________
[2023/05/11 12:16:15] [ info]  filters:
[2023/05/11 12:16:15] [ info] ___________
[2023/05/11 12:16:15] [ info]  outputs:
[2023/05/11 12:16:15] [ info] ___________
[2023/05/11 12:16:15] [ info]  collectors:
[2023/05/11 12:16:15] [ info] [fluent bit] version=2.1.2, commit=113c7c00d2, pid=1
[2023/05/11 12:16:15] [debug] [engine] coroutine stack size: 24576 bytes (24.0K)
[2023/05/11 12:16:15] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/05/11 12:16:15] [ info] [cmetrics] version=0.6.1
[2023/05/11 12:16:15] [ info] [ctraces ] version=0.3.0
[2023/05/11 12:16:15] [ info] [sp] stream processor started"}
```
- Steps to reproduce the problem:
Spin up fluent-bit in a podman container to send data to a influxdb v2 instance using the configs shown below
**Expected behavior**
Data specified in input.conf to be sent to instance specified in output.conf

**Your Environment**
* Version used: Fluent Bit v2.1.2
* Configuration:
**fluent-bit.conf:**
```
[SERVICE]
  Flush 1s
  Log_Level debug

  @INCLUDE input_*.conf
  @INCLUDE output_*.conf
  #@INCLUDE filter_*.conf
```
**input.conf:**
```
[INPUT]
  Name cpu
  Match *
  Tag  agent_cpu
  Interval 1s

[INPUT]
  Name mem
  Match *
  Tag  agent_mem
  Interval 1s

[INPUT]
  Name thermal
  Match *
  Tag  sagent_thermal
  Interval 1s

[INPUT]
  Name proc
  Match *
  Tag  agent_proc
  proc_path = /proc
  Interval 1s


[INPUT]
  Name disk
  Match *
  Tag  agent_disk
  Interval 1s
  Path /
```
**output.conf:**
```
[OUTPUT]
  Name influxdb
  Type influxdb_v2
  Host 192.168.1.2
  Port 9086
  Organization hawthorn
  Bucket fluent_bit
  HTTP_Token blahblahblah
```

* Environment name and version: podman version 4.5.0
* Server type and version: HP Z2 G8 SFF Workstation
* Operating System and version:  Linux fedora 6.2.14-300.fc38.x86_64 (silverblue)

**Additional context**
Cannot seem to be able to understand how to troubleshoot connectivity between fluent-but and influxdbv2

**Comment by oneofthemany** [comment]
If it helps here is the script used to build the fluent-bit container:

```
#!/bin/bash
function info {
         tput bold;
         tput setaf 3;
         echo $1;
         tput sgr0;
}
info "=== Setting up FluentBit==="

# shellcheck disable=SC2155
export RANDOM_TOKEN=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 88 ; echo '')

info "=== Configure Influx Token ==="
read -r -p "Enter Influx Token [example: ${RANDOM_TOKEN}]: " influxToken
export INFLUXDB_TOKEN=${influxToken:-"${RANDOM_TOKEN}"}

info "=== Configure Influx Organisation ==="
read -r -p "Enter Influx Organisation Name [example: my_org]: " influxOrg
export INFLUXDB_ORG=${influxOrg:-my_org}

info "=== Configure Influx Bucket ==="
read -r -p "Enter Influx Bucket Name [example: fluent_bit]: " influxBucket
export INFLUXDB_BUCKET_ID=${influxBucket:-fluent_bit}

info "=== Configure Influx IP Address ==="
read -r -p "Enter InfluxDB IP Address [example: 192.168.1.1]: " influxIPaddress
export INFLUXDB_IP=${influxIPaddress:-192.168.1.1}

info "=== Configure Influx Port ==="
read -r -p "Enter Influx Port [example: 8086]: " influxPort
export INFLUXDB_PORT=${influxPort:-8086}

info "=== Add a Custom Location for your Container ==="
read -r -p "Enter Custom Directory [example: /var/mnt/fluent_bit]: " customDir
export FLUENT_BIT_HOME_DIR=${customDir:-/var/mnt/fluent_bit}

info "=== Configure a Unique Device Name ==="
read -r -p "Enter Unique Name [example: pc_agent_001]: " uniqueId
export UNIQUE_NAME=${uniqueId:-pc_agent_001}

info "=== Add a Custom Port for your Container ==="
read -r -p "Enter Custom Port [example: 24224]: " customPort
export FLUENT_BIT_PORT=${customPort:-24224}

info "=== What Interval Would You Like? ==="
read -r -p "Enter Interval Here [example: 1s]: " customInterval
export FLUENT_BIT_INTERVAL=${customInterval:-1s}

info "=== What Flush Interval Would You Like? ==="
read -r -p "Enter Flush Interval Here [example: 1s]: " customFlush
export FLUENT_BIT_FlUSH_INTERVAL=${customFlush:-1s}

if [[ ! -d "${FLUENT_BIT_HOME_DIR}" ]]; then
  mkdir -p "${FLUENT_BIT_HOME_DIR}"/etc
elif [[ -d "${FLUENT_BIT_HOME_DIR}" ]]; then
  rm -rf "${FLUENT_BIT_HOME_DIR}"
  mkdir -p "${FLUENT_BIT_HOME_DIR}"/etc
fi

cat <<EOF > "${FLUENT_BIT_HOME_DIR}"/etc/fluent-bit.conf
[SERVICE]
  Flush ${FLUENT_BIT_FlUSH_INTERVAL}
  Daemon off
  Log_Level debug

  @INCLUDE input_*.conf
  @INCLUDE output_*.conf
  #@INCLUDE filter_*.conf
EOF

cat <<EOF > "${FLUENT_BIT_HOME_DIR}"/etc/input_"${UNIQUE_NAME}".conf
[INPUT]
  Name cpu
  Match *
  Tag  ${UNIQUE_NAME}_cpu
  Interval ${FLUENT_BIT_INTERVAL}

[INPUT]
  Name mem
  Match *
  Tag  ${UNIQUE_NAME}_mem
  Interval ${FLUENT_BIT_INTERVAL}

[INPUT]
  Name thermal
  Match *
  Tag  ${UNIQUE_NAME}_thermal
  Interval ${FLUENT_BIT_INTERVAL}

[INPUT]
  Name proc
  Match *
  Tag  ${UNIQUE_NAME}_proc
  proc_path = /proc
  Interval ${FLUENT_BIT_INTERVAL}


[INPUT]
  Name disk
  Match *
  Tag  ${UNIQUE_NAME}_disk
  Interval ${FLUENT_BIT_INTERVAL}
  Path /

#[INPUT]
#  Name tail
#  Match *
#  Path /var/log/syslog

  # The tag whose value is incremented for the consecutive simultaneous events.
  # Sequence_Tag _seq

  # Tags to be added to all records.
  # Tags host=localhost

  # Whether to use the multi-line parser.
  # Multiline true

  # The number of lines to buffer before flushing the output.
  # Buffer_Chunk_Size 32kb

  # The type of parser to use. Available options are csv, json, and regexp.
  # Parser csv

EOF

cat <<EOF > "${FLUENT_BIT_HOME_DIR}"/etc/output_"${UNIQUE_NAME}".conf
[OUTPUT]
  Name influxdb
  Type influxdb_v2
  Host ${INFLUXDB_IP}
  Port ${INFLUXDB_PORT}
  Organization ${INFLUXDB_ORG}
  Bucket ${INFLUXDB_BUCKET_ID}
  HTTP_Token ${INFLUXDB_TOKEN}
EOF

podman run -d \
--name=fluent_bit \
--net=telemetry-net \
-p 24224:24224 \
--security-opt label=disable \
--privileged \
-v "${FLUENT_BIT_HOME_DIR}"/etc:/fluent-bit/etc \
-v "${FLUENT_BIT_HOME_DIR}"/etc/input_"${UNIQUE_NAME}".conf:/fluent-bit/etc/input_"${UNIQUE_NAME}".conf \
-v "${FLUENT_BIT_HOME_DIR}"/etc/output_"${UNIQUE_NAME}".conf:/fluent-bit/etc/output_"${UNIQUE_NAME}".conf \
fluent/fluent-bit:latest-debug```

**Comment by leonardo-albertovich** [comment]
Oh, thanks a lot, it will definitely help. Sorry about the lack of acknowledgement, I meant to do it yesterday and it slipped through the cracks.

This issue is on our work queue and one of our team members will look into it as soon as possible. Sadly I can't give you an ETA at the moment but I'll assign it to myself so I can keep track of it.

**Comment by oneofthemany** [comment]
@leonardo-albertovich do you have any guides for influxdbv2 output configuration?

**Comment by leonardo-albertovich** [comment]
I don't have experience with any version of influxdb. What I noticed while reading the documentation is that the example mentions influxdb 1.1.0 and it makes me wonder if the plugin is compatible at all with influxdb 2 or not (in which case it would be good to create an improvement proposal issue and a PR to modify the documentation to explicitly state that the output plugin does not support influxdb 2).

But don't take my word for anything because as I said, I don't know anything about influxdb.

**Comment by oneofthemany** [comment]
OK I have managed to get it working, but only when i place the [INPUT] and [OUTPUT] values within the fluent-bit.conf file

is my syntax for looking at external files correct?

```
[SERVICE]
  Flush 1s
  Daemon off
  Log_Level debug

  @INCLUDE input.conf
  @INCLUDE output.conf
  #@INCLUDE filter.conf
```

**Comment by leonardo-albertovich** [comment]
That's really interesting, I've never heard of that before and can't think of any specific part of the code that could be the root of it.

I assume you verified that in both cases the environment variables are properly replaced and the files are correct right?

**Comment by leonardo-albertovich** [comment]
That's very interesting, we definitely need to investigate this issue.

If you feel like giving it a try, I think the easiest way to do it would be setting the endpoint address and port in output plugin to a local address where you run either an http server (eg. a python script) or netcat / [openssl](https://www.openssl.org/docs/man1.1.1/man1/openssl-s_server.html).

That way we'll see if there's anything that's missing when you include the files containing the plugin specs.

An alternative approach (the one I would take) that involves building fluent-bit from source would be just putting a few `printf` calls in the output plugin but that's more involved and could be off putting if you're not a developer.

We will take a look at it as time permits but sadly I can't give you an ETA at the moment so anything else you can do would be **much** appreciated and I'm sure it would seriously expedite the process.

Thanks for the effort you've put so far!

**Comment by oneofthemany** [comment]
i have output to influxdb v2 working now but as I have said above using INPUT and OUTPUT values inside the  fluent-bit.conf

ill keep this open until you get anywhere with the use of external files if you dont mind?

**Comment by leonardo-albertovich** [comment]
Of course, that's perfect, thanks for taking the time to report this and for sharing your results!

**Comment by oneofthemany** [comment]
solved the issue - the include needs to be at the top of the fluent-bit.conf file:
```

@INCLUDE input_*.conf
@INCLUDE output_*.conf
#@INCLUDE filter_*.conf
[SERVICE]
  http_server  On
  http_listen  0.0.0.0
  http_port   2020
  flush 1
  daemon off
  log_Level debug

```
