### ISSUE TITLE
Package td-agent-bit has no Installation candidate in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by kannn012** [fluent/fluent-bit#7364]
unable to Install td-agent-bit in ubuntu 20.04 LTS. getting this error. 

Package td-agent-bit is not available, but is referred to by another package.
E: Package 'td-agent-bit' has no installation candidate

**Comment by patrick-stephens** [comment]
Not an error, that package is no longer available since 1.9.9: https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit
