### ISSUE TITLE
Can fluentbit also be shipped in binary package alongside debain/rpm/etc

### ISSUE THREAD

**Issue by 116davinder** [fluent/fluent-bit#7367]
**Is your feature request related to a problem? Please describe.**
binary package from fluentbit team like other software does. why i need this, I am using hashicorp nomad and want to run fluentbit but I have to install this as system package and its painful to maintain and upgrade it.

**Perfect Case**: I am running node-exporter as nomad job and I just download the package from there github and start the task.

**Describe the solution you'd like**
I don't how to can be done.

**Describe alternatives you've considered**
1. Alternative, I am have to  install debain package on system and upgrade with APT/YUM/etc.
2. I create my own build CI and publish somewhere.

**Additional context**
Check assets for this release https://github.com/prometheus/node_exporter/releases/tag/v1.5.0 so many kinds of binary package to use.

**Comment by patrick-stephens** [comment]
No, it relies on system libraries - it is not a static binary so one binary will not work on all platforms.

**Comment by patrick-stephens** [comment]
You could also run the containers - I switched over to that as modular packages previously rather than cope with raw binaries. 

There are plenty of options around that (e.g. running as systemd services, etc.) and it gives you a single tarball/image to run everywhere once you have a container runtime or similar installed.

**Comment by 116davinder** [comment]
@patrick-stephens, using docker/container is extra burden on the system and lot of other hacks to allow read from several paths.
Thanks for suggestion, when i opened the debain package, i saw the libs and had same thought that it won't work.
