### ISSUE TITLE
Basic auth for forward input

### ISSUE THREAD

**Issue by danifv** [fluent/fluent-bit#7374]
**Is your feature request related to a problem? Please describe.**

Similarly to connecting fluent bit and fluentd with basic auth, it'd be useful to connect fluent bit instances in a similar fashion.

**Describe the solution you'd like**

Allow basic auth (username/password) for forward input type.

**Describe alternatives you've considered**

mTLS is a working solution, but for some cases basic auth would be more convenient.

**Comment by leonardo-albertovich** [comment]
If I'm correct that would be a modification to the fluent forward protocol which should go through the appropriate channel.

I encourage you to submit a proposal in their repository.

**Comment by danifv** [comment]
> If I'm correct that would be a modification to the fluent forward protocol which should go through the appropriate channel.
> 
> I encourage you to submit a proposal in their repository.

basic auth is already supported for fluent bit -> fluentd. Would supporting fluent bit -> fluent bit really require a protocol change?

**Comment by leonardo-albertovich** [comment]
In that case probably not, my bad, sorry.
