### ISSUE TITLE
macOS build is broken

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#7375]
## Bug Report

macOS build is broken:

```
/Users/edsiper/coding/fluent-bit/lib/chunkio/src/cio_file_unix.c:521:22: error: call to undeclared function 'fallocate'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            result = fallocate(cf->fd, 0, 0, new_size);
                     ^
```

**Comment by leonardo-albertovich** [comment]
Huh, interesting, I wonder when did this happen and why. 
Were you by any chance explicitly compiling fluent-bit with `-Werror` or its clang equivalent? that doesn't change the fact that this needs to be fixed at all, I'm just curious.

**Comment by patrick-stephens** [comment]
The nightly macOS builds look fine to me: https://github.com/fluent/fluent-bit/actions/runs/4977046480/jobs/8905696029

Is this maybe an ARM specific failure or some extra config options @edsiper ?

**Comment by leonardo-albertovich** [comment]
What's particularly weird is chunkio guards that code with a preprocessor conditional that depends on `CIO_HAVE_FALLOCATE` which is tested by `CMakeLists.txt` and then only header included by the snippet is `fcntl.h` which is also included by `cio_file_unix.c` except the snippet doesn't define `_GNU_SOURCE` before including the header.

Anyway, I'll get to it eventually...
