### ISSUE TITLE
Populate from local Kubernetes metadata if API request failed

### ISSUE THREAD

**Issue by nilsalex** [fluent/fluent-bit#7379]
**Is your feature request related to a problem? Please describe.**
The Kubernetes filter does not enrich logs with Kubernetes metadata when there was a cache miss and the API request failed.

**Describe the solution you'd like**
It would be nice if in such a case the filter enriched with local metadata inferred from e.g. the name of the log file. Then we have at least namespace, pod name, and container name.

**Describe alternatives you've considered**
1) The `meta` parameter in the `pack_map_content` [function](https://github.com/fluent/fluent-bit/blob/4398840ed586171a154e992496c4a30ef92e5c55/plugins/filter_kubernetes/kubernetes.c#LL214C5-L214C5) is unused. Maybe it is possible to include metadata from this struct in case `kube_buf` is empty?

2) Alternatively, the [function](https://github.com/fluent/fluent-bit/blob/4398840ed586171a154e992496c4a30ef92e5c55/plugins/filter_kubernetes/kube_meta.c#L1530) `flb_kube_meta_get`, called directly from the [function](https://github.com/fluent/fluent-bit/blob/4398840ed586171a154e992496c4a30ef92e5c55/plugins/filter_kubernetes/kubernetes.c#L537) `cb_kube_filter`, could populate the output buffer with the local metadata if otherwise there was no metadata found.

**Additional context**
Maybe I'm overlooking something and this is by design! Then I would be glad to hear why this is :-)

**Comment by patrick-stephens** [comment]
Potentially you can do this already with a simple LUA/modify filter to add this information via the filename as you say.

I'm not sure we would want to default it to do this, e.g. it may not be clear it is failing and you're only getting partial K8S metadata so you may want to opt into it either with an explicit extra filter or option. Particularly if you start using some of the features that rely on K8S annotations.
