### ISSUE TITLE
Pushing Data to Remote Kafka

### ISSUE THREAD

**Issue by prashantvicky** [fluent/fluent-bit#738]
## Bug Report

**Describe the bug**

1) Is Kafka Output plugin is discontinued 
When i tried 

> ./fluent-bit -i cpu -o kafka -p brokers=10.84.118.83:9092 -p topics=logkafka

**Error: Invalid output target. Aborting**

2) I wanted to know if we can push data to Remote Kafka Server or not (What i mean is fluent bit is  deployed in Cluster A and i wanted to push data To Remote Server B )
3) If not kafka out plugin then , is rest-kafka plogin will work?

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by edsiper** [comment]
If you don't have Kafka output plugin available means it was not enabled/included at build time (if you built Fluent Bit from scratch).

All td-agent-bit packages (ubuntu/debian/centos) have Kafka support. When building from scratch append the option -DFLB_OUT_KAFKA=On to your cmake arguments.
