### ISSUE TITLE
Filter `record_modifier` writes wrong key-value if key is `tag`

### ISSUE THREAD

**Issue by mariapoliss** [fluent/fluent-bit#7397]
## Bug Report

I have systemd input and send output to file. I need to add key-value "tag":"systemd" for further purposes (to send messages to graylog and make some pipeline rules in graylog). I use `record_modifier` filter to add the tag. But it misses one letter and write key-value as "tag":"ystemd". But if I name key for example "tagtest" it writes correctly without missing the letter in the value.

And that\`s interesting, if I write in configuration value with double s `Record tag ssystemd` key-value added correctly in log message.

**To Reproduce**

Steps to reproduce the problem:

- Add to configuration:
```
    [INPUT]
        Name              systemd
        Tag               systemd
        Path              /var/log/journal
        DB                /var/log/journal.db
        Read_from_Tail    False
        Strip_Underscores True
    [FILTER]
        Name   record_modifier
        Match  systemd
        Record tag systemd
    [FILTER]
        Name   record_modifier
        Match  systemd
        Record tagtest systemd
    [OUTPUT]
        Name file
        Match systemd
        Path /fluent-bit
```
- Run fluent bit of version 2.0.6-debug with the configuration
- Go to cmd of fluent bit container and execute `cat /fluent-bit/systemd`

```
systemd: [1684232964.534306049, {"COMM":"crio","EXE":"/usr/bin/crio","SYSTEMD_INVOCATION_ID":"3ea639d877d84198b54d49ff121eff7d","CMDLINE":"/usr/bin/crio","SYSTEMD_UNIT":"crio.service","BOOT_ID":"820f370e960643c9ba173d72679b1dbb","MACHINE_ID":"c5f993546b0b4a39b1d94e5e7edb57c4","PRIORITY":"6","hostname":"fluentbit-xgqsd","GID":"0","SYSTEMD_SLICE":"system.slice","CAP_EFFECTIVE":"1ffffffffff","UID":"0","SYSTEMD_CGROUP":"/system.slice/crio.service","TRANSPORT":"stdout","HOSTNAME":"node-local-1","SYSLOG_FACILITY":"3","SELINUX_CONTEXT":"system_u:system_r:container_runtime_t:s0","tag":"ystemd","STREAM_ID":"9dc27547a8be4ecfa177b318ece31d6d","tagtest":"systemd","SYSLOG_IDENTIFIER":"crio","log":"time=\"2023-05-16 10:29:24.534208232Z\" level=warning msg=\"falling back to loading from existing plugins on disk\"","PID":"1523"}]
```

**Expected behavior**
Log message contains key-value: "tag":"systemd".
**Actual behavior**
Log message contains key-value: "tag":"ystemd".

**Your Environment**

* Version used: fluent-bit 2.0.6
* Environment name and version: kubernetes v1.25.8

**Comment by leonardo-albertovich** [comment]
I couldn't reproduce this issue with 2.1 HEAD, 2.0 HEAD or 2.0.6 so I think we will need a bit more information about your system in order to validate this issue. 

My configuration file looks like this : 

```
[SERVICE]
    flush 1
    grace 1
    log_level info

[INPUT]
    Name              systemd
    Tag               systemd
    Path              /var/log/journal
    DB                journal.db
    Read_from_Tail    False
    Strip_Underscores True

[FILTER]
    Name   record_modifier
    Match  systemd
    Record tag systemd

[FILTER]
    Name   record_modifier
    Match  systemd
    Record tagtest systemd

[OUTPUT]
    Name file
    Match systemd
    Path .
```

And my output like this : 

```
systemd: [1665217984.124382000, {"PRIORITY":"6","SYSLOG_FACILITY":"3","TID":"3337","CODE_FILE":"src/resolve/resolved-manager.c","CODE_LINE":"333","CODE_FUNC":"on_clock_change","SYSLOG_IDENTIFIER":"systemd-resolved","MESSAGE":"Clock change detected. Flushing caches.","TRANSPORT":"journal","PID":"3337","UID":"101","GID":"103","COMM":"systemd-resolve","EXE":"/usr/lib/systemd/systemd-resolved","CMDLINE":"/lib/systemd/systemd-resolved","CAP_EFFECTIVE":"2000","SELINUX_CONTEXT":"unconfined\n","SYSTEMD_CGROUP":"/system.slice/systemd-resolved.service","SYSTEMD_UNIT":"systemd-resolved.service","SYSTEMD_SLICE":"system.slice","SYSTEMD_INVOCATION_ID":"76aa55e52c5a4799b5c5a76b4aee308d","SOURCE_REALTIME_TIMESTAMP":"1665217984124369","BOOT_ID":"42c8290ae923486283449c3d21e60abc","MACHINE_ID":"bea10013d8e84a1b850e7ee2ab8146b6","HOSTNAME":"cucaracha","tag":"systemd","tagtest":"systemd"}]
```

After running fluent-bit for a few seconds I got about 120k lines in my output file but none of them had the issue you are reporting.

Could you please try the latest fluent-bit 2.1 release or at least the latest fluent-bit 2.0 release and report your results?

**Comment by mariapoliss** [comment]
Thank you for quick response!
Sorry, it was my fault. I forgot that I have lua script that replaces "/" with "." in `tag` and I found a bug here in the script.

Now key-value added correctly.

Thank you!

**Comment by leonardo-albertovich** [comment]
No worries, I'm glad it's working now.
