### ISSUE TITLE
Maximum filestorage buffer size

### ISSUE THREAD

**Issue by federicobarera** [fluent/fluent-bit#7402]
**Is your feature request related to a problem? Please describe.**

During large network/connectivity outages between fluentbit and the telemetry backends, in our circumstances, would be better to buffer logs on disk until a maximum file size is reached. At that point, interrupting tailing logs as per default memory only behavior. At the moment the storage.total_limit_size removes old chunks from filesystem, which is not the behavior we'd want. 

**Describe the solution you'd like**

Have a setting to limit the overall file storage size, at which point tailing/ingestion will suspend as per memory behavior.

**Describe alternatives you've considered**

Using memory only, althought we would prefer having a disk buffer instead of keep suspending log ingestion.

**Comment by JeffLuoo** [comment]
Do you mean `storage.pause_on_chunks_overlimit`?

Ref: https://docs.fluentbit.io/manual/administration/buffering-and-storage#filesystem-buffering-to-the-rescue

**Comment by federicobarera** [comment]
@JeffLuoo 

> If storage.pause_on_chunks_overlimit is enabled (default is off), the input plugin will be paused upon exceeding storage.max_chunks_up. Thus, with this option, storage.max_chunks_up becomes a hard limit for the input. When the input is paused, records will not be ingested until it is resumed. For some inputs, such as TCP and tail, pausing the input will almost certainly lead to log loss. For the tail input, Fluent Bit can save its current offset in the current file it is reading, and pick back up when the input is resumed.

If I understood correctly, with `storage.pause_on_chunks_overlimit` + `storage.type  filesystem`, the file size can only grow up to the max memory used by fluentbit. If eg. max_chunks_up * chunk size = 256MB, then max file size will be 256MB. The request here is to have an upper limit for the storage file to also save `down` chunks like when `storage.pause_on_chunks_overlimit = false`, but stops to an upper limit of (eg. 2GB).

That would: 
1. Keep max memory used under control (max_chunks_up)
2. Buffer logs to file until a cap is reached, that would keep max storage predictable
3. would stop ingesting logs when buffer is reached

**Comment by federicobarera** [comment]
Maybe also similar to this: https://github.com/fluent/fluent-bit/issues/7461
