### ISSUE TITLE
Logs dropped upon pod restart

### ISSUE THREAD

**Issue by federicobarera** [fluent/fluent-bit#7406]
## Bug Report

**Describe the bug**

We notice that upon fluent-bit pods restart (new deployment, rebalancing, etc) an amount of logs is lost. We ran multiple tests with multiple configuration options obtaining the same outcome

**To Reproduce**

1. Multi node k8s setup (eg. 3).
2. Helm install (version and configuration below), installed as daemonset
3. Target application generating constant amount of logs or
4. Temporary pod with load eg `watch -n0.3 curl http://service`
5. Force pod restart `k delete pod -l app.kubernetes.io/instance=fluent-bit`

Given the rewriters, a set of different log types

```
a normal text log
```
```
{ "Source": "Test", "Log": "text" }
```

**Expected behavior**

Logs in flights are flushed and/or with `filesystem` setup, no logs are lost

**Screenshots**

We tried the following configurations multiple times obtaining the same output:

Input Storage Type: memory|filesystem
Emitters Storage Type: memory|filesystem

EDIT:
The picture here aggregates by the time the log is generated by the producing app, not the ingestion time of the log itself. We should see a consistent amount of logs per minute, independently of how long fluentbit was disconnected.

EDIT2:
Removing the rewriter filters, the same behavior persist, possibly identifying a problem in the es output plugin/config

![image](https://github.com/fluent/fluent-bit/assets/6658124/04780c84-f4a1-437b-9e4e-b70f93a1ea58)

**Your Environment**

* Version used: Helm Chart fluent-bit-0.24.0, Version 2.0.9
* Configuration: 

```
[SERVICE]
      Daemon Off
      Flush 1
      Log_Level info
      Parsers_File parsers.conf
      Parsers_File custom_parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port 2020
      Health_Check On
      
      storage.path /var/log/flb-storage/
      storage.sync full 
      storage.checksum off 
      storage.backlog.mem_limit 5M
      storage.max_chunks_up 128
      
      scheduler.base 3
      scheduler.cap 1500
    
    [INPUT]
      Name              tail
      Path              /var/log/containers/*.log
      Parser            cri1
      Tag               kube.*
      Skip_Long_Lines   Off
      storage.type      filesystem

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log           On
        Merge_Log_Trim      On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Keep_Log            On
        Annotations         Off
    
    [FILTER]
        Name  rewrite_tag
        Match kube.*
        emitter_storage.type      filesystem
        Rule  $kubernetes['container_name'] ^(fluent-bit)$  fluent.$TAG  false
    
    [FILTER]
        Name rewrite_tag
        Match kube.*
        emitter_storage.type      filesystem
        Rule  $Source ^(.+)$  custom.$TAG  false
    


    [OUTPUT]
      Name                      es
      Match                     custom.*
      Host                      ${ES_HOST}
      Port                      443                                                                                                                               
      HTTP_User                 ${ES_USER}                                                                                                   
      HTTP_Passwd               ${ES_PWD}     
      Index                     ${ES_TELEMETRY_INDEX}
      Logstash_Format           Off
      Retry_Limit               10
      Suppress_Type_Name        On
      Replace_Dots              On
      Trace_Error               Off
      Trace_Output              Off
      Tls                       On
      log_suppress_interval     10s
      storage.total_limit_size  300M

    
```
* Environment name and version (e.g. Kubernetes? What version?):

* **Kubernetes (AKS) 1.25.5**
* Server type and version:  
* Operating System and version: Ubuntu 22

**Comment by patrick-stephens** [comment]
You have no `DB` configured so there is no persistence for the `tail` input so it will only see logs added after it starts, i.e it functions similar to `tail -f`.

See https://docs.fluentbit.io/manual/pipeline/inputs/tail#keep_state

**Comment by federicobarera** [comment]
Thank you for hint @patrick-stephens . I started to look at possible issues with the input around the time you posted the comment here. I can confirm it works as expected
