### ISSUE TITLE
For exclude the logs from the ns we tried to annotated this command (kubectl annotate pods --namespace=test-ui --all fluentbit.io/exclude='true' ) but no luck even though the logs are getting generated to cloudwatch. could anyone help on this?

### ISSUE THREAD

**Issue by harsha20494** [fluent/fluent-bit#7414]

**Comment by harsha20494** [comment]
![image](https://github.com/fluent/fluent-bit/assets/68779338/f613b2b1-f309-4e0e-a0a4-45e4b6113f47)
Annotations:      fluentbit.io/exclude: true
                  kubernetes.io/psp: eks.privileged
Status:           Running

**Comment by patrick-stephens** [comment]
Are you doing this dynamically, i.e. after the pods have started and Fluent Bit is already tailing them? I think Fluent Bit caches the metadata so it will not see the annotations updated, you need to apply them at pod creation.
