### ISSUE TITLE
Bug in tag_compose?

### ISSUE THREAD

**Issue by yann-soubeyrand** [fluent/fluent-bit#742]
## Bug Report

I think the line
`     if (p) {`
at https://github.com/fluent/fluent-bit/blob/f4c7329f0373a822b956232565bfc30bd50946cb/plugins/in_tail/tail_file.c#L333 should rather be
`    if (*p) {`
However, this has no consequence other than executing useless code.

**Comment by yann-soubeyrand** [comment]
I think the same applies here https://github.com/fluent/fluent-bit/blob/399953ae372f119b8a1eff1c0a96ad3a317ce2ee/plugins/in_systemd/systemd.c#L54

**Comment by edsiper** [comment]
thanks for the report and fixes. changes merged.
