### ISSUE TITLE
Connection to Elastic search inside private n/w

### ISSUE THREAD

**Issue by bikramtpa** [fluent/fluent-bit#7435]
I've a question why fluentbit connection to elastic search is not working.

I installed fluent bit via helm chart and overridden the tag with 2.1.2-debug.The kubernetes cluster is a Azure managed kubernetes cluster inside private network where the private n/w also include a VM where an Elastic search is installed with only private IP 10.2.129.4.
 
When I telnet from the fluent bit container in AKS pod to 10.2.129.4 9200 then it gets connected however if does not work and the fluent bit logs displays error about connection issue. I use IP instead of domain name.

Fluentbit configuration in config map output sample
```
    [OUTPUT]
        Name es
        Match kube.*
        Host 10.2.129.4
        Logstash_Format On
        Retry_Limit False

    [OUTPUT]
        Name es
        Match host.*
        Host 10.2.129.4
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
```

Telnet works - 
```
kubectl exec -it fluent-bit-ns2st -- /bin/sh
# telnet 10.2.129.4 9200
Trying 10.2.129.4...
Connected to 10.2.129.4.
Escape character is '^]'.
```

Fluent bit Error log:
```
[2023/05/18 15:01:52] [error] [http_client] broken connection to 10.2.129.4:9200 ?
[2023/05/18 15:01:52] [ warn] [output:es:es.0] http_do=-1 URI=/_bulk
[2023/05/18 15:01:52] [ warn] [engine] failed to flush chunk '1-1684421580.498594689.flb', retry in 98 seconds: task_id=194, input=tail.0 > output=es.0 (out_id=0)
```

**Expected behavior**
Fluent bit container in AKS cluster should stream the logs to ElasticSearch in another VM with private ip in same private n/w.

**Comment by patrick-stephens** [comment]
Can you get more debug out, e.g. `log_level debug`? Also, no TLS or anything related to auth, etc.?

What happens if you try to curl the actual Elasticsearch API directly rather than just telnet to a port, i.e. is the API accepting things or are we missing something?

**Comment by bikramtpa** [comment]
@patrick-stephens  thanks for your comment. 
yes it turns out that the ssl authentication is the issue. For now I've disabled it and seems to work.
