### ISSUE TITLE
TCP listener input plugin creating log spam filling up disk in few (2 - 3 hours)

### ISSUE THREAD

**Issue by priyankarking** [fluent/fluent-bit#7439]
We encountered a problem where the file descriptor (FD) limit of Fluent Bit was reached, and as a result, we started observing a massive influx of error logs, particularly from the TCP input plugin. We suspect that Fluent Bit began generating an increasing number of file descriptors because the component responsible for accepting the data(at port 5001, which what we have configured in output plugin) was either not functioning or stuck in some way.

We first saw these below logs started coming when FD limit was reached. **During this time TCP input plugin was not used.**

Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [output:forward:forward.1] no upstream connections available
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [net] coult not create client socket, retrying
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [output:forward:forward.1] no upstream connections available
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [net] coult not create client socket, retrying
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [output:forward:forward.1] no upstream connections available
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [net] coult not create client socket, retrying
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [output:forward:forward.1] no upstream connections available
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [  Error] timerfd: Too many open files, errno=24 at /tmp/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [error] [sched]  'retry request' could not be created. the system might be running out of memory or file descriptors.
Apr 14 06:25:22 vm4 td-agent-bit[16481]: [2023/04/14 06:25:22] [ warn] [engine] retry for chunk '16481-1681453518.322193481.flb' could not be scheduled: input=tail.1 > output=forward.1

**These logs were coming regularly but rate of these logs was acceptable.**
Later when FD limit was already breached and someone tried to connect to TCP input plugin we saw millions of logs error coming because of TCP input plugin. 
Apr 13 17:46:17 vm4 td-agent-bit[4856]: accept4: Too many open files
 Apr 13 17:46:17 vm4 td-agent-bit[4856]: [2023/04/13 17:46:17] [error] [input:tcp:listener] could not accept new connection
 Apr 13 17:46:17 vm4 td-agent-bit[4856]: accept4: Too many open files
 Apr 13 17:46:17 vm4 td-agent-bit[4856]: [2023/04/13 17:46:17] [error] [input:tcp:listener] could not accept new connection

Anybody aware why tcp input plugin is emitting millions of logs of same type? is there any way to limit these logs...its causing OS disk full issue.

Increasing the limit of FD might not work here as ideally our service dont use that many FD....we only reach FD limit when the component accepting the data is not working or stuck. So may be that's the reason fluent bit tries to open more and more socket inorder to preserve data in TCP buffers and hence increasing file descriptors.

My main ask here is how do I limit these error logs from TCP input plugin as these are coming very frequently and keep on coming and filling up whole disk space within 2 - 3 hours.

We should see how we can minimize the millions of logs to a way more less error logging when this scenario hits.

We should also see why the TCP input plugin is attempting to reconnect(trying to make socket FD in this case) in a very tight loop? Is there a parameter available to configure the retry interval for the TCP input plugin? Currently, it appears to retry immediately and continue trying, resulting in high CPU usage.

OS:"Ubuntu 18.04.6 LTS

Version used: I tried both 1.9.10 and 2.2

Config used:

[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  labs.conf
    HTTP_Server   On
    HTTP_Listen   127.0.0.1
    HTTP_PORT     2020

[INPUT]
    Name         tail
    Path         /var/opt/labs/log/*.log
    Exclude_Path PARSED_FILES
    Path_Key     On
    Tag          tag1

[INPUT]
    Name       tail
    Path_Key   On
    Path       /var/opt/agent/agent*.log
    Tag        tag3
    Parser     agent

[INPUT]
    Name       tail
    Path_Key   On
    Path       /var/opt/agent/telemetry*.log
    Tag        tag4
    Parser     agent

[INPUT]
    Name            tail
    Path_Key        On
    Path            /var/log/*.log, /var/log/apt/*.log, /var/log/cloud/*/*.log, /var/log/clamav/*.log
    Exclude_Path    PARSED_VARLOG_FILES
    Tag             tag1

 [INPUT]
     Name        tcp
     Listen      127.0.0.1
     Port        1234
     Chunk_Size  32
     Buffer_Size 64
     Format      json
     Tag         tag2
     Alias       listener

[FILTER]
    Name       modify
    Match      cloud*
    Rename     @m message
    Rename     @l level
    Rename     @x exception
    Remove     @i

 [FILTER]
     Name       grep
     Match      tag2
     Exclude    $new_int['trgp'] 3333
     Exclude    $close['trgp'] 3333
     Alias      internal_log_filter

 [FILTER]
     Name       modify
     Match      tag2
     Set Region LOG_REGION
     Alias      set_region

 [FILTER]
     Name       modify
     Match      tag2
     Condition  Key_Exists new
     Set action new
     Alias      set_new_action

 [FILTER]
     Name       modify
     Match      tag2
     Condition  Key_Exists close
     Set action close
     Alias      set_close_action

 [FILTER]
     Name           nest
     Match          tag2
     Operation      lift
     Nested_under   new_conn
     Alias          convert_event_new_to_flat_schema

 [FILTER]
     Name           nest
     Match          tag2
     Operation      lift
     Nested_under   close_conn
     Alias          convert_event_close_to_flat_schema

[OUTPUT]
    Name       forward
    Host       127.0.0.1
    Port       5001
    Match      cloud*

[OUTPUT]
    Name       forward
    Host       127.0.0.1
    Port       5001
    match      tag1

 [OUTPUT]
     Name       forward
     Host       127.0.0.1
     Port       5001
     match      tag2
     Alias      output
    
   
   
  
![Screenshot_2](https://github.com/fluent/fluent-bit/assets/14851241/8b3b6db7-b229-4f01-b8db-2657e457e734)

  During issue time we saw many open TCP connection between td-agent-bit and port 5001 which is the port we have configured in output plugin.
  Note that during this time no data was coming from TCP input plugin. The data was coming mostly from other input plugins. 
![MicrosoftTeams-image (5)](https://github.com/fluent/fluent-bit/assets/14851241/80f9d3a2-f8eb-4034-af75-b16bfd32a050)

** To reproduce high rate of error logs from TCP input plugin follow below step:**

Checking the current soft and hard limit of FDs for td-agent-bit:
cmd:
prlimit -p <PID> --nofile

Now check the current FDs used by td-agent-bit:
cmd:
for x in `ps -eF| awk '{ print $2 }'`;do echo `ls /proc/$x/fd 2> /dev/null | wc -l` $x `cat /proc/$x/cmdline 2> /dev/null`;done | sort -n -r | head -n 20 | grep td-agent-bit
Now set the softlimit and hardlimit of td-agent-bit to “current FD usage” + 3

Now run: “sudo systemctl daemon-reload” and then run “sudo systemctl restart td-agent-bit.service”

Again check the soft and hard limit using cmd “prlimit -p <PID> --nofile” …it should be equal to what you have set.

Open another terminal for same VM and run a script which try to send logs to tail input plugin at high rate.

Now you can check the FD usage of td-agent-bit, it should have reached the limit you have set.
If that’s so, now you will start seeing logs like below in syslog file or you can use this cmd to check them for a particular time period:
sudo journalctl -u td-agent-bit.service --since "1 minutes ago"

Logs:
Apr 15 15:06:28 vm4 td-agent-bit[16481]: [2023/04/15 15:06:28] [  Error] timerfd: Too many open files, errno=24 at /tmp/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208
Apr 15 15:06:28 vm4 td-agent-bit[16481]: [2023/04/15 15:06:28] [error] [sched] a 'retry request' could not be scheduled. the system might be running out of memory or file descriptors. The scheduler will do a retry later.
Apr 15 15:06:28 vm4 td-agent-bit[16481]: [2023/04/15 15:06:28] [  Error] timerfd: Too many open files, errno=24 at /tmp/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208
Apr 15 15:06:28 vm4 td-agent-bit[16481]: [2023/04/15 15:06:28] [error] [sched] a 'retry request' could not be scheduled. the system might be running out of memory or file descriptors. The scheduler will do a retry later.
Apr 15 15:06:28 vm4 td-agent-bit[16481]: [2023/04/15 15:06:28] [  Error] timerfd: Too many open files, errno=24 at /tmp/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208

Note that you will not see TCP input plugin related log spam unless you try to connect to it:
cmd:
echo "Hello, server!" | nc 127.0.0.1 1234
After running and canceling above cmd you should also see below kind of logs using this cmd:
sudo journalctl -u td-agent-bit.service --since "1 minutes ago"| grep audit

Apr 15 17:43:16 vm4 td-agent-bit[16481]: [2023/04/15 17:43:16] [error] [input:tcp:listener] could not accept new connection
Apr 15 17:43:16 vm4 td-agent-bit[16481]: accept4: Too many open files
Apr 15 17:43:16 vm4 td-agent-bit[16481]: [2023/04/15 17:43:16] [error] [input:tcp:listener] could not accept new connection
Apr 15 17:43:16 vm4 td-agent-bit[16481]: accept4: Too many open files
Apr 15 17:43:16 vm4 td-agent-bit[16481]: [2023/04/15 17:43:16] [error] [input:tcp:listener] could not accept new connection

[Slack Message](https://fluent-all.slack.com/archives/C0CTQGHKJ/p1683701639201519?thread_ts=1683701639.201519&cid=C0CTQGHKJ)

**Comment by patrick-stephens** [comment]
You have an error here and you potentially will lose data so reporting that is vital I think.
Ultimately resolving the underlying error should be the priority, I think anything else is just hiding failures.
Logs should always be rotating and [using a separate partition](https://static.open-scap.org/examples/guide-checklist.html#xccdf_org.ssgproject.content_group_configure_auditd_data_retention) as well for best practice to prevent this kind of issue with any tool.

Saying that, a state-based error report limited to "we're now in an error state" and indicated that via metrics too would be nice. There is the recent log suppression functionality too although that's only recently introduced and will reduce rather than remove logs entirely.

I think something was asked on Slack too around this: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1683701639201519
In that I indicated how to potentially resolve the logging issue via the [systemd unit approach](https://serverfault.com/a/858845). However, I'll say again: there is an error that will cause you problems potentially and just hiding it is not the best idea.

There are also ways to not log things, e.g. use `log_level off` in the output plugin, but then you lose all information.

**Comment by leonardo-albertovich** [comment]
Fluent-bit doesn't deliberately keep connections open to hold data in the connection buffer. It does however not forcefully close inactive connections so the clients sending that data might be just not properly closing the connections (which is a common error) which means those will only be closed when the kernel decides to according to the systems configuration.

There is a setting named `net.io_timeout` which you could set to a reasonable value in order to terminate those dangling connections.

**Comment by priyankarking** [comment]
@patrick-stephens : 
>>Ultimately resolving the underlying error should be the priority, I think anything else is just hiding failures. You need to tune your buffering and retries to cope with what you want to do during your outage.

Yes. 
But finding that issue and resolving it will take time. And also, it does not guarantee that resolving that issue will not result in having similar issue in future which can again trigger this log spam from fluent bit.

>>You need to tune your buffering and retries to cope with what you want to do during your outage.
Can you explain more on this.

>>Logs should always be rotating
We are using logrotation. But the log spam is massive and filling up the disk so quickly even before our logrotate job can handle it.

Also, these massive log spamming result in high CPU usage from fluent bit as millions of logs are written so quickly in a tight loop.

>>There is the recent log suppression functionality too although that's only recently introduced and will reduce rather than remove logs entirely.
As I mentioned and @leonardo-albertovich also mentioned:
Turning off logs from plugin or suppressing logs from plugin will only be applicable to this log:
Apr 13 17:46:17 vm4 td-agent-bit[4856]: [2023/04/13 17:46:17] [error] [input:tcp:listener] could not accept new connection

Not this log (which does not seems to be coming from any plugin):
Apr 13 17:46:17 vm4 td-agent-bit[4856]: accept4: Too many open files

I have tried with latest fluent bit version, log spam continues to be issue there aswell.

**Comment by priyankarking** [comment]
@leonardo-albertovich : 

>>There is a setting named net.io_timeout which you could set to a reasonable value in order to terminate those dangling connections.

this is for output plugin ?

**Comment by leonardo-albertovich** [comment]
Those are for the input plugin.

**Comment by priyankarking** [comment]
As per internal discussing we are not opting for totally removing logging for fluent bit. So option this option:
StandardError=null / StandardOutput=null is not something we will opt for.

**Comment by priyankarking** [comment]
>>accept4: Too many open files is an error reported by system libraries so redirecting stderr will hide it - Leo indicated this above in that it does not come from Fluent Bit but directly via perror.

Although this log does not come from fluent bit, but it triggered by fluent bit.

>>The logs are legitimately reporting errors but I appreciate it may be at a high rate and there is no good solution currently that will reduce that rate other than resolving the error.

Yes the rate is super high. which is not expected. This github issue is raised inorder to control that log spam.
There were error from other plugin also during this the time of issue like tail plugin were also throwing similar error logs but their rate was acceptable. But TCP input plugin error log rate is not acceptable and we should look how we can control it.

**Comment by leonardo-albertovich** [comment]
@priyankarking, we understand that this is causing issues to you and that's why as a compromise we suggested a series of changes you could make to your deployment to minimize the impact.

The next logical step here would be for you to submit a pull request removing [these](https://github.com/fluent/fluent-bit/blob/master/src/flb_network.c#L1704-L1706) lines.

Please provide a detailed explanation in your PR of why these are redundant and tag me so I can review it.

If you have any questions about the PR process let me know, I'd be glad to help.

**Comment by priyankarking** [comment]
@leonardo-albertovich  : I am not aware to contribute to fluent bit repo.
Pls tell me all the info.

I though fluent bit developer will look into it and try to make changes accordingly.

**Comment by leonardo-albertovich** [comment]
You can get started with this entry from the documentation : https://docs.fluentbit.io/manual/development/developer-guide#development-environment

Basically, all you have to do is fork fluent-bit, create a new branch, delete those three lines, make a commit following the style and then create a pull request also following the style (which will be shown to you once you start the process but you can also check other open PRs for reference).

And if you have questions about the process while you do it you can ask and we will guide you.

**Comment by priyankarking** [comment]
thanks @leonardo-albertovich.

Should we also want someone who is more familiar with code to check why TCP input plugin is trying to reconnect in very tight loop. Is there any parameter by which we can configure the retry interval for TCP input plugin, as now its seems it retry immediately and keep on trying causing high CPU usage.

**Comment by leonardo-albertovich** [comment]
No, if your clients are leaving dangling connections the answer is to fix the client code or set `net.io_timeout` as I instructed you to.

**Comment by priyankarking** [comment]
There seems to be some missing context. Most of the file descriptors were being consumed by another output plugin because the destination was not reading the data. This particular output plugin was receiving data from other Tail input plugins we have. I believe this led to the fluent bit output plugin creating more and more sockets (file descriptors), eventually reaching the file descriptor limit for fluent bit. It's important to note that during this time, the TCP input plugin was not even being used.

Once the file descriptor limit is reached, if a client tries to connect to the TCP input plugin, it starts generating these log messages indefinitely, even when the client has stopped attempting to connect to the TCP input plugin.

The configuration setting you provided is for the TCP input plugin. However, it is not relevant to the issue until the file descriptor limit is reached.

Additionally, I couldn't find the "net.io_timeout" setting in the official documentation ?

Also could you pls reopen the issue, as it is not resolved yet.

**Comment by leonardo-albertovich** [comment]
Well, this paints a very different image than the one your original report does so please update that report with a more in depth explanation of the case and a proper copy of your configuration file so we know what we are working with, otherwise we won't be able to effectively look into it.

**Comment by priyankarking** [comment]
@leonardo-albertovich : I have tried to add more details. I have also asked my team colleague to add more information incase I have missed something.

**Comment by priyankarking** [comment]
@leonardo-albertovich : Forget to mention I have added details in at top in issue description.

**Comment by TimLovellSmith** [comment]
Given that the log message is "no upstream connections available" with no further suffix, and your config file using the forward pugin I imagine that all those log errors are coming from cb_forward_flush in forward.c while it tries to forward to tcp port 5001.

``
[OUTPUT]
Name forward
```

**Comment by priyankarking** [comment]
@leonardo-albertovich : Any comments based on updated information?

**Comment by leonardo-albertovich** [comment]
Not yet, I haven't been able to dedicate time to this issue.
I'm somewhat surprised that your forward connections are not being closed (is there an issue on the other side?) .
Just as a test could you set `net.io_timeout` to `10` in your output plugin?
I think I'll be able to put some time on this later this week since I'm starting with a batch of windows related issues.

**Comment by priyankarking** [comment]
>>Just as a test could you set net.io_timeout to 10 in your output plugin?

We can not repro. this issue as it pops up in an adhoc manner.
So not sure we can set net.io_timeout to 10 and retry.
For now we can only repro the log spam by TCP listener for which I have already shared information.

>>I think I'll be able to put some time on this later this week since I'm starting with a batch of windows related issues.

Sure. Lets get back to this whenever you get time.

**Comment by priyankarking** [comment]
@leonardo-albertovich  : Any update ?

**Comment by priyankarking** [comment]
@leonardo-albertovich  : Is there any timeline by which you would be able to look into  it ?

**Comment by priyankarking** [comment]
@leonardo-albertovich : Is there any update we can have now ? Atleast a date by which you would be able to help with this issue ?

**Comment by priyankarking** [comment]
@leonardo-albertovich : any updates ?
