### ISSUE TITLE
Support backpressure with `Mem_buf_limit` when using `filesystem` storage

### ISSUE THREAD

**Issue by braydonk** [fluent/fluent-bit#7461]
**Is your feature request related to a problem? Please describe.**
When using `filesystem` storage, the backpressure facilitations such as pausing the input plugins when limits are reached appear to be specifically disabled under `filesystem` storage.
https://github.com/fluent/fluent-bit/blob/f2b2efe3a960ca3597dead991137ab22ef986df3/src/flb_input_chunk.c#L1407-L1409

**Describe the solution you'd like**
It would be great if this limitation could be removed. It is a bit confusing that there is no backpressure support only in filesystem storage and it isn't documented as far as I have found.

**Additional context**
Perhaps this made sense at some point in the past, but today it is hard to tell if there's a reason this is disabled. The data that is actually used for the mem buf overlimit check (`in->mem_chunks_size`) seems to be set properly even while using filesystem storage.

**Comment by PettitWesley** [comment]
+1 on this, this is something that really confused both myself and our customers. 

The current state is that `storage.max_chunks_up` controls memory when you use `storage.type filesystem`: https://github.com/aws-samples/amazon-ecs-firelens-examples/tree/mainline/examples/fluent-bit/oomkill-prevention
