### ISSUE TITLE
fluent-bit metric proc_records < rdkafka.queue.buffering.max.messages still lose logs

### ISSUE THREAD

**Issue by farmerx** [fluent/fluent-bit#7467]

**Comment by farmerx** [comment]
"proc_records": 23873460，
"proc _bytes": 16156883362,
"errors": 0,
"retries": 919,
"retries_failed": 7,
"dropped _records": 31285,
"retried_records": 2648730

**Comment by farmerx** [comment]
rdkafka.queue.buffering.max.messages 2000000000
rdkafka.queue.buffering.max.kbytes 2000000000

**Comment by leonardo-albertovich** [comment]
Please update your original issue with a proper description of the issue and all the required context, so anyone who looks at this can make sense of it.
