### ISSUE TITLE
Regarding whether the tail plugin adopts multithreading

### ISSUE THREAD

**Issue by suppersam1** [fluent/fluent-bit#7468]
When I insert a large amount of data, multiple log files will be generated at the same time. When the next round of listening arrives, tail seems to have opened multiple threads to read data from multiple log files simultaneously. Is there any way to enable it to read one by one in chronological order

**Comment by leonardo-albertovich** [comment]
We would need to see your configuration file to make a proper recommendation.

First, just so we are on the same page, the tail input plugin does not create any threads other than the one thread that's created when `threaded` is set to `on`.

Then, if what you mean is that the plugin starts ingesting from all available files at the same time and what you want is for it to consume them in their entirety, then that's not really possible and for those outliers I would set up a secondary tail instance but there isn't much we can say about it without having a proper understanding of your use case.

**Comment by suppersam1** [comment]
> We would need to see your configuration file to make a proper recommendation.
> 
> First, just so we are on the same page, the tail input plugin does not create any threads other than the one thread that's created when `threaded` is set to `on`.
> 
> Then, if what you mean is that the plugin starts ingesting from all available files at the same time and what you want is for it to consume them in their entirety, then that's not really possible and for those outliers I would set up a secondary tail instance but there isn't much we can say about it without having a proper understanding of your use case.


[INPUT]
    name                tail
    path                /root/logs/postgresql*.log
    Buffer_Max_Size     5M
    tag                 pglog
    multiline.parser    multiline-pglog
    Rotate_Wait         30
    db                  /var/lib/fluentbit/pg.db

This is my configuration file. 

Here are my actions:
1. Insert a large amount of data into the pg database
2. PG database generates multiple log files like this：postgresql-2023-05-24_193724.log postgresql-2023-05-24_193819.log
3. The next scan of tail plugin is coming, adding multiple log files to the observation queue.
4. I found that the tail plugin starts reading data from multiple log files at the same time, resulting in a disordered chronological order of the logs
