### ISSUE TITLE
Improve Python mutltiline support for PEP657/Python3.11

### ISSUE THREAD

**Issue by peschmae** [fluent/fluent-bit#7478]
**Is your feature request related to a problem? Please describe.**
Starting with Python 3.11 tracebacks are more fine grained and give a hint where an error occurred. 

An example of a new traceback looks like this
```
Traceback (most recent call last):
  File "distance.py", line 11, in <module>
    print(manhattan_distance(p1, p2))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "distance.py", line 6, in manhattan_distance
    return abs(point_1.x - point_2.x) + abs(point_1.y - point_2.y)
                           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'x'
```
These additional lines (with `^` or `~`) aren't matching the python multiline regex and end up as single line messages.

**Describe the solution you'd like**
Add a regex matching the new lines to the python multiline handler, to also catch these lines into the multiline message.

**Additional context**
In-depth explanation for the Python changes: https://docs.python.org/3/whatsnew/3.11.html#pep-657-fine-grained-error-locations-in-tracebacks

**Comment by peschmae** [comment]
Still relevant, as the persists in the latest version

**Comment by peschmae** [comment]
Still an issue in 3.0

**Comment by flo-ri-an** [comment]
still needs a resolution

**Comment by jeremych1000** [comment]
Why was this closed? :(

**Comment by suckowbiz** [comment]
Please re-open. This issue still is not resolved.
