### ISSUE TITLE
[plugin][out_kafka] Topics need to be manually set - cannot use Topic_Key to generate

### ISSUE THREAD

**Issue by whithajess** [fluent/fluent-bit#749]
**Is your feature request related to a problem? Please describe.**

Without being able to set `Topics` via the `Topic_Key` we would have to manually add topics all the time - as well as this there is an issue limiting the length of `Topics` https://github.com/fluent/fluent-bit/issues/748

**Describe the solution you'd like**

I would like topics to be created automatically via `Topic_Key` I think an option like: 
```
Topic_Key_Generate   true
```
 could be used to make sure this is an option you want turned on.

By default Kafka has the `auto.create.topics.enable` set as `true` so sending a message will auto create the topic on the server - [kafka documentation](https://kafka.apache.org/documentation/#brokerconfigs)

**Additional context**

We want new topics to not require manual addition to fluent-bit configuration.

**Comment by snowjunkie** [comment]
And in a situation in which that Kafka setting were false, what behaviour would you expect at the fluentbit end? Since fluentbit will fail to deliver the message, would you just expect the flow as per an unrecoverable error?

**Comment by anandsinghkunwar** [comment]
@snowjunkie Shouldn't it be the same flow as in the case of a specifying a Topic Name which isn't already created in kafka and has `auto.create.topics.enable` set as `false`

**Comment by LuukSt** [comment]
In fluentd it is possible to (optionally) specify a default topic. So if the topic derived from a topic key does not exist it will try to write to the default topic and only log an error if the default topic also doesn't exist. Perhaps this could be a nice addition as well for fluentbit?

**Comment by whithajess** [comment]
@LuukSt I think that is already the case from my original testing of the Kafka feature set (undocumented)

Unfortunately I believe the company I was working for at the time of logging this issue is looking into another system due to constraints in the Kafka plugin in `fluent-bit` - Bit of a shame as I really liked the idea of using this as its a very lightweight option for getting logs from Kubernetes containers that would fit well with a lot of companies using Kafka etc. for streaming data.

Not blaming `fluent-bit` seems `edsiper` is doing most of the work and needs help!

**Comment by whithajess** [comment]
Fixed by: https://github.com/fluent/fluent-bit/pull/1912
Docs here: https://github.com/fluent/fluent-bit-docs/pull/259
