### ISSUE TITLE
Documentation for threaded option?

### ISSUE THREAD

**Issue by jeongukjae** [fluent/fluent-bit#7496]
I know this isn't a bug, but there's no other appropriate option for this in the issue templates, so I'm writing this with bug report template.

## Bug Report

**Describe the bug**

I found that threaded option in the release note (https://fluentbit.io/announcements/v2.0.0/#performance) and it works well. So I want to check the detailed documentation about it, but I can't.

**Expected behavior**

Docs for threaded option.
Maybe this page?: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file#config_input

**Additional context**

I think it should be great if the documentation specifies the buffers. I found that the threaded input plugin cannot adjust the buffer size.
* Ring Buffer defs in input plugin: https://github.com/fluent/fluent-bit/blob/a4d9309ddb0162dfa11cd337c7f41266fe998d44/src/flb_input.c#L57-L68
* With threaded option, fluent bit try to append records to ring buffer: https://github.com/fluent/fluent-bit/blob/a4d9309ddb0162dfa11cd337c7f41266fe998d44/src/flb_input_chunk.c#L1983-L1987

**Comment by patrick-stephens** [comment]
The docs are handled over in https://github.com/fluent/fluent-bit-docs, if you can please submit a PR there.
