### ISSUE TITLE
node_systemd_unit_state  gets a bad timestamp with a misplaced  decimal in the unix epoch

### ISSUE THREAD

**Issue by roganlynch** [fluent/fluent-bit#7506]
## Bug Report

**Describe the bug**

fluent-bit 2.1.3  & 2.1.4 on patched ubuntu 20.04 x86_64
Errors in the syslog output. Misplaced / Missing decimal  in Unix epoch date.  Creating chunks that won't be cleared by normal output to `remote_write` to AWS managed Prometheus 

EXAMPLE SYSLOG error:
```
Jun  1 02:17:58 cust-dev-bastion-a01 fluent-bit[233236]: timestamp too old: 1685579439362 metric: "node_systemd_unit_state"
```

NOTE: 
```
# date -d @1685579439362
Thu Nov 20 06:56:02 UTC 55383
```
vs.

```
# date -d @1685579439.362
Thu Jun  1 00:30:39 UTC 2023
```

**To Reproduce**
Happens after 30-60 minutes of starting the fluent-bit process. With trivial config - below. 
Always a `node` metric
**Input config**:

```
[INPUT]
    Name node_exporter_metrics
    Scrape_Interval 10s
    Tag metrics-local-node
```
**Expected behavior**
10 decimal digits, a period, and additional digits for the mantissa 

**Your Environment**
* Version used: 2.1.3 & 2.14
* Configuration: ABOVE
* Environment name and version (e.g. Kubernetes? What version?): Running directly on host
* Server type and version: AWS
* Operating System and version: Ubuntu 20.04 x86
* Filters and plugins: node_metrics  input plugin

**Comment by cosmo0920** [comment]
How did you obtained syslog error?

Only using in_node_exporter_metrics and prometheus remote_write does not generate syslog error, I guess...

**Comment by cosmo0920** [comment]
@rlynch-bitpusher ping?

**Comment by rlynch-bitpusher** [comment]
Hello  @cosmo0920  - you need to be pointed at AWS Managed Prometheus - the error comes directly from the 400 response.
[etc.fluent-bit.tar.gz](https://github.com/fluent/fluent-bit/files/11669226/etc.fluent-bit.tar.gz)
if you look at the json output from fluent-bit from this config (pointed at AMP)  you will see that the `proc_bytes` field only increments - and never levels of or clears whilst all other fields are zero. This is suggestive of a memory leak.

**Comment by rlynch-bitpusher** [comment]
`curl -s  "http://localhost:2020/api/v1/metrics" | jq -C .`
```
{
  "input": {
    "node_exporter_metrics.0": {
      "records": 0,
      "bytes": 0
    }
  },
  "filter": {},
  "output": {
    "prometheus_remote_write.0": {
      "proc_records": 0,
      "proc_bytes": 50922,
      "errors": 0,
      "retries": 0,
      "retries_failed": 0,
      "dropped_records": 0,
      "retried_records": 0
    }
  }
}
```

**Comment by cosmo0920** [comment]
We'll mitigate this issue with https://github.com/fluent/fluent-bit/pull/7528 and https://github.com/fluent/fluent-bit/pull/7514.

**Comment by anderssynstad** [comment]
Was this pushed til 2.1.9? I'm still getting the 400 error and "out of bounds" after upgrading to fluent-bit 2.1.9 and adding `systemd` to the metrics list for `node_exporter_metrics`.
