### ISSUE TITLE
Support key format strings for Azure Blob as supported on Amazon S3

### ISSUE THREAD

**Issue by wouterAA** [fluent/fluent-bit#7515]
We make heavy use of Amazon S3 output key format strings configuration property (https://docs.fluentbit.io/manual/pipeline/outputs/s3, see s3_key_format). To be specific we use the %Y%m%d%H%M%S format string. We would like to see the "format string" functionality for the Azure Blob output path configuration property (https://docs.fluentbit.io/manual/pipeline/outputs/azure_blob see path).

Our SaaS product is hosted on both AWS and Azure. To reduce maintenance, it is a goal to limit the differences between the cloud providers. Because the Azure Blob output, does not support format strings, we need to use a different logging processor. We have good experiences with fluentbit, and want to use it at both places.

**Comment by pmcgrath-mck** [comment]
Not sure I understand, is it that the azure blob output, supports a path which we can configure, but it behaves differently ?
Does not support a format string ?

**Comment by aglees** [comment]
That's correct @pmcgrath-mck, the plug-in does not support the same `key_format` options that have been supported on S3 for a long time now.
