### ISSUE TITLE
Add a Prometheus Remote-Write input plugin

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluent-bit#7526]
**Is your feature request related to a problem? Please describe.**
When running Fluent Bit as an OTEL aggregator (multiple replicas) and wanting to aggregate metrics from Prometheus there isn't currently a way to do this without duplicating the metrics across all of the replicas. This is because Prometheus can't currently push metrics in OTEL format.

**Describe the solution you'd like**
I'd like Fluent Bit to support the [Prometheus Remote-Write specification](https://prometheus.io/docs/concepts/remote_write_spec/) so prometheus can push metrics to a Fluent Bit Aggregator service without duplicating the metrics.

**Describe alternatives you've considered**
Not aggregating metrics and pushing straight from Prometheus, but this isn't as reliable or consistent.

**Additional context**

**Comment by agup006** [comment]
Ah I like this I assume HTTP/2 input is needed @leonardo-albertovich as FYI

**Comment by stevehipwell** [comment]
Based on the [spec](https://prometheus.io/docs/concepts/remote_write_spec/#:~:text=Prometheus%20Remote%20Write%20compatible%20senders%20MUST%20retry%20write%20requests%20on,4xx%20responses%20other%20than%20429) I think HTTP/1.1 is valid.

**Comment by leonardo-albertovich** [comment]
Yes, HTTP/1.1 should be good enough, there are no blockers as far as I know.

**Comment by stevehipwell** [comment]
I assume that #8725 is related or potentially delivers this functionality?

**Comment by stevehipwell** [comment]
It looks like the [Prometheus Remote Write](https://docs.fluentbit.io/manual/pipeline/inputs/prometheus-remote-write) functionality has been delivered so I'll close this issue.
