### ISSUE TITLE
Time format with year after microseconds being parsed incorrectly

### ISSUE THREAD

**Issue by michaeltravisuk** [fluent/fluent-bit#754]
## Bug Report

I am trying to parse logs which have a time format in which the year is located after the time, with the time having microsecond resolution.  The same year format (%Y) is working correctly on other time formats I am parsing in which the year is found earlier in the string.

**To Reproduce**
http://rubular.com/r/HivjzdSqS2

Time format being used is:
`%a %b %d %H:%M:%S.%L %Y`

A sample timestamp I'm trying to parse:
`Wed Sep 05 10:11:41.514940 2018`

The above time format is parsed correctly by Ruby's `strptime`
The timestamp below matches to the year 2038:
```
[99] error-logs: [2107356286.513100000, {message goes here}
```
Removing the (%Y) works as a workaround (I assume it simply uses the current year if there isn't one supplied), but I would ideally like to be able to parse based on year.

**Expected behavior**
Time to be parsed with the correct year.

* Version used: 0.14.1
* Configuration: Default build options, with TLS and Kafka support enabled.
* OS: CentOS 6 and 7

**Comment by dominique-pfister** [comment]
Stumbled across this as well, in all 0.14.X versions. Glad to say that is fixed with version 1.0.0 (and later), with commit [a82e268d7](https://github.com/fluent/fluent-bit/commit/a82e268d7ba67769612246cc171fb9c4f77c6df3#diff-4b32890b525e896dd8ec2ea5d0fa941a)
