### ISSUE TITLE
Field Names - use of "." as separator for InfluxDB field names

### ISSUE THREAD

**Issue by oneofthemany** [fluent/fluent-bit#7546]
## Bug Report

**Describe the bug**
Having a field name with a "." as a separator limits function within Influx DB when undertaking certain queries.

**To Reproduce**
- Example log message:
```
{"log":" runtime error @7:6-7:74: map: failed to evaluate map function: member "Mem" with type object is not in the record"}
```
- Steps to reproduce the problem:

using the following query to determine memory percentage:
```
percentage = from(bucket: "fluent_bit")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "rock-5b_agent.mem")
  |> filter(fn: (r) => r["_field"] == "Mem.total" or r["_field"] == "Mem.free")
  |> toFloat()
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> map(fn: (r) => ({r with _value: r.Mem.free / r.Mem.total * 100.0 }))
  |> yield(name: "percentage")
```

**Expected behaviour**
The field name being sent from fluent_bit to InfluxDB would amend the separator of "." with a "_".

**Screenshots**
![image](https://github.com/fluent/fluent-bit/assets/44924639/2319478d-fed8-4b5b-918d-e64139af53c1)

**Your Environment**
* Version used: 2.1

**Additional context**
The only way to undertake the memory time line is by using a more complex and less efficient approach:

```
total = from(bucket: "fluent_bit")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "rock-5b_agent.mem")
  |> filter(fn: (r) => r["_field"] == "Mem.total")
  |> aggregateWindow(every: 10s, fn: last, createEmpty: false)
  |> group(columns: ["_field"])

free = from(bucket: "fluent_bit")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "rock-5b_agent.mem")
  |> filter(fn: (r) => r["_field"] == "Mem.free")
  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)
  |> group(columns: ["_field"])

join(tables: {total: total, free: free}, on: ["_time"])
|> map(fn: (r) => ({ r with _value: float(v: r._value_free) / float(v: r._value_total) * 100.0}))
|> keep(columns: ["_value","_time"])
```

![image](https://github.com/fluent/fluent-bit/assets/44924639/ecc84655-91e2-4d27-bcb1-893336b3d673)

**Comment by patrick-stephens** [comment]
You could also modify the field names prior to the output to remove the dots and replace with underscores. I know it's not ideal but would work with the current versions.

**Comment by oneofthemany** [comment]
> You could also modify the field names prior to the output to remove the dots and replace with underscores. I know it's not ideal but would work with the current versions.

How do you edit the field names ahead of output as these are taken directly from /proc?

**Comment by patrick-stephens** [comment]
Use a filter, e.g. modify, lua or otherwise. It's no different to modifying any other key - the input will auto-create some but you can mangle them afterwards however you like.

You may need to lift them first via https://docs.fluentbit.io/manual/pipeline/filters/nest then modify but a LUA filter could do it all in one go.

**Comment by oneofthemany** [comment]
> Use a filter, e.g. modify, lua or otherwise. It's no different to modifying any other key - the input will auto-create some but you can mangle them afterwards however you like.
> 
> You may need to lift them first via https://docs.fluentbit.io/manual/pipeline/filters/nest then modify but a LUA filter could do it all in one go.

cool thanks I have now simply added this to the input_mem.conf:

```
[FILTER]
  name modify
  match *
  rename Mem.free Mem_free
  rename Mem.used Mem_used
  rename Mem.total Mem_total
  rename Swap.free Swap_free
  rename Swap.used Swap_used
  rename Swap.total Swap_total
```
Thanks for your help :)
