### ISSUE TITLE
rewrite_tag rule does not match if key contains a "." (period, dot)

### ISSUE THREAD

**Issue by ynikitin-etsy** [fluent/fluent-bit#7556]
## Bug Report

The `rewrite_tag` filter's rule will not match any record if the key contains a period (dot, ".").

This is the configuration:

```
[SERVICE]
    flush        1
    daemon       Off
    log_level    trace
    http_server  On
    http_listen  0.0.0.0
    http_port    2020

[INPUT]
    Name tail
    Tag cos_containers
    Path /Users/ynikitin/input/cos_containers
    Read_from_Head True
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On

[FILTER]
    Name modify
    Match *
    Add hi.there test

[FILTER]
    Name          rewrite_tag
    Match         cos_containers
    Rule          $hi.there ^test$ some_new_tag false
    Emitter_Name  new_tag_emitter

[OUTPUT]
    Name file
    Path /Users/ynikitin/output/
    Match *
```

Command

```
echo "try13" >> /Users/ynikitin/input/cos_containers
```

**Expected behavior**

`curl -s http://127.0.0.1:2020/api/v1/metrics | jq`

When I see how many records that filter emitted, it should be non-zero.

```
"rewrite_tag.1": {
      "drop_records": 3,
      "add_records": 0,
      "records": 3,
      "bytes": 127,
      "emit_records": 3
    }
```

emit_records is 3, which is good.

**Actual behavior**

```
"rewrite_tag.1": {
      "drop_records": 0,
      "add_records": 0,
      "records": 8,
      "bytes": 506,
      "emit_records": 0
    }
```

emit_records is 0, which is not so good.

**Notes**

If I change the periods (dots) to underscores, this works.

```
[FILTER]
    Name modify
    Match *
    Add hi_there test

[FILTER]
    Name          rewrite_tag
    Match         cos_containers
    Rule          $hi_there ^test$ some_new_tag false
    Emitter_Name  new_tag_emitter
```

**Your Environment**

MacOS 13.4
```
ynikitin@10531 fluentbit % fluent-bit -c conf.conf
Fluent Bit v2.1.4
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
```

**Other Notes**

Docs do not contain any notes on what the key could be.

https://docs.fluentbit.io/manual/pipeline/filters/rewrite-tag#key

**Comment by nokute78** [comment]
Hmm, it worked without `$`.
Could you test following configuration ?

```
[INPUT]
    Name dummy
    Tag test

[FILTER]
    Name modify
    Match test
    Add hi.there test

[FILTER]
    Name rewrite_tag
    Match test
    Rule hi.there ^test$ some_new_tag false
 
[OUTPUT]
    Name stdout
    Match *
```

**Comment by jsammut1976** [comment]
I have the same issue.

I can also confirm that it works without `$` as suggested by @nokute78 .  However I'm not sure whether we should use it without the `$` as the latest documentation specifies that _"A key name is specified and prefixed with a $"_.

I think this is a bug.  What do you recommend?

**Comment by eamh0001** [comment]
Hi! This issue still happens in v3.1.9. 
I agree on what @jsammut1976 says, either this is a bug or the documentation should reflect that issue. Plus, it is quite difficult to debug (especially to someone new to fluentbit) as it just silently doesn't work.

**Comment by linuxmail** [comment]
hi,

thanks for this hint !!

```
filters:
    - name: rewrite_tag
      match: container
      rule: com.hashicorp.nomad.namespace ^(backoffice-test)$ ns.backoffice false
      emitter_name: re_emitted
```

this works, even with v4.0.4

**Comment by dmitryshostak** [comment]
Literally spent more than a day of debugging. Thanks!
