### ISSUE TITLE
Output to System Center Operations Manager

### ISSUE THREAD

**Issue by ivan11paths** [fluent/fluent-bit#7562]
I have the need to integrate the logs generated in a kubernetes cluster with a System Center Operations Manager. Is there a plugin implemented for this purpose? I have seen that there is integration with [Azure Log Analytics](https://docs.fluentbit.io/manual/pipeline/outputs/azure), but in this case it would be for an on-premise service.

**Comment by agup006** [comment]
No plugin for this at the moment, @ivan11paths would you be open to contributing one?
