### ISSUE TITLE
[out_kafka - avro plugin] Union and null support & long & double

### ISSUE THREAD

**Issue by zakuArbor** [fluent/fluent-bit#7566]
## Bug Report

**Describe the bug**
Aside from the impending #5435 which aims to fix `schema_id` (which took me a long time to realize), I have been stuck trying to support "optional" fields. According to the Avro specification, unions should be supported and a few sources online states union is a workaround to have `optional` field. However, I cannot seem to get it working. I have copied a few schemas online and also made my own with no avail. I have tried the schema on a python program and it seems to work without issues. In addition, what is the state of Avro in fluent-bit?  Are unions with null values even supported in fluent-bit's avro support?

**schema:**
```
{
    "type": "record",
    "name": "studentEnrollment",
    "fields": [
        {
            "name": "name",
            "type": "string",
            "default": ""
        },
        {
            "name": "student_id",
            "type": ["null", "string"],
            "default": null
        }
    ]
}
```

**To Reproduce**
**part of the configuration:**
```
[INPUT]
    name dummy
    tag  dummy.log
    dummy {"name": "John Smith", "student_id": "test"}
    samples 1

[OUTPUT]
    name  kafka
    match *
    brokers localhost:9092
    topics sample-avro
    Schema_str { "type": "record", "name": "studentEnrollment", "fields": [ { "name": "name", "type": "string", "default": "" }, { "name": "student_id", "type": [ "null", "string" ], "default": null } ] }
    log_level debug
    Schema_id 4
    Format avro
```

**output:**
```
fka:kafka.0] error encoding to AVRO:schema:{ "type": "record", "name": "studentEnrollment", "fields": [ { "name": "name", "type": "string", "default": "" }, { "name": "student_id", "type": [ "null", "string" ], "default": null } ] }:schemaID:4:
juhkim@BBf032729b:~/doc/projects/log-event-collector-service/out_kafka_pb/test-prog/consumer$ cat /tmp/out
[2023/06/14 15:40:38] [error] Cannot get field:
  Unknown record field message

[2023/06/14 15:40:38] [error] [/home/juhkim/test/fluent-bit/src/flb_avro.c:306 errno=0] Success
[2023/06/14 15:40:38] [error] Failed msgpack to avro

[2023/06/14 15:40:38] [error] [output:kafka:kafka.0] error encoding to AVRO:schema:{ "type": "record", "name": "studentEnrollment", "fields": [ { "name": "name", "type": "string", "default": "" }, { "name": "student_id", "type": [ "null", "string" ], "default": null } ] }:schemaID:4:
```

**Expected behavior** To serialize to Avro without complaints

**Your Environment**
* Version used: latest master/main branch
* Configuration: Listed above
* Operating System and version: `WSL2 Ubuntu`
* Filters and plugins: `out_kafka` with `avro`

**Additional info**
* sending data such as `{"name": "John Smith", "student_id": null}`  does not work
* also tested using avro-tools except my output I suggested in the config does not work since avro-tools expect this instead: `{"name": "John Smith", "student_id": {"string": "test"}}` which also has been tested and does not work.

**Comment by zakuArbor** [comment]
>what is the state of Avro in fluent-bit?

Based on my findings and confirmed by #4097, `long` and `double` are not supported. As suspected, it has to do with how `msgpack_object_type` doesn't differentiate between 32bit and 64 bit ([source](https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview). To be clear, msgPack can handle both 32bit and 64bit values. The way I approach this previously when I was experimenting protobuf in Fluent-Bit, I had to manually add a statement to say if the key is xxx, treat it as 64 bit. Not a solution.

**Comment by zakuArbor** [comment]
**Adding Support for Long**
One could change `src/flb_avro.c` along the lines of:
```c
if ((unsigned long)o->via.u64 > INT_MAX) {
    ret = do_avro(avro_value_set_long(val, o->via.u64),"failed on long");
    break;
}
```

**Comment by silverwind** [comment]
I also ran into strange `Union has no selected branch` avro encoding errors on a `["string", null]` type. Luckily I was able to eliminate all unions from the schema.

**Comment by sthiyagu9** [comment]
Hi, is there any update or workaround for the union and null (optional fields) support issue, or is it still unresolved?
