### ISSUE TITLE
Release numbers on web page are confusing

### ISSUE THREAD

**Issue by edespong** [fluent/fluent-bit#7571]
## Bug Report

**Describe the bug**
1. Trying to get the latest version of fluent-bit, I went to https://fluentbit.io/. 

There it says:
```
V2.1.2 Released On May 18, 2023
[READ THE NOTES »](https://fluentbit.io/announcements/v2.1.3)
```
The text says 2.1.2, and the release notes are for 2.1.3, even though at the current date the latest release on github is 2.1.4.

2. I click `Download Now`, get to https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit and then click `Windows 10 2019.03 - Windows EXE`.

3. I get to https://docs.fluentbit.io/manual/installation/windows#installation-packages where it says:
```
The latest stable version is 2.1.2 each version is available on the Github release as well as at :
...
fluent-bit-2.1.4-win32.exe
...
```

In the end, the actual executables seem to be the latest version, 2.1.4, but all the information up until that makes the whole download experience quite confusing if you know what the latest version is and is actively looking for it.

**Expected behavior**
I would expect all version numbers and information to be about 2.1.4

![Screenshot 2023-06-15 084038](https://github.com/fluent/fluent-bit/assets/1311589/83578244-1e32-4906-b37a-6b520213ecb6)

**Comment by patrick-stephens** [comment]
So this is just a docs typo I think, please submit a PR to resolve: https://github.com/fluent/fluent-bit-docs/tree/master/installation

There is some automation in place to try to resolve this but it is currently failing so we have to do it manually which occasionally leads to missed bits.
