### ISSUE TITLE
Could not create chunk file

### ISSUE THREAD

**Issue by ufferefsgaard** [fluent/fluent-bit#7573]
## Could not create chunk file

We use FluentBit 2.0.8 on Windows 2022 Nodes on Azure AKS 1.25.6
Roughly twice a day we get this error repeated many times:

[C:\src\lib\chunkio\src\cio_memfs.c:45 errno=12] Not enough space
[2023/06/15 07:56:14] [error] [input chunk] could not create chunk file: tail.0:34376-1686815774.110862700.flb
[2023/06/15 07:56:14] [error] [input chunk] no available chunk

During this time we don't get logs through FluentBit.

Any help will be appreciated.

**Configuration**

fluent-bit.conf:

[SERVICE[]
  Parsers_File      C:\fluent-bit\etc\parsers.conf

[INPUT[]
  Name              tail
  Tag               kube.*
  Path              C:\var\log\containers\\*.log
  Parser            cri
  Buffer_Chunk_Size 128k
  Buffer_Max_Size   256k
  Mem_Buf_Limit     20MB
  Refresh_Interval  10
  Docker_Mode       On

[INPUT[]
  Name              tail
  Tag               kubelet.err
  Path              C:\k\kubelet.err.log

[FILTER[]
  Name              kubernetes
  Match             kube.*
  Kube_URL          https://kubernetes.default.svc.cluster.local:443
  Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
  Buffer_Size       0
  Kubelet_Port      10250
  Merge_Log         On
  Merge_Log_Trim    On
  tls.verify        Off

[FILTER[]
  Name              record_modifier
  Match             kube.*
  Record            domain netherlands
  Record            environment Production

[FILTER[]
  Name              Parser
  Match             kube.*
  Parser            fluent_bit_parser
  Preserve_Key      On
  Reserve_Data      On
  Key_Name          log

[OUTPUT[]
  Name           newrelic
  Match          *
  licenseKey     ${LICENSE_KEY}
  endpoint       ${ENDPOINT}
  lowDataMode    ${LOW_DATA_MODE}
  Retry_Limit    ${RETRY_LIMIT}

parsers.conf:

[PARSER[]
  Name              docker
  Format            json
  Time_Key          time
  Time_Format       %Y-%m-%dT%H:%M:%S.%L%z
  Time_Keep         On

[PARSER[]
    Name            json
    Format          json
    Time_Key        timestamp
    Time_Format     %d/%b/%Y:%H:%M:%S %z

[PARSER[]
    Name            cri
    Format          regex
    Regex           ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
    Time_Key        time
    Time_Format     %Y-%m-%dT%H:%M:%S.%L%z

[PARSER[]
    Name            fluent_bit_parser
    Format          regex
    Regex           ^\[(?<time>\d+\/\d+\/\d+ \d+:\d+:\d+)\] \W(?<level>error| \w*)\W(?<log>.*)$
    Time_Key        time
    Time_Format     %Y/%m/%d%t%H:%M:%S

**Comment by yungjenhung** [comment]
Hey @ufferefsgaard Have you noticed that the fluent-bit process consumes higher CPU than usual when hitting the error message "could not create chunk file"?

**Comment by davidgiga1993** [comment]
Did you ever find a solution / root cause of this issue? Facing the same on Windows 2022 on Amazon EKS

**Comment by ufferefsgaard** [comment]
@davidgiga1993 Sadly no - we are living with it. But have changed most logging to Open Telemetry by now.
