### ISSUE TITLE
fluent-bit lock files in windows when accessing via smb share

### ISSUE THREAD

**Issue by andrerca** [fluent/fluent-bit#7591]
## Bug Report

**Describe the bug**
When fluent-bit is reading *.json files from smb share, log rotate will not work because fluent-bit lock the files for deletion.

**To Reproduce**
- Write your json files in server A and share the folder.
- From server B, install fluent-bit and tail input json files in the shared folder.
- Try to delete an older file. For me, the file disappears but if i F5, the file reappear again without permissions.

**Expected behavior**
Older files should be deleted by log rotate.

**Your Environment**
Windows Server 2019, fluent-bit version 2.1.2, no plugins, only json_parser.

Config file:
```

[SERVICE]
flush 5
daemon Off
log_level debug
parsers_file parsers.conf
plugins_file plugins.conf
http_server Off
http_listen 0.0.0.0
http_port 2020
storage.metrics on
Log_File D:\log\fluent-bit.log

[INPUT]
Name tail
Path \\vm22\Risk*.json
Tag risk
Parser json_field
DB D:\Fluent-DB\Risk\point.db
Refresh_Interval 20
Buffer_Max_Size 5MB
Buffer_Chunk_Size 400kb
Mem_Buf_Limit 1000MB

[OUTPUT]
Name es
Match risk
Host elasticsearch
Port 9200
Index log-service-risk
Trace_Error On
Generate_ID On
Buffer_Size 1000MB
Write_Operation upsert
Retry_Limit 5

[OUTPUT]
Name stdout
Match *


```

**Comment by MrPibody7** [comment]
I was able to reproduce the behavior, and also found the following:

**Comment by andrerca** [comment]
Thank you MrPibody7. I tried to reproduce your steps.

- Using delete key and cleaning Recyble Bin also worked for me, the file was permanently deleted.

- After moving and deleting the file, i refreshed/F5 the shared folder and guess who is back? The deleted file ;D

**Comment by andrerca** [comment]
Thank you MrPibody7. I tried to reproduce your steps.

    Using delete key and cleaning Recyble Bin also worked for me, the file was permanently deleted.

    After moving and deleting the file, i refreshed/F5 the shared folder and guess who is back? The deleted file ;D

edit: miss click and closed the issue, reopening

**Comment by liguangcheng** [comment]
is this issue only occur on Windows？

**Comment by MrPibody7** [comment]
Thanks, @andrerca you're right, again, after refreshing using F5 the "deleted" file is back.

**Comment by MrPibody7** [comment]
@liguangcheng  I tested in Linux using NFS, and this issue doesn't happen.

**Comment by MrPibody7** [comment]
@liguangcheng  I tested running fluent-bit in Linux again, but this time mounting a Windows File Share on the Linux File System as a CIFS file system type. 
In this case, the behavior reported was present. After this was read, I deleted tusing the shift and delete keys. Apparently, it was deleted, but when I refreshed ( pressing  F5 ), the file appeared again.
