### ISSUE TITLE
Syslog Input Mode UDP

### ISSUE THREAD

**Issue by anandsinghkunwar** [fluent/fluent-bit#760]
**Is your feature request related to a problem? Please describe.**
There is a syslog TCP input endpoint, but not a UDP one.

**Describe the solution you'd like**
Just like the syslog input mode `tcp`, I'd love if there was a syslog mode `udp` 

**Additional context**
I have many servers which expect a syslog UDP endpoint for pushing their logs.

**Comment by konstantin-kornienko-epam** [comment]
Also need this feature! Use case - collect large amount of log data from local application (udp/json) and forward it to fluentd or logstash for futher processing.
