### ISSUE TITLE
Fluentbit can't process metrics with large value.

### ISSUE THREAD

**Issue by adrienyhuel** [fluent/fluent-bit#7605]
## Bug Report

**Describe the bug**
When a metric event is very large, fluentbit can't process the event in its output plugins.
We tried both stdout and opentelemetry output plugins, and both fail with respectively "could not process metrics payload" and "Error decoding msgpack encoded context" errors.

It seems that the failing function is "cmt_decode_msgpack_create" from cmetrics.

**To Reproduce**
Generate metrics vith a very long value

**Expected behavior**
Fluent should be able to parse msgpck message regardless of the size.

**Your Environment**
* Version used: 2.1.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Virtual Machine
* Server type and version: 
* Operating System and version: Debian 11
* Filters and plugins: 

**Additional context**
We're using FluentBit to scrape metrics from coroot-pg-agent, and send them to OpenTelemetry.
Coroot Agent has some metrics pg_top_query_*, where one of attributes is the sql query itself.
When the query is very long (we had some queries with more than 3000 chars), fluentbit can't process the metric.

**Comment by patrick-stephens** [comment]
Can you provide an example metric? "Very long" could be subjective :)

**Comment by adrienyhuel** [comment]
@patrick-stephens 

Coroot-pg-agent export metrics like a prometheus exporter, it expose an endpoint.
When fluentbit call this endpoint (with the prometheus_scrape input), it receive metrics like that : 

```
# HELP pg_agent_info 
# TYPE pg_agent_info gauge
pg_agent_info{version="1.2.2"} 1
...
pg_top_query_time_per_second{db="bookstore",query="set extra_float_digits = ?",user="admin"} 0
pg_top_query_time_per_second{db="bookstore",query="show transaction isolation level",user="admin"} 0
pg_top_query_time_per_second{db="postgres",query="select d.datname, r.rolname, left ( s.query, ? ), s.queryid, s.calls, s.total_plan_time + s.total_exec_time, s.blk_read_time + s.blk_write_time from pg_stat_statements s join pg_roles r on r.oid = s.userid join pg_database d on d.oid = s.dbid and not d.datistemplate",user="coroot"} 7.476280115024478e-06
....
```

In this sample pg_top_query_time_per_second doesn't have long sql queries, but I seen some very long ones (more than 3000 characters) on our production machine, where there is queries made by an application.
