### ISSUE TITLE
Kubernetes Filter doesn't allow reemitted events

### ISSUE THREAD

**Issue by FireDrunk** [fluent/fluent-bit#7611]
## Bug Report

**Describe the bug**
The `kubernetes` filter doesn't seem to accept *any* reemitted events.

**To Reproduce**
```
    [FILTER]
        Name kubernetes
        Match kube.*
        # Merge_Log On
        # Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 512k
        
    [FILTER]
        Name rewrite_tag
        Match kube.*
        Rule $kubernetes['namespace_name'] ^(?<k8s_ns>prefix-.+)$ prefixed_namespace.$0 false
    
    [FILTER]
        Name kubernetes
        Match prefixed_namespace.*
        #Kube_Tag_Prefix prefixed_namespace.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 512k
```

**Expected behavior**
I'm trying to get 2 instances of the `kubernetes` filter:
- One where the `Merge_Log` option is On
- One where the `Merge_Log` option is Off

I want to only accept specific tagged events into the one with the `Merge_Log` option set to `On`.

**Your Environment**
* Version used: 2.0.11
* Configuration: Helm Chart
* Environment name and version (e.g. Kubernetes? What version?): Local K3d cluster (1.25.6)
* Server type and version: n/a
* Operating System and version: n/a
* Filters and plugins: default from Helm chart

When using this setup the Kubernetes filter complains that it's receiving reemitted Events with this error: 
```
[2023/06/26 08:02:21] [ warn] [filter:kubernetes:kubernetes.2] invalid pattern for given tag prefixed_namespace.prefix-test
```
I've tried setting `Kube_Tag_Prefix` but that doesn't help.

Easy reproduction:

- K3d Cluster with Fluent Bit preinstalled with given filters
- `kubectl create namespace prefix-test`
- `kubectl run -n prefix-test -it --rm --image sikwan/random-json-logger json`
- Watch the logs

**Comment by FireDrunk** [comment]
@patrick-stephens 
We are having merge issues because different parts of the Kubernetes Cluster are logging JSON in different formats. Because the `Merge_Log` option is (currently) on for all logging, some fields are colliding in the ElasticSearch output index.
To circumvent this we want to exclude all 'infrastructure' related namespaces (the ones where we don't control the log output) from the 'corporate' namespaces (where we do control the log output), and standardize that log format.

The reemitted log entry should already be enriched by the first Kubernetes Filter. So I basically only need the Merge_Log option.

It would be better to have the Merge_Log option off, and have custom rules for parsing a dedicated log standard, but that requires (way) more work from our Developers.

If we can achieve the functionality of the Merge_Log option, without the Kubernetes Filter, that's also fine by me.

**Comment by patrick-stephens** [comment]
You can probably adjust tail to exclude namespaces easily, it's part of the filename anyway. Then it should just be a simple case of tag matching for each tail to the right Kubernetes filter. 

Make sure to use a different tag prefix for one and configure it.

**Comment by FireDrunk** [comment]
I don't want to fully exclude namespace, I just don't want the `Merge_Log` option set to On for those namespaces. I do want all their logging.

**Comment by patrick-stephens** [comment]
Yes, I'm saying exclude it from the tail input that then feeds the K8S filter with it on. A separate tail input can then just do the excluded files to another K8S filter. Just need to ensure the tag prefix differs.

**Comment by FireDrunk** [comment]
@patrick-stephens 
I'm trying your proposed setup, but I'm having issues:

```[INPUT]
        Name tail
        Path /var/log/containers/*_prefix-*_*.log
        multiline.parser docker, cri
        Tag kube-prefix.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_prefix-*_*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
```
and:
```
[FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 512k
    
    [FILTER]
        Name kubernetes
        Match kube-prefix.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 512k
```

This setup errors with:
```
[2023/06/27 11:15:38] [debug] [filter:kubernetes:kubernetes.1] Send out request to API Server for pods information
[2023/06/27 11:15:38] [debug] [http_client] not using http_proxy for header
[2023/06/27 11:15:38] [debug] [http_client] server kubernetes.default.svc:443 will close connection #87
[2023/06/27 11:15:38] [debug] [filter:kubernetes:kubernetes.1] Request (ns=prefix-test, pod=ers.bash) http_do=0, HTTP Status: 404
[2023/06/27 11:15:38] [debug] [filter:kubernetes:kubernetes.1] HTTP response
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"ers.bash\" not found","reason":"NotFound","details":{"name":"ers.bash","kind":"pods"},"code":404}
```
It seems like having multiple wildcards in the file parser results in an incorrect parsing of the pod name. I've also reduced the wildcards to `*_prefix-*`, but that doesn't help.

**Comment by patrick-stephens** [comment]
You need to specify `kube_tag_prefix` correctly - look at the K8S filter docs.

**Comment by FireDrunk** [comment]
Thanks! That seems to work! (Going to do some more testing...)
My config for now (for reference):

```
    [INPUT]
        Name tail
        Path /var/log/containers/*_prefix-*_*.log
        multiline.parser docker, cri
        Tag kube-prefix.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_prefix-*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
```

```
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 512k
    
    [FILTER]
        Name kubernetes
        Match kube-prefix.*
        Kube_Tag_Prefix kube-prefix.var.log.containers.
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Buffer_Size 512k
```

**Comment by patrick-stephens** [comment]
OK great, as I say it gives you a little more granularity (and therefore control) for the sake of verbosity although config files can be generated easily enough too.

You could prioritise namespaces, say kube-system, versus others for important logs vs nice-to-have ones.

**Comment by FireDrunk** [comment]
We've just deployed the change to production, and it seems to work correctly.
Thanks for your help @patrick-stephens !
