### ISSUE TITLE
Please add logo of "Intel" in ReadMe to companies using fluentbit

### ISSUE THREAD

**Issue by rajphoenix20** [fluent/fluent-bit#7620]
## Bug Report

**Describe the bug**

Please add Intel logo to the following section, as we started using it for cloud products.

![image](https://github.com/fluent/fluent-bit/assets/73574021/a6d17beb-958c-4579-b053-081b05d49737)

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by agup006** [comment]
@rajphoenix20 Awesome, happy to help here

**Comment by ariCrespo79** [comment]
Update from Fluentbit partners here

![fluentbit partners-1](https://github.com/fluent/fluent-bit/assets/82909162/fad97e3c-ddfc-4595-b2c8-4b0568dae2c9)
