### ISSUE TITLE
"MK SERVER SETUP CALLED" Messages without prefix

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-bit#7638]
## Bug Report

**Describe the bug**
The Fluent Bit log output shows `MK SERVER SETUP CALLED` messages during startup (sometimes also later). This should be either removed or correctly prefixed, so the message can be parsed properly (especially in case of forwarding Fluent Bits own logs). Currently we are running log-level "info", but do not expect these messages to appear. This should be categorized as debug level message. 
We did not observe this messages in the past, but we are not sure if this is related to config change or by Fluent Bit version change. 

It looks like this is the line where the message is being printed:
https://github.com/fluent/fluent-bit/blob/f70462c100afc192648951a2e205d420717397f9/lib/monkey/mk_server/monkey.c#L202

![image](https://github.com/fluent/fluent-bit/assets/60474128/3b59c929-7a88-48c2-b3f5-cde08fb6d906)

**To Reproduce**
- Start Fluent Bit with HTTP server enabled
- Watch stdout/logfile output of Fluent Bit

**Expected behavior**
Message should be correctly prefixed and only printed if log level is debug or trace.

**Your Environment**

* Version used: 2.1.4
* Operating System and version: Ubuntu 22..04
* Filters and plugins: HTTP server enabled

**Comment by nokute78** [comment]
I think it will be removed.
Latest monkey server is fixed.
https://github.com/monkey/monkey/pull/401
