### ISSUE TITLE
Kubernetes filter seems not to delete the original field once it has been parsed

### ISSUE THREAD

**Issue by yann-soubeyrand** [fluent/fluent-bit#764]
## Bug Report

**Describe the bug**
When using Kubernetes filter and annotation on pods to specify a parser to use, the field which is parsed at this stage (log) is not removed.

**To Reproduce**
Run fluent-bit with the below configuration:
```
    [INPUT]
        Name                           tail
        Path                           /var/log/containers/*.log
        Parser                         docker
        Tag                             kubernetes.*

    [FILTER]
        Name                           kubernetes
        Match                          kubernetes.*
        Kube_URL                       https://kubernetes.default.svc.cluster.local:443
        Merge_Log                      On
        K8S-Logging.Exclude            On
        K8S-Logging.Parser             On

    [OUTPUT]
        Name                           forward
        Match                          *
        Host                           fluentd

    [PARSER]
        Name                           docker
        Format                         json
        Time_Key                       time
        Time_Format                    %Y-%m-%dT%H:%M:%S.%L
        Decode_Field_As                escaped_utf8 log

    [PARSER]
        Name                           fluent-bit
        Format                         regex
        Regex                          ^\[(?<time>[^\]]+)\] \[(?<level>[^\]]+)\] \[(?<module>[^\]]+)\] (?<message>.*)$
        Time_Key                       time
        Time_Format                    %Y/%m/%d %H:%M:%S
```
Launch fluent-bit pods with the following annotation:
`        fluentbit.io/parser: "fluent-bit"`

**Expected behavior**
The event forwarded to fluentd should not contain the log field which has been parsed by the fluent-bit parser. Only the parsed fields (level, module and message) should be present in the record.

**Your Environment**

* Version used: v0.14.1
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.9
* Server type and version: AWS EC2
* Operating System and version: Debian installed by Kops
* Filters and plugins: see above

**Comment by edsiper** [comment]
I think the default behavior is right. But also I think it would be good to offer an option to let the user decide or not to keep the original log message if it was parsed properly.

Considering this as an enhancement request.

**Comment by yann-soubeyrand** [comment]
https://github.com/fluent/fluent-bit/pull/1223 should implement the expected behaviour.

**Comment by yann-soubeyrand** [comment]
Merged.
