### ISSUE TITLE
Output to Azure Blob file key does not work

### ISSUE THREAD

**Issue by smoms** [fluent/fluent-bit#7645]
## Bug Report
Hi,
I am running this config in Docker for Desktop using the latest image:

```
...
    [INPUT]
        Name              tail
        Path              /var/mylog.log
        Read_from_Head    true
        Parser            jsonparser
        DB                /var/some.db
        DB.Sync           Off
        Skip_Long_Lines   Off
        Refresh_Interval  10
        Buffer_Max_Size   5MB
        Buffer_Chunk_Size 1MB

    [OUTPUT]
        name                  azure_blob
        match                 *
        account_name          myac
        shared_key             ...
        path                  audit_trails
        container_name        logs
        auto_create_container on
        tls                   on
....
```
I get a filename like: tail.0

I would like to get a filename in Azure Blob that I can rotate. For example by day, I could give a name based on day like: mylog_ddmmyy.log

I tried with key: "object_key_format" in the OUTPUT but it does not work. FLuentbit does not start.

Any help pls?

**Comment by patrick-stephens** [comment]
I think, looking at the docs, this output uses the tag name which is defined by the input.
You have not specified a tag for the tail input so it is using the default.
https://docs.fluentbit.io/manual/concepts/key-concepts#tag

You can specify the tag in the tail input to whatever you like but getting it to change daily might be tricky, a `rewrite_tag` filter could be used potentially but it would need to consume the suffix from a key probably so you may need another filter to add the key you want.

If you just want the filename then you can use a wildcard in the tag as well with the path. It is documented here: https://docs.fluentbit.io/manual/pipeline/filters/kubernetes#workflow-of-tail-+-kubernetes-filter
I'm not sure if you only ever want to tail `mylog.log` or if that is just an example.

I think this is a feature request to add an option to use a static prefix with a dynamic suffix, i.e. static + record key with any other filter (e.g. lua) filling that key in dynamically with what you want (datestamp in this case, something else maybe for others).

**Comment by smoms** [comment]
@patrick-stephens  thanks. And sorry I missed to say that I would expect the log not as mylog.log but as mylog_ddmmyy.log

And I do not understand the use of [Azure_Object_Key_Format](https://github.com/chestercheng/fluent-bit-go-azblob), as it seems that fluentbit crashes when I add that entry in the OUTPUT plugin. Maybe you have an example?

**Comment by patrick-stephens** [comment]
I suspect the logs will tell you what's happening so be useful to have them - I suspect it is exiting with an error saying it does not understand that configuration.

You have linked to another repository containing a separate Golang-based output plugin - this is not an official plugin and is not part of the official package or container so it's configuration is likely different. The docs for the official plugin are here: https://docs.fluentbit.io/manual/pipeline/outputs/azure_blob

Note that your input file could be named to include the datestamp as well and this would work for what you need - it is the same as the K8S example in the docs: https://docs.fluentbit.io/manual/pipeline/outputs/azure_blob#configuration-for-azure-storage-service
This uses a tag of `var.log.containers.app-default-96cbdef2340.log` which is then the name of the file in Azure by the looks of it: 
![Screenshot from 2023-07-03 13-05-19](https://github.com/fluent/fluent-bit/assets/6388272/d1e2f8fd-1363-4008-b13e-ed2d2f75c7a2)

If you use a wildcard in the `tail` input tag then it should substitute the filename in, so if you ensure your filename is `mylog_whatever.log` on disk then it should be the same tag and therefore same name in Azure.

**Comment by smoms** [comment]
Yeah I know that sample. Do you mean that I should find a way to dynamically change the tag name to include the date token (to get a daily rotation)? Because a static filename would not help me..

**Comment by patrick-stephens** [comment]
Why not get the filename to include it is my suggestion? Then a wildcard tag of `/log/*` would be set to the right value always.

Otherwise yeah you could get the tag to be set to a dynamic value using a LUA filter maybe to get the datestamp and create a key to use for rewrite_tag to then update the tag. It's a bit convoluted I know, just trying to come up with a solution you can do now.

**Comment by smoms** [comment]
I understand the first point now, but to me it is just shifting the problem to the upstream system which in my case is OTel Collector Contrib which I think has the same issue...

About the LUA option, am I correct you suggest to use LUA to rewrite the records in the logs and then extract the key with a rewrite_tag filter?

It seems that the S3 [plugin ](https://docs.fluentbit.io/manual/pipeline/outputs/s3)is by far richer though.

**Comment by YouShallNotCrash** [comment]
Hi, 
Sorry to squeeze in with my own question, but do I understand well that there is no simple way to force this plugin to divide its output to/as separate blobs (e.g. one per day or month)? Something like a rolling appender function

**Comment by smoms** [comment]
@YouShallNotCrash yes, at the time the was created issue. The plugin for S3 is more flexible. Thereafter I did not check anymore.

**Comment by AndreRicardo-Zoetis** [comment]
Any update on this? Is there a way to use the Azure Blob output plugin and break the files by day or size?

**Comment by YouShallNotCrash** [comment]
If that's of any use, I overcame it by extracting date from the log timestamp field (lua script) and adding it to a tag (rewrite_tag fluentbit filter). I used date and time only to hour "precision", so every hour I get a new blob in Azure storage, with the name including what is in this tag
