### ISSUE TITLE
Filter "aws" fails to retrieve meta data from imds v2

### ISSUE THREAD

**Issue by AndLindemann** [fluent/fluent-bit#7648]
## Bug Report

**Describe the bug**
"aws" filter fails to retrieve meta data from imds v2.
I know there's an older issue related to (a similar?) problem, but that is closed, so I thought it'd be easier to raise a new one.

```
Jul 04 06:30:12 tstinstance fluent-bit[1132]: [2023/07/04 06:30:12] [error] [aws_client] failed to add header to request
Jul 04 06:30:12 tstinstance fluent-bit[1132]: [2023/07/04 06:30:12] [ warn] [imds] failed to retrieve metadata
Jul 04 06:30:12 tstinstance fluent-bit[1132]: [2023/07/04 06:30:12] [error] [filter:aws:aws.0] Failed to get instance ID
```

Changing to 
```
imds_version v1
```
fixes it immediately.
I'm sure this did work before, as we've been running the config for quite some time. Can't say when it broke however, just noticed it today but could've been broken for a while.

**Expected behavior**
Retrieve metadata from imds and append to logs

**Your Environment**

* Version used: fluent-bit-2.1.6-1.x86_64
* Configuration:
Relevant config part:
```
[INPUT]
    Name        tcp
    Listen      127.0.0.1
    Port        5170
    Chunk_Size  32
    Buffer_Size 64
    Format      json
    Tag         mytag

[FILTER]
    Name aws
    Match *
    imds_version v2
    az true
    ec2_instance_id true
    ec2_instance_type true
    private_ip true
    ami_id true
    account_id false
    hostname false
    vpc_id false

[OUTPUT]
    Name                cloudwatch_logs
    Match               *
    region              eu-west-1
    log_group_name      my-log-group

```
* Environment name and version (e.g. Kubernetes? What version?):  fluent-bit running as systemd service, no containers
* Server type and version:  AWS EC2 instance
* Operating System and version: Amazon Linux 2
* Filters and plugins: AWS
EC2 instance metadata config:
![grafik](https://github.com/fluent/fluent-bit/assets/4157845/58500d69-4c04-4455-b158-9a24b05d8a57)

**Comment by bandesz** [comment]
Same issue, it started to happen after we've updated from 2.0.5 to 2.1.7.

These three lines are being repeated in the logs:
```
[2023/08/11 09:44:28] [error] [aws_client] failed to add header to request
[2023/08/11 09:44:28] [ warn] [imds] failed to retrieve metadata
[2023/08/11 09:44:28] [error] [filter:aws:aws.2] Failed to get instance ID
```

Our config:
```
[FILTER]
    Name aws
    Match *
    az true
    ec2_instance_id true
    ec2_instance_type true
    private_ip true
    ami_id true
    account_id true
    hostname true
```

**Comment by bandesz** [comment]
Relevant issue: https://github.com/fluent/fluent-bit/issues/6918

**Comment by saraangelmurphy** [comment]
This is also impacting my organization, with the same behaviour. Switching back to imds_version v1 fixes the issue, but naturally means that we cannot require imds v2, which is non-ideal.

**Comment by matthewfala** [comment]
Hi, IMDS `http-put-response-hop-limit` hop limit on the instance may need to be set to `2` if you are running Fluent Bit from a container.

IMDS v2 for security purposes sets TTL to 1 for packets. This means that if Fluent Bit is running in a container, the connection from host network to the container network costs an additional hop which causes packet drop.

See how to set the hop limit here or follow the below guidance:
https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/instance-metadata-v2-how-it-works.html

## Setting Hop Limit

The AWS cli can be used to set `http-put-response-hop-limit` to `2` via the following:

```
aws ec2 modify-instance-metadata-options \
     --instance-id <my-instance-id> \
     --http-put-response-hop-limit 2
```

The AWS cli can also be used to require IMDSv2 for security purposes:

```
aws ec2 modify-instance-metadata-options \
     --instance-id <my-instance-id> \
     --http-tokens required \
     --http-endpoint enabled
```

**Comment by tboeghk** [comment]
This also impacts us on Amazon Linux 2023. On AL2023 IMDBSv1 is prohibited thus the fallback is not working. The filter is not working on versions following `2.0.4`
