### ISSUE TITLE
[custom develop]I want to develop a out plugin

### ISSUE THREAD

**Issue by syl000** [fluent/fluent-bit#7681]
I want to develop a out plugin, but I have some problems. Can someone help me?

1.pull the code

2.CMake Error:
`[CMake] CMake Error:`
`1> [CMake]   Running`
`1> [CMake] `
`1> [CMake]    '/usr/bin/ninja' '-C' '/root/.vs/fluent-bit/8b3a59f9-2d53-428e-a477-3de483794660/out/build/Linux-GCC-Debug/CMakeFiles/CMakeTmp' '-t' 'recompact'`
`1> [CMake] `
`1> [CMake]   failed with:`
`1> [CMake] `
`1> [CMake]    ninja: error: build.ninja:50: bad $-escape (literal $ must be written as $$)`
`1> [CMake]     FLAGS = -Wall -D__FLB_FILENAME__=__FILE__ -Wall -D__FILENAME__='"$(sub...`
`1> [CMake]                                                                      ^ near here`
`1> [CMake] `
`1> [CMake] `
`1> [CMake] `
`1> [CMake] CMake Error at /usr/share/cmake-3.22/Modules/Internal/CheckSourceCompiles.cmake:92 (try_compile):`
`1> [CMake]   Failed to generate test project build system.`
`1> [CMake] Call Stack (most recent call first):`
`1> [CMake]   /usr/share/cmake-3.22/Modules/CheckCSourceCompiles.cmake:76 (cmake_check_source_compiles)`
`1> [CMake]   lib/cfl/CMakeLists.txt:53 (check_c_source_compiles)`
`1> [CMake] -- Configuring incomplete, errors occurred!`

3.env
- vs_2022+ubuntu_22.04+cmake_3.22.1+ninja_1.10.1

**Comment by patrick-stephens** [comment]
We do not officially support Ninja and this frankly looks to be an issue with doing the build via it. There should be no inherent issue with using it but it may be that something needs tweaking.

Can you build via the official process? https://docs.fluentbit.io/manual/installation/sources/build-and-install

If so then that would confirm an issue using Ninja so a PR to resolve it would be appreciated.

**Comment by syl000** [comment]
> * ninja

I removed ninja and switched to make, and it worked successfully. Thank you very much. I have another question: how do I debug and run the entire program locally?

**Comment by patrick-stephens** [comment]
Gdb? 
I'm not really sure what you're after but it may be worth using the Slack channels rather than Github issues
