### ISSUE TITLE
Unable to push system metrics using node_exporter_metrics and InfluxDb

### ISSUE THREAD

**Issue by kapilbhavsar** [fluent/fluent-bit#7689]
Hi,

I'm trying to collect system metrics using node_exporter_metrics and pushing it to InfluxDb using

`bin/fluent-bit -f 5 -i node_exporter_metrics -o influxdb://x.x.x.x:8086 -p database=xxxx`

I see following error

`{"error":"partial write: unable to parse 'node_systemd,name=emergency.target,state=activating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=emergency.target,state=active,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=emergency.target,state=deactivating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=emergency.target,state=inactive,type= unit_state=38 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=emergency.target,state=failed,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=graphical.target,state=activating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=graphical.target,state=active,type= unit_state=38 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=graphical.target,state=deactivating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=graphical.target,state=inactive,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=graphical.target,state=failed,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=cryptsetup.target,state=activating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=cryptsetup.target,state=active,type= unit_state=38 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=cryptsetup.target,state=deactivating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=cryptsetup.target,state=inactive,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=cryptsetup.target,state=failed,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=ureadahead-stop.timer,state=activating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=ureadahead-stop.timer,state=active,type= unit_state=38 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=ureadahead-stop.timer,state=deactivating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=ureadahead-stop.timer,state=inactive,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=ureadahead-stop.timer,state=failed,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_systemd,name=systemd-fsckd.socket,state=activating,type= unit_state=0 1689162594310169483': missing tag value\nunable to parse 'node_syste
[2023/07/12 21:19:59] [ info] [task] node_exporter_metrics/node_exporter_metrics.0 has 1 pending task(s):
[2023/07/12 21:19:59] [ info] [task]   task_id=1 still running on route(s): influxdb/influxdb.0
[2023/07/12 21:20:00] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2023/07/12 21:20:00] [error] [output:influxdb:influxdb.0] http_status=400`

Fluent Bit v2.1.6
Ubuntu 18.04.6 V7.2.2
InfluxDB version: 1.8.10

**Comment by agup006** [comment]
Do you have the tag_key or Auto_Keys set with Influxdb - I've seen Auto_keys not working correctly for Influx.

**Comment by kapilbhavsar** [comment]
It happens specifically with systemd metrics only ... when I set `metrics="cpu,cpufreq,meminfo,diskstats,filesystem,uname,stat,time,loadavg,vmstat,netdev,filefd"` in the command ... it works perfectly. I've not set  tag_key or Auto_Keys .
