### ISSUE TITLE
Fluent Bit accumulates orphaned chunks

### ISSUE THREAD

**Issue by skhalash** [fluent/fluent-bit#7690]
## Bug Report

**Describe the bug**
On our Kubernetes clusters running Fluent Bit, we are monitoring the size of the Fluent Bit storage. In some cases, the `tail.0` directory grew to up to 10GB and never shrunk even though the log ingestion rate had spikes, but then continued staying pretty low for some time. After taking a look at the files (chunks) in `tail.0` we realized that most of them are pretty old (haven't been modified for weeks or even months).  Fluent Bit logs also revealed that the old chunks are registered by the storage backlog (unfortunately, don't have the exact log lines). However, the dump shows that the backlog is empty. Eventually, we have to clean up the old chunks manually every time, otherwise, the `tail.0` directory grows too much.

* Is it the normal behavior of the backlog (unfortunately, this mechanism is hardly documented)? If yes, why does the dump say the backlog is empty?
* Is it possible to restrict the backlog size?
* Even though a small number of chunks are up, the backlog is not getting processed. Is there a way to work around it?

**Your Environment**

* Version used: 2.1.2
* Configuration:
```
[SERVICE]
    Daemon Off
    Flush 1
    Log_Level warn
    Parsers_File custom_parsers.conf
    Parsers_File dynamic-parsers/parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    storage.path /data/flb-storage/
    storage.metrics on

[INPUT]
    Name tail
    Alias tele-tail
    Path /var/log/containers/*.log
    Exclude_Path /var/log/containers/telemetry-fluent-bit-*_kyma-system_fluent-bit-*.log
    multiline.parser docker, cri, go, python, java
    Tag tele.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On
    Refresh_Interval 10
    DB /data/flb_kube.db
    storage.type  filesystem
    Read_from_Head True

[FILTER]
    Name kubernetes
    Match tele.*
    Merge_Log On
    K8S-Logging.Parser On
    K8S-Logging.Exclude On
    Buffer_Size 1MB

[FILTER]
    name                  rewrite_tag
    match                 tele.*
    emitter_mem_buf_limit 10M
    emitter_name          application-logs-http
    emitter_storage.type  filesystem
    rule                  $kubernetes['container_name'] "^(?!istio-proxy$).*" application-logs.$TAG true

[OUTPUT]
    name                     http
    match                    application-logs.*
    alias                    application-logs-http
    allow_duplicated_headers true
    format                   json
    host                     ${HOST}
    http_passwd              ${PASSWORD}
    http_user                ${USERNAME}
    port                     443
    retry_limit              no_limits
    storage.total_limit_size 1G
    tls                      on
    tls.verify               on
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.25
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
Dump:
```
[2023/07/12 15:01:17] [engine] caught signal (SIGCONT)
[2023/07/12 15:01:17] Fluent Bit Dump

===== Input =====
tele-tail (tail)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 4.8M (5000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0

storage_backlog.1 (storage_backlog)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 0b (0 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0

application-logs-http (emitter)
│
├─ status
│  └─ overlimit     : no
│     ├─ mem size   : 0b (0 bytes)
│     └─ mem limit  : 9.5M (10000000 bytes)
│
├─ tasks
│  ├─ total tasks   : 0
│  ├─ new           : 0
│  ├─ running       : 0
│  └─ size          : 0b (0 bytes)
│
└─ chunks
   └─ total chunks  : 0
      ├─ up chunks  : 0
      ├─ down chunks: 0
      └─ busy chunks: 0
         ├─ size    : 0b (0 bytes)
         └─ size err: 0

===== Storage Layer =====
total chunks     : 3476
├─ mem chunks    : 0
└─ fs chunks     : 3476
   ├─ up         : 1
   └─ down       : 3475
```

**Comment by agup006** [comment]
A restart should flush out old chunks. I would also recommend not setting unlimited retries and modifying the scheduler settings to ensure exponential backoff does not hit a massive amount of time

**Comment by skhalash** [comment]
@agup006 Thanks for the hint. We will try out setting a request limit. However, restarting Fluent Bit unfortunately does not flush the old chunks.

**Comment by lecaros** [comment]
Is there any information about those old chunks in the Fluent Bit's log file?
You should see at least the enqueueing of those and then whether they were successfully flushed or not.

**Comment by aslafy-z** [comment]
Not stale
