### ISSUE TITLE
The image built by Dockerfile is scanned for many high risk vulnerabilities

### ISSUE THREAD

**Issue by I560781** [fluent/fluent-bit#7697]
## Bug Report

**Describe the bug**
I used [Dockerfile](https://github.com/fluent/fluent-bit/blob/v2.1.6/dockerfiles/Dockerfile ) to build the fluent-bit image, I scanned it and I found a lot of high risk security vulnerabilities, which is very different from the results when I scanned fluent-bit2.1.6 published in the [docker-hub](https://hub.docker.com/layers/fluent/fluent-bit/2.1.6/images/sha256-0b76c510605b2f79218cc929d4169606cf6b408c01e0ce8ce38fa16dfcb97c4d?context=explore) repository. And I found that the Dockerfile published by the community is very different from the [Hub.Dockerfile](https://hub.docker.com/layers/fluent/fluent-bit/2.1.6/images/sha256-0b76c510605b2f79218cc929d4169606cf6b408c01e0ce8ce38fa16dfcb97c4d?context=explore). Ask where the [Dockerfile](https://github.com/fluent/fluent-bit/blob/v2.1.6/dockerfiles/Dockerfile ) can build a more secure image.

**To Reproduce**
- Steps to reproduce the problem:

Step1   

```
# Build image

git clone https://github.com/fluent/fluent-bit/tree/v2.1.6)
cd fluent-bit
docker build -t fluent-bit:fix-cve-test -f dockerfiles/Dockerfile

```
Step2 
Scan the image you built

```
grype  fluent-bit:fix-cve-test 
```
<img width="1728" alt="image" src="https://github.com/fluent/fluent-bit/assets/139338364/5172b247-acd7-4eca-8cf0-37ccd30d98fe">

Many high-risk vulnerabilities will be found

**Expected behavior**
grype fluent/fluent-bit:2.1.6|egrep "High"

**Screenshots**

<img width="1225" alt="image" src="https://github.com/fluent/fluent-bit/assets/139338364/5b732ab6-aaa3-48c4-a1a1-2059f84b5559">

* Version used: fluent-bit:2.1.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: suse server
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Please repeat with the 2.1.7 release.

Be aware that these dependencies come from the upstream Debian repositories so must have a resolution there: `won't fix` vulnerabilities will not be resolved for example.

There is an open issue on migrating to OpenSSL 3 as well for those targets that can support it: #7644
