### ISSUE TITLE
Lua Filter file to be relative to configuration file

### ISSUE THREAD

**Issue by anandsinghkunwar** [fluent/fluent-bit#770]
## Bug Report

**Describe the bug**
Just like in the case [include file](https://fluentbit.io/documentation/current/configuration/file.html#config_include_file) option for configuration, I expected the lua filter file to be picked up relative to the configuration file.

**To Reproduce**
To reproduce you can create a `test.lua` file in the same path as your config file, fluentbit isn't able to locate it.

**Expected behavior**
Expected behavior is that fluentbit finds the `test.lua` file and is able to use it.

**Additional context**
It will be even better if we could somehow include scripts using `@INCLUDE` syntax.

**Comment by edsiper** [comment]
thanks, we will fix the issue.

**Comment by edsiper** [comment]
Fixed by 695633a7c9d8abe5849017cd4405094e980e1521

Merged into GIT master and 0.14 branch (0.14.3 release)
