### ISSUE TITLE
filter_lua changes the JSON schema

### ISSUE THREAD

**Issue by enesgur** [fluent/fluent-bit#7708]
## Bug Report

I have JSON logs in my project, and I've tested the **Fluent Bit 2.1.7** version on **Debian**. The Linux version is `5.10.0-19-cloud-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.149-2 (2022-10-21)`.

I realized that Fluent Bit is changing the JSON schema. Here's an example:

Input:` {"aaa": null, "bbb": "cccc"}`
Stdout:` {"date": 1689498354.316911, "token": "11111", "bbb": "cccc", "extra": {}, "hostname": "ip-xxx-xx-xx-xx"}`

The `aaa` field is missing. Here's another example:

Input: `{"foo": [], "bar": {}}`
Stdout: `{"date": 1689498914.5041, "token": "11111", "extra": {}, "foo": {}, "bar": {}, "hostname": "ip-xxx-xx-xx-xx"}`

The `foo` has changed to an object, but it should be a list

**To Reproduce**

The parser.conf
```
[PARSER]
    Name        json-test
    Format      json
    Time_Key    time
    Time_Format %s.%L
    Time_Keep   On
```

The fluent.conf
```
[SERVICE]
    Daemon                          off
    Log_Level                       debug
    Parsers_file                    /tmp/parser.conf

[INPUT]
    Name                tail
    Tag                 json-test
    Path                /tmp/log.log
    Parser              json-test
    Read_from_Head      false
    Buffer_Chunk_Size   1m
    Buffer_Max_Size     1m

[FILTER]
    Name    record_modifier
    Match   *
    Record  hostname ${HOSTNAME}
    Record  token 11111

[FILTER]
    Name    Lua
    Match   *
    call    append_tag
    code    function append_tag(tag, timestamp, record) new_record = record new_record["extra"] = {} return 1, timestamp, new_record end


[OUTPUT]
    Name            stdout
    Match           *
    format          json_lines

```

Append a log `echo '{"foo": [], "bar": {}}' >> /tmp/log.log`
Append a log `echo '{"aaa": null, "bbb": "cccc"}' >> /tmp/log.log`

**Expected behaviors**
`{"date":1689499573.713323,"token":"11111","extra":{},"foo":[],"bar":{},"hostname":"ip-xxx-xx-xx-xx"}`
`{"date":1689499619.142707,"token":"11111","aaa":null,"bbb":"cccc","extra":{},"hostname":"ip-xxx-xx-xx-xx"}`

**Environment**

* Version used: Fluent Bit v2.1.7
* Server Info: `Linux version 5.10.0-19-cloud-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.149-2 (2022-10-21)`

**Comment by nokute78** [comment]
> The foo has changed to an object, but it should be a list

For this case, could you try `type_array_key` property for filter_lua plugin ?
https://docs.fluentbit.io/manual/pipeline/filters/lua#config

filter_lua converted empty array -> empty map.
The property is to prevent it.

**Comment by nokute78** [comment]
> The aaa field is missing.

This is Lua spec.
https://www.lua.org/pil/2.5.html
```
Also like global variables, you can assign nil to a table field to delete it.
```

We convert `json` -> `msgpack` -> `lua assosiative array`.
nil is a special value for lua associative array. It is the value to delete key/value pair.

**Comment by enesgur** [comment]
> > The foo has changed to an object, but it should be a list
> 
> For this case, could you try `type_array_key` property for filter_lua plugin ? https://docs.fluentbit.io/manual/pipeline/filters/lua#config
> 
> filter_lua converted empty array -> empty map. The property is to prevent it.
> 

Thank you for your reply. But Do you think it's the right way? Because my log lines could contain many empty lists. And I could not predict it. Also, There could be nested empty lists. Is there any way to prevent it?

For example a logline:
`{"foo": [], "bar": {"cc": [], "dd": {"cc": []}}}`

**Comment by sujithkumar6400** [comment]
I agree with @enesgur , Considering when we are reading Kubernetes container logs. We can not predict which key would have empty lists.
