### ISSUE TITLE
Tail input plugin is not releasing file handle on the deleted files on ec2 instances

### ISSUE THREAD

**Issue by praneethreddymallupally** [fluent/fluent-bit#7709]
## Bug Report

**Describe the bug**

Fluentbit (with **inotify_watcher** enabled) is getting stuck in a unrecoverable state when a logrotate is triggered leading to a log loss situations

here's the logrotate conf
```
 $ cat /tmp/logrotate.conf
/local/scratch/user/*[^g][^z]
{
 copytruncate
 daily
 dateext
 dateformat - %Y-%m-%d-%s
 rotate 10
 create 0640 user user
 compress
 missingok
 size 100M
}
```
logrotate tool uses the above conf and initiates the rotation process either when the size limit (512MB) is reached or the daily condition is met. 

Observation:
```
T1: $(ls -i /local/scratch/user/) => output.log (inode1)
T2: logrotate is triggered
T3: $(ls -i /local/scratch/user/) => output.log (inode1), output.log-2023-07-16-1689507266 (inode2)
T4: $(ls -i /local/scratch/user/)  => output.log (inode1), output.log-2023-07-16-1689507266 (inode2), output.log-2023-07-16-1689507266.gz (inode3)
T5: $(ls -i /local/scratch/user/) => output.log (inode1), output.log-2023-07-16-1689507266.gz (inode3)
```

With the scan frequency set to 5 seconds, Fluentbit detects a new file that matches the specified pattern and opens a file handle on `/local/scratch/user/output.log-2023-07-16-1689507266`. However, this file gets deleted once the gzip compression process is complete. Unfortunately, Fluentbit becomes stuck and fails to release the file handle for the deleted file. Moreover, it also does not open a new file handle on "output.log", which is not the desired behavior.

```
[user@host ]$ sudo ls -l /proc/$(pidof fluent-bit)/fd
lr-x------ 1 root root 64 Jul 14 07:04 780 -> /local/scratch/user/output.log-2023-07-16-1689507266 (deleted)
```

Here's the service and tail config
```
[SERVICE]
    flush        10
    grace        30
    log_level    info
    log_file     /var/log/fluentbit.log
    scheduler.cap 2000
    scheduler.base 5
    json.convert_nan_to_null false
    storage.metrics on
    storage.path /var/tmp/fluentbit/storage
    storage.sync full

[INPUT]
    name tail
    alias              app.tail.0
    Tag                app.tail.0.*
    Buffer_Chunk_Size  2MB
    Buffer_Max_Size    4MB
    Path               /local/scratch/user/*
    Path_Key           log_file_path
    Exclude_Path      /local/scratch/user/*.gz
    Read_from_Head    False
    Offset_Key        offset
    Refresh_Interval  5
    Rotate_Wait       3600
    DB                /var/tmp/fluentbit/db/app.db
    Inotify_Watcher   true
    storage.type      filesystem
```

**Expected behavior**
Fluentbit has to release the file handle on a deleted file, when it finishes consuming all of the data from a rotated file or when the rotate_timeout(3600) expires, whichever occurs first.

**Your Environment**
* Version used: 2.1.4
* Environment name and version (e.g. Kubernetes? What version?): EC2 instance 
* Operating System and version: RHEL 7
* Filters and plugins: tail

Suggestions are welcome

**Comment by agup006** [comment]
2 quick things to try

Reducing the rotate_wait to a lower time period, right now its at 1 hour and that is quite high 

Updating with latest in case any updates on file handlers helped solve

**Comment by praneethreddymallupally** [comment]
> 2 quick things to try
> 
> Reducing the rotate_wait to a lower time period, right now its at 1 hour and that is quite high
> 
> Updating with latest in case any updates on file handlers helped solve

Thanks for the suggestion. I will give a try. Reg the 2nd one, I hope you are referring to updating to the latest version of fluentbit i.e., 2.1.7

**Comment by agup006** [comment]
Yes thanks for confirming yes the update was referring to going to the latest version of fluentbit

**Comment by jessejlt** [comment]
We've also hit this issue and have had to switch from file-based logging to journald, which has thus far proved more reliable.

**Comment by praneethreddymallupally** [comment]
@agup006 I tried this out and kept it running for almost 2-3 weeks. 
So far its working good and thus completely eliminating the dangling fd issue.  Thanks for the suggestions.

**Comment by agup006** [comment]
Great to hear! I’ll close for now
