### ISSUE TITLE
Kernel messages (kmsg) are re-processed on each restart or "hot reload"

### ISSUE THREAD

**Issue by nimrodshn** [fluent/fluent-bit#7712]
## Bug Report

**Describe the bug**
When restarting **and "hot reloading"** fluent-bit all the kmsg events are re-processed from the ring buffer causing previously emitted events to be re-emitted. Is that expected?

**To Reproduce**
1. Parse / output kmsg events.
For example:
```
[INPUT]
    name kmsg
    tag KernelMsg

[OUTPUT]
    tag KernelMsg
    name stdout
```

**Expected behavior**
Only send the events **not previously** seen, specifically for "hot reload" that makes even more sense.

**Your Environment**
Ubuntu 18.04 LTS.

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
Attempting to parse network traffic flowing through a linux machine.

**Comment by nimrodshn** [comment]
In addition the 'hot reload' feature causes fluent-bit to, again, ingest all log messages in the kernel ring buffer.

**Comment by agup006** [comment]
Hey @nimrodshn this looks like default behavior every time the plugin is loaded from https://docs.fluentbit.io/manual/pipeline/inputs/kernel-logs

It might be worth extending this plugin to include DB like journal and tail plugins. Is that functionality you can assist with?

**Comment by nimrodshn** [comment]
@agup006 Sure I can try!
