### ISSUE TITLE
Use multiple regex in a single parser

### ISSUE THREAD

**Issue by ashraf133** [fluent/fluent-bit#7727]
## Bug Report

**Describe the bug**
Unable to use OR (|) operator to use multiple regex in a single parser

**To Reproduce**
- Rubular link if applicable:
 https://rubular.com/r/zeyM0Nc7ilGVGz

```
apache2 access log : 
127.0.0.1 - frank [10/Nov/2022:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326
apache2 access regex: 
^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>.*)")?$


nginx log:
47.29.201.179 - - [28/Nov/2022:13:17:10 +0000] "GET /?p=1 HTTP/2.0" 200 5316 "https://domain1.com/?p=1" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36" "2.75"

nginx: regex:
^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")


```
i want to use (|) to parse a file which contain the two format

**Comment by meehanman** [comment]
@ashraf133 Have you seen this previous [answer on Stackoverflow](https://stackoverflow.com/a/73167733/1330180) from my on using multiple parsers. You could have 2 separate parsers and then in your Parser Filter (or Input Parser) eg.

This example would take the logs and use the parse_common_fields filter first, if this filter fails then it would use the JSON filter below. This is essentially what you are trying to achive.
```conf
[Filter]
    Name Parser
    Match *
    Parser parse_common_fields
    Parser json
    Key_Name log
```

**Comment by patrick-stephens** [comment]
@meehanman might be worth adding the example to the official docs as well as a good example - it comes up a bit how to handle two (or more) wildly differing formats.
