### ISSUE TITLE
Excessive Kernel Memory Usage by fluent-bit

### ISSUE THREAD

**Issue by nikhil-bhat** [fluent/fluent-bit#7732]
## Bug Report

**Describe the bug**
Hi , i am seeing very high memory usage in fluentd which is not proportional to the load. on inspecting further i  found most of the memory was consumed by /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes
In order to confirm my suspicion i dropped the dentry and inode cache using, memory usage immediately dropped.
``` 

sync; echo 3 > /proc/sys/vm/drop_caches
```
**To Reproduce**

- Steps to reproduce the problem:

**Expected behavior**
Memory usage should be stable with load

**Screenshots**
![image](https://github.com/fluent/fluent-bit/assets/6253611/e8c3a670-aa85-4cf8-b67c-e305ec3518cb)
![image](https://github.com/fluent/fluent-bit/assets/6253611/fe29cb8b-74c3-4823-8f72-c1f31383f999)

![image](https://github.com/fluent/fluent-bit/assets/6253611/7722850a-61cd-420a-b5e2-eaeaec10a979)

**Your Environment**

* Version used: 2.0.9
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): aks 1.25
* Operating System and version: mariner Linux 5.15 kernel
* Filters and plugins: Rewrite_filter

**Additional context**

I have seen similar issues being reported for memory usage where down chunks are not reclaimed , excessive memory usage with rewrite_tag

**Comment by patrick-stephens** [comment]
2.0.9 is fairly old now, is it reproducible with 2.1.8?

**Comment by nikhil-bhat** [comment]
hi @patrick-stephens  i havent tried reproduing it with 2.1.8 . Will do soon.
In general i have observed two memory leaks

1.) Memory leak when destination are unreachable

Running a tool like pcstat -pid <pid> of fluent-bit reveals that flb files are present 100%  cached in the  page cache of fluent-bit

![image](https://github.com/fluent/fluent-bit/assets/6253611/2fd1155e-04b7-4cb8-a0e5-3687a07af0f3)

Expectation are that chunks kept in the filesystem wont be cached forever 

2.) Slow memory leak 

I see memory slowly increases gradually over the week for  fluent-bit , dont see page cache involved , but running
```
sync; echo 3 > /proc/sys/vm/drop_caches
``` immediately drop memory usage

**Comment by wcurryii-eero** [comment]
I updated to 2.1.8 this week to hopefully resolve our fluent-bit memory leak, but it is still present. I dropped the kernel caches on one of our nodes and saw the leaky fluent-bit's container memory usage drop.

![Screenshot 2023-08-25 at 9 15 14 AM](https://github.com/fluent/fluent-bit/assets/97629962/41f616be-30f1-49a0-bcdf-c9df737b7b0b)
