### ISSUE TITLE
Official Manual 2.1: Input Forward Plugin missing in list of Plugins supporting TLS

### ISSUE THREAD

**Issue by JSchy65** [fluent/fluent-bit#7747]
https://docs.fluentbit.io/manual/administration/transport-security

Here you find the list of input plugins that can take advantage of the TLS feature.
In that list, the **Forward Input Plugin** is **missing**.

Please add the "Forward Input Plugin" to that list.

If it is missing, that can can lead to confusion especially for decision makers.

**Comment by patrick-stephens** [comment]
Thanks, please can you submit a PR to add it here? https://github.com/fluent/fluent-bit-docs/blob/master/administration/transport-security.md

**Comment by JSchy65** [comment]
Done, see https://github.com/fluent/fluent-bit-docs/commit/6af301009b8406917572ed69369acc2aeecd7936
