### ISSUE TITLE
Regex_Parser in Kubernetes Filter not being detected

### ISSUE THREAD

**Issue by dxts** [fluent/fluent-bit#7754]
## Bug Report

**Describe the bug**

The fluent-bit setup within my Kubernetes cluster is generating errors when applying a custom Tag format and parser. 
Specifically, the errors occur at the Filter stage where it states the regex pattern doesn't match the tag of the current log line, despite the custom tag format appearing correctly.

**To Reproduce**

- Rubular link if applicable: https://rubular.com/r/zMiJqDF3Q9vGKx
- Example log message if applicable:
```json
{"log":"[2023/07/26 11:31:28] [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.logging.fluent-bit-qbnt2.fluent-bit.23d2897e94f32061bc13fc44c11845be1a43399a17ff3dfb46bbd19926086bb1","stream":"stdout","time":"2023-07-26T11:31:28.000Z"}
```

- Steps to reproduce the problem:
  1. Implement a custom Tag format in the Input. (Used Helm chart, defined in .Values.config.inputs)
      ```
      [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri, java
        Tag kube.<namespace_name>.<pod_name>.<container_name>.<docker_id>
        Tag_Regex (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Refresh_Interval 10 
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
      ```
  2. Create a custom regex parser for the new Tag name format and set in the Filter. (defined in .Values.config.customParsers, and .Values.config.filters resp.)
      ```
      [PARSER]
        Name kube-custom
        Format regex
        Regex (?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)\.(?<docker_id>[^.]+)
        
      [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix kube.
        Regex_Parser kube-custom
      ```
  3. Observe the errors generated at the Filter stage. 
      ```stdout
      invalid pattern for given tag kube.logging.fluent-bit-qbnt2.fluent-bit.23d2897e94f32061bc13fc44c11845be1a43399a17ff3dfb46bbd19926086bb1
      ```
      The Tag seems to be following the custom format, and using the Rubular link above we see that the `Kube_Tag_Prefix` and `Regex_Parser` configuration should successfully parse this Tag.
  
  4. If I set the Tag field in the Input to mimic the default Tag format, and keep the current Filter config (with the custom parser and tag-prefix), the errors no longer appear and the logs are output successfully.
      ```
      [INPUT]
        ...
        Tag kube.<pod_name>_<namespace_name>_<container_name>-<docker_id>.log
        ...
      ```
      Fluent-bit pod logs now 
      ```
      [2023/07/26 11:49:24] [ info] [output:http:http.4] openobserve.logging:5080, HTTP status=200 {"code":200,"status":[{"name":"default","successful":29,"failed":0}]}
      ```     

**Expected behavior**

I expected the Filter to correctly parse the custom Tag format. However, the Filter seems to still be parsing the Tag in the default format.

**Screenshots**

**Your Environment**

* Version used: 2.1.7
* Configuration:
* Helm chart version: 0.36.0
* Environment name and version (e.g. Kubernetes? What version?): 
  - Kubernetes :
    - Client Version: v1.25.3
    - Server Version: v1.26.3
* Server type and version:
* Operating System and version:
* Filters and plugins: Kubernetes Filter, Tail Input, OpenObserve Output, Regex Custom-Parser

**Additional context**

I'm trying to set a custom Tag format, so that in the Outputs I can match by `Match kube.<my-namespace>.*` to create separate output streams, per namespace, in my log monitor (OpenObserve).

**Comment by patrick-stephens** [comment]
The issue is `kube_tag_prefix` so the filter is ignoring everything as you say. It may be the additional nesting of tags but not sure - what is your actual configuration for the `kubernetes filter` as that is where `kube_tag_prefix` is defined, have you set it up to match your new tag prefix otherwise it will assume the default `kube.var.log.containers.xxx`

However, namespace is already part of the tag with the defaults using `kube.*` as it is part of the filename so you could still do a `Match_Regex` on that for output?

**Comment by dxts** [comment]
> The issue is kube_tag_prefix so the filter is ignoring everything as you say. 

Sorry, I don't follow. The Match clause must be working, otherwise the filter would not try to regex match on the Tag. 
I do have `Kube_Tag_Prefix` defined and it removes the `kube.` part of the tag. The `kube-custom` regex parser should handle the rest.

> It may be the additional nesting of tags but not sure - what is your actual configuration for the kubernetes filter as that is where kube_tag_prefix is defined, have you set it up to match your new tag prefix otherwise it will assume the default kube.var.log.containers.xxx

My Filter configuration is the same as in the report above, and it includes 
```yaml
filters: |
  [FILTER]
      Name kubernetes
      Match kube.*
      Kube_Tag_Prefix kube.
      Regex_Parser kube-custom
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On
```


> However, namespace is already part of the tag with the defaults using kube.* as it is part of the filename so you could still do a Match_Regex on that for output?

Ahan, maybe I will just follow that then. Thanks

**Comment by patrick-stephens** [comment]
Match is unrelated to the `Kube_Tag_Prefix` setting, yes it matches but the configuration is inconsistent. Have a look at the docs for the details but it defaults to an assumption that your `tail` input is using `kube.*` - it however needs to strip off the relevant directories inserted into the tag so uses `kube.var.log.containers.XX` assuming that was where they are.

You need to modify `Kube_Tag_Prefix` appropriately if you change the original `tail` tag.

**Comment by patrick-stephens** [comment]
> But my Filter configuration does do that. Is it not enough to do it there?

No it doesn't. The defaults are `kube.*` which becomes something like `kube.var.log.containers.<filename>` and the `kube_tag_prefix` default is therefore `kube.var.log.containers.`.

Your configuration is incorrect, see https://calyptia.com/blog/kubernetes-metadata-enrichment-with-fluent-bit-with-troubleshooting-tips
