### ISSUE TITLE
Generated msgpack format changed in v2.1.0 - Date wrapped in additional sequence

### ISSUE THREAD

**Issue by sarfata** [fluent/fluent-bit#7755]
## Bug Report

**Describe the bug**

Before v2.1.0 date was encoded as:
```
(ExtType(code=0, data=b'd\xc0\xee\x7f7a\xe4\x89'), {'rand_value': 13625873794586244841})
```

Since v2.1.0 it is encoded as:
```
((ExtType(code=0, data=b'd\xc0\xeeT79\xc5g'), {}), {'rand_value': 1235066654796201019})
```

**To Reproduce**

- Steps to reproduce the problem:
  - Run the [sample tcp listener python script](https://docs.fluentbit.io/manual/pipeline/outputs/tcp-and-tls#command-line): `python test.py`
  - Run fluent-bit: ` ./fluent-bit-2.0.14 -i random -o tcp://127.0.0.1:5170`
  - Observe that in the output of the plugin, the first element is now a sequence of the timestamp and then an empty map. It used to be directly the `ExtType` which contains the timestamp.

**Expected behavior**
I expect the output to not change when updating to v2.1. I could not find any documented change or PR that intentionally changed the output format. 

**Your Environment**
* Version used: all version after 2.1 seems to have this issue (at least 2.1.0 and 2.1.14)
* Configuration: (none - just command line options)
* Environment name and version: tested on macos and Linux
* Filters and plugins: just the tcp output plugin. Demonstrated here with the `random` plugin but the same problem applies to other input plugins as well. I have not tested other output plugins but I don't see anything specific for tcp so this may apply to other output plugins that encode the data in msgpack format.

**Additional context**

We are using the TCP output plugin to send logs to our own program where we do some buffering/processing of logs.

**Bisecting the issue**

It looks like this change was introduced with the commit to use the [new log event abstraction layer](https://github.com/fluent/fluent-bit/commit/d18fce24a04fea481c4d91249ccf83cc40e90ea0) which was part of #7133. 

Last commit before #7133 was 1f04c0b and last commit of this PR was 44a205:
```
$ python test.py &
$  ./fluent-bit-1f04c0b -i random -o tcp://127.0.0.1:5170
(ExtType(code=0, data=b'd\xc0\xf2\x157j\xa9A'), {'rand_value': 17936554027584687856})
$  ./fluent-bit-44a205f -i random -o tcp://127.0.0.1:5170
((ExtType(code=0, data=b'd\xc1\x1226A3\xb8'), {}), {'rand_value': 3675798311345593912})
```

**Comment by leonardo-albertovich** [comment]
Hi @sarfata, this is not a bug, it's a feature that was discussed in this issue #6666. Compatibility wise, the only output plugin that supports re-encoding the data in the previous format is `forward` so I'd suggest updating your sink to support the new format.

Other than that you could try changing the value of [FLB_LOG_EVENT_FORMAT_DEFAULT](https://github.com/fluent/fluent-bit/blob/master/include/fluent-bit/flb_log_event.h#L30) to `FLB_LOG_EVENT_FORMAT_FLUENT_BIT_V1` if you are willing to build fluent-bit yourself but I wouldn't encourage relying on it.

**Comment by sarfata** [comment]
Thanks for the legendary-quick reply @leonardo-albertovich.

We have already made a fix to support the new format. I was not sure if the change was intentional. I did not see anything new or changed in changelog or the documentation. Sorry if I missed it.

**Comment by fredrik-jansson-se** [comment]
I'm maintaining a fluentbit input plugin for our platform. Is the msgpack "protocol" for log documented anywhere? 

The first time i implemented it I read code to figure it out, turns out that I had totally missed the v2.

Would it be possible/reasonable to add this information to https://docs.fluentbit.io/manual?
