### ISSUE TITLE
[in_http] add support for TLS

### ISSUE THREAD

**Issue by ryn9** [fluent/fluent-bit#7756]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
To better serve in an aggregation role, the in_http plugin should support TLS.

This would be similar to what is found in fluentd: https://docs.fluentd.org/input/http#how-to-enable-tls-encryption

**Describe alternatives you've considered**
n/a

**Comment by leonardo-albertovich** [comment]
It does, in fact, every TCP based input plugin does.

**Comment by patrick-stephens** [comment]
Probably a docs issue I think similar to https://github.com/fluent/fluent-bit/issues/7747
Be great if you can submit a PR @ryn9 for the docs repo.

You can see all the options for a particular plugin as well via the `-i <plugin> --help` command line:

```shell
$ docker run --rm -it fluent/fluent-bit -i http --help
...
tls                       Enable or disable TLS/SSL support
                          > default: off, type: boolean

tls.verify                Force certificate validation
                          > default: on, type: boolean

tls.debug                 Set TLS debug verbosity level. It accept the following values: 0
                          (No debug), 1 (Error), 2 (State change), 3 (Informational) and 4
                          Verbose
                          > default: 1, type: integer

tls.ca_file               Absolute path to CA certificate file
                          > default: default, type: string

tls.ca_path               Absolute path to scan for certificate files
                          > default: default, type: string

tls.crt_file              Absolute path to Certificate file
                          > default: default, type: string

tls.key_file              Absolute path to private Key file
                          > default: default, type: string

tls.key_passwd            Optional password for tls.key_file file
                          > default: default, type: string

tls.vhost                 Hostname to be used for TLS SNI extension
                          > default: default, type: string
...
```

**Comment by ryn9** [comment]
@patrick-stephens 
https://github.com/fluent/fluent-bit-docs/pull/1172
I updated fluent-bit-docs/pipeline/inputs/http.md to have a similar section to "TLS / SSL" found in fluent-bit-docs/pipeline/output/http.md
