### ISSUE TITLE
support http header in input prometheus_scrape for bearer token

### ISSUE THREAD

**Issue by helmut72** [fluent/fluent-bit#7759]
**Is your feature request related to a problem? Please describe.**

For example Watchtower provides metrics through an enabled API. This API is ideally secured with a token:
https://containrrr.dev/watchtower/metrics/

**Describe the solution you'd like**

Support http headers in input prometheus_scrape for bearer tokens like it's possible for output prometheus_remote_write

**Comment by patrick-stephens** [comment]
I think there were some general HTTP header improvements in the works, I'm sure I saw an issue or PR somewhere...

**Comment by helmut72** [comment]
Would be great.

**Comment by patrick-stephens** [comment]
This is now covered via https://github.com/fluent/fluent-bit/pull/7785

**Comment by braydonk** [comment]
This wasn't me discussing it in the community meeting, but taking a look at the PR it looks good to me!

**Comment by helmut72** [comment]
This was fast, thank you!

**Comment by patrick-stephens** [comment]
Until a release is out, you can grab the test images/packages from the nightly builds to verify.

**Comment by helmut72** [comment]
Where can I find nightly docker images?

**Comment by helmut72** [comment]
Thank you. I have tested with Watchtower and Gitea and it works 🎉

**Comment by patrick-stephens** [comment]
Great, might be worth adding an example to the docs just to show it explicitly if you have time.

**Comment by helmut72** [comment]
Here is an example, but it's not much different to current prometheus_scrape example:

```
[INPUT]
    name         prometheus_scrape
    tag          gitea
    host         172.17.1.1
    port         3000
    bearer_token verysecret

[OUTPUT]
    name  stdout
    match gitea
```
