### ISSUE TITLE
Ability for Kubernetes filter plugin to alter tag

### ISSUE THREAD

**Issue by yann-soubeyrand** [fluent/fluent-bit#776]
**Is your feature request related to a problem? Please describe.**
When using Fluent Bit to gather Kubernetes logs, one has to make use of the tail input plugin and the Kubernetes filter plugin. However, it's difficult to route the logs because the tag does not carry enough metadata. The new Tag_Regex option of the tail input plugin can help by setting a tag of the form prefix.<namespace_name>.<pod_name>.<container_name>.<container_id> but that's not enough as we cannot distinguish between logs coming form container's stdout and stderr streams.

**Describe the solution you'd like**
To solve this problem, it would be great if Kubernetes filter plugin could rewrite event's tag to a tag of the form prefix.<namespace_name>.<pod_name>.<container_name>.<container_id>.<(stdout|stderr)>. Even better, the form of the rewritten tag could be configured as with the Tag_Regex option of the tail input plugin. Indeed, in some cases the pod name can be unnecessary.

**Describe alternatives you've considered**
As a workaround, I use the Tag_Regex option of the tail input plugin as described above and then rewrite the tag in fluentd to append the stream identifier.

**Additional context**
What I'm trying to accomplish is parsing and filtering Kubernetes logs with Fluent Bit prior to sending it to Elasticsearch or Fluentd. But doing so requires being able to distinguish logs coming from container's stdout from those coming from stderr (for both parsing and filtering).

**Comment by chiefy** [comment]
Just a note: if you use `Tag` and `Tag_Regex` w/ the `tail` input as specified above you *can not* use the `kubernetes` filter plugin - it will throw warnings and skip the log:

```
[ warn] [filter_kube] invalid pattern for given tag kube.logging.fluent-bit-wrdpf.fluent-bit
```

**Comment by yann-soubeyrand** [comment]
@chiefy you have to use the Regex_Parser option on the Kubernetes filter
```
Regex_Parser                   kubernetes-tag
```
and add the corresponding parser
```
[PARSER]
    Name                           kubernetes-tag
    Format                         regex
    Regex                          ^kubernetes\.[^.]+\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)$
```

**Comment by chiefy** [comment]
thanks @yann-soubeyrand that fixed it for me - 👍

**Comment by mailtoraja18** [comment]
> thanks @yann-soubeyrand that fixed it for me -

@chiefy if possible , can you please post your complete config. Thanks

**Comment by mitchellmaler** [comment]
I am getting the same error and I tried adding a Regex_Parser but it still is occurring.

```
[ warn] [filter_kube] invalid pattern for given tag kube.logging-system.fluent-bit.fluent-bit-vgxql.a7d880d0f01681b031ea2e642821b81aa1ab2176874b78bb24d05cf2a2832020
```

```
    [INPUT]
        Name              tail
        Tag               kube.<namespace_name>.<container_name>.<pod_name>.<docker_id>
        Tag_Regex         (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     256MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Path_Key          file

    [FILTER]
        Name                kubernetes
        Match               kube.**
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Regex_Parser        kubernetes-tag

    [PARSER]
        Name    kubernetes-tag
        Format  regex
        Regex   ^kube\.(?<namespace_name>[^_]+)\.(?<container_name>.+)\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<docker_id>[a-z0-9]{64})$
```

The regex works in rubular so I am unsure why it doesn't like the parser for the filter.

**Comment by qingling128** [comment]
Running into the same issue here. It no longer works:

Error:
```
[2019/06/24 07:12:39] [ warn] [filter_kube] invalid pattern for given tag k8s_container.kube-system.calico-node-vtxjz.calico-node.4fa34e485a248a3d7acd6b33cd939c4cba2b90a684f7155100127ccc0d151869
```

Config:
```
    [INPUT]
        # https://docs.fluentbit.io/manual/input/tail
        Name               tail
        Tag_Regex          (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Tag                k8s_container.<namespace_name>.<pod_name>.<container_name>.<docker_id>
        Path               /var/log/containers/*.log
        Parser             docker
        DB                 /var/log/fluent-bit-k8s-container.db
        Buffer_Chunk_Size  512KB
        Buffer_Max_Size    5M
        Rotate_Wait        30
        Mem_Buf_Limit      30MB
        Skip_Long_Lines    On
        Refresh_Interval   10
        storage.type       filesystem
...
    [FILTER]
        # https://docs.fluentbit.io/manual/filter/kubernetes
        Name                kubernetes
        Match               k8s_container.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Annotations         Off
        Regex_Parser        k8s-custom-tag
...
    [PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   ^k8s_container\.(?<namespace_name>[^_.]+)\.(?<container_name>[^.]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*+)\.(?<docker_id>[a-z0-9]{64})$
```

**Comment by chiefy** [comment]
@qingling128 @mitchellmaler depending on what version you are using, you need to add `Kube_Tag_Prefix` to your k8s filter. [Check the docs](https://docs.fluentbit.io/manual/filter/kubernetes#configuration-parameters) but it must match what's coming in!

**Comment by mitchellmaler** [comment]
@chiefy Do you have an example of adding the prefix? 
I tried setting the prefix to 'Kube_Tag_Prefix     kube.' but that still didn't work

**Comment by mitchellmaler** [comment]
@qingling128 @chiefy I figured it out.

Set 'Kube_Tag_Prefix to kube.'
Then change the PARSER to not include the tag prefix.
```
  [PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   (?<namespace_name>[^_.]+)\.(?<container_name>[^.]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*+)\.(?<docker_id>[a-z0-9]{64})$
```

**Comment by mitchellmaler** [comment]
@qingling128 Also your Tag Order namespace.pod.container is different from your parser order of namespace.container.pod

**Comment by qingling128** [comment]
@mitchellmaler Oh! Silly me. Thanks for taking a look!

**Comment by edsiper** [comment]
FYI:

The Rewrite Tag plugin has been implemented and is very flexible to compose new tags since it support different placeholders, it will be part of v1.4 release, for now you can read the draft docs here:

https://docs.fluentbit.io/manual/v/1.4-dev/pipeline/filters/rewrite-tag

**Comment by edsiper** [comment]
@yann-soubeyrand comments ?

**Comment by yann-soubeyrand** [comment]
> @yann-soubeyrand comments ?

Hi @edsiper, looks great, nice work, thank you ;-) I however cannot test since I work for a new company which sadly doesn't use Fluent Bit :-/

**Comment by DandyDeveloper** [comment]
@edsiper I'm actually in the process of testing this, although it seems I'm managing to get it through the rewrite, running `stdout` on a match for the new tag (and everything) shows no output. 

Just trying to work out how/why.

**Comment by edsiper** [comment]
configuration ?

**Comment by DandyDeveloper** [comment]
@edsiper 

```
    [FILTER]
        Name          rewrite_tag
        Match         *
        Rule          $kubernetes['labels']['app'] ^(.*)$ test.$0 false
```

I see that it's definitely going through this filter, as it never makes it to the stdout:

```
    [OUTPUT]
        Name    stdout
        Match   *
```

I am not super familiar with emitters, could it be how the process is being emitted? 

I also have a Kubernetes filter, I was going to test without this as well:

```
    [FILTER]
        K8S-Logging.Exclude     true
        K8S-Logging.Parser     true
        Kube_CA_File     xyz
        Kube_Token_File     xyz
        Kube_URL     https://kubernetes.default.svc:443
        Match     kube.*
        Merge_Log     true
        Name     kubernetes
```

**Comment by DandyDeveloper** [comment]
@edsiper 
```json
{
  "log"=>"A log example", 
  "stream"=>"stdout",
  "time"=>"2020-05-19T01:51:24.199314634Z",
  "kubernetes"=>{
    "pod_name"=>"sentry-worker-b74d97ff-jjb2p",
    "namespace_name"=>"sentry",
    "pod_id"=>"eed9fbc2-77d0-11ea-a826-16566d82eee4",
    "labels"=>{
      "app"=>"sentry",
      "pod-template-hash"=>"b74d97ff",
      "release"=>"sentry", 
      "role"=>"worker"
    }, 
    "annotations"=>{
      "anno1"=>"blah"
    }, 
    "host"=>"s241", 
    "container_name"=>"sentry-worker", 
    "docker_id"=>"50461dba186d2aa2306a1ea5d4454037313f8bce0dec3ad5b9fd9f65db8b1b7e"
  }
}
```

Here's a doc example.

**Comment by DandyDeveloper** [comment]
@edsiper 
```
{
  "log"=>"A log example", 
  "stream"=>"stdout",
  "time"=>"2020-05-19T01:51:24.199314634Z",
  "kubernetes"=>{
    "pod_name"=>"sentry-worker-b74d97ff-jjb2p",
    "namespace_name"=>"sentry",
    "pod_id"=>"eed9fbc2-77d0-11ea-a826-16566d82eee4",
    "labels"=>{
      "app"=>"sentry",
      "pod-template-hash"=>"b74d97ff",
      "release"=>"sentry", 
      "role"=>"worker"
    }, 
    "annotations"=>{
      "anno1"=>"blah"
    }, 
    "host"=>"node2", 
    "container_name"=>"sentry-worker", 
    "docker_id"=>"50461dba186d2aa2306a1ea5d4454037313f8bce0dec3ad5b9fd9f65db8b1b7e"
  }
}
```

Here's a doc example.

**Comment by edsiper** [comment]
I think you might have a configuration error, without the full content I cannot advise. 

Anyways I've created a minimized configuration that you can use to test the behavior, please refer to the file attached [776.tar.gz](https://github.com/fluent/fluent-bit/files/4659310/776.tar.gz)

**Comment by DandyDeveloper** [comment]
@edsiper This actually doesn't work:

```
dandy@DESKTOP-2GSHJ08:~/test/776$ docker run  -it --mount type=bind,source="/mnt/f/test/776",target=/app fluent/fluent-bit:1.4-debug /fluent-bit/bin/fluent-bit -c /app/fluent-bit.conf -R /app/parsers.conf
Fluent Bit v1.4.4
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/05/21 06:46:02] [error] [parser] parser named 'json' already exists, skip.
[2020/05/21 06:46:02] [ info] [storage] version=1.0.3, initializing...
[2020/05/21 06:46:02] [ info] [storage] in-memory
[2020/05/21 06:46:02] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/05/21 06:46:02] [ info] [engine] started (pid=1)
[2020/05/21 06:46:02] [ info] [sp] stream processor started
```

Nothing in the stdout?

**Comment by DandyDeveloper** [comment]
@edsiper Yeah that works locally, I am trying to figure out whether the Kubernetes filter is impacting this.

**Comment by DandyDeveloper** [comment]
@edsiper Is it possible that the kubernetes filter not properly escaping the JSON (`2020/05/21 07:46:08] [debug] [filter:kubernetes:kubernetes.0] could not merge JSON log as requested
`) is causing the output to be invalid and prompting the rewrite_tag to struggle reading the keys from the document and just failing to retag and just destroy the document? 

```
[2020/05/21 07:46:08] [debug] [input:tail:tail.0] file=/var/log/containers/rook-ceph-mgr-a-59cdf9b46c-xdcdn_rook-ceph_mgr-0f29f3dc7b1d12fea83e2e7680b9b6c8f0dd9aad07159f83a5c1c3fba8131859.log read=280 lines=1
[2020/05/21 07:46:08] [debug] [task] created task=0x7f1c96230e80 id=0 without routes, dropping.
[2020/05/21 07:46:08] [debug] [task] destroy task=0x7f1c96230e80 (task_id=0)
```

I see this for example for most of the events coming in.

**Comment by DandyDeveloper** [comment]
https://gist.github.com/DandyDeveloper/7dfc3f8545d08f81fd708fe3fa59c64d

Here's a Gist of my full config.

**Comment by edsiper** [comment]
can you provide a sample of the problematic log file ?, the config looks ok to me.

**Comment by DandyDeveloper** [comment]
@edsiper 

```
10.244.2.1 - - [07/Apr/2020:13:49:46 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
10.244.2.1 - - [07/Apr/2020:13:49:53 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
10.244.2.1 - - [07/Apr/2020:13:49:56 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
10.244.2.1 - - [07/Apr/2020:13:50:03 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
10.244.2.1 - - [07/Apr/2020:13:50:06 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
10.244.2.1 - - [07/Apr/2020:13:50:13 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
10.244.2.1 - - [07/Apr/2020:13:50:16 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.13"
```
These are the logs directly from `docker logs <container name>`

**Comment by DandyDeveloper** [comment]
@edsiper So.... I've tried this again today, and I'm going to say this is entirely my mistake on the filter heirarchy? 

I've moved the rewrite way down just to make sure it DEFINITELY went after the kubernetes filter and things are working....

So I'm guessing that it was somehow always going into the rewrite first and just being dropped because the k8s keys were not yet applied as it hadn't even gotten to that filter.

**Comment by edsiper** [comment]
Closing this since Tag rewrite feature is already in place.
