### ISSUE TITLE
FILTER - Parser - Nest parsed JSON under specific key

### ISSUE THREAD

**Issue by JohnPreston** [fluent/fluent-bit#7775]
As I use a Parse as follows

```
[PARSER]
    Name            cdk-proxy
    Format          json
    Time_Key        timestamp
    Time_Format     %FT%T.%L%z
    Time_Keep       Off
    Decode_Field json logging
```

And use it in the following config

```
[INPUT]
    name dummy
    tag dummy.data
    Samples 1
    Dummy {"log":"{\"instant\":{\"epochSecond\":1690415884,\"nanoOfSecond\":432855410},\"thread\":\"nioEventLoopGroup-2-1\",\"level\":\"DEBUG\",\"loggerName\":\"io.conduktor.proxy.rebuilder.components.AbstractReBuilder\",\"message\":\"Rebuilt ApiVersions request with proxy request header RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=record_exploder, correlationId=2941, headerVersion=2): ApiVersionsRequestData(clientSoftwareName='confluent-kafka-python', clientSoftwareVersion='1.9.2-rdkafka-1.9.2') version : 3 version from header : 3 \",\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.logging.slf4j.Log4jLogger\",\"contextMap\":{},\"threadId\":30,\"threadPriority\":10,\"timestamp\":\"2023-07-26T23:58:04.432+0000\"}\r"}

[SERVICE]
    Log_Level       debug

[SERVICE]
    Parsers_File /home/john/_TESTING/parsers.conf

[FILTER]
    Name record_modifier
    Match dummy.*
    Record ecs_cluster ANewCluster
    Record ecs_task_arn arn:aws:ecs:eu-west-1:111111111111:task/ANewCluster/b78e02165fb64f32804d3ab9303a3c81
    Record ecs_task_definition traefik:58

[FILTER]
    Name    lua
    Match   *
    code    function has_key(a,b)return a[b]~=nil end;function cb_filter(c,d,e)if not has_key(e,"time")then e["time"]=os.date("%F %H:%M:%S",d)end;return 1,d,e end
    call    cb_filter

[FILTER]
    Name            parser
    Parser          cdk-proxy
    Key_Name        log
    Match           dummy.*
    Reserve_Data    On
    Preserve_Key    Off


[OUTPUT]
    Name stdout
    Match dummy.*
    Format json
```

All the keys in the parsed JSON of my event are brought up at the "root" of the record.
I want to be able to perform the same operation but place all the keys extracted using my Parser to be nested within a user-defined key of the record.

For example

```
[FILTER]
    Name            parser
    Parser          cdk-proxy
    Key_Name        log
    Match           dummy.*
    Reserve_Data    On
    Preserve_Key    Off
    Nest_Under app_logs
```
Thank you

**Comment by JohnPreston** [comment]
> Here's a `[FILTER]` block you can add to nest the whole record under a different key ("nested" in the example):
> 
> ```
> [FILTER]
>     Name    lua
>     Match   *
>     code    function cb_filter(tag, ts, record) return 1, ts, { ['nested'] = record } end
>     call    cb_filter
> ```

Hey,
thanks for the suggestion. Although it works if the very first filter in the workflow is the `Parser` filter. If there were already other filters, such as `record_modifier` to add new fields to the record, these would get nested with it. Even if you had a common prefix for these keys you didn't want nested, the `lift` operation (with nest filter) does not support to use the `wildcard` argument and therefore everything found in `Nested_Under` gets lifted up.

**Comment by tarruda** [comment]
>  If there were already other filters, such as record_modifier to add new fields to the record, these would get nested with it

Can't you use `record_modifier` after the nest filter?

**Comment by domruf** [comment]
@JohnPreston have you ever found a solution for this?
I'm facing the same problem.

**Comment by RaJiska** [comment]
Interested for a solution here as well
