### ISSUE TITLE
Fluent-bit 2.1.6 gets rejected by elasticsearch 

### ISSUE THREAD

**Issue by nserev** [fluent/fluent-bit#7776]
## Bug Report

**Describe the bug**
We are trying to upgrade an old fluent-bit service that is working fine, however the new version seems to have some issues sending messages to the same elasticsearch cluster.

The version which we are trying to upgrade from is hosted on kubernetes 1.24.

Information about the currently working version is the following:

Version: 1.3.7
Configuration file: 
[fluent-bit-1.3.7.config.txt](https://github.com/fluent/fluent-bit/files/12229788/fluent-bit-1.3.7.config.txt)

We want to upgrade to version: 2.1.6
Configuration file: 
[fluent-bit-2.1.6.config.txt](https://github.com/fluent/fluent-bit/files/12229830/fluent-bit-2.1.6.config.txt)

When we start old service  we can see the following measurements:
![Screenshot_2023-08-01_16-43-56](https://github.com/fluent/fluent-bit/assets/4789693/946d9926-0472-4155-9dbe-faa9ac115ecc)

However the new service has the following graph:
![Screenshot_2023-08-01_16-46-28](https://github.com/fluent/fluent-bit/assets/4789693/6d85a2fa-f7e4-4c57-abce-f73ffa7ae4a6)

From what it seems it is trying to send too many messages to Elasticsearch and it is getting rejected. We can see the same in the logs too

```
error":{"type":"es_rejected_execution_exception","reason":"rejected execution of processing of [indices:data/write/bulk[s][p]]: request: BulkShardRequest
```

Switching back to old configuration works as expected every time and message processing works fine. Can someone help me to understand what should I need to tweak in order the new version to start working ?

Thank you.

**Comment by patrick-stephens** [comment]
It is quite a jump in versions so as @lecaros says it would be good to see full debug logs.
```
log_level debug
trace_output on
trace_error on
```
I'd have a look at the docs for some pointers: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

It may be you can tweak the operation used (`Write_Operation`) for sending data - I'm not sure what it was for 1.3.7...

**Comment by nserev** [comment]
Hello,

We have tried Write_Operation to be either `create`(default) or `upsert`. Both had same result.

Also we tried with `Workers` parameter which from docs it said had a different version before. 1.8.13

Below you can see debug attached. This is the only error that I see in the logs.

[fluent-bit-debug-trace-output.txt](https://github.com/fluent/fluent-bit/files/12240653/fluent-bit-debug-trace-output.txt)

**Comment by nserev** [comment]
Hi

Was this trace output of any use ? Do you have any ideas what can be the issue ?
