### ISSUE TITLE
newrelic output doesn't ignore excluded grep messages

### ISSUE THREAD

**Issue by yasserf** [fluent/fluent-bit#7777]
## Bug Report

I added the following exclude filter

```
[FILTER]
    Name grep
    Match *
    Logical_Op or
    Exclude log ^A\d\s.*
    Exclude log ^DEBUG IMAP:.*
```

and attached two different outputs, stdout and nrlogs

```
[OUTPUT]
  Name stdout
  Match *
  
[OUTPUT]
  Name nrlogs
  Match *
  api_key ...
```

The expected output was to see it not show up in newrelic and stdout, however the actual behavior is that it's ignored within the stdout printing but still within newrelic.

**Expected behavior**

Not to show up in newrelic (same behaviour as stdout)

**Your Environment**

* Version used: Fluent Bit v2.1.7
* Configuration: Stated above
* Environment name and version (e.g. Kubernetes? What version?): Using tail input from a file
* Server type and version: Auzre
* Operating System and version: Linux (Ubuntu)
* Filters and plugins: As stated above

**Additional context**

Trying to get this working to avoid sending a large amount (IE millions) of debug logs to the server by having some exclude patterns locally.

```
**To Replicate**

# Reference other files

[INPUT]
  Name   dummy
  Dummy  { "message": "B5 test" }

[FILTER]
  Name grep
  Match *
  Logical_Op or
  Exclude log ^A\d\s.*
  Exclude log ^DEBUG IMAP:.*
  Exclude log ^\*\s.*

[OUTPUT]
  Name stdout
  Match *

[OUTPUT]
  Name nrlogs
  Match *
  license_key ...
```

That input would show up in console and newrelic

```
[2023/08/01 17:37:20] [ warn] [engine] service will shutdown in max 5 seconds
[0] dummy.0: [[1690911439.920335126, {}], {"message"=>"B5 test"}]
[2023/08/01 17:37:20] [ info] [input] pausing dummy.0
```

where as 

```
[INPUT]
  Name   dummy
  Dummy  { "message": "A5 test" }
```

only shows up in newrelic (shouldn't show up in either)

**Comment by yasserf** [comment]
@patrick-stephens yup just added!

**Comment by patrick-stephens** [comment]
And are you sure the actual thing is showing up in New Relic and not just an artefact of earlier tests? I'd probably also switch up the `log_level debug` to see if anything shows up in the logs - nothing should get to the output is my understanding of what you want.

**Comment by yasserf** [comment]
yup pretty sure, A5 Test is showing up in logs in newrelic

<img width="425" alt="image" src="https://github.com/fluent/fluent-bit/assets/2734923/adf75ef8-deb5-414e-ae58-fddf0d012c0a">

**Comment by patrick-stephens** [comment]
Yeah, I'm a little concerned about the reference to other files.

Your actual grep filter doesn't actually function on the `message` key but on the `log` key.

What is the intended effect of the filter here just so we're clear, particularly when `message` = `dummy`.

```
[FILTER]
  Name grep
  Match *
  Logical_Op or
  Exclude log ^A\d\s.*
  Exclude log ^DEBUG IMAP:.*
  Exclude log ^\*\s.*
```
As you can see, nothing in the filter works on the `message` key.
My concern would be this is a big sequence of other filters so let's make sure we have the entire config to reproduce it.

`stdout` and `nr` should be identical though so it's confusing but just want to clarify.

**Comment by yasserf** [comment]
yeah i just caught the log and message key part as well, sorry about that, rushed through the example config.

Will run some more tests and update. Thank you fo the swift replies!

**Comment by patrick-stephens** [comment]
Trying to reproduce without new relic shows expected output per what I thought, i.e. the filter is not doing anything.

```shell
$ cat fluent-bit.conf
[INPUT]
  Name   dummy
  Dummy  { "message": "A5 test" }
  
[INPUT]
  Name   dummy
  Dummy  { "message": "B5 test" }

[FILTER]
  Name grep
  Match *
  Logical_Op or
  Exclude log ^A\d\s.*
  Exclude log ^DEBUG IMAP:.*
  Exclude log ^\*\s.*

[OUTPUT]
  Name stdout
  Match *

$ docker run --rm -it -v $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf fluent/fluent-bit:2.1.8
Fluent Bit v2.1.8
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/08/01 17:48:01] [ info] [fluent bit] version=2.1.8, commit=1d83649441, pid=1
[2023/08/01 17:48:01] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/08/01 17:48:01] [ info] [cmetrics] version=0.6.3
[2023/08/01 17:48:01] [ info] [ctraces ] version=0.3.1
[2023/08/01 17:48:01] [ info] [input:dummy:dummy.0] initializing
[2023/08/01 17:48:01] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/08/01 17:48:01] [ info] [input:dummy:dummy.1] initializing
[2023/08/01 17:48:01] [ info] [input:dummy:dummy.1] storage_strategy='memory' (memory only)
[2023/08/01 17:48:01] [ info] [filter:grep:grep.0] OR mode
[2023/08/01 17:48:01] [ info] [sp] stream processor started
[2023/08/01 17:48:01] [ info] [output:stdout:stdout.0] worker #0 started
[0] dummy.0: [[1690912081.359310137, {}], {"message"=>"A5 test"}]
[0] dummy.1: [[1690912081.359601111, {}], {"message"=>"B5 test"}]
[0] dummy.0: [[1690912082.359247415, {}], {"message"=>"A5 test"}]
[0] dummy.1: [[1690912082.359286180, {}], {"message"=>"B5 test"}]
```

**Comment by yasserf** [comment]
can verify that change message to log works, so likely something invalid in our config as well

**Comment by patrick-stephens** [comment]
Double check the full config, it may be there is something messing with the tags for a specific filter chain and only `stdout` picks it up but I cannot see how with the config above so probably need the full specific reproducer for it.

**Comment by patrick-stephens** [comment]
Filters apply in the order they are defined, i.e. the order they are encountered within the config file. If you use wildcard includes then no order is guaranteed for those so beware of that.

Inputs and outputs will always be before/after the filter chains regardless of when you define them. They can be considered independent.

**Comment by yasserf** [comment]
just tested for a while and can verify it works as expected

I'm not really sure what the issue was, the input key on tail was mapped to the name `message'` but I noticed in the console output that it was printing with was the keyword `log`. So I just changed them all to use log (the default) and it worked.

Thanks again fo the help, sorry for the dud issue 🙈
