### ISSUE TITLE
fluent-bit to kafka

### ISSUE THREAD

**Issue by xiaohuxiaoqian** [fluent/fluent-bit#7781]
## Bug Report
![1690972596521](https://github.com/fluent/fluent-bit/assets/37332000/b383ba76-d700-44c4-b43d-320cae1595d5)

![1690972641865](https://github.com/fluent/fluent-bit/assets/37332000/8465ec57-0bba-420d-a9cd-3a204812c4e4)

unable to collect logs

**Comment by patrick-stephens** [comment]
You're not using the config you have specified - you can see from the output that it is using CPU input and stdout output.
