### ISSUE TITLE
Ingested log files are garbled/encrypted

### ISSUE THREAD

**Issue by wmcclure01** [fluent/fluent-bit#7789]
## Bug Report

**Describe the bug**
Ingesting log files into Loki and the results of files are coming back as if they are encrypted somehow. I've left them without any parsing and an, admittedly, horrible attempt at parsing. The Parse seems to work with tagging and spacing but the data is still garbled nonsense.

**To Reproduce**

- Example log message if applicable:
```

{"time":"\u0000F\u0000i\u0000n\u0000i\u0000s\u0000h\u0000e\u0000d","message":"\u0000 \u0000i\u0000n\u0000 \u00000\u00000\u0000:\u00000\u00004\u0000:\u00003\u00003\u0000.\u00003\u00001\u00009\u0000 \u0000w\u0000i\u0000t\u0000h\u0000 \u00003\u0000 \u0000e\u0000r\u0000r\u0000o\u0000r\u0000s\u0000 \u0000a\u0000n\u0000d\u0000 \u00003\u0000 \u0000f\u0000i\u0000e\u0000l\u0000d\u0000 \u0000c\u0000o\u0000n\u0000v\u0000e\u0000r\u0000s\u0000i\u0000o\u0000n\u0000 \u0000e\u0000r\u0000r\u0000o\u0000r\u0000s\u0000\r\u0000"}

```
- Steps to reproduce the problem: 

**Expected behavior**
Files are straight .log text files. Exact log referenced above is here.
```
Started running D:\ProgramData\Alteryx\Service\Staging\8896_e0cce63a1bbc4daa9c2ad51151697716\Escalationquerytest.yxmd at Thu Aug  3 15:19:54 2023
00:00:00.003 - RunId - Alteryx: cc12f4b5-7a15-4c8c-ba76-bcafeb9b2c2e
00:00:00.025 - WorkflowId - Alteryx: 19f58740-3d5c-4e1d-a8c9-7b09e0799cd1
00:00:00.558 - ToolId 1: ODBC Driver version: 03.52
Finished in 00:00:02.076
```

**Screenshots**

**Your Environment**

* Version used: fluent-bit-2.1.8-win64.exe
* Configuration: 
```
[INPUT]
    Name        tail
    Path        D:\ProgramData\Alteryx\Logs\Alteryx_Log_*.log
    Tag         ayxworker_np.*
    #DB          ayxworker.sqlite
    Parser       gds
[OUTPUT]
    Name         loki
    Match        ayxworker_np.*
    labels       job=windows-gds
    Host         loki_endpoit
    port         443
    tls          on
    tls.verify   on
    http_user    loki-user
    http_passwd  loki@password
    tenant_id    gds
```
* Environment name and version (e.g. Kubernetes? What version?): Single AWS EC2
* Server type and version: 
* Operating System and version: Windows Server 2019 Datacenter
* Filters and plugins: Stock configuration

**Additional context**
Files are log

**Comment by patrick-stephens** [comment]
Check the encoding.

Using the stdout output will show you the data before it goes into Loki to verify there more easily too.

**Comment by leonardo-albertovich** [comment]
This is UTF-16 and sadly I don't think we have the means to do UTF-16 to UTF-8 conversion yet. There are plans to implement a decoder /  encoder system meant to handle this amongst other things but we're not there yet.
