### ISSUE TITLE
Publish JSON Schema in latest version

### ISSUE THREAD

**Issue by henrysachs** [fluent/fluent-bit#7814]
**Is your feature request related to a problem? Please describe.**

I would like to generate types for typescript to generate fluenbit config files from this language and validate them. Therefore I would like to use the json schema provided here: 

https://packages.fluentbit.io/2.1.8/fluent-bit-schema-2.1.8.json

**Describe the solution you'd like**

A Json Schema like described in this document: https://json-schema.org/draft/2020-12/json-schema-core.html

**Describe alternatives you've considered**

to be honest i haven't considered any because fluent-bit already provides these schemas not just in the format i expected. 

**Additional context**

**Comment by patrick-stephens** [comment]
What specifically is the issue with the format? 
https://packages.fluentbit.io/2.1.8/fluent-bit-schema-pretty-2.1.8.json

Is it something the tool does not like or something incorrect?
Trying to understand the requirements that are not being met.

Is there an automated way to verify the schema so we can build that in to CI as well?

**Comment by henrysachs** [comment]
I'm still searching for a tool to do this, but I tried to convert the schema to types with a tool like these: https://quicktype.io/ 
and it seems like it fails. I thought it is related to the schema being "wrong"

**Comment by patrick-stephens** [comment]
We do parse it for Go: https://github.com/calyptia/go-fluentbit-config

**Comment by henrysachs** [comment]
Maybe I need to find a different tool to generate the types from this Schema if it works for go. I thought it was Schema related because others seem to work :(

**Comment by patrick-stephens** [comment]
Or use the Go parser and export it for whatever you need? I imagine there are Golang libraries to help.

**Comment by JustinGrote** [comment]
I generated a JSON schema like @henrysachs was looking for here:
https://github.com/fluent/fluent-bit/issues/9289#issuecomment-2316416611
