### ISSUE TITLE
pls add Raw/Plaintext UDP  input

### ISSUE THREAD

**Issue by macaty** [fluent/fluent-bit#7828]
Many UDP type logs are not fixed types such as Syslog, we want to implement Raw/Plaintext UDP log format acceptance, so that we can add custom parsers to parse the corresponding logs.

**Comment by macaty** [comment]
like https://docs.fluentd.org/input/udp

**Comment by agup006** [comment]
I believe there is an input udp plugin though not documented, it should have same settings as input tcp

**Comment by cosmo0920** [comment]
in_udp doc will be handled here: https://github.com/fluent/fluent-bit-docs/pull/1165

**Comment by cosmo0920** [comment]
in_udp document is already available here: https://docs.fluentbit.io/manual/pipeline/inputs/udp
