### ISSUE TITLE
Runtime tests not enabled in CI

### ISSUE THREAD

**Issue by donbowman** [fluent/fluent-bit#783]
I notice that only the internal tests are enabled in travisci.
some of the runtime tests fail.
I've fixed a couple. But before I complete this and send a PR re-enabling, I thought I would ask, is there a reason?

Also, the rt-out-td can't pass I think, it relies on some info (td.conf) that is not in the repo. If i fix this, should i change FLB_ALL to not enable td? or should I change the test to 'pass' if that file is not present? Or ?

any comments?

**Comment by edsiper** [comment]
@donbowman 

the thing is that most of runtime tests requires external services but since they are not there in a CI mode they will give false positives.

**Comment by edsiper** [comment]
yes, avoid make test for now, so you do direct calls to the binary tests.

**Comment by donbowman** [comment]
some of these other ones seem not to have ever run? e.g. rt-modify and rt-nest are the same cut+paste code, and don't set the set_output callback.

**Comment by edsiper** [comment]
@donbowman if some test is incomplete or not functional, we will let the maintainers of that specific code to address the issues.
