### ISSUE TITLE
Docker run with -c configfile for overriding conf file but it failed due to load default conf file (multiline_parser).

### ISSUE THREAD

**Issue by pingpong-j** [fluent/fluent-bit#7831]
## Bug Report

**Describe the bug**
I try to run fluent-bit in a container, overriding my config file.
```
 docker run --mount type=bind,source=$mylocaldir,target=/usr/var/fluentbit -ti cr.fluentbit.io/fluent/fluent-bit:2.1.8-debug --config /usr/var/fluentbit/fluent-bit.conf
```

But it failed with this message.
```
Sections 'multiline_parser' and 'parser' are not valid in the main configuration file. It belongs to
the 'parsers_file' configuration files.
[2023/08/16 06:20:04] [error] configuration file contains errors, aborting.
```

It seems to load the default conf file because `parsers_file` field is located in this line.
https://github.com/fluent/fluent-bit/blob/master/conf/fluent-bit.conf#L28

I also tried to overwrite the directory (/fluent-bit/etc) to remove origin conf files. But it also failed.

**To Reproduce**
This is my conf file. It doesn't use a multiline feature.
```
[INPUT]
    Name        tail
    Path        /usr/var/fluentbit/log/*.log

[Parser]
    Name        json
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S%z # ex) 2023-08-14T02:54:51Z

[Output]
    Name        es
    Match       *
    Host        $myhost
    Port        $myport
    compress    gzip
    Generate_ID On
    Logstash_Format On
    Logstash_Prefix traefik-fluentbit-test
```

**Expected behavior**
1. I can run a fluent-bit process in container with only my custom conf files. (my original intention)
2. fluent-bit does not load default fluent-bit.conf file on passing another conf file as an argument.

**Screenshots**

**Your Environment**
* Version used: 2.1.8, 2.1.8-debug
* Configuration: describe above
* Environment name and version (e.g. Kubernetes? What version?): docker
* Server type and version:
* Operating System and version: MacOS
* Filters and plugins: no

**Additional context**

**Comment by patrick-stephens** [comment]
The issue is what the error says - you cannot include a `[PARSER]` definition (or a multiline one) in the main config file. Your config file should load a parsers file that defines the parser not include it inline.

```
Sections 'multiline_parser' and 'parser' are not valid in the main configuration file. It belongs to the 'parsers_file' configuration files.
```

Your config above includes a `parser` section hence the error:
```
[INPUT]
    Name        tail
    Path        /usr/var/fluentbit/log/*.log

[Parser] <--- this cannot be in the main config file
    Name        json
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S%z # ex) 2023-08-14T02:54:51Z

[Output]
``

**Comment by pingpong-j** [comment]
Aha. Sorry for bothering you. 
I miss it though the document contains this.
```
All parsers must be defined in a parsers.conf file, not in the Fluent Bit global configuration file. T
```
