### ISSUE TITLE
Parser using large Regex expression not supported - causes fluent-bit startup error

### ISSUE THREAD

**Issue by KlDec** [fluent/fluent-bit#7836]
## Bug Report

**Describe the bug**
Using fluent-bit with RegEx to parse log data. Parser definition looks like this:
[PARSER]
    Name P1
    Format regex
    RegEx <HERE GOES THE EXPRESSION>
    Time_Key time
    Time_Format %Y-%m-%d %H:%M:%S %z

with <HERE GOES THE EXPRESSION> being a 12kB long regular expression, that has been verified at https://rubular.com/ successfully and with good performance.

During startup, fluentbit logs the following error and shuts down:
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 systemd[1]: Started TD Agent Bit BM EHEKT.
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: #033[1mFluent Bit v1.6.3#033[0m
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: * #033[1m#033[93mCopyright (C) 2019-2020 The Fluent Bit Authors#033[0m
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: * #033[1m#033[93mCopyright (C) 2015-2018 Treasure Data#033[0m
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: * https://fluentbit.io
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: [2023/08/16 16:35:01] [  Error] File /home/bmon/Data/EHEKT/Fluentbit-EHEKT-Parsers.conf
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 Fluentbit-EHEKT[1188173]: [2023/08/16 16:35:01] [  Error] Error in line 3: Length of content has exceeded limit
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 systemd[1]: Fluentbit-EHEKT.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 16:35:01 PubD-ubuntu-2gb-hel1-1 systemd[1]: Fluentbit-EHEKT.service: Failed with result 'exit-code'.

Line 3 in Fluentbit-EHEKT-Parsers.conf contains the regular expression (all in one line, no line breaks etc). 

**Expected behavior**
fluent-bit should handle long regular expressions to allow parsing long data streams. The size of the regular expression should be configurable in case it is so limited as is by default

**Your Environment**
* Version used:  v1.6.3
* Configuration: fluent-but runs as demon 24x7 on a Linux machine in the cloud
* Operating System and version: Ubuntu 20.04.1 LTS
* Filters and plugins:
[INPUT]
    Name  tail
    Tag   P1
    Path  ${BM_DATAHOME}/${SITE}/*01_*.csv
    Parser P1
[FILTER]
    name grep
    match *
    exclude log ^.*$
[OUTPUT]
    Name  pgsql
    Match *
    Host  127.0.0.1
    Port  5432
    Database XX
    Table YYYY
    User  ZZZZ
    Password ZZZZZZZZZZZ
    Timestamp_key timestamp

**Comment by patrick-stephens** [comment]
Version 1.6.3 is very old now, please try the latest 2.1.8 to confirm if it is still an issue.

**Comment by KlDec** [comment]
Verified with 2.1.8 and the issue is resolved in this release. Thanks a lot Patrick.
