### ISSUE TITLE
input kafka do not see any message value

### ISSUE THREAD

**Issue by supamas-tec** [fluent/fluent-bit#7844]
this is my message in kafka
![image](https://github.com/fluent/fluent-bit/assets/101784230/1fbf5f95-b81d-4fd9-8c37-1bdc10ffc655)

this is my fluentbit config
```yaml
[INPUT]
        Name kafka
        brokers kafka.kafka.svc:9092
        Topics      fluentbit-test
        group_id fluentbit-group
        poll_ms 100
[OUTPUT]
        Name   stdout
        Match  *
        Format json_lines
```
this is my output
`
{"date":1692609619.335278,"topic":"fluentbit-test","partition":0,"offset":188921,"error":null,"key":"message"}
`
i'm not see any message value.did i do anything wrong?

**Comment by agup006** [comment]
Heya are you running the latest version? There were some errors with json data in Kafka

**Comment by supamas-tec** [comment]
@agup006 
first i use version 2.1.7 and i try use 2.1.8 from your suggestion.
It's work.thank you
