### ISSUE TITLE
MQTT input plugin: store mqtt payload under own field in output record

### ISSUE THREAD

**Issue by JSchy65** [fluent/fluent-bit#7845]
Actually, the MQTT input plugin outputs a record of received mqtt message in the following form (example):
{"date": 1692605819.581571, "topic": "topicA/topicB", "hostname": "clientA", **"a": "abc", "b": 123**}

**Mqtt payload and metadata are intermixed** !
In the above example, "a" and "b" are the mqtt payload and the other fields are metadata.

**One problem** is, that in output plugins, it is not possible to use the "log_key" (Amazon S3) or "template" (File) mechanism to only store the payload. If you want to store the payload only, you need to delete the unwanted meta data fields with a set of "record_modifier" filters. This is possible but makes the configuration unnecessarily complex. And it breaks, if for some reason the meta data is extended by a new field.

**Another problem** is, that if in the payload there is a field with the same name as in the metadata, that both fields interfere with each other which may lead to unexpected result.

To prevent such problem, **the requested feature is to store the mqtt payload in an own field**, e.g.
{"date": 1692605819.581571, "day": "2023-08-21", "topic": "topicA/topicB", "hostname": "clientA", "**payload": {"a": "abc", "b": 123}**}

This would be the same logic as for example for the http input plugin. That stores it's payload in the "log" subfield, e.g.
{"date": 1692605786.000000, "hostname": "clientA", "container_name": "/eclipse-mosquitto-A11", "day": "2023-08-21", **"log": "2023-08-21 08:16:26+0000: New connection from 172.18.0.1:46912 on port 1883."**}

This would make post processing of the payload data much easier and removes the inconsistence between the usage of different plugins and therefore makes the usage of the Fluent Bit universe more consistent for the users.

**To be compatible with the actual version**, the idea is to introduce a new configuration parameter "payload_key". If the parameter doesn't exist, the behavior is the same as today and payload and metadata are still intermixed. If the "payload_key" ist set to a value, e.g. "payload", the mqtt payload is stored in that subfield as shown above.

**Comment by nokute78** [comment]
I pushed a patch #7872 and it was merged.
