### ISSUE TITLE
Parsing date fails when fractional seconds are all zeros 

### ISSUE THREAD

**Issue by squalou** [fluent/fluent-bit#7850]
## Bug Report

**Describe the bug**

Parsing date format using a pattern does not allow to parse dates when fractions of seconds are zero, and as a result omitted. (which seems to be allowed by strptime doc)

An example will be much more explicit, consider real-life logs below (from sonarQube to name it):

```json
{ ...., "timestamp":"2023-08-17T09:50:57.999Z", ...}
{ ...., "timestamp":"2023-08-17T09:50:58Z", ...}
{ ...., "timestamp":"2023-08-17T09:50:58.001Z", ...}
```

From fluentbit documentation I tried to use `%Y-%m-%dT%H:%M:%S.%L%z`

Which will fail with `2023-08-17T09:50:58Z`

I have no way to change source logs behaviour.

Here's a link to a question asked in sonarQube forum, (in answer they 're asking to ask fluentbit'sadvice ;) )

https://community.sonarsource.com/t/sonarqube-server-json-log-format-inconsistent-time-missing-zeros-make-it-hard-to-parse/97610

According to them, from strptime documentation `leading zeros are permitted but not required.` , which explains that `.000` are omitted, but ... I still have an issue with the `.` separator that is missing.
 
Is there any way to set the pattern with facultative fields ?

**To Reproduce**
- Example log message if applicable:
```
{"process":"web","timestamp":"2023-08-17T09:50:57.999Z","severity":"INFO","logger":"org.sonar.server.platform.web.MasterServletFilter","message":"Initializing servlet filter org.sonar.server.platform.web.WebServiceReroutingFilter@7ad8fb8f [pattern=UrlPattern{inclusions=[/api/components/update_key, ...], exclusions=[]}]"}
{"process":"web","timestamp":"2023-08-17T09:50:58Z","severity":"INFO","logger":"org.sonar.server.platform.web.MasterServletFilter","message":"Initializing servlet filter org.sonar.server.authentication.DefaultAdminCredentialsVerifierFilter@2ae6cce1 [pattern=UrlPattern{inclusions=[/*], exclusions=[*.css, ...]}]"}
{"process":"web","timestamp":"2023-08-17T09:50:58.001Z","severity":"INFO","logger":"org.sonar.server.platform.web.MasterServletFilter","message":"Initializing servlet filter org.sonar.server.authentication.InitFilter@5fc4896c [pattern=UrlPattern{inclusions=[/sessions/init/*], exclusions=[]}]"}
```

Will result with following error

```
[2023/08/22 09:41:47] [error] [parser] cannot parse '2023-08-17T09:50:58Z'
```

- Steps to reproduce the problem:

Use following configuration

parser
```
[PARSER]
    Name        sonar
    Format      json
    Time_Key    timestamp
    Time_Format  %Y-%m-%dT%H:%M:%S.%L%z

```

conf
```
[SERVICE]
    flush                 1
    log_level             debug
    parsers_file          /fluent-bit/etc/fluent-bit-parsers.conf

[INPUT]
    name tail
    path /test.log
    read_from_head true

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       sonar

[OUTPUT]
    Name stdout
    Match *

```

**Expected behavior**

3 logs in above example are correctly parsed

**Your Environment**

* Version used: 2.31.11
* Configuration: local docker (linux)
* Environment name and version : target environment : AWS ECS
* Server type and version: laptop :)
* Operating System and version: linux 6.4.6
* Filters and plugins:

**Additional context**

**Comment by nokute78** [comment]
Hmm, golang and ruby also failed to parse the timestamp.
They expect `.000`.

```ruby
require  'time'

p Time.strptime("2023-08-17T09:50:58Z", "%Y-%m-%dT%H:%M:%S.%L%z")
```

```
$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
$ ruby ~/a.rb 
/usr/lib/ruby/3.0.0/time.rb:452:in `strptime': invalid date or strptime format - `2023-08-17T09:50:58Z' `%Y-%m-%dT%H:%M:%S.%L%z' (ArgumentError)
	from /home/taka/a.rb:3:in `<main>'
```

Golang also failed.

```go
package main

import (
	"fmt"
	"time"
)

func print_time(s string) {
	t, err := time.Parse("2006-01-02T15:04:05.000Z", s)
	if err != nil {
		fmt.Printf("error %s\n", err)
		return
	}
	fmt.Printf("time = %v\n", t)
}

func main() {
	print_time("2023-08-17T09:50:58Z")
	print_time("2023-08-17T09:50:58.001Z")
}
```

```
$ go run ~/a.go 
error parsing time "2023-08-17T09:50:58Z" as "2006-01-02T15:04:05.000Z": cannot parse "Z" as ".000"
time = 2023-08-17 09:50:58.001 +0000 UTC
```

**Comment by squalou** [comment]
Thank you, I relayed this to sonar.
It makes sense honestly that they keep a regular format.

No hope for a 'facultative' approach existing and that I would have missed when reading the doc ?

**Comment by nokute78** [comment]
Lua filter plugin is flexible.
Following example is to append `.000`.

```lua
function test(tag, timestamp, record)
         ts = record["timestamp"]

         if string.find(ts, "%.%d%d%dZ") then
            return 0, timestamp, record
         end

         new_record = record
         new_record["timestamp"] = string.sub(ts,1,-2) .. ".000Z"
         return 2, timstamp, new_record
end
```

```
[INPUT]
    Name dummy
    Dummy {"key":"value", "timestamp":"2023-08-17T09:50:58Z"}
    Samples 1

[INPUT]
    Name dummy
    Dummy {"key":"value", "timestamp":"2023-08-17T09:50:58.001Z"}
    Samples 1

[FILTER]
    Name lua
    Match *
    Script b.lua
    Call test

[OUTPUT]
    Name stdout
    Match *
```

Log:
```
$ bin/fluent-bit -c b.conf 
Fluent Bit v2.1.9
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/08/27 07:49:04] [ info] [fluent bit] version=2.1.9, commit=a2105c2c25, pid=3779
[2023/08/27 07:49:04] [ info] [storage] ver=1.2.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/08/27 07:49:04] [ info] [cmetrics] version=0.6.3
[2023/08/27 07:49:04] [ info] [ctraces ] version=0.3.1
[2023/08/27 07:49:04] [ info] [input:dummy:dummy.0] initializing
[2023/08/27 07:49:04] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/08/27 07:49:04] [ info] [input:dummy:dummy.1] initializing
[2023/08/27 07:49:04] [ info] [input:dummy:dummy.1] storage_strategy='memory' (memory only)
[2023/08/27 07:49:04] [ info] [sp] stream processor started
[2023/08/27 07:49:04] [ info] [output:stdout:stdout.0] worker #0 started
[0] dummy.0: [[1693090145.977023695, {}], {"timestamp"=>"2023-08-17T09:50:58.000Z", "key"=>"value"}]
[0] dummy.1: [[1693090145.977263745, {}], {"key"=>"value", "timestamp"=>"2023-08-17T09:50:58.001Z"}]
^C[2023/08/27 07:49:11] [engine] caught signal (SIGINT)
```

**Comment by squalou** [comment]
Looks soooo promising !
Except I have an issue I can't understand.

When using "Dummy" input just like you, it works.

*but*

using a 'tail' input as this : 

```
[INPUT]
    name tail
    path /test.log
    read_from_head true
 ```
 
 with the file `test.log` containing my log strings example, 
 they all get "trapped" as string in a "log" field, "record" looks like this
 
 If I add 
 
 ```lua
         print(record)
        print(record["log"])
```
here's what I see

```
table: 0x7ff6faa1dcc0
{"process":"app","timestamp":"2023-08-16T10:58:10Z","severity":"INFO","logger":"org.sonar.application.SchedulerImpl","message":"SonarQube is operational"}

```

but `record["timestamp"]` is `nil` and `record["log"]["timestamp"]` fails with a message telling me `record["log"]` is a string, not a table.

And of course can't find anything relevant in 'lua' plugin documentation.

**Comment by squalou** [comment]
Damn ... looks like I need to *first* parse as json but ... it's the json parser that is responsible for timestamp pattern recognition ... that's a nice vicious circle :)

**Comment by squalou** [comment]
\o/

https://sonarsource.atlassian.net/browse/SONAR-20331


Sonar qualified this as a bug on their side, so ... closing this issue here and waiting for their fix :)

thanks again to participants here.
