### ISSUE TITLE
Event timestamp reset to epoch 0 when a filter parser doesn't match

### ISSUE THREAD

**Issue by paebersold-tyro** [fluent/fluent-bit#7854]
## Bug Report

Not sure if this is a bug or by design.  However the behaviour was unexpected and couldn't find any documentation covering it.

**Describe the bug**
When using a custom parser when no match is achieved the timestamp of the fluent-bit event is set to epoch 0 (ie 0.000000000)

**To Reproduce**
- Running fluent-bit via docker
- use 'logger' to send a test message that will match
```
logger -T -p local1.info -t bob-sammy -P 9999 -n 1.2.3.4 'test message'
```
we see in the logs
```
[0] my_syslog: [[1692744599.857157000, {}], {"mymatch"=>"sammy", "pri"=>"142", "time"=>"2023-08-23T08:49:59.857157+10:00", "host"=>"syslog-1-mc", "ident"=>"bob-sammy", "pid"=>"-", "msgid"=>"-", "extradata"=>"[timeQuality tzKnown="1" isSynced="1" syncAccuracy="369421"]", "message"=>"test message"}]
```
- Steps to reproduce the problem:

However if we send a message that does not match
```
logger -T -p local1.info -t nomatch -P 9999 -n 1.2.3.4 'test message'
```
in the logs
```
[0] my_syslog: [[0.000000000, {}], {"pri"=>"142", "time"=>"2023-08-23T08:50:17.537377+10:00", "host"=>"syslog-1-mc", "ident"=>"nomatch", "pid"=>"-", "msgid"=>"-", "extradata"=>"[timeQuality tzKnown="1" isSynced="1" syncAccuracy="378421"]", "message"=>"test message"}]
```

note event timestamp now 0.000000000

**Expected behavior**
Event timestamp would not be modified

**Your Environment**
* Version used: 2.1.2
* Configuration:

 fluent-bit.conf

[SERVICE]
	flush 1
	log_level info
	dns_mode                TCP
	parsers_file            parsers.conf
	parsers_file            custom-parsers.conf

[INPUT]
	Name            syslog
	Alias           syslog
	Tag             my_syslog
	Listen          0.0.0.0
	Parser          syslog-rfc5424
	Mode            tcp
	Port            9999

[FILTER]
	Name            parser
	Match           my_syslog 
	Key_Name        ident
	Parser          mytest
	Preserve_Key          true
	Reserve_Data          true

[OUTPUT]
	Name stdout
	Match *

custom-parsers.conf

[PARSER]
    Name mytest
    Format regex
    Regex ^bob-(?<mymatch>[^ ]*)$

* Environment name and version (e.g. Kubernetes? What version?): Docker image
* Server type and version: Docker 20.10
* Operating System and version: SLES 12.5

**Additional context**
We normally send syslog messages to fluent-bit and then output the messages to Loki.  However as the timestamp is reset Loki rejects these messages as being too old (as expected as they are from 1970 now).

So is the resetting of the timestamp intended as there was no match or is there some configuration that I have missed?

Thank you.

**Comment by patrick-stephens** [comment]
Can you try with 2.1.8?

**Comment by paebersold-tyro** [comment]
Thanks for the quick response.  Yep, 2.1.8 solved the issue, thank you.
