### ISSUE TITLE
 Retain file position in tail input plugin during HTTP interface failure

### ISSUE THREAD

**Issue by studyhuang1996** [fluent/fluent-bit#7856]
## Bug Report

**Describe the bug**
I'm currently using the tail input plugin in Fluent Bit to sync data to an HTTP interface. The plugin uses a database to persist the file position for resuming tailing after restarts or failures.

However, I've noticed that when the HTTP interface is down or experiences errors, the data corresponding to that period gets lost. It seems that the database position is updated even during interface failures.

I would like to propose a feature enhancement where the tail plugin's database position persistence can be configured not to update during interface failures. This way, when the interface recovers, Fluent Bit can resume reading data from the point where it failed.

This would enable higher fault tolerance and prevent data loss in scenarios where the HTTP interface experiences temporary issues.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[SERVICE]
    flush        1
    log_level    debug
    parsers_file parsers.conf
[INPUT]
    Name         tail
    Tag          mysql_audit
    Path        audit-test.log
    Parser       json
    DB        mysql_audit_db.db
    Read_from_Head  true
    skip_empty_lines  on
    Refresh_Interval 5s
    Buffer_Chunk_Size 2m
    buffer_max_size  30m
[FILTER]
    Name      lua
    Match      *
    script  audit_script.lua
    call   auditDataModify
[FILTER]
    Name modify
    Match *
    ADD  SERVER_IP  **
    Rename ID   EVENT_ID
[OUTPUT]
    Name http
    Match *
    Host 127.0.0.1
    Port 8123
    URI /?query=INSERT+INTO+test+FORMAT+JSONEachRow
    http_user ***
    http_passwd ***
```

**Expected behavior**
data not lose

**Your Environment**
* Version used: 2.1.6
* Configuration:
* Server type and version:
* Operating System and version: linux
* Filters and plugins:

**Comment by agup006** [comment]
Ah this is a nice idea, if I understand correctly we would still continue retry but upon a failed retry not update the tail file position such that we resume from where we were last. 

A couple considerations though could be log rotate for high volume, metrics that would show dropped when in reality fluent bit would duplicate to resend

**Comment by studyhuang1996** [comment]
Yes, what you want is to stop the service directly after retrying, without updating the offset of db, so that the next recovery starts reading from the current position, rather than discarding the current log after a few retries, resulting in data loss
