### ISSUE TITLE
[engine] caught signal (SIGSEGV)

### ISSUE THREAD

**Issue by jaksonwkr** [fluent/fluent-bit#7858]
## Bug Report

**Describe the bug**
Fluent-bit restarts frequently

**To Reproduce**

```
[2023/08/23 17:44:08] [debug] [output:stackdriver:stackdriver.0] [logging.googleapis.com/monitored_resource] not found in the payload
[2023/08/23 17:44:08] [debug] [http_client] not using http_proxy for header
[2023/08/23 17:44:08] [debug] [net] socket #81 could not connect to 2001:4860:4802:34::174:443
[2023/08/23 17:44:08] [debug] [net] socket #81 could not connect to 2001:4860:4802:36::174:443
[2023/08/23 17:44:08] [debug] [net] socket #81 could not connect to 2001:4860:4802:32::174:443
[2023/08/23 17:44:08] [debug] [net] socket #81 could not connect to 2001:4860:4802:38::174:443
[2023/08/23 17:44:08] [engine] caught signal (SIGSEGV)
#0  0x7fd30602a5f3      in  ???() at ???:0
#1  0x7fd306056af1      in  ???() at ???:0
#2  0x55c41b168a6a      in  tls_net_handshake() at src/tls/openssl.c:544
#3  0x55c41b16974d      in  flb_tls_session_create() at src/tls/flb_tls.c:529
#4  0x55c41b19ff17      in  flb_io_net_connect() at src/flb_io.c:162
#5  0x55c41b10d8fe      in  create_conn() at src/flb_upstream.c:577
#6  0x55c41b10dec9      in  flb_upstream_conn_get() at src/flb_upstream.c:766
#7  0x55c41b4d6a30      in  cb_stackdriver_flush() at plugins/out_stackdriver/stackdriver.c:2538
#8  0x55c41b0cd10c      in  output_pre_cb_flush() at include/fluent-bit/flb_output.h:590
#9  0x55c41bc1c6c6      in  co_init() at lib/monkey/deps/flb_libco/amd64.c:117
#10 0xffffffffffffffff  in  ???() at ???:0
```
- Steps to reproduce the problem:

Configure Stackdriver output plugin

**Expected behavior**

It looks like it's trying to connect to Stackdriver through IPv6, but my network only supports IPv4.
It should try IPv4 if IPv6 fails.

**Screenshots**

**Your Environment**

* Version used: 2.1.8
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.25
* Server type and version:
* Operating System and version:
* Filters and plugins: Tail, Kubernetes and Stackdriver

**Additional context**

**Comment by jaksonwkr** [comment]
To fix the problem I set net.dns.prefer_ipv4 to true

**Comment by leonardo-albertovich** [comment]
Thanks or reporting this issue, is this something that triggers frequently or in a somewhat deterministic way? 

It would be very helpful if you tried to reproduce the issue with a different plugin (ie. http) but I undestand that you might not have the resources to do so.

**Comment by jaksonwkr** [comment]
It happens frequently.
I'll try to test with http plugin and let you know here
