### ISSUE TITLE
in_kafka: Infinite loop until OOM

### ISSUE THREAD

**Issue by Starfa** [fluent/fluent-bit#7859]
## Bug Report
Fluent-bit will attempt to read all Kafka messages, causing memory to continually increase until reaching OOM KILLED.
I looked at the code of the in_kafka plugin and found that the problem occurs here.
```
static int in_kafka_collect(struct flb_input_instance *ins,
                            struct flb_config *config, void *in_context)
{
    int ret;
    struct flb_in_kafka_config *ctx = in_context;
    rd_kafka_message_t *rkm;

    ret = FLB_EVENT_ENCODER_SUCCESS;

    while (ret == FLB_EVENT_ENCODER_SUCCESS) {
        rkm = rd_kafka_consumer_poll(ctx->kafka.rk, 1);

        if (!rkm) {
            break;
        }

        flb_plg_debug(ins, "kafka message received");

        ret = process_message(ctx, rkm);

        rd_kafka_message_destroy(rkm);

        /* TO-DO: commit the record based on `ret` */
        rd_kafka_commit(ctx->kafka.rk, NULL, 0);
    }
    // ...........
}
```

**To Reproduce**
1. Testing environment with limited available memory, such as 1GB.
2. Creating a Kafka topic with a data size exceeding 1GB.
3. Running fluent-bit to consume this topic.

**Expected behavior**
Can consume Kafka messages normally.

**Your Environment**
* Version used: version=2.1.9, commit=8ae604e5a6
* Filters and plugins: in_kafka

**Comment by agup006** [comment]
Would you be able to try and adjust the rdkafka buffer / queue settings? I believe its 100k messages in queue by default which of course is huge

**Comment by pavel-orlov** [comment]
I have the similar issue and it seems the plugin blocks other plugins for processing or output while there are still messages in the kafka queue. For example, if the consumer or network is down for a while, it leads to a big offset between latest and current. The plugin seems to lock all other activities in fluent bit until it consumes all the messages in the queue. 
@tarruda Can you please look at this?

**Comment by Starfa** [comment]
> Would you be able to try and adjust the rdkafka buffer / queue settings? I believe its 100k messages in queue by default which of course is huge

I've been trying to learn about rdkafka, and I found out that when its queue buffer reaches either of these two conditions: queue length of 100k or a queue size of 50M, it will stop prefetching. Therefore, when using the default settings, the maximum size of the rdkafka queue buffer can only reach up to 50M.

**Comment by Starfa** [comment]
> Would you be able to try and adjust the rdkafka buffer / queue settings? I believe its 100k messages in queue by default which of course is huge

When one of these two conditions is met, rdkafka queue buffer will stop prefetching: queue length of 100k or a queue size of 50M. Therefore, when using the default settings, the maximum size of the rdkafka queue buffer can only reach up to 50M.

Does this method cache the received Kafka messages in the memory of Fluent Bit? If so, I think it could be the root cause.
```
static int process_message(struct flb_in_kafka_config *ctx,
                           rd_kafka_message_t *rkm)
```
