### ISSUE TITLE
please support the chunk option in in_forward module 

### ISSUE THREAD

**Issue by komeda-shinji** [fluent/fluent-bit#786]
According to the fluentd protocol, in PackedForward Mode, when a server receives the chunk option from a client, the server MUST respond ack. 
But fluent-bit does not understand the chunk option, no response will be returned.

**Comment by dsouzajude** [comment]
Also looking forward to this fix :)

**Comment by zhanghjster** [comment]
looking forward to it too :)

**Comment by luben** [comment]
Yes, with TCP reconnect on each forwarded frame (current behavior) it can easily lead to port exhaustion in high throughput cases.

**Comment by edsiper** [comment]
Fixed in f838308d

It will be part of v1.5 release on July 13th. 

thanks!
