### ISSUE TITLE
Fluent Bit Event Format Issue

### ISSUE THREAD

**Issue by OriMeyuhas** [fluent/fluent-bit#7861]
**Description:**
I’m working with Grafana Loki and Fluentd on an EKS cluster. On my IoT device, I have Fluent Bit installed to forward logs to Fluentd. By default, Fluent Bit sends logs in the format `[[TIMESTAMP, METADATA], MESSAGE]`. However, I’m trying to forward only the `MESSAGE` part to Fluentd since Grafana Loki is already capturing its own timestamp.
The current output from Fluent Bit looks like this:
```
[0] sensor: [[1692719658.517654104, {}], {“log”=>“hello”}]
```
When this is received by Grafana Loki, it appears as:
```
2023-08-22 17:54:18.935 log=hello
2023-08-22 17:54:18.935 [2023-08-22 14:54:18.090994403 +0000, {}]
```
![Screen Shot 2023-08-24 at 13 02 17](https://github.com/fluent/fluent-bit/assets/107118002/8271e208-a605-4bb3-ac79-babbc36172bf)

---
**Expected Behavior:**
1. I’d like to have an option or method to forward only the `MESSAGE` part from Fluent Bit, without the timestamp.
2. If the timestamp cannot be excluded, the message should be forwarded in a single line instead of two.

**Actual Behavior:**
Currently, Fluent Bit always includes the timestamp in the event format, and I haven’t found a way to exclude it. Additionally, the message is split into two lines.

**Configuration:**
Here’s my Fluent Bit configuration:
```ini
[SERVICE]
    Flush       1
    Daemon      Off
    Log_Level   debug
[INPUT]
    Name        tail
    Path        /path/to/file/text.txt
    Tag         sensor
[OUTPUT]
    Name        http
    Match       *
    Host        my-host
    Port        80
[OUTPUT]
    Name        stdout
    Match       *
```
---
**Additional Context:**
If there’s a workaround or a recommended approach to achieve this, I’d appreciate any guidance. Otherwise, considering this as a feature request would be beneficial for scenarios where the receiving end (like Fluentd) already captures timestamps and prefers single-line messages.

**Comment by agup006** [comment]
Hey @OriMeyuhas I see you are not using the Loki plugin, can you try with that in your configuration?

**Comment by OriMeyuhas** [comment]
@agup006,
Thank you for your suggestion. However, in my setup, I'm using Fluentd as an intermediary aggregator. The logs are sent from Fluent Bit to Fluentd, and then Fluentd forwards them to Loki. Due to this architecture, I'm not using the Loki plugin directly in Fluent Bit. Instead, I'm relying on Fluentd to handle the forwarding to Loki.
