### ISSUE TITLE
Unexpected 400 ( invalid requests ) errors between HTTP_OUTPUT and INPUT plugin

### ISSUE THREAD

**Issue by nmr** [fluent/fluent-bit#7864]
## Bug Report

Hi,

In my testing environment I send logs from kubernetes cluster to the external ELK stack via fluentbit daemonset ( fluent-bit:2.1.7 ). In my configuration I use HTTP_INPUT filter which will send data to the logstash instance outside a kubernetes cluster. The logstash instance then queues this data and sends it to the appropriate elasticsearch index. This scenario works fine, but I decided to tweak it a bit.

Fluentbit is more efficient and lighter than logastash so I decided to replace it. Instead of logstash, I configured an fluentbit instance with HTTP_INPUT filter, which queues data and then sends it to elasticsearch ( configuration below ).

My architecture:
![screenshot](https://github.com/fluent/fluent-bit/assets/26190125/e6291680-1641-4964-a336-a49251a29b2f)

This solution also works. It uses much less resources than logstash, but some requests are rejected with an HTTP 400 error message:

Sample error:
```
[2023/08/23 07:19:01] [error] [output:http:http.0] 10.xxx.xxx.xxx:30001, HTTP status=400
error: invalid request

[2023/08/23 07:19:01] [ warn] [engine] failed to flush chunk '1-1692775140.769892701.flb', retry in 11 seconds: task_id=2, input=tail.0 > output=http.0 (out_id=0)
```

I've tried to debug this case with tcpdump. I've catched the network traffic between daemonset with HTTP_OUTPUT plugin and standalone fluentbit instance with HTTP_INPUT plugin and requests with status ok ( 200 ) are different from those with 400 only with content-length ( json data ). Moreover - I've copied such a json to the curl request, sent it to the server and it was accepted correctly ( error code 200). 

I decided to send a ticket because I don't know what is the cause of request with error code 400. The problem is that the payload json contains a very large number of lines with logs. If the request is rejected with a 400 error, the logs are lost

It looks that the part of requests generated in HTTP_OUTPUT filter are not compatible with HTTP_INPUT filter, but all requests generated by the HTTP_OUTPUT plugin are correctly accepted by logstash. I suspect that some parsers in the HTTP_INPUT plugin will be the problem here.

Can you help debug this issue and repair this behaviour of fluentbit HTTP_INPUT plugin?

My configmap ( for elasticsearch and fluentbit destination is the same )
```
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations       Off
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/testingsampleapp*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        multiline.parser  cri
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            http
        Match           *
        Host            ${EXTERNAL_ELASTICSERACH_OR_FLUENTD_HOST}
        Port            ${EXTERNAL_ELASTICSERACH_OR_FLUENTD_HOST}
        Format          json
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

```

Configuration of fluentbit outside kubernetes cluster ( forwarder to elasticsearch )
```
[SERVICE]
    storage.path /var/lib/fluentbit/
    storage.backlog.mem_limit 500M
    storage.max_chunks_up 1024

 

[INPUT]
    name http
    listen 0.0.0.0
    port 10001
    storage.type filesystem
    buffer_max_size 300M

 


[OUTPUT]
    Name  es
    Match *
    Host xxx.xxx.xxx.xxx
    Port  xxxx
    tls On
    tls.verify Off
    tls.ca_file /etc/logstash/cert/ca.crt
    Index testing_index
    http_user myuser
    http_passwd mypassword!!
    Buffer_Size 1M
    Trace_Error On
```

**Expected behavior**
Request without 400 error.

**Environment**
* Version used: fluent-bit:2.1.7
* Environment name: Kubernetes

**Comment by agup006** [comment]
@nmr would you be able to use out_forward and in_forward, you will gain even more performance by not having to convert out of MessagePack
