### ISSUE TITLE
Support usage of Client certificate and Private key in Kubernetes Filter

### ISSUE THREAD

**Issue by nareshku** [fluent/fluent-bit#7871]
**Is your feature request related to a problem? Please describe.**

Currently, our setup involves utilizing Fluent Bit as a systemd unit located outside of the Kubernetes cluster environment. Consequently, the conventional approach of accessing the APIServer or Kubelet by providing the `Kube_Token_File` and `Kube_CA_File` in the [Kubernetes Filter](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes) is unfeasible. This limitation arises because the `Kube_Token_File` and `Kube_CA_File` (which corresponds to the ServiceAccount Token and CA cert respectively) is automatically managed and updated by the Kubernetes control plane exclusively for the Fluent Bit running inside of a Pod. This arrangement is incompatible with our setup of running Fluent Bit as an independent process external to the cluster.

**Describe the solution you'd like**

In order to enable Fluent Bit's secure interaction with APIServer and Kubelet when operating outside of cluster, we propose to incorporate support for Client Certificate and Private Key authentication, similar to the functionality demonstrated by the following curl commands:

Kubelet Access:
```
curl --cert ./identity.cert --key ./identity.key https://localhost:20250/pods -k
```
API Server Access:
```
curl --cert ./identity.cert --key ./identity.key $APISERVER/api/v1/namespaces/default/pods -k
```
Expected Kubernetes Filter options
```
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Client_Cert         /var/run/secrets/identity.cert
        Private_Key         /var/run/secrets/identity.key
        Use_Kubelet         true
        Kubelet_Port        10250
```

**Describe alternatives you've considered**
An alternative approach that we've evaluated involves developing an independent process responsible for generating the Service Account Token and CA certificate at regular intervals. While this solution could address the challenge of providing the necessary authentication credentials to Fluent Bit running externally, it introduces a new layer of complexity and potential points of failure.

**Comment by suriyanath** [comment]
why this has been closed without a solution?.. it would still be a need, for us CI environment use single node minikube cluster where by default it configures key and certificates and we need to monitor pod logs and for that this feature keys would be helpful.
