### ISSUE TITLE
Question: In case of network interruption, are chunks stored in the same order as they were sent ?

### ISSUE THREAD

**Issue by JSchy65** [fluent/fluent-bit#7878]
If the network connection between a Fluent Bit client and a Fluen Bit server is interrupted and reestablishes several times during the transfer of a huge amount of chunks, is there a guarantee, that this chunks will be stored on the server side in the same order they were originally sent from the client. See also: https://github.com/fluent/fluentd/discussions/4280

**Comment by confiq** [comment]
what do you mean by client/server? fluentbit is processor, no?

**Comment by JSchy65** [comment]
The idea is to have a Fluent Bit instance on a vehicle. Docker containers on the vehicle push their logs to that Fluent Bit instance. The Fluent Bit instance transfers the logs via network to a Fluent Bit instance in a data center. The logs should be stored in a S3 bucket.

As you can imagine, the network connection from a driving vehicle into a data center is not always that stable.

A very first experiment showed to us, that if we interrupt the network connection an reestablish it again multiple times, that the log entries arrived not in the original order. The single chunks are mixed in the S3 output. Therefore, that solution seems to be not suitable for transfering logdata because for logdata, it's essential to be in the correct order.

Is our undestanding right, that Fluent Bit transports the chunks in an arbitray order (using the Forward Output Plugin) if network connection is interrupted and reestablished again ?

In that case, we can't use S3 as destination but anything else that stores the data in a database and therefore ist not sensitive for out of  sequence log records. Is that a reasonable conclusion?

**Comment by patrick-stephens** [comment]
There is no guarantee on order of transmission.
Timestamps are provided for all records though and this is part of the Forward protocol as well.
Loki used to have a requirement of in-order transmission but this was dropped a while ago - it orders via the timestamp.

**Comment by JSchy65** [comment]
That matches with our observations - Thank you very much.
