### ISSUE TITLE
Prometheus metrics for paused due to mem buf over limit 

### ISSUE THREAD

**Issue by yeya24** [fluent/fluent-bit#7882]
## Is your feature request related to a problem? Please describe.

We had several incidents caused by fluentbit ingestion paused due to membuf over limit. Somewhat it never resumed again, which is kind of weird.
We need a way to quickly identify the pausing problem and alarm on it asap. But now fluentbit doesn't have any available Prometheus metrics for it.

I think I can write some queries to use existing metrics like `input_records_total` but having a metric dedicated for pausing can be handy.

## Describe the solution you'd like

Add a new metric for input paused due to mem buf limit and expose to Prometheus metrics endpoint

**Comment by yeya24** [comment]
I see we do have metrics via one API endpoint https://docs.fluentbit.io/manual/administration/monitoring#metric-descriptions.
But it would really useful if we can expose the same metrics in Prometheus endpoint

**Comment by patrick-stephens** [comment]
The metrics are also available in Prometheus format via the webserver endpoints: 
- /api/v1/metrics/prometheus
- /api/v2/metrics/prometheus

> I see we do have metrics via one API endpoint https://docs.fluentbit.io/manual/administration/monitoring#metric-descriptions. But it would really useful if we can expose the same metrics in Prometheus endpoint

Are you not seeing those metrics when you use the Fluent Bit Metrics input plugin and connect it to an output plugin?
- https://docs.fluentbit.io/manual/pipeline/inputs/fluentbit-metrics
- https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-exporter
- https://docs.fluentbit.io/manual/pipeline/outputs/prometheus-remote-write

**Comment by yeya24** [comment]
Hi @patrick-stephens, thanks for the reply.
There is no API `/api/v2/metrics/prometheus` mentioned in the doc itself IIUC.

We enabled webserver and am using the `/api/v1/metrics/prometheus` API. I don't think the overlimit metric is in https://docs.fluentbit.io/manual/administration/monitoring#metric-descriptions. Can you double check the doc?

**Comment by yeya24** [comment]
I think the metric I want `input_chunks.{plugin name}.status.overlimit` is only available in `api/v1/storage` endpoint. It doesn't exist in Prometheus metrics endpoint.

If we have a way to send this metric to the prometheus endpoint it would be great. Is it doable using the output plugin you mentioned?

**Comment by 0xF0D0** [comment]
👍 we need this too

**Comment by yeya24** [comment]
Sorry @patrick-stephens, I just realized that there is a v2 endpoint for Prometheus metrics, while I am still using the old v1 endpoint for it as https://github.com/aws/aws-for-fluent-bit doesn't expose it, thus I don't see the metric.

I think my requirement has been resolved. I just need to wait for the aws distro to catch up. Thanks
