### ISSUE TITLE
Multiple tag matching broken

### ISSUE THREAD

**Issue by JoakimHagen** [fluent/fluent-bit#7889]
## Bug Report

**Describe the bug**
According to the [documentation](https://docs.fluentd.org/configuration/config-file#how-do-the-match-patterns-work), matching multiple tags in the configuration is done with space delimiters or curly-braced set {X,Y,Z}. My experience with v2.1.8 is that neither of these work.

**To Reproduce**
Consider the following config
```
[SERVICE]
    Flush        1
    Daemon       Off
    HTTP_Server  Off
    Log_Level    info

[INPUT]
    Name             tail
    path             anything_with_content.log
    read_from_head   true
    tag              one

[INPUT]
    Name             tail
    path             anything_with_content.log
    read_from_head   true
    tag              two

[OUTPUT]
    name         stdout
    match        one two
```
- Steps to reproduce the problem:
* Save the configuration above as `fluent-bit.config`
* Create a log file with any content named `anything_with_content.log`
* Run `fluent-bit --config=fluent-bit.config`
* Watch no log output from the log-file get printed

**Expected behavior**
If we replace the single output with multiple ones, using only a single tag match each, we get the output we expect.
There shouldn't be any difference between these two methods.
```
[OUTPUT]
    name         stdout
    match        one
[OUTPUT]
    name         stdout
    match        two
```

**Your Environment**
* Version used: v2.1.8
* Configuration: As displayed above. (match {one,two} was also attempted)
* Server type and version: KVM virtual-machine hosted on RedHat 8
* Operating System and version: CentOS Stream 8
* Filters and plugins: None

**Comment by lecaros** [comment]
Hello @JoakimHagen 
The documentation you're referring to is for Fluentd, not Fluent Bit. That's a pattern currently not supported in Fluent Bit.
https://docs.fluentbit.io/manual/concepts/data-pipeline/router

**Comment by JoakimHagen** [comment]
I understand. My bad. It'd be a welcome addition in that case. Thank you for the quick response.
