### ISSUE TITLE
fluent-bit startup log reports error "kubelet upstream connection error"

### ISSUE THREAD

**Issue by opencmit2** [fluent/fluent-bit#7898]
fluent-bit starts up with the following error message：

![096213079d0477a34ac12856b0c67bf](https://github.com/fluent/fluent-bit/assets/112474703/419f3c03-2893-401f-b414-bb57d54f27c4)

Here is the configuration information for fluent-bit：

![93311c51876a0651e7057b5c86ef880](https://github.com/fluent/fluent-bit/assets/112474703/2aecc7d2-d542-433d-a2e8-770414d36835)

fluent-bit version： 1.9.3
kubernetes version： 1.23.6

**Comment by docmerlin** [comment]
May be related to:
https://github.com/fluent/fluent-bit/issues/5820
