### ISSUE TITLE
Internal and external wire protocol differs

### ISSUE THREAD

**Issue by BernhardSchmid** [fluent/fluent-bit#7923]
## Bug Report

**Describe the bug**
Hi,

according to the change documented here https://docs.fluentbit.io/manual/concepts/key-concepts#event-format the fluent bit event format changes with version 2.1.0. In the documentation it is named `wire protocol`.

Data captured from the (build-in) `forward` output plug-in follows the specification described here https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1 where the protocol follows the old format.

**Expected behavior**
Similar encodings with msgpack internally and in forward protocol.

**To Reproduce**

- Steps to reproduce the problem:
    - Capture data from go plugin's invocation of `Flash()` 
    - Capture data from forward output plugin

**Screenshots**

#### Go plugin
Capturing the data from a go plugin's **Flush()** call shows the new format as described for version 2.1.0 and above.
![image](https://github.com/fluent/fluent-bit/assets/39767912/fe349cfb-e1ec-4f7e-b525-2096c98cc4b7)

We analysed the new timestamp message as follows
blue: array32 describing two entries,
red: valid timestamp as we expected
green: empty map --> no meta data

#### build-in forward output plugin

Data captured from the forward output plugin follows the old format.
```
00000000: 92ac 6475 6d6d 7931 2e6c 6f63 616c 94dd  ..dummy1.local..
00000010: 0000 0002 d700 64e5 d91b 0a0f d34c 81a7  ......d......L..
00000020: 6d65 7373 6167 65a5 6475 6d6d 79dd 0000  message.dummy...
00000030: 0002 d700 64e5 d91c 0a12 4b52 81a7 6d65  ....d.....KR..me
00000040: 7373 6167 65a5 6475 6d6d 79dd 0000 0002  ssage.dummy.....
00000050: d700 64e5 d91d 0a05 ac16 81a7 6d65 7373  ..d.........mess
00000060: 6167 65a5 6475 6d6d 79dd 0000 0002 d700  age.dummy.......
00000070: 64e5 d91e 0a0c bbe1 81a7 6d65 7373 6167  d.........messag
00000080: 65a5 6475 6d6d 7992 ac64 756d 6d79 312e  e.dummy..dummy1.
00000090: 6c6f 6361 6c95 dd00 0000 02d7 0064 e5d9  local........d..
000000a0: 240a 4c44 9381 a76d 6573 7361 6765 a564  $.LD...message.d
000000b0: 756d 6d79 dd00 0000 02d7 0064 e5d9 250a  ummy.......d..%.
000000c0: 1292 5d81 a76d 6573 7361 6765 a564 756d  ..]..message.dum
000000d0: 6d79 dd00 0000 02d7 0064 e5d9 260a 0f0f  my.......d..&...
000000e0: 2581 a76d 6573 7361 6765 a564 756d 6d79  %..message.dummy
000000f0: dd00 0000 02d7 0064 e5d9 270a 0fe5 3381  .......d..'...3.
00000100: a76d 6573 7361 6765 a564 756d 6d79 dd00  .message.dummy..
00000110: 0000 02d7 0064 e5d9 280a 19a4 7d81 a76d  .....d..(...}..m
00000120: 6573 7361 6765 a564 756d 6d79 0a         essage.dummy.
```

**Your Environment**

* Version used: fluentbit v2.1.6/v2.1.7/v2.1.8
* Configuration: default as predefined in cmake/make
* Environment name and version (e.g. Kubernetes? What version?): local
* Operating System and version: (both setups provides the same result)
    * mac osx
    * containerized running on latest podman
* Filters and plugins: defaults shipped with fluentbit, own go plugin to capture binary data from call Flush()

**Comment by BernhardSchmid** [comment]
Hi - can this be evaluated by someone with domain skills in the area so that the discussion might at least start?
Thanks in advance.

**Comment by ScarletTanager** [comment]
@agup006 Can you see if someone can look at this?

**Comment by agup006** [comment]
@cosmo0920 would you be able to take a look at this?

**Comment by agup006** [comment]
@cosmo0920 i recall seeing a fluent 1.5 forward protocol, let’s definitely tag the folks from the issue there, and perhaps add some of them in the issue here for more discussion

**Comment by cosmo0920** [comment]
Thanks for tagging to me. Yeah, I'm currently working for revising the Forward protocol from v1 to v1.5.
This is not public for now but it'll be revealed until or during the KubeCon NA.

**Comment by cosmo0920** [comment]
Here is the latest revision of the Forward Protocol v1.5 discussion: https://gist.github.com/cosmo0920/1892e1672d52c3c1a74c2ee3559d6691

**Comment by BernhardSchmid** [comment]
@cosmo0920 Thank you for the insights about the new/planned protocol spec and the link to the revision. I'm currently on travel but will review this as soon as possible.

@agup006 Thanks for connecting this!
Regards

**Comment by cosmo0920** [comment]
Now, we published the new specification of Forward protocol:
* https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1.5
* https://github.com/fluent/fluentd/wiki/msgpack-schema-for-msgpack-payloads-of-cmetrics-and-ctraces

**Comment by cosmo0920** [comment]
Hopefully, there are answering your questions.

**Comment by BernhardSchmid** [comment]
@cosmo0920 Thank you for the links.

For now just one quick question. I read that fluent-bit version 2.2 provides support for the v1.5 spec. Does this mean that the **forward _output_ plugin** - starting with fluent-bit version 2.2 - is encoding the data stream according to the format v1.5 OR does this mean that the **forward _input_ plugin** - starting with fluent-bit version 2.2 - accepts now also version v1.5 beside the older ones?

Thanks in advance!

**Comment by cosmo0920** [comment]
> For now just one quick question. I read that fluent-bit version 2.2 provides support for the v1.5 spec. Does this mean that the **forward _output_ plugin** - starting with fluent-bit version 2.2 - is encoding the data stream according to the format v1.5 OR does this mean that the **forward _input_ plugin** - starting with fluent-bit version 2.2 - accepts now also version v1.5 beside the older ones?

It means that forward output plugin of fluent-bit supports 1.5 spec and 1.5 spec just adding "optional things" into v1 spec. So, for the former one, I'd say yes. 

Then, the latter question is also yes. v1.5 spec is just adding additional things which are metadata handlings and msgpack payloads which is generated from cmetrics and ctraces contexts. Their handlings are not defined in v1 spec and v1.5 spec declares how to compound these msgpack payloads into forward protocol.

v1.5 supported clients and servers still support/handle the older protocol -- which is forward protocol v1.
