### ISSUE TITLE
Match not work with loki output

### ISSUE THREAD

**Issue by rfmoz** [fluent/fluent-bit#7924]
## Bug Report

**Describe the bug**
When Match is configured on Loki output, it doesn't work unless it uses a wildcard.

**To Reproduce**
For example, this seems to send info to Loki, but it doesn't, only to stdout:
```
[INPUT]
    name http
    listen 0.0.0.0
    port 5170
    tag testag

[OUTPUT]
    Name   stdout
    match *

[OUTPUT]
    name   loki
    Match  testag
    labels job=fluentbit

```
Also this fails too:
```
[INPUT]
    name http
    listen 0.0.0.0
    port 5170
    tag testag

[OUTPUT]
    Name   stdout
    match nothing

[OUTPUT]
    name   loki
    Match  testag
    labels job=fluentbit

```
But this works:
```
[INPUT]
    name http
    listen 0.0.0.0
    port 5170
    tag testag

[OUTPUT]
    Name   stdout
    match nothing

[OUTPUT]
    name   loki
    Match  *
    labels job=fluentbit

```

**Expected behavior**
I expect to use "tag testag" in Input and see the information on Output if "Match testag" is used.

**Your Environment**
fluent-bit  2.1.9 and loki 2.8.4  in baremetal Debian 12

Thanks,

**Comment by patrick-stephens** [comment]
This should work fine, are you sure you have input?
I would use dummy input rather than http to always generate matching tag plus it is reproducible then - this report doesn't have any actual data coming in for example.

**Comment by rfmoz** [comment]
Sure, I have input. With dummy works, but it doesn't with http. For example this was the test:

This works:
```
[INPUT]
    Name   dummy
    Dummy {"message": "custom dummy"}
    Tag testag

[OUTPUT]
    name   loki
    Match  testag
    labels job=fluentbit
```
Producing the following lines:
```
2023-09-15T19:39:16+02:00 {job="fluentbit"} {"message":"custom dummy"}
2023-09-15T19:39:17+02:00 {job="fluentbit"} {"message":"custom dummy"}
```

But this doesn't work:
```
[INPUT]
    Name http
    Listen 0.0.0.0
    Port 5170
    Tag testag

[OUTPUT]
    name   loki
    Match  testag
    labels job=fluentbit
```

None combination works     `Match  testag*`      `Match  *testag`         `Match  *testag*`, only works with wildcard  `Match  *`

**Comment by patrick-stephens** [comment]
So only HTTP input does not match? That feels unlikely to be anything on the Loki side then... 
Dummy input works fine but not http input?
Do you have a simple reproducer for it, e.g. a compose stack that generates the http input?

I think the code is generic anyway for matching.

**Comment by rfmoz** [comment]
That's right, the combination between http input tag and output match fails.

The environment is very simple. Install fluent-bit 2.1.9 on a latest Debian and add this config:

```
[INPUT]
    Name http
    Listen 0.0.0.0
    Port 5170
    Tag testag

[OUTPUT]
    name  stdout
    match testag
```
Open `journal -f` in on terminal and execute a test request in other:

`curl -X POST http://localhost:5170/reports -H 'Content-Type: application/json' -d '{"parameter1":"my_login","data":"my_data"}'
`
You won't see it.

But change the configuration to:
```
[INPUT]
    Name http
    Listen 0.0.0.0
    Port 5170
    Tag testag

[OUTPUT]
    name  stdout
    match *
```
And reapeat the request, you will see something like:
`Sep 15 22:37:17 debian12 fluent-bit[7913]: [0] reports: [[1694810236.887533185, {}], {"parameter1"=>"my_login", "data"=>"my_data"}]`

**Comment by nokute78** [comment]
Tag of in_http is created from the end of the request URL.
https://docs.fluentbit.io/manual/pipeline/inputs/http#how-to-set-tag

`curl -X POST http://localhost:5170/reports -H 'Content-Type: application/json' -d '{"parameter1":"my_login","data":"my_data"}'`
In this case, a tag will be `reports`.

**Comment by rfmoz** [comment]
Thanks, there is the misunderstanding.

I also update the documentation, here is the PR:

https://github.com/fluent/fluent-bit-docs/pull/1195

**Comment by patrick-stephens** [comment]
Ah I was not aware of that either so super useful update!
