### ISSUE TITLE
in_tail optimize purge outdated files when ignore_older option is enabled

### ISSUE THREAD

**Issue by geniusjoe** [fluent/fluent-bit#7936]
**Your Environment:**
Version used: v2.1.9
Environment name and version (e.g. Kubernetes? What version?): 	
OS Version: tlinux3.1x86_64
Kubernetes Version: 1.20.6

**Is your feature request related to a problem? Please describe.**

When I'm using an `in_tail` plugin with [Ignore_Older](https://docs.fluentbit.io/manual/pipeline/inputs/tail) option enabled, I notice that outdated monitored files(whose latest modified time are earlier than ignore_older time) cannot be deleted and will remain in the `static_list` and `event_list` forever.
It will increase the number of system open fd(file descriptor) and increase the number of inotify watched files. This may lead to high cpu usage.

**Describe the solution you'd like**

Refer to [1.8 version](https://github.com/fluent/fluent-bit/blob/dc7cbaac13d3abbbaee1c21c87734146bf7c8404/plugins/in_tail/tail_file.c#L1684), we can add an outdated file check in `check_purge_deleted_file` function. But we need to add a validation to see if this file has been parsed competely(check if `file->offset >= st.st_size` ). When this file has been parsed completely and outdated, we remove this file from monitored list. Example below:
```
    if (ctx->ignore_older > 0) {
        mtime = flb_tail_stat_mtime(&st);
        if (mtime > 0) {
            if ((ts - ctx->ignore_older) > mtime && file->offset >= st.st_size) {
                flb_plg_debug(ctx->ins, "purge: monitored file (ignore older): %s",
                              file->name);
                flb_tail_file_remove(file);
                return FLB_TRUE;
            }
        }
    }
```

**Describe alternatives you've considered**

**Additional context**

Are there any questions or advice? Please feel free to let me know and I can also make a PR.

**Comment by mooseh** [comment]
We have also experienced very strange behaviour with ignore_older since version 2.1.8, we have had to revert back to 2.1.6 in order to get around this issue, this really needs looking into as this caused a major headache to our infrastructure team.
