### ISSUE TITLE
Timestamp Inconsistencies in High-Volume Logs

### ISSUE THREAD

**Issue by LevitatingKraken** [fluent/fluent-bit#7937]
## Bug Report

**Describe the bug**
Some of our logs processed by Fluent Bit have an incorrect date. Specifically, the year, month, and day seem to be affected. 
Logs with the time "Sep 18, 2023" Are parsed as "May 18, 2024" in the `@timestamp` field and is indexed under `.ds-fluent-2024.05.18-2023.09.18-000001`.

Expected:
![image](https://github.com/fluent/fluent-bit/assets/88397999/c51404f5-3598-4fc8-a221-7ca3fa3eb609)
 
Actual:
![image](https://github.com/fluent/fluent-bit/assets/88397999/1c04dbc0-9271-4ec4-a882-2fba5a83272d)

**To Reproduce**
- Example log message:
```
{"log":"some text","stream":"stdout","time":"2023-09-18T22:10:51.758Z"}
```
- Steps to reproduce the problem:
  1. Configure Fluent Bit with the provided configuration.
  2. Process logs at a high volume (10 Billion logs per day in our case).
  3. Observe logs with incorrect dates.

**Expected behavior**
Logs should maintain their original and correct timestamps without discrepancies in the date(year/month/day)

**Your Environment**
* Version used: Fluent Bit 0.38.0
* Configuration:
  ```
  config:
    customParsers: |
      [PARSER]
          Name                pap_code_json
          Format              json
          Time_Key            time
          Time_Format         %Y-%m-%dT%H:%M:%S.%L
    inputs: |
      [INPUT]
          Name                tail
          Tag                    .*
          Path                /var/log/containers/*_default_*.log, /var/log/containers/*_dev-*.log
          multiline.parser    docker, cri
      [INPUT]
          Name                kubernetes_events
          Tag                 k8s_events
          kube_url            https://kubernetes.default.svc
          kube_namespace      default
   filters: |
    [FILTER]
        Name parser
        Match   .*
        Key_Name log
        Parser pap_code_json
    [FILTER]
        Name kubernetes
        Match   .*
        Merge_Log On
        Merge_Log_Key log_processed
        Kube_Tag_Prefix xyz.var.log.containers.
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off
    [FILTER]
        Name lua
        Match   .*
        script /fluent-bit/scripts/kubernetes_filter.lua
        call kubernetes_filter
    [FILTER]
        Name lua
        Match   .*
        script /fluent-bit/scripts/dd_filter.lua
        call dd_filter
  ```
* Environment name and version: Kubernetes, EKS 1.27

**Additional context**
This timestamp discrepancy makes our log management and analysis extremely challenging, as we rely on accurate timestamps for various operations and insights. We have a high volume of logs daily, and even a small percentage of logs with wrong timestamps can equate to a large number of affected logs.

**Comment by LevitatingKraken** [comment]
an update:
I noticed it happens only when I add this:
`
     [INPUT]
         Name             kubernetes_events
         Tag                 k8s_events
         kube_url            https://kubernetes.default.svc
         kube_namespace      default
`

**Comment by pitch-d** [comment]
I've notice the same kind of behavior, both timestamp set to future and back in time.
It's a bit annoying in my case when using opensearch output and indices already deleted will get recreated
