### ISSUE TITLE
Tag/match not working for OpenTelemetry input

### ISSUE THREAD

**Issue by carlosli888** [fluent/fluent-bit#7939]
## Bug Report

**Describe the bug**
If I want to output logs received via OpenTelemetry plugin, I am forced to use `*` as the `Match` string.  If I use anything else, logs are not sent to the output plugins.

**To Reproduce**
- Steps to reproduce the problem:
1.  Start an instance of FluentBit as a server.
```
[INPUT]
    Name                opentelemetry
    Listen              0.0.0.0
    Port                4319
    Tag                 otel
[OUTPUT]
    Name                stdout
    Match               otel
```
2. Use another instance of FluentBit to act as a log generator.
```
[INPUT]
    Name                dummy 
[OUTPUT]
    Name                opentelemetry
    Match               *
    Host                127.0.0.1
    Port                4319
```
3. If we examine the output from the FluentBit acting as a server, nothing is shown.  However, if we change the `Match` string of the *Stdout* plugin to `*`, then it works.  

**Expected behavior**
I expect routing to work the same way for all plugins except *Forward* as described by [https://docs.fluentbit.io/manual/concepts/key-concepts#tag].  Alternatively, if the `Match` string needs to match the original source, this is clearly documented and it works.  Currently, adding the `otel` tag to the *Dummy* input makes no difference.

**Screenshots**
![image](https://github.com/fluent/fluent-bit/assets/47931389/570f5fd0-deb2-4e55-a236-63ac5a7e8971)

**Your Environment**

* Version used: 2.1.8
* Configuration: See reproduction steps above
* Environment name and version (e.g. Kubernetes? What version?): See OS below
* Server type and version:
* Operating System and version: Windows 10
* Filters and plugins: See reproduction steps above

**Additional context**
This was first discovered while troubleshooting why logs were not being sent to Loki.

**Comment by nokute78** [comment]
Tag seems to be composed by uri.
e.g. v1_metrics from `/v1/metrics`

I sent a patch to create a tag from property `tag`.
https://github.com/fluent/fluent-bit/pull/8134
