### ISSUE TITLE
in_udp doesn't recognize end of packet as a separator

### ISSUE THREAD

**Issue by adamagnew** [fluent/fluent-bit#7944]
## Bug Report

**Describe the bug**
When using in_udp we receive UDP packets that consist of the entire log line. Unfortunately, the packet doesn't end in a \n or \0 , instead it just ends. Consequently, fluent-bit never recognizes a separator and doesn't process the input.
This worked with the in_syslog input with mode udp, but we'd much prefer to move to in_udp to skip the computational cost of parsers that are mandatory under in_syslog.

**To Reproduce**
Use in_udp, point a log source at it that doesn't terminate the strings. In our case, it's an F5 appliance.

```
# tcpdump -nnSX udp port 539
17:55:17.207943 IP 10.95.2.14.29128 > 192.168.6.165.529: UDP, length 1065
        0x0000:  4500 0445 0c10 4000 f411 a2dd 0a5f 020e  E..E..@......_..
        0x0010:  c0a8 06a5 71c8 0211 0431 607a 6163 6c5f  ....q....1`zacl_
        0x0020:  706f 6c69 6379 5f6e 616d 653d 2222 2c61  policy_name="",a
        0x0030:  636c 5f70 6f6c 6963 795f 7479 7065 3d22  cl_policy_type="
        0x0040:  2d22 2c61 636c 5f72 756c 655f 6e61 6d65  -",acl_rule_name
        0x0050:  3d22 222c 6163 6c5f 7275 6c65 5f75 7569  ="",acl_rule_uui
....
        0x0410:  6567 6f72 6965 733d 224e 6f2d 6c6f 6f6b  egories="No-look
        0x0420:  7570 222c 6465 7374 5f69 7069 6e74 5f63  up",dest_ipint_c
        0x0430:  6174 6567 6f72 6965 733d 224e 6f2d 6c6f  ategories="No-lo
        0x0440:  6f6b 7570 22                             okup"
```
**Expected behavior**
We'd like it to recognize the end of the packet as a separator

* Version used: current HEAD
* Configuration: in_udp to capture UDP logs
* Environment name and version (e.g. Kubernetes? What version?):  Openshift 4.12, image compiled from latest source

**Additional context**
We use fluentbit as a generic log aggregator for a variety of sources. The in_syslog plugin requires that you define a parser. While we use the simplest parser we can, it still adds about 30% to our CPU consumption. We'd LOVE to use the new in_udp plugin instead as many of our logs don't conform to syslog RFCs to begin with.

**Comment by lecaros** [comment]
What's your config?
Do you have a separator character?
