### ISSUE TITLE
Better documentation for grep, particular around use of regexes

### ISSUE THREAD

**Issue by charlesritchea** [fluent/fluent-bit#7945]
It's frustrating that the only example in the grep documentation is `log aa` which isn't even a regex. I'm trying to find out how to input my regex, but I'm getting conflicting messages online, like do I need to surround with `\\` or not?

**Comment by patrick-stephens** [comment]
Yeah an improved example would be good if you can submit a PR: https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/filters/grep.md

Regexes are always hard, particularly when combined with string escaping in various languages.

I would say the best way to test is by running with dummy input to generate representative data then using your grep filter with stdout to test it all locally. This is then using actual Fluent Bit directly.
Dummy+stdout is a good way to iterate fast and easily so I tried to document it here: https://calyptia.com/blog/fluent-bit-tips-tricks

**Comment by charlesritchea** [comment]
I can't submit a doc PR if I don't know how it works
