### ISSUE TITLE
OUTPUT Exclude some tag

### ISSUE THREAD

**Issue by peng3693** [fluent/fluent-bit#7958]
## Bug Report

**Describe the bug**
We have many tags with uncertain prefixes, and here is the current last Filter.
`
[FILTER]
        Name   rewrite_tag
        Match  kube.*
        Rule   $log ^(.*)$ $TAG[4]-$record_date.log false
        Emitter_Mem_Buf_Limit 50MB
`

I will add a rewrite_tag before this Filter, regular expression matching will be given to the new tag aaa.log. 
There are currently 2 OUTPUTs, where one OUTPUT outputs all logs except for the aaa.log tag and one OUTPUT outputs the log of the aaa.log tag. How can I exclude the aaa.log tag from the first OUTPUT now?

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
> There are currently 2 OUTPUTs, where one OUTPUT outputs all logs except for the aaa.log tag and one OUTPUT outputs the log of the aaa.log tag. How can I exclude the aaa.log tag from the first OUTPUT now?

Please clarify: first it says the output is excluded then it says it needs to be excluded.

Ultimately this needs to be handled by tagging and matching - remember you can also do `match_regex` too.

I don't think this is a bug.
