### ISSUE TITLE
Another race condition in fluent-bit on Windows

### ISSUE THREAD

**Issue by obs-gh-arvindsrinivasan** [fluent/fluent-bit#7963]
## Bug Report

**Describe the bug**
Fluent-bit crashes randomly at different places in mk_list_add, or mk_list_del depending on when the race occurs.

**To Reproduce**
Difficult to reproduce as it happens every 2-3 days. However I was able to grab a stack trace in vscode.

**Screenshots**
![image__44_](https://github.com/fluent/fluent-bit/assets/134466083/691c5e20-1703-41f4-a0d5-b39ef378554d)

**Your Environment**

* Version used: 2.0.9
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Windows Server 2016
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
[SERVICE]
    flush        5
    daemon       Off
    net.dns.resolver LEGACY
    log_level    trace  
    log_file    C:\Users\Administrator\Documents\fluent\fluent.log
[INPUT]
    Name         winlog
    Channels     Security,Application,System
    Interval_Sec 5
    DB           C:\Users\Administrator\Documents\fluent\fluent.pos
# Uncomment the below section if using AWS EC2
[FILTER]
    Name aws
    Match *
    imds_version v1
    az true
    ec2_instance_id true
    ec2_instance_type true
    account_id true
    hostname true
    vpc_id true
[FILTER]
    Name record_modifier
    Match *
# if you want to group your servers into an application group
# [e.g. Proxy nodes] so you have have custom alert levels for them
# uncomment this next line
#    Record appgroup ha-proxy
    Record host ${HOSTNAME}
    Record datacenter AWS
    Record obs_ver 20230727
    Remove_key _MACHINE_ID

[INPUT]
    name tail
    tag  tail_osquery_results
    Path_Key path
    path C:\Program Files\osquery\log\osqueryd.results.log
    Read_from_Head False
    db      osquery-results.db
[INPUT]
    name tail
    tag  tail_osquery_snapshots
    Path_Key path
    path C:\Program Files\osquery\log\osqueryd.snapshots.log
    Read_from_Head False
    Buffer_Max_Size 5MB
    Buffer_Chunk_Size 512k
    Skip_Long_Lines On
    db      osquery-snapshots.db

[OUTPUT]
    name        http
    match       *
    host        xxxxxxx.com
    port        443
    URI         /v1/http/fluentbit/tail
    Format      msgpack
    Header      Authorization Bearer xyxddfdf
    Compress    gzip
    tls         on
    net.dns.mode TCP
    net.keepalive_idle_timeout 15
    net.keepalive_max_recycle 50

**Comment by obs-gh-arvindsrinivasan** [comment]
mk_list_add/del need mutexes to prevent this from happening.

**Comment by patrick-stephens** [comment]
Is it reproducible with 2.1.9?

**Comment by obs-gh-arvindsrinivasan** [comment]
Trying to reproduce it with a 2.1.9 build now. The race condition is still there as multiple coroutines are running and adding/deleting from mk_list. The freed memory gets reused asynchronously. There needs to be some locking mechanism in mk_list_del, specifically.

**Comment by obs-gh-arvindsrinivasan** [comment]
The race appears to be between mk_sched_conn_timeout_del and mk_sched_conn_timeout_add. It could also be a bad free (not necessarily a race), but given how random it is, and that it happens in a coroutine it strongly implicates a race condition.

**Comment by obs-gh-arvindsrinivasan** [comment]
PR coming shortly to address this.
