### ISSUE TITLE
Release updates: bitbake file don't update the version

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit#7988]
## Bug Report

When we process a new release e.g: v2.1.10, the CI system prepares the new versioning for the new release on this case v2.1.11. The bitbake files gets renamed but the version inside it keeps being the old one:

https://github.com/fluent/fluent-bit/blob/2.1/fluent-bit-2.1.11.bb#L19

**Comment by patrick-stephens** [comment]
The script does seem to target this but it looks like the sed is failing here: https://github.com/fluent/fluent-bit/blob/bf17059bf673326cbdd738b1e66f36ab51f48d3d/update_version.sh#L76
