### ISSUE TITLE
Why is there no HTTP polling input?

### ISSUE THREAD

**Issue by AdaptiveStep** [fluent/fluent-bit#7993]
**Is your feature request related to a problem? Please describe.**
I might have missed something, but it seems to me that Its impossible to poll simple HTTP REST endpoints with fluentbit right now. 
Logstash supports this and Vector too. It's frustrating if I need to create a separate container just to do something as simple as http polling. 

**Describe the solution you'd like**
I would like there to be a simple input that polls a rest api with a syntax like this:
```
[INPUT]
  name http_poll
  rate 60
  url: https://mydomain.comm/api/v1/stuff
  tls: On
  ...
```
and so on with the rest of the tls data.

**Describe alternatives you've considered**
It might be an alternative to create new layer in the fluentbit image that includes lua-http, and then from lua make some http requests.
Otherwise a completely different container is needed for this mere function alone, that exists in pretty much all other collectors. 

**Additional context**
It is currently impossible (for me) to fetch http data without using some other collector to do this. 
This is a basic feature that all log collectors would have use of and it should not be a big problem implementing this.

**Comment by patrick-stephens** [comment]
We do actually have an option for this in the Calyptia Core commercial offerings (based on Fluent Bit) although in that case it is built with a Golang plugin packaged into the images. A LUA alternative would also be doable (subject to system dependencies but I think it was possible with pure LUA alternatives when we looked).

I think the main issue was that every API is different - they all do things like auth, pagination, etc. differently so need to be customised in some fashion. It is possible to support but needs to be considered too.

The other option is to use `exec` with `curl` or similar but `exec` is not supported by distroless images (it requires `/bin/sh` which is not present) so again the OSS image by default would not support i - the debug image would.

It seems like a good feature request assuming the configuration around the API is properly handled - or just say it only ever supports a fairly simple endpoint without parameters.
