### ISSUE TITLE
[Question/Help] how to send nginx ingress access logs from fluent-bit container to an output

### ISSUE THREAD

**Issue by moinologics** [fluent/fluent-bit#7996]
i have one running kubernetes cluster which is running nginx-ingress-controller and fluent-bit conatainer (docker image fluent/fluent-bit:2.1-debug) side by side.
i want to send nginx-ingress-controller access logs (which is in stdout) to an output.

i have tried [this](https://github.com/fluent/fluent-bit/issues/1534#issuecomment-590132981) but getiing **read error, check permissions: /var/log/containers/*.log**

fluent-bit.conf
```
    [SERVICE]
        Parsers_File /fluent-bit/etc/parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*ingress-nginx-controller*/controller/*.log
        Parser            k3s-ingress-nginx
        DB                /var/log/flb_kube.db
        Refresh_Interval  10
    
    [OUTPUT]
        Name   stdout
        Match  *
    
    [OUTPUT]
        # some output config here
```

parsers.conf
```
    [PARSER]
        Name        k3s-ingress-nginx
        Format      regex
        Regex       ^(?<timestamp>[^ ]*) (?<log_stream>[^ ]*)(?: +\S*)? (?<raw_access_log>(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] \[(?<proxy_alternative_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<req_id>[^ ]*) (?<location_lat>[^ ]*) (?<location_long>[^ ]*) (?<location_country_code>[^ ]*) (?<location_city>[^ ]*).*)$
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
```

**Comment by patrick-stephens** [comment]
Have you checked the permissions then?

Please follow the issue template to provide a lot more detail - how have you deployed? What does your actual pod spec look like and does it include the `/var/log/containers/` mount path per your input? Did you use the helm chart - that is the only official supported deployment?

**Comment by moinologics** [comment]
ok, i have mounted the /var/log/containers dir in pod and it seems working, but logs are not parsed and getting error
`[ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.var.log.containers.ingress-nginx_ingress-nginx-controller-78c8fff89b-wgjr5_1e1449e7-7e62-4234-bcae-457dedfa87a8.controller.0.log`
i'm updating the config (in issue) and parser file with new data. can you tell me what may be the problem?

**Comment by moinologics** [comment]
ok i make it working but only one small problem now, some logs are not in correct format and when parser is not able to parse them it put them in a key **log**, but i want them to completely discard and not to send them to remote storage. (it may be good if they appear only on stdout)

PS: i am updating config to latest in issue description

**Comment by patrick-stephens** [comment]
Just drop any with the default `log` key using `grep` filter.

**Comment by moinologics** [comment]
Will it not send empty object?
can you give example of this grep filter?

**Comment by patrick-stephens** [comment]
It's in the docs: https://docs.fluentbit.io/manual/pipeline/filters/grep
Just set to exclude for any value of the `log` key, i.e. a regex that matches all values. I think that should drop it then. Dropped records are not allowed any further.
