### ISSUE TITLE
td-agent-bit: make --quiet explain what it does

### ISSUE THREAD

**Issue by grosser** [fluent/fluent-bit#8009]
**Is your feature request related to a problem? Please describe.**
at it spams too many info logs and I want only warn+error

**Describe the solution you'd like**
--help says what the option exactly does

**Describe alternatives you've considered**
nothing

**Comment by patrick-stephens** [comment]
`td-agent-bit` is no longer supported: https://docs.fluentbit.io/manual/installation/linux#migration-to-fluent-bit

Are you asking for a way to control the log level?

There is the `log_level` configuration option which should do that, it supports `debug, info, warn, error` levels.

By default it is info I believe but you should be able to change that in the config file for Fluent Bit:
```
[SERVICE]
  log_level warn
```

I don't think there is a way to control it purely via command line arguments - there is `--verbose` to increase it above `info` but no way to decrease or set it direct from the command line. Is that the request? A general `--log-level X` option might be good.

**Comment by grosser** [comment]
Thanks, I guess let me first do the migration and then come back if the issue is still there :)
