### ISSUE TITLE
Filter Modify doesn't work as expected on keys after applying parsing using CRI plugin

### ISSUE THREAD

**Issue by omar-khaled-mahmoud** [fluent/fluent-bit#8018]
## Bug Report

Description 

After parsing my container log messages using CRI plugin , I can't manipulate the records anymore like 
   [INPUT]
        Name tail
        Tag  kube.*
        Path /var/log/containers/*.log
        parser cri

  [FILTER] 
     Name Modify
     Rename *key"
     Hard_copy

**Comment by patrick-stephens** [comment]
Can you provide more details? What keys are failing? What does the actual output look like (e.g. add a `stdout` filter - not output - *before* the `modify` one to check).

**Comment by omar-khaled-mahmoud** [comment]
very helpful thanks
