### ISSUE TITLE
Tail does not see all pods. 

### ISSUE THREAD

**Issue by Csana111** [fluent/fluent-bit#8026]
## Bug Report

**Describe the bug**
I have a Kubernetes cluester, and I deploy FluentBit as a daemonset. I have several namespaces, and I want to collect logs from my development namespace. When I deploy FluentBit, it can see my deployed pods, but if I run standalone pods (without deployment and daemonset), it cannot see this change and does not collect logs from them. All parsers work well; I tested them with dummy input. I try to increase memory limits and buffers, but these do not help. I also tried using a different path (/var/log/pods/*/*/*.log). I do not see any problem with my pods either.

**To Reproduce**
Deploy pods with Kubernetes api. In my case these pods do not include in FluentBit.

**Your Environment**

    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port  2020
        Health_Check On

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            cytolog_parser
        Tag               kube.*
        Refresh_Interval  1
        Buffer_Max_Size   10MB
        Mem_Buf_Limit     128MB

   [FILTER]
          Name             kubernetes
          Match            kube.*
          Kube_URL         https://kubernetes.default.svc:443
          Kube_CA_File     /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix  kube.var.log.containers.
          Buffer_Size      8MB
          Merge_Log        On
          Merge_Log_Key    log
          K8S-Logging.Parser  On
          K8S-Logging.Exclude On

    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_Under  kubernetes

    [OUTPUT]
        Name  stdout
        Match *

    [PARSER]
        Name    cytolog_parser
        Format    regex
        Regex   ^.+Z (?<stream>.+) [A-Z] \[(?<level>[A-Z]+)\](\[(?<audience>.+)\])? (?<date>[^A-Za-z]+) (?<file>[^:]+):(?<line>\d+): (?<log>.*)$
        Time_Key    date
        Time_Format   %Y-%m-%d %H:%M:%S
        Time_Keep  on

    [PARSER]
        Name    default_parser
        Format    regex
        Regex   ^(?<date>[^Z]+Z)\s(?<stream>[^\s]+)\s(?<code>[A-Z])\s(?<log>.*)$
        Time_Key    date
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep  on

    [PARSER]
        Name    json_parser
        Format    json

**Comment by patrick-stephens** [comment]
I suspect the difference is that you're not running as a daemonset.
Pod logs are stored on the host they're running on, each host does not have logs for pods on other nodes so you must run on all nodes to get all logs.

**Comment by Csana111** [comment]
I deployed it as a daemonset with helm charts. (and also I have only one node in the cluster)

**Comment by patrick-stephens** [comment]
> if I run standalone pods (without deployment and daemonset), it cannot see this change and does not collect logs from them

OK, what does this mean? To me it sounded like you were deploying Fluent Bit "standalone". Are you running them via `kubectl run`? If so, are the pod logs on the actual node? If not then Fluent Bit won't see them.

**Comment by Csana111** [comment]
So, I have only one node. I install FluentBit with helm with my own values, and I wrote the above configuration into default values.yaml. I have a deployment (handler) which run pods if its needed (when I run simulations - and these simulations run on 1-20 pods). And when it runs these pods, FluentBit cannot see them. This is my problem.

**Comment by patrick-stephens** [comment]
Does the node have the pod logs?

**Comment by Csana111** [comment]
Yes, I can get it with kubectl logs, and I can list them with kubernetes dashboard as well.
