### ISSUE TITLE
Add TLS support to input elasticsearch

### ISSUE THREAD

**Issue by gulywwx** [fluent/fluent-bit#8029]
**Is your feature request related to a problem? Please describe.**

Provide support for using TLS when using elasticsearch input.

**Describe the solution you'd like**

Similar to elasticsearch output plugins, the usual security configuration for TLS:

```
[INPUT]
    Name elasticsearch
    Listen 0.0.0.0
    Port 9200
    buffer_max_size     20M
    buffer_chunk_size   10M    
    tls on
    tls.verify on
    tls.ca_file ca.crt
    tls.crt_file host.crt
    tls.key_file host.key
```

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Is it not supported? I thought it was...

**Comment by gulywwx** [comment]
The version is v2.1.10. I am running a container

Thanks @patrick-stephens, it does support TLS.  Would you mind updating the document https://docs.fluentbit.io/manual/administration/transport-security to reflect this feature?
