### ISSUE TITLE
Modify Filter not applying rename rules correctly in v2.1.10

### ISSUE THREAD

**Issue by vesalaakso-rovio** [fluent/fluent-bit#8033]
## Bug Report

**Describe the bug**
The modify filter in Fluent Bit version 2.1.10 does not seem to be applying the rename rules correctly for simple JSON logs. Despite the presence of matching keys in the log, the rename rules aren't applied. However, when adding a test key-value pair `TESTKEY: TESTVALUE`, it appears correctly, suggesting the filter is processing, but specific rename rules are not being applied as expected.

**To Reproduce**
- Example log message if applicable:
```
{
  "L": "INFO",
  "T": "2023-10-12T18:28:20.583Z",
  "M": "[360] Request served",
  "path": "/",
  "comment": "",
  "clientIP": "ip",
  "method": "GET",
  "statusCode": 200,
  "latency": "25.874µs",
  "reqID": "id"
}
```
```
{"level":"info","msg":"message","time":"2023-10-12T17:50:19Z"}
```
- Steps to reproduce the problem:

1. Configure Fluent Bit with the modify filter as shown below.
2. Feed the mentioned example log messages into Fluent Bit.
3. Observe that the keys aren't renamed as expected, but the added test key-value pair appears correctly.

 - Debug log of the fluent bit
```
[debug] [filter:modify:modify.0] Rule RENAME M TO message : No keys matching M found, not applying rule
[debug] [filter:modify:modify.0] Rule RENAME msg TO message : No keys matching msg found, not applying rule
[debug] [filter:modify:modify.0] Rule RENAME L TO level : No keys matching L found, not applying rule
```
**Expected behavior**
The modify filter should successfully rename the keys based on the rules provided in the configuration. The log keys L, M, and msg should be renamed to level and message respectively.

**Your Environment**

* Version used: Fluent Bit 2.1.10
* Configuration:
```
[FILTER]
    Name   modify
    Match  *
    Rename L level
    Rename M message
    Rename msg message
    Add TESTKEY TESTVALUE
```
* Environment name and version (e.g. Kubernetes? What version?): 1.26
* Filters and plugins: Modify filter

**Additional context**
As a test to verify the modify filter's functionality, I added the key-value pair `TESTKEY: TESTVALUE`. This key-value pair appeared correctly in the processed logs, confirming that the filter is functioning to some extent, but there's a specific issue with the rename rules.

**Comment by patrick-stephens** [comment]
@vesalaakso-rovio any chance you could set up a full config that reproduces it with `dummy` input and then an `expect` filter?

**Comment by vesalaakso-rovio** [comment]
I couldn't reproduce my issue using dummy input. The fields were modified correctly, so the problem must be elsewhere. I wonder if my configuration is correct? I'm using Elasticsearch output.

Here is my full configuration
```
[SERVICE]
    Flush 1
    Daemon Off
    Log_Level info
    Parsers_File parsers.conf
    Parsers_File custom_parsers.conf
[INPUT]
    Name tail
    Path /var/log/containers/*.log
    multiline.parser cri
    Tag kube.*
    Mem_Buf_Limit 5MB
    Skip_Long_Lines On
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix     kube.var.log.containers.
    Merge_Log           On
    Merge_Log_Trim      On
    Keep_Log            Off
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Use_Kubelet         On
    Kubelet_Port        10250
    Buffer_Size         256KB
[FILTER]
    Name   modify
    Match  kube.*
    Rename L level
    Rename M message
    Rename msg message
[OUTPUT]
    Name                es
    Match               kube.*_mynamespace_*
    Host                elasticsearch-endpoint
    Port                443
    Logstash_Format     On
    Logstash_Prefix     mynamespace
    Logstash_DateFormat %Y.%W
    Retry_Limit         10
    tls                 On
    Replace_Dots        On
    Generate_ID         On
    Suppress_Type_Name  On
```

**Comment by vesalaakso-rovio** [comment]
Thank you so much. I was doing it wrong. I added following to my configuration and it started to work.

```
    [FILTER]
        Name         parser
        Match        kube.*
        Key_Name     log
        Parser       json
        Reserve_Data On
    [FILTER]
        Name   modify
        Match  kube.*
        Rename L level
        Rename M message
        Rename msg message
```
