### ISSUE TITLE
Hot reload finished but had "requested parser xxx not found" and other failures

### ISSUE THREAD

**Issue by ym11369** [fluent/fluent-bit#8038]
## Bug Report

**Describe the bug**
Tried **2.1.10** both on container and local host machine, both show same issue below. 

Local run errors(log level : info):
fluent-bit configuration reference a parsers configuration and had some parser definition in parsers file. When trigger hot-reload, shown error messages like: ` parser 'extract_kubelet_log' is not registered`, `requested parser 'extractinfo' not found"`, `Failed to connect to mdsd: dial unix /var/run/mdsd/default_djson.socket: connect: no such file or directory` etc.

And fluent-bit hot-reload port seems crashed then as well. 
  ```
curl -X GET localhost:2020/api/v2/reload
curl: (7) Failed to connect to localhost port 2020: Connection refused
```

But after restart fluent-bit with `systemctl restart fluent-bit`, fluent-bit works well.

**To Reproduce**

container run failure logs(log level : debug):
[reloadlog.txt](https://github.com/fluent/fluent-bit/files/12892247/reloadlog.txt)

- Steps to reproduce the problem:
1. fluent-bit config reference a parser config
2. send http post request  `curl -X POST -d '{}' localhost:2020/api/v2/reload` to reload a running fluent-bit service
3. check the status of fluent-bit

**Expected behavior**

Hot reload with no errors and no need to restart fluent-bit by systemctl or docker command

**Screenshots**

![image](https://github.com/fluent/fluent-bit/assets/65710487/ae46b4c2-2114-4550-b3bb-893acad00a86)
![image](https://github.com/fluent/fluent-bit/assets/65710487/6830a7d0-e3ea-406b-96ee-591a758e9ef6)

**Your Environment**

* Version used: 2.1.10
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version:
* Operating System and version: Ubuntu 20.04.6 LTS
* Filters and plugins: Upload the configurations that I use.

[config.zip](https://github.com/fluent/fluent-bit/files/12892168/config.zip)

**Comment by patrick-stephens** [comment]
@ym11369 please include the config inline to help viewing it. Can you try with an absolute rather than relative path as well for the parser config file?

@cosmo0920 I think we saw this previously with working-directory not being the default?

**Comment by ym11369** [comment]
And the parsers.conf like below:

```
[PARSER]
    Name    extractinfo
    Key_Name source_path
    Format  regex
    Regex   ^/var/log/pods/(?<EnvNamespace>[^_]+)_(?<Pod>.+)-[a-z0-9]+_[a-z0-9]+/(?<Container>.+)/[a-z0-9]+\.log

[PARSER]
    Name              extractlog
    Format            regex
    Key_Name          log
    Regex             ^(?<time>[^ ]*) [^ ]* [^ ]* (?<log>.*)$
    Decode_Field_As   json       log

[PARSER]
    Name              extract_event_log
    Format            json
    Time_Key          time
    Time_Format       %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep         On

[PARSER]
    Name              extract_kubelet_log
    Format            regex
    Key_Name          log
    Regex             ^[^ ]* (?<time>[^ ]*)\s+[^ ]* (?<caller>[^ ]*) (?<log>.*)$

[PARSER]
    Name              extract_syslog
    Format            regex
    Key_Name          log
    Regex             ^(?<LocalTime>[^ ]* {1,2}[^ ]* [^ ]*) (?<Host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<ProcessId>[0-9]+)\])?(?:[^\:]*\:)? *(?<Message>.*)$


```

**Comment by patrick-stephens** [comment]
I know it is in the same folder but please try with an absolute path.

**Comment by ym11369** [comment]
@patrick-stephens  Thanks, tried with absolute path, it looks good to me now.

**Comment by patrick-stephens** [comment]
@cosmo0920 so did we resolve this on master?

**Comment by cosmo0920** [comment]
Hmm..., not sure it's solved master. I'll take a look tomorrow/

**Comment by ym11369** [comment]
@patrick-stephens 
And have another findings during my test which try to make some indentation error in fluent-bit.conf or syntax error in reference lua file. The status of fluent-bit thread is different between 'reload' and 'systemctl restart'. Is this an expected behavior?  **Reload** usually didn't kill the thread even have errors. **systemctl restart** will failed to start fluent-bit if any error.

Details:
1. Tried to deliberately make some indentation error in fluent-bit.conf 

**Reload**:
Reload post request returned `200 OK` and response was  `{"reload":"done","status":0}`. The output of `systemctl status fluent-bit` looks no error's during this reload.  fluent-bit thread alive. And it seems used old-cached fluent-bit.conf to run.
![image](https://github.com/fluent/fluent-bit/assets/65710487/03f2c12d-eede-4a08-946c-8941f5a557fe)

And we can find the error in /var/log/syslog
![image](https://github.com/fluent/fluent-bit/assets/65710487/912dc9b2-5725-4ef7-96a7-60a6d8f37922)

**Restart**
But when we run `systemctl restart fluent-bit` the fluent-bit failed to be started.
![image](https://github.com/fluent/fluent-bit/assets/65710487/b1e6bd21-218a-4963-a89b-4512ee281180)

/var/log/syslog
![image](https://github.com/fluent/fluent-bit/assets/65710487/8df0b960-254f-48e2-b7a8-8ffaa74c85c0)

2. Tried to deliberately make some syntax error in reference lua file

**Reload**:

 The output of `systemctl status fluent-bit` show errors `[luajit] error loading script: //etc/fluent-bit/modify_user_record.lua:80: 'end' expected (to close 'for' at line 5) near '<eof>'` as expected. But fluent-bit thread looks alive. **But the 2020 port was not work anymore**.
![image](https://github.com/fluent/fluent-bit/assets/65710487/83e4ec5f-5f70-437d-b9ed-7178e948ffa4)

Consistent with /var/log/syslog
![image](https://github.com/fluent/fluent-bit/assets/65710487/d9a7e404-f3d7-43f5-8d21-c2e596be52ae)

**Restart**
Same with 1, just different error msg, thread killed same with 1

![image](https://github.com/fluent/fluent-bit/assets/65710487/30b4a674-ba86-4185-afb9-5b7f5001df5d)

**Comment by patrick-stephens** [comment]
I would raise a separate issue explicitly with the details - it's confusing to start other issues in comments and hard to say a PR resolves a comment vs an issue.

**Comment by canob** [comment]
The same problem here with hot reload using Linux FluentBit Container.
If I execute a `curl -X POST -d '{}' localhost:2020/api/v2/reload` inside the container (I'm using the debug docker image) , FluentBit stop working:
```
[2023/11/03 13:36:33] [ info] [reload] start everything
[2023/11/03 13:36:33] [ info] [fluent bit] version=2.1.10, commit=b19e9ce674, pid=1
[2023/11/03 13:36:33] [ info] [storage] ver=1.5.1, type=memory+filesystem, sync=full, checksum=off, max_chunks_up=128
[2023/11/03 13:36:33] [ info] [storage] backlog input plugin: storage_backlog.10
[2023/11/03 13:36:33] [ info] [cmetrics] version=0.6.3
[2023/11/03 13:36:33] [ info] [ctraces ] version=0.3.1
[2023/11/03 13:36:33] [ info] [input:syslog:syslog.0] initializing
[2023/11/03 13:36:33] [ info] [input:syslog:syslog.0] storage_strategy='filesystem' (memory + filesystem)
[2023/11/03 13:36:33] [error] [lib] backend failed
[2023/11/03 13:36:33] [error] [in_syslog] parser not set
[2023/11/03 13:36:33] [error] [input:syslog:syslog.0] could not initialize plugin
[2023/11/03 13:36:33] [error] failed initialize input syslog.0
[2023/11/03 13:36:33] [error] [engine] input initialization failed
[2023/11/03 13:36:34] [engine] caught signal (SIGSEGV)
#0  0x55f29c5b9fa0      in  flb_input_thread_instance_exit() at src/flb_input_thread.c:522
#1  0x55f29c5ac46d      in  flb_input_instance_exit() at src/flb_input.c:1283
#2  0x55f29c5ac523      in  flb_input_exit_all() at src/flb_input.c:1311
#3  0x55f29c5ebee7      in  flb_engine_shutdown() at src/flb_engine.c:1089
#4  0x55f29c58f28b      in  flb_lib_worker() at src/flb_lib.c:641
#5  0x7f752fa26ea6      in  start_thread() at reate.c:477
#6  0x7f752f2daa2e      in  ???() at sysv/linux/x86_64/clone.S:95
#7  0xffffffffffffffff  in  ???() at ???:0
```
After that error, I restart the container and FluentBit works as usual, but that happens every time I tried a hot reload.

**Comment by canob** [comment]
Finally, was this solved with the latest commits? Is going to be solved on next Fluentbit release, when the last commits will be merged?

**Comment by patrick-stephens** [comment]
@canob you're using an older version, are you still seeing issues with 2.2.0? As I say, please raise a separate issue rather than commenting on closed ones as most people will not see it.

**Comment by canob** [comment]
Thanks @patrick-stephens 
The issue is still there in new version 2.2.0, so I'm going to open a new issue.

**Comment by ym11369** [comment]
Sorry for the late response. Didn't have chance to have a try for personal errands. We can track with canob's new issue.

**Comment by zhaohongda1987** [comment]
I also face this problem with version 2.2.0, The phenomenon is consistent with hot reload failed and restart fluent-bit k8s pod is working well.
this is the error log:
`[2023/11/22 02:22:53] [ warn] [input:systemd:systemd.11] seek_cursor failed
[2023/11/22 02:22:53] [ info] [input:tail:tail.12] initializing
[2023/11/22 02:22:53] [ info] [input:tail:tail.12] storage_strategy='memory' (memory only)
[2023/11/22 02:22:53] [ info] [input:tail:tail.13] initializing
[2023/11/22 02:22:53] [ info] [input:tail:tail.13] storage_strategy='memory' (memory only)
[2023/11/22 02:22:53] [ info] [input:tail:tail.14] initializing
[2023/11/22 02:22:53] [ info] [input:tail:tail.14] storage_strategy='memory' (memory only)
[2023/11/22 02:22:53] [ info] [filter:multiline:multiline.0] created emitter: emitter_for_multiline.0
[2023/11/22 02:22:53] [ info] [input:emitter:emitter_for_multiline.0] initializing
[2023/11/22 02:22:53] [ info] [input:emitter:emitter_for_multiline.0] storage_strategy='memory' (memory only)
[2023/11/22 02:22:53] [error] [lib] backend failed
[2023/11/22 02:22:53] [error] [multiline] parser 'multiline-regex-1' not registered
[2023/11/22 02:22:53] [error] Failed initialize filter multiline.0
[2023/11/22 02:22:53] [error] [engine] filter initialization failed
[2023/11/22 02:22:54] [ info] [input] pausing tail.0`

**Comment by patrick-stephens** [comment]
Please don't comment on a closed issue.
