### ISSUE TITLE
Fluent-bit not reading logs from java application

### ISSUE THREAD

**Issue by NicholasK13** [fluent/fluent-bit#804]
Issue:
I'm trying to send logs from my java application to fluent-bit which is present on a remote photon-os based machine. I'm using logback for implementing it.

```
public class App {
  private final static Logger logger = LoggerFactory.getLogger(App.class);

  public static void main(String[] args) {
   for (int i = 0; ; i++) {
      logger.debug("Warn msg");
      try {
         Thread.sleep(5000);
       } catch (InterruptedException e) {
        // do nothing now
      }
   }
 }
}
```

logback.xml

       
```
<configuration>

	<!-- for JSON logs -->
	<appender name="json" class="ch.qos.logback.core.ConsoleAppender">
		<layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
			<jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
				<prettyPrint>true</prettyPrint>
			</jsonFormatter>
			<timestampFormat>yyyy-MM-dd' 'HH:mm:ss.SSS</timestampFormat>
		</layout>
	</appender>

        <!-- for FLUENTD logs -->
	<appender name="fluentd" class="ch.qos.logback.more.appenders.DataFluentAppender">

		<remoteHost>xx.xxx.xxx.xxx</remoteHost>
		<port>7777</port>

		<layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
			<jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
			</jsonFormatter>
			<timestampFormat>yyyy-MM-dd' 'HH:mm:ss.SSS</timestampFormat>
		</layout>

	</appender>

        <root level="TRACE">
		<appender-ref ref="fluentd" />
		<appender-ref ref="json" />
	</root>
</configuration>
```

This is what gets printed in my console using the json appender
_{"timestamp":"2018-09-28 12:41:03.394","level":"DEBUG","thread":"main","logger":"org.efk.com.App","message":"logging and logging","context":"default"}_

Here's the fluent-bit configuration : 
td-agent-bit.conf

```
[INPUT]
    Name          tcp
    Listen        xx.xxx.xxx.xxx
    Port          7777
    Chunk_Size    1024
    Buffer_Size   2048

[OUTPUT]
    Name          stdout
```

When i see the logs I get this exception 

_[2018/09/28 07:04:48] [trace] [in_tcp] read()=93 pre_len=0 now_len=93
[2018/09/28 07:04:48] [debug] [in_serial] invalid JSON message, skipping
[2018/09/28 07:04:53] [trace] [in_tcp] read()=93 pre_len=93 now_len=186
[2018/09/28 07:04:53] [debug] [in_serial] invalid JSON message, skipping_

Also I am able to see the output when I test my configuration from the command line via 
_echo '{"key 1": 10, "key 2": "YYY"}' | nc xx.xxx.xxx.xxx 7777_
This outputs : 
_[0] tcp.0: [1538116716.154995913, {"key 1"=>10, "key 2"=>"YYY"}]_

I'm able to print the logs in my console and it indeed is in valid format. I've been cracking my head for 2 days on this, any help is highly appreciated.

**Comment by edsiper** [comment]
I tried to reproduce the problem without success. Do you think you can provide a Java program ready to reproduce ?

**Comment by NicholasKurian** [comment]
My app as of now just contains 3 files : App.java, logback.xml and the pom.xml. I've edited my question to include the entire App.java and the logback.xml. Are you asking for the entire project as a jar?

**Comment by edsiper** [comment]
Yeah, something that I can run easily (my Java skills are zero)

**Comment by NicholasK13** [comment]
I could share it but the code currently connects to a remote machine within a VPN. You would not be able to execute it. So how do we proceed with it?

**Comment by edsiper** [comment]
Example.jar that perform tcp connection and send the json string to
reproduce the problem

**Comment by NicholasK13** [comment]
Can you please let me know the remote host and port so I can configure that in my app, so when I export it all you will need to do is to execute the jar.

**Comment by NicholasK13** [comment]
@edsiper : Really looking forward for further assistance on this bug - please do let me know if you require additional assistance/help from my end to further debug the issue.

**Comment by edsiper** [comment]
A simple cfg file to alter host and port

**Comment by NicholasK13** [comment]
I'm attaching the executable jar, you need to do the following : 

1. Change the name from **_EFK-v1.0.txt_** to **_EFK-v1.0.jar_**. Was not able to upload a .jar to github.
2. Run it using the following command : 
**java -DHOST="xx.xxx.xxx.xxx" -DPORT="xxxxx" -jar EFK-v1.0.jar**
    (You will need to substitute the values for -DHOST and -DPORT accordingly)

Do let me know if you need more info.
[EFK-v1.0.txt](https://github.com/fluent/fluent-bit/files/2429229/EFK-v1.0.txt)

**Comment by edsiper** [comment]
thanks. I was able to reproduce the problem, I will troubleshoot during the week.

**Comment by edsiper** [comment]
@NicholasK13 

Your test application is writing messages in Fluentd protocol format which is called "Forward", if you enable _forward_ input plugin in Fluent Bit you will be able to receive the messages properly:

```
[0] debug.test: [1538312126.000000000, {"level"=>"DEBUG", "logger"=>"org.efk.com.App", "thread"=>"main", "message"=>"logging and logging"}]
```

Note that TCP Input plugin only accept JSON maps as records and not msgpack as forward protocol does.

**Comment by NicholasK13** [comment]
**@edsiper** 

Ah okay that worked. Thanks for your time. I was trying to use fluent-bit for HA and as per [this](https://github.com/fluent/fluent-bit/issues/565) it doesn't offer any features like fluentd. Can you please let me know if fluent-bit has added any more features or is fluentd better when it comes to HA?

**Comment by NicholasK13** [comment]
Appreciate your time and help on this @edsiper!
