### ISSUE TITLE
[Documentation] The description of storage.total_limit_size is misleading

### ISSUE THREAD

**Issue by aliaksei-audonin** [fluent/fluent-bit#8055]
## Bug Report

**Describe the bug**
The description of `storage.total_limit_size` under [https://docs.fluentbit.io/manual/administration/buffering-and-storage#output-section-configuration](https://docs.fluentbit.io/manual/administration/buffering-and-storage#output-section-configuration) suggests that the value is the number of chunks whereas actually it's the size of the disk space that can be used for buffering.

**To Reproduce**
- Set `storage.total_limit_size 1024` expecting the resulting limit in 1024 x 2MB(Chunk size) = 2048MB
- Restart Fluent Bit
- Example log message:
```
[input chunk] fail to drop enough chunks in order to place new data
```

**Expected behavior**
Documentation should be updated to reflect that the value is size in bytes, not the number of Chunks.

**Your Environment**
* Version used: 2.1.10
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes, 1.25
* Filters and plugins: opensearch

Thank you.

**Comment by lecaros** [comment]
Hello @aliaksei-audonin,
Thanks for catching this; I think what you say makes sense. Would you like to submit a PR? I'll gladly take care of it if you do.

**Comment by opencmit2** [comment]
Hi @lecaros

**Comment by opencmit2** [comment]
Hi @lecaros 
If it helps move things along, I'm glad to take care of the corrections. Just assign the issue over to me.

**Comment by lecaros** [comment]
Hi @opencmit2,
you can submit a PR in https://github.com/fluent/fluent-bit-docs.
