### ISSUE TITLE
Add COUNT DISTINCT function to FluentBit Stream Processing

### ISSUE THREAD

**Issue by canob** [fluent/fluent-bit#8059]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a use case based on NG firewall logs with Stream Processing to aggregate how many different origin IPs a user had in last five minutes.

**Describe the solution you'd like**
With COUNT DISTINCT function, I can get the number of unique values in the column or expression, in this case, origin IP column.

**Describe alternatives you've considered**
Do it outside FluentBit, with other stream processor, for example Benthos, https://www.benthos.dev, or put the events in a relational database like MySQL/MariaDB/PostgreSQL and use COUNT DISTINCT.

**Additional context**
I think it is a really good addition to FluentBit Stream Processing.

**Comment by patrick-stephens** [comment]
Looks like was responded to here as well for anyone finding this: https://github.com/fluent/fluent-bit/discussions/8034#discussioncomment-7277657
