### ISSUE TITLE
Q: cpu input plugin error on mac m2 pro

### ISSUE THREAD

**Issue by phiremande** [fluent/fluent-bit#8079]
## Bug Report

**Describe the bug**

cpu output plugin isn't working on apple mac M2 pro device.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
Please check the attached screen shot.
```
- Steps to reproduce the problem:
https://docs.fluentbit.io/manual/v/1.9-pre/installation/macos

compile the fluent-bit binary using the steps mentioned in the above link.
run fluent-bit -c <config-file>
with configuration file containing the mentioned configuration.

**Expected behavior**

No error should be shown and cpu metrics need to be output to stdout.

**Screenshots**

**Your Environment**

* Version used: latest from master
* Configuration: cmake -DFLB_CONFIG_YAML=Off -DFLB_ALL=On ../
* [SERVICE]
*     Flush 5
*     Daemon Off
*     Log_Level debug
* [INPUT]
*     Name cpu
*     tag my_cpu
* [OUTPUT]
*     Name stdout
*     Match *
* Environment name and version (e.g. Kubernetes? What version?): Mac laptop
* Server type and version: Apple M2 Pro
* Operating System and version: macOS Ventura 13.6, 
* Filters and plugins: cpu input plugin and stdout output plugin
![SmartSelect_20231023_145111_Photo Editor](https://github.com/fluent/fluent-bit/assets/16595434/960aa40a-46ab-4a1b-bc5a-a8e7979ed40f)

**Additional context**

**Comment by lake2** [comment]
same issue +1

**Comment by lake2** [comment]
mac m3 pro:
<img width="1630" height="556" alt="Image" src="https://github.com/user-attachments/assets/e8606bc1-9e3f-46d8-b704-6b3aae8c0191" />
