### ISSUE TITLE
[out_loki] Add support for structured metadata

### ISSUE THREAD

**Issue by thomaschaaf** [fluent/fluent-bit#8080]
**Is your feature request related to a problem? Please describe.**
Searching for requestIds is slow with loki. We would like to provide it with structured metadata so that it is faster at searching for things like request ids.

**Describe the solution you'd like**
Allow to send structured metadata: https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/

**Comment by ptr1120** [comment]
+1

**Comment by jtackaberry** [comment]
Not stale. Necessary feature as many of us are using labels to encode information that really should be structured metadata (such as certain annotations coming from K8s pods).

**Comment by jtackaberry** [comment]
Loki 3.0 is now out and structured metadata is officially stable.

**Comment by jtackaberry** [comment]
I've submitted PR #9048 for this one.
