### ISSUE TITLE
About fluent-bit to support "multi-process workers"

### ISSUE THREAD

**Issue by YuWan1117** [fluent/fluent-bit#8088]
**Is your feature request related to a problem? Please describe.**

We use `fluent-bit` to collect `kubernetes logs` via the `tail` input plugins, and our `CPU limit` is set to 2, but in some traffic burst scenarios, some `fluent-bit` pod `CPU` reaching 1 seem to be a bottleneck.

### The Pods CPU Usage
![image](https://github.com/fluent/fluent-bit/assets/7919137/adb0b705-edbd-4472-90bb-97aac31dd6e3)

### Resource Config
```yaml
resources:
  limits:
    cpu: 2000m
    memory: 1000Mi
  requests:
    cpu: 30m
    memory: 50Mi
```

My fluent-bit input config is as follows: 

### Input Config
```yaml
  inputs: |
    [INPUT]
        Name  tail
        Path  /data/logs/*/*/*/*.log
        DB    /var/log/fluent/test/service-log.db
        Tag   servicelog.*
        Multiline         On
        Multiline_Flush   4
        Parser_Firstline  multiline
        Mem_Buf_Limit     400MB
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   32k
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
        Read_from_Head    True

    [INPUT]
        Name  tail
        Path  /var/log/pods/*/*/*.log
        DB    /var/log/fluent/test/containers-std-log.db
        Tag   containers-std-log.*
        multiline.parser  docker, cri
        Mem_Buf_Limit     400MB
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   32k
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
        Read_from_Head    True
```

**Describe the solution you'd like**

**I expect to specify that these two tails (serviceLog processing & containerLog processing) use different processes for efficient CPU utilization**.
Whether it is possible to support `multi-process-workers` functionality similar to that provided by `fluentd`？
https://docs.fluentd.org/deployment/multi-process-workers

Thanks for your help firstly.

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Output workers are supported - just specify them, e.g. https://docs.fluentbit.io/manual/pipeline/outputs/kinesis#worker-support
However most output plugins default to more than 1 I think in more recent versions as well - you do not indicate what version of Fluent Bit you are using so make sure it is the latest (2.1.10 currently).

Tail can also use `threaded on` I believe to use a separate thread.

We should expand the docs though to help people so please submit a docs PR if it helps you: https://github.com/fluent/fluent-bit-docs

**Comment by drbugfinder-work** [comment]
We're observing a similar behavior as described by @YuWan1117. In our pipeline(s), we're using a mix of `Tag rewrite,` `Multiline`, and `Lua` filters. It seems that the Lua component, specifically, is bottlenecking, fully occupying a single core during high-load scenarios (where all multi-threaded inputs are coming together into a single-threaded filter). Thread-support for input and output will not help with this particular issue.
Would it be possible to also add thread-support to the filters (all? subset?)

**Comment by patrick-stephens** [comment]
Filters can be run as processors which then associates them with the workers/threads for the input or output they are associated with. Unfortunately this means they cannot match, but use the input or output match to control what records are run through them but it may be good enough for what you want?
- https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file#config_processors

**Comment by drbugfinder-work** [comment]
@patrick-stephens You're right, that could help in some cases! Unfortunately, this is only available in YAML configuration style. 
Also this would require multiple processing (e.g. Lua filter), if the same record goes to multiple outputs - so multi-threaded filters still would be very helpful to have.

**Comment by patrick-stephens** [comment]
Agreed, however I wanted to highlight some options for now. I think multi-threaded filters may need a bit of work but that's not really something I can comment on, any contribution to implement it greatly appreciated too.

**Comment by YuWan1117** [comment]
Thanks for your reply firstly.

> Output workers are supported - just specify them, e.g. https://docs.fluentbit.io/manual/pipeline/outputs/kinesis#worker-support However most output plugins default to more than 1 I think in more recent versions as well - you do not indicate what version of Fluent Bit you are using so make sure it is the latest (2.1.10 currently).

That's right. 
I know the `output` support `workers`, and we set `workers` to 2. And I use `fluent-bit` with `2.1.7` version.

> Tail can also use `threaded on` I believe to use a separate thread.

About the  `threaded on` configuration you mentioned, I didn't find any information about it in the `fluent-bit` doc for the `Tail` Input. Hope you providing the  doc about `threaded on`.

> https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file#config_processors

The `processors` functionality is only exposed in YAML configuration. How should I use it in the way I deploy `fluent-bit` with Helm?

Thanks.

**Comment by YuWan1117** [comment]
I just founded the [developer-guide doc](https://docs.fluentbit.io/manual/development/developer-guide#input:~:text=.flags%20%20%20%20%20%20%20%20%3D-,FLB_INPUT_THREADED,-%7D%3B)  that mentions the `FLB_INPUT_THREAD`.  And I view the source code when set `Threaded on` property will run in a separate thread.

**Comment by YuWan1117** [comment]
When I add the `Threaded On` in the `tail` config, it appears some errors with `2.1.7` version. 

### The error log
```
[2023/11/22 06:29:13] [error] [/src/fluent-bit/src/flb_input_chunk.c:1875 errno=2] No such file or directory
[2023/11/22 06:29:25] [error] [/src/fluent-bit/src/flb_input_chunk.c:1875 errno=11] Resource temporarily unavailable
```

The errors like this, I don't find the reason:
<img width="1123" alt="image" src="https://github.com/fluent/fluent-bit/assets/7919137/d0e17d82-d885-4c15-8925-cdc71c5f3c81">

**But when I upgrade the `fluent-bit` image to `2.1.10` version, it doesn't appear errors.** 

### Input Config
```yaml
  inputs: |
    [INPUT]
        Name  tail
        Path  /data/logs/*/*/*/*.log
        DB    /var/log/fluent/test/service-log.db
        Tag   servicelog.*
        Multiline         On
        Multiline_Flush   4
        Parser_Firstline  multiline
        Mem_Buf_Limit     400MB
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   32k
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
        Threaded       On
        Read_from_Head    True

    [INPUT]
        Name  tail
        Path  /var/log/pods/*/*/*.log
        DB    /var/log/fluent/test/containers-std-log.db
        Tag   containers-std-log.*
        multiline.parser  docker, cri
        Mem_Buf_Limit     400MB
        Buffer_Chunk_Size 32k
        Buffer_Max_Size   32k
        Skip_Long_Lines   On
        Skip_Empty_Lines  On
        Threaded       On
        Read_from_Head    True
```

**Comment by patrick-stephens** [comment]
Sure, use latest is always the guidance. Bugs are fixed and features are implemented.
2.2.0 is now the latest btw.
