### ISSUE TITLE
Package builds failing due to time zone config on Actuated runners

### ISSUE THREAD

**Issue by patrick-stephens** [fluent/fluent-bit#8111]
## Bug Report

**Describe the bug**

Package builds are hitting a timeout due to waiting for interactive set up of timezones on the Actuated runners: https://github.com/fluent/fluent-bit/actions/runs/6702694931/job/18212073059#step:9:441

```
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa   3. Antarctica  5. Arctic  7. Atlantic  9. Indian    11. US
  2. America  4. Australia   6. Asia    8. Europe    10. Pacific  12. Etc
Error: The action has timed out.
```

Workflow was updated via https://github.com/fluent/fluent-bit/pull/8107 to add a timeout (hit above) to prevent 6 hours wait time and also set `DEBIAN_FRONTEND=noninteractive` however this does not seem to have resolved it.

**Comment by alexellis** [comment]
Quick question for you @patrick-stephens 

Is this a new workflow, or an existing one that broke?

**Comment by patrick-stephens** [comment]
Not new, been there for over a year I think so yeah only recently broke.
The one liner is basically this: https://github.com/fluent/fluent-bit/blob/0ae1dba373e38c2aac109e8e67378dc6d2ac1d1b/.github/workflows/call-build-linux-packages.yaml#L166-L167

**Comment by alexellis** [comment]
It seems like we don't have the tzdata package yet, so that's what awscli is trying to add. We'll put it into the base image now.

**Comment by patrick-stephens** [comment]
Cheers, yeah that should solve it as then it'll be configured.

**Comment by patrick-stephens** [comment]
@alexellis if you let me know when I can trigger another unstable build or it'll run again tomorrow morning.

**Comment by alexellis** [comment]
These builds show the above steps running as expected: https://github.com/cncf-tests/tzdata/actions

**Comment by patrick-stephens** [comment]
Looks ok now.
