### ISSUE TITLE
The NEW_TAG parameter of the rewrite_tag filter concatenates the current date

### ISSUE THREAD

**Issue by peng3693** [fluent/fluent-bit#8119]
## Bug Report

**Describe the bug**

I want to concatenate the current date to the new_tag, but it doesn't work, and I'm not sure if my following supports it
`
[FILTER]
    Name                rewrite_tag
    Match               my_tag
    Rule                $log ^(.*)$ aaa-${strftime(%Y%m%d)}
`

I also don't have the current date in my record, so I can't do the following:
**$TAG[4]-$record_date.log**
Is there any way to achieve the results I want?

**Expected behavior**

**aaa-20231102**

**Comment by patrick-stephens** [comment]
Inject the current date into a key (e.g. with LUA) and then just use it?

**Comment by peng3693** [comment]
> Inject the current date into a key (e.g. with LUA) and then just use it?
Yes, that's the only way I can think of right now, using lua scripts to add and then remove.

    [FILTER]
        Name                lua
        Match               aaa-*
        script              /fluent-bit/scripts/record_date.lua
        call                record_date

    [FILTER]
        Name                rewrite_tag
        Match               aaa-*
        Rule                $record_date ^(.*)$ $TAG-$record_date.log false

    [FILTER]
        Name                record_modifier
        Match               aaa-*
        Remove_key          record_date
