### ISSUE TITLE
storage.sync full does not what is statet in documentation / may lead to blocking docker container

### ISSUE THREAD

**Issue by JSchy65** [fluent/fluent-bit#8128]
The Buffering & Storage documentation states about the storage.sync parameter:

"Using full increases the reliability of the filesystem buffer and ensures that data is guaranteed to be synced to the filesystem even if Fluent Bit crashes. On linux, full corresponds with the MAP_SYNC option for memory mapped files."

But this is not the way, it is implemented.

See nmap docu (https://man7.org/linux/man-pages/man2/mmap.2.html):
```
MAP_SYNC:

"This flag is available only with the MAP_SHARED_VALIDATE mapping type"

and

"Shared file mappings with this flag provide the guarantee that while some memory is mapped
 writable in the address space of the process, it will be visible in the same file at the same
 offset even after the system crashes or is rebooted."
```

See Fluent Bit Sources:

**cio_file_unix.c**

Only the MAP_SHARED flag is used. MAP_SHARED_VALIDATE is never used. If MAP_SYNC would be used, it wouldn't work.

**cio_file_native_sync()** about line 480:
```
if (sync_mode & CIO_FULL_SYNC) {
        sync_mode = MS_SYNC;
    }
    else {
        sync_mode = MS_ASYNC;
    }

    result = msync(cf->map, cf->alloc_size, sync_mode);
```
Choosing the full option does not lead to the usage of MAP_SHARED_VALIDATE in conjunction with MAP_SYNC as documented, but to the usage of MS_SYNC.

See msync docu (https://man7.org/linux/man-pages/man2/msync.2.html):
```
MS_ASYNC: Specifies that an update be scheduled, but the call returns immediately.

MS_SYNC: Requests an update and waits for it to complete.
```

That means, that instead of the MAP_SYNC only MS_SYNC is used. **But this has nothing to do with "guaranteed to be synced to the filesystem even if Fluent Bit crashes"**. MS_SYNC does not guarante this. Instead, the call to msync() comes back, if the contents are written to file. As a result, because the chunks are written synchronously, the usage of storage.sync full takes longer time to execute and therefore increases the risk of backpressure, which in case of logging through docker logging container, may increase the risk of blocking container even in a moderate load scenario. Using storage.sync normal = MS_ASYNC reduces this risk dramaticaly in my use case.

**Please change the documention in a way, that reflects what really is implemented**:
```
storage.sync normal:

   Chunks are written to file asynchrously.

storade.sync full:

   Chunks are written to file synchronously. Because that blocks the write process
   until the file is written, this option may, dependend on your load scenarion, increase
   the risk of backpressure. If used in conjunction with the Docker fluentd Logging Driver,
   it may increases the risk of blocking container.
```
I write this issue, because that was exact what happend to me. I believed, I get more reliability of the filesystem buffer but ended up in blocking docker containers.

**Comment by patrick-stephens** [comment]
Can you submit a docs PR with the updates?
https://github.com/fluent/fluent-bit-docs/blob/master/administration/buffering-and-storage.md
