### ISSUE TITLE
High CPU / Memory usage using `kubernetes_events` plugin

### ISSUE THREAD

**Issue by mkatana-silkycoders** [fluent/fluent-bit#8138]
Tested Fluent-bit Version:
- 2.1.8
- 2.1.10 (latest)

Number of namespaces: ~400

### First problem

High cpu usage when using plugin `kubernetes_events`, on left without plugin on right with plugin.

CPU Stats
![image](https://github.com/fluent/fluent-bit/assets/140446787/761f3df1-45ad-44ae-933d-d93cb38c90c5)

Memory
![image](https://github.com/fluent/fluent-bit/assets/140446787/e00f567f-9475-465e-8d93-5d8675946e95)

Basic example:

```yaml
    [INPUT]
        name                          kubernetes_events
        tag                           k8s_events
        kube_url                      https://kubernetes.default.svc:443

    [OUTPUT]
        Name                          kafka
        Match                         k8s_events
        Brokers                       kafka:9093
        Topics                        events
        Workers                       3
        rdkafka.compression.codec     gzip
        rdkafka.request.required.acks 1
```

#### #1

When i set `interval_nsec` to `default` from [doc](https://docs.fluentbit.io/manual/pipeline/inputs/kubernetes-events) events are colleceted and **high CPU / Memory usage...**

```yaml
interval_nsec                 500000000
```

#### #2

When i set `interval_nsec` to `10000000000`, events are not collected and **theres no high CPU / Memory usage**

```yaml
interval_nsec                 10000000000
```

#### #3

Wrong default value its not 5 seconds, its 0.5s ?!

![image](https://github.com/fluent/fluent-bit/assets/140446787/b6aa085c-c1cc-4e4d-9f1c-79389808b19c)

![image](https://github.com/fluent/fluent-bit/assets/140446787/8ee29b51-ab4a-4c59-a826-395921a1b040)

#### #4

When i use: `interval_sec   60`  events are not collected and no CPU / Memory high usage

**Comment by mkatana-silkycoders** [comment]
@pwhelan

**Comment by pwhelan** [comment]
It might be better to reconsider increasing the interval to 5 seconds as the default. Initially it was even lower, @edsiper?

**Comment by mkatana-silkycoders** [comment]
reopen
