### ISSUE TITLE
Parser fails to parse properties with inline comments

### ISSUE THREAD

**Issue by Jess-Izen** [fluent/fluent-bit#8140]
## Bug Report

**Describe the bug**
Configuration files currently support new-line comments, but in-line comments seem to break the parser. It fails to parse any property with an in-line comment, with a generic warning: `could not configure property`.

Sent me in circles trying to figure out what I was doing wrong with `mem_buf_limit`, until I came across [this other issue](https://github.com/fluent/fluent-bit/issues/5576) that was closed as stale.

**To Reproduce**
Sample failing config:
```
[INPUT]
    Name exec
    Command curl -s http://127.0.0.1:2020/api/v1/metrics/prometheus
    Interval_Sec 30
    Tag fb_metrics
    Mem_Buf_Limit  5MB  # up to 10MB incl. output buffering
```
which returns: 
`could not configure property 'Mem_Buf_Limit' on input plugin with section name 'exec'`

Whereas this works fine:
```
[INPUT]
    Name exec
    Command curl -s http://127.0.0.1:2020/api/v1/metrics/prometheus
    Interval_Sec 30
    Tag fb_metrics
    # up to 10MB incl. output buffering
    Mem_Buf_Limit  5MB
```

**Expected behavior**
Ideally, support in-line comments. Alternately, provide a clearer error message (even with trace, it's unclear what is going wrong). Or, would be nice to have the restriction documented.

**Your Environment**
Fluent Bit v1.9.10
(running on AL2 / AWS for Fluent Bit Container Image Version 2.31.12.20230911)

**Comment by patrick-stephens** [comment]
1.9 is no longer supported by OSS so is it reproducible on 2.1.10?

**Comment by patrick-stephens** [comment]
Indeed it seems reproducible on latest with `dummy` input:

```shell
$ cat fluent-bit.conf
[INPUT]
  name dummy # test comment
  tag test

[OUTPUT]
  name stdout
  match *
```
Will fail:

```shell
$ docker run --rm -it -v $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro fluent/fluent-bit:2.1.10
Fluent Bit v2.1.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/11/07 15:31:49] [error] [config] section 'dummy # test comment' tried to instance a plugin name that don't exists
[2023/11/07 15:31:49] [error] configuration file contains errors, aborting.
```

**Comment by pwhelan** [comment]
From what I can tell, we do not support inline comments:

https://github.com/fluent/fluent-bit/blob/fca5bf41fa9b849326f6e35cc2d00fdf72635d61/src/config_format/flb_cf_fluentbit.c#L553
```c
        /* Skip commented lines */
        if (buf[0] == '#') {
            continue;
        }

```

And https://github.com/fluent/fluent-bit/blob/fca5bf41fa9b849326f6e35cc2d00fdf72635d61/src/config_format/flb_cf_fluentbit.c#L641
```c
        if (buf[indent_len] == '#' || indent_len == len) {
            continue;
        }
```

There are no other checks for the '#' character in `flb_cf_fluentbit.c`.

**Comment by patrick-stephens** [comment]
Ah, so if it starts with a comment we ignore it entirely otherwise we try to process it as part of the config which then depends on the specific config entry, e.g. is it a single key-value separated by the first space or many of them, etc.

**Comment by patrick-stephens** [comment]
Docs issue initially then, not sure it's feasible to globally support end-of-line comments but we should say we don't for now.
@Jess-Izen could you submit a docs PR?

**Comment by Jess-Izen** [comment]
Sure, is there a section you think this belongs in?
