### ISSUE TITLE
[Output]Why Azure Blob output result have "@timestamp" field?

### ISSUE THREAD

**Issue by peng3693** [fluent/fluent-bit#8146]
## Bug Report

**Describe the bug**
I have two outputs, one is http and one is azure_blob, and azure_blob always has a "@timestamp" field in the output, but I don't have this field in my record. I also tried to remove "@timestamp" using the record_modifier filter, but it didn't work, why did the azure blob output have "@timestamp"?

    [OUTPUT]
        Name  http
        Match *.log
        Host $ingest-endpoint
        Port 443
        HTTP_User $ingest-username
        HTTP_Passwd $ingest-password
        tls true
        tls.verify false
        URI /
        Format json
        Json_date_key @timestamp
        Json_date_format iso8601

    [OUTPUT]
        name                  azure_blob
        match                 *.log
        account_name          $Blobstore-account
        shared_key            $Blobstore-key
        path                  kubernetes
        container_name        logs-separated
        auto_create_container on
        tls                   on
        endpoint              $Blobstore-endpoint

**Current output results:**
{
    "@timestamp": "2023-11-06T13:42:02.672544Z",
    "resource": ...,
    "scopeLogs": ...
}

**Expect the output:**
{
    "resource": ...,
    "scopeLogs": ...
}

**Comment by ak15** [comment]
similar issue faced by me too
