### ISSUE TITLE
tag & tag_regex in tail input not documented

### ISSUE THREAD

**Issue by donbowman** [fluent/fluent-bit#815]
in the tail input, one can indicate a config 'Tag', but also 'Tag_Regex'.
The 'Tag_Regex' seems to have something to do with < and >, but its not obvious what.

https://docs.fluentbit.io/manual/input/tail has no mention.

It looks like its intended to be:

```
[INPUT]
    Name             tail
    Path             log/*.log
    Parser           docker_no_time
    Tag              kube.<namespace_name>.<pod_name>.<container_name>
    Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On
```

And then we end up with tags like:

'kube.NAMESPACE.PODNAME.CONTAINER', which is much more convenient to use in e.g. Filter

**Comment by donbowman** [comment]
OK, if I do this:

```
[INPUT]
    Name             tail
    Path             log/*
    Parser           docker_no_time
    Tag              kube.<namespace_name>.<pod_name>.<container_name>
    Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
    Refresh_Interval 5
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Regex_Parser        kube-custom
    Merge_JSON_Log      On
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On

[PARSER]
    Name    kube-custom
    Format  regex
#    Regex   (?<tag>[^.]+)?\.?(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
    Regex    (?<kube>[^.]+)\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)

```

then the tag is fetched out by tail as: `kube.namespace.pod.container`

which allows routing by any of the 3 levels of coordinates in match syntax. In turn, this would allow adding e.g. a parser per field per container if needed.

**Comment by donbowman** [comment]
Resolved with https://github.com/fluent/fluent-bit-docs/commit/38f70c9544bf42e3e7fcd9e355b7ca36e010e984

**Comment by knopka** [comment]
Hi @donbowman
are 'Tag' and 'Tag_Regex' in tail input plugin useful and available for Kuberntes filter plugin only?

**Comment by donbowman** [comment]
https://regex101.com/

give your suggested pattern a try there.
i'm not sure what your tag is coming from, but its not the file name put out by the CRI.

try
```
(?<kube>[^.]+)\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)
```

**Comment by Voolodimer** [comment]
@donbowman At the beginning my log-file looks like "/var/log/containers/kubia-vl7dk_default_kubia-904a37e56f2a6363d523621bbe4dd099fef7eb17e2c92ed97637b58e516b7341.log"

after the [INPUT] block, the tag turns into "Tag kube.<namespace_name>.<container_name>.<pod_name>" -> kube.default.fluent-bit.my-fluent-bit-lk4h9 (it's correct)

I checked this expression (?<kube>[^.]+)\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+), it works fine.

At the end I want to get enriched data

This is my test config: 

`
data:
  custom_parsers.conf: |
    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name kube-custom
        Format regex
        #Regex (?<tag>[^.]+)?\.?(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Regex (?<kube>[^.]+)\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        #Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name tail
        Path /var/log/containers/kubia-vl7dk*.log
        Parser cri
        Tag kube.<namespace_name>.<container_name>.<pod_name>
        Tag_Regex (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
        Refresh_Interval 8
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [FILTER]
        Name kubernetes
        Match kube.*
        Regex_Parser kube-custom
        Merge_Log On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name stdout
        Match *
`

**Comment by raghibomar786** [comment]
Hey @donbowman , I'm trying to read logs from /var/log/containers and write to a file at path /output/path. I want to create subfolders for each container at this path, so I tried:

```
[OUTPUT]
        Name file
        Match kube.*
        Path /output/path/${tag_parts[3]}/${tag_parts[2]}.log
        Mkdir True
```
Given my tag is of the form : kube.<namespace_name>.<pod_name>.<container_name> (which I'm getting correctly), but this doesn't work. I've tried using `/output/path/${container_name}`, `/output/path/${tag.container_name}`, `/output/path/${tag['container_name']}` but nothing seems to work. How can I extract the container name from tag into my output path?
