### ISSUE TITLE
Using JSON parser when Time_Key is integer

### ISSUE THREAD

**Issue by daljitsharma** [fluent/fluent-bit#8154]
## Bug Report

**Describe the bug**
When using the [JSON parser](https://docs.fluentbit.io/manual/pipeline/parsers/json) to set the time, it does not seem to work as expected if the Time_Key is an integer. The time key could be an integer if the time is given in Epoch. 

**To Reproduce**
- Example log message:
```
{"log": "{ \"msg\":\"blah\" , \"time\":1699549828 }", "container_id": "test"}
```
- Steps to reproduce the problem:
Using parser file:
```
[PARSER]
    Name        json
    Time_Key    time
    Time_Format %s
    Format      json
```
And config:
```
[SERVICE]
    flush           1
    log_level       info
    parsers_file    /fluent-bit/etc/custom-parser.conf

[INPUT]
    Name dummy
    Dummy {"log": "{ \"msg\":\"blah\" , \"time\":1699558262 }", "container_id": "test"}

# This works fine since time is string
#[INPUT]
#   Name dummy
#    Dummy {"log": "{ \"msg\":\"blah\" , \"time\":\"1699558262\" }", "container_id": "test"}

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser json
    Reserve_Data True

[OUTPUT]
    Name                es
    Match               *
    AWS_Region          ${AWS_REGION}
    AWS_Auth            On
    AWS_Role_ARN        ${AWS_ROLE_ARN}
    Host                ${OPENSEARCH_HOST}
    Port                ${OPENSEARCH_PORT}
    TLS                 On
    Retry_Limit         6
    Replace_Dots        On
    Logstash_Format     On
    Logstash_DateFormat %Y-%m-%d
    logstash_Prefix     ${LOGSTASH_PREFIX}
    Suppress_Type_Name  On
```

**Expected behavior**

I would expect this to work regardless of if the time field is string or number or documentation saying the field just be in string form.

**Your Environment**

* Version used: Fluent bit 1.9.10

**Comment by patrick-stephens** [comment]
1.9 is no longer supported, is it reproducible on latest (2.2.0)?

**Comment by nokute78** [comment]
I can reproduce using [current master](https://github.com/fluent/fluent-bit/tree/281aea0a10a11db25529f248551ed5c2eab40223)

I sent a patch.
https://github.com/fluent/fluent-bit/pull/8160
