### ISSUE TITLE
Grok patterns parser plugin support

### ISSUE THREAD

**Issue by antonionappi88** [fluent/fluent-bit#8166]
**Is your feature request related to a problem? Please describe.**
We are currently running fluentd as sidecar container to ship logs outside Kubernetes Clusters. We intensively use GROK patterns to parse logs.
**Describe the solution you'd like**
We would like fluent bit to support GROK patterns as well

We found the https://github.com/fluent/fluent-bit/issues/723 issue mentioning the same but it was closed.

I was wondering if there is any possibility to have it.

Thank you,
Antonio

**Comment by brunooliveiramac** [comment]
let do it, upvote

**Comment by AdaptiveStep** [comment]
Can't we just use this in a lua filter?
https://github.com/dscoshpe/lpeg-grok/blob/master/grok.lua

**Comment by agup006** [comment]
Will be great to get a contribution for this, @brunooliveiramac @antonionappi88 @AdaptiveStep is this something you would be able to contribute?

**Comment by amine250** [comment]
This would be a huge deal. 

Fluentd is not as maintained as it used to be, but we're stuck using it because of Grok parsing.

**Comment by amine250** [comment]
To remove stale label

**Comment by evnct** [comment]
Automatically stalling issues is lazy and rather idiotic. Remove the Stale label.

**Comment by benbenik** [comment]
I am confused: is this feature request auto-stale and therefor "Closed as not planned" automatically? Or is this actively considered as not to implement by the development team? Seeing the love given to this post and the abundance of readily available GROK filters I wonder why GROK is not included by default in Fluent-bit? Resolving to writing/converting to regular expressions is not productive, nor does it make the resulting regex easier to read or maintain. Besides reading other good arguments of fellow postrers. Please consider the unmet need of users seen in this and other GROK posts. I also think that closing or making every GROK issue auto-stale is burying an unmet need, like issues https://github.com/fluent/fluent-bit/issues/723 and https://github.com/fluent/fluent-bit/issues/8788

**Comment by amine250** [comment]
@benbenik I came to a conviction that this is how open source software works.

We’re never getting this feature unless forked by some company that will put it behind a paywall.
