### ISSUE TITLE
Duplicate logs being sent to Stackdriver

### ISSUE THREAD

**Issue by aliabbasrizvi** [fluent/fluent-bit#8175]
## Bug Report

**Describe the bug**
Duplicate log messages are being sent to Stackdriver from our ECS container

**To Reproduce**
Our `fluent.conf` file looks like

```
[SERVICE]
    parsers_file parsers.conf

[FILTER]
    Name         parser
    Parser       docker
    Match        *
    Key_Name     log
    Reserve_Data On

[OUTPUT]
    Name         stackdriver
    Match        *
    severity_key severity

[OUTPUT]
    Name  stdout
    Match *
```

`parsers.conf` looks like

```
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %s.%L
    Time_Keep    On
    # Command       |  Decoder       | Field | Optional Action   |
    # ==============|================|=======|===================|
    Decode_Field_As    json            log     try_next
    Decode_Field_As    escaped_utf8    log
```

For our ECS container log driver is `awsfirelens` and it is configured to forward to `stackdriver`

**Expected behavior**
Our goal is to have logs in Cloudwatch as well as in Stackdriver. But what we are seeing is that each log message is logged twice in Stackdriver.

Looking for guidance on how to resolve this

* Version used: 2.1.5
* Configuration: Shared `fluent.conf` and `parsers.conf` above
* Environment name and version (e.g. Kubernetes? What version?): ECS

**Comment by patrick-stephens** [comment]
Is it reproducible with a more recent version, e.g. 2.2.0?

**Comment by aliabbasrizvi** [comment]
This turned out to be a non-issue since I had log configuration on AWS container also set to send to Stackdriver. As a result additional logs were coming from there. Closing this issue.
