### ISSUE TITLE
Wrong documentation for buffer size - Elasticsearch output plugin

### ISSUE THREAD

**Issue by bm-skutzke** [fluent/fluent-bit#8178]
## Bug Report

**Describe the bug**
Sometimes we observed following message in Fluent Bit's logs:
```
[2023/11/10 11:36:49] [ warn] [http_client] cannot increase buffer: current=512000 requested=544768 max=512000
```

The documentation says that the default value for `Buffer_Size` is `4KB`:
https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

This is not true since it is 512kb (= 512000 bytes) when looking at the source code:
`#define FLB_ES_DEFAULT_HTTP_MAX   "512k"`
(https://github.com/fluent/fluent-bit/blob/master/plugins/out_es/es.h, L32)

**Your Environment**
* Version used: 2.2.0

**Comment by patrick-stephens** [comment]
Thanks, can you submit a PR to update the docs?
https://github.com/fluent/fluent-bit-docs

**Comment by patrick-stephens** [comment]
The actual value reported by `--help` is correct at least:

```shell
$ docker run --rm -it fluent/fluent-bit:2.2.0 -o es --help
...
buffer_size                    Specify the buffer size used to read the response from the
                               Elasticsearch HTTP service. This option is useful for
                               debugging purposes where is required to read full
                               responses, note that response size grows depending of the
                               number of records inserted. To set an unlimited amount of
                               memory set this value to 'false', otherwise the value must
                               be according to the Unit Size specification
                               > default: 512k, type: size
```

**Comment by bm-skutzke** [comment]
PR: https://github.com/fluent/fluent-bit-docs/pull/1258
