### ISSUE TITLE
http output logstash error

### ISSUE THREAD

**Issue by tmxkaos112** [fluent/fluent-bit#8181]
I looked at https://docs.fluentbit.io/tutorials/ship_to/logstash and followed it, but I got an error. Can you tell me why?

[2023/11/15 05:56:25] [error] [http_client] broken connection to 1.23.456.189:12345 ?
[2023/11/15 05:56:25] [error] [output:http:http.0] could not flush records to 1.23.456.189:12345 (http_do=-1)
[2023/11/15 05:56:25] [ warn] [engine] failed to flush chunk '1-1700027754.562770377.flb', retry in 7 seconds: task_id=0, input=tail.0 > output=http.0 (out_id=0)

my fleunt bit conf

[SERVICE]
   Parsers_File /fluent-bit/etc/parsers.conf
   Flush        1
   Log_Level    info
   Daemon       off

[INPUT]
   Name         tail
   Path         /fluent-bit/log/s/*.log
   Tag          test-search-index-dev
   Refresh_Interval  5
   Buffer_Chunk_Size 32k
   Buffer_Max_Size   1m
   Skip_Long_Lines   Off
   Multiline On
   Parser_Firstline multiline

[OUTPUT]
   Name   http
   Match  test-search-index-dev
   Host    1.23.456.189
   Port   12345
   Format json_lines

[OUTPUT]
   Name   stdout
   Match  test-search-index-dev
   Format json_lines

logstash conf

input {
  http {
    port               => 12345
    add_field          => { "[@metadata][input-http]" => "" }
    codec => json_lines
  }
}

filter {
  if [@metadata][input-http] {
    date {
      match => [ "date", "UNIX" ]
      remove_field => [ "date" ]
    }
    mutate {
      remove_field => ["headers","host"]
    }
  }
}

output {
  stdout {
      codec => rubydebug
  }
  if "test-search-index-dev" in [tags] {
    file {
        path => "/tmp/my_logstash.log"
        codec => rubydebug
    }
  }
}

my log data sample

{"date":1700027754.56299,"message":"{\n  \"hostname\" : \"local\",\n  \"serverTimestamp\" : \"2023-11-15T14:55:53.431\"}"}

**Comment by patrick-stephens** [comment]
It fails to write to the output destination - could be lots of things, e.g. TLS, invalid port/hostname, etc.

**Comment by tmxkaos112** [comment]
@patrick-stephens I tried again and succeeded because the inbound rule was there.
thank you for your reply
