### ISSUE TITLE
out_loki setting incorrect X-Scope-OrgID header with multiple loki outputs

### ISSUE THREAD

**Issue by sedan07** [fluent/fluent-bit#8191]
## Bug Report

**Describe the bug**
When setting up two Loki outputs with separate routing configuration, one using a hardcoded `tenant_id` and the other using a `tenant_id_key` the `X-Scope-OrgID` header is set incorrectly for messages matching the first Loki output. 

It seems to work okay if all messages only match the first output. But once a log message matches the second output the `tenant_id` remains at the value set dynamically by the `tenant_id_key` for BOTH outputs, so messages with the hardcoded `tenant_id` actually use the dynamically set `tenant_id`. Fluent Bit metrics suggest the routing is working and the messages are correctly going to the first Loki output but then getting sent with the wrong `X-Scope-OrgID` value.

**To Reproduce**

In the following scenario 60 messages a minute should go into Loki under OrgID: `tenant1` and another 60 under the dynamically set `tenant2`

```
[SERVICE]
    flush     1
    log_level info

[INPUT]
    name      dummy
    dummy     {"key": 1, "sub": {"stream": "stdout", "id": "some id"}, "kubernetes": {"labels": {"team": "Santiago Wanderers"}}}
    Tag       app

[INPUT]
    name      dummy
    dummy     {"key": 2, "sub": {"stream": "stdout", "id": "new id"}, "kubernetes": {"labels": {"team": "Deportes Temuco", "org-id": "tenant2"}}}
    Tag       infra

[OUTPUT]
    name                   loki
    match                  app
    host                   gateway
    port                   3100
    labels                 job=fluentbit
    label_keys             $sub['stream']
    tenant_id              tenant1
    auto_kubernetes_labels on

[OUTPUT]
    name                   loki
    match                  infra
    host                   gateway
    port                   3100
    labels                 job=fluentbit
    label_keys             $sub['stream']
    tenant_id_key          $kubernetes['labels']['org-id']
    auto_kubernetes_labels on
```

**Expected behavior**
Logs tagged to match output 0 should use the hardcoded `tenant_id` and ones matching the output 1 matcher should use the value of the key specified by the `tenant_id_key` field.

**Screenshots**
Tenant1
![tenant1](https://github.com/fluent/fluent-bit/assets/1449113/bd63407b-06ca-4170-93ce-4ca50f5271e7)

Tenant2 (Used a hardcoded `tenant_id` until 11:22 then used the above config with `tenant_id_key`)
![tenant2](https://github.com/fluent/fluent-bit/assets/1449113/742fe25c-2a25-4570-bb48-d5633d9089b4)

**Your Environment**
* Version used: 2.1.10 - Couldn't try 2.2.0 as the Loki output [appears broken](https://github.com/fluent/fluent-bit/issues/8184)
* Configuration: in_tail -> filter_kubernetes -> filter_rewrite_tag -> out_loki
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.24
* Server type and version: AWS EC2
* Operating System and version: Bottlerocket v1.16.1
* Filters and plugins: 

**Additional context**
I was trying to allow workloads to optionally define a different Loki OrgID through a pod label for their logs to go into, whilst keeping logs from other workloads just going into the default Loki OrgID.

Might be related to: https://github.com/fluent/fluent-bit/issues/6911

**Comment by patrick-stephens** [comment]
I wonder if `tenant_id_key` should reference the key not the value (does it support record-accessor syntax as well)?
```
tenant_id_key          key
```
Or in your case, I'm not sure if nested keys can be done like this:
```
tenant_id_key          kubernetes.labels.org-id
```
Plus what happens if the key is missing? It probably should have a filter before it to enforce a key and/or create a dedicated one.

**Comment by sedan07** [comment]
@patrick-stephens thanks for you suggestions.
You're probably right the `tenant_id_key` should probably reference the key name (doh!). However interestingly enough that doesn't fix it.
Using:
```
tenant_id_key          kubernetes.labels.org-id
```
Results in:
```
[ warn] [output:loki:loki.1] the value of kubernetes.labels.org-id is missing
```
Possibly because nested keys aren't supported.
using:
```
tenant_id_key          kubernetes['labels']['org-id']
```
same:
```
[ warn] [output:loki:loki.1] the value of kubernetes['labels']['org-id'] is missing
```

If I modify my example and add a `org_id` top level field that's correctly picked up. But, it's still very keen to send all the logs using that `tenant_id` regardless of the routing and hardcoded `tenant_id` on `loki.0`. I would also like to know how it even picked up the "tenant2" value before, as it wasn't an existing key so how did it look it up...

**Comment by patrick-stephens** [comment]
Sure, I think the issue then is a feature request for record accessor support for that configuration setting. As you say, it supports a key but just not a nested one.

Personally I would probably want to dedicate a key for it then use a LUA or similar filter to default that value if not found, e.g. when labels not set, otherwise you also have to build that defaulting capability into the Loki output and everyone will want something different so using an explicit filter to do what you want makes more sense.

**Comment by sedan07** [comment]
But even with using a dedicated key it still doesn't work as expected as the output with the `tenant_id` hardcoded uses the last value set by the `tenant_id_key` on the other loki output. Which if it is a "feature" seems a very strange one and should at least be documented. But in my mind it seems like a bug. The two outputs should act independently, which seems to be the case with other outputs. 

Using a lua filter would certainly work to set a top level key but seems overkill for such a trivial action and introduces a small performance hit. But yes, supporting nested keys is a feature request (although the docs don't state either way what's supported, so maybe it's meant to already support it?!)

**Comment by sedan07** [comment]
I guess I'm misunderstanding how the `tenant_id_key` field is meant to be used. I took it to mean: set the `X-Scope-OrgID` header based on the value of a specified key in the current log message. But it doesn't seem to expect to get changed, as every time it's changed it [logs a warning](https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/out_loki/loki.c#L1152). What is the expected use case for this field? How should it be used?

Even if it isn't meant to be be using record accessors it appears to [call the function](https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/out_loki/loki.c#L1117) to get the record accessor value. And using the record accessor syntax with brackets does work. As in it reads the value for each log message, logging a warning on every change. Does `flb_ra_get_value_object` support record accessor syntax?

But the bug appears to be that the `dynamic_tenant_id` variable is shared between all instances of the loki plugin which means as soon as it's set, ALL instances of the plugin [ignore the non-dynamically defined `tenant_id`](https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/out_loki/loki.c#L1623) and use the last `dynamic_tenant_id` value. I believe I'm correct in saying: Fluent Bit supports multiple outputs, and these can be of the same type or different... true? If this is true then the way the `tenant_id_key` field is currently handled breaks that.

**Comment by cosmo0920** [comment]
I understand what this ticket means.



> I guess I'm misunderstanding how the `tenant_id_key` field is meant to be used. I took it to mean: set the `X-Scope-OrgID` header based on the value of a specified key in the current log message. But it doesn't seem to expect to get changed, as every time it's changed it [logs a warning](https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/out_loki/loki.c#L1152). What is the expected use case for this field? How should it be used?

Yes. If you specify `tenant_id_key` field, it's effective for the all cases even if `tenant_id` is specified in the configuration.

This is because the `X-Scope-OrgID` is handled by these lines:
https://github.com/fluent/fluent-bit/blob/v2.1.10/plugins/out_loki/loki.c#L1617-L1627

Do you know the ideal behavior for this case? `tenant_id` parameter should be prioritized?
