### ISSUE TITLE
Converting part of record to json string

### ISSUE THREAD

**Issue by MrKich** [fluent/fluent-bit#8193]
**Is your feature request related to a problem? Please describe.**
I could not find a feature to simply convert part of parsed record back to json.
Typical usage for me is when I need to parse deep nested json, extract (lift) and rename some deep fields in it and then return part of parsed record as string.

E.g. using zalando logbook (java spring) can produce json logs, which after parsing look like this:
```
{
  "origin": "remote",
  "type": "request",
  "correlation": "2d66e4bc-9a0d-11e5-a84c-1f39510f0d6b",
  "protocol": "HTTP/1.1",
  "sender": "127.0.0.1",
  "method": "GET",
  "uri": "http://example.org/test",
  "host": "example.org",
  "path": "/test",
  "scheme": "http",
  "port": null,
  "headers": {
    "Accept": ["application/json"],
    "Content-Type": ["application/json"]
  },
  "body": {"test": [1,2,3]}
}
```

I want to change 'body' value from object to string (e.g. `"body": "{\"test\": [1,2,3]}"` ). 

**Describe the solution you'd like**
I think it is possible to implement a new 'config_parameter' for filter 'type-converter' to encode record type as json string or may be just another new filter.

**Describe alternatives you've considered**
I tried to use lua to convert records to json strings, but it implies using an external lua library for that, which is not handy and simple.

**Comment by nokute78** [comment]
I sent a patch https://github.com/fluent/fluent-bit/pull/8200
Could you check it ?

**Comment by MrKich** [comment]
I really appreciate how quickly a patch was made.
I checked it - it works and it solves my problem, thank you.

A few suggestions I could think of:
1. I don't think that adding extra `dst_data_type` with `json_string` is necessary, just `string` seems enough.
2. It would be awesome if converter supported not only map (for `map_key`) but other json types as well - int, float, boolean, array, null, string, because parsed json is not always a json object and it would be useful to omit extra typechecking.
Right now I gonna make typechecking with lua.

**Comment by nokute78** [comment]
Thank you for testing and comment.

> just string seems enough

In the future, some user may request to support another structured format like LTSV.
So I designed to explicitly specify the format.

> It would be awesome if converter supported not only map (for map_key) but other json types as well

I don't think it is a feature of filter_type_converter plugin.
The plugin is a type sensitive and it means the type of value should be fixed.

I also think the Lua plugin would be more appropriate for your use case.
