### ISSUE TITLE
Potential log loss during high load at Multiline & Rewrite Tag Filter (in_emitter)

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-bit#8198]
## Bug Report

**Describe the bug**
When logs from multiple input sources (especially those using tail with wildcard) pass through a single `Multiline Filter`, it can lead to congestion at the `in_emitter`. This congestion potentially causes the loss of logs from all involved input sources. Additionally, if one overly active input source fills the in_emitter buffer, it can affect all other inputs as well.

The following logs can be seen when the issue happens: 
```
...
[2023/11/17 14:14:54] [ info] [filter:multiline:multiline.0] created new multiline stream for dummy.57_dummy_logs
[2023/11/17 14:14:54] [ info] [filter:multiline:multiline.0] created new multiline stream for dummy.58_dummy_logs
[2023/11/17 14:14:54] [ info] [filter:multiline:multiline.0] created new multiline stream for dummy.59_dummy_logs
[2023/11/17 14:14:55] [ warn] [input] emitter.59 paused (mem buf overlimit)
[2023/11/17 14:14:55] [error] [input:emitter:emitter_for_multiline.0] error registering chunk with tag: dummy_logs
[2023/11/17 14:14:55] [error] [input:emitter:emitter_for_multiline.0] error registering chunk with tag: dummy_logs
[2023/11/17 14:14:55] [error] [input:emitter:emitter_for_multiline.0] error registering chunk with tag: dummy_logs
[2023/11/17 14:14:55] [error] [input:emitter:emitter_for_multiline.0] error registering chunk with tag: dummy_logs
...
```
The whole chunk (from potentially all involved sources) will be dropped here: https://github.com/fluent/fluent-bit/blob/9b9c800d76f6310ab0241b253a783ea6283dff2c/plugins/in_emitter/emitter.c#L94-L97

**To Reproduce**
- Use following config: https://gist.github.com/drbugfinder-work/6e5afb5f6a9982a9ff8d6bb5168e5d88
- Wait until multiline buffer is filled (should happen immediately with the given configuration)
- Check in_emitter memory consumption with: `curl http://127.0.0.1:2020/api/v1/storage | jq`

**Expected behavior**
- The input plugin should pause correctly
- There should be no log loss, particularly logs from other involved input sources (in the case of tail with file wildcard).

**Your Environment**
* Version used: 2.2.0
* Configuration: https://gist.github.com/drbugfinder-work/6e5afb5f6a9982a9ff8d6bb5168e5d88

**Additional context**
- Especially in environments like K8s it not predictable how many pod logs will be matched by a wildcard tail plugin. 
- The provided configuration file creates high load and features an artificially high number of inputs. However, same behavior occurs in real environments with slightly fewer inputs (few tail input with wildcard) but larger messages. Hence, this represents a genuine configuration scenario.

**Comment by drbugfinder-work** [comment]
cc @agup006

**Comment by nokute78** [comment]
@drbugfinder-work Could you check Buffering & Storage documentation ?
https://docs.fluentbit.io/manual/administration/buffering-and-storage

Following log means touching memory limit of in_emitter.
in_emitter uses 10MB memory as a buffer by default.
```
[2023/11/17 14:14:55] [ warn] [input] emitter.59 paused (mem buf overlimit)
```

I believe that one of these methods could be a solution.

1. Increasing mem_buf_limit
2. Using filesystem buffer

## 1. Increasing mem_buf_limit

Multiline filter supports `emitter_mem_buf_limit` to change the size of buffer of in_emitter.

## 2. Using filesystem buffer

Multiline filter supports `emitter_storage.type` to use filesystem buffering.

https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace#configuration-parameters

**Comment by drbugfinder-work** [comment]
Hi @nokute78,

Certainly, that's indeed the situation. I'm aware of that. As previously discussed with @agup006, it might be beneficial to implement a signaling mechanism to halt the input. This could mirror the conventional output feedback method that pauses the inputs.

The issue here is that one cannot always estimate the required buffer space accurately. In typical pipelines (unlike the in_emitter), the input is typically paused when the buffer limit is reached without dropping logs within the pipeline.

**Comment by nokute78** [comment]
Pausing a plugin means that previous plugin/source needs pausing/dropping input.
In this case it is to pause in_dummy plugin.

On the other hand, how should we do if the input plugin is in_http ? Should we return 503? Can http client waiting and buffering ?

**Comment by drbugfinder-work** [comment]
@nokute78

In most of our pipelines we use tail input plugins. Normally, these tail inputs pause when the output plugin (e.g. forward) buffers reach capacity (for instance, when the target is unreachable).
However, when a multiline plugin is introduced into the pipeline, its behavior diverges unexpectedly. It starts behaving as two distinct pipelines, interconnected by a loopback at the conclusion of the first one, feeding into the in_emitter input of the second.
Consequently, if the output buffers of the latter half of the pipeline become full, the inputs from the first half of the pipeline should ideally pause. However, in the current scenario, only the in_emitter of the second half is halted, while the primary inputs persist uninterrupted. 
The tail input plugins continue to ingest further messages and these will be dropped immediately (see code in initial text) at the multiline_filter/in_emitter. This behavior is problematic, especially when relying on a database for the tail inputs, as the dropping of records within the pipeline deviates from the expected functionality.

To address this, it seems more appropriate for the primary inputs to pause in a pipeline using a multiline filter plugin, rather than just halting a specific segment. This adjustment would maintain data integrity and prevent the loss of crucial information within the pipeline process.

**Comment by nokute78** [comment]
filter_multiline has an unique buffer and it can store a huge records that cause pausing input plugin.
If the input plugin is in_tail, could you test `buffer false` for filter_multiline ?
https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace

**Comment by vfcastro** [comment]
Having a pretty similiar issue of losing logs during high load here. The diference is that in our case we don't even see the error messages in fluent-bit logs. We're setting cpu requests/limits for fluent-bit pods (100 milicores). As soon as an Java application starts logging like a hundred stacktraces per sec, fluent-bit pod gets overwhelmed (cpu throttling) and the logs processing stops at all, simply dropping the logs. 

We tried disabling buffer, setting filesystem buffer, tweaking emitter_mem_buf_limit, without success. By disabling the multiline filter we get the same amount of log lines processed without issues. One can argue that setting cpu requets/limits higher could solve the issue (we tried, but it just took a little bit longer for the issue arise), but in our understanding, we should be able to limit the cpu usage for fluent-bit and still having it functional, even then with a reduced performance.

**Comment by drbugfinder-work** [comment]
Upon retesting with the tail input plugin and disabling buffering specifically for the filter_multiline, the issue seems to shift from the multiline plugin to the preceding rewrite_tag plugin in some of our pipelines where we use this combination. This is noteworthy as the rewrite_tag plugin also internally uses the in_emitter, thereby encountering similar pausing issues.
Furthermore, even in the reproducer scenario that utilizes dummy inputs, not tail inputs, the problem persists. 

In essence, it appears to be more than just an issue confined to the multiline plugin; rather, it seems to be a broader challenge related to the signaling of pause within the in_emitter, impacting both multiline and rewrite_tag modules. This holds true irrespective of the input plugin in use.

**Comment by drbugfinder-work** [comment]
Fixed in #8473

**Comment by Cajga** [comment]
I was soo, happy to see this issue and see the message with "Fixed in #8473"... then back to step one as the PR is not merged yet :/
In any case, thanks a lot @drbugfinder-work and @nokute78 to work on this!!!

**Comment by asymmetric** [comment]
> When logs from multiple input sources (especially those using tail with wildcard) pass through a single Multiline Filter, it can lead to congestion at the in_emitter. This congestion potentially causes the loss of logs from all involved input sources. Additionally, if one overly active input source fills the in_emitter buffer, it can affect all other inputs as well.

Just to clarify, I think log loss can happen also when there's only one, very noisy input -- it's not necessary for more than one input to be involved.

**Comment by drbugfinder-work** [comment]
Fixed https://github.com/fluent/fluent-bit/pull/8473
