### ISSUE TITLE
in_serial: Support JSON Format

### ISSUE THREAD

**Issue by toru-takahashi** [fluent/fluent-bit#82]
in_serial plugin read a stream of bytes, so the only thing is that user need to specify a delimiter string so the plugin can know when a message ends and a new one begins.
But, adding delimiter to JSON format is not suitable.

The request is that in_serial supports JSON Format.

**Comment by edsiper** [comment]
The serial_json branch contains the implementation of this requested feature. As described in the https://github.com/fluent/fluent-bit/commit/7d4700e396f88377e41e1fb4efe05bc6a6567992 commit, there is an issue in the used lib/jsmn library when some bad formed JSON message is received. 

The following issue have been logged with jsmn team:

zserge/jsmn#81

note: functional but still under development

**Comment by edsiper** [comment]
in_serial is an already merged feature. Closing this issue and opening a new one #117 to track jsmn updates
