### ISSUE TITLE
rewrite_tag "could not compose tag" with dash in tag name

### ISSUE THREAD

**Issue by etesyolk80** [fluent/fluent-bit#8203]
## Bug Report

**Describe the bug**
I have been trying to utilize tags to send the logs to the files equal to the new tag and used the dash for the file name
Unfortunately received the below error:

[error] [record accessor] syntax error, unexpected '$', expecting $end at '$ct-$zhenya'
[error] [filter:rewrite_tag:rewrite_tag.0] could not compose tag: $ct-$zhenya.log
[error] Failed initialize filter rewrite_tag.0
[error] [engine] filter initialization failed
[error] [lib] backend failed

**Expected behavior**
no error when rewriting tag contains dahes 

**Your Environment**
Configuration used:

```
[INPUT]
    NAME   dummy
    Dummy  {"ts": "zhenya", "ct": "zhenya", "zhenya": "tesyolkin"}
    Tag    test_tag

[FILTER]
    Name          rewrite_tag
    Match         test_tag
    Rule          $ts ^(zhenya)$  $ct-$zhenya.log false
    Emitter_Name  re_emitted


[OUTPUT]
    name  file
    match *
    Path  /root/zhenya
```
                                                     
 
* Version used: 2.2.0
* Operating System and version: Ubuntu 20.04

**Comment by etesyolk80** [comment]
> I think this has been a restriction for a while, my guess is you want the tag to specify the filename and it must have a dash in it?
> 
> A workaround would be to just create a separate key first (e.g. with LUA) with the value including the dash then specify that key directly (no need for dash now) and optionally drop the key afterwards.

Yes, exactly. My filename should contain a dash. 
It's weird that I can use a "." or even "," , but not the "-" (it should be supported by the docs )
Was able to implement it with LUA, thanks.

**Comment by patrick-stephens** [comment]
It would be good if you could submit a docs PR to help others: https://github.com/fluent/fluent-bit-docs/blob/master/pipeline/filters/rewrite-tag.md

I'm not sure if this is a limitation of the record-accessor syntax or just specific to this particular plugin.
