### ISSUE TITLE
Is it possible to write a custom plugin in go?

### ISSUE THREAD

**Issue by abhi-jha** [fluent/fluent-bit#8204]
I need to add a custom header in the log ingestion request. 

Now I have found an example : https://devcodef1.com/news/1017567/custom-http-headers-in-fluentbit-plugin

But it is in C which is making it a bit harder to compile. 

I see the docs mentioning some plugins that can be written in go : https://docs.fluentbit.io/manual/development/golang-output-plugins

Can the above C code be compiled in go and then made available to load at runtime?

**Comment by patrick-stephens** [comment]
Why not just specify custom headers in the output itself? https://docs.fluentbit.io/manual/pipeline/outputs/http

**Comment by patrick-stephens** [comment]
Separately Golang output plugins are pretty straightforward now so you can just write it all directly in Golang, I'm not sure why you want to translate the C code as that is primarily using library functions but Golang already has its own well specified and standard http support.

https://github.com/calyptia/plugin

**Comment by abhi-jha** [comment]
Well our issue is a bit specific. We have to do auth before flsuhing logs. That depends on a header. We can get the header from a remote server and then inject that header in the in the output plugin request. 

I guess this needs a custom plugin, right? I can grab something from a server and inject in the output plugin header.

**Comment by patrick-stephens** [comment]
No idea, you can potentially inject the header somehow into the config but if it's dynamic then yeah probably something dedicated for it. A simple Golang output plugin is straightforward if you follow the example and then you can add in whatever you need for it, e.g. talk to the other thing.

**Comment by sgarc57** [comment]
If there is just a need to create a wrapper for an existing plugin (to add a specific header), is there an easy way to do that, or would we have to implement all the methods in the original plugin written in c?

**Comment by sgarc57** [comment]
yes, so for example in this case, where the result of a function call needs to be added as a header, would it be possible to do that as a custom header, or is there the requirement to build a plugin?

**Comment by patrick-stephens** [comment]
I don't think there is any OSS method to inject function call results into any plugin via configuration other than by using something like a LUA or WASM filter to inject the result as a value for a specific key then reference that key in the output plugin to use it. 

In this case, I'm not sure if custom headers supports record-accessor syntax (to look up the value of another field) but it may be worth a quick check and/or feature request.

Commercially we have some additional Enterprise plugins that do a lot of things in this vein (e.g. scraping custom APIs and/or templating requests/responses via config) so rather than reinvent things or implement your own plugin it may be worth engaging directly but I'm not trying to shill anything here :)

**Comment by sgarc57** [comment]
If I understand your suggestion, then it means there is the possibility to specify an additional header key to add via a filter, and also some lua code to for example make an http request and return the result as the value.

**Comment by patrick-stephens** [comment]
Record accessor syntax is the way to look up values in specific fields: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

This however depends on the specific option/plugin supporting that for the particular configuration you want to do - I'm not sure if the current HTTP custom header configuration option supports this but it potentially could.

So yeah, assuming it did support it, then you just need another filter to inject the value to use.

**Comment by abhi-jha** [comment]
I am having hard time visualing this. Is there an example for this?
