### ISSUE TITLE
TCP INPUT - not sending logs using the logback tcp appender to Fluent Bit due to connection closed right after open connection

### ISSUE THREAD

**Issue by AntonioJoaoSchwartzSoares** [fluent/fluent-bit#8211]
## Bug Report

**Describe the bug**

We are trying to send logs to Fluent Bit using the TCP input Plugin using logback SocketAppender under a Java application. For some reason the connection is stablished and closed immediately.

```
[2023/11/24 09:59:09] [trace] [input:tcp:tcp.0 at /tmp/fluent-bit-20230928-4986-g81p0w/fluent-bit-2.1.10/plugins/in_tcp/tcp.c:50] **new TCP connection arrived FD=62**
[2023/11/24 09:59:09] [trace] [input:tcp:tcp.0 at /tmp/fluent-bit-20230928-4986-g81p0w/fluent-bit-2.1.10/plugins/in_tcp/tcp_conn.c:261] read()=4 pre_len=0 now_len=4
[2023/11/24 09:59:09] [ warn] [input:tcp:tcp.0] invalid JSON message, skipping
[2023/11/24 09:59:09] [trace] [input:tcp:tcp.0 at /tmp/fluent-bit-20230928-4986-g81p0w/fluent-bit-2.1.10/plugins/in_tcp/tcp_conn.c:255] f**d=62 closed connection**
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:
1- configure the pom file in the  application to add the logback dependency:
```xml
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
</dependency>
```

2- Configure the logback-spring.xml to add the appenders

```xml
<configuration>
    <appender name="FLUENTBIT" class="ch.qos.logback.classic.net.SocketAppender">
        <remoteHost>localhost</remoteHost>
        <port>24224</port> 
    </appender>

    <root level="INFO">
        <appender-ref ref="FLUENTBIT" />
    </root>
</configuration>
```

Change the application to use the logger to initialize Logback:

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    private static final Logger logger = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        // Resto do seu código...

        // Exemplo de uso do logger
        logger.info("Mensagem de log para o Fluent Bit");
    }
}
```

Add a INPUT plugin configuration in the fluent-bit.conf file to allow the communication via TCP:

```text
[INPUT]
    Name        tcp
    Tag         app
    Listen      0.0.0.0
    Port        5170
    Chunk_Size  3200
    Buffer_Size 3200
    Format      json
```

**Expected behavior**

Now when you run your Java application, logs will be sent to Fluent Bit using Logback's SocketAppender.

**Screenshots**

<img width="562" alt="image" src="https://github.com/fluent/fluent-bit/assets/42280453/50cdfea5-2eb6-4883-a9bb-a80f408cbd75">

<img width="720" alt="image" src="https://github.com/fluent/fluent-bit/assets/42280453/2d238194-12dd-484c-96a6-2c6876325b86">

<img width="1170" alt="image" src="https://github.com/fluent/fluent-bit/assets/42280453/7293f7a1-61c1-4181-9c85-ceb035b8e830">

**Your Environment**

* Version used: Fluent Bit v2.1.10, logback-classic 1.4.11
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Mac OS 
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

How has this issue affected you? I am not able to send the log files to fluentbit.
What are you trying to accomplish? Send the log files to fluentbit
Most of the Java examples we found in internet guide us to add the pom dependencies, add the tcp appender on logback-spring.xml and add sl4J logger to the application.
I would appreciate if you could help me by pointing out a Java working example so I can compare with mine to see what is missing.

**Comment by edsiper** [comment]
+ @lecaros

**Comment by lecaros** [comment]
Hi @AntonioJoaoSchwartzSoares
It seems that your logback is not sending the log in json format.
Can you configure an appended to console and verify the format?
If that's the case, you could add a layout>jsonformatter to your appender.

**Comment by AntonioJoaoSchwartzSoares** [comment]
Hi @lecaros , thank you for your prompt response!
Can you give me an example of a layout>jsonformatter? I am trynig few ones but not working.
If you please could show me the entire logback-spring.xml file I would appreciate.

**Comment by lecaros** [comment]
Have you verified it's not formatting as json? (This is not a Fluent Bit issue, btw :) )
I don't have one at hand, but this match seems okay.
https://stackoverflow.com/questions/40576959/logback-jsonlayout-printing-all-logs-on-the-same-line

**Comment by AntonioJoaoSchwartzSoares** [comment]
Hi @lecaros ,
thank you for your support!

**Comment by edsiper** [comment]
Closing assuming the issue was addressed.
