### ISSUE TITLE
Fluent-bit, How can I use strftime in path

### ISSUE THREAD

**Issue by huypd6946-cowell** [fluent/fluent-bit#8217]
my log file name contains the current date, like my_log_210616.log

and I need to tail the file in fluent-bit. I tried with,

`[INPUT]
Name    tail
Path    /var/log/my-service/my_log_%y%m%d.log

[OUTPUT]
Name stdout
Match *`

but it doesn't watch the file. I replaced my_log_%y%m%d.log with my_log_210616.log, then it works.

How can I use strftime in the path?

**Comment by patrick-stephens** [comment]
You cannot, per the docs it can use wildcards though and regexes.
