### ISSUE TITLE
Custom Fluent Bit Parser Not Applied Despite Correct Annotation and Configuration when using fluentbit.io/parser

### ISSUE THREAD

**Issue by alexglenn-ddl** [fluent/fluent-bit#8219]
## Bug Report

**Describe the bug**
Fluent Bit does not seem to apply a custom parser defined in parsers.conf even though the fluentbit.io/parser annotation is recognized. When the parser is omitted from parsers.conf, Fluent Bit correctly warns that the parser is not found. Additionally, other annotations like fluentbit.io/exclude work as expected, indicating that Fluent Bit successfully recognizes pod metadata. The issue appears specific to the execution of the custom parser.

```
[PARSER]
    Name   apache2
    Format regex
    Regex  .*?\s(?<host>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] (?:"|\")(?<method>\S+) (?<path>[^\"]*?) HTTP\/\d+\.\d+" (?<code>\d{3}) (?<size>\d+) (?<responsetimems>\d+|-) (?:"|\")(?<referer>[^\"]*)(?:"|\") (?:"|\")(?<agent>[^\"]*)(?:"|\")
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```

Is my custom regex and i've validate it's working using https://rubular.com/r/IhIbCAIs7ImOkc for the following log 

`2023-11-24T11:21:00.171913888Z stdout F 1.1.1.1 - - [24/Nov/2023:03:21:00 -0800] "GET /somepath/somerepo.git/info/refs?service=some-service HTTP/1.1" 401 726 108 "-" "SomeUserAgent/1.0"
`

This also works if I hardcode the parser to use apache 2 for everything it just doesn't seem to work by using the annotation as expected.

We use new relic to collect the logs but to prove out there was no issue with that I changed the output to just be stdout 

Even using the debug container and setting the logs all the way down to trace level I can't seem to get any details on why it's not calling the parser required.

**To Reproduce**
- https://rubular.com/r/IhIbCAIs7ImOkc
- Example log message if applicable:
```
`[1] kube.var.log.containers.git-0_random-namespace_git-randomid1234567890abcdef1234567890abcdef12345678abcdef123456789abcdef.log: [1700749674.147663397, {"stream"=>"stdout", "logtag"=>"F", "message"=>"111.111.111.111 - randomuser [23/Nov/2023:06:27:54 -0800] "GET /projectpath/randomrepo.git/info/refs?service=random-service HTTP/1.1" 200 526 5159 "-" "RandomAgent/1.0.0.202311050840-r"", "kubernetes"=>{"pod_name"=>"git-0", "namespace_name"=>"random-namespace", "pod_id"=>"randompodid-4c31-4fef-96c2-02d5c0936573", "labels"=>{"app.kubernetes.io/instance"=>"git", "app.kubernetes.io/name"=>"git", "apps.kubernetes.io/pod-index"=>"0", "controller-revision-hash"=>"git-randomhash1234", "random-label"=>"true", "statefulset.kubernetes.io/pod-name"=>"git-0"}, "annotations"=>{"checksum/config"=>"randomchecksum1234567890abcdef1234567890abcdef12345678abcdef123456789abcdef", "fluentbit.io/exclude"=>"false", "fluentbit.io/parser"=>"apache2", "random.annotation.com/random-annotation"=>"111.111.111.30"}, "host"=>"ip-111-111-111-111.us-west-2.compute.internal", "container_name"=>"git", "docker_id"=>"randomdockerid1234567890abcdef1234567890abcdef12345678abcdef123456789abcdef", "container_hash"=>"randomregistry.io/random/image@sha256:randomhash1234567890abcdef1234567890abcdef12345678abcdef123456789abcdef", "container_image"=>"randomregistry.io/random/image:v1.0.3"}, "clusterName"=>"randomcluster12345"}]`
```
- Steps to reproduce the problem:

Add annotation to pod fluentbit.io/parser"=>"apache2 

use the following config 

```
apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     ${LOG_LEVEL}
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              ${PATH}
        Parser            ${LOG_PARSER}
        DB                ${FB_DB}
        Mem_Buf_Limit     7MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name           kubernetes
        Match          kube.*
        # We need the full DNS suffix as Windows only supports resolving names with this suffix
        # See: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#dns-limitations
        Kube_URL       https://kubernetes.default.svc.cluster.local:443
        Buffer_Size    ${K8S_BUFFER_SIZE}
        K8S-Logging.Exclude ${K8S_LOGGING_EXCLUDE}
        K8S-Logging.Parser On
        Merge_Log On

    [FILTER]
        Name           record_modifier
        Match          *
        Record         clusterName ${CLUSTER_NAME}

    [OUTPUT]
        Name           newrelic
        Match          *
        licenseKey     ${LICENSE_KEY}
        endpoint       ${ENDPOINT}
        lowDataMode    ${LOW_DATA_MODE}
  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On

    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    # ADDED - Apache parsers - from https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  .*?\s(?<host>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+) (?<path>[^\"]*?) HTTP\/\d+\.\d+" (?<code>\d{3}) (?<size>\d+) (?<responsetimems>\d+|-) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>\S+) \S+ \S+ \[(?<time>[^\]]+)\] "(?<method>\S+) (?<path>[^\"]+) HTTP/\d\.\d" (?<status>\d+) (?<size>\d+) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<requestLength>\d+) (?<responseTime>[^ ]+) \[(?<upstreamName>[^\]]*)\] \[(?<upstreamAddr>[^\]]*)\] (?<upstreamHost>[^:]+):(?<upstreamPort>\d+) (?<requestTime>[^ ]+) (?<upstreamResponseTime>[^ ]+) (?<upstreamStatus>\d+) (?<requestId>[^\s]+)
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
```

apache2 pasrer not used.

**Expected behavior**
apache2 parser should be used and break out details from message into separate attributes

**Screenshots**
N/A

**Your Environment**

* Version used:
Fluent Bit v2.0.8
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/11/23 14:27:22] [ info] [fluent bit] version=2.0.8, commit=9444fdc5ee, pid=1
[2023/11/23 14:27:22] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/11/23 14:27:22] [ info] [cmetrics] version=0.5.8
[2023/11/23 14:27:22] [ info] [ctraces ] version=0.2.7
[2023/11/23 14:27:22] [ info] [input:tail:tail.0] initializing
[2023/11/23 14:27:22] [ info] [input:tail:tail.0] storage_strategy='memory' (memory only)
[2023/11/23 14:27:22] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc.cluster.local port=443
[2023/11/23 14:27:22] [ info] [filter:kubernetes:kubernetes.0]  token updated
[2023/11/23 14:27:22] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2023/11/23 14:27:22] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2023/11/23 14:27:22] [ info] [filter:kubernetes:kubernetes.0] connectivity OK
[2023/11/23 14:27:22] [ info] [output:stdout:stdout.1] worker #0 started
[2023/11/23 14:27:22] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2023/11/23 14:27:22] [ info] [sp] stream processor started

* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?):  v1.28.3-eks
* Server type and version: N/A
* Operating System and version: N/A
* Filters and plugins: Using New relic however i've disable the NR output plugin and tested using just stdout

**Additional context**
I want to be able to parse different logs for different pods so I can gather useful information out of them for creating dashboards and alerts etc. out of log attributes information

**Comment by alexglenn-ddl** [comment]
hey @patrick-stephens I can update for testing and ran with the latest version of fluent and received the same. I can bump to that version again for testing possible solutions however we use the new relic log integration which includes fluentbit and annoyingly comes with that version currently, so would need to either raise with them once/if we find a fix to bump the underlying version or find another method if it's version specific. 

We are running linux containers.

I can confirm the log parsing works if I change the pasrer to be the apache2 filter globally it only fails when using the annotation

**Comment by patrick-stephens** [comment]
So are you using New Relic's version they have built themselves rather than upstream OSS version? I'm not sure what other changes go in there unfortunately or if that impacts anything.

So log parsing is not being applied just with the annotation, the parser itself works?

**Comment by alexglenn-ddl** [comment]
Yes although I also changed to use the upstream fluent image for testing and got the same error. The parser itself works it just doesn't get applied when setting the annotation. Although I've managed to find the resolution in a bit of a missing link I figured out from this issue https://github.com/fluent/fluent-bit/issues/7218 

The primary cause was the shift from Docker to containerd (CRI) within EKS. This change impacted how logs are formatted and parsed. The standard log parser we were using previously became incompatible with the new log format under containerd. Even though we were using cri as the default filter parser. It looks like it doesn't like not using the multiline format on parsing the logs correctly. 

If we change 

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              ${PATH}
        Parser  ${LOG_PARSER}
        DB                ${FB_DB}
        Mem_Buf_Limit     7MB
        Skip_Long_Lines   On
        Refresh_Interval  10
 
 to
 
     [INPUT]
        Name              tail
        Tag               kube.*
        Path              ${PATH}
        multiline.parser  ${LOG_PARSER}
        DB                ${FB_DB}
        Mem_Buf_Limit     7MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        
  With CRI as our multline input parser, this now works and the annotation is applied as possible. It looks like a few other people have experienced the same based on that issue. 
  
  I'm not sure if it's worth referencing that in the docs as it doesn't reference any requirements for multiline parser and cri in later versions of k8s versions. 
  
  https://docs.fluentbit.io/manual/pipeline/filters/kubernetes
  
  If it does happy to raise a PR detailing what i've found and how to apply. But I think this specific issue can be closed based on I now have a fix

**Comment by patrick-stephens** [comment]
Ah right, yeah there is a lot of reinvention of CRI/docker log parsers that causes other issues so generally the approach should be always use the built in ones to handle the kubelet log processing then add your own as a separate filter stage.

https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-and-containers-v1.8

I've actually got a blog in the works around this but any clarification/contribution is greatly appreciated.
