### ISSUE TITLE
CloudWatch log classes support

### ISSUE THREAD

**Issue by SamuraiPrinciple** [fluent/fluent-bit#8220]
**Is your feature request related to a problem? Please describe.**
With the newly announced support for CloudWatch log classes:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CloudWatch_Logs_Log_Classes.html

it would be very nice if cloudwatch_logs output were to support creating log groups with Infrequent Access log class.

**Describe the solution you'd like**
Any reasonably ergonomic way of configuring fluentbit cloudwatch_logs output so that created log groups have Infrequent Access log class.

**Describe alternatives you've considered**
Alternative is for all the log groups to be pre-created with correct log class.

**Additional context**

Infrequent Access log class makes it possible to achieve operational savings.

**Comment by cristianmagana** [comment]
+1. This would be huge for orgs running in AWS!

**Comment by azastawski** [comment]
+1 yes please

**Comment by serkanh** [comment]
+1 pretty pls.

**Comment by dagnai** [comment]
+1!

**Comment by snehagg24** [comment]
+1

**Comment by pieterjanverbruggen** [comment]
+1

**Comment by adanecki** [comment]
Is there any chance, for this being implemented soon?

**Comment by mutchida** [comment]
This would be a big benefit for lot of AWS customers

**Comment by cristianmagana** [comment]
@edsiper @leonardo-albertovich  @nokute78  any chance fluentbit could provide CloudWatch Infrequent Access (%50 cost saving in log ingest) in the roadmap?

**Comment by dariodor** [comment]
+1

**Comment by boarder7395** [comment]
Can this be reopened seems like there is a lot of interest.
