### ISSUE TITLE
Azure Ouptut plugin - missing from online documentation

### ISSUE THREAD

**Issue by mp3monster** [fluent/fluent-bit#8227]
## Bug Report

When using fluent-bit --help you get a list of plugins available.  It lists an azure plugin which is detailed in the online documentation

**To Reproduce**
 fluent-bit --help

**Expected behavior**
Page detailing the configuration options

**Screenshots**

**Your Environment**
N/A

**Additional context**

**Comment by patrick-stephens** [comment]
I think this is a case of docs named differently to plugins again:

```
  azure                   Send events to Azure HTTP Event Collector
  azure_blob              Azure Blob Storage
  azure_logs_ingestion    Send logs to Log Analytics with Log Ingestion API
  azure_kusto             Send events to Kusto (Azure Data Explorer)
```
We can match up the names with the config `name` value used in each doc:
- `azure`: https://docs.fluentbit.io/manual/pipeline/outputs/azure
- `azure_blob`: https://docs.fluentbit.io/manual/pipeline/outputs/azure_blob
- `azure_logs_ingestion`: https://docs.fluentbit.io/manual/pipeline/outputs/azure_logs_ingestion
- `azure_kusto`: https://docs.fluentbit.io/manual/pipeline/outputs/azure_kusto

**Comment by patrick-stephens** [comment]
I'm not sure what the best option is here to align the exact plugin name so it is visible in the table/sub-buttons? @mp3monster any suggestions?

**Comment by mp3monster** [comment]
@patrick-stephens the azure plugin name is certainly confusing. But we have a mapping for all of them. So happy to see the issue closed. There as a few discrepancies between the plugin name and the name provided in the documentation - but with this one exception

**Comment by mp3monster** [comment]
Clarity obtained
