### ISSUE TITLE
Kensis Firehose and Kenesis Streams plugins missing from online documentation

### ISSUE THREAD

**Issue by mp3monster** [fluent/fluent-bit#8228]
## Bug Report

Kenesis Firehose and Kinesis Streams are missing from the online documentation but listed as plugins in fluent-bit --help

**Comment by patrick-stephens** [comment]
They're Amazon ones Phil: 
![image](https://github.com/fluent/fluent-bit/assets/6388272/12829299-e256-4393-b12c-1387e7471da4)
