### ISSUE TITLE
collector fluent-bit self cpu metric

### ISSUE THREAD

**Issue by thanq** [fluent/fluent-bit#8237]
**Describe the solution you'd like**
I want use cpu input plugin, collector fluent-bit self cpu metric ,  Can you provide the global variable to retrieve the fluentbit self PID?

Example:
[INPUT]
    Name cpu
    Tag  my_cpu
     PID  ${PID}

**Comment by patrick-stephens** [comment]
It might be better to use the process exporter plugin and then the better querying options there - you can query by process name for example.

https://docs.fluentbit.io/manual/pipeline/inputs/process-exporter-metrics
