### ISSUE TITLE
Lua error on hotreload when a new lua filter is added

### ISSUE THREAD

**Issue by geisbruch** [fluent/fluent-bit#8240]
## Bug Report

**Describe the bug**
If you add a lua filter to your config and runs a hot reload you get the following error

[2023/12/01 23:52:52] [error] Failed pre_run callback on filter lua.1
[2023/12/01 23:52:52] [error] [reload] check properties and additonal vaildations for filter plugins is failed
[2023/12/01 23:52:52] [error] [reload] reloaded config is invalid. Reloading is halted

**To Reproduce**
Fluentbit Verdion v2.2.0

- Steps to reproduce the problem:

Create a config simple config, as example:
```
[SERVICE]
    log_level    info
    flush           1
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020

[INPUT]
    Name forward
    Alias input_stream
    Listen 0.0.0.0
    port 24224
    Tag_Prefix docker.

[FILTER]
    Name Lua
    Match *
    call some_function
    script lua/filters.lua
```

Start fluentbit with hot reload
`/opt/fluent-bit/bin/fluent-bit --enable-hot-reload -c /configs/logs/fluent-bit.conf`

Append to your file other lua function, as example
```
[FILTER]
    Name Lua
    Match *
    call append_tag2
    code function append_tag2(tag, timestamp, record) new_record = record new_record["tag"] = tag return 1, timestamp, new_record end
```

Run a reload:

`curl -X POST -d '{}' localhost:2020/api/v2/reload`

```
[2023/12/02 00:03:15] [ info] reloading instance pid=498 tid=0xffffa8f34020
{"reload":"done","status":0}[2023/12/02 00:03:15] [error] [filter_lua] filter cannot be loaded
[2023/12/02 00:03:15] [error] Failed pre_run callback on filter lua.0
[2023/12/02 00:03:15] [error] [reload] check properties and additonal vaildations for filter plugins is failed
[2023/12/02 00:03:15] [error] [reload] reloaded config is invalid. Reloading is halted
```

As I could check that happens only if you have `script` if you run only using `code` I doesn't occurs

**Expected behavior**
A nice reload without errors

**Your Environment**

* Version used: 2.2.0
* Configuration: in the example
* Environment name and version (e.g. Kubernetes? What version?): ubuntu over docker
* Operating System and version: ubuntu
* Filters and plugins: plain instalation

**Comment by patrick-stephens** [comment]
I imagine this is the existing issue with using relative paths - if you specify a full absolute path for the filter (no assumptions on working directory please) then does it work?

**Comment by geisbruch** [comment]
Thank you Patrick, It works !! Sorry my apologize if it's duplicated

**Comment by patrick-stephens** [comment]
No worries, it's a general issue with hot reload that I believe is being worked on.
