### ISSUE TITLE
Output Processor Multi-Threading not working as expected (Mutex wait)

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-bit#8245]
## Bug Report
**Describe the bug**
We've observed an issue related to output multi-threading/worker option that seems to affect the performance of the processor in our case.
Observations:
- Output multi-threading does not seem to work as expected.
- Specifically, it appears that each thread is spending a significant amount of time in the mutexwait of the flb_processor_run instead of being effectively parallelized.

For instance (in our configuration):
- With 2 output workers, each output thread waits in mutexwait for approximately 50% of the time.
- With 10 output workers, this waiting time increases to around 90%.
- With 100 output workers, it almost reaches 99% of the time, indicating a significant serial processing bottleneck.
- Currently, there is no measurable benefit when using the multi-threading option of the outputs, except for very rare use cases where the log sink is notably slow or has a high response time.

Expected Behavior:
The output threads (including the processors) should ideally run in parallel, minimizing the waiting time in mutexwait and thus optimizing the overall performance.

**To Reproduce**
Simplified example configuration: https://gist.github.com/drbugfinder-work/456ef9715db25372a935d2d3a997e049
(You may have to adjust the number of dummy inputs / lua calculation to get similar results on your machine.)

**Screenshots**
- 2 workers:
![Bildschirmfoto 2023-12-04 um 15 59 43](https://github.com/fluent/fluent-bit/assets/60474128/ee96a1cb-1166-4c66-a1e4-8fa866786fed)

- 10 workers:
![Bildschirmfoto 2023-12-01 um 11 22 03](https://github.com/fluent/fluent-bit/assets/60474128/34f8709a-c407-410e-a2b6-0fd745c99141)

- 100 workers:
![Bildschirmfoto 2023-12-01 um 09 13 33](https://github.com/fluent/fluent-bit/assets/60474128/67b9d440-c4ae-44b2-95f3-d588217ff3e4)

**Your Environment**

* Version used: v2.2.0

**Comment by leonardo-albertovich** [comment]
Hi @drbugfinder-work, what you observed is the expected behavior when filters are used in the processor stack in the output stage. 

We are working on improving the situation but there is no way around it at the moment.

**Comment by patrick-stephens** [comment]
Yeah I wasn't really thinking of adding multiple workers as well as processors though :)

**Comment by drbugfinder-work** [comment]
@patrick-stephens 
I've added a chunk mode to the lua filter, so with the help of lua lanes the lua script can be parallelized on a whole chunk
https://github.com/fluent/fluent-bit/pull/8478

**Comment by patrick-stephens** [comment]
Sounds interesting @drbugfinder-work , @tarruda and @agup006 may be interested in that PR.

**Comment by drbugfinder-work** [comment]
Still open

**Comment by lecaros** [comment]
@drbugfinder-work what would be the expectation here? To correct the current expected behavior?

**Comment by drbugfinder-work** [comment]
@lecaros This issue is several months old. I haven't tested again with output processors in this context - and with input processors it is working as expected. So I would keep this issue closed for now. 
Thank you!
