### ISSUE TITLE
Workload/managed identity support for Azure Blob output

### ISSUE THREAD

**Issue by nc-ruth** [fluent/fluent-bit#8249]
**Is your feature request related to a problem? Please describe.**
I currently face challenges when working with Azure Blob output due to the lack of workload/managed identity support. This limitation affects the seamless integration and secure interaction with Azure Blob storage, leading to potential authentication issues and additional management overhead. It seems like the general recommendation by Microsoft is to avoid using [access keys.](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#protect-your-access-keys)

**Describe the solution you'd like**
I would like to request the implementation of workload/managed identity support for Azure Blob output. This enhancement would enable a more secure and streamlined workflow when interacting with Azure Blob storage, allowing users to leverage managed identities for authentication and access control.

**Describe alternatives you've considered**
I have considered alternative solutions such as using shared access signatures or manually managing storage account keys. However, these alternatives introduce security risks and operational complexities that could be mitigated with native support for managed identities. 

**Additional context**
I believe this feature would benefit a wide range of users who rely on Azure Blob storage for various applications and scenarios. Another related issue underscores the significant interest of implementing this feature based on its feedback from the community. https://github.com/fluent/fluent-bit/issues/2814

**Comment by patrick-stephens** [comment]
One area we would also like to improve is integration testing around this but it requires some effort and compute to do so. If anyone can help in that area it would be appreciated and improve the overall quality of releases for users on Azure.

Integration tests are here: https://github.com/fluent/fluent-bit-ci
Primarily running on GKE at the moment as we have donated compute to support that.

Feel free to reach out to me here or better on Slack: https://slack.fluentd.org/

**Comment by stevehipwell** [comment]
I think this is a duplication of #7525.
