### ISSUE TITLE
auto_kubernetes_labels not adding k8 label to stream

### ISSUE THREAD

**Issue by naveenpg11** [fluent/fluent-bit#8258]
## Bug Report

**Describe the bug**

I've like to add new output to my existing fluentbit service to send logs to loki. But the output sending log lines without any K8 labels. How do i configure fluentbit to send log with relevant k8 labels.

>  [Output]
>         Name loki
>         Match *
>         host HOST
>         port 443
>         tls on
>         tenant_id TENANT
>         auto_kubernetes_labels on

This output sending log lines without any K8 labels.

**To Reproduce**
- Just use the above output, I've tried the same in 2 different environment already.
- Example log message if applicable:
```
{
  "log": "2023-12-06T13:34:24.521608043Z stdout F 10.23.169.184 - - [06/Dec/2023:13:34:24 +0000] \"GET / HTTP/1.1\" 200  1442 \"-\" \"ELB-HealthChecker/2.0\" \"-\""
}
with only one label
```

![image](https://github.com/fluent/fluent-bit/assets/8851374/789fbe0e-5ee2-4d4c-b2b3-b04c0e44a5cb)

**Comment by smallc2009** [comment]
you need the kubernetes filter in your configuration. The kubernetes filter enriches kubernetes metadata into your log.
if you have custom input tag, you also need to match the tag and define `Kube_Tag_Prefix`. 

code snippet
```
[Input]
    Name    tail
    Path    /var/log/containers/*_net-apps*.log
    Refresh_Interval    10
    Skip_Long_Lines    true
    DB    /fluent-bit/tail/net-apps.db
    DB.Sync    Normal
    Mem_Buf_Limit    50MB
    Parser    docker
    Tag    netapps.*
    storage.type    filesystem
[Filter]
    Name    kubernetes
    Match    netapps.*
    Kube_URL    https://kubernetes.default.svc:443
    Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix    netapps.var.log.containers.
    Merge_Log    true
    K8S-Logging.Parser    true
    Labels    true
    Annotations    false
```
