### ISSUE TITLE
Fluent Bit still buffers to the filesystem if the folder in `storage.path` exists even if `Emitter_Storage.type` is set to `memory`

### ISSUE THREAD

**Issue by lpugoy** [fluent/fluent-bit#8259]
## Bug Report

**Describe the bug**
If a rewrite tag filter has `Emitter_Storage.type` set to `memory`, Fluent Bit will act as if `Emitter_Storage.type` is set to `filesystem` if `storage.path` is set in the `[SERVICE]` section and the filter's folder exists.

I can confirm this also happens with inputs with `Storage.type` set to `memory`. 

**To Reproduce**

Fluent Bit config
```
[SERVICE]
    storage.path /fluent-bit/data

[INPUT]
    Name dummy
    Tag dummy

[FILTER]
    Name rewrite_tag
    Match dummy
    Rule $message dummy rewritten false
    Emitter_Name rewriter
    Emitter_Storage.type memory

[OUTPUT]
    Name stdout
    Match rewritten
```

- Steps to reproduce the problem:
1. `mkdir -p "$(pwd)/data/emitter.2"`
2. Watch for file system changes in the `data` directory: `inotifywait` in Linux or `fswatch` in Mac, for example.
3. Run Fluent Bit: `docker run --name fluentbit --rm -v $(pwd)/data:/fluent-bit/data:rw -v $(pwd)/fluentbit.conf:/config/fluentbit.conf:ro cr.fluentbit.io/fluent/fluent-bit:2.2.0 -c /config/fluentbit.conf`.

**Expected behavior**
No files will be created under the `data/emitter.2` directory.

**Your Environment**
* Version used: 2.2.0
* Configuration: Fluent Bit config given above
* Environment name and version (e.g. Kubernetes? What version?): Docker
* Server type and version: n/a
* Operating System and version: n/a
* Filters and plugins: n/a

**Additional context**
This makes having some inputs/rewrite filters use filesystem buffering while others use memory impossible.

**Comment by nokute78** [comment]
@edsiper @leonardo-albertovich 
`cio_scan_streams` from `cio_load` creates cio_stream and set storage_type to filesystem if `storage.path` is defined and sub directory is found.

`mkdir -p "$(pwd)/data/emitter.2"` means that fluent-bit create cio_stream for emitter.2 and its storage_type is filesystem before creating plugin instances.

**Comment by nokute78** [comment]
I sent a patch https://github.com/fluent/fluent-bit/pull/8290 .
