### ISSUE TITLE
[error] [output:foward:foward.0] could not write foward entries V2.2.0 windows 

### ISSUE THREAD

**Issue by lisandrarocha1** [fluent/fluent-bit#8261]
## Bug Report

**Describe the bug**

**To Reproduce**
The fluentbit.conf that we use
[SERVICE]
       flush 5
daemon off
log_level info
log_file log\log.log
parsers_file parsers.conf

[INPUT]
Name tail
Path D:\netserver\*.log
Tag data_index
Ignore_Older 1h
Path_Key filename
multiline.parser multiline-regex
Refresh_interval 5
Buffer_Max_Size 100MB
Buffer_Chunk_Size 400k
Mem_Buf_Limit 100MB
DB C:\fluentbif_repo\data_index.db

[FILTER]
Name record_modifier
Match *
Record hostname ${HOSTNAME}

[FILTER]
Name parser 
Match *
Key_Name filename
Parser extract_filename
Reserv_Data True

[OUTPUT]
name forward 
Match *
Host hostname1245
Port 24224
net.dns.resolver LEGACY
- Steps to reproduce the problem:

This is how our configuration is set. As the expected behavior is the fluent-bit agenda don’t stop so we not loose data in our index. But when this error happens, after a while the agent stop to send data to fluentd and we have to restart the agent 

**Your Environment**

* Version used:2.2.0
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):fluentd version 1.16.1
* Server type and version: Rhel 8.7
* Operating System and version: windows server 2016
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
I'm a little confused by your server type being RHEL and the OS being Windows - what do you mean?

Can you confirm that Fluentd is working correctly and not the cause of the backpressure? I.e. it is not overloaded so preventing any more sending to it.

What do the logs for Fluent Bit show? Run with `log_level debug`.

Can you confirm with two FB instances? One forwarding to the other with a `null` output to prevent any backpressure.

**Comment by lisandrarocha1** [comment]
Here we use the fluentD in a linux server. That is what I a mean. So, we have the fluent-bit version 2.2.0 in a windows server and the fluentD version 1.16.1 in a linux server.

The fluentd configuration doesn't seem to be the problem. Because we have other windows server sending data to that same fluentd server and we don't have this same problem.

I put the logs on debug to see. 
About the last line, I don't know if I understand what you mean. Send the data from one FB to other? Could you explain for me , please?

Thanks
