### ISSUE TITLE
Docker Filter for Container Metadata running outside kubernetes

### ISSUE THREAD

**Issue by mitchellmaler** [fluent/fluent-bit#827]
Fluent bit should support collecting docker metadata for container log collection that is running outside of kubernetes. If I am tailing a log '086f0b4f2e4d068e84baeaaebc90ce9b941892e0067c74be94682c729df2b90a-json.log' it should be able to parse the config.v2.json next to it and get information about the running container or using the docker socket. This would be similar to the kubernetes filter.

**Comment by gitfool** [comment]
I was thinking the same while playing with Fluent Bit on AWS ECS. Is there a possible workaround in the meantime using existing plugins to somehow load the relevant `config.v2.json` and look up the metadata, or is a new filter the only solution?
