### ISSUE TITLE
out_stackdriver: error formatting JSON payload

### ISSUE THREAD

**Issue by ryanohnemus** [fluent/fluent-bit#8284]
## Bug Report

**Describe the bug**
Building fluentbit from a recent master commit and using the out_stackdriver plugin produces:
`[error] [output:stackdriver:stackdriver.0] error formatting JSON payload` (followed by engine failed to flush chunk errors). No data is being exported to google cloud.

**To Reproduce**
- Steps to reproduce the problem: 

Build fluent-bit from a recent git commit on master branch such as: https://github.com/fluent/fluent-bit/commit/1cb694e45fb39480bcda181d8bcc383f22d8f34a

then run fluent-bit with the `out_stackdriver` plugin set up. 

I was able to narrow it down to this commit: https://github.com/fluent/fluent-bit/commit/1a8dd39e3a26ddf06d479d2314b96d51faa0dec9

and doing a git revert of that commit and rebuilding resolves the issue. 

**Expected behavior**
json payload created properly and records exported to google cloud

**Comment by patrick-stephens** [comment]
@braydonk can you have a look as I think this was functionality added to resolve a separate issue?

**Comment by braydonk** [comment]
https://github.com/fluent/fluent-bit/pull/8229 should resolve this. There was an edge case I didn't cover while I was trying to fix the original bug.

**Comment by ryanohnemus** [comment]
Closing this after confirming #8229 resolved the issue. Thanks again @braydonk!
