### ISSUE TITLE
Skip_Empty_Lines does not work for CR LF. 

### ISSUE THREAD

**Issue by avizen-j** [fluent/fluent-bit#8313]
I have encountered similar issue mentioned here - https://github.com/fluent/fluent-bit/issues/4215

`Skip_Empty_Lines` works only for `LF` empty lines. So in case you are running container on windows and while testing you manually create "log", empty line will contain `CR LF` which is ignored by this setting.

**LF case**
![image](https://github.com/fluent/fluent-bit/assets/54904772/1770d1a2-ed30-4c01-997b-5015e1cc4906)

**CR LF case**
![image](https://github.com/fluent/fluent-bit/assets/54904772/fe3e6118-7896-4782-acfc-46363e6cb014)

**Result**
![image](https://github.com/fluent/fluent-bit/assets/54904772/4bd14987-c21f-4a13-bd28-af9543a8eaa0)

**Potential resolution**
I assume the issue is here:
https://github.com/fluent/fluent-bit/blob/3ce15c6f68d40075acbaabb5941036f278091c4c/plugins/in_tail/tail_file.c#L487C1-L496C1

Most likely `crlf` identification should be updated as well as if statement on L490 should be something like that:
`if (skip_empty_lines && crlf)` or simply `if (crlf)`

Current one does make sense as 2nd `if` will never be true:
```
if (len >= 2) {
 crlf = (data[len-1] == '\r');
 if (len == 1 && crlf) {
  data += 2;
  processed_bytes += 2;
  continue;
 }
}
```

**Sample config**
```
[INPUT]
    Name tail
    Skip_Empty_Lines On
    Path /app-logs/*

[OUTPUT]
    Name stdout
```

**Comment by nokute78** [comment]
Thank you for reporting.

I sent a patch https://github.com/fluent/fluent-bit/pull/8474 .
