### ISSUE TITLE
Ability to add more specific pod annotations (bis)

### ISSUE THREAD

**Issue by yann-soubeyrand** [fluent/fluent-bit#832]
Following https://github.com/fluent/fluent-bit/issues/777, more specific “parser” annotations have been implemented. This feature request is about implementing the same for the “exclude” annotation.

**Describe the solution you'd like**
To be consistent with the aforementioned issue, I suggest adding the following annotations:
```
- fluentbit.io/exclude_<(stdout|stderr)>-<container>
- fluentbit.io/exclude-<container>
- fluentbit.io/exclude_<(stdout|stderr)>
```

**Additional context**
See https://github.com/fluent/fluent-bit/issues/777.

**Comment by AndresPineros** [comment]
Also, it would be nice to be able to select the multiline regex for each pod too. Something like:
`fluentbit.io/multiline-first-line: "[0-9]{2}-[0-9]{2}-[0-9]{2}"`

The reason behind this is that not every pod in a Kubernetes cluster has Json logs and different pods have different multiline rules. Without this, it is very complex to have decent multilines for frameworks like Springboot, .Net, Node and others that are running in the same cluster.

**Comment by yann-soubeyrand** [comment]
Should be implemented in https://github.com/fluent/fluent-bit/pull/1265.

**Comment by yann-soubeyrand** [comment]
Here is the documentation update PR : https://github.com/fluent/fluent-bit-docs/pull/159.

**Comment by yann-soubeyrand** [comment]
PRs have been merged almost a year ago, closing ;-)
