### ISSUE TITLE
[Feature Request] Provide support for HTTPS proxy

### ISSUE THREAD

**Issue by harsh-nasit** [fluent/fluent-bit#8320]
I would like to request the implementation of HTTPS proxy support in the HTTP plugin of Fluent Bit. Currently, the HTTP plugin (referenced in src/flb_http_client.c) lacks native support for HTTPS proxy configurations.

Given the increasing prevalence of HTTPS protocols in modern web environments, having the ability to configure Fluent Bit to work seamlessly with HTTPS proxies would greatly enhance its compatibility and usability.

Ref:
https://github.com/fluent/fluent-bit/blob/34a2cd02ab4e8c512cc23911a3885ed8914e0c0c/src/flb_http_client.c#L678

**Comment by antoniomrfranco** [comment]
This PR should add support for HTTPS proxy: https://github.com/fluent/fluent-bit/pull/11778
