### ISSUE TITLE
How can I add a `container` name (or, at the very least, a `pod` name) as a suffix to a document sent by `fluent-bit`?

### ISSUE THREAD

**Issue by kinseii** [fluent/fluent-bit#8333]
**Describe the bug**
It's not a bug, but rather a question.

I have a problem with the fact that from some services come fields with different data types and OpenSearch can not parse them. In particular, if I enable `Merge_Log On` in fluent-bit, some services can send different data types to fields with the same name, so parsing doesn't work. I want to add a suffix to `Merge_Log_Key log_parsed` and make the logs from each service unique to avoid this problem.

**Expected behavior**
Thus, I would like to make a suffix such as `Merge_Log_Key log_parsed.CONTAINER_NAME(or POD_NAME)`. Is this possible with some filter or will I need to write a lua-script? Maybe someone already has a working solution.

**Your Environment**
* Version used: fluent-bit 2.2.0, OpenSearch 2.11.1
* Configuration: 
```
[FILTER]
    Name kubernetes
    Match kube.*
    Buffer_Size 256KB
    Merge_Log On
    Merge_Log_Key log_parsed
    Merge_Log_Trim Off
    Keep_Log On
```
* Environment name and version (e.g. Kubernetes? What version?): AKS 1.27.7

**Comment by leoswaldo** [comment]
I don't think this will be answered over here if you want to add questions I'd recommend you to reachout to the community on the slack channel https://www.launchpass.com/fluent-all
