### ISSUE TITLE
Parser regex should ignore missing fields

### ISSUE THREAD

**Issue by yann-soubeyrand** [fluent/fluent-bit#834]
## Bug Report

**Describe the bug**
When a field is described as optional in the regex and it is missing from the input record, it is not discarded which causes some memory violations:
- if the field is the time key, the parser tries to parse a missing field as a time,
- if this field has a type set in the configuration, the parser tries to transtype it.

**Example config**
```
[PARSER]
    Name                           apache-symfony-error
    Format                         regex
    Regex                          ^(?:\[(?<time>[^\]]+)\] \[(?:(?<module>[^.:\]]+)(?:\.(?<channel>[^:\]]+))?:)?(?<level>[^\]]+)\] (?:\[request (-|(?<request_id>[^\]]+))\] )?(?:\[pid (?<pid>[^\]]+)\] )?(?:\[client (?<client>[^\]]+)\] )?)?(?<message>.*)$
    Time_Key                       time
    Time_Format                    %a %b %d %H:%M:%S.%L %Y
    Types                          module:string channel:string level:string request_id:string pid:integer client:string message:string
```

**Example record**
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 100.112.0.44. Set the 'ServerName' directive globally to suppress this message`

**Expected behavior**
Missing fields should be discarded as in fluentd.

**Comment by edsiper** [comment]
Fixed by #835.
