### ISSUE TITLE
Support Elasticsearch API key authentication

### ISSUE THREAD

**Issue by husnialhamdani** [fluent/fluent-bit#8357]
**Is your feature request related to a problem? Please describe.**

There's no Elasticsearch API key option in here: https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch

**Describe the solution you'd like**

Able to authenticate to Elasticsearch using Elasticsearch API key

**Describe alternatives you've considered**

**Additional context**

**Comment by graphaelli** [comment]
There is now 🎉
