### ISSUE TITLE
The issue of continuous memory increase when referencing a large number of log files with 'input tail

### ISSUE THREAD

**Issue by tmxkaos112** [fluent/fluent-bit#8358]
I have an environment where log files are continuously generated. 
In this scenario, I've set up a pipeline to continuously reference and send newly created logs from /my/path/*.log to S3. However, as the log files continue to increase, the memory also grows. Here is my configuration.

And my version is 2.1.10.

```text 
[SERVICE]
   Parsers_File /fluent-bit/etc/parsers.conf
   Flush        1
   Log_Level    info
   Daemon       off

[INPUT]
   Name         tail
   Path         /fluent-bit/log/my/path/*.log
   Tag          DEVLOG.*
   Refresh_Interval  1
   Ignore_Older 1m
   Buffer_Chunk_Size 2m
   Buffer_Max_Size   100m
   Skip_Long_Lines   Off
   Skip_Empty_Lines On
   Mem_Buf_Limit 512m
   Inotify_Watcher false
   Read_from_Head  true

[OUTPUT]
   Name                s3
   Match               DEVLOG.*
   region              ${region}
   bucket              ${bucket}
   upload_timeout      10s
   use_put_object      On
   static_file_path    On
   upload_chunk_size   10m
   json_date_key       false
   log_key             log
   s3_key_format       /DEVLOG/$TAG[1]/$TAG[2].$TAG[3]
   s3_key_format_tag_delimiters .
   compression         gzip
```

   
   --------------

The same issue persists even with Inotify_Watcher set to true. Also, I'm unsure if Ignore_Older is functioning correctly. Can you shed some light on this?
   
I observed that when the memory keeps increasing, deleting log files from the actual application log path mounted in the 'path' of input tail releases the memory. Any insights into why this happens?

**Comment by edsiper** [comment]
how much memory usage are you seeing?

**Comment by tmxkaos112** [comment]
@edsiper 
When I tested for about 1 minute, the memory usage was about 1G.

If it continues for more than 1 minute, almost 3G is used.

**Comment by lecaros** [comment]
How many files match your path config by that time?
Can you run the same test but remove these settings?
```text
   Buffer_Chunk_Size 2m
   Buffer_Max_Size   100m
```
