### ISSUE TITLE
Message "No such file or directory" of flb_cf_fluentbit.c by execution on windows

### ISSUE THREAD

**Issue by itinside** [fluent/fluent-bit#8362]
I have download the fluent-bit-*-win64.zip Version for my first test of fluent-bit with the exemple from the documentation Page https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing .
But i receive the error message that something is missing in a directory.  

[2024/01/08 22:56:06] [error] [D:\a\fluent-bit\fluent-bit\src\config_format\flb_cf_fluentbit.c:454 errno=2] No such file or directory
[2024/01/08 22:56:06] [ info] [fluent bit] version=2.0.14, commit=bf20c16ea4, pid=10972
[2024/01/08 22:56:06] [ info] [storage] ver=1.4.0, type=memory, sync=normal, checksum=off, max_chunks_up=128
...

After that i test the older Version 2.0.14 with cmd and Powershell, but the same happend.

**Comment by itinside** [comment]
It happend by parsing the configfile if you add a comment on the end of the parameter:
![image](https://github.com/fluent/fluent-bit/assets/14044676/43a76cdb-6db5-4662-9209-5f7c760cfb83)

**Comment by patrick-stephens** [comment]
end of line comments are not supported

**Comment by patrick-stephens** [comment]
@pwhelan did you raise a docs PR on this I recall?

**Comment by itinside** [comment]
Yes it can be right, but in other lines you can define it, without errors, but not by this parameter.
Also it is a bit confused that it is not pollible to use TABs in this file.

@pwhelan What do you mean with PR, please?

**Comment by patrick-stephens** [comment]
@itinside inline comments are not supported - yes they may happen to work in some cases but not others but that's not the official support, you have to have comments on a separate line

Tabs should be fine but indentation has to be consistent so my guess is you're mixing tabs/spaces at different places.

**Comment by jamesawebb** [comment]
I found similar behaviour after `@INCLUDE`ing a file that didn't exist (typo).
