### ISSUE TITLE
Does fluent-bit support collecting logs of files in a specific directory inside a container

### ISSUE THREAD

**Issue by ForcemCS** [fluent/fluent-bit#8383]
One of my current requirements is to collect logs of files in a specific directory inside a container, and I'm not sure which plugin to use.

**Comment by ForcemCS** [comment]
I'm currently thinking of using the **hostpath** approach, but when my **Pod** is restarted (assuming my app is down for some reason and I need the previous logs for problem troubleshooting) the old logs get overwritten.

**Comment by patrick-stephens** [comment]
Yes, you obviously need to mount them via a shared volume to a Fluent Bit container or put Fluent Bit inside your container.
A sidecar container may be a better approach then trying to use a separate deployment or daemonset.

It's not really a Fluent Bit issue though, more a general architecture question.
