### ISSUE TITLE
Cross-compiling with Yocto isn't working

### ISSUE THREAD

**Issue by 2n3906** [fluent/fluent-bit#839]
## Bug Report

**Cross-compiling to ARM with Yocto & bitbake stopped working after 0.12.x.**
Out-of-tree builds using Yocto (cross-compiling to an ARM target) aren't working because:

1. `FindMonkey.cmake` fails to find Monkey, and
2. LuaJIT doesn't build properly for an ARM target.

**To Reproduce**
Build fluent-bit using a bitbake recipe for an ARMv7 target.  (Note that the exact recipe included in the repo is no longer adequate for a successful build.)

**Expected behavior**
Yocto/OE's support for Cmake projects is very robust and usually just works.

**Workarounds that work**
I can successfully build fluent-bit 0.14.4 (the latest release) using this patch for FindMonkey:
```
--- fluent-bit-0.14.4.orig/cmake/FindMonkey.cmake
+++ fluent-bit-0.14.4/cmake/FindMonkey.cmake
@@ -9,11 +9,4 @@
 #  - MONKEY_INCLUDE_DIR: root include directory

 unset(MONKEY_INCLUDE_DIR CACHE)
-find_path(MONKEY_INCLUDE_DIR
-  NAMES monkey/mk_core.h monkey/mk_lib.h
-  PATHS ${PROJECT_SOURCE_DIR}/lib/monkey/include
-  )
-
-include(FindPackageHandleStandardArgs)
-find_package_handle_standard_args(Monkey DEFAULT_MSG MONKEY_INCLUDE_DIR)
-include(FeatureSummary)
+set(MONKEY_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/lib/monkey/include")
```

And these modifications to the recipe:
```
S = "${WORKDIR}/fluent-bit-${PV}"
HOST_SYS_ARCH = "${HOST_ARCH}"
HOST_SYS_TRIPLE = "${HOST_SYS_ARCH}-unknown-linux"
EXTRA_OECMAKE = "-DGNU_HOST=${HOST_SYS_TRIPLE} -DFLB_WITHOUT_EXAMPLES=On -DFLB_LUAJIT=Off -DFLB_FILTER_LUA=Off"
```

Note that Lua needs to be switched off for the build to succeed.

Fixing LuaJIT is beyond my capabilities and it's probably not a big deal to leave Lua off by default, but something about FindMonkey doesn't play nicely with out-of-tree builds in Yocto.

I'm happy to contribute an updated BitBake recipe in a pull request if someone more familiar with Cmake suggests a satisfactory FindMonkey fix that works for everyone.

**Comment by edsiper** [comment]
@2n3906 an updated bitbake recipe would be appreciate. Please send me the updated one to try to find the root cause of the cmake problem.

**Comment by 2n3906** [comment]
Thanks for the response. I pull-requested an update to the Yocto recipe that gets us closer to a complete solution.  Happy to test any new workarounds you come up with for FindMonkey.

**Comment by edsiper** [comment]
Yocto recipes has been updated and fixes are in place now:

https://docs.fluentbit.io/manual/installation/yocto

**Comment by edsiper** [comment]
Fixed.

**Comment by nandra** [comment]
@edsiper I want to have fluent-bit cross-compiled with luajit support. In bitbake recipe it's disabled by default (as per above fix). I checked luajit recipe in openembedded and basically we need to pass some parameters from bitbake to cmake to have luajit build properly. Any ideas how to pass e.g. BUILD_CC from bitbake env to cmake?

Example from oe how to override CC, BUILD_CC from recipe for luajit:
```
# We don't want the lua buildsystem's compiler optimizations, or its
# stripping, and we don't want it to pick up CFLAGS or LDFLAGS, as those apply
# to both host and target compiles
EXTRA_OEMAKE = "\
    Q= E='@:' \
    \
    CCOPT= CCOPT_x86= CFLAGS= LDFLAGS= TARGET_STRIP='@:' \
    \
    'TARGET_SYS=${LUA_TARGET_OS}' \
    \
    'CC=${CC}' \
    'TARGET_AR=${AR} rcus' \
    'TARGET_CFLAGS=${CFLAGS}' \
    'TARGET_LDFLAGS=${LDFLAGS}' \
    'TARGET_SHLDFLAGS=${LDFLAGS}' \
    'HOST_CC=${BUILD_CC}' \
    'HOST_CFLAGS=${BUILD_CFLAGS}' \
    \
    'PREFIX=${prefix}' \
    'MULTILIB=${baselib}' \
    'LDCONFIG=:' \
"
```

Thanks
