### ISSUE TITLE
out_stackdriver: LogEntry structure

### ISSUE THREAD

**Issue by aplulu** [fluent/fluent-bit#840]
If jsonPayload contains keys such as httpRequest, operation, severity etc, can I move them to root level?
Including httpRequest and severity at the root level makes it easier to view logs in Cloud Console.

https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#httprequest
https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/stackdriver.c#L383

similar issue
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/126
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/57/commits/d5d1792aa734139234cc4ea40bad4cbacc578b34

**Comment by derekperkins** [comment]
This would make the logs much easier to consume.

**Comment by ensonic** [comment]
Yes severity would be super important to have. On the output side. 'severity' is a top-level field in LogEntry
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity

Any information what the fluent-bit side to populate this from? I could make a PR for that.

**Comment by sebbacon** [comment]
Google's own fluentd implementation [strips special, named fields from the JSON payload](https://cloud.google.com/logging/docs/agent/configuration#special_fields_in_structured_payloads) and sets them in the `LogEntry` object. These fields include `severity`.

The place to fix this is, I believe, [here](https://github.com/fluent/fluent-bit/blob/master/plugins/out_stackdriver/stackdriver.c).
