### ISSUE TITLE
librdkafka input batch config

### ISSUE THREAD

**Issue by artemus717** [fluent/fluent-bit#8400]
How can I config batch size in INPUT of Kafka plugin.

Seemed there are a limit of message consume.

Fluent Bit version is 2.2

Checked this document and tried many config, but consume is still slow than logstash.
https://docs.confluent.io/platform/current/clients/librdkafka/html/md_CONFIGURATION.html

Thanks in advance.

**Comment by lyhgo** [comment]
I just find this is related to this line of code.
file: plugins/in_kafka/in_kafka.c
![image](https://github.com/fluent/fluent-bit/assets/37298119/a6ffa779-e0f4-4974-bcf8-942643ca2380)


When I test locally, the result is.
with it: 1s consume 3-5 messages.
without it: 1s consume 200-300 messages.
Does anyone have a suggestion?
Thanks in advance.

**Comment by simontilmant** [comment]
The problem seems linked to the fact that a call to `rd_kafka_commit` is performed for every single message.
If we look at https://docs.huihoo.com/apache/kafka/confluent/3.1/clients/consumer.html, `rd_kafka_commit` is called every 1000 messages.

The following change take for the site above is dramatically improving performance

```
static void in_kafka_callback(int write_fd, void *data)
{
    struct flb_input_thread *it = data;
    struct flb_in_kafka_config *ctx = data - offsetof(struct flb_in_kafka_config, it);
    mpack_writer_t *writer = &ctx->it.writer;
    static const int MIN_COMMIT_COUNT = 1000;

    int msg_count = 0;

    while (!flb_input_thread_exited(it)) {
        rd_kafka_message_t *rkm = rd_kafka_consumer_poll(ctx->kafka.rk, 500);

        if (rkm) {
            process_message(writer, rkm);
            fflush(ctx->it.write_file);
            rd_kafka_message_destroy(rkm);

            if ((++msg_count % MIN_COMMIT_COUNT) == 0)
                rd_kafka_commit(ctx->kafka.rk, NULL, 0);
        }
    }
}
```
