### ISSUE TITLE
Decode_Field_As escaped_utf8 replaces \n at the end with null byte

### ISSUE THREAD

**Issue by xanonid** [fluent/fluent-bit#841]
## Bug Report

**Describe the bug**
The the default docker parser with `Decode_Field_As escaped_utf8` converts sometimes
newlines at the end to `\u0000`.
`\t` and `\n` are also differently processed (but not to their `\uXXXX` sequence).

**To Reproduce**

```
{"log":"test\n","stream":"stdout","time":"2018-10-09T17:04:54.905646487Z"}
{"log":"test\u0009\t\n","stream":"stdout","time":"2018-10-09T17:04:54.905646487Z"}
{"log":"test\u0009\t\u000a\n","stream":"stdout","time":"2018-10-09T17:04:54.905646487Z"}
```

Call `./fluent-bit -i tail -p "path=logfile" -p "parser=docker" -R parser.conf -o file -p "path=output.txt"`
with parser.conf:

```
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
    Decode_Field_As   escaped_utf8    log
```

Output:
```
tail.0: [1539104694.905647, {"log":"test\\\u0000", "stream":"stdout", "time":"2018-10-09T17:04:54.905646487Z"}]
tail.0: [1539104694.905647, {"log":"test\t\t\\n", "stream":"stdout", "time":"2018-10-09T17:04:54.905646487Z"}]
tail.0: [1539104694.905647, {"log":"test\t\t\n\\n", "stream":"stdout", "time":"2018-10-09T17:04:54.905646487Z"}]
```

**Expected behavior**
Output:
```
tail.0: [1539104694.905647, {"log":"test\n", "stream":"stdout", "time":"2018-10-09T17:04:54.905646487Z"}]
tail.0: [1539104694.905647, {"log":"test\t\t\n", "stream":"stdout", "time":"2018-10-09T17:04:54.905646487Z"}]
tail.0: [1539104694.905647, {"log":"test\t\t\n\n", "stream":"stdout", "time":"2018-10-09T17:04:54.905646487Z"}]
```

The same issue can be also reproduced with the forward and stdout output (which needs to be redirected to see the null byte).

**Environment:**
* Version used: 0.14.4 & last 0.14 branch (163abb6c5df)
* Environment name and version: reproduced on Kubernetes and locally
* Operating System and version: Debian, Ubuntu

**Comment by edsiper** [comment]
thanks again. #847 merged and fixed.
