### ISSUE TITLE
Fluentbit hot reload not working for 50 nodes cluster

### ISSUE THREAD

**Issue by Praveen2099** [fluent/fluent-bit#8412]
## Bug Report

**Describe the bug**

I have deployed fluentbit as a daemonset in the 50 nodes cluster and created a kubernetes service.
I am using hot reload api by using service name but it is not working it is not reloading the latest configuration 
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by CatherineF-dev** [comment]
qq: is it working now?

**Comment by Praveen2099** [comment]
No its not working
. sorry to say but so much delay in the response

**Comment by Praveen2099** [comment]
@CatherineF-dev  Currently we have deployed fluentbit as a daemonset.So can you please tell me how to reload all pods hot reload api.

**Comment by CatherineF-dev** [comment]
> So can you please tell me how to reload all pods hot reload api.

I want to use this feature as well.

**Comment by Praveen2099** [comment]
@patrick-stephens  can you please help here.

**Comment by patrick-stephens** [comment]
Not working is really vague and so you need to provide more detail on what/how it is not working. Does it work for a single pod?

My guess is you're going via a service (not [headless](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services)?) so it's only hitting one pod. You need to tell all pods to reload so you need to trigger it on all of them by working with the pods directly, not the services.

**Comment by Praveen2099** [comment]
@patrick-stephens thanks for the reply.
I have 50 pods.So how to trigger reload for all pods.

**Comment by patrick-stephens** [comment]
As I say, the same way you do it for any K8S workflow where you want to hit all the pods. This is nothing to do with Fluent Bit but just how K8S works - the same as if you had 50 VMs behind a LoadBalancer and wanted to hit them all.

You need to ensure you ping each of the pods endpoint. There are a few approaches to do that so I would research the one best for you, e.g. first result on google: https://stackoverflow.com/a/50797128

**Comment by patrick-stephens** [comment]
I would recommend you use the official helm chart which includes a hot-reload sidecar that does exactly what you want, or follow the same approach: https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit

See https://github.com/fluent/helm-charts/blob/4298193bedae6b4804e02633e851947432f5ed3b/charts/fluent-bit/values.yaml#L490-L497 for config of hot reload.
It runs a sidecar that then pokes the hot reload API of its associated container (in the same pod) when required. It inverts the process you are trying to do so is potentially simpler.

**Comment by Praveen2099** [comment]
Thanks.
Ii will definitely work.
