### ISSUE TITLE
inline messages

### ISSUE THREAD

**Issue by mashkouski** [fluent/fluent-bit#8418]
fluent-bit 2.2.1 (very often) (and 2.2.2 (rarely)) in windows with small flush time (1 sec) sends inline messages in forward output.
(We have our own tcp "forward" server written in rust)

inline messages example:

```
[
"tag",
  [
     [ time, {message} ],
     [ time, {message} ],
   ],
  
  [ 
     "tag",
        [
            [ time, {message} ],
            [ time, {message} ],
        ],
       {
         options
       }
  ]
]
```

And sometimes we get multi-level nesting, but always with one `options` section

I think it is not expected behaviour (I don't found it in forward protocol specifications)

Used fluent config:

```
[SERVICE]
    flush        1

    daemon       Off

    log_level    info

    parsers_file parsers.conf
    plugins_file plugins.conf

    http_server  Off
    http_listen  0.0.0.0
    http_port    2020

    storage.metrics on
    storage.path C:/Program Files/fluent-bit/storage
    storage.sync normal
    storage.checksum off

[INPUT]
    Name         winevtlog
    Channels     application,system,security
    Interval_Sec 1
    Read_Existing_Events True
    storage.type  filesystem
    Tag ws.windows.machine-name

[OUTPUT]
    Name          forward
    Match         ws.windows.machine-name
    Host          10.10.120.55
    Port          24225
    Require_ack_response True
    storage.total_limit_size 10000M
    Retry_Limit no_limits
```

(parsers_file and plugins_file - with default options)

Environment
- fluent-bit 2.2.1 (well reproduces) / 2.2.2
- Windows 11 Desktop, Intel x64

**Comment by nokute78** [comment]
Could you check the forward protocol specification v1.5 ?
https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1.5#event-modes

**Comment by mashkouski** [comment]
Yep
and 99% messages has normal format:

```
[
  "tag.name",
  [
    [[1441588984, {Hash}], {"message": "foo"}],
    [[1441588985, {Hash}], {"message": "bar"}],
    [[1441588986, {Hash}], {"message": "baz"}]
  ],
  {"option": "optional", "fluent_signal": 0}
]
```
(Hash - absent, time in fixext8 (or ext8) and fluent_signal = 0)

but 1% instead "option" section has nesting message, like:

```
[
  "tag.name",
  [
    [[1441588984, {Hash}], {"message": "foo"}],
    [[1441588985, {Hash}], {"message": "bar"}],
    [[1441588986, {Hash}], {"message": "baz"}]
  ],
  [
    "tag.name",
    [
      [[1441588984, {Hash}], {"message": "foo"}],
      [[1441588985, {Hash}], {"message": "bar"}],
      [[1441588986, {Hash}], {"message": "baz"}]
    ],
    {"option": "optional", "fluent_signal": 0}
  ]
]
```
(nested message has fluent_signal = 0)

First tag and second - has the same value

This nesting can also be multi-level

And I can't find in protocol 1.5 description this behaviour
