### ISSUE TITLE
More YAML configuration documentation

### ISSUE THREAD

**Issue by epsteina16** [fluent/fluent-bit#8433]
**Is your feature request related to a problem? Please describe.**
Many plugins and configuration sections are missing examples for YAML configuration. 
Here are some examples:
https://docs.fluentbit.io/manual/administration/buffering-and-storage#configuration
https://docs.fluentbit.io/manual/pipeline/outputs/file#configuration-file
https://docs.fluentbit.io/manual/pipeline/outputs/loki#getting-started

**Describe the solution you'd like**
It would be helpful to show all configuration snippets in both YAML and classic format.
Maybe an option to toggle between them.

**Additional context**
Now that YAML is production ready, it would help if it was documented as a first-class configuration format for wider adoption and ease of use.

**Comment by lecaros** [comment]
Hello @epsteina16, thanks for noting this.
PRs are always welcome! :)

**Comment by epsteina16** [comment]
Thanks for the response @lecaros 
We'd like to move to full YAML-based configuration, and having more documentation across the board would be very helpful for us and I'm sure others as well.

**Comment by patrick-stephens** [comment]
I think we all agree, it's more that it takes time to do and so contribution is always welcome for any plugins you're working with. OSS docs are a great way to contribute particularly for first time PRs.

**Comment by patrick-stephens** [comment]
Saying that I just checked and @nokute78 has been a very busy bee with adding a lot more: https://github.com/fluent/fluent-bit-docs/pulls

Thanks @nokute78

**Comment by uberjew666** [comment]
Can parsers also be configured using YAML?

**Comment by patrick-stephens** [comment]
Not yet but they will be.

**Comment by epsteina16** [comment]
Just checking in on this. Thanks @nokute78 for adding many examples!
Is there a timeline for when a larger set of YAML examples will be added to the docs?

**Comment by patrick-stephens** [comment]
It would greatly speed things up if people can submit PRs proactively to add any missing examples. Docs PRs are a great and simple way to contribute to OSS.
