### ISSUE TITLE
node_exporter in docker: mount points from container shown (not from host)

### ISSUE THREAD

**Issue by daberlin** [fluent/fluent-bit#8434]
## Bug Report

**Describe the bug**
I run fluentbit inside a docker container with node_exporter enabled. Two volumes are mounted:
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

FB config:
[INPUT]
    name                        node_exporter_metrics
    tag                         metrics
    scrape_interval             2
    path.procfs                 /host/proc
    path.sysfs                  /host/sys

[OUTPUT]
    name                        prometheus_exporter
    match                       metrics
    host                        0.0.0.0
    port                        2021

Prometheus shows only mountpoints from inside the container, bot even the rootfs.
Are we missing an option "path.rootfs" or are there hardcoded paths?

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
node_filesystem_avail_bytes{compose_project="sechub-develop", device="/dev/root", fstype="ext4", instance="logging:2021", job="fluent-bit", mountpoint="/etc/hostname"}
```
--> /etc/hostname is not mounted on the host

- Steps to reproduce the problem:

**Expected behavior**
I would expect to see the host's mountpoints.

**Screenshots**
n/a

**Your Environment**
* Version used: Fluent Bit v2.2.2
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): docker v24
* Server type and version: Azure VM
* Operating System and version: Ubuntu server 22.04
* Filters and plugins: see above

**Comment by MrMMorris** [comment]
might be related to the bug I just opened 
https://github.com/fluent/fluent-bit/issues/9092

**Comment by vchirikov** [comment]
Trying to configure fluent-bit as replacement of node_exporter and have the same question about `path.rootfs` :\
