### ISSUE TITLE
syslog and stdout plugin is collecting the logs and appending as nested json object

### ISSUE THREAD

**Issue by udhayakumarcp** [fluent/fluent-bit#8458]
## Bug Report

**Describe the bug**
It appending the logs as nested logs

**To Reproduce**
Use the below configuration to reproduce the issue

```
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics on

[INPUT]
    Name     syslog
    Parser   syslog-rfc3164-local 
    #Parser   syslog-rfc5424
    #Parser   syslog-rfc3164
    Listen   0.0.0.0
    Port     5140
    Mode     tcp
    Tag      syslog

[OUTPUT]
    Name     stdout
    Match    *
```
Example log message of output from stdout plugin
```
 [
   [1707168225.000000000, {}],
   {"pri"=>"30", "time"=>"Feb  5 21:23:45", "ident"=>"chiefnet-0800277BF4F2", "message"=>"[181] syslog: [
     [1707168224.000000000, {}],
     {"pri"=>"30", "time"=>"Feb  5 21:23:44", "ident"=>"chiefnet-0800277BF4F2", "message"=>"[181] syslog: [
       [1707168223.000000000, {}],
       {"pri"=>"30", "time"=>"Feb  5 21:23:43", "ident"=>"chiefnet-0800277BF4F2", "message"=>"[181] syslog: [
         [1707168222.000000000, {}], 
         {"pri"=>"30", "time"=>"Feb  5 21:23:42", "ident"=>"chiefnet-0800277BF4F2", "message"=>"[181] syslog: [
           [1707168222.000000000, {}], 
           {"pri"=>"30", "time"=>"Feb  5 21:23:42", "ident"=>"chiefnet-0800277BF4F2", "message"=>"2024-02-05 21:23:42,385 | INFO | traffic_steering_manager.py | 397 | traffic_steering_manager | __wan_interface_failover_handler | No WAN interfaces to be monitored"}
          ]"}
        ]"}
      ]"}
    ]"}
  ]
  
```
**Expected behavior**
it should print as the below output it seems

```
 [
    [1707168222.000000000, 
    {"pri"=>"30", "time"=>"Feb  5 21:23:42", "ident"=>"chiefnet-0800277BF4F2", "message"=>"2024-02-05 21:23:42,385 | INFO | traffic_steering_manager.py | 397 | traffic_steering_manager | __wan_interface_failover_handler | No WAN interfaces to be monitored"}]
 ]
  
```
**Your Environment**

![image](https://github.com/fluent/fluent-bit/assets/50567115/255ad8ed-7c3a-4a6e-b1c9-1c6e5895f144)

* Version used:2.2.2
* Configuration: 3GB RAM 30GB HDD 1core
* Environment name and version (e.g. Kubernetes? What version?): Oracle Virtual box
* Server type and version:
* Operating System and version:Ubuntu 22.04.3 2023.11.08 LTS (Cubic 2023-11-08 19:41)
* Filters and plugins: syslog, stdout

**Comment by patrick-stephens** [comment]
What's generating the syslog input?
Are you logging Fluent Bit output to syslog so it is recursing?

**Comment by udhayakumarcp** [comment]
> What's generating the syslog input? Are you logging Fluent Bit output to syslog so it is recursing?

There is Rsyslog running to write and forward the syslog through TCP. The log are from the oneof my python application. if see the Syyslog it fine. Where the flent bit is prinintg the nested logs in stdout.

I am not sure that i am loggin the fluent bit output to syslog. I haven't do that. Is this default behaviour of fluent bit. How i can verify? Will stdout log the logs to syslog?

**Comment by patrick-stephens** [comment]
I imagine you have Ubuntu configured to send systemd logs to rsyslog. Fluent Bit does not control syslog but the packages do install a systemd service - however this is standard and it sounds like all your services would be sending to syslog.

**Comment by udhayakumarcp** [comment]
@patrick-stephens, Thanks for your inputs.
