### ISSUE TITLE
Release of Fluent-Bit 2.2.3

### ISSUE THREAD

**Issue by Garfield96** [fluent/fluent-bit#8502]
## Bug Report

**Describe the bug**
Fluent-Bit v2.2.2 has a memory leak, which occurs with the forward output plugin. As a result, long-running Fluent-Bit instances at some point will crash. The issue was fixed in https://github.com/fluent/fluent-bit/pull/8399 and backported to 2.2.x via https://github.com/fluent/fluent-bit/pull/8402, but not yet released. It would be highly appreciated if a new patch release could be published which makes the fix officially available.

Thanks

cc: @edsiper

**Comment by Garfield96** [comment]
@edsiper @patrick-stephens Can you please provide a release date for fluent-bit v2.2.3? Thanks

**Comment by patrick-stephens** [comment]
I cannot so I'll ask @edsiper , @agup006 may also have covered in the community meeting

**Comment by patrick-stephens** [comment]
Closing as we have it: https://github.com/fluent/fluent-bit/releases/tag/v2.2.3
