### ISSUE TITLE
Kubernetes filter: Tag longer than 5 chars

### ISSUE THREAD

**Issue by NikNikM** [fluent/fluent-bit#8508]
## Bug Report

**Describe the bug**
When using Kubernetes filter https://docs.fluentbit.io/manual/pipeline/filters/kubernetes,
if the tag in the input tail is longer that 5 chars, the filter is not working and it's really difficult for users to find that this is the problem.

**To Reproduce**
```
[INPUT]
    Name    tail
    Tag     abcdef.*
    Path    /var/log/containers/*.log
    Parser  docker
```

```
[FILTER]
    Name             kubernetes
    Match            abcdef.* (or even with *)
    Kube_Tag_Prefix  kube.var.log.containers.
    Merge_Log        On
    Merge_Log_Key    log_processed
```

**Expected behavior**
It should work with longer tags or at least it should be clearly mention in the documentation.

**Additional context**
The issue is not really that big if you know what is the issue :)
The problem is basically that Kube_Tag_Prefix is used to move the pointer and then the regex is applied.
https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_meta.c#L1263
so the tag length is not considered.

It is better described here: https://calyptia.com/blog/kubernetes-metadata-enrichment-with-fluent-bit-with-troubleshooting-tips

**Comment by patrick-stephens** [comment]
Nope, your kube_tag_prefix is incorrect - it must match your tag from tail. The wildcard is expanded to the full path location of the log file.

See https://calyptia.com/blog/kubernetes-metadata-enrichment-with-fluent-bit-with-troubleshooting-tips

It will happen to work for <6 because that is the length of `kube.`...

**Comment by NikNikM** [comment]
Hi Patrick, thanks for you help. 
Yes, that's the same article that I mentioned.
But you can omit `kube_tag_prefix` as it's optional and then it will take the default `kube.var.log.containers.`.
Then your tag must be <6 for the same reason you said but the relation between `Match` (so the tag in the input tail) and `kube_tag_prefix` is not mention or at least it's not straightforward.
I'm pretty sure many engineers will struggle with this and that's the reason I opened this bug, which is not a bug itself if the relation between `Match` and `kube_tag_prefix` is clearly explained, which currently, in my opinion, is not (copy-paste from kubernetes filter for `Kube_Tag_Prefix`):
_"When the source records comes from Tail input plugin, this option allows to specify what's the prefix used in Tail configuration."_

**Comment by patrick-stephens** [comment]
The `kube_tag_prefix` is not optional, my blog post tries to explain what is required. In this case your tag does not correctly have the prefix stripped to just leave the relevant filename which can then be parsed to give the relevant information to query the K8S API server.

I think we both agree this needs a doc update so please submit a PR there: https://github.com/fluent/fluent-bit-docs

My point was that there is nothing restricting the tag to be <6 chars (assuming the rest of the config is correct) and this is not a bug in Fluent Bit but more a misconfiguration that is easy to do. A feature request to store the info we need in metadata or elsewhere would be nice but this is not a bug per se.
