### ISSUE TITLE
Fluent-Bit v0.15.0 [flb_msgpack_to_gelf] missing short_message key

### ISSUE THREAD

**Issue by GuWeHa** [fluent/fluent-bit#851]
**Question**

Hi folks,

I'm working on a k8s solution putting fluent-bit output in GELF format directly to graylog without using fluentd as aggregator.

Because GELF isn't supported natively up to fluent-bit v0.14.4 it pulled the last sources and built my own v0.15.0. Sadly, I've some problems with short_message key.

Here is my flb.conf (just as small test only):
```
[SERVICE]
    Flush         1
    Daemon        off
    Log_Level     debug

[INPUT]
    Name          cpu
    Tag           my_cpu

[OUTPUT]
    Name          gelf
    Match         *
    Host          192.168.192.28
    Port          12501
    Mode          udp
    Short_Message my_key
```
Runninng it with _./fluent-bit -c flb.conf_ I get this output:

```
guido@slvkube10 test]$ ./fluent-bit -c flb.conf 
Fluent-Bit v0.15.0
Copyright (C) Treasure Data

[2018/10/17 10:56:48] [ info] [engine] started (pid=13363)
[2018/10/17 10:56:48] [debug] [router] match rule cpu.0:gelf.0
[2018/10/17 10:56:48] [debug] [input cpu.0] [mem buf] size = 317
[2018/10/17 10:56:49] [debug] [task] created task=0x562974588020 id=0 OK
[2018/10/17 10:56:49] [error] [flb_msgpack_to_gelf] missing short_message key
[2018/10/17 10:56:49] [error] [out_gelf] error encoding to GELF
```

I think there's  s.th. wrong with short_message key. But what? Wrong spelling in _flb.conf_ file? Wrong place of insertation .conf file? S.th. else?

Any help would be greatly appreciated!

Greetinx

Guido

**Comment by edsiper** [comment]
ack.
