### ISSUE TITLE
Filter to append tag to record (or at least accessing tag through record_modifier)

### ISSUE THREAD

**Issue by Sikwan** [fluent/fluent-bit#853]
**Is your feature request related to a problem? Please describe.**
Hey guys, I am using fluent-bit to stream logs from my docker-swarm (using the fluentd logging-driver). I know, I could use fluentd instead of fluent-bit but I wanted to try out the lightweight option, especially since it is then sending logs to another fluentd instance).
Right now everything is working perfectly fine, except I cannot find a way to append the image name to my records. I did put the image as a tag, which I see when I print my records, but I cannot find a way to dump the tag value into the record in fluentbit.

My pipeline is somewhat like this:
forward_input > Filter (json parser) > http_output > Fluentd

**Describe the solution you'd like**
It would be great if we could access the tag value within record_modifier and add it to the record. I saw that elasticsearch and kafka output both had an option to dump the tag in the record.

**Describe alternatives you've considered**
There is a LUA script doing the same thing within the fluent-bit repo, though I have to admit having to use a LUA script for something so simple if a bit hard to swallow to me.

**Additional context**
It is highly possible that this is already possible, but I could not find a solution.

**Comment by edsiper** [comment]
There is no generic way at the moment to include the tag as part of the record in the input side. Workarounds:

- use a Lua script
- If you are using in_tail, set the _path_key_ option which will include the file name being monitored. If the file name contains the image name that could help.

**Comment by sparrowt** [comment]
See example using the Lua script method here: https://github.com/fluent/fluent-bit/discussions/8657#discussioncomment-12351065
