### ISSUE TITLE
Sending logs from local to aws s3 using fluent-bit

### ISSUE THREAD

**Issue by premeximietas** [fluent/fluent-bit#8532]
i am trying to send the logs from my local machine to the aws s3  using fluent-bit , i have pulled the image of the fluent-bit in the docker and created the configure file of the fluent-bit 

fluent-bit.conf=>

[SERVICE]
    Flush            5
    Daemon           Off
    Log_Level        debug

[INPUT]
    Name             tail
    Path             C:\projects\logging_fastapi\logs
    Tag              app.log
    Refresh_Interval 10

[FILTER]
    Name             record_modifier
    Match            *
    Record           container_id ${HOSTNAME}

[OUTPUT]
    Name             s3
    Match            app.log  
    Bucket           specyfeedbackbatch
    Region           us-east-1
    S3_Key_Format    /%Y/%m/%d/%H/%Y-%m-%d-%H-%M-%S-application.log
    Total_File_Size  5M

after this i ran the command of the docker container as  docker run -d --name fluentbit -v C:\projects\logging_fastapi\fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf -v C:\projects\logging_fastapi\logs\:/logs:ro fluent/fluent-bit:latest

binding the conf file and my logs file after creating the container it shows me [ 2024-02-28 15:23:00 [2024/02/28 09:53:00] [debug] [input:tail:tail.0] scanning path C:\projects\logging_fastapi\logs
2024-02-28 15:23:00 [2024/02/28 09:53:00] [debug] [input:tail:tail.0] cannot read info from: C:\projects\logging_fastapi\logs
2024-02-28 15:23:00 [2024/02/28 09:53:00] [debug] [input:tail:tail.0] 0 new files found on path 'C:\projects\logging_fastapi\logs' ]

and it is not sending files to the aws s3 , state the expected error or the necessary changes i need to get the desired output that i want.

**Comment by patrick-stephens** [comment]
We discussed this on Slack, the issue is a container misconfiguration as you're mounting to a different location to the one you're tailing.

S3 upload also requires the correct authentication to be set up which is not done for that container as far as I can see.

I would encourage you to use the Windows packages rather than the Linux container for this.
