### ISSUE TITLE
Parsing logs from a particular namespace to tenant namespaces

### ISSUE THREAD

**Issue by bartoszpyrek** [fluent/fluent-bit#8533]
## Bug Report

**Describe the bug**

I wanted to parse logs from flux-system namespace to tenant namespaces. But still these logs are only available in the flux-system namespace, to which tenants don't have permissions due to the multitenancy.

Current config:

```
[INPUT]
    Name             tail
    Tag              kube.<namespace_name>.<container_name>.<pod_name>.<docker_id>-
    Tag_Regex        (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
    Path             /var/log/containers/*.log
    Parser           docker
    DB               /var/log/flb_kube.db
    Mem_Buf_Limit    30MB
    Skip_Long_Lines  Off
    Refresh_Interval 60
    Threaded         On
    Storage.type     memrb

[FILTER]
    Name                parser
    Match               kube.flux-system.*
    Key_Name            message
    Parser              json
    Preserve_Key        True
    Reserve_Data        True
[FILTER]
    Name                rewrite_tag
    Match               kube.flux-system.*
    Rule                $namespace['extracted'] ^(.*)$ flux.$namespace['extracted'] true
    Emitter_Name        re_emitted

{{- range $namespace := $tenantNamespaces }}
[OUTPUT]
    Name                   loki
    Match                  flux.{{ $namespace }}
    Host                   loki-stack.loki.svc.cluster.local
    Port                   3100
    Tenant_id              {{ $tenantName | lower }}
    Auto_kubernetes_labels On
    Remove_keys            stream,logtag,time,log
    Drop_single_key        On
    Labels                 job=fluent-bit, node=${NODE_NAME}, container=$kubernetes['container_name'], namespace={{ $namespace }}, pod=$kubernetes['pod_name'], stream=$stream
{{- end }}
```

Is there an issue in my config and do I need to change values? I am passing the configuration helm chart from there: https://github.com/fluent/helm-charts.

**Expected behavior**

Tenants should have access to their fluxcd logs in their tenant namespaces.

**Comment by patrick-stephens** [comment]
Can you clarify what you mean and how you are deploying this config?
Which namespace do you want and does the FB deployment have access to it?

Note that namespace is part of the log filename so you could just adjust the wildcard for your tail to match it unless you mean you want all namespaces going to flux?

**Comment by bartoszpyrek** [comment]
I mean that I would like to parse logs from the flux-system namespace to the tenant-based namespaces with the logs related to the tenant application, for example: flux-system namespace -> tenantName_appName namespace. Of course, fluent-bit has access to all of these namespaces.

We are deploying the configuration via helm chart: https://github.com/fluent/helm-charts.

Could you explain your last question about adjusting the wildcard?

**Comment by patrick-stephens** [comment]
Can you be specific on the name of the log you want to parse? Saying from one namespace to another doesn't make sense to me: logs come from pods in a namespace so which namespace logs do you want to parse and which namespace are you in for FB.

The K8S standard dictates the kubelog log file naming scheme to include namespace so you can adjust your path to just tail the logs from a namespace potentially.

**Comment by bartoszpyrek** [comment]
Example log from source-controller pod in the flux-system namespace:
{"level":"info","ts":"2024-03-01T07:22:26.472Z","msg":"no changes since last reconcilation: observed revision 'xxxx'","controller":"gitrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"GitRepository","GitRepository":{"name":"tenant-git-repository","namespace":"tenant-xxx"},"namespace":"tenant-xxx","name":"tenant-git-repository","reconcileID":"xyz"}

And there are the fields available in the Loki datasource:

```
GitRepository_name	
tenant-git-repository

GitRepository_namespace	
tenant-xxx

app	
source-controller

app_kubernetes_io_name	
source-controller

cluster	
nonprod004

container	
manager

controller	
gitrepository

controllerGroup	
source.toolkit.fluxcd.io

controllerKind	
GitRepository

env	
nonprod

image	
ghcr.io/fluxcd/source-controller:v1.0.1

job	
fluent-bit

kubernetes_annotations_prometheus_io_port	
8080

kubernetes_annotations_prometheus_io_scrape	
true

kubernetes_container_hash	
ghcr.io/fluxcd/source-controller@sha256:xxxxx

kubernetes_container_name	
manager

kubernetes_docker_id	
xxxxx

kubernetes_host	
aks-default-xxxxx

kubernetes_labels_app	
source-controller

kubernetes_labels_app_kubernetes_io_name	
source-controller

kubernetes_labels_pod_template_hash	
xxxxx

kubernetes_namespace_name	
flux-system

kubernetes_pod_id	
xxxxx

kubernetes_pod_name	
source-controller

level	
info

message	
{"level":"info","ts":"2024-03-01T07:22:26.472Z","msg":"no changes since last reconcilation: observed revision 'xxxx'","controller":"gitrepository","controllerGroup":"source.toolkit.fluxcd.io","controllerKind":"GitRepository","GitRepository":{"name":"tenant-git-repository","namespace":"tenant-xxx"},"namespace":"tenant-zzz","name":"tenant-git-repository","reconcileID":"xyz"}

msg	
no changes since last reconcilation: observed revision 'main@sha1:xxxxx

name	
tenant-git-repository

namespace	
flux-system

namespace_extracted	
tenant_xxx

node	
aks-default-xxxxx

pod	
source-controller

pod_template_hash	
xxxxx

reconcileID	
xyz

region	
westeurope

stream	
stderr

ts	
2024-03-01T07:39:44.984Z
```

And the same log I would like to have in the tenant namespace, which the name is under the **namespace_extracted** parameter, but I have issue with setting up the filters and output for such log.
