### ISSUE TITLE
Input forward plugin do not support Shared_Key.

### ISSUE THREAD

**Issue by SharathSunny** [fluent/fluent-bit#8537]
Hi I have used forward plugin for my container fluentbit logs. To make the connection secure I have tried using Shared_Key, So I can see that Input forward plugin do not support Shared_key at my remote fluentbit server.
![image](https://github.com/fluent/fluent-bit/assets/59260905/c5411555-c687-43a8-a3c4-d1cac6f66584)
It is Good if it is supported.

**Comment by SharathSunny** [comment]
@leonardo-albertovich any update on this

**Comment by SharathSunny** [comment]
@endersonmaia any update on this

**Comment by edsiper** [comment]
This was recently implemented in https://github.com/fluent/fluent-bit/pull/8561 , it will be part of v3 release next week. 

Closing this as fixed.
