### ISSUE TITLE
Packages for Debian Testing (Trixie)

### ISSUE THREAD

**Issue by leonheldattoradex** [fluent/fluent-bit#8546]
**Is your feature request related to a problem? Please describe.**
Right now there are Debian packages only for oldstable (Bullseye) and stable (Bookworm): https://docs.fluentbit.io/manual/installation/linux/debian.
Debian is slow enough that a lot of people actually use testing.

**Describe the solution you'd like**
Debian packages for testing.

I could contribute if necessary (haven't found a public repo of the Debian metadata, though).

**Comment by patrick-stephens** [comment]
Packaging stuff is all here: https://github.com/fluent/fluent-bit/tree/master/packaging

There's a few bits but first step is to sort a container target to do the build (ARM64 as well): https://github.com/fluent/fluent-bit/blob/master/packaging/distros/debian/Dockerfile

Add it to the list of supported targets here: https://github.com/fluent/fluent-bit/blob/master/packaging/build-config.json

Then we can build it in CI auto-magically from that point on, and via `./packaging/build.sh -d <distro>`.

**Comment by patrick-stephens** [comment]
S3 buckets are used to host the packages and these should be automatically populated once that is done but we can verify in a staging build easily enough.

Ah Debian needs a little poke here: https://github.com/fluent/fluent-bit/blob/9d9ac68a2b45a4cedeafbf7c5aba513f494eced6/packaging/update-repos.sh#L50-L58

There will have been a recent PR to do Bookworm support you can find as well to see what it required.
