### ISSUE TITLE
Support AWS pod identity 

### ISSUE THREAD

**Issue by truongnht** [fluent/fluent-bit#8550]
**Is your feature request related to a problem? Please describe.**
Current release of fluent-bit (2.2.2) does not support pod identity way of retrieving credentials. 

**Describe the solution you'd like**
To use fluent-bit with pod-identity feature, aws sdk needs to be at required minimum version describe [here](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html)
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by voidlily** [comment]
Still affected on 3.0.4, haven't tested 3.0.6

**Comment by truongnht** [comment]
If you compare 3.0.4 and 3.0.6, there is no difference in that related area, so it should yield the same result, unfortunately

**Comment by voidlily** [comment]
https://github.com/fluent/fluent-bit/blob/master/src/aws/flb_aws_credentials_sts.c if i'm reading this right, fluent-bit implements its own AWS SDK so it might not be as straightforward as a version bump to implement this

**Comment by voidlily** [comment]
https://github.com/fluent/fluent-bit/pull/9206

**Comment by ohookins** [comment]
Super keen to get this supported.
