### ISSUE TITLE
Fluentbit opentelemetry output plugin does not format fields correctly

### ISSUE THREAD

**Issue by cb645j** [fluent/fluent-bit#8552]
This is a follow up to issue 8359.  That ticket was closed however my main issue was NOT fixed.  The TOPLEVEL traceid and spanid fields are still not being set.  If there is another PR or ticket for this work then please post it.

I have a PR open to resolve this 

https://github.com/fluent/fluent-bit/pull/8644

**Comment by cb645j** [comment]
@edsiper @sudomateo

**Comment by cb645j** [comment]
@edsiper

**Comment by cb645j** [comment]
https://github.com/fluent/fluent-bit/pull/8576

**Comment by cb645j** [comment]
Can this please be triaged

**Comment by sudomateo** [comment]
> Can this please be triaged

Hey! I've been keeping up with your work here and I just wanted to note that I'm not a Fluent Bit maintainer. I'm primarily a user of Fluent Bit and a light contributor. I'm happy to compile and test code though to help where I can.

**Comment by cb645j** [comment]
@sudomateo Thank you, Please take a look at my pull and test it out if you can. I was able to test and get it working but if you can also test in your scenrio that would be great. I have added support for spanid, traceid, severitytext, and severitynumber. So those are the ones you can try.  I havnt yet decided how we would want to handle adding attributes so if you have suggestions then that would be great.
