### ISSUE TITLE
use fluent-bit collecting log to VictoriaLogs, _stream: {} is null

### ISSUE THREAD

**Issue by dw130** [fluent/fluent-bit#8560]
Describe the bug
use fluent-bit to collect log to VictoriaLogs in debug mode

check VictoriaLogs debug log, 
receive request body is 

query arg: {"_msg":"xxxxxxx","_stream":"{}","_time":"2024-03-05T11:41:28.547184Z"}

_stream is {}

How to cofigure to fill the _stream field with  log path name?
Thanks !

fluent-bit.conf is
[INPUT]
name tail
tag log
Parser json
Path /home/log/*.debug.log

[OUTPUT]
Name http
Match *
host xx.xx
port 9200
uri /insert/jsonline?_stream_fields=stream&_msg_field=log&_time_field=date&debug=1
format json_lines
json_date_format iso8601

To Reproduce
use fluent-bit to collect log to VictoriaLogs in debug mode

Version
fluent-bit --version Fluent Bit v2.2.2
VictoriaLogs latest

**Comment by patrick-stephens** [comment]
What does stdout output show the actual parsed data as? If it's not parsing a _stream key then that's why - you can use other filters to copy/move/rename keys if the data from the input log is elsewhere. Is the log actually JSON?

**Comment by valyala** [comment]
@dw130 , the `_stream` field is automatically populated by [VictoriaLogs](https://docs.victoriametrics.com/victorialogs/) during data ingestion, according to the list of [log stream fields](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) specified via `_stream_fields` query arg at the `uri` option. See [these docs](https://docs.victoriametrics.com/victorialogs/data-ingestion/fluentbit/#http) for details.

**Comment by agup006** [comment]
Hey @valyala should we add a VictoriaLogs section within our Fluent Bit docs, similar to Observe / Dash0 / Dynatrace?
