### ISSUE TITLE
S3 Plugin: support for zstd compression

### ISSUE THREAD

**Issue by cdancy** [fluent/fluent-bit#8598]
Piggy backing off of [ISSUE 8099](https://github.com/fluent/fluent-bit/issues/8099): we'd like to see support for zstd compression within the S3 plugin. This can result in much smaller file-part size thereby bringing down costs for workloads where there is a potential problem.

I can attempt to take on initial work here if you all think this could be done I would just need some pointers on where to get started.

Tagging some more well known developers that I've worked with and/or talked to in the past to get the conversation started:

@edsiper @patrick-stephens @PettitWesley

**Comment by patrick-stephens** [comment]
I can't help with implementation I'm afraid but packaging wise make sure to update any extra dependencies required for a build of each target in the container definitions in `./packaging/distros/`.

**Comment by cdancy** [comment]
Never got the time to circle back and look into things here. Would love to have this feature though.
