### ISSUE TITLE
Document Retry_Limit for output plugins

### ISSUE THREAD

**Issue by Globegitter** [fluent/fluent-bit#860]
**Is your feature request related to a problem? Please describe.**
As a note, I have already asked on Slack but not received any response, so posting here. There is very little mention of `Retry_Limit` in the docs and nothing at all in the output plugin sections. It would be great to have that documented in all plugins that support that.

And further does the HTTP output plugin support it? I could not find any mention of that anywhere in issues or the docs.

**Comment by edsiper** [comment]
Sorry about the missing docs. Retry_Limit is applicable to all output plugins, you can do:

- Retry_Limit  N  (where N is a number >= 1)
- Retry_Limit  False (no limits, retry forever)

**Comment by edsiper** [comment]
Documented here: 

https://docs.fluentbit.io/manual/configuration/scheduler

thanks

**Comment by vinoth3105** [comment]
How to add retry input plugin http pull in "on_timer" method, could you pls help on that..
