### ISSUE TITLE
fluent-bit keeps complaining about parser not set [in_syslog] plugin

### ISSUE THREAD

**Issue by outofsight** [fluent/fluent-bit#8607]
## Bug Report

**Describe the bug**
fluent-bit keeps complaining about parser not set [in_syslog] plugin and refuse to start.

**To Reproduce**
- Start docker container with the sample config for input syslog in the documentation.

**Sample conf configuration used**
```
[SERVICE]
    Flush               1
    Log_Level           info
    # Parsers_File        parsers.conf

[INPUT]
    Name                syslog
    Path                /tmp/in_syslog
    Buffer_Chunk_Size   32000
    Buffer_Max_Size     64000
    Receive_Buffer_Size 512000

[OUTPUT]
    Name   stdout
    Match  *
```

**Log Output**
```
Fluent Bit v2.2.2
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

____________________
< Fluent Bit v2.2.2 >
 -------------------
          \
           \
            \          __---__
               __--( /     \ )XXXXXXXXXXX\v.
             .-XXX(   O   O  )XXXXXXXXXXXXXXX-
            /XXX(       U     )        XXXXXXX\
          /XXXXX(              )--_  XXXXXXXXXXX\
         /XXXXX/ (      O     )   XXXXXX   \XXXXX\
         XXXXX/   /            XXXXXX   \__ \XXXXX
         XXXXXX__/          XXXXXX         \__---->
 ---___  XXX__/          XXXXXX      \__         /
   \-  --__/   ___/\  XXXXXX            /  ___--/=
       \-\/XXX\ XXXXXX                      /XXXXX
         \XXXXXXXXX   \                    /XXXXX/
          \XXXXXX      >                 _/XXXXX/
            \XXXXX--__/              __-- XXXX/
             -XXXXXXXX---------------  XXXXXX-
                \XXXXXXXXXXXXXXXXXXXXXXXXXX/
                  ""VXXXXXXXXXXXXXXXXXXV""

[2024/03/20 10:38:11] [ info] [fluent bit] version=2.2.2, commit=eeea396e88, pid=1
[2024/03/20 10:38:11] [ info] [storage] ver=1.5.1, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/03/20 10:38:11] [ info] [cmetrics] version=0.6.6
[2024/03/20 10:38:11] [ info] [ctraces ] version=0.4.0
[2024/03/20 10:38:11] [ info] [input:syslog:syslog.0] initializing
[2024/03/20 10:38:11] [ info] [input:syslog:syslog.0] storage_strategy='memory' (memory only)
[2024/03/20 10:38:11] [error] [in_syslog] parser not set
[2024/03/20 10:38:11] [error] [lib] backend failed
[2024/03/20 10:38:11] [error] [input:syslog:syslog.0] could not initialize plugin
[2024/03/20 10:38:11] [error] failed initialize input syslog.0
```

** Alternative YAML configuration tried**
```
env:
    flush_interval: 5

service:
    flush:        ${flush_interval}
    log_level:    debug
    http_server:  on
    http_port:    2020
    # parsers_file: /fluent-bit/etc/parsers.confg

pipeline:
  inputs:
    - name: http
      tag: http
      port: 8080

    - name: syslog
      tag: syslog
      mode: udp
      port: 514
      parser: syslog-rfc5424
  
  outputs:
    - name: stdout
      match: syslog
    - name: stdout
      match: http

```

**Note**
- Parser property is supposed to be optional but even explicitely adding doesn't solve
- When including Parser_File fluentbit complain about not finding file parsers.conf; tried also with path /fluent-bit/etc/parsers.conf.

**Your Environment**
* Version used: as above
* Configuration: as above
* Environment name and version: Docker 20
* Server type and version:
* Operating System and version: Linux
* Filters and plugins: as above

**Additional context**
I just want to collect syslog messages and sento to some backend (Loki)

**Comment by lecaros** [comment]
if the output you shared is from the first config, then the error makes sense. You must set the parser in the input

**Comment by outofsight** [comment]
> if the output you shared is from the first config, then the error makes sense. You must set the parser in the input

syslog-rfc5424 parser is supposed to be builtin. Parser property is supposed to be optional. Uncommenting show a file not found.

**Comment by ruben-chainalysis** [comment]
I know this one was closed, but I'm hitting the same issue. Specifying the parser makes no difference, tried with the documented parsers `syslog-rfc5424`, also just `rfc5424` to check and they both yield the `parser not set` error before crashing.

**Comment by outofsight** [comment]
> I know this one was closed, but I'm hitting the same issue. Specifying the parser makes no difference, tried with the documented parsers `syslog-rfc5424`, also just `rfc5424` to check and they both yield the `parser not set` error before crashing.

Don't remember well, but it seems I had to copy parsers.builtin.conf (from docker image?) in the same mapped directory of my config.yml

**Comment by evnct** [comment]
Could be more clear about this in the documentation. Would be better if there was a specific way to skip the parsing. In my case I would like to skip parsing in Fluentbit, because I want to to use Grok in my OpenSearch pipeline.

**Comment by evnct** [comment]
> Don't remember well, but it seems I had to copy parsers.builtin.conf (from docker image?) in the same mapped directory of my config.yml

@outofsight No such file in `fluent-bit/etc/`. Could you give an example on how you got it working?
