### ISSUE TITLE
Document buffering

### ISSUE THREAD

**Issue by Globegitter** [fluent/fluent-bit#861]
**Is your feature request related to a problem? Please describe.**
Again I asked in Slack but no response so posting here: There is some very high level introduction to buffering here: https://docs.fluentbit.io/manual/getting_started/buffer but I have not been able to find anything in the docs on how to actually configure it. I have found this issue: https://github.com/fluent/fluent-bit/issues/328 that does explain how to set it up via cli flags, but is it also possible to activate that in the config file?

I would be happy to provide more documentation for it if I know myslef if it is just possible via cli flags or also via the config file.

**Comment by edsiper** [comment]
hi @Globegitter 

the current buffering (file system) support is being deprecated and not longer maintained. A new one is coming up that we aim to have a preview-release of it at the end of 2018.

regards,

**Comment by gauravcdac** [comment]
I have used the fluentbit 0.14.9 version and I am using file buffering by using Buffer_path option in services plugin. I am able to store logs in specified directory but the logs are not getting transferred to destination.
Please suggest me something.
