### ISSUE TITLE
Add parameter Topic_Regex for kafka input plugin

### ISSUE THREAD

**Issue by Sanchez1998** [fluent/fluent-bit#8611]
**Problem with dynamic reading kafka topics in kafka input plugin**

**It will be great, if we will have opportunity to read messages from all kafka topics (*), or from topics with custom pattern. Now we only have one parameter  topics, with description: Single entry or list of topics separated by comma (,) that Fluent Bit will subscribe to.**

**As a solution i see adding a new parameter, something like Topic_Regex.**

**Comment by Ytipytiman** [comment]
I have the same issue. It will be great if we will have it.
