### ISSUE TITLE
run-macos-unit-tests randomly failing

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-bit#8617]
## Bug Report

**Describe the bug**
When building my PR, the unit tests for the run-macos-unit-tests are failing. Please see:
https://github.com/fluent/fluent-bit/actions/runs/8375313586/job/22934478507#step:4:4326
https://github.com/fluent/fluent-bit/actions/runs/8373377486/job/22928080387#step:4:4341
https://github.com/fluent/fluent-bit/actions/runs/8359387867/job/22884653474#step:4:4321

It looks like this is not only the case for my PR: 
https://github.com/fluent/fluent-bit/actions/runs/8358991258
https://github.com/fluent/fluent-bit/actions/runs/8358991258
https://github.com/fluent/fluent-bit/actions/runs/8260096631
https://github.com/fluent/fluent-bit/actions/runs/8275956406

The last commit in master branch with green tests I could find was: 9a173d0b32d288c022ec751510dd929edde04c95

@patrick-stephens

**Comment by patrick-stephens** [comment]
I think there's some known issues with race or similar problems on MacOS, they've always had issues but we explicitly ignored them until recently so taking a while to work through then.

The commit you linked is a workflow one so doesn't run unit tests, it runs a dummy of the same name to meet the required checks on PRs.

**Comment by drbugfinder-work** [comment]
Thanks for the explanation @pat. I just wasn't sure how tolerant you are to failing unit tests when merging a PR. I tried to run the PR tests several times but could not get a fully green build because of that issue (so I wasn't sure if that is the reason why the PR is not approved/merged).

**Comment by patrick-stephens** [comment]
Yeah it would be better to have fully green CI but I think there is another issue on it.
