### ISSUE TITLE
type_converter does not convert string 0 to integer 0

### ISSUE THREAD

**Issue by rinaldou** [fluent/fluent-bit#8632]
## Bug Report

**Describe the bug**

Tried to convert with type_converter string '0' to 0 integer. But that returns an error.

**To Reproduce**
[INPUT]
  Name    dummy
  Dummy   {"teste": "0"}

[FILTER]
  Name    type_converter
  Match   *
  str_key teste teste_int int

[OUTPUT]
  Name    stdout
  Match   *
```
Mar 23 02:06:46 pc-1578775 fluent-bit[201134]: [0] dummy.0: [[1711170405.703057957, {}], {"teste"=>"0"}]
Mar 23 02:06:46 pc-1578775 fluent-bit[201134]: [2024/03/23 02:06:46] [error] flb_typecast_conv_str: convert error. input=0
Mar 23 02:06:46 pc-1578775 fluent-bit[201134]: [2024/03/23 02:06:46] [error] [filter:type_converter:type_converter.0] failed to convert. key=teste
```
- Steps to reproduce the problem:
Run the type_converter filter and the data is string '0'

**Expected behavior**

I expect that it converts to integer zero, not send an error.

**Screenshots**

**Your Environment**

* Version used: 2.2.2
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

I need to convert the field to integer, but when the data is '0', it gives an error.

**Comment by nokute78** [comment]
Thank you for reporting.
I sent a patch https://github.com/fluent/fluent-bit/pull/8636 .
