### ISSUE TITLE
Upstream load balancing with kubernetes headless service

### ISSUE THREAD

**Issue by Misterhex** [fluent/fluent-bit#864]
Does the new upstream feature works with kubernetes headless service? How could we check where is fluentbit sending to which pod ip?

Thanks for the help

```
[Upstream]
name forward_balancing

[Node]
Host headless-service.cluster.local <- resolve to multiple A records of fluentd pods
Port 24434
```

**Comment by edsiper** [comment]
I am not familiar with headless service concept in Kubernetes, would you please elaborate?

Note that the upstream feature (balance connections to different nodes) is only available in Forward output plugin for now.

**Comment by Misterhex** [comment]
Hi @edsiper , headlesss service in kubernetes is just a dns name that resolve multiple A records.

**Comment by Misterhex** [comment]
Tried in my own lab setup and confirmed the followings load balance correctly.

1) upstream server with single node hostname 
that resolves multiple ip. ( headless service in k8 )
2) forward with hostname that resolves multiple ip

**Comment by bobykus31** [comment]
Does it failover to second ip  if fluentd on one of ip addresses not responding?

**Comment by ZPerling** [comment]
> 

`out_forward with hostname to k8 service load balancer without session affinity.`

I found that in this case a long connection is created between flunt-bit and fluentd, the connection is not reload balanced after it is established, and if a new instance of fluntd is expanded, the traffic is not forwarded to the new instance

@Misterhex
