### ISSUE TITLE
Incorrect dockerfile in hub.docker.com

### ISSUE THREAD

**Issue by wfernandes** [fluent/fluent-bit#865]
## Bug Report

The [docker file on docker hub](https://hub.docker.com/r/fluent/fluent-bit/~/dockerfile/) is incorrect.

- The `COPY` instruction is incorrect. 
  ```
  # Configuration files
  COPY fluent-bit.conf \
     parsers.conf \
     parsers_java.conf \
     parsers_mult.conf \
     parsers_openstack.conf \
     parsers_cinder.conf \
     /fluent-bit/etc/
  ```
  The above files should be prepended with `conf/`

When we copied the file locally and tried to build the image, we got an error because the copy path was incorrect.

**Comment by edsiper** [comment]
You have to clone the git repository fluent/fluent-bit-docker-image and get into the 0.14 branch:

```
https://github.com/fluent/fluent-bit-docker-image/tree/0.14
```

that's from where the Dockerfile comes from with further config files.
