### ISSUE TITLE
Add logo to list of companies using fluent-bit

### ISSUE THREAD

**Issue by sh-cho** [fluent/fluent-bit#8653]
I'm working at @kakao, messaging application company in South Korea.

We (especially messaging server) uses fluent-bit mainly for producing application logs.

~This is our logo (from wikipedia)~ -> I'll try to retrieve original logo file from person in charge.

Thanks!

**Comment by patrick-stephens** [comment]
Please provide any style guidelines and other commercial/marketing guidance along with confirming official permission to use it.

**Comment by sh-cho** [comment]
I'll try to ask later.
