### ISSUE TITLE
[question] Error code of fluent-bit

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#87]
In flb_error.h, some defines are octal  (not decimal) 
Is it intentional?
If not, I think there is a risk of overlap in the future.

Note:
As you know, the number which starts '0' is octal in C language.
For example, this value is 8 (not 10).
``` C
#define FLB_ERR_CFG_FILE             010
```

**Comment by edsiper** [comment]
you are right, that's wrong, they should be prefixed with 0xN for hexa or keep it as decimal.

**Comment by nokute78** [comment]
Thanks.
I sent a patch (#88)

**Comment by edsiper** [comment]
#88 merged. thanks.
