### ISSUE TITLE
Forward input + multi-line parser consumes more than 100% CPU and lost of enriched data

### ISSUE THREAD

**Issue by quanghungb** [fluent/fluent-bit#8702]
## Bug Report

During the evaluation of Fluent Bit, I am trying to have the following architecture (critical for our use case): 
|fluent-bit-shipper| -> |fluent-bit-aggregator| -> |final destination|

But I got those 2 blocking issues: 
* CPU high usage (more than 100%) 
* Lost of enriched data (that have been done at the source)

Everything (configurations, instructions to reproduce, observations) provided here: 
- v2.2: https://github.com/quanghungb/fluent-bit-forward
- v3: https://github.com/quanghungb/fluent-bit-forward/tree/fluent-bit-v3.0.0

(I also shared this issue with Eduardo and Anurag as they asked)

Thanks for your help & feedback

**Comment by drbugfinder-work** [comment]
Maybe related: https://github.com/fluent/fluent-bit/pull/8473

**Comment by quanghungb** [comment]
@drbugfinder-work FYI I just tried with the latest version `3.0.2` and still observed the same issues :(

**Comment by quanghungb** [comment]
@drbugfinder-work FYI I tried the newest version 3.0.2 and can observe the same issues:
* CPU usage growing up over 100% after few moment
* the enriched data are still missing 

Regarding your question about the multiline parser/regex, the issues appear only with forward input, because with the tail input everything is working well

**Comment by quanghungb** [comment]
hey @drbugfinder-work I was running the same scenario (with the latest 3.0.2) on my Macbook Air (much much less power than my workstation) and did not see the issues. So I assumes that on my Macbook Air the throughput is less important so it does not flood the aggregator forward input.
