### ISSUE TITLE
update v3.x docker to find /fluent-bit/etc/fluent-bit.yaml

### ISSUE THREAD

**Issue by fulldeck** [fluent/fluent-bit#8710]
The latest docker v3.x of fluent-bit is still using fluent-bit.conf

CMD  /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf

We need a new docker container to pick up the fluent-bit.yaml

CMD /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.yaml

Or 

Maybe fluent-bit by default would look for fluent-bit.conf or fluent-bit.yaml in the fluent-bit folder path where the conf files are found.

**Comment by fulldeck** [comment]
I tried mapping the fluent-bit.conf to the fluent-bit.yaml file in the docker compose file and the process is looking for the classic file configuration


docker-compose
```
    volumes:
         - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
```

output error:
```
[2024/04/14 08:51:25] [error] [config] error in /fluent-bit/etc/fluent-bit.conf:2: undefined value - check config is in valid classic format
[2024/04/14 08:51:25] [error] configuration file contains errors, aborting.
```

**Comment by quanghungb** [comment]
+1

I got the same issue. So I have to run the containers individually with the mounted config file (https://github.com/quanghungb/fluent-bit-forward/tree/fluent-bit-v3.0.0?tab=readme-ov-file#upgrade-to-v3)

**Comment by opencmit2** [comment]
I recommend overriding CMD when starting a container, as it allows for the use of various configuration files, requiring the inevitable priority conflicts to be resolved.

**Comment by fulldeck** [comment]
Well that was excellent, thank you.
I added the "command" argument and it read the yaml config file now. 

  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit:latest
    restart: always
    hostname: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.yaml
    volumes:
      - ./fluentbit:/fluent-bit/etc
      - ./certs:/etc/ssl/certs/      
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5170:5170"

**Comment by fulldeck** [comment]
Thank you.

We may want to add this to the doc pages.

Cheers
