### ISSUE TITLE
es index use record-accessor

### ISSUE THREAD

**Issue by chunxingque** [fluent/fluent-bit#8719]
## Bug Report

**Describe the bug**
I want to use the JSON parsed **project** field as the index name. I referred to the method used by record-accessor, but it did not take effect, I checked the ES index and found that the log uploaded the **$project** index.
Is there a solution to this?
referred：https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/record-accessor

fluent-bit.conf
```
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf

[INPUT]
    name         tail
    path         /var/Log/*.log
    Parser       nlog_json

[OUTPUT]
    Name  stdout
    Match *

[OUTPUT]
    Name  es
    Match *
    Host  192.168.15.115
    Port  9200
    HTTP_User  elastic
    HTTP_Passwd 123456
    Index $project
```
parsers.conf
```
[PARSER]
    Name   nlog_json
    Format json
    Time_Key nlogdate
    Time_Format %Y-%m-%d %H:%M:%S.%L
    Time_Keep   On
```

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{ "project": "log_json", "nlogdate": "2024-04-16 00:07:06.2160", "level": "INFO", "message": {"RequestBody":"","ResponseBody":null,"ExcuteStartTime":"2024-04-16 00:07:06.215","ExcuteEndTime":"2024-04-16 00:07:06.215","UserIP":"192.168.10.115","UserName":"no token api"}, "counter": "50045", "callsite": "HSCM.Host.Middleware.RequestLoggerMiddleware.Invoke", "callsite_linenumber": "86", "request_method": "GET", "url": "http://192.168.10.121/" }
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: fluent-bit:3.0.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Comment by ns-kdalsania** [comment]
We are having similar issue in opensearch output plugin. we are not able to use dynamic variable for index field.
