### ISSUE TITLE
systemd input plugin is missing while building on a docker container

### ISSUE THREAD

**Issue by isshwar** [fluent/fluent-bit#8728]
Hi,

I have an automated gitlab pipeline to build fluent-bit in a docker container. but after the build, fluent-bit binary is missing systemd input plugin. Below is the script on gitlab pipeline that I use to build the binary. Is it because of the docker container missing journald installed?

image: debian:buster-slim
  script:
    - apt-get update -y && apt-get install -y build-essential cmake flex bison libyaml-cpp-dev git wget libssl-dev libyaml-dev curl
    - wget https://github.com/fluent/fluent-bit/archive/refs/tags/v${FLUENT_BIT_VERSION}.tar.gz
    - tar -xvzf v${FLUENT_BIT_VERSION}.tar.gz
    - cd fluent-bit-${FLUENT_BIT_VERSION}/build && cmake .. && make
    - mv ${CI_PROJECT_DIR}/fluent-bit-${FLUENT_BIT_VERSION}/build/bin/fluent-bit ${CI_PROJECT_DIR}/habitat/fluent-bit
    - echo "${FLUENT_BIT_VERSION}" > ${CI_PROJECT_DIR}/habitat/pkg_version.txt

Also, tried building on debian 12, still the binary file is missing systemd input plugin
- cloned latest version from github
- installed CMake >= 3.12,Flex,Bison >= 3,YAML headers,OpenSSL headers
- cd build/ && cmake .. && make

Any help is appreciated

Thanks

**Comment by patrick-stephens** [comment]
You are missing dependencies for systemd - dev package.

I would recommend just looking at how the Dockerfile here does it: https://github.com/fluent/fluent-bit/blob/master/dockerfiles/Dockerfile

I'm closing as not a Fluent Bit issue.
