### ISSUE TITLE
Unexpected behaviour for metrics after the migration to 3.0.1

### ISSUE THREAD

**Issue by kzonov** [fluent/fluent-bit#8729]
## Bug Report

Hello dear Fluend/Fluentbit team.

We recently migrated from 2.1.9 to 3.0.1 and noticed that some of our metrics started misbehaving.
In particular we used to use the `fluentbit_input_bytes_total` being at 0 as an indication that the ingestion stopped. Now it is at 0 almost all the time, but sometime it gets up. At the same time we see that Fluentbit processing works well as expected, and the `fluentbit_output_proc_bytes_total` is about at the same level as before. As if we don't read anything, but keep writing as before.

Here is an illustration of the behaviour:
<img width="751" alt="image" src="https://github.com/fluent/fluent-bit/assets/701016/0b7ea797-cb7d-4f67-8e10-4ee366ee24ec">
Around 16:00 we performed the upgrade and as we can see, the Input metric slightly changed and later on went completely to 0 for all Fluentbit pods, while the Output metric is still on the expected level.
A similar situation is with the output records metric:
<img width="750" alt="image" src="https://github.com/fluent/fluent-bit/assets/701016/1e161962-7084-4808-9196-8e41adaed9a7">

The queries we're using for these graphs are:
`sum by(pod, name) (rate(fluentbit_input_bytes_total{env="$env", name!="loki_standard_rewrite_kube"}[1m]))`
and
`sum by (pod, name) (rate(fluentbit_input_records_total{env="$env", name!="loki_standard_rewrite_kube"}[1m]))`

**Expected behavior**
We expect the metric to function as before, showing us how much data do we read from the sources, to be able to determine if a congestion happens that leads to the blockage of the reading path.

**Your Environment**
* Version used: 3.0.1
* Configuration:
Here are some parts of the configuration:
```
    [SERVICE]
      Flush         1
      Log_Level     warn
      Daemon        off
      Parsers_File  parsers.conf
      HTTP_Server   On
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020

    [INPUT]
      Name                systemd
      Tag                 systemd.*
      Path                /var/log/journal
      Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
      DB                  /var/log/flb_kubelet.db
      Read_From_Tail      true
      Mem_Buf_Limit       50MB

    [INPUT]
      Name               tail
      Tag                kube.*
      Path               /var/log/containers/*.log
      multiline.parser   docker, cri
      DB                 /var/log/flb_kube.db
      Mem_Buf_Limit      50MB
      Skip_Long_Lines    On
      Refresh_Interval   10
      Ignore_Older       24h
      Rotate_Wait        60

    [OUTPUT]
      Name                    loki
      Match                   *
      labels                  env={{ $.Values.loki.environment }}, job=$job, namespace=$kubernetes['namespace_name'], instance=$kubernetes['pod_name']
      host                    {{ $.Values.loki.host }}
      port                    443
      tls                     {{ if $.Values.loki.useTLS }}On{{ else }}Off{{ end }}
      tenant_id               standard
      Retry_Limit             10

    [OUTPUT]
      Name                opensearch
      Match               *
      Host                {{ $.Values.opensearch.host }}
      Port                {{ $.Values.opensearch.port }}
      tls                 On
      HTTP_User           {{ $.Values.opensearch.user }}
      HTTP_Passwd         ${FLUENT_OPENSEARCH_PASSWORD}
      Logstash_Format     On
      Logstash_Prefix     logs-others
      Logstash_Prefix_Key index_name
      Replace_Dots        On
      Trace_Error         Off
      net.dns.mode        TCP
      Retry_Limit         2
```

* Environment name and version (e.g. Kubernetes? What version?): Kubernetes

Once again, we can confirm that the logs flow through, even at the times when the metric reports as 0. We didn't make any changes neither to the Fluentbit configuration nor to the Monitoring part, so the problem is isolated precisely to the version upgrade.

Thank you, hoping for your support!

**Comment by alexku7** [comment]
I also have this issue :(

**Comment by alexku7** [comment]
is it fixed here ?

https://github.com/fluent/fluent-bit/issues/9086

**Comment by alexku7** [comment]
still exists in 3.1.7 :(

But i think I eliminated the scenario

In my case the metric is zero only if I use a multiline parser. If I remove the multiline parsing, everything is ok.

Just to clarify, the logs are flowing, other input plugins have correct metrics byt only the tail has zero.
Since we also use it for aleting and monitoring we can"t upgrade to 3.x  :((

**Comment by mindw** [comment]
I can confirm the following:
* reproduced in 3.1.9
* **last working version is 2.1.10** - All 2.2.x versions have the above behaviour.
* internal metrics are also 0.
* pipeline has both `rewrite_tag` and `multiline` filter plugins configured.
* It's possible that any re-emitted records are not counted for the relevant input.
Hope this helps.
