### ISSUE TITLE
Add sane metadata to debian package repo

### ISSUE THREAD

**Issue by pluhmen** [fluent/fluent-bit#8730]
**Is your feature request related to a problem? Please describe.**
At the moment `apt-cache policy` returns this repo metadata

```
 500 https://packages.fluentbit.io/debian/bullseye bullseye/main amd64 Packages
     release o=bullseye bullseye,a=bullseye,n=bullseye,l=bullseye bullseye,c=main,b=amd64
     origin packages.fluentbit.io
```

**Describe the solution you'd like**
Metadata should be specific for fluent-bit releases

```
 500 https://packages.fluentbit.io/debian/bullseye bullseye/main amd64 Packages
     release o=packages.fluentbit.io,a=bullseye,n=bullseye,l=fluentbit,c=main,b=amd64
     origin packages.fluentbit.io
````
or similar

**Additional context**
With the current metadata provided it's (nearly) impossible to configure unattended-upgrades as the release origin and label are unspecific and can not be distinguished from other repo metadata.

**Comment by patrick-stephens** [comment]
Probably a case of updating here: https://github.com/fluent/fluent-bit/blob/master/packaging/update-apt-repo.sh

The packaging process is a bit convoluted sometimes as it had to cope with the old bare metal server then the transition to an S3 bucket but keeping both going for a while. It probably needs some love and a tidy up if you feel like submitting some PRs.
