### ISSUE TITLE
help with utf8_copyright files

### ISSUE THREAD

**Issue by vchhasatia** [fluent/fluent-bit#8746]
Hello fluent-bit team,

I was wondering what licenses utf8_copyright.json, utf8_copyright.mp and utf8_copyright.txt files in https://github.com/fluent/fluent-bit/tree/master/tests/internal/data/pack are under?

I am bit confused as these 3 files have "(c)" as copyright.

**Comment by patrick-stephens** [comment]
I think you're confusing things here - those are test files to verify processing of the copyright symbol. They are under the same licence and copyright as Fluent Bit, they are explicitly testing processing of a copyright symbol though so must include it.

**Comment by vchhasatia** [comment]
Thank you Patrick-Stephens for clarification!
