### ISSUE TITLE
Managed identity for azure kusto output plugin

### ISSUE THREAD

**Issue by mansi1597** [fluent/fluent-bit#8763]
I am looking for a solution to send logs from fluent bit container to kusto. Currently, we use client id and secret. We are trying to move away from secret. Is there any way we can atleast move to certificate instead of secret if managed identity solution is going to take time?

**Comment by patrick-stephens** [comment]
Probably a duplicate of #7525 (similar to https://github.com/fluent/fluent-bit/issues/8249#issuecomment-1961628658)

**Comment by mansi1597** [comment]
There are multiple duplicates but none of them are actively being addressed

**Comment by patrick-stephens** [comment]
Contribution would be greatly welcomed, as it is OSS every update requires someone to contribute a PR so if you have the time and/or an environment to test it in (getting Azure access costs as well for example) to donate that would speed it up.
