### ISSUE TITLE
Impossible to ingest timestamp from nested json

### ISSUE THREAD

**Issue by tumd** [fluent/fluent-bit#8777]
**Describe the bug**

Similar to https://github.com/fluent/fluent-bit/issues/1013, I try to parse a timestamp field located under a nested key in a json structured log.
My particular logs are from MongoDB. Please see it's [documentation](https://www.mongodb.com/docs/manual/reference/log-messages/) for more example logs.

**To Reproduce**

Example log that should be possible to parse;
```json
{"t":{"$date":"2020-05-01T15:16:17.180+00:00"},"s":"I", "c":"NETWORK", "id":12345, "ctx":"listener", "msg":"Listening on","attr":{"address":"127.0.0.1"}}
```

```
[PARSER]
  Name   mongodb-json
  Format json
  Time_Key t.$date
  Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```
```
[SERVICE]
  Log_Level debug
  Parsers_File parsers.conf

[INPUT]
  Name tail
  Path mongos.log
  Parser mongodb-json
  Read_from_Head true
  Exit_On_Eof true

[OUTPUT]
  Name   stdout
  Match  *
```

**The problem is;** The field containing the timestamp is impossible to parse as such. I have been unable to find _any_ working workaround to get this field parsed.

Please either add support to use `Time_Key` with nested fields, or suggest a reasonable & working workaround.

I have tried;
 * to set the Parser `Time_Key` in various different variations to suit the nested key; 
   * `Time_Key t.$date`
   * `Time_Key t.\$date`
   * `Time_Key "t.$date"`
   * `Time_Key "t.\$date"`
   * `Time_Key t.$$date`
   *  ...
 * to use the "Record Accessor" in the parser to reach the timestamp. Like so; `Time_Key $t.["$date"]`.
 * a whole bunch of different nest-filter variations, including lift `$date` from `t` without luck.
 * to parse the `t` key as json with another parser-filter:
 ```
[PARSER]
  Name   json
  Format json

[PARSER]
  Name   mongodb-json
  Format json
  Time_Key $date
  Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```
```
[INPUT]
  Name tail
  Path mongos.log
  Parser json
  Read_from_Head true
  Exit_On_Eof true

[FILTER]
  Name parser
  Parser mongodb-json
  Key_name t
```

Initially I figured that the key-_name_ `$date` containing a `$` was the issue, but it seem not to be.
A manually crafted log-entry where the `t`-key have been flatted out works great with bellow parser;
```json
{"$date":"2020-05-01T15:16:17.180+00:00","s":"I", "c":"NETWORK", "id":12345, "ctx":"listener", "msg":"Listening on","attr":{"address":"127.0.0.1"}}
```
```
[PARSER]
  Name   mongodb-json
  Format json
  Time_Key $date
  Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```

**Expected behavior**

That the nested `t.$date` may be possible to use as a timestamp field.

**Screenshots**

**Your Environment**

* Version used: v3.0.3
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): Nah
* Server type and version: GCP e2-medium
* Operating System and version: Debian GNU/Linux 11 (bullseye)
* Filters and plugins: Se above

**Additional context**

**Comment by vanabbott** [comment]
@tumd did you ever find a workaround for this? I'm running into a similar issue parsing mongo logs

**Comment by tumd** [comment]
> @tumd did you ever find a workaround for this?

Unfortunately, no. But my best bet is to try to use lua to manipulate/flatten/rename, or even parse the timestamp-field.
Please let me know if you find a solution! :)

**Comment by vanabbott** [comment]
> Please let me know if you find a solution! :)

@tumd I ended up using fluentd's record_transformer to first add the value in "t.$date" to a new "@timestamp" field, then removed the entire "t" field from the log, then was able to parse on the new @timestamp field.

`<filter application.mongo>
  @type record_transformer
  enable_ruby
  <record>
    @timestamp ${record["t"]["$date"]}
  </record>
  remove_keys t
</filter>

<filter application.mongo>
  @type parser
  key_name @timestamp
  reserve_data true
  remove_key_name_field true
  <parse>
    @type time
    time_format %iso8601
  </parse>
</filter>
`

**Comment by sriharip316** [comment]
Parse the mongodb log, flatten it and parse the time field again.

```
[INPUT]
    Name                tail
    Path                mongodb.log
    Parser              mongodb_log
    Tag                 mongodb.log

[FILTER]
    Name            nest
    Match           mongodb.log
    Operation       lift
    Nested_under    t

[FILTER]
    Name          parser
    Match         mongodb.log
    Key_Name      $date
    Parser        mongodb_log_ts
    Reserve_Data  true
```

```
[PARSER]
    Name            mongodb_log
    Format          json

[PARSER]
    Name            mongodb_log_ts
    Format          regex
    Regex           ^(?<ts>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}\+\d{2}:\d{2})$
    Time_Key        ts
    Time_Format     %Y-%m-%dT%H:%M:%S.%L%z
```

**Comment by pitch-d** [comment]
thank you @sriharip316 
you saved my day 🙏
