### ISSUE TITLE
$dd_tags not interpreted by datadog properly

### ISSUE THREAD

**Issue by dudo** [fluent/fluent-bit#8782]
### Describe the bug
I'm doing some fun lua scripting, and using the `$dd_tags` var to inject env and version tags into datadog output. 

If I set `dd_tags     $dd_tags`, the tags within datadog seem malformed, and I end up with a `_dd_tags` top level tag.

Whereas, if I hardcode the values `dd_tags     env:d,version:1234`, it works as expected, with top level `env` and `version` tags.

In both scenarios, I see "attributes" on the log with dd_tags as expected. Something seems amiss with the way `$dd_tags` is being evaluated, maybe?

### Kubernetes configmap

```yaml
append_dd_tags.lua: |
  function append_tags(tag, timestamp, record)
      local tags = {}

      -- Conditionally add environment tag
      if record["env"] then
          table.insert(tags, "env:" .. record["env"])
          record["env"] = nil
      end

      -- Conditionally add version tag
      if record["version"] then
          table.insert(tags, "version:" .. record["version"])
          record["version"] = nil
      end

      -- Construct the dd_tags field
      record["dd_tags"] = table.concat(tags, ",")
      return 1, timestamp, record
  end

fluent-bit.conf: |
  ...
  @INCLUDE filter-lua.conf
  @INCLUDE output-datadog.conf

filter-lua.conf: |
  [FILTER]
      Name   lua
      Match  *
      script /fluent-bit/etc/append_dd_tags.lua
      call   append_tags

output-datadog.conf: |
  [OUTPUT]
      Name        datadog
      Match       *
      ...
      dd_tags     $dd_tags
```

### Version

fluent/fluent-bit: 2.0.14
datadog/agent: 7.52.0

**Comment by dudo** [comment]
So... I don't think `$dd_tags` is a thing. ChatGPT led me astray. I just remapped the attributes to tags within the log pipeline. All good!

**Comment by Fer-moreno-epam** [comment]
I have the same issue. so not sure how to pass the attributes as tags for datadog.
