### ISSUE TITLE
Need Grok parsing support in fluentbit 

### ISSUE THREAD

**Issue by Praveen2099** [fluent/fluent-bit#8788]
**Is your feature request related to a problem? Please describe.**

In fluentbit i need to parse plain text logs using Grok . Either via Grok parser or using Lua script
.But currently there is no document or page have this info in the internet.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Praveen2099** [comment]
@patrick-stephens  need your help how to use Grok.I have required to only use Grok.
In lua scripts also there is no official Grok library

**Comment by patrick-stephens** [comment]
Duplicate of https://github.com/fluent/fluent-bit/issues/8166 I think.

**Comment by Praveen2099** [comment]
But i didn't find the solution.Can you please give the solution
