### ISSUE TITLE
unable to run as docker container

### ISSUE THREAD

**Issue by newbie78** [fluent/fluent-bit#880]
## Bug Report

**Describe the bug**
Hi, everybody
https://hub.docker.com/r/fluent/fluent-bit/
I tried what was described in "3. Test it" but did not receive log message on Fluent Bit container
what i'm doing wrong?

**To Reproduce**
start command in two different terminal window
```
docker run -p 127.0.0.1:24224:24224 fluent/fluent-bit:latest
docker run --log-driver=fluentd -t ubuntu echo "Testing a log message"
```

**Expected behavior**
Expected the log in the container with fluent-bit as a describe in description on docker hub page

**Screenshots**
![image](https://user-images.githubusercontent.com/28735/47904756-96b97f80-de96-11e8-837d-8c0489f8706f.png)
![image](https://user-images.githubusercontent.com/28735/47904808-a6d15f00-de96-11e8-8723-ffc55616cd2a.png)

**Your Environment**
* Version used: 0.14.6
* Environment name and version: Docker version 18.06.1-ce
* Operating System and version: Debian 9

thanx

**Comment by edsiper** [comment]
It works adding the tty argument:

```
$ docker run -ti -p 127.0.0.1:24224:24224 fluent/fluent-bit:latest
```

**Comment by edsiper** [comment]
Updated. thanks.
