### ISSUE TITLE
Systemd_filter not working

### ISSUE THREAD

**Issue by ItzMiracleOwO** [fluent/fluent-bit#8803]
## Bug Report

**Describe the bug**

Systemd_filter is not working, docker logs are still included

**To Reproduce**
- Start service with above config
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**
Docker should not be included in log

**Screenshots**

![image](https://github.com/fluent/fluent-bit/assets/76854136/7ac4e86b-68a3-4c67-b65a-2aab5e0cc25b)

**Your Environment**

* Version used: 2.1.1
* Configuration:
```

[INPUT]
    Name   kmsg
    Tag    kernel
[INPUT]
    Name            systemd
    Tag             systemd
#    Exclude  _SYSTEMD_UNIT ^(docker|kubelet)\.service$
    Systemd_Filter    _SYSTEMD_UNIT=docker.service

[OUTPUT]
    name    http
    match   *
    tls     On
    host    in.logs.betterstack.com
    port    443
    uri     /fluentbit
    header  Authorization Bearer zFoVZYGiyh8wUYQPVfvNQeJR
    header  Content-Type application/msgpack
    format  msgpack
    retry_limit 5
```

* Environment name and version (e.g. Kubernetes? What version?): Fedora Server 40
* Server type and version: 
* Operating System and version: Fedora server 40
* Filters and plugins:

**Additional context**
I am trying not to include docker logs

**Comment by patrick-stephens** [comment]
Can you confirm this still happens on the latest (3.0.3 currently)? 2.1.1 is no longer supported.

**Comment by ItzMiracleOwO** [comment]
Hi, 2.1.1 is the lastest I can get from `dnf`, see: https://packages.fedoraproject.org/pkgs/fluent-bit/fluent-bit/fedora-40.html

**Comment by patrick-stephens** [comment]
I can't really comment on how Fedora is working there but we do build targets for compatible systems so you can use the Fluent Bit repos as well: https://docs.fluentbit.io/manual/installation/linux
