### ISSUE TITLE
Binary data over tcp input

### ISSUE THREAD

**Issue by HKalbasi** [fluent/fluent-bit#8810]
I have a binary arbitrary data, containing `\0` and non ascii bytes. I want to transfer it into the fluent bit using the tcp input, but it doesn't work using the none parser as it detects `\0` as delimiter. Is there any mode that I can write length and data to emit raw binary data into the fluent bit? If not, is it possible to add a parser or something else for it? I can use msgpack but since my data is already a flat buffer message, it doesn't really make sense to wrap it in an additional msgpack.

**Comment by nrossi-dusty** [comment]
+1

This worked with td-agent, but doesn't work with td-agent-bit. I'm resorting to base64 encoding the message, which wastes a lot of network bandwidth.

**Comment by nickolasrossi** [comment]
+1

This worked with td-agent, but doesn't with td-agent-bit. I have resorted to base64 encoding the message, which wastes a lot of network bandwidth.

**Comment by brainerazer** [comment]
I have the same issue. Seems like this line is the culprit: https://github.com/fluent/fluent-bit/blob/4851c4bb35c26f23e6baf9b51ec9fef746bf490f/plugins/in_tail/tail_file.c#L454

Is there any possibility to input binary logs?
