### ISSUE TITLE
Fluent-bit version 1.9.6  [  Error] timerfd: Too many open files, errno=24 at /__w/1/s/external/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208

### ISSUE THREAD

**Issue by NarineM** [fluent/fluent-bit#8816]
## Bug Report

**Describe the bug**
fluent-bit fails with these errors randomly. In result tail plugin that monitors log files on the machine does not work.

- Example log message if applicable:
```
Apr 28 01:00:55 [2633351]: [log] error opening log file /var/opt/testapp/log/fluentbit.log. Using stderr.
Apr 28 01:00:55 [2633351]: [2024/04/28 01:00:55] [  Error] timerfd: Too many open files, errno=24 at /__w/1/s/external/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208
Apr 28 01:00:55 [2633351]: [2024/04/28 01:00:55] [error] [input collector] COLLECT_TIME registration failed
Apr 28 01:00:55 [2633351]: [log] error opening log file /var/opt/testapp/log/fluentbit.log. Using stderr.
Apr 28 01:00:55 [2633351]: [2024/04/28 01:00:55] [error] [input collector] COLLECT_TIME registration failed
Apr 28 01:00:55 j[2633351]: [2024/04/28 01:00:55] [  Error] timerfd: Too many open files, errno=24 at /__w/1/s/external/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:208
Apr 28 01:00:55 [2633351]: [log] error opening log file /var/opt/testapp/log/fluentbit.log. Using stderr.

```
- Steps to reproduce the problem:
 In my configuration fluent config has about 70 tail plugin configurations with each config monitoring one log file.
Fluent-bit version 1.9.6  

**Expected behavior**
no error , tail working as expected

* Version used: 1.9.6
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:  Ubuntu 22.04
* Filters and plugins: tail

**Additional context**
Need some workaround as in this setup fluent does not collect any logs.

**Comment by agup006** [comment]
Hi @NarineM could you check with the latest fluent bit? 1.9.x is no longer maintained

**Comment by NarineM** [comment]
@agup006 thanks for your response. What major version you recommend as known stable version? Is this issue known to be fixed  in  versions 3? or starting 2.* ?

**Comment by NarineM** [comment]
Similar to https://github.com/fluent/fluent-bit/issues/1777

**Comment by mariapoliss** [comment]
Reproduced in version 3.0.6
```
[2024/06/10 12:37:15] [error] [/src/fluent-bit/plugins/in_tail/tail_fs_inotify.c:360 errno=24] Too many open files
[2024/06/10 12:37:15] [error] failed initialize input tail.0
[2024/06/10 12:37:15] [error] [engine] input initialization failed
```
Work around from comment https://github.com/fluent/fluent-bit/issues/1777#issuecomment-613849415 to increase max_user_instances to 500 works, but could it be fixed in Fluentbit?
