### ISSUE TITLE
HTTP_password with special characters

### ISSUE THREAD

**Issue by HoussemGargour** [fluent/fluent-bit#8843]
## Bug Report

**Describe the bug**
We have an error when we try to connect to Opensearch 401 because of the password with special characters

```
[error][output:opensearch:opensearch.0] HTTP status=401 URI=/_bulk 
```

**Your Environment**
We are trying to install fluent-bit in linux machine red hat 9.
* Version used: fluent-bit 3.0.3
* Configuration:
    Name es
    Match *
    Host hostname
    HTTP_user username
    HTTP_passwrd (toto\tata%titi]tt
    tls On
    tls.verify Off
    Index fluent-bit
    Replace_Dots On
    Logstash_Format On
    Logstash_DateFormat %Y-%m-%d
    Time_key @timestamp
    Type flb_type
    retry_limit False
    Trace_Error On
    Suppress_Type_Name On

* Environment name and version (e.g. Kubernetes? What version?): Linux Red Hat 9
* Server type and version: Opensearch 2.7.0
* Operating System and version: Linix red hat 9

Can you help me with this problem thx !

**Comment by leonardo-albertovich** [comment]
Just tested this with both the latest version and 3.0.3 and both of them produced the correct authorization header. 

I assume that you might've had to change your password not to reveal any secrets but it seems that the information you have provided does not cause any issues. 

Could you please help me clarify the situation?
