### ISSUE TITLE
MongoDB output plugin

### ISSUE THREAD

**Issue by w4term3loon** [fluent/fluent-bit#8846]
**Is your feature request related to a problem? Please describe.**
Default **MongoDB output plugin** support.

**Describe the solution you'd like**
MongoDB output plugin as a default plugin to ease the process of setting up the connection between such databases and Fluent-bit.

**Describe alternatives you've considered**
For my use case, MongoDB is the optimal choice, hence I would rather not deviate.

**Additional context**
This would be a useful feature for users, and another supported database would be a nice addition to the multiple supported ones. (e.g. PostgreSQL, BigQuery, Influx, etc.)

**Comment by w4term3loon** [comment]
Sorry, for the commit-hash changes, trying to organize the commits and had some mixup with my configs and commit authors.

**Comment by lake2** [comment]
same issue here.
I need  a mongodb output pulgin.

**Comment by lake2** [comment]
@w4term3loon  Is there any chance to merge this into master

**Comment by w4term3loon** [comment]
Hi @lake2, unfortunately, I didn't have the time to continue on this feature but feel free to finish it! Merging it as is is impossible, since it is far from finished. It initialises the connection between fluent and MongoDB but dumping data is not implemented.
