### ISSUE TITLE
Fluent-bit 3.0.4 throwing repeated warnings ( [ warn] [record accessor] translation failed, root key=hec_token)

### ISSUE THREAD

**Issue by Nithinrao9696** [fluent/fluent-bit#8859]
## Bug Report

**Describe the bug**
After upgrading fluent-bit from 3.0.3 to 3.0.4, we have noticed fluent-bit pods started throwing repeated warnings in the logs

**To Reproduce**
 upgrade to 3.0.4 version of fluent-bit
- Rubular link if applicable:
- Example log message if applicable:
```

[2024/05/22 13:12:09] [ warn] [record accessor] translation failed, root key=hec_token
[2024/05/22 13:12:09] [ warn] [record accessor] translation failed, root key=hec_token
[2024/05/22 13:12:09] [ warn] [record accessor] translation failed, root key=hec_token
[2024/05/22 13:12:09] [ warn] [record accessor] translation failed, root key=hec_token
[2024/05/22 13:12:09] [ warn] [record accessor] translation failed, root key=hec_token

```

**Comment by digarok** [comment]
I think there's a problem with this PR. 
https://github.com/fluent/fluent-bit/pull/8793/files

We're getting spammed with the same message as the user above, millions of times per minute:
`[2024/05/22 16:08:04] [ warn] [record accessor] translation failed, root key=hec_token`

**Comment by yuliyan-valchev-ft** [comment]
Same error 
`[2024/05/22 15:06:30] [ warn] [record accessor] translation failed, root key=hec_token
[2024/05/22 15:06:30] [debug] [output:splunk:splunk.0] Could not find hec_token in metadata`

It started appearing right after we started using the latest helm chart 0.46.7

**Comment by edsiper** [comment]
we are looking into this.

**Comment by edsiper** [comment]
Fix will be there shortly: https://github.com/fluent/fluent-bit/pull/8864

**Comment by nehjain17** [comment]
We are facing security issue and need to upgrade to 3.0.4 asap. Getting the same error.

**Comment by nehjain17** [comment]
With 3.0.5 getting below error. 
[2024/05/24 05:47:13] [ warn] [output:splunk:splunk.16] http_status=401:
{"text":"Token is required","code":2}

**Comment by edsiper** [comment]
> With 3.0.5 getting below error. [2024/05/24 05:47:13] [ warn] [output:splunk:splunk.16] http_status=401: {"text":"Token is required","code":2}

@nehjain17 What is your config?

**Comment by nehjain17** [comment]
Output Config:

[OUTPUT]
        Name splunk
        Match index1*
        event_index index1
        host splunk_host_name
        Port 443
        splunk_token ${TOKEN}
        tls On
        tls.verify Off
        Retry_Limit 5
        net.connect_timeout 30
        net.keepalive on
