### ISSUE TITLE
3.0.5: output:splunk: Error http_status=401 Token is required

### ISSUE THREAD

**Issue by nehjain17** [fluent/fluent-bit#8867]
With 3.0.5 getting below error.
[2024/05/24 05:47:13] [ warn] [output:splunk:splunk.16] http_status=401:
{"text":"Token is required","code":2}

**Comment by edsiper** [comment]
Please provide your full configuration

**Comment by nehjain17** [comment]
output plugin

[OUTPUT]
        Name splunk
        Match index1
        event_index index1
        host splunk_host_name
        Port 443
        splunk_token ${TOKEN}
        tls On
        tls.verify Off
        Retry_Limit 5
        net.connect_timeout 30
        net.keepalive on

**Comment by rchopd** [comment]
we are also facing same issue... 3.0.4 had lot of warning noice so upgraded to 3.0.5 which gave us "Token is required" error, despite of providing splunk_token in output config 
@edsiper can you please take a look at it.

**Comment by edsiper** [comment]
I am looking into this.

**Comment by edsiper** [comment]
I have pushed https://github.com/fluent/fluent-bit/pull/8873 to fix this issue.

**Comment by rchopd** [comment]
Hey @edsiper 
Thanks for fixing the issue. Will it be available in 3.0.5 or you are going to create a new tag?

**Comment by edsiper** [comment]
@rchopd `v3.0.6` has been pushed, packages and images will be available in a couple of hours.

**Comment by rchopd** [comment]
Thanks a lot.. will test it once available and let you know our findings

**Comment by soc-team-members** [comment]
We are using v3.1.9, but we are still (or again?) getting these debug messages, even though we did specify a valid splunk_token. 

[2024/11/08 11:26:48] [debug] [output:splunk:splunk.1] Could not find hec_token in metadata

**Comment by Ridhubharan** [comment]
Hi. I am using Fluent bit v3.2 and facing the same issue.

My config:
```
[OUTPUT]
    name  splunk
    match  *
    host  127.0.0.1
    port  8088
    Splunk_Token  <token>
    tls  On
    tls.verify  Off
    Splunk_Send_Raw  On
```

Error from journalctl:

> [output:splunk:splunk.1] Could not find hec_token in metadata

**Comment by siarheimuha** [comment]
Fluentbit 3.2.2 
[debug] [output:splunk:splunk.0] Could not find hec_token in metadata
