### ISSUE TITLE
Support for linux on IBM Power platform (ppc64le)

### ISSUE THREAD

**Issue by bogdansavu** [fluent/fluent-bit#8870]
I am trying to compile the agent on the RHEL 8 ppc64le platform, but I am getting the following error:

[  5%] Generating buildvm_arch.h
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:39: error: lib_ffi not yet implemented for PPC64:
|.error lib_ffi not yet implemented for PPC64
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:641: error: bad displacement `SAVE_TOC':
  |  .toc ld TOCREG, SAVE_TOC
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:656: error: bad displacement `SAVE_TOC':
  |  .toc ld TOCREG, SAVE_TOC
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:712: error: bad displacement `SAVE_TOC':
  |  saveregs
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:758: error: bad displacement `SAVE_TOC':
  |  saveregs
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:765: error: bad displacement `SAVE_TOC':
  |  saveregs
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:813: error: bad displacement `SAVE_TOC':
  |  saveregs
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:3179: error: bad displacement `SAVE_TOC':
  |  saveregs
  |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:5873: error: bad displacement `SAVE_TOC':
    |  .toc ld TOCREG, SAVE_TOC
    |   a, b	[MACRO .toc (2)]
/root/fluent-bit/lib/luajit-3065c9/src/vm_ppc.dasc:*: info: 9 errors in input file -- no output file generated.
make[2]: *** [lib/luajit-cmake/CMakeFiles/buildvm_arch_h.dir/build.make:73: lib/luajit-cmake/buildvm_arch.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:5203: lib/luajit-cmake/CMakeFiles/buildvm_arch_h.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by patrick-stephens** [comment]
I believe we had some PPC support added a while ago but maybe only for the containers which would be Debian based.

Can you run the containers instead?

However it looks like a fundamental issue on that target. It's not an officially supported platform unfortunately so probably needs some tweaks or updates to be contributed (if it is even possible): https://docs.fluentbit.io/manual/installation/linux/redhat-centos

**Comment by patrick-stephens** [comment]
Containers are just however you run them on your OS (install container runtime, etc.) then run: https://docs.fluentbit.io/manual/installation/docker

However, I was confused as looks like PPC support for containers was not merged yet: https://github.com/fluent/fluent-bit/pull/6792
I would pick up that PR and see if it helps as well as improve it for future merge?
