### ISSUE TITLE
Tracing documentation samples fail for the latest fluent bit release

### ISSUE THREAD

**Issue by NemmyM** [fluent/fluent-bit#8885]
## Bug Report

**Describe the bug**
Trying to follow  [tracing documentation](https://docs.fluentbit.io/manual/administration/troubleshooting) fails for fluent bit versions above 3.0.3

**To Reproduce**
docker run --rm -ti -p 2020:2020 fluent/fluent-bit:latest -Z -H -i dummy -p alias=input_dummy -o stdout -f 1
curl 127.0.0.1:2020/api/v1/trace/input_dummy
```
{"status":"not found"}
```

**Expected behavior**
```
{"status":"ok"}
```

**Your Environment**
* Version used:fluent-bit:latest, fluent-bit:3.0.3
* Environment name and version (e.g. Kubernetes? What version?): Docker version 26.1.3, build b72abbb
* Operating System and version: Ubuntu 24.04 LTS

**Additional context**
Pinning down to fluent-bit to versions 2.0 up to 3.0.3 works as expected.
docker run --rm -ti -p 2020:2020 fluent/fluent-bit:3.0.3 -Z -H -i dummy -p alias=input_dummy -o stdout -f 1

**Comment by pwhelan** [comment]
There is a fix in #8886. This was caused by the refactor done to the trace API and how it handled the input name.
