### ISSUE TITLE
hash_value_field support (from fluentd) for fluent-bit's filter_parsers

### ISSUE THREAD

**Issue by kfdm** [fluent/fluent-bit#8893]
**Is your feature request related to a problem? Please describe.**

Using [filter_parser](https://docs.fluentd.org/filter/parser) you can parse a field into a new value. For example

```
[FILTER]
    Name parser
    Match systemd.json
    Parser systemd_json
    Key_name MESSAGE
    Reserve_Data On
```

Allows me to take a `MESSAGE` field from some incoming systemd (journald) logs, and parse them.
One minor issue, is that it all gets merged down into the original hash value

```
# Input
{"MESSAGE": '{"some":"value"}}
# Output
{"MESSAGE": '{"some":"value"}, "some":value}
```

Fluentd's version of [filter_parser](https://docs.fluentd.org/filter/parser) supports a `hash_value_field` field, that lets us control where this goes.

```
# Input
{"MESSAGE": '{"some":"value"}}
# Output
{"MESSAGE": '{"some":"value"}, "parsed": {"some":value}}
```

What would be involved in allowing fluent-bit's filter_parser to support a similar `hash_value_field` target, to avoid a case where something parsed out might overwrite another field

I think it's not really possible to use `filter_lua` to parse it, and I think there's no way to have [filter_record_modifer](https://docs.fluentbit.io/manual/pipeline/filters/record-modifier) to make a copy either. I'm trying to simplify a few things to avoid deploying fluentd, so I'm hoping there might be a way to handle this within fluent-bit alone.

**Comment by Athishpranav2003** [comment]
I guess i can work on this feature. I am trying to refactor some code in msgpack itself. Once that PR gets accepted i will create this PR for the approval

**Comment by Athishpranav2003** [comment]
Raised PR #9243 for the latest lib

**Comment by Athishpranav2003** [comment]
@kfdm if possible you can also look at the PR
