### ISSUE TITLE
Finding a way to supress or redirect fluent-bit startup log

### ISSUE THREAD

**Issue by HarrisonEagle** [fluent/fluent-bit#8899]
**Is your feature request related to a problem? Please describe.**
Well, I am using fluent-bit to convert my logs to structured logs of GCP Cloud Logging. It works well and all structured logs are written to stdout. 
But the problem is, the startup logs of fluent-bit like following are written in stderr:
```
Fluent Bit v1.9.10
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
```
Is there any way to suppress the startup logs, or redirect fluent-bit startup logs to stdout or other files?

**Describe the solution you'd like**
 Adding CLI flags or configuration options to disable startup logs, or redirect startup logs of fluent-bit to stdout

**Describe alternatives you've considered**

**Additional context**
Writing logs to stderr making startup logs are handled as error logs in GCP Cloud Logging, which makes it difficult to set AlertPolicy to detect error logs properly. That is the reason I want the option to redirect or suppress fluent-bit's startup logs.

**Comment by patrick-stephens** [comment]
Do you mean the option to log to a file for Fluent Bit (https://docs.fluentbit.io/manual/administration/configuring-fluent-bit)?
```
  -l, --log_file=FILE     write log info to a file
```
You can also redirect stderr to stdout, or is that not possible?
Finally, 1.9 is not supported by OSS so I'd also step up to a more recent version to check any issues there.

**Comment by hblab-longnt1** [comment]
Same issue, I also want to suppress startup log of Fluentbit, since it's being treated as error log in GCP
