### ISSUE TITLE
Bulk size in output es module

### ISSUE THREAD

**Issue by nikitamishagin** [fluent/fluent-bit#8906]
**Is your feature request related to a problem? Please describe.**
I tried using fluent-bit to collect logs from nginx-ingress-controller and send them to elasticsearch. Everything works well for small loads, but for large loads you need to configure the size of the packet sent to elasticsearch (bulk). As I understand it, the output es module does not have such a parameter and sends 10-20 logs in one packet. With 5k+ logs, the module simply cannot cope with its task.

**Describe the solution you'd like**
Could you add the ability to customize the size of the sent packet in elasticsearch?

**Additional context**
Logs are lost at the sending stage under heavy loads on the ingress-controller. I would like to deliver all the logs in fewer packets.

**Comment by hawk-nguyen-nguyen** [comment]
i experience the same any update here

**Comment by nikitamishagin** [comment]
Hello, team. Specifying the size of the sent packet is a very important feature for Elasticsearch. Please pay attention to this issue.

**Comment by mohijeet-changejar** [comment]
i am facing the same issue elastic search is reaching its queue size limit of thread_pool queue because of data being sent is less in size but more in number of write requests....
