### ISSUE TITLE
Datadog output setup proxy with user:password

### ISSUE THREAD

**Issue by aejii** [fluent/fluent-bit#8907]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to configure a Proxy and I can't add an user/password

**Describe the solution you'd like**
instead of just _http://host:port_ , allow _http://user:password@host:port_ 

**Describe alternatives you've considered**
use a (deprecated) passwordless proxy

**Additional context**
passwordless proxy are deprecated

edit:
I saw some flb_http_proxy_auth and flb_http_basic_auth in the code, is the auth proxy already available but not documented ?

**Comment by patrick-stephens** [comment]
I thought the http proxy config supported that already, is it not working as per the docs? https://docs.fluentbit.io/manual/administration/http-proxy

**Comment by aejii** [comment]
I was using this doc : https://docs.fluentbit.io/manual/pipeline/outputs/datadog (and the Proxy key).

With https://docs.fluentbit.io/manual/administration/http-proxy it's working perfectly !
