### ISSUE TITLE
Debian/Ubuntu Package File Placement

### ISSUE THREAD

**Issue by sandstrom** [fluent/fluent-bit#891]
Debian and Ubuntu packages should not install stuff in `/opt`. 

Instead `/usr/share`, `/usr/lib`, `/usr/bin` etc should be used. It would be great if the `td-agent` and `td-agent-bit` packages would adhere to this principle.

`dpkg-query -L td-agent-bit` will list the current install locations. Can also be used to understand where other packages are storing their files.

Since this is a larger change it would make sense to wait until a major release, or wait until you upgrade the packages for a new debian/ubuntu release.

More details:
https://wiki.debian.org/FilesystemHierarchyStandard
https://askubuntu.com/questions/34880/use-of-opt-and-usr-local-directories
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by edsiper** [comment]
thanks. PR are welcome.
