### ISSUE TITLE
splunk output with splunk_send_raw on is using the wrong endpoint

### ISSUE THREAD

**Issue by pmeier** [fluent/fluent-bit#8927]
## Bug Report

**Describe the bug**

When using the `splunk` output with `Splunk_Send_Raw On` the data is send to the [`/services/collector/raw`](https://docs.splunk.com/Documentation/Splunk/9.2.1/RESTREF/RESTinput#services.2Fcollector.2Fraw) endpoint rather than [`/services/collector/event`](https://docs.splunk.com/Documentation/Splunk/9.2.1/RESTREF/RESTinput#services.2Fcollector.2Fevent):

https://github.com/fluent/fluent-bit/blob/c3d12804d251e4810a045efd3862bf13c8047bd4/plugins/out_splunk/splunk.h#L25-L26

This seems to be wrong. To the best of my understanding, the term "raw" for Splunk means "raw log message without metadata". It is not entirely clear from their documentation, but in the [examples](https://docs.splunk.com/Documentation/Splunk/9.2.1/Data/HECExamples) they are only ever explicitly using the `/services/collector/raw` endpoint when sending pure messages. This is also supported by our observations that when we are using `Splunk_Send_Raw On`, the whole record is showing up as JSON string as message, rather than it being parsed out.

This was introduced in aeb18f77b3eb83ca9d2ec6511f6fe7c275fe79a3 (cc @edsiper) and first released with v1.8.0. The commit message states

> In addition this patch fixes the raw mode endpoint.

without further indication what exactly was supposed to be fixed by this. In contrast, this likely broke the raw mode.

**Comment by agup006** [comment]
We should make the URi configurable with send raw @cosmo0920

**Comment by pmeier** [comment]
It would solve my issue, but I'm not sure why you want to ever hit the `/raw` endpoint from fluent-bit. This endpoint is for sending plain strings and attaching the timestamp on when the message was received to it. This is equivalent of sending the following JSON object to the `/event` endpoint

```json
{
  "event": "<message sent to the /raw endpoint>",
  "time": "<timestamp when the message was received>"
}
```

This wrapping is exactly what the splunk output in fluent bit is doing by default, i.e. `Splunk_Send_Raw Off`: the internal record is nested under the `event` key and the timestamp is inserted as the `time` key.

Thus, there is never a need to use the `/raw` endpoint from fluent-bit: 

- Either you don't want to perform the wrapping yourself. In this case you use the default behavior (or set `Splunk_Send_Raw Off` explicitly) and leave this to fluent-bit
- Or you want to have specific control over what is being sent to splunk. In this case you set `Splunk_Send_Raw On` and format the record to whatever shape you want it to be.

In both cases however, the output from fluent-bit is JSON object and thus has to go to the `/event` endpoint and never to the `/raw` endpoint.
