### ISSUE TITLE
Increase metric name length to avoid truncating the metric name

### ISSUE THREAD

**Issue by imankurpatel000** [fluent/fluent-bit#8938]
**Is your feature request related to a problem? Please describe.**

Currently, metric name length is limited to 64 characters as defined [here](https://github.com/fluent/fluent-bit/blob/34c9f5e66355e89f064a73e74e0ce2689560df82/include/fluent-bit/flb_metrics.h#L59-L72). We use fluent-bit in a k8s cluster with close to 200 outputs. The output `alias` is defined as a combination of Application name, container name and stdout/stderr which sometimes exceeds the 64 character limit so we end up losing some information in the metric name. The bigger problem is sometimes because of the truncation we end up with the same metric name for 2 different outputs so now we have no way to know which metric corresponds to which output. We also get an error in prometheus.

Example configuration
```
[Output]
    Name     s3
    Alias    very-very-long-application-name.very-very-long-container-name.stdout
    ...
[Output]
    Name     s3
    Alias    very-very-long-application-name.very-very-long-container-name.stderr
    ...
    
```

Prometheus metric for this looks like below with truncated name.
```
fluentbit_output_dropped_records_total{name="very-very-long-application-name.very-very-long-container-name.s"} 0 1714977925107
fluentbit_output_dropped_records_total{name="very-very-long-application-name.very-very-long-container-name.s"} 29994 1714977925107
```

This fails in Prometheus with `err: duplicate sample for timestamp`.

**Describe the solution you'd like**

I see 2 solutions to this.
1. The simplest solution is to just increase the 64 character limit defined [here](https://github.com/fluent/fluent-bit/blob/34c9f5e66355e89f064a73e74e0ce2689560df82/include/fluent-bit/flb_metrics.h#L59-L72).
2. Implement something similar to #3825. This way we don't have to rely on just the `alias` to distinguish between different output metrics.

**Comment by edsiper** [comment]
Assigned to @cosmo0920

**Comment by imankurpatel000** [comment]
Hey @edsiper & @cosmo0920 thanks a lot for fixing this so quickly. Can you please let me know when this will be released?
