### ISSUE TITLE
Using a filter to send only the messages you want

### ISSUE THREAD

**Issue by MarloGrayhat** [fluent/fluent-bit#8942]
I have log files that store all information about events that occur in the program, including messages coming from another service. I would like to send with fluent bit only those messages that come to me from this service and nothing else.

I would like to see a filter that would help me to separate the necessary data from the not necessary data using regex or checking if the json has a field. 

As an alternative solution I see writing logic to save incoming messages to a separate log file, however, I would not want to reduce performance, because in my work execution time is one of the most important parameters.

**Comment by patrick-stephens** [comment]
Can you expand this following the template with more details?
It would be useful to have sample input, expected output, etc. too.

**Comment by MarloGrayhat** [comment]
I have as input a log file with the following content
```json
{"level":"debug","ts":"2024-05-28T18:23:31.218+0400","caller":"ws/helper.go:39","msg":"connect to binance was successful","debug mode":true,"Exchange":"Binance","API":"WS_SPOT","Trading":"SPOT"}
{"level":"debug","ts":"2024-05-28T18:23:31.218+0400","caller":"ws/helper.go:39","msg":"subscribe to [bnbusdt@trade] was successful","debug mode":true,"Exchange":"Binance","API":"WS_SPOT","Trading":"SPOT"}
{"level":"debug","ts":"2024-05-28T18:23:31.256+0400","caller":"ws/helper.go:39","msg":"{\"e\":\"trade\",\"E\":1716906210886,\"T\":1716906210886,\"s\":\"BNBUSDT\",\"t\":1299601057,\"p\":\"600.100\",\"q\":\"0.02\",\"X\":\"MARKET\",\"m\":true}","debug mode":true,"Exchange":"Binance","API":"WS_SPOT","Trading":"SPOT"}
{"level":"debug","ts":"2024-05-28T18:23:31.256+0400","caller":"ws/helper.go:39","msg":"{\"e\":\"trade\",\"E\":1716906210886,\"T\":1716906210886,\"s\":\"BNBUSDT\",\"t\":1299601058,\"p\":\"600.100\",\"q\":\"0.14\",\"X\":\"MARKET\",\"m\":true}","debug mode":true,"Exchange":"Binance","API":"WS_SPOT","Trading":"SPOT"}
{"level":"debug","ts":"2024-05-28T18:23:31.886+0400","caller":"ws/helper.go:39","msg":"{\"e\":\"trade\",\"E\":1716906211507,\"T\":1716906211507,\"s\":\"BNBUSDT\",\"t\":1299601059,\"p\":\"600.100\",\"q\":\"0.04\",\"X\":\"MARKET\",\"m\":true}","debug mode":true,"Exchange":"Binance","API":"WS_SPOT","Trading":"SPOT"}
{"level":"debug","ts":"2024-05-28T18:23:32.395+0400","caller":"ws/helper.go:39","msg":"{\"e\":\"trade\",\"E\":1716906212024,\"T\":1716906212024,\"s\":\"BNBUSDT\",\"t\":1299601060,\"p\":\"600.100\",\"q\":\"0.04\",\"X\":\"MARKET\",\"m\":true}","debug mode":true,"Exchange":"Binance","API":"WS_SPOT","Trading":"SPOT"}
```

In the final database, I only want to have the content from rows 2-6:


|   e       |       E       |        T          |       s       |       t       |       p       |   q       |       X       |       m   |
|-----------|---------------|-------------------|---------------|---------------|---------------|-----------|---------------|-----------|
|"trade"    | 1716906210886 |   1716906210886   |   "BNBUSDT"   |   1299601057  |   "600.100"   |   "0.02"  |   "MARKET"    |   true    |
|"trade"    | 1716906210886 |   1716906210886   |   "BNBUSDT"   |   1299601058  |   "600.100"   |   "0.14"  |   "MARKET"    |   true    |
|"trade"    | 1716906211507 |   1716906211507   |   "BNBUSDT"   |   1299601059  |   "600.100"   |   "0.04"  |   "MARKET"    |   true    |
|"trade"    | 1716906212024 |   1716906212024   |   "BNBUSDT"   |   1299601060  |   "600.100"   |   "0.04"  |   "MARKET"    |   true    |

**Comment by patrick-stephens** [comment]
I think a simple `grep` would do this, you just need to configure it to drop/allow whatever regex matches the records you want.

**Comment by patrick-stephens** [comment]
Otherwise you can do something more complex with LUA - the return code indicates what to do with the message: https://docs.fluentbit.io/manual/pipeline/filters/lua#callback-prototype (-1 means drop it).
