### ISSUE TITLE
out_cloudwatch_logs: log_group_class option introduced breaking change in 3.0.7

### ISSUE THREAD

**Issue by nicolas-laduguie** [fluent/fluent-bit#8949]
## Bug Report

**Describe the bug**
Release 3.0.7 delivered the new log_group_class option support for cloudwatch output, but this introduces a breaking change, causing fluentbit not able to start.

**To Reproduce**
- Run 3.0.6 version of fluentbit with cloudwatch output option auto_create_group set to Off => should work fine
- Keep same config and run fluentbit 3.0.7 => fail starting with following error :  
```
[2024/06/12 00:07:27] [error] [output:cloudwatch_logs:cloudwatch_logs.0] Configuring log_group_class requires `auto_create_group On`.
```

**Expected behavior**
Since 3.0.7 is a patch revision, should not introduce any breaking change and should work well with a configuration compliant with 3.0.6.

**Your Environment**
* Version used: 3.0.7
* Configuration: 
```
[OUTPUT]
    Name cloudwatch_logs
    Match *
    region us-west-2
    log_group_name XXX
    log_stream_prefix XXX
    auto_create_group Off
```

* Operating System and version: Ubuntu 22.04

**Comment by nicolas-laduguie** [comment]
The change introducing the breaking change : https://github.com/fluent/fluent-bit/pull/8832

**Comment by lecaros** [comment]
ping @PettitWesley @edsiper

**Comment by cschp** [comment]
I also have this issue and i am hoping for a resolution soon

**Comment by ssc-ksaitou** [comment]
Same here.

Setting `auto_create_group=true` in `fluent-bit.conf` and allowing `logs:CreateLogGroup` in IAM worked as a workaround in my case, however I don't want to do so.
