### ISSUE TITLE
License issue: GPL v2 code is cut&paste in and copyright removed, replaced

### ISSUE THREAD

**Issue by donbowman** [fluent/fluent-bit#895]
It appears that some code has been cut & paste from other sources which are GPL, and then the license changed to Apache2 by just removing it from the file. An example:

If we look @ lib/sha1/sha1.c the top of the file reads:

```
/*
 * Code adapted to fill Fluent Bit requirements, no big changes
 * just a few header files added.
 */
```

and it is being released in fluent-bit under apache2 license.

However, this file is in turn copied from [monkey/duda](https://github.com/monkey/duda/blob/master/packages/websocket/sha1.c) with the top lines as:

```
/* 
 * Code adapted to fill Monkey Project requirements, no big changes
 * just a few header files added
 */
```

And, in turn it comes from [libgit2](http://hackage.haskell.org/package/hlibgit2-0.17.0.1/src/libgit2/src/sha1.c), which is under GPLv2 (with linking exception), the top lines being:
```
/*
 * Copyright (C) 2009-2012 the libgit2 contributors
 *
 * This file is part of libgit2, distributed under the GNU GPL v2 with
 * a Linking Exception. For full terms see the included COPYING file.
 */
```
There are a few trivial changes (casting to remove warnings), but no code changes.

It also appears in [git](https://github.com/git/git/blob/master/block-sha1/sha1.c) under LGPL-2.1

Some discussion occurred [here](http://git.661346.n2.nabble.com/Linus-sha1-is-much-faster-td3448007.html) on the relicense to GPLv2.

**Comment by edsiper** [comment]
thanks for catching that.

Fixed by f60b8568
