### ISSUE TITLE
 system startup logs

### ISSUE THREAD

**Issue by 2048038907** [fluent/fluent-bit#8958]
How to modify the format of system startup logs

![image](https://github.com/fluent/fluent-bit/assets/102948223/a51dc94a-8532-4d42-9a46-b40d56dc854d)

[2024/06/14 09:20:40] [ info]    Convert to    [2024/06/14 09:20:40.156] [ info]

**Comment by patrick-stephens** [comment]
What do you want to modify and how?

**Comment by cosmo0920** [comment]
什么意思呢？不可能改变系统启动记录。
What do you mean? Fluent bit does not have a capability to change the start up logs.
