### ISSUE TITLE
fluent-bit 3.0.7 breaks kubernetes filter when using tls.verify and Use_Kubelet

### ISSUE THREAD

**Issue by fcuello-fudo** [fluent/fluent-bit#8959]
## Bug Report

**Describe the bug**

If kubernetes filter is configured with tls.verify and Use_Kubelet is used, the requests to the k8s API will succeed but the requests to the node's kubelet will fail with tls errors.

**To Reproduce**
- Steps to reproduce the problem:
Use the kubernetes filter and enable `Use_Kubelet`

**Expected behavior**
kubernetes filter works as before

**Your Environment**

* Version used: 3.0.7

**Additional context**

```
Fluent Bit v3.0.7
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________  
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \ 
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  < 
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/ 

[2024/06/14 08:37:58] [error] [tls] error: unexpected EOF with reason: certificate verify failed
[2024/06/14 08:37:58] [error] [filter:kubernetes:kubernetes.0] kubelet upstream connection error
```

What seems to be happening is that the connection to the kubelet is using the address 127.0.0.1 and that address is not included in the kubelet's cert.

Disabling `tls.verify`  solves the problem, but then the requests that go to the k8s api are not verified anymore.

**Comment by kjq** [comment]
We see the same issue and disabling `tls.verify` looked to work.

**Comment by cosmo0920** [comment]
Hey, we're trying to restore the previous behavior in https://github.com/fluent/fluent-bit/pull/8966 and https://github.com/fluent/fluent-bit/pull/8967 (for 3.0 line).
Could you try this branch then?
