### ISSUE TITLE
default behavior of dd_message_key from out_datadog is broken

### ISSUE THREAD

**Issue by pmeier** [fluent/fluent-bit#8982]
## Bug Report

Documentation states

https://github.com/fluent/fluent-bit/blob/2bef95819e33a933d56c9f20808b7640dc9a1db7/plugins/out_datadog/datadog.c#L536-L542

But the default behavior is not happening. If you leave this configuration option out, no processing is applied and thus by default the `'log'` instead of the `'message'` key is used. And since this format is not recognized by Datadog, the message does not show up at all.

We figured this out by configuring the plugin to send its data to a self-controlled HTTP server that does nothing but mirror back its input.

**Expected behavior**

Honor the default behavior described in the documentation.

**Your Environment**

* Version used: 3.0.7
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes
* Filters and plugins: `out_datadog`

**Comment by patrick-stephens** [comment]
Please can you follow the issue template to capture all the relevant information like OS, target, what version of Fluent Bit, etc.?

**Comment by pmeier** [comment]
Done @patrick-stephens

**Comment by vinnymac** [comment]
Just experienced this issue. Default behavior did not work, but adding `dd_message_key: log` fixed it.

😅 spent an hour thinking this was an issue with our log ingestion pipeline in DD, but was just the fluent bit configuration.
