### ISSUE TITLE
Add proxy_url into Input Prometheus Scrape Metrics

### ISSUE THREAD

**Issue by ntheanh201** [fluent/fluent-bit#8987]
**Is your feature request related to a problem? Please describe.**

I cannot scrape metrics from Prometheus due to the need to route through a proxy. Adding proxy_url would solve this.

**Describe the solution you'd like**

I would like the option to specify a proxy_url in the Prometheus Scrape Metrics configuration of Fluent-bit, allowing metrics to be collected through a proxy server.

**Describe alternatives you've considered**

**Additional context**

This issue affects our ability to collect and monitor metrics in environments with strict network policies. Being able to configure a proxy directly in Fluent-bit would simplify our setup and improve reliability.

**Comment by patrick-stephens** [comment]
I thought all were supported via the generic proxy approach: https://docs.fluentbit.io/manual/administration/http-proxy

**Comment by ntheanh201** [comment]
> I thought all were supported via the generic proxy approach: https://docs.fluentbit.io/manual/administration/http-proxy

I see, it can solve my case, but I still think it would be nice if we have proxy_url for each configuration of that Input
