### ISSUE TITLE
flb_hash_table_get,  should have ssize_t for return parameter out_size

### ISSUE THREAD

**Issue by jordanauge** [fluent/fluent-bit#8996]
## Bug Report

Hello, I noticed some inconsistent data types are used in the hash table code:

[flb_hash_table_entry.val_size](https://github.com/fluent/fluent-bit/blob/f5737c03df6804d06bab4b469edfe46e212ce7f6/include/fluent-bit/flb_hash_table.h#L44) is a ssize_t that is set to -1 to indicate the user is only storing a pointer, and not actual data in the entry.

However (at least) two function prototypes are using size_t:

 - [flb_hash_table_get](https://github.com/fluent/fluent-bit/blob/f5737c03df6804d06bab4b469edfe46e212ce7f6/src/flb_hash_table.c#L383)
 - [entry_set_value](https://github.com/fluent/fluent-bit/blob/f5737c03df6804d06bab4b469edfe46e212ce7f6/src/flb_hash_table.c#L250)

Thanks
-- Jordan

**Comment by patrick-stephens** [comment]
Thanks for the report, can you submit a PR?

**Comment by jordanauge** [comment]
I can look at it but there are several plugins impacted, we need to be careful. 

ssize_t as in flb_hash_table_add ? or size_t as in _get ? -1 is used as a special value internally when val_size <= 0,  and i don't seem to find a plugin using negative values from a first look. It might make sense to align to size_t.

What do you think should be the right prototype ?
