### ISSUE TITLE
Documentation for InfluxDB references Tags_List_Enabled and Tags_List_Key

### ISSUE THREAD

**Issue by nochristrequired** [fluent/fluent-bit#8998]
## Bug Report

**Describe the bug**
_Tags_List_Enabled_ and _Tags_List_Key_  are shown in the fluent-bit documentation under pipeline/outputs/influxdb, and this feature does not seem to be merged.

Docs: https://docs.fluentbit.io/manual/pipeline/outputs/influxdb
Docs PR: https://github.com/fluent/fluent-bit-docs/pull/541

Feature PR: https://github.com/fluent/fluent-bit/pull/3586

**Expected behavior**
Documentation should not mention features that are not widely available. (stale PR)

Additionally, I wish this feature WAS available. :)

**Comment by patrick-stephens** [comment]
Can you submit a docs PR to revert it? I can merge that, Github doesn't want to auto-revert probably because it was quite a while ago.
