### ISSUE TITLE
Question about two plugins for Azure Log Analytics

### ISSUE THREAD

**Issue by yitaopan** [fluent/fluent-bit#9003]
**Is your feature request related to a problem? Please describe.**

Hi, we notice that there are two plugins for Azure Log Analytics, the [Http data collector api](https://docs.fluentbit.io/manual/pipeline/outputs/azure) and the [DCR based one](https://docs.fluentbit.io/manual/pipeline/outputs/azure_logs_ingestion), would like to learn about the relationship between these plugins, are they both included in this repo? Thanks.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Yes, check: https://github.com/fluent/fluent-bit/tree/master/plugins

All official Fluent Bit plugins are included, it's not like Fluentd where you add required ones.
