### ISSUE TITLE
Content-Type rejected: ``

### ISSUE THREAD

**Issue by metalfork** [fluent/fluent-bit#9018]
https://github.com/fluent/fluent-bit/blob/060418c51bea221f0f6a1992f44dbdee7845f490/plugins/in_http/http_prot.c#L526-L529

Can we update the conditional here to allow `application/json;charset=utf-8` as the `Content-Type`? Currently the conditional just checks for `application/json` (length `16`) so the encoding value causes a failure.  See this in AWS Fargate at the moment with Serilog and the dotnet Http sink. [Ref](https://github.com/FantasticFiasco/serilog-sinks-http/issues/43)

**Comment by patrick-stephens** [comment]
Can you submit a PR?

**Comment by metalfork** [comment]
> Can you submit a PR?

@patrick-stephens submitted https://github.com/fluent/fluent-bit/pull/9023
