### ISSUE TITLE
Upgrade LuaJIT to import ARM64 Windows support

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-bit#9020]
**Is your feature request related to a problem? Please describe.**

The current version of LuaJIT supports ARM64 Windows in this commit: https://github.com/LuaJIT/LuaJIT/commit/cb413bf8f4814fe3e47c8c619602c7a161469faf
And completed supporting ARM64 Windows in this ticket:
https://github.com/LuaJIT/LuaJIT/issues/593

**Describe the solution you'd like**

Upgrading bundled LuaJIT and support ARM64 Windows.

**Describe alternatives you've considered**

Currently, LuaJIT is disabled for ARM64 Windows.

**Additional context**

ARM64 Windows is just happened to be shipped due to Surface laptop and Copilot+PC which are shipped with Snapdragon X Elite/Plus which is built on top of AArch64 architecture.

**Comment by edsiper** [comment]
fixed in #9044
