### ISSUE TITLE
Core: Fluent Bit's http server does not respond when enabling keepalive and failed to upgrade to HTTP/2 

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-bit#9030]
## Bug Report

**Describe the bug**

When failed to upgrade HTTP/2 from HTTP/1.1 with `http2 true` in input plugins, enabling keepalive is harmful because HTTP response does not happen and stale.
This behavior causes this https://github.com/fluent/fluent-bit/issues/9010 type of issues.
Meanwhile, we need to disable keepalive on internal of http server

In this PR https://github.com/fluent/fluent-bit/pull/9019, we actually disable keepalive automatically when HTTP/2 upgrade is failed.

**Expected behavior**

When enabling keepalive, the HTTP response should be returned to callee.
 

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by edsiper** [comment]
fixed in #9036
