### ISSUE TITLE
Fluent Bit 3.1.0 build breaks (luajit)

### ISSUE THREAD

**Issue by drbugfinder-work** [fluent/fluent-bit#9062]
## Bug Report
```
[2024-07-09T06:36:57.522Z] [ 33%] Built target minilua
[2024-07-09T06:36:57.522Z] [ 33%] Generating luajit_relver.txt
[2024-07-09T06:36:57.522Z] fatal: not a git repository (or any of the parent directories): .git
[2024-07-09T06:36:57.522Z] make[2]: *** [lib/luajit-cmake/CMakeFiles/buildvm_arch_h.dir/build.make:84: lib/luajit-cmake/luajit_relver.txt] Error 128
[2024-07-09T06:36:57.522Z] make[2]: *** Deleting file 'lib/luajit-cmake/luajit_relver.txt'
[2024-07-09T06:36:57.522Z] make[1]: *** [CMakeFiles/Makefile2:4607: lib/luajit-cmake/CMakeFiles/buildvm_arch_h.dir/all] Error 2
[2024-07-09T06:36:57.522Z] make[1]: *** Waiting for unfinished jobs....
```
**Describe the bug**
Build process breaks when building lua target. Happens since 3.1.0
Might be related to https://github.com/fluent/fluent-bit/commit/7ee1b357cc0d80acefb0153aa69edc8e45b2110e and/or https://github.com/fluent/fluent-bit/commit/1267204aaad584c893526d3d01b2bdf377f396bc

**Your Environment**
* Version used: 3.1.0
* Operating System and version: Ubuntu 24.04, Docker container

**Comment by drbugfinder-work** [comment]
cc @cosmo0920 @edsiper

**Comment by drbugfinder-work** [comment]
Reason seems to be that we are not building from git repo, but from extracted zip. As workaround removal of git command/package works.

**Comment by drbugfinder-work** [comment]
> This could be caused by this line: https://github.com/zhaozg/luajit-cmake/blob/18a430d8000884a20cd753e805892d3d26209727/LuaJIT.cmake#L412
> 
> LuaJIT always assumes there is a .git directory to generate luajit_relver.txt for showing the commit date as unit timestamp.
Thank you, I also found that.

However, I think this is a bad assumption. Currently there is this situation (like in our build), where git is installed, but the sources are not in a git repo. This should be patched out (like it is possible to build entirely without git installed https://github.com/fluent/fluent-bit/commit/7ee1b357cc0d80acefb0153aa69edc8e45b2110e)

**Comment by cosmo0920** [comment]
Our use case is all covered with your pointed out commit. Could you send your patch as a PR?

**Comment by drbugfinder-work** [comment]
I have no patch, yet. I can have a look.

I'm just saying that this is not documented in the `README` or `Build and Install` documentation that it is now necessary to clone Fluent Bit sources as a git repo - in the past it wasn't necessary, so it's a regression.

**Comment by patrick-stephens** [comment]
Related https://github.com/fluent/fluent-bit/issues/9064
