### ISSUE TITLE
Server/Hostname should print on payload using filter eventhough in payload value is not present

### ISSUE THREAD

**Issue by pranavsankar07** [fluent/fluent-bit#9067]
Hi Folks,

I'm new to Fluenbit, Recently we've configured and tested the fluentbit & S3 functionality for sending logs to S3 buckets.

I'm sending apps logs via fluentbit to S3 and its successful, But for some payloads the hostname was not present and i need hostname tag/value to be present in payload (data sent to S3).

Is there any way which i can determine from which server logs are originating in Fluent Bit and then add this server information to the payload ?

BR
Pranav

**Comment by patrick-stephens** [comment]
What inputs are you using?
You can always just add an extra tag into your records anyway with the hostname in it.

**Comment by pranavsankar07** [comment]
Below input i'm using, @patrick-stephens Can you help me how can i extract/add the hostname which sends the logs even though its not in payload.

[INPUT]
    name tail
    Tag  nginx-log
    path /var/log/*.log
    read_from_head true
    parser nginx
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10
