### ISSUE TITLE
how to set file roll over base on file size or day when use file out put plugin

### ISSUE THREAD

**Issue by huangyu2019** [fluent/fluent-bit#9079]
**Is your feature request related to a problem? Please describe.**

when i use file out put plugin there is no scrolling feature found, since the output file gets bigger day by day as application running more than 1 month  or more 
**Describe the solution you'd like**

I hope it can roll over the out put file  base on file size or time such as what log4j RollingFileAppender done 
**Describe alternatives you've considered**

**Additional context**

**Comment by patrick-stephens** [comment]
Typically this would be controlled by something else like `logrotate` and then is common for all files on the host.
