### ISSUE TITLE
out_nats core dump (memory corruption) if Tag string is too long (about 26+ chars)

### ISSUE THREAD

**Issue by stevelr** [fluent/fluent-bit#909]
## Bug Report
out_nats plugin causes core dump ("memory corruption") if Tag is more than about 26 chars

**Describe the bug**
Root cause
  flb_malloc on line 192 of plugins/out_nats/nats.c doesn't allocate enough memory and snprintf on following line overwrites the buffer and causes memory corruption.

potential fix:
  instead of `flb_malloc(json_len + 32)`
  use:    `flb_malloc(json_len + tag_len + 32)`
 
**To Reproduce**
(Assumes you have docker and nc (netcat) installed)
1. Save this file as ./fb.conf: [fb.conf.txt](https://github.com/fluent/fluent-bit/files/2578913/fb.conf.txt) 
2. start nats server in background ```docker run --rm -d --name nats-test -p 4222:4222 nats:latest```
3. start fluent-bit in foreground ```fluent-bit -c fb.conf```
4. in another terminal, send a couple TCP messages to fluent-bit
```
# you need to send at least two for the memory corruption to be detected
echo '{"Subject":"stuff"}' | nc -c 127.0.0.1 7777
sleep 1
echo '{"Subject":"stuff"}' | nc -c 127.0.0.1 7777
```

**Expected behavior**
no crash.

If you change Tag in fb.conf to a short word such as "MyTag", no crash occurs.  I didn't see any documented length limits for 'Tag', but even if there were documented limits, the C implementation should be more defensive.

**Screenshots**

**Your Environment**

* Version used: fluent-bit v0.14.2
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?): Arch linux
* Server type and version:
* Operating System and version: Arch linux 4.18.14-arch1-1-ARCH
* Filters and plugins: tcp,nats

**Additional context**

I noticed the bug while reading the code, then built a test case to reproduce.

**Comment by edsiper** [comment]
fixed by #930
