### ISSUE TITLE
Kubernetes annotation parser overrides docker parser

### ISSUE THREAD

**Issue by MichaelMitchellM** [fluent/fluent-bit#911]
## Bug Report

**Describe the bug**
Can't use both the docker (json) parser and the kubernetes 

**To Reproduce**
- Deploy in Kubernetes
- Create a test logging pod with parser annotation selecting some regex parser with a testing regex
- Look at the test logging pod's messages in kibana
- Notice that the docker json parsing didn't happen, only the annotated parser did stuff

**Expected behavior**
Use docker parser's Decode_Field_As for JSON messages and the Kubernetes annotation parser for non JSON messages.

* Kubernetes:
```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Version used:
```
image: fluent/fluent-bit:0.13.4
```
* Configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Retry_Limit     False
        Time_Key        es_time

  parsers.conf: |
    [PARSER]
        Name    test
        Format  regex
        Regex ^(?<testvalue>[^\s]*)

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   json       log     try_next
        Decode_Field_As   escaped    log

```

* Filters and plugins:
Docker parser and test parser.
Kubernetes filter plugin.

**Additional context**
If I log JSON, I would like to use the docker parser to decode the JSON docker log field.
Otherwise, I would like to use a custom parser to regex the non-JSON docker log field.

The reason for wanting these options:
I am making a golang based server and I use other packages that have their own log messages.
I would like to log JSON formatted messages so they can provide fields indexable by elasticsearch and for the third party stuff I would like to extract somethings with a regex and keep the regular log message. The main things I want to regex out of the third party stuff is like line number and file path.

**Comment by donbowman** [comment]
I think you want to try Merge_Log option on your kubernetes filter to achieve this.

**Comment by edsiper** [comment]
Please confirm if you can reproduce the problem with image  fluent/fluent-bit:0.14.7
