### ISSUE TITLE
Influxdb output does not handle integer value correctly

### ISSUE THREAD

**Issue by jcdauchy-moodys** [fluent/fluent-bit#9120]
## Bug Report

**Describe the bug**
 If value is an integer, using Influxdb line protocol, we should suffix the value with an "i", this is not the case, so all values are sent as float

- Steps to reproduce the problem:

create a measurement in influxdb database with a column of type integer, then push some data as integer type in fluentbit, your data will not be pushed.

**Expected behavior**

**Screenshots**

[2024/07/22 12:55:13] [error] [output:influxdb:influxdb.1] http_status=400 {"error":"partial write: field type conflict: input field \"myintergerfiled\" on measurement \"test\" is type integer, already exists as type float dropped=5"}

**Your Environment**

* Version used: 2.1.7 and others
* Configuration:
* Environment name and version : kubernetes 1.30
* Filters and plugins:

Influxdb output

**Additional context**

I tried to push a log to an influxdb measurement already created with an integer column type and it was complainging that my value is FLOAT :

**Comment by Athishpranav2003** [comment]
@jcdauchy-moodys are you working on this or can i make a PR for this real quick?
I guess i understood the problem here but just need to make sure if you are working on this currently

**Comment by cosmo0920** [comment]
Hi, I'm tried to create a patch for fixing this: https://github.com/fluent/fluent-bit/pull/9301
Could you add a reproducible steps for this issue?

**Comment by jcdauchy-moodys** [comment]
Sorry about the late reply, as it causes a breaking change in the "influxdb" schema of each impacted measurement, I did not dare to make it available for all :(
