### ISSUE TITLE
fluentbit.io/parser not working with nginx if not correct tag

### ISSUE THREAD

**Issue by hoa-tran** [fluent/fluent-bit#9129]
## Bug Report

**Describe the bug**
I have an input nginx from tail. I setting annotation for nginx `fluentbit.io/parser: custom-k8s-nginx-ingress` to using a custom parse (likely `k8s-nginx-ingress` parser default). When I set tag for tail is `nginx.*` it working but when I change **Tag** `nginx.*` and all **Match** of it to new name such as `nginx2.*`, this parse not working

**To Reproduce**
- Install fluentbit using helm chart.
- Add annotations to nginx.
- Config setting like `Configuration` below.
- Change `Tag` in **INPUT** and `Match` in **FILTER** to `nginx2.*`
Ref: https://braindose.blog/2022/07/18/monitor-and-analyze-nginx-ingress-controller-logs-on-kubernetes-using-elasticsearch-and-kibana/

**Expected behavior**
I can set another tag for tail with nginx because I have some nginx and I want to apply some special filter and output for each. 
**Screenshots**
- Data when set  tag to `nginx2.*` :
![Data when set  tag to nginx2.*](https://github.com/user-attachments/assets/d69986c7-424a-4170-b350-2fe7e1a28d64)
- Expected data:
![Expected data](https://github.com/user-attachments/assets/2f4ba120-3851-49e0-9f1d-f88341a2a56d)

**Your Environment**
* Version used: `fluent-bit:3.1.3`
* Configuration:
```bash
[INPUT]
    Name                tail
    Path                /var/log/containers/*ingress-nginx-controller*nginx_controller*
    multiline.parser    docker, cri
    Tag                 nginx.*
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On

[FILTER]
    Name                kubernetes
    Match               nginx.*
    Merge_Log           On
    Merge_Log_Key       On
    Keep_Log            Off
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Buffer_Size         5MB
```
* Environment name and version (e.g. Kubernetes? What version?): `EKS v1.30.0`
* Server type and version: EKS
* Operating System and version: Linux
Thank for your help!

**Comment by patrick-stephens** [comment]
I think you need to look at the kube tag prefix setting here. Likely the change in tag leads to an error trying to look up the pod metadata. 

Using any non default kube.* tag requires adjusting the prefix on the filter. As you change it you need it to match what the tail input generates so it strips the relevant path off and just gives you the actual filename with only pod+namespace info.

**Comment by hoa-tran** [comment]
@patrick-stephens Thank for your reply. Can you give me an suggestion for this config?
```
[INPUT]
    Name                tail
    Exclude_Path        /var/log/containers/*logging_elastic*, /var/log/containers/*ingress-nginx-controller*nginx_controller*, /var/log/containers/*fluent_fluent-bit*
    Path                /var/log/containers/*.log
    multiline.parser    docker, cri
    Tag                 kube.*
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On
[INPUT]
    Name                systemd
    Tag                 host.*
    Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
    Read_From_Tail      On
[INPUT]
    Name                tail
    Exclude_Path        /var/log/containers/*ingress-nginx-controller*internal-nginx_controller*
    Path                /var/log/containers/*ingress-nginx-controller*nginx_controller*
    multiline.parser    docker, cri
    Tag                 public_nginx.*
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On
[INPUT]
    Name                tail
    Path                /var/log/containers/*ingress-nginx-controller*internal-nginx_controller*
    multiline.parser    docker, cri
    Tag                 nginx.*
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On
    ```

**Comment by hoa-tran** [comment]
@patrick-stephens Thank for your help. I try with this simple configuration and it still not working. I think maybe my **annotations** `fluentbit.io/parser: custom-k8s-internal-nginx-ingress` is not working when I chang tag from `nginx.*` to `nginx2.*`

```
[INPUT]
    Name                tail
    Path                /var/log/containers/*ingress-nginx-controller*internal-nginx_controller*
    multiline.parser    docker, cri
    Tag                 nginx2.*
    Mem_Buf_Limit       5MB
    Skip_Long_Lines     On

[FILTER]
    Name                kubernetes
    Match               nginx2.*
    Merge_Log           On
    Keep_Log            Off
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Buffer_Size         5MB  outputs: |
[OUTPUT]
    Name                es
    Match               nginx2.*
    Logstash_Format     On
    Logstash_Prefix     eks-internal-nginx-obs
    Retry_Limit         False
    Host                elasticsearch-es-http.logging
    Port                9200
    HTTP_User           elastic
    HTTP_Passwd         xxxxxxxxxxx
    tls                 On
    tls.verify          Off
    Suppress_Type_Name  On
    Replace_Dots        On
    Buffer_Size         5MB

 ## customParsers
[PARSER]
    Name                docker_no_time
    Format              json
    Time_Keep           Off
    Time_Key            time
    Time_Format         %Y-%m-%dT%H:%M:%S.%L
[PARSER]
    Name                custom-k8s-internal-nginx-ingress
    Format              regex
    Regex               ^(?<http_x_forwarded_for>[^ ]*) (?<remote_addr>[^ ]+) - (?<remote_user>[^ ]+) \[(?<time_local>[^\]]+)\] "(?<http_method>[A-Z]+) (?<http_path>[^ ]+) HTTP\/\d\.\d" (?<status>[^ ]+) (?<body_bytes_sent>[^ ]+) "(?<http_referer>[^"]+)" "(?<http_authorization>[^"]+)" "(?<http_user_agent>[^"]+)" (?<request_length>[^ ]+) (?<request_time>[^ ]+) \[(?<proxy_upstream_name>[^\]]*)\] \[(?<proxy_alternative_upstream_name>[^\]]*)\] \[(?<upstream_addr>[^\]]*)\] \[(?<upstream_response_length>[^\]]*)\] \[(?<upstream_response_time>[^\]]*)\] \[(?<upstream_status>[^\]]*)\] (?<req_id>[^ ]+) "(?<request_body>[^"]*)" "(?<request_filename>[^"]+)" "(?<host>[^"]+)" "(?<cookie_access_token>[^"]*)" "(?<cookie_userId>[^"]*)" "(?<cookie_vdmsAccesstoken>[^"]*)" "(?<response_body>[^"]*)"$
    Time_Key            time
    Time_Format         %d/%b/%Y:%H:%M:%S %z
[PARSER]
    Name                catchall
    Format              regex
    Regex               ^(?<message>.*)$
```

**Comment by patrick-stephens** [comment]
Please read my original comment and look at the linked article, just changing the tag will break things unless you also change the kube_tag_prefix: https://github.com/fluent/fluent-bit/issues/9129#issuecomment-2256558866

I try to go over it in the linked article, your `kube_tag_prefix` needs to strip away everything but the final filename to then use that to query the K8S API.

Turn on debug logging and check the errors from the K8S API server - I bet it's saying it cannot get metadata for your pods which means it has no labels so knows nothing about your custom parser.
