### ISSUE TITLE
Fluent-bit doesn't track file changes after startup in detached mode

### ISSUE THREAD

**Issue by joshualan** [fluent/fluent-bit#914]
## Bug Report

**Describe the bug**
After installing fluent-bit v0.14.5 on a Centos 7 docker container, fluent-bit will only work immediately on startup and then not report on any changes to a tracked log file with the tail input plugin. When checking the process via `ps aux`, the fluent-bit process will still be there.

**To Reproduce**
- Steps to reproduce the problem:
  - Install fluent-bit on a Centos 7 docker container
  - Run it on either the background `fluent-bit -c myconf.conf &` or in daemon mode `fluent-bit -d -c myconf.conf`
    - This tracked file uses the tail input plugin
  - Note that on startup, fluent-bit will report changes to the tracked file once.
  - Append output to the tracked file
  - fluent-bit did not see the change to the tracked file and will not see any tracked file further changes.

**Expected behavior**
fluent-bit should track new appends to the file. The exact configuration on the same Docker container works on a differently built machine.

**Your Environment**

* Version used: 0.14.5
* Configuration: EFK 
* Environment name and version (e.g. Kubernetes? What version?): Docker Client & Server 18.03.1-ee-3
* Server type and version: 
* Operating System and version: RHEL 7.3
* Filters and plugins:

**Additional context**

A process is running on the CentOS container that appends output log files. Fluent-bit sends the log files to Elasticsearch, which is on another Docker container.

The containers are set up via `docker-compose`. This problem only occurs on some machines (like this one) and works flawlessly on most others. 

Configuration File:
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name   tail
    path   /logs/log.[0-9]*.txt
    Tag    log_tag

[OUTPUT]
    Name  es
    Match log*tag
    Host  elasticsearch
    Port  9200
    Index server_log
    Type  docker
    Retry_Limit False   
```

**Comment by edsiper** [comment]
How are you counting the logs?

**Comment by edsiper** [comment]
ping

**Comment by joshualan** [comment]
I'm not exactly sure what you mean but the /logs folder is a symbolic link to the folder where the logs are being generated.

**Comment by esenmetu92** [comment]
We are facing with the same problem. We have set the db as path/to/logs.db and intput as tail, output as stdout. When we changed the file, we do not see the changes in the output. But, if we stop and restart the fluentbit.exe than new changes are written to the output.

**Comment by frank90086** [comment]
I am facing this problem and don't know how to fix it.

I mount fluent-bit log path to application log path, fluent-bit tail logs when startup (because Read_from_Head set true), and do nothing until application stop then flush all of un-flushed logs to output.

#### Fluent-bit version
V1.6.10
#### Docker Image
fluent/fluent-bit:1.6.10
#### Application lang
dotnet core 3.1
#### Log provider
serilog
#### config
```
[SERVICE]
    Flush               5
    Daemon              off
    Log_Level           trace
    Parsers_File        parsers.conf

@INCLUDE input.conf
# @INCLUDE filter.conf
@INCLUDE output.conf

[INPUT]
    Name                tail
    Path                /fluentbit/log/_.log
    Tag                 *
    Read_from_Head      on
    Parser              tail_log
    Refresh_Interval    5

[OUTPUT]
    Name                forward
    Match               *
    Host                fluentd
    Port                24224
    Tag                 $TAG[2]
    Retry_Limit         3

[PARSER]
    Name                tail_log
    Format              json
```
