### ISSUE TITLE
[ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.face

### ISSUE THREAD

**Issue by aman-marutitech** [fluent/fluent-bit#9148]
i'm using fluentbit v3.1 to transfer container logs to s3 bucket
below is values.yaml file which contains configuration details:

config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_amazon-guardduty_*.log,/var/log/containers/*_default_*.log,/var/log/containers/*_istio-system_*.log,/var/log/containers/*_kiali-operator_*.log,/var/log/containers/*_kube-node-lease_*.log,/var/log/containers/*_kube-public_*.log,/var/log/containers/*_kube-system_*.log,/var/log/containers/*_lacework_*.log,/var/log/containers/*_newrelic_*.log,/var/log/containers/*_nginx*.log,/var/log/containers/*_istio-proxy*.log
        multiline.parser docker, cri
        Tag kube.<pod_name>.<namespace_name>.<container_name>.<container_id>
        Tag_Regex (?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<container_id>[a-z0-9]{64})\.log$
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_Tag_Prefix  kube.
        Kube_URL https://kubernetes.default.svc:443
        Merge_Log On
        Keep_Log Off
        Labels Off
        Annotations Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name s3
        Match kube.*
        bucket bucket_name
        region us-west-2
        total_file_size 100M
        use_put_object On
        compression gzip
        storage_class DEEP_ARCHIVE
        store_dir /tmp/fluent-bit/s3
        s3_key_format /$TAG[3]/%Y/%m/%d/log.txt.$UUID.gz
        s3_key_format_tag_delimiters .

after deploying fluentbit , when i checked fluentbit pod logs i'm getting below warning message
 [ warn] [filter:kubernetes:kubernetes.0] invalid pattern for given tag kube.fb-f67b89444.namespace.fb.9e3765ae67efcbb8089f47f7dc1f5a6c760ec47f435a29d26ffce6f49a55555a

fluentbit reads logs from this below path
/var/log/containers/fb-f67b89444-cr284_namespace_fb-d24e9f860f6140931ebf100579fa0587b6c94d2b1a44eb4c91858b2e7e666666.log

here fb-f67b89444-cr284 is pod name, namespace is namespace name,fb is container name,d24e9f860f6140931ebf100579fa0587b6c94d2b1a44eb4c91858b2e7e666666 is container id 

i have tried Kube_Tag_Prefix  kube.var.log.container.
but same issue

even if we get this warning message, fluentbit is creating container name folder in s3 bucket and uploading log files
how to solve this issue?

**Comment by patrick-stephens** [comment]
Is this related to https://github.com/fluent/fluent-bit/issues/8743#issuecomment-2067622939?

**Comment by aman-marutitech** [comment]
@patrick-stephens Yes, it's the same issue, i tried every possible ways like using parser,regex , but getting same warning messages in fluenbit pod logs.

**Comment by patrick-stephens** [comment]
Did the comment there resolve it then? That other comment says it was sorted but was a docs issue.

**Comment by aman-marutitech** [comment]
maybe it was sorted or resolved from their end based on their configuration, but the issue still remains for my configuration.
eventhough i'm getting warn messages ,but fluentbit able to filter container name and it's creating container name folder in s3, so i'm not sure that it's an expected issue or it's due to the latest fluentbit version
