### ISSUE TITLE
Fluentbit Version 3.1.2 and later: Too many open files error results in massive loss of loglines

### ISSUE THREAD

**Issue by JSchy65** [fluent/fluent-bit#9151]
I do some load testing with 50 logging container each creating about 45 loglines per second with about 100 chars per line (e.g. 50x 325.000 Lines/31 MB in 2 hours). The logs are collected by the **tail input plugin** and are written to a S3 bucket by the **AWS S3 output plugin**.

**With fluentbit Versions 3.0.7 and 3.1.1, this tests were passed successfully**. All loglines were written into the S3 bucket. No loss of loglines.

But with Versions > 3.1.1 (I tested with 3.1.2 and 3.1.4), after about 1 1/2 hours, the error "Too many open files" occured the first time and about 214.000 times again during my test. From 325.000 loglines 148.000 got lost (per container). The issue occurred during each test run. It is not intermittent.

**The Version 3.1.1 is the last version not having this issue**.
All tests were done with the same configuration on the same environment (Ubuntu 22.04 LTS).

_Excerpt from the logfile_:

Jul 31 12:36:57 clientA fluent-bit[2038]: [2024/07/31 12:36:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=5268541 watch_fd=912 name=/var/lib/docker/containers/146e0c94126e49ba235a886457edcb33ca6e19440caabf272a395090a8fb1c5b/146e0c94126e49ba235a886457edcb33ca6e19440caabf272a395090a8fb1c5b-json.log
Jul 31 12:37:57 clientA fluent-bit[2038]: [/tmp/fluent-bit/lib/chunkio/src/cio_file_unix.c:410 errno=24] **Too many open files**
Jul 31 12:37:57 clientA fluent-bit[2038]: [2024/07/31 12:37:57] [error] [input chunk] could not create chunk file: emitter.2:2038-1722422277.796466512.flb
Jul 31 12:37:57 clientA fluent-bit[2038]: [2024/07/31 12:37:57] [error] [input chunk] no available chunk
Jul 31 12:37:57 clientA fluent-bit[2038]: [2024/07/31 12:37:57] [error] [input:emitter:containerlogging-rewrite-tag-s3-emitter] error registering chunk with tag: containerlogging.clientA.logsimulator-0037
Jul 31 12:37:57 clientA fluent-bit[2038]: [2024/07/31 12:37:57] [error] [in_emitter] error registering chunk with tag: containerlogging.clientA.logsimulator-0037

The log is full of such sections:
_[vm-2024-07-31-312-2GB.zip](https://github.com/user-attachments/files/16452269/vm-2024-07-31-312-2GB.zip)_:

[INPUT]
    name     tail
    tag      containerlogging
    path     /var/lib/docker/containers/*/*-json.log
    path_key filename
    multiline.parser docker
    skip_empty_lines true
    storage.type filesystem
    db       /var/fluent/storage/db

[FILTER]
    Name   lua
    Match  containerlogging
    script /etc/fluent-bit/get_container_name.lua
    call   get_container_name

[FILTER]
    name  rewrite_tag
    match containerlogging
    rule  $container ^(.*)$ containerlogging.$hostname.$1 false
    emitter_name          containerlogging-rewrite-tag-s3-emitter
    emitter_storage.type  filesystem
    emitter_mem_buf_limit 2GB

[OUTPUT]
    name   s3
    match  containerlogging.*
    region eu-central-1
    bucket .......
    s3_key_format /$TAG[1]/%Y-%m-%d/containerlogs/$TAG[2]/%H-%M-%SZ-$INDEX.log
    s3_key_format_tag_delimiters .
    preserve_data_ordering true
    static_file_path false
    log_key log
    upload_timeout 1800s

The lua script getting the container name is similar to get_container_name here:
https://stackoverflow.com/questions/73000422/how-to-classify-docker-container-logs-by-container-name-using-fluent-bit

**Comment by edsiper** [comment]
how many chunks exists in your filesystem path when you test the newest version ?

**Comment by JSchy65** [comment]
The Tail Input Plugin may cause the problem.

There are 1024 file handles allowd for fluentbit on my test system:
  sudo systemctl show fluent-bit | grep LimitNOFILE
     LimitNOFILE=524288
     LimitNOFILESoft=1024

I wanted to test, whether the tail input plugin can handle the file rotation of the log files correctly under heavy load.
Therefore I configured the containers to rotate their log files approximately every 5 minutes under the above mentioned workload:
   --log-opt max-size=2300k
   --log-opt max-file=100

After about 1 1/2 hours of execution of the workload test, there will be a total of about 900 Logfiles.
This is near to the maximum allowed open files.

**I assume, that the tail plugin opens the log files, but does not close them again if this file is no longer relevant for the plugin.**

This may lead to the "too many files open" error once the number of still opened logfiles is getting too big.

**Comment by edsiper** [comment]
remember that the limit is for `file descriptors`, that considers sockets, pipes, timers, inotify file descriptors and many others. Give it more capacity like 4096.
