### ISSUE TITLE
[error] [/src/fluent-bit/plugins/in_kmsg/in_kmsg.c:311 errno=1] Operation not permitted

### ISSUE THREAD

**Issue by alexkayzer** [fluent/fluent-bit#9159]
## Bug Report

**Describe the bug**
Fluent-bit don't start

**To Reproduce**
Set config
```
[INPUT]
    Name   kmsg
    Tag    kernel

[OUTPUT]
    Name   stdout
    Match  *
```

**Your Environment**
* Version used: 3.0.4
* Configuration: default
* Environment name and version (e.g. Kubernetes? What version?): k8s 1.26
* Operating System and version: Talos 1.4.6
* Filters and plugins: default

securityContext: 
          privileged: true
          runAsUser: 0

**Comment by patrick-stephens** [comment]
What's the full pod spec? I think this will need host level access.
