### ISSUE TITLE
Allow you to specify the port when working with the kinesis plugin.

### ISSUE THREAD

**Issue by azalio** [fluent/fluent-bit#9160]
Fluentbit has a [Kinesis](https://docs.fluentbit.io/manual/pipeline/outputs/kinesis ) output plugin.

However, in the Fluentbit code, the port 443 is [directly](https://github.com/fluent/fluent-bit/blob/master/plugins/out_kinesis_streams/kinesis.c#L258.) specified. 

My cloud provider, which is not AWS, supports the Kinesis protocol, but the endpoint uses port 8443. 
Unfortunately, I cannot specify the port number in the Fluent Bit configuration for the Kinesis plugin, so I am unable to use Fluentbit in this scenario. 
Could you please allow me to configure the port number for the Kinesis plugin?

**Describe the solution you'd like**
```
[OUTPUT]
    Name kinesis_streams
    ...
    stream          /topic
    endpoint      https://some-endpoint
    port              8443
```

**Comment by Athishpranav2003** [comment]
Hey guys
I guess i can work on this quick,
Will create PR soon for the same

**Comment by Athishpranav2003** [comment]
@azalio I have created the PR and it compiles successfully
I need your help in testing
Can you test the code using the PR?
