### ISSUE TITLE
[systemd] Crash with SIGBUS on log rotation

### ISSUE THREAD

**Issue by orgads** [fluent/fluent-bit#9167]
## Bug Report

**Describe the bug**
When logrotate is activated, and the log is rotated, fluent-bit sometimes crashes with SIGBUS.

On this occasion, rsyslogd also crashed with SIGBUS.

It doesn't easily reproduce, but it happens to one of our customers several times a day on RHEL 8 machines.

**To Reproduce**
```
[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              systemd
    Path              /run/log/journal
    Tag               systemd
    Systemd_Filter    _COMM=conmon
    Lowercase         On
    Strip_Underscores On
    DB                /fluent-bit/db/cursor.db

[FILTER]
    Name          rewrite_tag
    Match         systemd
    Rule          $container_tag ^.*$ $container_tag false
    emitter_mem_buf_limit 128MB

[OUTPUT]
    Name   forward
    Match  docker.*
    Host   ${FLUENT_FORWARD_HOST}
    Port   ${FLUENT_FORWARD_PORT}
```

**Expected behavior**
The application should not crash :)

**Screenshots**
```
Aug 04 13:26:59 server fluent-bit[3070]: [2024/08/04 10:26:59] [debug] [task] destroy task=0x7fe105037400 (task_id=0)
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [task] created task=0x7fe105037900 id=0 OK
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [output:forward:forward.0] request 777 bytes to flush
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [output:forward:forward.0] task_id=0 assigned to thread #1
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [upstream] KA connection #29 to fluentd:24224 has been assigned (recycled)
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [task] destroy task=0x7fe105037900 (task_id=0)
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [upstream] KA connection #29 to fluentd:24224 is now available
Aug 04 13:27:00 server fluent-bit[3070]: [2024/08/04 10:27:00] [debug] [out flush] cb_destroy coro_id=12513
Aug 04 13:27:01 server systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Aug 04 13:27:01 server systemd[1]: Started Process Core Dump (PID 537762/UID 0).
Aug 04 13:27:01 server systemd[1]: Started Process Core Dump (PID 537764/UID 0).
Aug 04 13:27:01 server systemd-coredump[537766]: Resource limits disable core dumping for process 3080 (fluent-bit).
Aug 04 13:27:01 server systemd-coredump[537766]: [🡕] Process 3080 (fluent-bit) of user 200000 dumped core.
Aug 04 13:27:01 server systemd-coredump[537767]: Resource limits disable core dumping for process 1217 (rsyslogd).
Aug 04 13:27:01 server systemd-coredump[537767]: [🡕] Process 1217 (rsyslogd) of user 0 dumped core.
Aug 04 13:27:01 server systemd[1]: systemd-coredump@1-537762-0.service: Succeeded.
Aug 04 13:27:01 server systemd[1]: systemd-coredump@0-537764-0.service: Succeeded.
Aug 04 13:27:01 server systemd[1]: rsyslog.service: Main process exited, code=killed, status=7/BUS
Aug 04 13:27:01 server systemd[1]: rsyslog.service: Failed with result 'signal'.
```
**Your Environment**
* Version used: 3.1.3
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): Podman 4.9.4
* Server type and version: Unsure
* Operating System and version: RHEL 8
* Filters and plugins: See above

**Comment by patrick-stephens** [comment]
Can you enable core dumps so we can get a stack trace?

**Comment by patrick-stephens** [comment]
The container logs should have a stack trace then.

**Comment by orgads** [comment]
I can see the signal handler when I send signal 11 like you did here, but in my case it doesn't appear. Will a core dump help?

**Comment by patrick-stephens** [comment]
Are you grabbing stderr as well as stdout?
It may be host level limits as well or locked down container deployments that need it enabling.

**Comment by orgads** [comment]
Yes. All the logs are written to stderr, and I do see other logs.

**Comment by edsiper** [comment]
@patrick-stephens not sure if possible but having a custom image that runs with Valgrind on it will be helpful

**Comment by orgads** [comment]
Looks like it was already reported for systemd https://github.com/systemd/systemd/issues/33277 and according to that issue, it is fixed in recent systemd.

I'll ask them to upgrade systemd if possible.

**Comment by patrick-stephens** [comment]
> @patrick-stephens not sure if possible but having a custom image that runs with Valgrind on it will be helpful

The debug image includes valgrind along with a load of other tools: https://github.com/fluent/fluent-bit/blob/725640616fa9127f1ea5922c4c3076806830c70a/dockerfiles/Dockerfile#L222-L228

**Comment by edsiper** [comment]
Not a Fluent Bit issue, fixed in Systemd
