### ISSUE TITLE
[record_modifier]Add field from Tag

### ISSUE THREAD

**Issue by zhijiangwang** [fluent/fluent-bit#917]
I run fluent-bit 0.13.5 with docker.
I want to get some metadata from tag.
In fluentd I can use **tag_parts[0]** to get value.How can I config to get some value in fluent-bit?
Please help me.

**Comment by anoopvm** [comment]
I'm looking for the same use-case. Is there a way to get it done in fluent-bit?

**Comment by calumah** [comment]
I have the same problem, I succeeded by using filter_lua but strangely enough it is not in the documentation...

```
[FILTER]
    Name lua
    Match *
    script add_tag.lua
    call add_tag
```

```lua
function add_tag(tag, timestamp, record)
    -- Add type from tag
    record.my_choosen_field = tag
    -- Return -1 = skip / 0 = record not modified / 1 = record modified repack
    return 1, timestamp, record
end
```

Don't know about performance of this filter_lua but it works....

Also see https://github.com/fluent/fluent-bit/issues/629

**Comment by calumah** [comment]
Just found https://github.com/fluent/fluent-bit/blob/master/scripts/append_tag.lua ...

**Comment by JeffLuoo** [comment]
Hi I have the same use-case and am wondering that do you come out any idea other than Lua script? As Lua script might have performance issue...
