### ISSUE TITLE
[error] [config] error in C:\conf\fluent-bit.conf:5: undefined value - check config is in valid classic format

### ISSUE THREAD

**Issue by Tomas-Big-Z** [fluent/fluent-bit#9181]
## Bug Report

**Describe the bug**
Fluent Bit exits with an error at startup

**To Reproduce**

Create this simple config:

```
[SERVICE]

	flush	5
	log_level	debug

[INPUT]
	Name              tail
	path              C:\Program Files\fluent-bit\sample_source.log
	Tag               dmskrnl_raw
	Read_from_Head    True    


[OUTPUT]
	Name stdout
	Match *
```

Launch Fluent Bit:

`fluent-bit -c "C:\conf\fluent-bit.conf"`

Get error:

```
[2024/08/09 15:30:39] [error] [config] error in C:\conf\fluent-bit.conf:5: undefined value - check config is in valid classic format
[2024/08/09 15:30:39] [error] configuration file contains errors, aborting.
```

**Expected behavior**

The contents of the source file "sample_source.log" should be displayed in STDOUT

**Screenshots**

![image](https://github.com/user-attachments/assets/7985d927-f470-4760-b071-d39d97319438)

![image](https://github.com/user-attachments/assets/c0efdc1d-2d6b-47ff-a327-e147593fa375)

**Your Environment**

* Version used: 3.1.4
* Configuration: default
* Environment name and version (e.g. Kubernetes? What version?): Windows
* Server type and version: Windows Server 2022
* Operating System and version:  Version 21H2
* Filters and plugins: default

**Additional context**
I made sure the .config file is properly indented (no mix of tabs & spaces, no blank lines with indentation).
If i comment out the line 5, the same error is displayed for line 10, if i comment out line 10, the same error is displayed for line 23, and so ad infinitum.
Text editor uses UTF-8 encoding, no issues when working with Fluentd configs.

**Comment by edsiper** [comment]
I think the problem is because of the mix of Tabs and spaces, use only spaces works right away:

```
[SERVICE]
  flush	     5
  log_level  debug

[INPUT]
  Name              tail
  path              C:\Program Files\fluent-bit\sample_source.log
  Tag               dmskrnl_raw
  Read_from_Head    True

[OUTPUT]
  Name  stdout
  Match *

```
