### ISSUE TITLE
/api/v2/metrics/prometheus endpoint doesn't follow prometheus 2.0 exposition format

### ISSUE THREAD

**Issue by shuaich** [fluent/fluent-bit#9191]
## Bug Report

**Describe the bug**
Lines belonging to the same metric name are not grouped returned by `curl -s http://127.0.0.1:2020/api/v2/metrics/prometheus`. 

```
# HELP fluentbit_input_bytes_total Number of input bytes.
# TYPE fluentbit_input_bytes_total counter
fluentbit_input_bytes_total{name="load-generator1"} 23789838413
# HELP fluentbit_input_records_total Number of input records.
# TYPE fluentbit_input_records_total counter
fluentbit_input_records_total{name="load-generator1"} 49079979
# HELP fluentbit_input_files_opened_total Total number of opened files
# TYPE fluentbit_input_files_opened_total counter
fluentbit_input_files_opened_total{name="load-generator1"} 1
# HELP fluentbit_input_bytes_total Number of input bytes.
# TYPE fluentbit_input_bytes_total counter
fluentbit_input_bytes_total{name="load-generator2"} 23746472970
# HELP fluentbit_input_records_total Number of input records.
# TYPE fluentbit_input_records_total counter
fluentbit_input_records_total{name="load-generator2"} 48988492
# HELP fluentbit_input_files_opened_total Total number of opened files
# TYPE fluentbit_input_files_opened_total counter
fluentbit_input_files_opened_total{name="load-generator2"} 1

# TYPE fluentbit_build_info gauge
fluentbit_build_info{hostname="gke-dd62a60a025549a792c0-d934-3422-vm",version="3.1.4",os="linux"} 1723447542
```

It doesn't follow Prometheus exposition format[1] in that "All lines for a given metric must be provided as one single group, with the optional HELP and TYPE lines first (in no particular order)." and breaks prometheus clients decoding data from this endpoint[2].

[1]https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#grouping-and-sorting
[1]https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/main.go#L215

**To Reproduce**
- Steps to reproduce the problem:
Run fluentbit 3.1.4 and run `curl -s http://127.0.0.1:2020/api/v2/metrics/prometheus`
**Expected behavior**

All lines belonging to the same metric name are grouped with one # HELP and # TYPE line as in `curl -s http://127.0.0.1:2020/api/v1/metrics/prometheus` endpoint.

```
# HELP fluentbit_input_bytes_total Number of input bytes.
# TYPE fluentbit_input_bytes_total counter
fluentbit_input_bytes_total{name="kube-apiserver"} 511265158 1723480469060
fluentbit_input_bytes_total{name="kube-scheduler"} 2851772 1723480469060
fluentbit_input_bytes_total{name="load-generator1"} 24216203589 1723480469060
fluentbit_input_bytes_total{name="load-generator2"} 24173321562 1723480469060
```

**Screenshots**

**Your Environment**

* Version used: fluentbit 3.1.4
* Configuration: Prometheus exporter plugin not used.
* Environment name and version (e.g. Kubernetes? What version?): k8s 1.30+
* Server type and version:
* Operating System and version: k8s 1.30+
* Filters and plugins:

**Additional context**

**Comment by shuaich** [comment]
Lines are grouped for `/api/v1/metrics/prometheus` result: https://github.com/fluent/fluent-bit/blob/13db2ee143d13a27004b37c7c55715eb192276e2/src/http_server/api/v1/metrics.c#L416

**Comment by patrick-stephens** [comment]
Possibly related to https://github.com/fluent/fluent-bit/issues/5465
