### ISSUE TITLE
[v3.1.5] Time_System_Timezone feature fails to work when DST is in effect

### ISSUE THREAD

**Issue by gwharton** [fluent/fluent-bit#9197]
## Bug Report

When DST is in effect, the Time_System_Timezone feature outputs the wrong times.

**To Reproduce**

Lets assume I have a service that outputs logs with local time format, with no timezone specifiers.

**TEST DATE 1**
UTC Time : 20/01/2024 10:00:00 UTC 
Local Time : 20/01/2024 10:00:00 GMT (UTC+0) for Europe/London Timezone
Timestamp : 1705744800

**TEST DATE 2**
UTC Time : 20/08/2024 10:00:00 UTC 
Local Time : 20/08/2024 11:00:00 BST (UTC+1) for Europe/London Timezone
Timestamp : 1724148000

```
tee /tmp/fluent-bit.conf >/dev/null <<'EOF'
[SERVICE]
    flush 1
    daemon Off
    log_level debug
    parsers_file /tmp/parsers.conf
    plugins_file /tmp/plugins.conf
    http_server Off
[INPUT]
    Name dummy
    Dummy {"time": "20/01/2024 10:00:00"}
[INPUT]
    Name dummy
    Dummy {"time": "20/08/2024 11:00:00"}
[FILTER]
    Name parser
    Match *
    Key_Name time
    Parser test-regex-parser
[OUTPUT]
    Name stdout
    Match *
EOF
tee /tmp/parsers.conf >/dev/null <<'EOF'
[PARSER]
    Name test-regex-parser
    Format regex
    Regex ^(?<time>.*)$
    Reserve_Data On
    Time_Key time
    Time_Format %d/%m/%Y %H:%M:%S
    Time_Keep On
    Time_System_Timezone On
EOF
tee /tmp/plugins.conf >/dev/null <<'EOF'
[PLUGINS]
EOF
TZ=Europe/London /opt/fluent-bit/bin/fluent-bit -c /tmp/fluent-bit.conf
```
Produces the output
```
[0] dummy.0: [[1705744800.000000000, {}], {"time"=>"20/01/2024 10:00:00"}]
[0] dummy.1: [[1724151600.000000000, {}], {"time"=>"20/08/2024 11:00:00"}]
```
1705744800.000000000 = GMT: Saturday, 20 January 2024 10:00:00
1724151600.000000000 = GMT: Tuesday, 20 August 2024 11:00:00 <-- INCORRECT

**Your Environment**
fluent-bit v3.1.5
Ubuntu 24.04

**Additional context**
Not setting `tm.tm_isdst` to -1 prior to the call to mktime would cause this

**Comment by braydonk** [comment]
Thank you for opening an issue with an easy reproduction. I believe you're correct, and will be opening a PR to resolve the issue.

**Comment by edsiper** [comment]
fixed in https://github.com/fluent/fluent-bit/pull/9201
