### ISSUE TITLE
Add static library into fluent bit

### ISSUE THREAD

**Issue by ivlevaleksandr4** [fluent/fluent-bit#9241]
I am developing fluent bit plugin for P7 logger https://baical.net/p7.html
Plugin done for work with binary data and now i have to add Baical Server https://baical.net/index.html into fluent bit build so i can use static libBaical.a in my in_p7 plugin, because Baical Server can decode telemetry files, generated by P7 logger

How can i do this?

**Comment by patrick-stephens** [comment]
Libraries are added via CMake either vendored into `lib` or found via system package managers or cmake look up.

**Comment by ivlevaleksandr4** [comment]
> Libraries are added via CMake either vendored into `lib` or found via system package managers or cmake look up.

but what if this is C++ library e. g. libBaical.a
all fluent bit plugins are C code

**Comment by patrick-stephens** [comment]
Well then you'll need to make sure it can provide the C ABI required but that's normally fine. 

I can't really answer questions about the new dependency you want to use though. That's on your PR to sort, I don't think we typically use C++ libraries

**Comment by ivlevaleksandr4** [comment]
> ABI

Okay, what about libkafka and libjemalloc?
These two are contain cpp source files but still at use
