### ISSUE TITLE
Update msgpack-c library

### ISSUE THREAD

**Issue by Athishpranav2003** [fluent/fluent-bit#9246]
With the new release in msgpack library it would be great if it's updated here too(will be needed to clean some code in parser filter)

**Comment by Athishpranav2003** [comment]
@edsiper I have created the issue

**Comment by edsiper** [comment]
@Athishpranav2003 thanks for opening this issue. 

is there any specific reason to upgrade the library version ?

**Comment by Athishpranav2003** [comment]
While trying to work on feature request in #8893 I thought methods to construct the struct would make the code neat. It was added to the lib recently after I worked with the maintainer of msgpack

**Comment by edsiper** [comment]
Looking at https://github.com/fluent/fluent-bit/issues/8893 it seems to me that the straightforward way to accomplish is just defining an extra config option to do the packing instead of modifying the underlaying msgpack library.

**Comment by Athishpranav2003** [comment]
I have a sol without updating msgpack
But updating leads to clean code. Which one do u want me to proceed with

**Comment by Athishpranav2003** [comment]
So basically some redundant code can be avoided with the updated msgpack lib. @edsiper idk if its worth the effort to update the lib. If not please let me know. I will go ahead and work with existing lib

**Comment by edsiper** [comment]
I am ok with updating msgpack if there is some bug or security problem found, if is not the case I will put it on hold. 

For data manipulation, we are moving forward to use the apis provided by [fluent/cfl](https://github.com/fluent/cfl), specifically [cfl_object](https://github.com/fluent/cfl/blob/master/src/cfl_object.c) to reduce the number of direct serialization calls with msgpack-c. We are providing high-level primitives to simplify the work done in plugins/processors in general.
