### ISSUE TITLE
out_http: Sending data in JSON format is very slow

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-bit#926]
### Describe the bug

Sending data to a HTTP endpoint in JSON format is extremely slow.

Compared with sending data in msgpack format to the same HTTP endpoint,
it's 100-200x slower and much more CPU cnsuming.

### How To Reproduce

Run fluent-bit with the following configuration.

    [SERVICE]
        Flush      1

    [INPUT]
        Name       forward

    [OUTPUT]
        Name       http
        Host       127.0.0.1
        Port       9200
        Format     json

Then, send a bulk of records to the instance.

### Benchmarking

I've benchmarked `out_http` plugin using my dev machine.

 - OS: Debian 9.2 / Linux 4.9.0
 - Mem: 8GB
 - CPU: Intel i5-7200 (2.50GHz)

I launched a fluent-bit (v1.0.0@0c2c51e6) instance with the bare-minimum
configuration (see above).

I input 50,000 records to the instance and measured the time it took
to transfer all the records.

**Result**

| #                               | TIME [sec] | SPEED [events/sec] |
| ------------------------------- | ---------- | ------------------ |
| forward + http (format=msgpack) |      0.61  |            81,967  |
| forward + http (format=json)    |    116.09  |               430  |

So `forard + out_http (json)` is 190 times slower than `forward + out_http (msgpack)`

**Comment by fujimotos** [comment]
So I'm poking around to see what degrades the performance so badly.

Here is a profile report generate by `perf`, applying it to an
actively running fluent-bit instance.

```
# Overhead       Samples  Command        Shared Object      Symbol                            
# ........  ............  .............  .................  ..................................
#
    31.88%           344  fluent-bit     libc-2.24.so       [.] __mpn_divrem
    14.46%           156  fluent-bit     libc-2.24.so       [.] __GI___printf_fp_l
    11.58%           125  fluent-bit     libc-2.24.so       [.] hack_digit
     7.23%            78  fluent-bit     fluent-bit         [.] msgpack2json
     5.75%            62  fluent-bit     fluent-bit         [.] try_to_write
     5.19%            56  fluent-bit     libc-2.24.so       [.] vfprintf
     4.36%            47  fluent-bit     fluent-bit         [.] flb_utils_write_str
     2.41%            26  fluent-bit     libc-2.24.so       [.] __mpn_mul_1
     1.85%            20  fluent-bit     libc-2.24.so       [.] __memmove_avx_unaligned_erms
     1.58%            17  fluent-bit     libc-2.24.so       [.] _IO_str_init_static_internal
     1.30%            14  fluent-bit     libc-2.24.so       [.] _IO_default_xsputn
     1.20%            13  fluent-bit     libc-2.24.so       [.] _IO_old_init
     1.20%            13  fluent-bit     libc-2.24.so       [.] _IO_vsnprintf
     1.11%            12  fluent-bit     libc-2.24.so       [.] __mpn_cmp
     1.02%            11  fluent-bit     libc-2.24.so       [.] __mpn_mul
     0.83%             9  fluent-bit     libc-2.24.so       [.] __strchrnul
```

So three obscure functions (`__mpn_divrem`, `__GI___printf_fp_l`,
and `hack_digit`) dominates the workload, consuming 58% of the
CPU time.

The call graph suggests that these functions are actually part of `snprintf()`,
which is heavily used by `msgpack2json()`.

```
flb_msgpack_raw_to_json_str
flb_msgpack_to_json
msgpack2json
 |          
  --94.35%--msgpack2json
            |          
             --77.50%--__snprintf
                         |          
                          --64.98%--__GI___printf_fp_l
                                    |          
                                    |--45.01%--hack_digit
                                    |          |          
                                    |          |--32.19%--__mpn_divrem
                                    |          
                                     --0.61%--__mpn_rshift
```

So a surprising amount of CPU time is eaten up by `snprintf()` somehow.

**Comment by edsiper** [comment]
thanks for the research, snprintf() is _very_ expensive, we need something like itoa() since it's not available on Linux. It does not make sense to use snprintf() to convert an uint64_t to a string.

**Comment by fujimotos** [comment]
I looked at the code a bit more along the line @bluebike suggests.

It turns out that it's actually the case. The current logic grows `json_buf`
by fixed size (128 bytes), and it leads to a surprising amount of time being
wasted on re-computation.

Here is the summary of my research:

```
| EVENTS | INITIAL [bytes] | ACTUAL [bytes] | RECALC [calls] |
| ------ | --------------- | -------------- | -------------- |
|      1 |             36  |            47  |             1  |
|     10 |            349  |           470  |             1  |
|    100 |           3483  |          4700  |            10  |
|   1000 |          34803  |         47000  |            96  |
|  10000 |         348003  |        470000  |           954  |
```

So: when I input 10000 msgs to fluent-bit, it initially grabs a buffer of 348KB
and tries to grow it to 470KB. This means calling `msgpack2json()` 954 times,
which kills the performance.

I have fixed the code to use an exponential growth factor (also increase the
initial buffer size a bit) in #931. It seems to fix the issue very cleanly:

```
| EVENTS | INITIAL [bytes] | ACTUAL [bytes] | RECALC [calls] |
| ------ | --------------- | -------------- | -------------- |
|      1 |             54  |            47  |             0  |
|     10 |            523  |           470  |             0  |
|    100 |           5255  |          4700  |             0  |
|   1000 |          52205  |         47000  |             0  |
|  10000 |         522005  |        470000  |             0  |
```

Now I see 50000-60000 msg/s on the patched version, compared to 430
msg/s on the latest master branch.

**Comment by fujimotos** [comment]
Also: I can confirm #931 speeds up other plugins as well.

For example, I have tested `out_nats` with NATS v1.3.0, comparing the
patched version with the master HEAD. Here is the result:

```
| EVENTS | MASTER [sec] | PATCHED [sec] |
| ------ | ------------ | ------------- |
|   5000 |       2.665  |           <1  |
|   7500 |       5.723  |           <1  |
|  10000 |      10.957  |           <1  |
|  12500 |      16.678  |           <1  |
```

So the patched version can process 10,000 messages without really much effort,
while it took more than 10 sec in the latest master.

Now, although I have not tried yet, it's very possible that the patch helps
the following plugins:

 1. `out_stackdriver` 
 2. `out_kafka_rest` 
 3. `out_kafka` (with `format=json`)
 4. `out_es`

**Comment by fujimotos** [comment]
OK. Now I think I can close this ticket.
Thanks @edsiper and @bluebike for comments.
