### ISSUE TITLE
The multiline plugin is abnormal.

### ISSUE THREAD

**Issue by hpingping** [fluent/fluent-bit#9262]
## Bug Report

**Describe the bug**
I have the following problem after fluent-bit has been up for a while
The CPU usage keeps increasing until the CPU of the entire node is used up.
The memory usage of fluent-bit keep increasing, causing OOM.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2024/08/22 06:29:13] [ info] [input] resume emitter_for_multiline.1
[2024/08/22 06:29:13] [ info] [input] resume tail.1
[2024/08/22 06:29:13] [ info] [input] resume tail.2
[2024/08/22 06:29:13] [ info] [input] resume tail.0
[2024/08/22 06:29:13] [ info] [input] emitter.3 resume (mem buf overlimit)
```
- Steps to reproduce the problem:

**Expected behavior**
The CPU usage and memory usage do not increase continuously

**Screenshots**

**Your Environment**
Version used: 3.1.6
Configuration:
Environment name and version (e.g. Kubernetes? What version?): Kubernetes v1.25.3
Server type and version:
Operating System and version:
Filters and plugins: tail multiline

**Additional context**
The fluent-bit.conf file in the first container is configured as follows:
```
[INPUT]
    name tail
    path /onip/log/*/var/profile/*/*.alog,/onip/log/*/var/profile/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[INPUT]
    name tail
    path /onip/log/*/var/profile1/*/*.alog,/onip/log/*/var/profile1/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[FILTER]
    Name modify
    Match rating_profile
    Add index_pre rating_profile
    Add formate_type rating_profile
    Add src_sys cbs_179_union_testing

[FILTER]
    name                  multiline
    match                 rating_profile
    multiline.key_content message
    multiline.parser      multiline_rating_profile

[FILTER]
    name                  grep
    match                 rating_profile
    regex                 message ^\d{8} \d{6}\.\d{3}
```
```
[MULTILINE_PARSER]
    name          multiline_rating_profile
    type          regex
    flush_timeout 1000
    rule      "start_state"   "^\d{8} \d{6}\.\d{3}"                    "cont"
    rule      "cont"          "^((?!^\d{8} \d{6}\.\d{3}).)*$" 
```
配置文件中添加了multiline
At first, the CPU usage keeps increasing. After the CPU usage reaches the top, (The CPU limits of the container are set to two cores.) The memory usage keeps increasing, and logs cannot be collected.
![image](https://github.com/user-attachments/assets/cd558df9-b2b2-44ed-83c1-06a3cf3fd922)
![image](https://github.com/user-attachments/assets/89299cf9-dd04-4e17-85f9-2d836576afdd)
![image](https://github.com/user-attachments/assets/d7a2262c-54a7-46d7-9b15-34e353798877)

The configuration of the other container is as follows:
```
[INPUT]
    name tail
    path /onip/log/*/var/profile/*/*.alog,/onip/log/*/var/profile/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[INPUT]
    name tail
    path /onip/log/*/var/profile1/*/*.alog,/onip/log/*/var/profile1/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h

[FILTER]
    Name modify
    Match rating_profile
    Add index_pre rating_profile
    Add formate_type rating_profile
    Add src_sys cbs_179_union_testing

[FILTER]
    name                  grep
    match                 rating_profile
    regex                 message ^\d{8} \d{6}\.\d{3}
```
For the second container, I removed the multi-line parsing configuration. After the container was started, the CPU was stable.
![image](https://github.com/user-attachments/assets/f1c5ccb5-a9d1-40d7-8646-c45e16a9b353)

I don't know if it's a problem with the configuration I wrote, or a problem with the multiline plugin.
However, the first container does collect single-line and multi-line log information in normal cases.
The second container can collect logs continuously.

**Comment by drbugfinder-work** [comment]
Hi @hpingping,
to me this looks like you are reaching the limit (too high log volume). The first graph of the CPU looks like one CPU core (of your 2 CPU core limit) is fully saturated => 50% in your graph (It cannot go higher, unless you enable multi-threading). So it cannot keep up with the processing and finally the memory goes up because the buffers fill up.

**Comment by hpingping** [comment]
I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second. (I don't know why, but I can't upload pictures)
I tried to switch the conf file for log collection later. The configuration is as follows:
```
[PARSER]
    Name multiline
    Format regex
    Regex /(?<message>^\d{8} \d{6}\.\d{3}.*)/
```
```
[INPUT]
    name tail
    path /onip/log/*/var/profile/*/*.alog,/onip/log/*/var/profile/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h
    Multiline On
    Parser_Firstline multiline

[INPUT]
    name tail
    path /onip/log/*/var/profile1/*/*.alog,/onip/log/*/var/profile1/*/*.blog,xxx
    Path_Key path
    Key message
    Tag rating_profile
    Buffer_Chunk_Size 10M
    Buffer_Max_Size 10M
    Mem_Buf_Limit 10M
    Ignore_Older 1h
    Multiline On
    Parser_Firstline multiline

[FILTER]
    Name modify
    Match rating_profile
    Add index_pre cbs-1
    Add formate_type rating_profile
    Add src_sys cbs_179_union_testing
[FILTER]
    name                  grep
    match                 rating_profile
    regex                 message ^\d{8} \d{6}\.\d{3}
```
It's been running for over an hour and the cpu seems to be fine so far. I'll keep an eye on the status going forward.

He seems to have the same problem.
https://github.com/fluent/fluent-bit/issues/8925

**Comment by drbugfinder-work** [comment]
Please create a reproducer configuration (using Dummy input plugin) which shows the issue.

**Comment by yangliuqing5470** [comment]
fluent-bit version >= 2.1.0 have the issuse，since #7133(“ log event: introduction of the log event abstraction layer ") commit.

**Comment by yangliuqing5470** [comment]
multiline plugin becomes slower

**Comment by hpingping** [comment]
Will this be optimized later? At the moment, it looks like there's a problem.

**Comment by sjzaib** [comment]
Same problem happening with me when i tried 3.1.7. Previously we were on 1.9.9 and this issue was not there.
I tested older versions and can confirm that it started from version 2.1.0

[#9337 ] looks same

**Comment by jtackaberry** [comment]
Confirmed here as well.  On first start, Fluent Bit CPU is normal, then gradually degrades until it consumes all available CPU.  Restart, rinse, repeat.  Issue cleared after removing the multiline filter:

```yaml
  - name: multiline
    alias: multiline
    match: syslog.application
    multiline.key_content: message
    multiline.parser: java
```

But based on what we're seeing, it will be a bit of a challenge to distill this down to a specific reproducible case with the dummy plugin.

This week we swapped rsyslog with Fluent Bit for one of our higher volume logging services, but we're seeing this CPU degradation only in one of the 8 regions.  That region happens to be the highest volume of them all, so either this is based on some load threshold or, probably more likely, it's related to some particular customer behavior and the resulting log signatures. 

Next week I will capture a few minutes of logs from that region and continuously feed it into Fluent Bit and see if I can reproduce, and if I'm able, I will start simplifying the configuration and input until I can converge on a bite-sized test case. Hopefully.

**Comment by jtackaberry** [comment]
Actually I just noticed that #8925 has a reproducible test case so this should be pretty easy to adapt to the dummy input.

**Comment by drbugfinder-work** [comment]
Unfortunately, there is no reproducer test in any of the referenced issues (#9262, #8925, #9337).
So I tried to use the example multiline config and build my own reproducer. I tried multiple variations (multiline filter as separate filter; multiline in tail plugin; ...), but I could not see any increase in CPU load over time. Of course the CPU load increases, when the input rate is higher, but I could only see linear growth. 
I cannot find any other common pattern (e.g. all using kubernetes filter, all using tail DB, ...) between #9262, #8925 and #9337, other than using multiline...

Maybe you can try this config and tell if it works for you - and change until the issue occurs for you.
**parsers.conf:**
```
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    rule      "start_state"   "/([A-Za-z]+ \d+ \d+\:\d+\:\d+)(.*)/"  "cont"
    rule      "cont"          "/^\s+at.*/"                     "cont"
```

**fluent-bit.conf**
```
[SERVICE]
    flush                 1
    log_level             info
    parsers_file          /root/test/parsers.conf


[INPUT]
    name                  tail
    path                  test.log
    read_from_head        false
#    multiline.parser      go, multiline-regex-test
    Mem_Buf_Limit         10MB
    Skip_Long_Lines       On
    Refresh_Interval      1

[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      go, multiline-regex-test

[OUTPUT]
    name                  file
    match                 *
    path                  /root/test/out
```

script to create dummy mutliline logs (line by line):
**write_ml.sh**
```
#!/bin/bash

input_file="input.log"
output_file="test.log"
sleep_time=0.0005

while true; do
 while IFS= read -r line; do
   echo "$line" >> "$output_file"
   sleep "$sleep_time"
 done < "$input_file"
done

```




> fluent-bit version >= 2.1.0 have the issuse，since #7133(“ log event: introduction of the log event abstraction layer ") commit.

cc @leonardo-albertovich

**Comment by yangliuqing5470** [comment]
> dummy

How big is the test.log file you are using? Maybe it needs to be at least tens of megabytes.

**Comment by yangliuqing5470** [comment]
> Unfortunately, there is no reproducer test in any of the referenced issues (#9262, #8925, #9337). So I tried to use the example multiline config and build my own reproducer from scratch. I tried multiple variations (multiline filter as separate filter; multiline in tail plugin; ...), but I could not see any increase in CPU load over time. Of course the CPU load increases, when the input rate is higher, but I could only see linear growth. I cannot find any other common pattern (e.g. all using kubernetes filter, all using tail DB, ...) between #9262, #8925 and #9337, other than using multiline...
> 
> Maybe you can try this config and tell if it works for you - and change until the issue occurs for you. **parsers.conf:**
> 
> ```
> [MULTILINE_PARSER]
>     name          multiline-regex-test
>     type          regex
>     flush_timeout 1000
>     rule      "start_state"   "/([A-Za-z]+ \d+ \d+\:\d+\:\d+)(.*)/"  "cont"
>     rule      "cont"          "/^\s+at.*/"                     "cont"
> ```
> 
> **fluent-bit.conf**
> 
> ```
> [SERVICE]
>     flush                 1
>     log_level             info
>     parsers_file          /root/test/parsers.conf
> 
> 
> [INPUT]
>     name                  tail
>     path                  test.log
>     read_from_head        false
> #    multiline.parser      go, multiline-regex-test
>     Mem_Buf_Limit         10MB
>     Skip_Long_Lines       On
>     Refresh_Interval      1
> 
> [FILTER]
>     name                  multiline
>     match                 *
>     multiline.key_content log
>     multiline.parser      go, multiline-regex-test
> 
> [OUTPUT]
>     name                  file
>     match                 *
>     path                  /root/test/out
> ```
> 
> script to create dummy mutliline logs (line by line): **write_ml.sh**
> 
> ```
> #!/bin/bash
> 
> input_file="input.log"
> output_file="test.log"
> sleep_time=0.0005
> 
> while true; do
>  while IFS= read -r line; do
>    echo "$line" >> "$output_file"
>    sleep "$sleep_time"
>  done < "$input_file"
> done
> ```
> 
> > fluent-bit version >= 2.1.0 have the issuse，since #7133(“ log event: introduction of the log event abstraction layer ") commit.
> 
> cc @leonardo-albertovich

How big is the test file you are using? Maybe it needs to be at least tens of megabytes.

**Comment by yangliuqing5470** [comment]
> Unfortunately, there is no reproducer test in any of the referenced issues (#9262, #8925, #9337). So I tried to use the example multiline config and build my own reproducer from scratch. I tried multiple variations (multiline filter as separate filter; multiline in tail plugin; ...), but I could not see any increase in CPU load over time. Of course the CPU load increases, when the input rate is higher, but I could only see linear growth. I cannot find any other common pattern (e.g. all using kubernetes filter, all using tail DB, ...) between #9262, #8925 and #9337, other than using multiline...
> 
> Maybe you can try this config and tell if it works for you - and change until the issue occurs for you. **parsers.conf:**
> 
> ```
> [MULTILINE_PARSER]
>     name          multiline-regex-test
>     type          regex
>     flush_timeout 1000
>     rule      "start_state"   "/([A-Za-z]+ \d+ \d+\:\d+\:\d+)(.*)/"  "cont"
>     rule      "cont"          "/^\s+at.*/"                     "cont"
> ```
> 
> **fluent-bit.conf**
> 
> ```
> [SERVICE]
>     flush                 1
>     log_level             info
>     parsers_file          /root/test/parsers.conf
> 
> 
> [INPUT]
>     name                  tail
>     path                  test.log
>     read_from_head        false
> #    multiline.parser      go, multiline-regex-test
>     Mem_Buf_Limit         10MB
>     Skip_Long_Lines       On
>     Refresh_Interval      1
> 
> [FILTER]
>     name                  multiline
>     match                 *
>     multiline.key_content log
>     multiline.parser      go, multiline-regex-test
> 
> [OUTPUT]
>     name                  file
>     match                 *
>     path                  /root/test/out
> ```
> 
> script to create dummy mutliline logs (line by line): **write_ml.sh**
> 
> ```
> #!/bin/bash
> 
> input_file="input.log"
> output_file="test.log"
> sleep_time=0.0005
> 
> while true; do
>  while IFS= read -r line; do
>    echo "$line" >> "$output_file"
>    sleep "$sleep_time"
>  done < "$input_file"
> done
> ```
> 
> > fluent-bit version >= 2.1.0 have the issuse，since #7133(“ log event: introduction of the log event abstraction layer ") commit.
> 
> cc @leonardo-albertovich

How big is the test.log file you are using? Maybe it needs to be at least tens of megabytes.

**Comment by drbugfinder-work** [comment]
@yangliuqing5470 

> I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.

@hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.

**Comment by yangliuqing5470** [comment]
> @yangliuqing5470
> 
> > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> 
> @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.

I started by preparing a log file of several tens of megabytes, and then started fluentd. At this time, I found that fluentd was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.

**Comment by yangliuqing5470** [comment]
> > @yangliuqing5470
> > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > 
> > 
> > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> 
> I started by preparing a log file of several tens of megabytes, and then started fluentd. At this time, I found that fluentd was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.

The efficiency of processing a sudden increase in logs is low

**Comment by yangliuqing5470** [comment]
> @yangliuqing5470
> 
> > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> 
> @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.

I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.

**Comment by drbugfinder-work** [comment]
> > @yangliuqing5470
> > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > 
> > 
> > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> 
> I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.

Of course the CPU will peak with constant input. The whole pipeline will run at maximum throughput - and it will settle when it is finished. This is intended behaviour. 
You can see this if you use my script to fill the file for a minute or so and change the fluent-bit.conf to 
`read_from_head true`
Leave the script running to constantly fill the input file further.
When you then start Fluent Bit it will have peak CPU load when it constantly reads existng data. Once all written data is processed, it will drop in CPU load and continue to process the newly written data constantly. 

**The issue which https://github.com/fluent/fluent-bit/issues/9262, https://github.com/fluent/fluent-bit/issues/8925 and https://github.com/fluent/fluent-bit/issues/9337 are describing is a constant increase in CPU load, which is totally different behaviour.**

**Comment by yangliuqing5470** [comment]
> > > @yangliuqing5470
> > > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > > 
> > > 
> > > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> > 
> > 
> > I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.
> 
> Of course the CPU will peak with constant input. The whole pipeline will run at maximum throughput - and it will settle when it is finished. This is intended behaviour. You can see this if you use my script to fill the file for a minute or so and change the fluent-bit.conf to `read_from_head true` Leave the script running to constantly fill the input file further. When you then start Fluent Bit it will have peak CPU load when it constantly reads existng data. Once all written data is processed, it will drop in CPU load and continue to process the newly written data constantly.
> 
> **The issue which #9262, #8925 and #9337 are describing is a constant increase in CPU load, which is totally different behaviour.**

Yes, I understand what you mean, but it is also a problem that the sudden increase in the number of logs is slow to process, which may cause log loss. There is no such problem before version 2.1.0

**Comment by yangliuqing5470** [comment]
> > > > @yangliuqing5470
> > > > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > > > 
> > > > 
> > > > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> > > 
> > > 
> > > I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.
> > 
> > 
> > Of course the CPU will peak with constant input. The whole pipeline will run at maximum throughput - and it will settle when it is finished. This is intended behaviour. You can see this if you use my script to fill the file for a minute or so and change the fluent-bit.conf to `read_from_head true` Leave the script running to constantly fill the input file further. When you then start Fluent Bit it will have peak CPU load when it constantly reads existng data. Once all written data is processed, it will drop in CPU load and continue to process the newly written data constantly.
> > **The issue which #9262, #8925 and #9337 are describing is a constant increase in CPU load, which is totally different behaviour.**
> 
> Yes, I understand what you mean, but it is also a problem that the sudden increase in the number of logs is slow to process, which may cause log loss. There is no such problem before version 2.1.0

It takes nearly 2 hours to process a log file of more than 70 MB

**Comment by yangliuqing5470** [comment]
> > > @yangliuqing5470
> > > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > > 
> > > 
> > > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> > 
> > 
> > I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.
> 
> Of course the CPU will peak with constant input. The whole pipeline will run at maximum throughput - and it will settle when it is finished. This is intended behaviour. You can see this if you use my script to fill the file for a minute or so and change the fluent-bit.conf to `read_from_head true` Leave the script running to constantly fill the input file further. When you then start Fluent Bit it will have peak CPU load when it constantly reads existng data. Once all written data is processed, it will drop in CPU load and continue to process the newly written data constantly.
> 
> **The issue which #9262, #8925 and #9337 are describing is a constant increase in CPU load, which is totally different behaviour.**

Yes, I understand what you mean, but it is also a problem that the sudden increase in the number of logs is slow to process, which may cause log loss. There is no such problem before version 2.1.0.

It takes nearly 2 hours to process a log file of more than 70 MB

**Comment by drbugfinder-work** [comment]
> > > > @yangliuqing5470
> > > > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > > > 
> > > > 
> > > > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> > > 
> > > 
> > > I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.
> > 
> > 
> > Of course the CPU will peak with constant input. The whole pipeline will run at maximum throughput - and it will settle when it is finished. This is intended behaviour. You can see this if you use my script to fill the file for a minute or so and change the fluent-bit.conf to `read_from_head true` Leave the script running to constantly fill the input file further. When you then start Fluent Bit it will have peak CPU load when it constantly reads existng data. Once all written data is processed, it will drop in CPU load and continue to process the newly written data constantly.
> > **The issue which #9262, #8925 and #9337 are describing is a constant increase in CPU load, which is totally different behaviour.**
> 
> Yes, I understand what you mean, but it is also a problem that the sudden increase in the number of logs is slow to process, which may cause log loss. There is no such problem before version 2.1.0.
> 
> It takes nearly 2 hours to process a log file of more than 70 MB

With my provided config and Fluent Bit v3.1.7 / v3.1.8 my test.log file of now over 1.9GB is processed within <5 minutes. I cannot confirm your observations.

**Comment by yangliuqing5470** [comment]
> > > > > @yangliuqing5470
> > > > > > I don't think my logs are huge. I checked the kafka monitor and there are only 200+ data being generated per second.
> > > > > 
> > > > > 
> > > > > @hpingping said that the throughput is only about 200 "data" (? logs? lines?) per second for the issue to occur. So the write_ml.sh will sleep accordingly to print 200 lines/sec. I let it run with 1000 lines/sec over last night and there was no increase in CPU load over time.
> > > > 
> > > > 
> > > > I started by preparing a log file of several tens of megabytes, and then started fluent-bit. At this time, I found that fluent-bit was slow to process, and the CPU occupied a full core. The same test did not have this problem before version 2.1.0.
> > > 
> > > 
> > > Of course the CPU will peak with constant input. The whole pipeline will run at maximum throughput - and it will settle when it is finished. This is intended behaviour. You can see this if you use my script to fill the file for a minute or so and change the fluent-bit.conf to `read_from_head true` Leave the script running to constantly fill the input file further. When you then start Fluent Bit it will have peak CPU load when it constantly reads existng data. Once all written data is processed, it will drop in CPU load and continue to process the newly written data constantly.
> > > **The issue which #9262, #8925 and #9337 are describing is a constant increase in CPU load, which is totally different behaviour.**
> > 
> > 
> > Yes, I understand what you mean, but it is also a problem that the sudden increase in the number of logs is slow to process, which may cause log loss. There is no such problem before version 2.1.0.
> > It takes nearly 2 hours to process a log file of more than 70 MB
> 
> With my provided config and Fluent Bit v3.1.7 / v3.1.8 my test.log file of now over 1.9GB is processed within <5 minutes. I cannot confirm your observations.
My test:
![input1](https://github.com/user-attachments/assets/36912ce3-57c1-47cc-8fab-2c74ff0b8c63)
![input2](https://github.com/user-attachments/assets/bbccb726-562c-480b-91c3-bea604d109a2)
![running](https://github.com/user-attachments/assets/6510e3f6-6df7-42f5-9b25-0baf078364db)
![running2](https://github.com/user-attachments/assets/0fe925e9-0936-48c1-bc03-a12c3c0b0d95)
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    log_file     C:\\fluent-bit\\fluent.log
    parsers_file parsers.conf

    plugins_file plugins.conf

    http_server  on
    http_listen  0.0.0.0
    http_port    2020
    storage.metrics off
    grace 30

[INPUT]
    Name tail
    Path D:\\applogs\\app.log.*
    Tag kube.*
    Mem_Buf_Limit 200MB
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size 10MB
    Skip_Long_Lines On
    DB D:\\applogs\\fluent-bit.pos
    Read_from_Head true
    Refresh_Interval 10

[FILTER]
    Name multiline
    Match kube.*
    multiline.key_content log
    multiline.parser multiline_framework

[OUTPUT]
    Name             file
    Match            *
    Path             D:\\fluent-bit-output

**Comment by drbugfinder-work** [comment]
@yangliuqing5470 please don't get me wrong. I also see this behaviour one _**some**_ Fluent Bit instances (even though the log rate is very low ~ 20-200 logs/sec). Look at the number of chunks and running tasks.
![Bildschirmfoto 2024-09-25 um 12 32 20](https://github.com/user-attachments/assets/0ec3d76a-63e0-45fd-867f-fc9e19b35ed1)

I could not find the reason for it, yet.

@leonardo-albertovich Do you have any clue where these many tasks are coming from? There's almost no load on the pipeline at the moment of the screenshot.

**Comment by drbugfinder-work** [comment]
@leonardo-albertovich @edsiper I think I found a CPU hog in the function https://github.com/fluent/fluent-bit/blob/f36c95620224b0a372e4ce481e3dd58b6670251f/src/multiline/flb_ml.c#L1265-L1267

![image](https://github.com/user-attachments/assets/c7036cc1-4cd6-4840-b0c6-29798ab7dd54)

When I skip this section of the code, the multiline filter operates at "lightspeed" again.

Could you please explain to me what the metadata deduplication is doing?

It seems to be _extremely_ CPU-intensive - by several orders of magnitude compared to the rest of the multiline filter code.
https://github.com/fluent/fluent-bit/blob/f36c95620224b0a372e4ce481e3dd58b6670251f/src/multiline/flb_ml.c#L1490-L1494
Skipping the `flb_ml_flush_metadata_buffer` function resulted in throughput increasing from 

**_<0.1MB/Minute 
to 
~0,5GB/Minute_** in my tests

**Comment by drbugfinder-work** [comment]
Used config:

**fluent-bit.conf**
```
[SERVICE]
    flush                 1
    log_level             info
    parsers_file          /root/test/parsers.conf

[INPUT]
    name                  tail
    path                  test.log
    read_from_head        true
    Mem_Buf_Limit         10MB
    Buffer_Chunk_Size     1MB
    Buffer_Max_Size       10MB
    Skip_Long_Lines       On
    Refresh_Interval      1
    Tag                   test

[FILTER]
    name                  multiline
    match                 test*
    multiline.key_content log
    multiline.parser      go, multiline-regex-test

[OUTPUT]
    name                  file
    match                 test
    path                  /root/test/out
```
**parsers.conf**
```
[MULTILINE_PARSER]
    name          multiline-regex-test
    type          regex
    flush_timeout 1000
    rule         "start_state"   "/(Dec \d+ \d+\:\d+\:\d+)(.*)/"  "cont"
    rule         "cont"          "/^\s+at.*/"                     "cont"
```

**Test data generator:** 
```
#!/bin/bash

output_file="test.log"
temp_file="temp.log"
log_content="Dec 14 06:41:08 Exception in thread \"main\" java.lang.RuntimeException: Something has gone wrong, aborting!
    at com.myproject.module.MyProject.badMethod(MyProject.java:22)
    at com.myproject.module.MyProject.oneMoreMethod(MyProject.java:18)
    at com.myproject.module.MyProject.anotherMethod(MyProject.java:14)
    at com.myproject.module.MyProject.someMethod(MyProject.java:10)
    at com.myproject.module.MyProject.main(MyProject.java:6)"

target_size=$((1024 * 1024 * 1024))

echo "$log_content" > "$output_file"

# Duplicate the file by copying it to itself until it reaches the target size
current_size=$(stat -c%s "$output_file")

echo "$log_content" > "$output_file"
while [[ $current_size -lt $target_size ]]; do
        cp "$output_file" "$temp_file"
        cat "$temp_file" >> "$output_file"
        current_size=$(stat -c%s "$output_file")
done
truncate -s $target_size "$output_file"
rm "$temp_file"
```

**Comment by yangliuqing5470** [comment]
> It seems to be _extremely_ CPU-intensive - by several orders of magnitude compared to the rest of the multiline filter code

great job!
