### ISSUE TITLE
Use of uninitalised memory error in cmt_decode_prometheus_lex()

### ISSUE THREAD

**Issue by skorpion98** [fluent/fluent-bit#9267]
## Bug Report

**Describe the bug**
 Conditional jump or move depends on uninitialised value(s) in function `cmt_decode_prometheus_lex()`

**To Reproduce**
The [attached archive](https://github.com/user-attachments/files/16709901/fluentbit_undefined.zip) contains:
- the executable on which we performed our tests 
- the input file to exercise the bug
- the output of Valgrind confirming our finding

At least for this testcase, a memory safety tool is required to expose the bug. To reproduce, run the given binary with the testcase file inside valgrind with a command like `valgrind ./flb-it-fuzz-cmetrics_decode_fuzz_OSSFUZZ testcase`

**Your Environment**

* Version used: commit hash 839c963
* Environment name and version:  standard OSS-Fuzz Docker image for fluent-bit
* Operating System and version: Ubuntu 20.04

**Additional context**
The binary in the archive is a compiled version of a fuzzing harness you made available for OSS-Fuzz (i.e. flb-it-fuzz-cmetrics_decode_fuzz_OSSFUZZ). It is compiled with the default OSS-Fuzz configuration for this project, using the AFL++ engine.

We cannot provide more info on which variable is causing this error as the binary seems to be compiled, by default, without debugging symbols and our attempts to add them were unsuccessful. We are confident that developers with knowledge on the codebase will be able to find the root of the issue with little effort, but we remain available to assist you in case of need.

**Comment by edsiper** [comment]
@skorpion98 thanks for reporting this issue. 

I have validated the problem in CMetric library and ported the test case there:

- https://github.com/fluent/cmetrics/pull/217

@leonardo-albertovich I pushed a branch as a PR with the test case in CMetrics, please take a look at it,.

**Comment by edsiper** [comment]
fixed by CMetrics v0.9.5
