### ISSUE TITLE
Support mTLS for forward protocol input

### ISSUE THREAD

**Issue by jasonkeene** [fluent/fluent-bit#927]
**Is your feature request related to a problem? Please describe.**

When sending data into fluent-bit, we need to have this encrypted and authenticated.

**Describe the solution you'd like**

Support mutual auth TLS.

**Describe alternatives you've considered**

We ended up using ghostunnel as a TLS proxy. That works fine.
Alternatively, we're considering using Istio/envoy to proxy over TLS.
Besides mTLS, we didn't really consider alternatives because, well, mTLS is pretty solid and well adopted for this purpose.

**Additional context**

This is already supported in fluentd: https://docs.fluentd.org/v1.0/articles/in_forward#how-to-enable-tls-mutual-authentication

**Comment by abh** [comment]
The feature request is still relevant, best I can tell.

**Comment by danifv** [comment]
Hello,
are there any upgrades on this feature?

**Comment by schen2315** [comment]
Hi, bumping
