### ISSUE TITLE
in_forward: input forward plugin fails to append logs but continues to send an acknowledgment message back

### ISSUE THREAD

**Issue by mirko-lazarevic** [fluent/fluent-bit#9288]
## Bug Report

**Describe the bug**
I’m encountering an issue with Fluent Bit when using the `[INPUT] Forward` plugin configured to run in memory-only mode. The Fluent Bit engine discards packets when the memory buffer limit is exceeded (`[ warn] [input] forward.0 paused (mem buf overlimit`). Despite this, acknowledgments are still sent (chunk id is not nil), signalling successful log reception back to client. This implies that the `[INPUT] Forward` plugin fails to append logs but continues to send an acknowledgment message back, which may lead to data loss without the sender being aware.

**To Reproduce**
- Steps to reproduce the problem:

1. Configure the `[INPUT] forward plugin` in memory-only mode with a specified buffer limit.
```
[INPUT]
    Name                forward
    Listen              127.0.0.1
    Port                24224
    Buffer_Chunk_Size   512KB
    Buffer_Max_Size     2MB
    Mem_Buf_Limit       10MB
```
2. Send logs (with chunk_id) to Fluent Bit until the memory buffer limit is exceeded.
3. Notice that Fluent Bit logs a warning about memory buffer overlimit and check for acknowledgments sent back to the sender.
```
[ warn] [input] forward.0 paused (mem buf overlimit)
```

**Expected behavior**
I expected Fluent Bit not to send acknowledgments for records that it fails to append due to memory buffer limit. The acknowledgment should only be sent if the record is successfully stored and processed. 

**Your Environment**

* Version used: 3.1.6
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: macOS Sonoma
* Filters and plugins: input forward plugin

**Additional context**
- [Here](https://github.com/fluent/fluent-bit/blob/4427d42554c565171a775f18df397d87d894c9fb/plugins/in_forward/fw_prot.c#L1110) is the section of code where the result of `flb_input_log_append` is disregarded.

**Comment by drbugfinder-work** [comment]
It should drop all connections... 
https://github.com/fluent/fluent-bit/blob/a6feacd6e92e08c0e5290f255864e70b12301fa8/plugins/in_forward/fw.c#L360-L370

Looks like this is not enough / the connection gets re-established.

**Comment by mirko-lazarevic** [comment]
Hey @drbugfinder-work, I think I made a mistake. I encountered this issue with version 3.0.6, not 3.1.6 as I originally stated. Additionally, I noticed that although all connections are closed, this has introduced another issue, which I've reported here: https://github.com/fluent/fluent-bit/issues/9443.
