### ISSUE TITLE
Conditional filtering referencing nested fields

### ISSUE THREAD

**Issue by baldomeromero** [fluent/fluent-bit#932]
## Bug Report

**Describe the bug**
I want to filter_modify a record depending on the value o a nested field, in our case, it is "kubernetes.labels.app" but it is not being read as a nested field but as a field with dots in its name.

**Your Environment**
* Version used: 0.14.8 oficial docker image over Kubernetes
* Configuration:

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On

    [FILTER]
        Name                modify
        Match               kube.*
        Rename              log message
        Condition           Key_Exists kubernetes.labels.app

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
....

* Environment name and version (e.g. Kubernetes? What version?):
Kubernetes 
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Comment by gitfool** [comment]
Similarly, I need to copy and/or rename nested fields; for example I currently have to do the following to copy and rename some nested kubernetes fields:
```
[FILTER]
    name                  modify
    match                 *
    copy                  kubernetes kubernetes_copy

[FILTER]
    name                  nest
    match                 *
    operation             lift
    nested_under          kubernetes_copy
    prefix_with           kubernetes_copy_

[FILTER]
    name                  modify
    match                 *
    rename                kubernetes_copy_container_name container_name
    rename                kubernetes_copy_docker_id container_id
    remove_wildcard       kubernetes_copy
```
which ideally could be expressed more succinctly, and execute more efficiently, using dotted notation:
```
[FILTER]
    name                  modify
    match                 *
    copy                  kubernetes.container_name container_name
    copy                  kubernetes.docker_id container_id
```
@edsiper what do you reckon?

**Comment by edsiper** [comment]
For custom/complex filtering like this, I suggest you use [Filter Lua](https://docs.fluentbit.io/manual/filter/lua) and create a script for the purpose

**Comment by gitfool** [comment]
@edsiper I'm not familiar with Lua script, or how Fluent Bit uses it, so I have some dumb questions:
- How much of a performance impact does using Lua script have compared to built-in operators?
- Are  nested fields accessible as nested tables in Lua?
- The examples always use `new_record` but can I just modify in-place the passed in `record` table? e.g.
```
  function lift_partial_info(tag, timestamp, record)
     record["container_id"] = record["kubernetes"]["docker_id"]
     record["container_name"] = record["kubernetes"]["container_name"]
     return 1, timestamp, record
  end
```

**Comment by chinniehendrix** [comment]
Hi @gitfool, any luck with that?

**Comment by gitfool** [comment]
@chinniehendrix I've been successfully using the following (extracted from the k8s config map):
```yml
  filters.conf: |
    [FILTER]
        name                  kubernetes
        match                 kube.*
        kube_url              https://kubernetes.default.svc.cluster.local:443
        merge_log             true
        keep_log              false
        k8s-logging.parser    true
        k8s-logging.exclude   true

    [FILTER]
        name                  lua
        match                 *
        script                filters.lua
        call                  transform

  filters.lua: |
    function transform(tag, timestamp, record)
        if record["kubernetes"] then
            record["Service"] = record["kubernetes"]["container_name"] -- alias across ec2, ecs & k8s
        end

        if record["RenderedMessage"] then
            record["Message"], record["RenderedMessage"] = record["RenderedMessage"], nil
        else
            record["Message"], record["log"] = record["log"], nil
        end

        return 1, timestamp, record
    end
```

**Comment by chinniehendrix** [comment]
@gitfool Cool, it worked! Thanks a lot!
