### ISSUE TITLE
Directly include environment variables in `s3_key_format` in s3 output

### ISSUE THREAD

**Issue by skeggse** [fluent/fluent-bit#9365]
**Is your feature request related to a problem? Please describe.**

I want to include values that aren't in the individual log records in the S3 key. For example, I'd like to prefix the S3 key with the environment and EKS cluster that the `fluentbit` agent is running in. I could incorporate that value into every single entry in the log file, but if it's always going to be the same that'll be a bunch of extra data to ship off in the final object that simply doesn't need to be there. Compression will probably mitigate that a good bit, but it'll still be there to process once decompressed.

**Describe the solution you'd like**

I've got the values available to `fluentbit` as environment variables, so ideally I'd be able to specify an `s3_key_format` option that looks like `/$ENV:ENVIRONMENT/$ENV:EKS_CLUSTER/$TAG/%Y/%m/%d/%H/$UUID.log.gz`

**Describe alternatives you've considered**

For now I'm including the extra fields in the log files themselves.

**Additional context**

In addition to reducing the log data to process, it also makes it easier to find the relevant file more quickly. If I know I want to look for a particular cluster in a particular environment, being able to navigate S3 in that way would be really nice :)

**Comment by patrick-stephens** [comment]
Does it work with the actual variable syntax, i.e. `${VAR}`?
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/variables

**Comment by skeggse** [comment]
I spent too much time looking at the documentation page for the S3 plugin, and not enough time looking at the the general fluent-bit docs! That does indeed work, thank you :)
