### ISSUE TITLE
zstd compression to both the Kafka input and Kafka output processors

### ISSUE THREAD

**Issue by hafkaM** [fluent/fluent-bit#9367]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Would it be possible to add support for zstd compression to both the Kafka input and Kafka output processors? For high-performance tasks, this compression is more efficient and is currently only available in Fluentd. However, Fluentd is slower compared to Fluent Bit.

**Comment by patrick-stephens** [comment]
Related to #2483 which seems to enable it for output.
Also: 
#5957 #4564 #7715

**Comment by leonardo-albertovich** [comment]
So, do I understand correctly that even though a PR aimed to address this was merged back in 2020 this is still not working?
