### ISSUE TITLE
Blocked when unable to connect to kubernetes API

### ISSUE THREAD

**Issue by jasonkeene** [fluent/fluent-bit#937]
## Bug Report

**Describe the bug**

We experimented with kube-apiserver downtime and discovered that fluent-bit will block on `connect` which prevents all other work from making forward progress. Eventually, these connects will timeout after a few minutes but will get blocked again shortly afterwards on new messages.

This affects logs for pods that already have metadata and entirely unrelated messages that do not pass through `filter_kubernetes`.

**To Reproduce**

Here is the scenario we have to demonstrate this:

1. Setup a pod that logs once a second. Observe these messages being written to an output (`out_file` is fine).
1. Add an iptable rule to block fluent-bit from sending outbound packets to the kube-apiserver:

    ```
    iptables -A OUTPUT -d <kube_apiserver_ip> -p tcp -j DROP
    ```

    Everything should continue to function correctly since fluent-bit does not need to lookup metadata for the existing pods.
1. Add a new pod that logs once a second.
1. Observe that all logs stop flowing to their destinations.
1. Additionally, you can trace fluent-bit with the program below. This will show fluent-bit blocked on connect. It will also print the stack when connect fails.

We were able to improve the situation by lowering the `tcp_syn_retries` value system wide:

```
echo 1 > /proc/sys/net/ipv4/tcp_syn_retries
```

This helps but messages are still delayed when `connect` is blocked.

When the new logging pod is removed messages start flowing correctly once all the new logging pods' messages are processed.

When the iptables rule is removed messages start flowing correctly again.

**Expected behavior**

`kube-apiserver` downtime should not affect messages other than those for new pods where metadata is not available locally.

**Possible solutions**

1. Just recommend that users lower the `connect` timeout via `/proc/sys/net/ipv4/tcp_syn_retries` to mitigate the issue.
1. Re-enable async I/O and timeout on `select()`. Async I/O is disabled [here][async-disabled]. If this was enabled you could then block with `select()` and tightly control the timeout.
1. Once api downtime is detected, only re-check availability periodically. Perhaps some sort of exponential backoff with a limit? This option would be ideal as it would not affect other messages whereas the timeouts will still affect delivery of other messages.

[async-disabled]: https://github.com/fluent/fluent-bit/blob/7000e3712c6b8b04b345c2615e69e293a43e22d4/plugins/filter_kubernetes/kube_meta.c#L708-L709

**Additional context**

Here is a copy of the stack when we are blocked on `connect`:

```
        flb_net_tcp_fd_connect+246
        flb_io_net_connect+342
        create_conn+152
        flb_upstream_conn_get+63
        0x7fffffffe000
        get_and_merge_meta+78
        flb_kube_meta_get+284
        cb_kube_filter+303
        flb_filter_do+202
        flb_input_dbuf_write_end+354
        flb_input_dyntag_append_raw+120
        process_content+1134
        flb_tail_file_chunk+738
        in_tail_collect_static+101
        flb_input_collector_fd+1113
        flb_engine_start+1561
        main+1810
        __libc_start_main+240
        0xb43e258d4c544155
```

Here is the `bpftrace` program used to dump the stack:

```
#!/usr/bin/env bpftrace

#include <fluent-bit/flb_upstream.h>

uprobe:fluent-bit/bin/fluent-bit:get_local_pod_info {
    printf("+ %d get_local_pod_info: %s\n", nsecs / 1000000, str(arg2));
}

uretprobe:fluent-bit/bin/fluent-bit:get_local_pod_info {
    printf("- %d get_local_pod_info: %d\n", nsecs / 1000000, retval);
}

uprobe:fluent-bit/bin/fluent-bit:get_api_server_info {
    printf("+ %d get_api_server_info: %s\n", nsecs / 1000000, str(arg2));
}

uretprobe:fluent-bit/bin/fluent-bit:get_api_server_info {
    printf("- %d get_api_server_info: %d\n", nsecs / 1000000, retval);
}

uprobe:fluent-bit/bin/fluent-bit:flb_upstream_conn_get {
    printf("+ %d flb_upstream_conn_get: %s %d\n", nsecs / 1000000, str(((flb_upstream *)arg0)->tcp_host), ((flb_upstream *)arg0)->tcp_port);
}

uretprobe:fluent-bit/bin/fluent-bit:flb_upstream_conn_get {
    printf("- %d flb_upstream_conn_get\n", nsecs / 1000000);
}

uprobe:fluent-bit/bin/fluent-bit:flb_io_net_connect {
    printf("+ flb_io_net_connect\n");
}

uretprobe:fluent-bit/bin/fluent-bit:flb_io_net_connect {
    printf("- flb_io_net_connect\n");
}

uprobe:fluent-bit/bin/fluent-bit:flb_net_tcp_fd_connect {
    printf("+ flb_net_tcp_fd_connect\n");
}

uretprobe:fluent-bit/bin/fluent-bit:flb_net_tcp_fd_connect {
    printf("- flb_net_tcp_fd_connect\n");
}

uprobe:lib/x86_64-linux-gnu/libc-2.23.so:connect {
    printf("+ connect\n");
}

uretprobe:lib/x86_64-linux-gnu/libc-2.23.so:connect {
    // only dump stack when connect fails
    if (retval != 0) {
        printf("%s\n", ustack);
    };
    printf("- connect: %d\n", retval);
}

uprobe:lib/x86_64-linux-gnu/libpthread-2.23.so:connect {
    printf("+ connect\n");
}

uretprobe:lib/x86_64-linux-gnu/libpthread-2.23.so:connect {
    // only dump stack when connect fails
    if (retval != 0) {
        printf("%s\n", ustack);
    };
    printf("- connect: %d\n", retval);
}
```

**Comment by edsiper** [comment]
no issues reported around this in the latest years.
