### ISSUE TITLE
Splunk/Custom HTTP Retry Codes

### ISSUE THREAD

**Issue by meehanman** [fluent/fluent-bit#9371]
When Splunk is having a bad time, you'll get a `408 - Your request timed out. Try again.` but both the [out_http](https://github.com/fluent/fluent-bit/blob/974e474676c5dcf4046637eb8d790ba8219febf5/plugins/out_http/http.c) and [out_splunk](https://github.com/fluent/fluent-bit/blob/69bf966c5f073d116a51f2b4d00590ae5367d13b/plugins/out_splunk/splunk.c) plugins will never retry :face_palm: 

out_http
```c
if (c->resp.status >= 400 && c->resp.status < 500 && c->resp.status != 429) {
    flb_plg_warn(ctx->ins, "could not flush records to %s:%i (http_do=%i), "
                    "chunk will not be retried",
                    ctx->host, ctx->port, ret);
    out_ret = FLB_ERROR;
}
```

out_splunk
```c
/*
    * Requests that get 4xx responses from the Splunk HTTP Event
    * Collector will 'always' fail, so there is no point in retrying
    * them:
    *
    * https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/TroubleshootHTTPEventCollector#Possible_error_codes
    */
ret = (c->resp.status < 400 || c->resp.status >= 500) ?
    FLB_RETRY : FLB_ERROR;
```

**Describe the solution you'd like**

The **Splunk out** plugin requires more conformity to the [Troubleshooting Documentation](https://docs.splunk.com/Documentation/SecureGateway/3.5.15/Admin/TroubleshootGateway) that they provide that indicates that `408 and 429` HTTP results should constitute a retry and not return `FLB_ERROR`. 

The **HTTP out** Plugin would be great to add additional options to [Configuring Retries](https://docs.fluentbit.io/manual/administration/scheduling-and-retries) that will allow more configuration to the retry logic such as the addition of additional HTTP codes we would want to retry with eg. if you wanted to retry with HTTP code `666` you could. In theory, we'd just want to add `408 and 429` to the list.

**Describe alternatives you've considered**

We only really have the option of setting up some intermediary proxy server that would proxy the requests correctly to give it a retryable HTTP response code if there is a 4xx error.

**Comment by agup006** [comment]
@cosmo0920 is this something we could add for next sprint?

**Comment by cosmo0920** [comment]
Hi, I sent PRs to extend retrying handlings for HTTP status codes for 408 and 429.

**Comment by cosmo0920** [comment]
This could be marked as done. Due to two PRs are merged into master.
