### ISSUE TITLE
how to match more than one tags ?

### ISSUE THREAD

**Issue by CoffeeHi** [fluent/fluent-bit#9373]
Hi guys, I want to filter two tags in one section, one is `kube.*` the other is `tap-test`, how to define that ?
Seems define like below does not take effect.
```
[FILTER]
   Name            nest
   Match           kube.*
   Match           tap-test
   Operation       nest
   Wildcard        payload.*
   Nest_under      payload
   Remove_prefix   payload.
```

**Comment by cw-Guo** [comment]
see Match_regex in https://docs.fluentbit.io/manual/concepts/data-pipeline/router#routing-with-regex

**Comment by CoffeeHi** [comment]
thanks
