### ISSUE TITLE
[SIGSEV] Http_proxy not working with out_http

### ISSUE THREAD

**Issue by kushwiz** [fluent/fluent-bit#938]
Starting program: /root/fluent-bit/build/bin/fluent-bit -c conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Fluent-Bit v0.14.8
Copyright (C) Treasure Data

[New Thread 0x7ffff700a700 (LWP 408)]
[2018/12/04 22:29:12] [ info] [engine] started (pid=404)
[2018/12/04 22:29:12] [ info] [filter_kube] https=1 host=kubernetes.default.svc.cluster.local port=443
[2018/12/04 22:29:12] [ info] [filter_kube] local POD info OK
[2018/12/04 22:29:12] [ info] [filter_kube] testing connectivity with API server...
[2018/12/04 22:29:12] [ info] [filter_kube] API server connectivity OK

Thread 1 "fluent-bit" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff70684d3 in _IO_vfprintf_internal (s=s@entry=0x555555e34390, 
    format=format@entry=0x5555557d42d8 "%s http://%s:%i/%s HTTP/1.%i\r\nHost: %s:%i\r\nProxy-Connection: KeepAlive\r\nContent-Length: %i\r\n", ap=ap@entry=0x555555e34500)
    at vfprintf.c:1643
#2  0x00007ffff7093910 in _IO_vsnprintf (string=0x55555612cb20 "POST http://", maxlen=<optimized out>, 
    format=0x5555557d42d8 "%s http://%s:%i/%s HTTP/1.%i\r\nHost: %s:%i\r\nProxy-Connection: KeepAlive\r\nContent-Length: %i\r\n", args=args@entry=0x555555e34500) at vsnprintf.c:114
#3  0x00007ffff706ffdf in __GI___snprintf (s=<optimized out>, maxlen=<optimized out>, format=<optimized out>) at snprintf.c:33
#4  0x00005555556087c8 in flb_http_client (u_conn=0x555555e1aa80, method=1, uri=0x555555d6e100 "/logs", 
    body=0x55555601e650 "[{\"date\":1543961768.999254, \"log\”:\”[redacted]\”, \"st"..., body_len=53970, host=0x555555ab53f0 “[redacted_host_name]”, port=80, 
    proxy=0x555555ab5aa0 "http://[redacted_proxy_host_colon_port]”, flags=0) at /root/fluent-bit/src/flb_http_client.c:485
#5  0x00005555555d9757 in cb_http_flush (data=0x555555e3e5f0, bytes=46842, 
    tag=0x555555e1ab80 “[redacted_tag]”, tag_len=163, i_ins=0x555555ab5660, out_context=0x555555e18700, config=0x555555ab0260) at /root/fluent-bit/plugins/out_http/http.c:232
#6  0x000055555559c628 in output_pre_cb_flush () at /root/fluent-bit/include/fluent-bit/flb_output.h:311
#7  0x000055555567e6c7 in co_init () at /root/fluent-bit/lib/flb_libco/amd64.c:117
#8  0x20726f727245225c in ?? ()
#9  0x0000000000006211 in ?? ()
#10 0x0000555555e3a6b8 in ?? ()
#11 0x0000555555e3a6e0 in ?? ()
#12 0x000055555567d6c0 in ?? ()
#13 0x0000555555e347f0 in ?? ()
#14 0x6136356400000005 in ?? ()
#15 0x41d701bf00000025 in ?? ()
#16 0x0000555555e50fb1 in ?? ()
#17 0x6136356400000005 in ?? ()
#18 0x41d701bf0000000e in ?? ()

**Comment by edsiper** [comment]
how are you specifying the Proxy server ?, please share your configuration.

**Comment by kushwiz** [comment]
[OUTPUT]
     name http
     Host mywebsite.com
     URI /logs
     Match *
     Port 443
     #tls On ---> I want to do this via proxy, but disabled for now
     #tls.verify On ---> I want to do this via proxy, but disabled for now
     #tls.key_file /fluent-bit/keys/key.pem . ---> I want to do this via proxy, but disabled for now
     #tls.crt_file /fluent-bit/ssl/cert.pem ---> I want to do this via proxy, but disabled for now
     Time_as_Integer On
     Format json
     json_date_key date
     Proxy http://10.20.30.40:3128
