### ISSUE TITLE
IPv6 support issue in flb_hs_create

### ISSUE THREAD

**Issue by ryanlyy** [fluent/fluent-bit#9423]
In below code, tmp length is 32. but if ipv6 address is like: 1234:5678:1234:5678:1234:5678:1234:5678. and if port is 33333. then the total length of listen address is: 32 + 7 + 5 = 44. But the buff tmp is only 32 bytes. so there will be memory issue.

/* Create ROOT endpoints */
struct flb_hs *flb_hs_create(const char *listen, const char *tcp_port,
                             struct flb_config *config)
{
    int vid;
    char tmp[32];

    /* Compose listen address */
    snprintf(tmp, sizeof(tmp) -1, "%s:%s", listen, tcp_port);

**Comment by niedbalski** [comment]
I confirm this issue. To my understanding v6 addresses can be up to 39 characters long (1234:5678:1234:5678:1234:5678:1234:5678 is a valid example), and ports can be up to 5 characters long (65535).  Also, we need to account for the colon (:) between the address and port. Thus, the maximum length would be: 39 (IPv6 address) + 1 (colon) + 5 (port) = 45.

For context should refer to this [RFC 4291](https://datatracker.ietf.org/doc/html/rfc4291) -- My understanding is that this affects http server (https://github.com/fluent/fluent-bit/blob/dd53a3997e5e1de7f2609399bd65a3991b58a466/src/flb_engine.c#L873)
