### ISSUE TITLE
Systemd input plugin no longer recognizes buffer_max_size in fluentbit v3.0

### ISSUE THREAD

**Issue by shuaich** [fluent/fluent-bit#9464]
## Bug Report

**Describe the bug**
After upgrading fluentbit from 1.8.12 to 3.1.4, fluentbit fails to initialize systemd plugin with following configuration

```
[INPUT]
        Name         systemd
        Alias           xxx
        Tag             xxx
        Systemd_Filter  _SYSTEMD_UNIT=xxx
        Path            /var/log/xxx
        DB              /var/lib/xxx.db
        Buffer_Max_Size 1MB
        Mem_Buf_Limit   1MB
```

**Investigation**
This PR introduced configmap to systemd plugin: https://github.com/fluent/fluent-bit/commit/2f28ee57668db28e9338b468dc80bda5dda508be#diff-286fb1d6dda90a3a6f8b0907800d35b8848c725b7d0634777120e79a5e375985R479 to validate configuration paramters. I think this explains the error log.

**Ask**
1. Is Buffer_Max_Size ever used by systemd plugin?
   This will confirm if discarding Buffer_Max_Size is a breaking change.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2024/09/18 23:09:34] [error] [config] systemd: unknown configuration property 'buffer_max_size'. The following properties are allowed: path, max_fields, max_entries, systemd_filter_type, systemd_filter, read_from_tail, lowercase, strip_underscores, db.sync, and db.
```
- Steps to reproduce the problem:

Add Buffer_Max_Size configuration parameter in systemd in fluentbit v3.1.4.

**Expected behavior**

Fluentbit initializes systemd plugins.

**Screenshots**

**Your Environment**

* Version used: fluentbit v3.1.4
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): K8s 1.30
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
I remember seeing something similar in Slack and I'm pretty certain it has never had that option available - it's just that older versions ignored invalid config whereas new versions explicitly fail on it (which is good IMHO).

I cannot see it in the docs for 1.8 anyway: https://docs.fluentbit.io/manual/1.8/pipeline/inputs/systemd

**Comment by patrick-stephens** [comment]
Yeah it was discussed here then brought up in the community meeting: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1726701528570929

I'm going to close as I do not think this is an issue, just a change in that invalid config is no longer ignored (which is good as what you think is configured is not).

**Comment by shuaich** [comment]
Thank you @patrick-stephens for confirming this.
