### ISSUE TITLE
79dc185b0cf3d393a10143e9feeb82a43fb646d1 breaks tests

### ISSUE THREAD

**Issue by donbowman** [fluent/fluent-bit#948]
## Bug Report

**Describe the bug**

As of chunkio 79dc185b0cf3d393a10143e9feeb82a43fb646d1, if one runs:

```
cmake -DFLB_BACKTRACE=Off -DFLB_SHARED_LIB=Off -DFLB_DEBUG=On -DFLB_ALL=On -DFLB_EXAMPLES=Off -DFLB_TESTS_INTERNAL=On -DFLB_TESTS_RUNTIME=On -DFLB_WITHOUT_flb-rt-out_elasticsearch=1 -DFLB_WITHOUT_flb-rt-out_td=1 -DFLB_WITHOUT_flb-rt-out_forward=1 -DFLB_WITHOUT_flb-rt-in_disk=1 -DFLB_WITHOUT_flb-rt-in_proc=1 ../
make -j8
bin/flb-rt-in_cpu
```
we can see it fails. it passes w/ the previous commit.

if we run `ctest --output-on-failure -j8` we see that most(?all?) tests fail.

**Comment by edsiper** [comment]
Fixed normal matching (wildcard).

still need to fix one pending match_regex.

**Comment by edsiper** [comment]
It's fixed now

**Comment by edsiper** [comment]
(there is one crash on exit, different issue)

**Comment by donbowman** [comment]
ok, this crash in retry test comes from a486bd6f6b74e9f54ac3ba61ab0832a1ebecfc2d . I might take a look for it.

thanks git bisect!
