### ISSUE TITLE
High CPU when flushing?

### ISSUE THREAD

**Issue by dmamalis** [fluent/fluent-bit#953]
## Bug Report

**Describe the bug**
Fluent-bit causes high CPU usage at flashing period 

**To Reproduce**
- Steps to reproduce the problem: 
 Compile for ARM, start the service and watch metrics on remote influxDB server

**Expected behavior**

Lower CPU usage when flashing

**Screenshots**

The following screenshot is a snapshot of the data provided from fluent-bit to a Grafana server. From 8 to 8.28 fluent-bit flashes every one minute. The strange pattern between 8:20-8:21 is irrelevant to fluent-bit. However 8:29-8:33 is flushing every 5 seconds.
![screenshot_20181210_083047](https://user-images.githubusercontent.com/5211553/49715779-20a8f500-fc5a-11e8-8889-161c9c6b3958.png)

**Your Environment**

* Version used: 0.14
* Configuration: 
```
[SERVICE]
   Flush    60
   #Log_Level debug

[INPUT]
   #===================================================
   # CPU input plugin
   #===================================================
   Name cpu
   Tag cpu_metrics

[INPUT]
   #===================================================
   # Memory input plugin
   #===================================================
   Name mem
   Tag  mem_metrics

[INPUT]
   #===================================================
   # Network Traffic input plugin
   #===================================================
   Name netif
   Tag netif_metrics
   Interval_Sec 5
   Interval_NSec 0
   Interface eth0

[INPUT]
   #===================================================
   # Process input plugin
   #===================================================
   Name proc
   Proc_Name monitor
   Tag monitor_metrics
   Interval_Sec 5
   Interval_NSec 0
   Fd true
   Mem true

[INPUT]
   #===================================================
   # Process input plugin
   #===================================================
   Name proc
   Proc_Name fluent-bit
   Tag fluent-bit_metrics
   Interval_Sec 5
   Interval_NSec 0
   Fd true
   Mem true

[INPUT]
   #===================================================
   # Process input plugin
   #===================================================
   Name proc
   Proc_Name open
   Tag open_metrics
   Interval_Sec 5
   Interval_NSec 0
   Fd true
   Mem true

[INPUT]
   #===================================================
   # Lora logs input plugin
   #===================================================
   Name tail
   Tag ymi
   Path /var/log/ymi.log
   DB /home/root/fluent-bit.db
   Buffer_Chunk_Size 128k
   Buffer_Max_Size 256k


[OUTPUT]
   Name influxdb
   Match *_metrics
   Host 192.168.2.2
   Port 4545
   HTTP_User whatever
   HTTP_Passwd whatever
   Database kudzu_ath_ymi
   #Sequence_Tag _seq
   tls On
   tls.verify Off
   tls.debug 1
   tls.crt_file /home/root/whatever.crt
   tls.key_file /home/root/whatever.key

[OUTPUT]
   Name es
   Match  ymi
   Host 192.168.2.2
   Port 4546
   Logstash_Format On
   Include_Tag_Key On
   Tag_key ga (edited)
```

* Operating System and version: 
```Linux 3.12.70 #1 PREEMPT Wed Aug 29 12:07:37 CDT 2018 armv5tejl GNU/Linux```

* Filters and plugins: 
No Filters
cpu, mem, netif, proc, tail, influxdb, es

**Additional context**

During testing we tried different configurations. The CPU peak would slightly vary in height but overall the problem seems to persist no matter what the configuration is, getting worse the more Processes are being monitored.

**Comment by rolandjitsu** [comment]
I'm having a similar issue on an ARM device as well. It's constantly using one of the cores at 100%, regardless of flush interval.

**Comment by agup006** [comment]
Doing a bit of cleanup, and it looks like this may from an older version - would we be able to try out the latest 1.7.0 version to see if it persists? Some notable performance fixes that we made were enabling connection persistence, optimizing I/O usage, TLS optimizations. I'm wondering if we may have been running into some connection re-use issues here.

I'm going to close for now, feel free to re-open
