### ISSUE TITLE
Allow accessing yaml configuration .env.xxx from lua module

### ISSUE THREAD

**Issue by ecerulm** [fluent/fluent-bit#9585]
**Is your feature request related to a problem? Please describe.**

While using [fluentbit yaml configuration](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file) you can use 

```
env:
  myvar1: myvalue1
```

but those values cannot be accessed via [lua module](https://docs.fluentbit.io/manual/pipeline/filters/lua) today, the following code **won't** work

```
          - name: lua
            call: modify
            code: |
              function modify(tag, timestamp, record)
               new_record = {}
               new_record.xxxx = env.myvar1
               return  1, timestamp, new_record
              end
```

**Describe the solution you'd like**

I would like a global variable `env` available while evaluating the lua function giving access to the things defined in the fluent configuration yaml at `.env`

**Describe alternatives you've considered**

* hard coding the values in the lua code 

**Additional context**

**Comment by edsiper** [comment]
tests are welcome: https://github.com/fluent/fluent-bit/pull/9617
