### ISSUE TITLE
Unreleased version available on packages.fluentbit.io

### ISSUE THREAD

**Issue by wouttom** [fluent/fluent-bit#9595]
## Bug Report

**Describe the bug**

According to the github-releases of the project version 3.1.10 is currently the latest release.
However at the rpm-mirror https://packages.fluentbit.io/centos/8/ version 3.2.0 has been available since November 13th.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

Only released versions are available in the main package repositories.
Development/unreleased versions should be in a separate repository.

**Screenshots**

**Your Environment**

* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
This is a released version, the issue was that the Github Release was not made due to this PR merged afterwards: https://github.com/fluent/fluent-bit/pull/9445

The docs are all updated to show 3.2 now so I'll manually create the Github Release for now to stop more concerns.

**Comment by patrick-stephens** [comment]
@edsiper we still need to run the docs update script with the hashes and the like for Windows: https://github.com/fluent/fluent-bit-docs/blob/master/update-release-version-docs.sh
