### ISSUE TITLE
cprofiles: can't compile due to incompatible-pointer-types

### ISSUE THREAD

**Issue by ThomasDevoogdt** [fluent/fluent-bit#9601]
## Bug Report

```
/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/fluent-bit-3.2.0/lib/cprofiles/src/cprof_profile.c: In function ‘cprof_profile_destroy’:
/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/fluent-bit-3.2.0/lib/cprofiles/src/cprof_profile.c:160:18: error: assignment to ‘struct cprof_mapping *’ from incompatible pointer type ‘struct cprof_location *’ [-Wincompatible-pointer-types]
  160 |         location = cfl_list_entry(iterator,
      |                  ^
/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/fluent-bit-3.2.0/lib/cprofiles/src/cprof_profile.c:166:32: error: passing argument 1 of ‘cprof_location_destroy’ from incompatible pointer type [-Wincompatible-pointer-types]
  166 |         cprof_location_destroy(location);
      |                                ^~~~~~~~
      |                                |
      |                                struct cprof_mapping *
In file included from /home/thomas/br-test-pkg/bootlin-armv7-glibc/build/fluent-bit-3.2.0/lib/cprofiles/src/cprof_profile.c:21:
/home/thomas/br-test-pkg/bootlin-armv7-glibc/build/fluent-bit-3.2.0/lib/cprofiles/include/cprofiles/cprofiles.h:304:52: note: expected ‘struct cprof_location *’ but argument is of type ‘struct cprof_mapping *’
  304 | void cprof_location_destroy(struct cprof_location *instance);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
```

**Describe the bug**

New toolchains are asserting on it.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: 3.2.0
* Configuration: Buildroot
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

@leonardo-albertovich can you have a look, since you've added this in https://github.com/fluent/fluent-bit/commit/29549089459997f16b1d8403c83d375cd58839e4?

**Comment by edsiper** [comment]
@ThomasDevoogdt thanks for this report. I have fixed the data type problem, however note that cprofiles still needs other adjustments regarding dependencies (profiles are under active development).

**Comment by ThomasDevoogdt** [comment]
> @ThomasDevoogdt thanks for this report. I have fixed the data type problem, however note that cprofiles still needs other adjustments regarding dependencies (profiles are under active development).

Hi @edsiper, I guess you didn't saw my PR https://github.com/fluent/cprofiles/pull/3, can you have a look, since that one also solves another related issue.

BTW, since it's under active development, why is it already part of the v3.2.0 stable release?

**Comment by edsiper** [comment]
@ThomasDevoogdt Didn't see your PR. Note that profiles are not stable in OTel, the feature needs to be enabled manually since it's in experimental mode.

@jeredfloyd for dependencies or external libraries that lives in lib/, the PR needs to be send to the original repository from where we pull that library, in this case is fluent/cprofiles.

**Comment by ThomasDevoogdt** [comment]
@edsiper But why is that experimental issue enabled then? See https://github.com/fluent/fluent-bit/blob/master/CMakeLists.txt#L158-L159. Btw, there is a small typo in the comment line there.

**Comment by edsiper** [comment]
@ThomasDevoogdt Because OpenTelemetry Profiles schema is **not stable**, it's still flagged as in development mode and they are still adapting it which causes breaking changes:

https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/profiles/v1development

**Comment by ThomasDevoogdt** [comment]
Fixed by https://github.com/fluent/fluent-bit/commit/4ab9331285845ced7275b923e8a3a65472e2d88a, please also read my comment here, https://github.com/fluent/cprofiles/pull/3#issuecomment-2552317890, a bit disappointing that contributions gets ignored.

**Comment by ThomasDevoogdt** [comment]
Btw, I have another compile issue, would be nice if someone could have a look at https://github.com/fluent/fluent-bit/pull/9600.
