### ISSUE TITLE
Output to InfluxDB fails with error: partial write

### ISSUE THREAD

**Issue by dmamalis** [fluent/fluent-bit#962]
## Bug Report

**Describe the bug**
Output to InfluxDB fails with error: partial write ... value out of range dropped=0

- Example log message:
```
[2018/12/14 13:51:05] [error] [out_influxdb] http_status=400
{"error":"partial write: unable to parse 'cpu_metrics,_seq=1 cpu_p=0.000000,user_p=0.000000,system_p=0.000000,cpu0.p_cpu=0.000000,cpu0.p_user=0.000000,cpu0.p_system=0.000000 18446744072560440211': strconv.ParseInt: parsing \"18446744072560440211\": value out of range\nunable to parse 'cpu_metrics,_seq=2 cpu_p=0.000000,user_p=0.000000,system_p=0.000000,cpu0.p_cpu=0.000000,cpu0.p_user=0.000000,cpu0.p_system=0.000000 18446744073561470460': strconv.ParseInt: parsing \"18446744073561470460\": value out of range dropped=0"}
```
**Your Environment**

* Version used:
v0.14.9

* Configuration:
```
[SERVICE]
    Flush   5
    Log_Level debug

[INPUT]
    #===================================================
    # CPU input plugin
    #===================================================
    Name cpu
    Tag cpu_metrics

[OUTPUT]
    Name influxdb
    Match *_metrics
    Host db.domain.com
    Port 1234
    HTTP_User sure
    HTTP_Passwd sure
    Database dbdbdb
    Sequence_Tag _seq
    tls On
    tls.verify Off
    tls.debug 1
    tls.crt_file /etc/ssl/re.crt
    tls.key_file /etc/ssl/re.key
```
* Operating System and version:
Poky (Yocto Project Reference Distro) 2.1.2 \n \l

* Filters and plugins:
Build Flags =  JSMN_PARENT_LINKS JSMN_STRICT FLB_HAVE_TLS FLB_HAVE_FLUSH_LIBCO FLB_HAVE_VALGRIND FLB_HAVE_FORK FLB_HAVE_TIMESPEC_GET FLB_HAVE_PROXY_GO FLB_HAVE_LIBBACKTRACE FLB_HAVE_C_TLS FLB_HAVE_ACCEPT4 FLB_HAVE_INOTIFY

**Additional context**
The same version, built with the same flags and same configuration has been tested successfully in desktop environment (Ubuntu 18.04). Then the project is being built against [the toolchain](https://www.lorixone.io/yocto/sdk/2.1.2/poky-wifx-glibc-x86_64-wifx-base-sdk-cortexa5hf-neon-toolchain-2.1.2.tar.bz2)

**Comment by edsiper** [comment]
Please test our Fluent Bit dev version 1.1.x using the following docs:

https://docs.fluentbit.io/manual/installation/yocto

**Comment by dmamalis** [comment]
I can verify that the problem has not appeared in my set up.

However, there are still issues with the build process. Onigmo needs to be disabled and disabling Lua is not enough since the module seems to be used in many more modules.
In the recipe, LUAJIT, FILTER_LUA, SHARED_LIB and EXAMPLES is switched off but there are more modules which need to be off for the build process to work.

I follow the cmake build process and I had to confifure the following to be able to build.
```cmake -DGNU_HOST=${HOST_SYS} -DFLB_LUAJIT=Off -DFLB_FILTER_LUA=Off -DFLB_SHARED_LIB=Off -DFLB_EXAMPLES=Off -DFLB_REGEX=Off -DFLB_PARSER=Off -DFLB_IN_TAIL=Off -DFLB_FILTER_GREP=Off -DFLB_FILTER_PARSER=Off -DFLB_IN_EXEC=Off -DFLB_IN_SYSLOG=Off -DFLB_IN_STDIN=Off ../
```

Last but not least, JEMALLOC seems to be giving a segmentation fault on the target device. I will come back with more info as soon as I have some.
