### ISSUE TITLE
Recent update broke Fluent-bit on all my VMs

### ISSUE THREAD

**Issue by jxk435** [fluent/fluent-bit#9623]
## Bug Report

**Describe the bug**
I was writing an install script to automate the install process for Fluent-bit and it seemed to work perfectly. I ran it in prod around 2:10pm right after running updates/upgrades on the ubuntu 24.04 VMs, but after installing and checking the systemctl status fluent-bit.service, all the boxes failed to install fluent-bit. I tried installing manually per the fluent-bit instructions (did not use the single line installer) found here [https://docs.fluentbit.io/manual/installation/linux/ubuntu] but the actually install step produced an error about dependencies. This appears to have stopped working after the latest fluent-bit update that got deployed 10 minutes before I ran my scripts. I have our root cert in place, ran update-ca-certificates, the fluent-bit GPG key is installed, added to sources.list.d, ran apt update, and the install fails. 

I have also tried installing the below packages named in the error but they cannot be found. 

**To Reproduce**
- Rubular link if applicable: N/A
- Example log message if applicable:
```
$ sudo apt install fluent-bit
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fluent-bit : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.8 is to be installed
              Depends: libsasl2-2 (>= 2.1.28+dfsg1) but 2.1.27+dfsg2-3ubuntu1.2 is to be installed
              Depends: libssl3t64 (>= 3.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
- Steps to reproduce the problem:

**Expected behavior**
Expected fluent-bit to install the latest version successfully through apt install command

**Screenshots**
N/A, error added above

**Your Environment**

* Version used: Latest fluent-bit version deployed
* Configuration: ?
* Environment name and version (e.g. Kubernetes? What version?): Azure VM? 
* Server type and version: Running on Azure VM
* Operating System and version: Ubuntu 24.04.5 LTS Jammy Jellyfish
* Filters and plugins: N/A, vanilla install

**Additional context**
This is going to be used on several load balanced VMs and I am pushing configs and commands uniformly through Ansible. Testing on an Ubuntu 22.04 VM with same configs but previous ubuntu version. Both 24 and 22 ubuntu are having the same issues.

**Comment by jxk435** [comment]
After running updates and patching that has appeared since Monday, I can install Fluent-bit successfully on the ubuntu 24.04 boxes, but right after install, Fluent-bit fails to start and I see this error:

```
systemctl status fluent-bit.service
× fluent-bit.service - Fluent Bit
     Loaded: loaded (/usr/lib/systemd/system/fluent-bit.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-11-20 14:23:51 UTC; 11s ago
   Duration: 1.025s
       Docs: https://docs.fluentbit.io/manual/
    Process: 18419 ExecStart=/opt/fluent-bit/bin/fluent-bit -c //etc/fluent-bit/fluent-bit.conf (code=exited, status=255/EXCEPTION)
   Main PID: 18419 (code=exited, status=255/EXCEPTION)
        CPU: 25ms
```

On the Ubuntu 22.04 VM, after running updates and patches, Fluent-bit still will not install with the error in the original post

**Comment by lecaros** [comment]
Hi @jxk435 
is this still an issue for you?
if you have detailed steps you followed that would be great to use as a reproducer

Thanks

**Comment by jxk435** [comment]
Good morning. It turns out that there was an error in the parsers.conf file. My Sr. Engineer had started a new parser and the regex was not completed. I copied this unknowingly and it seemed to have broken Fluent-bit. 

On my Ubuntu 22 box, I was not able to fix the installation issue, but after upgrading to ubuntu 24, it was resolved and installed as expected. 

Thank you.
