### ISSUE TITLE
[File Output] support JSON format

### ISSUE THREAD

**Issue by erks** [fluent/fluent-bit#964]
**Is your feature request related to a problem? Please describe.**
Cannot configure `File` output with `JSON` format (`fluentd` can do it via `formatter_json`).

**Describe the solution you'd like**
Add support for `JSON` format to `File` output

**Describe alternatives you've considered**
Switch to `fluentd`

**Additional context**

**Comment by edsiper** [comment]
Json output is supported by 'Format plain' option. Give it a try.

**Comment by erks** [comment]
@edsiper thanks a lot, although, it doesn't seem to be documented.
