### ISSUE TITLE
Routing is forward matched

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#967]
## Bug Report

**Describe the bug**
Routing is broken at master.

**To Reproduce**
b.conf
```python
[INPUT]
    Name dummy
    Tag  hoge
    dummy {"log":"this is a pen"}

[FILTER]
    Name grep
    Match hogeeeeeeeeeeee
    Regex log that

[OUTPUT]
    Name stdout
    Match *
```

fluent-bit will never output. This means filter_grep is forward matched.
 (The tag is "hoge" , but "hogeeeeeeeeeeee" is matched.)
```
$ ../bin/fluent-bit -c b.conf 
Fluent Bit v1.1.0
Copyright (C) Treasure Data

[2018/12/17 23:45:53] [ info] [storage] initializing...
[2018/12/17 23:45:53] [ info] [storage] in-memory
[2018/12/17 23:45:53] [ info] [storage] normal synchronization mode, checksum disabled
[2018/12/17 23:45:53] [ info] [engine] started (pid=16377)
^C[engine] caught signal (SIGINT)
[2018/12/17 23:46:25] [ info] [input] pausing dummy.0
```

**Expected behavior**
v0.14.9 is working correctly.
```
$ ../bin/fluent-bit -c b.conf 
Fluent-Bit v0.14.9
Copyright (C) Treasure Data

[2018/12/17 23:42:40] [ info] [engine] started (pid=13279)
[0] hoge: [1545057761.001764655, {"log"=>"this is a pen"}]
[1] hoge: [1545057762.001743602, {"log"=>"this is a pen"}]
[2] hoge: [1545057763.001826758, {"log"=>"this is a pen"}]
[3] hoge: [1545057764.001882592, {"log"=>"this is a pen"}]
^C[engine] caught signal (SIGINT)
```

**Screenshots**
none

**Your Environment**

* Version used: v1.1.0 (master)
* Configuration:   see above.
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: CentOS6 
* Filters and plugins: see above.

**Additional context**
v.0.14.9 is working and v1.1.0 is broken.
I think #918 and some recent commits  are affected.

**Comment by edsiper** [comment]
thanks for reporting this @nokute78 . I am troubleshooting the issue now. 

I've added a test case to tests/internal router: 87c4dff0

**Comment by edsiper** [comment]
Looks like the problem goes away changing:

```c
else if (off + 1 >= tag_len) {
```
https://github.com/fluent/fluent-bit/blob/master/src/flb_router.c#L86

by 

```c
else if (off  >= tag_len) {
```

@nokute78 would you please test with that change ? (it worked fine here but if you have more tests would be useful)

**Comment by edsiper** [comment]
with that change in passes the internal test but most of runtime tests breaks.

**Comment by nokute78** [comment]
The patch is LGTM. But I don't know why runtime tests are broken.

This ret is 0 so the test will be failed.
I think it is timing issue.
```C
    while ( (ret = get_result()) == 0 && (time_in_ms() - start < 4000))
        usleep(10);
    ret = get_result(); /* 1sec passed, data should be flushed */
    TEST_CHECK(ret > start + 900 && ret < start + 4000);
```

**Comment by edsiper** [comment]
I am still stuck in that too, the internal tests works, but runtime do not
find matches

**Comment by nokute78** [comment]
@edsiper I sent a PR, but it conflicts.

**Comment by nokute78** [comment]
I fixed conflict.

**Comment by edsiper** [comment]
The issue is already fixed in master (last night), would u please double
check?

**Comment by nokute78** [comment]
@edsiper Thanks. The issue is fixed in master.
So close this issue and drop my PR.
