### ISSUE TITLE
Publish windows images under the same tag

### ISSUE THREAD

**Issue by jbiers** [fluent/fluent-bit#9678]
**Is your feature request related to a problem? Please describe.**
I want to be able pull the fluent-bit image from Dockerhub without specifying Windows 2019 or Windows 2022, letting the runtime choose which one should be used.

**Describe the solution you'd like**
At SUSE we have a repo which takes the images from the fluent-bit project and adds a [Docker Manifest](https://docs.docker.com/reference/cli/docker/manifest/) to it to publish in our registry. As a result, we have both windows images published under the same tag ([reference](https://hub.docker.com/r/rancher/fluent-bit/tags)). It would be useful if fluent-bit itself implemented this logic.

**Comment by patrick-stephens** [comment]
This is already a request: https://github.com/fluent/fluent-bit/issues/9509
I'm going to close this so it is tracked there.
