### ISSUE TITLE
Require namespace-Level RoleBindings in Fluent Bit configuration to restrict Cluster-level access

### ISSUE THREAD

**Issue by sourabh507** [fluent/fluent-bit#9716]
**Is your feature request related to a problem? Please describe.**
To avoid providing cluster-level access, we need to abstract permissions by assigning roles at the `namespace` level. For this purpose, we require a `RoleBinding` in the Fluent Bit configuration.

**Describe the solution you'd like**
A `RoleBinding` grants the permissions defined in a Role to a user or set of users within a specific namespace. This ensures that users have the necessary permissions to perform their tasks without having broader access to the entire cluster.

**Comment by patrick-stephens** [comment]
Should this be on the helm chart? This repo has no specific requirements for K8S or is this specific to a plugin?

**Comment by sourabh507** [comment]
> Should this be on the helm chart? This repo has no specific requirements for K8S or is this specific to a plugin?

yes it should be there on the helm chart repo, let me create same issue there
