### ISSUE TITLE
Can't parse plugins.conf anymore

### ISSUE THREAD

**Issue by dlutz** [fluent/fluent-bit#9729]
## Bug Report

**Describe the bug**
Version `3.2.0` seems to have introduced a bug affecting parsing the file `plugins.conf` using the classic configuration. Parsing a file based on the example https://github.com/fluent/fluent-bit/blob/master/conf/plugins.conf doesn't work anymore.

Commit https://github.com/fluent/fluent-bit/commit/6611a0606dbff391ba2b8b311f9112c1bd6cbfe2 introduced the new function `flb_plugin_load_config_format`, which uses `entry->key` instead of `entry->val->data.as_string` (as in `flb_plugin_load_config_file`). fluent-bit then tries to load the plugin from the path `path` (i.e. the keyword `path`) instead of the effective path from the configuration.

**To Reproduce**
- Example log messages:
```
Dec 12 14:29:33 (redacted) fluent-bit[124779]: [2024/12/12 14:29:33] [error] [proxy] error opening plugin path: 'path: cannot open shared object file: No such file or directory'
Dec 12 14:29:33 (redacted) fluent-bit[124779]: [2024/12/12 14:29:33] [error] [plugin] error loading proxy plugin: path
```
- Steps to reproduce the problem:
  -  Use classic configuration
  - Include `plugins.conf` from `fluent-bit.conf` (`plugins_file plugins.conf`)
  - Use `plugins.conf` like this (based on the example https://github.com/fluent/fluent-bit/blob/master/conf/plugins.conf)
```
[PLUGINS]
    # Path /path/to/out_gstdout.so
    Path /usr/local/lib/out_some_plugin.so
```

**Expected behavior**
The plugin should be loaded as before 3.2.0.

**Screenshots**
N/A

**Your Environment**
* Version used: 3.2.2
* Configuration: Classic configuration (with `plugins.conf` file)
* Environment name and version: VM based on Linux
* Operating System and version: RHEL 8.10
* Filters and plugins: Trying to use custom plugin

**Additional context**
Loading the plugin worked before 3.2.0. With 3.2.0, fluent-bit doesn't start but logs an error. (Loading the plugion with the `-e` command line option instead of using `plugins.conf` works.)

**Comment by Swaagie** [comment]
Can confirm, we ran into the same issue last week. Changing to YAML based configuration made it clear why this failed as the error message itself is also easily misinterpreted. Spend quite some time to understand what Fluentbit was really trying to tell me 😅
