### ISSUE TITLE
kmsg plugin doesn't work

### ISSUE THREAD

**Issue by bbkgh** [fluent/fluent-bit#974]
## Bug Report

**Describe the bug**
Kmsg Plugin doesn't work. I am using fluent/fluent-bit Docker image.
This command 
`fluent-bit -i kmsg -t kernel -o stdout -m '*'`
outputs:
Fluent-Bit v0.14.9
Copyright (C) Treasure Data

[2018/12/18 14:00:23] [ info] [engine] started (pid=18619)
[2018/12/18 14:00:23] [error] [plugins/in_kmsg/in_kmsg.c:287 errno=2] No such file or directory
[2018/12/18 14:00:23] [error] Failed initialize input kmsg.0

**Comment by edsiper** [comment]
In a container, not all system resources are exposed, you have to do it manually, e.g:

```
$ docker run -ti --device=/dev/kmsg fluent/fluent-bit /fluent-bit/bin/fluent-bit -i kmsg -o stdout -f 1
```

the above command will expose /dev/kmsg device (which is used by kmsg plugin) and run fluent bit
