### ISSUE TITLE
Filter chaining do not work in 1.0.0

### ISSUE THREAD

**Issue by nikinaydenov** [fluent/fluent-bit#975]
## Bug Report

**Describe the bug**
Filter chaining is broken in 1.0.0

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
echo '{"key1": 123456789, "message": "[info]", "to_remove": "this"}' | /opt/td-agent/embedded/bin/fluent-cat my_tag
```
- Steps to reproduce the problem:
Simple setup with config:
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    #Plugins_File plugins.conf
    HTTP_Server  Off

[INPUT]
    Name        forward
    Listen      127.0.0.1
    Port        24224
    Chunk_Size  32  
    Buffer_Size 64  

[FILTER]
    Name   modify
    Match  *
    Rename message suobshtenie
    Rename key1 kluch1

#[FILTER]
#    Name       record_modifier
#    Match      *
#    Remove_key to_remove
#    Record sourcetype journald

#[FILTER]
#    Name   lua
#    Match  *
#    script remove_color.lua
#    call   rmcolor

[OUTPUT]
    Name  stdout
    Match *
```

**Expected behavior**
Timestamp to be correct. Fluent-bit to pass the message through all filters in order they are described in the configuration file. Do not crash with SEGV

**Screenshots**
With the above config:
```
echo '{"key1": 123456789, "message": "[info]", "to_remove": "this"}' | /opt/td-agent/embedded/bin/fluent-cat my_tag

[0] my_tag: [1545149467.416087419, {"kluch1"=>123456789, "suobshtenie"=>"[info]", "to_remove"=>"this"}]
```
Works fine: the two keys are renamed. Now uncomment the whole record modifier section and issue the same command:
```
[0] my_tag: [2192572464.000000047, {"key1"=>123456789, "message"=>"[info]", "sourcetype"=>"journald"}]
```
Record_modifier works, but not modify. Also notice the timestamp
Issue few times the same command:
```
echo '{"key1": 123456789, "message": "[info]", "to_remove": "this"}' | /opt/td-agent/embedded/bin/fluent-cat my_tag
echo '{"key1": 123456789, "message": "[info]", "not_to_remove": "that"}' | /opt/td-agent/embedded/bin/fluent-cat my_tag
echo '{"key1": 123456789, "message": "[info]", "to_remove": "this"}' | /opt/td-agent/embedded/bin/fluent-cat my_tag
echo '{"key1": 123456789, "message": "[info]", "to_remove": "this"}' | /opt/td-agent/embedded/bin/fluent-cat my_tag

[2018/12/18 18:22:08] [ info] [in_fw] binding 127.0.0.1:24224
[0] my_tag: [104.000000000, {"key1"=>123456789, "message"=>"[info]", "sourcetype"=>"journald"}]
[0] my_tag: [1545150140.337405943, {"kluch1"=>123456789, "suobshtenie"=>"[info]", "not_to_remove"=>"that"}]
[2018/12/18 18:22:44] [ warn] unknown time format 5
[0] my_tag: [104.000000000, {"key1"=>123456789, "message"=>"[info]", "sourcetype"=>"journald"}]
[1] my_tag: [1545150165.981431341, {"kluch1"=>123456789, "suobshtenie"=>"[info]", "to_remove"=>"this"}]
```
The last two lines should give the same wrong output, but even that do not works - the output depends probably from the content of some buffer that still have part pf the previous message.

Now reorder modify and record_modifier and issue the same command:
```
[engine] caught signal (SIGSEGV)
ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)ERROR: no debug info in ELF executable (-1)Aborted (core dumped)
```
Now try enabling Lua. Crash and other weird things: sometimes it looks like the lua receive nil on place of the record table. 

**Your Environment**
* Version used: 1.0.0
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): 
* Server type and version: Laptop
* Operating System and version: Ubuntu 18.0.4. Probably crash on RHEL as well 
* Filters and plugins: modify, record_modifier, lua

**Additional context**
In this shape fluet-bit is completely unusable. I test with the docker image which install 1.1.0 despite the tag is 1.0.0. Similar results but even more weird. 
In case you need more tests just let me know.

**Comment by bayaro** [comment]
Hi, maybe it'll help.

In may case I use 
`[PARSER]
    Name syslog-msg
    Format json`

`[INPUT]
    Name tail
    Path /tmp/zzz.log

[FILTER]  # F1
    Name parser
    Match *
    Key_Name log
    Reserve_Data True
    Parser syslog-msg

[FILTER] # F2
    Name record_modifier
    Match *
    Record env local

[OUTPUT]
    Name file
    Match *
    Path /tmp/xxx.log
`

And only one filter is processed, the first one. Just exchange the order of F1 & F2 to F2 -> F1 and only F2 will be processed.

I can suggest that at https://github.com/fluent/fluent-bit/blob/master/src/flb_filter.c#L99
cb_filter returns zero in out_size.

**Comment by edsiper** [comment]
thanks for the feedback, currently working in the issue (I was able to reproduce it)

**Comment by bayaro** [comment]
Could you please share the spec file for rpm build. So I'll have a possibility to build it from source and make some investigation. Currently I couldn't collect all dependencies.
Also if it is possible may you share the link to previous version rpm?

**Comment by edsiper** [comment]
I've pushed a fix into GIT Master that address the issue, would you please both test it?

to build the RPM just use 'cpack' command (ref: https://cmake.org/cmake/help/v3.7/module/CPackRPM.html)

**Comment by bayaro** [comment]
Sorry, I'm no so familiar with building.
```
lib/monkey/mk_core/../include/monkey/mk_core/mk_dep_unistd.h:12:16: fatal error: io.h: No such file or directory
 #include <io.h>
```
as I found io.h should not be used in linux?
Unfortunatelly I do not know which key should be used to "undefine" it.

cpack with `-G RPM` fails on the same postion

**Comment by bayaro** [comment]
IT was a problem with cmake cache ....
I have successfully build the 4995c58ec6a102b.

Both filters were successfully processed. Thank you.

**Comment by nikinaydenov** [comment]
Ok guys, I build it from master. Looks like the problem is solved. Tested with modify, record_modifier and lua (changing the value) - works in simple test with forward input and dummy input. Will continue digging and testing in real environment (real data from my test environment).

**Comment by nikinaydenov** [comment]
Can be I do not build it right, but now I receive this with systemd input on Ubuntu 18.0.4:
```
root@niki-pc:/etc/td-agent-bit# /opt/td-agent-bit/bin/fluent-bit -c /etc/td-agent-bit/td-agent-bit.conf 
Fluent Bit v1.1.0
Copyright (C) Treasure Data

Input plugin 'systemd' cannot be loaded
Error: You must specify an output target. Aborting
```
I can open another ticket if that helps

**Comment by edsiper** [comment]
thanks. I will backport the changes for the next release.

Fixed

**Comment by servo1x** [comment]
@nikinaydenov can you share your remove color lua script?

**Comment by jesk78** [comment]
Still not working for me in 1.0.4 (CentOS 7 package).
