### ISSUE TITLE
Redirect on other output in case of parsing failure

### ISSUE THREAD

**Issue by Theoooooo** [fluent/fluent-bit#978]
**Is your feature request related to a problem? Please describe.**
When you setup a parsing regex, if a parsing failed i don't know which message failed and i can't have a trace of what happened. If i could see which message failed to get parsed, i will modify my regex to make it work with the message who failed to get parsed.

**Describe the solution you'd like**
I would like to have the option to redirect to another output when a parsing failed.
Like in the parsing or in the config file, set a Failed_Redirection option to set a output redirection when the parsing failed. This will redirect the failed parsing to another [INPUT] which allow to get though another parsing and another output behind.

**Describe alternatives you've considered**
I didn't found any alternative to my problem but maybe i didn't do the good researches.

**Additional context**
If a message failed to parse, i can't see which message failed and i need to setup a debug output with the full message output for a long time to see all the message and trying to figure out which message failed to get parsed. It's just a lot of time of waiting

I don't really have a screenshoot to join, i think the problem is self-explanatory

**Comment by burandobata** [comment]
+1
it would be good to be able to mark not parsed messages. E.g. by adding some on-failure logic/field.
