### ISSUE TITLE
td-agent-bit.conf dont preserved on RPM package upgrades

### ISSUE THREAD

**Issue by evgkrsk** [fluent/fluent-bit#980]
## Bug Report

**Describe the bug**
After upgrade to td-agent-bit-1.0.0-1.x86_64 my /etc/td-agent-bit/td-agent-bit.conf is lost (replaced by bundled/default version), so logs shipping is silently broken.

**To Reproduce**
- install td-agent-bit-0.14.8-1.x86_64
- edit default td-agent-bit.conf
- upgrade to td-agent-bit-1.0.0-1.x86_64
- look at contents of td-agent-bit.conf

**Expected behavior**
- hand-written td-agent-bit.conf must be preserved during package upgrades
- td-agent-bit.conf must be marked as config(noreplace) in rpm spec file

**Your Environment**
* Versions used: 0.14.8-1 and 1.0.0-1
* Configuration: hand-written
* Operating System and version: Centos 7.6

**Comment by evgkrsk** [comment]
N.B.: parsers.conf also affected by this issue.

**Comment by chsnell** [comment]
It's probably just missing the (noreplace) item on the %config line, but I can't find the wider RPM spec file within this repository.  Is that something only in td's fork that's not publicly available?

**Comment by nicosto** [comment]
This issue still present in the v1.1.1

**Comment by apollo13** [comment]
It looks like this was fixed with https://github.com/fluent/fluent-bit/commit/e6c9468df5bb709d52bd4ec7a155517c2d1903c5#diff-af3b638bc2a3e6c650974192a53c7291R681

**Comment by edsiper** [comment]
Yes, fixed in v1.3 release
