### ISSUE TITLE
Fluent-bit adds characters (\u0000\u0000\u0000) at the end of the tag when the storage.type filesystem option is used

### ISSUE THREAD

**Issue by lcrash** [fluent/fluent-bit#995]
## Bug Report

**Describe the bug**
Fluent-bit adds characters (\u0000\u0000\u0000) at the end of the tag when the storage.type filesystem option is used

**To Reproduce**
- Example log message if applicable:
tag=metrics-server-5cbc77f79f-4trrv_kube-system_metrics-server-1cba1794431e212431086117289e3b5943bee3dedeed5f77952a4872df37d377.log\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u00

- Steps to reproduce the problem:
[SERVICE]
Flush         1
Grace         30
Log_Level   info
Daemon        off
Parsers_File  parsers.conf
HTTP_Server. On
HTTP_Listen   0.0.0.0
HTTP_Port     2020
storage.path              /var/log/flb-storage/
storage.sync              full
storage.checksum          on
storage.backlog.mem_limit 5M

    [INPUT]
        Name              tail
        Tag               AMS.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  5
        Docker_Mode       On
        Docker_Mode_Flush 10
        storage.type    filesystem

**Your Environment**
* Version used: Fluent-Bit 1.0.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):

AKS version 1.11.5

**Comment by lcrash** [comment]
From FluentD logs 

#0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: invalid_index_name_exception [reason]: 'Invalid index name [metrics-server-5cbc77f79f-4trrv_kube-system_metrics-server-1cba1794431e212431086117289e3b5943bee3dedeed5f77952a4872df37d377.log\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\

**Comment by edsiper** [comment]
@lcrash I am trying to reproduce the problem without success. 

Would you please provide your full Kubernetes Configmap ?

**Comment by yann-soubeyrand** [comment]
Hi!

We are affected by the same bug.

Here is our ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush                          15
        Log_Level                      info
        Parsers_File                   parsers.conf
        Storage.Path                   /var/lib/fluent-bit/buffer/
        HTTP_Server                    On
        HTTP_Listen                    0.0.0.0
        HTTP_Port                      2020

    [INPUT]
        Name                           tail
        Path                           /var/log/containers/*.log
        Parser                         docker
        Tag_Regex                      ^(?<pod>.+)_(?<namespace>.+)_(?<container>.+)-(?<docker_id>[a-f0-9]{64})\.log$
        Tag                            kubernetes.development.<namespace>.<pod>.<container>
        Refresh_Interval               15
        Skip_Long_Lines                On
        DB                             /var/lib/fluent-bit/in_tail.db
        Storage.Type                   Filesystem

    [FILTER]
        Name                           kubernetes
        Match                          kubernetes.*
        Regex_Parser                   kubernetes-tag
        Kube_URL                       https://kubernetes.default.svc.cluster.local:443
        Merge_Log                      On
        K8S-Logging.Exclude            On
        K8S-Logging.Parser             On

    [OUTPUT]
        Name                           forward
        Match                          *
        Host                           fluentd
        Retry_Limit                    False
  parsers.conf: |
    [PARSER]
        Name                           docker
        Format                         json
        Time_Key                       time
        Time_Format                    %Y-%m-%dT%H:%M:%S.%L%z
        Decode_Field_As                escaped log

    [PARSER]
        Name                           kubernetes-tag
        Format                         regex
        Regex                          ^kubernetes\.[^.]+\.(?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)$
```

**Comment by edsiper** [comment]
@yann-soubeyrand can you attach a simple log file from your environment (/var/log/containers/..) ?, I want to try to reproduce locally

**Comment by lcrash** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================

  fluent-bit.conf: |
    [SERVICE]
        Flush           1
        Grace           30
        Log_Level       info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path              /var/log/flb-storage/
        storage.sync              full
        storage.checksum          on
        storage.backlog.mem_limit 5M
        

    @INCLUDE filter-kubernetes.conf
    @INCLUDE input-kubernetes.conf
    @INCLUDE output-forward.conf

  upstream-kubernetes.conf: |
    [UPSTREAM]
        name            forward-balancing

    [NODE]
        name            fluentd-0
        host            fluentd-0
        port            24224
        Shared_Key      fluentd
        Self_Hostname   fluentd
        tls             on
        tls.verify      off

    [NODE]
        name            fluentd-1
        host            fluentd-1
        port            24224
        Self_Hostname   fluentd
        tls             on
        tls.verify      off

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               AMS.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  5
        Docker_Mode       On
        Docker_Mode_Flush 10
        storage.type    filesystem

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               AMS.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        K8S-Logging.Parser  On

  output-forward.conf: |

    [OUTPUT]
        name            forward
        Match           *
        Upstream        /fluent-bit/etc/upstream-kubernetes.conf
        Retry_Limit     false

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped_utf8    log

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S


The issue is when there is a problem with connection to FluentD (Output forward)

**Comment by edsiper** [comment]
Fixed by https://github.com/fluent/fluent-bit/commit/e04001ec612c94ca4d2cc3d92f5514ebe6883702

thanks everyone for the help.

**Comment by edsiper** [comment]
FYI: fix included in v1.0.2 release.
