### ISSUE TITLE
yum install creates /etctd-agent-bit directory in root filesystem

### ISSUE THREAD

**Issue by JungleGenius** [fluent/fluent-bit#996]
yum install creates "/etctd-agent-bit" directory in root filesystem.

rpm package version  "td-agent-bit-1.0.1-1.x86_64".

Looks like the install script was trying to use this path "/etc/td-agent-bit" but there is a typo someplace.

Maybe related to this message: [Warning] [config] I cannot open /etc/td-agent-bit/plugins.conf file

Thanks!

**Comment by edsiper** [comment]
Fixed by d4a3300e

**Comment by JungleGenius** [comment]
Thanks...
