### ISSUE TITLE
fluent-bit couldn't tail file in docker/pod 

### ISSUE THREAD

**Issue by yangsongx** [fluent/fluent-bit#997]
## Bug Report

**Describe the bug**
fluent-bit couldn't keep tail-ing file in docker/pod 

I meet a very weird issue, I just want to tail file log.

Every time I run fluent-bit at the first time in  a docker, it works fine. But after that, it can't keep tailing the file contents anymore, event I keep appending many data into that log file!

**To Reproduce**
- run fluent-bit in a docker/Pod (it works ok under normal Linux host)
- `fluent-bit -i tail -p path=/tmp/foo.log -o stdout -vvv`
- keep appending the log via `echo 'hello' >>/tmp/foo.log`
- Steps to reproduce the problem:

**Expected behavior**
We should see the output on the screen.

At the startup ,it print out the tail of the file, but after that, it won't output any text data, though I keep appending many many text data(of course, they are line-by-line, not a single line text) to that log file!

This happend in Docker, and it works fine in a normal Linux host.

Did anyone meet the same issue as mine?
**Screenshots**

**Your Environment**

* Version used: 1.0.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): run it in Docker
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by dkarthi** [comment]
The suggested fix "docker run -it --log-opt mode=non-blocking" not working for me ..
